// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --version 6


// RUN: %clang_cc1 -O0  -fbounds-safety -triple x86_64 -emit-llvm %s -o - | FileCheck --check-prefix=CHECK-O0 %s
// RUN: %clang_cc1 -O2  -fbounds-safety -triple x86_64 -emit-llvm %s -o - | FileCheck --check-prefix=CHECK-O2 %s
// RUN: %clang_cc1 -O2  -fbounds-safety -triple arm -emit-llvm %s -o - | FileCheck --check-prefix=CHECK-ARM-O2 %s
// RUN: %clang_cc1 -O0  -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -triple x86_64 -emit-llvm %s -o - | FileCheck --check-prefix=CHECK-O0 %s
// RUN: %clang_cc1 -O2  -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -triple x86_64 -emit-llvm %s -o - | FileCheck --check-prefix=CHECK-O2 %s
// RUN: %clang_cc1 -O2  -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -triple arm -emit-llvm %s -o - | FileCheck --check-prefix=CHECK-ARM-O2 %s

#include <ptrcheck.h>
// CHECK-O0-LABEL: define dso_local i32 @main(
// CHECK-O0-SAME: ) #[[ATTR0:[0-9]+]] {
// CHECK-O0-NEXT:  [[ENTRY:.*:]]
// CHECK-O0-NEXT:    [[RETVAL:%.*]] = alloca i32, align 4
// CHECK-O0-NEXT:    [[ARR:%.*]] = alloca [10 x i32], align 16
// CHECK-O0-NEXT:    [[UPTR:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[BPTR:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.indexable", align 8
// CHECK-O0-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    [[AGG_TEMP6:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// CHECK-O0-NEXT:    store i32 0, ptr [[RETVAL]], align 4
// CHECK-O0-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARR]], i64 0, i64 0
// CHECK-O0-NEXT:    [[UPPER:%.*]] = getelementptr inbounds i32, ptr [[ARRAYDECAY]], i64 10
// CHECK-O0-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[ARRAYDECAY]], ptr [[TMP0]], align 8
// CHECK-O0-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[UPPER]], ptr [[TMP1]], align 8
// CHECK-O0-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[ARRAYDECAY]], ptr [[TMP2]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2, {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    [[TMP3:%.*]] = icmp uge ptr [[WIDE_PTR_PTR]], [[WIDE_PTR_LB]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP3]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT]]:
// CHECK-O0-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[UPTR]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_PTR]], ptr [[TMP4]], align 8
// CHECK-O0-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[UPTR]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_UB]], ptr [[TMP5]], align 8
// CHECK-O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[UPTR]], i64 16, i1 false)
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP1]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR3:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR2]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.indexable", ptr [[AGG_TEMP1]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB5:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR4]], align 8
// CHECK-O0-NEXT:    [[TMP6:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[BPTR]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_PTR3]], ptr [[TMP6]], align 8
// CHECK-O0-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[BPTR]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_UB5]], ptr [[TMP7]], align 8
// CHECK-O0-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[BPTR]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[WIDE_PTR_PTR3]], ptr [[TMP8]], align 8
// CHECK-O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[TMP]], ptr align 8 [[BPTR]], i64 24, i1 false)
// CHECK-O0-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// CHECK-O0-NEXT:    [[TMP10:%.*]] = load ptr, ptr [[TMP9]], align 8
// CHECK-O0-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i32, ptr [[TMP10]], i64 -1
// CHECK-O0-NEXT:    [[TMP11:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[BPTR]], i32 0, i32 0
// CHECK-O0-NEXT:    store ptr [[BOUND_PTR_ARITH]], ptr [[TMP11]], align 8
// CHECK-O0-NEXT:    [[TMP12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// CHECK-O0-NEXT:    [[TMP13:%.*]] = load ptr, ptr [[TMP12]], align 8
// CHECK-O0-NEXT:    [[TMP14:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[BPTR]], i32 0, i32 1
// CHECK-O0-NEXT:    store ptr [[TMP13]], ptr [[TMP14]], align 8
// CHECK-O0-NEXT:    [[TMP15:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// CHECK-O0-NEXT:    [[TMP16:%.*]] = load ptr, ptr [[TMP15]], align 8
// CHECK-O0-NEXT:    [[TMP17:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[BPTR]], i32 0, i32 2
// CHECK-O0-NEXT:    store ptr [[TMP16]], ptr [[TMP17]], align 8
// CHECK-O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP6]], ptr align 8 [[BPTR]], i64 24, i1 false)
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR_ADDR7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP6]], i32 0, i32 0
// CHECK-O0-NEXT:    [[WIDE_PTR_PTR8:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR7]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_UB_ADDR9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP6]], i32 0, i32 1
// CHECK-O0-NEXT:    [[WIDE_PTR_UB10:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR9]], align 8
// CHECK-O0-NEXT:    [[WIDE_PTR_LB_ADDR11:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP6]], i32 0, i32 2
// CHECK-O0-NEXT:    [[WIDE_PTR_LB12:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR11]], align 8
// CHECK-O0-NEXT:    [[TMP18:%.*]] = icmp ult ptr [[WIDE_PTR_PTR8]], [[WIDE_PTR_UB10]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP18]], label %[[CONT14:.*]], label %[[TRAP13:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP13]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT14]]:
// CHECK-O0-NEXT:    [[TMP19:%.*]] = icmp uge ptr [[WIDE_PTR_PTR8]], [[WIDE_PTR_LB12]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    br i1 [[TMP19]], label %[[CONT16:.*]], label %[[TRAP15:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O0:       [[TRAP15]]:
// CHECK-O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// CHECK-O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O0:       [[CONT16]]:
// CHECK-O0-NEXT:    [[TMP20:%.*]] = load i32, ptr [[WIDE_PTR_PTR8]], align 4
// CHECK-O0-NEXT:    ret i32 [[TMP20]]
//
// CHECK-O2-LABEL: define dso_local i32 @main(
// CHECK-O2-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-O2-NEXT:  [[ENTRY:.*:]]
// CHECK-O2-NEXT:    [[ARR:%.*]] = alloca [10 x i32], align 16
// CHECK-O2-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[ARR]]) #[[ATTR3:[0-9]+]]
// CHECK-O2-NEXT:    [[UPPER:%.*]] = getelementptr inbounds nuw i8, ptr [[ARR]], i64 40
// CHECK-O2-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i8, ptr [[ARR]], i64 -4
// CHECK-O2-NEXT:    [[TMP0:%.*]] = icmp ult ptr [[BOUND_PTR_ARITH]], [[UPPER]], {{!annotation ![0-9]+}}
// CHECK-O2-NEXT:    [[TMP1:%.*]] = icmp uge ptr [[BOUND_PTR_ARITH]], [[ARR]], {{!annotation ![0-9]+}}
// CHECK-O2-NEXT:    [[OR_COND:%.*]] = and i1 [[TMP0]], [[TMP1]], {{!annotation ![0-9]+}}
// CHECK-O2-NEXT:    br i1 [[OR_COND]], label %[[CONT14:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-O2:       [[TRAP]]:
// CHECK-O2-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-O2-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-O2:       [[CONT14]]:
// CHECK-O2-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[ARR]]) #[[ATTR3]]
// CHECK-O2-NEXT:    ret i32 undef
//
// CHECK-ARM-O2-LABEL: define dso_local arm_aapcscc i32 @main(
// CHECK-ARM-O2-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// CHECK-ARM-O2-NEXT:  [[ENTRY:.*:]]
// CHECK-ARM-O2-NEXT:    [[ARR:%.*]] = alloca [10 x i32], align 4
// CHECK-ARM-O2-NEXT:    call void @llvm.lifetime.start.p0(ptr nonnull [[ARR]]) #[[ATTR3:[0-9]+]]
// CHECK-ARM-O2-NEXT:    [[UPPER:%.*]] = getelementptr inbounds nuw i8, ptr [[ARR]], i32 40
// CHECK-ARM-O2-NEXT:    [[BOUND_PTR_ARITH:%.*]] = getelementptr i8, ptr [[ARR]], i32 -4
// CHECK-ARM-O2-NEXT:    [[TMP0:%.*]] = icmp ult ptr [[BOUND_PTR_ARITH]], [[UPPER]], {{!annotation ![0-9]+}}
// CHECK-ARM-O2-NEXT:    [[TMP1:%.*]] = icmp uge ptr [[BOUND_PTR_ARITH]], [[ARR]], {{!annotation ![0-9]+}}
// CHECK-ARM-O2-NEXT:    [[OR_COND:%.*]] = and i1 [[TMP0]], [[TMP1]], {{!annotation ![0-9]+}}
// CHECK-ARM-O2-NEXT:    br i1 [[OR_COND]], label %[[CONT14:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// CHECK-ARM-O2:       [[TRAP]]:
// CHECK-ARM-O2-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR4:[0-9]+]], {{!annotation ![0-9]+}}
// CHECK-ARM-O2-NEXT:    unreachable, {{!annotation ![0-9]+}}
// CHECK-ARM-O2:       [[CONT14]]:
// CHECK-ARM-O2-NEXT:    call void @llvm.lifetime.end.p0(ptr nonnull [[ARR]]) #[[ATTR3]]
// CHECK-ARM-O2-NEXT:    ret i32 undef
//
int main() {
    int arr[10];
    int *__indexable uPtr = arr;
    int *__bidi_indexable bptr = uPtr;
    --bptr;
    return *bptr; // trap : underflow
}
