// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --version 6


// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck --check-prefixes O0 %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -emit-llvm %s -o - | FileCheck --check-prefixes O2 %s
// RUN: %clang_cc1 -O0 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck --check-prefixes O0 %s
// RUN: %clang_cc1 -O2 -triple x86_64 -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck --check-prefixes O2 %s

#include <ptrcheck.h>

// O0-LABEL: define dso_local i32 @main(
// O0-SAME: ) #[[ATTR0:[0-9]+]] {
// O0-NEXT:  [[ENTRY:.*]]:
// O0-NEXT:    [[RETVAL:%.*]] = alloca i32, align 4
// O0-NEXT:    [[ARR:%.*]] = alloca [10 x i32], align 16
// O0-NEXT:    [[LEN:%.*]] = alloca i32, align 4
// O0-NEXT:    [[DCP:%.*]] = alloca ptr, align 8
// O0-NEXT:    [[TMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// O0-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// O0-NEXT:    [[AGG_TEMP1:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// O0-NEXT:    [[AGG_TEMP7:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// O0-NEXT:    [[TP:%.*]] = alloca ptr, align 8
// O0-NEXT:    [[AGG_TEMP14:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// O0-NEXT:    [[BP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// O0-NEXT:    [[AGG_TEMP27:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// O0-NEXT:    store i32 0, ptr [[RETVAL]], align 4
// O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 16 [[ARR]], ptr align 16 @__const.main.arr, i64 40, i1 false)
// O0-NEXT:    store i32 5, ptr [[LEN]], align 4
// O0-NEXT:    [[ARRAYDECAY:%.*]] = getelementptr inbounds [10 x i32], ptr [[ARR]], i64 0, i64 0
// O0-NEXT:    [[UPPER:%.*]] = getelementptr inbounds i32, ptr [[ARRAYDECAY]], i64 10
// O0-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 0
// O0-NEXT:    store ptr [[ARRAYDECAY]], ptr [[TMP0]], align 8
// O0-NEXT:    [[TMP1:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 1
// O0-NEXT:    store ptr [[UPPER]], ptr [[TMP1]], align 8
// O0-NEXT:    [[TMP2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[TMP]], i32 0, i32 2
// O0-NEXT:    store ptr [[ARRAYDECAY]], ptr [[TMP2]], align 8
// O0-NEXT:    [[TMP3:%.*]] = load i32, ptr [[LEN]], align 4
// O0-NEXT:    [[CONV:%.*]] = sext i32 [[TMP3]] to i64
// O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP]], ptr align 8 [[TMP]], i64 24, i1 false), {{!annotation ![0-9]+}}
// O0-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1, {{!annotation ![0-9]+}}
// O0-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8, {{!annotation ![0-9]+}}
// O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP1]], ptr align 8 [[TMP]], i64 24, i1 false), {{!annotation ![0-9]+}}
// O0-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 0, {{!annotation ![0-9]+}}
// O0-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8, {{!annotation ![0-9]+}}
// O0-NEXT:    [[WIDE_PTR_UB_ADDR2:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 1, {{!annotation ![0-9]+}}
// O0-NEXT:    [[WIDE_PTR_UB3:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR2]], align 8, {{!annotation ![0-9]+}}
// O0-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP1]], i32 0, i32 2, {{!annotation ![0-9]+}}
// O0-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8, {{!annotation ![0-9]+}}
// O0-NEXT:    [[SUB_PTR_LHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_UB]] to i64, {{!annotation ![0-9]+}}
// O0-NEXT:    [[SUB_PTR_RHS_CAST:%.*]] = ptrtoint ptr [[WIDE_PTR_PTR]] to i64, {{!annotation ![0-9]+}}
// O0-NEXT:    [[SUB_PTR_SUB:%.*]] = sub i64 [[SUB_PTR_LHS_CAST]], [[SUB_PTR_RHS_CAST]], {{!annotation ![0-9]+}}
// O0-NEXT:    [[SUB_PTR_DIV:%.*]] = sdiv exact i64 [[SUB_PTR_SUB]], 4, {{!annotation ![0-9]+}}
// O0-NEXT:    [[CMP:%.*]] = icmp sle i64 [[CONV]], [[SUB_PTR_DIV]], {{!annotation ![0-9]+}}
// O0-NEXT:    br i1 [[CMP]], label %[[LAND_RHS:.*]], label %[[LAND_END:.*]], {{!annotation ![0-9]+}}
// O0:       [[LAND_RHS]]:
// O0-NEXT:    [[CMP5:%.*]] = icmp sle i64 0, [[CONV]], {{!annotation ![0-9]+}}
// O0-NEXT:    br label %[[LAND_END]], {{!annotation ![0-9]+}}
// O0:       [[LAND_END]]:
// O0-NEXT:    [[TMP4:%.*]] = phi i1 [ false, %[[ENTRY]] ], [ [[CMP5]], %[[LAND_RHS]] ], {{!annotation ![0-9]+}}
// O0-NEXT:    br i1 [[TMP4]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// O0:       [[TRAP]]:
// O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3:[0-9]+]], {{!annotation ![0-9]+}}
// O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// O0:       [[CONT]]:
// O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP7]], ptr align 8 [[TMP]], i64 24, i1 false)
// O0-NEXT:    [[WIDE_PTR_PTR_ADDR8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 0
// O0-NEXT:    [[WIDE_PTR_PTR9:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR8]], align 8
// O0-NEXT:    [[WIDE_PTR_UB_ADDR10:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 1
// O0-NEXT:    [[WIDE_PTR_UB11:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR10]], align 8
// O0-NEXT:    [[WIDE_PTR_LB_ADDR12:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP7]], i32 0, i32 2
// O0-NEXT:    [[WIDE_PTR_LB13:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR12]], align 8
// O0-NEXT:    store ptr [[WIDE_PTR_PTR9]], ptr [[DCP]], align 8
// O0-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[DCP]], align 8
// O0-NEXT:    [[TMP6:%.*]] = load i32, ptr [[LEN]], align 4
// O0-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP6]] to i64
// O0-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP5]], i64 [[IDX_EXT]]
// O0-NEXT:    [[TMP7:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP14]], i32 0, i32 0
// O0-NEXT:    store ptr [[TMP5]], ptr [[TMP7]], align 8
// O0-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP14]], i32 0, i32 1
// O0-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP8]], align 8
// O0-NEXT:    [[TMP9:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP14]], i32 0, i32 2
// O0-NEXT:    store ptr [[TMP5]], ptr [[TMP9]], align 8
// O0-NEXT:    [[WIDE_PTR_PTR_ADDR15:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP14]], i32 0, i32 0
// O0-NEXT:    [[WIDE_PTR_PTR16:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR15]], align 8
// O0-NEXT:    [[WIDE_PTR_UB_ADDR17:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP14]], i32 0, i32 1
// O0-NEXT:    [[WIDE_PTR_UB18:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR17]], align 8
// O0-NEXT:    [[WIDE_PTR_LB_ADDR19:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP14]], i32 0, i32 2
// O0-NEXT:    [[WIDE_PTR_LB20:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR19]], align 8
// O0-NEXT:    [[TMP10:%.*]] = icmp ne ptr [[WIDE_PTR_PTR16]], null, {{!annotation ![0-9]+}}
// O0-NEXT:    br i1 [[TMP10]], label %[[BOUNDSCHECK_NOTNULL:.*]], label %[[BOUNDSCHECK_NULL:.*]], {{!annotation ![0-9]+}}
// O0:       [[BOUNDSCHECK_NOTNULL]]:
// O0-NEXT:    [[TMP11:%.*]] = icmp ult ptr [[WIDE_PTR_PTR16]], [[WIDE_PTR_UB18]], {{!annotation ![0-9]+}}
// O0-NEXT:    br i1 [[TMP11]], label %[[CONT22:.*]], label %[[TRAP21:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// O0:       [[TRAP21]]:
// O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// O0:       [[CONT22]]:
// O0-NEXT:    [[TMP12:%.*]] = icmp uge ptr [[WIDE_PTR_PTR16]], [[WIDE_PTR_LB20]], {{!annotation ![0-9]+}}
// O0-NEXT:    br i1 [[TMP12]], label %[[CONT24:.*]], label %[[TRAP23:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// O0:       [[TRAP23]]:
// O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// O0:       [[CONT24]]:
// O0-NEXT:    br label %[[BOUNDSCHECK_NULL]]
// O0:       [[BOUNDSCHECK_NULL]]:
// O0-NEXT:    store ptr [[WIDE_PTR_PTR16]], ptr [[TP]], align 8
// O0-NEXT:    [[TMP13:%.*]] = load ptr, ptr [[DCP]], align 8
// O0-NEXT:    [[TMP14:%.*]] = load i32, ptr [[LEN]], align 4
// O0-NEXT:    [[IDX_EXT25:%.*]] = sext i32 [[TMP14]] to i64
// O0-NEXT:    [[ADD_PTR26:%.*]] = getelementptr inbounds i32, ptr [[TMP13]], i64 [[IDX_EXT25]]
// O0-NEXT:    [[TMP15:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[BP]], i32 0, i32 0
// O0-NEXT:    store ptr [[TMP13]], ptr [[TMP15]], align 8
// O0-NEXT:    [[TMP16:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[BP]], i32 0, i32 1
// O0-NEXT:    store ptr [[ADD_PTR26]], ptr [[TMP16]], align 8
// O0-NEXT:    [[TMP17:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[BP]], i32 0, i32 2
// O0-NEXT:    store ptr [[TMP13]], ptr [[TMP17]], align 8
// O0-NEXT:    br label %[[BINGO:.*]]
// O0:       [[BINGO]]:
// O0-NEXT:    call void @llvm.memcpy.p0.p0.i64(ptr align 8 [[AGG_TEMP27]], ptr align 8 [[BP]], i64 24, i1 false)
// O0-NEXT:    [[WIDE_PTR_PTR_ADDR28:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP27]], i32 0, i32 0
// O0-NEXT:    [[WIDE_PTR_PTR29:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR28]], align 8
// O0-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR29]], i64 5
// O0-NEXT:    [[WIDE_PTR_UB_ADDR30:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP27]], i32 0, i32 1
// O0-NEXT:    [[WIDE_PTR_UB31:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR30]], align 8
// O0-NEXT:    [[WIDE_PTR_LB_ADDR32:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP27]], i32 0, i32 2
// O0-NEXT:    [[WIDE_PTR_LB33:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR32]], align 8
// O0-NEXT:    [[TMP18:%.*]] = icmp ult ptr [[ARRAYIDX]], [[WIDE_PTR_UB31]], {{!annotation ![0-9]+}}
// O0-NEXT:    br i1 [[TMP18]], label %[[CONT35:.*]], label %[[TRAP34:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// O0:       [[TRAP34]]:
// O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// O0:       [[CONT35]]:
// O0-NEXT:    [[TMP19:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB33]], {{!annotation ![0-9]+}}
// O0-NEXT:    br i1 [[TMP19]], label %[[CONT37:.*]], label %[[TRAP36:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// O0:       [[TRAP36]]:
// O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR3]], {{!annotation ![0-9]+}}
// O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// O0:       [[CONT37]]:
// O0-NEXT:    [[TMP20:%.*]] = load i32, ptr [[ARRAYIDX]], align 4
// O0-NEXT:    ret i32 [[TMP20]]
//
// O2-LABEL: define dso_local noundef i32 @main(
// O2-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// O2-NEXT:  [[ENTRY:.*:]]
// O2-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR2:[0-9]+]], {{!annotation ![0-9]+}}
// O2-NEXT:    unreachable, {{!annotation ![0-9]+}}
//
int main() {
    int arr[10] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};

    int len = 5;
    int *__counted_by(len) dcp = arr;
    int *__single tp = dcp; // ok: check len >= 1 or dcp is null
    int *bp = dcp; // construct bounds pointer based on calculated bounds
bingo:;
    return bp[5]; // oob trap!
}


