// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --replace-value-regex "!annotation ![0-9]+" "!tbaa ![0-9]+" "!tbaa\.struct ![0-9]+" "!nosanitize ![0-9]+" "!srcloc ![0-9]+" "!prof ![0-9]+" --version 6


// RUN: %clang_cc1 -O0 -triple arm64e -fbounds-safety -emit-llvm %s -o - | FileCheck --check-prefix=O0 %s
// RUN: %clang_cc1 -O2 -triple arm64e -fbounds-safety -emit-llvm %s -o - | FileCheck --check-prefix=O2 %s
// RUN: %clang_cc1 -O0 -triple arm64e -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck --check-prefix=O0 %s
// RUN: %clang_cc1 -O2 -triple arm64e -fbounds-safety -x objective-c -fexperimental-bounds-safety-objc -emit-llvm %s -o - | FileCheck --check-prefix=O2 %s

#include <ptrcheck.h>

// O0-LABEL: define dso_local void @foo(
// O0-SAME: ptr noundef [[BUF:%.*]], i32 noundef [[LEN:%.*]]) #[[ATTR0:[0-9]+]] {
// O0-NEXT:  [[ENTRY:.*:]]
// O0-NEXT:    [[BUF_ADDR:%.*]] = alloca ptr, align 8
// O0-NEXT:    [[LEN_ADDR:%.*]] = alloca i32, align 4
// O0-NEXT:    [[AGG_TEMP:%.*]] = alloca %"__bounds_safety::wide_ptr.bidi_indexable", align 8
// O0-NEXT:    store ptr [[BUF]], ptr [[BUF_ADDR]], align 8
// O0-NEXT:    store i32 [[LEN]], ptr [[LEN_ADDR]], align 4
// O0-NEXT:    [[TMP0:%.*]] = load i32, ptr [[LEN_ADDR]], align 4
// O0-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[BUF_ADDR]], align 8
// O0-NEXT:    [[TMP2:%.*]] = load i32, ptr [[LEN_ADDR]], align 4
// O0-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[TMP2]] to i64
// O0-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i32, ptr [[TMP1]], i64 [[IDX_EXT]]
// O0-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// O0-NEXT:    store ptr [[TMP1]], ptr [[TMP3]], align 8
// O0-NEXT:    [[TMP4:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// O0-NEXT:    store ptr [[ADD_PTR]], ptr [[TMP4]], align 8
// O0-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// O0-NEXT:    store ptr [[TMP1]], ptr [[TMP5]], align 8
// O0-NEXT:    [[WIDE_PTR_PTR_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 0
// O0-NEXT:    [[WIDE_PTR_PTR:%.*]] = load ptr, ptr [[WIDE_PTR_PTR_ADDR]], align 8
// O0-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i32, ptr [[WIDE_PTR_PTR]], i64 5
// O0-NEXT:    [[WIDE_PTR_UB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 1
// O0-NEXT:    [[WIDE_PTR_UB:%.*]] = load ptr, ptr [[WIDE_PTR_UB_ADDR]], align 8
// O0-NEXT:    [[WIDE_PTR_LB_ADDR:%.*]] = getelementptr inbounds nuw %"__bounds_safety::wide_ptr.bidi_indexable", ptr [[AGG_TEMP]], i32 0, i32 2
// O0-NEXT:    [[WIDE_PTR_LB:%.*]] = load ptr, ptr [[WIDE_PTR_LB_ADDR]], align 8
// O0-NEXT:    [[TMP6:%.*]] = icmp ult ptr [[ARRAYIDX]], [[WIDE_PTR_UB]], {{!annotation ![0-9]+}}
// O0-NEXT:    br i1 [[TMP6]], label %[[CONT:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// O0:       [[TRAP]]:
// O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR2:[0-9]+]], {{!annotation ![0-9]+}}
// O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// O0:       [[CONT]]:
// O0-NEXT:    [[TMP7:%.*]] = icmp uge ptr [[ARRAYIDX]], [[WIDE_PTR_LB]], {{!annotation ![0-9]+}}
// O0-NEXT:    br i1 [[TMP7]], label %[[CONT2:.*]], label %[[TRAP1:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// O0:       [[TRAP1]]:
// O0-NEXT:    call void @llvm.ubsantrap(i8 25) #[[ATTR2]], {{!annotation ![0-9]+}}
// O0-NEXT:    unreachable, {{!annotation ![0-9]+}}
// O0:       [[CONT2]]:
// O0-NEXT:    store i32 [[TMP0]], ptr [[ARRAYIDX]], align 4
// O0-NEXT:    ret void
//
// O2-LABEL: define dso_local void @foo(
// O2-SAME: ptr noundef writeonly captures(address) [[BUF:%.*]], i32 noundef [[LEN:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
// O2-NEXT:  [[ENTRY:.*:]]
// O2-NEXT:    [[IDX_EXT:%.*]] = sext i32 [[LEN]] to i64
// O2-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds [4 x i8], ptr [[BUF]], i64 [[IDX_EXT]]
// O2-NEXT:    [[ARRAYIDX:%.*]] = getelementptr i8, ptr [[BUF]], i64 20
// O2-NEXT:    [[TMP0:%.*]] = icmp ult ptr [[ARRAYIDX]], [[ADD_PTR]], {{!annotation ![0-9]+}}
// O2-NEXT:    [[TMP1:%.*]] = icmp uge ptr [[ARRAYIDX]], [[BUF]], {{!annotation ![0-9]+}}
// O2-NEXT:    [[OR_COND:%.*]] = and i1 [[TMP1]], [[TMP0]], {{!annotation ![0-9]+}}
// O2-NEXT:    br i1 [[OR_COND]], label %[[CONT1:.*]], label %[[TRAP:.*]], {{!prof ![0-9]+}}, {{!annotation ![0-9]+}}
// O2:       [[TRAP]]:
// O2-NEXT:    tail call void @llvm.ubsantrap(i8 25) #[[ATTR2:[0-9]+]], {{!annotation ![0-9]+}}
// O2-NEXT:    unreachable, {{!annotation ![0-9]+}}
// O2:       [[CONT1]]:
// O2-NEXT:    store i32 [[LEN]], ptr [[ARRAYIDX]], align 4, {{!tbaa ![0-9]+}}
// O2-NEXT:    ret void
//
void foo(int *__counted_by(len) buf, int len) {
    buf[5] = len;
}









