# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

load("@bazel_skylib//:bzl_library.bzl", "bzl_library")
load("@hedron_compile_commands//:refresh_compile_commands.bzl", "refresh_compile_commands")

bzl_library(
    name = "configure",
    srcs = ["configure.bzl"],
    visibility = ["//visibility:public"],
)

refresh_compile_commands(
    name = "refresh_compile_commands",
    output_dir = "../..",
    targets = [
        "@llvm-project//...",
    ],
)
