; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals none --version 6
; RUN: opt -passes=loop-vectorize -S %s | FileCheck %s

target triple = "x86_64-unknown-linux-gnu"

; Test case for https://github.com/llvm/llvm-project/issues/185867.
define void @fminnum_with_any_of_cost(ptr %p) #0 {
; CHECK-LABEL: define void @fminnum_with_any_of_cost(
; CHECK-SAME: ptr [[P:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[SCALAR_PH:.*]]:
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[RED:%.*]] = phi float [ 0.000000e+00, %[[SCALAR_PH]] ], [ [[MIN:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr inbounds float, ptr [[P]], i64 [[IV]]
; CHECK-NEXT:    [[LDV:%.*]] = load float, ptr [[GEP]], align 4
; CHECK-NEXT:    [[MIN]] = tail call float @llvm.minnum.f32(float [[RED]], float [[LDV]])
; CHECK-NEXT:    [[IV_NEXT]] = add i64 [[IV]], 1
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i64 [[IV_NEXT]], 140
; CHECK-NEXT:    br i1 [[CMP]], label %[[EXIT:.*]], label %[[LOOP]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %red = phi float [ 0.000000e+00, %entry ], [ %min, %loop ]
  %gep = getelementptr inbounds float, ptr %p, i64 %iv
  %ldv = load float, ptr %gep, align 4
  %min = tail call float @llvm.minnum.f32(float %red, float %ldv)
  %iv.next = add i64 %iv, 1
  %cmp = icmp eq i64 %iv.next, 140
  br i1 %cmp, label %exit, label %loop

exit:
  ret void
}

attributes #0 = { "target-cpu"="znver4" }
