; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=loop-vectorize -enable-masked-invariant-load -force-vector-width=4 \
; RUN:     -force-vector-interleave=1 -mtriple=x86_64-unknown-linux-gnu -mattr=avx2 -S \
; RUN:     | FileCheck %s

;; Two distinct loop-invariant pointers loaded under the same predicate in the
;; same block.  Each load is independently lowered to a single-lane masked load
;; + broadcast, but they share the SAME AnyOf(mask) and lane-0 mask material
;; thanks to the standard VPlan CSE that runs before unrolling.
;;
;;   for (i = 0; i < n; ++i)
;;     if (cond[i])
;;       a[i] = *inv1 + *inv2;

define void @cond_invar_load_two_ptrs(ptr noalias %a, ptr noalias %cond, ptr noalias %inv1, ptr noalias %inv2, i64 %n) {
; CHECK-LABEL: @cond_invar_load_two_ptrs(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[N:%.*]], 4
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK:       vector.ph:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[N]], 4
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[N]], [[N_MOD_VF]]
; CHECK-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK:       vector.body:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds i32, ptr [[COND:%.*]], i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i32>, ptr [[TMP0]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ne <4 x i32> [[WIDE_LOAD]], zeroinitializer
; CHECK-NEXT:    [[TMP2:%.*]] = freeze <4 x i1> [[TMP1]]
; CHECK-NEXT:    [[TMP3:%.*]] = call i1 @llvm.vector.reduce.or.v4i1(<4 x i1> [[TMP2]])
; CHECK-NEXT:    [[TMP4:%.*]] = insertelement <4 x i1> zeroinitializer, i1 [[TMP3]], i32 0
; CHECK-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <4 x i32> @llvm.masked.load.v4i32.p0(ptr align 4 [[INV1:%.*]], <4 x i1> [[TMP4]], <4 x i32> poison)
; CHECK-NEXT:    [[BROADCAST_LANE:%.*]] = shufflevector <4 x i32> [[WIDE_MASKED_LOAD]], <4 x i32> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[WIDE_MASKED_LOAD1:%.*]] = call <4 x i32> @llvm.masked.load.v4i32.p0(ptr align 4 [[INV2:%.*]], <4 x i1> [[TMP4]], <4 x i32> poison)
; CHECK-NEXT:    [[BROADCAST_LANE2:%.*]] = shufflevector <4 x i32> [[WIDE_MASKED_LOAD1]], <4 x i32> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP5:%.*]] = add <4 x i32> [[BROADCAST_LANE]], [[BROADCAST_LANE2]]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i32, ptr [[A:%.*]], i64 [[INDEX]]
; CHECK-NEXT:    call void @llvm.masked.store.v4i32.p0(<4 x i32> [[TMP5]], ptr align 4 [[TMP6]], <4 x i1> [[TMP1]])
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; CHECK-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP7]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       middle.block:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[N]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label [[FOR_END:%.*]], label [[SCALAR_PH]]
; CHECK:       scalar.ph:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], [[MIDDLE_BLOCK]] ], [ 0, [[ENTRY:%.*]] ]
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[I:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[I_NEXT:%.*]], [[FOR_INC:%.*]] ]
; CHECK-NEXT:    [[COND_GEP:%.*]] = getelementptr inbounds i32, ptr [[COND]], i64 [[I]]
; CHECK-NEXT:    [[CV:%.*]] = load i32, ptr [[COND_GEP]], align 4
; CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[CV]], 0
; CHECK-NEXT:    br i1 [[TOBOOL]], label [[IF_THEN:%.*]], label [[FOR_INC]]
; CHECK:       if.then:
; CHECK-NEXT:    [[V1:%.*]] = load i32, ptr [[INV1]], align 4
; CHECK-NEXT:    [[V2:%.*]] = load i32, ptr [[INV2]], align 4
; CHECK-NEXT:    [[SUM:%.*]] = add i32 [[V1]], [[V2]]
; CHECK-NEXT:    [[A_GEP:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[I]]
; CHECK-NEXT:    store i32 [[SUM]], ptr [[A_GEP]], align 4
; CHECK-NEXT:    br label [[FOR_INC]]
; CHECK:       for.inc:
; CHECK-NEXT:    [[I_NEXT]] = add nuw nsw i64 [[I]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[EXITCOND]], label [[FOR_END]], label [[FOR_BODY]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK:       for.end:
; CHECK-NEXT:    ret void
;
entry:
  br label %for.body

for.body:
  %i = phi i64 [ 0, %entry ], [ %i.next, %for.inc ]
  %cond.gep = getelementptr inbounds i32, ptr %cond, i64 %i
  %cv = load i32, ptr %cond.gep, align 4
  %tobool = icmp ne i32 %cv, 0
  br i1 %tobool, label %if.then, label %for.inc

if.then:
  %v1 = load i32, ptr %inv1, align 4
  %v2 = load i32, ptr %inv2, align 4
  %sum = add i32 %v1, %v2
  %a.gep = getelementptr inbounds i32, ptr %a, i64 %i
  store i32 %sum, ptr %a.gep, align 4
  br label %for.inc

for.inc:
  %i.next = add nuw nsw i64 %i, 1
  %exitcond = icmp eq i64 %i.next, %n
  br i1 %exitcond, label %for.end, label %for.body

for.end:
  ret void
}
