; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -passes=loop-vectorize -force-vector-width=4 -force-vector-interleave=1 \
; RUN:     -mtriple=x86_64-unknown-linux-gnu -mattr=avx2 -S | FileCheck %s --check-prefix=CHECK-OFF
; RUN: opt < %s -passes=loop-vectorize -force-vector-width=4 -force-vector-interleave=1 \
; RUN:     -enable-masked-invariant-load -mtriple=x86_64-unknown-linux-gnu -mattr=avx2 -S | FileCheck %s --check-prefix=CHECK-ON

;; Conditional load from a loop-invariant pointer.
;;
;;   for (i = 0; i < n; ++i)
;;     if (cond[i])
;;       a[i] = *inv;
;;
;; The pointer %inv is loop-invariant and the load is predicated by %tobool.
;; Without -enable-masked-invariant-load the cost model falls back to per-lane
;; scalarised predicated loads (CM_Scalarize) - one pred.load.if/continue
;; chain per VF lane.
;;
;; With -enable-masked-invariant-load the load becomes:
;;   * AnyOf reduction across the block mask,
;;   * lane-0 mask materialisation (zeroinitializer + insertelement i1),
;;   * one masked.load from %inv,
;;   * shufflevector broadcast of lane 0 to all VF lanes.

define void @cond_invar_load(ptr noalias %a, ptr noalias %cond, ptr noalias %inv, i64 %n) {
; CHECK-OFF-LABEL: @cond_invar_load(
; CHECK-OFF-NEXT:  entry:
; CHECK-OFF-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[N:%.*]], 4
; CHECK-OFF-NEXT:    br i1 [[MIN_ITERS_CHECK]], label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK-OFF:       vector.ph:
; CHECK-OFF-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[N]], 4
; CHECK-OFF-NEXT:    [[N_VEC:%.*]] = sub i64 [[N]], [[N_MOD_VF]]
; CHECK-OFF-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK-OFF:       vector.body:
; CHECK-OFF-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[PRED_LOAD_CONTINUE6:%.*]] ]
; CHECK-OFF-NEXT:    [[TMP0:%.*]] = getelementptr inbounds i32, ptr [[COND:%.*]], i64 [[INDEX]]
; CHECK-OFF-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i32>, ptr [[TMP0]], align 4
; CHECK-OFF-NEXT:    [[TMP1:%.*]] = icmp ne <4 x i32> [[WIDE_LOAD]], zeroinitializer
; CHECK-OFF-NEXT:    [[TMP2:%.*]] = extractelement <4 x i1> [[TMP1]], i64 0
; CHECK-OFF-NEXT:    br i1 [[TMP2]], label [[PRED_LOAD_IF:%.*]], label [[PRED_LOAD_CONTINUE:%.*]]
; CHECK-OFF:       pred.load.if:
; CHECK-OFF-NEXT:    [[TMP3:%.*]] = load i32, ptr [[INV:%.*]], align 4
; CHECK-OFF-NEXT:    [[TMP4:%.*]] = insertelement <4 x i32> poison, i32 [[TMP3]], i64 0
; CHECK-OFF-NEXT:    br label [[PRED_LOAD_CONTINUE]]
; CHECK-OFF:       pred.load.continue:
; CHECK-OFF-NEXT:    [[TMP5:%.*]] = phi <4 x i32> [ poison, [[VECTOR_BODY]] ], [ [[TMP4]], [[PRED_LOAD_IF]] ]
; CHECK-OFF-NEXT:    [[TMP6:%.*]] = extractelement <4 x i1> [[TMP1]], i64 1
; CHECK-OFF-NEXT:    br i1 [[TMP6]], label [[PRED_LOAD_IF1:%.*]], label [[PRED_LOAD_CONTINUE2:%.*]]
; CHECK-OFF:       pred.load.if1:
; CHECK-OFF-NEXT:    [[TMP7:%.*]] = load i32, ptr [[INV]], align 4
; CHECK-OFF-NEXT:    [[TMP8:%.*]] = insertelement <4 x i32> [[TMP5]], i32 [[TMP7]], i64 1
; CHECK-OFF-NEXT:    br label [[PRED_LOAD_CONTINUE2]]
; CHECK-OFF:       pred.load.continue2:
; CHECK-OFF-NEXT:    [[TMP9:%.*]] = phi <4 x i32> [ [[TMP5]], [[PRED_LOAD_CONTINUE]] ], [ [[TMP8]], [[PRED_LOAD_IF1]] ]
; CHECK-OFF-NEXT:    [[TMP10:%.*]] = extractelement <4 x i1> [[TMP1]], i64 2
; CHECK-OFF-NEXT:    br i1 [[TMP10]], label [[PRED_LOAD_IF3:%.*]], label [[PRED_LOAD_CONTINUE4:%.*]]
; CHECK-OFF:       pred.load.if3:
; CHECK-OFF-NEXT:    [[TMP11:%.*]] = load i32, ptr [[INV]], align 4
; CHECK-OFF-NEXT:    [[TMP12:%.*]] = insertelement <4 x i32> [[TMP9]], i32 [[TMP11]], i64 2
; CHECK-OFF-NEXT:    br label [[PRED_LOAD_CONTINUE4]]
; CHECK-OFF:       pred.load.continue4:
; CHECK-OFF-NEXT:    [[TMP13:%.*]] = phi <4 x i32> [ [[TMP9]], [[PRED_LOAD_CONTINUE2]] ], [ [[TMP12]], [[PRED_LOAD_IF3]] ]
; CHECK-OFF-NEXT:    [[TMP14:%.*]] = extractelement <4 x i1> [[TMP1]], i64 3
; CHECK-OFF-NEXT:    br i1 [[TMP14]], label [[PRED_LOAD_IF5:%.*]], label [[PRED_LOAD_CONTINUE6]]
; CHECK-OFF:       pred.load.if5:
; CHECK-OFF-NEXT:    [[TMP15:%.*]] = load i32, ptr [[INV]], align 4
; CHECK-OFF-NEXT:    [[TMP16:%.*]] = insertelement <4 x i32> [[TMP13]], i32 [[TMP15]], i64 3
; CHECK-OFF-NEXT:    br label [[PRED_LOAD_CONTINUE6]]
; CHECK-OFF:       pred.load.continue6:
; CHECK-OFF-NEXT:    [[TMP17:%.*]] = phi <4 x i32> [ [[TMP13]], [[PRED_LOAD_CONTINUE4]] ], [ [[TMP16]], [[PRED_LOAD_IF5]] ]
; CHECK-OFF-NEXT:    [[TMP18:%.*]] = getelementptr i32, ptr [[A:%.*]], i64 [[INDEX]]
; CHECK-OFF-NEXT:    call void @llvm.masked.store.v4i32.p0(<4 x i32> [[TMP17]], ptr align 4 [[TMP18]], <4 x i1> [[TMP1]])
; CHECK-OFF-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; CHECK-OFF-NEXT:    [[TMP19:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-OFF-NEXT:    br i1 [[TMP19]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK-OFF:       middle.block:
; CHECK-OFF-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[N]], [[N_VEC]]
; CHECK-OFF-NEXT:    br i1 [[CMP_N]], label [[FOR_END:%.*]], label [[SCALAR_PH]]
; CHECK-OFF:       scalar.ph:
; CHECK-OFF-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], [[MIDDLE_BLOCK]] ], [ 0, [[ENTRY:%.*]] ]
; CHECK-OFF-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK-OFF:       for.body:
; CHECK-OFF-NEXT:    [[I:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[I_NEXT:%.*]], [[FOR_INC:%.*]] ]
; CHECK-OFF-NEXT:    [[COND_GEP:%.*]] = getelementptr inbounds i32, ptr [[COND]], i64 [[I]]
; CHECK-OFF-NEXT:    [[CV:%.*]] = load i32, ptr [[COND_GEP]], align 4
; CHECK-OFF-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[CV]], 0
; CHECK-OFF-NEXT:    br i1 [[TOBOOL]], label [[IF_THEN:%.*]], label [[FOR_INC]]
; CHECK-OFF:       if.then:
; CHECK-OFF-NEXT:    [[V:%.*]] = load i32, ptr [[INV]], align 4
; CHECK-OFF-NEXT:    [[A_GEP:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[I]]
; CHECK-OFF-NEXT:    store i32 [[V]], ptr [[A_GEP]], align 4
; CHECK-OFF-NEXT:    br label [[FOR_INC]]
; CHECK-OFF:       for.inc:
; CHECK-OFF-NEXT:    [[I_NEXT]] = add nuw nsw i64 [[I]], 1
; CHECK-OFF-NEXT:    [[EXITCOND:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; CHECK-OFF-NEXT:    br i1 [[EXITCOND]], label [[FOR_END]], label [[FOR_BODY]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK-OFF:       for.end:
; CHECK-OFF-NEXT:    ret void
;
; CHECK-ON-LABEL: @cond_invar_load(
; CHECK-ON-NEXT:  entry:
; CHECK-ON-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[N:%.*]], 4
; CHECK-ON-NEXT:    br i1 [[MIN_ITERS_CHECK]], label [[SCALAR_PH:%.*]], label [[VECTOR_PH:%.*]]
; CHECK-ON:       vector.ph:
; CHECK-ON-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[N]], 4
; CHECK-ON-NEXT:    [[N_VEC:%.*]] = sub i64 [[N]], [[N_MOD_VF]]
; CHECK-ON-NEXT:    br label [[VECTOR_BODY:%.*]]
; CHECK-ON:       vector.body:
; CHECK-ON-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, [[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], [[VECTOR_BODY]] ]
; CHECK-ON-NEXT:    [[TMP0:%.*]] = getelementptr inbounds i32, ptr [[COND:%.*]], i64 [[INDEX]]
; CHECK-ON-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i32>, ptr [[TMP0]], align 4
; CHECK-ON-NEXT:    [[TMP1:%.*]] = icmp ne <4 x i32> [[WIDE_LOAD]], zeroinitializer
; CHECK-ON-NEXT:    [[TMP2:%.*]] = freeze <4 x i1> [[TMP1]]
; CHECK-ON-NEXT:    [[TMP3:%.*]] = call i1 @llvm.vector.reduce.or.v4i1(<4 x i1> [[TMP2]])
; CHECK-ON-NEXT:    [[TMP4:%.*]] = insertelement <4 x i1> zeroinitializer, i1 [[TMP3]], i32 0
; CHECK-ON-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <4 x i32> @llvm.masked.load.v4i32.p0(ptr align 4 [[INV:%.*]], <4 x i1> [[TMP4]], <4 x i32> poison)
; CHECK-ON-NEXT:    [[BROADCAST_LANE:%.*]] = shufflevector <4 x i32> [[WIDE_MASKED_LOAD]], <4 x i32> poison, <4 x i32> zeroinitializer
; CHECK-ON-NEXT:    [[TMP5:%.*]] = getelementptr i32, ptr [[A:%.*]], i64 [[INDEX]]
; CHECK-ON-NEXT:    call void @llvm.masked.store.v4i32.p0(<4 x i32> [[BROADCAST_LANE]], ptr align 4 [[TMP5]], <4 x i1> [[TMP1]])
; CHECK-ON-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; CHECK-ON-NEXT:    [[TMP6:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-ON-NEXT:    br i1 [[TMP6]], label [[MIDDLE_BLOCK:%.*]], label [[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK-ON:       middle.block:
; CHECK-ON-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[N]], [[N_VEC]]
; CHECK-ON-NEXT:    br i1 [[CMP_N]], label [[FOR_END:%.*]], label [[SCALAR_PH]]
; CHECK-ON:       scalar.ph:
; CHECK-ON-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], [[MIDDLE_BLOCK]] ], [ 0, [[ENTRY:%.*]] ]
; CHECK-ON-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK-ON:       for.body:
; CHECK-ON-NEXT:    [[I:%.*]] = phi i64 [ [[BC_RESUME_VAL]], [[SCALAR_PH]] ], [ [[I_NEXT:%.*]], [[FOR_INC:%.*]] ]
; CHECK-ON-NEXT:    [[COND_GEP:%.*]] = getelementptr inbounds i32, ptr [[COND]], i64 [[I]]
; CHECK-ON-NEXT:    [[CV:%.*]] = load i32, ptr [[COND_GEP]], align 4
; CHECK-ON-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[CV]], 0
; CHECK-ON-NEXT:    br i1 [[TOBOOL]], label [[IF_THEN:%.*]], label [[FOR_INC]]
; CHECK-ON:       if.then:
; CHECK-ON-NEXT:    [[V:%.*]] = load i32, ptr [[INV]], align 4
; CHECK-ON-NEXT:    [[A_GEP:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[I]]
; CHECK-ON-NEXT:    store i32 [[V]], ptr [[A_GEP]], align 4
; CHECK-ON-NEXT:    br label [[FOR_INC]]
; CHECK-ON:       for.inc:
; CHECK-ON-NEXT:    [[I_NEXT]] = add nuw nsw i64 [[I]], 1
; CHECK-ON-NEXT:    [[EXITCOND:%.*]] = icmp eq i64 [[I_NEXT]], [[N]]
; CHECK-ON-NEXT:    br i1 [[EXITCOND]], label [[FOR_END]], label [[FOR_BODY]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK-ON:       for.end:
; CHECK-ON-NEXT:    ret void
;
entry:
  br label %for.body

for.body:
  %i = phi i64 [ 0, %entry ], [ %i.next, %for.inc ]
  %cond.gep = getelementptr inbounds i32, ptr %cond, i64 %i
  %cv = load i32, ptr %cond.gep, align 4
  %tobool = icmp ne i32 %cv, 0
  br i1 %tobool, label %if.then, label %for.inc

if.then:
  %v = load i32, ptr %inv, align 4
  %a.gep = getelementptr inbounds i32, ptr %a, i64 %i
  store i32 %v, ptr %a.gep, align 4
  br label %for.inc

for.inc:
  %i.next = add nuw nsw i64 %i, 1
  %exitcond = icmp eq i64 %i.next, %n
  br i1 %exitcond, label %for.end, label %for.body

for.end:
  ret void
}
