; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals none --version 6
; RUN: opt -passes=loop-vectorize -force-vector-interleave=2 -S %s | FileCheck --check-prefix=UF2 %s
; RUN: opt -passes=loop-vectorize -force-vector-interleave=4 -S %s | FileCheck --check-prefix=UF4 %s

target triple = "x86_64-apple-macosx"

; TODO: Test case where register pressure is too high and introducing a wide canonical
; IV would add spills for UF = 4 but not UF = 2.
define i32 @many_reductions(ptr %a, ptr %b, ptr %c, ptr %d, ptr %e, ptr %f, i64 %N) #0 {
; UF2-LABEL: define i32 @many_reductions(
; UF2-SAME: ptr [[A:%.*]], ptr [[B:%.*]], ptr [[C:%.*]], ptr [[D:%.*]], ptr [[E:%.*]], ptr [[F:%.*]], i64 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; UF2-NEXT:  [[ENTRY:.*:]]
; UF2-NEXT:    br label %[[VECTOR_PH:.*]]
; UF2:       [[VECTOR_PH]]:
; UF2-NEXT:    [[N_RND_UP:%.*]] = add i64 [[N]], 15
; UF2-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[N_RND_UP]], 16
; UF2-NEXT:    [[N_VEC:%.*]] = sub i64 [[N_RND_UP]], [[N_MOD_VF]]
; UF2-NEXT:    [[TRIP_COUNT_MINUS_1:%.*]] = sub i64 [[N]], 1
; UF2-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <8 x i64> poison, i64 [[TRIP_COUNT_MINUS_1]], i64 0
; UF2-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <8 x i64> [[BROADCAST_SPLATINSERT]], <8 x i64> poison, <8 x i32> zeroinitializer
; UF2-NEXT:    br label %[[VECTOR_BODY:.*]]
; UF2:       [[VECTOR_BODY]]:
; UF2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; UF2-NEXT:    [[VEC_PHI:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP14:%.*]], %[[VECTOR_BODY]] ]
; UF2-NEXT:    [[VEC_PHI1:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP15:%.*]], %[[VECTOR_BODY]] ]
; UF2-NEXT:    [[VEC_PHI2:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP16:%.*]], %[[VECTOR_BODY]] ]
; UF2-NEXT:    [[VEC_PHI3:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP17:%.*]], %[[VECTOR_BODY]] ]
; UF2-NEXT:    [[VEC_PHI4:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP18:%.*]], %[[VECTOR_BODY]] ]
; UF2-NEXT:    [[VEC_PHI5:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP19:%.*]], %[[VECTOR_BODY]] ]
; UF2-NEXT:    [[VEC_PHI6:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP20:%.*]], %[[VECTOR_BODY]] ]
; UF2-NEXT:    [[VEC_PHI7:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP21:%.*]], %[[VECTOR_BODY]] ]
; UF2-NEXT:    [[VEC_PHI8:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP22:%.*]], %[[VECTOR_BODY]] ]
; UF2-NEXT:    [[VEC_PHI9:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP23:%.*]], %[[VECTOR_BODY]] ]
; UF2-NEXT:    [[VEC_PHI10:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP24:%.*]], %[[VECTOR_BODY]] ]
; UF2-NEXT:    [[VEC_PHI11:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP25:%.*]], %[[VECTOR_BODY]] ]
; UF2-NEXT:    [[VEC_IV:%.*]] = phi <8 x i64> [ <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7>, %[[VECTOR_PH]] ], [ [[VEC_IND_NEXT:%.*]], %[[VECTOR_BODY]] ]
; UF2-NEXT:    [[VEC_IV16:%.*]] = add nuw <8 x i64> [[VEC_IV]], splat (i64 8)
; UF2-NEXT:    [[TMP0:%.*]] = icmp ule <8 x i64> [[VEC_IV]], [[BROADCAST_SPLAT]]
; UF2-NEXT:    [[TMP1:%.*]] = icmp ule <8 x i64> [[VEC_IV16]], [[BROADCAST_SPLAT]]
; UF2-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDEX]]
; UF2-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[INDEX]]
; UF2-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i32, ptr [[C]], i64 [[INDEX]]
; UF2-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i32, ptr [[D]], i64 [[INDEX]]
; UF2-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i32, ptr [[E]], i64 [[INDEX]]
; UF2-NEXT:    [[TMP7:%.*]] = getelementptr inbounds i32, ptr [[F]], i64 [[INDEX]]
; UF2-NEXT:    [[TMP8:%.*]] = getelementptr inbounds i32, ptr [[TMP2]], i64 8
; UF2-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP2]], <8 x i1> [[TMP0]], <8 x i32> poison)
; UF2-NEXT:    [[WIDE_MASKED_LOAD17:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP8]], <8 x i1> [[TMP1]], <8 x i32> poison)
; UF2-NEXT:    [[TMP9:%.*]] = getelementptr inbounds i32, ptr [[TMP3]], i64 8
; UF2-NEXT:    [[WIDE_MASKED_LOAD18:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP3]], <8 x i1> [[TMP0]], <8 x i32> poison)
; UF2-NEXT:    [[WIDE_MASKED_LOAD19:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP9]], <8 x i1> [[TMP1]], <8 x i32> poison)
; UF2-NEXT:    [[TMP10:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i64 8
; UF2-NEXT:    [[WIDE_MASKED_LOAD20:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP4]], <8 x i1> [[TMP0]], <8 x i32> poison)
; UF2-NEXT:    [[WIDE_MASKED_LOAD21:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP10]], <8 x i1> [[TMP1]], <8 x i32> poison)
; UF2-NEXT:    [[TMP11:%.*]] = getelementptr inbounds i32, ptr [[TMP5]], i64 8
; UF2-NEXT:    [[WIDE_MASKED_LOAD22:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP5]], <8 x i1> [[TMP0]], <8 x i32> poison)
; UF2-NEXT:    [[WIDE_MASKED_LOAD23:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP11]], <8 x i1> [[TMP1]], <8 x i32> poison)
; UF2-NEXT:    [[TMP12:%.*]] = getelementptr inbounds i32, ptr [[TMP6]], i64 8
; UF2-NEXT:    [[WIDE_MASKED_LOAD24:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP6]], <8 x i1> [[TMP0]], <8 x i32> poison)
; UF2-NEXT:    [[WIDE_MASKED_LOAD25:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP12]], <8 x i1> [[TMP1]], <8 x i32> poison)
; UF2-NEXT:    [[TMP13:%.*]] = getelementptr inbounds i32, ptr [[TMP7]], i64 8
; UF2-NEXT:    [[WIDE_MASKED_LOAD26:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP7]], <8 x i1> [[TMP0]], <8 x i32> poison)
; UF2-NEXT:    [[WIDE_MASKED_LOAD27:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP13]], <8 x i1> [[TMP1]], <8 x i32> poison)
; UF2-NEXT:    [[TMP14]] = add <8 x i32> [[VEC_PHI]], [[WIDE_MASKED_LOAD]]
; UF2-NEXT:    [[TMP15]] = add <8 x i32> [[VEC_PHI1]], [[WIDE_MASKED_LOAD17]]
; UF2-NEXT:    [[TMP16]] = add <8 x i32> [[VEC_PHI2]], [[WIDE_MASKED_LOAD18]]
; UF2-NEXT:    [[TMP17]] = add <8 x i32> [[VEC_PHI3]], [[WIDE_MASKED_LOAD19]]
; UF2-NEXT:    [[TMP18]] = add <8 x i32> [[VEC_PHI4]], [[WIDE_MASKED_LOAD20]]
; UF2-NEXT:    [[TMP19]] = add <8 x i32> [[VEC_PHI5]], [[WIDE_MASKED_LOAD21]]
; UF2-NEXT:    [[TMP20]] = add <8 x i32> [[VEC_PHI6]], [[WIDE_MASKED_LOAD22]]
; UF2-NEXT:    [[TMP21]] = add <8 x i32> [[VEC_PHI7]], [[WIDE_MASKED_LOAD23]]
; UF2-NEXT:    [[TMP22]] = add <8 x i32> [[VEC_PHI8]], [[WIDE_MASKED_LOAD24]]
; UF2-NEXT:    [[TMP23]] = add <8 x i32> [[VEC_PHI9]], [[WIDE_MASKED_LOAD25]]
; UF2-NEXT:    [[TMP24]] = add <8 x i32> [[VEC_PHI10]], [[WIDE_MASKED_LOAD26]]
; UF2-NEXT:    [[TMP25]] = add <8 x i32> [[VEC_PHI11]], [[WIDE_MASKED_LOAD27]]
; UF2-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], 16
; UF2-NEXT:    [[VEC_IND_NEXT]] = add nuw <8 x i64> [[VEC_IV16]], splat (i64 8)
; UF2-NEXT:    [[TMP26:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; UF2-NEXT:    br i1 [[TMP26]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; UF2:       [[MIDDLE_BLOCK]]:
; UF2-NEXT:    [[TMP27:%.*]] = select <8 x i1> [[TMP0]], <8 x i32> [[TMP14]], <8 x i32> [[VEC_PHI]]
; UF2-NEXT:    [[TMP28:%.*]] = select <8 x i1> [[TMP1]], <8 x i32> [[TMP15]], <8 x i32> [[VEC_PHI1]]
; UF2-NEXT:    [[TMP29:%.*]] = select <8 x i1> [[TMP0]], <8 x i32> [[TMP16]], <8 x i32> [[VEC_PHI2]]
; UF2-NEXT:    [[TMP30:%.*]] = select <8 x i1> [[TMP1]], <8 x i32> [[TMP17]], <8 x i32> [[VEC_PHI3]]
; UF2-NEXT:    [[TMP31:%.*]] = select <8 x i1> [[TMP0]], <8 x i32> [[TMP18]], <8 x i32> [[VEC_PHI4]]
; UF2-NEXT:    [[TMP32:%.*]] = select <8 x i1> [[TMP1]], <8 x i32> [[TMP19]], <8 x i32> [[VEC_PHI5]]
; UF2-NEXT:    [[TMP33:%.*]] = select <8 x i1> [[TMP0]], <8 x i32> [[TMP20]], <8 x i32> [[VEC_PHI6]]
; UF2-NEXT:    [[TMP34:%.*]] = select <8 x i1> [[TMP1]], <8 x i32> [[TMP21]], <8 x i32> [[VEC_PHI7]]
; UF2-NEXT:    [[TMP35:%.*]] = select <8 x i1> [[TMP0]], <8 x i32> [[TMP22]], <8 x i32> [[VEC_PHI8]]
; UF2-NEXT:    [[TMP36:%.*]] = select <8 x i1> [[TMP1]], <8 x i32> [[TMP23]], <8 x i32> [[VEC_PHI9]]
; UF2-NEXT:    [[TMP37:%.*]] = select <8 x i1> [[TMP0]], <8 x i32> [[TMP24]], <8 x i32> [[VEC_PHI10]]
; UF2-NEXT:    [[TMP38:%.*]] = select <8 x i1> [[TMP1]], <8 x i32> [[TMP25]], <8 x i32> [[VEC_PHI11]]
; UF2-NEXT:    [[BIN_RDX:%.*]] = add <8 x i32> [[TMP28]], [[TMP27]]
; UF2-NEXT:    [[TMP39:%.*]] = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> [[BIN_RDX]])
; UF2-NEXT:    [[BIN_RDX28:%.*]] = add <8 x i32> [[TMP30]], [[TMP29]]
; UF2-NEXT:    [[TMP40:%.*]] = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> [[BIN_RDX28]])
; UF2-NEXT:    [[BIN_RDX29:%.*]] = add <8 x i32> [[TMP32]], [[TMP31]]
; UF2-NEXT:    [[TMP41:%.*]] = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> [[BIN_RDX29]])
; UF2-NEXT:    [[BIN_RDX30:%.*]] = add <8 x i32> [[TMP34]], [[TMP33]]
; UF2-NEXT:    [[TMP42:%.*]] = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> [[BIN_RDX30]])
; UF2-NEXT:    [[BIN_RDX31:%.*]] = add <8 x i32> [[TMP36]], [[TMP35]]
; UF2-NEXT:    [[TMP43:%.*]] = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> [[BIN_RDX31]])
; UF2-NEXT:    [[BIN_RDX32:%.*]] = add <8 x i32> [[TMP38]], [[TMP37]]
; UF2-NEXT:    [[TMP44:%.*]] = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> [[BIN_RDX32]])
; UF2-NEXT:    br label %[[EXIT:.*]]
; UF2:       [[EXIT]]:
; UF2-NEXT:    [[A1:%.*]] = add i32 [[TMP39]], [[TMP40]]
; UF2-NEXT:    [[A2:%.*]] = add i32 [[TMP41]], [[TMP42]]
; UF2-NEXT:    [[A3:%.*]] = add i32 [[TMP43]], [[TMP44]]
; UF2-NEXT:    [[A4:%.*]] = add i32 [[A1]], [[A2]]
; UF2-NEXT:    [[A5:%.*]] = add i32 [[A4]], [[A3]]
; UF2-NEXT:    ret i32 [[A5]]
;
; UF4-LABEL: define i32 @many_reductions(
; UF4-SAME: ptr [[A:%.*]], ptr [[B:%.*]], ptr [[C:%.*]], ptr [[D:%.*]], ptr [[E:%.*]], ptr [[F:%.*]], i64 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; UF4-NEXT:  [[ENTRY:.*:]]
; UF4-NEXT:    br label %[[VECTOR_PH:.*]]
; UF4:       [[VECTOR_PH]]:
; UF4-NEXT:    [[N_RND_UP:%.*]] = add i64 [[N]], 31
; UF4-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[N_RND_UP]], 32
; UF4-NEXT:    [[N_VEC:%.*]] = sub i64 [[N_RND_UP]], [[N_MOD_VF]]
; UF4-NEXT:    [[TRIP_COUNT_MINUS_1:%.*]] = sub i64 [[N]], 1
; UF4-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <8 x i64> poison, i64 [[TRIP_COUNT_MINUS_1]], i64 0
; UF4-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <8 x i64> [[BROADCAST_SPLATINSERT]], <8 x i64> poison, <8 x i32> zeroinitializer
; UF4-NEXT:    br label %[[VECTOR_BODY:.*]]
; UF4:       [[VECTOR_BODY]]:
; UF4-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; UF4-NEXT:    [[VEC_PHI:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP28:%.*]], %[[VECTOR_BODY]] ]
; UF4-NEXT:    [[VEC_PHI1:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP29:%.*]], %[[VECTOR_BODY]] ]
; UF4-NEXT:    [[VEC_PHI2:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP30:%.*]], %[[VECTOR_BODY]] ]
; UF4-NEXT:    [[VEC_PHI3:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP31:%.*]], %[[VECTOR_BODY]] ]
; UF4-NEXT:    [[VEC_PHI4:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP32:%.*]], %[[VECTOR_BODY]] ]
; UF4-NEXT:    [[VEC_PHI5:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP33:%.*]], %[[VECTOR_BODY]] ]
; UF4-NEXT:    [[VEC_PHI6:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP34:%.*]], %[[VECTOR_BODY]] ]
; UF4-NEXT:    [[VEC_PHI7:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP35:%.*]], %[[VECTOR_BODY]] ]
; UF4-NEXT:    [[VEC_PHI8:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP36:%.*]], %[[VECTOR_BODY]] ]
; UF4-NEXT:    [[VEC_PHI9:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP37:%.*]], %[[VECTOR_BODY]] ]
; UF4-NEXT:    [[VEC_PHI10:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP38:%.*]], %[[VECTOR_BODY]] ]
; UF4-NEXT:    [[VEC_PHI11:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP39:%.*]], %[[VECTOR_BODY]] ]
; UF4-NEXT:    [[VEC_PHI12:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP40:%.*]], %[[VECTOR_BODY]] ]
; UF4-NEXT:    [[VEC_PHI13:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP41:%.*]], %[[VECTOR_BODY]] ]
; UF4-NEXT:    [[VEC_PHI14:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP42:%.*]], %[[VECTOR_BODY]] ]
; UF4-NEXT:    [[VEC_PHI15:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP43:%.*]], %[[VECTOR_BODY]] ]
; UF4-NEXT:    [[VEC_PHI16:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP44:%.*]], %[[VECTOR_BODY]] ]
; UF4-NEXT:    [[VEC_PHI17:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP45:%.*]], %[[VECTOR_BODY]] ]
; UF4-NEXT:    [[VEC_PHI18:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP46:%.*]], %[[VECTOR_BODY]] ]
; UF4-NEXT:    [[VEC_PHI19:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP47:%.*]], %[[VECTOR_BODY]] ]
; UF4-NEXT:    [[VEC_PHI20:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP48:%.*]], %[[VECTOR_BODY]] ]
; UF4-NEXT:    [[VEC_PHI21:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP49:%.*]], %[[VECTOR_BODY]] ]
; UF4-NEXT:    [[VEC_PHI22:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP50:%.*]], %[[VECTOR_BODY]] ]
; UF4-NEXT:    [[VEC_PHI23:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP51:%.*]], %[[VECTOR_BODY]] ]
; UF4-NEXT:    [[BROADCAST_SPLATINSERT24:%.*]] = insertelement <8 x i64> poison, i64 [[INDEX]], i64 0
; UF4-NEXT:    [[BROADCAST_SPLAT25:%.*]] = shufflevector <8 x i64> [[BROADCAST_SPLATINSERT24]], <8 x i64> poison, <8 x i32> zeroinitializer
; UF4-NEXT:    [[VEC_IV:%.*]] = add nuw <8 x i64> [[BROADCAST_SPLAT25]], <i64 0, i64 1, i64 2, i64 3, i64 4, i64 5, i64 6, i64 7>
; UF4-NEXT:    [[VEC_IV28:%.*]] = add nuw <8 x i64> [[BROADCAST_SPLAT25]], <i64 8, i64 9, i64 10, i64 11, i64 12, i64 13, i64 14, i64 15>
; UF4-NEXT:    [[VEC_IV31:%.*]] = add nuw <8 x i64> [[BROADCAST_SPLAT25]], <i64 16, i64 17, i64 18, i64 19, i64 20, i64 21, i64 22, i64 23>
; UF4-NEXT:    [[VEC_IV34:%.*]] = add nuw <8 x i64> [[BROADCAST_SPLAT25]], <i64 24, i64 25, i64 26, i64 27, i64 28, i64 29, i64 30, i64 31>
; UF4-NEXT:    [[TMP0:%.*]] = icmp ule <8 x i64> [[VEC_IV]], [[BROADCAST_SPLAT]]
; UF4-NEXT:    [[TMP1:%.*]] = icmp ule <8 x i64> [[VEC_IV28]], [[BROADCAST_SPLAT]]
; UF4-NEXT:    [[TMP2:%.*]] = icmp ule <8 x i64> [[VEC_IV31]], [[BROADCAST_SPLAT]]
; UF4-NEXT:    [[TMP3:%.*]] = icmp ule <8 x i64> [[VEC_IV34]], [[BROADCAST_SPLAT]]
; UF4-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDEX]]
; UF4-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i32, ptr [[B]], i64 [[INDEX]]
; UF4-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i32, ptr [[C]], i64 [[INDEX]]
; UF4-NEXT:    [[TMP7:%.*]] = getelementptr inbounds i32, ptr [[D]], i64 [[INDEX]]
; UF4-NEXT:    [[TMP8:%.*]] = getelementptr inbounds i32, ptr [[E]], i64 [[INDEX]]
; UF4-NEXT:    [[TMP9:%.*]] = getelementptr inbounds i32, ptr [[F]], i64 [[INDEX]]
; UF4-NEXT:    [[TMP10:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i64 8
; UF4-NEXT:    [[TMP11:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i64 16
; UF4-NEXT:    [[TMP12:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i64 24
; UF4-NEXT:    [[WIDE_MASKED_LOAD:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP4]], <8 x i1> [[TMP0]], <8 x i32> poison)
; UF4-NEXT:    [[WIDE_MASKED_LOAD35:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP10]], <8 x i1> [[TMP1]], <8 x i32> poison)
; UF4-NEXT:    [[WIDE_MASKED_LOAD36:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP11]], <8 x i1> [[TMP2]], <8 x i32> poison)
; UF4-NEXT:    [[WIDE_MASKED_LOAD37:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP12]], <8 x i1> [[TMP3]], <8 x i32> poison)
; UF4-NEXT:    [[TMP13:%.*]] = getelementptr inbounds i32, ptr [[TMP5]], i64 8
; UF4-NEXT:    [[TMP14:%.*]] = getelementptr inbounds i32, ptr [[TMP5]], i64 16
; UF4-NEXT:    [[TMP15:%.*]] = getelementptr inbounds i32, ptr [[TMP5]], i64 24
; UF4-NEXT:    [[WIDE_MASKED_LOAD38:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP5]], <8 x i1> [[TMP0]], <8 x i32> poison)
; UF4-NEXT:    [[WIDE_MASKED_LOAD39:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP13]], <8 x i1> [[TMP1]], <8 x i32> poison)
; UF4-NEXT:    [[WIDE_MASKED_LOAD40:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP14]], <8 x i1> [[TMP2]], <8 x i32> poison)
; UF4-NEXT:    [[WIDE_MASKED_LOAD41:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP15]], <8 x i1> [[TMP3]], <8 x i32> poison)
; UF4-NEXT:    [[TMP16:%.*]] = getelementptr inbounds i32, ptr [[TMP6]], i64 8
; UF4-NEXT:    [[TMP17:%.*]] = getelementptr inbounds i32, ptr [[TMP6]], i64 16
; UF4-NEXT:    [[TMP18:%.*]] = getelementptr inbounds i32, ptr [[TMP6]], i64 24
; UF4-NEXT:    [[WIDE_MASKED_LOAD42:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP6]], <8 x i1> [[TMP0]], <8 x i32> poison)
; UF4-NEXT:    [[WIDE_MASKED_LOAD43:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP16]], <8 x i1> [[TMP1]], <8 x i32> poison)
; UF4-NEXT:    [[WIDE_MASKED_LOAD44:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP17]], <8 x i1> [[TMP2]], <8 x i32> poison)
; UF4-NEXT:    [[WIDE_MASKED_LOAD45:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP18]], <8 x i1> [[TMP3]], <8 x i32> poison)
; UF4-NEXT:    [[TMP19:%.*]] = getelementptr inbounds i32, ptr [[TMP7]], i64 8
; UF4-NEXT:    [[TMP20:%.*]] = getelementptr inbounds i32, ptr [[TMP7]], i64 16
; UF4-NEXT:    [[TMP21:%.*]] = getelementptr inbounds i32, ptr [[TMP7]], i64 24
; UF4-NEXT:    [[WIDE_MASKED_LOAD46:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP7]], <8 x i1> [[TMP0]], <8 x i32> poison)
; UF4-NEXT:    [[WIDE_MASKED_LOAD47:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP19]], <8 x i1> [[TMP1]], <8 x i32> poison)
; UF4-NEXT:    [[WIDE_MASKED_LOAD48:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP20]], <8 x i1> [[TMP2]], <8 x i32> poison)
; UF4-NEXT:    [[WIDE_MASKED_LOAD49:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP21]], <8 x i1> [[TMP3]], <8 x i32> poison)
; UF4-NEXT:    [[TMP22:%.*]] = getelementptr inbounds i32, ptr [[TMP8]], i64 8
; UF4-NEXT:    [[TMP23:%.*]] = getelementptr inbounds i32, ptr [[TMP8]], i64 16
; UF4-NEXT:    [[TMP24:%.*]] = getelementptr inbounds i32, ptr [[TMP8]], i64 24
; UF4-NEXT:    [[WIDE_MASKED_LOAD50:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP8]], <8 x i1> [[TMP0]], <8 x i32> poison)
; UF4-NEXT:    [[WIDE_MASKED_LOAD51:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP22]], <8 x i1> [[TMP1]], <8 x i32> poison)
; UF4-NEXT:    [[WIDE_MASKED_LOAD52:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP23]], <8 x i1> [[TMP2]], <8 x i32> poison)
; UF4-NEXT:    [[WIDE_MASKED_LOAD53:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP24]], <8 x i1> [[TMP3]], <8 x i32> poison)
; UF4-NEXT:    [[TMP25:%.*]] = getelementptr inbounds i32, ptr [[TMP9]], i64 8
; UF4-NEXT:    [[TMP26:%.*]] = getelementptr inbounds i32, ptr [[TMP9]], i64 16
; UF4-NEXT:    [[TMP27:%.*]] = getelementptr inbounds i32, ptr [[TMP9]], i64 24
; UF4-NEXT:    [[WIDE_MASKED_LOAD54:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP9]], <8 x i1> [[TMP0]], <8 x i32> poison)
; UF4-NEXT:    [[WIDE_MASKED_LOAD55:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP25]], <8 x i1> [[TMP1]], <8 x i32> poison)
; UF4-NEXT:    [[WIDE_MASKED_LOAD56:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP26]], <8 x i1> [[TMP2]], <8 x i32> poison)
; UF4-NEXT:    [[WIDE_MASKED_LOAD57:%.*]] = call <8 x i32> @llvm.masked.load.v8i32.p0(ptr align 4 [[TMP27]], <8 x i1> [[TMP3]], <8 x i32> poison)
; UF4-NEXT:    [[TMP28]] = add <8 x i32> [[VEC_PHI]], [[WIDE_MASKED_LOAD]]
; UF4-NEXT:    [[TMP29]] = add <8 x i32> [[VEC_PHI1]], [[WIDE_MASKED_LOAD35]]
; UF4-NEXT:    [[TMP30]] = add <8 x i32> [[VEC_PHI2]], [[WIDE_MASKED_LOAD36]]
; UF4-NEXT:    [[TMP31]] = add <8 x i32> [[VEC_PHI3]], [[WIDE_MASKED_LOAD37]]
; UF4-NEXT:    [[TMP32]] = add <8 x i32> [[VEC_PHI4]], [[WIDE_MASKED_LOAD38]]
; UF4-NEXT:    [[TMP33]] = add <8 x i32> [[VEC_PHI5]], [[WIDE_MASKED_LOAD39]]
; UF4-NEXT:    [[TMP34]] = add <8 x i32> [[VEC_PHI6]], [[WIDE_MASKED_LOAD40]]
; UF4-NEXT:    [[TMP35]] = add <8 x i32> [[VEC_PHI7]], [[WIDE_MASKED_LOAD41]]
; UF4-NEXT:    [[TMP36]] = add <8 x i32> [[VEC_PHI8]], [[WIDE_MASKED_LOAD42]]
; UF4-NEXT:    [[TMP37]] = add <8 x i32> [[VEC_PHI9]], [[WIDE_MASKED_LOAD43]]
; UF4-NEXT:    [[TMP38]] = add <8 x i32> [[VEC_PHI10]], [[WIDE_MASKED_LOAD44]]
; UF4-NEXT:    [[TMP39]] = add <8 x i32> [[VEC_PHI11]], [[WIDE_MASKED_LOAD45]]
; UF4-NEXT:    [[TMP40]] = add <8 x i32> [[VEC_PHI12]], [[WIDE_MASKED_LOAD46]]
; UF4-NEXT:    [[TMP41]] = add <8 x i32> [[VEC_PHI13]], [[WIDE_MASKED_LOAD47]]
; UF4-NEXT:    [[TMP42]] = add <8 x i32> [[VEC_PHI14]], [[WIDE_MASKED_LOAD48]]
; UF4-NEXT:    [[TMP43]] = add <8 x i32> [[VEC_PHI15]], [[WIDE_MASKED_LOAD49]]
; UF4-NEXT:    [[TMP44]] = add <8 x i32> [[VEC_PHI16]], [[WIDE_MASKED_LOAD50]]
; UF4-NEXT:    [[TMP45]] = add <8 x i32> [[VEC_PHI17]], [[WIDE_MASKED_LOAD51]]
; UF4-NEXT:    [[TMP46]] = add <8 x i32> [[VEC_PHI18]], [[WIDE_MASKED_LOAD52]]
; UF4-NEXT:    [[TMP47]] = add <8 x i32> [[VEC_PHI19]], [[WIDE_MASKED_LOAD53]]
; UF4-NEXT:    [[TMP48]] = add <8 x i32> [[VEC_PHI20]], [[WIDE_MASKED_LOAD54]]
; UF4-NEXT:    [[TMP49]] = add <8 x i32> [[VEC_PHI21]], [[WIDE_MASKED_LOAD55]]
; UF4-NEXT:    [[TMP50]] = add <8 x i32> [[VEC_PHI22]], [[WIDE_MASKED_LOAD56]]
; UF4-NEXT:    [[TMP51]] = add <8 x i32> [[VEC_PHI23]], [[WIDE_MASKED_LOAD57]]
; UF4-NEXT:    [[INDEX_NEXT]] = add i64 [[INDEX]], 32
; UF4-NEXT:    [[TMP52:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; UF4-NEXT:    br i1 [[TMP52]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; UF4:       [[MIDDLE_BLOCK]]:
; UF4-NEXT:    [[TMP53:%.*]] = select <8 x i1> [[TMP0]], <8 x i32> [[TMP28]], <8 x i32> [[VEC_PHI]]
; UF4-NEXT:    [[TMP54:%.*]] = select <8 x i1> [[TMP1]], <8 x i32> [[TMP29]], <8 x i32> [[VEC_PHI1]]
; UF4-NEXT:    [[TMP55:%.*]] = select <8 x i1> [[TMP2]], <8 x i32> [[TMP30]], <8 x i32> [[VEC_PHI2]]
; UF4-NEXT:    [[TMP56:%.*]] = select <8 x i1> [[TMP3]], <8 x i32> [[TMP31]], <8 x i32> [[VEC_PHI3]]
; UF4-NEXT:    [[TMP57:%.*]] = select <8 x i1> [[TMP0]], <8 x i32> [[TMP32]], <8 x i32> [[VEC_PHI4]]
; UF4-NEXT:    [[TMP58:%.*]] = select <8 x i1> [[TMP1]], <8 x i32> [[TMP33]], <8 x i32> [[VEC_PHI5]]
; UF4-NEXT:    [[TMP59:%.*]] = select <8 x i1> [[TMP2]], <8 x i32> [[TMP34]], <8 x i32> [[VEC_PHI6]]
; UF4-NEXT:    [[TMP60:%.*]] = select <8 x i1> [[TMP3]], <8 x i32> [[TMP35]], <8 x i32> [[VEC_PHI7]]
; UF4-NEXT:    [[TMP61:%.*]] = select <8 x i1> [[TMP0]], <8 x i32> [[TMP36]], <8 x i32> [[VEC_PHI8]]
; UF4-NEXT:    [[TMP62:%.*]] = select <8 x i1> [[TMP1]], <8 x i32> [[TMP37]], <8 x i32> [[VEC_PHI9]]
; UF4-NEXT:    [[TMP63:%.*]] = select <8 x i1> [[TMP2]], <8 x i32> [[TMP38]], <8 x i32> [[VEC_PHI10]]
; UF4-NEXT:    [[TMP64:%.*]] = select <8 x i1> [[TMP3]], <8 x i32> [[TMP39]], <8 x i32> [[VEC_PHI11]]
; UF4-NEXT:    [[TMP65:%.*]] = select <8 x i1> [[TMP0]], <8 x i32> [[TMP40]], <8 x i32> [[VEC_PHI12]]
; UF4-NEXT:    [[TMP66:%.*]] = select <8 x i1> [[TMP1]], <8 x i32> [[TMP41]], <8 x i32> [[VEC_PHI13]]
; UF4-NEXT:    [[TMP67:%.*]] = select <8 x i1> [[TMP2]], <8 x i32> [[TMP42]], <8 x i32> [[VEC_PHI14]]
; UF4-NEXT:    [[TMP68:%.*]] = select <8 x i1> [[TMP3]], <8 x i32> [[TMP43]], <8 x i32> [[VEC_PHI15]]
; UF4-NEXT:    [[TMP69:%.*]] = select <8 x i1> [[TMP0]], <8 x i32> [[TMP44]], <8 x i32> [[VEC_PHI16]]
; UF4-NEXT:    [[TMP70:%.*]] = select <8 x i1> [[TMP1]], <8 x i32> [[TMP45]], <8 x i32> [[VEC_PHI17]]
; UF4-NEXT:    [[TMP71:%.*]] = select <8 x i1> [[TMP2]], <8 x i32> [[TMP46]], <8 x i32> [[VEC_PHI18]]
; UF4-NEXT:    [[TMP72:%.*]] = select <8 x i1> [[TMP3]], <8 x i32> [[TMP47]], <8 x i32> [[VEC_PHI19]]
; UF4-NEXT:    [[TMP73:%.*]] = select <8 x i1> [[TMP0]], <8 x i32> [[TMP48]], <8 x i32> [[VEC_PHI20]]
; UF4-NEXT:    [[TMP74:%.*]] = select <8 x i1> [[TMP1]], <8 x i32> [[TMP49]], <8 x i32> [[VEC_PHI21]]
; UF4-NEXT:    [[TMP75:%.*]] = select <8 x i1> [[TMP2]], <8 x i32> [[TMP50]], <8 x i32> [[VEC_PHI22]]
; UF4-NEXT:    [[TMP76:%.*]] = select <8 x i1> [[TMP3]], <8 x i32> [[TMP51]], <8 x i32> [[VEC_PHI23]]
; UF4-NEXT:    [[BIN_RDX:%.*]] = add <8 x i32> [[TMP54]], [[TMP53]]
; UF4-NEXT:    [[BIN_RDX58:%.*]] = add <8 x i32> [[TMP55]], [[BIN_RDX]]
; UF4-NEXT:    [[BIN_RDX59:%.*]] = add <8 x i32> [[TMP56]], [[BIN_RDX58]]
; UF4-NEXT:    [[TMP77:%.*]] = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> [[BIN_RDX59]])
; UF4-NEXT:    [[BIN_RDX60:%.*]] = add <8 x i32> [[TMP58]], [[TMP57]]
; UF4-NEXT:    [[BIN_RDX61:%.*]] = add <8 x i32> [[TMP59]], [[BIN_RDX60]]
; UF4-NEXT:    [[BIN_RDX62:%.*]] = add <8 x i32> [[TMP60]], [[BIN_RDX61]]
; UF4-NEXT:    [[TMP78:%.*]] = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> [[BIN_RDX62]])
; UF4-NEXT:    [[BIN_RDX63:%.*]] = add <8 x i32> [[TMP62]], [[TMP61]]
; UF4-NEXT:    [[BIN_RDX64:%.*]] = add <8 x i32> [[TMP63]], [[BIN_RDX63]]
; UF4-NEXT:    [[BIN_RDX65:%.*]] = add <8 x i32> [[TMP64]], [[BIN_RDX64]]
; UF4-NEXT:    [[TMP79:%.*]] = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> [[BIN_RDX65]])
; UF4-NEXT:    [[BIN_RDX66:%.*]] = add <8 x i32> [[TMP66]], [[TMP65]]
; UF4-NEXT:    [[BIN_RDX67:%.*]] = add <8 x i32> [[TMP67]], [[BIN_RDX66]]
; UF4-NEXT:    [[BIN_RDX68:%.*]] = add <8 x i32> [[TMP68]], [[BIN_RDX67]]
; UF4-NEXT:    [[TMP80:%.*]] = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> [[BIN_RDX68]])
; UF4-NEXT:    [[BIN_RDX69:%.*]] = add <8 x i32> [[TMP70]], [[TMP69]]
; UF4-NEXT:    [[BIN_RDX70:%.*]] = add <8 x i32> [[TMP71]], [[BIN_RDX69]]
; UF4-NEXT:    [[BIN_RDX71:%.*]] = add <8 x i32> [[TMP72]], [[BIN_RDX70]]
; UF4-NEXT:    [[TMP81:%.*]] = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> [[BIN_RDX71]])
; UF4-NEXT:    [[BIN_RDX72:%.*]] = add <8 x i32> [[TMP74]], [[TMP73]]
; UF4-NEXT:    [[BIN_RDX73:%.*]] = add <8 x i32> [[TMP75]], [[BIN_RDX72]]
; UF4-NEXT:    [[BIN_RDX74:%.*]] = add <8 x i32> [[TMP76]], [[BIN_RDX73]]
; UF4-NEXT:    [[TMP82:%.*]] = call i32 @llvm.vector.reduce.add.v8i32(<8 x i32> [[BIN_RDX74]])
; UF4-NEXT:    br label %[[EXIT:.*]]
; UF4:       [[EXIT]]:
; UF4-NEXT:    [[A1:%.*]] = add i32 [[TMP77]], [[TMP78]]
; UF4-NEXT:    [[A2:%.*]] = add i32 [[TMP79]], [[TMP80]]
; UF4-NEXT:    [[A3:%.*]] = add i32 [[TMP81]], [[TMP82]]
; UF4-NEXT:    [[A4:%.*]] = add i32 [[A1]], [[A2]]
; UF4-NEXT:    [[A5:%.*]] = add i32 [[A4]], [[A3]]
; UF4-NEXT:    ret i32 [[A5]]
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %sa = phi i32 [ 0, %entry ], [ %sa.n, %loop ]
  %sb = phi i32 [ 0, %entry ], [ %sb.n, %loop ]
  %sc = phi i32 [ 0, %entry ], [ %sc.n, %loop ]
  %sd = phi i32 [ 0, %entry ], [ %sd.n, %loop ]
  %se = phi i32 [ 0, %entry ], [ %se.n, %loop ]
  %sf = phi i32 [ 0, %entry ], [ %sf.n, %loop ]
  %ga = getelementptr inbounds i32, ptr %a, i64 %iv
  %gb = getelementptr inbounds i32, ptr %b, i64 %iv
  %gc = getelementptr inbounds i32, ptr %c, i64 %iv
  %gd = getelementptr inbounds i32, ptr %d, i64 %iv
  %ge = getelementptr inbounds i32, ptr %e, i64 %iv
  %gf = getelementptr inbounds i32, ptr %f, i64 %iv
  %la = load i32, ptr %ga, align 4
  %lb = load i32, ptr %gb, align 4
  %lc = load i32, ptr %gc, align 4
  %ld = load i32, ptr %gd, align 4
  %le = load i32, ptr %ge, align 4
  %lf = load i32, ptr %gf, align 4
  %sa.n = add i32 %sa, %la
  %sb.n = add i32 %sb, %lb
  %sc.n = add i32 %sc, %lc
  %sd.n = add i32 %sd, %ld
  %se.n = add i32 %se, %le
  %sf.n = add i32 %sf, %lf
  %iv.next = add nuw nsw i64 %iv, 1
  %ec = icmp eq i64 %iv.next, %N
  br i1 %ec, label %exit, label %loop

exit:
  %a1 = add i32 %sa.n, %sb.n
  %a2 = add i32 %sc.n, %sd.n
  %a3 = add i32 %se.n, %sf.n
  %a4 = add i32 %a1, %a2
  %a5 = add i32 %a4, %a3
  ret i32 %a5
}

attributes #0 = { optsize "target-cpu"="skylake-avx512" }
