; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt < %s -S -passes='loop-vectorize' -enable-invariant-bound-versioning=true | FileCheck %s
;
; LoopVectorize speculative load hoist shouldn't kick in as SCEV cannot compute the trip count of a float-bounded loop, so the
; pass enters the dynamic-bound path.  It then rejects because the
; branch condition is an FCmpInst, not an ICmpInst.
;
;   void foo(float *A, float *B, float *Limit) {
;     for (float x = 0.0f; x < *Limit; x += 1.0f)
;       A[(int)x] = B[(int)x];
;   }

define dso_local void @foo(ptr noundef %A, ptr noundef readonly %B, ptr noundef readonly %Limit) #0 {
; CHECK-LABEL: @foo(
; CHECK-NEXT:  entry:
; CHECK-NEXT:    br label [[FOR_BODY:%.*]]
; CHECK:       for.body:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, [[ENTRY:%.*]] ], [ [[IV_NEXT:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[FIV:%.*]] = phi float [ 0.000000e+00, [[ENTRY]] ], [ [[FIV_NEXT:%.*]], [[FOR_BODY]] ]
; CHECK-NEXT:    [[GEP_B:%.*]] = getelementptr inbounds i32, ptr [[B:%.*]], i64 [[IV]]
; CHECK-NEXT:    [[B:%.*]] = load i32, ptr [[GEP_B]], align 4
; CHECK-NEXT:    [[GEP_A:%.*]] = getelementptr inbounds i32, ptr [[A:%.*]], i64 [[IV]]
; CHECK-NEXT:    store i32 [[B]], ptr [[GEP_A]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; CHECK-NEXT:    [[FIV_NEXT]] = fadd float [[FIV]], 1.000000e+00
; CHECK-NEXT:    [[LIM:%.*]] = load float, ptr [[LIMIT:%.*]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = fcmp olt float [[FIV_NEXT]], [[LIM]]
; CHECK-NEXT:    br i1 [[CMP]], label [[FOR_BODY]], label [[FOR_EXIT:%.*]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       for.exit:
; CHECK-NEXT:    ret void
;
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  %fiv = phi float [ 0.0, %entry ], [ %fiv.next, %for.body ]
  %gep.b = getelementptr inbounds i32, ptr %B, i64 %iv
  %b = load i32, ptr %gep.b, align 4
  %gep.a = getelementptr inbounds i32, ptr %A, i64 %iv
  store i32 %b, ptr %gep.a, align 4
  %iv.next = add nuw nsw i64 %iv, 1
  %fiv.next = fadd float %fiv, 1.0
  %lim = load float, ptr %Limit, align 4
  %cmp = fcmp olt float %fiv.next, %lim
  br i1 %cmp, label %for.body, label %for.exit, !llvm.loop !0

for.exit:
  ret void
}

attributes #0 = { mustprogress nofree norecurse nosync nounwind memory(argmem: readwrite) uwtable }

!0 = distinct !{!0, !1, !2}
!1 = !{!"llvm.loop.mustprogress"}
!2 = !{!"llvm.loop.unroll.disable"}
