; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -S -passes='loop-vectorize' -enable-invariant-bound-versioning=true | FileCheck %s
;

target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "aarch64-unknown-linux-gnu"

$warypen = comdat any

; Function Attrs: uwtable
define weak_odr dso_local noundef double @baz(ptr noundef nonnull align 8 dereferenceable(88) %arg, double noundef %arg1) local_unnamed_addr #0 comdat($warypen) {
; CHECK-LABEL: define weak_odr dso_local noundef double @baz(
; CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(88) [[ARG:%.*]], double noundef [[ARG1:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] comdat($warypen) {
; CHECK-NEXT:  [[BB:.*]]:
; CHECK-NEXT:    [[GETELEMENTPTR:%.*]] = getelementptr inbounds nuw i8, ptr [[ARG]], i64 72
; CHECK-NEXT:    [[LOAD:%.*]] = load i32, ptr [[GETELEMENTPTR]], align 8
; CHECK-NEXT:    [[ICMP:%.*]] = icmp eq i32 [[LOAD]], 0
; CHECK-NEXT:    br i1 [[ICMP]], label %[[BB6:.*]], label %[[BB2:.*]]
; CHECK:       [[BB2]]:
; CHECK-NEXT:    [[GETELEMENTPTR3:%.*]] = getelementptr inbounds nuw i8, ptr [[ARG]], i64 80
; CHECK-NEXT:    [[LOAD4:%.*]] = load ptr, ptr [[GETELEMENTPTR3]], align 8, !tbaa [[DOUBLEPTR_TBAA14:![0-9]+]]
; CHECK-NEXT:    br label %[[BB8:.*]]
; CHECK:       [[BB5:.*]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi double [ [[FADD:%.*]], %[[BB8]] ]
; CHECK-NEXT:    br label %[[BB6]]
; CHECK:       [[BB6]]:
; CHECK-NEXT:    [[PHI7:%.*]] = phi double [ 0.000000e+00, %[[BB]] ], [ [[PHI]], %[[BB5]] ]
; CHECK-NEXT:    [[FDIV:%.*]] = fdiv double 1.000000e+00, [[ARG1]]
; CHECK-NEXT:    [[CALL:%.*]] = tail call double @pow(double noundef [[PHI7]], double noundef [[FDIV]]) #[[ATTR3:[0-9]+]], !tbaa [[INT_TBAA10:![0-9]+]]
; CHECK-NEXT:    ret double [[CALL]]
; CHECK:       [[BB8]]:
; CHECK-NEXT:    [[PHI9:%.*]] = phi i64 [ 0, %[[BB2]] ], [ [[ADD:%.*]], %[[BB8]] ]
; CHECK-NEXT:    [[PHI10:%.*]] = phi double [ 0.000000e+00, %[[BB2]] ], [ [[FADD]], %[[BB8]] ]
; CHECK-NEXT:    [[GETELEMENTPTR11:%.*]] = getelementptr inbounds nuw [8 x i8], ptr [[LOAD4]], i64 [[PHI9]]
; CHECK-NEXT:    [[LOAD12:%.*]] = load double, ptr [[GETELEMENTPTR11]], align 8
; CHECK-NEXT:    [[CALL13:%.*]] = tail call noundef double @llvm.fabs.f64(double [[LOAD12]])
; CHECK-NEXT:    [[CALL14:%.*]] = tail call double @pow(double noundef [[CALL13]], double noundef [[ARG1]]) #[[ATTR3]], !tbaa [[INT_TBAA10]]
; CHECK-NEXT:    [[FADD]] = fadd double [[PHI10]], [[CALL14]]
; CHECK-NEXT:    [[ADD]] = add nuw nsw i64 [[PHI9]], 1
; CHECK-NEXT:    [[LOAD15:%.*]] = load i32, ptr [[GETELEMENTPTR]], align 8
; CHECK-NEXT:    [[ZEXT:%.*]] = zext i32 [[LOAD15]] to i64
; CHECK-NEXT:    [[ICMP16:%.*]] = icmp samesign ult i64 [[ADD]], [[ZEXT]]
; CHECK-NEXT:    br i1 [[ICMP16]], label %[[BB8]], label %[[BB5]], !llvm.loop [[LOOP30:![0-9]+]]
;
bb:
  %getelementptr = getelementptr inbounds nuw i8, ptr %arg, i64 72
  %load = load i32, ptr %getelementptr, align 8
  %icmp = icmp eq i32 %load, 0
  br i1 %icmp, label %bb6, label %bb2

bb2:                                              ; preds = %bb
  %getelementptr3 = getelementptr inbounds nuw i8, ptr %arg, i64 80
  %load4 = load ptr, ptr %getelementptr3, align 8, !tbaa !14
  br label %bb8

bb5:                                              ; preds = %bb8
  %phi = phi double [ %fadd, %bb8 ]
  br label %bb6

bb6:                                              ; preds = %bb5, %bb
  %phi7 = phi double [ 0.000000e+00, %bb ], [ %phi, %bb5 ]
  %fdiv = fdiv double 1.000000e+00, %arg1
  %call = tail call double @pow(double noundef %phi7, double noundef %fdiv) #3, !tbaa !10
  ret double %call

bb8:                                              ; preds = %bb8, %bb2
  %phi9 = phi i64 [ 0, %bb2 ], [ %add, %bb8 ]
  %phi10 = phi double [ 0.000000e+00, %bb2 ], [ %fadd, %bb8 ]
  %getelementptr11 = getelementptr inbounds nuw [8 x i8], ptr %load4, i64 %phi9
  %load12 = load double, ptr %getelementptr11, align 8
  %call13 = tail call noundef double @llvm.fabs.f64(double %load12)
  %call14 = tail call double @pow(double noundef %call13, double noundef %arg1) #3, !tbaa !10
  %fadd = fadd double %phi10, %call14
  %add = add nuw nsw i64 %phi9, 1
  %load15 = load i32, ptr %getelementptr, align 8
  %zext = zext i32 %load15 to i64
  %icmp16 = icmp samesign ult i64 %add, %zext
  br i1 %icmp16, label %bb8, label %bb5, !llvm.loop !30
}

; Function Attrs: mustprogress nocallback nofree nounwind willreturn memory(errnomem: write)
declare double @pow(double noundef, double noundef) local_unnamed_addr #1

; Function Attrs: nocallback nocreateundeforpoison nofree nosync nounwind speculatable willreturn memory(none)
declare double @llvm.fabs.f64(double) #2

attributes #0 = { uwtable "frame-pointer"="non-leaf-no-reserve" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="cortex-a57" "target-features"="+aes,+crc,+fp-armv8,+neon,+outline-atomics,+perfmon,+sha2,+v8a,-fmv" }
attributes #1 = { mustprogress nocallback nofree nounwind willreturn memory(errnomem: write) "frame-pointer"="non-leaf-no-reserve" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="cortex-a57" "target-features"="+aes,+crc,+fp-armv8,+neon,+outline-atomics,+perfmon,+sha2,+v8a,-fmv" }
attributes #2 = { nocallback nocreateundeforpoison nofree nosync nounwind speculatable willreturn memory(none) }
attributes #3 = { nounwind }

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!2, !3, !4, !5, !6, !7, !8}
!llvm.ident = !{!9}
!llvm.errno.tbaa = !{!10}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus, file: !1, producer: "clang version 23.0.0git (ssh://git-hexagon-lv.qualcomm.com:29418/llvm/llvm-project fa6bb24a9808ef39e1ecebfc7d42c885fca2261f)", isOptimized: true, runtimeVersion: 0, emissionKind: NoDebug, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "test.cc", directory: "well")
!2 = !{i32 2, !"Debug Info Version", i32 3}
!3 = !{i32 8, !"PIC Level", i32 2}
!4 = !{i32 7, !"PIE Level", i32 2}
!5 = !{i32 7, !"uwtable", i32 2}
!6 = !{i32 7, !"frame-pointer", i32 4}
!7 = !{i32 1, !"ThinLTO", i32 0}
!8 = !{i32 1, !"EnableSplitLTOUnit", i32 1}
!9 = !{!"clang version 23.0.0git (ssh://git-hexagon-lv.qualcomm.com:29418/llvm/llvm-project fa6bb24a9808ef39e1ecebfc7d42c885fca2261f)"}
!10 = !{!11, !11, i64 0}
!11 = !{!"int", !12, i64 0}
!12 = !{!"omnipotent char", !13, i64 0}
!13 = !{!"Simple C++ TBAA"}
!14 = !{!15, !29, i64 80}
!15 = !{!"sym1", !16, i64 0, !11, i64 72, !11, i64 76, !29, i64 80}
!16 = !{!"sym2", !11, i64 8, !17, i64 16, !28, i64 64}
!17 = !{!"sym3", !18, i64 0}
!18 = !{!"sym4", !19, i64 0}
!19 = !{!"sym5", !20, i64 0, !22, i64 8}
!20 = !{!"sym6", !21, i64 0}
!21 = !{!"sym7"}
!22 = !{!"sym8", !23, i64 0, !27, i64 32}
!23 = !{!"sym9", !24, i64 0, !25, i64 8, !25, i64 16, !25, i64 24}
!24 = !{!"sym10", !12, i64 0}
!25 = !{!"p1 sym9", !26, i64 0}
!26 = !{!"any pointer", !12, i64 0}
!27 = !{!"long", !12, i64 0}
!28 = !{!"p1 sym11", !26, i64 0}
!29 = !{!"p1 double", !26, i64 0}
!30 = distinct !{!30}
;.
; CHECK: [[INT_TBAA10]] = !{[[META11:![0-9]+]], [[META11]], i64 0}
; CHECK: [[META11]] = !{!"int", [[META12:![0-9]+]], i64 0}
; CHECK: [[META12]] = !{!"omnipotent char", [[META13:![0-9]+]], i64 0}
; CHECK: [[META13]] = !{!"Simple C++ TBAA"}
; CHECK: [[DOUBLEPTR_TBAA14]] = !{[[META15:![0-9]+]], [[META29:![0-9]+]], i64 80}
; CHECK: [[META15]] = !{!"sym1", [[META16:![0-9]+]], i64 0, [[META11]], i64 72, [[META11]], i64 76, [[META29]], i64 80}
; CHECK: [[META16]] = !{!"sym2", [[META11]], i64 8, [[META17:![0-9]+]], i64 16, [[META28:![0-9]+]], i64 64}
; CHECK: [[META17]] = !{!"sym3", [[META18:![0-9]+]], i64 0}
; CHECK: [[META18]] = !{!"sym4", [[META19:![0-9]+]], i64 0}
; CHECK: [[META19]] = !{!"sym5", [[META20:![0-9]+]], i64 0, [[META22:![0-9]+]], i64 8}
; CHECK: [[META20]] = !{!"sym6", [[META21:![0-9]+]], i64 0}
; CHECK: [[META21]] = !{!"sym7"}
; CHECK: [[META22]] = !{!"sym8", [[META23:![0-9]+]], i64 0, [[META27:![0-9]+]], i64 32}
; CHECK: [[META23]] = !{!"sym9", [[META24:![0-9]+]], i64 0, [[META25:![0-9]+]], i64 8, [[META25]], i64 16, [[META25]], i64 24}
; CHECK: [[META24]] = !{!"sym10", [[META12]], i64 0}
; CHECK: [[META25]] = !{!"p1 sym9", [[META26:![0-9]+]], i64 0}
; CHECK: [[META26]] = !{!"any pointer", [[META12]], i64 0}
; CHECK: [[META27]] = !{!"long", [[META12]], i64 0}
; CHECK: [[META28]] = !{!"p1 sym11", [[META26]], i64 0}
; CHECK: [[META29]] = !{!"p1 double", [[META26]], i64 0}
; CHECK: [[LOOP30]] = distinct !{[[LOOP30]]}
;.
