; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=loop-vectorize %s | FileCheck %s

; The loop should be vectorized. The vectorizer needs to prove
;   (A umin B) u<= A to establish memory safety from the dereferenceable
;   assumption.
;
; long n = umin(count, length);
; for (long i = 0; i < n; i++)
;   if (ptr[i] == 0) return null;
; ...
define ptr @main(i32 %length, ptr %ptr, i64 %0) #0 {
; CHECK-LABEL: define ptr @main(
; CHECK-SAME: i32 [[LENGTH:%.*]], ptr [[PTR:%.*]], i64 [[TMP0:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[NULL_CHECK0:%.*]] = icmp eq i64 [[TMP0]], 0
; CHECK-NEXT:    br i1 [[NULL_CHECK0]], label %[[DEOPT:.*]], label %[[PREHEADER:.*]]
; CHECK:       [[PREHEADER]]:
; CHECK-NEXT:    [[LENGTH_64:%.*]] = zext i32 [[LENGTH]] to i64
; CHECK-NEXT:    [[EXIT:%.*]] = call i64 @llvm.umin.i64(i64 [[TMP0]], i64 [[LENGTH_64]])
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "align"(ptr [[PTR]], i64 8), "dereferenceable"(ptr [[PTR]], i64 [[LENGTH_64]]) ]
; CHECK-NEXT:    [[NULL_CHECK:%.*]] = icmp eq i32 [[LENGTH]], 0
; CHECK-NEXT:    br i1 [[NULL_CHECK]], label %[[DEOPT]], label %[[SCALAR_PH:.*]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[EXIT]], 4
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH1:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[EXIT]], 4
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 [[EXIT]], [[N_MOD_VF]]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY_INTERIM:.*]] ]
; CHECK-NEXT:    [[ELEMENT_GEP:%.*]] = getelementptr i8, ptr [[PTR]], i64 [[IV]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i8>, ptr [[ELEMENT_GEP]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq <4 x i8> [[WIDE_LOAD]], zeroinitializer
; CHECK-NEXT:    [[TMP3:%.*]] = freeze <4 x i1> [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = call i1 @llvm.vector.reduce.or.v4i1(<4 x i1> [[TMP3]])
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[IV]], 4
; CHECK-NEXT:    [[TMP5:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP4]], label %[[VECTOR_EARLY_EXIT:.*]], label %[[VECTOR_BODY_INTERIM]]
; CHECK:       [[VECTOR_BODY_INTERIM]]:
; CHECK-NEXT:    br i1 [[TMP5]], label %[[MIDDLE_BLOCK:.*]], label %[[LOOP]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[EXIT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[DEOPT_LOOPEXIT:.*]], label %[[SCALAR_PH1]]
; CHECK:       [[VECTOR_EARLY_EXIT]]:
; CHECK-NEXT:    br label %[[FOUND:.*]]
; CHECK:       [[SCALAR_PH1]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[SCALAR_PH]] ]
; CHECK-NEXT:    br label %[[LOOP1:.*]]
; CHECK:       [[LOOP1]]:
; CHECK-NEXT:    [[IV1:%.*]] = phi i64 [ [[IV_NEXT:%.*]], %[[LATCH:.*]] ], [ [[BC_RESUME_VAL]], %[[SCALAR_PH1]] ]
; CHECK-NEXT:    [[ELEMENT_GEP1:%.*]] = getelementptr i8, ptr [[PTR]], i64 [[IV1]]
; CHECK-NEXT:    [[ELEMENT:%.*]] = load i8, ptr [[ELEMENT_GEP1]], align 1
; CHECK-NEXT:    [[FOUND_CHECK:%.*]] = icmp eq i8 [[ELEMENT]], 0
; CHECK-NEXT:    br i1 [[FOUND_CHECK]], label %[[FOUND]], label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[IV_NEXT]] = add i64 [[IV1]], 1
; CHECK-NEXT:    [[RANGE_CHECK:%.*]] = icmp ult i64 [[IV_NEXT]], [[EXIT]]
; CHECK-NEXT:    br i1 [[RANGE_CHECK]], label %[[LOOP1]], label %[[DEOPT_LOOPEXIT]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK:       [[FOUND]]:
; CHECK-NEXT:    ret ptr null
; CHECK:       [[DEOPT_LOOPEXIT]]:
; CHECK-NEXT:    br label %[[DEOPT]]
; CHECK:       [[DEOPT]]:
; CHECK-NEXT:    unreachable
;
entry:
  %null_check0 = icmp eq i64 %0, 0
  br i1 %null_check0, label %deopt, label %preheader

preheader:                                        ; preds = %entry
  %length.64 = zext i32 %length to i64
  %exit = call i64 @llvm.umin.i64(i64 %0, i64 %length.64)
  call void @llvm.assume(i1 true) [ "align"(ptr %ptr, i64 8), "dereferenceable"(ptr %ptr, i64 %length.64) ]
  %null_check = icmp eq i32 %length, 0
  br i1 %null_check, label %deopt, label %loop

loop:                                             ; preds = %latch, %preheader
  %iv = phi i64 [ %iv.next, %latch ], [ 0, %preheader ]
  %element_gep = getelementptr i8, ptr %ptr, i64 %iv
  %element = load i8, ptr %element_gep, align 1
  %found_check = icmp eq i8 %element, 0
  br i1 %found_check, label %found, label %latch

latch:                                            ; preds = %loop
  %iv.next = add i64 %iv, 1
  %range_check = icmp ult i64 %iv.next, %exit
  br i1 %range_check, label %loop, label %deopt

found:                                            ; preds = %loop
  ret ptr null

deopt:                                            ; preds = %latch, %preheader
  unreachable
}

declare i64 @llvm.umin.i64(i64, i64)

declare void @llvm.assume(i1 noundef)

attributes #0 = { nofree nosync }
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP3]] = distinct !{[[LOOP3]], [[META2]], [[META1]]}
;.
