; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals none --filter-out-after "^scalar.ph" --version 6
; RUN: opt %s -passes=loop-vectorize -force-vector-interleave=1 -force-vector-width=4 -enable-interleaved-mem-accesses -S | FileCheck %s
; RUN: opt %s -passes=loop-vectorize -force-vector-interleave=1 -force-vector-width=4 -enable-interleaved-mem-accesses -force-target-supports-scalable-vectors=true -scalable-vectorization=preferred -S | FileCheck %s --check-prefix=SCALABLE

define void @scalablevf(ptr %dst.start, i8 %a, i8 %b) {
; CHECK-LABEL: define void @scalablevf(
; CHECK-SAME: ptr [[DST_START:%.*]], i8 [[A:%.*]], i8 [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT1:%.*]] = insertelement <4 x i8> poison, i8 [[A]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT2:%.*]] = shufflevector <4 x i8> [[BROADCAST_SPLATINSERT1]], <4 x i8> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT2:%.*]] = insertelement <4 x i8> poison, i8 [[B]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x i8> [[BROADCAST_SPLATINSERT2]], <4 x i8> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[OFFSET_IDX:%.*]] = shl i64 [[INDEX]], 2
; CHECK-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[DST_START]], i64 [[OFFSET_IDX]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i8>, ptr [[NEXT_GEP]], align 1
; CHECK-NEXT:    [[TMP0:%.*]] = mul nuw <4 x i8> [[WIDE_LOAD]], [[BROADCAST_SPLAT]]
; CHECK-NEXT:    [[TMP1:%.*]] = udiv <4 x i8> [[TMP0]], splat (i8 -1)
; CHECK-NEXT:    [[TMP2:%.*]] = add <4 x i8> [[BROADCAST_SPLAT2]], [[TMP1]]
; CHECK-NEXT:    store <4 x i8> [[TMP2]], ptr [[NEXT_GEP]], align 1
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 1
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[INDEX_NEXT]], 64
; CHECK-NEXT:    br i1 [[TMP3]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
; SCALABLE-LABEL: define void @scalablevf(
; SCALABLE-SAME: ptr [[DST_START:%.*]], i8 [[A:%.*]], i8 [[B:%.*]]) {
; SCALABLE-NEXT:  [[ENTRY:.*:]]
; SCALABLE-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; SCALABLE-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; SCALABLE-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 64, [[TMP1]]
; SCALABLE-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; SCALABLE:       [[VECTOR_PH]]:
; SCALABLE-NEXT:    [[N_MOD_VF:%.*]] = urem i64 64, [[TMP0]]
; SCALABLE-NEXT:    [[N_VEC:%.*]] = sub i64 64, [[N_MOD_VF]]
; SCALABLE-NEXT:    [[TMP5:%.*]] = shl i64 [[N_VEC]], 2
; SCALABLE-NEXT:    [[TMP6:%.*]] = getelementptr i8, ptr [[DST_START]], i64 [[TMP5]]
; SCALABLE-NEXT:    [[BROADCAST_SPLATINSERT1:%.*]] = insertelement <vscale x 4 x i8> poison, i8 [[A]], i64 0
; SCALABLE-NEXT:    [[BROADCAST_SPLAT2:%.*]] = shufflevector <vscale x 4 x i8> [[BROADCAST_SPLATINSERT1]], <vscale x 4 x i8> poison, <vscale x 4 x i32> zeroinitializer
; SCALABLE-NEXT:    [[BROADCAST_SPLATINSERT2:%.*]] = insertelement <vscale x 4 x i8> poison, i8 [[B]], i64 0
; SCALABLE-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 4 x i8> [[BROADCAST_SPLATINSERT2]], <vscale x 4 x i8> poison, <vscale x 4 x i32> zeroinitializer
; SCALABLE-NEXT:    br label %[[VECTOR_BODY:.*]]
; SCALABLE:       [[VECTOR_BODY]]:
; SCALABLE-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; SCALABLE-NEXT:    [[OFFSET_IDX:%.*]] = shl i64 [[INDEX]], 2
; SCALABLE-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[DST_START]], i64 [[OFFSET_IDX]]
; SCALABLE-NEXT:    [[TMP10:%.*]] = load <vscale x 4 x i8>, ptr [[NEXT_GEP]], align 1
; SCALABLE-NEXT:    [[TMP20:%.*]] = mul nuw <vscale x 4 x i8> [[TMP10]], [[BROADCAST_SPLAT]]
; SCALABLE-NEXT:    [[TMP21:%.*]] = udiv <vscale x 4 x i8> [[TMP20]], splat (i8 -1)
; SCALABLE-NEXT:    [[TMP22:%.*]] = add <vscale x 4 x i8> [[BROADCAST_SPLAT2]], [[TMP21]]
; SCALABLE-NEXT:    store <vscale x 4 x i8> [[TMP22]], ptr [[NEXT_GEP]], align 1
; SCALABLE-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; SCALABLE-NEXT:    [[TMP23:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; SCALABLE-NEXT:    br i1 [[TMP23]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; SCALABLE:       [[MIDDLE_BLOCK]]:
; SCALABLE-NEXT:    [[CMP_N:%.*]] = icmp eq i64 64, [[N_VEC]]
; SCALABLE-NEXT:    br i1 [[CMP_N]], [[EXIT:label %.*]], label %[[SCALAR_PH]]
; SCALABLE:       [[SCALAR_PH]]:
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %dst = phi ptr [ %dst.start, %entry ], [ %dst.next, %loop ]
  %dst.next = getelementptr inbounds nuw i8, ptr %dst, i64 4
  %load.dst = load i8, ptr %dst, align 1
  %mul.dst.0 = mul nuw i8 %load.dst, %b
  %udiv.0 = udiv i8 %mul.dst.0, 255
  %val.0 = add i8 %a, %udiv.0
  store i8 %val.0, ptr %dst, align 1
  %gep.dst.1 = getelementptr inbounds nuw i8, ptr %dst, i64 1
  %load.dst.1 = load i8, ptr %gep.dst.1, align 1
  %mul.dst.1 = mul nuw i8 %load.dst.1, %b
  %udiv.1 = udiv i8 %mul.dst.1, 255
  %val.1 = add i8 %a, %udiv.1
  store i8 %val.1, ptr %gep.dst.1, align 1
  %gep.dst.2 = getelementptr inbounds nuw i8, ptr %dst, i64 2
  %load.dst.2 = load i8, ptr %gep.dst.2, align 1
  %mul.dst.2 = mul nuw i8 %load.dst.2, %b
  %udiv.2 = udiv i8 %mul.dst.2, 255
  %val.2 = add i8 %a, %udiv.2
  store i8 %val.2, ptr %gep.dst.2, align 1
  %gep.dst.3 = getelementptr inbounds nuw i8, ptr %dst, i64 3
  %load.dst.3 = load i8, ptr %gep.dst.3, align 1
  %mul.dst.3 = mul nuw i8 %load.dst.3, %b
  %udiv.3 = udiv i8 %mul.dst.3, 255
  %val.3 = add i8 %a, %udiv.3
  store i8 %val.3, ptr %gep.dst.3, align 1
  %iv.next = add i64 %iv, 4
  %exit.cond = icmp eq i64 %iv.next, 256
  br i1 %exit.cond, label %exit, label %loop

exit:
  ret void
}

; Each field uses a distinct live-in. We cannot use BuildVector to combine them for scalable vectors.
define void @scalablevf_distinct_args(ptr %dst.start, i8 %a0, i8 %a1, i8 %a2, i8 %a3, i8 %b0, i8 %b1, i8 %b2, i8 %b3) {
; CHECK-LABEL: define void @scalablevf_distinct_args(
; CHECK-SAME: ptr [[DST_START:%.*]], i8 [[A0:%.*]], i8 [[A1:%.*]], i8 [[A2:%.*]], i8 [[A3:%.*]], i8 [[B0:%.*]], i8 [[B1:%.*]], i8 [[B2:%.*]], i8 [[B3:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[TMP13:%.*]] = insertelement <4 x i8> poison, i8 [[A0]], i32 0
; CHECK-NEXT:    [[TMP14:%.*]] = insertelement <4 x i8> [[TMP13]], i8 [[A1]], i32 1
; CHECK-NEXT:    [[TMP15:%.*]] = insertelement <4 x i8> [[TMP14]], i8 [[A2]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = insertelement <4 x i8> [[TMP15]], i8 [[A3]], i32 3
; CHECK-NEXT:    [[TMP4:%.*]] = insertelement <4 x i8> poison, i8 [[B0]], i32 0
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <4 x i8> [[TMP4]], i8 [[B1]], i32 1
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <4 x i8> [[TMP5]], i8 [[B2]], i32 2
; CHECK-NEXT:    [[TMP7:%.*]] = insertelement <4 x i8> [[TMP6]], i8 [[B3]], i32 3
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP8:%.*]] = shl i64 [[INDEX]], 2
; CHECK-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[DST_START]], i64 [[TMP8]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i8>, ptr [[NEXT_GEP]], align 1
; CHECK-NEXT:    [[TMP9:%.*]] = mul nuw <4 x i8> [[WIDE_LOAD]], [[TMP7]]
; CHECK-NEXT:    [[TMP10:%.*]] = udiv <4 x i8> [[TMP9]], splat (i8 -1)
; CHECK-NEXT:    [[TMP11:%.*]] = add <4 x i8> [[TMP3]], [[TMP10]]
; CHECK-NEXT:    store <4 x i8> [[TMP11]], ptr [[NEXT_GEP]], align 1
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 1
; CHECK-NEXT:    [[TMP12:%.*]] = icmp eq i64 [[INDEX_NEXT]], 64
; CHECK-NEXT:    br i1 [[TMP12]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
; SCALABLE-LABEL: define void @scalablevf_distinct_args(
; SCALABLE-SAME: ptr [[DST_START:%.*]], i8 [[A0:%.*]], i8 [[A1:%.*]], i8 [[A2:%.*]], i8 [[A3:%.*]], i8 [[B0:%.*]], i8 [[B1:%.*]], i8 [[B2:%.*]], i8 [[B3:%.*]]) {
; SCALABLE-NEXT:  [[ENTRY:.*:]]
; SCALABLE-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; SCALABLE-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; SCALABLE-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 64, [[TMP1]]
; SCALABLE-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; SCALABLE:       [[VECTOR_PH]]:
; SCALABLE-NEXT:    [[TMP2:%.*]] = shl nuw i64 [[TMP0]], 2
; SCALABLE-NEXT:    [[N_MOD_VF:%.*]] = urem i64 64, [[TMP2]]
; SCALABLE-NEXT:    [[N_VEC:%.*]] = sub i64 64, [[N_MOD_VF]]
; SCALABLE-NEXT:    [[TMP3:%.*]] = shl i64 [[N_VEC]], 2
; SCALABLE-NEXT:    [[TMP4:%.*]] = getelementptr i8, ptr [[DST_START]], i64 [[TMP3]]
; SCALABLE-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <vscale x 4 x i8> poison, i8 [[B0]], i64 0
; SCALABLE-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <vscale x 4 x i8> [[BROADCAST_SPLATINSERT]], <vscale x 4 x i8> poison, <vscale x 4 x i32> zeroinitializer
; SCALABLE-NEXT:    [[BROADCAST_SPLATINSERT1:%.*]] = insertelement <vscale x 4 x i8> poison, i8 [[A0]], i64 0
; SCALABLE-NEXT:    [[BROADCAST_SPLAT2:%.*]] = shufflevector <vscale x 4 x i8> [[BROADCAST_SPLATINSERT1]], <vscale x 4 x i8> poison, <vscale x 4 x i32> zeroinitializer
; SCALABLE-NEXT:    [[BROADCAST_SPLATINSERT3:%.*]] = insertelement <vscale x 4 x i8> poison, i8 [[B1]], i64 0
; SCALABLE-NEXT:    [[BROADCAST_SPLAT4:%.*]] = shufflevector <vscale x 4 x i8> [[BROADCAST_SPLATINSERT3]], <vscale x 4 x i8> poison, <vscale x 4 x i32> zeroinitializer
; SCALABLE-NEXT:    [[BROADCAST_SPLATINSERT5:%.*]] = insertelement <vscale x 4 x i8> poison, i8 [[A1]], i64 0
; SCALABLE-NEXT:    [[BROADCAST_SPLAT6:%.*]] = shufflevector <vscale x 4 x i8> [[BROADCAST_SPLATINSERT5]], <vscale x 4 x i8> poison, <vscale x 4 x i32> zeroinitializer
; SCALABLE-NEXT:    [[BROADCAST_SPLATINSERT7:%.*]] = insertelement <vscale x 4 x i8> poison, i8 [[B2]], i64 0
; SCALABLE-NEXT:    [[BROADCAST_SPLAT8:%.*]] = shufflevector <vscale x 4 x i8> [[BROADCAST_SPLATINSERT7]], <vscale x 4 x i8> poison, <vscale x 4 x i32> zeroinitializer
; SCALABLE-NEXT:    [[BROADCAST_SPLATINSERT9:%.*]] = insertelement <vscale x 4 x i8> poison, i8 [[A2]], i64 0
; SCALABLE-NEXT:    [[BROADCAST_SPLAT10:%.*]] = shufflevector <vscale x 4 x i8> [[BROADCAST_SPLATINSERT9]], <vscale x 4 x i8> poison, <vscale x 4 x i32> zeroinitializer
; SCALABLE-NEXT:    [[BROADCAST_SPLATINSERT11:%.*]] = insertelement <vscale x 4 x i8> poison, i8 [[B3]], i64 0
; SCALABLE-NEXT:    [[BROADCAST_SPLAT12:%.*]] = shufflevector <vscale x 4 x i8> [[BROADCAST_SPLATINSERT11]], <vscale x 4 x i8> poison, <vscale x 4 x i32> zeroinitializer
; SCALABLE-NEXT:    [[BROADCAST_SPLATINSERT13:%.*]] = insertelement <vscale x 4 x i8> poison, i8 [[A3]], i64 0
; SCALABLE-NEXT:    [[BROADCAST_SPLAT14:%.*]] = shufflevector <vscale x 4 x i8> [[BROADCAST_SPLATINSERT13]], <vscale x 4 x i8> poison, <vscale x 4 x i32> zeroinitializer
; SCALABLE-NEXT:    br label %[[VECTOR_BODY:.*]]
; SCALABLE:       [[VECTOR_BODY]]:
; SCALABLE-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; SCALABLE-NEXT:    [[TMP5:%.*]] = shl i64 [[INDEX]], 2
; SCALABLE-NEXT:    [[NEXT_GEP:%.*]] = getelementptr i8, ptr [[DST_START]], i64 [[TMP5]]
; SCALABLE-NEXT:    [[WIDE_VEC:%.*]] = load <vscale x 16 x i8>, ptr [[NEXT_GEP]], align 1
; SCALABLE-NEXT:    [[STRIDED_VEC:%.*]] = call { <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8> } @llvm.vector.deinterleave4.nxv16i8(<vscale x 16 x i8> [[WIDE_VEC]])
; SCALABLE-NEXT:    [[TMP6:%.*]] = extractvalue { <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8> } [[STRIDED_VEC]], 0
; SCALABLE-NEXT:    [[TMP7:%.*]] = extractvalue { <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8> } [[STRIDED_VEC]], 1
; SCALABLE-NEXT:    [[TMP8:%.*]] = extractvalue { <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8> } [[STRIDED_VEC]], 2
; SCALABLE-NEXT:    [[TMP9:%.*]] = extractvalue { <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8>, <vscale x 4 x i8> } [[STRIDED_VEC]], 3
; SCALABLE-NEXT:    [[TMP10:%.*]] = mul nuw <vscale x 4 x i8> [[TMP6]], [[BROADCAST_SPLAT]]
; SCALABLE-NEXT:    [[TMP11:%.*]] = udiv <vscale x 4 x i8> [[TMP10]], splat (i8 -1)
; SCALABLE-NEXT:    [[TMP12:%.*]] = add <vscale x 4 x i8> [[BROADCAST_SPLAT2]], [[TMP11]]
; SCALABLE-NEXT:    [[TMP13:%.*]] = mul nuw <vscale x 4 x i8> [[TMP7]], [[BROADCAST_SPLAT4]]
; SCALABLE-NEXT:    [[TMP14:%.*]] = udiv <vscale x 4 x i8> [[TMP13]], splat (i8 -1)
; SCALABLE-NEXT:    [[TMP15:%.*]] = add <vscale x 4 x i8> [[BROADCAST_SPLAT6]], [[TMP14]]
; SCALABLE-NEXT:    [[TMP16:%.*]] = mul nuw <vscale x 4 x i8> [[TMP8]], [[BROADCAST_SPLAT8]]
; SCALABLE-NEXT:    [[TMP17:%.*]] = udiv <vscale x 4 x i8> [[TMP16]], splat (i8 -1)
; SCALABLE-NEXT:    [[TMP18:%.*]] = add <vscale x 4 x i8> [[BROADCAST_SPLAT10]], [[TMP17]]
; SCALABLE-NEXT:    [[TMP19:%.*]] = mul nuw <vscale x 4 x i8> [[TMP9]], [[BROADCAST_SPLAT12]]
; SCALABLE-NEXT:    [[TMP20:%.*]] = udiv <vscale x 4 x i8> [[TMP19]], splat (i8 -1)
; SCALABLE-NEXT:    [[TMP21:%.*]] = add <vscale x 4 x i8> [[BROADCAST_SPLAT14]], [[TMP20]]
; SCALABLE-NEXT:    [[INTERLEAVED_VEC:%.*]] = call <vscale x 16 x i8> @llvm.vector.interleave4.nxv16i8(<vscale x 4 x i8> [[TMP12]], <vscale x 4 x i8> [[TMP15]], <vscale x 4 x i8> [[TMP18]], <vscale x 4 x i8> [[TMP21]])
; SCALABLE-NEXT:    store <vscale x 16 x i8> [[INTERLEAVED_VEC]], ptr [[NEXT_GEP]], align 1
; SCALABLE-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP2]]
; SCALABLE-NEXT:    [[TMP22:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; SCALABLE-NEXT:    br i1 [[TMP22]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; SCALABLE:       [[MIDDLE_BLOCK]]:
; SCALABLE-NEXT:    [[CMP_N:%.*]] = icmp eq i64 64, [[N_VEC]]
; SCALABLE-NEXT:    br i1 [[CMP_N]], [[EXIT:label %.*]], label %[[SCALAR_PH]]
; SCALABLE:       [[SCALAR_PH]]:
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %dst = phi ptr [ %dst.start, %entry ], [ %dst.next, %loop ]
  %dst.next = getelementptr inbounds nuw i8, ptr %dst, i64 4
  %load.dst = load i8, ptr %dst, align 1
  %mul.dst.0 = mul nuw i8 %load.dst, %b0
  %udiv.0 = udiv i8 %mul.dst.0, 255
  %val.0 = add i8 %a0, %udiv.0
  store i8 %val.0, ptr %dst, align 1
  %gep.dst.1 = getelementptr inbounds nuw i8, ptr %dst, i64 1
  %load.dst.1 = load i8, ptr %gep.dst.1, align 1
  %mul.dst.1 = mul nuw i8 %load.dst.1, %b1
  %udiv.1 = udiv i8 %mul.dst.1, 255
  %val.1 = add i8 %a1, %udiv.1
  store i8 %val.1, ptr %gep.dst.1, align 1
  %gep.dst.2 = getelementptr inbounds nuw i8, ptr %dst, i64 2
  %load.dst.2 = load i8, ptr %gep.dst.2, align 1
  %mul.dst.2 = mul nuw i8 %load.dst.2, %b2
  %udiv.2 = udiv i8 %mul.dst.2, 255
  %val.2 = add i8 %a2, %udiv.2
  store i8 %val.2, ptr %gep.dst.2, align 1
  %gep.dst.3 = getelementptr inbounds nuw i8, ptr %dst, i64 3
  %load.dst.3 = load i8, ptr %gep.dst.3, align 1
  %mul.dst.3 = mul nuw i8 %load.dst.3, %b3
  %udiv.3 = udiv i8 %mul.dst.3, 255
  %val.3 = add i8 %a3, %udiv.3
  store i8 %val.3, ptr %gep.dst.3, align 1
  %iv.next = add i64 %iv, 4
  %exit.cond = icmp eq i64 %iv.next, 256
  br i1 %exit.cond, label %exit, label %loop

exit:
  ret void
}
