; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -passes=loop-vectorize -force-vector-width=2 -S < %s | FileCheck %s

; NOTE: This is a focused reproducer for OpenMP declare-simd style VFABI mapping.
; The math libcall is marked no-builtin (as clang emits for declare-simd) and
; memory(none), matching the readnone effects clang gives these libcalls under
; fast-math. LAA must honor the VFABI mapping and vectorize the loop even though
; the scalar callee is no-builtin: a readnone call carries no dependence edge.

define void @test_vector_abi(ptr noalias %x, ptr %c) #0 {
; CHECK-LABEL: define void @test_vector_abi(
; CHECK-SAME: ptr noalias [[X:%.*]], ptr [[C:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds double, ptr [[C]], i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <2 x double>, ptr [[TMP0]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = call <2 x double> @vector_acosh(<2 x double> [[WIDE_LOAD]])
; CHECK-NEXT:    [[TMP2:%.*]] = getelementptr inbounds double, ptr [[X]], i64 [[INDEX]]
; CHECK-NEXT:    store <2 x double> [[TMP1]], ptr [[TMP2]], align 8
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 2
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1000
; CHECK-NEXT:    br i1 [[TMP3]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %loop ]
  %src = getelementptr inbounds double, ptr %c, i64 %iv
  %v = load double, ptr %src, align 8
  %r = tail call double @acosh(double noundef %v) #2
  %dst = getelementptr inbounds double, ptr %x, i64 %iv
  store double %r, ptr %dst, align 8
  %iv.next = add nuw nsw i64 %iv, 1
  %done = icmp eq i64 %iv.next, 1000
  br i1 %done, label %exit, label %loop, !llvm.loop !0

exit:
  ret void
}


declare double @acosh(double noundef) #1

declare <2 x double> @vector_acosh(<2 x double>)

attributes #0 = { noinline nounwind strictfp }
attributes #1 = { nounwind memory(none) "_ZGV_LLVM_N2v_acosh" "no-builtins" "vector-function-abi-variant"="_ZGV_LLVM_N2v_acosh(vector_acosh)" }
attributes #2 = { nobuiltin nounwind strictfp memory(none) "no-builtins" }

!0 = distinct !{!0, !1}
!1 = !{!"llvm.loop.vectorize.enable", i1 true}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]], [[META2:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META2]] = !{!"llvm.loop.unroll.runtime.disable"}
;.
