; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S < %s -passes='pseudo-probe,loop-vectorize' -force-vector-width=8 -force-vector-interleave=1 | FileCheck %s

target datalayout = "e-m:o-i64:64-i128:128-n32:64-S128"

define i32 @quant_4x4(ptr noundef captures(none) %dct, ptr noundef readonly captures(none) %mf, ptr noundef readonly captures(none) %bias) {
; CHECK-LABEL: define i32 @quant_4x4(
; CHECK-SAME: ptr noundef captures(none) [[DCT:%.*]], ptr noundef readonly captures(none) [[MF:%.*]], ptr noundef readonly captures(none) [[BIAS:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @llvm.pseudoprobe(i64 -6440704332784127821, i64 1, i32 0, i64 -1)
; CHECK-NEXT:    br label %[[VECTOR_MEMCHECK:.*]]
; CHECK:       [[VECTOR_MEMCHECK]]:
; CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr i8, ptr [[DCT]], i64 32
; CHECK-NEXT:    [[SCEVGEP1:%.*]] = getelementptr i8, ptr [[BIAS]], i64 32
; CHECK-NEXT:    [[SCEVGEP2:%.*]] = getelementptr i8, ptr [[MF]], i64 32
; CHECK-NEXT:    [[BOUND0:%.*]] = icmp ult ptr [[DCT]], [[SCEVGEP1]]
; CHECK-NEXT:    [[BOUND1:%.*]] = icmp ult ptr [[BIAS]], [[SCEVGEP]]
; CHECK-NEXT:    [[FOUND_CONFLICT:%.*]] = and i1 [[BOUND0]], [[BOUND1]]
; CHECK-NEXT:    [[BOUND03:%.*]] = icmp ult ptr [[DCT]], [[SCEVGEP2]]
; CHECK-NEXT:    [[BOUND14:%.*]] = icmp ult ptr [[MF]], [[SCEVGEP]]
; CHECK-NEXT:    [[FOUND_CONFLICT5:%.*]] = and i1 [[BOUND03]], [[BOUND14]]
; CHECK-NEXT:    [[CONFLICT_RDX:%.*]] = or i1 [[FOUND_CONFLICT]], [[FOUND_CONFLICT5]]
; CHECK-NEXT:    br i1 [[CONFLICT_RDX]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <8 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[BIN_RDX:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds nuw [2 x i8], ptr [[DCT]], i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD6:%.*]] = load <8 x i16>, ptr [[TMP0]], align 2, !tbaa [[SHORT_TBAA1:![0-9]+]], !alias.scope [[META5:![0-9]+]], !noalias [[META8:![0-9]+]]
; CHECK-NEXT:    [[TMP2:%.*]] = sext <8 x i16> [[WIDE_LOAD6]] to <8 x i32>
; CHECK-NEXT:    [[TMP4:%.*]] = icmp sgt <8 x i16> [[WIDE_LOAD6]], zeroinitializer
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds nuw [2 x i8], ptr [[BIAS]], i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD9:%.*]] = load <8 x i16>, ptr [[TMP3]], align 2, !tbaa [[SHORT_TBAA1]], !alias.scope [[META11:![0-9]+]]
; CHECK-NEXT:    [[TMP9:%.*]] = zext <8 x i16> [[WIDE_LOAD9]] to <8 x i32>
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds nuw [2 x i8], ptr [[MF]], i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD10:%.*]] = load <8 x i16>, ptr [[TMP5]], align 2, !tbaa [[SHORT_TBAA1]], !alias.scope [[META12:![0-9]+]]
; CHECK-NEXT:    [[TMP10:%.*]] = zext <8 x i16> [[WIDE_LOAD10]] to <8 x i32>
; CHECK-NEXT:    call void @llvm.pseudoprobe(i64 -6440704332784127821, i64 3, i32 0, i64 -1)
; CHECK-NEXT:    call void @llvm.pseudoprobe(i64 -6440704332784127821, i64 3, i32 0, i64 -1)
; CHECK-NEXT:    call void @llvm.pseudoprobe(i64 -6440704332784127821, i64 3, i32 0, i64 -1)
; CHECK-NEXT:    call void @llvm.pseudoprobe(i64 -6440704332784127821, i64 3, i32 0, i64 -1)
; CHECK-NEXT:    call void @llvm.pseudoprobe(i64 -6440704332784127821, i64 3, i32 0, i64 -1)
; CHECK-NEXT:    call void @llvm.pseudoprobe(i64 -6440704332784127821, i64 3, i32 0, i64 -1)
; CHECK-NEXT:    call void @llvm.pseudoprobe(i64 -6440704332784127821, i64 3, i32 0, i64 -1)
; CHECK-NEXT:    call void @llvm.pseudoprobe(i64 -6440704332784127821, i64 3, i32 0, i64 -1)
; CHECK-NEXT:    [[TMP12:%.*]] = sub nsw <8 x i32> [[TMP9]], [[TMP2]]
; CHECK-NEXT:    [[TMP14:%.*]] = mul nsw <8 x i32> [[TMP12]], [[TMP10]]
; CHECK-NEXT:    [[TMP16:%.*]] = lshr <8 x i32> [[TMP14]], splat (i32 16)
; CHECK-NEXT:    [[TMP18:%.*]] = trunc nuw nsw <8 x i32> [[TMP16]] to <8 x i16>
; CHECK-NEXT:    [[TMP20:%.*]] = sub nsw <8 x i16> zeroinitializer, [[TMP18]]
; CHECK-NEXT:    [[TMP22:%.*]] = add nuw nsw <8 x i32> [[TMP9]], [[TMP2]]
; CHECK-NEXT:    [[TMP24:%.*]] = mul nuw nsw <8 x i32> [[TMP22]], [[TMP10]]
; CHECK-NEXT:    [[TMP26:%.*]] = lshr <8 x i32> [[TMP24]], splat (i32 16)
; CHECK-NEXT:    [[TMP28:%.*]] = trunc nuw nsw <8 x i32> [[TMP26]] to <8 x i16>
; CHECK-NEXT:    [[PREDPHI11:%.*]] = select <8 x i1> [[TMP4]], <8 x i16> [[TMP28]], <8 x i16> [[TMP20]]
; CHECK-NEXT:    store <8 x i16> [[PREDPHI11]], ptr [[TMP0]], align 2, !tbaa [[SHORT_TBAA1]], !alias.scope [[META5]], !noalias [[META8]]
; CHECK-NEXT:    [[TMP30:%.*]] = sext <8 x i16> [[PREDPHI11]] to <8 x i32>
; CHECK-NEXT:    [[BIN_RDX]] = or <8 x i32> [[VEC_PHI]], [[TMP30]]
; CHECK-NEXT:    call void @llvm.pseudoprobe(i64 -6440704332784127821, i64 6, i32 0, i64 -1)
; CHECK-NEXT:    call void @llvm.pseudoprobe(i64 -6440704332784127821, i64 6, i32 0, i64 -1)
; CHECK-NEXT:    call void @llvm.pseudoprobe(i64 -6440704332784127821, i64 6, i32 0, i64 -1)
; CHECK-NEXT:    call void @llvm.pseudoprobe(i64 -6440704332784127821, i64 6, i32 0, i64 -1)
; CHECK-NEXT:    call void @llvm.pseudoprobe(i64 -6440704332784127821, i64 6, i32 0, i64 -1)
; CHECK-NEXT:    call void @llvm.pseudoprobe(i64 -6440704332784127821, i64 6, i32 0, i64 -1)
; CHECK-NEXT:    call void @llvm.pseudoprobe(i64 -6440704332784127821, i64 6, i32 0, i64 -1)
; CHECK-NEXT:    call void @llvm.pseudoprobe(i64 -6440704332784127821, i64 6, i32 0, i64 -1)
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 8
; CHECK-NEXT:    [[TMP19:%.*]] = icmp eq i64 [[INDEX_NEXT]], 16
; CHECK-NEXT:    br i1 [[TMP19]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP13:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[TMP32:%.*]] = call i32 @llvm.vector.reduce.or.v8i32(<8 x i32> [[BIN_RDX]])
; CHECK-NEXT:    br label %[[FOR_COND_CLEANUP:.*]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND_CLEANUP]]:
; CHECK-NEXT:    [[OR_LCSSA:%.*]] = phi i32 [ [[OR:%.*]], %[[IF_END:.*]] ], [ [[TMP32]], %[[MIDDLE_BLOCK]] ]
; CHECK-NEXT:    [[TOBOOL:%.*]] = icmp ne i32 [[OR_LCSSA]], 0
; CHECK-NEXT:    [[LNOT_EXT:%.*]] = zext i1 [[TOBOOL]] to i32
; CHECK-NEXT:    call void @llvm.pseudoprobe(i64 -6440704332784127821, i64 2, i32 0, i64 -1)
; CHECK-NEXT:    ret i32 [[LNOT_EXT]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ 0, %[[SCALAR_PH]] ], [ [[INDVARS_IV_NEXT:%.*]], %[[IF_END]] ]
; CHECK-NEXT:    [[NZ_053:%.*]] = phi i32 [ 0, %[[SCALAR_PH]] ], [ [[OR]], %[[IF_END]] ]
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds nuw [2 x i8], ptr [[DCT]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[TMP33:%.*]] = load i16, ptr [[ARRAYIDX]], align 2, !tbaa [[SHORT_TBAA1]]
; CHECK-NEXT:    [[CONV:%.*]] = sext i16 [[TMP33]] to i32
; CHECK-NEXT:    [[CMP1:%.*]] = icmp sgt i16 [[TMP33]], 0
; CHECK-NEXT:    [[ARRAYIDX4:%.*]] = getelementptr inbounds nuw [2 x i8], ptr [[BIAS]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[TMP34:%.*]] = load i16, ptr [[ARRAYIDX4]], align 2, !tbaa [[SHORT_TBAA1]]
; CHECK-NEXT:    [[CONV5:%.*]] = zext i16 [[TMP34]] to i32
; CHECK-NEXT:    [[ARRAYIDX10:%.*]] = getelementptr inbounds nuw [2 x i8], ptr [[MF]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[TMP35:%.*]] = load i16, ptr [[ARRAYIDX10]], align 2, !tbaa [[SHORT_TBAA1]]
; CHECK-NEXT:    [[CONV11:%.*]] = zext i16 [[TMP35]] to i32
; CHECK-NEXT:    call void @llvm.pseudoprobe(i64 -6440704332784127821, i64 3, i32 0, i64 -1)
; CHECK-NEXT:    br i1 [[CMP1]], label %[[IF_THEN:.*]], label %[[IF_ELSE:.*]]
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    [[ADD:%.*]] = add nuw nsw i32 [[CONV5]], [[CONV]]
; CHECK-NEXT:    [[MUL:%.*]] = mul nuw nsw i32 [[ADD]], [[CONV11]]
; CHECK-NEXT:    [[SHR:%.*]] = lshr i32 [[MUL]], 16
; CHECK-NEXT:    [[CONV12:%.*]] = trunc nuw nsw i32 [[SHR]] to i16
; CHECK-NEXT:    call void @llvm.pseudoprobe(i64 -6440704332784127821, i64 4, i32 0, i64 -1)
; CHECK-NEXT:    br label %[[IF_END]]
; CHECK:       [[IF_ELSE]]:
; CHECK-NEXT:    [[SUB:%.*]] = sub nsw i32 [[CONV5]], [[CONV]]
; CHECK-NEXT:    [[MUL24:%.*]] = mul nsw i32 [[SUB]], [[CONV11]]
; CHECK-NEXT:    [[SHR25:%.*]] = lshr i32 [[MUL24]], 16
; CHECK-NEXT:    [[TMP36:%.*]] = trunc nuw nsw i32 [[SHR25]] to i16
; CHECK-NEXT:    [[CONV27:%.*]] = sub nsw i16 0, [[TMP36]]
; CHECK-NEXT:    call void @llvm.pseudoprobe(i64 -6440704332784127821, i64 5, i32 0, i64 -1)
; CHECK-NEXT:    br label %[[IF_END]]
; CHECK:       [[IF_END]]:
; CHECK-NEXT:    [[STOREMERGE:%.*]] = phi i16 [ [[CONV27]], %[[IF_ELSE]] ], [ [[CONV12]], %[[IF_THEN]] ]
; CHECK-NEXT:    store i16 [[STOREMERGE]], ptr [[ARRAYIDX]], align 2, !tbaa [[SHORT_TBAA1]]
; CHECK-NEXT:    [[CONV32:%.*]] = sext i16 [[STOREMERGE]] to i32
; CHECK-NEXT:    [[OR]] = or i32 [[NZ_053]], [[CONV32]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add nuw nsw i64 [[INDVARS_IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 16
; CHECK-NEXT:    call void @llvm.pseudoprobe(i64 -6440704332784127821, i64 6, i32 0, i64 -1)
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]], !llvm.loop [[LOOP17:![0-9]+]]
;
entry:
  br label %for.body

for.cond.cleanup:
  %or.lcssa = phi i32 [ %or, %if.end ]
  %tobool = icmp ne i32 %or.lcssa, 0
  %lnot.ext = zext i1 %tobool to i32
  ret i32 %lnot.ext

for.body:
  %indvars.iv = phi i64 [ 0, %entry ], [ %indvars.iv.next, %if.end ]
  %nz.053 = phi i32 [ 0, %entry ], [ %or, %if.end ]
  %arrayidx = getelementptr inbounds nuw [2 x i8], ptr %dct, i64 %indvars.iv
  %0 = load i16, ptr %arrayidx, align 2, !tbaa !0
  %conv = sext i16 %0 to i32
  %cmp1 = icmp sgt i16 %0, 0
  %arrayidx4 = getelementptr inbounds nuw [2 x i8], ptr %bias, i64 %indvars.iv
  %1 = load i16, ptr %arrayidx4, align 2, !tbaa !0
  %conv5 = zext i16 %1 to i32
  %arrayidx10 = getelementptr inbounds nuw [2 x i8], ptr %mf, i64 %indvars.iv
  %2 = load i16, ptr %arrayidx10, align 2, !tbaa !0
  %conv11 = zext i16 %2 to i32
  br i1 %cmp1, label %if.then, label %if.else

if.then:
  %add = add nuw nsw i32 %conv5, %conv
  %mul = mul nuw nsw i32 %add, %conv11
  %shr = lshr i32 %mul, 16
  %conv12 = trunc nuw nsw i32 %shr to i16
  br label %if.end

if.else:
  %sub = sub nsw i32 %conv5, %conv
  %mul24 = mul nsw i32 %sub, %conv11
  %shr25 = lshr i32 %mul24, 16
  %3 = trunc nuw nsw i32 %shr25 to i16
  %conv27 = sub nsw i16 0, %3
  br label %if.end

if.end:
  %storemerge = phi i16 [ %conv27, %if.else ], [ %conv12, %if.then ]
  store i16 %storemerge, ptr %arrayidx, align 2, !tbaa !0
  %conv32 = sext i16 %storemerge to i32
  %or = or i32 %nz.053, %conv32
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %exitcond.not = icmp eq i64 %indvars.iv.next, 16
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body, !llvm.loop !4

}

!0 = !{!1, !1, i64 0}
!1 = !{!"short", !2, i64 0}
!2 = !{!"omnipotent char", !3, i64 0}
!3 = !{!"Simple C/C++ TBAA"}
!4 = distinct !{!4, !5}
!5 = !{!"llvm.loop.mustprogress"}

;.
; CHECK: [[SHORT_TBAA1]] = !{[[META2:![0-9]+]], [[META2]], i64 0}
; CHECK: [[META2]] = !{!"short", [[META3:![0-9]+]], i64 0}
; CHECK: [[META3]] = !{!"omnipotent char", [[META4:![0-9]+]], i64 0}
; CHECK: [[META4]] = !{!"Simple C/C++ TBAA"}
; CHECK: [[META5]] = !{[[META6:![0-9]+]]}
; CHECK: [[META6]] = distinct !{[[META6]], [[META7:![0-9]+]]}
; CHECK: [[META7]] = distinct !{[[META7]], !"LVerDomain"}
; CHECK: [[META8]] = !{[[META9:![0-9]+]], [[META10:![0-9]+]]}
; CHECK: [[META9]] = distinct !{[[META9]], [[META7]]}
; CHECK: [[META10]] = distinct !{[[META10]], [[META7]]}
; CHECK: [[META11]] = !{[[META9]]}
; CHECK: [[META12]] = !{[[META10]]}
; CHECK: [[LOOP13]] = distinct !{[[LOOP13]], [[META14:![0-9]+]], [[META15:![0-9]+]], [[META16:![0-9]+]]}
; CHECK: [[META14]] = !{!"llvm.loop.mustprogress"}
; CHECK: [[META15]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META16]] = !{!"llvm.loop.unroll.runtime.disable"}
; CHECK: [[LOOP17]] = distinct !{[[LOOP17]], [[META14]], [[META15]]}
;.
