; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --filter-out-after "scalar.ph:" --replace-value-regex "!llvm.loop ![0-9]+" --version 6
; RUN: opt < %s -passes=loop-vectorize -force-vector-interleave=1 -vectorize-vector-loops \
; RUN:     -mtriple=aarch64 -mattr=+sve2 -S | FileCheck %s --check-prefixes=CHECK,CHECK-SVE2
; RUN: opt < %s -passes=loop-vectorize -force-vector-interleave=1 -vectorize-vector-loops \
; RUN:     -mtriple=aarch64 -mattr=+sve2p1 -S | FileCheck %s --check-prefixes=CHECK,CHECK-SVE2p1
; RUN: opt < %s -passes=loop-vectorize -force-vector-interleave=2 -vectorize-vector-loops \
; RUN:     -mtriple=aarch64 -mattr=+sve2p1 -S | FileCheck %s --check-prefixes=CHECK-IC2

; Test we can interleave reductions without vectorizing
; RUN: opt < %s -passes=loop-vectorize -force-vector-interleave=2 -force-vector-width=1 \
; RUN:     -vectorize-vector-loops -mtriple=aarch64 -mattr=+sve2p1 -S \
; RUN:     | FileCheck %s --check-prefixes=CHECK-VF1-IC2

define i32 @smax_intrinsic(ptr nocapture readonly %x) {
; CHECK-LABEL: define i32 @smax_intrinsic(
; CHECK-SAME: ptr readonly captures(none) [[X:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 @llvm.vscale.i32()
; CHECK-NEXT:    [[TMP1:%.*]] = shl nuw i32 [[TMP0]], 2
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i32 1024, [[TMP1]]
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[TMP3:%.*]] = shl nuw i32 [[TMP0]], 2
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i32 1024, [[TMP3]]
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i32 1024, [[N_MOD_VF]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i32 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x i32> [ splat (i32 100), %[[VECTOR_PH]] ], [ [[TMP5:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i32>, ptr [[TMP4]], align 4
; CHECK-NEXT:    [[TMP5]] = call <vscale x 4 x i32> @llvm.smax.nxv4i32(<vscale x 4 x i32> [[VEC_PHI]], <vscale x 4 x i32> [[WIDE_LOAD]])
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i32 [[INDEX]], [[TMP3]]
; CHECK-NEXT:    [[TMP6:%.*]] = icmp eq i32 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP6]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[TMP7:%.*]] = call i32 @llvm.vector.reduce.smax.nxv4i32(<vscale x 4 x i32> [[TMP5]])
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i32 1024, [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
;
; CHECK-IC2-LABEL: define i32 @smax_intrinsic(
; CHECK-IC2-SAME: ptr readonly captures(none) [[X:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-IC2-NEXT:  [[ENTRY:.*:]]
; CHECK-IC2-NEXT:    [[TMP0:%.*]] = call i32 @llvm.vscale.i32()
; CHECK-IC2-NEXT:    [[TMP1:%.*]] = shl nuw i32 [[TMP0]], 3
; CHECK-IC2-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i32 1024, [[TMP1]]
; CHECK-IC2-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK-IC2:       [[VECTOR_PH]]:
; CHECK-IC2-NEXT:    [[TMP2:%.*]] = shl nuw i32 [[TMP0]], 2
; CHECK-IC2-NEXT:    [[TMP3:%.*]] = shl nuw i32 [[TMP2]], 1
; CHECK-IC2-NEXT:    [[N_MOD_VF:%.*]] = urem i32 1024, [[TMP3]]
; CHECK-IC2-NEXT:    [[N_VEC:%.*]] = sub i32 1024, [[N_MOD_VF]]
; CHECK-IC2-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-IC2:       [[VECTOR_BODY]]:
; CHECK-IC2-NEXT:    [[INDEX:%.*]] = phi i32 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-IC2-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x i32> [ splat (i32 100), %[[VECTOR_PH]] ], [ [[TMP8:%.*]], %[[VECTOR_BODY]] ]
; CHECK-IC2-NEXT:    [[VEC_PHI1:%.*]] = phi <vscale x 4 x i32> [ splat (i32 100), %[[VECTOR_PH]] ], [ [[TMP9:%.*]], %[[VECTOR_BODY]] ]
; CHECK-IC2-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[INDEX]]
; CHECK-IC2-NEXT:    [[TMP6:%.*]] = zext i32 [[TMP2]] to i64
; CHECK-IC2-NEXT:    [[TMP7:%.*]] = getelementptr inbounds i32, ptr [[TMP4]], i64 [[TMP6]]
; CHECK-IC2-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i32>, ptr [[TMP4]], align 4
; CHECK-IC2-NEXT:    [[WIDE_LOAD2:%.*]] = load <vscale x 4 x i32>, ptr [[TMP7]], align 4
; CHECK-IC2-NEXT:    [[TMP8]] = call <vscale x 4 x i32> @llvm.smax.nxv4i32(<vscale x 4 x i32> [[VEC_PHI]], <vscale x 4 x i32> [[WIDE_LOAD]])
; CHECK-IC2-NEXT:    [[TMP9]] = call <vscale x 4 x i32> @llvm.smax.nxv4i32(<vscale x 4 x i32> [[VEC_PHI1]], <vscale x 4 x i32> [[WIDE_LOAD2]])
; CHECK-IC2-NEXT:    [[INDEX_NEXT]] = add nuw i32 [[INDEX]], [[TMP3]]
; CHECK-IC2-NEXT:    [[TMP10:%.*]] = icmp eq i32 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-IC2-NEXT:    br i1 [[TMP10]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; CHECK-IC2:       [[MIDDLE_BLOCK]]:
; CHECK-IC2-NEXT:    [[RDX_MINMAX:%.*]] = call <vscale x 4 x i32> @llvm.smax.nxv4i32(<vscale x 4 x i32> [[TMP8]], <vscale x 4 x i32> [[TMP9]])
; CHECK-IC2-NEXT:    [[TMP11:%.*]] = call i32 @llvm.vector.reduce.smax.nxv4i32(<vscale x 4 x i32> [[RDX_MINMAX]])
; CHECK-IC2-NEXT:    [[CMP_N:%.*]] = icmp eq i32 1024, [[N_VEC]]
; CHECK-IC2-NEXT:    br i1 [[CMP_N]], [[FOR_COND_CLEANUP:label %.*]], label %[[SCALAR_PH]]
; CHECK-IC2:       [[SCALAR_PH]]:
;
; CHECK-VF1-IC2-LABEL: define i32 @smax_intrinsic(
; CHECK-VF1-IC2-SAME: ptr readonly captures(none) [[X:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-VF1-IC2-NEXT:  [[ENTRY:.*:]]
; CHECK-VF1-IC2-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK-VF1-IC2:       [[VECTOR_PH]]:
; CHECK-VF1-IC2-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-VF1-IC2:       [[VECTOR_BODY]]:
; CHECK-VF1-IC2-NEXT:    [[INDEX:%.*]] = phi i32 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-VF1-IC2-NEXT:    [[VEC_PHI:%.*]] = phi i32 [ 100, %[[VECTOR_PH]] ], [ [[TMP5:%.*]], %[[VECTOR_BODY]] ]
; CHECK-VF1-IC2-NEXT:    [[VEC_PHI1:%.*]] = phi i32 [ 100, %[[VECTOR_PH]] ], [ [[TMP6:%.*]], %[[VECTOR_BODY]] ]
; CHECK-VF1-IC2-NEXT:    [[TMP0:%.*]] = add i32 [[INDEX]], 1
; CHECK-VF1-IC2-NEXT:    [[TMP1:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[INDEX]]
; CHECK-VF1-IC2-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i32, ptr [[X]], i32 [[TMP0]]
; CHECK-VF1-IC2-NEXT:    [[TMP3:%.*]] = load i32, ptr [[TMP1]], align 4
; CHECK-VF1-IC2-NEXT:    [[TMP4:%.*]] = load i32, ptr [[TMP2]], align 4
; CHECK-VF1-IC2-NEXT:    [[TMP5]] = tail call i32 @llvm.smax.i32(i32 [[VEC_PHI]], i32 [[TMP3]])
; CHECK-VF1-IC2-NEXT:    [[TMP6]] = tail call i32 @llvm.smax.i32(i32 [[VEC_PHI1]], i32 [[TMP4]])
; CHECK-VF1-IC2-NEXT:    [[INDEX_NEXT]] = add nuw i32 [[INDEX]], 2
; CHECK-VF1-IC2-NEXT:    [[TMP7:%.*]] = icmp eq i32 [[INDEX_NEXT]], 1024
; CHECK-VF1-IC2-NEXT:    br i1 [[TMP7]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; CHECK-VF1-IC2:       [[MIDDLE_BLOCK]]:
; CHECK-VF1-IC2-NEXT:    [[RDX_MINMAX:%.*]] = call i32 @llvm.smax.i32(i32 [[TMP5]], i32 [[TMP6]])
; CHECK-VF1-IC2-NEXT:    br label %[[FOR_COND_CLEANUP:.*]]
; CHECK-VF1-IC2:       [[FOR_COND_CLEANUP]]:
; CHECK-VF1-IC2-NEXT:    ret i32 [[RDX_MINMAX]]
;
entry:
  br label %for.body

for.body:                                         ; preds = %entry, %for.body
  %i.012 = phi i32 [ 0, %entry ], [ %inc, %for.body ]
  %s.011 = phi i32 [ 100, %entry ], [ %1, %for.body ]
  %arrayidx = getelementptr inbounds i32, ptr %x, i32 %i.012
  %0 = load i32, ptr %arrayidx, align 4
  %1 = tail call i32 @llvm.smax.i32(i32 %s.011, i32 %0)
  %inc = add nuw nsw i32 %i.012, 1
  %exitcond.not = icmp eq i32 %inc, 1024
  br i1 %exitcond.not, label %for.cond.cleanup, label %for.body

for.cond.cleanup:                                 ; preds = %for.body
  ret i32 %1
}

define <4 x i32> @reduction_smax_4xi32(ptr noalias nocapture %A) {
; CHECK-SVE2-LABEL: define <4 x i32> @reduction_smax_4xi32(
; CHECK-SVE2-SAME: ptr noalias captures(none) [[A:%.*]]) #[[ATTR0]] {
; CHECK-SVE2-NEXT:  [[ENTRY:.*]]:
; CHECK-SVE2-NEXT:    br label %[[SCALAR_LOOP:.*]]
; CHECK-SVE2:       [[SCALAR_LOOP]]:
; CHECK-SVE2-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], %[[SCALAR_LOOP]] ], [ 0, %[[ENTRY]] ]
; CHECK-SVE2-NEXT:    [[ACC_02:%.*]] = phi <4 x i32> [ [[L7:%.*]], %[[SCALAR_LOOP]] ], [ zeroinitializer, %[[ENTRY]] ]
; CHECK-SVE2-NEXT:    [[L2:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV]]
; CHECK-SVE2-NEXT:    [[L3:%.*]] = load <4 x i32>, ptr [[L2]], align 4
; CHECK-SVE2-NEXT:    [[L7]] = tail call <4 x i32> @llvm.smax.v4i32(<4 x i32> [[ACC_02]], <4 x i32> [[L3]])
; CHECK-SVE2-NEXT:    [[INDVARS_IV_NEXT]] = add i64 [[INDVARS_IV]], 4
; CHECK-SVE2-NEXT:    [[LFTR_WIDEIV:%.*]] = trunc i64 [[INDVARS_IV_NEXT]] to i32
; CHECK-SVE2-NEXT:    [[EXITCOND:%.*]] = icmp eq i32 [[LFTR_WIDEIV]], 256
; CHECK-SVE2-NEXT:    br i1 [[EXITCOND]], label %[[LOOP_EXIT:.*]], label %[[SCALAR_LOOP]]
; CHECK-SVE2:       [[LOOP_EXIT]]:
; CHECK-SVE2-NEXT:    [[SUM_0_LCSSA:%.*]] = phi <4 x i32> [ [[L7]], %[[SCALAR_LOOP]] ]
; CHECK-SVE2-NEXT:    ret <4 x i32> [[SUM_0_LCSSA]]
;
; CHECK-SVE2p1-LABEL: define <4 x i32> @reduction_smax_4xi32(
; CHECK-SVE2p1-SAME: ptr noalias captures(none) [[A:%.*]]) #[[ATTR0]] {
; CHECK-SVE2p1-NEXT:  [[ENTRY:.*:]]
; CHECK-SVE2p1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-SVE2p1-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 64, [[TMP0]]
; CHECK-SVE2p1-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK-SVE2p1:       [[VECTOR_PH]]:
; CHECK-SVE2p1-NEXT:    [[N_MOD_VF:%.*]] = urem i64 64, [[TMP0]]
; CHECK-SVE2p1-NEXT:    [[N_VEC:%.*]] = sub i64 64, [[N_MOD_VF]]
; CHECK-SVE2p1-NEXT:    [[TMP2:%.*]] = shl i64 [[N_VEC]], 2
; CHECK-SVE2p1-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-SVE2p1:       [[VECTOR_BODY]]:
; CHECK-SVE2p1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-SVE2p1-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP4:%.*]], %[[VECTOR_BODY]] ]
; CHECK-SVE2p1-NEXT:    [[OFFSET_IDX:%.*]] = shl i64 [[INDEX]], 2
; CHECK-SVE2p1-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[OFFSET_IDX]]
; CHECK-SVE2p1-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i32>, ptr [[TMP3]], align 4
; CHECK-SVE2p1-NEXT:    [[TMP4]] = call <vscale x 4 x i32> @llvm.smax.nxv4i32(<vscale x 4 x i32> [[VEC_PHI]], <vscale x 4 x i32> [[WIDE_LOAD]])
; CHECK-SVE2p1-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; CHECK-SVE2p1-NEXT:    [[TMP5:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-SVE2p1-NEXT:    br i1 [[TMP5]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; CHECK-SVE2p1:       [[MIDDLE_BLOCK]]:
; CHECK-SVE2p1-NEXT:    [[TMP6:%.*]] = call <4 x i32> @llvm.vector.partial.reduce.smax.v4i32.nxv4i32(<4 x i32> splat (i32 -2147483648), <vscale x 4 x i32> [[TMP4]])
; CHECK-SVE2p1-NEXT:    [[CMP_N:%.*]] = icmp eq i64 64, [[N_VEC]]
; CHECK-SVE2p1-NEXT:    br i1 [[CMP_N]], [[LOOP_EXIT:label %.*]], label %[[SCALAR_PH]]
; CHECK-SVE2p1:       [[SCALAR_PH]]:
;
; CHECK-IC2-LABEL: define <4 x i32> @reduction_smax_4xi32(
; CHECK-IC2-SAME: ptr noalias captures(none) [[A:%.*]]) #[[ATTR0]] {
; CHECK-IC2-NEXT:  [[ENTRY:.*:]]
; CHECK-IC2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 1
; CHECK-IC2-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 64, [[TMP1]]
; CHECK-IC2-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK-IC2:       [[VECTOR_PH]]:
; CHECK-IC2-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP0]], 1
; CHECK-IC2-NEXT:    [[N_MOD_VF:%.*]] = urem i64 64, [[TMP3]]
; CHECK-IC2-NEXT:    [[N_VEC:%.*]] = sub i64 64, [[N_MOD_VF]]
; CHECK-IC2-NEXT:    [[TMP4:%.*]] = shl i64 [[N_VEC]], 2
; CHECK-IC2-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-IC2:       [[VECTOR_BODY]]:
; CHECK-IC2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-IC2-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP9:%.*]], %[[VECTOR_BODY]] ]
; CHECK-IC2-NEXT:    [[VEC_PHI1:%.*]] = phi <vscale x 4 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP10:%.*]], %[[VECTOR_BODY]] ]
; CHECK-IC2-NEXT:    [[OFFSET_IDX:%.*]] = shl i64 [[INDEX]], 2
; CHECK-IC2-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[OFFSET_IDX]]
; CHECK-IC2-NEXT:    [[TMP8:%.*]] = getelementptr inbounds <4 x i32>, ptr [[TMP5]], i64 [[TMP0]]
; CHECK-IC2-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i32>, ptr [[TMP5]], align 4
; CHECK-IC2-NEXT:    [[WIDE_LOAD2:%.*]] = load <vscale x 4 x i32>, ptr [[TMP8]], align 4
; CHECK-IC2-NEXT:    [[TMP9]] = call <vscale x 4 x i32> @llvm.smax.nxv4i32(<vscale x 4 x i32> [[VEC_PHI]], <vscale x 4 x i32> [[WIDE_LOAD]])
; CHECK-IC2-NEXT:    [[TMP10]] = call <vscale x 4 x i32> @llvm.smax.nxv4i32(<vscale x 4 x i32> [[VEC_PHI1]], <vscale x 4 x i32> [[WIDE_LOAD2]])
; CHECK-IC2-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; CHECK-IC2-NEXT:    [[TMP11:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-IC2-NEXT:    br i1 [[TMP11]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; CHECK-IC2:       [[MIDDLE_BLOCK]]:
; CHECK-IC2-NEXT:    [[RDX_MINMAX:%.*]] = call <vscale x 4 x i32> @llvm.smax.nxv4i32(<vscale x 4 x i32> [[TMP9]], <vscale x 4 x i32> [[TMP10]])
; CHECK-IC2-NEXT:    [[TMP12:%.*]] = call <4 x i32> @llvm.vector.partial.reduce.smax.v4i32.nxv4i32(<4 x i32> splat (i32 -2147483648), <vscale x 4 x i32> [[RDX_MINMAX]])
; CHECK-IC2-NEXT:    [[CMP_N:%.*]] = icmp eq i64 64, [[N_VEC]]
; CHECK-IC2-NEXT:    br i1 [[CMP_N]], [[LOOP_EXIT:label %.*]], label %[[SCALAR_PH]]
; CHECK-IC2:       [[SCALAR_PH]]:
;
; CHECK-VF1-IC2-LABEL: define <4 x i32> @reduction_smax_4xi32(
; CHECK-VF1-IC2-SAME: ptr noalias captures(none) [[A:%.*]]) #[[ATTR0]] {
; CHECK-VF1-IC2-NEXT:  [[ENTRY:.*:]]
; CHECK-VF1-IC2-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK-VF1-IC2:       [[VECTOR_PH]]:
; CHECK-VF1-IC2-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-VF1-IC2:       [[VECTOR_BODY]]:
; CHECK-VF1-IC2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-VF1-IC2-NEXT:    [[VEC_PHI:%.*]] = phi <4 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP5:%.*]], %[[VECTOR_BODY]] ]
; CHECK-VF1-IC2-NEXT:    [[VEC_PHI1:%.*]] = phi <4 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP6:%.*]], %[[VECTOR_BODY]] ]
; CHECK-VF1-IC2-NEXT:    [[OFFSET_IDX:%.*]] = shl i64 [[INDEX]], 2
; CHECK-VF1-IC2-NEXT:    [[TMP0:%.*]] = add i64 [[OFFSET_IDX]], 4
; CHECK-VF1-IC2-NEXT:    [[TMP1:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[OFFSET_IDX]]
; CHECK-VF1-IC2-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[TMP0]]
; CHECK-VF1-IC2-NEXT:    [[TMP3:%.*]] = load <4 x i32>, ptr [[TMP1]], align 4
; CHECK-VF1-IC2-NEXT:    [[TMP4:%.*]] = load <4 x i32>, ptr [[TMP2]], align 4
; CHECK-VF1-IC2-NEXT:    [[TMP5]] = tail call <4 x i32> @llvm.smax.v4i32(<4 x i32> [[VEC_PHI]], <4 x i32> [[TMP3]])
; CHECK-VF1-IC2-NEXT:    [[TMP6]] = tail call <4 x i32> @llvm.smax.v4i32(<4 x i32> [[VEC_PHI1]], <4 x i32> [[TMP4]])
; CHECK-VF1-IC2-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 2
; CHECK-VF1-IC2-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[INDEX_NEXT]], 64
; CHECK-VF1-IC2-NEXT:    br i1 [[TMP7]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; CHECK-VF1-IC2:       [[MIDDLE_BLOCK]]:
; CHECK-VF1-IC2-NEXT:    [[RDX_MINMAX:%.*]] = call <4 x i32> @llvm.smax.v4i32(<4 x i32> [[TMP5]], <4 x i32> [[TMP6]])
; CHECK-VF1-IC2-NEXT:    br label %[[LOOP_EXIT:.*]]
; CHECK-VF1-IC2:       [[LOOP_EXIT]]:
; CHECK-VF1-IC2-NEXT:    ret <4 x i32> [[RDX_MINMAX]]
;
entry:
  br label %scalar.loop

scalar.loop:                                           ; preds = %entry, %scalar.loop
  %indvars.iv = phi i64 [ %indvars.iv.next, %scalar.loop ], [ 0, %entry ]
  %acc.02 = phi <4 x i32> [ %l7, %scalar.loop ], [ zeroinitializer, %entry ]
  %l2 = getelementptr inbounds i32, ptr %A, i64 %indvars.iv
  %l3 = load <4 x i32>, ptr %l2, align 4
  %l7 = tail call <4 x i32> @llvm.smax.v4i32(<4 x i32> %acc.02, <4 x i32> %l3)
  %indvars.iv.next = add i64 %indvars.iv, 4
  %lftr.wideiv = trunc i64 %indvars.iv.next to i32
  %exitcond = icmp eq i32 %lftr.wideiv, 256
  br i1 %exitcond, label %loop.exit, label %scalar.loop

loop.exit:                                      ; preds = %scalar.loop
  %sum.0.lcssa = phi <4 x i32> [ %l7, %scalar.loop ]
  ret <4 x i32> %sum.0.lcssa
}

define <4 x i32> @reduction_umin_4xi32(ptr noalias nocapture %A) {
; CHECK-SVE2-LABEL: define <4 x i32> @reduction_umin_4xi32(
; CHECK-SVE2-SAME: ptr noalias captures(none) [[A:%.*]]) #[[ATTR0]] {
; CHECK-SVE2-NEXT:  [[ENTRY:.*]]:
; CHECK-SVE2-NEXT:    br label %[[SCALAR_LOOP:.*]]
; CHECK-SVE2:       [[SCALAR_LOOP]]:
; CHECK-SVE2-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], %[[SCALAR_LOOP]] ], [ 0, %[[ENTRY]] ]
; CHECK-SVE2-NEXT:    [[ACC_02:%.*]] = phi <4 x i32> [ [[L7:%.*]], %[[SCALAR_LOOP]] ], [ zeroinitializer, %[[ENTRY]] ]
; CHECK-SVE2-NEXT:    [[L2:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[INDVARS_IV]]
; CHECK-SVE2-NEXT:    [[L3:%.*]] = load <4 x i32>, ptr [[L2]], align 4
; CHECK-SVE2-NEXT:    [[L7]] = tail call <4 x i32> @llvm.umin.v4i32(<4 x i32> [[ACC_02]], <4 x i32> [[L3]])
; CHECK-SVE2-NEXT:    [[INDVARS_IV_NEXT]] = add i64 [[INDVARS_IV]], 4
; CHECK-SVE2-NEXT:    [[LFTR_WIDEIV:%.*]] = trunc i64 [[INDVARS_IV_NEXT]] to i32
; CHECK-SVE2-NEXT:    [[EXITCOND:%.*]] = icmp eq i32 [[LFTR_WIDEIV]], 256
; CHECK-SVE2-NEXT:    br i1 [[EXITCOND]], label %[[LOOP_EXIT:.*]], label %[[SCALAR_LOOP]]
; CHECK-SVE2:       [[LOOP_EXIT]]:
; CHECK-SVE2-NEXT:    [[SUM_0_LCSSA:%.*]] = phi <4 x i32> [ [[L7]], %[[SCALAR_LOOP]] ]
; CHECK-SVE2-NEXT:    ret <4 x i32> [[SUM_0_LCSSA]]
;
; CHECK-SVE2p1-LABEL: define <4 x i32> @reduction_umin_4xi32(
; CHECK-SVE2p1-SAME: ptr noalias captures(none) [[A:%.*]]) #[[ATTR0]] {
; CHECK-SVE2p1-NEXT:  [[ENTRY:.*:]]
; CHECK-SVE2p1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-SVE2p1-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 64, [[TMP0]]
; CHECK-SVE2p1-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK-SVE2p1:       [[VECTOR_PH]]:
; CHECK-SVE2p1-NEXT:    [[N_MOD_VF:%.*]] = urem i64 64, [[TMP0]]
; CHECK-SVE2p1-NEXT:    [[N_VEC:%.*]] = sub i64 64, [[N_MOD_VF]]
; CHECK-SVE2p1-NEXT:    [[TMP2:%.*]] = shl i64 [[N_VEC]], 2
; CHECK-SVE2p1-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-SVE2p1:       [[VECTOR_BODY]]:
; CHECK-SVE2p1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-SVE2p1-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP4:%.*]], %[[VECTOR_BODY]] ]
; CHECK-SVE2p1-NEXT:    [[OFFSET_IDX:%.*]] = shl i64 [[INDEX]], 2
; CHECK-SVE2p1-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[OFFSET_IDX]]
; CHECK-SVE2p1-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i32>, ptr [[TMP3]], align 4
; CHECK-SVE2p1-NEXT:    [[TMP4]] = call <vscale x 4 x i32> @llvm.umin.nxv4i32(<vscale x 4 x i32> [[VEC_PHI]], <vscale x 4 x i32> [[WIDE_LOAD]])
; CHECK-SVE2p1-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP0]]
; CHECK-SVE2p1-NEXT:    [[TMP5:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-SVE2p1-NEXT:    br i1 [[TMP5]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; CHECK-SVE2p1:       [[MIDDLE_BLOCK]]:
; CHECK-SVE2p1-NEXT:    [[TMP6:%.*]] = call <4 x i32> @llvm.vector.partial.reduce.umin.v4i32.nxv4i32(<4 x i32> splat (i32 -1), <vscale x 4 x i32> [[TMP4]])
; CHECK-SVE2p1-NEXT:    [[CMP_N:%.*]] = icmp eq i64 64, [[N_VEC]]
; CHECK-SVE2p1-NEXT:    br i1 [[CMP_N]], [[LOOP_EXIT:label %.*]], label %[[SCALAR_PH]]
; CHECK-SVE2p1:       [[SCALAR_PH]]:
;
; CHECK-IC2-LABEL: define <4 x i32> @reduction_umin_4xi32(
; CHECK-IC2-SAME: ptr noalias captures(none) [[A:%.*]]) #[[ATTR0]] {
; CHECK-IC2-NEXT:  [[ENTRY:.*:]]
; CHECK-IC2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 1
; CHECK-IC2-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 64, [[TMP1]]
; CHECK-IC2-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK-IC2:       [[VECTOR_PH]]:
; CHECK-IC2-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP0]], 1
; CHECK-IC2-NEXT:    [[N_MOD_VF:%.*]] = urem i64 64, [[TMP3]]
; CHECK-IC2-NEXT:    [[N_VEC:%.*]] = sub i64 64, [[N_MOD_VF]]
; CHECK-IC2-NEXT:    [[TMP4:%.*]] = shl i64 [[N_VEC]], 2
; CHECK-IC2-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-IC2:       [[VECTOR_BODY]]:
; CHECK-IC2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-IC2-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP9:%.*]], %[[VECTOR_BODY]] ]
; CHECK-IC2-NEXT:    [[VEC_PHI1:%.*]] = phi <vscale x 4 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP10:%.*]], %[[VECTOR_BODY]] ]
; CHECK-IC2-NEXT:    [[OFFSET_IDX:%.*]] = shl i64 [[INDEX]], 2
; CHECK-IC2-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[OFFSET_IDX]]
; CHECK-IC2-NEXT:    [[TMP8:%.*]] = getelementptr inbounds <4 x i32>, ptr [[TMP5]], i64 [[TMP0]]
; CHECK-IC2-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i32>, ptr [[TMP5]], align 4
; CHECK-IC2-NEXT:    [[WIDE_LOAD2:%.*]] = load <vscale x 4 x i32>, ptr [[TMP8]], align 4
; CHECK-IC2-NEXT:    [[TMP9]] = call <vscale x 4 x i32> @llvm.umin.nxv4i32(<vscale x 4 x i32> [[VEC_PHI]], <vscale x 4 x i32> [[WIDE_LOAD]])
; CHECK-IC2-NEXT:    [[TMP10]] = call <vscale x 4 x i32> @llvm.umin.nxv4i32(<vscale x 4 x i32> [[VEC_PHI1]], <vscale x 4 x i32> [[WIDE_LOAD2]])
; CHECK-IC2-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; CHECK-IC2-NEXT:    [[TMP11:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-IC2-NEXT:    br i1 [[TMP11]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; CHECK-IC2:       [[MIDDLE_BLOCK]]:
; CHECK-IC2-NEXT:    [[RDX_MINMAX:%.*]] = call <vscale x 4 x i32> @llvm.umin.nxv4i32(<vscale x 4 x i32> [[TMP9]], <vscale x 4 x i32> [[TMP10]])
; CHECK-IC2-NEXT:    [[TMP12:%.*]] = call <4 x i32> @llvm.vector.partial.reduce.umin.v4i32.nxv4i32(<4 x i32> splat (i32 -1), <vscale x 4 x i32> [[RDX_MINMAX]])
; CHECK-IC2-NEXT:    [[CMP_N:%.*]] = icmp eq i64 64, [[N_VEC]]
; CHECK-IC2-NEXT:    br i1 [[CMP_N]], [[LOOP_EXIT:label %.*]], label %[[SCALAR_PH]]
; CHECK-IC2:       [[SCALAR_PH]]:
;
; CHECK-VF1-IC2-LABEL: define <4 x i32> @reduction_umin_4xi32(
; CHECK-VF1-IC2-SAME: ptr noalias captures(none) [[A:%.*]]) #[[ATTR0]] {
; CHECK-VF1-IC2-NEXT:  [[ENTRY:.*:]]
; CHECK-VF1-IC2-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK-VF1-IC2:       [[VECTOR_PH]]:
; CHECK-VF1-IC2-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-VF1-IC2:       [[VECTOR_BODY]]:
; CHECK-VF1-IC2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-VF1-IC2-NEXT:    [[VEC_PHI:%.*]] = phi <4 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP5:%.*]], %[[VECTOR_BODY]] ]
; CHECK-VF1-IC2-NEXT:    [[VEC_PHI1:%.*]] = phi <4 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP6:%.*]], %[[VECTOR_BODY]] ]
; CHECK-VF1-IC2-NEXT:    [[OFFSET_IDX:%.*]] = shl i64 [[INDEX]], 2
; CHECK-VF1-IC2-NEXT:    [[TMP0:%.*]] = add i64 [[OFFSET_IDX]], 4
; CHECK-VF1-IC2-NEXT:    [[TMP1:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[OFFSET_IDX]]
; CHECK-VF1-IC2-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i32, ptr [[A]], i64 [[TMP0]]
; CHECK-VF1-IC2-NEXT:    [[TMP3:%.*]] = load <4 x i32>, ptr [[TMP1]], align 4
; CHECK-VF1-IC2-NEXT:    [[TMP4:%.*]] = load <4 x i32>, ptr [[TMP2]], align 4
; CHECK-VF1-IC2-NEXT:    [[TMP5]] = tail call <4 x i32> @llvm.umin.v4i32(<4 x i32> [[VEC_PHI]], <4 x i32> [[TMP3]])
; CHECK-VF1-IC2-NEXT:    [[TMP6]] = tail call <4 x i32> @llvm.umin.v4i32(<4 x i32> [[VEC_PHI1]], <4 x i32> [[TMP4]])
; CHECK-VF1-IC2-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 2
; CHECK-VF1-IC2-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[INDEX_NEXT]], 64
; CHECK-VF1-IC2-NEXT:    br i1 [[TMP7]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; CHECK-VF1-IC2:       [[MIDDLE_BLOCK]]:
; CHECK-VF1-IC2-NEXT:    [[RDX_MINMAX:%.*]] = call <4 x i32> @llvm.umin.v4i32(<4 x i32> [[TMP5]], <4 x i32> [[TMP6]])
; CHECK-VF1-IC2-NEXT:    br label %[[LOOP_EXIT:.*]]
; CHECK-VF1-IC2:       [[LOOP_EXIT]]:
; CHECK-VF1-IC2-NEXT:    ret <4 x i32> [[RDX_MINMAX]]
;
entry:
  br label %scalar.loop

scalar.loop:                                           ; preds = %entry, %scalar.loop
  %indvars.iv = phi i64 [ %indvars.iv.next, %scalar.loop ], [ 0, %entry ]
  %acc.02 = phi <4 x i32> [ %l7, %scalar.loop ], [ zeroinitializer, %entry ]
  %l2 = getelementptr inbounds i32, ptr %A, i64 %indvars.iv
  %l3 = load <4 x i32>, ptr %l2, align 4
  %l7 = tail call <4 x i32> @llvm.umin.v4i32(<4 x i32> %acc.02, <4 x i32> %l3)
  %indvars.iv.next = add i64 %indvars.iv, 4
  %lftr.wideiv = trunc i64 %indvars.iv.next to i32
  %exitcond = icmp eq i32 %lftr.wideiv, 256
  br i1 %exitcond, label %loop.exit, label %scalar.loop

loop.exit:                                      ; preds = %scalar.loop
  %sum.0.lcssa = phi <4 x i32> [ %l7, %scalar.loop ]
  ret <4 x i32> %sum.0.lcssa
}

; Verify 64-bit vectors are also supported.
define <4 x i16> @reduction_smin_4xi16(ptr noalias nocapture %A) {
; CHECK-SVE2-LABEL: define <4 x i16> @reduction_smin_4xi16(
; CHECK-SVE2-SAME: ptr noalias captures(none) [[A:%.*]]) #[[ATTR0]] {
; CHECK-SVE2-NEXT:  [[ENTRY:.*]]:
; CHECK-SVE2-NEXT:    br label %[[SCALAR_LOOP:.*]]
; CHECK-SVE2:       [[SCALAR_LOOP]]:
; CHECK-SVE2-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], %[[SCALAR_LOOP]] ], [ 0, %[[ENTRY]] ]
; CHECK-SVE2-NEXT:    [[ACC_02:%.*]] = phi <4 x i16> [ [[L7:%.*]], %[[SCALAR_LOOP]] ], [ zeroinitializer, %[[ENTRY]] ]
; CHECK-SVE2-NEXT:    [[L2:%.*]] = getelementptr inbounds i16, ptr [[A]], i64 [[INDVARS_IV]]
; CHECK-SVE2-NEXT:    [[L3:%.*]] = load <4 x i16>, ptr [[L2]], align 4
; CHECK-SVE2-NEXT:    [[L7]] = tail call <4 x i16> @llvm.smax.v4i16(<4 x i16> [[ACC_02]], <4 x i16> [[L3]])
; CHECK-SVE2-NEXT:    [[INDVARS_IV_NEXT]] = add i64 [[INDVARS_IV]], 4
; CHECK-SVE2-NEXT:    [[EXITCOND:%.*]] = icmp eq i64 [[INDVARS_IV_NEXT]], 256
; CHECK-SVE2-NEXT:    br i1 [[EXITCOND]], label %[[LOOP_EXIT:.*]], label %[[SCALAR_LOOP]]
; CHECK-SVE2:       [[LOOP_EXIT]]:
; CHECK-SVE2-NEXT:    [[SUM_0_LCSSA:%.*]] = phi <4 x i16> [ [[L7]], %[[SCALAR_LOOP]] ]
; CHECK-SVE2-NEXT:    ret <4 x i16> [[SUM_0_LCSSA]]
;
; CHECK-SVE2p1-LABEL: define <4 x i16> @reduction_smin_4xi16(
; CHECK-SVE2p1-SAME: ptr noalias captures(none) [[A:%.*]]) #[[ATTR0]] {
; CHECK-SVE2p1-NEXT:  [[ENTRY:.*:]]
; CHECK-SVE2p1-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-SVE2p1-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 1
; CHECK-SVE2p1-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 64, [[TMP1]]
; CHECK-SVE2p1-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK-SVE2p1:       [[VECTOR_PH]]:
; CHECK-SVE2p1-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP0]], 1
; CHECK-SVE2p1-NEXT:    [[N_MOD_VF:%.*]] = urem i64 64, [[TMP3]]
; CHECK-SVE2p1-NEXT:    [[N_VEC:%.*]] = sub i64 64, [[N_MOD_VF]]
; CHECK-SVE2p1-NEXT:    [[TMP4:%.*]] = shl i64 [[N_VEC]], 2
; CHECK-SVE2p1-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-SVE2p1:       [[VECTOR_BODY]]:
; CHECK-SVE2p1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-SVE2p1-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 8 x i16> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP6:%.*]], %[[VECTOR_BODY]] ]
; CHECK-SVE2p1-NEXT:    [[OFFSET_IDX:%.*]] = shl i64 [[INDEX]], 2
; CHECK-SVE2p1-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i16, ptr [[A]], i64 [[OFFSET_IDX]]
; CHECK-SVE2p1-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 8 x i16>, ptr [[TMP5]], align 4
; CHECK-SVE2p1-NEXT:    [[TMP6]] = call <vscale x 8 x i16> @llvm.smax.nxv8i16(<vscale x 8 x i16> [[VEC_PHI]], <vscale x 8 x i16> [[WIDE_LOAD]])
; CHECK-SVE2p1-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; CHECK-SVE2p1-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-SVE2p1-NEXT:    br i1 [[TMP7]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; CHECK-SVE2p1:       [[MIDDLE_BLOCK]]:
; CHECK-SVE2p1-NEXT:    [[TMP8:%.*]] = call <4 x i16> @llvm.vector.partial.reduce.smax.v4i16.nxv8i16(<4 x i16> splat (i16 -32768), <vscale x 8 x i16> [[TMP6]])
; CHECK-SVE2p1-NEXT:    [[CMP_N:%.*]] = icmp eq i64 64, [[N_VEC]]
; CHECK-SVE2p1-NEXT:    br i1 [[CMP_N]], [[LOOP_EXIT:label %.*]], label %[[SCALAR_PH]]
; CHECK-SVE2p1:       [[SCALAR_PH]]:
;
; CHECK-IC2-LABEL: define <4 x i16> @reduction_smin_4xi16(
; CHECK-IC2-SAME: ptr noalias captures(none) [[A:%.*]]) #[[ATTR0]] {
; CHECK-IC2-NEXT:  [[ENTRY:.*:]]
; CHECK-IC2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; CHECK-IC2-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 64, [[TMP1]]
; CHECK-IC2-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK-IC2:       [[VECTOR_PH]]:
; CHECK-IC2-NEXT:    [[TMP7:%.*]] = shl nuw i64 [[TMP0]], 1
; CHECK-IC2-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP7]], 1
; CHECK-IC2-NEXT:    [[N_MOD_VF:%.*]] = urem i64 64, [[TMP3]]
; CHECK-IC2-NEXT:    [[N_VEC:%.*]] = sub i64 64, [[N_MOD_VF]]
; CHECK-IC2-NEXT:    [[TMP4:%.*]] = shl i64 [[N_VEC]], 2
; CHECK-IC2-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-IC2:       [[VECTOR_BODY]]:
; CHECK-IC2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-IC2-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 8 x i16> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP9:%.*]], %[[VECTOR_BODY]] ]
; CHECK-IC2-NEXT:    [[VEC_PHI1:%.*]] = phi <vscale x 8 x i16> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP10:%.*]], %[[VECTOR_BODY]] ]
; CHECK-IC2-NEXT:    [[OFFSET_IDX:%.*]] = shl i64 [[INDEX]], 2
; CHECK-IC2-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i16, ptr [[A]], i64 [[OFFSET_IDX]]
; CHECK-IC2-NEXT:    [[TMP8:%.*]] = getelementptr inbounds <4 x i16>, ptr [[TMP5]], i64 [[TMP7]]
; CHECK-IC2-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 8 x i16>, ptr [[TMP5]], align 4
; CHECK-IC2-NEXT:    [[WIDE_LOAD2:%.*]] = load <vscale x 8 x i16>, ptr [[TMP8]], align 4
; CHECK-IC2-NEXT:    [[TMP9]] = call <vscale x 8 x i16> @llvm.smax.nxv8i16(<vscale x 8 x i16> [[VEC_PHI]], <vscale x 8 x i16> [[WIDE_LOAD]])
; CHECK-IC2-NEXT:    [[TMP10]] = call <vscale x 8 x i16> @llvm.smax.nxv8i16(<vscale x 8 x i16> [[VEC_PHI1]], <vscale x 8 x i16> [[WIDE_LOAD2]])
; CHECK-IC2-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; CHECK-IC2-NEXT:    [[TMP11:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-IC2-NEXT:    br i1 [[TMP11]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; CHECK-IC2:       [[MIDDLE_BLOCK]]:
; CHECK-IC2-NEXT:    [[RDX_MINMAX:%.*]] = call <vscale x 8 x i16> @llvm.smax.nxv8i16(<vscale x 8 x i16> [[TMP9]], <vscale x 8 x i16> [[TMP10]])
; CHECK-IC2-NEXT:    [[TMP12:%.*]] = call <4 x i16> @llvm.vector.partial.reduce.smax.v4i16.nxv8i16(<4 x i16> splat (i16 -32768), <vscale x 8 x i16> [[RDX_MINMAX]])
; CHECK-IC2-NEXT:    [[CMP_N:%.*]] = icmp eq i64 64, [[N_VEC]]
; CHECK-IC2-NEXT:    br i1 [[CMP_N]], [[LOOP_EXIT:label %.*]], label %[[SCALAR_PH]]
; CHECK-IC2:       [[SCALAR_PH]]:
;
; CHECK-VF1-IC2-LABEL: define <4 x i16> @reduction_smin_4xi16(
; CHECK-VF1-IC2-SAME: ptr noalias captures(none) [[A:%.*]]) #[[ATTR0]] {
; CHECK-VF1-IC2-NEXT:  [[ENTRY:.*:]]
; CHECK-VF1-IC2-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK-VF1-IC2:       [[VECTOR_PH]]:
; CHECK-VF1-IC2-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-VF1-IC2:       [[VECTOR_BODY]]:
; CHECK-VF1-IC2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-VF1-IC2-NEXT:    [[VEC_PHI:%.*]] = phi <4 x i16> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP5:%.*]], %[[VECTOR_BODY]] ]
; CHECK-VF1-IC2-NEXT:    [[VEC_PHI1:%.*]] = phi <4 x i16> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP6:%.*]], %[[VECTOR_BODY]] ]
; CHECK-VF1-IC2-NEXT:    [[OFFSET_IDX:%.*]] = shl i64 [[INDEX]], 2
; CHECK-VF1-IC2-NEXT:    [[TMP0:%.*]] = add i64 [[OFFSET_IDX]], 4
; CHECK-VF1-IC2-NEXT:    [[TMP1:%.*]] = getelementptr inbounds i16, ptr [[A]], i64 [[OFFSET_IDX]]
; CHECK-VF1-IC2-NEXT:    [[TMP2:%.*]] = getelementptr inbounds i16, ptr [[A]], i64 [[TMP0]]
; CHECK-VF1-IC2-NEXT:    [[TMP3:%.*]] = load <4 x i16>, ptr [[TMP1]], align 4
; CHECK-VF1-IC2-NEXT:    [[TMP4:%.*]] = load <4 x i16>, ptr [[TMP2]], align 4
; CHECK-VF1-IC2-NEXT:    [[TMP5]] = tail call <4 x i16> @llvm.smax.v4i16(<4 x i16> [[VEC_PHI]], <4 x i16> [[TMP3]])
; CHECK-VF1-IC2-NEXT:    [[TMP6]] = tail call <4 x i16> @llvm.smax.v4i16(<4 x i16> [[VEC_PHI1]], <4 x i16> [[TMP4]])
; CHECK-VF1-IC2-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 2
; CHECK-VF1-IC2-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[INDEX_NEXT]], 64
; CHECK-VF1-IC2-NEXT:    br i1 [[TMP7]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; CHECK-VF1-IC2:       [[MIDDLE_BLOCK]]:
; CHECK-VF1-IC2-NEXT:    [[RDX_MINMAX:%.*]] = call <4 x i16> @llvm.smax.v4i16(<4 x i16> [[TMP5]], <4 x i16> [[TMP6]])
; CHECK-VF1-IC2-NEXT:    br label %[[LOOP_EXIT:.*]]
; CHECK-VF1-IC2:       [[LOOP_EXIT]]:
; CHECK-VF1-IC2-NEXT:    ret <4 x i16> [[RDX_MINMAX]]
;
entry:
  br label %scalar.loop

scalar.loop:                                           ; preds = %entry, %scalar.loop
  %indvars.iv = phi i64 [ %indvars.iv.next, %scalar.loop ], [ 0, %entry ]
  %acc.02 = phi <4 x i16> [ %l7, %scalar.loop ], [ zeroinitializer, %entry ]
  %l2 = getelementptr inbounds i16, ptr %A, i64 %indvars.iv
  %l3 = load <4 x i16>, ptr %l2, align 4
  %l7 = tail call <4 x i16> @llvm.smax.v4i16(<4 x i16> %acc.02, <4 x i16> %l3)
  %indvars.iv.next = add i64 %indvars.iv, 4
  %exitcond = icmp eq i64 %indvars.iv.next, 256
  br i1 %exitcond, label %loop.exit, label %scalar.loop

loop.exit:                                      ; preds = %scalar.loop
  %sum.0.lcssa = phi <4 x i16> [ %l7, %scalar.loop ]
  ret <4 x i16> %sum.0.lcssa
}
