; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --filter-out-after "scalar.ph:" --replace-value-regex "!llvm.loop ![0-9]+" --version 6
; RUN: opt < %s -passes=loop-vectorize -force-vector-interleave=1 -vectorize-vector-loops \
; RUN:     -mtriple=aarch64 -mattr=+sve2 -S | FileCheck %s --check-prefixes=CHECK
; RUN: opt < %s -passes=loop-vectorize -force-vector-interleave=1 -vectorize-vector-loops \
; RUN:     -mtriple=aarch64 -mattr=+sve2p1 -S | FileCheck %s --check-prefixes=CHECK
; RUN: opt < %s -passes=loop-vectorize -force-vector-interleave=2 -vectorize-vector-loops \
; RUN:     -mtriple=aarch64 -mattr=+sve2p1 -S | FileCheck %s --check-prefixes=CHECK-IC2

; Test whether we can interleave reductions without vectorizing.
; RUN: opt < %s -passes=loop-vectorize -force-vector-interleave=2 -force-vector-width=1 \
; RUN:     -vectorize-vector-loops -mtriple=aarch64 -mattr=+sve2p1 -S \
; RUN:     | FileCheck %s --check-prefixes=CHECK-VF1-IC2

define float @reduction_fadd_single(ptr noalias nocapture %A) {
; CHECK-LABEL: define float @reduction_fadd_single(
; CHECK-SAME: ptr noalias captures(none) [[A:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 2
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 256, [[TMP1]]
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[TMP2:%.*]] = shl nuw i64 [[TMP0]], 2
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i64 256, [[TMP2]]
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i64 256, [[N_MOD_VF]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x float> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP4:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x float>, ptr [[TMP3]], align 4
; CHECK-NEXT:    [[TMP4]] = fadd fast <vscale x 4 x float> [[VEC_PHI]], [[WIDE_LOAD]]
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP2]]
; CHECK-NEXT:    [[TMP5:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP5]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[TMP6:%.*]] = call fast float @llvm.vector.reduce.fadd.nxv4f32(float 0.000000e+00, <vscale x 4 x float> [[TMP4]])
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i64 256, [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], [[LOOP_EXIT:label %.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
;
; CHECK-IC2-LABEL: define float @reduction_fadd_single(
; CHECK-IC2-SAME: ptr noalias captures(none) [[A:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-IC2-NEXT:  [[ENTRY:.*:]]
; CHECK-IC2-NEXT:    [[TMP0:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-IC2-NEXT:    [[TMP1:%.*]] = shl nuw i64 [[TMP0]], 3
; CHECK-IC2-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 256, [[TMP1]]
; CHECK-IC2-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK-IC2:       [[VECTOR_PH]]:
; CHECK-IC2-NEXT:    [[TMP2:%.*]] = shl nuw i64 [[TMP0]], 2
; CHECK-IC2-NEXT:    [[TMP3:%.*]] = shl nuw i64 [[TMP2]], 1
; CHECK-IC2-NEXT:    [[N_MOD_VF:%.*]] = urem i64 256, [[TMP3]]
; CHECK-IC2-NEXT:    [[N_VEC:%.*]] = sub i64 256, [[N_MOD_VF]]
; CHECK-IC2-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-IC2:       [[VECTOR_BODY]]:
; CHECK-IC2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-IC2-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x float> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP6:%.*]], %[[VECTOR_BODY]] ]
; CHECK-IC2-NEXT:    [[VEC_PHI1:%.*]] = phi <vscale x 4 x float> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP7:%.*]], %[[VECTOR_BODY]] ]
; CHECK-IC2-NEXT:    [[TMP4:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[INDEX]]
; CHECK-IC2-NEXT:    [[TMP5:%.*]] = getelementptr inbounds float, ptr [[TMP4]], i64 [[TMP2]]
; CHECK-IC2-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x float>, ptr [[TMP4]], align 4
; CHECK-IC2-NEXT:    [[WIDE_LOAD2:%.*]] = load <vscale x 4 x float>, ptr [[TMP5]], align 4
; CHECK-IC2-NEXT:    [[TMP6]] = fadd fast <vscale x 4 x float> [[VEC_PHI]], [[WIDE_LOAD]]
; CHECK-IC2-NEXT:    [[TMP7]] = fadd fast <vscale x 4 x float> [[VEC_PHI1]], [[WIDE_LOAD2]]
; CHECK-IC2-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; CHECK-IC2-NEXT:    [[TMP8:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-IC2-NEXT:    br i1 [[TMP8]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; CHECK-IC2:       [[MIDDLE_BLOCK]]:
; CHECK-IC2-NEXT:    [[BIN_RDX:%.*]] = fadd fast <vscale x 4 x float> [[TMP7]], [[TMP6]]
; CHECK-IC2-NEXT:    [[TMP9:%.*]] = call fast float @llvm.vector.reduce.fadd.nxv4f32(float 0.000000e+00, <vscale x 4 x float> [[BIN_RDX]])
; CHECK-IC2-NEXT:    [[CMP_N:%.*]] = icmp eq i64 256, [[N_VEC]]
; CHECK-IC2-NEXT:    br i1 [[CMP_N]], [[LOOP_EXIT:label %.*]], label %[[SCALAR_PH]]
; CHECK-IC2:       [[SCALAR_PH]]:
;
; CHECK-VF1-IC2-LABEL: define float @reduction_fadd_single(
; CHECK-VF1-IC2-SAME: ptr noalias captures(none) [[A:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-VF1-IC2-NEXT:  [[ENTRY:.*:]]
; CHECK-VF1-IC2-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK-VF1-IC2:       [[VECTOR_PH]]:
; CHECK-VF1-IC2-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-VF1-IC2:       [[VECTOR_BODY]]:
; CHECK-VF1-IC2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-VF1-IC2-NEXT:    [[VEC_PHI:%.*]] = phi float [ 0.000000e+00, %[[VECTOR_PH]] ], [ [[TMP5:%.*]], %[[VECTOR_BODY]] ]
; CHECK-VF1-IC2-NEXT:    [[VEC_PHI1:%.*]] = phi float [ 0.000000e+00, %[[VECTOR_PH]] ], [ [[TMP6:%.*]], %[[VECTOR_BODY]] ]
; CHECK-VF1-IC2-NEXT:    [[TMP0:%.*]] = add i64 [[INDEX]], 1
; CHECK-VF1-IC2-NEXT:    [[TMP1:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[INDEX]]
; CHECK-VF1-IC2-NEXT:    [[TMP2:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[TMP0]]
; CHECK-VF1-IC2-NEXT:    [[TMP3:%.*]] = load float, ptr [[TMP1]], align 4
; CHECK-VF1-IC2-NEXT:    [[TMP4:%.*]] = load float, ptr [[TMP2]], align 4
; CHECK-VF1-IC2-NEXT:    [[TMP5]] = fadd fast float [[VEC_PHI]], [[TMP3]]
; CHECK-VF1-IC2-NEXT:    [[TMP6]] = fadd fast float [[VEC_PHI1]], [[TMP4]]
; CHECK-VF1-IC2-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 2
; CHECK-VF1-IC2-NEXT:    [[TMP7:%.*]] = icmp eq i64 [[INDEX_NEXT]], 256
; CHECK-VF1-IC2-NEXT:    br i1 [[TMP7]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], {{!llvm.loop ![0-9]+}}
; CHECK-VF1-IC2:       [[MIDDLE_BLOCK]]:
; CHECK-VF1-IC2-NEXT:    [[BIN_RDX:%.*]] = fadd fast float [[TMP6]], [[TMP5]]
; CHECK-VF1-IC2-NEXT:    br label %[[LOOP_EXIT:.*]]
; CHECK-VF1-IC2:       [[LOOP_EXIT]]:
; CHECK-VF1-IC2-NEXT:    ret float [[BIN_RDX]]
;
entry:
  br label %scalar.loop

scalar.loop:                                           ; preds = %entry, %scalar.loop
  %indvars.iv = phi i64 [ %indvars.iv.next, %scalar.loop ], [ 0, %entry ]
  %sum.02 = phi float [ %l7, %scalar.loop ], [ 0.000000e+00, %entry ]
  %l2 = getelementptr inbounds float, ptr %A, i64 %indvars.iv
  %l3 = load float, ptr %l2, align 4
  %l7 = fadd fast float %sum.02, %l3
  %indvars.iv.next = add i64 %indvars.iv, 1
  %lftr.wideiv = trunc i64 %indvars.iv.next to i32
  %exitcond = icmp eq i32 %lftr.wideiv, 256
  br i1 %exitcond, label %loop.exit, label %scalar.loop

loop.exit:                                      ; preds = %scalar.loop
  %sum.0.lcssa = phi float [ %l7, %scalar.loop ]
  ret float %sum.0.lcssa
}

define <4 x float> @reduction_fadd_4xf32(ptr noalias nocapture %A) {
; CHECK-LABEL: define <4 x float> @reduction_fadd_4xf32(
; CHECK-SAME: ptr noalias captures(none) [[A:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[SCALAR_LOOP:.*]]
; CHECK:       [[SCALAR_LOOP]]:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], %[[SCALAR_LOOP]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    [[SUM_02:%.*]] = phi <4 x float> [ [[L7:%.*]], %[[SCALAR_LOOP]] ], [ zeroinitializer, %[[ENTRY]] ]
; CHECK-NEXT:    [[L2:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[L3:%.*]] = load <4 x float>, ptr [[L2]], align 4
; CHECK-NEXT:    [[L7]] = fadd <4 x float> [[SUM_02]], [[L3]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add i64 [[INDVARS_IV]], 4
; CHECK-NEXT:    [[LFTR_WIDEIV:%.*]] = trunc i64 [[INDVARS_IV_NEXT]] to i32
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp eq i32 [[LFTR_WIDEIV]], 256
; CHECK-NEXT:    br i1 [[EXITCOND]], label %[[LOOP_EXIT:.*]], label %[[SCALAR_LOOP]]
; CHECK:       [[LOOP_EXIT]]:
; CHECK-NEXT:    [[SUM_0_LCSSA:%.*]] = phi <4 x float> [ [[L7]], %[[SCALAR_LOOP]] ]
; CHECK-NEXT:    ret <4 x float> [[SUM_0_LCSSA]]
;
; CHECK-IC2-LABEL: define <4 x float> @reduction_fadd_4xf32(
; CHECK-IC2-SAME: ptr noalias captures(none) [[A:%.*]]) #[[ATTR0]] {
; CHECK-IC2-NEXT:  [[ENTRY:.*]]:
; CHECK-IC2-NEXT:    br label %[[SCALAR_LOOP:.*]]
; CHECK-IC2:       [[SCALAR_LOOP]]:
; CHECK-IC2-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], %[[SCALAR_LOOP]] ], [ 0, %[[ENTRY]] ]
; CHECK-IC2-NEXT:    [[SUM_02:%.*]] = phi <4 x float> [ [[L7:%.*]], %[[SCALAR_LOOP]] ], [ zeroinitializer, %[[ENTRY]] ]
; CHECK-IC2-NEXT:    [[L2:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[INDVARS_IV]]
; CHECK-IC2-NEXT:    [[L3:%.*]] = load <4 x float>, ptr [[L2]], align 4
; CHECK-IC2-NEXT:    [[L7]] = fadd <4 x float> [[SUM_02]], [[L3]]
; CHECK-IC2-NEXT:    [[INDVARS_IV_NEXT]] = add i64 [[INDVARS_IV]], 4
; CHECK-IC2-NEXT:    [[LFTR_WIDEIV:%.*]] = trunc i64 [[INDVARS_IV_NEXT]] to i32
; CHECK-IC2-NEXT:    [[EXITCOND:%.*]] = icmp eq i32 [[LFTR_WIDEIV]], 256
; CHECK-IC2-NEXT:    br i1 [[EXITCOND]], label %[[LOOP_EXIT:.*]], label %[[SCALAR_LOOP]]
; CHECK-IC2:       [[LOOP_EXIT]]:
; CHECK-IC2-NEXT:    [[SUM_0_LCSSA:%.*]] = phi <4 x float> [ [[L7]], %[[SCALAR_LOOP]] ]
; CHECK-IC2-NEXT:    ret <4 x float> [[SUM_0_LCSSA]]
;
; CHECK-VF1-IC2-LABEL: define <4 x float> @reduction_fadd_4xf32(
; CHECK-VF1-IC2-SAME: ptr noalias captures(none) [[A:%.*]]) #[[ATTR0]] {
; CHECK-VF1-IC2-NEXT:  [[ENTRY:.*]]:
; CHECK-VF1-IC2-NEXT:    br label %[[SCALAR_LOOP:.*]]
; CHECK-VF1-IC2:       [[SCALAR_LOOP]]:
; CHECK-VF1-IC2-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], %[[SCALAR_LOOP]] ], [ 0, %[[ENTRY]] ]
; CHECK-VF1-IC2-NEXT:    [[SUM_02:%.*]] = phi <4 x float> [ [[L7:%.*]], %[[SCALAR_LOOP]] ], [ zeroinitializer, %[[ENTRY]] ]
; CHECK-VF1-IC2-NEXT:    [[L2:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[INDVARS_IV]]
; CHECK-VF1-IC2-NEXT:    [[L3:%.*]] = load <4 x float>, ptr [[L2]], align 4
; CHECK-VF1-IC2-NEXT:    [[L7]] = fadd <4 x float> [[SUM_02]], [[L3]]
; CHECK-VF1-IC2-NEXT:    [[INDVARS_IV_NEXT]] = add i64 [[INDVARS_IV]], 4
; CHECK-VF1-IC2-NEXT:    [[LFTR_WIDEIV:%.*]] = trunc i64 [[INDVARS_IV_NEXT]] to i32
; CHECK-VF1-IC2-NEXT:    [[EXITCOND:%.*]] = icmp eq i32 [[LFTR_WIDEIV]], 256
; CHECK-VF1-IC2-NEXT:    br i1 [[EXITCOND]], label %[[LOOP_EXIT:.*]], label %[[SCALAR_LOOP]]
; CHECK-VF1-IC2:       [[LOOP_EXIT]]:
; CHECK-VF1-IC2-NEXT:    [[SUM_0_LCSSA:%.*]] = phi <4 x float> [ [[L7]], %[[SCALAR_LOOP]] ]
; CHECK-VF1-IC2-NEXT:    ret <4 x float> [[SUM_0_LCSSA]]
;
entry:
  br label %scalar.loop

scalar.loop:                                           ; preds = %entry, %scalar.loop
  %indvars.iv = phi i64 [ %indvars.iv.next, %scalar.loop ], [ 0, %entry ]
  %sum.02 = phi <4 x float> [ %l7, %scalar.loop ], [ zeroinitializer, %entry ]
  %l2 = getelementptr inbounds float, ptr %A, i64 %indvars.iv
  %l3 = load <4 x float>, ptr %l2, align 4
  %l7 = fadd <4 x float> %sum.02, %l3
  %indvars.iv.next = add i64 %indvars.iv, 4
  %lftr.wideiv = trunc i64 %indvars.iv.next to i32
  %exitcond = icmp eq i32 %lftr.wideiv, 256
  br i1 %exitcond, label %loop.exit, label %scalar.loop

loop.exit:                                      ; preds = %scalar.loop
  %sum.0.lcssa = phi <4 x float> [ %l7, %scalar.loop ]
  ret <4 x float> %sum.0.lcssa
}

define <4 x float> @reduction_fadd_fast_4xf32(ptr noalias nocapture %A) {
; CHECK-LABEL: define <4 x float> @reduction_fadd_fast_4xf32(
; CHECK-SAME: ptr noalias captures(none) [[A:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[SCALAR_LOOP:.*]]
; CHECK:       [[SCALAR_LOOP]]:
; CHECK-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], %[[SCALAR_LOOP]] ], [ 0, %[[ENTRY]] ]
; CHECK-NEXT:    [[SUM_02:%.*]] = phi fast <4 x float> [ [[L7:%.*]], %[[SCALAR_LOOP]] ], [ zeroinitializer, %[[ENTRY]] ]
; CHECK-NEXT:    [[L2:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[INDVARS_IV]]
; CHECK-NEXT:    [[L3:%.*]] = load <4 x float>, ptr [[L2]], align 4
; CHECK-NEXT:    [[L7]] = fadd fast <4 x float> [[SUM_02]], [[L3]]
; CHECK-NEXT:    [[INDVARS_IV_NEXT]] = add i64 [[INDVARS_IV]], 4
; CHECK-NEXT:    [[LFTR_WIDEIV:%.*]] = trunc i64 [[INDVARS_IV_NEXT]] to i32
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp eq i32 [[LFTR_WIDEIV]], 256
; CHECK-NEXT:    br i1 [[EXITCOND]], label %[[LOOP_EXIT:.*]], label %[[SCALAR_LOOP]]
; CHECK:       [[LOOP_EXIT]]:
; CHECK-NEXT:    [[SUM_0_LCSSA:%.*]] = phi fast <4 x float> [ [[L7]], %[[SCALAR_LOOP]] ]
; CHECK-NEXT:    ret <4 x float> [[SUM_0_LCSSA]]
;
; CHECK-IC2-LABEL: define <4 x float> @reduction_fadd_fast_4xf32(
; CHECK-IC2-SAME: ptr noalias captures(none) [[A:%.*]]) #[[ATTR0]] {
; CHECK-IC2-NEXT:  [[ENTRY:.*]]:
; CHECK-IC2-NEXT:    br label %[[SCALAR_LOOP:.*]]
; CHECK-IC2:       [[SCALAR_LOOP]]:
; CHECK-IC2-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], %[[SCALAR_LOOP]] ], [ 0, %[[ENTRY]] ]
; CHECK-IC2-NEXT:    [[SUM_02:%.*]] = phi fast <4 x float> [ [[L7:%.*]], %[[SCALAR_LOOP]] ], [ zeroinitializer, %[[ENTRY]] ]
; CHECK-IC2-NEXT:    [[L2:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[INDVARS_IV]]
; CHECK-IC2-NEXT:    [[L3:%.*]] = load <4 x float>, ptr [[L2]], align 4
; CHECK-IC2-NEXT:    [[L7]] = fadd fast <4 x float> [[SUM_02]], [[L3]]
; CHECK-IC2-NEXT:    [[INDVARS_IV_NEXT]] = add i64 [[INDVARS_IV]], 4
; CHECK-IC2-NEXT:    [[LFTR_WIDEIV:%.*]] = trunc i64 [[INDVARS_IV_NEXT]] to i32
; CHECK-IC2-NEXT:    [[EXITCOND:%.*]] = icmp eq i32 [[LFTR_WIDEIV]], 256
; CHECK-IC2-NEXT:    br i1 [[EXITCOND]], label %[[LOOP_EXIT:.*]], label %[[SCALAR_LOOP]]
; CHECK-IC2:       [[LOOP_EXIT]]:
; CHECK-IC2-NEXT:    [[SUM_0_LCSSA:%.*]] = phi fast <4 x float> [ [[L7]], %[[SCALAR_LOOP]] ]
; CHECK-IC2-NEXT:    ret <4 x float> [[SUM_0_LCSSA]]
;
; CHECK-VF1-IC2-LABEL: define <4 x float> @reduction_fadd_fast_4xf32(
; CHECK-VF1-IC2-SAME: ptr noalias captures(none) [[A:%.*]]) #[[ATTR0]] {
; CHECK-VF1-IC2-NEXT:  [[ENTRY:.*]]:
; CHECK-VF1-IC2-NEXT:    br label %[[SCALAR_LOOP:.*]]
; CHECK-VF1-IC2:       [[SCALAR_LOOP]]:
; CHECK-VF1-IC2-NEXT:    [[INDVARS_IV:%.*]] = phi i64 [ [[INDVARS_IV_NEXT:%.*]], %[[SCALAR_LOOP]] ], [ 0, %[[ENTRY]] ]
; CHECK-VF1-IC2-NEXT:    [[SUM_02:%.*]] = phi fast <4 x float> [ [[L7:%.*]], %[[SCALAR_LOOP]] ], [ zeroinitializer, %[[ENTRY]] ]
; CHECK-VF1-IC2-NEXT:    [[L2:%.*]] = getelementptr inbounds float, ptr [[A]], i64 [[INDVARS_IV]]
; CHECK-VF1-IC2-NEXT:    [[L3:%.*]] = load <4 x float>, ptr [[L2]], align 4
; CHECK-VF1-IC2-NEXT:    [[L7]] = fadd fast <4 x float> [[SUM_02]], [[L3]]
; CHECK-VF1-IC2-NEXT:    [[INDVARS_IV_NEXT]] = add i64 [[INDVARS_IV]], 4
; CHECK-VF1-IC2-NEXT:    [[LFTR_WIDEIV:%.*]] = trunc i64 [[INDVARS_IV_NEXT]] to i32
; CHECK-VF1-IC2-NEXT:    [[EXITCOND:%.*]] = icmp eq i32 [[LFTR_WIDEIV]], 256
; CHECK-VF1-IC2-NEXT:    br i1 [[EXITCOND]], label %[[LOOP_EXIT:.*]], label %[[SCALAR_LOOP]]
; CHECK-VF1-IC2:       [[LOOP_EXIT]]:
; CHECK-VF1-IC2-NEXT:    [[SUM_0_LCSSA:%.*]] = phi fast <4 x float> [ [[L7]], %[[SCALAR_LOOP]] ]
; CHECK-VF1-IC2-NEXT:    ret <4 x float> [[SUM_0_LCSSA]]
;
entry:
  br label %scalar.loop

scalar.loop:                                           ; preds = %entry, %scalar.loop
  %indvars.iv = phi i64 [ %indvars.iv.next, %scalar.loop ], [ 0, %entry ]
  %sum.02 = phi fast <4 x float> [ %l7, %scalar.loop ], [ zeroinitializer, %entry ]
  %l2 = getelementptr inbounds float, ptr %A, i64 %indvars.iv
  %l3 = load <4 x float>, ptr %l2, align 4
  %l7 = fadd fast <4 x float> %sum.02, %l3
  %indvars.iv.next = add i64 %indvars.iv, 4
  %lftr.wideiv = trunc i64 %indvars.iv.next to i32
  %exitcond = icmp eq i32 %lftr.wideiv, 256
  br i1 %exitcond, label %loop.exit, label %scalar.loop

loop.exit:                                      ; preds = %scalar.loop
  %sum.0.lcssa = phi fast <4 x float> [ %l7, %scalar.loop ]
  ret <4 x float> %sum.0.lcssa
}
