; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals none --filter-out-after "scalar.body:" --version 5
; RUN: opt -passes=loop-vectorize -scalable-vectorization=on -force-vector-width=1 -force-vector-interleave=1 -force-target-supports-scalable-vectors=true -vectorize-vector-loops -S < %s | FileCheck %s --check-prefix=CHECK-UF1
; RUN: opt -passes=loop-vectorize -scalable-vectorization=on -force-vector-width=1 -force-vector-interleave=2 -force-target-supports-scalable-vectors=true -vectorize-vector-loops -S < %s | FileCheck %s --check-prefix=CHECK-UF2

; void recurrence_1(int *a, int *b, int n) {
;   for(int i = 0; i < n; i++)
;     b[i] =  a[i] + a[i - 1]
; }
;
define <4 x i32> @recurrence_1(ptr nocapture readonly %a, ptr nocapture noalias %b, i32 %n) {
; CHECK-UF1-LABEL: define <4 x i32> @recurrence_1(
; CHECK-UF1-SAME: ptr readonly captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i32 [[N:%.*]]) {
; CHECK-UF1-NEXT:  [[ENTRY:.*:]]
; CHECK-UF1-NEXT:    br label %[[FOR_PREHEADER:.*]]
; CHECK-UF1:       [[FOR_PREHEADER]]:
; CHECK-UF1-NEXT:    [[PRE_LOAD:%.*]] = load <4 x i32>, ptr [[A]], align 16
; CHECK-UF1-NEXT:    [[BROADCAST:%.*]] = call <vscale x 4 x i32> @llvm.vector.broadcast.nxv4i32.v4i32(<4 x i32> [[PRE_LOAD]])
; CHECK-UF1-NEXT:    [[TMP0:%.*]] = add i32 [[N]], -1
; CHECK-UF1-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i64
; CHECK-UF1-NEXT:    [[TMP2:%.*]] = add nuw nsw i64 [[TMP1]], 1
; CHECK-UF1-NEXT:    [[TMP4:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-UF1-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[TMP2]], [[TMP4]]
; CHECK-UF1-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK-UF1:       [[VECTOR_PH]]:
; CHECK-UF1-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[TMP2]], [[TMP4]]
; CHECK-UF1-NEXT:    [[N_VEC:%.*]] = sub i64 [[TMP2]], [[N_MOD_VF]]
; CHECK-UF1-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-UF1:       [[VECTOR_BODY]]:
; CHECK-UF1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-UF1-NEXT:    [[VECTOR_RECUR:%.*]] = phi <vscale x 4 x i32> [ [[BROADCAST]], %[[VECTOR_PH]] ], [ [[WIDE_LOAD:%.*]], %[[VECTOR_BODY]] ]
; CHECK-UF1-NEXT:    [[TMP9:%.*]] = add nuw nsw i64 [[INDEX]], 1
; CHECK-UF1-NEXT:    [[TMP10:%.*]] = getelementptr inbounds <4 x i32>, ptr [[A]], i64 [[TMP9]]
; CHECK-UF1-NEXT:    [[WIDE_LOAD]] = load <vscale x 4 x i32>, ptr [[TMP10]], align 16
; CHECK-UF1-NEXT:    [[TMP11:%.*]] = call <vscale x 4 x i32> @llvm.vector.splice.right.nxv4i32(<vscale x 4 x i32> [[VECTOR_RECUR]], <vscale x 4 x i32> [[WIDE_LOAD]], i32 4)
; CHECK-UF1-NEXT:    [[TMP12:%.*]] = getelementptr inbounds <4 x i32>, ptr [[B]], i64 [[INDEX]]
; CHECK-UF1-NEXT:    [[TMP13:%.*]] = add <vscale x 4 x i32> [[WIDE_LOAD]], [[TMP11]]
; CHECK-UF1-NEXT:    store <vscale x 4 x i32> [[TMP13]], ptr [[TMP12]], align 16
; CHECK-UF1-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP4]]
; CHECK-UF1-NEXT:    [[TMP14:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-UF1-NEXT:    br i1 [[TMP14]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK-UF1:       [[MIDDLE_BLOCK]]:
; CHECK-UF1-NEXT:    [[TMP15:%.*]] = call <vscale x 4 x i32> @llvm.vector.splice.right.nxv4i32(<vscale x 4 x i32> [[WIDE_LOAD]], <vscale x 4 x i32> poison, i32 4)
; CHECK-UF1-NEXT:    [[TMP16:%.*]] = call <4 x i32> @llvm.vector.extract.v4i32.nxv4i32(<vscale x 4 x i32> [[TMP15]], i64 0)
; CHECK-UF1-NEXT:    [[TMP17:%.*]] = call <vscale x 4 x i32> @llvm.vector.splice.right.nxv4i32(<vscale x 4 x i32> [[TMP11]], <vscale x 4 x i32> poison, i32 4)
; CHECK-UF1-NEXT:    [[TMP18:%.*]] = call <4 x i32> @llvm.vector.extract.v4i32.nxv4i32(<vscale x 4 x i32> [[TMP17]], i64 0)
; CHECK-UF1-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[TMP2]], [[N_VEC]]
; CHECK-UF1-NEXT:    br i1 [[CMP_N]], [[FOR_EXIT:label %.*]], label %[[SCALAR_PH]]
; CHECK-UF1:       [[SCALAR_PH]]:
; CHECK-UF1-NEXT:    [[SCALAR_RECUR_INIT:%.*]] = phi <4 x i32> [ [[TMP16]], %[[MIDDLE_BLOCK]] ], [ [[PRE_LOAD]], %[[FOR_PREHEADER]] ]
; CHECK-UF1-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[FOR_PREHEADER]] ]
; CHECK-UF1-NEXT:    br label %[[SCALAR_BODY:.*]]
; CHECK-UF1:       [[SCALAR_BODY]]:
;
; CHECK-UF2-LABEL: define <4 x i32> @recurrence_1(
; CHECK-UF2-SAME: ptr readonly captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i32 [[N:%.*]]) {
; CHECK-UF2-NEXT:  [[ENTRY:.*:]]
; CHECK-UF2-NEXT:    br label %[[FOR_PREHEADER:.*]]
; CHECK-UF2:       [[FOR_PREHEADER]]:
; CHECK-UF2-NEXT:    [[PRE_LOAD:%.*]] = load <4 x i32>, ptr [[A]], align 16
; CHECK-UF2-NEXT:    [[BROADCAST:%.*]] = call <vscale x 4 x i32> @llvm.vector.broadcast.nxv4i32.v4i32(<4 x i32> [[PRE_LOAD]])
; CHECK-UF2-NEXT:    [[TMP0:%.*]] = add i32 [[N]], -1
; CHECK-UF2-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i64
; CHECK-UF2-NEXT:    [[TMP2:%.*]] = add nuw nsw i64 [[TMP1]], 1
; CHECK-UF2-NEXT:    [[TMP3:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-UF2-NEXT:    [[TMP4:%.*]] = shl nuw i64 [[TMP3]], 1
; CHECK-UF2-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[TMP2]], [[TMP4]]
; CHECK-UF2-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK-UF2:       [[VECTOR_PH]]:
; CHECK-UF2-NEXT:    [[TMP10:%.*]] = shl nuw i64 [[TMP3]], 1
; CHECK-UF2-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[TMP2]], [[TMP10]]
; CHECK-UF2-NEXT:    [[N_VEC:%.*]] = sub i64 [[TMP2]], [[N_MOD_VF]]
; CHECK-UF2-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-UF2:       [[VECTOR_BODY]]:
; CHECK-UF2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-UF2-NEXT:    [[VECTOR_RECUR:%.*]] = phi <vscale x 4 x i32> [ [[BROADCAST]], %[[VECTOR_PH]] ], [ [[WIDE_LOAD3:%.*]], %[[VECTOR_BODY]] ]
; CHECK-UF2-NEXT:    [[TMP11:%.*]] = add nuw nsw i64 [[INDEX]], 1
; CHECK-UF2-NEXT:    [[TMP12:%.*]] = getelementptr inbounds <4 x i32>, ptr [[A]], i64 [[TMP11]]
; CHECK-UF2-NEXT:    [[TMP15:%.*]] = getelementptr inbounds <4 x i32>, ptr [[TMP12]], i64 [[TMP3]]
; CHECK-UF2-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i32>, ptr [[TMP12]], align 16
; CHECK-UF2-NEXT:    [[WIDE_LOAD3]] = load <vscale x 4 x i32>, ptr [[TMP15]], align 16
; CHECK-UF2-NEXT:    [[TMP16:%.*]] = call <vscale x 4 x i32> @llvm.vector.splice.right.nxv4i32(<vscale x 4 x i32> [[VECTOR_RECUR]], <vscale x 4 x i32> [[WIDE_LOAD]], i32 4)
; CHECK-UF2-NEXT:    [[TMP17:%.*]] = call <vscale x 4 x i32> @llvm.vector.splice.right.nxv4i32(<vscale x 4 x i32> [[WIDE_LOAD]], <vscale x 4 x i32> [[WIDE_LOAD3]], i32 4)
; CHECK-UF2-NEXT:    [[TMP18:%.*]] = getelementptr inbounds <4 x i32>, ptr [[B]], i64 [[INDEX]]
; CHECK-UF2-NEXT:    [[TMP19:%.*]] = add <vscale x 4 x i32> [[WIDE_LOAD]], [[TMP16]]
; CHECK-UF2-NEXT:    [[TMP20:%.*]] = add <vscale x 4 x i32> [[WIDE_LOAD3]], [[TMP17]]
; CHECK-UF2-NEXT:    [[TMP23:%.*]] = getelementptr inbounds <4 x i32>, ptr [[TMP18]], i64 [[TMP3]]
; CHECK-UF2-NEXT:    store <vscale x 4 x i32> [[TMP19]], ptr [[TMP18]], align 16
; CHECK-UF2-NEXT:    store <vscale x 4 x i32> [[TMP20]], ptr [[TMP23]], align 16
; CHECK-UF2-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP10]]
; CHECK-UF2-NEXT:    [[TMP24:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-UF2-NEXT:    br i1 [[TMP24]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK-UF2:       [[MIDDLE_BLOCK]]:
; CHECK-UF2-NEXT:    [[TMP25:%.*]] = call <vscale x 4 x i32> @llvm.vector.splice.right.nxv4i32(<vscale x 4 x i32> [[WIDE_LOAD3]], <vscale x 4 x i32> poison, i32 4)
; CHECK-UF2-NEXT:    [[TMP26:%.*]] = call <4 x i32> @llvm.vector.extract.v4i32.nxv4i32(<vscale x 4 x i32> [[TMP25]], i64 0)
; CHECK-UF2-NEXT:    [[TMP27:%.*]] = call <vscale x 4 x i32> @llvm.vector.splice.right.nxv4i32(<vscale x 4 x i32> [[TMP17]], <vscale x 4 x i32> poison, i32 4)
; CHECK-UF2-NEXT:    [[TMP28:%.*]] = call <4 x i32> @llvm.vector.extract.v4i32.nxv4i32(<vscale x 4 x i32> [[TMP27]], i64 0)
; CHECK-UF2-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[TMP2]], [[N_VEC]]
; CHECK-UF2-NEXT:    br i1 [[CMP_N]], [[FOR_EXIT:label %.*]], label %[[SCALAR_PH]]
; CHECK-UF2:       [[SCALAR_PH]]:
; CHECK-UF2-NEXT:    [[SCALAR_RECUR_INIT:%.*]] = phi <4 x i32> [ [[TMP26]], %[[MIDDLE_BLOCK]] ], [ [[PRE_LOAD]], %[[FOR_PREHEADER]] ]
; CHECK-UF2-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[FOR_PREHEADER]] ]
; CHECK-UF2-NEXT:    br label %[[SCALAR_BODY:.*]]
; CHECK-UF2:       [[SCALAR_BODY]]:
;
entry:
  br label %for.preheader

for.preheader:
  %pre_load = load <4 x i32>, ptr %a
  br label %scalar.body

scalar.body:
  %0 = phi <4 x i32> [ %pre_load, %for.preheader ], [ %1, %scalar.body ]
  %indvars.iv = phi i64 [ 0, %for.preheader ], [ %indvars.iv.next, %scalar.body ]
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %arrayidx32 = getelementptr inbounds <4 x i32>, ptr %a, i64 %indvars.iv.next
  %1 = load <4 x i32>, ptr %arrayidx32
  %arrayidx34 = getelementptr inbounds <4 x i32>, ptr %b, i64 %indvars.iv
  %add35 = add <4 x i32> %1, %0
  store <4 x i32> %add35, ptr %arrayidx34
  %lftr.wideiv = trunc i64 %indvars.iv.next to i32
  %exitcond = icmp eq i32 %lftr.wideiv, %n
  br i1 %exitcond, label %for.exit, label %scalar.body

for.exit:
  ret <4 x i32> %0
}

; A second order recurrence is represented as a chain or first order ones.
; void recurrence_2(int *a, int *b, int n) {
;   for(int i = 0; i < n; i++)
;     b[i] =  a[i] + a[i - 2]
; }
define <4 x i32> @recurrence_2(ptr nocapture readonly %a, ptr nocapture noalias %b, i32 %n) {
; CHECK-UF1-LABEL: define <4 x i32> @recurrence_2(
; CHECK-UF1-SAME: ptr readonly captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i32 [[N:%.*]]) {
; CHECK-UF1-NEXT:  [[ENTRY:.*:]]
; CHECK-UF1-NEXT:    br label %[[FOR_PREHEADER:.*]]
; CHECK-UF1:       [[FOR_PREHEADER]]:
; CHECK-UF1-NEXT:    [[PRE_LOAD:%.*]] = load <4 x i32>, ptr [[A]], align 16
; CHECK-UF1-NEXT:    [[BROADCAST:%.*]] = call <vscale x 4 x i32> @llvm.vector.broadcast.nxv4i32.v4i32(<4 x i32> [[PRE_LOAD]])
; CHECK-UF1-NEXT:    [[TMP0:%.*]] = add i32 [[N]], -1
; CHECK-UF1-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i64
; CHECK-UF1-NEXT:    [[TMP2:%.*]] = add nuw nsw i64 [[TMP1]], 1
; CHECK-UF1-NEXT:    [[TMP3:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-UF1-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[TMP2]], [[TMP3]]
; CHECK-UF1-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK-UF1:       [[VECTOR_PH]]:
; CHECK-UF1-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[TMP2]], [[TMP3]]
; CHECK-UF1-NEXT:    [[N_VEC:%.*]] = sub i64 [[TMP2]], [[N_MOD_VF]]
; CHECK-UF1-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-UF1:       [[VECTOR_BODY]]:
; CHECK-UF1-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-UF1-NEXT:    [[VECTOR_RECUR:%.*]] = phi <vscale x 4 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP7:%.*]], %[[VECTOR_BODY]] ]
; CHECK-UF1-NEXT:    [[VECTOR_RECUR1:%.*]] = phi <vscale x 4 x i32> [ [[BROADCAST]], %[[VECTOR_PH]] ], [ [[WIDE_LOAD:%.*]], %[[VECTOR_BODY]] ]
; CHECK-UF1-NEXT:    [[TMP5:%.*]] = add nuw nsw i64 [[INDEX]], 1
; CHECK-UF1-NEXT:    [[TMP6:%.*]] = getelementptr inbounds <4 x i32>, ptr [[A]], i64 [[TMP5]]
; CHECK-UF1-NEXT:    [[WIDE_LOAD]] = load <vscale x 4 x i32>, ptr [[TMP6]], align 16
; CHECK-UF1-NEXT:    [[TMP7]] = call <vscale x 4 x i32> @llvm.vector.splice.right.nxv4i32(<vscale x 4 x i32> [[VECTOR_RECUR1]], <vscale x 4 x i32> [[WIDE_LOAD]], i32 4)
; CHECK-UF1-NEXT:    [[TMP8:%.*]] = call <vscale x 4 x i32> @llvm.vector.splice.right.nxv4i32(<vscale x 4 x i32> [[VECTOR_RECUR]], <vscale x 4 x i32> [[TMP7]], i32 4)
; CHECK-UF1-NEXT:    [[TMP9:%.*]] = getelementptr inbounds <4 x i32>, ptr [[B]], i64 [[INDEX]]
; CHECK-UF1-NEXT:    [[TMP10:%.*]] = add <vscale x 4 x i32> [[WIDE_LOAD]], [[TMP8]]
; CHECK-UF1-NEXT:    store <vscale x 4 x i32> [[TMP10]], ptr [[TMP9]], align 16
; CHECK-UF1-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP3]]
; CHECK-UF1-NEXT:    [[TMP11:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-UF1-NEXT:    br i1 [[TMP11]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK-UF1:       [[MIDDLE_BLOCK]]:
; CHECK-UF1-NEXT:    [[TMP12:%.*]] = call <vscale x 4 x i32> @llvm.vector.splice.right.nxv4i32(<vscale x 4 x i32> [[TMP7]], <vscale x 4 x i32> poison, i32 4)
; CHECK-UF1-NEXT:    [[TMP13:%.*]] = call <4 x i32> @llvm.vector.extract.v4i32.nxv4i32(<vscale x 4 x i32> [[TMP12]], i64 0)
; CHECK-UF1-NEXT:    [[TMP14:%.*]] = call <vscale x 4 x i32> @llvm.vector.splice.right.nxv4i32(<vscale x 4 x i32> [[WIDE_LOAD]], <vscale x 4 x i32> poison, i32 4)
; CHECK-UF1-NEXT:    [[TMP15:%.*]] = call <4 x i32> @llvm.vector.extract.v4i32.nxv4i32(<vscale x 4 x i32> [[TMP14]], i64 0)
; CHECK-UF1-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[TMP2]], [[N_VEC]]
; CHECK-UF1-NEXT:    br i1 [[CMP_N]], [[FOR_EXIT:label %.*]], label %[[SCALAR_PH]]
; CHECK-UF1:       [[SCALAR_PH]]:
; CHECK-UF1-NEXT:    [[SCALAR_RECUR_INIT:%.*]] = phi <4 x i32> [ [[TMP13]], %[[MIDDLE_BLOCK]] ], [ zeroinitializer, %[[FOR_PREHEADER]] ]
; CHECK-UF1-NEXT:    [[SCALAR_RECUR_INIT2:%.*]] = phi <4 x i32> [ [[TMP15]], %[[MIDDLE_BLOCK]] ], [ [[PRE_LOAD]], %[[FOR_PREHEADER]] ]
; CHECK-UF1-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[FOR_PREHEADER]] ]
; CHECK-UF1-NEXT:    br label %[[SCALAR_BODY:.*]]
; CHECK-UF1:       [[SCALAR_BODY]]:
;
; CHECK-UF2-LABEL: define <4 x i32> @recurrence_2(
; CHECK-UF2-SAME: ptr readonly captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i32 [[N:%.*]]) {
; CHECK-UF2-NEXT:  [[ENTRY:.*:]]
; CHECK-UF2-NEXT:    br label %[[FOR_PREHEADER:.*]]
; CHECK-UF2:       [[FOR_PREHEADER]]:
; CHECK-UF2-NEXT:    [[PRE_LOAD:%.*]] = load <4 x i32>, ptr [[A]], align 16
; CHECK-UF2-NEXT:    [[BROADCAST:%.*]] = call <vscale x 4 x i32> @llvm.vector.broadcast.nxv4i32.v4i32(<4 x i32> [[PRE_LOAD]])
; CHECK-UF2-NEXT:    [[TMP0:%.*]] = add i32 [[N]], -1
; CHECK-UF2-NEXT:    [[TMP1:%.*]] = zext i32 [[TMP0]] to i64
; CHECK-UF2-NEXT:    [[TMP2:%.*]] = add nuw nsw i64 [[TMP1]], 1
; CHECK-UF2-NEXT:    [[TMP3:%.*]] = call i64 @llvm.vscale.i64()
; CHECK-UF2-NEXT:    [[TMP4:%.*]] = shl nuw i64 [[TMP3]], 1
; CHECK-UF2-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i64 [[TMP2]], [[TMP4]]
; CHECK-UF2-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_PH:.*]]
; CHECK-UF2:       [[VECTOR_PH]]:
; CHECK-UF2-NEXT:    [[TMP6:%.*]] = shl nuw i64 [[TMP3]], 1
; CHECK-UF2-NEXT:    [[N_MOD_VF:%.*]] = urem i64 [[TMP2]], [[TMP6]]
; CHECK-UF2-NEXT:    [[N_VEC:%.*]] = sub i64 [[TMP2]], [[N_MOD_VF]]
; CHECK-UF2-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK-UF2:       [[VECTOR_BODY]]:
; CHECK-UF2-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-UF2-NEXT:    [[VECTOR_RECUR:%.*]] = phi <vscale x 4 x i32> [ zeroinitializer, %[[VECTOR_PH]] ], [ [[TMP10:%.*]], %[[VECTOR_BODY]] ]
; CHECK-UF2-NEXT:    [[VECTOR_RECUR1:%.*]] = phi <vscale x 4 x i32> [ [[BROADCAST]], %[[VECTOR_PH]] ], [ [[WIDE_LOAD2:%.*]], %[[VECTOR_BODY]] ]
; CHECK-UF2-NEXT:    [[TMP7:%.*]] = add nuw nsw i64 [[INDEX]], 1
; CHECK-UF2-NEXT:    [[TMP8:%.*]] = getelementptr inbounds <4 x i32>, ptr [[A]], i64 [[TMP7]]
; CHECK-UF2-NEXT:    [[TMP11:%.*]] = getelementptr inbounds <4 x i32>, ptr [[TMP8]], i64 [[TMP3]]
; CHECK-UF2-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 4 x i32>, ptr [[TMP8]], align 16
; CHECK-UF2-NEXT:    [[WIDE_LOAD2]] = load <vscale x 4 x i32>, ptr [[TMP11]], align 16
; CHECK-UF2-NEXT:    [[TMP9:%.*]] = call <vscale x 4 x i32> @llvm.vector.splice.right.nxv4i32(<vscale x 4 x i32> [[VECTOR_RECUR1]], <vscale x 4 x i32> [[WIDE_LOAD]], i32 4)
; CHECK-UF2-NEXT:    [[TMP10]] = call <vscale x 4 x i32> @llvm.vector.splice.right.nxv4i32(<vscale x 4 x i32> [[WIDE_LOAD]], <vscale x 4 x i32> [[WIDE_LOAD2]], i32 4)
; CHECK-UF2-NEXT:    [[TMP14:%.*]] = call <vscale x 4 x i32> @llvm.vector.splice.right.nxv4i32(<vscale x 4 x i32> [[VECTOR_RECUR]], <vscale x 4 x i32> [[TMP9]], i32 4)
; CHECK-UF2-NEXT:    [[TMP15:%.*]] = call <vscale x 4 x i32> @llvm.vector.splice.right.nxv4i32(<vscale x 4 x i32> [[TMP9]], <vscale x 4 x i32> [[TMP10]], i32 4)
; CHECK-UF2-NEXT:    [[TMP16:%.*]] = getelementptr inbounds <4 x i32>, ptr [[B]], i64 [[INDEX]]
; CHECK-UF2-NEXT:    [[TMP17:%.*]] = add <vscale x 4 x i32> [[WIDE_LOAD]], [[TMP14]]
; CHECK-UF2-NEXT:    [[TMP18:%.*]] = add <vscale x 4 x i32> [[WIDE_LOAD2]], [[TMP15]]
; CHECK-UF2-NEXT:    [[TMP21:%.*]] = getelementptr inbounds <4 x i32>, ptr [[TMP16]], i64 [[TMP3]]
; CHECK-UF2-NEXT:    store <vscale x 4 x i32> [[TMP17]], ptr [[TMP16]], align 16
; CHECK-UF2-NEXT:    store <vscale x 4 x i32> [[TMP18]], ptr [[TMP21]], align 16
; CHECK-UF2-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], [[TMP6]]
; CHECK-UF2-NEXT:    [[TMP22:%.*]] = icmp eq i64 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-UF2-NEXT:    br i1 [[TMP22]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK-UF2:       [[MIDDLE_BLOCK]]:
; CHECK-UF2-NEXT:    [[TMP23:%.*]] = call <vscale x 4 x i32> @llvm.vector.splice.right.nxv4i32(<vscale x 4 x i32> [[TMP10]], <vscale x 4 x i32> poison, i32 4)
; CHECK-UF2-NEXT:    [[TMP24:%.*]] = call <4 x i32> @llvm.vector.extract.v4i32.nxv4i32(<vscale x 4 x i32> [[TMP23]], i64 0)
; CHECK-UF2-NEXT:    [[TMP25:%.*]] = call <vscale x 4 x i32> @llvm.vector.splice.right.nxv4i32(<vscale x 4 x i32> [[WIDE_LOAD2]], <vscale x 4 x i32> poison, i32 4)
; CHECK-UF2-NEXT:    [[TMP26:%.*]] = call <4 x i32> @llvm.vector.extract.v4i32.nxv4i32(<vscale x 4 x i32> [[TMP25]], i64 0)
; CHECK-UF2-NEXT:    [[CMP_N:%.*]] = icmp eq i64 [[TMP2]], [[N_VEC]]
; CHECK-UF2-NEXT:    br i1 [[CMP_N]], [[FOR_EXIT:label %.*]], label %[[SCALAR_PH]]
; CHECK-UF2:       [[SCALAR_PH]]:
; CHECK-UF2-NEXT:    [[SCALAR_RECUR_INIT:%.*]] = phi <4 x i32> [ [[TMP24]], %[[MIDDLE_BLOCK]] ], [ zeroinitializer, %[[FOR_PREHEADER]] ]
; CHECK-UF2-NEXT:    [[SCALAR_RECUR_INIT3:%.*]] = phi <4 x i32> [ [[TMP26]], %[[MIDDLE_BLOCK]] ], [ [[PRE_LOAD]], %[[FOR_PREHEADER]] ]
; CHECK-UF2-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i64 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[FOR_PREHEADER]] ]
; CHECK-UF2-NEXT:    br label %[[SCALAR_BODY:.*]]
; CHECK-UF2:       [[SCALAR_BODY]]:
;
entry:
  br label %for.preheader

for.preheader:
  %pre_load = load <4 x i32>, ptr %a
  br label %scalar.body

scalar.body:
  %prev.2 = phi <4 x i32> [ zeroinitializer, %for.preheader ], [ %prev.1, %scalar.body ]
  %prev.1 = phi <4 x i32> [ %pre_load, %for.preheader ], [ %1, %scalar.body ]
  %indvars.iv = phi i64 [ 0, %for.preheader ], [ %indvars.iv.next, %scalar.body ]
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 1
  %arrayidx32 = getelementptr inbounds <4 x i32>, ptr %a, i64 %indvars.iv.next
  %1 = load <4 x i32>, ptr %arrayidx32
  %arrayidx34 = getelementptr inbounds <4 x i32>, ptr %b, i64 %indvars.iv
  %add36 = add <4 x i32> %1, %prev.2
  store <4 x i32> %add36, ptr %arrayidx34
  %lftr.wideiv = trunc i64 %indvars.iv.next to i32
  %exitcond = icmp eq i32 %lftr.wideiv, %n
  br i1 %exitcond, label %for.exit, label %scalar.body

for.exit:
  ret <4 x i32> %prev.1
}
