; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S < %s -p loop-vectorize -force-vector-width=4 | FileCheck %s

; Trip count is zext(add nsw %len, -1) where %len is known non-negative via !range. 
; TODO: SCEV must fold the zext through the add to compute the backedge-taken
; count, enabling vectorization.
define void @early_exit_zext_trip_count(ptr %p) {
; CHECK-LABEL: define void @early_exit_zext_trip_count(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[BASE:%.*]] = getelementptr inbounds nuw i8, ptr [[P]], i64 8
; CHECK-NEXT:    [[LEN:%.*]] = load atomic i32, ptr [[BASE]] unordered, align 4, !range [[RNG0:![0-9]+]]
; CHECK-NEXT:    [[LEN_PLUS_8:%.*]] = add nuw nsw i32 [[LEN]], 8
; CHECK-NEXT:    [[LEN_PLUS_8_WIDE:%.*]] = zext i32 [[LEN_PLUS_8]] to i64
; CHECK-NEXT:    call void @llvm.assume(i1 true) [ "dereferenceable"(ptr [[P]], i64 [[LEN_PLUS_8_WIDE]]) ]
; CHECK-NEXT:    [[LEN_IS_ZERO:%.*]] = icmp eq i32 [[LEN]], 0
; CHECK-NEXT:    br i1 [[LEN_IS_ZERO]], label [[RET:%.*]], label [[PREHEADER:%.*]]
; CHECK:       preheader:
; CHECK-NEXT:    [[EXIT_32:%.*]] = add nsw i32 [[LEN]], -1
; CHECK-NEXT:    [[EXIT:%.*]] = zext i32 [[EXIT_32]] to i64
; CHECK-NEXT:    br label [[LOOP:%.*]]
; CHECK:       loop:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ [[IV_NEXT:%.*]], [[LATCH:%.*]] ], [ 0, [[PREHEADER]] ]
; CHECK-NEXT:    [[ELEM_PTR:%.*]] = getelementptr inbounds nuw i8, ptr [[BASE]], i64 [[IV]]
; CHECK-NEXT:    [[ELEM:%.*]] = load i8, ptr [[ELEM_PTR]], align 1
; CHECK-NEXT:    [[IS_TARGET:%.*]] = icmp eq i8 [[ELEM]], 0
; CHECK-NEXT:    br i1 [[IS_TARGET]], label [[DEOPT:%.*]], label [[LATCH]]
; CHECK:       latch:
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; CHECK-NEXT:    [[LOOP_COND:%.*]] = icmp ult i64 [[IV]], [[EXIT]]
; CHECK-NEXT:    br i1 [[LOOP_COND]], label [[LOOP]], label [[RET_LOOPEXIT:%.*]]
; CHECK:       ret.loopexit:
; CHECK-NEXT:    br label [[RET]]
; CHECK:       ret:
; CHECK-NEXT:    ret void
; CHECK:       deopt:
; CHECK-NEXT:    call void @deopt()
; CHECK-NEXT:    unreachable
;
entry:
  %base = getelementptr inbounds nuw i8, ptr %p, i64 8
  %len = load atomic i32, ptr %base unordered, align 4, !range !0
  %len.plus.8 = add nuw nsw i32 %len, 8
  %len.plus.8.wide = zext i32 %len.plus.8 to i64
  call void @llvm.assume(i1 true) [ "dereferenceable"(ptr %p, i64 %len.plus.8.wide) ]
  %len.is.zero = icmp eq i32 %len, 0
  br i1 %len.is.zero, label %ret, label %preheader

preheader:                                        ; preds = %entry
  %exit.32 = add nsw i32 %len, -1
  %exit = zext i32 %exit.32 to i64
  br label %loop

loop:                                             ; preds = %latch, %preheader
  %iv = phi i64 [ %iv.next, %latch ], [ 0, %preheader ]
  %elem.ptr = getelementptr inbounds nuw i8, ptr %base, i64 %iv
  %elem = load i8, ptr %elem.ptr, align 1
  %is.target = icmp eq i8 %elem, 0
  br i1 %is.target, label %deopt, label %latch

latch:                                            ; preds = %loop
  %iv.next = add nuw nsw i64 %iv, 1
  %loop.cond = icmp ult i64 %iv, %exit
  br i1 %loop.cond, label %loop, label %ret

ret:                                              ; preds = %latch, %entry
  ret void

deopt:                                            ; preds = %loop
  call void @deopt()
  unreachable
}

declare void @deopt()

!0 = !{i32 0, i32 1000}
;.
; CHECK: [[RNG0]] = !{i32 0, i32 1000}
;.
