; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals none --version 6
; RUN: opt < %s -passes=loop-vectorize -S -force-vector-width=4 | FileCheck %s
; RUN: opt < %s -passes=loop-vectorize -S -force-tail-folding-style=data -prefer-predicate-over-epilogue=predicate-dont-vectorize -force-vector-width=4 | FileCheck %s -check-prefix=TF
; RUN: opt < %s -passes=loop-vectorize -S -force-tail-folding-style=data -prefer-predicate-over-epilogue=predicate-dont-vectorize -force-vector-width=4 -force-vector-interleave=2 | FileCheck %s -check-prefix=TF-UNROLL

define void @uniform_load(ptr noalias nocapture %a, ptr noalias nocapture %b, i64 %n) {
; CHECK-LABEL: define void @uniform_load(
; CHECK-SAME: ptr noalias captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x i64> poison, i64 [[TMP0]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x i64> [[BROADCAST_SPLATINSERT]], <4 x i64> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[INDEX]]
; CHECK-NEXT:    store <4 x i64> [[BROADCAST_SPLAT]], ptr [[TMP1]], align 4
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; CHECK-NEXT:    br i1 [[TMP2]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[SCALAR_PH:.*]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 1024, %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[V:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[IV]]
; CHECK-NEXT:    store i64 [[V]], ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[IV_NEXT]], 1025
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_END:.*]], label %[[FOR_BODY]], !llvm.loop [[LOOP3:![0-9]+]]
; CHECK:       [[FOR_END]]:
; CHECK-NEXT:    ret void
;
; TF-LABEL: define void @uniform_load(
; TF-SAME: ptr noalias captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i64 [[N:%.*]]) {
; TF-NEXT:  [[ENTRY:.*:]]
; TF-NEXT:    br label %[[VECTOR_PH:.*]]
; TF:       [[VECTOR_PH]]:
; TF-NEXT:    br label %[[VECTOR_BODY:.*]]
; TF:       [[VECTOR_BODY]]:
; TF-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[FOR_END:.*]] ]
; TF-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i64(i64 [[INDEX]], i64 1025)
; TF-NEXT:    [[TMP1:%.*]] = load i64, ptr [[B]], align 8
; TF-NEXT:    [[TMP2:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 0
; TF-NEXT:    br i1 [[TMP2]], label %[[PRED_STORE_IF:.*]], label %[[PRED_STORE_IF1:.*]]
; TF:       [[PRED_STORE_IF]]:
; TF-NEXT:    [[TMP3:%.*]] = add i64 [[INDEX]], 0
; TF-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP3]]
; TF-NEXT:    store i64 [[TMP1]], ptr [[TMP4]], align 4
; TF-NEXT:    br label %[[PRED_STORE_IF1]]
; TF:       [[PRED_STORE_IF1]]:
; TF-NEXT:    [[TMP11:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 1
; TF-NEXT:    br i1 [[TMP11]], label %[[PRED_STORE_IF2:.*]], label %[[PRED_STORE_CONTINUE2:.*]]
; TF:       [[PRED_STORE_IF2]]:
; TF-NEXT:    [[TMP5:%.*]] = add i64 [[INDEX]], 1
; TF-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP5]]
; TF-NEXT:    store i64 [[TMP1]], ptr [[TMP6]], align 4
; TF-NEXT:    br label %[[PRED_STORE_CONTINUE2]]
; TF:       [[PRED_STORE_CONTINUE2]]:
; TF-NEXT:    [[TMP7:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 2
; TF-NEXT:    br i1 [[TMP7]], label %[[PRED_STORE_IF3:.*]], label %[[PRED_STORE_CONTINUE4:.*]]
; TF:       [[PRED_STORE_IF3]]:
; TF-NEXT:    [[TMP8:%.*]] = add i64 [[INDEX]], 2
; TF-NEXT:    [[TMP9:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP8]]
; TF-NEXT:    store i64 [[TMP1]], ptr [[TMP9]], align 4
; TF-NEXT:    br label %[[PRED_STORE_CONTINUE4]]
; TF:       [[PRED_STORE_CONTINUE4]]:
; TF-NEXT:    [[TMP10:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 3
; TF-NEXT:    br i1 [[TMP10]], label %[[PRED_STORE_IF5:.*]], label %[[FOR_END]]
; TF:       [[PRED_STORE_IF5]]:
; TF-NEXT:    [[TMP12:%.*]] = add i64 [[INDEX]], 3
; TF-NEXT:    [[TMP13:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP12]]
; TF-NEXT:    store i64 [[TMP1]], ptr [[TMP13]], align 4
; TF-NEXT:    br label %[[FOR_END]]
; TF:       [[FOR_END]]:
; TF-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; TF-NEXT:    [[TMP14:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1028
; TF-NEXT:    br i1 [[TMP14]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; TF:       [[MIDDLE_BLOCK]]:
; TF-NEXT:    br label %[[FOR_END1:.*]]
; TF:       [[FOR_END1]]:
; TF-NEXT:    ret void
;
; TF-UNROLL-LABEL: define void @uniform_load(
; TF-UNROLL-SAME: ptr noalias captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i64 [[N:%.*]]) {
; TF-UNROLL-NEXT:  [[ENTRY:.*:]]
; TF-UNROLL-NEXT:    br label %[[VECTOR_PH:.*]]
; TF-UNROLL:       [[VECTOR_PH]]:
; TF-UNROLL-NEXT:    br label %[[VECTOR_BODY:.*]]
; TF-UNROLL:       [[VECTOR_BODY]]:
; TF-UNROLL-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[PRED_STORE_CONTINUE15:.*]] ]
; TF-UNROLL-NEXT:    [[TMP0:%.*]] = add i64 [[INDEX]], 4
; TF-UNROLL-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i64(i64 [[INDEX]], i64 1025)
; TF-UNROLL-NEXT:    [[ACTIVE_LANE_MASK1:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i64(i64 [[TMP0]], i64 1025)
; TF-UNROLL-NEXT:    [[TMP2:%.*]] = load i64, ptr [[B]], align 8
; TF-UNROLL-NEXT:    [[TMP3:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 0
; TF-UNROLL-NEXT:    br i1 [[TMP3]], label %[[PRED_STORE_IF:.*]], label %[[PRED_STORE_IF9:.*]]
; TF-UNROLL:       [[PRED_STORE_IF]]:
; TF-UNROLL-NEXT:    [[TMP16:%.*]] = add i64 [[INDEX]], 0
; TF-UNROLL-NEXT:    [[TMP17:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP16]]
; TF-UNROLL-NEXT:    store i64 [[TMP2]], ptr [[TMP17]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_IF9]]
; TF-UNROLL:       [[PRED_STORE_IF9]]:
; TF-UNROLL-NEXT:    [[TMP5:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 1
; TF-UNROLL-NEXT:    br i1 [[TMP5]], label %[[PRED_STORE_IF2:.*]], label %[[PRED_STORE_CONTINUE10:.*]]
; TF-UNROLL:       [[PRED_STORE_IF2]]:
; TF-UNROLL-NEXT:    [[TMP6:%.*]] = add i64 [[INDEX]], 1
; TF-UNROLL-NEXT:    [[TMP7:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP6]]
; TF-UNROLL-NEXT:    store i64 [[TMP2]], ptr [[TMP7]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE10]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE10]]:
; TF-UNROLL-NEXT:    [[TMP8:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 2
; TF-UNROLL-NEXT:    br i1 [[TMP8]], label %[[PRED_STORE_IF4:.*]], label %[[PRED_STORE_CONTINUE12:.*]]
; TF-UNROLL:       [[PRED_STORE_IF4]]:
; TF-UNROLL-NEXT:    [[TMP9:%.*]] = add i64 [[INDEX]], 2
; TF-UNROLL-NEXT:    [[TMP10:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP9]]
; TF-UNROLL-NEXT:    store i64 [[TMP2]], ptr [[TMP10]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE12]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE12]]:
; TF-UNROLL-NEXT:    [[TMP11:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 3
; TF-UNROLL-NEXT:    br i1 [[TMP11]], label %[[PRED_STORE_IF6:.*]], label %[[FOR_END:.*]]
; TF-UNROLL:       [[PRED_STORE_IF6]]:
; TF-UNROLL-NEXT:    [[TMP25:%.*]] = add i64 [[INDEX]], 3
; TF-UNROLL-NEXT:    [[TMP26:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP25]]
; TF-UNROLL-NEXT:    store i64 [[TMP2]], ptr [[TMP26]], align 4
; TF-UNROLL-NEXT:    br label %[[FOR_END]]
; TF-UNROLL:       [[FOR_END]]:
; TF-UNROLL-NEXT:    [[TMP14:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 0
; TF-UNROLL-NEXT:    br i1 [[TMP14]], label %[[PRED_STORE_IF8:.*]], label %[[PRED_STORE_CONTINUE9:.*]]
; TF-UNROLL:       [[PRED_STORE_IF8]]:
; TF-UNROLL-NEXT:    [[TMP15:%.*]] = add i64 [[INDEX]], 4
; TF-UNROLL-NEXT:    [[TMP27:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP15]]
; TF-UNROLL-NEXT:    store i64 [[TMP2]], ptr [[TMP27]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE9]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE9]]:
; TF-UNROLL-NEXT:    [[TMP28:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 1
; TF-UNROLL-NEXT:    br i1 [[TMP28]], label %[[PRED_STORE_IF10:.*]], label %[[PRED_STORE_CONTINUE11:.*]]
; TF-UNROLL:       [[PRED_STORE_IF10]]:
; TF-UNROLL-NEXT:    [[TMP18:%.*]] = add i64 [[INDEX]], 5
; TF-UNROLL-NEXT:    [[TMP19:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP18]]
; TF-UNROLL-NEXT:    store i64 [[TMP2]], ptr [[TMP19]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE11]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE11]]:
; TF-UNROLL-NEXT:    [[TMP20:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 2
; TF-UNROLL-NEXT:    br i1 [[TMP20]], label %[[PRED_STORE_IF12:.*]], label %[[PRED_STORE_CONTINUE13:.*]]
; TF-UNROLL:       [[PRED_STORE_IF12]]:
; TF-UNROLL-NEXT:    [[TMP21:%.*]] = add i64 [[INDEX]], 6
; TF-UNROLL-NEXT:    [[TMP22:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP21]]
; TF-UNROLL-NEXT:    store i64 [[TMP2]], ptr [[TMP22]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE13]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE13]]:
; TF-UNROLL-NEXT:    [[TMP23:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 3
; TF-UNROLL-NEXT:    br i1 [[TMP23]], label %[[PRED_STORE_IF14:.*]], label %[[PRED_STORE_CONTINUE15]]
; TF-UNROLL:       [[PRED_STORE_IF14]]:
; TF-UNROLL-NEXT:    [[TMP24:%.*]] = add i64 [[INDEX]], 7
; TF-UNROLL-NEXT:    [[TMP29:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP24]]
; TF-UNROLL-NEXT:    store i64 [[TMP2]], ptr [[TMP29]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE15]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE15]]:
; TF-UNROLL-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 8
; TF-UNROLL-NEXT:    [[TMP30:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1032
; TF-UNROLL-NEXT:    br i1 [[TMP30]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP0:![0-9]+]]
; TF-UNROLL:       [[MIDDLE_BLOCK]]:
; TF-UNROLL-NEXT:    br label %[[FOR_END1:.*]]
; TF-UNROLL:       [[FOR_END1]]:
; TF-UNROLL-NEXT:    ret void
;
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  %v = load i64, ptr %b, align 8
  %arrayidx = getelementptr inbounds i64, ptr %a, i64 %iv
  store i64 %v, ptr %arrayidx
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, 1025
  br i1 %exitcond.not, label %for.end, label %for.body

for.end:
  ret void
}

define i64 @uniform_load_outside_use(ptr noalias nocapture %a, ptr noalias nocapture %b, i64 %n) {
; CHECK-LABEL: define i64 @uniform_load_outside_use(
; CHECK-SAME: ptr noalias captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x i64> poison, i64 [[TMP0]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x i64> [[BROADCAST_SPLATINSERT]], <4 x i64> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[INDEX]]
; CHECK-NEXT:    store <4 x i64> [[BROADCAST_SPLAT]], ptr [[TMP1]], align 4
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; CHECK-NEXT:    br i1 [[TMP2]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[SCALAR_PH:.*]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 1024, %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[V:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[IV]]
; CHECK-NEXT:    store i64 [[V]], ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[IV_NEXT]], 1025
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_END:.*]], label %[[FOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
; CHECK:       [[FOR_END]]:
; CHECK-NEXT:    [[V_LCSSA:%.*]] = phi i64 [ [[V]], %[[FOR_BODY]] ]
; CHECK-NEXT:    ret i64 [[V_LCSSA]]
;
; TF-LABEL: define i64 @uniform_load_outside_use(
; TF-SAME: ptr noalias captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i64 [[N:%.*]]) {
; TF-NEXT:  [[ENTRY:.*:]]
; TF-NEXT:    br label %[[VECTOR_PH:.*]]
; TF:       [[VECTOR_PH]]:
; TF-NEXT:    br label %[[VECTOR_BODY:.*]]
; TF:       [[VECTOR_BODY]]:
; TF-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[FOR_END:.*]] ]
; TF-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i64(i64 [[INDEX]], i64 1025)
; TF-NEXT:    [[TMP1:%.*]] = load i64, ptr [[B]], align 8
; TF-NEXT:    [[TMP2:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 0
; TF-NEXT:    br i1 [[TMP2]], label %[[PRED_STORE_IF:.*]], label %[[PRED_STORE_IF1:.*]]
; TF:       [[PRED_STORE_IF]]:
; TF-NEXT:    [[TMP3:%.*]] = add i64 [[INDEX]], 0
; TF-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP3]]
; TF-NEXT:    store i64 [[TMP1]], ptr [[TMP4]], align 4
; TF-NEXT:    br label %[[PRED_STORE_IF1]]
; TF:       [[PRED_STORE_IF1]]:
; TF-NEXT:    [[TMP11:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 1
; TF-NEXT:    br i1 [[TMP11]], label %[[PRED_STORE_IF2:.*]], label %[[PRED_STORE_CONTINUE2:.*]]
; TF:       [[PRED_STORE_IF2]]:
; TF-NEXT:    [[TMP5:%.*]] = add i64 [[INDEX]], 1
; TF-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP5]]
; TF-NEXT:    store i64 [[TMP1]], ptr [[TMP6]], align 4
; TF-NEXT:    br label %[[PRED_STORE_CONTINUE2]]
; TF:       [[PRED_STORE_CONTINUE2]]:
; TF-NEXT:    [[TMP7:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 2
; TF-NEXT:    br i1 [[TMP7]], label %[[PRED_STORE_IF3:.*]], label %[[PRED_STORE_CONTINUE4:.*]]
; TF:       [[PRED_STORE_IF3]]:
; TF-NEXT:    [[TMP8:%.*]] = add i64 [[INDEX]], 2
; TF-NEXT:    [[TMP9:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP8]]
; TF-NEXT:    store i64 [[TMP1]], ptr [[TMP9]], align 4
; TF-NEXT:    br label %[[PRED_STORE_CONTINUE4]]
; TF:       [[PRED_STORE_CONTINUE4]]:
; TF-NEXT:    [[TMP10:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 3
; TF-NEXT:    br i1 [[TMP10]], label %[[PRED_STORE_IF5:.*]], label %[[FOR_END]]
; TF:       [[PRED_STORE_IF5]]:
; TF-NEXT:    [[TMP12:%.*]] = add i64 [[INDEX]], 3
; TF-NEXT:    [[TMP13:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP12]]
; TF-NEXT:    store i64 [[TMP1]], ptr [[TMP13]], align 4
; TF-NEXT:    br label %[[FOR_END]]
; TF:       [[FOR_END]]:
; TF-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; TF-NEXT:    [[TMP14:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1028
; TF-NEXT:    br i1 [[TMP14]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP3:![0-9]+]]
; TF:       [[MIDDLE_BLOCK]]:
; TF-NEXT:    br label %[[FOR_END1:.*]]
; TF:       [[FOR_END1]]:
; TF-NEXT:    ret i64 [[TMP1]]
;
; TF-UNROLL-LABEL: define i64 @uniform_load_outside_use(
; TF-UNROLL-SAME: ptr noalias captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i64 [[N:%.*]]) {
; TF-UNROLL-NEXT:  [[ENTRY:.*:]]
; TF-UNROLL-NEXT:    br label %[[VECTOR_PH:.*]]
; TF-UNROLL:       [[VECTOR_PH]]:
; TF-UNROLL-NEXT:    br label %[[VECTOR_BODY:.*]]
; TF-UNROLL:       [[VECTOR_BODY]]:
; TF-UNROLL-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[PRED_STORE_CONTINUE15:.*]] ]
; TF-UNROLL-NEXT:    [[TMP0:%.*]] = add i64 [[INDEX]], 4
; TF-UNROLL-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i64(i64 [[INDEX]], i64 1025)
; TF-UNROLL-NEXT:    [[ACTIVE_LANE_MASK1:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i64(i64 [[TMP0]], i64 1025)
; TF-UNROLL-NEXT:    [[TMP2:%.*]] = load i64, ptr [[B]], align 8
; TF-UNROLL-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x i64> poison, i64 [[TMP2]], i64 0
; TF-UNROLL-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x i64> [[BROADCAST_SPLATINSERT]], <4 x i64> poison, <4 x i32> zeroinitializer
; TF-UNROLL-NEXT:    [[TMP3:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 0
; TF-UNROLL-NEXT:    br i1 [[TMP3]], label %[[PRED_STORE_IF:.*]], label %[[PRED_STORE_IF9:.*]]
; TF-UNROLL:       [[PRED_STORE_IF]]:
; TF-UNROLL-NEXT:    [[TMP16:%.*]] = add i64 [[INDEX]], 0
; TF-UNROLL-NEXT:    [[TMP17:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP16]]
; TF-UNROLL-NEXT:    store i64 [[TMP2]], ptr [[TMP17]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_IF9]]
; TF-UNROLL:       [[PRED_STORE_IF9]]:
; TF-UNROLL-NEXT:    [[TMP5:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 1
; TF-UNROLL-NEXT:    br i1 [[TMP5]], label %[[PRED_STORE_IF2:.*]], label %[[PRED_STORE_CONTINUE10:.*]]
; TF-UNROLL:       [[PRED_STORE_IF2]]:
; TF-UNROLL-NEXT:    [[TMP6:%.*]] = add i64 [[INDEX]], 1
; TF-UNROLL-NEXT:    [[TMP7:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP6]]
; TF-UNROLL-NEXT:    store i64 [[TMP2]], ptr [[TMP7]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE10]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE10]]:
; TF-UNROLL-NEXT:    [[TMP8:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 2
; TF-UNROLL-NEXT:    br i1 [[TMP8]], label %[[PRED_STORE_IF4:.*]], label %[[PRED_STORE_CONTINUE12:.*]]
; TF-UNROLL:       [[PRED_STORE_IF4]]:
; TF-UNROLL-NEXT:    [[TMP9:%.*]] = add i64 [[INDEX]], 2
; TF-UNROLL-NEXT:    [[TMP10:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP9]]
; TF-UNROLL-NEXT:    store i64 [[TMP2]], ptr [[TMP10]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE12]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE12]]:
; TF-UNROLL-NEXT:    [[TMP11:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 3
; TF-UNROLL-NEXT:    br i1 [[TMP11]], label %[[PRED_STORE_IF6:.*]], label %[[FOR_END:.*]]
; TF-UNROLL:       [[PRED_STORE_IF6]]:
; TF-UNROLL-NEXT:    [[TMP25:%.*]] = add i64 [[INDEX]], 3
; TF-UNROLL-NEXT:    [[TMP26:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP25]]
; TF-UNROLL-NEXT:    store i64 [[TMP2]], ptr [[TMP26]], align 4
; TF-UNROLL-NEXT:    br label %[[FOR_END]]
; TF-UNROLL:       [[FOR_END]]:
; TF-UNROLL-NEXT:    [[TMP14:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 0
; TF-UNROLL-NEXT:    br i1 [[TMP14]], label %[[PRED_STORE_IF8:.*]], label %[[PRED_STORE_CONTINUE9:.*]]
; TF-UNROLL:       [[PRED_STORE_IF8]]:
; TF-UNROLL-NEXT:    [[TMP15:%.*]] = add i64 [[INDEX]], 4
; TF-UNROLL-NEXT:    [[TMP37:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP15]]
; TF-UNROLL-NEXT:    store i64 [[TMP2]], ptr [[TMP37]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE9]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE9]]:
; TF-UNROLL-NEXT:    [[TMP39:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 1
; TF-UNROLL-NEXT:    br i1 [[TMP39]], label %[[PRED_STORE_IF10:.*]], label %[[PRED_STORE_CONTINUE11:.*]]
; TF-UNROLL:       [[PRED_STORE_IF10]]:
; TF-UNROLL-NEXT:    [[TMP18:%.*]] = add i64 [[INDEX]], 5
; TF-UNROLL-NEXT:    [[TMP19:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP18]]
; TF-UNROLL-NEXT:    store i64 [[TMP2]], ptr [[TMP19]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE11]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE11]]:
; TF-UNROLL-NEXT:    [[TMP20:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 2
; TF-UNROLL-NEXT:    br i1 [[TMP20]], label %[[PRED_STORE_IF12:.*]], label %[[PRED_STORE_CONTINUE13:.*]]
; TF-UNROLL:       [[PRED_STORE_IF12]]:
; TF-UNROLL-NEXT:    [[TMP21:%.*]] = add i64 [[INDEX]], 6
; TF-UNROLL-NEXT:    [[TMP22:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP21]]
; TF-UNROLL-NEXT:    store i64 [[TMP2]], ptr [[TMP22]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE13]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE13]]:
; TF-UNROLL-NEXT:    [[TMP23:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 3
; TF-UNROLL-NEXT:    br i1 [[TMP23]], label %[[PRED_STORE_IF14:.*]], label %[[PRED_STORE_CONTINUE15]]
; TF-UNROLL:       [[PRED_STORE_IF14]]:
; TF-UNROLL-NEXT:    [[TMP24:%.*]] = add i64 [[INDEX]], 7
; TF-UNROLL-NEXT:    [[TMP40:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP24]]
; TF-UNROLL-NEXT:    store i64 [[TMP2]], ptr [[TMP40]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE15]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE15]]:
; TF-UNROLL-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 8
; TF-UNROLL-NEXT:    [[TMP41:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1032
; TF-UNROLL-NEXT:    br i1 [[TMP41]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP3:![0-9]+]]
; TF-UNROLL:       [[MIDDLE_BLOCK]]:
; TF-UNROLL-NEXT:    [[TMP27:%.*]] = xor <4 x i1> [[ACTIVE_LANE_MASK]], splat (i1 true)
; TF-UNROLL-NEXT:    [[TMP28:%.*]] = xor <4 x i1> [[ACTIVE_LANE_MASK1]], splat (i1 true)
; TF-UNROLL-NEXT:    [[FIRST_INACTIVE_LANE:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.v4i1(<4 x i1> [[TMP28]], i1 false)
; TF-UNROLL-NEXT:    [[TMP29:%.*]] = add i64 4, [[FIRST_INACTIVE_LANE]]
; TF-UNROLL-NEXT:    [[FIRST_INACTIVE_LANE16:%.*]] = call i64 @llvm.experimental.cttz.elts.i64.v4i1(<4 x i1> [[TMP27]], i1 false)
; TF-UNROLL-NEXT:    [[TMP30:%.*]] = add i64 0, [[FIRST_INACTIVE_LANE16]]
; TF-UNROLL-NEXT:    [[TMP31:%.*]] = icmp ne i64 [[FIRST_INACTIVE_LANE16]], 4
; TF-UNROLL-NEXT:    [[TMP32:%.*]] = select i1 [[TMP31]], i64 [[TMP30]], i64 [[TMP29]]
; TF-UNROLL-NEXT:    [[LAST_ACTIVE_LANE:%.*]] = sub i64 [[TMP32]], 1
; TF-UNROLL-NEXT:    [[TMP33:%.*]] = extractelement <4 x i64> [[BROADCAST_SPLAT]], i64 [[LAST_ACTIVE_LANE]]
; TF-UNROLL-NEXT:    [[TMP34:%.*]] = sub i64 [[LAST_ACTIVE_LANE]], 4
; TF-UNROLL-NEXT:    [[TMP35:%.*]] = extractelement <4 x i64> [[BROADCAST_SPLAT]], i64 [[TMP34]]
; TF-UNROLL-NEXT:    [[TMP36:%.*]] = icmp uge i64 [[LAST_ACTIVE_LANE]], 4
; TF-UNROLL-NEXT:    [[TMP38:%.*]] = select i1 [[TMP36]], i64 [[TMP35]], i64 [[TMP33]]
; TF-UNROLL-NEXT:    br label %[[FOR_END1:.*]]
; TF-UNROLL:       [[FOR_END1]]:
; TF-UNROLL-NEXT:    ret i64 [[TMP38]]
;
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  %v = load i64, ptr %b, align 8
  %arrayidx = getelementptr inbounds i64, ptr %a, i64 %iv
  store i64 %v, ptr %arrayidx
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, 1025
  br i1 %exitcond.not, label %for.end, label %for.body

for.end:
  ret i64 %v
}


define void @conditional_uniform_load(ptr noalias nocapture %a, ptr noalias nocapture %b, i64 %n) {
; CHECK-LABEL: define void @conditional_uniform_load(
; CHECK-SAME: ptr noalias captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[PRED_LOAD_CONTINUE6:.*]] ]
; CHECK-NEXT:    [[VEC_IND:%.*]] = phi <4 x i64> [ <i64 0, i64 1, i64 2, i64 3>, %[[VECTOR_PH]] ], [ [[VEC_IND_NEXT:%.*]], %[[PRED_LOAD_CONTINUE6]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ugt <4 x i64> [[VEC_IND]], splat (i64 10)
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <4 x i1> [[TMP0]], i32 0
; CHECK-NEXT:    br i1 [[TMP1]], label %[[PRED_LOAD_IF:.*]], label %[[PRED_LOAD_CONTINUE:.*]]
; CHECK:       [[PRED_LOAD_IF]]:
; CHECK-NEXT:    [[TMP2:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    [[TMP3:%.*]] = insertelement <4 x i64> poison, i64 [[TMP2]], i32 0
; CHECK-NEXT:    br label %[[PRED_LOAD_CONTINUE]]
; CHECK:       [[PRED_LOAD_CONTINUE]]:
; CHECK-NEXT:    [[TMP4:%.*]] = phi <4 x i64> [ poison, %[[VECTOR_BODY]] ], [ [[TMP3]], %[[PRED_LOAD_IF]] ]
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <4 x i1> [[TMP0]], i32 1
; CHECK-NEXT:    br i1 [[TMP5]], label %[[PRED_LOAD_IF1:.*]], label %[[PRED_LOAD_CONTINUE2:.*]]
; CHECK:       [[PRED_LOAD_IF1]]:
; CHECK-NEXT:    [[TMP6:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    [[TMP7:%.*]] = insertelement <4 x i64> [[TMP4]], i64 [[TMP6]], i32 1
; CHECK-NEXT:    br label %[[PRED_LOAD_CONTINUE2]]
; CHECK:       [[PRED_LOAD_CONTINUE2]]:
; CHECK-NEXT:    [[TMP8:%.*]] = phi <4 x i64> [ [[TMP4]], %[[PRED_LOAD_CONTINUE]] ], [ [[TMP7]], %[[PRED_LOAD_IF1]] ]
; CHECK-NEXT:    [[TMP9:%.*]] = extractelement <4 x i1> [[TMP0]], i32 2
; CHECK-NEXT:    br i1 [[TMP9]], label %[[PRED_LOAD_IF3:.*]], label %[[PRED_LOAD_CONTINUE4:.*]]
; CHECK:       [[PRED_LOAD_IF3]]:
; CHECK-NEXT:    [[TMP10:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    [[TMP11:%.*]] = insertelement <4 x i64> [[TMP8]], i64 [[TMP10]], i32 2
; CHECK-NEXT:    br label %[[PRED_LOAD_CONTINUE4]]
; CHECK:       [[PRED_LOAD_CONTINUE4]]:
; CHECK-NEXT:    [[TMP12:%.*]] = phi <4 x i64> [ [[TMP8]], %[[PRED_LOAD_CONTINUE2]] ], [ [[TMP11]], %[[PRED_LOAD_IF3]] ]
; CHECK-NEXT:    [[TMP13:%.*]] = extractelement <4 x i1> [[TMP0]], i32 3
; CHECK-NEXT:    br i1 [[TMP13]], label %[[PRED_LOAD_IF5:.*]], label %[[PRED_LOAD_CONTINUE6]]
; CHECK:       [[PRED_LOAD_IF5]]:
; CHECK-NEXT:    [[TMP14:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    [[TMP15:%.*]] = insertelement <4 x i64> [[TMP12]], i64 [[TMP14]], i32 3
; CHECK-NEXT:    br label %[[PRED_LOAD_CONTINUE6]]
; CHECK:       [[PRED_LOAD_CONTINUE6]]:
; CHECK-NEXT:    [[TMP16:%.*]] = phi <4 x i64> [ [[TMP12]], %[[PRED_LOAD_CONTINUE4]] ], [ [[TMP15]], %[[PRED_LOAD_IF5]] ]
; CHECK-NEXT:    [[PREDPHI:%.*]] = select <4 x i1> [[TMP0]], <4 x i64> [[TMP16]], <4 x i64> zeroinitializer
; CHECK-NEXT:    [[TMP17:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[INDEX]]
; CHECK-NEXT:    store <4 x i64> [[PREDPHI]], ptr [[TMP17]], align 4
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; CHECK-NEXT:    [[VEC_IND_NEXT]] = add nuw nsw <4 x i64> [[VEC_IND]], splat (i64 4)
; CHECK-NEXT:    [[TMP18:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; CHECK-NEXT:    br i1 [[TMP18]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP6:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[SCALAR_PH:.*]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 1024, %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[CMP:%.*]] = icmp ugt i64 [[IV]], 10
; CHECK-NEXT:    br i1 [[CMP]], label %[[DO_LOAD:.*]], label %[[LATCH]]
; CHECK:       [[DO_LOAD]]:
; CHECK-NEXT:    [[V:%.*]] = load i64, ptr [[B]], align 8
; CHECK-NEXT:    br label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[PHI:%.*]] = phi i64 [ 0, %[[FOR_BODY]] ], [ [[V]], %[[DO_LOAD]] ]
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[IV]]
; CHECK-NEXT:    store i64 [[PHI]], ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[IV_NEXT]], 1025
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_END:.*]], label %[[FOR_BODY]], !llvm.loop [[LOOP7:![0-9]+]]
; CHECK:       [[FOR_END]]:
; CHECK-NEXT:    ret void
;
; TF-LABEL: define void @conditional_uniform_load(
; TF-SAME: ptr noalias captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i64 [[N:%.*]]) {
; TF-NEXT:  [[ENTRY:.*:]]
; TF-NEXT:    br label %[[VECTOR_PH:.*]]
; TF:       [[VECTOR_PH]]:
; TF-NEXT:    br label %[[VECTOR_BODY:.*]]
; TF:       [[VECTOR_BODY]]:
; TF-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[FOR_END:.*]] ]
; TF-NEXT:    [[VEC_IND:%.*]] = phi <4 x i64> [ <i64 0, i64 1, i64 2, i64 3>, %[[VECTOR_PH]] ], [ [[VEC_IND_NEXT:%.*]], %[[FOR_END]] ]
; TF-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i64(i64 [[INDEX]], i64 1025)
; TF-NEXT:    [[TMP1:%.*]] = icmp ugt <4 x i64> [[VEC_IND]], splat (i64 10)
; TF-NEXT:    [[TMP2:%.*]] = select <4 x i1> [[ACTIVE_LANE_MASK]], <4 x i1> [[TMP1]], <4 x i1> zeroinitializer
; TF-NEXT:    [[TMP3:%.*]] = extractelement <4 x i1> [[TMP2]], i32 0
; TF-NEXT:    br i1 [[TMP3]], label %[[PRED_LOAD_IF:.*]], label %[[PRED_LOAD_CONTINUE:.*]]
; TF:       [[PRED_LOAD_IF]]:
; TF-NEXT:    [[TMP4:%.*]] = load i64, ptr [[B]], align 8
; TF-NEXT:    [[TMP5:%.*]] = insertelement <4 x i64> poison, i64 [[TMP4]], i32 0
; TF-NEXT:    br label %[[PRED_LOAD_CONTINUE]]
; TF:       [[PRED_LOAD_CONTINUE]]:
; TF-NEXT:    [[TMP6:%.*]] = phi <4 x i64> [ poison, %[[VECTOR_BODY]] ], [ [[TMP5]], %[[PRED_LOAD_IF]] ]
; TF-NEXT:    [[TMP7:%.*]] = extractelement <4 x i1> [[TMP2]], i32 1
; TF-NEXT:    br i1 [[TMP7]], label %[[PRED_LOAD_IF1:.*]], label %[[PRED_LOAD_CONTINUE2:.*]]
; TF:       [[PRED_LOAD_IF1]]:
; TF-NEXT:    [[TMP8:%.*]] = load i64, ptr [[B]], align 8
; TF-NEXT:    [[TMP9:%.*]] = insertelement <4 x i64> [[TMP6]], i64 [[TMP8]], i32 1
; TF-NEXT:    br label %[[PRED_LOAD_CONTINUE2]]
; TF:       [[PRED_LOAD_CONTINUE2]]:
; TF-NEXT:    [[TMP10:%.*]] = phi <4 x i64> [ [[TMP6]], %[[PRED_LOAD_CONTINUE]] ], [ [[TMP9]], %[[PRED_LOAD_IF1]] ]
; TF-NEXT:    [[TMP11:%.*]] = extractelement <4 x i1> [[TMP2]], i32 2
; TF-NEXT:    br i1 [[TMP11]], label %[[PRED_LOAD_IF3:.*]], label %[[PRED_LOAD_CONTINUE4:.*]]
; TF:       [[PRED_LOAD_IF3]]:
; TF-NEXT:    [[TMP12:%.*]] = load i64, ptr [[B]], align 8
; TF-NEXT:    [[TMP13:%.*]] = insertelement <4 x i64> [[TMP10]], i64 [[TMP12]], i32 2
; TF-NEXT:    br label %[[PRED_LOAD_CONTINUE4]]
; TF:       [[PRED_LOAD_CONTINUE4]]:
; TF-NEXT:    [[TMP14:%.*]] = phi <4 x i64> [ [[TMP10]], %[[PRED_LOAD_CONTINUE2]] ], [ [[TMP13]], %[[PRED_LOAD_IF3]] ]
; TF-NEXT:    [[TMP15:%.*]] = extractelement <4 x i1> [[TMP2]], i32 3
; TF-NEXT:    br i1 [[TMP15]], label %[[PRED_LOAD_IF5:.*]], label %[[PRED_LOAD_CONTINUE6:.*]]
; TF:       [[PRED_LOAD_IF5]]:
; TF-NEXT:    [[TMP16:%.*]] = load i64, ptr [[B]], align 8
; TF-NEXT:    [[TMP17:%.*]] = insertelement <4 x i64> [[TMP14]], i64 [[TMP16]], i32 3
; TF-NEXT:    br label %[[PRED_LOAD_CONTINUE6]]
; TF:       [[PRED_LOAD_CONTINUE6]]:
; TF-NEXT:    [[TMP18:%.*]] = phi <4 x i64> [ [[TMP14]], %[[PRED_LOAD_CONTINUE4]] ], [ [[TMP17]], %[[PRED_LOAD_IF5]] ]
; TF-NEXT:    [[PREDPHI:%.*]] = select <4 x i1> [[TMP1]], <4 x i64> [[TMP18]], <4 x i64> zeroinitializer
; TF-NEXT:    [[TMP19:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 0
; TF-NEXT:    br i1 [[TMP19]], label %[[PRED_STORE_IF:.*]], label %[[PRED_STORE_CONTINUE:.*]]
; TF:       [[PRED_STORE_IF]]:
; TF-NEXT:    [[TMP20:%.*]] = add i64 [[INDEX]], 0
; TF-NEXT:    [[TMP21:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP20]]
; TF-NEXT:    [[TMP26:%.*]] = extractelement <4 x i64> [[PREDPHI]], i32 0
; TF-NEXT:    store i64 [[TMP26]], ptr [[TMP21]], align 4
; TF-NEXT:    br label %[[PRED_STORE_CONTINUE]]
; TF:       [[PRED_STORE_CONTINUE]]:
; TF-NEXT:    [[TMP22:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 1
; TF-NEXT:    br i1 [[TMP22]], label %[[PRED_STORE_IF7:.*]], label %[[PRED_STORE_CONTINUE8:.*]]
; TF:       [[PRED_STORE_IF7]]:
; TF-NEXT:    [[TMP23:%.*]] = add i64 [[INDEX]], 1
; TF-NEXT:    [[TMP24:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP23]]
; TF-NEXT:    [[TMP25:%.*]] = extractelement <4 x i64> [[PREDPHI]], i32 1
; TF-NEXT:    store i64 [[TMP25]], ptr [[TMP24]], align 4
; TF-NEXT:    br label %[[PRED_STORE_CONTINUE8]]
; TF:       [[PRED_STORE_CONTINUE8]]:
; TF-NEXT:    [[TMP27:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 2
; TF-NEXT:    br i1 [[TMP27]], label %[[PRED_STORE_IF9:.*]], label %[[PRED_STORE_CONTINUE10:.*]]
; TF:       [[PRED_STORE_IF9]]:
; TF-NEXT:    [[TMP31:%.*]] = add i64 [[INDEX]], 2
; TF-NEXT:    [[TMP28:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP31]]
; TF-NEXT:    [[TMP29:%.*]] = extractelement <4 x i64> [[PREDPHI]], i32 2
; TF-NEXT:    store i64 [[TMP29]], ptr [[TMP28]], align 4
; TF-NEXT:    br label %[[PRED_STORE_CONTINUE10]]
; TF:       [[PRED_STORE_CONTINUE10]]:
; TF-NEXT:    [[TMP30:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 3
; TF-NEXT:    br i1 [[TMP30]], label %[[PRED_STORE_IF11:.*]], label %[[FOR_END]]
; TF:       [[PRED_STORE_IF11]]:
; TF-NEXT:    [[TMP32:%.*]] = add i64 [[INDEX]], 3
; TF-NEXT:    [[TMP33:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP32]]
; TF-NEXT:    [[TMP34:%.*]] = extractelement <4 x i64> [[PREDPHI]], i32 3
; TF-NEXT:    store i64 [[TMP34]], ptr [[TMP33]], align 4
; TF-NEXT:    br label %[[FOR_END]]
; TF:       [[FOR_END]]:
; TF-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; TF-NEXT:    [[VEC_IND_NEXT]] = add <4 x i64> [[VEC_IND]], splat (i64 4)
; TF-NEXT:    [[TMP35:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1028
; TF-NEXT:    br i1 [[TMP35]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; TF:       [[MIDDLE_BLOCK]]:
; TF-NEXT:    br label %[[FOR_END1:.*]]
; TF:       [[FOR_END1]]:
; TF-NEXT:    ret void
;
; TF-UNROLL-LABEL: define void @conditional_uniform_load(
; TF-UNROLL-SAME: ptr noalias captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i64 [[N:%.*]]) {
; TF-UNROLL-NEXT:  [[ENTRY:.*:]]
; TF-UNROLL-NEXT:    br label %[[VECTOR_PH:.*]]
; TF-UNROLL:       [[VECTOR_PH]]:
; TF-UNROLL-NEXT:    br label %[[VECTOR_BODY:.*]]
; TF-UNROLL:       [[VECTOR_BODY]]:
; TF-UNROLL-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[PRED_STORE_CONTINUE30:.*]] ]
; TF-UNROLL-NEXT:    [[VEC_IND:%.*]] = phi <4 x i64> [ <i64 0, i64 1, i64 2, i64 3>, %[[VECTOR_PH]] ], [ [[VEC_IND_NEXT:%.*]], %[[PRED_STORE_CONTINUE30]] ]
; TF-UNROLL-NEXT:    [[STEP_ADD:%.*]] = add <4 x i64> [[VEC_IND]], splat (i64 4)
; TF-UNROLL-NEXT:    [[TMP0:%.*]] = add i64 [[INDEX]], 4
; TF-UNROLL-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i64(i64 [[INDEX]], i64 1025)
; TF-UNROLL-NEXT:    [[ACTIVE_LANE_MASK1:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i64(i64 [[TMP0]], i64 1025)
; TF-UNROLL-NEXT:    [[TMP2:%.*]] = icmp ugt <4 x i64> [[VEC_IND]], splat (i64 10)
; TF-UNROLL-NEXT:    [[TMP3:%.*]] = icmp ugt <4 x i64> [[STEP_ADD]], splat (i64 10)
; TF-UNROLL-NEXT:    [[TMP5:%.*]] = select <4 x i1> [[ACTIVE_LANE_MASK]], <4 x i1> [[TMP2]], <4 x i1> zeroinitializer
; TF-UNROLL-NEXT:    [[TMP4:%.*]] = select <4 x i1> [[ACTIVE_LANE_MASK1]], <4 x i1> [[TMP3]], <4 x i1> zeroinitializer
; TF-UNROLL-NEXT:    [[TMP6:%.*]] = extractelement <4 x i1> [[TMP5]], i32 0
; TF-UNROLL-NEXT:    br i1 [[TMP6]], label %[[PRED_LOAD_IF:.*]], label %[[PRED_LOAD_CONTINUE:.*]]
; TF-UNROLL:       [[PRED_LOAD_IF]]:
; TF-UNROLL-NEXT:    [[TMP7:%.*]] = load i64, ptr [[B]], align 8
; TF-UNROLL-NEXT:    [[TMP8:%.*]] = insertelement <4 x i64> poison, i64 [[TMP7]], i32 0
; TF-UNROLL-NEXT:    br label %[[PRED_LOAD_CONTINUE]]
; TF-UNROLL:       [[PRED_LOAD_CONTINUE]]:
; TF-UNROLL-NEXT:    [[TMP9:%.*]] = phi <4 x i64> [ poison, %[[VECTOR_BODY]] ], [ [[TMP8]], %[[PRED_LOAD_IF]] ]
; TF-UNROLL-NEXT:    [[TMP10:%.*]] = extractelement <4 x i1> [[TMP5]], i32 1
; TF-UNROLL-NEXT:    br i1 [[TMP10]], label %[[PRED_LOAD_IF1:.*]], label %[[PRED_LOAD_CONTINUE2:.*]]
; TF-UNROLL:       [[PRED_LOAD_IF1]]:
; TF-UNROLL-NEXT:    [[TMP11:%.*]] = load i64, ptr [[B]], align 8
; TF-UNROLL-NEXT:    [[TMP12:%.*]] = insertelement <4 x i64> [[TMP9]], i64 [[TMP11]], i32 1
; TF-UNROLL-NEXT:    br label %[[PRED_LOAD_CONTINUE2]]
; TF-UNROLL:       [[PRED_LOAD_CONTINUE2]]:
; TF-UNROLL-NEXT:    [[TMP13:%.*]] = phi <4 x i64> [ [[TMP9]], %[[PRED_LOAD_CONTINUE]] ], [ [[TMP12]], %[[PRED_LOAD_IF1]] ]
; TF-UNROLL-NEXT:    [[TMP14:%.*]] = extractelement <4 x i1> [[TMP5]], i32 2
; TF-UNROLL-NEXT:    br i1 [[TMP14]], label %[[PRED_LOAD_IF3:.*]], label %[[PRED_LOAD_CONTINUE4:.*]]
; TF-UNROLL:       [[PRED_LOAD_IF3]]:
; TF-UNROLL-NEXT:    [[TMP15:%.*]] = load i64, ptr [[B]], align 8
; TF-UNROLL-NEXT:    [[TMP16:%.*]] = insertelement <4 x i64> [[TMP13]], i64 [[TMP15]], i32 2
; TF-UNROLL-NEXT:    br label %[[PRED_LOAD_CONTINUE4]]
; TF-UNROLL:       [[PRED_LOAD_CONTINUE4]]:
; TF-UNROLL-NEXT:    [[TMP17:%.*]] = phi <4 x i64> [ [[TMP13]], %[[PRED_LOAD_CONTINUE2]] ], [ [[TMP16]], %[[PRED_LOAD_IF3]] ]
; TF-UNROLL-NEXT:    [[TMP18:%.*]] = extractelement <4 x i1> [[TMP5]], i32 3
; TF-UNROLL-NEXT:    br i1 [[TMP18]], label %[[PRED_LOAD_IF5:.*]], label %[[PRED_LOAD_CONTINUE6:.*]]
; TF-UNROLL:       [[PRED_LOAD_IF5]]:
; TF-UNROLL-NEXT:    [[TMP19:%.*]] = load i64, ptr [[B]], align 8
; TF-UNROLL-NEXT:    [[TMP20:%.*]] = insertelement <4 x i64> [[TMP17]], i64 [[TMP19]], i32 3
; TF-UNROLL-NEXT:    br label %[[PRED_LOAD_CONTINUE6]]
; TF-UNROLL:       [[PRED_LOAD_CONTINUE6]]:
; TF-UNROLL-NEXT:    [[TMP21:%.*]] = phi <4 x i64> [ [[TMP17]], %[[PRED_LOAD_CONTINUE4]] ], [ [[TMP20]], %[[PRED_LOAD_IF5]] ]
; TF-UNROLL-NEXT:    [[TMP22:%.*]] = extractelement <4 x i1> [[TMP4]], i32 0
; TF-UNROLL-NEXT:    br i1 [[TMP22]], label %[[PRED_LOAD_IF7:.*]], label %[[PRED_LOAD_CONTINUE8:.*]]
; TF-UNROLL:       [[PRED_LOAD_IF7]]:
; TF-UNROLL-NEXT:    [[TMP23:%.*]] = load i64, ptr [[B]], align 8
; TF-UNROLL-NEXT:    [[TMP24:%.*]] = insertelement <4 x i64> poison, i64 [[TMP23]], i32 0
; TF-UNROLL-NEXT:    br label %[[PRED_LOAD_CONTINUE8]]
; TF-UNROLL:       [[PRED_LOAD_CONTINUE8]]:
; TF-UNROLL-NEXT:    [[TMP25:%.*]] = phi <4 x i64> [ poison, %[[PRED_LOAD_CONTINUE6]] ], [ [[TMP24]], %[[PRED_LOAD_IF7]] ]
; TF-UNROLL-NEXT:    [[TMP26:%.*]] = extractelement <4 x i1> [[TMP4]], i32 1
; TF-UNROLL-NEXT:    br i1 [[TMP26]], label %[[PRED_LOAD_IF9:.*]], label %[[PRED_LOAD_CONTINUE10:.*]]
; TF-UNROLL:       [[PRED_LOAD_IF9]]:
; TF-UNROLL-NEXT:    [[TMP27:%.*]] = load i64, ptr [[B]], align 8
; TF-UNROLL-NEXT:    [[TMP28:%.*]] = insertelement <4 x i64> [[TMP25]], i64 [[TMP27]], i32 1
; TF-UNROLL-NEXT:    br label %[[PRED_LOAD_CONTINUE10]]
; TF-UNROLL:       [[PRED_LOAD_CONTINUE10]]:
; TF-UNROLL-NEXT:    [[TMP29:%.*]] = phi <4 x i64> [ [[TMP25]], %[[PRED_LOAD_CONTINUE8]] ], [ [[TMP28]], %[[PRED_LOAD_IF9]] ]
; TF-UNROLL-NEXT:    [[TMP30:%.*]] = extractelement <4 x i1> [[TMP4]], i32 2
; TF-UNROLL-NEXT:    br i1 [[TMP30]], label %[[PRED_LOAD_IF11:.*]], label %[[PRED_LOAD_CONTINUE12:.*]]
; TF-UNROLL:       [[PRED_LOAD_IF11]]:
; TF-UNROLL-NEXT:    [[TMP31:%.*]] = load i64, ptr [[B]], align 8
; TF-UNROLL-NEXT:    [[TMP32:%.*]] = insertelement <4 x i64> [[TMP29]], i64 [[TMP31]], i32 2
; TF-UNROLL-NEXT:    br label %[[PRED_LOAD_CONTINUE12]]
; TF-UNROLL:       [[PRED_LOAD_CONTINUE12]]:
; TF-UNROLL-NEXT:    [[TMP33:%.*]] = phi <4 x i64> [ [[TMP29]], %[[PRED_LOAD_CONTINUE10]] ], [ [[TMP32]], %[[PRED_LOAD_IF11]] ]
; TF-UNROLL-NEXT:    [[TMP34:%.*]] = extractelement <4 x i1> [[TMP4]], i32 3
; TF-UNROLL-NEXT:    br i1 [[TMP34]], label %[[PRED_LOAD_IF13:.*]], label %[[PRED_LOAD_CONTINUE14:.*]]
; TF-UNROLL:       [[PRED_LOAD_IF13]]:
; TF-UNROLL-NEXT:    [[TMP35:%.*]] = load i64, ptr [[B]], align 8
; TF-UNROLL-NEXT:    [[TMP36:%.*]] = insertelement <4 x i64> [[TMP33]], i64 [[TMP35]], i32 3
; TF-UNROLL-NEXT:    br label %[[PRED_LOAD_CONTINUE14]]
; TF-UNROLL:       [[PRED_LOAD_CONTINUE14]]:
; TF-UNROLL-NEXT:    [[TMP37:%.*]] = phi <4 x i64> [ [[TMP33]], %[[PRED_LOAD_CONTINUE12]] ], [ [[TMP36]], %[[PRED_LOAD_IF13]] ]
; TF-UNROLL-NEXT:    [[PREDPHI:%.*]] = select <4 x i1> [[TMP2]], <4 x i64> [[TMP21]], <4 x i64> zeroinitializer
; TF-UNROLL-NEXT:    [[PREDPHI15:%.*]] = select <4 x i1> [[TMP3]], <4 x i64> [[TMP37]], <4 x i64> zeroinitializer
; TF-UNROLL-NEXT:    [[TMP38:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 0
; TF-UNROLL-NEXT:    br i1 [[TMP38]], label %[[PRED_STORE_IF:.*]], label %[[PRED_STORE_CONTINUE23:.*]]
; TF-UNROLL:       [[PRED_STORE_IF]]:
; TF-UNROLL-NEXT:    [[TMP55:%.*]] = add i64 [[INDEX]], 0
; TF-UNROLL-NEXT:    [[TMP56:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP55]]
; TF-UNROLL-NEXT:    [[TMP40:%.*]] = extractelement <4 x i64> [[PREDPHI]], i32 0
; TF-UNROLL-NEXT:    store i64 [[TMP40]], ptr [[TMP56]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE23]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE23]]:
; TF-UNROLL-NEXT:    [[TMP41:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 1
; TF-UNROLL-NEXT:    br i1 [[TMP41]], label %[[PRED_STORE_IF17:.*]], label %[[PRED_STORE_CONTINUE25:.*]]
; TF-UNROLL:       [[PRED_STORE_IF17]]:
; TF-UNROLL-NEXT:    [[TMP42:%.*]] = add i64 [[INDEX]], 1
; TF-UNROLL-NEXT:    [[TMP43:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP42]]
; TF-UNROLL-NEXT:    [[TMP44:%.*]] = extractelement <4 x i64> [[PREDPHI]], i32 1
; TF-UNROLL-NEXT:    store i64 [[TMP44]], ptr [[TMP43]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE25]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE25]]:
; TF-UNROLL-NEXT:    [[TMP62:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 2
; TF-UNROLL-NEXT:    br i1 [[TMP62]], label %[[PRED_STORE_IF26:.*]], label %[[PRED_STORE_CONTINUE27:.*]]
; TF-UNROLL:       [[PRED_STORE_IF26]]:
; TF-UNROLL-NEXT:    [[TMP46:%.*]] = add i64 [[INDEX]], 2
; TF-UNROLL-NEXT:    [[TMP47:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP46]]
; TF-UNROLL-NEXT:    [[TMP48:%.*]] = extractelement <4 x i64> [[PREDPHI]], i32 2
; TF-UNROLL-NEXT:    store i64 [[TMP48]], ptr [[TMP47]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE27]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE27]]:
; TF-UNROLL-NEXT:    [[TMP49:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 3
; TF-UNROLL-NEXT:    br i1 [[TMP49]], label %[[PRED_STORE_IF21:.*]], label %[[FOR_END:.*]]
; TF-UNROLL:       [[PRED_STORE_IF21]]:
; TF-UNROLL-NEXT:    [[TMP67:%.*]] = add i64 [[INDEX]], 3
; TF-UNROLL-NEXT:    [[TMP68:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP67]]
; TF-UNROLL-NEXT:    [[TMP69:%.*]] = extractelement <4 x i64> [[PREDPHI]], i32 3
; TF-UNROLL-NEXT:    store i64 [[TMP69]], ptr [[TMP68]], align 4
; TF-UNROLL-NEXT:    br label %[[FOR_END]]
; TF-UNROLL:       [[FOR_END]]:
; TF-UNROLL-NEXT:    [[TMP53:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 0
; TF-UNROLL-NEXT:    br i1 [[TMP53]], label %[[PRED_STORE_IF23:.*]], label %[[PRED_STORE_CONTINUE24:.*]]
; TF-UNROLL:       [[PRED_STORE_IF23]]:
; TF-UNROLL-NEXT:    [[TMP54:%.*]] = add i64 [[INDEX]], 4
; TF-UNROLL-NEXT:    [[TMP70:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP54]]
; TF-UNROLL-NEXT:    [[TMP71:%.*]] = extractelement <4 x i64> [[PREDPHI15]], i32 0
; TF-UNROLL-NEXT:    store i64 [[TMP71]], ptr [[TMP70]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE24]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE24]]:
; TF-UNROLL-NEXT:    [[TMP57:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 1
; TF-UNROLL-NEXT:    br i1 [[TMP57]], label %[[PRED_STORE_IF25:.*]], label %[[PRED_STORE_CONTINUE26:.*]]
; TF-UNROLL:       [[PRED_STORE_IF25]]:
; TF-UNROLL-NEXT:    [[TMP58:%.*]] = add i64 [[INDEX]], 5
; TF-UNROLL-NEXT:    [[TMP59:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP58]]
; TF-UNROLL-NEXT:    [[TMP60:%.*]] = extractelement <4 x i64> [[PREDPHI15]], i32 1
; TF-UNROLL-NEXT:    store i64 [[TMP60]], ptr [[TMP59]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE26]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE26]]:
; TF-UNROLL-NEXT:    [[TMP61:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 2
; TF-UNROLL-NEXT:    br i1 [[TMP61]], label %[[PRED_STORE_IF27:.*]], label %[[PRED_STORE_CONTINUE28:.*]]
; TF-UNROLL:       [[PRED_STORE_IF27]]:
; TF-UNROLL-NEXT:    [[TMP72:%.*]] = add i64 [[INDEX]], 6
; TF-UNROLL-NEXT:    [[TMP63:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP72]]
; TF-UNROLL-NEXT:    [[TMP64:%.*]] = extractelement <4 x i64> [[PREDPHI15]], i32 2
; TF-UNROLL-NEXT:    store i64 [[TMP64]], ptr [[TMP63]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE28]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE28]]:
; TF-UNROLL-NEXT:    [[TMP65:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 3
; TF-UNROLL-NEXT:    br i1 [[TMP65]], label %[[PRED_STORE_IF29:.*]], label %[[PRED_STORE_CONTINUE30]]
; TF-UNROLL:       [[PRED_STORE_IF29]]:
; TF-UNROLL-NEXT:    [[TMP66:%.*]] = add i64 [[INDEX]], 7
; TF-UNROLL-NEXT:    [[TMP73:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP66]]
; TF-UNROLL-NEXT:    [[TMP74:%.*]] = extractelement <4 x i64> [[PREDPHI15]], i32 3
; TF-UNROLL-NEXT:    store i64 [[TMP74]], ptr [[TMP73]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE30]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE30]]:
; TF-UNROLL-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 8
; TF-UNROLL-NEXT:    [[VEC_IND_NEXT]] = add <4 x i64> [[STEP_ADD]], splat (i64 4)
; TF-UNROLL-NEXT:    [[TMP75:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1032
; TF-UNROLL-NEXT:    br i1 [[TMP75]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP4:![0-9]+]]
; TF-UNROLL:       [[MIDDLE_BLOCK]]:
; TF-UNROLL-NEXT:    br label %[[FOR_END1:.*]]
; TF-UNROLL:       [[FOR_END1]]:
; TF-UNROLL-NEXT:    ret void
;
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %latch ]
  %cmp = icmp ugt i64 %iv, 10
  br i1 %cmp, label %do_load, label %latch
do_load:
  %v = load i64, ptr %b, align 8
  br label %latch

latch:
  %phi = phi i64 [0, %for.body], [%v, %do_load]
  %arrayidx = getelementptr inbounds i64, ptr %a, i64 %iv
  store i64 %phi, ptr %arrayidx
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, 1025
  br i1 %exitcond.not, label %for.end, label %for.body, !llvm.loop !0

for.end:
  ret void
}

define void @uniform_load_unaligned(ptr noalias nocapture %a, ptr noalias nocapture %b, i64 %n) {
; CHECK-LABEL: define void @uniform_load_unaligned(
; CHECK-SAME: ptr noalias captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = load i64, ptr [[B]], align 1
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x i64> poison, i64 [[TMP0]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x i64> [[BROADCAST_SPLATINSERT]], <4 x i64> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[INDEX]]
; CHECK-NEXT:    store <4 x i64> [[BROADCAST_SPLAT]], ptr [[TMP1]], align 4
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; CHECK-NEXT:    br i1 [[TMP2]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP8:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[SCALAR_PH:.*]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 1024, %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    [[V:%.*]] = load i64, ptr [[B]], align 1
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[IV]]
; CHECK-NEXT:    store i64 [[V]], ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[IV_NEXT]], 1025
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_END:.*]], label %[[FOR_BODY]], !llvm.loop [[LOOP9:![0-9]+]]
; CHECK:       [[FOR_END]]:
; CHECK-NEXT:    ret void
;
; TF-LABEL: define void @uniform_load_unaligned(
; TF-SAME: ptr noalias captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i64 [[N:%.*]]) {
; TF-NEXT:  [[ENTRY:.*:]]
; TF-NEXT:    br label %[[VECTOR_PH:.*]]
; TF:       [[VECTOR_PH]]:
; TF-NEXT:    br label %[[VECTOR_BODY:.*]]
; TF:       [[VECTOR_BODY]]:
; TF-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[FOR_END:.*]] ]
; TF-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i64(i64 [[INDEX]], i64 1025)
; TF-NEXT:    [[TMP1:%.*]] = load i64, ptr [[B]], align 1
; TF-NEXT:    [[TMP2:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 0
; TF-NEXT:    br i1 [[TMP2]], label %[[PRED_STORE_IF:.*]], label %[[PRED_STORE_IF1:.*]]
; TF:       [[PRED_STORE_IF]]:
; TF-NEXT:    [[TMP3:%.*]] = add i64 [[INDEX]], 0
; TF-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP3]]
; TF-NEXT:    store i64 [[TMP1]], ptr [[TMP4]], align 4
; TF-NEXT:    br label %[[PRED_STORE_IF1]]
; TF:       [[PRED_STORE_IF1]]:
; TF-NEXT:    [[TMP11:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 1
; TF-NEXT:    br i1 [[TMP11]], label %[[PRED_STORE_IF2:.*]], label %[[PRED_STORE_CONTINUE2:.*]]
; TF:       [[PRED_STORE_IF2]]:
; TF-NEXT:    [[TMP5:%.*]] = add i64 [[INDEX]], 1
; TF-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP5]]
; TF-NEXT:    store i64 [[TMP1]], ptr [[TMP6]], align 4
; TF-NEXT:    br label %[[PRED_STORE_CONTINUE2]]
; TF:       [[PRED_STORE_CONTINUE2]]:
; TF-NEXT:    [[TMP7:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 2
; TF-NEXT:    br i1 [[TMP7]], label %[[PRED_STORE_IF3:.*]], label %[[PRED_STORE_CONTINUE4:.*]]
; TF:       [[PRED_STORE_IF3]]:
; TF-NEXT:    [[TMP8:%.*]] = add i64 [[INDEX]], 2
; TF-NEXT:    [[TMP9:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP8]]
; TF-NEXT:    store i64 [[TMP1]], ptr [[TMP9]], align 4
; TF-NEXT:    br label %[[PRED_STORE_CONTINUE4]]
; TF:       [[PRED_STORE_CONTINUE4]]:
; TF-NEXT:    [[TMP10:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 3
; TF-NEXT:    br i1 [[TMP10]], label %[[PRED_STORE_IF5:.*]], label %[[FOR_END]]
; TF:       [[PRED_STORE_IF5]]:
; TF-NEXT:    [[TMP12:%.*]] = add i64 [[INDEX]], 3
; TF-NEXT:    [[TMP13:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP12]]
; TF-NEXT:    store i64 [[TMP1]], ptr [[TMP13]], align 4
; TF-NEXT:    br label %[[FOR_END]]
; TF:       [[FOR_END]]:
; TF-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; TF-NEXT:    [[TMP14:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1028
; TF-NEXT:    br i1 [[TMP14]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
; TF:       [[MIDDLE_BLOCK]]:
; TF-NEXT:    br label %[[FOR_END1:.*]]
; TF:       [[FOR_END1]]:
; TF-NEXT:    ret void
;
; TF-UNROLL-LABEL: define void @uniform_load_unaligned(
; TF-UNROLL-SAME: ptr noalias captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i64 [[N:%.*]]) {
; TF-UNROLL-NEXT:  [[ENTRY:.*:]]
; TF-UNROLL-NEXT:    br label %[[VECTOR_PH:.*]]
; TF-UNROLL:       [[VECTOR_PH]]:
; TF-UNROLL-NEXT:    br label %[[VECTOR_BODY:.*]]
; TF-UNROLL:       [[VECTOR_BODY]]:
; TF-UNROLL-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[PRED_STORE_CONTINUE15:.*]] ]
; TF-UNROLL-NEXT:    [[TMP0:%.*]] = add i64 [[INDEX]], 4
; TF-UNROLL-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i64(i64 [[INDEX]], i64 1025)
; TF-UNROLL-NEXT:    [[ACTIVE_LANE_MASK1:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i64(i64 [[TMP0]], i64 1025)
; TF-UNROLL-NEXT:    [[TMP2:%.*]] = load i64, ptr [[B]], align 1
; TF-UNROLL-NEXT:    [[TMP3:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 0
; TF-UNROLL-NEXT:    br i1 [[TMP3]], label %[[PRED_STORE_IF:.*]], label %[[PRED_STORE_IF9:.*]]
; TF-UNROLL:       [[PRED_STORE_IF]]:
; TF-UNROLL-NEXT:    [[TMP16:%.*]] = add i64 [[INDEX]], 0
; TF-UNROLL-NEXT:    [[TMP17:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP16]]
; TF-UNROLL-NEXT:    store i64 [[TMP2]], ptr [[TMP17]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_IF9]]
; TF-UNROLL:       [[PRED_STORE_IF9]]:
; TF-UNROLL-NEXT:    [[TMP5:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 1
; TF-UNROLL-NEXT:    br i1 [[TMP5]], label %[[PRED_STORE_IF2:.*]], label %[[PRED_STORE_CONTINUE10:.*]]
; TF-UNROLL:       [[PRED_STORE_IF2]]:
; TF-UNROLL-NEXT:    [[TMP6:%.*]] = add i64 [[INDEX]], 1
; TF-UNROLL-NEXT:    [[TMP7:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP6]]
; TF-UNROLL-NEXT:    store i64 [[TMP2]], ptr [[TMP7]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE10]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE10]]:
; TF-UNROLL-NEXT:    [[TMP8:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 2
; TF-UNROLL-NEXT:    br i1 [[TMP8]], label %[[PRED_STORE_IF4:.*]], label %[[PRED_STORE_CONTINUE12:.*]]
; TF-UNROLL:       [[PRED_STORE_IF4]]:
; TF-UNROLL-NEXT:    [[TMP9:%.*]] = add i64 [[INDEX]], 2
; TF-UNROLL-NEXT:    [[TMP10:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP9]]
; TF-UNROLL-NEXT:    store i64 [[TMP2]], ptr [[TMP10]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE12]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE12]]:
; TF-UNROLL-NEXT:    [[TMP11:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 3
; TF-UNROLL-NEXT:    br i1 [[TMP11]], label %[[PRED_STORE_IF6:.*]], label %[[FOR_END:.*]]
; TF-UNROLL:       [[PRED_STORE_IF6]]:
; TF-UNROLL-NEXT:    [[TMP25:%.*]] = add i64 [[INDEX]], 3
; TF-UNROLL-NEXT:    [[TMP26:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP25]]
; TF-UNROLL-NEXT:    store i64 [[TMP2]], ptr [[TMP26]], align 4
; TF-UNROLL-NEXT:    br label %[[FOR_END]]
; TF-UNROLL:       [[FOR_END]]:
; TF-UNROLL-NEXT:    [[TMP14:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 0
; TF-UNROLL-NEXT:    br i1 [[TMP14]], label %[[PRED_STORE_IF8:.*]], label %[[PRED_STORE_CONTINUE9:.*]]
; TF-UNROLL:       [[PRED_STORE_IF8]]:
; TF-UNROLL-NEXT:    [[TMP15:%.*]] = add i64 [[INDEX]], 4
; TF-UNROLL-NEXT:    [[TMP27:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP15]]
; TF-UNROLL-NEXT:    store i64 [[TMP2]], ptr [[TMP27]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE9]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE9]]:
; TF-UNROLL-NEXT:    [[TMP28:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 1
; TF-UNROLL-NEXT:    br i1 [[TMP28]], label %[[PRED_STORE_IF10:.*]], label %[[PRED_STORE_CONTINUE11:.*]]
; TF-UNROLL:       [[PRED_STORE_IF10]]:
; TF-UNROLL-NEXT:    [[TMP18:%.*]] = add i64 [[INDEX]], 5
; TF-UNROLL-NEXT:    [[TMP19:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP18]]
; TF-UNROLL-NEXT:    store i64 [[TMP2]], ptr [[TMP19]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE11]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE11]]:
; TF-UNROLL-NEXT:    [[TMP20:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 2
; TF-UNROLL-NEXT:    br i1 [[TMP20]], label %[[PRED_STORE_IF12:.*]], label %[[PRED_STORE_CONTINUE13:.*]]
; TF-UNROLL:       [[PRED_STORE_IF12]]:
; TF-UNROLL-NEXT:    [[TMP21:%.*]] = add i64 [[INDEX]], 6
; TF-UNROLL-NEXT:    [[TMP22:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP21]]
; TF-UNROLL-NEXT:    store i64 [[TMP2]], ptr [[TMP22]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE13]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE13]]:
; TF-UNROLL-NEXT:    [[TMP23:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 3
; TF-UNROLL-NEXT:    br i1 [[TMP23]], label %[[PRED_STORE_IF14:.*]], label %[[PRED_STORE_CONTINUE15]]
; TF-UNROLL:       [[PRED_STORE_IF14]]:
; TF-UNROLL-NEXT:    [[TMP24:%.*]] = add i64 [[INDEX]], 7
; TF-UNROLL-NEXT:    [[TMP29:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP24]]
; TF-UNROLL-NEXT:    store i64 [[TMP2]], ptr [[TMP29]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE15]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE15]]:
; TF-UNROLL-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 8
; TF-UNROLL-NEXT:    [[TMP30:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1032
; TF-UNROLL-NEXT:    br i1 [[TMP30]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
; TF-UNROLL:       [[MIDDLE_BLOCK]]:
; TF-UNROLL-NEXT:    br label %[[FOR_END1:.*]]
; TF-UNROLL:       [[FOR_END1]]:
; TF-UNROLL-NEXT:    ret void
;
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  %v = load i64, ptr %b, align 1
  %arrayidx = getelementptr inbounds i64, ptr %a, i64 %iv
  store i64 %v, ptr %arrayidx
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, 1025
  br i1 %exitcond.not, label %for.end, label %for.body

for.end:
  ret void
}

define void @uniform_store(ptr noalias nocapture %a, ptr noalias nocapture %b, i64 %v, i64 %n) {
; CHECK-LABEL: define void @uniform_store(
; CHECK-SAME: ptr noalias captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i64 [[V:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x i64> poison, i64 [[V]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x i64> [[BROADCAST_SPLATINSERT]], <4 x i64> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    store i64 [[V]], ptr [[B]], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[INDEX]]
; CHECK-NEXT:    store <4 x i64> [[BROADCAST_SPLAT]], ptr [[TMP0]], align 4
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; CHECK-NEXT:    br i1 [[TMP1]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP10:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[SCALAR_PH:.*]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 1024, %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    store i64 [[V]], ptr [[B]], align 8
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[IV]]
; CHECK-NEXT:    store i64 [[V]], ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[IV_NEXT]], 1025
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_END:.*]], label %[[FOR_BODY]], !llvm.loop [[LOOP11:![0-9]+]]
; CHECK:       [[FOR_END]]:
; CHECK-NEXT:    ret void
;
; TF-LABEL: define void @uniform_store(
; TF-SAME: ptr noalias captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i64 [[V:%.*]], i64 [[N:%.*]]) {
; TF-NEXT:  [[ENTRY:.*:]]
; TF-NEXT:    br label %[[VECTOR_PH:.*]]
; TF:       [[VECTOR_PH]]:
; TF-NEXT:    br label %[[VECTOR_BODY:.*]]
; TF:       [[VECTOR_BODY]]:
; TF-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[FOR_END:.*]] ]
; TF-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i64(i64 [[INDEX]], i64 1025)
; TF-NEXT:    store i64 [[V]], ptr [[B]], align 8
; TF-NEXT:    [[TMP0:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 0
; TF-NEXT:    br i1 [[TMP0]], label %[[PRED_STORE_IF:.*]], label %[[PRED_STORE_IF1:.*]]
; TF:       [[PRED_STORE_IF]]:
; TF-NEXT:    [[TMP2:%.*]] = add i64 [[INDEX]], 0
; TF-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP2]]
; TF-NEXT:    store i64 [[V]], ptr [[TMP3]], align 4
; TF-NEXT:    br label %[[PRED_STORE_IF1]]
; TF:       [[PRED_STORE_IF1]]:
; TF-NEXT:    [[TMP10:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 1
; TF-NEXT:    br i1 [[TMP10]], label %[[PRED_STORE_IF2:.*]], label %[[PRED_STORE_CONTINUE2:.*]]
; TF:       [[PRED_STORE_IF2]]:
; TF-NEXT:    [[TMP4:%.*]] = add i64 [[INDEX]], 1
; TF-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP4]]
; TF-NEXT:    store i64 [[V]], ptr [[TMP5]], align 4
; TF-NEXT:    br label %[[PRED_STORE_CONTINUE2]]
; TF:       [[PRED_STORE_CONTINUE2]]:
; TF-NEXT:    [[TMP6:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 2
; TF-NEXT:    br i1 [[TMP6]], label %[[PRED_STORE_IF3:.*]], label %[[PRED_STORE_CONTINUE4:.*]]
; TF:       [[PRED_STORE_IF3]]:
; TF-NEXT:    [[TMP7:%.*]] = add i64 [[INDEX]], 2
; TF-NEXT:    [[TMP8:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP7]]
; TF-NEXT:    store i64 [[V]], ptr [[TMP8]], align 4
; TF-NEXT:    br label %[[PRED_STORE_CONTINUE4]]
; TF:       [[PRED_STORE_CONTINUE4]]:
; TF-NEXT:    [[TMP9:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 3
; TF-NEXT:    br i1 [[TMP9]], label %[[PRED_STORE_IF5:.*]], label %[[FOR_END]]
; TF:       [[PRED_STORE_IF5]]:
; TF-NEXT:    [[TMP11:%.*]] = add i64 [[INDEX]], 3
; TF-NEXT:    [[TMP12:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP11]]
; TF-NEXT:    store i64 [[V]], ptr [[TMP12]], align 4
; TF-NEXT:    br label %[[FOR_END]]
; TF:       [[FOR_END]]:
; TF-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; TF-NEXT:    [[TMP13:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1028
; TF-NEXT:    br i1 [[TMP13]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP6:![0-9]+]]
; TF:       [[MIDDLE_BLOCK]]:
; TF-NEXT:    br label %[[FOR_END1:.*]]
; TF:       [[FOR_END1]]:
; TF-NEXT:    ret void
;
; TF-UNROLL-LABEL: define void @uniform_store(
; TF-UNROLL-SAME: ptr noalias captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i64 [[V:%.*]], i64 [[N:%.*]]) {
; TF-UNROLL-NEXT:  [[ENTRY:.*:]]
; TF-UNROLL-NEXT:    br label %[[VECTOR_PH:.*]]
; TF-UNROLL:       [[VECTOR_PH]]:
; TF-UNROLL-NEXT:    br label %[[VECTOR_BODY:.*]]
; TF-UNROLL:       [[VECTOR_BODY]]:
; TF-UNROLL-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[PRED_STORE_CONTINUE15:.*]] ]
; TF-UNROLL-NEXT:    [[TMP0:%.*]] = add i64 [[INDEX]], 4
; TF-UNROLL-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i64(i64 [[INDEX]], i64 1025)
; TF-UNROLL-NEXT:    [[ACTIVE_LANE_MASK1:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i64(i64 [[TMP0]], i64 1025)
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[B]], align 8
; TF-UNROLL-NEXT:    [[TMP1:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 0
; TF-UNROLL-NEXT:    br i1 [[TMP1]], label %[[PRED_STORE_IF:.*]], label %[[PRED_STORE_IF9:.*]]
; TF-UNROLL:       [[PRED_STORE_IF]]:
; TF-UNROLL-NEXT:    [[TMP15:%.*]] = add i64 [[INDEX]], 0
; TF-UNROLL-NEXT:    [[TMP16:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP15]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP16]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_IF9]]
; TF-UNROLL:       [[PRED_STORE_IF9]]:
; TF-UNROLL-NEXT:    [[TMP4:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 1
; TF-UNROLL-NEXT:    br i1 [[TMP4]], label %[[PRED_STORE_IF2:.*]], label %[[PRED_STORE_CONTINUE10:.*]]
; TF-UNROLL:       [[PRED_STORE_IF2]]:
; TF-UNROLL-NEXT:    [[TMP5:%.*]] = add i64 [[INDEX]], 1
; TF-UNROLL-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP5]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP6]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE10]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE10]]:
; TF-UNROLL-NEXT:    [[TMP7:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 2
; TF-UNROLL-NEXT:    br i1 [[TMP7]], label %[[PRED_STORE_IF4:.*]], label %[[PRED_STORE_CONTINUE12:.*]]
; TF-UNROLL:       [[PRED_STORE_IF4]]:
; TF-UNROLL-NEXT:    [[TMP8:%.*]] = add i64 [[INDEX]], 2
; TF-UNROLL-NEXT:    [[TMP9:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP8]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP9]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE12]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE12]]:
; TF-UNROLL-NEXT:    [[TMP10:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 3
; TF-UNROLL-NEXT:    br i1 [[TMP10]], label %[[PRED_STORE_IF6:.*]], label %[[FOR_END:.*]]
; TF-UNROLL:       [[PRED_STORE_IF6]]:
; TF-UNROLL-NEXT:    [[TMP24:%.*]] = add i64 [[INDEX]], 3
; TF-UNROLL-NEXT:    [[TMP25:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP24]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP25]], align 4
; TF-UNROLL-NEXT:    br label %[[FOR_END]]
; TF-UNROLL:       [[FOR_END]]:
; TF-UNROLL-NEXT:    [[TMP13:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 0
; TF-UNROLL-NEXT:    br i1 [[TMP13]], label %[[PRED_STORE_IF8:.*]], label %[[PRED_STORE_CONTINUE9:.*]]
; TF-UNROLL:       [[PRED_STORE_IF8]]:
; TF-UNROLL-NEXT:    [[TMP14:%.*]] = add i64 [[INDEX]], 4
; TF-UNROLL-NEXT:    [[TMP26:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP14]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP26]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE9]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE9]]:
; TF-UNROLL-NEXT:    [[TMP27:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 1
; TF-UNROLL-NEXT:    br i1 [[TMP27]], label %[[PRED_STORE_IF10:.*]], label %[[PRED_STORE_CONTINUE11:.*]]
; TF-UNROLL:       [[PRED_STORE_IF10]]:
; TF-UNROLL-NEXT:    [[TMP17:%.*]] = add i64 [[INDEX]], 5
; TF-UNROLL-NEXT:    [[TMP18:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP17]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP18]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE11]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE11]]:
; TF-UNROLL-NEXT:    [[TMP19:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 2
; TF-UNROLL-NEXT:    br i1 [[TMP19]], label %[[PRED_STORE_IF12:.*]], label %[[PRED_STORE_CONTINUE13:.*]]
; TF-UNROLL:       [[PRED_STORE_IF12]]:
; TF-UNROLL-NEXT:    [[TMP20:%.*]] = add i64 [[INDEX]], 6
; TF-UNROLL-NEXT:    [[TMP21:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP20]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP21]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE13]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE13]]:
; TF-UNROLL-NEXT:    [[TMP22:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 3
; TF-UNROLL-NEXT:    br i1 [[TMP22]], label %[[PRED_STORE_IF14:.*]], label %[[PRED_STORE_CONTINUE15]]
; TF-UNROLL:       [[PRED_STORE_IF14]]:
; TF-UNROLL-NEXT:    [[TMP23:%.*]] = add i64 [[INDEX]], 7
; TF-UNROLL-NEXT:    [[TMP28:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP23]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP28]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE15]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE15]]:
; TF-UNROLL-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 8
; TF-UNROLL-NEXT:    [[TMP29:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1032
; TF-UNROLL-NEXT:    br i1 [[TMP29]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP6:![0-9]+]]
; TF-UNROLL:       [[MIDDLE_BLOCK]]:
; TF-UNROLL-NEXT:    br label %[[FOR_END1:.*]]
; TF-UNROLL:       [[FOR_END1]]:
; TF-UNROLL-NEXT:    ret void
;
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  store i64 %v, ptr %b, align 8
  %arrayidx = getelementptr inbounds i64, ptr %a, i64 %iv
  store i64 %v, ptr %arrayidx
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, 1025
  br i1 %exitcond.not, label %for.end, label %for.body

for.end:
  ret void
}

define void @uniform_store_of_loop_varying(ptr noalias nocapture %a, ptr noalias nocapture %b, i64 %v, i64 %n) {
; CHECK-LABEL: define void @uniform_store_of_loop_varying(
; CHECK-SAME: ptr noalias captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i64 [[V:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x i64> poison, i64 [[V]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x i64> [[BROADCAST_SPLATINSERT]], <4 x i64> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = add i64 [[INDEX]], 0
; CHECK-NEXT:    [[TMP1:%.*]] = add i64 [[INDEX]], 1
; CHECK-NEXT:    [[TMP2:%.*]] = add i64 [[INDEX]], 2
; CHECK-NEXT:    [[TMP3:%.*]] = add i64 [[INDEX]], 3
; CHECK-NEXT:    store i64 [[TMP3]], ptr [[B]], align 8
; CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP0]]
; CHECK-NEXT:    store <4 x i64> [[BROADCAST_SPLAT]], ptr [[TMP4]], align 4
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; CHECK-NEXT:    [[TMP5:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; CHECK-NEXT:    br i1 [[TMP5]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP12:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[SCALAR_PH:.*]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 1024, %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    store i64 [[IV]], ptr [[B]], align 8
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[IV]]
; CHECK-NEXT:    store i64 [[V]], ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[IV_NEXT]], 1025
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_END:.*]], label %[[FOR_BODY]], !llvm.loop [[LOOP13:![0-9]+]]
; CHECK:       [[FOR_END]]:
; CHECK-NEXT:    ret void
;
; TF-LABEL: define void @uniform_store_of_loop_varying(
; TF-SAME: ptr noalias captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i64 [[V:%.*]], i64 [[N:%.*]]) {
; TF-NEXT:  [[ENTRY:.*:]]
; TF-NEXT:    br label %[[VECTOR_PH:.*]]
; TF:       [[VECTOR_PH]]:
; TF-NEXT:    br label %[[VECTOR_BODY:.*]]
; TF:       [[VECTOR_BODY]]:
; TF-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[FOR_END:.*]] ]
; TF-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i64(i64 [[INDEX]], i64 1025)
; TF-NEXT:    [[TMP0:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 0
; TF-NEXT:    br i1 [[TMP0]], label %[[PRED_STORE_IF:.*]], label %[[MIDDLE_BLOCK:.*]]
; TF:       [[PRED_STORE_IF]]:
; TF-NEXT:    [[TMP2:%.*]] = add i64 [[INDEX]], 0
; TF-NEXT:    store i64 [[TMP2]], ptr [[B]], align 8
; TF-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP2]]
; TF-NEXT:    store i64 [[V]], ptr [[TMP4]], align 4
; TF-NEXT:    br label %[[MIDDLE_BLOCK]]
; TF:       [[MIDDLE_BLOCK]]:
; TF-NEXT:    [[TMP3:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 1
; TF-NEXT:    br i1 [[TMP3]], label %[[PRED_STORE_IF1:.*]], label %[[PRED_STORE_CONTINUE4:.*]]
; TF:       [[PRED_STORE_IF1]]:
; TF-NEXT:    [[TMP10:%.*]] = add i64 [[INDEX]], 1
; TF-NEXT:    store i64 [[TMP10]], ptr [[B]], align 8
; TF-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP10]]
; TF-NEXT:    store i64 [[V]], ptr [[TMP5]], align 4
; TF-NEXT:    br label %[[PRED_STORE_CONTINUE4]]
; TF:       [[PRED_STORE_CONTINUE4]]:
; TF-NEXT:    [[TMP6:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 2
; TF-NEXT:    br i1 [[TMP6]], label %[[PRED_STORE_IF3:.*]], label %[[PRED_STORE_IF5:.*]]
; TF:       [[PRED_STORE_IF3]]:
; TF-NEXT:    [[TMP7:%.*]] = add i64 [[INDEX]], 2
; TF-NEXT:    store i64 [[TMP7]], ptr [[B]], align 8
; TF-NEXT:    [[TMP8:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP7]]
; TF-NEXT:    store i64 [[V]], ptr [[TMP8]], align 4
; TF-NEXT:    br label %[[PRED_STORE_IF5]]
; TF:       [[PRED_STORE_IF5]]:
; TF-NEXT:    [[TMP9:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 3
; TF-NEXT:    br i1 [[TMP9]], label %[[PRED_STORE_IF6:.*]], label %[[FOR_END]]
; TF:       [[PRED_STORE_IF6]]:
; TF-NEXT:    [[TMP11:%.*]] = add i64 [[INDEX]], 3
; TF-NEXT:    store i64 [[TMP11]], ptr [[B]], align 8
; TF-NEXT:    [[TMP12:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP11]]
; TF-NEXT:    store i64 [[V]], ptr [[TMP12]], align 4
; TF-NEXT:    br label %[[FOR_END]]
; TF:       [[FOR_END]]:
; TF-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; TF-NEXT:    [[TMP13:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1028
; TF-NEXT:    br i1 [[TMP13]], label %[[MIDDLE_BLOCK1:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP7:![0-9]+]]
; TF:       [[MIDDLE_BLOCK1]]:
; TF-NEXT:    br label %[[FOR_END1:.*]]
; TF:       [[FOR_END1]]:
; TF-NEXT:    ret void
;
; TF-UNROLL-LABEL: define void @uniform_store_of_loop_varying(
; TF-UNROLL-SAME: ptr noalias captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i64 [[V:%.*]], i64 [[N:%.*]]) {
; TF-UNROLL-NEXT:  [[PRED_STORE_IF3:.*:]]
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE4:.*]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE4]]:
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE6:.*]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE6]]:
; TF-UNROLL-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[PRED_STORE_CONTINUE4]] ], [ [[INDEX_NEXT:%.*]], %[[PRED_STORE_CONTINUE15:.*]] ]
; TF-UNROLL-NEXT:    [[TMP15:%.*]] = add i64 [[INDEX]], 4
; TF-UNROLL-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i64(i64 [[INDEX]], i64 1025)
; TF-UNROLL-NEXT:    [[ACTIVE_LANE_MASK1:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i64(i64 [[TMP15]], i64 1025)
; TF-UNROLL-NEXT:    [[TMP1:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 0
; TF-UNROLL-NEXT:    br i1 [[TMP1]], label %[[PRED_STORE_IF:.*]], label %[[MIDDLE_BLOCK:.*]]
; TF-UNROLL:       [[PRED_STORE_IF]]:
; TF-UNROLL-NEXT:    [[TMP3:%.*]] = add i64 [[INDEX]], 0
; TF-UNROLL-NEXT:    store i64 [[TMP3]], ptr [[B]], align 8
; TF-UNROLL-NEXT:    [[TMP11:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP3]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP11]], align 4
; TF-UNROLL-NEXT:    br label %[[MIDDLE_BLOCK]]
; TF-UNROLL:       [[MIDDLE_BLOCK]]:
; TF-UNROLL-NEXT:    [[TMP4:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 1
; TF-UNROLL-NEXT:    br i1 [[TMP4]], label %[[PRED_STORE_IF2:.*]], label %[[PRED_STORE_CONTINUE12:.*]]
; TF-UNROLL:       [[PRED_STORE_IF2]]:
; TF-UNROLL-NEXT:    [[TMP5:%.*]] = add i64 [[INDEX]], 1
; TF-UNROLL-NEXT:    store i64 [[TMP5]], ptr [[B]], align 8
; TF-UNROLL-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP5]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP6]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE12]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE12]]:
; TF-UNROLL-NEXT:    [[TMP7:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 2
; TF-UNROLL-NEXT:    br i1 [[TMP7]], label %[[PRED_STORE_IF4:.*]], label %[[PRED_STORE_IF13:.*]]
; TF-UNROLL:       [[PRED_STORE_IF4]]:
; TF-UNROLL-NEXT:    [[TMP8:%.*]] = add i64 [[INDEX]], 2
; TF-UNROLL-NEXT:    store i64 [[TMP8]], ptr [[B]], align 8
; TF-UNROLL-NEXT:    [[TMP9:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP8]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP9]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_IF13]]
; TF-UNROLL:       [[PRED_STORE_IF13]]:
; TF-UNROLL-NEXT:    [[TMP10:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 3
; TF-UNROLL-NEXT:    br i1 [[TMP10]], label %[[PRED_STORE_IF6:.*]], label %[[FOR_END:.*]]
; TF-UNROLL:       [[PRED_STORE_IF6]]:
; TF-UNROLL-NEXT:    [[TMP24:%.*]] = add i64 [[INDEX]], 3
; TF-UNROLL-NEXT:    store i64 [[TMP24]], ptr [[B]], align 8
; TF-UNROLL-NEXT:    [[TMP25:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP24]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP25]], align 4
; TF-UNROLL-NEXT:    br label %[[FOR_END]]
; TF-UNROLL:       [[FOR_END]]:
; TF-UNROLL-NEXT:    [[TMP13:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 0
; TF-UNROLL-NEXT:    br i1 [[TMP13]], label %[[PRED_STORE_IF8:.*]], label %[[PRED_STORE_CONTINUE9:.*]]
; TF-UNROLL:       [[PRED_STORE_IF8]]:
; TF-UNROLL-NEXT:    [[TMP14:%.*]] = add i64 [[INDEX]], 4
; TF-UNROLL-NEXT:    store i64 [[TMP14]], ptr [[B]], align 8
; TF-UNROLL-NEXT:    [[TMP26:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP14]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP26]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE9]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE9]]:
; TF-UNROLL-NEXT:    [[TMP16:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 1
; TF-UNROLL-NEXT:    br i1 [[TMP16]], label %[[PRED_STORE_IF10:.*]], label %[[PRED_STORE_CONTINUE11:.*]]
; TF-UNROLL:       [[PRED_STORE_IF10]]:
; TF-UNROLL-NEXT:    [[TMP17:%.*]] = add i64 [[INDEX]], 5
; TF-UNROLL-NEXT:    store i64 [[TMP17]], ptr [[B]], align 8
; TF-UNROLL-NEXT:    [[TMP18:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP17]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP18]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE11]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE11]]:
; TF-UNROLL-NEXT:    [[TMP19:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 2
; TF-UNROLL-NEXT:    br i1 [[TMP19]], label %[[PRED_STORE_IF12:.*]], label %[[PRED_STORE_CONTINUE13:.*]]
; TF-UNROLL:       [[PRED_STORE_IF12]]:
; TF-UNROLL-NEXT:    [[TMP20:%.*]] = add i64 [[INDEX]], 6
; TF-UNROLL-NEXT:    store i64 [[TMP20]], ptr [[B]], align 8
; TF-UNROLL-NEXT:    [[TMP21:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP20]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP21]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE13]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE13]]:
; TF-UNROLL-NEXT:    [[TMP22:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 3
; TF-UNROLL-NEXT:    br i1 [[TMP22]], label %[[PRED_STORE_IF14:.*]], label %[[PRED_STORE_CONTINUE15]]
; TF-UNROLL:       [[PRED_STORE_IF14]]:
; TF-UNROLL-NEXT:    [[TMP23:%.*]] = add i64 [[INDEX]], 7
; TF-UNROLL-NEXT:    store i64 [[TMP23]], ptr [[B]], align 8
; TF-UNROLL-NEXT:    [[TMP27:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP23]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP27]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE15]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE15]]:
; TF-UNROLL-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 8
; TF-UNROLL-NEXT:    [[TMP28:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1032
; TF-UNROLL-NEXT:    br i1 [[TMP28]], label %[[MIDDLE_BLOCK1:.*]], label %[[PRED_STORE_CONTINUE6]], !llvm.loop [[LOOP7:![0-9]+]]
; TF-UNROLL:       [[MIDDLE_BLOCK1]]:
; TF-UNROLL-NEXT:    br label %[[FOR_END1:.*]]
; TF-UNROLL:       [[FOR_END1]]:
; TF-UNROLL-NEXT:    ret void
;
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  store i64 %iv, ptr %b, align 8
  %arrayidx = getelementptr inbounds i64, ptr %a, i64 %iv
  store i64 %v, ptr %arrayidx
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, 1025
  br i1 %exitcond.not, label %for.end, label %for.body

for.end:
  ret void
}

define void @conditional_uniform_store(ptr noalias nocapture %a, ptr noalias nocapture %b, i64 %v, i64 %n) {
; CHECK-LABEL: define void @conditional_uniform_store(
; CHECK-SAME: ptr noalias captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i64 [[V:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x i64> poison, i64 [[V]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x i64> [[BROADCAST_SPLATINSERT]], <4 x i64> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[PRED_STORE_CONTINUE6:.*]] ]
; CHECK-NEXT:    [[VEC_IND:%.*]] = phi <4 x i64> [ <i64 0, i64 1, i64 2, i64 3>, %[[VECTOR_PH]] ], [ [[VEC_IND_NEXT:%.*]], %[[PRED_STORE_CONTINUE6]] ]
; CHECK-NEXT:    [[TMP0:%.*]] = icmp ugt <4 x i64> [[VEC_IND]], splat (i64 10)
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <4 x i1> [[TMP0]], i32 0
; CHECK-NEXT:    br i1 [[TMP1]], label %[[PRED_STORE_IF:.*]], label %[[PRED_STORE_CONTINUE:.*]]
; CHECK:       [[PRED_STORE_IF]]:
; CHECK-NEXT:    store i64 [[V]], ptr [[B]], align 8
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE]]
; CHECK:       [[PRED_STORE_CONTINUE]]:
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x i1> [[TMP0]], i32 1
; CHECK-NEXT:    br i1 [[TMP2]], label %[[PRED_STORE_IF1:.*]], label %[[PRED_STORE_CONTINUE2:.*]]
; CHECK:       [[PRED_STORE_IF1]]:
; CHECK-NEXT:    store i64 [[V]], ptr [[B]], align 8
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE2]]
; CHECK:       [[PRED_STORE_CONTINUE2]]:
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <4 x i1> [[TMP0]], i32 2
; CHECK-NEXT:    br i1 [[TMP3]], label %[[PRED_STORE_IF3:.*]], label %[[PRED_STORE_CONTINUE4:.*]]
; CHECK:       [[PRED_STORE_IF3]]:
; CHECK-NEXT:    store i64 [[V]], ptr [[B]], align 8
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE4]]
; CHECK:       [[PRED_STORE_CONTINUE4]]:
; CHECK-NEXT:    [[TMP4:%.*]] = extractelement <4 x i1> [[TMP0]], i32 3
; CHECK-NEXT:    br i1 [[TMP4]], label %[[PRED_STORE_IF5:.*]], label %[[PRED_STORE_CONTINUE6]]
; CHECK:       [[PRED_STORE_IF5]]:
; CHECK-NEXT:    store i64 [[V]], ptr [[B]], align 8
; CHECK-NEXT:    br label %[[PRED_STORE_CONTINUE6]]
; CHECK:       [[PRED_STORE_CONTINUE6]]:
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[INDEX]]
; CHECK-NEXT:    store <4 x i64> [[BROADCAST_SPLAT]], ptr [[TMP5]], align 4
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; CHECK-NEXT:    [[VEC_IND_NEXT]] = add nuw nsw <4 x i64> [[VEC_IND]], splat (i64 4)
; CHECK-NEXT:    [[TMP6:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; CHECK-NEXT:    br i1 [[TMP6]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP14:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[SCALAR_PH:.*]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 1024, %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LATCH:.*]] ]
; CHECK-NEXT:    [[CMP:%.*]] = icmp ugt i64 [[IV]], 10
; CHECK-NEXT:    br i1 [[CMP]], label %[[DO_STORE:.*]], label %[[LATCH]]
; CHECK:       [[DO_STORE]]:
; CHECK-NEXT:    store i64 [[V]], ptr [[B]], align 8
; CHECK-NEXT:    br label %[[LATCH]]
; CHECK:       [[LATCH]]:
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[IV]]
; CHECK-NEXT:    store i64 [[V]], ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[IV_NEXT]], 1025
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_END:.*]], label %[[FOR_BODY]], !llvm.loop [[LOOP15:![0-9]+]]
; CHECK:       [[FOR_END]]:
; CHECK-NEXT:    ret void
;
; TF-LABEL: define void @conditional_uniform_store(
; TF-SAME: ptr noalias captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i64 [[V:%.*]], i64 [[N:%.*]]) {
; TF-NEXT:  [[ENTRY:.*:]]
; TF-NEXT:    br label %[[VECTOR_PH:.*]]
; TF:       [[VECTOR_PH]]:
; TF-NEXT:    br label %[[VECTOR_BODY:.*]]
; TF:       [[VECTOR_BODY]]:
; TF-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[FOR_END:.*]] ]
; TF-NEXT:    [[VEC_IND:%.*]] = phi <4 x i64> [ <i64 0, i64 1, i64 2, i64 3>, %[[VECTOR_PH]] ], [ [[VEC_IND_NEXT:%.*]], %[[FOR_END]] ]
; TF-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i64(i64 [[INDEX]], i64 1025)
; TF-NEXT:    [[TMP1:%.*]] = icmp ugt <4 x i64> [[VEC_IND]], splat (i64 10)
; TF-NEXT:    [[TMP2:%.*]] = select <4 x i1> [[ACTIVE_LANE_MASK]], <4 x i1> [[TMP1]], <4 x i1> zeroinitializer
; TF-NEXT:    [[TMP3:%.*]] = extractelement <4 x i1> [[TMP2]], i32 0
; TF-NEXT:    br i1 [[TMP3]], label %[[PRED_STORE_IF:.*]], label %[[PRED_STORE_CONTINUE:.*]]
; TF:       [[PRED_STORE_IF]]:
; TF-NEXT:    store i64 [[V]], ptr [[B]], align 8
; TF-NEXT:    br label %[[PRED_STORE_CONTINUE]]
; TF:       [[PRED_STORE_CONTINUE]]:
; TF-NEXT:    [[TMP4:%.*]] = extractelement <4 x i1> [[TMP2]], i32 1
; TF-NEXT:    br i1 [[TMP4]], label %[[PRED_STORE_IF1:.*]], label %[[PRED_STORE_CONTINUE2:.*]]
; TF:       [[PRED_STORE_IF1]]:
; TF-NEXT:    store i64 [[V]], ptr [[B]], align 8
; TF-NEXT:    br label %[[PRED_STORE_CONTINUE2]]
; TF:       [[PRED_STORE_CONTINUE2]]:
; TF-NEXT:    [[TMP5:%.*]] = extractelement <4 x i1> [[TMP2]], i32 2
; TF-NEXT:    br i1 [[TMP5]], label %[[PRED_STORE_IF3:.*]], label %[[PRED_STORE_CONTINUE4:.*]]
; TF:       [[PRED_STORE_IF3]]:
; TF-NEXT:    store i64 [[V]], ptr [[B]], align 8
; TF-NEXT:    br label %[[PRED_STORE_CONTINUE4]]
; TF:       [[PRED_STORE_CONTINUE4]]:
; TF-NEXT:    [[TMP6:%.*]] = extractelement <4 x i1> [[TMP2]], i32 3
; TF-NEXT:    br i1 [[TMP6]], label %[[PRED_STORE_IF5:.*]], label %[[PRED_STORE_CONTINUE6:.*]]
; TF:       [[PRED_STORE_IF5]]:
; TF-NEXT:    store i64 [[V]], ptr [[B]], align 8
; TF-NEXT:    br label %[[PRED_STORE_CONTINUE6]]
; TF:       [[PRED_STORE_CONTINUE6]]:
; TF-NEXT:    [[TMP7:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 0
; TF-NEXT:    br i1 [[TMP7]], label %[[PRED_STORE_IF7:.*]], label %[[PRED_STORE_CONTINUE8:.*]]
; TF:       [[PRED_STORE_IF7]]:
; TF-NEXT:    [[TMP8:%.*]] = add i64 [[INDEX]], 0
; TF-NEXT:    [[TMP9:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP8]]
; TF-NEXT:    store i64 [[V]], ptr [[TMP9]], align 4
; TF-NEXT:    br label %[[PRED_STORE_CONTINUE8]]
; TF:       [[PRED_STORE_CONTINUE8]]:
; TF-NEXT:    [[TMP12:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 1
; TF-NEXT:    br i1 [[TMP12]], label %[[PRED_STORE_IF9:.*]], label %[[PRED_STORE_CONTINUE10:.*]]
; TF:       [[PRED_STORE_IF9]]:
; TF-NEXT:    [[TMP10:%.*]] = add i64 [[INDEX]], 1
; TF-NEXT:    [[TMP11:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP10]]
; TF-NEXT:    store i64 [[V]], ptr [[TMP11]], align 4
; TF-NEXT:    br label %[[PRED_STORE_CONTINUE10]]
; TF:       [[PRED_STORE_CONTINUE10]]:
; TF-NEXT:    [[TMP13:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 2
; TF-NEXT:    br i1 [[TMP13]], label %[[PRED_STORE_IF11:.*]], label %[[PRED_STORE_CONTINUE12:.*]]
; TF:       [[PRED_STORE_IF11]]:
; TF-NEXT:    [[TMP16:%.*]] = add i64 [[INDEX]], 2
; TF-NEXT:    [[TMP14:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP16]]
; TF-NEXT:    store i64 [[V]], ptr [[TMP14]], align 4
; TF-NEXT:    br label %[[PRED_STORE_CONTINUE12]]
; TF:       [[PRED_STORE_CONTINUE12]]:
; TF-NEXT:    [[TMP15:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 3
; TF-NEXT:    br i1 [[TMP15]], label %[[PRED_STORE_IF13:.*]], label %[[FOR_END]]
; TF:       [[PRED_STORE_IF13]]:
; TF-NEXT:    [[TMP17:%.*]] = add i64 [[INDEX]], 3
; TF-NEXT:    [[TMP18:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP17]]
; TF-NEXT:    store i64 [[V]], ptr [[TMP18]], align 4
; TF-NEXT:    br label %[[FOR_END]]
; TF:       [[FOR_END]]:
; TF-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; TF-NEXT:    [[VEC_IND_NEXT]] = add <4 x i64> [[VEC_IND]], splat (i64 4)
; TF-NEXT:    [[TMP19:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1028
; TF-NEXT:    br i1 [[TMP19]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP8:![0-9]+]]
; TF:       [[MIDDLE_BLOCK]]:
; TF-NEXT:    br label %[[FOR_END1:.*]]
; TF:       [[FOR_END1]]:
; TF-NEXT:    ret void
;
; TF-UNROLL-LABEL: define void @conditional_uniform_store(
; TF-UNROLL-SAME: ptr noalias captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i64 [[V:%.*]], i64 [[N:%.*]]) {
; TF-UNROLL-NEXT:  [[ENTRY:.*:]]
; TF-UNROLL-NEXT:    br label %[[VECTOR_PH:.*]]
; TF-UNROLL:       [[VECTOR_PH]]:
; TF-UNROLL-NEXT:    br label %[[VECTOR_BODY:.*]]
; TF-UNROLL:       [[VECTOR_BODY]]:
; TF-UNROLL-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[PRED_STORE_CONTINUE31:.*]] ]
; TF-UNROLL-NEXT:    [[VEC_IND:%.*]] = phi <4 x i64> [ <i64 0, i64 1, i64 2, i64 3>, %[[VECTOR_PH]] ], [ [[VEC_IND_NEXT:%.*]], %[[PRED_STORE_CONTINUE31]] ]
; TF-UNROLL-NEXT:    [[STEP_ADD:%.*]] = add <4 x i64> [[VEC_IND]], splat (i64 4)
; TF-UNROLL-NEXT:    [[TMP0:%.*]] = add i64 [[INDEX]], 4
; TF-UNROLL-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i64(i64 [[INDEX]], i64 1025)
; TF-UNROLL-NEXT:    [[ACTIVE_LANE_MASK1:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i64(i64 [[TMP0]], i64 1025)
; TF-UNROLL-NEXT:    [[TMP2:%.*]] = icmp ugt <4 x i64> [[VEC_IND]], splat (i64 10)
; TF-UNROLL-NEXT:    [[TMP3:%.*]] = icmp ugt <4 x i64> [[STEP_ADD]], splat (i64 10)
; TF-UNROLL-NEXT:    [[TMP5:%.*]] = select <4 x i1> [[ACTIVE_LANE_MASK]], <4 x i1> [[TMP2]], <4 x i1> zeroinitializer
; TF-UNROLL-NEXT:    [[TMP4:%.*]] = select <4 x i1> [[ACTIVE_LANE_MASK1]], <4 x i1> [[TMP3]], <4 x i1> zeroinitializer
; TF-UNROLL-NEXT:    [[TMP6:%.*]] = extractelement <4 x i1> [[TMP5]], i32 0
; TF-UNROLL-NEXT:    br i1 [[TMP6]], label %[[PRED_STORE_IF:.*]], label %[[PRED_STORE_CONTINUE:.*]]
; TF-UNROLL:       [[PRED_STORE_IF]]:
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[B]], align 8
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE]]:
; TF-UNROLL-NEXT:    [[TMP7:%.*]] = extractelement <4 x i1> [[TMP5]], i32 1
; TF-UNROLL-NEXT:    br i1 [[TMP7]], label %[[PRED_STORE_IF1:.*]], label %[[PRED_STORE_CONTINUE2:.*]]
; TF-UNROLL:       [[PRED_STORE_IF1]]:
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[B]], align 8
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE2]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE2]]:
; TF-UNROLL-NEXT:    [[TMP8:%.*]] = extractelement <4 x i1> [[TMP5]], i32 2
; TF-UNROLL-NEXT:    br i1 [[TMP8]], label %[[PRED_STORE_IF3:.*]], label %[[PRED_STORE_CONTINUE4:.*]]
; TF-UNROLL:       [[PRED_STORE_IF3]]:
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[B]], align 8
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE4]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE4]]:
; TF-UNROLL-NEXT:    [[TMP9:%.*]] = extractelement <4 x i1> [[TMP5]], i32 3
; TF-UNROLL-NEXT:    br i1 [[TMP9]], label %[[PRED_STORE_IF5:.*]], label %[[PRED_STORE_CONTINUE6:.*]]
; TF-UNROLL:       [[PRED_STORE_IF5]]:
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[B]], align 8
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE6]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE6]]:
; TF-UNROLL-NEXT:    [[TMP10:%.*]] = extractelement <4 x i1> [[TMP4]], i32 0
; TF-UNROLL-NEXT:    br i1 [[TMP10]], label %[[PRED_STORE_IF7:.*]], label %[[PRED_STORE_CONTINUE8:.*]]
; TF-UNROLL:       [[PRED_STORE_IF7]]:
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[B]], align 8
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE8]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE8]]:
; TF-UNROLL-NEXT:    [[TMP11:%.*]] = extractelement <4 x i1> [[TMP4]], i32 1
; TF-UNROLL-NEXT:    br i1 [[TMP11]], label %[[PRED_STORE_IF9:.*]], label %[[PRED_STORE_CONTINUE10:.*]]
; TF-UNROLL:       [[PRED_STORE_IF9]]:
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[B]], align 8
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE10]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE10]]:
; TF-UNROLL-NEXT:    [[TMP12:%.*]] = extractelement <4 x i1> [[TMP4]], i32 2
; TF-UNROLL-NEXT:    br i1 [[TMP12]], label %[[PRED_STORE_IF11:.*]], label %[[PRED_STORE_CONTINUE12:.*]]
; TF-UNROLL:       [[PRED_STORE_IF11]]:
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[B]], align 8
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE12]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE12]]:
; TF-UNROLL-NEXT:    [[TMP13:%.*]] = extractelement <4 x i1> [[TMP4]], i32 3
; TF-UNROLL-NEXT:    br i1 [[TMP13]], label %[[PRED_STORE_IF13:.*]], label %[[PRED_STORE_CONTINUE14:.*]]
; TF-UNROLL:       [[PRED_STORE_IF13]]:
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[B]], align 8
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE14]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE14]]:
; TF-UNROLL-NEXT:    [[TMP14:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 0
; TF-UNROLL-NEXT:    br i1 [[TMP14]], label %[[PRED_STORE_IF16:.*]], label %[[FOR_BODY:.*]]
; TF-UNROLL:       [[PRED_STORE_IF16]]:
; TF-UNROLL-NEXT:    [[TMP33:%.*]] = add i64 [[INDEX]], 0
; TF-UNROLL-NEXT:    [[TMP34:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP33]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP34]], align 4
; TF-UNROLL-NEXT:    br label %[[FOR_BODY]]
; TF-UNROLL:       [[FOR_BODY]]:
; TF-UNROLL-NEXT:    [[TMP35:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 1
; TF-UNROLL-NEXT:    br i1 [[TMP35]], label %[[PRED_STORE_IF29:.*]], label %[[PRED_STORE_CONTINUE30:.*]]
; TF-UNROLL:       [[PRED_STORE_IF29]]:
; TF-UNROLL-NEXT:    [[TMP36:%.*]] = add i64 [[INDEX]], 1
; TF-UNROLL-NEXT:    [[TMP37:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP36]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP37]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE30]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE30]]:
; TF-UNROLL-NEXT:    [[TMP19:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 2
; TF-UNROLL-NEXT:    br i1 [[TMP19]], label %[[FOR_END:.*]], label %[[PRED_STORE_CONTINUE21:.*]]
; TF-UNROLL:       [[FOR_END]]:
; TF-UNROLL-NEXT:    [[TMP20:%.*]] = add i64 [[INDEX]], 2
; TF-UNROLL-NEXT:    [[TMP21:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP20]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP21]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE21]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE21]]:
; TF-UNROLL-NEXT:    [[TMP22:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 3
; TF-UNROLL-NEXT:    br i1 [[TMP22]], label %[[PRED_STORE_IF22:.*]], label %[[PRED_STORE_CONTINUE23:.*]]
; TF-UNROLL:       [[PRED_STORE_IF22]]:
; TF-UNROLL-NEXT:    [[TMP23:%.*]] = add i64 [[INDEX]], 3
; TF-UNROLL-NEXT:    [[TMP24:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP23]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP24]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE23]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE23]]:
; TF-UNROLL-NEXT:    [[TMP25:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 0
; TF-UNROLL-NEXT:    br i1 [[TMP25]], label %[[PRED_STORE_IF24:.*]], label %[[PRED_STORE_CONTINUE25:.*]]
; TF-UNROLL:       [[PRED_STORE_IF24]]:
; TF-UNROLL-NEXT:    [[TMP26:%.*]] = add i64 [[INDEX]], 4
; TF-UNROLL-NEXT:    [[TMP27:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP26]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP27]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE25]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE25]]:
; TF-UNROLL-NEXT:    [[TMP28:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 1
; TF-UNROLL-NEXT:    br i1 [[TMP28]], label %[[PRED_STORE_IF26:.*]], label %[[PRED_STORE_CONTINUE27:.*]]
; TF-UNROLL:       [[PRED_STORE_IF26]]:
; TF-UNROLL-NEXT:    [[TMP29:%.*]] = add i64 [[INDEX]], 5
; TF-UNROLL-NEXT:    [[TMP30:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP29]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP30]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE27]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE27]]:
; TF-UNROLL-NEXT:    [[TMP31:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 2
; TF-UNROLL-NEXT:    br i1 [[TMP31]], label %[[PRED_STORE_IF28:.*]], label %[[PRED_STORE_CONTINUE29:.*]]
; TF-UNROLL:       [[PRED_STORE_IF28]]:
; TF-UNROLL-NEXT:    [[TMP32:%.*]] = add i64 [[INDEX]], 6
; TF-UNROLL-NEXT:    [[TMP38:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP32]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP38]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE29]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE29]]:
; TF-UNROLL-NEXT:    [[TMP39:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 3
; TF-UNROLL-NEXT:    br i1 [[TMP39]], label %[[PRED_STORE_IF30:.*]], label %[[PRED_STORE_CONTINUE31]]
; TF-UNROLL:       [[PRED_STORE_IF30]]:
; TF-UNROLL-NEXT:    [[TMP40:%.*]] = add i64 [[INDEX]], 7
; TF-UNROLL-NEXT:    [[TMP41:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP40]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP41]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE31]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE31]]:
; TF-UNROLL-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 8
; TF-UNROLL-NEXT:    [[VEC_IND_NEXT]] = add <4 x i64> [[STEP_ADD]], splat (i64 4)
; TF-UNROLL-NEXT:    [[TMP42:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1032
; TF-UNROLL-NEXT:    br i1 [[TMP42]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP8:![0-9]+]]
; TF-UNROLL:       [[MIDDLE_BLOCK]]:
; TF-UNROLL-NEXT:    br label %[[FOR_END1:.*]]
; TF-UNROLL:       [[FOR_END1]]:
; TF-UNROLL-NEXT:    ret void
;
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %latch ]
  %cmp = icmp ugt i64 %iv, 10
  br i1 %cmp, label %do_store, label %latch
do_store:
  store i64 %v, ptr %b, align 8
  br label %latch
latch:
  %arrayidx = getelementptr inbounds i64, ptr %a, i64 %iv
  store i64 %v, ptr %arrayidx
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, 1025
  br i1 %exitcond.not, label %for.end, label %for.body

for.end:
  ret void
}


define void @uniform_store_unaligned(ptr noalias nocapture %a, ptr noalias nocapture %b, i64 %v, i64 %n) {
; CHECK-LABEL: define void @uniform_store_unaligned(
; CHECK-SAME: ptr noalias captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i64 [[V:%.*]], i64 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    br label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[BROADCAST_SPLATINSERT:%.*]] = insertelement <4 x i64> poison, i64 [[V]], i64 0
; CHECK-NEXT:    [[BROADCAST_SPLAT:%.*]] = shufflevector <4 x i64> [[BROADCAST_SPLATINSERT]], <4 x i64> poison, <4 x i32> zeroinitializer
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    store i64 [[V]], ptr [[B]], align 1
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[INDEX]]
; CHECK-NEXT:    store <4 x i64> [[BROADCAST_SPLAT]], ptr [[TMP0]], align 4
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; CHECK-NEXT:    br i1 [[TMP1]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP16:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    br label %[[SCALAR_PH:.*]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i64 [ 1024, %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    store i64 [[V]], ptr [[B]], align 1
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[IV]]
; CHECK-NEXT:    store i64 [[V]], ptr [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add nuw nsw i64 [[IV]], 1
; CHECK-NEXT:    [[EXITCOND_NOT:%.*]] = icmp eq i64 [[IV_NEXT]], 1025
; CHECK-NEXT:    br i1 [[EXITCOND_NOT]], label %[[FOR_END:.*]], label %[[FOR_BODY]], !llvm.loop [[LOOP17:![0-9]+]]
; CHECK:       [[FOR_END]]:
; CHECK-NEXT:    ret void
;
; TF-LABEL: define void @uniform_store_unaligned(
; TF-SAME: ptr noalias captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i64 [[V:%.*]], i64 [[N:%.*]]) {
; TF-NEXT:  [[ENTRY:.*:]]
; TF-NEXT:    br label %[[VECTOR_PH:.*]]
; TF:       [[VECTOR_PH]]:
; TF-NEXT:    br label %[[VECTOR_BODY:.*]]
; TF:       [[VECTOR_BODY]]:
; TF-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[FOR_END:.*]] ]
; TF-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i64(i64 [[INDEX]], i64 1025)
; TF-NEXT:    store i64 [[V]], ptr [[B]], align 1
; TF-NEXT:    [[TMP0:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 0
; TF-NEXT:    br i1 [[TMP0]], label %[[PRED_STORE_IF:.*]], label %[[PRED_STORE_IF1:.*]]
; TF:       [[PRED_STORE_IF]]:
; TF-NEXT:    [[TMP2:%.*]] = add i64 [[INDEX]], 0
; TF-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP2]]
; TF-NEXT:    store i64 [[V]], ptr [[TMP3]], align 4
; TF-NEXT:    br label %[[PRED_STORE_IF1]]
; TF:       [[PRED_STORE_IF1]]:
; TF-NEXT:    [[TMP10:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 1
; TF-NEXT:    br i1 [[TMP10]], label %[[PRED_STORE_IF2:.*]], label %[[PRED_STORE_CONTINUE2:.*]]
; TF:       [[PRED_STORE_IF2]]:
; TF-NEXT:    [[TMP4:%.*]] = add i64 [[INDEX]], 1
; TF-NEXT:    [[TMP5:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP4]]
; TF-NEXT:    store i64 [[V]], ptr [[TMP5]], align 4
; TF-NEXT:    br label %[[PRED_STORE_CONTINUE2]]
; TF:       [[PRED_STORE_CONTINUE2]]:
; TF-NEXT:    [[TMP6:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 2
; TF-NEXT:    br i1 [[TMP6]], label %[[PRED_STORE_IF3:.*]], label %[[PRED_STORE_CONTINUE4:.*]]
; TF:       [[PRED_STORE_IF3]]:
; TF-NEXT:    [[TMP7:%.*]] = add i64 [[INDEX]], 2
; TF-NEXT:    [[TMP8:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP7]]
; TF-NEXT:    store i64 [[V]], ptr [[TMP8]], align 4
; TF-NEXT:    br label %[[PRED_STORE_CONTINUE4]]
; TF:       [[PRED_STORE_CONTINUE4]]:
; TF-NEXT:    [[TMP9:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 3
; TF-NEXT:    br i1 [[TMP9]], label %[[PRED_STORE_IF5:.*]], label %[[FOR_END]]
; TF:       [[PRED_STORE_IF5]]:
; TF-NEXT:    [[TMP11:%.*]] = add i64 [[INDEX]], 3
; TF-NEXT:    [[TMP12:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP11]]
; TF-NEXT:    store i64 [[V]], ptr [[TMP12]], align 4
; TF-NEXT:    br label %[[FOR_END]]
; TF:       [[FOR_END]]:
; TF-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 4
; TF-NEXT:    [[TMP13:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1028
; TF-NEXT:    br i1 [[TMP13]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP9:![0-9]+]]
; TF:       [[MIDDLE_BLOCK]]:
; TF-NEXT:    br label %[[FOR_END1:.*]]
; TF:       [[FOR_END1]]:
; TF-NEXT:    ret void
;
; TF-UNROLL-LABEL: define void @uniform_store_unaligned(
; TF-UNROLL-SAME: ptr noalias captures(none) [[A:%.*]], ptr noalias captures(none) [[B:%.*]], i64 [[V:%.*]], i64 [[N:%.*]]) {
; TF-UNROLL-NEXT:  [[ENTRY:.*:]]
; TF-UNROLL-NEXT:    br label %[[VECTOR_PH:.*]]
; TF-UNROLL:       [[VECTOR_PH]]:
; TF-UNROLL-NEXT:    br label %[[VECTOR_BODY:.*]]
; TF-UNROLL:       [[VECTOR_BODY]]:
; TF-UNROLL-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[PRED_STORE_CONTINUE15:.*]] ]
; TF-UNROLL-NEXT:    [[TMP0:%.*]] = add i64 [[INDEX]], 4
; TF-UNROLL-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i64(i64 [[INDEX]], i64 1025)
; TF-UNROLL-NEXT:    [[ACTIVE_LANE_MASK1:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i64(i64 [[TMP0]], i64 1025)
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[B]], align 1
; TF-UNROLL-NEXT:    [[TMP1:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 0
; TF-UNROLL-NEXT:    br i1 [[TMP1]], label %[[PRED_STORE_IF:.*]], label %[[PRED_STORE_IF9:.*]]
; TF-UNROLL:       [[PRED_STORE_IF]]:
; TF-UNROLL-NEXT:    [[TMP15:%.*]] = add i64 [[INDEX]], 0
; TF-UNROLL-NEXT:    [[TMP16:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP15]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP16]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_IF9]]
; TF-UNROLL:       [[PRED_STORE_IF9]]:
; TF-UNROLL-NEXT:    [[TMP4:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 1
; TF-UNROLL-NEXT:    br i1 [[TMP4]], label %[[PRED_STORE_IF2:.*]], label %[[PRED_STORE_CONTINUE10:.*]]
; TF-UNROLL:       [[PRED_STORE_IF2]]:
; TF-UNROLL-NEXT:    [[TMP5:%.*]] = add i64 [[INDEX]], 1
; TF-UNROLL-NEXT:    [[TMP6:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP5]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP6]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE10]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE10]]:
; TF-UNROLL-NEXT:    [[TMP7:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 2
; TF-UNROLL-NEXT:    br i1 [[TMP7]], label %[[PRED_STORE_IF4:.*]], label %[[PRED_STORE_CONTINUE12:.*]]
; TF-UNROLL:       [[PRED_STORE_IF4]]:
; TF-UNROLL-NEXT:    [[TMP8:%.*]] = add i64 [[INDEX]], 2
; TF-UNROLL-NEXT:    [[TMP9:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP8]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP9]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE12]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE12]]:
; TF-UNROLL-NEXT:    [[TMP10:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 3
; TF-UNROLL-NEXT:    br i1 [[TMP10]], label %[[PRED_STORE_IF6:.*]], label %[[FOR_END:.*]]
; TF-UNROLL:       [[PRED_STORE_IF6]]:
; TF-UNROLL-NEXT:    [[TMP24:%.*]] = add i64 [[INDEX]], 3
; TF-UNROLL-NEXT:    [[TMP25:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP24]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP25]], align 4
; TF-UNROLL-NEXT:    br label %[[FOR_END]]
; TF-UNROLL:       [[FOR_END]]:
; TF-UNROLL-NEXT:    [[TMP13:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 0
; TF-UNROLL-NEXT:    br i1 [[TMP13]], label %[[PRED_STORE_IF8:.*]], label %[[PRED_STORE_CONTINUE9:.*]]
; TF-UNROLL:       [[PRED_STORE_IF8]]:
; TF-UNROLL-NEXT:    [[TMP14:%.*]] = add i64 [[INDEX]], 4
; TF-UNROLL-NEXT:    [[TMP26:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP14]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP26]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE9]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE9]]:
; TF-UNROLL-NEXT:    [[TMP27:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 1
; TF-UNROLL-NEXT:    br i1 [[TMP27]], label %[[PRED_STORE_IF10:.*]], label %[[PRED_STORE_CONTINUE11:.*]]
; TF-UNROLL:       [[PRED_STORE_IF10]]:
; TF-UNROLL-NEXT:    [[TMP17:%.*]] = add i64 [[INDEX]], 5
; TF-UNROLL-NEXT:    [[TMP18:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP17]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP18]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE11]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE11]]:
; TF-UNROLL-NEXT:    [[TMP19:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 2
; TF-UNROLL-NEXT:    br i1 [[TMP19]], label %[[PRED_STORE_IF12:.*]], label %[[PRED_STORE_CONTINUE13:.*]]
; TF-UNROLL:       [[PRED_STORE_IF12]]:
; TF-UNROLL-NEXT:    [[TMP20:%.*]] = add i64 [[INDEX]], 6
; TF-UNROLL-NEXT:    [[TMP21:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP20]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP21]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE13]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE13]]:
; TF-UNROLL-NEXT:    [[TMP22:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK1]], i32 3
; TF-UNROLL-NEXT:    br i1 [[TMP22]], label %[[PRED_STORE_IF14:.*]], label %[[PRED_STORE_CONTINUE15]]
; TF-UNROLL:       [[PRED_STORE_IF14]]:
; TF-UNROLL-NEXT:    [[TMP23:%.*]] = add i64 [[INDEX]], 7
; TF-UNROLL-NEXT:    [[TMP28:%.*]] = getelementptr inbounds i64, ptr [[A]], i64 [[TMP23]]
; TF-UNROLL-NEXT:    store i64 [[V]], ptr [[TMP28]], align 4
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE15]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE15]]:
; TF-UNROLL-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 8
; TF-UNROLL-NEXT:    [[TMP29:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1032
; TF-UNROLL-NEXT:    br i1 [[TMP29]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP9:![0-9]+]]
; TF-UNROLL:       [[MIDDLE_BLOCK]]:
; TF-UNROLL-NEXT:    br label %[[FOR_END1:.*]]
; TF-UNROLL:       [[FOR_END1]]:
; TF-UNROLL-NEXT:    ret void
;
entry:
  br label %for.body

for.body:
  %iv = phi i64 [ 0, %entry ], [ %iv.next, %for.body ]
  store i64 %v, ptr %b, align 1
  %arrayidx = getelementptr inbounds i64, ptr %a, i64 %iv
  store i64 %v, ptr %arrayidx
  %iv.next = add nuw nsw i64 %iv, 1
  %exitcond.not = icmp eq i64 %iv.next, 1025
  br i1 %exitcond.not, label %for.end, label %for.body

for.end:
  ret void
}

define void @uniform_load_store(ptr %p, ptr %q, i32 %n) {
; CHECK-LABEL: define void @uniform_load_store(
; CHECK-SAME: ptr [[P:%.*]], ptr [[Q:%.*]], i32 [[N:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[MIN_ITERS_CHECK:%.*]] = icmp ult i32 [[N]], 4
; CHECK-NEXT:    br i1 [[MIN_ITERS_CHECK]], label %[[SCALAR_PH:.*]], label %[[VECTOR_SCEVCHECK:.*]]
; CHECK:       [[VECTOR_SCEVCHECK]]:
; CHECK-NEXT:    [[TMP0:%.*]] = add i32 [[N]], -1
; CHECK-NEXT:    [[TMP1:%.*]] = icmp slt i32 [[TMP0]], 0
; CHECK-NEXT:    br i1 [[TMP1]], label %[[SCALAR_PH]], label %[[VECTOR_MEMCHECK:.*]]
; CHECK:       [[VECTOR_MEMCHECK]]:
; CHECK-NEXT:    [[SCEVGEP:%.*]] = getelementptr i8, ptr [[Q]], i64 4
; CHECK-NEXT:    [[TMP2:%.*]] = add i32 [[N]], -1
; CHECK-NEXT:    [[TMP3:%.*]] = zext i32 [[TMP2]] to i64
; CHECK-NEXT:    [[TMP4:%.*]] = shl nuw nsw i64 [[TMP3]], 2
; CHECK-NEXT:    [[TMP5:%.*]] = add nuw nsw i64 [[TMP4]], 4
; CHECK-NEXT:    [[SCEVGEP1:%.*]] = getelementptr i8, ptr [[P]], i64 [[TMP5]]
; CHECK-NEXT:    [[BOUND0:%.*]] = icmp ult ptr [[Q]], [[SCEVGEP1]]
; CHECK-NEXT:    [[BOUND1:%.*]] = icmp ult ptr [[P]], [[SCEVGEP]]
; CHECK-NEXT:    [[FOUND_CONFLICT:%.*]] = and i1 [[BOUND0]], [[BOUND1]]
; CHECK-NEXT:    br i1 [[FOUND_CONFLICT]], label %[[SCALAR_PH]], label %[[VECTOR_PH:.*]]
; CHECK:       [[VECTOR_PH]]:
; CHECK-NEXT:    [[N_MOD_VF:%.*]] = urem i32 [[N]], 4
; CHECK-NEXT:    [[N_VEC:%.*]] = sub i32 [[N]], [[N_MOD_VF]]
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i32 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i32, ptr [[P]], i32 [[INDEX]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <4 x i32>, ptr [[TMP6]], align 4, !alias.scope [[META18:![0-9]+]]
; CHECK-NEXT:    [[TMP7:%.*]] = add <4 x i32> [[WIDE_LOAD]], splat (i32 1)
; CHECK-NEXT:    store <4 x i32> [[TMP7]], ptr [[TMP6]], align 4, !alias.scope [[META18]]
; CHECK-NEXT:    [[TMP8:%.*]] = extractelement <4 x i32> [[TMP7]], i32 3
; CHECK-NEXT:    store i32 [[TMP8]], ptr [[Q]], align 4, !alias.scope [[META21:![0-9]+]], !noalias [[META18]]
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i32 [[INDEX]], 4
; CHECK-NEXT:    [[TMP9:%.*]] = icmp eq i32 [[INDEX_NEXT]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[TMP9]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP23:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[CMP_N:%.*]] = icmp eq i32 [[N]], [[N_VEC]]
; CHECK-NEXT:    br i1 [[CMP_N]], label %[[EXIT:.*]], label %[[SCALAR_PH]]
; CHECK:       [[SCALAR_PH]]:
; CHECK-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i32 [ [[N_VEC]], %[[MIDDLE_BLOCK]] ], [ 0, %[[ENTRY]] ], [ 0, %[[VECTOR_SCEVCHECK]] ], [ 0, %[[VECTOR_MEMCHECK]] ]
; CHECK-NEXT:    br label %[[LOOP:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[IV:%.*]] = phi i32 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; CHECK-NEXT:    [[GEP:%.*]] = getelementptr i32, ptr [[P]], i32 [[IV]]
; CHECK-NEXT:    [[X:%.*]] = load i32, ptr [[GEP]], align 4
; CHECK-NEXT:    [[Y:%.*]] = add i32 [[X]], 1
; CHECK-NEXT:    store i32 [[Y]], ptr [[GEP]], align 4
; CHECK-NEXT:    store i32 [[Y]], ptr [[Q]], align 4
; CHECK-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; CHECK-NEXT:    [[DONE:%.*]] = icmp eq i32 [[IV_NEXT]], [[N]]
; CHECK-NEXT:    br i1 [[DONE]], label %[[EXIT]], label %[[LOOP]], !llvm.loop [[LOOP24:![0-9]+]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    ret void
;
; TF-LABEL: define void @uniform_load_store(
; TF-SAME: ptr [[P:%.*]], ptr [[Q:%.*]], i32 [[N:%.*]]) {
; TF-NEXT:  [[ENTRY:.*:]]
; TF-NEXT:    br label %[[VECTOR_SCEVCHECK:.*]]
; TF:       [[VECTOR_SCEVCHECK]]:
; TF-NEXT:    [[TMP0:%.*]] = add i32 [[N]], -1
; TF-NEXT:    [[TMP1:%.*]] = icmp slt i32 [[TMP0]], 0
; TF-NEXT:    br i1 [[TMP1]], label %[[SCALAR_PH:.*]], label %[[VECTOR_MEMCHECK:.*]]
; TF:       [[VECTOR_MEMCHECK]]:
; TF-NEXT:    [[SCEVGEP:%.*]] = getelementptr i8, ptr [[Q]], i64 4
; TF-NEXT:    [[TMP2:%.*]] = add i32 [[N]], -1
; TF-NEXT:    [[TMP3:%.*]] = zext i32 [[TMP2]] to i64
; TF-NEXT:    [[TMP4:%.*]] = shl nuw nsw i64 [[TMP3]], 2
; TF-NEXT:    [[TMP5:%.*]] = add nuw nsw i64 [[TMP4]], 4
; TF-NEXT:    [[SCEVGEP1:%.*]] = getelementptr i8, ptr [[P]], i64 [[TMP5]]
; TF-NEXT:    [[BOUND0:%.*]] = icmp ult ptr [[Q]], [[SCEVGEP1]]
; TF-NEXT:    [[BOUND1:%.*]] = icmp ult ptr [[P]], [[SCEVGEP]]
; TF-NEXT:    [[FOUND_CONFLICT:%.*]] = and i1 [[BOUND0]], [[BOUND1]]
; TF-NEXT:    br i1 [[FOUND_CONFLICT]], label %[[SCALAR_PH]], label %[[VECTOR_PH:.*]]
; TF:       [[VECTOR_PH]]:
; TF-NEXT:    [[N_RND_UP:%.*]] = add i32 [[N]], 3
; TF-NEXT:    [[N_MOD_VF:%.*]] = urem i32 [[N_RND_UP]], 4
; TF-NEXT:    [[N_VEC:%.*]] = sub i32 [[N_RND_UP]], [[N_MOD_VF]]
; TF-NEXT:    br label %[[VECTOR_BODY:.*]]
; TF:       [[VECTOR_BODY]]:
; TF-NEXT:    [[INDEX:%.*]] = phi i32 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[PRED_STORE_CONTINUE13:.*]] ]
; TF-NEXT:    [[TMP9:%.*]] = add i32 [[INDEX]], 0
; TF-NEXT:    [[TMP7:%.*]] = add i32 [[INDEX]], 1
; TF-NEXT:    [[TMP8:%.*]] = add i32 [[INDEX]], 2
; TF-NEXT:    [[TMP10:%.*]] = add i32 [[INDEX]], 3
; TF-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i32(i32 [[TMP9]], i32 [[N]])
; TF-NEXT:    [[TMP14:%.*]] = getelementptr i32, ptr [[P]], i32 [[TMP9]]
; TF-NEXT:    [[TMP11:%.*]] = getelementptr i32, ptr [[P]], i32 [[TMP7]]
; TF-NEXT:    [[TMP12:%.*]] = getelementptr i32, ptr [[P]], i32 [[TMP8]]
; TF-NEXT:    [[TMP13:%.*]] = getelementptr i32, ptr [[P]], i32 [[TMP10]]
; TF-NEXT:    [[TMP33:%.*]] = insertelement <4 x ptr> poison, ptr [[TMP14]], i32 0
; TF-NEXT:    [[TMP15:%.*]] = insertelement <4 x ptr> [[TMP33]], ptr [[TMP11]], i32 1
; TF-NEXT:    [[TMP16:%.*]] = insertelement <4 x ptr> [[TMP15]], ptr [[TMP12]], i32 2
; TF-NEXT:    [[TMP17:%.*]] = insertelement <4 x ptr> [[TMP16]], ptr [[TMP13]], i32 3
; TF-NEXT:    [[TMP18:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 0
; TF-NEXT:    br i1 [[TMP18]], label %[[PRED_LOAD_IF:.*]], label %[[PRED_LOAD_CONTINUE:.*]]
; TF:       [[PRED_LOAD_IF]]:
; TF-NEXT:    [[TMP19:%.*]] = load i32, ptr [[TMP14]], align 4, !alias.scope [[META10:![0-9]+]]
; TF-NEXT:    [[TMP20:%.*]] = insertelement <4 x i32> poison, i32 [[TMP19]], i32 0
; TF-NEXT:    br label %[[PRED_LOAD_CONTINUE]]
; TF:       [[PRED_LOAD_CONTINUE]]:
; TF-NEXT:    [[TMP21:%.*]] = phi <4 x i32> [ poison, %[[VECTOR_BODY]] ], [ [[TMP20]], %[[PRED_LOAD_IF]] ]
; TF-NEXT:    [[TMP22:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 1
; TF-NEXT:    br i1 [[TMP22]], label %[[PRED_LOAD_IF2:.*]], label %[[PRED_LOAD_CONTINUE3:.*]]
; TF:       [[PRED_LOAD_IF2]]:
; TF-NEXT:    [[TMP23:%.*]] = load i32, ptr [[TMP11]], align 4, !alias.scope [[META10]]
; TF-NEXT:    [[TMP24:%.*]] = insertelement <4 x i32> [[TMP21]], i32 [[TMP23]], i32 1
; TF-NEXT:    br label %[[PRED_LOAD_CONTINUE3]]
; TF:       [[PRED_LOAD_CONTINUE3]]:
; TF-NEXT:    [[TMP25:%.*]] = phi <4 x i32> [ [[TMP21]], %[[PRED_LOAD_CONTINUE]] ], [ [[TMP24]], %[[PRED_LOAD_IF2]] ]
; TF-NEXT:    [[TMP26:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 2
; TF-NEXT:    br i1 [[TMP26]], label %[[PRED_LOAD_IF4:.*]], label %[[PRED_LOAD_CONTINUE5:.*]]
; TF:       [[PRED_LOAD_IF4]]:
; TF-NEXT:    [[TMP27:%.*]] = load i32, ptr [[TMP12]], align 4, !alias.scope [[META10]]
; TF-NEXT:    [[TMP28:%.*]] = insertelement <4 x i32> [[TMP25]], i32 [[TMP27]], i32 2
; TF-NEXT:    br label %[[PRED_LOAD_CONTINUE5]]
; TF:       [[PRED_LOAD_CONTINUE5]]:
; TF-NEXT:    [[TMP29:%.*]] = phi <4 x i32> [ [[TMP25]], %[[PRED_LOAD_CONTINUE3]] ], [ [[TMP28]], %[[PRED_LOAD_IF4]] ]
; TF-NEXT:    [[TMP30:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 3
; TF-NEXT:    br i1 [[TMP30]], label %[[PRED_LOAD_IF6:.*]], label %[[PRED_LOAD_CONTINUE7:.*]]
; TF:       [[PRED_LOAD_IF6]]:
; TF-NEXT:    [[TMP31:%.*]] = load i32, ptr [[TMP13]], align 4, !alias.scope [[META10]]
; TF-NEXT:    [[TMP32:%.*]] = insertelement <4 x i32> [[TMP29]], i32 [[TMP31]], i32 3
; TF-NEXT:    br label %[[PRED_LOAD_CONTINUE7]]
; TF:       [[PRED_LOAD_CONTINUE7]]:
; TF-NEXT:    [[TMP34:%.*]] = phi <4 x i32> [ [[TMP29]], %[[PRED_LOAD_CONTINUE5]] ], [ [[TMP32]], %[[PRED_LOAD_IF6]] ]
; TF-NEXT:    [[TMP35:%.*]] = add <4 x i32> [[TMP34]], splat (i32 1)
; TF-NEXT:    [[TMP45:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 0
; TF-NEXT:    br i1 [[TMP45]], label %[[PRED_STORE_IF:.*]], label %[[PRED_STORE_CONTINUE:.*]]
; TF:       [[PRED_STORE_IF]]:
; TF-NEXT:    [[TMP36:%.*]] = extractelement <4 x i32> [[TMP35]], i32 0
; TF-NEXT:    store i32 [[TMP36]], ptr [[TMP14]], align 4, !alias.scope [[META10]]
; TF-NEXT:    [[TMP37:%.*]] = extractelement <4 x i32> [[TMP35]], i32 0
; TF-NEXT:    store i32 [[TMP37]], ptr [[Q]], align 4, !alias.scope [[META13:![0-9]+]], !noalias [[META10]]
; TF-NEXT:    br label %[[PRED_STORE_CONTINUE]]
; TF:       [[PRED_STORE_CONTINUE]]:
; TF-NEXT:    [[TMP38:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 1
; TF-NEXT:    br i1 [[TMP38]], label %[[PRED_STORE_IF8:.*]], label %[[PRED_STORE_CONTINUE9:.*]]
; TF:       [[PRED_STORE_IF8]]:
; TF-NEXT:    [[TMP39:%.*]] = extractelement <4 x i32> [[TMP35]], i32 1
; TF-NEXT:    store i32 [[TMP39]], ptr [[TMP11]], align 4, !alias.scope [[META10]]
; TF-NEXT:    [[TMP40:%.*]] = extractelement <4 x i32> [[TMP35]], i32 1
; TF-NEXT:    store i32 [[TMP40]], ptr [[Q]], align 4, !alias.scope [[META13]], !noalias [[META10]]
; TF-NEXT:    br label %[[PRED_STORE_CONTINUE9]]
; TF:       [[PRED_STORE_CONTINUE9]]:
; TF-NEXT:    [[TMP41:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 2
; TF-NEXT:    br i1 [[TMP41]], label %[[PRED_STORE_IF10:.*]], label %[[PRED_STORE_CONTINUE11:.*]]
; TF:       [[PRED_STORE_IF10]]:
; TF-NEXT:    [[TMP42:%.*]] = extractelement <4 x i32> [[TMP35]], i32 2
; TF-NEXT:    store i32 [[TMP42]], ptr [[TMP12]], align 4, !alias.scope [[META10]]
; TF-NEXT:    [[TMP43:%.*]] = extractelement <4 x i32> [[TMP35]], i32 2
; TF-NEXT:    store i32 [[TMP43]], ptr [[Q]], align 4, !alias.scope [[META13]], !noalias [[META10]]
; TF-NEXT:    br label %[[PRED_STORE_CONTINUE11]]
; TF:       [[PRED_STORE_CONTINUE11]]:
; TF-NEXT:    [[TMP44:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 3
; TF-NEXT:    br i1 [[TMP44]], label %[[PRED_STORE_IF12:.*]], label %[[PRED_STORE_CONTINUE13]]
; TF:       [[PRED_STORE_IF12]]:
; TF-NEXT:    [[TMP47:%.*]] = extractelement <4 x i32> [[TMP35]], i32 3
; TF-NEXT:    store i32 [[TMP47]], ptr [[TMP13]], align 4, !alias.scope [[META10]]
; TF-NEXT:    [[TMP46:%.*]] = extractelement <4 x i32> [[TMP35]], i32 3
; TF-NEXT:    store i32 [[TMP46]], ptr [[Q]], align 4, !alias.scope [[META13]], !noalias [[META10]]
; TF-NEXT:    br label %[[PRED_STORE_CONTINUE13]]
; TF:       [[PRED_STORE_CONTINUE13]]:
; TF-NEXT:    [[INDEX_NEXT]] = add i32 [[INDEX]], 4
; TF-NEXT:    [[TMP48:%.*]] = icmp eq i32 [[INDEX_NEXT]], [[N_VEC]]
; TF-NEXT:    br i1 [[TMP48]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP15:![0-9]+]]
; TF:       [[MIDDLE_BLOCK]]:
; TF-NEXT:    br label %[[EXIT:.*]]
; TF:       [[SCALAR_PH]]:
; TF-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i32 [ 0, %[[VECTOR_SCEVCHECK]] ], [ 0, %[[VECTOR_MEMCHECK]] ]
; TF-NEXT:    br label %[[LOOP:.*]]
; TF:       [[LOOP]]:
; TF-NEXT:    [[IV:%.*]] = phi i32 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP]] ]
; TF-NEXT:    [[GEP:%.*]] = getelementptr i32, ptr [[P]], i32 [[IV]]
; TF-NEXT:    [[X:%.*]] = load i32, ptr [[GEP]], align 4
; TF-NEXT:    [[Y:%.*]] = add i32 [[X]], 1
; TF-NEXT:    store i32 [[Y]], ptr [[GEP]], align 4
; TF-NEXT:    store i32 [[Y]], ptr [[Q]], align 4
; TF-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; TF-NEXT:    [[DONE:%.*]] = icmp eq i32 [[IV_NEXT]], [[N]]
; TF-NEXT:    br i1 [[DONE]], label %[[EXIT]], label %[[LOOP]], !llvm.loop [[LOOP16:![0-9]+]]
; TF:       [[EXIT]]:
; TF-NEXT:    ret void
;
; TF-UNROLL-LABEL: define void @uniform_load_store(
; TF-UNROLL-SAME: ptr [[P:%.*]], ptr [[Q:%.*]], i32 [[N:%.*]]) {
; TF-UNROLL-NEXT:  [[ENTRY:.*:]]
; TF-UNROLL-NEXT:    br label %[[VECTOR_SCEVCHECK:.*]]
; TF-UNROLL:       [[VECTOR_SCEVCHECK]]:
; TF-UNROLL-NEXT:    [[TMP0:%.*]] = add i32 [[N]], -1
; TF-UNROLL-NEXT:    [[TMP1:%.*]] = icmp slt i32 [[TMP0]], 0
; TF-UNROLL-NEXT:    br i1 [[TMP1]], label %[[SCALAR_PH:.*]], label %[[VECTOR_MEMCHECK:.*]]
; TF-UNROLL:       [[VECTOR_MEMCHECK]]:
; TF-UNROLL-NEXT:    [[SCEVGEP:%.*]] = getelementptr i8, ptr [[Q]], i64 4
; TF-UNROLL-NEXT:    [[TMP2:%.*]] = add i32 [[N]], -1
; TF-UNROLL-NEXT:    [[TMP3:%.*]] = zext i32 [[TMP2]] to i64
; TF-UNROLL-NEXT:    [[TMP4:%.*]] = shl nuw nsw i64 [[TMP3]], 2
; TF-UNROLL-NEXT:    [[TMP5:%.*]] = add nuw nsw i64 [[TMP4]], 4
; TF-UNROLL-NEXT:    [[SCEVGEP1:%.*]] = getelementptr i8, ptr [[P]], i64 [[TMP5]]
; TF-UNROLL-NEXT:    [[BOUND0:%.*]] = icmp ult ptr [[Q]], [[SCEVGEP1]]
; TF-UNROLL-NEXT:    [[BOUND1:%.*]] = icmp ult ptr [[P]], [[SCEVGEP]]
; TF-UNROLL-NEXT:    [[FOUND_CONFLICT:%.*]] = and i1 [[BOUND0]], [[BOUND1]]
; TF-UNROLL-NEXT:    br i1 [[FOUND_CONFLICT]], label %[[SCALAR_PH]], label %[[VECTOR_PH:.*]]
; TF-UNROLL:       [[VECTOR_PH]]:
; TF-UNROLL-NEXT:    [[N_RND_UP:%.*]] = add i32 [[N]], 7
; TF-UNROLL-NEXT:    [[N_MOD_VF:%.*]] = urem i32 [[N_RND_UP]], 8
; TF-UNROLL-NEXT:    [[N_VEC:%.*]] = sub i32 [[N_RND_UP]], [[N_MOD_VF]]
; TF-UNROLL-NEXT:    br label %[[VECTOR_BODY:.*]]
; TF-UNROLL:       [[VECTOR_BODY]]:
; TF-UNROLL-NEXT:    [[INDEX:%.*]] = phi i32 [ 0, %[[VECTOR_PH]] ], [ [[INDEX_NEXT:%.*]], %[[PRED_STORE_CONTINUE30:.*]] ]
; TF-UNROLL-NEXT:    [[TMP13:%.*]] = add i32 [[INDEX]], 0
; TF-UNROLL-NEXT:    [[TMP7:%.*]] = add i32 [[INDEX]], 1
; TF-UNROLL-NEXT:    [[TMP8:%.*]] = add i32 [[INDEX]], 2
; TF-UNROLL-NEXT:    [[TMP9:%.*]] = add i32 [[INDEX]], 3
; TF-UNROLL-NEXT:    [[TMP10:%.*]] = add i32 [[INDEX]], 4
; TF-UNROLL-NEXT:    [[TMP11:%.*]] = add i32 [[INDEX]], 5
; TF-UNROLL-NEXT:    [[TMP12:%.*]] = add i32 [[INDEX]], 6
; TF-UNROLL-NEXT:    [[TMP14:%.*]] = add i32 [[INDEX]], 7
; TF-UNROLL-NEXT:    [[ACTIVE_LANE_MASK:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i32(i32 [[TMP13]], i32 [[N]])
; TF-UNROLL-NEXT:    [[ACTIVE_LANE_MASK2:%.*]] = call <4 x i1> @llvm.get.active.lane.mask.v4i1.i32(i32 [[TMP10]], i32 [[N]])
; TF-UNROLL-NEXT:    [[TMP27:%.*]] = getelementptr i32, ptr [[P]], i32 [[TMP13]]
; TF-UNROLL-NEXT:    [[TMP15:%.*]] = getelementptr i32, ptr [[P]], i32 [[TMP7]]
; TF-UNROLL-NEXT:    [[TMP16:%.*]] = getelementptr i32, ptr [[P]], i32 [[TMP8]]
; TF-UNROLL-NEXT:    [[TMP17:%.*]] = getelementptr i32, ptr [[P]], i32 [[TMP9]]
; TF-UNROLL-NEXT:    [[TMP18:%.*]] = insertelement <4 x ptr> poison, ptr [[TMP27]], i32 0
; TF-UNROLL-NEXT:    [[TMP19:%.*]] = insertelement <4 x ptr> [[TMP18]], ptr [[TMP15]], i32 1
; TF-UNROLL-NEXT:    [[TMP20:%.*]] = insertelement <4 x ptr> [[TMP19]], ptr [[TMP16]], i32 2
; TF-UNROLL-NEXT:    [[TMP21:%.*]] = insertelement <4 x ptr> [[TMP20]], ptr [[TMP17]], i32 3
; TF-UNROLL-NEXT:    [[TMP22:%.*]] = getelementptr i32, ptr [[P]], i32 [[TMP10]]
; TF-UNROLL-NEXT:    [[TMP23:%.*]] = getelementptr i32, ptr [[P]], i32 [[TMP11]]
; TF-UNROLL-NEXT:    [[TMP24:%.*]] = getelementptr i32, ptr [[P]], i32 [[TMP12]]
; TF-UNROLL-NEXT:    [[TMP25:%.*]] = getelementptr i32, ptr [[P]], i32 [[TMP14]]
; TF-UNROLL-NEXT:    [[TMP26:%.*]] = insertelement <4 x ptr> poison, ptr [[TMP22]], i32 0
; TF-UNROLL-NEXT:    [[TMP45:%.*]] = insertelement <4 x ptr> [[TMP26]], ptr [[TMP23]], i32 1
; TF-UNROLL-NEXT:    [[TMP28:%.*]] = insertelement <4 x ptr> [[TMP45]], ptr [[TMP24]], i32 2
; TF-UNROLL-NEXT:    [[TMP29:%.*]] = insertelement <4 x ptr> [[TMP28]], ptr [[TMP25]], i32 3
; TF-UNROLL-NEXT:    [[TMP30:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 0
; TF-UNROLL-NEXT:    br i1 [[TMP30]], label %[[PRED_LOAD_IF:.*]], label %[[PRED_LOAD_CONTINUE:.*]]
; TF-UNROLL:       [[PRED_LOAD_IF]]:
; TF-UNROLL-NEXT:    [[TMP31:%.*]] = load i32, ptr [[TMP27]], align 4, !alias.scope [[META10:![0-9]+]]
; TF-UNROLL-NEXT:    [[TMP32:%.*]] = insertelement <4 x i32> poison, i32 [[TMP31]], i32 0
; TF-UNROLL-NEXT:    br label %[[PRED_LOAD_CONTINUE]]
; TF-UNROLL:       [[PRED_LOAD_CONTINUE]]:
; TF-UNROLL-NEXT:    [[TMP33:%.*]] = phi <4 x i32> [ poison, %[[VECTOR_BODY]] ], [ [[TMP32]], %[[PRED_LOAD_IF]] ]
; TF-UNROLL-NEXT:    [[TMP34:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 1
; TF-UNROLL-NEXT:    br i1 [[TMP34]], label %[[PRED_LOAD_IF3:.*]], label %[[PRED_LOAD_CONTINUE4:.*]]
; TF-UNROLL:       [[PRED_LOAD_IF3]]:
; TF-UNROLL-NEXT:    [[TMP35:%.*]] = load i32, ptr [[TMP15]], align 4, !alias.scope [[META10]]
; TF-UNROLL-NEXT:    [[TMP36:%.*]] = insertelement <4 x i32> [[TMP33]], i32 [[TMP35]], i32 1
; TF-UNROLL-NEXT:    br label %[[PRED_LOAD_CONTINUE4]]
; TF-UNROLL:       [[PRED_LOAD_CONTINUE4]]:
; TF-UNROLL-NEXT:    [[TMP37:%.*]] = phi <4 x i32> [ [[TMP33]], %[[PRED_LOAD_CONTINUE]] ], [ [[TMP36]], %[[PRED_LOAD_IF3]] ]
; TF-UNROLL-NEXT:    [[TMP38:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 2
; TF-UNROLL-NEXT:    br i1 [[TMP38]], label %[[PRED_LOAD_IF5:.*]], label %[[PRED_LOAD_CONTINUE6:.*]]
; TF-UNROLL:       [[PRED_LOAD_IF5]]:
; TF-UNROLL-NEXT:    [[TMP39:%.*]] = load i32, ptr [[TMP16]], align 4, !alias.scope [[META10]]
; TF-UNROLL-NEXT:    [[TMP40:%.*]] = insertelement <4 x i32> [[TMP37]], i32 [[TMP39]], i32 2
; TF-UNROLL-NEXT:    br label %[[PRED_LOAD_CONTINUE6]]
; TF-UNROLL:       [[PRED_LOAD_CONTINUE6]]:
; TF-UNROLL-NEXT:    [[TMP41:%.*]] = phi <4 x i32> [ [[TMP37]], %[[PRED_LOAD_CONTINUE4]] ], [ [[TMP40]], %[[PRED_LOAD_IF5]] ]
; TF-UNROLL-NEXT:    [[TMP42:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 3
; TF-UNROLL-NEXT:    br i1 [[TMP42]], label %[[PRED_LOAD_IF7:.*]], label %[[PRED_LOAD_CONTINUE8:.*]]
; TF-UNROLL:       [[PRED_LOAD_IF7]]:
; TF-UNROLL-NEXT:    [[TMP43:%.*]] = load i32, ptr [[TMP17]], align 4, !alias.scope [[META10]]
; TF-UNROLL-NEXT:    [[TMP44:%.*]] = insertelement <4 x i32> [[TMP41]], i32 [[TMP43]], i32 3
; TF-UNROLL-NEXT:    br label %[[PRED_LOAD_CONTINUE8]]
; TF-UNROLL:       [[PRED_LOAD_CONTINUE8]]:
; TF-UNROLL-NEXT:    [[TMP47:%.*]] = phi <4 x i32> [ [[TMP41]], %[[PRED_LOAD_CONTINUE6]] ], [ [[TMP44]], %[[PRED_LOAD_IF7]] ]
; TF-UNROLL-NEXT:    [[TMP46:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK2]], i32 0
; TF-UNROLL-NEXT:    br i1 [[TMP46]], label %[[PRED_LOAD_IF9:.*]], label %[[PRED_LOAD_CONTINUE10:.*]]
; TF-UNROLL:       [[PRED_LOAD_IF9]]:
; TF-UNROLL-NEXT:    [[TMP61:%.*]] = load i32, ptr [[TMP22]], align 4, !alias.scope [[META10]]
; TF-UNROLL-NEXT:    [[TMP48:%.*]] = insertelement <4 x i32> poison, i32 [[TMP61]], i32 0
; TF-UNROLL-NEXT:    br label %[[PRED_LOAD_CONTINUE10]]
; TF-UNROLL:       [[PRED_LOAD_CONTINUE10]]:
; TF-UNROLL-NEXT:    [[TMP49:%.*]] = phi <4 x i32> [ poison, %[[PRED_LOAD_CONTINUE8]] ], [ [[TMP48]], %[[PRED_LOAD_IF9]] ]
; TF-UNROLL-NEXT:    [[TMP50:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK2]], i32 1
; TF-UNROLL-NEXT:    br i1 [[TMP50]], label %[[PRED_LOAD_IF11:.*]], label %[[PRED_LOAD_CONTINUE12:.*]]
; TF-UNROLL:       [[PRED_LOAD_IF11]]:
; TF-UNROLL-NEXT:    [[TMP51:%.*]] = load i32, ptr [[TMP23]], align 4, !alias.scope [[META10]]
; TF-UNROLL-NEXT:    [[TMP52:%.*]] = insertelement <4 x i32> [[TMP49]], i32 [[TMP51]], i32 1
; TF-UNROLL-NEXT:    br label %[[PRED_LOAD_CONTINUE12]]
; TF-UNROLL:       [[PRED_LOAD_CONTINUE12]]:
; TF-UNROLL-NEXT:    [[TMP53:%.*]] = phi <4 x i32> [ [[TMP49]], %[[PRED_LOAD_CONTINUE10]] ], [ [[TMP52]], %[[PRED_LOAD_IF11]] ]
; TF-UNROLL-NEXT:    [[TMP54:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK2]], i32 2
; TF-UNROLL-NEXT:    br i1 [[TMP54]], label %[[PRED_LOAD_IF13:.*]], label %[[PRED_LOAD_CONTINUE14:.*]]
; TF-UNROLL:       [[PRED_LOAD_IF13]]:
; TF-UNROLL-NEXT:    [[TMP55:%.*]] = load i32, ptr [[TMP24]], align 4, !alias.scope [[META10]]
; TF-UNROLL-NEXT:    [[TMP56:%.*]] = insertelement <4 x i32> [[TMP53]], i32 [[TMP55]], i32 2
; TF-UNROLL-NEXT:    br label %[[PRED_LOAD_CONTINUE14]]
; TF-UNROLL:       [[PRED_LOAD_CONTINUE14]]:
; TF-UNROLL-NEXT:    [[TMP57:%.*]] = phi <4 x i32> [ [[TMP53]], %[[PRED_LOAD_CONTINUE12]] ], [ [[TMP56]], %[[PRED_LOAD_IF13]] ]
; TF-UNROLL-NEXT:    [[TMP58:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK2]], i32 3
; TF-UNROLL-NEXT:    br i1 [[TMP58]], label %[[PRED_LOAD_IF15:.*]], label %[[PRED_LOAD_CONTINUE16:.*]]
; TF-UNROLL:       [[PRED_LOAD_IF15]]:
; TF-UNROLL-NEXT:    [[TMP59:%.*]] = load i32, ptr [[TMP25]], align 4, !alias.scope [[META10]]
; TF-UNROLL-NEXT:    [[TMP60:%.*]] = insertelement <4 x i32> [[TMP57]], i32 [[TMP59]], i32 3
; TF-UNROLL-NEXT:    br label %[[PRED_LOAD_CONTINUE16]]
; TF-UNROLL:       [[PRED_LOAD_CONTINUE16]]:
; TF-UNROLL-NEXT:    [[TMP63:%.*]] = phi <4 x i32> [ [[TMP57]], %[[PRED_LOAD_CONTINUE14]] ], [ [[TMP60]], %[[PRED_LOAD_IF15]] ]
; TF-UNROLL-NEXT:    [[TMP64:%.*]] = add <4 x i32> [[TMP47]], splat (i32 1)
; TF-UNROLL-NEXT:    [[TMP65:%.*]] = add <4 x i32> [[TMP63]], splat (i32 1)
; TF-UNROLL-NEXT:    [[TMP89:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 0
; TF-UNROLL-NEXT:    br i1 [[TMP89]], label %[[PRED_STORE_IF:.*]], label %[[PRED_STORE_CONTINUE:.*]]
; TF-UNROLL:       [[PRED_STORE_IF]]:
; TF-UNROLL-NEXT:    [[TMP90:%.*]] = extractelement <4 x i32> [[TMP64]], i32 0
; TF-UNROLL-NEXT:    store i32 [[TMP90]], ptr [[TMP27]], align 4, !alias.scope [[META10]]
; TF-UNROLL-NEXT:    [[TMP66:%.*]] = extractelement <4 x i32> [[TMP64]], i32 0
; TF-UNROLL-NEXT:    store i32 [[TMP66]], ptr [[Q]], align 4, !alias.scope [[META13:![0-9]+]], !noalias [[META10]]
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE]]:
; TF-UNROLL-NEXT:    [[TMP67:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 1
; TF-UNROLL-NEXT:    br i1 [[TMP67]], label %[[PRED_STORE_IF17:.*]], label %[[PRED_STORE_CONTINUE18:.*]]
; TF-UNROLL:       [[PRED_STORE_IF17]]:
; TF-UNROLL-NEXT:    [[TMP68:%.*]] = extractelement <4 x i32> [[TMP64]], i32 1
; TF-UNROLL-NEXT:    store i32 [[TMP68]], ptr [[TMP15]], align 4, !alias.scope [[META10]]
; TF-UNROLL-NEXT:    [[TMP69:%.*]] = extractelement <4 x i32> [[TMP64]], i32 1
; TF-UNROLL-NEXT:    store i32 [[TMP69]], ptr [[Q]], align 4, !alias.scope [[META13]], !noalias [[META10]]
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE18]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE18]]:
; TF-UNROLL-NEXT:    [[TMP70:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 2
; TF-UNROLL-NEXT:    br i1 [[TMP70]], label %[[PRED_STORE_IF19:.*]], label %[[PRED_STORE_CONTINUE20:.*]]
; TF-UNROLL:       [[PRED_STORE_IF19]]:
; TF-UNROLL-NEXT:    [[TMP71:%.*]] = extractelement <4 x i32> [[TMP64]], i32 2
; TF-UNROLL-NEXT:    store i32 [[TMP71]], ptr [[TMP16]], align 4, !alias.scope [[META10]]
; TF-UNROLL-NEXT:    [[TMP72:%.*]] = extractelement <4 x i32> [[TMP64]], i32 2
; TF-UNROLL-NEXT:    store i32 [[TMP72]], ptr [[Q]], align 4, !alias.scope [[META13]], !noalias [[META10]]
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE20]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE20]]:
; TF-UNROLL-NEXT:    [[TMP73:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK]], i32 3
; TF-UNROLL-NEXT:    br i1 [[TMP73]], label %[[PRED_STORE_IF21:.*]], label %[[MIDDLE_BLOCK:.*]]
; TF-UNROLL:       [[PRED_STORE_IF21]]:
; TF-UNROLL-NEXT:    [[TMP74:%.*]] = extractelement <4 x i32> [[TMP64]], i32 3
; TF-UNROLL-NEXT:    store i32 [[TMP74]], ptr [[TMP17]], align 4, !alias.scope [[META10]]
; TF-UNROLL-NEXT:    [[TMP75:%.*]] = extractelement <4 x i32> [[TMP64]], i32 3
; TF-UNROLL-NEXT:    store i32 [[TMP75]], ptr [[Q]], align 4, !alias.scope [[META13]], !noalias [[META10]]
; TF-UNROLL-NEXT:    br label %[[MIDDLE_BLOCK]]
; TF-UNROLL:       [[MIDDLE_BLOCK]]:
; TF-UNROLL-NEXT:    [[TMP76:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK2]], i32 0
; TF-UNROLL-NEXT:    br i1 [[TMP76]], label %[[PRED_STORE_IF23:.*]], label %[[LOOP:.*]]
; TF-UNROLL:       [[PRED_STORE_IF23]]:
; TF-UNROLL-NEXT:    [[TMP77:%.*]] = extractelement <4 x i32> [[TMP65]], i32 0
; TF-UNROLL-NEXT:    store i32 [[TMP77]], ptr [[TMP22]], align 4, !alias.scope [[META10]]
; TF-UNROLL-NEXT:    [[TMP78:%.*]] = extractelement <4 x i32> [[TMP65]], i32 0
; TF-UNROLL-NEXT:    store i32 [[TMP78]], ptr [[Q]], align 4, !alias.scope [[META13]], !noalias [[META10]]
; TF-UNROLL-NEXT:    br label %[[LOOP]]
; TF-UNROLL:       [[LOOP]]:
; TF-UNROLL-NEXT:    [[TMP79:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK2]], i32 1
; TF-UNROLL-NEXT:    br i1 [[TMP79]], label %[[PRED_STORE_IF25:.*]], label %[[PRED_STORE_CONTINUE26:.*]]
; TF-UNROLL:       [[PRED_STORE_IF25]]:
; TF-UNROLL-NEXT:    [[TMP80:%.*]] = extractelement <4 x i32> [[TMP65]], i32 1
; TF-UNROLL-NEXT:    store i32 [[TMP80]], ptr [[TMP23]], align 4, !alias.scope [[META10]]
; TF-UNROLL-NEXT:    [[TMP81:%.*]] = extractelement <4 x i32> [[TMP65]], i32 1
; TF-UNROLL-NEXT:    store i32 [[TMP81]], ptr [[Q]], align 4, !alias.scope [[META13]], !noalias [[META10]]
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE26]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE26]]:
; TF-UNROLL-NEXT:    [[TMP82:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK2]], i32 2
; TF-UNROLL-NEXT:    br i1 [[TMP82]], label %[[PRED_STORE_IF27:.*]], label %[[PRED_STORE_CONTINUE28:.*]]
; TF-UNROLL:       [[PRED_STORE_IF27]]:
; TF-UNROLL-NEXT:    [[TMP83:%.*]] = extractelement <4 x i32> [[TMP65]], i32 2
; TF-UNROLL-NEXT:    store i32 [[TMP83]], ptr [[TMP24]], align 4, !alias.scope [[META10]]
; TF-UNROLL-NEXT:    [[TMP84:%.*]] = extractelement <4 x i32> [[TMP65]], i32 2
; TF-UNROLL-NEXT:    store i32 [[TMP84]], ptr [[Q]], align 4, !alias.scope [[META13]], !noalias [[META10]]
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE28]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE28]]:
; TF-UNROLL-NEXT:    [[TMP85:%.*]] = extractelement <4 x i1> [[ACTIVE_LANE_MASK2]], i32 3
; TF-UNROLL-NEXT:    br i1 [[TMP85]], label %[[PRED_STORE_IF29:.*]], label %[[PRED_STORE_CONTINUE30]]
; TF-UNROLL:       [[PRED_STORE_IF29]]:
; TF-UNROLL-NEXT:    [[TMP86:%.*]] = extractelement <4 x i32> [[TMP65]], i32 3
; TF-UNROLL-NEXT:    store i32 [[TMP86]], ptr [[TMP25]], align 4, !alias.scope [[META10]]
; TF-UNROLL-NEXT:    [[TMP87:%.*]] = extractelement <4 x i32> [[TMP65]], i32 3
; TF-UNROLL-NEXT:    store i32 [[TMP87]], ptr [[Q]], align 4, !alias.scope [[META13]], !noalias [[META10]]
; TF-UNROLL-NEXT:    br label %[[PRED_STORE_CONTINUE30]]
; TF-UNROLL:       [[PRED_STORE_CONTINUE30]]:
; TF-UNROLL-NEXT:    [[INDEX_NEXT]] = add i32 [[INDEX]], 8
; TF-UNROLL-NEXT:    [[TMP88:%.*]] = icmp eq i32 [[INDEX_NEXT]], [[N_VEC]]
; TF-UNROLL-NEXT:    br i1 [[TMP88]], label %[[MIDDLE_BLOCK1:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP15:![0-9]+]]
; TF-UNROLL:       [[MIDDLE_BLOCK1]]:
; TF-UNROLL-NEXT:    br label %[[EXIT:.*]]
; TF-UNROLL:       [[SCALAR_PH]]:
; TF-UNROLL-NEXT:    [[BC_RESUME_VAL:%.*]] = phi i32 [ 0, %[[VECTOR_SCEVCHECK]] ], [ 0, %[[VECTOR_MEMCHECK]] ]
; TF-UNROLL-NEXT:    br label %[[LOOP1:.*]]
; TF-UNROLL:       [[LOOP1]]:
; TF-UNROLL-NEXT:    [[IV:%.*]] = phi i32 [ [[BC_RESUME_VAL]], %[[SCALAR_PH]] ], [ [[IV_NEXT:%.*]], %[[LOOP1]] ]
; TF-UNROLL-NEXT:    [[GEP:%.*]] = getelementptr i32, ptr [[P]], i32 [[IV]]
; TF-UNROLL-NEXT:    [[X:%.*]] = load i32, ptr [[GEP]], align 4
; TF-UNROLL-NEXT:    [[Y:%.*]] = add i32 [[X]], 1
; TF-UNROLL-NEXT:    store i32 [[Y]], ptr [[GEP]], align 4
; TF-UNROLL-NEXT:    store i32 [[Y]], ptr [[Q]], align 4
; TF-UNROLL-NEXT:    [[IV_NEXT]] = add i32 [[IV]], 1
; TF-UNROLL-NEXT:    [[DONE:%.*]] = icmp eq i32 [[IV_NEXT]], [[N]]
; TF-UNROLL-NEXT:    br i1 [[DONE]], label %[[EXIT]], label %[[LOOP1]], !llvm.loop [[LOOP16:![0-9]+]]
; TF-UNROLL:       [[EXIT]]:
; TF-UNROLL-NEXT:    ret void
;
entry:
  br label %loop

loop:
  %iv = phi i32 [0, %entry], [%iv.next, %loop]
  %gep = getelementptr i32, ptr %p, i32 %iv
  %x = load i32, ptr %gep
  %y = add i32 %x, 1
  store i32 %y, ptr %gep
  store i32 %y, ptr %q
  %iv.next = add i32 %iv, 1
  %done = icmp eq i32 %iv.next, %n
  br i1 %done, label %exit, label %loop

exit:
  ret void
}

!0 = distinct !{!0, !1, !2}
!1 = !{!"llvm.loop.vectorize.width", i32 4}
!2 = !{!"llvm.loop.vectorize.enable", i1 true}
