; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -O3 %s | FileCheck %s

target triple = "aarch64-unknown-linux-gnu"

; Test that a search loop with computable header exit gets rotated and
; runtime-unrolled at -O3.
define ptr @search_loop_unrolled(ptr %begin, ptr %end, i8 %val) {
; CHECK-LABEL: define ptr @search_loop_unrolled(
; CHECK-SAME: ptr nofree readnone captures(address) [[BEGIN:%.*]], ptr nofree readonly captures(address, ret: address, provenance) [[END:%.*]], i8 [[VAL:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[CMP_ENTRY:%.*]] = icmp eq ptr [[BEGIN]], [[END]]
; CHECK-NEXT:    [[PTR_DEC1:%.*]] = getelementptr inbounds i8, ptr [[END]], i64 -1
; CHECK-NEXT:    [[CMP_END2:%.*]] = icmp eq ptr [[PTR_DEC1]], [[BEGIN]]
; CHECK-NEXT:    [[OR_COND:%.*]] = select i1 [[CMP_ENTRY]], i1 true, i1 [[CMP_END2]]
; CHECK-NEXT:    br i1 [[OR_COND]], label %[[COMMON_RET:.*]], label %[[FOR_COND:.*]]
; CHECK:       [[FOR_COND]]:
; CHECK-NEXT:    [[END5:%.*]] = ptrtoint ptr [[END]] to i64
; CHECK-NEXT:    [[BEGIN6:%.*]] = ptrtoint ptr [[BEGIN]] to i64
; CHECK-NEXT:    [[TMP0:%.*]] = xor i64 [[BEGIN6]], -1
; CHECK-NEXT:    [[TMP1:%.*]] = add i64 [[TMP0]], [[END5]]
; CHECK-NEXT:    [[TMP2:%.*]] = freeze i64 [[TMP1]]
; CHECK-NEXT:    [[TMP3:%.*]] = add i64 [[TMP2]], -1
; CHECK-NEXT:    [[XTRAITER:%.*]] = and i64 [[TMP2]], 3
; CHECK-NEXT:    [[LCMP_MOD_NOT:%.*]] = icmp eq i64 [[XTRAITER]], 0
; CHECK-NEXT:    br i1 [[LCMP_MOD_NOT]], label %[[FOR_BODY_PROL_LOOPEXIT:.*]], label %[[FOR_BODY_PROL:.*]]
; CHECK:       [[FOR_BODY_PROL]]:
; CHECK-NEXT:    [[PTR_DEC5:%.*]] = phi ptr [ [[PTR_DEC4:%.*]], %[[FOR_COND_PROL:.*]] ], [ [[PTR_DEC1]], %[[FOR_COND]] ]
; CHECK-NEXT:    [[PROL_ITER:%.*]] = phi i64 [ [[PROL_ITER_NEXT:%.*]], %[[FOR_COND_PROL]] ], [ 0, %[[FOR_COND]] ]
; CHECK-NEXT:    [[LOAD_PROL:%.*]] = load i8, ptr [[PTR_DEC5]], align 1
; CHECK-NEXT:    [[CMP_VAL_PROL:%.*]] = icmp eq i8 [[LOAD_PROL]], [[VAL]]
; CHECK-NEXT:    br i1 [[CMP_VAL_PROL]], label %[[COMMON_RET]], label %[[FOR_COND_PROL]]
; CHECK:       [[FOR_COND_PROL]]:
; CHECK-NEXT:    [[PTR_DEC4]] = getelementptr inbounds i8, ptr [[PTR_DEC5]], i64 -1
; CHECK-NEXT:    [[PROL_ITER_NEXT]] = add i64 [[PROL_ITER]], 1
; CHECK-NEXT:    [[PROL_ITER_CMP_NOT:%.*]] = icmp eq i64 [[PROL_ITER_NEXT]], [[XTRAITER]]
; CHECK-NEXT:    br i1 [[PROL_ITER_CMP_NOT]], label %[[FOR_BODY_PROL_LOOPEXIT]], label %[[FOR_BODY_PROL]], !llvm.loop [[LOOP0:![0-9]+]]
; CHECK:       [[FOR_BODY_PROL_LOOPEXIT]]:
; CHECK-NEXT:    [[PTR_DEC3_UNR:%.*]] = phi ptr [ [[PTR_DEC1]], %[[FOR_COND]] ], [ [[PTR_DEC4]], %[[FOR_COND_PROL]] ]
; CHECK-NEXT:    [[TMP4:%.*]] = icmp ult i64 [[TMP3]], 3
; CHECK-NEXT:    br i1 [[TMP4]], label %[[COMMON_RET]], label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND1:.*]]:
; CHECK-NEXT:    [[PTR_DEC:%.*]] = getelementptr inbounds i8, ptr [[PTR_DEC3:%.*]], i64 -1
; CHECK-NEXT:    [[LOAD_1:%.*]] = load i8, ptr [[PTR_DEC]], align 1
; CHECK-NEXT:    [[CMP_VAL_1:%.*]] = icmp eq i8 [[LOAD_1]], [[VAL]]
; CHECK-NEXT:    br i1 [[CMP_VAL_1]], label %[[COMMON_RET_LOOPEXIT_UNR_LCSSA_LOOPEXIT_SPLIT_LOOP_EXIT14:.*]], label %[[FOR_COND_1:.*]]
; CHECK:       [[FOR_COND_1]]:
; CHECK-NEXT:    [[PTR_DEC_1:%.*]] = getelementptr inbounds i8, ptr [[PTR_DEC3]], i64 -2
; CHECK-NEXT:    [[LOAD_2:%.*]] = load i8, ptr [[PTR_DEC_1]], align 1
; CHECK-NEXT:    [[CMP_VAL_2:%.*]] = icmp eq i8 [[LOAD_2]], [[VAL]]
; CHECK-NEXT:    br i1 [[CMP_VAL_2]], label %[[COMMON_RET_LOOPEXIT_UNR_LCSSA_LOOPEXIT_SPLIT_LOOP_EXIT12:.*]], label %[[FOR_COND_2:.*]]
; CHECK:       [[FOR_COND_2]]:
; CHECK-NEXT:    [[PTR_DEC_2:%.*]] = getelementptr inbounds i8, ptr [[PTR_DEC3]], i64 -3
; CHECK-NEXT:    [[LOAD_3:%.*]] = load i8, ptr [[PTR_DEC_2]], align 1
; CHECK-NEXT:    [[CMP_VAL_3:%.*]] = icmp eq i8 [[LOAD_3]], [[VAL]]
; CHECK-NEXT:    br i1 [[CMP_VAL_3]], label %[[COMMON_RET_LOOPEXIT_UNR_LCSSA_LOOPEXIT_SPLIT_LOOP_EXIT10:.*]], label %[[FOR_COND_3:.*]]
; CHECK:       [[FOR_COND_3]]:
; CHECK-NEXT:    [[PTR_DEC_3:%.*]] = getelementptr inbounds i8, ptr [[PTR_DEC3]], i64 -4
; CHECK-NEXT:    [[CMP_END:%.*]] = icmp eq ptr [[PTR_DEC_3]], [[BEGIN]]
; CHECK-NEXT:    br i1 [[CMP_END]], label %[[COMMON_RET]], label %[[FOR_BODY]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[PTR_DEC3]] = phi ptr [ [[PTR_DEC_3]], %[[FOR_COND_3]] ], [ [[PTR_DEC3_UNR]], %[[FOR_BODY_PROL_LOOPEXIT]] ]
; CHECK-NEXT:    [[LOAD:%.*]] = load i8, ptr [[PTR_DEC3]], align 1
; CHECK-NEXT:    [[CMP_VAL:%.*]] = icmp eq i8 [[LOAD]], [[VAL]]
; CHECK-NEXT:    br i1 [[CMP_VAL]], label %[[COMMON_RET]], label %[[FOR_COND1]]
; CHECK:       [[COMMON_RET_LOOPEXIT_UNR_LCSSA_LOOPEXIT_SPLIT_LOOP_EXIT10]]:
; CHECK-NEXT:    [[PTR_DEC_2_LE:%.*]] = getelementptr inbounds i8, ptr [[PTR_DEC3]], i64 -3
; CHECK-NEXT:    br label %[[COMMON_RET]]
; CHECK:       [[COMMON_RET_LOOPEXIT_UNR_LCSSA_LOOPEXIT_SPLIT_LOOP_EXIT12]]:
; CHECK-NEXT:    [[PTR_DEC_1_LE:%.*]] = getelementptr inbounds i8, ptr [[PTR_DEC3]], i64 -2
; CHECK-NEXT:    br label %[[COMMON_RET]]
; CHECK:       [[COMMON_RET_LOOPEXIT_UNR_LCSSA_LOOPEXIT_SPLIT_LOOP_EXIT14]]:
; CHECK-NEXT:    [[PTR_DEC_LE:%.*]] = getelementptr inbounds i8, ptr [[PTR_DEC3]], i64 -1
; CHECK-NEXT:    br label %[[COMMON_RET]]
; CHECK:       [[COMMON_RET]]:
; CHECK-NEXT:    [[COMMON_RET_OP:%.*]] = phi ptr [ [[END]], %[[ENTRY]] ], [ [[END]], %[[FOR_BODY_PROL_LOOPEXIT]] ], [ [[PTR_DEC3]], %[[FOR_BODY]] ], [ [[PTR_DEC_LE]], %[[COMMON_RET_LOOPEXIT_UNR_LCSSA_LOOPEXIT_SPLIT_LOOP_EXIT14]] ], [ [[PTR_DEC_2_LE]], %[[COMMON_RET_LOOPEXIT_UNR_LCSSA_LOOPEXIT_SPLIT_LOOP_EXIT10]] ], [ [[PTR_DEC_1_LE]], %[[COMMON_RET_LOOPEXIT_UNR_LCSSA_LOOPEXIT_SPLIT_LOOP_EXIT12]] ], [ [[END]], %[[FOR_COND_3]] ], [ [[PTR_DEC5]], %[[FOR_BODY_PROL]] ]
; CHECK-NEXT:    ret ptr [[COMMON_RET_OP]]
;
entry:
  %cmp.entry = icmp eq ptr %begin, %end
  br i1 %cmp.entry, label %exit, label %for.cond

for.cond:
  %ptr = phi ptr [ %end, %entry ], [ %ptr.dec, %for.body ]
  %ptr.dec = getelementptr inbounds i8, ptr %ptr, i64 -1
  %cmp.end = icmp eq ptr %ptr.dec, %begin
  br i1 %cmp.end, label %not.found, label %for.body

for.body:
  %load = load i8, ptr %ptr.dec, align 1
  %cmp.val = icmp eq i8 %load, %val
  br i1 %cmp.val, label %found, label %for.cond

found:
  ret ptr %ptr.dec

not.found:
  br label %exit

exit:
  ret ptr %end
}

define i64 @rotate_needed_to_vectorize(ptr noalias %scan, ptr noalias %match) {
; CHECK-LABEL: define i64 @rotate_needed_to_vectorize(
; CHECK-SAME: ptr noalias nofree readonly captures(none) [[SCAN:%.*]], ptr noalias nofree readonly captures(none) [[MATCH:%.*]]) local_unnamed_addr #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[HEADER:.*]]
; CHECK:       [[HEADER]]:
; CHECK-NEXT:    [[LEN:%.*]] = phi i64 [ 0, %[[ENTRY]] ], [ [[INDEX_NEXT:%.*]], %[[EXIT:.*]] ]
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr inbounds nuw i8, ptr [[SCAN]], i64 [[LEN]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <16 x i8>, ptr [[GEP1]], align 1
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr inbounds nuw i8, ptr [[MATCH]], i64 [[LEN]]
; CHECK-NEXT:    [[WIDE_LOAD2:%.*]] = load <16 x i8>, ptr [[GEP2]], align 1
; CHECK-NEXT:    [[TMP2:%.*]] = icmp ne <16 x i8> [[WIDE_LOAD]], [[WIDE_LOAD2]]
; CHECK-NEXT:    [[TMP3:%.*]] = freeze <16 x i1> [[TMP2]]
; CHECK-NEXT:    [[TMP4:%.*]] = bitcast <16 x i1> [[TMP3]] to i16
; CHECK-NEXT:    [[DOTNOT:%.*]] = icmp eq i16 [[TMP4]], 0
; CHECK-NEXT:    br i1 [[DOTNOT]], label %[[EXIT]], label %[[VECTOR_EARLY_EXIT:.*]]
; CHECK:       [[EXIT]]:
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[LEN]], 16
; CHECK-NEXT:    [[TMP5:%.*]] = icmp eq i64 [[INDEX_NEXT]], 1024
; CHECK-NEXT:    br i1 [[TMP5]], label %[[EXIT1:.*]], label %[[HEADER]], !llvm.loop [[LOOP2:![0-9]+]]
; CHECK:       [[VECTOR_EARLY_EXIT]]:
; CHECK-NEXT:    [[TMP6:%.*]] = tail call i64 @llvm.experimental.cttz.elts.i64.v16i1(<16 x i1> [[TMP3]], i1 false)
; CHECK-NEXT:    [[TMP7:%.*]] = add i64 [[LEN]], [[TMP6]]
; CHECK-NEXT:    br label %[[EXIT1]]
; CHECK:       [[EXIT1]]:
; CHECK-NEXT:    [[LEN_LCSSA:%.*]] = phi i64 [ [[TMP7]], %[[VECTOR_EARLY_EXIT]] ], [ 1024, %[[EXIT]] ]
; CHECK-NEXT:    ret i64 [[LEN_LCSSA]]
;
entry:
  call void @llvm.assume(i1 true) [ "dereferenceable"(ptr %scan, i64 1024) ]
  call void @llvm.assume(i1 true) [ "dereferenceable"(ptr %match, i64 1024) ]
  br label %header

header:
  %len = phi i64 [ 0, %entry ], [ %len.next, %body ]
  %cmp.limit = icmp eq i64 %len, 1024
  br i1 %cmp.limit, label %exit, label %body

body:
  %gep1 = getelementptr inbounds i8, ptr %scan, i64 %len
  %v1 = load i8, ptr %gep1, align 1
  %gep2 = getelementptr inbounds i8, ptr %match, i64 %len
  %v2 = load i8, ptr %gep2, align 1
  %cmp.data = icmp eq i8 %v1, %v2
  %len.next = add nuw i64 %len, 1
  br i1 %cmp.data, label %header, label %mismatch

mismatch:
  br label %exit

exit:
  %result = phi i64 [ 1024, %header ], [ %len, %mismatch ]
  ret i64 %result
}
;.
; CHECK: [[LOOP0]] = distinct !{[[LOOP0]], [[META1:![0-9]+]]}
; CHECK: [[META1]] = !{!"llvm.loop.unroll.disable"}
; CHECK: [[LOOP2]] = distinct !{[[LOOP2]], [[META3:![0-9]+]], [[META4:![0-9]+]]}
; CHECK: [[META3]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META4]] = !{!"llvm.loop.unroll.runtime.disable"}
;.
