; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -O3 -force-vector-interleave=1 -mtriple=aarch64 -mattr=+sve2p1 -vectorize-vector-loops -S < %s | FileCheck %s

; This is a phase ordering test verifying the output of the -O3 opt pipeline.
; We are expecting the loop to use SVE udot and uabd intrinsics instead of NEON

; TODO-REVEC: Get rid of -force-vector-interleave=1

define dso_local void @pixel_ssd.do.body2(<4 x i32> %vssd_v.0, <4 x i32> %vssd_u.0, ptr %pixuv1.addr.0, ptr %pixuv2.addr.0, i64 %0, ptr %ssd_u, ptr %ssd_v) #1 {
; CHECK-LABEL: define dso_local void @pixel_ssd.do.body2(
; CHECK-SAME: <4 x i32> [[VSSD_V_0:%.*]], <4 x i32> [[VSSD_U_0:%.*]], ptr readonly captures(none) [[PIXUV1_ADDR_0:%.*]], ptr readonly captures(none) [[PIXUV2_ADDR_0:%.*]], i64 [[TMP0:%.*]], ptr writeonly captures(none) [[SSD_U:%.*]], ptr writeonly captures(none) [[SSD_V:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[NEWFUNCROOT:.*]]:
; CHECK-NEXT:    [[SMAX:%.*]] = shl i64 [[TMP0]], 4
; CHECK-NEXT:    [[ASSUMP:%.*]] = icmp sgt i64 [[SMAX]], 31
; CHECK-NEXT:    tail call void @llvm.assume(i1 [[ASSUMP]])
; CHECK-NEXT:    [[TMP1:%.*]] = add nsw i64 [[SMAX]], -8
; CHECK-NEXT:    [[TMP2:%.*]] = lshr exact i64 [[TMP1]], 3
; CHECK-NEXT:    [[TMP3:%.*]] = tail call <vscale x 4 x i32> @llvm.vector.insert.nxv4i32.v4i32(<vscale x 4 x i32> zeroinitializer, <4 x i32> [[VSSD_V_0]], i64 0)
; CHECK-NEXT:    [[TMP4:%.*]] = tail call <vscale x 4 x i32> @llvm.vector.insert.nxv4i32.v4i32(<vscale x 4 x i32> zeroinitializer, <4 x i32> [[VSSD_U_0]], i64 0)
; CHECK-NEXT:    [[INVARIANT_OP:%.*]] = sub nuw i64 [[TMP2]], 1
; CHECK-NEXT:    br label %[[VECTOR_BODY:.*]]
; CHECK:       [[VECTOR_BODY]]:
; CHECK-NEXT:    [[INDEX:%.*]] = phi i64 [ 0, %[[NEWFUNCROOT]] ], [ [[INDEX_NEXT:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_PHI:%.*]] = phi <vscale x 4 x i32> [ [[TMP3]], %[[NEWFUNCROOT]] ], [ [[TMP11:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[VEC_PHI1:%.*]] = phi <vscale x 4 x i32> [ [[TMP4]], %[[NEWFUNCROOT]] ], [ [[TMP10:%.*]], %[[VECTOR_BODY]] ]
; CHECK-NEXT:    [[TMP9:%.*]] = shl i64 [[INDEX]], 4
; CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds nuw i8, ptr [[PIXUV1_ADDR_0]], i64 [[TMP9]]
; CHECK-NEXT:    [[WIDE_LOAD:%.*]] = load <vscale x 16 x i8>, ptr [[ADD_PTR]], align 1
; CHECK-NEXT:    [[ADD_PTR7:%.*]] = getelementptr inbounds nuw i8, ptr [[PIXUV2_ADDR_0]], i64 [[TMP9]]
; CHECK-NEXT:    [[WIDE_LOAD2:%.*]] = load <vscale x 16 x i8>, ptr [[ADD_PTR7]], align 1
; CHECK-NEXT:    [[TMP7:%.*]] = tail call <vscale x 16 x i8> @llvm.aarch64.sve.uabd.u.nxv16i8(<vscale x 16 x i1> splat (i1 true), <vscale x 16 x i8> [[WIDE_LOAD]], <vscale x 16 x i8> [[WIDE_LOAD2]])
; CHECK-NEXT:    [[TMP8:%.*]] = tail call <vscale x 16 x i8> @llvm.vector.segmented.shuffle.nxv16i8.v16i32(<vscale x 16 x i8> [[TMP7]], <vscale x 16 x i8> poison, <16 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14, i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>)
; CHECK-NEXT:    [[TMP14:%.*]] = tail call <vscale x 16 x i8> @llvm.vector.segmented.shuffle.nxv16i8.v16i32(<vscale x 16 x i8> [[TMP7]], <vscale x 16 x i8> poison, <16 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15, i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>)
; CHECK-NEXT:    [[TMP10]] = tail call <vscale x 4 x i32> @llvm.aarch64.sve.udot.nxv4i32(<vscale x 4 x i32> [[VEC_PHI1]], <vscale x 16 x i8> [[TMP8]], <vscale x 16 x i8> [[TMP8]])
; CHECK-NEXT:    [[TMP11]] = tail call <vscale x 4 x i32> @llvm.aarch64.sve.udot.nxv4i32(<vscale x 4 x i32> [[VEC_PHI]], <vscale x 16 x i8> [[TMP14]], <vscale x 16 x i8> [[TMP14]])
; CHECK-NEXT:    [[INDEX_NEXT]] = add nuw i64 [[INDEX]], 2
; CHECK-NEXT:    [[TMP13:%.*]] = icmp eq i64 [[INDEX]], [[INVARIANT_OP]]
; CHECK-NEXT:    br i1 [[TMP13]], label %[[MIDDLE_BLOCK:.*]], label %[[VECTOR_BODY]], !llvm.loop [[LOOP5:![0-9]+]]
; CHECK:       [[MIDDLE_BLOCK]]:
; CHECK-NEXT:    [[VDOT1_I_1:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.nxv4i32(<4 x i32> zeroinitializer, <vscale x 4 x i32> [[TMP11]])
; CHECK-NEXT:    [[VDOT1_I44_1:%.*]] = tail call <4 x i32> @llvm.vector.partial.reduce.add.v4i32.nxv4i32(<4 x i32> zeroinitializer, <vscale x 4 x i32> [[TMP10]])
; CHECK-NEXT:    [[VADDVQ_U32_I45:%.*]] = tail call noundef i32 @llvm.aarch64.neon.uaddv.i32.v4i32(<4 x i32> [[VDOT1_I44_1]])
; CHECK-NEXT:    [[DIV41:%.*]] = lshr i32 [[VADDVQ_U32_I45]], 1
; CHECK-NEXT:    [[CONV:%.*]] = zext nneg i32 [[DIV41]] to i64
; CHECK-NEXT:    store i64 [[CONV]], ptr [[SSD_U]], align 8
; CHECK-NEXT:    [[VADDVQ_U32_I:%.*]] = tail call noundef i32 @llvm.aarch64.neon.uaddv.i32.v4i32(<4 x i32> [[VDOT1_I_1]])
; CHECK-NEXT:    [[DIV2442:%.*]] = lshr i32 [[VADDVQ_U32_I]], 1
; CHECK-NEXT:    [[CONV25:%.*]] = zext nneg i32 [[DIV2442]] to i64
; CHECK-NEXT:    store i64 [[CONV25]], ptr [[SSD_V]], align 8
; CHECK-NEXT:    ret void
;
newFuncRoot:
  %tc = mul i64 %0, 16
  %assump = icmp sge i64 %tc, 32
  call void @llvm.assume(i1 %assump)
  br label %do.body2

do.body2:                                         ; preds = %newFuncRoot, %do.body2
  %indvars.iv = phi i64 [ %indvars.iv.next, %do.body2 ], [ 0, %newFuncRoot ]
  %vssd_v.1 = phi <4 x i32> [ %vdot1.i, %do.body2 ], [ %vssd_v.0, %newFuncRoot ]
  %vssd_u.1 = phi <4 x i32> [ %vdot1.i44, %do.body2 ], [ %vssd_u.0, %newFuncRoot ]
  %1 = shl nuw nsw i64 %indvars.iv, 1
  %add.ptr = getelementptr inbounds nuw i8, ptr %pixuv1.addr.0, i64 %1
  %2 = load <16 x i8>, ptr %add.ptr, align 1
  %add.ptr7 = getelementptr inbounds nuw i8, ptr %pixuv2.addr.0, i64 %1
  %3 = load <16 x i8>, ptr %add.ptr7, align 1
  %vabd.i = tail call noundef <16 x i8> @llvm.aarch64.neon.uabd.v16i8(<16 x i8> %2, <16 x i8> %3)
  %shuffle.i = shufflevector <16 x i8> %vabd.i, <16 x i8> poison, <16 x i32> <i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14, i32 0, i32 2, i32 4, i32 6, i32 8, i32 10, i32 12, i32 14>
  %shuffle.i43 = shufflevector <16 x i8> %vabd.i, <16 x i8> poison, <16 x i32> <i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15, i32 1, i32 3, i32 5, i32 7, i32 9, i32 11, i32 13, i32 15>
  %vdot1.i44 = tail call noundef <4 x i32> @llvm.aarch64.neon.udot.v4i32.v16i8(<4 x i32> %vssd_u.1, <16 x i8> %shuffle.i, <16 x i8> %shuffle.i)
  %vdot1.i = tail call noundef <4 x i32> @llvm.aarch64.neon.udot.v4i32.v16i8(<4 x i32> %vssd_v.1, <16 x i8> %shuffle.i43, <16 x i8> %shuffle.i43)
  %indvars.iv.next = add nuw nsw i64 %indvars.iv, 8
  %cmp = icmp slt i64 %indvars.iv.next, %tc
  br i1 %cmp, label %do.body2, label %do.end.exitStub, !llvm.loop !5

do.end.exitStub:                                  ; preds = %do.body2
  %vaddvq_u32.i45 = tail call noundef i32 @llvm.aarch64.neon.uaddv.i32.v4i32(<4 x i32> %vdot1.i44)
  %div41 = lshr i32 %vaddvq_u32.i45, 1
  %conv = zext nneg i32 %div41 to i64
  store i64 %conv, ptr %ssd_u, align 8
  %vaddvq_u32.i = tail call noundef i32 @llvm.aarch64.neon.uaddv.i32.v4i32(<4 x i32> %vdot1.i)
  %div2442 = lshr i32 %vaddvq_u32.i, 1
  %conv25 = zext nneg i32 %div2442 to i64
  store i64 %conv25, ptr %ssd_v, align 8
  ret void
}

declare void @llvm.assume(i1 noundef)

attributes #0 = { nocallback nofree nosync nounwind willreturn memory(none) }
attributes #1 = { vscale_range(2,2) }

!llvm.module.flags = !{!0, !1, !2, !3, !4}

!0 = !{i32 1, !"wchar_size", i32 4}
!1 = !{i32 8, !"PIC Level", i32 2}
!2 = !{i32 7, !"PIE Level", i32 2}
!3 = !{i32 7, !"uwtable", i32 2}
!4 = !{i32 7, !"frame-pointer", i32 1}
!5 = distinct !{!5, !6}
!6 = !{!"llvm.loop.mustprogress"}
;.
; CHECK: [[LOOP5]] = distinct !{[[LOOP5]], [[META6:![0-9]+]], [[META7:![0-9]+]], [[META8:![0-9]+]]}
; CHECK: [[META6]] = !{!"llvm.loop.mustprogress"}
; CHECK: [[META7]] = !{!"llvm.loop.isvectorized", i32 1}
; CHECK: [[META8]] = !{!"llvm.loop.unroll.runtime.disable"}
;.
