# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -O0 -mtriple=wasm32-unknown-unknown -run-pass=regbankselect -verify-machineinstrs %s -o - | FileCheck %s

---
name:            and_i32
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: and_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    ; CHECK-NEXT: [[AND:%[0-9]+]]:i32regbank(s32) = G_AND [[ARGUMENT_i32_]], [[ARGUMENT_i32_1]]
    ; CHECK-NEXT: RETURN [[AND]](s32), implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    %2:_(s32) = G_AND %0, %1
    RETURN %2(s32), implicit-def $arguments
...
---
name:            and_i64
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: and_i64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i64_1:%[0-9]+]]:i64(s64) = ARGUMENT_i64 1, implicit $arguments
    ; CHECK-NEXT: [[AND:%[0-9]+]]:i64regbank(s64) = G_AND [[ARGUMENT_i64_]], [[ARGUMENT_i64_1]]
    ; CHECK-NEXT: RETURN [[AND]](s64), implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:i64(s64) = ARGUMENT_i64 1, implicit $arguments
    %2:_(s64) = G_AND %0, %1
    RETURN %2(s64), implicit-def $arguments
...

---
name:            or_i32
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: or_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    ; CHECK-NEXT: [[OR:%[0-9]+]]:i32regbank(s32) = G_OR [[ARGUMENT_i32_]], [[ARGUMENT_i32_1]]
    ; CHECK-NEXT: RETURN [[OR]](s32), implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    %2:_(s32) = G_OR %0, %1
    RETURN %2(s32), implicit-def $arguments
...
---
name:            or_i64
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: or_i64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i64_1:%[0-9]+]]:i64(s64) = ARGUMENT_i64 1, implicit $arguments
    ; CHECK-NEXT: [[OR:%[0-9]+]]:i64regbank(s64) = G_OR [[ARGUMENT_i64_]], [[ARGUMENT_i64_1]]
    ; CHECK-NEXT: RETURN [[OR]](s64), implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:i64(s64) = ARGUMENT_i64 1, implicit $arguments
    %2:_(s64) = G_OR %0, %1
    RETURN %2(s64), implicit-def $arguments
...

---
name:            xor_i32
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: xor_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:i32regbank(s32) = G_XOR [[ARGUMENT_i32_]], [[ARGUMENT_i32_1]]
    ; CHECK-NEXT: RETURN [[XOR]](s32), implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    %2:_(s32) = G_XOR %0, %1
    RETURN %2(s32), implicit-def $arguments
...
---
name:            xor_i64
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: xor_i64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i64_1:%[0-9]+]]:i64(s64) = ARGUMENT_i64 1, implicit $arguments
    ; CHECK-NEXT: [[XOR:%[0-9]+]]:i64regbank(s64) = G_XOR [[ARGUMENT_i64_]], [[ARGUMENT_i64_1]]
    ; CHECK-NEXT: RETURN [[XOR]](s64), implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:i64(s64) = ARGUMENT_i64 1, implicit $arguments
    %2:_(s64) = G_XOR %0, %1
    RETURN %2(s64), implicit-def $arguments
...

---
name:            shl_i32
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: shl_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[C:%[0-9]+]]:i32regbank(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:i32regbank(s32) = G_SHL [[ARGUMENT_i32_]], [[C]](s32)
    ; CHECK-NEXT: RETURN [[SHL]](s32), implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:_(s32) = G_CONSTANT i32 5
    %2:_(s32) = G_SHL %0, %1
    RETURN %2(s32), implicit-def $arguments
...
---
name:            shl_i64
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: shl_i64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[C:%[0-9]+]]:i64regbank(s64) = G_CONSTANT i64 37
    ; CHECK-NEXT: [[SHL:%[0-9]+]]:i64regbank(s64) = G_SHL [[ARGUMENT_i64_]], [[C]](s64)
    ; CHECK-NEXT: RETURN [[SHL]](s64), implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:_(s64) = G_CONSTANT i64 37
    %2:_(s64) = G_SHL %0, %1
    RETURN %2(s64), implicit-def $arguments
...

---
name:            ashr_i32
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: ashr_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[C:%[0-9]+]]:i32regbank(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[ASHR:%[0-9]+]]:i32regbank(s32) = G_ASHR [[ARGUMENT_i32_]], [[C]](s32)
    ; CHECK-NEXT: RETURN [[ASHR]](s32), implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:_(s32) = G_CONSTANT i32 5
    %2:_(s32) = G_ASHR %0, %1
    RETURN %2(s32), implicit-def $arguments
...
---
name:            ashr_i64
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: ashr_i64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[C:%[0-9]+]]:i64regbank(s64) = G_CONSTANT i64 37
    ; CHECK-NEXT: [[ASHR:%[0-9]+]]:i64regbank(s64) = G_ASHR [[ARGUMENT_i64_]], [[C]](s64)
    ; CHECK-NEXT: RETURN [[ASHR]](s64), implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:_(s64) = G_CONSTANT i64 37
    %2:_(s64) = G_ASHR %0, %1
    RETURN %2(s64), implicit-def $arguments
...

---
name:            lshr_i32
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: lshr_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[C:%[0-9]+]]:i32regbank(s32) = G_CONSTANT i32 5
    ; CHECK-NEXT: [[LSHR:%[0-9]+]]:i32regbank(s32) = G_LSHR [[ARGUMENT_i32_]], [[C]](s32)
    ; CHECK-NEXT: RETURN [[LSHR]](s32), implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:_(s32) = G_CONSTANT i32 5
    %2:_(s32) = G_LSHR %0, %1
    RETURN %2(s32), implicit-def $arguments
...
---
name:            lshr_i64
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: lshr_i64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[C:%[0-9]+]]:i64regbank(s64) = G_CONSTANT i64 37
    ; CHECK-NEXT: [[LSHR:%[0-9]+]]:i64regbank(s64) = G_LSHR [[ARGUMENT_i64_]], [[C]](s64)
    ; CHECK-NEXT: RETURN [[LSHR]](s64), implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:_(s64) = G_CONSTANT i64 37
    %2:_(s64) = G_LSHR %0, %1
    RETURN %2(s64), implicit-def $arguments
...

---
name:            ctlz_i32
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: ctlz_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[CTLZ:%[0-9]+]]:i32regbank(s32) = G_CTLZ [[ARGUMENT_i32_]](s32)
    ; CHECK-NEXT: RETURN [[CTLZ]](s32), implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:_(s32) = G_CTLZ %0
    RETURN %1(s32), implicit-def $arguments
...
---
name:            ctlz_i64
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: ctlz_i64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[CTLZ:%[0-9]+]]:i64regbank(s64) = G_CTLZ [[ARGUMENT_i64_]](s64)
    ; CHECK-NEXT: RETURN [[CTLZ]](s64), implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:_(s64) = G_CTLZ %0
    RETURN %1(s64), implicit-def $arguments
...

---
name:            cttz_i32
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: cttz_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[CTTZ:%[0-9]+]]:i32regbank(s32) = G_CTTZ [[ARGUMENT_i32_]](s32)
    ; CHECK-NEXT: RETURN [[CTTZ]](s32), implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:_(s32) = G_CTTZ %0
    RETURN %1(s32), implicit-def $arguments
...
---
name:            cttz_i64
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: cttz_i64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[CTTZ:%[0-9]+]]:i64regbank(s64) = G_CTTZ [[ARGUMENT_i64_]](s64)
    ; CHECK-NEXT: RETURN [[CTTZ]](s64), implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:_(s64) = G_CTTZ %0
    RETURN %1(s64), implicit-def $arguments
...

---
name:            ctpop_i32
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: ctpop_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[CTPOP:%[0-9]+]]:i32regbank(s32) = G_CTPOP [[ARGUMENT_i32_]](s32)
    ; CHECK-NEXT: RETURN [[CTPOP]](s32), implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:_(s32) = G_CTPOP %0
    RETURN %1(s32), implicit-def $arguments
...
---
name:            ctpop_i64
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: ctpop_i64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[CTPOP:%[0-9]+]]:i64regbank(s64) = G_CTPOP [[ARGUMENT_i64_]](s64)
    ; CHECK-NEXT: RETURN [[CTPOP]](s64), implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:_(s64) = G_CTPOP %0
    RETURN %1(s64), implicit-def $arguments
...

---
name:            rotl_i32
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: rotl_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    ; CHECK-NEXT: [[ROTL:%[0-9]+]]:i32regbank(s32) = G_ROTL [[ARGUMENT_i32_]], [[ARGUMENT_i32_1]](s32)
    ; CHECK-NEXT: RETURN [[ROTL]](s32), implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    %2:_(s32) = G_ROTL %0, %1(s32)
    RETURN %2(s32), implicit-def $arguments
...
---
name:            rotl_i64
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: rotl_i64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i64_1:%[0-9]+]]:i64(s64) = ARGUMENT_i64 1, implicit $arguments
    ; CHECK-NEXT: [[ROTL:%[0-9]+]]:i64regbank(s64) = G_ROTL [[ARGUMENT_i64_]], [[ARGUMENT_i64_1]](s64)
    ; CHECK-NEXT: RETURN [[ROTL]](s64), implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:i64(s64) = ARGUMENT_i64 1, implicit $arguments
    %2:_(s64) = G_ROTL %0, %1(s64)
    RETURN %2(s64), implicit-def $arguments
...

---
name:            rotr_i32
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: rotr_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i32_:%[0-9]+]]:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i32_1:%[0-9]+]]:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    ; CHECK-NEXT: [[ROTR:%[0-9]+]]:i32regbank(s32) = G_ROTR [[ARGUMENT_i32_]], [[ARGUMENT_i32_1]](s32)
    ; CHECK-NEXT: RETURN [[ROTR]](s32), implicit-def $arguments
    %0:i32(s32) = ARGUMENT_i32 0, implicit $arguments
    %1:i32(s32) = ARGUMENT_i32 1, implicit $arguments
    %2:_(s32) = G_ROTR %0, %1(s32)
    RETURN %2(s32), implicit-def $arguments
...
---
name:            rotr_i64
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: rotr_i64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[ARGUMENT_i64_:%[0-9]+]]:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    ; CHECK-NEXT: [[ARGUMENT_i64_1:%[0-9]+]]:i64(s64) = ARGUMENT_i64 1, implicit $arguments
    ; CHECK-NEXT: [[ROTR:%[0-9]+]]:i64regbank(s64) = G_ROTR [[ARGUMENT_i64_]], [[ARGUMENT_i64_1]](s64)
    ; CHECK-NEXT: RETURN [[ROTR]](s64), implicit-def $arguments
    %0:i64(s64) = ARGUMENT_i64 0, implicit $arguments
    %1:i64(s64) = ARGUMENT_i64 1, implicit $arguments
    %2:_(s64) = G_ROTR %0, %1(s64)
    RETURN %2(s64), implicit-def $arguments
...
