# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -O0 -mtriple=wasm32-unknown-unknown -run-pass=regbankselect -verify-machineinstrs %s -o - | FileCheck %s

---
name:            const_i32
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: const_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:i32regbank(s32) = G_CONSTANT i32 0
    ; CHECK-NEXT: RETURN [[C]](s32), implicit-def $arguments
    %0:_(s32) = G_CONSTANT i32 0
    RETURN %0(s32), implicit-def $arguments
...
---
name:            const_i64
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: const_i64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[C:%[0-9]+]]:i64regbank(s64) = G_CONSTANT i64 0
    ; CHECK-NEXT: RETURN [[C]](s64), implicit-def $arguments
    %0:_(s64) = G_CONSTANT i64 0
    RETURN %0(s64), implicit-def $arguments
...

---
name:            implicit_i32
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: implicit_i32
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:i32regbank(s32) = G_IMPLICIT_DEF
    ; CHECK-NEXT: RETURN [[DEF]](s32), implicit-def $arguments
    %0:_(s32) = G_IMPLICIT_DEF
    RETURN %0(s32), implicit-def $arguments
...
---
name:            implicit_i64
alignment:       1
legalized:       true
tracksRegLiveness: true
body:             |
  bb.1.entry:
    liveins: $arguments

    ; CHECK-LABEL: name: implicit_i64
    ; CHECK: liveins: $arguments
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:i64regbank(s64) = G_IMPLICIT_DEF
    ; CHECK-NEXT: RETURN [[DEF]](s64), implicit-def $arguments
    %0:_(s64) = G_IMPLICIT_DEF
    RETURN %0(s64), implicit-def $arguments
...
