; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s -passes=tailcallelim -S | FileCheck %s

define i32 @test1(i32 %c) !prof !0 {
; CHECK-LABEL: define i32 @test1(
; CHECK-SAME: i32 [[C:%.*]]) !prof [[PROF0:![0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[TAILRECURSE:.*]]
; CHECK:       [[TAILRECURSE]]:
; CHECK-NEXT:    [[C_TR:%.*]] = phi i32 [ [[C]], %[[ENTRY]] ], [ [[TMP:%.*]], %[[DEFAULT:.*]] ]
; CHECK-NEXT:    [[RET_TR:%.*]] = phi i32 [ poison, %[[ENTRY]] ], [ [[CURRENT_RET_TR:%.*]], %[[DEFAULT]] ]
; CHECK-NEXT:    [[RET_KNOWN_TR:%.*]] = phi i1 [ false, %[[ENTRY]] ], [ true, %[[DEFAULT]] ]
; CHECK-NEXT:    switch i32 [[C_TR]], label %[[DEFAULT]] [
; CHECK-NEXT:      i32 0, label %[[ONZERO:.*]]
; CHECK-NEXT:    ], !prof [[PROF1:![0-9]+]]
; CHECK:       [[ONZERO]]:
; CHECK-NEXT:    [[CURRENT_RET_TR1:%.*]] = select i1 [[RET_KNOWN_TR]], i32 [[RET_TR]], i32 0, !prof [[PROF2:![0-9]+]]
; CHECK-NEXT:    ret i32 [[CURRENT_RET_TR1]]
; CHECK:       [[DEFAULT]]:
; CHECK-NEXT:    [[TMP]] = add i32 [[C_TR]], -1
; CHECK-NEXT:    [[CURRENT_RET_TR]] = select i1 [[RET_KNOWN_TR]], i32 [[RET_TR]], i32 1, !prof [[PROF2]]
; CHECK-NEXT:    br label %[[TAILRECURSE]]
;
entry:
  switch i32 %c, label %default [ i32 0, label %onzero ], !prof !1
onzero:
  ret i32 0
default:
  %tmp = add i32 %c, -1
  %tmp.2 = call i32 @test1(i32 %tmp)
  ret i32 1
}

define i32 @test2(i32 %c) !prof !0 {
; CHECK-LABEL: define i32 @test2(
; CHECK-SAME: i32 [[C:%.*]]) !prof [[PROF3:![0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[TAILRECURSE:.*]]
; CHECK:       [[TAILRECURSE]]:
; CHECK-NEXT:    [[C_TR:%.*]] = phi i32 [ [[C]], %[[ENTRY]] ], [ [[TMP:%.*]], %[[DEFAULT:.*]] ]
; CHECK-NEXT:    [[RET_TR:%.*]] = phi i32 [ poison, %[[ENTRY]] ], [ [[CURRENT_RET_TR:%.*]], %[[DEFAULT]] ]
; CHECK-NEXT:    [[RET_KNOWN_TR:%.*]] = phi i1 [ false, %[[ENTRY]] ], [ true, %[[DEFAULT]] ]
; CHECK-NEXT:    switch i32 [[C_TR]], label %[[DEFAULT]] [
; CHECK-NEXT:      i32 0, label %[[ONZERO:.*]]
; CHECK-NEXT:      i32 1, label %[[ONONE:.*]]
; CHECK-NEXT:    ], !prof [[PROF4:![0-9]+]]
; CHECK:       [[ONZERO]]:
; CHECK-NEXT:    [[CURRENT_RET_TR1:%.*]] = select i1 [[RET_KNOWN_TR]], i32 [[RET_TR]], i32 0, !prof [[PROF5:![0-9]+]]
; CHECK-NEXT:    ret i32 [[CURRENT_RET_TR1]]
; CHECK:       [[ONONE]]:
; CHECK-NEXT:    [[CURRENT_RET_TR2:%.*]] = select i1 [[RET_KNOWN_TR]], i32 [[RET_TR]], i32 1, !prof [[PROF5]]
; CHECK-NEXT:    ret i32 [[CURRENT_RET_TR2]]
; CHECK:       [[DEFAULT]]:
; CHECK-NEXT:    [[TMP]] = add i32 [[C_TR]], -1
; CHECK-NEXT:    [[CURRENT_RET_TR]] = select i1 [[RET_KNOWN_TR]], i32 [[RET_TR]], i32 2, !prof [[PROF5]]
; CHECK-NEXT:    br label %[[TAILRECURSE]]
;
entry:
  switch i32 %c, label %default [ i32 0, label %onzero i32 1, label %onone], !prof !2
onzero:
  ret i32 0
onone:
  ret i32 1
default:
  %tmp = add i32 %c, -1
  %tmp.2 = call i32 @test2(i32 %tmp)
  ret i32 2
}

define i32 @test3(i32 %c) !prof !0 {
; CHECK-LABEL: define i32 @test3(
; CHECK-SAME: i32 [[C:%.*]]) !prof [[PROF6:![0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[TAILRECURSE:.*]]
; CHECK:       [[TAILRECURSE]]:
; CHECK-NEXT:    [[C_TR:%.*]] = phi i32 [ [[C]], %[[ENTRY]] ], [ [[TMP:%.*]], %[[ONONE:.*]] ], [ [[TMP_3:%.*]], %[[DEFAULT:.*]] ]
; CHECK-NEXT:    [[RET_TR:%.*]] = phi i32 [ poison, %[[ENTRY]] ], [ [[CURRENT_RET_TR:%.*]], %[[ONONE]] ], [ [[CURRENT_RET_TR1:%.*]], %[[DEFAULT]] ]
; CHECK-NEXT:    [[RET_KNOWN_TR:%.*]] = phi i1 [ false, %[[ENTRY]] ], [ true, %[[ONONE]] ], [ true, %[[DEFAULT]] ]
; CHECK-NEXT:    switch i32 [[C_TR]], label %[[DEFAULT]] [
; CHECK-NEXT:      i32 0, label %[[ONZERO:.*]]
; CHECK-NEXT:      i32 1, label %[[ONONE]]
; CHECK-NEXT:    ], !prof [[PROF4]]
; CHECK:       [[ONZERO]]:
; CHECK-NEXT:    [[CURRENT_RET_TR2:%.*]] = select i1 [[RET_KNOWN_TR]], i32 [[RET_TR]], i32 0, !prof [[PROF7:![0-9]+]]
; CHECK-NEXT:    ret i32 [[CURRENT_RET_TR2]]
; CHECK:       [[ONONE]]:
; CHECK-NEXT:    [[TMP]] = add i32 [[C_TR]], 1
; CHECK-NEXT:    [[CURRENT_RET_TR]] = select i1 [[RET_KNOWN_TR]], i32 [[RET_TR]], i32 1, !prof [[PROF7]]
; CHECK-NEXT:    br label %[[TAILRECURSE]]
; CHECK:       [[DEFAULT]]:
; CHECK-NEXT:    [[TMP_3]] = add i32 [[C_TR]], -2
; CHECK-NEXT:    [[CURRENT_RET_TR1]] = select i1 [[RET_KNOWN_TR]], i32 [[RET_TR]], i32 2, !prof [[PROF7]]
; CHECK-NEXT:    br label %[[TAILRECURSE]]
;
entry:
  switch i32 %c, label %default [ i32 0, label %onzero i32 1, label %onone], !prof !2
onzero:
  ret i32 0
onone:
  %tmp = add i32 %c, 1
  %tmp.2 = call i32 @test3(i32 %tmp)
  ret i32 1
default:
  %tmp.3 = add i32 %c, -2
  %tmp.4 = call i32 @test3(i32 %tmp.3)
  ret i32 2
}

!0 = !{!"function_entry_count", i64 1000}
!1 = !{!"branch_weights", i32 2, i32 3}
!2 = !{!"branch_weights", i32 2, i32 3, i32 5}
;.
; CHECK: [[PROF0]] = !{!"function_entry_count", i64 600}
; CHECK: [[PROF1]] = !{!"branch_weights", i32 2, i32 3}
; CHECK: [[PROF2]] = !{!"branch_weights", i32 429496730, i32 644245095}
; CHECK: [[PROF3]] = !{!"function_entry_count", i64 800}
; CHECK: [[PROF4]] = !{!"branch_weights", i32 2, i32 3, i32 5}
; CHECK: [[PROF5]] = !{!"branch_weights", i32 214748365, i32 858993459}
; CHECK: [[PROF6]] = !{!"function_entry_count", i64 300}
; CHECK: [[PROF7]] = !{!"branch_weights", i32 751619277, i32 322122547}
;.
