; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes="tailcallelim" -verify-dom-info -S | FileCheck %s

; NOTE: All the following test cases are generate from the underlying C code (-O1)
;   before that the shift accumulator optimization was implemented



; InstCombine strength-reduce `f(x-1) + f(x-1)` to shl:
; int f(int x) {
;     if (x == 1) return 7;
;     return f(x-1) + f(x-1); // f(x-1) * 2
; }
define i32 @test_shl_const_accumulator(i32 %x) {
; CHECK-LABEL: define i32 @test_shl_const_accumulator(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[TAILRECURSE:.*]]:
; CHECK-NEXT:    br label %[[COMMON_RET:.*]]
; CHECK:       [[COMMON_RET]]:
; CHECK-NEXT:    [[ADD:%.*]] = phi i32 [ 7, %[[TAILRECURSE]] ], [ [[ADD1:%.*]], %[[IF_END1:.*]] ]
; CHECK-NEXT:    [[X_TR:%.*]] = phi i32 [ [[X]], %[[TAILRECURSE]] ], [ [[SUB:%.*]], %[[IF_END1]] ]
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[X_TR]], 1
; CHECK-NEXT:    br i1 [[CMP]], label %[[IF_END:.*]], label %[[IF_END1]]
; CHECK:       [[IF_END]]:
; CHECK-NEXT:    ret i32 [[ADD]]
; CHECK:       [[IF_END1]]:
; CHECK-NEXT:    [[SUB]] = add nsw i32 [[X_TR]], -1
; CHECK-NEXT:    [[ADD1]] = shl i32 [[ADD]], 1
; CHECK-NEXT:    br label %[[COMMON_RET]]
;
entry:
  %cmp = icmp eq i32 %x, 1
  br i1 %cmp, label %common.ret, label %if.end

common.ret:
  %common.ret.op = phi i32 [ %add, %if.end ], [ 7, %entry ]
  ret i32 %common.ret.op

if.end:
  %sub = add nsw i32 %x, -1
  %call = tail call i32 @test_shl_const_accumulator(i32 %sub)
  %add = shl nsw i32 %call, 1
  br label %common.ret
}


; int f2(int x) {
;     if (x == 1) return 14;
;     return f2(x-1) >> 1;
; }
define i32 @test_ashr_const_accumulator(i32 %x) {
; CHECK-LABEL: define i32 @test_ashr_const_accumulator(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[TAILRECURSE:.*]]:
; CHECK-NEXT:    br label %[[TAILRECURSE1:.*]]
; CHECK:       [[TAILRECURSE1]]:
; CHECK-NEXT:    [[ACCUMULATOR_TR:%.*]] = phi i32 [ 14, %[[TAILRECURSE]] ], [ [[SHR:%.*]], %[[IF_END:.*]] ]
; CHECK-NEXT:    [[X_TR:%.*]] = phi i32 [ [[X]], %[[TAILRECURSE]] ], [ [[SUB:%.*]], %[[IF_END]] ]
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[X_TR]], 1
; CHECK-NEXT:    br i1 [[CMP]], label %[[COMMON_RET:.*]], label %[[IF_END]]
; CHECK:       [[COMMON_RET]]:
; CHECK-NEXT:    ret i32 [[ACCUMULATOR_TR]]
; CHECK:       [[IF_END]]:
; CHECK-NEXT:    [[SUB]] = add nsw i32 [[X_TR]], -1
; CHECK-NEXT:    [[SHR]] = ashr i32 [[ACCUMULATOR_TR]], 1
; CHECK-NEXT:    br label %[[TAILRECURSE1]]
;
entry:
  %cmp = icmp eq i32 %x, 1
  br i1 %cmp, label %common.ret, label %if.end

common.ret:
  %common.ret.op = phi i32 [ %shr, %if.end ], [ 14, %entry ]
  ret i32 %common.ret.op

if.end:
  %sub = add nsw i32 %x, -1
  %call = tail call i32 @test_ashr_const_accumulator(i32 %sub)
  %shr = ashr i32 %call, 1
  br label %common.ret
}


; unsigned int f3(unsigned int x) {
;     if (x <= 1) return 21;
;     return f3(x - 1) >> 1;
; }
define i32 @test_lshr_const_unsigned(i32 %x) {
; CHECK-LABEL: define i32 @test_lshr_const_unsigned(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[TAILRECURSE:.*]]:
; CHECK-NEXT:    br label %[[TAILRECURSE1:.*]]
; CHECK:       [[TAILRECURSE1]]:
; CHECK-NEXT:    [[ACCUMULATOR_TR:%.*]] = phi i32 [ 21, %[[TAILRECURSE]] ], [ [[SHR:%.*]], %[[IF_END:.*]] ]
; CHECK-NEXT:    [[X_TR:%.*]] = phi i32 [ [[X]], %[[TAILRECURSE]] ], [ [[SUB:%.*]], %[[IF_END]] ]
; CHECK-NEXT:    [[CMP:%.*]] = icmp ult i32 [[X_TR]], 2
; CHECK-NEXT:    br i1 [[CMP]], label %[[COMMON_RET:.*]], label %[[IF_END]]
; CHECK:       [[COMMON_RET]]:
; CHECK-NEXT:    ret i32 [[ACCUMULATOR_TR]]
; CHECK:       [[IF_END]]:
; CHECK-NEXT:    [[SUB]] = add i32 [[X_TR]], -1
; CHECK-NEXT:    [[SHR]] = lshr i32 [[ACCUMULATOR_TR]], 1
; CHECK-NEXT:    br label %[[TAILRECURSE1]]
;
entry:
  %cmp = icmp ult i32 %x, 2
  br i1 %cmp, label %common.ret, label %if.end

common.ret:
  %common.ret.op = phi i32 [ %shr, %if.end ], [ 21, %entry ]
  ret i32 %common.ret.op

if.end:
  %sub = add i32 %x, -1
  %call = tail call i32 @test_lshr_const_unsigned(i32 %sub)
  %shr = lshr i32 %call, 1
  br label %common.ret
}

; Negative test: non-constant shift amount prevents shift-accumulator optimization
; int f4(int x, int k) {
;   if (x == 1) return 7;
;   return f4(x-1, k) << k; // variable shift amount
; }
define i32 @test_neg_variable_shift_amount(i32 %x, i32 %k) {
; CHECK-LABEL: define i32 @test_neg_variable_shift_amount(
; CHECK-SAME: i32 [[X:%.*]], i32 [[K:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[X]], 1
; CHECK-NEXT:    br i1 [[CMP]], label %[[COMMON_RET:.*]], label %[[IF_END:.*]]
; CHECK:       [[COMMON_RET]]:
; CHECK-NEXT:    ret i32 7
; CHECK:       [[IF_END]]:
; CHECK-NEXT:    [[SUB:%.*]] = add nsw i32 [[X]], -1
; CHECK-NEXT:    [[CALL:%.*]] = tail call i32 @test_neg_variable_shift_amount(i32 [[SUB]], i32 [[K]])
; CHECK-NEXT:    [[SHL:%.*]] = shl i32 [[CALL]], [[K]]
; CHECK-NEXT:    ret i32 [[SHL]]
;
entry:
  %cmp = icmp eq i32 %x, 1
  br i1 %cmp, label %common.ret, label %if.end

common.ret:
  %common.ret.op = phi i32 [ %shl, %if.end ], [ 7, %entry ]
  ret i32 %common.ret.op

if.end:
  %sub = add nsw i32 %x, -1
  %call = tail call i32 @test_neg_variable_shift_amount(i32 %sub, i32 %k)
  %shl = shl i32 %call, %k
  br label %common.ret
}

; Negative test: intervening operation on result prevents forming clean accumulator
; int f5(int x) {
;   if (x == 1) return 7;
;   return (f5(x-1) + 1) << 1; // extra add breaks accumulator invariant
; }
define i32 @test_neg_intervening_op(i32 %x) {
; CHECK-LABEL: define i32 @test_neg_intervening_op(
; CHECK-SAME: i32 [[X:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[X]], 1
; CHECK-NEXT:    br i1 [[CMP]], label %[[COMMON_RET:.*]], label %[[IF_END:.*]]
; CHECK:       [[COMMON_RET]]:
; CHECK-NEXT:    ret i32 7
; CHECK:       [[IF_END]]:
; CHECK-NEXT:    [[SUB:%.*]] = add nsw i32 [[X]], -1
; CHECK-NEXT:    [[CALL:%.*]] = tail call i32 @test_neg_intervening_op(i32 [[SUB]])
; CHECK-NEXT:    [[TMP:%.*]] = add i32 [[CALL]], 1
; CHECK-NEXT:    [[SHL:%.*]] = shl i32 [[TMP]], 1
; CHECK-NEXT:    ret i32 [[SHL]]
;
entry:
  %cmp = icmp eq i32 %x, 1
  br i1 %cmp, label %common.ret, label %if.end

common.ret:
  %common.ret.op = phi i32 [ %shl, %if.end ], [ 7, %entry ]
  ret i32 %common.ret.op

if.end:
  %sub = add nsw i32 %x, -1
  %call = tail call i32 @test_neg_intervening_op(i32 %sub)
  %tmp = add i32 %call, 1
  %shl = shl i32 %tmp, 1
  br label %common.ret
}
