; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=thumbv6-linux-gnueabi < %s | FileCheck %s

; After various DAGCombine optimizations, we end up with an sbcs with
; multiple uses of the cpsr def, and we therefore clone the subs/sbcs.
; Make sure this doesn't crash.
;
; The output here might change at some point in the future, and no
; longer clone the operations; if that happens, there probably isn't any
; straightforward way to fix the test.
define i64 @f(i64 %x2, i32 %z) {
; CHECK-LABEL: f:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    .save {r4, lr}
; CHECK-NEXT:    push {r4, lr}
; CHECK-NEXT:    mov r2, r0
; CHECK-NEXT:    orrs r2, r1
; CHECK-NEXT:    rsbs r3, r2, #0
; CHECK-NEXT:    adcs r3, r2
; CHECK-NEXT:    lsrs r0, r3
; CHECK-NEXT:    movs r2, #31
; CHECK-NEXT:    eors r2, r3
; CHECK-NEXT:    lsls r4, r1, #1
; CHECK-NEXT:    lsls r4, r2
; CHECK-NEXT:    orrs r0, r4
; CHECK-NEXT:    lsrs r1, r3
; CHECK-NEXT:    pop {r4, pc}
  %x3 = add nsw i64 %x2, -1
  %x8 = icmp ne i64 %x2, 0
  %x9 = xor i1 %x8, true
  %x10 = zext i1 %x9 to i64
  %x11 = lshr i64 %x2, %x10
  ret i64 %x11
}
