; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=thumbv6m-none-eabi -O2 | FileCheck %s

; Test that add + zext(setcc) patterns are lowered efficiently on Thumb1.

define i32 @add_zext_setne_zero(i32 %x, i32 %z) {
; CHECK-LABEL: add_zext_setne_zero:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    movs r2, #0
; CHECK-NEXT:    subs r1, r1, #1
; CHECK-NEXT:    adcs r0, r2
; CHECK-NEXT:    bx lr
  %cmp = icmp ne i32 %z, 0
  %ext = zext i1 %cmp to i32
  %result = add i32 %x, %ext
  ret i32 %result
}

define i32 @add_zext_seteq_zero(i32 %x, i32 %z) {
; CHECK-LABEL: add_zext_seteq_zero:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    movs r2, #0
; CHECK-NEXT:    rsbs r1, r1, #0
; CHECK-NEXT:    adcs r0, r2
; CHECK-NEXT:    bx lr
  %cmp = icmp eq i32 %z, 0
  %ext = zext i1 %cmp to i32
  %result = add i32 %x, %ext
  ret i32 %result
}

define i32 @add_zext_setne_const(i32 %x, i32 %z) {
; CHECK-LABEL: add_zext_setne_const:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    cmp r1, #42
; CHECK-NEXT:    beq .LBB2_2
; CHECK-NEXT:  @ %bb.1:
; CHECK-NEXT:    adds r0, r0, #1
; CHECK-NEXT:  .LBB2_2:
; CHECK-NEXT:    bx lr
  %cmp = icmp ne i32 %z, 42
  %ext = zext i1 %cmp to i32
  %result = add i32 %x, %ext
  ret i32 %result
}

define i32 @add_zext_seteq_const(i32 %x, i32 %z) {
; CHECK-LABEL: add_zext_seteq_const:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    cmp r1, #42
; CHECK-NEXT:    bne .LBB3_2
; CHECK-NEXT:  @ %bb.1:
; CHECK-NEXT:    adds r0, r0, #1
; CHECK-NEXT:  .LBB3_2:
; CHECK-NEXT:    bx lr
  %cmp = icmp eq i32 %z, 42
  %ext = zext i1 %cmp to i32
  %result = add i32 %x, %ext
  ret i32 %result
}

; Commuted operand order: zext on the left
define i32 @add_zext_setne_zero_commuted(i32 %x, i32 %z) {
; CHECK-LABEL: add_zext_setne_zero_commuted:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    movs r2, #0
; CHECK-NEXT:    subs r1, r1, #1
; CHECK-NEXT:    adcs r0, r2
; CHECK-NEXT:    bx lr
  %cmp = icmp ne i32 %z, 0
  %ext = zext i1 %cmp to i32
  %result = add i32 %ext, %x
  ret i32 %result
}

; Negative test: multi-use of zext should not be combined
define i32 @add_zext_setne_zero_multiuse(i32 %x, i32 %z) {
; CHECK-LABEL: add_zext_setne_zero_multiuse:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    subs r2, r1, #1
; CHECK-NEXT:    sbcs r1, r2
; CHECK-NEXT:    adds r0, r0, r1
; CHECK-NEXT:    adds r0, r0, r1
; CHECK-NEXT:    bx lr
  %cmp = icmp ne i32 %z, 0
  %ext = zext i1 %cmp to i32
  %result = add i32 %x, %ext
  %result2 = add i32 %result, %ext
  ret i32 %result2
}

; Negative test: multi-use of setcc should not be combined
define i32 @add_zext_setne_zero_multiuse_cmp(i32 %x, i32 %z) {
; CHECK-LABEL: add_zext_setne_zero_multiuse_cmp:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    bx lr
  %cmp = icmp ne i32 %z, 0
  %ext = zext i1 %cmp to i32
  %ext2 = sext i1 %cmp to i32
  %result = add i32 %x, %ext
  %result2 = add i32 %result, %ext2
  ret i32 %result2
}

; Large constant
define i32 @add_zext_setne_large_const(i32 %x, i32 %z) {
; CHECK-LABEL: add_zext_setne_large_const:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    cmp r1, #255
; CHECK-NEXT:    beq .LBB7_2
; CHECK-NEXT:  @ %bb.1:
; CHECK-NEXT:    adds r0, r0, #1
; CHECK-NEXT:  .LBB7_2:
; CHECK-NEXT:    bx lr
  %cmp = icmp ne i32 %z, 255
  %ext = zext i1 %cmp to i32
  %result = add i32 %x, %ext
  ret i32 %result
}

; Constant that requires materialization
define i32 @add_zext_seteq_large_const(i32 %x, i32 %z) {
; CHECK-LABEL: add_zext_seteq_large_const:
; CHECK:       @ %bb.0:
; CHECK-NEXT:    movs r2, #1
; CHECK-NEXT:    lsls r2, r2, #10
; CHECK-NEXT:    cmp r1, r2
; CHECK-NEXT:    bne .LBB8_2
; CHECK-NEXT:  @ %bb.1:
; CHECK-NEXT:    adds r0, r0, #1
; CHECK-NEXT:  .LBB8_2:
; CHECK-NEXT:    bx lr
  %cmp = icmp eq i32 %z, 1024
  %ext = zext i1 %cmp to i32
  %result = add i32 %x, %ext
  ret i32 %result
}
