import("//llvm/utils/TableGen/tablegen.gni")
import("//third-party/unittest/unittest.gni")

tablegen("LibraryOpts") {
  visibility = [ ":OptionTests" ]
  args = [ "-gen-opt-parser-defs" ]
}

tablegen("Opts") {
  visibility = [ ":OptionTests" ]
  args = [ "-gen-opt-parser-defs" ]
}

tablegen("SubCommandOpts") {
  visibility = [ ":OptionTests" ]
  args = [ "-gen-opt-parser-defs" ]
}

unittest("OptionTests") {
  deps = [
    ":LibraryOpts",
    ":Opts",
    ":SubCommandOpts",
    "//llvm/lib/Option",
    "//llvm/lib/Support",
  ]
  sources = [
    "LibraryOptionsTest.cpp",
    "OptionMarshallingTest.cpp",
    "OptionParsingTest.cpp",
    "OptionSubCommandsTest.cpp",
  ]
}
