; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -passes=spirv-emit-intrinsics %s -mtriple=spirv64-amd-amdhsa -o - | FileCheck %s

define void @test() addrspace(4) {
; CHECK-LABEL: define void @test() addrspace(4) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call addrspace(4) void @llvm.spv.init.global.p1.i32(ptr addrspace(1) @[[GLOB0:[0-9]+]], i32 0)
; CHECK-NEXT:    call addrspace(4) void @llvm.spv.assign.ptr.type.p4(ptr addrspace(4) null, metadata i8 poison, i32 4)
; CHECK-NEXT:    [[TMP0:%.*]] = call addrspace(4) ptr addrspace(4) @llvm.spv.ptrcast.p4.p4(ptr addrspace(4) null, metadata ptr poison, i32 4)
; CHECK-NEXT:    call addrspace(4) void @llvm.spv.assign.ptr.type.p4(ptr addrspace(4) [[TMP0]], metadata ptr poison, i32 4)
; CHECK-NEXT:    [[A:%.*]] = call addrspace(4) ptr addrspace(4) (i1, ptr addrspace(4), ...) @llvm.spv.gep.p4.p4(i1 false, ptr addrspace(4) [[TMP0]], i64 42)
; CHECK-NEXT:    call addrspace(4) void @llvm.spv.assign.ptr.type.p4(ptr addrspace(4) [[A]], metadata target("spirv.$TypedPointerType", i8, 4) (i64) poison, i32 4)
; CHECK-NEXT:    [[B:%.*]] = call spir_func addrspace(4) ptr addrspace(4) [[A]](i64 0)
; CHECK-NEXT:    call addrspace(4) void @llvm.spv.assign.ptr.type.p4(ptr addrspace(4) [[B]], metadata i8 poison, i32 4)
; CHECK-NEXT:    ret void
;
entry:
  %A = getelementptr ptr, ptr addrspace(4) null, i64 42
  %B = call spir_func addrspace(4) ptr addrspace(4) %A(i64 0)
  ret void
}
