; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lasx < %s | FileCheck %s
; RUN: llc --mtriple=loongarch64 --mattr=+lasx < %s | FileCheck %s

define void @xvavg_b(ptr %res, ptr %a, ptr %b) nounwind {
; CHECK-LABEL: xvavg_b:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvld $xr1, $a2, 0
; CHECK-NEXT:    xvavg.b $xr0, $xr0, $xr1
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %va = load <32 x i8>, ptr %a
  %vb = load <32 x i8>, ptr %b
  %ea = sext <32 x i8> %va to <32 x i16>
  %eb = sext <32 x i8> %vb to <32 x i16>
  %add = add <32 x i16> %ea, %eb
  %shr = lshr <32 x i16> %add, <i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1>
  %r = trunc <32 x i16> %shr to <32 x i8>
  store <32 x i8> %r, ptr %res
  ret void
}

define <32 x i8> @vavg_b_csa(<32 x i8> %a, <32 x i8> %b) nounwind {
; CHECK-LABEL: vavg_b_csa:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavg.b $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = and <32 x i8> %a, %b
  %1 = xor <32 x i8> %a, %b
  %2 = ashr <32 x i8> %1, splat (i8 1)
  %3 = add <32 x i8> %2, %0
  ret <32 x i8> %3
}

define <32 x i8> @vavg_b_sho(<32 x i8> %a, <32 x i8> %b) nounwind {
; CHECK-LABEL: vavg_b_sho:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavg.b $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <32 x i8> %a, splat (i8 1)
  %1 = ashr <32 x i8> %b, splat (i8 1)
  %2 = and <32 x i8> %a, %b
  %3 = and <32 x i8> %2, splat (i8 1)
  %4 = add <32 x i8> %0, %1
  %5 = add <32 x i8> %4, %3
  ret <32 x i8> %5
}

define void @xvavg_h(ptr %res, ptr %a, ptr %b) nounwind {
; CHECK-LABEL: xvavg_h:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvld $xr1, $a2, 0
; CHECK-NEXT:    xvavg.h $xr0, $xr0, $xr1
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %va = load <16 x i16>, ptr %a
  %vb = load <16 x i16>, ptr %b
  %ea = sext <16 x i16> %va to <16 x i32>
  %eb = sext <16 x i16> %vb to <16 x i32>
  %add = add <16 x i32> %ea, %eb
  %shr = lshr <16 x i32> %add, <i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1>
  %r = trunc <16 x i32> %shr to <16 x i16>
  store <16 x i16> %r, ptr %res
  ret void
}

define <16 x i16> @vavg_h_csa(<16 x i16> %a, <16 x i16> %b) nounwind {
; CHECK-LABEL: vavg_h_csa:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavg.h $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = and <16 x i16> %a, %b
  %1 = xor <16 x i16> %a, %b
  %2 = ashr <16 x i16> %1, splat (i16 1)
  %3 = add <16 x i16> %2, %0
  ret <16 x i16> %3
}

define <16 x i16> @vavg_h_sho(<16 x i16> %a, <16 x i16> %b) nounwind {
; CHECK-LABEL: vavg_h_sho:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavg.h $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <16 x i16> %a, splat (i16 1)
  %1 = ashr <16 x i16> %b, splat (i16 1)
  %2 = and <16 x i16> %a, %b
  %3 = and <16 x i16> %2, splat (i16 1)
  %4 = add <16 x i16> %0, %1
  %5 = add <16 x i16> %4, %3
  ret <16 x i16> %5
}

define void @xvavg_w(ptr %res, ptr %a, ptr %b) nounwind {
; CHECK-LABEL: xvavg_w:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvld $xr1, $a2, 0
; CHECK-NEXT:    xvavg.w $xr0, $xr0, $xr1
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %va = load <8 x i32>, ptr %a
  %vb = load <8 x i32>, ptr %b
  %ea = sext <8 x i32> %va to <8 x i64>
  %eb = sext <8 x i32> %vb to <8 x i64>
  %add = add <8 x i64> %ea, %eb
  %shr = lshr <8 x i64> %add, <i64 1, i64 1, i64 1, i64 1, i64 1, i64 1, i64 1, i64 1>
  %r = trunc <8 x i64> %shr to <8 x i32>
  store <8 x i32> %r, ptr %res
  ret void
}

define <8 x i32> @vavg_w_csa(<8 x i32> %a, <8 x i32> %b) nounwind {
; CHECK-LABEL: vavg_w_csa:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavg.w $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = and <8 x i32> %a, %b
  %1 = xor <8 x i32> %a, %b
  %2 = ashr <8 x i32> %1, splat (i32 1)
  %3 = add <8 x i32> %2, %0
  ret <8 x i32> %3
}

define <8 x i32> @vavg_w_sho(<8 x i32> %a, <8 x i32> %b) nounwind {
; CHECK-LABEL: vavg_w_sho:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavg.w $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <8 x i32> %a, splat (i32 1)
  %1 = ashr <8 x i32> %b, splat (i32 1)
  %2 = and <8 x i32> %a, %b
  %3 = and <8 x i32> %2, splat (i32 1)
  %4 = add <8 x i32> %0, %1
  %5 = add <8 x i32> %4, %3
  ret <8 x i32> %5
}

define void @xvavg_d(ptr %res, ptr %a, ptr %b) nounwind {
; CHECK-LABEL: xvavg_d:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvld $xr1, $a2, 0
; CHECK-NEXT:    xvavg.d $xr0, $xr0, $xr1
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %va = load <4 x i64>, ptr %a
  %vb = load <4 x i64>, ptr %b
  %ea = sext <4 x i64> %va to <4 x i128>
  %eb = sext <4 x i64> %vb to <4 x i128>
  %add = add <4 x i128> %ea, %eb
  %shr = lshr <4 x i128> %add, <i128 1, i128 1, i128 1, i128 1>
  %r = trunc <4 x i128> %shr to <4 x i64>
  store <4 x i64> %r, ptr %res
  ret void
}

define <4 x i64> @vavg_d_csa(<4 x i64> %a, <4 x i64> %b) nounwind {
; CHECK-LABEL: vavg_d_csa:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavg.d $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = and <4 x i64> %a, %b
  %1 = xor <4 x i64> %a, %b
  %2 = ashr <4 x i64> %1, splat (i64 1)
  %3 = add <4 x i64> %2, %0
  ret <4 x i64> %3
}

define <4 x i64> @vavg_d_sho(<4 x i64> %a, <4 x i64> %b) nounwind {
; CHECK-LABEL: vavg_d_sho:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavg.d $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <4 x i64> %a, splat (i64 1)
  %1 = ashr <4 x i64> %b, splat (i64 1)
  %2 = and <4 x i64> %a, %b
  %3 = and <4 x i64> %2, splat (i64 1)
  %4 = add <4 x i64> %0, %1
  %5 = add <4 x i64> %4, %3
  ret <4 x i64> %5
}

define void @xvavg_bu(ptr %res, ptr %a, ptr %b) nounwind {
; CHECK-LABEL: xvavg_bu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvld $xr1, $a2, 0
; CHECK-NEXT:    xvavg.bu $xr0, $xr0, $xr1
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %va = load <32 x i8>, ptr %a
  %vb = load <32 x i8>, ptr %b
  %ea = zext <32 x i8> %va to <32 x i16>
  %eb = zext <32 x i8> %vb to <32 x i16>
  %add = add <32 x i16> %ea, %eb
  %shr = lshr <32 x i16> %add, <i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1>
  %r = trunc <32 x i16> %shr to <32 x i8>
  store <32 x i8> %r, ptr %res
  ret void
}

define <32 x i8> @vavg_bu_csa(<32 x i8> %a, <32 x i8> %b) nounwind {
; CHECK-LABEL: vavg_bu_csa:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavg.bu $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = and <32 x i8> %a, %b
  %1 = xor <32 x i8> %a, %b
  %2 = lshr <32 x i8> %1, splat (i8 1)
  %3 = add <32 x i8> %2, %0
  ret <32 x i8> %3
}

define <32 x i8> @vavg_bu_sho(<32 x i8> %a, <32 x i8> %b) nounwind {
; CHECK-LABEL: vavg_bu_sho:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavg.bu $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = lshr <32 x i8> %a, splat (i8 1)
  %1 = lshr <32 x i8> %b, splat (i8 1)
  %2 = and <32 x i8> %a, %b
  %3 = and <32 x i8> %2, splat (i8 1)
  %4 = add <32 x i8> %0, %1
  %5 = add <32 x i8> %4, %3
  ret <32 x i8> %5
}

define void @xvavg_hu(ptr %res, ptr %a, ptr %b) nounwind {
; CHECK-LABEL: xvavg_hu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvld $xr1, $a2, 0
; CHECK-NEXT:    xvavg.hu $xr0, $xr0, $xr1
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %va = load <16 x i16>, ptr %a
  %vb = load <16 x i16>, ptr %b
  %ea = zext <16 x i16> %va to <16 x i32>
  %eb = zext <16 x i16> %vb to <16 x i32>
  %add = add <16 x i32> %ea, %eb
  %shr = lshr <16 x i32> %add, <i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1>
  %r = trunc <16 x i32> %shr to <16 x i16>
  store <16 x i16> %r, ptr %res
  ret void
}

define <16 x i16> @vavg_hu_csa(<16 x i16> %a, <16 x i16> %b) nounwind {
; CHECK-LABEL: vavg_hu_csa:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavg.hu $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = and <16 x i16> %a, %b
  %1 = xor <16 x i16> %a, %b
  %2 = lshr <16 x i16> %1, splat (i16 1)
  %3 = add <16 x i16> %2, %0
  ret <16 x i16> %3
}

define <16 x i16> @vavg_hu_sho(<16 x i16> %a, <16 x i16> %b) nounwind {
; CHECK-LABEL: vavg_hu_sho:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavg.hu $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = lshr <16 x i16> %a, splat (i16 1)
  %1 = lshr <16 x i16> %b, splat (i16 1)
  %2 = and <16 x i16> %a, %b
  %3 = and <16 x i16> %2, splat (i16 1)
  %4 = add <16 x i16> %0, %1
  %5 = add <16 x i16> %4, %3
  ret <16 x i16> %5
}

define void @xvavg_wu(ptr %res, ptr %a, ptr %b) nounwind {
; CHECK-LABEL: xvavg_wu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvld $xr1, $a2, 0
; CHECK-NEXT:    xvavg.wu $xr0, $xr0, $xr1
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %va = load <8 x i32>, ptr %a
  %vb = load <8 x i32>, ptr %b
  %ea = zext <8 x i32> %va to <8 x i64>
  %eb = zext <8 x i32> %vb to <8 x i64>
  %add = add <8 x i64> %ea, %eb
  %shr = lshr <8 x i64> %add, <i64 1, i64 1, i64 1, i64 1, i64 1, i64 1, i64 1, i64 1>
  %r = trunc <8 x i64> %shr to <8 x i32>
  store <8 x i32> %r, ptr %res
  ret void
}

define <8 x i32> @vavg_wu_csa(<8 x i32> %a, <8 x i32> %b) nounwind {
; CHECK-LABEL: vavg_wu_csa:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavg.wu $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = and <8 x i32> %a, %b
  %1 = xor <8 x i32> %a, %b
  %2 = lshr <8 x i32> %1, splat (i32 1)
  %3 = add <8 x i32> %2, %0
  ret <8 x i32> %3
}

define <8 x i32> @vavg_wu_sho(<8 x i32> %a, <8 x i32> %b) nounwind {
; CHECK-LABEL: vavg_wu_sho:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavg.wu $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = lshr <8 x i32> %a, splat (i32 1)
  %1 = lshr <8 x i32> %b, splat (i32 1)
  %2 = and <8 x i32> %a, %b
  %3 = and <8 x i32> %2, splat (i32 1)
  %4 = add <8 x i32> %0, %1
  %5 = add <8 x i32> %4, %3
  ret <8 x i32> %5
}

define void @xvavg_du(ptr %res, ptr %a, ptr %b) nounwind {
; CHECK-LABEL: xvavg_du:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvld $xr1, $a2, 0
; CHECK-NEXT:    xvavg.du $xr0, $xr0, $xr1
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %va = load <4 x i64>, ptr %a
  %vb = load <4 x i64>, ptr %b
  %ea = zext <4 x i64> %va to <4 x i128>
  %eb = zext <4 x i64> %vb to <4 x i128>
  %add = add <4 x i128> %ea, %eb
  %shr = lshr <4 x i128> %add, <i128 1, i128 1, i128 1, i128 1>
  %r = trunc <4 x i128> %shr to <4 x i64>
  store <4 x i64> %r, ptr %res
  ret void
}

define <4 x i64> @vavg_du_csa(<4 x i64> %a, <4 x i64> %b) nounwind {
; CHECK-LABEL: vavg_du_csa:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavg.du $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = and <4 x i64> %a, %b
  %1 = xor <4 x i64> %a, %b
  %2 = lshr <4 x i64> %1, splat (i64 1)
  %3 = add <4 x i64> %2, %0
  ret <4 x i64> %3
}

define <4 x i64> @vavg_du_sho(<4 x i64> %a, <4 x i64> %b) nounwind {
; CHECK-LABEL: vavg_du_sho:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavg.du $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = lshr <4 x i64> %a, splat (i64 1)
  %1 = lshr <4 x i64> %b, splat (i64 1)
  %2 = and <4 x i64> %a, %b
  %3 = and <4 x i64> %2, splat (i64 1)
  %4 = add <4 x i64> %0, %1
  %5 = add <4 x i64> %4, %3
  ret <4 x i64> %5
}

define void @xvavgr_b(ptr %res, ptr %a, ptr %b) nounwind {
; CHECK-LABEL: xvavgr_b:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvld $xr1, $a2, 0
; CHECK-NEXT:    xvavgr.b $xr0, $xr0, $xr1
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %va = load <32 x i8>, ptr %a
  %vb = load <32 x i8>, ptr %b
  %ea = sext <32 x i8> %va to <32 x i16>
  %eb = sext <32 x i8> %vb to <32 x i16>
  %add = add <32 x i16> %ea, %eb
  %add1 = add <32 x i16> %add, <i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1>
  %shr = lshr <32 x i16> %add1, <i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1>
  %r = trunc <32 x i16> %shr to <32 x i8>
  store <32 x i8> %r, ptr %res
  ret void
}

define <32 x i8> @vavgr_b_csa(<32 x i8> %a, <32 x i8> %b) nounwind {
; CHECK-LABEL: vavgr_b_csa:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavgr.b $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = and <32 x i8> %a, %b
  %1 = xor <32 x i8> %a, %b
  %2 = add <32 x i8> %1, splat (i8 1)
  %3 = ashr <32 x i8> %2, splat (i8 1)
  %4 = add <32 x i8> %3, %0
  ret <32 x i8> %4
}

define <32 x i8> @vavgr_b_sho(<32 x i8> %a, <32 x i8> %b) nounwind {
; CHECK-LABEL: vavgr_b_sho:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavgr.b $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <32 x i8> %a, splat (i8 1)
  %1 = ashr <32 x i8> %b, splat (i8 1)
  %2 = or <32 x i8> %a, %b
  %3 = and <32 x i8> %2, splat (i8 1)
  %4 = add <32 x i8> %0, %1
  %5 = add <32 x i8> %4, %3
  ret <32 x i8> %5
}

define void @xvavgr_h(ptr %res, ptr %a, ptr %b) nounwind {
; CHECK-LABEL: xvavgr_h:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvld $xr1, $a2, 0
; CHECK-NEXT:    xvavgr.h $xr0, $xr0, $xr1
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %va = load <16 x i16>, ptr %a
  %vb = load <16 x i16>, ptr %b
  %ea = sext <16 x i16> %va to <16 x i32>
  %eb = sext <16 x i16> %vb to <16 x i32>
  %add = add <16 x i32> %ea, %eb
  %add1 = add <16 x i32> %add, <i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1>
  %shr = lshr <16 x i32> %add1, <i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1>
  %r = trunc <16 x i32> %shr to <16 x i16>
  store <16 x i16> %r, ptr %res
  ret void
}

define <16 x i16> @vavgr_h_csa(<16 x i16> %a, <16 x i16> %b) nounwind {
; CHECK-LABEL: vavgr_h_csa:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavgr.h $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = and <16 x i16> %a, %b
  %1 = xor <16 x i16> %a, %b
  %2 = add <16 x i16> %1, splat (i16 1)
  %3 = ashr <16 x i16> %2, splat (i16 1)
  %4 = add <16 x i16> %3, %0
  ret <16 x i16> %4
}

define <16 x i16> @vavgr_h_sho(<16 x i16> %a, <16 x i16> %b) nounwind {
; CHECK-LABEL: vavgr_h_sho:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavgr.h $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <16 x i16> %a, splat (i16 1)
  %1 = ashr <16 x i16> %b, splat (i16 1)
  %2 = or <16 x i16> %a, %b
  %3 = and <16 x i16> %2, splat (i16 1)
  %4 = add <16 x i16> %0, %1
  %5 = add <16 x i16> %4, %3
  ret <16 x i16> %5
}

define void @xvavgr_w(ptr %res, ptr %a, ptr %b) nounwind {
; CHECK-LABEL: xvavgr_w:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvld $xr1, $a2, 0
; CHECK-NEXT:    xvavgr.w $xr0, $xr0, $xr1
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %va = load <8 x i32>, ptr %a
  %vb = load <8 x i32>, ptr %b
  %ea = sext <8 x i32> %va to <8 x i64>
  %eb = sext <8 x i32> %vb to <8 x i64>
  %add = add <8 x i64> %ea, %eb
  %add1 = add <8 x i64> %add, <i64 1, i64 1, i64 1, i64 1, i64 1, i64 1, i64 1, i64 1>
  %shr = lshr <8 x i64> %add1, <i64 1, i64 1, i64 1, i64 1, i64 1, i64 1, i64 1, i64 1>
  %r = trunc <8 x i64> %shr to <8 x i32>
  store <8 x i32> %r, ptr %res
  ret void
}

define <8 x i32> @vavgr_w_csa(<8 x i32> %a, <8 x i32> %b) nounwind {
; CHECK-LABEL: vavgr_w_csa:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavgr.w $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = and <8 x i32> %a, %b
  %1 = xor <8 x i32> %a, %b
  %2 = add <8 x i32> %1, splat (i32 1)
  %3 = ashr <8 x i32> %2, splat (i32 1)
  %4 = add <8 x i32> %3, %0
  ret <8 x i32> %4
}

define <8 x i32> @vavgr_w_sho(<8 x i32> %a, <8 x i32> %b) nounwind {
; CHECK-LABEL: vavgr_w_sho:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavgr.w $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <8 x i32> %a, splat (i32 1)
  %1 = ashr <8 x i32> %b, splat (i32 1)
  %2 = or <8 x i32> %a, %b
  %3 = and <8 x i32> %2, splat (i32 1)
  %4 = add <8 x i32> %0, %1
  %5 = add <8 x i32> %4, %3
  ret <8 x i32> %5
}

define void @xvavgr_d(ptr %res, ptr %a, ptr %b) nounwind {
; CHECK-LABEL: xvavgr_d:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvld $xr1, $a2, 0
; CHECK-NEXT:    xvavgr.d $xr0, $xr0, $xr1
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %va = load <4 x i64>, ptr %a
  %vb = load <4 x i64>, ptr %b
  %ea = sext <4 x i64> %va to <4 x i128>
  %eb = sext <4 x i64> %vb to <4 x i128>
  %add = add <4 x i128> %ea, %eb
  %add1 = add <4 x i128> %add, <i128 1, i128 1, i128 1, i128 1>
  %shr = lshr <4 x i128> %add1, <i128 1, i128 1, i128 1, i128 1>
  %r = trunc <4 x i128> %shr to <4 x i64>
  store <4 x i64> %r, ptr %res
  ret void
}

define <4 x i64> @vavgr_d_csa(<4 x i64> %a, <4 x i64> %b) nounwind {
; CHECK-LABEL: vavgr_d_csa:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavgr.d $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = and <4 x i64> %a, %b
  %1 = xor <4 x i64> %a, %b
  %2 = add <4 x i64> %1, splat (i64 1)
  %3 = ashr <4 x i64> %2, splat (i64 1)
  %4 = add <4 x i64> %3, %0
  ret <4 x i64> %4
}

define <4 x i64> @vavgr_d_sho(<4 x i64> %a, <4 x i64> %b) nounwind {
; CHECK-LABEL: vavgr_d_sho:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavgr.d $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = ashr <4 x i64> %a, splat (i64 1)
  %1 = ashr <4 x i64> %b, splat (i64 1)
  %2 = or <4 x i64> %a, %b
  %3 = and <4 x i64> %2, splat (i64 1)
  %4 = add <4 x i64> %0, %1
  %5 = add <4 x i64> %4, %3
  ret <4 x i64> %5
}

define void @xvavgr_bu(ptr %res, ptr %a, ptr %b) nounwind {
; CHECK-LABEL: xvavgr_bu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvld $xr1, $a2, 0
; CHECK-NEXT:    xvavgr.bu $xr0, $xr0, $xr1
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %va = load <32 x i8>, ptr %a
  %vb = load <32 x i8>, ptr %b
  %ea = zext <32 x i8> %va to <32 x i16>
  %eb = zext <32 x i8> %vb to <32 x i16>
  %add = add <32 x i16> %ea, %eb
  %add1 = add <32 x i16> %add, <i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1>
  %shr = lshr <32 x i16> %add1, <i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1, i16 1>
  %r = trunc <32 x i16> %shr to <32 x i8>
  store <32 x i8> %r, ptr %res
  ret void
}

define <32 x i8> @vavgr_bu_csa(<32 x i8> %a, <32 x i8> %b) nounwind {
; CHECK-LABEL: vavgr_bu_csa:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavgr.bu $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = and <32 x i8> %a, %b
  %1 = xor <32 x i8> %a, %b
  %2 = add <32 x i8> %1, splat (i8 1)
  %3 = lshr <32 x i8> %2, splat (i8 1)
  %4 = add <32 x i8> %3, %0
  ret <32 x i8> %4
}

define <32 x i8> @vavgr_bu_sho(<32 x i8> %a, <32 x i8> %b) nounwind {
; CHECK-LABEL: vavgr_bu_sho:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavgr.bu $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = lshr <32 x i8> %a, splat (i8 1)
  %1 = lshr <32 x i8> %b, splat (i8 1)
  %2 = or <32 x i8> %a, %b
  %3 = and <32 x i8> %2, splat (i8 1)
  %4 = add <32 x i8> %0, %1
  %5 = add <32 x i8> %4, %3
  ret <32 x i8> %5
}

define void @xvavgr_hu(ptr %res, ptr %a, ptr %b) nounwind {
; CHECK-LABEL: xvavgr_hu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvld $xr1, $a2, 0
; CHECK-NEXT:    xvavgr.hu $xr0, $xr0, $xr1
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %va = load <16 x i16>, ptr %a
  %vb = load <16 x i16>, ptr %b
  %ea = zext <16 x i16> %va to <16 x i32>
  %eb = zext <16 x i16> %vb to <16 x i32>
  %add = add <16 x i32> %ea, %eb
  %add1 = add <16 x i32> %add, <i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1>
  %shr = lshr <16 x i32> %add1, <i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1, i32 1>
  %r = trunc <16 x i32> %shr to <16 x i16>
  store <16 x i16> %r, ptr %res
  ret void
}

define <16 x i16> @vavgr_hu_csa(<16 x i16> %a, <16 x i16> %b) nounwind {
; CHECK-LABEL: vavgr_hu_csa:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavgr.hu $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = and <16 x i16> %a, %b
  %1 = xor <16 x i16> %a, %b
  %2 = add <16 x i16> %1, splat (i16 1)
  %3 = lshr <16 x i16> %2, splat (i16 1)
  %4 = add <16 x i16> %3, %0
  ret <16 x i16> %4
}

define <16 x i16> @vavgr_hu_sho(<16 x i16> %a, <16 x i16> %b) nounwind {
; CHECK-LABEL: vavgr_hu_sho:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavgr.hu $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = lshr <16 x i16> %a, splat (i16 1)
  %1 = lshr <16 x i16> %b, splat (i16 1)
  %2 = or <16 x i16> %a, %b
  %3 = and <16 x i16> %2, splat (i16 1)
  %4 = add <16 x i16> %0, %1
  %5 = add <16 x i16> %4, %3
  ret <16 x i16> %5
}

define void @xvavgr_wu(ptr %res, ptr %a, ptr %b) nounwind {
; CHECK-LABEL: xvavgr_wu:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvld $xr1, $a2, 0
; CHECK-NEXT:    xvavgr.wu $xr0, $xr0, $xr1
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %va = load <8 x i32>, ptr %a
  %vb = load <8 x i32>, ptr %b
  %ea = zext <8 x i32> %va to <8 x i64>
  %eb = zext <8 x i32> %vb to <8 x i64>
  %add = add <8 x i64> %ea, %eb
  %add1 = add <8 x i64> %add, <i64 1, i64 1, i64 1, i64 1, i64 1, i64 1, i64 1, i64 1>
  %shr = lshr <8 x i64> %add1, <i64 1, i64 1, i64 1, i64 1, i64 1, i64 1, i64 1, i64 1>
  %r = trunc <8 x i64> %shr to <8 x i32>
  store <8 x i32> %r, ptr %res
  ret void
}

define <8 x i32> @vavgr_wu_csa(<8 x i32> %a, <8 x i32> %b) nounwind {
; CHECK-LABEL: vavgr_wu_csa:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavgr.wu $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = and <8 x i32> %a, %b
  %1 = xor <8 x i32> %a, %b
  %2 = add <8 x i32> %1, splat (i32 1)
  %3 = lshr <8 x i32> %2, splat (i32 1)
  %4 = add <8 x i32> %3, %0
  ret <8 x i32> %4
}

define <8 x i32> @vavgr_wu_sho(<8 x i32> %a, <8 x i32> %b) nounwind {
; CHECK-LABEL: vavgr_wu_sho:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavgr.wu $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = lshr <8 x i32> %a, splat (i32 1)
  %1 = lshr <8 x i32> %b, splat (i32 1)
  %2 = or <8 x i32> %a, %b
  %3 = and <8 x i32> %2, splat (i32 1)
  %4 = add <8 x i32> %0, %1
  %5 = add <8 x i32> %4, %3
  ret <8 x i32> %5
}

define void @xvavgr_du(ptr %res, ptr %a, ptr %b) nounwind {
; CHECK-LABEL: xvavgr_du:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvld $xr1, $a2, 0
; CHECK-NEXT:    xvavgr.du $xr0, $xr0, $xr1
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %va = load <4 x i64>, ptr %a
  %vb = load <4 x i64>, ptr %b
  %ea = zext <4 x i64> %va to <4 x i128>
  %eb = zext <4 x i64> %vb to <4 x i128>
  %add = add <4 x i128> %ea, %eb
  %add1 = add <4 x i128> %add, <i128 1, i128 1, i128 1, i128 1>
  %shr = lshr <4 x i128> %add1, <i128 1, i128 1, i128 1, i128 1>
  %r = trunc <4 x i128> %shr to <4 x i64>
  store <4 x i64> %r, ptr %res
  ret void
}

define <4 x i64> @vavgr_du_csa(<4 x i64> %a, <4 x i64> %b) nounwind {
; CHECK-LABEL: vavgr_du_csa:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavgr.du $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = and <4 x i64> %a, %b
  %1 = xor <4 x i64> %a, %b
  %2 = add <4 x i64> %1, splat (i64 1)
  %3 = lshr <4 x i64> %2, splat (i64 1)
  %4 = add <4 x i64> %3, %0
  ret <4 x i64> %4
}

define <4 x i64> @vavgr_du_sho(<4 x i64> %a, <4 x i64> %b) nounwind {
; CHECK-LABEL: vavgr_du_sho:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvavgr.du $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = lshr <4 x i64> %a, splat (i64 1)
  %1 = lshr <4 x i64> %b, splat (i64 1)
  %2 = or <4 x i64> %a, %b
  %3 = and <4 x i64> %2, splat (i64 1)
  %4 = add <4 x i64> %0, %1
  %5 = add <4 x i64> %4, %3
  ret <4 x i64> %5
}
