; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lasx < %s | FileCheck %s --check-prefix=LA32
; RUN: llc --mtriple=loongarch64 --mattr=+lasx < %s | FileCheck %s --check-prefix=LA64

define i32 @bitcast_extract_v8f32(<8 x float> %a) nounwind {
; LA32-LABEL: bitcast_extract_v8f32:
; LA32:       # %bb.0: # %entry
; LA32-NEXT:    xvpickve.w $xr0, $xr0, 7
; LA32-NEXT:    movfr2gr.s $a0, $fa0
; LA32-NEXT:    ret
;
; LA64-LABEL: bitcast_extract_v8f32:
; LA64:       # %bb.0: # %entry
; LA64-NEXT:    xvpickve2gr.w $a0, $xr0, 7
; LA64-NEXT:    ret
entry:
  %b = extractelement <8 x float> %a, i32 7
  %c = bitcast float %b to i32
  ret i32 %c
}

define i64 @bitcast_extract_v4f64(<4 x double> %a) nounwind {
; LA32-LABEL: bitcast_extract_v4f64:
; LA32:       # %bb.0: # %entry
; LA32-NEXT:    xvpickve.d $xr0, $xr0, 3
; LA32-NEXT:    movfr2gr.s $a0, $fa0
; LA32-NEXT:    movfrh2gr.s $a1, $fa0
; LA32-NEXT:    ret
;
; LA64-LABEL: bitcast_extract_v4f64:
; LA64:       # %bb.0: # %entry
; LA64-NEXT:    xvpickve2gr.d $a0, $xr0, 3
; LA64-NEXT:    ret
entry:
  %b = extractelement <4 x double> %a, i32 3
  %c = bitcast double %b to i64
  ret i64 %c
}
