; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lasx < %s | FileCheck %s
; RUN: llc --mtriple=loongarch64 --mattr=+lasx %s -o - | FileCheck %s

;; Fix https://github.com/llvm/llvm-project/issues/137000.

define <4 x double> @shufflevector_v4f64(<4 x double> %a, <4 x double> %b) {
; CHECK-LABEL: shufflevector_v4f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvpickve.d $xr2, $xr1, 3
; CHECK-NEXT:    xvpermi.d $xr3, $xr0, 238
; CHECK-NEXT:    xvrepl128vei.d $xr3, $xr3, 1
; CHECK-NEXT:    vextrins.d $vr3, $vr2, 16
; CHECK-NEXT:    xvpickve.d $xr1, $xr1, 2
; CHECK-NEXT:    vextrins.d $vr0, $vr1, 16
; CHECK-NEXT:    xvpermi.q $xr0, $xr3, 2
; CHECK-NEXT:    ret
entry:
  %c = shufflevector <4 x double> %a, <4 x double> %b, <4 x i32> <i32 0, i32 6, i32 3, i32 7>
  ret <4 x double> %c
}
