; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lasx < %s | FileCheck %s --check-prefixes=CHECK
; RUN: llc --mtriple=loongarch64 --mattr=+lasx < %s | FileCheck %s --check-prefixes=CHECK

define void @fpext_v4f32_to_v4f64(ptr %res, ptr %a0) nounwind {
; CHECK-LABEL: fpext_v4f32_to_v4f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    vld $vr0, $a1, 0
; CHECK-NEXT:    vreplvei.w $vr1, $vr0, 3
; CHECK-NEXT:    fcvt.d.s $fa1, $fa1
; CHECK-NEXT:    vreplvei.w $vr2, $vr0, 2
; CHECK-NEXT:    fcvt.d.s $fa2, $fa2
; CHECK-NEXT:    vextrins.d $vr2, $vr1, 16
; CHECK-NEXT:    vreplvei.w $vr1, $vr0, 1
; CHECK-NEXT:    fcvt.d.s $fa1, $fa1
; CHECK-NEXT:    vreplvei.w $vr0, $vr0, 0
; CHECK-NEXT:    fcvt.d.s $fa0, $fa0
; CHECK-NEXT:    vextrins.d $vr0, $vr1, 16
; CHECK-NEXT:    xvpermi.q $xr0, $xr2, 2
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %v0 = load <4 x float>, ptr %a0
  %ext = fpext <4 x float> %v0 to <4 x double>
  store <4 x double> %ext, ptr %res
  ret void
}

define void @fpext_v8f32_to_v8f64(ptr %res, ptr %a0) nounwind {
; CHECK-LABEL: fpext_v8f32_to_v8f64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvpermi.q $xr1, $xr0, 1
; CHECK-NEXT:    vreplvei.w $vr2, $vr1, 3
; CHECK-NEXT:    fcvt.d.s $fa2, $fa2
; CHECK-NEXT:    vreplvei.w $vr3, $vr1, 2
; CHECK-NEXT:    fcvt.d.s $fa3, $fa3
; CHECK-NEXT:    vextrins.d $vr3, $vr2, 16
; CHECK-NEXT:    vreplvei.w $vr2, $vr1, 1
; CHECK-NEXT:    fcvt.d.s $fa2, $fa2
; CHECK-NEXT:    vreplvei.w $vr1, $vr1, 0
; CHECK-NEXT:    fcvt.d.s $fa1, $fa1
; CHECK-NEXT:    vextrins.d $vr1, $vr2, 16
; CHECK-NEXT:    xvpermi.q $xr1, $xr3, 2
; CHECK-NEXT:    vreplvei.w $vr2, $vr0, 3
; CHECK-NEXT:    fcvt.d.s $fa2, $fa2
; CHECK-NEXT:    vreplvei.w $vr3, $vr0, 2
; CHECK-NEXT:    fcvt.d.s $fa3, $fa3
; CHECK-NEXT:    vextrins.d $vr3, $vr2, 16
; CHECK-NEXT:    vreplvei.w $vr2, $vr0, 1
; CHECK-NEXT:    fcvt.d.s $fa2, $fa2
; CHECK-NEXT:    vreplvei.w $vr0, $vr0, 0
; CHECK-NEXT:    fcvt.d.s $fa0, $fa0
; CHECK-NEXT:    vextrins.d $vr0, $vr2, 16
; CHECK-NEXT:    xvpermi.q $xr0, $xr3, 2
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    xvst $xr1, $a0, 32
; CHECK-NEXT:    ret
entry:
  %v0 = load <8 x float>, ptr %a0
  %ext = fpext <8 x float> %v0 to <8 x double>
  store <8 x double> %ext, ptr %res
  ret void
}
