; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lasx < %s | FileCheck %s --check-prefixes=CHECK
; RUN: llc --mtriple=loongarch64 --mattr=+lasx < %s | FileCheck %s --check-prefixes=CHECK

;; fptrunc
define void @fptrunc_v4f64_to_v4f32(ptr %res, ptr %a0) nounwind {
; CHECK-LABEL: fptrunc_v4f64_to_v4f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvpermi.q $xr1, $xr0, 1
; CHECK-NEXT:    vfcvt.s.d $vr0, $vr1, $vr0
; CHECK-NEXT:    vst $vr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %v0 = load <4 x double>, ptr %a0
  %trunc = fptrunc <4 x double> %v0 to <4 x float>
  store <4 x float> %trunc, ptr %res
  ret void
}

define void @fptrunc_v8f64_to_v8f32(ptr %res, ptr %a0) nounwind {
; CHECK-LABEL: fptrunc_v8f64_to_v8f32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvld $xr1, $a1, 32
; CHECK-NEXT:    pcalau12i $a1, %pc_hi20(.LCPI1_0)
; CHECK-NEXT:    xvld $xr2, $a1, %pc_lo12(.LCPI1_0)
; CHECK-NEXT:    xvfcvt.s.d $xr0, $xr1, $xr0
; CHECK-NEXT:    xvperm.w $xr0, $xr0, $xr2
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %v0 = load <8 x double>, ptr %a0
  %trunc = fptrunc <8 x double> %v0 to <8 x float>
  store <8 x float> %trunc, ptr %res
  ret void
}
