; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lasx < %s | FileCheck %s --check-prefix=LA32
; RUN: llc --mtriple=loongarch64 --mattr=+lasx < %s | FileCheck %s --check-prefix=LA64

define <8 x float> @insert_bitcast_v8f32(<8 x float> %a, i32 %b) nounwind {
; LA32-LABEL: insert_bitcast_v8f32:
; LA32:       # %bb.0: # %entry
; LA32-NEXT:    movgr2fr.w $fa1, $a0
; LA32-NEXT:    xvinsve0.w $xr0, $xr1, 1
; LA32-NEXT:    ret
;
; LA64-LABEL: insert_bitcast_v8f32:
; LA64:       # %bb.0: # %entry
; LA64-NEXT:    xvinsgr2vr.w $xr0, $a0, 1
; LA64-NEXT:    ret
entry:
  %c = bitcast i32 %b to float
  %d = insertelement <8 x float> %a, float %c, i32 1
  ret <8 x float> %d
}

define <4 x double> @insert_bitcast_v4f64(<4 x double> %a, i64 %b) nounwind {
; LA32-LABEL: insert_bitcast_v4f64:
; LA32:       # %bb.0: # %entry
; LA32-NEXT:    movgr2fr.w $fa1, $a0
; LA32-NEXT:    movgr2frh.w $fa1, $a1
; LA32-NEXT:    xvinsve0.d $xr0, $xr1, 1
; LA32-NEXT:    ret
;
; LA64-LABEL: insert_bitcast_v4f64:
; LA64:       # %bb.0: # %entry
; LA64-NEXT:    xvinsgr2vr.d $xr0, $a0, 1
; LA64-NEXT:    ret
entry:
  %c = bitcast i64 %b to double
  %d = insertelement <4 x double> %a, double %c, i32 1
  ret <4 x double> %d
}
