; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lasx < %s | FileCheck %s
; RUN: llc -mtriple=loongarch64 -mattr=+lasx < %s | FileCheck %s

define <32 x i8> @xvuadd_b(<32 x i8> %a, <32 x i8> %b) {
; CHECK-LABEL: xvuadd_b:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xvsadd.bu $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
  %ret = call <32 x i8> @llvm.uadd.sat.v32i8(<32 x i8> %a, <32 x i8> %b)
  ret <32 x i8> %ret
}

define <16 x i16> @xvuadd_h(<16 x i16> %a, <16 x i16> %b) {
; CHECK-LABEL: xvuadd_h:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xvsadd.hu $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
  %ret = call <16 x i16> @llvm.uadd.sat.v16i16(<16 x i16> %a, <16 x i16> %b)
  ret <16 x i16> %ret
}

define <8 x i32> @xvuadd_w(<8 x i32> %a, <8 x i32> %b) {
; CHECK-LABEL: xvuadd_w:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xvsadd.wu $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
  %ret = call <8 x i32> @llvm.uadd.sat.v8i32(<8 x i32> %a, <8 x i32> %b)
  ret <8 x i32> %ret
}

define <4 x i64> @xvuadd_d(<4 x i64> %a, <4 x i64> %b) {
; CHECK-LABEL: xvuadd_d:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xvsadd.du $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
  %ret = call <4 x i64> @llvm.uadd.sat.v4i64(<4 x i64> %a, <4 x i64> %b)
  ret <4 x i64> %ret
}

declare <32 x i8> @llvm.uadd.sat.v32i8(<32 x i8>, <32 x i8>)
declare <16 x i16> @llvm.uadd.sat.v16i16(<16 x i16>, <16 x i16>)
declare <8 x i32> @llvm.uadd.sat.v8i32(<8 x i32>, <8 x i32>)
declare <4 x i64> @llvm.uadd.sat.v4i64(<4 x i64>, <4 x i64>)
