; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lasx < %s | FileCheck %s
; RUN: llc --mtriple=loongarch64 --mattr=+lasx < %s | FileCheck %s

define void @uitofp_v8i32_v8f32(ptr %res, ptr %in){
; CHECK-LABEL: uitofp_v8i32_v8f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvffint.s.wu $xr0, $xr0
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
  %v0 = load <8 x i32>, ptr %in
  %v1 = uitofp <8 x i32> %v0 to <8 x float>
  store <8 x float> %v1, ptr %res
  ret void
}

define void @uitofp_v4f64_v4f64(ptr %res, ptr %in){
; CHECK-LABEL: uitofp_v4f64_v4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvffint.d.lu $xr0, $xr0
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
  %v0 = load <4 x i64>, ptr %in
  %v1 = uitofp <4 x i64> %v0 to <4 x double>
  store <4 x double> %v1, ptr %res
  ret void
}

define void @uitofp_v4i64_v4f32(ptr %res, ptr %in){
; CHECK-LABEL: uitofp_v4i64_v4f32:
; CHECK:       # %bb.0:
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvffint.d.lu $xr0, $xr0
; CHECK-NEXT:    xvpermi.d $xr1, $xr0, 238
; CHECK-NEXT:    xvfcvt.s.d $xr0, $xr1, $xr0
; CHECK-NEXT:    vst $vr0, $a0, 0
; CHECK-NEXT:    ret
  %v0 = load <4 x i64>, ptr %in
  %v1 = uitofp <4 x i64> %v0 to <4 x float>
  store <4 x float> %v1, ptr %res
  ret void
}

define void @uitofp_v4i32_v4f64(ptr %res, ptr %in){
; CHECK-LABEL: uitofp_v4i32_v4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    vld $vr0, $a1, 0
; CHECK-NEXT:    vext2xv.du.wu $xr0, $xr0
; CHECK-NEXT:    xvffint.d.lu $xr0, $xr0
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
  %v0 = load <4 x i32>, ptr %in
  %v1 = uitofp <4 x i32> %v0 to <4 x double>
  store <4 x double> %v1, ptr %res
  ret void
}

define <2 x double> @uitofp_v2i8_v2f64(<16 x i8> %a) {
; CHECK-LABEL: uitofp_v2i8_v2f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    # kill: def $vr0 killed $vr0 def $xr0
; CHECK-NEXT:    vext2xv.du.bu $xr0, $xr0
; CHECK-NEXT:    vffint.d.lu $vr0, $vr0
; CHECK-NEXT:    ret
  %shuf = shufflevector <16 x i8> %a, <16 x i8> poison, <2 x i32> <i32 0, i32 1>
  %cvt = uitofp <2 x i8> %shuf to <2 x double>
  ret <2 x double> %cvt
}

define <2 x double> @uitofp_v16i8_v2f64(<16 x i8> %a) {
; CHECK-LABEL: uitofp_v16i8_v2f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    # kill: def $vr0 killed $vr0 def $xr0
; CHECK-NEXT:    vext2xv.hu.bu $xr0, $xr0
; CHECK-NEXT:    vext2xv.wu.hu $xr0, $xr0
; CHECK-NEXT:    vext2xv.du.wu $xr0, $xr0
; CHECK-NEXT:    xvffint.d.lu $xr0, $xr0
; CHECK-NEXT:    # kill: def $vr0 killed $vr0 killed $xr0
; CHECK-NEXT:    ret
  %cvt = uitofp <16 x i8> %a to <16 x double>
  %shuf = shufflevector <16 x double> %cvt, <16 x double> poison, <2 x i32> <i32 0, i32 1>
  ret <2 x double> %shuf
}

define <4 x double> @uitofp_v4i8_v4f64(<16 x i8> %a) {
; CHECK-LABEL: uitofp_v4i8_v4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    # kill: def $vr0 killed $vr0 def $xr0
; CHECK-NEXT:    vext2xv.du.bu $xr0, $xr0
; CHECK-NEXT:    xvffint.d.lu $xr0, $xr0
; CHECK-NEXT:    ret
  %shuf = shufflevector <16 x i8> %a, <16 x i8> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  %cvt = uitofp <4 x i8> %shuf to <4 x double>
  ret <4 x double> %cvt
}

define <4 x double> @uitofp_v16i8_v4f64(<16 x i8> %a) {
; CHECK-LABEL: uitofp_v16i8_v4f64:
; CHECK:       # %bb.0:
; CHECK-NEXT:    # kill: def $vr0 killed $vr0 def $xr0
; CHECK-NEXT:    vext2xv.hu.bu $xr0, $xr0
; CHECK-NEXT:    vext2xv.wu.hu $xr0, $xr0
; CHECK-NEXT:    vext2xv.du.wu $xr0, $xr0
; CHECK-NEXT:    xvffint.d.lu $xr0, $xr0
; CHECK-NEXT:    ret
  %cvt = uitofp <16 x i8> %a to <16 x double>
  %shuf = shufflevector <16 x double> %cvt, <16 x double> poison, <4 x i32> <i32 0, i32 1, i32 2, i32 3>
  ret <4 x double> %shuf
}
