; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc --mtriple=loongarch32 --mattr=+32s,+lasx < %s | FileCheck %s
; RUN: llc --mtriple=loongarch64 --mattr=+lasx < %s | FileCheck %s

define void @xor_v32i8(ptr %res, ptr %a0, ptr %a1) nounwind {
; CHECK-LABEL: xor_v32i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvld $xr1, $a2, 0
; CHECK-NEXT:    xvxor.v $xr0, $xr0, $xr1
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %v0 = load <32 x i8>, ptr %a0
  %v1 = load <32 x i8>, ptr %a1
  %v2 = xor <32 x i8> %v0, %v1
  store <32 x i8> %v2, ptr %res
  ret void
}

define void @xor_v16i16(ptr %res, ptr %a0, ptr %a1) nounwind {
; CHECK-LABEL: xor_v16i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvld $xr1, $a2, 0
; CHECK-NEXT:    xvxor.v $xr0, $xr0, $xr1
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %v0 = load <16 x i16>, ptr %a0
  %v1 = load <16 x i16>, ptr %a1
  %v2 = xor <16 x i16> %v0, %v1
  store <16 x i16> %v2, ptr %res
  ret void
}

define void @xor_v8i32(ptr %res, ptr %a0, ptr %a1) nounwind {
; CHECK-LABEL: xor_v8i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvld $xr1, $a2, 0
; CHECK-NEXT:    xvxor.v $xr0, $xr0, $xr1
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %v0 = load <8 x i32>, ptr %a0
  %v1 = load <8 x i32>, ptr %a1
  %v2 = xor <8 x i32> %v0, %v1
  store <8 x i32> %v2, ptr %res
  ret void
}

define void @xor_v4i64(ptr %res, ptr %a0, ptr %a1) nounwind {
; CHECK-LABEL: xor_v4i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvld $xr1, $a2, 0
; CHECK-NEXT:    xvxor.v $xr0, $xr0, $xr1
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %v0 = load <4 x i64>, ptr %a0
  %v1 = load <4 x i64>, ptr %a1
  %v2 = xor <4 x i64> %v0, %v1
  store <4 x i64> %v2, ptr %res
  ret void
}

define void @xor_u_v32i8(ptr %res, ptr %a0) nounwind {
; CHECK-LABEL: xor_u_v32i8:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvxori.b $xr0, $xr0, 31
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %v0 = load <32 x i8>, ptr %a0
  %v1 = xor <32 x i8> %v0, <i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31, i8 31>
  store <32 x i8> %v1, ptr %res
  ret void
}

define void @xor_u_v16i16(ptr %res, ptr %a0) nounwind {
; CHECK-LABEL: xor_u_v16i16:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvrepli.h $xr1, 31
; CHECK-NEXT:    xvxor.v $xr0, $xr0, $xr1
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %v0 = load <16 x i16>, ptr %a0
  %v1 = xor <16 x i16> %v0, <i16 31, i16 31, i16 31, i16 31, i16 31, i16 31, i16 31, i16 31, i16 31, i16 31, i16 31, i16 31, i16 31, i16 31, i16 31, i16 31>
  store <16 x i16> %v1, ptr %res
  ret void
}

define void @xor_u_v8i32(ptr %res, ptr %a0) nounwind {
; CHECK-LABEL: xor_u_v8i32:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvrepli.w $xr1, 31
; CHECK-NEXT:    xvxor.v $xr0, $xr0, $xr1
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %v0 = load <8 x i32>, ptr %a0
  %v1 = xor <8 x i32> %v0, <i32 31, i32 31, i32 31, i32 31, i32 31, i32 31, i32 31, i32 31>
  store <8 x i32> %v1, ptr %res
  ret void
}

define void @xor_u_v4i64(ptr %res, ptr %a0) nounwind {
; CHECK-LABEL: xor_u_v4i64:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvld $xr0, $a1, 0
; CHECK-NEXT:    xvrepli.d $xr1, 31
; CHECK-NEXT:    xvxor.v $xr0, $xr0, $xr1
; CHECK-NEXT:    xvst $xr0, $a0, 0
; CHECK-NEXT:    ret
entry:
  %v0 = load <4 x i64>, ptr %a0
  %v1 = xor <4 x i64> %v0, <i64 31, i64 31, i64 31, i64 31>
  store <4 x i64> %v1, ptr %res
  ret void
}

define <16 x i16> @xor_u_v16i16_1(<16 x i16> %a) nounwind {
; CHECK-LABEL: xor_u_v16i16_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvrepli.b $xr1, 1
; CHECK-NEXT:    xvxor.v $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = xor <16 x i16> %a, splat (i16 257)
  ret <16 x i16> %0
}

define <8 x i32> @xor_u_v8i32_1(<8 x i32> %a) nounwind {
; CHECK-LABEL: xor_u_v8i32_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvrepli.b $xr1, 1
; CHECK-NEXT:    xvxor.v $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = xor <8 x i32> %a, splat (i32 16843009)
  ret <8 x i32> %0
}

define <4 x i64> @xor_u_v4i64_1(<4 x i64> %a) nounwind {
; CHECK-LABEL: xor_u_v4i64_1:
; CHECK:       # %bb.0: # %entry
; CHECK-NEXT:    xvrepli.b $xr1, 1
; CHECK-NEXT:    xvxor.v $xr0, $xr0, $xr1
; CHECK-NEXT:    ret
entry:
  %0 = xor <4 x i64> %a, splat (i64 72340172838076673)
  ret <4 x i64> %0
}
