; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=nvptx64 -mcpu=sm_90 -mattr=+ptx83 | FileCheck --check-prefix=SM90PTX83 %s
; RUN: llc < %s -mtriple=nvptx64 -mcpu=sm_90 -mattr=+ptx81 | FileCheck --check-prefix=SM90PTX81 %s
; RUN: llc < %s -mtriple=nvptx64 -mcpu=sm_90 -mattr=+ptx78 | FileCheck --check-prefix=SM90PTX78 %s
; RUN: %if ptxas-sm_90 && ptxas-isa-8.3 %{ llc < %s -mtriple=nvptx64 -mcpu=sm_90 -mattr=+ptx83 | %ptxas-verify -arch=sm_90 %}
; RUN: %if ptxas-sm_90 && ptxas-isa-8.1 %{ llc < %s -mtriple=nvptx64 -mcpu=sm_90 -mattr=+ptx81 | %ptxas-verify -arch=sm_90 %}
; RUN: %if ptxas-sm_90 && ptxas-isa-7.8 %{ llc < %s -mtriple=nvptx64 -mcpu=sm_90 -mattr=+ptx78 | %ptxas-verify -arch=sm_90 %}

; This file mirrors llvm/test/Transforms/AtomicExpand/NVPTX/expand-atomic-rmw-elementwise.ll
; so we can see the final PTX for the same set of cases. We see that the DAGCombiner appropriately folds away
; extractelement, insertelement, and shufflevector nodes.
;
; We test the following PTX versions:
;   +ptx78 (minimum for sm_90)
;     - Scalar atom.add on {i32, i64, f16, bf16, f32, f64}
;     - Scalar atom.{and,or,xor,min,max,cas,exch} on {i32, i64}
;     - Scalar atom.cas.b16
;     - Max cmpxchg width = 64 bits
;     - No vector or 128-bit atoms.
;   +ptx81
;     - Adds native vector atoms:
;         atom.v2/v4/v8.{f16,bf16}.{add,min,max}.noftz
;         atom.v2/v4.{f16x2,bf16x2}.{add,min,max}.noftz
;         atom.v2/v4.f32.add
;       NVPTX does not emit these yet, so today this produces the same
;       PTX as +ptx78.
;   +ptx83
;     - Adds atom.cas.b128 / atom.exch.b128 (hasAtomSwap128)
;     - Max cmpxchg width = 128 bits.

; For now all 3 PTX versions produce the same PTX. In the future, +ptx81 and +ptx83
; will produce vector atoms.
define <2 x float> @fadd_v2f32_elementwise(ptr %addr, <2 x float> %val) {
; SM90PTX83-LABEL: fadd_v2f32_elementwise(
; SM90PTX83:       {
; SM90PTX83-NEXT:    .reg .b32 %r<5>;
; SM90PTX83-NEXT:    .reg .b64 %rd<2>;
; SM90PTX83-EMPTY:
; SM90PTX83-NEXT:  // %bb.0: // %entry
; SM90PTX83-NEXT:    ld.param::func.b64 %rd1, [fadd_v2f32_elementwise_param_0];
; SM90PTX83-NEXT:    ld.param::func.v2.b32 {%r1, %r2}, [fadd_v2f32_elementwise_param_1];
; SM90PTX83-NEXT:    atom.relaxed.sys.add.f32 %r3, [%rd1], %r1;
; SM90PTX83-NEXT:    atom.relaxed.sys.add.f32 %r4, [%rd1+4], %r2;
; SM90PTX83-NEXT:    st.param::func.v2.b32 [func_retval0], {%r3, %r4};
; SM90PTX83-NEXT:    ret;
;
; SM90PTX81-LABEL: fadd_v2f32_elementwise(
; SM90PTX81:       {
; SM90PTX81-NEXT:    .reg .b32 %r<5>;
; SM90PTX81-NEXT:    .reg .b64 %rd<2>;
; SM90PTX81-EMPTY:
; SM90PTX81-NEXT:  // %bb.0: // %entry
; SM90PTX81-NEXT:    ld.param.b64 %rd1, [fadd_v2f32_elementwise_param_0];
; SM90PTX81-NEXT:    ld.param.v2.b32 {%r1, %r2}, [fadd_v2f32_elementwise_param_1];
; SM90PTX81-NEXT:    atom.relaxed.sys.add.f32 %r3, [%rd1], %r1;
; SM90PTX81-NEXT:    atom.relaxed.sys.add.f32 %r4, [%rd1+4], %r2;
; SM90PTX81-NEXT:    st.param.v2.b32 [func_retval0], {%r3, %r4};
; SM90PTX81-NEXT:    ret;
;
; SM90PTX78-LABEL: fadd_v2f32_elementwise(
; SM90PTX78:       {
; SM90PTX78-NEXT:    .reg .b32 %r<5>;
; SM90PTX78-NEXT:    .reg .b64 %rd<2>;
; SM90PTX78-EMPTY:
; SM90PTX78-NEXT:  // %bb.0: // %entry
; SM90PTX78-NEXT:    ld.param.b64 %rd1, [fadd_v2f32_elementwise_param_0];
; SM90PTX78-NEXT:    ld.param.v2.b32 {%r1, %r2}, [fadd_v2f32_elementwise_param_1];
; SM90PTX78-NEXT:    atom.relaxed.sys.add.f32 %r3, [%rd1], %r1;
; SM90PTX78-NEXT:    atom.relaxed.sys.add.f32 %r4, [%rd1+4], %r2;
; SM90PTX78-NEXT:    st.param.v2.b32 [func_retval0], {%r3, %r4};
; SM90PTX78-NEXT:    ret;
entry:
  %old = atomicrmw elementwise fadd ptr %addr, <2 x float> %val monotonic
  ret <2 x float> %old
}

; For now all 3 PTX versions produce the same PTX. In the future, +ptx81 and +ptx83
; will produce vector atom
define <4 x float> @fadd_v4f32_elementwise(ptr %addr, <4 x float> %val) {
; SM90PTX83-LABEL: fadd_v4f32_elementwise(
; SM90PTX83:       {
; SM90PTX83-NEXT:    .reg .b32 %r<9>;
; SM90PTX83-NEXT:    .reg .b64 %rd<2>;
; SM90PTX83-EMPTY:
; SM90PTX83-NEXT:  // %bb.0: // %entry
; SM90PTX83-NEXT:    ld.param::func.b64 %rd1, [fadd_v4f32_elementwise_param_0];
; SM90PTX83-NEXT:    ld.param::func.v4.b32 {%r1, %r2, %r3, %r4}, [fadd_v4f32_elementwise_param_1];
; SM90PTX83-NEXT:    atom.relaxed.sys.add.f32 %r5, [%rd1], %r1;
; SM90PTX83-NEXT:    atom.relaxed.sys.add.f32 %r6, [%rd1+4], %r2;
; SM90PTX83-NEXT:    atom.relaxed.sys.add.f32 %r7, [%rd1+8], %r3;
; SM90PTX83-NEXT:    atom.relaxed.sys.add.f32 %r8, [%rd1+12], %r4;
; SM90PTX83-NEXT:    st.param::func.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90PTX83-NEXT:    ret;
;
; SM90PTX81-LABEL: fadd_v4f32_elementwise(
; SM90PTX81:       {
; SM90PTX81-NEXT:    .reg .b32 %r<9>;
; SM90PTX81-NEXT:    .reg .b64 %rd<2>;
; SM90PTX81-EMPTY:
; SM90PTX81-NEXT:  // %bb.0: // %entry
; SM90PTX81-NEXT:    ld.param.b64 %rd1, [fadd_v4f32_elementwise_param_0];
; SM90PTX81-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fadd_v4f32_elementwise_param_1];
; SM90PTX81-NEXT:    atom.relaxed.sys.add.f32 %r5, [%rd1], %r1;
; SM90PTX81-NEXT:    atom.relaxed.sys.add.f32 %r6, [%rd1+4], %r2;
; SM90PTX81-NEXT:    atom.relaxed.sys.add.f32 %r7, [%rd1+8], %r3;
; SM90PTX81-NEXT:    atom.relaxed.sys.add.f32 %r8, [%rd1+12], %r4;
; SM90PTX81-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90PTX81-NEXT:    ret;
;
; SM90PTX78-LABEL: fadd_v4f32_elementwise(
; SM90PTX78:       {
; SM90PTX78-NEXT:    .reg .b32 %r<9>;
; SM90PTX78-NEXT:    .reg .b64 %rd<2>;
; SM90PTX78-EMPTY:
; SM90PTX78-NEXT:  // %bb.0: // %entry
; SM90PTX78-NEXT:    ld.param.b64 %rd1, [fadd_v4f32_elementwise_param_0];
; SM90PTX78-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fadd_v4f32_elementwise_param_1];
; SM90PTX78-NEXT:    atom.relaxed.sys.add.f32 %r5, [%rd1], %r1;
; SM90PTX78-NEXT:    atom.relaxed.sys.add.f32 %r6, [%rd1+4], %r2;
; SM90PTX78-NEXT:    atom.relaxed.sys.add.f32 %r7, [%rd1+8], %r3;
; SM90PTX78-NEXT:    atom.relaxed.sys.add.f32 %r8, [%rd1+12], %r4;
; SM90PTX78-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90PTX78-NEXT:    ret;
entry:
  %old = atomicrmw elementwise fadd ptr %addr, <4 x float> %val monotonic, align 16
  ret <4 x float> %old
}

; For now all 3 PTX versions produce the same PTX. In the future, +ptx81 and +ptx83
; will produce vector atom
define <4 x float> @fadd_v4f32_elementwise_volatile(ptr %addr, <4 x float> %val) {
; SM90PTX83-LABEL: fadd_v4f32_elementwise_volatile(
; SM90PTX83:       {
; SM90PTX83-NEXT:    .reg .b32 %r<9>;
; SM90PTX83-NEXT:    .reg .b64 %rd<2>;
; SM90PTX83-EMPTY:
; SM90PTX83-NEXT:  // %bb.0: // %entry
; SM90PTX83-NEXT:    ld.param::func.b64 %rd1, [fadd_v4f32_elementwise_volatile_param_0];
; SM90PTX83-NEXT:    ld.param::func.v4.b32 {%r1, %r2, %r3, %r4}, [fadd_v4f32_elementwise_volatile_param_1];
; SM90PTX83-NEXT:    atom.relaxed.sys.add.f32 %r5, [%rd1], %r1;
; SM90PTX83-NEXT:    atom.relaxed.sys.add.f32 %r6, [%rd1+4], %r2;
; SM90PTX83-NEXT:    atom.relaxed.sys.add.f32 %r7, [%rd1+8], %r3;
; SM90PTX83-NEXT:    atom.relaxed.sys.add.f32 %r8, [%rd1+12], %r4;
; SM90PTX83-NEXT:    st.param::func.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90PTX83-NEXT:    ret;
;
; SM90PTX81-LABEL: fadd_v4f32_elementwise_volatile(
; SM90PTX81:       {
; SM90PTX81-NEXT:    .reg .b32 %r<9>;
; SM90PTX81-NEXT:    .reg .b64 %rd<2>;
; SM90PTX81-EMPTY:
; SM90PTX81-NEXT:  // %bb.0: // %entry
; SM90PTX81-NEXT:    ld.param.b64 %rd1, [fadd_v4f32_elementwise_volatile_param_0];
; SM90PTX81-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fadd_v4f32_elementwise_volatile_param_1];
; SM90PTX81-NEXT:    atom.relaxed.sys.add.f32 %r5, [%rd1], %r1;
; SM90PTX81-NEXT:    atom.relaxed.sys.add.f32 %r6, [%rd1+4], %r2;
; SM90PTX81-NEXT:    atom.relaxed.sys.add.f32 %r7, [%rd1+8], %r3;
; SM90PTX81-NEXT:    atom.relaxed.sys.add.f32 %r8, [%rd1+12], %r4;
; SM90PTX81-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90PTX81-NEXT:    ret;
;
; SM90PTX78-LABEL: fadd_v4f32_elementwise_volatile(
; SM90PTX78:       {
; SM90PTX78-NEXT:    .reg .b32 %r<9>;
; SM90PTX78-NEXT:    .reg .b64 %rd<2>;
; SM90PTX78-EMPTY:
; SM90PTX78-NEXT:  // %bb.0: // %entry
; SM90PTX78-NEXT:    ld.param.b64 %rd1, [fadd_v4f32_elementwise_volatile_param_0];
; SM90PTX78-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fadd_v4f32_elementwise_volatile_param_1];
; SM90PTX78-NEXT:    atom.relaxed.sys.add.f32 %r5, [%rd1], %r1;
; SM90PTX78-NEXT:    atom.relaxed.sys.add.f32 %r6, [%rd1+4], %r2;
; SM90PTX78-NEXT:    atom.relaxed.sys.add.f32 %r7, [%rd1+8], %r3;
; SM90PTX78-NEXT:    atom.relaxed.sys.add.f32 %r8, [%rd1+12], %r4;
; SM90PTX78-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90PTX78-NEXT:    ret;
entry:
  %old = atomicrmw volatile elementwise fadd ptr %addr, <4 x float> %val monotonic, align 16
  ret <4 x float> %old
}

; For now all 3 PTX versions produce the same PTX. In the future, +ptx81 and +ptx83
; will produce vector atom
define <4 x float> @fadd_v4f32_elementwise_block(ptr %addr, <4 x float> %val) {
; SM90PTX83-LABEL: fadd_v4f32_elementwise_block(
; SM90PTX83:       {
; SM90PTX83-NEXT:    .reg .b32 %r<9>;
; SM90PTX83-NEXT:    .reg .b64 %rd<2>;
; SM90PTX83-EMPTY:
; SM90PTX83-NEXT:  // %bb.0: // %entry
; SM90PTX83-NEXT:    ld.param::func.b64 %rd1, [fadd_v4f32_elementwise_block_param_0];
; SM90PTX83-NEXT:    ld.param::func.v4.b32 {%r1, %r2, %r3, %r4}, [fadd_v4f32_elementwise_block_param_1];
; SM90PTX83-NEXT:    atom.relaxed.cta.add.f32 %r5, [%rd1], %r1;
; SM90PTX83-NEXT:    atom.relaxed.cta.add.f32 %r6, [%rd1+4], %r2;
; SM90PTX83-NEXT:    atom.relaxed.cta.add.f32 %r7, [%rd1+8], %r3;
; SM90PTX83-NEXT:    atom.relaxed.cta.add.f32 %r8, [%rd1+12], %r4;
; SM90PTX83-NEXT:    st.param::func.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90PTX83-NEXT:    ret;
;
; SM90PTX81-LABEL: fadd_v4f32_elementwise_block(
; SM90PTX81:       {
; SM90PTX81-NEXT:    .reg .b32 %r<9>;
; SM90PTX81-NEXT:    .reg .b64 %rd<2>;
; SM90PTX81-EMPTY:
; SM90PTX81-NEXT:  // %bb.0: // %entry
; SM90PTX81-NEXT:    ld.param.b64 %rd1, [fadd_v4f32_elementwise_block_param_0];
; SM90PTX81-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fadd_v4f32_elementwise_block_param_1];
; SM90PTX81-NEXT:    atom.relaxed.cta.add.f32 %r5, [%rd1], %r1;
; SM90PTX81-NEXT:    atom.relaxed.cta.add.f32 %r6, [%rd1+4], %r2;
; SM90PTX81-NEXT:    atom.relaxed.cta.add.f32 %r7, [%rd1+8], %r3;
; SM90PTX81-NEXT:    atom.relaxed.cta.add.f32 %r8, [%rd1+12], %r4;
; SM90PTX81-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90PTX81-NEXT:    ret;
;
; SM90PTX78-LABEL: fadd_v4f32_elementwise_block(
; SM90PTX78:       {
; SM90PTX78-NEXT:    .reg .b32 %r<9>;
; SM90PTX78-NEXT:    .reg .b64 %rd<2>;
; SM90PTX78-EMPTY:
; SM90PTX78-NEXT:  // %bb.0: // %entry
; SM90PTX78-NEXT:    ld.param.b64 %rd1, [fadd_v4f32_elementwise_block_param_0];
; SM90PTX78-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fadd_v4f32_elementwise_block_param_1];
; SM90PTX78-NEXT:    atom.relaxed.cta.add.f32 %r5, [%rd1], %r1;
; SM90PTX78-NEXT:    atom.relaxed.cta.add.f32 %r6, [%rd1+4], %r2;
; SM90PTX78-NEXT:    atom.relaxed.cta.add.f32 %r7, [%rd1+8], %r3;
; SM90PTX78-NEXT:    atom.relaxed.cta.add.f32 %r8, [%rd1+12], %r4;
; SM90PTX78-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90PTX78-NEXT:    ret;
entry:
  %old = atomicrmw elementwise fadd ptr %addr, <4 x float> %val syncscope("block") monotonic, align 16
  ret <4 x float> %old
}

; For now all 3 PTX versions produce the same PTX. In the future, +ptx81 and +ptx83
; will produce vector atom
define <4 x float> @fadd_v4f32_elementwise_seq_cst(ptr %addr, <4 x float> %val) {
; SM90PTX83-LABEL: fadd_v4f32_elementwise_seq_cst(
; SM90PTX83:       {
; SM90PTX83-NEXT:    .reg .b32 %r<9>;
; SM90PTX83-NEXT:    .reg .b64 %rd<2>;
; SM90PTX83-EMPTY:
; SM90PTX83-NEXT:  // %bb.0: // %entry
; SM90PTX83-NEXT:    ld.param::func.b64 %rd1, [fadd_v4f32_elementwise_seq_cst_param_0];
; SM90PTX83-NEXT:    ld.param::func.v4.b32 {%r1, %r2, %r3, %r4}, [fadd_v4f32_elementwise_seq_cst_param_1];
; SM90PTX83-NEXT:    fence.sc.sys;
; SM90PTX83-NEXT:    atom.acquire.sys.add.f32 %r5, [%rd1], %r1;
; SM90PTX83-NEXT:    fence.sc.sys;
; SM90PTX83-NEXT:    atom.acquire.sys.add.f32 %r6, [%rd1+4], %r2;
; SM90PTX83-NEXT:    fence.sc.sys;
; SM90PTX83-NEXT:    atom.acquire.sys.add.f32 %r7, [%rd1+8], %r3;
; SM90PTX83-NEXT:    fence.sc.sys;
; SM90PTX83-NEXT:    atom.acquire.sys.add.f32 %r8, [%rd1+12], %r4;
; SM90PTX83-NEXT:    st.param::func.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90PTX83-NEXT:    ret;
;
; SM90PTX81-LABEL: fadd_v4f32_elementwise_seq_cst(
; SM90PTX81:       {
; SM90PTX81-NEXT:    .reg .b32 %r<9>;
; SM90PTX81-NEXT:    .reg .b64 %rd<2>;
; SM90PTX81-EMPTY:
; SM90PTX81-NEXT:  // %bb.0: // %entry
; SM90PTX81-NEXT:    ld.param.b64 %rd1, [fadd_v4f32_elementwise_seq_cst_param_0];
; SM90PTX81-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fadd_v4f32_elementwise_seq_cst_param_1];
; SM90PTX81-NEXT:    fence.sc.sys;
; SM90PTX81-NEXT:    atom.acquire.sys.add.f32 %r5, [%rd1], %r1;
; SM90PTX81-NEXT:    fence.sc.sys;
; SM90PTX81-NEXT:    atom.acquire.sys.add.f32 %r6, [%rd1+4], %r2;
; SM90PTX81-NEXT:    fence.sc.sys;
; SM90PTX81-NEXT:    atom.acquire.sys.add.f32 %r7, [%rd1+8], %r3;
; SM90PTX81-NEXT:    fence.sc.sys;
; SM90PTX81-NEXT:    atom.acquire.sys.add.f32 %r8, [%rd1+12], %r4;
; SM90PTX81-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90PTX81-NEXT:    ret;
;
; SM90PTX78-LABEL: fadd_v4f32_elementwise_seq_cst(
; SM90PTX78:       {
; SM90PTX78-NEXT:    .reg .b32 %r<9>;
; SM90PTX78-NEXT:    .reg .b64 %rd<2>;
; SM90PTX78-EMPTY:
; SM90PTX78-NEXT:  // %bb.0: // %entry
; SM90PTX78-NEXT:    ld.param.b64 %rd1, [fadd_v4f32_elementwise_seq_cst_param_0];
; SM90PTX78-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fadd_v4f32_elementwise_seq_cst_param_1];
; SM90PTX78-NEXT:    fence.sc.sys;
; SM90PTX78-NEXT:    atom.acquire.sys.add.f32 %r5, [%rd1], %r1;
; SM90PTX78-NEXT:    fence.sc.sys;
; SM90PTX78-NEXT:    atom.acquire.sys.add.f32 %r6, [%rd1+4], %r2;
; SM90PTX78-NEXT:    fence.sc.sys;
; SM90PTX78-NEXT:    atom.acquire.sys.add.f32 %r7, [%rd1+8], %r3;
; SM90PTX78-NEXT:    fence.sc.sys;
; SM90PTX78-NEXT:    atom.acquire.sys.add.f32 %r8, [%rd1+12], %r4;
; SM90PTX78-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90PTX78-NEXT:    ret;
entry:
  %old = atomicrmw elementwise fadd ptr %addr, <4 x float> %val seq_cst, align 16
  ret <4 x float> %old
}

; +ptx83 produces a 128-bit cmpxchg loop. +ptx81 and +ptx78 produce two 64-bit cmpxchg loops.
; If this were not an elementwise atomicrmw, we would not have been able to break up the atomic
; into two 64-bit cmpxchg loops.
;
; In the future, both +ptx83 and +ptx81 will produce vector atom.
define <8 x half> @fmin_v8f16_elementwise(ptr %addr, <8 x half> %val) {
; SM90PTX83-LABEL: fmin_v8f16_elementwise(
; SM90PTX83:       {
; SM90PTX83-NEXT:    .reg .pred %p<2>;
; SM90PTX83-NEXT:    .reg .b32 %r<13>;
; SM90PTX83-NEXT:    .reg .b64 %rd<23>;
; SM90PTX83-EMPTY:
; SM90PTX83-NEXT:  // %bb.0: // %entry
; SM90PTX83-NEXT:    ld.param::func.v4.b32 {%r1, %r2, %r3, %r4}, [fmin_v8f16_elementwise_param_1];
; SM90PTX83-NEXT:    ld.param::func.b64 %rd1, [fmin_v8f16_elementwise_param_0];
; SM90PTX83-NEXT:    ld.v4.b32 {%r9, %r10, %r11, %r12}, [%rd1];
; SM90PTX83-NEXT:  $L__BB5_1: // %atomicrmw.start
; SM90PTX83-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90PTX83-NEXT:    min.f16x2 %r5, %r9, %r1;
; SM90PTX83-NEXT:    cvt.u64.u32 %rd2, %r5;
; SM90PTX83-NEXT:    min.f16x2 %r6, %r10, %r2;
; SM90PTX83-NEXT:    cvt.u64.u32 %rd3, %r6;
; SM90PTX83-NEXT:    shl.b64 %rd4, %rd3, 32;
; SM90PTX83-NEXT:    or.b64 %rd5, %rd2, %rd4;
; SM90PTX83-NEXT:    min.f16x2 %r7, %r11, %r3;
; SM90PTX83-NEXT:    cvt.u64.u32 %rd6, %r7;
; SM90PTX83-NEXT:    min.f16x2 %r8, %r12, %r4;
; SM90PTX83-NEXT:    cvt.u64.u32 %rd7, %r8;
; SM90PTX83-NEXT:    shl.b64 %rd8, %rd7, 32;
; SM90PTX83-NEXT:    or.b64 %rd9, %rd6, %rd8;
; SM90PTX83-NEXT:    cvt.u64.u32 %rd10, %r9;
; SM90PTX83-NEXT:    cvt.u64.u32 %rd11, %r10;
; SM90PTX83-NEXT:    shl.b64 %rd12, %rd11, 32;
; SM90PTX83-NEXT:    or.b64 %rd13, %rd10, %rd12;
; SM90PTX83-NEXT:    cvt.u64.u32 %rd14, %r11;
; SM90PTX83-NEXT:    cvt.u64.u32 %rd15, %r12;
; SM90PTX83-NEXT:    shl.b64 %rd16, %rd15, 32;
; SM90PTX83-NEXT:    or.b64 %rd17, %rd14, %rd16;
; SM90PTX83-NEXT:    {
; SM90PTX83-NEXT:    .reg .b128 cmp, swap, dst;
; SM90PTX83-NEXT:    mov.b128 cmp, {%rd13, %rd17};
; SM90PTX83-NEXT:    mov.b128 swap, {%rd5, %rd9};
; SM90PTX83-NEXT:    atom.relaxed.sys.cas.b128 dst, [%rd1], cmp, swap;
; SM90PTX83-NEXT:    mov.b128 {%rd18, %rd19}, dst;
; SM90PTX83-NEXT:    }
; SM90PTX83-NEXT:    xor.b64 %rd20, %rd19, %rd17;
; SM90PTX83-NEXT:    xor.b64 %rd21, %rd18, %rd13;
; SM90PTX83-NEXT:    or.b64 %rd22, %rd21, %rd20;
; SM90PTX83-NEXT:    mov.b64 {_, %r12}, %rd19;
; SM90PTX83-NEXT:    cvt.u32.u64 %r11, %rd19;
; SM90PTX83-NEXT:    mov.b64 {_, %r10}, %rd18;
; SM90PTX83-NEXT:    cvt.u32.u64 %r9, %rd18;
; SM90PTX83-NEXT:    setp.ne.b64 %p1, %rd22, 0;
; SM90PTX83-NEXT:    @%p1 bra $L__BB5_1;
; SM90PTX83-NEXT:  // %bb.2: // %atomicrmw.end
; SM90PTX83-NEXT:    st.param::func.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90PTX83-NEXT:    ret;
;
; SM90PTX81-LABEL: fmin_v8f16_elementwise(
; SM90PTX81:       {
; SM90PTX81-NEXT:    .reg .pred %p<3>;
; SM90PTX81-NEXT:    .reg .b32 %r<13>;
; SM90PTX81-NEXT:    .reg .b64 %rd<20>;
; SM90PTX81-EMPTY:
; SM90PTX81-NEXT:  // %bb.0: // %entry
; SM90PTX81-NEXT:    ld.param.b64 %rd1, [fmin_v8f16_elementwise_param_0];
; SM90PTX81-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fmin_v8f16_elementwise_param_1];
; SM90PTX81-NEXT:    ld.v2.b32 {%r9, %r10}, [%rd1];
; SM90PTX81-NEXT:  $L__BB5_1: // %atomicrmw.start
; SM90PTX81-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90PTX81-NEXT:    min.f16x2 %r5, %r9, %r1;
; SM90PTX81-NEXT:    cvt.u64.u32 %rd2, %r5;
; SM90PTX81-NEXT:    min.f16x2 %r6, %r10, %r2;
; SM90PTX81-NEXT:    cvt.u64.u32 %rd3, %r6;
; SM90PTX81-NEXT:    shl.b64 %rd4, %rd3, 32;
; SM90PTX81-NEXT:    or.b64 %rd5, %rd2, %rd4;
; SM90PTX81-NEXT:    cvt.u64.u32 %rd6, %r9;
; SM90PTX81-NEXT:    cvt.u64.u32 %rd7, %r10;
; SM90PTX81-NEXT:    shl.b64 %rd8, %rd7, 32;
; SM90PTX81-NEXT:    or.b64 %rd9, %rd6, %rd8;
; SM90PTX81-NEXT:    atom.relaxed.sys.cas.b64 %rd10, [%rd1], %rd9, %rd5;
; SM90PTX81-NEXT:    setp.ne.b64 %p1, %rd10, %rd9;
; SM90PTX81-NEXT:    mov.b64 {_, %r10}, %rd10;
; SM90PTX81-NEXT:    cvt.u32.u64 %r9, %rd10;
; SM90PTX81-NEXT:    @%p1 bra $L__BB5_1;
; SM90PTX81-NEXT:  // %bb.2: // %atomicrmw.end
; SM90PTX81-NEXT:    ld.v2.b32 {%r11, %r12}, [%rd1+8];
; SM90PTX81-NEXT:  $L__BB5_3: // %atomicrmw.start3
; SM90PTX81-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90PTX81-NEXT:    min.f16x2 %r7, %r11, %r3;
; SM90PTX81-NEXT:    cvt.u64.u32 %rd11, %r7;
; SM90PTX81-NEXT:    min.f16x2 %r8, %r12, %r4;
; SM90PTX81-NEXT:    cvt.u64.u32 %rd12, %r8;
; SM90PTX81-NEXT:    shl.b64 %rd13, %rd12, 32;
; SM90PTX81-NEXT:    or.b64 %rd14, %rd11, %rd13;
; SM90PTX81-NEXT:    cvt.u64.u32 %rd15, %r11;
; SM90PTX81-NEXT:    cvt.u64.u32 %rd16, %r12;
; SM90PTX81-NEXT:    shl.b64 %rd17, %rd16, 32;
; SM90PTX81-NEXT:    or.b64 %rd18, %rd15, %rd17;
; SM90PTX81-NEXT:    atom.relaxed.sys.cas.b64 %rd19, [%rd1+8], %rd18, %rd14;
; SM90PTX81-NEXT:    setp.ne.b64 %p2, %rd19, %rd18;
; SM90PTX81-NEXT:    mov.b64 {_, %r12}, %rd19;
; SM90PTX81-NEXT:    cvt.u32.u64 %r11, %rd19;
; SM90PTX81-NEXT:    @%p2 bra $L__BB5_3;
; SM90PTX81-NEXT:  // %bb.4: // %atomicrmw.end2
; SM90PTX81-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90PTX81-NEXT:    ret;
;
; SM90PTX78-LABEL: fmin_v8f16_elementwise(
; SM90PTX78:       {
; SM90PTX78-NEXT:    .reg .pred %p<3>;
; SM90PTX78-NEXT:    .reg .b32 %r<13>;
; SM90PTX78-NEXT:    .reg .b64 %rd<20>;
; SM90PTX78-EMPTY:
; SM90PTX78-NEXT:  // %bb.0: // %entry
; SM90PTX78-NEXT:    ld.param.b64 %rd1, [fmin_v8f16_elementwise_param_0];
; SM90PTX78-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fmin_v8f16_elementwise_param_1];
; SM90PTX78-NEXT:    ld.v2.b32 {%r9, %r10}, [%rd1];
; SM90PTX78-NEXT:  $L__BB5_1: // %atomicrmw.start
; SM90PTX78-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90PTX78-NEXT:    min.f16x2 %r5, %r9, %r1;
; SM90PTX78-NEXT:    cvt.u64.u32 %rd2, %r5;
; SM90PTX78-NEXT:    min.f16x2 %r6, %r10, %r2;
; SM90PTX78-NEXT:    cvt.u64.u32 %rd3, %r6;
; SM90PTX78-NEXT:    shl.b64 %rd4, %rd3, 32;
; SM90PTX78-NEXT:    or.b64 %rd5, %rd2, %rd4;
; SM90PTX78-NEXT:    cvt.u64.u32 %rd6, %r9;
; SM90PTX78-NEXT:    cvt.u64.u32 %rd7, %r10;
; SM90PTX78-NEXT:    shl.b64 %rd8, %rd7, 32;
; SM90PTX78-NEXT:    or.b64 %rd9, %rd6, %rd8;
; SM90PTX78-NEXT:    atom.relaxed.sys.cas.b64 %rd10, [%rd1], %rd9, %rd5;
; SM90PTX78-NEXT:    setp.ne.b64 %p1, %rd10, %rd9;
; SM90PTX78-NEXT:    mov.b64 {_, %r10}, %rd10;
; SM90PTX78-NEXT:    cvt.u32.u64 %r9, %rd10;
; SM90PTX78-NEXT:    @%p1 bra $L__BB5_1;
; SM90PTX78-NEXT:  // %bb.2: // %atomicrmw.end
; SM90PTX78-NEXT:    ld.v2.b32 {%r11, %r12}, [%rd1+8];
; SM90PTX78-NEXT:  $L__BB5_3: // %atomicrmw.start3
; SM90PTX78-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90PTX78-NEXT:    min.f16x2 %r7, %r11, %r3;
; SM90PTX78-NEXT:    cvt.u64.u32 %rd11, %r7;
; SM90PTX78-NEXT:    min.f16x2 %r8, %r12, %r4;
; SM90PTX78-NEXT:    cvt.u64.u32 %rd12, %r8;
; SM90PTX78-NEXT:    shl.b64 %rd13, %rd12, 32;
; SM90PTX78-NEXT:    or.b64 %rd14, %rd11, %rd13;
; SM90PTX78-NEXT:    cvt.u64.u32 %rd15, %r11;
; SM90PTX78-NEXT:    cvt.u64.u32 %rd16, %r12;
; SM90PTX78-NEXT:    shl.b64 %rd17, %rd16, 32;
; SM90PTX78-NEXT:    or.b64 %rd18, %rd15, %rd17;
; SM90PTX78-NEXT:    atom.relaxed.sys.cas.b64 %rd19, [%rd1+8], %rd18, %rd14;
; SM90PTX78-NEXT:    setp.ne.b64 %p2, %rd19, %rd18;
; SM90PTX78-NEXT:    mov.b64 {_, %r12}, %rd19;
; SM90PTX78-NEXT:    cvt.u32.u64 %r11, %rd19;
; SM90PTX78-NEXT:    @%p2 bra $L__BB5_3;
; SM90PTX78-NEXT:  // %bb.4: // %atomicrmw.end2
; SM90PTX78-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90PTX78-NEXT:    ret;
entry:
  %old = atomicrmw elementwise fmin ptr %addr, <8 x half> %val monotonic, align 16
  ret <8 x half> %old
}

; This will always get scalarized.
define <1 x float> @fadd_v1f32_elementwise(ptr %addr, <1 x float> %val) {
; SM90PTX83-LABEL: fadd_v1f32_elementwise(
; SM90PTX83:       {
; SM90PTX83-NEXT:    .reg .b32 %r<3>;
; SM90PTX83-NEXT:    .reg .b64 %rd<2>;
; SM90PTX83-EMPTY:
; SM90PTX83-NEXT:  // %bb.0: // %entry
; SM90PTX83-NEXT:    ld.param::func.b64 %rd1, [fadd_v1f32_elementwise_param_0];
; SM90PTX83-NEXT:    ld.param::func.b32 %r1, [fadd_v1f32_elementwise_param_1];
; SM90PTX83-NEXT:    atom.relaxed.sys.add.f32 %r2, [%rd1], %r1;
; SM90PTX83-NEXT:    st.param::func.b32 [func_retval0], %r2;
; SM90PTX83-NEXT:    ret;
;
; SM90PTX81-LABEL: fadd_v1f32_elementwise(
; SM90PTX81:       {
; SM90PTX81-NEXT:    .reg .b32 %r<3>;
; SM90PTX81-NEXT:    .reg .b64 %rd<2>;
; SM90PTX81-EMPTY:
; SM90PTX81-NEXT:  // %bb.0: // %entry
; SM90PTX81-NEXT:    ld.param.b64 %rd1, [fadd_v1f32_elementwise_param_0];
; SM90PTX81-NEXT:    ld.param.b32 %r1, [fadd_v1f32_elementwise_param_1];
; SM90PTX81-NEXT:    atom.relaxed.sys.add.f32 %r2, [%rd1], %r1;
; SM90PTX81-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90PTX81-NEXT:    ret;
;
; SM90PTX78-LABEL: fadd_v1f32_elementwise(
; SM90PTX78:       {
; SM90PTX78-NEXT:    .reg .b32 %r<3>;
; SM90PTX78-NEXT:    .reg .b64 %rd<2>;
; SM90PTX78-EMPTY:
; SM90PTX78-NEXT:  // %bb.0: // %entry
; SM90PTX78-NEXT:    ld.param.b64 %rd1, [fadd_v1f32_elementwise_param_0];
; SM90PTX78-NEXT:    ld.param.b32 %r1, [fadd_v1f32_elementwise_param_1];
; SM90PTX78-NEXT:    atom.relaxed.sys.add.f32 %r2, [%rd1], %r1;
; SM90PTX78-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90PTX78-NEXT:    ret;
entry:
  %old = atomicrmw elementwise fadd ptr %addr, <1 x float> %val monotonic, align 4
  ret <1 x float> %old
}

; This will always get scalarized because PTX does not support integer vector atom.
define <4 x i32> @add_v4i32_elementwise(ptr %addr, <4 x i32> %val) {
; SM90PTX83-LABEL: add_v4i32_elementwise(
; SM90PTX83:       {
; SM90PTX83-NEXT:    .reg .b32 %r<9>;
; SM90PTX83-NEXT:    .reg .b64 %rd<2>;
; SM90PTX83-EMPTY:
; SM90PTX83-NEXT:  // %bb.0: // %entry
; SM90PTX83-NEXT:    ld.param::func.b64 %rd1, [add_v4i32_elementwise_param_0];
; SM90PTX83-NEXT:    ld.param::func.v4.b32 {%r1, %r2, %r3, %r4}, [add_v4i32_elementwise_param_1];
; SM90PTX83-NEXT:    atom.relaxed.sys.add.u32 %r5, [%rd1], %r1;
; SM90PTX83-NEXT:    atom.relaxed.sys.add.u32 %r6, [%rd1+4], %r2;
; SM90PTX83-NEXT:    atom.relaxed.sys.add.u32 %r7, [%rd1+8], %r3;
; SM90PTX83-NEXT:    atom.relaxed.sys.add.u32 %r8, [%rd1+12], %r4;
; SM90PTX83-NEXT:    st.param::func.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90PTX83-NEXT:    ret;
;
; SM90PTX81-LABEL: add_v4i32_elementwise(
; SM90PTX81:       {
; SM90PTX81-NEXT:    .reg .b32 %r<9>;
; SM90PTX81-NEXT:    .reg .b64 %rd<2>;
; SM90PTX81-EMPTY:
; SM90PTX81-NEXT:  // %bb.0: // %entry
; SM90PTX81-NEXT:    ld.param.b64 %rd1, [add_v4i32_elementwise_param_0];
; SM90PTX81-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [add_v4i32_elementwise_param_1];
; SM90PTX81-NEXT:    atom.relaxed.sys.add.u32 %r5, [%rd1], %r1;
; SM90PTX81-NEXT:    atom.relaxed.sys.add.u32 %r6, [%rd1+4], %r2;
; SM90PTX81-NEXT:    atom.relaxed.sys.add.u32 %r7, [%rd1+8], %r3;
; SM90PTX81-NEXT:    atom.relaxed.sys.add.u32 %r8, [%rd1+12], %r4;
; SM90PTX81-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90PTX81-NEXT:    ret;
;
; SM90PTX78-LABEL: add_v4i32_elementwise(
; SM90PTX78:       {
; SM90PTX78-NEXT:    .reg .b32 %r<9>;
; SM90PTX78-NEXT:    .reg .b64 %rd<2>;
; SM90PTX78-EMPTY:
; SM90PTX78-NEXT:  // %bb.0: // %entry
; SM90PTX78-NEXT:    ld.param.b64 %rd1, [add_v4i32_elementwise_param_0];
; SM90PTX78-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [add_v4i32_elementwise_param_1];
; SM90PTX78-NEXT:    atom.relaxed.sys.add.u32 %r5, [%rd1], %r1;
; SM90PTX78-NEXT:    atom.relaxed.sys.add.u32 %r6, [%rd1+4], %r2;
; SM90PTX78-NEXT:    atom.relaxed.sys.add.u32 %r7, [%rd1+8], %r3;
; SM90PTX78-NEXT:    atom.relaxed.sys.add.u32 %r8, [%rd1+12], %r4;
; SM90PTX78-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90PTX78-NEXT:    ret;
entry:
  %old = atomicrmw volatile elementwise add ptr %addr, <4 x i32> %val monotonic, align 16
  ret <4 x i32> %old
}

; +ptx83 produces a 128-bit cmpxchg loop. +ptx81 and +ptx78 produce two 64-bit cmpxchg loops.
; These will never produce vector atomics because PTX does not support double vector atom.
define <4 x double> @fmax_v4f64_elementwise(ptr %addr, <4 x double> %val) {
; SM90PTX83-LABEL: fmax_v4f64_elementwise(
; SM90PTX83:       {
; SM90PTX83-NEXT:    .reg .pred %p<3>;
; SM90PTX83-NEXT:    .reg .b64 %rd<24>;
; SM90PTX83-EMPTY:
; SM90PTX83-NEXT:  // %bb.0: // %entry
; SM90PTX83-NEXT:    ld.param::func.b64 %rd9, [fmax_v4f64_elementwise_param_0];
; SM90PTX83-NEXT:    ld.param::func.v2.b64 {%rd1, %rd2}, [fmax_v4f64_elementwise_param_1];
; SM90PTX83-NEXT:    ld.param::func.v2.b64 {%rd3, %rd4}, [fmax_v4f64_elementwise_param_1+16];
; SM90PTX83-NEXT:    ld.v2.b64 {%rd20, %rd21}, [%rd9];
; SM90PTX83-NEXT:  $L__BB9_1: // %atomicrmw.start
; SM90PTX83-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90PTX83-NEXT:    max.f64 %rd10, %rd20, %rd1;
; SM90PTX83-NEXT:    max.f64 %rd11, %rd21, %rd2;
; SM90PTX83-NEXT:    {
; SM90PTX83-NEXT:    .reg .b128 cmp, swap, dst;
; SM90PTX83-NEXT:    mov.b128 cmp, {%rd20, %rd21};
; SM90PTX83-NEXT:    mov.b128 swap, {%rd10, %rd11};
; SM90PTX83-NEXT:    atom.relaxed.sys.cas.b128 dst, [%rd9], cmp, swap;
; SM90PTX83-NEXT:    mov.b128 {%rd5, %rd6}, dst;
; SM90PTX83-NEXT:    }
; SM90PTX83-NEXT:    xor.b64 %rd12, %rd6, %rd21;
; SM90PTX83-NEXT:    xor.b64 %rd13, %rd5, %rd20;
; SM90PTX83-NEXT:    or.b64 %rd14, %rd13, %rd12;
; SM90PTX83-NEXT:    setp.ne.b64 %p1, %rd14, 0;
; SM90PTX83-NEXT:    mov.b64 %rd20, %rd5;
; SM90PTX83-NEXT:    mov.b64 %rd21, %rd6;
; SM90PTX83-NEXT:    @%p1 bra $L__BB9_1;
; SM90PTX83-NEXT:  // %bb.2: // %atomicrmw.end
; SM90PTX83-NEXT:    ld.v2.b64 {%rd22, %rd23}, [%rd9+16];
; SM90PTX83-NEXT:  $L__BB9_3: // %atomicrmw.start3
; SM90PTX83-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90PTX83-NEXT:    max.f64 %rd15, %rd22, %rd3;
; SM90PTX83-NEXT:    max.f64 %rd16, %rd23, %rd4;
; SM90PTX83-NEXT:    {
; SM90PTX83-NEXT:    .reg .b128 cmp, swap, dst;
; SM90PTX83-NEXT:    mov.b128 cmp, {%rd22, %rd23};
; SM90PTX83-NEXT:    mov.b128 swap, {%rd15, %rd16};
; SM90PTX83-NEXT:    atom.relaxed.sys.cas.b128 dst, [%rd9+16], cmp, swap;
; SM90PTX83-NEXT:    mov.b128 {%rd7, %rd8}, dst;
; SM90PTX83-NEXT:    }
; SM90PTX83-NEXT:    xor.b64 %rd17, %rd8, %rd23;
; SM90PTX83-NEXT:    xor.b64 %rd18, %rd7, %rd22;
; SM90PTX83-NEXT:    or.b64 %rd19, %rd18, %rd17;
; SM90PTX83-NEXT:    setp.ne.b64 %p2, %rd19, 0;
; SM90PTX83-NEXT:    mov.b64 %rd22, %rd7;
; SM90PTX83-NEXT:    mov.b64 %rd23, %rd8;
; SM90PTX83-NEXT:    @%p2 bra $L__BB9_3;
; SM90PTX83-NEXT:  // %bb.4: // %atomicrmw.end2
; SM90PTX83-NEXT:    st.param::func.v2.b64 [func_retval0+16], {%rd7, %rd8};
; SM90PTX83-NEXT:    st.param::func.v2.b64 [func_retval0], {%rd5, %rd6};
; SM90PTX83-NEXT:    ret;
;
; SM90PTX81-LABEL: fmax_v4f64_elementwise(
; SM90PTX81:       {
; SM90PTX81-NEXT:    .reg .pred %p<5>;
; SM90PTX81-NEXT:    .reg .b64 %rd<18>;
; SM90PTX81-EMPTY:
; SM90PTX81-NEXT:  // %bb.0: // %entry
; SM90PTX81-NEXT:    ld.param.b64 %rd9, [fmax_v4f64_elementwise_param_0];
; SM90PTX81-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [fmax_v4f64_elementwise_param_1+16];
; SM90PTX81-NEXT:    ld.param.v2.b64 {%rd3, %rd4}, [fmax_v4f64_elementwise_param_1];
; SM90PTX81-NEXT:    ld.b64 %rd14, [%rd9];
; SM90PTX81-NEXT:  $L__BB9_1: // %atomicrmw.start
; SM90PTX81-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90PTX81-NEXT:    mov.b64 %rd5, %rd14;
; SM90PTX81-NEXT:    max.f64 %rd10, %rd5, %rd3;
; SM90PTX81-NEXT:    atom.relaxed.sys.cas.b64 %rd14, [%rd9], %rd5, %rd10;
; SM90PTX81-NEXT:    setp.ne.b64 %p1, %rd14, %rd5;
; SM90PTX81-NEXT:    @%p1 bra $L__BB9_1;
; SM90PTX81-NEXT:  // %bb.2: // %atomicrmw.end
; SM90PTX81-NEXT:    ld.b64 %rd15, [%rd9+8];
; SM90PTX81-NEXT:  $L__BB9_3: // %atomicrmw.start6
; SM90PTX81-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90PTX81-NEXT:    mov.b64 %rd6, %rd15;
; SM90PTX81-NEXT:    max.f64 %rd11, %rd6, %rd4;
; SM90PTX81-NEXT:    atom.relaxed.sys.cas.b64 %rd15, [%rd9+8], %rd6, %rd11;
; SM90PTX81-NEXT:    setp.ne.b64 %p2, %rd15, %rd6;
; SM90PTX81-NEXT:    @%p2 bra $L__BB9_3;
; SM90PTX81-NEXT:  // %bb.4: // %atomicrmw.end5
; SM90PTX81-NEXT:    ld.b64 %rd16, [%rd9+16];
; SM90PTX81-NEXT:  $L__BB9_5: // %atomicrmw.start16
; SM90PTX81-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90PTX81-NEXT:    max.f64 %rd12, %rd16, %rd1;
; SM90PTX81-NEXT:    atom.relaxed.sys.cas.b64 %rd7, [%rd9+16], %rd16, %rd12;
; SM90PTX81-NEXT:    setp.ne.b64 %p3, %rd7, %rd16;
; SM90PTX81-NEXT:    mov.b64 %rd16, %rd7;
; SM90PTX81-NEXT:    @%p3 bra $L__BB9_5;
; SM90PTX81-NEXT:  // %bb.6: // %atomicrmw.end15
; SM90PTX81-NEXT:    ld.b64 %rd17, [%rd9+24];
; SM90PTX81-NEXT:  $L__BB9_7: // %atomicrmw.start21
; SM90PTX81-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90PTX81-NEXT:    max.f64 %rd13, %rd17, %rd2;
; SM90PTX81-NEXT:    atom.relaxed.sys.cas.b64 %rd8, [%rd9+24], %rd17, %rd13;
; SM90PTX81-NEXT:    setp.ne.b64 %p4, %rd8, %rd17;
; SM90PTX81-NEXT:    mov.b64 %rd17, %rd8;
; SM90PTX81-NEXT:    @%p4 bra $L__BB9_7;
; SM90PTX81-NEXT:  // %bb.8: // %atomicrmw.end20
; SM90PTX81-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd7, %rd8};
; SM90PTX81-NEXT:    st.param.v2.b64 [func_retval0], {%rd14, %rd15};
; SM90PTX81-NEXT:    ret;
;
; SM90PTX78-LABEL: fmax_v4f64_elementwise(
; SM90PTX78:       {
; SM90PTX78-NEXT:    .reg .pred %p<5>;
; SM90PTX78-NEXT:    .reg .b64 %rd<18>;
; SM90PTX78-EMPTY:
; SM90PTX78-NEXT:  // %bb.0: // %entry
; SM90PTX78-NEXT:    ld.param.b64 %rd9, [fmax_v4f64_elementwise_param_0];
; SM90PTX78-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [fmax_v4f64_elementwise_param_1+16];
; SM90PTX78-NEXT:    ld.param.v2.b64 {%rd3, %rd4}, [fmax_v4f64_elementwise_param_1];
; SM90PTX78-NEXT:    ld.b64 %rd14, [%rd9];
; SM90PTX78-NEXT:  $L__BB9_1: // %atomicrmw.start
; SM90PTX78-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90PTX78-NEXT:    mov.b64 %rd5, %rd14;
; SM90PTX78-NEXT:    max.f64 %rd10, %rd5, %rd3;
; SM90PTX78-NEXT:    atom.relaxed.sys.cas.b64 %rd14, [%rd9], %rd5, %rd10;
; SM90PTX78-NEXT:    setp.ne.b64 %p1, %rd14, %rd5;
; SM90PTX78-NEXT:    @%p1 bra $L__BB9_1;
; SM90PTX78-NEXT:  // %bb.2: // %atomicrmw.end
; SM90PTX78-NEXT:    ld.b64 %rd15, [%rd9+8];
; SM90PTX78-NEXT:  $L__BB9_3: // %atomicrmw.start6
; SM90PTX78-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90PTX78-NEXT:    mov.b64 %rd6, %rd15;
; SM90PTX78-NEXT:    max.f64 %rd11, %rd6, %rd4;
; SM90PTX78-NEXT:    atom.relaxed.sys.cas.b64 %rd15, [%rd9+8], %rd6, %rd11;
; SM90PTX78-NEXT:    setp.ne.b64 %p2, %rd15, %rd6;
; SM90PTX78-NEXT:    @%p2 bra $L__BB9_3;
; SM90PTX78-NEXT:  // %bb.4: // %atomicrmw.end5
; SM90PTX78-NEXT:    ld.b64 %rd16, [%rd9+16];
; SM90PTX78-NEXT:  $L__BB9_5: // %atomicrmw.start16
; SM90PTX78-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90PTX78-NEXT:    max.f64 %rd12, %rd16, %rd1;
; SM90PTX78-NEXT:    atom.relaxed.sys.cas.b64 %rd7, [%rd9+16], %rd16, %rd12;
; SM90PTX78-NEXT:    setp.ne.b64 %p3, %rd7, %rd16;
; SM90PTX78-NEXT:    mov.b64 %rd16, %rd7;
; SM90PTX78-NEXT:    @%p3 bra $L__BB9_5;
; SM90PTX78-NEXT:  // %bb.6: // %atomicrmw.end15
; SM90PTX78-NEXT:    ld.b64 %rd17, [%rd9+24];
; SM90PTX78-NEXT:  $L__BB9_7: // %atomicrmw.start21
; SM90PTX78-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90PTX78-NEXT:    max.f64 %rd13, %rd17, %rd2;
; SM90PTX78-NEXT:    atom.relaxed.sys.cas.b64 %rd8, [%rd9+24], %rd17, %rd13;
; SM90PTX78-NEXT:    setp.ne.b64 %p4, %rd8, %rd17;
; SM90PTX78-NEXT:    mov.b64 %rd17, %rd8;
; SM90PTX78-NEXT:    @%p4 bra $L__BB9_7;
; SM90PTX78-NEXT:  // %bb.8: // %atomicrmw.end20
; SM90PTX78-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd7, %rd8};
; SM90PTX78-NEXT:    st.param.v2.b64 [func_retval0], {%rd14, %rd15};
; SM90PTX78-NEXT:    ret;
entry:
  %old = atomicrmw elementwise fmax ptr %addr, <4 x double> %val monotonic, align 32
  ret <4 x double> %old
}
