; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -march=nvptx64 -mcpu=sm_90 -mattr=+ptx87 | FileCheck %s --check-prefix=SM90
; RUN: %if ptxas-sm_90 && ptxas-isa-8.7 %{ llc < %s -march=nvptx64 -mcpu=sm_90 -mattr=+ptx87 | %ptxas-verify -arch=sm_90 %}

define <1 x i8> @xchg_acq_rel_v1i8_global_cta(ptr addrspace(1) %addr, <1 x i8> %val) {
; SM90-LABEL: xchg_acq_rel_v1i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<14>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [xchg_acq_rel_v1i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b8 %r5, [xchg_acq_rel_v1i8_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r6, %rd2;
; SM90-NEXT:    and.b32 %r7, %r6, 3;
; SM90-NEXT:    shl.b32 %r1, %r7, 3;
; SM90-NEXT:    mov.b32 %r8, 255;
; SM90-NEXT:    shl.b32 %r9, %r8, %r1;
; SM90-NEXT:    not.b32 %r2, %r9;
; SM90-NEXT:    shl.b32 %r3, %r5, %r1;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r13, [%rd1];
; SM90-NEXT:  $L__BB0_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b32 %r10, %r13, %r2;
; SM90-NEXT:    or.b32 %r11, %r10, %r3;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r4, [%rd1], %r13, %r11;
; SM90-NEXT:    setp.ne.b32 %p1, %r4, %r13;
; SM90-NEXT:    mov.b32 %r13, %r4;
; SM90-NEXT:    @%p1 bra $L__BB0_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r12, %r4, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b8 [func_retval0], %r12;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xchg ptr  addrspace(1) %addr, <1 x i8> %val syncscope("block") acq_rel
        ret <1 x i8> %retval
}

define <2 x i8> @xchg_acq_rel_v2i8_global_cta(ptr addrspace(1) %addr, <2 x i8> %val) {
; SM90-LABEL: xchg_acq_rel_v2i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<14>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [xchg_acq_rel_v2i8_global_cta_param_0];
; SM90-NEXT:    ld.param.b16 %r5, [xchg_acq_rel_v2i8_global_cta_param_1];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r6, %rd2;
; SM90-NEXT:    and.b32 %r7, %r6, 3;
; SM90-NEXT:    shl.b32 %r1, %r7, 3;
; SM90-NEXT:    mov.b32 %r8, 65535;
; SM90-NEXT:    shl.b32 %r9, %r8, %r1;
; SM90-NEXT:    not.b32 %r2, %r9;
; SM90-NEXT:    shl.b32 %r3, %r5, %r1;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r13, [%rd1];
; SM90-NEXT:  $L__BB1_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b32 %r10, %r13, %r2;
; SM90-NEXT:    or.b32 %r11, %r10, %r3;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r4, [%rd1], %r13, %r11;
; SM90-NEXT:    setp.ne.b32 %p1, %r4, %r13;
; SM90-NEXT:    mov.b32 %r13, %r4;
; SM90-NEXT:    @%p1 bra $L__BB1_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r12, %r4, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r12;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xchg ptr  addrspace(1) %addr, <2 x i8> %val syncscope("block") acq_rel
        ret <2 x i8> %retval
}

define <4 x i8> @xchg_acq_rel_v4i8_global_cta(ptr addrspace(1) %addr, <4 x i8> %val) {
; SM90-LABEL: xchg_acq_rel_v4i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<3>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [xchg_acq_rel_v4i8_global_cta_param_0];
; SM90-NEXT:    ld.param.b32 %r1, [xchg_acq_rel_v4i8_global_cta_param_1];
; SM90-NEXT:    atom.acq_rel.cta.global.exch.b32 %r2, [%rd1], %r1;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xchg ptr  addrspace(1) %addr, <4 x i8> %val syncscope("block") acq_rel
        ret <4 x i8> %retval
}

define <8 x i8> @xchg_acq_rel_v8i8_global_cta(ptr addrspace(1) %addr, <8 x i8> %val) {
; SM90-LABEL: xchg_acq_rel_v8i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<4>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [xchg_acq_rel_v8i8_global_cta_param_0];
; SM90-NEXT:    ld.param.b64 %rd2, [xchg_acq_rel_v8i8_global_cta_param_1];
; SM90-NEXT:    atom.acq_rel.cta.global.exch.b64 %rd3, [%rd1], %rd2;
; SM90-NEXT:    st.param.b64 [func_retval0], %rd3;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xchg ptr  addrspace(1) %addr, <8 x i8> %val syncscope("block") acq_rel
        ret <8 x i8> %retval
}

define <1 x i16> @xchg_acq_rel_v1i16_global_cta(ptr addrspace(1) %addr, <1 x i16> %val) {
; SM90-LABEL: xchg_acq_rel_v1i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<14>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [xchg_acq_rel_v1i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b16 %r5, [xchg_acq_rel_v1i16_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r6, %rd2;
; SM90-NEXT:    and.b32 %r7, %r6, 3;
; SM90-NEXT:    shl.b32 %r1, %r7, 3;
; SM90-NEXT:    mov.b32 %r8, 65535;
; SM90-NEXT:    shl.b32 %r9, %r8, %r1;
; SM90-NEXT:    not.b32 %r2, %r9;
; SM90-NEXT:    shl.b32 %r3, %r5, %r1;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r13, [%rd1];
; SM90-NEXT:  $L__BB4_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b32 %r10, %r13, %r2;
; SM90-NEXT:    or.b32 %r11, %r10, %r3;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r4, [%rd1], %r13, %r11;
; SM90-NEXT:    setp.ne.b32 %p1, %r4, %r13;
; SM90-NEXT:    mov.b32 %r13, %r4;
; SM90-NEXT:    @%p1 bra $L__BB4_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r12, %r4, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r12;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xchg ptr  addrspace(1) %addr, <1 x i16> %val syncscope("block") acq_rel
        ret <1 x i16> %retval
}

define <2 x i16> @xchg_acq_rel_v2i16_global_cta(ptr addrspace(1) %addr, <2 x i16> %val) {
; SM90-LABEL: xchg_acq_rel_v2i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<3>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [xchg_acq_rel_v2i16_global_cta_param_0];
; SM90-NEXT:    ld.param.b32 %r1, [xchg_acq_rel_v2i16_global_cta_param_1];
; SM90-NEXT:    atom.acq_rel.cta.global.exch.b32 %r2, [%rd1], %r1;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xchg ptr  addrspace(1) %addr, <2 x i16> %val syncscope("block") acq_rel
        ret <2 x i16> %retval
}

define <4 x i16> @xchg_acq_rel_v4i16_global_cta(ptr addrspace(1) %addr, <4 x i16> %val) {
; SM90-LABEL: xchg_acq_rel_v4i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<4>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [xchg_acq_rel_v4i16_global_cta_param_0];
; SM90-NEXT:    ld.param.b64 %rd2, [xchg_acq_rel_v4i16_global_cta_param_1];
; SM90-NEXT:    atom.acq_rel.cta.global.exch.b64 %rd3, [%rd1], %rd2;
; SM90-NEXT:    st.param.b64 [func_retval0], %rd3;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xchg ptr  addrspace(1) %addr, <4 x i16> %val syncscope("block") acq_rel
        ret <4 x i16> %retval
}

define <8 x i16> @xchg_acq_rel_v8i16_global_cta(ptr addrspace(1) %addr, <8 x i16> %val) {
; SM90-LABEL: xchg_acq_rel_v8i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<6>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [xchg_acq_rel_v8i16_global_cta_param_0];
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [xchg_acq_rel_v8i16_global_cta_param_1];
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 amt, dst;
; SM90-NEXT:    mov.b128 amt, {%rd2, %rd3};
; SM90-NEXT:    atom.acq_rel.cta.global.exch.b128 dst, [%rd1], amt;
; SM90-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd4, %rd5};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xchg ptr  addrspace(1) %addr, <8 x i16> %val syncscope("block") acq_rel
        ret <8 x i16> %retval
}

define <1 x i32> @xchg_acq_rel_v1i32_global_cta(ptr addrspace(1) %addr, <1 x i32> %val) {
; SM90-LABEL: xchg_acq_rel_v1i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<3>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [xchg_acq_rel_v1i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b32 %r1, [xchg_acq_rel_v1i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.exch.b32 %r2, [%rd1], %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xchg ptr  addrspace(1) %addr, <1 x i32> %val syncscope("block") acq_rel
        ret <1 x i32> %retval
}

define <2 x i32> @xchg_acq_rel_v2i32_global_cta(ptr addrspace(1) %addr, <2 x i32> %val) {
; SM90-LABEL: xchg_acq_rel_v2i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [xchg_acq_rel_v2i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [xchg_acq_rel_v2i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.exch.b32 %r3, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.exch.b32 %r4, [%rd1+4], %r2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r3, %r4};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xchg ptr  addrspace(1) %addr, <2 x i32> %val syncscope("block") acq_rel
        ret <2 x i32> %retval
}

define <4 x i32> @xchg_acq_rel_v4i32_global_cta(ptr addrspace(1) %addr, <4 x i32> %val) {
; SM90-LABEL: xchg_acq_rel_v4i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<9>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [xchg_acq_rel_v4i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [xchg_acq_rel_v4i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.exch.b32 %r5, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.exch.b32 %r6, [%rd1+4], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.exch.b32 %r7, [%rd1+8], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.exch.b32 %r8, [%rd1+12], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xchg ptr  addrspace(1) %addr, <4 x i32> %val syncscope("block") acq_rel
        ret <4 x i32> %retval
}

define <8 x i32> @xchg_acq_rel_v8i32_global_cta(ptr addrspace(1) %addr, <8 x i32> %val) {
; SM90-LABEL: xchg_acq_rel_v8i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<17>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [xchg_acq_rel_v8i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [xchg_acq_rel_v8i32_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [xchg_acq_rel_v8i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.exch.b32 %r9, [%rd1], %r5;
; SM90-NEXT:    atom.relaxed.cta.global.exch.b32 %r10, [%rd1+4], %r6;
; SM90-NEXT:    atom.relaxed.cta.global.exch.b32 %r11, [%rd1+8], %r7;
; SM90-NEXT:    atom.relaxed.cta.global.exch.b32 %r12, [%rd1+12], %r8;
; SM90-NEXT:    atom.relaxed.cta.global.exch.b32 %r13, [%rd1+16], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.exch.b32 %r14, [%rd1+20], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.exch.b32 %r15, [%rd1+24], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.exch.b32 %r16, [%rd1+28], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r13, %r14, %r15, %r16};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xchg ptr  addrspace(1) %addr, <8 x i32> %val syncscope("block") acq_rel
        ret <8 x i32> %retval
}

define <1 x i64> @xchg_acq_rel_v1i64_global_cta(ptr addrspace(1) %addr, <1 x i64> %val) {
; SM90-LABEL: xchg_acq_rel_v1i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<4>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [xchg_acq_rel_v1i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b64 %rd2, [xchg_acq_rel_v1i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.exch.b64 %rd3, [%rd1], %rd2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b64 [func_retval0], %rd3;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xchg ptr  addrspace(1) %addr, <1 x i64> %val syncscope("block") acq_rel
        ret <1 x i64> %retval
}

define <2 x i64> @xchg_acq_rel_v2i64_global_cta(ptr addrspace(1) %addr, <2 x i64> %val) {
; SM90-LABEL: xchg_acq_rel_v2i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<6>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [xchg_acq_rel_v2i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [xchg_acq_rel_v2i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.exch.b64 %rd4, [%rd1], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.exch.b64 %rd5, [%rd1+8], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd4, %rd5};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xchg ptr  addrspace(1) %addr, <2 x i64> %val syncscope("block") acq_rel
        ret <2 x i64> %retval
}

define <4 x i64> @xchg_acq_rel_v4i64_global_cta(ptr addrspace(1) %addr, <4 x i64> %val) {
; SM90-LABEL: xchg_acq_rel_v4i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<10>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [xchg_acq_rel_v4i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [xchg_acq_rel_v4i64_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [xchg_acq_rel_v4i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.exch.b64 %rd6, [%rd1], %rd4;
; SM90-NEXT:    atom.relaxed.cta.global.exch.b64 %rd7, [%rd1+8], %rd5;
; SM90-NEXT:    atom.relaxed.cta.global.exch.b64 %rd8, [%rd1+16], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.exch.b64 %rd9, [%rd1+24], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd8, %rd9};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd6, %rd7};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xchg ptr  addrspace(1) %addr, <4 x i64> %val syncscope("block") acq_rel
        ret <4 x i64> %retval
}

define <8 x i64> @xchg_acq_rel_v8i64_global_cta(ptr addrspace(1) %addr, <8 x i64> %val) {
; SM90-LABEL: xchg_acq_rel_v8i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<18>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [xchg_acq_rel_v8i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [xchg_acq_rel_v8i64_global_cta_param_1+48];
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [xchg_acq_rel_v8i64_global_cta_param_1+32];
; SM90-NEXT:    ld.param.v2.b64 {%rd6, %rd7}, [xchg_acq_rel_v8i64_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v2.b64 {%rd8, %rd9}, [xchg_acq_rel_v8i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.exch.b64 %rd10, [%rd1], %rd8;
; SM90-NEXT:    atom.relaxed.cta.global.exch.b64 %rd11, [%rd1+8], %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.exch.b64 %rd12, [%rd1+16], %rd6;
; SM90-NEXT:    atom.relaxed.cta.global.exch.b64 %rd13, [%rd1+24], %rd7;
; SM90-NEXT:    atom.relaxed.cta.global.exch.b64 %rd14, [%rd1+32], %rd4;
; SM90-NEXT:    atom.relaxed.cta.global.exch.b64 %rd15, [%rd1+40], %rd5;
; SM90-NEXT:    atom.relaxed.cta.global.exch.b64 %rd16, [%rd1+48], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.exch.b64 %rd17, [%rd1+56], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+48], {%rd16, %rd17};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+32], {%rd14, %rd15};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd12, %rd13};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd10, %rd11};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xchg ptr  addrspace(1) %addr, <8 x i64> %val syncscope("block") acq_rel
        ret <8 x i64> %retval
}

define <1 x i8> @add_acq_rel_v1i8_global_cta(ptr addrspace(1) %addr, <1 x i8> %val) {
; SM90-LABEL: add_acq_rel_v1i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<16>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [add_acq_rel_v1i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b8 %r6, [add_acq_rel_v1i8_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd2;
; SM90-NEXT:    and.b32 %r8, %r7, 3;
; SM90-NEXT:    shl.b32 %r1, %r8, 3;
; SM90-NEXT:    mov.b32 %r9, 255;
; SM90-NEXT:    shl.b32 %r2, %r9, %r1;
; SM90-NEXT:    not.b32 %r3, %r2;
; SM90-NEXT:    shl.b32 %r4, %r6, %r1;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r15, [%rd1];
; SM90-NEXT:  $L__BB16_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    add.s32 %r10, %r15, %r4;
; SM90-NEXT:    and.b32 %r11, %r10, %r2;
; SM90-NEXT:    and.b32 %r12, %r15, %r3;
; SM90-NEXT:    or.b32 %r13, %r12, %r11;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r5, [%rd1], %r15, %r13;
; SM90-NEXT:    setp.ne.b32 %p1, %r5, %r15;
; SM90-NEXT:    mov.b32 %r15, %r5;
; SM90-NEXT:    @%p1 bra $L__BB16_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r14, %r5, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b8 [func_retval0], %r14;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <1 x i8> %val syncscope("block") acq_rel
        ret <1 x i8> %retval
}

define <2 x i8> @add_acq_rel_v2i8_global_cta(ptr addrspace(1) %addr, <2 x i8> %val) {
; SM90-LABEL: add_acq_rel_v2i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<10>;
; SM90-NEXT:    .reg .b32 %r<18>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b8 {%rs1, %rs2}, [add_acq_rel_v2i8_global_cta_param_1];
; SM90-NEXT:    mov.b32 %r4, {%rs1, %rs2};
; SM90-NEXT:    ld.param.b64 %rd2, [add_acq_rel_v2i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:    and.b32 %r6, %r5, 3;
; SM90-NEXT:    shl.b32 %r1, %r6, 3;
; SM90-NEXT:    mov.b32 %r7, 65535;
; SM90-NEXT:    shl.b32 %r8, %r7, %r1;
; SM90-NEXT:    not.b32 %r2, %r8;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r17, [%rd1];
; SM90-NEXT:  $L__BB17_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r9, %r17, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs3, %r9;
; SM90-NEXT:    shr.u16 %rs4, %rs3, 8;
; SM90-NEXT:    mov.b32 %r10, {%rs3, %rs4};
; SM90-NEXT:    add.s16x2 %r11, %r10, %r4;
; SM90-NEXT:    mov.b32 {%rs5, %rs6}, %r11;
; SM90-NEXT:    shl.b16 %rs7, %rs6, 8;
; SM90-NEXT:    and.b16 %rs8, %rs5, 255;
; SM90-NEXT:    or.b16 %rs9, %rs8, %rs7;
; SM90-NEXT:    cvt.u32.u16 %r12, %rs9;
; SM90-NEXT:    shl.b32 %r13, %r12, %r1;
; SM90-NEXT:    and.b32 %r14, %r17, %r2;
; SM90-NEXT:    or.b32 %r15, %r14, %r13;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r17, %r15;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r17;
; SM90-NEXT:    mov.b32 %r17, %r3;
; SM90-NEXT:    @%p1 bra $L__BB17_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r16, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r16;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <2 x i8> %val syncscope("block") acq_rel
        ret <2 x i8> %retval
}

define <4 x i8> @add_acq_rel_v4i8_global_cta(ptr addrspace(1) %addr, <4 x i8> %val) {
; SM90-LABEL: add_acq_rel_v4i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<13>;
; SM90-NEXT:    .reg .b32 %r<19>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [add_acq_rel_v4i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [add_acq_rel_v4i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r18, [%rd1];
; SM90-NEXT:    prmt.b32 %r3, %r2, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs1, %r3;
; SM90-NEXT:    prmt.b32 %r6, %r2, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs4, %r6;
; SM90-NEXT:    prmt.b32 %r10, %r2, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs7, %r10;
; SM90-NEXT:    prmt.b32 %r13, %r2, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs10, %r13;
; SM90-NEXT:  $L__BB18_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    prmt.b32 %r4, %r18, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r4;
; SM90-NEXT:    add.s16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r5, %rs3;
; SM90-NEXT:    prmt.b32 %r7, %r18, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs5, %r7;
; SM90-NEXT:    add.s16 %rs6, %rs5, %rs4;
; SM90-NEXT:    cvt.u32.u16 %r8, %rs6;
; SM90-NEXT:    prmt.b32 %r9, %r8, %r5, 0x3340U;
; SM90-NEXT:    prmt.b32 %r11, %r18, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs8, %r11;
; SM90-NEXT:    add.s16 %rs9, %rs8, %rs7;
; SM90-NEXT:    cvt.u32.u16 %r12, %rs9;
; SM90-NEXT:    prmt.b32 %r14, %r18, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs11, %r14;
; SM90-NEXT:    add.s16 %rs12, %rs11, %rs10;
; SM90-NEXT:    cvt.u32.u16 %r15, %rs12;
; SM90-NEXT:    prmt.b32 %r16, %r15, %r12, 0x3340U;
; SM90-NEXT:    prmt.b32 %r17, %r16, %r9, 0x5410U;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r18, %r17;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r18;
; SM90-NEXT:    mov.b32 %r18, %r1;
; SM90-NEXT:    @%p1 bra $L__BB18_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <4 x i8> %val syncscope("block") acq_rel
        ret <4 x i8> %retval
}

define <8 x i8> @add_acq_rel_v8i8_global_cta(ptr addrspace(1) %addr, <8 x i8> %val) {
; SM90-LABEL: add_acq_rel_v8i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<25>;
; SM90-NEXT:    .reg .b32 %r<35>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [add_acq_rel_v8i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [add_acq_rel_v8i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r34}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r33, %rd2;
; SM90-NEXT:    prmt.b32 %r3, %r1, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs1, %r3;
; SM90-NEXT:    prmt.b32 %r6, %r1, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs4, %r6;
; SM90-NEXT:    prmt.b32 %r10, %r1, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs7, %r10;
; SM90-NEXT:    prmt.b32 %r13, %r1, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs10, %r13;
; SM90-NEXT:    prmt.b32 %r18, %r2, 0, 0x7773U;
; SM90-NEXT:    prmt.b32 %r21, %r2, 0, 0x7772U;
; SM90-NEXT:  $L__BB19_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    prmt.b32 %r4, %r33, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r4;
; SM90-NEXT:    add.s16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r5, %rs3;
; SM90-NEXT:    prmt.b32 %r7, %r33, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs5, %r7;
; SM90-NEXT:    add.s16 %rs6, %rs5, %rs4;
; SM90-NEXT:    cvt.u32.u16 %r8, %rs6;
; SM90-NEXT:    prmt.b32 %r9, %r8, %r5, 0x3340U;
; SM90-NEXT:    prmt.b32 %r11, %r33, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs8, %r11;
; SM90-NEXT:    add.s16 %rs9, %rs8, %rs7;
; SM90-NEXT:    cvt.u32.u16 %r12, %rs9;
; SM90-NEXT:    prmt.b32 %r14, %r33, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs11, %r14;
; SM90-NEXT:    add.s16 %rs12, %rs11, %rs10;
; SM90-NEXT:    cvt.u32.u16 %r15, %rs12;
; SM90-NEXT:    prmt.b32 %r16, %r15, %r12, 0x3340U;
; SM90-NEXT:    prmt.b32 %r17, %r16, %r9, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r17;
; SM90-NEXT:    cvt.u16.u32 %rs13, %r18;
; SM90-NEXT:    prmt.b32 %r19, %r34, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs14, %r19;
; SM90-NEXT:    add.s16 %rs15, %rs14, %rs13;
; SM90-NEXT:    cvt.u32.u16 %r20, %rs15;
; SM90-NEXT:    cvt.u16.u32 %rs16, %r21;
; SM90-NEXT:    prmt.b32 %r22, %r34, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs17, %r22;
; SM90-NEXT:    add.s16 %rs18, %rs17, %rs16;
; SM90-NEXT:    cvt.u32.u16 %r23, %rs18;
; SM90-NEXT:    prmt.b32 %r24, %r23, %r20, 0x3340U;
; SM90-NEXT:    prmt.b32 %r25, %r2, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs19, %r25;
; SM90-NEXT:    prmt.b32 %r26, %r34, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs20, %r26;
; SM90-NEXT:    add.s16 %rs21, %rs20, %rs19;
; SM90-NEXT:    cvt.u32.u16 %r27, %rs21;
; SM90-NEXT:    prmt.b32 %r28, %r2, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs22, %r28;
; SM90-NEXT:    prmt.b32 %r29, %r34, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs23, %r29;
; SM90-NEXT:    add.s16 %rs24, %rs23, %rs22;
; SM90-NEXT:    cvt.u32.u16 %r30, %rs24;
; SM90-NEXT:    prmt.b32 %r31, %r30, %r27, 0x3340U;
; SM90-NEXT:    prmt.b32 %r32, %r31, %r24, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r32;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r33;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r34;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r34}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r33, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB19_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r33, %r34};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <8 x i8> %val syncscope("block") acq_rel
        ret <8 x i8> %retval
}

define <1 x i16> @add_acq_rel_v1i16_global_cta(ptr addrspace(1) %addr, <1 x i16> %val) {
; SM90-LABEL: add_acq_rel_v1i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<16>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [add_acq_rel_v1i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b16 %r6, [add_acq_rel_v1i16_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd2;
; SM90-NEXT:    and.b32 %r8, %r7, 3;
; SM90-NEXT:    shl.b32 %r1, %r8, 3;
; SM90-NEXT:    mov.b32 %r9, 65535;
; SM90-NEXT:    shl.b32 %r2, %r9, %r1;
; SM90-NEXT:    not.b32 %r3, %r2;
; SM90-NEXT:    shl.b32 %r4, %r6, %r1;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r15, [%rd1];
; SM90-NEXT:  $L__BB20_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    add.s32 %r10, %r15, %r4;
; SM90-NEXT:    and.b32 %r11, %r10, %r2;
; SM90-NEXT:    and.b32 %r12, %r15, %r3;
; SM90-NEXT:    or.b32 %r13, %r12, %r11;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r5, [%rd1], %r15, %r13;
; SM90-NEXT:    setp.ne.b32 %p1, %r5, %r15;
; SM90-NEXT:    mov.b32 %r15, %r5;
; SM90-NEXT:    @%p1 bra $L__BB20_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r14, %r5, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r14;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <1 x i16> %val syncscope("block") acq_rel
        ret <1 x i16> %retval
}

define <2 x i16> @add_acq_rel_v2i16_global_cta(ptr addrspace(1) %addr, <2 x i16> %val) {
; SM90-LABEL: add_acq_rel_v2i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [add_acq_rel_v2i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [add_acq_rel_v2i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:  $L__BB21_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    add.s16x2 %r3, %r4, %r2;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r4;
; SM90-NEXT:    mov.b32 %r4, %r1;
; SM90-NEXT:    @%p1 bra $L__BB21_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <2 x i16> %val syncscope("block") acq_rel
        ret <2 x i16> %retval
}

define <4 x i16> @add_acq_rel_v4i16_global_cta(ptr addrspace(1) %addr, <4 x i16> %val) {
; SM90-LABEL: add_acq_rel_v4i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [add_acq_rel_v4i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [add_acq_rel_v4i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB22_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    add.s16x2 %r3, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r3;
; SM90-NEXT:    add.s16x2 %r4, %r6, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r4;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB22_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <4 x i16> %val syncscope("block") acq_rel
        ret <4 x i16> %retval
}

define <8 x i16> @add_acq_rel_v8i16_global_cta(ptr addrspace(1) %addr, <8 x i16> %val) {
; SM90-LABEL: add_acq_rel_v8i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [add_acq_rel_v8i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [add_acq_rel_v8i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB23_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    add.s16x2 %r5, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd5, %r5;
; SM90-NEXT:    add.s16x2 %r6, %r10, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r6;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    add.s16x2 %r7, %r11, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r7;
; SM90-NEXT:    add.s16x2 %r8, %r12, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r8;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r10;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r12;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd22;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB23_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <8 x i16> %val syncscope("block") acq_rel
        ret <8 x i16> %retval
}

define <1 x i32> @add_acq_rel_v1i32_global_cta(ptr addrspace(1) %addr, <1 x i32> %val) {
; SM90-LABEL: add_acq_rel_v1i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<3>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [add_acq_rel_v1i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b32 %r1, [add_acq_rel_v1i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r2, [%rd1], %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <1 x i32> %val syncscope("block") acq_rel
        ret <1 x i32> %retval
}

define <2 x i32> @add_acq_rel_v2i32_global_cta(ptr addrspace(1) %addr, <2 x i32> %val) {
; SM90-LABEL: add_acq_rel_v2i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [add_acq_rel_v2i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [add_acq_rel_v2i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r3, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r4, [%rd1+4], %r2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r3, %r4};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <2 x i32> %val syncscope("block") acq_rel
        ret <2 x i32> %retval
}

define <4 x i32> @add_acq_rel_v4i32_global_cta(ptr addrspace(1) %addr, <4 x i32> %val) {
; SM90-LABEL: add_acq_rel_v4i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<9>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [add_acq_rel_v4i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [add_acq_rel_v4i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r5, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r6, [%rd1+4], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r7, [%rd1+8], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r8, [%rd1+12], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <4 x i32> %val syncscope("block") acq_rel
        ret <4 x i32> %retval
}

define <8 x i32> @add_acq_rel_v8i32_global_cta(ptr addrspace(1) %addr, <8 x i32> %val) {
; SM90-LABEL: add_acq_rel_v8i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<17>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [add_acq_rel_v8i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [add_acq_rel_v8i32_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [add_acq_rel_v8i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r9, [%rd1], %r5;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r10, [%rd1+4], %r6;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r11, [%rd1+8], %r7;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r12, [%rd1+12], %r8;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r13, [%rd1+16], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r14, [%rd1+20], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r15, [%rd1+24], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r16, [%rd1+28], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r13, %r14, %r15, %r16};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <8 x i32> %val syncscope("block") acq_rel
        ret <8 x i32> %retval
}

define <1 x i64> @add_acq_rel_v1i64_global_cta(ptr addrspace(1) %addr, <1 x i64> %val) {
; SM90-LABEL: add_acq_rel_v1i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<4>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [add_acq_rel_v1i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b64 %rd2, [add_acq_rel_v1i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd3, [%rd1], %rd2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b64 [func_retval0], %rd3;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <1 x i64> %val syncscope("block") acq_rel
        ret <1 x i64> %retval
}

define <2 x i64> @add_acq_rel_v2i64_global_cta(ptr addrspace(1) %addr, <2 x i64> %val) {
; SM90-LABEL: add_acq_rel_v2i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<6>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [add_acq_rel_v2i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [add_acq_rel_v2i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd4, [%rd1], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd5, [%rd1+8], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd4, %rd5};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <2 x i64> %val syncscope("block") acq_rel
        ret <2 x i64> %retval
}

define <4 x i64> @add_acq_rel_v4i64_global_cta(ptr addrspace(1) %addr, <4 x i64> %val) {
; SM90-LABEL: add_acq_rel_v4i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<10>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [add_acq_rel_v4i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [add_acq_rel_v4i64_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [add_acq_rel_v4i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd6, [%rd1], %rd4;
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd7, [%rd1+8], %rd5;
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd8, [%rd1+16], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd9, [%rd1+24], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd8, %rd9};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd6, %rd7};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <4 x i64> %val syncscope("block") acq_rel
        ret <4 x i64> %retval
}

define <8 x i64> @add_acq_rel_v8i64_global_cta(ptr addrspace(1) %addr, <8 x i64> %val) {
; SM90-LABEL: add_acq_rel_v8i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<18>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [add_acq_rel_v8i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [add_acq_rel_v8i64_global_cta_param_1+48];
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [add_acq_rel_v8i64_global_cta_param_1+32];
; SM90-NEXT:    ld.param.v2.b64 {%rd6, %rd7}, [add_acq_rel_v8i64_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v2.b64 {%rd8, %rd9}, [add_acq_rel_v8i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd10, [%rd1], %rd8;
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd11, [%rd1+8], %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd12, [%rd1+16], %rd6;
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd13, [%rd1+24], %rd7;
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd14, [%rd1+32], %rd4;
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd15, [%rd1+40], %rd5;
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd16, [%rd1+48], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd17, [%rd1+56], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+48], {%rd16, %rd17};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+32], {%rd14, %rd15};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd12, %rd13};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd10, %rd11};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <8 x i64> %val syncscope("block") acq_rel
        ret <8 x i64> %retval
}

define <1 x i8> @sub_acq_rel_v1i8_global_cta(ptr addrspace(1) %addr, <1 x i8> %val) {
; SM90-LABEL: sub_acq_rel_v1i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<16>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [sub_acq_rel_v1i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b8 %r6, [sub_acq_rel_v1i8_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd2;
; SM90-NEXT:    and.b32 %r8, %r7, 3;
; SM90-NEXT:    shl.b32 %r1, %r8, 3;
; SM90-NEXT:    mov.b32 %r9, 255;
; SM90-NEXT:    shl.b32 %r2, %r9, %r1;
; SM90-NEXT:    not.b32 %r3, %r2;
; SM90-NEXT:    shl.b32 %r4, %r6, %r1;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r15, [%rd1];
; SM90-NEXT:  $L__BB32_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    sub.s32 %r10, %r15, %r4;
; SM90-NEXT:    and.b32 %r11, %r10, %r2;
; SM90-NEXT:    and.b32 %r12, %r15, %r3;
; SM90-NEXT:    or.b32 %r13, %r12, %r11;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r5, [%rd1], %r15, %r13;
; SM90-NEXT:    setp.ne.b32 %p1, %r5, %r15;
; SM90-NEXT:    mov.b32 %r15, %r5;
; SM90-NEXT:    @%p1 bra $L__BB32_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r14, %r5, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b8 [func_retval0], %r14;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise sub ptr  addrspace(1) %addr, <1 x i8> %val syncscope("block") acq_rel
        ret <1 x i8> %retval
}

define <2 x i8> @sub_acq_rel_v2i8_global_cta(ptr addrspace(1) %addr, <2 x i8> %val) {
; SM90-LABEL: sub_acq_rel_v2i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<12>;
; SM90-NEXT:    .reg .b32 %r<16>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b8 {%rs1, %rs2}, [sub_acq_rel_v2i8_global_cta_param_1];
; SM90-NEXT:    mov.b32 %r4, {%rs1, %rs2};
; SM90-NEXT:    ld.param.b64 %rd2, [sub_acq_rel_v2i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:    and.b32 %r6, %r5, 3;
; SM90-NEXT:    shl.b32 %r1, %r6, 3;
; SM90-NEXT:    mov.b32 %r7, 65535;
; SM90-NEXT:    shl.b32 %r8, %r7, %r1;
; SM90-NEXT:    not.b32 %r2, %r8;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r15, [%rd1];
; SM90-NEXT:    mov.b32 {%rs5, %rs6}, %r4;
; SM90-NEXT:  $L__BB33_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r9, %r15, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs3, %r9;
; SM90-NEXT:    shr.u16 %rs4, %rs3, 8;
; SM90-NEXT:    sub.s16 %rs7, %rs4, %rs6;
; SM90-NEXT:    sub.s16 %rs8, %rs3, %rs5;
; SM90-NEXT:    and.b16 %rs9, %rs8, 255;
; SM90-NEXT:    shl.b16 %rs10, %rs7, 8;
; SM90-NEXT:    or.b16 %rs11, %rs9, %rs10;
; SM90-NEXT:    cvt.u32.u16 %r10, %rs11;
; SM90-NEXT:    shl.b32 %r11, %r10, %r1;
; SM90-NEXT:    and.b32 %r12, %r15, %r2;
; SM90-NEXT:    or.b32 %r13, %r12, %r11;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r15, %r13;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r15;
; SM90-NEXT:    mov.b32 %r15, %r3;
; SM90-NEXT:    @%p1 bra $L__BB33_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r14, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r14;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise sub ptr  addrspace(1) %addr, <2 x i8> %val syncscope("block") acq_rel
        ret <2 x i8> %retval
}

define <4 x i8> @sub_acq_rel_v4i8_global_cta(ptr addrspace(1) %addr, <4 x i8> %val) {
; SM90-LABEL: sub_acq_rel_v4i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<13>;
; SM90-NEXT:    .reg .b32 %r<19>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [sub_acq_rel_v4i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [sub_acq_rel_v4i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r18, [%rd1];
; SM90-NEXT:    prmt.b32 %r3, %r2, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs1, %r3;
; SM90-NEXT:    prmt.b32 %r6, %r2, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs4, %r6;
; SM90-NEXT:    prmt.b32 %r10, %r2, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs7, %r10;
; SM90-NEXT:    prmt.b32 %r13, %r2, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs10, %r13;
; SM90-NEXT:  $L__BB34_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    prmt.b32 %r4, %r18, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r4;
; SM90-NEXT:    sub.s16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r5, %rs3;
; SM90-NEXT:    prmt.b32 %r7, %r18, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs5, %r7;
; SM90-NEXT:    sub.s16 %rs6, %rs5, %rs4;
; SM90-NEXT:    cvt.u32.u16 %r8, %rs6;
; SM90-NEXT:    prmt.b32 %r9, %r8, %r5, 0x3340U;
; SM90-NEXT:    prmt.b32 %r11, %r18, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs8, %r11;
; SM90-NEXT:    sub.s16 %rs9, %rs8, %rs7;
; SM90-NEXT:    cvt.u32.u16 %r12, %rs9;
; SM90-NEXT:    prmt.b32 %r14, %r18, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs11, %r14;
; SM90-NEXT:    sub.s16 %rs12, %rs11, %rs10;
; SM90-NEXT:    cvt.u32.u16 %r15, %rs12;
; SM90-NEXT:    prmt.b32 %r16, %r15, %r12, 0x3340U;
; SM90-NEXT:    prmt.b32 %r17, %r16, %r9, 0x5410U;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r18, %r17;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r18;
; SM90-NEXT:    mov.b32 %r18, %r1;
; SM90-NEXT:    @%p1 bra $L__BB34_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise sub ptr  addrspace(1) %addr, <4 x i8> %val syncscope("block") acq_rel
        ret <4 x i8> %retval
}

define <8 x i8> @sub_acq_rel_v8i8_global_cta(ptr addrspace(1) %addr, <8 x i8> %val) {
; SM90-LABEL: sub_acq_rel_v8i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<25>;
; SM90-NEXT:    .reg .b32 %r<35>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [sub_acq_rel_v8i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [sub_acq_rel_v8i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r34}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r33, %rd2;
; SM90-NEXT:    prmt.b32 %r3, %r1, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs1, %r3;
; SM90-NEXT:    prmt.b32 %r6, %r1, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs4, %r6;
; SM90-NEXT:    prmt.b32 %r10, %r1, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs7, %r10;
; SM90-NEXT:    prmt.b32 %r13, %r1, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs10, %r13;
; SM90-NEXT:    prmt.b32 %r18, %r2, 0, 0x7773U;
; SM90-NEXT:    prmt.b32 %r21, %r2, 0, 0x7772U;
; SM90-NEXT:  $L__BB35_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    prmt.b32 %r4, %r33, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r4;
; SM90-NEXT:    sub.s16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r5, %rs3;
; SM90-NEXT:    prmt.b32 %r7, %r33, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs5, %r7;
; SM90-NEXT:    sub.s16 %rs6, %rs5, %rs4;
; SM90-NEXT:    cvt.u32.u16 %r8, %rs6;
; SM90-NEXT:    prmt.b32 %r9, %r8, %r5, 0x3340U;
; SM90-NEXT:    prmt.b32 %r11, %r33, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs8, %r11;
; SM90-NEXT:    sub.s16 %rs9, %rs8, %rs7;
; SM90-NEXT:    cvt.u32.u16 %r12, %rs9;
; SM90-NEXT:    prmt.b32 %r14, %r33, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs11, %r14;
; SM90-NEXT:    sub.s16 %rs12, %rs11, %rs10;
; SM90-NEXT:    cvt.u32.u16 %r15, %rs12;
; SM90-NEXT:    prmt.b32 %r16, %r15, %r12, 0x3340U;
; SM90-NEXT:    prmt.b32 %r17, %r16, %r9, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r17;
; SM90-NEXT:    cvt.u16.u32 %rs13, %r18;
; SM90-NEXT:    prmt.b32 %r19, %r34, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs14, %r19;
; SM90-NEXT:    sub.s16 %rs15, %rs14, %rs13;
; SM90-NEXT:    cvt.u32.u16 %r20, %rs15;
; SM90-NEXT:    cvt.u16.u32 %rs16, %r21;
; SM90-NEXT:    prmt.b32 %r22, %r34, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs17, %r22;
; SM90-NEXT:    sub.s16 %rs18, %rs17, %rs16;
; SM90-NEXT:    cvt.u32.u16 %r23, %rs18;
; SM90-NEXT:    prmt.b32 %r24, %r23, %r20, 0x3340U;
; SM90-NEXT:    prmt.b32 %r25, %r2, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs19, %r25;
; SM90-NEXT:    prmt.b32 %r26, %r34, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs20, %r26;
; SM90-NEXT:    sub.s16 %rs21, %rs20, %rs19;
; SM90-NEXT:    cvt.u32.u16 %r27, %rs21;
; SM90-NEXT:    prmt.b32 %r28, %r2, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs22, %r28;
; SM90-NEXT:    prmt.b32 %r29, %r34, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs23, %r29;
; SM90-NEXT:    sub.s16 %rs24, %rs23, %rs22;
; SM90-NEXT:    cvt.u32.u16 %r30, %rs24;
; SM90-NEXT:    prmt.b32 %r31, %r30, %r27, 0x3340U;
; SM90-NEXT:    prmt.b32 %r32, %r31, %r24, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r32;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r33;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r34;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r34}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r33, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB35_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r33, %r34};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise sub ptr  addrspace(1) %addr, <8 x i8> %val syncscope("block") acq_rel
        ret <8 x i8> %retval
}

define <1 x i16> @sub_acq_rel_v1i16_global_cta(ptr addrspace(1) %addr, <1 x i16> %val) {
; SM90-LABEL: sub_acq_rel_v1i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<16>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [sub_acq_rel_v1i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b16 %r6, [sub_acq_rel_v1i16_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd2;
; SM90-NEXT:    and.b32 %r8, %r7, 3;
; SM90-NEXT:    shl.b32 %r1, %r8, 3;
; SM90-NEXT:    mov.b32 %r9, 65535;
; SM90-NEXT:    shl.b32 %r2, %r9, %r1;
; SM90-NEXT:    not.b32 %r3, %r2;
; SM90-NEXT:    shl.b32 %r4, %r6, %r1;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r15, [%rd1];
; SM90-NEXT:  $L__BB36_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    sub.s32 %r10, %r15, %r4;
; SM90-NEXT:    and.b32 %r11, %r10, %r2;
; SM90-NEXT:    and.b32 %r12, %r15, %r3;
; SM90-NEXT:    or.b32 %r13, %r12, %r11;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r5, [%rd1], %r15, %r13;
; SM90-NEXT:    setp.ne.b32 %p1, %r5, %r15;
; SM90-NEXT:    mov.b32 %r15, %r5;
; SM90-NEXT:    @%p1 bra $L__BB36_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r14, %r5, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r14;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise sub ptr  addrspace(1) %addr, <1 x i16> %val syncscope("block") acq_rel
        ret <1 x i16> %retval
}

define <2 x i16> @sub_acq_rel_v2i16_global_cta(ptr addrspace(1) %addr, <2 x i16> %val) {
; SM90-LABEL: sub_acq_rel_v2i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<7>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [sub_acq_rel_v2i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [sub_acq_rel_v2i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:    mov.b32 {%rs1, %rs2}, %r2;
; SM90-NEXT:  $L__BB37_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    mov.b32 {%rs3, %rs4}, %r4;
; SM90-NEXT:    sub.s16 %rs5, %rs4, %rs2;
; SM90-NEXT:    sub.s16 %rs6, %rs3, %rs1;
; SM90-NEXT:    mov.b32 %r3, {%rs6, %rs5};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r4;
; SM90-NEXT:    mov.b32 %r4, %r1;
; SM90-NEXT:    @%p1 bra $L__BB37_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise sub ptr  addrspace(1) %addr, <2 x i16> %val syncscope("block") acq_rel
        ret <2 x i16> %retval
}

define <4 x i16> @sub_acq_rel_v4i16_global_cta(ptr addrspace(1) %addr, <4 x i16> %val) {
; SM90-LABEL: sub_acq_rel_v4i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<13>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [sub_acq_rel_v4i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [sub_acq_rel_v4i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:    mov.b32 {%rs1, %rs2}, %r1;
; SM90-NEXT:    mov.b32 {%rs7, %rs8}, %r2;
; SM90-NEXT:  $L__BB38_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    mov.b32 {%rs3, %rs4}, %r5;
; SM90-NEXT:    sub.s16 %rs5, %rs4, %rs2;
; SM90-NEXT:    sub.s16 %rs6, %rs3, %rs1;
; SM90-NEXT:    mov.b32 %r3, {%rs6, %rs5};
; SM90-NEXT:    cvt.u64.u32 %rd3, %r3;
; SM90-NEXT:    mov.b32 {%rs9, %rs10}, %r6;
; SM90-NEXT:    sub.s16 %rs11, %rs10, %rs8;
; SM90-NEXT:    sub.s16 %rs12, %rs9, %rs7;
; SM90-NEXT:    mov.b32 %r4, {%rs12, %rs11};
; SM90-NEXT:    cvt.u64.u32 %rd4, %r4;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB38_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise sub ptr  addrspace(1) %addr, <4 x i16> %val syncscope("block") acq_rel
        ret <4 x i16> %retval
}

define <8 x i16> @sub_acq_rel_v8i16_global_cta(ptr addrspace(1) %addr, <8 x i16> %val) {
; SM90-LABEL: sub_acq_rel_v8i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<25>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [sub_acq_rel_v8i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [sub_acq_rel_v8i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:    mov.b32 {%rs1, %rs2}, %r1;
; SM90-NEXT:    mov.b32 {%rs7, %rs8}, %r2;
; SM90-NEXT:  $L__BB39_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    mov.b32 {%rs3, %rs4}, %r9;
; SM90-NEXT:    sub.s16 %rs5, %rs4, %rs2;
; SM90-NEXT:    sub.s16 %rs6, %rs3, %rs1;
; SM90-NEXT:    mov.b32 %r5, {%rs6, %rs5};
; SM90-NEXT:    cvt.u64.u32 %rd5, %r5;
; SM90-NEXT:    mov.b32 {%rs9, %rs10}, %r10;
; SM90-NEXT:    sub.s16 %rs11, %rs10, %rs8;
; SM90-NEXT:    sub.s16 %rs12, %rs9, %rs7;
; SM90-NEXT:    mov.b32 %r6, {%rs12, %rs11};
; SM90-NEXT:    cvt.u64.u32 %rd6, %r6;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    mov.b32 {%rs13, %rs14}, %r3;
; SM90-NEXT:    mov.b32 {%rs15, %rs16}, %r11;
; SM90-NEXT:    sub.s16 %rs17, %rs16, %rs14;
; SM90-NEXT:    sub.s16 %rs18, %rs15, %rs13;
; SM90-NEXT:    mov.b32 %r7, {%rs18, %rs17};
; SM90-NEXT:    cvt.u64.u32 %rd9, %r7;
; SM90-NEXT:    mov.b32 {%rs19, %rs20}, %r4;
; SM90-NEXT:    mov.b32 {%rs21, %rs22}, %r12;
; SM90-NEXT:    sub.s16 %rs23, %rs22, %rs20;
; SM90-NEXT:    sub.s16 %rs24, %rs21, %rs19;
; SM90-NEXT:    mov.b32 %r8, {%rs24, %rs23};
; SM90-NEXT:    cvt.u64.u32 %rd10, %r8;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r10;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r12;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd22;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB39_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise sub ptr  addrspace(1) %addr, <8 x i16> %val syncscope("block") acq_rel
        ret <8 x i16> %retval
}

define <1 x i32> @sub_acq_rel_v1i32_global_cta(ptr addrspace(1) %addr, <1 x i32> %val) {
; SM90-LABEL: sub_acq_rel_v1i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<4>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [sub_acq_rel_v1i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b32 %r1, [sub_acq_rel_v1i32_global_cta_param_1];
; SM90-NEXT:    neg.s32 %r2, %r1;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r3, [%rd1], %r2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r3;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise sub ptr  addrspace(1) %addr, <1 x i32> %val syncscope("block") acq_rel
        ret <1 x i32> %retval
}

define <2 x i32> @sub_acq_rel_v2i32_global_cta(ptr addrspace(1) %addr, <2 x i32> %val) {
; SM90-LABEL: sub_acq_rel_v2i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [sub_acq_rel_v2i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [sub_acq_rel_v2i32_global_cta_param_1];
; SM90-NEXT:    neg.s32 %r3, %r1;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r4, [%rd1], %r3;
; SM90-NEXT:    neg.s32 %r5, %r2;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r6, [%rd1+4], %r5;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r4, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise sub ptr  addrspace(1) %addr, <2 x i32> %val syncscope("block") acq_rel
        ret <2 x i32> %retval
}

define <4 x i32> @sub_acq_rel_v4i32_global_cta(ptr addrspace(1) %addr, <4 x i32> %val) {
; SM90-LABEL: sub_acq_rel_v4i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [sub_acq_rel_v4i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [sub_acq_rel_v4i32_global_cta_param_1];
; SM90-NEXT:    neg.s32 %r5, %r1;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r6, [%rd1], %r5;
; SM90-NEXT:    neg.s32 %r7, %r2;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r8, [%rd1+4], %r7;
; SM90-NEXT:    neg.s32 %r9, %r3;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r10, [%rd1+8], %r9;
; SM90-NEXT:    neg.s32 %r11, %r4;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r12, [%rd1+12], %r11;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r6, %r8, %r10, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise sub ptr  addrspace(1) %addr, <4 x i32> %val syncscope("block") acq_rel
        ret <4 x i32> %retval
}

define <8 x i32> @sub_acq_rel_v8i32_global_cta(ptr addrspace(1) %addr, <8 x i32> %val) {
; SM90-LABEL: sub_acq_rel_v8i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<25>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [sub_acq_rel_v8i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [sub_acq_rel_v8i32_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [sub_acq_rel_v8i32_global_cta_param_1];
; SM90-NEXT:    neg.s32 %r9, %r5;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r10, [%rd1], %r9;
; SM90-NEXT:    neg.s32 %r11, %r6;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r12, [%rd1+4], %r11;
; SM90-NEXT:    neg.s32 %r13, %r7;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r14, [%rd1+8], %r13;
; SM90-NEXT:    neg.s32 %r15, %r8;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r16, [%rd1+12], %r15;
; SM90-NEXT:    neg.s32 %r17, %r1;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r18, [%rd1+16], %r17;
; SM90-NEXT:    neg.s32 %r19, %r2;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r20, [%rd1+20], %r19;
; SM90-NEXT:    neg.s32 %r21, %r3;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r22, [%rd1+24], %r21;
; SM90-NEXT:    neg.s32 %r23, %r4;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r24, [%rd1+28], %r23;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r18, %r20, %r22, %r24};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r10, %r12, %r14, %r16};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise sub ptr  addrspace(1) %addr, <8 x i32> %val syncscope("block") acq_rel
        ret <8 x i32> %retval
}

define <1 x i64> @sub_acq_rel_v1i64_global_cta(ptr addrspace(1) %addr, <1 x i64> %val) {
; SM90-LABEL: sub_acq_rel_v1i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<5>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [sub_acq_rel_v1i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b64 %rd2, [sub_acq_rel_v1i64_global_cta_param_1];
; SM90-NEXT:    neg.s64 %rd3, %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd4, [%rd1], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b64 [func_retval0], %rd4;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise sub ptr  addrspace(1) %addr, <1 x i64> %val syncscope("block") acq_rel
        ret <1 x i64> %retval
}

define <2 x i64> @sub_acq_rel_v2i64_global_cta(ptr addrspace(1) %addr, <2 x i64> %val) {
; SM90-LABEL: sub_acq_rel_v2i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<8>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [sub_acq_rel_v2i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [sub_acq_rel_v2i64_global_cta_param_1];
; SM90-NEXT:    neg.s64 %rd4, %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd5, [%rd1], %rd4;
; SM90-NEXT:    neg.s64 %rd6, %rd3;
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd7, [%rd1+8], %rd6;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd5, %rd7};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise sub ptr  addrspace(1) %addr, <2 x i64> %val syncscope("block") acq_rel
        ret <2 x i64> %retval
}

define <4 x i64> @sub_acq_rel_v4i64_global_cta(ptr addrspace(1) %addr, <4 x i64> %val) {
; SM90-LABEL: sub_acq_rel_v4i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<14>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [sub_acq_rel_v4i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [sub_acq_rel_v4i64_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [sub_acq_rel_v4i64_global_cta_param_1];
; SM90-NEXT:    neg.s64 %rd6, %rd4;
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd7, [%rd1], %rd6;
; SM90-NEXT:    neg.s64 %rd8, %rd5;
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd9, [%rd1+8], %rd8;
; SM90-NEXT:    neg.s64 %rd10, %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd11, [%rd1+16], %rd10;
; SM90-NEXT:    neg.s64 %rd12, %rd3;
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd13, [%rd1+24], %rd12;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd11, %rd13};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd7, %rd9};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise sub ptr  addrspace(1) %addr, <4 x i64> %val syncscope("block") acq_rel
        ret <4 x i64> %retval
}

define <8 x i64> @sub_acq_rel_v8i64_global_cta(ptr addrspace(1) %addr, <8 x i64> %val) {
; SM90-LABEL: sub_acq_rel_v8i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [sub_acq_rel_v8i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [sub_acq_rel_v8i64_global_cta_param_1+48];
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [sub_acq_rel_v8i64_global_cta_param_1+32];
; SM90-NEXT:    ld.param.v2.b64 {%rd6, %rd7}, [sub_acq_rel_v8i64_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v2.b64 {%rd8, %rd9}, [sub_acq_rel_v8i64_global_cta_param_1];
; SM90-NEXT:    neg.s64 %rd10, %rd8;
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd11, [%rd1], %rd10;
; SM90-NEXT:    neg.s64 %rd12, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd13, [%rd1+8], %rd12;
; SM90-NEXT:    neg.s64 %rd14, %rd6;
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd15, [%rd1+16], %rd14;
; SM90-NEXT:    neg.s64 %rd16, %rd7;
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd17, [%rd1+24], %rd16;
; SM90-NEXT:    neg.s64 %rd18, %rd4;
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd19, [%rd1+32], %rd18;
; SM90-NEXT:    neg.s64 %rd20, %rd5;
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd21, [%rd1+40], %rd20;
; SM90-NEXT:    neg.s64 %rd22, %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd23, [%rd1+48], %rd22;
; SM90-NEXT:    neg.s64 %rd24, %rd3;
; SM90-NEXT:    atom.relaxed.cta.global.add.u64 %rd25, [%rd1+56], %rd24;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+48], {%rd23, %rd25};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+32], {%rd19, %rd21};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd15, %rd17};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd11, %rd13};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise sub ptr  addrspace(1) %addr, <8 x i64> %val syncscope("block") acq_rel
        ret <8 x i64> %retval
}

define <1 x i8> @and_acq_rel_v1i8_global_cta(ptr addrspace(1) %addr, <1 x i8> %val) {
; SM90-LABEL: and_acq_rel_v1i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<12>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [and_acq_rel_v1i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b8 %r1, [and_acq_rel_v1i8_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd2, %rd1, -4;
; SM90-NEXT:    cvt.u32.u64 %r2, %rd1;
; SM90-NEXT:    and.b32 %r3, %r2, 3;
; SM90-NEXT:    shl.b32 %r4, %r3, 3;
; SM90-NEXT:    mov.b32 %r5, 255;
; SM90-NEXT:    shl.b32 %r6, %r5, %r4;
; SM90-NEXT:    not.b32 %r7, %r6;
; SM90-NEXT:    shl.b32 %r8, %r1, %r4;
; SM90-NEXT:    or.b32 %r9, %r8, %r7;
; SM90-NEXT:    atom.relaxed.cta.global.and.b32 %r10, [%rd2], %r9;
; SM90-NEXT:    shr.u32 %r11, %r10, %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b8 [func_retval0], %r11;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise and ptr  addrspace(1) %addr, <1 x i8> %val syncscope("block") acq_rel
        ret <1 x i8> %retval
}

define <2 x i8> @and_acq_rel_v2i8_global_cta(ptr addrspace(1) %addr, <2 x i8> %val) {
; SM90-LABEL: and_acq_rel_v2i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<12>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [and_acq_rel_v2i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    and.b64 %rd2, %rd1, -4;
; SM90-NEXT:    cvt.u32.u64 %r1, %rd1;
; SM90-NEXT:    and.b32 %r2, %r1, 3;
; SM90-NEXT:    shl.b32 %r3, %r2, 3;
; SM90-NEXT:    mov.b32 %r4, 65535;
; SM90-NEXT:    shl.b32 %r5, %r4, %r3;
; SM90-NEXT:    not.b32 %r6, %r5;
; SM90-NEXT:    ld.param.b16 %r7, [and_acq_rel_v2i8_global_cta_param_1];
; SM90-NEXT:    shl.b32 %r8, %r7, %r3;
; SM90-NEXT:    or.b32 %r9, %r8, %r6;
; SM90-NEXT:    atom.relaxed.cta.global.and.b32 %r10, [%rd2], %r9;
; SM90-NEXT:    shr.u32 %r11, %r10, %r3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r11;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise and ptr  addrspace(1) %addr, <2 x i8> %val syncscope("block") acq_rel
        ret <2 x i8> %retval
}

define <4 x i8> @and_acq_rel_v4i8_global_cta(ptr addrspace(1) %addr, <4 x i8> %val) {
; SM90-LABEL: and_acq_rel_v4i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [and_acq_rel_v4i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [and_acq_rel_v4i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:  $L__BB50_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b32 %r3, %r4, %r2;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r4;
; SM90-NEXT:    mov.b32 %r4, %r1;
; SM90-NEXT:    @%p1 bra $L__BB50_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise and ptr  addrspace(1) %addr, <4 x i8> %val syncscope("block") acq_rel
        ret <4 x i8> %retval
}

define <8 x i8> @and_acq_rel_v8i8_global_cta(ptr addrspace(1) %addr, <8 x i8> %val) {
; SM90-LABEL: and_acq_rel_v8i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [and_acq_rel_v8i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [and_acq_rel_v8i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB51_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b32 %r3, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r3;
; SM90-NEXT:    and.b32 %r4, %r6, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r4;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB51_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise and ptr  addrspace(1) %addr, <8 x i8> %val syncscope("block") acq_rel
        ret <8 x i8> %retval
}

define <1 x i16> @and_acq_rel_v1i16_global_cta(ptr addrspace(1) %addr, <1 x i16> %val) {
; SM90-LABEL: and_acq_rel_v1i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<12>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [and_acq_rel_v1i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b16 %r1, [and_acq_rel_v1i16_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd2, %rd1, -4;
; SM90-NEXT:    cvt.u32.u64 %r2, %rd1;
; SM90-NEXT:    and.b32 %r3, %r2, 3;
; SM90-NEXT:    shl.b32 %r4, %r3, 3;
; SM90-NEXT:    mov.b32 %r5, 65535;
; SM90-NEXT:    shl.b32 %r6, %r5, %r4;
; SM90-NEXT:    not.b32 %r7, %r6;
; SM90-NEXT:    shl.b32 %r8, %r1, %r4;
; SM90-NEXT:    or.b32 %r9, %r8, %r7;
; SM90-NEXT:    atom.relaxed.cta.global.and.b32 %r10, [%rd2], %r9;
; SM90-NEXT:    shr.u32 %r11, %r10, %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r11;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise and ptr  addrspace(1) %addr, <1 x i16> %val syncscope("block") acq_rel
        ret <1 x i16> %retval
}

define <2 x i16> @and_acq_rel_v2i16_global_cta(ptr addrspace(1) %addr, <2 x i16> %val) {
; SM90-LABEL: and_acq_rel_v2i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [and_acq_rel_v2i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [and_acq_rel_v2i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:  $L__BB53_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b32 %r3, %r4, %r2;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r4;
; SM90-NEXT:    mov.b32 %r4, %r1;
; SM90-NEXT:    @%p1 bra $L__BB53_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise and ptr  addrspace(1) %addr, <2 x i16> %val syncscope("block") acq_rel
        ret <2 x i16> %retval
}

define <4 x i16> @and_acq_rel_v4i16_global_cta(ptr addrspace(1) %addr, <4 x i16> %val) {
; SM90-LABEL: and_acq_rel_v4i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [and_acq_rel_v4i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [and_acq_rel_v4i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB54_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b32 %r3, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r3;
; SM90-NEXT:    and.b32 %r4, %r6, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r4;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB54_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise and ptr  addrspace(1) %addr, <4 x i16> %val syncscope("block") acq_rel
        ret <4 x i16> %retval
}

define <8 x i16> @and_acq_rel_v8i16_global_cta(ptr addrspace(1) %addr, <8 x i16> %val) {
; SM90-LABEL: and_acq_rel_v8i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [and_acq_rel_v8i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [and_acq_rel_v8i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB55_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b32 %r5, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd5, %r5;
; SM90-NEXT:    and.b32 %r6, %r10, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r6;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    and.b32 %r7, %r11, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r7;
; SM90-NEXT:    and.b32 %r8, %r12, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r8;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r10;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r12;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd22;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB55_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise and ptr  addrspace(1) %addr, <8 x i16> %val syncscope("block") acq_rel
        ret <8 x i16> %retval
}

define <1 x i32> @and_acq_rel_v1i32_global_cta(ptr addrspace(1) %addr, <1 x i32> %val) {
; SM90-LABEL: and_acq_rel_v1i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<3>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [and_acq_rel_v1i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b32 %r1, [and_acq_rel_v1i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.and.b32 %r2, [%rd1], %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise and ptr  addrspace(1) %addr, <1 x i32> %val syncscope("block") acq_rel
        ret <1 x i32> %retval
}

define <2 x i32> @and_acq_rel_v2i32_global_cta(ptr addrspace(1) %addr, <2 x i32> %val) {
; SM90-LABEL: and_acq_rel_v2i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [and_acq_rel_v2i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [and_acq_rel_v2i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.and.b32 %r3, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.and.b32 %r4, [%rd1+4], %r2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r3, %r4};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise and ptr  addrspace(1) %addr, <2 x i32> %val syncscope("block") acq_rel
        ret <2 x i32> %retval
}

define <4 x i32> @and_acq_rel_v4i32_global_cta(ptr addrspace(1) %addr, <4 x i32> %val) {
; SM90-LABEL: and_acq_rel_v4i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<9>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [and_acq_rel_v4i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [and_acq_rel_v4i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.and.b32 %r5, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.and.b32 %r6, [%rd1+4], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.and.b32 %r7, [%rd1+8], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.and.b32 %r8, [%rd1+12], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise and ptr  addrspace(1) %addr, <4 x i32> %val syncscope("block") acq_rel
        ret <4 x i32> %retval
}

define <8 x i32> @and_acq_rel_v8i32_global_cta(ptr addrspace(1) %addr, <8 x i32> %val) {
; SM90-LABEL: and_acq_rel_v8i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<17>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [and_acq_rel_v8i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [and_acq_rel_v8i32_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [and_acq_rel_v8i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.and.b32 %r9, [%rd1], %r5;
; SM90-NEXT:    atom.relaxed.cta.global.and.b32 %r10, [%rd1+4], %r6;
; SM90-NEXT:    atom.relaxed.cta.global.and.b32 %r11, [%rd1+8], %r7;
; SM90-NEXT:    atom.relaxed.cta.global.and.b32 %r12, [%rd1+12], %r8;
; SM90-NEXT:    atom.relaxed.cta.global.and.b32 %r13, [%rd1+16], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.and.b32 %r14, [%rd1+20], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.and.b32 %r15, [%rd1+24], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.and.b32 %r16, [%rd1+28], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r13, %r14, %r15, %r16};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise and ptr  addrspace(1) %addr, <8 x i32> %val syncscope("block") acq_rel
        ret <8 x i32> %retval
}

define <1 x i64> @and_acq_rel_v1i64_global_cta(ptr addrspace(1) %addr, <1 x i64> %val) {
; SM90-LABEL: and_acq_rel_v1i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<4>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [and_acq_rel_v1i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b64 %rd2, [and_acq_rel_v1i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.and.b64 %rd3, [%rd1], %rd2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b64 [func_retval0], %rd3;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise and ptr  addrspace(1) %addr, <1 x i64> %val syncscope("block") acq_rel
        ret <1 x i64> %retval
}

define <2 x i64> @and_acq_rel_v2i64_global_cta(ptr addrspace(1) %addr, <2 x i64> %val) {
; SM90-LABEL: and_acq_rel_v2i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<6>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [and_acq_rel_v2i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [and_acq_rel_v2i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.and.b64 %rd4, [%rd1], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.and.b64 %rd5, [%rd1+8], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd4, %rd5};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise and ptr  addrspace(1) %addr, <2 x i64> %val syncscope("block") acq_rel
        ret <2 x i64> %retval
}

define <4 x i64> @and_acq_rel_v4i64_global_cta(ptr addrspace(1) %addr, <4 x i64> %val) {
; SM90-LABEL: and_acq_rel_v4i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<10>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [and_acq_rel_v4i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [and_acq_rel_v4i64_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [and_acq_rel_v4i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.and.b64 %rd6, [%rd1], %rd4;
; SM90-NEXT:    atom.relaxed.cta.global.and.b64 %rd7, [%rd1+8], %rd5;
; SM90-NEXT:    atom.relaxed.cta.global.and.b64 %rd8, [%rd1+16], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.and.b64 %rd9, [%rd1+24], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd8, %rd9};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd6, %rd7};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise and ptr  addrspace(1) %addr, <4 x i64> %val syncscope("block") acq_rel
        ret <4 x i64> %retval
}

define <8 x i64> @and_acq_rel_v8i64_global_cta(ptr addrspace(1) %addr, <8 x i64> %val) {
; SM90-LABEL: and_acq_rel_v8i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<18>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [and_acq_rel_v8i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [and_acq_rel_v8i64_global_cta_param_1+48];
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [and_acq_rel_v8i64_global_cta_param_1+32];
; SM90-NEXT:    ld.param.v2.b64 {%rd6, %rd7}, [and_acq_rel_v8i64_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v2.b64 {%rd8, %rd9}, [and_acq_rel_v8i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.and.b64 %rd10, [%rd1], %rd8;
; SM90-NEXT:    atom.relaxed.cta.global.and.b64 %rd11, [%rd1+8], %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.and.b64 %rd12, [%rd1+16], %rd6;
; SM90-NEXT:    atom.relaxed.cta.global.and.b64 %rd13, [%rd1+24], %rd7;
; SM90-NEXT:    atom.relaxed.cta.global.and.b64 %rd14, [%rd1+32], %rd4;
; SM90-NEXT:    atom.relaxed.cta.global.and.b64 %rd15, [%rd1+40], %rd5;
; SM90-NEXT:    atom.relaxed.cta.global.and.b64 %rd16, [%rd1+48], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.and.b64 %rd17, [%rd1+56], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+48], {%rd16, %rd17};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+32], {%rd14, %rd15};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd12, %rd13};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd10, %rd11};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise and ptr  addrspace(1) %addr, <8 x i64> %val syncscope("block") acq_rel
        ret <8 x i64> %retval
}

define <1 x i8> @nand_acq_rel_v1i8_global_cta(ptr addrspace(1) %addr, <1 x i8> %val) {
; SM90-LABEL: nand_acq_rel_v1i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<17>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [nand_acq_rel_v1i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b8 %r6, [nand_acq_rel_v1i8_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd2;
; SM90-NEXT:    and.b32 %r8, %r7, 3;
; SM90-NEXT:    shl.b32 %r1, %r8, 3;
; SM90-NEXT:    mov.b32 %r9, 255;
; SM90-NEXT:    shl.b32 %r2, %r9, %r1;
; SM90-NEXT:    not.b32 %r3, %r2;
; SM90-NEXT:    shl.b32 %r4, %r6, %r1;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r16, [%rd1];
; SM90-NEXT:  $L__BB64_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b32 %r10, %r16, %r4;
; SM90-NEXT:    not.b32 %r11, %r10;
; SM90-NEXT:    and.b32 %r12, %r11, %r2;
; SM90-NEXT:    and.b32 %r13, %r16, %r3;
; SM90-NEXT:    or.b32 %r14, %r13, %r12;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r5, [%rd1], %r16, %r14;
; SM90-NEXT:    setp.ne.b32 %p1, %r5, %r16;
; SM90-NEXT:    mov.b32 %r16, %r5;
; SM90-NEXT:    @%p1 bra $L__BB64_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r15, %r5, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b8 [func_retval0], %r15;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <1 x i8> %val syncscope("block") acq_rel
        ret <1 x i8> %retval
}

define <2 x i8> @nand_acq_rel_v2i8_global_cta(ptr addrspace(1) %addr, <2 x i8> %val) {
; SM90-LABEL: nand_acq_rel_v2i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<9>;
; SM90-NEXT:    .reg .b32 %r<19>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b8 {%rs1, %rs2}, [nand_acq_rel_v2i8_global_cta_param_1];
; SM90-NEXT:    mov.b32 %r4, {%rs1, %rs2};
; SM90-NEXT:    ld.param.b64 %rd2, [nand_acq_rel_v2i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:    and.b32 %r6, %r5, 3;
; SM90-NEXT:    shl.b32 %r1, %r6, 3;
; SM90-NEXT:    mov.b32 %r7, 65535;
; SM90-NEXT:    shl.b32 %r8, %r7, %r1;
; SM90-NEXT:    not.b32 %r2, %r8;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r18, [%rd1];
; SM90-NEXT:  $L__BB65_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r9, %r18, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs3, %r9;
; SM90-NEXT:    shr.u16 %rs4, %rs3, 8;
; SM90-NEXT:    mov.b32 %r10, {%rs3, %rs4};
; SM90-NEXT:    and.b32 %r11, %r10, %r4;
; SM90-NEXT:    xor.b32 %r12, %r11, 16711935;
; SM90-NEXT:    mov.b32 {%rs5, %rs6}, %r12;
; SM90-NEXT:    shl.b16 %rs7, %rs6, 8;
; SM90-NEXT:    or.b16 %rs8, %rs5, %rs7;
; SM90-NEXT:    cvt.u32.u16 %r13, %rs8;
; SM90-NEXT:    shl.b32 %r14, %r13, %r1;
; SM90-NEXT:    and.b32 %r15, %r18, %r2;
; SM90-NEXT:    or.b32 %r16, %r15, %r14;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r18, %r16;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r18;
; SM90-NEXT:    mov.b32 %r18, %r3;
; SM90-NEXT:    @%p1 bra $L__BB65_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r17, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r17;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <2 x i8> %val syncscope("block") acq_rel
        ret <2 x i8> %retval
}

define <4 x i8> @nand_acq_rel_v4i8_global_cta(ptr addrspace(1) %addr, <4 x i8> %val) {
; SM90-LABEL: nand_acq_rel_v4i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<6>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [nand_acq_rel_v4i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [nand_acq_rel_v4i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r5, [%rd1];
; SM90-NEXT:  $L__BB66_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b32 %r3, %r5, %r2;
; SM90-NEXT:    xor.b32 %r4, %r3, -1;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r5, %r4;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r5;
; SM90-NEXT:    mov.b32 %r5, %r1;
; SM90-NEXT:    @%p1 bra $L__BB66_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <4 x i8> %val syncscope("block") acq_rel
        ret <4 x i8> %retval
}

define <8 x i8> @nand_acq_rel_v8i8_global_cta(ptr addrspace(1) %addr, <8 x i8> %val) {
; SM90-LABEL: nand_acq_rel_v8i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<9>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [nand_acq_rel_v8i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [nand_acq_rel_v8i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r8}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd2;
; SM90-NEXT:  $L__BB67_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd3, %r7;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r8;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    and.b32 %r3, %r8, %r2;
; SM90-NEXT:    and.b32 %r4, %r7, %r1;
; SM90-NEXT:    xor.b32 %r5, %r4, -1;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    xor.b32 %r6, %r3, -1;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd6, %rd10;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd6;
; SM90-NEXT:    mov.b64 {_, %r8}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB67_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r7, %r8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <8 x i8> %val syncscope("block") acq_rel
        ret <8 x i8> %retval
}

define <1 x i16> @nand_acq_rel_v1i16_global_cta(ptr addrspace(1) %addr, <1 x i16> %val) {
; SM90-LABEL: nand_acq_rel_v1i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<17>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [nand_acq_rel_v1i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b16 %r6, [nand_acq_rel_v1i16_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd2;
; SM90-NEXT:    and.b32 %r8, %r7, 3;
; SM90-NEXT:    shl.b32 %r1, %r8, 3;
; SM90-NEXT:    mov.b32 %r9, 65535;
; SM90-NEXT:    shl.b32 %r2, %r9, %r1;
; SM90-NEXT:    not.b32 %r3, %r2;
; SM90-NEXT:    shl.b32 %r4, %r6, %r1;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r16, [%rd1];
; SM90-NEXT:  $L__BB68_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b32 %r10, %r16, %r4;
; SM90-NEXT:    not.b32 %r11, %r10;
; SM90-NEXT:    and.b32 %r12, %r11, %r2;
; SM90-NEXT:    and.b32 %r13, %r16, %r3;
; SM90-NEXT:    or.b32 %r14, %r13, %r12;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r5, [%rd1], %r16, %r14;
; SM90-NEXT:    setp.ne.b32 %p1, %r5, %r16;
; SM90-NEXT:    mov.b32 %r16, %r5;
; SM90-NEXT:    @%p1 bra $L__BB68_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r15, %r5, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r15;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <1 x i16> %val syncscope("block") acq_rel
        ret <1 x i16> %retval
}

define <2 x i16> @nand_acq_rel_v2i16_global_cta(ptr addrspace(1) %addr, <2 x i16> %val) {
; SM90-LABEL: nand_acq_rel_v2i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<6>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [nand_acq_rel_v2i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [nand_acq_rel_v2i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r5, [%rd1];
; SM90-NEXT:  $L__BB69_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b32 %r3, %r5, %r2;
; SM90-NEXT:    xor.b32 %r4, %r3, -1;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r5, %r4;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r5;
; SM90-NEXT:    mov.b32 %r5, %r1;
; SM90-NEXT:    @%p1 bra $L__BB69_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <2 x i16> %val syncscope("block") acq_rel
        ret <2 x i16> %retval
}

define <4 x i16> @nand_acq_rel_v4i16_global_cta(ptr addrspace(1) %addr, <4 x i16> %val) {
; SM90-LABEL: nand_acq_rel_v4i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<9>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [nand_acq_rel_v4i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [nand_acq_rel_v4i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r8}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd2;
; SM90-NEXT:  $L__BB70_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd3, %r7;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r8;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    and.b32 %r3, %r8, %r2;
; SM90-NEXT:    and.b32 %r4, %r7, %r1;
; SM90-NEXT:    xor.b32 %r5, %r4, -1;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    xor.b32 %r6, %r3, -1;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd6, %rd10;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd6;
; SM90-NEXT:    mov.b64 {_, %r8}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB70_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r7, %r8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <4 x i16> %val syncscope("block") acq_rel
        ret <4 x i16> %retval
}

define <8 x i16> @nand_acq_rel_v8i16_global_cta(ptr addrspace(1) %addr, <8 x i16> %val) {
; SM90-LABEL: nand_acq_rel_v8i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<17>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [nand_acq_rel_v8i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [nand_acq_rel_v8i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r16}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r15, %rd4;
; SM90-NEXT:    mov.b64 {_, %r14}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r13, %rd3;
; SM90-NEXT:  $L__BB71_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd5, %r13;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r14;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r15;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r16;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    and.b32 %r5, %r16, %r4;
; SM90-NEXT:    and.b32 %r6, %r15, %r3;
; SM90-NEXT:    and.b32 %r7, %r14, %r2;
; SM90-NEXT:    and.b32 %r8, %r13, %r1;
; SM90-NEXT:    xor.b32 %r9, %r8, -1;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r9;
; SM90-NEXT:    xor.b32 %r10, %r7, -1;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r10;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    xor.b32 %r11, %r6, -1;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r11;
; SM90-NEXT:    xor.b32 %r12, %r5, -1;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r12;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd8, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd16, %rd20};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd12;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd8;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r16}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r15, %rd22;
; SM90-NEXT:    mov.b64 {_, %r14}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r13, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB71_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r13, %r14, %r15, %r16};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <8 x i16> %val syncscope("block") acq_rel
        ret <8 x i16> %retval
}

define <1 x i32> @nand_acq_rel_v1i32_global_cta(ptr addrspace(1) %addr, <1 x i32> %val) {
; SM90-LABEL: nand_acq_rel_v1i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<6>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [nand_acq_rel_v1i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b32 %r1, [nand_acq_rel_v1i32_global_cta_param_1];
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r5, [%rd1];
; SM90-NEXT:  $L__BB72_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b32 %r3, %r5, %r1;
; SM90-NEXT:    not.b32 %r4, %r3;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r2, [%rd1], %r5, %r4;
; SM90-NEXT:    setp.ne.b32 %p1, %r2, %r5;
; SM90-NEXT:    mov.b32 %r5, %r2;
; SM90-NEXT:    @%p1 bra $L__BB72_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <1 x i32> %val syncscope("block") acq_rel
        ret <1 x i32> %retval
}

define <2 x i32> @nand_acq_rel_v2i32_global_cta(ptr addrspace(1) %addr, <2 x i32> %val) {
; SM90-LABEL: nand_acq_rel_v2i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<13>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [nand_acq_rel_v2i32_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [nand_acq_rel_v2i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB73_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd3, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r6;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    and.b32 %r3, %r6, %r2;
; SM90-NEXT:    and.b32 %r4, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r3;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    not.b64 %rd11, %rd10;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd12, [%rd1], %rd6, %rd11;
; SM90-NEXT:    setp.ne.b64 %p1, %rd12, %rd6;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd12;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd12;
; SM90-NEXT:    @%p1 bra $L__BB73_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <2 x i32> %val syncscope("block") acq_rel
        ret <2 x i32> %retval
}

define <4 x i32> @nand_acq_rel_v4i32_global_cta(ptr addrspace(1) %addr, <4 x i32> %val) {
; SM90-LABEL: nand_acq_rel_v4i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<28>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [nand_acq_rel_v4i32_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [nand_acq_rel_v4i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB74_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd5, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r10;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r12;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    and.b32 %r5, %r12, %r4;
; SM90-NEXT:    and.b32 %r6, %r11, %r3;
; SM90-NEXT:    and.b32 %r7, %r10, %r2;
; SM90-NEXT:    and.b32 %r8, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r8;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r7;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    not.b64 %rd17, %rd16;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r6;
; SM90-NEXT:    cvt.u64.u32 %rd19, %r5;
; SM90-NEXT:    shl.b64 %rd20, %rd19, 32;
; SM90-NEXT:    or.b64 %rd21, %rd18, %rd20;
; SM90-NEXT:    not.b64 %rd22, %rd21;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd8, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd17, %rd22};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd23, %rd24}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd25, %rd24, %rd12;
; SM90-NEXT:    xor.b64 %rd26, %rd23, %rd8;
; SM90-NEXT:    or.b64 %rd27, %rd26, %rd25;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd24;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd24;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd23;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd23;
; SM90-NEXT:    setp.ne.b64 %p1, %rd27, 0;
; SM90-NEXT:    @%p1 bra $L__BB74_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <4 x i32> %val syncscope("block") acq_rel
        ret <4 x i32> %retval
}

define <8 x i32> @nand_acq_rel_v8i32_global_cta(ptr addrspace(1) %addr, <8 x i32> %val) {
; SM90-LABEL: nand_acq_rel_v8i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<3>;
; SM90-NEXT:    .reg .b32 %r<25>;
; SM90-NEXT:    .reg .b64 %rd<54>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [nand_acq_rel_v8i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [nand_acq_rel_v8i32_global_cta_param_1];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [nand_acq_rel_v8i32_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r20}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r19, %rd4;
; SM90-NEXT:    mov.b64 {_, %r18}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r17, %rd3;
; SM90-NEXT:  $L__BB75_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd5, %r17;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r18;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r19;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r20;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    and.b32 %r9, %r20, %r4;
; SM90-NEXT:    and.b32 %r10, %r19, %r3;
; SM90-NEXT:    and.b32 %r11, %r18, %r2;
; SM90-NEXT:    and.b32 %r12, %r17, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r12;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r11;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    not.b64 %rd17, %rd16;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r10;
; SM90-NEXT:    cvt.u64.u32 %rd19, %r9;
; SM90-NEXT:    shl.b64 %rd20, %rd19, 32;
; SM90-NEXT:    or.b64 %rd21, %rd18, %rd20;
; SM90-NEXT:    not.b64 %rd22, %rd21;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd8, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd17, %rd22};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd23, %rd24}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd25, %rd24, %rd12;
; SM90-NEXT:    xor.b64 %rd26, %rd23, %rd8;
; SM90-NEXT:    or.b64 %rd27, %rd26, %rd25;
; SM90-NEXT:    mov.b64 {_, %r20}, %rd24;
; SM90-NEXT:    cvt.u32.u64 %r19, %rd24;
; SM90-NEXT:    mov.b64 {_, %r18}, %rd23;
; SM90-NEXT:    cvt.u32.u64 %r17, %rd23;
; SM90-NEXT:    setp.ne.b64 %p1, %rd27, 0;
; SM90-NEXT:    @%p1 bra $L__BB75_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd28, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd28, %rd28};
; SM90-NEXT:    mov.b128 swap, {%rd28, %rd28};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd29, %rd30}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r24}, %rd30;
; SM90-NEXT:    cvt.u32.u64 %r23, %rd30;
; SM90-NEXT:    mov.b64 {_, %r22}, %rd29;
; SM90-NEXT:    cvt.u32.u64 %r21, %rd29;
; SM90-NEXT:  $L__BB75_3: // %atomicrmw.start2
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd31, %r21;
; SM90-NEXT:    cvt.u64.u32 %rd32, %r22;
; SM90-NEXT:    shl.b64 %rd33, %rd32, 32;
; SM90-NEXT:    or.b64 %rd34, %rd31, %rd33;
; SM90-NEXT:    cvt.u64.u32 %rd35, %r23;
; SM90-NEXT:    cvt.u64.u32 %rd36, %r24;
; SM90-NEXT:    shl.b64 %rd37, %rd36, 32;
; SM90-NEXT:    or.b64 %rd38, %rd35, %rd37;
; SM90-NEXT:    and.b32 %r13, %r24, %r8;
; SM90-NEXT:    and.b32 %r14, %r23, %r7;
; SM90-NEXT:    and.b32 %r15, %r22, %r6;
; SM90-NEXT:    and.b32 %r16, %r21, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd39, %r16;
; SM90-NEXT:    cvt.u64.u32 %rd40, %r15;
; SM90-NEXT:    shl.b64 %rd41, %rd40, 32;
; SM90-NEXT:    or.b64 %rd42, %rd39, %rd41;
; SM90-NEXT:    not.b64 %rd43, %rd42;
; SM90-NEXT:    cvt.u64.u32 %rd44, %r14;
; SM90-NEXT:    cvt.u64.u32 %rd45, %r13;
; SM90-NEXT:    shl.b64 %rd46, %rd45, 32;
; SM90-NEXT:    or.b64 %rd47, %rd44, %rd46;
; SM90-NEXT:    not.b64 %rd48, %rd47;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd34, %rd38};
; SM90-NEXT:    mov.b128 swap, {%rd43, %rd48};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd49, %rd50}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd51, %rd50, %rd38;
; SM90-NEXT:    xor.b64 %rd52, %rd49, %rd34;
; SM90-NEXT:    or.b64 %rd53, %rd52, %rd51;
; SM90-NEXT:    mov.b64 {_, %r24}, %rd50;
; SM90-NEXT:    cvt.u32.u64 %r23, %rd50;
; SM90-NEXT:    mov.b64 {_, %r22}, %rd49;
; SM90-NEXT:    cvt.u32.u64 %r21, %rd49;
; SM90-NEXT:    setp.ne.b64 %p2, %rd53, 0;
; SM90-NEXT:    @%p2 bra $L__BB75_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end1
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r21, %r22, %r23, %r24};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r17, %r18, %r19, %r20};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <8 x i32> %val syncscope("block") acq_rel
        ret <8 x i32> %retval
}

define <1 x i64> @nand_acq_rel_v1i64_global_cta(ptr addrspace(1) %addr, <1 x i64> %val) {
; SM90-LABEL: nand_acq_rel_v1i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b64 %rd<7>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd3, [nand_acq_rel_v1i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b64 %rd1, [nand_acq_rel_v1i64_global_cta_param_1];
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd6, [%rd3];
; SM90-NEXT:  $L__BB76_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b64 %rd4, %rd6, %rd1;
; SM90-NEXT:    not.b64 %rd5, %rd4;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd2, [%rd3], %rd6, %rd5;
; SM90-NEXT:    setp.ne.b64 %p1, %rd2, %rd6;
; SM90-NEXT:    mov.b64 %rd6, %rd2;
; SM90-NEXT:    @%p1 bra $L__BB76_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b64 [func_retval0], %rd2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <1 x i64> %val syncscope("block") acq_rel
        ret <1 x i64> %retval
}

define <2 x i64> @nand_acq_rel_v2i64_global_cta(ptr addrspace(1) %addr, <2 x i64> %val) {
; SM90-LABEL: nand_acq_rel_v2i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b64 %rd<16>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [nand_acq_rel_v2i64_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd3, [nand_acq_rel_v2i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd6, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd6, %rd6};
; SM90-NEXT:    mov.b128 swap, {%rd6, %rd6};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd3], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd14, %rd15}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB77_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b64 %rd7, %rd15, %rd5;
; SM90-NEXT:    and.b64 %rd8, %rd14, %rd4;
; SM90-NEXT:    not.b64 %rd9, %rd8;
; SM90-NEXT:    not.b64 %rd10, %rd7;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd14, %rd15};
; SM90-NEXT:    mov.b128 swap, {%rd9, %rd10};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd3], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd1, %rd2}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd11, %rd2, %rd15;
; SM90-NEXT:    xor.b64 %rd12, %rd1, %rd14;
; SM90-NEXT:    or.b64 %rd13, %rd12, %rd11;
; SM90-NEXT:    setp.ne.b64 %p1, %rd13, 0;
; SM90-NEXT:    mov.b64 %rd14, %rd1;
; SM90-NEXT:    mov.b64 %rd15, %rd2;
; SM90-NEXT:    @%p1 bra $L__BB77_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd1, %rd2};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <2 x i64> %val syncscope("block") acq_rel
        ret <2 x i64> %retval
}

define <4 x i64> @nand_acq_rel_v4i64_global_cta(ptr addrspace(1) %addr, <4 x i64> %val) {
; SM90-LABEL: nand_acq_rel_v4i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<3>;
; SM90-NEXT:    .reg .b64 %rd<30>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd9, [nand_acq_rel_v4i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [nand_acq_rel_v4i64_global_cta_param_1];
; SM90-NEXT:    ld.param.v2.b64 {%rd3, %rd4}, [nand_acq_rel_v4i64_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd10, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd10, %rd10};
; SM90-NEXT:    mov.b128 swap, {%rd10, %rd10};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd26, %rd27}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB78_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b64 %rd11, %rd27, %rd2;
; SM90-NEXT:    and.b64 %rd12, %rd26, %rd1;
; SM90-NEXT:    not.b64 %rd13, %rd12;
; SM90-NEXT:    not.b64 %rd14, %rd11;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd26, %rd27};
; SM90-NEXT:    mov.b128 swap, {%rd13, %rd14};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd5, %rd6}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd15, %rd6, %rd27;
; SM90-NEXT:    xor.b64 %rd16, %rd5, %rd26;
; SM90-NEXT:    or.b64 %rd17, %rd16, %rd15;
; SM90-NEXT:    setp.ne.b64 %p1, %rd17, 0;
; SM90-NEXT:    mov.b64 %rd26, %rd5;
; SM90-NEXT:    mov.b64 %rd27, %rd6;
; SM90-NEXT:    @%p1 bra $L__BB78_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd18, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd18, %rd18};
; SM90-NEXT:    mov.b128 swap, {%rd18, %rd18};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd28, %rd29}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB78_3: // %atomicrmw.start2
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b64 %rd19, %rd29, %rd4;
; SM90-NEXT:    and.b64 %rd20, %rd28, %rd3;
; SM90-NEXT:    not.b64 %rd21, %rd20;
; SM90-NEXT:    not.b64 %rd22, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd28, %rd29};
; SM90-NEXT:    mov.b128 swap, {%rd21, %rd22};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd7, %rd8}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd8, %rd29;
; SM90-NEXT:    xor.b64 %rd24, %rd7, %rd28;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    setp.ne.b64 %p2, %rd25, 0;
; SM90-NEXT:    mov.b64 %rd28, %rd7;
; SM90-NEXT:    mov.b64 %rd29, %rd8;
; SM90-NEXT:    @%p2 bra $L__BB78_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end1
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd7, %rd8};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd5, %rd6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <4 x i64> %val syncscope("block") acq_rel
        ret <4 x i64> %retval
}

define <8 x i64> @nand_acq_rel_v8i64_global_cta(ptr addrspace(1) %addr, <8 x i64> %val) {
; SM90-LABEL: nand_acq_rel_v8i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<5>;
; SM90-NEXT:    .reg .b64 %rd<58>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd17, [nand_acq_rel_v8i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd3, %rd4}, [nand_acq_rel_v8i64_global_cta_param_1+48];
; SM90-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [nand_acq_rel_v8i64_global_cta_param_1+32];
; SM90-NEXT:    ld.param.v2.b64 {%rd5, %rd6}, [nand_acq_rel_v8i64_global_cta_param_1];
; SM90-NEXT:    ld.param.v2.b64 {%rd7, %rd8}, [nand_acq_rel_v8i64_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd18, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd18, %rd18};
; SM90-NEXT:    mov.b128 swap, {%rd18, %rd18};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd50, %rd51}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB79_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    mov.b64 %rd10, %rd51;
; SM90-NEXT:    mov.b64 %rd9, %rd50;
; SM90-NEXT:    and.b64 %rd19, %rd10, %rd6;
; SM90-NEXT:    and.b64 %rd20, %rd9, %rd5;
; SM90-NEXT:    not.b64 %rd21, %rd20;
; SM90-NEXT:    not.b64 %rd22, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd9, %rd10};
; SM90-NEXT:    mov.b128 swap, {%rd21, %rd22};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd50, %rd51}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd51, %rd10;
; SM90-NEXT:    xor.b64 %rd24, %rd50, %rd9;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB79_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd26, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd26, %rd26};
; SM90-NEXT:    mov.b128 swap, {%rd26, %rd26};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd52, %rd53}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB79_3: // %atomicrmw.start6
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    mov.b64 %rd12, %rd53;
; SM90-NEXT:    mov.b64 %rd11, %rd52;
; SM90-NEXT:    and.b64 %rd27, %rd12, %rd8;
; SM90-NEXT:    and.b64 %rd28, %rd11, %rd7;
; SM90-NEXT:    not.b64 %rd29, %rd28;
; SM90-NEXT:    not.b64 %rd30, %rd27;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd11, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd29, %rd30};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd52, %rd53}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd31, %rd53, %rd12;
; SM90-NEXT:    xor.b64 %rd32, %rd52, %rd11;
; SM90-NEXT:    or.b64 %rd33, %rd32, %rd31;
; SM90-NEXT:    setp.ne.b64 %p2, %rd33, 0;
; SM90-NEXT:    @%p2 bra $L__BB79_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end5
; SM90-NEXT:    mov.b64 %rd34, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd34, %rd34};
; SM90-NEXT:    mov.b128 swap, {%rd34, %rd34};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+32], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd54, %rd55}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB79_5: // %atomicrmw.start16
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b64 %rd35, %rd55, %rd2;
; SM90-NEXT:    and.b64 %rd36, %rd54, %rd1;
; SM90-NEXT:    not.b64 %rd37, %rd36;
; SM90-NEXT:    not.b64 %rd38, %rd35;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd54, %rd55};
; SM90-NEXT:    mov.b128 swap, {%rd37, %rd38};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+32], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd13, %rd14}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd39, %rd14, %rd55;
; SM90-NEXT:    xor.b64 %rd40, %rd13, %rd54;
; SM90-NEXT:    or.b64 %rd41, %rd40, %rd39;
; SM90-NEXT:    setp.ne.b64 %p3, %rd41, 0;
; SM90-NEXT:    mov.b64 %rd54, %rd13;
; SM90-NEXT:    mov.b64 %rd55, %rd14;
; SM90-NEXT:    @%p3 bra $L__BB79_5;
; SM90-NEXT:  // %bb.6: // %atomicrmw.end15
; SM90-NEXT:    mov.b64 %rd42, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd42, %rd42};
; SM90-NEXT:    mov.b128 swap, {%rd42, %rd42};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+48], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd56, %rd57}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB79_7: // %atomicrmw.start22
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b64 %rd43, %rd57, %rd4;
; SM90-NEXT:    and.b64 %rd44, %rd56, %rd3;
; SM90-NEXT:    not.b64 %rd45, %rd44;
; SM90-NEXT:    not.b64 %rd46, %rd43;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd56, %rd57};
; SM90-NEXT:    mov.b128 swap, {%rd45, %rd46};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+48], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd15, %rd16}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd47, %rd16, %rd57;
; SM90-NEXT:    xor.b64 %rd48, %rd15, %rd56;
; SM90-NEXT:    or.b64 %rd49, %rd48, %rd47;
; SM90-NEXT:    setp.ne.b64 %p4, %rd49, 0;
; SM90-NEXT:    mov.b64 %rd56, %rd15;
; SM90-NEXT:    mov.b64 %rd57, %rd16;
; SM90-NEXT:    @%p4 bra $L__BB79_7;
; SM90-NEXT:  // %bb.8: // %atomicrmw.end21
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+48], {%rd15, %rd16};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+32], {%rd13, %rd14};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd50, %rd51};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd52, %rd53};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <8 x i64> %val syncscope("block") acq_rel
        ret <8 x i64> %retval
}

define <1 x i8> @or_acq_rel_v1i8_global_cta(ptr addrspace(1) %addr, <1 x i8> %val) {
; SM90-LABEL: or_acq_rel_v1i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<8>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [or_acq_rel_v1i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b8 %r1, [or_acq_rel_v1i8_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd2, %rd1, -4;
; SM90-NEXT:    cvt.u32.u64 %r2, %rd1;
; SM90-NEXT:    and.b32 %r3, %r2, 3;
; SM90-NEXT:    shl.b32 %r4, %r3, 3;
; SM90-NEXT:    shl.b32 %r5, %r1, %r4;
; SM90-NEXT:    atom.relaxed.cta.global.or.b32 %r6, [%rd2], %r5;
; SM90-NEXT:    shr.u32 %r7, %r6, %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b8 [func_retval0], %r7;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise or ptr  addrspace(1) %addr, <1 x i8> %val syncscope("block") acq_rel
        ret <1 x i8> %retval
}

define <2 x i8> @or_acq_rel_v2i8_global_cta(ptr addrspace(1) %addr, <2 x i8> %val) {
; SM90-LABEL: or_acq_rel_v2i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<8>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [or_acq_rel_v2i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    and.b64 %rd2, %rd1, -4;
; SM90-NEXT:    cvt.u32.u64 %r1, %rd1;
; SM90-NEXT:    and.b32 %r2, %r1, 3;
; SM90-NEXT:    shl.b32 %r3, %r2, 3;
; SM90-NEXT:    ld.param.b16 %r4, [or_acq_rel_v2i8_global_cta_param_1];
; SM90-NEXT:    shl.b32 %r5, %r4, %r3;
; SM90-NEXT:    atom.relaxed.cta.global.or.b32 %r6, [%rd2], %r5;
; SM90-NEXT:    shr.u32 %r7, %r6, %r3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r7;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise or ptr  addrspace(1) %addr, <2 x i8> %val syncscope("block") acq_rel
        ret <2 x i8> %retval
}

define <4 x i8> @or_acq_rel_v4i8_global_cta(ptr addrspace(1) %addr, <4 x i8> %val) {
; SM90-LABEL: or_acq_rel_v4i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [or_acq_rel_v4i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [or_acq_rel_v4i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:  $L__BB82_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    or.b32 %r3, %r4, %r2;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r4;
; SM90-NEXT:    mov.b32 %r4, %r1;
; SM90-NEXT:    @%p1 bra $L__BB82_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise or ptr  addrspace(1) %addr, <4 x i8> %val syncscope("block") acq_rel
        ret <4 x i8> %retval
}

define <8 x i8> @or_acq_rel_v8i8_global_cta(ptr addrspace(1) %addr, <8 x i8> %val) {
; SM90-LABEL: or_acq_rel_v8i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [or_acq_rel_v8i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [or_acq_rel_v8i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB83_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    or.b32 %r3, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r3;
; SM90-NEXT:    or.b32 %r4, %r6, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r4;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB83_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise or ptr  addrspace(1) %addr, <8 x i8> %val syncscope("block") acq_rel
        ret <8 x i8> %retval
}

define <1 x i16> @or_acq_rel_v1i16_global_cta(ptr addrspace(1) %addr, <1 x i16> %val) {
; SM90-LABEL: or_acq_rel_v1i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<8>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [or_acq_rel_v1i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b16 %r1, [or_acq_rel_v1i16_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd2, %rd1, -4;
; SM90-NEXT:    cvt.u32.u64 %r2, %rd1;
; SM90-NEXT:    and.b32 %r3, %r2, 3;
; SM90-NEXT:    shl.b32 %r4, %r3, 3;
; SM90-NEXT:    shl.b32 %r5, %r1, %r4;
; SM90-NEXT:    atom.relaxed.cta.global.or.b32 %r6, [%rd2], %r5;
; SM90-NEXT:    shr.u32 %r7, %r6, %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r7;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise or ptr  addrspace(1) %addr, <1 x i16> %val syncscope("block") acq_rel
        ret <1 x i16> %retval
}

define <2 x i16> @or_acq_rel_v2i16_global_cta(ptr addrspace(1) %addr, <2 x i16> %val) {
; SM90-LABEL: or_acq_rel_v2i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [or_acq_rel_v2i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [or_acq_rel_v2i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:  $L__BB85_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    or.b32 %r3, %r4, %r2;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r4;
; SM90-NEXT:    mov.b32 %r4, %r1;
; SM90-NEXT:    @%p1 bra $L__BB85_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise or ptr  addrspace(1) %addr, <2 x i16> %val syncscope("block") acq_rel
        ret <2 x i16> %retval
}

define <4 x i16> @or_acq_rel_v4i16_global_cta(ptr addrspace(1) %addr, <4 x i16> %val) {
; SM90-LABEL: or_acq_rel_v4i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [or_acq_rel_v4i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [or_acq_rel_v4i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB86_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    or.b32 %r3, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r3;
; SM90-NEXT:    or.b32 %r4, %r6, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r4;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB86_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise or ptr  addrspace(1) %addr, <4 x i16> %val syncscope("block") acq_rel
        ret <4 x i16> %retval
}

define <8 x i16> @or_acq_rel_v8i16_global_cta(ptr addrspace(1) %addr, <8 x i16> %val) {
; SM90-LABEL: or_acq_rel_v8i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [or_acq_rel_v8i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [or_acq_rel_v8i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB87_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    or.b32 %r5, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd5, %r5;
; SM90-NEXT:    or.b32 %r6, %r10, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r6;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    or.b32 %r7, %r11, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r7;
; SM90-NEXT:    or.b32 %r8, %r12, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r8;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r10;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r12;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd22;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB87_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise or ptr  addrspace(1) %addr, <8 x i16> %val syncscope("block") acq_rel
        ret <8 x i16> %retval
}

define <1 x i32> @or_acq_rel_v1i32_global_cta(ptr addrspace(1) %addr, <1 x i32> %val) {
; SM90-LABEL: or_acq_rel_v1i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<3>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [or_acq_rel_v1i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b32 %r1, [or_acq_rel_v1i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.or.b32 %r2, [%rd1], %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise or ptr  addrspace(1) %addr, <1 x i32> %val syncscope("block") acq_rel
        ret <1 x i32> %retval
}

define <2 x i32> @or_acq_rel_v2i32_global_cta(ptr addrspace(1) %addr, <2 x i32> %val) {
; SM90-LABEL: or_acq_rel_v2i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [or_acq_rel_v2i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [or_acq_rel_v2i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.or.b32 %r3, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.or.b32 %r4, [%rd1+4], %r2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r3, %r4};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise or ptr  addrspace(1) %addr, <2 x i32> %val syncscope("block") acq_rel
        ret <2 x i32> %retval
}

define <4 x i32> @or_acq_rel_v4i32_global_cta(ptr addrspace(1) %addr, <4 x i32> %val) {
; SM90-LABEL: or_acq_rel_v4i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<9>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [or_acq_rel_v4i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [or_acq_rel_v4i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.or.b32 %r5, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.or.b32 %r6, [%rd1+4], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.or.b32 %r7, [%rd1+8], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.or.b32 %r8, [%rd1+12], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise or ptr  addrspace(1) %addr, <4 x i32> %val syncscope("block") acq_rel
        ret <4 x i32> %retval
}

define <8 x i32> @or_acq_rel_v8i32_global_cta(ptr addrspace(1) %addr, <8 x i32> %val) {
; SM90-LABEL: or_acq_rel_v8i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<17>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [or_acq_rel_v8i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [or_acq_rel_v8i32_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [or_acq_rel_v8i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.or.b32 %r9, [%rd1], %r5;
; SM90-NEXT:    atom.relaxed.cta.global.or.b32 %r10, [%rd1+4], %r6;
; SM90-NEXT:    atom.relaxed.cta.global.or.b32 %r11, [%rd1+8], %r7;
; SM90-NEXT:    atom.relaxed.cta.global.or.b32 %r12, [%rd1+12], %r8;
; SM90-NEXT:    atom.relaxed.cta.global.or.b32 %r13, [%rd1+16], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.or.b32 %r14, [%rd1+20], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.or.b32 %r15, [%rd1+24], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.or.b32 %r16, [%rd1+28], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r13, %r14, %r15, %r16};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise or ptr  addrspace(1) %addr, <8 x i32> %val syncscope("block") acq_rel
        ret <8 x i32> %retval
}

define <1 x i64> @or_acq_rel_v1i64_global_cta(ptr addrspace(1) %addr, <1 x i64> %val) {
; SM90-LABEL: or_acq_rel_v1i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<4>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [or_acq_rel_v1i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b64 %rd2, [or_acq_rel_v1i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.or.b64 %rd3, [%rd1], %rd2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b64 [func_retval0], %rd3;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise or ptr  addrspace(1) %addr, <1 x i64> %val syncscope("block") acq_rel
        ret <1 x i64> %retval
}

define <2 x i64> @or_acq_rel_v2i64_global_cta(ptr addrspace(1) %addr, <2 x i64> %val) {
; SM90-LABEL: or_acq_rel_v2i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<6>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [or_acq_rel_v2i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [or_acq_rel_v2i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.or.b64 %rd4, [%rd1], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.or.b64 %rd5, [%rd1+8], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd4, %rd5};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise or ptr  addrspace(1) %addr, <2 x i64> %val syncscope("block") acq_rel
        ret <2 x i64> %retval
}

define <4 x i64> @or_acq_rel_v4i64_global_cta(ptr addrspace(1) %addr, <4 x i64> %val) {
; SM90-LABEL: or_acq_rel_v4i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<10>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [or_acq_rel_v4i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [or_acq_rel_v4i64_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [or_acq_rel_v4i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.or.b64 %rd6, [%rd1], %rd4;
; SM90-NEXT:    atom.relaxed.cta.global.or.b64 %rd7, [%rd1+8], %rd5;
; SM90-NEXT:    atom.relaxed.cta.global.or.b64 %rd8, [%rd1+16], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.or.b64 %rd9, [%rd1+24], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd8, %rd9};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd6, %rd7};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise or ptr  addrspace(1) %addr, <4 x i64> %val syncscope("block") acq_rel
        ret <4 x i64> %retval
}

define <8 x i64> @or_acq_rel_v8i64_global_cta(ptr addrspace(1) %addr, <8 x i64> %val) {
; SM90-LABEL: or_acq_rel_v8i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<18>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [or_acq_rel_v8i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [or_acq_rel_v8i64_global_cta_param_1+48];
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [or_acq_rel_v8i64_global_cta_param_1+32];
; SM90-NEXT:    ld.param.v2.b64 {%rd6, %rd7}, [or_acq_rel_v8i64_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v2.b64 {%rd8, %rd9}, [or_acq_rel_v8i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.or.b64 %rd10, [%rd1], %rd8;
; SM90-NEXT:    atom.relaxed.cta.global.or.b64 %rd11, [%rd1+8], %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.or.b64 %rd12, [%rd1+16], %rd6;
; SM90-NEXT:    atom.relaxed.cta.global.or.b64 %rd13, [%rd1+24], %rd7;
; SM90-NEXT:    atom.relaxed.cta.global.or.b64 %rd14, [%rd1+32], %rd4;
; SM90-NEXT:    atom.relaxed.cta.global.or.b64 %rd15, [%rd1+40], %rd5;
; SM90-NEXT:    atom.relaxed.cta.global.or.b64 %rd16, [%rd1+48], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.or.b64 %rd17, [%rd1+56], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+48], {%rd16, %rd17};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+32], {%rd14, %rd15};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd12, %rd13};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd10, %rd11};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise or ptr  addrspace(1) %addr, <8 x i64> %val syncscope("block") acq_rel
        ret <8 x i64> %retval
}

define <1 x i8> @xor_acq_rel_v1i8_global_cta(ptr addrspace(1) %addr, <1 x i8> %val) {
; SM90-LABEL: xor_acq_rel_v1i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<8>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [xor_acq_rel_v1i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b8 %r1, [xor_acq_rel_v1i8_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd2, %rd1, -4;
; SM90-NEXT:    cvt.u32.u64 %r2, %rd1;
; SM90-NEXT:    and.b32 %r3, %r2, 3;
; SM90-NEXT:    shl.b32 %r4, %r3, 3;
; SM90-NEXT:    shl.b32 %r5, %r1, %r4;
; SM90-NEXT:    atom.relaxed.cta.global.xor.b32 %r6, [%rd2], %r5;
; SM90-NEXT:    shr.u32 %r7, %r6, %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b8 [func_retval0], %r7;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xor ptr  addrspace(1) %addr, <1 x i8> %val syncscope("block") acq_rel
        ret <1 x i8> %retval
}

define <2 x i8> @xor_acq_rel_v2i8_global_cta(ptr addrspace(1) %addr, <2 x i8> %val) {
; SM90-LABEL: xor_acq_rel_v2i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<8>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [xor_acq_rel_v2i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    and.b64 %rd2, %rd1, -4;
; SM90-NEXT:    cvt.u32.u64 %r1, %rd1;
; SM90-NEXT:    and.b32 %r2, %r1, 3;
; SM90-NEXT:    shl.b32 %r3, %r2, 3;
; SM90-NEXT:    ld.param.b16 %r4, [xor_acq_rel_v2i8_global_cta_param_1];
; SM90-NEXT:    shl.b32 %r5, %r4, %r3;
; SM90-NEXT:    atom.relaxed.cta.global.xor.b32 %r6, [%rd2], %r5;
; SM90-NEXT:    shr.u32 %r7, %r6, %r3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r7;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xor ptr  addrspace(1) %addr, <2 x i8> %val syncscope("block") acq_rel
        ret <2 x i8> %retval
}

define <4 x i8> @xor_acq_rel_v4i8_global_cta(ptr addrspace(1) %addr, <4 x i8> %val) {
; SM90-LABEL: xor_acq_rel_v4i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [xor_acq_rel_v4i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [xor_acq_rel_v4i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:  $L__BB98_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    xor.b32 %r3, %r4, %r2;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r4;
; SM90-NEXT:    mov.b32 %r4, %r1;
; SM90-NEXT:    @%p1 bra $L__BB98_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xor ptr  addrspace(1) %addr, <4 x i8> %val syncscope("block") acq_rel
        ret <4 x i8> %retval
}

define <8 x i8> @xor_acq_rel_v8i8_global_cta(ptr addrspace(1) %addr, <8 x i8> %val) {
; SM90-LABEL: xor_acq_rel_v8i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [xor_acq_rel_v8i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [xor_acq_rel_v8i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB99_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    xor.b32 %r3, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r3;
; SM90-NEXT:    xor.b32 %r4, %r6, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r4;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB99_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xor ptr  addrspace(1) %addr, <8 x i8> %val syncscope("block") acq_rel
        ret <8 x i8> %retval
}

define <1 x i16> @xor_acq_rel_v1i16_global_cta(ptr addrspace(1) %addr, <1 x i16> %val) {
; SM90-LABEL: xor_acq_rel_v1i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<8>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [xor_acq_rel_v1i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b16 %r1, [xor_acq_rel_v1i16_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd2, %rd1, -4;
; SM90-NEXT:    cvt.u32.u64 %r2, %rd1;
; SM90-NEXT:    and.b32 %r3, %r2, 3;
; SM90-NEXT:    shl.b32 %r4, %r3, 3;
; SM90-NEXT:    shl.b32 %r5, %r1, %r4;
; SM90-NEXT:    atom.relaxed.cta.global.xor.b32 %r6, [%rd2], %r5;
; SM90-NEXT:    shr.u32 %r7, %r6, %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r7;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xor ptr  addrspace(1) %addr, <1 x i16> %val syncscope("block") acq_rel
        ret <1 x i16> %retval
}

define <2 x i16> @xor_acq_rel_v2i16_global_cta(ptr addrspace(1) %addr, <2 x i16> %val) {
; SM90-LABEL: xor_acq_rel_v2i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [xor_acq_rel_v2i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [xor_acq_rel_v2i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:  $L__BB101_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    xor.b32 %r3, %r4, %r2;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r4;
; SM90-NEXT:    mov.b32 %r4, %r1;
; SM90-NEXT:    @%p1 bra $L__BB101_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xor ptr  addrspace(1) %addr, <2 x i16> %val syncscope("block") acq_rel
        ret <2 x i16> %retval
}

define <4 x i16> @xor_acq_rel_v4i16_global_cta(ptr addrspace(1) %addr, <4 x i16> %val) {
; SM90-LABEL: xor_acq_rel_v4i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [xor_acq_rel_v4i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [xor_acq_rel_v4i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB102_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    xor.b32 %r3, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r3;
; SM90-NEXT:    xor.b32 %r4, %r6, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r4;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB102_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xor ptr  addrspace(1) %addr, <4 x i16> %val syncscope("block") acq_rel
        ret <4 x i16> %retval
}

define <8 x i16> @xor_acq_rel_v8i16_global_cta(ptr addrspace(1) %addr, <8 x i16> %val) {
; SM90-LABEL: xor_acq_rel_v8i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [xor_acq_rel_v8i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [xor_acq_rel_v8i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB103_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    xor.b32 %r5, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd5, %r5;
; SM90-NEXT:    xor.b32 %r6, %r10, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r6;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    xor.b32 %r7, %r11, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r7;
; SM90-NEXT:    xor.b32 %r8, %r12, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r8;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r10;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r12;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd22;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB103_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xor ptr  addrspace(1) %addr, <8 x i16> %val syncscope("block") acq_rel
        ret <8 x i16> %retval
}

define <1 x i32> @xor_acq_rel_v1i32_global_cta(ptr addrspace(1) %addr, <1 x i32> %val) {
; SM90-LABEL: xor_acq_rel_v1i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<3>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [xor_acq_rel_v1i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b32 %r1, [xor_acq_rel_v1i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.xor.b32 %r2, [%rd1], %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xor ptr  addrspace(1) %addr, <1 x i32> %val syncscope("block") acq_rel
        ret <1 x i32> %retval
}

define <2 x i32> @xor_acq_rel_v2i32_global_cta(ptr addrspace(1) %addr, <2 x i32> %val) {
; SM90-LABEL: xor_acq_rel_v2i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [xor_acq_rel_v2i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [xor_acq_rel_v2i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.xor.b32 %r3, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.xor.b32 %r4, [%rd1+4], %r2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r3, %r4};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xor ptr  addrspace(1) %addr, <2 x i32> %val syncscope("block") acq_rel
        ret <2 x i32> %retval
}

define <4 x i32> @xor_acq_rel_v4i32_global_cta(ptr addrspace(1) %addr, <4 x i32> %val) {
; SM90-LABEL: xor_acq_rel_v4i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<9>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [xor_acq_rel_v4i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [xor_acq_rel_v4i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.xor.b32 %r5, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.xor.b32 %r6, [%rd1+4], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.xor.b32 %r7, [%rd1+8], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.xor.b32 %r8, [%rd1+12], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xor ptr  addrspace(1) %addr, <4 x i32> %val syncscope("block") acq_rel
        ret <4 x i32> %retval
}

define <8 x i32> @xor_acq_rel_v8i32_global_cta(ptr addrspace(1) %addr, <8 x i32> %val) {
; SM90-LABEL: xor_acq_rel_v8i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<17>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [xor_acq_rel_v8i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [xor_acq_rel_v8i32_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [xor_acq_rel_v8i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.xor.b32 %r9, [%rd1], %r5;
; SM90-NEXT:    atom.relaxed.cta.global.xor.b32 %r10, [%rd1+4], %r6;
; SM90-NEXT:    atom.relaxed.cta.global.xor.b32 %r11, [%rd1+8], %r7;
; SM90-NEXT:    atom.relaxed.cta.global.xor.b32 %r12, [%rd1+12], %r8;
; SM90-NEXT:    atom.relaxed.cta.global.xor.b32 %r13, [%rd1+16], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.xor.b32 %r14, [%rd1+20], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.xor.b32 %r15, [%rd1+24], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.xor.b32 %r16, [%rd1+28], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r13, %r14, %r15, %r16};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xor ptr  addrspace(1) %addr, <8 x i32> %val syncscope("block") acq_rel
        ret <8 x i32> %retval
}

define <1 x i64> @xor_acq_rel_v1i64_global_cta(ptr addrspace(1) %addr, <1 x i64> %val) {
; SM90-LABEL: xor_acq_rel_v1i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<4>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [xor_acq_rel_v1i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b64 %rd2, [xor_acq_rel_v1i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.xor.b64 %rd3, [%rd1], %rd2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b64 [func_retval0], %rd3;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xor ptr  addrspace(1) %addr, <1 x i64> %val syncscope("block") acq_rel
        ret <1 x i64> %retval
}

define <2 x i64> @xor_acq_rel_v2i64_global_cta(ptr addrspace(1) %addr, <2 x i64> %val) {
; SM90-LABEL: xor_acq_rel_v2i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<6>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [xor_acq_rel_v2i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [xor_acq_rel_v2i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.xor.b64 %rd4, [%rd1], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.xor.b64 %rd5, [%rd1+8], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd4, %rd5};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xor ptr  addrspace(1) %addr, <2 x i64> %val syncscope("block") acq_rel
        ret <2 x i64> %retval
}

define <4 x i64> @xor_acq_rel_v4i64_global_cta(ptr addrspace(1) %addr, <4 x i64> %val) {
; SM90-LABEL: xor_acq_rel_v4i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<10>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [xor_acq_rel_v4i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [xor_acq_rel_v4i64_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [xor_acq_rel_v4i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.xor.b64 %rd6, [%rd1], %rd4;
; SM90-NEXT:    atom.relaxed.cta.global.xor.b64 %rd7, [%rd1+8], %rd5;
; SM90-NEXT:    atom.relaxed.cta.global.xor.b64 %rd8, [%rd1+16], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.xor.b64 %rd9, [%rd1+24], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd8, %rd9};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd6, %rd7};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xor ptr  addrspace(1) %addr, <4 x i64> %val syncscope("block") acq_rel
        ret <4 x i64> %retval
}

define <8 x i64> @xor_acq_rel_v8i64_global_cta(ptr addrspace(1) %addr, <8 x i64> %val) {
; SM90-LABEL: xor_acq_rel_v8i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<18>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [xor_acq_rel_v8i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [xor_acq_rel_v8i64_global_cta_param_1+48];
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [xor_acq_rel_v8i64_global_cta_param_1+32];
; SM90-NEXT:    ld.param.v2.b64 {%rd6, %rd7}, [xor_acq_rel_v8i64_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v2.b64 {%rd8, %rd9}, [xor_acq_rel_v8i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.xor.b64 %rd10, [%rd1], %rd8;
; SM90-NEXT:    atom.relaxed.cta.global.xor.b64 %rd11, [%rd1+8], %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.xor.b64 %rd12, [%rd1+16], %rd6;
; SM90-NEXT:    atom.relaxed.cta.global.xor.b64 %rd13, [%rd1+24], %rd7;
; SM90-NEXT:    atom.relaxed.cta.global.xor.b64 %rd14, [%rd1+32], %rd4;
; SM90-NEXT:    atom.relaxed.cta.global.xor.b64 %rd15, [%rd1+40], %rd5;
; SM90-NEXT:    atom.relaxed.cta.global.xor.b64 %rd16, [%rd1+48], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.xor.b64 %rd17, [%rd1+56], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+48], {%rd16, %rd17};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+32], {%rd14, %rd15};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd12, %rd13};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd10, %rd11};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise xor ptr  addrspace(1) %addr, <8 x i64> %val syncscope("block") acq_rel
        ret <8 x i64> %retval
}

define <1 x i8> @max_acq_rel_v1i8_global_cta(ptr addrspace(1) %addr, <1 x i8> %val) {
; SM90-LABEL: max_acq_rel_v1i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<4>;
; SM90-NEXT:    .reg .b32 %r<16>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [max_acq_rel_v1i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.s8 %rs1, [max_acq_rel_v1i8_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r4, %rd2;
; SM90-NEXT:    and.b32 %r5, %r4, 3;
; SM90-NEXT:    shl.b32 %r1, %r5, 3;
; SM90-NEXT:    mov.b32 %r6, 255;
; SM90-NEXT:    shl.b32 %r7, %r6, %r1;
; SM90-NEXT:    not.b32 %r2, %r7;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r15, [%rd1];
; SM90-NEXT:  $L__BB112_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r8, %r15, %r1;
; SM90-NEXT:    cvt.s8.s32 %rs2, %r8;
; SM90-NEXT:    max.s16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r9, %rs3;
; SM90-NEXT:    and.b32 %r10, %r9, 255;
; SM90-NEXT:    shl.b32 %r11, %r10, %r1;
; SM90-NEXT:    and.b32 %r12, %r15, %r2;
; SM90-NEXT:    or.b32 %r13, %r12, %r11;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r15, %r13;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r15;
; SM90-NEXT:    mov.b32 %r15, %r3;
; SM90-NEXT:    @%p1 bra $L__BB112_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r14, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b8 [func_retval0], %r14;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise max ptr  addrspace(1) %addr, <1 x i8> %val syncscope("block") acq_rel
        ret <1 x i8> %retval
}

define <2 x i8> @max_acq_rel_v2i8_global_cta(ptr addrspace(1) %addr, <2 x i8> %val) {
; SM90-LABEL: max_acq_rel_v2i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<14>;
; SM90-NEXT:    .reg .b32 %r<20>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b8 {%rs1, %rs2}, [max_acq_rel_v2i8_global_cta_param_1];
; SM90-NEXT:    mov.b32 %r4, {%rs1, %rs2};
; SM90-NEXT:    ld.param.b64 %rd2, [max_acq_rel_v2i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:    and.b32 %r6, %r5, 3;
; SM90-NEXT:    shl.b32 %r1, %r6, 3;
; SM90-NEXT:    mov.b32 %r7, 65535;
; SM90-NEXT:    shl.b32 %r8, %r7, %r1;
; SM90-NEXT:    not.b32 %r2, %r8;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r19, [%rd1];
; SM90-NEXT:    mov.b32 {%rs5, %rs6}, %r4;
; SM90-NEXT:    cvt.s16.s8 %rs7, %rs6;
; SM90-NEXT:    cvt.s16.s8 %rs8, %rs5;
; SM90-NEXT:    mov.b32 %r12, {%rs8, %rs7};
; SM90-NEXT:  $L__BB113_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r9, %r19, %r1;
; SM90-NEXT:    cvt.s8.s32 %rs3, %r9;
; SM90-NEXT:    bfe.s32 %r10, %r9, 8, 8;
; SM90-NEXT:    cvt.s8.s32 %rs4, %r10;
; SM90-NEXT:    mov.b32 %r11, {%rs3, %rs4};
; SM90-NEXT:    max.s16x2 %r13, %r11, %r12;
; SM90-NEXT:    mov.b32 {%rs9, %rs10}, %r13;
; SM90-NEXT:    shl.b16 %rs11, %rs10, 8;
; SM90-NEXT:    and.b16 %rs12, %rs9, 255;
; SM90-NEXT:    or.b16 %rs13, %rs12, %rs11;
; SM90-NEXT:    cvt.u32.u16 %r14, %rs13;
; SM90-NEXT:    shl.b32 %r15, %r14, %r1;
; SM90-NEXT:    and.b32 %r16, %r19, %r2;
; SM90-NEXT:    or.b32 %r17, %r16, %r15;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r19, %r17;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r19;
; SM90-NEXT:    mov.b32 %r19, %r3;
; SM90-NEXT:    @%p1 bra $L__BB113_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r18, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r18;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise max ptr  addrspace(1) %addr, <2 x i8> %val syncscope("block") acq_rel
        ret <2 x i8> %retval
}

define <4 x i8> @max_acq_rel_v4i8_global_cta(ptr addrspace(1) %addr, <4 x i8> %val) {
; SM90-LABEL: max_acq_rel_v4i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<6>;
; SM90-NEXT:    .reg .b32 %r<27>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [max_acq_rel_v4i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [max_acq_rel_v4i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r26, [%rd1];
; SM90-NEXT:    prmt.b32 %r3, %r2, 0, 0x8880U;
; SM90-NEXT:    prmt.b32 %r5, %r2, 0, 0x9991U;
; SM90-NEXT:    prmt.b32 %r7, %r2, 0, 0xaaa2U;
; SM90-NEXT:    prmt.b32 %r9, %r2, 0, 0xbbb3U;
; SM90-NEXT:  $L__BB114_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    prmt.b32 %r4, %r26, 0, 0x8880U;
; SM90-NEXT:    setp.gt.s32 %p1, %r4, %r3;
; SM90-NEXT:    prmt.b32 %r6, %r26, 0, 0x9991U;
; SM90-NEXT:    setp.gt.s32 %p2, %r6, %r5;
; SM90-NEXT:    prmt.b32 %r8, %r26, 0, 0xaaa2U;
; SM90-NEXT:    setp.gt.s32 %p3, %r8, %r7;
; SM90-NEXT:    prmt.b32 %r10, %r26, 0, 0xbbb3U;
; SM90-NEXT:    setp.gt.s32 %p4, %r10, %r9;
; SM90-NEXT:    prmt.b32 %r11, %r2, 0, 0x7770U;
; SM90-NEXT:    prmt.b32 %r12, %r2, 0, 0x7771U;
; SM90-NEXT:    prmt.b32 %r13, %r2, 0, 0x7772U;
; SM90-NEXT:    prmt.b32 %r14, %r2, 0, 0x7773U;
; SM90-NEXT:    prmt.b32 %r15, %r26, 0, 0x7773U;
; SM90-NEXT:    selp.b32 %r16, %r15, %r14, %p4;
; SM90-NEXT:    prmt.b32 %r17, %r26, 0, 0x7772U;
; SM90-NEXT:    selp.b32 %r18, %r17, %r13, %p3;
; SM90-NEXT:    prmt.b32 %r19, %r18, %r16, 0x3340U;
; SM90-NEXT:    prmt.b32 %r20, %r26, 0, 0x7771U;
; SM90-NEXT:    selp.b32 %r21, %r20, %r12, %p2;
; SM90-NEXT:    prmt.b32 %r22, %r26, 0, 0x7770U;
; SM90-NEXT:    selp.b32 %r23, %r22, %r11, %p1;
; SM90-NEXT:    prmt.b32 %r24, %r23, %r21, 0x3340U;
; SM90-NEXT:    prmt.b32 %r25, %r24, %r19, 0x5410U;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r26, %r25;
; SM90-NEXT:    setp.ne.b32 %p5, %r1, %r26;
; SM90-NEXT:    mov.b32 %r26, %r1;
; SM90-NEXT:    @%p5 bra $L__BB114_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise max ptr  addrspace(1) %addr, <4 x i8> %val syncscope("block") acq_rel
        ret <4 x i8> %retval
}

define <8 x i8> @max_acq_rel_v8i8_global_cta(ptr addrspace(1) %addr, <8 x i8> %val) {
; SM90-LABEL: max_acq_rel_v8i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<10>;
; SM90-NEXT:    .reg .b16 %rs<25>;
; SM90-NEXT:    .reg .b32 %r<51>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [max_acq_rel_v8i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [max_acq_rel_v8i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r50}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r49, %rd2;
; SM90-NEXT:    prmt.b32 %r3, %r2, 0, 0x8880U;
; SM90-NEXT:    prmt.b32 %r5, %r2, 0, 0x9991U;
; SM90-NEXT:  $L__BB115_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd3, %r49;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r50;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    prmt.b32 %r4, %r50, 0, 0x8880U;
; SM90-NEXT:    setp.gt.s32 %p1, %r4, %r3;
; SM90-NEXT:    prmt.b32 %r6, %r50, 0, 0x9991U;
; SM90-NEXT:    setp.gt.s32 %p2, %r6, %r5;
; SM90-NEXT:    prmt.b32 %r7, %r2, 0, 0xaaa2U;
; SM90-NEXT:    prmt.b32 %r8, %r50, 0, 0xaaa2U;
; SM90-NEXT:    setp.gt.s32 %p3, %r8, %r7;
; SM90-NEXT:    prmt.b32 %r9, %r2, 0, 0xbbb3U;
; SM90-NEXT:    prmt.b32 %r10, %r50, 0, 0xbbb3U;
; SM90-NEXT:    setp.gt.s32 %p4, %r10, %r9;
; SM90-NEXT:    prmt.b32 %r11, %r1, 0, 0x8880U;
; SM90-NEXT:    prmt.b32 %r12, %r49, 0, 0x8880U;
; SM90-NEXT:    setp.gt.s32 %p5, %r12, %r11;
; SM90-NEXT:    prmt.b32 %r13, %r1, 0, 0x9991U;
; SM90-NEXT:    prmt.b32 %r14, %r49, 0, 0x9991U;
; SM90-NEXT:    setp.gt.s32 %p6, %r14, %r13;
; SM90-NEXT:    prmt.b32 %r15, %r1, 0, 0xaaa2U;
; SM90-NEXT:    prmt.b32 %r16, %r49, 0, 0xaaa2U;
; SM90-NEXT:    setp.gt.s32 %p7, %r16, %r15;
; SM90-NEXT:    prmt.b32 %r17, %r1, 0, 0xbbb3U;
; SM90-NEXT:    prmt.b32 %r18, %r49, 0, 0xbbb3U;
; SM90-NEXT:    setp.gt.s32 %p8, %r18, %r17;
; SM90-NEXT:    prmt.b32 %r19, %r2, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs1, %r19;
; SM90-NEXT:    prmt.b32 %r20, %r50, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r20;
; SM90-NEXT:    prmt.b32 %r21, %r2, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs3, %r21;
; SM90-NEXT:    prmt.b32 %r22, %r50, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs4, %r22;
; SM90-NEXT:    prmt.b32 %r23, %r2, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs5, %r23;
; SM90-NEXT:    prmt.b32 %r24, %r50, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs6, %r24;
; SM90-NEXT:    prmt.b32 %r25, %r2, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs7, %r25;
; SM90-NEXT:    prmt.b32 %r26, %r50, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs8, %r26;
; SM90-NEXT:    prmt.b32 %r27, %r1, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs9, %r27;
; SM90-NEXT:    prmt.b32 %r28, %r49, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs10, %r28;
; SM90-NEXT:    prmt.b32 %r29, %r1, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs11, %r29;
; SM90-NEXT:    prmt.b32 %r30, %r49, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs12, %r30;
; SM90-NEXT:    prmt.b32 %r31, %r1, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs13, %r31;
; SM90-NEXT:    prmt.b32 %r32, %r49, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs14, %r32;
; SM90-NEXT:    prmt.b32 %r33, %r1, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs15, %r33;
; SM90-NEXT:    prmt.b32 %r34, %r49, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs16, %r34;
; SM90-NEXT:    selp.b16 %rs17, %rs16, %rs15, %p8;
; SM90-NEXT:    cvt.u32.u16 %r35, %rs17;
; SM90-NEXT:    selp.b16 %rs18, %rs14, %rs13, %p7;
; SM90-NEXT:    cvt.u32.u16 %r36, %rs18;
; SM90-NEXT:    prmt.b32 %r37, %r36, %r35, 0x3340U;
; SM90-NEXT:    selp.b16 %rs19, %rs12, %rs11, %p6;
; SM90-NEXT:    cvt.u32.u16 %r38, %rs19;
; SM90-NEXT:    selp.b16 %rs20, %rs10, %rs9, %p5;
; SM90-NEXT:    cvt.u32.u16 %r39, %rs20;
; SM90-NEXT:    prmt.b32 %r40, %r39, %r38, 0x3340U;
; SM90-NEXT:    prmt.b32 %r41, %r40, %r37, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r41;
; SM90-NEXT:    selp.b16 %rs21, %rs8, %rs7, %p4;
; SM90-NEXT:    cvt.u32.u16 %r42, %rs21;
; SM90-NEXT:    selp.b16 %rs22, %rs6, %rs5, %p3;
; SM90-NEXT:    cvt.u32.u16 %r43, %rs22;
; SM90-NEXT:    prmt.b32 %r44, %r43, %r42, 0x3340U;
; SM90-NEXT:    selp.b16 %rs23, %rs4, %rs3, %p2;
; SM90-NEXT:    cvt.u32.u16 %r45, %rs23;
; SM90-NEXT:    selp.b16 %rs24, %rs2, %rs1, %p1;
; SM90-NEXT:    cvt.u32.u16 %r46, %rs24;
; SM90-NEXT:    prmt.b32 %r47, %r46, %r45, 0x3340U;
; SM90-NEXT:    prmt.b32 %r48, %r47, %r44, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r48;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd6, %rd10;
; SM90-NEXT:    setp.ne.b64 %p9, %rd11, %rd6;
; SM90-NEXT:    mov.b64 {_, %r50}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r49, %rd11;
; SM90-NEXT:    @%p9 bra $L__BB115_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r49, %r50};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise max ptr  addrspace(1) %addr, <8 x i8> %val syncscope("block") acq_rel
        ret <8 x i8> %retval
}

define <1 x i16> @max_acq_rel_v1i16_global_cta(ptr addrspace(1) %addr, <1 x i16> %val) {
; SM90-LABEL: max_acq_rel_v1i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<4>;
; SM90-NEXT:    .reg .b32 %r<15>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [max_acq_rel_v1i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b16 %rs1, [max_acq_rel_v1i16_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r4, %rd2;
; SM90-NEXT:    and.b32 %r5, %r4, 3;
; SM90-NEXT:    shl.b32 %r1, %r5, 3;
; SM90-NEXT:    mov.b32 %r6, 65535;
; SM90-NEXT:    shl.b32 %r7, %r6, %r1;
; SM90-NEXT:    not.b32 %r2, %r7;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r14, [%rd1];
; SM90-NEXT:  $L__BB116_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r8, %r14, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r8;
; SM90-NEXT:    max.s16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r9, %rs3;
; SM90-NEXT:    shl.b32 %r10, %r9, %r1;
; SM90-NEXT:    and.b32 %r11, %r14, %r2;
; SM90-NEXT:    or.b32 %r12, %r11, %r10;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r14, %r12;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r14;
; SM90-NEXT:    mov.b32 %r14, %r3;
; SM90-NEXT:    @%p1 bra $L__BB116_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r13, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r13;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise max ptr  addrspace(1) %addr, <1 x i16> %val syncscope("block") acq_rel
        ret <1 x i16> %retval
}

define <2 x i16> @max_acq_rel_v2i16_global_cta(ptr addrspace(1) %addr, <2 x i16> %val) {
; SM90-LABEL: max_acq_rel_v2i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [max_acq_rel_v2i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [max_acq_rel_v2i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:  $L__BB117_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.s16x2 %r3, %r4, %r2;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r4;
; SM90-NEXT:    mov.b32 %r4, %r1;
; SM90-NEXT:    @%p1 bra $L__BB117_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise max ptr  addrspace(1) %addr, <2 x i16> %val syncscope("block") acq_rel
        ret <2 x i16> %retval
}

define <4 x i16> @max_acq_rel_v4i16_global_cta(ptr addrspace(1) %addr, <4 x i16> %val) {
; SM90-LABEL: max_acq_rel_v4i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [max_acq_rel_v4i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [max_acq_rel_v4i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB118_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd3, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r6;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    max.s16x2 %r3, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r3;
; SM90-NEXT:    max.s16x2 %r4, %r6, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r4;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd6, %rd10;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd6;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB118_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise max ptr  addrspace(1) %addr, <4 x i16> %val syncscope("block") acq_rel
        ret <4 x i16> %retval
}

define <8 x i16> @max_acq_rel_v8i16_global_cta(ptr addrspace(1) %addr, <8 x i16> %val) {
; SM90-LABEL: max_acq_rel_v8i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [max_acq_rel_v8i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [max_acq_rel_v8i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB119_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd5, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r10;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r12;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    max.s16x2 %r5, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r5;
; SM90-NEXT:    max.s16x2 %r6, %r10, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r6;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    max.s16x2 %r7, %r11, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r7;
; SM90-NEXT:    max.s16x2 %r8, %r12, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r8;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd8, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd16, %rd20};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd12;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd8;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd22;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB119_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise max ptr  addrspace(1) %addr, <8 x i16> %val syncscope("block") acq_rel
        ret <8 x i16> %retval
}

define <1 x i32> @max_acq_rel_v1i32_global_cta(ptr addrspace(1) %addr, <1 x i32> %val) {
; SM90-LABEL: max_acq_rel_v1i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<3>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [max_acq_rel_v1i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b32 %r1, [max_acq_rel_v1i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.max.s32 %r2, [%rd1], %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise max ptr  addrspace(1) %addr, <1 x i32> %val syncscope("block") acq_rel
        ret <1 x i32> %retval
}

define <2 x i32> @max_acq_rel_v2i32_global_cta(ptr addrspace(1) %addr, <2 x i32> %val) {
; SM90-LABEL: max_acq_rel_v2i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [max_acq_rel_v2i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [max_acq_rel_v2i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.max.s32 %r3, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.max.s32 %r4, [%rd1+4], %r2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r3, %r4};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise max ptr  addrspace(1) %addr, <2 x i32> %val syncscope("block") acq_rel
        ret <2 x i32> %retval
}

define <4 x i32> @max_acq_rel_v4i32_global_cta(ptr addrspace(1) %addr, <4 x i32> %val) {
; SM90-LABEL: max_acq_rel_v4i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<9>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [max_acq_rel_v4i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [max_acq_rel_v4i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.max.s32 %r5, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.max.s32 %r6, [%rd1+4], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.max.s32 %r7, [%rd1+8], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.max.s32 %r8, [%rd1+12], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise max ptr  addrspace(1) %addr, <4 x i32> %val syncscope("block") acq_rel
        ret <4 x i32> %retval
}

define <8 x i32> @max_acq_rel_v8i32_global_cta(ptr addrspace(1) %addr, <8 x i32> %val) {
; SM90-LABEL: max_acq_rel_v8i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<17>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [max_acq_rel_v8i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [max_acq_rel_v8i32_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [max_acq_rel_v8i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.max.s32 %r9, [%rd1], %r5;
; SM90-NEXT:    atom.relaxed.cta.global.max.s32 %r10, [%rd1+4], %r6;
; SM90-NEXT:    atom.relaxed.cta.global.max.s32 %r11, [%rd1+8], %r7;
; SM90-NEXT:    atom.relaxed.cta.global.max.s32 %r12, [%rd1+12], %r8;
; SM90-NEXT:    atom.relaxed.cta.global.max.s32 %r13, [%rd1+16], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.max.s32 %r14, [%rd1+20], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.max.s32 %r15, [%rd1+24], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.max.s32 %r16, [%rd1+28], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r13, %r14, %r15, %r16};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise max ptr  addrspace(1) %addr, <8 x i32> %val syncscope("block") acq_rel
        ret <8 x i32> %retval
}

define <1 x i64> @max_acq_rel_v1i64_global_cta(ptr addrspace(1) %addr, <1 x i64> %val) {
; SM90-LABEL: max_acq_rel_v1i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<4>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [max_acq_rel_v1i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b64 %rd2, [max_acq_rel_v1i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.max.s64 %rd3, [%rd1], %rd2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b64 [func_retval0], %rd3;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise max ptr  addrspace(1) %addr, <1 x i64> %val syncscope("block") acq_rel
        ret <1 x i64> %retval
}

define <2 x i64> @max_acq_rel_v2i64_global_cta(ptr addrspace(1) %addr, <2 x i64> %val) {
; SM90-LABEL: max_acq_rel_v2i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<6>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [max_acq_rel_v2i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [max_acq_rel_v2i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.max.s64 %rd4, [%rd1], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.max.s64 %rd5, [%rd1+8], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd4, %rd5};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise max ptr  addrspace(1) %addr, <2 x i64> %val syncscope("block") acq_rel
        ret <2 x i64> %retval
}

define <4 x i64> @max_acq_rel_v4i64_global_cta(ptr addrspace(1) %addr, <4 x i64> %val) {
; SM90-LABEL: max_acq_rel_v4i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<10>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [max_acq_rel_v4i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [max_acq_rel_v4i64_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [max_acq_rel_v4i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.max.s64 %rd6, [%rd1], %rd4;
; SM90-NEXT:    atom.relaxed.cta.global.max.s64 %rd7, [%rd1+8], %rd5;
; SM90-NEXT:    atom.relaxed.cta.global.max.s64 %rd8, [%rd1+16], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.max.s64 %rd9, [%rd1+24], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd8, %rd9};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd6, %rd7};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise max ptr  addrspace(1) %addr, <4 x i64> %val syncscope("block") acq_rel
        ret <4 x i64> %retval
}

define <8 x i64> @max_acq_rel_v8i64_global_cta(ptr addrspace(1) %addr, <8 x i64> %val) {
; SM90-LABEL: max_acq_rel_v8i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<18>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [max_acq_rel_v8i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [max_acq_rel_v8i64_global_cta_param_1+48];
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [max_acq_rel_v8i64_global_cta_param_1+32];
; SM90-NEXT:    ld.param.v2.b64 {%rd6, %rd7}, [max_acq_rel_v8i64_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v2.b64 {%rd8, %rd9}, [max_acq_rel_v8i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.max.s64 %rd10, [%rd1], %rd8;
; SM90-NEXT:    atom.relaxed.cta.global.max.s64 %rd11, [%rd1+8], %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.max.s64 %rd12, [%rd1+16], %rd6;
; SM90-NEXT:    atom.relaxed.cta.global.max.s64 %rd13, [%rd1+24], %rd7;
; SM90-NEXT:    atom.relaxed.cta.global.max.s64 %rd14, [%rd1+32], %rd4;
; SM90-NEXT:    atom.relaxed.cta.global.max.s64 %rd15, [%rd1+40], %rd5;
; SM90-NEXT:    atom.relaxed.cta.global.max.s64 %rd16, [%rd1+48], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.max.s64 %rd17, [%rd1+56], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+48], {%rd16, %rd17};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+32], {%rd14, %rd15};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd12, %rd13};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd10, %rd11};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise max ptr  addrspace(1) %addr, <8 x i64> %val syncscope("block") acq_rel
        ret <8 x i64> %retval
}

define <1 x i8> @min_acq_rel_v1i8_global_cta(ptr addrspace(1) %addr, <1 x i8> %val) {
; SM90-LABEL: min_acq_rel_v1i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<4>;
; SM90-NEXT:    .reg .b32 %r<16>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [min_acq_rel_v1i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.s8 %rs1, [min_acq_rel_v1i8_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r4, %rd2;
; SM90-NEXT:    and.b32 %r5, %r4, 3;
; SM90-NEXT:    shl.b32 %r1, %r5, 3;
; SM90-NEXT:    mov.b32 %r6, 255;
; SM90-NEXT:    shl.b32 %r7, %r6, %r1;
; SM90-NEXT:    not.b32 %r2, %r7;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r15, [%rd1];
; SM90-NEXT:  $L__BB128_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r8, %r15, %r1;
; SM90-NEXT:    cvt.s8.s32 %rs2, %r8;
; SM90-NEXT:    min.s16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r9, %rs3;
; SM90-NEXT:    and.b32 %r10, %r9, 255;
; SM90-NEXT:    shl.b32 %r11, %r10, %r1;
; SM90-NEXT:    and.b32 %r12, %r15, %r2;
; SM90-NEXT:    or.b32 %r13, %r12, %r11;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r15, %r13;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r15;
; SM90-NEXT:    mov.b32 %r15, %r3;
; SM90-NEXT:    @%p1 bra $L__BB128_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r14, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b8 [func_retval0], %r14;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise min ptr  addrspace(1) %addr, <1 x i8> %val syncscope("block") acq_rel
        ret <1 x i8> %retval
}

define <2 x i8> @min_acq_rel_v2i8_global_cta(ptr addrspace(1) %addr, <2 x i8> %val) {
; SM90-LABEL: min_acq_rel_v2i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<14>;
; SM90-NEXT:    .reg .b32 %r<20>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b8 {%rs1, %rs2}, [min_acq_rel_v2i8_global_cta_param_1];
; SM90-NEXT:    mov.b32 %r4, {%rs1, %rs2};
; SM90-NEXT:    ld.param.b64 %rd2, [min_acq_rel_v2i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:    and.b32 %r6, %r5, 3;
; SM90-NEXT:    shl.b32 %r1, %r6, 3;
; SM90-NEXT:    mov.b32 %r7, 65535;
; SM90-NEXT:    shl.b32 %r8, %r7, %r1;
; SM90-NEXT:    not.b32 %r2, %r8;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r19, [%rd1];
; SM90-NEXT:    mov.b32 {%rs5, %rs6}, %r4;
; SM90-NEXT:    cvt.s16.s8 %rs7, %rs6;
; SM90-NEXT:    cvt.s16.s8 %rs8, %rs5;
; SM90-NEXT:    mov.b32 %r12, {%rs8, %rs7};
; SM90-NEXT:  $L__BB129_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r9, %r19, %r1;
; SM90-NEXT:    cvt.s8.s32 %rs3, %r9;
; SM90-NEXT:    bfe.s32 %r10, %r9, 8, 8;
; SM90-NEXT:    cvt.s8.s32 %rs4, %r10;
; SM90-NEXT:    mov.b32 %r11, {%rs3, %rs4};
; SM90-NEXT:    min.s16x2 %r13, %r11, %r12;
; SM90-NEXT:    mov.b32 {%rs9, %rs10}, %r13;
; SM90-NEXT:    shl.b16 %rs11, %rs10, 8;
; SM90-NEXT:    and.b16 %rs12, %rs9, 255;
; SM90-NEXT:    or.b16 %rs13, %rs12, %rs11;
; SM90-NEXT:    cvt.u32.u16 %r14, %rs13;
; SM90-NEXT:    shl.b32 %r15, %r14, %r1;
; SM90-NEXT:    and.b32 %r16, %r19, %r2;
; SM90-NEXT:    or.b32 %r17, %r16, %r15;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r19, %r17;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r19;
; SM90-NEXT:    mov.b32 %r19, %r3;
; SM90-NEXT:    @%p1 bra $L__BB129_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r18, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r18;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise min ptr  addrspace(1) %addr, <2 x i8> %val syncscope("block") acq_rel
        ret <2 x i8> %retval
}

define <4 x i8> @min_acq_rel_v4i8_global_cta(ptr addrspace(1) %addr, <4 x i8> %val) {
; SM90-LABEL: min_acq_rel_v4i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<6>;
; SM90-NEXT:    .reg .b32 %r<27>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [min_acq_rel_v4i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [min_acq_rel_v4i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r26, [%rd1];
; SM90-NEXT:    prmt.b32 %r3, %r2, 0, 0x8880U;
; SM90-NEXT:    prmt.b32 %r5, %r2, 0, 0x9991U;
; SM90-NEXT:    prmt.b32 %r7, %r2, 0, 0xaaa2U;
; SM90-NEXT:    prmt.b32 %r9, %r2, 0, 0xbbb3U;
; SM90-NEXT:  $L__BB130_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    prmt.b32 %r4, %r26, 0, 0x8880U;
; SM90-NEXT:    setp.le.s32 %p1, %r4, %r3;
; SM90-NEXT:    prmt.b32 %r6, %r26, 0, 0x9991U;
; SM90-NEXT:    setp.le.s32 %p2, %r6, %r5;
; SM90-NEXT:    prmt.b32 %r8, %r26, 0, 0xaaa2U;
; SM90-NEXT:    setp.le.s32 %p3, %r8, %r7;
; SM90-NEXT:    prmt.b32 %r10, %r26, 0, 0xbbb3U;
; SM90-NEXT:    setp.le.s32 %p4, %r10, %r9;
; SM90-NEXT:    prmt.b32 %r11, %r2, 0, 0x7770U;
; SM90-NEXT:    prmt.b32 %r12, %r2, 0, 0x7771U;
; SM90-NEXT:    prmt.b32 %r13, %r2, 0, 0x7772U;
; SM90-NEXT:    prmt.b32 %r14, %r2, 0, 0x7773U;
; SM90-NEXT:    prmt.b32 %r15, %r26, 0, 0x7773U;
; SM90-NEXT:    selp.b32 %r16, %r15, %r14, %p4;
; SM90-NEXT:    prmt.b32 %r17, %r26, 0, 0x7772U;
; SM90-NEXT:    selp.b32 %r18, %r17, %r13, %p3;
; SM90-NEXT:    prmt.b32 %r19, %r18, %r16, 0x3340U;
; SM90-NEXT:    prmt.b32 %r20, %r26, 0, 0x7771U;
; SM90-NEXT:    selp.b32 %r21, %r20, %r12, %p2;
; SM90-NEXT:    prmt.b32 %r22, %r26, 0, 0x7770U;
; SM90-NEXT:    selp.b32 %r23, %r22, %r11, %p1;
; SM90-NEXT:    prmt.b32 %r24, %r23, %r21, 0x3340U;
; SM90-NEXT:    prmt.b32 %r25, %r24, %r19, 0x5410U;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r26, %r25;
; SM90-NEXT:    setp.ne.b32 %p5, %r1, %r26;
; SM90-NEXT:    mov.b32 %r26, %r1;
; SM90-NEXT:    @%p5 bra $L__BB130_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise min ptr  addrspace(1) %addr, <4 x i8> %val syncscope("block") acq_rel
        ret <4 x i8> %retval
}

define <8 x i8> @min_acq_rel_v8i8_global_cta(ptr addrspace(1) %addr, <8 x i8> %val) {
; SM90-LABEL: min_acq_rel_v8i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<10>;
; SM90-NEXT:    .reg .b16 %rs<25>;
; SM90-NEXT:    .reg .b32 %r<51>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [min_acq_rel_v8i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [min_acq_rel_v8i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r50}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r49, %rd2;
; SM90-NEXT:    prmt.b32 %r3, %r2, 0, 0x8880U;
; SM90-NEXT:    prmt.b32 %r5, %r2, 0, 0x9991U;
; SM90-NEXT:  $L__BB131_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd3, %r49;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r50;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    prmt.b32 %r4, %r50, 0, 0x8880U;
; SM90-NEXT:    setp.le.s32 %p1, %r4, %r3;
; SM90-NEXT:    prmt.b32 %r6, %r50, 0, 0x9991U;
; SM90-NEXT:    setp.le.s32 %p2, %r6, %r5;
; SM90-NEXT:    prmt.b32 %r7, %r2, 0, 0xaaa2U;
; SM90-NEXT:    prmt.b32 %r8, %r50, 0, 0xaaa2U;
; SM90-NEXT:    setp.le.s32 %p3, %r8, %r7;
; SM90-NEXT:    prmt.b32 %r9, %r2, 0, 0xbbb3U;
; SM90-NEXT:    prmt.b32 %r10, %r50, 0, 0xbbb3U;
; SM90-NEXT:    setp.le.s32 %p4, %r10, %r9;
; SM90-NEXT:    prmt.b32 %r11, %r1, 0, 0x8880U;
; SM90-NEXT:    prmt.b32 %r12, %r49, 0, 0x8880U;
; SM90-NEXT:    setp.le.s32 %p5, %r12, %r11;
; SM90-NEXT:    prmt.b32 %r13, %r1, 0, 0x9991U;
; SM90-NEXT:    prmt.b32 %r14, %r49, 0, 0x9991U;
; SM90-NEXT:    setp.le.s32 %p6, %r14, %r13;
; SM90-NEXT:    prmt.b32 %r15, %r1, 0, 0xaaa2U;
; SM90-NEXT:    prmt.b32 %r16, %r49, 0, 0xaaa2U;
; SM90-NEXT:    setp.le.s32 %p7, %r16, %r15;
; SM90-NEXT:    prmt.b32 %r17, %r1, 0, 0xbbb3U;
; SM90-NEXT:    prmt.b32 %r18, %r49, 0, 0xbbb3U;
; SM90-NEXT:    setp.le.s32 %p8, %r18, %r17;
; SM90-NEXT:    prmt.b32 %r19, %r2, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs1, %r19;
; SM90-NEXT:    prmt.b32 %r20, %r50, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r20;
; SM90-NEXT:    prmt.b32 %r21, %r2, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs3, %r21;
; SM90-NEXT:    prmt.b32 %r22, %r50, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs4, %r22;
; SM90-NEXT:    prmt.b32 %r23, %r2, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs5, %r23;
; SM90-NEXT:    prmt.b32 %r24, %r50, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs6, %r24;
; SM90-NEXT:    prmt.b32 %r25, %r2, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs7, %r25;
; SM90-NEXT:    prmt.b32 %r26, %r50, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs8, %r26;
; SM90-NEXT:    prmt.b32 %r27, %r1, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs9, %r27;
; SM90-NEXT:    prmt.b32 %r28, %r49, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs10, %r28;
; SM90-NEXT:    prmt.b32 %r29, %r1, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs11, %r29;
; SM90-NEXT:    prmt.b32 %r30, %r49, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs12, %r30;
; SM90-NEXT:    prmt.b32 %r31, %r1, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs13, %r31;
; SM90-NEXT:    prmt.b32 %r32, %r49, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs14, %r32;
; SM90-NEXT:    prmt.b32 %r33, %r1, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs15, %r33;
; SM90-NEXT:    prmt.b32 %r34, %r49, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs16, %r34;
; SM90-NEXT:    selp.b16 %rs17, %rs16, %rs15, %p8;
; SM90-NEXT:    cvt.u32.u16 %r35, %rs17;
; SM90-NEXT:    selp.b16 %rs18, %rs14, %rs13, %p7;
; SM90-NEXT:    cvt.u32.u16 %r36, %rs18;
; SM90-NEXT:    prmt.b32 %r37, %r36, %r35, 0x3340U;
; SM90-NEXT:    selp.b16 %rs19, %rs12, %rs11, %p6;
; SM90-NEXT:    cvt.u32.u16 %r38, %rs19;
; SM90-NEXT:    selp.b16 %rs20, %rs10, %rs9, %p5;
; SM90-NEXT:    cvt.u32.u16 %r39, %rs20;
; SM90-NEXT:    prmt.b32 %r40, %r39, %r38, 0x3340U;
; SM90-NEXT:    prmt.b32 %r41, %r40, %r37, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r41;
; SM90-NEXT:    selp.b16 %rs21, %rs8, %rs7, %p4;
; SM90-NEXT:    cvt.u32.u16 %r42, %rs21;
; SM90-NEXT:    selp.b16 %rs22, %rs6, %rs5, %p3;
; SM90-NEXT:    cvt.u32.u16 %r43, %rs22;
; SM90-NEXT:    prmt.b32 %r44, %r43, %r42, 0x3340U;
; SM90-NEXT:    selp.b16 %rs23, %rs4, %rs3, %p2;
; SM90-NEXT:    cvt.u32.u16 %r45, %rs23;
; SM90-NEXT:    selp.b16 %rs24, %rs2, %rs1, %p1;
; SM90-NEXT:    cvt.u32.u16 %r46, %rs24;
; SM90-NEXT:    prmt.b32 %r47, %r46, %r45, 0x3340U;
; SM90-NEXT:    prmt.b32 %r48, %r47, %r44, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r48;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd6, %rd10;
; SM90-NEXT:    setp.ne.b64 %p9, %rd11, %rd6;
; SM90-NEXT:    mov.b64 {_, %r50}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r49, %rd11;
; SM90-NEXT:    @%p9 bra $L__BB131_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r49, %r50};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise min ptr  addrspace(1) %addr, <8 x i8> %val syncscope("block") acq_rel
        ret <8 x i8> %retval
}

define <1 x i16> @min_acq_rel_v1i16_global_cta(ptr addrspace(1) %addr, <1 x i16> %val) {
; SM90-LABEL: min_acq_rel_v1i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<4>;
; SM90-NEXT:    .reg .b32 %r<15>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [min_acq_rel_v1i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b16 %rs1, [min_acq_rel_v1i16_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r4, %rd2;
; SM90-NEXT:    and.b32 %r5, %r4, 3;
; SM90-NEXT:    shl.b32 %r1, %r5, 3;
; SM90-NEXT:    mov.b32 %r6, 65535;
; SM90-NEXT:    shl.b32 %r7, %r6, %r1;
; SM90-NEXT:    not.b32 %r2, %r7;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r14, [%rd1];
; SM90-NEXT:  $L__BB132_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r8, %r14, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r8;
; SM90-NEXT:    min.s16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r9, %rs3;
; SM90-NEXT:    shl.b32 %r10, %r9, %r1;
; SM90-NEXT:    and.b32 %r11, %r14, %r2;
; SM90-NEXT:    or.b32 %r12, %r11, %r10;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r14, %r12;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r14;
; SM90-NEXT:    mov.b32 %r14, %r3;
; SM90-NEXT:    @%p1 bra $L__BB132_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r13, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r13;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise min ptr  addrspace(1) %addr, <1 x i16> %val syncscope("block") acq_rel
        ret <1 x i16> %retval
}

define <2 x i16> @min_acq_rel_v2i16_global_cta(ptr addrspace(1) %addr, <2 x i16> %val) {
; SM90-LABEL: min_acq_rel_v2i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [min_acq_rel_v2i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [min_acq_rel_v2i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:  $L__BB133_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.s16x2 %r3, %r4, %r2;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r4;
; SM90-NEXT:    mov.b32 %r4, %r1;
; SM90-NEXT:    @%p1 bra $L__BB133_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise min ptr  addrspace(1) %addr, <2 x i16> %val syncscope("block") acq_rel
        ret <2 x i16> %retval
}

define <4 x i16> @min_acq_rel_v4i16_global_cta(ptr addrspace(1) %addr, <4 x i16> %val) {
; SM90-LABEL: min_acq_rel_v4i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [min_acq_rel_v4i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [min_acq_rel_v4i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB134_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd3, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r6;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    min.s16x2 %r3, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r3;
; SM90-NEXT:    min.s16x2 %r4, %r6, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r4;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd6, %rd10;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd6;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB134_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise min ptr  addrspace(1) %addr, <4 x i16> %val syncscope("block") acq_rel
        ret <4 x i16> %retval
}

define <8 x i16> @min_acq_rel_v8i16_global_cta(ptr addrspace(1) %addr, <8 x i16> %val) {
; SM90-LABEL: min_acq_rel_v8i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [min_acq_rel_v8i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [min_acq_rel_v8i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB135_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd5, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r10;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r12;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    min.s16x2 %r5, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r5;
; SM90-NEXT:    min.s16x2 %r6, %r10, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r6;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    min.s16x2 %r7, %r11, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r7;
; SM90-NEXT:    min.s16x2 %r8, %r12, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r8;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd8, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd16, %rd20};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd12;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd8;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd22;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB135_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise min ptr  addrspace(1) %addr, <8 x i16> %val syncscope("block") acq_rel
        ret <8 x i16> %retval
}

define <1 x i32> @min_acq_rel_v1i32_global_cta(ptr addrspace(1) %addr, <1 x i32> %val) {
; SM90-LABEL: min_acq_rel_v1i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<3>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [min_acq_rel_v1i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b32 %r1, [min_acq_rel_v1i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.min.s32 %r2, [%rd1], %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise min ptr  addrspace(1) %addr, <1 x i32> %val syncscope("block") acq_rel
        ret <1 x i32> %retval
}

define <2 x i32> @min_acq_rel_v2i32_global_cta(ptr addrspace(1) %addr, <2 x i32> %val) {
; SM90-LABEL: min_acq_rel_v2i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [min_acq_rel_v2i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [min_acq_rel_v2i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.min.s32 %r3, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.min.s32 %r4, [%rd1+4], %r2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r3, %r4};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise min ptr  addrspace(1) %addr, <2 x i32> %val syncscope("block") acq_rel
        ret <2 x i32> %retval
}

define <4 x i32> @min_acq_rel_v4i32_global_cta(ptr addrspace(1) %addr, <4 x i32> %val) {
; SM90-LABEL: min_acq_rel_v4i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<9>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [min_acq_rel_v4i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [min_acq_rel_v4i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.min.s32 %r5, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.min.s32 %r6, [%rd1+4], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.min.s32 %r7, [%rd1+8], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.min.s32 %r8, [%rd1+12], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise min ptr  addrspace(1) %addr, <4 x i32> %val syncscope("block") acq_rel
        ret <4 x i32> %retval
}

define <8 x i32> @min_acq_rel_v8i32_global_cta(ptr addrspace(1) %addr, <8 x i32> %val) {
; SM90-LABEL: min_acq_rel_v8i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<17>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [min_acq_rel_v8i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [min_acq_rel_v8i32_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [min_acq_rel_v8i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.min.s32 %r9, [%rd1], %r5;
; SM90-NEXT:    atom.relaxed.cta.global.min.s32 %r10, [%rd1+4], %r6;
; SM90-NEXT:    atom.relaxed.cta.global.min.s32 %r11, [%rd1+8], %r7;
; SM90-NEXT:    atom.relaxed.cta.global.min.s32 %r12, [%rd1+12], %r8;
; SM90-NEXT:    atom.relaxed.cta.global.min.s32 %r13, [%rd1+16], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.min.s32 %r14, [%rd1+20], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.min.s32 %r15, [%rd1+24], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.min.s32 %r16, [%rd1+28], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r13, %r14, %r15, %r16};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise min ptr  addrspace(1) %addr, <8 x i32> %val syncscope("block") acq_rel
        ret <8 x i32> %retval
}

define <1 x i64> @min_acq_rel_v1i64_global_cta(ptr addrspace(1) %addr, <1 x i64> %val) {
; SM90-LABEL: min_acq_rel_v1i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<4>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [min_acq_rel_v1i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b64 %rd2, [min_acq_rel_v1i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.min.s64 %rd3, [%rd1], %rd2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b64 [func_retval0], %rd3;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise min ptr  addrspace(1) %addr, <1 x i64> %val syncscope("block") acq_rel
        ret <1 x i64> %retval
}

define <2 x i64> @min_acq_rel_v2i64_global_cta(ptr addrspace(1) %addr, <2 x i64> %val) {
; SM90-LABEL: min_acq_rel_v2i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<6>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [min_acq_rel_v2i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [min_acq_rel_v2i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.min.s64 %rd4, [%rd1], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.min.s64 %rd5, [%rd1+8], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd4, %rd5};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise min ptr  addrspace(1) %addr, <2 x i64> %val syncscope("block") acq_rel
        ret <2 x i64> %retval
}

define <4 x i64> @min_acq_rel_v4i64_global_cta(ptr addrspace(1) %addr, <4 x i64> %val) {
; SM90-LABEL: min_acq_rel_v4i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<10>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [min_acq_rel_v4i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [min_acq_rel_v4i64_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [min_acq_rel_v4i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.min.s64 %rd6, [%rd1], %rd4;
; SM90-NEXT:    atom.relaxed.cta.global.min.s64 %rd7, [%rd1+8], %rd5;
; SM90-NEXT:    atom.relaxed.cta.global.min.s64 %rd8, [%rd1+16], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.min.s64 %rd9, [%rd1+24], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd8, %rd9};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd6, %rd7};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise min ptr  addrspace(1) %addr, <4 x i64> %val syncscope("block") acq_rel
        ret <4 x i64> %retval
}

define <8 x i64> @min_acq_rel_v8i64_global_cta(ptr addrspace(1) %addr, <8 x i64> %val) {
; SM90-LABEL: min_acq_rel_v8i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<18>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [min_acq_rel_v8i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [min_acq_rel_v8i64_global_cta_param_1+48];
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [min_acq_rel_v8i64_global_cta_param_1+32];
; SM90-NEXT:    ld.param.v2.b64 {%rd6, %rd7}, [min_acq_rel_v8i64_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v2.b64 {%rd8, %rd9}, [min_acq_rel_v8i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.min.s64 %rd10, [%rd1], %rd8;
; SM90-NEXT:    atom.relaxed.cta.global.min.s64 %rd11, [%rd1+8], %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.min.s64 %rd12, [%rd1+16], %rd6;
; SM90-NEXT:    atom.relaxed.cta.global.min.s64 %rd13, [%rd1+24], %rd7;
; SM90-NEXT:    atom.relaxed.cta.global.min.s64 %rd14, [%rd1+32], %rd4;
; SM90-NEXT:    atom.relaxed.cta.global.min.s64 %rd15, [%rd1+40], %rd5;
; SM90-NEXT:    atom.relaxed.cta.global.min.s64 %rd16, [%rd1+48], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.min.s64 %rd17, [%rd1+56], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+48], {%rd16, %rd17};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+32], {%rd14, %rd15};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd12, %rd13};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd10, %rd11};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise min ptr  addrspace(1) %addr, <8 x i64> %val syncscope("block") acq_rel
        ret <8 x i64> %retval
}

define <1 x i8> @umax_acq_rel_v1i8_global_cta(ptr addrspace(1) %addr, <1 x i8> %val) {
; SM90-LABEL: umax_acq_rel_v1i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<5>;
; SM90-NEXT:    .reg .b32 %r<15>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b8 %rs1, [umax_acq_rel_v1i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd2, [umax_acq_rel_v1i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r4, %rd2;
; SM90-NEXT:    and.b32 %r5, %r4, 3;
; SM90-NEXT:    shl.b32 %r1, %r5, 3;
; SM90-NEXT:    mov.b32 %r6, 255;
; SM90-NEXT:    shl.b32 %r7, %r6, %r1;
; SM90-NEXT:    not.b32 %r2, %r7;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r14, [%rd1];
; SM90-NEXT:  $L__BB144_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r8, %r14, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r8;
; SM90-NEXT:    and.b16 %rs3, %rs2, 255;
; SM90-NEXT:    max.u16 %rs4, %rs3, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r9, %rs4;
; SM90-NEXT:    shl.b32 %r10, %r9, %r1;
; SM90-NEXT:    and.b32 %r11, %r14, %r2;
; SM90-NEXT:    or.b32 %r12, %r11, %r10;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r14, %r12;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r14;
; SM90-NEXT:    mov.b32 %r14, %r3;
; SM90-NEXT:    @%p1 bra $L__BB144_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r13, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b8 [func_retval0], %r13;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umax ptr  addrspace(1) %addr, <1 x i8> %val syncscope("block") acq_rel
        ret <1 x i8> %retval
}

define <2 x i8> @umax_acq_rel_v2i8_global_cta(ptr addrspace(1) %addr, <2 x i8> %val) {
; SM90-LABEL: umax_acq_rel_v2i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<9>;
; SM90-NEXT:    .reg .b32 %r<19>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b8 {%rs1, %rs2}, [umax_acq_rel_v2i8_global_cta_param_1];
; SM90-NEXT:    mov.b32 %r4, {%rs1, %rs2};
; SM90-NEXT:    ld.param.b64 %rd2, [umax_acq_rel_v2i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:    and.b32 %r6, %r5, 3;
; SM90-NEXT:    shl.b32 %r1, %r6, 3;
; SM90-NEXT:    mov.b32 %r7, 65535;
; SM90-NEXT:    shl.b32 %r8, %r7, %r1;
; SM90-NEXT:    not.b32 %r2, %r8;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r18, [%rd1];
; SM90-NEXT:  $L__BB145_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r9, %r18, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs3, %r9;
; SM90-NEXT:    shr.u16 %rs4, %rs3, 8;
; SM90-NEXT:    mov.b32 %r10, {%rs3, %rs4};
; SM90-NEXT:    and.b32 %r11, %r10, 16711935;
; SM90-NEXT:    max.u16x2 %r12, %r11, %r4;
; SM90-NEXT:    mov.b32 {%rs5, %rs6}, %r12;
; SM90-NEXT:    shl.b16 %rs7, %rs6, 8;
; SM90-NEXT:    or.b16 %rs8, %rs5, %rs7;
; SM90-NEXT:    cvt.u32.u16 %r13, %rs8;
; SM90-NEXT:    shl.b32 %r14, %r13, %r1;
; SM90-NEXT:    and.b32 %r15, %r18, %r2;
; SM90-NEXT:    or.b32 %r16, %r15, %r14;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r18, %r16;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r18;
; SM90-NEXT:    mov.b32 %r18, %r3;
; SM90-NEXT:    @%p1 bra $L__BB145_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r17, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r17;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umax ptr  addrspace(1) %addr, <2 x i8> %val syncscope("block") acq_rel
        ret <2 x i8> %retval
}

define <4 x i8> @umax_acq_rel_v4i8_global_cta(ptr addrspace(1) %addr, <4 x i8> %val) {
; SM90-LABEL: umax_acq_rel_v4i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<6>;
; SM90-NEXT:    .reg .b32 %r<19>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [umax_acq_rel_v4i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [umax_acq_rel_v4i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r18, [%rd1];
; SM90-NEXT:    prmt.b32 %r3, %r2, 0, 0x7770U;
; SM90-NEXT:    prmt.b32 %r5, %r2, 0, 0x7771U;
; SM90-NEXT:    prmt.b32 %r7, %r2, 0, 0x7772U;
; SM90-NEXT:    prmt.b32 %r9, %r2, 0, 0x7773U;
; SM90-NEXT:  $L__BB146_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    prmt.b32 %r4, %r18, 0, 0x7770U;
; SM90-NEXT:    setp.gt.u32 %p1, %r4, %r3;
; SM90-NEXT:    prmt.b32 %r6, %r18, 0, 0x7771U;
; SM90-NEXT:    setp.gt.u32 %p2, %r6, %r5;
; SM90-NEXT:    prmt.b32 %r8, %r18, 0, 0x7772U;
; SM90-NEXT:    setp.gt.u32 %p3, %r8, %r7;
; SM90-NEXT:    prmt.b32 %r10, %r18, 0, 0x7773U;
; SM90-NEXT:    setp.gt.u32 %p4, %r10, %r9;
; SM90-NEXT:    selp.b32 %r11, %r10, %r9, %p4;
; SM90-NEXT:    selp.b32 %r12, %r8, %r7, %p3;
; SM90-NEXT:    prmt.b32 %r13, %r12, %r11, 0x3340U;
; SM90-NEXT:    selp.b32 %r14, %r6, %r5, %p2;
; SM90-NEXT:    selp.b32 %r15, %r4, %r3, %p1;
; SM90-NEXT:    prmt.b32 %r16, %r15, %r14, 0x3340U;
; SM90-NEXT:    prmt.b32 %r17, %r16, %r13, 0x5410U;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r18, %r17;
; SM90-NEXT:    setp.ne.b32 %p5, %r1, %r18;
; SM90-NEXT:    mov.b32 %r18, %r1;
; SM90-NEXT:    @%p5 bra $L__BB146_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umax ptr  addrspace(1) %addr, <4 x i8> %val syncscope("block") acq_rel
        ret <4 x i8> %retval
}

define <8 x i8> @umax_acq_rel_v8i8_global_cta(ptr addrspace(1) %addr, <8 x i8> %val) {
; SM90-LABEL: umax_acq_rel_v8i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<10>;
; SM90-NEXT:    .reg .b16 %rs<25>;
; SM90-NEXT:    .reg .b32 %r<35>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [umax_acq_rel_v8i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [umax_acq_rel_v8i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r34}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r33, %rd2;
; SM90-NEXT:    prmt.b32 %r3, %r2, 0, 0x7770U;
; SM90-NEXT:    prmt.b32 %r5, %r2, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs1, %r3;
; SM90-NEXT:    cvt.u16.u32 %rs3, %r5;
; SM90-NEXT:  $L__BB147_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd3, %r33;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r34;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    prmt.b32 %r4, %r34, 0, 0x7770U;
; SM90-NEXT:    setp.gt.u32 %p1, %r4, %r3;
; SM90-NEXT:    prmt.b32 %r6, %r34, 0, 0x7771U;
; SM90-NEXT:    setp.gt.u32 %p2, %r6, %r5;
; SM90-NEXT:    prmt.b32 %r7, %r2, 0, 0x7772U;
; SM90-NEXT:    prmt.b32 %r8, %r34, 0, 0x7772U;
; SM90-NEXT:    setp.gt.u32 %p3, %r8, %r7;
; SM90-NEXT:    prmt.b32 %r9, %r2, 0, 0x7773U;
; SM90-NEXT:    prmt.b32 %r10, %r34, 0, 0x7773U;
; SM90-NEXT:    setp.gt.u32 %p4, %r10, %r9;
; SM90-NEXT:    prmt.b32 %r11, %r1, 0, 0x7770U;
; SM90-NEXT:    prmt.b32 %r12, %r33, 0, 0x7770U;
; SM90-NEXT:    setp.gt.u32 %p5, %r12, %r11;
; SM90-NEXT:    prmt.b32 %r13, %r1, 0, 0x7771U;
; SM90-NEXT:    prmt.b32 %r14, %r33, 0, 0x7771U;
; SM90-NEXT:    setp.gt.u32 %p6, %r14, %r13;
; SM90-NEXT:    prmt.b32 %r15, %r1, 0, 0x7772U;
; SM90-NEXT:    prmt.b32 %r16, %r33, 0, 0x7772U;
; SM90-NEXT:    setp.gt.u32 %p7, %r16, %r15;
; SM90-NEXT:    prmt.b32 %r17, %r1, 0, 0x7773U;
; SM90-NEXT:    prmt.b32 %r18, %r33, 0, 0x7773U;
; SM90-NEXT:    setp.gt.u32 %p8, %r18, %r17;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r4;
; SM90-NEXT:    cvt.u16.u32 %rs4, %r6;
; SM90-NEXT:    cvt.u16.u32 %rs5, %r7;
; SM90-NEXT:    cvt.u16.u32 %rs6, %r8;
; SM90-NEXT:    cvt.u16.u32 %rs7, %r9;
; SM90-NEXT:    cvt.u16.u32 %rs8, %r10;
; SM90-NEXT:    cvt.u16.u32 %rs9, %r11;
; SM90-NEXT:    cvt.u16.u32 %rs10, %r12;
; SM90-NEXT:    cvt.u16.u32 %rs11, %r13;
; SM90-NEXT:    cvt.u16.u32 %rs12, %r14;
; SM90-NEXT:    cvt.u16.u32 %rs13, %r15;
; SM90-NEXT:    cvt.u16.u32 %rs14, %r16;
; SM90-NEXT:    cvt.u16.u32 %rs15, %r17;
; SM90-NEXT:    cvt.u16.u32 %rs16, %r18;
; SM90-NEXT:    selp.b16 %rs17, %rs16, %rs15, %p8;
; SM90-NEXT:    cvt.u32.u16 %r19, %rs17;
; SM90-NEXT:    selp.b16 %rs18, %rs14, %rs13, %p7;
; SM90-NEXT:    cvt.u32.u16 %r20, %rs18;
; SM90-NEXT:    prmt.b32 %r21, %r20, %r19, 0x3340U;
; SM90-NEXT:    selp.b16 %rs19, %rs12, %rs11, %p6;
; SM90-NEXT:    cvt.u32.u16 %r22, %rs19;
; SM90-NEXT:    selp.b16 %rs20, %rs10, %rs9, %p5;
; SM90-NEXT:    cvt.u32.u16 %r23, %rs20;
; SM90-NEXT:    prmt.b32 %r24, %r23, %r22, 0x3340U;
; SM90-NEXT:    prmt.b32 %r25, %r24, %r21, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r25;
; SM90-NEXT:    selp.b16 %rs21, %rs8, %rs7, %p4;
; SM90-NEXT:    cvt.u32.u16 %r26, %rs21;
; SM90-NEXT:    selp.b16 %rs22, %rs6, %rs5, %p3;
; SM90-NEXT:    cvt.u32.u16 %r27, %rs22;
; SM90-NEXT:    prmt.b32 %r28, %r27, %r26, 0x3340U;
; SM90-NEXT:    selp.b16 %rs23, %rs4, %rs3, %p2;
; SM90-NEXT:    cvt.u32.u16 %r29, %rs23;
; SM90-NEXT:    selp.b16 %rs24, %rs2, %rs1, %p1;
; SM90-NEXT:    cvt.u32.u16 %r30, %rs24;
; SM90-NEXT:    prmt.b32 %r31, %r30, %r29, 0x3340U;
; SM90-NEXT:    prmt.b32 %r32, %r31, %r28, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r32;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd6, %rd10;
; SM90-NEXT:    setp.ne.b64 %p9, %rd11, %rd6;
; SM90-NEXT:    mov.b64 {_, %r34}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r33, %rd11;
; SM90-NEXT:    @%p9 bra $L__BB147_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r33, %r34};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umax ptr  addrspace(1) %addr, <8 x i8> %val syncscope("block") acq_rel
        ret <8 x i8> %retval
}

define <1 x i16> @umax_acq_rel_v1i16_global_cta(ptr addrspace(1) %addr, <1 x i16> %val) {
; SM90-LABEL: umax_acq_rel_v1i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<4>;
; SM90-NEXT:    .reg .b32 %r<15>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [umax_acq_rel_v1i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b16 %rs1, [umax_acq_rel_v1i16_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r4, %rd2;
; SM90-NEXT:    and.b32 %r5, %r4, 3;
; SM90-NEXT:    shl.b32 %r1, %r5, 3;
; SM90-NEXT:    mov.b32 %r6, 65535;
; SM90-NEXT:    shl.b32 %r7, %r6, %r1;
; SM90-NEXT:    not.b32 %r2, %r7;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r14, [%rd1];
; SM90-NEXT:  $L__BB148_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r8, %r14, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r8;
; SM90-NEXT:    max.u16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r9, %rs3;
; SM90-NEXT:    shl.b32 %r10, %r9, %r1;
; SM90-NEXT:    and.b32 %r11, %r14, %r2;
; SM90-NEXT:    or.b32 %r12, %r11, %r10;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r14, %r12;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r14;
; SM90-NEXT:    mov.b32 %r14, %r3;
; SM90-NEXT:    @%p1 bra $L__BB148_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r13, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r13;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umax ptr  addrspace(1) %addr, <1 x i16> %val syncscope("block") acq_rel
        ret <1 x i16> %retval
}

define <2 x i16> @umax_acq_rel_v2i16_global_cta(ptr addrspace(1) %addr, <2 x i16> %val) {
; SM90-LABEL: umax_acq_rel_v2i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [umax_acq_rel_v2i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [umax_acq_rel_v2i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:  $L__BB149_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.u16x2 %r3, %r4, %r2;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r4;
; SM90-NEXT:    mov.b32 %r4, %r1;
; SM90-NEXT:    @%p1 bra $L__BB149_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umax ptr  addrspace(1) %addr, <2 x i16> %val syncscope("block") acq_rel
        ret <2 x i16> %retval
}

define <4 x i16> @umax_acq_rel_v4i16_global_cta(ptr addrspace(1) %addr, <4 x i16> %val) {
; SM90-LABEL: umax_acq_rel_v4i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [umax_acq_rel_v4i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [umax_acq_rel_v4i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB150_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd3, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r6;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    max.u16x2 %r3, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r3;
; SM90-NEXT:    max.u16x2 %r4, %r6, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r4;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd6, %rd10;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd6;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB150_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umax ptr  addrspace(1) %addr, <4 x i16> %val syncscope("block") acq_rel
        ret <4 x i16> %retval
}

define <8 x i16> @umax_acq_rel_v8i16_global_cta(ptr addrspace(1) %addr, <8 x i16> %val) {
; SM90-LABEL: umax_acq_rel_v8i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [umax_acq_rel_v8i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [umax_acq_rel_v8i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB151_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd5, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r10;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r12;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    max.u16x2 %r5, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r5;
; SM90-NEXT:    max.u16x2 %r6, %r10, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r6;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    max.u16x2 %r7, %r11, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r7;
; SM90-NEXT:    max.u16x2 %r8, %r12, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r8;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd8, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd16, %rd20};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd12;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd8;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd22;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB151_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umax ptr  addrspace(1) %addr, <8 x i16> %val syncscope("block") acq_rel
        ret <8 x i16> %retval
}

define <1 x i32> @umax_acq_rel_v1i32_global_cta(ptr addrspace(1) %addr, <1 x i32> %val) {
; SM90-LABEL: umax_acq_rel_v1i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<3>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [umax_acq_rel_v1i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b32 %r1, [umax_acq_rel_v1i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.max.u32 %r2, [%rd1], %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umax ptr  addrspace(1) %addr, <1 x i32> %val syncscope("block") acq_rel
        ret <1 x i32> %retval
}

define <2 x i32> @umax_acq_rel_v2i32_global_cta(ptr addrspace(1) %addr, <2 x i32> %val) {
; SM90-LABEL: umax_acq_rel_v2i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [umax_acq_rel_v2i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [umax_acq_rel_v2i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.max.u32 %r3, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.max.u32 %r4, [%rd1+4], %r2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r3, %r4};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umax ptr  addrspace(1) %addr, <2 x i32> %val syncscope("block") acq_rel
        ret <2 x i32> %retval
}

define <4 x i32> @umax_acq_rel_v4i32_global_cta(ptr addrspace(1) %addr, <4 x i32> %val) {
; SM90-LABEL: umax_acq_rel_v4i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<9>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [umax_acq_rel_v4i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [umax_acq_rel_v4i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.max.u32 %r5, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.max.u32 %r6, [%rd1+4], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.max.u32 %r7, [%rd1+8], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.max.u32 %r8, [%rd1+12], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umax ptr  addrspace(1) %addr, <4 x i32> %val syncscope("block") acq_rel
        ret <4 x i32> %retval
}

define <8 x i32> @umax_acq_rel_v8i32_global_cta(ptr addrspace(1) %addr, <8 x i32> %val) {
; SM90-LABEL: umax_acq_rel_v8i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<17>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [umax_acq_rel_v8i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [umax_acq_rel_v8i32_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [umax_acq_rel_v8i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.max.u32 %r9, [%rd1], %r5;
; SM90-NEXT:    atom.relaxed.cta.global.max.u32 %r10, [%rd1+4], %r6;
; SM90-NEXT:    atom.relaxed.cta.global.max.u32 %r11, [%rd1+8], %r7;
; SM90-NEXT:    atom.relaxed.cta.global.max.u32 %r12, [%rd1+12], %r8;
; SM90-NEXT:    atom.relaxed.cta.global.max.u32 %r13, [%rd1+16], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.max.u32 %r14, [%rd1+20], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.max.u32 %r15, [%rd1+24], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.max.u32 %r16, [%rd1+28], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r13, %r14, %r15, %r16};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umax ptr  addrspace(1) %addr, <8 x i32> %val syncscope("block") acq_rel
        ret <8 x i32> %retval
}

define <1 x i64> @umax_acq_rel_v1i64_global_cta(ptr addrspace(1) %addr, <1 x i64> %val) {
; SM90-LABEL: umax_acq_rel_v1i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<4>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [umax_acq_rel_v1i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b64 %rd2, [umax_acq_rel_v1i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.max.u64 %rd3, [%rd1], %rd2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b64 [func_retval0], %rd3;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umax ptr  addrspace(1) %addr, <1 x i64> %val syncscope("block") acq_rel
        ret <1 x i64> %retval
}

define <2 x i64> @umax_acq_rel_v2i64_global_cta(ptr addrspace(1) %addr, <2 x i64> %val) {
; SM90-LABEL: umax_acq_rel_v2i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<6>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [umax_acq_rel_v2i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [umax_acq_rel_v2i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.max.u64 %rd4, [%rd1], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.max.u64 %rd5, [%rd1+8], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd4, %rd5};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umax ptr  addrspace(1) %addr, <2 x i64> %val syncscope("block") acq_rel
        ret <2 x i64> %retval
}

define <4 x i64> @umax_acq_rel_v4i64_global_cta(ptr addrspace(1) %addr, <4 x i64> %val) {
; SM90-LABEL: umax_acq_rel_v4i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<10>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [umax_acq_rel_v4i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [umax_acq_rel_v4i64_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [umax_acq_rel_v4i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.max.u64 %rd6, [%rd1], %rd4;
; SM90-NEXT:    atom.relaxed.cta.global.max.u64 %rd7, [%rd1+8], %rd5;
; SM90-NEXT:    atom.relaxed.cta.global.max.u64 %rd8, [%rd1+16], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.max.u64 %rd9, [%rd1+24], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd8, %rd9};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd6, %rd7};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umax ptr  addrspace(1) %addr, <4 x i64> %val syncscope("block") acq_rel
        ret <4 x i64> %retval
}

define <8 x i64> @umax_acq_rel_v8i64_global_cta(ptr addrspace(1) %addr, <8 x i64> %val) {
; SM90-LABEL: umax_acq_rel_v8i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<18>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [umax_acq_rel_v8i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [umax_acq_rel_v8i64_global_cta_param_1+48];
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [umax_acq_rel_v8i64_global_cta_param_1+32];
; SM90-NEXT:    ld.param.v2.b64 {%rd6, %rd7}, [umax_acq_rel_v8i64_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v2.b64 {%rd8, %rd9}, [umax_acq_rel_v8i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.max.u64 %rd10, [%rd1], %rd8;
; SM90-NEXT:    atom.relaxed.cta.global.max.u64 %rd11, [%rd1+8], %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.max.u64 %rd12, [%rd1+16], %rd6;
; SM90-NEXT:    atom.relaxed.cta.global.max.u64 %rd13, [%rd1+24], %rd7;
; SM90-NEXT:    atom.relaxed.cta.global.max.u64 %rd14, [%rd1+32], %rd4;
; SM90-NEXT:    atom.relaxed.cta.global.max.u64 %rd15, [%rd1+40], %rd5;
; SM90-NEXT:    atom.relaxed.cta.global.max.u64 %rd16, [%rd1+48], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.max.u64 %rd17, [%rd1+56], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+48], {%rd16, %rd17};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+32], {%rd14, %rd15};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd12, %rd13};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd10, %rd11};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umax ptr  addrspace(1) %addr, <8 x i64> %val syncscope("block") acq_rel
        ret <8 x i64> %retval
}

define <1 x i8> @umin_acq_rel_v1i8_global_cta(ptr addrspace(1) %addr, <1 x i8> %val) {
; SM90-LABEL: umin_acq_rel_v1i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<5>;
; SM90-NEXT:    .reg .b32 %r<15>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b8 %rs1, [umin_acq_rel_v1i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd2, [umin_acq_rel_v1i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r4, %rd2;
; SM90-NEXT:    and.b32 %r5, %r4, 3;
; SM90-NEXT:    shl.b32 %r1, %r5, 3;
; SM90-NEXT:    mov.b32 %r6, 255;
; SM90-NEXT:    shl.b32 %r7, %r6, %r1;
; SM90-NEXT:    not.b32 %r2, %r7;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r14, [%rd1];
; SM90-NEXT:  $L__BB160_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r8, %r14, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r8;
; SM90-NEXT:    and.b16 %rs3, %rs2, 255;
; SM90-NEXT:    min.u16 %rs4, %rs3, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r9, %rs4;
; SM90-NEXT:    shl.b32 %r10, %r9, %r1;
; SM90-NEXT:    and.b32 %r11, %r14, %r2;
; SM90-NEXT:    or.b32 %r12, %r11, %r10;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r14, %r12;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r14;
; SM90-NEXT:    mov.b32 %r14, %r3;
; SM90-NEXT:    @%p1 bra $L__BB160_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r13, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b8 [func_retval0], %r13;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umin ptr  addrspace(1) %addr, <1 x i8> %val syncscope("block") acq_rel
        ret <1 x i8> %retval
}

define <2 x i8> @umin_acq_rel_v2i8_global_cta(ptr addrspace(1) %addr, <2 x i8> %val) {
; SM90-LABEL: umin_acq_rel_v2i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<9>;
; SM90-NEXT:    .reg .b32 %r<19>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b8 {%rs1, %rs2}, [umin_acq_rel_v2i8_global_cta_param_1];
; SM90-NEXT:    mov.b32 %r4, {%rs1, %rs2};
; SM90-NEXT:    ld.param.b64 %rd2, [umin_acq_rel_v2i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:    and.b32 %r6, %r5, 3;
; SM90-NEXT:    shl.b32 %r1, %r6, 3;
; SM90-NEXT:    mov.b32 %r7, 65535;
; SM90-NEXT:    shl.b32 %r8, %r7, %r1;
; SM90-NEXT:    not.b32 %r2, %r8;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r18, [%rd1];
; SM90-NEXT:  $L__BB161_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r9, %r18, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs3, %r9;
; SM90-NEXT:    shr.u16 %rs4, %rs3, 8;
; SM90-NEXT:    mov.b32 %r10, {%rs3, %rs4};
; SM90-NEXT:    and.b32 %r11, %r10, 16711935;
; SM90-NEXT:    min.u16x2 %r12, %r11, %r4;
; SM90-NEXT:    mov.b32 {%rs5, %rs6}, %r12;
; SM90-NEXT:    shl.b16 %rs7, %rs6, 8;
; SM90-NEXT:    or.b16 %rs8, %rs5, %rs7;
; SM90-NEXT:    cvt.u32.u16 %r13, %rs8;
; SM90-NEXT:    shl.b32 %r14, %r13, %r1;
; SM90-NEXT:    and.b32 %r15, %r18, %r2;
; SM90-NEXT:    or.b32 %r16, %r15, %r14;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r18, %r16;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r18;
; SM90-NEXT:    mov.b32 %r18, %r3;
; SM90-NEXT:    @%p1 bra $L__BB161_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r17, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r17;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umin ptr  addrspace(1) %addr, <2 x i8> %val syncscope("block") acq_rel
        ret <2 x i8> %retval
}

define <4 x i8> @umin_acq_rel_v4i8_global_cta(ptr addrspace(1) %addr, <4 x i8> %val) {
; SM90-LABEL: umin_acq_rel_v4i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<6>;
; SM90-NEXT:    .reg .b32 %r<19>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [umin_acq_rel_v4i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [umin_acq_rel_v4i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r18, [%rd1];
; SM90-NEXT:    prmt.b32 %r3, %r2, 0, 0x7770U;
; SM90-NEXT:    prmt.b32 %r5, %r2, 0, 0x7771U;
; SM90-NEXT:    prmt.b32 %r7, %r2, 0, 0x7772U;
; SM90-NEXT:    prmt.b32 %r9, %r2, 0, 0x7773U;
; SM90-NEXT:  $L__BB162_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    prmt.b32 %r4, %r18, 0, 0x7770U;
; SM90-NEXT:    setp.le.u32 %p1, %r4, %r3;
; SM90-NEXT:    prmt.b32 %r6, %r18, 0, 0x7771U;
; SM90-NEXT:    setp.le.u32 %p2, %r6, %r5;
; SM90-NEXT:    prmt.b32 %r8, %r18, 0, 0x7772U;
; SM90-NEXT:    setp.le.u32 %p3, %r8, %r7;
; SM90-NEXT:    prmt.b32 %r10, %r18, 0, 0x7773U;
; SM90-NEXT:    setp.le.u32 %p4, %r10, %r9;
; SM90-NEXT:    selp.b32 %r11, %r10, %r9, %p4;
; SM90-NEXT:    selp.b32 %r12, %r8, %r7, %p3;
; SM90-NEXT:    prmt.b32 %r13, %r12, %r11, 0x3340U;
; SM90-NEXT:    selp.b32 %r14, %r6, %r5, %p2;
; SM90-NEXT:    selp.b32 %r15, %r4, %r3, %p1;
; SM90-NEXT:    prmt.b32 %r16, %r15, %r14, 0x3340U;
; SM90-NEXT:    prmt.b32 %r17, %r16, %r13, 0x5410U;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r18, %r17;
; SM90-NEXT:    setp.ne.b32 %p5, %r1, %r18;
; SM90-NEXT:    mov.b32 %r18, %r1;
; SM90-NEXT:    @%p5 bra $L__BB162_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umin ptr  addrspace(1) %addr, <4 x i8> %val syncscope("block") acq_rel
        ret <4 x i8> %retval
}

define <8 x i8> @umin_acq_rel_v8i8_global_cta(ptr addrspace(1) %addr, <8 x i8> %val) {
; SM90-LABEL: umin_acq_rel_v8i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<10>;
; SM90-NEXT:    .reg .b16 %rs<25>;
; SM90-NEXT:    .reg .b32 %r<35>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [umin_acq_rel_v8i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [umin_acq_rel_v8i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r34}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r33, %rd2;
; SM90-NEXT:    prmt.b32 %r3, %r2, 0, 0x7770U;
; SM90-NEXT:    prmt.b32 %r5, %r2, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs1, %r3;
; SM90-NEXT:    cvt.u16.u32 %rs3, %r5;
; SM90-NEXT:  $L__BB163_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd3, %r33;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r34;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    prmt.b32 %r4, %r34, 0, 0x7770U;
; SM90-NEXT:    setp.le.u32 %p1, %r4, %r3;
; SM90-NEXT:    prmt.b32 %r6, %r34, 0, 0x7771U;
; SM90-NEXT:    setp.le.u32 %p2, %r6, %r5;
; SM90-NEXT:    prmt.b32 %r7, %r2, 0, 0x7772U;
; SM90-NEXT:    prmt.b32 %r8, %r34, 0, 0x7772U;
; SM90-NEXT:    setp.le.u32 %p3, %r8, %r7;
; SM90-NEXT:    prmt.b32 %r9, %r2, 0, 0x7773U;
; SM90-NEXT:    prmt.b32 %r10, %r34, 0, 0x7773U;
; SM90-NEXT:    setp.le.u32 %p4, %r10, %r9;
; SM90-NEXT:    prmt.b32 %r11, %r1, 0, 0x7770U;
; SM90-NEXT:    prmt.b32 %r12, %r33, 0, 0x7770U;
; SM90-NEXT:    setp.le.u32 %p5, %r12, %r11;
; SM90-NEXT:    prmt.b32 %r13, %r1, 0, 0x7771U;
; SM90-NEXT:    prmt.b32 %r14, %r33, 0, 0x7771U;
; SM90-NEXT:    setp.le.u32 %p6, %r14, %r13;
; SM90-NEXT:    prmt.b32 %r15, %r1, 0, 0x7772U;
; SM90-NEXT:    prmt.b32 %r16, %r33, 0, 0x7772U;
; SM90-NEXT:    setp.le.u32 %p7, %r16, %r15;
; SM90-NEXT:    prmt.b32 %r17, %r1, 0, 0x7773U;
; SM90-NEXT:    prmt.b32 %r18, %r33, 0, 0x7773U;
; SM90-NEXT:    setp.le.u32 %p8, %r18, %r17;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r4;
; SM90-NEXT:    cvt.u16.u32 %rs4, %r6;
; SM90-NEXT:    cvt.u16.u32 %rs5, %r7;
; SM90-NEXT:    cvt.u16.u32 %rs6, %r8;
; SM90-NEXT:    cvt.u16.u32 %rs7, %r9;
; SM90-NEXT:    cvt.u16.u32 %rs8, %r10;
; SM90-NEXT:    cvt.u16.u32 %rs9, %r11;
; SM90-NEXT:    cvt.u16.u32 %rs10, %r12;
; SM90-NEXT:    cvt.u16.u32 %rs11, %r13;
; SM90-NEXT:    cvt.u16.u32 %rs12, %r14;
; SM90-NEXT:    cvt.u16.u32 %rs13, %r15;
; SM90-NEXT:    cvt.u16.u32 %rs14, %r16;
; SM90-NEXT:    cvt.u16.u32 %rs15, %r17;
; SM90-NEXT:    cvt.u16.u32 %rs16, %r18;
; SM90-NEXT:    selp.b16 %rs17, %rs16, %rs15, %p8;
; SM90-NEXT:    cvt.u32.u16 %r19, %rs17;
; SM90-NEXT:    selp.b16 %rs18, %rs14, %rs13, %p7;
; SM90-NEXT:    cvt.u32.u16 %r20, %rs18;
; SM90-NEXT:    prmt.b32 %r21, %r20, %r19, 0x3340U;
; SM90-NEXT:    selp.b16 %rs19, %rs12, %rs11, %p6;
; SM90-NEXT:    cvt.u32.u16 %r22, %rs19;
; SM90-NEXT:    selp.b16 %rs20, %rs10, %rs9, %p5;
; SM90-NEXT:    cvt.u32.u16 %r23, %rs20;
; SM90-NEXT:    prmt.b32 %r24, %r23, %r22, 0x3340U;
; SM90-NEXT:    prmt.b32 %r25, %r24, %r21, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r25;
; SM90-NEXT:    selp.b16 %rs21, %rs8, %rs7, %p4;
; SM90-NEXT:    cvt.u32.u16 %r26, %rs21;
; SM90-NEXT:    selp.b16 %rs22, %rs6, %rs5, %p3;
; SM90-NEXT:    cvt.u32.u16 %r27, %rs22;
; SM90-NEXT:    prmt.b32 %r28, %r27, %r26, 0x3340U;
; SM90-NEXT:    selp.b16 %rs23, %rs4, %rs3, %p2;
; SM90-NEXT:    cvt.u32.u16 %r29, %rs23;
; SM90-NEXT:    selp.b16 %rs24, %rs2, %rs1, %p1;
; SM90-NEXT:    cvt.u32.u16 %r30, %rs24;
; SM90-NEXT:    prmt.b32 %r31, %r30, %r29, 0x3340U;
; SM90-NEXT:    prmt.b32 %r32, %r31, %r28, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r32;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd6, %rd10;
; SM90-NEXT:    setp.ne.b64 %p9, %rd11, %rd6;
; SM90-NEXT:    mov.b64 {_, %r34}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r33, %rd11;
; SM90-NEXT:    @%p9 bra $L__BB163_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r33, %r34};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umin ptr  addrspace(1) %addr, <8 x i8> %val syncscope("block") acq_rel
        ret <8 x i8> %retval
}

define <1 x i16> @umin_acq_rel_v1i16_global_cta(ptr addrspace(1) %addr, <1 x i16> %val) {
; SM90-LABEL: umin_acq_rel_v1i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<4>;
; SM90-NEXT:    .reg .b32 %r<15>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [umin_acq_rel_v1i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b16 %rs1, [umin_acq_rel_v1i16_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r4, %rd2;
; SM90-NEXT:    and.b32 %r5, %r4, 3;
; SM90-NEXT:    shl.b32 %r1, %r5, 3;
; SM90-NEXT:    mov.b32 %r6, 65535;
; SM90-NEXT:    shl.b32 %r7, %r6, %r1;
; SM90-NEXT:    not.b32 %r2, %r7;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r14, [%rd1];
; SM90-NEXT:  $L__BB164_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r8, %r14, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r8;
; SM90-NEXT:    min.u16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r9, %rs3;
; SM90-NEXT:    shl.b32 %r10, %r9, %r1;
; SM90-NEXT:    and.b32 %r11, %r14, %r2;
; SM90-NEXT:    or.b32 %r12, %r11, %r10;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r14, %r12;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r14;
; SM90-NEXT:    mov.b32 %r14, %r3;
; SM90-NEXT:    @%p1 bra $L__BB164_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r13, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r13;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umin ptr  addrspace(1) %addr, <1 x i16> %val syncscope("block") acq_rel
        ret <1 x i16> %retval
}

define <2 x i16> @umin_acq_rel_v2i16_global_cta(ptr addrspace(1) %addr, <2 x i16> %val) {
; SM90-LABEL: umin_acq_rel_v2i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [umin_acq_rel_v2i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [umin_acq_rel_v2i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:  $L__BB165_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.u16x2 %r3, %r4, %r2;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r4;
; SM90-NEXT:    mov.b32 %r4, %r1;
; SM90-NEXT:    @%p1 bra $L__BB165_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umin ptr  addrspace(1) %addr, <2 x i16> %val syncscope("block") acq_rel
        ret <2 x i16> %retval
}

define <4 x i16> @umin_acq_rel_v4i16_global_cta(ptr addrspace(1) %addr, <4 x i16> %val) {
; SM90-LABEL: umin_acq_rel_v4i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [umin_acq_rel_v4i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [umin_acq_rel_v4i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB166_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd3, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r6;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    min.u16x2 %r3, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r3;
; SM90-NEXT:    min.u16x2 %r4, %r6, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r4;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd6, %rd10;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd6;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB166_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umin ptr  addrspace(1) %addr, <4 x i16> %val syncscope("block") acq_rel
        ret <4 x i16> %retval
}

define <8 x i16> @umin_acq_rel_v8i16_global_cta(ptr addrspace(1) %addr, <8 x i16> %val) {
; SM90-LABEL: umin_acq_rel_v8i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [umin_acq_rel_v8i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [umin_acq_rel_v8i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB167_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd5, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r10;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r12;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    min.u16x2 %r5, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r5;
; SM90-NEXT:    min.u16x2 %r6, %r10, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r6;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    min.u16x2 %r7, %r11, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r7;
; SM90-NEXT:    min.u16x2 %r8, %r12, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r8;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd8, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd16, %rd20};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd12;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd8;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd22;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB167_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umin ptr  addrspace(1) %addr, <8 x i16> %val syncscope("block") acq_rel
        ret <8 x i16> %retval
}

define <1 x i32> @umin_acq_rel_v1i32_global_cta(ptr addrspace(1) %addr, <1 x i32> %val) {
; SM90-LABEL: umin_acq_rel_v1i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<3>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [umin_acq_rel_v1i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b32 %r1, [umin_acq_rel_v1i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.min.u32 %r2, [%rd1], %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umin ptr  addrspace(1) %addr, <1 x i32> %val syncscope("block") acq_rel
        ret <1 x i32> %retval
}

define <2 x i32> @umin_acq_rel_v2i32_global_cta(ptr addrspace(1) %addr, <2 x i32> %val) {
; SM90-LABEL: umin_acq_rel_v2i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [umin_acq_rel_v2i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [umin_acq_rel_v2i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.min.u32 %r3, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.min.u32 %r4, [%rd1+4], %r2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r3, %r4};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umin ptr  addrspace(1) %addr, <2 x i32> %val syncscope("block") acq_rel
        ret <2 x i32> %retval
}

define <4 x i32> @umin_acq_rel_v4i32_global_cta(ptr addrspace(1) %addr, <4 x i32> %val) {
; SM90-LABEL: umin_acq_rel_v4i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<9>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [umin_acq_rel_v4i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [umin_acq_rel_v4i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.min.u32 %r5, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.min.u32 %r6, [%rd1+4], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.min.u32 %r7, [%rd1+8], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.min.u32 %r8, [%rd1+12], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umin ptr  addrspace(1) %addr, <4 x i32> %val syncscope("block") acq_rel
        ret <4 x i32> %retval
}

define <8 x i32> @umin_acq_rel_v8i32_global_cta(ptr addrspace(1) %addr, <8 x i32> %val) {
; SM90-LABEL: umin_acq_rel_v8i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<17>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [umin_acq_rel_v8i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [umin_acq_rel_v8i32_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [umin_acq_rel_v8i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.min.u32 %r9, [%rd1], %r5;
; SM90-NEXT:    atom.relaxed.cta.global.min.u32 %r10, [%rd1+4], %r6;
; SM90-NEXT:    atom.relaxed.cta.global.min.u32 %r11, [%rd1+8], %r7;
; SM90-NEXT:    atom.relaxed.cta.global.min.u32 %r12, [%rd1+12], %r8;
; SM90-NEXT:    atom.relaxed.cta.global.min.u32 %r13, [%rd1+16], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.min.u32 %r14, [%rd1+20], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.min.u32 %r15, [%rd1+24], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.min.u32 %r16, [%rd1+28], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r13, %r14, %r15, %r16};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umin ptr  addrspace(1) %addr, <8 x i32> %val syncscope("block") acq_rel
        ret <8 x i32> %retval
}

define <1 x i64> @umin_acq_rel_v1i64_global_cta(ptr addrspace(1) %addr, <1 x i64> %val) {
; SM90-LABEL: umin_acq_rel_v1i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<4>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [umin_acq_rel_v1i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b64 %rd2, [umin_acq_rel_v1i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.min.u64 %rd3, [%rd1], %rd2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b64 [func_retval0], %rd3;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umin ptr  addrspace(1) %addr, <1 x i64> %val syncscope("block") acq_rel
        ret <1 x i64> %retval
}

define <2 x i64> @umin_acq_rel_v2i64_global_cta(ptr addrspace(1) %addr, <2 x i64> %val) {
; SM90-LABEL: umin_acq_rel_v2i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<6>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [umin_acq_rel_v2i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [umin_acq_rel_v2i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.min.u64 %rd4, [%rd1], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.min.u64 %rd5, [%rd1+8], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd4, %rd5};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umin ptr  addrspace(1) %addr, <2 x i64> %val syncscope("block") acq_rel
        ret <2 x i64> %retval
}

define <4 x i64> @umin_acq_rel_v4i64_global_cta(ptr addrspace(1) %addr, <4 x i64> %val) {
; SM90-LABEL: umin_acq_rel_v4i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<10>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [umin_acq_rel_v4i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [umin_acq_rel_v4i64_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [umin_acq_rel_v4i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.min.u64 %rd6, [%rd1], %rd4;
; SM90-NEXT:    atom.relaxed.cta.global.min.u64 %rd7, [%rd1+8], %rd5;
; SM90-NEXT:    atom.relaxed.cta.global.min.u64 %rd8, [%rd1+16], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.min.u64 %rd9, [%rd1+24], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd8, %rd9};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd6, %rd7};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umin ptr  addrspace(1) %addr, <4 x i64> %val syncscope("block") acq_rel
        ret <4 x i64> %retval
}

define <8 x i64> @umin_acq_rel_v8i64_global_cta(ptr addrspace(1) %addr, <8 x i64> %val) {
; SM90-LABEL: umin_acq_rel_v8i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<18>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [umin_acq_rel_v8i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [umin_acq_rel_v8i64_global_cta_param_1+48];
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [umin_acq_rel_v8i64_global_cta_param_1+32];
; SM90-NEXT:    ld.param.v2.b64 {%rd6, %rd7}, [umin_acq_rel_v8i64_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v2.b64 {%rd8, %rd9}, [umin_acq_rel_v8i64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.min.u64 %rd10, [%rd1], %rd8;
; SM90-NEXT:    atom.relaxed.cta.global.min.u64 %rd11, [%rd1+8], %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.min.u64 %rd12, [%rd1+16], %rd6;
; SM90-NEXT:    atom.relaxed.cta.global.min.u64 %rd13, [%rd1+24], %rd7;
; SM90-NEXT:    atom.relaxed.cta.global.min.u64 %rd14, [%rd1+32], %rd4;
; SM90-NEXT:    atom.relaxed.cta.global.min.u64 %rd15, [%rd1+40], %rd5;
; SM90-NEXT:    atom.relaxed.cta.global.min.u64 %rd16, [%rd1+48], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.min.u64 %rd17, [%rd1+56], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+48], {%rd16, %rd17};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+32], {%rd14, %rd15};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd12, %rd13};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd10, %rd11};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise umin ptr  addrspace(1) %addr, <8 x i64> %val syncscope("block") acq_rel
        ret <8 x i64> %retval
}

define <1 x i8> @uinc_wrap_acq_rel_v1i8_global_cta(ptr addrspace(1) %addr, <1 x i8> %val) {
; SM90-LABEL: uinc_wrap_acq_rel_v1i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<3>;
; SM90-NEXT:    .reg .b16 %rs<6>;
; SM90-NEXT:    .reg .b32 %r<16>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b8 %rs1, [uinc_wrap_acq_rel_v1i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd2, [uinc_wrap_acq_rel_v1i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r4, %rd2;
; SM90-NEXT:    and.b32 %r5, %r4, 3;
; SM90-NEXT:    shl.b32 %r1, %r5, 3;
; SM90-NEXT:    mov.b32 %r6, 255;
; SM90-NEXT:    shl.b32 %r7, %r6, %r1;
; SM90-NEXT:    not.b32 %r2, %r7;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r15, [%rd1];
; SM90-NEXT:  $L__BB176_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r8, %r15, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r8;
; SM90-NEXT:    and.b16 %rs3, %rs2, 255;
; SM90-NEXT:    add.s16 %rs4, %rs2, 1;
; SM90-NEXT:    setp.ge.u16 %p1, %rs3, %rs1;
; SM90-NEXT:    selp.b16 %rs5, 0, %rs4, %p1;
; SM90-NEXT:    cvt.u32.u16 %r9, %rs5;
; SM90-NEXT:    and.b32 %r10, %r9, 255;
; SM90-NEXT:    shl.b32 %r11, %r10, %r1;
; SM90-NEXT:    and.b32 %r12, %r15, %r2;
; SM90-NEXT:    or.b32 %r13, %r12, %r11;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r15, %r13;
; SM90-NEXT:    setp.ne.b32 %p2, %r3, %r15;
; SM90-NEXT:    mov.b32 %r15, %r3;
; SM90-NEXT:    @%p2 bra $L__BB176_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r14, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b8 [func_retval0], %r14;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise uinc_wrap ptr  addrspace(1) %addr, <1 x i8> %val syncscope("block") acq_rel
        ret <1 x i8> %retval
}

define <2 x i8> @uinc_wrap_acq_rel_v2i8_global_cta(ptr addrspace(1) %addr, <2 x i8> %val) {
; SM90-LABEL: uinc_wrap_acq_rel_v2i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<4>;
; SM90-NEXT:    .reg .b16 %rs<15>;
; SM90-NEXT:    .reg .b32 %r<19>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b8 {%rs1, %rs2}, [uinc_wrap_acq_rel_v2i8_global_cta_param_1];
; SM90-NEXT:    mov.b32 %r4, {%rs1, %rs2};
; SM90-NEXT:    ld.param.b64 %rd2, [uinc_wrap_acq_rel_v2i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:    and.b32 %r6, %r5, 3;
; SM90-NEXT:    shl.b32 %r1, %r6, 3;
; SM90-NEXT:    mov.b32 %r7, 65535;
; SM90-NEXT:    shl.b32 %r8, %r7, %r1;
; SM90-NEXT:    not.b32 %r2, %r8;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r18, [%rd1];
; SM90-NEXT:    mov.b32 {%rs6, %rs7}, %r4;
; SM90-NEXT:  $L__BB177_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r9, %r18, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs3, %r9;
; SM90-NEXT:    shr.u16 %rs4, %rs3, 8;
; SM90-NEXT:    mov.b32 %r10, {%rs3, %rs4};
; SM90-NEXT:    and.b16 %rs5, %rs3, 255;
; SM90-NEXT:    mov.b32 %r11, 65537;
; SM90-NEXT:    add.s16x2 %r12, %r10, %r11;
; SM90-NEXT:    setp.ge.u16 %p1, %rs4, %rs7;
; SM90-NEXT:    setp.ge.u16 %p2, %rs5, %rs6;
; SM90-NEXT:    mov.b32 {%rs8, %rs9}, %r12;
; SM90-NEXT:    selp.b16 %rs10, 0, %rs8, %p2;
; SM90-NEXT:    selp.b16 %rs11, 0, %rs9, %p1;
; SM90-NEXT:    shl.b16 %rs12, %rs11, 8;
; SM90-NEXT:    and.b16 %rs13, %rs10, 255;
; SM90-NEXT:    or.b16 %rs14, %rs13, %rs12;
; SM90-NEXT:    cvt.u32.u16 %r13, %rs14;
; SM90-NEXT:    shl.b32 %r14, %r13, %r1;
; SM90-NEXT:    and.b32 %r15, %r18, %r2;
; SM90-NEXT:    or.b32 %r16, %r15, %r14;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r18, %r16;
; SM90-NEXT:    setp.ne.b32 %p3, %r3, %r18;
; SM90-NEXT:    mov.b32 %r18, %r3;
; SM90-NEXT:    @%p3 bra $L__BB177_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r17, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r17;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise uinc_wrap ptr  addrspace(1) %addr, <2 x i8> %val syncscope("block") acq_rel
        ret <2 x i8> %retval
}

define <4 x i8> @uinc_wrap_acq_rel_v4i8_global_cta(ptr addrspace(1) %addr, <4 x i8> %val) {
; SM90-LABEL: uinc_wrap_acq_rel_v4i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<6>;
; SM90-NEXT:    .reg .b16 %rs<9>;
; SM90-NEXT:    .reg .b32 %r<23>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [uinc_wrap_acq_rel_v4i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [uinc_wrap_acq_rel_v4i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r22, [%rd1];
; SM90-NEXT:    prmt.b32 %r7, %r2, 0, 0x7770U;
; SM90-NEXT:    prmt.b32 %r8, %r2, 0, 0x7771U;
; SM90-NEXT:    prmt.b32 %r9, %r2, 0, 0x7772U;
; SM90-NEXT:    prmt.b32 %r10, %r2, 0, 0x7773U;
; SM90-NEXT:  $L__BB178_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    prmt.b32 %r3, %r22, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs1, %r3;
; SM90-NEXT:    add.s16 %rs2, %rs1, 1;
; SM90-NEXT:    prmt.b32 %r4, %r22, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs3, %r4;
; SM90-NEXT:    add.s16 %rs4, %rs3, 1;
; SM90-NEXT:    prmt.b32 %r5, %r22, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs5, %r5;
; SM90-NEXT:    add.s16 %rs6, %rs5, 1;
; SM90-NEXT:    prmt.b32 %r6, %r22, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs7, %r6;
; SM90-NEXT:    add.s16 %rs8, %rs7, 1;
; SM90-NEXT:    setp.ge.u32 %p1, %r3, %r7;
; SM90-NEXT:    setp.ge.u32 %p2, %r4, %r8;
; SM90-NEXT:    setp.ge.u32 %p3, %r5, %r9;
; SM90-NEXT:    setp.ge.u32 %p4, %r6, %r10;
; SM90-NEXT:    cvt.u32.u16 %r11, %rs8;
; SM90-NEXT:    selp.b32 %r12, 0, %r11, %p4;
; SM90-NEXT:    cvt.u32.u16 %r13, %rs6;
; SM90-NEXT:    selp.b32 %r14, 0, %r13, %p3;
; SM90-NEXT:    prmt.b32 %r15, %r14, %r12, 0x3340U;
; SM90-NEXT:    cvt.u32.u16 %r16, %rs4;
; SM90-NEXT:    selp.b32 %r17, 0, %r16, %p2;
; SM90-NEXT:    cvt.u32.u16 %r18, %rs2;
; SM90-NEXT:    selp.b32 %r19, 0, %r18, %p1;
; SM90-NEXT:    prmt.b32 %r20, %r19, %r17, 0x3340U;
; SM90-NEXT:    prmt.b32 %r21, %r20, %r15, 0x5410U;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r22, %r21;
; SM90-NEXT:    setp.ne.b32 %p5, %r1, %r22;
; SM90-NEXT:    mov.b32 %r22, %r1;
; SM90-NEXT:    @%p5 bra $L__BB178_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise uinc_wrap ptr  addrspace(1) %addr, <4 x i8> %val syncscope("block") acq_rel
        ret <4 x i8> %retval
}

define <8 x i8> @uinc_wrap_acq_rel_v8i8_global_cta(ptr addrspace(1) %addr, <8 x i8> %val) {
; SM90-LABEL: uinc_wrap_acq_rel_v8i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<10>;
; SM90-NEXT:    .reg .b16 %rs<25>;
; SM90-NEXT:    .reg .b32 %r<35>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [uinc_wrap_acq_rel_v8i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [uinc_wrap_acq_rel_v8i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r34}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r33, %rd2;
; SM90-NEXT:    prmt.b32 %r11, %r2, 0, 0x7770U;
; SM90-NEXT:    prmt.b32 %r12, %r2, 0, 0x7771U;
; SM90-NEXT:  $L__BB179_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd3, %r33;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r34;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    prmt.b32 %r3, %r34, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs1, %r3;
; SM90-NEXT:    add.s16 %rs2, %rs1, 1;
; SM90-NEXT:    prmt.b32 %r4, %r34, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs3, %r4;
; SM90-NEXT:    add.s16 %rs4, %rs3, 1;
; SM90-NEXT:    prmt.b32 %r5, %r34, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs5, %r5;
; SM90-NEXT:    add.s16 %rs6, %rs5, 1;
; SM90-NEXT:    prmt.b32 %r6, %r34, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs7, %r6;
; SM90-NEXT:    add.s16 %rs8, %rs7, 1;
; SM90-NEXT:    prmt.b32 %r7, %r33, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs9, %r7;
; SM90-NEXT:    add.s16 %rs10, %rs9, 1;
; SM90-NEXT:    prmt.b32 %r8, %r33, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs11, %r8;
; SM90-NEXT:    add.s16 %rs12, %rs11, 1;
; SM90-NEXT:    prmt.b32 %r9, %r33, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs13, %r9;
; SM90-NEXT:    add.s16 %rs14, %rs13, 1;
; SM90-NEXT:    prmt.b32 %r10, %r33, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs15, %r10;
; SM90-NEXT:    add.s16 %rs16, %rs15, 1;
; SM90-NEXT:    setp.ge.u32 %p1, %r3, %r11;
; SM90-NEXT:    setp.ge.u32 %p2, %r4, %r12;
; SM90-NEXT:    prmt.b32 %r13, %r2, 0, 0x7772U;
; SM90-NEXT:    setp.ge.u32 %p3, %r5, %r13;
; SM90-NEXT:    prmt.b32 %r14, %r2, 0, 0x7773U;
; SM90-NEXT:    setp.ge.u32 %p4, %r6, %r14;
; SM90-NEXT:    prmt.b32 %r15, %r1, 0, 0x7770U;
; SM90-NEXT:    setp.ge.u32 %p5, %r7, %r15;
; SM90-NEXT:    prmt.b32 %r16, %r1, 0, 0x7771U;
; SM90-NEXT:    setp.ge.u32 %p6, %r8, %r16;
; SM90-NEXT:    prmt.b32 %r17, %r1, 0, 0x7772U;
; SM90-NEXT:    setp.ge.u32 %p7, %r9, %r17;
; SM90-NEXT:    prmt.b32 %r18, %r1, 0, 0x7773U;
; SM90-NEXT:    setp.ge.u32 %p8, %r10, %r18;
; SM90-NEXT:    selp.b16 %rs17, 0, %rs16, %p8;
; SM90-NEXT:    cvt.u32.u16 %r19, %rs17;
; SM90-NEXT:    selp.b16 %rs18, 0, %rs14, %p7;
; SM90-NEXT:    cvt.u32.u16 %r20, %rs18;
; SM90-NEXT:    prmt.b32 %r21, %r20, %r19, 0x3340U;
; SM90-NEXT:    selp.b16 %rs19, 0, %rs12, %p6;
; SM90-NEXT:    cvt.u32.u16 %r22, %rs19;
; SM90-NEXT:    selp.b16 %rs20, 0, %rs10, %p5;
; SM90-NEXT:    cvt.u32.u16 %r23, %rs20;
; SM90-NEXT:    prmt.b32 %r24, %r23, %r22, 0x3340U;
; SM90-NEXT:    prmt.b32 %r25, %r24, %r21, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r25;
; SM90-NEXT:    selp.b16 %rs21, 0, %rs8, %p4;
; SM90-NEXT:    cvt.u32.u16 %r26, %rs21;
; SM90-NEXT:    selp.b16 %rs22, 0, %rs6, %p3;
; SM90-NEXT:    cvt.u32.u16 %r27, %rs22;
; SM90-NEXT:    prmt.b32 %r28, %r27, %r26, 0x3340U;
; SM90-NEXT:    selp.b16 %rs23, 0, %rs4, %p2;
; SM90-NEXT:    cvt.u32.u16 %r29, %rs23;
; SM90-NEXT:    selp.b16 %rs24, 0, %rs2, %p1;
; SM90-NEXT:    cvt.u32.u16 %r30, %rs24;
; SM90-NEXT:    prmt.b32 %r31, %r30, %r29, 0x3340U;
; SM90-NEXT:    prmt.b32 %r32, %r31, %r28, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r32;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd6, %rd10;
; SM90-NEXT:    setp.ne.b64 %p9, %rd11, %rd6;
; SM90-NEXT:    mov.b64 {_, %r34}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r33, %rd11;
; SM90-NEXT:    @%p9 bra $L__BB179_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r33, %r34};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise uinc_wrap ptr  addrspace(1) %addr, <8 x i8> %val syncscope("block") acq_rel
        ret <8 x i8> %retval
}

define <1 x i16> @uinc_wrap_acq_rel_v1i16_global_cta(ptr addrspace(1) %addr, <1 x i16> %val) {
; SM90-LABEL: uinc_wrap_acq_rel_v1i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<3>;
; SM90-NEXT:    .reg .b16 %rs<5>;
; SM90-NEXT:    .reg .b32 %r<15>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [uinc_wrap_acq_rel_v1i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b16 %rs1, [uinc_wrap_acq_rel_v1i16_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r4, %rd2;
; SM90-NEXT:    and.b32 %r5, %r4, 3;
; SM90-NEXT:    shl.b32 %r1, %r5, 3;
; SM90-NEXT:    mov.b32 %r6, 65535;
; SM90-NEXT:    shl.b32 %r7, %r6, %r1;
; SM90-NEXT:    not.b32 %r2, %r7;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r14, [%rd1];
; SM90-NEXT:  $L__BB180_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r8, %r14, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r8;
; SM90-NEXT:    add.s16 %rs3, %rs2, 1;
; SM90-NEXT:    setp.ge.u16 %p1, %rs2, %rs1;
; SM90-NEXT:    selp.b16 %rs4, 0, %rs3, %p1;
; SM90-NEXT:    cvt.u32.u16 %r9, %rs4;
; SM90-NEXT:    shl.b32 %r10, %r9, %r1;
; SM90-NEXT:    and.b32 %r11, %r14, %r2;
; SM90-NEXT:    or.b32 %r12, %r11, %r10;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r14, %r12;
; SM90-NEXT:    setp.ne.b32 %p2, %r3, %r14;
; SM90-NEXT:    mov.b32 %r14, %r3;
; SM90-NEXT:    @%p2 bra $L__BB180_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r13, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r13;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise uinc_wrap ptr  addrspace(1) %addr, <1 x i16> %val syncscope("block") acq_rel
        ret <1 x i16> %retval
}

define <2 x i16> @uinc_wrap_acq_rel_v2i16_global_cta(ptr addrspace(1) %addr, <2 x i16> %val) {
; SM90-LABEL: uinc_wrap_acq_rel_v2i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<4>;
; SM90-NEXT:    .reg .b16 %rs<9>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [uinc_wrap_acq_rel_v2i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [uinc_wrap_acq_rel_v2i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r6, [%rd1];
; SM90-NEXT:    mov.b32 {%rs1, %rs2}, %r2;
; SM90-NEXT:  $L__BB181_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    mov.b32 %r3, 65537;
; SM90-NEXT:    add.s16x2 %r4, %r6, %r3;
; SM90-NEXT:    mov.b32 {%rs3, %rs4}, %r6;
; SM90-NEXT:    setp.ge.u16 %p1, %rs3, %rs1;
; SM90-NEXT:    setp.ge.u16 %p2, %rs4, %rs2;
; SM90-NEXT:    mov.b32 {%rs5, %rs6}, %r4;
; SM90-NEXT:    selp.b16 %rs7, 0, %rs6, %p2;
; SM90-NEXT:    selp.b16 %rs8, 0, %rs5, %p1;
; SM90-NEXT:    mov.b32 %r5, {%rs8, %rs7};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r6, %r5;
; SM90-NEXT:    setp.ne.b32 %p3, %r1, %r6;
; SM90-NEXT:    mov.b32 %r6, %r1;
; SM90-NEXT:    @%p3 bra $L__BB181_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise uinc_wrap ptr  addrspace(1) %addr, <2 x i16> %val syncscope("block") acq_rel
        ret <2 x i16> %retval
}

define <4 x i16> @uinc_wrap_acq_rel_v4i16_global_cta(ptr addrspace(1) %addr, <4 x i16> %val) {
; SM90-LABEL: uinc_wrap_acq_rel_v4i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<6>;
; SM90-NEXT:    .reg .b16 %rs<17>;
; SM90-NEXT:    .reg .b32 %r<10>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [uinc_wrap_acq_rel_v4i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [uinc_wrap_acq_rel_v4i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r9}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r8, %rd2;
; SM90-NEXT:    mov.b32 {%rs1, %rs2}, %r2;
; SM90-NEXT:    mov.b32 {%rs5, %rs6}, %r1;
; SM90-NEXT:  $L__BB182_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd3, %r8;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r9;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    mov.b32 %r3, 65537;
; SM90-NEXT:    add.s16x2 %r4, %r9, %r3;
; SM90-NEXT:    add.s16x2 %r5, %r8, %r3;
; SM90-NEXT:    mov.b32 {%rs3, %rs4}, %r9;
; SM90-NEXT:    setp.ge.u16 %p1, %rs3, %rs1;
; SM90-NEXT:    setp.ge.u16 %p2, %rs4, %rs2;
; SM90-NEXT:    mov.b32 {%rs7, %rs8}, %r8;
; SM90-NEXT:    setp.ge.u16 %p3, %rs7, %rs5;
; SM90-NEXT:    setp.ge.u16 %p4, %rs8, %rs6;
; SM90-NEXT:    mov.b32 {%rs9, %rs10}, %r5;
; SM90-NEXT:    selp.b16 %rs11, 0, %rs10, %p4;
; SM90-NEXT:    selp.b16 %rs12, 0, %rs9, %p3;
; SM90-NEXT:    mov.b32 %r6, {%rs12, %rs11};
; SM90-NEXT:    cvt.u64.u32 %rd7, %r6;
; SM90-NEXT:    mov.b32 {%rs13, %rs14}, %r4;
; SM90-NEXT:    selp.b16 %rs15, 0, %rs14, %p2;
; SM90-NEXT:    selp.b16 %rs16, 0, %rs13, %p1;
; SM90-NEXT:    mov.b32 %r7, {%rs16, %rs15};
; SM90-NEXT:    cvt.u64.u32 %rd8, %r7;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd6, %rd10;
; SM90-NEXT:    setp.ne.b64 %p5, %rd11, %rd6;
; SM90-NEXT:    mov.b64 {_, %r9}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r8, %rd11;
; SM90-NEXT:    @%p5 bra $L__BB182_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r8, %r9};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise uinc_wrap ptr  addrspace(1) %addr, <4 x i16> %val syncscope("block") acq_rel
        ret <4 x i16> %retval
}

define <8 x i16> @uinc_wrap_acq_rel_v8i16_global_cta(ptr addrspace(1) %addr, <8 x i16> %val) {
; SM90-LABEL: uinc_wrap_acq_rel_v8i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<10>;
; SM90-NEXT:    .reg .b16 %rs<33>;
; SM90-NEXT:    .reg .b32 %r<18>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [uinc_wrap_acq_rel_v8i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [uinc_wrap_acq_rel_v8i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r17}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r16, %rd4;
; SM90-NEXT:    mov.b64 {_, %r15}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r14, %rd3;
; SM90-NEXT:    mov.b32 {%rs1, %rs2}, %r4;
; SM90-NEXT:    mov.b32 {%rs5, %rs6}, %r3;
; SM90-NEXT:  $L__BB183_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd5, %r14;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r15;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r16;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r17;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    mov.b32 %r5, 65537;
; SM90-NEXT:    add.s16x2 %r6, %r17, %r5;
; SM90-NEXT:    add.s16x2 %r7, %r16, %r5;
; SM90-NEXT:    add.s16x2 %r8, %r15, %r5;
; SM90-NEXT:    add.s16x2 %r9, %r14, %r5;
; SM90-NEXT:    mov.b32 {%rs3, %rs4}, %r17;
; SM90-NEXT:    setp.ge.u16 %p1, %rs3, %rs1;
; SM90-NEXT:    setp.ge.u16 %p2, %rs4, %rs2;
; SM90-NEXT:    mov.b32 {%rs7, %rs8}, %r16;
; SM90-NEXT:    setp.ge.u16 %p3, %rs7, %rs5;
; SM90-NEXT:    setp.ge.u16 %p4, %rs8, %rs6;
; SM90-NEXT:    mov.b32 {%rs9, %rs10}, %r2;
; SM90-NEXT:    mov.b32 {%rs11, %rs12}, %r15;
; SM90-NEXT:    setp.ge.u16 %p5, %rs11, %rs9;
; SM90-NEXT:    setp.ge.u16 %p6, %rs12, %rs10;
; SM90-NEXT:    mov.b32 {%rs13, %rs14}, %r1;
; SM90-NEXT:    mov.b32 {%rs15, %rs16}, %r14;
; SM90-NEXT:    setp.ge.u16 %p7, %rs15, %rs13;
; SM90-NEXT:    setp.ge.u16 %p8, %rs16, %rs14;
; SM90-NEXT:    mov.b32 {%rs17, %rs18}, %r9;
; SM90-NEXT:    selp.b16 %rs19, 0, %rs18, %p8;
; SM90-NEXT:    selp.b16 %rs20, 0, %rs17, %p7;
; SM90-NEXT:    mov.b32 %r10, {%rs20, %rs19};
; SM90-NEXT:    cvt.u64.u32 %rd13, %r10;
; SM90-NEXT:    mov.b32 {%rs21, %rs22}, %r8;
; SM90-NEXT:    selp.b16 %rs23, 0, %rs22, %p6;
; SM90-NEXT:    selp.b16 %rs24, 0, %rs21, %p5;
; SM90-NEXT:    mov.b32 %r11, {%rs24, %rs23};
; SM90-NEXT:    cvt.u64.u32 %rd14, %r11;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    mov.b32 {%rs25, %rs26}, %r7;
; SM90-NEXT:    selp.b16 %rs27, 0, %rs26, %p4;
; SM90-NEXT:    selp.b16 %rs28, 0, %rs25, %p3;
; SM90-NEXT:    mov.b32 %r12, {%rs28, %rs27};
; SM90-NEXT:    cvt.u64.u32 %rd17, %r12;
; SM90-NEXT:    mov.b32 {%rs29, %rs30}, %r6;
; SM90-NEXT:    selp.b16 %rs31, 0, %rs30, %p2;
; SM90-NEXT:    selp.b16 %rs32, 0, %rs29, %p1;
; SM90-NEXT:    mov.b32 %r13, {%rs32, %rs31};
; SM90-NEXT:    cvt.u64.u32 %rd18, %r13;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd8, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd16, %rd20};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd12;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd8;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r17}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r16, %rd22;
; SM90-NEXT:    mov.b64 {_, %r15}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r14, %rd21;
; SM90-NEXT:    setp.ne.b64 %p9, %rd25, 0;
; SM90-NEXT:    @%p9 bra $L__BB183_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r14, %r15, %r16, %r17};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise uinc_wrap ptr  addrspace(1) %addr, <8 x i16> %val syncscope("block") acq_rel
        ret <8 x i16> %retval
}

define <1 x i32> @uinc_wrap_acq_rel_v1i32_global_cta(ptr addrspace(1) %addr, <1 x i32> %val) {
; SM90-LABEL: uinc_wrap_acq_rel_v1i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<3>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [uinc_wrap_acq_rel_v1i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b32 %r1, [uinc_wrap_acq_rel_v1i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.inc.u32 %r2, [%rd1], %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise uinc_wrap ptr  addrspace(1) %addr, <1 x i32> %val syncscope("block") acq_rel
        ret <1 x i32> %retval
}

define <2 x i32> @uinc_wrap_acq_rel_v2i32_global_cta(ptr addrspace(1) %addr, <2 x i32> %val) {
; SM90-LABEL: uinc_wrap_acq_rel_v2i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [uinc_wrap_acq_rel_v2i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [uinc_wrap_acq_rel_v2i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.inc.u32 %r3, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.inc.u32 %r4, [%rd1+4], %r2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r3, %r4};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise uinc_wrap ptr  addrspace(1) %addr, <2 x i32> %val syncscope("block") acq_rel
        ret <2 x i32> %retval
}

define <4 x i32> @uinc_wrap_acq_rel_v4i32_global_cta(ptr addrspace(1) %addr, <4 x i32> %val) {
; SM90-LABEL: uinc_wrap_acq_rel_v4i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<9>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [uinc_wrap_acq_rel_v4i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [uinc_wrap_acq_rel_v4i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.inc.u32 %r5, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.inc.u32 %r6, [%rd1+4], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.inc.u32 %r7, [%rd1+8], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.inc.u32 %r8, [%rd1+12], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise uinc_wrap ptr  addrspace(1) %addr, <4 x i32> %val syncscope("block") acq_rel
        ret <4 x i32> %retval
}

define <8 x i32> @uinc_wrap_acq_rel_v8i32_global_cta(ptr addrspace(1) %addr, <8 x i32> %val) {
; SM90-LABEL: uinc_wrap_acq_rel_v8i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<17>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [uinc_wrap_acq_rel_v8i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [uinc_wrap_acq_rel_v8i32_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [uinc_wrap_acq_rel_v8i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.inc.u32 %r9, [%rd1], %r5;
; SM90-NEXT:    atom.relaxed.cta.global.inc.u32 %r10, [%rd1+4], %r6;
; SM90-NEXT:    atom.relaxed.cta.global.inc.u32 %r11, [%rd1+8], %r7;
; SM90-NEXT:    atom.relaxed.cta.global.inc.u32 %r12, [%rd1+12], %r8;
; SM90-NEXT:    atom.relaxed.cta.global.inc.u32 %r13, [%rd1+16], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.inc.u32 %r14, [%rd1+20], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.inc.u32 %r15, [%rd1+24], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.inc.u32 %r16, [%rd1+28], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r13, %r14, %r15, %r16};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise uinc_wrap ptr  addrspace(1) %addr, <8 x i32> %val syncscope("block") acq_rel
        ret <8 x i32> %retval
}

define <1 x i64> @uinc_wrap_acq_rel_v1i64_global_cta(ptr addrspace(1) %addr, <1 x i64> %val) {
; SM90-LABEL: uinc_wrap_acq_rel_v1i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<3>;
; SM90-NEXT:    .reg .b64 %rd<7>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd3, [uinc_wrap_acq_rel_v1i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b64 %rd1, [uinc_wrap_acq_rel_v1i64_global_cta_param_1];
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd6, [%rd3];
; SM90-NEXT:  $L__BB188_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    add.s64 %rd4, %rd6, 1;
; SM90-NEXT:    setp.ge.u64 %p1, %rd6, %rd1;
; SM90-NEXT:    selp.b64 %rd5, 0, %rd4, %p1;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd2, [%rd3], %rd6, %rd5;
; SM90-NEXT:    setp.ne.b64 %p2, %rd2, %rd6;
; SM90-NEXT:    mov.b64 %rd6, %rd2;
; SM90-NEXT:    @%p2 bra $L__BB188_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b64 [func_retval0], %rd2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise uinc_wrap ptr  addrspace(1) %addr, <1 x i64> %val syncscope("block") acq_rel
        ret <1 x i64> %retval
}

define <2 x i64> @uinc_wrap_acq_rel_v2i64_global_cta(ptr addrspace(1) %addr, <2 x i64> %val) {
; SM90-LABEL: uinc_wrap_acq_rel_v2i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<4>;
; SM90-NEXT:    .reg .b64 %rd<16>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [uinc_wrap_acq_rel_v2i64_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd3, [uinc_wrap_acq_rel_v2i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd6, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd6, %rd6};
; SM90-NEXT:    mov.b128 swap, {%rd6, %rd6};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd3], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd14, %rd15}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB189_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    add.s64 %rd7, %rd15, 1;
; SM90-NEXT:    add.s64 %rd8, %rd14, 1;
; SM90-NEXT:    setp.ge.u64 %p1, %rd15, %rd5;
; SM90-NEXT:    setp.ge.u64 %p2, %rd14, %rd4;
; SM90-NEXT:    selp.b64 %rd9, 0, %rd8, %p2;
; SM90-NEXT:    selp.b64 %rd10, 0, %rd7, %p1;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd14, %rd15};
; SM90-NEXT:    mov.b128 swap, {%rd9, %rd10};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd3], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd1, %rd2}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd11, %rd2, %rd15;
; SM90-NEXT:    xor.b64 %rd12, %rd1, %rd14;
; SM90-NEXT:    or.b64 %rd13, %rd12, %rd11;
; SM90-NEXT:    setp.ne.b64 %p3, %rd13, 0;
; SM90-NEXT:    mov.b64 %rd14, %rd1;
; SM90-NEXT:    mov.b64 %rd15, %rd2;
; SM90-NEXT:    @%p3 bra $L__BB189_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd1, %rd2};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise uinc_wrap ptr  addrspace(1) %addr, <2 x i64> %val syncscope("block") acq_rel
        ret <2 x i64> %retval
}

define <4 x i64> @uinc_wrap_acq_rel_v4i64_global_cta(ptr addrspace(1) %addr, <4 x i64> %val) {
; SM90-LABEL: uinc_wrap_acq_rel_v4i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<7>;
; SM90-NEXT:    .reg .b64 %rd<30>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd9, [uinc_wrap_acq_rel_v4i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [uinc_wrap_acq_rel_v4i64_global_cta_param_1];
; SM90-NEXT:    ld.param.v2.b64 {%rd3, %rd4}, [uinc_wrap_acq_rel_v4i64_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd10, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd10, %rd10};
; SM90-NEXT:    mov.b128 swap, {%rd10, %rd10};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd26, %rd27}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB190_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    add.s64 %rd11, %rd27, 1;
; SM90-NEXT:    add.s64 %rd12, %rd26, 1;
; SM90-NEXT:    setp.ge.u64 %p1, %rd27, %rd2;
; SM90-NEXT:    setp.ge.u64 %p2, %rd26, %rd1;
; SM90-NEXT:    selp.b64 %rd13, 0, %rd12, %p2;
; SM90-NEXT:    selp.b64 %rd14, 0, %rd11, %p1;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd26, %rd27};
; SM90-NEXT:    mov.b128 swap, {%rd13, %rd14};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd5, %rd6}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd15, %rd6, %rd27;
; SM90-NEXT:    xor.b64 %rd16, %rd5, %rd26;
; SM90-NEXT:    or.b64 %rd17, %rd16, %rd15;
; SM90-NEXT:    setp.ne.b64 %p3, %rd17, 0;
; SM90-NEXT:    mov.b64 %rd26, %rd5;
; SM90-NEXT:    mov.b64 %rd27, %rd6;
; SM90-NEXT:    @%p3 bra $L__BB190_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd18, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd18, %rd18};
; SM90-NEXT:    mov.b128 swap, {%rd18, %rd18};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd28, %rd29}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB190_3: // %atomicrmw.start2
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    add.s64 %rd19, %rd29, 1;
; SM90-NEXT:    add.s64 %rd20, %rd28, 1;
; SM90-NEXT:    setp.ge.u64 %p4, %rd29, %rd4;
; SM90-NEXT:    setp.ge.u64 %p5, %rd28, %rd3;
; SM90-NEXT:    selp.b64 %rd21, 0, %rd20, %p5;
; SM90-NEXT:    selp.b64 %rd22, 0, %rd19, %p4;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd28, %rd29};
; SM90-NEXT:    mov.b128 swap, {%rd21, %rd22};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd7, %rd8}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd8, %rd29;
; SM90-NEXT:    xor.b64 %rd24, %rd7, %rd28;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    setp.ne.b64 %p6, %rd25, 0;
; SM90-NEXT:    mov.b64 %rd28, %rd7;
; SM90-NEXT:    mov.b64 %rd29, %rd8;
; SM90-NEXT:    @%p6 bra $L__BB190_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end1
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd7, %rd8};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd5, %rd6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise uinc_wrap ptr  addrspace(1) %addr, <4 x i64> %val syncscope("block") acq_rel
        ret <4 x i64> %retval
}

define <8 x i64> @uinc_wrap_acq_rel_v8i64_global_cta(ptr addrspace(1) %addr, <8 x i64> %val) {
; SM90-LABEL: uinc_wrap_acq_rel_v8i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<13>;
; SM90-NEXT:    .reg .b64 %rd<58>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd17, [uinc_wrap_acq_rel_v8i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd3, %rd4}, [uinc_wrap_acq_rel_v8i64_global_cta_param_1+48];
; SM90-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [uinc_wrap_acq_rel_v8i64_global_cta_param_1+32];
; SM90-NEXT:    ld.param.v2.b64 {%rd5, %rd6}, [uinc_wrap_acq_rel_v8i64_global_cta_param_1];
; SM90-NEXT:    ld.param.v2.b64 {%rd7, %rd8}, [uinc_wrap_acq_rel_v8i64_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd18, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd18, %rd18};
; SM90-NEXT:    mov.b128 swap, {%rd18, %rd18};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd50, %rd51}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB191_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    mov.b64 %rd10, %rd51;
; SM90-NEXT:    mov.b64 %rd9, %rd50;
; SM90-NEXT:    add.s64 %rd19, %rd10, 1;
; SM90-NEXT:    add.s64 %rd20, %rd9, 1;
; SM90-NEXT:    setp.ge.u64 %p1, %rd10, %rd6;
; SM90-NEXT:    setp.ge.u64 %p2, %rd9, %rd5;
; SM90-NEXT:    selp.b64 %rd21, 0, %rd20, %p2;
; SM90-NEXT:    selp.b64 %rd22, 0, %rd19, %p1;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd9, %rd10};
; SM90-NEXT:    mov.b128 swap, {%rd21, %rd22};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd50, %rd51}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd51, %rd10;
; SM90-NEXT:    xor.b64 %rd24, %rd50, %rd9;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    setp.ne.b64 %p3, %rd25, 0;
; SM90-NEXT:    @%p3 bra $L__BB191_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd26, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd26, %rd26};
; SM90-NEXT:    mov.b128 swap, {%rd26, %rd26};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd52, %rd53}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB191_3: // %atomicrmw.start6
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    mov.b64 %rd12, %rd53;
; SM90-NEXT:    mov.b64 %rd11, %rd52;
; SM90-NEXT:    add.s64 %rd27, %rd12, 1;
; SM90-NEXT:    add.s64 %rd28, %rd11, 1;
; SM90-NEXT:    setp.ge.u64 %p4, %rd12, %rd8;
; SM90-NEXT:    setp.ge.u64 %p5, %rd11, %rd7;
; SM90-NEXT:    selp.b64 %rd29, 0, %rd28, %p5;
; SM90-NEXT:    selp.b64 %rd30, 0, %rd27, %p4;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd11, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd29, %rd30};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd52, %rd53}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd31, %rd53, %rd12;
; SM90-NEXT:    xor.b64 %rd32, %rd52, %rd11;
; SM90-NEXT:    or.b64 %rd33, %rd32, %rd31;
; SM90-NEXT:    setp.ne.b64 %p6, %rd33, 0;
; SM90-NEXT:    @%p6 bra $L__BB191_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end5
; SM90-NEXT:    mov.b64 %rd34, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd34, %rd34};
; SM90-NEXT:    mov.b128 swap, {%rd34, %rd34};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+32], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd54, %rd55}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB191_5: // %atomicrmw.start16
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    add.s64 %rd35, %rd55, 1;
; SM90-NEXT:    add.s64 %rd36, %rd54, 1;
; SM90-NEXT:    setp.ge.u64 %p7, %rd55, %rd2;
; SM90-NEXT:    setp.ge.u64 %p8, %rd54, %rd1;
; SM90-NEXT:    selp.b64 %rd37, 0, %rd36, %p8;
; SM90-NEXT:    selp.b64 %rd38, 0, %rd35, %p7;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd54, %rd55};
; SM90-NEXT:    mov.b128 swap, {%rd37, %rd38};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+32], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd13, %rd14}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd39, %rd14, %rd55;
; SM90-NEXT:    xor.b64 %rd40, %rd13, %rd54;
; SM90-NEXT:    or.b64 %rd41, %rd40, %rd39;
; SM90-NEXT:    setp.ne.b64 %p9, %rd41, 0;
; SM90-NEXT:    mov.b64 %rd54, %rd13;
; SM90-NEXT:    mov.b64 %rd55, %rd14;
; SM90-NEXT:    @%p9 bra $L__BB191_5;
; SM90-NEXT:  // %bb.6: // %atomicrmw.end15
; SM90-NEXT:    mov.b64 %rd42, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd42, %rd42};
; SM90-NEXT:    mov.b128 swap, {%rd42, %rd42};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+48], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd56, %rd57}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB191_7: // %atomicrmw.start22
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    add.s64 %rd43, %rd57, 1;
; SM90-NEXT:    add.s64 %rd44, %rd56, 1;
; SM90-NEXT:    setp.ge.u64 %p10, %rd57, %rd4;
; SM90-NEXT:    setp.ge.u64 %p11, %rd56, %rd3;
; SM90-NEXT:    selp.b64 %rd45, 0, %rd44, %p11;
; SM90-NEXT:    selp.b64 %rd46, 0, %rd43, %p10;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd56, %rd57};
; SM90-NEXT:    mov.b128 swap, {%rd45, %rd46};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+48], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd15, %rd16}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd47, %rd16, %rd57;
; SM90-NEXT:    xor.b64 %rd48, %rd15, %rd56;
; SM90-NEXT:    or.b64 %rd49, %rd48, %rd47;
; SM90-NEXT:    setp.ne.b64 %p12, %rd49, 0;
; SM90-NEXT:    mov.b64 %rd56, %rd15;
; SM90-NEXT:    mov.b64 %rd57, %rd16;
; SM90-NEXT:    @%p12 bra $L__BB191_7;
; SM90-NEXT:  // %bb.8: // %atomicrmw.end21
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+48], {%rd15, %rd16};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+32], {%rd13, %rd14};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd50, %rd51};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd52, %rd53};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise uinc_wrap ptr  addrspace(1) %addr, <8 x i64> %val syncscope("block") acq_rel
        ret <8 x i64> %retval
}

define <1 x i8> @udec_wrap_acq_rel_v1i8_global_cta(ptr addrspace(1) %addr, <1 x i8> %val) {
; SM90-LABEL: udec_wrap_acq_rel_v1i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<4>;
; SM90-NEXT:    .reg .b16 %rs<7>;
; SM90-NEXT:    .reg .b32 %r<16>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b8 %rs1, [udec_wrap_acq_rel_v1i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd2, [udec_wrap_acq_rel_v1i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r4, %rd2;
; SM90-NEXT:    and.b32 %r5, %r4, 3;
; SM90-NEXT:    shl.b32 %r1, %r5, 3;
; SM90-NEXT:    mov.b32 %r6, 255;
; SM90-NEXT:    shl.b32 %r7, %r6, %r1;
; SM90-NEXT:    not.b32 %r2, %r7;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r15, [%rd1];
; SM90-NEXT:  $L__BB192_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r8, %r15, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r8;
; SM90-NEXT:    and.b16 %rs3, %rs2, 255;
; SM90-NEXT:    add.s16 %rs4, %rs2, -1;
; SM90-NEXT:    setp.eq.b16 %p1, %rs3, 0;
; SM90-NEXT:    setp.gt.u16 %p2, %rs3, %rs1;
; SM90-NEXT:    selp.b16 %rs5, %rs1, %rs4, %p2;
; SM90-NEXT:    selp.b16 %rs6, %rs1, %rs5, %p1;
; SM90-NEXT:    cvt.u32.u16 %r9, %rs6;
; SM90-NEXT:    and.b32 %r10, %r9, 255;
; SM90-NEXT:    shl.b32 %r11, %r10, %r1;
; SM90-NEXT:    and.b32 %r12, %r15, %r2;
; SM90-NEXT:    or.b32 %r13, %r12, %r11;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r15, %r13;
; SM90-NEXT:    setp.ne.b32 %p3, %r3, %r15;
; SM90-NEXT:    mov.b32 %r15, %r3;
; SM90-NEXT:    @%p3 bra $L__BB192_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r14, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b8 [func_retval0], %r14;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise udec_wrap ptr  addrspace(1) %addr, <1 x i8> %val syncscope("block") acq_rel
        ret <1 x i8> %retval
}

define <2 x i8> @udec_wrap_acq_rel_v2i8_global_cta(ptr addrspace(1) %addr, <2 x i8> %val) {
; SM90-LABEL: udec_wrap_acq_rel_v2i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<6>;
; SM90-NEXT:    .reg .b16 %rs<17>;
; SM90-NEXT:    .reg .b32 %r<16>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b8 {%rs1, %rs2}, [udec_wrap_acq_rel_v2i8_global_cta_param_1];
; SM90-NEXT:    mov.b32 %r4, {%rs1, %rs2};
; SM90-NEXT:    ld.param.b64 %rd2, [udec_wrap_acq_rel_v2i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:    and.b32 %r6, %r5, 3;
; SM90-NEXT:    shl.b32 %r1, %r6, 3;
; SM90-NEXT:    mov.b32 %r7, 65535;
; SM90-NEXT:    shl.b32 %r8, %r7, %r1;
; SM90-NEXT:    not.b32 %r2, %r8;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r15, [%rd1];
; SM90-NEXT:    mov.b32 {%rs8, %rs9}, %r4;
; SM90-NEXT:  $L__BB193_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r9, %r15, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs3, %r9;
; SM90-NEXT:    and.b16 %rs4, %rs3, 255;
; SM90-NEXT:    shr.u16 %rs5, %rs3, 8;
; SM90-NEXT:    add.s16 %rs6, %rs5, -1;
; SM90-NEXT:    add.s16 %rs7, %rs3, -1;
; SM90-NEXT:    setp.eq.b16 %p1, %rs5, 0;
; SM90-NEXT:    setp.eq.b16 %p2, %rs4, 0;
; SM90-NEXT:    setp.gt.u16 %p3, %rs5, %rs9;
; SM90-NEXT:    setp.gt.u16 %p4, %rs4, %rs8;
; SM90-NEXT:    selp.b16 %rs10, %rs8, %rs7, %p4;
; SM90-NEXT:    selp.b16 %rs11, %rs8, %rs10, %p2;
; SM90-NEXT:    selp.b16 %rs12, %rs9, %rs6, %p3;
; SM90-NEXT:    selp.b16 %rs13, %rs9, %rs12, %p1;
; SM90-NEXT:    shl.b16 %rs14, %rs13, 8;
; SM90-NEXT:    and.b16 %rs15, %rs11, 255;
; SM90-NEXT:    or.b16 %rs16, %rs15, %rs14;
; SM90-NEXT:    cvt.u32.u16 %r10, %rs16;
; SM90-NEXT:    shl.b32 %r11, %r10, %r1;
; SM90-NEXT:    and.b32 %r12, %r15, %r2;
; SM90-NEXT:    or.b32 %r13, %r12, %r11;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r15, %r13;
; SM90-NEXT:    setp.ne.b32 %p5, %r3, %r15;
; SM90-NEXT:    mov.b32 %r15, %r3;
; SM90-NEXT:    @%p5 bra $L__BB193_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r14, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r14;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise udec_wrap ptr  addrspace(1) %addr, <2 x i8> %val syncscope("block") acq_rel
        ret <2 x i8> %retval
}

define <4 x i8> @udec_wrap_acq_rel_v4i8_global_cta(ptr addrspace(1) %addr, <4 x i8> %val) {
; SM90-LABEL: udec_wrap_acq_rel_v4i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<10>;
; SM90-NEXT:    .reg .b16 %rs<9>;
; SM90-NEXT:    .reg .b32 %r<27>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [udec_wrap_acq_rel_v4i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [udec_wrap_acq_rel_v4i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r26, [%rd1];
; SM90-NEXT:    prmt.b32 %r7, %r2, 0, 0x7770U;
; SM90-NEXT:    prmt.b32 %r8, %r2, 0, 0x7771U;
; SM90-NEXT:    prmt.b32 %r9, %r2, 0, 0x7772U;
; SM90-NEXT:    prmt.b32 %r10, %r2, 0, 0x7773U;
; SM90-NEXT:  $L__BB194_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    prmt.b32 %r3, %r26, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs1, %r3;
; SM90-NEXT:    add.s16 %rs2, %rs1, -1;
; SM90-NEXT:    prmt.b32 %r4, %r26, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs3, %r4;
; SM90-NEXT:    add.s16 %rs4, %rs3, -1;
; SM90-NEXT:    prmt.b32 %r5, %r26, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs5, %r5;
; SM90-NEXT:    add.s16 %rs6, %rs5, -1;
; SM90-NEXT:    prmt.b32 %r6, %r26, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs7, %r6;
; SM90-NEXT:    add.s16 %rs8, %rs7, -1;
; SM90-NEXT:    setp.eq.b32 %p1, %r3, 0;
; SM90-NEXT:    setp.eq.b32 %p2, %r4, 0;
; SM90-NEXT:    setp.eq.b32 %p3, %r5, 0;
; SM90-NEXT:    setp.eq.b32 %p4, %r6, 0;
; SM90-NEXT:    setp.gt.u32 %p5, %r3, %r7;
; SM90-NEXT:    setp.gt.u32 %p6, %r4, %r8;
; SM90-NEXT:    setp.gt.u32 %p7, %r5, %r9;
; SM90-NEXT:    setp.gt.u32 %p8, %r6, %r10;
; SM90-NEXT:    cvt.u32.u16 %r11, %rs8;
; SM90-NEXT:    selp.b32 %r12, %r10, %r11, %p8;
; SM90-NEXT:    selp.b32 %r13, %r10, %r12, %p4;
; SM90-NEXT:    cvt.u32.u16 %r14, %rs6;
; SM90-NEXT:    selp.b32 %r15, %r9, %r14, %p7;
; SM90-NEXT:    selp.b32 %r16, %r9, %r15, %p3;
; SM90-NEXT:    prmt.b32 %r17, %r16, %r13, 0x3340U;
; SM90-NEXT:    cvt.u32.u16 %r18, %rs4;
; SM90-NEXT:    selp.b32 %r19, %r8, %r18, %p6;
; SM90-NEXT:    selp.b32 %r20, %r8, %r19, %p2;
; SM90-NEXT:    cvt.u32.u16 %r21, %rs2;
; SM90-NEXT:    selp.b32 %r22, %r7, %r21, %p5;
; SM90-NEXT:    selp.b32 %r23, %r7, %r22, %p1;
; SM90-NEXT:    prmt.b32 %r24, %r23, %r20, 0x3340U;
; SM90-NEXT:    prmt.b32 %r25, %r24, %r17, 0x5410U;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r26, %r25;
; SM90-NEXT:    setp.ne.b32 %p9, %r1, %r26;
; SM90-NEXT:    mov.b32 %r26, %r1;
; SM90-NEXT:    @%p9 bra $L__BB194_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise udec_wrap ptr  addrspace(1) %addr, <4 x i8> %val syncscope("block") acq_rel
        ret <4 x i8> %retval
}

define <8 x i8> @udec_wrap_acq_rel_v8i8_global_cta(ptr addrspace(1) %addr, <8 x i8> %val) {
; SM90-LABEL: udec_wrap_acq_rel_v8i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<18>;
; SM90-NEXT:    .reg .b16 %rs<41>;
; SM90-NEXT:    .reg .b32 %r<35>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [udec_wrap_acq_rel_v8i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [udec_wrap_acq_rel_v8i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r34}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r33, %rd2;
; SM90-NEXT:    prmt.b32 %r11, %r2, 0, 0x7770U;
; SM90-NEXT:    prmt.b32 %r12, %r2, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs17, %r11;
; SM90-NEXT:    cvt.u16.u32 %rs18, %r12;
; SM90-NEXT:  $L__BB195_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd3, %r33;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r34;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    prmt.b32 %r3, %r34, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs1, %r3;
; SM90-NEXT:    add.s16 %rs2, %rs1, -1;
; SM90-NEXT:    prmt.b32 %r4, %r34, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs3, %r4;
; SM90-NEXT:    add.s16 %rs4, %rs3, -1;
; SM90-NEXT:    prmt.b32 %r5, %r34, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs5, %r5;
; SM90-NEXT:    add.s16 %rs6, %rs5, -1;
; SM90-NEXT:    prmt.b32 %r6, %r34, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs7, %r6;
; SM90-NEXT:    add.s16 %rs8, %rs7, -1;
; SM90-NEXT:    prmt.b32 %r7, %r33, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs9, %r7;
; SM90-NEXT:    add.s16 %rs10, %rs9, -1;
; SM90-NEXT:    prmt.b32 %r8, %r33, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs11, %r8;
; SM90-NEXT:    add.s16 %rs12, %rs11, -1;
; SM90-NEXT:    prmt.b32 %r9, %r33, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs13, %r9;
; SM90-NEXT:    add.s16 %rs14, %rs13, -1;
; SM90-NEXT:    prmt.b32 %r10, %r33, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs15, %r10;
; SM90-NEXT:    add.s16 %rs16, %rs15, -1;
; SM90-NEXT:    setp.eq.b32 %p1, %r3, 0;
; SM90-NEXT:    setp.eq.b32 %p2, %r4, 0;
; SM90-NEXT:    setp.eq.b32 %p3, %r5, 0;
; SM90-NEXT:    setp.eq.b32 %p4, %r6, 0;
; SM90-NEXT:    setp.eq.b32 %p5, %r7, 0;
; SM90-NEXT:    setp.eq.b32 %p6, %r8, 0;
; SM90-NEXT:    setp.eq.b32 %p7, %r9, 0;
; SM90-NEXT:    setp.eq.b32 %p8, %r10, 0;
; SM90-NEXT:    setp.gt.u32 %p9, %r3, %r11;
; SM90-NEXT:    setp.gt.u32 %p10, %r4, %r12;
; SM90-NEXT:    prmt.b32 %r13, %r2, 0, 0x7772U;
; SM90-NEXT:    setp.gt.u32 %p11, %r5, %r13;
; SM90-NEXT:    prmt.b32 %r14, %r2, 0, 0x7773U;
; SM90-NEXT:    setp.gt.u32 %p12, %r6, %r14;
; SM90-NEXT:    prmt.b32 %r15, %r1, 0, 0x7770U;
; SM90-NEXT:    setp.gt.u32 %p13, %r7, %r15;
; SM90-NEXT:    prmt.b32 %r16, %r1, 0, 0x7771U;
; SM90-NEXT:    setp.gt.u32 %p14, %r8, %r16;
; SM90-NEXT:    prmt.b32 %r17, %r1, 0, 0x7772U;
; SM90-NEXT:    setp.gt.u32 %p15, %r9, %r17;
; SM90-NEXT:    prmt.b32 %r18, %r1, 0, 0x7773U;
; SM90-NEXT:    setp.gt.u32 %p16, %r10, %r18;
; SM90-NEXT:    cvt.u16.u32 %rs19, %r13;
; SM90-NEXT:    cvt.u16.u32 %rs20, %r14;
; SM90-NEXT:    cvt.u16.u32 %rs21, %r15;
; SM90-NEXT:    cvt.u16.u32 %rs22, %r16;
; SM90-NEXT:    cvt.u16.u32 %rs23, %r17;
; SM90-NEXT:    cvt.u16.u32 %rs24, %r18;
; SM90-NEXT:    selp.b16 %rs25, %rs24, %rs16, %p16;
; SM90-NEXT:    selp.b16 %rs26, %rs24, %rs25, %p8;
; SM90-NEXT:    cvt.u32.u16 %r19, %rs26;
; SM90-NEXT:    selp.b16 %rs27, %rs23, %rs14, %p15;
; SM90-NEXT:    selp.b16 %rs28, %rs23, %rs27, %p7;
; SM90-NEXT:    cvt.u32.u16 %r20, %rs28;
; SM90-NEXT:    prmt.b32 %r21, %r20, %r19, 0x3340U;
; SM90-NEXT:    selp.b16 %rs29, %rs22, %rs12, %p14;
; SM90-NEXT:    selp.b16 %rs30, %rs22, %rs29, %p6;
; SM90-NEXT:    cvt.u32.u16 %r22, %rs30;
; SM90-NEXT:    selp.b16 %rs31, %rs21, %rs10, %p13;
; SM90-NEXT:    selp.b16 %rs32, %rs21, %rs31, %p5;
; SM90-NEXT:    cvt.u32.u16 %r23, %rs32;
; SM90-NEXT:    prmt.b32 %r24, %r23, %r22, 0x3340U;
; SM90-NEXT:    prmt.b32 %r25, %r24, %r21, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r25;
; SM90-NEXT:    selp.b16 %rs33, %rs20, %rs8, %p12;
; SM90-NEXT:    selp.b16 %rs34, %rs20, %rs33, %p4;
; SM90-NEXT:    cvt.u32.u16 %r26, %rs34;
; SM90-NEXT:    selp.b16 %rs35, %rs19, %rs6, %p11;
; SM90-NEXT:    selp.b16 %rs36, %rs19, %rs35, %p3;
; SM90-NEXT:    cvt.u32.u16 %r27, %rs36;
; SM90-NEXT:    prmt.b32 %r28, %r27, %r26, 0x3340U;
; SM90-NEXT:    selp.b16 %rs37, %rs18, %rs4, %p10;
; SM90-NEXT:    selp.b16 %rs38, %rs18, %rs37, %p2;
; SM90-NEXT:    cvt.u32.u16 %r29, %rs38;
; SM90-NEXT:    selp.b16 %rs39, %rs17, %rs2, %p9;
; SM90-NEXT:    selp.b16 %rs40, %rs17, %rs39, %p1;
; SM90-NEXT:    cvt.u32.u16 %r30, %rs40;
; SM90-NEXT:    prmt.b32 %r31, %r30, %r29, 0x3340U;
; SM90-NEXT:    prmt.b32 %r32, %r31, %r28, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r32;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd6, %rd10;
; SM90-NEXT:    setp.ne.b64 %p17, %rd11, %rd6;
; SM90-NEXT:    mov.b64 {_, %r34}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r33, %rd11;
; SM90-NEXT:    @%p17 bra $L__BB195_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r33, %r34};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise udec_wrap ptr  addrspace(1) %addr, <8 x i8> %val syncscope("block") acq_rel
        ret <8 x i8> %retval
}

define <1 x i16> @udec_wrap_acq_rel_v1i16_global_cta(ptr addrspace(1) %addr, <1 x i16> %val) {
; SM90-LABEL: udec_wrap_acq_rel_v1i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<4>;
; SM90-NEXT:    .reg .b16 %rs<6>;
; SM90-NEXT:    .reg .b32 %r<15>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [udec_wrap_acq_rel_v1i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b16 %rs1, [udec_wrap_acq_rel_v1i16_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r4, %rd2;
; SM90-NEXT:    and.b32 %r5, %r4, 3;
; SM90-NEXT:    shl.b32 %r1, %r5, 3;
; SM90-NEXT:    mov.b32 %r6, 65535;
; SM90-NEXT:    shl.b32 %r7, %r6, %r1;
; SM90-NEXT:    not.b32 %r2, %r7;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r14, [%rd1];
; SM90-NEXT:  $L__BB196_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r8, %r14, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r8;
; SM90-NEXT:    add.s16 %rs3, %rs2, -1;
; SM90-NEXT:    setp.eq.b16 %p1, %rs2, 0;
; SM90-NEXT:    setp.gt.u16 %p2, %rs2, %rs1;
; SM90-NEXT:    selp.b16 %rs4, %rs1, %rs3, %p2;
; SM90-NEXT:    selp.b16 %rs5, %rs1, %rs4, %p1;
; SM90-NEXT:    cvt.u32.u16 %r9, %rs5;
; SM90-NEXT:    shl.b32 %r10, %r9, %r1;
; SM90-NEXT:    and.b32 %r11, %r14, %r2;
; SM90-NEXT:    or.b32 %r12, %r11, %r10;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r14, %r12;
; SM90-NEXT:    setp.ne.b32 %p3, %r3, %r14;
; SM90-NEXT:    mov.b32 %r14, %r3;
; SM90-NEXT:    @%p3 bra $L__BB196_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r13, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r13;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise udec_wrap ptr  addrspace(1) %addr, <1 x i16> %val syncscope("block") acq_rel
        ret <1 x i16> %retval
}

define <2 x i16> @udec_wrap_acq_rel_v2i16_global_cta(ptr addrspace(1) %addr, <2 x i16> %val) {
; SM90-LABEL: udec_wrap_acq_rel_v2i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<6>;
; SM90-NEXT:    .reg .b16 %rs<11>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [udec_wrap_acq_rel_v2i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [udec_wrap_acq_rel_v2i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:    mov.b32 {%rs5, %rs6}, %r2;
; SM90-NEXT:  $L__BB197_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    mov.b32 {%rs1, %rs2}, %r4;
; SM90-NEXT:    add.s16 %rs3, %rs1, -1;
; SM90-NEXT:    add.s16 %rs4, %rs2, -1;
; SM90-NEXT:    setp.eq.b16 %p1, %rs1, 0;
; SM90-NEXT:    setp.eq.b16 %p2, %rs2, 0;
; SM90-NEXT:    setp.gt.u16 %p3, %rs1, %rs5;
; SM90-NEXT:    setp.gt.u16 %p4, %rs2, %rs6;
; SM90-NEXT:    selp.b16 %rs7, %rs6, %rs4, %p4;
; SM90-NEXT:    selp.b16 %rs8, %rs6, %rs7, %p2;
; SM90-NEXT:    selp.b16 %rs9, %rs5, %rs3, %p3;
; SM90-NEXT:    selp.b16 %rs10, %rs5, %rs9, %p1;
; SM90-NEXT:    mov.b32 %r3, {%rs10, %rs8};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p5, %r1, %r4;
; SM90-NEXT:    mov.b32 %r4, %r1;
; SM90-NEXT:    @%p5 bra $L__BB197_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise udec_wrap ptr  addrspace(1) %addr, <2 x i16> %val syncscope("block") acq_rel
        ret <2 x i16> %retval
}

define <4 x i16> @udec_wrap_acq_rel_v4i16_global_cta(ptr addrspace(1) %addr, <4 x i16> %val) {
; SM90-LABEL: udec_wrap_acq_rel_v4i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<10>;
; SM90-NEXT:    .reg .b16 %rs<21>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [udec_wrap_acq_rel_v4i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [udec_wrap_acq_rel_v4i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:    mov.b32 {%rs9, %rs10}, %r2;
; SM90-NEXT:    mov.b32 {%rs11, %rs12}, %r1;
; SM90-NEXT:  $L__BB198_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd3, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r6;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    mov.b32 {%rs1, %rs2}, %r6;
; SM90-NEXT:    add.s16 %rs3, %rs1, -1;
; SM90-NEXT:    add.s16 %rs4, %rs2, -1;
; SM90-NEXT:    mov.b32 {%rs5, %rs6}, %r5;
; SM90-NEXT:    add.s16 %rs7, %rs5, -1;
; SM90-NEXT:    add.s16 %rs8, %rs6, -1;
; SM90-NEXT:    setp.eq.b16 %p1, %rs1, 0;
; SM90-NEXT:    setp.eq.b16 %p2, %rs2, 0;
; SM90-NEXT:    setp.eq.b16 %p3, %rs5, 0;
; SM90-NEXT:    setp.eq.b16 %p4, %rs6, 0;
; SM90-NEXT:    setp.gt.u16 %p5, %rs1, %rs9;
; SM90-NEXT:    setp.gt.u16 %p6, %rs2, %rs10;
; SM90-NEXT:    setp.gt.u16 %p7, %rs5, %rs11;
; SM90-NEXT:    setp.gt.u16 %p8, %rs6, %rs12;
; SM90-NEXT:    selp.b16 %rs13, %rs12, %rs8, %p8;
; SM90-NEXT:    selp.b16 %rs14, %rs12, %rs13, %p4;
; SM90-NEXT:    selp.b16 %rs15, %rs11, %rs7, %p7;
; SM90-NEXT:    selp.b16 %rs16, %rs11, %rs15, %p3;
; SM90-NEXT:    mov.b32 %r3, {%rs16, %rs14};
; SM90-NEXT:    cvt.u64.u32 %rd7, %r3;
; SM90-NEXT:    selp.b16 %rs17, %rs10, %rs4, %p6;
; SM90-NEXT:    selp.b16 %rs18, %rs10, %rs17, %p2;
; SM90-NEXT:    selp.b16 %rs19, %rs9, %rs3, %p5;
; SM90-NEXT:    selp.b16 %rs20, %rs9, %rs19, %p1;
; SM90-NEXT:    mov.b32 %r4, {%rs20, %rs18};
; SM90-NEXT:    cvt.u64.u32 %rd8, %r4;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd6, %rd10;
; SM90-NEXT:    setp.ne.b64 %p9, %rd11, %rd6;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p9 bra $L__BB198_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise udec_wrap ptr  addrspace(1) %addr, <4 x i16> %val syncscope("block") acq_rel
        ret <4 x i16> %retval
}

define <8 x i16> @udec_wrap_acq_rel_v8i16_global_cta(ptr addrspace(1) %addr, <8 x i16> %val) {
; SM90-LABEL: udec_wrap_acq_rel_v8i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<18>;
; SM90-NEXT:    .reg .b16 %rs<41>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [udec_wrap_acq_rel_v8i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [udec_wrap_acq_rel_v8i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:    mov.b32 {%rs17, %rs18}, %r4;
; SM90-NEXT:    mov.b32 {%rs19, %rs20}, %r3;
; SM90-NEXT:  $L__BB199_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd5, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r10;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r12;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    mov.b32 {%rs1, %rs2}, %r12;
; SM90-NEXT:    add.s16 %rs3, %rs1, -1;
; SM90-NEXT:    add.s16 %rs4, %rs2, -1;
; SM90-NEXT:    mov.b32 {%rs5, %rs6}, %r11;
; SM90-NEXT:    add.s16 %rs7, %rs5, -1;
; SM90-NEXT:    add.s16 %rs8, %rs6, -1;
; SM90-NEXT:    mov.b32 {%rs9, %rs10}, %r10;
; SM90-NEXT:    add.s16 %rs11, %rs9, -1;
; SM90-NEXT:    add.s16 %rs12, %rs10, -1;
; SM90-NEXT:    mov.b32 {%rs13, %rs14}, %r9;
; SM90-NEXT:    add.s16 %rs15, %rs13, -1;
; SM90-NEXT:    add.s16 %rs16, %rs14, -1;
; SM90-NEXT:    setp.eq.b16 %p1, %rs1, 0;
; SM90-NEXT:    setp.eq.b16 %p2, %rs2, 0;
; SM90-NEXT:    setp.eq.b16 %p3, %rs5, 0;
; SM90-NEXT:    setp.eq.b16 %p4, %rs6, 0;
; SM90-NEXT:    setp.eq.b16 %p5, %rs9, 0;
; SM90-NEXT:    setp.eq.b16 %p6, %rs10, 0;
; SM90-NEXT:    setp.eq.b16 %p7, %rs13, 0;
; SM90-NEXT:    setp.eq.b16 %p8, %rs14, 0;
; SM90-NEXT:    setp.gt.u16 %p9, %rs1, %rs17;
; SM90-NEXT:    setp.gt.u16 %p10, %rs2, %rs18;
; SM90-NEXT:    setp.gt.u16 %p11, %rs5, %rs19;
; SM90-NEXT:    setp.gt.u16 %p12, %rs6, %rs20;
; SM90-NEXT:    mov.b32 {%rs21, %rs22}, %r2;
; SM90-NEXT:    setp.gt.u16 %p13, %rs9, %rs21;
; SM90-NEXT:    setp.gt.u16 %p14, %rs10, %rs22;
; SM90-NEXT:    mov.b32 {%rs23, %rs24}, %r1;
; SM90-NEXT:    setp.gt.u16 %p15, %rs13, %rs23;
; SM90-NEXT:    setp.gt.u16 %p16, %rs14, %rs24;
; SM90-NEXT:    selp.b16 %rs25, %rs24, %rs16, %p16;
; SM90-NEXT:    selp.b16 %rs26, %rs24, %rs25, %p8;
; SM90-NEXT:    selp.b16 %rs27, %rs23, %rs15, %p15;
; SM90-NEXT:    selp.b16 %rs28, %rs23, %rs27, %p7;
; SM90-NEXT:    mov.b32 %r5, {%rs28, %rs26};
; SM90-NEXT:    cvt.u64.u32 %rd13, %r5;
; SM90-NEXT:    selp.b16 %rs29, %rs22, %rs12, %p14;
; SM90-NEXT:    selp.b16 %rs30, %rs22, %rs29, %p6;
; SM90-NEXT:    selp.b16 %rs31, %rs21, %rs11, %p13;
; SM90-NEXT:    selp.b16 %rs32, %rs21, %rs31, %p5;
; SM90-NEXT:    mov.b32 %r6, {%rs32, %rs30};
; SM90-NEXT:    cvt.u64.u32 %rd14, %r6;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    selp.b16 %rs33, %rs20, %rs8, %p12;
; SM90-NEXT:    selp.b16 %rs34, %rs20, %rs33, %p4;
; SM90-NEXT:    selp.b16 %rs35, %rs19, %rs7, %p11;
; SM90-NEXT:    selp.b16 %rs36, %rs19, %rs35, %p3;
; SM90-NEXT:    mov.b32 %r7, {%rs36, %rs34};
; SM90-NEXT:    cvt.u64.u32 %rd17, %r7;
; SM90-NEXT:    selp.b16 %rs37, %rs18, %rs4, %p10;
; SM90-NEXT:    selp.b16 %rs38, %rs18, %rs37, %p2;
; SM90-NEXT:    selp.b16 %rs39, %rs17, %rs3, %p9;
; SM90-NEXT:    selp.b16 %rs40, %rs17, %rs39, %p1;
; SM90-NEXT:    mov.b32 %r8, {%rs40, %rs38};
; SM90-NEXT:    cvt.u64.u32 %rd18, %r8;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd8, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd16, %rd20};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd12;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd8;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd22;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd21;
; SM90-NEXT:    setp.ne.b64 %p17, %rd25, 0;
; SM90-NEXT:    @%p17 bra $L__BB199_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise udec_wrap ptr  addrspace(1) %addr, <8 x i16> %val syncscope("block") acq_rel
        ret <8 x i16> %retval
}

define <1 x i32> @udec_wrap_acq_rel_v1i32_global_cta(ptr addrspace(1) %addr, <1 x i32> %val) {
; SM90-LABEL: udec_wrap_acq_rel_v1i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<3>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [udec_wrap_acq_rel_v1i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b32 %r1, [udec_wrap_acq_rel_v1i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.dec.u32 %r2, [%rd1], %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise udec_wrap ptr  addrspace(1) %addr, <1 x i32> %val syncscope("block") acq_rel
        ret <1 x i32> %retval
}

define <2 x i32> @udec_wrap_acq_rel_v2i32_global_cta(ptr addrspace(1) %addr, <2 x i32> %val) {
; SM90-LABEL: udec_wrap_acq_rel_v2i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [udec_wrap_acq_rel_v2i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [udec_wrap_acq_rel_v2i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.dec.u32 %r3, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.dec.u32 %r4, [%rd1+4], %r2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r3, %r4};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise udec_wrap ptr  addrspace(1) %addr, <2 x i32> %val syncscope("block") acq_rel
        ret <2 x i32> %retval
}

define <4 x i32> @udec_wrap_acq_rel_v4i32_global_cta(ptr addrspace(1) %addr, <4 x i32> %val) {
; SM90-LABEL: udec_wrap_acq_rel_v4i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<9>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [udec_wrap_acq_rel_v4i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [udec_wrap_acq_rel_v4i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.dec.u32 %r5, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.dec.u32 %r6, [%rd1+4], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.dec.u32 %r7, [%rd1+8], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.dec.u32 %r8, [%rd1+12], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise udec_wrap ptr  addrspace(1) %addr, <4 x i32> %val syncscope("block") acq_rel
        ret <4 x i32> %retval
}

define <8 x i32> @udec_wrap_acq_rel_v8i32_global_cta(ptr addrspace(1) %addr, <8 x i32> %val) {
; SM90-LABEL: udec_wrap_acq_rel_v8i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<17>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [udec_wrap_acq_rel_v8i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [udec_wrap_acq_rel_v8i32_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [udec_wrap_acq_rel_v8i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.dec.u32 %r9, [%rd1], %r5;
; SM90-NEXT:    atom.relaxed.cta.global.dec.u32 %r10, [%rd1+4], %r6;
; SM90-NEXT:    atom.relaxed.cta.global.dec.u32 %r11, [%rd1+8], %r7;
; SM90-NEXT:    atom.relaxed.cta.global.dec.u32 %r12, [%rd1+12], %r8;
; SM90-NEXT:    atom.relaxed.cta.global.dec.u32 %r13, [%rd1+16], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.dec.u32 %r14, [%rd1+20], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.dec.u32 %r15, [%rd1+24], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.dec.u32 %r16, [%rd1+28], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r13, %r14, %r15, %r16};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise udec_wrap ptr  addrspace(1) %addr, <8 x i32> %val syncscope("block") acq_rel
        ret <8 x i32> %retval
}

define <1 x i64> @udec_wrap_acq_rel_v1i64_global_cta(ptr addrspace(1) %addr, <1 x i64> %val) {
; SM90-LABEL: udec_wrap_acq_rel_v1i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<4>;
; SM90-NEXT:    .reg .b64 %rd<8>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd3, [udec_wrap_acq_rel_v1i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b64 %rd1, [udec_wrap_acq_rel_v1i64_global_cta_param_1];
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd7, [%rd3];
; SM90-NEXT:  $L__BB204_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    add.s64 %rd4, %rd7, -1;
; SM90-NEXT:    setp.eq.b64 %p1, %rd7, 0;
; SM90-NEXT:    setp.gt.u64 %p2, %rd7, %rd1;
; SM90-NEXT:    selp.b64 %rd5, %rd1, %rd4, %p2;
; SM90-NEXT:    selp.b64 %rd6, %rd1, %rd5, %p1;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd2, [%rd3], %rd7, %rd6;
; SM90-NEXT:    setp.ne.b64 %p3, %rd2, %rd7;
; SM90-NEXT:    mov.b64 %rd7, %rd2;
; SM90-NEXT:    @%p3 bra $L__BB204_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b64 [func_retval0], %rd2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise udec_wrap ptr  addrspace(1) %addr, <1 x i64> %val syncscope("block") acq_rel
        ret <1 x i64> %retval
}

define <2 x i64> @udec_wrap_acq_rel_v2i64_global_cta(ptr addrspace(1) %addr, <2 x i64> %val) {
; SM90-LABEL: udec_wrap_acq_rel_v2i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<6>;
; SM90-NEXT:    .reg .b64 %rd<18>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [udec_wrap_acq_rel_v2i64_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd3, [udec_wrap_acq_rel_v2i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd6, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd6, %rd6};
; SM90-NEXT:    mov.b128 swap, {%rd6, %rd6};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd3], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd16, %rd17}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB205_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    add.s64 %rd7, %rd17, -1;
; SM90-NEXT:    add.s64 %rd8, %rd16, -1;
; SM90-NEXT:    setp.eq.b64 %p1, %rd17, 0;
; SM90-NEXT:    setp.eq.b64 %p2, %rd16, 0;
; SM90-NEXT:    setp.gt.u64 %p3, %rd17, %rd5;
; SM90-NEXT:    setp.gt.u64 %p4, %rd16, %rd4;
; SM90-NEXT:    selp.b64 %rd9, %rd4, %rd8, %p4;
; SM90-NEXT:    selp.b64 %rd10, %rd4, %rd9, %p2;
; SM90-NEXT:    selp.b64 %rd11, %rd5, %rd7, %p3;
; SM90-NEXT:    selp.b64 %rd12, %rd5, %rd11, %p1;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd17};
; SM90-NEXT:    mov.b128 swap, {%rd10, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd3], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd1, %rd2}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd13, %rd2, %rd17;
; SM90-NEXT:    xor.b64 %rd14, %rd1, %rd16;
; SM90-NEXT:    or.b64 %rd15, %rd14, %rd13;
; SM90-NEXT:    setp.ne.b64 %p5, %rd15, 0;
; SM90-NEXT:    mov.b64 %rd16, %rd1;
; SM90-NEXT:    mov.b64 %rd17, %rd2;
; SM90-NEXT:    @%p5 bra $L__BB205_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd1, %rd2};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise udec_wrap ptr  addrspace(1) %addr, <2 x i64> %val syncscope("block") acq_rel
        ret <2 x i64> %retval
}

define <4 x i64> @udec_wrap_acq_rel_v4i64_global_cta(ptr addrspace(1) %addr, <4 x i64> %val) {
; SM90-LABEL: udec_wrap_acq_rel_v4i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<11>;
; SM90-NEXT:    .reg .b64 %rd<34>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd9, [udec_wrap_acq_rel_v4i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [udec_wrap_acq_rel_v4i64_global_cta_param_1];
; SM90-NEXT:    ld.param.v2.b64 {%rd3, %rd4}, [udec_wrap_acq_rel_v4i64_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd10, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd10, %rd10};
; SM90-NEXT:    mov.b128 swap, {%rd10, %rd10};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd30, %rd31}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB206_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    add.s64 %rd11, %rd31, -1;
; SM90-NEXT:    add.s64 %rd12, %rd30, -1;
; SM90-NEXT:    setp.eq.b64 %p1, %rd31, 0;
; SM90-NEXT:    setp.eq.b64 %p2, %rd30, 0;
; SM90-NEXT:    setp.gt.u64 %p3, %rd31, %rd2;
; SM90-NEXT:    setp.gt.u64 %p4, %rd30, %rd1;
; SM90-NEXT:    selp.b64 %rd13, %rd1, %rd12, %p4;
; SM90-NEXT:    selp.b64 %rd14, %rd1, %rd13, %p2;
; SM90-NEXT:    selp.b64 %rd15, %rd2, %rd11, %p3;
; SM90-NEXT:    selp.b64 %rd16, %rd2, %rd15, %p1;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd30, %rd31};
; SM90-NEXT:    mov.b128 swap, {%rd14, %rd16};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd5, %rd6}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd17, %rd6, %rd31;
; SM90-NEXT:    xor.b64 %rd18, %rd5, %rd30;
; SM90-NEXT:    or.b64 %rd19, %rd18, %rd17;
; SM90-NEXT:    setp.ne.b64 %p5, %rd19, 0;
; SM90-NEXT:    mov.b64 %rd30, %rd5;
; SM90-NEXT:    mov.b64 %rd31, %rd6;
; SM90-NEXT:    @%p5 bra $L__BB206_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd20, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd20, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd20, %rd20};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd32, %rd33}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB206_3: // %atomicrmw.start2
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    add.s64 %rd21, %rd33, -1;
; SM90-NEXT:    add.s64 %rd22, %rd32, -1;
; SM90-NEXT:    setp.eq.b64 %p6, %rd33, 0;
; SM90-NEXT:    setp.eq.b64 %p7, %rd32, 0;
; SM90-NEXT:    setp.gt.u64 %p8, %rd33, %rd4;
; SM90-NEXT:    setp.gt.u64 %p9, %rd32, %rd3;
; SM90-NEXT:    selp.b64 %rd23, %rd3, %rd22, %p9;
; SM90-NEXT:    selp.b64 %rd24, %rd3, %rd23, %p7;
; SM90-NEXT:    selp.b64 %rd25, %rd4, %rd21, %p8;
; SM90-NEXT:    selp.b64 %rd26, %rd4, %rd25, %p6;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd32, %rd33};
; SM90-NEXT:    mov.b128 swap, {%rd24, %rd26};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd7, %rd8}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd27, %rd8, %rd33;
; SM90-NEXT:    xor.b64 %rd28, %rd7, %rd32;
; SM90-NEXT:    or.b64 %rd29, %rd28, %rd27;
; SM90-NEXT:    setp.ne.b64 %p10, %rd29, 0;
; SM90-NEXT:    mov.b64 %rd32, %rd7;
; SM90-NEXT:    mov.b64 %rd33, %rd8;
; SM90-NEXT:    @%p10 bra $L__BB206_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end1
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd7, %rd8};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd5, %rd6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise udec_wrap ptr  addrspace(1) %addr, <4 x i64> %val syncscope("block") acq_rel
        ret <4 x i64> %retval
}

define <8 x i64> @udec_wrap_acq_rel_v8i64_global_cta(ptr addrspace(1) %addr, <8 x i64> %val) {
; SM90-LABEL: udec_wrap_acq_rel_v8i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<21>;
; SM90-NEXT:    .reg .b64 %rd<66>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd17, [udec_wrap_acq_rel_v8i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd3, %rd4}, [udec_wrap_acq_rel_v8i64_global_cta_param_1+48];
; SM90-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [udec_wrap_acq_rel_v8i64_global_cta_param_1+32];
; SM90-NEXT:    ld.param.v2.b64 {%rd5, %rd6}, [udec_wrap_acq_rel_v8i64_global_cta_param_1];
; SM90-NEXT:    ld.param.v2.b64 {%rd7, %rd8}, [udec_wrap_acq_rel_v8i64_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd18, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd18, %rd18};
; SM90-NEXT:    mov.b128 swap, {%rd18, %rd18};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd58, %rd59}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB207_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    mov.b64 %rd10, %rd59;
; SM90-NEXT:    mov.b64 %rd9, %rd58;
; SM90-NEXT:    add.s64 %rd19, %rd10, -1;
; SM90-NEXT:    add.s64 %rd20, %rd9, -1;
; SM90-NEXT:    setp.eq.b64 %p1, %rd10, 0;
; SM90-NEXT:    setp.eq.b64 %p2, %rd9, 0;
; SM90-NEXT:    setp.gt.u64 %p3, %rd10, %rd6;
; SM90-NEXT:    setp.gt.u64 %p4, %rd9, %rd5;
; SM90-NEXT:    selp.b64 %rd21, %rd5, %rd20, %p4;
; SM90-NEXT:    selp.b64 %rd22, %rd5, %rd21, %p2;
; SM90-NEXT:    selp.b64 %rd23, %rd6, %rd19, %p3;
; SM90-NEXT:    selp.b64 %rd24, %rd6, %rd23, %p1;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd9, %rd10};
; SM90-NEXT:    mov.b128 swap, {%rd22, %rd24};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd58, %rd59}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd25, %rd59, %rd10;
; SM90-NEXT:    xor.b64 %rd26, %rd58, %rd9;
; SM90-NEXT:    or.b64 %rd27, %rd26, %rd25;
; SM90-NEXT:    setp.ne.b64 %p5, %rd27, 0;
; SM90-NEXT:    @%p5 bra $L__BB207_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd28, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd28, %rd28};
; SM90-NEXT:    mov.b128 swap, {%rd28, %rd28};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd60, %rd61}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB207_3: // %atomicrmw.start6
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    mov.b64 %rd12, %rd61;
; SM90-NEXT:    mov.b64 %rd11, %rd60;
; SM90-NEXT:    add.s64 %rd29, %rd12, -1;
; SM90-NEXT:    add.s64 %rd30, %rd11, -1;
; SM90-NEXT:    setp.eq.b64 %p6, %rd12, 0;
; SM90-NEXT:    setp.eq.b64 %p7, %rd11, 0;
; SM90-NEXT:    setp.gt.u64 %p8, %rd12, %rd8;
; SM90-NEXT:    setp.gt.u64 %p9, %rd11, %rd7;
; SM90-NEXT:    selp.b64 %rd31, %rd7, %rd30, %p9;
; SM90-NEXT:    selp.b64 %rd32, %rd7, %rd31, %p7;
; SM90-NEXT:    selp.b64 %rd33, %rd8, %rd29, %p8;
; SM90-NEXT:    selp.b64 %rd34, %rd8, %rd33, %p6;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd11, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd32, %rd34};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd60, %rd61}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd35, %rd61, %rd12;
; SM90-NEXT:    xor.b64 %rd36, %rd60, %rd11;
; SM90-NEXT:    or.b64 %rd37, %rd36, %rd35;
; SM90-NEXT:    setp.ne.b64 %p10, %rd37, 0;
; SM90-NEXT:    @%p10 bra $L__BB207_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end5
; SM90-NEXT:    mov.b64 %rd38, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd38, %rd38};
; SM90-NEXT:    mov.b128 swap, {%rd38, %rd38};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+32], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd62, %rd63}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB207_5: // %atomicrmw.start16
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    add.s64 %rd39, %rd63, -1;
; SM90-NEXT:    add.s64 %rd40, %rd62, -1;
; SM90-NEXT:    setp.eq.b64 %p11, %rd63, 0;
; SM90-NEXT:    setp.eq.b64 %p12, %rd62, 0;
; SM90-NEXT:    setp.gt.u64 %p13, %rd63, %rd2;
; SM90-NEXT:    setp.gt.u64 %p14, %rd62, %rd1;
; SM90-NEXT:    selp.b64 %rd41, %rd1, %rd40, %p14;
; SM90-NEXT:    selp.b64 %rd42, %rd1, %rd41, %p12;
; SM90-NEXT:    selp.b64 %rd43, %rd2, %rd39, %p13;
; SM90-NEXT:    selp.b64 %rd44, %rd2, %rd43, %p11;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd62, %rd63};
; SM90-NEXT:    mov.b128 swap, {%rd42, %rd44};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+32], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd13, %rd14}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd45, %rd14, %rd63;
; SM90-NEXT:    xor.b64 %rd46, %rd13, %rd62;
; SM90-NEXT:    or.b64 %rd47, %rd46, %rd45;
; SM90-NEXT:    setp.ne.b64 %p15, %rd47, 0;
; SM90-NEXT:    mov.b64 %rd62, %rd13;
; SM90-NEXT:    mov.b64 %rd63, %rd14;
; SM90-NEXT:    @%p15 bra $L__BB207_5;
; SM90-NEXT:  // %bb.6: // %atomicrmw.end15
; SM90-NEXT:    mov.b64 %rd48, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd48, %rd48};
; SM90-NEXT:    mov.b128 swap, {%rd48, %rd48};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+48], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd64, %rd65}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB207_7: // %atomicrmw.start22
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    add.s64 %rd49, %rd65, -1;
; SM90-NEXT:    add.s64 %rd50, %rd64, -1;
; SM90-NEXT:    setp.eq.b64 %p16, %rd65, 0;
; SM90-NEXT:    setp.eq.b64 %p17, %rd64, 0;
; SM90-NEXT:    setp.gt.u64 %p18, %rd65, %rd4;
; SM90-NEXT:    setp.gt.u64 %p19, %rd64, %rd3;
; SM90-NEXT:    selp.b64 %rd51, %rd3, %rd50, %p19;
; SM90-NEXT:    selp.b64 %rd52, %rd3, %rd51, %p17;
; SM90-NEXT:    selp.b64 %rd53, %rd4, %rd49, %p18;
; SM90-NEXT:    selp.b64 %rd54, %rd4, %rd53, %p16;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd64, %rd65};
; SM90-NEXT:    mov.b128 swap, {%rd52, %rd54};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+48], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd15, %rd16}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd55, %rd16, %rd65;
; SM90-NEXT:    xor.b64 %rd56, %rd15, %rd64;
; SM90-NEXT:    or.b64 %rd57, %rd56, %rd55;
; SM90-NEXT:    setp.ne.b64 %p20, %rd57, 0;
; SM90-NEXT:    mov.b64 %rd64, %rd15;
; SM90-NEXT:    mov.b64 %rd65, %rd16;
; SM90-NEXT:    @%p20 bra $L__BB207_7;
; SM90-NEXT:  // %bb.8: // %atomicrmw.end21
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+48], {%rd15, %rd16};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+32], {%rd13, %rd14};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd58, %rd59};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd60, %rd61};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise udec_wrap ptr  addrspace(1) %addr, <8 x i64> %val syncscope("block") acq_rel
        ret <8 x i64> %retval
}

define <1 x i8> @usub_cond_acq_rel_v1i8_global_cta(ptr addrspace(1) %addr, <1 x i8> %val) {
; SM90-LABEL: usub_cond_acq_rel_v1i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<3>;
; SM90-NEXT:    .reg .b16 %rs<6>;
; SM90-NEXT:    .reg .b32 %r<16>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b8 %rs1, [usub_cond_acq_rel_v1i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd2, [usub_cond_acq_rel_v1i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r4, %rd2;
; SM90-NEXT:    and.b32 %r5, %r4, 3;
; SM90-NEXT:    shl.b32 %r1, %r5, 3;
; SM90-NEXT:    mov.b32 %r6, 255;
; SM90-NEXT:    shl.b32 %r7, %r6, %r1;
; SM90-NEXT:    not.b32 %r2, %r7;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r15, [%rd1];
; SM90-NEXT:  $L__BB208_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r8, %r15, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r8;
; SM90-NEXT:    and.b16 %rs3, %rs2, 255;
; SM90-NEXT:    setp.ge.u16 %p1, %rs3, %rs1;
; SM90-NEXT:    sub.s16 %rs4, %rs2, %rs1;
; SM90-NEXT:    selp.b16 %rs5, %rs4, %rs2, %p1;
; SM90-NEXT:    cvt.u32.u16 %r9, %rs5;
; SM90-NEXT:    and.b32 %r10, %r9, 255;
; SM90-NEXT:    shl.b32 %r11, %r10, %r1;
; SM90-NEXT:    and.b32 %r12, %r15, %r2;
; SM90-NEXT:    or.b32 %r13, %r12, %r11;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r15, %r13;
; SM90-NEXT:    setp.ne.b32 %p2, %r3, %r15;
; SM90-NEXT:    mov.b32 %r15, %r3;
; SM90-NEXT:    @%p2 bra $L__BB208_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r14, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b8 [func_retval0], %r14;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_cond ptr  addrspace(1) %addr, <1 x i8> %val syncscope("block") acq_rel
        ret <1 x i8> %retval
}

define <2 x i8> @usub_cond_acq_rel_v2i8_global_cta(ptr addrspace(1) %addr, <2 x i8> %val) {
; SM90-LABEL: usub_cond_acq_rel_v2i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<4>;
; SM90-NEXT:    .reg .b16 %rs<15>;
; SM90-NEXT:    .reg .b32 %r<16>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b8 {%rs1, %rs2}, [usub_cond_acq_rel_v2i8_global_cta_param_1];
; SM90-NEXT:    mov.b32 %r4, {%rs1, %rs2};
; SM90-NEXT:    ld.param.b64 %rd2, [usub_cond_acq_rel_v2i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:    and.b32 %r6, %r5, 3;
; SM90-NEXT:    shl.b32 %r1, %r6, 3;
; SM90-NEXT:    mov.b32 %r7, 65535;
; SM90-NEXT:    shl.b32 %r8, %r7, %r1;
; SM90-NEXT:    not.b32 %r2, %r8;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r15, [%rd1];
; SM90-NEXT:    mov.b32 {%rs6, %rs7}, %r4;
; SM90-NEXT:  $L__BB209_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r9, %r15, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs3, %r9;
; SM90-NEXT:    and.b16 %rs4, %rs3, 255;
; SM90-NEXT:    shr.u16 %rs5, %rs3, 8;
; SM90-NEXT:    setp.ge.u16 %p1, %rs5, %rs7;
; SM90-NEXT:    setp.ge.u16 %p2, %rs4, %rs6;
; SM90-NEXT:    sub.s16 %rs8, %rs5, %rs7;
; SM90-NEXT:    sub.s16 %rs9, %rs3, %rs6;
; SM90-NEXT:    selp.b16 %rs10, %rs9, %rs3, %p2;
; SM90-NEXT:    selp.b16 %rs11, %rs8, %rs5, %p1;
; SM90-NEXT:    shl.b16 %rs12, %rs11, 8;
; SM90-NEXT:    and.b16 %rs13, %rs10, 255;
; SM90-NEXT:    or.b16 %rs14, %rs13, %rs12;
; SM90-NEXT:    cvt.u32.u16 %r10, %rs14;
; SM90-NEXT:    shl.b32 %r11, %r10, %r1;
; SM90-NEXT:    and.b32 %r12, %r15, %r2;
; SM90-NEXT:    or.b32 %r13, %r12, %r11;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r15, %r13;
; SM90-NEXT:    setp.ne.b32 %p3, %r3, %r15;
; SM90-NEXT:    mov.b32 %r15, %r3;
; SM90-NEXT:    @%p3 bra $L__BB209_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r14, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r14;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_cond ptr  addrspace(1) %addr, <2 x i8> %val syncscope("block") acq_rel
        ret <2 x i8> %retval
}

define <4 x i8> @usub_cond_acq_rel_v4i8_global_cta(ptr addrspace(1) %addr, <4 x i8> %val) {
; SM90-LABEL: usub_cond_acq_rel_v4i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<6>;
; SM90-NEXT:    .reg .b16 %rs<13>;
; SM90-NEXT:    .reg .b32 %r<23>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [usub_cond_acq_rel_v4i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [usub_cond_acq_rel_v4i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r22, [%rd1];
; SM90-NEXT:    prmt.b32 %r3, %r2, 0, 0x7770U;
; SM90-NEXT:    prmt.b32 %r5, %r2, 0, 0x7771U;
; SM90-NEXT:    prmt.b32 %r7, %r2, 0, 0x7772U;
; SM90-NEXT:    prmt.b32 %r9, %r2, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs1, %r9;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r7;
; SM90-NEXT:    cvt.u16.u32 %rs3, %r5;
; SM90-NEXT:    cvt.u16.u32 %rs4, %r3;
; SM90-NEXT:  $L__BB210_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    prmt.b32 %r4, %r22, 0, 0x7770U;
; SM90-NEXT:    setp.ge.u32 %p1, %r4, %r3;
; SM90-NEXT:    prmt.b32 %r6, %r22, 0, 0x7771U;
; SM90-NEXT:    setp.ge.u32 %p2, %r6, %r5;
; SM90-NEXT:    prmt.b32 %r8, %r22, 0, 0x7772U;
; SM90-NEXT:    setp.ge.u32 %p3, %r8, %r7;
; SM90-NEXT:    prmt.b32 %r10, %r22, 0, 0x7773U;
; SM90-NEXT:    setp.ge.u32 %p4, %r10, %r9;
; SM90-NEXT:    cvt.u16.u32 %rs5, %r4;
; SM90-NEXT:    sub.s16 %rs6, %rs5, %rs4;
; SM90-NEXT:    cvt.u16.u32 %rs7, %r6;
; SM90-NEXT:    sub.s16 %rs8, %rs7, %rs3;
; SM90-NEXT:    cvt.u16.u32 %rs9, %r8;
; SM90-NEXT:    sub.s16 %rs10, %rs9, %rs2;
; SM90-NEXT:    cvt.u16.u32 %rs11, %r10;
; SM90-NEXT:    sub.s16 %rs12, %rs11, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r11, %rs12;
; SM90-NEXT:    selp.b32 %r12, %r11, %r10, %p4;
; SM90-NEXT:    cvt.u32.u16 %r13, %rs10;
; SM90-NEXT:    selp.b32 %r14, %r13, %r8, %p3;
; SM90-NEXT:    prmt.b32 %r15, %r14, %r12, 0x3340U;
; SM90-NEXT:    cvt.u32.u16 %r16, %rs8;
; SM90-NEXT:    selp.b32 %r17, %r16, %r6, %p2;
; SM90-NEXT:    cvt.u32.u16 %r18, %rs6;
; SM90-NEXT:    selp.b32 %r19, %r18, %r4, %p1;
; SM90-NEXT:    prmt.b32 %r20, %r19, %r17, 0x3340U;
; SM90-NEXT:    prmt.b32 %r21, %r20, %r15, 0x5410U;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r22, %r21;
; SM90-NEXT:    setp.ne.b32 %p5, %r1, %r22;
; SM90-NEXT:    mov.b32 %r22, %r1;
; SM90-NEXT:    @%p5 bra $L__BB210_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_cond ptr  addrspace(1) %addr, <4 x i8> %val syncscope("block") acq_rel
        ret <4 x i8> %retval
}

define <8 x i8> @usub_cond_acq_rel_v8i8_global_cta(ptr addrspace(1) %addr, <8 x i8> %val) {
; SM90-LABEL: usub_cond_acq_rel_v8i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<10>;
; SM90-NEXT:    .reg .b16 %rs<33>;
; SM90-NEXT:    .reg .b32 %r<35>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [usub_cond_acq_rel_v8i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [usub_cond_acq_rel_v8i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r34}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r33, %rd2;
; SM90-NEXT:    prmt.b32 %r3, %r2, 0, 0x7770U;
; SM90-NEXT:    prmt.b32 %r5, %r2, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs13, %r5;
; SM90-NEXT:    cvt.u16.u32 %rs15, %r3;
; SM90-NEXT:  $L__BB211_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd3, %r33;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r34;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    prmt.b32 %r4, %r34, 0, 0x7770U;
; SM90-NEXT:    setp.ge.u32 %p1, %r4, %r3;
; SM90-NEXT:    prmt.b32 %r6, %r34, 0, 0x7771U;
; SM90-NEXT:    setp.ge.u32 %p2, %r6, %r5;
; SM90-NEXT:    prmt.b32 %r7, %r2, 0, 0x7772U;
; SM90-NEXT:    prmt.b32 %r8, %r34, 0, 0x7772U;
; SM90-NEXT:    setp.ge.u32 %p3, %r8, %r7;
; SM90-NEXT:    prmt.b32 %r9, %r2, 0, 0x7773U;
; SM90-NEXT:    prmt.b32 %r10, %r34, 0, 0x7773U;
; SM90-NEXT:    setp.ge.u32 %p4, %r10, %r9;
; SM90-NEXT:    prmt.b32 %r11, %r1, 0, 0x7770U;
; SM90-NEXT:    prmt.b32 %r12, %r33, 0, 0x7770U;
; SM90-NEXT:    setp.ge.u32 %p5, %r12, %r11;
; SM90-NEXT:    prmt.b32 %r13, %r1, 0, 0x7771U;
; SM90-NEXT:    prmt.b32 %r14, %r33, 0, 0x7771U;
; SM90-NEXT:    setp.ge.u32 %p6, %r14, %r13;
; SM90-NEXT:    prmt.b32 %r15, %r1, 0, 0x7772U;
; SM90-NEXT:    prmt.b32 %r16, %r33, 0, 0x7772U;
; SM90-NEXT:    setp.ge.u32 %p7, %r16, %r15;
; SM90-NEXT:    prmt.b32 %r17, %r1, 0, 0x7773U;
; SM90-NEXT:    prmt.b32 %r18, %r33, 0, 0x7773U;
; SM90-NEXT:    setp.ge.u32 %p8, %r18, %r17;
; SM90-NEXT:    cvt.u16.u32 %rs1, %r17;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r18;
; SM90-NEXT:    cvt.u16.u32 %rs3, %r15;
; SM90-NEXT:    cvt.u16.u32 %rs4, %r16;
; SM90-NEXT:    cvt.u16.u32 %rs5, %r13;
; SM90-NEXT:    cvt.u16.u32 %rs6, %r14;
; SM90-NEXT:    cvt.u16.u32 %rs7, %r11;
; SM90-NEXT:    cvt.u16.u32 %rs8, %r12;
; SM90-NEXT:    cvt.u16.u32 %rs9, %r9;
; SM90-NEXT:    cvt.u16.u32 %rs10, %r10;
; SM90-NEXT:    cvt.u16.u32 %rs11, %r7;
; SM90-NEXT:    cvt.u16.u32 %rs12, %r8;
; SM90-NEXT:    cvt.u16.u32 %rs14, %r6;
; SM90-NEXT:    cvt.u16.u32 %rs16, %r4;
; SM90-NEXT:    sub.s16 %rs17, %rs16, %rs15;
; SM90-NEXT:    sub.s16 %rs18, %rs14, %rs13;
; SM90-NEXT:    sub.s16 %rs19, %rs12, %rs11;
; SM90-NEXT:    sub.s16 %rs20, %rs10, %rs9;
; SM90-NEXT:    sub.s16 %rs21, %rs8, %rs7;
; SM90-NEXT:    sub.s16 %rs22, %rs6, %rs5;
; SM90-NEXT:    sub.s16 %rs23, %rs4, %rs3;
; SM90-NEXT:    sub.s16 %rs24, %rs2, %rs1;
; SM90-NEXT:    selp.b16 %rs25, %rs24, %rs2, %p8;
; SM90-NEXT:    cvt.u32.u16 %r19, %rs25;
; SM90-NEXT:    selp.b16 %rs26, %rs23, %rs4, %p7;
; SM90-NEXT:    cvt.u32.u16 %r20, %rs26;
; SM90-NEXT:    prmt.b32 %r21, %r20, %r19, 0x3340U;
; SM90-NEXT:    selp.b16 %rs27, %rs22, %rs6, %p6;
; SM90-NEXT:    cvt.u32.u16 %r22, %rs27;
; SM90-NEXT:    selp.b16 %rs28, %rs21, %rs8, %p5;
; SM90-NEXT:    cvt.u32.u16 %r23, %rs28;
; SM90-NEXT:    prmt.b32 %r24, %r23, %r22, 0x3340U;
; SM90-NEXT:    prmt.b32 %r25, %r24, %r21, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r25;
; SM90-NEXT:    selp.b16 %rs29, %rs20, %rs10, %p4;
; SM90-NEXT:    cvt.u32.u16 %r26, %rs29;
; SM90-NEXT:    selp.b16 %rs30, %rs19, %rs12, %p3;
; SM90-NEXT:    cvt.u32.u16 %r27, %rs30;
; SM90-NEXT:    prmt.b32 %r28, %r27, %r26, 0x3340U;
; SM90-NEXT:    selp.b16 %rs31, %rs18, %rs14, %p2;
; SM90-NEXT:    cvt.u32.u16 %r29, %rs31;
; SM90-NEXT:    selp.b16 %rs32, %rs17, %rs16, %p1;
; SM90-NEXT:    cvt.u32.u16 %r30, %rs32;
; SM90-NEXT:    prmt.b32 %r31, %r30, %r29, 0x3340U;
; SM90-NEXT:    prmt.b32 %r32, %r31, %r28, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r32;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd6, %rd10;
; SM90-NEXT:    setp.ne.b64 %p9, %rd11, %rd6;
; SM90-NEXT:    mov.b64 {_, %r34}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r33, %rd11;
; SM90-NEXT:    @%p9 bra $L__BB211_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r33, %r34};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_cond ptr  addrspace(1) %addr, <8 x i8> %val syncscope("block") acq_rel
        ret <8 x i8> %retval
}

define <1 x i16> @usub_cond_acq_rel_v1i16_global_cta(ptr addrspace(1) %addr, <1 x i16> %val) {
; SM90-LABEL: usub_cond_acq_rel_v1i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<3>;
; SM90-NEXT:    .reg .b16 %rs<5>;
; SM90-NEXT:    .reg .b32 %r<15>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [usub_cond_acq_rel_v1i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b16 %rs1, [usub_cond_acq_rel_v1i16_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r4, %rd2;
; SM90-NEXT:    and.b32 %r5, %r4, 3;
; SM90-NEXT:    shl.b32 %r1, %r5, 3;
; SM90-NEXT:    mov.b32 %r6, 65535;
; SM90-NEXT:    shl.b32 %r7, %r6, %r1;
; SM90-NEXT:    not.b32 %r2, %r7;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r14, [%rd1];
; SM90-NEXT:  $L__BB212_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r8, %r14, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r8;
; SM90-NEXT:    setp.ge.u16 %p1, %rs2, %rs1;
; SM90-NEXT:    sub.s16 %rs3, %rs2, %rs1;
; SM90-NEXT:    selp.b16 %rs4, %rs3, %rs2, %p1;
; SM90-NEXT:    cvt.u32.u16 %r9, %rs4;
; SM90-NEXT:    shl.b32 %r10, %r9, %r1;
; SM90-NEXT:    and.b32 %r11, %r14, %r2;
; SM90-NEXT:    or.b32 %r12, %r11, %r10;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r14, %r12;
; SM90-NEXT:    setp.ne.b32 %p2, %r3, %r14;
; SM90-NEXT:    mov.b32 %r14, %r3;
; SM90-NEXT:    @%p2 bra $L__BB212_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r13, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r13;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_cond ptr  addrspace(1) %addr, <1 x i16> %val syncscope("block") acq_rel
        ret <1 x i16> %retval
}

define <2 x i16> @usub_cond_acq_rel_v2i16_global_cta(ptr addrspace(1) %addr, <2 x i16> %val) {
; SM90-LABEL: usub_cond_acq_rel_v2i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<4>;
; SM90-NEXT:    .reg .b16 %rs<9>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [usub_cond_acq_rel_v2i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [usub_cond_acq_rel_v2i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:    mov.b32 {%rs1, %rs2}, %r2;
; SM90-NEXT:  $L__BB213_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    mov.b32 {%rs3, %rs4}, %r4;
; SM90-NEXT:    setp.ge.u16 %p1, %rs3, %rs1;
; SM90-NEXT:    setp.ge.u16 %p2, %rs4, %rs2;
; SM90-NEXT:    sub.s16 %rs5, %rs3, %rs1;
; SM90-NEXT:    sub.s16 %rs6, %rs4, %rs2;
; SM90-NEXT:    selp.b16 %rs7, %rs6, %rs4, %p2;
; SM90-NEXT:    selp.b16 %rs8, %rs5, %rs3, %p1;
; SM90-NEXT:    mov.b32 %r3, {%rs8, %rs7};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p3, %r1, %r4;
; SM90-NEXT:    mov.b32 %r4, %r1;
; SM90-NEXT:    @%p3 bra $L__BB213_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_cond ptr  addrspace(1) %addr, <2 x i16> %val syncscope("block") acq_rel
        ret <2 x i16> %retval
}

define <4 x i16> @usub_cond_acq_rel_v4i16_global_cta(ptr addrspace(1) %addr, <4 x i16> %val) {
; SM90-LABEL: usub_cond_acq_rel_v4i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<6>;
; SM90-NEXT:    .reg .b16 %rs<17>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [usub_cond_acq_rel_v4i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [usub_cond_acq_rel_v4i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:    mov.b32 {%rs1, %rs2}, %r2;
; SM90-NEXT:    mov.b32 {%rs5, %rs6}, %r1;
; SM90-NEXT:  $L__BB214_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd3, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r6;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    mov.b32 {%rs3, %rs4}, %r6;
; SM90-NEXT:    setp.ge.u16 %p1, %rs3, %rs1;
; SM90-NEXT:    setp.ge.u16 %p2, %rs4, %rs2;
; SM90-NEXT:    mov.b32 {%rs7, %rs8}, %r5;
; SM90-NEXT:    setp.ge.u16 %p3, %rs7, %rs5;
; SM90-NEXT:    setp.ge.u16 %p4, %rs8, %rs6;
; SM90-NEXT:    sub.s16 %rs9, %rs3, %rs1;
; SM90-NEXT:    sub.s16 %rs10, %rs4, %rs2;
; SM90-NEXT:    sub.s16 %rs11, %rs7, %rs5;
; SM90-NEXT:    sub.s16 %rs12, %rs8, %rs6;
; SM90-NEXT:    selp.b16 %rs13, %rs12, %rs8, %p4;
; SM90-NEXT:    selp.b16 %rs14, %rs11, %rs7, %p3;
; SM90-NEXT:    mov.b32 %r3, {%rs14, %rs13};
; SM90-NEXT:    cvt.u64.u32 %rd7, %r3;
; SM90-NEXT:    selp.b16 %rs15, %rs10, %rs4, %p2;
; SM90-NEXT:    selp.b16 %rs16, %rs9, %rs3, %p1;
; SM90-NEXT:    mov.b32 %r4, {%rs16, %rs15};
; SM90-NEXT:    cvt.u64.u32 %rd8, %r4;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd6, %rd10;
; SM90-NEXT:    setp.ne.b64 %p5, %rd11, %rd6;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p5 bra $L__BB214_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_cond ptr  addrspace(1) %addr, <4 x i16> %val syncscope("block") acq_rel
        ret <4 x i16> %retval
}

define <8 x i16> @usub_cond_acq_rel_v8i16_global_cta(ptr addrspace(1) %addr, <8 x i16> %val) {
; SM90-LABEL: usub_cond_acq_rel_v8i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<10>;
; SM90-NEXT:    .reg .b16 %rs<33>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [usub_cond_acq_rel_v8i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [usub_cond_acq_rel_v8i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:    mov.b32 {%rs1, %rs2}, %r4;
; SM90-NEXT:    mov.b32 {%rs5, %rs6}, %r3;
; SM90-NEXT:  $L__BB215_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd5, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r10;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r12;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    mov.b32 {%rs3, %rs4}, %r12;
; SM90-NEXT:    setp.ge.u16 %p1, %rs3, %rs1;
; SM90-NEXT:    setp.ge.u16 %p2, %rs4, %rs2;
; SM90-NEXT:    mov.b32 {%rs7, %rs8}, %r11;
; SM90-NEXT:    setp.ge.u16 %p3, %rs7, %rs5;
; SM90-NEXT:    setp.ge.u16 %p4, %rs8, %rs6;
; SM90-NEXT:    mov.b32 {%rs9, %rs10}, %r2;
; SM90-NEXT:    mov.b32 {%rs11, %rs12}, %r10;
; SM90-NEXT:    setp.ge.u16 %p5, %rs11, %rs9;
; SM90-NEXT:    setp.ge.u16 %p6, %rs12, %rs10;
; SM90-NEXT:    mov.b32 {%rs13, %rs14}, %r1;
; SM90-NEXT:    mov.b32 {%rs15, %rs16}, %r9;
; SM90-NEXT:    setp.ge.u16 %p7, %rs15, %rs13;
; SM90-NEXT:    setp.ge.u16 %p8, %rs16, %rs14;
; SM90-NEXT:    sub.s16 %rs17, %rs3, %rs1;
; SM90-NEXT:    sub.s16 %rs18, %rs4, %rs2;
; SM90-NEXT:    sub.s16 %rs19, %rs7, %rs5;
; SM90-NEXT:    sub.s16 %rs20, %rs8, %rs6;
; SM90-NEXT:    sub.s16 %rs21, %rs11, %rs9;
; SM90-NEXT:    sub.s16 %rs22, %rs12, %rs10;
; SM90-NEXT:    sub.s16 %rs23, %rs15, %rs13;
; SM90-NEXT:    sub.s16 %rs24, %rs16, %rs14;
; SM90-NEXT:    selp.b16 %rs25, %rs24, %rs16, %p8;
; SM90-NEXT:    selp.b16 %rs26, %rs23, %rs15, %p7;
; SM90-NEXT:    mov.b32 %r5, {%rs26, %rs25};
; SM90-NEXT:    cvt.u64.u32 %rd13, %r5;
; SM90-NEXT:    selp.b16 %rs27, %rs22, %rs12, %p6;
; SM90-NEXT:    selp.b16 %rs28, %rs21, %rs11, %p5;
; SM90-NEXT:    mov.b32 %r6, {%rs28, %rs27};
; SM90-NEXT:    cvt.u64.u32 %rd14, %r6;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    selp.b16 %rs29, %rs20, %rs8, %p4;
; SM90-NEXT:    selp.b16 %rs30, %rs19, %rs7, %p3;
; SM90-NEXT:    mov.b32 %r7, {%rs30, %rs29};
; SM90-NEXT:    cvt.u64.u32 %rd17, %r7;
; SM90-NEXT:    selp.b16 %rs31, %rs18, %rs4, %p2;
; SM90-NEXT:    selp.b16 %rs32, %rs17, %rs3, %p1;
; SM90-NEXT:    mov.b32 %r8, {%rs32, %rs31};
; SM90-NEXT:    cvt.u64.u32 %rd18, %r8;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd8, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd16, %rd20};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd12;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd8;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd22;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd21;
; SM90-NEXT:    setp.ne.b64 %p9, %rd25, 0;
; SM90-NEXT:    @%p9 bra $L__BB215_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_cond ptr  addrspace(1) %addr, <8 x i16> %val syncscope("block") acq_rel
        ret <8 x i16> %retval
}

define <1 x i32> @usub_cond_acq_rel_v1i32_global_cta(ptr addrspace(1) %addr, <1 x i32> %val) {
; SM90-LABEL: usub_cond_acq_rel_v1i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<3>;
; SM90-NEXT:    .reg .b32 %r<6>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [usub_cond_acq_rel_v1i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b32 %r1, [usub_cond_acq_rel_v1i32_global_cta_param_1];
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r5, [%rd1];
; SM90-NEXT:  $L__BB216_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    setp.ge.u32 %p1, %r5, %r1;
; SM90-NEXT:    sub.s32 %r3, %r5, %r1;
; SM90-NEXT:    selp.b32 %r4, %r3, %r5, %p1;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r2, [%rd1], %r5, %r4;
; SM90-NEXT:    setp.ne.b32 %p2, %r2, %r5;
; SM90-NEXT:    mov.b32 %r5, %r2;
; SM90-NEXT:    @%p2 bra $L__BB216_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_cond ptr  addrspace(1) %addr, <1 x i32> %val syncscope("block") acq_rel
        ret <1 x i32> %retval
}

define <2 x i32> @usub_cond_acq_rel_v2i32_global_cta(ptr addrspace(1) %addr, <2 x i32> %val) {
; SM90-LABEL: usub_cond_acq_rel_v2i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<4>;
; SM90-NEXT:    .reg .b32 %r<9>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [usub_cond_acq_rel_v2i32_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [usub_cond_acq_rel_v2i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r8}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd2;
; SM90-NEXT:  $L__BB217_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd3, %r7;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r8;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    setp.ge.u32 %p1, %r8, %r2;
; SM90-NEXT:    setp.ge.u32 %p2, %r7, %r1;
; SM90-NEXT:    sub.s32 %r3, %r8, %r2;
; SM90-NEXT:    sub.s32 %r4, %r7, %r1;
; SM90-NEXT:    selp.b32 %r5, %r4, %r7, %p2;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    selp.b32 %r6, %r3, %r8, %p1;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd6, %rd10;
; SM90-NEXT:    setp.ne.b64 %p3, %rd11, %rd6;
; SM90-NEXT:    mov.b64 {_, %r8}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd11;
; SM90-NEXT:    @%p3 bra $L__BB217_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r7, %r8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_cond ptr  addrspace(1) %addr, <2 x i32> %val syncscope("block") acq_rel
        ret <2 x i32> %retval
}

define <4 x i32> @usub_cond_acq_rel_v4i32_global_cta(ptr addrspace(1) %addr, <4 x i32> %val) {
; SM90-LABEL: usub_cond_acq_rel_v4i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<6>;
; SM90-NEXT:    .reg .b32 %r<17>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [usub_cond_acq_rel_v4i32_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [usub_cond_acq_rel_v4i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r16}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r15, %rd4;
; SM90-NEXT:    mov.b64 {_, %r14}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r13, %rd3;
; SM90-NEXT:  $L__BB218_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd5, %r13;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r14;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r15;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r16;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    setp.ge.u32 %p1, %r16, %r4;
; SM90-NEXT:    setp.ge.u32 %p2, %r15, %r3;
; SM90-NEXT:    setp.ge.u32 %p3, %r14, %r2;
; SM90-NEXT:    setp.ge.u32 %p4, %r13, %r1;
; SM90-NEXT:    sub.s32 %r5, %r16, %r4;
; SM90-NEXT:    sub.s32 %r6, %r15, %r3;
; SM90-NEXT:    sub.s32 %r7, %r14, %r2;
; SM90-NEXT:    sub.s32 %r8, %r13, %r1;
; SM90-NEXT:    selp.b32 %r9, %r8, %r13, %p4;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r9;
; SM90-NEXT:    selp.b32 %r10, %r7, %r14, %p3;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r10;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    selp.b32 %r11, %r6, %r15, %p2;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r11;
; SM90-NEXT:    selp.b32 %r12, %r5, %r16, %p1;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r12;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd8, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd16, %rd20};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd12;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd8;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r16}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r15, %rd22;
; SM90-NEXT:    mov.b64 {_, %r14}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r13, %rd21;
; SM90-NEXT:    setp.ne.b64 %p5, %rd25, 0;
; SM90-NEXT:    @%p5 bra $L__BB218_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r13, %r14, %r15, %r16};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_cond ptr  addrspace(1) %addr, <4 x i32> %val syncscope("block") acq_rel
        ret <4 x i32> %retval
}

define <8 x i32> @usub_cond_acq_rel_v8i32_global_cta(ptr addrspace(1) %addr, <8 x i32> %val) {
; SM90-LABEL: usub_cond_acq_rel_v8i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<11>;
; SM90-NEXT:    .reg .b32 %r<33>;
; SM90-NEXT:    .reg .b64 %rd<50>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [usub_cond_acq_rel_v8i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [usub_cond_acq_rel_v8i32_global_cta_param_1];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [usub_cond_acq_rel_v8i32_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r28}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r27, %rd4;
; SM90-NEXT:    mov.b64 {_, %r26}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r25, %rd3;
; SM90-NEXT:  $L__BB219_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd5, %r25;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r26;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r27;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r28;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    setp.ge.u32 %p1, %r28, %r4;
; SM90-NEXT:    setp.ge.u32 %p2, %r27, %r3;
; SM90-NEXT:    setp.ge.u32 %p3, %r26, %r2;
; SM90-NEXT:    setp.ge.u32 %p4, %r25, %r1;
; SM90-NEXT:    sub.s32 %r9, %r28, %r4;
; SM90-NEXT:    sub.s32 %r10, %r27, %r3;
; SM90-NEXT:    sub.s32 %r11, %r26, %r2;
; SM90-NEXT:    sub.s32 %r12, %r25, %r1;
; SM90-NEXT:    selp.b32 %r13, %r12, %r25, %p4;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r13;
; SM90-NEXT:    selp.b32 %r14, %r11, %r26, %p3;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r14;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    selp.b32 %r15, %r10, %r27, %p2;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r15;
; SM90-NEXT:    selp.b32 %r16, %r9, %r28, %p1;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r16;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd8, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd16, %rd20};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd12;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd8;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r28}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r27, %rd22;
; SM90-NEXT:    mov.b64 {_, %r26}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r25, %rd21;
; SM90-NEXT:    setp.ne.b64 %p5, %rd25, 0;
; SM90-NEXT:    @%p5 bra $L__BB219_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd26, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd26, %rd26};
; SM90-NEXT:    mov.b128 swap, {%rd26, %rd26};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd27, %rd28}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r32}, %rd28;
; SM90-NEXT:    cvt.u32.u64 %r31, %rd28;
; SM90-NEXT:    mov.b64 {_, %r30}, %rd27;
; SM90-NEXT:    cvt.u32.u64 %r29, %rd27;
; SM90-NEXT:  $L__BB219_3: // %atomicrmw.start2
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd29, %r29;
; SM90-NEXT:    cvt.u64.u32 %rd30, %r30;
; SM90-NEXT:    shl.b64 %rd31, %rd30, 32;
; SM90-NEXT:    or.b64 %rd32, %rd29, %rd31;
; SM90-NEXT:    cvt.u64.u32 %rd33, %r31;
; SM90-NEXT:    cvt.u64.u32 %rd34, %r32;
; SM90-NEXT:    shl.b64 %rd35, %rd34, 32;
; SM90-NEXT:    or.b64 %rd36, %rd33, %rd35;
; SM90-NEXT:    setp.ge.u32 %p6, %r32, %r8;
; SM90-NEXT:    setp.ge.u32 %p7, %r31, %r7;
; SM90-NEXT:    setp.ge.u32 %p8, %r30, %r6;
; SM90-NEXT:    setp.ge.u32 %p9, %r29, %r5;
; SM90-NEXT:    sub.s32 %r17, %r32, %r8;
; SM90-NEXT:    sub.s32 %r18, %r31, %r7;
; SM90-NEXT:    sub.s32 %r19, %r30, %r6;
; SM90-NEXT:    sub.s32 %r20, %r29, %r5;
; SM90-NEXT:    selp.b32 %r21, %r20, %r29, %p9;
; SM90-NEXT:    cvt.u64.u32 %rd37, %r21;
; SM90-NEXT:    selp.b32 %r22, %r19, %r30, %p8;
; SM90-NEXT:    cvt.u64.u32 %rd38, %r22;
; SM90-NEXT:    shl.b64 %rd39, %rd38, 32;
; SM90-NEXT:    or.b64 %rd40, %rd37, %rd39;
; SM90-NEXT:    selp.b32 %r23, %r18, %r31, %p7;
; SM90-NEXT:    cvt.u64.u32 %rd41, %r23;
; SM90-NEXT:    selp.b32 %r24, %r17, %r32, %p6;
; SM90-NEXT:    cvt.u64.u32 %rd42, %r24;
; SM90-NEXT:    shl.b64 %rd43, %rd42, 32;
; SM90-NEXT:    or.b64 %rd44, %rd41, %rd43;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd32, %rd36};
; SM90-NEXT:    mov.b128 swap, {%rd40, %rd44};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd45, %rd46}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd47, %rd46, %rd36;
; SM90-NEXT:    xor.b64 %rd48, %rd45, %rd32;
; SM90-NEXT:    or.b64 %rd49, %rd48, %rd47;
; SM90-NEXT:    mov.b64 {_, %r32}, %rd46;
; SM90-NEXT:    cvt.u32.u64 %r31, %rd46;
; SM90-NEXT:    mov.b64 {_, %r30}, %rd45;
; SM90-NEXT:    cvt.u32.u64 %r29, %rd45;
; SM90-NEXT:    setp.ne.b64 %p10, %rd49, 0;
; SM90-NEXT:    @%p10 bra $L__BB219_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end1
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r29, %r30, %r31, %r32};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r25, %r26, %r27, %r28};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_cond ptr  addrspace(1) %addr, <8 x i32> %val syncscope("block") acq_rel
        ret <8 x i32> %retval
}

define <1 x i64> @usub_cond_acq_rel_v1i64_global_cta(ptr addrspace(1) %addr, <1 x i64> %val) {
; SM90-LABEL: usub_cond_acq_rel_v1i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<3>;
; SM90-NEXT:    .reg .b64 %rd<7>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd3, [usub_cond_acq_rel_v1i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b64 %rd1, [usub_cond_acq_rel_v1i64_global_cta_param_1];
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd6, [%rd3];
; SM90-NEXT:  $L__BB220_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    setp.ge.u64 %p1, %rd6, %rd1;
; SM90-NEXT:    sub.s64 %rd4, %rd6, %rd1;
; SM90-NEXT:    selp.b64 %rd5, %rd4, %rd6, %p1;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd2, [%rd3], %rd6, %rd5;
; SM90-NEXT:    setp.ne.b64 %p2, %rd2, %rd6;
; SM90-NEXT:    mov.b64 %rd6, %rd2;
; SM90-NEXT:    @%p2 bra $L__BB220_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b64 [func_retval0], %rd2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_cond ptr  addrspace(1) %addr, <1 x i64> %val syncscope("block") acq_rel
        ret <1 x i64> %retval
}

define <2 x i64> @usub_cond_acq_rel_v2i64_global_cta(ptr addrspace(1) %addr, <2 x i64> %val) {
; SM90-LABEL: usub_cond_acq_rel_v2i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<4>;
; SM90-NEXT:    .reg .b64 %rd<16>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [usub_cond_acq_rel_v2i64_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd3, [usub_cond_acq_rel_v2i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd6, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd6, %rd6};
; SM90-NEXT:    mov.b128 swap, {%rd6, %rd6};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd3], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd14, %rd15}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB221_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    setp.ge.u64 %p1, %rd15, %rd5;
; SM90-NEXT:    setp.ge.u64 %p2, %rd14, %rd4;
; SM90-NEXT:    sub.s64 %rd7, %rd15, %rd5;
; SM90-NEXT:    sub.s64 %rd8, %rd14, %rd4;
; SM90-NEXT:    selp.b64 %rd9, %rd8, %rd14, %p2;
; SM90-NEXT:    selp.b64 %rd10, %rd7, %rd15, %p1;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd14, %rd15};
; SM90-NEXT:    mov.b128 swap, {%rd9, %rd10};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd3], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd1, %rd2}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd11, %rd2, %rd15;
; SM90-NEXT:    xor.b64 %rd12, %rd1, %rd14;
; SM90-NEXT:    or.b64 %rd13, %rd12, %rd11;
; SM90-NEXT:    setp.ne.b64 %p3, %rd13, 0;
; SM90-NEXT:    mov.b64 %rd14, %rd1;
; SM90-NEXT:    mov.b64 %rd15, %rd2;
; SM90-NEXT:    @%p3 bra $L__BB221_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd1, %rd2};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_cond ptr  addrspace(1) %addr, <2 x i64> %val syncscope("block") acq_rel
        ret <2 x i64> %retval
}

define <4 x i64> @usub_cond_acq_rel_v4i64_global_cta(ptr addrspace(1) %addr, <4 x i64> %val) {
; SM90-LABEL: usub_cond_acq_rel_v4i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<7>;
; SM90-NEXT:    .reg .b64 %rd<30>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd9, [usub_cond_acq_rel_v4i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [usub_cond_acq_rel_v4i64_global_cta_param_1];
; SM90-NEXT:    ld.param.v2.b64 {%rd3, %rd4}, [usub_cond_acq_rel_v4i64_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd10, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd10, %rd10};
; SM90-NEXT:    mov.b128 swap, {%rd10, %rd10};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd26, %rd27}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB222_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    setp.ge.u64 %p1, %rd27, %rd2;
; SM90-NEXT:    setp.ge.u64 %p2, %rd26, %rd1;
; SM90-NEXT:    sub.s64 %rd11, %rd27, %rd2;
; SM90-NEXT:    sub.s64 %rd12, %rd26, %rd1;
; SM90-NEXT:    selp.b64 %rd13, %rd12, %rd26, %p2;
; SM90-NEXT:    selp.b64 %rd14, %rd11, %rd27, %p1;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd26, %rd27};
; SM90-NEXT:    mov.b128 swap, {%rd13, %rd14};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd5, %rd6}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd15, %rd6, %rd27;
; SM90-NEXT:    xor.b64 %rd16, %rd5, %rd26;
; SM90-NEXT:    or.b64 %rd17, %rd16, %rd15;
; SM90-NEXT:    setp.ne.b64 %p3, %rd17, 0;
; SM90-NEXT:    mov.b64 %rd26, %rd5;
; SM90-NEXT:    mov.b64 %rd27, %rd6;
; SM90-NEXT:    @%p3 bra $L__BB222_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd18, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd18, %rd18};
; SM90-NEXT:    mov.b128 swap, {%rd18, %rd18};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd28, %rd29}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB222_3: // %atomicrmw.start2
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    setp.ge.u64 %p4, %rd29, %rd4;
; SM90-NEXT:    setp.ge.u64 %p5, %rd28, %rd3;
; SM90-NEXT:    sub.s64 %rd19, %rd29, %rd4;
; SM90-NEXT:    sub.s64 %rd20, %rd28, %rd3;
; SM90-NEXT:    selp.b64 %rd21, %rd20, %rd28, %p5;
; SM90-NEXT:    selp.b64 %rd22, %rd19, %rd29, %p4;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd28, %rd29};
; SM90-NEXT:    mov.b128 swap, {%rd21, %rd22};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd7, %rd8}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd8, %rd29;
; SM90-NEXT:    xor.b64 %rd24, %rd7, %rd28;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    setp.ne.b64 %p6, %rd25, 0;
; SM90-NEXT:    mov.b64 %rd28, %rd7;
; SM90-NEXT:    mov.b64 %rd29, %rd8;
; SM90-NEXT:    @%p6 bra $L__BB222_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end1
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd7, %rd8};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd5, %rd6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_cond ptr  addrspace(1) %addr, <4 x i64> %val syncscope("block") acq_rel
        ret <4 x i64> %retval
}

define <8 x i64> @usub_cond_acq_rel_v8i64_global_cta(ptr addrspace(1) %addr, <8 x i64> %val) {
; SM90-LABEL: usub_cond_acq_rel_v8i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<13>;
; SM90-NEXT:    .reg .b64 %rd<58>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd17, [usub_cond_acq_rel_v8i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd3, %rd4}, [usub_cond_acq_rel_v8i64_global_cta_param_1+48];
; SM90-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [usub_cond_acq_rel_v8i64_global_cta_param_1+32];
; SM90-NEXT:    ld.param.v2.b64 {%rd5, %rd6}, [usub_cond_acq_rel_v8i64_global_cta_param_1];
; SM90-NEXT:    ld.param.v2.b64 {%rd7, %rd8}, [usub_cond_acq_rel_v8i64_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd18, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd18, %rd18};
; SM90-NEXT:    mov.b128 swap, {%rd18, %rd18};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd50, %rd51}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB223_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    mov.b64 %rd10, %rd51;
; SM90-NEXT:    mov.b64 %rd9, %rd50;
; SM90-NEXT:    setp.ge.u64 %p1, %rd10, %rd6;
; SM90-NEXT:    setp.ge.u64 %p2, %rd9, %rd5;
; SM90-NEXT:    sub.s64 %rd19, %rd10, %rd6;
; SM90-NEXT:    sub.s64 %rd20, %rd9, %rd5;
; SM90-NEXT:    selp.b64 %rd21, %rd20, %rd9, %p2;
; SM90-NEXT:    selp.b64 %rd22, %rd19, %rd10, %p1;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd9, %rd10};
; SM90-NEXT:    mov.b128 swap, {%rd21, %rd22};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd50, %rd51}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd51, %rd10;
; SM90-NEXT:    xor.b64 %rd24, %rd50, %rd9;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    setp.ne.b64 %p3, %rd25, 0;
; SM90-NEXT:    @%p3 bra $L__BB223_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd26, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd26, %rd26};
; SM90-NEXT:    mov.b128 swap, {%rd26, %rd26};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd52, %rd53}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB223_3: // %atomicrmw.start6
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    mov.b64 %rd12, %rd53;
; SM90-NEXT:    mov.b64 %rd11, %rd52;
; SM90-NEXT:    setp.ge.u64 %p4, %rd12, %rd8;
; SM90-NEXT:    setp.ge.u64 %p5, %rd11, %rd7;
; SM90-NEXT:    sub.s64 %rd27, %rd12, %rd8;
; SM90-NEXT:    sub.s64 %rd28, %rd11, %rd7;
; SM90-NEXT:    selp.b64 %rd29, %rd28, %rd11, %p5;
; SM90-NEXT:    selp.b64 %rd30, %rd27, %rd12, %p4;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd11, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd29, %rd30};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd52, %rd53}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd31, %rd53, %rd12;
; SM90-NEXT:    xor.b64 %rd32, %rd52, %rd11;
; SM90-NEXT:    or.b64 %rd33, %rd32, %rd31;
; SM90-NEXT:    setp.ne.b64 %p6, %rd33, 0;
; SM90-NEXT:    @%p6 bra $L__BB223_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end5
; SM90-NEXT:    mov.b64 %rd34, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd34, %rd34};
; SM90-NEXT:    mov.b128 swap, {%rd34, %rd34};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+32], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd54, %rd55}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB223_5: // %atomicrmw.start16
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    setp.ge.u64 %p7, %rd55, %rd2;
; SM90-NEXT:    setp.ge.u64 %p8, %rd54, %rd1;
; SM90-NEXT:    sub.s64 %rd35, %rd55, %rd2;
; SM90-NEXT:    sub.s64 %rd36, %rd54, %rd1;
; SM90-NEXT:    selp.b64 %rd37, %rd36, %rd54, %p8;
; SM90-NEXT:    selp.b64 %rd38, %rd35, %rd55, %p7;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd54, %rd55};
; SM90-NEXT:    mov.b128 swap, {%rd37, %rd38};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+32], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd13, %rd14}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd39, %rd14, %rd55;
; SM90-NEXT:    xor.b64 %rd40, %rd13, %rd54;
; SM90-NEXT:    or.b64 %rd41, %rd40, %rd39;
; SM90-NEXT:    setp.ne.b64 %p9, %rd41, 0;
; SM90-NEXT:    mov.b64 %rd54, %rd13;
; SM90-NEXT:    mov.b64 %rd55, %rd14;
; SM90-NEXT:    @%p9 bra $L__BB223_5;
; SM90-NEXT:  // %bb.6: // %atomicrmw.end15
; SM90-NEXT:    mov.b64 %rd42, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd42, %rd42};
; SM90-NEXT:    mov.b128 swap, {%rd42, %rd42};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+48], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd56, %rd57}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB223_7: // %atomicrmw.start22
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    setp.ge.u64 %p10, %rd57, %rd4;
; SM90-NEXT:    setp.ge.u64 %p11, %rd56, %rd3;
; SM90-NEXT:    sub.s64 %rd43, %rd57, %rd4;
; SM90-NEXT:    sub.s64 %rd44, %rd56, %rd3;
; SM90-NEXT:    selp.b64 %rd45, %rd44, %rd56, %p11;
; SM90-NEXT:    selp.b64 %rd46, %rd43, %rd57, %p10;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd56, %rd57};
; SM90-NEXT:    mov.b128 swap, {%rd45, %rd46};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+48], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd15, %rd16}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd47, %rd16, %rd57;
; SM90-NEXT:    xor.b64 %rd48, %rd15, %rd56;
; SM90-NEXT:    or.b64 %rd49, %rd48, %rd47;
; SM90-NEXT:    setp.ne.b64 %p12, %rd49, 0;
; SM90-NEXT:    mov.b64 %rd56, %rd15;
; SM90-NEXT:    mov.b64 %rd57, %rd16;
; SM90-NEXT:    @%p12 bra $L__BB223_7;
; SM90-NEXT:  // %bb.8: // %atomicrmw.end21
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+48], {%rd15, %rd16};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+32], {%rd13, %rd14};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd50, %rd51};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd52, %rd53};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_cond ptr  addrspace(1) %addr, <8 x i64> %val syncscope("block") acq_rel
        ret <8 x i64> %retval
}

define <1 x i8> @usub_sat_acq_rel_v1i8_global_cta(ptr addrspace(1) %addr, <1 x i8> %val) {
; SM90-LABEL: usub_sat_acq_rel_v1i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<6>;
; SM90-NEXT:    .reg .b32 %r<15>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b8 %rs1, [usub_sat_acq_rel_v1i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd2, [usub_sat_acq_rel_v1i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r4, %rd2;
; SM90-NEXT:    and.b32 %r5, %r4, 3;
; SM90-NEXT:    shl.b32 %r1, %r5, 3;
; SM90-NEXT:    mov.b32 %r6, 255;
; SM90-NEXT:    shl.b32 %r7, %r6, %r1;
; SM90-NEXT:    not.b32 %r2, %r7;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r14, [%rd1];
; SM90-NEXT:  $L__BB224_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r8, %r14, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r8;
; SM90-NEXT:    and.b16 %rs3, %rs2, 255;
; SM90-NEXT:    max.u16 %rs4, %rs3, %rs1;
; SM90-NEXT:    sub.s16 %rs5, %rs4, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r9, %rs5;
; SM90-NEXT:    shl.b32 %r10, %r9, %r1;
; SM90-NEXT:    and.b32 %r11, %r14, %r2;
; SM90-NEXT:    or.b32 %r12, %r11, %r10;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r14, %r12;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r14;
; SM90-NEXT:    mov.b32 %r14, %r3;
; SM90-NEXT:    @%p1 bra $L__BB224_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r13, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b8 [func_retval0], %r13;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_sat ptr  addrspace(1) %addr, <1 x i8> %val syncscope("block") acq_rel
        ret <1 x i8> %retval
}

define <2 x i8> @usub_sat_acq_rel_v2i8_global_cta(ptr addrspace(1) %addr, <2 x i8> %val) {
; SM90-LABEL: usub_sat_acq_rel_v2i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<13>;
; SM90-NEXT:    .reg .b32 %r<19>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b8 {%rs1, %rs2}, [usub_sat_acq_rel_v2i8_global_cta_param_1];
; SM90-NEXT:    mov.b32 %r4, {%rs1, %rs2};
; SM90-NEXT:    ld.param.b64 %rd2, [usub_sat_acq_rel_v2i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:    and.b32 %r6, %r5, 3;
; SM90-NEXT:    shl.b32 %r1, %r6, 3;
; SM90-NEXT:    mov.b32 %r7, 65535;
; SM90-NEXT:    shl.b32 %r8, %r7, %r1;
; SM90-NEXT:    not.b32 %r2, %r8;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r18, [%rd1];
; SM90-NEXT:    mov.b32 {%rs7, %rs8}, %r4;
; SM90-NEXT:  $L__BB225_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r9, %r18, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs3, %r9;
; SM90-NEXT:    shr.u16 %rs4, %rs3, 8;
; SM90-NEXT:    mov.b32 %r10, {%rs3, %rs4};
; SM90-NEXT:    and.b32 %r11, %r10, 16711935;
; SM90-NEXT:    max.u16x2 %r12, %r11, %r4;
; SM90-NEXT:    mov.b32 {%rs5, %rs6}, %r12;
; SM90-NEXT:    sub.s16 %rs9, %rs5, %rs7;
; SM90-NEXT:    sub.s16 %rs10, %rs6, %rs8;
; SM90-NEXT:    shl.b16 %rs11, %rs10, 8;
; SM90-NEXT:    or.b16 %rs12, %rs9, %rs11;
; SM90-NEXT:    cvt.u32.u16 %r13, %rs12;
; SM90-NEXT:    shl.b32 %r14, %r13, %r1;
; SM90-NEXT:    and.b32 %r15, %r18, %r2;
; SM90-NEXT:    or.b32 %r16, %r15, %r14;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r18, %r16;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r18;
; SM90-NEXT:    mov.b32 %r18, %r3;
; SM90-NEXT:    @%p1 bra $L__BB225_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r17, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r17;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_sat ptr  addrspace(1) %addr, <2 x i8> %val syncscope("block") acq_rel
        ret <2 x i8> %retval
}

define <4 x i8> @usub_sat_acq_rel_v4i8_global_cta(ptr addrspace(1) %addr, <4 x i8> %val) {
; SM90-LABEL: usub_sat_acq_rel_v4i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<17>;
; SM90-NEXT:    .reg .b32 %r<19>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [usub_sat_acq_rel_v4i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [usub_sat_acq_rel_v4i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r18, [%rd1];
; SM90-NEXT:    prmt.b32 %r3, %r2, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs1, %r3;
; SM90-NEXT:    prmt.b32 %r6, %r2, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs5, %r6;
; SM90-NEXT:    prmt.b32 %r10, %r2, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs9, %r10;
; SM90-NEXT:    prmt.b32 %r13, %r2, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs13, %r13;
; SM90-NEXT:  $L__BB226_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    prmt.b32 %r4, %r18, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r4;
; SM90-NEXT:    max.u16 %rs3, %rs2, %rs1;
; SM90-NEXT:    sub.s16 %rs4, %rs3, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r5, %rs4;
; SM90-NEXT:    prmt.b32 %r7, %r18, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs6, %r7;
; SM90-NEXT:    max.u16 %rs7, %rs6, %rs5;
; SM90-NEXT:    sub.s16 %rs8, %rs7, %rs5;
; SM90-NEXT:    cvt.u32.u16 %r8, %rs8;
; SM90-NEXT:    prmt.b32 %r9, %r8, %r5, 0x3340U;
; SM90-NEXT:    prmt.b32 %r11, %r18, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs10, %r11;
; SM90-NEXT:    max.u16 %rs11, %rs10, %rs9;
; SM90-NEXT:    sub.s16 %rs12, %rs11, %rs9;
; SM90-NEXT:    cvt.u32.u16 %r12, %rs12;
; SM90-NEXT:    prmt.b32 %r14, %r18, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs14, %r14;
; SM90-NEXT:    max.u16 %rs15, %rs14, %rs13;
; SM90-NEXT:    sub.s16 %rs16, %rs15, %rs13;
; SM90-NEXT:    cvt.u32.u16 %r15, %rs16;
; SM90-NEXT:    prmt.b32 %r16, %r15, %r12, 0x3340U;
; SM90-NEXT:    prmt.b32 %r17, %r16, %r9, 0x5410U;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r18, %r17;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r18;
; SM90-NEXT:    mov.b32 %r18, %r1;
; SM90-NEXT:    @%p1 bra $L__BB226_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_sat ptr  addrspace(1) %addr, <4 x i8> %val syncscope("block") acq_rel
        ret <4 x i8> %retval
}

define <8 x i8> @usub_sat_acq_rel_v8i8_global_cta(ptr addrspace(1) %addr, <8 x i8> %val) {
; SM90-LABEL: usub_sat_acq_rel_v8i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<33>;
; SM90-NEXT:    .reg .b32 %r<35>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [usub_sat_acq_rel_v8i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [usub_sat_acq_rel_v8i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r34}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r33, %rd2;
; SM90-NEXT:    prmt.b32 %r3, %r1, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs1, %r3;
; SM90-NEXT:    prmt.b32 %r6, %r1, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs5, %r6;
; SM90-NEXT:    prmt.b32 %r10, %r1, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs9, %r10;
; SM90-NEXT:    prmt.b32 %r13, %r1, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs13, %r13;
; SM90-NEXT:    prmt.b32 %r18, %r2, 0, 0x7773U;
; SM90-NEXT:    prmt.b32 %r21, %r2, 0, 0x7772U;
; SM90-NEXT:  $L__BB227_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    prmt.b32 %r4, %r33, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r4;
; SM90-NEXT:    max.u16 %rs3, %rs2, %rs1;
; SM90-NEXT:    sub.s16 %rs4, %rs3, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r5, %rs4;
; SM90-NEXT:    prmt.b32 %r7, %r33, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs6, %r7;
; SM90-NEXT:    max.u16 %rs7, %rs6, %rs5;
; SM90-NEXT:    sub.s16 %rs8, %rs7, %rs5;
; SM90-NEXT:    cvt.u32.u16 %r8, %rs8;
; SM90-NEXT:    prmt.b32 %r9, %r8, %r5, 0x3340U;
; SM90-NEXT:    prmt.b32 %r11, %r33, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs10, %r11;
; SM90-NEXT:    max.u16 %rs11, %rs10, %rs9;
; SM90-NEXT:    sub.s16 %rs12, %rs11, %rs9;
; SM90-NEXT:    cvt.u32.u16 %r12, %rs12;
; SM90-NEXT:    prmt.b32 %r14, %r33, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs14, %r14;
; SM90-NEXT:    max.u16 %rs15, %rs14, %rs13;
; SM90-NEXT:    sub.s16 %rs16, %rs15, %rs13;
; SM90-NEXT:    cvt.u32.u16 %r15, %rs16;
; SM90-NEXT:    prmt.b32 %r16, %r15, %r12, 0x3340U;
; SM90-NEXT:    prmt.b32 %r17, %r16, %r9, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r17;
; SM90-NEXT:    cvt.u16.u32 %rs17, %r18;
; SM90-NEXT:    prmt.b32 %r19, %r34, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs18, %r19;
; SM90-NEXT:    max.u16 %rs19, %rs18, %rs17;
; SM90-NEXT:    sub.s16 %rs20, %rs19, %rs17;
; SM90-NEXT:    cvt.u32.u16 %r20, %rs20;
; SM90-NEXT:    cvt.u16.u32 %rs21, %r21;
; SM90-NEXT:    prmt.b32 %r22, %r34, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs22, %r22;
; SM90-NEXT:    max.u16 %rs23, %rs22, %rs21;
; SM90-NEXT:    sub.s16 %rs24, %rs23, %rs21;
; SM90-NEXT:    cvt.u32.u16 %r23, %rs24;
; SM90-NEXT:    prmt.b32 %r24, %r23, %r20, 0x3340U;
; SM90-NEXT:    prmt.b32 %r25, %r2, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs25, %r25;
; SM90-NEXT:    prmt.b32 %r26, %r34, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs26, %r26;
; SM90-NEXT:    max.u16 %rs27, %rs26, %rs25;
; SM90-NEXT:    sub.s16 %rs28, %rs27, %rs25;
; SM90-NEXT:    cvt.u32.u16 %r27, %rs28;
; SM90-NEXT:    prmt.b32 %r28, %r2, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs29, %r28;
; SM90-NEXT:    prmt.b32 %r29, %r34, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs30, %r29;
; SM90-NEXT:    max.u16 %rs31, %rs30, %rs29;
; SM90-NEXT:    sub.s16 %rs32, %rs31, %rs29;
; SM90-NEXT:    cvt.u32.u16 %r30, %rs32;
; SM90-NEXT:    prmt.b32 %r31, %r30, %r27, 0x3340U;
; SM90-NEXT:    prmt.b32 %r32, %r31, %r24, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r32;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r33;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r34;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r34}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r33, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB227_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r33, %r34};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_sat ptr  addrspace(1) %addr, <8 x i8> %val syncscope("block") acq_rel
        ret <8 x i8> %retval
}

define <1 x i16> @usub_sat_acq_rel_v1i16_global_cta(ptr addrspace(1) %addr, <1 x i16> %val) {
; SM90-LABEL: usub_sat_acq_rel_v1i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<5>;
; SM90-NEXT:    .reg .b32 %r<15>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [usub_sat_acq_rel_v1i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b16 %rs1, [usub_sat_acq_rel_v1i16_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r4, %rd2;
; SM90-NEXT:    and.b32 %r5, %r4, 3;
; SM90-NEXT:    shl.b32 %r1, %r5, 3;
; SM90-NEXT:    mov.b32 %r6, 65535;
; SM90-NEXT:    shl.b32 %r7, %r6, %r1;
; SM90-NEXT:    not.b32 %r2, %r7;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r14, [%rd1];
; SM90-NEXT:  $L__BB228_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r8, %r14, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r8;
; SM90-NEXT:    max.u16 %rs3, %rs2, %rs1;
; SM90-NEXT:    sub.s16 %rs4, %rs3, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r9, %rs4;
; SM90-NEXT:    shl.b32 %r10, %r9, %r1;
; SM90-NEXT:    and.b32 %r11, %r14, %r2;
; SM90-NEXT:    or.b32 %r12, %r11, %r10;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r14, %r12;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r14;
; SM90-NEXT:    mov.b32 %r14, %r3;
; SM90-NEXT:    @%p1 bra $L__BB228_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r13, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r13;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_sat ptr  addrspace(1) %addr, <1 x i16> %val syncscope("block") acq_rel
        ret <1 x i16> %retval
}

define <2 x i16> @usub_sat_acq_rel_v2i16_global_cta(ptr addrspace(1) %addr, <2 x i16> %val) {
; SM90-LABEL: usub_sat_acq_rel_v2i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<7>;
; SM90-NEXT:    .reg .b32 %r<6>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [usub_sat_acq_rel_v2i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [usub_sat_acq_rel_v2i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r5, [%rd1];
; SM90-NEXT:    mov.b32 {%rs3, %rs4}, %r2;
; SM90-NEXT:  $L__BB229_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.u16x2 %r3, %r5, %r2;
; SM90-NEXT:    mov.b32 {%rs1, %rs2}, %r3;
; SM90-NEXT:    sub.s16 %rs5, %rs2, %rs4;
; SM90-NEXT:    sub.s16 %rs6, %rs1, %rs3;
; SM90-NEXT:    mov.b32 %r4, {%rs6, %rs5};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r5, %r4;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r5;
; SM90-NEXT:    mov.b32 %r5, %r1;
; SM90-NEXT:    @%p1 bra $L__BB229_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_sat ptr  addrspace(1) %addr, <2 x i16> %val syncscope("block") acq_rel
        ret <2 x i16> %retval
}

define <4 x i16> @usub_sat_acq_rel_v4i16_global_cta(ptr addrspace(1) %addr, <4 x i16> %val) {
; SM90-LABEL: usub_sat_acq_rel_v4i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<13>;
; SM90-NEXT:    .reg .b32 %r<9>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [usub_sat_acq_rel_v4i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [usub_sat_acq_rel_v4i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r8}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd2;
; SM90-NEXT:    mov.b32 {%rs3, %rs4}, %r1;
; SM90-NEXT:    mov.b32 {%rs9, %rs10}, %r2;
; SM90-NEXT:  $L__BB230_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.u16x2 %r3, %r7, %r1;
; SM90-NEXT:    mov.b32 {%rs1, %rs2}, %r3;
; SM90-NEXT:    sub.s16 %rs5, %rs2, %rs4;
; SM90-NEXT:    sub.s16 %rs6, %rs1, %rs3;
; SM90-NEXT:    mov.b32 %r4, {%rs6, %rs5};
; SM90-NEXT:    cvt.u64.u32 %rd3, %r4;
; SM90-NEXT:    max.u16x2 %r5, %r8, %r2;
; SM90-NEXT:    mov.b32 {%rs7, %rs8}, %r5;
; SM90-NEXT:    sub.s16 %rs11, %rs8, %rs10;
; SM90-NEXT:    sub.s16 %rs12, %rs7, %rs9;
; SM90-NEXT:    mov.b32 %r6, {%rs12, %rs11};
; SM90-NEXT:    cvt.u64.u32 %rd4, %r6;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r7;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r8;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r8}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB230_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r7, %r8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_sat ptr  addrspace(1) %addr, <4 x i16> %val syncscope("block") acq_rel
        ret <4 x i16> %retval
}

define <8 x i16> @usub_sat_acq_rel_v8i16_global_cta(ptr addrspace(1) %addr, <8 x i16> %val) {
; SM90-LABEL: usub_sat_acq_rel_v8i16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<25>;
; SM90-NEXT:    .reg .b32 %r<17>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [usub_sat_acq_rel_v8i16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [usub_sat_acq_rel_v8i16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r16}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r15, %rd4;
; SM90-NEXT:    mov.b64 {_, %r14}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r13, %rd3;
; SM90-NEXT:    mov.b32 {%rs3, %rs4}, %r1;
; SM90-NEXT:    mov.b32 {%rs9, %rs10}, %r2;
; SM90-NEXT:  $L__BB231_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.u16x2 %r5, %r13, %r1;
; SM90-NEXT:    mov.b32 {%rs1, %rs2}, %r5;
; SM90-NEXT:    sub.s16 %rs5, %rs2, %rs4;
; SM90-NEXT:    sub.s16 %rs6, %rs1, %rs3;
; SM90-NEXT:    mov.b32 %r6, {%rs6, %rs5};
; SM90-NEXT:    cvt.u64.u32 %rd5, %r6;
; SM90-NEXT:    max.u16x2 %r7, %r14, %r2;
; SM90-NEXT:    mov.b32 {%rs7, %rs8}, %r7;
; SM90-NEXT:    sub.s16 %rs11, %rs8, %rs10;
; SM90-NEXT:    sub.s16 %rs12, %rs7, %rs9;
; SM90-NEXT:    mov.b32 %r8, {%rs12, %rs11};
; SM90-NEXT:    cvt.u64.u32 %rd6, %r8;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    max.u16x2 %r9, %r15, %r3;
; SM90-NEXT:    mov.b32 {%rs13, %rs14}, %r9;
; SM90-NEXT:    mov.b32 {%rs15, %rs16}, %r3;
; SM90-NEXT:    sub.s16 %rs17, %rs14, %rs16;
; SM90-NEXT:    sub.s16 %rs18, %rs13, %rs15;
; SM90-NEXT:    mov.b32 %r10, {%rs18, %rs17};
; SM90-NEXT:    cvt.u64.u32 %rd9, %r10;
; SM90-NEXT:    max.u16x2 %r11, %r16, %r4;
; SM90-NEXT:    mov.b32 {%rs19, %rs20}, %r11;
; SM90-NEXT:    mov.b32 {%rs21, %rs22}, %r4;
; SM90-NEXT:    sub.s16 %rs23, %rs20, %rs22;
; SM90-NEXT:    sub.s16 %rs24, %rs19, %rs21;
; SM90-NEXT:    mov.b32 %r12, {%rs24, %rs23};
; SM90-NEXT:    cvt.u64.u32 %rd10, %r12;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r13;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r14;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r15;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r16;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r16}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r15, %rd22;
; SM90-NEXT:    mov.b64 {_, %r14}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r13, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB231_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r13, %r14, %r15, %r16};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_sat ptr  addrspace(1) %addr, <8 x i16> %val syncscope("block") acq_rel
        ret <8 x i16> %retval
}

define <1 x i32> @usub_sat_acq_rel_v1i32_global_cta(ptr addrspace(1) %addr, <1 x i32> %val) {
; SM90-LABEL: usub_sat_acq_rel_v1i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<6>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [usub_sat_acq_rel_v1i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b32 %r1, [usub_sat_acq_rel_v1i32_global_cta_param_1];
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r5, [%rd1];
; SM90-NEXT:  $L__BB232_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.u32 %r3, %r5, %r1;
; SM90-NEXT:    sub.s32 %r4, %r3, %r1;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r2, [%rd1], %r5, %r4;
; SM90-NEXT:    setp.ne.b32 %p1, %r2, %r5;
; SM90-NEXT:    mov.b32 %r5, %r2;
; SM90-NEXT:    @%p1 bra $L__BB232_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_sat ptr  addrspace(1) %addr, <1 x i32> %val syncscope("block") acq_rel
        ret <1 x i32> %retval
}

define <2 x i32> @usub_sat_acq_rel_v2i32_global_cta(ptr addrspace(1) %addr, <2 x i32> %val) {
; SM90-LABEL: usub_sat_acq_rel_v2i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<9>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [usub_sat_acq_rel_v2i32_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [usub_sat_acq_rel_v2i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r8}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd2;
; SM90-NEXT:  $L__BB233_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.u32 %r3, %r7, %r1;
; SM90-NEXT:    sub.s32 %r4, %r3, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r4;
; SM90-NEXT:    max.u32 %r5, %r8, %r2;
; SM90-NEXT:    sub.s32 %r6, %r5, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r6;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r7;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r8;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r8}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB233_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r7, %r8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_sat ptr  addrspace(1) %addr, <2 x i32> %val syncscope("block") acq_rel
        ret <2 x i32> %retval
}

define <4 x i32> @usub_sat_acq_rel_v4i32_global_cta(ptr addrspace(1) %addr, <4 x i32> %val) {
; SM90-LABEL: usub_sat_acq_rel_v4i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<17>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [usub_sat_acq_rel_v4i32_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [usub_sat_acq_rel_v4i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r16}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r15, %rd4;
; SM90-NEXT:    mov.b64 {_, %r14}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r13, %rd3;
; SM90-NEXT:  $L__BB234_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.u32 %r5, %r13, %r1;
; SM90-NEXT:    sub.s32 %r6, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd5, %r6;
; SM90-NEXT:    max.u32 %r7, %r14, %r2;
; SM90-NEXT:    sub.s32 %r8, %r7, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r8;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    max.u32 %r9, %r15, %r3;
; SM90-NEXT:    sub.s32 %r10, %r9, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r10;
; SM90-NEXT:    max.u32 %r11, %r16, %r4;
; SM90-NEXT:    sub.s32 %r12, %r11, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r12;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r13;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r14;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r15;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r16;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r16}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r15, %rd22;
; SM90-NEXT:    mov.b64 {_, %r14}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r13, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB234_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r13, %r14, %r15, %r16};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_sat ptr  addrspace(1) %addr, <4 x i32> %val syncscope("block") acq_rel
        ret <4 x i32> %retval
}

define <8 x i32> @usub_sat_acq_rel_v8i32_global_cta(ptr addrspace(1) %addr, <8 x i32> %val) {
; SM90-LABEL: usub_sat_acq_rel_v8i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<3>;
; SM90-NEXT:    .reg .b32 %r<33>;
; SM90-NEXT:    .reg .b64 %rd<50>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [usub_sat_acq_rel_v8i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [usub_sat_acq_rel_v8i32_global_cta_param_1];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [usub_sat_acq_rel_v8i32_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r28}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r27, %rd4;
; SM90-NEXT:    mov.b64 {_, %r26}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r25, %rd3;
; SM90-NEXT:  $L__BB235_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.u32 %r9, %r25, %r1;
; SM90-NEXT:    sub.s32 %r10, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd5, %r10;
; SM90-NEXT:    max.u32 %r11, %r26, %r2;
; SM90-NEXT:    sub.s32 %r12, %r11, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r12;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    max.u32 %r13, %r27, %r3;
; SM90-NEXT:    sub.s32 %r14, %r13, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r14;
; SM90-NEXT:    max.u32 %r15, %r28, %r4;
; SM90-NEXT:    sub.s32 %r16, %r15, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r16;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r25;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r26;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r27;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r28;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r28}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r27, %rd22;
; SM90-NEXT:    mov.b64 {_, %r26}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r25, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB235_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd26, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd26, %rd26};
; SM90-NEXT:    mov.b128 swap, {%rd26, %rd26};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd27, %rd28}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r32}, %rd28;
; SM90-NEXT:    cvt.u32.u64 %r31, %rd28;
; SM90-NEXT:    mov.b64 {_, %r30}, %rd27;
; SM90-NEXT:    cvt.u32.u64 %r29, %rd27;
; SM90-NEXT:  $L__BB235_3: // %atomicrmw.start2
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.u32 %r17, %r29, %r5;
; SM90-NEXT:    sub.s32 %r18, %r17, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd29, %r18;
; SM90-NEXT:    max.u32 %r19, %r30, %r6;
; SM90-NEXT:    sub.s32 %r20, %r19, %r6;
; SM90-NEXT:    cvt.u64.u32 %rd30, %r20;
; SM90-NEXT:    shl.b64 %rd31, %rd30, 32;
; SM90-NEXT:    or.b64 %rd32, %rd29, %rd31;
; SM90-NEXT:    max.u32 %r21, %r31, %r7;
; SM90-NEXT:    sub.s32 %r22, %r21, %r7;
; SM90-NEXT:    cvt.u64.u32 %rd33, %r22;
; SM90-NEXT:    max.u32 %r23, %r32, %r8;
; SM90-NEXT:    sub.s32 %r24, %r23, %r8;
; SM90-NEXT:    cvt.u64.u32 %rd34, %r24;
; SM90-NEXT:    shl.b64 %rd35, %rd34, 32;
; SM90-NEXT:    or.b64 %rd36, %rd33, %rd35;
; SM90-NEXT:    cvt.u64.u32 %rd37, %r29;
; SM90-NEXT:    cvt.u64.u32 %rd38, %r30;
; SM90-NEXT:    shl.b64 %rd39, %rd38, 32;
; SM90-NEXT:    or.b64 %rd40, %rd37, %rd39;
; SM90-NEXT:    cvt.u64.u32 %rd41, %r31;
; SM90-NEXT:    cvt.u64.u32 %rd42, %r32;
; SM90-NEXT:    shl.b64 %rd43, %rd42, 32;
; SM90-NEXT:    or.b64 %rd44, %rd41, %rd43;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd40, %rd44};
; SM90-NEXT:    mov.b128 swap, {%rd32, %rd36};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd45, %rd46}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd47, %rd46, %rd44;
; SM90-NEXT:    xor.b64 %rd48, %rd45, %rd40;
; SM90-NEXT:    or.b64 %rd49, %rd48, %rd47;
; SM90-NEXT:    mov.b64 {_, %r32}, %rd46;
; SM90-NEXT:    cvt.u32.u64 %r31, %rd46;
; SM90-NEXT:    mov.b64 {_, %r30}, %rd45;
; SM90-NEXT:    cvt.u32.u64 %r29, %rd45;
; SM90-NEXT:    setp.ne.b64 %p2, %rd49, 0;
; SM90-NEXT:    @%p2 bra $L__BB235_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end1
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r29, %r30, %r31, %r32};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r25, %r26, %r27, %r28};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_sat ptr  addrspace(1) %addr, <8 x i32> %val syncscope("block") acq_rel
        ret <8 x i32> %retval
}

define <1 x i64> @usub_sat_acq_rel_v1i64_global_cta(ptr addrspace(1) %addr, <1 x i64> %val) {
; SM90-LABEL: usub_sat_acq_rel_v1i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b64 %rd<7>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd3, [usub_sat_acq_rel_v1i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b64 %rd1, [usub_sat_acq_rel_v1i64_global_cta_param_1];
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd6, [%rd3];
; SM90-NEXT:  $L__BB236_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.u64 %rd4, %rd6, %rd1;
; SM90-NEXT:    sub.s64 %rd5, %rd4, %rd1;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd2, [%rd3], %rd6, %rd5;
; SM90-NEXT:    setp.ne.b64 %p1, %rd2, %rd6;
; SM90-NEXT:    mov.b64 %rd6, %rd2;
; SM90-NEXT:    @%p1 bra $L__BB236_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b64 [func_retval0], %rd2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_sat ptr  addrspace(1) %addr, <1 x i64> %val syncscope("block") acq_rel
        ret <1 x i64> %retval
}

define <2 x i64> @usub_sat_acq_rel_v2i64_global_cta(ptr addrspace(1) %addr, <2 x i64> %val) {
; SM90-LABEL: usub_sat_acq_rel_v2i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b64 %rd<16>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [usub_sat_acq_rel_v2i64_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd3, [usub_sat_acq_rel_v2i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd6, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd6, %rd6};
; SM90-NEXT:    mov.b128 swap, {%rd6, %rd6};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd3], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd14, %rd15}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB237_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.u64 %rd7, %rd14, %rd4;
; SM90-NEXT:    sub.s64 %rd8, %rd7, %rd4;
; SM90-NEXT:    max.u64 %rd9, %rd15, %rd5;
; SM90-NEXT:    sub.s64 %rd10, %rd9, %rd5;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd14, %rd15};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd10};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd3], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd1, %rd2}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd11, %rd2, %rd15;
; SM90-NEXT:    xor.b64 %rd12, %rd1, %rd14;
; SM90-NEXT:    or.b64 %rd13, %rd12, %rd11;
; SM90-NEXT:    setp.ne.b64 %p1, %rd13, 0;
; SM90-NEXT:    mov.b64 %rd14, %rd1;
; SM90-NEXT:    mov.b64 %rd15, %rd2;
; SM90-NEXT:    @%p1 bra $L__BB237_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd1, %rd2};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_sat ptr  addrspace(1) %addr, <2 x i64> %val syncscope("block") acq_rel
        ret <2 x i64> %retval
}

define <4 x i64> @usub_sat_acq_rel_v4i64_global_cta(ptr addrspace(1) %addr, <4 x i64> %val) {
; SM90-LABEL: usub_sat_acq_rel_v4i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<3>;
; SM90-NEXT:    .reg .b64 %rd<30>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd9, [usub_sat_acq_rel_v4i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [usub_sat_acq_rel_v4i64_global_cta_param_1];
; SM90-NEXT:    ld.param.v2.b64 {%rd3, %rd4}, [usub_sat_acq_rel_v4i64_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd10, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd10, %rd10};
; SM90-NEXT:    mov.b128 swap, {%rd10, %rd10};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd26, %rd27}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB238_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.u64 %rd11, %rd26, %rd1;
; SM90-NEXT:    sub.s64 %rd12, %rd11, %rd1;
; SM90-NEXT:    max.u64 %rd13, %rd27, %rd2;
; SM90-NEXT:    sub.s64 %rd14, %rd13, %rd2;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd26, %rd27};
; SM90-NEXT:    mov.b128 swap, {%rd12, %rd14};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd5, %rd6}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd15, %rd6, %rd27;
; SM90-NEXT:    xor.b64 %rd16, %rd5, %rd26;
; SM90-NEXT:    or.b64 %rd17, %rd16, %rd15;
; SM90-NEXT:    setp.ne.b64 %p1, %rd17, 0;
; SM90-NEXT:    mov.b64 %rd26, %rd5;
; SM90-NEXT:    mov.b64 %rd27, %rd6;
; SM90-NEXT:    @%p1 bra $L__BB238_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd18, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd18, %rd18};
; SM90-NEXT:    mov.b128 swap, {%rd18, %rd18};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd28, %rd29}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB238_3: // %atomicrmw.start2
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.u64 %rd19, %rd28, %rd3;
; SM90-NEXT:    sub.s64 %rd20, %rd19, %rd3;
; SM90-NEXT:    max.u64 %rd21, %rd29, %rd4;
; SM90-NEXT:    sub.s64 %rd22, %rd21, %rd4;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd28, %rd29};
; SM90-NEXT:    mov.b128 swap, {%rd20, %rd22};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd7, %rd8}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd8, %rd29;
; SM90-NEXT:    xor.b64 %rd24, %rd7, %rd28;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    setp.ne.b64 %p2, %rd25, 0;
; SM90-NEXT:    mov.b64 %rd28, %rd7;
; SM90-NEXT:    mov.b64 %rd29, %rd8;
; SM90-NEXT:    @%p2 bra $L__BB238_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end1
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd7, %rd8};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd5, %rd6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_sat ptr  addrspace(1) %addr, <4 x i64> %val syncscope("block") acq_rel
        ret <4 x i64> %retval
}

define <8 x i64> @usub_sat_acq_rel_v8i64_global_cta(ptr addrspace(1) %addr, <8 x i64> %val) {
; SM90-LABEL: usub_sat_acq_rel_v8i64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<5>;
; SM90-NEXT:    .reg .b64 %rd<58>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd17, [usub_sat_acq_rel_v8i64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd3, %rd4}, [usub_sat_acq_rel_v8i64_global_cta_param_1+48];
; SM90-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [usub_sat_acq_rel_v8i64_global_cta_param_1+32];
; SM90-NEXT:    ld.param.v2.b64 {%rd5, %rd6}, [usub_sat_acq_rel_v8i64_global_cta_param_1];
; SM90-NEXT:    ld.param.v2.b64 {%rd7, %rd8}, [usub_sat_acq_rel_v8i64_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd18, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd18, %rd18};
; SM90-NEXT:    mov.b128 swap, {%rd18, %rd18};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd50, %rd51}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB239_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    mov.b64 %rd10, %rd51;
; SM90-NEXT:    mov.b64 %rd9, %rd50;
; SM90-NEXT:    max.u64 %rd19, %rd9, %rd5;
; SM90-NEXT:    sub.s64 %rd20, %rd19, %rd5;
; SM90-NEXT:    max.u64 %rd21, %rd10, %rd6;
; SM90-NEXT:    sub.s64 %rd22, %rd21, %rd6;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd9, %rd10};
; SM90-NEXT:    mov.b128 swap, {%rd20, %rd22};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd50, %rd51}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd51, %rd10;
; SM90-NEXT:    xor.b64 %rd24, %rd50, %rd9;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB239_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd26, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd26, %rd26};
; SM90-NEXT:    mov.b128 swap, {%rd26, %rd26};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd52, %rd53}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB239_3: // %atomicrmw.start6
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    mov.b64 %rd12, %rd53;
; SM90-NEXT:    mov.b64 %rd11, %rd52;
; SM90-NEXT:    max.u64 %rd27, %rd11, %rd7;
; SM90-NEXT:    sub.s64 %rd28, %rd27, %rd7;
; SM90-NEXT:    max.u64 %rd29, %rd12, %rd8;
; SM90-NEXT:    sub.s64 %rd30, %rd29, %rd8;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd11, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd28, %rd30};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd52, %rd53}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd31, %rd53, %rd12;
; SM90-NEXT:    xor.b64 %rd32, %rd52, %rd11;
; SM90-NEXT:    or.b64 %rd33, %rd32, %rd31;
; SM90-NEXT:    setp.ne.b64 %p2, %rd33, 0;
; SM90-NEXT:    @%p2 bra $L__BB239_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end5
; SM90-NEXT:    mov.b64 %rd34, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd34, %rd34};
; SM90-NEXT:    mov.b128 swap, {%rd34, %rd34};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+32], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd54, %rd55}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB239_5: // %atomicrmw.start16
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.u64 %rd35, %rd54, %rd1;
; SM90-NEXT:    sub.s64 %rd36, %rd35, %rd1;
; SM90-NEXT:    max.u64 %rd37, %rd55, %rd2;
; SM90-NEXT:    sub.s64 %rd38, %rd37, %rd2;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd54, %rd55};
; SM90-NEXT:    mov.b128 swap, {%rd36, %rd38};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+32], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd13, %rd14}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd39, %rd14, %rd55;
; SM90-NEXT:    xor.b64 %rd40, %rd13, %rd54;
; SM90-NEXT:    or.b64 %rd41, %rd40, %rd39;
; SM90-NEXT:    setp.ne.b64 %p3, %rd41, 0;
; SM90-NEXT:    mov.b64 %rd54, %rd13;
; SM90-NEXT:    mov.b64 %rd55, %rd14;
; SM90-NEXT:    @%p3 bra $L__BB239_5;
; SM90-NEXT:  // %bb.6: // %atomicrmw.end15
; SM90-NEXT:    mov.b64 %rd42, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd42, %rd42};
; SM90-NEXT:    mov.b128 swap, {%rd42, %rd42};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+48], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd56, %rd57}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB239_7: // %atomicrmw.start22
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.u64 %rd43, %rd56, %rd3;
; SM90-NEXT:    sub.s64 %rd44, %rd43, %rd3;
; SM90-NEXT:    max.u64 %rd45, %rd57, %rd4;
; SM90-NEXT:    sub.s64 %rd46, %rd45, %rd4;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd56, %rd57};
; SM90-NEXT:    mov.b128 swap, {%rd44, %rd46};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+48], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd15, %rd16}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd47, %rd16, %rd57;
; SM90-NEXT:    xor.b64 %rd48, %rd15, %rd56;
; SM90-NEXT:    or.b64 %rd49, %rd48, %rd47;
; SM90-NEXT:    setp.ne.b64 %p4, %rd49, 0;
; SM90-NEXT:    mov.b64 %rd56, %rd15;
; SM90-NEXT:    mov.b64 %rd57, %rd16;
; SM90-NEXT:    @%p4 bra $L__BB239_7;
; SM90-NEXT:  // %bb.8: // %atomicrmw.end21
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+48], {%rd15, %rd16};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+32], {%rd13, %rd14};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd50, %rd51};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd52, %rd53};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise usub_sat ptr  addrspace(1) %addr, <8 x i64> %val syncscope("block") acq_rel
        ret <8 x i64> %retval
}

define <1 x float> @fadd_acq_rel_v1f32_global_cta(ptr addrspace(1) %addr, <1 x float> %val) {
; SM90-LABEL: fadd_acq_rel_v1f32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<3>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [fadd_acq_rel_v1f32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b32 %r1, [fadd_acq_rel_v1f32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.f32 %r2, [%rd1], %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fadd ptr  addrspace(1) %addr, <1 x float> %val syncscope("block") acq_rel
        ret <1 x float> %retval
}

define <2 x float> @fadd_acq_rel_v2f32_global_cta(ptr addrspace(1) %addr, <2 x float> %val) {
; SM90-LABEL: fadd_acq_rel_v2f32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [fadd_acq_rel_v2f32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [fadd_acq_rel_v2f32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.f32 %r3, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.add.f32 %r4, [%rd1+4], %r2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r3, %r4};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fadd ptr  addrspace(1) %addr, <2 x float> %val syncscope("block") acq_rel
        ret <2 x float> %retval
}

define <4 x float> @fadd_acq_rel_v4f32_global_cta(ptr addrspace(1) %addr, <4 x float> %val) {
; SM90-LABEL: fadd_acq_rel_v4f32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<9>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [fadd_acq_rel_v4f32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fadd_acq_rel_v4f32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.f32 %r5, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.add.f32 %r6, [%rd1+4], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.add.f32 %r7, [%rd1+8], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.add.f32 %r8, [%rd1+12], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fadd ptr  addrspace(1) %addr, <4 x float> %val syncscope("block") acq_rel
        ret <4 x float> %retval
}

define <8 x float> @fadd_acq_rel_v8f32_global_cta(ptr addrspace(1) %addr, <8 x float> %val) {
; SM90-LABEL: fadd_acq_rel_v8f32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<17>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [fadd_acq_rel_v8f32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fadd_acq_rel_v8f32_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [fadd_acq_rel_v8f32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.f32 %r9, [%rd1], %r5;
; SM90-NEXT:    atom.relaxed.cta.global.add.f32 %r10, [%rd1+4], %r6;
; SM90-NEXT:    atom.relaxed.cta.global.add.f32 %r11, [%rd1+8], %r7;
; SM90-NEXT:    atom.relaxed.cta.global.add.f32 %r12, [%rd1+12], %r8;
; SM90-NEXT:    atom.relaxed.cta.global.add.f32 %r13, [%rd1+16], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.add.f32 %r14, [%rd1+20], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.add.f32 %r15, [%rd1+24], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.add.f32 %r16, [%rd1+28], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r13, %r14, %r15, %r16};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fadd ptr  addrspace(1) %addr, <8 x float> %val syncscope("block") acq_rel
        ret <8 x float> %retval
}

define <1 x float> @fsub_acq_rel_v1f32_global_cta(ptr addrspace(1) %addr, <1 x float> %val) {
; SM90-LABEL: fsub_acq_rel_v1f32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [fsub_acq_rel_v1f32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b32 %r1, [fsub_acq_rel_v1f32_global_cta_param_1];
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:  $L__BB244_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    sub.rn.f32 %r3, %r4, %r1;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r2, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p1, %r2, %r4;
; SM90-NEXT:    mov.b32 %r4, %r2;
; SM90-NEXT:    @%p1 bra $L__BB244_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fsub ptr  addrspace(1) %addr, <1 x float> %val syncscope("block") acq_rel
        ret <1 x float> %retval
}

define <2 x float> @fsub_acq_rel_v2f32_global_cta(ptr addrspace(1) %addr, <2 x float> %val) {
; SM90-LABEL: fsub_acq_rel_v2f32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [fsub_acq_rel_v2f32_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fsub_acq_rel_v2f32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB245_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    sub.rn.f32 %r3, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r3;
; SM90-NEXT:    sub.rn.f32 %r4, %r6, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r4;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB245_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fsub ptr  addrspace(1) %addr, <2 x float> %val syncscope("block") acq_rel
        ret <2 x float> %retval
}

define <4 x float> @fsub_acq_rel_v4f32_global_cta(ptr addrspace(1) %addr, <4 x float> %val) {
; SM90-LABEL: fsub_acq_rel_v4f32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fsub_acq_rel_v4f32_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fsub_acq_rel_v4f32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB246_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    sub.rn.f32 %r5, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd5, %r5;
; SM90-NEXT:    sub.rn.f32 %r6, %r10, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r6;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    sub.rn.f32 %r7, %r11, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r7;
; SM90-NEXT:    sub.rn.f32 %r8, %r12, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r8;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r10;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r12;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd22;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB246_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fsub ptr  addrspace(1) %addr, <4 x float> %val syncscope("block") acq_rel
        ret <4 x float> %retval
}

define <8 x float> @fsub_acq_rel_v8f32_global_cta(ptr addrspace(1) %addr, <8 x float> %val) {
; SM90-LABEL: fsub_acq_rel_v8f32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<3>;
; SM90-NEXT:    .reg .b32 %r<25>;
; SM90-NEXT:    .reg .b64 %rd<50>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [fsub_acq_rel_v8f32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fsub_acq_rel_v8f32_global_cta_param_1];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [fsub_acq_rel_v8f32_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r20}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r19, %rd4;
; SM90-NEXT:    mov.b64 {_, %r18}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r17, %rd3;
; SM90-NEXT:  $L__BB247_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    sub.rn.f32 %r9, %r17, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd5, %r9;
; SM90-NEXT:    sub.rn.f32 %r10, %r18, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r10;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    sub.rn.f32 %r11, %r19, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r11;
; SM90-NEXT:    sub.rn.f32 %r12, %r20, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r12;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r17;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r18;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r19;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r20;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r20}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r19, %rd22;
; SM90-NEXT:    mov.b64 {_, %r18}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r17, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB247_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd26, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd26, %rd26};
; SM90-NEXT:    mov.b128 swap, {%rd26, %rd26};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd27, %rd28}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r24}, %rd28;
; SM90-NEXT:    cvt.u32.u64 %r23, %rd28;
; SM90-NEXT:    mov.b64 {_, %r22}, %rd27;
; SM90-NEXT:    cvt.u32.u64 %r21, %rd27;
; SM90-NEXT:  $L__BB247_3: // %atomicrmw.start2
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    sub.rn.f32 %r13, %r21, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd29, %r13;
; SM90-NEXT:    sub.rn.f32 %r14, %r22, %r6;
; SM90-NEXT:    cvt.u64.u32 %rd30, %r14;
; SM90-NEXT:    shl.b64 %rd31, %rd30, 32;
; SM90-NEXT:    or.b64 %rd32, %rd29, %rd31;
; SM90-NEXT:    sub.rn.f32 %r15, %r23, %r7;
; SM90-NEXT:    cvt.u64.u32 %rd33, %r15;
; SM90-NEXT:    sub.rn.f32 %r16, %r24, %r8;
; SM90-NEXT:    cvt.u64.u32 %rd34, %r16;
; SM90-NEXT:    shl.b64 %rd35, %rd34, 32;
; SM90-NEXT:    or.b64 %rd36, %rd33, %rd35;
; SM90-NEXT:    cvt.u64.u32 %rd37, %r21;
; SM90-NEXT:    cvt.u64.u32 %rd38, %r22;
; SM90-NEXT:    shl.b64 %rd39, %rd38, 32;
; SM90-NEXT:    or.b64 %rd40, %rd37, %rd39;
; SM90-NEXT:    cvt.u64.u32 %rd41, %r23;
; SM90-NEXT:    cvt.u64.u32 %rd42, %r24;
; SM90-NEXT:    shl.b64 %rd43, %rd42, 32;
; SM90-NEXT:    or.b64 %rd44, %rd41, %rd43;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd40, %rd44};
; SM90-NEXT:    mov.b128 swap, {%rd32, %rd36};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd45, %rd46}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd47, %rd46, %rd44;
; SM90-NEXT:    xor.b64 %rd48, %rd45, %rd40;
; SM90-NEXT:    or.b64 %rd49, %rd48, %rd47;
; SM90-NEXT:    mov.b64 {_, %r24}, %rd46;
; SM90-NEXT:    cvt.u32.u64 %r23, %rd46;
; SM90-NEXT:    mov.b64 {_, %r22}, %rd45;
; SM90-NEXT:    cvt.u32.u64 %r21, %rd45;
; SM90-NEXT:    setp.ne.b64 %p2, %rd49, 0;
; SM90-NEXT:    @%p2 bra $L__BB247_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end1
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r21, %r22, %r23, %r24};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r17, %r18, %r19, %r20};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fsub ptr  addrspace(1) %addr, <8 x float> %val syncscope("block") acq_rel
        ret <8 x float> %retval
}

define <1 x float> @fmin_acq_rel_v1f32_global_cta(ptr addrspace(1) %addr, <1 x float> %val) {
; SM90-LABEL: fmin_acq_rel_v1f32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [fmin_acq_rel_v1f32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b32 %r1, [fmin_acq_rel_v1f32_global_cta_param_1];
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:  $L__BB248_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.f32 %r3, %r4, %r1;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r2, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p1, %r2, %r4;
; SM90-NEXT:    mov.b32 %r4, %r2;
; SM90-NEXT:    @%p1 bra $L__BB248_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmin ptr  addrspace(1) %addr, <1 x float> %val syncscope("block") acq_rel
        ret <1 x float> %retval
}

define <2 x float> @fmin_acq_rel_v2f32_global_cta(ptr addrspace(1) %addr, <2 x float> %val) {
; SM90-LABEL: fmin_acq_rel_v2f32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [fmin_acq_rel_v2f32_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fmin_acq_rel_v2f32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB249_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.f32 %r3, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r3;
; SM90-NEXT:    min.f32 %r4, %r6, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r4;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB249_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmin ptr  addrspace(1) %addr, <2 x float> %val syncscope("block") acq_rel
        ret <2 x float> %retval
}

define <4 x float> @fmin_acq_rel_v4f32_global_cta(ptr addrspace(1) %addr, <4 x float> %val) {
; SM90-LABEL: fmin_acq_rel_v4f32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fmin_acq_rel_v4f32_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fmin_acq_rel_v4f32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB250_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.f32 %r5, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd5, %r5;
; SM90-NEXT:    min.f32 %r6, %r10, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r6;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    min.f32 %r7, %r11, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r7;
; SM90-NEXT:    min.f32 %r8, %r12, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r8;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r10;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r12;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd22;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB250_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmin ptr  addrspace(1) %addr, <4 x float> %val syncscope("block") acq_rel
        ret <4 x float> %retval
}

define <8 x float> @fmin_acq_rel_v8f32_global_cta(ptr addrspace(1) %addr, <8 x float> %val) {
; SM90-LABEL: fmin_acq_rel_v8f32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<3>;
; SM90-NEXT:    .reg .b32 %r<25>;
; SM90-NEXT:    .reg .b64 %rd<50>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [fmin_acq_rel_v8f32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fmin_acq_rel_v8f32_global_cta_param_1];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [fmin_acq_rel_v8f32_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r20}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r19, %rd4;
; SM90-NEXT:    mov.b64 {_, %r18}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r17, %rd3;
; SM90-NEXT:  $L__BB251_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.f32 %r9, %r17, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd5, %r9;
; SM90-NEXT:    min.f32 %r10, %r18, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r10;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    min.f32 %r11, %r19, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r11;
; SM90-NEXT:    min.f32 %r12, %r20, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r12;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r17;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r18;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r19;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r20;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r20}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r19, %rd22;
; SM90-NEXT:    mov.b64 {_, %r18}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r17, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB251_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd26, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd26, %rd26};
; SM90-NEXT:    mov.b128 swap, {%rd26, %rd26};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd27, %rd28}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r24}, %rd28;
; SM90-NEXT:    cvt.u32.u64 %r23, %rd28;
; SM90-NEXT:    mov.b64 {_, %r22}, %rd27;
; SM90-NEXT:    cvt.u32.u64 %r21, %rd27;
; SM90-NEXT:  $L__BB251_3: // %atomicrmw.start2
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.f32 %r13, %r21, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd29, %r13;
; SM90-NEXT:    min.f32 %r14, %r22, %r6;
; SM90-NEXT:    cvt.u64.u32 %rd30, %r14;
; SM90-NEXT:    shl.b64 %rd31, %rd30, 32;
; SM90-NEXT:    or.b64 %rd32, %rd29, %rd31;
; SM90-NEXT:    min.f32 %r15, %r23, %r7;
; SM90-NEXT:    cvt.u64.u32 %rd33, %r15;
; SM90-NEXT:    min.f32 %r16, %r24, %r8;
; SM90-NEXT:    cvt.u64.u32 %rd34, %r16;
; SM90-NEXT:    shl.b64 %rd35, %rd34, 32;
; SM90-NEXT:    or.b64 %rd36, %rd33, %rd35;
; SM90-NEXT:    cvt.u64.u32 %rd37, %r21;
; SM90-NEXT:    cvt.u64.u32 %rd38, %r22;
; SM90-NEXT:    shl.b64 %rd39, %rd38, 32;
; SM90-NEXT:    or.b64 %rd40, %rd37, %rd39;
; SM90-NEXT:    cvt.u64.u32 %rd41, %r23;
; SM90-NEXT:    cvt.u64.u32 %rd42, %r24;
; SM90-NEXT:    shl.b64 %rd43, %rd42, 32;
; SM90-NEXT:    or.b64 %rd44, %rd41, %rd43;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd40, %rd44};
; SM90-NEXT:    mov.b128 swap, {%rd32, %rd36};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd45, %rd46}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd47, %rd46, %rd44;
; SM90-NEXT:    xor.b64 %rd48, %rd45, %rd40;
; SM90-NEXT:    or.b64 %rd49, %rd48, %rd47;
; SM90-NEXT:    mov.b64 {_, %r24}, %rd46;
; SM90-NEXT:    cvt.u32.u64 %r23, %rd46;
; SM90-NEXT:    mov.b64 {_, %r22}, %rd45;
; SM90-NEXT:    cvt.u32.u64 %r21, %rd45;
; SM90-NEXT:    setp.ne.b64 %p2, %rd49, 0;
; SM90-NEXT:    @%p2 bra $L__BB251_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end1
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r21, %r22, %r23, %r24};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r17, %r18, %r19, %r20};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmin ptr  addrspace(1) %addr, <8 x float> %val syncscope("block") acq_rel
        ret <8 x float> %retval
}

define <1 x float> @fmax_acq_rel_v1f32_global_cta(ptr addrspace(1) %addr, <1 x float> %val) {
; SM90-LABEL: fmax_acq_rel_v1f32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [fmax_acq_rel_v1f32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b32 %r1, [fmax_acq_rel_v1f32_global_cta_param_1];
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:  $L__BB252_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.f32 %r3, %r4, %r1;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r2, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p1, %r2, %r4;
; SM90-NEXT:    mov.b32 %r4, %r2;
; SM90-NEXT:    @%p1 bra $L__BB252_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmax ptr  addrspace(1) %addr, <1 x float> %val syncscope("block") acq_rel
        ret <1 x float> %retval
}

define <2 x float> @fmax_acq_rel_v2f32_global_cta(ptr addrspace(1) %addr, <2 x float> %val) {
; SM90-LABEL: fmax_acq_rel_v2f32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [fmax_acq_rel_v2f32_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fmax_acq_rel_v2f32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB253_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.f32 %r3, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r3;
; SM90-NEXT:    max.f32 %r4, %r6, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r4;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB253_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmax ptr  addrspace(1) %addr, <2 x float> %val syncscope("block") acq_rel
        ret <2 x float> %retval
}

define <4 x float> @fmax_acq_rel_v4f32_global_cta(ptr addrspace(1) %addr, <4 x float> %val) {
; SM90-LABEL: fmax_acq_rel_v4f32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fmax_acq_rel_v4f32_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fmax_acq_rel_v4f32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB254_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.f32 %r5, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd5, %r5;
; SM90-NEXT:    max.f32 %r6, %r10, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r6;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    max.f32 %r7, %r11, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r7;
; SM90-NEXT:    max.f32 %r8, %r12, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r8;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r10;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r12;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd22;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB254_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmax ptr  addrspace(1) %addr, <4 x float> %val syncscope("block") acq_rel
        ret <4 x float> %retval
}

define <8 x float> @fmax_acq_rel_v8f32_global_cta(ptr addrspace(1) %addr, <8 x float> %val) {
; SM90-LABEL: fmax_acq_rel_v8f32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<3>;
; SM90-NEXT:    .reg .b32 %r<25>;
; SM90-NEXT:    .reg .b64 %rd<50>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [fmax_acq_rel_v8f32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fmax_acq_rel_v8f32_global_cta_param_1];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [fmax_acq_rel_v8f32_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r20}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r19, %rd4;
; SM90-NEXT:    mov.b64 {_, %r18}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r17, %rd3;
; SM90-NEXT:  $L__BB255_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.f32 %r9, %r17, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd5, %r9;
; SM90-NEXT:    max.f32 %r10, %r18, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r10;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    max.f32 %r11, %r19, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r11;
; SM90-NEXT:    max.f32 %r12, %r20, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r12;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r17;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r18;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r19;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r20;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r20}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r19, %rd22;
; SM90-NEXT:    mov.b64 {_, %r18}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r17, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB255_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd26, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd26, %rd26};
; SM90-NEXT:    mov.b128 swap, {%rd26, %rd26};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd27, %rd28}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r24}, %rd28;
; SM90-NEXT:    cvt.u32.u64 %r23, %rd28;
; SM90-NEXT:    mov.b64 {_, %r22}, %rd27;
; SM90-NEXT:    cvt.u32.u64 %r21, %rd27;
; SM90-NEXT:  $L__BB255_3: // %atomicrmw.start2
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.f32 %r13, %r21, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd29, %r13;
; SM90-NEXT:    max.f32 %r14, %r22, %r6;
; SM90-NEXT:    cvt.u64.u32 %rd30, %r14;
; SM90-NEXT:    shl.b64 %rd31, %rd30, 32;
; SM90-NEXT:    or.b64 %rd32, %rd29, %rd31;
; SM90-NEXT:    max.f32 %r15, %r23, %r7;
; SM90-NEXT:    cvt.u64.u32 %rd33, %r15;
; SM90-NEXT:    max.f32 %r16, %r24, %r8;
; SM90-NEXT:    cvt.u64.u32 %rd34, %r16;
; SM90-NEXT:    shl.b64 %rd35, %rd34, 32;
; SM90-NEXT:    or.b64 %rd36, %rd33, %rd35;
; SM90-NEXT:    cvt.u64.u32 %rd37, %r21;
; SM90-NEXT:    cvt.u64.u32 %rd38, %r22;
; SM90-NEXT:    shl.b64 %rd39, %rd38, 32;
; SM90-NEXT:    or.b64 %rd40, %rd37, %rd39;
; SM90-NEXT:    cvt.u64.u32 %rd41, %r23;
; SM90-NEXT:    cvt.u64.u32 %rd42, %r24;
; SM90-NEXT:    shl.b64 %rd43, %rd42, 32;
; SM90-NEXT:    or.b64 %rd44, %rd41, %rd43;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd40, %rd44};
; SM90-NEXT:    mov.b128 swap, {%rd32, %rd36};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd45, %rd46}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd47, %rd46, %rd44;
; SM90-NEXT:    xor.b64 %rd48, %rd45, %rd40;
; SM90-NEXT:    or.b64 %rd49, %rd48, %rd47;
; SM90-NEXT:    mov.b64 {_, %r24}, %rd46;
; SM90-NEXT:    cvt.u32.u64 %r23, %rd46;
; SM90-NEXT:    mov.b64 {_, %r22}, %rd45;
; SM90-NEXT:    cvt.u32.u64 %r21, %rd45;
; SM90-NEXT:    setp.ne.b64 %p2, %rd49, 0;
; SM90-NEXT:    @%p2 bra $L__BB255_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end1
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r21, %r22, %r23, %r24};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r17, %r18, %r19, %r20};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmax ptr  addrspace(1) %addr, <8 x float> %val syncscope("block") acq_rel
        ret <8 x float> %retval
}

define <1 x float> @fminimum_acq_rel_v1f32_global_cta(ptr addrspace(1) %addr, <1 x float> %val) {
; SM90-LABEL: fminimum_acq_rel_v1f32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [fminimum_acq_rel_v1f32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b32 %r1, [fminimum_acq_rel_v1f32_global_cta_param_1];
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:  $L__BB256_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.NaN.f32 %r3, %r4, %r1;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r2, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p1, %r2, %r4;
; SM90-NEXT:    mov.b32 %r4, %r2;
; SM90-NEXT:    @%p1 bra $L__BB256_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fminimum ptr  addrspace(1) %addr, <1 x float> %val syncscope("block") acq_rel
        ret <1 x float> %retval
}

define <2 x float> @fminimum_acq_rel_v2f32_global_cta(ptr addrspace(1) %addr, <2 x float> %val) {
; SM90-LABEL: fminimum_acq_rel_v2f32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [fminimum_acq_rel_v2f32_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fminimum_acq_rel_v2f32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB257_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.NaN.f32 %r3, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r3;
; SM90-NEXT:    min.NaN.f32 %r4, %r6, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r4;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB257_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fminimum ptr  addrspace(1) %addr, <2 x float> %val syncscope("block") acq_rel
        ret <2 x float> %retval
}

define <4 x float> @fminimum_acq_rel_v4f32_global_cta(ptr addrspace(1) %addr, <4 x float> %val) {
; SM90-LABEL: fminimum_acq_rel_v4f32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fminimum_acq_rel_v4f32_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fminimum_acq_rel_v4f32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB258_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.NaN.f32 %r5, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd5, %r5;
; SM90-NEXT:    min.NaN.f32 %r6, %r10, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r6;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    min.NaN.f32 %r7, %r11, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r7;
; SM90-NEXT:    min.NaN.f32 %r8, %r12, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r8;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r10;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r12;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd22;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB258_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fminimum ptr  addrspace(1) %addr, <4 x float> %val syncscope("block") acq_rel
        ret <4 x float> %retval
}

define <8 x float> @fminimum_acq_rel_v8f32_global_cta(ptr addrspace(1) %addr, <8 x float> %val) {
; SM90-LABEL: fminimum_acq_rel_v8f32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<3>;
; SM90-NEXT:    .reg .b32 %r<25>;
; SM90-NEXT:    .reg .b64 %rd<50>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [fminimum_acq_rel_v8f32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fminimum_acq_rel_v8f32_global_cta_param_1];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [fminimum_acq_rel_v8f32_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r20}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r19, %rd4;
; SM90-NEXT:    mov.b64 {_, %r18}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r17, %rd3;
; SM90-NEXT:  $L__BB259_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.NaN.f32 %r9, %r17, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd5, %r9;
; SM90-NEXT:    min.NaN.f32 %r10, %r18, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r10;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    min.NaN.f32 %r11, %r19, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r11;
; SM90-NEXT:    min.NaN.f32 %r12, %r20, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r12;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r17;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r18;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r19;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r20;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r20}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r19, %rd22;
; SM90-NEXT:    mov.b64 {_, %r18}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r17, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB259_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd26, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd26, %rd26};
; SM90-NEXT:    mov.b128 swap, {%rd26, %rd26};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd27, %rd28}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r24}, %rd28;
; SM90-NEXT:    cvt.u32.u64 %r23, %rd28;
; SM90-NEXT:    mov.b64 {_, %r22}, %rd27;
; SM90-NEXT:    cvt.u32.u64 %r21, %rd27;
; SM90-NEXT:  $L__BB259_3: // %atomicrmw.start2
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.NaN.f32 %r13, %r21, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd29, %r13;
; SM90-NEXT:    min.NaN.f32 %r14, %r22, %r6;
; SM90-NEXT:    cvt.u64.u32 %rd30, %r14;
; SM90-NEXT:    shl.b64 %rd31, %rd30, 32;
; SM90-NEXT:    or.b64 %rd32, %rd29, %rd31;
; SM90-NEXT:    min.NaN.f32 %r15, %r23, %r7;
; SM90-NEXT:    cvt.u64.u32 %rd33, %r15;
; SM90-NEXT:    min.NaN.f32 %r16, %r24, %r8;
; SM90-NEXT:    cvt.u64.u32 %rd34, %r16;
; SM90-NEXT:    shl.b64 %rd35, %rd34, 32;
; SM90-NEXT:    or.b64 %rd36, %rd33, %rd35;
; SM90-NEXT:    cvt.u64.u32 %rd37, %r21;
; SM90-NEXT:    cvt.u64.u32 %rd38, %r22;
; SM90-NEXT:    shl.b64 %rd39, %rd38, 32;
; SM90-NEXT:    or.b64 %rd40, %rd37, %rd39;
; SM90-NEXT:    cvt.u64.u32 %rd41, %r23;
; SM90-NEXT:    cvt.u64.u32 %rd42, %r24;
; SM90-NEXT:    shl.b64 %rd43, %rd42, 32;
; SM90-NEXT:    or.b64 %rd44, %rd41, %rd43;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd40, %rd44};
; SM90-NEXT:    mov.b128 swap, {%rd32, %rd36};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd45, %rd46}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd47, %rd46, %rd44;
; SM90-NEXT:    xor.b64 %rd48, %rd45, %rd40;
; SM90-NEXT:    or.b64 %rd49, %rd48, %rd47;
; SM90-NEXT:    mov.b64 {_, %r24}, %rd46;
; SM90-NEXT:    cvt.u32.u64 %r23, %rd46;
; SM90-NEXT:    mov.b64 {_, %r22}, %rd45;
; SM90-NEXT:    cvt.u32.u64 %r21, %rd45;
; SM90-NEXT:    setp.ne.b64 %p2, %rd49, 0;
; SM90-NEXT:    @%p2 bra $L__BB259_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end1
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r21, %r22, %r23, %r24};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r17, %r18, %r19, %r20};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fminimum ptr  addrspace(1) %addr, <8 x float> %val syncscope("block") acq_rel
        ret <8 x float> %retval
}

define <1 x float> @fmaximum_acq_rel_v1f32_global_cta(ptr addrspace(1) %addr, <1 x float> %val) {
; SM90-LABEL: fmaximum_acq_rel_v1f32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [fmaximum_acq_rel_v1f32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b32 %r1, [fmaximum_acq_rel_v1f32_global_cta_param_1];
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:  $L__BB260_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.NaN.f32 %r3, %r4, %r1;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r2, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p1, %r2, %r4;
; SM90-NEXT:    mov.b32 %r4, %r2;
; SM90-NEXT:    @%p1 bra $L__BB260_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmaximum ptr  addrspace(1) %addr, <1 x float> %val syncscope("block") acq_rel
        ret <1 x float> %retval
}

define <2 x float> @fmaximum_acq_rel_v2f32_global_cta(ptr addrspace(1) %addr, <2 x float> %val) {
; SM90-LABEL: fmaximum_acq_rel_v2f32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [fmaximum_acq_rel_v2f32_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fmaximum_acq_rel_v2f32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB261_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.NaN.f32 %r3, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r3;
; SM90-NEXT:    max.NaN.f32 %r4, %r6, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r4;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB261_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmaximum ptr  addrspace(1) %addr, <2 x float> %val syncscope("block") acq_rel
        ret <2 x float> %retval
}

define <4 x float> @fmaximum_acq_rel_v4f32_global_cta(ptr addrspace(1) %addr, <4 x float> %val) {
; SM90-LABEL: fmaximum_acq_rel_v4f32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fmaximum_acq_rel_v4f32_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fmaximum_acq_rel_v4f32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB262_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.NaN.f32 %r5, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd5, %r5;
; SM90-NEXT:    max.NaN.f32 %r6, %r10, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r6;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    max.NaN.f32 %r7, %r11, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r7;
; SM90-NEXT:    max.NaN.f32 %r8, %r12, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r8;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r10;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r12;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd22;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB262_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmaximum ptr  addrspace(1) %addr, <4 x float> %val syncscope("block") acq_rel
        ret <4 x float> %retval
}

define <8 x float> @fmaximum_acq_rel_v8f32_global_cta(ptr addrspace(1) %addr, <8 x float> %val) {
; SM90-LABEL: fmaximum_acq_rel_v8f32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<3>;
; SM90-NEXT:    .reg .b32 %r<25>;
; SM90-NEXT:    .reg .b64 %rd<50>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [fmaximum_acq_rel_v8f32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fmaximum_acq_rel_v8f32_global_cta_param_1];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [fmaximum_acq_rel_v8f32_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r20}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r19, %rd4;
; SM90-NEXT:    mov.b64 {_, %r18}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r17, %rd3;
; SM90-NEXT:  $L__BB263_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.NaN.f32 %r9, %r17, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd5, %r9;
; SM90-NEXT:    max.NaN.f32 %r10, %r18, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r10;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    max.NaN.f32 %r11, %r19, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r11;
; SM90-NEXT:    max.NaN.f32 %r12, %r20, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r12;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r17;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r18;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r19;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r20;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r20}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r19, %rd22;
; SM90-NEXT:    mov.b64 {_, %r18}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r17, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB263_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd26, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd26, %rd26};
; SM90-NEXT:    mov.b128 swap, {%rd26, %rd26};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd27, %rd28}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r24}, %rd28;
; SM90-NEXT:    cvt.u32.u64 %r23, %rd28;
; SM90-NEXT:    mov.b64 {_, %r22}, %rd27;
; SM90-NEXT:    cvt.u32.u64 %r21, %rd27;
; SM90-NEXT:  $L__BB263_3: // %atomicrmw.start2
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.NaN.f32 %r13, %r21, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd29, %r13;
; SM90-NEXT:    max.NaN.f32 %r14, %r22, %r6;
; SM90-NEXT:    cvt.u64.u32 %rd30, %r14;
; SM90-NEXT:    shl.b64 %rd31, %rd30, 32;
; SM90-NEXT:    or.b64 %rd32, %rd29, %rd31;
; SM90-NEXT:    max.NaN.f32 %r15, %r23, %r7;
; SM90-NEXT:    cvt.u64.u32 %rd33, %r15;
; SM90-NEXT:    max.NaN.f32 %r16, %r24, %r8;
; SM90-NEXT:    cvt.u64.u32 %rd34, %r16;
; SM90-NEXT:    shl.b64 %rd35, %rd34, 32;
; SM90-NEXT:    or.b64 %rd36, %rd33, %rd35;
; SM90-NEXT:    cvt.u64.u32 %rd37, %r21;
; SM90-NEXT:    cvt.u64.u32 %rd38, %r22;
; SM90-NEXT:    shl.b64 %rd39, %rd38, 32;
; SM90-NEXT:    or.b64 %rd40, %rd37, %rd39;
; SM90-NEXT:    cvt.u64.u32 %rd41, %r23;
; SM90-NEXT:    cvt.u64.u32 %rd42, %r24;
; SM90-NEXT:    shl.b64 %rd43, %rd42, 32;
; SM90-NEXT:    or.b64 %rd44, %rd41, %rd43;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd40, %rd44};
; SM90-NEXT:    mov.b128 swap, {%rd32, %rd36};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd45, %rd46}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd47, %rd46, %rd44;
; SM90-NEXT:    xor.b64 %rd48, %rd45, %rd40;
; SM90-NEXT:    or.b64 %rd49, %rd48, %rd47;
; SM90-NEXT:    mov.b64 {_, %r24}, %rd46;
; SM90-NEXT:    cvt.u32.u64 %r23, %rd46;
; SM90-NEXT:    mov.b64 {_, %r22}, %rd45;
; SM90-NEXT:    cvt.u32.u64 %r21, %rd45;
; SM90-NEXT:    setp.ne.b64 %p2, %rd49, 0;
; SM90-NEXT:    @%p2 bra $L__BB263_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end1
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r21, %r22, %r23, %r24};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r17, %r18, %r19, %r20};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmaximum ptr  addrspace(1) %addr, <8 x float> %val syncscope("block") acq_rel
        ret <8 x float> %retval
}

define <1 x double> @fadd_acq_rel_v1f64_global_cta(ptr addrspace(1) %addr, <1 x double> %val) {
; SM90-LABEL: fadd_acq_rel_v1f64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<4>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [fadd_acq_rel_v1f64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b64 %rd2, [fadd_acq_rel_v1f64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.f64 %rd3, [%rd1], %rd2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b64 [func_retval0], %rd3;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fadd ptr  addrspace(1) %addr, <1 x double> %val syncscope("block") acq_rel
        ret <1 x double> %retval
}

define <2 x double> @fadd_acq_rel_v2f64_global_cta(ptr addrspace(1) %addr, <2 x double> %val) {
; SM90-LABEL: fadd_acq_rel_v2f64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<6>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [fadd_acq_rel_v2f64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [fadd_acq_rel_v2f64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.f64 %rd4, [%rd1], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.add.f64 %rd5, [%rd1+8], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd4, %rd5};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fadd ptr  addrspace(1) %addr, <2 x double> %val syncscope("block") acq_rel
        ret <2 x double> %retval
}

define <4 x double> @fadd_acq_rel_v4f64_global_cta(ptr addrspace(1) %addr, <4 x double> %val) {
; SM90-LABEL: fadd_acq_rel_v4f64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<10>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [fadd_acq_rel_v4f64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [fadd_acq_rel_v4f64_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [fadd_acq_rel_v4f64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.f64 %rd6, [%rd1], %rd4;
; SM90-NEXT:    atom.relaxed.cta.global.add.f64 %rd7, [%rd1+8], %rd5;
; SM90-NEXT:    atom.relaxed.cta.global.add.f64 %rd8, [%rd1+16], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.add.f64 %rd9, [%rd1+24], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd8, %rd9};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd6, %rd7};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fadd ptr  addrspace(1) %addr, <4 x double> %val syncscope("block") acq_rel
        ret <4 x double> %retval
}

define <8 x double> @fadd_acq_rel_v8f64_global_cta(ptr addrspace(1) %addr, <8 x double> %val) {
; SM90-LABEL: fadd_acq_rel_v8f64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b64 %rd<18>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [fadd_acq_rel_v8f64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [fadd_acq_rel_v8f64_global_cta_param_1+48];
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [fadd_acq_rel_v8f64_global_cta_param_1+32];
; SM90-NEXT:    ld.param.v2.b64 {%rd6, %rd7}, [fadd_acq_rel_v8f64_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v2.b64 {%rd8, %rd9}, [fadd_acq_rel_v8f64_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.f64 %rd10, [%rd1], %rd8;
; SM90-NEXT:    atom.relaxed.cta.global.add.f64 %rd11, [%rd1+8], %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.add.f64 %rd12, [%rd1+16], %rd6;
; SM90-NEXT:    atom.relaxed.cta.global.add.f64 %rd13, [%rd1+24], %rd7;
; SM90-NEXT:    atom.relaxed.cta.global.add.f64 %rd14, [%rd1+32], %rd4;
; SM90-NEXT:    atom.relaxed.cta.global.add.f64 %rd15, [%rd1+40], %rd5;
; SM90-NEXT:    atom.relaxed.cta.global.add.f64 %rd16, [%rd1+48], %rd2;
; SM90-NEXT:    atom.relaxed.cta.global.add.f64 %rd17, [%rd1+56], %rd3;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+48], {%rd16, %rd17};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+32], {%rd14, %rd15};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd12, %rd13};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd10, %rd11};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fadd ptr  addrspace(1) %addr, <8 x double> %val syncscope("block") acq_rel
        ret <8 x double> %retval
}

define <1 x double> @fsub_acq_rel_v1f64_global_cta(ptr addrspace(1) %addr, <1 x double> %val) {
; SM90-LABEL: fsub_acq_rel_v1f64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b64 %rd<6>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd3, [fsub_acq_rel_v1f64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b64 %rd1, [fsub_acq_rel_v1f64_global_cta_param_1];
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd5, [%rd3];
; SM90-NEXT:  $L__BB268_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    sub.rn.f64 %rd4, %rd5, %rd1;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd2, [%rd3], %rd5, %rd4;
; SM90-NEXT:    setp.ne.b64 %p1, %rd2, %rd5;
; SM90-NEXT:    mov.b64 %rd5, %rd2;
; SM90-NEXT:    @%p1 bra $L__BB268_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b64 [func_retval0], %rd2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fsub ptr  addrspace(1) %addr, <1 x double> %val syncscope("block") acq_rel
        ret <1 x double> %retval
}

define <2 x double> @fsub_acq_rel_v2f64_global_cta(ptr addrspace(1) %addr, <2 x double> %val) {
; SM90-LABEL: fsub_acq_rel_v2f64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b64 %rd<14>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [fsub_acq_rel_v2f64_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd3, [fsub_acq_rel_v2f64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd6, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd6, %rd6};
; SM90-NEXT:    mov.b128 swap, {%rd6, %rd6};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd3], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd12, %rd13}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB269_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    sub.rn.f64 %rd7, %rd12, %rd4;
; SM90-NEXT:    sub.rn.f64 %rd8, %rd13, %rd5;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd12, %rd13};
; SM90-NEXT:    mov.b128 swap, {%rd7, %rd8};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd3], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd1, %rd2}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd9, %rd2, %rd13;
; SM90-NEXT:    xor.b64 %rd10, %rd1, %rd12;
; SM90-NEXT:    or.b64 %rd11, %rd10, %rd9;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, 0;
; SM90-NEXT:    mov.b64 %rd12, %rd1;
; SM90-NEXT:    mov.b64 %rd13, %rd2;
; SM90-NEXT:    @%p1 bra $L__BB269_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd1, %rd2};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fsub ptr  addrspace(1) %addr, <2 x double> %val syncscope("block") acq_rel
        ret <2 x double> %retval
}

define <4 x double> @fsub_acq_rel_v4f64_global_cta(ptr addrspace(1) %addr, <4 x double> %val) {
; SM90-LABEL: fsub_acq_rel_v4f64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<3>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd9, [fsub_acq_rel_v4f64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [fsub_acq_rel_v4f64_global_cta_param_1];
; SM90-NEXT:    ld.param.v2.b64 {%rd3, %rd4}, [fsub_acq_rel_v4f64_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd10, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd10, %rd10};
; SM90-NEXT:    mov.b128 swap, {%rd10, %rd10};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd22, %rd23}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB270_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    sub.rn.f64 %rd11, %rd22, %rd1;
; SM90-NEXT:    sub.rn.f64 %rd12, %rd23, %rd2;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd22, %rd23};
; SM90-NEXT:    mov.b128 swap, {%rd11, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd5, %rd6}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd13, %rd6, %rd23;
; SM90-NEXT:    xor.b64 %rd14, %rd5, %rd22;
; SM90-NEXT:    or.b64 %rd15, %rd14, %rd13;
; SM90-NEXT:    setp.ne.b64 %p1, %rd15, 0;
; SM90-NEXT:    mov.b64 %rd22, %rd5;
; SM90-NEXT:    mov.b64 %rd23, %rd6;
; SM90-NEXT:    @%p1 bra $L__BB270_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd16, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd16};
; SM90-NEXT:    mov.b128 swap, {%rd16, %rd16};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd24, %rd25}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB270_3: // %atomicrmw.start2
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    sub.rn.f64 %rd17, %rd24, %rd3;
; SM90-NEXT:    sub.rn.f64 %rd18, %rd25, %rd4;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd24, %rd25};
; SM90-NEXT:    mov.b128 swap, {%rd17, %rd18};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd7, %rd8}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd19, %rd8, %rd25;
; SM90-NEXT:    xor.b64 %rd20, %rd7, %rd24;
; SM90-NEXT:    or.b64 %rd21, %rd20, %rd19;
; SM90-NEXT:    setp.ne.b64 %p2, %rd21, 0;
; SM90-NEXT:    mov.b64 %rd24, %rd7;
; SM90-NEXT:    mov.b64 %rd25, %rd8;
; SM90-NEXT:    @%p2 bra $L__BB270_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end1
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd7, %rd8};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd5, %rd6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fsub ptr  addrspace(1) %addr, <4 x double> %val syncscope("block") acq_rel
        ret <4 x double> %retval
}

define <8 x double> @fsub_acq_rel_v8f64_global_cta(ptr addrspace(1) %addr, <8 x double> %val) {
; SM90-LABEL: fsub_acq_rel_v8f64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<5>;
; SM90-NEXT:    .reg .b64 %rd<50>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd17, [fsub_acq_rel_v8f64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd3, %rd4}, [fsub_acq_rel_v8f64_global_cta_param_1+48];
; SM90-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [fsub_acq_rel_v8f64_global_cta_param_1+32];
; SM90-NEXT:    ld.param.v2.b64 {%rd5, %rd6}, [fsub_acq_rel_v8f64_global_cta_param_1];
; SM90-NEXT:    ld.param.v2.b64 {%rd7, %rd8}, [fsub_acq_rel_v8f64_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd18, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd18, %rd18};
; SM90-NEXT:    mov.b128 swap, {%rd18, %rd18};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd42, %rd43}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB271_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    mov.b64 %rd10, %rd43;
; SM90-NEXT:    mov.b64 %rd9, %rd42;
; SM90-NEXT:    sub.rn.f64 %rd19, %rd9, %rd5;
; SM90-NEXT:    sub.rn.f64 %rd20, %rd10, %rd6;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd9, %rd10};
; SM90-NEXT:    mov.b128 swap, {%rd19, %rd20};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd42, %rd43}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd21, %rd43, %rd10;
; SM90-NEXT:    xor.b64 %rd22, %rd42, %rd9;
; SM90-NEXT:    or.b64 %rd23, %rd22, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd23, 0;
; SM90-NEXT:    @%p1 bra $L__BB271_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd24, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd24, %rd24};
; SM90-NEXT:    mov.b128 swap, {%rd24, %rd24};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd44, %rd45}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB271_3: // %atomicrmw.start6
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    mov.b64 %rd12, %rd45;
; SM90-NEXT:    mov.b64 %rd11, %rd44;
; SM90-NEXT:    sub.rn.f64 %rd25, %rd11, %rd7;
; SM90-NEXT:    sub.rn.f64 %rd26, %rd12, %rd8;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd11, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd25, %rd26};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd44, %rd45}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd27, %rd45, %rd12;
; SM90-NEXT:    xor.b64 %rd28, %rd44, %rd11;
; SM90-NEXT:    or.b64 %rd29, %rd28, %rd27;
; SM90-NEXT:    setp.ne.b64 %p2, %rd29, 0;
; SM90-NEXT:    @%p2 bra $L__BB271_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end5
; SM90-NEXT:    mov.b64 %rd30, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd30, %rd30};
; SM90-NEXT:    mov.b128 swap, {%rd30, %rd30};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+32], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd46, %rd47}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB271_5: // %atomicrmw.start16
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    sub.rn.f64 %rd31, %rd46, %rd1;
; SM90-NEXT:    sub.rn.f64 %rd32, %rd47, %rd2;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd46, %rd47};
; SM90-NEXT:    mov.b128 swap, {%rd31, %rd32};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+32], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd13, %rd14}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd33, %rd14, %rd47;
; SM90-NEXT:    xor.b64 %rd34, %rd13, %rd46;
; SM90-NEXT:    or.b64 %rd35, %rd34, %rd33;
; SM90-NEXT:    setp.ne.b64 %p3, %rd35, 0;
; SM90-NEXT:    mov.b64 %rd46, %rd13;
; SM90-NEXT:    mov.b64 %rd47, %rd14;
; SM90-NEXT:    @%p3 bra $L__BB271_5;
; SM90-NEXT:  // %bb.6: // %atomicrmw.end15
; SM90-NEXT:    mov.b64 %rd36, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd36, %rd36};
; SM90-NEXT:    mov.b128 swap, {%rd36, %rd36};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+48], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd48, %rd49}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB271_7: // %atomicrmw.start22
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    sub.rn.f64 %rd37, %rd48, %rd3;
; SM90-NEXT:    sub.rn.f64 %rd38, %rd49, %rd4;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd48, %rd49};
; SM90-NEXT:    mov.b128 swap, {%rd37, %rd38};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+48], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd15, %rd16}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd39, %rd16, %rd49;
; SM90-NEXT:    xor.b64 %rd40, %rd15, %rd48;
; SM90-NEXT:    or.b64 %rd41, %rd40, %rd39;
; SM90-NEXT:    setp.ne.b64 %p4, %rd41, 0;
; SM90-NEXT:    mov.b64 %rd48, %rd15;
; SM90-NEXT:    mov.b64 %rd49, %rd16;
; SM90-NEXT:    @%p4 bra $L__BB271_7;
; SM90-NEXT:  // %bb.8: // %atomicrmw.end21
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+48], {%rd15, %rd16};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+32], {%rd13, %rd14};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd42, %rd43};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd44, %rd45};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fsub ptr  addrspace(1) %addr, <8 x double> %val syncscope("block") acq_rel
        ret <8 x double> %retval
}

define <1 x double> @fmin_acq_rel_v1f64_global_cta(ptr addrspace(1) %addr, <1 x double> %val) {
; SM90-LABEL: fmin_acq_rel_v1f64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b64 %rd<6>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd3, [fmin_acq_rel_v1f64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b64 %rd1, [fmin_acq_rel_v1f64_global_cta_param_1];
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd5, [%rd3];
; SM90-NEXT:  $L__BB272_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.f64 %rd4, %rd5, %rd1;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd2, [%rd3], %rd5, %rd4;
; SM90-NEXT:    setp.ne.b64 %p1, %rd2, %rd5;
; SM90-NEXT:    mov.b64 %rd5, %rd2;
; SM90-NEXT:    @%p1 bra $L__BB272_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b64 [func_retval0], %rd2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmin ptr  addrspace(1) %addr, <1 x double> %val syncscope("block") acq_rel
        ret <1 x double> %retval
}

define <2 x double> @fmin_acq_rel_v2f64_global_cta(ptr addrspace(1) %addr, <2 x double> %val) {
; SM90-LABEL: fmin_acq_rel_v2f64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b64 %rd<14>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [fmin_acq_rel_v2f64_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd3, [fmin_acq_rel_v2f64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd6, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd6, %rd6};
; SM90-NEXT:    mov.b128 swap, {%rd6, %rd6};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd3], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd12, %rd13}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB273_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.f64 %rd7, %rd12, %rd4;
; SM90-NEXT:    min.f64 %rd8, %rd13, %rd5;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd12, %rd13};
; SM90-NEXT:    mov.b128 swap, {%rd7, %rd8};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd3], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd1, %rd2}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd9, %rd2, %rd13;
; SM90-NEXT:    xor.b64 %rd10, %rd1, %rd12;
; SM90-NEXT:    or.b64 %rd11, %rd10, %rd9;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, 0;
; SM90-NEXT:    mov.b64 %rd12, %rd1;
; SM90-NEXT:    mov.b64 %rd13, %rd2;
; SM90-NEXT:    @%p1 bra $L__BB273_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd1, %rd2};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmin ptr  addrspace(1) %addr, <2 x double> %val syncscope("block") acq_rel
        ret <2 x double> %retval
}

define <4 x double> @fmin_acq_rel_v4f64_global_cta(ptr addrspace(1) %addr, <4 x double> %val) {
; SM90-LABEL: fmin_acq_rel_v4f64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<3>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd9, [fmin_acq_rel_v4f64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [fmin_acq_rel_v4f64_global_cta_param_1];
; SM90-NEXT:    ld.param.v2.b64 {%rd3, %rd4}, [fmin_acq_rel_v4f64_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd10, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd10, %rd10};
; SM90-NEXT:    mov.b128 swap, {%rd10, %rd10};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd22, %rd23}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB274_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.f64 %rd11, %rd22, %rd1;
; SM90-NEXT:    min.f64 %rd12, %rd23, %rd2;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd22, %rd23};
; SM90-NEXT:    mov.b128 swap, {%rd11, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd5, %rd6}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd13, %rd6, %rd23;
; SM90-NEXT:    xor.b64 %rd14, %rd5, %rd22;
; SM90-NEXT:    or.b64 %rd15, %rd14, %rd13;
; SM90-NEXT:    setp.ne.b64 %p1, %rd15, 0;
; SM90-NEXT:    mov.b64 %rd22, %rd5;
; SM90-NEXT:    mov.b64 %rd23, %rd6;
; SM90-NEXT:    @%p1 bra $L__BB274_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd16, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd16};
; SM90-NEXT:    mov.b128 swap, {%rd16, %rd16};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd24, %rd25}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB274_3: // %atomicrmw.start2
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.f64 %rd17, %rd24, %rd3;
; SM90-NEXT:    min.f64 %rd18, %rd25, %rd4;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd24, %rd25};
; SM90-NEXT:    mov.b128 swap, {%rd17, %rd18};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd7, %rd8}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd19, %rd8, %rd25;
; SM90-NEXT:    xor.b64 %rd20, %rd7, %rd24;
; SM90-NEXT:    or.b64 %rd21, %rd20, %rd19;
; SM90-NEXT:    setp.ne.b64 %p2, %rd21, 0;
; SM90-NEXT:    mov.b64 %rd24, %rd7;
; SM90-NEXT:    mov.b64 %rd25, %rd8;
; SM90-NEXT:    @%p2 bra $L__BB274_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end1
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd7, %rd8};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd5, %rd6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmin ptr  addrspace(1) %addr, <4 x double> %val syncscope("block") acq_rel
        ret <4 x double> %retval
}

define <8 x double> @fmin_acq_rel_v8f64_global_cta(ptr addrspace(1) %addr, <8 x double> %val) {
; SM90-LABEL: fmin_acq_rel_v8f64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<5>;
; SM90-NEXT:    .reg .b64 %rd<50>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd17, [fmin_acq_rel_v8f64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd3, %rd4}, [fmin_acq_rel_v8f64_global_cta_param_1+48];
; SM90-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [fmin_acq_rel_v8f64_global_cta_param_1+32];
; SM90-NEXT:    ld.param.v2.b64 {%rd5, %rd6}, [fmin_acq_rel_v8f64_global_cta_param_1];
; SM90-NEXT:    ld.param.v2.b64 {%rd7, %rd8}, [fmin_acq_rel_v8f64_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd18, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd18, %rd18};
; SM90-NEXT:    mov.b128 swap, {%rd18, %rd18};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd42, %rd43}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB275_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    mov.b64 %rd10, %rd43;
; SM90-NEXT:    mov.b64 %rd9, %rd42;
; SM90-NEXT:    min.f64 %rd19, %rd9, %rd5;
; SM90-NEXT:    min.f64 %rd20, %rd10, %rd6;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd9, %rd10};
; SM90-NEXT:    mov.b128 swap, {%rd19, %rd20};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd42, %rd43}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd21, %rd43, %rd10;
; SM90-NEXT:    xor.b64 %rd22, %rd42, %rd9;
; SM90-NEXT:    or.b64 %rd23, %rd22, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd23, 0;
; SM90-NEXT:    @%p1 bra $L__BB275_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd24, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd24, %rd24};
; SM90-NEXT:    mov.b128 swap, {%rd24, %rd24};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd44, %rd45}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB275_3: // %atomicrmw.start6
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    mov.b64 %rd12, %rd45;
; SM90-NEXT:    mov.b64 %rd11, %rd44;
; SM90-NEXT:    min.f64 %rd25, %rd11, %rd7;
; SM90-NEXT:    min.f64 %rd26, %rd12, %rd8;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd11, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd25, %rd26};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd44, %rd45}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd27, %rd45, %rd12;
; SM90-NEXT:    xor.b64 %rd28, %rd44, %rd11;
; SM90-NEXT:    or.b64 %rd29, %rd28, %rd27;
; SM90-NEXT:    setp.ne.b64 %p2, %rd29, 0;
; SM90-NEXT:    @%p2 bra $L__BB275_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end5
; SM90-NEXT:    mov.b64 %rd30, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd30, %rd30};
; SM90-NEXT:    mov.b128 swap, {%rd30, %rd30};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+32], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd46, %rd47}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB275_5: // %atomicrmw.start15
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.f64 %rd31, %rd46, %rd1;
; SM90-NEXT:    min.f64 %rd32, %rd47, %rd2;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd46, %rd47};
; SM90-NEXT:    mov.b128 swap, {%rd31, %rd32};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+32], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd13, %rd14}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd33, %rd14, %rd47;
; SM90-NEXT:    xor.b64 %rd34, %rd13, %rd46;
; SM90-NEXT:    or.b64 %rd35, %rd34, %rd33;
; SM90-NEXT:    setp.ne.b64 %p3, %rd35, 0;
; SM90-NEXT:    mov.b64 %rd46, %rd13;
; SM90-NEXT:    mov.b64 %rd47, %rd14;
; SM90-NEXT:    @%p3 bra $L__BB275_5;
; SM90-NEXT:  // %bb.6: // %atomicrmw.end14
; SM90-NEXT:    mov.b64 %rd36, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd36, %rd36};
; SM90-NEXT:    mov.b128 swap, {%rd36, %rd36};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+48], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd48, %rd49}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB275_7: // %atomicrmw.start20
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.f64 %rd37, %rd48, %rd3;
; SM90-NEXT:    min.f64 %rd38, %rd49, %rd4;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd48, %rd49};
; SM90-NEXT:    mov.b128 swap, {%rd37, %rd38};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+48], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd15, %rd16}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd39, %rd16, %rd49;
; SM90-NEXT:    xor.b64 %rd40, %rd15, %rd48;
; SM90-NEXT:    or.b64 %rd41, %rd40, %rd39;
; SM90-NEXT:    setp.ne.b64 %p4, %rd41, 0;
; SM90-NEXT:    mov.b64 %rd48, %rd15;
; SM90-NEXT:    mov.b64 %rd49, %rd16;
; SM90-NEXT:    @%p4 bra $L__BB275_7;
; SM90-NEXT:  // %bb.8: // %atomicrmw.end19
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+48], {%rd15, %rd16};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+32], {%rd13, %rd14};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd42, %rd43};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd44, %rd45};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmin ptr  addrspace(1) %addr, <8 x double> %val syncscope("block") acq_rel
        ret <8 x double> %retval
}

define <1 x double> @fmax_acq_rel_v1f64_global_cta(ptr addrspace(1) %addr, <1 x double> %val) {
; SM90-LABEL: fmax_acq_rel_v1f64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b64 %rd<6>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd3, [fmax_acq_rel_v1f64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b64 %rd1, [fmax_acq_rel_v1f64_global_cta_param_1];
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd5, [%rd3];
; SM90-NEXT:  $L__BB276_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.f64 %rd4, %rd5, %rd1;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd2, [%rd3], %rd5, %rd4;
; SM90-NEXT:    setp.ne.b64 %p1, %rd2, %rd5;
; SM90-NEXT:    mov.b64 %rd5, %rd2;
; SM90-NEXT:    @%p1 bra $L__BB276_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b64 [func_retval0], %rd2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmax ptr  addrspace(1) %addr, <1 x double> %val syncscope("block") acq_rel
        ret <1 x double> %retval
}

define <2 x double> @fmax_acq_rel_v2f64_global_cta(ptr addrspace(1) %addr, <2 x double> %val) {
; SM90-LABEL: fmax_acq_rel_v2f64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b64 %rd<14>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [fmax_acq_rel_v2f64_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd3, [fmax_acq_rel_v2f64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd6, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd6, %rd6};
; SM90-NEXT:    mov.b128 swap, {%rd6, %rd6};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd3], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd12, %rd13}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB277_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.f64 %rd7, %rd12, %rd4;
; SM90-NEXT:    max.f64 %rd8, %rd13, %rd5;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd12, %rd13};
; SM90-NEXT:    mov.b128 swap, {%rd7, %rd8};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd3], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd1, %rd2}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd9, %rd2, %rd13;
; SM90-NEXT:    xor.b64 %rd10, %rd1, %rd12;
; SM90-NEXT:    or.b64 %rd11, %rd10, %rd9;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, 0;
; SM90-NEXT:    mov.b64 %rd12, %rd1;
; SM90-NEXT:    mov.b64 %rd13, %rd2;
; SM90-NEXT:    @%p1 bra $L__BB277_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd1, %rd2};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmax ptr  addrspace(1) %addr, <2 x double> %val syncscope("block") acq_rel
        ret <2 x double> %retval
}

define <4 x double> @fmax_acq_rel_v4f64_global_cta(ptr addrspace(1) %addr, <4 x double> %val) {
; SM90-LABEL: fmax_acq_rel_v4f64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<3>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd9, [fmax_acq_rel_v4f64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [fmax_acq_rel_v4f64_global_cta_param_1];
; SM90-NEXT:    ld.param.v2.b64 {%rd3, %rd4}, [fmax_acq_rel_v4f64_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd10, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd10, %rd10};
; SM90-NEXT:    mov.b128 swap, {%rd10, %rd10};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd22, %rd23}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB278_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.f64 %rd11, %rd22, %rd1;
; SM90-NEXT:    max.f64 %rd12, %rd23, %rd2;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd22, %rd23};
; SM90-NEXT:    mov.b128 swap, {%rd11, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd5, %rd6}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd13, %rd6, %rd23;
; SM90-NEXT:    xor.b64 %rd14, %rd5, %rd22;
; SM90-NEXT:    or.b64 %rd15, %rd14, %rd13;
; SM90-NEXT:    setp.ne.b64 %p1, %rd15, 0;
; SM90-NEXT:    mov.b64 %rd22, %rd5;
; SM90-NEXT:    mov.b64 %rd23, %rd6;
; SM90-NEXT:    @%p1 bra $L__BB278_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd16, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd16};
; SM90-NEXT:    mov.b128 swap, {%rd16, %rd16};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd24, %rd25}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB278_3: // %atomicrmw.start2
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.f64 %rd17, %rd24, %rd3;
; SM90-NEXT:    max.f64 %rd18, %rd25, %rd4;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd24, %rd25};
; SM90-NEXT:    mov.b128 swap, {%rd17, %rd18};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd7, %rd8}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd19, %rd8, %rd25;
; SM90-NEXT:    xor.b64 %rd20, %rd7, %rd24;
; SM90-NEXT:    or.b64 %rd21, %rd20, %rd19;
; SM90-NEXT:    setp.ne.b64 %p2, %rd21, 0;
; SM90-NEXT:    mov.b64 %rd24, %rd7;
; SM90-NEXT:    mov.b64 %rd25, %rd8;
; SM90-NEXT:    @%p2 bra $L__BB278_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end1
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd7, %rd8};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd5, %rd6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmax ptr  addrspace(1) %addr, <4 x double> %val syncscope("block") acq_rel
        ret <4 x double> %retval
}

define <8 x double> @fmax_acq_rel_v8f64_global_cta(ptr addrspace(1) %addr, <8 x double> %val) {
; SM90-LABEL: fmax_acq_rel_v8f64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<5>;
; SM90-NEXT:    .reg .b64 %rd<50>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd17, [fmax_acq_rel_v8f64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd3, %rd4}, [fmax_acq_rel_v8f64_global_cta_param_1+48];
; SM90-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [fmax_acq_rel_v8f64_global_cta_param_1+32];
; SM90-NEXT:    ld.param.v2.b64 {%rd5, %rd6}, [fmax_acq_rel_v8f64_global_cta_param_1];
; SM90-NEXT:    ld.param.v2.b64 {%rd7, %rd8}, [fmax_acq_rel_v8f64_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd18, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd18, %rd18};
; SM90-NEXT:    mov.b128 swap, {%rd18, %rd18};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd42, %rd43}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB279_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    mov.b64 %rd10, %rd43;
; SM90-NEXT:    mov.b64 %rd9, %rd42;
; SM90-NEXT:    max.f64 %rd19, %rd9, %rd5;
; SM90-NEXT:    max.f64 %rd20, %rd10, %rd6;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd9, %rd10};
; SM90-NEXT:    mov.b128 swap, {%rd19, %rd20};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd42, %rd43}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd21, %rd43, %rd10;
; SM90-NEXT:    xor.b64 %rd22, %rd42, %rd9;
; SM90-NEXT:    or.b64 %rd23, %rd22, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd23, 0;
; SM90-NEXT:    @%p1 bra $L__BB279_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd24, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd24, %rd24};
; SM90-NEXT:    mov.b128 swap, {%rd24, %rd24};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd44, %rd45}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB279_3: // %atomicrmw.start6
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    mov.b64 %rd12, %rd45;
; SM90-NEXT:    mov.b64 %rd11, %rd44;
; SM90-NEXT:    max.f64 %rd25, %rd11, %rd7;
; SM90-NEXT:    max.f64 %rd26, %rd12, %rd8;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd11, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd25, %rd26};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd44, %rd45}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd27, %rd45, %rd12;
; SM90-NEXT:    xor.b64 %rd28, %rd44, %rd11;
; SM90-NEXT:    or.b64 %rd29, %rd28, %rd27;
; SM90-NEXT:    setp.ne.b64 %p2, %rd29, 0;
; SM90-NEXT:    @%p2 bra $L__BB279_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end5
; SM90-NEXT:    mov.b64 %rd30, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd30, %rd30};
; SM90-NEXT:    mov.b128 swap, {%rd30, %rd30};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+32], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd46, %rd47}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB279_5: // %atomicrmw.start15
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.f64 %rd31, %rd46, %rd1;
; SM90-NEXT:    max.f64 %rd32, %rd47, %rd2;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd46, %rd47};
; SM90-NEXT:    mov.b128 swap, {%rd31, %rd32};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+32], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd13, %rd14}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd33, %rd14, %rd47;
; SM90-NEXT:    xor.b64 %rd34, %rd13, %rd46;
; SM90-NEXT:    or.b64 %rd35, %rd34, %rd33;
; SM90-NEXT:    setp.ne.b64 %p3, %rd35, 0;
; SM90-NEXT:    mov.b64 %rd46, %rd13;
; SM90-NEXT:    mov.b64 %rd47, %rd14;
; SM90-NEXT:    @%p3 bra $L__BB279_5;
; SM90-NEXT:  // %bb.6: // %atomicrmw.end14
; SM90-NEXT:    mov.b64 %rd36, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd36, %rd36};
; SM90-NEXT:    mov.b128 swap, {%rd36, %rd36};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+48], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd48, %rd49}, dst;
; SM90-NEXT:    }
; SM90-NEXT:  $L__BB279_7: // %atomicrmw.start20
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.f64 %rd37, %rd48, %rd3;
; SM90-NEXT:    max.f64 %rd38, %rd49, %rd4;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd48, %rd49};
; SM90-NEXT:    mov.b128 swap, {%rd37, %rd38};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+48], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd15, %rd16}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd39, %rd16, %rd49;
; SM90-NEXT:    xor.b64 %rd40, %rd15, %rd48;
; SM90-NEXT:    or.b64 %rd41, %rd40, %rd39;
; SM90-NEXT:    setp.ne.b64 %p4, %rd41, 0;
; SM90-NEXT:    mov.b64 %rd48, %rd15;
; SM90-NEXT:    mov.b64 %rd49, %rd16;
; SM90-NEXT:    @%p4 bra $L__BB279_7;
; SM90-NEXT:  // %bb.8: // %atomicrmw.end19
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+48], {%rd15, %rd16};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+32], {%rd13, %rd14};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd42, %rd43};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd44, %rd45};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmax ptr  addrspace(1) %addr, <8 x double> %val syncscope("block") acq_rel
        ret <8 x double> %retval
}

define <1 x double> @fminimum_acq_rel_v1f64_global_cta(ptr addrspace(1) %addr, <1 x double> %val) {
; SM90-LABEL: fminimum_acq_rel_v1f64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<6>;
; SM90-NEXT:    .reg .b64 %rd<10>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd3, [fminimum_acq_rel_v1f64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b64 %rd1, [fminimum_acq_rel_v1f64_global_cta_param_1];
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd9, [%rd3];
; SM90-NEXT:    setp.eq.b64 %p3, %rd1, -9223372036854775808;
; SM90-NEXT:  $L__BB280_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    setp.nan.f64 %p1, %rd9, %rd1;
; SM90-NEXT:    min.f64 %rd4, %rd9, %rd1;
; SM90-NEXT:    selp.f64 %rd5, 0d7FF8000000000000, %rd4, %p1;
; SM90-NEXT:    setp.eq.b64 %p2, %rd9, -9223372036854775808;
; SM90-NEXT:    selp.f64 %rd6, %rd9, %rd5, %p2;
; SM90-NEXT:    selp.f64 %rd7, %rd1, %rd6, %p3;
; SM90-NEXT:    setp.eq.f64 %p4, %rd5, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd8, %rd7, %rd5, %p4;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd2, [%rd3], %rd9, %rd8;
; SM90-NEXT:    setp.ne.b64 %p5, %rd2, %rd9;
; SM90-NEXT:    mov.b64 %rd9, %rd2;
; SM90-NEXT:    @%p5 bra $L__BB280_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b64 [func_retval0], %rd2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fminimum ptr  addrspace(1) %addr, <1 x double> %val syncscope("block") acq_rel
        ret <1 x double> %retval
}

define <2 x double> @fminimum_acq_rel_v2f64_global_cta(ptr addrspace(1) %addr, <2 x double> %val) {
; SM90-LABEL: fminimum_acq_rel_v2f64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<10>;
; SM90-NEXT:    .reg .b64 %rd<22>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [fminimum_acq_rel_v2f64_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd3, [fminimum_acq_rel_v2f64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd6, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd6, %rd6};
; SM90-NEXT:    mov.b128 swap, {%rd6, %rd6};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd3], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd20, %rd21}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    setp.eq.b64 %p3, %rd4, -9223372036854775808;
; SM90-NEXT:    setp.eq.b64 %p7, %rd5, -9223372036854775808;
; SM90-NEXT:  $L__BB281_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    setp.nan.f64 %p1, %rd20, %rd4;
; SM90-NEXT:    min.f64 %rd7, %rd20, %rd4;
; SM90-NEXT:    selp.f64 %rd8, 0d7FF8000000000000, %rd7, %p1;
; SM90-NEXT:    setp.eq.b64 %p2, %rd20, -9223372036854775808;
; SM90-NEXT:    selp.f64 %rd9, %rd20, %rd8, %p2;
; SM90-NEXT:    selp.f64 %rd10, %rd4, %rd9, %p3;
; SM90-NEXT:    setp.eq.f64 %p4, %rd8, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd11, %rd10, %rd8, %p4;
; SM90-NEXT:    setp.nan.f64 %p5, %rd21, %rd5;
; SM90-NEXT:    min.f64 %rd12, %rd21, %rd5;
; SM90-NEXT:    selp.f64 %rd13, 0d7FF8000000000000, %rd12, %p5;
; SM90-NEXT:    setp.eq.b64 %p6, %rd21, -9223372036854775808;
; SM90-NEXT:    selp.f64 %rd14, %rd21, %rd13, %p6;
; SM90-NEXT:    selp.f64 %rd15, %rd5, %rd14, %p7;
; SM90-NEXT:    setp.eq.f64 %p8, %rd13, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd16, %rd15, %rd13, %p8;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd20, %rd21};
; SM90-NEXT:    mov.b128 swap, {%rd11, %rd16};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd3], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd1, %rd2}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd17, %rd2, %rd21;
; SM90-NEXT:    xor.b64 %rd18, %rd1, %rd20;
; SM90-NEXT:    or.b64 %rd19, %rd18, %rd17;
; SM90-NEXT:    setp.ne.b64 %p9, %rd19, 0;
; SM90-NEXT:    mov.b64 %rd20, %rd1;
; SM90-NEXT:    mov.b64 %rd21, %rd2;
; SM90-NEXT:    @%p9 bra $L__BB281_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd1, %rd2};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fminimum ptr  addrspace(1) %addr, <2 x double> %val syncscope("block") acq_rel
        ret <2 x double> %retval
}

define <4 x double> @fminimum_acq_rel_v4f64_global_cta(ptr addrspace(1) %addr, <4 x double> %val) {
; SM90-LABEL: fminimum_acq_rel_v4f64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<19>;
; SM90-NEXT:    .reg .b64 %rd<42>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd9, [fminimum_acq_rel_v4f64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [fminimum_acq_rel_v4f64_global_cta_param_1];
; SM90-NEXT:    ld.param.v2.b64 {%rd3, %rd4}, [fminimum_acq_rel_v4f64_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd10, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd10, %rd10};
; SM90-NEXT:    mov.b128 swap, {%rd10, %rd10};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd38, %rd39}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    setp.eq.b64 %p3, %rd1, -9223372036854775808;
; SM90-NEXT:    setp.eq.b64 %p7, %rd2, -9223372036854775808;
; SM90-NEXT:  $L__BB282_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    setp.nan.f64 %p1, %rd38, %rd1;
; SM90-NEXT:    min.f64 %rd11, %rd38, %rd1;
; SM90-NEXT:    selp.f64 %rd12, 0d7FF8000000000000, %rd11, %p1;
; SM90-NEXT:    setp.eq.b64 %p2, %rd38, -9223372036854775808;
; SM90-NEXT:    selp.f64 %rd13, %rd38, %rd12, %p2;
; SM90-NEXT:    selp.f64 %rd14, %rd1, %rd13, %p3;
; SM90-NEXT:    setp.eq.f64 %p4, %rd12, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd15, %rd14, %rd12, %p4;
; SM90-NEXT:    setp.nan.f64 %p5, %rd39, %rd2;
; SM90-NEXT:    min.f64 %rd16, %rd39, %rd2;
; SM90-NEXT:    selp.f64 %rd17, 0d7FF8000000000000, %rd16, %p5;
; SM90-NEXT:    setp.eq.b64 %p6, %rd39, -9223372036854775808;
; SM90-NEXT:    selp.f64 %rd18, %rd39, %rd17, %p6;
; SM90-NEXT:    selp.f64 %rd19, %rd2, %rd18, %p7;
; SM90-NEXT:    setp.eq.f64 %p8, %rd17, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd20, %rd19, %rd17, %p8;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd38, %rd39};
; SM90-NEXT:    mov.b128 swap, {%rd15, %rd20};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd5, %rd6}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd21, %rd6, %rd39;
; SM90-NEXT:    xor.b64 %rd22, %rd5, %rd38;
; SM90-NEXT:    or.b64 %rd23, %rd22, %rd21;
; SM90-NEXT:    setp.ne.b64 %p9, %rd23, 0;
; SM90-NEXT:    mov.b64 %rd38, %rd5;
; SM90-NEXT:    mov.b64 %rd39, %rd6;
; SM90-NEXT:    @%p9 bra $L__BB282_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd24, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd24, %rd24};
; SM90-NEXT:    mov.b128 swap, {%rd24, %rd24};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd40, %rd41}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    setp.eq.b64 %p12, %rd3, -9223372036854775808;
; SM90-NEXT:    setp.eq.b64 %p16, %rd4, -9223372036854775808;
; SM90-NEXT:  $L__BB282_3: // %atomicrmw.start2
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    setp.nan.f64 %p10, %rd40, %rd3;
; SM90-NEXT:    min.f64 %rd25, %rd40, %rd3;
; SM90-NEXT:    selp.f64 %rd26, 0d7FF8000000000000, %rd25, %p10;
; SM90-NEXT:    setp.eq.b64 %p11, %rd40, -9223372036854775808;
; SM90-NEXT:    selp.f64 %rd27, %rd40, %rd26, %p11;
; SM90-NEXT:    selp.f64 %rd28, %rd3, %rd27, %p12;
; SM90-NEXT:    setp.eq.f64 %p13, %rd26, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd29, %rd28, %rd26, %p13;
; SM90-NEXT:    setp.nan.f64 %p14, %rd41, %rd4;
; SM90-NEXT:    min.f64 %rd30, %rd41, %rd4;
; SM90-NEXT:    selp.f64 %rd31, 0d7FF8000000000000, %rd30, %p14;
; SM90-NEXT:    setp.eq.b64 %p15, %rd41, -9223372036854775808;
; SM90-NEXT:    selp.f64 %rd32, %rd41, %rd31, %p15;
; SM90-NEXT:    selp.f64 %rd33, %rd4, %rd32, %p16;
; SM90-NEXT:    setp.eq.f64 %p17, %rd31, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd34, %rd33, %rd31, %p17;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd40, %rd41};
; SM90-NEXT:    mov.b128 swap, {%rd29, %rd34};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd7, %rd8}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd35, %rd8, %rd41;
; SM90-NEXT:    xor.b64 %rd36, %rd7, %rd40;
; SM90-NEXT:    or.b64 %rd37, %rd36, %rd35;
; SM90-NEXT:    setp.ne.b64 %p18, %rd37, 0;
; SM90-NEXT:    mov.b64 %rd40, %rd7;
; SM90-NEXT:    mov.b64 %rd41, %rd8;
; SM90-NEXT:    @%p18 bra $L__BB282_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end1
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd7, %rd8};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd5, %rd6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fminimum ptr  addrspace(1) %addr, <4 x double> %val syncscope("block") acq_rel
        ret <4 x double> %retval
}

define <8 x double> @fminimum_acq_rel_v8f64_global_cta(ptr addrspace(1) %addr, <8 x double> %val) {
; SM90-LABEL: fminimum_acq_rel_v8f64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<37>;
; SM90-NEXT:    .reg .b64 %rd<82>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd17, [fminimum_acq_rel_v8f64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd3, %rd4}, [fminimum_acq_rel_v8f64_global_cta_param_1+48];
; SM90-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [fminimum_acq_rel_v8f64_global_cta_param_1+32];
; SM90-NEXT:    ld.param.v2.b64 {%rd5, %rd6}, [fminimum_acq_rel_v8f64_global_cta_param_1];
; SM90-NEXT:    ld.param.v2.b64 {%rd7, %rd8}, [fminimum_acq_rel_v8f64_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd18, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd18, %rd18};
; SM90-NEXT:    mov.b128 swap, {%rd18, %rd18};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd74, %rd75}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    setp.eq.b64 %p3, %rd5, -9223372036854775808;
; SM90-NEXT:    setp.eq.b64 %p7, %rd6, -9223372036854775808;
; SM90-NEXT:  $L__BB283_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    mov.b64 %rd10, %rd75;
; SM90-NEXT:    mov.b64 %rd9, %rd74;
; SM90-NEXT:    setp.nan.f64 %p1, %rd9, %rd5;
; SM90-NEXT:    min.f64 %rd19, %rd9, %rd5;
; SM90-NEXT:    selp.f64 %rd20, 0d7FF8000000000000, %rd19, %p1;
; SM90-NEXT:    setp.eq.b64 %p2, %rd9, -9223372036854775808;
; SM90-NEXT:    selp.f64 %rd21, %rd9, %rd20, %p2;
; SM90-NEXT:    selp.f64 %rd22, %rd5, %rd21, %p3;
; SM90-NEXT:    setp.eq.f64 %p4, %rd20, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd23, %rd22, %rd20, %p4;
; SM90-NEXT:    setp.nan.f64 %p5, %rd10, %rd6;
; SM90-NEXT:    min.f64 %rd24, %rd10, %rd6;
; SM90-NEXT:    selp.f64 %rd25, 0d7FF8000000000000, %rd24, %p5;
; SM90-NEXT:    setp.eq.b64 %p6, %rd10, -9223372036854775808;
; SM90-NEXT:    selp.f64 %rd26, %rd10, %rd25, %p6;
; SM90-NEXT:    selp.f64 %rd27, %rd6, %rd26, %p7;
; SM90-NEXT:    setp.eq.f64 %p8, %rd25, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd28, %rd27, %rd25, %p8;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd9, %rd10};
; SM90-NEXT:    mov.b128 swap, {%rd23, %rd28};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd74, %rd75}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd29, %rd75, %rd10;
; SM90-NEXT:    xor.b64 %rd30, %rd74, %rd9;
; SM90-NEXT:    or.b64 %rd31, %rd30, %rd29;
; SM90-NEXT:    setp.ne.b64 %p9, %rd31, 0;
; SM90-NEXT:    @%p9 bra $L__BB283_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd32, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd32, %rd32};
; SM90-NEXT:    mov.b128 swap, {%rd32, %rd32};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd76, %rd77}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    setp.eq.b64 %p12, %rd7, -9223372036854775808;
; SM90-NEXT:    setp.eq.b64 %p16, %rd8, -9223372036854775808;
; SM90-NEXT:  $L__BB283_3: // %atomicrmw.start6
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    mov.b64 %rd12, %rd77;
; SM90-NEXT:    mov.b64 %rd11, %rd76;
; SM90-NEXT:    setp.nan.f64 %p10, %rd11, %rd7;
; SM90-NEXT:    min.f64 %rd33, %rd11, %rd7;
; SM90-NEXT:    selp.f64 %rd34, 0d7FF8000000000000, %rd33, %p10;
; SM90-NEXT:    setp.eq.b64 %p11, %rd11, -9223372036854775808;
; SM90-NEXT:    selp.f64 %rd35, %rd11, %rd34, %p11;
; SM90-NEXT:    selp.f64 %rd36, %rd7, %rd35, %p12;
; SM90-NEXT:    setp.eq.f64 %p13, %rd34, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd37, %rd36, %rd34, %p13;
; SM90-NEXT:    setp.nan.f64 %p14, %rd12, %rd8;
; SM90-NEXT:    min.f64 %rd38, %rd12, %rd8;
; SM90-NEXT:    selp.f64 %rd39, 0d7FF8000000000000, %rd38, %p14;
; SM90-NEXT:    setp.eq.b64 %p15, %rd12, -9223372036854775808;
; SM90-NEXT:    selp.f64 %rd40, %rd12, %rd39, %p15;
; SM90-NEXT:    selp.f64 %rd41, %rd8, %rd40, %p16;
; SM90-NEXT:    setp.eq.f64 %p17, %rd39, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd42, %rd41, %rd39, %p17;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd11, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd37, %rd42};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd76, %rd77}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd43, %rd77, %rd12;
; SM90-NEXT:    xor.b64 %rd44, %rd76, %rd11;
; SM90-NEXT:    or.b64 %rd45, %rd44, %rd43;
; SM90-NEXT:    setp.ne.b64 %p18, %rd45, 0;
; SM90-NEXT:    @%p18 bra $L__BB283_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end5
; SM90-NEXT:    mov.b64 %rd46, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd46, %rd46};
; SM90-NEXT:    mov.b128 swap, {%rd46, %rd46};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+32], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd78, %rd79}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    setp.eq.b64 %p21, %rd1, -9223372036854775808;
; SM90-NEXT:    setp.eq.b64 %p25, %rd2, -9223372036854775808;
; SM90-NEXT:  $L__BB283_5: // %atomicrmw.start15
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    setp.nan.f64 %p19, %rd78, %rd1;
; SM90-NEXT:    min.f64 %rd47, %rd78, %rd1;
; SM90-NEXT:    selp.f64 %rd48, 0d7FF8000000000000, %rd47, %p19;
; SM90-NEXT:    setp.eq.b64 %p20, %rd78, -9223372036854775808;
; SM90-NEXT:    selp.f64 %rd49, %rd78, %rd48, %p20;
; SM90-NEXT:    selp.f64 %rd50, %rd1, %rd49, %p21;
; SM90-NEXT:    setp.eq.f64 %p22, %rd48, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd51, %rd50, %rd48, %p22;
; SM90-NEXT:    setp.nan.f64 %p23, %rd79, %rd2;
; SM90-NEXT:    min.f64 %rd52, %rd79, %rd2;
; SM90-NEXT:    selp.f64 %rd53, 0d7FF8000000000000, %rd52, %p23;
; SM90-NEXT:    setp.eq.b64 %p24, %rd79, -9223372036854775808;
; SM90-NEXT:    selp.f64 %rd54, %rd79, %rd53, %p24;
; SM90-NEXT:    selp.f64 %rd55, %rd2, %rd54, %p25;
; SM90-NEXT:    setp.eq.f64 %p26, %rd53, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd56, %rd55, %rd53, %p26;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd78, %rd79};
; SM90-NEXT:    mov.b128 swap, {%rd51, %rd56};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+32], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd13, %rd14}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd57, %rd14, %rd79;
; SM90-NEXT:    xor.b64 %rd58, %rd13, %rd78;
; SM90-NEXT:    or.b64 %rd59, %rd58, %rd57;
; SM90-NEXT:    setp.ne.b64 %p27, %rd59, 0;
; SM90-NEXT:    mov.b64 %rd78, %rd13;
; SM90-NEXT:    mov.b64 %rd79, %rd14;
; SM90-NEXT:    @%p27 bra $L__BB283_5;
; SM90-NEXT:  // %bb.6: // %atomicrmw.end14
; SM90-NEXT:    mov.b64 %rd60, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd60, %rd60};
; SM90-NEXT:    mov.b128 swap, {%rd60, %rd60};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+48], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd80, %rd81}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    setp.eq.b64 %p30, %rd3, -9223372036854775808;
; SM90-NEXT:    setp.eq.b64 %p34, %rd4, -9223372036854775808;
; SM90-NEXT:  $L__BB283_7: // %atomicrmw.start20
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    setp.nan.f64 %p28, %rd80, %rd3;
; SM90-NEXT:    min.f64 %rd61, %rd80, %rd3;
; SM90-NEXT:    selp.f64 %rd62, 0d7FF8000000000000, %rd61, %p28;
; SM90-NEXT:    setp.eq.b64 %p29, %rd80, -9223372036854775808;
; SM90-NEXT:    selp.f64 %rd63, %rd80, %rd62, %p29;
; SM90-NEXT:    selp.f64 %rd64, %rd3, %rd63, %p30;
; SM90-NEXT:    setp.eq.f64 %p31, %rd62, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd65, %rd64, %rd62, %p31;
; SM90-NEXT:    setp.nan.f64 %p32, %rd81, %rd4;
; SM90-NEXT:    min.f64 %rd66, %rd81, %rd4;
; SM90-NEXT:    selp.f64 %rd67, 0d7FF8000000000000, %rd66, %p32;
; SM90-NEXT:    setp.eq.b64 %p33, %rd81, -9223372036854775808;
; SM90-NEXT:    selp.f64 %rd68, %rd81, %rd67, %p33;
; SM90-NEXT:    selp.f64 %rd69, %rd4, %rd68, %p34;
; SM90-NEXT:    setp.eq.f64 %p35, %rd67, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd70, %rd69, %rd67, %p35;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd80, %rd81};
; SM90-NEXT:    mov.b128 swap, {%rd65, %rd70};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+48], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd15, %rd16}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd71, %rd16, %rd81;
; SM90-NEXT:    xor.b64 %rd72, %rd15, %rd80;
; SM90-NEXT:    or.b64 %rd73, %rd72, %rd71;
; SM90-NEXT:    setp.ne.b64 %p36, %rd73, 0;
; SM90-NEXT:    mov.b64 %rd80, %rd15;
; SM90-NEXT:    mov.b64 %rd81, %rd16;
; SM90-NEXT:    @%p36 bra $L__BB283_7;
; SM90-NEXT:  // %bb.8: // %atomicrmw.end19
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+48], {%rd15, %rd16};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+32], {%rd13, %rd14};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd74, %rd75};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd76, %rd77};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fminimum ptr  addrspace(1) %addr, <8 x double> %val syncscope("block") acq_rel
        ret <8 x double> %retval
}

define <1 x double> @fmaximum_acq_rel_v1f64_global_cta(ptr addrspace(1) %addr, <1 x double> %val) {
; SM90-LABEL: fmaximum_acq_rel_v1f64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<6>;
; SM90-NEXT:    .reg .b64 %rd<10>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd3, [fmaximum_acq_rel_v1f64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b64 %rd1, [fmaximum_acq_rel_v1f64_global_cta_param_1];
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd9, [%rd3];
; SM90-NEXT:    setp.eq.b64 %p3, %rd1, 0;
; SM90-NEXT:  $L__BB284_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    setp.nan.f64 %p1, %rd9, %rd1;
; SM90-NEXT:    max.f64 %rd4, %rd9, %rd1;
; SM90-NEXT:    selp.f64 %rd5, 0d7FF8000000000000, %rd4, %p1;
; SM90-NEXT:    setp.eq.b64 %p2, %rd9, 0;
; SM90-NEXT:    selp.f64 %rd6, %rd9, %rd5, %p2;
; SM90-NEXT:    selp.f64 %rd7, %rd1, %rd6, %p3;
; SM90-NEXT:    setp.eq.f64 %p4, %rd5, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd8, %rd7, %rd5, %p4;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd2, [%rd3], %rd9, %rd8;
; SM90-NEXT:    setp.ne.b64 %p5, %rd2, %rd9;
; SM90-NEXT:    mov.b64 %rd9, %rd2;
; SM90-NEXT:    @%p5 bra $L__BB284_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b64 [func_retval0], %rd2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmaximum ptr  addrspace(1) %addr, <1 x double> %val syncscope("block") acq_rel
        ret <1 x double> %retval
}

define <2 x double> @fmaximum_acq_rel_v2f64_global_cta(ptr addrspace(1) %addr, <2 x double> %val) {
; SM90-LABEL: fmaximum_acq_rel_v2f64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<10>;
; SM90-NEXT:    .reg .b64 %rd<22>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b64 {%rd4, %rd5}, [fmaximum_acq_rel_v2f64_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd3, [fmaximum_acq_rel_v2f64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd6, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd6, %rd6};
; SM90-NEXT:    mov.b128 swap, {%rd6, %rd6};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd3], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd20, %rd21}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    setp.eq.b64 %p3, %rd4, 0;
; SM90-NEXT:    setp.eq.b64 %p7, %rd5, 0;
; SM90-NEXT:  $L__BB285_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    setp.nan.f64 %p1, %rd20, %rd4;
; SM90-NEXT:    max.f64 %rd7, %rd20, %rd4;
; SM90-NEXT:    selp.f64 %rd8, 0d7FF8000000000000, %rd7, %p1;
; SM90-NEXT:    setp.eq.b64 %p2, %rd20, 0;
; SM90-NEXT:    selp.f64 %rd9, %rd20, %rd8, %p2;
; SM90-NEXT:    selp.f64 %rd10, %rd4, %rd9, %p3;
; SM90-NEXT:    setp.eq.f64 %p4, %rd8, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd11, %rd10, %rd8, %p4;
; SM90-NEXT:    setp.nan.f64 %p5, %rd21, %rd5;
; SM90-NEXT:    max.f64 %rd12, %rd21, %rd5;
; SM90-NEXT:    selp.f64 %rd13, 0d7FF8000000000000, %rd12, %p5;
; SM90-NEXT:    setp.eq.b64 %p6, %rd21, 0;
; SM90-NEXT:    selp.f64 %rd14, %rd21, %rd13, %p6;
; SM90-NEXT:    selp.f64 %rd15, %rd5, %rd14, %p7;
; SM90-NEXT:    setp.eq.f64 %p8, %rd13, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd16, %rd15, %rd13, %p8;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd20, %rd21};
; SM90-NEXT:    mov.b128 swap, {%rd11, %rd16};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd3], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd1, %rd2}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd17, %rd2, %rd21;
; SM90-NEXT:    xor.b64 %rd18, %rd1, %rd20;
; SM90-NEXT:    or.b64 %rd19, %rd18, %rd17;
; SM90-NEXT:    setp.ne.b64 %p9, %rd19, 0;
; SM90-NEXT:    mov.b64 %rd20, %rd1;
; SM90-NEXT:    mov.b64 %rd21, %rd2;
; SM90-NEXT:    @%p9 bra $L__BB285_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd1, %rd2};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmaximum ptr  addrspace(1) %addr, <2 x double> %val syncscope("block") acq_rel
        ret <2 x double> %retval
}

define <4 x double> @fmaximum_acq_rel_v4f64_global_cta(ptr addrspace(1) %addr, <4 x double> %val) {
; SM90-LABEL: fmaximum_acq_rel_v4f64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<19>;
; SM90-NEXT:    .reg .b64 %rd<42>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd9, [fmaximum_acq_rel_v4f64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [fmaximum_acq_rel_v4f64_global_cta_param_1];
; SM90-NEXT:    ld.param.v2.b64 {%rd3, %rd4}, [fmaximum_acq_rel_v4f64_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd10, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd10, %rd10};
; SM90-NEXT:    mov.b128 swap, {%rd10, %rd10};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd38, %rd39}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    setp.eq.b64 %p3, %rd1, 0;
; SM90-NEXT:    setp.eq.b64 %p7, %rd2, 0;
; SM90-NEXT:  $L__BB286_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    setp.nan.f64 %p1, %rd38, %rd1;
; SM90-NEXT:    max.f64 %rd11, %rd38, %rd1;
; SM90-NEXT:    selp.f64 %rd12, 0d7FF8000000000000, %rd11, %p1;
; SM90-NEXT:    setp.eq.b64 %p2, %rd38, 0;
; SM90-NEXT:    selp.f64 %rd13, %rd38, %rd12, %p2;
; SM90-NEXT:    selp.f64 %rd14, %rd1, %rd13, %p3;
; SM90-NEXT:    setp.eq.f64 %p4, %rd12, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd15, %rd14, %rd12, %p4;
; SM90-NEXT:    setp.nan.f64 %p5, %rd39, %rd2;
; SM90-NEXT:    max.f64 %rd16, %rd39, %rd2;
; SM90-NEXT:    selp.f64 %rd17, 0d7FF8000000000000, %rd16, %p5;
; SM90-NEXT:    setp.eq.b64 %p6, %rd39, 0;
; SM90-NEXT:    selp.f64 %rd18, %rd39, %rd17, %p6;
; SM90-NEXT:    selp.f64 %rd19, %rd2, %rd18, %p7;
; SM90-NEXT:    setp.eq.f64 %p8, %rd17, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd20, %rd19, %rd17, %p8;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd38, %rd39};
; SM90-NEXT:    mov.b128 swap, {%rd15, %rd20};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd5, %rd6}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd21, %rd6, %rd39;
; SM90-NEXT:    xor.b64 %rd22, %rd5, %rd38;
; SM90-NEXT:    or.b64 %rd23, %rd22, %rd21;
; SM90-NEXT:    setp.ne.b64 %p9, %rd23, 0;
; SM90-NEXT:    mov.b64 %rd38, %rd5;
; SM90-NEXT:    mov.b64 %rd39, %rd6;
; SM90-NEXT:    @%p9 bra $L__BB286_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd24, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd24, %rd24};
; SM90-NEXT:    mov.b128 swap, {%rd24, %rd24};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd40, %rd41}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    setp.eq.b64 %p12, %rd3, 0;
; SM90-NEXT:    setp.eq.b64 %p16, %rd4, 0;
; SM90-NEXT:  $L__BB286_3: // %atomicrmw.start2
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    setp.nan.f64 %p10, %rd40, %rd3;
; SM90-NEXT:    max.f64 %rd25, %rd40, %rd3;
; SM90-NEXT:    selp.f64 %rd26, 0d7FF8000000000000, %rd25, %p10;
; SM90-NEXT:    setp.eq.b64 %p11, %rd40, 0;
; SM90-NEXT:    selp.f64 %rd27, %rd40, %rd26, %p11;
; SM90-NEXT:    selp.f64 %rd28, %rd3, %rd27, %p12;
; SM90-NEXT:    setp.eq.f64 %p13, %rd26, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd29, %rd28, %rd26, %p13;
; SM90-NEXT:    setp.nan.f64 %p14, %rd41, %rd4;
; SM90-NEXT:    max.f64 %rd30, %rd41, %rd4;
; SM90-NEXT:    selp.f64 %rd31, 0d7FF8000000000000, %rd30, %p14;
; SM90-NEXT:    setp.eq.b64 %p15, %rd41, 0;
; SM90-NEXT:    selp.f64 %rd32, %rd41, %rd31, %p15;
; SM90-NEXT:    selp.f64 %rd33, %rd4, %rd32, %p16;
; SM90-NEXT:    setp.eq.f64 %p17, %rd31, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd34, %rd33, %rd31, %p17;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd40, %rd41};
; SM90-NEXT:    mov.b128 swap, {%rd29, %rd34};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd9+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd7, %rd8}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd35, %rd8, %rd41;
; SM90-NEXT:    xor.b64 %rd36, %rd7, %rd40;
; SM90-NEXT:    or.b64 %rd37, %rd36, %rd35;
; SM90-NEXT:    setp.ne.b64 %p18, %rd37, 0;
; SM90-NEXT:    mov.b64 %rd40, %rd7;
; SM90-NEXT:    mov.b64 %rd41, %rd8;
; SM90-NEXT:    @%p18 bra $L__BB286_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end1
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd7, %rd8};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd5, %rd6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmaximum ptr  addrspace(1) %addr, <4 x double> %val syncscope("block") acq_rel
        ret <4 x double> %retval
}

define <8 x double> @fmaximum_acq_rel_v8f64_global_cta(ptr addrspace(1) %addr, <8 x double> %val) {
; SM90-LABEL: fmaximum_acq_rel_v8f64_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<37>;
; SM90-NEXT:    .reg .b64 %rd<82>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd17, [fmaximum_acq_rel_v8f64_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b64 {%rd3, %rd4}, [fmaximum_acq_rel_v8f64_global_cta_param_1+48];
; SM90-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [fmaximum_acq_rel_v8f64_global_cta_param_1+32];
; SM90-NEXT:    ld.param.v2.b64 {%rd5, %rd6}, [fmaximum_acq_rel_v8f64_global_cta_param_1];
; SM90-NEXT:    ld.param.v2.b64 {%rd7, %rd8}, [fmaximum_acq_rel_v8f64_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd18, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd18, %rd18};
; SM90-NEXT:    mov.b128 swap, {%rd18, %rd18};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd74, %rd75}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    setp.eq.b64 %p3, %rd5, 0;
; SM90-NEXT:    setp.eq.b64 %p7, %rd6, 0;
; SM90-NEXT:  $L__BB287_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    mov.b64 %rd10, %rd75;
; SM90-NEXT:    mov.b64 %rd9, %rd74;
; SM90-NEXT:    setp.nan.f64 %p1, %rd9, %rd5;
; SM90-NEXT:    max.f64 %rd19, %rd9, %rd5;
; SM90-NEXT:    selp.f64 %rd20, 0d7FF8000000000000, %rd19, %p1;
; SM90-NEXT:    setp.eq.b64 %p2, %rd9, 0;
; SM90-NEXT:    selp.f64 %rd21, %rd9, %rd20, %p2;
; SM90-NEXT:    selp.f64 %rd22, %rd5, %rd21, %p3;
; SM90-NEXT:    setp.eq.f64 %p4, %rd20, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd23, %rd22, %rd20, %p4;
; SM90-NEXT:    setp.nan.f64 %p5, %rd10, %rd6;
; SM90-NEXT:    max.f64 %rd24, %rd10, %rd6;
; SM90-NEXT:    selp.f64 %rd25, 0d7FF8000000000000, %rd24, %p5;
; SM90-NEXT:    setp.eq.b64 %p6, %rd10, 0;
; SM90-NEXT:    selp.f64 %rd26, %rd10, %rd25, %p6;
; SM90-NEXT:    selp.f64 %rd27, %rd6, %rd26, %p7;
; SM90-NEXT:    setp.eq.f64 %p8, %rd25, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd28, %rd27, %rd25, %p8;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd9, %rd10};
; SM90-NEXT:    mov.b128 swap, {%rd23, %rd28};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd74, %rd75}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd29, %rd75, %rd10;
; SM90-NEXT:    xor.b64 %rd30, %rd74, %rd9;
; SM90-NEXT:    or.b64 %rd31, %rd30, %rd29;
; SM90-NEXT:    setp.ne.b64 %p9, %rd31, 0;
; SM90-NEXT:    @%p9 bra $L__BB287_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd32, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd32, %rd32};
; SM90-NEXT:    mov.b128 swap, {%rd32, %rd32};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd76, %rd77}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    setp.eq.b64 %p12, %rd7, 0;
; SM90-NEXT:    setp.eq.b64 %p16, %rd8, 0;
; SM90-NEXT:  $L__BB287_3: // %atomicrmw.start6
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    mov.b64 %rd12, %rd77;
; SM90-NEXT:    mov.b64 %rd11, %rd76;
; SM90-NEXT:    setp.nan.f64 %p10, %rd11, %rd7;
; SM90-NEXT:    max.f64 %rd33, %rd11, %rd7;
; SM90-NEXT:    selp.f64 %rd34, 0d7FF8000000000000, %rd33, %p10;
; SM90-NEXT:    setp.eq.b64 %p11, %rd11, 0;
; SM90-NEXT:    selp.f64 %rd35, %rd11, %rd34, %p11;
; SM90-NEXT:    selp.f64 %rd36, %rd7, %rd35, %p12;
; SM90-NEXT:    setp.eq.f64 %p13, %rd34, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd37, %rd36, %rd34, %p13;
; SM90-NEXT:    setp.nan.f64 %p14, %rd12, %rd8;
; SM90-NEXT:    max.f64 %rd38, %rd12, %rd8;
; SM90-NEXT:    selp.f64 %rd39, 0d7FF8000000000000, %rd38, %p14;
; SM90-NEXT:    setp.eq.b64 %p15, %rd12, 0;
; SM90-NEXT:    selp.f64 %rd40, %rd12, %rd39, %p15;
; SM90-NEXT:    selp.f64 %rd41, %rd8, %rd40, %p16;
; SM90-NEXT:    setp.eq.f64 %p17, %rd39, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd42, %rd41, %rd39, %p17;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd11, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd37, %rd42};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd76, %rd77}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd43, %rd77, %rd12;
; SM90-NEXT:    xor.b64 %rd44, %rd76, %rd11;
; SM90-NEXT:    or.b64 %rd45, %rd44, %rd43;
; SM90-NEXT:    setp.ne.b64 %p18, %rd45, 0;
; SM90-NEXT:    @%p18 bra $L__BB287_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end5
; SM90-NEXT:    mov.b64 %rd46, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd46, %rd46};
; SM90-NEXT:    mov.b128 swap, {%rd46, %rd46};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+32], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd78, %rd79}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    setp.eq.b64 %p21, %rd1, 0;
; SM90-NEXT:    setp.eq.b64 %p25, %rd2, 0;
; SM90-NEXT:  $L__BB287_5: // %atomicrmw.start15
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    setp.nan.f64 %p19, %rd78, %rd1;
; SM90-NEXT:    max.f64 %rd47, %rd78, %rd1;
; SM90-NEXT:    selp.f64 %rd48, 0d7FF8000000000000, %rd47, %p19;
; SM90-NEXT:    setp.eq.b64 %p20, %rd78, 0;
; SM90-NEXT:    selp.f64 %rd49, %rd78, %rd48, %p20;
; SM90-NEXT:    selp.f64 %rd50, %rd1, %rd49, %p21;
; SM90-NEXT:    setp.eq.f64 %p22, %rd48, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd51, %rd50, %rd48, %p22;
; SM90-NEXT:    setp.nan.f64 %p23, %rd79, %rd2;
; SM90-NEXT:    max.f64 %rd52, %rd79, %rd2;
; SM90-NEXT:    selp.f64 %rd53, 0d7FF8000000000000, %rd52, %p23;
; SM90-NEXT:    setp.eq.b64 %p24, %rd79, 0;
; SM90-NEXT:    selp.f64 %rd54, %rd79, %rd53, %p24;
; SM90-NEXT:    selp.f64 %rd55, %rd2, %rd54, %p25;
; SM90-NEXT:    setp.eq.f64 %p26, %rd53, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd56, %rd55, %rd53, %p26;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd78, %rd79};
; SM90-NEXT:    mov.b128 swap, {%rd51, %rd56};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+32], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd13, %rd14}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd57, %rd14, %rd79;
; SM90-NEXT:    xor.b64 %rd58, %rd13, %rd78;
; SM90-NEXT:    or.b64 %rd59, %rd58, %rd57;
; SM90-NEXT:    setp.ne.b64 %p27, %rd59, 0;
; SM90-NEXT:    mov.b64 %rd78, %rd13;
; SM90-NEXT:    mov.b64 %rd79, %rd14;
; SM90-NEXT:    @%p27 bra $L__BB287_5;
; SM90-NEXT:  // %bb.6: // %atomicrmw.end14
; SM90-NEXT:    mov.b64 %rd60, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd60, %rd60};
; SM90-NEXT:    mov.b128 swap, {%rd60, %rd60};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+48], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd80, %rd81}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    setp.eq.b64 %p30, %rd3, 0;
; SM90-NEXT:    setp.eq.b64 %p34, %rd4, 0;
; SM90-NEXT:  $L__BB287_7: // %atomicrmw.start20
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    setp.nan.f64 %p28, %rd80, %rd3;
; SM90-NEXT:    max.f64 %rd61, %rd80, %rd3;
; SM90-NEXT:    selp.f64 %rd62, 0d7FF8000000000000, %rd61, %p28;
; SM90-NEXT:    setp.eq.b64 %p29, %rd80, 0;
; SM90-NEXT:    selp.f64 %rd63, %rd80, %rd62, %p29;
; SM90-NEXT:    selp.f64 %rd64, %rd3, %rd63, %p30;
; SM90-NEXT:    setp.eq.f64 %p31, %rd62, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd65, %rd64, %rd62, %p31;
; SM90-NEXT:    setp.nan.f64 %p32, %rd81, %rd4;
; SM90-NEXT:    max.f64 %rd66, %rd81, %rd4;
; SM90-NEXT:    selp.f64 %rd67, 0d7FF8000000000000, %rd66, %p32;
; SM90-NEXT:    setp.eq.b64 %p33, %rd81, 0;
; SM90-NEXT:    selp.f64 %rd68, %rd81, %rd67, %p33;
; SM90-NEXT:    selp.f64 %rd69, %rd4, %rd68, %p34;
; SM90-NEXT:    setp.eq.f64 %p35, %rd67, 0d0000000000000000;
; SM90-NEXT:    selp.f64 %rd70, %rd69, %rd67, %p35;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd80, %rd81};
; SM90-NEXT:    mov.b128 swap, {%rd65, %rd70};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd17+48], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd15, %rd16}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd71, %rd16, %rd81;
; SM90-NEXT:    xor.b64 %rd72, %rd15, %rd80;
; SM90-NEXT:    or.b64 %rd73, %rd72, %rd71;
; SM90-NEXT:    setp.ne.b64 %p36, %rd73, 0;
; SM90-NEXT:    mov.b64 %rd80, %rd15;
; SM90-NEXT:    mov.b64 %rd81, %rd16;
; SM90-NEXT:    @%p36 bra $L__BB287_7;
; SM90-NEXT:  // %bb.8: // %atomicrmw.end19
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b64 [func_retval0+48], {%rd15, %rd16};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+32], {%rd13, %rd14};
; SM90-NEXT:    st.param.v2.b64 [func_retval0], {%rd74, %rd75};
; SM90-NEXT:    st.param.v2.b64 [func_retval0+16], {%rd76, %rd77};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmaximum ptr  addrspace(1) %addr, <8 x double> %val syncscope("block") acq_rel
        ret <8 x double> %retval
}

define <1 x half> @fadd_acq_rel_v1f16_global_cta(ptr addrspace(1) %addr, <1 x half> %val) {
; SM90-LABEL: fadd_acq_rel_v1f16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b16 %rs<3>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [fadd_acq_rel_v1f16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b16 %rs1, [fadd_acq_rel_v1f16_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.f16 %rs2, [%rd1], %rs1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %rs2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fadd ptr  addrspace(1) %addr, <1 x half> %val syncscope("block") acq_rel
        ret <1 x half> %retval
}

define <2 x half> @fadd_acq_rel_v2f16_global_cta(ptr addrspace(1) %addr, <2 x half> %val) {
; SM90-LABEL: fadd_acq_rel_v2f16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b16 %rs<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [fadd_acq_rel_v2f16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b16 {%rs1, %rs2}, [fadd_acq_rel_v2f16_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.f16 %rs3, [%rd1], %rs1;
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.f16 %rs4, [%rd1+2], %rs2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b16 [func_retval0], {%rs3, %rs4};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fadd ptr  addrspace(1) %addr, <2 x half> %val syncscope("block") acq_rel
        ret <2 x half> %retval
}

define <4 x half> @fadd_acq_rel_v4f16_global_cta(ptr addrspace(1) %addr, <4 x half> %val) {
; SM90-LABEL: fadd_acq_rel_v4f16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b16 %rs<9>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [fadd_acq_rel_v4f16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b16 {%rs1, %rs2, %rs3, %rs4}, [fadd_acq_rel_v4f16_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.f16 %rs5, [%rd1], %rs1;
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.f16 %rs6, [%rd1+2], %rs2;
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.f16 %rs7, [%rd1+4], %rs3;
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.f16 %rs8, [%rd1+6], %rs4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b16 [func_retval0], {%rs5, %rs6, %rs7, %rs8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fadd ptr  addrspace(1) %addr, <4 x half> %val syncscope("block") acq_rel
        ret <4 x half> %retval
}

define <8 x half> @fadd_acq_rel_v8f16_global_cta(ptr addrspace(1) %addr, <8 x half> %val) {
; SM90-LABEL: fadd_acq_rel_v8f16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b16 %rs<17>;
; SM90-NEXT:    .reg .b32 %r<9>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [fadd_acq_rel_v8f16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fadd_acq_rel_v8f16_global_cta_param_1];
; SM90-NEXT:    mov.b32 {%rs1, %rs2}, %r4;
; SM90-NEXT:    mov.b32 {%rs3, %rs4}, %r3;
; SM90-NEXT:    mov.b32 {%rs5, %rs6}, %r2;
; SM90-NEXT:    mov.b32 {%rs7, %rs8}, %r1;
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.f16 %rs9, [%rd1], %rs7;
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.f16 %rs10, [%rd1+2], %rs8;
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.f16 %rs11, [%rd1+4], %rs5;
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.f16 %rs12, [%rd1+6], %rs6;
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.f16 %rs13, [%rd1+8], %rs3;
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.f16 %rs14, [%rd1+10], %rs4;
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.f16 %rs15, [%rd1+12], %rs1;
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.f16 %rs16, [%rd1+14], %rs2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    mov.b32 %r5, {%rs9, %rs10};
; SM90-NEXT:    mov.b32 %r6, {%rs11, %rs12};
; SM90-NEXT:    mov.b32 %r7, {%rs13, %rs14};
; SM90-NEXT:    mov.b32 %r8, {%rs15, %rs16};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fadd ptr  addrspace(1) %addr, <8 x half> %val syncscope("block") acq_rel
        ret <8 x half> %retval
}

define <1 x half> @fsub_acq_rel_v1f16_global_cta(ptr addrspace(1) %addr, <1 x half> %val) {
; SM90-LABEL: fsub_acq_rel_v1f16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<4>;
; SM90-NEXT:    .reg .b32 %r<15>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [fsub_acq_rel_v1f16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b16 %rs1, [fsub_acq_rel_v1f16_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r4, %rd2;
; SM90-NEXT:    and.b32 %r5, %r4, 3;
; SM90-NEXT:    shl.b32 %r1, %r5, 3;
; SM90-NEXT:    mov.b32 %r6, 65535;
; SM90-NEXT:    shl.b32 %r7, %r6, %r1;
; SM90-NEXT:    not.b32 %r2, %r7;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r14, [%rd1];
; SM90-NEXT:  $L__BB292_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r8, %r14, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r8;
; SM90-NEXT:    sub.rn.f16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r9, %rs3;
; SM90-NEXT:    shl.b32 %r10, %r9, %r1;
; SM90-NEXT:    and.b32 %r11, %r14, %r2;
; SM90-NEXT:    or.b32 %r12, %r11, %r10;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r14, %r12;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r14;
; SM90-NEXT:    mov.b32 %r14, %r3;
; SM90-NEXT:    @%p1 bra $L__BB292_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r13, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r13;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fsub ptr  addrspace(1) %addr, <1 x half> %val syncscope("block") acq_rel
        ret <1 x half> %retval
}

define <2 x half> @fsub_acq_rel_v2f16_global_cta(ptr addrspace(1) %addr, <2 x half> %val) {
; SM90-LABEL: fsub_acq_rel_v2f16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [fsub_acq_rel_v2f16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fsub_acq_rel_v2f16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:  $L__BB293_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    sub.rn.f16x2 %r3, %r4, %r2;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r4;
; SM90-NEXT:    mov.b32 %r4, %r1;
; SM90-NEXT:    @%p1 bra $L__BB293_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fsub ptr  addrspace(1) %addr, <2 x half> %val syncscope("block") acq_rel
        ret <2 x half> %retval
}

define <4 x half> @fsub_acq_rel_v4f16_global_cta(ptr addrspace(1) %addr, <4 x half> %val) {
; SM90-LABEL: fsub_acq_rel_v4f16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [fsub_acq_rel_v4f16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fsub_acq_rel_v4f16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB294_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    sub.rn.f16x2 %r3, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r3;
; SM90-NEXT:    sub.rn.f16x2 %r4, %r6, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r4;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB294_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fsub ptr  addrspace(1) %addr, <4 x half> %val syncscope("block") acq_rel
        ret <4 x half> %retval
}

define <8 x half> @fsub_acq_rel_v8f16_global_cta(ptr addrspace(1) %addr, <8 x half> %val) {
; SM90-LABEL: fsub_acq_rel_v8f16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fsub_acq_rel_v8f16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fsub_acq_rel_v8f16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB295_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    sub.rn.f16x2 %r5, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd5, %r5;
; SM90-NEXT:    sub.rn.f16x2 %r6, %r10, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r6;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    sub.rn.f16x2 %r7, %r11, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r7;
; SM90-NEXT:    sub.rn.f16x2 %r8, %r12, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r8;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r10;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r12;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd22;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB295_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fsub ptr  addrspace(1) %addr, <8 x half> %val syncscope("block") acq_rel
        ret <8 x half> %retval
}

define <1 x half> @fmin_acq_rel_v1f16_global_cta(ptr addrspace(1) %addr, <1 x half> %val) {
; SM90-LABEL: fmin_acq_rel_v1f16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<4>;
; SM90-NEXT:    .reg .b32 %r<15>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [fmin_acq_rel_v1f16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b16 %rs1, [fmin_acq_rel_v1f16_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r4, %rd2;
; SM90-NEXT:    and.b32 %r5, %r4, 3;
; SM90-NEXT:    shl.b32 %r1, %r5, 3;
; SM90-NEXT:    mov.b32 %r6, 65535;
; SM90-NEXT:    shl.b32 %r7, %r6, %r1;
; SM90-NEXT:    not.b32 %r2, %r7;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r14, [%rd1];
; SM90-NEXT:  $L__BB296_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r8, %r14, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r8;
; SM90-NEXT:    min.f16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r9, %rs3;
; SM90-NEXT:    shl.b32 %r10, %r9, %r1;
; SM90-NEXT:    and.b32 %r11, %r14, %r2;
; SM90-NEXT:    or.b32 %r12, %r11, %r10;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r14, %r12;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r14;
; SM90-NEXT:    mov.b32 %r14, %r3;
; SM90-NEXT:    @%p1 bra $L__BB296_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r13, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r13;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmin ptr  addrspace(1) %addr, <1 x half> %val syncscope("block") acq_rel
        ret <1 x half> %retval
}

define <2 x half> @fmin_acq_rel_v2f16_global_cta(ptr addrspace(1) %addr, <2 x half> %val) {
; SM90-LABEL: fmin_acq_rel_v2f16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [fmin_acq_rel_v2f16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fmin_acq_rel_v2f16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:  $L__BB297_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.f16x2 %r3, %r4, %r2;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r4;
; SM90-NEXT:    mov.b32 %r4, %r1;
; SM90-NEXT:    @%p1 bra $L__BB297_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmin ptr  addrspace(1) %addr, <2 x half> %val syncscope("block") acq_rel
        ret <2 x half> %retval
}

define <4 x half> @fmin_acq_rel_v4f16_global_cta(ptr addrspace(1) %addr, <4 x half> %val) {
; SM90-LABEL: fmin_acq_rel_v4f16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [fmin_acq_rel_v4f16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fmin_acq_rel_v4f16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB298_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.f16x2 %r3, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r3;
; SM90-NEXT:    min.f16x2 %r4, %r6, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r4;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB298_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmin ptr  addrspace(1) %addr, <4 x half> %val syncscope("block") acq_rel
        ret <4 x half> %retval
}

define <8 x half> @fmin_acq_rel_v8f16_global_cta(ptr addrspace(1) %addr, <8 x half> %val) {
; SM90-LABEL: fmin_acq_rel_v8f16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fmin_acq_rel_v8f16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fmin_acq_rel_v8f16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB299_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.f16x2 %r5, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd5, %r5;
; SM90-NEXT:    min.f16x2 %r6, %r10, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r6;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    min.f16x2 %r7, %r11, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r7;
; SM90-NEXT:    min.f16x2 %r8, %r12, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r8;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r10;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r12;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd22;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB299_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmin ptr  addrspace(1) %addr, <8 x half> %val syncscope("block") acq_rel
        ret <8 x half> %retval
}

define <1 x half> @fmax_acq_rel_v1f16_global_cta(ptr addrspace(1) %addr, <1 x half> %val) {
; SM90-LABEL: fmax_acq_rel_v1f16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<4>;
; SM90-NEXT:    .reg .b32 %r<15>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [fmax_acq_rel_v1f16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b16 %rs1, [fmax_acq_rel_v1f16_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r4, %rd2;
; SM90-NEXT:    and.b32 %r5, %r4, 3;
; SM90-NEXT:    shl.b32 %r1, %r5, 3;
; SM90-NEXT:    mov.b32 %r6, 65535;
; SM90-NEXT:    shl.b32 %r7, %r6, %r1;
; SM90-NEXT:    not.b32 %r2, %r7;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r14, [%rd1];
; SM90-NEXT:  $L__BB300_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r8, %r14, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r8;
; SM90-NEXT:    max.f16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r9, %rs3;
; SM90-NEXT:    shl.b32 %r10, %r9, %r1;
; SM90-NEXT:    and.b32 %r11, %r14, %r2;
; SM90-NEXT:    or.b32 %r12, %r11, %r10;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r14, %r12;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r14;
; SM90-NEXT:    mov.b32 %r14, %r3;
; SM90-NEXT:    @%p1 bra $L__BB300_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r13, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r13;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmax ptr  addrspace(1) %addr, <1 x half> %val syncscope("block") acq_rel
        ret <1 x half> %retval
}

define <2 x half> @fmax_acq_rel_v2f16_global_cta(ptr addrspace(1) %addr, <2 x half> %val) {
; SM90-LABEL: fmax_acq_rel_v2f16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [fmax_acq_rel_v2f16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fmax_acq_rel_v2f16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:  $L__BB301_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.f16x2 %r3, %r4, %r2;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r4;
; SM90-NEXT:    mov.b32 %r4, %r1;
; SM90-NEXT:    @%p1 bra $L__BB301_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmax ptr  addrspace(1) %addr, <2 x half> %val syncscope("block") acq_rel
        ret <2 x half> %retval
}

define <4 x half> @fmax_acq_rel_v4f16_global_cta(ptr addrspace(1) %addr, <4 x half> %val) {
; SM90-LABEL: fmax_acq_rel_v4f16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [fmax_acq_rel_v4f16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fmax_acq_rel_v4f16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB302_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.f16x2 %r3, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r3;
; SM90-NEXT:    max.f16x2 %r4, %r6, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r4;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB302_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmax ptr  addrspace(1) %addr, <4 x half> %val syncscope("block") acq_rel
        ret <4 x half> %retval
}

define <8 x half> @fmax_acq_rel_v8f16_global_cta(ptr addrspace(1) %addr, <8 x half> %val) {
; SM90-LABEL: fmax_acq_rel_v8f16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fmax_acq_rel_v8f16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fmax_acq_rel_v8f16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB303_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.f16x2 %r5, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd5, %r5;
; SM90-NEXT:    max.f16x2 %r6, %r10, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r6;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    max.f16x2 %r7, %r11, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r7;
; SM90-NEXT:    max.f16x2 %r8, %r12, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r8;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r10;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r12;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd22;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB303_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmax ptr  addrspace(1) %addr, <8 x half> %val syncscope("block") acq_rel
        ret <8 x half> %retval
}

define <1 x half> @fminimum_acq_rel_v1f16_global_cta(ptr addrspace(1) %addr, <1 x half> %val) {
; SM90-LABEL: fminimum_acq_rel_v1f16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<4>;
; SM90-NEXT:    .reg .b32 %r<15>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [fminimum_acq_rel_v1f16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b16 %rs1, [fminimum_acq_rel_v1f16_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r4, %rd2;
; SM90-NEXT:    and.b32 %r5, %r4, 3;
; SM90-NEXT:    shl.b32 %r1, %r5, 3;
; SM90-NEXT:    mov.b32 %r6, 65535;
; SM90-NEXT:    shl.b32 %r7, %r6, %r1;
; SM90-NEXT:    not.b32 %r2, %r7;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r14, [%rd1];
; SM90-NEXT:  $L__BB304_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r8, %r14, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r8;
; SM90-NEXT:    min.NaN.f16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r9, %rs3;
; SM90-NEXT:    shl.b32 %r10, %r9, %r1;
; SM90-NEXT:    and.b32 %r11, %r14, %r2;
; SM90-NEXT:    or.b32 %r12, %r11, %r10;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r14, %r12;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r14;
; SM90-NEXT:    mov.b32 %r14, %r3;
; SM90-NEXT:    @%p1 bra $L__BB304_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r13, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r13;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fminimum ptr  addrspace(1) %addr, <1 x half> %val syncscope("block") acq_rel
        ret <1 x half> %retval
}

define <2 x half> @fminimum_acq_rel_v2f16_global_cta(ptr addrspace(1) %addr, <2 x half> %val) {
; SM90-LABEL: fminimum_acq_rel_v2f16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [fminimum_acq_rel_v2f16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fminimum_acq_rel_v2f16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:  $L__BB305_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.NaN.f16x2 %r3, %r4, %r2;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r4;
; SM90-NEXT:    mov.b32 %r4, %r1;
; SM90-NEXT:    @%p1 bra $L__BB305_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fminimum ptr  addrspace(1) %addr, <2 x half> %val syncscope("block") acq_rel
        ret <2 x half> %retval
}

define <4 x half> @fminimum_acq_rel_v4f16_global_cta(ptr addrspace(1) %addr, <4 x half> %val) {
; SM90-LABEL: fminimum_acq_rel_v4f16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [fminimum_acq_rel_v4f16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fminimum_acq_rel_v4f16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB306_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.NaN.f16x2 %r3, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r3;
; SM90-NEXT:    min.NaN.f16x2 %r4, %r6, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r4;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB306_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fminimum ptr  addrspace(1) %addr, <4 x half> %val syncscope("block") acq_rel
        ret <4 x half> %retval
}

define <8 x half> @fminimum_acq_rel_v8f16_global_cta(ptr addrspace(1) %addr, <8 x half> %val) {
; SM90-LABEL: fminimum_acq_rel_v8f16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fminimum_acq_rel_v8f16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fminimum_acq_rel_v8f16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB307_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.NaN.f16x2 %r5, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd5, %r5;
; SM90-NEXT:    min.NaN.f16x2 %r6, %r10, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r6;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    min.NaN.f16x2 %r7, %r11, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r7;
; SM90-NEXT:    min.NaN.f16x2 %r8, %r12, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r8;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r10;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r12;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd22;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB307_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fminimum ptr  addrspace(1) %addr, <8 x half> %val syncscope("block") acq_rel
        ret <8 x half> %retval
}

define <1 x half> @fmaximum_acq_rel_v1f16_global_cta(ptr addrspace(1) %addr, <1 x half> %val) {
; SM90-LABEL: fmaximum_acq_rel_v1f16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<4>;
; SM90-NEXT:    .reg .b32 %r<15>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [fmaximum_acq_rel_v1f16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b16 %rs1, [fmaximum_acq_rel_v1f16_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r4, %rd2;
; SM90-NEXT:    and.b32 %r5, %r4, 3;
; SM90-NEXT:    shl.b32 %r1, %r5, 3;
; SM90-NEXT:    mov.b32 %r6, 65535;
; SM90-NEXT:    shl.b32 %r7, %r6, %r1;
; SM90-NEXT:    not.b32 %r2, %r7;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r14, [%rd1];
; SM90-NEXT:  $L__BB308_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r8, %r14, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r8;
; SM90-NEXT:    max.NaN.f16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r9, %rs3;
; SM90-NEXT:    shl.b32 %r10, %r9, %r1;
; SM90-NEXT:    and.b32 %r11, %r14, %r2;
; SM90-NEXT:    or.b32 %r12, %r11, %r10;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r14, %r12;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r14;
; SM90-NEXT:    mov.b32 %r14, %r3;
; SM90-NEXT:    @%p1 bra $L__BB308_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r13, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r13;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmaximum ptr  addrspace(1) %addr, <1 x half> %val syncscope("block") acq_rel
        ret <1 x half> %retval
}

define <2 x half> @fmaximum_acq_rel_v2f16_global_cta(ptr addrspace(1) %addr, <2 x half> %val) {
; SM90-LABEL: fmaximum_acq_rel_v2f16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [fmaximum_acq_rel_v2f16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fmaximum_acq_rel_v2f16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:  $L__BB309_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.NaN.f16x2 %r3, %r4, %r2;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r4;
; SM90-NEXT:    mov.b32 %r4, %r1;
; SM90-NEXT:    @%p1 bra $L__BB309_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmaximum ptr  addrspace(1) %addr, <2 x half> %val syncscope("block") acq_rel
        ret <2 x half> %retval
}

define <4 x half> @fmaximum_acq_rel_v4f16_global_cta(ptr addrspace(1) %addr, <4 x half> %val) {
; SM90-LABEL: fmaximum_acq_rel_v4f16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [fmaximum_acq_rel_v4f16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fmaximum_acq_rel_v4f16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB310_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.NaN.f16x2 %r3, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r3;
; SM90-NEXT:    max.NaN.f16x2 %r4, %r6, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r4;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB310_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmaximum ptr  addrspace(1) %addr, <4 x half> %val syncscope("block") acq_rel
        ret <4 x half> %retval
}

define <8 x half> @fmaximum_acq_rel_v8f16_global_cta(ptr addrspace(1) %addr, <8 x half> %val) {
; SM90-LABEL: fmaximum_acq_rel_v8f16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fmaximum_acq_rel_v8f16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fmaximum_acq_rel_v8f16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB311_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.NaN.f16x2 %r5, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd5, %r5;
; SM90-NEXT:    max.NaN.f16x2 %r6, %r10, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r6;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    max.NaN.f16x2 %r7, %r11, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r7;
; SM90-NEXT:    max.NaN.f16x2 %r8, %r12, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r8;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r10;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r12;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd22;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB311_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmaximum ptr  addrspace(1) %addr, <8 x half> %val syncscope("block") acq_rel
        ret <8 x half> %retval
}

define <1 x bfloat> @fadd_acq_rel_v1bf16_global_cta(ptr addrspace(1) %addr, <1 x bfloat> %val) {
; SM90-LABEL: fadd_acq_rel_v1bf16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b16 %rs<3>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [fadd_acq_rel_v1bf16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b16 %rs1, [fadd_acq_rel_v1bf16_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.bf16 %rs2, [%rd1], %rs1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %rs2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fadd ptr  addrspace(1) %addr, <1 x bfloat> %val syncscope("block") acq_rel
        ret <1 x bfloat> %retval
}

define <2 x bfloat> @fadd_acq_rel_v2bf16_global_cta(ptr addrspace(1) %addr, <2 x bfloat> %val) {
; SM90-LABEL: fadd_acq_rel_v2bf16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b16 %rs<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [fadd_acq_rel_v2bf16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b16 {%rs1, %rs2}, [fadd_acq_rel_v2bf16_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.bf16 %rs3, [%rd1], %rs1;
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.bf16 %rs4, [%rd1+2], %rs2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b16 [func_retval0], {%rs3, %rs4};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fadd ptr  addrspace(1) %addr, <2 x bfloat> %val syncscope("block") acq_rel
        ret <2 x bfloat> %retval
}

define <4 x bfloat> @fadd_acq_rel_v4bf16_global_cta(ptr addrspace(1) %addr, <4 x bfloat> %val) {
; SM90-LABEL: fadd_acq_rel_v4bf16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b16 %rs<9>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [fadd_acq_rel_v4bf16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b16 {%rs1, %rs2, %rs3, %rs4}, [fadd_acq_rel_v4bf16_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.bf16 %rs5, [%rd1], %rs1;
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.bf16 %rs6, [%rd1+2], %rs2;
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.bf16 %rs7, [%rd1+4], %rs3;
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.bf16 %rs8, [%rd1+6], %rs4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b16 [func_retval0], {%rs5, %rs6, %rs7, %rs8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fadd ptr  addrspace(1) %addr, <4 x bfloat> %val syncscope("block") acq_rel
        ret <4 x bfloat> %retval
}

define <8 x bfloat> @fadd_acq_rel_v8bf16_global_cta(ptr addrspace(1) %addr, <8 x bfloat> %val) {
; SM90-LABEL: fadd_acq_rel_v8bf16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b16 %rs<17>;
; SM90-NEXT:    .reg .b32 %r<9>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [fadd_acq_rel_v8bf16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fadd_acq_rel_v8bf16_global_cta_param_1];
; SM90-NEXT:    mov.b32 {%rs1, %rs2}, %r4;
; SM90-NEXT:    mov.b32 {%rs3, %rs4}, %r3;
; SM90-NEXT:    mov.b32 {%rs5, %rs6}, %r2;
; SM90-NEXT:    mov.b32 {%rs7, %rs8}, %r1;
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.bf16 %rs9, [%rd1], %rs7;
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.bf16 %rs10, [%rd1+2], %rs8;
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.bf16 %rs11, [%rd1+4], %rs5;
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.bf16 %rs12, [%rd1+6], %rs6;
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.bf16 %rs13, [%rd1+8], %rs3;
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.bf16 %rs14, [%rd1+10], %rs4;
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.bf16 %rs15, [%rd1+12], %rs1;
; SM90-NEXT:    atom.relaxed.cta.global.add.noftz.bf16 %rs16, [%rd1+14], %rs2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    mov.b32 %r5, {%rs9, %rs10};
; SM90-NEXT:    mov.b32 %r6, {%rs11, %rs12};
; SM90-NEXT:    mov.b32 %r7, {%rs13, %rs14};
; SM90-NEXT:    mov.b32 %r8, {%rs15, %rs16};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fadd ptr  addrspace(1) %addr, <8 x bfloat> %val syncscope("block") acq_rel
        ret <8 x bfloat> %retval
}

define <1 x bfloat> @fsub_acq_rel_v1bf16_global_cta(ptr addrspace(1) %addr, <1 x bfloat> %val) {
; SM90-LABEL: fsub_acq_rel_v1bf16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<4>;
; SM90-NEXT:    .reg .b32 %r<15>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [fsub_acq_rel_v1bf16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b16 %rs1, [fsub_acq_rel_v1bf16_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r4, %rd2;
; SM90-NEXT:    and.b32 %r5, %r4, 3;
; SM90-NEXT:    shl.b32 %r1, %r5, 3;
; SM90-NEXT:    mov.b32 %r6, 65535;
; SM90-NEXT:    shl.b32 %r7, %r6, %r1;
; SM90-NEXT:    not.b32 %r2, %r7;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r14, [%rd1];
; SM90-NEXT:  $L__BB316_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r8, %r14, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r8;
; SM90-NEXT:    sub.rn.bf16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r9, %rs3;
; SM90-NEXT:    shl.b32 %r10, %r9, %r1;
; SM90-NEXT:    and.b32 %r11, %r14, %r2;
; SM90-NEXT:    or.b32 %r12, %r11, %r10;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r14, %r12;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r14;
; SM90-NEXT:    mov.b32 %r14, %r3;
; SM90-NEXT:    @%p1 bra $L__BB316_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r13, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r13;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fsub ptr  addrspace(1) %addr, <1 x bfloat> %val syncscope("block") acq_rel
        ret <1 x bfloat> %retval
}

define <2 x bfloat> @fsub_acq_rel_v2bf16_global_cta(ptr addrspace(1) %addr, <2 x bfloat> %val) {
; SM90-LABEL: fsub_acq_rel_v2bf16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [fsub_acq_rel_v2bf16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fsub_acq_rel_v2bf16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:  $L__BB317_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    sub.rn.bf16x2 %r3, %r4, %r2;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r4;
; SM90-NEXT:    mov.b32 %r4, %r1;
; SM90-NEXT:    @%p1 bra $L__BB317_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fsub ptr  addrspace(1) %addr, <2 x bfloat> %val syncscope("block") acq_rel
        ret <2 x bfloat> %retval
}

define <4 x bfloat> @fsub_acq_rel_v4bf16_global_cta(ptr addrspace(1) %addr, <4 x bfloat> %val) {
; SM90-LABEL: fsub_acq_rel_v4bf16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [fsub_acq_rel_v4bf16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fsub_acq_rel_v4bf16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB318_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    sub.rn.bf16x2 %r3, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r3;
; SM90-NEXT:    sub.rn.bf16x2 %r4, %r6, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r4;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB318_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fsub ptr  addrspace(1) %addr, <4 x bfloat> %val syncscope("block") acq_rel
        ret <4 x bfloat> %retval
}

define <8 x bfloat> @fsub_acq_rel_v8bf16_global_cta(ptr addrspace(1) %addr, <8 x bfloat> %val) {
; SM90-LABEL: fsub_acq_rel_v8bf16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fsub_acq_rel_v8bf16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fsub_acq_rel_v8bf16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB319_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    sub.rn.bf16x2 %r5, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd5, %r5;
; SM90-NEXT:    sub.rn.bf16x2 %r6, %r10, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r6;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    sub.rn.bf16x2 %r7, %r11, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r7;
; SM90-NEXT:    sub.rn.bf16x2 %r8, %r12, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r8;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r10;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r12;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd22;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB319_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fsub ptr  addrspace(1) %addr, <8 x bfloat> %val syncscope("block") acq_rel
        ret <8 x bfloat> %retval
}

define <1 x bfloat> @fmin_acq_rel_v1bf16_global_cta(ptr addrspace(1) %addr, <1 x bfloat> %val) {
; SM90-LABEL: fmin_acq_rel_v1bf16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<4>;
; SM90-NEXT:    .reg .b32 %r<15>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [fmin_acq_rel_v1bf16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b16 %rs1, [fmin_acq_rel_v1bf16_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r4, %rd2;
; SM90-NEXT:    and.b32 %r5, %r4, 3;
; SM90-NEXT:    shl.b32 %r1, %r5, 3;
; SM90-NEXT:    mov.b32 %r6, 65535;
; SM90-NEXT:    shl.b32 %r7, %r6, %r1;
; SM90-NEXT:    not.b32 %r2, %r7;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r14, [%rd1];
; SM90-NEXT:  $L__BB320_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r8, %r14, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r8;
; SM90-NEXT:    min.bf16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r9, %rs3;
; SM90-NEXT:    shl.b32 %r10, %r9, %r1;
; SM90-NEXT:    and.b32 %r11, %r14, %r2;
; SM90-NEXT:    or.b32 %r12, %r11, %r10;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r14, %r12;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r14;
; SM90-NEXT:    mov.b32 %r14, %r3;
; SM90-NEXT:    @%p1 bra $L__BB320_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r13, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r13;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmin ptr  addrspace(1) %addr, <1 x bfloat> %val syncscope("block") acq_rel
        ret <1 x bfloat> %retval
}

define <2 x bfloat> @fmin_acq_rel_v2bf16_global_cta(ptr addrspace(1) %addr, <2 x bfloat> %val) {
; SM90-LABEL: fmin_acq_rel_v2bf16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [fmin_acq_rel_v2bf16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fmin_acq_rel_v2bf16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:  $L__BB321_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.bf16x2 %r3, %r4, %r2;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r4;
; SM90-NEXT:    mov.b32 %r4, %r1;
; SM90-NEXT:    @%p1 bra $L__BB321_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmin ptr  addrspace(1) %addr, <2 x bfloat> %val syncscope("block") acq_rel
        ret <2 x bfloat> %retval
}

define <4 x bfloat> @fmin_acq_rel_v4bf16_global_cta(ptr addrspace(1) %addr, <4 x bfloat> %val) {
; SM90-LABEL: fmin_acq_rel_v4bf16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [fmin_acq_rel_v4bf16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fmin_acq_rel_v4bf16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB322_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.bf16x2 %r3, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r3;
; SM90-NEXT:    min.bf16x2 %r4, %r6, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r4;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB322_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmin ptr  addrspace(1) %addr, <4 x bfloat> %val syncscope("block") acq_rel
        ret <4 x bfloat> %retval
}

define <8 x bfloat> @fmin_acq_rel_v8bf16_global_cta(ptr addrspace(1) %addr, <8 x bfloat> %val) {
; SM90-LABEL: fmin_acq_rel_v8bf16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fmin_acq_rel_v8bf16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fmin_acq_rel_v8bf16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB323_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.bf16x2 %r5, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd5, %r5;
; SM90-NEXT:    min.bf16x2 %r6, %r10, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r6;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    min.bf16x2 %r7, %r11, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r7;
; SM90-NEXT:    min.bf16x2 %r8, %r12, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r8;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r10;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r12;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd22;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB323_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmin ptr  addrspace(1) %addr, <8 x bfloat> %val syncscope("block") acq_rel
        ret <8 x bfloat> %retval
}

define <1 x bfloat> @fmax_acq_rel_v1bf16_global_cta(ptr addrspace(1) %addr, <1 x bfloat> %val) {
; SM90-LABEL: fmax_acq_rel_v1bf16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<4>;
; SM90-NEXT:    .reg .b32 %r<15>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [fmax_acq_rel_v1bf16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b16 %rs1, [fmax_acq_rel_v1bf16_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r4, %rd2;
; SM90-NEXT:    and.b32 %r5, %r4, 3;
; SM90-NEXT:    shl.b32 %r1, %r5, 3;
; SM90-NEXT:    mov.b32 %r6, 65535;
; SM90-NEXT:    shl.b32 %r7, %r6, %r1;
; SM90-NEXT:    not.b32 %r2, %r7;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r14, [%rd1];
; SM90-NEXT:  $L__BB324_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r8, %r14, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r8;
; SM90-NEXT:    max.bf16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r9, %rs3;
; SM90-NEXT:    shl.b32 %r10, %r9, %r1;
; SM90-NEXT:    and.b32 %r11, %r14, %r2;
; SM90-NEXT:    or.b32 %r12, %r11, %r10;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r14, %r12;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r14;
; SM90-NEXT:    mov.b32 %r14, %r3;
; SM90-NEXT:    @%p1 bra $L__BB324_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r13, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r13;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmax ptr  addrspace(1) %addr, <1 x bfloat> %val syncscope("block") acq_rel
        ret <1 x bfloat> %retval
}

define <2 x bfloat> @fmax_acq_rel_v2bf16_global_cta(ptr addrspace(1) %addr, <2 x bfloat> %val) {
; SM90-LABEL: fmax_acq_rel_v2bf16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [fmax_acq_rel_v2bf16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fmax_acq_rel_v2bf16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:  $L__BB325_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.bf16x2 %r3, %r4, %r2;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r4;
; SM90-NEXT:    mov.b32 %r4, %r1;
; SM90-NEXT:    @%p1 bra $L__BB325_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmax ptr  addrspace(1) %addr, <2 x bfloat> %val syncscope("block") acq_rel
        ret <2 x bfloat> %retval
}

define <4 x bfloat> @fmax_acq_rel_v4bf16_global_cta(ptr addrspace(1) %addr, <4 x bfloat> %val) {
; SM90-LABEL: fmax_acq_rel_v4bf16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [fmax_acq_rel_v4bf16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fmax_acq_rel_v4bf16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB326_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.bf16x2 %r3, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r3;
; SM90-NEXT:    max.bf16x2 %r4, %r6, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r4;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB326_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmax ptr  addrspace(1) %addr, <4 x bfloat> %val syncscope("block") acq_rel
        ret <4 x bfloat> %retval
}

define <8 x bfloat> @fmax_acq_rel_v8bf16_global_cta(ptr addrspace(1) %addr, <8 x bfloat> %val) {
; SM90-LABEL: fmax_acq_rel_v8bf16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fmax_acq_rel_v8bf16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fmax_acq_rel_v8bf16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB327_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.bf16x2 %r5, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd5, %r5;
; SM90-NEXT:    max.bf16x2 %r6, %r10, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r6;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    max.bf16x2 %r7, %r11, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r7;
; SM90-NEXT:    max.bf16x2 %r8, %r12, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r8;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r10;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r12;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd22;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB327_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmax ptr  addrspace(1) %addr, <8 x bfloat> %val syncscope("block") acq_rel
        ret <8 x bfloat> %retval
}

define <1 x bfloat> @fminimum_acq_rel_v1bf16_global_cta(ptr addrspace(1) %addr, <1 x bfloat> %val) {
; SM90-LABEL: fminimum_acq_rel_v1bf16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<4>;
; SM90-NEXT:    .reg .b32 %r<15>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [fminimum_acq_rel_v1bf16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b16 %rs1, [fminimum_acq_rel_v1bf16_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r4, %rd2;
; SM90-NEXT:    and.b32 %r5, %r4, 3;
; SM90-NEXT:    shl.b32 %r1, %r5, 3;
; SM90-NEXT:    mov.b32 %r6, 65535;
; SM90-NEXT:    shl.b32 %r7, %r6, %r1;
; SM90-NEXT:    not.b32 %r2, %r7;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r14, [%rd1];
; SM90-NEXT:  $L__BB328_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r8, %r14, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r8;
; SM90-NEXT:    min.NaN.bf16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r9, %rs3;
; SM90-NEXT:    shl.b32 %r10, %r9, %r1;
; SM90-NEXT:    and.b32 %r11, %r14, %r2;
; SM90-NEXT:    or.b32 %r12, %r11, %r10;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r14, %r12;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r14;
; SM90-NEXT:    mov.b32 %r14, %r3;
; SM90-NEXT:    @%p1 bra $L__BB328_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r13, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r13;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fminimum ptr  addrspace(1) %addr, <1 x bfloat> %val syncscope("block") acq_rel
        ret <1 x bfloat> %retval
}

define <2 x bfloat> @fminimum_acq_rel_v2bf16_global_cta(ptr addrspace(1) %addr, <2 x bfloat> %val) {
; SM90-LABEL: fminimum_acq_rel_v2bf16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [fminimum_acq_rel_v2bf16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fminimum_acq_rel_v2bf16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:  $L__BB329_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.NaN.bf16x2 %r3, %r4, %r2;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r4;
; SM90-NEXT:    mov.b32 %r4, %r1;
; SM90-NEXT:    @%p1 bra $L__BB329_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fminimum ptr  addrspace(1) %addr, <2 x bfloat> %val syncscope("block") acq_rel
        ret <2 x bfloat> %retval
}

define <4 x bfloat> @fminimum_acq_rel_v4bf16_global_cta(ptr addrspace(1) %addr, <4 x bfloat> %val) {
; SM90-LABEL: fminimum_acq_rel_v4bf16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [fminimum_acq_rel_v4bf16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fminimum_acq_rel_v4bf16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB330_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.NaN.bf16x2 %r3, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r3;
; SM90-NEXT:    min.NaN.bf16x2 %r4, %r6, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r4;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB330_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fminimum ptr  addrspace(1) %addr, <4 x bfloat> %val syncscope("block") acq_rel
        ret <4 x bfloat> %retval
}

define <8 x bfloat> @fminimum_acq_rel_v8bf16_global_cta(ptr addrspace(1) %addr, <8 x bfloat> %val) {
; SM90-LABEL: fminimum_acq_rel_v8bf16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fminimum_acq_rel_v8bf16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fminimum_acq_rel_v8bf16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB331_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    min.NaN.bf16x2 %r5, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd5, %r5;
; SM90-NEXT:    min.NaN.bf16x2 %r6, %r10, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r6;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    min.NaN.bf16x2 %r7, %r11, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r7;
; SM90-NEXT:    min.NaN.bf16x2 %r8, %r12, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r8;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r10;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r12;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd22;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB331_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fminimum ptr  addrspace(1) %addr, <8 x bfloat> %val syncscope("block") acq_rel
        ret <8 x bfloat> %retval
}

define <1 x bfloat> @fmaximum_acq_rel_v1bf16_global_cta(ptr addrspace(1) %addr, <1 x bfloat> %val) {
; SM90-LABEL: fmaximum_acq_rel_v1bf16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<4>;
; SM90-NEXT:    .reg .b32 %r<15>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [fmaximum_acq_rel_v1bf16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b16 %rs1, [fmaximum_acq_rel_v1bf16_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r4, %rd2;
; SM90-NEXT:    and.b32 %r5, %r4, 3;
; SM90-NEXT:    shl.b32 %r1, %r5, 3;
; SM90-NEXT:    mov.b32 %r6, 65535;
; SM90-NEXT:    shl.b32 %r7, %r6, %r1;
; SM90-NEXT:    not.b32 %r2, %r7;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r14, [%rd1];
; SM90-NEXT:  $L__BB332_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r8, %r14, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r8;
; SM90-NEXT:    max.NaN.bf16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r9, %rs3;
; SM90-NEXT:    shl.b32 %r10, %r9, %r1;
; SM90-NEXT:    and.b32 %r11, %r14, %r2;
; SM90-NEXT:    or.b32 %r12, %r11, %r10;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r14, %r12;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r14;
; SM90-NEXT:    mov.b32 %r14, %r3;
; SM90-NEXT:    @%p1 bra $L__BB332_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r13, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r13;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmaximum ptr  addrspace(1) %addr, <1 x bfloat> %val syncscope("block") acq_rel
        ret <1 x bfloat> %retval
}

define <2 x bfloat> @fmaximum_acq_rel_v2bf16_global_cta(ptr addrspace(1) %addr, <2 x bfloat> %val) {
; SM90-LABEL: fmaximum_acq_rel_v2bf16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [fmaximum_acq_rel_v2bf16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fmaximum_acq_rel_v2bf16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r4, [%rd1];
; SM90-NEXT:  $L__BB333_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.NaN.bf16x2 %r3, %r4, %r2;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r4, %r3;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r4;
; SM90-NEXT:    mov.b32 %r4, %r1;
; SM90-NEXT:    @%p1 bra $L__BB333_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmaximum ptr  addrspace(1) %addr, <2 x bfloat> %val syncscope("block") acq_rel
        ret <2 x bfloat> %retval
}

define <4 x bfloat> @fmaximum_acq_rel_v4bf16_global_cta(ptr addrspace(1) %addr, <4 x bfloat> %val) {
; SM90-LABEL: fmaximum_acq_rel_v4bf16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [fmaximum_acq_rel_v4bf16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fmaximum_acq_rel_v4bf16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB334_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.NaN.bf16x2 %r3, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r3;
; SM90-NEXT:    max.NaN.bf16x2 %r4, %r6, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r4;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB334_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmaximum ptr  addrspace(1) %addr, <4 x bfloat> %val syncscope("block") acq_rel
        ret <4 x bfloat> %retval
}

define <8 x bfloat> @fmaximum_acq_rel_v8bf16_global_cta(ptr addrspace(1) %addr, <8 x bfloat> %val) {
; SM90-LABEL: fmaximum_acq_rel_v8bf16_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<26>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [fmaximum_acq_rel_v8bf16_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [fmaximum_acq_rel_v8bf16_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB335_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    max.NaN.bf16x2 %r5, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd5, %r5;
; SM90-NEXT:    max.NaN.bf16x2 %r6, %r10, %r2;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r6;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    max.NaN.bf16x2 %r7, %r11, %r3;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r7;
; SM90-NEXT:    max.NaN.bf16x2 %r8, %r12, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r8;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r10;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    cvt.u64.u32 %rd17, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r12;
; SM90-NEXT:    shl.b64 %rd19, %rd18, 32;
; SM90-NEXT:    or.b64 %rd20, %rd17, %rd19;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd16, %rd20};
; SM90-NEXT:    mov.b128 swap, {%rd8, %rd12};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd21, %rd22}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd23, %rd22, %rd20;
; SM90-NEXT:    xor.b64 %rd24, %rd21, %rd16;
; SM90-NEXT:    or.b64 %rd25, %rd24, %rd23;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd22;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd22;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd21;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd21;
; SM90-NEXT:    setp.ne.b64 %p1, %rd25, 0;
; SM90-NEXT:    @%p1 bra $L__BB335_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise fmaximum ptr  addrspace(1) %addr, <8 x bfloat> %val syncscope("block") acq_rel
        ret <8 x bfloat> %retval
}

define <1 x i8> @add_monotonic_v1i8_global_cta(ptr addrspace(1) %addr, <1 x i8> %val) {
; SM90-LABEL: add_monotonic_v1i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<16>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [add_monotonic_v1i8_global_cta_param_0];
; SM90-NEXT:    ld.param.b8 %r6, [add_monotonic_v1i8_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd2;
; SM90-NEXT:    and.b32 %r8, %r7, 3;
; SM90-NEXT:    shl.b32 %r1, %r8, 3;
; SM90-NEXT:    mov.b32 %r9, 255;
; SM90-NEXT:    shl.b32 %r2, %r9, %r1;
; SM90-NEXT:    not.b32 %r3, %r2;
; SM90-NEXT:    shl.b32 %r4, %r6, %r1;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r15, [%rd1];
; SM90-NEXT:  $L__BB336_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    add.s32 %r10, %r15, %r4;
; SM90-NEXT:    and.b32 %r11, %r10, %r2;
; SM90-NEXT:    and.b32 %r12, %r15, %r3;
; SM90-NEXT:    or.b32 %r13, %r12, %r11;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r5, [%rd1], %r15, %r13;
; SM90-NEXT:    setp.ne.b32 %p1, %r5, %r15;
; SM90-NEXT:    mov.b32 %r15, %r5;
; SM90-NEXT:    @%p1 bra $L__BB336_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r14, %r5, %r1;
; SM90-NEXT:    st.param.b8 [func_retval0], %r14;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <1 x i8> %val syncscope("block") monotonic
        ret <1 x i8> %retval
}

define <2 x i8> @add_monotonic_v2i8_global_cta(ptr addrspace(1) %addr, <2 x i8> %val) {
; SM90-LABEL: add_monotonic_v2i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<10>;
; SM90-NEXT:    .reg .b32 %r<18>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b8 {%rs1, %rs2}, [add_monotonic_v2i8_global_cta_param_1];
; SM90-NEXT:    mov.b32 %r4, {%rs1, %rs2};
; SM90-NEXT:    ld.param.b64 %rd2, [add_monotonic_v2i8_global_cta_param_0];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:    and.b32 %r6, %r5, 3;
; SM90-NEXT:    shl.b32 %r1, %r6, 3;
; SM90-NEXT:    mov.b32 %r7, 65535;
; SM90-NEXT:    shl.b32 %r8, %r7, %r1;
; SM90-NEXT:    not.b32 %r2, %r8;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r17, [%rd1];
; SM90-NEXT:  $L__BB337_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r9, %r17, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs3, %r9;
; SM90-NEXT:    shr.u16 %rs4, %rs3, 8;
; SM90-NEXT:    mov.b32 %r10, {%rs3, %rs4};
; SM90-NEXT:    add.s16x2 %r11, %r10, %r4;
; SM90-NEXT:    mov.b32 {%rs5, %rs6}, %r11;
; SM90-NEXT:    shl.b16 %rs7, %rs6, 8;
; SM90-NEXT:    and.b16 %rs8, %rs5, 255;
; SM90-NEXT:    or.b16 %rs9, %rs8, %rs7;
; SM90-NEXT:    cvt.u32.u16 %r12, %rs9;
; SM90-NEXT:    shl.b32 %r13, %r12, %r1;
; SM90-NEXT:    and.b32 %r14, %r17, %r2;
; SM90-NEXT:    or.b32 %r15, %r14, %r13;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r17, %r15;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r17;
; SM90-NEXT:    mov.b32 %r17, %r3;
; SM90-NEXT:    @%p1 bra $L__BB337_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r16, %r3, %r1;
; SM90-NEXT:    st.param.b16 [func_retval0], %r16;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <2 x i8> %val syncscope("block") monotonic
        ret <2 x i8> %retval
}

define <4 x i8> @add_monotonic_v4i8_global_cta(ptr addrspace(1) %addr, <4 x i8> %val) {
; SM90-LABEL: add_monotonic_v4i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<13>;
; SM90-NEXT:    .reg .b32 %r<19>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [add_monotonic_v4i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [add_monotonic_v4i8_global_cta_param_0];
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r18, [%rd1];
; SM90-NEXT:    prmt.b32 %r3, %r2, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs1, %r3;
; SM90-NEXT:    prmt.b32 %r6, %r2, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs4, %r6;
; SM90-NEXT:    prmt.b32 %r10, %r2, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs7, %r10;
; SM90-NEXT:    prmt.b32 %r13, %r2, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs10, %r13;
; SM90-NEXT:  $L__BB338_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    prmt.b32 %r4, %r18, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r4;
; SM90-NEXT:    add.s16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r5, %rs3;
; SM90-NEXT:    prmt.b32 %r7, %r18, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs5, %r7;
; SM90-NEXT:    add.s16 %rs6, %rs5, %rs4;
; SM90-NEXT:    cvt.u32.u16 %r8, %rs6;
; SM90-NEXT:    prmt.b32 %r9, %r8, %r5, 0x3340U;
; SM90-NEXT:    prmt.b32 %r11, %r18, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs8, %r11;
; SM90-NEXT:    add.s16 %rs9, %rs8, %rs7;
; SM90-NEXT:    cvt.u32.u16 %r12, %rs9;
; SM90-NEXT:    prmt.b32 %r14, %r18, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs11, %r14;
; SM90-NEXT:    add.s16 %rs12, %rs11, %rs10;
; SM90-NEXT:    cvt.u32.u16 %r15, %rs12;
; SM90-NEXT:    prmt.b32 %r16, %r15, %r12, 0x3340U;
; SM90-NEXT:    prmt.b32 %r17, %r16, %r9, 0x5410U;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r18, %r17;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r18;
; SM90-NEXT:    mov.b32 %r18, %r1;
; SM90-NEXT:    @%p1 bra $L__BB338_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <4 x i8> %val syncscope("block") monotonic
        ret <4 x i8> %retval
}

define <8 x i8> @add_monotonic_v8i8_global_cta(ptr addrspace(1) %addr, <8 x i8> %val) {
; SM90-LABEL: add_monotonic_v8i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<25>;
; SM90-NEXT:    .reg .b32 %r<35>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [add_monotonic_v8i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [add_monotonic_v8i8_global_cta_param_0];
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r34}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r33, %rd2;
; SM90-NEXT:    prmt.b32 %r3, %r1, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs1, %r3;
; SM90-NEXT:    prmt.b32 %r6, %r1, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs4, %r6;
; SM90-NEXT:    prmt.b32 %r10, %r1, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs7, %r10;
; SM90-NEXT:    prmt.b32 %r13, %r1, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs10, %r13;
; SM90-NEXT:    prmt.b32 %r18, %r2, 0, 0x7773U;
; SM90-NEXT:    prmt.b32 %r21, %r2, 0, 0x7772U;
; SM90-NEXT:  $L__BB339_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    prmt.b32 %r4, %r33, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r4;
; SM90-NEXT:    add.s16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r5, %rs3;
; SM90-NEXT:    prmt.b32 %r7, %r33, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs5, %r7;
; SM90-NEXT:    add.s16 %rs6, %rs5, %rs4;
; SM90-NEXT:    cvt.u32.u16 %r8, %rs6;
; SM90-NEXT:    prmt.b32 %r9, %r8, %r5, 0x3340U;
; SM90-NEXT:    prmt.b32 %r11, %r33, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs8, %r11;
; SM90-NEXT:    add.s16 %rs9, %rs8, %rs7;
; SM90-NEXT:    cvt.u32.u16 %r12, %rs9;
; SM90-NEXT:    prmt.b32 %r14, %r33, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs11, %r14;
; SM90-NEXT:    add.s16 %rs12, %rs11, %rs10;
; SM90-NEXT:    cvt.u32.u16 %r15, %rs12;
; SM90-NEXT:    prmt.b32 %r16, %r15, %r12, 0x3340U;
; SM90-NEXT:    prmt.b32 %r17, %r16, %r9, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r17;
; SM90-NEXT:    cvt.u16.u32 %rs13, %r18;
; SM90-NEXT:    prmt.b32 %r19, %r34, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs14, %r19;
; SM90-NEXT:    add.s16 %rs15, %rs14, %rs13;
; SM90-NEXT:    cvt.u32.u16 %r20, %rs15;
; SM90-NEXT:    cvt.u16.u32 %rs16, %r21;
; SM90-NEXT:    prmt.b32 %r22, %r34, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs17, %r22;
; SM90-NEXT:    add.s16 %rs18, %rs17, %rs16;
; SM90-NEXT:    cvt.u32.u16 %r23, %rs18;
; SM90-NEXT:    prmt.b32 %r24, %r23, %r20, 0x3340U;
; SM90-NEXT:    prmt.b32 %r25, %r2, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs19, %r25;
; SM90-NEXT:    prmt.b32 %r26, %r34, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs20, %r26;
; SM90-NEXT:    add.s16 %rs21, %rs20, %rs19;
; SM90-NEXT:    cvt.u32.u16 %r27, %rs21;
; SM90-NEXT:    prmt.b32 %r28, %r2, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs22, %r28;
; SM90-NEXT:    prmt.b32 %r29, %r34, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs23, %r29;
; SM90-NEXT:    add.s16 %rs24, %rs23, %rs22;
; SM90-NEXT:    cvt.u32.u16 %r30, %rs24;
; SM90-NEXT:    prmt.b32 %r31, %r30, %r27, 0x3340U;
; SM90-NEXT:    prmt.b32 %r32, %r31, %r24, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r32;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r33;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r34;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r34}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r33, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB339_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r33, %r34};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <8 x i8> %val syncscope("block") monotonic
        ret <8 x i8> %retval
}

define <1 x i8> @add_acquire_v1i8_global_cta(ptr addrspace(1) %addr, <1 x i8> %val) {
; SM90-LABEL: add_acquire_v1i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<16>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [add_acquire_v1i8_global_cta_param_0];
; SM90-NEXT:    ld.param.b8 %r6, [add_acquire_v1i8_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd2;
; SM90-NEXT:    and.b32 %r8, %r7, 3;
; SM90-NEXT:    shl.b32 %r1, %r8, 3;
; SM90-NEXT:    mov.b32 %r9, 255;
; SM90-NEXT:    shl.b32 %r2, %r9, %r1;
; SM90-NEXT:    not.b32 %r3, %r2;
; SM90-NEXT:    shl.b32 %r4, %r6, %r1;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r15, [%rd1];
; SM90-NEXT:  $L__BB340_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    add.s32 %r10, %r15, %r4;
; SM90-NEXT:    and.b32 %r11, %r10, %r2;
; SM90-NEXT:    and.b32 %r12, %r15, %r3;
; SM90-NEXT:    or.b32 %r13, %r12, %r11;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r5, [%rd1], %r15, %r13;
; SM90-NEXT:    setp.ne.b32 %p1, %r5, %r15;
; SM90-NEXT:    mov.b32 %r15, %r5;
; SM90-NEXT:    @%p1 bra $L__BB340_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r14, %r5, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b8 [func_retval0], %r14;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <1 x i8> %val syncscope("block") acquire
        ret <1 x i8> %retval
}

define <2 x i8> @add_acquire_v2i8_global_cta(ptr addrspace(1) %addr, <2 x i8> %val) {
; SM90-LABEL: add_acquire_v2i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<10>;
; SM90-NEXT:    .reg .b32 %r<18>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b8 {%rs1, %rs2}, [add_acquire_v2i8_global_cta_param_1];
; SM90-NEXT:    mov.b32 %r4, {%rs1, %rs2};
; SM90-NEXT:    ld.param.b64 %rd2, [add_acquire_v2i8_global_cta_param_0];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:    and.b32 %r6, %r5, 3;
; SM90-NEXT:    shl.b32 %r1, %r6, 3;
; SM90-NEXT:    mov.b32 %r7, 65535;
; SM90-NEXT:    shl.b32 %r8, %r7, %r1;
; SM90-NEXT:    not.b32 %r2, %r8;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r17, [%rd1];
; SM90-NEXT:  $L__BB341_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r9, %r17, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs3, %r9;
; SM90-NEXT:    shr.u16 %rs4, %rs3, 8;
; SM90-NEXT:    mov.b32 %r10, {%rs3, %rs4};
; SM90-NEXT:    add.s16x2 %r11, %r10, %r4;
; SM90-NEXT:    mov.b32 {%rs5, %rs6}, %r11;
; SM90-NEXT:    shl.b16 %rs7, %rs6, 8;
; SM90-NEXT:    and.b16 %rs8, %rs5, 255;
; SM90-NEXT:    or.b16 %rs9, %rs8, %rs7;
; SM90-NEXT:    cvt.u32.u16 %r12, %rs9;
; SM90-NEXT:    shl.b32 %r13, %r12, %r1;
; SM90-NEXT:    and.b32 %r14, %r17, %r2;
; SM90-NEXT:    or.b32 %r15, %r14, %r13;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r17, %r15;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r17;
; SM90-NEXT:    mov.b32 %r17, %r3;
; SM90-NEXT:    @%p1 bra $L__BB341_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r16, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r16;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <2 x i8> %val syncscope("block") acquire
        ret <2 x i8> %retval
}

define <4 x i8> @add_acquire_v4i8_global_cta(ptr addrspace(1) %addr, <4 x i8> %val) {
; SM90-LABEL: add_acquire_v4i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<13>;
; SM90-NEXT:    .reg .b32 %r<19>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [add_acquire_v4i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [add_acquire_v4i8_global_cta_param_0];
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r18, [%rd1];
; SM90-NEXT:    prmt.b32 %r3, %r2, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs1, %r3;
; SM90-NEXT:    prmt.b32 %r6, %r2, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs4, %r6;
; SM90-NEXT:    prmt.b32 %r10, %r2, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs7, %r10;
; SM90-NEXT:    prmt.b32 %r13, %r2, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs10, %r13;
; SM90-NEXT:  $L__BB342_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    prmt.b32 %r4, %r18, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r4;
; SM90-NEXT:    add.s16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r5, %rs3;
; SM90-NEXT:    prmt.b32 %r7, %r18, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs5, %r7;
; SM90-NEXT:    add.s16 %rs6, %rs5, %rs4;
; SM90-NEXT:    cvt.u32.u16 %r8, %rs6;
; SM90-NEXT:    prmt.b32 %r9, %r8, %r5, 0x3340U;
; SM90-NEXT:    prmt.b32 %r11, %r18, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs8, %r11;
; SM90-NEXT:    add.s16 %rs9, %rs8, %rs7;
; SM90-NEXT:    cvt.u32.u16 %r12, %rs9;
; SM90-NEXT:    prmt.b32 %r14, %r18, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs11, %r14;
; SM90-NEXT:    add.s16 %rs12, %rs11, %rs10;
; SM90-NEXT:    cvt.u32.u16 %r15, %rs12;
; SM90-NEXT:    prmt.b32 %r16, %r15, %r12, 0x3340U;
; SM90-NEXT:    prmt.b32 %r17, %r16, %r9, 0x5410U;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r18, %r17;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r18;
; SM90-NEXT:    mov.b32 %r18, %r1;
; SM90-NEXT:    @%p1 bra $L__BB342_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <4 x i8> %val syncscope("block") acquire
        ret <4 x i8> %retval
}

define <8 x i8> @add_acquire_v8i8_global_cta(ptr addrspace(1) %addr, <8 x i8> %val) {
; SM90-LABEL: add_acquire_v8i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<25>;
; SM90-NEXT:    .reg .b32 %r<35>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [add_acquire_v8i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [add_acquire_v8i8_global_cta_param_0];
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r34}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r33, %rd2;
; SM90-NEXT:    prmt.b32 %r3, %r1, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs1, %r3;
; SM90-NEXT:    prmt.b32 %r6, %r1, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs4, %r6;
; SM90-NEXT:    prmt.b32 %r10, %r1, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs7, %r10;
; SM90-NEXT:    prmt.b32 %r13, %r1, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs10, %r13;
; SM90-NEXT:    prmt.b32 %r18, %r2, 0, 0x7773U;
; SM90-NEXT:    prmt.b32 %r21, %r2, 0, 0x7772U;
; SM90-NEXT:  $L__BB343_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    prmt.b32 %r4, %r33, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r4;
; SM90-NEXT:    add.s16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r5, %rs3;
; SM90-NEXT:    prmt.b32 %r7, %r33, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs5, %r7;
; SM90-NEXT:    add.s16 %rs6, %rs5, %rs4;
; SM90-NEXT:    cvt.u32.u16 %r8, %rs6;
; SM90-NEXT:    prmt.b32 %r9, %r8, %r5, 0x3340U;
; SM90-NEXT:    prmt.b32 %r11, %r33, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs8, %r11;
; SM90-NEXT:    add.s16 %rs9, %rs8, %rs7;
; SM90-NEXT:    cvt.u32.u16 %r12, %rs9;
; SM90-NEXT:    prmt.b32 %r14, %r33, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs11, %r14;
; SM90-NEXT:    add.s16 %rs12, %rs11, %rs10;
; SM90-NEXT:    cvt.u32.u16 %r15, %rs12;
; SM90-NEXT:    prmt.b32 %r16, %r15, %r12, 0x3340U;
; SM90-NEXT:    prmt.b32 %r17, %r16, %r9, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r17;
; SM90-NEXT:    cvt.u16.u32 %rs13, %r18;
; SM90-NEXT:    prmt.b32 %r19, %r34, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs14, %r19;
; SM90-NEXT:    add.s16 %rs15, %rs14, %rs13;
; SM90-NEXT:    cvt.u32.u16 %r20, %rs15;
; SM90-NEXT:    cvt.u16.u32 %rs16, %r21;
; SM90-NEXT:    prmt.b32 %r22, %r34, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs17, %r22;
; SM90-NEXT:    add.s16 %rs18, %rs17, %rs16;
; SM90-NEXT:    cvt.u32.u16 %r23, %rs18;
; SM90-NEXT:    prmt.b32 %r24, %r23, %r20, 0x3340U;
; SM90-NEXT:    prmt.b32 %r25, %r2, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs19, %r25;
; SM90-NEXT:    prmt.b32 %r26, %r34, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs20, %r26;
; SM90-NEXT:    add.s16 %rs21, %rs20, %rs19;
; SM90-NEXT:    cvt.u32.u16 %r27, %rs21;
; SM90-NEXT:    prmt.b32 %r28, %r2, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs22, %r28;
; SM90-NEXT:    prmt.b32 %r29, %r34, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs23, %r29;
; SM90-NEXT:    add.s16 %rs24, %rs23, %rs22;
; SM90-NEXT:    cvt.u32.u16 %r30, %rs24;
; SM90-NEXT:    prmt.b32 %r31, %r30, %r27, 0x3340U;
; SM90-NEXT:    prmt.b32 %r32, %r31, %r24, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r32;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r33;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r34;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r34}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r33, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB343_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r33, %r34};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <8 x i8> %val syncscope("block") acquire
        ret <8 x i8> %retval
}

define <1 x i8> @add_release_v1i8_global_cta(ptr addrspace(1) %addr, <1 x i8> %val) {
; SM90-LABEL: add_release_v1i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<16>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [add_release_v1i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b8 %r6, [add_release_v1i8_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd2;
; SM90-NEXT:    and.b32 %r8, %r7, 3;
; SM90-NEXT:    shl.b32 %r1, %r8, 3;
; SM90-NEXT:    mov.b32 %r9, 255;
; SM90-NEXT:    shl.b32 %r2, %r9, %r1;
; SM90-NEXT:    not.b32 %r3, %r2;
; SM90-NEXT:    shl.b32 %r4, %r6, %r1;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r15, [%rd1];
; SM90-NEXT:  $L__BB344_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    add.s32 %r10, %r15, %r4;
; SM90-NEXT:    and.b32 %r11, %r10, %r2;
; SM90-NEXT:    and.b32 %r12, %r15, %r3;
; SM90-NEXT:    or.b32 %r13, %r12, %r11;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r5, [%rd1], %r15, %r13;
; SM90-NEXT:    setp.ne.b32 %p1, %r5, %r15;
; SM90-NEXT:    mov.b32 %r15, %r5;
; SM90-NEXT:    @%p1 bra $L__BB344_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r14, %r5, %r1;
; SM90-NEXT:    st.param.b8 [func_retval0], %r14;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <1 x i8> %val syncscope("block") release
        ret <1 x i8> %retval
}

define <2 x i8> @add_release_v2i8_global_cta(ptr addrspace(1) %addr, <2 x i8> %val) {
; SM90-LABEL: add_release_v2i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<10>;
; SM90-NEXT:    .reg .b32 %r<18>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b8 {%rs1, %rs2}, [add_release_v2i8_global_cta_param_1];
; SM90-NEXT:    mov.b32 %r4, {%rs1, %rs2};
; SM90-NEXT:    ld.param.b64 %rd2, [add_release_v2i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:    and.b32 %r6, %r5, 3;
; SM90-NEXT:    shl.b32 %r1, %r6, 3;
; SM90-NEXT:    mov.b32 %r7, 65535;
; SM90-NEXT:    shl.b32 %r8, %r7, %r1;
; SM90-NEXT:    not.b32 %r2, %r8;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r17, [%rd1];
; SM90-NEXT:  $L__BB345_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r9, %r17, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs3, %r9;
; SM90-NEXT:    shr.u16 %rs4, %rs3, 8;
; SM90-NEXT:    mov.b32 %r10, {%rs3, %rs4};
; SM90-NEXT:    add.s16x2 %r11, %r10, %r4;
; SM90-NEXT:    mov.b32 {%rs5, %rs6}, %r11;
; SM90-NEXT:    shl.b16 %rs7, %rs6, 8;
; SM90-NEXT:    and.b16 %rs8, %rs5, 255;
; SM90-NEXT:    or.b16 %rs9, %rs8, %rs7;
; SM90-NEXT:    cvt.u32.u16 %r12, %rs9;
; SM90-NEXT:    shl.b32 %r13, %r12, %r1;
; SM90-NEXT:    and.b32 %r14, %r17, %r2;
; SM90-NEXT:    or.b32 %r15, %r14, %r13;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r17, %r15;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r17;
; SM90-NEXT:    mov.b32 %r17, %r3;
; SM90-NEXT:    @%p1 bra $L__BB345_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r16, %r3, %r1;
; SM90-NEXT:    st.param.b16 [func_retval0], %r16;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <2 x i8> %val syncscope("block") release
        ret <2 x i8> %retval
}

define <4 x i8> @add_release_v4i8_global_cta(ptr addrspace(1) %addr, <4 x i8> %val) {
; SM90-LABEL: add_release_v4i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<13>;
; SM90-NEXT:    .reg .b32 %r<19>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [add_release_v4i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [add_release_v4i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r18, [%rd1];
; SM90-NEXT:    prmt.b32 %r3, %r2, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs1, %r3;
; SM90-NEXT:    prmt.b32 %r6, %r2, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs4, %r6;
; SM90-NEXT:    prmt.b32 %r10, %r2, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs7, %r10;
; SM90-NEXT:    prmt.b32 %r13, %r2, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs10, %r13;
; SM90-NEXT:  $L__BB346_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    prmt.b32 %r4, %r18, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r4;
; SM90-NEXT:    add.s16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r5, %rs3;
; SM90-NEXT:    prmt.b32 %r7, %r18, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs5, %r7;
; SM90-NEXT:    add.s16 %rs6, %rs5, %rs4;
; SM90-NEXT:    cvt.u32.u16 %r8, %rs6;
; SM90-NEXT:    prmt.b32 %r9, %r8, %r5, 0x3340U;
; SM90-NEXT:    prmt.b32 %r11, %r18, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs8, %r11;
; SM90-NEXT:    add.s16 %rs9, %rs8, %rs7;
; SM90-NEXT:    cvt.u32.u16 %r12, %rs9;
; SM90-NEXT:    prmt.b32 %r14, %r18, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs11, %r14;
; SM90-NEXT:    add.s16 %rs12, %rs11, %rs10;
; SM90-NEXT:    cvt.u32.u16 %r15, %rs12;
; SM90-NEXT:    prmt.b32 %r16, %r15, %r12, 0x3340U;
; SM90-NEXT:    prmt.b32 %r17, %r16, %r9, 0x5410U;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r18, %r17;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r18;
; SM90-NEXT:    mov.b32 %r18, %r1;
; SM90-NEXT:    @%p1 bra $L__BB346_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <4 x i8> %val syncscope("block") release
        ret <4 x i8> %retval
}

define <8 x i8> @add_release_v8i8_global_cta(ptr addrspace(1) %addr, <8 x i8> %val) {
; SM90-LABEL: add_release_v8i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<25>;
; SM90-NEXT:    .reg .b32 %r<35>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [add_release_v8i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [add_release_v8i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r34}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r33, %rd2;
; SM90-NEXT:    prmt.b32 %r3, %r1, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs1, %r3;
; SM90-NEXT:    prmt.b32 %r6, %r1, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs4, %r6;
; SM90-NEXT:    prmt.b32 %r10, %r1, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs7, %r10;
; SM90-NEXT:    prmt.b32 %r13, %r1, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs10, %r13;
; SM90-NEXT:    prmt.b32 %r18, %r2, 0, 0x7773U;
; SM90-NEXT:    prmt.b32 %r21, %r2, 0, 0x7772U;
; SM90-NEXT:  $L__BB347_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    prmt.b32 %r4, %r33, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r4;
; SM90-NEXT:    add.s16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r5, %rs3;
; SM90-NEXT:    prmt.b32 %r7, %r33, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs5, %r7;
; SM90-NEXT:    add.s16 %rs6, %rs5, %rs4;
; SM90-NEXT:    cvt.u32.u16 %r8, %rs6;
; SM90-NEXT:    prmt.b32 %r9, %r8, %r5, 0x3340U;
; SM90-NEXT:    prmt.b32 %r11, %r33, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs8, %r11;
; SM90-NEXT:    add.s16 %rs9, %rs8, %rs7;
; SM90-NEXT:    cvt.u32.u16 %r12, %rs9;
; SM90-NEXT:    prmt.b32 %r14, %r33, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs11, %r14;
; SM90-NEXT:    add.s16 %rs12, %rs11, %rs10;
; SM90-NEXT:    cvt.u32.u16 %r15, %rs12;
; SM90-NEXT:    prmt.b32 %r16, %r15, %r12, 0x3340U;
; SM90-NEXT:    prmt.b32 %r17, %r16, %r9, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r17;
; SM90-NEXT:    cvt.u16.u32 %rs13, %r18;
; SM90-NEXT:    prmt.b32 %r19, %r34, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs14, %r19;
; SM90-NEXT:    add.s16 %rs15, %rs14, %rs13;
; SM90-NEXT:    cvt.u32.u16 %r20, %rs15;
; SM90-NEXT:    cvt.u16.u32 %rs16, %r21;
; SM90-NEXT:    prmt.b32 %r22, %r34, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs17, %r22;
; SM90-NEXT:    add.s16 %rs18, %rs17, %rs16;
; SM90-NEXT:    cvt.u32.u16 %r23, %rs18;
; SM90-NEXT:    prmt.b32 %r24, %r23, %r20, 0x3340U;
; SM90-NEXT:    prmt.b32 %r25, %r2, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs19, %r25;
; SM90-NEXT:    prmt.b32 %r26, %r34, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs20, %r26;
; SM90-NEXT:    add.s16 %rs21, %rs20, %rs19;
; SM90-NEXT:    cvt.u32.u16 %r27, %rs21;
; SM90-NEXT:    prmt.b32 %r28, %r2, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs22, %r28;
; SM90-NEXT:    prmt.b32 %r29, %r34, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs23, %r29;
; SM90-NEXT:    add.s16 %rs24, %rs23, %rs22;
; SM90-NEXT:    cvt.u32.u16 %r30, %rs24;
; SM90-NEXT:    prmt.b32 %r31, %r30, %r27, 0x3340U;
; SM90-NEXT:    prmt.b32 %r32, %r31, %r24, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r32;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r33;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r34;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r34}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r33, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB347_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r33, %r34};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <8 x i8> %val syncscope("block") release
        ret <8 x i8> %retval
}

define <1 x i8> @add_seq_cst_v1i8_global_cta(ptr addrspace(1) %addr, <1 x i8> %val) {
; SM90-LABEL: add_seq_cst_v1i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<16>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [add_seq_cst_v1i8_global_cta_param_0];
; SM90-NEXT:    fence.sc.cta;
; SM90-NEXT:    ld.param.b8 %r6, [add_seq_cst_v1i8_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd2;
; SM90-NEXT:    and.b32 %r8, %r7, 3;
; SM90-NEXT:    shl.b32 %r1, %r8, 3;
; SM90-NEXT:    mov.b32 %r9, 255;
; SM90-NEXT:    shl.b32 %r2, %r9, %r1;
; SM90-NEXT:    not.b32 %r3, %r2;
; SM90-NEXT:    shl.b32 %r4, %r6, %r1;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r15, [%rd1];
; SM90-NEXT:  $L__BB348_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    add.s32 %r10, %r15, %r4;
; SM90-NEXT:    and.b32 %r11, %r10, %r2;
; SM90-NEXT:    and.b32 %r12, %r15, %r3;
; SM90-NEXT:    or.b32 %r13, %r12, %r11;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r5, [%rd1], %r15, %r13;
; SM90-NEXT:    setp.ne.b32 %p1, %r5, %r15;
; SM90-NEXT:    mov.b32 %r15, %r5;
; SM90-NEXT:    @%p1 bra $L__BB348_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r14, %r5, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b8 [func_retval0], %r14;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <1 x i8> %val syncscope("block") seq_cst
        ret <1 x i8> %retval
}

define <2 x i8> @add_seq_cst_v2i8_global_cta(ptr addrspace(1) %addr, <2 x i8> %val) {
; SM90-LABEL: add_seq_cst_v2i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<10>;
; SM90-NEXT:    .reg .b32 %r<18>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b8 {%rs1, %rs2}, [add_seq_cst_v2i8_global_cta_param_1];
; SM90-NEXT:    mov.b32 %r4, {%rs1, %rs2};
; SM90-NEXT:    ld.param.b64 %rd2, [add_seq_cst_v2i8_global_cta_param_0];
; SM90-NEXT:    fence.sc.cta;
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:    and.b32 %r6, %r5, 3;
; SM90-NEXT:    shl.b32 %r1, %r6, 3;
; SM90-NEXT:    mov.b32 %r7, 65535;
; SM90-NEXT:    shl.b32 %r8, %r7, %r1;
; SM90-NEXT:    not.b32 %r2, %r8;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r17, [%rd1];
; SM90-NEXT:  $L__BB349_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r9, %r17, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs3, %r9;
; SM90-NEXT:    shr.u16 %rs4, %rs3, 8;
; SM90-NEXT:    mov.b32 %r10, {%rs3, %rs4};
; SM90-NEXT:    add.s16x2 %r11, %r10, %r4;
; SM90-NEXT:    mov.b32 {%rs5, %rs6}, %r11;
; SM90-NEXT:    shl.b16 %rs7, %rs6, 8;
; SM90-NEXT:    and.b16 %rs8, %rs5, 255;
; SM90-NEXT:    or.b16 %rs9, %rs8, %rs7;
; SM90-NEXT:    cvt.u32.u16 %r12, %rs9;
; SM90-NEXT:    shl.b32 %r13, %r12, %r1;
; SM90-NEXT:    and.b32 %r14, %r17, %r2;
; SM90-NEXT:    or.b32 %r15, %r14, %r13;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r17, %r15;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r17;
; SM90-NEXT:    mov.b32 %r17, %r3;
; SM90-NEXT:    @%p1 bra $L__BB349_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r16, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r16;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <2 x i8> %val syncscope("block") seq_cst
        ret <2 x i8> %retval
}

define <4 x i8> @add_seq_cst_v4i8_global_cta(ptr addrspace(1) %addr, <4 x i8> %val) {
; SM90-LABEL: add_seq_cst_v4i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<13>;
; SM90-NEXT:    .reg .b32 %r<19>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [add_seq_cst_v4i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [add_seq_cst_v4i8_global_cta_param_0];
; SM90-NEXT:    fence.sc.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r18, [%rd1];
; SM90-NEXT:    prmt.b32 %r3, %r2, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs1, %r3;
; SM90-NEXT:    prmt.b32 %r6, %r2, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs4, %r6;
; SM90-NEXT:    prmt.b32 %r10, %r2, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs7, %r10;
; SM90-NEXT:    prmt.b32 %r13, %r2, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs10, %r13;
; SM90-NEXT:  $L__BB350_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    prmt.b32 %r4, %r18, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r4;
; SM90-NEXT:    add.s16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r5, %rs3;
; SM90-NEXT:    prmt.b32 %r7, %r18, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs5, %r7;
; SM90-NEXT:    add.s16 %rs6, %rs5, %rs4;
; SM90-NEXT:    cvt.u32.u16 %r8, %rs6;
; SM90-NEXT:    prmt.b32 %r9, %r8, %r5, 0x3340U;
; SM90-NEXT:    prmt.b32 %r11, %r18, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs8, %r11;
; SM90-NEXT:    add.s16 %rs9, %rs8, %rs7;
; SM90-NEXT:    cvt.u32.u16 %r12, %rs9;
; SM90-NEXT:    prmt.b32 %r14, %r18, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs11, %r14;
; SM90-NEXT:    add.s16 %rs12, %rs11, %rs10;
; SM90-NEXT:    cvt.u32.u16 %r15, %rs12;
; SM90-NEXT:    prmt.b32 %r16, %r15, %r12, 0x3340U;
; SM90-NEXT:    prmt.b32 %r17, %r16, %r9, 0x5410U;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r18, %r17;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r18;
; SM90-NEXT:    mov.b32 %r18, %r1;
; SM90-NEXT:    @%p1 bra $L__BB350_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <4 x i8> %val syncscope("block") seq_cst
        ret <4 x i8> %retval
}

define <8 x i8> @add_seq_cst_v8i8_global_cta(ptr addrspace(1) %addr, <8 x i8> %val) {
; SM90-LABEL: add_seq_cst_v8i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<25>;
; SM90-NEXT:    .reg .b32 %r<35>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [add_seq_cst_v8i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [add_seq_cst_v8i8_global_cta_param_0];
; SM90-NEXT:    fence.sc.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r34}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r33, %rd2;
; SM90-NEXT:    prmt.b32 %r3, %r1, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs1, %r3;
; SM90-NEXT:    prmt.b32 %r6, %r1, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs4, %r6;
; SM90-NEXT:    prmt.b32 %r10, %r1, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs7, %r10;
; SM90-NEXT:    prmt.b32 %r13, %r1, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs10, %r13;
; SM90-NEXT:    prmt.b32 %r18, %r2, 0, 0x7773U;
; SM90-NEXT:    prmt.b32 %r21, %r2, 0, 0x7772U;
; SM90-NEXT:  $L__BB351_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    prmt.b32 %r4, %r33, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs2, %r4;
; SM90-NEXT:    add.s16 %rs3, %rs2, %rs1;
; SM90-NEXT:    cvt.u32.u16 %r5, %rs3;
; SM90-NEXT:    prmt.b32 %r7, %r33, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs5, %r7;
; SM90-NEXT:    add.s16 %rs6, %rs5, %rs4;
; SM90-NEXT:    cvt.u32.u16 %r8, %rs6;
; SM90-NEXT:    prmt.b32 %r9, %r8, %r5, 0x3340U;
; SM90-NEXT:    prmt.b32 %r11, %r33, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs8, %r11;
; SM90-NEXT:    add.s16 %rs9, %rs8, %rs7;
; SM90-NEXT:    cvt.u32.u16 %r12, %rs9;
; SM90-NEXT:    prmt.b32 %r14, %r33, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs11, %r14;
; SM90-NEXT:    add.s16 %rs12, %rs11, %rs10;
; SM90-NEXT:    cvt.u32.u16 %r15, %rs12;
; SM90-NEXT:    prmt.b32 %r16, %r15, %r12, 0x3340U;
; SM90-NEXT:    prmt.b32 %r17, %r16, %r9, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd3, %r17;
; SM90-NEXT:    cvt.u16.u32 %rs13, %r18;
; SM90-NEXT:    prmt.b32 %r19, %r34, 0, 0x7773U;
; SM90-NEXT:    cvt.u16.u32 %rs14, %r19;
; SM90-NEXT:    add.s16 %rs15, %rs14, %rs13;
; SM90-NEXT:    cvt.u32.u16 %r20, %rs15;
; SM90-NEXT:    cvt.u16.u32 %rs16, %r21;
; SM90-NEXT:    prmt.b32 %r22, %r34, 0, 0x7772U;
; SM90-NEXT:    cvt.u16.u32 %rs17, %r22;
; SM90-NEXT:    add.s16 %rs18, %rs17, %rs16;
; SM90-NEXT:    cvt.u32.u16 %r23, %rs18;
; SM90-NEXT:    prmt.b32 %r24, %r23, %r20, 0x3340U;
; SM90-NEXT:    prmt.b32 %r25, %r2, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs19, %r25;
; SM90-NEXT:    prmt.b32 %r26, %r34, 0, 0x7771U;
; SM90-NEXT:    cvt.u16.u32 %rs20, %r26;
; SM90-NEXT:    add.s16 %rs21, %rs20, %rs19;
; SM90-NEXT:    cvt.u32.u16 %r27, %rs21;
; SM90-NEXT:    prmt.b32 %r28, %r2, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs22, %r28;
; SM90-NEXT:    prmt.b32 %r29, %r34, 0, 0x7770U;
; SM90-NEXT:    cvt.u16.u32 %rs23, %r29;
; SM90-NEXT:    add.s16 %rs24, %rs23, %rs22;
; SM90-NEXT:    cvt.u32.u16 %r30, %rs24;
; SM90-NEXT:    prmt.b32 %r31, %r30, %r27, 0x3340U;
; SM90-NEXT:    prmt.b32 %r32, %r31, %r24, 0x5410U;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r32;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r33;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r34;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd10, %rd6;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd10;
; SM90-NEXT:    mov.b64 {_, %r34}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r33, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB351_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r33, %r34};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <8 x i8> %val syncscope("block") seq_cst
        ret <8 x i8> %retval
}

define <1 x i32> @add_monotonic_v1i32_global_cta(ptr addrspace(1) %addr, <1 x i32> %val) {
; SM90-LABEL: add_monotonic_v1i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<3>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [add_monotonic_v1i32_global_cta_param_0];
; SM90-NEXT:    ld.param.b32 %r1, [add_monotonic_v1i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r2, [%rd1], %r1;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <1 x i32> %val syncscope("block") monotonic
        ret <1 x i32> %retval
}

define <2 x i32> @add_monotonic_v2i32_global_cta(ptr addrspace(1) %addr, <2 x i32> %val) {
; SM90-LABEL: add_monotonic_v2i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [add_monotonic_v2i32_global_cta_param_0];
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [add_monotonic_v2i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r3, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r4, [%rd1+4], %r2;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r3, %r4};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <2 x i32> %val syncscope("block") monotonic
        ret <2 x i32> %retval
}

define <4 x i32> @add_monotonic_v4i32_global_cta(ptr addrspace(1) %addr, <4 x i32> %val) {
; SM90-LABEL: add_monotonic_v4i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<9>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [add_monotonic_v4i32_global_cta_param_0];
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [add_monotonic_v4i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r5, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r6, [%rd1+4], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r7, [%rd1+8], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r8, [%rd1+12], %r4;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <4 x i32> %val syncscope("block") monotonic
        ret <4 x i32> %retval
}

define <8 x i32> @add_monotonic_v8i32_global_cta(ptr addrspace(1) %addr, <8 x i32> %val) {
; SM90-LABEL: add_monotonic_v8i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<17>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [add_monotonic_v8i32_global_cta_param_0];
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [add_monotonic_v8i32_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [add_monotonic_v8i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r9, [%rd1], %r5;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r10, [%rd1+4], %r6;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r11, [%rd1+8], %r7;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r12, [%rd1+12], %r8;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r13, [%rd1+16], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r14, [%rd1+20], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r15, [%rd1+24], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r16, [%rd1+28], %r4;
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r13, %r14, %r15, %r16};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <8 x i32> %val syncscope("block") monotonic
        ret <8 x i32> %retval
}

define <1 x i32> @add_acquire_v1i32_global_cta(ptr addrspace(1) %addr, <1 x i32> %val) {
; SM90-LABEL: add_acquire_v1i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<3>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [add_acquire_v1i32_global_cta_param_0];
; SM90-NEXT:    ld.param.b32 %r1, [add_acquire_v1i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r2, [%rd1], %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <1 x i32> %val syncscope("block") acquire
        ret <1 x i32> %retval
}

define <2 x i32> @add_acquire_v2i32_global_cta(ptr addrspace(1) %addr, <2 x i32> %val) {
; SM90-LABEL: add_acquire_v2i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [add_acquire_v2i32_global_cta_param_0];
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [add_acquire_v2i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r3, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r4, [%rd1+4], %r2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r3, %r4};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <2 x i32> %val syncscope("block") acquire
        ret <2 x i32> %retval
}

define <4 x i32> @add_acquire_v4i32_global_cta(ptr addrspace(1) %addr, <4 x i32> %val) {
; SM90-LABEL: add_acquire_v4i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<9>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [add_acquire_v4i32_global_cta_param_0];
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [add_acquire_v4i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r5, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r6, [%rd1+4], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r7, [%rd1+8], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r8, [%rd1+12], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <4 x i32> %val syncscope("block") acquire
        ret <4 x i32> %retval
}

define <8 x i32> @add_acquire_v8i32_global_cta(ptr addrspace(1) %addr, <8 x i32> %val) {
; SM90-LABEL: add_acquire_v8i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<17>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [add_acquire_v8i32_global_cta_param_0];
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [add_acquire_v8i32_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [add_acquire_v8i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r9, [%rd1], %r5;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r10, [%rd1+4], %r6;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r11, [%rd1+8], %r7;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r12, [%rd1+12], %r8;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r13, [%rd1+16], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r14, [%rd1+20], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r15, [%rd1+24], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r16, [%rd1+28], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r13, %r14, %r15, %r16};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <8 x i32> %val syncscope("block") acquire
        ret <8 x i32> %retval
}

define <1 x i32> @add_release_v1i32_global_cta(ptr addrspace(1) %addr, <1 x i32> %val) {
; SM90-LABEL: add_release_v1i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<3>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [add_release_v1i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b32 %r1, [add_release_v1i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r2, [%rd1], %r1;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <1 x i32> %val syncscope("block") release
        ret <1 x i32> %retval
}

define <2 x i32> @add_release_v2i32_global_cta(ptr addrspace(1) %addr, <2 x i32> %val) {
; SM90-LABEL: add_release_v2i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [add_release_v2i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [add_release_v2i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r3, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r4, [%rd1+4], %r2;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r3, %r4};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <2 x i32> %val syncscope("block") release
        ret <2 x i32> %retval
}

define <4 x i32> @add_release_v4i32_global_cta(ptr addrspace(1) %addr, <4 x i32> %val) {
; SM90-LABEL: add_release_v4i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<9>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [add_release_v4i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [add_release_v4i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r5, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r6, [%rd1+4], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r7, [%rd1+8], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r8, [%rd1+12], %r4;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <4 x i32> %val syncscope("block") release
        ret <4 x i32> %retval
}

define <8 x i32> @add_release_v8i32_global_cta(ptr addrspace(1) %addr, <8 x i32> %val) {
; SM90-LABEL: add_release_v8i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<17>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [add_release_v8i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [add_release_v8i32_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [add_release_v8i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r9, [%rd1], %r5;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r10, [%rd1+4], %r6;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r11, [%rd1+8], %r7;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r12, [%rd1+12], %r8;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r13, [%rd1+16], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r14, [%rd1+20], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r15, [%rd1+24], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r16, [%rd1+28], %r4;
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r13, %r14, %r15, %r16};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <8 x i32> %val syncscope("block") release
        ret <8 x i32> %retval
}

define <1 x i32> @add_seq_cst_v1i32_global_cta(ptr addrspace(1) %addr, <1 x i32> %val) {
; SM90-LABEL: add_seq_cst_v1i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<3>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [add_seq_cst_v1i32_global_cta_param_0];
; SM90-NEXT:    fence.sc.cta;
; SM90-NEXT:    ld.param.b32 %r1, [add_seq_cst_v1i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r2, [%rd1], %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <1 x i32> %val syncscope("block") seq_cst
        ret <1 x i32> %retval
}

define <2 x i32> @add_seq_cst_v2i32_global_cta(ptr addrspace(1) %addr, <2 x i32> %val) {
; SM90-LABEL: add_seq_cst_v2i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<5>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [add_seq_cst_v2i32_global_cta_param_0];
; SM90-NEXT:    fence.sc.cta;
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [add_seq_cst_v2i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r3, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r4, [%rd1+4], %r2;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r3, %r4};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <2 x i32> %val syncscope("block") seq_cst
        ret <2 x i32> %retval
}

define <4 x i32> @add_seq_cst_v4i32_global_cta(ptr addrspace(1) %addr, <4 x i32> %val) {
; SM90-LABEL: add_seq_cst_v4i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<9>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [add_seq_cst_v4i32_global_cta_param_0];
; SM90-NEXT:    fence.sc.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [add_seq_cst_v4i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r5, [%rd1], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r6, [%rd1+4], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r7, [%rd1+8], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r8, [%rd1+12], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r5, %r6, %r7, %r8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <4 x i32> %val syncscope("block") seq_cst
        ret <4 x i32> %retval
}

define <8 x i32> @add_seq_cst_v8i32_global_cta(ptr addrspace(1) %addr, <8 x i32> %val) {
; SM90-LABEL: add_seq_cst_v8i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .b32 %r<17>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [add_seq_cst_v8i32_global_cta_param_0];
; SM90-NEXT:    fence.sc.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [add_seq_cst_v8i32_global_cta_param_1+16];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [add_seq_cst_v8i32_global_cta_param_1];
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r9, [%rd1], %r5;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r10, [%rd1+4], %r6;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r11, [%rd1+8], %r7;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r12, [%rd1+12], %r8;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r13, [%rd1+16], %r1;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r14, [%rd1+20], %r2;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r15, [%rd1+24], %r3;
; SM90-NEXT:    atom.relaxed.cta.global.add.u32 %r16, [%rd1+28], %r4;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r13, %r14, %r15, %r16};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise add ptr  addrspace(1) %addr, <8 x i32> %val syncscope("block") seq_cst
        ret <8 x i32> %retval
}

define <1 x i8> @nand_monotonic_v1i8_global_cta(ptr addrspace(1) %addr, <1 x i8> %val) {
; SM90-LABEL: nand_monotonic_v1i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<17>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [nand_monotonic_v1i8_global_cta_param_0];
; SM90-NEXT:    ld.param.b8 %r6, [nand_monotonic_v1i8_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd2;
; SM90-NEXT:    and.b32 %r8, %r7, 3;
; SM90-NEXT:    shl.b32 %r1, %r8, 3;
; SM90-NEXT:    mov.b32 %r9, 255;
; SM90-NEXT:    shl.b32 %r2, %r9, %r1;
; SM90-NEXT:    not.b32 %r3, %r2;
; SM90-NEXT:    shl.b32 %r4, %r6, %r1;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r16, [%rd1];
; SM90-NEXT:  $L__BB368_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b32 %r10, %r16, %r4;
; SM90-NEXT:    not.b32 %r11, %r10;
; SM90-NEXT:    and.b32 %r12, %r11, %r2;
; SM90-NEXT:    and.b32 %r13, %r16, %r3;
; SM90-NEXT:    or.b32 %r14, %r13, %r12;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r5, [%rd1], %r16, %r14;
; SM90-NEXT:    setp.ne.b32 %p1, %r5, %r16;
; SM90-NEXT:    mov.b32 %r16, %r5;
; SM90-NEXT:    @%p1 bra $L__BB368_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r15, %r5, %r1;
; SM90-NEXT:    st.param.b8 [func_retval0], %r15;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <1 x i8> %val syncscope("block") monotonic
        ret <1 x i8> %retval
}

define <2 x i8> @nand_monotonic_v2i8_global_cta(ptr addrspace(1) %addr, <2 x i8> %val) {
; SM90-LABEL: nand_monotonic_v2i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<9>;
; SM90-NEXT:    .reg .b32 %r<19>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b8 {%rs1, %rs2}, [nand_monotonic_v2i8_global_cta_param_1];
; SM90-NEXT:    mov.b32 %r4, {%rs1, %rs2};
; SM90-NEXT:    ld.param.b64 %rd2, [nand_monotonic_v2i8_global_cta_param_0];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:    and.b32 %r6, %r5, 3;
; SM90-NEXT:    shl.b32 %r1, %r6, 3;
; SM90-NEXT:    mov.b32 %r7, 65535;
; SM90-NEXT:    shl.b32 %r8, %r7, %r1;
; SM90-NEXT:    not.b32 %r2, %r8;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r18, [%rd1];
; SM90-NEXT:  $L__BB369_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r9, %r18, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs3, %r9;
; SM90-NEXT:    shr.u16 %rs4, %rs3, 8;
; SM90-NEXT:    mov.b32 %r10, {%rs3, %rs4};
; SM90-NEXT:    and.b32 %r11, %r10, %r4;
; SM90-NEXT:    xor.b32 %r12, %r11, 16711935;
; SM90-NEXT:    mov.b32 {%rs5, %rs6}, %r12;
; SM90-NEXT:    shl.b16 %rs7, %rs6, 8;
; SM90-NEXT:    or.b16 %rs8, %rs5, %rs7;
; SM90-NEXT:    cvt.u32.u16 %r13, %rs8;
; SM90-NEXT:    shl.b32 %r14, %r13, %r1;
; SM90-NEXT:    and.b32 %r15, %r18, %r2;
; SM90-NEXT:    or.b32 %r16, %r15, %r14;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r18, %r16;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r18;
; SM90-NEXT:    mov.b32 %r18, %r3;
; SM90-NEXT:    @%p1 bra $L__BB369_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r17, %r3, %r1;
; SM90-NEXT:    st.param.b16 [func_retval0], %r17;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <2 x i8> %val syncscope("block") monotonic
        ret <2 x i8> %retval
}

define <4 x i8> @nand_monotonic_v4i8_global_cta(ptr addrspace(1) %addr, <4 x i8> %val) {
; SM90-LABEL: nand_monotonic_v4i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<6>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [nand_monotonic_v4i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [nand_monotonic_v4i8_global_cta_param_0];
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r5, [%rd1];
; SM90-NEXT:  $L__BB370_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b32 %r3, %r5, %r2;
; SM90-NEXT:    xor.b32 %r4, %r3, -1;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r5, %r4;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r5;
; SM90-NEXT:    mov.b32 %r5, %r1;
; SM90-NEXT:    @%p1 bra $L__BB370_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <4 x i8> %val syncscope("block") monotonic
        ret <4 x i8> %retval
}

define <8 x i8> @nand_monotonic_v8i8_global_cta(ptr addrspace(1) %addr, <8 x i8> %val) {
; SM90-LABEL: nand_monotonic_v8i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<9>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [nand_monotonic_v8i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [nand_monotonic_v8i8_global_cta_param_0];
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r8}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd2;
; SM90-NEXT:  $L__BB371_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd3, %r7;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r8;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    and.b32 %r3, %r8, %r2;
; SM90-NEXT:    and.b32 %r4, %r7, %r1;
; SM90-NEXT:    xor.b32 %r5, %r4, -1;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    xor.b32 %r6, %r3, -1;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd6, %rd10;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd6;
; SM90-NEXT:    mov.b64 {_, %r8}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB371_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r7, %r8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <8 x i8> %val syncscope("block") monotonic
        ret <8 x i8> %retval
}

define <1 x i8> @nand_acquire_v1i8_global_cta(ptr addrspace(1) %addr, <1 x i8> %val) {
; SM90-LABEL: nand_acquire_v1i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<17>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [nand_acquire_v1i8_global_cta_param_0];
; SM90-NEXT:    ld.param.b8 %r6, [nand_acquire_v1i8_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd2;
; SM90-NEXT:    and.b32 %r8, %r7, 3;
; SM90-NEXT:    shl.b32 %r1, %r8, 3;
; SM90-NEXT:    mov.b32 %r9, 255;
; SM90-NEXT:    shl.b32 %r2, %r9, %r1;
; SM90-NEXT:    not.b32 %r3, %r2;
; SM90-NEXT:    shl.b32 %r4, %r6, %r1;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r16, [%rd1];
; SM90-NEXT:  $L__BB372_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b32 %r10, %r16, %r4;
; SM90-NEXT:    not.b32 %r11, %r10;
; SM90-NEXT:    and.b32 %r12, %r11, %r2;
; SM90-NEXT:    and.b32 %r13, %r16, %r3;
; SM90-NEXT:    or.b32 %r14, %r13, %r12;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r5, [%rd1], %r16, %r14;
; SM90-NEXT:    setp.ne.b32 %p1, %r5, %r16;
; SM90-NEXT:    mov.b32 %r16, %r5;
; SM90-NEXT:    @%p1 bra $L__BB372_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r15, %r5, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b8 [func_retval0], %r15;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <1 x i8> %val syncscope("block") acquire
        ret <1 x i8> %retval
}

define <2 x i8> @nand_acquire_v2i8_global_cta(ptr addrspace(1) %addr, <2 x i8> %val) {
; SM90-LABEL: nand_acquire_v2i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<9>;
; SM90-NEXT:    .reg .b32 %r<19>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b8 {%rs1, %rs2}, [nand_acquire_v2i8_global_cta_param_1];
; SM90-NEXT:    mov.b32 %r4, {%rs1, %rs2};
; SM90-NEXT:    ld.param.b64 %rd2, [nand_acquire_v2i8_global_cta_param_0];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:    and.b32 %r6, %r5, 3;
; SM90-NEXT:    shl.b32 %r1, %r6, 3;
; SM90-NEXT:    mov.b32 %r7, 65535;
; SM90-NEXT:    shl.b32 %r8, %r7, %r1;
; SM90-NEXT:    not.b32 %r2, %r8;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r18, [%rd1];
; SM90-NEXT:  $L__BB373_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r9, %r18, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs3, %r9;
; SM90-NEXT:    shr.u16 %rs4, %rs3, 8;
; SM90-NEXT:    mov.b32 %r10, {%rs3, %rs4};
; SM90-NEXT:    and.b32 %r11, %r10, %r4;
; SM90-NEXT:    xor.b32 %r12, %r11, 16711935;
; SM90-NEXT:    mov.b32 {%rs5, %rs6}, %r12;
; SM90-NEXT:    shl.b16 %rs7, %rs6, 8;
; SM90-NEXT:    or.b16 %rs8, %rs5, %rs7;
; SM90-NEXT:    cvt.u32.u16 %r13, %rs8;
; SM90-NEXT:    shl.b32 %r14, %r13, %r1;
; SM90-NEXT:    and.b32 %r15, %r18, %r2;
; SM90-NEXT:    or.b32 %r16, %r15, %r14;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r18, %r16;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r18;
; SM90-NEXT:    mov.b32 %r18, %r3;
; SM90-NEXT:    @%p1 bra $L__BB373_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r17, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r17;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <2 x i8> %val syncscope("block") acquire
        ret <2 x i8> %retval
}

define <4 x i8> @nand_acquire_v4i8_global_cta(ptr addrspace(1) %addr, <4 x i8> %val) {
; SM90-LABEL: nand_acquire_v4i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<6>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [nand_acquire_v4i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [nand_acquire_v4i8_global_cta_param_0];
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r5, [%rd1];
; SM90-NEXT:  $L__BB374_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b32 %r3, %r5, %r2;
; SM90-NEXT:    xor.b32 %r4, %r3, -1;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r5, %r4;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r5;
; SM90-NEXT:    mov.b32 %r5, %r1;
; SM90-NEXT:    @%p1 bra $L__BB374_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <4 x i8> %val syncscope("block") acquire
        ret <4 x i8> %retval
}

define <8 x i8> @nand_acquire_v8i8_global_cta(ptr addrspace(1) %addr, <8 x i8> %val) {
; SM90-LABEL: nand_acquire_v8i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<9>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [nand_acquire_v8i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [nand_acquire_v8i8_global_cta_param_0];
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r8}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd2;
; SM90-NEXT:  $L__BB375_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd3, %r7;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r8;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    and.b32 %r3, %r8, %r2;
; SM90-NEXT:    and.b32 %r4, %r7, %r1;
; SM90-NEXT:    xor.b32 %r5, %r4, -1;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    xor.b32 %r6, %r3, -1;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd6, %rd10;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd6;
; SM90-NEXT:    mov.b64 {_, %r8}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB375_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r7, %r8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <8 x i8> %val syncscope("block") acquire
        ret <8 x i8> %retval
}

define <1 x i8> @nand_release_v1i8_global_cta(ptr addrspace(1) %addr, <1 x i8> %val) {
; SM90-LABEL: nand_release_v1i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<17>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [nand_release_v1i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b8 %r6, [nand_release_v1i8_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd2;
; SM90-NEXT:    and.b32 %r8, %r7, 3;
; SM90-NEXT:    shl.b32 %r1, %r8, 3;
; SM90-NEXT:    mov.b32 %r9, 255;
; SM90-NEXT:    shl.b32 %r2, %r9, %r1;
; SM90-NEXT:    not.b32 %r3, %r2;
; SM90-NEXT:    shl.b32 %r4, %r6, %r1;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r16, [%rd1];
; SM90-NEXT:  $L__BB376_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b32 %r10, %r16, %r4;
; SM90-NEXT:    not.b32 %r11, %r10;
; SM90-NEXT:    and.b32 %r12, %r11, %r2;
; SM90-NEXT:    and.b32 %r13, %r16, %r3;
; SM90-NEXT:    or.b32 %r14, %r13, %r12;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r5, [%rd1], %r16, %r14;
; SM90-NEXT:    setp.ne.b32 %p1, %r5, %r16;
; SM90-NEXT:    mov.b32 %r16, %r5;
; SM90-NEXT:    @%p1 bra $L__BB376_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r15, %r5, %r1;
; SM90-NEXT:    st.param.b8 [func_retval0], %r15;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <1 x i8> %val syncscope("block") release
        ret <1 x i8> %retval
}

define <2 x i8> @nand_release_v2i8_global_cta(ptr addrspace(1) %addr, <2 x i8> %val) {
; SM90-LABEL: nand_release_v2i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<9>;
; SM90-NEXT:    .reg .b32 %r<19>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b8 {%rs1, %rs2}, [nand_release_v2i8_global_cta_param_1];
; SM90-NEXT:    mov.b32 %r4, {%rs1, %rs2};
; SM90-NEXT:    ld.param.b64 %rd2, [nand_release_v2i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:    and.b32 %r6, %r5, 3;
; SM90-NEXT:    shl.b32 %r1, %r6, 3;
; SM90-NEXT:    mov.b32 %r7, 65535;
; SM90-NEXT:    shl.b32 %r8, %r7, %r1;
; SM90-NEXT:    not.b32 %r2, %r8;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r18, [%rd1];
; SM90-NEXT:  $L__BB377_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r9, %r18, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs3, %r9;
; SM90-NEXT:    shr.u16 %rs4, %rs3, 8;
; SM90-NEXT:    mov.b32 %r10, {%rs3, %rs4};
; SM90-NEXT:    and.b32 %r11, %r10, %r4;
; SM90-NEXT:    xor.b32 %r12, %r11, 16711935;
; SM90-NEXT:    mov.b32 {%rs5, %rs6}, %r12;
; SM90-NEXT:    shl.b16 %rs7, %rs6, 8;
; SM90-NEXT:    or.b16 %rs8, %rs5, %rs7;
; SM90-NEXT:    cvt.u32.u16 %r13, %rs8;
; SM90-NEXT:    shl.b32 %r14, %r13, %r1;
; SM90-NEXT:    and.b32 %r15, %r18, %r2;
; SM90-NEXT:    or.b32 %r16, %r15, %r14;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r18, %r16;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r18;
; SM90-NEXT:    mov.b32 %r18, %r3;
; SM90-NEXT:    @%p1 bra $L__BB377_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r17, %r3, %r1;
; SM90-NEXT:    st.param.b16 [func_retval0], %r17;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <2 x i8> %val syncscope("block") release
        ret <2 x i8> %retval
}

define <4 x i8> @nand_release_v4i8_global_cta(ptr addrspace(1) %addr, <4 x i8> %val) {
; SM90-LABEL: nand_release_v4i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<6>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [nand_release_v4i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [nand_release_v4i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r5, [%rd1];
; SM90-NEXT:  $L__BB378_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b32 %r3, %r5, %r2;
; SM90-NEXT:    xor.b32 %r4, %r3, -1;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r5, %r4;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r5;
; SM90-NEXT:    mov.b32 %r5, %r1;
; SM90-NEXT:    @%p1 bra $L__BB378_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <4 x i8> %val syncscope("block") release
        ret <4 x i8> %retval
}

define <8 x i8> @nand_release_v8i8_global_cta(ptr addrspace(1) %addr, <8 x i8> %val) {
; SM90-LABEL: nand_release_v8i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<9>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [nand_release_v8i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [nand_release_v8i8_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r8}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd2;
; SM90-NEXT:  $L__BB379_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd3, %r7;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r8;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    and.b32 %r3, %r8, %r2;
; SM90-NEXT:    and.b32 %r4, %r7, %r1;
; SM90-NEXT:    xor.b32 %r5, %r4, -1;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    xor.b32 %r6, %r3, -1;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd6, %rd10;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd6;
; SM90-NEXT:    mov.b64 {_, %r8}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB379_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r7, %r8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <8 x i8> %val syncscope("block") release
        ret <8 x i8> %retval
}

define <1 x i8> @nand_seq_cst_v1i8_global_cta(ptr addrspace(1) %addr, <1 x i8> %val) {
; SM90-LABEL: nand_seq_cst_v1i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<17>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd2, [nand_seq_cst_v1i8_global_cta_param_0];
; SM90-NEXT:    fence.sc.cta;
; SM90-NEXT:    ld.param.b8 %r6, [nand_seq_cst_v1i8_global_cta_param_1];
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd2;
; SM90-NEXT:    and.b32 %r8, %r7, 3;
; SM90-NEXT:    shl.b32 %r1, %r8, 3;
; SM90-NEXT:    mov.b32 %r9, 255;
; SM90-NEXT:    shl.b32 %r2, %r9, %r1;
; SM90-NEXT:    not.b32 %r3, %r2;
; SM90-NEXT:    shl.b32 %r4, %r6, %r1;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r16, [%rd1];
; SM90-NEXT:  $L__BB380_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b32 %r10, %r16, %r4;
; SM90-NEXT:    not.b32 %r11, %r10;
; SM90-NEXT:    and.b32 %r12, %r11, %r2;
; SM90-NEXT:    and.b32 %r13, %r16, %r3;
; SM90-NEXT:    or.b32 %r14, %r13, %r12;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r5, [%rd1], %r16, %r14;
; SM90-NEXT:    setp.ne.b32 %p1, %r5, %r16;
; SM90-NEXT:    mov.b32 %r16, %r5;
; SM90-NEXT:    @%p1 bra $L__BB380_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r15, %r5, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b8 [func_retval0], %r15;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <1 x i8> %val syncscope("block") seq_cst
        ret <1 x i8> %retval
}

define <2 x i8> @nand_seq_cst_v2i8_global_cta(ptr addrspace(1) %addr, <2 x i8> %val) {
; SM90-LABEL: nand_seq_cst_v2i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b16 %rs<9>;
; SM90-NEXT:    .reg .b32 %r<19>;
; SM90-NEXT:    .reg .b64 %rd<3>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b8 {%rs1, %rs2}, [nand_seq_cst_v2i8_global_cta_param_1];
; SM90-NEXT:    mov.b32 %r4, {%rs1, %rs2};
; SM90-NEXT:    ld.param.b64 %rd2, [nand_seq_cst_v2i8_global_cta_param_0];
; SM90-NEXT:    fence.sc.cta;
; SM90-NEXT:    and.b64 %rd1, %rd2, -4;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:    and.b32 %r6, %r5, 3;
; SM90-NEXT:    shl.b32 %r1, %r6, 3;
; SM90-NEXT:    mov.b32 %r7, 65535;
; SM90-NEXT:    shl.b32 %r8, %r7, %r1;
; SM90-NEXT:    not.b32 %r2, %r8;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r18, [%rd1];
; SM90-NEXT:  $L__BB381_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    shr.u32 %r9, %r18, %r1;
; SM90-NEXT:    cvt.u16.u32 %rs3, %r9;
; SM90-NEXT:    shr.u16 %rs4, %rs3, 8;
; SM90-NEXT:    mov.b32 %r10, {%rs3, %rs4};
; SM90-NEXT:    and.b32 %r11, %r10, %r4;
; SM90-NEXT:    xor.b32 %r12, %r11, 16711935;
; SM90-NEXT:    mov.b32 {%rs5, %rs6}, %r12;
; SM90-NEXT:    shl.b16 %rs7, %rs6, 8;
; SM90-NEXT:    or.b16 %rs8, %rs5, %rs7;
; SM90-NEXT:    cvt.u32.u16 %r13, %rs8;
; SM90-NEXT:    shl.b32 %r14, %r13, %r1;
; SM90-NEXT:    and.b32 %r15, %r18, %r2;
; SM90-NEXT:    or.b32 %r16, %r15, %r14;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r3, [%rd1], %r18, %r16;
; SM90-NEXT:    setp.ne.b32 %p1, %r3, %r18;
; SM90-NEXT:    mov.b32 %r18, %r3;
; SM90-NEXT:    @%p1 bra $L__BB381_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    shr.u32 %r17, %r3, %r1;
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b16 [func_retval0], %r17;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <2 x i8> %val syncscope("block") seq_cst
        ret <2 x i8> %retval
}

define <4 x i8> @nand_seq_cst_v4i8_global_cta(ptr addrspace(1) %addr, <4 x i8> %val) {
; SM90-LABEL: nand_seq_cst_v4i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<6>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b32 %r2, [nand_seq_cst_v4i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [nand_seq_cst_v4i8_global_cta_param_0];
; SM90-NEXT:    fence.sc.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r5, [%rd1];
; SM90-NEXT:  $L__BB382_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b32 %r3, %r5, %r2;
; SM90-NEXT:    xor.b32 %r4, %r3, -1;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r1, [%rd1], %r5, %r4;
; SM90-NEXT:    setp.ne.b32 %p1, %r1, %r5;
; SM90-NEXT:    mov.b32 %r5, %r1;
; SM90-NEXT:    @%p1 bra $L__BB382_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r1;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <4 x i8> %val syncscope("block") seq_cst
        ret <4 x i8> %retval
}

define <8 x i8> @nand_seq_cst_v8i8_global_cta(ptr addrspace(1) %addr, <8 x i8> %val) {
; SM90-LABEL: nand_seq_cst_v8i8_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<9>;
; SM90-NEXT:    .reg .b64 %rd<12>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [nand_seq_cst_v8i8_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [nand_seq_cst_v8i8_global_cta_param_0];
; SM90-NEXT:    fence.sc.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r8}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd2;
; SM90-NEXT:  $L__BB383_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd3, %r7;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r8;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    and.b32 %r3, %r8, %r2;
; SM90-NEXT:    and.b32 %r4, %r7, %r1;
; SM90-NEXT:    xor.b32 %r5, %r4, -1;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r5;
; SM90-NEXT:    xor.b32 %r6, %r3, -1;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r6;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd11, [%rd1], %rd6, %rd10;
; SM90-NEXT:    setp.ne.b64 %p1, %rd11, %rd6;
; SM90-NEXT:    mov.b64 {_, %r8}, %rd11;
; SM90-NEXT:    cvt.u32.u64 %r7, %rd11;
; SM90-NEXT:    @%p1 bra $L__BB383_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r7, %r8};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <8 x i8> %val syncscope("block") seq_cst
        ret <8 x i8> %retval
}

define <1 x i32> @nand_monotonic_v1i32_global_cta(ptr addrspace(1) %addr, <1 x i32> %val) {
; SM90-LABEL: nand_monotonic_v1i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<6>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [nand_monotonic_v1i32_global_cta_param_0];
; SM90-NEXT:    ld.param.b32 %r1, [nand_monotonic_v1i32_global_cta_param_1];
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r5, [%rd1];
; SM90-NEXT:  $L__BB384_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b32 %r3, %r5, %r1;
; SM90-NEXT:    not.b32 %r4, %r3;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r2, [%rd1], %r5, %r4;
; SM90-NEXT:    setp.ne.b32 %p1, %r2, %r5;
; SM90-NEXT:    mov.b32 %r5, %r2;
; SM90-NEXT:    @%p1 bra $L__BB384_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <1 x i32> %val syncscope("block") monotonic
        ret <1 x i32> %retval
}

define <2 x i32> @nand_monotonic_v2i32_global_cta(ptr addrspace(1) %addr, <2 x i32> %val) {
; SM90-LABEL: nand_monotonic_v2i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<13>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [nand_monotonic_v2i32_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [nand_monotonic_v2i32_global_cta_param_0];
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB385_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd3, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r6;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    and.b32 %r3, %r6, %r2;
; SM90-NEXT:    and.b32 %r4, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r3;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    not.b64 %rd11, %rd10;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd12, [%rd1], %rd6, %rd11;
; SM90-NEXT:    setp.ne.b64 %p1, %rd12, %rd6;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd12;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd12;
; SM90-NEXT:    @%p1 bra $L__BB385_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <2 x i32> %val syncscope("block") monotonic
        ret <2 x i32> %retval
}

define <4 x i32> @nand_monotonic_v4i32_global_cta(ptr addrspace(1) %addr, <4 x i32> %val) {
; SM90-LABEL: nand_monotonic_v4i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<28>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [nand_monotonic_v4i32_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [nand_monotonic_v4i32_global_cta_param_0];
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB386_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd5, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r10;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r12;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    and.b32 %r5, %r12, %r4;
; SM90-NEXT:    and.b32 %r6, %r11, %r3;
; SM90-NEXT:    and.b32 %r7, %r10, %r2;
; SM90-NEXT:    and.b32 %r8, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r8;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r7;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    not.b64 %rd17, %rd16;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r6;
; SM90-NEXT:    cvt.u64.u32 %rd19, %r5;
; SM90-NEXT:    shl.b64 %rd20, %rd19, 32;
; SM90-NEXT:    or.b64 %rd21, %rd18, %rd20;
; SM90-NEXT:    not.b64 %rd22, %rd21;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd8, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd17, %rd22};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd23, %rd24}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd25, %rd24, %rd12;
; SM90-NEXT:    xor.b64 %rd26, %rd23, %rd8;
; SM90-NEXT:    or.b64 %rd27, %rd26, %rd25;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd24;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd24;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd23;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd23;
; SM90-NEXT:    setp.ne.b64 %p1, %rd27, 0;
; SM90-NEXT:    @%p1 bra $L__BB386_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <4 x i32> %val syncscope("block") monotonic
        ret <4 x i32> %retval
}

define <8 x i32> @nand_monotonic_v8i32_global_cta(ptr addrspace(1) %addr, <8 x i32> %val) {
; SM90-LABEL: nand_monotonic_v8i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<3>;
; SM90-NEXT:    .reg .b32 %r<25>;
; SM90-NEXT:    .reg .b64 %rd<54>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [nand_monotonic_v8i32_global_cta_param_0];
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [nand_monotonic_v8i32_global_cta_param_1];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [nand_monotonic_v8i32_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r20}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r19, %rd4;
; SM90-NEXT:    mov.b64 {_, %r18}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r17, %rd3;
; SM90-NEXT:  $L__BB387_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd5, %r17;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r18;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r19;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r20;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    and.b32 %r9, %r20, %r4;
; SM90-NEXT:    and.b32 %r10, %r19, %r3;
; SM90-NEXT:    and.b32 %r11, %r18, %r2;
; SM90-NEXT:    and.b32 %r12, %r17, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r12;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r11;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    not.b64 %rd17, %rd16;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r10;
; SM90-NEXT:    cvt.u64.u32 %rd19, %r9;
; SM90-NEXT:    shl.b64 %rd20, %rd19, 32;
; SM90-NEXT:    or.b64 %rd21, %rd18, %rd20;
; SM90-NEXT:    not.b64 %rd22, %rd21;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd8, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd17, %rd22};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd23, %rd24}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd25, %rd24, %rd12;
; SM90-NEXT:    xor.b64 %rd26, %rd23, %rd8;
; SM90-NEXT:    or.b64 %rd27, %rd26, %rd25;
; SM90-NEXT:    mov.b64 {_, %r20}, %rd24;
; SM90-NEXT:    cvt.u32.u64 %r19, %rd24;
; SM90-NEXT:    mov.b64 {_, %r18}, %rd23;
; SM90-NEXT:    cvt.u32.u64 %r17, %rd23;
; SM90-NEXT:    setp.ne.b64 %p1, %rd27, 0;
; SM90-NEXT:    @%p1 bra $L__BB387_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd28, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd28, %rd28};
; SM90-NEXT:    mov.b128 swap, {%rd28, %rd28};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd29, %rd30}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r24}, %rd30;
; SM90-NEXT:    cvt.u32.u64 %r23, %rd30;
; SM90-NEXT:    mov.b64 {_, %r22}, %rd29;
; SM90-NEXT:    cvt.u32.u64 %r21, %rd29;
; SM90-NEXT:  $L__BB387_3: // %atomicrmw.start2
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd31, %r21;
; SM90-NEXT:    cvt.u64.u32 %rd32, %r22;
; SM90-NEXT:    shl.b64 %rd33, %rd32, 32;
; SM90-NEXT:    or.b64 %rd34, %rd31, %rd33;
; SM90-NEXT:    cvt.u64.u32 %rd35, %r23;
; SM90-NEXT:    cvt.u64.u32 %rd36, %r24;
; SM90-NEXT:    shl.b64 %rd37, %rd36, 32;
; SM90-NEXT:    or.b64 %rd38, %rd35, %rd37;
; SM90-NEXT:    and.b32 %r13, %r24, %r8;
; SM90-NEXT:    and.b32 %r14, %r23, %r7;
; SM90-NEXT:    and.b32 %r15, %r22, %r6;
; SM90-NEXT:    and.b32 %r16, %r21, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd39, %r16;
; SM90-NEXT:    cvt.u64.u32 %rd40, %r15;
; SM90-NEXT:    shl.b64 %rd41, %rd40, 32;
; SM90-NEXT:    or.b64 %rd42, %rd39, %rd41;
; SM90-NEXT:    not.b64 %rd43, %rd42;
; SM90-NEXT:    cvt.u64.u32 %rd44, %r14;
; SM90-NEXT:    cvt.u64.u32 %rd45, %r13;
; SM90-NEXT:    shl.b64 %rd46, %rd45, 32;
; SM90-NEXT:    or.b64 %rd47, %rd44, %rd46;
; SM90-NEXT:    not.b64 %rd48, %rd47;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd34, %rd38};
; SM90-NEXT:    mov.b128 swap, {%rd43, %rd48};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd49, %rd50}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd51, %rd50, %rd38;
; SM90-NEXT:    xor.b64 %rd52, %rd49, %rd34;
; SM90-NEXT:    or.b64 %rd53, %rd52, %rd51;
; SM90-NEXT:    mov.b64 {_, %r24}, %rd50;
; SM90-NEXT:    cvt.u32.u64 %r23, %rd50;
; SM90-NEXT:    mov.b64 {_, %r22}, %rd49;
; SM90-NEXT:    cvt.u32.u64 %r21, %rd49;
; SM90-NEXT:    setp.ne.b64 %p2, %rd53, 0;
; SM90-NEXT:    @%p2 bra $L__BB387_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end1
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r21, %r22, %r23, %r24};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r17, %r18, %r19, %r20};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <8 x i32> %val syncscope("block") monotonic
        ret <8 x i32> %retval
}

define <1 x i32> @nand_acquire_v1i32_global_cta(ptr addrspace(1) %addr, <1 x i32> %val) {
; SM90-LABEL: nand_acquire_v1i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<6>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [nand_acquire_v1i32_global_cta_param_0];
; SM90-NEXT:    ld.param.b32 %r1, [nand_acquire_v1i32_global_cta_param_1];
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r5, [%rd1];
; SM90-NEXT:  $L__BB388_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b32 %r3, %r5, %r1;
; SM90-NEXT:    not.b32 %r4, %r3;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r2, [%rd1], %r5, %r4;
; SM90-NEXT:    setp.ne.b32 %p1, %r2, %r5;
; SM90-NEXT:    mov.b32 %r5, %r2;
; SM90-NEXT:    @%p1 bra $L__BB388_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <1 x i32> %val syncscope("block") acquire
        ret <1 x i32> %retval
}

define <2 x i32> @nand_acquire_v2i32_global_cta(ptr addrspace(1) %addr, <2 x i32> %val) {
; SM90-LABEL: nand_acquire_v2i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<13>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [nand_acquire_v2i32_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [nand_acquire_v2i32_global_cta_param_0];
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB389_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd3, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r6;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    and.b32 %r3, %r6, %r2;
; SM90-NEXT:    and.b32 %r4, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r3;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    not.b64 %rd11, %rd10;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd12, [%rd1], %rd6, %rd11;
; SM90-NEXT:    setp.ne.b64 %p1, %rd12, %rd6;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd12;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd12;
; SM90-NEXT:    @%p1 bra $L__BB389_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <2 x i32> %val syncscope("block") acquire
        ret <2 x i32> %retval
}

define <4 x i32> @nand_acquire_v4i32_global_cta(ptr addrspace(1) %addr, <4 x i32> %val) {
; SM90-LABEL: nand_acquire_v4i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<28>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [nand_acquire_v4i32_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [nand_acquire_v4i32_global_cta_param_0];
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB390_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd5, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r10;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r12;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    and.b32 %r5, %r12, %r4;
; SM90-NEXT:    and.b32 %r6, %r11, %r3;
; SM90-NEXT:    and.b32 %r7, %r10, %r2;
; SM90-NEXT:    and.b32 %r8, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r8;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r7;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    not.b64 %rd17, %rd16;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r6;
; SM90-NEXT:    cvt.u64.u32 %rd19, %r5;
; SM90-NEXT:    shl.b64 %rd20, %rd19, 32;
; SM90-NEXT:    or.b64 %rd21, %rd18, %rd20;
; SM90-NEXT:    not.b64 %rd22, %rd21;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd8, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd17, %rd22};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd23, %rd24}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd25, %rd24, %rd12;
; SM90-NEXT:    xor.b64 %rd26, %rd23, %rd8;
; SM90-NEXT:    or.b64 %rd27, %rd26, %rd25;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd24;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd24;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd23;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd23;
; SM90-NEXT:    setp.ne.b64 %p1, %rd27, 0;
; SM90-NEXT:    @%p1 bra $L__BB390_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <4 x i32> %val syncscope("block") acquire
        ret <4 x i32> %retval
}

define <8 x i32> @nand_acquire_v8i32_global_cta(ptr addrspace(1) %addr, <8 x i32> %val) {
; SM90-LABEL: nand_acquire_v8i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<3>;
; SM90-NEXT:    .reg .b32 %r<25>;
; SM90-NEXT:    .reg .b64 %rd<54>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [nand_acquire_v8i32_global_cta_param_0];
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [nand_acquire_v8i32_global_cta_param_1];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [nand_acquire_v8i32_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r20}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r19, %rd4;
; SM90-NEXT:    mov.b64 {_, %r18}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r17, %rd3;
; SM90-NEXT:  $L__BB391_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd5, %r17;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r18;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r19;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r20;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    and.b32 %r9, %r20, %r4;
; SM90-NEXT:    and.b32 %r10, %r19, %r3;
; SM90-NEXT:    and.b32 %r11, %r18, %r2;
; SM90-NEXT:    and.b32 %r12, %r17, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r12;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r11;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    not.b64 %rd17, %rd16;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r10;
; SM90-NEXT:    cvt.u64.u32 %rd19, %r9;
; SM90-NEXT:    shl.b64 %rd20, %rd19, 32;
; SM90-NEXT:    or.b64 %rd21, %rd18, %rd20;
; SM90-NEXT:    not.b64 %rd22, %rd21;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd8, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd17, %rd22};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd23, %rd24}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd25, %rd24, %rd12;
; SM90-NEXT:    xor.b64 %rd26, %rd23, %rd8;
; SM90-NEXT:    or.b64 %rd27, %rd26, %rd25;
; SM90-NEXT:    mov.b64 {_, %r20}, %rd24;
; SM90-NEXT:    cvt.u32.u64 %r19, %rd24;
; SM90-NEXT:    mov.b64 {_, %r18}, %rd23;
; SM90-NEXT:    cvt.u32.u64 %r17, %rd23;
; SM90-NEXT:    setp.ne.b64 %p1, %rd27, 0;
; SM90-NEXT:    @%p1 bra $L__BB391_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd28, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd28, %rd28};
; SM90-NEXT:    mov.b128 swap, {%rd28, %rd28};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd29, %rd30}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r24}, %rd30;
; SM90-NEXT:    cvt.u32.u64 %r23, %rd30;
; SM90-NEXT:    mov.b64 {_, %r22}, %rd29;
; SM90-NEXT:    cvt.u32.u64 %r21, %rd29;
; SM90-NEXT:  $L__BB391_3: // %atomicrmw.start2
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd31, %r21;
; SM90-NEXT:    cvt.u64.u32 %rd32, %r22;
; SM90-NEXT:    shl.b64 %rd33, %rd32, 32;
; SM90-NEXT:    or.b64 %rd34, %rd31, %rd33;
; SM90-NEXT:    cvt.u64.u32 %rd35, %r23;
; SM90-NEXT:    cvt.u64.u32 %rd36, %r24;
; SM90-NEXT:    shl.b64 %rd37, %rd36, 32;
; SM90-NEXT:    or.b64 %rd38, %rd35, %rd37;
; SM90-NEXT:    and.b32 %r13, %r24, %r8;
; SM90-NEXT:    and.b32 %r14, %r23, %r7;
; SM90-NEXT:    and.b32 %r15, %r22, %r6;
; SM90-NEXT:    and.b32 %r16, %r21, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd39, %r16;
; SM90-NEXT:    cvt.u64.u32 %rd40, %r15;
; SM90-NEXT:    shl.b64 %rd41, %rd40, 32;
; SM90-NEXT:    or.b64 %rd42, %rd39, %rd41;
; SM90-NEXT:    not.b64 %rd43, %rd42;
; SM90-NEXT:    cvt.u64.u32 %rd44, %r14;
; SM90-NEXT:    cvt.u64.u32 %rd45, %r13;
; SM90-NEXT:    shl.b64 %rd46, %rd45, 32;
; SM90-NEXT:    or.b64 %rd47, %rd44, %rd46;
; SM90-NEXT:    not.b64 %rd48, %rd47;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd34, %rd38};
; SM90-NEXT:    mov.b128 swap, {%rd43, %rd48};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd49, %rd50}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd51, %rd50, %rd38;
; SM90-NEXT:    xor.b64 %rd52, %rd49, %rd34;
; SM90-NEXT:    or.b64 %rd53, %rd52, %rd51;
; SM90-NEXT:    mov.b64 {_, %r24}, %rd50;
; SM90-NEXT:    cvt.u32.u64 %r23, %rd50;
; SM90-NEXT:    mov.b64 {_, %r22}, %rd49;
; SM90-NEXT:    cvt.u32.u64 %r21, %rd49;
; SM90-NEXT:    setp.ne.b64 %p2, %rd53, 0;
; SM90-NEXT:    @%p2 bra $L__BB391_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end1
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r21, %r22, %r23, %r24};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r17, %r18, %r19, %r20};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <8 x i32> %val syncscope("block") acquire
        ret <8 x i32> %retval
}

define <1 x i32> @nand_release_v1i32_global_cta(ptr addrspace(1) %addr, <1 x i32> %val) {
; SM90-LABEL: nand_release_v1i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<6>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [nand_release_v1i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.b32 %r1, [nand_release_v1i32_global_cta_param_1];
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r5, [%rd1];
; SM90-NEXT:  $L__BB392_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b32 %r3, %r5, %r1;
; SM90-NEXT:    not.b32 %r4, %r3;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r2, [%rd1], %r5, %r4;
; SM90-NEXT:    setp.ne.b32 %p1, %r2, %r5;
; SM90-NEXT:    mov.b32 %r5, %r2;
; SM90-NEXT:    @%p1 bra $L__BB392_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <1 x i32> %val syncscope("block") release
        ret <1 x i32> %retval
}

define <2 x i32> @nand_release_v2i32_global_cta(ptr addrspace(1) %addr, <2 x i32> %val) {
; SM90-LABEL: nand_release_v2i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<13>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [nand_release_v2i32_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [nand_release_v2i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB393_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd3, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r6;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    and.b32 %r3, %r6, %r2;
; SM90-NEXT:    and.b32 %r4, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r3;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    not.b64 %rd11, %rd10;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd12, [%rd1], %rd6, %rd11;
; SM90-NEXT:    setp.ne.b64 %p1, %rd12, %rd6;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd12;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd12;
; SM90-NEXT:    @%p1 bra $L__BB393_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <2 x i32> %val syncscope("block") release
        ret <2 x i32> %retval
}

define <4 x i32> @nand_release_v4i32_global_cta(ptr addrspace(1) %addr, <4 x i32> %val) {
; SM90-LABEL: nand_release_v4i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<28>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [nand_release_v4i32_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [nand_release_v4i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB394_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd5, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r10;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r12;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    and.b32 %r5, %r12, %r4;
; SM90-NEXT:    and.b32 %r6, %r11, %r3;
; SM90-NEXT:    and.b32 %r7, %r10, %r2;
; SM90-NEXT:    and.b32 %r8, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r8;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r7;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    not.b64 %rd17, %rd16;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r6;
; SM90-NEXT:    cvt.u64.u32 %rd19, %r5;
; SM90-NEXT:    shl.b64 %rd20, %rd19, 32;
; SM90-NEXT:    or.b64 %rd21, %rd18, %rd20;
; SM90-NEXT:    not.b64 %rd22, %rd21;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd8, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd17, %rd22};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd23, %rd24}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd25, %rd24, %rd12;
; SM90-NEXT:    xor.b64 %rd26, %rd23, %rd8;
; SM90-NEXT:    or.b64 %rd27, %rd26, %rd25;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd24;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd24;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd23;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd23;
; SM90-NEXT:    setp.ne.b64 %p1, %rd27, 0;
; SM90-NEXT:    @%p1 bra $L__BB394_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <4 x i32> %val syncscope("block") release
        ret <4 x i32> %retval
}

define <8 x i32> @nand_release_v8i32_global_cta(ptr addrspace(1) %addr, <8 x i32> %val) {
; SM90-LABEL: nand_release_v8i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<3>;
; SM90-NEXT:    .reg .b32 %r<25>;
; SM90-NEXT:    .reg .b64 %rd<54>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [nand_release_v8i32_global_cta_param_0];
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [nand_release_v8i32_global_cta_param_1];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [nand_release_v8i32_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r20}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r19, %rd4;
; SM90-NEXT:    mov.b64 {_, %r18}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r17, %rd3;
; SM90-NEXT:  $L__BB395_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd5, %r17;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r18;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r19;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r20;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    and.b32 %r9, %r20, %r4;
; SM90-NEXT:    and.b32 %r10, %r19, %r3;
; SM90-NEXT:    and.b32 %r11, %r18, %r2;
; SM90-NEXT:    and.b32 %r12, %r17, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r12;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r11;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    not.b64 %rd17, %rd16;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r10;
; SM90-NEXT:    cvt.u64.u32 %rd19, %r9;
; SM90-NEXT:    shl.b64 %rd20, %rd19, 32;
; SM90-NEXT:    or.b64 %rd21, %rd18, %rd20;
; SM90-NEXT:    not.b64 %rd22, %rd21;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd8, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd17, %rd22};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd23, %rd24}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd25, %rd24, %rd12;
; SM90-NEXT:    xor.b64 %rd26, %rd23, %rd8;
; SM90-NEXT:    or.b64 %rd27, %rd26, %rd25;
; SM90-NEXT:    mov.b64 {_, %r20}, %rd24;
; SM90-NEXT:    cvt.u32.u64 %r19, %rd24;
; SM90-NEXT:    mov.b64 {_, %r18}, %rd23;
; SM90-NEXT:    cvt.u32.u64 %r17, %rd23;
; SM90-NEXT:    setp.ne.b64 %p1, %rd27, 0;
; SM90-NEXT:    @%p1 bra $L__BB395_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd28, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd28, %rd28};
; SM90-NEXT:    mov.b128 swap, {%rd28, %rd28};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd29, %rd30}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r24}, %rd30;
; SM90-NEXT:    cvt.u32.u64 %r23, %rd30;
; SM90-NEXT:    mov.b64 {_, %r22}, %rd29;
; SM90-NEXT:    cvt.u32.u64 %r21, %rd29;
; SM90-NEXT:  $L__BB395_3: // %atomicrmw.start2
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd31, %r21;
; SM90-NEXT:    cvt.u64.u32 %rd32, %r22;
; SM90-NEXT:    shl.b64 %rd33, %rd32, 32;
; SM90-NEXT:    or.b64 %rd34, %rd31, %rd33;
; SM90-NEXT:    cvt.u64.u32 %rd35, %r23;
; SM90-NEXT:    cvt.u64.u32 %rd36, %r24;
; SM90-NEXT:    shl.b64 %rd37, %rd36, 32;
; SM90-NEXT:    or.b64 %rd38, %rd35, %rd37;
; SM90-NEXT:    and.b32 %r13, %r24, %r8;
; SM90-NEXT:    and.b32 %r14, %r23, %r7;
; SM90-NEXT:    and.b32 %r15, %r22, %r6;
; SM90-NEXT:    and.b32 %r16, %r21, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd39, %r16;
; SM90-NEXT:    cvt.u64.u32 %rd40, %r15;
; SM90-NEXT:    shl.b64 %rd41, %rd40, 32;
; SM90-NEXT:    or.b64 %rd42, %rd39, %rd41;
; SM90-NEXT:    not.b64 %rd43, %rd42;
; SM90-NEXT:    cvt.u64.u32 %rd44, %r14;
; SM90-NEXT:    cvt.u64.u32 %rd45, %r13;
; SM90-NEXT:    shl.b64 %rd46, %rd45, 32;
; SM90-NEXT:    or.b64 %rd47, %rd44, %rd46;
; SM90-NEXT:    not.b64 %rd48, %rd47;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd34, %rd38};
; SM90-NEXT:    mov.b128 swap, {%rd43, %rd48};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd49, %rd50}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd51, %rd50, %rd38;
; SM90-NEXT:    xor.b64 %rd52, %rd49, %rd34;
; SM90-NEXT:    or.b64 %rd53, %rd52, %rd51;
; SM90-NEXT:    mov.b64 {_, %r24}, %rd50;
; SM90-NEXT:    cvt.u32.u64 %r23, %rd50;
; SM90-NEXT:    mov.b64 {_, %r22}, %rd49;
; SM90-NEXT:    cvt.u32.u64 %r21, %rd49;
; SM90-NEXT:    setp.ne.b64 %p2, %rd53, 0;
; SM90-NEXT:    @%p2 bra $L__BB395_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end1
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r21, %r22, %r23, %r24};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r17, %r18, %r19, %r20};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <8 x i32> %val syncscope("block") release
        ret <8 x i32> %retval
}

define <1 x i32> @nand_seq_cst_v1i32_global_cta(ptr addrspace(1) %addr, <1 x i32> %val) {
; SM90-LABEL: nand_seq_cst_v1i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<6>;
; SM90-NEXT:    .reg .b64 %rd<2>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [nand_seq_cst_v1i32_global_cta_param_0];
; SM90-NEXT:    fence.sc.cta;
; SM90-NEXT:    ld.param.b32 %r1, [nand_seq_cst_v1i32_global_cta_param_1];
; SM90-NEXT:    ld.relaxed.cta.global.b32 %r5, [%rd1];
; SM90-NEXT:  $L__BB396_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    and.b32 %r3, %r5, %r1;
; SM90-NEXT:    not.b32 %r4, %r3;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b32 %r2, [%rd1], %r5, %r4;
; SM90-NEXT:    setp.ne.b32 %p1, %r2, %r5;
; SM90-NEXT:    mov.b32 %r5, %r2;
; SM90-NEXT:    @%p1 bra $L__BB396_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.b32 [func_retval0], %r2;
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <1 x i32> %val syncscope("block") seq_cst
        ret <1 x i32> %retval
}

define <2 x i32> @nand_seq_cst_v2i32_global_cta(ptr addrspace(1) %addr, <2 x i32> %val) {
; SM90-LABEL: nand_seq_cst_v2i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<7>;
; SM90-NEXT:    .reg .b64 %rd<13>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v2.b32 {%r1, %r2}, [nand_seq_cst_v2i32_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [nand_seq_cst_v2i32_global_cta_param_0];
; SM90-NEXT:    fence.sc.cta;
; SM90-NEXT:    ld.relaxed.cta.global.b64 %rd2, [%rd1];
; SM90-NEXT:    mov.b64 {_, %r6}, %rd2;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd2;
; SM90-NEXT:  $L__BB397_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd3, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd4, %r6;
; SM90-NEXT:    shl.b64 %rd5, %rd4, 32;
; SM90-NEXT:    or.b64 %rd6, %rd3, %rd5;
; SM90-NEXT:    and.b32 %r3, %r6, %r2;
; SM90-NEXT:    and.b32 %r4, %r5, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd7, %r4;
; SM90-NEXT:    cvt.u64.u32 %rd8, %r3;
; SM90-NEXT:    shl.b64 %rd9, %rd8, 32;
; SM90-NEXT:    or.b64 %rd10, %rd7, %rd9;
; SM90-NEXT:    not.b64 %rd11, %rd10;
; SM90-NEXT:    atom.relaxed.cta.global.cas.b64 %rd12, [%rd1], %rd6, %rd11;
; SM90-NEXT:    setp.ne.b64 %p1, %rd12, %rd6;
; SM90-NEXT:    mov.b64 {_, %r6}, %rd12;
; SM90-NEXT:    cvt.u32.u64 %r5, %rd12;
; SM90-NEXT:    @%p1 bra $L__BB397_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v2.b32 [func_retval0], {%r5, %r6};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <2 x i32> %val syncscope("block") seq_cst
        ret <2 x i32> %retval
}

define <4 x i32> @nand_seq_cst_v4i32_global_cta(ptr addrspace(1) %addr, <4 x i32> %val) {
; SM90-LABEL: nand_seq_cst_v4i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<2>;
; SM90-NEXT:    .reg .b32 %r<13>;
; SM90-NEXT:    .reg .b64 %rd<28>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [nand_seq_cst_v4i32_global_cta_param_1];
; SM90-NEXT:    ld.param.b64 %rd1, [nand_seq_cst_v4i32_global_cta_param_0];
; SM90-NEXT:    fence.sc.cta;
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r12}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd4;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd3;
; SM90-NEXT:  $L__BB398_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd5, %r9;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r10;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r11;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r12;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    and.b32 %r5, %r12, %r4;
; SM90-NEXT:    and.b32 %r6, %r11, %r3;
; SM90-NEXT:    and.b32 %r7, %r10, %r2;
; SM90-NEXT:    and.b32 %r8, %r9, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r8;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r7;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    not.b64 %rd17, %rd16;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r6;
; SM90-NEXT:    cvt.u64.u32 %rd19, %r5;
; SM90-NEXT:    shl.b64 %rd20, %rd19, 32;
; SM90-NEXT:    or.b64 %rd21, %rd18, %rd20;
; SM90-NEXT:    not.b64 %rd22, %rd21;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd8, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd17, %rd22};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd23, %rd24}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd25, %rd24, %rd12;
; SM90-NEXT:    xor.b64 %rd26, %rd23, %rd8;
; SM90-NEXT:    or.b64 %rd27, %rd26, %rd25;
; SM90-NEXT:    mov.b64 {_, %r12}, %rd24;
; SM90-NEXT:    cvt.u32.u64 %r11, %rd24;
; SM90-NEXT:    mov.b64 {_, %r10}, %rd23;
; SM90-NEXT:    cvt.u32.u64 %r9, %rd23;
; SM90-NEXT:    setp.ne.b64 %p1, %rd27, 0;
; SM90-NEXT:    @%p1 bra $L__BB398_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r9, %r10, %r11, %r12};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <4 x i32> %val syncscope("block") seq_cst
        ret <4 x i32> %retval
}

define <8 x i32> @nand_seq_cst_v8i32_global_cta(ptr addrspace(1) %addr, <8 x i32> %val) {
; SM90-LABEL: nand_seq_cst_v8i32_global_cta(
; SM90:       {
; SM90-NEXT:    .reg .pred %p<3>;
; SM90-NEXT:    .reg .b32 %r<25>;
; SM90-NEXT:    .reg .b64 %rd<54>;
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    ld.param.b64 %rd1, [nand_seq_cst_v8i32_global_cta_param_0];
; SM90-NEXT:    fence.sc.cta;
; SM90-NEXT:    ld.param.v4.b32 {%r1, %r2, %r3, %r4}, [nand_seq_cst_v8i32_global_cta_param_1];
; SM90-NEXT:    ld.param.v4.b32 {%r5, %r6, %r7, %r8}, [nand_seq_cst_v8i32_global_cta_param_1+16];
; SM90-NEXT:    mov.b64 %rd2, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd2, %rd2};
; SM90-NEXT:    mov.b128 swap, {%rd2, %rd2};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd3, %rd4}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r20}, %rd4;
; SM90-NEXT:    cvt.u32.u64 %r19, %rd4;
; SM90-NEXT:    mov.b64 {_, %r18}, %rd3;
; SM90-NEXT:    cvt.u32.u64 %r17, %rd3;
; SM90-NEXT:  $L__BB399_1: // %atomicrmw.start
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd5, %r17;
; SM90-NEXT:    cvt.u64.u32 %rd6, %r18;
; SM90-NEXT:    shl.b64 %rd7, %rd6, 32;
; SM90-NEXT:    or.b64 %rd8, %rd5, %rd7;
; SM90-NEXT:    cvt.u64.u32 %rd9, %r19;
; SM90-NEXT:    cvt.u64.u32 %rd10, %r20;
; SM90-NEXT:    shl.b64 %rd11, %rd10, 32;
; SM90-NEXT:    or.b64 %rd12, %rd9, %rd11;
; SM90-NEXT:    and.b32 %r9, %r20, %r4;
; SM90-NEXT:    and.b32 %r10, %r19, %r3;
; SM90-NEXT:    and.b32 %r11, %r18, %r2;
; SM90-NEXT:    and.b32 %r12, %r17, %r1;
; SM90-NEXT:    cvt.u64.u32 %rd13, %r12;
; SM90-NEXT:    cvt.u64.u32 %rd14, %r11;
; SM90-NEXT:    shl.b64 %rd15, %rd14, 32;
; SM90-NEXT:    or.b64 %rd16, %rd13, %rd15;
; SM90-NEXT:    not.b64 %rd17, %rd16;
; SM90-NEXT:    cvt.u64.u32 %rd18, %r10;
; SM90-NEXT:    cvt.u64.u32 %rd19, %r9;
; SM90-NEXT:    shl.b64 %rd20, %rd19, 32;
; SM90-NEXT:    or.b64 %rd21, %rd18, %rd20;
; SM90-NEXT:    not.b64 %rd22, %rd21;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd8, %rd12};
; SM90-NEXT:    mov.b128 swap, {%rd17, %rd22};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd23, %rd24}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd25, %rd24, %rd12;
; SM90-NEXT:    xor.b64 %rd26, %rd23, %rd8;
; SM90-NEXT:    or.b64 %rd27, %rd26, %rd25;
; SM90-NEXT:    mov.b64 {_, %r20}, %rd24;
; SM90-NEXT:    cvt.u32.u64 %r19, %rd24;
; SM90-NEXT:    mov.b64 {_, %r18}, %rd23;
; SM90-NEXT:    cvt.u32.u64 %r17, %rd23;
; SM90-NEXT:    setp.ne.b64 %p1, %rd27, 0;
; SM90-NEXT:    @%p1 bra $L__BB399_1;
; SM90-NEXT:  // %bb.2: // %atomicrmw.end
; SM90-NEXT:    mov.b64 %rd28, 0;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd28, %rd28};
; SM90-NEXT:    mov.b128 swap, {%rd28, %rd28};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd29, %rd30}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    mov.b64 {_, %r24}, %rd30;
; SM90-NEXT:    cvt.u32.u64 %r23, %rd30;
; SM90-NEXT:    mov.b64 {_, %r22}, %rd29;
; SM90-NEXT:    cvt.u32.u64 %r21, %rd29;
; SM90-NEXT:  $L__BB399_3: // %atomicrmw.start2
; SM90-NEXT:    // =>This Inner Loop Header: Depth=1
; SM90-NEXT:    cvt.u64.u32 %rd31, %r21;
; SM90-NEXT:    cvt.u64.u32 %rd32, %r22;
; SM90-NEXT:    shl.b64 %rd33, %rd32, 32;
; SM90-NEXT:    or.b64 %rd34, %rd31, %rd33;
; SM90-NEXT:    cvt.u64.u32 %rd35, %r23;
; SM90-NEXT:    cvt.u64.u32 %rd36, %r24;
; SM90-NEXT:    shl.b64 %rd37, %rd36, 32;
; SM90-NEXT:    or.b64 %rd38, %rd35, %rd37;
; SM90-NEXT:    and.b32 %r13, %r24, %r8;
; SM90-NEXT:    and.b32 %r14, %r23, %r7;
; SM90-NEXT:    and.b32 %r15, %r22, %r6;
; SM90-NEXT:    and.b32 %r16, %r21, %r5;
; SM90-NEXT:    cvt.u64.u32 %rd39, %r16;
; SM90-NEXT:    cvt.u64.u32 %rd40, %r15;
; SM90-NEXT:    shl.b64 %rd41, %rd40, 32;
; SM90-NEXT:    or.b64 %rd42, %rd39, %rd41;
; SM90-NEXT:    not.b64 %rd43, %rd42;
; SM90-NEXT:    cvt.u64.u32 %rd44, %r14;
; SM90-NEXT:    cvt.u64.u32 %rd45, %r13;
; SM90-NEXT:    shl.b64 %rd46, %rd45, 32;
; SM90-NEXT:    or.b64 %rd47, %rd44, %rd46;
; SM90-NEXT:    not.b64 %rd48, %rd47;
; SM90-NEXT:    {
; SM90-NEXT:    .reg .b128 cmp, swap, dst;
; SM90-NEXT:    mov.b128 cmp, {%rd34, %rd38};
; SM90-NEXT:    mov.b128 swap, {%rd43, %rd48};
; SM90-NEXT:    atom.relaxed.cta.global.cas.b128 dst, [%rd1+16], cmp, swap;
; SM90-NEXT:    mov.b128 {%rd49, %rd50}, dst;
; SM90-NEXT:    }
; SM90-NEXT:    xor.b64 %rd51, %rd50, %rd38;
; SM90-NEXT:    xor.b64 %rd52, %rd49, %rd34;
; SM90-NEXT:    or.b64 %rd53, %rd52, %rd51;
; SM90-NEXT:    mov.b64 {_, %r24}, %rd50;
; SM90-NEXT:    cvt.u32.u64 %r23, %rd50;
; SM90-NEXT:    mov.b64 {_, %r22}, %rd49;
; SM90-NEXT:    cvt.u32.u64 %r21, %rd49;
; SM90-NEXT:    setp.ne.b64 %p2, %rd53, 0;
; SM90-NEXT:    @%p2 bra $L__BB399_3;
; SM90-NEXT:  // %bb.4: // %atomicrmw.end1
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    st.param.v4.b32 [func_retval0+16], {%r21, %r22, %r23, %r24};
; SM90-NEXT:    st.param.v4.b32 [func_retval0], {%r17, %r18, %r19, %r20};
; SM90-NEXT:    ret;
        %retval = atomicrmw elementwise nand ptr  addrspace(1) %addr, <8 x i32> %val syncscope("block") seq_cst
        ret <8 x i32> %retval
}
