; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --filter "^\s*(?:mov\.b64|ld(?:\.[A-Za-z0-9_:]+)*\.global|st(?:\.[A-Za-z0-9_:]+)*\.global|atom(?:\.[A-Za-z0-9_:]+)*\.global)" --version 6
; RUN: llc < %s -mtriple=nvptx64 -mcpu=sm_80 -mattr=+ptx74 | FileCheck %s
; RUN: %if ptxas %{ llc < %s -mtriple=nvptx64 -mcpu=sm_80 -mattr=+ptx74 | %ptxas-verify %}

; Test !mem.cache_hint metadata on LLVM memory intrinsics.
;
; For memcpy:
;   operand_no = 0 applies to destination (store side)
;   operand_no = 1 applies to source (load side)

declare void @llvm.memcpy.p1.p1.i64(ptr addrspace(1), ptr addrspace(1), i64, i1)
declare <2 x i16> @llvm.masked.load.v2i16.p1(ptr addrspace(1), <2 x i1>, <2 x i16>)
declare <4 x i32> @llvm.masked.load.v4i32.p1(ptr addrspace(1), <4 x i1>, <4 x i32>)

;-----------------------------------------------------------------------------
; Test memcpy with cache hints on both source and destination
; Source (operand 1): L1::evict_first, L2::evict_first, L2::128B
; Dest (operand 0): L1::evict_last, L2::evict_last
;-----------------------------------------------------------------------------

define void @test_memcpy_both_hints(ptr addrspace(1) %dest, ptr addrspace(1) %src) {
; CHECK-LABEL: test_memcpy_both_hints(
; CHECK:    ld.global.L1::evict_first.L2::evict_first.L2::128B.b8 %rs1, [%rd2+3];
; CHECK:    st.global.L1::evict_last.L2::evict_last.b8 [%rd1+3], %rs1;
; CHECK:    ld.global.L1::evict_first.L2::evict_first.L2::128B.b8 %rs2, [%rd2+2];
; CHECK:    st.global.L1::evict_last.L2::evict_last.b8 [%rd1+2], %rs2;
; CHECK:    ld.global.L1::evict_first.L2::evict_first.L2::128B.b8 %rs3, [%rd2+1];
; CHECK:    st.global.L1::evict_last.L2::evict_last.b8 [%rd1+1], %rs3;
; CHECK:    ld.global.L1::evict_first.L2::evict_first.L2::128B.b8 %rs4, [%rd2];
; CHECK:    st.global.L1::evict_last.L2::evict_last.b8 [%rd1], %rs4;
  call void @llvm.memcpy.p1.p1.i64(ptr addrspace(1) %dest, ptr addrspace(1) %src, i64 4, i1 false), !mem.cache_hint !80
  ret void
}

;-----------------------------------------------------------------------------
; Test memcpy with cache hint only on source (load side)
; Source (operand 1): L1::evict_first
; Dest (operand 0): no hint
;-----------------------------------------------------------------------------

define void @test_memcpy_src_hint_only(ptr addrspace(1) %dest, ptr addrspace(1) %src) {
; CHECK-LABEL: test_memcpy_src_hint_only(
; CHECK:    ld.global.L1::evict_first.b8 %rs1, [%rd2+3];
; CHECK:    st.global.b8 [%rd1+3], %rs1;
; CHECK:    ld.global.L1::evict_first.b8 %rs2, [%rd2+2];
; CHECK:    st.global.b8 [%rd1+2], %rs2;
; CHECK:    ld.global.L1::evict_first.b8 %rs3, [%rd2+1];
; CHECK:    st.global.b8 [%rd1+1], %rs3;
; CHECK:    ld.global.L1::evict_first.b8 %rs4, [%rd2];
; CHECK:    st.global.b8 [%rd1], %rs4;
  call void @llvm.memcpy.p1.p1.i64(ptr addrspace(1) %dest, ptr addrspace(1) %src, i64 4, i1 false), !mem.cache_hint !81
  ret void
}

;-----------------------------------------------------------------------------
; Test memcpy with cache hint only on destination (store side)
; Source (operand 1): no hint
; Dest (operand 0): L2::evict_last
;-----------------------------------------------------------------------------

define void @test_memcpy_dest_hint_only(ptr addrspace(1) %dest, ptr addrspace(1) %src) {
; CHECK-LABEL: test_memcpy_dest_hint_only(
; CHECK:    ld.global.b8 %rs1, [%rd2+3];
; CHECK:    st.global.L2::evict_last.b8 [%rd1+3], %rs1;
; CHECK:    ld.global.b8 %rs2, [%rd2+2];
; CHECK:    st.global.L2::evict_last.b8 [%rd1+2], %rs2;
; CHECK:    ld.global.b8 %rs3, [%rd2+1];
; CHECK:    st.global.L2::evict_last.b8 [%rd1+1], %rs3;
; CHECK:    ld.global.b8 %rs4, [%rd2];
; CHECK:    st.global.L2::evict_last.b8 [%rd1], %rs4;
  call void @llvm.memcpy.p1.p1.i64(ptr addrspace(1) %dest, ptr addrspace(1) %src, i64 4, i1 false), !mem.cache_hint !82
  ret void
}

;-----------------------------------------------------------------------------
; Test memcpy with L2::cache_hint on both operands
;-----------------------------------------------------------------------------

define void @test_memcpy_l2_cache_hint(ptr addrspace(1) %dest, ptr addrspace(1) %src) {
; CHECK-LABEL: test_memcpy_l2_cache_hint(
; CHECK:    mov.b64 %rd2, 12345;
; CHECK:    ld.global.L2::cache_hint.b8 %rs1, [%rd3+3], %rd2;
; CHECK:    st.global.L2::cache_hint.b8 [%rd1+3], %rs1, %rd2;
; CHECK:    ld.global.L2::cache_hint.b8 %rs2, [%rd3+2], %rd2;
; CHECK:    st.global.L2::cache_hint.b8 [%rd1+2], %rs2, %rd2;
; CHECK:    ld.global.L2::cache_hint.b8 %rs3, [%rd3+1], %rd2;
; CHECK:    st.global.L2::cache_hint.b8 [%rd1+1], %rs3, %rd2;
; CHECK:    ld.global.L2::cache_hint.b8 %rs4, [%rd3], %rd2;
; CHECK:    st.global.L2::cache_hint.b8 [%rd1], %rs4, %rd2;
  call void @llvm.memcpy.p1.p1.i64(ptr addrspace(1) %dest, ptr addrspace(1) %src, i64 4, i1 false), !mem.cache_hint !83
  ret void
}

;-----------------------------------------------------------------------------
; Test memcpy without cache hints produces plain load/store
;-----------------------------------------------------------------------------

define void @test_memcpy_no_hint(ptr addrspace(1) %dest, ptr addrspace(1) %src) {
; CHECK-LABEL: test_memcpy_no_hint(
; CHECK:    ld.global.b8 %rs1, [%rd2+3];
; CHECK:    st.global.b8 [%rd1+3], %rs1;
; CHECK:    ld.global.b8 %rs2, [%rd2+2];
; CHECK:    st.global.b8 [%rd1+2], %rs2;
; CHECK:    ld.global.b8 %rs3, [%rd2+1];
; CHECK:    st.global.b8 [%rd1+1], %rs3;
; CHECK:    ld.global.b8 %rs4, [%rd2];
; CHECK:    st.global.b8 [%rd1], %rs4;
  call void @llvm.memcpy.p1.p1.i64(ptr addrspace(1) %dest, ptr addrspace(1) %src, i64 4, i1 false)
  ret void
}

;-----------------------------------------------------------------------------
; Combined L1 + L2 eviction policies
;-----------------------------------------------------------------------------

; Source: L1::evict_first + L2::evict_last
; Dest: no hint
define void @test_memcpy_src_l1_l2_combined(ptr addrspace(1) %dest, ptr addrspace(1) %src) {
; CHECK-LABEL: test_memcpy_src_l1_l2_combined(
; CHECK:    ld.global.L1::evict_first.L2::evict_last.b8 %rs1, [%rd2+3];
; CHECK:    st.global.b8 [%rd1+3], %rs1;
; CHECK:    ld.global.L1::evict_first.L2::evict_last.b8 %rs2, [%rd2+2];
; CHECK:    st.global.b8 [%rd1+2], %rs2;
; CHECK:    ld.global.L1::evict_first.L2::evict_last.b8 %rs3, [%rd2+1];
; CHECK:    st.global.b8 [%rd1+1], %rs3;
; CHECK:    ld.global.L1::evict_first.L2::evict_last.b8 %rs4, [%rd2];
; CHECK:    st.global.b8 [%rd1], %rs4;
  call void @llvm.memcpy.p1.p1.i64(ptr addrspace(1) %dest, ptr addrspace(1) %src, i64 4, i1 false), !mem.cache_hint !84
  ret void
}

; Source: no hint
; Dest: L1::evict_unchanged + L2::evict_first
define void @test_memcpy_dest_l1_l2_combined(ptr addrspace(1) %dest, ptr addrspace(1) %src) {
; CHECK-LABEL: test_memcpy_dest_l1_l2_combined(
; CHECK:    ld.global.b8 %rs1, [%rd2+3];
; CHECK:    st.global.L1::evict_unchanged.L2::evict_first.b8 [%rd1+3], %rs1;
; CHECK:    ld.global.b8 %rs2, [%rd2+2];
; CHECK:    st.global.L1::evict_unchanged.L2::evict_first.b8 [%rd1+2], %rs2;
; CHECK:    ld.global.b8 %rs3, [%rd2+1];
; CHECK:    st.global.L1::evict_unchanged.L2::evict_first.b8 [%rd1+1], %rs3;
; CHECK:    ld.global.b8 %rs4, [%rd2];
; CHECK:    st.global.L1::evict_unchanged.L2::evict_first.b8 [%rd1], %rs4;
  call void @llvm.memcpy.p1.p1.i64(ptr addrspace(1) %dest, ptr addrspace(1) %src, i64 4, i1 false), !mem.cache_hint !85
  ret void
}

;-----------------------------------------------------------------------------
; L1 + prefetch combinations
;-----------------------------------------------------------------------------

; Source: L1::evict_last + L2::256B prefetch
; Dest: L1::no_allocate
define void @test_memcpy_l1_prefetch(ptr addrspace(1) %dest, ptr addrspace(1) %src) {
; CHECK-LABEL: test_memcpy_l1_prefetch(
; CHECK:    ld.global.L1::evict_last.L2::256B.b8 %rs1, [%rd2+3];
; CHECK:    st.global.L1::no_allocate.b8 [%rd1+3], %rs1;
; CHECK:    ld.global.L1::evict_last.L2::256B.b8 %rs2, [%rd2+2];
; CHECK:    st.global.L1::no_allocate.b8 [%rd1+2], %rs2;
; CHECK:    ld.global.L1::evict_last.L2::256B.b8 %rs3, [%rd2+1];
; CHECK:    st.global.L1::no_allocate.b8 [%rd1+1], %rs3;
; CHECK:    ld.global.L1::evict_last.L2::256B.b8 %rs4, [%rd2];
; CHECK:    st.global.L1::no_allocate.b8 [%rd1], %rs4;
  call void @llvm.memcpy.p1.p1.i64(ptr addrspace(1) %dest, ptr addrspace(1) %src, i64 4, i1 false), !mem.cache_hint !86
  ret void
}

; Source: L2::64B prefetch only
; Dest: L2::evict_last only
define void @test_memcpy_prefetch_vs_eviction(ptr addrspace(1) %dest, ptr addrspace(1) %src) {
; CHECK-LABEL: test_memcpy_prefetch_vs_eviction(
; CHECK:    ld.global.L2::64B.b8 %rs1, [%rd2+3];
; CHECK:    st.global.L2::evict_last.b8 [%rd1+3], %rs1;
; CHECK:    ld.global.L2::64B.b8 %rs2, [%rd2+2];
; CHECK:    st.global.L2::evict_last.b8 [%rd1+2], %rs2;
; CHECK:    ld.global.L2::64B.b8 %rs3, [%rd2+1];
; CHECK:    st.global.L2::evict_last.b8 [%rd1+1], %rs3;
; CHECK:    ld.global.L2::64B.b8 %rs4, [%rd2];
; CHECK:    st.global.L2::evict_last.b8 [%rd1], %rs4;
  call void @llvm.memcpy.p1.p1.i64(ptr addrspace(1) %dest, ptr addrspace(1) %src, i64 4, i1 false), !mem.cache_hint !87
  ret void
}

;-----------------------------------------------------------------------------
; L2::cache_hint combined with other hints
;-----------------------------------------------------------------------------

; Source: L2::cache_hint + L1::evict_first
; Dest: no hint
define void @test_memcpy_src_cache_hint_l1(ptr addrspace(1) %dest, ptr addrspace(1) %src) {
; CHECK-LABEL: test_memcpy_src_cache_hint_l1(
; CHECK:    mov.b64 %rd2, 12345;
; CHECK:    ld.global.L1::evict_first.L2::cache_hint.b8 %rs1, [%rd3+3], %rd2;
; CHECK:    st.global.b8 [%rd1+3], %rs1;
; CHECK:    ld.global.L1::evict_first.L2::cache_hint.b8 %rs2, [%rd3+2], %rd2;
; CHECK:    st.global.b8 [%rd1+2], %rs2;
; CHECK:    ld.global.L1::evict_first.L2::cache_hint.b8 %rs3, [%rd3+1], %rd2;
; CHECK:    st.global.b8 [%rd1+1], %rs3;
; CHECK:    ld.global.L1::evict_first.L2::cache_hint.b8 %rs4, [%rd3], %rd2;
; CHECK:    st.global.b8 [%rd1], %rs4;
  call void @llvm.memcpy.p1.p1.i64(ptr addrspace(1) %dest, ptr addrspace(1) %src, i64 4, i1 false), !mem.cache_hint !88
  ret void
}

; Source: no hint
; Dest: L2::cache_hint + L1::evict_last + L2::evict_first
define void @test_memcpy_dest_cache_hint_combined(ptr addrspace(1) %dest, ptr addrspace(1) %src) {
; CHECK-LABEL: test_memcpy_dest_cache_hint_combined(
; CHECK:    ld.global.b8 %rs1, [%rd2+3];
; CHECK:    mov.b64 %rd3, 12345;
; CHECK:    st.global.L1::evict_last.L2::evict_first.L2::cache_hint.b8 [%rd1+3], %rs1, %rd3;
; CHECK:    ld.global.b8 %rs2, [%rd2+2];
; CHECK:    st.global.L1::evict_last.L2::evict_first.L2::cache_hint.b8 [%rd1+2], %rs2, %rd3;
; CHECK:    ld.global.b8 %rs3, [%rd2+1];
; CHECK:    st.global.L1::evict_last.L2::evict_first.L2::cache_hint.b8 [%rd1+1], %rs3, %rd3;
; CHECK:    ld.global.b8 %rs4, [%rd2];
; CHECK:    st.global.L1::evict_last.L2::evict_first.L2::cache_hint.b8 [%rd1], %rs4, %rd3;
  call void @llvm.memcpy.p1.p1.i64(ptr addrspace(1) %dest, ptr addrspace(1) %src, i64 4, i1 false), !mem.cache_hint !89
  ret void
}

; Both operands: L2::cache_hint + L1 eviction + L2 eviction
; Source: L2::cache_hint + L1::evict_unchanged + L2::evict_last
; Dest: L2::cache_hint + L1::evict_first + L2::evict_first
define void @test_memcpy_both_cache_hint_combined(ptr addrspace(1) %dest, ptr addrspace(1) %src) {
; CHECK-LABEL: test_memcpy_both_cache_hint_combined(
; CHECK:    mov.b64 %rd2, 12345;
; CHECK:    ld.global.L1::evict_unchanged.L2::evict_last.L2::cache_hint.b8 %rs1, [%rd3+3], %rd2;
; CHECK:    st.global.L1::evict_first.L2::evict_first.L2::cache_hint.b8 [%rd1+3], %rs1, %rd2;
; CHECK:    ld.global.L1::evict_unchanged.L2::evict_last.L2::cache_hint.b8 %rs2, [%rd3+2], %rd2;
; CHECK:    st.global.L1::evict_first.L2::evict_first.L2::cache_hint.b8 [%rd1+2], %rs2, %rd2;
; CHECK:    ld.global.L1::evict_unchanged.L2::evict_last.L2::cache_hint.b8 %rs3, [%rd3+1], %rd2;
; CHECK:    st.global.L1::evict_first.L2::evict_first.L2::cache_hint.b8 [%rd1+1], %rs3, %rd2;
; CHECK:    ld.global.L1::evict_unchanged.L2::evict_last.L2::cache_hint.b8 %rs4, [%rd3], %rd2;
; CHECK:    st.global.L1::evict_first.L2::evict_first.L2::cache_hint.b8 [%rd1], %rs4, %rd2;
  call void @llvm.memcpy.p1.p1.i64(ptr addrspace(1) %dest, ptr addrspace(1) %src, i64 4, i1 false), !mem.cache_hint !90
  ret void
}

;-----------------------------------------------------------------------------
; L2::cache_hint + prefetch combinations
;-----------------------------------------------------------------------------

; Source: L2::cache_hint + L2::128B prefetch
; Dest: L2::cache_hint + L1::evict_last
define void @test_memcpy_cache_hint_prefetch(ptr addrspace(1) %dest, ptr addrspace(1) %src) {
; CHECK-LABEL: test_memcpy_cache_hint_prefetch(
; CHECK:    mov.b64 %rd2, 12345;
; CHECK:    ld.global.L2::cache_hint.L2::128B.b8 %rs1, [%rd3+3], %rd2;
; CHECK:    st.global.L1::evict_last.L2::cache_hint.b8 [%rd1+3], %rs1, %rd2;
; CHECK:    ld.global.L2::cache_hint.L2::128B.b8 %rs2, [%rd3+2], %rd2;
; CHECK:    st.global.L1::evict_last.L2::cache_hint.b8 [%rd1+2], %rs2, %rd2;
; CHECK:    ld.global.L2::cache_hint.L2::128B.b8 %rs3, [%rd3+1], %rd2;
; CHECK:    st.global.L1::evict_last.L2::cache_hint.b8 [%rd1+1], %rs3, %rd2;
; CHECK:    ld.global.L2::cache_hint.L2::128B.b8 %rs4, [%rd3], %rd2;
; CHECK:    st.global.L1::evict_last.L2::cache_hint.b8 [%rd1], %rs4, %rd2;
  call void @llvm.memcpy.p1.p1.i64(ptr addrspace(1) %dest, ptr addrspace(1) %src, i64 4, i1 false), !mem.cache_hint !91
  ret void
}

;-----------------------------------------------------------------------------
; Asymmetric hint combinations (complex vs simple)
;-----------------------------------------------------------------------------

; Source: all hints (L1 + L2 eviction + prefetch)
; Dest: simple L1 hint only
define void @test_memcpy_complex_src_simple_dest(ptr addrspace(1) %dest, ptr addrspace(1) %src) {
; CHECK-LABEL: test_memcpy_complex_src_simple_dest(
; CHECK:    ld.global.L1::evict_first.L2::evict_last.L2::64B.b8 %rs1, [%rd2+3];
; CHECK:    st.global.L1::evict_last.b8 [%rd1+3], %rs1;
; CHECK:    ld.global.L1::evict_first.L2::evict_last.L2::64B.b8 %rs2, [%rd2+2];
; CHECK:    st.global.L1::evict_last.b8 [%rd1+2], %rs2;
; CHECK:    ld.global.L1::evict_first.L2::evict_last.L2::64B.b8 %rs3, [%rd2+1];
; CHECK:    st.global.L1::evict_last.b8 [%rd1+1], %rs3;
; CHECK:    ld.global.L1::evict_first.L2::evict_last.L2::64B.b8 %rs4, [%rd2];
; CHECK:    st.global.L1::evict_last.b8 [%rd1], %rs4;
  call void @llvm.memcpy.p1.p1.i64(ptr addrspace(1) %dest, ptr addrspace(1) %src, i64 4, i1 false), !mem.cache_hint !92
  ret void
}

; Source: simple L2 prefetch only
; Dest: all hints (L1 + L2 eviction + L2::cache_hint)
define void @test_memcpy_simple_src_complex_dest(ptr addrspace(1) %dest, ptr addrspace(1) %src) {
; CHECK-LABEL: test_memcpy_simple_src_complex_dest(
; CHECK:    ld.global.L2::256B.b8 %rs1, [%rd2+3];
; CHECK:    mov.b64 %rd3, 12345;
; CHECK:    st.global.L1::no_allocate.L2::evict_last.L2::cache_hint.b8 [%rd1+3], %rs1, %rd3;
; CHECK:    ld.global.L2::256B.b8 %rs2, [%rd2+2];
; CHECK:    st.global.L1::no_allocate.L2::evict_last.L2::cache_hint.b8 [%rd1+2], %rs2, %rd3;
; CHECK:    ld.global.L2::256B.b8 %rs3, [%rd2+1];
; CHECK:    st.global.L1::no_allocate.L2::evict_last.L2::cache_hint.b8 [%rd1+1], %rs3, %rd3;
; CHECK:    ld.global.L2::256B.b8 %rs4, [%rd2];
; CHECK:    st.global.L1::no_allocate.L2::evict_last.L2::cache_hint.b8 [%rd1], %rs4, %rd3;
  call void @llvm.memcpy.p1.p1.i64(ptr addrspace(1) %dest, ptr addrspace(1) %src, i64 4, i1 false), !mem.cache_hint !93
  ret void
}

;-----------------------------------------------------------------------------
; Different L1 eviction policies on src vs dest
;-----------------------------------------------------------------------------

; Source: L1::evict_unchanged
; Dest: L1::evict_first
define void @test_memcpy_different_l1_policies(ptr addrspace(1) %dest, ptr addrspace(1) %src) {
; CHECK-LABEL: test_memcpy_different_l1_policies(
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs1, [%rd2+3];
; CHECK:    st.global.L1::evict_first.b8 [%rd1+3], %rs1;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs2, [%rd2+2];
; CHECK:    st.global.L1::evict_first.b8 [%rd1+2], %rs2;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs3, [%rd2+1];
; CHECK:    st.global.L1::evict_first.b8 [%rd1+1], %rs3;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs4, [%rd2];
; CHECK:    st.global.L1::evict_first.b8 [%rd1], %rs4;
  call void @llvm.memcpy.p1.p1.i64(ptr addrspace(1) %dest, ptr addrspace(1) %src, i64 4, i1 false), !mem.cache_hint !94
  ret void
}

; Source: L1::no_allocate
; Dest: L1::evict_unchanged
define void @test_memcpy_no_allocate_vs_unchanged(ptr addrspace(1) %dest, ptr addrspace(1) %src) {
; CHECK-LABEL: test_memcpy_no_allocate_vs_unchanged(
; CHECK:    ld.global.L1::no_allocate.b8 %rs1, [%rd2+3];
; CHECK:    st.global.L1::evict_unchanged.b8 [%rd1+3], %rs1;
; CHECK:    ld.global.L1::no_allocate.b8 %rs2, [%rd2+2];
; CHECK:    st.global.L1::evict_unchanged.b8 [%rd1+2], %rs2;
; CHECK:    ld.global.L1::no_allocate.b8 %rs3, [%rd2+1];
; CHECK:    st.global.L1::evict_unchanged.b8 [%rd1+1], %rs3;
; CHECK:    ld.global.L1::no_allocate.b8 %rs4, [%rd2];
; CHECK:    st.global.L1::evict_unchanged.b8 [%rd1], %rs4;
  call void @llvm.memcpy.p1.p1.i64(ptr addrspace(1) %dest, ptr addrspace(1) %src, i64 4, i1 false), !mem.cache_hint !95
  ret void
}

;-----------------------------------------------------------------------------
; All hints maxed out on both operands
;-----------------------------------------------------------------------------

; Source: L1::evict_first + L2::evict_first + L2::256B + L2::cache_hint
; Dest: L1::evict_last + L2::evict_last + L2::128B + L2::cache_hint
define void @test_memcpy_all_hints_both(ptr addrspace(1) %dest, ptr addrspace(1) %src) {
; CHECK-LABEL: test_memcpy_all_hints_both(
; CHECK:    mov.b64 %rd2, 12345;
; CHECK:    ld.global.L1::evict_first.L2::evict_first.L2::cache_hint.L2::256B.b8 %rs1, [%rd3+3], %rd2;
; CHECK:    st.global.L1::evict_last.L2::evict_last.L2::cache_hint.L2::128B.b8 [%rd1+3], %rs1, %rd2;
; CHECK:    ld.global.L1::evict_first.L2::evict_first.L2::cache_hint.L2::256B.b8 %rs2, [%rd3+2], %rd2;
; CHECK:    st.global.L1::evict_last.L2::evict_last.L2::cache_hint.L2::128B.b8 [%rd1+2], %rs2, %rd2;
; CHECK:    ld.global.L1::evict_first.L2::evict_first.L2::cache_hint.L2::256B.b8 %rs3, [%rd3+1], %rd2;
; CHECK:    st.global.L1::evict_last.L2::evict_last.L2::cache_hint.L2::128B.b8 [%rd1+1], %rs3, %rd2;
; CHECK:    ld.global.L1::evict_first.L2::evict_first.L2::cache_hint.L2::256B.b8 %rs4, [%rd3], %rd2;
; CHECK:    st.global.L1::evict_last.L2::evict_last.L2::cache_hint.L2::128B.b8 [%rd1], %rs4, %rd2;
  call void @llvm.memcpy.p1.p1.i64(ptr addrspace(1) %dest, ptr addrspace(1) %src, i64 4, i1 false), !mem.cache_hint !96
  ret void
}

;-----------------------------------------------------------------------------
; TODO: Preserve cache hints on llvm.masked.load.
; Masked load pointer operand is operand 0. SelectionDAGBuilder::visitMaskedLoad
; does not currently thread !mem.cache_hint into the MachineMemOperand, so the
; generated loads are plain today.
;-----------------------------------------------------------------------------

; TODO: This should eventually lower to ld.global.L1::evict_first.b32.
define <2 x i16> @test_masked_load_l1_hint_v2i16(ptr addrspace(1) %p) {
; CHECK-LABEL: test_masked_load_l1_hint_v2i16(
; CHECK:    ld.global.b32 %r1, [%rd1];
  %v = call <2 x i16> @llvm.masked.load.v2i16.p1(ptr addrspace(1) align 4 %p, <2 x i1> <i1 true, i1 false>, <2 x i16> poison), !mem.cache_hint !101
  ret <2 x i16> %v
}

; TODO: This should eventually lower to ld.global.L2::cache_hint.v4.b32.
define <4 x i32> @test_masked_load_l2_cache_policy_v4i32(ptr addrspace(1) %p) {
; CHECK-LABEL: test_masked_load_l2_cache_policy_v4i32(
; CHECK:    ld.global.v4.b32 {%r1, %r2, %r3, %r4}, [%rd1];
  %v = call <4 x i32> @llvm.masked.load.v4i32.p1(ptr addrspace(1) align 16 %p, <4 x i1> <i1 true, i1 false, i1 true, i1 true>, <4 x i32> poison), !mem.cache_hint !102
  ret <4 x i32> %v
}

;-----------------------------------------------------------------------------
; Large memcpy tests - verify hints propagate to all expanded load/stores
; LLVM expands memcpy to multiple load/store pairs. Each pair should
; get the appropriate cache hints from the original memcpy metadata.
; The expansion may use various sizes (b8, b16, b32, v2, v4, etc.)
;-----------------------------------------------------------------------------

; 16-byte memcpy: verify hints are applied to expanded loads/stores
define void @test_memcpy_16bytes(ptr addrspace(1) %dest, ptr addrspace(1) %src) {
; CHECK-LABEL: test_memcpy_16bytes(
; CHECK:    ld.global.L1::evict_first.b8 %rs1, [%rd2+15];
; CHECK:    st.global.L1::evict_last.b8 [%rd1+15], %rs1;
; CHECK:    ld.global.L1::evict_first.b8 %rs2, [%rd2+14];
; CHECK:    st.global.L1::evict_last.b8 [%rd1+14], %rs2;
; CHECK:    ld.global.L1::evict_first.b8 %rs3, [%rd2+13];
; CHECK:    st.global.L1::evict_last.b8 [%rd1+13], %rs3;
; CHECK:    ld.global.L1::evict_first.b8 %rs4, [%rd2+12];
; CHECK:    st.global.L1::evict_last.b8 [%rd1+12], %rs4;
; CHECK:    ld.global.L1::evict_first.b8 %rs5, [%rd2+11];
; CHECK:    st.global.L1::evict_last.b8 [%rd1+11], %rs5;
; CHECK:    ld.global.L1::evict_first.b8 %rs6, [%rd2+10];
; CHECK:    st.global.L1::evict_last.b8 [%rd1+10], %rs6;
; CHECK:    ld.global.L1::evict_first.b8 %rs7, [%rd2+9];
; CHECK:    st.global.L1::evict_last.b8 [%rd1+9], %rs7;
; CHECK:    ld.global.L1::evict_first.b8 %rs8, [%rd2+8];
; CHECK:    st.global.L1::evict_last.b8 [%rd1+8], %rs8;
; CHECK:    ld.global.L1::evict_first.b8 %rs9, [%rd2+7];
; CHECK:    st.global.L1::evict_last.b8 [%rd1+7], %rs9;
; CHECK:    ld.global.L1::evict_first.b8 %rs10, [%rd2+6];
; CHECK:    st.global.L1::evict_last.b8 [%rd1+6], %rs10;
; CHECK:    ld.global.L1::evict_first.b8 %rs11, [%rd2+5];
; CHECK:    st.global.L1::evict_last.b8 [%rd1+5], %rs11;
; CHECK:    ld.global.L1::evict_first.b8 %rs12, [%rd2+4];
; CHECK:    st.global.L1::evict_last.b8 [%rd1+4], %rs12;
; CHECK:    ld.global.L1::evict_first.b8 %rs13, [%rd2+3];
; CHECK:    st.global.L1::evict_last.b8 [%rd1+3], %rs13;
; CHECK:    ld.global.L1::evict_first.b8 %rs14, [%rd2+2];
; CHECK:    st.global.L1::evict_last.b8 [%rd1+2], %rs14;
; CHECK:    ld.global.L1::evict_first.b8 %rs15, [%rd2+1];
; CHECK:    st.global.L1::evict_last.b8 [%rd1+1], %rs15;
; CHECK:    ld.global.L1::evict_first.b8 %rs16, [%rd2];
; CHECK:    st.global.L1::evict_last.b8 [%rd1], %rs16;
  call void @llvm.memcpy.p1.p1.i64(ptr addrspace(1) %dest, ptr addrspace(1) %src, i64 16, i1 false), !mem.cache_hint !97
  ret void
}

; 32-byte memcpy: all loads should have L1::evict_unchanged, all stores L2::evict_first
define void @test_memcpy_32bytes(ptr addrspace(1) %dest, ptr addrspace(1) %src) {
; CHECK-LABEL: test_memcpy_32bytes(
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs1, [%rd2+31];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+31], %rs1;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs2, [%rd2+30];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+30], %rs2;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs3, [%rd2+29];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+29], %rs3;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs4, [%rd2+28];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+28], %rs4;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs5, [%rd2+27];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+27], %rs5;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs6, [%rd2+26];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+26], %rs6;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs7, [%rd2+25];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+25], %rs7;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs8, [%rd2+24];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+24], %rs8;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs9, [%rd2+23];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+23], %rs9;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs10, [%rd2+22];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+22], %rs10;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs11, [%rd2+21];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+21], %rs11;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs12, [%rd2+20];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+20], %rs12;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs13, [%rd2+19];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+19], %rs13;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs14, [%rd2+18];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+18], %rs14;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs15, [%rd2+17];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+17], %rs15;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs16, [%rd2+16];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+16], %rs16;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs17, [%rd2+15];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+15], %rs17;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs18, [%rd2+14];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+14], %rs18;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs19, [%rd2+13];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+13], %rs19;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs20, [%rd2+12];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+12], %rs20;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs21, [%rd2+11];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+11], %rs21;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs22, [%rd2+10];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+10], %rs22;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs23, [%rd2+9];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+9], %rs23;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs24, [%rd2+8];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+8], %rs24;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs25, [%rd2+7];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+7], %rs25;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs26, [%rd2+6];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+6], %rs26;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs27, [%rd2+5];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+5], %rs27;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs28, [%rd2+4];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+4], %rs28;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs29, [%rd2+3];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+3], %rs29;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs30, [%rd2+2];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+2], %rs30;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs31, [%rd2+1];
; CHECK:    st.global.L2::evict_first.b8 [%rd1+1], %rs31;
; CHECK:    ld.global.L1::evict_unchanged.b8 %rs32, [%rd2];
; CHECK:    st.global.L2::evict_first.b8 [%rd1], %rs32;
  call void @llvm.memcpy.p1.p1.i64(ptr addrspace(1) %dest, ptr addrspace(1) %src, i64 32, i1 false), !mem.cache_hint !98
  ret void
}

; 128-byte memcpy with combined hints
; Note: Large memcpy (>64 bytes) is expanded to a loop in the backend.
; Cache hints are not preserved for loop-based expansion.
; This test verifies the code compiles correctly.
define void @test_memcpy_128bytes_combined(ptr addrspace(1) %dest, ptr addrspace(1) %src) {
; CHECK-LABEL: test_memcpy_128bytes_combined(
; CHECK:    mov.b64 %rd5, 0;
; CHECK:    ld.global.b8 %rs1, [%rd3];
; CHECK:    st.global.b8 [%rd4], %rs1;
  call void @llvm.memcpy.p1.p1.i64(ptr addrspace(1) %dest, ptr addrspace(1) %src, i64 128, i1 false), !mem.cache_hint !100
  ret void
}

;-----------------------------------------------------------------------------
; Metadata definitions
;-----------------------------------------------------------------------------

; memcpy with both dest and src hints
!80 = !{i32 0, !180, i32 1, !181}
; operand 0 (dest/store): L1::evict_last, L2::evict_last
!180 = !{!"nvvm.l1_eviction", !"last", !"nvvm.l2_eviction", !"last"}
; operand 1 (src/load): L1::evict_first, L2::evict_first, L2::128B prefetch
!181 = !{!"nvvm.l1_eviction", !"first", !"nvvm.l2_eviction", !"first", !"nvvm.l2_prefetch_size", !"128B"}

; memcpy with only source hint (load side)
!81 = !{i32 1, !182}
!182 = !{!"nvvm.l1_eviction", !"first"}

; memcpy with only dest hint (store side)
!82 = !{i32 0, !183}
!183 = !{!"nvvm.l2_eviction", !"last"}

; memcpy with L2::cache_hint on both operands
!83 = !{i32 0, !184, i32 1, !185}
!184 = !{!"nvvm.l2_cache_hint", i64 12345}
!185 = !{!"nvvm.l2_cache_hint", i64 12345}

; Combined L1 + L2 eviction on source only
!84 = !{i32 1, !186}
!186 = !{!"nvvm.l1_eviction", !"first", !"nvvm.l2_eviction", !"last"}

; Combined L1 + L2 eviction on dest only
!85 = !{i32 0, !187}
!187 = !{!"nvvm.l1_eviction", !"unchanged", !"nvvm.l2_eviction", !"first"}

; L1 + prefetch on source, L1 on dest
!86 = !{i32 0, !189, i32 1, !188}
!188 = !{!"nvvm.l1_eviction", !"last", !"nvvm.l2_prefetch_size", !"256B"}
!189 = !{!"nvvm.l1_eviction", !"no_allocate"}

; Prefetch on source, L2 eviction on dest
!87 = !{i32 0, !191, i32 1, !190}
!190 = !{!"nvvm.l2_prefetch_size", !"64B"}
!191 = !{!"nvvm.l2_eviction", !"last"}

; L2::cache_hint + L1 eviction on source only
!88 = !{i32 1, !192}
!192 = !{!"nvvm.l2_cache_hint", i64 12345, !"nvvm.l1_eviction", !"first"}

; L2::cache_hint + L1 + L2 eviction on dest only
!89 = !{i32 0, !193}
!193 = !{!"nvvm.l2_cache_hint", i64 12345, !"nvvm.l1_eviction", !"last", !"nvvm.l2_eviction", !"first"}

; Both operands: L2::cache_hint + L1 + L2 eviction
!90 = !{i32 0, !195, i32 1, !194}
!194 = !{!"nvvm.l2_cache_hint", i64 12345, !"nvvm.l1_eviction", !"unchanged", !"nvvm.l2_eviction", !"last"}
!195 = !{!"nvvm.l2_cache_hint", i64 12345, !"nvvm.l1_eviction", !"first", !"nvvm.l2_eviction", !"first"}

; L2::cache_hint + prefetch on source, L2::cache_hint + L1 on dest
!91 = !{i32 0, !197, i32 1, !196}
!196 = !{!"nvvm.l2_cache_hint", i64 12345, !"nvvm.l2_prefetch_size", !"128B"}
!197 = !{!"nvvm.l2_cache_hint", i64 12345, !"nvvm.l1_eviction", !"last"}

; Complex source (all non-cache_hint), simple dest
!92 = !{i32 0, !199, i32 1, !198}
!198 = !{!"nvvm.l1_eviction", !"first", !"nvvm.l2_eviction", !"last", !"nvvm.l2_prefetch_size", !"64B"}
!199 = !{!"nvvm.l1_eviction", !"last"}

; Simple source, complex dest (with cache_hint)
!93 = !{i32 0, !201, i32 1, !200}
!200 = !{!"nvvm.l2_prefetch_size", !"256B"}
!201 = !{!"nvvm.l2_cache_hint", i64 12345, !"nvvm.l1_eviction", !"no_allocate", !"nvvm.l2_eviction", !"last"}

; Different L1 policies: unchanged vs first
!94 = !{i32 0, !203, i32 1, !202}
!202 = !{!"nvvm.l1_eviction", !"unchanged"}
!203 = !{!"nvvm.l1_eviction", !"first"}

; Different L1 policies: no_allocate vs unchanged
!95 = !{i32 0, !205, i32 1, !204}
!204 = !{!"nvvm.l1_eviction", !"no_allocate"}
!205 = !{!"nvvm.l1_eviction", !"unchanged"}

; All hints maxed out on both operands
!96 = !{i32 0, !207, i32 1, !206}
!206 = !{!"nvvm.l2_cache_hint", i64 12345, !"nvvm.l1_eviction", !"first", !"nvvm.l2_eviction", !"first", !"nvvm.l2_prefetch_size", !"256B"}
!207 = !{!"nvvm.l2_cache_hint", i64 12345, !"nvvm.l1_eviction", !"last", !"nvvm.l2_eviction", !"last", !"nvvm.l2_prefetch_size", !"128B"}

; Large memcpy metadata
!97 = !{i32 0, !209, i32 1, !208}
!208 = !{!"nvvm.l1_eviction", !"first"}
!209 = !{!"nvvm.l1_eviction", !"last"}

!98 = !{i32 0, !211, i32 1, !210}
!210 = !{!"nvvm.l1_eviction", !"unchanged"}
!211 = !{!"nvvm.l2_eviction", !"first"}

!99 = !{i32 0, !213, i32 1, !212}
!212 = !{!"nvvm.l2_cache_hint", i64 12345}
!213 = !{!"nvvm.l2_cache_hint", i64 12345}

!100 = !{i32 0, !215, i32 1, !214}
!214 = !{!"nvvm.l1_eviction", !"first", !"nvvm.l2_eviction", !"last", !"nvvm.l2_prefetch_size", !"256B"}
!215 = !{!"nvvm.l1_eviction", !"last", !"nvvm.l2_eviction", !"first"}

; Masked load metadata
!101 = !{i32 0, !216}
!216 = !{!"nvvm.l1_eviction", !"first"}

!102 = !{i32 0, !217}
!217 = !{!"nvvm.l2_cache_hint", i64 12345}
