; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --filter "^\s*(?:mov\.b64|ld(?:\.[A-Za-z0-9_:]+)*\.global|st(?:\.[A-Za-z0-9_:]+)*\.global|atom(?:\.[A-Za-z0-9_:]+)*\.global)" --version 6
; RUN: llc < %s -mtriple=nvptx64 -mcpu=sm_80 -mattr=+ptx74 | FileCheck %s
; RUN: %if ptxas %{ llc < %s -mtriple=nvptx64 -mcpu=sm_80 -mattr=+ptx74 | %ptxas-verify %}

; Test !mem.cache_hint metadata lowering to PTX load/store cache qualifiers.

;-----------------------------------------------------------------------------
; Basic L1 eviction policies for loads
;-----------------------------------------------------------------------------

define i32 @test_load_l1_first(ptr addrspace(1) %p) {
; CHECK-LABEL: test_load_l1_first(
; CHECK:    ld.global.L1::evict_first.b32 %r1, [%rd1];
  %v = load i32, ptr addrspace(1) %p, !mem.cache_hint !0
  ret i32 %v
}

define i32 @test_load_l1_last(ptr addrspace(1) %p) {
; CHECK-LABEL: test_load_l1_last(
; CHECK:    ld.global.L1::evict_last.b32 %r1, [%rd1];
  %v = load i32, ptr addrspace(1) %p, !mem.cache_hint !1
  ret i32 %v
}

define i32 @test_load_l1_unchanged(ptr addrspace(1) %p) {
; CHECK-LABEL: test_load_l1_unchanged(
; CHECK:    ld.global.L1::evict_unchanged.b32 %r1, [%rd1];
  %v = load i32, ptr addrspace(1) %p, !mem.cache_hint !2
  ret i32 %v
}

define i32 @test_load_l1_no_allocate(ptr addrspace(1) %p) {
; CHECK-LABEL: test_load_l1_no_allocate(
; CHECK:    ld.global.L1::no_allocate.b32 %r1, [%rd1];
  %v = load i32, ptr addrspace(1) %p, !mem.cache_hint !3
  ret i32 %v
}

;-----------------------------------------------------------------------------
; Basic L2 eviction policies for loads
;-----------------------------------------------------------------------------

define i32 @test_load_l2_first(ptr addrspace(1) %p) {
; CHECK-LABEL: test_load_l2_first(
; CHECK:    ld.global.L2::evict_first.b32 %r1, [%rd1];
  %v = load i32, ptr addrspace(1) %p, !mem.cache_hint !4
  ret i32 %v
}

define i32 @test_load_l2_last(ptr addrspace(1) %p) {
; CHECK-LABEL: test_load_l2_last(
; CHECK:    ld.global.L2::evict_last.b32 %r1, [%rd1];
  %v = load i32, ptr addrspace(1) %p, !mem.cache_hint !5
  ret i32 %v
}

;-----------------------------------------------------------------------------
; L2 prefetch sizes for loads
;-----------------------------------------------------------------------------

define i32 @test_load_prefetch_64(ptr addrspace(1) %p) {
; CHECK-LABEL: test_load_prefetch_64(
; CHECK:    ld.global.L2::64B.b32 %r1, [%rd1];
  %v = load i32, ptr addrspace(1) %p, !mem.cache_hint !6
  ret i32 %v
}

define i32 @test_load_prefetch_128(ptr addrspace(1) %p) {
; CHECK-LABEL: test_load_prefetch_128(
; CHECK:    ld.global.L2::128B.b32 %r1, [%rd1];
  %v = load i32, ptr addrspace(1) %p, !mem.cache_hint !7
  ret i32 %v
}

define i32 @test_load_prefetch_256(ptr addrspace(1) %p) {
; CHECK-LABEL: test_load_prefetch_256(
; CHECK:    ld.global.L2::256B.b32 %r1, [%rd1];
  %v = load i32, ptr addrspace(1) %p, !mem.cache_hint !8
  ret i32 %v
}

;-----------------------------------------------------------------------------
; All L1 + L2 combinations for loads
;-----------------------------------------------------------------------------

define i32 @test_load_l1_first_l2_first(ptr addrspace(1) %p) {
; CHECK-LABEL: test_load_l1_first_l2_first(
; CHECK:    ld.global.L1::evict_first.L2::evict_first.b32 %r1, [%rd1];
  %v = load i32, ptr addrspace(1) %p, !mem.cache_hint !9
  ret i32 %v
}

define i32 @test_load_l1_first_l2_last(ptr addrspace(1) %p) {
; CHECK-LABEL: test_load_l1_first_l2_last(
; CHECK:    ld.global.L1::evict_first.L2::evict_last.b32 %r1, [%rd1];
  %v = load i32, ptr addrspace(1) %p, !mem.cache_hint !10
  ret i32 %v
}

define i32 @test_load_l1_last_l2_first(ptr addrspace(1) %p) {
; CHECK-LABEL: test_load_l1_last_l2_first(
; CHECK:    ld.global.L1::evict_last.L2::evict_first.b32 %r1, [%rd1];
  %v = load i32, ptr addrspace(1) %p, !mem.cache_hint !11
  ret i32 %v
}

define i32 @test_load_l1_last_l2_last(ptr addrspace(1) %p) {
; CHECK-LABEL: test_load_l1_last_l2_last(
; CHECK:    ld.global.L1::evict_last.L2::evict_last.b32 %r1, [%rd1];
  %v = load i32, ptr addrspace(1) %p, !mem.cache_hint !12
  ret i32 %v
}

;-----------------------------------------------------------------------------
; L1 + L2 + Prefetch combination for loads
;-----------------------------------------------------------------------------

define i32 @test_load_l1_first_l2_last_prefetch_128(ptr addrspace(1) %p) {
; CHECK-LABEL: test_load_l1_first_l2_last_prefetch_128(
; CHECK:    ld.global.L1::evict_first.L2::evict_last.L2::128B.b32 %r1, [%rd1];
  %v = load i32, ptr addrspace(1) %p, !mem.cache_hint !13
  ret i32 %v
}

;-----------------------------------------------------------------------------
; Basic L1 eviction policies for stores
;-----------------------------------------------------------------------------

define void @test_store_l1_first(ptr addrspace(1) %p, i32 %v) {
; CHECK-LABEL: test_store_l1_first(
; CHECK:    st.global.L1::evict_first.b32 [%rd1], %r1;
  store i32 %v, ptr addrspace(1) %p, !mem.cache_hint !14
  ret void
}

define void @test_store_l1_last(ptr addrspace(1) %p, i32 %v) {
; CHECK-LABEL: test_store_l1_last(
; CHECK:    st.global.L1::evict_last.b32 [%rd1], %r1;
  store i32 %v, ptr addrspace(1) %p, !mem.cache_hint !15
  ret void
}

define void @test_store_l1_unchanged(ptr addrspace(1) %p, i32 %v) {
; CHECK-LABEL: test_store_l1_unchanged(
; CHECK:    st.global.L1::evict_unchanged.b32 [%rd1], %r1;
  store i32 %v, ptr addrspace(1) %p, !mem.cache_hint !16
  ret void
}

define void @test_store_l1_no_allocate(ptr addrspace(1) %p, i32 %v) {
; CHECK-LABEL: test_store_l1_no_allocate(
; CHECK:    st.global.L1::no_allocate.b32 [%rd1], %r1;
  store i32 %v, ptr addrspace(1) %p, !mem.cache_hint !17
  ret void
}

;-----------------------------------------------------------------------------
; Basic L2 eviction policies for stores
;-----------------------------------------------------------------------------

define void @test_store_l2_first(ptr addrspace(1) %p, i32 %v) {
; CHECK-LABEL: test_store_l2_first(
; CHECK:    st.global.L2::evict_first.b32 [%rd1], %r1;
  store i32 %v, ptr addrspace(1) %p, !mem.cache_hint !18
  ret void
}

define void @test_store_l2_last(ptr addrspace(1) %p, i32 %v) {
; CHECK-LABEL: test_store_l2_last(
; CHECK:    st.global.L2::evict_last.b32 [%rd1], %r1;
  store i32 %v, ptr addrspace(1) %p, !mem.cache_hint !19
  ret void
}

;-----------------------------------------------------------------------------
; All L1 + L2 combinations for stores
;-----------------------------------------------------------------------------

define void @test_store_l1_first_l2_first(ptr addrspace(1) %p, i32 %v) {
; CHECK-LABEL: test_store_l1_first_l2_first(
; CHECK:    st.global.L1::evict_first.L2::evict_first.b32 [%rd1], %r1;
  store i32 %v, ptr addrspace(1) %p, !mem.cache_hint !20
  ret void
}

define void @test_store_l1_first_l2_last(ptr addrspace(1) %p, i32 %v) {
; CHECK-LABEL: test_store_l1_first_l2_last(
; CHECK:    st.global.L1::evict_first.L2::evict_last.b32 [%rd1], %r1;
  store i32 %v, ptr addrspace(1) %p, !mem.cache_hint !21
  ret void
}

define void @test_store_l1_last_l2_first(ptr addrspace(1) %p, i32 %v) {
; CHECK-LABEL: test_store_l1_last_l2_first(
; CHECK:    st.global.L1::evict_last.L2::evict_first.b32 [%rd1], %r1;
  store i32 %v, ptr addrspace(1) %p, !mem.cache_hint !22
  ret void
}

define void @test_store_l1_last_l2_last(ptr addrspace(1) %p, i32 %v) {
; CHECK-LABEL: test_store_l1_last_l2_last(
; CHECK:    st.global.L1::evict_last.L2::evict_last.b32 [%rd1], %r1;
  store i32 %v, ptr addrspace(1) %p, !mem.cache_hint !23
  ret void
}

;-----------------------------------------------------------------------------
; Different data types - loads
;-----------------------------------------------------------------------------

define i16 @test_load_i16_l1_first(ptr addrspace(1) %p) {
; CHECK-LABEL: test_load_i16_l1_first(
; CHECK:    ld.global.L1::evict_first.b16 %r1, [%rd1];
  %v = load i16, ptr addrspace(1) %p, !mem.cache_hint !0
  ret i16 %v
}

define i64 @test_load_i64_l1_last(ptr addrspace(1) %p) {
; CHECK-LABEL: test_load_i64_l1_last(
; CHECK:    ld.global.L1::evict_last.b64 %rd2, [%rd1];
  %v = load i64, ptr addrspace(1) %p, !mem.cache_hint !1
  ret i64 %v
}

define float @test_load_f32_l2_first(ptr addrspace(1) %p) {
; CHECK-LABEL: test_load_f32_l2_first(
; CHECK:    ld.global.L2::evict_first.b32 %r1, [%rd1];
  %v = load float, ptr addrspace(1) %p, !mem.cache_hint !4
  ret float %v
}

define double @test_load_f64_l2_last(ptr addrspace(1) %p) {
; CHECK-LABEL: test_load_f64_l2_last(
; CHECK:    ld.global.L2::evict_last.b64 %rd2, [%rd1];
  %v = load double, ptr addrspace(1) %p, !mem.cache_hint !5
  ret double %v
}

;-----------------------------------------------------------------------------
; Different data types - stores
;-----------------------------------------------------------------------------

define void @test_store_i16_l1_first(ptr addrspace(1) %p, i16 %v) {
; CHECK-LABEL: test_store_i16_l1_first(
; CHECK:    st.global.L1::evict_first.b16 [%rd1], %rs1;
  store i16 %v, ptr addrspace(1) %p, !mem.cache_hint !14
  ret void
}

define void @test_store_i64_l2_last(ptr addrspace(1) %p, i64 %v) {
; CHECK-LABEL: test_store_i64_l2_last(
; CHECK:    st.global.L2::evict_last.b64 [%rd1], %rd2;
  store i64 %v, ptr addrspace(1) %p, !mem.cache_hint !19
  ret void
}

define void @test_store_f32_l1_no_allocate(ptr addrspace(1) %p, float %v) {
; CHECK-LABEL: test_store_f32_l1_no_allocate(
; CHECK:    st.global.L1::no_allocate.b32 [%rd1], %r1;
  store float %v, ptr addrspace(1) %p, !mem.cache_hint !17
  ret void
}

;-----------------------------------------------------------------------------
; Vector loads with cache hints
;-----------------------------------------------------------------------------

define <2 x i32> @test_load_v2i32_l1_first(ptr addrspace(1) %p) {
; CHECK-LABEL: test_load_v2i32_l1_first(
; CHECK:    ld.global.L1::evict_first.v2.b32 {%r1, %r2}, [%rd1];
  %v = load <2 x i32>, ptr addrspace(1) %p, !mem.cache_hint !0
  ret <2 x i32> %v
}

define <4 x i32> @test_load_v4i32_l2_last(ptr addrspace(1) %p) {
; CHECK-LABEL: test_load_v4i32_l2_last(
; CHECK:    ld.global.L2::evict_last.v4.b32 {%r1, %r2, %r3, %r4}, [%rd1];
  %v = load <4 x i32>, ptr addrspace(1) %p, !mem.cache_hint !5
  ret <4 x i32> %v
}

define <2 x float> @test_load_v2f32_l1_unchanged(ptr addrspace(1) %p) {
; CHECK-LABEL: test_load_v2f32_l1_unchanged(
; CHECK:    ld.global.L1::evict_unchanged.v2.b32 {%r1, %r2}, [%rd1];
  %v = load <2 x float>, ptr addrspace(1) %p, !mem.cache_hint !2
  ret <2 x float> %v
}

define <2 x double> @test_load_v2f64_prefetch_128(ptr addrspace(1) %p) {
; CHECK-LABEL: test_load_v2f64_prefetch_128(
; CHECK:    ld.global.L2::128B.v2.b64 {%rd2, %rd3}, [%rd1];
  %v = load <2 x double>, ptr addrspace(1) %p, !mem.cache_hint !7
  ret <2 x double> %v
}

;-----------------------------------------------------------------------------
; Vector stores with cache hints
;-----------------------------------------------------------------------------

define void @test_store_v2i32_l1_last(ptr addrspace(1) %p, <2 x i32> %v) {
; CHECK-LABEL: test_store_v2i32_l1_last(
; CHECK:    st.global.L1::evict_last.v2.b32 [%rd1], {%r1, %r2};
  store <2 x i32> %v, ptr addrspace(1) %p, !mem.cache_hint !15
  ret void
}

define void @test_store_v4i32_l2_first(ptr addrspace(1) %p, <4 x i32> %v) {
; CHECK-LABEL: test_store_v4i32_l2_first(
; CHECK:    st.global.L2::evict_first.v4.b32 [%rd1], {%r1, %r2, %r3, %r4};
  store <4 x i32> %v, ptr addrspace(1) %p, !mem.cache_hint !18
  ret void
}

define void @test_store_v2f64_l1_no_allocate(ptr addrspace(1) %p, <2 x double> %v) {
; CHECK-LABEL: test_store_v2f64_l1_no_allocate(
; CHECK:    st.global.L1::no_allocate.v2.b64 [%rd1], {%rd2, %rd3};
  store <2 x double> %v, ptr addrspace(1) %p, !mem.cache_hint !17
  ret void
}

;-----------------------------------------------------------------------------
; Invariant loads with cache hints may still use LDG (ld.global.nc)
;-----------------------------------------------------------------------------

define i32 @test_invariant_load_with_hint(ptr addrspace(1) %p) {
; CHECK-LABEL: test_invariant_load_with_hint(
; CHECK:    ld.global.nc.L1::evict_first.b32 %r1, [%rd1];
  %v = load i32, ptr addrspace(1) %p, !invariant.load !{}, !mem.cache_hint !0
  ret i32 %v
}

define i32 @test_invariant_load_with_cache_policy(ptr addrspace(1) %p) {
; CHECK-LABEL: test_invariant_load_with_cache_policy(
; CHECK:    mov.b64 %rd2, 12345;
; CHECK:    ld.global.nc.L2::cache_hint.b32 %r1, [%rd1], %rd2;
  %v = load i32, ptr addrspace(1) %p, !invariant.load !{}, !mem.cache_hint !24
  ret i32 %v
}

define <2 x i32> @test_invariant_load_v2i32_with_hint(ptr addrspace(1) %p) {
; CHECK-LABEL: test_invariant_load_v2i32_with_hint(
; CHECK:    ld.global.nc.L1::evict_last.L2::evict_first.v2.b32 {%r1, %r2}, [%rd1];
  %v = load <2 x i32>, ptr addrspace(1) %p, !invariant.load !{}, !mem.cache_hint !11
  ret <2 x i32> %v
}

;-----------------------------------------------------------------------------
; No hint should produce plain load/store
;-----------------------------------------------------------------------------

define i32 @test_load_no_hint(ptr addrspace(1) %p) {
; CHECK-LABEL: test_load_no_hint(
; CHECK:    ld.global.b32 %r1, [%rd1];
  %v = load i32, ptr addrspace(1) %p
  ret i32 %v
}

define void @test_store_no_hint(ptr addrspace(1) %p, i32 %v) {
; CHECK-LABEL: test_store_no_hint(
; CHECK:    st.global.b32 [%rd1], %r1;
  store i32 %v, ptr addrspace(1) %p
  ret void
}

;-----------------------------------------------------------------------------
; Metadata definitions
;-----------------------------------------------------------------------------

!0 = !{i32 0, !25}
!25 = !{!"nvvm.l1_eviction", !"first"}
!1 = !{i32 0, !26}
!26 = !{!"nvvm.l1_eviction", !"last"}
!2 = !{i32 0, !27}
!27 = !{!"nvvm.l1_eviction", !"unchanged"}
!3 = !{i32 0, !28}
!28 = !{!"nvvm.l1_eviction", !"no_allocate"}
!4 = !{i32 0, !29}
!29 = !{!"nvvm.l2_eviction", !"first"}
!5 = !{i32 0, !30}
!30 = !{!"nvvm.l2_eviction", !"last"}
!6 = !{i32 0, !31}
!31 = !{!"nvvm.l2_prefetch_size", !"64B"}
!7 = !{i32 0, !32}
!32 = !{!"nvvm.l2_prefetch_size", !"128B"}
!8 = !{i32 0, !33}
!33 = !{!"nvvm.l2_prefetch_size", !"256B"}
!9 = !{i32 0, !34}
!34 = !{!"nvvm.l1_eviction", !"first", !"nvvm.l2_eviction", !"first"}
!10 = !{i32 0, !35}
!35 = !{!"nvvm.l1_eviction", !"first", !"nvvm.l2_eviction", !"last"}
!11 = !{i32 0, !36}
!36 = !{!"nvvm.l1_eviction", !"last", !"nvvm.l2_eviction", !"first"}
!12 = !{i32 0, !37}
!37 = !{!"nvvm.l1_eviction", !"last", !"nvvm.l2_eviction", !"last"}
!13 = !{i32 0, !38}
!38 = !{!"nvvm.l1_eviction", !"first", !"nvvm.l2_eviction", !"last", !"nvvm.l2_prefetch_size", !"128B"}
!14 = !{i32 1, !25}
!15 = !{i32 1, !26}
!16 = !{i32 1, !27}
!17 = !{i32 1, !28}
!18 = !{i32 1, !29}
!19 = !{i32 1, !30}
!20 = !{i32 1, !34}
!21 = !{i32 1, !35}
!22 = !{i32 1, !36}
!23 = !{i32 1, !37}
!24 = !{i32 0, !39}
!39 = !{!"nvvm.l2_cache_hint", i64 12345}
