; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=nvptx64 -mcpu=sm_80 | FileCheck -check-prefixes=CHECK80 %s
; RUN: llc < %s -mtriple=nvptx64 -mcpu=sm_90 | FileCheck -check-prefixes=CHECK90 %s
; RUN: %if ptxas-sm_90 %{ llc < %s -mtriple=nvptx64 -mcpu=sm_90 | %ptxas-verify -arch=sm_90 %}

define ptx_kernel void @kernel_func_clusterxyz() "nvvm.cluster_dim"="3,5,7" {
; CHECK80-LABEL: kernel_func_clusterxyz(
; CHECK80:       {
; CHECK80-EMPTY:
; CHECK80-EMPTY:
; CHECK80-NEXT:  // %bb.0:
; CHECK80-NEXT:    ret;
;
; CHECK90-LABEL: kernel_func_clusterxyz(
; CHECK90:       .explicitcluster
; CHECK90-NEXT:  .reqnctapercluster 3, 5, 7
; CHECK90-NEXT:  {
; CHECK90-EMPTY:
; CHECK90-EMPTY:
; CHECK90-NEXT:  // %bb.0:
; CHECK90-NEXT:    ret;
  ret void
}
