; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=nvptx64 -mcpu=sm_35 -verify-machineinstrs | FileCheck %s
; RUN: %if ptxas %{ llc < %s -mtriple=nvptx64 -mcpu=sm_35 | %ptxas-verify %}
target triple = "nvptx64-nvidia-cuda"

define float @fabs_free(i32 %in) {
; CHECK-LABEL: fabs_free(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .f32 %f<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.u32 %r1, [fabs_free_param_0];
; CHECK-NEXT:    and.b32 %r2, %r1, 2147483647;
; CHECK-NEXT:    mov.b32 %f1, %r2;
; CHECK-NEXT:    st.param.f32 [func_retval0], %f1;
; CHECK-NEXT:    ret;
  %b = bitcast i32 %in to float
  %f = call float @llvm.fabs.f32(float %b)
  ret float %f
}

define float @fneg_free(i32 %in) {
; CHECK-LABEL: fneg_free(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .f32 %f<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.u32 %r1, [fneg_free_param_0];
; CHECK-NEXT:    xor.b32 %r2, %r1, -2147483648;
; CHECK-NEXT:    mov.b32 %f1, %r2;
; CHECK-NEXT:    st.param.f32 [func_retval0], %f1;
; CHECK-NEXT:    ret;
  %b = bitcast i32 %in to float
  %f = fneg float %b
  ret float %f
}
