; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=nvptx64 -mcpu=sm_90 -mattr=+ptx86 | FileCheck --check-prefixes=CHECK %s
; RUN: %if ptxas-sm_90 && ptxas-isa-8.6 %{ llc < %s -mtriple=nvptx64 -mcpu=sm_90 -mattr=+ptx86 | %ptxas-verify -arch=sm_90 %}

define void @test_nvvm_fence_proxy_async_generic_acquire_sync_restrict() {
; CHECK-LABEL: test_nvvm_fence_proxy_async_generic_acquire_sync_restrict(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    fence.proxy.async::generic.acquire.sync_restrict::shared::cluster.cluster;
; CHECK-NEXT:    ret;
  call void @llvm.nvvm.fence.proxy.async_generic.acquire.sync_restrict.space.cluster.scope.cluster()
  ret void
}

define void @test_nvvm_fence_proxy_async_generic_release_sync_restrict() {
; CHECK-LABEL: test_nvvm_fence_proxy_async_generic_release_sync_restrict(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    fence.proxy.async::generic.release.sync_restrict::shared::cta.cluster;
; CHECK-NEXT:    ret;
  call void @llvm.nvvm.fence.proxy.async_generic.release.sync_restrict.space.cta.scope.cluster()
  ret void
}
