; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5

; RUN: llc < %s -march=nvptx64 -mcpu=sm_90 -mattr=+ptx87 | FileCheck %s --check-prefix=SM90
; RUN: %if ptxas %{ llc < %s -march=nvptx -mcpu=sm_90 -mattr=+ptx87 | %ptxas-verify %}


define void @fence_acquire_sys() {
; SM90-LABEL: fence_acquire_sys(
; SM90:       {
; SM90-EMPTY:
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    fence.acquire.sys;
; SM90-NEXT:    ret;
    fence syncscope("") acquire
    ret void
}


define void @fence_acquire_cta() {
; SM90-LABEL: fence_acquire_cta(
; SM90:       {
; SM90-EMPTY:
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    fence.acquire.cta;
; SM90-NEXT:    ret;
    fence syncscope("block") acquire
    ret void
}


define void @fence_acquire_cluster() {
; SM90-LABEL: fence_acquire_cluster(
; SM90:       {
; SM90-EMPTY:
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    fence.acquire.cluster;
; SM90-NEXT:    ret;
    fence syncscope("cluster") acquire
    ret void
}


define void @fence_acquire_gpu() {
; SM90-LABEL: fence_acquire_gpu(
; SM90:       {
; SM90-EMPTY:
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    fence.acquire.gpu;
; SM90-NEXT:    ret;
    fence syncscope("device") acquire
    ret void
}


define void @fence_release_sys() {
; SM90-LABEL: fence_release_sys(
; SM90:       {
; SM90-EMPTY:
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    fence.release.sys;
; SM90-NEXT:    ret;
    fence syncscope("") release
    ret void
}


define void @fence_release_cta() {
; SM90-LABEL: fence_release_cta(
; SM90:       {
; SM90-EMPTY:
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    fence.release.cta;
; SM90-NEXT:    ret;
    fence syncscope("block") release
    ret void
}


define void @fence_release_cluster() {
; SM90-LABEL: fence_release_cluster(
; SM90:       {
; SM90-EMPTY:
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    fence.release.cluster;
; SM90-NEXT:    ret;
    fence syncscope("cluster") release
    ret void
}


define void @fence_release_gpu() {
; SM90-LABEL: fence_release_gpu(
; SM90:       {
; SM90-EMPTY:
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    fence.release.gpu;
; SM90-NEXT:    ret;
    fence syncscope("device") release
    ret void
}


define void @fence_acq_rel_sys() {
; SM90-LABEL: fence_acq_rel_sys(
; SM90:       {
; SM90-EMPTY:
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    fence.acq_rel.sys;
; SM90-NEXT:    ret;
    fence syncscope("") acq_rel
    ret void
}


define void @fence_acq_rel_cta() {
; SM90-LABEL: fence_acq_rel_cta(
; SM90:       {
; SM90-EMPTY:
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    fence.acq_rel.cta;
; SM90-NEXT:    ret;
    fence syncscope("block") acq_rel
    ret void
}


define void @fence_acq_rel_cluster() {
; SM90-LABEL: fence_acq_rel_cluster(
; SM90:       {
; SM90-EMPTY:
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    fence.acq_rel.cluster;
; SM90-NEXT:    ret;
    fence syncscope("cluster") acq_rel
    ret void
}


define void @fence_acq_rel_gpu() {
; SM90-LABEL: fence_acq_rel_gpu(
; SM90:       {
; SM90-EMPTY:
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    fence.acq_rel.gpu;
; SM90-NEXT:    ret;
    fence syncscope("device") acq_rel
    ret void
}


define void @fence_seq_cst_sys() {
; SM90-LABEL: fence_seq_cst_sys(
; SM90:       {
; SM90-EMPTY:
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    fence.sc.sys;
; SM90-NEXT:    ret;
    fence syncscope("") seq_cst
    ret void
}


define void @fence_seq_cst_cta() {
; SM90-LABEL: fence_seq_cst_cta(
; SM90:       {
; SM90-EMPTY:
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    fence.sc.cta;
; SM90-NEXT:    ret;
    fence syncscope("block") seq_cst
    ret void
}


define void @fence_seq_cst_cluster() {
; SM90-LABEL: fence_seq_cst_cluster(
; SM90:       {
; SM90-EMPTY:
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    fence.sc.cluster;
; SM90-NEXT:    ret;
    fence syncscope("cluster") seq_cst
    ret void
}


define void @fence_seq_cst_gpu() {
; SM90-LABEL: fence_seq_cst_gpu(
; SM90:       {
; SM90-EMPTY:
; SM90-EMPTY:
; SM90-NEXT:  // %bb.0:
; SM90-NEXT:    fence.sc.gpu;
; SM90-NEXT:    ret;
    fence syncscope("device") seq_cst
    ret void
}

