; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=nvptx64 -mcpu=sm_90 -mattr=+ptx80 | FileCheck --check-prefixes=CHECK %s
; RUN: %if ptxas-sm_90 && ptxas-isa-8.0 %{ llc < %s -mtriple=nvptx64 -mcpu=sm_90 -mattr=+ptx80 | %ptxas-verify -arch=sm_90 %}

define void @test_nvvm_fence_proxy_async() {
; CHECK-LABEL: test_nvvm_fence_proxy_async(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    fence.proxy.async;
; CHECK-NEXT:    ret;
  call void @llvm.nvvm.fence.proxy.async()
  ret void
}

define void @test_nvvm_fence_proxy_async_global() {
; CHECK-LABEL: test_nvvm_fence_proxy_async_global(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    fence.proxy.async.global;
; CHECK-NEXT:    ret;
  call void @llvm.nvvm.fence.proxy.async.global()
  ret void
}

define void @test_nvvm_fence_proxy_async_shared_cluster() {
; CHECK-LABEL: test_nvvm_fence_proxy_async_shared_cluster(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    fence.proxy.async.shared::cluster;
; CHECK-NEXT:    ret;
  call void @llvm.nvvm.fence.proxy.async.shared_cluster()
  ret void
}

define void @test_nvvm_fence_proxy_async_shared_cta() {
; CHECK-LABEL: test_nvvm_fence_proxy_async_shared_cta(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    fence.proxy.async.shared::cta;
; CHECK-NEXT:    ret;
  call void @llvm.nvvm.fence.proxy.async.shared_cta()
  ret void
}
