; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=nvptx64 -mcpu=sm_90a -mattr=+ptx88 | FileCheck %s
; RUN: %if ptxas-sm_90a && ptxas-isa-8.8 %{ llc < %s -mtriple=nvptx64 -mcpu=sm_90a -mattr=+ptx88 | %ptxas-verify -arch=sm_90a %}

; combineInsertEltToShuffle must fire pre-type-legalization, else this i8 pack
; lowers to prmts that read uninitialized registers.

define ptx_kernel void @pack_i8(<2 x i8> %a) {
; CHECK-LABEL: pack_i8(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<4>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b32 %r1, 0;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    cvt.rn.satfinite.e4m3x2.f32 %rs1, %r1, %r1;
; CHECK-EMPTY:
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    cvt.u32.u16 %r2, %rs1;
; CHECK-NEXT:    prmt.b32 %r3, %r2, 0, 0x14U;
; CHECK-NEXT:    mov.b64 %rd1, 0;
; CHECK-NEXT:    st.shared.v4.b32 [%rd1], {%r3, 0, 0, 0};
; CHECK-NEXT:    ret;
  %asm = tail call <2 x i8> asm "cvt.rn.satfinite.e4m3x2.f32  $0, $2, $1; \0A", "=h,r,r"(i32 0, i32 0)
  %s = shufflevector <2 x i8> %a, <2 x i8> %asm, <4 x i32> <i32 1, i32 3, i32 poison, i32 poison>
  %ins = insertelement <4 x i8> %s, i8 0, i64 0
  %bc = bitcast <4 x i8> %ins to i32
  %v = insertelement <4 x i32> zeroinitializer, i32 %bc, i64 0
  store <4 x i32> %v, ptr addrspace(3) null, align 16
  ret void
}
