; RUN: llc -enable-new-pm -mtriple=nvptx64-nvidia-cuda -mcpu=sm_90 -O0 \
; RUN:     -print-pipeline-passes=tree < %s 2>&1 | FileCheck %s --check-prefix=O0
; RUN: llc -enable-new-pm -mtriple=nvptx64-nvidia-cuda -mcpu=sm_90 -O2 \
; RUN:     -print-pipeline-passes=tree < %s 2>&1 | FileCheck %s --check-prefix=O2

; O0: require<MachineModuleAnalysis>
; O0-NEXT: require<profile-summary>
; O0-NEXT: require<collector-metadata>
; O0-NEXT: require<runtime-libcall-info>
; O0-NEXT: require<libcall-lowering-info>
; O0-NEXT: pre-isel-intrinsic-lowering
; O0-NEXT: function
; O0-NEXT:   expand-ir-insts<O0>
; O0-NEXT: nvvm-reflect
; O0-NEXT: nvptx-assign-valid-global-names
; O0-NEXT: generic-to-nvvm
; O0-NEXT: expand-variadics
; O0-NEXT: function
; O0-NEXT:   nvptx-mark-kernel-ptrs-global
; O0-NEXT: nvptx-promote-param-align
; O0-NEXT: nvptx-lower-args
; O0-NEXT: function
; O0-NEXT:   nvptx-lower-alloca
; O0-NEXT:   atomic-expand
; O0-NEXT: nvptx-lower-ctor-dtor
; O0-NEXT: function
; O0-NEXT:   verify
; O0-NEXT:   gc-lowering
; O0-NEXT: shadow-stack-gc-lowering
; O0-NEXT: function
; O0-NEXT:   unreachableblockelim
; O0-NEXT:   ee-instrument<post-inline>
; O0-NEXT:   scalarize-masked-mem-intrin
; O0-NEXT:   expand-reductions
; O0-NEXT:   nvptx-lower-unreachable
; O0-NEXT:   lower-invoke
; O0-NEXT:   unreachableblockelim
; O0-NEXT:   inline-asm-prepare
; O0-NEXT:   safe-stack
; O0-NEXT:   stack-protector
; O0-NEXT:   verify
; O0-NEXT: nvptx-asm-printer-begin
; O0-NEXT: function
; O0-NEXT:   nvptx-lower-aggr-copies
; O0-NEXT:   nvptx-alloca-hoisting
; O0-NEXT:   machine-function
; O0-NEXT:     nvptx-isel
; O0-NEXT:     nvptx-replace-image-handles
; O0-NEXT:     finalize-isel
; O0-NEXT:     localstackalloc
; O0-NEXT:     nvptx-forward-params
; O0-NEXT:     nvptx-proxyreg-erasure
; O0-NEXT:     phi-node-elimination
; O0-NEXT:     two-address-instruction
; O0-NEXT:     nvptx-prolog-epilog
; O0-NEXT:     remove-redundant-debug-values
; O0-NEXT:     fixup-statepoint-caller-saved
; O0-NEXT:     post-ra-pseudos
; O0-NEXT:     fentry-insert
; O0-NEXT:     xray-instrumentation
; O0-NEXT:     live-debug-values
; O0-NEXT:     machine-sanmd
; O0-NEXT:     stack-frame-layout
; O0-NEXT:     nvptx-asm-printer
; O0-NEXT:   free-machine-function
; O0-NEXT: nvptx-asm-printer-end

; O2: require<MachineModuleAnalysis>
; O2-NEXT: require<profile-summary>
; O2-NEXT: require<collector-metadata>
; O2-NEXT: require<runtime-libcall-info>
; O2-NEXT: require<libcall-lowering-info>
; O2-NEXT: function
; O2-NEXT:   objc-arc-contract
; O2-NEXT: pre-isel-intrinsic-lowering
; O2-NEXT: function
; O2-NEXT:   expand-ir-insts<O2>
; O2-NEXT: nvvm-reflect
; O2-NEXT: function
; O2-NEXT:   nvptx-image-optimizer
; O2-NEXT: nvptx-assign-valid-global-names
; O2-NEXT: generic-to-nvvm
; O2-NEXT: expand-variadics
; O2-NEXT: function
; O2-NEXT:   nvptx-mark-kernel-ptrs-global
; O2-NEXT: nvptx-promote-param-align
; O2-NEXT: nvptx-lower-args
; O2-NEXT: function
; O2-NEXT:   sroa<preserve-cfg;aggregate-to-vector>
; O2-NEXT:   nvptx-lower-alloca
; O2-NEXT:   infer-address-spaces
; O2-NEXT:   nvptx-atomic-lower
; O2-NEXT:   separate-const-offset-from-gep<>
; O2-NEXT:   speculative-execution<>
; O2-NEXT:   slsr
; O2-NEXT:   early-cse<>
; O2-NEXT:   nary-reassociate
; O2-NEXT:   early-cse<>
; O2-NEXT:   atomic-expand
; O2-NEXT: nvptx-lower-ctor-dtor
; O2-NEXT: function
; O2-NEXT:   verify
; O2-NEXT:   loop
; O2-NEXT:     canon-freeze
; O2-NEXT:     loop-reduce
; O2-NEXT:   gc-lowering
; O2-NEXT: shadow-stack-gc-lowering
; O2-NEXT: function
; O2-NEXT:   unreachableblockelim
; O2-NEXT:   consthoist
; O2-NEXT:   replace-with-veclib
; O2-NEXT:   partially-inline-libcalls
; O2-NEXT:   ee-instrument<post-inline>
; O2-NEXT:   scalarize-masked-mem-intrin
; O2-NEXT:   expand-reductions
; O2-NEXT:   early-cse<>
; O2-NEXT:   load-store-vectorizer
; O2-NEXT:   sroa<preserve-cfg;aggregate-to-vector>
; O2-NEXT:   nvptx-tag-invariant-loads
; O2-NEXT:   nvptx-ir-peephole
; O2-NEXT:   nvptx-lower-unreachable
; O2-NEXT:   codegenprepare
; O2-NEXT:   lower-invoke
; O2-NEXT:   unreachableblockelim
; O2-NEXT:   inline-asm-prepare
; O2-NEXT:   safe-stack
; O2-NEXT:   stack-protector
; O2-NEXT:   verify
; O2-NEXT: nvptx-asm-printer-begin
; O2-NEXT: function
; O2-NEXT:   nvptx-lower-aggr-copies
; O2-NEXT:   nvptx-alloca-hoisting
; O2-NEXT:   machine-function
; O2-NEXT:     nvptx-isel
; O2-NEXT:     nvptx-replace-image-handles
; O2-NEXT:     finalize-isel
; O2-NEXT:     early-tailduplication
; O2-NEXT:     opt-phis
; O2-NEXT:     stack-coloring
; O2-NEXT:     localstackalloc
; O2-NEXT:     dead-mi-elimination
; O2-NEXT:     early-machinelicm
; O2-NEXT:     machine-cse
; O2-NEXT:     machine-sink
; O2-NEXT:     peephole-opt
; O2-NEXT:     dead-mi-elimination
; O2-NEXT:     nvptx-forward-params
; O2-NEXT:     nvptx-address-folder
; O2-NEXT:     nvptx-proxyreg-erasure
; O2-NEXT:     process-imp-defs
; O2-NEXT:     unreachable-mbb-elimination
; O2-NEXT:     require<live-vars>
; O2-NEXT:     require<machine-loops>
; O2-NEXT:     phi-node-elimination
; O2-NEXT:     two-address-instruction
; O2-NEXT:     register-coalescer
; O2-NEXT:     machine-scheduler
; O2-NEXT:     stack-slot-coloring
; O2-NEXT:     nvptx-prolog-epilog
; O2-NEXT:     nvptx-peephole
; O2-NEXT:     remove-redundant-debug-values
; O2-NEXT:     fixup-statepoint-caller-saved
; O2-NEXT:     branch-folder
; O2-NEXT:     post-ra-pseudos
; O2-NEXT:     block-placement
; O2-NEXT:     fentry-insert
; O2-NEXT:     xray-instrumentation
; O2-NEXT:     live-debug-values
; O2-NEXT:     machine-sanmd
; O2-NEXT:     stack-frame-layout
; O2-NEXT:     nvptx-asm-printer
; O2-NEXT:   free-machine-function
; O2-NEXT: nvptx-asm-printer-end

define void @empty() {
  ret void
}
