; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -march=nvptx64 -mcpu=sm_100 -O2 < %s | FileCheck %s
; RUN: %if ptxas-sm_100 %{ llc < %s -march=nvptx64 -mcpu=sm_100 -O2 | %ptxas-verify -arch=sm_100 %}

target triple = "nvptx64-nvidia-cuda"

; Test int16 integer comparison inversions

define i32 @test_int16_eq(i16 %a, i16 %b) {
; CHECK-LABEL: test_int16_eq(
; CHECK:       {
; CHECK-NEXT:    .reg .pred %p<2>;
; CHECK-NEXT:    .reg .b16 %rs<3>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    ld.param.b16 %rs2, [test_int16_eq_param_1];
; CHECK-NEXT:    ld.param.b16 %rs1, [test_int16_eq_param_0];
; CHECK-NEXT:    setp.eq.b16 %p1, %rs1, %rs2;
; CHECK-NEXT:    mov.b32 %r1, 0;
; CHECK-NEXT:    @%p1 bra $L__BB0_2;
; CHECK-NEXT:  // %bb.1: // %then
; CHECK-NEXT:    mov.b32 %r1, 1;
; CHECK-NEXT:  $L__BB0_2: // %merge1
; CHECK-NEXT:    @!%p1 bra $L__BB0_4;
; CHECK-NEXT:  // %bb.3: // %else
; CHECK-NEXT:    mov.b32 %r1, 0;
; CHECK-NEXT:  $L__BB0_4: // %merge2
; CHECK-NEXT:    st.param.b32 [func_retval0], %r1;
; CHECK-NEXT:    ret;
entry:
  %cmp = icmp eq i16 %a, %b
  br i1 %cmp, label %merge1, label %then

then:
  %tmp = load i32, ptr addrspace(1) null, align 4
  br label %merge1

merge1:
  %phi1 = phi i32 [ 1, %then ], [ 0, %entry ]
  %cmp2 = icmp ne i16 %a, %b
  br i1 %cmp2, label %merge2, label %else

else:
  br label %merge2

merge2:
  %phi2 = phi i32 [ %phi1, %merge1 ], [ 0, %else ]
  ret i32 %phi2
}

define i32 @test_int16_ne(i16 %a, i16 %b) {
; CHECK-LABEL: test_int16_ne(
; CHECK:       {
; CHECK-NEXT:    .reg .pred %p<2>;
; CHECK-NEXT:    .reg .b16 %rs<3>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    ld.param.b16 %rs2, [test_int16_ne_param_1];
; CHECK-NEXT:    ld.param.b16 %rs1, [test_int16_ne_param_0];
; CHECK-NEXT:    setp.ne.b16 %p1, %rs1, %rs2;
; CHECK-NEXT:    mov.b32 %r1, 0;
; CHECK-NEXT:    @%p1 bra $L__BB1_2;
; CHECK-NEXT:  // %bb.1: // %then
; CHECK-NEXT:    mov.b32 %r1, 1;
; CHECK-NEXT:  $L__BB1_2: // %merge1
; CHECK-NEXT:    @!%p1 bra $L__BB1_4;
; CHECK-NEXT:  // %bb.3: // %else
; CHECK-NEXT:    mov.b32 %r1, 0;
; CHECK-NEXT:  $L__BB1_4: // %merge2
; CHECK-NEXT:    st.param.b32 [func_retval0], %r1;
; CHECK-NEXT:    ret;
entry:
  %cmp = icmp ne i16 %a, %b
  br i1 %cmp, label %merge1, label %then

then:
  %tmp = load i32, ptr addrspace(1) null, align 4
  br label %merge1

merge1:
  %phi1 = phi i32 [ 1, %then ], [ 0, %entry ]
  %cmp2 = icmp eq i16 %a, %b
  br i1 %cmp2, label %merge2, label %else

else:
  br label %merge2

merge2:
  %phi2 = phi i32 [ %phi1, %merge1 ], [ 0, %else ]
  ret i32 %phi2
}

define i32 @test_int16_slt(i16 %a, i16 %b) {
; CHECK-LABEL: test_int16_slt(
; CHECK:       {
; CHECK-NEXT:    .reg .pred %p<2>;
; CHECK-NEXT:    .reg .b16 %rs<3>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    ld.param.b16 %rs2, [test_int16_slt_param_1];
; CHECK-NEXT:    ld.param.b16 %rs1, [test_int16_slt_param_0];
; CHECK-NEXT:    setp.lt.s16 %p1, %rs1, %rs2;
; CHECK-NEXT:    mov.b32 %r1, 0;
; CHECK-NEXT:    @%p1 bra $L__BB2_2;
; CHECK-NEXT:  // %bb.1: // %then
; CHECK-NEXT:    mov.b32 %r1, 1;
; CHECK-NEXT:  $L__BB2_2: // %merge1
; CHECK-NEXT:    @!%p1 bra $L__BB2_4;
; CHECK-NEXT:  // %bb.3: // %else
; CHECK-NEXT:    mov.b32 %r1, 0;
; CHECK-NEXT:  $L__BB2_4: // %merge2
; CHECK-NEXT:    st.param.b32 [func_retval0], %r1;
; CHECK-NEXT:    ret;
entry:
  %cmp = icmp slt i16 %a, %b
  br i1 %cmp, label %merge1, label %then

then:
  %tmp = load i32, ptr addrspace(1) null, align 4
  br label %merge1

merge1:
  %phi1 = phi i32 [ 1, %then ], [ 0, %entry ]
  %cmp2 = icmp sge i16 %a, %b
  br i1 %cmp2, label %merge2, label %else

else:
  br label %merge2

merge2:
  %phi2 = phi i32 [ %phi1, %merge1 ], [ 0, %else ]
  ret i32 %phi2
}

define i32 @test_int16_sle(i16 %a, i16 %b) {
; CHECK-LABEL: test_int16_sle(
; CHECK:       {
; CHECK-NEXT:    .reg .pred %p<2>;
; CHECK-NEXT:    .reg .b16 %rs<3>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    ld.param.b16 %rs2, [test_int16_sle_param_1];
; CHECK-NEXT:    ld.param.b16 %rs1, [test_int16_sle_param_0];
; CHECK-NEXT:    setp.le.s16 %p1, %rs1, %rs2;
; CHECK-NEXT:    mov.b32 %r1, 0;
; CHECK-NEXT:    @%p1 bra $L__BB3_2;
; CHECK-NEXT:  // %bb.1: // %then
; CHECK-NEXT:    mov.b32 %r1, 1;
; CHECK-NEXT:  $L__BB3_2: // %merge1
; CHECK-NEXT:    @!%p1 bra $L__BB3_4;
; CHECK-NEXT:  // %bb.3: // %else
; CHECK-NEXT:    mov.b32 %r1, 0;
; CHECK-NEXT:  $L__BB3_4: // %merge2
; CHECK-NEXT:    st.param.b32 [func_retval0], %r1;
; CHECK-NEXT:    ret;
entry:
  %cmp = icmp sle i16 %a, %b
  br i1 %cmp, label %merge1, label %then

then:
  %tmp = load i32, ptr addrspace(1) null, align 4
  br label %merge1

merge1:
  %phi1 = phi i32 [ 1, %then ], [ 0, %entry ]
  %cmp2 = icmp sgt i16 %a, %b
  br i1 %cmp2, label %merge2, label %else

else:
  br label %merge2

merge2:
  %phi2 = phi i32 [ %phi1, %merge1 ], [ 0, %else ]
  ret i32 %phi2
}

define i32 @test_int16_sgt(i16 %a, i16 %b) {
; CHECK-LABEL: test_int16_sgt(
; CHECK:       {
; CHECK-NEXT:    .reg .pred %p<2>;
; CHECK-NEXT:    .reg .b16 %rs<3>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    ld.param.b16 %rs2, [test_int16_sgt_param_1];
; CHECK-NEXT:    ld.param.b16 %rs1, [test_int16_sgt_param_0];
; CHECK-NEXT:    setp.gt.s16 %p1, %rs1, %rs2;
; CHECK-NEXT:    mov.b32 %r1, 0;
; CHECK-NEXT:    @%p1 bra $L__BB4_2;
; CHECK-NEXT:  // %bb.1: // %then
; CHECK-NEXT:    mov.b32 %r1, 1;
; CHECK-NEXT:  $L__BB4_2: // %merge1
; CHECK-NEXT:    @!%p1 bra $L__BB4_4;
; CHECK-NEXT:  // %bb.3: // %else
; CHECK-NEXT:    mov.b32 %r1, 0;
; CHECK-NEXT:  $L__BB4_4: // %merge2
; CHECK-NEXT:    st.param.b32 [func_retval0], %r1;
; CHECK-NEXT:    ret;
entry:
  %cmp = icmp sgt i16 %a, %b
  br i1 %cmp, label %merge1, label %then

then:
  %tmp = load i32, ptr addrspace(1) null, align 4
  br label %merge1

merge1:
  %phi1 = phi i32 [ 1, %then ], [ 0, %entry ]
  %cmp2 = icmp sle i16 %a, %b
  br i1 %cmp2, label %merge2, label %else

else:
  br label %merge2

merge2:
  %phi2 = phi i32 [ %phi1, %merge1 ], [ 0, %else ]
  ret i32 %phi2
}

define i32 @test_int16_sge(i16 %a, i16 %b) {
; CHECK-LABEL: test_int16_sge(
; CHECK:       {
; CHECK-NEXT:    .reg .pred %p<2>;
; CHECK-NEXT:    .reg .b16 %rs<3>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    ld.param.b16 %rs2, [test_int16_sge_param_1];
; CHECK-NEXT:    ld.param.b16 %rs1, [test_int16_sge_param_0];
; CHECK-NEXT:    setp.ge.s16 %p1, %rs1, %rs2;
; CHECK-NEXT:    mov.b32 %r1, 0;
; CHECK-NEXT:    @%p1 bra $L__BB5_2;
; CHECK-NEXT:  // %bb.1: // %then
; CHECK-NEXT:    mov.b32 %r1, 1;
; CHECK-NEXT:  $L__BB5_2: // %merge1
; CHECK-NEXT:    @!%p1 bra $L__BB5_4;
; CHECK-NEXT:  // %bb.3: // %else
; CHECK-NEXT:    mov.b32 %r1, 0;
; CHECK-NEXT:  $L__BB5_4: // %merge2
; CHECK-NEXT:    st.param.b32 [func_retval0], %r1;
; CHECK-NEXT:    ret;
entry:
  %cmp = icmp sge i16 %a, %b
  br i1 %cmp, label %merge1, label %then

then:
  %tmp = load i32, ptr addrspace(1) null, align 4
  br label %merge1

merge1:
  %phi1 = phi i32 [ 1, %then ], [ 0, %entry ]
  %cmp2 = icmp slt i16 %a, %b
  br i1 %cmp2, label %merge2, label %else

else:
  br label %merge2

merge2:
  %phi2 = phi i32 [ %phi1, %merge1 ], [ 0, %else ]
  ret i32 %phi2
}

define i32 @test_int16_ult(i16 %a, i16 %b) {
; CHECK-LABEL: test_int16_ult(
; CHECK:       {
; CHECK-NEXT:    .reg .pred %p<2>;
; CHECK-NEXT:    .reg .b16 %rs<3>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    ld.param.b16 %rs2, [test_int16_ult_param_1];
; CHECK-NEXT:    ld.param.b16 %rs1, [test_int16_ult_param_0];
; CHECK-NEXT:    setp.lt.u16 %p1, %rs1, %rs2;
; CHECK-NEXT:    mov.b32 %r1, 0;
; CHECK-NEXT:    @%p1 bra $L__BB6_2;
; CHECK-NEXT:  // %bb.1: // %then
; CHECK-NEXT:    mov.b32 %r1, 1;
; CHECK-NEXT:  $L__BB6_2: // %merge1
; CHECK-NEXT:    @!%p1 bra $L__BB6_4;
; CHECK-NEXT:  // %bb.3: // %else
; CHECK-NEXT:    mov.b32 %r1, 0;
; CHECK-NEXT:  $L__BB6_4: // %merge2
; CHECK-NEXT:    st.param.b32 [func_retval0], %r1;
; CHECK-NEXT:    ret;
entry:
  %cmp = icmp ult i16 %a, %b
  br i1 %cmp, label %merge1, label %then

then:
  %tmp = load i32, ptr addrspace(1) null, align 4
  br label %merge1

merge1:
  %phi1 = phi i32 [ 1, %then ], [ 0, %entry ]
  %cmp2 = icmp uge i16 %a, %b
  br i1 %cmp2, label %merge2, label %else

else:
  br label %merge2

merge2:
  %phi2 = phi i32 [ %phi1, %merge1 ], [ 0, %else ]
  ret i32 %phi2
}

define i32 @test_int16_ule(i16 %a, i16 %b) {
; CHECK-LABEL: test_int16_ule(
; CHECK:       {
; CHECK-NEXT:    .reg .pred %p<2>;
; CHECK-NEXT:    .reg .b16 %rs<3>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    ld.param.b16 %rs2, [test_int16_ule_param_1];
; CHECK-NEXT:    ld.param.b16 %rs1, [test_int16_ule_param_0];
; CHECK-NEXT:    setp.le.u16 %p1, %rs1, %rs2;
; CHECK-NEXT:    mov.b32 %r1, 0;
; CHECK-NEXT:    @%p1 bra $L__BB7_2;
; CHECK-NEXT:  // %bb.1: // %then
; CHECK-NEXT:    mov.b32 %r1, 1;
; CHECK-NEXT:  $L__BB7_2: // %merge1
; CHECK-NEXT:    @!%p1 bra $L__BB7_4;
; CHECK-NEXT:  // %bb.3: // %else
; CHECK-NEXT:    mov.b32 %r1, 0;
; CHECK-NEXT:  $L__BB7_4: // %merge2
; CHECK-NEXT:    st.param.b32 [func_retval0], %r1;
; CHECK-NEXT:    ret;
entry:
  %cmp = icmp ule i16 %a, %b
  br i1 %cmp, label %merge1, label %then

then:
  %tmp = load i32, ptr addrspace(1) null, align 4
  br label %merge1

merge1:
  %phi1 = phi i32 [ 1, %then ], [ 0, %entry ]
  %cmp2 = icmp ugt i16 %a, %b
  br i1 %cmp2, label %merge2, label %else

else:
  br label %merge2

merge2:
  %phi2 = phi i32 [ %phi1, %merge1 ], [ 0, %else ]
  ret i32 %phi2
}

define i32 @test_int16_ugt(i16 %a, i16 %b) {
; CHECK-LABEL: test_int16_ugt(
; CHECK:       {
; CHECK-NEXT:    .reg .pred %p<2>;
; CHECK-NEXT:    .reg .b16 %rs<3>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    ld.param.b16 %rs2, [test_int16_ugt_param_1];
; CHECK-NEXT:    ld.param.b16 %rs1, [test_int16_ugt_param_0];
; CHECK-NEXT:    setp.gt.u16 %p1, %rs1, %rs2;
; CHECK-NEXT:    mov.b32 %r1, 0;
; CHECK-NEXT:    @%p1 bra $L__BB8_2;
; CHECK-NEXT:  // %bb.1: // %then
; CHECK-NEXT:    mov.b32 %r1, 1;
; CHECK-NEXT:  $L__BB8_2: // %merge1
; CHECK-NEXT:    @!%p1 bra $L__BB8_4;
; CHECK-NEXT:  // %bb.3: // %else
; CHECK-NEXT:    mov.b32 %r1, 0;
; CHECK-NEXT:  $L__BB8_4: // %merge2
; CHECK-NEXT:    st.param.b32 [func_retval0], %r1;
; CHECK-NEXT:    ret;
entry:
  %cmp = icmp ugt i16 %a, %b
  br i1 %cmp, label %merge1, label %then

then:
  %tmp = load i32, ptr addrspace(1) null, align 4
  br label %merge1

merge1:
  %phi1 = phi i32 [ 1, %then ], [ 0, %entry ]
  %cmp2 = icmp ule i16 %a, %b
  br i1 %cmp2, label %merge2, label %else

else:
  br label %merge2

merge2:
  %phi2 = phi i32 [ %phi1, %merge1 ], [ 0, %else ]
  ret i32 %phi2
}

define i32 @test_int16_uge(i16 %a, i16 %b) {
; CHECK-LABEL: test_int16_uge(
; CHECK:       {
; CHECK-NEXT:    .reg .pred %p<2>;
; CHECK-NEXT:    .reg .b16 %rs<3>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0: // %entry
; CHECK-NEXT:    ld.param.b16 %rs2, [test_int16_uge_param_1];
; CHECK-NEXT:    ld.param.b16 %rs1, [test_int16_uge_param_0];
; CHECK-NEXT:    setp.ge.u16 %p1, %rs1, %rs2;
; CHECK-NEXT:    mov.b32 %r1, 0;
; CHECK-NEXT:    @%p1 bra $L__BB9_2;
; CHECK-NEXT:  // %bb.1: // %then
; CHECK-NEXT:    mov.b32 %r1, 1;
; CHECK-NEXT:  $L__BB9_2: // %merge1
; CHECK-NEXT:    @!%p1 bra $L__BB9_4;
; CHECK-NEXT:  // %bb.3: // %else
; CHECK-NEXT:    mov.b32 %r1, 0;
; CHECK-NEXT:  $L__BB9_4: // %merge2
; CHECK-NEXT:    st.param.b32 [func_retval0], %r1;
; CHECK-NEXT:    ret;
entry:
  %cmp = icmp uge i16 %a, %b
  br i1 %cmp, label %merge1, label %then

then:
  %tmp = load i32, ptr addrspace(1) null, align 4
  br label %merge1

merge1:
  %phi1 = phi i32 [ 1, %then ], [ 0, %entry ]
  %cmp2 = icmp ult i16 %a, %b
  br i1 %cmp2, label %merge2, label %else

else:
  br label %merge2

merge2:
  %phi2 = phi i32 [ %phi1, %merge1 ], [ 0, %else ]
  ret i32 %phi2
}
