; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=nvptx64 -mcpu=sm_90 -mattr=+ptx81 | FileCheck --check-prefixes=CHECK-PTX64 %s
; RUN: llc < %s -mtriple=nvptx64 -mcpu=sm_90 -mattr=+ptx81 --nvptx-short-ptr | FileCheck --check-prefixes=CHECK-SHARED32 %s
; RUN: %if ptxas-sm_90 && ptxas-isa-8.1 %{ llc < %s -mtriple=nvptx64 -mcpu=sm_90 -mattr=+ptx81 | %ptxas-verify -arch=sm_90 %}
; RUN: %if ptxas-sm_90 && ptxas-isa-8.1 %{ llc < %s -mtriple=nvptx64 -mcpu=sm_90 -mattr=+ptx81 --nvptx-short-ptr | %ptxas-verify -arch=sm_90 %}

define void @test_st_async_mbarrier_b32(ptr addrspace(7) %addr, i32 %value, ptr addrspace(7) %mbar) {
; CHECK-PTX64-LABEL: test_st_async_mbarrier_b32(
; CHECK-PTX64:       {
; CHECK-PTX64-NEXT:    .reg .b32 %r<2>;
; CHECK-PTX64-NEXT:    .reg .b64 %rd<3>;
; CHECK-PTX64-EMPTY:
; CHECK-PTX64-NEXT:  // %bb.0:
; CHECK-PTX64-NEXT:    ld.param.b64 %rd1, [test_st_async_mbarrier_b32_param_0];
; CHECK-PTX64-NEXT:    ld.param.b32 %r1, [test_st_async_mbarrier_b32_param_1];
; CHECK-PTX64-NEXT:    ld.param.b64 %rd2, [test_st_async_mbarrier_b32_param_2];
; CHECK-PTX64-NEXT:    st.async.shared::cluster.mbarrier::complete_tx::bytes.b32 [%rd1], %r1, [%rd2];
; CHECK-PTX64-NEXT:    ret;
;
; CHECK-SHARED32-LABEL: test_st_async_mbarrier_b32(
; CHECK-SHARED32:       {
; CHECK-SHARED32-NEXT:    .reg .b32 %r<4>;
; CHECK-SHARED32-EMPTY:
; CHECK-SHARED32-NEXT:  // %bb.0:
; CHECK-SHARED32-NEXT:    ld.param.b32 %r1, [test_st_async_mbarrier_b32_param_0];
; CHECK-SHARED32-NEXT:    ld.param.b32 %r2, [test_st_async_mbarrier_b32_param_1];
; CHECK-SHARED32-NEXT:    ld.param.b32 %r3, [test_st_async_mbarrier_b32_param_2];
; CHECK-SHARED32-NEXT:    st.async.shared::cluster.mbarrier::complete_tx::bytes.b32 [%r1], %r2, [%r3];
; CHECK-SHARED32-NEXT:    ret;
  call void @llvm.nvvm.st.async.space.cluster.i32(ptr addrspace(7) %addr, i32 %value, ptr addrspace(7) %mbar)
  ret void
}

define void @test_st_async_mbarrier_b64(ptr addrspace(7) %addr, i64 %value, ptr addrspace(7) %mbar) {
; CHECK-PTX64-LABEL: test_st_async_mbarrier_b64(
; CHECK-PTX64:       {
; CHECK-PTX64-NEXT:    .reg .b64 %rd<4>;
; CHECK-PTX64-EMPTY:
; CHECK-PTX64-NEXT:  // %bb.0:
; CHECK-PTX64-NEXT:    ld.param.b64 %rd1, [test_st_async_mbarrier_b64_param_0];
; CHECK-PTX64-NEXT:    ld.param.b64 %rd2, [test_st_async_mbarrier_b64_param_1];
; CHECK-PTX64-NEXT:    ld.param.b64 %rd3, [test_st_async_mbarrier_b64_param_2];
; CHECK-PTX64-NEXT:    st.async.shared::cluster.mbarrier::complete_tx::bytes.b64 [%rd1], %rd2, [%rd3];
; CHECK-PTX64-NEXT:    ret;
;
; CHECK-SHARED32-LABEL: test_st_async_mbarrier_b64(
; CHECK-SHARED32:       {
; CHECK-SHARED32-NEXT:    .reg .b32 %r<3>;
; CHECK-SHARED32-NEXT:    .reg .b64 %rd<2>;
; CHECK-SHARED32-EMPTY:
; CHECK-SHARED32-NEXT:  // %bb.0:
; CHECK-SHARED32-NEXT:    ld.param.b32 %r1, [test_st_async_mbarrier_b64_param_0];
; CHECK-SHARED32-NEXT:    ld.param.b64 %rd1, [test_st_async_mbarrier_b64_param_1];
; CHECK-SHARED32-NEXT:    ld.param.b32 %r2, [test_st_async_mbarrier_b64_param_2];
; CHECK-SHARED32-NEXT:    st.async.shared::cluster.mbarrier::complete_tx::bytes.b64 [%r1], %rd1, [%r2];
; CHECK-SHARED32-NEXT:    ret;
  call void @llvm.nvvm.st.async.space.cluster.i64(ptr addrspace(7) %addr, i64 %value, ptr addrspace(7) %mbar)
  ret void
}
