; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=nvptx64 -mcpu=sm_90 -mattr=+ptx92 | FileCheck --check-prefixes=CHECK-PTX64 %s
; RUN: llc < %s -mtriple=nvptx64 -mcpu=sm_90 -mattr=+ptx92 --nvptx-short-ptr | FileCheck --check-prefixes=CHECK-SHARED32 %s
; RUN: %if ptxas-sm_90 && ptxas-isa-9.2 %{ llc < %s -mtriple=nvptx64 -mcpu=sm_90 -mattr=+ptx92 | %ptxas-verify -arch=sm_90 %}
; RUN: %if ptxas-sm_90 && ptxas-isa-9.2 %{ llc < %s -mtriple=nvptx64 -mcpu=sm_90 -mattr=+ptx92 --nvptx-short-ptr | %ptxas-verify -arch=sm_90 %}

define void @test_st_async_mbarrier_b128(ptr addrspace(7) %addr, i128 %value, ptr addrspace(7) %mbar) {
; CHECK-PTX64-LABEL: test_st_async_mbarrier_b128(
; CHECK-PTX64:       {
; CHECK-PTX64-NEXT:    .reg .b64 %rd<5>;
; CHECK-PTX64-EMPTY:
; CHECK-PTX64-NEXT:  // %bb.0:
; CHECK-PTX64-NEXT:    ld.param.b64 %rd1, [test_st_async_mbarrier_b128_param_0];
; CHECK-PTX64-NEXT:    ld.param.v2.b64 {%rd2, %rd3}, [test_st_async_mbarrier_b128_param_1];
; CHECK-PTX64-NEXT:    ld.param.b64 %rd4, [test_st_async_mbarrier_b128_param_2];
; CHECK-PTX64-NEXT:    {
; CHECK-PTX64-NEXT:    .reg .b128 %in_128;
; CHECK-PTX64-NEXT:    mov.b128 %in_128, {%rd2, %rd3};
; CHECK-PTX64-NEXT:    st.async.shared::cluster.mbarrier::complete_tx::bytes.b128 [%rd1], %in_128, [%rd4];
; CHECK-PTX64-NEXT:    }
; CHECK-PTX64-NEXT:    ret;
;
; CHECK-SHARED32-LABEL: test_st_async_mbarrier_b128(
; CHECK-SHARED32:       {
; CHECK-SHARED32-NEXT:    .reg .b32 %r<3>;
; CHECK-SHARED32-NEXT:    .reg .b64 %rd<3>;
; CHECK-SHARED32-EMPTY:
; CHECK-SHARED32-NEXT:  // %bb.0:
; CHECK-SHARED32-NEXT:    ld.param.b32 %r1, [test_st_async_mbarrier_b128_param_0];
; CHECK-SHARED32-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [test_st_async_mbarrier_b128_param_1];
; CHECK-SHARED32-NEXT:    ld.param.b32 %r2, [test_st_async_mbarrier_b128_param_2];
; CHECK-SHARED32-NEXT:    {
; CHECK-SHARED32-NEXT:    .reg .b128 %in_128;
; CHECK-SHARED32-NEXT:    mov.b128 %in_128, {%rd1, %rd2};
; CHECK-SHARED32-NEXT:    st.async.shared::cluster.mbarrier::complete_tx::bytes.b128 [%r1], %in_128, [%r2];
; CHECK-SHARED32-NEXT:    }
; CHECK-SHARED32-NEXT:    ret;
  call void @llvm.nvvm.st.async.space.cluster.i128(ptr addrspace(7) %addr, i128 %value, ptr addrspace(7) %mbar)
  ret void
}
