; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -march=nvptx64 -mcpu=sm_90 -mattr=+ptx87 | FileCheck %s
; RUN: %if ptxas-sm_90 && ptxas-isa-8.7 %{ llc < %s -march=nvptx64 -mcpu=sm_90 -mattr=+ptx87 | %ptxas-verify -arch=sm_90 %}

define void @notatomic_i8_generic(i8 %val, ptr %addr) {
; CHECK-LABEL: notatomic_i8_generic(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [notatomic_i8_generic_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_i8_generic_param_1];
; CHECK-NEXT:    st.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store i8 %val, ptr %addr
    ret void
}

define void @notatomic_i8_generic_volatile(i8 %val, ptr %addr) {
; CHECK-LABEL: notatomic_i8_generic_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [notatomic_i8_generic_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_i8_generic_volatile_param_1];
; CHECK-NEXT:    st.volatile.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store volatile i8 %val, ptr %addr
    ret void
}

define void @notatomic_i16_generic(i16 %val, ptr %addr) {
; CHECK-LABEL: notatomic_i16_generic(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [notatomic_i16_generic_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_i16_generic_param_1];
; CHECK-NEXT:    st.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store i16 %val, ptr %addr
    ret void
}

define void @notatomic_i16_generic_volatile(i16 %val, ptr %addr) {
; CHECK-LABEL: notatomic_i16_generic_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [notatomic_i16_generic_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_i16_generic_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store volatile i16 %val, ptr %addr
    ret void
}

define void @notatomic_i32_generic(i32 %val, ptr %addr) {
; CHECK-LABEL: notatomic_i32_generic(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [notatomic_i32_generic_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_i32_generic_param_1];
; CHECK-NEXT:    st.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store i32 %val, ptr %addr
    ret void
}

define void @notatomic_i32_generic_volatile(i32 %val, ptr %addr) {
; CHECK-LABEL: notatomic_i32_generic_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [notatomic_i32_generic_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_i32_generic_volatile_param_1];
; CHECK-NEXT:    st.volatile.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store volatile i32 %val, ptr %addr
    ret void
}

define void @notatomic_i64_generic(i64 %val, ptr %addr) {
; CHECK-LABEL: notatomic_i64_generic(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_i64_generic_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [notatomic_i64_generic_param_1];
; CHECK-NEXT:    st.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store i64 %val, ptr %addr
    ret void
}

define void @notatomic_i64_generic_volatile(i64 %val, ptr %addr) {
; CHECK-LABEL: notatomic_i64_generic_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_i64_generic_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [notatomic_i64_generic_volatile_param_1];
; CHECK-NEXT:    st.volatile.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store volatile i64 %val, ptr %addr
    ret void
}

define void @notatomic_i128_generic(i128 %val, ptr %addr) {
; CHECK-LABEL: notatomic_i128_generic(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [notatomic_i128_generic_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [notatomic_i128_generic_param_1];
; CHECK-NEXT:    st.v2.b64 [%rd3], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    store i128 %val, ptr %addr
    ret void
}

define void @notatomic_i128_generic_volatile(i128 %val, ptr %addr) {
; CHECK-LABEL: notatomic_i128_generic_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [notatomic_i128_generic_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [notatomic_i128_generic_volatile_param_1];
; CHECK-NEXT:    st.volatile.v2.b64 [%rd3], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    store volatile i128 %val, ptr %addr
    ret void
}

define void @notatomic_half_generic(half %val, ptr %addr) {
; CHECK-LABEL: notatomic_half_generic(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [notatomic_half_generic_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_half_generic_param_1];
; CHECK-NEXT:    st.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store half %val, ptr %addr
    ret void
}

define void @notatomic_half_generic_volatile(half %val, ptr %addr) {
; CHECK-LABEL: notatomic_half_generic_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [notatomic_half_generic_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_half_generic_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store volatile half %val, ptr %addr
    ret void
}

define void @notatomic_bfloat_generic(bfloat %val, ptr %addr) {
; CHECK-LABEL: notatomic_bfloat_generic(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [notatomic_bfloat_generic_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_bfloat_generic_param_1];
; CHECK-NEXT:    st.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store bfloat %val, ptr %addr
    ret void
}

define void @notatomic_bfloat_generic_volatile(bfloat %val, ptr %addr) {
; CHECK-LABEL: notatomic_bfloat_generic_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [notatomic_bfloat_generic_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_bfloat_generic_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store volatile bfloat %val, ptr %addr
    ret void
}

define void @notatomic_float_generic(float %val, ptr %addr) {
; CHECK-LABEL: notatomic_float_generic(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [notatomic_float_generic_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_float_generic_param_1];
; CHECK-NEXT:    st.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store float %val, ptr %addr
    ret void
}

define void @notatomic_float_generic_volatile(float %val, ptr %addr) {
; CHECK-LABEL: notatomic_float_generic_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [notatomic_float_generic_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_float_generic_volatile_param_1];
; CHECK-NEXT:    st.volatile.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store volatile float %val, ptr %addr
    ret void
}

define void @notatomic_double_generic(double %val, ptr %addr) {
; CHECK-LABEL: notatomic_double_generic(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_double_generic_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [notatomic_double_generic_param_1];
; CHECK-NEXT:    st.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store double %val, ptr %addr
    ret void
}

define void @notatomic_double_generic_volatile(double %val, ptr %addr) {
; CHECK-LABEL: notatomic_double_generic_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_double_generic_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [notatomic_double_generic_volatile_param_1];
; CHECK-NEXT:    st.volatile.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store volatile double %val, ptr %addr
    ret void
}

define void @notatomic_i8_global(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: notatomic_i8_global(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [notatomic_i8_global_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_i8_global_param_1];
; CHECK-NEXT:    st.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store i8 %val, ptr addrspace(1) %addr
    ret void
}

define void @notatomic_i8_global_volatile(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: notatomic_i8_global_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [notatomic_i8_global_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_i8_global_volatile_param_1];
; CHECK-NEXT:    st.volatile.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store volatile i8 %val, ptr addrspace(1) %addr
    ret void
}

define void @notatomic_i16_global(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: notatomic_i16_global(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [notatomic_i16_global_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_i16_global_param_1];
; CHECK-NEXT:    st.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store i16 %val, ptr addrspace(1) %addr
    ret void
}

define void @notatomic_i16_global_volatile(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: notatomic_i16_global_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [notatomic_i16_global_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_i16_global_volatile_param_1];
; CHECK-NEXT:    st.volatile.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store volatile i16 %val, ptr addrspace(1) %addr
    ret void
}

define void @notatomic_i32_global(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: notatomic_i32_global(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [notatomic_i32_global_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_i32_global_param_1];
; CHECK-NEXT:    st.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store i32 %val, ptr addrspace(1) %addr
    ret void
}

define void @notatomic_i32_global_volatile(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: notatomic_i32_global_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [notatomic_i32_global_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_i32_global_volatile_param_1];
; CHECK-NEXT:    st.volatile.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store volatile i32 %val, ptr addrspace(1) %addr
    ret void
}

define void @notatomic_i64_global(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: notatomic_i64_global(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_i64_global_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [notatomic_i64_global_param_1];
; CHECK-NEXT:    st.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store i64 %val, ptr addrspace(1) %addr
    ret void
}

define void @notatomic_i64_global_volatile(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: notatomic_i64_global_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_i64_global_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [notatomic_i64_global_volatile_param_1];
; CHECK-NEXT:    st.volatile.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store volatile i64 %val, ptr addrspace(1) %addr
    ret void
}

define void @notatomic_i128_global(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: notatomic_i128_global(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [notatomic_i128_global_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [notatomic_i128_global_param_1];
; CHECK-NEXT:    st.global.v2.b64 [%rd3], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    store i128 %val, ptr addrspace(1) %addr
    ret void
}

define void @notatomic_i128_global_volatile(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: notatomic_i128_global_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [notatomic_i128_global_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [notatomic_i128_global_volatile_param_1];
; CHECK-NEXT:    st.volatile.global.v2.b64 [%rd3], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    store volatile i128 %val, ptr addrspace(1) %addr
    ret void
}

define void @notatomic_half_global(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: notatomic_half_global(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [notatomic_half_global_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_half_global_param_1];
; CHECK-NEXT:    st.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store half %val, ptr addrspace(1) %addr
    ret void
}

define void @notatomic_half_global_volatile(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: notatomic_half_global_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [notatomic_half_global_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_half_global_volatile_param_1];
; CHECK-NEXT:    st.volatile.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store volatile half %val, ptr addrspace(1) %addr
    ret void
}

define void @notatomic_bfloat_global(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: notatomic_bfloat_global(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [notatomic_bfloat_global_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_bfloat_global_param_1];
; CHECK-NEXT:    st.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store bfloat %val, ptr addrspace(1) %addr
    ret void
}

define void @notatomic_bfloat_global_volatile(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: notatomic_bfloat_global_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [notatomic_bfloat_global_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_bfloat_global_volatile_param_1];
; CHECK-NEXT:    st.volatile.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store volatile bfloat %val, ptr addrspace(1) %addr
    ret void
}

define void @notatomic_float_global(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: notatomic_float_global(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [notatomic_float_global_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_float_global_param_1];
; CHECK-NEXT:    st.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store float %val, ptr addrspace(1) %addr
    ret void
}

define void @notatomic_float_global_volatile(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: notatomic_float_global_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [notatomic_float_global_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_float_global_volatile_param_1];
; CHECK-NEXT:    st.volatile.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store volatile float %val, ptr addrspace(1) %addr
    ret void
}

define void @notatomic_double_global(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: notatomic_double_global(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_double_global_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [notatomic_double_global_param_1];
; CHECK-NEXT:    st.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store double %val, ptr addrspace(1) %addr
    ret void
}

define void @notatomic_double_global_volatile(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: notatomic_double_global_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_double_global_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [notatomic_double_global_volatile_param_1];
; CHECK-NEXT:    st.volatile.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store volatile double %val, ptr addrspace(1) %addr
    ret void
}

define void @notatomic_i8_shared(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: notatomic_i8_shared(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [notatomic_i8_shared_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_i8_shared_param_1];
; CHECK-NEXT:    st.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store i8 %val, ptr addrspace(3) %addr
    ret void
}

define void @notatomic_i8_shared_volatile(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: notatomic_i8_shared_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [notatomic_i8_shared_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_i8_shared_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store volatile i8 %val, ptr addrspace(3) %addr
    ret void
}

define void @notatomic_i16_shared(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: notatomic_i16_shared(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [notatomic_i16_shared_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_i16_shared_param_1];
; CHECK-NEXT:    st.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store i16 %val, ptr addrspace(3) %addr
    ret void
}

define void @notatomic_i16_shared_volatile(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: notatomic_i16_shared_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [notatomic_i16_shared_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_i16_shared_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store volatile i16 %val, ptr addrspace(3) %addr
    ret void
}

define void @notatomic_i32_shared(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: notatomic_i32_shared(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [notatomic_i32_shared_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_i32_shared_param_1];
; CHECK-NEXT:    st.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store i32 %val, ptr addrspace(3) %addr
    ret void
}

define void @notatomic_i32_shared_volatile(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: notatomic_i32_shared_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [notatomic_i32_shared_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_i32_shared_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store volatile i32 %val, ptr addrspace(3) %addr
    ret void
}

define void @notatomic_i64_shared(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: notatomic_i64_shared(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_i64_shared_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [notatomic_i64_shared_param_1];
; CHECK-NEXT:    st.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store i64 %val, ptr addrspace(3) %addr
    ret void
}

define void @notatomic_i64_shared_volatile(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: notatomic_i64_shared_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_i64_shared_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [notatomic_i64_shared_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store volatile i64 %val, ptr addrspace(3) %addr
    ret void
}

define void @notatomic_i128_shared(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: notatomic_i128_shared(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [notatomic_i128_shared_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [notatomic_i128_shared_param_1];
; CHECK-NEXT:    st.shared.v2.b64 [%rd3], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    store i128 %val, ptr addrspace(3) %addr
    ret void
}

define void @notatomic_i128_shared_volatile(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: notatomic_i128_shared_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [notatomic_i128_shared_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [notatomic_i128_shared_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.v2.b64 [%rd3], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    store volatile i128 %val, ptr addrspace(3) %addr
    ret void
}

define void @notatomic_half_shared(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: notatomic_half_shared(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [notatomic_half_shared_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_half_shared_param_1];
; CHECK-NEXT:    st.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store half %val, ptr addrspace(3) %addr
    ret void
}

define void @notatomic_half_shared_volatile(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: notatomic_half_shared_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [notatomic_half_shared_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_half_shared_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store volatile half %val, ptr addrspace(3) %addr
    ret void
}

define void @notatomic_bfloat_shared(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: notatomic_bfloat_shared(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [notatomic_bfloat_shared_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_bfloat_shared_param_1];
; CHECK-NEXT:    st.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store bfloat %val, ptr addrspace(3) %addr
    ret void
}

define void @notatomic_bfloat_shared_volatile(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: notatomic_bfloat_shared_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [notatomic_bfloat_shared_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_bfloat_shared_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store volatile bfloat %val, ptr addrspace(3) %addr
    ret void
}

define void @notatomic_float_shared(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: notatomic_float_shared(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [notatomic_float_shared_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_float_shared_param_1];
; CHECK-NEXT:    st.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store float %val, ptr addrspace(3) %addr
    ret void
}

define void @notatomic_float_shared_volatile(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: notatomic_float_shared_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [notatomic_float_shared_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_float_shared_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store volatile float %val, ptr addrspace(3) %addr
    ret void
}

define void @notatomic_double_shared(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: notatomic_double_shared(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_double_shared_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [notatomic_double_shared_param_1];
; CHECK-NEXT:    st.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store double %val, ptr addrspace(3) %addr
    ret void
}

define void @notatomic_double_shared_volatile(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: notatomic_double_shared_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_double_shared_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [notatomic_double_shared_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store volatile double %val, ptr addrspace(3) %addr
    ret void
}

define void @notatomic_i8_local(i8 %val) {
; CHECK-LABEL: notatomic_i8_local(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot54[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot54;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [notatomic_i8_local_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store i8 %val, ptr addrspace(5) %slot
    ret void
}

define void @notatomic_i8_local_volatile(i8 %val) {
; CHECK-LABEL: notatomic_i8_local_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot55[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot55;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [notatomic_i8_local_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store volatile i8 %val, ptr addrspace(5) %slot
    ret void
}

define void @notatomic_i16_local(i16 %val) {
; CHECK-LABEL: notatomic_i16_local(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot56[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot56;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [notatomic_i16_local_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store i16 %val, ptr addrspace(5) %slot
    ret void
}

define void @notatomic_i16_local_volatile(i16 %val) {
; CHECK-LABEL: notatomic_i16_local_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot57[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot57;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [notatomic_i16_local_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store volatile i16 %val, ptr addrspace(5) %slot
    ret void
}

define void @notatomic_i32_local(i32 %val) {
; CHECK-LABEL: notatomic_i32_local(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot58[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot58;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [notatomic_i32_local_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store i32 %val, ptr addrspace(5) %slot
    ret void
}

define void @notatomic_i32_local_volatile(i32 %val) {
; CHECK-LABEL: notatomic_i32_local_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot59[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot59;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [notatomic_i32_local_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store volatile i32 %val, ptr addrspace(5) %slot
    ret void
}

define void @notatomic_i64_local(i64 %val) {
; CHECK-LABEL: notatomic_i64_local(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot60[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot60;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_i64_local_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store i64 %val, ptr addrspace(5) %slot
    ret void
}

define void @notatomic_i64_local_volatile(i64 %val) {
; CHECK-LABEL: notatomic_i64_local_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot61[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot61;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_i64_local_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store volatile i64 %val, ptr addrspace(5) %slot
    ret void
}

define void @notatomic_i128_local(i128 %val) {
; CHECK-LABEL: notatomic_i128_local(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot62[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot62;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [notatomic_i128_local_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store i128 %val, ptr addrspace(5) %slot
    ret void
}

define void @notatomic_i128_local_volatile(i128 %val) {
; CHECK-LABEL: notatomic_i128_local_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot63[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot63;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [notatomic_i128_local_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store volatile i128 %val, ptr addrspace(5) %slot
    ret void
}

define void @notatomic_half_local(half %val) {
; CHECK-LABEL: notatomic_half_local(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot64[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot64;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [notatomic_half_local_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store half %val, ptr addrspace(5) %slot
    ret void
}

define void @notatomic_half_local_volatile(half %val) {
; CHECK-LABEL: notatomic_half_local_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot65[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot65;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [notatomic_half_local_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store volatile half %val, ptr addrspace(5) %slot
    ret void
}

define void @notatomic_bfloat_local(bfloat %val) {
; CHECK-LABEL: notatomic_bfloat_local(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot66[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot66;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [notatomic_bfloat_local_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store bfloat %val, ptr addrspace(5) %slot
    ret void
}

define void @notatomic_bfloat_local_volatile(bfloat %val) {
; CHECK-LABEL: notatomic_bfloat_local_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot67[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot67;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [notatomic_bfloat_local_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store volatile bfloat %val, ptr addrspace(5) %slot
    ret void
}

define void @notatomic_float_local(float %val) {
; CHECK-LABEL: notatomic_float_local(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot68[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot68;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [notatomic_float_local_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store float %val, ptr addrspace(5) %slot
    ret void
}

define void @notatomic_float_local_volatile(float %val) {
; CHECK-LABEL: notatomic_float_local_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot69[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot69;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [notatomic_float_local_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store volatile float %val, ptr addrspace(5) %slot
    ret void
}

define void @notatomic_double_local(double %val) {
; CHECK-LABEL: notatomic_double_local(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot70[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot70;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_double_local_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store double %val, ptr addrspace(5) %slot
    ret void
}

define void @notatomic_double_local_volatile(double %val) {
; CHECK-LABEL: notatomic_double_local_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot71[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot71;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [notatomic_double_local_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store volatile double %val, ptr addrspace(5) %slot
    ret void
}

define void @unordered_i8_generic_sys(i8 %val, ptr %addr) {
; CHECK-LABEL: unordered_i8_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_generic_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i8_generic_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr %addr syncscope("") unordered, align 1
    ret void
}

define void @unordered_i8_generic_cta(i8 %val, ptr %addr) {
; CHECK-LABEL: unordered_i8_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_generic_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i8_generic_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr %addr syncscope("block") unordered, align 1
    ret void
}

define void @unordered_i8_generic_cluster(i8 %val, ptr %addr) {
; CHECK-LABEL: unordered_i8_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_generic_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i8_generic_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr %addr syncscope("cluster") unordered, align 1
    ret void
}

define void @unordered_i8_generic_gpu(i8 %val, ptr %addr) {
; CHECK-LABEL: unordered_i8_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_generic_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i8_generic_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr %addr syncscope("device") unordered, align 1
    ret void
}

define void @unordered_i8_generic_sys_volatile(i8 %val, ptr %addr) {
; CHECK-LABEL: unordered_i8_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_generic_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i8_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr %addr syncscope("") unordered, align 1
    ret void
}

define void @unordered_i8_generic_cta_volatile(i8 %val, ptr %addr) {
; CHECK-LABEL: unordered_i8_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_generic_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i8_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr %addr syncscope("block") unordered, align 1
    ret void
}

define void @unordered_i8_generic_cluster_volatile(i8 %val, ptr %addr) {
; CHECK-LABEL: unordered_i8_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_generic_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i8_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr %addr syncscope("cluster") unordered, align 1
    ret void
}

define void @unordered_i8_generic_gpu_volatile(i8 %val, ptr %addr) {
; CHECK-LABEL: unordered_i8_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_generic_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i8_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr %addr syncscope("device") unordered, align 1
    ret void
}

define void @unordered_i16_generic_sys(i16 %val, ptr %addr) {
; CHECK-LABEL: unordered_i16_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_generic_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i16_generic_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr %addr syncscope("") unordered, align 2
    ret void
}

define void @unordered_i16_generic_cta(i16 %val, ptr %addr) {
; CHECK-LABEL: unordered_i16_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_generic_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i16_generic_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr %addr syncscope("block") unordered, align 2
    ret void
}

define void @unordered_i16_generic_cluster(i16 %val, ptr %addr) {
; CHECK-LABEL: unordered_i16_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_generic_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i16_generic_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr %addr syncscope("cluster") unordered, align 2
    ret void
}

define void @unordered_i16_generic_gpu(i16 %val, ptr %addr) {
; CHECK-LABEL: unordered_i16_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_generic_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i16_generic_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr %addr syncscope("device") unordered, align 2
    ret void
}

define void @unordered_i16_generic_sys_volatile(i16 %val, ptr %addr) {
; CHECK-LABEL: unordered_i16_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_generic_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i16_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr %addr syncscope("") unordered, align 2
    ret void
}

define void @unordered_i16_generic_cta_volatile(i16 %val, ptr %addr) {
; CHECK-LABEL: unordered_i16_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_generic_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i16_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr %addr syncscope("block") unordered, align 2
    ret void
}

define void @unordered_i16_generic_cluster_volatile(i16 %val, ptr %addr) {
; CHECK-LABEL: unordered_i16_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_generic_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i16_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr %addr syncscope("cluster") unordered, align 2
    ret void
}

define void @unordered_i16_generic_gpu_volatile(i16 %val, ptr %addr) {
; CHECK-LABEL: unordered_i16_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_generic_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i16_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr %addr syncscope("device") unordered, align 2
    ret void
}

define void @unordered_i32_generic_sys(i32 %val, ptr %addr) {
; CHECK-LABEL: unordered_i32_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_i32_generic_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i32_generic_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr %addr syncscope("") unordered, align 4
    ret void
}

define void @unordered_i32_generic_cta(i32 %val, ptr %addr) {
; CHECK-LABEL: unordered_i32_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_i32_generic_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i32_generic_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr %addr syncscope("block") unordered, align 4
    ret void
}

define void @unordered_i32_generic_cluster(i32 %val, ptr %addr) {
; CHECK-LABEL: unordered_i32_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_i32_generic_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i32_generic_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr %addr syncscope("cluster") unordered, align 4
    ret void
}

define void @unordered_i32_generic_gpu(i32 %val, ptr %addr) {
; CHECK-LABEL: unordered_i32_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_i32_generic_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i32_generic_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr %addr syncscope("device") unordered, align 4
    ret void
}

define void @unordered_i32_generic_sys_volatile(i32 %val, ptr %addr) {
; CHECK-LABEL: unordered_i32_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_i32_generic_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i32_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr %addr syncscope("") unordered, align 4
    ret void
}

define void @unordered_i32_generic_cta_volatile(i32 %val, ptr %addr) {
; CHECK-LABEL: unordered_i32_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_i32_generic_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i32_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr %addr syncscope("block") unordered, align 4
    ret void
}

define void @unordered_i32_generic_cluster_volatile(i32 %val, ptr %addr) {
; CHECK-LABEL: unordered_i32_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_i32_generic_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i32_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr %addr syncscope("cluster") unordered, align 4
    ret void
}

define void @unordered_i32_generic_gpu_volatile(i32 %val, ptr %addr) {
; CHECK-LABEL: unordered_i32_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_i32_generic_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i32_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr %addr syncscope("device") unordered, align 4
    ret void
}

define void @unordered_i64_generic_sys(i64 %val, ptr %addr) {
; CHECK-LABEL: unordered_i64_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_generic_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_i64_generic_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr %addr syncscope("") unordered, align 8
    ret void
}

define void @unordered_i64_generic_cta(i64 %val, ptr %addr) {
; CHECK-LABEL: unordered_i64_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_generic_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_i64_generic_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr %addr syncscope("block") unordered, align 8
    ret void
}

define void @unordered_i64_generic_cluster(i64 %val, ptr %addr) {
; CHECK-LABEL: unordered_i64_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_generic_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_i64_generic_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr %addr syncscope("cluster") unordered, align 8
    ret void
}

define void @unordered_i64_generic_gpu(i64 %val, ptr %addr) {
; CHECK-LABEL: unordered_i64_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_generic_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_i64_generic_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr %addr syncscope("device") unordered, align 8
    ret void
}

define void @unordered_i64_generic_sys_volatile(i64 %val, ptr %addr) {
; CHECK-LABEL: unordered_i64_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_generic_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_i64_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr %addr syncscope("") unordered, align 8
    ret void
}

define void @unordered_i64_generic_cta_volatile(i64 %val, ptr %addr) {
; CHECK-LABEL: unordered_i64_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_generic_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_i64_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr %addr syncscope("block") unordered, align 8
    ret void
}

define void @unordered_i64_generic_cluster_volatile(i64 %val, ptr %addr) {
; CHECK-LABEL: unordered_i64_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_generic_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_i64_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr %addr syncscope("cluster") unordered, align 8
    ret void
}

define void @unordered_i64_generic_gpu_volatile(i64 %val, ptr %addr) {
; CHECK-LABEL: unordered_i64_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_generic_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_i64_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr %addr syncscope("device") unordered, align 8
    ret void
}

define void @unordered_i128_generic_sys(i128 %val, ptr %addr) {
; CHECK-LABEL: unordered_i128_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_generic_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [unordered_i128_generic_sys_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.sys.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr %addr syncscope("") unordered, align 16
    ret void
}

define void @unordered_i128_generic_cta(i128 %val, ptr %addr) {
; CHECK-LABEL: unordered_i128_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_generic_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [unordered_i128_generic_cta_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cta.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr %addr syncscope("block") unordered, align 16
    ret void
}

define void @unordered_i128_generic_cluster(i128 %val, ptr %addr) {
; CHECK-LABEL: unordered_i128_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_generic_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [unordered_i128_generic_cluster_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cluster.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr %addr syncscope("cluster") unordered, align 16
    ret void
}

define void @unordered_i128_generic_gpu(i128 %val, ptr %addr) {
; CHECK-LABEL: unordered_i128_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_generic_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [unordered_i128_generic_gpu_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.gpu.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr %addr syncscope("device") unordered, align 16
    ret void
}

define void @unordered_i128_generic_sys_volatile(i128 %val, ptr %addr) {
; CHECK-LABEL: unordered_i128_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_generic_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [unordered_i128_generic_sys_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.sys.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr %addr syncscope("") unordered, align 16
    ret void
}

define void @unordered_i128_generic_cta_volatile(i128 %val, ptr %addr) {
; CHECK-LABEL: unordered_i128_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_generic_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [unordered_i128_generic_cta_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cta.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr %addr syncscope("block") unordered, align 16
    ret void
}

define void @unordered_i128_generic_cluster_volatile(i128 %val, ptr %addr) {
; CHECK-LABEL: unordered_i128_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_generic_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [unordered_i128_generic_cluster_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cluster.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr %addr syncscope("cluster") unordered, align 16
    ret void
}

define void @unordered_i128_generic_gpu_volatile(i128 %val, ptr %addr) {
; CHECK-LABEL: unordered_i128_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_generic_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [unordered_i128_generic_gpu_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.gpu.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr %addr syncscope("device") unordered, align 16
    ret void
}

define void @unordered_half_generic_sys(half %val, ptr %addr) {
; CHECK-LABEL: unordered_half_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_generic_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_half_generic_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr %addr syncscope("") unordered, align 2
    ret void
}

define void @unordered_half_generic_cta(half %val, ptr %addr) {
; CHECK-LABEL: unordered_half_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_generic_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_half_generic_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr %addr syncscope("block") unordered, align 2
    ret void
}

define void @unordered_half_generic_cluster(half %val, ptr %addr) {
; CHECK-LABEL: unordered_half_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_generic_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_half_generic_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr %addr syncscope("cluster") unordered, align 2
    ret void
}

define void @unordered_half_generic_gpu(half %val, ptr %addr) {
; CHECK-LABEL: unordered_half_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_generic_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_half_generic_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr %addr syncscope("device") unordered, align 2
    ret void
}

define void @unordered_half_generic_sys_volatile(half %val, ptr %addr) {
; CHECK-LABEL: unordered_half_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_generic_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_half_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr %addr syncscope("") unordered, align 2
    ret void
}

define void @unordered_half_generic_cta_volatile(half %val, ptr %addr) {
; CHECK-LABEL: unordered_half_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_generic_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_half_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr %addr syncscope("block") unordered, align 2
    ret void
}

define void @unordered_half_generic_cluster_volatile(half %val, ptr %addr) {
; CHECK-LABEL: unordered_half_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_generic_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_half_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr %addr syncscope("cluster") unordered, align 2
    ret void
}

define void @unordered_half_generic_gpu_volatile(half %val, ptr %addr) {
; CHECK-LABEL: unordered_half_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_generic_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_half_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr %addr syncscope("device") unordered, align 2
    ret void
}

define void @unordered_bfloat_generic_sys(bfloat %val, ptr %addr) {
; CHECK-LABEL: unordered_bfloat_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_generic_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_bfloat_generic_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr %addr syncscope("") unordered, align 2
    ret void
}

define void @unordered_bfloat_generic_cta(bfloat %val, ptr %addr) {
; CHECK-LABEL: unordered_bfloat_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_generic_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_bfloat_generic_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr %addr syncscope("block") unordered, align 2
    ret void
}

define void @unordered_bfloat_generic_cluster(bfloat %val, ptr %addr) {
; CHECK-LABEL: unordered_bfloat_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_generic_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_bfloat_generic_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr %addr syncscope("cluster") unordered, align 2
    ret void
}

define void @unordered_bfloat_generic_gpu(bfloat %val, ptr %addr) {
; CHECK-LABEL: unordered_bfloat_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_generic_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_bfloat_generic_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr %addr syncscope("device") unordered, align 2
    ret void
}

define void @unordered_bfloat_generic_sys_volatile(bfloat %val, ptr %addr) {
; CHECK-LABEL: unordered_bfloat_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_generic_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_bfloat_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr %addr syncscope("") unordered, align 2
    ret void
}

define void @unordered_bfloat_generic_cta_volatile(bfloat %val, ptr %addr) {
; CHECK-LABEL: unordered_bfloat_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_generic_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_bfloat_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr %addr syncscope("block") unordered, align 2
    ret void
}

define void @unordered_bfloat_generic_cluster_volatile(bfloat %val, ptr %addr) {
; CHECK-LABEL: unordered_bfloat_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_generic_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_bfloat_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr %addr syncscope("cluster") unordered, align 2
    ret void
}

define void @unordered_bfloat_generic_gpu_volatile(bfloat %val, ptr %addr) {
; CHECK-LABEL: unordered_bfloat_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_generic_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_bfloat_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr %addr syncscope("device") unordered, align 2
    ret void
}

define void @unordered_float_generic_sys(float %val, ptr %addr) {
; CHECK-LABEL: unordered_float_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_float_generic_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_float_generic_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr %addr syncscope("") unordered, align 4
    ret void
}

define void @unordered_float_generic_cta(float %val, ptr %addr) {
; CHECK-LABEL: unordered_float_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_float_generic_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_float_generic_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr %addr syncscope("block") unordered, align 4
    ret void
}

define void @unordered_float_generic_cluster(float %val, ptr %addr) {
; CHECK-LABEL: unordered_float_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_float_generic_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_float_generic_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr %addr syncscope("cluster") unordered, align 4
    ret void
}

define void @unordered_float_generic_gpu(float %val, ptr %addr) {
; CHECK-LABEL: unordered_float_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_float_generic_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_float_generic_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr %addr syncscope("device") unordered, align 4
    ret void
}

define void @unordered_float_generic_sys_volatile(float %val, ptr %addr) {
; CHECK-LABEL: unordered_float_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_float_generic_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_float_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr %addr syncscope("") unordered, align 4
    ret void
}

define void @unordered_float_generic_cta_volatile(float %val, ptr %addr) {
; CHECK-LABEL: unordered_float_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_float_generic_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_float_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr %addr syncscope("block") unordered, align 4
    ret void
}

define void @unordered_float_generic_cluster_volatile(float %val, ptr %addr) {
; CHECK-LABEL: unordered_float_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_float_generic_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_float_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr %addr syncscope("cluster") unordered, align 4
    ret void
}

define void @unordered_float_generic_gpu_volatile(float %val, ptr %addr) {
; CHECK-LABEL: unordered_float_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_float_generic_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_float_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr %addr syncscope("device") unordered, align 4
    ret void
}

define void @unordered_double_generic_sys(double %val, ptr %addr) {
; CHECK-LABEL: unordered_double_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_generic_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_double_generic_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr %addr syncscope("") unordered, align 8
    ret void
}

define void @unordered_double_generic_cta(double %val, ptr %addr) {
; CHECK-LABEL: unordered_double_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_generic_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_double_generic_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr %addr syncscope("block") unordered, align 8
    ret void
}

define void @unordered_double_generic_cluster(double %val, ptr %addr) {
; CHECK-LABEL: unordered_double_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_generic_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_double_generic_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr %addr syncscope("cluster") unordered, align 8
    ret void
}

define void @unordered_double_generic_gpu(double %val, ptr %addr) {
; CHECK-LABEL: unordered_double_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_generic_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_double_generic_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr %addr syncscope("device") unordered, align 8
    ret void
}

define void @unordered_double_generic_sys_volatile(double %val, ptr %addr) {
; CHECK-LABEL: unordered_double_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_generic_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_double_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr %addr syncscope("") unordered, align 8
    ret void
}

define void @unordered_double_generic_cta_volatile(double %val, ptr %addr) {
; CHECK-LABEL: unordered_double_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_generic_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_double_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr %addr syncscope("block") unordered, align 8
    ret void
}

define void @unordered_double_generic_cluster_volatile(double %val, ptr %addr) {
; CHECK-LABEL: unordered_double_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_generic_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_double_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr %addr syncscope("cluster") unordered, align 8
    ret void
}

define void @unordered_double_generic_gpu_volatile(double %val, ptr %addr) {
; CHECK-LABEL: unordered_double_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_generic_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_double_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr %addr syncscope("device") unordered, align 8
    ret void
}

define void @unordered_i8_global_sys(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i8_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_global_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i8_global_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(1) %addr syncscope("") unordered, align 1
    ret void
}

define void @unordered_i8_global_cta(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i8_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_global_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i8_global_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(1) %addr syncscope("block") unordered, align 1
    ret void
}

define void @unordered_i8_global_cluster(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i8_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_global_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i8_global_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(1) %addr syncscope("cluster") unordered, align 1
    ret void
}

define void @unordered_i8_global_gpu(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i8_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_global_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i8_global_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(1) %addr syncscope("device") unordered, align 1
    ret void
}

define void @unordered_i8_global_sys_volatile(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i8_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_global_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i8_global_sys_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(1) %addr syncscope("") unordered, align 1
    ret void
}

define void @unordered_i8_global_cta_volatile(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i8_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_global_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i8_global_cta_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(1) %addr syncscope("block") unordered, align 1
    ret void
}

define void @unordered_i8_global_cluster_volatile(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i8_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_global_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i8_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(1) %addr syncscope("cluster") unordered, align 1
    ret void
}

define void @unordered_i8_global_gpu_volatile(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i8_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_global_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i8_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(1) %addr syncscope("device") unordered, align 1
    ret void
}

define void @unordered_i16_global_sys(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i16_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_global_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i16_global_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(1) %addr syncscope("") unordered, align 2
    ret void
}

define void @unordered_i16_global_cta(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i16_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_global_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i16_global_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(1) %addr syncscope("block") unordered, align 2
    ret void
}

define void @unordered_i16_global_cluster(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i16_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_global_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i16_global_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(1) %addr syncscope("cluster") unordered, align 2
    ret void
}

define void @unordered_i16_global_gpu(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i16_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_global_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i16_global_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(1) %addr syncscope("device") unordered, align 2
    ret void
}

define void @unordered_i16_global_sys_volatile(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i16_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_global_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i16_global_sys_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(1) %addr syncscope("") unordered, align 2
    ret void
}

define void @unordered_i16_global_cta_volatile(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i16_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_global_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i16_global_cta_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(1) %addr syncscope("block") unordered, align 2
    ret void
}

define void @unordered_i16_global_cluster_volatile(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i16_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_global_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i16_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(1) %addr syncscope("cluster") unordered, align 2
    ret void
}

define void @unordered_i16_global_gpu_volatile(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i16_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_global_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i16_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(1) %addr syncscope("device") unordered, align 2
    ret void
}

define void @unordered_i32_global_sys(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i32_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_i32_global_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i32_global_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(1) %addr syncscope("") unordered, align 4
    ret void
}

define void @unordered_i32_global_cta(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i32_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_i32_global_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i32_global_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(1) %addr syncscope("block") unordered, align 4
    ret void
}

define void @unordered_i32_global_cluster(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i32_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_i32_global_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i32_global_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(1) %addr syncscope("cluster") unordered, align 4
    ret void
}

define void @unordered_i32_global_gpu(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i32_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_i32_global_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i32_global_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(1) %addr syncscope("device") unordered, align 4
    ret void
}

define void @unordered_i32_global_sys_volatile(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i32_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_i32_global_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i32_global_sys_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(1) %addr syncscope("") unordered, align 4
    ret void
}

define void @unordered_i32_global_cta_volatile(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i32_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_i32_global_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i32_global_cta_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(1) %addr syncscope("block") unordered, align 4
    ret void
}

define void @unordered_i32_global_cluster_volatile(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i32_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_i32_global_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i32_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(1) %addr syncscope("cluster") unordered, align 4
    ret void
}

define void @unordered_i32_global_gpu_volatile(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i32_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_i32_global_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i32_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(1) %addr syncscope("device") unordered, align 4
    ret void
}

define void @unordered_i64_global_sys(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i64_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_global_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_i64_global_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(1) %addr syncscope("") unordered, align 8
    ret void
}

define void @unordered_i64_global_cta(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i64_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_global_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_i64_global_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(1) %addr syncscope("block") unordered, align 8
    ret void
}

define void @unordered_i64_global_cluster(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i64_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_global_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_i64_global_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(1) %addr syncscope("cluster") unordered, align 8
    ret void
}

define void @unordered_i64_global_gpu(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i64_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_global_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_i64_global_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(1) %addr syncscope("device") unordered, align 8
    ret void
}

define void @unordered_i64_global_sys_volatile(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i64_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_global_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_i64_global_sys_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(1) %addr syncscope("") unordered, align 8
    ret void
}

define void @unordered_i64_global_cta_volatile(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i64_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_global_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_i64_global_cta_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(1) %addr syncscope("block") unordered, align 8
    ret void
}

define void @unordered_i64_global_cluster_volatile(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i64_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_global_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_i64_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(1) %addr syncscope("cluster") unordered, align 8
    ret void
}

define void @unordered_i64_global_gpu_volatile(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i64_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_global_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_i64_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(1) %addr syncscope("device") unordered, align 8
    ret void
}

define void @unordered_i128_global_sys(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i128_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_global_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [unordered_i128_global_sys_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.sys.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(1) %addr syncscope("") unordered, align 16
    ret void
}

define void @unordered_i128_global_cta(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i128_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_global_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [unordered_i128_global_cta_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cta.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(1) %addr syncscope("block") unordered, align 16
    ret void
}

define void @unordered_i128_global_cluster(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i128_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_global_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [unordered_i128_global_cluster_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cluster.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(1) %addr syncscope("cluster") unordered, align 16
    ret void
}

define void @unordered_i128_global_gpu(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i128_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_global_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [unordered_i128_global_gpu_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.gpu.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(1) %addr syncscope("device") unordered, align 16
    ret void
}

define void @unordered_i128_global_sys_volatile(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i128_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_global_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [unordered_i128_global_sys_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.sys.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(1) %addr syncscope("") unordered, align 16
    ret void
}

define void @unordered_i128_global_cta_volatile(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i128_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_global_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [unordered_i128_global_cta_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cta.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(1) %addr syncscope("block") unordered, align 16
    ret void
}

define void @unordered_i128_global_cluster_volatile(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i128_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_global_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [unordered_i128_global_cluster_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cluster.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(1) %addr syncscope("cluster") unordered, align 16
    ret void
}

define void @unordered_i128_global_gpu_volatile(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_i128_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_global_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [unordered_i128_global_gpu_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.gpu.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(1) %addr syncscope("device") unordered, align 16
    ret void
}

define void @unordered_half_global_sys(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_half_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_global_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_half_global_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(1) %addr syncscope("") unordered, align 2
    ret void
}

define void @unordered_half_global_cta(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_half_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_global_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_half_global_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(1) %addr syncscope("block") unordered, align 2
    ret void
}

define void @unordered_half_global_cluster(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_half_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_global_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_half_global_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(1) %addr syncscope("cluster") unordered, align 2
    ret void
}

define void @unordered_half_global_gpu(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_half_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_global_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_half_global_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(1) %addr syncscope("device") unordered, align 2
    ret void
}

define void @unordered_half_global_sys_volatile(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_half_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_global_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_half_global_sys_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(1) %addr syncscope("") unordered, align 2
    ret void
}

define void @unordered_half_global_cta_volatile(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_half_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_global_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_half_global_cta_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(1) %addr syncscope("block") unordered, align 2
    ret void
}

define void @unordered_half_global_cluster_volatile(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_half_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_global_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_half_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(1) %addr syncscope("cluster") unordered, align 2
    ret void
}

define void @unordered_half_global_gpu_volatile(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_half_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_global_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_half_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(1) %addr syncscope("device") unordered, align 2
    ret void
}

define void @unordered_bfloat_global_sys(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_bfloat_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_global_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_bfloat_global_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(1) %addr syncscope("") unordered, align 2
    ret void
}

define void @unordered_bfloat_global_cta(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_bfloat_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_global_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_bfloat_global_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(1) %addr syncscope("block") unordered, align 2
    ret void
}

define void @unordered_bfloat_global_cluster(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_bfloat_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_global_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_bfloat_global_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(1) %addr syncscope("cluster") unordered, align 2
    ret void
}

define void @unordered_bfloat_global_gpu(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_bfloat_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_global_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_bfloat_global_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(1) %addr syncscope("device") unordered, align 2
    ret void
}

define void @unordered_bfloat_global_sys_volatile(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_bfloat_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_global_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_bfloat_global_sys_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(1) %addr syncscope("") unordered, align 2
    ret void
}

define void @unordered_bfloat_global_cta_volatile(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_bfloat_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_global_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_bfloat_global_cta_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(1) %addr syncscope("block") unordered, align 2
    ret void
}

define void @unordered_bfloat_global_cluster_volatile(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_bfloat_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_global_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_bfloat_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(1) %addr syncscope("cluster") unordered, align 2
    ret void
}

define void @unordered_bfloat_global_gpu_volatile(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_bfloat_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_global_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_bfloat_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(1) %addr syncscope("device") unordered, align 2
    ret void
}

define void @unordered_float_global_sys(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_float_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_float_global_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_float_global_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(1) %addr syncscope("") unordered, align 4
    ret void
}

define void @unordered_float_global_cta(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_float_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_float_global_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_float_global_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(1) %addr syncscope("block") unordered, align 4
    ret void
}

define void @unordered_float_global_cluster(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_float_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_float_global_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_float_global_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(1) %addr syncscope("cluster") unordered, align 4
    ret void
}

define void @unordered_float_global_gpu(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_float_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_float_global_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_float_global_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(1) %addr syncscope("device") unordered, align 4
    ret void
}

define void @unordered_float_global_sys_volatile(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_float_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_float_global_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_float_global_sys_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(1) %addr syncscope("") unordered, align 4
    ret void
}

define void @unordered_float_global_cta_volatile(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_float_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_float_global_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_float_global_cta_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(1) %addr syncscope("block") unordered, align 4
    ret void
}

define void @unordered_float_global_cluster_volatile(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_float_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_float_global_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_float_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(1) %addr syncscope("cluster") unordered, align 4
    ret void
}

define void @unordered_float_global_gpu_volatile(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_float_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_float_global_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_float_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(1) %addr syncscope("device") unordered, align 4
    ret void
}

define void @unordered_double_global_sys(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_double_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_global_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_double_global_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(1) %addr syncscope("") unordered, align 8
    ret void
}

define void @unordered_double_global_cta(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_double_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_global_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_double_global_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(1) %addr syncscope("block") unordered, align 8
    ret void
}

define void @unordered_double_global_cluster(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_double_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_global_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_double_global_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(1) %addr syncscope("cluster") unordered, align 8
    ret void
}

define void @unordered_double_global_gpu(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_double_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_global_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_double_global_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(1) %addr syncscope("device") unordered, align 8
    ret void
}

define void @unordered_double_global_sys_volatile(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_double_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_global_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_double_global_sys_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(1) %addr syncscope("") unordered, align 8
    ret void
}

define void @unordered_double_global_cta_volatile(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_double_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_global_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_double_global_cta_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(1) %addr syncscope("block") unordered, align 8
    ret void
}

define void @unordered_double_global_cluster_volatile(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_double_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_global_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_double_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(1) %addr syncscope("cluster") unordered, align 8
    ret void
}

define void @unordered_double_global_gpu_volatile(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: unordered_double_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_global_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_double_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(1) %addr syncscope("device") unordered, align 8
    ret void
}

define void @unordered_i8_shared_sys(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i8_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_shared_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i8_shared_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(3) %addr syncscope("") unordered, align 1
    ret void
}

define void @unordered_i8_shared_cta(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i8_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_shared_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i8_shared_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(3) %addr syncscope("block") unordered, align 1
    ret void
}

define void @unordered_i8_shared_cluster(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i8_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_shared_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i8_shared_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(3) %addr syncscope("cluster") unordered, align 1
    ret void
}

define void @unordered_i8_shared_gpu(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i8_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_shared_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i8_shared_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(3) %addr syncscope("device") unordered, align 1
    ret void
}

define void @unordered_i8_shared_sys_volatile(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i8_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_shared_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i8_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(3) %addr syncscope("") unordered, align 1
    ret void
}

define void @unordered_i8_shared_cta_volatile(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i8_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_shared_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i8_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(3) %addr syncscope("block") unordered, align 1
    ret void
}

define void @unordered_i8_shared_cluster_volatile(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i8_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_shared_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i8_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(3) %addr syncscope("cluster") unordered, align 1
    ret void
}

define void @unordered_i8_shared_gpu_volatile(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i8_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_shared_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i8_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(3) %addr syncscope("device") unordered, align 1
    ret void
}

define void @unordered_i16_shared_sys(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i16_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_shared_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i16_shared_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(3) %addr syncscope("") unordered, align 2
    ret void
}

define void @unordered_i16_shared_cta(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i16_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_shared_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i16_shared_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(3) %addr syncscope("block") unordered, align 2
    ret void
}

define void @unordered_i16_shared_cluster(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i16_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_shared_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i16_shared_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(3) %addr syncscope("cluster") unordered, align 2
    ret void
}

define void @unordered_i16_shared_gpu(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i16_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_shared_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i16_shared_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(3) %addr syncscope("device") unordered, align 2
    ret void
}

define void @unordered_i16_shared_sys_volatile(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i16_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_shared_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i16_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(3) %addr syncscope("") unordered, align 2
    ret void
}

define void @unordered_i16_shared_cta_volatile(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i16_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_shared_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i16_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(3) %addr syncscope("block") unordered, align 2
    ret void
}

define void @unordered_i16_shared_cluster_volatile(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i16_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_shared_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i16_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(3) %addr syncscope("cluster") unordered, align 2
    ret void
}

define void @unordered_i16_shared_gpu_volatile(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i16_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_shared_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i16_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(3) %addr syncscope("device") unordered, align 2
    ret void
}

define void @unordered_i32_shared_sys(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i32_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_i32_shared_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i32_shared_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(3) %addr syncscope("") unordered, align 4
    ret void
}

define void @unordered_i32_shared_cta(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i32_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_i32_shared_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i32_shared_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(3) %addr syncscope("block") unordered, align 4
    ret void
}

define void @unordered_i32_shared_cluster(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i32_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_i32_shared_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i32_shared_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(3) %addr syncscope("cluster") unordered, align 4
    ret void
}

define void @unordered_i32_shared_gpu(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i32_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_i32_shared_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i32_shared_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(3) %addr syncscope("device") unordered, align 4
    ret void
}

define void @unordered_i32_shared_sys_volatile(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i32_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_i32_shared_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i32_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(3) %addr syncscope("") unordered, align 4
    ret void
}

define void @unordered_i32_shared_cta_volatile(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i32_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_i32_shared_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i32_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(3) %addr syncscope("block") unordered, align 4
    ret void
}

define void @unordered_i32_shared_cluster_volatile(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i32_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_i32_shared_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i32_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(3) %addr syncscope("cluster") unordered, align 4
    ret void
}

define void @unordered_i32_shared_gpu_volatile(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i32_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_i32_shared_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i32_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(3) %addr syncscope("device") unordered, align 4
    ret void
}

define void @unordered_i64_shared_sys(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i64_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_shared_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_i64_shared_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(3) %addr syncscope("") unordered, align 8
    ret void
}

define void @unordered_i64_shared_cta(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i64_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_shared_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_i64_shared_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(3) %addr syncscope("block") unordered, align 8
    ret void
}

define void @unordered_i64_shared_cluster(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i64_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_shared_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_i64_shared_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(3) %addr syncscope("cluster") unordered, align 8
    ret void
}

define void @unordered_i64_shared_gpu(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i64_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_shared_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_i64_shared_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(3) %addr syncscope("device") unordered, align 8
    ret void
}

define void @unordered_i64_shared_sys_volatile(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i64_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_shared_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_i64_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(3) %addr syncscope("") unordered, align 8
    ret void
}

define void @unordered_i64_shared_cta_volatile(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i64_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_shared_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_i64_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(3) %addr syncscope("block") unordered, align 8
    ret void
}

define void @unordered_i64_shared_cluster_volatile(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i64_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_shared_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_i64_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(3) %addr syncscope("cluster") unordered, align 8
    ret void
}

define void @unordered_i64_shared_gpu_volatile(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i64_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_shared_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_i64_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(3) %addr syncscope("device") unordered, align 8
    ret void
}

define void @unordered_i128_shared_sys(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i128_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_shared_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [unordered_i128_shared_sys_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.sys.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(3) %addr syncscope("") unordered, align 16
    ret void
}

define void @unordered_i128_shared_cta(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i128_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_shared_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [unordered_i128_shared_cta_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cta.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(3) %addr syncscope("block") unordered, align 16
    ret void
}

define void @unordered_i128_shared_cluster(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i128_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_shared_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [unordered_i128_shared_cluster_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cluster.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(3) %addr syncscope("cluster") unordered, align 16
    ret void
}

define void @unordered_i128_shared_gpu(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i128_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_shared_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [unordered_i128_shared_gpu_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.gpu.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(3) %addr syncscope("device") unordered, align 16
    ret void
}

define void @unordered_i128_shared_sys_volatile(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i128_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_shared_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [unordered_i128_shared_sys_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.sys.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(3) %addr syncscope("") unordered, align 16
    ret void
}

define void @unordered_i128_shared_cta_volatile(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i128_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_shared_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [unordered_i128_shared_cta_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cta.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(3) %addr syncscope("block") unordered, align 16
    ret void
}

define void @unordered_i128_shared_cluster_volatile(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i128_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_shared_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [unordered_i128_shared_cluster_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cluster.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(3) %addr syncscope("cluster") unordered, align 16
    ret void
}

define void @unordered_i128_shared_gpu_volatile(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_i128_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_shared_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [unordered_i128_shared_gpu_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.gpu.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(3) %addr syncscope("device") unordered, align 16
    ret void
}

define void @unordered_half_shared_sys(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_half_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_shared_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_half_shared_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(3) %addr syncscope("") unordered, align 2
    ret void
}

define void @unordered_half_shared_cta(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_half_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_shared_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_half_shared_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(3) %addr syncscope("block") unordered, align 2
    ret void
}

define void @unordered_half_shared_cluster(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_half_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_shared_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_half_shared_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(3) %addr syncscope("cluster") unordered, align 2
    ret void
}

define void @unordered_half_shared_gpu(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_half_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_shared_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_half_shared_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(3) %addr syncscope("device") unordered, align 2
    ret void
}

define void @unordered_half_shared_sys_volatile(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_half_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_shared_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_half_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(3) %addr syncscope("") unordered, align 2
    ret void
}

define void @unordered_half_shared_cta_volatile(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_half_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_shared_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_half_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(3) %addr syncscope("block") unordered, align 2
    ret void
}

define void @unordered_half_shared_cluster_volatile(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_half_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_shared_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_half_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(3) %addr syncscope("cluster") unordered, align 2
    ret void
}

define void @unordered_half_shared_gpu_volatile(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_half_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_shared_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_half_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(3) %addr syncscope("device") unordered, align 2
    ret void
}

define void @unordered_bfloat_shared_sys(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_bfloat_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_shared_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_bfloat_shared_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(3) %addr syncscope("") unordered, align 2
    ret void
}

define void @unordered_bfloat_shared_cta(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_bfloat_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_shared_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_bfloat_shared_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(3) %addr syncscope("block") unordered, align 2
    ret void
}

define void @unordered_bfloat_shared_cluster(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_bfloat_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_shared_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_bfloat_shared_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(3) %addr syncscope("cluster") unordered, align 2
    ret void
}

define void @unordered_bfloat_shared_gpu(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_bfloat_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_shared_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_bfloat_shared_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(3) %addr syncscope("device") unordered, align 2
    ret void
}

define void @unordered_bfloat_shared_sys_volatile(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_bfloat_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_shared_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_bfloat_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(3) %addr syncscope("") unordered, align 2
    ret void
}

define void @unordered_bfloat_shared_cta_volatile(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_bfloat_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_shared_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_bfloat_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(3) %addr syncscope("block") unordered, align 2
    ret void
}

define void @unordered_bfloat_shared_cluster_volatile(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_bfloat_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_shared_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_bfloat_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(3) %addr syncscope("cluster") unordered, align 2
    ret void
}

define void @unordered_bfloat_shared_gpu_volatile(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_bfloat_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_shared_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_bfloat_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(3) %addr syncscope("device") unordered, align 2
    ret void
}

define void @unordered_float_shared_sys(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_float_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_float_shared_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_float_shared_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(3) %addr syncscope("") unordered, align 4
    ret void
}

define void @unordered_float_shared_cta(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_float_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_float_shared_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_float_shared_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(3) %addr syncscope("block") unordered, align 4
    ret void
}

define void @unordered_float_shared_cluster(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_float_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_float_shared_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_float_shared_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(3) %addr syncscope("cluster") unordered, align 4
    ret void
}

define void @unordered_float_shared_gpu(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_float_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_float_shared_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_float_shared_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(3) %addr syncscope("device") unordered, align 4
    ret void
}

define void @unordered_float_shared_sys_volatile(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_float_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_float_shared_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_float_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(3) %addr syncscope("") unordered, align 4
    ret void
}

define void @unordered_float_shared_cta_volatile(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_float_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_float_shared_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_float_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(3) %addr syncscope("block") unordered, align 4
    ret void
}

define void @unordered_float_shared_cluster_volatile(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_float_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_float_shared_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_float_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(3) %addr syncscope("cluster") unordered, align 4
    ret void
}

define void @unordered_float_shared_gpu_volatile(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_float_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [unordered_float_shared_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_float_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(3) %addr syncscope("device") unordered, align 4
    ret void
}

define void @unordered_double_shared_sys(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_double_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_shared_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_double_shared_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(3) %addr syncscope("") unordered, align 8
    ret void
}

define void @unordered_double_shared_cta(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_double_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_shared_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_double_shared_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(3) %addr syncscope("block") unordered, align 8
    ret void
}

define void @unordered_double_shared_cluster(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_double_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_shared_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_double_shared_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(3) %addr syncscope("cluster") unordered, align 8
    ret void
}

define void @unordered_double_shared_gpu(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_double_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_shared_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_double_shared_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(3) %addr syncscope("device") unordered, align 8
    ret void
}

define void @unordered_double_shared_sys_volatile(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_double_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_shared_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_double_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(3) %addr syncscope("") unordered, align 8
    ret void
}

define void @unordered_double_shared_cta_volatile(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_double_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_shared_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_double_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(3) %addr syncscope("block") unordered, align 8
    ret void
}

define void @unordered_double_shared_cluster_volatile(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_double_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_shared_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_double_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(3) %addr syncscope("cluster") unordered, align 8
    ret void
}

define void @unordered_double_shared_gpu_volatile(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: unordered_double_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_shared_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [unordered_double_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(3) %addr syncscope("device") unordered, align 8
    ret void
}

define void @unordered_i8_local_sys(i8 %val) {
; CHECK-LABEL: unordered_i8_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot288[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot288;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i8 %val, ptr addrspace(5) %slot syncscope("") unordered, align 1
    ret void
}

define void @unordered_i8_local_cta(i8 %val) {
; CHECK-LABEL: unordered_i8_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot289[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot289;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i8 %val, ptr addrspace(5) %slot syncscope("block") unordered, align 1
    ret void
}

define void @unordered_i8_local_cluster(i8 %val) {
; CHECK-LABEL: unordered_i8_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot290[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot290;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i8 %val, ptr addrspace(5) %slot syncscope("cluster") unordered, align 1
    ret void
}

define void @unordered_i8_local_gpu(i8 %val) {
; CHECK-LABEL: unordered_i8_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot291[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot291;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i8 %val, ptr addrspace(5) %slot syncscope("device") unordered, align 1
    ret void
}

define void @unordered_i8_local_sys_volatile(i8 %val) {
; CHECK-LABEL: unordered_i8_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot292[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot292;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i8 %val, ptr addrspace(5) %slot syncscope("") unordered, align 1
    ret void
}

define void @unordered_i8_local_cta_volatile(i8 %val) {
; CHECK-LABEL: unordered_i8_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot293[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot293;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i8 %val, ptr addrspace(5) %slot syncscope("block") unordered, align 1
    ret void
}

define void @unordered_i8_local_cluster_volatile(i8 %val) {
; CHECK-LABEL: unordered_i8_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot294[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot294;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i8 %val, ptr addrspace(5) %slot syncscope("cluster") unordered, align 1
    ret void
}

define void @unordered_i8_local_gpu_volatile(i8 %val) {
; CHECK-LABEL: unordered_i8_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot295[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot295;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [unordered_i8_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i8 %val, ptr addrspace(5) %slot syncscope("device") unordered, align 1
    ret void
}

define void @unordered_i16_local_sys(i16 %val) {
; CHECK-LABEL: unordered_i16_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot296[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot296;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i16 %val, ptr addrspace(5) %slot syncscope("") unordered, align 2
    ret void
}

define void @unordered_i16_local_cta(i16 %val) {
; CHECK-LABEL: unordered_i16_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot297[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot297;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i16 %val, ptr addrspace(5) %slot syncscope("block") unordered, align 2
    ret void
}

define void @unordered_i16_local_cluster(i16 %val) {
; CHECK-LABEL: unordered_i16_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot298[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot298;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i16 %val, ptr addrspace(5) %slot syncscope("cluster") unordered, align 2
    ret void
}

define void @unordered_i16_local_gpu(i16 %val) {
; CHECK-LABEL: unordered_i16_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot299[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot299;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i16 %val, ptr addrspace(5) %slot syncscope("device") unordered, align 2
    ret void
}

define void @unordered_i16_local_sys_volatile(i16 %val) {
; CHECK-LABEL: unordered_i16_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot300[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot300;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i16 %val, ptr addrspace(5) %slot syncscope("") unordered, align 2
    ret void
}

define void @unordered_i16_local_cta_volatile(i16 %val) {
; CHECK-LABEL: unordered_i16_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot301[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot301;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i16 %val, ptr addrspace(5) %slot syncscope("block") unordered, align 2
    ret void
}

define void @unordered_i16_local_cluster_volatile(i16 %val) {
; CHECK-LABEL: unordered_i16_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot302[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot302;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i16 %val, ptr addrspace(5) %slot syncscope("cluster") unordered, align 2
    ret void
}

define void @unordered_i16_local_gpu_volatile(i16 %val) {
; CHECK-LABEL: unordered_i16_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot303[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot303;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_i16_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i16 %val, ptr addrspace(5) %slot syncscope("device") unordered, align 2
    ret void
}

define void @unordered_i32_local_sys(i32 %val) {
; CHECK-LABEL: unordered_i32_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot304[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot304;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [unordered_i32_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i32 %val, ptr addrspace(5) %slot syncscope("") unordered, align 4
    ret void
}

define void @unordered_i32_local_cta(i32 %val) {
; CHECK-LABEL: unordered_i32_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot305[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot305;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [unordered_i32_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i32 %val, ptr addrspace(5) %slot syncscope("block") unordered, align 4
    ret void
}

define void @unordered_i32_local_cluster(i32 %val) {
; CHECK-LABEL: unordered_i32_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot306[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot306;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [unordered_i32_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i32 %val, ptr addrspace(5) %slot syncscope("cluster") unordered, align 4
    ret void
}

define void @unordered_i32_local_gpu(i32 %val) {
; CHECK-LABEL: unordered_i32_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot307[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot307;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [unordered_i32_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i32 %val, ptr addrspace(5) %slot syncscope("device") unordered, align 4
    ret void
}

define void @unordered_i32_local_sys_volatile(i32 %val) {
; CHECK-LABEL: unordered_i32_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot308[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot308;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [unordered_i32_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i32 %val, ptr addrspace(5) %slot syncscope("") unordered, align 4
    ret void
}

define void @unordered_i32_local_cta_volatile(i32 %val) {
; CHECK-LABEL: unordered_i32_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot309[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot309;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [unordered_i32_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i32 %val, ptr addrspace(5) %slot syncscope("block") unordered, align 4
    ret void
}

define void @unordered_i32_local_cluster_volatile(i32 %val) {
; CHECK-LABEL: unordered_i32_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot310[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot310;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [unordered_i32_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i32 %val, ptr addrspace(5) %slot syncscope("cluster") unordered, align 4
    ret void
}

define void @unordered_i32_local_gpu_volatile(i32 %val) {
; CHECK-LABEL: unordered_i32_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot311[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot311;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [unordered_i32_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i32 %val, ptr addrspace(5) %slot syncscope("device") unordered, align 4
    ret void
}

define void @unordered_i64_local_sys(i64 %val) {
; CHECK-LABEL: unordered_i64_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot312[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot312;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i64 %val, ptr addrspace(5) %slot syncscope("") unordered, align 8
    ret void
}

define void @unordered_i64_local_cta(i64 %val) {
; CHECK-LABEL: unordered_i64_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot313[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot313;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i64 %val, ptr addrspace(5) %slot syncscope("block") unordered, align 8
    ret void
}

define void @unordered_i64_local_cluster(i64 %val) {
; CHECK-LABEL: unordered_i64_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot314[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot314;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i64 %val, ptr addrspace(5) %slot syncscope("cluster") unordered, align 8
    ret void
}

define void @unordered_i64_local_gpu(i64 %val) {
; CHECK-LABEL: unordered_i64_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot315[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot315;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i64 %val, ptr addrspace(5) %slot syncscope("device") unordered, align 8
    ret void
}

define void @unordered_i64_local_sys_volatile(i64 %val) {
; CHECK-LABEL: unordered_i64_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot316[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot316;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i64 %val, ptr addrspace(5) %slot syncscope("") unordered, align 8
    ret void
}

define void @unordered_i64_local_cta_volatile(i64 %val) {
; CHECK-LABEL: unordered_i64_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot317[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot317;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i64 %val, ptr addrspace(5) %slot syncscope("block") unordered, align 8
    ret void
}

define void @unordered_i64_local_cluster_volatile(i64 %val) {
; CHECK-LABEL: unordered_i64_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot318[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot318;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i64 %val, ptr addrspace(5) %slot syncscope("cluster") unordered, align 8
    ret void
}

define void @unordered_i64_local_gpu_volatile(i64 %val) {
; CHECK-LABEL: unordered_i64_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot319[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot319;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_i64_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i64 %val, ptr addrspace(5) %slot syncscope("device") unordered, align 8
    ret void
}

define void @unordered_i128_local_sys(i128 %val) {
; CHECK-LABEL: unordered_i128_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot320[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot320;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i128 %val, ptr addrspace(5) %slot syncscope("") unordered, align 16
    ret void
}

define void @unordered_i128_local_cta(i128 %val) {
; CHECK-LABEL: unordered_i128_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot321[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot321;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i128 %val, ptr addrspace(5) %slot syncscope("block") unordered, align 16
    ret void
}

define void @unordered_i128_local_cluster(i128 %val) {
; CHECK-LABEL: unordered_i128_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot322[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot322;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i128 %val, ptr addrspace(5) %slot syncscope("cluster") unordered, align 16
    ret void
}

define void @unordered_i128_local_gpu(i128 %val) {
; CHECK-LABEL: unordered_i128_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot323[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot323;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i128 %val, ptr addrspace(5) %slot syncscope("device") unordered, align 16
    ret void
}

define void @unordered_i128_local_sys_volatile(i128 %val) {
; CHECK-LABEL: unordered_i128_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot324[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot324;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i128 %val, ptr addrspace(5) %slot syncscope("") unordered, align 16
    ret void
}

define void @unordered_i128_local_cta_volatile(i128 %val) {
; CHECK-LABEL: unordered_i128_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot325[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot325;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i128 %val, ptr addrspace(5) %slot syncscope("block") unordered, align 16
    ret void
}

define void @unordered_i128_local_cluster_volatile(i128 %val) {
; CHECK-LABEL: unordered_i128_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot326[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot326;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i128 %val, ptr addrspace(5) %slot syncscope("cluster") unordered, align 16
    ret void
}

define void @unordered_i128_local_gpu_volatile(i128 %val) {
; CHECK-LABEL: unordered_i128_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot327[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot327;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [unordered_i128_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i128 %val, ptr addrspace(5) %slot syncscope("device") unordered, align 16
    ret void
}

define void @unordered_half_local_sys(half %val) {
; CHECK-LABEL: unordered_half_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot328[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot328;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic half %val, ptr addrspace(5) %slot syncscope("") unordered, align 2
    ret void
}

define void @unordered_half_local_cta(half %val) {
; CHECK-LABEL: unordered_half_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot329[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot329;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic half %val, ptr addrspace(5) %slot syncscope("block") unordered, align 2
    ret void
}

define void @unordered_half_local_cluster(half %val) {
; CHECK-LABEL: unordered_half_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot330[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot330;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic half %val, ptr addrspace(5) %slot syncscope("cluster") unordered, align 2
    ret void
}

define void @unordered_half_local_gpu(half %val) {
; CHECK-LABEL: unordered_half_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot331[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot331;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic half %val, ptr addrspace(5) %slot syncscope("device") unordered, align 2
    ret void
}

define void @unordered_half_local_sys_volatile(half %val) {
; CHECK-LABEL: unordered_half_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot332[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot332;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile half %val, ptr addrspace(5) %slot syncscope("") unordered, align 2
    ret void
}

define void @unordered_half_local_cta_volatile(half %val) {
; CHECK-LABEL: unordered_half_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot333[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot333;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile half %val, ptr addrspace(5) %slot syncscope("block") unordered, align 2
    ret void
}

define void @unordered_half_local_cluster_volatile(half %val) {
; CHECK-LABEL: unordered_half_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot334[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot334;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile half %val, ptr addrspace(5) %slot syncscope("cluster") unordered, align 2
    ret void
}

define void @unordered_half_local_gpu_volatile(half %val) {
; CHECK-LABEL: unordered_half_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot335[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot335;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_half_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile half %val, ptr addrspace(5) %slot syncscope("device") unordered, align 2
    ret void
}

define void @unordered_bfloat_local_sys(bfloat %val) {
; CHECK-LABEL: unordered_bfloat_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot336[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot336;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic bfloat %val, ptr addrspace(5) %slot syncscope("") unordered, align 2
    ret void
}

define void @unordered_bfloat_local_cta(bfloat %val) {
; CHECK-LABEL: unordered_bfloat_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot337[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot337;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic bfloat %val, ptr addrspace(5) %slot syncscope("block") unordered, align 2
    ret void
}

define void @unordered_bfloat_local_cluster(bfloat %val) {
; CHECK-LABEL: unordered_bfloat_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot338[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot338;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic bfloat %val, ptr addrspace(5) %slot syncscope("cluster") unordered, align 2
    ret void
}

define void @unordered_bfloat_local_gpu(bfloat %val) {
; CHECK-LABEL: unordered_bfloat_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot339[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot339;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic bfloat %val, ptr addrspace(5) %slot syncscope("device") unordered, align 2
    ret void
}

define void @unordered_bfloat_local_sys_volatile(bfloat %val) {
; CHECK-LABEL: unordered_bfloat_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot340[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot340;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile bfloat %val, ptr addrspace(5) %slot syncscope("") unordered, align 2
    ret void
}

define void @unordered_bfloat_local_cta_volatile(bfloat %val) {
; CHECK-LABEL: unordered_bfloat_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot341[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot341;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile bfloat %val, ptr addrspace(5) %slot syncscope("block") unordered, align 2
    ret void
}

define void @unordered_bfloat_local_cluster_volatile(bfloat %val) {
; CHECK-LABEL: unordered_bfloat_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot342[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot342;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile bfloat %val, ptr addrspace(5) %slot syncscope("cluster") unordered, align 2
    ret void
}

define void @unordered_bfloat_local_gpu_volatile(bfloat %val) {
; CHECK-LABEL: unordered_bfloat_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot343[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot343;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [unordered_bfloat_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile bfloat %val, ptr addrspace(5) %slot syncscope("device") unordered, align 2
    ret void
}

define void @unordered_float_local_sys(float %val) {
; CHECK-LABEL: unordered_float_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot344[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot344;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [unordered_float_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic float %val, ptr addrspace(5) %slot syncscope("") unordered, align 4
    ret void
}

define void @unordered_float_local_cta(float %val) {
; CHECK-LABEL: unordered_float_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot345[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot345;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [unordered_float_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic float %val, ptr addrspace(5) %slot syncscope("block") unordered, align 4
    ret void
}

define void @unordered_float_local_cluster(float %val) {
; CHECK-LABEL: unordered_float_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot346[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot346;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [unordered_float_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic float %val, ptr addrspace(5) %slot syncscope("cluster") unordered, align 4
    ret void
}

define void @unordered_float_local_gpu(float %val) {
; CHECK-LABEL: unordered_float_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot347[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot347;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [unordered_float_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic float %val, ptr addrspace(5) %slot syncscope("device") unordered, align 4
    ret void
}

define void @unordered_float_local_sys_volatile(float %val) {
; CHECK-LABEL: unordered_float_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot348[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot348;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [unordered_float_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile float %val, ptr addrspace(5) %slot syncscope("") unordered, align 4
    ret void
}

define void @unordered_float_local_cta_volatile(float %val) {
; CHECK-LABEL: unordered_float_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot349[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot349;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [unordered_float_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile float %val, ptr addrspace(5) %slot syncscope("block") unordered, align 4
    ret void
}

define void @unordered_float_local_cluster_volatile(float %val) {
; CHECK-LABEL: unordered_float_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot350[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot350;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [unordered_float_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile float %val, ptr addrspace(5) %slot syncscope("cluster") unordered, align 4
    ret void
}

define void @unordered_float_local_gpu_volatile(float %val) {
; CHECK-LABEL: unordered_float_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot351[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot351;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [unordered_float_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile float %val, ptr addrspace(5) %slot syncscope("device") unordered, align 4
    ret void
}

define void @unordered_double_local_sys(double %val) {
; CHECK-LABEL: unordered_double_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot352[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot352;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic double %val, ptr addrspace(5) %slot syncscope("") unordered, align 8
    ret void
}

define void @unordered_double_local_cta(double %val) {
; CHECK-LABEL: unordered_double_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot353[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot353;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic double %val, ptr addrspace(5) %slot syncscope("block") unordered, align 8
    ret void
}

define void @unordered_double_local_cluster(double %val) {
; CHECK-LABEL: unordered_double_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot354[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot354;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic double %val, ptr addrspace(5) %slot syncscope("cluster") unordered, align 8
    ret void
}

define void @unordered_double_local_gpu(double %val) {
; CHECK-LABEL: unordered_double_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot355[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot355;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic double %val, ptr addrspace(5) %slot syncscope("device") unordered, align 8
    ret void
}

define void @unordered_double_local_sys_volatile(double %val) {
; CHECK-LABEL: unordered_double_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot356[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot356;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile double %val, ptr addrspace(5) %slot syncscope("") unordered, align 8
    ret void
}

define void @unordered_double_local_cta_volatile(double %val) {
; CHECK-LABEL: unordered_double_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot357[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot357;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile double %val, ptr addrspace(5) %slot syncscope("block") unordered, align 8
    ret void
}

define void @unordered_double_local_cluster_volatile(double %val) {
; CHECK-LABEL: unordered_double_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot358[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot358;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile double %val, ptr addrspace(5) %slot syncscope("cluster") unordered, align 8
    ret void
}

define void @unordered_double_local_gpu_volatile(double %val) {
; CHECK-LABEL: unordered_double_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot359[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot359;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [unordered_double_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile double %val, ptr addrspace(5) %slot syncscope("device") unordered, align 8
    ret void
}

define void @monotonic_i8_generic_sys(i8 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i8_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_generic_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i8_generic_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr %addr syncscope("") monotonic, align 1
    ret void
}

define void @monotonic_i8_generic_cta(i8 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i8_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_generic_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i8_generic_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr %addr syncscope("block") monotonic, align 1
    ret void
}

define void @monotonic_i8_generic_cluster(i8 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i8_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_generic_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i8_generic_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr %addr syncscope("cluster") monotonic, align 1
    ret void
}

define void @monotonic_i8_generic_gpu(i8 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i8_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_generic_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i8_generic_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr %addr syncscope("device") monotonic, align 1
    ret void
}

define void @monotonic_i8_generic_sys_volatile(i8 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i8_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_generic_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i8_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr %addr syncscope("") monotonic, align 1
    ret void
}

define void @monotonic_i8_generic_cta_volatile(i8 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i8_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_generic_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i8_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr %addr syncscope("block") monotonic, align 1
    ret void
}

define void @monotonic_i8_generic_cluster_volatile(i8 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i8_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_generic_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i8_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr %addr syncscope("cluster") monotonic, align 1
    ret void
}

define void @monotonic_i8_generic_gpu_volatile(i8 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i8_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_generic_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i8_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr %addr syncscope("device") monotonic, align 1
    ret void
}

define void @monotonic_i16_generic_sys(i16 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i16_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_generic_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i16_generic_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr %addr syncscope("") monotonic, align 2
    ret void
}

define void @monotonic_i16_generic_cta(i16 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i16_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_generic_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i16_generic_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr %addr syncscope("block") monotonic, align 2
    ret void
}

define void @monotonic_i16_generic_cluster(i16 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i16_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_generic_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i16_generic_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr %addr syncscope("cluster") monotonic, align 2
    ret void
}

define void @monotonic_i16_generic_gpu(i16 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i16_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_generic_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i16_generic_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr %addr syncscope("device") monotonic, align 2
    ret void
}

define void @monotonic_i16_generic_sys_volatile(i16 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i16_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_generic_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i16_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr %addr syncscope("") monotonic, align 2
    ret void
}

define void @monotonic_i16_generic_cta_volatile(i16 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i16_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_generic_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i16_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr %addr syncscope("block") monotonic, align 2
    ret void
}

define void @monotonic_i16_generic_cluster_volatile(i16 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i16_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_generic_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i16_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr %addr syncscope("cluster") monotonic, align 2
    ret void
}

define void @monotonic_i16_generic_gpu_volatile(i16 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i16_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_generic_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i16_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr %addr syncscope("device") monotonic, align 2
    ret void
}

define void @monotonic_i32_generic_sys(i32 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i32_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_i32_generic_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i32_generic_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr %addr syncscope("") monotonic, align 4
    ret void
}

define void @monotonic_i32_generic_cta(i32 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i32_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_i32_generic_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i32_generic_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr %addr syncscope("block") monotonic, align 4
    ret void
}

define void @monotonic_i32_generic_cluster(i32 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i32_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_i32_generic_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i32_generic_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr %addr syncscope("cluster") monotonic, align 4
    ret void
}

define void @monotonic_i32_generic_gpu(i32 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i32_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_i32_generic_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i32_generic_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr %addr syncscope("device") monotonic, align 4
    ret void
}

define void @monotonic_i32_generic_sys_volatile(i32 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i32_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_i32_generic_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i32_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr %addr syncscope("") monotonic, align 4
    ret void
}

define void @monotonic_i32_generic_cta_volatile(i32 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i32_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_i32_generic_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i32_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr %addr syncscope("block") monotonic, align 4
    ret void
}

define void @monotonic_i32_generic_cluster_volatile(i32 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i32_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_i32_generic_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i32_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr %addr syncscope("cluster") monotonic, align 4
    ret void
}

define void @monotonic_i32_generic_gpu_volatile(i32 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i32_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_i32_generic_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i32_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr %addr syncscope("device") monotonic, align 4
    ret void
}

define void @monotonic_i64_generic_sys(i64 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i64_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_generic_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_i64_generic_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr %addr syncscope("") monotonic, align 8
    ret void
}

define void @monotonic_i64_generic_cta(i64 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i64_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_generic_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_i64_generic_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr %addr syncscope("block") monotonic, align 8
    ret void
}

define void @monotonic_i64_generic_cluster(i64 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i64_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_generic_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_i64_generic_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr %addr syncscope("cluster") monotonic, align 8
    ret void
}

define void @monotonic_i64_generic_gpu(i64 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i64_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_generic_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_i64_generic_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr %addr syncscope("device") monotonic, align 8
    ret void
}

define void @monotonic_i64_generic_sys_volatile(i64 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i64_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_generic_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_i64_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr %addr syncscope("") monotonic, align 8
    ret void
}

define void @monotonic_i64_generic_cta_volatile(i64 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i64_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_generic_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_i64_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr %addr syncscope("block") monotonic, align 8
    ret void
}

define void @monotonic_i64_generic_cluster_volatile(i64 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i64_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_generic_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_i64_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr %addr syncscope("cluster") monotonic, align 8
    ret void
}

define void @monotonic_i64_generic_gpu_volatile(i64 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i64_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_generic_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_i64_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr %addr syncscope("device") monotonic, align 8
    ret void
}

define void @monotonic_i128_generic_sys(i128 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i128_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_generic_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [monotonic_i128_generic_sys_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.sys.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr %addr syncscope("") monotonic, align 16
    ret void
}

define void @monotonic_i128_generic_cta(i128 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i128_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_generic_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [monotonic_i128_generic_cta_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cta.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr %addr syncscope("block") monotonic, align 16
    ret void
}

define void @monotonic_i128_generic_cluster(i128 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i128_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_generic_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [monotonic_i128_generic_cluster_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cluster.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr %addr syncscope("cluster") monotonic, align 16
    ret void
}

define void @monotonic_i128_generic_gpu(i128 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i128_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_generic_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [monotonic_i128_generic_gpu_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.gpu.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr %addr syncscope("device") monotonic, align 16
    ret void
}

define void @monotonic_i128_generic_sys_volatile(i128 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i128_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_generic_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [monotonic_i128_generic_sys_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.sys.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr %addr syncscope("") monotonic, align 16
    ret void
}

define void @monotonic_i128_generic_cta_volatile(i128 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i128_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_generic_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [monotonic_i128_generic_cta_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cta.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr %addr syncscope("block") monotonic, align 16
    ret void
}

define void @monotonic_i128_generic_cluster_volatile(i128 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i128_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_generic_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [monotonic_i128_generic_cluster_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cluster.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr %addr syncscope("cluster") monotonic, align 16
    ret void
}

define void @monotonic_i128_generic_gpu_volatile(i128 %val, ptr %addr) {
; CHECK-LABEL: monotonic_i128_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_generic_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [monotonic_i128_generic_gpu_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.gpu.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr %addr syncscope("device") monotonic, align 16
    ret void
}

define void @monotonic_half_generic_sys(half %val, ptr %addr) {
; CHECK-LABEL: monotonic_half_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_generic_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_half_generic_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr %addr syncscope("") monotonic, align 2
    ret void
}

define void @monotonic_half_generic_cta(half %val, ptr %addr) {
; CHECK-LABEL: monotonic_half_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_generic_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_half_generic_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr %addr syncscope("block") monotonic, align 2
    ret void
}

define void @monotonic_half_generic_cluster(half %val, ptr %addr) {
; CHECK-LABEL: monotonic_half_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_generic_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_half_generic_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr %addr syncscope("cluster") monotonic, align 2
    ret void
}

define void @monotonic_half_generic_gpu(half %val, ptr %addr) {
; CHECK-LABEL: monotonic_half_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_generic_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_half_generic_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr %addr syncscope("device") monotonic, align 2
    ret void
}

define void @monotonic_half_generic_sys_volatile(half %val, ptr %addr) {
; CHECK-LABEL: monotonic_half_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_generic_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_half_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr %addr syncscope("") monotonic, align 2
    ret void
}

define void @monotonic_half_generic_cta_volatile(half %val, ptr %addr) {
; CHECK-LABEL: monotonic_half_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_generic_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_half_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr %addr syncscope("block") monotonic, align 2
    ret void
}

define void @monotonic_half_generic_cluster_volatile(half %val, ptr %addr) {
; CHECK-LABEL: monotonic_half_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_generic_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_half_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr %addr syncscope("cluster") monotonic, align 2
    ret void
}

define void @monotonic_half_generic_gpu_volatile(half %val, ptr %addr) {
; CHECK-LABEL: monotonic_half_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_generic_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_half_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr %addr syncscope("device") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_generic_sys(bfloat %val, ptr %addr) {
; CHECK-LABEL: monotonic_bfloat_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_generic_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_bfloat_generic_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr %addr syncscope("") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_generic_cta(bfloat %val, ptr %addr) {
; CHECK-LABEL: monotonic_bfloat_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_generic_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_bfloat_generic_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr %addr syncscope("block") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_generic_cluster(bfloat %val, ptr %addr) {
; CHECK-LABEL: monotonic_bfloat_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_generic_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_bfloat_generic_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr %addr syncscope("cluster") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_generic_gpu(bfloat %val, ptr %addr) {
; CHECK-LABEL: monotonic_bfloat_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_generic_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_bfloat_generic_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr %addr syncscope("device") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_generic_sys_volatile(bfloat %val, ptr %addr) {
; CHECK-LABEL: monotonic_bfloat_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_generic_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_bfloat_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr %addr syncscope("") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_generic_cta_volatile(bfloat %val, ptr %addr) {
; CHECK-LABEL: monotonic_bfloat_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_generic_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_bfloat_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr %addr syncscope("block") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_generic_cluster_volatile(bfloat %val, ptr %addr) {
; CHECK-LABEL: monotonic_bfloat_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_generic_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_bfloat_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr %addr syncscope("cluster") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_generic_gpu_volatile(bfloat %val, ptr %addr) {
; CHECK-LABEL: monotonic_bfloat_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_generic_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_bfloat_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr %addr syncscope("device") monotonic, align 2
    ret void
}

define void @monotonic_float_generic_sys(float %val, ptr %addr) {
; CHECK-LABEL: monotonic_float_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_float_generic_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_float_generic_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr %addr syncscope("") monotonic, align 4
    ret void
}

define void @monotonic_float_generic_cta(float %val, ptr %addr) {
; CHECK-LABEL: monotonic_float_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_float_generic_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_float_generic_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr %addr syncscope("block") monotonic, align 4
    ret void
}

define void @monotonic_float_generic_cluster(float %val, ptr %addr) {
; CHECK-LABEL: monotonic_float_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_float_generic_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_float_generic_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr %addr syncscope("cluster") monotonic, align 4
    ret void
}

define void @monotonic_float_generic_gpu(float %val, ptr %addr) {
; CHECK-LABEL: monotonic_float_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_float_generic_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_float_generic_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr %addr syncscope("device") monotonic, align 4
    ret void
}

define void @monotonic_float_generic_sys_volatile(float %val, ptr %addr) {
; CHECK-LABEL: monotonic_float_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_float_generic_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_float_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr %addr syncscope("") monotonic, align 4
    ret void
}

define void @monotonic_float_generic_cta_volatile(float %val, ptr %addr) {
; CHECK-LABEL: monotonic_float_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_float_generic_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_float_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr %addr syncscope("block") monotonic, align 4
    ret void
}

define void @monotonic_float_generic_cluster_volatile(float %val, ptr %addr) {
; CHECK-LABEL: monotonic_float_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_float_generic_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_float_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr %addr syncscope("cluster") monotonic, align 4
    ret void
}

define void @monotonic_float_generic_gpu_volatile(float %val, ptr %addr) {
; CHECK-LABEL: monotonic_float_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_float_generic_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_float_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr %addr syncscope("device") monotonic, align 4
    ret void
}

define void @monotonic_double_generic_sys(double %val, ptr %addr) {
; CHECK-LABEL: monotonic_double_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_generic_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_double_generic_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr %addr syncscope("") monotonic, align 8
    ret void
}

define void @monotonic_double_generic_cta(double %val, ptr %addr) {
; CHECK-LABEL: monotonic_double_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_generic_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_double_generic_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr %addr syncscope("block") monotonic, align 8
    ret void
}

define void @monotonic_double_generic_cluster(double %val, ptr %addr) {
; CHECK-LABEL: monotonic_double_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_generic_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_double_generic_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr %addr syncscope("cluster") monotonic, align 8
    ret void
}

define void @monotonic_double_generic_gpu(double %val, ptr %addr) {
; CHECK-LABEL: monotonic_double_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_generic_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_double_generic_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr %addr syncscope("device") monotonic, align 8
    ret void
}

define void @monotonic_double_generic_sys_volatile(double %val, ptr %addr) {
; CHECK-LABEL: monotonic_double_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_generic_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_double_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr %addr syncscope("") monotonic, align 8
    ret void
}

define void @monotonic_double_generic_cta_volatile(double %val, ptr %addr) {
; CHECK-LABEL: monotonic_double_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_generic_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_double_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr %addr syncscope("block") monotonic, align 8
    ret void
}

define void @monotonic_double_generic_cluster_volatile(double %val, ptr %addr) {
; CHECK-LABEL: monotonic_double_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_generic_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_double_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr %addr syncscope("cluster") monotonic, align 8
    ret void
}

define void @monotonic_double_generic_gpu_volatile(double %val, ptr %addr) {
; CHECK-LABEL: monotonic_double_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_generic_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_double_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr %addr syncscope("device") monotonic, align 8
    ret void
}

define void @monotonic_i8_global_sys(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i8_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_global_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i8_global_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(1) %addr syncscope("") monotonic, align 1
    ret void
}

define void @monotonic_i8_global_cta(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i8_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_global_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i8_global_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(1) %addr syncscope("block") monotonic, align 1
    ret void
}

define void @monotonic_i8_global_cluster(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i8_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_global_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i8_global_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(1) %addr syncscope("cluster") monotonic, align 1
    ret void
}

define void @monotonic_i8_global_gpu(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i8_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_global_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i8_global_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(1) %addr syncscope("device") monotonic, align 1
    ret void
}

define void @monotonic_i8_global_sys_volatile(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i8_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_global_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i8_global_sys_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(1) %addr syncscope("") monotonic, align 1
    ret void
}

define void @monotonic_i8_global_cta_volatile(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i8_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_global_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i8_global_cta_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(1) %addr syncscope("block") monotonic, align 1
    ret void
}

define void @monotonic_i8_global_cluster_volatile(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i8_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_global_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i8_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(1) %addr syncscope("cluster") monotonic, align 1
    ret void
}

define void @monotonic_i8_global_gpu_volatile(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i8_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_global_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i8_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(1) %addr syncscope("device") monotonic, align 1
    ret void
}

define void @monotonic_i16_global_sys(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i16_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_global_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i16_global_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(1) %addr syncscope("") monotonic, align 2
    ret void
}

define void @monotonic_i16_global_cta(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i16_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_global_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i16_global_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(1) %addr syncscope("block") monotonic, align 2
    ret void
}

define void @monotonic_i16_global_cluster(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i16_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_global_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i16_global_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(1) %addr syncscope("cluster") monotonic, align 2
    ret void
}

define void @monotonic_i16_global_gpu(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i16_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_global_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i16_global_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(1) %addr syncscope("device") monotonic, align 2
    ret void
}

define void @monotonic_i16_global_sys_volatile(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i16_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_global_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i16_global_sys_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(1) %addr syncscope("") monotonic, align 2
    ret void
}

define void @monotonic_i16_global_cta_volatile(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i16_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_global_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i16_global_cta_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(1) %addr syncscope("block") monotonic, align 2
    ret void
}

define void @monotonic_i16_global_cluster_volatile(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i16_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_global_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i16_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(1) %addr syncscope("cluster") monotonic, align 2
    ret void
}

define void @monotonic_i16_global_gpu_volatile(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i16_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_global_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i16_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(1) %addr syncscope("device") monotonic, align 2
    ret void
}

define void @monotonic_i32_global_sys(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i32_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_i32_global_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i32_global_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(1) %addr syncscope("") monotonic, align 4
    ret void
}

define void @monotonic_i32_global_cta(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i32_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_i32_global_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i32_global_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(1) %addr syncscope("block") monotonic, align 4
    ret void
}

define void @monotonic_i32_global_cluster(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i32_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_i32_global_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i32_global_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(1) %addr syncscope("cluster") monotonic, align 4
    ret void
}

define void @monotonic_i32_global_gpu(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i32_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_i32_global_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i32_global_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(1) %addr syncscope("device") monotonic, align 4
    ret void
}

define void @monotonic_i32_global_sys_volatile(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i32_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_i32_global_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i32_global_sys_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(1) %addr syncscope("") monotonic, align 4
    ret void
}

define void @monotonic_i32_global_cta_volatile(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i32_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_i32_global_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i32_global_cta_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(1) %addr syncscope("block") monotonic, align 4
    ret void
}

define void @monotonic_i32_global_cluster_volatile(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i32_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_i32_global_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i32_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(1) %addr syncscope("cluster") monotonic, align 4
    ret void
}

define void @monotonic_i32_global_gpu_volatile(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i32_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_i32_global_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i32_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(1) %addr syncscope("device") monotonic, align 4
    ret void
}

define void @monotonic_i64_global_sys(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i64_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_global_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_i64_global_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(1) %addr syncscope("") monotonic, align 8
    ret void
}

define void @monotonic_i64_global_cta(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i64_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_global_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_i64_global_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(1) %addr syncscope("block") monotonic, align 8
    ret void
}

define void @monotonic_i64_global_cluster(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i64_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_global_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_i64_global_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(1) %addr syncscope("cluster") monotonic, align 8
    ret void
}

define void @monotonic_i64_global_gpu(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i64_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_global_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_i64_global_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(1) %addr syncscope("device") monotonic, align 8
    ret void
}

define void @monotonic_i64_global_sys_volatile(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i64_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_global_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_i64_global_sys_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(1) %addr syncscope("") monotonic, align 8
    ret void
}

define void @monotonic_i64_global_cta_volatile(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i64_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_global_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_i64_global_cta_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(1) %addr syncscope("block") monotonic, align 8
    ret void
}

define void @monotonic_i64_global_cluster_volatile(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i64_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_global_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_i64_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(1) %addr syncscope("cluster") monotonic, align 8
    ret void
}

define void @monotonic_i64_global_gpu_volatile(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i64_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_global_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_i64_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(1) %addr syncscope("device") monotonic, align 8
    ret void
}

define void @monotonic_i128_global_sys(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i128_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_global_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [monotonic_i128_global_sys_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.sys.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(1) %addr syncscope("") monotonic, align 16
    ret void
}

define void @monotonic_i128_global_cta(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i128_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_global_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [monotonic_i128_global_cta_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cta.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(1) %addr syncscope("block") monotonic, align 16
    ret void
}

define void @monotonic_i128_global_cluster(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i128_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_global_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [monotonic_i128_global_cluster_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cluster.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(1) %addr syncscope("cluster") monotonic, align 16
    ret void
}

define void @monotonic_i128_global_gpu(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i128_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_global_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [monotonic_i128_global_gpu_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.gpu.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(1) %addr syncscope("device") monotonic, align 16
    ret void
}

define void @monotonic_i128_global_sys_volatile(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i128_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_global_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [monotonic_i128_global_sys_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.sys.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(1) %addr syncscope("") monotonic, align 16
    ret void
}

define void @monotonic_i128_global_cta_volatile(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i128_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_global_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [monotonic_i128_global_cta_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cta.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(1) %addr syncscope("block") monotonic, align 16
    ret void
}

define void @monotonic_i128_global_cluster_volatile(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i128_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_global_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [monotonic_i128_global_cluster_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cluster.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(1) %addr syncscope("cluster") monotonic, align 16
    ret void
}

define void @monotonic_i128_global_gpu_volatile(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_i128_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_global_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [monotonic_i128_global_gpu_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.gpu.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(1) %addr syncscope("device") monotonic, align 16
    ret void
}

define void @monotonic_half_global_sys(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_half_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_global_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_half_global_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(1) %addr syncscope("") monotonic, align 2
    ret void
}

define void @monotonic_half_global_cta(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_half_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_global_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_half_global_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(1) %addr syncscope("block") monotonic, align 2
    ret void
}

define void @monotonic_half_global_cluster(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_half_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_global_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_half_global_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(1) %addr syncscope("cluster") monotonic, align 2
    ret void
}

define void @monotonic_half_global_gpu(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_half_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_global_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_half_global_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(1) %addr syncscope("device") monotonic, align 2
    ret void
}

define void @monotonic_half_global_sys_volatile(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_half_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_global_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_half_global_sys_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(1) %addr syncscope("") monotonic, align 2
    ret void
}

define void @monotonic_half_global_cta_volatile(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_half_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_global_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_half_global_cta_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(1) %addr syncscope("block") monotonic, align 2
    ret void
}

define void @monotonic_half_global_cluster_volatile(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_half_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_global_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_half_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(1) %addr syncscope("cluster") monotonic, align 2
    ret void
}

define void @monotonic_half_global_gpu_volatile(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_half_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_global_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_half_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(1) %addr syncscope("device") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_global_sys(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_bfloat_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_global_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_bfloat_global_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(1) %addr syncscope("") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_global_cta(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_bfloat_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_global_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_bfloat_global_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(1) %addr syncscope("block") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_global_cluster(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_bfloat_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_global_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_bfloat_global_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(1) %addr syncscope("cluster") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_global_gpu(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_bfloat_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_global_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_bfloat_global_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(1) %addr syncscope("device") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_global_sys_volatile(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_bfloat_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_global_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_bfloat_global_sys_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(1) %addr syncscope("") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_global_cta_volatile(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_bfloat_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_global_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_bfloat_global_cta_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(1) %addr syncscope("block") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_global_cluster_volatile(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_bfloat_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_global_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_bfloat_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(1) %addr syncscope("cluster") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_global_gpu_volatile(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_bfloat_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_global_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_bfloat_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(1) %addr syncscope("device") monotonic, align 2
    ret void
}

define void @monotonic_float_global_sys(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_float_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_float_global_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_float_global_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(1) %addr syncscope("") monotonic, align 4
    ret void
}

define void @monotonic_float_global_cta(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_float_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_float_global_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_float_global_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(1) %addr syncscope("block") monotonic, align 4
    ret void
}

define void @monotonic_float_global_cluster(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_float_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_float_global_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_float_global_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(1) %addr syncscope("cluster") monotonic, align 4
    ret void
}

define void @monotonic_float_global_gpu(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_float_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_float_global_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_float_global_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(1) %addr syncscope("device") monotonic, align 4
    ret void
}

define void @monotonic_float_global_sys_volatile(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_float_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_float_global_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_float_global_sys_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(1) %addr syncscope("") monotonic, align 4
    ret void
}

define void @monotonic_float_global_cta_volatile(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_float_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_float_global_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_float_global_cta_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(1) %addr syncscope("block") monotonic, align 4
    ret void
}

define void @monotonic_float_global_cluster_volatile(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_float_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_float_global_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_float_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(1) %addr syncscope("cluster") monotonic, align 4
    ret void
}

define void @monotonic_float_global_gpu_volatile(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_float_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_float_global_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_float_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(1) %addr syncscope("device") monotonic, align 4
    ret void
}

define void @monotonic_double_global_sys(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_double_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_global_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_double_global_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(1) %addr syncscope("") monotonic, align 8
    ret void
}

define void @monotonic_double_global_cta(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_double_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_global_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_double_global_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(1) %addr syncscope("block") monotonic, align 8
    ret void
}

define void @monotonic_double_global_cluster(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_double_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_global_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_double_global_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(1) %addr syncscope("cluster") monotonic, align 8
    ret void
}

define void @monotonic_double_global_gpu(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_double_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_global_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_double_global_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(1) %addr syncscope("device") monotonic, align 8
    ret void
}

define void @monotonic_double_global_sys_volatile(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_double_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_global_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_double_global_sys_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(1) %addr syncscope("") monotonic, align 8
    ret void
}

define void @monotonic_double_global_cta_volatile(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_double_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_global_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_double_global_cta_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(1) %addr syncscope("block") monotonic, align 8
    ret void
}

define void @monotonic_double_global_cluster_volatile(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_double_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_global_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_double_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(1) %addr syncscope("cluster") monotonic, align 8
    ret void
}

define void @monotonic_double_global_gpu_volatile(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: monotonic_double_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_global_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_double_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(1) %addr syncscope("device") monotonic, align 8
    ret void
}

define void @monotonic_i8_shared_sys(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i8_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_shared_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i8_shared_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(3) %addr syncscope("") monotonic, align 1
    ret void
}

define void @monotonic_i8_shared_cta(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i8_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_shared_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i8_shared_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(3) %addr syncscope("block") monotonic, align 1
    ret void
}

define void @monotonic_i8_shared_cluster(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i8_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_shared_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i8_shared_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(3) %addr syncscope("cluster") monotonic, align 1
    ret void
}

define void @monotonic_i8_shared_gpu(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i8_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_shared_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i8_shared_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(3) %addr syncscope("device") monotonic, align 1
    ret void
}

define void @monotonic_i8_shared_sys_volatile(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i8_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_shared_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i8_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(3) %addr syncscope("") monotonic, align 1
    ret void
}

define void @monotonic_i8_shared_cta_volatile(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i8_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_shared_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i8_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(3) %addr syncscope("block") monotonic, align 1
    ret void
}

define void @monotonic_i8_shared_cluster_volatile(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i8_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_shared_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i8_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(3) %addr syncscope("cluster") monotonic, align 1
    ret void
}

define void @monotonic_i8_shared_gpu_volatile(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i8_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_shared_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i8_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(3) %addr syncscope("device") monotonic, align 1
    ret void
}

define void @monotonic_i16_shared_sys(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i16_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_shared_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i16_shared_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(3) %addr syncscope("") monotonic, align 2
    ret void
}

define void @monotonic_i16_shared_cta(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i16_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_shared_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i16_shared_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(3) %addr syncscope("block") monotonic, align 2
    ret void
}

define void @monotonic_i16_shared_cluster(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i16_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_shared_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i16_shared_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(3) %addr syncscope("cluster") monotonic, align 2
    ret void
}

define void @monotonic_i16_shared_gpu(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i16_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_shared_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i16_shared_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(3) %addr syncscope("device") monotonic, align 2
    ret void
}

define void @monotonic_i16_shared_sys_volatile(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i16_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_shared_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i16_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(3) %addr syncscope("") monotonic, align 2
    ret void
}

define void @monotonic_i16_shared_cta_volatile(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i16_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_shared_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i16_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(3) %addr syncscope("block") monotonic, align 2
    ret void
}

define void @monotonic_i16_shared_cluster_volatile(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i16_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_shared_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i16_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(3) %addr syncscope("cluster") monotonic, align 2
    ret void
}

define void @monotonic_i16_shared_gpu_volatile(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i16_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_shared_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i16_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(3) %addr syncscope("device") monotonic, align 2
    ret void
}

define void @monotonic_i32_shared_sys(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i32_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_i32_shared_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i32_shared_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(3) %addr syncscope("") monotonic, align 4
    ret void
}

define void @monotonic_i32_shared_cta(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i32_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_i32_shared_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i32_shared_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(3) %addr syncscope("block") monotonic, align 4
    ret void
}

define void @monotonic_i32_shared_cluster(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i32_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_i32_shared_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i32_shared_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(3) %addr syncscope("cluster") monotonic, align 4
    ret void
}

define void @monotonic_i32_shared_gpu(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i32_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_i32_shared_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i32_shared_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(3) %addr syncscope("device") monotonic, align 4
    ret void
}

define void @monotonic_i32_shared_sys_volatile(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i32_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_i32_shared_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i32_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(3) %addr syncscope("") monotonic, align 4
    ret void
}

define void @monotonic_i32_shared_cta_volatile(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i32_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_i32_shared_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i32_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(3) %addr syncscope("block") monotonic, align 4
    ret void
}

define void @monotonic_i32_shared_cluster_volatile(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i32_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_i32_shared_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i32_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(3) %addr syncscope("cluster") monotonic, align 4
    ret void
}

define void @monotonic_i32_shared_gpu_volatile(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i32_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_i32_shared_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i32_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(3) %addr syncscope("device") monotonic, align 4
    ret void
}

define void @monotonic_i64_shared_sys(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i64_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_shared_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_i64_shared_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(3) %addr syncscope("") monotonic, align 8
    ret void
}

define void @monotonic_i64_shared_cta(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i64_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_shared_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_i64_shared_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(3) %addr syncscope("block") monotonic, align 8
    ret void
}

define void @monotonic_i64_shared_cluster(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i64_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_shared_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_i64_shared_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(3) %addr syncscope("cluster") monotonic, align 8
    ret void
}

define void @monotonic_i64_shared_gpu(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i64_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_shared_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_i64_shared_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(3) %addr syncscope("device") monotonic, align 8
    ret void
}

define void @monotonic_i64_shared_sys_volatile(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i64_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_shared_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_i64_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(3) %addr syncscope("") monotonic, align 8
    ret void
}

define void @monotonic_i64_shared_cta_volatile(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i64_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_shared_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_i64_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(3) %addr syncscope("block") monotonic, align 8
    ret void
}

define void @monotonic_i64_shared_cluster_volatile(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i64_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_shared_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_i64_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(3) %addr syncscope("cluster") monotonic, align 8
    ret void
}

define void @monotonic_i64_shared_gpu_volatile(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i64_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_shared_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_i64_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(3) %addr syncscope("device") monotonic, align 8
    ret void
}

define void @monotonic_i128_shared_sys(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i128_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_shared_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [monotonic_i128_shared_sys_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.sys.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(3) %addr syncscope("") monotonic, align 16
    ret void
}

define void @monotonic_i128_shared_cta(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i128_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_shared_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [monotonic_i128_shared_cta_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cta.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(3) %addr syncscope("block") monotonic, align 16
    ret void
}

define void @monotonic_i128_shared_cluster(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i128_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_shared_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [monotonic_i128_shared_cluster_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cluster.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(3) %addr syncscope("cluster") monotonic, align 16
    ret void
}

define void @monotonic_i128_shared_gpu(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i128_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_shared_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [monotonic_i128_shared_gpu_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.gpu.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(3) %addr syncscope("device") monotonic, align 16
    ret void
}

define void @monotonic_i128_shared_sys_volatile(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i128_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_shared_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [monotonic_i128_shared_sys_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.sys.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(3) %addr syncscope("") monotonic, align 16
    ret void
}

define void @monotonic_i128_shared_cta_volatile(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i128_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_shared_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [monotonic_i128_shared_cta_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cta.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(3) %addr syncscope("block") monotonic, align 16
    ret void
}

define void @monotonic_i128_shared_cluster_volatile(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i128_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_shared_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [monotonic_i128_shared_cluster_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cluster.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(3) %addr syncscope("cluster") monotonic, align 16
    ret void
}

define void @monotonic_i128_shared_gpu_volatile(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_i128_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_shared_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [monotonic_i128_shared_gpu_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.gpu.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(3) %addr syncscope("device") monotonic, align 16
    ret void
}

define void @monotonic_half_shared_sys(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_half_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_shared_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_half_shared_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(3) %addr syncscope("") monotonic, align 2
    ret void
}

define void @monotonic_half_shared_cta(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_half_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_shared_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_half_shared_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(3) %addr syncscope("block") monotonic, align 2
    ret void
}

define void @monotonic_half_shared_cluster(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_half_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_shared_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_half_shared_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(3) %addr syncscope("cluster") monotonic, align 2
    ret void
}

define void @monotonic_half_shared_gpu(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_half_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_shared_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_half_shared_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(3) %addr syncscope("device") monotonic, align 2
    ret void
}

define void @monotonic_half_shared_sys_volatile(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_half_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_shared_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_half_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(3) %addr syncscope("") monotonic, align 2
    ret void
}

define void @monotonic_half_shared_cta_volatile(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_half_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_shared_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_half_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(3) %addr syncscope("block") monotonic, align 2
    ret void
}

define void @monotonic_half_shared_cluster_volatile(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_half_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_shared_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_half_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(3) %addr syncscope("cluster") monotonic, align 2
    ret void
}

define void @monotonic_half_shared_gpu_volatile(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_half_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_shared_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_half_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(3) %addr syncscope("device") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_shared_sys(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_bfloat_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_shared_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_bfloat_shared_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(3) %addr syncscope("") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_shared_cta(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_bfloat_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_shared_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_bfloat_shared_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(3) %addr syncscope("block") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_shared_cluster(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_bfloat_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_shared_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_bfloat_shared_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(3) %addr syncscope("cluster") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_shared_gpu(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_bfloat_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_shared_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_bfloat_shared_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(3) %addr syncscope("device") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_shared_sys_volatile(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_bfloat_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_shared_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_bfloat_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(3) %addr syncscope("") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_shared_cta_volatile(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_bfloat_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_shared_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_bfloat_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(3) %addr syncscope("block") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_shared_cluster_volatile(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_bfloat_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_shared_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_bfloat_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(3) %addr syncscope("cluster") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_shared_gpu_volatile(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_bfloat_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_shared_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_bfloat_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(3) %addr syncscope("device") monotonic, align 2
    ret void
}

define void @monotonic_float_shared_sys(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_float_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_float_shared_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_float_shared_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(3) %addr syncscope("") monotonic, align 4
    ret void
}

define void @monotonic_float_shared_cta(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_float_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_float_shared_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_float_shared_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(3) %addr syncscope("block") monotonic, align 4
    ret void
}

define void @monotonic_float_shared_cluster(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_float_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_float_shared_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_float_shared_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(3) %addr syncscope("cluster") monotonic, align 4
    ret void
}

define void @monotonic_float_shared_gpu(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_float_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_float_shared_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_float_shared_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(3) %addr syncscope("device") monotonic, align 4
    ret void
}

define void @monotonic_float_shared_sys_volatile(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_float_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_float_shared_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_float_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(3) %addr syncscope("") monotonic, align 4
    ret void
}

define void @monotonic_float_shared_cta_volatile(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_float_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_float_shared_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_float_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(3) %addr syncscope("block") monotonic, align 4
    ret void
}

define void @monotonic_float_shared_cluster_volatile(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_float_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_float_shared_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_float_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(3) %addr syncscope("cluster") monotonic, align 4
    ret void
}

define void @monotonic_float_shared_gpu_volatile(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_float_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [monotonic_float_shared_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_float_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(3) %addr syncscope("device") monotonic, align 4
    ret void
}

define void @monotonic_double_shared_sys(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_double_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_shared_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_double_shared_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(3) %addr syncscope("") monotonic, align 8
    ret void
}

define void @monotonic_double_shared_cta(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_double_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_shared_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_double_shared_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(3) %addr syncscope("block") monotonic, align 8
    ret void
}

define void @monotonic_double_shared_cluster(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_double_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_shared_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_double_shared_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(3) %addr syncscope("cluster") monotonic, align 8
    ret void
}

define void @monotonic_double_shared_gpu(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_double_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_shared_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_double_shared_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(3) %addr syncscope("device") monotonic, align 8
    ret void
}

define void @monotonic_double_shared_sys_volatile(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_double_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_shared_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_double_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(3) %addr syncscope("") monotonic, align 8
    ret void
}

define void @monotonic_double_shared_cta_volatile(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_double_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_shared_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_double_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(3) %addr syncscope("block") monotonic, align 8
    ret void
}

define void @monotonic_double_shared_cluster_volatile(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_double_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_shared_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_double_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(3) %addr syncscope("cluster") monotonic, align 8
    ret void
}

define void @monotonic_double_shared_gpu_volatile(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: monotonic_double_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_shared_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [monotonic_double_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(3) %addr syncscope("device") monotonic, align 8
    ret void
}

define void @monotonic_i8_local_sys(i8 %val) {
; CHECK-LABEL: monotonic_i8_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot576[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot576;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i8 %val, ptr addrspace(5) %slot syncscope("") monotonic, align 1
    ret void
}

define void @monotonic_i8_local_cta(i8 %val) {
; CHECK-LABEL: monotonic_i8_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot577[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot577;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i8 %val, ptr addrspace(5) %slot syncscope("block") monotonic, align 1
    ret void
}

define void @monotonic_i8_local_cluster(i8 %val) {
; CHECK-LABEL: monotonic_i8_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot578[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot578;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i8 %val, ptr addrspace(5) %slot syncscope("cluster") monotonic, align 1
    ret void
}

define void @monotonic_i8_local_gpu(i8 %val) {
; CHECK-LABEL: monotonic_i8_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot579[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot579;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i8 %val, ptr addrspace(5) %slot syncscope("device") monotonic, align 1
    ret void
}

define void @monotonic_i8_local_sys_volatile(i8 %val) {
; CHECK-LABEL: monotonic_i8_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot580[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot580;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i8 %val, ptr addrspace(5) %slot syncscope("") monotonic, align 1
    ret void
}

define void @monotonic_i8_local_cta_volatile(i8 %val) {
; CHECK-LABEL: monotonic_i8_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot581[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot581;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i8 %val, ptr addrspace(5) %slot syncscope("block") monotonic, align 1
    ret void
}

define void @monotonic_i8_local_cluster_volatile(i8 %val) {
; CHECK-LABEL: monotonic_i8_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot582[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot582;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i8 %val, ptr addrspace(5) %slot syncscope("cluster") monotonic, align 1
    ret void
}

define void @monotonic_i8_local_gpu_volatile(i8 %val) {
; CHECK-LABEL: monotonic_i8_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot583[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot583;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [monotonic_i8_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i8 %val, ptr addrspace(5) %slot syncscope("device") monotonic, align 1
    ret void
}

define void @monotonic_i16_local_sys(i16 %val) {
; CHECK-LABEL: monotonic_i16_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot584[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot584;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i16 %val, ptr addrspace(5) %slot syncscope("") monotonic, align 2
    ret void
}

define void @monotonic_i16_local_cta(i16 %val) {
; CHECK-LABEL: monotonic_i16_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot585[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot585;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i16 %val, ptr addrspace(5) %slot syncscope("block") monotonic, align 2
    ret void
}

define void @monotonic_i16_local_cluster(i16 %val) {
; CHECK-LABEL: monotonic_i16_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot586[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot586;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i16 %val, ptr addrspace(5) %slot syncscope("cluster") monotonic, align 2
    ret void
}

define void @monotonic_i16_local_gpu(i16 %val) {
; CHECK-LABEL: monotonic_i16_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot587[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot587;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i16 %val, ptr addrspace(5) %slot syncscope("device") monotonic, align 2
    ret void
}

define void @monotonic_i16_local_sys_volatile(i16 %val) {
; CHECK-LABEL: monotonic_i16_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot588[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot588;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i16 %val, ptr addrspace(5) %slot syncscope("") monotonic, align 2
    ret void
}

define void @monotonic_i16_local_cta_volatile(i16 %val) {
; CHECK-LABEL: monotonic_i16_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot589[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot589;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i16 %val, ptr addrspace(5) %slot syncscope("block") monotonic, align 2
    ret void
}

define void @monotonic_i16_local_cluster_volatile(i16 %val) {
; CHECK-LABEL: monotonic_i16_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot590[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot590;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i16 %val, ptr addrspace(5) %slot syncscope("cluster") monotonic, align 2
    ret void
}

define void @monotonic_i16_local_gpu_volatile(i16 %val) {
; CHECK-LABEL: monotonic_i16_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot591[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot591;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_i16_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i16 %val, ptr addrspace(5) %slot syncscope("device") monotonic, align 2
    ret void
}

define void @monotonic_i32_local_sys(i32 %val) {
; CHECK-LABEL: monotonic_i32_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot592[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot592;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [monotonic_i32_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i32 %val, ptr addrspace(5) %slot syncscope("") monotonic, align 4
    ret void
}

define void @monotonic_i32_local_cta(i32 %val) {
; CHECK-LABEL: monotonic_i32_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot593[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot593;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [monotonic_i32_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i32 %val, ptr addrspace(5) %slot syncscope("block") monotonic, align 4
    ret void
}

define void @monotonic_i32_local_cluster(i32 %val) {
; CHECK-LABEL: monotonic_i32_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot594[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot594;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [monotonic_i32_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i32 %val, ptr addrspace(5) %slot syncscope("cluster") monotonic, align 4
    ret void
}

define void @monotonic_i32_local_gpu(i32 %val) {
; CHECK-LABEL: monotonic_i32_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot595[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot595;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [monotonic_i32_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i32 %val, ptr addrspace(5) %slot syncscope("device") monotonic, align 4
    ret void
}

define void @monotonic_i32_local_sys_volatile(i32 %val) {
; CHECK-LABEL: monotonic_i32_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot596[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot596;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [monotonic_i32_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i32 %val, ptr addrspace(5) %slot syncscope("") monotonic, align 4
    ret void
}

define void @monotonic_i32_local_cta_volatile(i32 %val) {
; CHECK-LABEL: monotonic_i32_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot597[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot597;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [monotonic_i32_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i32 %val, ptr addrspace(5) %slot syncscope("block") monotonic, align 4
    ret void
}

define void @monotonic_i32_local_cluster_volatile(i32 %val) {
; CHECK-LABEL: monotonic_i32_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot598[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot598;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [monotonic_i32_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i32 %val, ptr addrspace(5) %slot syncscope("cluster") monotonic, align 4
    ret void
}

define void @monotonic_i32_local_gpu_volatile(i32 %val) {
; CHECK-LABEL: monotonic_i32_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot599[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot599;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [monotonic_i32_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i32 %val, ptr addrspace(5) %slot syncscope("device") monotonic, align 4
    ret void
}

define void @monotonic_i64_local_sys(i64 %val) {
; CHECK-LABEL: monotonic_i64_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot600[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot600;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i64 %val, ptr addrspace(5) %slot syncscope("") monotonic, align 8
    ret void
}

define void @monotonic_i64_local_cta(i64 %val) {
; CHECK-LABEL: monotonic_i64_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot601[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot601;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i64 %val, ptr addrspace(5) %slot syncscope("block") monotonic, align 8
    ret void
}

define void @monotonic_i64_local_cluster(i64 %val) {
; CHECK-LABEL: monotonic_i64_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot602[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot602;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i64 %val, ptr addrspace(5) %slot syncscope("cluster") monotonic, align 8
    ret void
}

define void @monotonic_i64_local_gpu(i64 %val) {
; CHECK-LABEL: monotonic_i64_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot603[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot603;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i64 %val, ptr addrspace(5) %slot syncscope("device") monotonic, align 8
    ret void
}

define void @monotonic_i64_local_sys_volatile(i64 %val) {
; CHECK-LABEL: monotonic_i64_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot604[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot604;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i64 %val, ptr addrspace(5) %slot syncscope("") monotonic, align 8
    ret void
}

define void @monotonic_i64_local_cta_volatile(i64 %val) {
; CHECK-LABEL: monotonic_i64_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot605[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot605;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i64 %val, ptr addrspace(5) %slot syncscope("block") monotonic, align 8
    ret void
}

define void @monotonic_i64_local_cluster_volatile(i64 %val) {
; CHECK-LABEL: monotonic_i64_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot606[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot606;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i64 %val, ptr addrspace(5) %slot syncscope("cluster") monotonic, align 8
    ret void
}

define void @monotonic_i64_local_gpu_volatile(i64 %val) {
; CHECK-LABEL: monotonic_i64_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot607[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot607;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_i64_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i64 %val, ptr addrspace(5) %slot syncscope("device") monotonic, align 8
    ret void
}

define void @monotonic_i128_local_sys(i128 %val) {
; CHECK-LABEL: monotonic_i128_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot608[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot608;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i128 %val, ptr addrspace(5) %slot syncscope("") monotonic, align 16
    ret void
}

define void @monotonic_i128_local_cta(i128 %val) {
; CHECK-LABEL: monotonic_i128_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot609[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot609;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i128 %val, ptr addrspace(5) %slot syncscope("block") monotonic, align 16
    ret void
}

define void @monotonic_i128_local_cluster(i128 %val) {
; CHECK-LABEL: monotonic_i128_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot610[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot610;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i128 %val, ptr addrspace(5) %slot syncscope("cluster") monotonic, align 16
    ret void
}

define void @monotonic_i128_local_gpu(i128 %val) {
; CHECK-LABEL: monotonic_i128_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot611[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot611;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i128 %val, ptr addrspace(5) %slot syncscope("device") monotonic, align 16
    ret void
}

define void @monotonic_i128_local_sys_volatile(i128 %val) {
; CHECK-LABEL: monotonic_i128_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot612[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot612;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i128 %val, ptr addrspace(5) %slot syncscope("") monotonic, align 16
    ret void
}

define void @monotonic_i128_local_cta_volatile(i128 %val) {
; CHECK-LABEL: monotonic_i128_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot613[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot613;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i128 %val, ptr addrspace(5) %slot syncscope("block") monotonic, align 16
    ret void
}

define void @monotonic_i128_local_cluster_volatile(i128 %val) {
; CHECK-LABEL: monotonic_i128_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot614[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot614;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i128 %val, ptr addrspace(5) %slot syncscope("cluster") monotonic, align 16
    ret void
}

define void @monotonic_i128_local_gpu_volatile(i128 %val) {
; CHECK-LABEL: monotonic_i128_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot615[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot615;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [monotonic_i128_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i128 %val, ptr addrspace(5) %slot syncscope("device") monotonic, align 16
    ret void
}

define void @monotonic_half_local_sys(half %val) {
; CHECK-LABEL: monotonic_half_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot616[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot616;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic half %val, ptr addrspace(5) %slot syncscope("") monotonic, align 2
    ret void
}

define void @monotonic_half_local_cta(half %val) {
; CHECK-LABEL: monotonic_half_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot617[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot617;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic half %val, ptr addrspace(5) %slot syncscope("block") monotonic, align 2
    ret void
}

define void @monotonic_half_local_cluster(half %val) {
; CHECK-LABEL: monotonic_half_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot618[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot618;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic half %val, ptr addrspace(5) %slot syncscope("cluster") monotonic, align 2
    ret void
}

define void @monotonic_half_local_gpu(half %val) {
; CHECK-LABEL: monotonic_half_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot619[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot619;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic half %val, ptr addrspace(5) %slot syncscope("device") monotonic, align 2
    ret void
}

define void @monotonic_half_local_sys_volatile(half %val) {
; CHECK-LABEL: monotonic_half_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot620[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot620;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile half %val, ptr addrspace(5) %slot syncscope("") monotonic, align 2
    ret void
}

define void @monotonic_half_local_cta_volatile(half %val) {
; CHECK-LABEL: monotonic_half_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot621[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot621;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile half %val, ptr addrspace(5) %slot syncscope("block") monotonic, align 2
    ret void
}

define void @monotonic_half_local_cluster_volatile(half %val) {
; CHECK-LABEL: monotonic_half_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot622[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot622;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile half %val, ptr addrspace(5) %slot syncscope("cluster") monotonic, align 2
    ret void
}

define void @monotonic_half_local_gpu_volatile(half %val) {
; CHECK-LABEL: monotonic_half_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot623[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot623;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_half_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile half %val, ptr addrspace(5) %slot syncscope("device") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_local_sys(bfloat %val) {
; CHECK-LABEL: monotonic_bfloat_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot624[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot624;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic bfloat %val, ptr addrspace(5) %slot syncscope("") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_local_cta(bfloat %val) {
; CHECK-LABEL: monotonic_bfloat_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot625[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot625;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic bfloat %val, ptr addrspace(5) %slot syncscope("block") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_local_cluster(bfloat %val) {
; CHECK-LABEL: monotonic_bfloat_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot626[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot626;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic bfloat %val, ptr addrspace(5) %slot syncscope("cluster") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_local_gpu(bfloat %val) {
; CHECK-LABEL: monotonic_bfloat_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot627[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot627;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic bfloat %val, ptr addrspace(5) %slot syncscope("device") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_local_sys_volatile(bfloat %val) {
; CHECK-LABEL: monotonic_bfloat_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot628[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot628;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile bfloat %val, ptr addrspace(5) %slot syncscope("") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_local_cta_volatile(bfloat %val) {
; CHECK-LABEL: monotonic_bfloat_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot629[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot629;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile bfloat %val, ptr addrspace(5) %slot syncscope("block") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_local_cluster_volatile(bfloat %val) {
; CHECK-LABEL: monotonic_bfloat_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot630[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot630;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile bfloat %val, ptr addrspace(5) %slot syncscope("cluster") monotonic, align 2
    ret void
}

define void @monotonic_bfloat_local_gpu_volatile(bfloat %val) {
; CHECK-LABEL: monotonic_bfloat_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot631[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot631;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [monotonic_bfloat_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile bfloat %val, ptr addrspace(5) %slot syncscope("device") monotonic, align 2
    ret void
}

define void @monotonic_float_local_sys(float %val) {
; CHECK-LABEL: monotonic_float_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot632[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot632;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [monotonic_float_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic float %val, ptr addrspace(5) %slot syncscope("") monotonic, align 4
    ret void
}

define void @monotonic_float_local_cta(float %val) {
; CHECK-LABEL: monotonic_float_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot633[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot633;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [monotonic_float_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic float %val, ptr addrspace(5) %slot syncscope("block") monotonic, align 4
    ret void
}

define void @monotonic_float_local_cluster(float %val) {
; CHECK-LABEL: monotonic_float_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot634[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot634;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [monotonic_float_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic float %val, ptr addrspace(5) %slot syncscope("cluster") monotonic, align 4
    ret void
}

define void @monotonic_float_local_gpu(float %val) {
; CHECK-LABEL: monotonic_float_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot635[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot635;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [monotonic_float_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic float %val, ptr addrspace(5) %slot syncscope("device") monotonic, align 4
    ret void
}

define void @monotonic_float_local_sys_volatile(float %val) {
; CHECK-LABEL: monotonic_float_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot636[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot636;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [monotonic_float_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile float %val, ptr addrspace(5) %slot syncscope("") monotonic, align 4
    ret void
}

define void @monotonic_float_local_cta_volatile(float %val) {
; CHECK-LABEL: monotonic_float_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot637[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot637;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [monotonic_float_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile float %val, ptr addrspace(5) %slot syncscope("block") monotonic, align 4
    ret void
}

define void @monotonic_float_local_cluster_volatile(float %val) {
; CHECK-LABEL: monotonic_float_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot638[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot638;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [monotonic_float_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile float %val, ptr addrspace(5) %slot syncscope("cluster") monotonic, align 4
    ret void
}

define void @monotonic_float_local_gpu_volatile(float %val) {
; CHECK-LABEL: monotonic_float_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot639[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot639;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [monotonic_float_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile float %val, ptr addrspace(5) %slot syncscope("device") monotonic, align 4
    ret void
}

define void @monotonic_double_local_sys(double %val) {
; CHECK-LABEL: monotonic_double_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot640[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot640;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic double %val, ptr addrspace(5) %slot syncscope("") monotonic, align 8
    ret void
}

define void @monotonic_double_local_cta(double %val) {
; CHECK-LABEL: monotonic_double_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot641[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot641;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic double %val, ptr addrspace(5) %slot syncscope("block") monotonic, align 8
    ret void
}

define void @monotonic_double_local_cluster(double %val) {
; CHECK-LABEL: monotonic_double_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot642[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot642;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic double %val, ptr addrspace(5) %slot syncscope("cluster") monotonic, align 8
    ret void
}

define void @monotonic_double_local_gpu(double %val) {
; CHECK-LABEL: monotonic_double_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot643[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot643;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic double %val, ptr addrspace(5) %slot syncscope("device") monotonic, align 8
    ret void
}

define void @monotonic_double_local_sys_volatile(double %val) {
; CHECK-LABEL: monotonic_double_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot644[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot644;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile double %val, ptr addrspace(5) %slot syncscope("") monotonic, align 8
    ret void
}

define void @monotonic_double_local_cta_volatile(double %val) {
; CHECK-LABEL: monotonic_double_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot645[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot645;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile double %val, ptr addrspace(5) %slot syncscope("block") monotonic, align 8
    ret void
}

define void @monotonic_double_local_cluster_volatile(double %val) {
; CHECK-LABEL: monotonic_double_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot646[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot646;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile double %val, ptr addrspace(5) %slot syncscope("cluster") monotonic, align 8
    ret void
}

define void @monotonic_double_local_gpu_volatile(double %val) {
; CHECK-LABEL: monotonic_double_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot647[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot647;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [monotonic_double_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile double %val, ptr addrspace(5) %slot syncscope("device") monotonic, align 8
    ret void
}

define void @release_i8_generic_sys(i8 %val, ptr %addr) {
; CHECK-LABEL: release_i8_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_generic_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i8_generic_sys_param_1];
; CHECK-NEXT:    st.release.sys.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr %addr syncscope("") release, align 1
    ret void
}

define void @release_i8_generic_cta(i8 %val, ptr %addr) {
; CHECK-LABEL: release_i8_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_generic_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i8_generic_cta_param_1];
; CHECK-NEXT:    st.release.cta.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr %addr syncscope("block") release, align 1
    ret void
}

define void @release_i8_generic_cluster(i8 %val, ptr %addr) {
; CHECK-LABEL: release_i8_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_generic_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i8_generic_cluster_param_1];
; CHECK-NEXT:    st.release.cluster.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr %addr syncscope("cluster") release, align 1
    ret void
}

define void @release_i8_generic_gpu(i8 %val, ptr %addr) {
; CHECK-LABEL: release_i8_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_generic_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i8_generic_gpu_param_1];
; CHECK-NEXT:    st.release.gpu.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr %addr syncscope("device") release, align 1
    ret void
}

define void @release_i8_generic_sys_volatile(i8 %val, ptr %addr) {
; CHECK-LABEL: release_i8_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_generic_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i8_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr %addr syncscope("") release, align 1
    ret void
}

define void @release_i8_generic_cta_volatile(i8 %val, ptr %addr) {
; CHECK-LABEL: release_i8_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_generic_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i8_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr %addr syncscope("block") release, align 1
    ret void
}

define void @release_i8_generic_cluster_volatile(i8 %val, ptr %addr) {
; CHECK-LABEL: release_i8_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_generic_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i8_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr %addr syncscope("cluster") release, align 1
    ret void
}

define void @release_i8_generic_gpu_volatile(i8 %val, ptr %addr) {
; CHECK-LABEL: release_i8_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_generic_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i8_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr %addr syncscope("device") release, align 1
    ret void
}

define void @release_i16_generic_sys(i16 %val, ptr %addr) {
; CHECK-LABEL: release_i16_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_generic_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i16_generic_sys_param_1];
; CHECK-NEXT:    st.release.sys.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr %addr syncscope("") release, align 2
    ret void
}

define void @release_i16_generic_cta(i16 %val, ptr %addr) {
; CHECK-LABEL: release_i16_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_generic_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i16_generic_cta_param_1];
; CHECK-NEXT:    st.release.cta.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr %addr syncscope("block") release, align 2
    ret void
}

define void @release_i16_generic_cluster(i16 %val, ptr %addr) {
; CHECK-LABEL: release_i16_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_generic_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i16_generic_cluster_param_1];
; CHECK-NEXT:    st.release.cluster.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr %addr syncscope("cluster") release, align 2
    ret void
}

define void @release_i16_generic_gpu(i16 %val, ptr %addr) {
; CHECK-LABEL: release_i16_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_generic_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i16_generic_gpu_param_1];
; CHECK-NEXT:    st.release.gpu.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr %addr syncscope("device") release, align 2
    ret void
}

define void @release_i16_generic_sys_volatile(i16 %val, ptr %addr) {
; CHECK-LABEL: release_i16_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_generic_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i16_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr %addr syncscope("") release, align 2
    ret void
}

define void @release_i16_generic_cta_volatile(i16 %val, ptr %addr) {
; CHECK-LABEL: release_i16_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_generic_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i16_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr %addr syncscope("block") release, align 2
    ret void
}

define void @release_i16_generic_cluster_volatile(i16 %val, ptr %addr) {
; CHECK-LABEL: release_i16_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_generic_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i16_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr %addr syncscope("cluster") release, align 2
    ret void
}

define void @release_i16_generic_gpu_volatile(i16 %val, ptr %addr) {
; CHECK-LABEL: release_i16_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_generic_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i16_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr %addr syncscope("device") release, align 2
    ret void
}

define void @release_i32_generic_sys(i32 %val, ptr %addr) {
; CHECK-LABEL: release_i32_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_i32_generic_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i32_generic_sys_param_1];
; CHECK-NEXT:    st.release.sys.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr %addr syncscope("") release, align 4
    ret void
}

define void @release_i32_generic_cta(i32 %val, ptr %addr) {
; CHECK-LABEL: release_i32_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_i32_generic_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i32_generic_cta_param_1];
; CHECK-NEXT:    st.release.cta.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr %addr syncscope("block") release, align 4
    ret void
}

define void @release_i32_generic_cluster(i32 %val, ptr %addr) {
; CHECK-LABEL: release_i32_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_i32_generic_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i32_generic_cluster_param_1];
; CHECK-NEXT:    st.release.cluster.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr %addr syncscope("cluster") release, align 4
    ret void
}

define void @release_i32_generic_gpu(i32 %val, ptr %addr) {
; CHECK-LABEL: release_i32_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_i32_generic_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i32_generic_gpu_param_1];
; CHECK-NEXT:    st.release.gpu.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr %addr syncscope("device") release, align 4
    ret void
}

define void @release_i32_generic_sys_volatile(i32 %val, ptr %addr) {
; CHECK-LABEL: release_i32_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_i32_generic_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i32_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr %addr syncscope("") release, align 4
    ret void
}

define void @release_i32_generic_cta_volatile(i32 %val, ptr %addr) {
; CHECK-LABEL: release_i32_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_i32_generic_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i32_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr %addr syncscope("block") release, align 4
    ret void
}

define void @release_i32_generic_cluster_volatile(i32 %val, ptr %addr) {
; CHECK-LABEL: release_i32_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_i32_generic_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i32_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr %addr syncscope("cluster") release, align 4
    ret void
}

define void @release_i32_generic_gpu_volatile(i32 %val, ptr %addr) {
; CHECK-LABEL: release_i32_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_i32_generic_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i32_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr %addr syncscope("device") release, align 4
    ret void
}

define void @release_i64_generic_sys(i64 %val, ptr %addr) {
; CHECK-LABEL: release_i64_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_generic_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_i64_generic_sys_param_1];
; CHECK-NEXT:    st.release.sys.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr %addr syncscope("") release, align 8
    ret void
}

define void @release_i64_generic_cta(i64 %val, ptr %addr) {
; CHECK-LABEL: release_i64_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_generic_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_i64_generic_cta_param_1];
; CHECK-NEXT:    st.release.cta.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr %addr syncscope("block") release, align 8
    ret void
}

define void @release_i64_generic_cluster(i64 %val, ptr %addr) {
; CHECK-LABEL: release_i64_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_generic_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_i64_generic_cluster_param_1];
; CHECK-NEXT:    st.release.cluster.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr %addr syncscope("cluster") release, align 8
    ret void
}

define void @release_i64_generic_gpu(i64 %val, ptr %addr) {
; CHECK-LABEL: release_i64_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_generic_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_i64_generic_gpu_param_1];
; CHECK-NEXT:    st.release.gpu.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr %addr syncscope("device") release, align 8
    ret void
}

define void @release_i64_generic_sys_volatile(i64 %val, ptr %addr) {
; CHECK-LABEL: release_i64_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_generic_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_i64_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr %addr syncscope("") release, align 8
    ret void
}

define void @release_i64_generic_cta_volatile(i64 %val, ptr %addr) {
; CHECK-LABEL: release_i64_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_generic_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_i64_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr %addr syncscope("block") release, align 8
    ret void
}

define void @release_i64_generic_cluster_volatile(i64 %val, ptr %addr) {
; CHECK-LABEL: release_i64_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_generic_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_i64_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr %addr syncscope("cluster") release, align 8
    ret void
}

define void @release_i64_generic_gpu_volatile(i64 %val, ptr %addr) {
; CHECK-LABEL: release_i64_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_generic_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_i64_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr %addr syncscope("device") release, align 8
    ret void
}

define void @release_i128_generic_sys(i128 %val, ptr %addr) {
; CHECK-LABEL: release_i128_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_generic_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [release_i128_generic_sys_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.release.sys.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr %addr syncscope("") release, align 16
    ret void
}

define void @release_i128_generic_cta(i128 %val, ptr %addr) {
; CHECK-LABEL: release_i128_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_generic_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [release_i128_generic_cta_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.release.cta.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr %addr syncscope("block") release, align 16
    ret void
}

define void @release_i128_generic_cluster(i128 %val, ptr %addr) {
; CHECK-LABEL: release_i128_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_generic_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [release_i128_generic_cluster_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.release.cluster.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr %addr syncscope("cluster") release, align 16
    ret void
}

define void @release_i128_generic_gpu(i128 %val, ptr %addr) {
; CHECK-LABEL: release_i128_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_generic_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [release_i128_generic_gpu_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.release.gpu.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr %addr syncscope("device") release, align 16
    ret void
}

define void @release_i128_generic_sys_volatile(i128 %val, ptr %addr) {
; CHECK-LABEL: release_i128_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_generic_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [release_i128_generic_sys_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.release.sys.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr %addr syncscope("") release, align 16
    ret void
}

define void @release_i128_generic_cta_volatile(i128 %val, ptr %addr) {
; CHECK-LABEL: release_i128_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_generic_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [release_i128_generic_cta_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.release.cta.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr %addr syncscope("block") release, align 16
    ret void
}

define void @release_i128_generic_cluster_volatile(i128 %val, ptr %addr) {
; CHECK-LABEL: release_i128_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_generic_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [release_i128_generic_cluster_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.release.cluster.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr %addr syncscope("cluster") release, align 16
    ret void
}

define void @release_i128_generic_gpu_volatile(i128 %val, ptr %addr) {
; CHECK-LABEL: release_i128_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_generic_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [release_i128_generic_gpu_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.release.gpu.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr %addr syncscope("device") release, align 16
    ret void
}

define void @release_half_generic_sys(half %val, ptr %addr) {
; CHECK-LABEL: release_half_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_generic_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_half_generic_sys_param_1];
; CHECK-NEXT:    st.release.sys.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr %addr syncscope("") release, align 2
    ret void
}

define void @release_half_generic_cta(half %val, ptr %addr) {
; CHECK-LABEL: release_half_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_generic_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_half_generic_cta_param_1];
; CHECK-NEXT:    st.release.cta.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr %addr syncscope("block") release, align 2
    ret void
}

define void @release_half_generic_cluster(half %val, ptr %addr) {
; CHECK-LABEL: release_half_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_generic_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_half_generic_cluster_param_1];
; CHECK-NEXT:    st.release.cluster.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr %addr syncscope("cluster") release, align 2
    ret void
}

define void @release_half_generic_gpu(half %val, ptr %addr) {
; CHECK-LABEL: release_half_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_generic_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_half_generic_gpu_param_1];
; CHECK-NEXT:    st.release.gpu.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr %addr syncscope("device") release, align 2
    ret void
}

define void @release_half_generic_sys_volatile(half %val, ptr %addr) {
; CHECK-LABEL: release_half_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_generic_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_half_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr %addr syncscope("") release, align 2
    ret void
}

define void @release_half_generic_cta_volatile(half %val, ptr %addr) {
; CHECK-LABEL: release_half_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_generic_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_half_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr %addr syncscope("block") release, align 2
    ret void
}

define void @release_half_generic_cluster_volatile(half %val, ptr %addr) {
; CHECK-LABEL: release_half_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_generic_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_half_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr %addr syncscope("cluster") release, align 2
    ret void
}

define void @release_half_generic_gpu_volatile(half %val, ptr %addr) {
; CHECK-LABEL: release_half_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_generic_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_half_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr %addr syncscope("device") release, align 2
    ret void
}

define void @release_bfloat_generic_sys(bfloat %val, ptr %addr) {
; CHECK-LABEL: release_bfloat_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_generic_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_bfloat_generic_sys_param_1];
; CHECK-NEXT:    st.release.sys.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr %addr syncscope("") release, align 2
    ret void
}

define void @release_bfloat_generic_cta(bfloat %val, ptr %addr) {
; CHECK-LABEL: release_bfloat_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_generic_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_bfloat_generic_cta_param_1];
; CHECK-NEXT:    st.release.cta.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr %addr syncscope("block") release, align 2
    ret void
}

define void @release_bfloat_generic_cluster(bfloat %val, ptr %addr) {
; CHECK-LABEL: release_bfloat_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_generic_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_bfloat_generic_cluster_param_1];
; CHECK-NEXT:    st.release.cluster.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr %addr syncscope("cluster") release, align 2
    ret void
}

define void @release_bfloat_generic_gpu(bfloat %val, ptr %addr) {
; CHECK-LABEL: release_bfloat_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_generic_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_bfloat_generic_gpu_param_1];
; CHECK-NEXT:    st.release.gpu.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr %addr syncscope("device") release, align 2
    ret void
}

define void @release_bfloat_generic_sys_volatile(bfloat %val, ptr %addr) {
; CHECK-LABEL: release_bfloat_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_generic_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_bfloat_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr %addr syncscope("") release, align 2
    ret void
}

define void @release_bfloat_generic_cta_volatile(bfloat %val, ptr %addr) {
; CHECK-LABEL: release_bfloat_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_generic_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_bfloat_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr %addr syncscope("block") release, align 2
    ret void
}

define void @release_bfloat_generic_cluster_volatile(bfloat %val, ptr %addr) {
; CHECK-LABEL: release_bfloat_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_generic_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_bfloat_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr %addr syncscope("cluster") release, align 2
    ret void
}

define void @release_bfloat_generic_gpu_volatile(bfloat %val, ptr %addr) {
; CHECK-LABEL: release_bfloat_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_generic_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_bfloat_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr %addr syncscope("device") release, align 2
    ret void
}

define void @release_float_generic_sys(float %val, ptr %addr) {
; CHECK-LABEL: release_float_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_float_generic_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_float_generic_sys_param_1];
; CHECK-NEXT:    st.release.sys.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr %addr syncscope("") release, align 4
    ret void
}

define void @release_float_generic_cta(float %val, ptr %addr) {
; CHECK-LABEL: release_float_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_float_generic_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_float_generic_cta_param_1];
; CHECK-NEXT:    st.release.cta.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr %addr syncscope("block") release, align 4
    ret void
}

define void @release_float_generic_cluster(float %val, ptr %addr) {
; CHECK-LABEL: release_float_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_float_generic_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_float_generic_cluster_param_1];
; CHECK-NEXT:    st.release.cluster.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr %addr syncscope("cluster") release, align 4
    ret void
}

define void @release_float_generic_gpu(float %val, ptr %addr) {
; CHECK-LABEL: release_float_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_float_generic_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_float_generic_gpu_param_1];
; CHECK-NEXT:    st.release.gpu.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr %addr syncscope("device") release, align 4
    ret void
}

define void @release_float_generic_sys_volatile(float %val, ptr %addr) {
; CHECK-LABEL: release_float_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_float_generic_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_float_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr %addr syncscope("") release, align 4
    ret void
}

define void @release_float_generic_cta_volatile(float %val, ptr %addr) {
; CHECK-LABEL: release_float_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_float_generic_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_float_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr %addr syncscope("block") release, align 4
    ret void
}

define void @release_float_generic_cluster_volatile(float %val, ptr %addr) {
; CHECK-LABEL: release_float_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_float_generic_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_float_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr %addr syncscope("cluster") release, align 4
    ret void
}

define void @release_float_generic_gpu_volatile(float %val, ptr %addr) {
; CHECK-LABEL: release_float_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_float_generic_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_float_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr %addr syncscope("device") release, align 4
    ret void
}

define void @release_double_generic_sys(double %val, ptr %addr) {
; CHECK-LABEL: release_double_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_generic_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_double_generic_sys_param_1];
; CHECK-NEXT:    st.release.sys.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr %addr syncscope("") release, align 8
    ret void
}

define void @release_double_generic_cta(double %val, ptr %addr) {
; CHECK-LABEL: release_double_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_generic_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_double_generic_cta_param_1];
; CHECK-NEXT:    st.release.cta.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr %addr syncscope("block") release, align 8
    ret void
}

define void @release_double_generic_cluster(double %val, ptr %addr) {
; CHECK-LABEL: release_double_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_generic_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_double_generic_cluster_param_1];
; CHECK-NEXT:    st.release.cluster.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr %addr syncscope("cluster") release, align 8
    ret void
}

define void @release_double_generic_gpu(double %val, ptr %addr) {
; CHECK-LABEL: release_double_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_generic_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_double_generic_gpu_param_1];
; CHECK-NEXT:    st.release.gpu.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr %addr syncscope("device") release, align 8
    ret void
}

define void @release_double_generic_sys_volatile(double %val, ptr %addr) {
; CHECK-LABEL: release_double_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_generic_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_double_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr %addr syncscope("") release, align 8
    ret void
}

define void @release_double_generic_cta_volatile(double %val, ptr %addr) {
; CHECK-LABEL: release_double_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_generic_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_double_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr %addr syncscope("block") release, align 8
    ret void
}

define void @release_double_generic_cluster_volatile(double %val, ptr %addr) {
; CHECK-LABEL: release_double_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_generic_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_double_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr %addr syncscope("cluster") release, align 8
    ret void
}

define void @release_double_generic_gpu_volatile(double %val, ptr %addr) {
; CHECK-LABEL: release_double_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_generic_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_double_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.release.sys.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr %addr syncscope("device") release, align 8
    ret void
}

define void @release_i8_global_sys(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i8_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_global_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i8_global_sys_param_1];
; CHECK-NEXT:    st.release.sys.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(1) %addr syncscope("") release, align 1
    ret void
}

define void @release_i8_global_cta(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i8_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_global_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i8_global_cta_param_1];
; CHECK-NEXT:    st.release.cta.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(1) %addr syncscope("block") release, align 1
    ret void
}

define void @release_i8_global_cluster(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i8_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_global_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i8_global_cluster_param_1];
; CHECK-NEXT:    st.release.cluster.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(1) %addr syncscope("cluster") release, align 1
    ret void
}

define void @release_i8_global_gpu(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i8_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_global_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i8_global_gpu_param_1];
; CHECK-NEXT:    st.release.gpu.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(1) %addr syncscope("device") release, align 1
    ret void
}

define void @release_i8_global_sys_volatile(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i8_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_global_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i8_global_sys_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(1) %addr syncscope("") release, align 1
    ret void
}

define void @release_i8_global_cta_volatile(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i8_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_global_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i8_global_cta_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(1) %addr syncscope("block") release, align 1
    ret void
}

define void @release_i8_global_cluster_volatile(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i8_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_global_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i8_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(1) %addr syncscope("cluster") release, align 1
    ret void
}

define void @release_i8_global_gpu_volatile(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i8_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_global_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i8_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(1) %addr syncscope("device") release, align 1
    ret void
}

define void @release_i16_global_sys(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i16_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_global_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i16_global_sys_param_1];
; CHECK-NEXT:    st.release.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(1) %addr syncscope("") release, align 2
    ret void
}

define void @release_i16_global_cta(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i16_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_global_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i16_global_cta_param_1];
; CHECK-NEXT:    st.release.cta.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(1) %addr syncscope("block") release, align 2
    ret void
}

define void @release_i16_global_cluster(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i16_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_global_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i16_global_cluster_param_1];
; CHECK-NEXT:    st.release.cluster.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(1) %addr syncscope("cluster") release, align 2
    ret void
}

define void @release_i16_global_gpu(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i16_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_global_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i16_global_gpu_param_1];
; CHECK-NEXT:    st.release.gpu.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(1) %addr syncscope("device") release, align 2
    ret void
}

define void @release_i16_global_sys_volatile(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i16_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_global_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i16_global_sys_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(1) %addr syncscope("") release, align 2
    ret void
}

define void @release_i16_global_cta_volatile(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i16_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_global_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i16_global_cta_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(1) %addr syncscope("block") release, align 2
    ret void
}

define void @release_i16_global_cluster_volatile(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i16_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_global_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i16_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(1) %addr syncscope("cluster") release, align 2
    ret void
}

define void @release_i16_global_gpu_volatile(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i16_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_global_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i16_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(1) %addr syncscope("device") release, align 2
    ret void
}

define void @release_i32_global_sys(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i32_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_i32_global_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i32_global_sys_param_1];
; CHECK-NEXT:    st.release.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(1) %addr syncscope("") release, align 4
    ret void
}

define void @release_i32_global_cta(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i32_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_i32_global_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i32_global_cta_param_1];
; CHECK-NEXT:    st.release.cta.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(1) %addr syncscope("block") release, align 4
    ret void
}

define void @release_i32_global_cluster(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i32_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_i32_global_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i32_global_cluster_param_1];
; CHECK-NEXT:    st.release.cluster.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(1) %addr syncscope("cluster") release, align 4
    ret void
}

define void @release_i32_global_gpu(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i32_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_i32_global_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i32_global_gpu_param_1];
; CHECK-NEXT:    st.release.gpu.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(1) %addr syncscope("device") release, align 4
    ret void
}

define void @release_i32_global_sys_volatile(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i32_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_i32_global_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i32_global_sys_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(1) %addr syncscope("") release, align 4
    ret void
}

define void @release_i32_global_cta_volatile(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i32_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_i32_global_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i32_global_cta_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(1) %addr syncscope("block") release, align 4
    ret void
}

define void @release_i32_global_cluster_volatile(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i32_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_i32_global_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i32_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(1) %addr syncscope("cluster") release, align 4
    ret void
}

define void @release_i32_global_gpu_volatile(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i32_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_i32_global_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i32_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(1) %addr syncscope("device") release, align 4
    ret void
}

define void @release_i64_global_sys(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i64_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_global_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_i64_global_sys_param_1];
; CHECK-NEXT:    st.release.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(1) %addr syncscope("") release, align 8
    ret void
}

define void @release_i64_global_cta(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i64_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_global_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_i64_global_cta_param_1];
; CHECK-NEXT:    st.release.cta.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(1) %addr syncscope("block") release, align 8
    ret void
}

define void @release_i64_global_cluster(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i64_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_global_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_i64_global_cluster_param_1];
; CHECK-NEXT:    st.release.cluster.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(1) %addr syncscope("cluster") release, align 8
    ret void
}

define void @release_i64_global_gpu(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i64_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_global_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_i64_global_gpu_param_1];
; CHECK-NEXT:    st.release.gpu.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(1) %addr syncscope("device") release, align 8
    ret void
}

define void @release_i64_global_sys_volatile(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i64_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_global_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_i64_global_sys_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(1) %addr syncscope("") release, align 8
    ret void
}

define void @release_i64_global_cta_volatile(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i64_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_global_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_i64_global_cta_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(1) %addr syncscope("block") release, align 8
    ret void
}

define void @release_i64_global_cluster_volatile(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i64_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_global_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_i64_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(1) %addr syncscope("cluster") release, align 8
    ret void
}

define void @release_i64_global_gpu_volatile(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i64_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_global_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_i64_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(1) %addr syncscope("device") release, align 8
    ret void
}

define void @release_i128_global_sys(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i128_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_global_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [release_i128_global_sys_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.release.sys.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(1) %addr syncscope("") release, align 16
    ret void
}

define void @release_i128_global_cta(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i128_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_global_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [release_i128_global_cta_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.release.cta.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(1) %addr syncscope("block") release, align 16
    ret void
}

define void @release_i128_global_cluster(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i128_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_global_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [release_i128_global_cluster_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.release.cluster.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(1) %addr syncscope("cluster") release, align 16
    ret void
}

define void @release_i128_global_gpu(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i128_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_global_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [release_i128_global_gpu_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.release.gpu.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(1) %addr syncscope("device") release, align 16
    ret void
}

define void @release_i128_global_sys_volatile(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i128_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_global_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [release_i128_global_sys_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.release.sys.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(1) %addr syncscope("") release, align 16
    ret void
}

define void @release_i128_global_cta_volatile(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i128_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_global_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [release_i128_global_cta_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.release.cta.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(1) %addr syncscope("block") release, align 16
    ret void
}

define void @release_i128_global_cluster_volatile(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i128_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_global_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [release_i128_global_cluster_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.release.cluster.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(1) %addr syncscope("cluster") release, align 16
    ret void
}

define void @release_i128_global_gpu_volatile(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_i128_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_global_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [release_i128_global_gpu_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.release.gpu.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(1) %addr syncscope("device") release, align 16
    ret void
}

define void @release_half_global_sys(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_half_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_global_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_half_global_sys_param_1];
; CHECK-NEXT:    st.release.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(1) %addr syncscope("") release, align 2
    ret void
}

define void @release_half_global_cta(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_half_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_global_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_half_global_cta_param_1];
; CHECK-NEXT:    st.release.cta.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(1) %addr syncscope("block") release, align 2
    ret void
}

define void @release_half_global_cluster(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_half_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_global_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_half_global_cluster_param_1];
; CHECK-NEXT:    st.release.cluster.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(1) %addr syncscope("cluster") release, align 2
    ret void
}

define void @release_half_global_gpu(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_half_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_global_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_half_global_gpu_param_1];
; CHECK-NEXT:    st.release.gpu.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(1) %addr syncscope("device") release, align 2
    ret void
}

define void @release_half_global_sys_volatile(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_half_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_global_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_half_global_sys_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(1) %addr syncscope("") release, align 2
    ret void
}

define void @release_half_global_cta_volatile(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_half_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_global_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_half_global_cta_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(1) %addr syncscope("block") release, align 2
    ret void
}

define void @release_half_global_cluster_volatile(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_half_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_global_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_half_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(1) %addr syncscope("cluster") release, align 2
    ret void
}

define void @release_half_global_gpu_volatile(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_half_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_global_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_half_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(1) %addr syncscope("device") release, align 2
    ret void
}

define void @release_bfloat_global_sys(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_bfloat_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_global_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_bfloat_global_sys_param_1];
; CHECK-NEXT:    st.release.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(1) %addr syncscope("") release, align 2
    ret void
}

define void @release_bfloat_global_cta(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_bfloat_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_global_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_bfloat_global_cta_param_1];
; CHECK-NEXT:    st.release.cta.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(1) %addr syncscope("block") release, align 2
    ret void
}

define void @release_bfloat_global_cluster(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_bfloat_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_global_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_bfloat_global_cluster_param_1];
; CHECK-NEXT:    st.release.cluster.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(1) %addr syncscope("cluster") release, align 2
    ret void
}

define void @release_bfloat_global_gpu(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_bfloat_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_global_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_bfloat_global_gpu_param_1];
; CHECK-NEXT:    st.release.gpu.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(1) %addr syncscope("device") release, align 2
    ret void
}

define void @release_bfloat_global_sys_volatile(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_bfloat_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_global_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_bfloat_global_sys_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(1) %addr syncscope("") release, align 2
    ret void
}

define void @release_bfloat_global_cta_volatile(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_bfloat_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_global_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_bfloat_global_cta_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(1) %addr syncscope("block") release, align 2
    ret void
}

define void @release_bfloat_global_cluster_volatile(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_bfloat_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_global_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_bfloat_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(1) %addr syncscope("cluster") release, align 2
    ret void
}

define void @release_bfloat_global_gpu_volatile(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_bfloat_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_global_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_bfloat_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(1) %addr syncscope("device") release, align 2
    ret void
}

define void @release_float_global_sys(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_float_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_float_global_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_float_global_sys_param_1];
; CHECK-NEXT:    st.release.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(1) %addr syncscope("") release, align 4
    ret void
}

define void @release_float_global_cta(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_float_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_float_global_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_float_global_cta_param_1];
; CHECK-NEXT:    st.release.cta.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(1) %addr syncscope("block") release, align 4
    ret void
}

define void @release_float_global_cluster(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_float_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_float_global_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_float_global_cluster_param_1];
; CHECK-NEXT:    st.release.cluster.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(1) %addr syncscope("cluster") release, align 4
    ret void
}

define void @release_float_global_gpu(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_float_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_float_global_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_float_global_gpu_param_1];
; CHECK-NEXT:    st.release.gpu.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(1) %addr syncscope("device") release, align 4
    ret void
}

define void @release_float_global_sys_volatile(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_float_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_float_global_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_float_global_sys_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(1) %addr syncscope("") release, align 4
    ret void
}

define void @release_float_global_cta_volatile(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_float_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_float_global_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_float_global_cta_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(1) %addr syncscope("block") release, align 4
    ret void
}

define void @release_float_global_cluster_volatile(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_float_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_float_global_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_float_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(1) %addr syncscope("cluster") release, align 4
    ret void
}

define void @release_float_global_gpu_volatile(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_float_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_float_global_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_float_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(1) %addr syncscope("device") release, align 4
    ret void
}

define void @release_double_global_sys(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_double_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_global_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_double_global_sys_param_1];
; CHECK-NEXT:    st.release.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(1) %addr syncscope("") release, align 8
    ret void
}

define void @release_double_global_cta(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_double_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_global_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_double_global_cta_param_1];
; CHECK-NEXT:    st.release.cta.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(1) %addr syncscope("block") release, align 8
    ret void
}

define void @release_double_global_cluster(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_double_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_global_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_double_global_cluster_param_1];
; CHECK-NEXT:    st.release.cluster.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(1) %addr syncscope("cluster") release, align 8
    ret void
}

define void @release_double_global_gpu(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_double_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_global_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_double_global_gpu_param_1];
; CHECK-NEXT:    st.release.gpu.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(1) %addr syncscope("device") release, align 8
    ret void
}

define void @release_double_global_sys_volatile(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_double_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_global_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_double_global_sys_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(1) %addr syncscope("") release, align 8
    ret void
}

define void @release_double_global_cta_volatile(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_double_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_global_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_double_global_cta_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(1) %addr syncscope("block") release, align 8
    ret void
}

define void @release_double_global_cluster_volatile(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_double_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_global_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_double_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(1) %addr syncscope("cluster") release, align 8
    ret void
}

define void @release_double_global_gpu_volatile(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: release_double_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_global_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_double_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.release.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(1) %addr syncscope("device") release, align 8
    ret void
}

define void @release_i8_shared_sys(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i8_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_shared_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i8_shared_sys_param_1];
; CHECK-NEXT:    st.release.sys.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(3) %addr syncscope("") release, align 1
    ret void
}

define void @release_i8_shared_cta(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i8_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_shared_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i8_shared_cta_param_1];
; CHECK-NEXT:    st.release.cta.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(3) %addr syncscope("block") release, align 1
    ret void
}

define void @release_i8_shared_cluster(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i8_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_shared_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i8_shared_cluster_param_1];
; CHECK-NEXT:    st.release.cluster.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(3) %addr syncscope("cluster") release, align 1
    ret void
}

define void @release_i8_shared_gpu(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i8_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_shared_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i8_shared_gpu_param_1];
; CHECK-NEXT:    st.release.gpu.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(3) %addr syncscope("device") release, align 1
    ret void
}

define void @release_i8_shared_sys_volatile(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i8_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_shared_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i8_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(3) %addr syncscope("") release, align 1
    ret void
}

define void @release_i8_shared_cta_volatile(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i8_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_shared_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i8_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(3) %addr syncscope("block") release, align 1
    ret void
}

define void @release_i8_shared_cluster_volatile(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i8_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_shared_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i8_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(3) %addr syncscope("cluster") release, align 1
    ret void
}

define void @release_i8_shared_gpu_volatile(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i8_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_shared_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i8_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(3) %addr syncscope("device") release, align 1
    ret void
}

define void @release_i16_shared_sys(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i16_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_shared_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i16_shared_sys_param_1];
; CHECK-NEXT:    st.release.sys.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(3) %addr syncscope("") release, align 2
    ret void
}

define void @release_i16_shared_cta(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i16_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_shared_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i16_shared_cta_param_1];
; CHECK-NEXT:    st.release.cta.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(3) %addr syncscope("block") release, align 2
    ret void
}

define void @release_i16_shared_cluster(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i16_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_shared_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i16_shared_cluster_param_1];
; CHECK-NEXT:    st.release.cluster.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(3) %addr syncscope("cluster") release, align 2
    ret void
}

define void @release_i16_shared_gpu(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i16_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_shared_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i16_shared_gpu_param_1];
; CHECK-NEXT:    st.release.gpu.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(3) %addr syncscope("device") release, align 2
    ret void
}

define void @release_i16_shared_sys_volatile(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i16_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_shared_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i16_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(3) %addr syncscope("") release, align 2
    ret void
}

define void @release_i16_shared_cta_volatile(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i16_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_shared_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i16_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(3) %addr syncscope("block") release, align 2
    ret void
}

define void @release_i16_shared_cluster_volatile(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i16_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_shared_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i16_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(3) %addr syncscope("cluster") release, align 2
    ret void
}

define void @release_i16_shared_gpu_volatile(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i16_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_shared_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i16_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(3) %addr syncscope("device") release, align 2
    ret void
}

define void @release_i32_shared_sys(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i32_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_i32_shared_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i32_shared_sys_param_1];
; CHECK-NEXT:    st.release.sys.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(3) %addr syncscope("") release, align 4
    ret void
}

define void @release_i32_shared_cta(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i32_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_i32_shared_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i32_shared_cta_param_1];
; CHECK-NEXT:    st.release.cta.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(3) %addr syncscope("block") release, align 4
    ret void
}

define void @release_i32_shared_cluster(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i32_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_i32_shared_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i32_shared_cluster_param_1];
; CHECK-NEXT:    st.release.cluster.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(3) %addr syncscope("cluster") release, align 4
    ret void
}

define void @release_i32_shared_gpu(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i32_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_i32_shared_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i32_shared_gpu_param_1];
; CHECK-NEXT:    st.release.gpu.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(3) %addr syncscope("device") release, align 4
    ret void
}

define void @release_i32_shared_sys_volatile(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i32_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_i32_shared_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i32_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(3) %addr syncscope("") release, align 4
    ret void
}

define void @release_i32_shared_cta_volatile(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i32_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_i32_shared_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i32_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(3) %addr syncscope("block") release, align 4
    ret void
}

define void @release_i32_shared_cluster_volatile(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i32_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_i32_shared_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i32_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(3) %addr syncscope("cluster") release, align 4
    ret void
}

define void @release_i32_shared_gpu_volatile(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i32_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_i32_shared_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i32_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(3) %addr syncscope("device") release, align 4
    ret void
}

define void @release_i64_shared_sys(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i64_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_shared_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_i64_shared_sys_param_1];
; CHECK-NEXT:    st.release.sys.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(3) %addr syncscope("") release, align 8
    ret void
}

define void @release_i64_shared_cta(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i64_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_shared_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_i64_shared_cta_param_1];
; CHECK-NEXT:    st.release.cta.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(3) %addr syncscope("block") release, align 8
    ret void
}

define void @release_i64_shared_cluster(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i64_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_shared_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_i64_shared_cluster_param_1];
; CHECK-NEXT:    st.release.cluster.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(3) %addr syncscope("cluster") release, align 8
    ret void
}

define void @release_i64_shared_gpu(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i64_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_shared_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_i64_shared_gpu_param_1];
; CHECK-NEXT:    st.release.gpu.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(3) %addr syncscope("device") release, align 8
    ret void
}

define void @release_i64_shared_sys_volatile(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i64_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_shared_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_i64_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(3) %addr syncscope("") release, align 8
    ret void
}

define void @release_i64_shared_cta_volatile(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i64_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_shared_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_i64_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(3) %addr syncscope("block") release, align 8
    ret void
}

define void @release_i64_shared_cluster_volatile(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i64_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_shared_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_i64_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(3) %addr syncscope("cluster") release, align 8
    ret void
}

define void @release_i64_shared_gpu_volatile(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i64_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_shared_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_i64_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(3) %addr syncscope("device") release, align 8
    ret void
}

define void @release_i128_shared_sys(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i128_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_shared_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [release_i128_shared_sys_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.release.sys.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(3) %addr syncscope("") release, align 16
    ret void
}

define void @release_i128_shared_cta(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i128_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_shared_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [release_i128_shared_cta_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.release.cta.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(3) %addr syncscope("block") release, align 16
    ret void
}

define void @release_i128_shared_cluster(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i128_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_shared_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [release_i128_shared_cluster_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.release.cluster.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(3) %addr syncscope("cluster") release, align 16
    ret void
}

define void @release_i128_shared_gpu(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i128_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_shared_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [release_i128_shared_gpu_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.release.gpu.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(3) %addr syncscope("device") release, align 16
    ret void
}

define void @release_i128_shared_sys_volatile(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i128_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_shared_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [release_i128_shared_sys_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.release.sys.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(3) %addr syncscope("") release, align 16
    ret void
}

define void @release_i128_shared_cta_volatile(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i128_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_shared_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [release_i128_shared_cta_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.release.cta.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(3) %addr syncscope("block") release, align 16
    ret void
}

define void @release_i128_shared_cluster_volatile(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i128_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_shared_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [release_i128_shared_cluster_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.release.cluster.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(3) %addr syncscope("cluster") release, align 16
    ret void
}

define void @release_i128_shared_gpu_volatile(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_i128_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_shared_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd3, [release_i128_shared_gpu_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.release.gpu.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(3) %addr syncscope("device") release, align 16
    ret void
}

define void @release_half_shared_sys(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_half_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_shared_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_half_shared_sys_param_1];
; CHECK-NEXT:    st.release.sys.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(3) %addr syncscope("") release, align 2
    ret void
}

define void @release_half_shared_cta(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_half_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_shared_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_half_shared_cta_param_1];
; CHECK-NEXT:    st.release.cta.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(3) %addr syncscope("block") release, align 2
    ret void
}

define void @release_half_shared_cluster(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_half_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_shared_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_half_shared_cluster_param_1];
; CHECK-NEXT:    st.release.cluster.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(3) %addr syncscope("cluster") release, align 2
    ret void
}

define void @release_half_shared_gpu(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_half_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_shared_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_half_shared_gpu_param_1];
; CHECK-NEXT:    st.release.gpu.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(3) %addr syncscope("device") release, align 2
    ret void
}

define void @release_half_shared_sys_volatile(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_half_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_shared_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_half_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(3) %addr syncscope("") release, align 2
    ret void
}

define void @release_half_shared_cta_volatile(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_half_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_shared_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_half_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(3) %addr syncscope("block") release, align 2
    ret void
}

define void @release_half_shared_cluster_volatile(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_half_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_shared_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_half_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(3) %addr syncscope("cluster") release, align 2
    ret void
}

define void @release_half_shared_gpu_volatile(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_half_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_shared_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_half_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(3) %addr syncscope("device") release, align 2
    ret void
}

define void @release_bfloat_shared_sys(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_bfloat_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_shared_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_bfloat_shared_sys_param_1];
; CHECK-NEXT:    st.release.sys.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(3) %addr syncscope("") release, align 2
    ret void
}

define void @release_bfloat_shared_cta(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_bfloat_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_shared_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_bfloat_shared_cta_param_1];
; CHECK-NEXT:    st.release.cta.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(3) %addr syncscope("block") release, align 2
    ret void
}

define void @release_bfloat_shared_cluster(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_bfloat_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_shared_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_bfloat_shared_cluster_param_1];
; CHECK-NEXT:    st.release.cluster.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(3) %addr syncscope("cluster") release, align 2
    ret void
}

define void @release_bfloat_shared_gpu(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_bfloat_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_shared_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_bfloat_shared_gpu_param_1];
; CHECK-NEXT:    st.release.gpu.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(3) %addr syncscope("device") release, align 2
    ret void
}

define void @release_bfloat_shared_sys_volatile(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_bfloat_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_shared_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_bfloat_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(3) %addr syncscope("") release, align 2
    ret void
}

define void @release_bfloat_shared_cta_volatile(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_bfloat_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_shared_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_bfloat_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(3) %addr syncscope("block") release, align 2
    ret void
}

define void @release_bfloat_shared_cluster_volatile(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_bfloat_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_shared_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_bfloat_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(3) %addr syncscope("cluster") release, align 2
    ret void
}

define void @release_bfloat_shared_gpu_volatile(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_bfloat_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_shared_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_bfloat_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(3) %addr syncscope("device") release, align 2
    ret void
}

define void @release_float_shared_sys(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_float_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_float_shared_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_float_shared_sys_param_1];
; CHECK-NEXT:    st.release.sys.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(3) %addr syncscope("") release, align 4
    ret void
}

define void @release_float_shared_cta(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_float_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_float_shared_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_float_shared_cta_param_1];
; CHECK-NEXT:    st.release.cta.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(3) %addr syncscope("block") release, align 4
    ret void
}

define void @release_float_shared_cluster(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_float_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_float_shared_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_float_shared_cluster_param_1];
; CHECK-NEXT:    st.release.cluster.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(3) %addr syncscope("cluster") release, align 4
    ret void
}

define void @release_float_shared_gpu(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_float_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_float_shared_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_float_shared_gpu_param_1];
; CHECK-NEXT:    st.release.gpu.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(3) %addr syncscope("device") release, align 4
    ret void
}

define void @release_float_shared_sys_volatile(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_float_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_float_shared_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_float_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(3) %addr syncscope("") release, align 4
    ret void
}

define void @release_float_shared_cta_volatile(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_float_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_float_shared_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_float_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(3) %addr syncscope("block") release, align 4
    ret void
}

define void @release_float_shared_cluster_volatile(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_float_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_float_shared_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_float_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(3) %addr syncscope("cluster") release, align 4
    ret void
}

define void @release_float_shared_gpu_volatile(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_float_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [release_float_shared_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd1, [release_float_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(3) %addr syncscope("device") release, align 4
    ret void
}

define void @release_double_shared_sys(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_double_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_shared_sys_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_double_shared_sys_param_1];
; CHECK-NEXT:    st.release.sys.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(3) %addr syncscope("") release, align 8
    ret void
}

define void @release_double_shared_cta(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_double_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_shared_cta_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_double_shared_cta_param_1];
; CHECK-NEXT:    st.release.cta.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(3) %addr syncscope("block") release, align 8
    ret void
}

define void @release_double_shared_cluster(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_double_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_shared_cluster_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_double_shared_cluster_param_1];
; CHECK-NEXT:    st.release.cluster.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(3) %addr syncscope("cluster") release, align 8
    ret void
}

define void @release_double_shared_gpu(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_double_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_shared_gpu_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_double_shared_gpu_param_1];
; CHECK-NEXT:    st.release.gpu.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(3) %addr syncscope("device") release, align 8
    ret void
}

define void @release_double_shared_sys_volatile(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_double_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_shared_sys_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_double_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(3) %addr syncscope("") release, align 8
    ret void
}

define void @release_double_shared_cta_volatile(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_double_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_shared_cta_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_double_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(3) %addr syncscope("block") release, align 8
    ret void
}

define void @release_double_shared_cluster_volatile(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_double_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_shared_cluster_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_double_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(3) %addr syncscope("cluster") release, align 8
    ret void
}

define void @release_double_shared_gpu_volatile(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: release_double_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_shared_gpu_volatile_param_0];
; CHECK-NEXT:    ld.param.b64 %rd2, [release_double_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.release.sys.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(3) %addr syncscope("device") release, align 8
    ret void
}

define void @release_i8_local_sys(i8 %val) {
; CHECK-LABEL: release_i8_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot864[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot864;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i8 %val, ptr addrspace(5) %slot syncscope("") release, align 1
    ret void
}

define void @release_i8_local_cta(i8 %val) {
; CHECK-LABEL: release_i8_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot865[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot865;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i8 %val, ptr addrspace(5) %slot syncscope("block") release, align 1
    ret void
}

define void @release_i8_local_cluster(i8 %val) {
; CHECK-LABEL: release_i8_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot866[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot866;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i8 %val, ptr addrspace(5) %slot syncscope("cluster") release, align 1
    ret void
}

define void @release_i8_local_gpu(i8 %val) {
; CHECK-LABEL: release_i8_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot867[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot867;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i8 %val, ptr addrspace(5) %slot syncscope("device") release, align 1
    ret void
}

define void @release_i8_local_sys_volatile(i8 %val) {
; CHECK-LABEL: release_i8_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot868[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot868;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i8 %val, ptr addrspace(5) %slot syncscope("") release, align 1
    ret void
}

define void @release_i8_local_cta_volatile(i8 %val) {
; CHECK-LABEL: release_i8_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot869[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot869;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i8 %val, ptr addrspace(5) %slot syncscope("block") release, align 1
    ret void
}

define void @release_i8_local_cluster_volatile(i8 %val) {
; CHECK-LABEL: release_i8_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot870[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot870;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i8 %val, ptr addrspace(5) %slot syncscope("cluster") release, align 1
    ret void
}

define void @release_i8_local_gpu_volatile(i8 %val) {
; CHECK-LABEL: release_i8_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot871[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot871;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [release_i8_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i8 %val, ptr addrspace(5) %slot syncscope("device") release, align 1
    ret void
}

define void @release_i16_local_sys(i16 %val) {
; CHECK-LABEL: release_i16_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot872[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot872;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i16 %val, ptr addrspace(5) %slot syncscope("") release, align 2
    ret void
}

define void @release_i16_local_cta(i16 %val) {
; CHECK-LABEL: release_i16_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot873[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot873;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i16 %val, ptr addrspace(5) %slot syncscope("block") release, align 2
    ret void
}

define void @release_i16_local_cluster(i16 %val) {
; CHECK-LABEL: release_i16_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot874[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot874;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i16 %val, ptr addrspace(5) %slot syncscope("cluster") release, align 2
    ret void
}

define void @release_i16_local_gpu(i16 %val) {
; CHECK-LABEL: release_i16_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot875[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot875;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i16 %val, ptr addrspace(5) %slot syncscope("device") release, align 2
    ret void
}

define void @release_i16_local_sys_volatile(i16 %val) {
; CHECK-LABEL: release_i16_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot876[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot876;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i16 %val, ptr addrspace(5) %slot syncscope("") release, align 2
    ret void
}

define void @release_i16_local_cta_volatile(i16 %val) {
; CHECK-LABEL: release_i16_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot877[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot877;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i16 %val, ptr addrspace(5) %slot syncscope("block") release, align 2
    ret void
}

define void @release_i16_local_cluster_volatile(i16 %val) {
; CHECK-LABEL: release_i16_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot878[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot878;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i16 %val, ptr addrspace(5) %slot syncscope("cluster") release, align 2
    ret void
}

define void @release_i16_local_gpu_volatile(i16 %val) {
; CHECK-LABEL: release_i16_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot879[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot879;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [release_i16_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i16 %val, ptr addrspace(5) %slot syncscope("device") release, align 2
    ret void
}

define void @release_i32_local_sys(i32 %val) {
; CHECK-LABEL: release_i32_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot880[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot880;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [release_i32_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i32 %val, ptr addrspace(5) %slot syncscope("") release, align 4
    ret void
}

define void @release_i32_local_cta(i32 %val) {
; CHECK-LABEL: release_i32_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot881[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot881;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [release_i32_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i32 %val, ptr addrspace(5) %slot syncscope("block") release, align 4
    ret void
}

define void @release_i32_local_cluster(i32 %val) {
; CHECK-LABEL: release_i32_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot882[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot882;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [release_i32_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i32 %val, ptr addrspace(5) %slot syncscope("cluster") release, align 4
    ret void
}

define void @release_i32_local_gpu(i32 %val) {
; CHECK-LABEL: release_i32_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot883[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot883;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [release_i32_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i32 %val, ptr addrspace(5) %slot syncscope("device") release, align 4
    ret void
}

define void @release_i32_local_sys_volatile(i32 %val) {
; CHECK-LABEL: release_i32_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot884[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot884;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [release_i32_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i32 %val, ptr addrspace(5) %slot syncscope("") release, align 4
    ret void
}

define void @release_i32_local_cta_volatile(i32 %val) {
; CHECK-LABEL: release_i32_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot885[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot885;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [release_i32_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i32 %val, ptr addrspace(5) %slot syncscope("block") release, align 4
    ret void
}

define void @release_i32_local_cluster_volatile(i32 %val) {
; CHECK-LABEL: release_i32_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot886[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot886;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [release_i32_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i32 %val, ptr addrspace(5) %slot syncscope("cluster") release, align 4
    ret void
}

define void @release_i32_local_gpu_volatile(i32 %val) {
; CHECK-LABEL: release_i32_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot887[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot887;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [release_i32_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i32 %val, ptr addrspace(5) %slot syncscope("device") release, align 4
    ret void
}

define void @release_i64_local_sys(i64 %val) {
; CHECK-LABEL: release_i64_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot888[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot888;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i64 %val, ptr addrspace(5) %slot syncscope("") release, align 8
    ret void
}

define void @release_i64_local_cta(i64 %val) {
; CHECK-LABEL: release_i64_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot889[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot889;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i64 %val, ptr addrspace(5) %slot syncscope("block") release, align 8
    ret void
}

define void @release_i64_local_cluster(i64 %val) {
; CHECK-LABEL: release_i64_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot890[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot890;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i64 %val, ptr addrspace(5) %slot syncscope("cluster") release, align 8
    ret void
}

define void @release_i64_local_gpu(i64 %val) {
; CHECK-LABEL: release_i64_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot891[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot891;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i64 %val, ptr addrspace(5) %slot syncscope("device") release, align 8
    ret void
}

define void @release_i64_local_sys_volatile(i64 %val) {
; CHECK-LABEL: release_i64_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot892[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot892;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i64 %val, ptr addrspace(5) %slot syncscope("") release, align 8
    ret void
}

define void @release_i64_local_cta_volatile(i64 %val) {
; CHECK-LABEL: release_i64_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot893[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot893;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i64 %val, ptr addrspace(5) %slot syncscope("block") release, align 8
    ret void
}

define void @release_i64_local_cluster_volatile(i64 %val) {
; CHECK-LABEL: release_i64_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot894[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot894;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i64 %val, ptr addrspace(5) %slot syncscope("cluster") release, align 8
    ret void
}

define void @release_i64_local_gpu_volatile(i64 %val) {
; CHECK-LABEL: release_i64_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot895[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot895;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [release_i64_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i64 %val, ptr addrspace(5) %slot syncscope("device") release, align 8
    ret void
}

define void @release_i128_local_sys(i128 %val) {
; CHECK-LABEL: release_i128_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot896[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot896;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i128 %val, ptr addrspace(5) %slot syncscope("") release, align 16
    ret void
}

define void @release_i128_local_cta(i128 %val) {
; CHECK-LABEL: release_i128_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot897[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot897;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i128 %val, ptr addrspace(5) %slot syncscope("block") release, align 16
    ret void
}

define void @release_i128_local_cluster(i128 %val) {
; CHECK-LABEL: release_i128_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot898[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot898;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i128 %val, ptr addrspace(5) %slot syncscope("cluster") release, align 16
    ret void
}

define void @release_i128_local_gpu(i128 %val) {
; CHECK-LABEL: release_i128_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot899[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot899;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i128 %val, ptr addrspace(5) %slot syncscope("device") release, align 16
    ret void
}

define void @release_i128_local_sys_volatile(i128 %val) {
; CHECK-LABEL: release_i128_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot900[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot900;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i128 %val, ptr addrspace(5) %slot syncscope("") release, align 16
    ret void
}

define void @release_i128_local_cta_volatile(i128 %val) {
; CHECK-LABEL: release_i128_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot901[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot901;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i128 %val, ptr addrspace(5) %slot syncscope("block") release, align 16
    ret void
}

define void @release_i128_local_cluster_volatile(i128 %val) {
; CHECK-LABEL: release_i128_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot902[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot902;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i128 %val, ptr addrspace(5) %slot syncscope("cluster") release, align 16
    ret void
}

define void @release_i128_local_gpu_volatile(i128 %val) {
; CHECK-LABEL: release_i128_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot903[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot903;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [release_i128_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i128 %val, ptr addrspace(5) %slot syncscope("device") release, align 16
    ret void
}

define void @release_half_local_sys(half %val) {
; CHECK-LABEL: release_half_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot904[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot904;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic half %val, ptr addrspace(5) %slot syncscope("") release, align 2
    ret void
}

define void @release_half_local_cta(half %val) {
; CHECK-LABEL: release_half_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot905[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot905;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic half %val, ptr addrspace(5) %slot syncscope("block") release, align 2
    ret void
}

define void @release_half_local_cluster(half %val) {
; CHECK-LABEL: release_half_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot906[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot906;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic half %val, ptr addrspace(5) %slot syncscope("cluster") release, align 2
    ret void
}

define void @release_half_local_gpu(half %val) {
; CHECK-LABEL: release_half_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot907[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot907;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic half %val, ptr addrspace(5) %slot syncscope("device") release, align 2
    ret void
}

define void @release_half_local_sys_volatile(half %val) {
; CHECK-LABEL: release_half_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot908[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot908;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile half %val, ptr addrspace(5) %slot syncscope("") release, align 2
    ret void
}

define void @release_half_local_cta_volatile(half %val) {
; CHECK-LABEL: release_half_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot909[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot909;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile half %val, ptr addrspace(5) %slot syncscope("block") release, align 2
    ret void
}

define void @release_half_local_cluster_volatile(half %val) {
; CHECK-LABEL: release_half_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot910[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot910;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile half %val, ptr addrspace(5) %slot syncscope("cluster") release, align 2
    ret void
}

define void @release_half_local_gpu_volatile(half %val) {
; CHECK-LABEL: release_half_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot911[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot911;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [release_half_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile half %val, ptr addrspace(5) %slot syncscope("device") release, align 2
    ret void
}

define void @release_bfloat_local_sys(bfloat %val) {
; CHECK-LABEL: release_bfloat_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot912[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot912;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic bfloat %val, ptr addrspace(5) %slot syncscope("") release, align 2
    ret void
}

define void @release_bfloat_local_cta(bfloat %val) {
; CHECK-LABEL: release_bfloat_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot913[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot913;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic bfloat %val, ptr addrspace(5) %slot syncscope("block") release, align 2
    ret void
}

define void @release_bfloat_local_cluster(bfloat %val) {
; CHECK-LABEL: release_bfloat_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot914[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot914;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic bfloat %val, ptr addrspace(5) %slot syncscope("cluster") release, align 2
    ret void
}

define void @release_bfloat_local_gpu(bfloat %val) {
; CHECK-LABEL: release_bfloat_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot915[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot915;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic bfloat %val, ptr addrspace(5) %slot syncscope("device") release, align 2
    ret void
}

define void @release_bfloat_local_sys_volatile(bfloat %val) {
; CHECK-LABEL: release_bfloat_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot916[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot916;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile bfloat %val, ptr addrspace(5) %slot syncscope("") release, align 2
    ret void
}

define void @release_bfloat_local_cta_volatile(bfloat %val) {
; CHECK-LABEL: release_bfloat_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot917[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot917;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile bfloat %val, ptr addrspace(5) %slot syncscope("block") release, align 2
    ret void
}

define void @release_bfloat_local_cluster_volatile(bfloat %val) {
; CHECK-LABEL: release_bfloat_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot918[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot918;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile bfloat %val, ptr addrspace(5) %slot syncscope("cluster") release, align 2
    ret void
}

define void @release_bfloat_local_gpu_volatile(bfloat %val) {
; CHECK-LABEL: release_bfloat_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot919[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot919;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [release_bfloat_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile bfloat %val, ptr addrspace(5) %slot syncscope("device") release, align 2
    ret void
}

define void @release_float_local_sys(float %val) {
; CHECK-LABEL: release_float_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot920[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot920;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [release_float_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic float %val, ptr addrspace(5) %slot syncscope("") release, align 4
    ret void
}

define void @release_float_local_cta(float %val) {
; CHECK-LABEL: release_float_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot921[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot921;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [release_float_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic float %val, ptr addrspace(5) %slot syncscope("block") release, align 4
    ret void
}

define void @release_float_local_cluster(float %val) {
; CHECK-LABEL: release_float_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot922[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot922;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [release_float_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic float %val, ptr addrspace(5) %slot syncscope("cluster") release, align 4
    ret void
}

define void @release_float_local_gpu(float %val) {
; CHECK-LABEL: release_float_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot923[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot923;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [release_float_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic float %val, ptr addrspace(5) %slot syncscope("device") release, align 4
    ret void
}

define void @release_float_local_sys_volatile(float %val) {
; CHECK-LABEL: release_float_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot924[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot924;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [release_float_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile float %val, ptr addrspace(5) %slot syncscope("") release, align 4
    ret void
}

define void @release_float_local_cta_volatile(float %val) {
; CHECK-LABEL: release_float_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot925[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot925;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [release_float_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile float %val, ptr addrspace(5) %slot syncscope("block") release, align 4
    ret void
}

define void @release_float_local_cluster_volatile(float %val) {
; CHECK-LABEL: release_float_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot926[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot926;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [release_float_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile float %val, ptr addrspace(5) %slot syncscope("cluster") release, align 4
    ret void
}

define void @release_float_local_gpu_volatile(float %val) {
; CHECK-LABEL: release_float_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot927[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot927;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [release_float_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile float %val, ptr addrspace(5) %slot syncscope("device") release, align 4
    ret void
}

define void @release_double_local_sys(double %val) {
; CHECK-LABEL: release_double_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot928[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot928;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic double %val, ptr addrspace(5) %slot syncscope("") release, align 8
    ret void
}

define void @release_double_local_cta(double %val) {
; CHECK-LABEL: release_double_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot929[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot929;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic double %val, ptr addrspace(5) %slot syncscope("block") release, align 8
    ret void
}

define void @release_double_local_cluster(double %val) {
; CHECK-LABEL: release_double_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot930[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot930;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic double %val, ptr addrspace(5) %slot syncscope("cluster") release, align 8
    ret void
}

define void @release_double_local_gpu(double %val) {
; CHECK-LABEL: release_double_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot931[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot931;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic double %val, ptr addrspace(5) %slot syncscope("device") release, align 8
    ret void
}

define void @release_double_local_sys_volatile(double %val) {
; CHECK-LABEL: release_double_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot932[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot932;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile double %val, ptr addrspace(5) %slot syncscope("") release, align 8
    ret void
}

define void @release_double_local_cta_volatile(double %val) {
; CHECK-LABEL: release_double_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot933[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot933;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile double %val, ptr addrspace(5) %slot syncscope("block") release, align 8
    ret void
}

define void @release_double_local_cluster_volatile(double %val) {
; CHECK-LABEL: release_double_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot934[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot934;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile double %val, ptr addrspace(5) %slot syncscope("cluster") release, align 8
    ret void
}

define void @release_double_local_gpu_volatile(double %val) {
; CHECK-LABEL: release_double_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot935[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot935;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [release_double_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile double %val, ptr addrspace(5) %slot syncscope("device") release, align 8
    ret void
}

define void @seq_cst_i8_generic_sys(i8 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i8_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_generic_sys_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i8_generic_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr %addr syncscope("") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_generic_cta(i8 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i8_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_generic_cta_param_0];
; CHECK-NEXT:    fence.sc.cta;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i8_generic_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr %addr syncscope("block") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_generic_cluster(i8 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i8_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_generic_cluster_param_0];
; CHECK-NEXT:    fence.sc.cluster;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i8_generic_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr %addr syncscope("cluster") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_generic_gpu(i8 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i8_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_generic_gpu_param_0];
; CHECK-NEXT:    fence.sc.gpu;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i8_generic_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr %addr syncscope("device") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_generic_sys_volatile(i8 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i8_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_generic_sys_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i8_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr %addr syncscope("") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_generic_cta_volatile(i8 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i8_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_generic_cta_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i8_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr %addr syncscope("block") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_generic_cluster_volatile(i8 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i8_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_generic_cluster_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i8_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr %addr syncscope("cluster") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_generic_gpu_volatile(i8 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i8_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_generic_gpu_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i8_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr %addr syncscope("device") seq_cst, align 1
    ret void
}

define void @seq_cst_i16_generic_sys(i16 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i16_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_generic_sys_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i16_generic_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr %addr syncscope("") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_generic_cta(i16 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i16_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_generic_cta_param_0];
; CHECK-NEXT:    fence.sc.cta;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i16_generic_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr %addr syncscope("block") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_generic_cluster(i16 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i16_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_generic_cluster_param_0];
; CHECK-NEXT:    fence.sc.cluster;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i16_generic_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr %addr syncscope("cluster") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_generic_gpu(i16 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i16_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_generic_gpu_param_0];
; CHECK-NEXT:    fence.sc.gpu;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i16_generic_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr %addr syncscope("device") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_generic_sys_volatile(i16 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i16_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_generic_sys_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i16_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr %addr syncscope("") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_generic_cta_volatile(i16 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i16_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_generic_cta_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i16_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr %addr syncscope("block") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_generic_cluster_volatile(i16 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i16_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_generic_cluster_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i16_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr %addr syncscope("cluster") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_generic_gpu_volatile(i16 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i16_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_generic_gpu_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i16_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr %addr syncscope("device") seq_cst, align 2
    ret void
}

define void @seq_cst_i32_generic_sys(i32 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i32_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_i32_generic_sys_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i32_generic_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr %addr syncscope("") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_generic_cta(i32 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i32_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_i32_generic_cta_param_0];
; CHECK-NEXT:    fence.sc.cta;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i32_generic_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr %addr syncscope("block") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_generic_cluster(i32 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i32_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_i32_generic_cluster_param_0];
; CHECK-NEXT:    fence.sc.cluster;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i32_generic_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr %addr syncscope("cluster") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_generic_gpu(i32 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i32_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_i32_generic_gpu_param_0];
; CHECK-NEXT:    fence.sc.gpu;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i32_generic_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr %addr syncscope("device") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_generic_sys_volatile(i32 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i32_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_i32_generic_sys_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i32_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr %addr syncscope("") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_generic_cta_volatile(i32 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i32_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_i32_generic_cta_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i32_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr %addr syncscope("block") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_generic_cluster_volatile(i32 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i32_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_i32_generic_cluster_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i32_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr %addr syncscope("cluster") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_generic_gpu_volatile(i32 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i32_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_i32_generic_gpu_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i32_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr %addr syncscope("device") seq_cst, align 4
    ret void
}

define void @seq_cst_i64_generic_sys(i64 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i64_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_generic_sys_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_i64_generic_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr %addr syncscope("") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_generic_cta(i64 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i64_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_generic_cta_param_0];
; CHECK-NEXT:    fence.sc.cta;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_i64_generic_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr %addr syncscope("block") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_generic_cluster(i64 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i64_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_generic_cluster_param_0];
; CHECK-NEXT:    fence.sc.cluster;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_i64_generic_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr %addr syncscope("cluster") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_generic_gpu(i64 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i64_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_generic_gpu_param_0];
; CHECK-NEXT:    fence.sc.gpu;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_i64_generic_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr %addr syncscope("device") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_generic_sys_volatile(i64 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i64_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_generic_sys_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_i64_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr %addr syncscope("") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_generic_cta_volatile(i64 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i64_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_generic_cta_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_i64_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr %addr syncscope("block") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_generic_cluster_volatile(i64 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i64_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_generic_cluster_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_i64_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr %addr syncscope("cluster") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_generic_gpu_volatile(i64 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i64_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_generic_gpu_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_i64_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr %addr syncscope("device") seq_cst, align 8
    ret void
}

define void @seq_cst_i128_generic_sys(i128 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i128_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_generic_sys_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd3, [seq_cst_i128_generic_sys_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.sys.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr %addr syncscope("") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_generic_cta(i128 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i128_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_generic_cta_param_0];
; CHECK-NEXT:    fence.sc.cta;
; CHECK-NEXT:    ld.param.b64 %rd3, [seq_cst_i128_generic_cta_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cta.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr %addr syncscope("block") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_generic_cluster(i128 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i128_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_generic_cluster_param_0];
; CHECK-NEXT:    fence.sc.cluster;
; CHECK-NEXT:    ld.param.b64 %rd3, [seq_cst_i128_generic_cluster_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cluster.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr %addr syncscope("cluster") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_generic_gpu(i128 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i128_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_generic_gpu_param_0];
; CHECK-NEXT:    fence.sc.gpu;
; CHECK-NEXT:    ld.param.b64 %rd3, [seq_cst_i128_generic_gpu_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.gpu.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr %addr syncscope("device") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_generic_sys_volatile(i128 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i128_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_generic_sys_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd3, [seq_cst_i128_generic_sys_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.sys.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr %addr syncscope("") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_generic_cta_volatile(i128 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i128_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_generic_cta_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd3, [seq_cst_i128_generic_cta_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cta.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr %addr syncscope("block") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_generic_cluster_volatile(i128 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i128_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_generic_cluster_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd3, [seq_cst_i128_generic_cluster_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cluster.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr %addr syncscope("cluster") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_generic_gpu_volatile(i128 %val, ptr %addr) {
; CHECK-LABEL: seq_cst_i128_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_generic_gpu_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd3, [seq_cst_i128_generic_gpu_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.gpu.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr %addr syncscope("device") seq_cst, align 16
    ret void
}

define void @seq_cst_half_generic_sys(half %val, ptr %addr) {
; CHECK-LABEL: seq_cst_half_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_generic_sys_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_half_generic_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr %addr syncscope("") seq_cst, align 2
    ret void
}

define void @seq_cst_half_generic_cta(half %val, ptr %addr) {
; CHECK-LABEL: seq_cst_half_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_generic_cta_param_0];
; CHECK-NEXT:    fence.sc.cta;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_half_generic_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr %addr syncscope("block") seq_cst, align 2
    ret void
}

define void @seq_cst_half_generic_cluster(half %val, ptr %addr) {
; CHECK-LABEL: seq_cst_half_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_generic_cluster_param_0];
; CHECK-NEXT:    fence.sc.cluster;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_half_generic_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr %addr syncscope("cluster") seq_cst, align 2
    ret void
}

define void @seq_cst_half_generic_gpu(half %val, ptr %addr) {
; CHECK-LABEL: seq_cst_half_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_generic_gpu_param_0];
; CHECK-NEXT:    fence.sc.gpu;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_half_generic_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr %addr syncscope("device") seq_cst, align 2
    ret void
}

define void @seq_cst_half_generic_sys_volatile(half %val, ptr %addr) {
; CHECK-LABEL: seq_cst_half_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_generic_sys_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_half_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr %addr syncscope("") seq_cst, align 2
    ret void
}

define void @seq_cst_half_generic_cta_volatile(half %val, ptr %addr) {
; CHECK-LABEL: seq_cst_half_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_generic_cta_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_half_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr %addr syncscope("block") seq_cst, align 2
    ret void
}

define void @seq_cst_half_generic_cluster_volatile(half %val, ptr %addr) {
; CHECK-LABEL: seq_cst_half_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_generic_cluster_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_half_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr %addr syncscope("cluster") seq_cst, align 2
    ret void
}

define void @seq_cst_half_generic_gpu_volatile(half %val, ptr %addr) {
; CHECK-LABEL: seq_cst_half_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_generic_gpu_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_half_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr %addr syncscope("device") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_generic_sys(bfloat %val, ptr %addr) {
; CHECK-LABEL: seq_cst_bfloat_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_generic_sys_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_bfloat_generic_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr %addr syncscope("") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_generic_cta(bfloat %val, ptr %addr) {
; CHECK-LABEL: seq_cst_bfloat_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_generic_cta_param_0];
; CHECK-NEXT:    fence.sc.cta;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_bfloat_generic_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr %addr syncscope("block") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_generic_cluster(bfloat %val, ptr %addr) {
; CHECK-LABEL: seq_cst_bfloat_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_generic_cluster_param_0];
; CHECK-NEXT:    fence.sc.cluster;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_bfloat_generic_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr %addr syncscope("cluster") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_generic_gpu(bfloat %val, ptr %addr) {
; CHECK-LABEL: seq_cst_bfloat_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_generic_gpu_param_0];
; CHECK-NEXT:    fence.sc.gpu;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_bfloat_generic_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr %addr syncscope("device") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_generic_sys_volatile(bfloat %val, ptr %addr) {
; CHECK-LABEL: seq_cst_bfloat_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_generic_sys_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_bfloat_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr %addr syncscope("") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_generic_cta_volatile(bfloat %val, ptr %addr) {
; CHECK-LABEL: seq_cst_bfloat_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_generic_cta_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_bfloat_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr %addr syncscope("block") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_generic_cluster_volatile(bfloat %val, ptr %addr) {
; CHECK-LABEL: seq_cst_bfloat_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_generic_cluster_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_bfloat_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr %addr syncscope("cluster") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_generic_gpu_volatile(bfloat %val, ptr %addr) {
; CHECK-LABEL: seq_cst_bfloat_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_generic_gpu_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_bfloat_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr %addr syncscope("device") seq_cst, align 2
    ret void
}

define void @seq_cst_float_generic_sys(float %val, ptr %addr) {
; CHECK-LABEL: seq_cst_float_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_float_generic_sys_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_float_generic_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr %addr syncscope("") seq_cst, align 4
    ret void
}

define void @seq_cst_float_generic_cta(float %val, ptr %addr) {
; CHECK-LABEL: seq_cst_float_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_float_generic_cta_param_0];
; CHECK-NEXT:    fence.sc.cta;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_float_generic_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr %addr syncscope("block") seq_cst, align 4
    ret void
}

define void @seq_cst_float_generic_cluster(float %val, ptr %addr) {
; CHECK-LABEL: seq_cst_float_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_float_generic_cluster_param_0];
; CHECK-NEXT:    fence.sc.cluster;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_float_generic_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr %addr syncscope("cluster") seq_cst, align 4
    ret void
}

define void @seq_cst_float_generic_gpu(float %val, ptr %addr) {
; CHECK-LABEL: seq_cst_float_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_float_generic_gpu_param_0];
; CHECK-NEXT:    fence.sc.gpu;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_float_generic_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr %addr syncscope("device") seq_cst, align 4
    ret void
}

define void @seq_cst_float_generic_sys_volatile(float %val, ptr %addr) {
; CHECK-LABEL: seq_cst_float_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_float_generic_sys_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_float_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr %addr syncscope("") seq_cst, align 4
    ret void
}

define void @seq_cst_float_generic_cta_volatile(float %val, ptr %addr) {
; CHECK-LABEL: seq_cst_float_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_float_generic_cta_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_float_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr %addr syncscope("block") seq_cst, align 4
    ret void
}

define void @seq_cst_float_generic_cluster_volatile(float %val, ptr %addr) {
; CHECK-LABEL: seq_cst_float_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_float_generic_cluster_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_float_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr %addr syncscope("cluster") seq_cst, align 4
    ret void
}

define void @seq_cst_float_generic_gpu_volatile(float %val, ptr %addr) {
; CHECK-LABEL: seq_cst_float_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_float_generic_gpu_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_float_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr %addr syncscope("device") seq_cst, align 4
    ret void
}

define void @seq_cst_double_generic_sys(double %val, ptr %addr) {
; CHECK-LABEL: seq_cst_double_generic_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_generic_sys_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_double_generic_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr %addr syncscope("") seq_cst, align 8
    ret void
}

define void @seq_cst_double_generic_cta(double %val, ptr %addr) {
; CHECK-LABEL: seq_cst_double_generic_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_generic_cta_param_0];
; CHECK-NEXT:    fence.sc.cta;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_double_generic_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr %addr syncscope("block") seq_cst, align 8
    ret void
}

define void @seq_cst_double_generic_cluster(double %val, ptr %addr) {
; CHECK-LABEL: seq_cst_double_generic_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_generic_cluster_param_0];
; CHECK-NEXT:    fence.sc.cluster;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_double_generic_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr %addr syncscope("cluster") seq_cst, align 8
    ret void
}

define void @seq_cst_double_generic_gpu(double %val, ptr %addr) {
; CHECK-LABEL: seq_cst_double_generic_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_generic_gpu_param_0];
; CHECK-NEXT:    fence.sc.gpu;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_double_generic_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr %addr syncscope("device") seq_cst, align 8
    ret void
}

define void @seq_cst_double_generic_sys_volatile(double %val, ptr %addr) {
; CHECK-LABEL: seq_cst_double_generic_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_generic_sys_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_double_generic_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr %addr syncscope("") seq_cst, align 8
    ret void
}

define void @seq_cst_double_generic_cta_volatile(double %val, ptr %addr) {
; CHECK-LABEL: seq_cst_double_generic_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_generic_cta_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_double_generic_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr %addr syncscope("block") seq_cst, align 8
    ret void
}

define void @seq_cst_double_generic_cluster_volatile(double %val, ptr %addr) {
; CHECK-LABEL: seq_cst_double_generic_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_generic_cluster_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_double_generic_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr %addr syncscope("cluster") seq_cst, align 8
    ret void
}

define void @seq_cst_double_generic_gpu_volatile(double %val, ptr %addr) {
; CHECK-LABEL: seq_cst_double_generic_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_generic_gpu_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_double_generic_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr %addr syncscope("device") seq_cst, align 8
    ret void
}

define void @seq_cst_i8_global_sys(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i8_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_global_sys_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i8_global_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(1) %addr syncscope("") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_global_cta(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i8_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_global_cta_param_0];
; CHECK-NEXT:    fence.sc.cta;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i8_global_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(1) %addr syncscope("block") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_global_cluster(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i8_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_global_cluster_param_0];
; CHECK-NEXT:    fence.sc.cluster;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i8_global_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(1) %addr syncscope("cluster") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_global_gpu(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i8_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_global_gpu_param_0];
; CHECK-NEXT:    fence.sc.gpu;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i8_global_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(1) %addr syncscope("device") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_global_sys_volatile(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i8_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_global_sys_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i8_global_sys_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(1) %addr syncscope("") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_global_cta_volatile(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i8_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_global_cta_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i8_global_cta_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(1) %addr syncscope("block") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_global_cluster_volatile(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i8_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_global_cluster_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i8_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(1) %addr syncscope("cluster") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_global_gpu_volatile(i8 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i8_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_global_gpu_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i8_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(1) %addr syncscope("device") seq_cst, align 1
    ret void
}

define void @seq_cst_i16_global_sys(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i16_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_global_sys_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i16_global_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(1) %addr syncscope("") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_global_cta(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i16_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_global_cta_param_0];
; CHECK-NEXT:    fence.sc.cta;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i16_global_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(1) %addr syncscope("block") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_global_cluster(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i16_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_global_cluster_param_0];
; CHECK-NEXT:    fence.sc.cluster;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i16_global_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(1) %addr syncscope("cluster") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_global_gpu(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i16_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_global_gpu_param_0];
; CHECK-NEXT:    fence.sc.gpu;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i16_global_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(1) %addr syncscope("device") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_global_sys_volatile(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i16_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_global_sys_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i16_global_sys_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(1) %addr syncscope("") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_global_cta_volatile(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i16_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_global_cta_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i16_global_cta_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(1) %addr syncscope("block") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_global_cluster_volatile(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i16_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_global_cluster_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i16_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(1) %addr syncscope("cluster") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_global_gpu_volatile(i16 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i16_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_global_gpu_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i16_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(1) %addr syncscope("device") seq_cst, align 2
    ret void
}

define void @seq_cst_i32_global_sys(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i32_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_i32_global_sys_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i32_global_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(1) %addr syncscope("") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_global_cta(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i32_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_i32_global_cta_param_0];
; CHECK-NEXT:    fence.sc.cta;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i32_global_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(1) %addr syncscope("block") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_global_cluster(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i32_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_i32_global_cluster_param_0];
; CHECK-NEXT:    fence.sc.cluster;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i32_global_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(1) %addr syncscope("cluster") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_global_gpu(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i32_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_i32_global_gpu_param_0];
; CHECK-NEXT:    fence.sc.gpu;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i32_global_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(1) %addr syncscope("device") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_global_sys_volatile(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i32_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_i32_global_sys_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i32_global_sys_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(1) %addr syncscope("") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_global_cta_volatile(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i32_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_i32_global_cta_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i32_global_cta_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(1) %addr syncscope("block") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_global_cluster_volatile(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i32_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_i32_global_cluster_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i32_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(1) %addr syncscope("cluster") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_global_gpu_volatile(i32 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i32_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_i32_global_gpu_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i32_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(1) %addr syncscope("device") seq_cst, align 4
    ret void
}

define void @seq_cst_i64_global_sys(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i64_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_global_sys_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_i64_global_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(1) %addr syncscope("") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_global_cta(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i64_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_global_cta_param_0];
; CHECK-NEXT:    fence.sc.cta;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_i64_global_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(1) %addr syncscope("block") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_global_cluster(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i64_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_global_cluster_param_0];
; CHECK-NEXT:    fence.sc.cluster;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_i64_global_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(1) %addr syncscope("cluster") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_global_gpu(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i64_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_global_gpu_param_0];
; CHECK-NEXT:    fence.sc.gpu;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_i64_global_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(1) %addr syncscope("device") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_global_sys_volatile(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i64_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_global_sys_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_i64_global_sys_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(1) %addr syncscope("") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_global_cta_volatile(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i64_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_global_cta_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_i64_global_cta_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(1) %addr syncscope("block") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_global_cluster_volatile(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i64_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_global_cluster_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_i64_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(1) %addr syncscope("cluster") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_global_gpu_volatile(i64 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i64_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_global_gpu_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_i64_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(1) %addr syncscope("device") seq_cst, align 8
    ret void
}

define void @seq_cst_i128_global_sys(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i128_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_global_sys_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd3, [seq_cst_i128_global_sys_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.sys.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(1) %addr syncscope("") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_global_cta(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i128_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_global_cta_param_0];
; CHECK-NEXT:    fence.sc.cta;
; CHECK-NEXT:    ld.param.b64 %rd3, [seq_cst_i128_global_cta_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cta.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(1) %addr syncscope("block") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_global_cluster(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i128_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_global_cluster_param_0];
; CHECK-NEXT:    fence.sc.cluster;
; CHECK-NEXT:    ld.param.b64 %rd3, [seq_cst_i128_global_cluster_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cluster.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(1) %addr syncscope("cluster") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_global_gpu(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i128_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_global_gpu_param_0];
; CHECK-NEXT:    fence.sc.gpu;
; CHECK-NEXT:    ld.param.b64 %rd3, [seq_cst_i128_global_gpu_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.gpu.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(1) %addr syncscope("device") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_global_sys_volatile(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i128_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_global_sys_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd3, [seq_cst_i128_global_sys_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.sys.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(1) %addr syncscope("") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_global_cta_volatile(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i128_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_global_cta_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd3, [seq_cst_i128_global_cta_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cta.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(1) %addr syncscope("block") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_global_cluster_volatile(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i128_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_global_cluster_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd3, [seq_cst_i128_global_cluster_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cluster.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(1) %addr syncscope("cluster") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_global_gpu_volatile(i128 %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_i128_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_global_gpu_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd3, [seq_cst_i128_global_gpu_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.gpu.global.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(1) %addr syncscope("device") seq_cst, align 16
    ret void
}

define void @seq_cst_half_global_sys(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_half_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_global_sys_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_half_global_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(1) %addr syncscope("") seq_cst, align 2
    ret void
}

define void @seq_cst_half_global_cta(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_half_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_global_cta_param_0];
; CHECK-NEXT:    fence.sc.cta;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_half_global_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(1) %addr syncscope("block") seq_cst, align 2
    ret void
}

define void @seq_cst_half_global_cluster(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_half_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_global_cluster_param_0];
; CHECK-NEXT:    fence.sc.cluster;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_half_global_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(1) %addr syncscope("cluster") seq_cst, align 2
    ret void
}

define void @seq_cst_half_global_gpu(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_half_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_global_gpu_param_0];
; CHECK-NEXT:    fence.sc.gpu;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_half_global_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(1) %addr syncscope("device") seq_cst, align 2
    ret void
}

define void @seq_cst_half_global_sys_volatile(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_half_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_global_sys_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_half_global_sys_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(1) %addr syncscope("") seq_cst, align 2
    ret void
}

define void @seq_cst_half_global_cta_volatile(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_half_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_global_cta_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_half_global_cta_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(1) %addr syncscope("block") seq_cst, align 2
    ret void
}

define void @seq_cst_half_global_cluster_volatile(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_half_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_global_cluster_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_half_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(1) %addr syncscope("cluster") seq_cst, align 2
    ret void
}

define void @seq_cst_half_global_gpu_volatile(half %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_half_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_global_gpu_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_half_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(1) %addr syncscope("device") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_global_sys(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_bfloat_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_global_sys_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_bfloat_global_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(1) %addr syncscope("") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_global_cta(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_bfloat_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_global_cta_param_0];
; CHECK-NEXT:    fence.sc.cta;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_bfloat_global_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(1) %addr syncscope("block") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_global_cluster(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_bfloat_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_global_cluster_param_0];
; CHECK-NEXT:    fence.sc.cluster;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_bfloat_global_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(1) %addr syncscope("cluster") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_global_gpu(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_bfloat_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_global_gpu_param_0];
; CHECK-NEXT:    fence.sc.gpu;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_bfloat_global_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(1) %addr syncscope("device") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_global_sys_volatile(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_bfloat_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_global_sys_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_bfloat_global_sys_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(1) %addr syncscope("") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_global_cta_volatile(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_bfloat_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_global_cta_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_bfloat_global_cta_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(1) %addr syncscope("block") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_global_cluster_volatile(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_bfloat_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_global_cluster_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_bfloat_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(1) %addr syncscope("cluster") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_global_gpu_volatile(bfloat %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_bfloat_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_global_gpu_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_bfloat_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(1) %addr syncscope("device") seq_cst, align 2
    ret void
}

define void @seq_cst_float_global_sys(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_float_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_float_global_sys_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_float_global_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(1) %addr syncscope("") seq_cst, align 4
    ret void
}

define void @seq_cst_float_global_cta(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_float_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_float_global_cta_param_0];
; CHECK-NEXT:    fence.sc.cta;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_float_global_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(1) %addr syncscope("block") seq_cst, align 4
    ret void
}

define void @seq_cst_float_global_cluster(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_float_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_float_global_cluster_param_0];
; CHECK-NEXT:    fence.sc.cluster;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_float_global_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(1) %addr syncscope("cluster") seq_cst, align 4
    ret void
}

define void @seq_cst_float_global_gpu(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_float_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_float_global_gpu_param_0];
; CHECK-NEXT:    fence.sc.gpu;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_float_global_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(1) %addr syncscope("device") seq_cst, align 4
    ret void
}

define void @seq_cst_float_global_sys_volatile(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_float_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_float_global_sys_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_float_global_sys_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(1) %addr syncscope("") seq_cst, align 4
    ret void
}

define void @seq_cst_float_global_cta_volatile(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_float_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_float_global_cta_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_float_global_cta_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(1) %addr syncscope("block") seq_cst, align 4
    ret void
}

define void @seq_cst_float_global_cluster_volatile(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_float_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_float_global_cluster_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_float_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(1) %addr syncscope("cluster") seq_cst, align 4
    ret void
}

define void @seq_cst_float_global_gpu_volatile(float %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_float_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_float_global_gpu_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_float_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(1) %addr syncscope("device") seq_cst, align 4
    ret void
}

define void @seq_cst_double_global_sys(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_double_global_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_global_sys_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_double_global_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(1) %addr syncscope("") seq_cst, align 8
    ret void
}

define void @seq_cst_double_global_cta(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_double_global_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_global_cta_param_0];
; CHECK-NEXT:    fence.sc.cta;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_double_global_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(1) %addr syncscope("block") seq_cst, align 8
    ret void
}

define void @seq_cst_double_global_cluster(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_double_global_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_global_cluster_param_0];
; CHECK-NEXT:    fence.sc.cluster;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_double_global_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(1) %addr syncscope("cluster") seq_cst, align 8
    ret void
}

define void @seq_cst_double_global_gpu(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_double_global_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_global_gpu_param_0];
; CHECK-NEXT:    fence.sc.gpu;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_double_global_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(1) %addr syncscope("device") seq_cst, align 8
    ret void
}

define void @seq_cst_double_global_sys_volatile(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_double_global_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_global_sys_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_double_global_sys_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(1) %addr syncscope("") seq_cst, align 8
    ret void
}

define void @seq_cst_double_global_cta_volatile(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_double_global_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_global_cta_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_double_global_cta_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(1) %addr syncscope("block") seq_cst, align 8
    ret void
}

define void @seq_cst_double_global_cluster_volatile(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_double_global_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_global_cluster_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_double_global_cluster_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(1) %addr syncscope("cluster") seq_cst, align 8
    ret void
}

define void @seq_cst_double_global_gpu_volatile(double %val, ptr addrspace(1) %addr) {
; CHECK-LABEL: seq_cst_double_global_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_global_gpu_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_double_global_gpu_volatile_param_1];
; CHECK-NEXT:    st.mmio.relaxed.sys.global.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(1) %addr syncscope("device") seq_cst, align 8
    ret void
}

define void @seq_cst_i8_shared_sys(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i8_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_shared_sys_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i8_shared_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(3) %addr syncscope("") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_shared_cta(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i8_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_shared_cta_param_0];
; CHECK-NEXT:    fence.sc.cta;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i8_shared_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(3) %addr syncscope("block") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_shared_cluster(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i8_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_shared_cluster_param_0];
; CHECK-NEXT:    fence.sc.cluster;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i8_shared_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(3) %addr syncscope("cluster") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_shared_gpu(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i8_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_shared_gpu_param_0];
; CHECK-NEXT:    fence.sc.gpu;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i8_shared_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i8 %val, ptr addrspace(3) %addr syncscope("device") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_shared_sys_volatile(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i8_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_shared_sys_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i8_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(3) %addr syncscope("") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_shared_cta_volatile(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i8_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_shared_cta_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i8_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(3) %addr syncscope("block") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_shared_cluster_volatile(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i8_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_shared_cluster_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i8_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(3) %addr syncscope("cluster") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_shared_gpu_volatile(i8 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i8_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_shared_gpu_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i8_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b8 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i8 %val, ptr addrspace(3) %addr syncscope("device") seq_cst, align 1
    ret void
}

define void @seq_cst_i16_shared_sys(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i16_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_shared_sys_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i16_shared_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(3) %addr syncscope("") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_shared_cta(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i16_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_shared_cta_param_0];
; CHECK-NEXT:    fence.sc.cta;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i16_shared_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(3) %addr syncscope("block") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_shared_cluster(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i16_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_shared_cluster_param_0];
; CHECK-NEXT:    fence.sc.cluster;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i16_shared_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(3) %addr syncscope("cluster") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_shared_gpu(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i16_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_shared_gpu_param_0];
; CHECK-NEXT:    fence.sc.gpu;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i16_shared_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic i16 %val, ptr addrspace(3) %addr syncscope("device") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_shared_sys_volatile(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i16_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_shared_sys_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i16_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(3) %addr syncscope("") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_shared_cta_volatile(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i16_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_shared_cta_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i16_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(3) %addr syncscope("block") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_shared_cluster_volatile(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i16_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_shared_cluster_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i16_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(3) %addr syncscope("cluster") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_shared_gpu_volatile(i16 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i16_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_shared_gpu_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i16_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile i16 %val, ptr addrspace(3) %addr syncscope("device") seq_cst, align 2
    ret void
}

define void @seq_cst_i32_shared_sys(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i32_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_i32_shared_sys_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i32_shared_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(3) %addr syncscope("") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_shared_cta(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i32_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_i32_shared_cta_param_0];
; CHECK-NEXT:    fence.sc.cta;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i32_shared_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(3) %addr syncscope("block") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_shared_cluster(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i32_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_i32_shared_cluster_param_0];
; CHECK-NEXT:    fence.sc.cluster;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i32_shared_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(3) %addr syncscope("cluster") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_shared_gpu(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i32_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_i32_shared_gpu_param_0];
; CHECK-NEXT:    fence.sc.gpu;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i32_shared_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic i32 %val, ptr addrspace(3) %addr syncscope("device") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_shared_sys_volatile(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i32_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_i32_shared_sys_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i32_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(3) %addr syncscope("") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_shared_cta_volatile(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i32_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_i32_shared_cta_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i32_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(3) %addr syncscope("block") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_shared_cluster_volatile(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i32_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_i32_shared_cluster_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i32_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(3) %addr syncscope("cluster") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_shared_gpu_volatile(i32 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i32_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_i32_shared_gpu_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i32_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile i32 %val, ptr addrspace(3) %addr syncscope("device") seq_cst, align 4
    ret void
}

define void @seq_cst_i64_shared_sys(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i64_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_shared_sys_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_i64_shared_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(3) %addr syncscope("") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_shared_cta(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i64_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_shared_cta_param_0];
; CHECK-NEXT:    fence.sc.cta;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_i64_shared_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(3) %addr syncscope("block") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_shared_cluster(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i64_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_shared_cluster_param_0];
; CHECK-NEXT:    fence.sc.cluster;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_i64_shared_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(3) %addr syncscope("cluster") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_shared_gpu(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i64_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_shared_gpu_param_0];
; CHECK-NEXT:    fence.sc.gpu;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_i64_shared_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic i64 %val, ptr addrspace(3) %addr syncscope("device") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_shared_sys_volatile(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i64_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_shared_sys_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_i64_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(3) %addr syncscope("") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_shared_cta_volatile(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i64_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_shared_cta_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_i64_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(3) %addr syncscope("block") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_shared_cluster_volatile(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i64_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_shared_cluster_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_i64_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(3) %addr syncscope("cluster") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_shared_gpu_volatile(i64 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i64_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_shared_gpu_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_i64_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile i64 %val, ptr addrspace(3) %addr syncscope("device") seq_cst, align 8
    ret void
}

define void @seq_cst_i128_shared_sys(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i128_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_shared_sys_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd3, [seq_cst_i128_shared_sys_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.sys.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(3) %addr syncscope("") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_shared_cta(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i128_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_shared_cta_param_0];
; CHECK-NEXT:    fence.sc.cta;
; CHECK-NEXT:    ld.param.b64 %rd3, [seq_cst_i128_shared_cta_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cta.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(3) %addr syncscope("block") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_shared_cluster(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i128_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_shared_cluster_param_0];
; CHECK-NEXT:    fence.sc.cluster;
; CHECK-NEXT:    ld.param.b64 %rd3, [seq_cst_i128_shared_cluster_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cluster.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(3) %addr syncscope("cluster") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_shared_gpu(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i128_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_shared_gpu_param_0];
; CHECK-NEXT:    fence.sc.gpu;
; CHECK-NEXT:    ld.param.b64 %rd3, [seq_cst_i128_shared_gpu_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.gpu.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic i128 %val, ptr addrspace(3) %addr syncscope("device") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_shared_sys_volatile(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i128_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_shared_sys_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd3, [seq_cst_i128_shared_sys_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.sys.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(3) %addr syncscope("") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_shared_cta_volatile(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i128_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_shared_cta_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd3, [seq_cst_i128_shared_cta_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cta.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(3) %addr syncscope("block") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_shared_cluster_volatile(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i128_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_shared_cluster_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd3, [seq_cst_i128_shared_cluster_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.cluster.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(3) %addr syncscope("cluster") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_shared_gpu_volatile(i128 %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_i128_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<6>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_shared_gpu_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd3, [seq_cst_i128_shared_gpu_volatile_param_1];
; CHECK-NEXT:    {
; CHECK-NEXT:    .reg .b128 amt, dst;
; CHECK-NEXT:    mov.b128 amt, {%rd1, %rd2};
; CHECK-NEXT:    atom.relaxed.gpu.shared.exch.b128 dst, [%rd3], amt;
; CHECK-NEXT:    mov.b128 {%rd4, %rd5}, dst;
; CHECK-NEXT:    }
; CHECK-NEXT:    ret;
    store atomic volatile i128 %val, ptr addrspace(3) %addr syncscope("device") seq_cst, align 16
    ret void
}

define void @seq_cst_half_shared_sys(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_half_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_shared_sys_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_half_shared_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(3) %addr syncscope("") seq_cst, align 2
    ret void
}

define void @seq_cst_half_shared_cta(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_half_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_shared_cta_param_0];
; CHECK-NEXT:    fence.sc.cta;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_half_shared_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(3) %addr syncscope("block") seq_cst, align 2
    ret void
}

define void @seq_cst_half_shared_cluster(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_half_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_shared_cluster_param_0];
; CHECK-NEXT:    fence.sc.cluster;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_half_shared_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(3) %addr syncscope("cluster") seq_cst, align 2
    ret void
}

define void @seq_cst_half_shared_gpu(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_half_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_shared_gpu_param_0];
; CHECK-NEXT:    fence.sc.gpu;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_half_shared_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic half %val, ptr addrspace(3) %addr syncscope("device") seq_cst, align 2
    ret void
}

define void @seq_cst_half_shared_sys_volatile(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_half_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_shared_sys_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_half_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(3) %addr syncscope("") seq_cst, align 2
    ret void
}

define void @seq_cst_half_shared_cta_volatile(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_half_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_shared_cta_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_half_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(3) %addr syncscope("block") seq_cst, align 2
    ret void
}

define void @seq_cst_half_shared_cluster_volatile(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_half_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_shared_cluster_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_half_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(3) %addr syncscope("cluster") seq_cst, align 2
    ret void
}

define void @seq_cst_half_shared_gpu_volatile(half %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_half_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_shared_gpu_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_half_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile half %val, ptr addrspace(3) %addr syncscope("device") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_shared_sys(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_bfloat_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_shared_sys_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_bfloat_shared_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(3) %addr syncscope("") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_shared_cta(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_bfloat_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_shared_cta_param_0];
; CHECK-NEXT:    fence.sc.cta;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_bfloat_shared_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(3) %addr syncscope("block") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_shared_cluster(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_bfloat_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_shared_cluster_param_0];
; CHECK-NEXT:    fence.sc.cluster;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_bfloat_shared_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(3) %addr syncscope("cluster") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_shared_gpu(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_bfloat_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_shared_gpu_param_0];
; CHECK-NEXT:    fence.sc.gpu;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_bfloat_shared_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic bfloat %val, ptr addrspace(3) %addr syncscope("device") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_shared_sys_volatile(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_bfloat_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_shared_sys_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_bfloat_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(3) %addr syncscope("") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_shared_cta_volatile(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_bfloat_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_shared_cta_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_bfloat_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(3) %addr syncscope("block") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_shared_cluster_volatile(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_bfloat_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_shared_cluster_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_bfloat_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(3) %addr syncscope("cluster") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_shared_gpu_volatile(bfloat %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_bfloat_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_shared_gpu_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_bfloat_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b16 [%rd1], %rs1;
; CHECK-NEXT:    ret;
    store atomic volatile bfloat %val, ptr addrspace(3) %addr syncscope("device") seq_cst, align 2
    ret void
}

define void @seq_cst_float_shared_sys(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_float_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_float_shared_sys_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_float_shared_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(3) %addr syncscope("") seq_cst, align 4
    ret void
}

define void @seq_cst_float_shared_cta(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_float_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_float_shared_cta_param_0];
; CHECK-NEXT:    fence.sc.cta;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_float_shared_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(3) %addr syncscope("block") seq_cst, align 4
    ret void
}

define void @seq_cst_float_shared_cluster(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_float_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_float_shared_cluster_param_0];
; CHECK-NEXT:    fence.sc.cluster;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_float_shared_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(3) %addr syncscope("cluster") seq_cst, align 4
    ret void
}

define void @seq_cst_float_shared_gpu(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_float_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_float_shared_gpu_param_0];
; CHECK-NEXT:    fence.sc.gpu;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_float_shared_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic float %val, ptr addrspace(3) %addr syncscope("device") seq_cst, align 4
    ret void
}

define void @seq_cst_float_shared_sys_volatile(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_float_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_float_shared_sys_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_float_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(3) %addr syncscope("") seq_cst, align 4
    ret void
}

define void @seq_cst_float_shared_cta_volatile(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_float_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_float_shared_cta_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_float_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(3) %addr syncscope("block") seq_cst, align 4
    ret void
}

define void @seq_cst_float_shared_cluster_volatile(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_float_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_float_shared_cluster_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_float_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(3) %addr syncscope("cluster") seq_cst, align 4
    ret void
}

define void @seq_cst_float_shared_gpu_volatile(float %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_float_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b32 %r1, [seq_cst_float_shared_gpu_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_float_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b32 [%rd1], %r1;
; CHECK-NEXT:    ret;
    store atomic volatile float %val, ptr addrspace(3) %addr syncscope("device") seq_cst, align 4
    ret void
}

define void @seq_cst_double_shared_sys(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_double_shared_sys(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_shared_sys_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_double_shared_sys_param_1];
; CHECK-NEXT:    st.relaxed.sys.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(3) %addr syncscope("") seq_cst, align 8
    ret void
}

define void @seq_cst_double_shared_cta(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_double_shared_cta(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_shared_cta_param_0];
; CHECK-NEXT:    fence.sc.cta;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_double_shared_cta_param_1];
; CHECK-NEXT:    st.relaxed.cta.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(3) %addr syncscope("block") seq_cst, align 8
    ret void
}

define void @seq_cst_double_shared_cluster(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_double_shared_cluster(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_shared_cluster_param_0];
; CHECK-NEXT:    fence.sc.cluster;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_double_shared_cluster_param_1];
; CHECK-NEXT:    st.relaxed.cluster.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(3) %addr syncscope("cluster") seq_cst, align 8
    ret void
}

define void @seq_cst_double_shared_gpu(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_double_shared_gpu(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_shared_gpu_param_0];
; CHECK-NEXT:    fence.sc.gpu;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_double_shared_gpu_param_1];
; CHECK-NEXT:    st.relaxed.gpu.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic double %val, ptr addrspace(3) %addr syncscope("device") seq_cst, align 8
    ret void
}

define void @seq_cst_double_shared_sys_volatile(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_double_shared_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_shared_sys_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_double_shared_sys_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(3) %addr syncscope("") seq_cst, align 8
    ret void
}

define void @seq_cst_double_shared_cta_volatile(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_double_shared_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_shared_cta_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_double_shared_cta_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(3) %addr syncscope("block") seq_cst, align 8
    ret void
}

define void @seq_cst_double_shared_cluster_volatile(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_double_shared_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_shared_cluster_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_double_shared_cluster_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(3) %addr syncscope("cluster") seq_cst, align 8
    ret void
}

define void @seq_cst_double_shared_gpu_volatile(double %val, ptr addrspace(3) %addr) {
; CHECK-LABEL: seq_cst_double_shared_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_shared_gpu_volatile_param_0];
; CHECK-NEXT:    fence.sc.sys;
; CHECK-NEXT:    ld.param.b64 %rd2, [seq_cst_double_shared_gpu_volatile_param_1];
; CHECK-NEXT:    st.volatile.shared.b64 [%rd2], %rd1;
; CHECK-NEXT:    ret;
    store atomic volatile double %val, ptr addrspace(3) %addr syncscope("device") seq_cst, align 8
    ret void
}

define void @seq_cst_i8_local_sys(i8 %val) {
; CHECK-LABEL: seq_cst_i8_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot1152[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1152;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i8 %val, ptr addrspace(5) %slot syncscope("") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_local_cta(i8 %val) {
; CHECK-LABEL: seq_cst_i8_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot1153[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1153;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i8 %val, ptr addrspace(5) %slot syncscope("block") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_local_cluster(i8 %val) {
; CHECK-LABEL: seq_cst_i8_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot1154[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1154;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i8 %val, ptr addrspace(5) %slot syncscope("cluster") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_local_gpu(i8 %val) {
; CHECK-LABEL: seq_cst_i8_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot1155[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1155;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i8 %val, ptr addrspace(5) %slot syncscope("device") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_local_sys_volatile(i8 %val) {
; CHECK-LABEL: seq_cst_i8_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot1156[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1156;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i8 %val, ptr addrspace(5) %slot syncscope("") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_local_cta_volatile(i8 %val) {
; CHECK-LABEL: seq_cst_i8_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot1157[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1157;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i8 %val, ptr addrspace(5) %slot syncscope("block") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_local_cluster_volatile(i8 %val) {
; CHECK-LABEL: seq_cst_i8_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot1158[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1158;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i8 %val, ptr addrspace(5) %slot syncscope("cluster") seq_cst, align 1
    ret void
}

define void @seq_cst_i8_local_gpu_volatile(i8 %val) {
; CHECK-LABEL: seq_cst_i8_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 1 .b8 __local_depot1159[1];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1159;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b8 %rs1, [seq_cst_i8_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b8 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i8, align 1, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i8 %val, ptr addrspace(5) %slot syncscope("device") seq_cst, align 1
    ret void
}

define void @seq_cst_i16_local_sys(i16 %val) {
; CHECK-LABEL: seq_cst_i16_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot1160[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1160;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i16 %val, ptr addrspace(5) %slot syncscope("") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_local_cta(i16 %val) {
; CHECK-LABEL: seq_cst_i16_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot1161[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1161;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i16 %val, ptr addrspace(5) %slot syncscope("block") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_local_cluster(i16 %val) {
; CHECK-LABEL: seq_cst_i16_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot1162[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1162;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i16 %val, ptr addrspace(5) %slot syncscope("cluster") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_local_gpu(i16 %val) {
; CHECK-LABEL: seq_cst_i16_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot1163[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1163;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i16 %val, ptr addrspace(5) %slot syncscope("device") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_local_sys_volatile(i16 %val) {
; CHECK-LABEL: seq_cst_i16_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot1164[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1164;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i16 %val, ptr addrspace(5) %slot syncscope("") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_local_cta_volatile(i16 %val) {
; CHECK-LABEL: seq_cst_i16_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot1165[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1165;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i16 %val, ptr addrspace(5) %slot syncscope("block") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_local_cluster_volatile(i16 %val) {
; CHECK-LABEL: seq_cst_i16_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot1166[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1166;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i16 %val, ptr addrspace(5) %slot syncscope("cluster") seq_cst, align 2
    ret void
}

define void @seq_cst_i16_local_gpu_volatile(i16 %val) {
; CHECK-LABEL: seq_cst_i16_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot1167[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1167;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_i16_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca i16, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i16 %val, ptr addrspace(5) %slot syncscope("device") seq_cst, align 2
    ret void
}

define void @seq_cst_i32_local_sys(i32 %val) {
; CHECK-LABEL: seq_cst_i32_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot1168[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1168;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [seq_cst_i32_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i32 %val, ptr addrspace(5) %slot syncscope("") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_local_cta(i32 %val) {
; CHECK-LABEL: seq_cst_i32_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot1169[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1169;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [seq_cst_i32_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i32 %val, ptr addrspace(5) %slot syncscope("block") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_local_cluster(i32 %val) {
; CHECK-LABEL: seq_cst_i32_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot1170[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1170;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [seq_cst_i32_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i32 %val, ptr addrspace(5) %slot syncscope("cluster") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_local_gpu(i32 %val) {
; CHECK-LABEL: seq_cst_i32_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot1171[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1171;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [seq_cst_i32_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i32 %val, ptr addrspace(5) %slot syncscope("device") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_local_sys_volatile(i32 %val) {
; CHECK-LABEL: seq_cst_i32_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot1172[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1172;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [seq_cst_i32_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i32 %val, ptr addrspace(5) %slot syncscope("") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_local_cta_volatile(i32 %val) {
; CHECK-LABEL: seq_cst_i32_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot1173[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1173;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [seq_cst_i32_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i32 %val, ptr addrspace(5) %slot syncscope("block") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_local_cluster_volatile(i32 %val) {
; CHECK-LABEL: seq_cst_i32_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot1174[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1174;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [seq_cst_i32_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i32 %val, ptr addrspace(5) %slot syncscope("cluster") seq_cst, align 4
    ret void
}

define void @seq_cst_i32_local_gpu_volatile(i32 %val) {
; CHECK-LABEL: seq_cst_i32_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot1175[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1175;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [seq_cst_i32_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca i32, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i32 %val, ptr addrspace(5) %slot syncscope("device") seq_cst, align 4
    ret void
}

define void @seq_cst_i64_local_sys(i64 %val) {
; CHECK-LABEL: seq_cst_i64_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot1176[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1176;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i64 %val, ptr addrspace(5) %slot syncscope("") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_local_cta(i64 %val) {
; CHECK-LABEL: seq_cst_i64_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot1177[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1177;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i64 %val, ptr addrspace(5) %slot syncscope("block") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_local_cluster(i64 %val) {
; CHECK-LABEL: seq_cst_i64_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot1178[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1178;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i64 %val, ptr addrspace(5) %slot syncscope("cluster") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_local_gpu(i64 %val) {
; CHECK-LABEL: seq_cst_i64_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot1179[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1179;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i64 %val, ptr addrspace(5) %slot syncscope("device") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_local_sys_volatile(i64 %val) {
; CHECK-LABEL: seq_cst_i64_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot1180[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1180;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i64 %val, ptr addrspace(5) %slot syncscope("") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_local_cta_volatile(i64 %val) {
; CHECK-LABEL: seq_cst_i64_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot1181[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1181;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i64 %val, ptr addrspace(5) %slot syncscope("block") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_local_cluster_volatile(i64 %val) {
; CHECK-LABEL: seq_cst_i64_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot1182[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1182;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i64 %val, ptr addrspace(5) %slot syncscope("cluster") seq_cst, align 8
    ret void
}

define void @seq_cst_i64_local_gpu_volatile(i64 %val) {
; CHECK-LABEL: seq_cst_i64_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot1183[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1183;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_i64_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca i64, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i64 %val, ptr addrspace(5) %slot syncscope("device") seq_cst, align 8
    ret void
}

define void @seq_cst_i128_local_sys(i128 %val) {
; CHECK-LABEL: seq_cst_i128_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot1184[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1184;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i128 %val, ptr addrspace(5) %slot syncscope("") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_local_cta(i128 %val) {
; CHECK-LABEL: seq_cst_i128_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot1185[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1185;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i128 %val, ptr addrspace(5) %slot syncscope("block") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_local_cluster(i128 %val) {
; CHECK-LABEL: seq_cst_i128_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot1186[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1186;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i128 %val, ptr addrspace(5) %slot syncscope("cluster") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_local_gpu(i128 %val) {
; CHECK-LABEL: seq_cst_i128_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot1187[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1187;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic i128 %val, ptr addrspace(5) %slot syncscope("device") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_local_sys_volatile(i128 %val) {
; CHECK-LABEL: seq_cst_i128_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot1188[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1188;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i128 %val, ptr addrspace(5) %slot syncscope("") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_local_cta_volatile(i128 %val) {
; CHECK-LABEL: seq_cst_i128_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot1189[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1189;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i128 %val, ptr addrspace(5) %slot syncscope("block") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_local_cluster_volatile(i128 %val) {
; CHECK-LABEL: seq_cst_i128_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot1190[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1190;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i128 %val, ptr addrspace(5) %slot syncscope("cluster") seq_cst, align 16
    ret void
}

define void @seq_cst_i128_local_gpu_volatile(i128 %val) {
; CHECK-LABEL: seq_cst_i128_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 16 .b8 __local_depot1191[16];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<4>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1191;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.v2.b64 {%rd1, %rd2}, [seq_cst_i128_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd3, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.v2.b64 [%SP], {%rd1, %rd2};
; CHECK-NEXT:    ret;
    %slot = alloca i128, align 16, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile i128 %val, ptr addrspace(5) %slot syncscope("device") seq_cst, align 16
    ret void
}

define void @seq_cst_half_local_sys(half %val) {
; CHECK-LABEL: seq_cst_half_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot1192[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1192;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic half %val, ptr addrspace(5) %slot syncscope("") seq_cst, align 2
    ret void
}

define void @seq_cst_half_local_cta(half %val) {
; CHECK-LABEL: seq_cst_half_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot1193[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1193;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic half %val, ptr addrspace(5) %slot syncscope("block") seq_cst, align 2
    ret void
}

define void @seq_cst_half_local_cluster(half %val) {
; CHECK-LABEL: seq_cst_half_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot1194[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1194;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic half %val, ptr addrspace(5) %slot syncscope("cluster") seq_cst, align 2
    ret void
}

define void @seq_cst_half_local_gpu(half %val) {
; CHECK-LABEL: seq_cst_half_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot1195[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1195;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic half %val, ptr addrspace(5) %slot syncscope("device") seq_cst, align 2
    ret void
}

define void @seq_cst_half_local_sys_volatile(half %val) {
; CHECK-LABEL: seq_cst_half_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot1196[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1196;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile half %val, ptr addrspace(5) %slot syncscope("") seq_cst, align 2
    ret void
}

define void @seq_cst_half_local_cta_volatile(half %val) {
; CHECK-LABEL: seq_cst_half_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot1197[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1197;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile half %val, ptr addrspace(5) %slot syncscope("block") seq_cst, align 2
    ret void
}

define void @seq_cst_half_local_cluster_volatile(half %val) {
; CHECK-LABEL: seq_cst_half_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot1198[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1198;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile half %val, ptr addrspace(5) %slot syncscope("cluster") seq_cst, align 2
    ret void
}

define void @seq_cst_half_local_gpu_volatile(half %val) {
; CHECK-LABEL: seq_cst_half_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot1199[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1199;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_half_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca half, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile half %val, ptr addrspace(5) %slot syncscope("device") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_local_sys(bfloat %val) {
; CHECK-LABEL: seq_cst_bfloat_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot1200[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1200;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic bfloat %val, ptr addrspace(5) %slot syncscope("") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_local_cta(bfloat %val) {
; CHECK-LABEL: seq_cst_bfloat_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot1201[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1201;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic bfloat %val, ptr addrspace(5) %slot syncscope("block") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_local_cluster(bfloat %val) {
; CHECK-LABEL: seq_cst_bfloat_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot1202[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1202;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic bfloat %val, ptr addrspace(5) %slot syncscope("cluster") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_local_gpu(bfloat %val) {
; CHECK-LABEL: seq_cst_bfloat_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot1203[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1203;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic bfloat %val, ptr addrspace(5) %slot syncscope("device") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_local_sys_volatile(bfloat %val) {
; CHECK-LABEL: seq_cst_bfloat_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot1204[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1204;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile bfloat %val, ptr addrspace(5) %slot syncscope("") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_local_cta_volatile(bfloat %val) {
; CHECK-LABEL: seq_cst_bfloat_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot1205[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1205;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile bfloat %val, ptr addrspace(5) %slot syncscope("block") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_local_cluster_volatile(bfloat %val) {
; CHECK-LABEL: seq_cst_bfloat_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot1206[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1206;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile bfloat %val, ptr addrspace(5) %slot syncscope("cluster") seq_cst, align 2
    ret void
}

define void @seq_cst_bfloat_local_gpu_volatile(bfloat %val) {
; CHECK-LABEL: seq_cst_bfloat_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 2 .b8 __local_depot1207[2];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b16 %rs<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1207;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b16 %rs1, [seq_cst_bfloat_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b16 [%SP], %rs1;
; CHECK-NEXT:    ret;
    %slot = alloca bfloat, align 2, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile bfloat %val, ptr addrspace(5) %slot syncscope("device") seq_cst, align 2
    ret void
}

define void @seq_cst_float_local_sys(float %val) {
; CHECK-LABEL: seq_cst_float_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot1208[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1208;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [seq_cst_float_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic float %val, ptr addrspace(5) %slot syncscope("") seq_cst, align 4
    ret void
}

define void @seq_cst_float_local_cta(float %val) {
; CHECK-LABEL: seq_cst_float_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot1209[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1209;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [seq_cst_float_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic float %val, ptr addrspace(5) %slot syncscope("block") seq_cst, align 4
    ret void
}

define void @seq_cst_float_local_cluster(float %val) {
; CHECK-LABEL: seq_cst_float_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot1210[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1210;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [seq_cst_float_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic float %val, ptr addrspace(5) %slot syncscope("cluster") seq_cst, align 4
    ret void
}

define void @seq_cst_float_local_gpu(float %val) {
; CHECK-LABEL: seq_cst_float_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot1211[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1211;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [seq_cst_float_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic float %val, ptr addrspace(5) %slot syncscope("device") seq_cst, align 4
    ret void
}

define void @seq_cst_float_local_sys_volatile(float %val) {
; CHECK-LABEL: seq_cst_float_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot1212[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1212;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [seq_cst_float_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile float %val, ptr addrspace(5) %slot syncscope("") seq_cst, align 4
    ret void
}

define void @seq_cst_float_local_cta_volatile(float %val) {
; CHECK-LABEL: seq_cst_float_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot1213[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1213;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [seq_cst_float_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile float %val, ptr addrspace(5) %slot syncscope("block") seq_cst, align 4
    ret void
}

define void @seq_cst_float_local_cluster_volatile(float %val) {
; CHECK-LABEL: seq_cst_float_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot1214[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1214;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [seq_cst_float_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile float %val, ptr addrspace(5) %slot syncscope("cluster") seq_cst, align 4
    ret void
}

define void @seq_cst_float_local_gpu_volatile(float %val) {
; CHECK-LABEL: seq_cst_float_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 4 .b8 __local_depot1215[4];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<3>;
; CHECK-NEXT:    .reg .b64 %rd<2>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1215;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b32 %r2, [seq_cst_float_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd1, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd1;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b32 [%SP], %r2;
; CHECK-NEXT:    ret;
    %slot = alloca float, align 4, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile float %val, ptr addrspace(5) %slot syncscope("device") seq_cst, align 4
    ret void
}

define void @seq_cst_double_local_sys(double %val) {
; CHECK-LABEL: seq_cst_double_local_sys(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot1216[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1216;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_local_sys_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic double %val, ptr addrspace(5) %slot syncscope("") seq_cst, align 8
    ret void
}

define void @seq_cst_double_local_cta(double %val) {
; CHECK-LABEL: seq_cst_double_local_cta(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot1217[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1217;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_local_cta_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic double %val, ptr addrspace(5) %slot syncscope("block") seq_cst, align 8
    ret void
}

define void @seq_cst_double_local_cluster(double %val) {
; CHECK-LABEL: seq_cst_double_local_cluster(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot1218[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1218;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_local_cluster_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic double %val, ptr addrspace(5) %slot syncscope("cluster") seq_cst, align 8
    ret void
}

define void @seq_cst_double_local_gpu(double %val) {
; CHECK-LABEL: seq_cst_double_local_gpu(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot1219[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1219;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_local_gpu_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic double %val, ptr addrspace(5) %slot syncscope("device") seq_cst, align 8
    ret void
}

define void @seq_cst_double_local_sys_volatile(double %val) {
; CHECK-LABEL: seq_cst_double_local_sys_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot1220[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1220;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_local_sys_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile double %val, ptr addrspace(5) %slot syncscope("") seq_cst, align 8
    ret void
}

define void @seq_cst_double_local_cta_volatile(double %val) {
; CHECK-LABEL: seq_cst_double_local_cta_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot1221[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1221;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_local_cta_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile double %val, ptr addrspace(5) %slot syncscope("block") seq_cst, align 8
    ret void
}

define void @seq_cst_double_local_cluster_volatile(double %val) {
; CHECK-LABEL: seq_cst_double_local_cluster_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot1222[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1222;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_local_cluster_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile double %val, ptr addrspace(5) %slot syncscope("cluster") seq_cst, align 8
    ret void
}

define void @seq_cst_double_local_gpu_volatile(double %val) {
; CHECK-LABEL: seq_cst_double_local_gpu_volatile(
; CHECK:       {
; CHECK-NEXT:    .local .align 8 .b8 __local_depot1223[8];
; CHECK-NEXT:    .reg .b64 %SP;
; CHECK-NEXT:    .reg .b64 %SPL;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    mov.b64 %SPL, __local_depot1223;
; CHECK-NEXT:    cvta.local.u64 %SP, %SPL;
; CHECK-NEXT:    ld.param.b64 %rd1, [seq_cst_double_local_gpu_volatile_param_0];
; CHECK-NEXT:    add.u64 %rd2, %SP, 0;
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd2;
; CHECK-NEXT:    // begin inline asm
; CHECK-NEXT:    // end inline asm
; CHECK-NEXT:    st.local.b64 [%SP], %rd1;
; CHECK-NEXT:    ret;
    %slot = alloca double, align 8, addrspace(5)
    call void asm sideeffect "", "r"(ptr addrspace(5) %slot)
    store atomic volatile double %val, ptr addrspace(5) %slot syncscope("device") seq_cst, align 8
    ret void
}

