; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=nvptx64 -mcpu=sm_100a -mattr=+ptx87 | FileCheck %s
; RUN: %if ptxas-isa-8.7 && ptxas-sm_100a %{ llc < %s -mtriple=nvptx64 -mcpu=sm_100a -mattr=+ptx87 | %ptxas-verify -arch=sm_100a %}

define void @tensormap_replace_swizzle_atomicity(ptr addrspace(1) %global_addr, ptr addrspace(3) %shared_addr) {
; CHECK-LABEL: tensormap_replace_swizzle_atomicity(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [tensormap_replace_swizzle_atomicity_param_0];
; CHECK-NEXT:    tensormap.replace.tile.swizzle_atomicity.global.b1024.b32 [%rd1], 0;
; CHECK-NEXT:    ld.param.b64 %rd2, [tensormap_replace_swizzle_atomicity_param_1];
; CHECK-NEXT:    tensormap.replace.tile.swizzle_atomicity.shared::cta.b1024.b32 [%rd2], 0;
; CHECK-NEXT:    tensormap.replace.tile.swizzle_atomicity.global.b1024.b32 [%rd1], 1;
; CHECK-NEXT:    tensormap.replace.tile.swizzle_atomicity.shared::cta.b1024.b32 [%rd2], 1;
; CHECK-NEXT:    tensormap.replace.tile.swizzle_atomicity.global.b1024.b32 [%rd1], 2;
; CHECK-NEXT:    tensormap.replace.tile.swizzle_atomicity.shared::cta.b1024.b32 [%rd2], 2;
; CHECK-NEXT:    tensormap.replace.tile.swizzle_atomicity.global.b1024.b32 [%rd1], 3;
; CHECK-NEXT:    tensormap.replace.tile.swizzle_atomicity.shared::cta.b1024.b32 [%rd2], 3;
; CHECK-NEXT:    ret;
  call void @llvm.nvvm.tensormap.replace.swizzle.atomicity.p1(ptr addrspace(1) %global_addr, /* swizzle_atomicity=16B */ i32 0)
  call void @llvm.nvvm.tensormap.replace.swizzle.atomicity.p3(ptr addrspace(3) %shared_addr, /* swizzle_atomicity=16B */ i32 0)

  call void @llvm.nvvm.tensormap.replace.swizzle.atomicity.p1(ptr addrspace(1) %global_addr, /* swizzle_atomicity=32B */ i32 1)
  call void @llvm.nvvm.tensormap.replace.swizzle.atomicity.p3(ptr addrspace(3) %shared_addr, /* swizzle_atomicity=32B */ i32 1)

  call void @llvm.nvvm.tensormap.replace.swizzle.atomicity.p1(ptr addrspace(1) %global_addr, /* swizzle_atomicity=32B + 8B flip */ i32 2)
  call void @llvm.nvvm.tensormap.replace.swizzle.atomicity.p3(ptr addrspace(3) %shared_addr, /* swizzle_atomicity=32B + 8B flip */ i32 2)
  
  call void @llvm.nvvm.tensormap.replace.swizzle.atomicity.p1(ptr addrspace(1) %global_addr, /* swizzle_atomicity=64B */ i32 3)
  call void @llvm.nvvm.tensormap.replace.swizzle.atomicity.p3(ptr addrspace(3) %shared_addr, /* swizzle_atomicity=64B */ i32 3)
  ret void
}

define void @tensormap_replace_elemtype(ptr addrspace(1) %global_addr, ptr addrspace(3) %shared_addr) {
; CHECK-LABEL: tensormap_replace_elemtype(
; CHECK:       {
; CHECK-NEXT:    .reg .b64 %rd<3>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd1, [tensormap_replace_elemtype_param_0];
; CHECK-NEXT:    tensormap.replace.tile.elemtype.global.b1024.b32 [%rd1], 13;
; CHECK-NEXT:    ld.param.b64 %rd2, [tensormap_replace_elemtype_param_1];
; CHECK-NEXT:    tensormap.replace.tile.elemtype.shared::cta.b1024.b32 [%rd2], 13;
; CHECK-NEXT:    tensormap.replace.tile.elemtype.global.b1024.b32 [%rd1], 14;
; CHECK-NEXT:    tensormap.replace.tile.elemtype.shared::cta.b1024.b32 [%rd2], 14;
; CHECK-NEXT:    tensormap.replace.tile.elemtype.global.b1024.b32 [%rd1], 15;
; CHECK-NEXT:    tensormap.replace.tile.elemtype.shared::cta.b1024.b32 [%rd2], 15;
; CHECK-NEXT:    ret;
  call void @llvm.nvvm.tensormap.replace.elemtype.p1(ptr addrspace(1) %global_addr, /* elemtype=b4x16 */ i32 13)
  call void @llvm.nvvm.tensormap.replace.elemtype.p3(ptr addrspace(3) %shared_addr, /* elemtype=b4x16 */ i32 13)

  call void @llvm.nvvm.tensormap.replace.elemtype.p1(ptr addrspace(1) %global_addr, /* elemtype=b4x16_p64 */ i32 14)
  call void @llvm.nvvm.tensormap.replace.elemtype.p3(ptr addrspace(3) %shared_addr, /* elemtype=b4x16_p64 */ i32 14)

  call void @llvm.nvvm.tensormap.replace.elemtype.p1(ptr addrspace(1) %global_addr, /* elemtype=b6x16_p32 */ i32 15)
  call void @llvm.nvvm.tensormap.replace.elemtype.p3(ptr addrspace(3) %shared_addr, /* elemtype=b6x16_p32 */ i32 15)
  ret void
}
