; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc < %s -mtriple=nvptx64 -mcpu=sm_90 -mattr=+ptx86 | FileCheck --check-prefixes=CHECK %s
; RUN: %if ptxas-sm_90 && ptxas-isa-8.6 %{ llc < %s -mtriple=nvptx64 -mcpu=sm_90 -mattr=+ptx86 | %ptxas-verify -arch=sm_90 %}

; CHECK-LABEL: test_fence_acquire
define void @test_fence_acquire() {
; CHECK-LABEL: test_fence_acquire(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    fence.acquire.sync_restrict::shared::cluster.cluster;
; CHECK-NEXT:    ret;
  call void @llvm.nvvm.fence.acquire.sync_restrict.space.cluster.scope.cluster();

  ret void
}

; CHECK-LABEL: test_fence_release
define void @test_fence_release() {
; CHECK-LABEL: test_fence_release(
; CHECK:       {
; CHECK-EMPTY:
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    fence.release.sync_restrict::shared::cta.cluster;
; CHECK-NEXT:    ret;
  call void @llvm.nvvm.fence.release.sync_restrict.space.cta.scope.cluster();

  ret void
}
