; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -march=nvptx64 < %s | FileCheck %s

define void @test_select_truncate_free(ptr %p, ptr %q, ptr %r) {
; CHECK-LABEL: test_select_truncate_free(
; CHECK:       {
; CHECK-NEXT:    .reg .pred %p<2>;
; CHECK-NEXT:    .reg .b32 %r<2>;
; CHECK-NEXT:    .reg .b64 %rd<5>;
; CHECK-EMPTY:
; CHECK-NEXT:  // %bb.0:
; CHECK-NEXT:    ld.param.b64 %rd2, [test_select_truncate_free_param_0];
; CHECK-NEXT:    ld.b32 %rd3, [%rd2];
; CHECK-NEXT:    setp.eq.b64 %p1, %rd3, 0;
; CHECK-NEXT:    ld.param.b64 %rd4, [test_select_truncate_free_param_1];
; CHECK-NEXT:    st.b64 [%rd4], %rd3;
; CHECK-NEXT:    @%p1 bra $L__BB0_2;
; CHECK-NEXT:  // %bb.1: // %if
; CHECK-NEXT:    ld.param.b64 %rd1, [test_select_truncate_free_param_2];
; CHECK-NEXT:    cvt.u32.u64 %r1, %rd3;
; CHECK-NEXT:    st.b32 [%rd1], %r1;
; CHECK-NEXT:  $L__BB0_2: // %end
; CHECK-NEXT:    ret;
  %a = load i32, ptr %p
  %b = zext i32 %a to i64
  store i64 %b, ptr %q
  %c = icmp ne i32 %a, 0
  br i1 %c, label %if, label %end

if:
  store i32 %a, ptr %r
  br label %end

end:
  ret void
}
