# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx908 -verify-machineinstrs -run-pass=prologepilog %s -o - | FileCheck -check-prefix=GFX908 %s
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx908 -passes='prolog-epilog' %s -o - | FileCheck -check-prefix=GFX908 %s
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx90a -verify-machineinstrs -run-pass=prologepilog %s -o - | FileCheck -check-prefix=GFX90A %s
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx90a -passes='prolog-epilog' %s -o - | FileCheck -check-prefix=GFX90A %s
# RUN: llc -mattr=+enable-flat-scratch -mtriple=amdgcn-amd-amdhsa -mcpu=gfx908 -verify-machineinstrs -run-pass=prologepilog %s -o - | FileCheck -check-prefix=GFX908-FLATSCR %s
# RUN: llc -mattr=+enable-flat-scratch -mtriple=amdgcn-amd-amdhsa -mcpu=gfx908 -passes='prolog-epilog' %s -o - | FileCheck -check-prefix=GFX908-FLATSCR %s
# RUN: llc -mattr=+enable-flat-scratch -mtriple=amdgcn-amd-amdhsa -mcpu=gfx90a -verify-machineinstrs -run-pass=prologepilog %s -o - | FileCheck -check-prefix=GFX90A-FLATSCR %s
# RUN: llc -mattr=+enable-flat-scratch -mtriple=amdgcn-amd-amdhsa -mcpu=gfx90a -passes='prolog-epilog' %s -o - | FileCheck -check-prefix=GFX90A-FLATSCR %s

---
name: agpr32_restore_clobber_scc
tracksRegLiveness: true
stack:
  - { id: 0, type: default, offset: 0, size: 8192, alignment: 8 }
  - { id: 1, type: spill-slot, offset: 0, size: 8192, alignment: 4 }

machineFunctionInfo:
  scratchRSrcReg:  $sgpr0_sgpr1_sgpr2_sgpr3
  frameOffsetReg:  $sgpr33
  stackPtrOffsetReg:  $sgpr32

body:             |
  ; GFX908-LABEL: name: agpr32_restore_clobber_scc
  ; GFX908: bb.0:
  ; GFX908-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GFX908-NEXT:   liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT:   S_CMP_EQ_U32 0, 0, implicit-def $scc
  ; GFX908-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $vgpr1, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.2, addrspace 5)
  ; GFX908-NEXT:   $vgpr1 = V_MOV_B32_e32 8200, implicit $exec
  ; GFX908-NEXT:   $vgpr0 = BUFFER_LOAD_DWORD_OFFEN $vgpr1, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.1, addrspace 5)
  ; GFX908-NEXT:   $agpr0 = V_ACCVGPR_WRITE_B32_e64 killed $vgpr0, implicit $exec
  ; GFX908-NEXT:   $vgpr1 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.2, addrspace 5)
  ; GFX908-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT: bb.1:
  ; GFX908-NEXT:   successors: %bb.2(0x80000000)
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT:   S_NOP 0
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT: bb.2:
  ; GFX908-NEXT:   liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT:   S_ENDPGM 0, amdgpu_allvgprs
  ;
  ; GFX90A-LABEL: name: agpr32_restore_clobber_scc
  ; GFX90A: bb.0:
  ; GFX90A-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GFX90A-NEXT:   liveins: $agpr32, $agpr33, $agpr34, $agpr35, $agpr36, $agpr37, $agpr38, $agpr39, $agpr40, $agpr41, $agpr42, $agpr43, $agpr44, $agpr45, $agpr46, $agpr47, $agpr48, $agpr49, $agpr50, $agpr51, $agpr52, $agpr53, $agpr54, $agpr55, $agpr56, $agpr57, $agpr58, $agpr59, $agpr60, $agpr61, $agpr62, $agpr63, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   $vgpr0 = V_ACCVGPR_READ_B32_e64 killed $agpr32, implicit $exec
  ; GFX90A-NEXT:   $vgpr1 = V_ACCVGPR_READ_B32_e64 killed $agpr33, implicit $exec
  ; GFX90A-NEXT:   $vgpr2 = V_ACCVGPR_READ_B32_e64 killed $agpr34, implicit $exec
  ; GFX90A-NEXT:   $vgpr3 = V_ACCVGPR_READ_B32_e64 killed $agpr35, implicit $exec
  ; GFX90A-NEXT:   $vgpr4 = V_ACCVGPR_READ_B32_e64 killed $agpr36, implicit $exec
  ; GFX90A-NEXT:   $vgpr5 = V_ACCVGPR_READ_B32_e64 killed $agpr37, implicit $exec
  ; GFX90A-NEXT:   $vgpr6 = V_ACCVGPR_READ_B32_e64 killed $agpr38, implicit $exec
  ; GFX90A-NEXT:   $vgpr7 = V_ACCVGPR_READ_B32_e64 killed $agpr39, implicit $exec
  ; GFX90A-NEXT:   $vgpr8 = V_ACCVGPR_READ_B32_e64 killed $agpr40, implicit $exec
  ; GFX90A-NEXT:   $vgpr9 = V_ACCVGPR_READ_B32_e64 killed $agpr41, implicit $exec
  ; GFX90A-NEXT:   $vgpr10 = V_ACCVGPR_READ_B32_e64 killed $agpr42, implicit $exec
  ; GFX90A-NEXT:   $vgpr11 = V_ACCVGPR_READ_B32_e64 killed $agpr43, implicit $exec
  ; GFX90A-NEXT:   $vgpr12 = V_ACCVGPR_READ_B32_e64 killed $agpr44, implicit $exec
  ; GFX90A-NEXT:   $vgpr13 = V_ACCVGPR_READ_B32_e64 killed $agpr45, implicit $exec
  ; GFX90A-NEXT:   $vgpr14 = V_ACCVGPR_READ_B32_e64 killed $agpr46, implicit $exec
  ; GFX90A-NEXT:   $vgpr15 = V_ACCVGPR_READ_B32_e64 killed $agpr47, implicit $exec
  ; GFX90A-NEXT:   $vgpr16 = V_ACCVGPR_READ_B32_e64 killed $agpr48, implicit $exec
  ; GFX90A-NEXT:   $vgpr17 = V_ACCVGPR_READ_B32_e64 killed $agpr49, implicit $exec
  ; GFX90A-NEXT:   $vgpr18 = V_ACCVGPR_READ_B32_e64 killed $agpr50, implicit $exec
  ; GFX90A-NEXT:   $vgpr19 = V_ACCVGPR_READ_B32_e64 killed $agpr51, implicit $exec
  ; GFX90A-NEXT:   $vgpr20 = V_ACCVGPR_READ_B32_e64 killed $agpr52, implicit $exec
  ; GFX90A-NEXT:   $vgpr21 = V_ACCVGPR_READ_B32_e64 killed $agpr53, implicit $exec
  ; GFX90A-NEXT:   $vgpr22 = V_ACCVGPR_READ_B32_e64 killed $agpr54, implicit $exec
  ; GFX90A-NEXT:   $vgpr23 = V_ACCVGPR_READ_B32_e64 killed $agpr55, implicit $exec
  ; GFX90A-NEXT:   $vgpr24 = V_ACCVGPR_READ_B32_e64 killed $agpr56, implicit $exec
  ; GFX90A-NEXT:   $vgpr25 = V_ACCVGPR_READ_B32_e64 killed $agpr57, implicit $exec
  ; GFX90A-NEXT:   $vgpr26 = V_ACCVGPR_READ_B32_e64 killed $agpr58, implicit $exec
  ; GFX90A-NEXT:   $vgpr27 = V_ACCVGPR_READ_B32_e64 killed $agpr59, implicit $exec
  ; GFX90A-NEXT:   $vgpr28 = V_ACCVGPR_READ_B32_e64 killed $agpr60, implicit $exec
  ; GFX90A-NEXT:   $vgpr29 = V_ACCVGPR_READ_B32_e64 killed $agpr61, implicit $exec
  ; GFX90A-NEXT:   $vgpr30 = V_ACCVGPR_READ_B32_e64 killed $agpr62, implicit $exec
  ; GFX90A-NEXT:   $vgpr31 = V_ACCVGPR_READ_B32_e64 killed $agpr63, implicit $exec
  ; GFX90A-NEXT:   $vgpr32 = V_ACCVGPR_READ_B32_e64 killed $agpr64, implicit $exec
  ; GFX90A-NEXT:   $vgpr33 = V_ACCVGPR_READ_B32_e64 killed $agpr65, implicit $exec
  ; GFX90A-NEXT:   $vgpr34 = V_ACCVGPR_READ_B32_e64 killed $agpr66, implicit $exec
  ; GFX90A-NEXT:   $vgpr35 = V_ACCVGPR_READ_B32_e64 killed $agpr67, implicit $exec
  ; GFX90A-NEXT:   $vgpr36 = V_ACCVGPR_READ_B32_e64 killed $agpr68, implicit $exec
  ; GFX90A-NEXT:   $vgpr37 = V_ACCVGPR_READ_B32_e64 killed $agpr69, implicit $exec
  ; GFX90A-NEXT:   $vgpr38 = V_ACCVGPR_READ_B32_e64 killed $agpr70, implicit $exec
  ; GFX90A-NEXT:   $vgpr39 = V_ACCVGPR_READ_B32_e64 killed $agpr71, implicit $exec
  ; GFX90A-NEXT:   $vgpr48 = V_ACCVGPR_READ_B32_e64 killed $agpr72, implicit $exec
  ; GFX90A-NEXT:   $vgpr49 = V_ACCVGPR_READ_B32_e64 killed $agpr73, implicit $exec
  ; GFX90A-NEXT:   $vgpr50 = V_ACCVGPR_READ_B32_e64 killed $agpr74, implicit $exec
  ; GFX90A-NEXT:   $vgpr51 = V_ACCVGPR_READ_B32_e64 killed $agpr75, implicit $exec
  ; GFX90A-NEXT:   $vgpr52 = V_ACCVGPR_READ_B32_e64 killed $agpr76, implicit $exec
  ; GFX90A-NEXT:   $vgpr53 = V_ACCVGPR_READ_B32_e64 killed $agpr77, implicit $exec
  ; GFX90A-NEXT:   $vgpr54 = V_ACCVGPR_READ_B32_e64 killed $agpr78, implicit $exec
  ; GFX90A-NEXT:   $vgpr55 = V_ACCVGPR_READ_B32_e64 killed $agpr79, implicit $exec
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr80, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 700, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.50, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr81, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 696, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.51, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr82, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 692, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.52, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr83, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 688, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.53, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr84, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 684, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.54, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr85, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 680, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.55, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr86, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 676, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.56, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr87, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 672, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.57, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr88, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 668, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.58, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr89, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 664, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.59, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr90, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 660, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.60, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr91, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 656, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.61, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr92, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 652, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.62, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr93, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 648, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.63, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr94, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 644, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.64, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr95, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 640, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.65, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr96, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 636, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.66, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr97, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 632, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.67, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr98, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 628, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.68, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr99, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 624, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.69, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr100, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 620, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.70, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr101, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 616, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.71, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr102, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 612, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.72, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr103, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 608, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.73, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr104, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 604, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.74, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr105, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 600, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.75, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr106, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 596, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.76, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr107, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 592, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.77, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr108, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 588, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.78, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr109, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 584, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.79, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr110, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 580, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.80, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr111, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 576, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.81, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr112, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 572, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.82, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr113, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 568, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.83, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr114, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 564, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.84, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr115, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 560, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.85, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr116, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 556, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.86, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr117, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 552, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.87, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr118, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 548, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.88, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr119, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 544, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.89, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr120, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 540, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.90, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr121, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 536, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.91, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr122, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 532, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.92, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr123, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 528, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.93, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr124, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 524, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.94, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr125, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 520, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.95, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr126, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 516, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.96, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr127, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 512, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.97, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr128, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 508, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.98, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr129, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 504, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.99, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr130, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 500, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.100, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr131, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 496, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.101, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr132, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 492, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.102, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr133, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 488, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.103, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr134, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 484, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.104, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr135, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 480, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.105, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr136, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 476, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.106, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr137, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 472, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.107, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr138, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 468, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.108, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr139, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 464, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.109, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr140, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 460, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.110, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr141, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 456, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.111, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr142, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 452, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.112, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr143, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 448, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.113, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr144, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 444, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.114, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr145, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 440, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.115, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr146, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 436, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.116, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr147, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 432, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.117, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr148, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 428, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.118, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr149, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 424, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.119, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr150, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 420, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.120, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr151, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 416, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.121, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr152, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 412, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.122, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr153, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 408, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.123, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr154, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 404, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.124, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr155, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 400, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.125, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr156, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 396, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.126, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr157, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 392, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.127, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr158, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 388, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.128, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr159, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 384, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.129, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr160, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 380, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.130, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr161, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 376, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.131, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr162, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 372, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.132, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr163, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 368, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.133, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr164, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 364, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.134, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr165, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 360, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.135, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr166, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 356, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.136, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr167, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 352, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.137, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr168, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 348, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.138, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr169, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 344, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.139, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr170, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 340, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.140, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr171, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 336, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.141, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr172, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 332, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.142, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr173, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 328, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.143, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr174, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 324, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.144, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr175, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 320, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.145, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr176, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 316, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.146, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr177, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 312, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.147, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr178, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 308, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.148, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr179, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 304, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.149, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr180, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 300, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.150, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr181, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 296, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.151, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr182, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 292, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.152, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr183, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 288, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.153, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr184, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 284, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.154, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr185, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 280, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.155, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr186, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 276, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.156, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr187, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 272, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.157, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr188, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 268, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.158, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr189, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 264, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.159, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr190, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 260, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.160, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr191, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 256, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.161, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr192, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 252, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.162, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr193, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 248, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.163, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr194, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 244, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.164, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr195, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 240, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.165, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr196, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 236, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.166, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr197, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 232, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.167, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr198, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 228, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.168, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr199, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 224, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.169, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr200, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 220, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.170, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr201, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 216, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.171, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr202, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 212, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.172, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr203, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 208, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.173, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr204, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 204, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.174, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr205, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 200, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.175, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr206, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 196, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.176, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr207, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 192, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.177, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr208, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 188, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.178, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr209, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 184, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.179, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr210, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 180, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.180, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr211, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 176, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.181, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr212, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 172, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.182, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr213, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 168, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.183, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr214, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 164, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.184, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr215, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 160, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.185, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr216, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 156, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.186, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr217, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 152, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.187, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr218, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 148, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.188, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr219, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 144, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.189, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr220, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 140, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.190, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr221, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 136, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.191, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr222, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 132, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.192, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr223, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 128, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.193, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr224, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 124, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.194, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr225, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 120, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.195, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr226, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 116, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.196, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr227, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 112, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.197, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr228, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 108, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.198, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr229, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 104, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.199, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr230, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 100, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.200, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr231, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 96, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.201, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr232, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 92, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.202, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr233, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 88, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.203, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr234, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 84, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.204, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr235, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 80, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.205, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr236, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 76, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.206, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr237, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 72, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.207, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr238, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 68, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.208, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr239, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 64, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.209, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr240, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 60, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.210, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr241, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 56, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.211, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr242, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 52, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.212, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr243, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 48, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.213, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr244, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 44, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.214, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr245, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 40, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.215, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr246, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 36, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.216, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr247, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 32, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.217, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr248, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 28, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.218, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr249, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 24, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.219, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr250, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 20, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.220, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr251, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 16, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.221, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr252, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 12, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.222, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr253, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 8, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.223, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr254, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 4, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.224, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr255, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.225, addrspace 5)
  ; GFX90A-NEXT:   S_CMP_EQ_U32 0, 0, implicit-def $scc
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $vgpr40, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 704, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.226, addrspace 5)
  ; GFX90A-NEXT:   $vgpr40 = V_MOV_B32_e32 8904, implicit $exec
  ; GFX90A-NEXT:   $agpr0 = BUFFER_LOAD_DWORD_OFFEN killed $vgpr40, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.1, addrspace 5)
  ; GFX90A-NEXT:   $vgpr40 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 704, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.226, addrspace 5)
  ; GFX90A-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT: bb.1:
  ; GFX90A-NEXT:   successors: %bb.2(0x80000000)
  ; GFX90A-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   S_NOP 0
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT: bb.2:
  ; GFX90A-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   $agpr255 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.225, addrspace 5)
  ; GFX90A-NEXT:   $agpr254 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 4, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.224, addrspace 5)
  ; GFX90A-NEXT:   $agpr253 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 8, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.223, addrspace 5)
  ; GFX90A-NEXT:   $agpr252 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 12, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.222, addrspace 5)
  ; GFX90A-NEXT:   $agpr251 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 16, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.221, addrspace 5)
  ; GFX90A-NEXT:   $agpr250 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 20, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.220, addrspace 5)
  ; GFX90A-NEXT:   $agpr249 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 24, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.219, addrspace 5)
  ; GFX90A-NEXT:   $agpr248 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 28, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.218, addrspace 5)
  ; GFX90A-NEXT:   $agpr247 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 32, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.217, addrspace 5)
  ; GFX90A-NEXT:   $agpr246 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 36, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.216, addrspace 5)
  ; GFX90A-NEXT:   $agpr245 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 40, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.215, addrspace 5)
  ; GFX90A-NEXT:   $agpr244 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 44, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.214, addrspace 5)
  ; GFX90A-NEXT:   $agpr243 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 48, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.213, addrspace 5)
  ; GFX90A-NEXT:   $agpr242 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 52, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.212, addrspace 5)
  ; GFX90A-NEXT:   $agpr241 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 56, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.211, addrspace 5)
  ; GFX90A-NEXT:   $agpr240 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 60, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.210, addrspace 5)
  ; GFX90A-NEXT:   $agpr239 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 64, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.209, addrspace 5)
  ; GFX90A-NEXT:   $agpr238 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 68, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.208, addrspace 5)
  ; GFX90A-NEXT:   $agpr237 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 72, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.207, addrspace 5)
  ; GFX90A-NEXT:   $agpr236 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 76, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.206, addrspace 5)
  ; GFX90A-NEXT:   $agpr235 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 80, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.205, addrspace 5)
  ; GFX90A-NEXT:   $agpr234 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 84, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.204, addrspace 5)
  ; GFX90A-NEXT:   $agpr233 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 88, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.203, addrspace 5)
  ; GFX90A-NEXT:   $agpr232 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 92, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.202, addrspace 5)
  ; GFX90A-NEXT:   $agpr231 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 96, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.201, addrspace 5)
  ; GFX90A-NEXT:   $agpr230 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 100, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.200, addrspace 5)
  ; GFX90A-NEXT:   $agpr229 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 104, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.199, addrspace 5)
  ; GFX90A-NEXT:   $agpr228 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 108, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.198, addrspace 5)
  ; GFX90A-NEXT:   $agpr227 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 112, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.197, addrspace 5)
  ; GFX90A-NEXT:   $agpr226 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 116, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.196, addrspace 5)
  ; GFX90A-NEXT:   $agpr225 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 120, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.195, addrspace 5)
  ; GFX90A-NEXT:   $agpr224 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 124, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.194, addrspace 5)
  ; GFX90A-NEXT:   $agpr223 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 128, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.193, addrspace 5)
  ; GFX90A-NEXT:   $agpr222 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 132, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.192, addrspace 5)
  ; GFX90A-NEXT:   $agpr221 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 136, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.191, addrspace 5)
  ; GFX90A-NEXT:   $agpr220 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 140, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.190, addrspace 5)
  ; GFX90A-NEXT:   $agpr219 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 144, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.189, addrspace 5)
  ; GFX90A-NEXT:   $agpr218 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 148, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.188, addrspace 5)
  ; GFX90A-NEXT:   $agpr217 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 152, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.187, addrspace 5)
  ; GFX90A-NEXT:   $agpr216 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 156, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.186, addrspace 5)
  ; GFX90A-NEXT:   $agpr215 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 160, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.185, addrspace 5)
  ; GFX90A-NEXT:   $agpr214 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 164, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.184, addrspace 5)
  ; GFX90A-NEXT:   $agpr213 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 168, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.183, addrspace 5)
  ; GFX90A-NEXT:   $agpr212 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 172, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.182, addrspace 5)
  ; GFX90A-NEXT:   $agpr211 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 176, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.181, addrspace 5)
  ; GFX90A-NEXT:   $agpr210 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 180, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.180, addrspace 5)
  ; GFX90A-NEXT:   $agpr209 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 184, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.179, addrspace 5)
  ; GFX90A-NEXT:   $agpr208 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 188, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.178, addrspace 5)
  ; GFX90A-NEXT:   $agpr207 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 192, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.177, addrspace 5)
  ; GFX90A-NEXT:   $agpr206 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 196, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.176, addrspace 5)
  ; GFX90A-NEXT:   $agpr205 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 200, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.175, addrspace 5)
  ; GFX90A-NEXT:   $agpr204 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 204, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.174, addrspace 5)
  ; GFX90A-NEXT:   $agpr203 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 208, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.173, addrspace 5)
  ; GFX90A-NEXT:   $agpr202 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 212, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.172, addrspace 5)
  ; GFX90A-NEXT:   $agpr201 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 216, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.171, addrspace 5)
  ; GFX90A-NEXT:   $agpr200 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 220, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.170, addrspace 5)
  ; GFX90A-NEXT:   $agpr199 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 224, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.169, addrspace 5)
  ; GFX90A-NEXT:   $agpr198 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 228, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.168, addrspace 5)
  ; GFX90A-NEXT:   $agpr197 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 232, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.167, addrspace 5)
  ; GFX90A-NEXT:   $agpr196 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 236, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.166, addrspace 5)
  ; GFX90A-NEXT:   $agpr195 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 240, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.165, addrspace 5)
  ; GFX90A-NEXT:   $agpr194 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 244, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.164, addrspace 5)
  ; GFX90A-NEXT:   $agpr193 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 248, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.163, addrspace 5)
  ; GFX90A-NEXT:   $agpr192 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 252, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.162, addrspace 5)
  ; GFX90A-NEXT:   $agpr191 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 256, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.161, addrspace 5)
  ; GFX90A-NEXT:   $agpr190 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 260, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.160, addrspace 5)
  ; GFX90A-NEXT:   $agpr189 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 264, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.159, addrspace 5)
  ; GFX90A-NEXT:   $agpr188 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 268, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.158, addrspace 5)
  ; GFX90A-NEXT:   $agpr187 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 272, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.157, addrspace 5)
  ; GFX90A-NEXT:   $agpr186 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 276, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.156, addrspace 5)
  ; GFX90A-NEXT:   $agpr185 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 280, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.155, addrspace 5)
  ; GFX90A-NEXT:   $agpr184 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 284, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.154, addrspace 5)
  ; GFX90A-NEXT:   $agpr183 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 288, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.153, addrspace 5)
  ; GFX90A-NEXT:   $agpr182 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 292, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.152, addrspace 5)
  ; GFX90A-NEXT:   $agpr181 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 296, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.151, addrspace 5)
  ; GFX90A-NEXT:   $agpr180 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 300, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.150, addrspace 5)
  ; GFX90A-NEXT:   $agpr179 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 304, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.149, addrspace 5)
  ; GFX90A-NEXT:   $agpr178 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 308, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.148, addrspace 5)
  ; GFX90A-NEXT:   $agpr177 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 312, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.147, addrspace 5)
  ; GFX90A-NEXT:   $agpr176 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 316, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.146, addrspace 5)
  ; GFX90A-NEXT:   $agpr175 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 320, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.145, addrspace 5)
  ; GFX90A-NEXT:   $agpr174 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 324, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.144, addrspace 5)
  ; GFX90A-NEXT:   $agpr173 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 328, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.143, addrspace 5)
  ; GFX90A-NEXT:   $agpr172 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 332, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.142, addrspace 5)
  ; GFX90A-NEXT:   $agpr171 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 336, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.141, addrspace 5)
  ; GFX90A-NEXT:   $agpr170 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 340, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.140, addrspace 5)
  ; GFX90A-NEXT:   $agpr169 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 344, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.139, addrspace 5)
  ; GFX90A-NEXT:   $agpr168 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 348, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.138, addrspace 5)
  ; GFX90A-NEXT:   $agpr167 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 352, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.137, addrspace 5)
  ; GFX90A-NEXT:   $agpr166 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 356, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.136, addrspace 5)
  ; GFX90A-NEXT:   $agpr165 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 360, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.135, addrspace 5)
  ; GFX90A-NEXT:   $agpr164 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 364, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.134, addrspace 5)
  ; GFX90A-NEXT:   $agpr163 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 368, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.133, addrspace 5)
  ; GFX90A-NEXT:   $agpr162 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 372, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.132, addrspace 5)
  ; GFX90A-NEXT:   $agpr161 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 376, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.131, addrspace 5)
  ; GFX90A-NEXT:   $agpr160 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 380, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.130, addrspace 5)
  ; GFX90A-NEXT:   $agpr159 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 384, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.129, addrspace 5)
  ; GFX90A-NEXT:   $agpr158 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 388, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.128, addrspace 5)
  ; GFX90A-NEXT:   $agpr157 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 392, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.127, addrspace 5)
  ; GFX90A-NEXT:   $agpr156 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 396, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.126, addrspace 5)
  ; GFX90A-NEXT:   $agpr155 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 400, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.125, addrspace 5)
  ; GFX90A-NEXT:   $agpr154 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 404, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.124, addrspace 5)
  ; GFX90A-NEXT:   $agpr153 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 408, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.123, addrspace 5)
  ; GFX90A-NEXT:   $agpr152 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 412, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.122, addrspace 5)
  ; GFX90A-NEXT:   $agpr151 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 416, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.121, addrspace 5)
  ; GFX90A-NEXT:   $agpr150 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 420, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.120, addrspace 5)
  ; GFX90A-NEXT:   $agpr149 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 424, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.119, addrspace 5)
  ; GFX90A-NEXT:   $agpr148 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 428, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.118, addrspace 5)
  ; GFX90A-NEXT:   $agpr147 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 432, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.117, addrspace 5)
  ; GFX90A-NEXT:   $agpr146 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 436, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.116, addrspace 5)
  ; GFX90A-NEXT:   $agpr145 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 440, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.115, addrspace 5)
  ; GFX90A-NEXT:   $agpr144 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 444, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.114, addrspace 5)
  ; GFX90A-NEXT:   $agpr143 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 448, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.113, addrspace 5)
  ; GFX90A-NEXT:   $agpr142 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 452, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.112, addrspace 5)
  ; GFX90A-NEXT:   $agpr141 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 456, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.111, addrspace 5)
  ; GFX90A-NEXT:   $agpr140 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 460, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.110, addrspace 5)
  ; GFX90A-NEXT:   $agpr139 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 464, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.109, addrspace 5)
  ; GFX90A-NEXT:   $agpr138 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 468, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.108, addrspace 5)
  ; GFX90A-NEXT:   $agpr137 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 472, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.107, addrspace 5)
  ; GFX90A-NEXT:   $agpr136 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 476, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.106, addrspace 5)
  ; GFX90A-NEXT:   $agpr135 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 480, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.105, addrspace 5)
  ; GFX90A-NEXT:   $agpr134 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 484, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.104, addrspace 5)
  ; GFX90A-NEXT:   $agpr133 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 488, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.103, addrspace 5)
  ; GFX90A-NEXT:   $agpr132 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 492, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.102, addrspace 5)
  ; GFX90A-NEXT:   $agpr131 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 496, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.101, addrspace 5)
  ; GFX90A-NEXT:   $agpr130 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 500, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.100, addrspace 5)
  ; GFX90A-NEXT:   $agpr129 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 504, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.99, addrspace 5)
  ; GFX90A-NEXT:   $agpr128 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 508, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.98, addrspace 5)
  ; GFX90A-NEXT:   $agpr127 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 512, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.97, addrspace 5)
  ; GFX90A-NEXT:   $agpr126 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 516, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.96, addrspace 5)
  ; GFX90A-NEXT:   $agpr125 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 520, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.95, addrspace 5)
  ; GFX90A-NEXT:   $agpr124 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 524, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.94, addrspace 5)
  ; GFX90A-NEXT:   $agpr123 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 528, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.93, addrspace 5)
  ; GFX90A-NEXT:   $agpr122 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 532, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.92, addrspace 5)
  ; GFX90A-NEXT:   $agpr121 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 536, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.91, addrspace 5)
  ; GFX90A-NEXT:   $agpr120 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 540, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.90, addrspace 5)
  ; GFX90A-NEXT:   $agpr119 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 544, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.89, addrspace 5)
  ; GFX90A-NEXT:   $agpr118 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 548, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.88, addrspace 5)
  ; GFX90A-NEXT:   $agpr117 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 552, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.87, addrspace 5)
  ; GFX90A-NEXT:   $agpr116 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 556, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.86, addrspace 5)
  ; GFX90A-NEXT:   $agpr115 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 560, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.85, addrspace 5)
  ; GFX90A-NEXT:   $agpr114 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 564, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.84, addrspace 5)
  ; GFX90A-NEXT:   $agpr113 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 568, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.83, addrspace 5)
  ; GFX90A-NEXT:   $agpr112 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 572, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.82, addrspace 5)
  ; GFX90A-NEXT:   $agpr111 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 576, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.81, addrspace 5)
  ; GFX90A-NEXT:   $agpr110 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 580, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.80, addrspace 5)
  ; GFX90A-NEXT:   $agpr109 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 584, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.79, addrspace 5)
  ; GFX90A-NEXT:   $agpr108 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 588, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.78, addrspace 5)
  ; GFX90A-NEXT:   $agpr107 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 592, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.77, addrspace 5)
  ; GFX90A-NEXT:   $agpr106 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 596, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.76, addrspace 5)
  ; GFX90A-NEXT:   $agpr105 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 600, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.75, addrspace 5)
  ; GFX90A-NEXT:   $agpr104 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 604, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.74, addrspace 5)
  ; GFX90A-NEXT:   $agpr103 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 608, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.73, addrspace 5)
  ; GFX90A-NEXT:   $agpr102 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 612, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.72, addrspace 5)
  ; GFX90A-NEXT:   $agpr101 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 616, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.71, addrspace 5)
  ; GFX90A-NEXT:   $agpr100 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 620, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.70, addrspace 5)
  ; GFX90A-NEXT:   $agpr99 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 624, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.69, addrspace 5)
  ; GFX90A-NEXT:   $agpr98 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 628, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.68, addrspace 5)
  ; GFX90A-NEXT:   $agpr97 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 632, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.67, addrspace 5)
  ; GFX90A-NEXT:   $agpr96 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 636, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.66, addrspace 5)
  ; GFX90A-NEXT:   $agpr95 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 640, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.65, addrspace 5)
  ; GFX90A-NEXT:   $agpr94 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 644, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.64, addrspace 5)
  ; GFX90A-NEXT:   $agpr93 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 648, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.63, addrspace 5)
  ; GFX90A-NEXT:   $agpr92 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 652, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.62, addrspace 5)
  ; GFX90A-NEXT:   $agpr91 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 656, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.61, addrspace 5)
  ; GFX90A-NEXT:   $agpr90 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 660, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.60, addrspace 5)
  ; GFX90A-NEXT:   $agpr89 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 664, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.59, addrspace 5)
  ; GFX90A-NEXT:   $agpr88 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 668, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.58, addrspace 5)
  ; GFX90A-NEXT:   $agpr87 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 672, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.57, addrspace 5)
  ; GFX90A-NEXT:   $agpr86 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 676, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.56, addrspace 5)
  ; GFX90A-NEXT:   $agpr85 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 680, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.55, addrspace 5)
  ; GFX90A-NEXT:   $agpr84 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 684, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.54, addrspace 5)
  ; GFX90A-NEXT:   $agpr83 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 688, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.53, addrspace 5)
  ; GFX90A-NEXT:   $agpr82 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 692, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.52, addrspace 5)
  ; GFX90A-NEXT:   $agpr81 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 696, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.51, addrspace 5)
  ; GFX90A-NEXT:   $agpr80 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 700, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.50, addrspace 5)
  ; GFX90A-NEXT:   $agpr79 = V_ACCVGPR_WRITE_B32_e64 $vgpr55, implicit $exec
  ; GFX90A-NEXT:   $agpr78 = V_ACCVGPR_WRITE_B32_e64 $vgpr54, implicit $exec
  ; GFX90A-NEXT:   $agpr77 = V_ACCVGPR_WRITE_B32_e64 $vgpr53, implicit $exec
  ; GFX90A-NEXT:   $agpr76 = V_ACCVGPR_WRITE_B32_e64 $vgpr52, implicit $exec
  ; GFX90A-NEXT:   $agpr75 = V_ACCVGPR_WRITE_B32_e64 $vgpr51, implicit $exec
  ; GFX90A-NEXT:   $agpr74 = V_ACCVGPR_WRITE_B32_e64 $vgpr50, implicit $exec
  ; GFX90A-NEXT:   $agpr73 = V_ACCVGPR_WRITE_B32_e64 $vgpr49, implicit $exec
  ; GFX90A-NEXT:   $agpr72 = V_ACCVGPR_WRITE_B32_e64 $vgpr48, implicit $exec
  ; GFX90A-NEXT:   $agpr71 = V_ACCVGPR_WRITE_B32_e64 $vgpr39, implicit $exec
  ; GFX90A-NEXT:   $agpr70 = V_ACCVGPR_WRITE_B32_e64 $vgpr38, implicit $exec
  ; GFX90A-NEXT:   $agpr69 = V_ACCVGPR_WRITE_B32_e64 $vgpr37, implicit $exec
  ; GFX90A-NEXT:   $agpr68 = V_ACCVGPR_WRITE_B32_e64 $vgpr36, implicit $exec
  ; GFX90A-NEXT:   $agpr67 = V_ACCVGPR_WRITE_B32_e64 $vgpr35, implicit $exec
  ; GFX90A-NEXT:   $agpr66 = V_ACCVGPR_WRITE_B32_e64 $vgpr34, implicit $exec
  ; GFX90A-NEXT:   $agpr65 = V_ACCVGPR_WRITE_B32_e64 $vgpr33, implicit $exec
  ; GFX90A-NEXT:   $agpr64 = V_ACCVGPR_WRITE_B32_e64 $vgpr32, implicit $exec
  ; GFX90A-NEXT:   $agpr63 = V_ACCVGPR_WRITE_B32_e64 $vgpr31, implicit $exec
  ; GFX90A-NEXT:   $agpr62 = V_ACCVGPR_WRITE_B32_e64 $vgpr30, implicit $exec
  ; GFX90A-NEXT:   $agpr61 = V_ACCVGPR_WRITE_B32_e64 $vgpr29, implicit $exec
  ; GFX90A-NEXT:   $agpr60 = V_ACCVGPR_WRITE_B32_e64 $vgpr28, implicit $exec
  ; GFX90A-NEXT:   $agpr59 = V_ACCVGPR_WRITE_B32_e64 $vgpr27, implicit $exec
  ; GFX90A-NEXT:   $agpr58 = V_ACCVGPR_WRITE_B32_e64 $vgpr26, implicit $exec
  ; GFX90A-NEXT:   $agpr57 = V_ACCVGPR_WRITE_B32_e64 $vgpr25, implicit $exec
  ; GFX90A-NEXT:   $agpr56 = V_ACCVGPR_WRITE_B32_e64 $vgpr24, implicit $exec
  ; GFX90A-NEXT:   $agpr55 = V_ACCVGPR_WRITE_B32_e64 $vgpr23, implicit $exec
  ; GFX90A-NEXT:   $agpr54 = V_ACCVGPR_WRITE_B32_e64 $vgpr22, implicit $exec
  ; GFX90A-NEXT:   $agpr53 = V_ACCVGPR_WRITE_B32_e64 $vgpr21, implicit $exec
  ; GFX90A-NEXT:   $agpr52 = V_ACCVGPR_WRITE_B32_e64 $vgpr20, implicit $exec
  ; GFX90A-NEXT:   $agpr51 = V_ACCVGPR_WRITE_B32_e64 $vgpr19, implicit $exec
  ; GFX90A-NEXT:   $agpr50 = V_ACCVGPR_WRITE_B32_e64 $vgpr18, implicit $exec
  ; GFX90A-NEXT:   $agpr49 = V_ACCVGPR_WRITE_B32_e64 $vgpr17, implicit $exec
  ; GFX90A-NEXT:   $agpr48 = V_ACCVGPR_WRITE_B32_e64 $vgpr16, implicit $exec
  ; GFX90A-NEXT:   $agpr47 = V_ACCVGPR_WRITE_B32_e64 $vgpr15, implicit $exec
  ; GFX90A-NEXT:   $agpr46 = V_ACCVGPR_WRITE_B32_e64 $vgpr14, implicit $exec
  ; GFX90A-NEXT:   $agpr45 = V_ACCVGPR_WRITE_B32_e64 $vgpr13, implicit $exec
  ; GFX90A-NEXT:   $agpr44 = V_ACCVGPR_WRITE_B32_e64 $vgpr12, implicit $exec
  ; GFX90A-NEXT:   $agpr43 = V_ACCVGPR_WRITE_B32_e64 $vgpr11, implicit $exec
  ; GFX90A-NEXT:   $agpr42 = V_ACCVGPR_WRITE_B32_e64 $vgpr10, implicit $exec
  ; GFX90A-NEXT:   $agpr41 = V_ACCVGPR_WRITE_B32_e64 $vgpr9, implicit $exec
  ; GFX90A-NEXT:   $agpr40 = V_ACCVGPR_WRITE_B32_e64 $vgpr8, implicit $exec
  ; GFX90A-NEXT:   $agpr39 = V_ACCVGPR_WRITE_B32_e64 $vgpr7, implicit $exec
  ; GFX90A-NEXT:   $agpr38 = V_ACCVGPR_WRITE_B32_e64 $vgpr6, implicit $exec
  ; GFX90A-NEXT:   $agpr37 = V_ACCVGPR_WRITE_B32_e64 $vgpr5, implicit $exec
  ; GFX90A-NEXT:   $agpr36 = V_ACCVGPR_WRITE_B32_e64 $vgpr4, implicit $exec
  ; GFX90A-NEXT:   $agpr35 = V_ACCVGPR_WRITE_B32_e64 $vgpr3, implicit $exec
  ; GFX90A-NEXT:   $agpr34 = V_ACCVGPR_WRITE_B32_e64 $vgpr2, implicit $exec
  ; GFX90A-NEXT:   $agpr33 = V_ACCVGPR_WRITE_B32_e64 $vgpr1, implicit $exec
  ; GFX90A-NEXT:   $agpr32 = V_ACCVGPR_WRITE_B32_e64 $vgpr0, implicit $exec
  ; GFX90A-NEXT:   S_ENDPGM 0, amdgpu_allvgprs
  ;
  ; GFX908-FLATSCR-LABEL: name: agpr32_restore_clobber_scc
  ; GFX908-FLATSCR: bb.0:
  ; GFX908-FLATSCR-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GFX908-FLATSCR-NEXT:   liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT:   S_CMP_EQ_U32 0, 0, implicit-def $scc
  ; GFX908-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $vgpr1, $sgpr32, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.2, addrspace 5)
  ; GFX908-FLATSCR-NEXT:   $vgpr1 = V_MOV_B32_e32 $sgpr32, implicit $exec
  ; GFX908-FLATSCR-NEXT:   $vgpr1 = V_ADD_U32_e32 8200, $vgpr1, implicit $exec
  ; GFX908-FLATSCR-NEXT:   $vgpr0 = SCRATCH_LOAD_DWORD $vgpr1, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.1, addrspace 5)
  ; GFX908-FLATSCR-NEXT:   $agpr0 = V_ACCVGPR_WRITE_B32_e64 killed $vgpr0, implicit $exec
  ; GFX908-FLATSCR-NEXT:   $vgpr1 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.2, addrspace 5)
  ; GFX908-FLATSCR-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT: bb.1:
  ; GFX908-FLATSCR-NEXT:   successors: %bb.2(0x80000000)
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT:   S_NOP 0
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT: bb.2:
  ; GFX908-FLATSCR-NEXT:   liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT:   S_ENDPGM 0, amdgpu_allvgprs
  ;
  ; GFX90A-FLATSCR-LABEL: name: agpr32_restore_clobber_scc
  ; GFX90A-FLATSCR: bb.0:
  ; GFX90A-FLATSCR-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GFX90A-FLATSCR-NEXT:   liveins: $agpr32, $agpr33, $agpr34, $agpr35, $agpr36, $agpr37, $agpr38, $agpr39, $agpr40, $agpr41, $agpr42, $agpr43, $agpr44, $agpr45, $agpr46, $agpr47, $agpr48, $agpr49, $agpr50, $agpr51, $agpr52, $agpr53, $agpr54, $agpr55, $agpr56, $agpr57, $agpr58, $agpr59, $agpr60, $agpr61, $agpr62, $agpr63, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT:   $vgpr0 = V_ACCVGPR_READ_B32_e64 killed $agpr32, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr1 = V_ACCVGPR_READ_B32_e64 killed $agpr33, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr2 = V_ACCVGPR_READ_B32_e64 killed $agpr34, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr3 = V_ACCVGPR_READ_B32_e64 killed $agpr35, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr4 = V_ACCVGPR_READ_B32_e64 killed $agpr36, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr5 = V_ACCVGPR_READ_B32_e64 killed $agpr37, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr6 = V_ACCVGPR_READ_B32_e64 killed $agpr38, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr7 = V_ACCVGPR_READ_B32_e64 killed $agpr39, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr8 = V_ACCVGPR_READ_B32_e64 killed $agpr40, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr9 = V_ACCVGPR_READ_B32_e64 killed $agpr41, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr10 = V_ACCVGPR_READ_B32_e64 killed $agpr42, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr11 = V_ACCVGPR_READ_B32_e64 killed $agpr43, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr12 = V_ACCVGPR_READ_B32_e64 killed $agpr44, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr13 = V_ACCVGPR_READ_B32_e64 killed $agpr45, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr14 = V_ACCVGPR_READ_B32_e64 killed $agpr46, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr15 = V_ACCVGPR_READ_B32_e64 killed $agpr47, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr16 = V_ACCVGPR_READ_B32_e64 killed $agpr48, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr17 = V_ACCVGPR_READ_B32_e64 killed $agpr49, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr18 = V_ACCVGPR_READ_B32_e64 killed $agpr50, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr19 = V_ACCVGPR_READ_B32_e64 killed $agpr51, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr20 = V_ACCVGPR_READ_B32_e64 killed $agpr52, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr21 = V_ACCVGPR_READ_B32_e64 killed $agpr53, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr22 = V_ACCVGPR_READ_B32_e64 killed $agpr54, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr23 = V_ACCVGPR_READ_B32_e64 killed $agpr55, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr24 = V_ACCVGPR_READ_B32_e64 killed $agpr56, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr25 = V_ACCVGPR_READ_B32_e64 killed $agpr57, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr26 = V_ACCVGPR_READ_B32_e64 killed $agpr58, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr27 = V_ACCVGPR_READ_B32_e64 killed $agpr59, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr28 = V_ACCVGPR_READ_B32_e64 killed $agpr60, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr29 = V_ACCVGPR_READ_B32_e64 killed $agpr61, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr30 = V_ACCVGPR_READ_B32_e64 killed $agpr62, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr31 = V_ACCVGPR_READ_B32_e64 killed $agpr63, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr32 = V_ACCVGPR_READ_B32_e64 killed $agpr64, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr33 = V_ACCVGPR_READ_B32_e64 killed $agpr65, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr34 = V_ACCVGPR_READ_B32_e64 killed $agpr66, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr35 = V_ACCVGPR_READ_B32_e64 killed $agpr67, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr36 = V_ACCVGPR_READ_B32_e64 killed $agpr68, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr37 = V_ACCVGPR_READ_B32_e64 killed $agpr69, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr38 = V_ACCVGPR_READ_B32_e64 killed $agpr70, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr39 = V_ACCVGPR_READ_B32_e64 killed $agpr71, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr48 = V_ACCVGPR_READ_B32_e64 killed $agpr72, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr49 = V_ACCVGPR_READ_B32_e64 killed $agpr73, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr50 = V_ACCVGPR_READ_B32_e64 killed $agpr74, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr51 = V_ACCVGPR_READ_B32_e64 killed $agpr75, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr52 = V_ACCVGPR_READ_B32_e64 killed $agpr76, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr53 = V_ACCVGPR_READ_B32_e64 killed $agpr77, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr54 = V_ACCVGPR_READ_B32_e64 killed $agpr78, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr55 = V_ACCVGPR_READ_B32_e64 killed $agpr79, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr80, $sgpr32, 700, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.50, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr81, $sgpr32, 696, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.51, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr82, $sgpr32, 692, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.52, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr83, $sgpr32, 688, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.53, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr84, $sgpr32, 684, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.54, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr85, $sgpr32, 680, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.55, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr86, $sgpr32, 676, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.56, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr87, $sgpr32, 672, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.57, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr88, $sgpr32, 668, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.58, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr89, $sgpr32, 664, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.59, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr90, $sgpr32, 660, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.60, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr91, $sgpr32, 656, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.61, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr92, $sgpr32, 652, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.62, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr93, $sgpr32, 648, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.63, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr94, $sgpr32, 644, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.64, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr95, $sgpr32, 640, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.65, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr96, $sgpr32, 636, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.66, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr97, $sgpr32, 632, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.67, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr98, $sgpr32, 628, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.68, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr99, $sgpr32, 624, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.69, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr100, $sgpr32, 620, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.70, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr101, $sgpr32, 616, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.71, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr102, $sgpr32, 612, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.72, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr103, $sgpr32, 608, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.73, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr104, $sgpr32, 604, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.74, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr105, $sgpr32, 600, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.75, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr106, $sgpr32, 596, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.76, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr107, $sgpr32, 592, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.77, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr108, $sgpr32, 588, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.78, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr109, $sgpr32, 584, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.79, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr110, $sgpr32, 580, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.80, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr111, $sgpr32, 576, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.81, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr112, $sgpr32, 572, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.82, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr113, $sgpr32, 568, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.83, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr114, $sgpr32, 564, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.84, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr115, $sgpr32, 560, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.85, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr116, $sgpr32, 556, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.86, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr117, $sgpr32, 552, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.87, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr118, $sgpr32, 548, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.88, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr119, $sgpr32, 544, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.89, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr120, $sgpr32, 540, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.90, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr121, $sgpr32, 536, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.91, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr122, $sgpr32, 532, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.92, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr123, $sgpr32, 528, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.93, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr124, $sgpr32, 524, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.94, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr125, $sgpr32, 520, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.95, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr126, $sgpr32, 516, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.96, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr127, $sgpr32, 512, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.97, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr128, $sgpr32, 508, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.98, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr129, $sgpr32, 504, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.99, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr130, $sgpr32, 500, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.100, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr131, $sgpr32, 496, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.101, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr132, $sgpr32, 492, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.102, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr133, $sgpr32, 488, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.103, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr134, $sgpr32, 484, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.104, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr135, $sgpr32, 480, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.105, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr136, $sgpr32, 476, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.106, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr137, $sgpr32, 472, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.107, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr138, $sgpr32, 468, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.108, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr139, $sgpr32, 464, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.109, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr140, $sgpr32, 460, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.110, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr141, $sgpr32, 456, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.111, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr142, $sgpr32, 452, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.112, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr143, $sgpr32, 448, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.113, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr144, $sgpr32, 444, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.114, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr145, $sgpr32, 440, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.115, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr146, $sgpr32, 436, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.116, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr147, $sgpr32, 432, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.117, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr148, $sgpr32, 428, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.118, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr149, $sgpr32, 424, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.119, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr150, $sgpr32, 420, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.120, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr151, $sgpr32, 416, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.121, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr152, $sgpr32, 412, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.122, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr153, $sgpr32, 408, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.123, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr154, $sgpr32, 404, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.124, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr155, $sgpr32, 400, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.125, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr156, $sgpr32, 396, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.126, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr157, $sgpr32, 392, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.127, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr158, $sgpr32, 388, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.128, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr159, $sgpr32, 384, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.129, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr160, $sgpr32, 380, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.130, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr161, $sgpr32, 376, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.131, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr162, $sgpr32, 372, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.132, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr163, $sgpr32, 368, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.133, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr164, $sgpr32, 364, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.134, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr165, $sgpr32, 360, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.135, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr166, $sgpr32, 356, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.136, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr167, $sgpr32, 352, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.137, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr168, $sgpr32, 348, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.138, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr169, $sgpr32, 344, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.139, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr170, $sgpr32, 340, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.140, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr171, $sgpr32, 336, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.141, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr172, $sgpr32, 332, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.142, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr173, $sgpr32, 328, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.143, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr174, $sgpr32, 324, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.144, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr175, $sgpr32, 320, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.145, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr176, $sgpr32, 316, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.146, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr177, $sgpr32, 312, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.147, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr178, $sgpr32, 308, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.148, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr179, $sgpr32, 304, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.149, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr180, $sgpr32, 300, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.150, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr181, $sgpr32, 296, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.151, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr182, $sgpr32, 292, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.152, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr183, $sgpr32, 288, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.153, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr184, $sgpr32, 284, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.154, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr185, $sgpr32, 280, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.155, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr186, $sgpr32, 276, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.156, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr187, $sgpr32, 272, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.157, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr188, $sgpr32, 268, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.158, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr189, $sgpr32, 264, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.159, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr190, $sgpr32, 260, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.160, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr191, $sgpr32, 256, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.161, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr192, $sgpr32, 252, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.162, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr193, $sgpr32, 248, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.163, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr194, $sgpr32, 244, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.164, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr195, $sgpr32, 240, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.165, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr196, $sgpr32, 236, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.166, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr197, $sgpr32, 232, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.167, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr198, $sgpr32, 228, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.168, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr199, $sgpr32, 224, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.169, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr200, $sgpr32, 220, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.170, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr201, $sgpr32, 216, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.171, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr202, $sgpr32, 212, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.172, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr203, $sgpr32, 208, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.173, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr204, $sgpr32, 204, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.174, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr205, $sgpr32, 200, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.175, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr206, $sgpr32, 196, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.176, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr207, $sgpr32, 192, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.177, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr208, $sgpr32, 188, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.178, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr209, $sgpr32, 184, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.179, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr210, $sgpr32, 180, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.180, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr211, $sgpr32, 176, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.181, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr212, $sgpr32, 172, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.182, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr213, $sgpr32, 168, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.183, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr214, $sgpr32, 164, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.184, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr215, $sgpr32, 160, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.185, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr216, $sgpr32, 156, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.186, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr217, $sgpr32, 152, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.187, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr218, $sgpr32, 148, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.188, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr219, $sgpr32, 144, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.189, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr220, $sgpr32, 140, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.190, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr221, $sgpr32, 136, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.191, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr222, $sgpr32, 132, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.192, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr223, $sgpr32, 128, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.193, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr224, $sgpr32, 124, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.194, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr225, $sgpr32, 120, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.195, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr226, $sgpr32, 116, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.196, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr227, $sgpr32, 112, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.197, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr228, $sgpr32, 108, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.198, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr229, $sgpr32, 104, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.199, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr230, $sgpr32, 100, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.200, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr231, $sgpr32, 96, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.201, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr232, $sgpr32, 92, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.202, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr233, $sgpr32, 88, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.203, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr234, $sgpr32, 84, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.204, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr235, $sgpr32, 80, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.205, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr236, $sgpr32, 76, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.206, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr237, $sgpr32, 72, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.207, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr238, $sgpr32, 68, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.208, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr239, $sgpr32, 64, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.209, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr240, $sgpr32, 60, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.210, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr241, $sgpr32, 56, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.211, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr242, $sgpr32, 52, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.212, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr243, $sgpr32, 48, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.213, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr244, $sgpr32, 44, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.214, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr245, $sgpr32, 40, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.215, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr246, $sgpr32, 36, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.216, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr247, $sgpr32, 32, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.217, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr248, $sgpr32, 28, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.218, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr249, $sgpr32, 24, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.219, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr250, $sgpr32, 20, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.220, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr251, $sgpr32, 16, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.221, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr252, $sgpr32, 12, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.222, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr253, $sgpr32, 8, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.223, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr254, $sgpr32, 4, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.224, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr255, $sgpr32, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.225, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   S_CMP_EQ_U32 0, 0, implicit-def $scc
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $vgpr40, $sgpr32, 704, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.226, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $vgpr40 = V_MOV_B32_e32 $sgpr32, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr40 = V_ADD_U32_e32 8904, $vgpr40, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr0 = SCRATCH_LOAD_DWORD killed $vgpr40, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.1, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $vgpr40 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 704, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.226, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT: bb.1:
  ; GFX90A-FLATSCR-NEXT:   successors: %bb.2(0x80000000)
  ; GFX90A-FLATSCR-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT:   S_NOP 0
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT: bb.2:
  ; GFX90A-FLATSCR-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT:   $agpr255 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.225, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr254 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 4, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.224, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr253 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 8, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.223, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr252 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 12, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.222, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr251 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 16, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.221, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr250 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 20, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.220, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr249 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 24, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.219, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr248 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 28, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.218, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr247 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 32, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.217, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr246 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 36, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.216, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr245 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 40, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.215, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr244 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 44, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.214, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr243 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 48, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.213, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr242 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 52, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.212, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr241 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 56, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.211, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr240 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 60, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.210, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr239 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 64, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.209, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr238 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 68, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.208, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr237 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 72, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.207, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr236 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 76, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.206, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr235 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 80, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.205, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr234 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 84, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.204, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr233 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 88, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.203, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr232 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 92, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.202, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr231 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 96, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.201, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr230 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 100, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.200, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr229 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 104, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.199, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr228 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 108, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.198, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr227 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 112, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.197, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr226 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 116, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.196, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr225 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 120, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.195, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr224 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 124, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.194, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr223 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 128, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.193, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr222 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 132, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.192, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr221 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 136, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.191, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr220 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 140, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.190, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr219 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 144, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.189, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr218 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 148, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.188, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr217 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 152, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.187, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr216 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 156, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.186, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr215 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 160, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.185, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr214 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 164, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.184, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr213 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 168, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.183, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr212 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 172, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.182, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr211 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 176, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.181, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr210 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 180, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.180, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr209 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 184, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.179, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr208 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 188, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.178, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr207 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 192, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.177, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr206 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 196, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.176, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr205 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 200, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.175, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr204 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 204, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.174, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr203 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 208, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.173, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr202 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 212, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.172, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr201 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 216, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.171, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr200 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 220, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.170, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr199 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 224, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.169, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr198 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 228, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.168, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr197 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 232, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.167, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr196 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 236, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.166, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr195 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 240, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.165, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr194 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 244, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.164, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr193 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 248, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.163, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr192 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 252, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.162, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr191 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 256, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.161, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr190 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 260, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.160, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr189 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 264, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.159, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr188 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 268, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.158, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr187 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 272, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.157, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr186 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 276, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.156, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr185 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 280, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.155, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr184 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 284, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.154, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr183 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 288, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.153, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr182 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 292, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.152, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr181 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 296, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.151, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr180 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 300, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.150, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr179 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 304, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.149, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr178 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 308, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.148, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr177 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 312, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.147, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr176 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 316, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.146, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr175 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 320, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.145, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr174 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 324, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.144, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr173 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 328, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.143, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr172 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 332, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.142, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr171 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 336, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.141, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr170 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 340, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.140, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr169 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 344, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.139, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr168 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 348, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.138, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr167 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 352, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.137, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr166 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 356, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.136, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr165 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 360, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.135, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr164 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 364, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.134, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr163 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 368, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.133, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr162 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 372, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.132, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr161 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 376, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.131, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr160 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 380, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.130, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr159 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 384, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.129, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr158 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 388, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.128, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr157 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 392, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.127, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr156 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 396, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.126, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr155 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 400, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.125, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr154 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 404, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.124, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr153 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 408, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.123, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr152 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 412, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.122, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr151 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 416, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.121, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr150 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 420, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.120, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr149 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 424, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.119, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr148 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 428, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.118, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr147 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 432, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.117, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr146 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 436, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.116, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr145 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 440, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.115, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr144 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 444, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.114, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr143 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 448, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.113, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr142 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 452, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.112, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr141 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 456, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.111, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr140 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 460, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.110, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr139 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 464, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.109, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr138 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 468, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.108, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr137 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 472, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.107, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr136 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 476, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.106, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr135 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 480, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.105, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr134 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 484, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.104, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr133 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 488, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.103, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr132 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 492, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.102, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr131 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 496, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.101, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr130 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 500, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.100, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr129 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 504, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.99, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr128 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 508, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.98, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr127 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 512, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.97, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr126 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 516, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.96, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr125 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 520, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.95, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr124 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 524, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.94, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr123 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 528, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.93, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr122 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 532, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.92, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr121 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 536, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.91, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr120 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 540, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.90, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr119 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 544, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.89, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr118 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 548, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.88, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr117 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 552, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.87, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr116 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 556, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.86, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr115 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 560, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.85, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr114 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 564, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.84, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr113 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 568, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.83, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr112 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 572, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.82, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr111 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 576, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.81, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr110 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 580, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.80, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr109 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 584, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.79, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr108 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 588, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.78, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr107 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 592, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.77, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr106 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 596, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.76, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr105 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 600, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.75, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr104 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 604, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.74, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr103 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 608, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.73, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr102 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 612, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.72, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr101 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 616, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.71, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr100 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 620, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.70, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr99 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 624, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.69, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr98 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 628, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.68, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr97 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 632, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.67, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr96 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 636, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.66, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr95 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 640, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.65, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr94 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 644, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.64, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr93 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 648, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.63, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr92 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 652, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.62, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr91 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 656, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.61, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr90 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 660, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.60, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr89 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 664, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.59, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr88 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 668, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.58, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr87 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 672, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.57, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr86 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 676, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.56, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr85 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 680, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.55, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr84 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 684, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.54, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr83 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 688, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.53, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr82 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 692, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.52, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr81 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 696, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.51, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr80 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 700, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.50, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr79 = V_ACCVGPR_WRITE_B32_e64 $vgpr55, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr78 = V_ACCVGPR_WRITE_B32_e64 $vgpr54, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr77 = V_ACCVGPR_WRITE_B32_e64 $vgpr53, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr76 = V_ACCVGPR_WRITE_B32_e64 $vgpr52, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr75 = V_ACCVGPR_WRITE_B32_e64 $vgpr51, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr74 = V_ACCVGPR_WRITE_B32_e64 $vgpr50, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr73 = V_ACCVGPR_WRITE_B32_e64 $vgpr49, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr72 = V_ACCVGPR_WRITE_B32_e64 $vgpr48, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr71 = V_ACCVGPR_WRITE_B32_e64 $vgpr39, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr70 = V_ACCVGPR_WRITE_B32_e64 $vgpr38, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr69 = V_ACCVGPR_WRITE_B32_e64 $vgpr37, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr68 = V_ACCVGPR_WRITE_B32_e64 $vgpr36, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr67 = V_ACCVGPR_WRITE_B32_e64 $vgpr35, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr66 = V_ACCVGPR_WRITE_B32_e64 $vgpr34, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr65 = V_ACCVGPR_WRITE_B32_e64 $vgpr33, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr64 = V_ACCVGPR_WRITE_B32_e64 $vgpr32, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr63 = V_ACCVGPR_WRITE_B32_e64 $vgpr31, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr62 = V_ACCVGPR_WRITE_B32_e64 $vgpr30, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr61 = V_ACCVGPR_WRITE_B32_e64 $vgpr29, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr60 = V_ACCVGPR_WRITE_B32_e64 $vgpr28, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr59 = V_ACCVGPR_WRITE_B32_e64 $vgpr27, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr58 = V_ACCVGPR_WRITE_B32_e64 $vgpr26, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr57 = V_ACCVGPR_WRITE_B32_e64 $vgpr25, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr56 = V_ACCVGPR_WRITE_B32_e64 $vgpr24, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr55 = V_ACCVGPR_WRITE_B32_e64 $vgpr23, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr54 = V_ACCVGPR_WRITE_B32_e64 $vgpr22, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr53 = V_ACCVGPR_WRITE_B32_e64 $vgpr21, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr52 = V_ACCVGPR_WRITE_B32_e64 $vgpr20, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr51 = V_ACCVGPR_WRITE_B32_e64 $vgpr19, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr50 = V_ACCVGPR_WRITE_B32_e64 $vgpr18, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr49 = V_ACCVGPR_WRITE_B32_e64 $vgpr17, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr48 = V_ACCVGPR_WRITE_B32_e64 $vgpr16, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr47 = V_ACCVGPR_WRITE_B32_e64 $vgpr15, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr46 = V_ACCVGPR_WRITE_B32_e64 $vgpr14, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr45 = V_ACCVGPR_WRITE_B32_e64 $vgpr13, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr44 = V_ACCVGPR_WRITE_B32_e64 $vgpr12, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr43 = V_ACCVGPR_WRITE_B32_e64 $vgpr11, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr42 = V_ACCVGPR_WRITE_B32_e64 $vgpr10, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr41 = V_ACCVGPR_WRITE_B32_e64 $vgpr9, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr40 = V_ACCVGPR_WRITE_B32_e64 $vgpr8, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr39 = V_ACCVGPR_WRITE_B32_e64 $vgpr7, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr38 = V_ACCVGPR_WRITE_B32_e64 $vgpr6, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr37 = V_ACCVGPR_WRITE_B32_e64 $vgpr5, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr36 = V_ACCVGPR_WRITE_B32_e64 $vgpr4, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr35 = V_ACCVGPR_WRITE_B32_e64 $vgpr3, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr34 = V_ACCVGPR_WRITE_B32_e64 $vgpr2, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr33 = V_ACCVGPR_WRITE_B32_e64 $vgpr1, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr32 = V_ACCVGPR_WRITE_B32_e64 $vgpr0, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   S_ENDPGM 0, amdgpu_allvgprs
  bb.0:
    liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255

    S_CMP_EQ_U32 0, 0, implicit-def $scc
    $agpr0 = SI_SPILL_A32_RESTORE %stack.1, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.1, align 4, addrspace 5)
    S_CBRANCH_SCC1 %bb.2, implicit $scc

  bb.1:
    S_NOP 0

  bb.2:
    liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255
    S_ENDPGM 0, amdgpu_allvgprs
...

---
name: agpr64_restore_clobber_scc
tracksRegLiveness: true
stack:
  - { id: 0, type: default, offset: 0, size: 8192, alignment: 8 }
  - { id: 1, type: spill-slot, offset: 0, size: 8192, alignment: 4 }

machineFunctionInfo:
  isEntryFunction: false
  scratchRSrcReg:  $sgpr0_sgpr1_sgpr2_sgpr3
  frameOffsetReg:  $sgpr33
  stackPtrOffsetReg:  $sgpr32

body:             |
  ; GFX908-LABEL: name: agpr64_restore_clobber_scc
  ; GFX908: bb.0:
  ; GFX908-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GFX908-NEXT:   liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT:   S_CMP_EQ_U32 0, 0, implicit-def $scc
  ; GFX908-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $vgpr1, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.2, addrspace 5)
  ; GFX908-NEXT:   $vgpr1 = V_MOV_B32_e32 8200, implicit $exec
  ; GFX908-NEXT:   $vgpr0 = BUFFER_LOAD_DWORD_OFFEN $vgpr1, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.1, addrspace 5)
  ; GFX908-NEXT:   $agpr0 = V_ACCVGPR_WRITE_B32_e64 killed $vgpr0, implicit $exec, implicit-def $agpr0_agpr1
  ; GFX908-NEXT:   $vgpr0 = BUFFER_LOAD_DWORD_OFFEN $vgpr1, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 4, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.1 + 4, addrspace 5)
  ; GFX908-NEXT:   $agpr1 = V_ACCVGPR_WRITE_B32_e64 killed $vgpr0, implicit $exec
  ; GFX908-NEXT:   $vgpr1 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.2, addrspace 5)
  ; GFX908-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT: bb.1:
  ; GFX908-NEXT:   successors: %bb.2(0x80000000)
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT:   S_NOP 0
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT: bb.2:
  ; GFX908-NEXT:   liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT:   S_ENDPGM 0, amdgpu_allvgprs
  ;
  ; GFX90A-LABEL: name: agpr64_restore_clobber_scc
  ; GFX90A: bb.0:
  ; GFX90A-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GFX90A-NEXT:   liveins: $agpr32, $agpr33, $agpr34, $agpr35, $agpr36, $agpr37, $agpr38, $agpr39, $agpr40, $agpr41, $agpr42, $agpr43, $agpr44, $agpr45, $agpr46, $agpr47, $agpr48, $agpr49, $agpr50, $agpr51, $agpr52, $agpr53, $agpr54, $agpr55, $agpr56, $agpr57, $agpr58, $agpr59, $agpr60, $agpr61, $agpr62, $agpr63, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   $vgpr0 = V_ACCVGPR_READ_B32_e64 killed $agpr32, implicit $exec
  ; GFX90A-NEXT:   $vgpr1 = V_ACCVGPR_READ_B32_e64 killed $agpr33, implicit $exec
  ; GFX90A-NEXT:   $vgpr2 = V_ACCVGPR_READ_B32_e64 killed $agpr34, implicit $exec
  ; GFX90A-NEXT:   $vgpr3 = V_ACCVGPR_READ_B32_e64 killed $agpr35, implicit $exec
  ; GFX90A-NEXT:   $vgpr4 = V_ACCVGPR_READ_B32_e64 killed $agpr36, implicit $exec
  ; GFX90A-NEXT:   $vgpr5 = V_ACCVGPR_READ_B32_e64 killed $agpr37, implicit $exec
  ; GFX90A-NEXT:   $vgpr6 = V_ACCVGPR_READ_B32_e64 killed $agpr38, implicit $exec
  ; GFX90A-NEXT:   $vgpr7 = V_ACCVGPR_READ_B32_e64 killed $agpr39, implicit $exec
  ; GFX90A-NEXT:   $vgpr8 = V_ACCVGPR_READ_B32_e64 killed $agpr40, implicit $exec
  ; GFX90A-NEXT:   $vgpr9 = V_ACCVGPR_READ_B32_e64 killed $agpr41, implicit $exec
  ; GFX90A-NEXT:   $vgpr10 = V_ACCVGPR_READ_B32_e64 killed $agpr42, implicit $exec
  ; GFX90A-NEXT:   $vgpr11 = V_ACCVGPR_READ_B32_e64 killed $agpr43, implicit $exec
  ; GFX90A-NEXT:   $vgpr12 = V_ACCVGPR_READ_B32_e64 killed $agpr44, implicit $exec
  ; GFX90A-NEXT:   $vgpr13 = V_ACCVGPR_READ_B32_e64 killed $agpr45, implicit $exec
  ; GFX90A-NEXT:   $vgpr14 = V_ACCVGPR_READ_B32_e64 killed $agpr46, implicit $exec
  ; GFX90A-NEXT:   $vgpr15 = V_ACCVGPR_READ_B32_e64 killed $agpr47, implicit $exec
  ; GFX90A-NEXT:   $vgpr16 = V_ACCVGPR_READ_B32_e64 killed $agpr48, implicit $exec
  ; GFX90A-NEXT:   $vgpr17 = V_ACCVGPR_READ_B32_e64 killed $agpr49, implicit $exec
  ; GFX90A-NEXT:   $vgpr18 = V_ACCVGPR_READ_B32_e64 killed $agpr50, implicit $exec
  ; GFX90A-NEXT:   $vgpr19 = V_ACCVGPR_READ_B32_e64 killed $agpr51, implicit $exec
  ; GFX90A-NEXT:   $vgpr20 = V_ACCVGPR_READ_B32_e64 killed $agpr52, implicit $exec
  ; GFX90A-NEXT:   $vgpr21 = V_ACCVGPR_READ_B32_e64 killed $agpr53, implicit $exec
  ; GFX90A-NEXT:   $vgpr22 = V_ACCVGPR_READ_B32_e64 killed $agpr54, implicit $exec
  ; GFX90A-NEXT:   $vgpr23 = V_ACCVGPR_READ_B32_e64 killed $agpr55, implicit $exec
  ; GFX90A-NEXT:   $vgpr24 = V_ACCVGPR_READ_B32_e64 killed $agpr56, implicit $exec
  ; GFX90A-NEXT:   $vgpr25 = V_ACCVGPR_READ_B32_e64 killed $agpr57, implicit $exec
  ; GFX90A-NEXT:   $vgpr26 = V_ACCVGPR_READ_B32_e64 killed $agpr58, implicit $exec
  ; GFX90A-NEXT:   $vgpr27 = V_ACCVGPR_READ_B32_e64 killed $agpr59, implicit $exec
  ; GFX90A-NEXT:   $vgpr28 = V_ACCVGPR_READ_B32_e64 killed $agpr60, implicit $exec
  ; GFX90A-NEXT:   $vgpr29 = V_ACCVGPR_READ_B32_e64 killed $agpr61, implicit $exec
  ; GFX90A-NEXT:   $vgpr30 = V_ACCVGPR_READ_B32_e64 killed $agpr62, implicit $exec
  ; GFX90A-NEXT:   $vgpr31 = V_ACCVGPR_READ_B32_e64 killed $agpr63, implicit $exec
  ; GFX90A-NEXT:   $vgpr32 = V_ACCVGPR_READ_B32_e64 killed $agpr64, implicit $exec
  ; GFX90A-NEXT:   $vgpr33 = V_ACCVGPR_READ_B32_e64 killed $agpr65, implicit $exec
  ; GFX90A-NEXT:   $vgpr34 = V_ACCVGPR_READ_B32_e64 killed $agpr66, implicit $exec
  ; GFX90A-NEXT:   $vgpr35 = V_ACCVGPR_READ_B32_e64 killed $agpr67, implicit $exec
  ; GFX90A-NEXT:   $vgpr36 = V_ACCVGPR_READ_B32_e64 killed $agpr68, implicit $exec
  ; GFX90A-NEXT:   $vgpr37 = V_ACCVGPR_READ_B32_e64 killed $agpr69, implicit $exec
  ; GFX90A-NEXT:   $vgpr38 = V_ACCVGPR_READ_B32_e64 killed $agpr70, implicit $exec
  ; GFX90A-NEXT:   $vgpr39 = V_ACCVGPR_READ_B32_e64 killed $agpr71, implicit $exec
  ; GFX90A-NEXT:   $vgpr48 = V_ACCVGPR_READ_B32_e64 killed $agpr72, implicit $exec
  ; GFX90A-NEXT:   $vgpr49 = V_ACCVGPR_READ_B32_e64 killed $agpr73, implicit $exec
  ; GFX90A-NEXT:   $vgpr50 = V_ACCVGPR_READ_B32_e64 killed $agpr74, implicit $exec
  ; GFX90A-NEXT:   $vgpr51 = V_ACCVGPR_READ_B32_e64 killed $agpr75, implicit $exec
  ; GFX90A-NEXT:   $vgpr52 = V_ACCVGPR_READ_B32_e64 killed $agpr76, implicit $exec
  ; GFX90A-NEXT:   $vgpr53 = V_ACCVGPR_READ_B32_e64 killed $agpr77, implicit $exec
  ; GFX90A-NEXT:   $vgpr54 = V_ACCVGPR_READ_B32_e64 killed $agpr78, implicit $exec
  ; GFX90A-NEXT:   $vgpr55 = V_ACCVGPR_READ_B32_e64 killed $agpr79, implicit $exec
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr80, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 700, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.50, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr81, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 696, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.51, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr82, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 692, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.52, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr83, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 688, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.53, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr84, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 684, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.54, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr85, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 680, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.55, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr86, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 676, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.56, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr87, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 672, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.57, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr88, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 668, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.58, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr89, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 664, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.59, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr90, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 660, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.60, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr91, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 656, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.61, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr92, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 652, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.62, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr93, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 648, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.63, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr94, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 644, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.64, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr95, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 640, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.65, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr96, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 636, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.66, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr97, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 632, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.67, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr98, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 628, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.68, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr99, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 624, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.69, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr100, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 620, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.70, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr101, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 616, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.71, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr102, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 612, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.72, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr103, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 608, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.73, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr104, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 604, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.74, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr105, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 600, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.75, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr106, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 596, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.76, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr107, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 592, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.77, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr108, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 588, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.78, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr109, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 584, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.79, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr110, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 580, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.80, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr111, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 576, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.81, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr112, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 572, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.82, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr113, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 568, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.83, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr114, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 564, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.84, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr115, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 560, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.85, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr116, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 556, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.86, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr117, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 552, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.87, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr118, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 548, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.88, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr119, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 544, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.89, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr120, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 540, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.90, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr121, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 536, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.91, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr122, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 532, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.92, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr123, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 528, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.93, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr124, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 524, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.94, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr125, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 520, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.95, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr126, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 516, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.96, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr127, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 512, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.97, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr128, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 508, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.98, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr129, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 504, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.99, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr130, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 500, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.100, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr131, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 496, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.101, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr132, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 492, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.102, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr133, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 488, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.103, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr134, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 484, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.104, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr135, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 480, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.105, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr136, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 476, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.106, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr137, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 472, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.107, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr138, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 468, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.108, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr139, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 464, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.109, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr140, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 460, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.110, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr141, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 456, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.111, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr142, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 452, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.112, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr143, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 448, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.113, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr144, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 444, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.114, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr145, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 440, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.115, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr146, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 436, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.116, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr147, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 432, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.117, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr148, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 428, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.118, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr149, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 424, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.119, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr150, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 420, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.120, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr151, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 416, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.121, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr152, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 412, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.122, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr153, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 408, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.123, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr154, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 404, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.124, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr155, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 400, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.125, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr156, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 396, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.126, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr157, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 392, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.127, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr158, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 388, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.128, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr159, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 384, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.129, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr160, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 380, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.130, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr161, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 376, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.131, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr162, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 372, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.132, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr163, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 368, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.133, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr164, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 364, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.134, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr165, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 360, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.135, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr166, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 356, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.136, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr167, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 352, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.137, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr168, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 348, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.138, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr169, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 344, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.139, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr170, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 340, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.140, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr171, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 336, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.141, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr172, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 332, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.142, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr173, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 328, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.143, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr174, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 324, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.144, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr175, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 320, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.145, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr176, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 316, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.146, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr177, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 312, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.147, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr178, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 308, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.148, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr179, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 304, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.149, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr180, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 300, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.150, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr181, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 296, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.151, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr182, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 292, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.152, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr183, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 288, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.153, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr184, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 284, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.154, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr185, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 280, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.155, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr186, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 276, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.156, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr187, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 272, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.157, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr188, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 268, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.158, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr189, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 264, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.159, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr190, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 260, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.160, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr191, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 256, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.161, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr192, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 252, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.162, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr193, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 248, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.163, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr194, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 244, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.164, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr195, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 240, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.165, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr196, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 236, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.166, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr197, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 232, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.167, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr198, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 228, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.168, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr199, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 224, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.169, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr200, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 220, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.170, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr201, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 216, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.171, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr202, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 212, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.172, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr203, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 208, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.173, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr204, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 204, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.174, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr205, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 200, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.175, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr206, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 196, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.176, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr207, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 192, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.177, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr208, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 188, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.178, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr209, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 184, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.179, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr210, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 180, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.180, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr211, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 176, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.181, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr212, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 172, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.182, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr213, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 168, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.183, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr214, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 164, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.184, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr215, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 160, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.185, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr216, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 156, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.186, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr217, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 152, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.187, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr218, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 148, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.188, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr219, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 144, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.189, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr220, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 140, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.190, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr221, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 136, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.191, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr222, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 132, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.192, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr223, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 128, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.193, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr224, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 124, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.194, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr225, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 120, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.195, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr226, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 116, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.196, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr227, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 112, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.197, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr228, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 108, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.198, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr229, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 104, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.199, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr230, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 100, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.200, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr231, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 96, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.201, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr232, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 92, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.202, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr233, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 88, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.203, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr234, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 84, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.204, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr235, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 80, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.205, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr236, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 76, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.206, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr237, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 72, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.207, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr238, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 68, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.208, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr239, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 64, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.209, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr240, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 60, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.210, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr241, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 56, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.211, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr242, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 52, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.212, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr243, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 48, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.213, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr244, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 44, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.214, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr245, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 40, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.215, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr246, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 36, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.216, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr247, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 32, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.217, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr248, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 28, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.218, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr249, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 24, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.219, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr250, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 20, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.220, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr251, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 16, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.221, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr252, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 12, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.222, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr253, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 8, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.223, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr254, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 4, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.224, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr255, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.225, addrspace 5)
  ; GFX90A-NEXT:   S_CMP_EQ_U32 0, 0, implicit-def $scc
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $vgpr40, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 704, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.226, addrspace 5)
  ; GFX90A-NEXT:   $vgpr40 = V_MOV_B32_e32 8904, implicit $exec
  ; GFX90A-NEXT:   $agpr0 = BUFFER_LOAD_DWORD_OFFEN $vgpr40, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec, implicit-def $agpr0_agpr1 :: ("amdgpu-non-volatile" load (s32) from %stack.1, addrspace 5)
  ; GFX90A-NEXT:   $agpr1 = BUFFER_LOAD_DWORD_OFFEN killed $vgpr40, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 4, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.1 + 4, addrspace 5)
  ; GFX90A-NEXT:   $vgpr40 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 704, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.226, addrspace 5)
  ; GFX90A-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT: bb.1:
  ; GFX90A-NEXT:   successors: %bb.2(0x80000000)
  ; GFX90A-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   S_NOP 0
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT: bb.2:
  ; GFX90A-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   $agpr255 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.225, addrspace 5)
  ; GFX90A-NEXT:   $agpr254 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 4, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.224, addrspace 5)
  ; GFX90A-NEXT:   $agpr253 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 8, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.223, addrspace 5)
  ; GFX90A-NEXT:   $agpr252 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 12, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.222, addrspace 5)
  ; GFX90A-NEXT:   $agpr251 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 16, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.221, addrspace 5)
  ; GFX90A-NEXT:   $agpr250 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 20, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.220, addrspace 5)
  ; GFX90A-NEXT:   $agpr249 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 24, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.219, addrspace 5)
  ; GFX90A-NEXT:   $agpr248 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 28, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.218, addrspace 5)
  ; GFX90A-NEXT:   $agpr247 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 32, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.217, addrspace 5)
  ; GFX90A-NEXT:   $agpr246 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 36, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.216, addrspace 5)
  ; GFX90A-NEXT:   $agpr245 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 40, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.215, addrspace 5)
  ; GFX90A-NEXT:   $agpr244 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 44, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.214, addrspace 5)
  ; GFX90A-NEXT:   $agpr243 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 48, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.213, addrspace 5)
  ; GFX90A-NEXT:   $agpr242 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 52, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.212, addrspace 5)
  ; GFX90A-NEXT:   $agpr241 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 56, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.211, addrspace 5)
  ; GFX90A-NEXT:   $agpr240 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 60, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.210, addrspace 5)
  ; GFX90A-NEXT:   $agpr239 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 64, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.209, addrspace 5)
  ; GFX90A-NEXT:   $agpr238 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 68, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.208, addrspace 5)
  ; GFX90A-NEXT:   $agpr237 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 72, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.207, addrspace 5)
  ; GFX90A-NEXT:   $agpr236 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 76, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.206, addrspace 5)
  ; GFX90A-NEXT:   $agpr235 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 80, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.205, addrspace 5)
  ; GFX90A-NEXT:   $agpr234 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 84, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.204, addrspace 5)
  ; GFX90A-NEXT:   $agpr233 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 88, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.203, addrspace 5)
  ; GFX90A-NEXT:   $agpr232 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 92, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.202, addrspace 5)
  ; GFX90A-NEXT:   $agpr231 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 96, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.201, addrspace 5)
  ; GFX90A-NEXT:   $agpr230 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 100, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.200, addrspace 5)
  ; GFX90A-NEXT:   $agpr229 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 104, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.199, addrspace 5)
  ; GFX90A-NEXT:   $agpr228 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 108, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.198, addrspace 5)
  ; GFX90A-NEXT:   $agpr227 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 112, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.197, addrspace 5)
  ; GFX90A-NEXT:   $agpr226 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 116, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.196, addrspace 5)
  ; GFX90A-NEXT:   $agpr225 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 120, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.195, addrspace 5)
  ; GFX90A-NEXT:   $agpr224 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 124, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.194, addrspace 5)
  ; GFX90A-NEXT:   $agpr223 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 128, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.193, addrspace 5)
  ; GFX90A-NEXT:   $agpr222 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 132, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.192, addrspace 5)
  ; GFX90A-NEXT:   $agpr221 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 136, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.191, addrspace 5)
  ; GFX90A-NEXT:   $agpr220 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 140, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.190, addrspace 5)
  ; GFX90A-NEXT:   $agpr219 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 144, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.189, addrspace 5)
  ; GFX90A-NEXT:   $agpr218 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 148, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.188, addrspace 5)
  ; GFX90A-NEXT:   $agpr217 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 152, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.187, addrspace 5)
  ; GFX90A-NEXT:   $agpr216 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 156, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.186, addrspace 5)
  ; GFX90A-NEXT:   $agpr215 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 160, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.185, addrspace 5)
  ; GFX90A-NEXT:   $agpr214 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 164, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.184, addrspace 5)
  ; GFX90A-NEXT:   $agpr213 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 168, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.183, addrspace 5)
  ; GFX90A-NEXT:   $agpr212 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 172, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.182, addrspace 5)
  ; GFX90A-NEXT:   $agpr211 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 176, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.181, addrspace 5)
  ; GFX90A-NEXT:   $agpr210 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 180, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.180, addrspace 5)
  ; GFX90A-NEXT:   $agpr209 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 184, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.179, addrspace 5)
  ; GFX90A-NEXT:   $agpr208 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 188, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.178, addrspace 5)
  ; GFX90A-NEXT:   $agpr207 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 192, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.177, addrspace 5)
  ; GFX90A-NEXT:   $agpr206 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 196, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.176, addrspace 5)
  ; GFX90A-NEXT:   $agpr205 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 200, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.175, addrspace 5)
  ; GFX90A-NEXT:   $agpr204 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 204, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.174, addrspace 5)
  ; GFX90A-NEXT:   $agpr203 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 208, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.173, addrspace 5)
  ; GFX90A-NEXT:   $agpr202 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 212, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.172, addrspace 5)
  ; GFX90A-NEXT:   $agpr201 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 216, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.171, addrspace 5)
  ; GFX90A-NEXT:   $agpr200 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 220, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.170, addrspace 5)
  ; GFX90A-NEXT:   $agpr199 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 224, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.169, addrspace 5)
  ; GFX90A-NEXT:   $agpr198 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 228, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.168, addrspace 5)
  ; GFX90A-NEXT:   $agpr197 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 232, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.167, addrspace 5)
  ; GFX90A-NEXT:   $agpr196 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 236, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.166, addrspace 5)
  ; GFX90A-NEXT:   $agpr195 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 240, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.165, addrspace 5)
  ; GFX90A-NEXT:   $agpr194 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 244, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.164, addrspace 5)
  ; GFX90A-NEXT:   $agpr193 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 248, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.163, addrspace 5)
  ; GFX90A-NEXT:   $agpr192 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 252, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.162, addrspace 5)
  ; GFX90A-NEXT:   $agpr191 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 256, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.161, addrspace 5)
  ; GFX90A-NEXT:   $agpr190 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 260, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.160, addrspace 5)
  ; GFX90A-NEXT:   $agpr189 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 264, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.159, addrspace 5)
  ; GFX90A-NEXT:   $agpr188 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 268, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.158, addrspace 5)
  ; GFX90A-NEXT:   $agpr187 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 272, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.157, addrspace 5)
  ; GFX90A-NEXT:   $agpr186 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 276, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.156, addrspace 5)
  ; GFX90A-NEXT:   $agpr185 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 280, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.155, addrspace 5)
  ; GFX90A-NEXT:   $agpr184 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 284, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.154, addrspace 5)
  ; GFX90A-NEXT:   $agpr183 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 288, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.153, addrspace 5)
  ; GFX90A-NEXT:   $agpr182 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 292, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.152, addrspace 5)
  ; GFX90A-NEXT:   $agpr181 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 296, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.151, addrspace 5)
  ; GFX90A-NEXT:   $agpr180 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 300, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.150, addrspace 5)
  ; GFX90A-NEXT:   $agpr179 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 304, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.149, addrspace 5)
  ; GFX90A-NEXT:   $agpr178 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 308, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.148, addrspace 5)
  ; GFX90A-NEXT:   $agpr177 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 312, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.147, addrspace 5)
  ; GFX90A-NEXT:   $agpr176 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 316, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.146, addrspace 5)
  ; GFX90A-NEXT:   $agpr175 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 320, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.145, addrspace 5)
  ; GFX90A-NEXT:   $agpr174 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 324, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.144, addrspace 5)
  ; GFX90A-NEXT:   $agpr173 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 328, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.143, addrspace 5)
  ; GFX90A-NEXT:   $agpr172 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 332, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.142, addrspace 5)
  ; GFX90A-NEXT:   $agpr171 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 336, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.141, addrspace 5)
  ; GFX90A-NEXT:   $agpr170 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 340, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.140, addrspace 5)
  ; GFX90A-NEXT:   $agpr169 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 344, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.139, addrspace 5)
  ; GFX90A-NEXT:   $agpr168 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 348, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.138, addrspace 5)
  ; GFX90A-NEXT:   $agpr167 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 352, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.137, addrspace 5)
  ; GFX90A-NEXT:   $agpr166 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 356, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.136, addrspace 5)
  ; GFX90A-NEXT:   $agpr165 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 360, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.135, addrspace 5)
  ; GFX90A-NEXT:   $agpr164 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 364, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.134, addrspace 5)
  ; GFX90A-NEXT:   $agpr163 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 368, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.133, addrspace 5)
  ; GFX90A-NEXT:   $agpr162 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 372, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.132, addrspace 5)
  ; GFX90A-NEXT:   $agpr161 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 376, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.131, addrspace 5)
  ; GFX90A-NEXT:   $agpr160 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 380, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.130, addrspace 5)
  ; GFX90A-NEXT:   $agpr159 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 384, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.129, addrspace 5)
  ; GFX90A-NEXT:   $agpr158 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 388, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.128, addrspace 5)
  ; GFX90A-NEXT:   $agpr157 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 392, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.127, addrspace 5)
  ; GFX90A-NEXT:   $agpr156 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 396, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.126, addrspace 5)
  ; GFX90A-NEXT:   $agpr155 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 400, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.125, addrspace 5)
  ; GFX90A-NEXT:   $agpr154 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 404, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.124, addrspace 5)
  ; GFX90A-NEXT:   $agpr153 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 408, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.123, addrspace 5)
  ; GFX90A-NEXT:   $agpr152 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 412, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.122, addrspace 5)
  ; GFX90A-NEXT:   $agpr151 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 416, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.121, addrspace 5)
  ; GFX90A-NEXT:   $agpr150 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 420, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.120, addrspace 5)
  ; GFX90A-NEXT:   $agpr149 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 424, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.119, addrspace 5)
  ; GFX90A-NEXT:   $agpr148 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 428, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.118, addrspace 5)
  ; GFX90A-NEXT:   $agpr147 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 432, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.117, addrspace 5)
  ; GFX90A-NEXT:   $agpr146 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 436, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.116, addrspace 5)
  ; GFX90A-NEXT:   $agpr145 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 440, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.115, addrspace 5)
  ; GFX90A-NEXT:   $agpr144 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 444, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.114, addrspace 5)
  ; GFX90A-NEXT:   $agpr143 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 448, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.113, addrspace 5)
  ; GFX90A-NEXT:   $agpr142 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 452, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.112, addrspace 5)
  ; GFX90A-NEXT:   $agpr141 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 456, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.111, addrspace 5)
  ; GFX90A-NEXT:   $agpr140 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 460, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.110, addrspace 5)
  ; GFX90A-NEXT:   $agpr139 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 464, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.109, addrspace 5)
  ; GFX90A-NEXT:   $agpr138 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 468, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.108, addrspace 5)
  ; GFX90A-NEXT:   $agpr137 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 472, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.107, addrspace 5)
  ; GFX90A-NEXT:   $agpr136 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 476, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.106, addrspace 5)
  ; GFX90A-NEXT:   $agpr135 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 480, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.105, addrspace 5)
  ; GFX90A-NEXT:   $agpr134 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 484, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.104, addrspace 5)
  ; GFX90A-NEXT:   $agpr133 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 488, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.103, addrspace 5)
  ; GFX90A-NEXT:   $agpr132 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 492, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.102, addrspace 5)
  ; GFX90A-NEXT:   $agpr131 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 496, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.101, addrspace 5)
  ; GFX90A-NEXT:   $agpr130 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 500, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.100, addrspace 5)
  ; GFX90A-NEXT:   $agpr129 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 504, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.99, addrspace 5)
  ; GFX90A-NEXT:   $agpr128 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 508, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.98, addrspace 5)
  ; GFX90A-NEXT:   $agpr127 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 512, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.97, addrspace 5)
  ; GFX90A-NEXT:   $agpr126 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 516, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.96, addrspace 5)
  ; GFX90A-NEXT:   $agpr125 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 520, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.95, addrspace 5)
  ; GFX90A-NEXT:   $agpr124 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 524, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.94, addrspace 5)
  ; GFX90A-NEXT:   $agpr123 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 528, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.93, addrspace 5)
  ; GFX90A-NEXT:   $agpr122 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 532, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.92, addrspace 5)
  ; GFX90A-NEXT:   $agpr121 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 536, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.91, addrspace 5)
  ; GFX90A-NEXT:   $agpr120 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 540, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.90, addrspace 5)
  ; GFX90A-NEXT:   $agpr119 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 544, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.89, addrspace 5)
  ; GFX90A-NEXT:   $agpr118 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 548, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.88, addrspace 5)
  ; GFX90A-NEXT:   $agpr117 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 552, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.87, addrspace 5)
  ; GFX90A-NEXT:   $agpr116 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 556, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.86, addrspace 5)
  ; GFX90A-NEXT:   $agpr115 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 560, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.85, addrspace 5)
  ; GFX90A-NEXT:   $agpr114 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 564, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.84, addrspace 5)
  ; GFX90A-NEXT:   $agpr113 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 568, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.83, addrspace 5)
  ; GFX90A-NEXT:   $agpr112 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 572, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.82, addrspace 5)
  ; GFX90A-NEXT:   $agpr111 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 576, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.81, addrspace 5)
  ; GFX90A-NEXT:   $agpr110 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 580, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.80, addrspace 5)
  ; GFX90A-NEXT:   $agpr109 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 584, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.79, addrspace 5)
  ; GFX90A-NEXT:   $agpr108 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 588, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.78, addrspace 5)
  ; GFX90A-NEXT:   $agpr107 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 592, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.77, addrspace 5)
  ; GFX90A-NEXT:   $agpr106 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 596, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.76, addrspace 5)
  ; GFX90A-NEXT:   $agpr105 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 600, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.75, addrspace 5)
  ; GFX90A-NEXT:   $agpr104 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 604, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.74, addrspace 5)
  ; GFX90A-NEXT:   $agpr103 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 608, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.73, addrspace 5)
  ; GFX90A-NEXT:   $agpr102 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 612, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.72, addrspace 5)
  ; GFX90A-NEXT:   $agpr101 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 616, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.71, addrspace 5)
  ; GFX90A-NEXT:   $agpr100 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 620, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.70, addrspace 5)
  ; GFX90A-NEXT:   $agpr99 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 624, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.69, addrspace 5)
  ; GFX90A-NEXT:   $agpr98 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 628, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.68, addrspace 5)
  ; GFX90A-NEXT:   $agpr97 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 632, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.67, addrspace 5)
  ; GFX90A-NEXT:   $agpr96 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 636, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.66, addrspace 5)
  ; GFX90A-NEXT:   $agpr95 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 640, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.65, addrspace 5)
  ; GFX90A-NEXT:   $agpr94 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 644, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.64, addrspace 5)
  ; GFX90A-NEXT:   $agpr93 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 648, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.63, addrspace 5)
  ; GFX90A-NEXT:   $agpr92 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 652, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.62, addrspace 5)
  ; GFX90A-NEXT:   $agpr91 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 656, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.61, addrspace 5)
  ; GFX90A-NEXT:   $agpr90 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 660, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.60, addrspace 5)
  ; GFX90A-NEXT:   $agpr89 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 664, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.59, addrspace 5)
  ; GFX90A-NEXT:   $agpr88 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 668, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.58, addrspace 5)
  ; GFX90A-NEXT:   $agpr87 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 672, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.57, addrspace 5)
  ; GFX90A-NEXT:   $agpr86 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 676, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.56, addrspace 5)
  ; GFX90A-NEXT:   $agpr85 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 680, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.55, addrspace 5)
  ; GFX90A-NEXT:   $agpr84 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 684, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.54, addrspace 5)
  ; GFX90A-NEXT:   $agpr83 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 688, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.53, addrspace 5)
  ; GFX90A-NEXT:   $agpr82 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 692, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.52, addrspace 5)
  ; GFX90A-NEXT:   $agpr81 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 696, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.51, addrspace 5)
  ; GFX90A-NEXT:   $agpr80 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 700, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.50, addrspace 5)
  ; GFX90A-NEXT:   $agpr79 = V_ACCVGPR_WRITE_B32_e64 $vgpr55, implicit $exec
  ; GFX90A-NEXT:   $agpr78 = V_ACCVGPR_WRITE_B32_e64 $vgpr54, implicit $exec
  ; GFX90A-NEXT:   $agpr77 = V_ACCVGPR_WRITE_B32_e64 $vgpr53, implicit $exec
  ; GFX90A-NEXT:   $agpr76 = V_ACCVGPR_WRITE_B32_e64 $vgpr52, implicit $exec
  ; GFX90A-NEXT:   $agpr75 = V_ACCVGPR_WRITE_B32_e64 $vgpr51, implicit $exec
  ; GFX90A-NEXT:   $agpr74 = V_ACCVGPR_WRITE_B32_e64 $vgpr50, implicit $exec
  ; GFX90A-NEXT:   $agpr73 = V_ACCVGPR_WRITE_B32_e64 $vgpr49, implicit $exec
  ; GFX90A-NEXT:   $agpr72 = V_ACCVGPR_WRITE_B32_e64 $vgpr48, implicit $exec
  ; GFX90A-NEXT:   $agpr71 = V_ACCVGPR_WRITE_B32_e64 $vgpr39, implicit $exec
  ; GFX90A-NEXT:   $agpr70 = V_ACCVGPR_WRITE_B32_e64 $vgpr38, implicit $exec
  ; GFX90A-NEXT:   $agpr69 = V_ACCVGPR_WRITE_B32_e64 $vgpr37, implicit $exec
  ; GFX90A-NEXT:   $agpr68 = V_ACCVGPR_WRITE_B32_e64 $vgpr36, implicit $exec
  ; GFX90A-NEXT:   $agpr67 = V_ACCVGPR_WRITE_B32_e64 $vgpr35, implicit $exec
  ; GFX90A-NEXT:   $agpr66 = V_ACCVGPR_WRITE_B32_e64 $vgpr34, implicit $exec
  ; GFX90A-NEXT:   $agpr65 = V_ACCVGPR_WRITE_B32_e64 $vgpr33, implicit $exec
  ; GFX90A-NEXT:   $agpr64 = V_ACCVGPR_WRITE_B32_e64 $vgpr32, implicit $exec
  ; GFX90A-NEXT:   $agpr63 = V_ACCVGPR_WRITE_B32_e64 $vgpr31, implicit $exec
  ; GFX90A-NEXT:   $agpr62 = V_ACCVGPR_WRITE_B32_e64 $vgpr30, implicit $exec
  ; GFX90A-NEXT:   $agpr61 = V_ACCVGPR_WRITE_B32_e64 $vgpr29, implicit $exec
  ; GFX90A-NEXT:   $agpr60 = V_ACCVGPR_WRITE_B32_e64 $vgpr28, implicit $exec
  ; GFX90A-NEXT:   $agpr59 = V_ACCVGPR_WRITE_B32_e64 $vgpr27, implicit $exec
  ; GFX90A-NEXT:   $agpr58 = V_ACCVGPR_WRITE_B32_e64 $vgpr26, implicit $exec
  ; GFX90A-NEXT:   $agpr57 = V_ACCVGPR_WRITE_B32_e64 $vgpr25, implicit $exec
  ; GFX90A-NEXT:   $agpr56 = V_ACCVGPR_WRITE_B32_e64 $vgpr24, implicit $exec
  ; GFX90A-NEXT:   $agpr55 = V_ACCVGPR_WRITE_B32_e64 $vgpr23, implicit $exec
  ; GFX90A-NEXT:   $agpr54 = V_ACCVGPR_WRITE_B32_e64 $vgpr22, implicit $exec
  ; GFX90A-NEXT:   $agpr53 = V_ACCVGPR_WRITE_B32_e64 $vgpr21, implicit $exec
  ; GFX90A-NEXT:   $agpr52 = V_ACCVGPR_WRITE_B32_e64 $vgpr20, implicit $exec
  ; GFX90A-NEXT:   $agpr51 = V_ACCVGPR_WRITE_B32_e64 $vgpr19, implicit $exec
  ; GFX90A-NEXT:   $agpr50 = V_ACCVGPR_WRITE_B32_e64 $vgpr18, implicit $exec
  ; GFX90A-NEXT:   $agpr49 = V_ACCVGPR_WRITE_B32_e64 $vgpr17, implicit $exec
  ; GFX90A-NEXT:   $agpr48 = V_ACCVGPR_WRITE_B32_e64 $vgpr16, implicit $exec
  ; GFX90A-NEXT:   $agpr47 = V_ACCVGPR_WRITE_B32_e64 $vgpr15, implicit $exec
  ; GFX90A-NEXT:   $agpr46 = V_ACCVGPR_WRITE_B32_e64 $vgpr14, implicit $exec
  ; GFX90A-NEXT:   $agpr45 = V_ACCVGPR_WRITE_B32_e64 $vgpr13, implicit $exec
  ; GFX90A-NEXT:   $agpr44 = V_ACCVGPR_WRITE_B32_e64 $vgpr12, implicit $exec
  ; GFX90A-NEXT:   $agpr43 = V_ACCVGPR_WRITE_B32_e64 $vgpr11, implicit $exec
  ; GFX90A-NEXT:   $agpr42 = V_ACCVGPR_WRITE_B32_e64 $vgpr10, implicit $exec
  ; GFX90A-NEXT:   $agpr41 = V_ACCVGPR_WRITE_B32_e64 $vgpr9, implicit $exec
  ; GFX90A-NEXT:   $agpr40 = V_ACCVGPR_WRITE_B32_e64 $vgpr8, implicit $exec
  ; GFX90A-NEXT:   $agpr39 = V_ACCVGPR_WRITE_B32_e64 $vgpr7, implicit $exec
  ; GFX90A-NEXT:   $agpr38 = V_ACCVGPR_WRITE_B32_e64 $vgpr6, implicit $exec
  ; GFX90A-NEXT:   $agpr37 = V_ACCVGPR_WRITE_B32_e64 $vgpr5, implicit $exec
  ; GFX90A-NEXT:   $agpr36 = V_ACCVGPR_WRITE_B32_e64 $vgpr4, implicit $exec
  ; GFX90A-NEXT:   $agpr35 = V_ACCVGPR_WRITE_B32_e64 $vgpr3, implicit $exec
  ; GFX90A-NEXT:   $agpr34 = V_ACCVGPR_WRITE_B32_e64 $vgpr2, implicit $exec
  ; GFX90A-NEXT:   $agpr33 = V_ACCVGPR_WRITE_B32_e64 $vgpr1, implicit $exec
  ; GFX90A-NEXT:   $agpr32 = V_ACCVGPR_WRITE_B32_e64 $vgpr0, implicit $exec
  ; GFX90A-NEXT:   S_ENDPGM 0, amdgpu_allvgprs
  ;
  ; GFX908-FLATSCR-LABEL: name: agpr64_restore_clobber_scc
  ; GFX908-FLATSCR: bb.0:
  ; GFX908-FLATSCR-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GFX908-FLATSCR-NEXT:   liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT:   S_CMP_EQ_U32 0, 0, implicit-def $scc
  ; GFX908-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $vgpr1, $sgpr32, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.2, addrspace 5)
  ; GFX908-FLATSCR-NEXT:   $vgpr1 = V_MOV_B32_e32 $sgpr32, implicit $exec
  ; GFX908-FLATSCR-NEXT:   $vgpr1 = V_ADD_U32_e32 8200, $vgpr1, implicit $exec
  ; GFX908-FLATSCR-NEXT:   $vgpr0 = SCRATCH_LOAD_DWORD $vgpr1, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.1, addrspace 5)
  ; GFX908-FLATSCR-NEXT:   $agpr0 = V_ACCVGPR_WRITE_B32_e64 killed $vgpr0, implicit $exec, implicit-def $agpr0_agpr1
  ; GFX908-FLATSCR-NEXT:   $vgpr0 = SCRATCH_LOAD_DWORD $vgpr1, 4, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.1 + 4, addrspace 5)
  ; GFX908-FLATSCR-NEXT:   $agpr1 = V_ACCVGPR_WRITE_B32_e64 killed $vgpr0, implicit $exec
  ; GFX908-FLATSCR-NEXT:   $vgpr1 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.2, addrspace 5)
  ; GFX908-FLATSCR-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT: bb.1:
  ; GFX908-FLATSCR-NEXT:   successors: %bb.2(0x80000000)
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT:   S_NOP 0
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT: bb.2:
  ; GFX908-FLATSCR-NEXT:   liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT:   S_ENDPGM 0, amdgpu_allvgprs
  ;
  ; GFX90A-FLATSCR-LABEL: name: agpr64_restore_clobber_scc
  ; GFX90A-FLATSCR: bb.0:
  ; GFX90A-FLATSCR-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GFX90A-FLATSCR-NEXT:   liveins: $agpr32, $agpr33, $agpr34, $agpr35, $agpr36, $agpr37, $agpr38, $agpr39, $agpr40, $agpr41, $agpr42, $agpr43, $agpr44, $agpr45, $agpr46, $agpr47, $agpr48, $agpr49, $agpr50, $agpr51, $agpr52, $agpr53, $agpr54, $agpr55, $agpr56, $agpr57, $agpr58, $agpr59, $agpr60, $agpr61, $agpr62, $agpr63, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT:   $vgpr0 = V_ACCVGPR_READ_B32_e64 killed $agpr32, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr1 = V_ACCVGPR_READ_B32_e64 killed $agpr33, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr2 = V_ACCVGPR_READ_B32_e64 killed $agpr34, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr3 = V_ACCVGPR_READ_B32_e64 killed $agpr35, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr4 = V_ACCVGPR_READ_B32_e64 killed $agpr36, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr5 = V_ACCVGPR_READ_B32_e64 killed $agpr37, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr6 = V_ACCVGPR_READ_B32_e64 killed $agpr38, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr7 = V_ACCVGPR_READ_B32_e64 killed $agpr39, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr8 = V_ACCVGPR_READ_B32_e64 killed $agpr40, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr9 = V_ACCVGPR_READ_B32_e64 killed $agpr41, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr10 = V_ACCVGPR_READ_B32_e64 killed $agpr42, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr11 = V_ACCVGPR_READ_B32_e64 killed $agpr43, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr12 = V_ACCVGPR_READ_B32_e64 killed $agpr44, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr13 = V_ACCVGPR_READ_B32_e64 killed $agpr45, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr14 = V_ACCVGPR_READ_B32_e64 killed $agpr46, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr15 = V_ACCVGPR_READ_B32_e64 killed $agpr47, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr16 = V_ACCVGPR_READ_B32_e64 killed $agpr48, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr17 = V_ACCVGPR_READ_B32_e64 killed $agpr49, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr18 = V_ACCVGPR_READ_B32_e64 killed $agpr50, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr19 = V_ACCVGPR_READ_B32_e64 killed $agpr51, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr20 = V_ACCVGPR_READ_B32_e64 killed $agpr52, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr21 = V_ACCVGPR_READ_B32_e64 killed $agpr53, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr22 = V_ACCVGPR_READ_B32_e64 killed $agpr54, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr23 = V_ACCVGPR_READ_B32_e64 killed $agpr55, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr24 = V_ACCVGPR_READ_B32_e64 killed $agpr56, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr25 = V_ACCVGPR_READ_B32_e64 killed $agpr57, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr26 = V_ACCVGPR_READ_B32_e64 killed $agpr58, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr27 = V_ACCVGPR_READ_B32_e64 killed $agpr59, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr28 = V_ACCVGPR_READ_B32_e64 killed $agpr60, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr29 = V_ACCVGPR_READ_B32_e64 killed $agpr61, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr30 = V_ACCVGPR_READ_B32_e64 killed $agpr62, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr31 = V_ACCVGPR_READ_B32_e64 killed $agpr63, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr32 = V_ACCVGPR_READ_B32_e64 killed $agpr64, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr33 = V_ACCVGPR_READ_B32_e64 killed $agpr65, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr34 = V_ACCVGPR_READ_B32_e64 killed $agpr66, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr35 = V_ACCVGPR_READ_B32_e64 killed $agpr67, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr36 = V_ACCVGPR_READ_B32_e64 killed $agpr68, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr37 = V_ACCVGPR_READ_B32_e64 killed $agpr69, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr38 = V_ACCVGPR_READ_B32_e64 killed $agpr70, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr39 = V_ACCVGPR_READ_B32_e64 killed $agpr71, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr48 = V_ACCVGPR_READ_B32_e64 killed $agpr72, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr49 = V_ACCVGPR_READ_B32_e64 killed $agpr73, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr50 = V_ACCVGPR_READ_B32_e64 killed $agpr74, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr51 = V_ACCVGPR_READ_B32_e64 killed $agpr75, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr52 = V_ACCVGPR_READ_B32_e64 killed $agpr76, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr53 = V_ACCVGPR_READ_B32_e64 killed $agpr77, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr54 = V_ACCVGPR_READ_B32_e64 killed $agpr78, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr55 = V_ACCVGPR_READ_B32_e64 killed $agpr79, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr80, $sgpr32, 700, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.50, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr81, $sgpr32, 696, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.51, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr82, $sgpr32, 692, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.52, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr83, $sgpr32, 688, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.53, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr84, $sgpr32, 684, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.54, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr85, $sgpr32, 680, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.55, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr86, $sgpr32, 676, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.56, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr87, $sgpr32, 672, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.57, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr88, $sgpr32, 668, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.58, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr89, $sgpr32, 664, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.59, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr90, $sgpr32, 660, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.60, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr91, $sgpr32, 656, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.61, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr92, $sgpr32, 652, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.62, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr93, $sgpr32, 648, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.63, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr94, $sgpr32, 644, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.64, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr95, $sgpr32, 640, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.65, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr96, $sgpr32, 636, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.66, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr97, $sgpr32, 632, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.67, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr98, $sgpr32, 628, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.68, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr99, $sgpr32, 624, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.69, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr100, $sgpr32, 620, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.70, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr101, $sgpr32, 616, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.71, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr102, $sgpr32, 612, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.72, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr103, $sgpr32, 608, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.73, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr104, $sgpr32, 604, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.74, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr105, $sgpr32, 600, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.75, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr106, $sgpr32, 596, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.76, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr107, $sgpr32, 592, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.77, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr108, $sgpr32, 588, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.78, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr109, $sgpr32, 584, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.79, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr110, $sgpr32, 580, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.80, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr111, $sgpr32, 576, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.81, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr112, $sgpr32, 572, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.82, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr113, $sgpr32, 568, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.83, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr114, $sgpr32, 564, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.84, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr115, $sgpr32, 560, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.85, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr116, $sgpr32, 556, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.86, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr117, $sgpr32, 552, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.87, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr118, $sgpr32, 548, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.88, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr119, $sgpr32, 544, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.89, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr120, $sgpr32, 540, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.90, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr121, $sgpr32, 536, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.91, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr122, $sgpr32, 532, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.92, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr123, $sgpr32, 528, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.93, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr124, $sgpr32, 524, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.94, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr125, $sgpr32, 520, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.95, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr126, $sgpr32, 516, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.96, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr127, $sgpr32, 512, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.97, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr128, $sgpr32, 508, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.98, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr129, $sgpr32, 504, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.99, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr130, $sgpr32, 500, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.100, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr131, $sgpr32, 496, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.101, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr132, $sgpr32, 492, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.102, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr133, $sgpr32, 488, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.103, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr134, $sgpr32, 484, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.104, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr135, $sgpr32, 480, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.105, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr136, $sgpr32, 476, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.106, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr137, $sgpr32, 472, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.107, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr138, $sgpr32, 468, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.108, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr139, $sgpr32, 464, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.109, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr140, $sgpr32, 460, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.110, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr141, $sgpr32, 456, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.111, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr142, $sgpr32, 452, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.112, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr143, $sgpr32, 448, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.113, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr144, $sgpr32, 444, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.114, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr145, $sgpr32, 440, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.115, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr146, $sgpr32, 436, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.116, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr147, $sgpr32, 432, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.117, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr148, $sgpr32, 428, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.118, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr149, $sgpr32, 424, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.119, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr150, $sgpr32, 420, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.120, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr151, $sgpr32, 416, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.121, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr152, $sgpr32, 412, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.122, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr153, $sgpr32, 408, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.123, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr154, $sgpr32, 404, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.124, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr155, $sgpr32, 400, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.125, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr156, $sgpr32, 396, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.126, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr157, $sgpr32, 392, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.127, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr158, $sgpr32, 388, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.128, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr159, $sgpr32, 384, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.129, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr160, $sgpr32, 380, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.130, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr161, $sgpr32, 376, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.131, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr162, $sgpr32, 372, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.132, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr163, $sgpr32, 368, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.133, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr164, $sgpr32, 364, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.134, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr165, $sgpr32, 360, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.135, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr166, $sgpr32, 356, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.136, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr167, $sgpr32, 352, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.137, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr168, $sgpr32, 348, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.138, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr169, $sgpr32, 344, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.139, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr170, $sgpr32, 340, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.140, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr171, $sgpr32, 336, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.141, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr172, $sgpr32, 332, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.142, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr173, $sgpr32, 328, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.143, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr174, $sgpr32, 324, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.144, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr175, $sgpr32, 320, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.145, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr176, $sgpr32, 316, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.146, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr177, $sgpr32, 312, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.147, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr178, $sgpr32, 308, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.148, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr179, $sgpr32, 304, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.149, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr180, $sgpr32, 300, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.150, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr181, $sgpr32, 296, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.151, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr182, $sgpr32, 292, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.152, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr183, $sgpr32, 288, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.153, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr184, $sgpr32, 284, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.154, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr185, $sgpr32, 280, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.155, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr186, $sgpr32, 276, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.156, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr187, $sgpr32, 272, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.157, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr188, $sgpr32, 268, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.158, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr189, $sgpr32, 264, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.159, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr190, $sgpr32, 260, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.160, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr191, $sgpr32, 256, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.161, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr192, $sgpr32, 252, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.162, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr193, $sgpr32, 248, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.163, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr194, $sgpr32, 244, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.164, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr195, $sgpr32, 240, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.165, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr196, $sgpr32, 236, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.166, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr197, $sgpr32, 232, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.167, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr198, $sgpr32, 228, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.168, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr199, $sgpr32, 224, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.169, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr200, $sgpr32, 220, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.170, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr201, $sgpr32, 216, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.171, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr202, $sgpr32, 212, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.172, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr203, $sgpr32, 208, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.173, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr204, $sgpr32, 204, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.174, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr205, $sgpr32, 200, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.175, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr206, $sgpr32, 196, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.176, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr207, $sgpr32, 192, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.177, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr208, $sgpr32, 188, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.178, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr209, $sgpr32, 184, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.179, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr210, $sgpr32, 180, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.180, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr211, $sgpr32, 176, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.181, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr212, $sgpr32, 172, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.182, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr213, $sgpr32, 168, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.183, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr214, $sgpr32, 164, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.184, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr215, $sgpr32, 160, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.185, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr216, $sgpr32, 156, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.186, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr217, $sgpr32, 152, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.187, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr218, $sgpr32, 148, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.188, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr219, $sgpr32, 144, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.189, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr220, $sgpr32, 140, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.190, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr221, $sgpr32, 136, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.191, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr222, $sgpr32, 132, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.192, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr223, $sgpr32, 128, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.193, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr224, $sgpr32, 124, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.194, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr225, $sgpr32, 120, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.195, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr226, $sgpr32, 116, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.196, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr227, $sgpr32, 112, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.197, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr228, $sgpr32, 108, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.198, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr229, $sgpr32, 104, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.199, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr230, $sgpr32, 100, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.200, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr231, $sgpr32, 96, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.201, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr232, $sgpr32, 92, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.202, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr233, $sgpr32, 88, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.203, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr234, $sgpr32, 84, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.204, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr235, $sgpr32, 80, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.205, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr236, $sgpr32, 76, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.206, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr237, $sgpr32, 72, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.207, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr238, $sgpr32, 68, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.208, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr239, $sgpr32, 64, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.209, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr240, $sgpr32, 60, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.210, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr241, $sgpr32, 56, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.211, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr242, $sgpr32, 52, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.212, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr243, $sgpr32, 48, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.213, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr244, $sgpr32, 44, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.214, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr245, $sgpr32, 40, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.215, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr246, $sgpr32, 36, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.216, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr247, $sgpr32, 32, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.217, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr248, $sgpr32, 28, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.218, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr249, $sgpr32, 24, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.219, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr250, $sgpr32, 20, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.220, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr251, $sgpr32, 16, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.221, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr252, $sgpr32, 12, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.222, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr253, $sgpr32, 8, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.223, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr254, $sgpr32, 4, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.224, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr255, $sgpr32, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.225, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   S_CMP_EQ_U32 0, 0, implicit-def $scc
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $vgpr40, $sgpr32, 704, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.226, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $vgpr40 = V_MOV_B32_e32 $sgpr32, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr40 = V_ADD_U32_e32 8904, $vgpr40, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr0_agpr1 = SCRATCH_LOAD_DWORDX2 killed $vgpr40, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s64) from %stack.1, align 4, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $vgpr40 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 704, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.226, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT: bb.1:
  ; GFX90A-FLATSCR-NEXT:   successors: %bb.2(0x80000000)
  ; GFX90A-FLATSCR-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT:   S_NOP 0
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT: bb.2:
  ; GFX90A-FLATSCR-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT:   $agpr255 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.225, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr254 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 4, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.224, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr253 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 8, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.223, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr252 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 12, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.222, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr251 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 16, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.221, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr250 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 20, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.220, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr249 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 24, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.219, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr248 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 28, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.218, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr247 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 32, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.217, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr246 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 36, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.216, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr245 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 40, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.215, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr244 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 44, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.214, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr243 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 48, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.213, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr242 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 52, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.212, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr241 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 56, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.211, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr240 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 60, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.210, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr239 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 64, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.209, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr238 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 68, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.208, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr237 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 72, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.207, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr236 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 76, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.206, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr235 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 80, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.205, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr234 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 84, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.204, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr233 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 88, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.203, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr232 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 92, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.202, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr231 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 96, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.201, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr230 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 100, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.200, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr229 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 104, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.199, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr228 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 108, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.198, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr227 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 112, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.197, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr226 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 116, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.196, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr225 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 120, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.195, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr224 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 124, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.194, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr223 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 128, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.193, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr222 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 132, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.192, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr221 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 136, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.191, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr220 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 140, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.190, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr219 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 144, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.189, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr218 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 148, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.188, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr217 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 152, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.187, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr216 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 156, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.186, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr215 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 160, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.185, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr214 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 164, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.184, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr213 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 168, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.183, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr212 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 172, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.182, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr211 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 176, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.181, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr210 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 180, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.180, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr209 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 184, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.179, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr208 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 188, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.178, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr207 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 192, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.177, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr206 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 196, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.176, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr205 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 200, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.175, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr204 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 204, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.174, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr203 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 208, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.173, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr202 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 212, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.172, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr201 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 216, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.171, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr200 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 220, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.170, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr199 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 224, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.169, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr198 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 228, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.168, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr197 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 232, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.167, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr196 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 236, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.166, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr195 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 240, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.165, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr194 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 244, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.164, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr193 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 248, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.163, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr192 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 252, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.162, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr191 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 256, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.161, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr190 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 260, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.160, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr189 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 264, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.159, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr188 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 268, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.158, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr187 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 272, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.157, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr186 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 276, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.156, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr185 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 280, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.155, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr184 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 284, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.154, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr183 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 288, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.153, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr182 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 292, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.152, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr181 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 296, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.151, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr180 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 300, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.150, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr179 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 304, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.149, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr178 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 308, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.148, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr177 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 312, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.147, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr176 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 316, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.146, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr175 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 320, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.145, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr174 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 324, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.144, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr173 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 328, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.143, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr172 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 332, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.142, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr171 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 336, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.141, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr170 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 340, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.140, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr169 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 344, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.139, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr168 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 348, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.138, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr167 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 352, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.137, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr166 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 356, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.136, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr165 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 360, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.135, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr164 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 364, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.134, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr163 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 368, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.133, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr162 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 372, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.132, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr161 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 376, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.131, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr160 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 380, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.130, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr159 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 384, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.129, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr158 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 388, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.128, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr157 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 392, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.127, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr156 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 396, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.126, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr155 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 400, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.125, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr154 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 404, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.124, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr153 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 408, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.123, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr152 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 412, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.122, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr151 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 416, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.121, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr150 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 420, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.120, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr149 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 424, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.119, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr148 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 428, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.118, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr147 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 432, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.117, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr146 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 436, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.116, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr145 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 440, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.115, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr144 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 444, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.114, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr143 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 448, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.113, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr142 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 452, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.112, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr141 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 456, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.111, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr140 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 460, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.110, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr139 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 464, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.109, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr138 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 468, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.108, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr137 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 472, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.107, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr136 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 476, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.106, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr135 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 480, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.105, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr134 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 484, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.104, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr133 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 488, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.103, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr132 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 492, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.102, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr131 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 496, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.101, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr130 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 500, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.100, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr129 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 504, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.99, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr128 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 508, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.98, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr127 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 512, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.97, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr126 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 516, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.96, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr125 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 520, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.95, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr124 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 524, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.94, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr123 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 528, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.93, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr122 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 532, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.92, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr121 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 536, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.91, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr120 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 540, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.90, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr119 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 544, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.89, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr118 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 548, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.88, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr117 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 552, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.87, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr116 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 556, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.86, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr115 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 560, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.85, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr114 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 564, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.84, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr113 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 568, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.83, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr112 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 572, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.82, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr111 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 576, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.81, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr110 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 580, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.80, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr109 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 584, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.79, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr108 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 588, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.78, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr107 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 592, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.77, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr106 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 596, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.76, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr105 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 600, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.75, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr104 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 604, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.74, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr103 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 608, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.73, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr102 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 612, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.72, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr101 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 616, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.71, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr100 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 620, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.70, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr99 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 624, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.69, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr98 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 628, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.68, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr97 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 632, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.67, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr96 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 636, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.66, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr95 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 640, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.65, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr94 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 644, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.64, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr93 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 648, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.63, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr92 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 652, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.62, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr91 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 656, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.61, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr90 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 660, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.60, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr89 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 664, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.59, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr88 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 668, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.58, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr87 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 672, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.57, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr86 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 676, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.56, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr85 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 680, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.55, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr84 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 684, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.54, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr83 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 688, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.53, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr82 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 692, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.52, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr81 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 696, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.51, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr80 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 700, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.50, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr79 = V_ACCVGPR_WRITE_B32_e64 $vgpr55, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr78 = V_ACCVGPR_WRITE_B32_e64 $vgpr54, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr77 = V_ACCVGPR_WRITE_B32_e64 $vgpr53, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr76 = V_ACCVGPR_WRITE_B32_e64 $vgpr52, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr75 = V_ACCVGPR_WRITE_B32_e64 $vgpr51, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr74 = V_ACCVGPR_WRITE_B32_e64 $vgpr50, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr73 = V_ACCVGPR_WRITE_B32_e64 $vgpr49, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr72 = V_ACCVGPR_WRITE_B32_e64 $vgpr48, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr71 = V_ACCVGPR_WRITE_B32_e64 $vgpr39, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr70 = V_ACCVGPR_WRITE_B32_e64 $vgpr38, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr69 = V_ACCVGPR_WRITE_B32_e64 $vgpr37, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr68 = V_ACCVGPR_WRITE_B32_e64 $vgpr36, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr67 = V_ACCVGPR_WRITE_B32_e64 $vgpr35, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr66 = V_ACCVGPR_WRITE_B32_e64 $vgpr34, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr65 = V_ACCVGPR_WRITE_B32_e64 $vgpr33, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr64 = V_ACCVGPR_WRITE_B32_e64 $vgpr32, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr63 = V_ACCVGPR_WRITE_B32_e64 $vgpr31, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr62 = V_ACCVGPR_WRITE_B32_e64 $vgpr30, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr61 = V_ACCVGPR_WRITE_B32_e64 $vgpr29, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr60 = V_ACCVGPR_WRITE_B32_e64 $vgpr28, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr59 = V_ACCVGPR_WRITE_B32_e64 $vgpr27, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr58 = V_ACCVGPR_WRITE_B32_e64 $vgpr26, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr57 = V_ACCVGPR_WRITE_B32_e64 $vgpr25, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr56 = V_ACCVGPR_WRITE_B32_e64 $vgpr24, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr55 = V_ACCVGPR_WRITE_B32_e64 $vgpr23, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr54 = V_ACCVGPR_WRITE_B32_e64 $vgpr22, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr53 = V_ACCVGPR_WRITE_B32_e64 $vgpr21, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr52 = V_ACCVGPR_WRITE_B32_e64 $vgpr20, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr51 = V_ACCVGPR_WRITE_B32_e64 $vgpr19, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr50 = V_ACCVGPR_WRITE_B32_e64 $vgpr18, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr49 = V_ACCVGPR_WRITE_B32_e64 $vgpr17, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr48 = V_ACCVGPR_WRITE_B32_e64 $vgpr16, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr47 = V_ACCVGPR_WRITE_B32_e64 $vgpr15, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr46 = V_ACCVGPR_WRITE_B32_e64 $vgpr14, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr45 = V_ACCVGPR_WRITE_B32_e64 $vgpr13, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr44 = V_ACCVGPR_WRITE_B32_e64 $vgpr12, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr43 = V_ACCVGPR_WRITE_B32_e64 $vgpr11, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr42 = V_ACCVGPR_WRITE_B32_e64 $vgpr10, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr41 = V_ACCVGPR_WRITE_B32_e64 $vgpr9, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr40 = V_ACCVGPR_WRITE_B32_e64 $vgpr8, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr39 = V_ACCVGPR_WRITE_B32_e64 $vgpr7, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr38 = V_ACCVGPR_WRITE_B32_e64 $vgpr6, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr37 = V_ACCVGPR_WRITE_B32_e64 $vgpr5, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr36 = V_ACCVGPR_WRITE_B32_e64 $vgpr4, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr35 = V_ACCVGPR_WRITE_B32_e64 $vgpr3, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr34 = V_ACCVGPR_WRITE_B32_e64 $vgpr2, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr33 = V_ACCVGPR_WRITE_B32_e64 $vgpr1, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr32 = V_ACCVGPR_WRITE_B32_e64 $vgpr0, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   S_ENDPGM 0, amdgpu_allvgprs
  bb.0:
    liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255

    S_CMP_EQ_U32 0, 0, implicit-def $scc
    $agpr0_agpr1 = SI_SPILL_A64_RESTORE %stack.1, $sgpr32, 0, implicit $exec :: (load (s64) from %stack.1, align 4, addrspace 5)
    S_CBRANCH_SCC1 %bb.2, implicit $scc

  bb.1:
    S_NOP 0

  bb.2:
    liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255
    S_ENDPGM 0, amdgpu_allvgprs
...

---
name: agpr96_restore_clobber_scc
tracksRegLiveness: true
stack:
  - { id: 0, type: default, offset: 0, size: 8192, alignment: 8 }
  - { id: 1, type: spill-slot, offset: 0, size: 8192, alignment: 4 }

machineFunctionInfo:
  isEntryFunction: false
  scratchRSrcReg:  $sgpr0_sgpr1_sgpr2_sgpr3
  frameOffsetReg:  $sgpr33
  stackPtrOffsetReg:  $sgpr32

body:             |
  ; GFX908-LABEL: name: agpr96_restore_clobber_scc
  ; GFX908: bb.0:
  ; GFX908-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GFX908-NEXT:   liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT:   S_CMP_EQ_U32 0, 0, implicit-def $scc
  ; GFX908-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $vgpr1, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.2, addrspace 5)
  ; GFX908-NEXT:   $vgpr1 = V_MOV_B32_e32 8200, implicit $exec
  ; GFX908-NEXT:   $vgpr0 = BUFFER_LOAD_DWORD_OFFEN $vgpr1, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.1, addrspace 5)
  ; GFX908-NEXT:   $agpr0 = V_ACCVGPR_WRITE_B32_e64 killed $vgpr0, implicit $exec, implicit-def $agpr0_agpr1_agpr2
  ; GFX908-NEXT:   $vgpr0 = BUFFER_LOAD_DWORD_OFFEN $vgpr1, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 4, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.1 + 4, addrspace 5)
  ; GFX908-NEXT:   $agpr1 = V_ACCVGPR_WRITE_B32_e64 killed $vgpr0, implicit $exec
  ; GFX908-NEXT:   $vgpr0 = BUFFER_LOAD_DWORD_OFFEN $vgpr1, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 8, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.1 + 8, addrspace 5)
  ; GFX908-NEXT:   $agpr2 = V_ACCVGPR_WRITE_B32_e64 killed $vgpr0, implicit $exec
  ; GFX908-NEXT:   $vgpr1 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.2, addrspace 5)
  ; GFX908-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT: bb.1:
  ; GFX908-NEXT:   successors: %bb.2(0x80000000)
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT:   S_NOP 0
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT: bb.2:
  ; GFX908-NEXT:   liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT:   S_ENDPGM 0, amdgpu_allvgprs
  ;
  ; GFX90A-LABEL: name: agpr96_restore_clobber_scc
  ; GFX90A: bb.0:
  ; GFX90A-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GFX90A-NEXT:   liveins: $agpr32, $agpr33, $agpr34, $agpr35, $agpr36, $agpr37, $agpr38, $agpr39, $agpr40, $agpr41, $agpr42, $agpr43, $agpr44, $agpr45, $agpr46, $agpr47, $agpr48, $agpr49, $agpr50, $agpr51, $agpr52, $agpr53, $agpr54, $agpr55, $agpr56, $agpr57, $agpr58, $agpr59, $agpr60, $agpr61, $agpr62, $agpr63, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   $vgpr0 = V_ACCVGPR_READ_B32_e64 killed $agpr32, implicit $exec
  ; GFX90A-NEXT:   $vgpr1 = V_ACCVGPR_READ_B32_e64 killed $agpr33, implicit $exec
  ; GFX90A-NEXT:   $vgpr2 = V_ACCVGPR_READ_B32_e64 killed $agpr34, implicit $exec
  ; GFX90A-NEXT:   $vgpr3 = V_ACCVGPR_READ_B32_e64 killed $agpr35, implicit $exec
  ; GFX90A-NEXT:   $vgpr4 = V_ACCVGPR_READ_B32_e64 killed $agpr36, implicit $exec
  ; GFX90A-NEXT:   $vgpr5 = V_ACCVGPR_READ_B32_e64 killed $agpr37, implicit $exec
  ; GFX90A-NEXT:   $vgpr6 = V_ACCVGPR_READ_B32_e64 killed $agpr38, implicit $exec
  ; GFX90A-NEXT:   $vgpr7 = V_ACCVGPR_READ_B32_e64 killed $agpr39, implicit $exec
  ; GFX90A-NEXT:   $vgpr8 = V_ACCVGPR_READ_B32_e64 killed $agpr40, implicit $exec
  ; GFX90A-NEXT:   $vgpr9 = V_ACCVGPR_READ_B32_e64 killed $agpr41, implicit $exec
  ; GFX90A-NEXT:   $vgpr10 = V_ACCVGPR_READ_B32_e64 killed $agpr42, implicit $exec
  ; GFX90A-NEXT:   $vgpr11 = V_ACCVGPR_READ_B32_e64 killed $agpr43, implicit $exec
  ; GFX90A-NEXT:   $vgpr12 = V_ACCVGPR_READ_B32_e64 killed $agpr44, implicit $exec
  ; GFX90A-NEXT:   $vgpr13 = V_ACCVGPR_READ_B32_e64 killed $agpr45, implicit $exec
  ; GFX90A-NEXT:   $vgpr14 = V_ACCVGPR_READ_B32_e64 killed $agpr46, implicit $exec
  ; GFX90A-NEXT:   $vgpr15 = V_ACCVGPR_READ_B32_e64 killed $agpr47, implicit $exec
  ; GFX90A-NEXT:   $vgpr16 = V_ACCVGPR_READ_B32_e64 killed $agpr48, implicit $exec
  ; GFX90A-NEXT:   $vgpr17 = V_ACCVGPR_READ_B32_e64 killed $agpr49, implicit $exec
  ; GFX90A-NEXT:   $vgpr18 = V_ACCVGPR_READ_B32_e64 killed $agpr50, implicit $exec
  ; GFX90A-NEXT:   $vgpr19 = V_ACCVGPR_READ_B32_e64 killed $agpr51, implicit $exec
  ; GFX90A-NEXT:   $vgpr20 = V_ACCVGPR_READ_B32_e64 killed $agpr52, implicit $exec
  ; GFX90A-NEXT:   $vgpr21 = V_ACCVGPR_READ_B32_e64 killed $agpr53, implicit $exec
  ; GFX90A-NEXT:   $vgpr22 = V_ACCVGPR_READ_B32_e64 killed $agpr54, implicit $exec
  ; GFX90A-NEXT:   $vgpr23 = V_ACCVGPR_READ_B32_e64 killed $agpr55, implicit $exec
  ; GFX90A-NEXT:   $vgpr24 = V_ACCVGPR_READ_B32_e64 killed $agpr56, implicit $exec
  ; GFX90A-NEXT:   $vgpr25 = V_ACCVGPR_READ_B32_e64 killed $agpr57, implicit $exec
  ; GFX90A-NEXT:   $vgpr26 = V_ACCVGPR_READ_B32_e64 killed $agpr58, implicit $exec
  ; GFX90A-NEXT:   $vgpr27 = V_ACCVGPR_READ_B32_e64 killed $agpr59, implicit $exec
  ; GFX90A-NEXT:   $vgpr28 = V_ACCVGPR_READ_B32_e64 killed $agpr60, implicit $exec
  ; GFX90A-NEXT:   $vgpr29 = V_ACCVGPR_READ_B32_e64 killed $agpr61, implicit $exec
  ; GFX90A-NEXT:   $vgpr30 = V_ACCVGPR_READ_B32_e64 killed $agpr62, implicit $exec
  ; GFX90A-NEXT:   $vgpr31 = V_ACCVGPR_READ_B32_e64 killed $agpr63, implicit $exec
  ; GFX90A-NEXT:   $vgpr32 = V_ACCVGPR_READ_B32_e64 killed $agpr64, implicit $exec
  ; GFX90A-NEXT:   $vgpr33 = V_ACCVGPR_READ_B32_e64 killed $agpr65, implicit $exec
  ; GFX90A-NEXT:   $vgpr34 = V_ACCVGPR_READ_B32_e64 killed $agpr66, implicit $exec
  ; GFX90A-NEXT:   $vgpr35 = V_ACCVGPR_READ_B32_e64 killed $agpr67, implicit $exec
  ; GFX90A-NEXT:   $vgpr36 = V_ACCVGPR_READ_B32_e64 killed $agpr68, implicit $exec
  ; GFX90A-NEXT:   $vgpr37 = V_ACCVGPR_READ_B32_e64 killed $agpr69, implicit $exec
  ; GFX90A-NEXT:   $vgpr38 = V_ACCVGPR_READ_B32_e64 killed $agpr70, implicit $exec
  ; GFX90A-NEXT:   $vgpr39 = V_ACCVGPR_READ_B32_e64 killed $agpr71, implicit $exec
  ; GFX90A-NEXT:   $vgpr48 = V_ACCVGPR_READ_B32_e64 killed $agpr72, implicit $exec
  ; GFX90A-NEXT:   $vgpr49 = V_ACCVGPR_READ_B32_e64 killed $agpr73, implicit $exec
  ; GFX90A-NEXT:   $vgpr50 = V_ACCVGPR_READ_B32_e64 killed $agpr74, implicit $exec
  ; GFX90A-NEXT:   $vgpr51 = V_ACCVGPR_READ_B32_e64 killed $agpr75, implicit $exec
  ; GFX90A-NEXT:   $vgpr52 = V_ACCVGPR_READ_B32_e64 killed $agpr76, implicit $exec
  ; GFX90A-NEXT:   $vgpr53 = V_ACCVGPR_READ_B32_e64 killed $agpr77, implicit $exec
  ; GFX90A-NEXT:   $vgpr54 = V_ACCVGPR_READ_B32_e64 killed $agpr78, implicit $exec
  ; GFX90A-NEXT:   $vgpr55 = V_ACCVGPR_READ_B32_e64 killed $agpr79, implicit $exec
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr80, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 700, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.50, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr81, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 696, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.51, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr82, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 692, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.52, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr83, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 688, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.53, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr84, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 684, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.54, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr85, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 680, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.55, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr86, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 676, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.56, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr87, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 672, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.57, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr88, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 668, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.58, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr89, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 664, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.59, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr90, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 660, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.60, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr91, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 656, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.61, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr92, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 652, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.62, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr93, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 648, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.63, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr94, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 644, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.64, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr95, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 640, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.65, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr96, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 636, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.66, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr97, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 632, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.67, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr98, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 628, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.68, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr99, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 624, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.69, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr100, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 620, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.70, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr101, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 616, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.71, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr102, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 612, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.72, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr103, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 608, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.73, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr104, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 604, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.74, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr105, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 600, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.75, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr106, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 596, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.76, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr107, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 592, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.77, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr108, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 588, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.78, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr109, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 584, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.79, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr110, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 580, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.80, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr111, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 576, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.81, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr112, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 572, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.82, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr113, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 568, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.83, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr114, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 564, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.84, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr115, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 560, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.85, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr116, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 556, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.86, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr117, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 552, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.87, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr118, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 548, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.88, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr119, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 544, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.89, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr120, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 540, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.90, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr121, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 536, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.91, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr122, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 532, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.92, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr123, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 528, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.93, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr124, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 524, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.94, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr125, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 520, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.95, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr126, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 516, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.96, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr127, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 512, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.97, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr128, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 508, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.98, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr129, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 504, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.99, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr130, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 500, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.100, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr131, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 496, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.101, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr132, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 492, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.102, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr133, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 488, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.103, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr134, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 484, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.104, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr135, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 480, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.105, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr136, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 476, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.106, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr137, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 472, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.107, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr138, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 468, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.108, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr139, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 464, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.109, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr140, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 460, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.110, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr141, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 456, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.111, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr142, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 452, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.112, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr143, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 448, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.113, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr144, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 444, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.114, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr145, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 440, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.115, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr146, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 436, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.116, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr147, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 432, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.117, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr148, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 428, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.118, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr149, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 424, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.119, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr150, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 420, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.120, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr151, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 416, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.121, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr152, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 412, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.122, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr153, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 408, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.123, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr154, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 404, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.124, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr155, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 400, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.125, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr156, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 396, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.126, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr157, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 392, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.127, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr158, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 388, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.128, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr159, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 384, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.129, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr160, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 380, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.130, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr161, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 376, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.131, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr162, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 372, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.132, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr163, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 368, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.133, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr164, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 364, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.134, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr165, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 360, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.135, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr166, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 356, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.136, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr167, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 352, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.137, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr168, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 348, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.138, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr169, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 344, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.139, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr170, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 340, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.140, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr171, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 336, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.141, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr172, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 332, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.142, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr173, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 328, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.143, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr174, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 324, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.144, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr175, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 320, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.145, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr176, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 316, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.146, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr177, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 312, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.147, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr178, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 308, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.148, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr179, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 304, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.149, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr180, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 300, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.150, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr181, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 296, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.151, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr182, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 292, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.152, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr183, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 288, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.153, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr184, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 284, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.154, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr185, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 280, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.155, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr186, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 276, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.156, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr187, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 272, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.157, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr188, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 268, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.158, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr189, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 264, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.159, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr190, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 260, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.160, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr191, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 256, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.161, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr192, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 252, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.162, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr193, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 248, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.163, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr194, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 244, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.164, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr195, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 240, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.165, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr196, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 236, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.166, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr197, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 232, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.167, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr198, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 228, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.168, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr199, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 224, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.169, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr200, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 220, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.170, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr201, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 216, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.171, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr202, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 212, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.172, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr203, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 208, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.173, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr204, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 204, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.174, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr205, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 200, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.175, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr206, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 196, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.176, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr207, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 192, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.177, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr208, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 188, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.178, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr209, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 184, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.179, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr210, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 180, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.180, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr211, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 176, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.181, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr212, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 172, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.182, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr213, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 168, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.183, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr214, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 164, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.184, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr215, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 160, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.185, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr216, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 156, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.186, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr217, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 152, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.187, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr218, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 148, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.188, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr219, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 144, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.189, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr220, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 140, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.190, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr221, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 136, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.191, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr222, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 132, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.192, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr223, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 128, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.193, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr224, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 124, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.194, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr225, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 120, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.195, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr226, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 116, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.196, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr227, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 112, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.197, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr228, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 108, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.198, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr229, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 104, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.199, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr230, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 100, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.200, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr231, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 96, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.201, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr232, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 92, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.202, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr233, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 88, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.203, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr234, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 84, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.204, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr235, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 80, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.205, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr236, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 76, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.206, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr237, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 72, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.207, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr238, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 68, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.208, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr239, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 64, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.209, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr240, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 60, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.210, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr241, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 56, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.211, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr242, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 52, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.212, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr243, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 48, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.213, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr244, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 44, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.214, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr245, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 40, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.215, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr246, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 36, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.216, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr247, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 32, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.217, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr248, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 28, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.218, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr249, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 24, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.219, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr250, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 20, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.220, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr251, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 16, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.221, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr252, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 12, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.222, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr253, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 8, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.223, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr254, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 4, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.224, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr255, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.225, addrspace 5)
  ; GFX90A-NEXT:   S_CMP_EQ_U32 0, 0, implicit-def $scc
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $vgpr40, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 704, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.226, addrspace 5)
  ; GFX90A-NEXT:   $vgpr40 = V_MOV_B32_e32 8904, implicit $exec
  ; GFX90A-NEXT:   $agpr0 = BUFFER_LOAD_DWORD_OFFEN $vgpr40, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec, implicit-def $agpr0_agpr1_agpr2 :: ("amdgpu-non-volatile" load (s32) from %stack.1, addrspace 5)
  ; GFX90A-NEXT:   $agpr1 = BUFFER_LOAD_DWORD_OFFEN $vgpr40, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 4, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.1 + 4, addrspace 5)
  ; GFX90A-NEXT:   $agpr2 = BUFFER_LOAD_DWORD_OFFEN killed $vgpr40, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 8, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.1 + 8, addrspace 5)
  ; GFX90A-NEXT:   $vgpr40 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 704, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.226, addrspace 5)
  ; GFX90A-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT: bb.1:
  ; GFX90A-NEXT:   successors: %bb.2(0x80000000)
  ; GFX90A-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   S_NOP 0
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT: bb.2:
  ; GFX90A-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   $agpr255 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.225, addrspace 5)
  ; GFX90A-NEXT:   $agpr254 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 4, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.224, addrspace 5)
  ; GFX90A-NEXT:   $agpr253 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 8, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.223, addrspace 5)
  ; GFX90A-NEXT:   $agpr252 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 12, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.222, addrspace 5)
  ; GFX90A-NEXT:   $agpr251 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 16, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.221, addrspace 5)
  ; GFX90A-NEXT:   $agpr250 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 20, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.220, addrspace 5)
  ; GFX90A-NEXT:   $agpr249 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 24, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.219, addrspace 5)
  ; GFX90A-NEXT:   $agpr248 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 28, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.218, addrspace 5)
  ; GFX90A-NEXT:   $agpr247 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 32, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.217, addrspace 5)
  ; GFX90A-NEXT:   $agpr246 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 36, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.216, addrspace 5)
  ; GFX90A-NEXT:   $agpr245 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 40, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.215, addrspace 5)
  ; GFX90A-NEXT:   $agpr244 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 44, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.214, addrspace 5)
  ; GFX90A-NEXT:   $agpr243 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 48, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.213, addrspace 5)
  ; GFX90A-NEXT:   $agpr242 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 52, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.212, addrspace 5)
  ; GFX90A-NEXT:   $agpr241 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 56, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.211, addrspace 5)
  ; GFX90A-NEXT:   $agpr240 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 60, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.210, addrspace 5)
  ; GFX90A-NEXT:   $agpr239 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 64, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.209, addrspace 5)
  ; GFX90A-NEXT:   $agpr238 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 68, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.208, addrspace 5)
  ; GFX90A-NEXT:   $agpr237 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 72, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.207, addrspace 5)
  ; GFX90A-NEXT:   $agpr236 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 76, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.206, addrspace 5)
  ; GFX90A-NEXT:   $agpr235 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 80, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.205, addrspace 5)
  ; GFX90A-NEXT:   $agpr234 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 84, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.204, addrspace 5)
  ; GFX90A-NEXT:   $agpr233 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 88, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.203, addrspace 5)
  ; GFX90A-NEXT:   $agpr232 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 92, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.202, addrspace 5)
  ; GFX90A-NEXT:   $agpr231 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 96, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.201, addrspace 5)
  ; GFX90A-NEXT:   $agpr230 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 100, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.200, addrspace 5)
  ; GFX90A-NEXT:   $agpr229 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 104, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.199, addrspace 5)
  ; GFX90A-NEXT:   $agpr228 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 108, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.198, addrspace 5)
  ; GFX90A-NEXT:   $agpr227 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 112, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.197, addrspace 5)
  ; GFX90A-NEXT:   $agpr226 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 116, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.196, addrspace 5)
  ; GFX90A-NEXT:   $agpr225 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 120, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.195, addrspace 5)
  ; GFX90A-NEXT:   $agpr224 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 124, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.194, addrspace 5)
  ; GFX90A-NEXT:   $agpr223 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 128, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.193, addrspace 5)
  ; GFX90A-NEXT:   $agpr222 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 132, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.192, addrspace 5)
  ; GFX90A-NEXT:   $agpr221 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 136, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.191, addrspace 5)
  ; GFX90A-NEXT:   $agpr220 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 140, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.190, addrspace 5)
  ; GFX90A-NEXT:   $agpr219 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 144, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.189, addrspace 5)
  ; GFX90A-NEXT:   $agpr218 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 148, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.188, addrspace 5)
  ; GFX90A-NEXT:   $agpr217 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 152, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.187, addrspace 5)
  ; GFX90A-NEXT:   $agpr216 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 156, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.186, addrspace 5)
  ; GFX90A-NEXT:   $agpr215 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 160, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.185, addrspace 5)
  ; GFX90A-NEXT:   $agpr214 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 164, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.184, addrspace 5)
  ; GFX90A-NEXT:   $agpr213 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 168, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.183, addrspace 5)
  ; GFX90A-NEXT:   $agpr212 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 172, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.182, addrspace 5)
  ; GFX90A-NEXT:   $agpr211 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 176, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.181, addrspace 5)
  ; GFX90A-NEXT:   $agpr210 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 180, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.180, addrspace 5)
  ; GFX90A-NEXT:   $agpr209 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 184, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.179, addrspace 5)
  ; GFX90A-NEXT:   $agpr208 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 188, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.178, addrspace 5)
  ; GFX90A-NEXT:   $agpr207 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 192, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.177, addrspace 5)
  ; GFX90A-NEXT:   $agpr206 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 196, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.176, addrspace 5)
  ; GFX90A-NEXT:   $agpr205 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 200, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.175, addrspace 5)
  ; GFX90A-NEXT:   $agpr204 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 204, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.174, addrspace 5)
  ; GFX90A-NEXT:   $agpr203 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 208, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.173, addrspace 5)
  ; GFX90A-NEXT:   $agpr202 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 212, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.172, addrspace 5)
  ; GFX90A-NEXT:   $agpr201 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 216, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.171, addrspace 5)
  ; GFX90A-NEXT:   $agpr200 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 220, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.170, addrspace 5)
  ; GFX90A-NEXT:   $agpr199 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 224, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.169, addrspace 5)
  ; GFX90A-NEXT:   $agpr198 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 228, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.168, addrspace 5)
  ; GFX90A-NEXT:   $agpr197 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 232, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.167, addrspace 5)
  ; GFX90A-NEXT:   $agpr196 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 236, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.166, addrspace 5)
  ; GFX90A-NEXT:   $agpr195 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 240, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.165, addrspace 5)
  ; GFX90A-NEXT:   $agpr194 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 244, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.164, addrspace 5)
  ; GFX90A-NEXT:   $agpr193 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 248, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.163, addrspace 5)
  ; GFX90A-NEXT:   $agpr192 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 252, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.162, addrspace 5)
  ; GFX90A-NEXT:   $agpr191 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 256, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.161, addrspace 5)
  ; GFX90A-NEXT:   $agpr190 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 260, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.160, addrspace 5)
  ; GFX90A-NEXT:   $agpr189 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 264, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.159, addrspace 5)
  ; GFX90A-NEXT:   $agpr188 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 268, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.158, addrspace 5)
  ; GFX90A-NEXT:   $agpr187 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 272, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.157, addrspace 5)
  ; GFX90A-NEXT:   $agpr186 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 276, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.156, addrspace 5)
  ; GFX90A-NEXT:   $agpr185 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 280, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.155, addrspace 5)
  ; GFX90A-NEXT:   $agpr184 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 284, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.154, addrspace 5)
  ; GFX90A-NEXT:   $agpr183 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 288, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.153, addrspace 5)
  ; GFX90A-NEXT:   $agpr182 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 292, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.152, addrspace 5)
  ; GFX90A-NEXT:   $agpr181 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 296, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.151, addrspace 5)
  ; GFX90A-NEXT:   $agpr180 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 300, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.150, addrspace 5)
  ; GFX90A-NEXT:   $agpr179 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 304, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.149, addrspace 5)
  ; GFX90A-NEXT:   $agpr178 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 308, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.148, addrspace 5)
  ; GFX90A-NEXT:   $agpr177 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 312, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.147, addrspace 5)
  ; GFX90A-NEXT:   $agpr176 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 316, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.146, addrspace 5)
  ; GFX90A-NEXT:   $agpr175 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 320, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.145, addrspace 5)
  ; GFX90A-NEXT:   $agpr174 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 324, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.144, addrspace 5)
  ; GFX90A-NEXT:   $agpr173 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 328, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.143, addrspace 5)
  ; GFX90A-NEXT:   $agpr172 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 332, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.142, addrspace 5)
  ; GFX90A-NEXT:   $agpr171 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 336, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.141, addrspace 5)
  ; GFX90A-NEXT:   $agpr170 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 340, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.140, addrspace 5)
  ; GFX90A-NEXT:   $agpr169 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 344, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.139, addrspace 5)
  ; GFX90A-NEXT:   $agpr168 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 348, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.138, addrspace 5)
  ; GFX90A-NEXT:   $agpr167 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 352, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.137, addrspace 5)
  ; GFX90A-NEXT:   $agpr166 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 356, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.136, addrspace 5)
  ; GFX90A-NEXT:   $agpr165 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 360, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.135, addrspace 5)
  ; GFX90A-NEXT:   $agpr164 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 364, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.134, addrspace 5)
  ; GFX90A-NEXT:   $agpr163 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 368, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.133, addrspace 5)
  ; GFX90A-NEXT:   $agpr162 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 372, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.132, addrspace 5)
  ; GFX90A-NEXT:   $agpr161 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 376, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.131, addrspace 5)
  ; GFX90A-NEXT:   $agpr160 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 380, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.130, addrspace 5)
  ; GFX90A-NEXT:   $agpr159 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 384, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.129, addrspace 5)
  ; GFX90A-NEXT:   $agpr158 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 388, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.128, addrspace 5)
  ; GFX90A-NEXT:   $agpr157 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 392, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.127, addrspace 5)
  ; GFX90A-NEXT:   $agpr156 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 396, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.126, addrspace 5)
  ; GFX90A-NEXT:   $agpr155 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 400, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.125, addrspace 5)
  ; GFX90A-NEXT:   $agpr154 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 404, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.124, addrspace 5)
  ; GFX90A-NEXT:   $agpr153 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 408, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.123, addrspace 5)
  ; GFX90A-NEXT:   $agpr152 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 412, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.122, addrspace 5)
  ; GFX90A-NEXT:   $agpr151 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 416, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.121, addrspace 5)
  ; GFX90A-NEXT:   $agpr150 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 420, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.120, addrspace 5)
  ; GFX90A-NEXT:   $agpr149 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 424, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.119, addrspace 5)
  ; GFX90A-NEXT:   $agpr148 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 428, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.118, addrspace 5)
  ; GFX90A-NEXT:   $agpr147 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 432, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.117, addrspace 5)
  ; GFX90A-NEXT:   $agpr146 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 436, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.116, addrspace 5)
  ; GFX90A-NEXT:   $agpr145 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 440, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.115, addrspace 5)
  ; GFX90A-NEXT:   $agpr144 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 444, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.114, addrspace 5)
  ; GFX90A-NEXT:   $agpr143 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 448, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.113, addrspace 5)
  ; GFX90A-NEXT:   $agpr142 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 452, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.112, addrspace 5)
  ; GFX90A-NEXT:   $agpr141 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 456, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.111, addrspace 5)
  ; GFX90A-NEXT:   $agpr140 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 460, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.110, addrspace 5)
  ; GFX90A-NEXT:   $agpr139 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 464, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.109, addrspace 5)
  ; GFX90A-NEXT:   $agpr138 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 468, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.108, addrspace 5)
  ; GFX90A-NEXT:   $agpr137 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 472, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.107, addrspace 5)
  ; GFX90A-NEXT:   $agpr136 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 476, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.106, addrspace 5)
  ; GFX90A-NEXT:   $agpr135 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 480, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.105, addrspace 5)
  ; GFX90A-NEXT:   $agpr134 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 484, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.104, addrspace 5)
  ; GFX90A-NEXT:   $agpr133 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 488, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.103, addrspace 5)
  ; GFX90A-NEXT:   $agpr132 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 492, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.102, addrspace 5)
  ; GFX90A-NEXT:   $agpr131 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 496, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.101, addrspace 5)
  ; GFX90A-NEXT:   $agpr130 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 500, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.100, addrspace 5)
  ; GFX90A-NEXT:   $agpr129 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 504, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.99, addrspace 5)
  ; GFX90A-NEXT:   $agpr128 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 508, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.98, addrspace 5)
  ; GFX90A-NEXT:   $agpr127 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 512, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.97, addrspace 5)
  ; GFX90A-NEXT:   $agpr126 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 516, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.96, addrspace 5)
  ; GFX90A-NEXT:   $agpr125 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 520, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.95, addrspace 5)
  ; GFX90A-NEXT:   $agpr124 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 524, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.94, addrspace 5)
  ; GFX90A-NEXT:   $agpr123 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 528, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.93, addrspace 5)
  ; GFX90A-NEXT:   $agpr122 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 532, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.92, addrspace 5)
  ; GFX90A-NEXT:   $agpr121 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 536, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.91, addrspace 5)
  ; GFX90A-NEXT:   $agpr120 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 540, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.90, addrspace 5)
  ; GFX90A-NEXT:   $agpr119 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 544, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.89, addrspace 5)
  ; GFX90A-NEXT:   $agpr118 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 548, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.88, addrspace 5)
  ; GFX90A-NEXT:   $agpr117 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 552, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.87, addrspace 5)
  ; GFX90A-NEXT:   $agpr116 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 556, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.86, addrspace 5)
  ; GFX90A-NEXT:   $agpr115 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 560, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.85, addrspace 5)
  ; GFX90A-NEXT:   $agpr114 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 564, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.84, addrspace 5)
  ; GFX90A-NEXT:   $agpr113 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 568, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.83, addrspace 5)
  ; GFX90A-NEXT:   $agpr112 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 572, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.82, addrspace 5)
  ; GFX90A-NEXT:   $agpr111 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 576, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.81, addrspace 5)
  ; GFX90A-NEXT:   $agpr110 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 580, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.80, addrspace 5)
  ; GFX90A-NEXT:   $agpr109 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 584, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.79, addrspace 5)
  ; GFX90A-NEXT:   $agpr108 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 588, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.78, addrspace 5)
  ; GFX90A-NEXT:   $agpr107 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 592, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.77, addrspace 5)
  ; GFX90A-NEXT:   $agpr106 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 596, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.76, addrspace 5)
  ; GFX90A-NEXT:   $agpr105 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 600, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.75, addrspace 5)
  ; GFX90A-NEXT:   $agpr104 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 604, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.74, addrspace 5)
  ; GFX90A-NEXT:   $agpr103 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 608, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.73, addrspace 5)
  ; GFX90A-NEXT:   $agpr102 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 612, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.72, addrspace 5)
  ; GFX90A-NEXT:   $agpr101 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 616, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.71, addrspace 5)
  ; GFX90A-NEXT:   $agpr100 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 620, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.70, addrspace 5)
  ; GFX90A-NEXT:   $agpr99 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 624, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.69, addrspace 5)
  ; GFX90A-NEXT:   $agpr98 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 628, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.68, addrspace 5)
  ; GFX90A-NEXT:   $agpr97 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 632, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.67, addrspace 5)
  ; GFX90A-NEXT:   $agpr96 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 636, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.66, addrspace 5)
  ; GFX90A-NEXT:   $agpr95 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 640, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.65, addrspace 5)
  ; GFX90A-NEXT:   $agpr94 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 644, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.64, addrspace 5)
  ; GFX90A-NEXT:   $agpr93 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 648, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.63, addrspace 5)
  ; GFX90A-NEXT:   $agpr92 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 652, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.62, addrspace 5)
  ; GFX90A-NEXT:   $agpr91 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 656, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.61, addrspace 5)
  ; GFX90A-NEXT:   $agpr90 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 660, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.60, addrspace 5)
  ; GFX90A-NEXT:   $agpr89 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 664, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.59, addrspace 5)
  ; GFX90A-NEXT:   $agpr88 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 668, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.58, addrspace 5)
  ; GFX90A-NEXT:   $agpr87 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 672, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.57, addrspace 5)
  ; GFX90A-NEXT:   $agpr86 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 676, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.56, addrspace 5)
  ; GFX90A-NEXT:   $agpr85 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 680, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.55, addrspace 5)
  ; GFX90A-NEXT:   $agpr84 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 684, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.54, addrspace 5)
  ; GFX90A-NEXT:   $agpr83 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 688, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.53, addrspace 5)
  ; GFX90A-NEXT:   $agpr82 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 692, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.52, addrspace 5)
  ; GFX90A-NEXT:   $agpr81 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 696, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.51, addrspace 5)
  ; GFX90A-NEXT:   $agpr80 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 700, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.50, addrspace 5)
  ; GFX90A-NEXT:   $agpr79 = V_ACCVGPR_WRITE_B32_e64 $vgpr55, implicit $exec
  ; GFX90A-NEXT:   $agpr78 = V_ACCVGPR_WRITE_B32_e64 $vgpr54, implicit $exec
  ; GFX90A-NEXT:   $agpr77 = V_ACCVGPR_WRITE_B32_e64 $vgpr53, implicit $exec
  ; GFX90A-NEXT:   $agpr76 = V_ACCVGPR_WRITE_B32_e64 $vgpr52, implicit $exec
  ; GFX90A-NEXT:   $agpr75 = V_ACCVGPR_WRITE_B32_e64 $vgpr51, implicit $exec
  ; GFX90A-NEXT:   $agpr74 = V_ACCVGPR_WRITE_B32_e64 $vgpr50, implicit $exec
  ; GFX90A-NEXT:   $agpr73 = V_ACCVGPR_WRITE_B32_e64 $vgpr49, implicit $exec
  ; GFX90A-NEXT:   $agpr72 = V_ACCVGPR_WRITE_B32_e64 $vgpr48, implicit $exec
  ; GFX90A-NEXT:   $agpr71 = V_ACCVGPR_WRITE_B32_e64 $vgpr39, implicit $exec
  ; GFX90A-NEXT:   $agpr70 = V_ACCVGPR_WRITE_B32_e64 $vgpr38, implicit $exec
  ; GFX90A-NEXT:   $agpr69 = V_ACCVGPR_WRITE_B32_e64 $vgpr37, implicit $exec
  ; GFX90A-NEXT:   $agpr68 = V_ACCVGPR_WRITE_B32_e64 $vgpr36, implicit $exec
  ; GFX90A-NEXT:   $agpr67 = V_ACCVGPR_WRITE_B32_e64 $vgpr35, implicit $exec
  ; GFX90A-NEXT:   $agpr66 = V_ACCVGPR_WRITE_B32_e64 $vgpr34, implicit $exec
  ; GFX90A-NEXT:   $agpr65 = V_ACCVGPR_WRITE_B32_e64 $vgpr33, implicit $exec
  ; GFX90A-NEXT:   $agpr64 = V_ACCVGPR_WRITE_B32_e64 $vgpr32, implicit $exec
  ; GFX90A-NEXT:   $agpr63 = V_ACCVGPR_WRITE_B32_e64 $vgpr31, implicit $exec
  ; GFX90A-NEXT:   $agpr62 = V_ACCVGPR_WRITE_B32_e64 $vgpr30, implicit $exec
  ; GFX90A-NEXT:   $agpr61 = V_ACCVGPR_WRITE_B32_e64 $vgpr29, implicit $exec
  ; GFX90A-NEXT:   $agpr60 = V_ACCVGPR_WRITE_B32_e64 $vgpr28, implicit $exec
  ; GFX90A-NEXT:   $agpr59 = V_ACCVGPR_WRITE_B32_e64 $vgpr27, implicit $exec
  ; GFX90A-NEXT:   $agpr58 = V_ACCVGPR_WRITE_B32_e64 $vgpr26, implicit $exec
  ; GFX90A-NEXT:   $agpr57 = V_ACCVGPR_WRITE_B32_e64 $vgpr25, implicit $exec
  ; GFX90A-NEXT:   $agpr56 = V_ACCVGPR_WRITE_B32_e64 $vgpr24, implicit $exec
  ; GFX90A-NEXT:   $agpr55 = V_ACCVGPR_WRITE_B32_e64 $vgpr23, implicit $exec
  ; GFX90A-NEXT:   $agpr54 = V_ACCVGPR_WRITE_B32_e64 $vgpr22, implicit $exec
  ; GFX90A-NEXT:   $agpr53 = V_ACCVGPR_WRITE_B32_e64 $vgpr21, implicit $exec
  ; GFX90A-NEXT:   $agpr52 = V_ACCVGPR_WRITE_B32_e64 $vgpr20, implicit $exec
  ; GFX90A-NEXT:   $agpr51 = V_ACCVGPR_WRITE_B32_e64 $vgpr19, implicit $exec
  ; GFX90A-NEXT:   $agpr50 = V_ACCVGPR_WRITE_B32_e64 $vgpr18, implicit $exec
  ; GFX90A-NEXT:   $agpr49 = V_ACCVGPR_WRITE_B32_e64 $vgpr17, implicit $exec
  ; GFX90A-NEXT:   $agpr48 = V_ACCVGPR_WRITE_B32_e64 $vgpr16, implicit $exec
  ; GFX90A-NEXT:   $agpr47 = V_ACCVGPR_WRITE_B32_e64 $vgpr15, implicit $exec
  ; GFX90A-NEXT:   $agpr46 = V_ACCVGPR_WRITE_B32_e64 $vgpr14, implicit $exec
  ; GFX90A-NEXT:   $agpr45 = V_ACCVGPR_WRITE_B32_e64 $vgpr13, implicit $exec
  ; GFX90A-NEXT:   $agpr44 = V_ACCVGPR_WRITE_B32_e64 $vgpr12, implicit $exec
  ; GFX90A-NEXT:   $agpr43 = V_ACCVGPR_WRITE_B32_e64 $vgpr11, implicit $exec
  ; GFX90A-NEXT:   $agpr42 = V_ACCVGPR_WRITE_B32_e64 $vgpr10, implicit $exec
  ; GFX90A-NEXT:   $agpr41 = V_ACCVGPR_WRITE_B32_e64 $vgpr9, implicit $exec
  ; GFX90A-NEXT:   $agpr40 = V_ACCVGPR_WRITE_B32_e64 $vgpr8, implicit $exec
  ; GFX90A-NEXT:   $agpr39 = V_ACCVGPR_WRITE_B32_e64 $vgpr7, implicit $exec
  ; GFX90A-NEXT:   $agpr38 = V_ACCVGPR_WRITE_B32_e64 $vgpr6, implicit $exec
  ; GFX90A-NEXT:   $agpr37 = V_ACCVGPR_WRITE_B32_e64 $vgpr5, implicit $exec
  ; GFX90A-NEXT:   $agpr36 = V_ACCVGPR_WRITE_B32_e64 $vgpr4, implicit $exec
  ; GFX90A-NEXT:   $agpr35 = V_ACCVGPR_WRITE_B32_e64 $vgpr3, implicit $exec
  ; GFX90A-NEXT:   $agpr34 = V_ACCVGPR_WRITE_B32_e64 $vgpr2, implicit $exec
  ; GFX90A-NEXT:   $agpr33 = V_ACCVGPR_WRITE_B32_e64 $vgpr1, implicit $exec
  ; GFX90A-NEXT:   $agpr32 = V_ACCVGPR_WRITE_B32_e64 $vgpr0, implicit $exec
  ; GFX90A-NEXT:   S_ENDPGM 0, amdgpu_allvgprs
  ;
  ; GFX908-FLATSCR-LABEL: name: agpr96_restore_clobber_scc
  ; GFX908-FLATSCR: bb.0:
  ; GFX908-FLATSCR-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GFX908-FLATSCR-NEXT:   liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT:   S_CMP_EQ_U32 0, 0, implicit-def $scc
  ; GFX908-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $vgpr1, $sgpr32, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.2, addrspace 5)
  ; GFX908-FLATSCR-NEXT:   $vgpr1 = V_MOV_B32_e32 $sgpr32, implicit $exec
  ; GFX908-FLATSCR-NEXT:   $vgpr1 = V_ADD_U32_e32 8200, $vgpr1, implicit $exec
  ; GFX908-FLATSCR-NEXT:   $vgpr0 = SCRATCH_LOAD_DWORD $vgpr1, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.1, addrspace 5)
  ; GFX908-FLATSCR-NEXT:   $agpr0 = V_ACCVGPR_WRITE_B32_e64 killed $vgpr0, implicit $exec, implicit-def $agpr0_agpr1_agpr2
  ; GFX908-FLATSCR-NEXT:   $vgpr0 = SCRATCH_LOAD_DWORD $vgpr1, 4, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.1 + 4, addrspace 5)
  ; GFX908-FLATSCR-NEXT:   $agpr1 = V_ACCVGPR_WRITE_B32_e64 killed $vgpr0, implicit $exec
  ; GFX908-FLATSCR-NEXT:   $vgpr0 = SCRATCH_LOAD_DWORD $vgpr1, 8, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.1 + 8, addrspace 5)
  ; GFX908-FLATSCR-NEXT:   $agpr2 = V_ACCVGPR_WRITE_B32_e64 killed $vgpr0, implicit $exec
  ; GFX908-FLATSCR-NEXT:   $vgpr1 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.2, addrspace 5)
  ; GFX908-FLATSCR-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT: bb.1:
  ; GFX908-FLATSCR-NEXT:   successors: %bb.2(0x80000000)
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT:   S_NOP 0
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT: bb.2:
  ; GFX908-FLATSCR-NEXT:   liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT:   S_ENDPGM 0, amdgpu_allvgprs
  ;
  ; GFX90A-FLATSCR-LABEL: name: agpr96_restore_clobber_scc
  ; GFX90A-FLATSCR: bb.0:
  ; GFX90A-FLATSCR-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GFX90A-FLATSCR-NEXT:   liveins: $agpr32, $agpr33, $agpr34, $agpr35, $agpr36, $agpr37, $agpr38, $agpr39, $agpr40, $agpr41, $agpr42, $agpr43, $agpr44, $agpr45, $agpr46, $agpr47, $agpr48, $agpr49, $agpr50, $agpr51, $agpr52, $agpr53, $agpr54, $agpr55, $agpr56, $agpr57, $agpr58, $agpr59, $agpr60, $agpr61, $agpr62, $agpr63, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT:   $vgpr0 = V_ACCVGPR_READ_B32_e64 killed $agpr32, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr1 = V_ACCVGPR_READ_B32_e64 killed $agpr33, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr2 = V_ACCVGPR_READ_B32_e64 killed $agpr34, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr3 = V_ACCVGPR_READ_B32_e64 killed $agpr35, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr4 = V_ACCVGPR_READ_B32_e64 killed $agpr36, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr5 = V_ACCVGPR_READ_B32_e64 killed $agpr37, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr6 = V_ACCVGPR_READ_B32_e64 killed $agpr38, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr7 = V_ACCVGPR_READ_B32_e64 killed $agpr39, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr8 = V_ACCVGPR_READ_B32_e64 killed $agpr40, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr9 = V_ACCVGPR_READ_B32_e64 killed $agpr41, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr10 = V_ACCVGPR_READ_B32_e64 killed $agpr42, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr11 = V_ACCVGPR_READ_B32_e64 killed $agpr43, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr12 = V_ACCVGPR_READ_B32_e64 killed $agpr44, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr13 = V_ACCVGPR_READ_B32_e64 killed $agpr45, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr14 = V_ACCVGPR_READ_B32_e64 killed $agpr46, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr15 = V_ACCVGPR_READ_B32_e64 killed $agpr47, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr16 = V_ACCVGPR_READ_B32_e64 killed $agpr48, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr17 = V_ACCVGPR_READ_B32_e64 killed $agpr49, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr18 = V_ACCVGPR_READ_B32_e64 killed $agpr50, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr19 = V_ACCVGPR_READ_B32_e64 killed $agpr51, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr20 = V_ACCVGPR_READ_B32_e64 killed $agpr52, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr21 = V_ACCVGPR_READ_B32_e64 killed $agpr53, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr22 = V_ACCVGPR_READ_B32_e64 killed $agpr54, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr23 = V_ACCVGPR_READ_B32_e64 killed $agpr55, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr24 = V_ACCVGPR_READ_B32_e64 killed $agpr56, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr25 = V_ACCVGPR_READ_B32_e64 killed $agpr57, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr26 = V_ACCVGPR_READ_B32_e64 killed $agpr58, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr27 = V_ACCVGPR_READ_B32_e64 killed $agpr59, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr28 = V_ACCVGPR_READ_B32_e64 killed $agpr60, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr29 = V_ACCVGPR_READ_B32_e64 killed $agpr61, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr30 = V_ACCVGPR_READ_B32_e64 killed $agpr62, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr31 = V_ACCVGPR_READ_B32_e64 killed $agpr63, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr32 = V_ACCVGPR_READ_B32_e64 killed $agpr64, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr33 = V_ACCVGPR_READ_B32_e64 killed $agpr65, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr34 = V_ACCVGPR_READ_B32_e64 killed $agpr66, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr35 = V_ACCVGPR_READ_B32_e64 killed $agpr67, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr36 = V_ACCVGPR_READ_B32_e64 killed $agpr68, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr37 = V_ACCVGPR_READ_B32_e64 killed $agpr69, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr38 = V_ACCVGPR_READ_B32_e64 killed $agpr70, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr39 = V_ACCVGPR_READ_B32_e64 killed $agpr71, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr48 = V_ACCVGPR_READ_B32_e64 killed $agpr72, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr49 = V_ACCVGPR_READ_B32_e64 killed $agpr73, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr50 = V_ACCVGPR_READ_B32_e64 killed $agpr74, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr51 = V_ACCVGPR_READ_B32_e64 killed $agpr75, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr52 = V_ACCVGPR_READ_B32_e64 killed $agpr76, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr53 = V_ACCVGPR_READ_B32_e64 killed $agpr77, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr54 = V_ACCVGPR_READ_B32_e64 killed $agpr78, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr55 = V_ACCVGPR_READ_B32_e64 killed $agpr79, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr80, $sgpr32, 700, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.50, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr81, $sgpr32, 696, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.51, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr82, $sgpr32, 692, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.52, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr83, $sgpr32, 688, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.53, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr84, $sgpr32, 684, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.54, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr85, $sgpr32, 680, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.55, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr86, $sgpr32, 676, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.56, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr87, $sgpr32, 672, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.57, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr88, $sgpr32, 668, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.58, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr89, $sgpr32, 664, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.59, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr90, $sgpr32, 660, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.60, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr91, $sgpr32, 656, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.61, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr92, $sgpr32, 652, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.62, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr93, $sgpr32, 648, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.63, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr94, $sgpr32, 644, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.64, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr95, $sgpr32, 640, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.65, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr96, $sgpr32, 636, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.66, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr97, $sgpr32, 632, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.67, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr98, $sgpr32, 628, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.68, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr99, $sgpr32, 624, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.69, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr100, $sgpr32, 620, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.70, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr101, $sgpr32, 616, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.71, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr102, $sgpr32, 612, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.72, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr103, $sgpr32, 608, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.73, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr104, $sgpr32, 604, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.74, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr105, $sgpr32, 600, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.75, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr106, $sgpr32, 596, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.76, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr107, $sgpr32, 592, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.77, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr108, $sgpr32, 588, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.78, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr109, $sgpr32, 584, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.79, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr110, $sgpr32, 580, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.80, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr111, $sgpr32, 576, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.81, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr112, $sgpr32, 572, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.82, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr113, $sgpr32, 568, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.83, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr114, $sgpr32, 564, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.84, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr115, $sgpr32, 560, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.85, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr116, $sgpr32, 556, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.86, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr117, $sgpr32, 552, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.87, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr118, $sgpr32, 548, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.88, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr119, $sgpr32, 544, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.89, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr120, $sgpr32, 540, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.90, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr121, $sgpr32, 536, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.91, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr122, $sgpr32, 532, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.92, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr123, $sgpr32, 528, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.93, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr124, $sgpr32, 524, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.94, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr125, $sgpr32, 520, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.95, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr126, $sgpr32, 516, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.96, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr127, $sgpr32, 512, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.97, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr128, $sgpr32, 508, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.98, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr129, $sgpr32, 504, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.99, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr130, $sgpr32, 500, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.100, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr131, $sgpr32, 496, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.101, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr132, $sgpr32, 492, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.102, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr133, $sgpr32, 488, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.103, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr134, $sgpr32, 484, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.104, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr135, $sgpr32, 480, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.105, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr136, $sgpr32, 476, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.106, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr137, $sgpr32, 472, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.107, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr138, $sgpr32, 468, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.108, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr139, $sgpr32, 464, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.109, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr140, $sgpr32, 460, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.110, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr141, $sgpr32, 456, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.111, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr142, $sgpr32, 452, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.112, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr143, $sgpr32, 448, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.113, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr144, $sgpr32, 444, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.114, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr145, $sgpr32, 440, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.115, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr146, $sgpr32, 436, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.116, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr147, $sgpr32, 432, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.117, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr148, $sgpr32, 428, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.118, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr149, $sgpr32, 424, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.119, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr150, $sgpr32, 420, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.120, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr151, $sgpr32, 416, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.121, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr152, $sgpr32, 412, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.122, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr153, $sgpr32, 408, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.123, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr154, $sgpr32, 404, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.124, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr155, $sgpr32, 400, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.125, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr156, $sgpr32, 396, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.126, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr157, $sgpr32, 392, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.127, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr158, $sgpr32, 388, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.128, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr159, $sgpr32, 384, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.129, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr160, $sgpr32, 380, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.130, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr161, $sgpr32, 376, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.131, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr162, $sgpr32, 372, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.132, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr163, $sgpr32, 368, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.133, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr164, $sgpr32, 364, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.134, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr165, $sgpr32, 360, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.135, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr166, $sgpr32, 356, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.136, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr167, $sgpr32, 352, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.137, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr168, $sgpr32, 348, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.138, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr169, $sgpr32, 344, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.139, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr170, $sgpr32, 340, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.140, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr171, $sgpr32, 336, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.141, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr172, $sgpr32, 332, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.142, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr173, $sgpr32, 328, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.143, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr174, $sgpr32, 324, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.144, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr175, $sgpr32, 320, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.145, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr176, $sgpr32, 316, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.146, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr177, $sgpr32, 312, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.147, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr178, $sgpr32, 308, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.148, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr179, $sgpr32, 304, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.149, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr180, $sgpr32, 300, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.150, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr181, $sgpr32, 296, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.151, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr182, $sgpr32, 292, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.152, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr183, $sgpr32, 288, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.153, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr184, $sgpr32, 284, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.154, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr185, $sgpr32, 280, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.155, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr186, $sgpr32, 276, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.156, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr187, $sgpr32, 272, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.157, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr188, $sgpr32, 268, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.158, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr189, $sgpr32, 264, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.159, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr190, $sgpr32, 260, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.160, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr191, $sgpr32, 256, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.161, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr192, $sgpr32, 252, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.162, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr193, $sgpr32, 248, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.163, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr194, $sgpr32, 244, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.164, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr195, $sgpr32, 240, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.165, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr196, $sgpr32, 236, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.166, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr197, $sgpr32, 232, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.167, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr198, $sgpr32, 228, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.168, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr199, $sgpr32, 224, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.169, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr200, $sgpr32, 220, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.170, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr201, $sgpr32, 216, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.171, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr202, $sgpr32, 212, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.172, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr203, $sgpr32, 208, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.173, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr204, $sgpr32, 204, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.174, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr205, $sgpr32, 200, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.175, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr206, $sgpr32, 196, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.176, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr207, $sgpr32, 192, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.177, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr208, $sgpr32, 188, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.178, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr209, $sgpr32, 184, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.179, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr210, $sgpr32, 180, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.180, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr211, $sgpr32, 176, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.181, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr212, $sgpr32, 172, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.182, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr213, $sgpr32, 168, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.183, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr214, $sgpr32, 164, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.184, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr215, $sgpr32, 160, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.185, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr216, $sgpr32, 156, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.186, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr217, $sgpr32, 152, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.187, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr218, $sgpr32, 148, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.188, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr219, $sgpr32, 144, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.189, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr220, $sgpr32, 140, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.190, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr221, $sgpr32, 136, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.191, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr222, $sgpr32, 132, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.192, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr223, $sgpr32, 128, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.193, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr224, $sgpr32, 124, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.194, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr225, $sgpr32, 120, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.195, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr226, $sgpr32, 116, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.196, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr227, $sgpr32, 112, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.197, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr228, $sgpr32, 108, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.198, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr229, $sgpr32, 104, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.199, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr230, $sgpr32, 100, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.200, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr231, $sgpr32, 96, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.201, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr232, $sgpr32, 92, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.202, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr233, $sgpr32, 88, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.203, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr234, $sgpr32, 84, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.204, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr235, $sgpr32, 80, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.205, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr236, $sgpr32, 76, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.206, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr237, $sgpr32, 72, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.207, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr238, $sgpr32, 68, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.208, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr239, $sgpr32, 64, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.209, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr240, $sgpr32, 60, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.210, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr241, $sgpr32, 56, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.211, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr242, $sgpr32, 52, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.212, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr243, $sgpr32, 48, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.213, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr244, $sgpr32, 44, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.214, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr245, $sgpr32, 40, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.215, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr246, $sgpr32, 36, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.216, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr247, $sgpr32, 32, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.217, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr248, $sgpr32, 28, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.218, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr249, $sgpr32, 24, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.219, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr250, $sgpr32, 20, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.220, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr251, $sgpr32, 16, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.221, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr252, $sgpr32, 12, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.222, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr253, $sgpr32, 8, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.223, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr254, $sgpr32, 4, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.224, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr255, $sgpr32, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.225, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   S_CMP_EQ_U32 0, 0, implicit-def $scc
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $vgpr40, $sgpr32, 704, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.226, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $vgpr40 = V_MOV_B32_e32 $sgpr32, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr40 = V_ADD_U32_e32 8904, $vgpr40, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr0_agpr1_agpr2 = SCRATCH_LOAD_DWORDX3 killed $vgpr40, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s96) from %stack.1, align 4, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $vgpr40 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 704, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.226, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT: bb.1:
  ; GFX90A-FLATSCR-NEXT:   successors: %bb.2(0x80000000)
  ; GFX90A-FLATSCR-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT:   S_NOP 0
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT: bb.2:
  ; GFX90A-FLATSCR-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT:   $agpr255 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.225, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr254 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 4, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.224, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr253 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 8, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.223, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr252 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 12, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.222, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr251 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 16, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.221, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr250 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 20, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.220, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr249 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 24, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.219, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr248 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 28, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.218, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr247 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 32, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.217, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr246 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 36, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.216, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr245 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 40, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.215, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr244 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 44, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.214, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr243 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 48, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.213, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr242 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 52, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.212, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr241 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 56, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.211, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr240 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 60, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.210, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr239 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 64, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.209, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr238 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 68, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.208, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr237 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 72, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.207, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr236 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 76, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.206, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr235 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 80, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.205, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr234 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 84, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.204, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr233 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 88, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.203, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr232 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 92, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.202, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr231 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 96, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.201, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr230 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 100, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.200, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr229 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 104, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.199, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr228 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 108, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.198, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr227 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 112, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.197, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr226 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 116, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.196, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr225 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 120, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.195, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr224 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 124, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.194, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr223 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 128, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.193, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr222 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 132, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.192, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr221 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 136, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.191, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr220 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 140, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.190, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr219 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 144, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.189, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr218 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 148, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.188, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr217 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 152, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.187, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr216 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 156, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.186, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr215 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 160, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.185, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr214 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 164, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.184, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr213 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 168, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.183, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr212 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 172, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.182, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr211 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 176, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.181, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr210 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 180, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.180, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr209 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 184, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.179, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr208 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 188, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.178, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr207 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 192, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.177, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr206 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 196, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.176, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr205 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 200, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.175, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr204 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 204, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.174, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr203 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 208, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.173, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr202 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 212, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.172, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr201 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 216, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.171, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr200 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 220, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.170, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr199 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 224, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.169, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr198 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 228, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.168, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr197 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 232, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.167, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr196 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 236, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.166, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr195 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 240, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.165, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr194 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 244, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.164, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr193 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 248, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.163, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr192 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 252, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.162, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr191 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 256, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.161, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr190 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 260, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.160, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr189 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 264, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.159, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr188 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 268, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.158, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr187 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 272, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.157, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr186 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 276, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.156, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr185 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 280, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.155, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr184 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 284, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.154, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr183 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 288, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.153, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr182 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 292, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.152, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr181 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 296, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.151, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr180 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 300, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.150, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr179 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 304, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.149, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr178 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 308, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.148, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr177 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 312, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.147, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr176 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 316, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.146, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr175 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 320, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.145, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr174 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 324, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.144, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr173 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 328, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.143, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr172 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 332, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.142, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr171 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 336, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.141, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr170 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 340, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.140, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr169 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 344, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.139, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr168 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 348, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.138, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr167 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 352, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.137, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr166 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 356, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.136, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr165 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 360, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.135, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr164 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 364, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.134, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr163 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 368, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.133, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr162 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 372, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.132, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr161 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 376, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.131, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr160 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 380, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.130, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr159 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 384, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.129, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr158 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 388, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.128, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr157 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 392, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.127, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr156 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 396, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.126, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr155 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 400, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.125, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr154 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 404, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.124, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr153 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 408, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.123, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr152 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 412, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.122, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr151 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 416, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.121, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr150 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 420, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.120, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr149 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 424, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.119, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr148 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 428, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.118, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr147 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 432, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.117, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr146 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 436, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.116, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr145 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 440, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.115, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr144 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 444, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.114, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr143 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 448, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.113, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr142 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 452, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.112, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr141 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 456, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.111, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr140 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 460, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.110, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr139 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 464, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.109, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr138 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 468, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.108, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr137 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 472, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.107, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr136 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 476, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.106, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr135 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 480, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.105, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr134 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 484, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.104, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr133 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 488, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.103, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr132 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 492, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.102, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr131 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 496, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.101, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr130 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 500, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.100, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr129 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 504, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.99, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr128 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 508, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.98, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr127 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 512, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.97, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr126 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 516, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.96, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr125 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 520, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.95, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr124 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 524, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.94, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr123 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 528, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.93, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr122 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 532, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.92, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr121 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 536, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.91, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr120 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 540, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.90, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr119 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 544, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.89, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr118 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 548, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.88, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr117 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 552, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.87, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr116 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 556, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.86, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr115 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 560, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.85, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr114 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 564, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.84, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr113 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 568, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.83, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr112 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 572, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.82, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr111 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 576, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.81, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr110 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 580, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.80, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr109 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 584, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.79, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr108 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 588, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.78, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr107 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 592, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.77, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr106 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 596, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.76, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr105 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 600, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.75, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr104 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 604, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.74, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr103 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 608, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.73, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr102 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 612, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.72, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr101 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 616, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.71, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr100 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 620, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.70, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr99 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 624, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.69, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr98 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 628, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.68, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr97 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 632, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.67, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr96 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 636, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.66, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr95 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 640, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.65, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr94 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 644, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.64, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr93 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 648, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.63, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr92 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 652, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.62, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr91 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 656, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.61, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr90 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 660, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.60, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr89 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 664, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.59, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr88 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 668, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.58, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr87 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 672, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.57, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr86 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 676, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.56, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr85 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 680, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.55, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr84 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 684, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.54, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr83 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 688, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.53, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr82 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 692, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.52, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr81 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 696, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.51, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr80 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 700, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.50, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr79 = V_ACCVGPR_WRITE_B32_e64 $vgpr55, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr78 = V_ACCVGPR_WRITE_B32_e64 $vgpr54, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr77 = V_ACCVGPR_WRITE_B32_e64 $vgpr53, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr76 = V_ACCVGPR_WRITE_B32_e64 $vgpr52, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr75 = V_ACCVGPR_WRITE_B32_e64 $vgpr51, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr74 = V_ACCVGPR_WRITE_B32_e64 $vgpr50, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr73 = V_ACCVGPR_WRITE_B32_e64 $vgpr49, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr72 = V_ACCVGPR_WRITE_B32_e64 $vgpr48, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr71 = V_ACCVGPR_WRITE_B32_e64 $vgpr39, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr70 = V_ACCVGPR_WRITE_B32_e64 $vgpr38, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr69 = V_ACCVGPR_WRITE_B32_e64 $vgpr37, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr68 = V_ACCVGPR_WRITE_B32_e64 $vgpr36, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr67 = V_ACCVGPR_WRITE_B32_e64 $vgpr35, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr66 = V_ACCVGPR_WRITE_B32_e64 $vgpr34, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr65 = V_ACCVGPR_WRITE_B32_e64 $vgpr33, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr64 = V_ACCVGPR_WRITE_B32_e64 $vgpr32, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr63 = V_ACCVGPR_WRITE_B32_e64 $vgpr31, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr62 = V_ACCVGPR_WRITE_B32_e64 $vgpr30, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr61 = V_ACCVGPR_WRITE_B32_e64 $vgpr29, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr60 = V_ACCVGPR_WRITE_B32_e64 $vgpr28, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr59 = V_ACCVGPR_WRITE_B32_e64 $vgpr27, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr58 = V_ACCVGPR_WRITE_B32_e64 $vgpr26, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr57 = V_ACCVGPR_WRITE_B32_e64 $vgpr25, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr56 = V_ACCVGPR_WRITE_B32_e64 $vgpr24, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr55 = V_ACCVGPR_WRITE_B32_e64 $vgpr23, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr54 = V_ACCVGPR_WRITE_B32_e64 $vgpr22, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr53 = V_ACCVGPR_WRITE_B32_e64 $vgpr21, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr52 = V_ACCVGPR_WRITE_B32_e64 $vgpr20, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr51 = V_ACCVGPR_WRITE_B32_e64 $vgpr19, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr50 = V_ACCVGPR_WRITE_B32_e64 $vgpr18, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr49 = V_ACCVGPR_WRITE_B32_e64 $vgpr17, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr48 = V_ACCVGPR_WRITE_B32_e64 $vgpr16, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr47 = V_ACCVGPR_WRITE_B32_e64 $vgpr15, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr46 = V_ACCVGPR_WRITE_B32_e64 $vgpr14, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr45 = V_ACCVGPR_WRITE_B32_e64 $vgpr13, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr44 = V_ACCVGPR_WRITE_B32_e64 $vgpr12, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr43 = V_ACCVGPR_WRITE_B32_e64 $vgpr11, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr42 = V_ACCVGPR_WRITE_B32_e64 $vgpr10, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr41 = V_ACCVGPR_WRITE_B32_e64 $vgpr9, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr40 = V_ACCVGPR_WRITE_B32_e64 $vgpr8, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr39 = V_ACCVGPR_WRITE_B32_e64 $vgpr7, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr38 = V_ACCVGPR_WRITE_B32_e64 $vgpr6, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr37 = V_ACCVGPR_WRITE_B32_e64 $vgpr5, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr36 = V_ACCVGPR_WRITE_B32_e64 $vgpr4, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr35 = V_ACCVGPR_WRITE_B32_e64 $vgpr3, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr34 = V_ACCVGPR_WRITE_B32_e64 $vgpr2, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr33 = V_ACCVGPR_WRITE_B32_e64 $vgpr1, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr32 = V_ACCVGPR_WRITE_B32_e64 $vgpr0, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   S_ENDPGM 0, amdgpu_allvgprs
  bb.0:
    liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255

    S_CMP_EQ_U32 0, 0, implicit-def $scc
    $agpr0_agpr1_agpr2 = SI_SPILL_A96_RESTORE %stack.1, $sgpr32, 0, implicit $exec :: (load (s64) from %stack.1, align 4, addrspace 5)
    S_CBRANCH_SCC1 %bb.2, implicit $scc

  bb.1:
    S_NOP 0

  bb.2:
    liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255
    S_ENDPGM 0, amdgpu_allvgprs
...

---
name: agpr32_save_clobber_scc
tracksRegLiveness: true

stack:
  - { id: 0, type: default, offset: 0, size: 8192, alignment: 8 }
  - { id: 1, type: spill-slot, offset: 0, size: 8192, alignment: 4 }

machineFunctionInfo:
  scratchRSrcReg:  $sgpr0_sgpr1_sgpr2_sgpr3
  frameOffsetReg:  $sgpr33
  stackPtrOffsetReg:  $sgpr32

body:             |
  ; GFX908-LABEL: name: agpr32_save_clobber_scc
  ; GFX908: bb.0:
  ; GFX908-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GFX908-NEXT:   liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $agpr0
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT:   S_CMP_EQ_U32 0, 0, implicit-def $scc
  ; GFX908-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $vgpr1, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.2, addrspace 5)
  ; GFX908-NEXT:   $vgpr1 = V_MOV_B32_e32 8200, implicit $exec
  ; GFX908-NEXT:   $vgpr0 = V_ACCVGPR_READ_B32_e64 $agpr0, implicit $exec
  ; GFX908-NEXT:   BUFFER_STORE_DWORD_OFFEN $vgpr0, $vgpr1, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.1, addrspace 5)
  ; GFX908-NEXT:   $vgpr1 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.2, addrspace 5)
  ; GFX908-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT: bb.1:
  ; GFX908-NEXT:   successors: %bb.2(0x80000000)
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT:   S_NOP 0
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT: bb.2:
  ; GFX908-NEXT:   liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $agpr0
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT:   S_ENDPGM 0, amdgpu_allvgprs
  ;
  ; GFX90A-LABEL: name: agpr32_save_clobber_scc
  ; GFX90A: bb.0:
  ; GFX90A-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GFX90A-NEXT:   liveins: $agpr0, $agpr32, $agpr33, $agpr34, $agpr35, $agpr36, $agpr37, $agpr38, $agpr39, $agpr40, $agpr41, $agpr42, $agpr43, $agpr44, $agpr45, $agpr46, $agpr47, $agpr48, $agpr49, $agpr50, $agpr51, $agpr52, $agpr53, $agpr54, $agpr55, $agpr56, $agpr57, $agpr58, $agpr59, $agpr60, $agpr61, $agpr62, $agpr63, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   $vgpr0 = V_ACCVGPR_READ_B32_e64 killed $agpr32, implicit $exec
  ; GFX90A-NEXT:   $vgpr1 = V_ACCVGPR_READ_B32_e64 killed $agpr33, implicit $exec
  ; GFX90A-NEXT:   $vgpr2 = V_ACCVGPR_READ_B32_e64 killed $agpr34, implicit $exec
  ; GFX90A-NEXT:   $vgpr3 = V_ACCVGPR_READ_B32_e64 killed $agpr35, implicit $exec
  ; GFX90A-NEXT:   $vgpr4 = V_ACCVGPR_READ_B32_e64 killed $agpr36, implicit $exec
  ; GFX90A-NEXT:   $vgpr5 = V_ACCVGPR_READ_B32_e64 killed $agpr37, implicit $exec
  ; GFX90A-NEXT:   $vgpr6 = V_ACCVGPR_READ_B32_e64 killed $agpr38, implicit $exec
  ; GFX90A-NEXT:   $vgpr7 = V_ACCVGPR_READ_B32_e64 killed $agpr39, implicit $exec
  ; GFX90A-NEXT:   $vgpr8 = V_ACCVGPR_READ_B32_e64 killed $agpr40, implicit $exec
  ; GFX90A-NEXT:   $vgpr9 = V_ACCVGPR_READ_B32_e64 killed $agpr41, implicit $exec
  ; GFX90A-NEXT:   $vgpr10 = V_ACCVGPR_READ_B32_e64 killed $agpr42, implicit $exec
  ; GFX90A-NEXT:   $vgpr11 = V_ACCVGPR_READ_B32_e64 killed $agpr43, implicit $exec
  ; GFX90A-NEXT:   $vgpr12 = V_ACCVGPR_READ_B32_e64 killed $agpr44, implicit $exec
  ; GFX90A-NEXT:   $vgpr13 = V_ACCVGPR_READ_B32_e64 killed $agpr45, implicit $exec
  ; GFX90A-NEXT:   $vgpr14 = V_ACCVGPR_READ_B32_e64 killed $agpr46, implicit $exec
  ; GFX90A-NEXT:   $vgpr15 = V_ACCVGPR_READ_B32_e64 killed $agpr47, implicit $exec
  ; GFX90A-NEXT:   $vgpr16 = V_ACCVGPR_READ_B32_e64 killed $agpr48, implicit $exec
  ; GFX90A-NEXT:   $vgpr17 = V_ACCVGPR_READ_B32_e64 killed $agpr49, implicit $exec
  ; GFX90A-NEXT:   $vgpr18 = V_ACCVGPR_READ_B32_e64 killed $agpr50, implicit $exec
  ; GFX90A-NEXT:   $vgpr19 = V_ACCVGPR_READ_B32_e64 killed $agpr51, implicit $exec
  ; GFX90A-NEXT:   $vgpr20 = V_ACCVGPR_READ_B32_e64 killed $agpr52, implicit $exec
  ; GFX90A-NEXT:   $vgpr21 = V_ACCVGPR_READ_B32_e64 killed $agpr53, implicit $exec
  ; GFX90A-NEXT:   $vgpr22 = V_ACCVGPR_READ_B32_e64 killed $agpr54, implicit $exec
  ; GFX90A-NEXT:   $vgpr23 = V_ACCVGPR_READ_B32_e64 killed $agpr55, implicit $exec
  ; GFX90A-NEXT:   $vgpr24 = V_ACCVGPR_READ_B32_e64 killed $agpr56, implicit $exec
  ; GFX90A-NEXT:   $vgpr25 = V_ACCVGPR_READ_B32_e64 killed $agpr57, implicit $exec
  ; GFX90A-NEXT:   $vgpr26 = V_ACCVGPR_READ_B32_e64 killed $agpr58, implicit $exec
  ; GFX90A-NEXT:   $vgpr27 = V_ACCVGPR_READ_B32_e64 killed $agpr59, implicit $exec
  ; GFX90A-NEXT:   $vgpr28 = V_ACCVGPR_READ_B32_e64 killed $agpr60, implicit $exec
  ; GFX90A-NEXT:   $vgpr29 = V_ACCVGPR_READ_B32_e64 killed $agpr61, implicit $exec
  ; GFX90A-NEXT:   $vgpr30 = V_ACCVGPR_READ_B32_e64 killed $agpr62, implicit $exec
  ; GFX90A-NEXT:   $vgpr31 = V_ACCVGPR_READ_B32_e64 killed $agpr63, implicit $exec
  ; GFX90A-NEXT:   $vgpr32 = V_ACCVGPR_READ_B32_e64 killed $agpr64, implicit $exec
  ; GFX90A-NEXT:   $vgpr33 = V_ACCVGPR_READ_B32_e64 killed $agpr65, implicit $exec
  ; GFX90A-NEXT:   $vgpr34 = V_ACCVGPR_READ_B32_e64 killed $agpr66, implicit $exec
  ; GFX90A-NEXT:   $vgpr35 = V_ACCVGPR_READ_B32_e64 killed $agpr67, implicit $exec
  ; GFX90A-NEXT:   $vgpr36 = V_ACCVGPR_READ_B32_e64 killed $agpr68, implicit $exec
  ; GFX90A-NEXT:   $vgpr37 = V_ACCVGPR_READ_B32_e64 killed $agpr69, implicit $exec
  ; GFX90A-NEXT:   $vgpr38 = V_ACCVGPR_READ_B32_e64 killed $agpr70, implicit $exec
  ; GFX90A-NEXT:   $vgpr39 = V_ACCVGPR_READ_B32_e64 killed $agpr71, implicit $exec
  ; GFX90A-NEXT:   $vgpr48 = V_ACCVGPR_READ_B32_e64 killed $agpr72, implicit $exec
  ; GFX90A-NEXT:   $vgpr49 = V_ACCVGPR_READ_B32_e64 killed $agpr73, implicit $exec
  ; GFX90A-NEXT:   $vgpr50 = V_ACCVGPR_READ_B32_e64 killed $agpr74, implicit $exec
  ; GFX90A-NEXT:   $vgpr51 = V_ACCVGPR_READ_B32_e64 killed $agpr75, implicit $exec
  ; GFX90A-NEXT:   $vgpr52 = V_ACCVGPR_READ_B32_e64 killed $agpr76, implicit $exec
  ; GFX90A-NEXT:   $vgpr53 = V_ACCVGPR_READ_B32_e64 killed $agpr77, implicit $exec
  ; GFX90A-NEXT:   $vgpr54 = V_ACCVGPR_READ_B32_e64 killed $agpr78, implicit $exec
  ; GFX90A-NEXT:   $vgpr55 = V_ACCVGPR_READ_B32_e64 killed $agpr79, implicit $exec
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr80, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 700, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.50, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr81, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 696, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.51, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr82, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 692, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.52, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr83, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 688, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.53, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr84, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 684, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.54, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr85, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 680, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.55, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr86, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 676, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.56, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr87, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 672, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.57, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr88, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 668, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.58, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr89, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 664, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.59, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr90, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 660, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.60, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr91, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 656, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.61, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr92, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 652, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.62, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr93, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 648, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.63, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr94, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 644, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.64, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr95, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 640, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.65, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr96, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 636, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.66, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr97, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 632, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.67, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr98, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 628, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.68, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr99, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 624, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.69, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr100, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 620, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.70, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr101, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 616, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.71, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr102, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 612, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.72, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr103, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 608, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.73, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr104, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 604, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.74, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr105, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 600, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.75, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr106, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 596, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.76, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr107, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 592, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.77, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr108, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 588, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.78, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr109, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 584, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.79, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr110, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 580, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.80, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr111, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 576, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.81, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr112, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 572, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.82, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr113, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 568, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.83, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr114, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 564, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.84, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr115, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 560, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.85, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr116, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 556, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.86, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr117, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 552, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.87, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr118, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 548, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.88, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr119, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 544, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.89, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr120, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 540, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.90, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr121, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 536, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.91, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr122, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 532, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.92, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr123, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 528, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.93, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr124, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 524, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.94, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr125, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 520, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.95, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr126, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 516, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.96, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr127, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 512, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.97, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr128, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 508, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.98, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr129, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 504, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.99, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr130, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 500, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.100, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr131, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 496, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.101, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr132, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 492, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.102, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr133, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 488, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.103, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr134, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 484, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.104, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr135, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 480, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.105, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr136, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 476, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.106, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr137, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 472, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.107, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr138, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 468, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.108, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr139, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 464, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.109, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr140, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 460, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.110, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr141, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 456, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.111, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr142, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 452, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.112, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr143, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 448, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.113, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr144, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 444, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.114, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr145, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 440, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.115, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr146, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 436, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.116, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr147, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 432, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.117, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr148, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 428, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.118, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr149, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 424, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.119, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr150, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 420, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.120, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr151, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 416, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.121, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr152, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 412, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.122, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr153, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 408, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.123, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr154, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 404, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.124, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr155, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 400, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.125, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr156, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 396, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.126, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr157, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 392, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.127, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr158, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 388, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.128, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr159, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 384, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.129, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr160, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 380, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.130, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr161, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 376, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.131, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr162, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 372, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.132, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr163, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 368, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.133, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr164, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 364, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.134, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr165, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 360, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.135, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr166, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 356, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.136, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr167, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 352, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.137, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr168, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 348, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.138, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr169, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 344, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.139, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr170, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 340, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.140, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr171, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 336, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.141, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr172, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 332, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.142, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr173, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 328, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.143, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr174, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 324, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.144, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr175, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 320, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.145, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr176, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 316, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.146, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr177, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 312, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.147, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr178, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 308, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.148, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr179, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 304, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.149, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr180, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 300, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.150, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr181, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 296, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.151, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr182, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 292, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.152, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr183, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 288, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.153, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr184, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 284, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.154, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr185, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 280, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.155, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr186, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 276, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.156, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr187, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 272, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.157, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr188, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 268, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.158, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr189, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 264, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.159, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr190, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 260, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.160, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr191, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 256, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.161, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr192, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 252, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.162, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr193, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 248, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.163, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr194, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 244, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.164, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr195, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 240, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.165, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr196, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 236, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.166, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr197, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 232, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.167, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr198, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 228, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.168, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr199, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 224, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.169, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr200, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 220, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.170, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr201, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 216, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.171, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr202, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 212, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.172, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr203, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 208, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.173, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr204, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 204, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.174, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr205, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 200, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.175, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr206, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 196, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.176, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr207, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 192, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.177, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr208, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 188, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.178, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr209, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 184, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.179, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr210, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 180, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.180, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr211, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 176, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.181, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr212, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 172, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.182, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr213, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 168, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.183, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr214, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 164, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.184, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr215, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 160, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.185, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr216, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 156, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.186, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr217, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 152, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.187, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr218, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 148, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.188, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr219, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 144, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.189, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr220, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 140, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.190, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr221, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 136, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.191, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr222, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 132, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.192, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr223, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 128, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.193, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr224, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 124, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.194, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr225, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 120, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.195, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr226, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 116, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.196, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr227, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 112, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.197, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr228, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 108, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.198, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr229, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 104, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.199, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr230, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 100, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.200, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr231, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 96, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.201, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr232, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 92, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.202, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr233, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 88, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.203, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr234, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 84, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.204, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr235, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 80, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.205, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr236, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 76, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.206, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr237, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 72, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.207, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr238, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 68, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.208, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr239, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 64, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.209, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr240, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 60, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.210, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr241, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 56, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.211, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr242, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 52, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.212, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr243, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 48, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.213, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr244, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 44, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.214, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr245, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 40, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.215, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr246, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 36, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.216, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr247, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 32, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.217, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr248, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 28, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.218, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr249, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 24, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.219, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr250, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 20, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.220, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr251, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 16, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.221, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr252, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 12, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.222, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr253, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 8, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.223, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr254, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 4, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.224, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr255, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.225, addrspace 5)
  ; GFX90A-NEXT:   S_CMP_EQ_U32 0, 0, implicit-def $scc
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $vgpr40, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 704, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.226, addrspace 5)
  ; GFX90A-NEXT:   $vgpr40 = V_MOV_B32_e32 8904, implicit $exec
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFEN $agpr0, killed $vgpr40, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.1, addrspace 5)
  ; GFX90A-NEXT:   $vgpr40 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 704, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.226, addrspace 5)
  ; GFX90A-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT: bb.1:
  ; GFX90A-NEXT:   successors: %bb.2(0x80000000)
  ; GFX90A-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   S_NOP 0
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT: bb.2:
  ; GFX90A-NEXT:   liveins: $agpr0, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   $agpr255 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.225, addrspace 5)
  ; GFX90A-NEXT:   $agpr254 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 4, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.224, addrspace 5)
  ; GFX90A-NEXT:   $agpr253 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 8, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.223, addrspace 5)
  ; GFX90A-NEXT:   $agpr252 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 12, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.222, addrspace 5)
  ; GFX90A-NEXT:   $agpr251 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 16, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.221, addrspace 5)
  ; GFX90A-NEXT:   $agpr250 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 20, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.220, addrspace 5)
  ; GFX90A-NEXT:   $agpr249 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 24, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.219, addrspace 5)
  ; GFX90A-NEXT:   $agpr248 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 28, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.218, addrspace 5)
  ; GFX90A-NEXT:   $agpr247 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 32, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.217, addrspace 5)
  ; GFX90A-NEXT:   $agpr246 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 36, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.216, addrspace 5)
  ; GFX90A-NEXT:   $agpr245 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 40, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.215, addrspace 5)
  ; GFX90A-NEXT:   $agpr244 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 44, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.214, addrspace 5)
  ; GFX90A-NEXT:   $agpr243 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 48, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.213, addrspace 5)
  ; GFX90A-NEXT:   $agpr242 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 52, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.212, addrspace 5)
  ; GFX90A-NEXT:   $agpr241 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 56, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.211, addrspace 5)
  ; GFX90A-NEXT:   $agpr240 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 60, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.210, addrspace 5)
  ; GFX90A-NEXT:   $agpr239 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 64, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.209, addrspace 5)
  ; GFX90A-NEXT:   $agpr238 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 68, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.208, addrspace 5)
  ; GFX90A-NEXT:   $agpr237 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 72, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.207, addrspace 5)
  ; GFX90A-NEXT:   $agpr236 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 76, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.206, addrspace 5)
  ; GFX90A-NEXT:   $agpr235 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 80, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.205, addrspace 5)
  ; GFX90A-NEXT:   $agpr234 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 84, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.204, addrspace 5)
  ; GFX90A-NEXT:   $agpr233 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 88, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.203, addrspace 5)
  ; GFX90A-NEXT:   $agpr232 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 92, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.202, addrspace 5)
  ; GFX90A-NEXT:   $agpr231 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 96, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.201, addrspace 5)
  ; GFX90A-NEXT:   $agpr230 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 100, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.200, addrspace 5)
  ; GFX90A-NEXT:   $agpr229 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 104, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.199, addrspace 5)
  ; GFX90A-NEXT:   $agpr228 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 108, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.198, addrspace 5)
  ; GFX90A-NEXT:   $agpr227 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 112, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.197, addrspace 5)
  ; GFX90A-NEXT:   $agpr226 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 116, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.196, addrspace 5)
  ; GFX90A-NEXT:   $agpr225 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 120, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.195, addrspace 5)
  ; GFX90A-NEXT:   $agpr224 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 124, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.194, addrspace 5)
  ; GFX90A-NEXT:   $agpr223 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 128, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.193, addrspace 5)
  ; GFX90A-NEXT:   $agpr222 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 132, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.192, addrspace 5)
  ; GFX90A-NEXT:   $agpr221 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 136, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.191, addrspace 5)
  ; GFX90A-NEXT:   $agpr220 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 140, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.190, addrspace 5)
  ; GFX90A-NEXT:   $agpr219 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 144, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.189, addrspace 5)
  ; GFX90A-NEXT:   $agpr218 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 148, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.188, addrspace 5)
  ; GFX90A-NEXT:   $agpr217 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 152, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.187, addrspace 5)
  ; GFX90A-NEXT:   $agpr216 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 156, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.186, addrspace 5)
  ; GFX90A-NEXT:   $agpr215 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 160, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.185, addrspace 5)
  ; GFX90A-NEXT:   $agpr214 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 164, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.184, addrspace 5)
  ; GFX90A-NEXT:   $agpr213 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 168, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.183, addrspace 5)
  ; GFX90A-NEXT:   $agpr212 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 172, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.182, addrspace 5)
  ; GFX90A-NEXT:   $agpr211 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 176, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.181, addrspace 5)
  ; GFX90A-NEXT:   $agpr210 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 180, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.180, addrspace 5)
  ; GFX90A-NEXT:   $agpr209 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 184, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.179, addrspace 5)
  ; GFX90A-NEXT:   $agpr208 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 188, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.178, addrspace 5)
  ; GFX90A-NEXT:   $agpr207 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 192, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.177, addrspace 5)
  ; GFX90A-NEXT:   $agpr206 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 196, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.176, addrspace 5)
  ; GFX90A-NEXT:   $agpr205 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 200, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.175, addrspace 5)
  ; GFX90A-NEXT:   $agpr204 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 204, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.174, addrspace 5)
  ; GFX90A-NEXT:   $agpr203 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 208, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.173, addrspace 5)
  ; GFX90A-NEXT:   $agpr202 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 212, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.172, addrspace 5)
  ; GFX90A-NEXT:   $agpr201 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 216, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.171, addrspace 5)
  ; GFX90A-NEXT:   $agpr200 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 220, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.170, addrspace 5)
  ; GFX90A-NEXT:   $agpr199 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 224, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.169, addrspace 5)
  ; GFX90A-NEXT:   $agpr198 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 228, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.168, addrspace 5)
  ; GFX90A-NEXT:   $agpr197 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 232, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.167, addrspace 5)
  ; GFX90A-NEXT:   $agpr196 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 236, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.166, addrspace 5)
  ; GFX90A-NEXT:   $agpr195 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 240, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.165, addrspace 5)
  ; GFX90A-NEXT:   $agpr194 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 244, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.164, addrspace 5)
  ; GFX90A-NEXT:   $agpr193 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 248, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.163, addrspace 5)
  ; GFX90A-NEXT:   $agpr192 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 252, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.162, addrspace 5)
  ; GFX90A-NEXT:   $agpr191 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 256, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.161, addrspace 5)
  ; GFX90A-NEXT:   $agpr190 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 260, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.160, addrspace 5)
  ; GFX90A-NEXT:   $agpr189 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 264, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.159, addrspace 5)
  ; GFX90A-NEXT:   $agpr188 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 268, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.158, addrspace 5)
  ; GFX90A-NEXT:   $agpr187 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 272, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.157, addrspace 5)
  ; GFX90A-NEXT:   $agpr186 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 276, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.156, addrspace 5)
  ; GFX90A-NEXT:   $agpr185 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 280, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.155, addrspace 5)
  ; GFX90A-NEXT:   $agpr184 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 284, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.154, addrspace 5)
  ; GFX90A-NEXT:   $agpr183 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 288, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.153, addrspace 5)
  ; GFX90A-NEXT:   $agpr182 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 292, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.152, addrspace 5)
  ; GFX90A-NEXT:   $agpr181 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 296, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.151, addrspace 5)
  ; GFX90A-NEXT:   $agpr180 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 300, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.150, addrspace 5)
  ; GFX90A-NEXT:   $agpr179 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 304, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.149, addrspace 5)
  ; GFX90A-NEXT:   $agpr178 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 308, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.148, addrspace 5)
  ; GFX90A-NEXT:   $agpr177 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 312, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.147, addrspace 5)
  ; GFX90A-NEXT:   $agpr176 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 316, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.146, addrspace 5)
  ; GFX90A-NEXT:   $agpr175 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 320, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.145, addrspace 5)
  ; GFX90A-NEXT:   $agpr174 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 324, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.144, addrspace 5)
  ; GFX90A-NEXT:   $agpr173 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 328, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.143, addrspace 5)
  ; GFX90A-NEXT:   $agpr172 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 332, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.142, addrspace 5)
  ; GFX90A-NEXT:   $agpr171 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 336, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.141, addrspace 5)
  ; GFX90A-NEXT:   $agpr170 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 340, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.140, addrspace 5)
  ; GFX90A-NEXT:   $agpr169 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 344, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.139, addrspace 5)
  ; GFX90A-NEXT:   $agpr168 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 348, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.138, addrspace 5)
  ; GFX90A-NEXT:   $agpr167 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 352, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.137, addrspace 5)
  ; GFX90A-NEXT:   $agpr166 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 356, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.136, addrspace 5)
  ; GFX90A-NEXT:   $agpr165 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 360, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.135, addrspace 5)
  ; GFX90A-NEXT:   $agpr164 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 364, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.134, addrspace 5)
  ; GFX90A-NEXT:   $agpr163 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 368, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.133, addrspace 5)
  ; GFX90A-NEXT:   $agpr162 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 372, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.132, addrspace 5)
  ; GFX90A-NEXT:   $agpr161 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 376, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.131, addrspace 5)
  ; GFX90A-NEXT:   $agpr160 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 380, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.130, addrspace 5)
  ; GFX90A-NEXT:   $agpr159 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 384, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.129, addrspace 5)
  ; GFX90A-NEXT:   $agpr158 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 388, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.128, addrspace 5)
  ; GFX90A-NEXT:   $agpr157 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 392, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.127, addrspace 5)
  ; GFX90A-NEXT:   $agpr156 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 396, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.126, addrspace 5)
  ; GFX90A-NEXT:   $agpr155 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 400, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.125, addrspace 5)
  ; GFX90A-NEXT:   $agpr154 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 404, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.124, addrspace 5)
  ; GFX90A-NEXT:   $agpr153 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 408, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.123, addrspace 5)
  ; GFX90A-NEXT:   $agpr152 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 412, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.122, addrspace 5)
  ; GFX90A-NEXT:   $agpr151 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 416, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.121, addrspace 5)
  ; GFX90A-NEXT:   $agpr150 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 420, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.120, addrspace 5)
  ; GFX90A-NEXT:   $agpr149 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 424, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.119, addrspace 5)
  ; GFX90A-NEXT:   $agpr148 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 428, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.118, addrspace 5)
  ; GFX90A-NEXT:   $agpr147 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 432, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.117, addrspace 5)
  ; GFX90A-NEXT:   $agpr146 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 436, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.116, addrspace 5)
  ; GFX90A-NEXT:   $agpr145 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 440, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.115, addrspace 5)
  ; GFX90A-NEXT:   $agpr144 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 444, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.114, addrspace 5)
  ; GFX90A-NEXT:   $agpr143 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 448, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.113, addrspace 5)
  ; GFX90A-NEXT:   $agpr142 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 452, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.112, addrspace 5)
  ; GFX90A-NEXT:   $agpr141 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 456, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.111, addrspace 5)
  ; GFX90A-NEXT:   $agpr140 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 460, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.110, addrspace 5)
  ; GFX90A-NEXT:   $agpr139 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 464, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.109, addrspace 5)
  ; GFX90A-NEXT:   $agpr138 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 468, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.108, addrspace 5)
  ; GFX90A-NEXT:   $agpr137 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 472, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.107, addrspace 5)
  ; GFX90A-NEXT:   $agpr136 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 476, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.106, addrspace 5)
  ; GFX90A-NEXT:   $agpr135 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 480, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.105, addrspace 5)
  ; GFX90A-NEXT:   $agpr134 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 484, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.104, addrspace 5)
  ; GFX90A-NEXT:   $agpr133 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 488, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.103, addrspace 5)
  ; GFX90A-NEXT:   $agpr132 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 492, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.102, addrspace 5)
  ; GFX90A-NEXT:   $agpr131 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 496, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.101, addrspace 5)
  ; GFX90A-NEXT:   $agpr130 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 500, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.100, addrspace 5)
  ; GFX90A-NEXT:   $agpr129 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 504, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.99, addrspace 5)
  ; GFX90A-NEXT:   $agpr128 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 508, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.98, addrspace 5)
  ; GFX90A-NEXT:   $agpr127 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 512, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.97, addrspace 5)
  ; GFX90A-NEXT:   $agpr126 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 516, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.96, addrspace 5)
  ; GFX90A-NEXT:   $agpr125 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 520, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.95, addrspace 5)
  ; GFX90A-NEXT:   $agpr124 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 524, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.94, addrspace 5)
  ; GFX90A-NEXT:   $agpr123 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 528, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.93, addrspace 5)
  ; GFX90A-NEXT:   $agpr122 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 532, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.92, addrspace 5)
  ; GFX90A-NEXT:   $agpr121 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 536, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.91, addrspace 5)
  ; GFX90A-NEXT:   $agpr120 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 540, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.90, addrspace 5)
  ; GFX90A-NEXT:   $agpr119 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 544, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.89, addrspace 5)
  ; GFX90A-NEXT:   $agpr118 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 548, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.88, addrspace 5)
  ; GFX90A-NEXT:   $agpr117 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 552, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.87, addrspace 5)
  ; GFX90A-NEXT:   $agpr116 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 556, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.86, addrspace 5)
  ; GFX90A-NEXT:   $agpr115 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 560, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.85, addrspace 5)
  ; GFX90A-NEXT:   $agpr114 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 564, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.84, addrspace 5)
  ; GFX90A-NEXT:   $agpr113 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 568, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.83, addrspace 5)
  ; GFX90A-NEXT:   $agpr112 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 572, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.82, addrspace 5)
  ; GFX90A-NEXT:   $agpr111 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 576, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.81, addrspace 5)
  ; GFX90A-NEXT:   $agpr110 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 580, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.80, addrspace 5)
  ; GFX90A-NEXT:   $agpr109 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 584, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.79, addrspace 5)
  ; GFX90A-NEXT:   $agpr108 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 588, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.78, addrspace 5)
  ; GFX90A-NEXT:   $agpr107 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 592, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.77, addrspace 5)
  ; GFX90A-NEXT:   $agpr106 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 596, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.76, addrspace 5)
  ; GFX90A-NEXT:   $agpr105 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 600, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.75, addrspace 5)
  ; GFX90A-NEXT:   $agpr104 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 604, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.74, addrspace 5)
  ; GFX90A-NEXT:   $agpr103 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 608, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.73, addrspace 5)
  ; GFX90A-NEXT:   $agpr102 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 612, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.72, addrspace 5)
  ; GFX90A-NEXT:   $agpr101 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 616, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.71, addrspace 5)
  ; GFX90A-NEXT:   $agpr100 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 620, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.70, addrspace 5)
  ; GFX90A-NEXT:   $agpr99 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 624, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.69, addrspace 5)
  ; GFX90A-NEXT:   $agpr98 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 628, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.68, addrspace 5)
  ; GFX90A-NEXT:   $agpr97 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 632, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.67, addrspace 5)
  ; GFX90A-NEXT:   $agpr96 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 636, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.66, addrspace 5)
  ; GFX90A-NEXT:   $agpr95 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 640, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.65, addrspace 5)
  ; GFX90A-NEXT:   $agpr94 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 644, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.64, addrspace 5)
  ; GFX90A-NEXT:   $agpr93 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 648, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.63, addrspace 5)
  ; GFX90A-NEXT:   $agpr92 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 652, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.62, addrspace 5)
  ; GFX90A-NEXT:   $agpr91 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 656, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.61, addrspace 5)
  ; GFX90A-NEXT:   $agpr90 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 660, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.60, addrspace 5)
  ; GFX90A-NEXT:   $agpr89 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 664, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.59, addrspace 5)
  ; GFX90A-NEXT:   $agpr88 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 668, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.58, addrspace 5)
  ; GFX90A-NEXT:   $agpr87 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 672, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.57, addrspace 5)
  ; GFX90A-NEXT:   $agpr86 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 676, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.56, addrspace 5)
  ; GFX90A-NEXT:   $agpr85 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 680, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.55, addrspace 5)
  ; GFX90A-NEXT:   $agpr84 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 684, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.54, addrspace 5)
  ; GFX90A-NEXT:   $agpr83 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 688, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.53, addrspace 5)
  ; GFX90A-NEXT:   $agpr82 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 692, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.52, addrspace 5)
  ; GFX90A-NEXT:   $agpr81 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 696, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.51, addrspace 5)
  ; GFX90A-NEXT:   $agpr80 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 700, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.50, addrspace 5)
  ; GFX90A-NEXT:   $agpr79 = V_ACCVGPR_WRITE_B32_e64 $vgpr55, implicit $exec
  ; GFX90A-NEXT:   $agpr78 = V_ACCVGPR_WRITE_B32_e64 $vgpr54, implicit $exec
  ; GFX90A-NEXT:   $agpr77 = V_ACCVGPR_WRITE_B32_e64 $vgpr53, implicit $exec
  ; GFX90A-NEXT:   $agpr76 = V_ACCVGPR_WRITE_B32_e64 $vgpr52, implicit $exec
  ; GFX90A-NEXT:   $agpr75 = V_ACCVGPR_WRITE_B32_e64 $vgpr51, implicit $exec
  ; GFX90A-NEXT:   $agpr74 = V_ACCVGPR_WRITE_B32_e64 $vgpr50, implicit $exec
  ; GFX90A-NEXT:   $agpr73 = V_ACCVGPR_WRITE_B32_e64 $vgpr49, implicit $exec
  ; GFX90A-NEXT:   $agpr72 = V_ACCVGPR_WRITE_B32_e64 $vgpr48, implicit $exec
  ; GFX90A-NEXT:   $agpr71 = V_ACCVGPR_WRITE_B32_e64 $vgpr39, implicit $exec
  ; GFX90A-NEXT:   $agpr70 = V_ACCVGPR_WRITE_B32_e64 $vgpr38, implicit $exec
  ; GFX90A-NEXT:   $agpr69 = V_ACCVGPR_WRITE_B32_e64 $vgpr37, implicit $exec
  ; GFX90A-NEXT:   $agpr68 = V_ACCVGPR_WRITE_B32_e64 $vgpr36, implicit $exec
  ; GFX90A-NEXT:   $agpr67 = V_ACCVGPR_WRITE_B32_e64 $vgpr35, implicit $exec
  ; GFX90A-NEXT:   $agpr66 = V_ACCVGPR_WRITE_B32_e64 $vgpr34, implicit $exec
  ; GFX90A-NEXT:   $agpr65 = V_ACCVGPR_WRITE_B32_e64 $vgpr33, implicit $exec
  ; GFX90A-NEXT:   $agpr64 = V_ACCVGPR_WRITE_B32_e64 $vgpr32, implicit $exec
  ; GFX90A-NEXT:   $agpr63 = V_ACCVGPR_WRITE_B32_e64 $vgpr31, implicit $exec
  ; GFX90A-NEXT:   $agpr62 = V_ACCVGPR_WRITE_B32_e64 $vgpr30, implicit $exec
  ; GFX90A-NEXT:   $agpr61 = V_ACCVGPR_WRITE_B32_e64 $vgpr29, implicit $exec
  ; GFX90A-NEXT:   $agpr60 = V_ACCVGPR_WRITE_B32_e64 $vgpr28, implicit $exec
  ; GFX90A-NEXT:   $agpr59 = V_ACCVGPR_WRITE_B32_e64 $vgpr27, implicit $exec
  ; GFX90A-NEXT:   $agpr58 = V_ACCVGPR_WRITE_B32_e64 $vgpr26, implicit $exec
  ; GFX90A-NEXT:   $agpr57 = V_ACCVGPR_WRITE_B32_e64 $vgpr25, implicit $exec
  ; GFX90A-NEXT:   $agpr56 = V_ACCVGPR_WRITE_B32_e64 $vgpr24, implicit $exec
  ; GFX90A-NEXT:   $agpr55 = V_ACCVGPR_WRITE_B32_e64 $vgpr23, implicit $exec
  ; GFX90A-NEXT:   $agpr54 = V_ACCVGPR_WRITE_B32_e64 $vgpr22, implicit $exec
  ; GFX90A-NEXT:   $agpr53 = V_ACCVGPR_WRITE_B32_e64 $vgpr21, implicit $exec
  ; GFX90A-NEXT:   $agpr52 = V_ACCVGPR_WRITE_B32_e64 $vgpr20, implicit $exec
  ; GFX90A-NEXT:   $agpr51 = V_ACCVGPR_WRITE_B32_e64 $vgpr19, implicit $exec
  ; GFX90A-NEXT:   $agpr50 = V_ACCVGPR_WRITE_B32_e64 $vgpr18, implicit $exec
  ; GFX90A-NEXT:   $agpr49 = V_ACCVGPR_WRITE_B32_e64 $vgpr17, implicit $exec
  ; GFX90A-NEXT:   $agpr48 = V_ACCVGPR_WRITE_B32_e64 $vgpr16, implicit $exec
  ; GFX90A-NEXT:   $agpr47 = V_ACCVGPR_WRITE_B32_e64 $vgpr15, implicit $exec
  ; GFX90A-NEXT:   $agpr46 = V_ACCVGPR_WRITE_B32_e64 $vgpr14, implicit $exec
  ; GFX90A-NEXT:   $agpr45 = V_ACCVGPR_WRITE_B32_e64 $vgpr13, implicit $exec
  ; GFX90A-NEXT:   $agpr44 = V_ACCVGPR_WRITE_B32_e64 $vgpr12, implicit $exec
  ; GFX90A-NEXT:   $agpr43 = V_ACCVGPR_WRITE_B32_e64 $vgpr11, implicit $exec
  ; GFX90A-NEXT:   $agpr42 = V_ACCVGPR_WRITE_B32_e64 $vgpr10, implicit $exec
  ; GFX90A-NEXT:   $agpr41 = V_ACCVGPR_WRITE_B32_e64 $vgpr9, implicit $exec
  ; GFX90A-NEXT:   $agpr40 = V_ACCVGPR_WRITE_B32_e64 $vgpr8, implicit $exec
  ; GFX90A-NEXT:   $agpr39 = V_ACCVGPR_WRITE_B32_e64 $vgpr7, implicit $exec
  ; GFX90A-NEXT:   $agpr38 = V_ACCVGPR_WRITE_B32_e64 $vgpr6, implicit $exec
  ; GFX90A-NEXT:   $agpr37 = V_ACCVGPR_WRITE_B32_e64 $vgpr5, implicit $exec
  ; GFX90A-NEXT:   $agpr36 = V_ACCVGPR_WRITE_B32_e64 $vgpr4, implicit $exec
  ; GFX90A-NEXT:   $agpr35 = V_ACCVGPR_WRITE_B32_e64 $vgpr3, implicit $exec
  ; GFX90A-NEXT:   $agpr34 = V_ACCVGPR_WRITE_B32_e64 $vgpr2, implicit $exec
  ; GFX90A-NEXT:   $agpr33 = V_ACCVGPR_WRITE_B32_e64 $vgpr1, implicit $exec
  ; GFX90A-NEXT:   $agpr32 = V_ACCVGPR_WRITE_B32_e64 $vgpr0, implicit $exec
  ; GFX90A-NEXT:   S_ENDPGM 0, amdgpu_allvgprs
  ;
  ; GFX908-FLATSCR-LABEL: name: agpr32_save_clobber_scc
  ; GFX908-FLATSCR: bb.0:
  ; GFX908-FLATSCR-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GFX908-FLATSCR-NEXT:   liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $agpr0
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT:   S_CMP_EQ_U32 0, 0, implicit-def $scc
  ; GFX908-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $vgpr1, $sgpr32, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.2, addrspace 5)
  ; GFX908-FLATSCR-NEXT:   $vgpr1 = V_MOV_B32_e32 $sgpr32, implicit $exec
  ; GFX908-FLATSCR-NEXT:   $vgpr1 = V_ADD_U32_e32 8200, $vgpr1, implicit $exec
  ; GFX908-FLATSCR-NEXT:   $vgpr0 = V_ACCVGPR_READ_B32_e64 $agpr0, implicit $exec
  ; GFX908-FLATSCR-NEXT:   SCRATCH_STORE_DWORD $vgpr0, $vgpr1, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.1, addrspace 5)
  ; GFX908-FLATSCR-NEXT:   $vgpr1 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.2, addrspace 5)
  ; GFX908-FLATSCR-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT: bb.1:
  ; GFX908-FLATSCR-NEXT:   successors: %bb.2(0x80000000)
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT:   S_NOP 0
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT: bb.2:
  ; GFX908-FLATSCR-NEXT:   liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $agpr0
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT:   S_ENDPGM 0, amdgpu_allvgprs
  ;
  ; GFX90A-FLATSCR-LABEL: name: agpr32_save_clobber_scc
  ; GFX90A-FLATSCR: bb.0:
  ; GFX90A-FLATSCR-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GFX90A-FLATSCR-NEXT:   liveins: $agpr0, $agpr32, $agpr33, $agpr34, $agpr35, $agpr36, $agpr37, $agpr38, $agpr39, $agpr40, $agpr41, $agpr42, $agpr43, $agpr44, $agpr45, $agpr46, $agpr47, $agpr48, $agpr49, $agpr50, $agpr51, $agpr52, $agpr53, $agpr54, $agpr55, $agpr56, $agpr57, $agpr58, $agpr59, $agpr60, $agpr61, $agpr62, $agpr63, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT:   $vgpr0 = V_ACCVGPR_READ_B32_e64 killed $agpr32, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr1 = V_ACCVGPR_READ_B32_e64 killed $agpr33, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr2 = V_ACCVGPR_READ_B32_e64 killed $agpr34, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr3 = V_ACCVGPR_READ_B32_e64 killed $agpr35, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr4 = V_ACCVGPR_READ_B32_e64 killed $agpr36, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr5 = V_ACCVGPR_READ_B32_e64 killed $agpr37, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr6 = V_ACCVGPR_READ_B32_e64 killed $agpr38, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr7 = V_ACCVGPR_READ_B32_e64 killed $agpr39, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr8 = V_ACCVGPR_READ_B32_e64 killed $agpr40, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr9 = V_ACCVGPR_READ_B32_e64 killed $agpr41, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr10 = V_ACCVGPR_READ_B32_e64 killed $agpr42, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr11 = V_ACCVGPR_READ_B32_e64 killed $agpr43, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr12 = V_ACCVGPR_READ_B32_e64 killed $agpr44, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr13 = V_ACCVGPR_READ_B32_e64 killed $agpr45, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr14 = V_ACCVGPR_READ_B32_e64 killed $agpr46, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr15 = V_ACCVGPR_READ_B32_e64 killed $agpr47, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr16 = V_ACCVGPR_READ_B32_e64 killed $agpr48, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr17 = V_ACCVGPR_READ_B32_e64 killed $agpr49, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr18 = V_ACCVGPR_READ_B32_e64 killed $agpr50, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr19 = V_ACCVGPR_READ_B32_e64 killed $agpr51, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr20 = V_ACCVGPR_READ_B32_e64 killed $agpr52, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr21 = V_ACCVGPR_READ_B32_e64 killed $agpr53, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr22 = V_ACCVGPR_READ_B32_e64 killed $agpr54, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr23 = V_ACCVGPR_READ_B32_e64 killed $agpr55, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr24 = V_ACCVGPR_READ_B32_e64 killed $agpr56, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr25 = V_ACCVGPR_READ_B32_e64 killed $agpr57, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr26 = V_ACCVGPR_READ_B32_e64 killed $agpr58, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr27 = V_ACCVGPR_READ_B32_e64 killed $agpr59, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr28 = V_ACCVGPR_READ_B32_e64 killed $agpr60, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr29 = V_ACCVGPR_READ_B32_e64 killed $agpr61, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr30 = V_ACCVGPR_READ_B32_e64 killed $agpr62, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr31 = V_ACCVGPR_READ_B32_e64 killed $agpr63, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr32 = V_ACCVGPR_READ_B32_e64 killed $agpr64, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr33 = V_ACCVGPR_READ_B32_e64 killed $agpr65, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr34 = V_ACCVGPR_READ_B32_e64 killed $agpr66, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr35 = V_ACCVGPR_READ_B32_e64 killed $agpr67, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr36 = V_ACCVGPR_READ_B32_e64 killed $agpr68, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr37 = V_ACCVGPR_READ_B32_e64 killed $agpr69, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr38 = V_ACCVGPR_READ_B32_e64 killed $agpr70, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr39 = V_ACCVGPR_READ_B32_e64 killed $agpr71, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr48 = V_ACCVGPR_READ_B32_e64 killed $agpr72, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr49 = V_ACCVGPR_READ_B32_e64 killed $agpr73, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr50 = V_ACCVGPR_READ_B32_e64 killed $agpr74, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr51 = V_ACCVGPR_READ_B32_e64 killed $agpr75, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr52 = V_ACCVGPR_READ_B32_e64 killed $agpr76, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr53 = V_ACCVGPR_READ_B32_e64 killed $agpr77, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr54 = V_ACCVGPR_READ_B32_e64 killed $agpr78, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr55 = V_ACCVGPR_READ_B32_e64 killed $agpr79, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr80, $sgpr32, 700, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.50, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr81, $sgpr32, 696, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.51, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr82, $sgpr32, 692, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.52, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr83, $sgpr32, 688, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.53, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr84, $sgpr32, 684, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.54, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr85, $sgpr32, 680, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.55, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr86, $sgpr32, 676, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.56, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr87, $sgpr32, 672, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.57, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr88, $sgpr32, 668, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.58, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr89, $sgpr32, 664, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.59, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr90, $sgpr32, 660, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.60, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr91, $sgpr32, 656, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.61, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr92, $sgpr32, 652, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.62, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr93, $sgpr32, 648, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.63, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr94, $sgpr32, 644, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.64, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr95, $sgpr32, 640, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.65, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr96, $sgpr32, 636, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.66, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr97, $sgpr32, 632, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.67, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr98, $sgpr32, 628, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.68, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr99, $sgpr32, 624, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.69, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr100, $sgpr32, 620, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.70, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr101, $sgpr32, 616, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.71, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr102, $sgpr32, 612, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.72, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr103, $sgpr32, 608, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.73, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr104, $sgpr32, 604, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.74, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr105, $sgpr32, 600, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.75, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr106, $sgpr32, 596, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.76, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr107, $sgpr32, 592, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.77, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr108, $sgpr32, 588, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.78, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr109, $sgpr32, 584, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.79, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr110, $sgpr32, 580, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.80, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr111, $sgpr32, 576, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.81, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr112, $sgpr32, 572, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.82, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr113, $sgpr32, 568, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.83, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr114, $sgpr32, 564, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.84, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr115, $sgpr32, 560, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.85, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr116, $sgpr32, 556, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.86, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr117, $sgpr32, 552, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.87, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr118, $sgpr32, 548, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.88, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr119, $sgpr32, 544, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.89, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr120, $sgpr32, 540, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.90, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr121, $sgpr32, 536, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.91, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr122, $sgpr32, 532, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.92, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr123, $sgpr32, 528, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.93, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr124, $sgpr32, 524, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.94, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr125, $sgpr32, 520, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.95, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr126, $sgpr32, 516, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.96, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr127, $sgpr32, 512, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.97, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr128, $sgpr32, 508, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.98, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr129, $sgpr32, 504, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.99, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr130, $sgpr32, 500, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.100, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr131, $sgpr32, 496, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.101, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr132, $sgpr32, 492, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.102, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr133, $sgpr32, 488, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.103, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr134, $sgpr32, 484, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.104, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr135, $sgpr32, 480, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.105, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr136, $sgpr32, 476, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.106, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr137, $sgpr32, 472, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.107, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr138, $sgpr32, 468, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.108, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr139, $sgpr32, 464, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.109, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr140, $sgpr32, 460, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.110, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr141, $sgpr32, 456, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.111, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr142, $sgpr32, 452, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.112, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr143, $sgpr32, 448, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.113, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr144, $sgpr32, 444, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.114, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr145, $sgpr32, 440, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.115, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr146, $sgpr32, 436, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.116, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr147, $sgpr32, 432, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.117, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr148, $sgpr32, 428, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.118, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr149, $sgpr32, 424, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.119, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr150, $sgpr32, 420, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.120, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr151, $sgpr32, 416, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.121, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr152, $sgpr32, 412, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.122, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr153, $sgpr32, 408, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.123, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr154, $sgpr32, 404, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.124, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr155, $sgpr32, 400, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.125, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr156, $sgpr32, 396, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.126, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr157, $sgpr32, 392, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.127, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr158, $sgpr32, 388, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.128, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr159, $sgpr32, 384, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.129, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr160, $sgpr32, 380, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.130, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr161, $sgpr32, 376, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.131, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr162, $sgpr32, 372, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.132, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr163, $sgpr32, 368, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.133, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr164, $sgpr32, 364, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.134, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr165, $sgpr32, 360, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.135, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr166, $sgpr32, 356, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.136, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr167, $sgpr32, 352, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.137, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr168, $sgpr32, 348, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.138, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr169, $sgpr32, 344, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.139, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr170, $sgpr32, 340, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.140, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr171, $sgpr32, 336, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.141, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr172, $sgpr32, 332, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.142, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr173, $sgpr32, 328, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.143, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr174, $sgpr32, 324, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.144, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr175, $sgpr32, 320, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.145, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr176, $sgpr32, 316, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.146, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr177, $sgpr32, 312, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.147, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr178, $sgpr32, 308, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.148, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr179, $sgpr32, 304, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.149, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr180, $sgpr32, 300, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.150, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr181, $sgpr32, 296, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.151, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr182, $sgpr32, 292, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.152, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr183, $sgpr32, 288, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.153, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr184, $sgpr32, 284, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.154, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr185, $sgpr32, 280, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.155, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr186, $sgpr32, 276, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.156, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr187, $sgpr32, 272, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.157, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr188, $sgpr32, 268, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.158, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr189, $sgpr32, 264, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.159, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr190, $sgpr32, 260, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.160, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr191, $sgpr32, 256, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.161, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr192, $sgpr32, 252, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.162, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr193, $sgpr32, 248, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.163, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr194, $sgpr32, 244, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.164, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr195, $sgpr32, 240, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.165, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr196, $sgpr32, 236, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.166, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr197, $sgpr32, 232, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.167, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr198, $sgpr32, 228, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.168, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr199, $sgpr32, 224, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.169, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr200, $sgpr32, 220, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.170, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr201, $sgpr32, 216, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.171, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr202, $sgpr32, 212, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.172, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr203, $sgpr32, 208, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.173, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr204, $sgpr32, 204, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.174, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr205, $sgpr32, 200, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.175, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr206, $sgpr32, 196, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.176, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr207, $sgpr32, 192, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.177, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr208, $sgpr32, 188, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.178, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr209, $sgpr32, 184, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.179, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr210, $sgpr32, 180, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.180, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr211, $sgpr32, 176, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.181, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr212, $sgpr32, 172, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.182, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr213, $sgpr32, 168, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.183, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr214, $sgpr32, 164, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.184, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr215, $sgpr32, 160, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.185, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr216, $sgpr32, 156, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.186, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr217, $sgpr32, 152, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.187, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr218, $sgpr32, 148, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.188, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr219, $sgpr32, 144, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.189, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr220, $sgpr32, 140, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.190, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr221, $sgpr32, 136, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.191, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr222, $sgpr32, 132, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.192, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr223, $sgpr32, 128, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.193, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr224, $sgpr32, 124, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.194, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr225, $sgpr32, 120, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.195, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr226, $sgpr32, 116, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.196, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr227, $sgpr32, 112, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.197, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr228, $sgpr32, 108, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.198, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr229, $sgpr32, 104, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.199, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr230, $sgpr32, 100, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.200, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr231, $sgpr32, 96, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.201, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr232, $sgpr32, 92, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.202, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr233, $sgpr32, 88, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.203, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr234, $sgpr32, 84, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.204, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr235, $sgpr32, 80, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.205, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr236, $sgpr32, 76, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.206, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr237, $sgpr32, 72, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.207, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr238, $sgpr32, 68, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.208, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr239, $sgpr32, 64, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.209, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr240, $sgpr32, 60, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.210, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr241, $sgpr32, 56, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.211, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr242, $sgpr32, 52, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.212, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr243, $sgpr32, 48, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.213, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr244, $sgpr32, 44, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.214, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr245, $sgpr32, 40, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.215, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr246, $sgpr32, 36, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.216, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr247, $sgpr32, 32, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.217, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr248, $sgpr32, 28, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.218, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr249, $sgpr32, 24, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.219, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr250, $sgpr32, 20, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.220, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr251, $sgpr32, 16, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.221, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr252, $sgpr32, 12, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.222, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr253, $sgpr32, 8, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.223, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr254, $sgpr32, 4, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.224, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr255, $sgpr32, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.225, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   S_CMP_EQ_U32 0, 0, implicit-def $scc
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $vgpr40, $sgpr32, 704, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.226, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $vgpr40 = V_MOV_B32_e32 $sgpr32, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr40 = V_ADD_U32_e32 8904, $vgpr40, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD $agpr0, killed $vgpr40, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.1, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $vgpr40 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 704, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.226, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT: bb.1:
  ; GFX90A-FLATSCR-NEXT:   successors: %bb.2(0x80000000)
  ; GFX90A-FLATSCR-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT:   S_NOP 0
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT: bb.2:
  ; GFX90A-FLATSCR-NEXT:   liveins: $agpr0, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT:   $agpr255 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.225, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr254 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 4, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.224, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr253 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 8, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.223, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr252 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 12, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.222, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr251 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 16, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.221, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr250 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 20, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.220, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr249 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 24, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.219, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr248 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 28, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.218, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr247 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 32, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.217, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr246 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 36, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.216, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr245 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 40, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.215, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr244 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 44, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.214, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr243 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 48, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.213, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr242 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 52, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.212, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr241 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 56, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.211, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr240 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 60, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.210, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr239 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 64, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.209, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr238 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 68, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.208, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr237 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 72, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.207, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr236 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 76, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.206, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr235 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 80, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.205, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr234 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 84, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.204, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr233 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 88, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.203, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr232 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 92, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.202, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr231 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 96, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.201, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr230 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 100, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.200, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr229 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 104, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.199, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr228 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 108, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.198, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr227 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 112, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.197, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr226 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 116, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.196, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr225 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 120, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.195, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr224 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 124, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.194, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr223 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 128, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.193, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr222 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 132, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.192, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr221 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 136, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.191, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr220 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 140, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.190, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr219 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 144, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.189, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr218 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 148, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.188, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr217 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 152, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.187, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr216 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 156, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.186, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr215 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 160, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.185, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr214 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 164, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.184, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr213 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 168, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.183, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr212 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 172, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.182, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr211 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 176, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.181, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr210 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 180, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.180, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr209 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 184, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.179, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr208 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 188, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.178, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr207 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 192, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.177, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr206 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 196, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.176, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr205 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 200, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.175, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr204 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 204, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.174, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr203 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 208, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.173, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr202 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 212, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.172, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr201 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 216, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.171, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr200 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 220, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.170, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr199 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 224, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.169, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr198 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 228, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.168, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr197 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 232, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.167, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr196 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 236, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.166, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr195 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 240, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.165, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr194 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 244, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.164, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr193 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 248, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.163, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr192 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 252, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.162, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr191 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 256, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.161, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr190 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 260, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.160, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr189 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 264, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.159, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr188 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 268, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.158, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr187 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 272, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.157, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr186 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 276, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.156, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr185 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 280, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.155, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr184 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 284, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.154, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr183 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 288, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.153, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr182 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 292, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.152, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr181 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 296, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.151, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr180 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 300, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.150, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr179 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 304, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.149, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr178 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 308, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.148, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr177 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 312, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.147, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr176 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 316, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.146, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr175 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 320, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.145, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr174 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 324, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.144, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr173 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 328, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.143, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr172 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 332, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.142, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr171 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 336, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.141, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr170 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 340, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.140, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr169 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 344, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.139, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr168 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 348, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.138, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr167 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 352, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.137, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr166 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 356, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.136, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr165 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 360, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.135, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr164 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 364, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.134, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr163 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 368, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.133, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr162 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 372, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.132, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr161 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 376, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.131, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr160 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 380, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.130, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr159 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 384, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.129, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr158 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 388, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.128, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr157 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 392, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.127, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr156 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 396, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.126, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr155 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 400, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.125, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr154 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 404, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.124, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr153 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 408, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.123, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr152 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 412, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.122, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr151 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 416, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.121, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr150 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 420, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.120, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr149 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 424, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.119, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr148 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 428, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.118, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr147 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 432, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.117, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr146 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 436, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.116, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr145 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 440, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.115, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr144 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 444, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.114, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr143 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 448, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.113, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr142 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 452, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.112, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr141 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 456, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.111, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr140 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 460, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.110, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr139 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 464, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.109, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr138 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 468, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.108, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr137 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 472, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.107, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr136 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 476, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.106, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr135 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 480, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.105, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr134 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 484, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.104, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr133 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 488, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.103, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr132 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 492, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.102, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr131 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 496, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.101, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr130 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 500, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.100, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr129 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 504, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.99, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr128 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 508, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.98, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr127 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 512, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.97, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr126 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 516, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.96, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr125 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 520, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.95, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr124 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 524, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.94, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr123 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 528, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.93, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr122 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 532, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.92, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr121 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 536, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.91, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr120 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 540, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.90, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr119 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 544, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.89, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr118 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 548, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.88, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr117 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 552, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.87, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr116 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 556, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.86, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr115 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 560, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.85, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr114 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 564, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.84, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr113 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 568, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.83, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr112 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 572, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.82, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr111 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 576, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.81, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr110 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 580, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.80, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr109 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 584, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.79, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr108 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 588, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.78, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr107 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 592, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.77, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr106 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 596, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.76, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr105 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 600, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.75, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr104 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 604, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.74, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr103 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 608, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.73, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr102 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 612, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.72, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr101 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 616, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.71, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr100 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 620, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.70, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr99 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 624, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.69, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr98 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 628, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.68, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr97 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 632, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.67, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr96 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 636, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.66, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr95 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 640, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.65, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr94 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 644, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.64, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr93 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 648, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.63, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr92 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 652, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.62, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr91 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 656, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.61, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr90 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 660, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.60, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr89 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 664, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.59, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr88 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 668, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.58, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr87 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 672, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.57, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr86 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 676, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.56, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr85 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 680, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.55, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr84 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 684, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.54, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr83 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 688, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.53, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr82 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 692, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.52, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr81 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 696, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.51, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr80 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 700, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.50, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr79 = V_ACCVGPR_WRITE_B32_e64 $vgpr55, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr78 = V_ACCVGPR_WRITE_B32_e64 $vgpr54, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr77 = V_ACCVGPR_WRITE_B32_e64 $vgpr53, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr76 = V_ACCVGPR_WRITE_B32_e64 $vgpr52, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr75 = V_ACCVGPR_WRITE_B32_e64 $vgpr51, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr74 = V_ACCVGPR_WRITE_B32_e64 $vgpr50, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr73 = V_ACCVGPR_WRITE_B32_e64 $vgpr49, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr72 = V_ACCVGPR_WRITE_B32_e64 $vgpr48, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr71 = V_ACCVGPR_WRITE_B32_e64 $vgpr39, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr70 = V_ACCVGPR_WRITE_B32_e64 $vgpr38, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr69 = V_ACCVGPR_WRITE_B32_e64 $vgpr37, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr68 = V_ACCVGPR_WRITE_B32_e64 $vgpr36, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr67 = V_ACCVGPR_WRITE_B32_e64 $vgpr35, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr66 = V_ACCVGPR_WRITE_B32_e64 $vgpr34, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr65 = V_ACCVGPR_WRITE_B32_e64 $vgpr33, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr64 = V_ACCVGPR_WRITE_B32_e64 $vgpr32, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr63 = V_ACCVGPR_WRITE_B32_e64 $vgpr31, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr62 = V_ACCVGPR_WRITE_B32_e64 $vgpr30, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr61 = V_ACCVGPR_WRITE_B32_e64 $vgpr29, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr60 = V_ACCVGPR_WRITE_B32_e64 $vgpr28, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr59 = V_ACCVGPR_WRITE_B32_e64 $vgpr27, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr58 = V_ACCVGPR_WRITE_B32_e64 $vgpr26, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr57 = V_ACCVGPR_WRITE_B32_e64 $vgpr25, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr56 = V_ACCVGPR_WRITE_B32_e64 $vgpr24, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr55 = V_ACCVGPR_WRITE_B32_e64 $vgpr23, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr54 = V_ACCVGPR_WRITE_B32_e64 $vgpr22, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr53 = V_ACCVGPR_WRITE_B32_e64 $vgpr21, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr52 = V_ACCVGPR_WRITE_B32_e64 $vgpr20, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr51 = V_ACCVGPR_WRITE_B32_e64 $vgpr19, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr50 = V_ACCVGPR_WRITE_B32_e64 $vgpr18, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr49 = V_ACCVGPR_WRITE_B32_e64 $vgpr17, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr48 = V_ACCVGPR_WRITE_B32_e64 $vgpr16, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr47 = V_ACCVGPR_WRITE_B32_e64 $vgpr15, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr46 = V_ACCVGPR_WRITE_B32_e64 $vgpr14, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr45 = V_ACCVGPR_WRITE_B32_e64 $vgpr13, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr44 = V_ACCVGPR_WRITE_B32_e64 $vgpr12, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr43 = V_ACCVGPR_WRITE_B32_e64 $vgpr11, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr42 = V_ACCVGPR_WRITE_B32_e64 $vgpr10, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr41 = V_ACCVGPR_WRITE_B32_e64 $vgpr9, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr40 = V_ACCVGPR_WRITE_B32_e64 $vgpr8, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr39 = V_ACCVGPR_WRITE_B32_e64 $vgpr7, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr38 = V_ACCVGPR_WRITE_B32_e64 $vgpr6, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr37 = V_ACCVGPR_WRITE_B32_e64 $vgpr5, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr36 = V_ACCVGPR_WRITE_B32_e64 $vgpr4, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr35 = V_ACCVGPR_WRITE_B32_e64 $vgpr3, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr34 = V_ACCVGPR_WRITE_B32_e64 $vgpr2, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr33 = V_ACCVGPR_WRITE_B32_e64 $vgpr1, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr32 = V_ACCVGPR_WRITE_B32_e64 $vgpr0, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   S_ENDPGM 0, amdgpu_allvgprs
  bb.0:
    liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $agpr0

    S_CMP_EQ_U32 0, 0, implicit-def $scc
    SI_SPILL_A32_SAVE $agpr0, %stack.1, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.1, align 4, addrspace 5)
    S_CBRANCH_SCC1 %bb.2, implicit $scc

  bb.1:
    S_NOP 0

  bb.2:
    liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $agpr0
    S_ENDPGM 0, amdgpu_allvgprs
...

---
name: agpr64_save_clobber_scc
tracksRegLiveness: true
stack:
  - { id: 0, type: default, offset: 0, size: 8192, alignment: 8 }
  - { id: 1, type: spill-slot, offset: 0, size: 8192, alignment: 4 }

machineFunctionInfo:
  scratchRSrcReg:  $sgpr0_sgpr1_sgpr2_sgpr3
  frameOffsetReg:  $sgpr33
  stackPtrOffsetReg:  $sgpr32

body:             |
  ; GFX908-LABEL: name: agpr64_save_clobber_scc
  ; GFX908: bb.0:
  ; GFX908-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GFX908-NEXT:   liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $agpr0_agpr1
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT:   S_CMP_EQ_U32 0, 0, implicit-def $scc
  ; GFX908-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $vgpr1, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.2, addrspace 5)
  ; GFX908-NEXT:   $vgpr1 = V_MOV_B32_e32 8200, implicit $exec
  ; GFX908-NEXT:   $vgpr0 = V_ACCVGPR_READ_B32_e64 $agpr0, implicit $exec, implicit-def $agpr0_agpr1, implicit $agpr0_agpr1
  ; GFX908-NEXT:   BUFFER_STORE_DWORD_OFFEN $vgpr0, $vgpr1, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec, implicit $agpr0_agpr1 :: ("amdgpu-non-volatile" store (s32) into %stack.1, addrspace 5)
  ; GFX908-NEXT:   $vgpr0 = V_ACCVGPR_READ_B32_e64 $agpr1, implicit $exec, implicit $agpr0_agpr1
  ; GFX908-NEXT:   BUFFER_STORE_DWORD_OFFEN $vgpr0, $vgpr1, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 4, 0, 0, implicit $exec, implicit $agpr0_agpr1 :: ("amdgpu-non-volatile" store (s32) into %stack.1 + 4, addrspace 5)
  ; GFX908-NEXT:   $vgpr1 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.2, addrspace 5)
  ; GFX908-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT: bb.1:
  ; GFX908-NEXT:   successors: %bb.2(0x80000000)
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT:   S_NOP 0
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT: bb.2:
  ; GFX908-NEXT:   liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $agpr0_agpr1
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT:   S_ENDPGM 0, amdgpu_allvgprs
  ;
  ; GFX90A-LABEL: name: agpr64_save_clobber_scc
  ; GFX90A: bb.0:
  ; GFX90A-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GFX90A-NEXT:   liveins: $agpr32, $agpr33, $agpr34, $agpr35, $agpr36, $agpr37, $agpr38, $agpr39, $agpr40, $agpr41, $agpr42, $agpr43, $agpr44, $agpr45, $agpr46, $agpr47, $agpr48, $agpr49, $agpr50, $agpr51, $agpr52, $agpr53, $agpr54, $agpr55, $agpr56, $agpr57, $agpr58, $agpr59, $agpr60, $agpr61, $agpr62, $agpr63, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55, $agpr0_agpr1, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   $vgpr0 = V_ACCVGPR_READ_B32_e64 killed $agpr32, implicit $exec
  ; GFX90A-NEXT:   $vgpr1 = V_ACCVGPR_READ_B32_e64 killed $agpr33, implicit $exec
  ; GFX90A-NEXT:   $vgpr2 = V_ACCVGPR_READ_B32_e64 killed $agpr34, implicit $exec
  ; GFX90A-NEXT:   $vgpr3 = V_ACCVGPR_READ_B32_e64 killed $agpr35, implicit $exec
  ; GFX90A-NEXT:   $vgpr4 = V_ACCVGPR_READ_B32_e64 killed $agpr36, implicit $exec
  ; GFX90A-NEXT:   $vgpr5 = V_ACCVGPR_READ_B32_e64 killed $agpr37, implicit $exec
  ; GFX90A-NEXT:   $vgpr6 = V_ACCVGPR_READ_B32_e64 killed $agpr38, implicit $exec
  ; GFX90A-NEXT:   $vgpr7 = V_ACCVGPR_READ_B32_e64 killed $agpr39, implicit $exec
  ; GFX90A-NEXT:   $vgpr8 = V_ACCVGPR_READ_B32_e64 killed $agpr40, implicit $exec
  ; GFX90A-NEXT:   $vgpr9 = V_ACCVGPR_READ_B32_e64 killed $agpr41, implicit $exec
  ; GFX90A-NEXT:   $vgpr10 = V_ACCVGPR_READ_B32_e64 killed $agpr42, implicit $exec
  ; GFX90A-NEXT:   $vgpr11 = V_ACCVGPR_READ_B32_e64 killed $agpr43, implicit $exec
  ; GFX90A-NEXT:   $vgpr12 = V_ACCVGPR_READ_B32_e64 killed $agpr44, implicit $exec
  ; GFX90A-NEXT:   $vgpr13 = V_ACCVGPR_READ_B32_e64 killed $agpr45, implicit $exec
  ; GFX90A-NEXT:   $vgpr14 = V_ACCVGPR_READ_B32_e64 killed $agpr46, implicit $exec
  ; GFX90A-NEXT:   $vgpr15 = V_ACCVGPR_READ_B32_e64 killed $agpr47, implicit $exec
  ; GFX90A-NEXT:   $vgpr16 = V_ACCVGPR_READ_B32_e64 killed $agpr48, implicit $exec
  ; GFX90A-NEXT:   $vgpr17 = V_ACCVGPR_READ_B32_e64 killed $agpr49, implicit $exec
  ; GFX90A-NEXT:   $vgpr18 = V_ACCVGPR_READ_B32_e64 killed $agpr50, implicit $exec
  ; GFX90A-NEXT:   $vgpr19 = V_ACCVGPR_READ_B32_e64 killed $agpr51, implicit $exec
  ; GFX90A-NEXT:   $vgpr20 = V_ACCVGPR_READ_B32_e64 killed $agpr52, implicit $exec
  ; GFX90A-NEXT:   $vgpr21 = V_ACCVGPR_READ_B32_e64 killed $agpr53, implicit $exec
  ; GFX90A-NEXT:   $vgpr22 = V_ACCVGPR_READ_B32_e64 killed $agpr54, implicit $exec
  ; GFX90A-NEXT:   $vgpr23 = V_ACCVGPR_READ_B32_e64 killed $agpr55, implicit $exec
  ; GFX90A-NEXT:   $vgpr24 = V_ACCVGPR_READ_B32_e64 killed $agpr56, implicit $exec
  ; GFX90A-NEXT:   $vgpr25 = V_ACCVGPR_READ_B32_e64 killed $agpr57, implicit $exec
  ; GFX90A-NEXT:   $vgpr26 = V_ACCVGPR_READ_B32_e64 killed $agpr58, implicit $exec
  ; GFX90A-NEXT:   $vgpr27 = V_ACCVGPR_READ_B32_e64 killed $agpr59, implicit $exec
  ; GFX90A-NEXT:   $vgpr28 = V_ACCVGPR_READ_B32_e64 killed $agpr60, implicit $exec
  ; GFX90A-NEXT:   $vgpr29 = V_ACCVGPR_READ_B32_e64 killed $agpr61, implicit $exec
  ; GFX90A-NEXT:   $vgpr30 = V_ACCVGPR_READ_B32_e64 killed $agpr62, implicit $exec
  ; GFX90A-NEXT:   $vgpr31 = V_ACCVGPR_READ_B32_e64 killed $agpr63, implicit $exec
  ; GFX90A-NEXT:   $vgpr32 = V_ACCVGPR_READ_B32_e64 killed $agpr64, implicit $exec
  ; GFX90A-NEXT:   $vgpr33 = V_ACCVGPR_READ_B32_e64 killed $agpr65, implicit $exec
  ; GFX90A-NEXT:   $vgpr34 = V_ACCVGPR_READ_B32_e64 killed $agpr66, implicit $exec
  ; GFX90A-NEXT:   $vgpr35 = V_ACCVGPR_READ_B32_e64 killed $agpr67, implicit $exec
  ; GFX90A-NEXT:   $vgpr36 = V_ACCVGPR_READ_B32_e64 killed $agpr68, implicit $exec
  ; GFX90A-NEXT:   $vgpr37 = V_ACCVGPR_READ_B32_e64 killed $agpr69, implicit $exec
  ; GFX90A-NEXT:   $vgpr38 = V_ACCVGPR_READ_B32_e64 killed $agpr70, implicit $exec
  ; GFX90A-NEXT:   $vgpr39 = V_ACCVGPR_READ_B32_e64 killed $agpr71, implicit $exec
  ; GFX90A-NEXT:   $vgpr48 = V_ACCVGPR_READ_B32_e64 killed $agpr72, implicit $exec
  ; GFX90A-NEXT:   $vgpr49 = V_ACCVGPR_READ_B32_e64 killed $agpr73, implicit $exec
  ; GFX90A-NEXT:   $vgpr50 = V_ACCVGPR_READ_B32_e64 killed $agpr74, implicit $exec
  ; GFX90A-NEXT:   $vgpr51 = V_ACCVGPR_READ_B32_e64 killed $agpr75, implicit $exec
  ; GFX90A-NEXT:   $vgpr52 = V_ACCVGPR_READ_B32_e64 killed $agpr76, implicit $exec
  ; GFX90A-NEXT:   $vgpr53 = V_ACCVGPR_READ_B32_e64 killed $agpr77, implicit $exec
  ; GFX90A-NEXT:   $vgpr54 = V_ACCVGPR_READ_B32_e64 killed $agpr78, implicit $exec
  ; GFX90A-NEXT:   $vgpr55 = V_ACCVGPR_READ_B32_e64 killed $agpr79, implicit $exec
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr80, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 700, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.50, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr81, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 696, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.51, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr82, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 692, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.52, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr83, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 688, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.53, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr84, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 684, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.54, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr85, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 680, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.55, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr86, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 676, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.56, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr87, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 672, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.57, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr88, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 668, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.58, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr89, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 664, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.59, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr90, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 660, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.60, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr91, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 656, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.61, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr92, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 652, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.62, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr93, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 648, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.63, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr94, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 644, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.64, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr95, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 640, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.65, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr96, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 636, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.66, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr97, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 632, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.67, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr98, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 628, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.68, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr99, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 624, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.69, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr100, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 620, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.70, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr101, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 616, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.71, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr102, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 612, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.72, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr103, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 608, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.73, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr104, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 604, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.74, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr105, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 600, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.75, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr106, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 596, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.76, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr107, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 592, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.77, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr108, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 588, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.78, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr109, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 584, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.79, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr110, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 580, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.80, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr111, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 576, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.81, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr112, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 572, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.82, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr113, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 568, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.83, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr114, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 564, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.84, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr115, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 560, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.85, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr116, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 556, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.86, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr117, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 552, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.87, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr118, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 548, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.88, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr119, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 544, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.89, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr120, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 540, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.90, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr121, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 536, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.91, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr122, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 532, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.92, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr123, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 528, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.93, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr124, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 524, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.94, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr125, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 520, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.95, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr126, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 516, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.96, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr127, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 512, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.97, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr128, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 508, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.98, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr129, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 504, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.99, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr130, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 500, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.100, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr131, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 496, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.101, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr132, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 492, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.102, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr133, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 488, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.103, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr134, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 484, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.104, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr135, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 480, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.105, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr136, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 476, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.106, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr137, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 472, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.107, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr138, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 468, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.108, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr139, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 464, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.109, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr140, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 460, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.110, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr141, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 456, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.111, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr142, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 452, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.112, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr143, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 448, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.113, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr144, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 444, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.114, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr145, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 440, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.115, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr146, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 436, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.116, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr147, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 432, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.117, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr148, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 428, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.118, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr149, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 424, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.119, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr150, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 420, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.120, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr151, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 416, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.121, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr152, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 412, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.122, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr153, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 408, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.123, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr154, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 404, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.124, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr155, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 400, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.125, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr156, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 396, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.126, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr157, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 392, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.127, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr158, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 388, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.128, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr159, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 384, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.129, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr160, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 380, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.130, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr161, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 376, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.131, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr162, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 372, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.132, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr163, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 368, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.133, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr164, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 364, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.134, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr165, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 360, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.135, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr166, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 356, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.136, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr167, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 352, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.137, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr168, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 348, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.138, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr169, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 344, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.139, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr170, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 340, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.140, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr171, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 336, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.141, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr172, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 332, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.142, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr173, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 328, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.143, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr174, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 324, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.144, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr175, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 320, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.145, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr176, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 316, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.146, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr177, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 312, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.147, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr178, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 308, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.148, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr179, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 304, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.149, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr180, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 300, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.150, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr181, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 296, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.151, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr182, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 292, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.152, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr183, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 288, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.153, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr184, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 284, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.154, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr185, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 280, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.155, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr186, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 276, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.156, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr187, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 272, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.157, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr188, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 268, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.158, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr189, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 264, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.159, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr190, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 260, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.160, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr191, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 256, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.161, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr192, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 252, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.162, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr193, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 248, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.163, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr194, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 244, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.164, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr195, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 240, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.165, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr196, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 236, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.166, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr197, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 232, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.167, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr198, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 228, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.168, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr199, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 224, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.169, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr200, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 220, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.170, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr201, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 216, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.171, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr202, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 212, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.172, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr203, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 208, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.173, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr204, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 204, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.174, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr205, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 200, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.175, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr206, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 196, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.176, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr207, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 192, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.177, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr208, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 188, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.178, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr209, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 184, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.179, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr210, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 180, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.180, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr211, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 176, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.181, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr212, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 172, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.182, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr213, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 168, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.183, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr214, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 164, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.184, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr215, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 160, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.185, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr216, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 156, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.186, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr217, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 152, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.187, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr218, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 148, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.188, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr219, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 144, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.189, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr220, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 140, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.190, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr221, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 136, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.191, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr222, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 132, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.192, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr223, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 128, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.193, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr224, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 124, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.194, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr225, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 120, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.195, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr226, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 116, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.196, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr227, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 112, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.197, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr228, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 108, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.198, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr229, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 104, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.199, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr230, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 100, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.200, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr231, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 96, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.201, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr232, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 92, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.202, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr233, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 88, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.203, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr234, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 84, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.204, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr235, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 80, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.205, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr236, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 76, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.206, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr237, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 72, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.207, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr238, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 68, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.208, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr239, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 64, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.209, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr240, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 60, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.210, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr241, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 56, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.211, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr242, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 52, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.212, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr243, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 48, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.213, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr244, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 44, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.214, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr245, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 40, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.215, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr246, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 36, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.216, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr247, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 32, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.217, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr248, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 28, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.218, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr249, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 24, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.219, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr250, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 20, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.220, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr251, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 16, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.221, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr252, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 12, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.222, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr253, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 8, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.223, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr254, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 4, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.224, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr255, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.225, addrspace 5)
  ; GFX90A-NEXT:   S_CMP_EQ_U32 0, 0, implicit-def $scc
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $vgpr40, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 704, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.226, addrspace 5)
  ; GFX90A-NEXT:   $vgpr40 = V_MOV_B32_e32 8904, implicit $exec
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFEN $agpr0, $vgpr40, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec, implicit-def $agpr0_agpr1, implicit $agpr0_agpr1 :: ("amdgpu-non-volatile" store (s32) into %stack.1, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFEN $agpr1, killed $vgpr40, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 4, 0, 0, implicit $exec, implicit $agpr0_agpr1 :: ("amdgpu-non-volatile" store (s32) into %stack.1 + 4, addrspace 5)
  ; GFX90A-NEXT:   $vgpr40 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 704, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.226, addrspace 5)
  ; GFX90A-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT: bb.1:
  ; GFX90A-NEXT:   successors: %bb.2(0x80000000)
  ; GFX90A-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   S_NOP 0
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT: bb.2:
  ; GFX90A-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55, $agpr0_agpr1, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   $agpr255 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.225, addrspace 5)
  ; GFX90A-NEXT:   $agpr254 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 4, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.224, addrspace 5)
  ; GFX90A-NEXT:   $agpr253 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 8, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.223, addrspace 5)
  ; GFX90A-NEXT:   $agpr252 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 12, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.222, addrspace 5)
  ; GFX90A-NEXT:   $agpr251 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 16, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.221, addrspace 5)
  ; GFX90A-NEXT:   $agpr250 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 20, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.220, addrspace 5)
  ; GFX90A-NEXT:   $agpr249 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 24, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.219, addrspace 5)
  ; GFX90A-NEXT:   $agpr248 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 28, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.218, addrspace 5)
  ; GFX90A-NEXT:   $agpr247 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 32, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.217, addrspace 5)
  ; GFX90A-NEXT:   $agpr246 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 36, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.216, addrspace 5)
  ; GFX90A-NEXT:   $agpr245 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 40, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.215, addrspace 5)
  ; GFX90A-NEXT:   $agpr244 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 44, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.214, addrspace 5)
  ; GFX90A-NEXT:   $agpr243 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 48, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.213, addrspace 5)
  ; GFX90A-NEXT:   $agpr242 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 52, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.212, addrspace 5)
  ; GFX90A-NEXT:   $agpr241 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 56, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.211, addrspace 5)
  ; GFX90A-NEXT:   $agpr240 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 60, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.210, addrspace 5)
  ; GFX90A-NEXT:   $agpr239 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 64, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.209, addrspace 5)
  ; GFX90A-NEXT:   $agpr238 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 68, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.208, addrspace 5)
  ; GFX90A-NEXT:   $agpr237 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 72, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.207, addrspace 5)
  ; GFX90A-NEXT:   $agpr236 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 76, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.206, addrspace 5)
  ; GFX90A-NEXT:   $agpr235 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 80, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.205, addrspace 5)
  ; GFX90A-NEXT:   $agpr234 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 84, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.204, addrspace 5)
  ; GFX90A-NEXT:   $agpr233 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 88, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.203, addrspace 5)
  ; GFX90A-NEXT:   $agpr232 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 92, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.202, addrspace 5)
  ; GFX90A-NEXT:   $agpr231 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 96, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.201, addrspace 5)
  ; GFX90A-NEXT:   $agpr230 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 100, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.200, addrspace 5)
  ; GFX90A-NEXT:   $agpr229 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 104, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.199, addrspace 5)
  ; GFX90A-NEXT:   $agpr228 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 108, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.198, addrspace 5)
  ; GFX90A-NEXT:   $agpr227 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 112, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.197, addrspace 5)
  ; GFX90A-NEXT:   $agpr226 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 116, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.196, addrspace 5)
  ; GFX90A-NEXT:   $agpr225 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 120, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.195, addrspace 5)
  ; GFX90A-NEXT:   $agpr224 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 124, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.194, addrspace 5)
  ; GFX90A-NEXT:   $agpr223 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 128, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.193, addrspace 5)
  ; GFX90A-NEXT:   $agpr222 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 132, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.192, addrspace 5)
  ; GFX90A-NEXT:   $agpr221 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 136, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.191, addrspace 5)
  ; GFX90A-NEXT:   $agpr220 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 140, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.190, addrspace 5)
  ; GFX90A-NEXT:   $agpr219 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 144, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.189, addrspace 5)
  ; GFX90A-NEXT:   $agpr218 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 148, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.188, addrspace 5)
  ; GFX90A-NEXT:   $agpr217 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 152, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.187, addrspace 5)
  ; GFX90A-NEXT:   $agpr216 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 156, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.186, addrspace 5)
  ; GFX90A-NEXT:   $agpr215 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 160, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.185, addrspace 5)
  ; GFX90A-NEXT:   $agpr214 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 164, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.184, addrspace 5)
  ; GFX90A-NEXT:   $agpr213 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 168, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.183, addrspace 5)
  ; GFX90A-NEXT:   $agpr212 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 172, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.182, addrspace 5)
  ; GFX90A-NEXT:   $agpr211 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 176, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.181, addrspace 5)
  ; GFX90A-NEXT:   $agpr210 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 180, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.180, addrspace 5)
  ; GFX90A-NEXT:   $agpr209 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 184, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.179, addrspace 5)
  ; GFX90A-NEXT:   $agpr208 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 188, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.178, addrspace 5)
  ; GFX90A-NEXT:   $agpr207 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 192, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.177, addrspace 5)
  ; GFX90A-NEXT:   $agpr206 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 196, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.176, addrspace 5)
  ; GFX90A-NEXT:   $agpr205 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 200, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.175, addrspace 5)
  ; GFX90A-NEXT:   $agpr204 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 204, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.174, addrspace 5)
  ; GFX90A-NEXT:   $agpr203 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 208, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.173, addrspace 5)
  ; GFX90A-NEXT:   $agpr202 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 212, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.172, addrspace 5)
  ; GFX90A-NEXT:   $agpr201 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 216, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.171, addrspace 5)
  ; GFX90A-NEXT:   $agpr200 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 220, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.170, addrspace 5)
  ; GFX90A-NEXT:   $agpr199 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 224, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.169, addrspace 5)
  ; GFX90A-NEXT:   $agpr198 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 228, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.168, addrspace 5)
  ; GFX90A-NEXT:   $agpr197 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 232, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.167, addrspace 5)
  ; GFX90A-NEXT:   $agpr196 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 236, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.166, addrspace 5)
  ; GFX90A-NEXT:   $agpr195 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 240, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.165, addrspace 5)
  ; GFX90A-NEXT:   $agpr194 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 244, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.164, addrspace 5)
  ; GFX90A-NEXT:   $agpr193 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 248, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.163, addrspace 5)
  ; GFX90A-NEXT:   $agpr192 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 252, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.162, addrspace 5)
  ; GFX90A-NEXT:   $agpr191 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 256, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.161, addrspace 5)
  ; GFX90A-NEXT:   $agpr190 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 260, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.160, addrspace 5)
  ; GFX90A-NEXT:   $agpr189 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 264, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.159, addrspace 5)
  ; GFX90A-NEXT:   $agpr188 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 268, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.158, addrspace 5)
  ; GFX90A-NEXT:   $agpr187 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 272, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.157, addrspace 5)
  ; GFX90A-NEXT:   $agpr186 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 276, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.156, addrspace 5)
  ; GFX90A-NEXT:   $agpr185 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 280, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.155, addrspace 5)
  ; GFX90A-NEXT:   $agpr184 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 284, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.154, addrspace 5)
  ; GFX90A-NEXT:   $agpr183 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 288, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.153, addrspace 5)
  ; GFX90A-NEXT:   $agpr182 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 292, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.152, addrspace 5)
  ; GFX90A-NEXT:   $agpr181 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 296, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.151, addrspace 5)
  ; GFX90A-NEXT:   $agpr180 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 300, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.150, addrspace 5)
  ; GFX90A-NEXT:   $agpr179 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 304, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.149, addrspace 5)
  ; GFX90A-NEXT:   $agpr178 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 308, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.148, addrspace 5)
  ; GFX90A-NEXT:   $agpr177 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 312, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.147, addrspace 5)
  ; GFX90A-NEXT:   $agpr176 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 316, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.146, addrspace 5)
  ; GFX90A-NEXT:   $agpr175 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 320, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.145, addrspace 5)
  ; GFX90A-NEXT:   $agpr174 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 324, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.144, addrspace 5)
  ; GFX90A-NEXT:   $agpr173 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 328, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.143, addrspace 5)
  ; GFX90A-NEXT:   $agpr172 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 332, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.142, addrspace 5)
  ; GFX90A-NEXT:   $agpr171 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 336, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.141, addrspace 5)
  ; GFX90A-NEXT:   $agpr170 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 340, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.140, addrspace 5)
  ; GFX90A-NEXT:   $agpr169 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 344, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.139, addrspace 5)
  ; GFX90A-NEXT:   $agpr168 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 348, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.138, addrspace 5)
  ; GFX90A-NEXT:   $agpr167 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 352, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.137, addrspace 5)
  ; GFX90A-NEXT:   $agpr166 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 356, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.136, addrspace 5)
  ; GFX90A-NEXT:   $agpr165 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 360, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.135, addrspace 5)
  ; GFX90A-NEXT:   $agpr164 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 364, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.134, addrspace 5)
  ; GFX90A-NEXT:   $agpr163 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 368, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.133, addrspace 5)
  ; GFX90A-NEXT:   $agpr162 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 372, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.132, addrspace 5)
  ; GFX90A-NEXT:   $agpr161 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 376, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.131, addrspace 5)
  ; GFX90A-NEXT:   $agpr160 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 380, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.130, addrspace 5)
  ; GFX90A-NEXT:   $agpr159 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 384, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.129, addrspace 5)
  ; GFX90A-NEXT:   $agpr158 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 388, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.128, addrspace 5)
  ; GFX90A-NEXT:   $agpr157 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 392, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.127, addrspace 5)
  ; GFX90A-NEXT:   $agpr156 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 396, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.126, addrspace 5)
  ; GFX90A-NEXT:   $agpr155 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 400, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.125, addrspace 5)
  ; GFX90A-NEXT:   $agpr154 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 404, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.124, addrspace 5)
  ; GFX90A-NEXT:   $agpr153 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 408, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.123, addrspace 5)
  ; GFX90A-NEXT:   $agpr152 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 412, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.122, addrspace 5)
  ; GFX90A-NEXT:   $agpr151 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 416, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.121, addrspace 5)
  ; GFX90A-NEXT:   $agpr150 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 420, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.120, addrspace 5)
  ; GFX90A-NEXT:   $agpr149 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 424, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.119, addrspace 5)
  ; GFX90A-NEXT:   $agpr148 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 428, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.118, addrspace 5)
  ; GFX90A-NEXT:   $agpr147 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 432, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.117, addrspace 5)
  ; GFX90A-NEXT:   $agpr146 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 436, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.116, addrspace 5)
  ; GFX90A-NEXT:   $agpr145 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 440, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.115, addrspace 5)
  ; GFX90A-NEXT:   $agpr144 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 444, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.114, addrspace 5)
  ; GFX90A-NEXT:   $agpr143 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 448, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.113, addrspace 5)
  ; GFX90A-NEXT:   $agpr142 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 452, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.112, addrspace 5)
  ; GFX90A-NEXT:   $agpr141 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 456, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.111, addrspace 5)
  ; GFX90A-NEXT:   $agpr140 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 460, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.110, addrspace 5)
  ; GFX90A-NEXT:   $agpr139 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 464, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.109, addrspace 5)
  ; GFX90A-NEXT:   $agpr138 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 468, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.108, addrspace 5)
  ; GFX90A-NEXT:   $agpr137 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 472, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.107, addrspace 5)
  ; GFX90A-NEXT:   $agpr136 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 476, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.106, addrspace 5)
  ; GFX90A-NEXT:   $agpr135 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 480, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.105, addrspace 5)
  ; GFX90A-NEXT:   $agpr134 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 484, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.104, addrspace 5)
  ; GFX90A-NEXT:   $agpr133 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 488, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.103, addrspace 5)
  ; GFX90A-NEXT:   $agpr132 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 492, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.102, addrspace 5)
  ; GFX90A-NEXT:   $agpr131 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 496, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.101, addrspace 5)
  ; GFX90A-NEXT:   $agpr130 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 500, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.100, addrspace 5)
  ; GFX90A-NEXT:   $agpr129 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 504, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.99, addrspace 5)
  ; GFX90A-NEXT:   $agpr128 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 508, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.98, addrspace 5)
  ; GFX90A-NEXT:   $agpr127 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 512, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.97, addrspace 5)
  ; GFX90A-NEXT:   $agpr126 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 516, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.96, addrspace 5)
  ; GFX90A-NEXT:   $agpr125 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 520, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.95, addrspace 5)
  ; GFX90A-NEXT:   $agpr124 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 524, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.94, addrspace 5)
  ; GFX90A-NEXT:   $agpr123 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 528, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.93, addrspace 5)
  ; GFX90A-NEXT:   $agpr122 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 532, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.92, addrspace 5)
  ; GFX90A-NEXT:   $agpr121 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 536, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.91, addrspace 5)
  ; GFX90A-NEXT:   $agpr120 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 540, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.90, addrspace 5)
  ; GFX90A-NEXT:   $agpr119 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 544, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.89, addrspace 5)
  ; GFX90A-NEXT:   $agpr118 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 548, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.88, addrspace 5)
  ; GFX90A-NEXT:   $agpr117 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 552, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.87, addrspace 5)
  ; GFX90A-NEXT:   $agpr116 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 556, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.86, addrspace 5)
  ; GFX90A-NEXT:   $agpr115 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 560, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.85, addrspace 5)
  ; GFX90A-NEXT:   $agpr114 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 564, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.84, addrspace 5)
  ; GFX90A-NEXT:   $agpr113 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 568, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.83, addrspace 5)
  ; GFX90A-NEXT:   $agpr112 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 572, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.82, addrspace 5)
  ; GFX90A-NEXT:   $agpr111 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 576, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.81, addrspace 5)
  ; GFX90A-NEXT:   $agpr110 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 580, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.80, addrspace 5)
  ; GFX90A-NEXT:   $agpr109 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 584, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.79, addrspace 5)
  ; GFX90A-NEXT:   $agpr108 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 588, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.78, addrspace 5)
  ; GFX90A-NEXT:   $agpr107 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 592, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.77, addrspace 5)
  ; GFX90A-NEXT:   $agpr106 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 596, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.76, addrspace 5)
  ; GFX90A-NEXT:   $agpr105 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 600, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.75, addrspace 5)
  ; GFX90A-NEXT:   $agpr104 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 604, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.74, addrspace 5)
  ; GFX90A-NEXT:   $agpr103 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 608, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.73, addrspace 5)
  ; GFX90A-NEXT:   $agpr102 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 612, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.72, addrspace 5)
  ; GFX90A-NEXT:   $agpr101 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 616, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.71, addrspace 5)
  ; GFX90A-NEXT:   $agpr100 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 620, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.70, addrspace 5)
  ; GFX90A-NEXT:   $agpr99 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 624, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.69, addrspace 5)
  ; GFX90A-NEXT:   $agpr98 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 628, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.68, addrspace 5)
  ; GFX90A-NEXT:   $agpr97 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 632, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.67, addrspace 5)
  ; GFX90A-NEXT:   $agpr96 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 636, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.66, addrspace 5)
  ; GFX90A-NEXT:   $agpr95 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 640, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.65, addrspace 5)
  ; GFX90A-NEXT:   $agpr94 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 644, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.64, addrspace 5)
  ; GFX90A-NEXT:   $agpr93 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 648, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.63, addrspace 5)
  ; GFX90A-NEXT:   $agpr92 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 652, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.62, addrspace 5)
  ; GFX90A-NEXT:   $agpr91 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 656, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.61, addrspace 5)
  ; GFX90A-NEXT:   $agpr90 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 660, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.60, addrspace 5)
  ; GFX90A-NEXT:   $agpr89 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 664, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.59, addrspace 5)
  ; GFX90A-NEXT:   $agpr88 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 668, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.58, addrspace 5)
  ; GFX90A-NEXT:   $agpr87 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 672, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.57, addrspace 5)
  ; GFX90A-NEXT:   $agpr86 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 676, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.56, addrspace 5)
  ; GFX90A-NEXT:   $agpr85 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 680, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.55, addrspace 5)
  ; GFX90A-NEXT:   $agpr84 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 684, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.54, addrspace 5)
  ; GFX90A-NEXT:   $agpr83 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 688, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.53, addrspace 5)
  ; GFX90A-NEXT:   $agpr82 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 692, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.52, addrspace 5)
  ; GFX90A-NEXT:   $agpr81 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 696, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.51, addrspace 5)
  ; GFX90A-NEXT:   $agpr80 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 700, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.50, addrspace 5)
  ; GFX90A-NEXT:   $agpr79 = V_ACCVGPR_WRITE_B32_e64 $vgpr55, implicit $exec
  ; GFX90A-NEXT:   $agpr78 = V_ACCVGPR_WRITE_B32_e64 $vgpr54, implicit $exec
  ; GFX90A-NEXT:   $agpr77 = V_ACCVGPR_WRITE_B32_e64 $vgpr53, implicit $exec
  ; GFX90A-NEXT:   $agpr76 = V_ACCVGPR_WRITE_B32_e64 $vgpr52, implicit $exec
  ; GFX90A-NEXT:   $agpr75 = V_ACCVGPR_WRITE_B32_e64 $vgpr51, implicit $exec
  ; GFX90A-NEXT:   $agpr74 = V_ACCVGPR_WRITE_B32_e64 $vgpr50, implicit $exec
  ; GFX90A-NEXT:   $agpr73 = V_ACCVGPR_WRITE_B32_e64 $vgpr49, implicit $exec
  ; GFX90A-NEXT:   $agpr72 = V_ACCVGPR_WRITE_B32_e64 $vgpr48, implicit $exec
  ; GFX90A-NEXT:   $agpr71 = V_ACCVGPR_WRITE_B32_e64 $vgpr39, implicit $exec
  ; GFX90A-NEXT:   $agpr70 = V_ACCVGPR_WRITE_B32_e64 $vgpr38, implicit $exec
  ; GFX90A-NEXT:   $agpr69 = V_ACCVGPR_WRITE_B32_e64 $vgpr37, implicit $exec
  ; GFX90A-NEXT:   $agpr68 = V_ACCVGPR_WRITE_B32_e64 $vgpr36, implicit $exec
  ; GFX90A-NEXT:   $agpr67 = V_ACCVGPR_WRITE_B32_e64 $vgpr35, implicit $exec
  ; GFX90A-NEXT:   $agpr66 = V_ACCVGPR_WRITE_B32_e64 $vgpr34, implicit $exec
  ; GFX90A-NEXT:   $agpr65 = V_ACCVGPR_WRITE_B32_e64 $vgpr33, implicit $exec
  ; GFX90A-NEXT:   $agpr64 = V_ACCVGPR_WRITE_B32_e64 $vgpr32, implicit $exec
  ; GFX90A-NEXT:   $agpr63 = V_ACCVGPR_WRITE_B32_e64 $vgpr31, implicit $exec
  ; GFX90A-NEXT:   $agpr62 = V_ACCVGPR_WRITE_B32_e64 $vgpr30, implicit $exec
  ; GFX90A-NEXT:   $agpr61 = V_ACCVGPR_WRITE_B32_e64 $vgpr29, implicit $exec
  ; GFX90A-NEXT:   $agpr60 = V_ACCVGPR_WRITE_B32_e64 $vgpr28, implicit $exec
  ; GFX90A-NEXT:   $agpr59 = V_ACCVGPR_WRITE_B32_e64 $vgpr27, implicit $exec
  ; GFX90A-NEXT:   $agpr58 = V_ACCVGPR_WRITE_B32_e64 $vgpr26, implicit $exec
  ; GFX90A-NEXT:   $agpr57 = V_ACCVGPR_WRITE_B32_e64 $vgpr25, implicit $exec
  ; GFX90A-NEXT:   $agpr56 = V_ACCVGPR_WRITE_B32_e64 $vgpr24, implicit $exec
  ; GFX90A-NEXT:   $agpr55 = V_ACCVGPR_WRITE_B32_e64 $vgpr23, implicit $exec
  ; GFX90A-NEXT:   $agpr54 = V_ACCVGPR_WRITE_B32_e64 $vgpr22, implicit $exec
  ; GFX90A-NEXT:   $agpr53 = V_ACCVGPR_WRITE_B32_e64 $vgpr21, implicit $exec
  ; GFX90A-NEXT:   $agpr52 = V_ACCVGPR_WRITE_B32_e64 $vgpr20, implicit $exec
  ; GFX90A-NEXT:   $agpr51 = V_ACCVGPR_WRITE_B32_e64 $vgpr19, implicit $exec
  ; GFX90A-NEXT:   $agpr50 = V_ACCVGPR_WRITE_B32_e64 $vgpr18, implicit $exec
  ; GFX90A-NEXT:   $agpr49 = V_ACCVGPR_WRITE_B32_e64 $vgpr17, implicit $exec
  ; GFX90A-NEXT:   $agpr48 = V_ACCVGPR_WRITE_B32_e64 $vgpr16, implicit $exec
  ; GFX90A-NEXT:   $agpr47 = V_ACCVGPR_WRITE_B32_e64 $vgpr15, implicit $exec
  ; GFX90A-NEXT:   $agpr46 = V_ACCVGPR_WRITE_B32_e64 $vgpr14, implicit $exec
  ; GFX90A-NEXT:   $agpr45 = V_ACCVGPR_WRITE_B32_e64 $vgpr13, implicit $exec
  ; GFX90A-NEXT:   $agpr44 = V_ACCVGPR_WRITE_B32_e64 $vgpr12, implicit $exec
  ; GFX90A-NEXT:   $agpr43 = V_ACCVGPR_WRITE_B32_e64 $vgpr11, implicit $exec
  ; GFX90A-NEXT:   $agpr42 = V_ACCVGPR_WRITE_B32_e64 $vgpr10, implicit $exec
  ; GFX90A-NEXT:   $agpr41 = V_ACCVGPR_WRITE_B32_e64 $vgpr9, implicit $exec
  ; GFX90A-NEXT:   $agpr40 = V_ACCVGPR_WRITE_B32_e64 $vgpr8, implicit $exec
  ; GFX90A-NEXT:   $agpr39 = V_ACCVGPR_WRITE_B32_e64 $vgpr7, implicit $exec
  ; GFX90A-NEXT:   $agpr38 = V_ACCVGPR_WRITE_B32_e64 $vgpr6, implicit $exec
  ; GFX90A-NEXT:   $agpr37 = V_ACCVGPR_WRITE_B32_e64 $vgpr5, implicit $exec
  ; GFX90A-NEXT:   $agpr36 = V_ACCVGPR_WRITE_B32_e64 $vgpr4, implicit $exec
  ; GFX90A-NEXT:   $agpr35 = V_ACCVGPR_WRITE_B32_e64 $vgpr3, implicit $exec
  ; GFX90A-NEXT:   $agpr34 = V_ACCVGPR_WRITE_B32_e64 $vgpr2, implicit $exec
  ; GFX90A-NEXT:   $agpr33 = V_ACCVGPR_WRITE_B32_e64 $vgpr1, implicit $exec
  ; GFX90A-NEXT:   $agpr32 = V_ACCVGPR_WRITE_B32_e64 $vgpr0, implicit $exec
  ; GFX90A-NEXT:   S_ENDPGM 0, amdgpu_allvgprs
  ;
  ; GFX908-FLATSCR-LABEL: name: agpr64_save_clobber_scc
  ; GFX908-FLATSCR: bb.0:
  ; GFX908-FLATSCR-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GFX908-FLATSCR-NEXT:   liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $agpr0_agpr1
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT:   S_CMP_EQ_U32 0, 0, implicit-def $scc
  ; GFX908-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $vgpr1, $sgpr32, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.2, addrspace 5)
  ; GFX908-FLATSCR-NEXT:   $vgpr1 = V_MOV_B32_e32 $sgpr32, implicit $exec
  ; GFX908-FLATSCR-NEXT:   $vgpr1 = V_ADD_U32_e32 8200, $vgpr1, implicit $exec
  ; GFX908-FLATSCR-NEXT:   $vgpr0 = V_ACCVGPR_READ_B32_e64 $agpr0, implicit $exec, implicit-def $agpr0_agpr1, implicit $agpr0_agpr1
  ; GFX908-FLATSCR-NEXT:   SCRATCH_STORE_DWORD $vgpr0, $vgpr1, 0, 0, implicit $exec, implicit $flat_scr, implicit $agpr0_agpr1 :: ("amdgpu-non-volatile" store (s32) into %stack.1, addrspace 5)
  ; GFX908-FLATSCR-NEXT:   $vgpr0 = V_ACCVGPR_READ_B32_e64 $agpr1, implicit $exec, implicit $agpr0_agpr1
  ; GFX908-FLATSCR-NEXT:   SCRATCH_STORE_DWORD $vgpr0, $vgpr1, 4, 0, implicit $exec, implicit $flat_scr, implicit $agpr0_agpr1 :: ("amdgpu-non-volatile" store (s32) into %stack.1 + 4, addrspace 5)
  ; GFX908-FLATSCR-NEXT:   $vgpr1 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.2, addrspace 5)
  ; GFX908-FLATSCR-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT: bb.1:
  ; GFX908-FLATSCR-NEXT:   successors: %bb.2(0x80000000)
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT:   S_NOP 0
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT: bb.2:
  ; GFX908-FLATSCR-NEXT:   liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $agpr0_agpr1
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT:   S_ENDPGM 0, amdgpu_allvgprs
  ;
  ; GFX90A-FLATSCR-LABEL: name: agpr64_save_clobber_scc
  ; GFX90A-FLATSCR: bb.0:
  ; GFX90A-FLATSCR-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GFX90A-FLATSCR-NEXT:   liveins: $agpr32, $agpr33, $agpr34, $agpr35, $agpr36, $agpr37, $agpr38, $agpr39, $agpr40, $agpr41, $agpr42, $agpr43, $agpr44, $agpr45, $agpr46, $agpr47, $agpr48, $agpr49, $agpr50, $agpr51, $agpr52, $agpr53, $agpr54, $agpr55, $agpr56, $agpr57, $agpr58, $agpr59, $agpr60, $agpr61, $agpr62, $agpr63, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55, $agpr0_agpr1, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT:   $vgpr0 = V_ACCVGPR_READ_B32_e64 killed $agpr32, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr1 = V_ACCVGPR_READ_B32_e64 killed $agpr33, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr2 = V_ACCVGPR_READ_B32_e64 killed $agpr34, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr3 = V_ACCVGPR_READ_B32_e64 killed $agpr35, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr4 = V_ACCVGPR_READ_B32_e64 killed $agpr36, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr5 = V_ACCVGPR_READ_B32_e64 killed $agpr37, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr6 = V_ACCVGPR_READ_B32_e64 killed $agpr38, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr7 = V_ACCVGPR_READ_B32_e64 killed $agpr39, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr8 = V_ACCVGPR_READ_B32_e64 killed $agpr40, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr9 = V_ACCVGPR_READ_B32_e64 killed $agpr41, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr10 = V_ACCVGPR_READ_B32_e64 killed $agpr42, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr11 = V_ACCVGPR_READ_B32_e64 killed $agpr43, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr12 = V_ACCVGPR_READ_B32_e64 killed $agpr44, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr13 = V_ACCVGPR_READ_B32_e64 killed $agpr45, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr14 = V_ACCVGPR_READ_B32_e64 killed $agpr46, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr15 = V_ACCVGPR_READ_B32_e64 killed $agpr47, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr16 = V_ACCVGPR_READ_B32_e64 killed $agpr48, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr17 = V_ACCVGPR_READ_B32_e64 killed $agpr49, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr18 = V_ACCVGPR_READ_B32_e64 killed $agpr50, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr19 = V_ACCVGPR_READ_B32_e64 killed $agpr51, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr20 = V_ACCVGPR_READ_B32_e64 killed $agpr52, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr21 = V_ACCVGPR_READ_B32_e64 killed $agpr53, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr22 = V_ACCVGPR_READ_B32_e64 killed $agpr54, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr23 = V_ACCVGPR_READ_B32_e64 killed $agpr55, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr24 = V_ACCVGPR_READ_B32_e64 killed $agpr56, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr25 = V_ACCVGPR_READ_B32_e64 killed $agpr57, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr26 = V_ACCVGPR_READ_B32_e64 killed $agpr58, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr27 = V_ACCVGPR_READ_B32_e64 killed $agpr59, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr28 = V_ACCVGPR_READ_B32_e64 killed $agpr60, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr29 = V_ACCVGPR_READ_B32_e64 killed $agpr61, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr30 = V_ACCVGPR_READ_B32_e64 killed $agpr62, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr31 = V_ACCVGPR_READ_B32_e64 killed $agpr63, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr32 = V_ACCVGPR_READ_B32_e64 killed $agpr64, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr33 = V_ACCVGPR_READ_B32_e64 killed $agpr65, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr34 = V_ACCVGPR_READ_B32_e64 killed $agpr66, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr35 = V_ACCVGPR_READ_B32_e64 killed $agpr67, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr36 = V_ACCVGPR_READ_B32_e64 killed $agpr68, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr37 = V_ACCVGPR_READ_B32_e64 killed $agpr69, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr38 = V_ACCVGPR_READ_B32_e64 killed $agpr70, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr39 = V_ACCVGPR_READ_B32_e64 killed $agpr71, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr48 = V_ACCVGPR_READ_B32_e64 killed $agpr72, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr49 = V_ACCVGPR_READ_B32_e64 killed $agpr73, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr50 = V_ACCVGPR_READ_B32_e64 killed $agpr74, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr51 = V_ACCVGPR_READ_B32_e64 killed $agpr75, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr52 = V_ACCVGPR_READ_B32_e64 killed $agpr76, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr53 = V_ACCVGPR_READ_B32_e64 killed $agpr77, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr54 = V_ACCVGPR_READ_B32_e64 killed $agpr78, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr55 = V_ACCVGPR_READ_B32_e64 killed $agpr79, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr80, $sgpr32, 700, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.50, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr81, $sgpr32, 696, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.51, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr82, $sgpr32, 692, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.52, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr83, $sgpr32, 688, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.53, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr84, $sgpr32, 684, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.54, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr85, $sgpr32, 680, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.55, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr86, $sgpr32, 676, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.56, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr87, $sgpr32, 672, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.57, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr88, $sgpr32, 668, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.58, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr89, $sgpr32, 664, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.59, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr90, $sgpr32, 660, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.60, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr91, $sgpr32, 656, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.61, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr92, $sgpr32, 652, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.62, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr93, $sgpr32, 648, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.63, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr94, $sgpr32, 644, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.64, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr95, $sgpr32, 640, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.65, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr96, $sgpr32, 636, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.66, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr97, $sgpr32, 632, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.67, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr98, $sgpr32, 628, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.68, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr99, $sgpr32, 624, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.69, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr100, $sgpr32, 620, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.70, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr101, $sgpr32, 616, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.71, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr102, $sgpr32, 612, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.72, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr103, $sgpr32, 608, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.73, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr104, $sgpr32, 604, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.74, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr105, $sgpr32, 600, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.75, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr106, $sgpr32, 596, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.76, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr107, $sgpr32, 592, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.77, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr108, $sgpr32, 588, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.78, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr109, $sgpr32, 584, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.79, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr110, $sgpr32, 580, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.80, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr111, $sgpr32, 576, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.81, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr112, $sgpr32, 572, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.82, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr113, $sgpr32, 568, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.83, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr114, $sgpr32, 564, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.84, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr115, $sgpr32, 560, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.85, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr116, $sgpr32, 556, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.86, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr117, $sgpr32, 552, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.87, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr118, $sgpr32, 548, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.88, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr119, $sgpr32, 544, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.89, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr120, $sgpr32, 540, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.90, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr121, $sgpr32, 536, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.91, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr122, $sgpr32, 532, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.92, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr123, $sgpr32, 528, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.93, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr124, $sgpr32, 524, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.94, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr125, $sgpr32, 520, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.95, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr126, $sgpr32, 516, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.96, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr127, $sgpr32, 512, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.97, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr128, $sgpr32, 508, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.98, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr129, $sgpr32, 504, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.99, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr130, $sgpr32, 500, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.100, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr131, $sgpr32, 496, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.101, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr132, $sgpr32, 492, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.102, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr133, $sgpr32, 488, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.103, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr134, $sgpr32, 484, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.104, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr135, $sgpr32, 480, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.105, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr136, $sgpr32, 476, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.106, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr137, $sgpr32, 472, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.107, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr138, $sgpr32, 468, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.108, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr139, $sgpr32, 464, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.109, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr140, $sgpr32, 460, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.110, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr141, $sgpr32, 456, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.111, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr142, $sgpr32, 452, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.112, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr143, $sgpr32, 448, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.113, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr144, $sgpr32, 444, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.114, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr145, $sgpr32, 440, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.115, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr146, $sgpr32, 436, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.116, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr147, $sgpr32, 432, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.117, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr148, $sgpr32, 428, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.118, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr149, $sgpr32, 424, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.119, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr150, $sgpr32, 420, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.120, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr151, $sgpr32, 416, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.121, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr152, $sgpr32, 412, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.122, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr153, $sgpr32, 408, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.123, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr154, $sgpr32, 404, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.124, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr155, $sgpr32, 400, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.125, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr156, $sgpr32, 396, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.126, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr157, $sgpr32, 392, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.127, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr158, $sgpr32, 388, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.128, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr159, $sgpr32, 384, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.129, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr160, $sgpr32, 380, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.130, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr161, $sgpr32, 376, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.131, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr162, $sgpr32, 372, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.132, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr163, $sgpr32, 368, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.133, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr164, $sgpr32, 364, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.134, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr165, $sgpr32, 360, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.135, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr166, $sgpr32, 356, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.136, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr167, $sgpr32, 352, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.137, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr168, $sgpr32, 348, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.138, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr169, $sgpr32, 344, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.139, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr170, $sgpr32, 340, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.140, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr171, $sgpr32, 336, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.141, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr172, $sgpr32, 332, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.142, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr173, $sgpr32, 328, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.143, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr174, $sgpr32, 324, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.144, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr175, $sgpr32, 320, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.145, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr176, $sgpr32, 316, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.146, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr177, $sgpr32, 312, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.147, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr178, $sgpr32, 308, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.148, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr179, $sgpr32, 304, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.149, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr180, $sgpr32, 300, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.150, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr181, $sgpr32, 296, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.151, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr182, $sgpr32, 292, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.152, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr183, $sgpr32, 288, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.153, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr184, $sgpr32, 284, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.154, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr185, $sgpr32, 280, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.155, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr186, $sgpr32, 276, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.156, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr187, $sgpr32, 272, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.157, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr188, $sgpr32, 268, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.158, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr189, $sgpr32, 264, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.159, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr190, $sgpr32, 260, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.160, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr191, $sgpr32, 256, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.161, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr192, $sgpr32, 252, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.162, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr193, $sgpr32, 248, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.163, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr194, $sgpr32, 244, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.164, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr195, $sgpr32, 240, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.165, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr196, $sgpr32, 236, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.166, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr197, $sgpr32, 232, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.167, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr198, $sgpr32, 228, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.168, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr199, $sgpr32, 224, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.169, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr200, $sgpr32, 220, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.170, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr201, $sgpr32, 216, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.171, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr202, $sgpr32, 212, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.172, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr203, $sgpr32, 208, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.173, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr204, $sgpr32, 204, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.174, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr205, $sgpr32, 200, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.175, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr206, $sgpr32, 196, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.176, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr207, $sgpr32, 192, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.177, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr208, $sgpr32, 188, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.178, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr209, $sgpr32, 184, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.179, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr210, $sgpr32, 180, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.180, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr211, $sgpr32, 176, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.181, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr212, $sgpr32, 172, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.182, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr213, $sgpr32, 168, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.183, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr214, $sgpr32, 164, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.184, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr215, $sgpr32, 160, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.185, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr216, $sgpr32, 156, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.186, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr217, $sgpr32, 152, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.187, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr218, $sgpr32, 148, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.188, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr219, $sgpr32, 144, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.189, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr220, $sgpr32, 140, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.190, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr221, $sgpr32, 136, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.191, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr222, $sgpr32, 132, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.192, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr223, $sgpr32, 128, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.193, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr224, $sgpr32, 124, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.194, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr225, $sgpr32, 120, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.195, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr226, $sgpr32, 116, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.196, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr227, $sgpr32, 112, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.197, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr228, $sgpr32, 108, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.198, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr229, $sgpr32, 104, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.199, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr230, $sgpr32, 100, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.200, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr231, $sgpr32, 96, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.201, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr232, $sgpr32, 92, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.202, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr233, $sgpr32, 88, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.203, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr234, $sgpr32, 84, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.204, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr235, $sgpr32, 80, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.205, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr236, $sgpr32, 76, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.206, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr237, $sgpr32, 72, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.207, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr238, $sgpr32, 68, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.208, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr239, $sgpr32, 64, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.209, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr240, $sgpr32, 60, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.210, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr241, $sgpr32, 56, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.211, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr242, $sgpr32, 52, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.212, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr243, $sgpr32, 48, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.213, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr244, $sgpr32, 44, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.214, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr245, $sgpr32, 40, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.215, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr246, $sgpr32, 36, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.216, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr247, $sgpr32, 32, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.217, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr248, $sgpr32, 28, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.218, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr249, $sgpr32, 24, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.219, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr250, $sgpr32, 20, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.220, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr251, $sgpr32, 16, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.221, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr252, $sgpr32, 12, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.222, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr253, $sgpr32, 8, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.223, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr254, $sgpr32, 4, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.224, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr255, $sgpr32, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.225, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   S_CMP_EQ_U32 0, 0, implicit-def $scc
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $vgpr40, $sgpr32, 704, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.226, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $vgpr40 = V_MOV_B32_e32 $sgpr32, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr40 = V_ADD_U32_e32 8904, $vgpr40, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORDX2 $agpr0_agpr1, killed $vgpr40, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s64) into %stack.1, align 4, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $vgpr40 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 704, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.226, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT: bb.1:
  ; GFX90A-FLATSCR-NEXT:   successors: %bb.2(0x80000000)
  ; GFX90A-FLATSCR-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT:   S_NOP 0
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT: bb.2:
  ; GFX90A-FLATSCR-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55, $agpr0_agpr1, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT:   $agpr255 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.225, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr254 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 4, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.224, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr253 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 8, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.223, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr252 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 12, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.222, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr251 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 16, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.221, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr250 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 20, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.220, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr249 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 24, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.219, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr248 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 28, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.218, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr247 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 32, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.217, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr246 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 36, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.216, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr245 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 40, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.215, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr244 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 44, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.214, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr243 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 48, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.213, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr242 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 52, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.212, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr241 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 56, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.211, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr240 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 60, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.210, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr239 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 64, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.209, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr238 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 68, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.208, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr237 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 72, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.207, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr236 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 76, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.206, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr235 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 80, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.205, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr234 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 84, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.204, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr233 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 88, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.203, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr232 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 92, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.202, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr231 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 96, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.201, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr230 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 100, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.200, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr229 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 104, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.199, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr228 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 108, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.198, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr227 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 112, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.197, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr226 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 116, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.196, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr225 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 120, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.195, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr224 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 124, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.194, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr223 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 128, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.193, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr222 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 132, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.192, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr221 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 136, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.191, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr220 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 140, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.190, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr219 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 144, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.189, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr218 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 148, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.188, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr217 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 152, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.187, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr216 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 156, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.186, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr215 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 160, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.185, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr214 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 164, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.184, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr213 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 168, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.183, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr212 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 172, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.182, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr211 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 176, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.181, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr210 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 180, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.180, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr209 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 184, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.179, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr208 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 188, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.178, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr207 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 192, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.177, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr206 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 196, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.176, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr205 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 200, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.175, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr204 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 204, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.174, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr203 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 208, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.173, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr202 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 212, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.172, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr201 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 216, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.171, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr200 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 220, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.170, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr199 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 224, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.169, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr198 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 228, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.168, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr197 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 232, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.167, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr196 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 236, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.166, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr195 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 240, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.165, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr194 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 244, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.164, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr193 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 248, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.163, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr192 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 252, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.162, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr191 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 256, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.161, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr190 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 260, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.160, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr189 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 264, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.159, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr188 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 268, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.158, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr187 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 272, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.157, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr186 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 276, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.156, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr185 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 280, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.155, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr184 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 284, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.154, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr183 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 288, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.153, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr182 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 292, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.152, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr181 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 296, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.151, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr180 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 300, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.150, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr179 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 304, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.149, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr178 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 308, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.148, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr177 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 312, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.147, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr176 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 316, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.146, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr175 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 320, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.145, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr174 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 324, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.144, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr173 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 328, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.143, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr172 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 332, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.142, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr171 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 336, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.141, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr170 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 340, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.140, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr169 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 344, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.139, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr168 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 348, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.138, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr167 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 352, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.137, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr166 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 356, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.136, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr165 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 360, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.135, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr164 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 364, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.134, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr163 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 368, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.133, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr162 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 372, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.132, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr161 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 376, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.131, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr160 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 380, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.130, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr159 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 384, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.129, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr158 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 388, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.128, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr157 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 392, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.127, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr156 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 396, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.126, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr155 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 400, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.125, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr154 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 404, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.124, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr153 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 408, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.123, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr152 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 412, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.122, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr151 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 416, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.121, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr150 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 420, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.120, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr149 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 424, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.119, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr148 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 428, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.118, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr147 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 432, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.117, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr146 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 436, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.116, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr145 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 440, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.115, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr144 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 444, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.114, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr143 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 448, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.113, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr142 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 452, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.112, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr141 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 456, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.111, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr140 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 460, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.110, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr139 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 464, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.109, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr138 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 468, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.108, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr137 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 472, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.107, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr136 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 476, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.106, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr135 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 480, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.105, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr134 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 484, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.104, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr133 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 488, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.103, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr132 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 492, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.102, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr131 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 496, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.101, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr130 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 500, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.100, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr129 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 504, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.99, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr128 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 508, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.98, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr127 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 512, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.97, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr126 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 516, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.96, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr125 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 520, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.95, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr124 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 524, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.94, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr123 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 528, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.93, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr122 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 532, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.92, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr121 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 536, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.91, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr120 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 540, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.90, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr119 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 544, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.89, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr118 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 548, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.88, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr117 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 552, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.87, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr116 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 556, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.86, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr115 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 560, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.85, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr114 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 564, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.84, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr113 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 568, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.83, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr112 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 572, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.82, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr111 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 576, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.81, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr110 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 580, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.80, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr109 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 584, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.79, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr108 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 588, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.78, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr107 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 592, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.77, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr106 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 596, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.76, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr105 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 600, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.75, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr104 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 604, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.74, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr103 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 608, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.73, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr102 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 612, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.72, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr101 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 616, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.71, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr100 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 620, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.70, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr99 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 624, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.69, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr98 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 628, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.68, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr97 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 632, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.67, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr96 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 636, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.66, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr95 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 640, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.65, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr94 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 644, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.64, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr93 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 648, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.63, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr92 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 652, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.62, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr91 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 656, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.61, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr90 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 660, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.60, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr89 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 664, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.59, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr88 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 668, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.58, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr87 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 672, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.57, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr86 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 676, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.56, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr85 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 680, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.55, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr84 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 684, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.54, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr83 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 688, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.53, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr82 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 692, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.52, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr81 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 696, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.51, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr80 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 700, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.50, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr79 = V_ACCVGPR_WRITE_B32_e64 $vgpr55, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr78 = V_ACCVGPR_WRITE_B32_e64 $vgpr54, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr77 = V_ACCVGPR_WRITE_B32_e64 $vgpr53, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr76 = V_ACCVGPR_WRITE_B32_e64 $vgpr52, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr75 = V_ACCVGPR_WRITE_B32_e64 $vgpr51, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr74 = V_ACCVGPR_WRITE_B32_e64 $vgpr50, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr73 = V_ACCVGPR_WRITE_B32_e64 $vgpr49, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr72 = V_ACCVGPR_WRITE_B32_e64 $vgpr48, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr71 = V_ACCVGPR_WRITE_B32_e64 $vgpr39, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr70 = V_ACCVGPR_WRITE_B32_e64 $vgpr38, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr69 = V_ACCVGPR_WRITE_B32_e64 $vgpr37, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr68 = V_ACCVGPR_WRITE_B32_e64 $vgpr36, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr67 = V_ACCVGPR_WRITE_B32_e64 $vgpr35, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr66 = V_ACCVGPR_WRITE_B32_e64 $vgpr34, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr65 = V_ACCVGPR_WRITE_B32_e64 $vgpr33, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr64 = V_ACCVGPR_WRITE_B32_e64 $vgpr32, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr63 = V_ACCVGPR_WRITE_B32_e64 $vgpr31, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr62 = V_ACCVGPR_WRITE_B32_e64 $vgpr30, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr61 = V_ACCVGPR_WRITE_B32_e64 $vgpr29, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr60 = V_ACCVGPR_WRITE_B32_e64 $vgpr28, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr59 = V_ACCVGPR_WRITE_B32_e64 $vgpr27, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr58 = V_ACCVGPR_WRITE_B32_e64 $vgpr26, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr57 = V_ACCVGPR_WRITE_B32_e64 $vgpr25, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr56 = V_ACCVGPR_WRITE_B32_e64 $vgpr24, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr55 = V_ACCVGPR_WRITE_B32_e64 $vgpr23, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr54 = V_ACCVGPR_WRITE_B32_e64 $vgpr22, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr53 = V_ACCVGPR_WRITE_B32_e64 $vgpr21, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr52 = V_ACCVGPR_WRITE_B32_e64 $vgpr20, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr51 = V_ACCVGPR_WRITE_B32_e64 $vgpr19, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr50 = V_ACCVGPR_WRITE_B32_e64 $vgpr18, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr49 = V_ACCVGPR_WRITE_B32_e64 $vgpr17, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr48 = V_ACCVGPR_WRITE_B32_e64 $vgpr16, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr47 = V_ACCVGPR_WRITE_B32_e64 $vgpr15, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr46 = V_ACCVGPR_WRITE_B32_e64 $vgpr14, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr45 = V_ACCVGPR_WRITE_B32_e64 $vgpr13, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr44 = V_ACCVGPR_WRITE_B32_e64 $vgpr12, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr43 = V_ACCVGPR_WRITE_B32_e64 $vgpr11, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr42 = V_ACCVGPR_WRITE_B32_e64 $vgpr10, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr41 = V_ACCVGPR_WRITE_B32_e64 $vgpr9, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr40 = V_ACCVGPR_WRITE_B32_e64 $vgpr8, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr39 = V_ACCVGPR_WRITE_B32_e64 $vgpr7, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr38 = V_ACCVGPR_WRITE_B32_e64 $vgpr6, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr37 = V_ACCVGPR_WRITE_B32_e64 $vgpr5, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr36 = V_ACCVGPR_WRITE_B32_e64 $vgpr4, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr35 = V_ACCVGPR_WRITE_B32_e64 $vgpr3, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr34 = V_ACCVGPR_WRITE_B32_e64 $vgpr2, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr33 = V_ACCVGPR_WRITE_B32_e64 $vgpr1, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr32 = V_ACCVGPR_WRITE_B32_e64 $vgpr0, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   S_ENDPGM 0, amdgpu_allvgprs
  bb.0:
    liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $agpr0_agpr1

    S_CMP_EQ_U32 0, 0, implicit-def $scc
    SI_SPILL_A64_SAVE $agpr0_agpr1, %stack.1, $sgpr32, 0, implicit $exec :: (store (s64) into %stack.1, align 4, addrspace 5)
    S_CBRANCH_SCC1 %bb.2, implicit $scc

  bb.1:
    S_NOP 0

  bb.2:
    liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $agpr0_agpr1
    S_ENDPGM 0, amdgpu_allvgprs
...
---
name: agpr96_save_clobber_scc
tracksRegLiveness: true
stack:
  - { id: 0, type: default, offset: 0, size: 8192, alignment: 8 }
  - { id: 1, type: spill-slot, offset: 0, size: 8192, alignment: 4 }

machineFunctionInfo:
  scratchRSrcReg:  $sgpr0_sgpr1_sgpr2_sgpr3
  frameOffsetReg:  $sgpr33
  stackPtrOffsetReg:  $sgpr32

body:             |
  ; GFX908-LABEL: name: agpr96_save_clobber_scc
  ; GFX908: bb.0:
  ; GFX908-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GFX908-NEXT:   liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $agpr0_agpr1
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT:   S_CMP_EQ_U32 0, 0, implicit-def $scc
  ; GFX908-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $vgpr1, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.2, addrspace 5)
  ; GFX908-NEXT:   $vgpr1 = V_MOV_B32_e32 8200, implicit $exec
  ; GFX908-NEXT:   $vgpr0 = V_ACCVGPR_READ_B32_e64 $agpr0, implicit $exec, implicit-def $agpr0_agpr1_agpr2, implicit $agpr0_agpr1_agpr2
  ; GFX908-NEXT:   BUFFER_STORE_DWORD_OFFEN $vgpr0, $vgpr1, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec, implicit $agpr0_agpr1_agpr2 :: ("amdgpu-non-volatile" store (s32) into %stack.1, addrspace 5)
  ; GFX908-NEXT:   $vgpr0 = V_ACCVGPR_READ_B32_e64 $agpr1, implicit $exec
  ; GFX908-NEXT:   BUFFER_STORE_DWORD_OFFEN $vgpr0, $vgpr1, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 4, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.1 + 4, addrspace 5)
  ; GFX908-NEXT:   $vgpr0 = V_ACCVGPR_READ_B32_e64 $agpr2, implicit $exec, implicit $agpr0_agpr1_agpr2
  ; GFX908-NEXT:   BUFFER_STORE_DWORD_OFFEN $vgpr0, $vgpr1, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 8, 0, 0, implicit $exec, implicit $agpr0_agpr1_agpr2 :: ("amdgpu-non-volatile" store (s32) into %stack.1 + 8, addrspace 5)
  ; GFX908-NEXT:   $vgpr1 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.2, addrspace 5)
  ; GFX908-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT: bb.1:
  ; GFX908-NEXT:   successors: %bb.2(0x80000000)
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT:   S_NOP 0
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT: bb.2:
  ; GFX908-NEXT:   liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $agpr0_agpr1
  ; GFX908-NEXT: {{  $}}
  ; GFX908-NEXT:   S_ENDPGM 0, amdgpu_allvgprs
  ;
  ; GFX90A-LABEL: name: agpr96_save_clobber_scc
  ; GFX90A: bb.0:
  ; GFX90A-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GFX90A-NEXT:   liveins: $agpr32, $agpr33, $agpr34, $agpr35, $agpr36, $agpr37, $agpr38, $agpr39, $agpr40, $agpr41, $agpr42, $agpr43, $agpr44, $agpr45, $agpr46, $agpr47, $agpr48, $agpr49, $agpr50, $agpr51, $agpr52, $agpr53, $agpr54, $agpr55, $agpr56, $agpr57, $agpr58, $agpr59, $agpr60, $agpr61, $agpr62, $agpr63, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55, $agpr0_agpr1, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   $vgpr0 = V_ACCVGPR_READ_B32_e64 killed $agpr32, implicit $exec
  ; GFX90A-NEXT:   $vgpr1 = V_ACCVGPR_READ_B32_e64 killed $agpr33, implicit $exec
  ; GFX90A-NEXT:   $vgpr2 = V_ACCVGPR_READ_B32_e64 killed $agpr34, implicit $exec
  ; GFX90A-NEXT:   $vgpr3 = V_ACCVGPR_READ_B32_e64 killed $agpr35, implicit $exec
  ; GFX90A-NEXT:   $vgpr4 = V_ACCVGPR_READ_B32_e64 killed $agpr36, implicit $exec
  ; GFX90A-NEXT:   $vgpr5 = V_ACCVGPR_READ_B32_e64 killed $agpr37, implicit $exec
  ; GFX90A-NEXT:   $vgpr6 = V_ACCVGPR_READ_B32_e64 killed $agpr38, implicit $exec
  ; GFX90A-NEXT:   $vgpr7 = V_ACCVGPR_READ_B32_e64 killed $agpr39, implicit $exec
  ; GFX90A-NEXT:   $vgpr8 = V_ACCVGPR_READ_B32_e64 killed $agpr40, implicit $exec
  ; GFX90A-NEXT:   $vgpr9 = V_ACCVGPR_READ_B32_e64 killed $agpr41, implicit $exec
  ; GFX90A-NEXT:   $vgpr10 = V_ACCVGPR_READ_B32_e64 killed $agpr42, implicit $exec
  ; GFX90A-NEXT:   $vgpr11 = V_ACCVGPR_READ_B32_e64 killed $agpr43, implicit $exec
  ; GFX90A-NEXT:   $vgpr12 = V_ACCVGPR_READ_B32_e64 killed $agpr44, implicit $exec
  ; GFX90A-NEXT:   $vgpr13 = V_ACCVGPR_READ_B32_e64 killed $agpr45, implicit $exec
  ; GFX90A-NEXT:   $vgpr14 = V_ACCVGPR_READ_B32_e64 killed $agpr46, implicit $exec
  ; GFX90A-NEXT:   $vgpr15 = V_ACCVGPR_READ_B32_e64 killed $agpr47, implicit $exec
  ; GFX90A-NEXT:   $vgpr16 = V_ACCVGPR_READ_B32_e64 killed $agpr48, implicit $exec
  ; GFX90A-NEXT:   $vgpr17 = V_ACCVGPR_READ_B32_e64 killed $agpr49, implicit $exec
  ; GFX90A-NEXT:   $vgpr18 = V_ACCVGPR_READ_B32_e64 killed $agpr50, implicit $exec
  ; GFX90A-NEXT:   $vgpr19 = V_ACCVGPR_READ_B32_e64 killed $agpr51, implicit $exec
  ; GFX90A-NEXT:   $vgpr20 = V_ACCVGPR_READ_B32_e64 killed $agpr52, implicit $exec
  ; GFX90A-NEXT:   $vgpr21 = V_ACCVGPR_READ_B32_e64 killed $agpr53, implicit $exec
  ; GFX90A-NEXT:   $vgpr22 = V_ACCVGPR_READ_B32_e64 killed $agpr54, implicit $exec
  ; GFX90A-NEXT:   $vgpr23 = V_ACCVGPR_READ_B32_e64 killed $agpr55, implicit $exec
  ; GFX90A-NEXT:   $vgpr24 = V_ACCVGPR_READ_B32_e64 killed $agpr56, implicit $exec
  ; GFX90A-NEXT:   $vgpr25 = V_ACCVGPR_READ_B32_e64 killed $agpr57, implicit $exec
  ; GFX90A-NEXT:   $vgpr26 = V_ACCVGPR_READ_B32_e64 killed $agpr58, implicit $exec
  ; GFX90A-NEXT:   $vgpr27 = V_ACCVGPR_READ_B32_e64 killed $agpr59, implicit $exec
  ; GFX90A-NEXT:   $vgpr28 = V_ACCVGPR_READ_B32_e64 killed $agpr60, implicit $exec
  ; GFX90A-NEXT:   $vgpr29 = V_ACCVGPR_READ_B32_e64 killed $agpr61, implicit $exec
  ; GFX90A-NEXT:   $vgpr30 = V_ACCVGPR_READ_B32_e64 killed $agpr62, implicit $exec
  ; GFX90A-NEXT:   $vgpr31 = V_ACCVGPR_READ_B32_e64 killed $agpr63, implicit $exec
  ; GFX90A-NEXT:   $vgpr32 = V_ACCVGPR_READ_B32_e64 killed $agpr64, implicit $exec
  ; GFX90A-NEXT:   $vgpr33 = V_ACCVGPR_READ_B32_e64 killed $agpr65, implicit $exec
  ; GFX90A-NEXT:   $vgpr34 = V_ACCVGPR_READ_B32_e64 killed $agpr66, implicit $exec
  ; GFX90A-NEXT:   $vgpr35 = V_ACCVGPR_READ_B32_e64 killed $agpr67, implicit $exec
  ; GFX90A-NEXT:   $vgpr36 = V_ACCVGPR_READ_B32_e64 killed $agpr68, implicit $exec
  ; GFX90A-NEXT:   $vgpr37 = V_ACCVGPR_READ_B32_e64 killed $agpr69, implicit $exec
  ; GFX90A-NEXT:   $vgpr38 = V_ACCVGPR_READ_B32_e64 killed $agpr70, implicit $exec
  ; GFX90A-NEXT:   $vgpr39 = V_ACCVGPR_READ_B32_e64 killed $agpr71, implicit $exec
  ; GFX90A-NEXT:   $vgpr48 = V_ACCVGPR_READ_B32_e64 killed $agpr72, implicit $exec
  ; GFX90A-NEXT:   $vgpr49 = V_ACCVGPR_READ_B32_e64 killed $agpr73, implicit $exec
  ; GFX90A-NEXT:   $vgpr50 = V_ACCVGPR_READ_B32_e64 killed $agpr74, implicit $exec
  ; GFX90A-NEXT:   $vgpr51 = V_ACCVGPR_READ_B32_e64 killed $agpr75, implicit $exec
  ; GFX90A-NEXT:   $vgpr52 = V_ACCVGPR_READ_B32_e64 killed $agpr76, implicit $exec
  ; GFX90A-NEXT:   $vgpr53 = V_ACCVGPR_READ_B32_e64 killed $agpr77, implicit $exec
  ; GFX90A-NEXT:   $vgpr54 = V_ACCVGPR_READ_B32_e64 killed $agpr78, implicit $exec
  ; GFX90A-NEXT:   $vgpr55 = V_ACCVGPR_READ_B32_e64 killed $agpr79, implicit $exec
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr80, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 700, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.50, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr81, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 696, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.51, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr82, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 692, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.52, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr83, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 688, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.53, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr84, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 684, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.54, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr85, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 680, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.55, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr86, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 676, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.56, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr87, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 672, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.57, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr88, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 668, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.58, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr89, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 664, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.59, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr90, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 660, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.60, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr91, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 656, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.61, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr92, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 652, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.62, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr93, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 648, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.63, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr94, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 644, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.64, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr95, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 640, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.65, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr96, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 636, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.66, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr97, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 632, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.67, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr98, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 628, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.68, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr99, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 624, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.69, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr100, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 620, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.70, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr101, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 616, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.71, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr102, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 612, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.72, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr103, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 608, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.73, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr104, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 604, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.74, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr105, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 600, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.75, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr106, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 596, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.76, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr107, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 592, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.77, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr108, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 588, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.78, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr109, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 584, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.79, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr110, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 580, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.80, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr111, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 576, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.81, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr112, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 572, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.82, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr113, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 568, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.83, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr114, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 564, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.84, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr115, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 560, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.85, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr116, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 556, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.86, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr117, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 552, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.87, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr118, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 548, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.88, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr119, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 544, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.89, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr120, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 540, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.90, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr121, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 536, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.91, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr122, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 532, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.92, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr123, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 528, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.93, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr124, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 524, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.94, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr125, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 520, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.95, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr126, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 516, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.96, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr127, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 512, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.97, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr128, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 508, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.98, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr129, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 504, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.99, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr130, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 500, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.100, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr131, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 496, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.101, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr132, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 492, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.102, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr133, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 488, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.103, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr134, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 484, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.104, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr135, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 480, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.105, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr136, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 476, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.106, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr137, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 472, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.107, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr138, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 468, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.108, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr139, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 464, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.109, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr140, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 460, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.110, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr141, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 456, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.111, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr142, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 452, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.112, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr143, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 448, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.113, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr144, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 444, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.114, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr145, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 440, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.115, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr146, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 436, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.116, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr147, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 432, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.117, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr148, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 428, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.118, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr149, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 424, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.119, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr150, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 420, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.120, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr151, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 416, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.121, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr152, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 412, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.122, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr153, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 408, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.123, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr154, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 404, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.124, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr155, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 400, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.125, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr156, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 396, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.126, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr157, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 392, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.127, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr158, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 388, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.128, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr159, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 384, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.129, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr160, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 380, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.130, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr161, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 376, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.131, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr162, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 372, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.132, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr163, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 368, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.133, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr164, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 364, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.134, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr165, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 360, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.135, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr166, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 356, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.136, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr167, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 352, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.137, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr168, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 348, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.138, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr169, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 344, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.139, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr170, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 340, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.140, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr171, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 336, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.141, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr172, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 332, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.142, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr173, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 328, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.143, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr174, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 324, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.144, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr175, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 320, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.145, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr176, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 316, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.146, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr177, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 312, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.147, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr178, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 308, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.148, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr179, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 304, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.149, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr180, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 300, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.150, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr181, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 296, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.151, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr182, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 292, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.152, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr183, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 288, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.153, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr184, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 284, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.154, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr185, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 280, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.155, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr186, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 276, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.156, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr187, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 272, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.157, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr188, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 268, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.158, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr189, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 264, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.159, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr190, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 260, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.160, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr191, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 256, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.161, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr192, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 252, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.162, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr193, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 248, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.163, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr194, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 244, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.164, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr195, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 240, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.165, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr196, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 236, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.166, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr197, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 232, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.167, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr198, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 228, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.168, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr199, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 224, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.169, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr200, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 220, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.170, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr201, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 216, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.171, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr202, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 212, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.172, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr203, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 208, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.173, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr204, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 204, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.174, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr205, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 200, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.175, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr206, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 196, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.176, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr207, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 192, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.177, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr208, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 188, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.178, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr209, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 184, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.179, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr210, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 180, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.180, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr211, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 176, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.181, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr212, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 172, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.182, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr213, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 168, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.183, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr214, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 164, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.184, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr215, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 160, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.185, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr216, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 156, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.186, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr217, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 152, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.187, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr218, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 148, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.188, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr219, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 144, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.189, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr220, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 140, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.190, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr221, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 136, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.191, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr222, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 132, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.192, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr223, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 128, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.193, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr224, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 124, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.194, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr225, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 120, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.195, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr226, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 116, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.196, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr227, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 112, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.197, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr228, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 108, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.198, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr229, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 104, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.199, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr230, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 100, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.200, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr231, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 96, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.201, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr232, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 92, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.202, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr233, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 88, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.203, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr234, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 84, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.204, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr235, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 80, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.205, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr236, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 76, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.206, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr237, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 72, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.207, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr238, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 68, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.208, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr239, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 64, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.209, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr240, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 60, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.210, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr241, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 56, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.211, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr242, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 52, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.212, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr243, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 48, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.213, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr244, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 44, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.214, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr245, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 40, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.215, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr246, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 36, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.216, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr247, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 32, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.217, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr248, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 28, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.218, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr249, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 24, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.219, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr250, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 20, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.220, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr251, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 16, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.221, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr252, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 12, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.222, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr253, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 8, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.223, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr254, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 4, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.224, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $agpr255, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.225, addrspace 5)
  ; GFX90A-NEXT:   S_CMP_EQ_U32 0, 0, implicit-def $scc
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFSET killed $vgpr40, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 704, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.226, addrspace 5)
  ; GFX90A-NEXT:   $vgpr40 = V_MOV_B32_e32 8904, implicit $exec
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFEN $agpr0, $vgpr40, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec, implicit-def $agpr0_agpr1_agpr2, implicit $agpr0_agpr1_agpr2 :: ("amdgpu-non-volatile" store (s32) into %stack.1, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFEN $agpr1, $vgpr40, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 4, 0, 0, implicit $exec :: ("amdgpu-non-volatile" store (s32) into %stack.1 + 4, addrspace 5)
  ; GFX90A-NEXT:   BUFFER_STORE_DWORD_OFFEN $agpr2, killed $vgpr40, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 8, 0, 0, implicit $exec, implicit $agpr0_agpr1_agpr2 :: ("amdgpu-non-volatile" store (s32) into %stack.1 + 8, addrspace 5)
  ; GFX90A-NEXT:   $vgpr40 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 704, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.226, addrspace 5)
  ; GFX90A-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT: bb.1:
  ; GFX90A-NEXT:   successors: %bb.2(0x80000000)
  ; GFX90A-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   S_NOP 0
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT: bb.2:
  ; GFX90A-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55, $agpr0_agpr1, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   $agpr255 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.225, addrspace 5)
  ; GFX90A-NEXT:   $agpr254 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 4, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.224, addrspace 5)
  ; GFX90A-NEXT:   $agpr253 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 8, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.223, addrspace 5)
  ; GFX90A-NEXT:   $agpr252 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 12, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.222, addrspace 5)
  ; GFX90A-NEXT:   $agpr251 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 16, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.221, addrspace 5)
  ; GFX90A-NEXT:   $agpr250 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 20, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.220, addrspace 5)
  ; GFX90A-NEXT:   $agpr249 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 24, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.219, addrspace 5)
  ; GFX90A-NEXT:   $agpr248 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 28, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.218, addrspace 5)
  ; GFX90A-NEXT:   $agpr247 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 32, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.217, addrspace 5)
  ; GFX90A-NEXT:   $agpr246 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 36, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.216, addrspace 5)
  ; GFX90A-NEXT:   $agpr245 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 40, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.215, addrspace 5)
  ; GFX90A-NEXT:   $agpr244 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 44, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.214, addrspace 5)
  ; GFX90A-NEXT:   $agpr243 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 48, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.213, addrspace 5)
  ; GFX90A-NEXT:   $agpr242 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 52, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.212, addrspace 5)
  ; GFX90A-NEXT:   $agpr241 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 56, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.211, addrspace 5)
  ; GFX90A-NEXT:   $agpr240 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 60, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.210, addrspace 5)
  ; GFX90A-NEXT:   $agpr239 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 64, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.209, addrspace 5)
  ; GFX90A-NEXT:   $agpr238 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 68, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.208, addrspace 5)
  ; GFX90A-NEXT:   $agpr237 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 72, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.207, addrspace 5)
  ; GFX90A-NEXT:   $agpr236 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 76, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.206, addrspace 5)
  ; GFX90A-NEXT:   $agpr235 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 80, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.205, addrspace 5)
  ; GFX90A-NEXT:   $agpr234 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 84, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.204, addrspace 5)
  ; GFX90A-NEXT:   $agpr233 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 88, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.203, addrspace 5)
  ; GFX90A-NEXT:   $agpr232 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 92, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.202, addrspace 5)
  ; GFX90A-NEXT:   $agpr231 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 96, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.201, addrspace 5)
  ; GFX90A-NEXT:   $agpr230 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 100, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.200, addrspace 5)
  ; GFX90A-NEXT:   $agpr229 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 104, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.199, addrspace 5)
  ; GFX90A-NEXT:   $agpr228 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 108, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.198, addrspace 5)
  ; GFX90A-NEXT:   $agpr227 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 112, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.197, addrspace 5)
  ; GFX90A-NEXT:   $agpr226 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 116, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.196, addrspace 5)
  ; GFX90A-NEXT:   $agpr225 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 120, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.195, addrspace 5)
  ; GFX90A-NEXT:   $agpr224 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 124, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.194, addrspace 5)
  ; GFX90A-NEXT:   $agpr223 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 128, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.193, addrspace 5)
  ; GFX90A-NEXT:   $agpr222 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 132, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.192, addrspace 5)
  ; GFX90A-NEXT:   $agpr221 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 136, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.191, addrspace 5)
  ; GFX90A-NEXT:   $agpr220 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 140, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.190, addrspace 5)
  ; GFX90A-NEXT:   $agpr219 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 144, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.189, addrspace 5)
  ; GFX90A-NEXT:   $agpr218 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 148, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.188, addrspace 5)
  ; GFX90A-NEXT:   $agpr217 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 152, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.187, addrspace 5)
  ; GFX90A-NEXT:   $agpr216 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 156, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.186, addrspace 5)
  ; GFX90A-NEXT:   $agpr215 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 160, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.185, addrspace 5)
  ; GFX90A-NEXT:   $agpr214 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 164, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.184, addrspace 5)
  ; GFX90A-NEXT:   $agpr213 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 168, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.183, addrspace 5)
  ; GFX90A-NEXT:   $agpr212 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 172, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.182, addrspace 5)
  ; GFX90A-NEXT:   $agpr211 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 176, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.181, addrspace 5)
  ; GFX90A-NEXT:   $agpr210 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 180, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.180, addrspace 5)
  ; GFX90A-NEXT:   $agpr209 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 184, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.179, addrspace 5)
  ; GFX90A-NEXT:   $agpr208 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 188, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.178, addrspace 5)
  ; GFX90A-NEXT:   $agpr207 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 192, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.177, addrspace 5)
  ; GFX90A-NEXT:   $agpr206 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 196, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.176, addrspace 5)
  ; GFX90A-NEXT:   $agpr205 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 200, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.175, addrspace 5)
  ; GFX90A-NEXT:   $agpr204 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 204, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.174, addrspace 5)
  ; GFX90A-NEXT:   $agpr203 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 208, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.173, addrspace 5)
  ; GFX90A-NEXT:   $agpr202 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 212, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.172, addrspace 5)
  ; GFX90A-NEXT:   $agpr201 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 216, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.171, addrspace 5)
  ; GFX90A-NEXT:   $agpr200 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 220, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.170, addrspace 5)
  ; GFX90A-NEXT:   $agpr199 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 224, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.169, addrspace 5)
  ; GFX90A-NEXT:   $agpr198 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 228, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.168, addrspace 5)
  ; GFX90A-NEXT:   $agpr197 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 232, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.167, addrspace 5)
  ; GFX90A-NEXT:   $agpr196 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 236, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.166, addrspace 5)
  ; GFX90A-NEXT:   $agpr195 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 240, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.165, addrspace 5)
  ; GFX90A-NEXT:   $agpr194 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 244, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.164, addrspace 5)
  ; GFX90A-NEXT:   $agpr193 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 248, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.163, addrspace 5)
  ; GFX90A-NEXT:   $agpr192 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 252, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.162, addrspace 5)
  ; GFX90A-NEXT:   $agpr191 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 256, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.161, addrspace 5)
  ; GFX90A-NEXT:   $agpr190 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 260, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.160, addrspace 5)
  ; GFX90A-NEXT:   $agpr189 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 264, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.159, addrspace 5)
  ; GFX90A-NEXT:   $agpr188 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 268, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.158, addrspace 5)
  ; GFX90A-NEXT:   $agpr187 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 272, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.157, addrspace 5)
  ; GFX90A-NEXT:   $agpr186 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 276, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.156, addrspace 5)
  ; GFX90A-NEXT:   $agpr185 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 280, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.155, addrspace 5)
  ; GFX90A-NEXT:   $agpr184 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 284, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.154, addrspace 5)
  ; GFX90A-NEXT:   $agpr183 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 288, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.153, addrspace 5)
  ; GFX90A-NEXT:   $agpr182 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 292, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.152, addrspace 5)
  ; GFX90A-NEXT:   $agpr181 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 296, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.151, addrspace 5)
  ; GFX90A-NEXT:   $agpr180 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 300, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.150, addrspace 5)
  ; GFX90A-NEXT:   $agpr179 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 304, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.149, addrspace 5)
  ; GFX90A-NEXT:   $agpr178 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 308, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.148, addrspace 5)
  ; GFX90A-NEXT:   $agpr177 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 312, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.147, addrspace 5)
  ; GFX90A-NEXT:   $agpr176 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 316, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.146, addrspace 5)
  ; GFX90A-NEXT:   $agpr175 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 320, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.145, addrspace 5)
  ; GFX90A-NEXT:   $agpr174 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 324, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.144, addrspace 5)
  ; GFX90A-NEXT:   $agpr173 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 328, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.143, addrspace 5)
  ; GFX90A-NEXT:   $agpr172 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 332, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.142, addrspace 5)
  ; GFX90A-NEXT:   $agpr171 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 336, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.141, addrspace 5)
  ; GFX90A-NEXT:   $agpr170 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 340, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.140, addrspace 5)
  ; GFX90A-NEXT:   $agpr169 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 344, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.139, addrspace 5)
  ; GFX90A-NEXT:   $agpr168 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 348, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.138, addrspace 5)
  ; GFX90A-NEXT:   $agpr167 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 352, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.137, addrspace 5)
  ; GFX90A-NEXT:   $agpr166 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 356, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.136, addrspace 5)
  ; GFX90A-NEXT:   $agpr165 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 360, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.135, addrspace 5)
  ; GFX90A-NEXT:   $agpr164 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 364, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.134, addrspace 5)
  ; GFX90A-NEXT:   $agpr163 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 368, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.133, addrspace 5)
  ; GFX90A-NEXT:   $agpr162 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 372, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.132, addrspace 5)
  ; GFX90A-NEXT:   $agpr161 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 376, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.131, addrspace 5)
  ; GFX90A-NEXT:   $agpr160 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 380, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.130, addrspace 5)
  ; GFX90A-NEXT:   $agpr159 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 384, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.129, addrspace 5)
  ; GFX90A-NEXT:   $agpr158 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 388, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.128, addrspace 5)
  ; GFX90A-NEXT:   $agpr157 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 392, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.127, addrspace 5)
  ; GFX90A-NEXT:   $agpr156 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 396, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.126, addrspace 5)
  ; GFX90A-NEXT:   $agpr155 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 400, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.125, addrspace 5)
  ; GFX90A-NEXT:   $agpr154 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 404, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.124, addrspace 5)
  ; GFX90A-NEXT:   $agpr153 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 408, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.123, addrspace 5)
  ; GFX90A-NEXT:   $agpr152 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 412, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.122, addrspace 5)
  ; GFX90A-NEXT:   $agpr151 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 416, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.121, addrspace 5)
  ; GFX90A-NEXT:   $agpr150 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 420, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.120, addrspace 5)
  ; GFX90A-NEXT:   $agpr149 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 424, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.119, addrspace 5)
  ; GFX90A-NEXT:   $agpr148 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 428, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.118, addrspace 5)
  ; GFX90A-NEXT:   $agpr147 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 432, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.117, addrspace 5)
  ; GFX90A-NEXT:   $agpr146 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 436, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.116, addrspace 5)
  ; GFX90A-NEXT:   $agpr145 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 440, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.115, addrspace 5)
  ; GFX90A-NEXT:   $agpr144 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 444, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.114, addrspace 5)
  ; GFX90A-NEXT:   $agpr143 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 448, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.113, addrspace 5)
  ; GFX90A-NEXT:   $agpr142 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 452, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.112, addrspace 5)
  ; GFX90A-NEXT:   $agpr141 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 456, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.111, addrspace 5)
  ; GFX90A-NEXT:   $agpr140 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 460, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.110, addrspace 5)
  ; GFX90A-NEXT:   $agpr139 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 464, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.109, addrspace 5)
  ; GFX90A-NEXT:   $agpr138 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 468, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.108, addrspace 5)
  ; GFX90A-NEXT:   $agpr137 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 472, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.107, addrspace 5)
  ; GFX90A-NEXT:   $agpr136 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 476, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.106, addrspace 5)
  ; GFX90A-NEXT:   $agpr135 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 480, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.105, addrspace 5)
  ; GFX90A-NEXT:   $agpr134 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 484, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.104, addrspace 5)
  ; GFX90A-NEXT:   $agpr133 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 488, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.103, addrspace 5)
  ; GFX90A-NEXT:   $agpr132 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 492, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.102, addrspace 5)
  ; GFX90A-NEXT:   $agpr131 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 496, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.101, addrspace 5)
  ; GFX90A-NEXT:   $agpr130 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 500, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.100, addrspace 5)
  ; GFX90A-NEXT:   $agpr129 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 504, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.99, addrspace 5)
  ; GFX90A-NEXT:   $agpr128 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 508, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.98, addrspace 5)
  ; GFX90A-NEXT:   $agpr127 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 512, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.97, addrspace 5)
  ; GFX90A-NEXT:   $agpr126 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 516, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.96, addrspace 5)
  ; GFX90A-NEXT:   $agpr125 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 520, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.95, addrspace 5)
  ; GFX90A-NEXT:   $agpr124 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 524, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.94, addrspace 5)
  ; GFX90A-NEXT:   $agpr123 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 528, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.93, addrspace 5)
  ; GFX90A-NEXT:   $agpr122 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 532, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.92, addrspace 5)
  ; GFX90A-NEXT:   $agpr121 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 536, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.91, addrspace 5)
  ; GFX90A-NEXT:   $agpr120 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 540, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.90, addrspace 5)
  ; GFX90A-NEXT:   $agpr119 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 544, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.89, addrspace 5)
  ; GFX90A-NEXT:   $agpr118 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 548, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.88, addrspace 5)
  ; GFX90A-NEXT:   $agpr117 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 552, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.87, addrspace 5)
  ; GFX90A-NEXT:   $agpr116 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 556, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.86, addrspace 5)
  ; GFX90A-NEXT:   $agpr115 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 560, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.85, addrspace 5)
  ; GFX90A-NEXT:   $agpr114 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 564, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.84, addrspace 5)
  ; GFX90A-NEXT:   $agpr113 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 568, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.83, addrspace 5)
  ; GFX90A-NEXT:   $agpr112 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 572, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.82, addrspace 5)
  ; GFX90A-NEXT:   $agpr111 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 576, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.81, addrspace 5)
  ; GFX90A-NEXT:   $agpr110 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 580, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.80, addrspace 5)
  ; GFX90A-NEXT:   $agpr109 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 584, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.79, addrspace 5)
  ; GFX90A-NEXT:   $agpr108 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 588, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.78, addrspace 5)
  ; GFX90A-NEXT:   $agpr107 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 592, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.77, addrspace 5)
  ; GFX90A-NEXT:   $agpr106 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 596, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.76, addrspace 5)
  ; GFX90A-NEXT:   $agpr105 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 600, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.75, addrspace 5)
  ; GFX90A-NEXT:   $agpr104 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 604, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.74, addrspace 5)
  ; GFX90A-NEXT:   $agpr103 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 608, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.73, addrspace 5)
  ; GFX90A-NEXT:   $agpr102 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 612, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.72, addrspace 5)
  ; GFX90A-NEXT:   $agpr101 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 616, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.71, addrspace 5)
  ; GFX90A-NEXT:   $agpr100 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 620, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.70, addrspace 5)
  ; GFX90A-NEXT:   $agpr99 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 624, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.69, addrspace 5)
  ; GFX90A-NEXT:   $agpr98 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 628, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.68, addrspace 5)
  ; GFX90A-NEXT:   $agpr97 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 632, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.67, addrspace 5)
  ; GFX90A-NEXT:   $agpr96 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 636, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.66, addrspace 5)
  ; GFX90A-NEXT:   $agpr95 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 640, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.65, addrspace 5)
  ; GFX90A-NEXT:   $agpr94 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 644, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.64, addrspace 5)
  ; GFX90A-NEXT:   $agpr93 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 648, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.63, addrspace 5)
  ; GFX90A-NEXT:   $agpr92 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 652, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.62, addrspace 5)
  ; GFX90A-NEXT:   $agpr91 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 656, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.61, addrspace 5)
  ; GFX90A-NEXT:   $agpr90 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 660, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.60, addrspace 5)
  ; GFX90A-NEXT:   $agpr89 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 664, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.59, addrspace 5)
  ; GFX90A-NEXT:   $agpr88 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 668, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.58, addrspace 5)
  ; GFX90A-NEXT:   $agpr87 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 672, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.57, addrspace 5)
  ; GFX90A-NEXT:   $agpr86 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 676, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.56, addrspace 5)
  ; GFX90A-NEXT:   $agpr85 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 680, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.55, addrspace 5)
  ; GFX90A-NEXT:   $agpr84 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 684, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.54, addrspace 5)
  ; GFX90A-NEXT:   $agpr83 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 688, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.53, addrspace 5)
  ; GFX90A-NEXT:   $agpr82 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 692, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.52, addrspace 5)
  ; GFX90A-NEXT:   $agpr81 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 696, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.51, addrspace 5)
  ; GFX90A-NEXT:   $agpr80 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 700, 0, 0, implicit $exec :: ("amdgpu-non-volatile" load (s32) from %stack.50, addrspace 5)
  ; GFX90A-NEXT:   $agpr79 = V_ACCVGPR_WRITE_B32_e64 $vgpr55, implicit $exec
  ; GFX90A-NEXT:   $agpr78 = V_ACCVGPR_WRITE_B32_e64 $vgpr54, implicit $exec
  ; GFX90A-NEXT:   $agpr77 = V_ACCVGPR_WRITE_B32_e64 $vgpr53, implicit $exec
  ; GFX90A-NEXT:   $agpr76 = V_ACCVGPR_WRITE_B32_e64 $vgpr52, implicit $exec
  ; GFX90A-NEXT:   $agpr75 = V_ACCVGPR_WRITE_B32_e64 $vgpr51, implicit $exec
  ; GFX90A-NEXT:   $agpr74 = V_ACCVGPR_WRITE_B32_e64 $vgpr50, implicit $exec
  ; GFX90A-NEXT:   $agpr73 = V_ACCVGPR_WRITE_B32_e64 $vgpr49, implicit $exec
  ; GFX90A-NEXT:   $agpr72 = V_ACCVGPR_WRITE_B32_e64 $vgpr48, implicit $exec
  ; GFX90A-NEXT:   $agpr71 = V_ACCVGPR_WRITE_B32_e64 $vgpr39, implicit $exec
  ; GFX90A-NEXT:   $agpr70 = V_ACCVGPR_WRITE_B32_e64 $vgpr38, implicit $exec
  ; GFX90A-NEXT:   $agpr69 = V_ACCVGPR_WRITE_B32_e64 $vgpr37, implicit $exec
  ; GFX90A-NEXT:   $agpr68 = V_ACCVGPR_WRITE_B32_e64 $vgpr36, implicit $exec
  ; GFX90A-NEXT:   $agpr67 = V_ACCVGPR_WRITE_B32_e64 $vgpr35, implicit $exec
  ; GFX90A-NEXT:   $agpr66 = V_ACCVGPR_WRITE_B32_e64 $vgpr34, implicit $exec
  ; GFX90A-NEXT:   $agpr65 = V_ACCVGPR_WRITE_B32_e64 $vgpr33, implicit $exec
  ; GFX90A-NEXT:   $agpr64 = V_ACCVGPR_WRITE_B32_e64 $vgpr32, implicit $exec
  ; GFX90A-NEXT:   $agpr63 = V_ACCVGPR_WRITE_B32_e64 $vgpr31, implicit $exec
  ; GFX90A-NEXT:   $agpr62 = V_ACCVGPR_WRITE_B32_e64 $vgpr30, implicit $exec
  ; GFX90A-NEXT:   $agpr61 = V_ACCVGPR_WRITE_B32_e64 $vgpr29, implicit $exec
  ; GFX90A-NEXT:   $agpr60 = V_ACCVGPR_WRITE_B32_e64 $vgpr28, implicit $exec
  ; GFX90A-NEXT:   $agpr59 = V_ACCVGPR_WRITE_B32_e64 $vgpr27, implicit $exec
  ; GFX90A-NEXT:   $agpr58 = V_ACCVGPR_WRITE_B32_e64 $vgpr26, implicit $exec
  ; GFX90A-NEXT:   $agpr57 = V_ACCVGPR_WRITE_B32_e64 $vgpr25, implicit $exec
  ; GFX90A-NEXT:   $agpr56 = V_ACCVGPR_WRITE_B32_e64 $vgpr24, implicit $exec
  ; GFX90A-NEXT:   $agpr55 = V_ACCVGPR_WRITE_B32_e64 $vgpr23, implicit $exec
  ; GFX90A-NEXT:   $agpr54 = V_ACCVGPR_WRITE_B32_e64 $vgpr22, implicit $exec
  ; GFX90A-NEXT:   $agpr53 = V_ACCVGPR_WRITE_B32_e64 $vgpr21, implicit $exec
  ; GFX90A-NEXT:   $agpr52 = V_ACCVGPR_WRITE_B32_e64 $vgpr20, implicit $exec
  ; GFX90A-NEXT:   $agpr51 = V_ACCVGPR_WRITE_B32_e64 $vgpr19, implicit $exec
  ; GFX90A-NEXT:   $agpr50 = V_ACCVGPR_WRITE_B32_e64 $vgpr18, implicit $exec
  ; GFX90A-NEXT:   $agpr49 = V_ACCVGPR_WRITE_B32_e64 $vgpr17, implicit $exec
  ; GFX90A-NEXT:   $agpr48 = V_ACCVGPR_WRITE_B32_e64 $vgpr16, implicit $exec
  ; GFX90A-NEXT:   $agpr47 = V_ACCVGPR_WRITE_B32_e64 $vgpr15, implicit $exec
  ; GFX90A-NEXT:   $agpr46 = V_ACCVGPR_WRITE_B32_e64 $vgpr14, implicit $exec
  ; GFX90A-NEXT:   $agpr45 = V_ACCVGPR_WRITE_B32_e64 $vgpr13, implicit $exec
  ; GFX90A-NEXT:   $agpr44 = V_ACCVGPR_WRITE_B32_e64 $vgpr12, implicit $exec
  ; GFX90A-NEXT:   $agpr43 = V_ACCVGPR_WRITE_B32_e64 $vgpr11, implicit $exec
  ; GFX90A-NEXT:   $agpr42 = V_ACCVGPR_WRITE_B32_e64 $vgpr10, implicit $exec
  ; GFX90A-NEXT:   $agpr41 = V_ACCVGPR_WRITE_B32_e64 $vgpr9, implicit $exec
  ; GFX90A-NEXT:   $agpr40 = V_ACCVGPR_WRITE_B32_e64 $vgpr8, implicit $exec
  ; GFX90A-NEXT:   $agpr39 = V_ACCVGPR_WRITE_B32_e64 $vgpr7, implicit $exec
  ; GFX90A-NEXT:   $agpr38 = V_ACCVGPR_WRITE_B32_e64 $vgpr6, implicit $exec
  ; GFX90A-NEXT:   $agpr37 = V_ACCVGPR_WRITE_B32_e64 $vgpr5, implicit $exec
  ; GFX90A-NEXT:   $agpr36 = V_ACCVGPR_WRITE_B32_e64 $vgpr4, implicit $exec
  ; GFX90A-NEXT:   $agpr35 = V_ACCVGPR_WRITE_B32_e64 $vgpr3, implicit $exec
  ; GFX90A-NEXT:   $agpr34 = V_ACCVGPR_WRITE_B32_e64 $vgpr2, implicit $exec
  ; GFX90A-NEXT:   $agpr33 = V_ACCVGPR_WRITE_B32_e64 $vgpr1, implicit $exec
  ; GFX90A-NEXT:   $agpr32 = V_ACCVGPR_WRITE_B32_e64 $vgpr0, implicit $exec
  ; GFX90A-NEXT:   S_ENDPGM 0, amdgpu_allvgprs
  ;
  ; GFX908-FLATSCR-LABEL: name: agpr96_save_clobber_scc
  ; GFX908-FLATSCR: bb.0:
  ; GFX908-FLATSCR-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GFX908-FLATSCR-NEXT:   liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $agpr0_agpr1
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT:   S_CMP_EQ_U32 0, 0, implicit-def $scc
  ; GFX908-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $vgpr1, $sgpr32, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.2, addrspace 5)
  ; GFX908-FLATSCR-NEXT:   $vgpr1 = V_MOV_B32_e32 $sgpr32, implicit $exec
  ; GFX908-FLATSCR-NEXT:   $vgpr1 = V_ADD_U32_e32 8200, $vgpr1, implicit $exec
  ; GFX908-FLATSCR-NEXT:   $vgpr0 = V_ACCVGPR_READ_B32_e64 $agpr0, implicit $exec, implicit-def $agpr0_agpr1_agpr2, implicit $agpr0_agpr1_agpr2
  ; GFX908-FLATSCR-NEXT:   SCRATCH_STORE_DWORD $vgpr0, $vgpr1, 0, 0, implicit $exec, implicit $flat_scr, implicit $agpr0_agpr1_agpr2 :: ("amdgpu-non-volatile" store (s32) into %stack.1, addrspace 5)
  ; GFX908-FLATSCR-NEXT:   $vgpr0 = V_ACCVGPR_READ_B32_e64 $agpr1, implicit $exec
  ; GFX908-FLATSCR-NEXT:   SCRATCH_STORE_DWORD $vgpr0, $vgpr1, 4, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.1 + 4, addrspace 5)
  ; GFX908-FLATSCR-NEXT:   $vgpr0 = V_ACCVGPR_READ_B32_e64 $agpr2, implicit $exec, implicit $agpr0_agpr1_agpr2
  ; GFX908-FLATSCR-NEXT:   SCRATCH_STORE_DWORD $vgpr0, $vgpr1, 8, 0, implicit $exec, implicit $flat_scr, implicit $agpr0_agpr1_agpr2 :: ("amdgpu-non-volatile" store (s32) into %stack.1 + 8, addrspace 5)
  ; GFX908-FLATSCR-NEXT:   $vgpr1 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.2, addrspace 5)
  ; GFX908-FLATSCR-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT: bb.1:
  ; GFX908-FLATSCR-NEXT:   successors: %bb.2(0x80000000)
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT:   S_NOP 0
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT: bb.2:
  ; GFX908-FLATSCR-NEXT:   liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $agpr0_agpr1
  ; GFX908-FLATSCR-NEXT: {{  $}}
  ; GFX908-FLATSCR-NEXT:   S_ENDPGM 0, amdgpu_allvgprs
  ;
  ; GFX90A-FLATSCR-LABEL: name: agpr96_save_clobber_scc
  ; GFX90A-FLATSCR: bb.0:
  ; GFX90A-FLATSCR-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GFX90A-FLATSCR-NEXT:   liveins: $agpr32, $agpr33, $agpr34, $agpr35, $agpr36, $agpr37, $agpr38, $agpr39, $agpr40, $agpr41, $agpr42, $agpr43, $agpr44, $agpr45, $agpr46, $agpr47, $agpr48, $agpr49, $agpr50, $agpr51, $agpr52, $agpr53, $agpr54, $agpr55, $agpr56, $agpr57, $agpr58, $agpr59, $agpr60, $agpr61, $agpr62, $agpr63, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55, $agpr0_agpr1, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT:   $vgpr0 = V_ACCVGPR_READ_B32_e64 killed $agpr32, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr1 = V_ACCVGPR_READ_B32_e64 killed $agpr33, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr2 = V_ACCVGPR_READ_B32_e64 killed $agpr34, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr3 = V_ACCVGPR_READ_B32_e64 killed $agpr35, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr4 = V_ACCVGPR_READ_B32_e64 killed $agpr36, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr5 = V_ACCVGPR_READ_B32_e64 killed $agpr37, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr6 = V_ACCVGPR_READ_B32_e64 killed $agpr38, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr7 = V_ACCVGPR_READ_B32_e64 killed $agpr39, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr8 = V_ACCVGPR_READ_B32_e64 killed $agpr40, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr9 = V_ACCVGPR_READ_B32_e64 killed $agpr41, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr10 = V_ACCVGPR_READ_B32_e64 killed $agpr42, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr11 = V_ACCVGPR_READ_B32_e64 killed $agpr43, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr12 = V_ACCVGPR_READ_B32_e64 killed $agpr44, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr13 = V_ACCVGPR_READ_B32_e64 killed $agpr45, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr14 = V_ACCVGPR_READ_B32_e64 killed $agpr46, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr15 = V_ACCVGPR_READ_B32_e64 killed $agpr47, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr16 = V_ACCVGPR_READ_B32_e64 killed $agpr48, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr17 = V_ACCVGPR_READ_B32_e64 killed $agpr49, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr18 = V_ACCVGPR_READ_B32_e64 killed $agpr50, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr19 = V_ACCVGPR_READ_B32_e64 killed $agpr51, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr20 = V_ACCVGPR_READ_B32_e64 killed $agpr52, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr21 = V_ACCVGPR_READ_B32_e64 killed $agpr53, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr22 = V_ACCVGPR_READ_B32_e64 killed $agpr54, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr23 = V_ACCVGPR_READ_B32_e64 killed $agpr55, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr24 = V_ACCVGPR_READ_B32_e64 killed $agpr56, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr25 = V_ACCVGPR_READ_B32_e64 killed $agpr57, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr26 = V_ACCVGPR_READ_B32_e64 killed $agpr58, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr27 = V_ACCVGPR_READ_B32_e64 killed $agpr59, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr28 = V_ACCVGPR_READ_B32_e64 killed $agpr60, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr29 = V_ACCVGPR_READ_B32_e64 killed $agpr61, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr30 = V_ACCVGPR_READ_B32_e64 killed $agpr62, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr31 = V_ACCVGPR_READ_B32_e64 killed $agpr63, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr32 = V_ACCVGPR_READ_B32_e64 killed $agpr64, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr33 = V_ACCVGPR_READ_B32_e64 killed $agpr65, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr34 = V_ACCVGPR_READ_B32_e64 killed $agpr66, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr35 = V_ACCVGPR_READ_B32_e64 killed $agpr67, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr36 = V_ACCVGPR_READ_B32_e64 killed $agpr68, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr37 = V_ACCVGPR_READ_B32_e64 killed $agpr69, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr38 = V_ACCVGPR_READ_B32_e64 killed $agpr70, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr39 = V_ACCVGPR_READ_B32_e64 killed $agpr71, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr48 = V_ACCVGPR_READ_B32_e64 killed $agpr72, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr49 = V_ACCVGPR_READ_B32_e64 killed $agpr73, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr50 = V_ACCVGPR_READ_B32_e64 killed $agpr74, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr51 = V_ACCVGPR_READ_B32_e64 killed $agpr75, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr52 = V_ACCVGPR_READ_B32_e64 killed $agpr76, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr53 = V_ACCVGPR_READ_B32_e64 killed $agpr77, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr54 = V_ACCVGPR_READ_B32_e64 killed $agpr78, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr55 = V_ACCVGPR_READ_B32_e64 killed $agpr79, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr80, $sgpr32, 700, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.50, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr81, $sgpr32, 696, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.51, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr82, $sgpr32, 692, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.52, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr83, $sgpr32, 688, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.53, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr84, $sgpr32, 684, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.54, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr85, $sgpr32, 680, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.55, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr86, $sgpr32, 676, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.56, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr87, $sgpr32, 672, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.57, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr88, $sgpr32, 668, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.58, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr89, $sgpr32, 664, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.59, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr90, $sgpr32, 660, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.60, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr91, $sgpr32, 656, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.61, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr92, $sgpr32, 652, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.62, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr93, $sgpr32, 648, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.63, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr94, $sgpr32, 644, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.64, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr95, $sgpr32, 640, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.65, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr96, $sgpr32, 636, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.66, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr97, $sgpr32, 632, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.67, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr98, $sgpr32, 628, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.68, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr99, $sgpr32, 624, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.69, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr100, $sgpr32, 620, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.70, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr101, $sgpr32, 616, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.71, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr102, $sgpr32, 612, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.72, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr103, $sgpr32, 608, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.73, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr104, $sgpr32, 604, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.74, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr105, $sgpr32, 600, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.75, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr106, $sgpr32, 596, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.76, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr107, $sgpr32, 592, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.77, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr108, $sgpr32, 588, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.78, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr109, $sgpr32, 584, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.79, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr110, $sgpr32, 580, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.80, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr111, $sgpr32, 576, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.81, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr112, $sgpr32, 572, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.82, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr113, $sgpr32, 568, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.83, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr114, $sgpr32, 564, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.84, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr115, $sgpr32, 560, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.85, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr116, $sgpr32, 556, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.86, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr117, $sgpr32, 552, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.87, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr118, $sgpr32, 548, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.88, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr119, $sgpr32, 544, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.89, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr120, $sgpr32, 540, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.90, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr121, $sgpr32, 536, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.91, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr122, $sgpr32, 532, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.92, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr123, $sgpr32, 528, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.93, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr124, $sgpr32, 524, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.94, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr125, $sgpr32, 520, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.95, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr126, $sgpr32, 516, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.96, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr127, $sgpr32, 512, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.97, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr128, $sgpr32, 508, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.98, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr129, $sgpr32, 504, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.99, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr130, $sgpr32, 500, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.100, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr131, $sgpr32, 496, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.101, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr132, $sgpr32, 492, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.102, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr133, $sgpr32, 488, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.103, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr134, $sgpr32, 484, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.104, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr135, $sgpr32, 480, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.105, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr136, $sgpr32, 476, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.106, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr137, $sgpr32, 472, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.107, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr138, $sgpr32, 468, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.108, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr139, $sgpr32, 464, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.109, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr140, $sgpr32, 460, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.110, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr141, $sgpr32, 456, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.111, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr142, $sgpr32, 452, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.112, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr143, $sgpr32, 448, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.113, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr144, $sgpr32, 444, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.114, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr145, $sgpr32, 440, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.115, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr146, $sgpr32, 436, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.116, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr147, $sgpr32, 432, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.117, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr148, $sgpr32, 428, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.118, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr149, $sgpr32, 424, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.119, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr150, $sgpr32, 420, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.120, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr151, $sgpr32, 416, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.121, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr152, $sgpr32, 412, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.122, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr153, $sgpr32, 408, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.123, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr154, $sgpr32, 404, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.124, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr155, $sgpr32, 400, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.125, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr156, $sgpr32, 396, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.126, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr157, $sgpr32, 392, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.127, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr158, $sgpr32, 388, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.128, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr159, $sgpr32, 384, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.129, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr160, $sgpr32, 380, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.130, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr161, $sgpr32, 376, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.131, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr162, $sgpr32, 372, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.132, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr163, $sgpr32, 368, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.133, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr164, $sgpr32, 364, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.134, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr165, $sgpr32, 360, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.135, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr166, $sgpr32, 356, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.136, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr167, $sgpr32, 352, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.137, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr168, $sgpr32, 348, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.138, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr169, $sgpr32, 344, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.139, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr170, $sgpr32, 340, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.140, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr171, $sgpr32, 336, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.141, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr172, $sgpr32, 332, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.142, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr173, $sgpr32, 328, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.143, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr174, $sgpr32, 324, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.144, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr175, $sgpr32, 320, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.145, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr176, $sgpr32, 316, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.146, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr177, $sgpr32, 312, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.147, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr178, $sgpr32, 308, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.148, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr179, $sgpr32, 304, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.149, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr180, $sgpr32, 300, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.150, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr181, $sgpr32, 296, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.151, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr182, $sgpr32, 292, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.152, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr183, $sgpr32, 288, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.153, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr184, $sgpr32, 284, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.154, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr185, $sgpr32, 280, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.155, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr186, $sgpr32, 276, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.156, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr187, $sgpr32, 272, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.157, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr188, $sgpr32, 268, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.158, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr189, $sgpr32, 264, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.159, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr190, $sgpr32, 260, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.160, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr191, $sgpr32, 256, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.161, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr192, $sgpr32, 252, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.162, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr193, $sgpr32, 248, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.163, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr194, $sgpr32, 244, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.164, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr195, $sgpr32, 240, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.165, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr196, $sgpr32, 236, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.166, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr197, $sgpr32, 232, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.167, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr198, $sgpr32, 228, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.168, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr199, $sgpr32, 224, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.169, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr200, $sgpr32, 220, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.170, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr201, $sgpr32, 216, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.171, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr202, $sgpr32, 212, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.172, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr203, $sgpr32, 208, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.173, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr204, $sgpr32, 204, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.174, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr205, $sgpr32, 200, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.175, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr206, $sgpr32, 196, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.176, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr207, $sgpr32, 192, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.177, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr208, $sgpr32, 188, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.178, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr209, $sgpr32, 184, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.179, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr210, $sgpr32, 180, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.180, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr211, $sgpr32, 176, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.181, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr212, $sgpr32, 172, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.182, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr213, $sgpr32, 168, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.183, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr214, $sgpr32, 164, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.184, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr215, $sgpr32, 160, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.185, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr216, $sgpr32, 156, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.186, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr217, $sgpr32, 152, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.187, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr218, $sgpr32, 148, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.188, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr219, $sgpr32, 144, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.189, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr220, $sgpr32, 140, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.190, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr221, $sgpr32, 136, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.191, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr222, $sgpr32, 132, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.192, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr223, $sgpr32, 128, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.193, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr224, $sgpr32, 124, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.194, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr225, $sgpr32, 120, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.195, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr226, $sgpr32, 116, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.196, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr227, $sgpr32, 112, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.197, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr228, $sgpr32, 108, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.198, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr229, $sgpr32, 104, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.199, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr230, $sgpr32, 100, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.200, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr231, $sgpr32, 96, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.201, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr232, $sgpr32, 92, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.202, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr233, $sgpr32, 88, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.203, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr234, $sgpr32, 84, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.204, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr235, $sgpr32, 80, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.205, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr236, $sgpr32, 76, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.206, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr237, $sgpr32, 72, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.207, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr238, $sgpr32, 68, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.208, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr239, $sgpr32, 64, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.209, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr240, $sgpr32, 60, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.210, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr241, $sgpr32, 56, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.211, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr242, $sgpr32, 52, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.212, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr243, $sgpr32, 48, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.213, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr244, $sgpr32, 44, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.214, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr245, $sgpr32, 40, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.215, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr246, $sgpr32, 36, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.216, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr247, $sgpr32, 32, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.217, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr248, $sgpr32, 28, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.218, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr249, $sgpr32, 24, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.219, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr250, $sgpr32, 20, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.220, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr251, $sgpr32, 16, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.221, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr252, $sgpr32, 12, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.222, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr253, $sgpr32, 8, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.223, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr254, $sgpr32, 4, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.224, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $agpr255, $sgpr32, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.225, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   S_CMP_EQ_U32 0, 0, implicit-def $scc
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORD_SADDR killed $vgpr40, $sgpr32, 704, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s32) into %stack.226, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $vgpr40 = V_MOV_B32_e32 $sgpr32, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $vgpr40 = V_ADD_U32_e32 8904, $vgpr40, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   SCRATCH_STORE_DWORDX3 $agpr0_agpr1_agpr2, killed $vgpr40, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" store (s96) into %stack.1, align 4, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $vgpr40 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 704, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.226, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT: bb.1:
  ; GFX90A-FLATSCR-NEXT:   successors: %bb.2(0x80000000)
  ; GFX90A-FLATSCR-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT:   S_NOP 0
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT: bb.2:
  ; GFX90A-FLATSCR-NEXT:   liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6, $vgpr7, $vgpr8, $vgpr9, $vgpr10, $vgpr11, $vgpr12, $vgpr13, $vgpr14, $vgpr15, $vgpr16, $vgpr17, $vgpr18, $vgpr19, $vgpr20, $vgpr21, $vgpr22, $vgpr23, $vgpr24, $vgpr25, $vgpr26, $vgpr27, $vgpr28, $vgpr29, $vgpr30, $vgpr31, $vgpr32, $vgpr33, $vgpr34, $vgpr35, $vgpr36, $vgpr37, $vgpr38, $vgpr39, $vgpr48, $vgpr49, $vgpr50, $vgpr51, $vgpr52, $vgpr53, $vgpr54, $vgpr55, $agpr0_agpr1, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239
  ; GFX90A-FLATSCR-NEXT: {{  $}}
  ; GFX90A-FLATSCR-NEXT:   $agpr255 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 0, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.225, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr254 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 4, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.224, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr253 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 8, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.223, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr252 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 12, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.222, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr251 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 16, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.221, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr250 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 20, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.220, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr249 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 24, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.219, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr248 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 28, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.218, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr247 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 32, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.217, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr246 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 36, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.216, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr245 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 40, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.215, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr244 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 44, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.214, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr243 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 48, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.213, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr242 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 52, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.212, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr241 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 56, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.211, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr240 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 60, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.210, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr239 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 64, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.209, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr238 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 68, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.208, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr237 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 72, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.207, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr236 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 76, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.206, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr235 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 80, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.205, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr234 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 84, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.204, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr233 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 88, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.203, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr232 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 92, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.202, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr231 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 96, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.201, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr230 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 100, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.200, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr229 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 104, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.199, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr228 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 108, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.198, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr227 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 112, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.197, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr226 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 116, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.196, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr225 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 120, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.195, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr224 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 124, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.194, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr223 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 128, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.193, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr222 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 132, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.192, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr221 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 136, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.191, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr220 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 140, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.190, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr219 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 144, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.189, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr218 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 148, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.188, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr217 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 152, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.187, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr216 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 156, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.186, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr215 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 160, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.185, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr214 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 164, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.184, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr213 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 168, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.183, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr212 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 172, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.182, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr211 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 176, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.181, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr210 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 180, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.180, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr209 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 184, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.179, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr208 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 188, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.178, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr207 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 192, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.177, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr206 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 196, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.176, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr205 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 200, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.175, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr204 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 204, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.174, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr203 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 208, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.173, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr202 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 212, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.172, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr201 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 216, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.171, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr200 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 220, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.170, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr199 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 224, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.169, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr198 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 228, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.168, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr197 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 232, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.167, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr196 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 236, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.166, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr195 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 240, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.165, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr194 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 244, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.164, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr193 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 248, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.163, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr192 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 252, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.162, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr191 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 256, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.161, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr190 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 260, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.160, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr189 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 264, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.159, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr188 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 268, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.158, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr187 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 272, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.157, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr186 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 276, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.156, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr185 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 280, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.155, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr184 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 284, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.154, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr183 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 288, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.153, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr182 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 292, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.152, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr181 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 296, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.151, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr180 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 300, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.150, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr179 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 304, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.149, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr178 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 308, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.148, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr177 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 312, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.147, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr176 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 316, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.146, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr175 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 320, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.145, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr174 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 324, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.144, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr173 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 328, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.143, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr172 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 332, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.142, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr171 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 336, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.141, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr170 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 340, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.140, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr169 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 344, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.139, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr168 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 348, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.138, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr167 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 352, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.137, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr166 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 356, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.136, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr165 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 360, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.135, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr164 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 364, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.134, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr163 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 368, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.133, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr162 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 372, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.132, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr161 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 376, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.131, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr160 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 380, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.130, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr159 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 384, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.129, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr158 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 388, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.128, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr157 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 392, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.127, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr156 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 396, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.126, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr155 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 400, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.125, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr154 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 404, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.124, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr153 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 408, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.123, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr152 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 412, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.122, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr151 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 416, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.121, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr150 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 420, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.120, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr149 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 424, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.119, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr148 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 428, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.118, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr147 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 432, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.117, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr146 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 436, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.116, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr145 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 440, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.115, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr144 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 444, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.114, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr143 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 448, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.113, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr142 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 452, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.112, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr141 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 456, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.111, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr140 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 460, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.110, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr139 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 464, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.109, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr138 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 468, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.108, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr137 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 472, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.107, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr136 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 476, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.106, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr135 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 480, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.105, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr134 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 484, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.104, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr133 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 488, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.103, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr132 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 492, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.102, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr131 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 496, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.101, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr130 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 500, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.100, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr129 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 504, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.99, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr128 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 508, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.98, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr127 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 512, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.97, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr126 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 516, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.96, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr125 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 520, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.95, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr124 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 524, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.94, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr123 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 528, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.93, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr122 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 532, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.92, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr121 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 536, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.91, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr120 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 540, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.90, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr119 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 544, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.89, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr118 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 548, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.88, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr117 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 552, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.87, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr116 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 556, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.86, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr115 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 560, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.85, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr114 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 564, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.84, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr113 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 568, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.83, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr112 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 572, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.82, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr111 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 576, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.81, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr110 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 580, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.80, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr109 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 584, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.79, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr108 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 588, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.78, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr107 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 592, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.77, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr106 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 596, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.76, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr105 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 600, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.75, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr104 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 604, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.74, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr103 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 608, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.73, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr102 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 612, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.72, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr101 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 616, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.71, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr100 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 620, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.70, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr99 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 624, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.69, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr98 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 628, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.68, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr97 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 632, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.67, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr96 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 636, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.66, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr95 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 640, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.65, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr94 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 644, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.64, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr93 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 648, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.63, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr92 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 652, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.62, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr91 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 656, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.61, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr90 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 660, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.60, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr89 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 664, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.59, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr88 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 668, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.58, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr87 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 672, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.57, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr86 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 676, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.56, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr85 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 680, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.55, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr84 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 684, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.54, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr83 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 688, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.53, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr82 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 692, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.52, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr81 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 696, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.51, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr80 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 700, 0, implicit $exec, implicit $flat_scr :: ("amdgpu-non-volatile" load (s32) from %stack.50, addrspace 5)
  ; GFX90A-FLATSCR-NEXT:   $agpr79 = V_ACCVGPR_WRITE_B32_e64 $vgpr55, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr78 = V_ACCVGPR_WRITE_B32_e64 $vgpr54, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr77 = V_ACCVGPR_WRITE_B32_e64 $vgpr53, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr76 = V_ACCVGPR_WRITE_B32_e64 $vgpr52, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr75 = V_ACCVGPR_WRITE_B32_e64 $vgpr51, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr74 = V_ACCVGPR_WRITE_B32_e64 $vgpr50, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr73 = V_ACCVGPR_WRITE_B32_e64 $vgpr49, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr72 = V_ACCVGPR_WRITE_B32_e64 $vgpr48, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr71 = V_ACCVGPR_WRITE_B32_e64 $vgpr39, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr70 = V_ACCVGPR_WRITE_B32_e64 $vgpr38, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr69 = V_ACCVGPR_WRITE_B32_e64 $vgpr37, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr68 = V_ACCVGPR_WRITE_B32_e64 $vgpr36, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr67 = V_ACCVGPR_WRITE_B32_e64 $vgpr35, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr66 = V_ACCVGPR_WRITE_B32_e64 $vgpr34, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr65 = V_ACCVGPR_WRITE_B32_e64 $vgpr33, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr64 = V_ACCVGPR_WRITE_B32_e64 $vgpr32, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr63 = V_ACCVGPR_WRITE_B32_e64 $vgpr31, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr62 = V_ACCVGPR_WRITE_B32_e64 $vgpr30, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr61 = V_ACCVGPR_WRITE_B32_e64 $vgpr29, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr60 = V_ACCVGPR_WRITE_B32_e64 $vgpr28, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr59 = V_ACCVGPR_WRITE_B32_e64 $vgpr27, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr58 = V_ACCVGPR_WRITE_B32_e64 $vgpr26, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr57 = V_ACCVGPR_WRITE_B32_e64 $vgpr25, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr56 = V_ACCVGPR_WRITE_B32_e64 $vgpr24, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr55 = V_ACCVGPR_WRITE_B32_e64 $vgpr23, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr54 = V_ACCVGPR_WRITE_B32_e64 $vgpr22, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr53 = V_ACCVGPR_WRITE_B32_e64 $vgpr21, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr52 = V_ACCVGPR_WRITE_B32_e64 $vgpr20, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr51 = V_ACCVGPR_WRITE_B32_e64 $vgpr19, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr50 = V_ACCVGPR_WRITE_B32_e64 $vgpr18, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr49 = V_ACCVGPR_WRITE_B32_e64 $vgpr17, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr48 = V_ACCVGPR_WRITE_B32_e64 $vgpr16, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr47 = V_ACCVGPR_WRITE_B32_e64 $vgpr15, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr46 = V_ACCVGPR_WRITE_B32_e64 $vgpr14, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr45 = V_ACCVGPR_WRITE_B32_e64 $vgpr13, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr44 = V_ACCVGPR_WRITE_B32_e64 $vgpr12, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr43 = V_ACCVGPR_WRITE_B32_e64 $vgpr11, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr42 = V_ACCVGPR_WRITE_B32_e64 $vgpr10, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr41 = V_ACCVGPR_WRITE_B32_e64 $vgpr9, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr40 = V_ACCVGPR_WRITE_B32_e64 $vgpr8, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr39 = V_ACCVGPR_WRITE_B32_e64 $vgpr7, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr38 = V_ACCVGPR_WRITE_B32_e64 $vgpr6, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr37 = V_ACCVGPR_WRITE_B32_e64 $vgpr5, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr36 = V_ACCVGPR_WRITE_B32_e64 $vgpr4, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr35 = V_ACCVGPR_WRITE_B32_e64 $vgpr3, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr34 = V_ACCVGPR_WRITE_B32_e64 $vgpr2, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr33 = V_ACCVGPR_WRITE_B32_e64 $vgpr1, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   $agpr32 = V_ACCVGPR_WRITE_B32_e64 $vgpr0, implicit $exec
  ; GFX90A-FLATSCR-NEXT:   S_ENDPGM 0, amdgpu_allvgprs
  bb.0:
    liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $agpr0_agpr1

    S_CMP_EQ_U32 0, 0, implicit-def $scc
    SI_SPILL_A96_SAVE $agpr0_agpr1_agpr2, %stack.1, $sgpr32, 0, implicit $exec :: (store (s64) into %stack.1, align 4, addrspace 5)
    S_CBRANCH_SCC1 %bb.2, implicit $scc

  bb.1:
    S_NOP 0

  bb.2:
    liveins: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15, $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31, $vgpr32_vgpr33_vgpr34_vgpr35_vgpr36_vgpr37_vgpr38_vgpr39_vgpr40_vgpr41_vgpr42_vgpr43_vgpr44_vgpr45_vgpr46_vgpr47, $vgpr48_vgpr49_vgpr50_vgpr51_vgpr52_vgpr53_vgpr54_vgpr55_vgpr56_vgpr57_vgpr58_vgpr59_vgpr60_vgpr61_vgpr62_vgpr63, $vgpr64_vgpr65_vgpr66_vgpr67_vgpr68_vgpr69_vgpr70_vgpr71_vgpr72_vgpr73_vgpr74_vgpr75_vgpr76_vgpr77_vgpr78_vgpr79, $vgpr80_vgpr81_vgpr82_vgpr83_vgpr84_vgpr85_vgpr86_vgpr87_vgpr88_vgpr89_vgpr90_vgpr91_vgpr92_vgpr93_vgpr94_vgpr95, $vgpr96_vgpr97_vgpr98_vgpr99_vgpr100_vgpr101_vgpr102_vgpr103_vgpr104_vgpr105_vgpr106_vgpr107_vgpr108_vgpr109_vgpr110_vgpr111, $vgpr112_vgpr113_vgpr114_vgpr115_vgpr116_vgpr117_vgpr118_vgpr119_vgpr120_vgpr121_vgpr122_vgpr123_vgpr124_vgpr125_vgpr126_vgpr127, $vgpr128_vgpr129_vgpr130_vgpr131_vgpr132_vgpr133_vgpr134_vgpr135_vgpr136_vgpr137_vgpr138_vgpr139_vgpr140_vgpr141_vgpr142_vgpr143, $vgpr144_vgpr145_vgpr146_vgpr147_vgpr148_vgpr149_vgpr150_vgpr151_vgpr152_vgpr153_vgpr154_vgpr155_vgpr156_vgpr157_vgpr158_vgpr159, $vgpr160_vgpr161_vgpr162_vgpr163_vgpr164_vgpr165_vgpr166_vgpr167_vgpr168_vgpr169_vgpr170_vgpr171_vgpr172_vgpr173_vgpr174_vgpr175, $vgpr176_vgpr177_vgpr178_vgpr179_vgpr180_vgpr181_vgpr182_vgpr183_vgpr184_vgpr185_vgpr186_vgpr187_vgpr188_vgpr189_vgpr190_vgpr191, $vgpr192_vgpr193_vgpr194_vgpr195_vgpr196_vgpr197_vgpr198_vgpr199_vgpr200_vgpr201_vgpr202_vgpr203_vgpr204_vgpr205_vgpr206_vgpr207, $vgpr208_vgpr209_vgpr210_vgpr211_vgpr212_vgpr213_vgpr214_vgpr215_vgpr216_vgpr217_vgpr218_vgpr219_vgpr220_vgpr221_vgpr222_vgpr223, $vgpr224_vgpr225_vgpr226_vgpr227_vgpr228_vgpr229_vgpr230_vgpr231_vgpr232_vgpr233_vgpr234_vgpr235_vgpr236_vgpr237_vgpr238_vgpr239, $vgpr240_vgpr241_vgpr242_vgpr243_vgpr244_vgpr245_vgpr246_vgpr247, $vgpr248_vgpr249_vgpr250_vgpr251, $vgpr252_vgpr253_vgpr254_vgpr255, $agpr0_agpr1
    S_ENDPGM 0, amdgpu_allvgprs
...
