; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mcpu=gfx1300 -global-isel=0 -o - %s | FileCheck -check-prefixes=CHECK,SDAG %s
; RUN: llc -mcpu=gfx1300 -global-isel=1 -o - %s | FileCheck -check-prefixes=CHECK,GISEL %s

target triple = "amdgcn-amd-amdhsa"

define ptr @laneshared_to_flat(ptr addrspace(10) %ptr) {
; SDAG-LABEL: laneshared_to_flat:
; SDAG:       ; %bb.0:
; SDAG-NEXT:    s_wait_loadcnt_dscnt 0x0
; SDAG-NEXT:    s_wait_expcnt 0x0
; SDAG-NEXT:    s_wait_samplecnt 0x0
; SDAG-NEXT:    s_wait_rtscnt 0x0
; SDAG-NEXT:    s_wait_kmcnt 0x0
; SDAG-NEXT:    v_mbcnt_lo_u32_b32 v1, -1, 0
; SDAG-NEXT:    s_mov_b64 s[0:1], src_flat_scratch_base_lo
; SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(VALU_DEP_2)
; SDAG-NEXT:    v_add_co_u32 v2, vcc_lo, v0, s0
; SDAG-NEXT:    v_lshlrev_b32_e32 v1, 20, v1
; SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; SDAG-NEXT:    v_add_co_ci_u32_e64 v1, null, s1, v1, vcc_lo
; SDAG-NEXT:    v_cmp_ne_u32_e32 vcc_lo, -1, v0
; SDAG-NEXT:    v_dual_cndmask_b32 v0, 0, v2 :: v_dual_cndmask_b32 v1, 0, v1
; SDAG-NEXT:    s_set_pc_i64 s[30:31]
;
; GISEL-LABEL: laneshared_to_flat:
; GISEL:       ; %bb.0:
; GISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GISEL-NEXT:    s_wait_expcnt 0x0
; GISEL-NEXT:    s_wait_samplecnt 0x0
; GISEL-NEXT:    s_wait_rtscnt 0x0
; GISEL-NEXT:    s_wait_kmcnt 0x0
; GISEL-NEXT:    v_dual_mov_b32 v1, src_flat_scratch_base_lo :: v_dual_mov_b32 v2, src_flat_scratch_base_hi
; GISEL-NEXT:    v_mbcnt_lo_u32_b32 v3, -1, 0
; GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GISEL-NEXT:    v_add_co_u32 v1, vcc_lo, v0, v1
; GISEL-NEXT:    v_lshlrev_b32_e32 v3, 20, v3
; GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GISEL-NEXT:    v_add_co_ci_u32_e64 v2, null, v3, v2, vcc_lo
; GISEL-NEXT:    v_cmp_ne_u32_e32 vcc_lo, -1, v0
; GISEL-NEXT:    v_dual_cndmask_b32 v0, 0, v1 :: v_dual_cndmask_b32 v1, 0, v2
; GISEL-NEXT:    s_set_pc_i64 s[30:31]
  %flat = addrspacecast ptr addrspace(10) %ptr to ptr
  ret ptr %flat
}

define ptr addrspace(10) @flat_to_laneshared(ptr %flat) {
; CHECK-LABEL: flat_to_laneshared:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_wait_loadcnt_dscnt 0x0
; CHECK-NEXT:    s_wait_expcnt 0x0
; CHECK-NEXT:    s_wait_samplecnt 0x0
; CHECK-NEXT:    s_wait_rtscnt 0x0
; CHECK-NEXT:    s_wait_kmcnt 0x0
; CHECK-NEXT:    v_cmp_ne_u64_e32 vcc_lo, 0, v[0:1]
; CHECK-NEXT:    v_subrev_nc_u32_e32 v2, src_flat_scratch_base_lo, v0
; CHECK-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; CHECK-NEXT:    v_cndmask_b32_e32 v0, -1, v2, vcc_lo
; CHECK-NEXT:    s_set_pc_i64 s[30:31]
  %ls = addrspacecast ptr %flat to ptr addrspace(10)
  ret ptr addrspace(10) %ls
}
