# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=amdgcn -mcpu=gfx908 %s -o - -run-pass machine-cp -verify-machineinstrs | FileCheck -check-prefix=GFX908 %s
# RUN: llc -mtriple=amdgcn -mcpu=gfx90a %s -o - -run-pass machine-cp -verify-machineinstrs | FileCheck -check-prefix=GFX90A %s

---
name:  propagate_agpr
body: |
  bb.0:
    successors:
    liveins: $agpr0

    ; GFX908-LABEL: name: propagate_agpr
    ; GFX908: liveins: $agpr0
    ; GFX908-NEXT: {{  $}}
    ; GFX908-NEXT: renamable $agpr1 = COPY renamable $agpr0, implicit $exec
    ; GFX908-NEXT: renamable $agpr2 = COPY $agpr0, implicit $exec
    ; GFX908-NEXT: renamable $agpr3 = COPY $agpr0, implicit $exec
    ; GFX908-NEXT: S_ENDPGM 0, implicit $agpr1, implicit $agpr2, implicit $agpr3
    ;
    ; GFX90A-LABEL: name: propagate_agpr
    ; GFX90A: liveins: $agpr0
    ; GFX90A-NEXT: {{  $}}
    ; GFX90A-NEXT: renamable $agpr1 = COPY renamable $agpr0, implicit $exec
    ; GFX90A-NEXT: renamable $agpr2 = COPY $agpr0, implicit $exec
    ; GFX90A-NEXT: renamable $agpr3 = COPY $agpr0, implicit $exec
    ; GFX90A-NEXT: S_ENDPGM 0, implicit $agpr1, implicit $agpr2, implicit $agpr3
    renamable $agpr1 = COPY renamable $agpr0, implicit $exec
    renamable $agpr2 = COPY renamable $agpr1, implicit $exec
    renamable $agpr3 = COPY renamable $agpr2, implicit $exec
    S_ENDPGM 0, implicit $agpr1, implicit $agpr2, implicit $agpr3
...
---
name:  do_not_propagate_agpr_to_agpr
body: |
  bb.0:
    successors:
    liveins: $agpr0

    ; GFX908-LABEL: name: do_not_propagate_agpr_to_agpr
    ; GFX908: liveins: $agpr0
    ; GFX908-NEXT: {{  $}}
    ; GFX908-NEXT: renamable $vgpr0 = COPY renamable $agpr0, implicit $exec
    ; GFX908-NEXT: renamable $agpr1 = COPY $agpr0, implicit $exec
    ; GFX908-NEXT: renamable $agpr2 = COPY $agpr0, implicit $exec
    ; GFX908-NEXT: S_ENDPGM 0, implicit $vgpr0, implicit $agpr1, implicit $agpr2
    ;
    ; GFX90A-LABEL: name: do_not_propagate_agpr_to_agpr
    ; GFX90A: liveins: $agpr0
    ; GFX90A-NEXT: {{  $}}
    ; GFX90A-NEXT: renamable $vgpr0 = COPY renamable $agpr0, implicit $exec
    ; GFX90A-NEXT: renamable $agpr1 = COPY $agpr0, implicit $exec
    ; GFX90A-NEXT: renamable $agpr2 = COPY $agpr0, implicit $exec
    ; GFX90A-NEXT: S_ENDPGM 0, implicit $vgpr0, implicit $agpr1, implicit $agpr2
    renamable $vgpr0 = COPY renamable $agpr0, implicit $exec
    renamable $agpr1 = COPY renamable $vgpr0, implicit $exec
    renamable $agpr2 = COPY renamable $vgpr0, implicit $exec
    S_ENDPGM 0, implicit $vgpr0, implicit $agpr1, implicit $agpr2
...
---
name:  propagate_vgpr_to_agpr
body: |
  bb.0:
    successors:
    liveins: $vgpr0

    ; GFX908-LABEL: name: propagate_vgpr_to_agpr
    ; GFX908: liveins: $vgpr0
    ; GFX908-NEXT: {{  $}}
    ; GFX908-NEXT: renamable $agpr0 = COPY renamable $vgpr0, implicit $exec
    ; GFX908-NEXT: renamable $agpr1 = COPY $vgpr0, implicit $exec
    ; GFX908-NEXT: renamable $agpr2 = COPY $vgpr0, implicit $exec
    ; GFX908-NEXT: S_ENDPGM 0, implicit $agpr0, implicit $agpr1, implicit $agpr2
    ;
    ; GFX90A-LABEL: name: propagate_vgpr_to_agpr
    ; GFX90A: liveins: $vgpr0
    ; GFX90A-NEXT: {{  $}}
    ; GFX90A-NEXT: renamable $agpr0 = COPY renamable $vgpr0, implicit $exec
    ; GFX90A-NEXT: renamable $agpr1 = COPY $vgpr0, implicit $exec
    ; GFX90A-NEXT: renamable $agpr2 = COPY $vgpr0, implicit $exec
    ; GFX90A-NEXT: S_ENDPGM 0, implicit $agpr0, implicit $agpr1, implicit $agpr2
    renamable $agpr0 = COPY renamable $vgpr0, implicit $exec
    renamable $agpr1 = COPY renamable $agpr0, implicit $exec
    renamable $agpr2 = COPY renamable $agpr0, implicit $exec
    S_ENDPGM 0, implicit $agpr0, implicit $agpr1, implicit $agpr2
...
---
name:  propagate_agpr_to_vgpr
body: |
  bb.0:
    successors:
    liveins: $agpr0

    ; GFX908-LABEL: name: propagate_agpr_to_vgpr
    ; GFX908: liveins: $agpr0
    ; GFX908-NEXT: {{  $}}
    ; GFX908-NEXT: renamable $vgpr0 = COPY renamable $agpr0, implicit $exec
    ; GFX908-NEXT: renamable $vgpr1 = COPY $agpr0, implicit $exec
    ; GFX908-NEXT: renamable $vgpr2 = COPY $agpr0, implicit $exec
    ; GFX908-NEXT: S_ENDPGM 0, implicit $vgpr0, implicit $vgpr1, implicit $vgpr2
    ;
    ; GFX90A-LABEL: name: propagate_agpr_to_vgpr
    ; GFX90A: liveins: $agpr0
    ; GFX90A-NEXT: {{  $}}
    ; GFX90A-NEXT: renamable $vgpr0 = COPY renamable $agpr0, implicit $exec
    ; GFX90A-NEXT: renamable $vgpr1 = COPY $agpr0, implicit $exec
    ; GFX90A-NEXT: renamable $vgpr2 = COPY $agpr0, implicit $exec
    ; GFX90A-NEXT: S_ENDPGM 0, implicit $vgpr0, implicit $vgpr1, implicit $vgpr2
    renamable $vgpr0 = COPY renamable $agpr0, implicit $exec
    renamable $vgpr1 = COPY renamable $vgpr0, implicit $exec
    renamable $vgpr2 = COPY renamable $vgpr0, implicit $exec
    S_ENDPGM 0, implicit $vgpr0, implicit $vgpr1, implicit $vgpr2
...
