; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5

; RUN: llc -mtriple=amdgcn -mcpu=tahiti < %s | FileCheck -check-prefix=SI %s
; RUN: llc -mtriple=amdgcn -mcpu=tonga < %s | FileCheck -check-prefix=VI %s
; RUN: llc -mtriple=amdgcn -mcpu=gfx900 < %s | FileCheck -check-prefix=GFX9 %s
; RUN: llc -mtriple=amdgcn -mcpu=gfx1100 -mattr=+real-true16 < %s | FileCheck -check-prefix=GFX11-TRUE16 %s
; RUN: llc -mtriple=amdgcn -mcpu=gfx1100 -mattr=-real-true16 < %s | FileCheck -check-prefix=GFX11-FAKE16 %s

define <28 x float> @bitcast_v28i32_to_v28f32(<28 x i32> %a, i32 %b) {
; SI-LABEL: bitcast_v28i32_to_v28f32:
; VI-LABEL: bitcast_v28i32_to_v28f32:
; GFX9-LABEL: bitcast_v28i32_to_v28f32:
; GFX11-TRUE16-LABEL: bitcast_v28i32_to_v28f32:
; GFX11-FAKE16-LABEL: bitcast_v28i32_to_v28f32:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <28 x i32> %a, splat (i32 3)
  %a2 = bitcast <28 x i32> %a1 to <28 x float>
  br label %end

cmp.false:
  %a3 = bitcast <28 x i32> %a to <28 x float>
  br label %end

end:
  %phi = phi <28 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <28 x float> %phi
}

define inreg <28 x float> @bitcast_v28i32_to_v28f32_scalar(<28 x i32> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v28i32_to_v28f32_scalar:
; VI-LABEL: bitcast_v28i32_to_v28f32_scalar:
; GFX9-LABEL: bitcast_v28i32_to_v28f32_scalar:
; GFX11-TRUE16-LABEL: bitcast_v28i32_to_v28f32_scalar:
; GFX11-FAKE16-LABEL: bitcast_v28i32_to_v28f32_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <28 x i32> %a, splat (i32 3)
  %a2 = bitcast <28 x i32> %a1 to <28 x float>
  br label %end

cmp.false:
  %a3 = bitcast <28 x i32> %a to <28 x float>
  br label %end

end:
  %phi = phi <28 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <28 x float> %phi
}

define <28 x i32> @bitcast_v28f32_to_v28i32(<28 x float> %a, i32 %b) {
; SI-LABEL: bitcast_v28f32_to_v28i32:
; VI-LABEL: bitcast_v28f32_to_v28i32:
; GFX9-LABEL: bitcast_v28f32_to_v28i32:
; GFX11-TRUE16-LABEL: bitcast_v28f32_to_v28i32:
; GFX11-FAKE16-LABEL: bitcast_v28f32_to_v28i32:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <28 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <28 x float> %a1 to <28 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <28 x float> %a to <28 x i32>
  br label %end

end:
  %phi = phi <28 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <28 x i32> %phi
}

define inreg <28 x i32> @bitcast_v28f32_to_v28i32_scalar(<28 x float> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v28f32_to_v28i32_scalar:
; VI-LABEL: bitcast_v28f32_to_v28i32_scalar:
; GFX9-LABEL: bitcast_v28f32_to_v28i32_scalar:
; GFX11-TRUE16-LABEL: bitcast_v28f32_to_v28i32_scalar:
; GFX11-FAKE16-LABEL: bitcast_v28f32_to_v28i32_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <28 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <28 x float> %a1 to <28 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <28 x float> %a to <28 x i32>
  br label %end

end:
  %phi = phi <28 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <28 x i32> %phi
}

define <14 x i64> @bitcast_v28i32_to_v14i64(<28 x i32> %a, i32 %b) {
; SI-LABEL: bitcast_v28i32_to_v14i64:
; VI-LABEL: bitcast_v28i32_to_v14i64:
; GFX9-LABEL: bitcast_v28i32_to_v14i64:
; GFX11-TRUE16-LABEL: bitcast_v28i32_to_v14i64:
; GFX11-FAKE16-LABEL: bitcast_v28i32_to_v14i64:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <28 x i32> %a, splat (i32 3)
  %a2 = bitcast <28 x i32> %a1 to <14 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <28 x i32> %a to <14 x i64>
  br label %end

end:
  %phi = phi <14 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <14 x i64> %phi
}

define inreg <14 x i64> @bitcast_v28i32_to_v14i64_scalar(<28 x i32> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v28i32_to_v14i64_scalar:
; VI-LABEL: bitcast_v28i32_to_v14i64_scalar:
; GFX9-LABEL: bitcast_v28i32_to_v14i64_scalar:
; GFX11-TRUE16-LABEL: bitcast_v28i32_to_v14i64_scalar:
; GFX11-FAKE16-LABEL: bitcast_v28i32_to_v14i64_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <28 x i32> %a, splat (i32 3)
  %a2 = bitcast <28 x i32> %a1 to <14 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <28 x i32> %a to <14 x i64>
  br label %end

end:
  %phi = phi <14 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <14 x i64> %phi
}

define <28 x i32> @bitcast_v14i64_to_v28i32(<14 x i64> %a, i32 %b) {
; SI-LABEL: bitcast_v14i64_to_v28i32:
; VI-LABEL: bitcast_v14i64_to_v28i32:
; GFX9-LABEL: bitcast_v14i64_to_v28i32:
; GFX11-TRUE16-LABEL: bitcast_v14i64_to_v28i32:
; GFX11-FAKE16-LABEL: bitcast_v14i64_to_v28i32:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <14 x i64> %a, splat (i64 3)
  %a2 = bitcast <14 x i64> %a1 to <28 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <14 x i64> %a to <28 x i32>
  br label %end

end:
  %phi = phi <28 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <28 x i32> %phi
}

define inreg <28 x i32> @bitcast_v14i64_to_v28i32_scalar(<14 x i64> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v14i64_to_v28i32_scalar:
; VI-LABEL: bitcast_v14i64_to_v28i32_scalar:
; GFX9-LABEL: bitcast_v14i64_to_v28i32_scalar:
; GFX11-TRUE16-LABEL: bitcast_v14i64_to_v28i32_scalar:
; GFX11-FAKE16-LABEL: bitcast_v14i64_to_v28i32_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <14 x i64> %a, splat (i64 3)
  %a2 = bitcast <14 x i64> %a1 to <28 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <14 x i64> %a to <28 x i32>
  br label %end

end:
  %phi = phi <28 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <28 x i32> %phi
}

define <14 x double> @bitcast_v28i32_to_v14f64(<28 x i32> %a, i32 %b) {
; SI-LABEL: bitcast_v28i32_to_v14f64:
; VI-LABEL: bitcast_v28i32_to_v14f64:
; GFX9-LABEL: bitcast_v28i32_to_v14f64:
; GFX11-TRUE16-LABEL: bitcast_v28i32_to_v14f64:
; GFX11-FAKE16-LABEL: bitcast_v28i32_to_v14f64:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <28 x i32> %a, splat (i32 3)
  %a2 = bitcast <28 x i32> %a1 to <14 x double>
  br label %end

cmp.false:
  %a3 = bitcast <28 x i32> %a to <14 x double>
  br label %end

end:
  %phi = phi <14 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <14 x double> %phi
}

define inreg <14 x double> @bitcast_v28i32_to_v14f64_scalar(<28 x i32> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v28i32_to_v14f64_scalar:
; VI-LABEL: bitcast_v28i32_to_v14f64_scalar:
; GFX9-LABEL: bitcast_v28i32_to_v14f64_scalar:
; GFX11-TRUE16-LABEL: bitcast_v28i32_to_v14f64_scalar:
; GFX11-FAKE16-LABEL: bitcast_v28i32_to_v14f64_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <28 x i32> %a, splat (i32 3)
  %a2 = bitcast <28 x i32> %a1 to <14 x double>
  br label %end

cmp.false:
  %a3 = bitcast <28 x i32> %a to <14 x double>
  br label %end

end:
  %phi = phi <14 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <14 x double> %phi
}

define <28 x i32> @bitcast_v14f64_to_v28i32(<14 x double> %a, i32 %b) {
; SI-LABEL: bitcast_v14f64_to_v28i32:
; VI-LABEL: bitcast_v14f64_to_v28i32:
; GFX9-LABEL: bitcast_v14f64_to_v28i32:
; GFX11-TRUE16-LABEL: bitcast_v14f64_to_v28i32:
; GFX11-FAKE16-LABEL: bitcast_v14f64_to_v28i32:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <14 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <14 x double> %a1 to <28 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <14 x double> %a to <28 x i32>
  br label %end

end:
  %phi = phi <28 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <28 x i32> %phi
}

define inreg <28 x i32> @bitcast_v14f64_to_v28i32_scalar(<14 x double> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v14f64_to_v28i32_scalar:
; VI-LABEL: bitcast_v14f64_to_v28i32_scalar:
; GFX9-LABEL: bitcast_v14f64_to_v28i32_scalar:
; GFX11-TRUE16-LABEL: bitcast_v14f64_to_v28i32_scalar:
; GFX11-FAKE16-LABEL: bitcast_v14f64_to_v28i32_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <14 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <14 x double> %a1 to <28 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <14 x double> %a to <28 x i32>
  br label %end

end:
  %phi = phi <28 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <28 x i32> %phi
}

define <56 x i16> @bitcast_v28i32_to_v56i16(<28 x i32> %a, i32 %b) {
; SI-LABEL: bitcast_v28i32_to_v56i16:
; VI-LABEL: bitcast_v28i32_to_v56i16:
; GFX9-LABEL: bitcast_v28i32_to_v56i16:
; GFX11-TRUE16-LABEL: bitcast_v28i32_to_v56i16:
; GFX11-FAKE16-LABEL: bitcast_v28i32_to_v56i16:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <28 x i32> %a, splat (i32 3)
  %a2 = bitcast <28 x i32> %a1 to <56 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <28 x i32> %a to <56 x i16>
  br label %end

end:
  %phi = phi <56 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <56 x i16> %phi
}

define inreg <56 x i16> @bitcast_v28i32_to_v56i16_scalar(<28 x i32> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v28i32_to_v56i16_scalar:
; VI-LABEL: bitcast_v28i32_to_v56i16_scalar:
; GFX9-LABEL: bitcast_v28i32_to_v56i16_scalar:
; GFX11-TRUE16-LABEL: bitcast_v28i32_to_v56i16_scalar:
; GFX11-FAKE16-LABEL: bitcast_v28i32_to_v56i16_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <28 x i32> %a, splat (i32 3)
  %a2 = bitcast <28 x i32> %a1 to <56 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <28 x i32> %a to <56 x i16>
  br label %end

end:
  %phi = phi <56 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <56 x i16> %phi
}

define <28 x i32> @bitcast_v56i16_to_v28i32(<56 x i16> %a, i32 %b) {
; SI-LABEL: bitcast_v56i16_to_v28i32:
; VI-LABEL: bitcast_v56i16_to_v28i32:
; GFX9-LABEL: bitcast_v56i16_to_v28i32:
; GFX11-TRUE16-LABEL: bitcast_v56i16_to_v28i32:
; GFX11-FAKE16-LABEL: bitcast_v56i16_to_v28i32:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <56 x i16> %a, splat (i16 3)
  %a2 = bitcast <56 x i16> %a1 to <28 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <56 x i16> %a to <28 x i32>
  br label %end

end:
  %phi = phi <28 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <28 x i32> %phi
}

define inreg <28 x i32> @bitcast_v56i16_to_v28i32_scalar(<56 x i16> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v56i16_to_v28i32_scalar:
; VI-LABEL: bitcast_v56i16_to_v28i32_scalar:
; GFX9-LABEL: bitcast_v56i16_to_v28i32_scalar:
; GFX11-TRUE16-LABEL: bitcast_v56i16_to_v28i32_scalar:
; GFX11-FAKE16-LABEL: bitcast_v56i16_to_v28i32_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <56 x i16> %a, splat (i16 3)
  %a2 = bitcast <56 x i16> %a1 to <28 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <56 x i16> %a to <28 x i32>
  br label %end

end:
  %phi = phi <28 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <28 x i32> %phi
}

define <56 x half> @bitcast_v28i32_to_v56f16(<28 x i32> %a, i32 %b) {
; SI-LABEL: bitcast_v28i32_to_v56f16:
; VI-LABEL: bitcast_v28i32_to_v56f16:
; GFX9-LABEL: bitcast_v28i32_to_v56f16:
; GFX11-TRUE16-LABEL: bitcast_v28i32_to_v56f16:
; GFX11-FAKE16-LABEL: bitcast_v28i32_to_v56f16:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <28 x i32> %a, splat (i32 3)
  %a2 = bitcast <28 x i32> %a1 to <56 x half>
  br label %end

cmp.false:
  %a3 = bitcast <28 x i32> %a to <56 x half>
  br label %end

end:
  %phi = phi <56 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <56 x half> %phi
}

define inreg <56 x half> @bitcast_v28i32_to_v56f16_scalar(<28 x i32> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v28i32_to_v56f16_scalar:
; VI-LABEL: bitcast_v28i32_to_v56f16_scalar:
; GFX9-LABEL: bitcast_v28i32_to_v56f16_scalar:
; GFX11-TRUE16-LABEL: bitcast_v28i32_to_v56f16_scalar:
; GFX11-FAKE16-LABEL: bitcast_v28i32_to_v56f16_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <28 x i32> %a, splat (i32 3)
  %a2 = bitcast <28 x i32> %a1 to <56 x half>
  br label %end

cmp.false:
  %a3 = bitcast <28 x i32> %a to <56 x half>
  br label %end

end:
  %phi = phi <56 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <56 x half> %phi
}

define <28 x i32> @bitcast_v56f16_to_v28i32(<56 x half> %a, i32 %b) {
; SI-LABEL: bitcast_v56f16_to_v28i32:
; VI-LABEL: bitcast_v56f16_to_v28i32:
; GFX9-LABEL: bitcast_v56f16_to_v28i32:
; GFX11-TRUE16-LABEL: bitcast_v56f16_to_v28i32:
; GFX11-FAKE16-LABEL: bitcast_v56f16_to_v28i32:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <56 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <56 x half> %a1 to <28 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <56 x half> %a to <28 x i32>
  br label %end

end:
  %phi = phi <28 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <28 x i32> %phi
}

define inreg <28 x i32> @bitcast_v56f16_to_v28i32_scalar(<56 x half> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v56f16_to_v28i32_scalar:
; VI-LABEL: bitcast_v56f16_to_v28i32_scalar:
; GFX9-LABEL: bitcast_v56f16_to_v28i32_scalar:
; GFX11-TRUE16-LABEL: bitcast_v56f16_to_v28i32_scalar:
; GFX11-FAKE16-LABEL: bitcast_v56f16_to_v28i32_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <56 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <56 x half> %a1 to <28 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <56 x half> %a to <28 x i32>
  br label %end

end:
  %phi = phi <28 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <28 x i32> %phi
}

define <14 x i64> @bitcast_v28f32_to_v14i64(<28 x float> %a, i32 %b) {
; SI-LABEL: bitcast_v28f32_to_v14i64:
; VI-LABEL: bitcast_v28f32_to_v14i64:
; GFX9-LABEL: bitcast_v28f32_to_v14i64:
; GFX11-TRUE16-LABEL: bitcast_v28f32_to_v14i64:
; GFX11-FAKE16-LABEL: bitcast_v28f32_to_v14i64:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <28 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <28 x float> %a1 to <14 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <28 x float> %a to <14 x i64>
  br label %end

end:
  %phi = phi <14 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <14 x i64> %phi
}

define inreg <14 x i64> @bitcast_v28f32_to_v14i64_scalar(<28 x float> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v28f32_to_v14i64_scalar:
; VI-LABEL: bitcast_v28f32_to_v14i64_scalar:
; GFX9-LABEL: bitcast_v28f32_to_v14i64_scalar:
; GFX11-TRUE16-LABEL: bitcast_v28f32_to_v14i64_scalar:
; GFX11-FAKE16-LABEL: bitcast_v28f32_to_v14i64_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <28 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <28 x float> %a1 to <14 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <28 x float> %a to <14 x i64>
  br label %end

end:
  %phi = phi <14 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <14 x i64> %phi
}

define <28 x float> @bitcast_v14i64_to_v28f32(<14 x i64> %a, i32 %b) {
; SI-LABEL: bitcast_v14i64_to_v28f32:
; VI-LABEL: bitcast_v14i64_to_v28f32:
; GFX9-LABEL: bitcast_v14i64_to_v28f32:
; GFX11-TRUE16-LABEL: bitcast_v14i64_to_v28f32:
; GFX11-FAKE16-LABEL: bitcast_v14i64_to_v28f32:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <14 x i64> %a, splat (i64 3)
  %a2 = bitcast <14 x i64> %a1 to <28 x float>
  br label %end

cmp.false:
  %a3 = bitcast <14 x i64> %a to <28 x float>
  br label %end

end:
  %phi = phi <28 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <28 x float> %phi
}

define inreg <28 x float> @bitcast_v14i64_to_v28f32_scalar(<14 x i64> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v14i64_to_v28f32_scalar:
; VI-LABEL: bitcast_v14i64_to_v28f32_scalar:
; GFX9-LABEL: bitcast_v14i64_to_v28f32_scalar:
; GFX11-TRUE16-LABEL: bitcast_v14i64_to_v28f32_scalar:
; GFX11-FAKE16-LABEL: bitcast_v14i64_to_v28f32_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <14 x i64> %a, splat (i64 3)
  %a2 = bitcast <14 x i64> %a1 to <28 x float>
  br label %end

cmp.false:
  %a3 = bitcast <14 x i64> %a to <28 x float>
  br label %end

end:
  %phi = phi <28 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <28 x float> %phi
}

define <14 x double> @bitcast_v28f32_to_v14f64(<28 x float> %a, i32 %b) {
; SI-LABEL: bitcast_v28f32_to_v14f64:
; VI-LABEL: bitcast_v28f32_to_v14f64:
; GFX9-LABEL: bitcast_v28f32_to_v14f64:
; GFX11-TRUE16-LABEL: bitcast_v28f32_to_v14f64:
; GFX11-FAKE16-LABEL: bitcast_v28f32_to_v14f64:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <28 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <28 x float> %a1 to <14 x double>
  br label %end

cmp.false:
  %a3 = bitcast <28 x float> %a to <14 x double>
  br label %end

end:
  %phi = phi <14 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <14 x double> %phi
}

define inreg <14 x double> @bitcast_v28f32_to_v14f64_scalar(<28 x float> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v28f32_to_v14f64_scalar:
; VI-LABEL: bitcast_v28f32_to_v14f64_scalar:
; GFX9-LABEL: bitcast_v28f32_to_v14f64_scalar:
; GFX11-TRUE16-LABEL: bitcast_v28f32_to_v14f64_scalar:
; GFX11-FAKE16-LABEL: bitcast_v28f32_to_v14f64_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <28 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <28 x float> %a1 to <14 x double>
  br label %end

cmp.false:
  %a3 = bitcast <28 x float> %a to <14 x double>
  br label %end

end:
  %phi = phi <14 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <14 x double> %phi
}

define <28 x float> @bitcast_v14f64_to_v28f32(<14 x double> %a, i32 %b) {
; SI-LABEL: bitcast_v14f64_to_v28f32:
; VI-LABEL: bitcast_v14f64_to_v28f32:
; GFX9-LABEL: bitcast_v14f64_to_v28f32:
; GFX11-TRUE16-LABEL: bitcast_v14f64_to_v28f32:
; GFX11-FAKE16-LABEL: bitcast_v14f64_to_v28f32:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <14 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <14 x double> %a1 to <28 x float>
  br label %end

cmp.false:
  %a3 = bitcast <14 x double> %a to <28 x float>
  br label %end

end:
  %phi = phi <28 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <28 x float> %phi
}

define inreg <28 x float> @bitcast_v14f64_to_v28f32_scalar(<14 x double> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v14f64_to_v28f32_scalar:
; VI-LABEL: bitcast_v14f64_to_v28f32_scalar:
; GFX9-LABEL: bitcast_v14f64_to_v28f32_scalar:
; GFX11-TRUE16-LABEL: bitcast_v14f64_to_v28f32_scalar:
; GFX11-FAKE16-LABEL: bitcast_v14f64_to_v28f32_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <14 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <14 x double> %a1 to <28 x float>
  br label %end

cmp.false:
  %a3 = bitcast <14 x double> %a to <28 x float>
  br label %end

end:
  %phi = phi <28 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <28 x float> %phi
}

define <56 x i16> @bitcast_v28f32_to_v56i16(<28 x float> %a, i32 %b) {
; SI-LABEL: bitcast_v28f32_to_v56i16:
; VI-LABEL: bitcast_v28f32_to_v56i16:
; GFX9-LABEL: bitcast_v28f32_to_v56i16:
; GFX11-TRUE16-LABEL: bitcast_v28f32_to_v56i16:
; GFX11-FAKE16-LABEL: bitcast_v28f32_to_v56i16:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <28 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <28 x float> %a1 to <56 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <28 x float> %a to <56 x i16>
  br label %end

end:
  %phi = phi <56 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <56 x i16> %phi
}

define inreg <56 x i16> @bitcast_v28f32_to_v56i16_scalar(<28 x float> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v28f32_to_v56i16_scalar:
; VI-LABEL: bitcast_v28f32_to_v56i16_scalar:
; GFX9-LABEL: bitcast_v28f32_to_v56i16_scalar:
; GFX11-TRUE16-LABEL: bitcast_v28f32_to_v56i16_scalar:
; GFX11-FAKE16-LABEL: bitcast_v28f32_to_v56i16_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <28 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <28 x float> %a1 to <56 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <28 x float> %a to <56 x i16>
  br label %end

end:
  %phi = phi <56 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <56 x i16> %phi
}

define <28 x float> @bitcast_v56i16_to_v28f32(<56 x i16> %a, i32 %b) {
; SI-LABEL: bitcast_v56i16_to_v28f32:
; VI-LABEL: bitcast_v56i16_to_v28f32:
; GFX9-LABEL: bitcast_v56i16_to_v28f32:
; GFX11-TRUE16-LABEL: bitcast_v56i16_to_v28f32:
; GFX11-FAKE16-LABEL: bitcast_v56i16_to_v28f32:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <56 x i16> %a, splat (i16 3)
  %a2 = bitcast <56 x i16> %a1 to <28 x float>
  br label %end

cmp.false:
  %a3 = bitcast <56 x i16> %a to <28 x float>
  br label %end

end:
  %phi = phi <28 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <28 x float> %phi
}

define inreg <28 x float> @bitcast_v56i16_to_v28f32_scalar(<56 x i16> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v56i16_to_v28f32_scalar:
; VI-LABEL: bitcast_v56i16_to_v28f32_scalar:
; GFX9-LABEL: bitcast_v56i16_to_v28f32_scalar:
; GFX11-TRUE16-LABEL: bitcast_v56i16_to_v28f32_scalar:
; GFX11-FAKE16-LABEL: bitcast_v56i16_to_v28f32_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <56 x i16> %a, splat (i16 3)
  %a2 = bitcast <56 x i16> %a1 to <28 x float>
  br label %end

cmp.false:
  %a3 = bitcast <56 x i16> %a to <28 x float>
  br label %end

end:
  %phi = phi <28 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <28 x float> %phi
}

define <56 x half> @bitcast_v28f32_to_v56f16(<28 x float> %a, i32 %b) {
; SI-LABEL: bitcast_v28f32_to_v56f16:
; VI-LABEL: bitcast_v28f32_to_v56f16:
; GFX9-LABEL: bitcast_v28f32_to_v56f16:
; GFX11-TRUE16-LABEL: bitcast_v28f32_to_v56f16:
; GFX11-FAKE16-LABEL: bitcast_v28f32_to_v56f16:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <28 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <28 x float> %a1 to <56 x half>
  br label %end

cmp.false:
  %a3 = bitcast <28 x float> %a to <56 x half>
  br label %end

end:
  %phi = phi <56 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <56 x half> %phi
}

define inreg <56 x half> @bitcast_v28f32_to_v56f16_scalar(<28 x float> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v28f32_to_v56f16_scalar:
; VI-LABEL: bitcast_v28f32_to_v56f16_scalar:
; GFX9-LABEL: bitcast_v28f32_to_v56f16_scalar:
; GFX11-TRUE16-LABEL: bitcast_v28f32_to_v56f16_scalar:
; GFX11-FAKE16-LABEL: bitcast_v28f32_to_v56f16_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <28 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <28 x float> %a1 to <56 x half>
  br label %end

cmp.false:
  %a3 = bitcast <28 x float> %a to <56 x half>
  br label %end

end:
  %phi = phi <56 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <56 x half> %phi
}

define <28 x float> @bitcast_v56f16_to_v28f32(<56 x half> %a, i32 %b) {
; SI-LABEL: bitcast_v56f16_to_v28f32:
; VI-LABEL: bitcast_v56f16_to_v28f32:
; GFX9-LABEL: bitcast_v56f16_to_v28f32:
; GFX11-TRUE16-LABEL: bitcast_v56f16_to_v28f32:
; GFX11-FAKE16-LABEL: bitcast_v56f16_to_v28f32:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <56 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <56 x half> %a1 to <28 x float>
  br label %end

cmp.false:
  %a3 = bitcast <56 x half> %a to <28 x float>
  br label %end

end:
  %phi = phi <28 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <28 x float> %phi
}

define inreg <28 x float> @bitcast_v56f16_to_v28f32_scalar(<56 x half> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v56f16_to_v28f32_scalar:
; VI-LABEL: bitcast_v56f16_to_v28f32_scalar:
; GFX9-LABEL: bitcast_v56f16_to_v28f32_scalar:
; GFX11-TRUE16-LABEL: bitcast_v56f16_to_v28f32_scalar:
; GFX11-FAKE16-LABEL: bitcast_v56f16_to_v28f32_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <56 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <56 x half> %a1 to <28 x float>
  br label %end

cmp.false:
  %a3 = bitcast <56 x half> %a to <28 x float>
  br label %end

end:
  %phi = phi <28 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <28 x float> %phi
}

define <14 x double> @bitcast_v14i64_to_v14f64(<14 x i64> %a, i32 %b) {
; SI-LABEL: bitcast_v14i64_to_v14f64:
; VI-LABEL: bitcast_v14i64_to_v14f64:
; GFX9-LABEL: bitcast_v14i64_to_v14f64:
; GFX11-TRUE16-LABEL: bitcast_v14i64_to_v14f64:
; GFX11-FAKE16-LABEL: bitcast_v14i64_to_v14f64:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <14 x i64> %a, splat (i64 3)
  %a2 = bitcast <14 x i64> %a1 to <14 x double>
  br label %end

cmp.false:
  %a3 = bitcast <14 x i64> %a to <14 x double>
  br label %end

end:
  %phi = phi <14 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <14 x double> %phi
}

define inreg <14 x double> @bitcast_v14i64_to_v14f64_scalar(<14 x i64> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v14i64_to_v14f64_scalar:
; VI-LABEL: bitcast_v14i64_to_v14f64_scalar:
; GFX9-LABEL: bitcast_v14i64_to_v14f64_scalar:
; GFX11-TRUE16-LABEL: bitcast_v14i64_to_v14f64_scalar:
; GFX11-FAKE16-LABEL: bitcast_v14i64_to_v14f64_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <14 x i64> %a, splat (i64 3)
  %a2 = bitcast <14 x i64> %a1 to <14 x double>
  br label %end

cmp.false:
  %a3 = bitcast <14 x i64> %a to <14 x double>
  br label %end

end:
  %phi = phi <14 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <14 x double> %phi
}

define <14 x i64> @bitcast_v14f64_to_v14i64(<14 x double> %a, i32 %b) {
; SI-LABEL: bitcast_v14f64_to_v14i64:
; VI-LABEL: bitcast_v14f64_to_v14i64:
; GFX9-LABEL: bitcast_v14f64_to_v14i64:
; GFX11-TRUE16-LABEL: bitcast_v14f64_to_v14i64:
; GFX11-FAKE16-LABEL: bitcast_v14f64_to_v14i64:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <14 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <14 x double> %a1 to <14 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <14 x double> %a to <14 x i64>
  br label %end

end:
  %phi = phi <14 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <14 x i64> %phi
}

define inreg <14 x i64> @bitcast_v14f64_to_v14i64_scalar(<14 x double> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v14f64_to_v14i64_scalar:
; VI-LABEL: bitcast_v14f64_to_v14i64_scalar:
; GFX9-LABEL: bitcast_v14f64_to_v14i64_scalar:
; GFX11-TRUE16-LABEL: bitcast_v14f64_to_v14i64_scalar:
; GFX11-FAKE16-LABEL: bitcast_v14f64_to_v14i64_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <14 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <14 x double> %a1 to <14 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <14 x double> %a to <14 x i64>
  br label %end

end:
  %phi = phi <14 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <14 x i64> %phi
}

define <56 x i16> @bitcast_v14i64_to_v56i16(<14 x i64> %a, i32 %b) {
; SI-LABEL: bitcast_v14i64_to_v56i16:
; VI-LABEL: bitcast_v14i64_to_v56i16:
; GFX9-LABEL: bitcast_v14i64_to_v56i16:
; GFX11-TRUE16-LABEL: bitcast_v14i64_to_v56i16:
; GFX11-FAKE16-LABEL: bitcast_v14i64_to_v56i16:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <14 x i64> %a, splat (i64 3)
  %a2 = bitcast <14 x i64> %a1 to <56 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <14 x i64> %a to <56 x i16>
  br label %end

end:
  %phi = phi <56 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <56 x i16> %phi
}

define inreg <56 x i16> @bitcast_v14i64_to_v56i16_scalar(<14 x i64> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v14i64_to_v56i16_scalar:
; VI-LABEL: bitcast_v14i64_to_v56i16_scalar:
; GFX9-LABEL: bitcast_v14i64_to_v56i16_scalar:
; GFX11-TRUE16-LABEL: bitcast_v14i64_to_v56i16_scalar:
; GFX11-FAKE16-LABEL: bitcast_v14i64_to_v56i16_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <14 x i64> %a, splat (i64 3)
  %a2 = bitcast <14 x i64> %a1 to <56 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <14 x i64> %a to <56 x i16>
  br label %end

end:
  %phi = phi <56 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <56 x i16> %phi
}

define <14 x i64> @bitcast_v56i16_to_v14i64(<56 x i16> %a, i32 %b) {
; SI-LABEL: bitcast_v56i16_to_v14i64:
; VI-LABEL: bitcast_v56i16_to_v14i64:
; GFX9-LABEL: bitcast_v56i16_to_v14i64:
; GFX11-TRUE16-LABEL: bitcast_v56i16_to_v14i64:
; GFX11-FAKE16-LABEL: bitcast_v56i16_to_v14i64:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <56 x i16> %a, splat (i16 3)
  %a2 = bitcast <56 x i16> %a1 to <14 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <56 x i16> %a to <14 x i64>
  br label %end

end:
  %phi = phi <14 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <14 x i64> %phi
}

define inreg <14 x i64> @bitcast_v56i16_to_v14i64_scalar(<56 x i16> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v56i16_to_v14i64_scalar:
; VI-LABEL: bitcast_v56i16_to_v14i64_scalar:
; GFX9-LABEL: bitcast_v56i16_to_v14i64_scalar:
; GFX11-TRUE16-LABEL: bitcast_v56i16_to_v14i64_scalar:
; GFX11-FAKE16-LABEL: bitcast_v56i16_to_v14i64_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <56 x i16> %a, splat (i16 3)
  %a2 = bitcast <56 x i16> %a1 to <14 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <56 x i16> %a to <14 x i64>
  br label %end

end:
  %phi = phi <14 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <14 x i64> %phi
}

define <56 x half> @bitcast_v14i64_to_v56f16(<14 x i64> %a, i32 %b) {
; SI-LABEL: bitcast_v14i64_to_v56f16:
; VI-LABEL: bitcast_v14i64_to_v56f16:
; GFX9-LABEL: bitcast_v14i64_to_v56f16:
; GFX11-TRUE16-LABEL: bitcast_v14i64_to_v56f16:
; GFX11-FAKE16-LABEL: bitcast_v14i64_to_v56f16:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <14 x i64> %a, splat (i64 3)
  %a2 = bitcast <14 x i64> %a1 to <56 x half>
  br label %end

cmp.false:
  %a3 = bitcast <14 x i64> %a to <56 x half>
  br label %end

end:
  %phi = phi <56 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <56 x half> %phi
}

define inreg <56 x half> @bitcast_v14i64_to_v56f16_scalar(<14 x i64> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v14i64_to_v56f16_scalar:
; VI-LABEL: bitcast_v14i64_to_v56f16_scalar:
; GFX9-LABEL: bitcast_v14i64_to_v56f16_scalar:
; GFX11-TRUE16-LABEL: bitcast_v14i64_to_v56f16_scalar:
; GFX11-FAKE16-LABEL: bitcast_v14i64_to_v56f16_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <14 x i64> %a, splat (i64 3)
  %a2 = bitcast <14 x i64> %a1 to <56 x half>
  br label %end

cmp.false:
  %a3 = bitcast <14 x i64> %a to <56 x half>
  br label %end

end:
  %phi = phi <56 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <56 x half> %phi
}

define <14 x i64> @bitcast_v56f16_to_v14i64(<56 x half> %a, i32 %b) {
; SI-LABEL: bitcast_v56f16_to_v14i64:
; VI-LABEL: bitcast_v56f16_to_v14i64:
; GFX9-LABEL: bitcast_v56f16_to_v14i64:
; GFX11-TRUE16-LABEL: bitcast_v56f16_to_v14i64:
; GFX11-FAKE16-LABEL: bitcast_v56f16_to_v14i64:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <56 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <56 x half> %a1 to <14 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <56 x half> %a to <14 x i64>
  br label %end

end:
  %phi = phi <14 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <14 x i64> %phi
}

define inreg <14 x i64> @bitcast_v56f16_to_v14i64_scalar(<56 x half> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v56f16_to_v14i64_scalar:
; VI-LABEL: bitcast_v56f16_to_v14i64_scalar:
; GFX9-LABEL: bitcast_v56f16_to_v14i64_scalar:
; GFX11-TRUE16-LABEL: bitcast_v56f16_to_v14i64_scalar:
; GFX11-FAKE16-LABEL: bitcast_v56f16_to_v14i64_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <56 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <56 x half> %a1 to <14 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <56 x half> %a to <14 x i64>
  br label %end

end:
  %phi = phi <14 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <14 x i64> %phi
}

define <56 x i16> @bitcast_v14f64_to_v56i16(<14 x double> %a, i32 %b) {
; SI-LABEL: bitcast_v14f64_to_v56i16:
; VI-LABEL: bitcast_v14f64_to_v56i16:
; GFX9-LABEL: bitcast_v14f64_to_v56i16:
; GFX11-TRUE16-LABEL: bitcast_v14f64_to_v56i16:
; GFX11-FAKE16-LABEL: bitcast_v14f64_to_v56i16:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <14 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <14 x double> %a1 to <56 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <14 x double> %a to <56 x i16>
  br label %end

end:
  %phi = phi <56 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <56 x i16> %phi
}

define inreg <56 x i16> @bitcast_v14f64_to_v56i16_scalar(<14 x double> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v14f64_to_v56i16_scalar:
; VI-LABEL: bitcast_v14f64_to_v56i16_scalar:
; GFX9-LABEL: bitcast_v14f64_to_v56i16_scalar:
; GFX11-TRUE16-LABEL: bitcast_v14f64_to_v56i16_scalar:
; GFX11-FAKE16-LABEL: bitcast_v14f64_to_v56i16_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <14 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <14 x double> %a1 to <56 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <14 x double> %a to <56 x i16>
  br label %end

end:
  %phi = phi <56 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <56 x i16> %phi
}

define <14 x double> @bitcast_v56i16_to_v14f64(<56 x i16> %a, i32 %b) {
; SI-LABEL: bitcast_v56i16_to_v14f64:
; VI-LABEL: bitcast_v56i16_to_v14f64:
; GFX9-LABEL: bitcast_v56i16_to_v14f64:
; GFX11-TRUE16-LABEL: bitcast_v56i16_to_v14f64:
; GFX11-FAKE16-LABEL: bitcast_v56i16_to_v14f64:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <56 x i16> %a, splat (i16 3)
  %a2 = bitcast <56 x i16> %a1 to <14 x double>
  br label %end

cmp.false:
  %a3 = bitcast <56 x i16> %a to <14 x double>
  br label %end

end:
  %phi = phi <14 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <14 x double> %phi
}

define inreg <14 x double> @bitcast_v56i16_to_v14f64_scalar(<56 x i16> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v56i16_to_v14f64_scalar:
; VI-LABEL: bitcast_v56i16_to_v14f64_scalar:
; GFX9-LABEL: bitcast_v56i16_to_v14f64_scalar:
; GFX11-TRUE16-LABEL: bitcast_v56i16_to_v14f64_scalar:
; GFX11-FAKE16-LABEL: bitcast_v56i16_to_v14f64_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <56 x i16> %a, splat (i16 3)
  %a2 = bitcast <56 x i16> %a1 to <14 x double>
  br label %end

cmp.false:
  %a3 = bitcast <56 x i16> %a to <14 x double>
  br label %end

end:
  %phi = phi <14 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <14 x double> %phi
}

define <56 x half> @bitcast_v14f64_to_v56f16(<14 x double> %a, i32 %b) {
; SI-LABEL: bitcast_v14f64_to_v56f16:
; VI-LABEL: bitcast_v14f64_to_v56f16:
; GFX9-LABEL: bitcast_v14f64_to_v56f16:
; GFX11-TRUE16-LABEL: bitcast_v14f64_to_v56f16:
; GFX11-FAKE16-LABEL: bitcast_v14f64_to_v56f16:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <14 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <14 x double> %a1 to <56 x half>
  br label %end

cmp.false:
  %a3 = bitcast <14 x double> %a to <56 x half>
  br label %end

end:
  %phi = phi <56 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <56 x half> %phi
}

define inreg <56 x half> @bitcast_v14f64_to_v56f16_scalar(<14 x double> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v14f64_to_v56f16_scalar:
; VI-LABEL: bitcast_v14f64_to_v56f16_scalar:
; GFX9-LABEL: bitcast_v14f64_to_v56f16_scalar:
; GFX11-TRUE16-LABEL: bitcast_v14f64_to_v56f16_scalar:
; GFX11-FAKE16-LABEL: bitcast_v14f64_to_v56f16_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <14 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <14 x double> %a1 to <56 x half>
  br label %end

cmp.false:
  %a3 = bitcast <14 x double> %a to <56 x half>
  br label %end

end:
  %phi = phi <56 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <56 x half> %phi
}

define <14 x double> @bitcast_v56f16_to_v14f64(<56 x half> %a, i32 %b) {
; SI-LABEL: bitcast_v56f16_to_v14f64:
; VI-LABEL: bitcast_v56f16_to_v14f64:
; GFX9-LABEL: bitcast_v56f16_to_v14f64:
; GFX11-TRUE16-LABEL: bitcast_v56f16_to_v14f64:
; GFX11-FAKE16-LABEL: bitcast_v56f16_to_v14f64:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <56 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <56 x half> %a1 to <14 x double>
  br label %end

cmp.false:
  %a3 = bitcast <56 x half> %a to <14 x double>
  br label %end

end:
  %phi = phi <14 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <14 x double> %phi
}

define inreg <14 x double> @bitcast_v56f16_to_v14f64_scalar(<56 x half> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v56f16_to_v14f64_scalar:
; VI-LABEL: bitcast_v56f16_to_v14f64_scalar:
; GFX9-LABEL: bitcast_v56f16_to_v14f64_scalar:
; GFX11-TRUE16-LABEL: bitcast_v56f16_to_v14f64_scalar:
; GFX11-FAKE16-LABEL: bitcast_v56f16_to_v14f64_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <56 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <56 x half> %a1 to <14 x double>
  br label %end

cmp.false:
  %a3 = bitcast <56 x half> %a to <14 x double>
  br label %end

end:
  %phi = phi <14 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <14 x double> %phi
}

define <56 x half> @bitcast_v56i16_to_v56f16(<56 x i16> %a, i32 %b) {
; SI-LABEL: bitcast_v56i16_to_v56f16:
; VI-LABEL: bitcast_v56i16_to_v56f16:
; GFX9-LABEL: bitcast_v56i16_to_v56f16:
; GFX11-TRUE16-LABEL: bitcast_v56i16_to_v56f16:
; GFX11-FAKE16-LABEL: bitcast_v56i16_to_v56f16:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <56 x i16> %a, splat (i16 3)
  %a2 = bitcast <56 x i16> %a1 to <56 x half>
  br label %end

cmp.false:
  %a3 = bitcast <56 x i16> %a to <56 x half>
  br label %end

end:
  %phi = phi <56 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <56 x half> %phi
}

define inreg <56 x half> @bitcast_v56i16_to_v56f16_scalar(<56 x i16> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v56i16_to_v56f16_scalar:
; VI-LABEL: bitcast_v56i16_to_v56f16_scalar:
; GFX9-LABEL: bitcast_v56i16_to_v56f16_scalar:
; GFX11-TRUE16-LABEL: bitcast_v56i16_to_v56f16_scalar:
; GFX11-FAKE16-LABEL: bitcast_v56i16_to_v56f16_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <56 x i16> %a, splat (i16 3)
  %a2 = bitcast <56 x i16> %a1 to <56 x half>
  br label %end

cmp.false:
  %a3 = bitcast <56 x i16> %a to <56 x half>
  br label %end

end:
  %phi = phi <56 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <56 x half> %phi
}

define <56 x i16> @bitcast_v56f16_to_v56i16(<56 x half> %a, i32 %b) {
; SI-LABEL: bitcast_v56f16_to_v56i16:
; VI-LABEL: bitcast_v56f16_to_v56i16:
; GFX9-LABEL: bitcast_v56f16_to_v56i16:
; GFX11-TRUE16-LABEL: bitcast_v56f16_to_v56i16:
; GFX11-FAKE16-LABEL: bitcast_v56f16_to_v56i16:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <56 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <56 x half> %a1 to <56 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <56 x half> %a to <56 x i16>
  br label %end

end:
  %phi = phi <56 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <56 x i16> %phi
}

define inreg <56 x i16> @bitcast_v56f16_to_v56i16_scalar(<56 x half> inreg %a, i32 inreg %b) {
; SI-LABEL: bitcast_v56f16_to_v56i16_scalar:
; VI-LABEL: bitcast_v56f16_to_v56i16_scalar:
; GFX9-LABEL: bitcast_v56f16_to_v56i16_scalar:
; GFX11-TRUE16-LABEL: bitcast_v56f16_to_v56i16_scalar:
; GFX11-FAKE16-LABEL: bitcast_v56f16_to_v56i16_scalar:
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <56 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <56 x half> %a1 to <56 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <56 x half> %a to <56 x i16>
  br label %end

end:
  %phi = phi <56 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <56 x i16> %phi
}
