; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -amdgpu-vector-idiom-enable -mtriple=amdgcn-amd-amdhsa -passes=amdgpu-vector-idiom -S %s | FileCheck %s
;
; Reduced testcase for planned enhancement:
; Vectorize accumulator access patterns where multiple consecutive float loads/stores
; from the same base pointer can be combined into vector operations.
; Expected: combine individual float loads into <4 x float> vector loads,
; and individual float stores into <4 x float> vector stores.
;
; Enhancement planned: accumulator vectorization

declare void @llvm.lifetime.start.p5(i64, ptr addrspace(5) nocapture)
declare void @llvm.lifetime.end.p5(i64, ptr addrspace(5) nocapture)

; -----------------------------------------------------------------------------
; Accumulator pattern: consecutive float loads from same base pointer
; Expect: combine into <4 x float> vector load
;
define amdgpu_kernel void @accumulator_vectorize_loads(i32 %idx) {
; CHECK-LABEL: define amdgpu_kernel void @accumulator_vectorize_loads(
; CHECK-SAME: i32 [[IDX:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ACCUMULATORS:%.*]] = alloca [4 x [1 x [8 x float]]], align 32, addrspace(5)
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [4 x [1 x [8 x float]]], ptr addrspace(5) [[ACCUMULATORS]], i32 0, i32 [[IDX]], i32 0
; CHECK-NEXT:    [[LOAD0:%.*]] = load float, ptr addrspace(5) [[ARRAYIDX]], align 16
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr inbounds [8 x float], ptr addrspace(5) [[ARRAYIDX]], i32 0, i32 1
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr addrspace(5) [[ARRAYIDX]], i64 4
; CHECK-NEXT:    [[TMP1:%.*]] = load <4 x float>, ptr addrspace(5) [[TMP0]], align 4
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x float> [[TMP1]], i32 3
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <4 x float> [[TMP1]], i32 2
; CHECK-NEXT:    [[TMP4:%.*]] = extractelement <4 x float> [[TMP1]], i32 1
; CHECK-NEXT:    [[TMP5:%.*]] = extractelement <4 x float> [[TMP1]], i32 0
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr inbounds [8 x float], ptr addrspace(5) [[ARRAYIDX]], i32 0, i32 2
; CHECK-NEXT:    [[GEP3:%.*]] = getelementptr inbounds [8 x float], ptr addrspace(5) [[ARRAYIDX]], i32 0, i32 3
; CHECK-NEXT:    [[GEP4:%.*]] = getelementptr inbounds [8 x float], ptr addrspace(5) [[ARRAYIDX]], i32 0, i32 4
; CHECK-NEXT:    [[GEP5:%.*]] = getelementptr inbounds [8 x float], ptr addrspace(5) [[ARRAYIDX]], i32 0, i32 5
; CHECK-NEXT:    [[TMP6:%.*]] = getelementptr i8, ptr addrspace(5) [[ARRAYIDX]], i64 20
; CHECK-NEXT:    [[TMP7:%.*]] = load <3 x float>, ptr addrspace(5) [[TMP6]], align 4
; CHECK-NEXT:    [[TMP10:%.*]] = extractelement <3 x float> [[TMP7]], i32 2
; CHECK-NEXT:    [[TMP9:%.*]] = extractelement <3 x float> [[TMP7]], i32 1
; CHECK-NEXT:    [[TMP11:%.*]] = extractelement <3 x float> [[TMP7]], i32 0
; CHECK-NEXT:    [[GEP6:%.*]] = getelementptr inbounds [8 x float], ptr addrspace(5) [[ARRAYIDX]], i32 0, i32 6
; CHECK-NEXT:    [[GEP7:%.*]] = getelementptr inbounds [8 x float], ptr addrspace(5) [[ARRAYIDX]], i32 0, i32 7
; CHECK-NEXT:    ret void
;
entry:
  %accumulators = alloca [4 x [1 x [8 x float]]], align 32, addrspace(5)
  %arrayidx = getelementptr inbounds [4 x [1 x [8 x float]]], ptr addrspace(5) %accumulators, i32 0, i32 %idx, i32 0

  ; Individual float loads that should be vectorized
  %load0 = load float, ptr addrspace(5) %arrayidx, align 16
  %gep1 = getelementptr inbounds [8 x float], ptr addrspace(5) %arrayidx, i32 0, i32 1
  %load1 = load float, ptr addrspace(5) %gep1, align 4
  %gep2 = getelementptr inbounds [8 x float], ptr addrspace(5) %arrayidx, i32 0, i32 2
  %load2 = load float, ptr addrspace(5) %gep2, align 8
  %gep3 = getelementptr inbounds [8 x float], ptr addrspace(5) %arrayidx, i32 0, i32 3
  %load3 = load float, ptr addrspace(5) %gep3, align 4

  %gep4 = getelementptr inbounds [8 x float], ptr addrspace(5) %arrayidx, i32 0, i32 4
  %load4 = load float, ptr addrspace(5) %gep4, align 16
  %gep5 = getelementptr inbounds [8 x float], ptr addrspace(5) %arrayidx, i32 0, i32 5
  %load5 = load float, ptr addrspace(5) %gep5, align 4
  %gep6 = getelementptr inbounds [8 x float], ptr addrspace(5) %arrayidx, i32 0, i32 6
  %load6 = load float, ptr addrspace(5) %gep6, align 8
  %gep7 = getelementptr inbounds [8 x float], ptr addrspace(5) %arrayidx, i32 0, i32 7
  %load7 = load float, ptr addrspace(5) %gep7, align 4

  ret void
}

; -----------------------------------------------------------------------------
; Accumulator pattern: consecutive float stores to same base pointer
; Expect: combine into <4 x float> vector store
;
define amdgpu_kernel void @accumulator_vectorize_stores(i32 %idx, <4 x float> %val1, <4 x float> %val2) {
; CHECK-LABEL: define amdgpu_kernel void @accumulator_vectorize_stores(
; CHECK-SAME: i32 [[IDX:%.*]], <4 x float> [[VAL1:%.*]], <4 x float> [[VAL2:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ACCUMULATORS:%.*]] = alloca [4 x [1 x [8 x float]]], align 32, addrspace(5)
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [4 x [1 x [8 x float]]], ptr addrspace(5) [[ACCUMULATORS]], i32 0, i32 [[IDX]], i32 0
; CHECK-NEXT:    store float 1.000000e+00, ptr addrspace(5) [[ARRAYIDX]], align 16
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr inbounds [8 x float], ptr addrspace(5) [[ARRAYIDX]], i32 0, i32 1
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr inbounds [8 x float], ptr addrspace(5) [[ARRAYIDX]], i32 0, i32 2
; CHECK-NEXT:    [[GEP3:%.*]] = getelementptr inbounds [8 x float], ptr addrspace(5) [[ARRAYIDX]], i32 0, i32 3
; CHECK-NEXT:    [[GEP4:%.*]] = getelementptr inbounds [8 x float], ptr addrspace(5) [[ARRAYIDX]], i32 0, i32 4
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr addrspace(5) [[ARRAYIDX]], i64 4
; CHECK-NEXT:    store <4 x float> <float 2.000000e+00, float 3.000000e+00, float 4.000000e+00, float 5.000000e+00>, ptr addrspace(5) [[TMP0]], align 4
; CHECK-NEXT:    [[GEP5:%.*]] = getelementptr inbounds [8 x float], ptr addrspace(5) [[ARRAYIDX]], i32 0, i32 5
; CHECK-NEXT:    [[GEP6:%.*]] = getelementptr inbounds [8 x float], ptr addrspace(5) [[ARRAYIDX]], i32 0, i32 6
; CHECK-NEXT:    [[GEP7:%.*]] = getelementptr inbounds [8 x float], ptr addrspace(5) [[ARRAYIDX]], i32 0, i32 7
; CHECK-NEXT:    [[TMP1:%.*]] = getelementptr i8, ptr addrspace(5) [[ARRAYIDX]], i64 20
; CHECK-NEXT:    store <3 x float> <float 6.000000e+00, float 7.000000e+00, float 8.000000e+00>, ptr addrspace(5) [[TMP1]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %accumulators = alloca [4 x [1 x [8 x float]]], align 32, addrspace(5)
  %arrayidx = getelementptr inbounds [4 x [1 x [8 x float]]], ptr addrspace(5) %accumulators, i32 0, i32 %idx, i32 0

  ; Individual float stores that should be vectorized
  store float 1.0, ptr addrspace(5) %arrayidx, align 16
  %gep1 = getelementptr inbounds [8 x float], ptr addrspace(5) %arrayidx, i32 0, i32 1
  store float 2.0, ptr addrspace(5) %gep1, align 4
  %gep2 = getelementptr inbounds [8 x float], ptr addrspace(5) %arrayidx, i32 0, i32 2
  store float 3.0, ptr addrspace(5) %gep2, align 8
  %gep3 = getelementptr inbounds [8 x float], ptr addrspace(5) %arrayidx, i32 0, i32 3
  store float 4.0, ptr addrspace(5) %gep3, align 4

  %gep4 = getelementptr inbounds [8 x float], ptr addrspace(5) %arrayidx, i32 0, i32 4
  store float 5.0, ptr addrspace(5) %gep4, align 16
  %gep5 = getelementptr inbounds [8 x float], ptr addrspace(5) %arrayidx, i32 0, i32 5
  store float 6.0, ptr addrspace(5) %gep5, align 4
  %gep6 = getelementptr inbounds [8 x float], ptr addrspace(5) %arrayidx, i32 0, i32 6
  store float 7.0, ptr addrspace(5) %gep6, align 8
  %gep7 = getelementptr inbounds [8 x float], ptr addrspace(5) %arrayidx, i32 0, i32 7
  store float 8.0, ptr addrspace(5) %gep7, align 4

  ret void
}

; -----------------------------------------------------------------------------
; Accumulator pattern: mixed loads and stores with arithmetic operations
; Expect: vectorize the memory operations while preserving the arithmetic
;
define amdgpu_kernel void @accumulator_vectorize_mixed(i32 %idx, <4 x float> %input) {
; CHECK-LABEL: define amdgpu_kernel void @accumulator_vectorize_mixed(
; CHECK-SAME: i32 [[IDX:%.*]], <4 x float> [[INPUT:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ACCUMULATORS:%.*]] = alloca [4 x [1 x [8 x float]]], align 32, addrspace(5)
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [4 x [1 x [8 x float]]], ptr addrspace(5) [[ACCUMULATORS]], i32 0, i32 [[IDX]], i32 0
; CHECK-NEXT:    [[LOAD0:%.*]] = load float, ptr addrspace(5) [[ARRAYIDX]], align 16
; CHECK-NEXT:    [[GEP1:%.*]] = getelementptr inbounds [8 x float], ptr addrspace(5) [[ARRAYIDX]], i32 0, i32 1
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr i8, ptr addrspace(5) [[ARRAYIDX]], i64 4
; CHECK-NEXT:    [[TMP1:%.*]] = load <3 x float>, ptr addrspace(5) [[TMP0]], align 4
; CHECK-NEXT:    [[LOAD3:%.*]] = extractelement <3 x float> [[TMP1]], i32 2
; CHECK-NEXT:    [[LOAD2:%.*]] = extractelement <3 x float> [[TMP1]], i32 1
; CHECK-NEXT:    [[LOAD1:%.*]] = extractelement <3 x float> [[TMP1]], i32 0
; CHECK-NEXT:    [[GEP2:%.*]] = getelementptr inbounds [8 x float], ptr addrspace(5) [[ARRAYIDX]], i32 0, i32 2
; CHECK-NEXT:    [[GEP3:%.*]] = getelementptr inbounds [8 x float], ptr addrspace(5) [[ARRAYIDX]], i32 0, i32 3
; CHECK-NEXT:    [[ADD0:%.*]] = fadd contract float [[LOAD0]], 1.000000e+00
; CHECK-NEXT:    [[ADD1:%.*]] = fadd contract float [[LOAD1]], 2.000000e+00
; CHECK-NEXT:    [[ADD2:%.*]] = fadd contract float [[LOAD2]], 3.000000e+00
; CHECK-NEXT:    [[ADD3:%.*]] = fadd contract float [[LOAD3]], 4.000000e+00
; CHECK-NEXT:    store float [[ADD0]], ptr addrspace(5) [[ARRAYIDX]], align 16
; CHECK-NEXT:    [[TMP5:%.*]] = getelementptr i8, ptr addrspace(5) [[ARRAYIDX]], i64 4
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <3 x float> undef, float [[ADD1]], i32 0
; CHECK-NEXT:    [[TMP7:%.*]] = insertelement <3 x float> [[TMP6]], float [[ADD2]], i32 1
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <3 x float> [[TMP7]], float [[ADD3]], i32 2
; CHECK-NEXT:    store <3 x float> [[TMP8]], ptr addrspace(5) [[TMP5]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %accumulators = alloca [4 x [1 x [8 x float]]], align 32, addrspace(5)
  %arrayidx = getelementptr inbounds [4 x [1 x [8 x float]]], ptr addrspace(5) %accumulators, i32 0, i32 %idx, i32 0

  ; Load accumulator values
  %load0 = load float, ptr addrspace(5) %arrayidx, align 16
  %gep1 = getelementptr inbounds [8 x float], ptr addrspace(5) %arrayidx, i32 0, i32 1
  %load1 = load float, ptr addrspace(5) %gep1, align 4
  %gep2 = getelementptr inbounds [8 x float], ptr addrspace(5) %arrayidx, i32 0, i32 2
  %load2 = load float, ptr addrspace(5) %gep2, align 8
  %gep3 = getelementptr inbounds [8 x float], ptr addrspace(5) %arrayidx, i32 0, i32 3
  %load3 = load float, ptr addrspace(5) %gep3, align 4

  ; Add input values
  %add0 = fadd contract float %load0, 1.0
  %add1 = fadd contract float %load1, 2.0
  %add2 = fadd contract float %load2, 3.0
  %add3 = fadd contract float %load3, 4.0

  ; Store back
  store float %add0, ptr addrspace(5) %arrayidx, align 16
  store float %add1, ptr addrspace(5) %gep1, align 4
  store float %add2, ptr addrspace(5) %gep2, align 8
  store float %add3, ptr addrspace(5) %gep3, align 4

  ret void
}
