; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1100 -amdgpu-uniform-intrinsic-combine -S < %s | FileCheck %s -check-prefix=CHECK

define i32 @test_uniform_src(i32 %index, i32 inreg %src) {
; CHECK-LABEL: define i32 @test_uniform_src(
; CHECK-SAME: i32 [[INDEX:%.*]], i32 inreg [[SRC:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    ret i32 [[SRC]]
;
  %res = call i32 @llvm.amdgcn.ds.bpermute(i32 %index, i32 %src)
  ret i32 %res
}

define i32 @test_uniform_index_sgpr(i32 inreg %lane, i32 %src) {
; CHECK-LABEL: define i32 @test_uniform_index_sgpr(
; CHECK-SAME: i32 inreg [[LANE:%.*]], i32 [[SRC:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[INDEX:%.*]] = shl i32 [[LANE]], 2
; CHECK-NEXT:    [[TMP1:%.*]] = lshr i32 [[INDEX]], 2
; CHECK-NEXT:    [[RES:%.*]] = call i32 @llvm.amdgcn.readlane.i32(i32 [[SRC]], i32 [[TMP1]])
; CHECK-NEXT:    ret i32 [[RES]]
;
  %index = shl i32 %lane, 2
  %res = call i32 @llvm.amdgcn.ds.bpermute(i32 %index, i32 %src)
  ret i32 %res
}

define i32 @test_uniform_index_intrinsic(i32 %lanearg, i32 %src) {
; CHECK-LABEL: define i32 @test_uniform_index_intrinsic(
; CHECK-SAME: i32 [[LANEARG:%.*]], i32 [[SRC:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LANE:%.*]] = call i32 @llvm.amdgcn.readfirstlane.i32(i32 [[LANEARG]])
; CHECK-NEXT:    [[INDEX:%.*]] = shl i32 [[LANE]], 2
; CHECK-NEXT:    [[TMP1:%.*]] = lshr i32 [[INDEX]], 2
; CHECK-NEXT:    [[RES:%.*]] = call i32 @llvm.amdgcn.readlane.i32(i32 [[SRC]], i32 [[TMP1]])
; CHECK-NEXT:    ret i32 [[RES]]
;
  %lane = call i32 @llvm.amdgcn.readfirstlane.i32(i32 %lanearg)
  %index = shl i32 %lane, 2
  %res = call i32 @llvm.amdgcn.ds.bpermute(i32 %index, i32 %src)
  ret i32 %res
}

define i32 @test_uniform_index_multi(i32 inreg %idx, i32 %src) {
; CHECK-LABEL: define i32 @test_uniform_index_multi(
; CHECK-SAME: i32 inreg [[IDX:%.*]], i32 [[SRC:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[COND:%.*]] = icmp ult i32 [[IDX]], 16
; CHECK-NEXT:    [[MASK:%.*]] = call i32 @llvm.amdgcn.ballot.i32(i1 [[COND]])
; CHECK-NEXT:    [[LANE_IDX:%.*]] = call i32 @llvm.cttz.i32(i32 [[MASK]], i1 true)
; CHECK-NEXT:    [[INDEX:%.*]] = shl i32 [[LANE_IDX]], 2
; CHECK-NEXT:    [[TMP1:%.*]] = lshr i32 [[INDEX]], 2
; CHECK-NEXT:    [[RES:%.*]] = call i32 @llvm.amdgcn.readlane.i32(i32 [[SRC]], i32 [[TMP1]])
; CHECK-NEXT:    ret i32 [[RES]]
;
  %cond = icmp ult i32 %idx, 16
  %mask = call i32 @llvm.amdgcn.ballot.i32(i1 %cond)
  %lane_idx = call i32 @llvm.cttz.i32(i32 %mask, i1 true)
  %index = shl i32 %lane_idx, 2
  %res = call i32 @llvm.amdgcn.ds.bpermute(i32 %index, i32 %src)
  ret i32 %res
}

define i32 @negative_test_divergent_index(i32 %lane, i32 %src) {
; CHECK-LABEL: define i32 @negative_test_divergent_index(
; CHECK-SAME: i32 [[LANE:%.*]], i32 [[SRC:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[INDEX:%.*]] = shl i32 [[LANE]], 2
; CHECK-NEXT:    [[RES:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[INDEX]], i32 [[SRC]])
; CHECK-NEXT:    ret i32 [[RES]]
;
  %index = shl i32 %lane, 2
  %res = call i32 @llvm.amdgcn.ds.bpermute(i32 %index, i32 %src)
  ret i32 %res
}

define i32 @negative_test_divergent_index_multi(i32 %lane, i32 %src) {
; CHECK-LABEL: define i32 @negative_test_divergent_index_multi(
; CHECK-SAME: i32 [[LANE:%.*]], i32 [[SRC:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[ADD:%.*]] = add i32 [[LANE]], 1
; CHECK-NEXT:    [[INDEX:%.*]] = shl i32 [[ADD]], 2
; CHECK-NEXT:    [[RES:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[INDEX]], i32 [[SRC]])
; CHECK-NEXT:    ret i32 [[RES]]
;
  %add = add i32 %lane, 1
  %index = shl i32 %add, 2
  %res = call i32 @llvm.amdgcn.ds.bpermute(i32 %index, i32 %src)
  ret i32 %res
}

define i32 @negative_test_divergent_intrinsic(i32 %src) {
; CHECK-LABEL: define i32 @negative_test_divergent_intrinsic(
; CHECK-SAME: i32 [[SRC:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:    [[LANE:%.*]] = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
; CHECK-NEXT:    [[INDEX:%.*]] = shl i32 [[LANE]], 2
; CHECK-NEXT:    [[RES:%.*]] = call i32 @llvm.amdgcn.ds.bpermute(i32 [[INDEX]], i32 [[SRC]])
; CHECK-NEXT:    ret i32 [[RES]]
;
  %lane = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
  %index = shl i32 %lane, 2
  %res = call i32 @llvm.amdgcn.ds.bpermute(i32 %index, i32 %src)
  ret i32 %res
}
