# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -mtriple=amdgcn--amdpal -mcpu=gfx1200 -amdgpu-enable-machine-level-inliner -run-pass=amdgpu-machine-level-inliner %s -o - | FileCheck %s

--- |
  define amdgpu_cs void @inline_simple_wwf(i32 %input, ptr addrspace(1) %output) { ret void }
  define amdgpu_gfx_whole_wave i32 @simple_whole_wave_func(i1 %active, i32 %x) { ret i32 0 }

  define amdgpu_cs void @inline_multiple_wwf(i32 %x, i32 %y, ptr addrspace(1) %out1, ptr addrspace(1) %out2) { ret void }
  define amdgpu_gfx_whole_wave i32 @another_whole_wave_func(i1 %active, i32 %a, i32 %b) { ret i32 0 }

  define amdgpu_cs void @inline_wwf_with_local(i32 %y) {
    %local = alloca i32, addrspace(5)
    ret void
  }
  define amdgpu_gfx_whole_wave i32 @whole_wave_func_with_local(i1 %mask, i32 %x) {
    %local = alloca i32, addrspace(5)
    ret i32 0
  }

  define amdgpu_cs void @dont_inline_non_wwf(i32 %input, ptr addrspace(1) %output) { ret void }
  define amdgpu_gfx i32 @regular_function(i32 %x) { ret i32 0 }
...
---
name:            inline_simple_wwf
alignment:       1
tracksRegLiveness: true
noPhis:          true
isSSA:           false
noVRegs:         true
hasFakeUses:     false
tracksDebugUserValues: true
frameInfo:
  maxAlignment:    1
  adjustsStack:    true
  hasCalls:        true
  maxCallFrameSize: 0
  isCalleeSavedInfoValid: true
machineFunctionInfo:
  maxKernArgAlign: 4
  isEntryFunction: true
  numWaveDispatchVGPRs: 3
  stackPtrOffsetReg: '$sgpr32'
  mode:
    ieee:            false
  occupancy:       16
  sgprForEXECCopy: '$sgpr105'
body:             |
  bb.0:
    liveins: $vgpr0, $vgpr1, $vgpr2

    ; CHECK-LABEL: name: inline_simple_wwf
    ; CHECK: successors: %bb.2(0x80000000)
    ; CHECK-NEXT: liveins: $vgpr0, $vgpr1, $vgpr2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $sgpr32 = S_MOV_B32 0
    ; CHECK-NEXT: $vgpr41 = V_MOV_B32_e32 $vgpr2, implicit $exec, implicit $exec
    ; CHECK-NEXT: $vgpr40 = V_MOV_B32_e32 $vgpr1, implicit $exec, implicit $exec
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .2:
    ; CHECK-NEXT: successors: %bb.1(0x80000000)
    ; CHECK-NEXT: liveins: $vgpr0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $sgpr0 = S_XOR_SAVEEXEC_B32 -1, implicit-def $exec, implicit-def dead $scc, implicit $exec
    ; CHECK-NEXT: SCRATCH_STORE_DWORD_SADDR $vgpr0, $sgpr32, 0, 0, implicit $exec, implicit $flat_scr
    ; CHECK-NEXT: $exec_lo = S_MOV_B32 -1
    ; CHECK-NEXT: $vgpr0 = V_ADD_U32_e32 42, killed $vgpr0, implicit $exec
    ; CHECK-NEXT: $exec_lo = S_XOR_B32 $sgpr0, -1, implicit-def $scc
    ; CHECK-NEXT: $vgpr0 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 0, 0, implicit $exec, implicit $flat_scr, implicit $vgpr0(tied-def 0)
    ; CHECK-NEXT: $exec_lo = S_MOV_B32 $sgpr0
    ; CHECK-NEXT: S_BRANCH %bb.1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .1:
    ; CHECK-NEXT: liveins: $vgpr40_vgpr41, $vgpr0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: GLOBAL_STORE_DWORD killed renamable $vgpr40_vgpr41, killed renamable $vgpr0, 0, 0, implicit $exec :: (store (s32) into %ir.output, addrspace 1)
    ; CHECK-NEXT: S_ENDPGM 0
    $sgpr32 = S_MOV_B32 0
    $vgpr41 = V_MOV_B32_e32 $vgpr2, implicit $exec, implicit $exec
    $vgpr40 = V_MOV_B32_e32 $vgpr1, implicit $exec, implicit $exec
    renamable $sgpr1 = S_MOV_B32 target-flags(amdgpu-abs32-hi) @simple_whole_wave_func
    renamable $sgpr0 = S_MOV_B32 target-flags(amdgpu-abs32-lo) @simple_whole_wave_func
    dead $sgpr30_sgpr31 = SI_CALL killed renamable $sgpr0_sgpr1, @simple_whole_wave_func, csr_amdgpu_si_gfx, implicit $vgpr0, implicit-def $vgpr0
    GLOBAL_STORE_DWORD killed renamable $vgpr40_vgpr41, killed renamable $vgpr0, 0, 0, implicit $exec :: (store (s32) into %ir.output, addrspace 1)
    S_ENDPGM 0
...
---
name:            simple_whole_wave_func
alignment:       1
tracksRegLiveness: true
noPhis:          true
isSSA:           false
noVRegs:         true
hasFakeUses:     false
tracksDebugUserValues: true
frameInfo:
  stackSize:       8
  maxAlignment:    4
  maxCallFrameSize: 0
  isCalleeSavedInfoValid: true
stack:
  - { id: 0, type: spill-slot, size: 4, alignment: 4 }
  - { id: 1, offset: 4, size: 4, alignment: 4 }
machineFunctionInfo:
  maxKernArgAlign: 1
  numWaveDispatchVGPRs: 1
  frameOffsetReg:  '$sgpr33'
  stackPtrOffsetReg: '$sgpr32'
  returnsVoid:     false
  occupancy:       16
  wwmReservedRegs:
    - '$vgpr0'
  scavengeFI:      '%stack.1'
  isWholeWaveFunction: true
body:             |
  bb.0:
    liveins: $vgpr0

    ; This function is going to get inlined, so there shouldn't be any CHECKS for it.
    ; CHECK-NOT: name: simple_whole_wave_func
    $sgpr0 = S_XOR_SAVEEXEC_B32 -1, implicit-def $exec, implicit-def dead $scc, implicit $exec
    SCRATCH_STORE_DWORD_SADDR $vgpr0, $sgpr32, 0, 0, implicit $exec, implicit $flat_scr :: (store (s32) into %stack.0, addrspace 5)
    $exec_lo = S_MOV_B32 -1
    $vgpr0 = V_ADD_U32_e32 42, killed $vgpr0, implicit $exec
    $exec_lo = S_XOR_B32 $sgpr0, -1, implicit-def $scc
    $vgpr0 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 0, 0, implicit $exec, implicit $flat_scr, implicit $vgpr0(tied-def 0) :: (load (s32) from %stack.0, addrspace 5)
    $exec_lo = S_MOV_B32 $sgpr0
    S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0
...
---
name:            another_whole_wave_func
alignment:       1
tracksRegLiveness: true
noPhis:          true
isSSA:           false
noVRegs:         true
hasFakeUses:     false
tracksDebugUserValues: true
frameInfo:
  stackSize:       8
  maxAlignment:    4
  maxCallFrameSize: 0
  isCalleeSavedInfoValid: true
stack:
  - { id: 0, type: spill-slot, size: 4, alignment: 4 }
  - { id: 1, offset: 4, size: 4, alignment: 4 }
machineFunctionInfo:
  maxKernArgAlign: 1
  numWaveDispatchVGPRs: 2
  frameOffsetReg:  '$sgpr33'
  stackPtrOffsetReg: '$sgpr32'
  returnsVoid:     false
  occupancy:       16
  wwmReservedRegs:
    - '$vgpr0'
  scavengeFI:      '%stack.1'
  isWholeWaveFunction: true
body:             |
  bb.0:
    liveins: $vgpr0, $vgpr1

    ; This function is going to get inlined, so there shouldn't be any CHECKS for it.
    ; CHECK-NOT: name: another_whole_wave_func
    $sgpr0 = S_XOR_SAVEEXEC_B32 -1, implicit-def $exec, implicit-def dead $scc, implicit $exec
    SCRATCH_STORE_DWORD_SADDR $vgpr0, $sgpr32, 0, 0, implicit $exec, implicit $flat_scr :: (store (s32) into %stack.0, addrspace 5)
    $exec_lo = S_MOV_B32 -1
    $vgpr0 = V_ADD_U32_e32 42, killed $vgpr0, implicit $exec
    $sgpr1 = S_MOV_B32 71
    $exec_lo = S_XOR_B32 $sgpr0, -1, implicit-def $scc
    $vgpr0 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 0, 0, implicit $exec, implicit $flat_scr, implicit $vgpr0(tied-def 0) :: (load (s32) from %stack.0, addrspace 5)
    $exec_lo = S_MOV_B32 $sgpr0
    S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0
...
---
name:            inline_multiple_wwf
alignment:       1
tracksRegLiveness: true
noPhis:          true
isSSA:           false
noVRegs:         true
hasFakeUses:     false
tracksDebugUserValues: true
frameInfo:
  maxAlignment:    1
  adjustsStack:    true
  hasCalls:        true
  maxCallFrameSize: 0
  isCalleeSavedInfoValid: true
machineFunctionInfo:
  maxKernArgAlign: 4
  isEntryFunction: true
  numWaveDispatchVGPRs: 6
  stackPtrOffsetReg: '$sgpr32'
  mode:
    ieee:            false
  occupancy:       16
  sgprForEXECCopy: '$sgpr105'
body:             |
  bb.0:
    liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5

    ; CHECK-LABEL: name: inline_multiple_wwf
    ; CHECK: successors: %bb.2(0x80000000)
    ; CHECK-NEXT: liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $sgpr32 = S_MOV_B32 0
    ; CHECK-NEXT: $vgpr41 = V_MOV_B32_e32 $vgpr5, implicit $exec, implicit $exec
    ; CHECK-NEXT: $vgpr44 = V_MOV_B32_e32 $vgpr0, implicit $exec, implicit $exec
    ; CHECK-NEXT: $vgpr40 = V_MOV_B32_e32 $vgpr4, implicit $exec, implicit $exec
    ; CHECK-NEXT: $vgpr43 = V_MOV_B32_e32 $vgpr3, implicit $exec, implicit $exec
    ; CHECK-NEXT: $vgpr42 = V_MOV_B32_e32 $vgpr2, implicit $exec, implicit $exec
    ; CHECK-NEXT: $vgpr45 = V_MOV_B32_e32 $vgpr1, implicit $exec, implicit $exec
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .2:
    ; CHECK-NEXT: successors: %bb.1(0x80000000)
    ; CHECK-NEXT: liveins: $vgpr0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $sgpr0 = S_XOR_SAVEEXEC_B32 -1, implicit-def $exec, implicit-def dead $scc, implicit $exec
    ; CHECK-NEXT: SCRATCH_STORE_DWORD_SADDR $vgpr0, $sgpr32, 0, 0, implicit $exec, implicit $flat_scr
    ; CHECK-NEXT: $exec_lo = S_MOV_B32 -1
    ; CHECK-NEXT: $vgpr0 = V_ADD_U32_e32 42, killed $vgpr0, implicit $exec
    ; CHECK-NEXT: $exec_lo = S_XOR_B32 $sgpr0, -1, implicit-def $scc
    ; CHECK-NEXT: $vgpr0 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 0, 0, implicit $exec, implicit $flat_scr, implicit $vgpr0(tied-def 0)
    ; CHECK-NEXT: $exec_lo = S_MOV_B32 $sgpr0
    ; CHECK-NEXT: S_BRANCH %bb.1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .1:
    ; CHECK-NEXT: successors: %bb.4(0x80000000)
    ; CHECK-NEXT: liveins: $vgpr40_vgpr41, $vgpr45, $vgpr42_vgpr43, $vgpr44, $vgpr0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $sgpr1 = S_MOV_B32 target-flags(amdgpu-abs32-hi) @dont_inline_non_wwf
    ; CHECK-NEXT: renamable $sgpr0 = S_MOV_B32 target-flags(amdgpu-abs32-lo) @dont_inline_non_wwf
    ; CHECK-NEXT: $vgpr46 = V_MOV_B32_e32 $vgpr0, implicit $exec, implicit $exec
    ; CHECK-NEXT: $vgpr0 = V_MOV_B32_e32 killed $vgpr44, implicit $exec, implicit $exec
    ; CHECK-NEXT: $vgpr1 = V_MOV_B32_e32 killed $vgpr45, implicit $exec, implicit $exec
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .4:
    ; CHECK-NEXT: successors: %bb.3(0x80000000)
    ; CHECK-NEXT: liveins: $vgpr0, $vgpr1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $sgpr0 = S_XOR_SAVEEXEC_B32 -1, implicit-def $exec, implicit-def dead $scc, implicit $exec
    ; CHECK-NEXT: SCRATCH_STORE_DWORD_SADDR $vgpr0, $sgpr32, 0, 0, implicit $exec, implicit $flat_scr
    ; CHECK-NEXT: $exec_lo = S_MOV_B32 -1
    ; CHECK-NEXT: $vgpr0 = V_ADD_U32_e32 42, killed $vgpr0, implicit $exec
    ; CHECK-NEXT: $sgpr1 = S_MOV_B32 71
    ; CHECK-NEXT: $exec_lo = S_XOR_B32 $sgpr0, -1, implicit-def $scc
    ; CHECK-NEXT: $vgpr0 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 0, 0, implicit $exec, implicit $flat_scr, implicit $vgpr0(tied-def 0)
    ; CHECK-NEXT: $exec_lo = S_MOV_B32 $sgpr0
    ; CHECK-NEXT: S_BRANCH %bb.3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .3:
    ; CHECK-NEXT: liveins: $vgpr40_vgpr41, $vgpr0, $vgpr42_vgpr43, $vgpr46
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: GLOBAL_STORE_DWORD killed renamable $vgpr42_vgpr43, killed renamable $vgpr46, 0, 0, implicit $exec :: (store (s32) into %ir.out1, addrspace 1)
    ; CHECK-NEXT: GLOBAL_STORE_DWORD killed renamable $vgpr40_vgpr41, killed renamable $vgpr0, 0, 0, implicit $exec :: (store (s32) into %ir.out2, addrspace 1)
    ; CHECK-NEXT: S_ENDPGM 0
    $sgpr32 = S_MOV_B32 0
    $vgpr41 = V_MOV_B32_e32 $vgpr5, implicit $exec, implicit $exec
    $vgpr44 = V_MOV_B32_e32 $vgpr0, implicit $exec, implicit $exec
    $vgpr40 = V_MOV_B32_e32 $vgpr4, implicit $exec, implicit $exec
    $vgpr43 = V_MOV_B32_e32 $vgpr3, implicit $exec, implicit $exec
    $vgpr42 = V_MOV_B32_e32 $vgpr2, implicit $exec, implicit $exec
    $vgpr45 = V_MOV_B32_e32 $vgpr1, implicit $exec, implicit $exec
    renamable $sgpr1 = S_MOV_B32 target-flags(amdgpu-abs32-hi) @simple_whole_wave_func
    renamable $sgpr0 = S_MOV_B32 target-flags(amdgpu-abs32-lo) @simple_whole_wave_func
    dead $sgpr30_sgpr31 = SI_CALL killed renamable $sgpr0_sgpr1, @simple_whole_wave_func, csr_amdgpu_si_gfx, implicit $vgpr0, implicit-def $vgpr0
    renamable $sgpr1 = S_MOV_B32 target-flags(amdgpu-abs32-hi) @dont_inline_non_wwf
    renamable $sgpr0 = S_MOV_B32 target-flags(amdgpu-abs32-lo) @dont_inline_non_wwf
    $vgpr46 = V_MOV_B32_e32 $vgpr0, implicit $exec, implicit $exec
    renamable $sgpr1 = S_MOV_B32 target-flags(amdgpu-abs32-hi) @another_whole_wave_func
    renamable $sgpr0 = S_MOV_B32 target-flags(amdgpu-abs32-lo) @another_whole_wave_func
    $vgpr0 = V_MOV_B32_e32 killed $vgpr44, implicit $exec, implicit $exec
    $vgpr1 = V_MOV_B32_e32 killed $vgpr45, implicit $exec, implicit $exec
    dead $sgpr30_sgpr31 = SI_CALL killed renamable $sgpr0_sgpr1, @another_whole_wave_func, csr_amdgpu_si_gfx, implicit $vgpr0, implicit $vgpr1, implicit-def $vgpr0
    GLOBAL_STORE_DWORD killed renamable $vgpr42_vgpr43, killed renamable $vgpr46, 0, 0, implicit $exec :: (store (s32) into %ir.out1, addrspace 1)
    GLOBAL_STORE_DWORD killed renamable $vgpr40_vgpr41, killed renamable $vgpr0, 0, 0, implicit $exec :: (store (s32) into %ir.out2, addrspace 1)
    S_ENDPGM 0
...
---
name:            inline_wwf_with_local
tracksRegLiveness: true
frameInfo:
  hasCalls: true
stack:
  - { id: 0, name: local, type: default, offset: 0, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      local-offset: 0, debug-info-variable: '', debug-info-expression: '',
      debug-info-location: '' }
  - { id: 1, name: '', type: default, offset: 4, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
body:             |
  bb.0:
    liveins: $vgpr0

    ; CHECK-LABEL: name: inline_wwf_with_local
    ; CHECK: successors: %bb.2(0x80000000)
    ; CHECK-NEXT: liveins: $vgpr0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $sgpr32 = S_MOV_B32 16
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .2:
    ; CHECK-NEXT: successors: %bb.1(0x80000000)
    ; CHECK-NEXT: liveins: $vgpr0, $vgpr1, $vgpr1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $sgpr0 = S_XOR_SAVEEXEC_B32 -1, implicit-def $exec, implicit-def dead $scc, implicit $exec
    ; CHECK-NEXT: SCRATCH_STORE_DWORD_SADDR $vgpr1, $sgpr32, 8, 0, implicit $exec, implicit $flat_scr
    ; CHECK-NEXT: $exec_lo = S_MOV_B32 -1
    ; CHECK-NEXT: $vgpr1 = V_MUL_LO_U32_e64 $vgpr0, 18, implicit $exec
    ; CHECK-NEXT: SCRATCH_STORE_DWORD_SADDR killed $vgpr1, $sgpr32, 0, 0, implicit $exec, implicit $flat_scr
    ; CHECK-NEXT: $exec_lo = S_XOR_B32 $sgpr0, -1, implicit-def $scc
    ; CHECK-NEXT: $vgpr1 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 8, 0, implicit $exec, implicit $flat_scr
    ; CHECK-NEXT: $exec_lo = S_MOV_B32 $sgpr0
    ; CHECK-NEXT: S_BRANCH %bb.1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: .1:
    ; CHECK-NEXT: liveins: $vgpr0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: SCRATCH_STORE_DWORD_ST killed $vgpr0, 0, 0, implicit $exec, implicit $flat_scr :: (volatile store (s32) into %ir.local, addrspace 5)
    ; CHECK-NEXT: S_ENDPGM 0
    $sgpr32 = S_MOV_B32 16
    $sgpr1 = S_MOV_B32 target-flags(amdgpu-abs32-hi) @whole_wave_func_with_local
    $sgpr0 = S_MOV_B32 target-flags(amdgpu-abs32-lo) @whole_wave_func_with_local
    dead $sgpr30_sgpr31 = SI_CALL killed $sgpr0_sgpr1, @whole_wave_func_with_local, csr_amdgpu_si_gfx, implicit $vgpr0, implicit-def $vgpr0
    SCRATCH_STORE_DWORD_ST killed $vgpr0, 0, 0, implicit $exec, implicit $flat_scr :: (volatile store (s32) into %ir.local, addrspace 5)
    S_ENDPGM 0
...
---
name:            whole_wave_func_with_local
tracksRegLiveness: true
frameInfo:
  stackSize:       16
stack:
  - { id: 0, name: local, type: default, offset: 0, size: 8, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      local-offset: 0, debug-info-variable: '', debug-info-expression: '',
      debug-info-location: '' }
  - { id: 1, name: '', type: spill-slot, offset: 8, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
  - { id: 2, name: '', type: default, offset: 12, size: 4, alignment: 4,
      stack-id: default, callee-saved-register: '', callee-saved-restored: true,
      debug-info-variable: '', debug-info-expression: '', debug-info-location: '' }
machineFunctionInfo:
  isEntryFunction: false
  isChainFunction: false
  scratchRSrcReg:  '$private_rsrc_reg'
  frameOffsetReg:  '$sgpr33'
  stackPtrOffsetReg: '$sgpr32'
  wwmReservedRegs:
    - '$vgpr1'
  scavengeFI:      '%stack.2'
  isWholeWaveFunction: true
body:             |
  bb.0:
    liveins: $vgpr0, $vgpr1, $vgpr1

    ; CHECK-NOT: name: whole_wave_func_with_local
    $sgpr0 = S_XOR_SAVEEXEC_B32 -1, implicit-def $exec, implicit-def dead $scc, implicit $exec
    SCRATCH_STORE_DWORD_SADDR $vgpr1, $sgpr32, 8, 0, implicit $exec, implicit $flat_scr :: (store (s32) into %stack.1, addrspace 5)
    $exec_lo = S_MOV_B32 -1
    $vgpr1 = V_MUL_LO_U32_e64 $vgpr0, 18, implicit $exec
    SCRATCH_STORE_DWORD_SADDR killed $vgpr1, $sgpr32, 0, 0, implicit $exec, implicit $flat_scr :: (volatile store (s32) into %ir.local, addrspace 5)
    $exec_lo = S_XOR_B32 $sgpr0, -1, implicit-def $scc
    $vgpr1 = SCRATCH_LOAD_DWORD_SADDR $sgpr32, 8, 0, implicit $exec, implicit $flat_scr :: (load (s32) from %stack.1, addrspace 5)
    $exec_lo = S_MOV_B32 $sgpr0
    S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0
...
---
name:            dont_inline_non_wwf
alignment:       1
tracksRegLiveness: true
noPhis:          true
isSSA:           false
noVRegs:         true
hasFakeUses:     false
tracksDebugUserValues: true
frameInfo:
  maxAlignment:    1
  adjustsStack:    true
  hasCalls:        true
  maxCallFrameSize: 0
  isCalleeSavedInfoValid: true
machineFunctionInfo:
  maxKernArgAlign: 4
  isEntryFunction: true
  numWaveDispatchVGPRs: 3
  stackPtrOffsetReg: '$sgpr32'
  mode:
    ieee:            false
  occupancy:       16
  sgprForEXECCopy: '$sgpr105'
body:             |
  bb.0:
    liveins: $vgpr0, $vgpr1, $vgpr2

    ; CHECK-LABEL: name: dont_inline_non_wwf
    ; CHECK: liveins: $vgpr0, $vgpr1, $vgpr2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $sgpr32 = S_MOV_B32 0
    ; CHECK-NEXT: $vgpr41 = V_MOV_B32_e32 $vgpr2, implicit $exec, implicit $exec
    ; CHECK-NEXT: $vgpr40 = V_MOV_B32_e32 $vgpr1, implicit $exec, implicit $exec
    ; CHECK-NEXT: renamable $sgpr1 = S_MOV_B32 target-flags(amdgpu-abs32-hi) @regular_function
    ; CHECK-NEXT: renamable $sgpr0 = S_MOV_B32 target-flags(amdgpu-abs32-lo) @regular_function
    ; CHECK-NEXT: dead $sgpr30_sgpr31 = SI_CALL killed renamable $sgpr0_sgpr1, @regular_function, csr_amdgpu, implicit $vgpr0, implicit-def $vgpr0
    ; CHECK-NEXT: GLOBAL_STORE_DWORD killed renamable $vgpr40_vgpr41, killed renamable $vgpr0, 0, 0, implicit $exec :: (store (s32) into %ir.output, addrspace 1)
    ; CHECK-NEXT: S_ENDPGM 0
    $sgpr32 = S_MOV_B32 0
    $vgpr41 = V_MOV_B32_e32 $vgpr2, implicit $exec, implicit $exec
    $vgpr40 = V_MOV_B32_e32 $vgpr1, implicit $exec, implicit $exec
    renamable $sgpr1 = S_MOV_B32 target-flags(amdgpu-abs32-hi) @regular_function
    renamable $sgpr0 = S_MOV_B32 target-flags(amdgpu-abs32-lo) @regular_function
    dead $sgpr30_sgpr31 = SI_CALL killed renamable $sgpr0_sgpr1, @regular_function, csr_amdgpu, implicit $vgpr0, implicit-def $vgpr0
    GLOBAL_STORE_DWORD killed renamable $vgpr40_vgpr41, killed renamable $vgpr0, 0, 0, implicit $exec :: (store (s32) into %ir.output, addrspace 1)
    S_ENDPGM 0
...
---
name:            regular_function
alignment:       1
tracksRegLiveness: true
noPhis:          true
isSSA:           false
noVRegs:         true
hasFakeUses:     false
tracksDebugUserValues: true
frameInfo:
  maxAlignment:    1
  maxCallFrameSize: 0
  isCalleeSavedInfoValid: true
machineFunctionInfo:
  maxKernArgAlign: 1
  numWaveDispatchVGPRs: 1
  frameOffsetReg:  '$sgpr33'
  stackPtrOffsetReg: '$sgpr32'
  returnsVoid:     false
  occupancy:       16
body:             |
  bb.0:
    liveins: $vgpr0

    ; CHECK-LABEL: name: regular_function
    ; CHECK: liveins: $vgpr0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: renamable $vgpr0 = V_ADD_U32_e32 10, killed $vgpr0, implicit $exec
    ; CHECK-NEXT: S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0
    renamable $vgpr0 = V_ADD_U32_e32 10, killed $vgpr0, implicit $exec
    S_SETPC_B64_return undef $sgpr30_sgpr31, implicit $vgpr0
...
