; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -mtriple=amdgcn-amd-amdhsa -passes=amdgpu-simplifylib %s | FileCheck %s

define float @test_tdo_scalar_f32_cbrt() {
; CHECK-LABEL: define float @test_tdo_scalar_f32_cbrt() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret float 1.000000e+00
;
entry:
  %c = call float @_Z4cbrtf(float 1.000000e+00)
  ret float %c
}

define <4 x float> @test_tdo_v2_f32_cbrt() {
; CHECK-LABEL: define <4 x float> @test_tdo_v2_f32_cbrt() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret <4 x float> <float 0.000000e+00, float -0.000000e+00, float 1.000000e+00, float -1.000000e+00>
;
entry:
  %c = call <4 x float> @_Z4cbrtDv4_f(<4 x float> <float 0.000000e+00, float -0.000000e+00, float 1.000000e+00, float -1.000000e+00>)
  ret <4 x float> %c
}

define half @test_tdo_scalar_f16_cbrt() {
; CHECK-LABEL: define half @test_tdo_scalar_f16_cbrt() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret half 1.000000e+00
;
entry:
  %c = call half @_Z4cbrtDh(half 1.000000e+00)
  ret half %c
}

define <4 x half> @test_tdo_v2_f16_cbrt() {
; CHECK-LABEL: define <4 x half> @test_tdo_v2_f16_cbrt() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret <4 x half> <half 0.000000e+00, half -0.000000e+00, half 1.000000e+00, half -1.000000e+00>
;
entry:
  %c = call <4 x half> @_Z4cbrtDv4_Dh(<4 x half> <half 0.000000e+00, half -0.000000e+00, half 1.000000e+00, half -1.000000e+00>)
  ret <4 x half> %c
}

define double @test_tdo_scalar_f64_cbrt() {
; CHECK-LABEL: define double @test_tdo_scalar_f64_cbrt() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret double 1.000000e+00
;
entry:
  %c = call double @_Z4cbrtd(double 1.000000e+00)
  ret double %c
}

define <4 x double> @test_tdo_v2_f64_cbrt() {
; CHECK-LABEL: define <4 x double> @test_tdo_v2_f64_cbrt() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret <4 x double> <double 0.000000e+00, double -0.000000e+00, double 1.000000e+00, double -1.000000e+00>
;
entry:
  %c = call <4 x double> @_Z4cbrtDv4_d(<4 x double> <double 0.000000e+00, double -0.000000e+00, double 1.000000e+00, double -1.000000e+00>)
  ret <4 x double> %c
}

declare float        @_Z4cbrtf(float)
declare <4 x float>  @_Z4cbrtDv4_f(<4 x float>)
declare half         @_Z4cbrtDh(half)
declare <4 x half>   @_Z4cbrtDv4_Dh(<4 x half>)
declare double       @_Z4cbrtd(double)
declare <4 x double> @_Z4cbrtDv4_d(<4 x double>)
