; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5

; RUN: llc -mtriple=amdgcn -amdgpu-codegenprepare-break-large-phis-threshold=4096 < %s | FileCheck -check-prefix=GCN %s
; RUN: llc -mtriple=amdgcn -mcpu=tonga -amdgpu-codegenprepare-break-large-phis-threshold=4096 < %s | FileCheck -check-prefixes=VI %s
; RUN: llc -mtriple=amdgcn -mcpu=gfx900 -amdgpu-codegenprepare-break-large-phis-threshold=4096 < %s | FileCheck -check-prefixes=GFX9 %s
; RUN: llc -mtriple=amdgcn -mcpu=gfx1100 -amdgpu-codegenprepare-break-large-phis-threshold=4096 < %s | FileCheck -check-prefixes=GFX11 %s

define <16 x float> @v_bitcast_v16i32_to_v16f32(<16 x i32> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v16i32_to_v16f32:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB0_2
; GCN-NEXT:  ; %bb.1: ; %cmp.true
; GCN-NEXT:    v_add_i32_e32 v15, vcc, 3, v15
; GCN-NEXT:    v_add_i32_e32 v14, vcc, 3, v14
; GCN-NEXT:    v_add_i32_e32 v13, vcc, 3, v13
; GCN-NEXT:    v_add_i32_e32 v12, vcc, 3, v12
; GCN-NEXT:    v_add_i32_e32 v11, vcc, 3, v11
; GCN-NEXT:    v_add_i32_e32 v10, vcc, 3, v10
; GCN-NEXT:    v_add_i32_e32 v9, vcc, 3, v9
; GCN-NEXT:    v_add_i32_e32 v8, vcc, 3, v8
; GCN-NEXT:    v_add_i32_e32 v7, vcc, 3, v7
; GCN-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; GCN-NEXT:    v_add_i32_e32 v5, vcc, 3, v5
; GCN-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; GCN-NEXT:    v_add_i32_e32 v3, vcc, 3, v3
; GCN-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; GCN-NEXT:    v_add_i32_e32 v1, vcc, 3, v1
; GCN-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; GCN-NEXT:  .LBB0_2: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v16i32_to_v16f32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB0_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v15, vcc, 3, v15
; VI-NEXT:    v_add_u32_e32 v14, vcc, 3, v14
; VI-NEXT:    v_add_u32_e32 v13, vcc, 3, v13
; VI-NEXT:    v_add_u32_e32 v12, vcc, 3, v12
; VI-NEXT:    v_add_u32_e32 v11, vcc, 3, v11
; VI-NEXT:    v_add_u32_e32 v10, vcc, 3, v10
; VI-NEXT:    v_add_u32_e32 v9, vcc, 3, v9
; VI-NEXT:    v_add_u32_e32 v8, vcc, 3, v8
; VI-NEXT:    v_add_u32_e32 v7, vcc, 3, v7
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_add_u32_e32 v5, vcc, 3, v5
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_add_u32_e32 v3, vcc, 3, v3
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_add_u32_e32 v1, vcc, 3, v1
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:  .LBB0_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v16i32_to_v16f32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB0_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_u32_e32 v15, 3, v15
; GFX9-NEXT:    v_add_u32_e32 v14, 3, v14
; GFX9-NEXT:    v_add_u32_e32 v13, 3, v13
; GFX9-NEXT:    v_add_u32_e32 v12, 3, v12
; GFX9-NEXT:    v_add_u32_e32 v11, 3, v11
; GFX9-NEXT:    v_add_u32_e32 v10, 3, v10
; GFX9-NEXT:    v_add_u32_e32 v9, 3, v9
; GFX9-NEXT:    v_add_u32_e32 v8, 3, v8
; GFX9-NEXT:    v_add_u32_e32 v7, 3, v7
; GFX9-NEXT:    v_add_u32_e32 v6, 3, v6
; GFX9-NEXT:    v_add_u32_e32 v5, 3, v5
; GFX9-NEXT:    v_add_u32_e32 v4, 3, v4
; GFX9-NEXT:    v_add_u32_e32 v3, 3, v3
; GFX9-NEXT:    v_add_u32_e32 v2, 3, v2
; GFX9-NEXT:    v_add_u32_e32 v1, 3, v1
; GFX9-NEXT:    v_add_u32_e32 v0, 3, v0
; GFX9-NEXT:  .LBB0_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v16i32_to_v16f32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB0_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_nc_u32_e32 v15, 3, v15
; GFX11-NEXT:    v_add_nc_u32_e32 v14, 3, v14
; GFX11-NEXT:    v_add_nc_u32_e32 v13, 3, v13
; GFX11-NEXT:    v_add_nc_u32_e32 v12, 3, v12
; GFX11-NEXT:    v_add_nc_u32_e32 v11, 3, v11
; GFX11-NEXT:    v_add_nc_u32_e32 v10, 3, v10
; GFX11-NEXT:    v_add_nc_u32_e32 v9, 3, v9
; GFX11-NEXT:    v_add_nc_u32_e32 v8, 3, v8
; GFX11-NEXT:    v_add_nc_u32_e32 v7, 3, v7
; GFX11-NEXT:    v_add_nc_u32_e32 v6, 3, v6
; GFX11-NEXT:    v_add_nc_u32_e32 v5, 3, v5
; GFX11-NEXT:    v_add_nc_u32_e32 v4, 3, v4
; GFX11-NEXT:    v_add_nc_u32_e32 v3, 3, v3
; GFX11-NEXT:    v_add_nc_u32_e32 v2, 3, v2
; GFX11-NEXT:    v_add_nc_u32_e32 v1, 3, v1
; GFX11-NEXT:    v_add_nc_u32_e32 v0, 3, v0
; GFX11-NEXT:  .LBB0_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <16 x i32> %a, splat (i32 3)
  %a2 = bitcast <16 x i32> %a1 to <16 x float>
  br label %end

cmp.false:
  %a3 = bitcast <16 x i32> %a to <16 x float>
  br label %end

end:
  %phi = phi <16 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x float> %phi
}

define <16 x i32> @v_bitcast_v16f32_to_v16i32(<16 x float> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v16f32_to_v16i32:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB1_2
; GCN-NEXT:  ; %bb.1: ; %cmp.true
; GCN-NEXT:    v_add_f32_e32 v15, 1.0, v15
; GCN-NEXT:    v_add_f32_e32 v14, 1.0, v14
; GCN-NEXT:    v_add_f32_e32 v13, 1.0, v13
; GCN-NEXT:    v_add_f32_e32 v12, 1.0, v12
; GCN-NEXT:    v_add_f32_e32 v11, 1.0, v11
; GCN-NEXT:    v_add_f32_e32 v10, 1.0, v10
; GCN-NEXT:    v_add_f32_e32 v9, 1.0, v9
; GCN-NEXT:    v_add_f32_e32 v8, 1.0, v8
; GCN-NEXT:    v_add_f32_e32 v7, 1.0, v7
; GCN-NEXT:    v_add_f32_e32 v6, 1.0, v6
; GCN-NEXT:    v_add_f32_e32 v5, 1.0, v5
; GCN-NEXT:    v_add_f32_e32 v4, 1.0, v4
; GCN-NEXT:    v_add_f32_e32 v3, 1.0, v3
; GCN-NEXT:    v_add_f32_e32 v2, 1.0, v2
; GCN-NEXT:    v_add_f32_e32 v1, 1.0, v1
; GCN-NEXT:    v_add_f32_e32 v0, 1.0, v0
; GCN-NEXT:  .LBB1_2: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v16f32_to_v16i32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB1_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f32_e32 v15, 1.0, v15
; VI-NEXT:    v_add_f32_e32 v14, 1.0, v14
; VI-NEXT:    v_add_f32_e32 v13, 1.0, v13
; VI-NEXT:    v_add_f32_e32 v12, 1.0, v12
; VI-NEXT:    v_add_f32_e32 v11, 1.0, v11
; VI-NEXT:    v_add_f32_e32 v10, 1.0, v10
; VI-NEXT:    v_add_f32_e32 v9, 1.0, v9
; VI-NEXT:    v_add_f32_e32 v8, 1.0, v8
; VI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; VI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; VI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; VI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; VI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; VI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; VI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; VI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; VI-NEXT:  .LBB1_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v16f32_to_v16i32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB1_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e32 v15, 1.0, v15
; GFX9-NEXT:    v_add_f32_e32 v14, 1.0, v14
; GFX9-NEXT:    v_add_f32_e32 v13, 1.0, v13
; GFX9-NEXT:    v_add_f32_e32 v12, 1.0, v12
; GFX9-NEXT:    v_add_f32_e32 v11, 1.0, v11
; GFX9-NEXT:    v_add_f32_e32 v10, 1.0, v10
; GFX9-NEXT:    v_add_f32_e32 v9, 1.0, v9
; GFX9-NEXT:    v_add_f32_e32 v8, 1.0, v8
; GFX9-NEXT:    v_add_f32_e32 v7, 1.0, v7
; GFX9-NEXT:    v_add_f32_e32 v6, 1.0, v6
; GFX9-NEXT:    v_add_f32_e32 v5, 1.0, v5
; GFX9-NEXT:    v_add_f32_e32 v4, 1.0, v4
; GFX9-NEXT:    v_add_f32_e32 v3, 1.0, v3
; GFX9-NEXT:    v_add_f32_e32 v2, 1.0, v2
; GFX9-NEXT:    v_add_f32_e32 v1, 1.0, v1
; GFX9-NEXT:    v_add_f32_e32 v0, 1.0, v0
; GFX9-NEXT:  .LBB1_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v16f32_to_v16i32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB1_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_dual_add_f32 v15, 1.0, v15 :: v_dual_add_f32 v14, 1.0, v14
; GFX11-NEXT:    v_dual_add_f32 v13, 1.0, v13 :: v_dual_add_f32 v12, 1.0, v12
; GFX11-NEXT:    v_dual_add_f32 v11, 1.0, v11 :: v_dual_add_f32 v10, 1.0, v10
; GFX11-NEXT:    v_dual_add_f32 v9, 1.0, v9 :: v_dual_add_f32 v8, 1.0, v8
; GFX11-NEXT:    v_dual_add_f32 v7, 1.0, v7 :: v_dual_add_f32 v6, 1.0, v6
; GFX11-NEXT:    v_dual_add_f32 v5, 1.0, v5 :: v_dual_add_f32 v4, 1.0, v4
; GFX11-NEXT:    v_dual_add_f32 v3, 1.0, v3 :: v_dual_add_f32 v2, 1.0, v2
; GFX11-NEXT:    v_dual_add_f32 v1, 1.0, v1 :: v_dual_add_f32 v0, 1.0, v0
; GFX11-NEXT:  .LBB1_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <16 x float> %a1 to <16 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <16 x float> %a to <16 x i32>
  br label %end

end:
  %phi = phi <16 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x i32> %phi
}

define <8 x i64> @v_bitcast_v16i32_to_v8i64(<16 x i32> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v16i32_to_v8i64:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB2_2
; GCN-NEXT:  ; %bb.1: ; %cmp.true
; GCN-NEXT:    v_add_i32_e32 v15, vcc, 3, v15
; GCN-NEXT:    v_add_i32_e32 v14, vcc, 3, v14
; GCN-NEXT:    v_add_i32_e32 v13, vcc, 3, v13
; GCN-NEXT:    v_add_i32_e32 v12, vcc, 3, v12
; GCN-NEXT:    v_add_i32_e32 v11, vcc, 3, v11
; GCN-NEXT:    v_add_i32_e32 v10, vcc, 3, v10
; GCN-NEXT:    v_add_i32_e32 v9, vcc, 3, v9
; GCN-NEXT:    v_add_i32_e32 v8, vcc, 3, v8
; GCN-NEXT:    v_add_i32_e32 v7, vcc, 3, v7
; GCN-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; GCN-NEXT:    v_add_i32_e32 v5, vcc, 3, v5
; GCN-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; GCN-NEXT:    v_add_i32_e32 v3, vcc, 3, v3
; GCN-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; GCN-NEXT:    v_add_i32_e32 v1, vcc, 3, v1
; GCN-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; GCN-NEXT:  .LBB2_2: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v16i32_to_v8i64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB2_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v15, vcc, 3, v15
; VI-NEXT:    v_add_u32_e32 v14, vcc, 3, v14
; VI-NEXT:    v_add_u32_e32 v13, vcc, 3, v13
; VI-NEXT:    v_add_u32_e32 v12, vcc, 3, v12
; VI-NEXT:    v_add_u32_e32 v11, vcc, 3, v11
; VI-NEXT:    v_add_u32_e32 v10, vcc, 3, v10
; VI-NEXT:    v_add_u32_e32 v9, vcc, 3, v9
; VI-NEXT:    v_add_u32_e32 v8, vcc, 3, v8
; VI-NEXT:    v_add_u32_e32 v7, vcc, 3, v7
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_add_u32_e32 v5, vcc, 3, v5
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_add_u32_e32 v3, vcc, 3, v3
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_add_u32_e32 v1, vcc, 3, v1
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:  .LBB2_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v16i32_to_v8i64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB2_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_u32_e32 v15, 3, v15
; GFX9-NEXT:    v_add_u32_e32 v14, 3, v14
; GFX9-NEXT:    v_add_u32_e32 v13, 3, v13
; GFX9-NEXT:    v_add_u32_e32 v12, 3, v12
; GFX9-NEXT:    v_add_u32_e32 v11, 3, v11
; GFX9-NEXT:    v_add_u32_e32 v10, 3, v10
; GFX9-NEXT:    v_add_u32_e32 v9, 3, v9
; GFX9-NEXT:    v_add_u32_e32 v8, 3, v8
; GFX9-NEXT:    v_add_u32_e32 v7, 3, v7
; GFX9-NEXT:    v_add_u32_e32 v6, 3, v6
; GFX9-NEXT:    v_add_u32_e32 v5, 3, v5
; GFX9-NEXT:    v_add_u32_e32 v4, 3, v4
; GFX9-NEXT:    v_add_u32_e32 v3, 3, v3
; GFX9-NEXT:    v_add_u32_e32 v2, 3, v2
; GFX9-NEXT:    v_add_u32_e32 v1, 3, v1
; GFX9-NEXT:    v_add_u32_e32 v0, 3, v0
; GFX9-NEXT:  .LBB2_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v16i32_to_v8i64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB2_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_nc_u32_e32 v15, 3, v15
; GFX11-NEXT:    v_add_nc_u32_e32 v14, 3, v14
; GFX11-NEXT:    v_add_nc_u32_e32 v13, 3, v13
; GFX11-NEXT:    v_add_nc_u32_e32 v12, 3, v12
; GFX11-NEXT:    v_add_nc_u32_e32 v11, 3, v11
; GFX11-NEXT:    v_add_nc_u32_e32 v10, 3, v10
; GFX11-NEXT:    v_add_nc_u32_e32 v9, 3, v9
; GFX11-NEXT:    v_add_nc_u32_e32 v8, 3, v8
; GFX11-NEXT:    v_add_nc_u32_e32 v7, 3, v7
; GFX11-NEXT:    v_add_nc_u32_e32 v6, 3, v6
; GFX11-NEXT:    v_add_nc_u32_e32 v5, 3, v5
; GFX11-NEXT:    v_add_nc_u32_e32 v4, 3, v4
; GFX11-NEXT:    v_add_nc_u32_e32 v3, 3, v3
; GFX11-NEXT:    v_add_nc_u32_e32 v2, 3, v2
; GFX11-NEXT:    v_add_nc_u32_e32 v1, 3, v1
; GFX11-NEXT:    v_add_nc_u32_e32 v0, 3, v0
; GFX11-NEXT:  .LBB2_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <16 x i32> %a, splat (i32 3)
  %a2 = bitcast <16 x i32> %a1 to <8 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <16 x i32> %a to <8 x i64>
  br label %end

end:
  %phi = phi <8 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x i64> %phi
}

define <16 x i32> @v_bitcast_v8i64_to_v16i32(<8 x i64> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v8i64_to_v16i32:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB3_2
; GCN-NEXT:  ; %bb.1: ; %cmp.true
; GCN-NEXT:    v_add_i32_e32 v14, vcc, 3, v14
; GCN-NEXT:    v_addc_u32_e32 v15, vcc, 0, v15, vcc
; GCN-NEXT:    v_add_i32_e32 v12, vcc, 3, v12
; GCN-NEXT:    v_addc_u32_e32 v13, vcc, 0, v13, vcc
; GCN-NEXT:    v_add_i32_e32 v10, vcc, 3, v10
; GCN-NEXT:    v_addc_u32_e32 v11, vcc, 0, v11, vcc
; GCN-NEXT:    v_add_i32_e32 v8, vcc, 3, v8
; GCN-NEXT:    v_addc_u32_e32 v9, vcc, 0, v9, vcc
; GCN-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; GCN-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; GCN-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; GCN-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; GCN-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; GCN-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; GCN-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; GCN-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; GCN-NEXT:  .LBB3_2: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v8i64_to_v16i32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB3_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v14, vcc, 3, v14
; VI-NEXT:    v_addc_u32_e32 v15, vcc, 0, v15, vcc
; VI-NEXT:    v_add_u32_e32 v12, vcc, 3, v12
; VI-NEXT:    v_addc_u32_e32 v13, vcc, 0, v13, vcc
; VI-NEXT:    v_add_u32_e32 v10, vcc, 3, v10
; VI-NEXT:    v_addc_u32_e32 v11, vcc, 0, v11, vcc
; VI-NEXT:    v_add_u32_e32 v8, vcc, 3, v8
; VI-NEXT:    v_addc_u32_e32 v9, vcc, 0, v9, vcc
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-NEXT:  .LBB3_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v8i64_to_v16i32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB3_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_co_u32_e32 v14, vcc, 3, v14
; GFX9-NEXT:    v_addc_co_u32_e32 v15, vcc, 0, v15, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v12, vcc, 3, v12
; GFX9-NEXT:    v_addc_co_u32_e32 v13, vcc, 0, v13, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v10, vcc, 3, v10
; GFX9-NEXT:    v_addc_co_u32_e32 v11, vcc, 0, v11, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v8, vcc, 3, v8
; GFX9-NEXT:    v_addc_co_u32_e32 v9, vcc, 0, v9, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v6, vcc, 3, v6
; GFX9-NEXT:    v_addc_co_u32_e32 v7, vcc, 0, v7, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v4, vcc, 3, v4
; GFX9-NEXT:    v_addc_co_u32_e32 v5, vcc, 0, v5, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v2, vcc, 3, v2
; GFX9-NEXT:    v_addc_co_u32_e32 v3, vcc, 0, v3, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v0, vcc, 3, v0
; GFX9-NEXT:    v_addc_co_u32_e32 v1, vcc, 0, v1, vcc
; GFX9-NEXT:  .LBB3_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v8i64_to_v16i32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB3_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_co_u32 v14, vcc_lo, v14, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v15, vcc_lo, 0, v15, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v12, vcc_lo, v12, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v13, vcc_lo, 0, v13, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v10, vcc_lo, v10, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v11, vcc_lo, 0, v11, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v8, vcc_lo, v8, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v9, vcc_lo, 0, v9, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v6, vcc_lo, v6, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v7, vcc_lo, 0, v7, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v4, vcc_lo, v4, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v5, vcc_lo, 0, v5, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v2, vcc_lo, v2, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v3, vcc_lo, 0, v3, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v0, vcc_lo, v0, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, 0, v1, vcc_lo
; GFX11-NEXT:  .LBB3_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <8 x i64> %a, splat (i64 3)
  %a2 = bitcast <8 x i64> %a1 to <16 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <8 x i64> %a to <16 x i32>
  br label %end

end:
  %phi = phi <16 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x i32> %phi
}

define <8 x double> @v_bitcast_v16i32_to_v8f64(<16 x i32> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v16i32_to_v8f64:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB4_2
; GCN-NEXT:  ; %bb.1: ; %cmp.true
; GCN-NEXT:    v_add_i32_e32 v15, vcc, 3, v15
; GCN-NEXT:    v_add_i32_e32 v14, vcc, 3, v14
; GCN-NEXT:    v_add_i32_e32 v13, vcc, 3, v13
; GCN-NEXT:    v_add_i32_e32 v12, vcc, 3, v12
; GCN-NEXT:    v_add_i32_e32 v11, vcc, 3, v11
; GCN-NEXT:    v_add_i32_e32 v10, vcc, 3, v10
; GCN-NEXT:    v_add_i32_e32 v9, vcc, 3, v9
; GCN-NEXT:    v_add_i32_e32 v8, vcc, 3, v8
; GCN-NEXT:    v_add_i32_e32 v7, vcc, 3, v7
; GCN-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; GCN-NEXT:    v_add_i32_e32 v5, vcc, 3, v5
; GCN-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; GCN-NEXT:    v_add_i32_e32 v3, vcc, 3, v3
; GCN-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; GCN-NEXT:    v_add_i32_e32 v1, vcc, 3, v1
; GCN-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; GCN-NEXT:  .LBB4_2: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v16i32_to_v8f64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB4_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v15, vcc, 3, v15
; VI-NEXT:    v_add_u32_e32 v14, vcc, 3, v14
; VI-NEXT:    v_add_u32_e32 v13, vcc, 3, v13
; VI-NEXT:    v_add_u32_e32 v12, vcc, 3, v12
; VI-NEXT:    v_add_u32_e32 v11, vcc, 3, v11
; VI-NEXT:    v_add_u32_e32 v10, vcc, 3, v10
; VI-NEXT:    v_add_u32_e32 v9, vcc, 3, v9
; VI-NEXT:    v_add_u32_e32 v8, vcc, 3, v8
; VI-NEXT:    v_add_u32_e32 v7, vcc, 3, v7
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_add_u32_e32 v5, vcc, 3, v5
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_add_u32_e32 v3, vcc, 3, v3
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_add_u32_e32 v1, vcc, 3, v1
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:  .LBB4_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v16i32_to_v8f64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB4_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_u32_e32 v15, 3, v15
; GFX9-NEXT:    v_add_u32_e32 v14, 3, v14
; GFX9-NEXT:    v_add_u32_e32 v13, 3, v13
; GFX9-NEXT:    v_add_u32_e32 v12, 3, v12
; GFX9-NEXT:    v_add_u32_e32 v11, 3, v11
; GFX9-NEXT:    v_add_u32_e32 v10, 3, v10
; GFX9-NEXT:    v_add_u32_e32 v9, 3, v9
; GFX9-NEXT:    v_add_u32_e32 v8, 3, v8
; GFX9-NEXT:    v_add_u32_e32 v7, 3, v7
; GFX9-NEXT:    v_add_u32_e32 v6, 3, v6
; GFX9-NEXT:    v_add_u32_e32 v5, 3, v5
; GFX9-NEXT:    v_add_u32_e32 v4, 3, v4
; GFX9-NEXT:    v_add_u32_e32 v3, 3, v3
; GFX9-NEXT:    v_add_u32_e32 v2, 3, v2
; GFX9-NEXT:    v_add_u32_e32 v1, 3, v1
; GFX9-NEXT:    v_add_u32_e32 v0, 3, v0
; GFX9-NEXT:  .LBB4_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v16i32_to_v8f64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB4_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_nc_u32_e32 v15, 3, v15
; GFX11-NEXT:    v_add_nc_u32_e32 v14, 3, v14
; GFX11-NEXT:    v_add_nc_u32_e32 v13, 3, v13
; GFX11-NEXT:    v_add_nc_u32_e32 v12, 3, v12
; GFX11-NEXT:    v_add_nc_u32_e32 v11, 3, v11
; GFX11-NEXT:    v_add_nc_u32_e32 v10, 3, v10
; GFX11-NEXT:    v_add_nc_u32_e32 v9, 3, v9
; GFX11-NEXT:    v_add_nc_u32_e32 v8, 3, v8
; GFX11-NEXT:    v_add_nc_u32_e32 v7, 3, v7
; GFX11-NEXT:    v_add_nc_u32_e32 v6, 3, v6
; GFX11-NEXT:    v_add_nc_u32_e32 v5, 3, v5
; GFX11-NEXT:    v_add_nc_u32_e32 v4, 3, v4
; GFX11-NEXT:    v_add_nc_u32_e32 v3, 3, v3
; GFX11-NEXT:    v_add_nc_u32_e32 v2, 3, v2
; GFX11-NEXT:    v_add_nc_u32_e32 v1, 3, v1
; GFX11-NEXT:    v_add_nc_u32_e32 v0, 3, v0
; GFX11-NEXT:  .LBB4_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <16 x i32> %a, splat (i32 3)
  %a2 = bitcast <16 x i32> %a1 to <8 x double>
  br label %end

cmp.false:
  %a3 = bitcast <16 x i32> %a to <8 x double>
  br label %end

end:
  %phi = phi <8 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x double> %phi
}

define <16 x i32> @v_bitcast_v8f64_to_v16i32(<8 x double> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v8f64_to_v16i32:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB5_2
; GCN-NEXT:  ; %bb.1: ; %cmp.true
; GCN-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GCN-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GCN-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GCN-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GCN-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GCN-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GCN-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GCN-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GCN-NEXT:  .LBB5_2: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v8f64_to_v16i32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB5_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; VI-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; VI-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; VI-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; VI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; VI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; VI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; VI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; VI-NEXT:  .LBB5_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v8f64_to_v16i32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB5_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GFX9-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GFX9-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GFX9-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GFX9-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX9-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX9-NEXT:  .LBB5_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v8f64_to_v16i32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB5_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GFX11-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GFX11-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GFX11-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GFX11-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX11-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX11-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX11-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX11-NEXT:  .LBB5_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <8 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <8 x double> %a1 to <16 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <8 x double> %a to <16 x i32>
  br label %end

end:
  %phi = phi <16 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x i32> %phi
}

define <32 x i16> @v_bitcast_v16i32_to_v32i16(<16 x i32> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v16i32_to_v32i16:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_mov_b32_e32 v30, v15
; GCN-NEXT:    v_mov_b32_e32 v28, v14
; GCN-NEXT:    v_mov_b32_e32 v26, v13
; GCN-NEXT:    v_mov_b32_e32 v24, v12
; GCN-NEXT:    v_mov_b32_e32 v22, v11
; GCN-NEXT:    v_mov_b32_e32 v20, v10
; GCN-NEXT:    v_mov_b32_e32 v18, v9
; GCN-NEXT:    v_mov_b32_e32 v32, v8
; GCN-NEXT:    v_mov_b32_e32 v14, v7
; GCN-NEXT:    v_mov_b32_e32 v12, v6
; GCN-NEXT:    v_mov_b32_e32 v10, v5
; GCN-NEXT:    v_mov_b32_e32 v8, v4
; GCN-NEXT:    v_mov_b32_e32 v6, v3
; GCN-NEXT:    v_mov_b32_e32 v4, v2
; GCN-NEXT:    v_mov_b32_e32 v2, v1
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GCN-NEXT:    ; implicit-def: $vgpr1
; GCN-NEXT:    ; implicit-def: $vgpr3
; GCN-NEXT:    ; implicit-def: $vgpr5
; GCN-NEXT:    ; implicit-def: $vgpr7
; GCN-NEXT:    ; implicit-def: $vgpr9
; GCN-NEXT:    ; implicit-def: $vgpr11
; GCN-NEXT:    ; implicit-def: $vgpr13
; GCN-NEXT:    ; implicit-def: $vgpr15
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr27
; GCN-NEXT:    ; implicit-def: $vgpr29
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB6_2
; GCN-NEXT:  ; %bb.1: ; %cmp.false
; GCN-NEXT:    v_alignbit_b32 v29, v30, v28, 16
; GCN-NEXT:    v_alignbit_b32 v25, v26, v24, 16
; GCN-NEXT:    v_alignbit_b32 v21, v22, v20, 16
; GCN-NEXT:    v_alignbit_b32 v17, v18, v32, 16
; GCN-NEXT:    v_alignbit_b32 v13, v14, v12, 16
; GCN-NEXT:    v_alignbit_b32 v9, v10, v8, 16
; GCN-NEXT:    v_alignbit_b32 v5, v6, v4, 16
; GCN-NEXT:    v_alignbit_b32 v1, v2, v0, 16
; GCN-NEXT:    v_lshrrev_b32_e32 v31, 16, v30
; GCN-NEXT:    v_lshrrev_b32_e32 v27, 16, v26
; GCN-NEXT:    v_lshrrev_b32_e32 v23, 16, v22
; GCN-NEXT:    v_lshrrev_b32_e32 v19, 16, v18
; GCN-NEXT:    v_lshrrev_b32_e32 v15, 16, v14
; GCN-NEXT:    v_lshrrev_b32_e32 v11, 16, v10
; GCN-NEXT:    v_lshrrev_b32_e32 v7, 16, v6
; GCN-NEXT:    v_lshrrev_b32_e32 v3, 16, v2
; GCN-NEXT:  .LBB6_2: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB6_4
; GCN-NEXT:  ; %bb.3: ; %cmp.true
; GCN-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; GCN-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; GCN-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; GCN-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; GCN-NEXT:    v_add_i32_e32 v10, vcc, 3, v10
; GCN-NEXT:    v_add_i32_e32 v8, vcc, 3, v8
; GCN-NEXT:    v_add_i32_e32 v14, vcc, 3, v14
; GCN-NEXT:    v_add_i32_e32 v12, vcc, 3, v12
; GCN-NEXT:    v_add_i32_e32 v18, vcc, 3, v18
; GCN-NEXT:    v_add_i32_e32 v32, vcc, 3, v32
; GCN-NEXT:    v_add_i32_e32 v22, vcc, 3, v22
; GCN-NEXT:    v_add_i32_e32 v20, vcc, 3, v20
; GCN-NEXT:    v_add_i32_e32 v26, vcc, 3, v26
; GCN-NEXT:    v_add_i32_e32 v24, vcc, 3, v24
; GCN-NEXT:    v_add_i32_e32 v30, vcc, 3, v30
; GCN-NEXT:    v_add_i32_e32 v28, vcc, 3, v28
; GCN-NEXT:    v_alignbit_b32 v29, v30, v28, 16
; GCN-NEXT:    v_alignbit_b32 v25, v26, v24, 16
; GCN-NEXT:    v_alignbit_b32 v21, v22, v20, 16
; GCN-NEXT:    v_alignbit_b32 v17, v18, v32, 16
; GCN-NEXT:    v_alignbit_b32 v13, v14, v12, 16
; GCN-NEXT:    v_alignbit_b32 v9, v10, v8, 16
; GCN-NEXT:    v_alignbit_b32 v5, v6, v4, 16
; GCN-NEXT:    v_alignbit_b32 v1, v2, v0, 16
; GCN-NEXT:    v_lshrrev_b32_e32 v31, 16, v30
; GCN-NEXT:    v_lshrrev_b32_e32 v27, 16, v26
; GCN-NEXT:    v_lshrrev_b32_e32 v23, 16, v22
; GCN-NEXT:    v_lshrrev_b32_e32 v19, 16, v18
; GCN-NEXT:    v_lshrrev_b32_e32 v15, 16, v14
; GCN-NEXT:    v_lshrrev_b32_e32 v11, 16, v10
; GCN-NEXT:    v_lshrrev_b32_e32 v7, 16, v6
; GCN-NEXT:    v_lshrrev_b32_e32 v3, 16, v2
; GCN-NEXT:  .LBB6_4: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    v_mov_b32_e32 v16, v32
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v16i32_to_v32i16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB6_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v15, vcc, 3, v15
; VI-NEXT:    v_add_u32_e32 v14, vcc, 3, v14
; VI-NEXT:    v_add_u32_e32 v13, vcc, 3, v13
; VI-NEXT:    v_add_u32_e32 v12, vcc, 3, v12
; VI-NEXT:    v_add_u32_e32 v11, vcc, 3, v11
; VI-NEXT:    v_add_u32_e32 v10, vcc, 3, v10
; VI-NEXT:    v_add_u32_e32 v9, vcc, 3, v9
; VI-NEXT:    v_add_u32_e32 v8, vcc, 3, v8
; VI-NEXT:    v_add_u32_e32 v7, vcc, 3, v7
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_add_u32_e32 v5, vcc, 3, v5
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_add_u32_e32 v3, vcc, 3, v3
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_add_u32_e32 v1, vcc, 3, v1
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:  .LBB6_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v16i32_to_v32i16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB6_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_u32_e32 v15, 3, v15
; GFX9-NEXT:    v_add_u32_e32 v14, 3, v14
; GFX9-NEXT:    v_add_u32_e32 v13, 3, v13
; GFX9-NEXT:    v_add_u32_e32 v12, 3, v12
; GFX9-NEXT:    v_add_u32_e32 v11, 3, v11
; GFX9-NEXT:    v_add_u32_e32 v10, 3, v10
; GFX9-NEXT:    v_add_u32_e32 v9, 3, v9
; GFX9-NEXT:    v_add_u32_e32 v8, 3, v8
; GFX9-NEXT:    v_add_u32_e32 v7, 3, v7
; GFX9-NEXT:    v_add_u32_e32 v6, 3, v6
; GFX9-NEXT:    v_add_u32_e32 v5, 3, v5
; GFX9-NEXT:    v_add_u32_e32 v4, 3, v4
; GFX9-NEXT:    v_add_u32_e32 v3, 3, v3
; GFX9-NEXT:    v_add_u32_e32 v2, 3, v2
; GFX9-NEXT:    v_add_u32_e32 v1, 3, v1
; GFX9-NEXT:    v_add_u32_e32 v0, 3, v0
; GFX9-NEXT:  .LBB6_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v16i32_to_v32i16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB6_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_nc_u32_e32 v15, 3, v15
; GFX11-NEXT:    v_add_nc_u32_e32 v14, 3, v14
; GFX11-NEXT:    v_add_nc_u32_e32 v13, 3, v13
; GFX11-NEXT:    v_add_nc_u32_e32 v12, 3, v12
; GFX11-NEXT:    v_add_nc_u32_e32 v11, 3, v11
; GFX11-NEXT:    v_add_nc_u32_e32 v10, 3, v10
; GFX11-NEXT:    v_add_nc_u32_e32 v9, 3, v9
; GFX11-NEXT:    v_add_nc_u32_e32 v8, 3, v8
; GFX11-NEXT:    v_add_nc_u32_e32 v7, 3, v7
; GFX11-NEXT:    v_add_nc_u32_e32 v6, 3, v6
; GFX11-NEXT:    v_add_nc_u32_e32 v5, 3, v5
; GFX11-NEXT:    v_add_nc_u32_e32 v4, 3, v4
; GFX11-NEXT:    v_add_nc_u32_e32 v3, 3, v3
; GFX11-NEXT:    v_add_nc_u32_e32 v2, 3, v2
; GFX11-NEXT:    v_add_nc_u32_e32 v1, 3, v1
; GFX11-NEXT:    v_add_nc_u32_e32 v0, 3, v0
; GFX11-NEXT:  .LBB6_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <16 x i32> %a, splat (i32 3)
  %a2 = bitcast <16 x i32> %a1 to <32 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <16 x i32> %a to <32 x i16>
  br label %end

end:
  %phi = phi <32 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x i16> %phi
}

define <16 x i32> @v_bitcast_v32i16_to_v16i32(<32 x i16> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v32i16_to_v16i32:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_mov_b32_e32 v38, v14
; GCN-NEXT:    v_mov_b32_e32 v37, v12
; GCN-NEXT:    v_mov_b32_e32 v36, v10
; GCN-NEXT:    v_mov_b32_e32 v35, v8
; GCN-NEXT:    v_mov_b32_e32 v34, v6
; GCN-NEXT:    v_mov_b32_e32 v33, v4
; GCN-NEXT:    v_mov_b32_e32 v32, v2
; GCN-NEXT:    v_mov_b32_e32 v31, v0
; GCN-NEXT:    buffer_load_dword v0, off, s[0:3], s32
; GCN-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:4
; GCN-NEXT:    v_lshlrev_b32_e32 v54, 16, v1
; GCN-NEXT:    v_lshlrev_b32_e32 v55, 16, v3
; GCN-NEXT:    v_lshlrev_b32_e32 v39, 16, v5
; GCN-NEXT:    v_lshlrev_b32_e32 v48, 16, v7
; GCN-NEXT:    v_lshlrev_b32_e32 v49, 16, v9
; GCN-NEXT:    v_lshlrev_b32_e32 v50, 16, v11
; GCN-NEXT:    v_lshlrev_b32_e32 v51, 16, v13
; GCN-NEXT:    v_lshlrev_b32_e32 v52, 16, v15
; GCN-NEXT:    v_lshlrev_b32_e32 v17, 16, v17
; GCN-NEXT:    v_lshlrev_b32_e32 v19, 16, v19
; GCN-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; GCN-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; GCN-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; GCN-NEXT:    v_lshlrev_b32_e32 v27, 16, v27
; GCN-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v2
; GCN-NEXT:    v_lshlrev_b32_e32 v53, 16, v0
; GCN-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execnz .LBB7_3
; GCN-NEXT:  ; %bb.1: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execnz .LBB7_4
; GCN-NEXT:  .LBB7_2: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
; GCN-NEXT:  .LBB7_3: ; %cmp.false
; GCN-NEXT:    v_and_b32_e32 v0, 0xffff, v31
; GCN-NEXT:    v_and_b32_e32 v1, 0xffff, v32
; GCN-NEXT:    v_or_b32_e32 v0, v0, v54
; GCN-NEXT:    v_or_b32_e32 v1, v1, v55
; GCN-NEXT:    v_and_b32_e32 v2, 0xffff, v33
; GCN-NEXT:    v_and_b32_e32 v3, 0xffff, v34
; GCN-NEXT:    v_and_b32_e32 v4, 0xffff, v35
; GCN-NEXT:    v_and_b32_e32 v5, 0xffff, v36
; GCN-NEXT:    v_and_b32_e32 v6, 0xffff, v37
; GCN-NEXT:    v_and_b32_e32 v7, 0xffff, v38
; GCN-NEXT:    v_and_b32_e32 v8, 0xffff, v16
; GCN-NEXT:    v_and_b32_e32 v9, 0xffff, v18
; GCN-NEXT:    v_and_b32_e32 v10, 0xffff, v20
; GCN-NEXT:    v_and_b32_e32 v11, 0xffff, v22
; GCN-NEXT:    v_and_b32_e32 v12, 0xffff, v24
; GCN-NEXT:    v_and_b32_e32 v13, 0xffff, v26
; GCN-NEXT:    v_and_b32_e32 v14, 0xffff, v28
; GCN-NEXT:    v_and_b32_e32 v15, 0xffff, v30
; GCN-NEXT:    v_or_b32_e32 v2, v2, v39
; GCN-NEXT:    v_or_b32_e32 v3, v3, v48
; GCN-NEXT:    v_or_b32_e32 v4, v4, v49
; GCN-NEXT:    v_or_b32_e32 v5, v5, v50
; GCN-NEXT:    v_or_b32_e32 v6, v6, v51
; GCN-NEXT:    v_or_b32_e32 v7, v7, v52
; GCN-NEXT:    v_or_b32_e32 v8, v8, v17
; GCN-NEXT:    v_or_b32_e32 v9, v9, v19
; GCN-NEXT:    v_or_b32_e32 v10, v10, v21
; GCN-NEXT:    v_or_b32_e32 v11, v11, v23
; GCN-NEXT:    v_or_b32_e32 v12, v12, v25
; GCN-NEXT:    v_or_b32_e32 v13, v13, v27
; GCN-NEXT:    v_or_b32_e32 v14, v14, v29
; GCN-NEXT:    v_or_b32_e32 v15, v15, v53
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    ; implicit-def: $vgpr32
; GCN-NEXT:    ; implicit-def: $vgpr33
; GCN-NEXT:    ; implicit-def: $vgpr34
; GCN-NEXT:    ; implicit-def: $vgpr35
; GCN-NEXT:    ; implicit-def: $vgpr36
; GCN-NEXT:    ; implicit-def: $vgpr37
; GCN-NEXT:    ; implicit-def: $vgpr38
; GCN-NEXT:    ; implicit-def: $vgpr16
; GCN-NEXT:    ; implicit-def: $vgpr18
; GCN-NEXT:    ; implicit-def: $vgpr20
; GCN-NEXT:    ; implicit-def: $vgpr22
; GCN-NEXT:    ; implicit-def: $vgpr24
; GCN-NEXT:    ; implicit-def: $vgpr26
; GCN-NEXT:    ; implicit-def: $vgpr28
; GCN-NEXT:    ; implicit-def: $vgpr30
; GCN-NEXT:    ; implicit-def: $vgpr54
; GCN-NEXT:    ; implicit-def: $vgpr55
; GCN-NEXT:    ; implicit-def: $vgpr39
; GCN-NEXT:    ; implicit-def: $vgpr48
; GCN-NEXT:    ; implicit-def: $vgpr49
; GCN-NEXT:    ; implicit-def: $vgpr50
; GCN-NEXT:    ; implicit-def: $vgpr51
; GCN-NEXT:    ; implicit-def: $vgpr52
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr27
; GCN-NEXT:    ; implicit-def: $vgpr29
; GCN-NEXT:    ; implicit-def: $vgpr53
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB7_2
; GCN-NEXT:  .LBB7_4: ; %cmp.true
; GCN-NEXT:    v_add_i32_e32 v0, vcc, 3, v31
; GCN-NEXT:    s_mov_b32 s6, 0x30000
; GCN-NEXT:    v_add_i32_e32 v1, vcc, 3, v32
; GCN-NEXT:    v_add_i32_e32 v2, vcc, 3, v33
; GCN-NEXT:    v_add_i32_e32 v3, vcc, 3, v34
; GCN-NEXT:    v_add_i32_e32 v4, vcc, 3, v35
; GCN-NEXT:    v_add_i32_e32 v5, vcc, 3, v36
; GCN-NEXT:    v_add_i32_e32 v6, vcc, 3, v37
; GCN-NEXT:    v_add_i32_e32 v7, vcc, 3, v38
; GCN-NEXT:    v_add_i32_e32 v8, vcc, 3, v16
; GCN-NEXT:    v_add_i32_e32 v9, vcc, 3, v18
; GCN-NEXT:    v_add_i32_e32 v10, vcc, 3, v20
; GCN-NEXT:    v_add_i32_e32 v11, vcc, 3, v22
; GCN-NEXT:    v_add_i32_e32 v12, vcc, 3, v24
; GCN-NEXT:    v_add_i32_e32 v13, vcc, 3, v26
; GCN-NEXT:    v_add_i32_e32 v14, vcc, 3, v28
; GCN-NEXT:    v_add_i32_e32 v15, vcc, 3, v30
; GCN-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GCN-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; GCN-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GCN-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GCN-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GCN-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GCN-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; GCN-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; GCN-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; GCN-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; GCN-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; GCN-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; GCN-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; GCN-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; GCN-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; GCN-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; GCN-NEXT:    v_or_b32_e32 v0, v54, v0
; GCN-NEXT:    v_or_b32_e32 v1, v55, v1
; GCN-NEXT:    v_or_b32_e32 v2, v39, v2
; GCN-NEXT:    v_or_b32_e32 v3, v48, v3
; GCN-NEXT:    v_or_b32_e32 v4, v49, v4
; GCN-NEXT:    v_or_b32_e32 v5, v50, v5
; GCN-NEXT:    v_or_b32_e32 v6, v51, v6
; GCN-NEXT:    v_or_b32_e32 v7, v52, v7
; GCN-NEXT:    v_or_b32_e32 v8, v17, v8
; GCN-NEXT:    v_or_b32_e32 v9, v19, v9
; GCN-NEXT:    v_or_b32_e32 v10, v21, v10
; GCN-NEXT:    v_or_b32_e32 v11, v23, v11
; GCN-NEXT:    v_or_b32_e32 v12, v25, v12
; GCN-NEXT:    v_or_b32_e32 v13, v27, v13
; GCN-NEXT:    v_or_b32_e32 v14, v29, v14
; GCN-NEXT:    v_or_b32_e32 v15, v53, v15
; GCN-NEXT:    v_add_i32_e32 v0, vcc, 0x30000, v0
; GCN-NEXT:    v_add_i32_e32 v1, vcc, s6, v1
; GCN-NEXT:    v_add_i32_e32 v2, vcc, s6, v2
; GCN-NEXT:    v_add_i32_e32 v3, vcc, s6, v3
; GCN-NEXT:    v_add_i32_e32 v4, vcc, s6, v4
; GCN-NEXT:    v_add_i32_e32 v5, vcc, s6, v5
; GCN-NEXT:    v_add_i32_e32 v6, vcc, s6, v6
; GCN-NEXT:    v_add_i32_e32 v7, vcc, s6, v7
; GCN-NEXT:    v_add_i32_e32 v8, vcc, s6, v8
; GCN-NEXT:    v_add_i32_e32 v9, vcc, s6, v9
; GCN-NEXT:    v_add_i32_e32 v10, vcc, s6, v10
; GCN-NEXT:    v_add_i32_e32 v11, vcc, s6, v11
; GCN-NEXT:    v_add_i32_e32 v12, vcc, s6, v12
; GCN-NEXT:    v_add_i32_e32 v13, vcc, 0x30000, v13
; GCN-NEXT:    v_add_i32_e32 v14, vcc, 0x30000, v14
; GCN-NEXT:    v_add_i32_e32 v15, vcc, 0x30000, v15
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v32i16_to_v16i32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB7_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v17, 3
; VI-NEXT:    v_add_u16_e32 v16, 3, v15
; VI-NEXT:    v_add_u16_sdwa v15, v15, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v15, v16, v15
; VI-NEXT:    v_add_u16_e32 v16, 3, v14
; VI-NEXT:    v_add_u16_sdwa v14, v14, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v14, v16, v14
; VI-NEXT:    v_add_u16_e32 v16, 3, v13
; VI-NEXT:    v_add_u16_sdwa v13, v13, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v13, v16, v13
; VI-NEXT:    v_add_u16_e32 v16, 3, v12
; VI-NEXT:    v_add_u16_sdwa v12, v12, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v12, v16, v12
; VI-NEXT:    v_add_u16_e32 v16, 3, v11
; VI-NEXT:    v_add_u16_sdwa v11, v11, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v11, v16, v11
; VI-NEXT:    v_add_u16_e32 v16, 3, v10
; VI-NEXT:    v_add_u16_sdwa v10, v10, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v10, v16, v10
; VI-NEXT:    v_add_u16_e32 v16, 3, v9
; VI-NEXT:    v_add_u16_sdwa v9, v9, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v9, v16, v9
; VI-NEXT:    v_add_u16_e32 v16, 3, v8
; VI-NEXT:    v_add_u16_sdwa v8, v8, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v8, v16, v8
; VI-NEXT:    v_add_u16_e32 v16, 3, v7
; VI-NEXT:    v_add_u16_sdwa v7, v7, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v7, v16, v7
; VI-NEXT:    v_add_u16_e32 v16, 3, v6
; VI-NEXT:    v_add_u16_sdwa v6, v6, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v6, v16, v6
; VI-NEXT:    v_add_u16_e32 v16, 3, v5
; VI-NEXT:    v_add_u16_sdwa v5, v5, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v5, v16, v5
; VI-NEXT:    v_add_u16_e32 v16, 3, v4
; VI-NEXT:    v_add_u16_sdwa v4, v4, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v4, v16, v4
; VI-NEXT:    v_add_u16_e32 v16, 3, v3
; VI-NEXT:    v_add_u16_sdwa v3, v3, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v3, v16, v3
; VI-NEXT:    v_add_u16_e32 v16, 3, v2
; VI-NEXT:    v_add_u16_sdwa v2, v2, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v2, v16, v2
; VI-NEXT:    v_add_u16_e32 v16, 3, v1
; VI-NEXT:    v_add_u16_sdwa v1, v1, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v1, v16, v1
; VI-NEXT:    v_add_u16_e32 v16, 3, v0
; VI-NEXT:    v_add_u16_sdwa v0, v0, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v0, v16, v0
; VI-NEXT:  .LBB7_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v32i16_to_v16i32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB7_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_pk_add_u16 v15, v15, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v14, v14, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v13, v13, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v12, v12, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v9, v9, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v8, v8, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX9-NEXT:  .LBB7_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v32i16_to_v16i32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB7_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_pk_add_u16 v15, v15, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v14, v14, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v13, v13, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v12, v12, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v9, v9, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v8, v8, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX11-NEXT:  .LBB7_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <32 x i16> %a, splat (i16 3)
  %a2 = bitcast <32 x i16> %a1 to <16 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <32 x i16> %a to <16 x i32>
  br label %end

end:
  %phi = phi <16 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x i32> %phi
}

define <32 x half> @v_bitcast_v16i32_to_v32f16(<16 x i32> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v16i32_to_v32f16:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v46, off, s[0:3], s32 ; 4-byte Folded Spill
; GCN-NEXT:    v_mov_b32_e32 v33, v15
; GCN-NEXT:    v_mov_b32_e32 v34, v14
; GCN-NEXT:    v_mov_b32_e32 v35, v13
; GCN-NEXT:    v_mov_b32_e32 v36, v12
; GCN-NEXT:    v_mov_b32_e32 v37, v11
; GCN-NEXT:    v_mov_b32_e32 v38, v10
; GCN-NEXT:    v_mov_b32_e32 v39, v9
; GCN-NEXT:    v_mov_b32_e32 v48, v8
; GCN-NEXT:    v_mov_b32_e32 v49, v7
; GCN-NEXT:    v_mov_b32_e32 v50, v6
; GCN-NEXT:    v_mov_b32_e32 v51, v5
; GCN-NEXT:    v_mov_b32_e32 v52, v4
; GCN-NEXT:    v_mov_b32_e32 v53, v3
; GCN-NEXT:    v_mov_b32_e32 v54, v2
; GCN-NEXT:    v_mov_b32_e32 v55, v1
; GCN-NEXT:    v_mov_b32_e32 v32, v0
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GCN-NEXT:    ; implicit-def: $vgpr0
; GCN-NEXT:    ; implicit-def: $vgpr1
; GCN-NEXT:    ; implicit-def: $vgpr2
; GCN-NEXT:    ; implicit-def: $vgpr3
; GCN-NEXT:    ; implicit-def: $vgpr4
; GCN-NEXT:    ; implicit-def: $vgpr5
; GCN-NEXT:    ; implicit-def: $vgpr6
; GCN-NEXT:    ; implicit-def: $vgpr7
; GCN-NEXT:    ; implicit-def: $vgpr8
; GCN-NEXT:    ; implicit-def: $vgpr9
; GCN-NEXT:    ; implicit-def: $vgpr10
; GCN-NEXT:    ; implicit-def: $vgpr11
; GCN-NEXT:    ; implicit-def: $vgpr12
; GCN-NEXT:    ; implicit-def: $vgpr13
; GCN-NEXT:    ; implicit-def: $vgpr14
; GCN-NEXT:    ; implicit-def: $vgpr15
; GCN-NEXT:    ; implicit-def: $vgpr16
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr18
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr20
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr22
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr24
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr26
; GCN-NEXT:    ; implicit-def: $vgpr27
; GCN-NEXT:    ; implicit-def: $vgpr28
; GCN-NEXT:    ; implicit-def: $vgpr29
; GCN-NEXT:    ; implicit-def: $vgpr30
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB8_2
; GCN-NEXT:  ; %bb.1: ; %cmp.false
; GCN-NEXT:    v_lshrrev_b32_e32 v0, 16, v33
; GCN-NEXT:    v_lshrrev_b32_e32 v1, 16, v34
; GCN-NEXT:    v_lshrrev_b32_e32 v3, 16, v35
; GCN-NEXT:    v_lshrrev_b32_e32 v5, 16, v36
; GCN-NEXT:    v_lshrrev_b32_e32 v7, 16, v37
; GCN-NEXT:    v_lshrrev_b32_e32 v9, 16, v38
; GCN-NEXT:    v_lshrrev_b32_e32 v11, 16, v39
; GCN-NEXT:    v_lshrrev_b32_e32 v13, 16, v48
; GCN-NEXT:    v_lshrrev_b32_e32 v15, 16, v49
; GCN-NEXT:    s_waitcnt expcnt(6)
; GCN-NEXT:    v_lshrrev_b32_e32 v40, 16, v50
; GCN-NEXT:    s_waitcnt expcnt(5)
; GCN-NEXT:    v_lshrrev_b32_e32 v41, 16, v51
; GCN-NEXT:    s_waitcnt expcnt(4)
; GCN-NEXT:    v_lshrrev_b32_e32 v42, 16, v52
; GCN-NEXT:    s_waitcnt expcnt(3)
; GCN-NEXT:    v_lshrrev_b32_e32 v43, 16, v53
; GCN-NEXT:    s_waitcnt expcnt(2)
; GCN-NEXT:    v_lshrrev_b32_e32 v44, 16, v54
; GCN-NEXT:    s_waitcnt expcnt(1)
; GCN-NEXT:    v_lshrrev_b32_e32 v45, 16, v55
; GCN-NEXT:    s_waitcnt expcnt(0)
; GCN-NEXT:    v_lshrrev_b32_e32 v46, 16, v32
; GCN-NEXT:    v_cvt_f32_f16_e32 v30, v33
; GCN-NEXT:    v_cvt_f32_f16_e32 v28, v34
; GCN-NEXT:    v_cvt_f32_f16_e32 v26, v35
; GCN-NEXT:    v_cvt_f32_f16_e32 v24, v36
; GCN-NEXT:    v_cvt_f32_f16_e32 v22, v37
; GCN-NEXT:    v_cvt_f32_f16_e32 v20, v38
; GCN-NEXT:    v_cvt_f32_f16_e32 v18, v39
; GCN-NEXT:    v_cvt_f32_f16_e32 v16, v48
; GCN-NEXT:    v_cvt_f32_f16_e32 v14, v49
; GCN-NEXT:    v_cvt_f32_f16_e32 v12, v50
; GCN-NEXT:    v_cvt_f32_f16_e32 v10, v51
; GCN-NEXT:    v_cvt_f32_f16_e32 v8, v52
; GCN-NEXT:    v_cvt_f32_f16_e32 v6, v53
; GCN-NEXT:    v_cvt_f32_f16_e32 v4, v54
; GCN-NEXT:    v_cvt_f32_f16_e32 v2, v55
; GCN-NEXT:    v_cvt_f32_f16_e32 v31, v0
; GCN-NEXT:    v_cvt_f32_f16_e32 v29, v1
; GCN-NEXT:    v_cvt_f32_f16_e32 v27, v3
; GCN-NEXT:    v_cvt_f32_f16_e32 v25, v5
; GCN-NEXT:    v_cvt_f32_f16_e32 v23, v7
; GCN-NEXT:    v_cvt_f32_f16_e32 v21, v9
; GCN-NEXT:    v_cvt_f32_f16_e32 v19, v11
; GCN-NEXT:    v_cvt_f32_f16_e32 v17, v13
; GCN-NEXT:    v_cvt_f32_f16_e32 v15, v15
; GCN-NEXT:    v_cvt_f32_f16_e32 v13, v40
; GCN-NEXT:    v_cvt_f32_f16_e32 v11, v41
; GCN-NEXT:    v_cvt_f32_f16_e32 v9, v42
; GCN-NEXT:    v_cvt_f32_f16_e32 v7, v43
; GCN-NEXT:    v_cvt_f32_f16_e32 v5, v44
; GCN-NEXT:    v_cvt_f32_f16_e32 v3, v45
; GCN-NEXT:    v_cvt_f32_f16_e32 v1, v46
; GCN-NEXT:    v_cvt_f32_f16_e32 v0, v32
; GCN-NEXT:    ; implicit-def: $vgpr32
; GCN-NEXT:    ; implicit-def: $vgpr55
; GCN-NEXT:    ; implicit-def: $vgpr54
; GCN-NEXT:    ; implicit-def: $vgpr53
; GCN-NEXT:    ; implicit-def: $vgpr52
; GCN-NEXT:    ; implicit-def: $vgpr51
; GCN-NEXT:    ; implicit-def: $vgpr50
; GCN-NEXT:    ; implicit-def: $vgpr49
; GCN-NEXT:    ; implicit-def: $vgpr48
; GCN-NEXT:    ; implicit-def: $vgpr39
; GCN-NEXT:    ; implicit-def: $vgpr38
; GCN-NEXT:    ; implicit-def: $vgpr37
; GCN-NEXT:    ; implicit-def: $vgpr36
; GCN-NEXT:    ; implicit-def: $vgpr35
; GCN-NEXT:    ; implicit-def: $vgpr34
; GCN-NEXT:    ; implicit-def: $vgpr33
; GCN-NEXT:  .LBB8_2: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB8_4
; GCN-NEXT:  ; %bb.3: ; %cmp.true
; GCN-NEXT:    v_add_i32_e32 v0, vcc, 3, v32
; GCN-NEXT:    v_add_i32_e32 v1, vcc, 3, v55
; GCN-NEXT:    v_add_i32_e32 v2, vcc, 3, v54
; GCN-NEXT:    v_add_i32_e32 v3, vcc, 3, v53
; GCN-NEXT:    v_add_i32_e32 v4, vcc, 3, v52
; GCN-NEXT:    v_add_i32_e32 v5, vcc, 3, v51
; GCN-NEXT:    v_add_i32_e32 v6, vcc, 3, v50
; GCN-NEXT:    v_add_i32_e32 v7, vcc, 3, v49
; GCN-NEXT:    v_add_i32_e32 v8, vcc, 3, v48
; GCN-NEXT:    v_add_i32_e32 v9, vcc, 3, v39
; GCN-NEXT:    v_add_i32_e32 v10, vcc, 3, v38
; GCN-NEXT:    v_add_i32_e32 v11, vcc, 3, v37
; GCN-NEXT:    v_add_i32_e32 v12, vcc, 3, v36
; GCN-NEXT:    v_add_i32_e32 v13, vcc, 3, v35
; GCN-NEXT:    v_add_i32_e32 v14, vcc, 3, v34
; GCN-NEXT:    v_add_i32_e32 v15, vcc, 3, v33
; GCN-NEXT:    v_lshrrev_b32_e32 v32, 16, v0
; GCN-NEXT:    v_lshrrev_b32_e32 v33, 16, v1
; GCN-NEXT:    v_lshrrev_b32_e32 v34, 16, v2
; GCN-NEXT:    v_lshrrev_b32_e32 v35, 16, v3
; GCN-NEXT:    v_lshrrev_b32_e32 v36, 16, v4
; GCN-NEXT:    v_lshrrev_b32_e32 v37, 16, v5
; GCN-NEXT:    v_lshrrev_b32_e32 v38, 16, v6
; GCN-NEXT:    v_lshrrev_b32_e32 v39, 16, v7
; GCN-NEXT:    v_lshrrev_b32_e32 v17, 16, v8
; GCN-NEXT:    v_lshrrev_b32_e32 v19, 16, v9
; GCN-NEXT:    v_lshrrev_b32_e32 v21, 16, v10
; GCN-NEXT:    v_lshrrev_b32_e32 v23, 16, v11
; GCN-NEXT:    v_lshrrev_b32_e32 v25, 16, v12
; GCN-NEXT:    v_lshrrev_b32_e32 v27, 16, v13
; GCN-NEXT:    v_lshrrev_b32_e32 v29, 16, v14
; GCN-NEXT:    v_lshrrev_b32_e32 v31, 16, v15
; GCN-NEXT:    v_cvt_f32_f16_e32 v30, v15
; GCN-NEXT:    v_cvt_f32_f16_e32 v28, v14
; GCN-NEXT:    v_cvt_f32_f16_e32 v26, v13
; GCN-NEXT:    v_cvt_f32_f16_e32 v24, v12
; GCN-NEXT:    v_cvt_f32_f16_e32 v22, v11
; GCN-NEXT:    v_cvt_f32_f16_e32 v20, v10
; GCN-NEXT:    v_cvt_f32_f16_e32 v18, v9
; GCN-NEXT:    v_cvt_f32_f16_e32 v16, v8
; GCN-NEXT:    v_cvt_f32_f16_e32 v14, v7
; GCN-NEXT:    v_cvt_f32_f16_e32 v12, v6
; GCN-NEXT:    v_cvt_f32_f16_e32 v10, v5
; GCN-NEXT:    v_cvt_f32_f16_e32 v8, v4
; GCN-NEXT:    v_cvt_f32_f16_e32 v6, v3
; GCN-NEXT:    v_cvt_f32_f16_e32 v4, v2
; GCN-NEXT:    v_cvt_f32_f16_e32 v2, v1
; GCN-NEXT:    v_cvt_f32_f16_e32 v0, v0
; GCN-NEXT:    v_cvt_f32_f16_e32 v31, v31
; GCN-NEXT:    v_cvt_f32_f16_e32 v29, v29
; GCN-NEXT:    v_cvt_f32_f16_e32 v27, v27
; GCN-NEXT:    v_cvt_f32_f16_e32 v25, v25
; GCN-NEXT:    v_cvt_f32_f16_e32 v23, v23
; GCN-NEXT:    v_cvt_f32_f16_e32 v21, v21
; GCN-NEXT:    v_cvt_f32_f16_e32 v19, v19
; GCN-NEXT:    v_cvt_f32_f16_e32 v17, v17
; GCN-NEXT:    v_cvt_f32_f16_e32 v15, v39
; GCN-NEXT:    v_cvt_f32_f16_e32 v13, v38
; GCN-NEXT:    v_cvt_f32_f16_e32 v11, v37
; GCN-NEXT:    v_cvt_f32_f16_e32 v9, v36
; GCN-NEXT:    v_cvt_f32_f16_e32 v7, v35
; GCN-NEXT:    v_cvt_f32_f16_e32 v5, v34
; GCN-NEXT:    v_cvt_f32_f16_e32 v3, v33
; GCN-NEXT:    v_cvt_f32_f16_e32 v1, v32
; GCN-NEXT:  .LBB8_4: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_waitcnt expcnt(0)
; GCN-NEXT:    buffer_load_dword v46, off, s[0:3], s32 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v16i32_to_v32f16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB8_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v15, vcc, 3, v15
; VI-NEXT:    v_add_u32_e32 v14, vcc, 3, v14
; VI-NEXT:    v_add_u32_e32 v13, vcc, 3, v13
; VI-NEXT:    v_add_u32_e32 v12, vcc, 3, v12
; VI-NEXT:    v_add_u32_e32 v11, vcc, 3, v11
; VI-NEXT:    v_add_u32_e32 v10, vcc, 3, v10
; VI-NEXT:    v_add_u32_e32 v9, vcc, 3, v9
; VI-NEXT:    v_add_u32_e32 v8, vcc, 3, v8
; VI-NEXT:    v_add_u32_e32 v7, vcc, 3, v7
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_add_u32_e32 v5, vcc, 3, v5
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_add_u32_e32 v3, vcc, 3, v3
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_add_u32_e32 v1, vcc, 3, v1
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:  .LBB8_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v16i32_to_v32f16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB8_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_u32_e32 v15, 3, v15
; GFX9-NEXT:    v_add_u32_e32 v14, 3, v14
; GFX9-NEXT:    v_add_u32_e32 v13, 3, v13
; GFX9-NEXT:    v_add_u32_e32 v12, 3, v12
; GFX9-NEXT:    v_add_u32_e32 v11, 3, v11
; GFX9-NEXT:    v_add_u32_e32 v10, 3, v10
; GFX9-NEXT:    v_add_u32_e32 v9, 3, v9
; GFX9-NEXT:    v_add_u32_e32 v8, 3, v8
; GFX9-NEXT:    v_add_u32_e32 v7, 3, v7
; GFX9-NEXT:    v_add_u32_e32 v6, 3, v6
; GFX9-NEXT:    v_add_u32_e32 v5, 3, v5
; GFX9-NEXT:    v_add_u32_e32 v4, 3, v4
; GFX9-NEXT:    v_add_u32_e32 v3, 3, v3
; GFX9-NEXT:    v_add_u32_e32 v2, 3, v2
; GFX9-NEXT:    v_add_u32_e32 v1, 3, v1
; GFX9-NEXT:    v_add_u32_e32 v0, 3, v0
; GFX9-NEXT:  .LBB8_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v16i32_to_v32f16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB8_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_nc_u32_e32 v15, 3, v15
; GFX11-NEXT:    v_add_nc_u32_e32 v14, 3, v14
; GFX11-NEXT:    v_add_nc_u32_e32 v13, 3, v13
; GFX11-NEXT:    v_add_nc_u32_e32 v12, 3, v12
; GFX11-NEXT:    v_add_nc_u32_e32 v11, 3, v11
; GFX11-NEXT:    v_add_nc_u32_e32 v10, 3, v10
; GFX11-NEXT:    v_add_nc_u32_e32 v9, 3, v9
; GFX11-NEXT:    v_add_nc_u32_e32 v8, 3, v8
; GFX11-NEXT:    v_add_nc_u32_e32 v7, 3, v7
; GFX11-NEXT:    v_add_nc_u32_e32 v6, 3, v6
; GFX11-NEXT:    v_add_nc_u32_e32 v5, 3, v5
; GFX11-NEXT:    v_add_nc_u32_e32 v4, 3, v4
; GFX11-NEXT:    v_add_nc_u32_e32 v3, 3, v3
; GFX11-NEXT:    v_add_nc_u32_e32 v2, 3, v2
; GFX11-NEXT:    v_add_nc_u32_e32 v1, 3, v1
; GFX11-NEXT:    v_add_nc_u32_e32 v0, 3, v0
; GFX11-NEXT:  .LBB8_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <16 x i32> %a, splat (i32 3)
  %a2 = bitcast <16 x i32> %a1 to <32 x half>
  br label %end

cmp.false:
  %a3 = bitcast <16 x i32> %a to <32 x half>
  br label %end

end:
  %phi = phi <32 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x half> %phi
}

define <16 x i32> @v_bitcast_v32f16_to_v16i32(<32 x half> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v32f16_to_v16i32:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GCN-NEXT:    s_waitcnt expcnt(1)
; GCN-NEXT:    buffer_load_dword v46, off, s[0:3], s32
; GCN-NEXT:    s_waitcnt expcnt(0)
; GCN-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:4
; GCN-NEXT:    v_cvt_f16_f32_e32 v45, v1
; GCN-NEXT:    v_cvt_f16_f32_e32 v44, v0
; GCN-NEXT:    v_cvt_f16_f32_e32 v43, v3
; GCN-NEXT:    v_cvt_f16_f32_e32 v42, v2
; GCN-NEXT:    v_cvt_f16_f32_e32 v41, v5
; GCN-NEXT:    v_cvt_f16_f32_e32 v52, v4
; GCN-NEXT:    v_cvt_f16_f32_e32 v40, v7
; GCN-NEXT:    v_cvt_f16_f32_e32 v50, v6
; GCN-NEXT:    v_cvt_f16_f32_e32 v55, v9
; GCN-NEXT:    v_cvt_f16_f32_e32 v48, v8
; GCN-NEXT:    v_cvt_f16_f32_e32 v54, v11
; GCN-NEXT:    v_cvt_f16_f32_e32 v38, v10
; GCN-NEXT:    v_cvt_f16_f32_e32 v53, v13
; GCN-NEXT:    v_cvt_f16_f32_e32 v36, v12
; GCN-NEXT:    v_cvt_f16_f32_e32 v51, v15
; GCN-NEXT:    v_cvt_f16_f32_e32 v34, v14
; GCN-NEXT:    v_cvt_f16_f32_e32 v49, v17
; GCN-NEXT:    v_cvt_f16_f32_e32 v33, v16
; GCN-NEXT:    v_cvt_f16_f32_e32 v39, v19
; GCN-NEXT:    v_cvt_f16_f32_e32 v32, v18
; GCN-NEXT:    v_cvt_f16_f32_e32 v37, v21
; GCN-NEXT:    v_cvt_f16_f32_e32 v31, v20
; GCN-NEXT:    v_cvt_f16_f32_e32 v35, v23
; GCN-NEXT:    v_cvt_f16_f32_e32 v21, v22
; GCN-NEXT:    v_cvt_f16_f32_e32 v25, v25
; GCN-NEXT:    v_cvt_f16_f32_e32 v19, v24
; GCN-NEXT:    v_cvt_f16_f32_e32 v23, v27
; GCN-NEXT:    v_cvt_f16_f32_e32 v18, v26
; GCN-NEXT:    v_cvt_f16_f32_e32 v22, v29
; GCN-NEXT:    v_cvt_f16_f32_e32 v17, v28
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v47
; GCN-NEXT:    v_cvt_f16_f32_e32 v20, v46
; GCN-NEXT:    v_cvt_f16_f32_e32 v16, v30
; GCN-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB9_2
; GCN-NEXT:  ; %bb.1: ; %cmp.false
; GCN-NEXT:    v_lshlrev_b32_e32 v0, 16, v45
; GCN-NEXT:    v_lshlrev_b32_e32 v1, 16, v43
; GCN-NEXT:    v_or_b32_e32 v0, v44, v0
; GCN-NEXT:    v_or_b32_e32 v1, v42, v1
; GCN-NEXT:    v_lshlrev_b32_e32 v2, 16, v41
; GCN-NEXT:    v_lshlrev_b32_e32 v3, 16, v40
; GCN-NEXT:    v_lshlrev_b32_e32 v4, 16, v55
; GCN-NEXT:    v_lshlrev_b32_e32 v5, 16, v54
; GCN-NEXT:    v_lshlrev_b32_e32 v6, 16, v53
; GCN-NEXT:    v_lshlrev_b32_e32 v7, 16, v51
; GCN-NEXT:    v_lshlrev_b32_e32 v8, 16, v49
; GCN-NEXT:    v_lshlrev_b32_e32 v9, 16, v39
; GCN-NEXT:    v_lshlrev_b32_e32 v10, 16, v37
; GCN-NEXT:    v_lshlrev_b32_e32 v11, 16, v35
; GCN-NEXT:    v_lshlrev_b32_e32 v12, 16, v25
; GCN-NEXT:    v_lshlrev_b32_e32 v13, 16, v23
; GCN-NEXT:    v_lshlrev_b32_e32 v14, 16, v22
; GCN-NEXT:    v_lshlrev_b32_e32 v15, 16, v20
; GCN-NEXT:    v_or_b32_e32 v2, v52, v2
; GCN-NEXT:    v_or_b32_e32 v3, v50, v3
; GCN-NEXT:    v_or_b32_e32 v4, v48, v4
; GCN-NEXT:    v_or_b32_e32 v5, v38, v5
; GCN-NEXT:    v_or_b32_e32 v6, v36, v6
; GCN-NEXT:    v_or_b32_e32 v7, v34, v7
; GCN-NEXT:    v_or_b32_e32 v8, v33, v8
; GCN-NEXT:    v_or_b32_e32 v9, v32, v9
; GCN-NEXT:    v_or_b32_e32 v10, v31, v10
; GCN-NEXT:    v_or_b32_e32 v11, v21, v11
; GCN-NEXT:    v_or_b32_e32 v12, v19, v12
; GCN-NEXT:    v_or_b32_e32 v13, v18, v13
; GCN-NEXT:    v_or_b32_e32 v14, v17, v14
; GCN-NEXT:    v_or_b32_e32 v15, v16, v15
; GCN-NEXT:    ; implicit-def: $vgpr45
; GCN-NEXT:    ; implicit-def: $vgpr44
; GCN-NEXT:    ; implicit-def: $vgpr43
; GCN-NEXT:    ; implicit-def: $vgpr42
; GCN-NEXT:    ; implicit-def: $vgpr41
; GCN-NEXT:    ; implicit-def: $vgpr52
; GCN-NEXT:    ; implicit-def: $vgpr40
; GCN-NEXT:    ; implicit-def: $vgpr50
; GCN-NEXT:    ; implicit-def: $vgpr55
; GCN-NEXT:    ; implicit-def: $vgpr48
; GCN-NEXT:    ; implicit-def: $vgpr54
; GCN-NEXT:    ; implicit-def: $vgpr38
; GCN-NEXT:    ; implicit-def: $vgpr53
; GCN-NEXT:    ; implicit-def: $vgpr36
; GCN-NEXT:    ; implicit-def: $vgpr51
; GCN-NEXT:    ; implicit-def: $vgpr34
; GCN-NEXT:    ; implicit-def: $vgpr49
; GCN-NEXT:    ; implicit-def: $vgpr33
; GCN-NEXT:    ; implicit-def: $vgpr39
; GCN-NEXT:    ; implicit-def: $vgpr32
; GCN-NEXT:    ; implicit-def: $vgpr37
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    ; implicit-def: $vgpr35
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr18
; GCN-NEXT:    ; implicit-def: $vgpr22
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr20
; GCN-NEXT:    ; implicit-def: $vgpr16
; GCN-NEXT:  .LBB9_2: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB9_4
; GCN-NEXT:  ; %bb.3: ; %cmp.true
; GCN-NEXT:    v_cvt_f32_f16_e32 v0, v45
; GCN-NEXT:    v_cvt_f32_f16_e32 v1, v44
; GCN-NEXT:    v_cvt_f32_f16_e32 v2, v43
; GCN-NEXT:    v_cvt_f32_f16_e32 v3, v42
; GCN-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; GCN-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; GCN-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; GCN-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; GCN-NEXT:    v_cvt_f16_f32_e32 v0, v0
; GCN-NEXT:    v_cvt_f16_f32_e32 v1, v1
; GCN-NEXT:    v_cvt_f16_f32_e32 v2, v2
; GCN-NEXT:    v_cvt_f16_f32_e32 v3, v3
; GCN-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; GCN-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; GCN-NEXT:    v_or_b32_e32 v0, v1, v0
; GCN-NEXT:    v_or_b32_e32 v1, v3, v2
; GCN-NEXT:    v_cvt_f32_f16_e32 v2, v41
; GCN-NEXT:    v_cvt_f32_f16_e32 v3, v52
; GCN-NEXT:    v_cvt_f32_f16_e32 v4, v40
; GCN-NEXT:    v_cvt_f32_f16_e32 v5, v50
; GCN-NEXT:    v_cvt_f32_f16_e32 v6, v55
; GCN-NEXT:    v_cvt_f32_f16_e32 v7, v48
; GCN-NEXT:    v_cvt_f32_f16_e32 v8, v54
; GCN-NEXT:    v_cvt_f32_f16_e32 v9, v38
; GCN-NEXT:    v_cvt_f32_f16_e32 v10, v53
; GCN-NEXT:    v_cvt_f32_f16_e32 v11, v36
; GCN-NEXT:    v_cvt_f32_f16_e32 v12, v51
; GCN-NEXT:    v_cvt_f32_f16_e32 v13, v34
; GCN-NEXT:    v_cvt_f32_f16_e32 v14, v49
; GCN-NEXT:    v_cvt_f32_f16_e32 v15, v33
; GCN-NEXT:    v_cvt_f32_f16_e32 v24, v39
; GCN-NEXT:    v_cvt_f32_f16_e32 v26, v32
; GCN-NEXT:    v_cvt_f32_f16_e32 v27, v37
; GCN-NEXT:    v_cvt_f32_f16_e32 v28, v31
; GCN-NEXT:    v_cvt_f32_f16_e32 v29, v35
; GCN-NEXT:    v_cvt_f32_f16_e32 v21, v21
; GCN-NEXT:    v_cvt_f32_f16_e32 v25, v25
; GCN-NEXT:    v_cvt_f32_f16_e32 v19, v19
; GCN-NEXT:    v_cvt_f32_f16_e32 v23, v23
; GCN-NEXT:    v_cvt_f32_f16_e32 v18, v18
; GCN-NEXT:    v_cvt_f32_f16_e32 v22, v22
; GCN-NEXT:    v_cvt_f32_f16_e32 v17, v17
; GCN-NEXT:    v_cvt_f32_f16_e32 v20, v20
; GCN-NEXT:    v_cvt_f32_f16_e32 v16, v16
; GCN-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; GCN-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; GCN-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; GCN-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; GCN-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; GCN-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; GCN-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; GCN-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; GCN-NEXT:    v_add_f32_e32 v10, 0x38000000, v10
; GCN-NEXT:    v_add_f32_e32 v11, 0x38000000, v11
; GCN-NEXT:    v_add_f32_e32 v12, 0x38000000, v12
; GCN-NEXT:    v_add_f32_e32 v13, 0x38000000, v13
; GCN-NEXT:    v_add_f32_e32 v14, 0x38000000, v14
; GCN-NEXT:    v_add_f32_e32 v15, 0x38000000, v15
; GCN-NEXT:    v_add_f32_e32 v24, 0x38000000, v24
; GCN-NEXT:    v_add_f32_e32 v26, 0x38000000, v26
; GCN-NEXT:    v_add_f32_e32 v27, 0x38000000, v27
; GCN-NEXT:    v_add_f32_e32 v28, 0x38000000, v28
; GCN-NEXT:    v_add_f32_e32 v29, 0x38000000, v29
; GCN-NEXT:    v_add_f32_e32 v21, 0x38000000, v21
; GCN-NEXT:    v_add_f32_e32 v25, 0x38000000, v25
; GCN-NEXT:    v_add_f32_e32 v19, 0x38000000, v19
; GCN-NEXT:    v_add_f32_e32 v23, 0x38000000, v23
; GCN-NEXT:    v_add_f32_e32 v18, 0x38000000, v18
; GCN-NEXT:    v_add_f32_e32 v22, 0x38000000, v22
; GCN-NEXT:    v_add_f32_e32 v17, 0x38000000, v17
; GCN-NEXT:    v_add_f32_e32 v20, 0x38000000, v20
; GCN-NEXT:    v_add_f32_e32 v16, 0x38000000, v16
; GCN-NEXT:    v_cvt_f16_f32_e32 v2, v2
; GCN-NEXT:    v_cvt_f16_f32_e32 v3, v3
; GCN-NEXT:    v_cvt_f16_f32_e32 v4, v4
; GCN-NEXT:    v_cvt_f16_f32_e32 v5, v5
; GCN-NEXT:    v_cvt_f16_f32_e32 v6, v6
; GCN-NEXT:    v_cvt_f16_f32_e32 v7, v7
; GCN-NEXT:    v_cvt_f16_f32_e32 v8, v8
; GCN-NEXT:    v_cvt_f16_f32_e32 v9, v9
; GCN-NEXT:    v_cvt_f16_f32_e32 v10, v10
; GCN-NEXT:    v_cvt_f16_f32_e32 v11, v11
; GCN-NEXT:    v_cvt_f16_f32_e32 v12, v12
; GCN-NEXT:    v_cvt_f16_f32_e32 v13, v13
; GCN-NEXT:    v_cvt_f16_f32_e32 v14, v14
; GCN-NEXT:    v_cvt_f16_f32_e32 v15, v15
; GCN-NEXT:    v_cvt_f16_f32_e32 v24, v24
; GCN-NEXT:    v_cvt_f16_f32_e32 v26, v26
; GCN-NEXT:    v_cvt_f16_f32_e32 v27, v27
; GCN-NEXT:    v_cvt_f16_f32_e32 v28, v28
; GCN-NEXT:    v_cvt_f16_f32_e32 v29, v29
; GCN-NEXT:    v_cvt_f16_f32_e32 v21, v21
; GCN-NEXT:    v_cvt_f16_f32_e32 v25, v25
; GCN-NEXT:    v_cvt_f16_f32_e32 v19, v19
; GCN-NEXT:    v_cvt_f16_f32_e32 v23, v23
; GCN-NEXT:    v_cvt_f16_f32_e32 v18, v18
; GCN-NEXT:    v_cvt_f16_f32_e32 v22, v22
; GCN-NEXT:    v_cvt_f16_f32_e32 v17, v17
; GCN-NEXT:    v_cvt_f16_f32_e32 v20, v20
; GCN-NEXT:    v_cvt_f16_f32_e32 v16, v16
; GCN-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; GCN-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GCN-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GCN-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; GCN-NEXT:    v_lshlrev_b32_e32 v10, 16, v10
; GCN-NEXT:    v_lshlrev_b32_e32 v12, 16, v12
; GCN-NEXT:    v_lshlrev_b32_e32 v14, 16, v14
; GCN-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; GCN-NEXT:    v_lshlrev_b32_e32 v27, 16, v27
; GCN-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; GCN-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; GCN-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; GCN-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; GCN-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; GCN-NEXT:    v_or_b32_e32 v2, v3, v2
; GCN-NEXT:    v_or_b32_e32 v3, v5, v4
; GCN-NEXT:    v_or_b32_e32 v4, v7, v6
; GCN-NEXT:    v_or_b32_e32 v5, v9, v8
; GCN-NEXT:    v_or_b32_e32 v6, v11, v10
; GCN-NEXT:    v_or_b32_e32 v7, v13, v12
; GCN-NEXT:    v_or_b32_e32 v8, v15, v14
; GCN-NEXT:    v_or_b32_e32 v9, v26, v24
; GCN-NEXT:    v_or_b32_e32 v10, v28, v27
; GCN-NEXT:    v_or_b32_e32 v11, v21, v29
; GCN-NEXT:    v_or_b32_e32 v12, v19, v25
; GCN-NEXT:    v_or_b32_e32 v13, v18, v23
; GCN-NEXT:    v_or_b32_e32 v14, v17, v22
; GCN-NEXT:    v_or_b32_e32 v15, v16, v20
; GCN-NEXT:  .LBB9_4: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v32f16_to_v16i32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB9_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v16, 0x200
; VI-NEXT:    v_add_f16_sdwa v17, v15, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v15, 0x200, v15
; VI-NEXT:    v_or_b32_e32 v15, v15, v17
; VI-NEXT:    v_add_f16_sdwa v17, v14, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v14, 0x200, v14
; VI-NEXT:    v_or_b32_e32 v14, v14, v17
; VI-NEXT:    v_add_f16_sdwa v17, v13, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v13, 0x200, v13
; VI-NEXT:    v_or_b32_e32 v13, v13, v17
; VI-NEXT:    v_add_f16_sdwa v17, v12, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v12, 0x200, v12
; VI-NEXT:    v_or_b32_e32 v12, v12, v17
; VI-NEXT:    v_add_f16_sdwa v17, v11, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v11, 0x200, v11
; VI-NEXT:    v_or_b32_e32 v11, v11, v17
; VI-NEXT:    v_add_f16_sdwa v17, v10, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v10, 0x200, v10
; VI-NEXT:    v_or_b32_e32 v10, v10, v17
; VI-NEXT:    v_add_f16_sdwa v17, v9, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v9, 0x200, v9
; VI-NEXT:    v_or_b32_e32 v9, v9, v17
; VI-NEXT:    v_add_f16_sdwa v17, v8, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v8, 0x200, v8
; VI-NEXT:    v_or_b32_e32 v8, v8, v17
; VI-NEXT:    v_add_f16_sdwa v17, v7, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v7, 0x200, v7
; VI-NEXT:    v_or_b32_e32 v7, v7, v17
; VI-NEXT:    v_add_f16_sdwa v17, v6, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v6, 0x200, v6
; VI-NEXT:    v_or_b32_e32 v6, v6, v17
; VI-NEXT:    v_add_f16_sdwa v17, v5, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v5, 0x200, v5
; VI-NEXT:    v_or_b32_e32 v5, v5, v17
; VI-NEXT:    v_add_f16_sdwa v17, v4, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v4, 0x200, v4
; VI-NEXT:    v_or_b32_e32 v4, v4, v17
; VI-NEXT:    v_add_f16_sdwa v17, v3, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v3, 0x200, v3
; VI-NEXT:    v_or_b32_e32 v3, v3, v17
; VI-NEXT:    v_add_f16_sdwa v17, v2, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, 0x200, v2
; VI-NEXT:    v_or_b32_e32 v2, v2, v17
; VI-NEXT:    v_add_f16_sdwa v17, v1, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v1, 0x200, v1
; VI-NEXT:    v_add_f16_sdwa v16, v0, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v0, 0x200, v0
; VI-NEXT:    v_or_b32_e32 v1, v1, v17
; VI-NEXT:    v_or_b32_e32 v0, v0, v16
; VI-NEXT:  .LBB9_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v32f16_to_v16i32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB9_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    s_movk_i32 s6, 0x200
; GFX9-NEXT:    v_pk_add_f16 v15, v15, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v14, v14, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v13, v13, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v12, v12, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v11, v11, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v10, v10, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v9, v9, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v8, v8, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v7, v7, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, v6, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v5, v5, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v4, v4, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v3, v3, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v2, v2, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v1, v1, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v0, v0, s6 op_sel_hi:[1,0]
; GFX9-NEXT:  .LBB9_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v32f16_to_v16i32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB9_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_pk_add_f16 v15, 0x200, v15 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v14, 0x200, v14 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v13, 0x200, v13 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v12, 0x200, v12 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v11, 0x200, v11 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v10, 0x200, v10 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v9, 0x200, v9 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v8, 0x200, v8 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v7, 0x200, v7 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v6, 0x200, v6 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v5, 0x200, v5 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v4, 0x200, v4 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v3, 0x200, v3 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v2, 0x200, v2 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v1, 0x200, v1 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v0, 0x200, v0 op_sel_hi:[0,1]
; GFX11-NEXT:  .LBB9_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <32 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <32 x half> %a1 to <16 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <32 x half> %a to <16 x i32>
  br label %end

end:
  %phi = phi <16 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x i32> %phi
}

define <32 x bfloat> @v_bitcast_v16i32_to_v32bf16(<16 x i32> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v16i32_to_v32bf16:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_mov_b32_e32 v55, v15
; GCN-NEXT:    v_mov_b32_e32 v54, v14
; GCN-NEXT:    v_mov_b32_e32 v53, v13
; GCN-NEXT:    v_mov_b32_e32 v52, v12
; GCN-NEXT:    v_mov_b32_e32 v51, v11
; GCN-NEXT:    v_mov_b32_e32 v50, v10
; GCN-NEXT:    v_mov_b32_e32 v49, v9
; GCN-NEXT:    v_mov_b32_e32 v48, v8
; GCN-NEXT:    v_mov_b32_e32 v39, v7
; GCN-NEXT:    v_mov_b32_e32 v38, v6
; GCN-NEXT:    v_mov_b32_e32 v37, v5
; GCN-NEXT:    v_mov_b32_e32 v36, v4
; GCN-NEXT:    v_mov_b32_e32 v35, v3
; GCN-NEXT:    v_mov_b32_e32 v34, v2
; GCN-NEXT:    v_mov_b32_e32 v33, v1
; GCN-NEXT:    v_mov_b32_e32 v32, v0
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GCN-NEXT:    ; implicit-def: $vgpr0
; GCN-NEXT:    ; implicit-def: $vgpr1
; GCN-NEXT:    ; implicit-def: $vgpr2
; GCN-NEXT:    ; implicit-def: $vgpr3
; GCN-NEXT:    ; implicit-def: $vgpr4
; GCN-NEXT:    ; implicit-def: $vgpr5
; GCN-NEXT:    ; implicit-def: $vgpr6
; GCN-NEXT:    ; implicit-def: $vgpr7
; GCN-NEXT:    ; implicit-def: $vgpr8
; GCN-NEXT:    ; implicit-def: $vgpr9
; GCN-NEXT:    ; implicit-def: $vgpr10
; GCN-NEXT:    ; implicit-def: $vgpr11
; GCN-NEXT:    ; implicit-def: $vgpr12
; GCN-NEXT:    ; implicit-def: $vgpr13
; GCN-NEXT:    ; implicit-def: $vgpr14
; GCN-NEXT:    ; implicit-def: $vgpr15
; GCN-NEXT:    ; implicit-def: $vgpr16
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr18
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr20
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr22
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr24
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr26
; GCN-NEXT:    ; implicit-def: $vgpr27
; GCN-NEXT:    ; implicit-def: $vgpr28
; GCN-NEXT:    ; implicit-def: $vgpr29
; GCN-NEXT:    ; implicit-def: $vgpr30
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execnz .LBB10_3
; GCN-NEXT:  ; %bb.1: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execnz .LBB10_4
; GCN-NEXT:  .LBB10_2: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
; GCN-NEXT:  .LBB10_3: ; %cmp.false
; GCN-NEXT:    v_and_b32_e32 v31, 0xffff0000, v55
; GCN-NEXT:    v_lshlrev_b32_e32 v30, 16, v55
; GCN-NEXT:    v_and_b32_e32 v29, 0xffff0000, v54
; GCN-NEXT:    v_lshlrev_b32_e32 v28, 16, v54
; GCN-NEXT:    v_and_b32_e32 v27, 0xffff0000, v53
; GCN-NEXT:    v_lshlrev_b32_e32 v26, 16, v53
; GCN-NEXT:    v_and_b32_e32 v25, 0xffff0000, v52
; GCN-NEXT:    v_lshlrev_b32_e32 v24, 16, v52
; GCN-NEXT:    v_and_b32_e32 v23, 0xffff0000, v51
; GCN-NEXT:    v_lshlrev_b32_e32 v22, 16, v51
; GCN-NEXT:    v_and_b32_e32 v21, 0xffff0000, v50
; GCN-NEXT:    v_lshlrev_b32_e32 v20, 16, v50
; GCN-NEXT:    v_and_b32_e32 v19, 0xffff0000, v49
; GCN-NEXT:    v_lshlrev_b32_e32 v18, 16, v49
; GCN-NEXT:    v_and_b32_e32 v17, 0xffff0000, v48
; GCN-NEXT:    v_lshlrev_b32_e32 v16, 16, v48
; GCN-NEXT:    v_and_b32_e32 v15, 0xffff0000, v39
; GCN-NEXT:    v_lshlrev_b32_e32 v14, 16, v39
; GCN-NEXT:    v_and_b32_e32 v13, 0xffff0000, v38
; GCN-NEXT:    v_lshlrev_b32_e32 v12, 16, v38
; GCN-NEXT:    v_and_b32_e32 v11, 0xffff0000, v37
; GCN-NEXT:    v_lshlrev_b32_e32 v10, 16, v37
; GCN-NEXT:    v_and_b32_e32 v9, 0xffff0000, v36
; GCN-NEXT:    v_lshlrev_b32_e32 v8, 16, v36
; GCN-NEXT:    v_and_b32_e32 v7, 0xffff0000, v35
; GCN-NEXT:    v_lshlrev_b32_e32 v6, 16, v35
; GCN-NEXT:    v_and_b32_e32 v5, 0xffff0000, v34
; GCN-NEXT:    v_lshlrev_b32_e32 v4, 16, v34
; GCN-NEXT:    v_and_b32_e32 v3, 0xffff0000, v33
; GCN-NEXT:    v_lshlrev_b32_e32 v2, 16, v33
; GCN-NEXT:    v_and_b32_e32 v1, 0xffff0000, v32
; GCN-NEXT:    v_lshlrev_b32_e32 v0, 16, v32
; GCN-NEXT:    ; implicit-def: $vgpr32
; GCN-NEXT:    ; implicit-def: $vgpr33
; GCN-NEXT:    ; implicit-def: $vgpr34
; GCN-NEXT:    ; implicit-def: $vgpr35
; GCN-NEXT:    ; implicit-def: $vgpr36
; GCN-NEXT:    ; implicit-def: $vgpr37
; GCN-NEXT:    ; implicit-def: $vgpr38
; GCN-NEXT:    ; implicit-def: $vgpr39
; GCN-NEXT:    ; implicit-def: $vgpr48
; GCN-NEXT:    ; implicit-def: $vgpr49
; GCN-NEXT:    ; implicit-def: $vgpr50
; GCN-NEXT:    ; implicit-def: $vgpr51
; GCN-NEXT:    ; implicit-def: $vgpr52
; GCN-NEXT:    ; implicit-def: $vgpr53
; GCN-NEXT:    ; implicit-def: $vgpr54
; GCN-NEXT:    ; implicit-def: $vgpr55
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB10_2
; GCN-NEXT:  .LBB10_4: ; %cmp.true
; GCN-NEXT:    v_add_i32_e32 v0, vcc, 3, v32
; GCN-NEXT:    v_add_i32_e32 v1, vcc, 3, v33
; GCN-NEXT:    v_add_i32_e32 v2, vcc, 3, v34
; GCN-NEXT:    v_add_i32_e32 v3, vcc, 3, v35
; GCN-NEXT:    v_add_i32_e32 v4, vcc, 3, v36
; GCN-NEXT:    v_add_i32_e32 v5, vcc, 3, v37
; GCN-NEXT:    v_add_i32_e32 v6, vcc, 3, v38
; GCN-NEXT:    v_add_i32_e32 v7, vcc, 3, v39
; GCN-NEXT:    v_add_i32_e32 v8, vcc, 3, v48
; GCN-NEXT:    v_add_i32_e32 v9, vcc, 3, v49
; GCN-NEXT:    v_add_i32_e32 v10, vcc, 3, v50
; GCN-NEXT:    v_add_i32_e32 v11, vcc, 3, v51
; GCN-NEXT:    v_add_i32_e32 v12, vcc, 3, v52
; GCN-NEXT:    v_add_i32_e32 v13, vcc, 3, v53
; GCN-NEXT:    v_add_i32_e32 v14, vcc, 3, v54
; GCN-NEXT:    v_add_i32_e32 v15, vcc, 3, v55
; GCN-NEXT:    v_and_b32_e32 v31, 0xffff0000, v15
; GCN-NEXT:    v_lshlrev_b32_e32 v30, 16, v15
; GCN-NEXT:    v_and_b32_e32 v29, 0xffff0000, v14
; GCN-NEXT:    v_lshlrev_b32_e32 v28, 16, v14
; GCN-NEXT:    v_and_b32_e32 v27, 0xffff0000, v13
; GCN-NEXT:    v_lshlrev_b32_e32 v26, 16, v13
; GCN-NEXT:    v_and_b32_e32 v25, 0xffff0000, v12
; GCN-NEXT:    v_lshlrev_b32_e32 v24, 16, v12
; GCN-NEXT:    v_and_b32_e32 v23, 0xffff0000, v11
; GCN-NEXT:    v_lshlrev_b32_e32 v22, 16, v11
; GCN-NEXT:    v_and_b32_e32 v21, 0xffff0000, v10
; GCN-NEXT:    v_lshlrev_b32_e32 v20, 16, v10
; GCN-NEXT:    v_and_b32_e32 v19, 0xffff0000, v9
; GCN-NEXT:    v_lshlrev_b32_e32 v18, 16, v9
; GCN-NEXT:    v_and_b32_e32 v17, 0xffff0000, v8
; GCN-NEXT:    v_lshlrev_b32_e32 v16, 16, v8
; GCN-NEXT:    v_and_b32_e32 v15, 0xffff0000, v7
; GCN-NEXT:    v_lshlrev_b32_e32 v14, 16, v7
; GCN-NEXT:    v_and_b32_e32 v13, 0xffff0000, v6
; GCN-NEXT:    v_lshlrev_b32_e32 v12, 16, v6
; GCN-NEXT:    v_and_b32_e32 v11, 0xffff0000, v5
; GCN-NEXT:    v_lshlrev_b32_e32 v10, 16, v5
; GCN-NEXT:    v_and_b32_e32 v9, 0xffff0000, v4
; GCN-NEXT:    v_lshlrev_b32_e32 v8, 16, v4
; GCN-NEXT:    v_and_b32_e32 v7, 0xffff0000, v3
; GCN-NEXT:    v_lshlrev_b32_e32 v6, 16, v3
; GCN-NEXT:    v_and_b32_e32 v5, 0xffff0000, v2
; GCN-NEXT:    v_lshlrev_b32_e32 v4, 16, v2
; GCN-NEXT:    v_and_b32_e32 v3, 0xffff0000, v1
; GCN-NEXT:    v_lshlrev_b32_e32 v2, 16, v1
; GCN-NEXT:    v_and_b32_e32 v1, 0xffff0000, v0
; GCN-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v16i32_to_v32bf16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB10_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v15, vcc, 3, v15
; VI-NEXT:    v_add_u32_e32 v14, vcc, 3, v14
; VI-NEXT:    v_add_u32_e32 v13, vcc, 3, v13
; VI-NEXT:    v_add_u32_e32 v12, vcc, 3, v12
; VI-NEXT:    v_add_u32_e32 v11, vcc, 3, v11
; VI-NEXT:    v_add_u32_e32 v10, vcc, 3, v10
; VI-NEXT:    v_add_u32_e32 v9, vcc, 3, v9
; VI-NEXT:    v_add_u32_e32 v8, vcc, 3, v8
; VI-NEXT:    v_add_u32_e32 v7, vcc, 3, v7
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_add_u32_e32 v5, vcc, 3, v5
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_add_u32_e32 v3, vcc, 3, v3
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_add_u32_e32 v1, vcc, 3, v1
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:  .LBB10_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v16i32_to_v32bf16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB10_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_u32_e32 v15, 3, v15
; GFX9-NEXT:    v_add_u32_e32 v14, 3, v14
; GFX9-NEXT:    v_add_u32_e32 v13, 3, v13
; GFX9-NEXT:    v_add_u32_e32 v12, 3, v12
; GFX9-NEXT:    v_add_u32_e32 v11, 3, v11
; GFX9-NEXT:    v_add_u32_e32 v10, 3, v10
; GFX9-NEXT:    v_add_u32_e32 v9, 3, v9
; GFX9-NEXT:    v_add_u32_e32 v8, 3, v8
; GFX9-NEXT:    v_add_u32_e32 v7, 3, v7
; GFX9-NEXT:    v_add_u32_e32 v6, 3, v6
; GFX9-NEXT:    v_add_u32_e32 v5, 3, v5
; GFX9-NEXT:    v_add_u32_e32 v4, 3, v4
; GFX9-NEXT:    v_add_u32_e32 v3, 3, v3
; GFX9-NEXT:    v_add_u32_e32 v2, 3, v2
; GFX9-NEXT:    v_add_u32_e32 v1, 3, v1
; GFX9-NEXT:    v_add_u32_e32 v0, 3, v0
; GFX9-NEXT:  .LBB10_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v16i32_to_v32bf16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB10_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_nc_u32_e32 v15, 3, v15
; GFX11-NEXT:    v_add_nc_u32_e32 v14, 3, v14
; GFX11-NEXT:    v_add_nc_u32_e32 v13, 3, v13
; GFX11-NEXT:    v_add_nc_u32_e32 v12, 3, v12
; GFX11-NEXT:    v_add_nc_u32_e32 v11, 3, v11
; GFX11-NEXT:    v_add_nc_u32_e32 v10, 3, v10
; GFX11-NEXT:    v_add_nc_u32_e32 v9, 3, v9
; GFX11-NEXT:    v_add_nc_u32_e32 v8, 3, v8
; GFX11-NEXT:    v_add_nc_u32_e32 v7, 3, v7
; GFX11-NEXT:    v_add_nc_u32_e32 v6, 3, v6
; GFX11-NEXT:    v_add_nc_u32_e32 v5, 3, v5
; GFX11-NEXT:    v_add_nc_u32_e32 v4, 3, v4
; GFX11-NEXT:    v_add_nc_u32_e32 v3, 3, v3
; GFX11-NEXT:    v_add_nc_u32_e32 v2, 3, v2
; GFX11-NEXT:    v_add_nc_u32_e32 v1, 3, v1
; GFX11-NEXT:    v_add_nc_u32_e32 v0, 3, v0
; GFX11-NEXT:  .LBB10_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <16 x i32> %a, splat (i32 3)
  %a2 = bitcast <16 x i32> %a1 to <32 x bfloat>
  br label %end

cmp.false:
  %a3 = bitcast <16 x i32> %a to <32 x bfloat>
  br label %end

end:
  %phi = phi <32 x bfloat> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x bfloat> %phi
}

define <16 x i32> @v_bitcast_v32bf16_to_v16i32(<32 x bfloat> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v32bf16_to_v16i32:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GCN-NEXT:    s_waitcnt expcnt(1)
; GCN-NEXT:    buffer_load_dword v46, off, s[0:3], s32
; GCN-NEXT:    s_waitcnt expcnt(0)
; GCN-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:4
; GCN-NEXT:    v_mul_f32_e32 v44, 1.0, v1
; GCN-NEXT:    v_mul_f32_e32 v45, 1.0, v0
; GCN-NEXT:    v_mul_f32_e32 v42, 1.0, v3
; GCN-NEXT:    v_mul_f32_e32 v43, 1.0, v2
; GCN-NEXT:    v_mul_f32_e32 v41, 1.0, v5
; GCN-NEXT:    v_mul_f32_e32 v51, 1.0, v4
; GCN-NEXT:    v_mul_f32_e32 v40, 1.0, v7
; GCN-NEXT:    v_mul_f32_e32 v49, 1.0, v6
; GCN-NEXT:    v_mul_f32_e32 v55, 1.0, v9
; GCN-NEXT:    v_mul_f32_e32 v39, 1.0, v8
; GCN-NEXT:    v_mul_f32_e32 v54, 1.0, v11
; GCN-NEXT:    v_mul_f32_e32 v37, 1.0, v10
; GCN-NEXT:    v_mul_f32_e32 v53, 1.0, v13
; GCN-NEXT:    v_mul_f32_e32 v36, 1.0, v12
; GCN-NEXT:    v_mul_f32_e32 v52, 1.0, v15
; GCN-NEXT:    v_mul_f32_e32 v34, 1.0, v14
; GCN-NEXT:    v_mul_f32_e32 v50, 1.0, v17
; GCN-NEXT:    v_mul_f32_e32 v33, 1.0, v16
; GCN-NEXT:    v_mul_f32_e32 v48, 1.0, v19
; GCN-NEXT:    v_mul_f32_e32 v32, 1.0, v18
; GCN-NEXT:    v_mul_f32_e32 v38, 1.0, v21
; GCN-NEXT:    v_mul_f32_e32 v31, 1.0, v20
; GCN-NEXT:    v_mul_f32_e32 v35, 1.0, v23
; GCN-NEXT:    v_mul_f32_e32 v21, 1.0, v22
; GCN-NEXT:    v_mul_f32_e32 v25, 1.0, v25
; GCN-NEXT:    v_mul_f32_e32 v19, 1.0, v24
; GCN-NEXT:    v_mul_f32_e32 v23, 1.0, v27
; GCN-NEXT:    v_mul_f32_e32 v18, 1.0, v26
; GCN-NEXT:    v_mul_f32_e32 v22, 1.0, v29
; GCN-NEXT:    v_mul_f32_e32 v17, 1.0, v28
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v47
; GCN-NEXT:    v_mul_f32_e32 v20, 1.0, v46
; GCN-NEXT:    v_mul_f32_e32 v16, 1.0, v30
; GCN-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB11_2
; GCN-NEXT:  ; %bb.1: ; %cmp.false
; GCN-NEXT:    v_lshrrev_b32_e32 v0, 16, v44
; GCN-NEXT:    v_lshrrev_b32_e32 v1, 16, v42
; GCN-NEXT:    v_alignbit_b32 v0, v0, v45, 16
; GCN-NEXT:    v_alignbit_b32 v1, v1, v43, 16
; GCN-NEXT:    v_lshrrev_b32_e32 v2, 16, v41
; GCN-NEXT:    v_lshrrev_b32_e32 v3, 16, v40
; GCN-NEXT:    v_lshrrev_b32_e32 v4, 16, v55
; GCN-NEXT:    v_lshrrev_b32_e32 v5, 16, v54
; GCN-NEXT:    v_lshrrev_b32_e32 v6, 16, v53
; GCN-NEXT:    v_lshrrev_b32_e32 v7, 16, v52
; GCN-NEXT:    v_lshrrev_b32_e32 v8, 16, v50
; GCN-NEXT:    v_lshrrev_b32_e32 v9, 16, v48
; GCN-NEXT:    v_lshrrev_b32_e32 v10, 16, v38
; GCN-NEXT:    v_lshrrev_b32_e32 v11, 16, v35
; GCN-NEXT:    v_lshrrev_b32_e32 v12, 16, v25
; GCN-NEXT:    v_lshrrev_b32_e32 v13, 16, v23
; GCN-NEXT:    v_lshrrev_b32_e32 v14, 16, v22
; GCN-NEXT:    v_lshrrev_b32_e32 v15, 16, v20
; GCN-NEXT:    v_alignbit_b32 v2, v2, v51, 16
; GCN-NEXT:    v_alignbit_b32 v3, v3, v49, 16
; GCN-NEXT:    v_alignbit_b32 v4, v4, v39, 16
; GCN-NEXT:    v_alignbit_b32 v5, v5, v37, 16
; GCN-NEXT:    v_alignbit_b32 v6, v6, v36, 16
; GCN-NEXT:    v_alignbit_b32 v7, v7, v34, 16
; GCN-NEXT:    v_alignbit_b32 v8, v8, v33, 16
; GCN-NEXT:    v_alignbit_b32 v9, v9, v32, 16
; GCN-NEXT:    v_alignbit_b32 v10, v10, v31, 16
; GCN-NEXT:    v_alignbit_b32 v11, v11, v21, 16
; GCN-NEXT:    v_alignbit_b32 v12, v12, v19, 16
; GCN-NEXT:    v_alignbit_b32 v13, v13, v18, 16
; GCN-NEXT:    v_alignbit_b32 v14, v14, v17, 16
; GCN-NEXT:    v_alignbit_b32 v15, v15, v16, 16
; GCN-NEXT:    ; implicit-def: $vgpr44
; GCN-NEXT:    ; implicit-def: $vgpr45
; GCN-NEXT:    ; implicit-def: $vgpr42
; GCN-NEXT:    ; implicit-def: $vgpr43
; GCN-NEXT:    ; implicit-def: $vgpr41
; GCN-NEXT:    ; implicit-def: $vgpr51
; GCN-NEXT:    ; implicit-def: $vgpr40
; GCN-NEXT:    ; implicit-def: $vgpr49
; GCN-NEXT:    ; implicit-def: $vgpr55
; GCN-NEXT:    ; implicit-def: $vgpr39
; GCN-NEXT:    ; implicit-def: $vgpr54
; GCN-NEXT:    ; implicit-def: $vgpr37
; GCN-NEXT:    ; implicit-def: $vgpr53
; GCN-NEXT:    ; implicit-def: $vgpr36
; GCN-NEXT:    ; implicit-def: $vgpr52
; GCN-NEXT:    ; implicit-def: $vgpr34
; GCN-NEXT:    ; implicit-def: $vgpr50
; GCN-NEXT:    ; implicit-def: $vgpr33
; GCN-NEXT:    ; implicit-def: $vgpr48
; GCN-NEXT:    ; implicit-def: $vgpr32
; GCN-NEXT:    ; implicit-def: $vgpr38
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    ; implicit-def: $vgpr35
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr18
; GCN-NEXT:    ; implicit-def: $vgpr22
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr20
; GCN-NEXT:    ; implicit-def: $vgpr16
; GCN-NEXT:  .LBB11_2: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB11_4
; GCN-NEXT:  ; %bb.3: ; %cmp.true
; GCN-NEXT:    v_and_b32_e32 v0, 0xffff0000, v45
; GCN-NEXT:    v_and_b32_e32 v1, 0xffff0000, v44
; GCN-NEXT:    v_and_b32_e32 v2, 0xffff0000, v43
; GCN-NEXT:    v_and_b32_e32 v3, 0xffff0000, v42
; GCN-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; GCN-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GCN-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GCN-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GCN-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GCN-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; GCN-NEXT:    v_alignbit_b32 v0, v1, v0, 16
; GCN-NEXT:    v_alignbit_b32 v1, v3, v2, 16
; GCN-NEXT:    v_and_b32_e32 v2, 0xffff0000, v51
; GCN-NEXT:    v_and_b32_e32 v3, 0xffff0000, v41
; GCN-NEXT:    v_and_b32_e32 v4, 0xffff0000, v49
; GCN-NEXT:    v_and_b32_e32 v5, 0xffff0000, v40
; GCN-NEXT:    v_and_b32_e32 v6, 0xffff0000, v39
; GCN-NEXT:    v_and_b32_e32 v7, 0xffff0000, v55
; GCN-NEXT:    v_and_b32_e32 v8, 0xffff0000, v37
; GCN-NEXT:    v_and_b32_e32 v9, 0xffff0000, v54
; GCN-NEXT:    v_and_b32_e32 v10, 0xffff0000, v36
; GCN-NEXT:    v_and_b32_e32 v11, 0xffff0000, v53
; GCN-NEXT:    v_and_b32_e32 v12, 0xffff0000, v34
; GCN-NEXT:    v_and_b32_e32 v13, 0xffff0000, v52
; GCN-NEXT:    v_and_b32_e32 v14, 0xffff0000, v33
; GCN-NEXT:    v_and_b32_e32 v15, 0xffff0000, v50
; GCN-NEXT:    v_and_b32_e32 v24, 0xffff0000, v32
; GCN-NEXT:    v_and_b32_e32 v26, 0xffff0000, v48
; GCN-NEXT:    v_and_b32_e32 v27, 0xffff0000, v31
; GCN-NEXT:    v_and_b32_e32 v28, 0xffff0000, v38
; GCN-NEXT:    v_and_b32_e32 v21, 0xffff0000, v21
; GCN-NEXT:    v_and_b32_e32 v29, 0xffff0000, v35
; GCN-NEXT:    v_and_b32_e32 v19, 0xffff0000, v19
; GCN-NEXT:    v_and_b32_e32 v25, 0xffff0000, v25
; GCN-NEXT:    v_and_b32_e32 v18, 0xffff0000, v18
; GCN-NEXT:    v_and_b32_e32 v23, 0xffff0000, v23
; GCN-NEXT:    v_and_b32_e32 v17, 0xffff0000, v17
; GCN-NEXT:    v_and_b32_e32 v22, 0xffff0000, v22
; GCN-NEXT:    v_and_b32_e32 v16, 0xffff0000, v16
; GCN-NEXT:    v_and_b32_e32 v20, 0xffff0000, v20
; GCN-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GCN-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GCN-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; GCN-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GCN-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GCN-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GCN-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GCN-NEXT:    v_add_f32_e32 v9, 0x40c00000, v9
; GCN-NEXT:    v_add_f32_e32 v10, 0x40c00000, v10
; GCN-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; GCN-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; GCN-NEXT:    v_add_f32_e32 v13, 0x40c00000, v13
; GCN-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; GCN-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; GCN-NEXT:    v_add_f32_e32 v24, 0x40c00000, v24
; GCN-NEXT:    v_add_f32_e32 v26, 0x40c00000, v26
; GCN-NEXT:    v_add_f32_e32 v27, 0x40c00000, v27
; GCN-NEXT:    v_add_f32_e32 v28, 0x40c00000, v28
; GCN-NEXT:    v_add_f32_e32 v21, 0x40c00000, v21
; GCN-NEXT:    v_add_f32_e32 v29, 0x40c00000, v29
; GCN-NEXT:    v_add_f32_e32 v19, 0x40c00000, v19
; GCN-NEXT:    v_add_f32_e32 v25, 0x40c00000, v25
; GCN-NEXT:    v_add_f32_e32 v18, 0x40c00000, v18
; GCN-NEXT:    v_add_f32_e32 v23, 0x40c00000, v23
; GCN-NEXT:    v_add_f32_e32 v17, 0x40c00000, v17
; GCN-NEXT:    v_add_f32_e32 v22, 0x40c00000, v22
; GCN-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GCN-NEXT:    v_add_f32_e32 v20, 0x40c00000, v20
; GCN-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; GCN-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; GCN-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; GCN-NEXT:    v_lshrrev_b32_e32 v9, 16, v9
; GCN-NEXT:    v_lshrrev_b32_e32 v11, 16, v11
; GCN-NEXT:    v_lshrrev_b32_e32 v13, 16, v13
; GCN-NEXT:    v_lshrrev_b32_e32 v15, 16, v15
; GCN-NEXT:    v_lshrrev_b32_e32 v26, 16, v26
; GCN-NEXT:    v_lshrrev_b32_e32 v28, 16, v28
; GCN-NEXT:    v_lshrrev_b32_e32 v29, 16, v29
; GCN-NEXT:    v_lshrrev_b32_e32 v25, 16, v25
; GCN-NEXT:    v_lshrrev_b32_e32 v23, 16, v23
; GCN-NEXT:    v_lshrrev_b32_e32 v22, 16, v22
; GCN-NEXT:    v_lshrrev_b32_e32 v20, 16, v20
; GCN-NEXT:    v_alignbit_b32 v2, v3, v2, 16
; GCN-NEXT:    v_alignbit_b32 v3, v5, v4, 16
; GCN-NEXT:    v_alignbit_b32 v4, v7, v6, 16
; GCN-NEXT:    v_alignbit_b32 v5, v9, v8, 16
; GCN-NEXT:    v_alignbit_b32 v6, v11, v10, 16
; GCN-NEXT:    v_alignbit_b32 v7, v13, v12, 16
; GCN-NEXT:    v_alignbit_b32 v8, v15, v14, 16
; GCN-NEXT:    v_alignbit_b32 v9, v26, v24, 16
; GCN-NEXT:    v_alignbit_b32 v10, v28, v27, 16
; GCN-NEXT:    v_alignbit_b32 v11, v29, v21, 16
; GCN-NEXT:    v_alignbit_b32 v12, v25, v19, 16
; GCN-NEXT:    v_alignbit_b32 v13, v23, v18, 16
; GCN-NEXT:    v_alignbit_b32 v14, v22, v17, 16
; GCN-NEXT:    v_alignbit_b32 v15, v20, v16, 16
; GCN-NEXT:  .LBB11_4: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v32bf16_to_v16i32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB11_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v15
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, 0x7fff, v17
; VI-NEXT:    v_and_b32_e32 v15, 0xffff0000, v15
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v15, 16, 1
; VI-NEXT:    s_movk_i32 s6, 0x7fff
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v15
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v15
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v15, v15
; VI-NEXT:    v_cndmask_b32_e32 v15, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v15, 16, v15
; VI-NEXT:    v_alignbit_b32 v15, v15, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v14
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v14, 0xffff0000, v14
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v14, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v14
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v14
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v14, v14
; VI-NEXT:    v_cndmask_b32_e32 v14, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v14, 16, v14
; VI-NEXT:    v_alignbit_b32 v14, v14, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v13
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v13, 0xffff0000, v13
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v13, 0x40c00000, v13
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v13, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v13
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v13
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v13, v13
; VI-NEXT:    v_cndmask_b32_e32 v13, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v13, 16, v13
; VI-NEXT:    v_alignbit_b32 v13, v13, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v12
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v12, 0xffff0000, v12
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v12, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v12
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v12
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v12, v12
; VI-NEXT:    v_cndmask_b32_e32 v12, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v12, 16, v12
; VI-NEXT:    v_alignbit_b32 v12, v12, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v11
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v11, 0xffff0000, v11
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v11, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v11
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v11
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v11, v11
; VI-NEXT:    v_cndmask_b32_e32 v11, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v11, 16, v11
; VI-NEXT:    v_alignbit_b32 v11, v11, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v10
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v10, 0xffff0000, v10
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v10, 0x40c00000, v10
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v10, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v10
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v10
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v10, v10
; VI-NEXT:    v_cndmask_b32_e32 v10, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v10, 16, v10
; VI-NEXT:    v_alignbit_b32 v10, v10, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v9
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v9, 0xffff0000, v9
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v9, 0x40c00000, v9
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v9, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v9
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v9
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v9, v9
; VI-NEXT:    v_cndmask_b32_e32 v9, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v9, 16, v9
; VI-NEXT:    v_alignbit_b32 v9, v9, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v8
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v8, 0xffff0000, v8
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v8
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_cndmask_b32_e32 v8, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v8, 16, v8
; VI-NEXT:    v_alignbit_b32 v8, v8, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v7
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v7, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v7
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v7
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; VI-NEXT:    v_cndmask_b32_e32 v7, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; VI-NEXT:    v_alignbit_b32 v7, v7, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v6
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v6, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v6
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v6
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; VI-NEXT:    v_cndmask_b32_e32 v6, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_alignbit_b32 v6, v6, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v5
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v5, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v5
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v5
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; VI-NEXT:    v_cndmask_b32_e32 v5, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_alignbit_b32 v5, v5, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v4
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v4, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v4
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v4
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; VI-NEXT:    v_cndmask_b32_e32 v4, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_alignbit_b32 v4, v4, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v3
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v3
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_alignbit_b32 v3, v3, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v2
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v2
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_alignbit_b32 v2, v2, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v1
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v1, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v1
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v1
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; VI-NEXT:    v_cndmask_b32_e32 v1, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_alignbit_b32 v1, v1, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v0
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v0, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v0
; VI-NEXT:    v_add_u32_e32 v17, vcc, 0x7fff, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v0
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; VI-NEXT:    v_cndmask_b32_e32 v0, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; VI-NEXT:    v_alignbit_b32 v0, v0, v16, 16
; VI-NEXT:  .LBB11_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v32bf16_to_v16i32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB11_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v15
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    s_movk_i32 s6, 0x7fff
; GFX9-NEXT:    v_and_b32_e32 v15, 0xffff0000, v15
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v15, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v15, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v15
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v15, v15
; GFX9-NEXT:    v_cndmask_b32_e32 v15, v17, v18, vcc
; GFX9-NEXT:    s_mov_b32 s7, 0x7060302
; GFX9-NEXT:    v_perm_b32 v15, v15, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v14
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v14, 0xffff0000, v14
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v14, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v14, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v14
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v14, v14
; GFX9-NEXT:    v_cndmask_b32_e32 v14, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v14, v14, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v13
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v13, 0xffff0000, v13
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v13, 0x40c00000, v13
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v13, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v13, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v13
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v13, v13
; GFX9-NEXT:    v_cndmask_b32_e32 v13, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v13, v13, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v12
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v12, 0xffff0000, v12
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v12, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v12, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v12
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v12, v12
; GFX9-NEXT:    v_cndmask_b32_e32 v12, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v12, v12, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v11
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v11, 0xffff0000, v11
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v11, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v11, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v11
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v11, v11
; GFX9-NEXT:    v_cndmask_b32_e32 v11, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v11, v11, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v10
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v10, 0xffff0000, v10
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v10, 0x40c00000, v10
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v10, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v10, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v10
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v10, v10
; GFX9-NEXT:    v_cndmask_b32_e32 v10, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v10, v10, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v9
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v9, 0xffff0000, v9
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v9, 0x40c00000, v9
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v9, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v9, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v9
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v9, v9
; GFX9-NEXT:    v_cndmask_b32_e32 v9, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v9, v9, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v8
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v8, 0xffff0000, v8
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v8, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v8, v8, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v7
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v7, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v7, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v7
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; GFX9-NEXT:    v_cndmask_b32_e32 v7, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v7, v7, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v6
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v6, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v6, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v6
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; GFX9-NEXT:    v_cndmask_b32_e32 v6, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v6, v6, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v5
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v5, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v5, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v5, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v5, v5, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v4
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v4, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v4, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v4
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; GFX9-NEXT:    v_cndmask_b32_e32 v4, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v4, v4, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v3
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v3, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v3, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v3
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; GFX9-NEXT:    v_cndmask_b32_e32 v3, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v3, v3, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v2, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v2, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v2, v2, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v1
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v1, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v1, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v1, v1, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v0
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v0, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v0, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v0
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v0, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v0, v0, v16, s7
; GFX9-NEXT:  .LBB11_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v32bf16_to_v16i32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB11_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_lshlrev_b32_e32 v17, 16, v14
; GFX11-NEXT:    v_lshlrev_b32_e32 v16, 16, v15
; GFX11-NEXT:    v_and_b32_e32 v14, 0xffff0000, v14
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_dual_add_f32 v17, 0x40c00000, v17 :: v_dual_add_f32 v16, 0x40c00000, v16
; GFX11-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_bfe_u32 v21, v17, 16, 1
; GFX11-NEXT:    v_bfe_u32 v18, v16, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v19, 0x400000, v16
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_bfe_u32 v23, v14, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v16, v16
; GFX11-NEXT:    v_add3_u32 v21, v21, v17, 0x7fff
; GFX11-NEXT:    v_add3_u32 v18, v18, v16, 0x7fff
; GFX11-NEXT:    v_cndmask_b32_e32 v16, v18, v19, vcc_lo
; GFX11-NEXT:    v_add3_u32 v19, v23, v14, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v15, 0xffff0000, v15
; GFX11-NEXT:    v_or_b32_e32 v18, 0x400000, v17
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; GFX11-NEXT:    v_bfe_u32 v20, v15, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v15
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v15, v15
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add3_u32 v20, v20, v15, 0x7fff
; GFX11-NEXT:    v_dual_cndmask_b32 v15, v20, v22 :: v_dual_lshlrev_b32 v20, 16, v13
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v17, v17
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_perm_b32 v15, v15, v16, 0x7060302
; GFX11-NEXT:    v_dual_cndmask_b32 v17, v21, v18 :: v_dual_add_f32 v18, 0x40c00000, v20
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_bfe_u32 v16, v18, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v18
; GFX11-NEXT:    v_add3_u32 v16, v16, v18, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v13, 0xffff0000, v13
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_add_f32_e32 v13, 0x40c00000, v13
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v14
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v14, v14
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v13
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_dual_cndmask_b32 v14, v19, v22 :: v_dual_lshlrev_b32 v19, 16, v12
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-NEXT:    v_perm_b32 v14, v14, v17, 0x7060302
; GFX11-NEXT:    v_bfe_u32 v17, v13, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_dual_add_f32 v19, 0x40c00000, v19 :: v_dual_cndmask_b32 v16, v16, v20
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v13, v13
; GFX11-NEXT:    v_add3_u32 v17, v17, v13, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_bfe_u32 v22, v19, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v19
; GFX11-NEXT:    v_cndmask_b32_e32 v13, v17, v21, vcc_lo
; GFX11-NEXT:    v_lshlrev_b32_e32 v21, 16, v11
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_add3_u32 v17, v22, v19, 0x7fff
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v19, v19
; GFX11-NEXT:    v_perm_b32 v13, v13, v16, 0x7060302
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_add_f32_e32 v19, 0x40c00000, v21
; GFX11-NEXT:    v_cndmask_b32_e32 v17, v17, v20, vcc_lo
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_bfe_u32 v16, v19, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v19
; GFX11-NEXT:    v_add3_u32 v16, v16, v19, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v11, 0xffff0000, v11
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v11
; GFX11-NEXT:    v_and_b32_e32 v12, 0xffff0000, v12
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; GFX11-NEXT:    v_bfe_u32 v18, v12, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v12
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v12, v12
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add3_u32 v18, v18, v12, 0x7fff
; GFX11-NEXT:    v_cndmask_b32_e32 v12, v18, v22, vcc_lo
; GFX11-NEXT:    v_lshlrev_b32_e32 v18, 16, v10
; GFX11-NEXT:    v_and_b32_e32 v10, 0xffff0000, v10
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_perm_b32 v12, v12, v17, 0x7060302
; GFX11-NEXT:    v_bfe_u32 v17, v11, 16, 1
; GFX11-NEXT:    v_add_f32_e32 v18, 0x40c00000, v18
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_add_f32_e32 v10, 0x40c00000, v10
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v19, v19
; GFX11-NEXT:    v_add3_u32 v17, v17, v11, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_bfe_u32 v22, v18, 16, 1
; GFX11-NEXT:    v_bfe_u32 v19, v10, 16, 1
; GFX11-NEXT:    v_cndmask_b32_e32 v16, v16, v20, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v11, v11
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v18
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_4) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_add3_u32 v19, v19, v10, 0x7fff
; GFX11-NEXT:    v_cndmask_b32_e32 v11, v17, v21, vcc_lo
; GFX11-NEXT:    v_add3_u32 v17, v22, v18, 0x7fff
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v10
; GFX11-NEXT:    v_perm_b32 v11, v11, v16, 0x7060302
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_cndmask_b32_e32 v17, v17, v20, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-NEXT:    v_dual_cndmask_b32 v10, v19, v22 :: v_dual_lshlrev_b32 v21, 16, v9
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_dual_add_f32 v18, 0x40c00000, v21 :: v_dual_lshlrev_b32 v19, 16, v8
; GFX11-NEXT:    v_and_b32_e32 v8, 0xffff0000, v8
; GFX11-NEXT:    v_perm_b32 v10, v10, v17, 0x7060302
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_3) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_bfe_u32 v16, v18, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v18
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-NEXT:    v_dual_add_f32 v19, 0x40c00000, v19 :: v_dual_add_f32 v8, 0x40c00000, v8
; GFX11-NEXT:    v_add3_u32 v16, v16, v18, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v9, 0xffff0000, v9
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_bfe_u32 v22, v19, 16, 1
; GFX11-NEXT:    v_bfe_u32 v18, v8, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_dual_cndmask_b32 v16, v16, v20 :: v_dual_add_f32 v9, 0x40c00000, v9
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v19
; GFX11-NEXT:    v_add3_u32 v18, v18, v8, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_bfe_u32 v17, v9, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v9
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-NEXT:    v_add3_u32 v17, v17, v9, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_3) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_cndmask_b32_e32 v9, v17, v21, vcc_lo
; GFX11-NEXT:    v_add3_u32 v17, v22, v19, 0x7fff
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v19, v19
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v8
; GFX11-NEXT:    v_perm_b32 v9, v9, v16, 0x7060302
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_cndmask_b32_e32 v17, v17, v20, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-NEXT:    v_cndmask_b32_e32 v8, v18, v22, vcc_lo
; GFX11-NEXT:    v_lshlrev_b32_e32 v18, 16, v6
; GFX11-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; GFX11-NEXT:    v_lshlrev_b32_e32 v21, 16, v7
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_perm_b32 v8, v8, v17, 0x7060302
; GFX11-NEXT:    v_add_f32_e32 v18, 0x40c00000, v18
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_dual_add_f32 v6, 0x40c00000, v6 :: v_dual_add_f32 v19, 0x40c00000, v21
; GFX11-NEXT:    v_bfe_u32 v22, v18, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_bfe_u32 v16, v19, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v19
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v19, v19
; GFX11-NEXT:    v_add3_u32 v16, v16, v19, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; GFX11-NEXT:    v_bfe_u32 v19, v6, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_dual_cndmask_b32 v16, v16, v20 :: v_dual_add_f32 v7, 0x40c00000, v7
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v18
; GFX11-NEXT:    v_add3_u32 v19, v19, v6, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_bfe_u32 v17, v7, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v7
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-NEXT:    v_add3_u32 v17, v17, v7, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_4) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_cndmask_b32_e32 v7, v17, v21, vcc_lo
; GFX11-NEXT:    v_add3_u32 v17, v22, v18, 0x7fff
; GFX11-NEXT:    v_lshlrev_b32_e32 v21, 16, v5
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v6
; GFX11-NEXT:    v_dual_add_f32 v18, 0x40c00000, v21 :: v_dual_cndmask_b32 v17, v17, v20
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_bfe_u32 v20, v18, 16, 1
; GFX11-NEXT:    v_dual_cndmask_b32 v6, v19, v22 :: v_dual_lshlrev_b32 v19, 16, v4
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; GFX11-NEXT:    v_perm_b32 v7, v7, v16, 0x7060302
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_4) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_perm_b32 v6, v6, v17, 0x7060302
; GFX11-NEXT:    v_add_f32_e32 v17, 0x40c00000, v19
; GFX11-NEXT:    v_add3_u32 v19, v20, v18, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v18
; GFX11-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; GFX11-NEXT:    v_bfe_u32 v22, v17, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_4) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_cndmask_b32_e32 v18, v19, v20, vcc_lo
; GFX11-NEXT:    v_or_b32_e32 v19, 0x400000, v17
; GFX11-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; GFX11-NEXT:    v_lshlrev_b32_e32 v20, 16, v3
; GFX11-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; GFX11-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_bfe_u32 v16, v5, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v5
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-NEXT:    v_add3_u32 v16, v16, v5, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_cndmask_b32_e32 v5, v16, v21, vcc_lo
; GFX11-NEXT:    v_add3_u32 v16, v22, v17, 0x7fff
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v17, v17
; GFX11-NEXT:    v_perm_b32 v5, v5, v18, 0x7060302
; GFX11-NEXT:    v_bfe_u32 v18, v4, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_2) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_cndmask_b32_e32 v16, v16, v19, vcc_lo
; GFX11-NEXT:    v_or_b32_e32 v19, 0x400000, v4
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-NEXT:    v_add3_u32 v18, v18, v4, 0x7fff
; GFX11-NEXT:    v_dual_add_f32 v17, 0x40c00000, v20 :: v_dual_lshlrev_b32 v20, 16, v2
; GFX11-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_cndmask_b32_e32 v4, v18, v19, vcc_lo
; GFX11-NEXT:    v_bfe_u32 v21, v17, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-NEXT:    v_add_f32_e32 v18, 0x40c00000, v20
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v17
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v17, v17
; GFX11-NEXT:    v_perm_b32 v4, v4, v16, 0x7060302
; GFX11-NEXT:    v_add3_u32 v19, v21, v17, 0x7fff
; GFX11-NEXT:    v_bfe_u32 v21, v3, 16, 1
; GFX11-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; GFX11-NEXT:    v_bfe_u32 v22, v18, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v23, 0x400000, v18
; GFX11-NEXT:    v_cndmask_b32_e32 v17, v19, v20, vcc_lo
; GFX11-NEXT:    v_add3_u32 v19, v21, v3, 0x7fff
; GFX11-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v3
; GFX11-NEXT:    v_add3_u32 v21, v22, v18, 0x7fff
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-NEXT:    v_lshlrev_b32_e32 v22, 16, v1
; GFX11-NEXT:    v_bfe_u32 v24, v2, 16, 1
; GFX11-NEXT:    v_cndmask_b32_e32 v3, v19, v20, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_add_f32_e32 v19, 0x40c00000, v22
; GFX11-NEXT:    v_add3_u32 v20, v24, v2, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_4) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_perm_b32 v3, v3, v17, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v18, v21, v23, vcc_lo
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v2
; GFX11-NEXT:    v_bfe_u32 v22, v19, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-NEXT:    v_dual_cndmask_b32 v2, v20, v21 :: v_dual_lshlrev_b32 v23, 16, v0
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-NEXT:    v_add3_u32 v21, v22, v19, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v19
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v19, v19
; GFX11-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX11-NEXT:    v_add_f32_e32 v20, 0x40c00000, v23
; GFX11-NEXT:    v_perm_b32 v2, v2, v18, 0x7060302
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_dual_cndmask_b32 v19, v21, v22 :: v_dual_add_f32 v0, 0x40c00000, v0
; GFX11-NEXT:    v_bfe_u32 v24, v20, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v25, 0x400000, v20
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_bfe_u32 v21, v0, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v26, 0x400000, v0
; GFX11-NEXT:    v_add3_u32 v24, v24, v20, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add3_u32 v21, v21, v0, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; GFX11-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_bfe_u32 v23, v1, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-NEXT:    v_add3_u32 v22, v23, v1, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v23, 0x400000, v1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_cndmask_b32_e32 v1, v22, v23, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v20, v20
; GFX11-NEXT:    v_perm_b32 v1, v1, v19, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v20, v24, v25, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-NEXT:    v_cndmask_b32_e32 v0, v21, v26, vcc_lo
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-NEXT:    v_perm_b32 v0, v0, v20, 0x7060302
; GFX11-NEXT:  .LBB11_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <32 x bfloat> %a, splat (bfloat 0xR40C0)
  %a2 = bitcast <32 x bfloat> %a1 to <16 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <32 x bfloat> %a to <16 x i32>
  br label %end

end:
  %phi = phi <16 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x i32> %phi
}

define <8 x i64> @v_bitcast_v16f32_to_v8i64(<16 x float> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v16f32_to_v8i64:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB12_2
; GCN-NEXT:  ; %bb.1: ; %cmp.true
; GCN-NEXT:    v_add_f32_e32 v15, 1.0, v15
; GCN-NEXT:    v_add_f32_e32 v14, 1.0, v14
; GCN-NEXT:    v_add_f32_e32 v13, 1.0, v13
; GCN-NEXT:    v_add_f32_e32 v12, 1.0, v12
; GCN-NEXT:    v_add_f32_e32 v11, 1.0, v11
; GCN-NEXT:    v_add_f32_e32 v10, 1.0, v10
; GCN-NEXT:    v_add_f32_e32 v9, 1.0, v9
; GCN-NEXT:    v_add_f32_e32 v8, 1.0, v8
; GCN-NEXT:    v_add_f32_e32 v7, 1.0, v7
; GCN-NEXT:    v_add_f32_e32 v6, 1.0, v6
; GCN-NEXT:    v_add_f32_e32 v5, 1.0, v5
; GCN-NEXT:    v_add_f32_e32 v4, 1.0, v4
; GCN-NEXT:    v_add_f32_e32 v3, 1.0, v3
; GCN-NEXT:    v_add_f32_e32 v2, 1.0, v2
; GCN-NEXT:    v_add_f32_e32 v1, 1.0, v1
; GCN-NEXT:    v_add_f32_e32 v0, 1.0, v0
; GCN-NEXT:  .LBB12_2: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v16f32_to_v8i64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB12_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f32_e32 v15, 1.0, v15
; VI-NEXT:    v_add_f32_e32 v14, 1.0, v14
; VI-NEXT:    v_add_f32_e32 v13, 1.0, v13
; VI-NEXT:    v_add_f32_e32 v12, 1.0, v12
; VI-NEXT:    v_add_f32_e32 v11, 1.0, v11
; VI-NEXT:    v_add_f32_e32 v10, 1.0, v10
; VI-NEXT:    v_add_f32_e32 v9, 1.0, v9
; VI-NEXT:    v_add_f32_e32 v8, 1.0, v8
; VI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; VI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; VI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; VI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; VI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; VI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; VI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; VI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; VI-NEXT:  .LBB12_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v16f32_to_v8i64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB12_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e32 v15, 1.0, v15
; GFX9-NEXT:    v_add_f32_e32 v14, 1.0, v14
; GFX9-NEXT:    v_add_f32_e32 v13, 1.0, v13
; GFX9-NEXT:    v_add_f32_e32 v12, 1.0, v12
; GFX9-NEXT:    v_add_f32_e32 v11, 1.0, v11
; GFX9-NEXT:    v_add_f32_e32 v10, 1.0, v10
; GFX9-NEXT:    v_add_f32_e32 v9, 1.0, v9
; GFX9-NEXT:    v_add_f32_e32 v8, 1.0, v8
; GFX9-NEXT:    v_add_f32_e32 v7, 1.0, v7
; GFX9-NEXT:    v_add_f32_e32 v6, 1.0, v6
; GFX9-NEXT:    v_add_f32_e32 v5, 1.0, v5
; GFX9-NEXT:    v_add_f32_e32 v4, 1.0, v4
; GFX9-NEXT:    v_add_f32_e32 v3, 1.0, v3
; GFX9-NEXT:    v_add_f32_e32 v2, 1.0, v2
; GFX9-NEXT:    v_add_f32_e32 v1, 1.0, v1
; GFX9-NEXT:    v_add_f32_e32 v0, 1.0, v0
; GFX9-NEXT:  .LBB12_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v16f32_to_v8i64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB12_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_dual_add_f32 v15, 1.0, v15 :: v_dual_add_f32 v14, 1.0, v14
; GFX11-NEXT:    v_dual_add_f32 v13, 1.0, v13 :: v_dual_add_f32 v12, 1.0, v12
; GFX11-NEXT:    v_dual_add_f32 v11, 1.0, v11 :: v_dual_add_f32 v10, 1.0, v10
; GFX11-NEXT:    v_dual_add_f32 v9, 1.0, v9 :: v_dual_add_f32 v8, 1.0, v8
; GFX11-NEXT:    v_dual_add_f32 v7, 1.0, v7 :: v_dual_add_f32 v6, 1.0, v6
; GFX11-NEXT:    v_dual_add_f32 v5, 1.0, v5 :: v_dual_add_f32 v4, 1.0, v4
; GFX11-NEXT:    v_dual_add_f32 v3, 1.0, v3 :: v_dual_add_f32 v2, 1.0, v2
; GFX11-NEXT:    v_dual_add_f32 v1, 1.0, v1 :: v_dual_add_f32 v0, 1.0, v0
; GFX11-NEXT:  .LBB12_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <16 x float> %a1 to <8 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <16 x float> %a to <8 x i64>
  br label %end

end:
  %phi = phi <8 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x i64> %phi
}

define <16 x float> @v_bitcast_v8i64_to_v16f32(<8 x i64> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v8i64_to_v16f32:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB13_2
; GCN-NEXT:  ; %bb.1: ; %cmp.true
; GCN-NEXT:    v_add_i32_e32 v14, vcc, 3, v14
; GCN-NEXT:    v_addc_u32_e32 v15, vcc, 0, v15, vcc
; GCN-NEXT:    v_add_i32_e32 v12, vcc, 3, v12
; GCN-NEXT:    v_addc_u32_e32 v13, vcc, 0, v13, vcc
; GCN-NEXT:    v_add_i32_e32 v10, vcc, 3, v10
; GCN-NEXT:    v_addc_u32_e32 v11, vcc, 0, v11, vcc
; GCN-NEXT:    v_add_i32_e32 v8, vcc, 3, v8
; GCN-NEXT:    v_addc_u32_e32 v9, vcc, 0, v9, vcc
; GCN-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; GCN-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; GCN-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; GCN-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; GCN-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; GCN-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; GCN-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; GCN-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; GCN-NEXT:  .LBB13_2: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v8i64_to_v16f32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB13_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v14, vcc, 3, v14
; VI-NEXT:    v_addc_u32_e32 v15, vcc, 0, v15, vcc
; VI-NEXT:    v_add_u32_e32 v12, vcc, 3, v12
; VI-NEXT:    v_addc_u32_e32 v13, vcc, 0, v13, vcc
; VI-NEXT:    v_add_u32_e32 v10, vcc, 3, v10
; VI-NEXT:    v_addc_u32_e32 v11, vcc, 0, v11, vcc
; VI-NEXT:    v_add_u32_e32 v8, vcc, 3, v8
; VI-NEXT:    v_addc_u32_e32 v9, vcc, 0, v9, vcc
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-NEXT:  .LBB13_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v8i64_to_v16f32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB13_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_co_u32_e32 v14, vcc, 3, v14
; GFX9-NEXT:    v_addc_co_u32_e32 v15, vcc, 0, v15, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v12, vcc, 3, v12
; GFX9-NEXT:    v_addc_co_u32_e32 v13, vcc, 0, v13, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v10, vcc, 3, v10
; GFX9-NEXT:    v_addc_co_u32_e32 v11, vcc, 0, v11, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v8, vcc, 3, v8
; GFX9-NEXT:    v_addc_co_u32_e32 v9, vcc, 0, v9, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v6, vcc, 3, v6
; GFX9-NEXT:    v_addc_co_u32_e32 v7, vcc, 0, v7, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v4, vcc, 3, v4
; GFX9-NEXT:    v_addc_co_u32_e32 v5, vcc, 0, v5, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v2, vcc, 3, v2
; GFX9-NEXT:    v_addc_co_u32_e32 v3, vcc, 0, v3, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v0, vcc, 3, v0
; GFX9-NEXT:    v_addc_co_u32_e32 v1, vcc, 0, v1, vcc
; GFX9-NEXT:  .LBB13_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v8i64_to_v16f32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB13_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_co_u32 v14, vcc_lo, v14, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v15, vcc_lo, 0, v15, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v12, vcc_lo, v12, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v13, vcc_lo, 0, v13, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v10, vcc_lo, v10, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v11, vcc_lo, 0, v11, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v8, vcc_lo, v8, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v9, vcc_lo, 0, v9, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v6, vcc_lo, v6, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v7, vcc_lo, 0, v7, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v4, vcc_lo, v4, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v5, vcc_lo, 0, v5, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v2, vcc_lo, v2, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v3, vcc_lo, 0, v3, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v0, vcc_lo, v0, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, 0, v1, vcc_lo
; GFX11-NEXT:  .LBB13_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <8 x i64> %a, splat (i64 3)
  %a2 = bitcast <8 x i64> %a1 to <16 x float>
  br label %end

cmp.false:
  %a3 = bitcast <8 x i64> %a to <16 x float>
  br label %end

end:
  %phi = phi <16 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x float> %phi
}

define <8 x double> @v_bitcast_v16f32_to_v8f64(<16 x float> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v16f32_to_v8f64:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB14_2
; GCN-NEXT:  ; %bb.1: ; %cmp.true
; GCN-NEXT:    v_add_f32_e32 v15, 1.0, v15
; GCN-NEXT:    v_add_f32_e32 v14, 1.0, v14
; GCN-NEXT:    v_add_f32_e32 v13, 1.0, v13
; GCN-NEXT:    v_add_f32_e32 v12, 1.0, v12
; GCN-NEXT:    v_add_f32_e32 v11, 1.0, v11
; GCN-NEXT:    v_add_f32_e32 v10, 1.0, v10
; GCN-NEXT:    v_add_f32_e32 v9, 1.0, v9
; GCN-NEXT:    v_add_f32_e32 v8, 1.0, v8
; GCN-NEXT:    v_add_f32_e32 v7, 1.0, v7
; GCN-NEXT:    v_add_f32_e32 v6, 1.0, v6
; GCN-NEXT:    v_add_f32_e32 v5, 1.0, v5
; GCN-NEXT:    v_add_f32_e32 v4, 1.0, v4
; GCN-NEXT:    v_add_f32_e32 v3, 1.0, v3
; GCN-NEXT:    v_add_f32_e32 v2, 1.0, v2
; GCN-NEXT:    v_add_f32_e32 v1, 1.0, v1
; GCN-NEXT:    v_add_f32_e32 v0, 1.0, v0
; GCN-NEXT:  .LBB14_2: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v16f32_to_v8f64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB14_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f32_e32 v15, 1.0, v15
; VI-NEXT:    v_add_f32_e32 v14, 1.0, v14
; VI-NEXT:    v_add_f32_e32 v13, 1.0, v13
; VI-NEXT:    v_add_f32_e32 v12, 1.0, v12
; VI-NEXT:    v_add_f32_e32 v11, 1.0, v11
; VI-NEXT:    v_add_f32_e32 v10, 1.0, v10
; VI-NEXT:    v_add_f32_e32 v9, 1.0, v9
; VI-NEXT:    v_add_f32_e32 v8, 1.0, v8
; VI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; VI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; VI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; VI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; VI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; VI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; VI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; VI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; VI-NEXT:  .LBB14_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v16f32_to_v8f64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB14_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e32 v15, 1.0, v15
; GFX9-NEXT:    v_add_f32_e32 v14, 1.0, v14
; GFX9-NEXT:    v_add_f32_e32 v13, 1.0, v13
; GFX9-NEXT:    v_add_f32_e32 v12, 1.0, v12
; GFX9-NEXT:    v_add_f32_e32 v11, 1.0, v11
; GFX9-NEXT:    v_add_f32_e32 v10, 1.0, v10
; GFX9-NEXT:    v_add_f32_e32 v9, 1.0, v9
; GFX9-NEXT:    v_add_f32_e32 v8, 1.0, v8
; GFX9-NEXT:    v_add_f32_e32 v7, 1.0, v7
; GFX9-NEXT:    v_add_f32_e32 v6, 1.0, v6
; GFX9-NEXT:    v_add_f32_e32 v5, 1.0, v5
; GFX9-NEXT:    v_add_f32_e32 v4, 1.0, v4
; GFX9-NEXT:    v_add_f32_e32 v3, 1.0, v3
; GFX9-NEXT:    v_add_f32_e32 v2, 1.0, v2
; GFX9-NEXT:    v_add_f32_e32 v1, 1.0, v1
; GFX9-NEXT:    v_add_f32_e32 v0, 1.0, v0
; GFX9-NEXT:  .LBB14_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v16f32_to_v8f64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB14_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_dual_add_f32 v15, 1.0, v15 :: v_dual_add_f32 v14, 1.0, v14
; GFX11-NEXT:    v_dual_add_f32 v13, 1.0, v13 :: v_dual_add_f32 v12, 1.0, v12
; GFX11-NEXT:    v_dual_add_f32 v11, 1.0, v11 :: v_dual_add_f32 v10, 1.0, v10
; GFX11-NEXT:    v_dual_add_f32 v9, 1.0, v9 :: v_dual_add_f32 v8, 1.0, v8
; GFX11-NEXT:    v_dual_add_f32 v7, 1.0, v7 :: v_dual_add_f32 v6, 1.0, v6
; GFX11-NEXT:    v_dual_add_f32 v5, 1.0, v5 :: v_dual_add_f32 v4, 1.0, v4
; GFX11-NEXT:    v_dual_add_f32 v3, 1.0, v3 :: v_dual_add_f32 v2, 1.0, v2
; GFX11-NEXT:    v_dual_add_f32 v1, 1.0, v1 :: v_dual_add_f32 v0, 1.0, v0
; GFX11-NEXT:  .LBB14_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <16 x float> %a1 to <8 x double>
  br label %end

cmp.false:
  %a3 = bitcast <16 x float> %a to <8 x double>
  br label %end

end:
  %phi = phi <8 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x double> %phi
}

define <16 x float> @v_bitcast_v8f64_to_v16f32(<8 x double> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v8f64_to_v16f32:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB15_2
; GCN-NEXT:  ; %bb.1: ; %cmp.true
; GCN-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GCN-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GCN-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GCN-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GCN-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GCN-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GCN-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GCN-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GCN-NEXT:  .LBB15_2: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v8f64_to_v16f32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB15_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; VI-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; VI-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; VI-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; VI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; VI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; VI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; VI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; VI-NEXT:  .LBB15_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v8f64_to_v16f32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB15_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GFX9-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GFX9-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GFX9-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GFX9-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX9-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX9-NEXT:  .LBB15_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v8f64_to_v16f32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB15_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GFX11-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GFX11-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GFX11-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GFX11-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX11-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX11-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX11-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX11-NEXT:  .LBB15_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <8 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <8 x double> %a1 to <16 x float>
  br label %end

cmp.false:
  %a3 = bitcast <8 x double> %a to <16 x float>
  br label %end

end:
  %phi = phi <16 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x float> %phi
}

define <32 x i16> @v_bitcast_v16f32_to_v32i16(<16 x float> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v16f32_to_v32i16:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_mov_b32_e32 v30, v15
; GCN-NEXT:    v_mov_b32_e32 v28, v14
; GCN-NEXT:    v_mov_b32_e32 v26, v13
; GCN-NEXT:    v_mov_b32_e32 v24, v12
; GCN-NEXT:    v_mov_b32_e32 v22, v11
; GCN-NEXT:    v_mov_b32_e32 v20, v10
; GCN-NEXT:    v_mov_b32_e32 v18, v9
; GCN-NEXT:    v_mov_b32_e32 v32, v8
; GCN-NEXT:    v_mov_b32_e32 v14, v7
; GCN-NEXT:    v_mov_b32_e32 v12, v6
; GCN-NEXT:    v_mov_b32_e32 v10, v5
; GCN-NEXT:    v_mov_b32_e32 v8, v4
; GCN-NEXT:    v_mov_b32_e32 v6, v3
; GCN-NEXT:    v_mov_b32_e32 v4, v2
; GCN-NEXT:    v_mov_b32_e32 v2, v1
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GCN-NEXT:    ; implicit-def: $vgpr1
; GCN-NEXT:    ; implicit-def: $vgpr3
; GCN-NEXT:    ; implicit-def: $vgpr5
; GCN-NEXT:    ; implicit-def: $vgpr7
; GCN-NEXT:    ; implicit-def: $vgpr9
; GCN-NEXT:    ; implicit-def: $vgpr11
; GCN-NEXT:    ; implicit-def: $vgpr13
; GCN-NEXT:    ; implicit-def: $vgpr15
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr27
; GCN-NEXT:    ; implicit-def: $vgpr29
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB16_2
; GCN-NEXT:  ; %bb.1: ; %cmp.false
; GCN-NEXT:    v_alignbit_b32 v29, v30, v28, 16
; GCN-NEXT:    v_alignbit_b32 v25, v26, v24, 16
; GCN-NEXT:    v_alignbit_b32 v21, v22, v20, 16
; GCN-NEXT:    v_alignbit_b32 v17, v18, v32, 16
; GCN-NEXT:    v_alignbit_b32 v13, v14, v12, 16
; GCN-NEXT:    v_alignbit_b32 v9, v10, v8, 16
; GCN-NEXT:    v_alignbit_b32 v5, v6, v4, 16
; GCN-NEXT:    v_alignbit_b32 v1, v2, v0, 16
; GCN-NEXT:    v_lshrrev_b32_e32 v31, 16, v30
; GCN-NEXT:    v_lshrrev_b32_e32 v27, 16, v26
; GCN-NEXT:    v_lshrrev_b32_e32 v23, 16, v22
; GCN-NEXT:    v_lshrrev_b32_e32 v19, 16, v18
; GCN-NEXT:    v_lshrrev_b32_e32 v15, 16, v14
; GCN-NEXT:    v_lshrrev_b32_e32 v11, 16, v10
; GCN-NEXT:    v_lshrrev_b32_e32 v7, 16, v6
; GCN-NEXT:    v_lshrrev_b32_e32 v3, 16, v2
; GCN-NEXT:  .LBB16_2: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB16_4
; GCN-NEXT:  ; %bb.3: ; %cmp.true
; GCN-NEXT:    v_add_f32_e32 v2, 1.0, v2
; GCN-NEXT:    v_add_f32_e32 v0, 1.0, v0
; GCN-NEXT:    v_add_f32_e32 v6, 1.0, v6
; GCN-NEXT:    v_add_f32_e32 v4, 1.0, v4
; GCN-NEXT:    v_add_f32_e32 v10, 1.0, v10
; GCN-NEXT:    v_add_f32_e32 v8, 1.0, v8
; GCN-NEXT:    v_add_f32_e32 v14, 1.0, v14
; GCN-NEXT:    v_add_f32_e32 v12, 1.0, v12
; GCN-NEXT:    v_add_f32_e32 v18, 1.0, v18
; GCN-NEXT:    v_add_f32_e32 v32, 1.0, v32
; GCN-NEXT:    v_add_f32_e32 v22, 1.0, v22
; GCN-NEXT:    v_add_f32_e32 v20, 1.0, v20
; GCN-NEXT:    v_add_f32_e32 v26, 1.0, v26
; GCN-NEXT:    v_add_f32_e32 v24, 1.0, v24
; GCN-NEXT:    v_add_f32_e32 v30, 1.0, v30
; GCN-NEXT:    v_add_f32_e32 v28, 1.0, v28
; GCN-NEXT:    v_alignbit_b32 v29, v30, v28, 16
; GCN-NEXT:    v_alignbit_b32 v25, v26, v24, 16
; GCN-NEXT:    v_alignbit_b32 v21, v22, v20, 16
; GCN-NEXT:    v_alignbit_b32 v17, v18, v32, 16
; GCN-NEXT:    v_alignbit_b32 v13, v14, v12, 16
; GCN-NEXT:    v_alignbit_b32 v9, v10, v8, 16
; GCN-NEXT:    v_alignbit_b32 v5, v6, v4, 16
; GCN-NEXT:    v_alignbit_b32 v1, v2, v0, 16
; GCN-NEXT:    v_lshrrev_b32_e32 v31, 16, v30
; GCN-NEXT:    v_lshrrev_b32_e32 v27, 16, v26
; GCN-NEXT:    v_lshrrev_b32_e32 v23, 16, v22
; GCN-NEXT:    v_lshrrev_b32_e32 v19, 16, v18
; GCN-NEXT:    v_lshrrev_b32_e32 v15, 16, v14
; GCN-NEXT:    v_lshrrev_b32_e32 v11, 16, v10
; GCN-NEXT:    v_lshrrev_b32_e32 v7, 16, v6
; GCN-NEXT:    v_lshrrev_b32_e32 v3, 16, v2
; GCN-NEXT:  .LBB16_4: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    v_mov_b32_e32 v16, v32
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v16f32_to_v32i16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB16_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f32_e32 v15, 1.0, v15
; VI-NEXT:    v_add_f32_e32 v14, 1.0, v14
; VI-NEXT:    v_add_f32_e32 v13, 1.0, v13
; VI-NEXT:    v_add_f32_e32 v12, 1.0, v12
; VI-NEXT:    v_add_f32_e32 v11, 1.0, v11
; VI-NEXT:    v_add_f32_e32 v10, 1.0, v10
; VI-NEXT:    v_add_f32_e32 v9, 1.0, v9
; VI-NEXT:    v_add_f32_e32 v8, 1.0, v8
; VI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; VI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; VI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; VI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; VI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; VI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; VI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; VI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; VI-NEXT:  .LBB16_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v16f32_to_v32i16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB16_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e32 v15, 1.0, v15
; GFX9-NEXT:    v_add_f32_e32 v14, 1.0, v14
; GFX9-NEXT:    v_add_f32_e32 v13, 1.0, v13
; GFX9-NEXT:    v_add_f32_e32 v12, 1.0, v12
; GFX9-NEXT:    v_add_f32_e32 v11, 1.0, v11
; GFX9-NEXT:    v_add_f32_e32 v10, 1.0, v10
; GFX9-NEXT:    v_add_f32_e32 v9, 1.0, v9
; GFX9-NEXT:    v_add_f32_e32 v8, 1.0, v8
; GFX9-NEXT:    v_add_f32_e32 v7, 1.0, v7
; GFX9-NEXT:    v_add_f32_e32 v6, 1.0, v6
; GFX9-NEXT:    v_add_f32_e32 v5, 1.0, v5
; GFX9-NEXT:    v_add_f32_e32 v4, 1.0, v4
; GFX9-NEXT:    v_add_f32_e32 v3, 1.0, v3
; GFX9-NEXT:    v_add_f32_e32 v2, 1.0, v2
; GFX9-NEXT:    v_add_f32_e32 v1, 1.0, v1
; GFX9-NEXT:    v_add_f32_e32 v0, 1.0, v0
; GFX9-NEXT:  .LBB16_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v16f32_to_v32i16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB16_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_dual_add_f32 v15, 1.0, v15 :: v_dual_add_f32 v14, 1.0, v14
; GFX11-NEXT:    v_dual_add_f32 v13, 1.0, v13 :: v_dual_add_f32 v12, 1.0, v12
; GFX11-NEXT:    v_dual_add_f32 v11, 1.0, v11 :: v_dual_add_f32 v10, 1.0, v10
; GFX11-NEXT:    v_dual_add_f32 v9, 1.0, v9 :: v_dual_add_f32 v8, 1.0, v8
; GFX11-NEXT:    v_dual_add_f32 v7, 1.0, v7 :: v_dual_add_f32 v6, 1.0, v6
; GFX11-NEXT:    v_dual_add_f32 v5, 1.0, v5 :: v_dual_add_f32 v4, 1.0, v4
; GFX11-NEXT:    v_dual_add_f32 v3, 1.0, v3 :: v_dual_add_f32 v2, 1.0, v2
; GFX11-NEXT:    v_dual_add_f32 v1, 1.0, v1 :: v_dual_add_f32 v0, 1.0, v0
; GFX11-NEXT:  .LBB16_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <16 x float> %a1 to <32 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <16 x float> %a to <32 x i16>
  br label %end

end:
  %phi = phi <32 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x i16> %phi
}

define <16 x float> @v_bitcast_v32i16_to_v16f32(<32 x i16> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v32i16_to_v16f32:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_mov_b32_e32 v38, v14
; GCN-NEXT:    v_mov_b32_e32 v37, v12
; GCN-NEXT:    v_mov_b32_e32 v36, v10
; GCN-NEXT:    v_mov_b32_e32 v35, v8
; GCN-NEXT:    v_mov_b32_e32 v34, v6
; GCN-NEXT:    v_mov_b32_e32 v33, v4
; GCN-NEXT:    v_mov_b32_e32 v32, v2
; GCN-NEXT:    v_mov_b32_e32 v31, v0
; GCN-NEXT:    buffer_load_dword v0, off, s[0:3], s32
; GCN-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:4
; GCN-NEXT:    v_lshlrev_b32_e32 v54, 16, v1
; GCN-NEXT:    v_lshlrev_b32_e32 v55, 16, v3
; GCN-NEXT:    v_lshlrev_b32_e32 v39, 16, v5
; GCN-NEXT:    v_lshlrev_b32_e32 v48, 16, v7
; GCN-NEXT:    v_lshlrev_b32_e32 v49, 16, v9
; GCN-NEXT:    v_lshlrev_b32_e32 v50, 16, v11
; GCN-NEXT:    v_lshlrev_b32_e32 v51, 16, v13
; GCN-NEXT:    v_lshlrev_b32_e32 v52, 16, v15
; GCN-NEXT:    v_lshlrev_b32_e32 v17, 16, v17
; GCN-NEXT:    v_lshlrev_b32_e32 v19, 16, v19
; GCN-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; GCN-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; GCN-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; GCN-NEXT:    v_lshlrev_b32_e32 v27, 16, v27
; GCN-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v2
; GCN-NEXT:    v_lshlrev_b32_e32 v53, 16, v0
; GCN-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execnz .LBB17_3
; GCN-NEXT:  ; %bb.1: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execnz .LBB17_4
; GCN-NEXT:  .LBB17_2: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
; GCN-NEXT:  .LBB17_3: ; %cmp.false
; GCN-NEXT:    v_and_b32_e32 v0, 0xffff, v31
; GCN-NEXT:    v_and_b32_e32 v1, 0xffff, v32
; GCN-NEXT:    v_or_b32_e32 v0, v0, v54
; GCN-NEXT:    v_or_b32_e32 v1, v1, v55
; GCN-NEXT:    v_and_b32_e32 v2, 0xffff, v33
; GCN-NEXT:    v_and_b32_e32 v3, 0xffff, v34
; GCN-NEXT:    v_and_b32_e32 v4, 0xffff, v35
; GCN-NEXT:    v_and_b32_e32 v5, 0xffff, v36
; GCN-NEXT:    v_and_b32_e32 v6, 0xffff, v37
; GCN-NEXT:    v_and_b32_e32 v7, 0xffff, v38
; GCN-NEXT:    v_and_b32_e32 v8, 0xffff, v16
; GCN-NEXT:    v_and_b32_e32 v9, 0xffff, v18
; GCN-NEXT:    v_and_b32_e32 v10, 0xffff, v20
; GCN-NEXT:    v_and_b32_e32 v11, 0xffff, v22
; GCN-NEXT:    v_and_b32_e32 v12, 0xffff, v24
; GCN-NEXT:    v_and_b32_e32 v13, 0xffff, v26
; GCN-NEXT:    v_and_b32_e32 v14, 0xffff, v28
; GCN-NEXT:    v_and_b32_e32 v15, 0xffff, v30
; GCN-NEXT:    v_or_b32_e32 v2, v2, v39
; GCN-NEXT:    v_or_b32_e32 v3, v3, v48
; GCN-NEXT:    v_or_b32_e32 v4, v4, v49
; GCN-NEXT:    v_or_b32_e32 v5, v5, v50
; GCN-NEXT:    v_or_b32_e32 v6, v6, v51
; GCN-NEXT:    v_or_b32_e32 v7, v7, v52
; GCN-NEXT:    v_or_b32_e32 v8, v8, v17
; GCN-NEXT:    v_or_b32_e32 v9, v9, v19
; GCN-NEXT:    v_or_b32_e32 v10, v10, v21
; GCN-NEXT:    v_or_b32_e32 v11, v11, v23
; GCN-NEXT:    v_or_b32_e32 v12, v12, v25
; GCN-NEXT:    v_or_b32_e32 v13, v13, v27
; GCN-NEXT:    v_or_b32_e32 v14, v14, v29
; GCN-NEXT:    v_or_b32_e32 v15, v15, v53
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    ; implicit-def: $vgpr32
; GCN-NEXT:    ; implicit-def: $vgpr33
; GCN-NEXT:    ; implicit-def: $vgpr34
; GCN-NEXT:    ; implicit-def: $vgpr35
; GCN-NEXT:    ; implicit-def: $vgpr36
; GCN-NEXT:    ; implicit-def: $vgpr37
; GCN-NEXT:    ; implicit-def: $vgpr38
; GCN-NEXT:    ; implicit-def: $vgpr16
; GCN-NEXT:    ; implicit-def: $vgpr18
; GCN-NEXT:    ; implicit-def: $vgpr20
; GCN-NEXT:    ; implicit-def: $vgpr22
; GCN-NEXT:    ; implicit-def: $vgpr24
; GCN-NEXT:    ; implicit-def: $vgpr26
; GCN-NEXT:    ; implicit-def: $vgpr28
; GCN-NEXT:    ; implicit-def: $vgpr30
; GCN-NEXT:    ; implicit-def: $vgpr54
; GCN-NEXT:    ; implicit-def: $vgpr55
; GCN-NEXT:    ; implicit-def: $vgpr39
; GCN-NEXT:    ; implicit-def: $vgpr48
; GCN-NEXT:    ; implicit-def: $vgpr49
; GCN-NEXT:    ; implicit-def: $vgpr50
; GCN-NEXT:    ; implicit-def: $vgpr51
; GCN-NEXT:    ; implicit-def: $vgpr52
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr27
; GCN-NEXT:    ; implicit-def: $vgpr29
; GCN-NEXT:    ; implicit-def: $vgpr53
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB17_2
; GCN-NEXT:  .LBB17_4: ; %cmp.true
; GCN-NEXT:    v_add_i32_e32 v0, vcc, 3, v31
; GCN-NEXT:    s_mov_b32 s6, 0x30000
; GCN-NEXT:    v_add_i32_e32 v1, vcc, 3, v32
; GCN-NEXT:    v_add_i32_e32 v2, vcc, 3, v33
; GCN-NEXT:    v_add_i32_e32 v3, vcc, 3, v34
; GCN-NEXT:    v_add_i32_e32 v4, vcc, 3, v35
; GCN-NEXT:    v_add_i32_e32 v5, vcc, 3, v36
; GCN-NEXT:    v_add_i32_e32 v6, vcc, 3, v37
; GCN-NEXT:    v_add_i32_e32 v7, vcc, 3, v38
; GCN-NEXT:    v_add_i32_e32 v8, vcc, 3, v16
; GCN-NEXT:    v_add_i32_e32 v9, vcc, 3, v18
; GCN-NEXT:    v_add_i32_e32 v10, vcc, 3, v20
; GCN-NEXT:    v_add_i32_e32 v11, vcc, 3, v22
; GCN-NEXT:    v_add_i32_e32 v12, vcc, 3, v24
; GCN-NEXT:    v_add_i32_e32 v13, vcc, 3, v26
; GCN-NEXT:    v_add_i32_e32 v14, vcc, 3, v28
; GCN-NEXT:    v_add_i32_e32 v15, vcc, 3, v30
; GCN-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GCN-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; GCN-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GCN-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GCN-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GCN-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GCN-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; GCN-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; GCN-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; GCN-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; GCN-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; GCN-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; GCN-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; GCN-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; GCN-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; GCN-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; GCN-NEXT:    v_or_b32_e32 v0, v54, v0
; GCN-NEXT:    v_or_b32_e32 v1, v55, v1
; GCN-NEXT:    v_or_b32_e32 v2, v39, v2
; GCN-NEXT:    v_or_b32_e32 v3, v48, v3
; GCN-NEXT:    v_or_b32_e32 v4, v49, v4
; GCN-NEXT:    v_or_b32_e32 v5, v50, v5
; GCN-NEXT:    v_or_b32_e32 v6, v51, v6
; GCN-NEXT:    v_or_b32_e32 v7, v52, v7
; GCN-NEXT:    v_or_b32_e32 v8, v17, v8
; GCN-NEXT:    v_or_b32_e32 v9, v19, v9
; GCN-NEXT:    v_or_b32_e32 v10, v21, v10
; GCN-NEXT:    v_or_b32_e32 v11, v23, v11
; GCN-NEXT:    v_or_b32_e32 v12, v25, v12
; GCN-NEXT:    v_or_b32_e32 v13, v27, v13
; GCN-NEXT:    v_or_b32_e32 v14, v29, v14
; GCN-NEXT:    v_or_b32_e32 v15, v53, v15
; GCN-NEXT:    v_add_i32_e32 v0, vcc, 0x30000, v0
; GCN-NEXT:    v_add_i32_e32 v1, vcc, s6, v1
; GCN-NEXT:    v_add_i32_e32 v2, vcc, s6, v2
; GCN-NEXT:    v_add_i32_e32 v3, vcc, s6, v3
; GCN-NEXT:    v_add_i32_e32 v4, vcc, s6, v4
; GCN-NEXT:    v_add_i32_e32 v5, vcc, s6, v5
; GCN-NEXT:    v_add_i32_e32 v6, vcc, s6, v6
; GCN-NEXT:    v_add_i32_e32 v7, vcc, s6, v7
; GCN-NEXT:    v_add_i32_e32 v8, vcc, s6, v8
; GCN-NEXT:    v_add_i32_e32 v9, vcc, s6, v9
; GCN-NEXT:    v_add_i32_e32 v10, vcc, s6, v10
; GCN-NEXT:    v_add_i32_e32 v11, vcc, s6, v11
; GCN-NEXT:    v_add_i32_e32 v12, vcc, s6, v12
; GCN-NEXT:    v_add_i32_e32 v13, vcc, 0x30000, v13
; GCN-NEXT:    v_add_i32_e32 v14, vcc, 0x30000, v14
; GCN-NEXT:    v_add_i32_e32 v15, vcc, 0x30000, v15
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v32i16_to_v16f32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB17_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v17, 3
; VI-NEXT:    v_add_u16_e32 v16, 3, v15
; VI-NEXT:    v_add_u16_sdwa v15, v15, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v15, v16, v15
; VI-NEXT:    v_add_u16_e32 v16, 3, v14
; VI-NEXT:    v_add_u16_sdwa v14, v14, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v14, v16, v14
; VI-NEXT:    v_add_u16_e32 v16, 3, v13
; VI-NEXT:    v_add_u16_sdwa v13, v13, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v13, v16, v13
; VI-NEXT:    v_add_u16_e32 v16, 3, v12
; VI-NEXT:    v_add_u16_sdwa v12, v12, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v12, v16, v12
; VI-NEXT:    v_add_u16_e32 v16, 3, v11
; VI-NEXT:    v_add_u16_sdwa v11, v11, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v11, v16, v11
; VI-NEXT:    v_add_u16_e32 v16, 3, v10
; VI-NEXT:    v_add_u16_sdwa v10, v10, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v10, v16, v10
; VI-NEXT:    v_add_u16_e32 v16, 3, v9
; VI-NEXT:    v_add_u16_sdwa v9, v9, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v9, v16, v9
; VI-NEXT:    v_add_u16_e32 v16, 3, v8
; VI-NEXT:    v_add_u16_sdwa v8, v8, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v8, v16, v8
; VI-NEXT:    v_add_u16_e32 v16, 3, v7
; VI-NEXT:    v_add_u16_sdwa v7, v7, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v7, v16, v7
; VI-NEXT:    v_add_u16_e32 v16, 3, v6
; VI-NEXT:    v_add_u16_sdwa v6, v6, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v6, v16, v6
; VI-NEXT:    v_add_u16_e32 v16, 3, v5
; VI-NEXT:    v_add_u16_sdwa v5, v5, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v5, v16, v5
; VI-NEXT:    v_add_u16_e32 v16, 3, v4
; VI-NEXT:    v_add_u16_sdwa v4, v4, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v4, v16, v4
; VI-NEXT:    v_add_u16_e32 v16, 3, v3
; VI-NEXT:    v_add_u16_sdwa v3, v3, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v3, v16, v3
; VI-NEXT:    v_add_u16_e32 v16, 3, v2
; VI-NEXT:    v_add_u16_sdwa v2, v2, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v2, v16, v2
; VI-NEXT:    v_add_u16_e32 v16, 3, v1
; VI-NEXT:    v_add_u16_sdwa v1, v1, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v1, v16, v1
; VI-NEXT:    v_add_u16_e32 v16, 3, v0
; VI-NEXT:    v_add_u16_sdwa v0, v0, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v0, v16, v0
; VI-NEXT:  .LBB17_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v32i16_to_v16f32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB17_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_pk_add_u16 v15, v15, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v14, v14, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v13, v13, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v12, v12, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v9, v9, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v8, v8, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX9-NEXT:  .LBB17_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v32i16_to_v16f32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB17_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_pk_add_u16 v15, v15, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v14, v14, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v13, v13, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v12, v12, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v9, v9, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v8, v8, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX11-NEXT:  .LBB17_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <32 x i16> %a, splat (i16 3)
  %a2 = bitcast <32 x i16> %a1 to <16 x float>
  br label %end

cmp.false:
  %a3 = bitcast <32 x i16> %a to <16 x float>
  br label %end

end:
  %phi = phi <16 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x float> %phi
}

define <32 x half> @v_bitcast_v16f32_to_v32f16(<16 x float> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v16f32_to_v32f16:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v46, off, s[0:3], s32 ; 4-byte Folded Spill
; GCN-NEXT:    v_mov_b32_e32 v33, v15
; GCN-NEXT:    v_mov_b32_e32 v34, v14
; GCN-NEXT:    v_mov_b32_e32 v35, v13
; GCN-NEXT:    v_mov_b32_e32 v36, v12
; GCN-NEXT:    v_mov_b32_e32 v37, v11
; GCN-NEXT:    v_mov_b32_e32 v38, v10
; GCN-NEXT:    v_mov_b32_e32 v39, v9
; GCN-NEXT:    v_mov_b32_e32 v48, v8
; GCN-NEXT:    v_mov_b32_e32 v49, v7
; GCN-NEXT:    v_mov_b32_e32 v50, v6
; GCN-NEXT:    v_mov_b32_e32 v51, v5
; GCN-NEXT:    v_mov_b32_e32 v52, v4
; GCN-NEXT:    v_mov_b32_e32 v53, v3
; GCN-NEXT:    v_mov_b32_e32 v54, v2
; GCN-NEXT:    v_mov_b32_e32 v55, v1
; GCN-NEXT:    v_mov_b32_e32 v32, v0
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GCN-NEXT:    ; implicit-def: $vgpr0
; GCN-NEXT:    ; implicit-def: $vgpr1
; GCN-NEXT:    ; implicit-def: $vgpr2
; GCN-NEXT:    ; implicit-def: $vgpr3
; GCN-NEXT:    ; implicit-def: $vgpr4
; GCN-NEXT:    ; implicit-def: $vgpr5
; GCN-NEXT:    ; implicit-def: $vgpr6
; GCN-NEXT:    ; implicit-def: $vgpr7
; GCN-NEXT:    ; implicit-def: $vgpr8
; GCN-NEXT:    ; implicit-def: $vgpr9
; GCN-NEXT:    ; implicit-def: $vgpr10
; GCN-NEXT:    ; implicit-def: $vgpr11
; GCN-NEXT:    ; implicit-def: $vgpr12
; GCN-NEXT:    ; implicit-def: $vgpr13
; GCN-NEXT:    ; implicit-def: $vgpr14
; GCN-NEXT:    ; implicit-def: $vgpr15
; GCN-NEXT:    ; implicit-def: $vgpr16
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr18
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr20
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr22
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr24
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr26
; GCN-NEXT:    ; implicit-def: $vgpr27
; GCN-NEXT:    ; implicit-def: $vgpr28
; GCN-NEXT:    ; implicit-def: $vgpr29
; GCN-NEXT:    ; implicit-def: $vgpr30
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB18_2
; GCN-NEXT:  ; %bb.1: ; %cmp.false
; GCN-NEXT:    v_lshrrev_b32_e32 v0, 16, v33
; GCN-NEXT:    v_lshrrev_b32_e32 v1, 16, v34
; GCN-NEXT:    v_lshrrev_b32_e32 v3, 16, v35
; GCN-NEXT:    v_lshrrev_b32_e32 v5, 16, v36
; GCN-NEXT:    v_lshrrev_b32_e32 v7, 16, v37
; GCN-NEXT:    v_lshrrev_b32_e32 v9, 16, v38
; GCN-NEXT:    v_lshrrev_b32_e32 v11, 16, v39
; GCN-NEXT:    v_lshrrev_b32_e32 v13, 16, v48
; GCN-NEXT:    v_lshrrev_b32_e32 v15, 16, v49
; GCN-NEXT:    s_waitcnt expcnt(6)
; GCN-NEXT:    v_lshrrev_b32_e32 v40, 16, v50
; GCN-NEXT:    s_waitcnt expcnt(5)
; GCN-NEXT:    v_lshrrev_b32_e32 v41, 16, v51
; GCN-NEXT:    s_waitcnt expcnt(4)
; GCN-NEXT:    v_lshrrev_b32_e32 v42, 16, v52
; GCN-NEXT:    s_waitcnt expcnt(3)
; GCN-NEXT:    v_lshrrev_b32_e32 v43, 16, v53
; GCN-NEXT:    s_waitcnt expcnt(2)
; GCN-NEXT:    v_lshrrev_b32_e32 v44, 16, v54
; GCN-NEXT:    s_waitcnt expcnt(1)
; GCN-NEXT:    v_lshrrev_b32_e32 v45, 16, v55
; GCN-NEXT:    s_waitcnt expcnt(0)
; GCN-NEXT:    v_lshrrev_b32_e32 v46, 16, v32
; GCN-NEXT:    v_cvt_f32_f16_e32 v30, v33
; GCN-NEXT:    v_cvt_f32_f16_e32 v28, v34
; GCN-NEXT:    v_cvt_f32_f16_e32 v26, v35
; GCN-NEXT:    v_cvt_f32_f16_e32 v24, v36
; GCN-NEXT:    v_cvt_f32_f16_e32 v22, v37
; GCN-NEXT:    v_cvt_f32_f16_e32 v20, v38
; GCN-NEXT:    v_cvt_f32_f16_e32 v18, v39
; GCN-NEXT:    v_cvt_f32_f16_e32 v16, v48
; GCN-NEXT:    v_cvt_f32_f16_e32 v14, v49
; GCN-NEXT:    v_cvt_f32_f16_e32 v12, v50
; GCN-NEXT:    v_cvt_f32_f16_e32 v10, v51
; GCN-NEXT:    v_cvt_f32_f16_e32 v8, v52
; GCN-NEXT:    v_cvt_f32_f16_e32 v6, v53
; GCN-NEXT:    v_cvt_f32_f16_e32 v4, v54
; GCN-NEXT:    v_cvt_f32_f16_e32 v2, v55
; GCN-NEXT:    v_cvt_f32_f16_e32 v31, v0
; GCN-NEXT:    v_cvt_f32_f16_e32 v29, v1
; GCN-NEXT:    v_cvt_f32_f16_e32 v27, v3
; GCN-NEXT:    v_cvt_f32_f16_e32 v25, v5
; GCN-NEXT:    v_cvt_f32_f16_e32 v23, v7
; GCN-NEXT:    v_cvt_f32_f16_e32 v21, v9
; GCN-NEXT:    v_cvt_f32_f16_e32 v19, v11
; GCN-NEXT:    v_cvt_f32_f16_e32 v17, v13
; GCN-NEXT:    v_cvt_f32_f16_e32 v15, v15
; GCN-NEXT:    v_cvt_f32_f16_e32 v13, v40
; GCN-NEXT:    v_cvt_f32_f16_e32 v11, v41
; GCN-NEXT:    v_cvt_f32_f16_e32 v9, v42
; GCN-NEXT:    v_cvt_f32_f16_e32 v7, v43
; GCN-NEXT:    v_cvt_f32_f16_e32 v5, v44
; GCN-NEXT:    v_cvt_f32_f16_e32 v3, v45
; GCN-NEXT:    v_cvt_f32_f16_e32 v1, v46
; GCN-NEXT:    v_cvt_f32_f16_e32 v0, v32
; GCN-NEXT:    ; implicit-def: $vgpr32
; GCN-NEXT:    ; implicit-def: $vgpr55
; GCN-NEXT:    ; implicit-def: $vgpr54
; GCN-NEXT:    ; implicit-def: $vgpr53
; GCN-NEXT:    ; implicit-def: $vgpr52
; GCN-NEXT:    ; implicit-def: $vgpr51
; GCN-NEXT:    ; implicit-def: $vgpr50
; GCN-NEXT:    ; implicit-def: $vgpr49
; GCN-NEXT:    ; implicit-def: $vgpr48
; GCN-NEXT:    ; implicit-def: $vgpr39
; GCN-NEXT:    ; implicit-def: $vgpr38
; GCN-NEXT:    ; implicit-def: $vgpr37
; GCN-NEXT:    ; implicit-def: $vgpr36
; GCN-NEXT:    ; implicit-def: $vgpr35
; GCN-NEXT:    ; implicit-def: $vgpr34
; GCN-NEXT:    ; implicit-def: $vgpr33
; GCN-NEXT:  .LBB18_2: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB18_4
; GCN-NEXT:  ; %bb.3: ; %cmp.true
; GCN-NEXT:    v_add_f32_e32 v0, 1.0, v32
; GCN-NEXT:    v_add_f32_e32 v1, 1.0, v55
; GCN-NEXT:    v_add_f32_e32 v2, 1.0, v54
; GCN-NEXT:    v_add_f32_e32 v3, 1.0, v53
; GCN-NEXT:    v_add_f32_e32 v4, 1.0, v52
; GCN-NEXT:    v_add_f32_e32 v5, 1.0, v51
; GCN-NEXT:    v_add_f32_e32 v6, 1.0, v50
; GCN-NEXT:    v_add_f32_e32 v7, 1.0, v49
; GCN-NEXT:    v_add_f32_e32 v8, 1.0, v48
; GCN-NEXT:    v_add_f32_e32 v9, 1.0, v39
; GCN-NEXT:    v_add_f32_e32 v10, 1.0, v38
; GCN-NEXT:    v_add_f32_e32 v11, 1.0, v37
; GCN-NEXT:    v_add_f32_e32 v12, 1.0, v36
; GCN-NEXT:    v_add_f32_e32 v13, 1.0, v35
; GCN-NEXT:    v_add_f32_e32 v14, 1.0, v34
; GCN-NEXT:    v_add_f32_e32 v15, 1.0, v33
; GCN-NEXT:    v_lshrrev_b32_e32 v32, 16, v0
; GCN-NEXT:    v_lshrrev_b32_e32 v33, 16, v1
; GCN-NEXT:    v_lshrrev_b32_e32 v34, 16, v2
; GCN-NEXT:    v_lshrrev_b32_e32 v35, 16, v3
; GCN-NEXT:    v_lshrrev_b32_e32 v36, 16, v4
; GCN-NEXT:    v_lshrrev_b32_e32 v37, 16, v5
; GCN-NEXT:    v_lshrrev_b32_e32 v38, 16, v6
; GCN-NEXT:    v_lshrrev_b32_e32 v39, 16, v7
; GCN-NEXT:    v_lshrrev_b32_e32 v17, 16, v8
; GCN-NEXT:    v_lshrrev_b32_e32 v19, 16, v9
; GCN-NEXT:    v_lshrrev_b32_e32 v21, 16, v10
; GCN-NEXT:    v_lshrrev_b32_e32 v23, 16, v11
; GCN-NEXT:    v_lshrrev_b32_e32 v25, 16, v12
; GCN-NEXT:    v_lshrrev_b32_e32 v27, 16, v13
; GCN-NEXT:    v_lshrrev_b32_e32 v29, 16, v14
; GCN-NEXT:    v_lshrrev_b32_e32 v31, 16, v15
; GCN-NEXT:    v_cvt_f32_f16_e32 v30, v15
; GCN-NEXT:    v_cvt_f32_f16_e32 v28, v14
; GCN-NEXT:    v_cvt_f32_f16_e32 v26, v13
; GCN-NEXT:    v_cvt_f32_f16_e32 v24, v12
; GCN-NEXT:    v_cvt_f32_f16_e32 v22, v11
; GCN-NEXT:    v_cvt_f32_f16_e32 v20, v10
; GCN-NEXT:    v_cvt_f32_f16_e32 v18, v9
; GCN-NEXT:    v_cvt_f32_f16_e32 v16, v8
; GCN-NEXT:    v_cvt_f32_f16_e32 v14, v7
; GCN-NEXT:    v_cvt_f32_f16_e32 v12, v6
; GCN-NEXT:    v_cvt_f32_f16_e32 v10, v5
; GCN-NEXT:    v_cvt_f32_f16_e32 v8, v4
; GCN-NEXT:    v_cvt_f32_f16_e32 v6, v3
; GCN-NEXT:    v_cvt_f32_f16_e32 v4, v2
; GCN-NEXT:    v_cvt_f32_f16_e32 v2, v1
; GCN-NEXT:    v_cvt_f32_f16_e32 v0, v0
; GCN-NEXT:    v_cvt_f32_f16_e32 v31, v31
; GCN-NEXT:    v_cvt_f32_f16_e32 v29, v29
; GCN-NEXT:    v_cvt_f32_f16_e32 v27, v27
; GCN-NEXT:    v_cvt_f32_f16_e32 v25, v25
; GCN-NEXT:    v_cvt_f32_f16_e32 v23, v23
; GCN-NEXT:    v_cvt_f32_f16_e32 v21, v21
; GCN-NEXT:    v_cvt_f32_f16_e32 v19, v19
; GCN-NEXT:    v_cvt_f32_f16_e32 v17, v17
; GCN-NEXT:    v_cvt_f32_f16_e32 v15, v39
; GCN-NEXT:    v_cvt_f32_f16_e32 v13, v38
; GCN-NEXT:    v_cvt_f32_f16_e32 v11, v37
; GCN-NEXT:    v_cvt_f32_f16_e32 v9, v36
; GCN-NEXT:    v_cvt_f32_f16_e32 v7, v35
; GCN-NEXT:    v_cvt_f32_f16_e32 v5, v34
; GCN-NEXT:    v_cvt_f32_f16_e32 v3, v33
; GCN-NEXT:    v_cvt_f32_f16_e32 v1, v32
; GCN-NEXT:  .LBB18_4: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_waitcnt expcnt(0)
; GCN-NEXT:    buffer_load_dword v46, off, s[0:3], s32 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v16f32_to_v32f16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB18_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f32_e32 v15, 1.0, v15
; VI-NEXT:    v_add_f32_e32 v14, 1.0, v14
; VI-NEXT:    v_add_f32_e32 v13, 1.0, v13
; VI-NEXT:    v_add_f32_e32 v12, 1.0, v12
; VI-NEXT:    v_add_f32_e32 v11, 1.0, v11
; VI-NEXT:    v_add_f32_e32 v10, 1.0, v10
; VI-NEXT:    v_add_f32_e32 v9, 1.0, v9
; VI-NEXT:    v_add_f32_e32 v8, 1.0, v8
; VI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; VI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; VI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; VI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; VI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; VI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; VI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; VI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; VI-NEXT:  .LBB18_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v16f32_to_v32f16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB18_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e32 v15, 1.0, v15
; GFX9-NEXT:    v_add_f32_e32 v14, 1.0, v14
; GFX9-NEXT:    v_add_f32_e32 v13, 1.0, v13
; GFX9-NEXT:    v_add_f32_e32 v12, 1.0, v12
; GFX9-NEXT:    v_add_f32_e32 v11, 1.0, v11
; GFX9-NEXT:    v_add_f32_e32 v10, 1.0, v10
; GFX9-NEXT:    v_add_f32_e32 v9, 1.0, v9
; GFX9-NEXT:    v_add_f32_e32 v8, 1.0, v8
; GFX9-NEXT:    v_add_f32_e32 v7, 1.0, v7
; GFX9-NEXT:    v_add_f32_e32 v6, 1.0, v6
; GFX9-NEXT:    v_add_f32_e32 v5, 1.0, v5
; GFX9-NEXT:    v_add_f32_e32 v4, 1.0, v4
; GFX9-NEXT:    v_add_f32_e32 v3, 1.0, v3
; GFX9-NEXT:    v_add_f32_e32 v2, 1.0, v2
; GFX9-NEXT:    v_add_f32_e32 v1, 1.0, v1
; GFX9-NEXT:    v_add_f32_e32 v0, 1.0, v0
; GFX9-NEXT:  .LBB18_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v16f32_to_v32f16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB18_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_dual_add_f32 v15, 1.0, v15 :: v_dual_add_f32 v14, 1.0, v14
; GFX11-NEXT:    v_dual_add_f32 v13, 1.0, v13 :: v_dual_add_f32 v12, 1.0, v12
; GFX11-NEXT:    v_dual_add_f32 v11, 1.0, v11 :: v_dual_add_f32 v10, 1.0, v10
; GFX11-NEXT:    v_dual_add_f32 v9, 1.0, v9 :: v_dual_add_f32 v8, 1.0, v8
; GFX11-NEXT:    v_dual_add_f32 v7, 1.0, v7 :: v_dual_add_f32 v6, 1.0, v6
; GFX11-NEXT:    v_dual_add_f32 v5, 1.0, v5 :: v_dual_add_f32 v4, 1.0, v4
; GFX11-NEXT:    v_dual_add_f32 v3, 1.0, v3 :: v_dual_add_f32 v2, 1.0, v2
; GFX11-NEXT:    v_dual_add_f32 v1, 1.0, v1 :: v_dual_add_f32 v0, 1.0, v0
; GFX11-NEXT:  .LBB18_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <16 x float> %a1 to <32 x half>
  br label %end

cmp.false:
  %a3 = bitcast <16 x float> %a to <32 x half>
  br label %end

end:
  %phi = phi <32 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x half> %phi
}

define <16 x float> @v_bitcast_v32f16_to_v16f32(<32 x half> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v32f16_to_v16f32:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GCN-NEXT:    s_waitcnt expcnt(1)
; GCN-NEXT:    buffer_load_dword v46, off, s[0:3], s32
; GCN-NEXT:    s_waitcnt expcnt(0)
; GCN-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:4
; GCN-NEXT:    v_cvt_f16_f32_e32 v45, v1
; GCN-NEXT:    v_cvt_f16_f32_e32 v44, v0
; GCN-NEXT:    v_cvt_f16_f32_e32 v43, v3
; GCN-NEXT:    v_cvt_f16_f32_e32 v42, v2
; GCN-NEXT:    v_cvt_f16_f32_e32 v41, v5
; GCN-NEXT:    v_cvt_f16_f32_e32 v52, v4
; GCN-NEXT:    v_cvt_f16_f32_e32 v40, v7
; GCN-NEXT:    v_cvt_f16_f32_e32 v50, v6
; GCN-NEXT:    v_cvt_f16_f32_e32 v55, v9
; GCN-NEXT:    v_cvt_f16_f32_e32 v48, v8
; GCN-NEXT:    v_cvt_f16_f32_e32 v54, v11
; GCN-NEXT:    v_cvt_f16_f32_e32 v38, v10
; GCN-NEXT:    v_cvt_f16_f32_e32 v53, v13
; GCN-NEXT:    v_cvt_f16_f32_e32 v36, v12
; GCN-NEXT:    v_cvt_f16_f32_e32 v51, v15
; GCN-NEXT:    v_cvt_f16_f32_e32 v34, v14
; GCN-NEXT:    v_cvt_f16_f32_e32 v49, v17
; GCN-NEXT:    v_cvt_f16_f32_e32 v33, v16
; GCN-NEXT:    v_cvt_f16_f32_e32 v39, v19
; GCN-NEXT:    v_cvt_f16_f32_e32 v32, v18
; GCN-NEXT:    v_cvt_f16_f32_e32 v37, v21
; GCN-NEXT:    v_cvt_f16_f32_e32 v31, v20
; GCN-NEXT:    v_cvt_f16_f32_e32 v35, v23
; GCN-NEXT:    v_cvt_f16_f32_e32 v21, v22
; GCN-NEXT:    v_cvt_f16_f32_e32 v25, v25
; GCN-NEXT:    v_cvt_f16_f32_e32 v19, v24
; GCN-NEXT:    v_cvt_f16_f32_e32 v23, v27
; GCN-NEXT:    v_cvt_f16_f32_e32 v18, v26
; GCN-NEXT:    v_cvt_f16_f32_e32 v22, v29
; GCN-NEXT:    v_cvt_f16_f32_e32 v17, v28
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v47
; GCN-NEXT:    v_cvt_f16_f32_e32 v20, v46
; GCN-NEXT:    v_cvt_f16_f32_e32 v16, v30
; GCN-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB19_2
; GCN-NEXT:  ; %bb.1: ; %cmp.false
; GCN-NEXT:    v_lshlrev_b32_e32 v0, 16, v45
; GCN-NEXT:    v_lshlrev_b32_e32 v1, 16, v43
; GCN-NEXT:    v_or_b32_e32 v0, v44, v0
; GCN-NEXT:    v_or_b32_e32 v1, v42, v1
; GCN-NEXT:    v_lshlrev_b32_e32 v2, 16, v41
; GCN-NEXT:    v_lshlrev_b32_e32 v3, 16, v40
; GCN-NEXT:    v_lshlrev_b32_e32 v4, 16, v55
; GCN-NEXT:    v_lshlrev_b32_e32 v5, 16, v54
; GCN-NEXT:    v_lshlrev_b32_e32 v6, 16, v53
; GCN-NEXT:    v_lshlrev_b32_e32 v7, 16, v51
; GCN-NEXT:    v_lshlrev_b32_e32 v8, 16, v49
; GCN-NEXT:    v_lshlrev_b32_e32 v9, 16, v39
; GCN-NEXT:    v_lshlrev_b32_e32 v10, 16, v37
; GCN-NEXT:    v_lshlrev_b32_e32 v11, 16, v35
; GCN-NEXT:    v_lshlrev_b32_e32 v12, 16, v25
; GCN-NEXT:    v_lshlrev_b32_e32 v13, 16, v23
; GCN-NEXT:    v_lshlrev_b32_e32 v14, 16, v22
; GCN-NEXT:    v_lshlrev_b32_e32 v15, 16, v20
; GCN-NEXT:    v_or_b32_e32 v2, v52, v2
; GCN-NEXT:    v_or_b32_e32 v3, v50, v3
; GCN-NEXT:    v_or_b32_e32 v4, v48, v4
; GCN-NEXT:    v_or_b32_e32 v5, v38, v5
; GCN-NEXT:    v_or_b32_e32 v6, v36, v6
; GCN-NEXT:    v_or_b32_e32 v7, v34, v7
; GCN-NEXT:    v_or_b32_e32 v8, v33, v8
; GCN-NEXT:    v_or_b32_e32 v9, v32, v9
; GCN-NEXT:    v_or_b32_e32 v10, v31, v10
; GCN-NEXT:    v_or_b32_e32 v11, v21, v11
; GCN-NEXT:    v_or_b32_e32 v12, v19, v12
; GCN-NEXT:    v_or_b32_e32 v13, v18, v13
; GCN-NEXT:    v_or_b32_e32 v14, v17, v14
; GCN-NEXT:    v_or_b32_e32 v15, v16, v15
; GCN-NEXT:    ; implicit-def: $vgpr45
; GCN-NEXT:    ; implicit-def: $vgpr44
; GCN-NEXT:    ; implicit-def: $vgpr43
; GCN-NEXT:    ; implicit-def: $vgpr42
; GCN-NEXT:    ; implicit-def: $vgpr41
; GCN-NEXT:    ; implicit-def: $vgpr52
; GCN-NEXT:    ; implicit-def: $vgpr40
; GCN-NEXT:    ; implicit-def: $vgpr50
; GCN-NEXT:    ; implicit-def: $vgpr55
; GCN-NEXT:    ; implicit-def: $vgpr48
; GCN-NEXT:    ; implicit-def: $vgpr54
; GCN-NEXT:    ; implicit-def: $vgpr38
; GCN-NEXT:    ; implicit-def: $vgpr53
; GCN-NEXT:    ; implicit-def: $vgpr36
; GCN-NEXT:    ; implicit-def: $vgpr51
; GCN-NEXT:    ; implicit-def: $vgpr34
; GCN-NEXT:    ; implicit-def: $vgpr49
; GCN-NEXT:    ; implicit-def: $vgpr33
; GCN-NEXT:    ; implicit-def: $vgpr39
; GCN-NEXT:    ; implicit-def: $vgpr32
; GCN-NEXT:    ; implicit-def: $vgpr37
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    ; implicit-def: $vgpr35
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr18
; GCN-NEXT:    ; implicit-def: $vgpr22
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr20
; GCN-NEXT:    ; implicit-def: $vgpr16
; GCN-NEXT:  .LBB19_2: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB19_4
; GCN-NEXT:  ; %bb.3: ; %cmp.true
; GCN-NEXT:    v_cvt_f32_f16_e32 v0, v45
; GCN-NEXT:    v_cvt_f32_f16_e32 v1, v44
; GCN-NEXT:    v_cvt_f32_f16_e32 v2, v43
; GCN-NEXT:    v_cvt_f32_f16_e32 v3, v42
; GCN-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; GCN-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; GCN-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; GCN-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; GCN-NEXT:    v_cvt_f16_f32_e32 v0, v0
; GCN-NEXT:    v_cvt_f16_f32_e32 v1, v1
; GCN-NEXT:    v_cvt_f16_f32_e32 v2, v2
; GCN-NEXT:    v_cvt_f16_f32_e32 v3, v3
; GCN-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; GCN-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; GCN-NEXT:    v_or_b32_e32 v0, v1, v0
; GCN-NEXT:    v_or_b32_e32 v1, v3, v2
; GCN-NEXT:    v_cvt_f32_f16_e32 v2, v41
; GCN-NEXT:    v_cvt_f32_f16_e32 v3, v52
; GCN-NEXT:    v_cvt_f32_f16_e32 v4, v40
; GCN-NEXT:    v_cvt_f32_f16_e32 v5, v50
; GCN-NEXT:    v_cvt_f32_f16_e32 v6, v55
; GCN-NEXT:    v_cvt_f32_f16_e32 v7, v48
; GCN-NEXT:    v_cvt_f32_f16_e32 v8, v54
; GCN-NEXT:    v_cvt_f32_f16_e32 v9, v38
; GCN-NEXT:    v_cvt_f32_f16_e32 v10, v53
; GCN-NEXT:    v_cvt_f32_f16_e32 v11, v36
; GCN-NEXT:    v_cvt_f32_f16_e32 v12, v51
; GCN-NEXT:    v_cvt_f32_f16_e32 v13, v34
; GCN-NEXT:    v_cvt_f32_f16_e32 v14, v49
; GCN-NEXT:    v_cvt_f32_f16_e32 v15, v33
; GCN-NEXT:    v_cvt_f32_f16_e32 v24, v39
; GCN-NEXT:    v_cvt_f32_f16_e32 v26, v32
; GCN-NEXT:    v_cvt_f32_f16_e32 v27, v37
; GCN-NEXT:    v_cvt_f32_f16_e32 v28, v31
; GCN-NEXT:    v_cvt_f32_f16_e32 v29, v35
; GCN-NEXT:    v_cvt_f32_f16_e32 v21, v21
; GCN-NEXT:    v_cvt_f32_f16_e32 v25, v25
; GCN-NEXT:    v_cvt_f32_f16_e32 v19, v19
; GCN-NEXT:    v_cvt_f32_f16_e32 v23, v23
; GCN-NEXT:    v_cvt_f32_f16_e32 v18, v18
; GCN-NEXT:    v_cvt_f32_f16_e32 v22, v22
; GCN-NEXT:    v_cvt_f32_f16_e32 v17, v17
; GCN-NEXT:    v_cvt_f32_f16_e32 v20, v20
; GCN-NEXT:    v_cvt_f32_f16_e32 v16, v16
; GCN-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; GCN-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; GCN-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; GCN-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; GCN-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; GCN-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; GCN-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; GCN-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; GCN-NEXT:    v_add_f32_e32 v10, 0x38000000, v10
; GCN-NEXT:    v_add_f32_e32 v11, 0x38000000, v11
; GCN-NEXT:    v_add_f32_e32 v12, 0x38000000, v12
; GCN-NEXT:    v_add_f32_e32 v13, 0x38000000, v13
; GCN-NEXT:    v_add_f32_e32 v14, 0x38000000, v14
; GCN-NEXT:    v_add_f32_e32 v15, 0x38000000, v15
; GCN-NEXT:    v_add_f32_e32 v24, 0x38000000, v24
; GCN-NEXT:    v_add_f32_e32 v26, 0x38000000, v26
; GCN-NEXT:    v_add_f32_e32 v27, 0x38000000, v27
; GCN-NEXT:    v_add_f32_e32 v28, 0x38000000, v28
; GCN-NEXT:    v_add_f32_e32 v29, 0x38000000, v29
; GCN-NEXT:    v_add_f32_e32 v21, 0x38000000, v21
; GCN-NEXT:    v_add_f32_e32 v25, 0x38000000, v25
; GCN-NEXT:    v_add_f32_e32 v19, 0x38000000, v19
; GCN-NEXT:    v_add_f32_e32 v23, 0x38000000, v23
; GCN-NEXT:    v_add_f32_e32 v18, 0x38000000, v18
; GCN-NEXT:    v_add_f32_e32 v22, 0x38000000, v22
; GCN-NEXT:    v_add_f32_e32 v17, 0x38000000, v17
; GCN-NEXT:    v_add_f32_e32 v20, 0x38000000, v20
; GCN-NEXT:    v_add_f32_e32 v16, 0x38000000, v16
; GCN-NEXT:    v_cvt_f16_f32_e32 v2, v2
; GCN-NEXT:    v_cvt_f16_f32_e32 v3, v3
; GCN-NEXT:    v_cvt_f16_f32_e32 v4, v4
; GCN-NEXT:    v_cvt_f16_f32_e32 v5, v5
; GCN-NEXT:    v_cvt_f16_f32_e32 v6, v6
; GCN-NEXT:    v_cvt_f16_f32_e32 v7, v7
; GCN-NEXT:    v_cvt_f16_f32_e32 v8, v8
; GCN-NEXT:    v_cvt_f16_f32_e32 v9, v9
; GCN-NEXT:    v_cvt_f16_f32_e32 v10, v10
; GCN-NEXT:    v_cvt_f16_f32_e32 v11, v11
; GCN-NEXT:    v_cvt_f16_f32_e32 v12, v12
; GCN-NEXT:    v_cvt_f16_f32_e32 v13, v13
; GCN-NEXT:    v_cvt_f16_f32_e32 v14, v14
; GCN-NEXT:    v_cvt_f16_f32_e32 v15, v15
; GCN-NEXT:    v_cvt_f16_f32_e32 v24, v24
; GCN-NEXT:    v_cvt_f16_f32_e32 v26, v26
; GCN-NEXT:    v_cvt_f16_f32_e32 v27, v27
; GCN-NEXT:    v_cvt_f16_f32_e32 v28, v28
; GCN-NEXT:    v_cvt_f16_f32_e32 v29, v29
; GCN-NEXT:    v_cvt_f16_f32_e32 v21, v21
; GCN-NEXT:    v_cvt_f16_f32_e32 v25, v25
; GCN-NEXT:    v_cvt_f16_f32_e32 v19, v19
; GCN-NEXT:    v_cvt_f16_f32_e32 v23, v23
; GCN-NEXT:    v_cvt_f16_f32_e32 v18, v18
; GCN-NEXT:    v_cvt_f16_f32_e32 v22, v22
; GCN-NEXT:    v_cvt_f16_f32_e32 v17, v17
; GCN-NEXT:    v_cvt_f16_f32_e32 v20, v20
; GCN-NEXT:    v_cvt_f16_f32_e32 v16, v16
; GCN-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; GCN-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GCN-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GCN-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; GCN-NEXT:    v_lshlrev_b32_e32 v10, 16, v10
; GCN-NEXT:    v_lshlrev_b32_e32 v12, 16, v12
; GCN-NEXT:    v_lshlrev_b32_e32 v14, 16, v14
; GCN-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; GCN-NEXT:    v_lshlrev_b32_e32 v27, 16, v27
; GCN-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; GCN-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; GCN-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; GCN-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; GCN-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; GCN-NEXT:    v_or_b32_e32 v2, v3, v2
; GCN-NEXT:    v_or_b32_e32 v3, v5, v4
; GCN-NEXT:    v_or_b32_e32 v4, v7, v6
; GCN-NEXT:    v_or_b32_e32 v5, v9, v8
; GCN-NEXT:    v_or_b32_e32 v6, v11, v10
; GCN-NEXT:    v_or_b32_e32 v7, v13, v12
; GCN-NEXT:    v_or_b32_e32 v8, v15, v14
; GCN-NEXT:    v_or_b32_e32 v9, v26, v24
; GCN-NEXT:    v_or_b32_e32 v10, v28, v27
; GCN-NEXT:    v_or_b32_e32 v11, v21, v29
; GCN-NEXT:    v_or_b32_e32 v12, v19, v25
; GCN-NEXT:    v_or_b32_e32 v13, v18, v23
; GCN-NEXT:    v_or_b32_e32 v14, v17, v22
; GCN-NEXT:    v_or_b32_e32 v15, v16, v20
; GCN-NEXT:  .LBB19_4: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v32f16_to_v16f32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB19_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v16, 0x200
; VI-NEXT:    v_add_f16_sdwa v17, v15, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v15, 0x200, v15
; VI-NEXT:    v_or_b32_e32 v15, v15, v17
; VI-NEXT:    v_add_f16_sdwa v17, v14, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v14, 0x200, v14
; VI-NEXT:    v_or_b32_e32 v14, v14, v17
; VI-NEXT:    v_add_f16_sdwa v17, v13, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v13, 0x200, v13
; VI-NEXT:    v_or_b32_e32 v13, v13, v17
; VI-NEXT:    v_add_f16_sdwa v17, v12, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v12, 0x200, v12
; VI-NEXT:    v_or_b32_e32 v12, v12, v17
; VI-NEXT:    v_add_f16_sdwa v17, v11, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v11, 0x200, v11
; VI-NEXT:    v_or_b32_e32 v11, v11, v17
; VI-NEXT:    v_add_f16_sdwa v17, v10, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v10, 0x200, v10
; VI-NEXT:    v_or_b32_e32 v10, v10, v17
; VI-NEXT:    v_add_f16_sdwa v17, v9, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v9, 0x200, v9
; VI-NEXT:    v_or_b32_e32 v9, v9, v17
; VI-NEXT:    v_add_f16_sdwa v17, v8, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v8, 0x200, v8
; VI-NEXT:    v_or_b32_e32 v8, v8, v17
; VI-NEXT:    v_add_f16_sdwa v17, v7, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v7, 0x200, v7
; VI-NEXT:    v_or_b32_e32 v7, v7, v17
; VI-NEXT:    v_add_f16_sdwa v17, v6, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v6, 0x200, v6
; VI-NEXT:    v_or_b32_e32 v6, v6, v17
; VI-NEXT:    v_add_f16_sdwa v17, v5, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v5, 0x200, v5
; VI-NEXT:    v_or_b32_e32 v5, v5, v17
; VI-NEXT:    v_add_f16_sdwa v17, v4, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v4, 0x200, v4
; VI-NEXT:    v_or_b32_e32 v4, v4, v17
; VI-NEXT:    v_add_f16_sdwa v17, v3, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v3, 0x200, v3
; VI-NEXT:    v_or_b32_e32 v3, v3, v17
; VI-NEXT:    v_add_f16_sdwa v17, v2, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, 0x200, v2
; VI-NEXT:    v_or_b32_e32 v2, v2, v17
; VI-NEXT:    v_add_f16_sdwa v17, v1, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v1, 0x200, v1
; VI-NEXT:    v_add_f16_sdwa v16, v0, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v0, 0x200, v0
; VI-NEXT:    v_or_b32_e32 v1, v1, v17
; VI-NEXT:    v_or_b32_e32 v0, v0, v16
; VI-NEXT:  .LBB19_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v32f16_to_v16f32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB19_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    s_movk_i32 s6, 0x200
; GFX9-NEXT:    v_pk_add_f16 v15, v15, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v14, v14, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v13, v13, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v12, v12, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v11, v11, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v10, v10, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v9, v9, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v8, v8, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v7, v7, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, v6, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v5, v5, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v4, v4, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v3, v3, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v2, v2, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v1, v1, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v0, v0, s6 op_sel_hi:[1,0]
; GFX9-NEXT:  .LBB19_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v32f16_to_v16f32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB19_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_pk_add_f16 v15, 0x200, v15 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v14, 0x200, v14 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v13, 0x200, v13 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v12, 0x200, v12 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v11, 0x200, v11 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v10, 0x200, v10 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v9, 0x200, v9 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v8, 0x200, v8 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v7, 0x200, v7 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v6, 0x200, v6 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v5, 0x200, v5 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v4, 0x200, v4 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v3, 0x200, v3 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v2, 0x200, v2 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v1, 0x200, v1 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v0, 0x200, v0 op_sel_hi:[0,1]
; GFX11-NEXT:  .LBB19_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <32 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <32 x half> %a1 to <16 x float>
  br label %end

cmp.false:
  %a3 = bitcast <32 x half> %a to <16 x float>
  br label %end

end:
  %phi = phi <16 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x float> %phi
}

define <32 x bfloat> @v_bitcast_v16f32_to_v32bf16(<16 x float> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v16f32_to_v32bf16:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_mov_b32_e32 v55, v15
; GCN-NEXT:    v_mov_b32_e32 v54, v14
; GCN-NEXT:    v_mov_b32_e32 v53, v13
; GCN-NEXT:    v_mov_b32_e32 v52, v12
; GCN-NEXT:    v_mov_b32_e32 v51, v11
; GCN-NEXT:    v_mov_b32_e32 v50, v10
; GCN-NEXT:    v_mov_b32_e32 v49, v9
; GCN-NEXT:    v_mov_b32_e32 v48, v8
; GCN-NEXT:    v_mov_b32_e32 v39, v7
; GCN-NEXT:    v_mov_b32_e32 v38, v6
; GCN-NEXT:    v_mov_b32_e32 v37, v5
; GCN-NEXT:    v_mov_b32_e32 v36, v4
; GCN-NEXT:    v_mov_b32_e32 v35, v3
; GCN-NEXT:    v_mov_b32_e32 v34, v2
; GCN-NEXT:    v_mov_b32_e32 v33, v1
; GCN-NEXT:    v_mov_b32_e32 v32, v0
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GCN-NEXT:    ; implicit-def: $vgpr0
; GCN-NEXT:    ; implicit-def: $vgpr1
; GCN-NEXT:    ; implicit-def: $vgpr2
; GCN-NEXT:    ; implicit-def: $vgpr3
; GCN-NEXT:    ; implicit-def: $vgpr4
; GCN-NEXT:    ; implicit-def: $vgpr5
; GCN-NEXT:    ; implicit-def: $vgpr6
; GCN-NEXT:    ; implicit-def: $vgpr7
; GCN-NEXT:    ; implicit-def: $vgpr8
; GCN-NEXT:    ; implicit-def: $vgpr9
; GCN-NEXT:    ; implicit-def: $vgpr10
; GCN-NEXT:    ; implicit-def: $vgpr11
; GCN-NEXT:    ; implicit-def: $vgpr12
; GCN-NEXT:    ; implicit-def: $vgpr13
; GCN-NEXT:    ; implicit-def: $vgpr14
; GCN-NEXT:    ; implicit-def: $vgpr15
; GCN-NEXT:    ; implicit-def: $vgpr16
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr18
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr20
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr22
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr24
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr26
; GCN-NEXT:    ; implicit-def: $vgpr27
; GCN-NEXT:    ; implicit-def: $vgpr28
; GCN-NEXT:    ; implicit-def: $vgpr29
; GCN-NEXT:    ; implicit-def: $vgpr30
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execnz .LBB20_3
; GCN-NEXT:  ; %bb.1: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execnz .LBB20_4
; GCN-NEXT:  .LBB20_2: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
; GCN-NEXT:  .LBB20_3: ; %cmp.false
; GCN-NEXT:    v_and_b32_e32 v31, 0xffff0000, v55
; GCN-NEXT:    v_lshlrev_b32_e32 v30, 16, v55
; GCN-NEXT:    v_and_b32_e32 v29, 0xffff0000, v54
; GCN-NEXT:    v_lshlrev_b32_e32 v28, 16, v54
; GCN-NEXT:    v_and_b32_e32 v27, 0xffff0000, v53
; GCN-NEXT:    v_lshlrev_b32_e32 v26, 16, v53
; GCN-NEXT:    v_and_b32_e32 v25, 0xffff0000, v52
; GCN-NEXT:    v_lshlrev_b32_e32 v24, 16, v52
; GCN-NEXT:    v_and_b32_e32 v23, 0xffff0000, v51
; GCN-NEXT:    v_lshlrev_b32_e32 v22, 16, v51
; GCN-NEXT:    v_and_b32_e32 v21, 0xffff0000, v50
; GCN-NEXT:    v_lshlrev_b32_e32 v20, 16, v50
; GCN-NEXT:    v_and_b32_e32 v19, 0xffff0000, v49
; GCN-NEXT:    v_lshlrev_b32_e32 v18, 16, v49
; GCN-NEXT:    v_and_b32_e32 v17, 0xffff0000, v48
; GCN-NEXT:    v_lshlrev_b32_e32 v16, 16, v48
; GCN-NEXT:    v_and_b32_e32 v15, 0xffff0000, v39
; GCN-NEXT:    v_lshlrev_b32_e32 v14, 16, v39
; GCN-NEXT:    v_and_b32_e32 v13, 0xffff0000, v38
; GCN-NEXT:    v_lshlrev_b32_e32 v12, 16, v38
; GCN-NEXT:    v_and_b32_e32 v11, 0xffff0000, v37
; GCN-NEXT:    v_lshlrev_b32_e32 v10, 16, v37
; GCN-NEXT:    v_and_b32_e32 v9, 0xffff0000, v36
; GCN-NEXT:    v_lshlrev_b32_e32 v8, 16, v36
; GCN-NEXT:    v_and_b32_e32 v7, 0xffff0000, v35
; GCN-NEXT:    v_lshlrev_b32_e32 v6, 16, v35
; GCN-NEXT:    v_and_b32_e32 v5, 0xffff0000, v34
; GCN-NEXT:    v_lshlrev_b32_e32 v4, 16, v34
; GCN-NEXT:    v_and_b32_e32 v3, 0xffff0000, v33
; GCN-NEXT:    v_lshlrev_b32_e32 v2, 16, v33
; GCN-NEXT:    v_and_b32_e32 v1, 0xffff0000, v32
; GCN-NEXT:    v_lshlrev_b32_e32 v0, 16, v32
; GCN-NEXT:    ; implicit-def: $vgpr32
; GCN-NEXT:    ; implicit-def: $vgpr33
; GCN-NEXT:    ; implicit-def: $vgpr34
; GCN-NEXT:    ; implicit-def: $vgpr35
; GCN-NEXT:    ; implicit-def: $vgpr36
; GCN-NEXT:    ; implicit-def: $vgpr37
; GCN-NEXT:    ; implicit-def: $vgpr38
; GCN-NEXT:    ; implicit-def: $vgpr39
; GCN-NEXT:    ; implicit-def: $vgpr48
; GCN-NEXT:    ; implicit-def: $vgpr49
; GCN-NEXT:    ; implicit-def: $vgpr50
; GCN-NEXT:    ; implicit-def: $vgpr51
; GCN-NEXT:    ; implicit-def: $vgpr52
; GCN-NEXT:    ; implicit-def: $vgpr53
; GCN-NEXT:    ; implicit-def: $vgpr54
; GCN-NEXT:    ; implicit-def: $vgpr55
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB20_2
; GCN-NEXT:  .LBB20_4: ; %cmp.true
; GCN-NEXT:    v_add_f32_e32 v0, 1.0, v32
; GCN-NEXT:    v_add_f32_e32 v1, 1.0, v33
; GCN-NEXT:    v_add_f32_e32 v2, 1.0, v34
; GCN-NEXT:    v_add_f32_e32 v3, 1.0, v35
; GCN-NEXT:    v_add_f32_e32 v4, 1.0, v36
; GCN-NEXT:    v_add_f32_e32 v5, 1.0, v37
; GCN-NEXT:    v_add_f32_e32 v6, 1.0, v38
; GCN-NEXT:    v_add_f32_e32 v7, 1.0, v39
; GCN-NEXT:    v_add_f32_e32 v8, 1.0, v48
; GCN-NEXT:    v_add_f32_e32 v9, 1.0, v49
; GCN-NEXT:    v_add_f32_e32 v10, 1.0, v50
; GCN-NEXT:    v_add_f32_e32 v11, 1.0, v51
; GCN-NEXT:    v_add_f32_e32 v12, 1.0, v52
; GCN-NEXT:    v_add_f32_e32 v13, 1.0, v53
; GCN-NEXT:    v_add_f32_e32 v14, 1.0, v54
; GCN-NEXT:    v_add_f32_e32 v15, 1.0, v55
; GCN-NEXT:    v_and_b32_e32 v31, 0xffff0000, v15
; GCN-NEXT:    v_lshlrev_b32_e32 v30, 16, v15
; GCN-NEXT:    v_and_b32_e32 v29, 0xffff0000, v14
; GCN-NEXT:    v_lshlrev_b32_e32 v28, 16, v14
; GCN-NEXT:    v_and_b32_e32 v27, 0xffff0000, v13
; GCN-NEXT:    v_lshlrev_b32_e32 v26, 16, v13
; GCN-NEXT:    v_and_b32_e32 v25, 0xffff0000, v12
; GCN-NEXT:    v_lshlrev_b32_e32 v24, 16, v12
; GCN-NEXT:    v_and_b32_e32 v23, 0xffff0000, v11
; GCN-NEXT:    v_lshlrev_b32_e32 v22, 16, v11
; GCN-NEXT:    v_and_b32_e32 v21, 0xffff0000, v10
; GCN-NEXT:    v_lshlrev_b32_e32 v20, 16, v10
; GCN-NEXT:    v_and_b32_e32 v19, 0xffff0000, v9
; GCN-NEXT:    v_lshlrev_b32_e32 v18, 16, v9
; GCN-NEXT:    v_and_b32_e32 v17, 0xffff0000, v8
; GCN-NEXT:    v_lshlrev_b32_e32 v16, 16, v8
; GCN-NEXT:    v_and_b32_e32 v15, 0xffff0000, v7
; GCN-NEXT:    v_lshlrev_b32_e32 v14, 16, v7
; GCN-NEXT:    v_and_b32_e32 v13, 0xffff0000, v6
; GCN-NEXT:    v_lshlrev_b32_e32 v12, 16, v6
; GCN-NEXT:    v_and_b32_e32 v11, 0xffff0000, v5
; GCN-NEXT:    v_lshlrev_b32_e32 v10, 16, v5
; GCN-NEXT:    v_and_b32_e32 v9, 0xffff0000, v4
; GCN-NEXT:    v_lshlrev_b32_e32 v8, 16, v4
; GCN-NEXT:    v_and_b32_e32 v7, 0xffff0000, v3
; GCN-NEXT:    v_lshlrev_b32_e32 v6, 16, v3
; GCN-NEXT:    v_and_b32_e32 v5, 0xffff0000, v2
; GCN-NEXT:    v_lshlrev_b32_e32 v4, 16, v2
; GCN-NEXT:    v_and_b32_e32 v3, 0xffff0000, v1
; GCN-NEXT:    v_lshlrev_b32_e32 v2, 16, v1
; GCN-NEXT:    v_and_b32_e32 v1, 0xffff0000, v0
; GCN-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v16f32_to_v32bf16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB20_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f32_e32 v15, 1.0, v15
; VI-NEXT:    v_add_f32_e32 v14, 1.0, v14
; VI-NEXT:    v_add_f32_e32 v13, 1.0, v13
; VI-NEXT:    v_add_f32_e32 v12, 1.0, v12
; VI-NEXT:    v_add_f32_e32 v11, 1.0, v11
; VI-NEXT:    v_add_f32_e32 v10, 1.0, v10
; VI-NEXT:    v_add_f32_e32 v9, 1.0, v9
; VI-NEXT:    v_add_f32_e32 v8, 1.0, v8
; VI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; VI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; VI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; VI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; VI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; VI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; VI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; VI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; VI-NEXT:  .LBB20_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v16f32_to_v32bf16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB20_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e32 v15, 1.0, v15
; GFX9-NEXT:    v_add_f32_e32 v14, 1.0, v14
; GFX9-NEXT:    v_add_f32_e32 v13, 1.0, v13
; GFX9-NEXT:    v_add_f32_e32 v12, 1.0, v12
; GFX9-NEXT:    v_add_f32_e32 v11, 1.0, v11
; GFX9-NEXT:    v_add_f32_e32 v10, 1.0, v10
; GFX9-NEXT:    v_add_f32_e32 v9, 1.0, v9
; GFX9-NEXT:    v_add_f32_e32 v8, 1.0, v8
; GFX9-NEXT:    v_add_f32_e32 v7, 1.0, v7
; GFX9-NEXT:    v_add_f32_e32 v6, 1.0, v6
; GFX9-NEXT:    v_add_f32_e32 v5, 1.0, v5
; GFX9-NEXT:    v_add_f32_e32 v4, 1.0, v4
; GFX9-NEXT:    v_add_f32_e32 v3, 1.0, v3
; GFX9-NEXT:    v_add_f32_e32 v2, 1.0, v2
; GFX9-NEXT:    v_add_f32_e32 v1, 1.0, v1
; GFX9-NEXT:    v_add_f32_e32 v0, 1.0, v0
; GFX9-NEXT:  .LBB20_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v16f32_to_v32bf16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB20_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_dual_add_f32 v15, 1.0, v15 :: v_dual_add_f32 v14, 1.0, v14
; GFX11-NEXT:    v_dual_add_f32 v13, 1.0, v13 :: v_dual_add_f32 v12, 1.0, v12
; GFX11-NEXT:    v_dual_add_f32 v11, 1.0, v11 :: v_dual_add_f32 v10, 1.0, v10
; GFX11-NEXT:    v_dual_add_f32 v9, 1.0, v9 :: v_dual_add_f32 v8, 1.0, v8
; GFX11-NEXT:    v_dual_add_f32 v7, 1.0, v7 :: v_dual_add_f32 v6, 1.0, v6
; GFX11-NEXT:    v_dual_add_f32 v5, 1.0, v5 :: v_dual_add_f32 v4, 1.0, v4
; GFX11-NEXT:    v_dual_add_f32 v3, 1.0, v3 :: v_dual_add_f32 v2, 1.0, v2
; GFX11-NEXT:    v_dual_add_f32 v1, 1.0, v1 :: v_dual_add_f32 v0, 1.0, v0
; GFX11-NEXT:  .LBB20_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <16 x float> %a1 to <32 x bfloat>
  br label %end

cmp.false:
  %a3 = bitcast <16 x float> %a to <32 x bfloat>
  br label %end

end:
  %phi = phi <32 x bfloat> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x bfloat> %phi
}

define <16 x float> @v_bitcast_v32bf16_to_v16f32(<32 x bfloat> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v32bf16_to_v16f32:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GCN-NEXT:    s_waitcnt expcnt(1)
; GCN-NEXT:    buffer_load_dword v46, off, s[0:3], s32
; GCN-NEXT:    s_waitcnt expcnt(0)
; GCN-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:4
; GCN-NEXT:    v_mul_f32_e32 v44, 1.0, v1
; GCN-NEXT:    v_mul_f32_e32 v45, 1.0, v0
; GCN-NEXT:    v_mul_f32_e32 v42, 1.0, v3
; GCN-NEXT:    v_mul_f32_e32 v43, 1.0, v2
; GCN-NEXT:    v_mul_f32_e32 v41, 1.0, v5
; GCN-NEXT:    v_mul_f32_e32 v51, 1.0, v4
; GCN-NEXT:    v_mul_f32_e32 v40, 1.0, v7
; GCN-NEXT:    v_mul_f32_e32 v49, 1.0, v6
; GCN-NEXT:    v_mul_f32_e32 v55, 1.0, v9
; GCN-NEXT:    v_mul_f32_e32 v39, 1.0, v8
; GCN-NEXT:    v_mul_f32_e32 v54, 1.0, v11
; GCN-NEXT:    v_mul_f32_e32 v37, 1.0, v10
; GCN-NEXT:    v_mul_f32_e32 v53, 1.0, v13
; GCN-NEXT:    v_mul_f32_e32 v36, 1.0, v12
; GCN-NEXT:    v_mul_f32_e32 v52, 1.0, v15
; GCN-NEXT:    v_mul_f32_e32 v34, 1.0, v14
; GCN-NEXT:    v_mul_f32_e32 v50, 1.0, v17
; GCN-NEXT:    v_mul_f32_e32 v33, 1.0, v16
; GCN-NEXT:    v_mul_f32_e32 v48, 1.0, v19
; GCN-NEXT:    v_mul_f32_e32 v32, 1.0, v18
; GCN-NEXT:    v_mul_f32_e32 v38, 1.0, v21
; GCN-NEXT:    v_mul_f32_e32 v31, 1.0, v20
; GCN-NEXT:    v_mul_f32_e32 v35, 1.0, v23
; GCN-NEXT:    v_mul_f32_e32 v21, 1.0, v22
; GCN-NEXT:    v_mul_f32_e32 v25, 1.0, v25
; GCN-NEXT:    v_mul_f32_e32 v19, 1.0, v24
; GCN-NEXT:    v_mul_f32_e32 v23, 1.0, v27
; GCN-NEXT:    v_mul_f32_e32 v18, 1.0, v26
; GCN-NEXT:    v_mul_f32_e32 v22, 1.0, v29
; GCN-NEXT:    v_mul_f32_e32 v17, 1.0, v28
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v47
; GCN-NEXT:    v_mul_f32_e32 v20, 1.0, v46
; GCN-NEXT:    v_mul_f32_e32 v16, 1.0, v30
; GCN-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB21_2
; GCN-NEXT:  ; %bb.1: ; %cmp.false
; GCN-NEXT:    v_lshrrev_b32_e32 v0, 16, v44
; GCN-NEXT:    v_lshrrev_b32_e32 v1, 16, v42
; GCN-NEXT:    v_alignbit_b32 v0, v0, v45, 16
; GCN-NEXT:    v_alignbit_b32 v1, v1, v43, 16
; GCN-NEXT:    v_lshrrev_b32_e32 v2, 16, v41
; GCN-NEXT:    v_lshrrev_b32_e32 v3, 16, v40
; GCN-NEXT:    v_lshrrev_b32_e32 v4, 16, v55
; GCN-NEXT:    v_lshrrev_b32_e32 v5, 16, v54
; GCN-NEXT:    v_lshrrev_b32_e32 v6, 16, v53
; GCN-NEXT:    v_lshrrev_b32_e32 v7, 16, v52
; GCN-NEXT:    v_lshrrev_b32_e32 v8, 16, v50
; GCN-NEXT:    v_lshrrev_b32_e32 v9, 16, v48
; GCN-NEXT:    v_lshrrev_b32_e32 v10, 16, v38
; GCN-NEXT:    v_lshrrev_b32_e32 v11, 16, v35
; GCN-NEXT:    v_lshrrev_b32_e32 v12, 16, v25
; GCN-NEXT:    v_lshrrev_b32_e32 v13, 16, v23
; GCN-NEXT:    v_lshrrev_b32_e32 v14, 16, v22
; GCN-NEXT:    v_lshrrev_b32_e32 v15, 16, v20
; GCN-NEXT:    v_alignbit_b32 v2, v2, v51, 16
; GCN-NEXT:    v_alignbit_b32 v3, v3, v49, 16
; GCN-NEXT:    v_alignbit_b32 v4, v4, v39, 16
; GCN-NEXT:    v_alignbit_b32 v5, v5, v37, 16
; GCN-NEXT:    v_alignbit_b32 v6, v6, v36, 16
; GCN-NEXT:    v_alignbit_b32 v7, v7, v34, 16
; GCN-NEXT:    v_alignbit_b32 v8, v8, v33, 16
; GCN-NEXT:    v_alignbit_b32 v9, v9, v32, 16
; GCN-NEXT:    v_alignbit_b32 v10, v10, v31, 16
; GCN-NEXT:    v_alignbit_b32 v11, v11, v21, 16
; GCN-NEXT:    v_alignbit_b32 v12, v12, v19, 16
; GCN-NEXT:    v_alignbit_b32 v13, v13, v18, 16
; GCN-NEXT:    v_alignbit_b32 v14, v14, v17, 16
; GCN-NEXT:    v_alignbit_b32 v15, v15, v16, 16
; GCN-NEXT:    ; implicit-def: $vgpr44
; GCN-NEXT:    ; implicit-def: $vgpr45
; GCN-NEXT:    ; implicit-def: $vgpr42
; GCN-NEXT:    ; implicit-def: $vgpr43
; GCN-NEXT:    ; implicit-def: $vgpr41
; GCN-NEXT:    ; implicit-def: $vgpr51
; GCN-NEXT:    ; implicit-def: $vgpr40
; GCN-NEXT:    ; implicit-def: $vgpr49
; GCN-NEXT:    ; implicit-def: $vgpr55
; GCN-NEXT:    ; implicit-def: $vgpr39
; GCN-NEXT:    ; implicit-def: $vgpr54
; GCN-NEXT:    ; implicit-def: $vgpr37
; GCN-NEXT:    ; implicit-def: $vgpr53
; GCN-NEXT:    ; implicit-def: $vgpr36
; GCN-NEXT:    ; implicit-def: $vgpr52
; GCN-NEXT:    ; implicit-def: $vgpr34
; GCN-NEXT:    ; implicit-def: $vgpr50
; GCN-NEXT:    ; implicit-def: $vgpr33
; GCN-NEXT:    ; implicit-def: $vgpr48
; GCN-NEXT:    ; implicit-def: $vgpr32
; GCN-NEXT:    ; implicit-def: $vgpr38
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    ; implicit-def: $vgpr35
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr18
; GCN-NEXT:    ; implicit-def: $vgpr22
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr20
; GCN-NEXT:    ; implicit-def: $vgpr16
; GCN-NEXT:  .LBB21_2: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB21_4
; GCN-NEXT:  ; %bb.3: ; %cmp.true
; GCN-NEXT:    v_and_b32_e32 v0, 0xffff0000, v45
; GCN-NEXT:    v_and_b32_e32 v1, 0xffff0000, v44
; GCN-NEXT:    v_and_b32_e32 v2, 0xffff0000, v43
; GCN-NEXT:    v_and_b32_e32 v3, 0xffff0000, v42
; GCN-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; GCN-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GCN-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GCN-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GCN-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GCN-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; GCN-NEXT:    v_alignbit_b32 v0, v1, v0, 16
; GCN-NEXT:    v_alignbit_b32 v1, v3, v2, 16
; GCN-NEXT:    v_and_b32_e32 v2, 0xffff0000, v51
; GCN-NEXT:    v_and_b32_e32 v3, 0xffff0000, v41
; GCN-NEXT:    v_and_b32_e32 v4, 0xffff0000, v49
; GCN-NEXT:    v_and_b32_e32 v5, 0xffff0000, v40
; GCN-NEXT:    v_and_b32_e32 v6, 0xffff0000, v39
; GCN-NEXT:    v_and_b32_e32 v7, 0xffff0000, v55
; GCN-NEXT:    v_and_b32_e32 v8, 0xffff0000, v37
; GCN-NEXT:    v_and_b32_e32 v9, 0xffff0000, v54
; GCN-NEXT:    v_and_b32_e32 v10, 0xffff0000, v36
; GCN-NEXT:    v_and_b32_e32 v11, 0xffff0000, v53
; GCN-NEXT:    v_and_b32_e32 v12, 0xffff0000, v34
; GCN-NEXT:    v_and_b32_e32 v13, 0xffff0000, v52
; GCN-NEXT:    v_and_b32_e32 v14, 0xffff0000, v33
; GCN-NEXT:    v_and_b32_e32 v15, 0xffff0000, v50
; GCN-NEXT:    v_and_b32_e32 v24, 0xffff0000, v32
; GCN-NEXT:    v_and_b32_e32 v26, 0xffff0000, v48
; GCN-NEXT:    v_and_b32_e32 v27, 0xffff0000, v31
; GCN-NEXT:    v_and_b32_e32 v28, 0xffff0000, v38
; GCN-NEXT:    v_and_b32_e32 v21, 0xffff0000, v21
; GCN-NEXT:    v_and_b32_e32 v29, 0xffff0000, v35
; GCN-NEXT:    v_and_b32_e32 v19, 0xffff0000, v19
; GCN-NEXT:    v_and_b32_e32 v25, 0xffff0000, v25
; GCN-NEXT:    v_and_b32_e32 v18, 0xffff0000, v18
; GCN-NEXT:    v_and_b32_e32 v23, 0xffff0000, v23
; GCN-NEXT:    v_and_b32_e32 v17, 0xffff0000, v17
; GCN-NEXT:    v_and_b32_e32 v22, 0xffff0000, v22
; GCN-NEXT:    v_and_b32_e32 v16, 0xffff0000, v16
; GCN-NEXT:    v_and_b32_e32 v20, 0xffff0000, v20
; GCN-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GCN-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GCN-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; GCN-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GCN-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GCN-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GCN-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GCN-NEXT:    v_add_f32_e32 v9, 0x40c00000, v9
; GCN-NEXT:    v_add_f32_e32 v10, 0x40c00000, v10
; GCN-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; GCN-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; GCN-NEXT:    v_add_f32_e32 v13, 0x40c00000, v13
; GCN-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; GCN-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; GCN-NEXT:    v_add_f32_e32 v24, 0x40c00000, v24
; GCN-NEXT:    v_add_f32_e32 v26, 0x40c00000, v26
; GCN-NEXT:    v_add_f32_e32 v27, 0x40c00000, v27
; GCN-NEXT:    v_add_f32_e32 v28, 0x40c00000, v28
; GCN-NEXT:    v_add_f32_e32 v21, 0x40c00000, v21
; GCN-NEXT:    v_add_f32_e32 v29, 0x40c00000, v29
; GCN-NEXT:    v_add_f32_e32 v19, 0x40c00000, v19
; GCN-NEXT:    v_add_f32_e32 v25, 0x40c00000, v25
; GCN-NEXT:    v_add_f32_e32 v18, 0x40c00000, v18
; GCN-NEXT:    v_add_f32_e32 v23, 0x40c00000, v23
; GCN-NEXT:    v_add_f32_e32 v17, 0x40c00000, v17
; GCN-NEXT:    v_add_f32_e32 v22, 0x40c00000, v22
; GCN-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GCN-NEXT:    v_add_f32_e32 v20, 0x40c00000, v20
; GCN-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; GCN-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; GCN-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; GCN-NEXT:    v_lshrrev_b32_e32 v9, 16, v9
; GCN-NEXT:    v_lshrrev_b32_e32 v11, 16, v11
; GCN-NEXT:    v_lshrrev_b32_e32 v13, 16, v13
; GCN-NEXT:    v_lshrrev_b32_e32 v15, 16, v15
; GCN-NEXT:    v_lshrrev_b32_e32 v26, 16, v26
; GCN-NEXT:    v_lshrrev_b32_e32 v28, 16, v28
; GCN-NEXT:    v_lshrrev_b32_e32 v29, 16, v29
; GCN-NEXT:    v_lshrrev_b32_e32 v25, 16, v25
; GCN-NEXT:    v_lshrrev_b32_e32 v23, 16, v23
; GCN-NEXT:    v_lshrrev_b32_e32 v22, 16, v22
; GCN-NEXT:    v_lshrrev_b32_e32 v20, 16, v20
; GCN-NEXT:    v_alignbit_b32 v2, v3, v2, 16
; GCN-NEXT:    v_alignbit_b32 v3, v5, v4, 16
; GCN-NEXT:    v_alignbit_b32 v4, v7, v6, 16
; GCN-NEXT:    v_alignbit_b32 v5, v9, v8, 16
; GCN-NEXT:    v_alignbit_b32 v6, v11, v10, 16
; GCN-NEXT:    v_alignbit_b32 v7, v13, v12, 16
; GCN-NEXT:    v_alignbit_b32 v8, v15, v14, 16
; GCN-NEXT:    v_alignbit_b32 v9, v26, v24, 16
; GCN-NEXT:    v_alignbit_b32 v10, v28, v27, 16
; GCN-NEXT:    v_alignbit_b32 v11, v29, v21, 16
; GCN-NEXT:    v_alignbit_b32 v12, v25, v19, 16
; GCN-NEXT:    v_alignbit_b32 v13, v23, v18, 16
; GCN-NEXT:    v_alignbit_b32 v14, v22, v17, 16
; GCN-NEXT:    v_alignbit_b32 v15, v20, v16, 16
; GCN-NEXT:  .LBB21_4: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v32bf16_to_v16f32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB21_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v15
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, 0x7fff, v17
; VI-NEXT:    v_and_b32_e32 v15, 0xffff0000, v15
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v15, 16, 1
; VI-NEXT:    s_movk_i32 s6, 0x7fff
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v15
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v15
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v15, v15
; VI-NEXT:    v_cndmask_b32_e32 v15, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v15, 16, v15
; VI-NEXT:    v_alignbit_b32 v15, v15, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v14
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v14, 0xffff0000, v14
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v14, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v14
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v14
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v14, v14
; VI-NEXT:    v_cndmask_b32_e32 v14, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v14, 16, v14
; VI-NEXT:    v_alignbit_b32 v14, v14, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v13
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v13, 0xffff0000, v13
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v13, 0x40c00000, v13
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v13, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v13
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v13
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v13, v13
; VI-NEXT:    v_cndmask_b32_e32 v13, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v13, 16, v13
; VI-NEXT:    v_alignbit_b32 v13, v13, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v12
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v12, 0xffff0000, v12
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v12, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v12
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v12
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v12, v12
; VI-NEXT:    v_cndmask_b32_e32 v12, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v12, 16, v12
; VI-NEXT:    v_alignbit_b32 v12, v12, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v11
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v11, 0xffff0000, v11
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v11, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v11
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v11
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v11, v11
; VI-NEXT:    v_cndmask_b32_e32 v11, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v11, 16, v11
; VI-NEXT:    v_alignbit_b32 v11, v11, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v10
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v10, 0xffff0000, v10
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v10, 0x40c00000, v10
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v10, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v10
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v10
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v10, v10
; VI-NEXT:    v_cndmask_b32_e32 v10, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v10, 16, v10
; VI-NEXT:    v_alignbit_b32 v10, v10, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v9
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v9, 0xffff0000, v9
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v9, 0x40c00000, v9
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v9, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v9
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v9
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v9, v9
; VI-NEXT:    v_cndmask_b32_e32 v9, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v9, 16, v9
; VI-NEXT:    v_alignbit_b32 v9, v9, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v8
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v8, 0xffff0000, v8
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v8
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_cndmask_b32_e32 v8, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v8, 16, v8
; VI-NEXT:    v_alignbit_b32 v8, v8, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v7
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v7, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v7
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v7
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; VI-NEXT:    v_cndmask_b32_e32 v7, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; VI-NEXT:    v_alignbit_b32 v7, v7, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v6
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v6, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v6
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v6
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; VI-NEXT:    v_cndmask_b32_e32 v6, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_alignbit_b32 v6, v6, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v5
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v5, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v5
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v5
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; VI-NEXT:    v_cndmask_b32_e32 v5, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_alignbit_b32 v5, v5, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v4
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v4, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v4
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v4
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; VI-NEXT:    v_cndmask_b32_e32 v4, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_alignbit_b32 v4, v4, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v3
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v3
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_alignbit_b32 v3, v3, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v2
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v2
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_alignbit_b32 v2, v2, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v1
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v1, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v1
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v1
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; VI-NEXT:    v_cndmask_b32_e32 v1, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_alignbit_b32 v1, v1, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v0
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v0, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v0
; VI-NEXT:    v_add_u32_e32 v17, vcc, 0x7fff, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v0
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; VI-NEXT:    v_cndmask_b32_e32 v0, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; VI-NEXT:    v_alignbit_b32 v0, v0, v16, 16
; VI-NEXT:  .LBB21_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v32bf16_to_v16f32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB21_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v15
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    s_movk_i32 s6, 0x7fff
; GFX9-NEXT:    v_and_b32_e32 v15, 0xffff0000, v15
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v15, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v15, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v15
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v15, v15
; GFX9-NEXT:    v_cndmask_b32_e32 v15, v17, v18, vcc
; GFX9-NEXT:    s_mov_b32 s7, 0x7060302
; GFX9-NEXT:    v_perm_b32 v15, v15, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v14
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v14, 0xffff0000, v14
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v14, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v14, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v14
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v14, v14
; GFX9-NEXT:    v_cndmask_b32_e32 v14, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v14, v14, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v13
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v13, 0xffff0000, v13
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v13, 0x40c00000, v13
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v13, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v13, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v13
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v13, v13
; GFX9-NEXT:    v_cndmask_b32_e32 v13, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v13, v13, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v12
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v12, 0xffff0000, v12
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v12, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v12, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v12
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v12, v12
; GFX9-NEXT:    v_cndmask_b32_e32 v12, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v12, v12, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v11
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v11, 0xffff0000, v11
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v11, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v11, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v11
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v11, v11
; GFX9-NEXT:    v_cndmask_b32_e32 v11, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v11, v11, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v10
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v10, 0xffff0000, v10
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v10, 0x40c00000, v10
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v10, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v10, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v10
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v10, v10
; GFX9-NEXT:    v_cndmask_b32_e32 v10, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v10, v10, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v9
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v9, 0xffff0000, v9
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v9, 0x40c00000, v9
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v9, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v9, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v9
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v9, v9
; GFX9-NEXT:    v_cndmask_b32_e32 v9, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v9, v9, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v8
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v8, 0xffff0000, v8
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v8, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v8, v8, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v7
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v7, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v7, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v7
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; GFX9-NEXT:    v_cndmask_b32_e32 v7, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v7, v7, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v6
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v6, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v6, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v6
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; GFX9-NEXT:    v_cndmask_b32_e32 v6, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v6, v6, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v5
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v5, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v5, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v5, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v5, v5, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v4
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v4, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v4, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v4
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; GFX9-NEXT:    v_cndmask_b32_e32 v4, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v4, v4, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v3
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v3, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v3, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v3
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; GFX9-NEXT:    v_cndmask_b32_e32 v3, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v3, v3, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v2, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v2, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v2, v2, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v1
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v1, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v1, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v1, v1, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v0
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v0, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v0, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v0
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v0, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v0, v0, v16, s7
; GFX9-NEXT:  .LBB21_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v32bf16_to_v16f32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB21_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_lshlrev_b32_e32 v17, 16, v14
; GFX11-NEXT:    v_lshlrev_b32_e32 v16, 16, v15
; GFX11-NEXT:    v_and_b32_e32 v14, 0xffff0000, v14
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_dual_add_f32 v17, 0x40c00000, v17 :: v_dual_add_f32 v16, 0x40c00000, v16
; GFX11-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_bfe_u32 v21, v17, 16, 1
; GFX11-NEXT:    v_bfe_u32 v18, v16, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v19, 0x400000, v16
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_bfe_u32 v23, v14, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v16, v16
; GFX11-NEXT:    v_add3_u32 v21, v21, v17, 0x7fff
; GFX11-NEXT:    v_add3_u32 v18, v18, v16, 0x7fff
; GFX11-NEXT:    v_cndmask_b32_e32 v16, v18, v19, vcc_lo
; GFX11-NEXT:    v_add3_u32 v19, v23, v14, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v15, 0xffff0000, v15
; GFX11-NEXT:    v_or_b32_e32 v18, 0x400000, v17
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; GFX11-NEXT:    v_bfe_u32 v20, v15, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v15
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v15, v15
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add3_u32 v20, v20, v15, 0x7fff
; GFX11-NEXT:    v_dual_cndmask_b32 v15, v20, v22 :: v_dual_lshlrev_b32 v20, 16, v13
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v17, v17
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_perm_b32 v15, v15, v16, 0x7060302
; GFX11-NEXT:    v_dual_cndmask_b32 v17, v21, v18 :: v_dual_add_f32 v18, 0x40c00000, v20
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_bfe_u32 v16, v18, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v18
; GFX11-NEXT:    v_add3_u32 v16, v16, v18, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v13, 0xffff0000, v13
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_add_f32_e32 v13, 0x40c00000, v13
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v14
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v14, v14
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v13
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_dual_cndmask_b32 v14, v19, v22 :: v_dual_lshlrev_b32 v19, 16, v12
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-NEXT:    v_perm_b32 v14, v14, v17, 0x7060302
; GFX11-NEXT:    v_bfe_u32 v17, v13, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_dual_add_f32 v19, 0x40c00000, v19 :: v_dual_cndmask_b32 v16, v16, v20
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v13, v13
; GFX11-NEXT:    v_add3_u32 v17, v17, v13, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_bfe_u32 v22, v19, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v19
; GFX11-NEXT:    v_cndmask_b32_e32 v13, v17, v21, vcc_lo
; GFX11-NEXT:    v_lshlrev_b32_e32 v21, 16, v11
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_add3_u32 v17, v22, v19, 0x7fff
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v19, v19
; GFX11-NEXT:    v_perm_b32 v13, v13, v16, 0x7060302
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_add_f32_e32 v19, 0x40c00000, v21
; GFX11-NEXT:    v_cndmask_b32_e32 v17, v17, v20, vcc_lo
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_bfe_u32 v16, v19, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v19
; GFX11-NEXT:    v_add3_u32 v16, v16, v19, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v11, 0xffff0000, v11
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v11
; GFX11-NEXT:    v_and_b32_e32 v12, 0xffff0000, v12
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; GFX11-NEXT:    v_bfe_u32 v18, v12, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v12
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v12, v12
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add3_u32 v18, v18, v12, 0x7fff
; GFX11-NEXT:    v_cndmask_b32_e32 v12, v18, v22, vcc_lo
; GFX11-NEXT:    v_lshlrev_b32_e32 v18, 16, v10
; GFX11-NEXT:    v_and_b32_e32 v10, 0xffff0000, v10
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_perm_b32 v12, v12, v17, 0x7060302
; GFX11-NEXT:    v_bfe_u32 v17, v11, 16, 1
; GFX11-NEXT:    v_add_f32_e32 v18, 0x40c00000, v18
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_add_f32_e32 v10, 0x40c00000, v10
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v19, v19
; GFX11-NEXT:    v_add3_u32 v17, v17, v11, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_bfe_u32 v22, v18, 16, 1
; GFX11-NEXT:    v_bfe_u32 v19, v10, 16, 1
; GFX11-NEXT:    v_cndmask_b32_e32 v16, v16, v20, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v11, v11
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v18
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_4) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_add3_u32 v19, v19, v10, 0x7fff
; GFX11-NEXT:    v_cndmask_b32_e32 v11, v17, v21, vcc_lo
; GFX11-NEXT:    v_add3_u32 v17, v22, v18, 0x7fff
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v10
; GFX11-NEXT:    v_perm_b32 v11, v11, v16, 0x7060302
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_cndmask_b32_e32 v17, v17, v20, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-NEXT:    v_dual_cndmask_b32 v10, v19, v22 :: v_dual_lshlrev_b32 v21, 16, v9
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_dual_add_f32 v18, 0x40c00000, v21 :: v_dual_lshlrev_b32 v19, 16, v8
; GFX11-NEXT:    v_and_b32_e32 v8, 0xffff0000, v8
; GFX11-NEXT:    v_perm_b32 v10, v10, v17, 0x7060302
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_3) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_bfe_u32 v16, v18, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v18
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-NEXT:    v_dual_add_f32 v19, 0x40c00000, v19 :: v_dual_add_f32 v8, 0x40c00000, v8
; GFX11-NEXT:    v_add3_u32 v16, v16, v18, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v9, 0xffff0000, v9
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_bfe_u32 v22, v19, 16, 1
; GFX11-NEXT:    v_bfe_u32 v18, v8, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_dual_cndmask_b32 v16, v16, v20 :: v_dual_add_f32 v9, 0x40c00000, v9
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v19
; GFX11-NEXT:    v_add3_u32 v18, v18, v8, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_bfe_u32 v17, v9, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v9
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-NEXT:    v_add3_u32 v17, v17, v9, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_3) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_cndmask_b32_e32 v9, v17, v21, vcc_lo
; GFX11-NEXT:    v_add3_u32 v17, v22, v19, 0x7fff
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v19, v19
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v8
; GFX11-NEXT:    v_perm_b32 v9, v9, v16, 0x7060302
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_cndmask_b32_e32 v17, v17, v20, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-NEXT:    v_cndmask_b32_e32 v8, v18, v22, vcc_lo
; GFX11-NEXT:    v_lshlrev_b32_e32 v18, 16, v6
; GFX11-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; GFX11-NEXT:    v_lshlrev_b32_e32 v21, 16, v7
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_perm_b32 v8, v8, v17, 0x7060302
; GFX11-NEXT:    v_add_f32_e32 v18, 0x40c00000, v18
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_dual_add_f32 v6, 0x40c00000, v6 :: v_dual_add_f32 v19, 0x40c00000, v21
; GFX11-NEXT:    v_bfe_u32 v22, v18, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_bfe_u32 v16, v19, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v19
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v19, v19
; GFX11-NEXT:    v_add3_u32 v16, v16, v19, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; GFX11-NEXT:    v_bfe_u32 v19, v6, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_dual_cndmask_b32 v16, v16, v20 :: v_dual_add_f32 v7, 0x40c00000, v7
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v18
; GFX11-NEXT:    v_add3_u32 v19, v19, v6, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_bfe_u32 v17, v7, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v7
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-NEXT:    v_add3_u32 v17, v17, v7, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_4) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_cndmask_b32_e32 v7, v17, v21, vcc_lo
; GFX11-NEXT:    v_add3_u32 v17, v22, v18, 0x7fff
; GFX11-NEXT:    v_lshlrev_b32_e32 v21, 16, v5
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v6
; GFX11-NEXT:    v_dual_add_f32 v18, 0x40c00000, v21 :: v_dual_cndmask_b32 v17, v17, v20
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_bfe_u32 v20, v18, 16, 1
; GFX11-NEXT:    v_dual_cndmask_b32 v6, v19, v22 :: v_dual_lshlrev_b32 v19, 16, v4
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; GFX11-NEXT:    v_perm_b32 v7, v7, v16, 0x7060302
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_4) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_perm_b32 v6, v6, v17, 0x7060302
; GFX11-NEXT:    v_add_f32_e32 v17, 0x40c00000, v19
; GFX11-NEXT:    v_add3_u32 v19, v20, v18, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v18
; GFX11-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; GFX11-NEXT:    v_bfe_u32 v22, v17, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_4) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_cndmask_b32_e32 v18, v19, v20, vcc_lo
; GFX11-NEXT:    v_or_b32_e32 v19, 0x400000, v17
; GFX11-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; GFX11-NEXT:    v_lshlrev_b32_e32 v20, 16, v3
; GFX11-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; GFX11-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_bfe_u32 v16, v5, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v5
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-NEXT:    v_add3_u32 v16, v16, v5, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_cndmask_b32_e32 v5, v16, v21, vcc_lo
; GFX11-NEXT:    v_add3_u32 v16, v22, v17, 0x7fff
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v17, v17
; GFX11-NEXT:    v_perm_b32 v5, v5, v18, 0x7060302
; GFX11-NEXT:    v_bfe_u32 v18, v4, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_2) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_cndmask_b32_e32 v16, v16, v19, vcc_lo
; GFX11-NEXT:    v_or_b32_e32 v19, 0x400000, v4
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-NEXT:    v_add3_u32 v18, v18, v4, 0x7fff
; GFX11-NEXT:    v_dual_add_f32 v17, 0x40c00000, v20 :: v_dual_lshlrev_b32 v20, 16, v2
; GFX11-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_cndmask_b32_e32 v4, v18, v19, vcc_lo
; GFX11-NEXT:    v_bfe_u32 v21, v17, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-NEXT:    v_add_f32_e32 v18, 0x40c00000, v20
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v17
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v17, v17
; GFX11-NEXT:    v_perm_b32 v4, v4, v16, 0x7060302
; GFX11-NEXT:    v_add3_u32 v19, v21, v17, 0x7fff
; GFX11-NEXT:    v_bfe_u32 v21, v3, 16, 1
; GFX11-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; GFX11-NEXT:    v_bfe_u32 v22, v18, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v23, 0x400000, v18
; GFX11-NEXT:    v_cndmask_b32_e32 v17, v19, v20, vcc_lo
; GFX11-NEXT:    v_add3_u32 v19, v21, v3, 0x7fff
; GFX11-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v3
; GFX11-NEXT:    v_add3_u32 v21, v22, v18, 0x7fff
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-NEXT:    v_lshlrev_b32_e32 v22, 16, v1
; GFX11-NEXT:    v_bfe_u32 v24, v2, 16, 1
; GFX11-NEXT:    v_cndmask_b32_e32 v3, v19, v20, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_add_f32_e32 v19, 0x40c00000, v22
; GFX11-NEXT:    v_add3_u32 v20, v24, v2, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_4) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_perm_b32 v3, v3, v17, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v18, v21, v23, vcc_lo
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v2
; GFX11-NEXT:    v_bfe_u32 v22, v19, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-NEXT:    v_dual_cndmask_b32 v2, v20, v21 :: v_dual_lshlrev_b32 v23, 16, v0
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-NEXT:    v_add3_u32 v21, v22, v19, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v19
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v19, v19
; GFX11-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX11-NEXT:    v_add_f32_e32 v20, 0x40c00000, v23
; GFX11-NEXT:    v_perm_b32 v2, v2, v18, 0x7060302
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_dual_cndmask_b32 v19, v21, v22 :: v_dual_add_f32 v0, 0x40c00000, v0
; GFX11-NEXT:    v_bfe_u32 v24, v20, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v25, 0x400000, v20
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_bfe_u32 v21, v0, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v26, 0x400000, v0
; GFX11-NEXT:    v_add3_u32 v24, v24, v20, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add3_u32 v21, v21, v0, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; GFX11-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_bfe_u32 v23, v1, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-NEXT:    v_add3_u32 v22, v23, v1, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v23, 0x400000, v1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_cndmask_b32_e32 v1, v22, v23, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v20, v20
; GFX11-NEXT:    v_perm_b32 v1, v1, v19, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v20, v24, v25, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-NEXT:    v_cndmask_b32_e32 v0, v21, v26, vcc_lo
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-NEXT:    v_perm_b32 v0, v0, v20, 0x7060302
; GFX11-NEXT:  .LBB21_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <32 x bfloat> %a, splat (bfloat 0xR40C0)
  %a2 = bitcast <32 x bfloat> %a1 to <16 x float>
  br label %end

cmp.false:
  %a3 = bitcast <32 x bfloat> %a to <16 x float>
  br label %end

end:
  %phi = phi <16 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x float> %phi
}

define <8 x double> @v_bitcast_v8i64_to_v8f64(<8 x i64> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v8i64_to_v8f64:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB22_2
; GCN-NEXT:  ; %bb.1: ; %cmp.true
; GCN-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; GCN-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; GCN-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; GCN-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; GCN-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; GCN-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; GCN-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; GCN-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; GCN-NEXT:    v_add_i32_e32 v8, vcc, 3, v8
; GCN-NEXT:    v_addc_u32_e32 v9, vcc, 0, v9, vcc
; GCN-NEXT:    v_add_i32_e32 v10, vcc, 3, v10
; GCN-NEXT:    v_addc_u32_e32 v11, vcc, 0, v11, vcc
; GCN-NEXT:    v_add_i32_e32 v12, vcc, 3, v12
; GCN-NEXT:    v_addc_u32_e32 v13, vcc, 0, v13, vcc
; GCN-NEXT:    v_add_i32_e32 v14, vcc, 3, v14
; GCN-NEXT:    v_addc_u32_e32 v15, vcc, 0, v15, vcc
; GCN-NEXT:  .LBB22_2: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v8i64_to_v8f64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB22_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; VI-NEXT:    v_add_u32_e32 v8, vcc, 3, v8
; VI-NEXT:    v_addc_u32_e32 v9, vcc, 0, v9, vcc
; VI-NEXT:    v_add_u32_e32 v10, vcc, 3, v10
; VI-NEXT:    v_addc_u32_e32 v11, vcc, 0, v11, vcc
; VI-NEXT:    v_add_u32_e32 v12, vcc, 3, v12
; VI-NEXT:    v_addc_u32_e32 v13, vcc, 0, v13, vcc
; VI-NEXT:    v_add_u32_e32 v14, vcc, 3, v14
; VI-NEXT:    v_addc_u32_e32 v15, vcc, 0, v15, vcc
; VI-NEXT:  .LBB22_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v8i64_to_v8f64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB22_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_co_u32_e32 v0, vcc, 3, v0
; GFX9-NEXT:    v_addc_co_u32_e32 v1, vcc, 0, v1, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v2, vcc, 3, v2
; GFX9-NEXT:    v_addc_co_u32_e32 v3, vcc, 0, v3, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v4, vcc, 3, v4
; GFX9-NEXT:    v_addc_co_u32_e32 v5, vcc, 0, v5, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v6, vcc, 3, v6
; GFX9-NEXT:    v_addc_co_u32_e32 v7, vcc, 0, v7, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v8, vcc, 3, v8
; GFX9-NEXT:    v_addc_co_u32_e32 v9, vcc, 0, v9, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v10, vcc, 3, v10
; GFX9-NEXT:    v_addc_co_u32_e32 v11, vcc, 0, v11, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v12, vcc, 3, v12
; GFX9-NEXT:    v_addc_co_u32_e32 v13, vcc, 0, v13, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v14, vcc, 3, v14
; GFX9-NEXT:    v_addc_co_u32_e32 v15, vcc, 0, v15, vcc
; GFX9-NEXT:  .LBB22_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v8i64_to_v8f64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB22_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_co_u32 v0, vcc_lo, v0, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, 0, v1, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v2, vcc_lo, v2, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v3, vcc_lo, 0, v3, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v4, vcc_lo, v4, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v5, vcc_lo, 0, v5, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v6, vcc_lo, v6, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v7, vcc_lo, 0, v7, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v8, vcc_lo, v8, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v9, vcc_lo, 0, v9, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v10, vcc_lo, v10, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v11, vcc_lo, 0, v11, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v12, vcc_lo, v12, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v13, vcc_lo, 0, v13, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v14, vcc_lo, v14, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v15, vcc_lo, 0, v15, vcc_lo
; GFX11-NEXT:  .LBB22_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <8 x i64> %a, splat (i64 3)
  %a2 = bitcast <8 x i64> %a1 to <8 x double>
  br label %end

cmp.false:
  %a3 = bitcast <8 x i64> %a to <8 x double>
  br label %end

end:
  %phi = phi <8 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x double> %phi
}

define <8 x i64> @v_bitcast_v8f64_to_v8i64(<8 x double> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v8f64_to_v8i64:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB23_2
; GCN-NEXT:  ; %bb.1: ; %cmp.true
; GCN-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GCN-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GCN-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GCN-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GCN-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GCN-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GCN-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GCN-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GCN-NEXT:  .LBB23_2: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v8f64_to_v8i64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB23_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; VI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; VI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; VI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; VI-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; VI-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; VI-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; VI-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; VI-NEXT:  .LBB23_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v8f64_to_v8i64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB23_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX9-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX9-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GFX9-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GFX9-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GFX9-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GFX9-NEXT:  .LBB23_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v8f64_to_v8i64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB23_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX11-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX11-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX11-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX11-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GFX11-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GFX11-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GFX11-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GFX11-NEXT:  .LBB23_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <8 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <8 x double> %a1 to <8 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <8 x double> %a to <8 x i64>
  br label %end

end:
  %phi = phi <8 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x i64> %phi
}

define <32 x i16> @v_bitcast_v8i64_to_v32i16(<8 x i64> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v8i64_to_v32i16:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_mov_b32_e32 v30, v15
; GCN-NEXT:    v_mov_b32_e32 v28, v14
; GCN-NEXT:    v_mov_b32_e32 v26, v13
; GCN-NEXT:    v_mov_b32_e32 v24, v12
; GCN-NEXT:    v_mov_b32_e32 v22, v11
; GCN-NEXT:    v_mov_b32_e32 v20, v10
; GCN-NEXT:    v_mov_b32_e32 v18, v9
; GCN-NEXT:    v_mov_b32_e32 v32, v8
; GCN-NEXT:    v_mov_b32_e32 v14, v7
; GCN-NEXT:    v_mov_b32_e32 v12, v6
; GCN-NEXT:    v_mov_b32_e32 v10, v5
; GCN-NEXT:    v_mov_b32_e32 v8, v4
; GCN-NEXT:    v_mov_b32_e32 v6, v3
; GCN-NEXT:    v_mov_b32_e32 v4, v2
; GCN-NEXT:    v_mov_b32_e32 v2, v1
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GCN-NEXT:    ; implicit-def: $vgpr1
; GCN-NEXT:    ; implicit-def: $vgpr3
; GCN-NEXT:    ; implicit-def: $vgpr5
; GCN-NEXT:    ; implicit-def: $vgpr7
; GCN-NEXT:    ; implicit-def: $vgpr9
; GCN-NEXT:    ; implicit-def: $vgpr11
; GCN-NEXT:    ; implicit-def: $vgpr13
; GCN-NEXT:    ; implicit-def: $vgpr15
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr27
; GCN-NEXT:    ; implicit-def: $vgpr29
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB24_2
; GCN-NEXT:  ; %bb.1: ; %cmp.false
; GCN-NEXT:    v_alignbit_b32 v29, v30, v28, 16
; GCN-NEXT:    v_alignbit_b32 v25, v26, v24, 16
; GCN-NEXT:    v_alignbit_b32 v21, v22, v20, 16
; GCN-NEXT:    v_alignbit_b32 v17, v18, v32, 16
; GCN-NEXT:    v_alignbit_b32 v13, v14, v12, 16
; GCN-NEXT:    v_alignbit_b32 v9, v10, v8, 16
; GCN-NEXT:    v_alignbit_b32 v5, v6, v4, 16
; GCN-NEXT:    v_alignbit_b32 v1, v2, v0, 16
; GCN-NEXT:    v_lshrrev_b32_e32 v31, 16, v30
; GCN-NEXT:    v_lshrrev_b32_e32 v27, 16, v26
; GCN-NEXT:    v_lshrrev_b32_e32 v23, 16, v22
; GCN-NEXT:    v_lshrrev_b32_e32 v19, 16, v18
; GCN-NEXT:    v_lshrrev_b32_e32 v15, 16, v14
; GCN-NEXT:    v_lshrrev_b32_e32 v11, 16, v10
; GCN-NEXT:    v_lshrrev_b32_e32 v7, 16, v6
; GCN-NEXT:    v_lshrrev_b32_e32 v3, 16, v2
; GCN-NEXT:  .LBB24_2: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB24_4
; GCN-NEXT:  ; %bb.3: ; %cmp.true
; GCN-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; GCN-NEXT:    v_addc_u32_e32 v2, vcc, 0, v2, vcc
; GCN-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; GCN-NEXT:    v_addc_u32_e32 v6, vcc, 0, v6, vcc
; GCN-NEXT:    v_add_i32_e32 v8, vcc, 3, v8
; GCN-NEXT:    v_addc_u32_e32 v10, vcc, 0, v10, vcc
; GCN-NEXT:    v_add_i32_e32 v12, vcc, 3, v12
; GCN-NEXT:    v_addc_u32_e32 v14, vcc, 0, v14, vcc
; GCN-NEXT:    v_add_i32_e32 v32, vcc, 3, v32
; GCN-NEXT:    v_addc_u32_e32 v18, vcc, 0, v18, vcc
; GCN-NEXT:    v_add_i32_e32 v20, vcc, 3, v20
; GCN-NEXT:    v_addc_u32_e32 v22, vcc, 0, v22, vcc
; GCN-NEXT:    v_add_i32_e32 v24, vcc, 3, v24
; GCN-NEXT:    v_addc_u32_e32 v26, vcc, 0, v26, vcc
; GCN-NEXT:    v_add_i32_e32 v28, vcc, 3, v28
; GCN-NEXT:    v_addc_u32_e32 v30, vcc, 0, v30, vcc
; GCN-NEXT:    v_alignbit_b32 v29, v30, v28, 16
; GCN-NEXT:    v_alignbit_b32 v25, v26, v24, 16
; GCN-NEXT:    v_alignbit_b32 v21, v22, v20, 16
; GCN-NEXT:    v_alignbit_b32 v17, v18, v32, 16
; GCN-NEXT:    v_alignbit_b32 v13, v14, v12, 16
; GCN-NEXT:    v_alignbit_b32 v9, v10, v8, 16
; GCN-NEXT:    v_alignbit_b32 v5, v6, v4, 16
; GCN-NEXT:    v_alignbit_b32 v1, v2, v0, 16
; GCN-NEXT:    v_lshrrev_b32_e32 v31, 16, v30
; GCN-NEXT:    v_lshrrev_b32_e32 v27, 16, v26
; GCN-NEXT:    v_lshrrev_b32_e32 v23, 16, v22
; GCN-NEXT:    v_lshrrev_b32_e32 v19, 16, v18
; GCN-NEXT:    v_lshrrev_b32_e32 v15, 16, v14
; GCN-NEXT:    v_lshrrev_b32_e32 v11, 16, v10
; GCN-NEXT:    v_lshrrev_b32_e32 v7, 16, v6
; GCN-NEXT:    v_lshrrev_b32_e32 v3, 16, v2
; GCN-NEXT:  .LBB24_4: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    v_mov_b32_e32 v16, v32
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v8i64_to_v32i16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB24_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v14, vcc, 3, v14
; VI-NEXT:    v_addc_u32_e32 v15, vcc, 0, v15, vcc
; VI-NEXT:    v_add_u32_e32 v12, vcc, 3, v12
; VI-NEXT:    v_addc_u32_e32 v13, vcc, 0, v13, vcc
; VI-NEXT:    v_add_u32_e32 v10, vcc, 3, v10
; VI-NEXT:    v_addc_u32_e32 v11, vcc, 0, v11, vcc
; VI-NEXT:    v_add_u32_e32 v8, vcc, 3, v8
; VI-NEXT:    v_addc_u32_e32 v9, vcc, 0, v9, vcc
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-NEXT:  .LBB24_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v8i64_to_v32i16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB24_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_co_u32_e32 v14, vcc, 3, v14
; GFX9-NEXT:    v_addc_co_u32_e32 v15, vcc, 0, v15, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v12, vcc, 3, v12
; GFX9-NEXT:    v_addc_co_u32_e32 v13, vcc, 0, v13, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v10, vcc, 3, v10
; GFX9-NEXT:    v_addc_co_u32_e32 v11, vcc, 0, v11, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v8, vcc, 3, v8
; GFX9-NEXT:    v_addc_co_u32_e32 v9, vcc, 0, v9, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v6, vcc, 3, v6
; GFX9-NEXT:    v_addc_co_u32_e32 v7, vcc, 0, v7, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v4, vcc, 3, v4
; GFX9-NEXT:    v_addc_co_u32_e32 v5, vcc, 0, v5, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v2, vcc, 3, v2
; GFX9-NEXT:    v_addc_co_u32_e32 v3, vcc, 0, v3, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v0, vcc, 3, v0
; GFX9-NEXT:    v_addc_co_u32_e32 v1, vcc, 0, v1, vcc
; GFX9-NEXT:  .LBB24_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v8i64_to_v32i16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB24_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_co_u32 v14, vcc_lo, v14, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v15, vcc_lo, 0, v15, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v12, vcc_lo, v12, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v13, vcc_lo, 0, v13, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v10, vcc_lo, v10, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v11, vcc_lo, 0, v11, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v8, vcc_lo, v8, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v9, vcc_lo, 0, v9, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v6, vcc_lo, v6, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v7, vcc_lo, 0, v7, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v4, vcc_lo, v4, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v5, vcc_lo, 0, v5, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v2, vcc_lo, v2, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v3, vcc_lo, 0, v3, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v0, vcc_lo, v0, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, 0, v1, vcc_lo
; GFX11-NEXT:  .LBB24_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <8 x i64> %a, splat (i64 3)
  %a2 = bitcast <8 x i64> %a1 to <32 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <8 x i64> %a to <32 x i16>
  br label %end

end:
  %phi = phi <32 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x i16> %phi
}

define <8 x i64> @v_bitcast_v32i16_to_v8i64(<32 x i16> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v32i16_to_v8i64:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_mov_b32_e32 v38, v14
; GCN-NEXT:    v_mov_b32_e32 v37, v12
; GCN-NEXT:    v_mov_b32_e32 v36, v10
; GCN-NEXT:    v_mov_b32_e32 v35, v8
; GCN-NEXT:    v_mov_b32_e32 v34, v6
; GCN-NEXT:    v_mov_b32_e32 v33, v4
; GCN-NEXT:    v_mov_b32_e32 v32, v2
; GCN-NEXT:    v_mov_b32_e32 v31, v0
; GCN-NEXT:    buffer_load_dword v0, off, s[0:3], s32
; GCN-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:4
; GCN-NEXT:    v_lshlrev_b32_e32 v54, 16, v1
; GCN-NEXT:    v_lshlrev_b32_e32 v55, 16, v3
; GCN-NEXT:    v_lshlrev_b32_e32 v39, 16, v5
; GCN-NEXT:    v_lshlrev_b32_e32 v48, 16, v7
; GCN-NEXT:    v_lshlrev_b32_e32 v49, 16, v9
; GCN-NEXT:    v_lshlrev_b32_e32 v50, 16, v11
; GCN-NEXT:    v_lshlrev_b32_e32 v51, 16, v13
; GCN-NEXT:    v_lshlrev_b32_e32 v52, 16, v15
; GCN-NEXT:    v_lshlrev_b32_e32 v17, 16, v17
; GCN-NEXT:    v_lshlrev_b32_e32 v19, 16, v19
; GCN-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; GCN-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; GCN-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; GCN-NEXT:    v_lshlrev_b32_e32 v27, 16, v27
; GCN-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v2
; GCN-NEXT:    v_lshlrev_b32_e32 v53, 16, v0
; GCN-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execnz .LBB25_3
; GCN-NEXT:  ; %bb.1: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execnz .LBB25_4
; GCN-NEXT:  .LBB25_2: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
; GCN-NEXT:  .LBB25_3: ; %cmp.false
; GCN-NEXT:    v_and_b32_e32 v0, 0xffff, v31
; GCN-NEXT:    v_and_b32_e32 v1, 0xffff, v32
; GCN-NEXT:    v_or_b32_e32 v0, v0, v54
; GCN-NEXT:    v_or_b32_e32 v1, v1, v55
; GCN-NEXT:    v_and_b32_e32 v2, 0xffff, v33
; GCN-NEXT:    v_and_b32_e32 v3, 0xffff, v34
; GCN-NEXT:    v_and_b32_e32 v4, 0xffff, v35
; GCN-NEXT:    v_and_b32_e32 v5, 0xffff, v36
; GCN-NEXT:    v_and_b32_e32 v6, 0xffff, v37
; GCN-NEXT:    v_and_b32_e32 v7, 0xffff, v38
; GCN-NEXT:    v_and_b32_e32 v8, 0xffff, v16
; GCN-NEXT:    v_and_b32_e32 v9, 0xffff, v18
; GCN-NEXT:    v_and_b32_e32 v10, 0xffff, v20
; GCN-NEXT:    v_and_b32_e32 v11, 0xffff, v22
; GCN-NEXT:    v_and_b32_e32 v12, 0xffff, v24
; GCN-NEXT:    v_and_b32_e32 v13, 0xffff, v26
; GCN-NEXT:    v_and_b32_e32 v14, 0xffff, v28
; GCN-NEXT:    v_and_b32_e32 v15, 0xffff, v30
; GCN-NEXT:    v_or_b32_e32 v2, v2, v39
; GCN-NEXT:    v_or_b32_e32 v3, v3, v48
; GCN-NEXT:    v_or_b32_e32 v4, v4, v49
; GCN-NEXT:    v_or_b32_e32 v5, v5, v50
; GCN-NEXT:    v_or_b32_e32 v6, v6, v51
; GCN-NEXT:    v_or_b32_e32 v7, v7, v52
; GCN-NEXT:    v_or_b32_e32 v8, v8, v17
; GCN-NEXT:    v_or_b32_e32 v9, v9, v19
; GCN-NEXT:    v_or_b32_e32 v10, v10, v21
; GCN-NEXT:    v_or_b32_e32 v11, v11, v23
; GCN-NEXT:    v_or_b32_e32 v12, v12, v25
; GCN-NEXT:    v_or_b32_e32 v13, v13, v27
; GCN-NEXT:    v_or_b32_e32 v14, v14, v29
; GCN-NEXT:    v_or_b32_e32 v15, v15, v53
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    ; implicit-def: $vgpr32
; GCN-NEXT:    ; implicit-def: $vgpr33
; GCN-NEXT:    ; implicit-def: $vgpr34
; GCN-NEXT:    ; implicit-def: $vgpr35
; GCN-NEXT:    ; implicit-def: $vgpr36
; GCN-NEXT:    ; implicit-def: $vgpr37
; GCN-NEXT:    ; implicit-def: $vgpr38
; GCN-NEXT:    ; implicit-def: $vgpr16
; GCN-NEXT:    ; implicit-def: $vgpr18
; GCN-NEXT:    ; implicit-def: $vgpr20
; GCN-NEXT:    ; implicit-def: $vgpr22
; GCN-NEXT:    ; implicit-def: $vgpr24
; GCN-NEXT:    ; implicit-def: $vgpr26
; GCN-NEXT:    ; implicit-def: $vgpr28
; GCN-NEXT:    ; implicit-def: $vgpr30
; GCN-NEXT:    ; implicit-def: $vgpr54
; GCN-NEXT:    ; implicit-def: $vgpr55
; GCN-NEXT:    ; implicit-def: $vgpr39
; GCN-NEXT:    ; implicit-def: $vgpr48
; GCN-NEXT:    ; implicit-def: $vgpr49
; GCN-NEXT:    ; implicit-def: $vgpr50
; GCN-NEXT:    ; implicit-def: $vgpr51
; GCN-NEXT:    ; implicit-def: $vgpr52
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr27
; GCN-NEXT:    ; implicit-def: $vgpr29
; GCN-NEXT:    ; implicit-def: $vgpr53
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB25_2
; GCN-NEXT:  .LBB25_4: ; %cmp.true
; GCN-NEXT:    v_add_i32_e32 v0, vcc, 3, v31
; GCN-NEXT:    s_mov_b32 s6, 0x30000
; GCN-NEXT:    v_add_i32_e32 v1, vcc, 3, v32
; GCN-NEXT:    v_add_i32_e32 v2, vcc, 3, v33
; GCN-NEXT:    v_add_i32_e32 v3, vcc, 3, v34
; GCN-NEXT:    v_add_i32_e32 v4, vcc, 3, v35
; GCN-NEXT:    v_add_i32_e32 v5, vcc, 3, v36
; GCN-NEXT:    v_add_i32_e32 v6, vcc, 3, v37
; GCN-NEXT:    v_add_i32_e32 v7, vcc, 3, v38
; GCN-NEXT:    v_add_i32_e32 v8, vcc, 3, v16
; GCN-NEXT:    v_add_i32_e32 v9, vcc, 3, v18
; GCN-NEXT:    v_add_i32_e32 v10, vcc, 3, v20
; GCN-NEXT:    v_add_i32_e32 v11, vcc, 3, v22
; GCN-NEXT:    v_add_i32_e32 v12, vcc, 3, v24
; GCN-NEXT:    v_add_i32_e32 v13, vcc, 3, v26
; GCN-NEXT:    v_add_i32_e32 v14, vcc, 3, v28
; GCN-NEXT:    v_add_i32_e32 v15, vcc, 3, v30
; GCN-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GCN-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; GCN-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GCN-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GCN-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GCN-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GCN-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; GCN-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; GCN-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; GCN-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; GCN-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; GCN-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; GCN-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; GCN-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; GCN-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; GCN-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; GCN-NEXT:    v_or_b32_e32 v0, v54, v0
; GCN-NEXT:    v_or_b32_e32 v1, v55, v1
; GCN-NEXT:    v_or_b32_e32 v2, v39, v2
; GCN-NEXT:    v_or_b32_e32 v3, v48, v3
; GCN-NEXT:    v_or_b32_e32 v4, v49, v4
; GCN-NEXT:    v_or_b32_e32 v5, v50, v5
; GCN-NEXT:    v_or_b32_e32 v6, v51, v6
; GCN-NEXT:    v_or_b32_e32 v7, v52, v7
; GCN-NEXT:    v_or_b32_e32 v8, v17, v8
; GCN-NEXT:    v_or_b32_e32 v9, v19, v9
; GCN-NEXT:    v_or_b32_e32 v10, v21, v10
; GCN-NEXT:    v_or_b32_e32 v11, v23, v11
; GCN-NEXT:    v_or_b32_e32 v12, v25, v12
; GCN-NEXT:    v_or_b32_e32 v13, v27, v13
; GCN-NEXT:    v_or_b32_e32 v14, v29, v14
; GCN-NEXT:    v_or_b32_e32 v15, v53, v15
; GCN-NEXT:    v_add_i32_e32 v0, vcc, 0x30000, v0
; GCN-NEXT:    v_add_i32_e32 v1, vcc, s6, v1
; GCN-NEXT:    v_add_i32_e32 v2, vcc, s6, v2
; GCN-NEXT:    v_add_i32_e32 v3, vcc, s6, v3
; GCN-NEXT:    v_add_i32_e32 v4, vcc, s6, v4
; GCN-NEXT:    v_add_i32_e32 v5, vcc, s6, v5
; GCN-NEXT:    v_add_i32_e32 v6, vcc, s6, v6
; GCN-NEXT:    v_add_i32_e32 v7, vcc, s6, v7
; GCN-NEXT:    v_add_i32_e32 v8, vcc, s6, v8
; GCN-NEXT:    v_add_i32_e32 v9, vcc, s6, v9
; GCN-NEXT:    v_add_i32_e32 v10, vcc, s6, v10
; GCN-NEXT:    v_add_i32_e32 v11, vcc, s6, v11
; GCN-NEXT:    v_add_i32_e32 v12, vcc, s6, v12
; GCN-NEXT:    v_add_i32_e32 v13, vcc, 0x30000, v13
; GCN-NEXT:    v_add_i32_e32 v14, vcc, 0x30000, v14
; GCN-NEXT:    v_add_i32_e32 v15, vcc, 0x30000, v15
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v32i16_to_v8i64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB25_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v17, 3
; VI-NEXT:    v_add_u16_e32 v16, 3, v15
; VI-NEXT:    v_add_u16_sdwa v15, v15, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v15, v16, v15
; VI-NEXT:    v_add_u16_e32 v16, 3, v14
; VI-NEXT:    v_add_u16_sdwa v14, v14, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v14, v16, v14
; VI-NEXT:    v_add_u16_e32 v16, 3, v13
; VI-NEXT:    v_add_u16_sdwa v13, v13, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v13, v16, v13
; VI-NEXT:    v_add_u16_e32 v16, 3, v12
; VI-NEXT:    v_add_u16_sdwa v12, v12, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v12, v16, v12
; VI-NEXT:    v_add_u16_e32 v16, 3, v11
; VI-NEXT:    v_add_u16_sdwa v11, v11, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v11, v16, v11
; VI-NEXT:    v_add_u16_e32 v16, 3, v10
; VI-NEXT:    v_add_u16_sdwa v10, v10, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v10, v16, v10
; VI-NEXT:    v_add_u16_e32 v16, 3, v9
; VI-NEXT:    v_add_u16_sdwa v9, v9, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v9, v16, v9
; VI-NEXT:    v_add_u16_e32 v16, 3, v8
; VI-NEXT:    v_add_u16_sdwa v8, v8, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v8, v16, v8
; VI-NEXT:    v_add_u16_e32 v16, 3, v7
; VI-NEXT:    v_add_u16_sdwa v7, v7, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v7, v16, v7
; VI-NEXT:    v_add_u16_e32 v16, 3, v6
; VI-NEXT:    v_add_u16_sdwa v6, v6, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v6, v16, v6
; VI-NEXT:    v_add_u16_e32 v16, 3, v5
; VI-NEXT:    v_add_u16_sdwa v5, v5, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v5, v16, v5
; VI-NEXT:    v_add_u16_e32 v16, 3, v4
; VI-NEXT:    v_add_u16_sdwa v4, v4, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v4, v16, v4
; VI-NEXT:    v_add_u16_e32 v16, 3, v3
; VI-NEXT:    v_add_u16_sdwa v3, v3, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v3, v16, v3
; VI-NEXT:    v_add_u16_e32 v16, 3, v2
; VI-NEXT:    v_add_u16_sdwa v2, v2, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v2, v16, v2
; VI-NEXT:    v_add_u16_e32 v16, 3, v1
; VI-NEXT:    v_add_u16_sdwa v1, v1, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v1, v16, v1
; VI-NEXT:    v_add_u16_e32 v16, 3, v0
; VI-NEXT:    v_add_u16_sdwa v0, v0, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v0, v16, v0
; VI-NEXT:  .LBB25_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v32i16_to_v8i64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB25_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_pk_add_u16 v15, v15, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v14, v14, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v13, v13, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v12, v12, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v9, v9, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v8, v8, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX9-NEXT:  .LBB25_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v32i16_to_v8i64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB25_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_pk_add_u16 v15, v15, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v14, v14, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v13, v13, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v12, v12, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v9, v9, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v8, v8, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX11-NEXT:  .LBB25_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <32 x i16> %a, splat (i16 3)
  %a2 = bitcast <32 x i16> %a1 to <8 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <32 x i16> %a to <8 x i64>
  br label %end

end:
  %phi = phi <8 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x i64> %phi
}

define <32 x half> @v_bitcast_v8i64_to_v32f16(<8 x i64> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v8i64_to_v32f16:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v46, off, s[0:3], s32 ; 4-byte Folded Spill
; GCN-NEXT:    v_mov_b32_e32 v34, v15
; GCN-NEXT:    v_mov_b32_e32 v33, v14
; GCN-NEXT:    v_mov_b32_e32 v36, v13
; GCN-NEXT:    v_mov_b32_e32 v35, v12
; GCN-NEXT:    v_mov_b32_e32 v38, v11
; GCN-NEXT:    v_mov_b32_e32 v37, v10
; GCN-NEXT:    v_mov_b32_e32 v48, v9
; GCN-NEXT:    v_mov_b32_e32 v39, v8
; GCN-NEXT:    v_mov_b32_e32 v50, v7
; GCN-NEXT:    v_mov_b32_e32 v49, v6
; GCN-NEXT:    v_mov_b32_e32 v52, v5
; GCN-NEXT:    v_mov_b32_e32 v51, v4
; GCN-NEXT:    v_mov_b32_e32 v54, v3
; GCN-NEXT:    v_mov_b32_e32 v53, v2
; GCN-NEXT:    v_mov_b32_e32 v55, v1
; GCN-NEXT:    v_mov_b32_e32 v32, v0
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GCN-NEXT:    ; implicit-def: $vgpr0
; GCN-NEXT:    ; implicit-def: $vgpr1
; GCN-NEXT:    ; implicit-def: $vgpr2
; GCN-NEXT:    ; implicit-def: $vgpr3
; GCN-NEXT:    ; implicit-def: $vgpr4
; GCN-NEXT:    ; implicit-def: $vgpr5
; GCN-NEXT:    ; implicit-def: $vgpr6
; GCN-NEXT:    ; implicit-def: $vgpr7
; GCN-NEXT:    ; implicit-def: $vgpr8
; GCN-NEXT:    ; implicit-def: $vgpr9
; GCN-NEXT:    ; implicit-def: $vgpr10
; GCN-NEXT:    ; implicit-def: $vgpr11
; GCN-NEXT:    ; implicit-def: $vgpr12
; GCN-NEXT:    ; implicit-def: $vgpr13
; GCN-NEXT:    ; implicit-def: $vgpr14
; GCN-NEXT:    ; implicit-def: $vgpr15
; GCN-NEXT:    ; implicit-def: $vgpr16
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr18
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr20
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr22
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr24
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr26
; GCN-NEXT:    ; implicit-def: $vgpr27
; GCN-NEXT:    ; implicit-def: $vgpr28
; GCN-NEXT:    ; implicit-def: $vgpr29
; GCN-NEXT:    ; implicit-def: $vgpr30
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB26_2
; GCN-NEXT:  ; %bb.1: ; %cmp.false
; GCN-NEXT:    v_lshrrev_b32_e32 v0, 16, v34
; GCN-NEXT:    v_lshrrev_b32_e32 v1, 16, v33
; GCN-NEXT:    v_lshrrev_b32_e32 v3, 16, v36
; GCN-NEXT:    v_lshrrev_b32_e32 v5, 16, v35
; GCN-NEXT:    v_lshrrev_b32_e32 v7, 16, v38
; GCN-NEXT:    v_lshrrev_b32_e32 v9, 16, v37
; GCN-NEXT:    v_lshrrev_b32_e32 v11, 16, v48
; GCN-NEXT:    v_lshrrev_b32_e32 v13, 16, v39
; GCN-NEXT:    v_lshrrev_b32_e32 v15, 16, v50
; GCN-NEXT:    s_waitcnt expcnt(6)
; GCN-NEXT:    v_lshrrev_b32_e32 v40, 16, v49
; GCN-NEXT:    s_waitcnt expcnt(5)
; GCN-NEXT:    v_lshrrev_b32_e32 v41, 16, v52
; GCN-NEXT:    s_waitcnt expcnt(4)
; GCN-NEXT:    v_lshrrev_b32_e32 v42, 16, v51
; GCN-NEXT:    s_waitcnt expcnt(3)
; GCN-NEXT:    v_lshrrev_b32_e32 v43, 16, v54
; GCN-NEXT:    s_waitcnt expcnt(2)
; GCN-NEXT:    v_lshrrev_b32_e32 v44, 16, v53
; GCN-NEXT:    s_waitcnt expcnt(1)
; GCN-NEXT:    v_lshrrev_b32_e32 v45, 16, v55
; GCN-NEXT:    s_waitcnt expcnt(0)
; GCN-NEXT:    v_lshrrev_b32_e32 v46, 16, v32
; GCN-NEXT:    v_cvt_f32_f16_e32 v30, v34
; GCN-NEXT:    v_cvt_f32_f16_e32 v28, v33
; GCN-NEXT:    v_cvt_f32_f16_e32 v26, v36
; GCN-NEXT:    v_cvt_f32_f16_e32 v24, v35
; GCN-NEXT:    v_cvt_f32_f16_e32 v22, v38
; GCN-NEXT:    v_cvt_f32_f16_e32 v20, v37
; GCN-NEXT:    v_cvt_f32_f16_e32 v18, v48
; GCN-NEXT:    v_cvt_f32_f16_e32 v16, v39
; GCN-NEXT:    v_cvt_f32_f16_e32 v14, v50
; GCN-NEXT:    v_cvt_f32_f16_e32 v12, v49
; GCN-NEXT:    v_cvt_f32_f16_e32 v10, v52
; GCN-NEXT:    v_cvt_f32_f16_e32 v8, v51
; GCN-NEXT:    v_cvt_f32_f16_e32 v6, v54
; GCN-NEXT:    v_cvt_f32_f16_e32 v4, v53
; GCN-NEXT:    v_cvt_f32_f16_e32 v2, v55
; GCN-NEXT:    v_cvt_f32_f16_e32 v31, v0
; GCN-NEXT:    v_cvt_f32_f16_e32 v29, v1
; GCN-NEXT:    v_cvt_f32_f16_e32 v27, v3
; GCN-NEXT:    v_cvt_f32_f16_e32 v25, v5
; GCN-NEXT:    v_cvt_f32_f16_e32 v23, v7
; GCN-NEXT:    v_cvt_f32_f16_e32 v21, v9
; GCN-NEXT:    v_cvt_f32_f16_e32 v19, v11
; GCN-NEXT:    v_cvt_f32_f16_e32 v17, v13
; GCN-NEXT:    v_cvt_f32_f16_e32 v15, v15
; GCN-NEXT:    v_cvt_f32_f16_e32 v13, v40
; GCN-NEXT:    v_cvt_f32_f16_e32 v11, v41
; GCN-NEXT:    v_cvt_f32_f16_e32 v9, v42
; GCN-NEXT:    v_cvt_f32_f16_e32 v7, v43
; GCN-NEXT:    v_cvt_f32_f16_e32 v5, v44
; GCN-NEXT:    v_cvt_f32_f16_e32 v3, v45
; GCN-NEXT:    v_cvt_f32_f16_e32 v1, v46
; GCN-NEXT:    v_cvt_f32_f16_e32 v0, v32
; GCN-NEXT:    ; implicit-def: $vgpr32
; GCN-NEXT:    ; implicit-def: $vgpr55
; GCN-NEXT:    ; implicit-def: $vgpr53
; GCN-NEXT:    ; implicit-def: $vgpr54
; GCN-NEXT:    ; implicit-def: $vgpr51
; GCN-NEXT:    ; implicit-def: $vgpr52
; GCN-NEXT:    ; implicit-def: $vgpr49
; GCN-NEXT:    ; implicit-def: $vgpr50
; GCN-NEXT:    ; implicit-def: $vgpr39
; GCN-NEXT:    ; implicit-def: $vgpr48
; GCN-NEXT:    ; implicit-def: $vgpr37
; GCN-NEXT:    ; implicit-def: $vgpr38
; GCN-NEXT:    ; implicit-def: $vgpr35
; GCN-NEXT:    ; implicit-def: $vgpr36
; GCN-NEXT:    ; implicit-def: $vgpr33
; GCN-NEXT:    ; implicit-def: $vgpr34
; GCN-NEXT:  .LBB26_2: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB26_4
; GCN-NEXT:  ; %bb.3: ; %cmp.true
; GCN-NEXT:    v_add_i32_e32 v0, vcc, 3, v32
; GCN-NEXT:    v_addc_u32_e32 v1, vcc, 0, v55, vcc
; GCN-NEXT:    v_add_i32_e32 v2, vcc, 3, v53
; GCN-NEXT:    v_addc_u32_e32 v3, vcc, 0, v54, vcc
; GCN-NEXT:    v_add_i32_e32 v4, vcc, 3, v51
; GCN-NEXT:    v_addc_u32_e32 v5, vcc, 0, v52, vcc
; GCN-NEXT:    v_add_i32_e32 v6, vcc, 3, v49
; GCN-NEXT:    v_addc_u32_e32 v7, vcc, 0, v50, vcc
; GCN-NEXT:    v_add_i32_e32 v8, vcc, 3, v39
; GCN-NEXT:    v_addc_u32_e32 v9, vcc, 0, v48, vcc
; GCN-NEXT:    v_add_i32_e32 v10, vcc, 3, v37
; GCN-NEXT:    v_addc_u32_e32 v11, vcc, 0, v38, vcc
; GCN-NEXT:    v_add_i32_e32 v12, vcc, 3, v35
; GCN-NEXT:    v_addc_u32_e32 v13, vcc, 0, v36, vcc
; GCN-NEXT:    v_add_i32_e32 v14, vcc, 3, v33
; GCN-NEXT:    v_addc_u32_e32 v15, vcc, 0, v34, vcc
; GCN-NEXT:    v_lshrrev_b32_e32 v32, 16, v0
; GCN-NEXT:    v_lshrrev_b32_e32 v33, 16, v1
; GCN-NEXT:    v_lshrrev_b32_e32 v34, 16, v2
; GCN-NEXT:    v_lshrrev_b32_e32 v35, 16, v3
; GCN-NEXT:    v_lshrrev_b32_e32 v36, 16, v4
; GCN-NEXT:    v_lshrrev_b32_e32 v37, 16, v5
; GCN-NEXT:    v_lshrrev_b32_e32 v38, 16, v6
; GCN-NEXT:    v_lshrrev_b32_e32 v39, 16, v7
; GCN-NEXT:    v_lshrrev_b32_e32 v17, 16, v8
; GCN-NEXT:    v_lshrrev_b32_e32 v19, 16, v9
; GCN-NEXT:    v_lshrrev_b32_e32 v21, 16, v10
; GCN-NEXT:    v_lshrrev_b32_e32 v23, 16, v11
; GCN-NEXT:    v_lshrrev_b32_e32 v25, 16, v12
; GCN-NEXT:    v_lshrrev_b32_e32 v27, 16, v13
; GCN-NEXT:    v_lshrrev_b32_e32 v29, 16, v14
; GCN-NEXT:    v_lshrrev_b32_e32 v31, 16, v15
; GCN-NEXT:    v_cvt_f32_f16_e32 v30, v15
; GCN-NEXT:    v_cvt_f32_f16_e32 v28, v14
; GCN-NEXT:    v_cvt_f32_f16_e32 v26, v13
; GCN-NEXT:    v_cvt_f32_f16_e32 v24, v12
; GCN-NEXT:    v_cvt_f32_f16_e32 v22, v11
; GCN-NEXT:    v_cvt_f32_f16_e32 v20, v10
; GCN-NEXT:    v_cvt_f32_f16_e32 v18, v9
; GCN-NEXT:    v_cvt_f32_f16_e32 v16, v8
; GCN-NEXT:    v_cvt_f32_f16_e32 v14, v7
; GCN-NEXT:    v_cvt_f32_f16_e32 v12, v6
; GCN-NEXT:    v_cvt_f32_f16_e32 v10, v5
; GCN-NEXT:    v_cvt_f32_f16_e32 v8, v4
; GCN-NEXT:    v_cvt_f32_f16_e32 v6, v3
; GCN-NEXT:    v_cvt_f32_f16_e32 v4, v2
; GCN-NEXT:    v_cvt_f32_f16_e32 v2, v1
; GCN-NEXT:    v_cvt_f32_f16_e32 v0, v0
; GCN-NEXT:    v_cvt_f32_f16_e32 v31, v31
; GCN-NEXT:    v_cvt_f32_f16_e32 v29, v29
; GCN-NEXT:    v_cvt_f32_f16_e32 v27, v27
; GCN-NEXT:    v_cvt_f32_f16_e32 v25, v25
; GCN-NEXT:    v_cvt_f32_f16_e32 v23, v23
; GCN-NEXT:    v_cvt_f32_f16_e32 v21, v21
; GCN-NEXT:    v_cvt_f32_f16_e32 v19, v19
; GCN-NEXT:    v_cvt_f32_f16_e32 v17, v17
; GCN-NEXT:    v_cvt_f32_f16_e32 v15, v39
; GCN-NEXT:    v_cvt_f32_f16_e32 v13, v38
; GCN-NEXT:    v_cvt_f32_f16_e32 v11, v37
; GCN-NEXT:    v_cvt_f32_f16_e32 v9, v36
; GCN-NEXT:    v_cvt_f32_f16_e32 v7, v35
; GCN-NEXT:    v_cvt_f32_f16_e32 v5, v34
; GCN-NEXT:    v_cvt_f32_f16_e32 v3, v33
; GCN-NEXT:    v_cvt_f32_f16_e32 v1, v32
; GCN-NEXT:  .LBB26_4: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_waitcnt expcnt(0)
; GCN-NEXT:    buffer_load_dword v46, off, s[0:3], s32 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v8i64_to_v32f16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB26_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v14, vcc, 3, v14
; VI-NEXT:    v_addc_u32_e32 v15, vcc, 0, v15, vcc
; VI-NEXT:    v_add_u32_e32 v12, vcc, 3, v12
; VI-NEXT:    v_addc_u32_e32 v13, vcc, 0, v13, vcc
; VI-NEXT:    v_add_u32_e32 v10, vcc, 3, v10
; VI-NEXT:    v_addc_u32_e32 v11, vcc, 0, v11, vcc
; VI-NEXT:    v_add_u32_e32 v8, vcc, 3, v8
; VI-NEXT:    v_addc_u32_e32 v9, vcc, 0, v9, vcc
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-NEXT:  .LBB26_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v8i64_to_v32f16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB26_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_co_u32_e32 v14, vcc, 3, v14
; GFX9-NEXT:    v_addc_co_u32_e32 v15, vcc, 0, v15, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v12, vcc, 3, v12
; GFX9-NEXT:    v_addc_co_u32_e32 v13, vcc, 0, v13, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v10, vcc, 3, v10
; GFX9-NEXT:    v_addc_co_u32_e32 v11, vcc, 0, v11, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v8, vcc, 3, v8
; GFX9-NEXT:    v_addc_co_u32_e32 v9, vcc, 0, v9, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v6, vcc, 3, v6
; GFX9-NEXT:    v_addc_co_u32_e32 v7, vcc, 0, v7, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v4, vcc, 3, v4
; GFX9-NEXT:    v_addc_co_u32_e32 v5, vcc, 0, v5, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v2, vcc, 3, v2
; GFX9-NEXT:    v_addc_co_u32_e32 v3, vcc, 0, v3, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v0, vcc, 3, v0
; GFX9-NEXT:    v_addc_co_u32_e32 v1, vcc, 0, v1, vcc
; GFX9-NEXT:  .LBB26_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v8i64_to_v32f16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB26_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_co_u32 v14, vcc_lo, v14, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v15, vcc_lo, 0, v15, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v12, vcc_lo, v12, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v13, vcc_lo, 0, v13, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v10, vcc_lo, v10, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v11, vcc_lo, 0, v11, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v8, vcc_lo, v8, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v9, vcc_lo, 0, v9, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v6, vcc_lo, v6, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v7, vcc_lo, 0, v7, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v4, vcc_lo, v4, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v5, vcc_lo, 0, v5, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v2, vcc_lo, v2, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v3, vcc_lo, 0, v3, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v0, vcc_lo, v0, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, 0, v1, vcc_lo
; GFX11-NEXT:  .LBB26_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <8 x i64> %a, splat (i64 3)
  %a2 = bitcast <8 x i64> %a1 to <32 x half>
  br label %end

cmp.false:
  %a3 = bitcast <8 x i64> %a to <32 x half>
  br label %end

end:
  %phi = phi <32 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x half> %phi
}

define <8 x i64> @v_bitcast_v32f16_to_v8i64(<32 x half> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v32f16_to_v8i64:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GCN-NEXT:    s_waitcnt expcnt(1)
; GCN-NEXT:    buffer_load_dword v46, off, s[0:3], s32
; GCN-NEXT:    s_waitcnt expcnt(0)
; GCN-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:4
; GCN-NEXT:    v_cvt_f16_f32_e32 v45, v1
; GCN-NEXT:    v_cvt_f16_f32_e32 v44, v0
; GCN-NEXT:    v_cvt_f16_f32_e32 v43, v3
; GCN-NEXT:    v_cvt_f16_f32_e32 v42, v2
; GCN-NEXT:    v_cvt_f16_f32_e32 v41, v5
; GCN-NEXT:    v_cvt_f16_f32_e32 v52, v4
; GCN-NEXT:    v_cvt_f16_f32_e32 v40, v7
; GCN-NEXT:    v_cvt_f16_f32_e32 v50, v6
; GCN-NEXT:    v_cvt_f16_f32_e32 v55, v9
; GCN-NEXT:    v_cvt_f16_f32_e32 v48, v8
; GCN-NEXT:    v_cvt_f16_f32_e32 v54, v11
; GCN-NEXT:    v_cvt_f16_f32_e32 v38, v10
; GCN-NEXT:    v_cvt_f16_f32_e32 v53, v13
; GCN-NEXT:    v_cvt_f16_f32_e32 v36, v12
; GCN-NEXT:    v_cvt_f16_f32_e32 v51, v15
; GCN-NEXT:    v_cvt_f16_f32_e32 v34, v14
; GCN-NEXT:    v_cvt_f16_f32_e32 v49, v17
; GCN-NEXT:    v_cvt_f16_f32_e32 v33, v16
; GCN-NEXT:    v_cvt_f16_f32_e32 v39, v19
; GCN-NEXT:    v_cvt_f16_f32_e32 v32, v18
; GCN-NEXT:    v_cvt_f16_f32_e32 v37, v21
; GCN-NEXT:    v_cvt_f16_f32_e32 v31, v20
; GCN-NEXT:    v_cvt_f16_f32_e32 v35, v23
; GCN-NEXT:    v_cvt_f16_f32_e32 v21, v22
; GCN-NEXT:    v_cvt_f16_f32_e32 v25, v25
; GCN-NEXT:    v_cvt_f16_f32_e32 v19, v24
; GCN-NEXT:    v_cvt_f16_f32_e32 v23, v27
; GCN-NEXT:    v_cvt_f16_f32_e32 v18, v26
; GCN-NEXT:    v_cvt_f16_f32_e32 v22, v29
; GCN-NEXT:    v_cvt_f16_f32_e32 v17, v28
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v47
; GCN-NEXT:    v_cvt_f16_f32_e32 v20, v46
; GCN-NEXT:    v_cvt_f16_f32_e32 v16, v30
; GCN-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB27_2
; GCN-NEXT:  ; %bb.1: ; %cmp.false
; GCN-NEXT:    v_lshlrev_b32_e32 v0, 16, v45
; GCN-NEXT:    v_lshlrev_b32_e32 v1, 16, v43
; GCN-NEXT:    v_or_b32_e32 v0, v44, v0
; GCN-NEXT:    v_or_b32_e32 v1, v42, v1
; GCN-NEXT:    v_lshlrev_b32_e32 v2, 16, v41
; GCN-NEXT:    v_lshlrev_b32_e32 v3, 16, v40
; GCN-NEXT:    v_lshlrev_b32_e32 v4, 16, v55
; GCN-NEXT:    v_lshlrev_b32_e32 v5, 16, v54
; GCN-NEXT:    v_lshlrev_b32_e32 v6, 16, v53
; GCN-NEXT:    v_lshlrev_b32_e32 v7, 16, v51
; GCN-NEXT:    v_lshlrev_b32_e32 v8, 16, v49
; GCN-NEXT:    v_lshlrev_b32_e32 v9, 16, v39
; GCN-NEXT:    v_lshlrev_b32_e32 v10, 16, v37
; GCN-NEXT:    v_lshlrev_b32_e32 v11, 16, v35
; GCN-NEXT:    v_lshlrev_b32_e32 v12, 16, v25
; GCN-NEXT:    v_lshlrev_b32_e32 v13, 16, v23
; GCN-NEXT:    v_lshlrev_b32_e32 v14, 16, v22
; GCN-NEXT:    v_lshlrev_b32_e32 v15, 16, v20
; GCN-NEXT:    v_or_b32_e32 v2, v52, v2
; GCN-NEXT:    v_or_b32_e32 v3, v50, v3
; GCN-NEXT:    v_or_b32_e32 v4, v48, v4
; GCN-NEXT:    v_or_b32_e32 v5, v38, v5
; GCN-NEXT:    v_or_b32_e32 v6, v36, v6
; GCN-NEXT:    v_or_b32_e32 v7, v34, v7
; GCN-NEXT:    v_or_b32_e32 v8, v33, v8
; GCN-NEXT:    v_or_b32_e32 v9, v32, v9
; GCN-NEXT:    v_or_b32_e32 v10, v31, v10
; GCN-NEXT:    v_or_b32_e32 v11, v21, v11
; GCN-NEXT:    v_or_b32_e32 v12, v19, v12
; GCN-NEXT:    v_or_b32_e32 v13, v18, v13
; GCN-NEXT:    v_or_b32_e32 v14, v17, v14
; GCN-NEXT:    v_or_b32_e32 v15, v16, v15
; GCN-NEXT:    ; implicit-def: $vgpr45
; GCN-NEXT:    ; implicit-def: $vgpr44
; GCN-NEXT:    ; implicit-def: $vgpr43
; GCN-NEXT:    ; implicit-def: $vgpr42
; GCN-NEXT:    ; implicit-def: $vgpr41
; GCN-NEXT:    ; implicit-def: $vgpr52
; GCN-NEXT:    ; implicit-def: $vgpr40
; GCN-NEXT:    ; implicit-def: $vgpr50
; GCN-NEXT:    ; implicit-def: $vgpr55
; GCN-NEXT:    ; implicit-def: $vgpr48
; GCN-NEXT:    ; implicit-def: $vgpr54
; GCN-NEXT:    ; implicit-def: $vgpr38
; GCN-NEXT:    ; implicit-def: $vgpr53
; GCN-NEXT:    ; implicit-def: $vgpr36
; GCN-NEXT:    ; implicit-def: $vgpr51
; GCN-NEXT:    ; implicit-def: $vgpr34
; GCN-NEXT:    ; implicit-def: $vgpr49
; GCN-NEXT:    ; implicit-def: $vgpr33
; GCN-NEXT:    ; implicit-def: $vgpr39
; GCN-NEXT:    ; implicit-def: $vgpr32
; GCN-NEXT:    ; implicit-def: $vgpr37
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    ; implicit-def: $vgpr35
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr18
; GCN-NEXT:    ; implicit-def: $vgpr22
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr20
; GCN-NEXT:    ; implicit-def: $vgpr16
; GCN-NEXT:  .LBB27_2: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB27_4
; GCN-NEXT:  ; %bb.3: ; %cmp.true
; GCN-NEXT:    v_cvt_f32_f16_e32 v0, v45
; GCN-NEXT:    v_cvt_f32_f16_e32 v1, v44
; GCN-NEXT:    v_cvt_f32_f16_e32 v2, v43
; GCN-NEXT:    v_cvt_f32_f16_e32 v3, v42
; GCN-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; GCN-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; GCN-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; GCN-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; GCN-NEXT:    v_cvt_f16_f32_e32 v0, v0
; GCN-NEXT:    v_cvt_f16_f32_e32 v1, v1
; GCN-NEXT:    v_cvt_f16_f32_e32 v2, v2
; GCN-NEXT:    v_cvt_f16_f32_e32 v3, v3
; GCN-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; GCN-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; GCN-NEXT:    v_or_b32_e32 v0, v1, v0
; GCN-NEXT:    v_or_b32_e32 v1, v3, v2
; GCN-NEXT:    v_cvt_f32_f16_e32 v2, v41
; GCN-NEXT:    v_cvt_f32_f16_e32 v3, v52
; GCN-NEXT:    v_cvt_f32_f16_e32 v4, v40
; GCN-NEXT:    v_cvt_f32_f16_e32 v5, v50
; GCN-NEXT:    v_cvt_f32_f16_e32 v6, v55
; GCN-NEXT:    v_cvt_f32_f16_e32 v7, v48
; GCN-NEXT:    v_cvt_f32_f16_e32 v8, v54
; GCN-NEXT:    v_cvt_f32_f16_e32 v9, v38
; GCN-NEXT:    v_cvt_f32_f16_e32 v10, v53
; GCN-NEXT:    v_cvt_f32_f16_e32 v11, v36
; GCN-NEXT:    v_cvt_f32_f16_e32 v12, v51
; GCN-NEXT:    v_cvt_f32_f16_e32 v13, v34
; GCN-NEXT:    v_cvt_f32_f16_e32 v14, v49
; GCN-NEXT:    v_cvt_f32_f16_e32 v15, v33
; GCN-NEXT:    v_cvt_f32_f16_e32 v24, v39
; GCN-NEXT:    v_cvt_f32_f16_e32 v26, v32
; GCN-NEXT:    v_cvt_f32_f16_e32 v27, v37
; GCN-NEXT:    v_cvt_f32_f16_e32 v28, v31
; GCN-NEXT:    v_cvt_f32_f16_e32 v29, v35
; GCN-NEXT:    v_cvt_f32_f16_e32 v21, v21
; GCN-NEXT:    v_cvt_f32_f16_e32 v25, v25
; GCN-NEXT:    v_cvt_f32_f16_e32 v19, v19
; GCN-NEXT:    v_cvt_f32_f16_e32 v23, v23
; GCN-NEXT:    v_cvt_f32_f16_e32 v18, v18
; GCN-NEXT:    v_cvt_f32_f16_e32 v22, v22
; GCN-NEXT:    v_cvt_f32_f16_e32 v17, v17
; GCN-NEXT:    v_cvt_f32_f16_e32 v20, v20
; GCN-NEXT:    v_cvt_f32_f16_e32 v16, v16
; GCN-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; GCN-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; GCN-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; GCN-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; GCN-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; GCN-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; GCN-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; GCN-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; GCN-NEXT:    v_add_f32_e32 v10, 0x38000000, v10
; GCN-NEXT:    v_add_f32_e32 v11, 0x38000000, v11
; GCN-NEXT:    v_add_f32_e32 v12, 0x38000000, v12
; GCN-NEXT:    v_add_f32_e32 v13, 0x38000000, v13
; GCN-NEXT:    v_add_f32_e32 v14, 0x38000000, v14
; GCN-NEXT:    v_add_f32_e32 v15, 0x38000000, v15
; GCN-NEXT:    v_add_f32_e32 v24, 0x38000000, v24
; GCN-NEXT:    v_add_f32_e32 v26, 0x38000000, v26
; GCN-NEXT:    v_add_f32_e32 v27, 0x38000000, v27
; GCN-NEXT:    v_add_f32_e32 v28, 0x38000000, v28
; GCN-NEXT:    v_add_f32_e32 v29, 0x38000000, v29
; GCN-NEXT:    v_add_f32_e32 v21, 0x38000000, v21
; GCN-NEXT:    v_add_f32_e32 v25, 0x38000000, v25
; GCN-NEXT:    v_add_f32_e32 v19, 0x38000000, v19
; GCN-NEXT:    v_add_f32_e32 v23, 0x38000000, v23
; GCN-NEXT:    v_add_f32_e32 v18, 0x38000000, v18
; GCN-NEXT:    v_add_f32_e32 v22, 0x38000000, v22
; GCN-NEXT:    v_add_f32_e32 v17, 0x38000000, v17
; GCN-NEXT:    v_add_f32_e32 v20, 0x38000000, v20
; GCN-NEXT:    v_add_f32_e32 v16, 0x38000000, v16
; GCN-NEXT:    v_cvt_f16_f32_e32 v2, v2
; GCN-NEXT:    v_cvt_f16_f32_e32 v3, v3
; GCN-NEXT:    v_cvt_f16_f32_e32 v4, v4
; GCN-NEXT:    v_cvt_f16_f32_e32 v5, v5
; GCN-NEXT:    v_cvt_f16_f32_e32 v6, v6
; GCN-NEXT:    v_cvt_f16_f32_e32 v7, v7
; GCN-NEXT:    v_cvt_f16_f32_e32 v8, v8
; GCN-NEXT:    v_cvt_f16_f32_e32 v9, v9
; GCN-NEXT:    v_cvt_f16_f32_e32 v10, v10
; GCN-NEXT:    v_cvt_f16_f32_e32 v11, v11
; GCN-NEXT:    v_cvt_f16_f32_e32 v12, v12
; GCN-NEXT:    v_cvt_f16_f32_e32 v13, v13
; GCN-NEXT:    v_cvt_f16_f32_e32 v14, v14
; GCN-NEXT:    v_cvt_f16_f32_e32 v15, v15
; GCN-NEXT:    v_cvt_f16_f32_e32 v24, v24
; GCN-NEXT:    v_cvt_f16_f32_e32 v26, v26
; GCN-NEXT:    v_cvt_f16_f32_e32 v27, v27
; GCN-NEXT:    v_cvt_f16_f32_e32 v28, v28
; GCN-NEXT:    v_cvt_f16_f32_e32 v29, v29
; GCN-NEXT:    v_cvt_f16_f32_e32 v21, v21
; GCN-NEXT:    v_cvt_f16_f32_e32 v25, v25
; GCN-NEXT:    v_cvt_f16_f32_e32 v19, v19
; GCN-NEXT:    v_cvt_f16_f32_e32 v23, v23
; GCN-NEXT:    v_cvt_f16_f32_e32 v18, v18
; GCN-NEXT:    v_cvt_f16_f32_e32 v22, v22
; GCN-NEXT:    v_cvt_f16_f32_e32 v17, v17
; GCN-NEXT:    v_cvt_f16_f32_e32 v20, v20
; GCN-NEXT:    v_cvt_f16_f32_e32 v16, v16
; GCN-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; GCN-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GCN-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GCN-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; GCN-NEXT:    v_lshlrev_b32_e32 v10, 16, v10
; GCN-NEXT:    v_lshlrev_b32_e32 v12, 16, v12
; GCN-NEXT:    v_lshlrev_b32_e32 v14, 16, v14
; GCN-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; GCN-NEXT:    v_lshlrev_b32_e32 v27, 16, v27
; GCN-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; GCN-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; GCN-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; GCN-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; GCN-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; GCN-NEXT:    v_or_b32_e32 v2, v3, v2
; GCN-NEXT:    v_or_b32_e32 v3, v5, v4
; GCN-NEXT:    v_or_b32_e32 v4, v7, v6
; GCN-NEXT:    v_or_b32_e32 v5, v9, v8
; GCN-NEXT:    v_or_b32_e32 v6, v11, v10
; GCN-NEXT:    v_or_b32_e32 v7, v13, v12
; GCN-NEXT:    v_or_b32_e32 v8, v15, v14
; GCN-NEXT:    v_or_b32_e32 v9, v26, v24
; GCN-NEXT:    v_or_b32_e32 v10, v28, v27
; GCN-NEXT:    v_or_b32_e32 v11, v21, v29
; GCN-NEXT:    v_or_b32_e32 v12, v19, v25
; GCN-NEXT:    v_or_b32_e32 v13, v18, v23
; GCN-NEXT:    v_or_b32_e32 v14, v17, v22
; GCN-NEXT:    v_or_b32_e32 v15, v16, v20
; GCN-NEXT:  .LBB27_4: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v32f16_to_v8i64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB27_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v16, 0x200
; VI-NEXT:    v_add_f16_sdwa v17, v15, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v15, 0x200, v15
; VI-NEXT:    v_or_b32_e32 v15, v15, v17
; VI-NEXT:    v_add_f16_sdwa v17, v14, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v14, 0x200, v14
; VI-NEXT:    v_or_b32_e32 v14, v14, v17
; VI-NEXT:    v_add_f16_sdwa v17, v13, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v13, 0x200, v13
; VI-NEXT:    v_or_b32_e32 v13, v13, v17
; VI-NEXT:    v_add_f16_sdwa v17, v12, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v12, 0x200, v12
; VI-NEXT:    v_or_b32_e32 v12, v12, v17
; VI-NEXT:    v_add_f16_sdwa v17, v11, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v11, 0x200, v11
; VI-NEXT:    v_or_b32_e32 v11, v11, v17
; VI-NEXT:    v_add_f16_sdwa v17, v10, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v10, 0x200, v10
; VI-NEXT:    v_or_b32_e32 v10, v10, v17
; VI-NEXT:    v_add_f16_sdwa v17, v9, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v9, 0x200, v9
; VI-NEXT:    v_or_b32_e32 v9, v9, v17
; VI-NEXT:    v_add_f16_sdwa v17, v8, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v8, 0x200, v8
; VI-NEXT:    v_or_b32_e32 v8, v8, v17
; VI-NEXT:    v_add_f16_sdwa v17, v7, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v7, 0x200, v7
; VI-NEXT:    v_or_b32_e32 v7, v7, v17
; VI-NEXT:    v_add_f16_sdwa v17, v6, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v6, 0x200, v6
; VI-NEXT:    v_or_b32_e32 v6, v6, v17
; VI-NEXT:    v_add_f16_sdwa v17, v5, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v5, 0x200, v5
; VI-NEXT:    v_or_b32_e32 v5, v5, v17
; VI-NEXT:    v_add_f16_sdwa v17, v4, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v4, 0x200, v4
; VI-NEXT:    v_or_b32_e32 v4, v4, v17
; VI-NEXT:    v_add_f16_sdwa v17, v3, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v3, 0x200, v3
; VI-NEXT:    v_or_b32_e32 v3, v3, v17
; VI-NEXT:    v_add_f16_sdwa v17, v2, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, 0x200, v2
; VI-NEXT:    v_or_b32_e32 v2, v2, v17
; VI-NEXT:    v_add_f16_sdwa v17, v1, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v1, 0x200, v1
; VI-NEXT:    v_add_f16_sdwa v16, v0, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v0, 0x200, v0
; VI-NEXT:    v_or_b32_e32 v1, v1, v17
; VI-NEXT:    v_or_b32_e32 v0, v0, v16
; VI-NEXT:  .LBB27_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v32f16_to_v8i64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB27_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    s_movk_i32 s6, 0x200
; GFX9-NEXT:    v_pk_add_f16 v15, v15, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v14, v14, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v13, v13, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v12, v12, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v11, v11, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v10, v10, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v9, v9, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v8, v8, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v7, v7, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, v6, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v5, v5, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v4, v4, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v3, v3, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v2, v2, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v1, v1, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v0, v0, s6 op_sel_hi:[1,0]
; GFX9-NEXT:  .LBB27_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v32f16_to_v8i64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB27_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_pk_add_f16 v15, 0x200, v15 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v14, 0x200, v14 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v13, 0x200, v13 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v12, 0x200, v12 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v11, 0x200, v11 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v10, 0x200, v10 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v9, 0x200, v9 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v8, 0x200, v8 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v7, 0x200, v7 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v6, 0x200, v6 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v5, 0x200, v5 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v4, 0x200, v4 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v3, 0x200, v3 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v2, 0x200, v2 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v1, 0x200, v1 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v0, 0x200, v0 op_sel_hi:[0,1]
; GFX11-NEXT:  .LBB27_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <32 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <32 x half> %a1 to <8 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <32 x half> %a to <8 x i64>
  br label %end

end:
  %phi = phi <8 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x i64> %phi
}

define <32 x bfloat> @v_bitcast_v8i64_to_v32bf16(<8 x i64> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v8i64_to_v32bf16:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_mov_b32_e32 v55, v15
; GCN-NEXT:    v_mov_b32_e32 v54, v14
; GCN-NEXT:    v_mov_b32_e32 v53, v13
; GCN-NEXT:    v_mov_b32_e32 v52, v12
; GCN-NEXT:    v_mov_b32_e32 v51, v11
; GCN-NEXT:    v_mov_b32_e32 v50, v10
; GCN-NEXT:    v_mov_b32_e32 v49, v9
; GCN-NEXT:    v_mov_b32_e32 v48, v8
; GCN-NEXT:    v_mov_b32_e32 v39, v7
; GCN-NEXT:    v_mov_b32_e32 v38, v6
; GCN-NEXT:    v_mov_b32_e32 v37, v5
; GCN-NEXT:    v_mov_b32_e32 v36, v4
; GCN-NEXT:    v_mov_b32_e32 v35, v3
; GCN-NEXT:    v_mov_b32_e32 v34, v2
; GCN-NEXT:    v_mov_b32_e32 v33, v1
; GCN-NEXT:    v_mov_b32_e32 v32, v0
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GCN-NEXT:    ; implicit-def: $vgpr0
; GCN-NEXT:    ; implicit-def: $vgpr1
; GCN-NEXT:    ; implicit-def: $vgpr2
; GCN-NEXT:    ; implicit-def: $vgpr3
; GCN-NEXT:    ; implicit-def: $vgpr4
; GCN-NEXT:    ; implicit-def: $vgpr5
; GCN-NEXT:    ; implicit-def: $vgpr6
; GCN-NEXT:    ; implicit-def: $vgpr7
; GCN-NEXT:    ; implicit-def: $vgpr8
; GCN-NEXT:    ; implicit-def: $vgpr9
; GCN-NEXT:    ; implicit-def: $vgpr10
; GCN-NEXT:    ; implicit-def: $vgpr11
; GCN-NEXT:    ; implicit-def: $vgpr12
; GCN-NEXT:    ; implicit-def: $vgpr13
; GCN-NEXT:    ; implicit-def: $vgpr14
; GCN-NEXT:    ; implicit-def: $vgpr15
; GCN-NEXT:    ; implicit-def: $vgpr16
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr18
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr20
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr22
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr24
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr26
; GCN-NEXT:    ; implicit-def: $vgpr27
; GCN-NEXT:    ; implicit-def: $vgpr28
; GCN-NEXT:    ; implicit-def: $vgpr29
; GCN-NEXT:    ; implicit-def: $vgpr30
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execnz .LBB28_3
; GCN-NEXT:  ; %bb.1: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execnz .LBB28_4
; GCN-NEXT:  .LBB28_2: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
; GCN-NEXT:  .LBB28_3: ; %cmp.false
; GCN-NEXT:    v_and_b32_e32 v31, 0xffff0000, v55
; GCN-NEXT:    v_lshlrev_b32_e32 v30, 16, v55
; GCN-NEXT:    v_and_b32_e32 v29, 0xffff0000, v54
; GCN-NEXT:    v_lshlrev_b32_e32 v28, 16, v54
; GCN-NEXT:    v_and_b32_e32 v27, 0xffff0000, v53
; GCN-NEXT:    v_lshlrev_b32_e32 v26, 16, v53
; GCN-NEXT:    v_and_b32_e32 v25, 0xffff0000, v52
; GCN-NEXT:    v_lshlrev_b32_e32 v24, 16, v52
; GCN-NEXT:    v_and_b32_e32 v23, 0xffff0000, v51
; GCN-NEXT:    v_lshlrev_b32_e32 v22, 16, v51
; GCN-NEXT:    v_and_b32_e32 v21, 0xffff0000, v50
; GCN-NEXT:    v_lshlrev_b32_e32 v20, 16, v50
; GCN-NEXT:    v_and_b32_e32 v19, 0xffff0000, v49
; GCN-NEXT:    v_lshlrev_b32_e32 v18, 16, v49
; GCN-NEXT:    v_and_b32_e32 v17, 0xffff0000, v48
; GCN-NEXT:    v_lshlrev_b32_e32 v16, 16, v48
; GCN-NEXT:    v_and_b32_e32 v15, 0xffff0000, v39
; GCN-NEXT:    v_lshlrev_b32_e32 v14, 16, v39
; GCN-NEXT:    v_and_b32_e32 v13, 0xffff0000, v38
; GCN-NEXT:    v_lshlrev_b32_e32 v12, 16, v38
; GCN-NEXT:    v_and_b32_e32 v11, 0xffff0000, v37
; GCN-NEXT:    v_lshlrev_b32_e32 v10, 16, v37
; GCN-NEXT:    v_and_b32_e32 v9, 0xffff0000, v36
; GCN-NEXT:    v_lshlrev_b32_e32 v8, 16, v36
; GCN-NEXT:    v_and_b32_e32 v7, 0xffff0000, v35
; GCN-NEXT:    v_lshlrev_b32_e32 v6, 16, v35
; GCN-NEXT:    v_and_b32_e32 v5, 0xffff0000, v34
; GCN-NEXT:    v_lshlrev_b32_e32 v4, 16, v34
; GCN-NEXT:    v_and_b32_e32 v3, 0xffff0000, v33
; GCN-NEXT:    v_lshlrev_b32_e32 v2, 16, v33
; GCN-NEXT:    v_and_b32_e32 v1, 0xffff0000, v32
; GCN-NEXT:    v_lshlrev_b32_e32 v0, 16, v32
; GCN-NEXT:    ; implicit-def: $vgpr32
; GCN-NEXT:    ; implicit-def: $vgpr33
; GCN-NEXT:    ; implicit-def: $vgpr34
; GCN-NEXT:    ; implicit-def: $vgpr35
; GCN-NEXT:    ; implicit-def: $vgpr36
; GCN-NEXT:    ; implicit-def: $vgpr37
; GCN-NEXT:    ; implicit-def: $vgpr38
; GCN-NEXT:    ; implicit-def: $vgpr39
; GCN-NEXT:    ; implicit-def: $vgpr48
; GCN-NEXT:    ; implicit-def: $vgpr49
; GCN-NEXT:    ; implicit-def: $vgpr50
; GCN-NEXT:    ; implicit-def: $vgpr51
; GCN-NEXT:    ; implicit-def: $vgpr52
; GCN-NEXT:    ; implicit-def: $vgpr53
; GCN-NEXT:    ; implicit-def: $vgpr54
; GCN-NEXT:    ; implicit-def: $vgpr55
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB28_2
; GCN-NEXT:  .LBB28_4: ; %cmp.true
; GCN-NEXT:    v_add_i32_e32 v0, vcc, 3, v32
; GCN-NEXT:    v_addc_u32_e32 v1, vcc, 0, v33, vcc
; GCN-NEXT:    v_add_i32_e32 v2, vcc, 3, v34
; GCN-NEXT:    v_addc_u32_e32 v3, vcc, 0, v35, vcc
; GCN-NEXT:    v_add_i32_e32 v4, vcc, 3, v36
; GCN-NEXT:    v_addc_u32_e32 v5, vcc, 0, v37, vcc
; GCN-NEXT:    v_add_i32_e32 v6, vcc, 3, v38
; GCN-NEXT:    v_addc_u32_e32 v7, vcc, 0, v39, vcc
; GCN-NEXT:    v_add_i32_e32 v8, vcc, 3, v48
; GCN-NEXT:    v_addc_u32_e32 v9, vcc, 0, v49, vcc
; GCN-NEXT:    v_add_i32_e32 v10, vcc, 3, v50
; GCN-NEXT:    v_addc_u32_e32 v11, vcc, 0, v51, vcc
; GCN-NEXT:    v_add_i32_e32 v12, vcc, 3, v52
; GCN-NEXT:    v_addc_u32_e32 v13, vcc, 0, v53, vcc
; GCN-NEXT:    v_add_i32_e32 v14, vcc, 3, v54
; GCN-NEXT:    v_addc_u32_e32 v15, vcc, 0, v55, vcc
; GCN-NEXT:    v_and_b32_e32 v31, 0xffff0000, v15
; GCN-NEXT:    v_lshlrev_b32_e32 v30, 16, v15
; GCN-NEXT:    v_and_b32_e32 v29, 0xffff0000, v14
; GCN-NEXT:    v_lshlrev_b32_e32 v28, 16, v14
; GCN-NEXT:    v_and_b32_e32 v27, 0xffff0000, v13
; GCN-NEXT:    v_lshlrev_b32_e32 v26, 16, v13
; GCN-NEXT:    v_and_b32_e32 v25, 0xffff0000, v12
; GCN-NEXT:    v_lshlrev_b32_e32 v24, 16, v12
; GCN-NEXT:    v_and_b32_e32 v23, 0xffff0000, v11
; GCN-NEXT:    v_lshlrev_b32_e32 v22, 16, v11
; GCN-NEXT:    v_and_b32_e32 v21, 0xffff0000, v10
; GCN-NEXT:    v_lshlrev_b32_e32 v20, 16, v10
; GCN-NEXT:    v_and_b32_e32 v19, 0xffff0000, v9
; GCN-NEXT:    v_lshlrev_b32_e32 v18, 16, v9
; GCN-NEXT:    v_and_b32_e32 v17, 0xffff0000, v8
; GCN-NEXT:    v_lshlrev_b32_e32 v16, 16, v8
; GCN-NEXT:    v_and_b32_e32 v15, 0xffff0000, v7
; GCN-NEXT:    v_lshlrev_b32_e32 v14, 16, v7
; GCN-NEXT:    v_and_b32_e32 v13, 0xffff0000, v6
; GCN-NEXT:    v_lshlrev_b32_e32 v12, 16, v6
; GCN-NEXT:    v_and_b32_e32 v11, 0xffff0000, v5
; GCN-NEXT:    v_lshlrev_b32_e32 v10, 16, v5
; GCN-NEXT:    v_and_b32_e32 v9, 0xffff0000, v4
; GCN-NEXT:    v_lshlrev_b32_e32 v8, 16, v4
; GCN-NEXT:    v_and_b32_e32 v7, 0xffff0000, v3
; GCN-NEXT:    v_lshlrev_b32_e32 v6, 16, v3
; GCN-NEXT:    v_and_b32_e32 v5, 0xffff0000, v2
; GCN-NEXT:    v_lshlrev_b32_e32 v4, 16, v2
; GCN-NEXT:    v_and_b32_e32 v3, 0xffff0000, v1
; GCN-NEXT:    v_lshlrev_b32_e32 v2, 16, v1
; GCN-NEXT:    v_and_b32_e32 v1, 0xffff0000, v0
; GCN-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v8i64_to_v32bf16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB28_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v14, vcc, 3, v14
; VI-NEXT:    v_addc_u32_e32 v15, vcc, 0, v15, vcc
; VI-NEXT:    v_add_u32_e32 v12, vcc, 3, v12
; VI-NEXT:    v_addc_u32_e32 v13, vcc, 0, v13, vcc
; VI-NEXT:    v_add_u32_e32 v10, vcc, 3, v10
; VI-NEXT:    v_addc_u32_e32 v11, vcc, 0, v11, vcc
; VI-NEXT:    v_add_u32_e32 v8, vcc, 3, v8
; VI-NEXT:    v_addc_u32_e32 v9, vcc, 0, v9, vcc
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-NEXT:  .LBB28_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v8i64_to_v32bf16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB28_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_co_u32_e32 v14, vcc, 3, v14
; GFX9-NEXT:    v_addc_co_u32_e32 v15, vcc, 0, v15, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v12, vcc, 3, v12
; GFX9-NEXT:    v_addc_co_u32_e32 v13, vcc, 0, v13, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v10, vcc, 3, v10
; GFX9-NEXT:    v_addc_co_u32_e32 v11, vcc, 0, v11, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v8, vcc, 3, v8
; GFX9-NEXT:    v_addc_co_u32_e32 v9, vcc, 0, v9, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v6, vcc, 3, v6
; GFX9-NEXT:    v_addc_co_u32_e32 v7, vcc, 0, v7, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v4, vcc, 3, v4
; GFX9-NEXT:    v_addc_co_u32_e32 v5, vcc, 0, v5, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v2, vcc, 3, v2
; GFX9-NEXT:    v_addc_co_u32_e32 v3, vcc, 0, v3, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v0, vcc, 3, v0
; GFX9-NEXT:    v_addc_co_u32_e32 v1, vcc, 0, v1, vcc
; GFX9-NEXT:  .LBB28_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v8i64_to_v32bf16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB28_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_co_u32 v14, vcc_lo, v14, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v15, vcc_lo, 0, v15, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v12, vcc_lo, v12, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v13, vcc_lo, 0, v13, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v10, vcc_lo, v10, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v11, vcc_lo, 0, v11, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v8, vcc_lo, v8, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v9, vcc_lo, 0, v9, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v6, vcc_lo, v6, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v7, vcc_lo, 0, v7, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v4, vcc_lo, v4, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v5, vcc_lo, 0, v5, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v2, vcc_lo, v2, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v3, vcc_lo, 0, v3, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v0, vcc_lo, v0, 3
; GFX11-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, 0, v1, vcc_lo
; GFX11-NEXT:  .LBB28_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <8 x i64> %a, splat (i64 3)
  %a2 = bitcast <8 x i64> %a1 to <32 x bfloat>
  br label %end

cmp.false:
  %a3 = bitcast <8 x i64> %a to <32 x bfloat>
  br label %end

end:
  %phi = phi <32 x bfloat> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x bfloat> %phi
}

define <8 x i64> @v_bitcast_v32bf16_to_v8i64(<32 x bfloat> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v32bf16_to_v8i64:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GCN-NEXT:    s_waitcnt expcnt(1)
; GCN-NEXT:    buffer_load_dword v46, off, s[0:3], s32
; GCN-NEXT:    s_waitcnt expcnt(0)
; GCN-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:4
; GCN-NEXT:    v_mul_f32_e32 v44, 1.0, v1
; GCN-NEXT:    v_mul_f32_e32 v45, 1.0, v0
; GCN-NEXT:    v_mul_f32_e32 v42, 1.0, v3
; GCN-NEXT:    v_mul_f32_e32 v43, 1.0, v2
; GCN-NEXT:    v_mul_f32_e32 v41, 1.0, v5
; GCN-NEXT:    v_mul_f32_e32 v51, 1.0, v4
; GCN-NEXT:    v_mul_f32_e32 v40, 1.0, v7
; GCN-NEXT:    v_mul_f32_e32 v49, 1.0, v6
; GCN-NEXT:    v_mul_f32_e32 v55, 1.0, v9
; GCN-NEXT:    v_mul_f32_e32 v39, 1.0, v8
; GCN-NEXT:    v_mul_f32_e32 v54, 1.0, v11
; GCN-NEXT:    v_mul_f32_e32 v37, 1.0, v10
; GCN-NEXT:    v_mul_f32_e32 v53, 1.0, v13
; GCN-NEXT:    v_mul_f32_e32 v36, 1.0, v12
; GCN-NEXT:    v_mul_f32_e32 v52, 1.0, v15
; GCN-NEXT:    v_mul_f32_e32 v34, 1.0, v14
; GCN-NEXT:    v_mul_f32_e32 v50, 1.0, v17
; GCN-NEXT:    v_mul_f32_e32 v33, 1.0, v16
; GCN-NEXT:    v_mul_f32_e32 v48, 1.0, v19
; GCN-NEXT:    v_mul_f32_e32 v32, 1.0, v18
; GCN-NEXT:    v_mul_f32_e32 v38, 1.0, v21
; GCN-NEXT:    v_mul_f32_e32 v31, 1.0, v20
; GCN-NEXT:    v_mul_f32_e32 v35, 1.0, v23
; GCN-NEXT:    v_mul_f32_e32 v21, 1.0, v22
; GCN-NEXT:    v_mul_f32_e32 v25, 1.0, v25
; GCN-NEXT:    v_mul_f32_e32 v19, 1.0, v24
; GCN-NEXT:    v_mul_f32_e32 v23, 1.0, v27
; GCN-NEXT:    v_mul_f32_e32 v18, 1.0, v26
; GCN-NEXT:    v_mul_f32_e32 v22, 1.0, v29
; GCN-NEXT:    v_mul_f32_e32 v17, 1.0, v28
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v47
; GCN-NEXT:    v_mul_f32_e32 v20, 1.0, v46
; GCN-NEXT:    v_mul_f32_e32 v16, 1.0, v30
; GCN-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB29_2
; GCN-NEXT:  ; %bb.1: ; %cmp.false
; GCN-NEXT:    v_lshrrev_b32_e32 v0, 16, v44
; GCN-NEXT:    v_lshrrev_b32_e32 v1, 16, v42
; GCN-NEXT:    v_alignbit_b32 v0, v0, v45, 16
; GCN-NEXT:    v_alignbit_b32 v1, v1, v43, 16
; GCN-NEXT:    v_lshrrev_b32_e32 v2, 16, v41
; GCN-NEXT:    v_lshrrev_b32_e32 v3, 16, v40
; GCN-NEXT:    v_lshrrev_b32_e32 v4, 16, v55
; GCN-NEXT:    v_lshrrev_b32_e32 v5, 16, v54
; GCN-NEXT:    v_lshrrev_b32_e32 v6, 16, v53
; GCN-NEXT:    v_lshrrev_b32_e32 v7, 16, v52
; GCN-NEXT:    v_lshrrev_b32_e32 v8, 16, v50
; GCN-NEXT:    v_lshrrev_b32_e32 v9, 16, v48
; GCN-NEXT:    v_lshrrev_b32_e32 v10, 16, v38
; GCN-NEXT:    v_lshrrev_b32_e32 v11, 16, v35
; GCN-NEXT:    v_lshrrev_b32_e32 v12, 16, v25
; GCN-NEXT:    v_lshrrev_b32_e32 v13, 16, v23
; GCN-NEXT:    v_lshrrev_b32_e32 v14, 16, v22
; GCN-NEXT:    v_lshrrev_b32_e32 v15, 16, v20
; GCN-NEXT:    v_alignbit_b32 v2, v2, v51, 16
; GCN-NEXT:    v_alignbit_b32 v3, v3, v49, 16
; GCN-NEXT:    v_alignbit_b32 v4, v4, v39, 16
; GCN-NEXT:    v_alignbit_b32 v5, v5, v37, 16
; GCN-NEXT:    v_alignbit_b32 v6, v6, v36, 16
; GCN-NEXT:    v_alignbit_b32 v7, v7, v34, 16
; GCN-NEXT:    v_alignbit_b32 v8, v8, v33, 16
; GCN-NEXT:    v_alignbit_b32 v9, v9, v32, 16
; GCN-NEXT:    v_alignbit_b32 v10, v10, v31, 16
; GCN-NEXT:    v_alignbit_b32 v11, v11, v21, 16
; GCN-NEXT:    v_alignbit_b32 v12, v12, v19, 16
; GCN-NEXT:    v_alignbit_b32 v13, v13, v18, 16
; GCN-NEXT:    v_alignbit_b32 v14, v14, v17, 16
; GCN-NEXT:    v_alignbit_b32 v15, v15, v16, 16
; GCN-NEXT:    ; implicit-def: $vgpr44
; GCN-NEXT:    ; implicit-def: $vgpr45
; GCN-NEXT:    ; implicit-def: $vgpr42
; GCN-NEXT:    ; implicit-def: $vgpr43
; GCN-NEXT:    ; implicit-def: $vgpr41
; GCN-NEXT:    ; implicit-def: $vgpr51
; GCN-NEXT:    ; implicit-def: $vgpr40
; GCN-NEXT:    ; implicit-def: $vgpr49
; GCN-NEXT:    ; implicit-def: $vgpr55
; GCN-NEXT:    ; implicit-def: $vgpr39
; GCN-NEXT:    ; implicit-def: $vgpr54
; GCN-NEXT:    ; implicit-def: $vgpr37
; GCN-NEXT:    ; implicit-def: $vgpr53
; GCN-NEXT:    ; implicit-def: $vgpr36
; GCN-NEXT:    ; implicit-def: $vgpr52
; GCN-NEXT:    ; implicit-def: $vgpr34
; GCN-NEXT:    ; implicit-def: $vgpr50
; GCN-NEXT:    ; implicit-def: $vgpr33
; GCN-NEXT:    ; implicit-def: $vgpr48
; GCN-NEXT:    ; implicit-def: $vgpr32
; GCN-NEXT:    ; implicit-def: $vgpr38
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    ; implicit-def: $vgpr35
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr18
; GCN-NEXT:    ; implicit-def: $vgpr22
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr20
; GCN-NEXT:    ; implicit-def: $vgpr16
; GCN-NEXT:  .LBB29_2: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB29_4
; GCN-NEXT:  ; %bb.3: ; %cmp.true
; GCN-NEXT:    v_and_b32_e32 v0, 0xffff0000, v45
; GCN-NEXT:    v_and_b32_e32 v1, 0xffff0000, v44
; GCN-NEXT:    v_and_b32_e32 v2, 0xffff0000, v43
; GCN-NEXT:    v_and_b32_e32 v3, 0xffff0000, v42
; GCN-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; GCN-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GCN-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GCN-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GCN-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GCN-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; GCN-NEXT:    v_alignbit_b32 v0, v1, v0, 16
; GCN-NEXT:    v_alignbit_b32 v1, v3, v2, 16
; GCN-NEXT:    v_and_b32_e32 v2, 0xffff0000, v51
; GCN-NEXT:    v_and_b32_e32 v3, 0xffff0000, v41
; GCN-NEXT:    v_and_b32_e32 v4, 0xffff0000, v49
; GCN-NEXT:    v_and_b32_e32 v5, 0xffff0000, v40
; GCN-NEXT:    v_and_b32_e32 v6, 0xffff0000, v39
; GCN-NEXT:    v_and_b32_e32 v7, 0xffff0000, v55
; GCN-NEXT:    v_and_b32_e32 v8, 0xffff0000, v37
; GCN-NEXT:    v_and_b32_e32 v9, 0xffff0000, v54
; GCN-NEXT:    v_and_b32_e32 v10, 0xffff0000, v36
; GCN-NEXT:    v_and_b32_e32 v11, 0xffff0000, v53
; GCN-NEXT:    v_and_b32_e32 v12, 0xffff0000, v34
; GCN-NEXT:    v_and_b32_e32 v13, 0xffff0000, v52
; GCN-NEXT:    v_and_b32_e32 v14, 0xffff0000, v33
; GCN-NEXT:    v_and_b32_e32 v15, 0xffff0000, v50
; GCN-NEXT:    v_and_b32_e32 v24, 0xffff0000, v32
; GCN-NEXT:    v_and_b32_e32 v26, 0xffff0000, v48
; GCN-NEXT:    v_and_b32_e32 v27, 0xffff0000, v31
; GCN-NEXT:    v_and_b32_e32 v28, 0xffff0000, v38
; GCN-NEXT:    v_and_b32_e32 v21, 0xffff0000, v21
; GCN-NEXT:    v_and_b32_e32 v29, 0xffff0000, v35
; GCN-NEXT:    v_and_b32_e32 v19, 0xffff0000, v19
; GCN-NEXT:    v_and_b32_e32 v25, 0xffff0000, v25
; GCN-NEXT:    v_and_b32_e32 v18, 0xffff0000, v18
; GCN-NEXT:    v_and_b32_e32 v23, 0xffff0000, v23
; GCN-NEXT:    v_and_b32_e32 v17, 0xffff0000, v17
; GCN-NEXT:    v_and_b32_e32 v22, 0xffff0000, v22
; GCN-NEXT:    v_and_b32_e32 v16, 0xffff0000, v16
; GCN-NEXT:    v_and_b32_e32 v20, 0xffff0000, v20
; GCN-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GCN-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GCN-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; GCN-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GCN-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GCN-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GCN-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GCN-NEXT:    v_add_f32_e32 v9, 0x40c00000, v9
; GCN-NEXT:    v_add_f32_e32 v10, 0x40c00000, v10
; GCN-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; GCN-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; GCN-NEXT:    v_add_f32_e32 v13, 0x40c00000, v13
; GCN-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; GCN-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; GCN-NEXT:    v_add_f32_e32 v24, 0x40c00000, v24
; GCN-NEXT:    v_add_f32_e32 v26, 0x40c00000, v26
; GCN-NEXT:    v_add_f32_e32 v27, 0x40c00000, v27
; GCN-NEXT:    v_add_f32_e32 v28, 0x40c00000, v28
; GCN-NEXT:    v_add_f32_e32 v21, 0x40c00000, v21
; GCN-NEXT:    v_add_f32_e32 v29, 0x40c00000, v29
; GCN-NEXT:    v_add_f32_e32 v19, 0x40c00000, v19
; GCN-NEXT:    v_add_f32_e32 v25, 0x40c00000, v25
; GCN-NEXT:    v_add_f32_e32 v18, 0x40c00000, v18
; GCN-NEXT:    v_add_f32_e32 v23, 0x40c00000, v23
; GCN-NEXT:    v_add_f32_e32 v17, 0x40c00000, v17
; GCN-NEXT:    v_add_f32_e32 v22, 0x40c00000, v22
; GCN-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GCN-NEXT:    v_add_f32_e32 v20, 0x40c00000, v20
; GCN-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; GCN-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; GCN-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; GCN-NEXT:    v_lshrrev_b32_e32 v9, 16, v9
; GCN-NEXT:    v_lshrrev_b32_e32 v11, 16, v11
; GCN-NEXT:    v_lshrrev_b32_e32 v13, 16, v13
; GCN-NEXT:    v_lshrrev_b32_e32 v15, 16, v15
; GCN-NEXT:    v_lshrrev_b32_e32 v26, 16, v26
; GCN-NEXT:    v_lshrrev_b32_e32 v28, 16, v28
; GCN-NEXT:    v_lshrrev_b32_e32 v29, 16, v29
; GCN-NEXT:    v_lshrrev_b32_e32 v25, 16, v25
; GCN-NEXT:    v_lshrrev_b32_e32 v23, 16, v23
; GCN-NEXT:    v_lshrrev_b32_e32 v22, 16, v22
; GCN-NEXT:    v_lshrrev_b32_e32 v20, 16, v20
; GCN-NEXT:    v_alignbit_b32 v2, v3, v2, 16
; GCN-NEXT:    v_alignbit_b32 v3, v5, v4, 16
; GCN-NEXT:    v_alignbit_b32 v4, v7, v6, 16
; GCN-NEXT:    v_alignbit_b32 v5, v9, v8, 16
; GCN-NEXT:    v_alignbit_b32 v6, v11, v10, 16
; GCN-NEXT:    v_alignbit_b32 v7, v13, v12, 16
; GCN-NEXT:    v_alignbit_b32 v8, v15, v14, 16
; GCN-NEXT:    v_alignbit_b32 v9, v26, v24, 16
; GCN-NEXT:    v_alignbit_b32 v10, v28, v27, 16
; GCN-NEXT:    v_alignbit_b32 v11, v29, v21, 16
; GCN-NEXT:    v_alignbit_b32 v12, v25, v19, 16
; GCN-NEXT:    v_alignbit_b32 v13, v23, v18, 16
; GCN-NEXT:    v_alignbit_b32 v14, v22, v17, 16
; GCN-NEXT:    v_alignbit_b32 v15, v20, v16, 16
; GCN-NEXT:  .LBB29_4: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v32bf16_to_v8i64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB29_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v15
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, 0x7fff, v17
; VI-NEXT:    v_and_b32_e32 v15, 0xffff0000, v15
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v15, 16, 1
; VI-NEXT:    s_movk_i32 s6, 0x7fff
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v15
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v15
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v15, v15
; VI-NEXT:    v_cndmask_b32_e32 v15, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v15, 16, v15
; VI-NEXT:    v_alignbit_b32 v15, v15, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v14
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v14, 0xffff0000, v14
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v14, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v14
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v14
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v14, v14
; VI-NEXT:    v_cndmask_b32_e32 v14, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v14, 16, v14
; VI-NEXT:    v_alignbit_b32 v14, v14, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v13
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v13, 0xffff0000, v13
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v13, 0x40c00000, v13
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v13, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v13
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v13
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v13, v13
; VI-NEXT:    v_cndmask_b32_e32 v13, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v13, 16, v13
; VI-NEXT:    v_alignbit_b32 v13, v13, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v12
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v12, 0xffff0000, v12
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v12, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v12
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v12
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v12, v12
; VI-NEXT:    v_cndmask_b32_e32 v12, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v12, 16, v12
; VI-NEXT:    v_alignbit_b32 v12, v12, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v11
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v11, 0xffff0000, v11
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v11, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v11
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v11
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v11, v11
; VI-NEXT:    v_cndmask_b32_e32 v11, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v11, 16, v11
; VI-NEXT:    v_alignbit_b32 v11, v11, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v10
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v10, 0xffff0000, v10
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v10, 0x40c00000, v10
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v10, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v10
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v10
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v10, v10
; VI-NEXT:    v_cndmask_b32_e32 v10, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v10, 16, v10
; VI-NEXT:    v_alignbit_b32 v10, v10, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v9
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v9, 0xffff0000, v9
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v9, 0x40c00000, v9
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v9, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v9
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v9
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v9, v9
; VI-NEXT:    v_cndmask_b32_e32 v9, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v9, 16, v9
; VI-NEXT:    v_alignbit_b32 v9, v9, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v8
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v8, 0xffff0000, v8
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v8
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_cndmask_b32_e32 v8, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v8, 16, v8
; VI-NEXT:    v_alignbit_b32 v8, v8, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v7
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v7, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v7
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v7
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; VI-NEXT:    v_cndmask_b32_e32 v7, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; VI-NEXT:    v_alignbit_b32 v7, v7, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v6
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v6, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v6
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v6
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; VI-NEXT:    v_cndmask_b32_e32 v6, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_alignbit_b32 v6, v6, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v5
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v5, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v5
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v5
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; VI-NEXT:    v_cndmask_b32_e32 v5, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_alignbit_b32 v5, v5, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v4
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v4, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v4
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v4
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; VI-NEXT:    v_cndmask_b32_e32 v4, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_alignbit_b32 v4, v4, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v3
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v3
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_alignbit_b32 v3, v3, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v2
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v2
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_alignbit_b32 v2, v2, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v1
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v1, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v1
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v1
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; VI-NEXT:    v_cndmask_b32_e32 v1, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_alignbit_b32 v1, v1, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v0
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v0, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v0
; VI-NEXT:    v_add_u32_e32 v17, vcc, 0x7fff, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v0
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; VI-NEXT:    v_cndmask_b32_e32 v0, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; VI-NEXT:    v_alignbit_b32 v0, v0, v16, 16
; VI-NEXT:  .LBB29_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v32bf16_to_v8i64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB29_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v15
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    s_movk_i32 s6, 0x7fff
; GFX9-NEXT:    v_and_b32_e32 v15, 0xffff0000, v15
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v15, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v15, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v15
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v15, v15
; GFX9-NEXT:    v_cndmask_b32_e32 v15, v17, v18, vcc
; GFX9-NEXT:    s_mov_b32 s7, 0x7060302
; GFX9-NEXT:    v_perm_b32 v15, v15, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v14
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v14, 0xffff0000, v14
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v14, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v14, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v14
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v14, v14
; GFX9-NEXT:    v_cndmask_b32_e32 v14, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v14, v14, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v13
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v13, 0xffff0000, v13
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v13, 0x40c00000, v13
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v13, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v13, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v13
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v13, v13
; GFX9-NEXT:    v_cndmask_b32_e32 v13, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v13, v13, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v12
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v12, 0xffff0000, v12
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v12, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v12, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v12
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v12, v12
; GFX9-NEXT:    v_cndmask_b32_e32 v12, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v12, v12, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v11
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v11, 0xffff0000, v11
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v11, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v11, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v11
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v11, v11
; GFX9-NEXT:    v_cndmask_b32_e32 v11, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v11, v11, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v10
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v10, 0xffff0000, v10
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v10, 0x40c00000, v10
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v10, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v10, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v10
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v10, v10
; GFX9-NEXT:    v_cndmask_b32_e32 v10, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v10, v10, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v9
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v9, 0xffff0000, v9
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v9, 0x40c00000, v9
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v9, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v9, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v9
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v9, v9
; GFX9-NEXT:    v_cndmask_b32_e32 v9, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v9, v9, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v8
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v8, 0xffff0000, v8
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v8, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v8, v8, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v7
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v7, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v7, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v7
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; GFX9-NEXT:    v_cndmask_b32_e32 v7, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v7, v7, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v6
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v6, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v6, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v6
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; GFX9-NEXT:    v_cndmask_b32_e32 v6, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v6, v6, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v5
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v5, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v5, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v5, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v5, v5, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v4
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v4, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v4, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v4
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; GFX9-NEXT:    v_cndmask_b32_e32 v4, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v4, v4, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v3
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v3, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v3, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v3
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; GFX9-NEXT:    v_cndmask_b32_e32 v3, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v3, v3, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v2, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v2, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v2, v2, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v1
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v1, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v1, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v1, v1, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v0
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v0, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v0, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v0
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v0, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v0, v0, v16, s7
; GFX9-NEXT:  .LBB29_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v32bf16_to_v8i64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB29_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_lshlrev_b32_e32 v17, 16, v14
; GFX11-NEXT:    v_lshlrev_b32_e32 v16, 16, v15
; GFX11-NEXT:    v_and_b32_e32 v14, 0xffff0000, v14
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_dual_add_f32 v17, 0x40c00000, v17 :: v_dual_add_f32 v16, 0x40c00000, v16
; GFX11-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_bfe_u32 v21, v17, 16, 1
; GFX11-NEXT:    v_bfe_u32 v18, v16, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v19, 0x400000, v16
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_bfe_u32 v23, v14, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v16, v16
; GFX11-NEXT:    v_add3_u32 v21, v21, v17, 0x7fff
; GFX11-NEXT:    v_add3_u32 v18, v18, v16, 0x7fff
; GFX11-NEXT:    v_cndmask_b32_e32 v16, v18, v19, vcc_lo
; GFX11-NEXT:    v_add3_u32 v19, v23, v14, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v15, 0xffff0000, v15
; GFX11-NEXT:    v_or_b32_e32 v18, 0x400000, v17
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; GFX11-NEXT:    v_bfe_u32 v20, v15, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v15
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v15, v15
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add3_u32 v20, v20, v15, 0x7fff
; GFX11-NEXT:    v_dual_cndmask_b32 v15, v20, v22 :: v_dual_lshlrev_b32 v20, 16, v13
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v17, v17
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_perm_b32 v15, v15, v16, 0x7060302
; GFX11-NEXT:    v_dual_cndmask_b32 v17, v21, v18 :: v_dual_add_f32 v18, 0x40c00000, v20
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_bfe_u32 v16, v18, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v18
; GFX11-NEXT:    v_add3_u32 v16, v16, v18, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v13, 0xffff0000, v13
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_add_f32_e32 v13, 0x40c00000, v13
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v14
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v14, v14
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v13
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_dual_cndmask_b32 v14, v19, v22 :: v_dual_lshlrev_b32 v19, 16, v12
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-NEXT:    v_perm_b32 v14, v14, v17, 0x7060302
; GFX11-NEXT:    v_bfe_u32 v17, v13, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_dual_add_f32 v19, 0x40c00000, v19 :: v_dual_cndmask_b32 v16, v16, v20
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v13, v13
; GFX11-NEXT:    v_add3_u32 v17, v17, v13, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_bfe_u32 v22, v19, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v19
; GFX11-NEXT:    v_cndmask_b32_e32 v13, v17, v21, vcc_lo
; GFX11-NEXT:    v_lshlrev_b32_e32 v21, 16, v11
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_add3_u32 v17, v22, v19, 0x7fff
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v19, v19
; GFX11-NEXT:    v_perm_b32 v13, v13, v16, 0x7060302
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_add_f32_e32 v19, 0x40c00000, v21
; GFX11-NEXT:    v_cndmask_b32_e32 v17, v17, v20, vcc_lo
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_bfe_u32 v16, v19, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v19
; GFX11-NEXT:    v_add3_u32 v16, v16, v19, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v11, 0xffff0000, v11
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v11
; GFX11-NEXT:    v_and_b32_e32 v12, 0xffff0000, v12
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; GFX11-NEXT:    v_bfe_u32 v18, v12, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v12
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v12, v12
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add3_u32 v18, v18, v12, 0x7fff
; GFX11-NEXT:    v_cndmask_b32_e32 v12, v18, v22, vcc_lo
; GFX11-NEXT:    v_lshlrev_b32_e32 v18, 16, v10
; GFX11-NEXT:    v_and_b32_e32 v10, 0xffff0000, v10
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_perm_b32 v12, v12, v17, 0x7060302
; GFX11-NEXT:    v_bfe_u32 v17, v11, 16, 1
; GFX11-NEXT:    v_add_f32_e32 v18, 0x40c00000, v18
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_add_f32_e32 v10, 0x40c00000, v10
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v19, v19
; GFX11-NEXT:    v_add3_u32 v17, v17, v11, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_bfe_u32 v22, v18, 16, 1
; GFX11-NEXT:    v_bfe_u32 v19, v10, 16, 1
; GFX11-NEXT:    v_cndmask_b32_e32 v16, v16, v20, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v11, v11
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v18
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_4) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_add3_u32 v19, v19, v10, 0x7fff
; GFX11-NEXT:    v_cndmask_b32_e32 v11, v17, v21, vcc_lo
; GFX11-NEXT:    v_add3_u32 v17, v22, v18, 0x7fff
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v10
; GFX11-NEXT:    v_perm_b32 v11, v11, v16, 0x7060302
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_cndmask_b32_e32 v17, v17, v20, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-NEXT:    v_dual_cndmask_b32 v10, v19, v22 :: v_dual_lshlrev_b32 v21, 16, v9
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_dual_add_f32 v18, 0x40c00000, v21 :: v_dual_lshlrev_b32 v19, 16, v8
; GFX11-NEXT:    v_and_b32_e32 v8, 0xffff0000, v8
; GFX11-NEXT:    v_perm_b32 v10, v10, v17, 0x7060302
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_3) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_bfe_u32 v16, v18, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v18
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-NEXT:    v_dual_add_f32 v19, 0x40c00000, v19 :: v_dual_add_f32 v8, 0x40c00000, v8
; GFX11-NEXT:    v_add3_u32 v16, v16, v18, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v9, 0xffff0000, v9
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_bfe_u32 v22, v19, 16, 1
; GFX11-NEXT:    v_bfe_u32 v18, v8, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_dual_cndmask_b32 v16, v16, v20 :: v_dual_add_f32 v9, 0x40c00000, v9
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v19
; GFX11-NEXT:    v_add3_u32 v18, v18, v8, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_bfe_u32 v17, v9, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v9
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-NEXT:    v_add3_u32 v17, v17, v9, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_3) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_cndmask_b32_e32 v9, v17, v21, vcc_lo
; GFX11-NEXT:    v_add3_u32 v17, v22, v19, 0x7fff
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v19, v19
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v8
; GFX11-NEXT:    v_perm_b32 v9, v9, v16, 0x7060302
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_cndmask_b32_e32 v17, v17, v20, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-NEXT:    v_cndmask_b32_e32 v8, v18, v22, vcc_lo
; GFX11-NEXT:    v_lshlrev_b32_e32 v18, 16, v6
; GFX11-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; GFX11-NEXT:    v_lshlrev_b32_e32 v21, 16, v7
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_perm_b32 v8, v8, v17, 0x7060302
; GFX11-NEXT:    v_add_f32_e32 v18, 0x40c00000, v18
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_dual_add_f32 v6, 0x40c00000, v6 :: v_dual_add_f32 v19, 0x40c00000, v21
; GFX11-NEXT:    v_bfe_u32 v22, v18, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_bfe_u32 v16, v19, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v19
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v19, v19
; GFX11-NEXT:    v_add3_u32 v16, v16, v19, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; GFX11-NEXT:    v_bfe_u32 v19, v6, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_dual_cndmask_b32 v16, v16, v20 :: v_dual_add_f32 v7, 0x40c00000, v7
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v18
; GFX11-NEXT:    v_add3_u32 v19, v19, v6, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_bfe_u32 v17, v7, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v7
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-NEXT:    v_add3_u32 v17, v17, v7, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_4) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_cndmask_b32_e32 v7, v17, v21, vcc_lo
; GFX11-NEXT:    v_add3_u32 v17, v22, v18, 0x7fff
; GFX11-NEXT:    v_lshlrev_b32_e32 v21, 16, v5
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v6
; GFX11-NEXT:    v_dual_add_f32 v18, 0x40c00000, v21 :: v_dual_cndmask_b32 v17, v17, v20
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_bfe_u32 v20, v18, 16, 1
; GFX11-NEXT:    v_dual_cndmask_b32 v6, v19, v22 :: v_dual_lshlrev_b32 v19, 16, v4
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; GFX11-NEXT:    v_perm_b32 v7, v7, v16, 0x7060302
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_4) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_perm_b32 v6, v6, v17, 0x7060302
; GFX11-NEXT:    v_add_f32_e32 v17, 0x40c00000, v19
; GFX11-NEXT:    v_add3_u32 v19, v20, v18, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v18
; GFX11-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; GFX11-NEXT:    v_bfe_u32 v22, v17, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_4) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_cndmask_b32_e32 v18, v19, v20, vcc_lo
; GFX11-NEXT:    v_or_b32_e32 v19, 0x400000, v17
; GFX11-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; GFX11-NEXT:    v_lshlrev_b32_e32 v20, 16, v3
; GFX11-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; GFX11-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_bfe_u32 v16, v5, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v5
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-NEXT:    v_add3_u32 v16, v16, v5, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_cndmask_b32_e32 v5, v16, v21, vcc_lo
; GFX11-NEXT:    v_add3_u32 v16, v22, v17, 0x7fff
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v17, v17
; GFX11-NEXT:    v_perm_b32 v5, v5, v18, 0x7060302
; GFX11-NEXT:    v_bfe_u32 v18, v4, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_2) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_cndmask_b32_e32 v16, v16, v19, vcc_lo
; GFX11-NEXT:    v_or_b32_e32 v19, 0x400000, v4
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-NEXT:    v_add3_u32 v18, v18, v4, 0x7fff
; GFX11-NEXT:    v_dual_add_f32 v17, 0x40c00000, v20 :: v_dual_lshlrev_b32 v20, 16, v2
; GFX11-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_cndmask_b32_e32 v4, v18, v19, vcc_lo
; GFX11-NEXT:    v_bfe_u32 v21, v17, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-NEXT:    v_add_f32_e32 v18, 0x40c00000, v20
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v17
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v17, v17
; GFX11-NEXT:    v_perm_b32 v4, v4, v16, 0x7060302
; GFX11-NEXT:    v_add3_u32 v19, v21, v17, 0x7fff
; GFX11-NEXT:    v_bfe_u32 v21, v3, 16, 1
; GFX11-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; GFX11-NEXT:    v_bfe_u32 v22, v18, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v23, 0x400000, v18
; GFX11-NEXT:    v_cndmask_b32_e32 v17, v19, v20, vcc_lo
; GFX11-NEXT:    v_add3_u32 v19, v21, v3, 0x7fff
; GFX11-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v3
; GFX11-NEXT:    v_add3_u32 v21, v22, v18, 0x7fff
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-NEXT:    v_lshlrev_b32_e32 v22, 16, v1
; GFX11-NEXT:    v_bfe_u32 v24, v2, 16, 1
; GFX11-NEXT:    v_cndmask_b32_e32 v3, v19, v20, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_add_f32_e32 v19, 0x40c00000, v22
; GFX11-NEXT:    v_add3_u32 v20, v24, v2, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_4) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_perm_b32 v3, v3, v17, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v18, v21, v23, vcc_lo
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v2
; GFX11-NEXT:    v_bfe_u32 v22, v19, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-NEXT:    v_dual_cndmask_b32 v2, v20, v21 :: v_dual_lshlrev_b32 v23, 16, v0
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-NEXT:    v_add3_u32 v21, v22, v19, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v19
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v19, v19
; GFX11-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX11-NEXT:    v_add_f32_e32 v20, 0x40c00000, v23
; GFX11-NEXT:    v_perm_b32 v2, v2, v18, 0x7060302
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_dual_cndmask_b32 v19, v21, v22 :: v_dual_add_f32 v0, 0x40c00000, v0
; GFX11-NEXT:    v_bfe_u32 v24, v20, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v25, 0x400000, v20
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_bfe_u32 v21, v0, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v26, 0x400000, v0
; GFX11-NEXT:    v_add3_u32 v24, v24, v20, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add3_u32 v21, v21, v0, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; GFX11-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_bfe_u32 v23, v1, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-NEXT:    v_add3_u32 v22, v23, v1, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v23, 0x400000, v1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_cndmask_b32_e32 v1, v22, v23, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v20, v20
; GFX11-NEXT:    v_perm_b32 v1, v1, v19, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v20, v24, v25, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-NEXT:    v_cndmask_b32_e32 v0, v21, v26, vcc_lo
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-NEXT:    v_perm_b32 v0, v0, v20, 0x7060302
; GFX11-NEXT:  .LBB29_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <32 x bfloat> %a, splat (bfloat 0xR40C0)
  %a2 = bitcast <32 x bfloat> %a1 to <8 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <32 x bfloat> %a to <8 x i64>
  br label %end

end:
  %phi = phi <8 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x i64> %phi
}

define <32 x i16> @v_bitcast_v8f64_to_v32i16(<8 x double> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v8f64_to_v32i16:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_mov_b32_e32 v55, v15
; GCN-NEXT:    v_mov_b32_e32 v54, v14
; GCN-NEXT:    v_mov_b32_e32 v53, v13
; GCN-NEXT:    v_mov_b32_e32 v52, v12
; GCN-NEXT:    v_mov_b32_e32 v51, v11
; GCN-NEXT:    v_mov_b32_e32 v50, v10
; GCN-NEXT:    v_mov_b32_e32 v49, v9
; GCN-NEXT:    v_mov_b32_e32 v48, v8
; GCN-NEXT:    v_mov_b32_e32 v38, v7
; GCN-NEXT:    v_mov_b32_e32 v37, v6
; GCN-NEXT:    v_mov_b32_e32 v36, v5
; GCN-NEXT:    v_mov_b32_e32 v35, v4
; GCN-NEXT:    v_mov_b32_e32 v34, v3
; GCN-NEXT:    v_mov_b32_e32 v33, v2
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GCN-NEXT:    ; implicit-def: $vgpr32
; GCN-NEXT:    ; implicit-def: $vgpr3
; GCN-NEXT:    ; implicit-def: $vgpr5
; GCN-NEXT:    ; implicit-def: $vgpr7
; GCN-NEXT:    ; implicit-def: $vgpr9
; GCN-NEXT:    ; implicit-def: $vgpr11
; GCN-NEXT:    ; implicit-def: $vgpr13
; GCN-NEXT:    ; implicit-def: $vgpr15
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr27
; GCN-NEXT:    ; implicit-def: $vgpr29
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB30_2
; GCN-NEXT:  ; %bb.1: ; %cmp.false
; GCN-NEXT:    v_alignbit_b32 v29, v55, v54, 16
; GCN-NEXT:    v_alignbit_b32 v25, v53, v52, 16
; GCN-NEXT:    v_alignbit_b32 v21, v51, v50, 16
; GCN-NEXT:    v_alignbit_b32 v17, v49, v48, 16
; GCN-NEXT:    v_alignbit_b32 v13, v38, v37, 16
; GCN-NEXT:    v_alignbit_b32 v9, v36, v35, 16
; GCN-NEXT:    v_alignbit_b32 v5, v34, v33, 16
; GCN-NEXT:    v_alignbit_b32 v32, v1, v0, 16
; GCN-NEXT:    v_lshrrev_b32_e32 v31, 16, v55
; GCN-NEXT:    v_lshrrev_b32_e32 v27, 16, v53
; GCN-NEXT:    v_lshrrev_b32_e32 v23, 16, v51
; GCN-NEXT:    v_lshrrev_b32_e32 v19, 16, v49
; GCN-NEXT:    v_lshrrev_b32_e32 v15, 16, v38
; GCN-NEXT:    v_lshrrev_b32_e32 v11, 16, v36
; GCN-NEXT:    v_lshrrev_b32_e32 v7, 16, v34
; GCN-NEXT:    v_lshrrev_b32_e32 v3, 16, v1
; GCN-NEXT:  .LBB30_2: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB30_4
; GCN-NEXT:  ; %bb.3: ; %cmp.true
; GCN-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GCN-NEXT:    v_add_f64 v[33:34], v[33:34], 1.0
; GCN-NEXT:    v_add_f64 v[35:36], v[35:36], 1.0
; GCN-NEXT:    v_add_f64 v[37:38], v[37:38], 1.0
; GCN-NEXT:    v_add_f64 v[48:49], v[48:49], 1.0
; GCN-NEXT:    v_add_f64 v[50:51], v[50:51], 1.0
; GCN-NEXT:    v_add_f64 v[52:53], v[52:53], 1.0
; GCN-NEXT:    v_add_f64 v[54:55], v[54:55], 1.0
; GCN-NEXT:    v_alignbit_b32 v29, v55, v54, 16
; GCN-NEXT:    v_alignbit_b32 v25, v53, v52, 16
; GCN-NEXT:    v_alignbit_b32 v21, v51, v50, 16
; GCN-NEXT:    v_alignbit_b32 v17, v49, v48, 16
; GCN-NEXT:    v_alignbit_b32 v13, v38, v37, 16
; GCN-NEXT:    v_alignbit_b32 v9, v36, v35, 16
; GCN-NEXT:    v_alignbit_b32 v5, v34, v33, 16
; GCN-NEXT:    v_alignbit_b32 v32, v1, v0, 16
; GCN-NEXT:    v_lshrrev_b32_e32 v31, 16, v55
; GCN-NEXT:    v_lshrrev_b32_e32 v27, 16, v53
; GCN-NEXT:    v_lshrrev_b32_e32 v23, 16, v51
; GCN-NEXT:    v_lshrrev_b32_e32 v19, 16, v49
; GCN-NEXT:    v_lshrrev_b32_e32 v15, 16, v38
; GCN-NEXT:    v_lshrrev_b32_e32 v11, 16, v36
; GCN-NEXT:    v_lshrrev_b32_e32 v7, 16, v34
; GCN-NEXT:    v_lshrrev_b32_e32 v3, 16, v1
; GCN-NEXT:  .LBB30_4: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    v_mov_b32_e32 v2, v1
; GCN-NEXT:    v_mov_b32_e32 v4, v33
; GCN-NEXT:    v_mov_b32_e32 v6, v34
; GCN-NEXT:    v_mov_b32_e32 v8, v35
; GCN-NEXT:    v_mov_b32_e32 v10, v36
; GCN-NEXT:    v_mov_b32_e32 v12, v37
; GCN-NEXT:    v_mov_b32_e32 v14, v38
; GCN-NEXT:    v_mov_b32_e32 v16, v48
; GCN-NEXT:    v_mov_b32_e32 v18, v49
; GCN-NEXT:    v_mov_b32_e32 v20, v50
; GCN-NEXT:    v_mov_b32_e32 v22, v51
; GCN-NEXT:    v_mov_b32_e32 v24, v52
; GCN-NEXT:    v_mov_b32_e32 v26, v53
; GCN-NEXT:    v_mov_b32_e32 v28, v54
; GCN-NEXT:    v_mov_b32_e32 v30, v55
; GCN-NEXT:    v_mov_b32_e32 v1, v32
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v8f64_to_v32i16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB30_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; VI-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; VI-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; VI-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; VI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; VI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; VI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; VI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; VI-NEXT:  .LBB30_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v8f64_to_v32i16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB30_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GFX9-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GFX9-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GFX9-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GFX9-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX9-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX9-NEXT:  .LBB30_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v8f64_to_v32i16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB30_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GFX11-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GFX11-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GFX11-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GFX11-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX11-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX11-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX11-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX11-NEXT:  .LBB30_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <8 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <8 x double> %a1 to <32 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <8 x double> %a to <32 x i16>
  br label %end

end:
  %phi = phi <32 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x i16> %phi
}

define <8 x double> @v_bitcast_v32i16_to_v8f64(<32 x i16> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v32i16_to_v8f64:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_mov_b32_e32 v38, v14
; GCN-NEXT:    v_mov_b32_e32 v37, v12
; GCN-NEXT:    v_mov_b32_e32 v36, v10
; GCN-NEXT:    v_mov_b32_e32 v35, v8
; GCN-NEXT:    v_mov_b32_e32 v34, v6
; GCN-NEXT:    v_mov_b32_e32 v33, v4
; GCN-NEXT:    v_mov_b32_e32 v32, v2
; GCN-NEXT:    v_mov_b32_e32 v31, v0
; GCN-NEXT:    buffer_load_dword v0, off, s[0:3], s32
; GCN-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:4
; GCN-NEXT:    v_lshlrev_b32_e32 v54, 16, v1
; GCN-NEXT:    v_lshlrev_b32_e32 v55, 16, v3
; GCN-NEXT:    v_lshlrev_b32_e32 v39, 16, v5
; GCN-NEXT:    v_lshlrev_b32_e32 v48, 16, v7
; GCN-NEXT:    v_lshlrev_b32_e32 v49, 16, v9
; GCN-NEXT:    v_lshlrev_b32_e32 v50, 16, v11
; GCN-NEXT:    v_lshlrev_b32_e32 v51, 16, v13
; GCN-NEXT:    v_lshlrev_b32_e32 v52, 16, v15
; GCN-NEXT:    v_lshlrev_b32_e32 v17, 16, v17
; GCN-NEXT:    v_lshlrev_b32_e32 v19, 16, v19
; GCN-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; GCN-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; GCN-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; GCN-NEXT:    v_lshlrev_b32_e32 v27, 16, v27
; GCN-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v2
; GCN-NEXT:    v_lshlrev_b32_e32 v53, 16, v0
; GCN-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execnz .LBB31_3
; GCN-NEXT:  ; %bb.1: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execnz .LBB31_4
; GCN-NEXT:  .LBB31_2: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
; GCN-NEXT:  .LBB31_3: ; %cmp.false
; GCN-NEXT:    v_and_b32_e32 v0, 0xffff, v31
; GCN-NEXT:    v_and_b32_e32 v1, 0xffff, v32
; GCN-NEXT:    v_or_b32_e32 v0, v0, v54
; GCN-NEXT:    v_or_b32_e32 v1, v1, v55
; GCN-NEXT:    v_and_b32_e32 v2, 0xffff, v33
; GCN-NEXT:    v_and_b32_e32 v3, 0xffff, v34
; GCN-NEXT:    v_and_b32_e32 v4, 0xffff, v35
; GCN-NEXT:    v_and_b32_e32 v5, 0xffff, v36
; GCN-NEXT:    v_and_b32_e32 v6, 0xffff, v37
; GCN-NEXT:    v_and_b32_e32 v7, 0xffff, v38
; GCN-NEXT:    v_and_b32_e32 v8, 0xffff, v16
; GCN-NEXT:    v_and_b32_e32 v9, 0xffff, v18
; GCN-NEXT:    v_and_b32_e32 v10, 0xffff, v20
; GCN-NEXT:    v_and_b32_e32 v11, 0xffff, v22
; GCN-NEXT:    v_and_b32_e32 v12, 0xffff, v24
; GCN-NEXT:    v_and_b32_e32 v13, 0xffff, v26
; GCN-NEXT:    v_and_b32_e32 v14, 0xffff, v28
; GCN-NEXT:    v_and_b32_e32 v15, 0xffff, v30
; GCN-NEXT:    v_or_b32_e32 v2, v2, v39
; GCN-NEXT:    v_or_b32_e32 v3, v3, v48
; GCN-NEXT:    v_or_b32_e32 v4, v4, v49
; GCN-NEXT:    v_or_b32_e32 v5, v5, v50
; GCN-NEXT:    v_or_b32_e32 v6, v6, v51
; GCN-NEXT:    v_or_b32_e32 v7, v7, v52
; GCN-NEXT:    v_or_b32_e32 v8, v8, v17
; GCN-NEXT:    v_or_b32_e32 v9, v9, v19
; GCN-NEXT:    v_or_b32_e32 v10, v10, v21
; GCN-NEXT:    v_or_b32_e32 v11, v11, v23
; GCN-NEXT:    v_or_b32_e32 v12, v12, v25
; GCN-NEXT:    v_or_b32_e32 v13, v13, v27
; GCN-NEXT:    v_or_b32_e32 v14, v14, v29
; GCN-NEXT:    v_or_b32_e32 v15, v15, v53
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    ; implicit-def: $vgpr32
; GCN-NEXT:    ; implicit-def: $vgpr33
; GCN-NEXT:    ; implicit-def: $vgpr34
; GCN-NEXT:    ; implicit-def: $vgpr35
; GCN-NEXT:    ; implicit-def: $vgpr36
; GCN-NEXT:    ; implicit-def: $vgpr37
; GCN-NEXT:    ; implicit-def: $vgpr38
; GCN-NEXT:    ; implicit-def: $vgpr16
; GCN-NEXT:    ; implicit-def: $vgpr18
; GCN-NEXT:    ; implicit-def: $vgpr20
; GCN-NEXT:    ; implicit-def: $vgpr22
; GCN-NEXT:    ; implicit-def: $vgpr24
; GCN-NEXT:    ; implicit-def: $vgpr26
; GCN-NEXT:    ; implicit-def: $vgpr28
; GCN-NEXT:    ; implicit-def: $vgpr30
; GCN-NEXT:    ; implicit-def: $vgpr54
; GCN-NEXT:    ; implicit-def: $vgpr55
; GCN-NEXT:    ; implicit-def: $vgpr39
; GCN-NEXT:    ; implicit-def: $vgpr48
; GCN-NEXT:    ; implicit-def: $vgpr49
; GCN-NEXT:    ; implicit-def: $vgpr50
; GCN-NEXT:    ; implicit-def: $vgpr51
; GCN-NEXT:    ; implicit-def: $vgpr52
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr27
; GCN-NEXT:    ; implicit-def: $vgpr29
; GCN-NEXT:    ; implicit-def: $vgpr53
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB31_2
; GCN-NEXT:  .LBB31_4: ; %cmp.true
; GCN-NEXT:    v_add_i32_e32 v0, vcc, 3, v31
; GCN-NEXT:    s_mov_b32 s6, 0x30000
; GCN-NEXT:    v_add_i32_e32 v1, vcc, 3, v32
; GCN-NEXT:    v_add_i32_e32 v2, vcc, 3, v33
; GCN-NEXT:    v_add_i32_e32 v3, vcc, 3, v34
; GCN-NEXT:    v_add_i32_e32 v4, vcc, 3, v35
; GCN-NEXT:    v_add_i32_e32 v5, vcc, 3, v36
; GCN-NEXT:    v_add_i32_e32 v6, vcc, 3, v37
; GCN-NEXT:    v_add_i32_e32 v7, vcc, 3, v38
; GCN-NEXT:    v_add_i32_e32 v8, vcc, 3, v16
; GCN-NEXT:    v_add_i32_e32 v9, vcc, 3, v18
; GCN-NEXT:    v_add_i32_e32 v10, vcc, 3, v20
; GCN-NEXT:    v_add_i32_e32 v11, vcc, 3, v22
; GCN-NEXT:    v_add_i32_e32 v12, vcc, 3, v24
; GCN-NEXT:    v_add_i32_e32 v13, vcc, 3, v26
; GCN-NEXT:    v_add_i32_e32 v14, vcc, 3, v28
; GCN-NEXT:    v_add_i32_e32 v15, vcc, 3, v30
; GCN-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GCN-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; GCN-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GCN-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GCN-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GCN-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GCN-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; GCN-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; GCN-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; GCN-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; GCN-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; GCN-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; GCN-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; GCN-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; GCN-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; GCN-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; GCN-NEXT:    v_or_b32_e32 v0, v54, v0
; GCN-NEXT:    v_or_b32_e32 v1, v55, v1
; GCN-NEXT:    v_or_b32_e32 v2, v39, v2
; GCN-NEXT:    v_or_b32_e32 v3, v48, v3
; GCN-NEXT:    v_or_b32_e32 v4, v49, v4
; GCN-NEXT:    v_or_b32_e32 v5, v50, v5
; GCN-NEXT:    v_or_b32_e32 v6, v51, v6
; GCN-NEXT:    v_or_b32_e32 v7, v52, v7
; GCN-NEXT:    v_or_b32_e32 v8, v17, v8
; GCN-NEXT:    v_or_b32_e32 v9, v19, v9
; GCN-NEXT:    v_or_b32_e32 v10, v21, v10
; GCN-NEXT:    v_or_b32_e32 v11, v23, v11
; GCN-NEXT:    v_or_b32_e32 v12, v25, v12
; GCN-NEXT:    v_or_b32_e32 v13, v27, v13
; GCN-NEXT:    v_or_b32_e32 v14, v29, v14
; GCN-NEXT:    v_or_b32_e32 v15, v53, v15
; GCN-NEXT:    v_add_i32_e32 v0, vcc, 0x30000, v0
; GCN-NEXT:    v_add_i32_e32 v1, vcc, s6, v1
; GCN-NEXT:    v_add_i32_e32 v2, vcc, s6, v2
; GCN-NEXT:    v_add_i32_e32 v3, vcc, s6, v3
; GCN-NEXT:    v_add_i32_e32 v4, vcc, s6, v4
; GCN-NEXT:    v_add_i32_e32 v5, vcc, s6, v5
; GCN-NEXT:    v_add_i32_e32 v6, vcc, s6, v6
; GCN-NEXT:    v_add_i32_e32 v7, vcc, s6, v7
; GCN-NEXT:    v_add_i32_e32 v8, vcc, s6, v8
; GCN-NEXT:    v_add_i32_e32 v9, vcc, s6, v9
; GCN-NEXT:    v_add_i32_e32 v10, vcc, s6, v10
; GCN-NEXT:    v_add_i32_e32 v11, vcc, s6, v11
; GCN-NEXT:    v_add_i32_e32 v12, vcc, s6, v12
; GCN-NEXT:    v_add_i32_e32 v13, vcc, 0x30000, v13
; GCN-NEXT:    v_add_i32_e32 v14, vcc, 0x30000, v14
; GCN-NEXT:    v_add_i32_e32 v15, vcc, 0x30000, v15
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v32i16_to_v8f64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB31_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v17, 3
; VI-NEXT:    v_add_u16_e32 v16, 3, v15
; VI-NEXT:    v_add_u16_sdwa v15, v15, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v15, v16, v15
; VI-NEXT:    v_add_u16_e32 v16, 3, v14
; VI-NEXT:    v_add_u16_sdwa v14, v14, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v14, v16, v14
; VI-NEXT:    v_add_u16_e32 v16, 3, v13
; VI-NEXT:    v_add_u16_sdwa v13, v13, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v13, v16, v13
; VI-NEXT:    v_add_u16_e32 v16, 3, v12
; VI-NEXT:    v_add_u16_sdwa v12, v12, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v12, v16, v12
; VI-NEXT:    v_add_u16_e32 v16, 3, v11
; VI-NEXT:    v_add_u16_sdwa v11, v11, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v11, v16, v11
; VI-NEXT:    v_add_u16_e32 v16, 3, v10
; VI-NEXT:    v_add_u16_sdwa v10, v10, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v10, v16, v10
; VI-NEXT:    v_add_u16_e32 v16, 3, v9
; VI-NEXT:    v_add_u16_sdwa v9, v9, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v9, v16, v9
; VI-NEXT:    v_add_u16_e32 v16, 3, v8
; VI-NEXT:    v_add_u16_sdwa v8, v8, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v8, v16, v8
; VI-NEXT:    v_add_u16_e32 v16, 3, v7
; VI-NEXT:    v_add_u16_sdwa v7, v7, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v7, v16, v7
; VI-NEXT:    v_add_u16_e32 v16, 3, v6
; VI-NEXT:    v_add_u16_sdwa v6, v6, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v6, v16, v6
; VI-NEXT:    v_add_u16_e32 v16, 3, v5
; VI-NEXT:    v_add_u16_sdwa v5, v5, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v5, v16, v5
; VI-NEXT:    v_add_u16_e32 v16, 3, v4
; VI-NEXT:    v_add_u16_sdwa v4, v4, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v4, v16, v4
; VI-NEXT:    v_add_u16_e32 v16, 3, v3
; VI-NEXT:    v_add_u16_sdwa v3, v3, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v3, v16, v3
; VI-NEXT:    v_add_u16_e32 v16, 3, v2
; VI-NEXT:    v_add_u16_sdwa v2, v2, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v2, v16, v2
; VI-NEXT:    v_add_u16_e32 v16, 3, v1
; VI-NEXT:    v_add_u16_sdwa v1, v1, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v1, v16, v1
; VI-NEXT:    v_add_u16_e32 v16, 3, v0
; VI-NEXT:    v_add_u16_sdwa v0, v0, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v0, v16, v0
; VI-NEXT:  .LBB31_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v32i16_to_v8f64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB31_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_pk_add_u16 v15, v15, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v14, v14, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v13, v13, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v12, v12, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v9, v9, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v8, v8, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX9-NEXT:  .LBB31_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v32i16_to_v8f64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB31_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_pk_add_u16 v15, v15, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v14, v14, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v13, v13, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v12, v12, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v9, v9, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v8, v8, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX11-NEXT:  .LBB31_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <32 x i16> %a, splat (i16 3)
  %a2 = bitcast <32 x i16> %a1 to <8 x double>
  br label %end

cmp.false:
  %a3 = bitcast <32 x i16> %a to <8 x double>
  br label %end

end:
  %phi = phi <8 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x double> %phi
}

define <32 x half> @v_bitcast_v8f64_to_v32f16(<8 x double> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v8f64_to_v32f16:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v42, off, s[0:3], s32 ; 4-byte Folded Spill
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GCN-NEXT:    ; implicit-def: $vgpr39
; GCN-NEXT:    ; implicit-def: $vgpr55
; GCN-NEXT:    ; implicit-def: $vgpr32
; GCN-NEXT:    ; implicit-def: $vgpr54
; GCN-NEXT:    ; implicit-def: $vgpr33
; GCN-NEXT:    ; implicit-def: $vgpr53
; GCN-NEXT:    ; implicit-def: $vgpr34
; GCN-NEXT:    ; implicit-def: $vgpr52
; GCN-NEXT:    ; implicit-def: $vgpr35
; GCN-NEXT:    ; implicit-def: $vgpr51
; GCN-NEXT:    ; implicit-def: $vgpr36
; GCN-NEXT:    ; implicit-def: $vgpr50
; GCN-NEXT:    ; implicit-def: $vgpr37
; GCN-NEXT:    ; implicit-def: $vgpr49
; GCN-NEXT:    ; implicit-def: $vgpr38
; GCN-NEXT:    ; implicit-def: $vgpr48
; GCN-NEXT:    ; implicit-def: $vgpr16
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr18
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr20
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr22
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr24
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr26
; GCN-NEXT:    ; implicit-def: $vgpr27
; GCN-NEXT:    ; implicit-def: $vgpr28
; GCN-NEXT:    ; implicit-def: $vgpr29
; GCN-NEXT:    ; implicit-def: $vgpr30
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB32_2
; GCN-NEXT:  ; %bb.1: ; %cmp.false
; GCN-NEXT:    v_lshrrev_b32_e32 v17, 16, v15
; GCN-NEXT:    v_lshrrev_b32_e32 v19, 16, v14
; GCN-NEXT:    v_lshrrev_b32_e32 v21, 16, v13
; GCN-NEXT:    v_lshrrev_b32_e32 v23, 16, v12
; GCN-NEXT:    v_lshrrev_b32_e32 v39, 16, v11
; GCN-NEXT:    v_lshrrev_b32_e32 v48, 16, v10
; GCN-NEXT:    v_lshrrev_b32_e32 v49, 16, v9
; GCN-NEXT:    v_lshrrev_b32_e32 v50, 16, v8
; GCN-NEXT:    v_lshrrev_b32_e32 v51, 16, v7
; GCN-NEXT:    v_lshrrev_b32_e32 v52, 16, v6
; GCN-NEXT:    v_lshrrev_b32_e32 v53, 16, v5
; GCN-NEXT:    v_lshrrev_b32_e32 v54, 16, v4
; GCN-NEXT:    v_lshrrev_b32_e32 v55, 16, v3
; GCN-NEXT:    s_waitcnt expcnt(2)
; GCN-NEXT:    v_lshrrev_b32_e32 v40, 16, v2
; GCN-NEXT:    s_waitcnt expcnt(1)
; GCN-NEXT:    v_lshrrev_b32_e32 v41, 16, v1
; GCN-NEXT:    s_waitcnt expcnt(0)
; GCN-NEXT:    v_lshrrev_b32_e32 v42, 16, v0
; GCN-NEXT:    v_cvt_f32_f16_e32 v30, v15
; GCN-NEXT:    v_cvt_f32_f16_e32 v28, v14
; GCN-NEXT:    v_cvt_f32_f16_e32 v26, v13
; GCN-NEXT:    v_cvt_f32_f16_e32 v24, v12
; GCN-NEXT:    v_cvt_f32_f16_e32 v22, v11
; GCN-NEXT:    v_cvt_f32_f16_e32 v20, v10
; GCN-NEXT:    v_cvt_f32_f16_e32 v18, v9
; GCN-NEXT:    v_cvt_f32_f16_e32 v16, v8
; GCN-NEXT:    v_cvt_f32_f16_e32 v38, v7
; GCN-NEXT:    v_cvt_f32_f16_e32 v37, v6
; GCN-NEXT:    v_cvt_f32_f16_e32 v36, v5
; GCN-NEXT:    v_cvt_f32_f16_e32 v35, v4
; GCN-NEXT:    v_cvt_f32_f16_e32 v34, v3
; GCN-NEXT:    v_cvt_f32_f16_e32 v33, v2
; GCN-NEXT:    v_cvt_f32_f16_e32 v32, v1
; GCN-NEXT:    v_cvt_f32_f16_e32 v31, v17
; GCN-NEXT:    v_cvt_f32_f16_e32 v29, v19
; GCN-NEXT:    v_cvt_f32_f16_e32 v27, v21
; GCN-NEXT:    v_cvt_f32_f16_e32 v25, v23
; GCN-NEXT:    v_cvt_f32_f16_e32 v23, v39
; GCN-NEXT:    v_cvt_f32_f16_e32 v21, v48
; GCN-NEXT:    v_cvt_f32_f16_e32 v19, v49
; GCN-NEXT:    v_cvt_f32_f16_e32 v17, v50
; GCN-NEXT:    v_cvt_f32_f16_e32 v48, v51
; GCN-NEXT:    v_cvt_f32_f16_e32 v49, v52
; GCN-NEXT:    v_cvt_f32_f16_e32 v50, v53
; GCN-NEXT:    v_cvt_f32_f16_e32 v51, v54
; GCN-NEXT:    v_cvt_f32_f16_e32 v52, v55
; GCN-NEXT:    v_cvt_f32_f16_e32 v53, v40
; GCN-NEXT:    v_cvt_f32_f16_e32 v54, v41
; GCN-NEXT:    v_cvt_f32_f16_e32 v55, v42
; GCN-NEXT:    v_cvt_f32_f16_e32 v39, v0
; GCN-NEXT:    ; implicit-def: $vgpr0
; GCN-NEXT:    ; implicit-def: $vgpr2
; GCN-NEXT:    ; implicit-def: $vgpr4
; GCN-NEXT:    ; implicit-def: $vgpr6
; GCN-NEXT:    ; implicit-def: $vgpr8
; GCN-NEXT:    ; implicit-def: $vgpr10
; GCN-NEXT:    ; implicit-def: $vgpr12
; GCN-NEXT:    ; implicit-def: $vgpr14
; GCN-NEXT:  .LBB32_2: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB32_4
; GCN-NEXT:  ; %bb.3: ; %cmp.true
; GCN-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GCN-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GCN-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GCN-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GCN-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GCN-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GCN-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GCN-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GCN-NEXT:    v_lshrrev_b32_e32 v55, 16, v0
; GCN-NEXT:    v_lshrrev_b32_e32 v54, 16, v1
; GCN-NEXT:    v_lshrrev_b32_e32 v53, 16, v2
; GCN-NEXT:    v_lshrrev_b32_e32 v52, 16, v3
; GCN-NEXT:    v_lshrrev_b32_e32 v51, 16, v4
; GCN-NEXT:    v_lshrrev_b32_e32 v50, 16, v5
; GCN-NEXT:    v_lshrrev_b32_e32 v49, 16, v6
; GCN-NEXT:    v_lshrrev_b32_e32 v48, 16, v7
; GCN-NEXT:    v_lshrrev_b32_e32 v17, 16, v8
; GCN-NEXT:    v_lshrrev_b32_e32 v19, 16, v9
; GCN-NEXT:    v_lshrrev_b32_e32 v21, 16, v10
; GCN-NEXT:    v_lshrrev_b32_e32 v23, 16, v11
; GCN-NEXT:    v_lshrrev_b32_e32 v25, 16, v12
; GCN-NEXT:    v_lshrrev_b32_e32 v27, 16, v13
; GCN-NEXT:    v_lshrrev_b32_e32 v29, 16, v14
; GCN-NEXT:    v_lshrrev_b32_e32 v31, 16, v15
; GCN-NEXT:    v_cvt_f32_f16_e32 v30, v15
; GCN-NEXT:    v_cvt_f32_f16_e32 v28, v14
; GCN-NEXT:    v_cvt_f32_f16_e32 v26, v13
; GCN-NEXT:    v_cvt_f32_f16_e32 v24, v12
; GCN-NEXT:    v_cvt_f32_f16_e32 v22, v11
; GCN-NEXT:    v_cvt_f32_f16_e32 v20, v10
; GCN-NEXT:    v_cvt_f32_f16_e32 v18, v9
; GCN-NEXT:    v_cvt_f32_f16_e32 v16, v8
; GCN-NEXT:    v_cvt_f32_f16_e32 v38, v7
; GCN-NEXT:    v_cvt_f32_f16_e32 v37, v6
; GCN-NEXT:    v_cvt_f32_f16_e32 v36, v5
; GCN-NEXT:    v_cvt_f32_f16_e32 v35, v4
; GCN-NEXT:    v_cvt_f32_f16_e32 v34, v3
; GCN-NEXT:    v_cvt_f32_f16_e32 v33, v2
; GCN-NEXT:    v_cvt_f32_f16_e32 v32, v1
; GCN-NEXT:    v_cvt_f32_f16_e32 v39, v0
; GCN-NEXT:    v_cvt_f32_f16_e32 v31, v31
; GCN-NEXT:    v_cvt_f32_f16_e32 v29, v29
; GCN-NEXT:    v_cvt_f32_f16_e32 v27, v27
; GCN-NEXT:    v_cvt_f32_f16_e32 v25, v25
; GCN-NEXT:    v_cvt_f32_f16_e32 v23, v23
; GCN-NEXT:    v_cvt_f32_f16_e32 v21, v21
; GCN-NEXT:    v_cvt_f32_f16_e32 v19, v19
; GCN-NEXT:    v_cvt_f32_f16_e32 v17, v17
; GCN-NEXT:    v_cvt_f32_f16_e32 v48, v48
; GCN-NEXT:    v_cvt_f32_f16_e32 v49, v49
; GCN-NEXT:    v_cvt_f32_f16_e32 v50, v50
; GCN-NEXT:    v_cvt_f32_f16_e32 v51, v51
; GCN-NEXT:    v_cvt_f32_f16_e32 v52, v52
; GCN-NEXT:    v_cvt_f32_f16_e32 v53, v53
; GCN-NEXT:    v_cvt_f32_f16_e32 v54, v54
; GCN-NEXT:    v_cvt_f32_f16_e32 v55, v55
; GCN-NEXT:  .LBB32_4: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    v_mov_b32_e32 v0, v39
; GCN-NEXT:    v_mov_b32_e32 v1, v55
; GCN-NEXT:    v_mov_b32_e32 v2, v32
; GCN-NEXT:    v_mov_b32_e32 v3, v54
; GCN-NEXT:    v_mov_b32_e32 v4, v33
; GCN-NEXT:    v_mov_b32_e32 v5, v53
; GCN-NEXT:    v_mov_b32_e32 v6, v34
; GCN-NEXT:    v_mov_b32_e32 v7, v52
; GCN-NEXT:    v_mov_b32_e32 v8, v35
; GCN-NEXT:    v_mov_b32_e32 v9, v51
; GCN-NEXT:    v_mov_b32_e32 v10, v36
; GCN-NEXT:    v_mov_b32_e32 v11, v50
; GCN-NEXT:    v_mov_b32_e32 v12, v37
; GCN-NEXT:    v_mov_b32_e32 v13, v49
; GCN-NEXT:    v_mov_b32_e32 v14, v38
; GCN-NEXT:    v_mov_b32_e32 v15, v48
; GCN-NEXT:    s_waitcnt expcnt(0)
; GCN-NEXT:    buffer_load_dword v42, off, s[0:3], s32 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v8f64_to_v32f16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB32_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; VI-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; VI-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; VI-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; VI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; VI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; VI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; VI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; VI-NEXT:  .LBB32_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v8f64_to_v32f16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB32_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GFX9-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GFX9-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GFX9-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GFX9-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX9-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX9-NEXT:  .LBB32_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v8f64_to_v32f16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB32_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GFX11-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GFX11-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GFX11-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GFX11-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX11-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX11-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX11-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX11-NEXT:  .LBB32_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <8 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <8 x double> %a1 to <32 x half>
  br label %end

cmp.false:
  %a3 = bitcast <8 x double> %a to <32 x half>
  br label %end

end:
  %phi = phi <32 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x half> %phi
}

define <8 x double> @v_bitcast_v32f16_to_v8f64(<32 x half> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v32f16_to_v8f64:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GCN-NEXT:    s_waitcnt expcnt(1)
; GCN-NEXT:    buffer_load_dword v46, off, s[0:3], s32
; GCN-NEXT:    s_waitcnt expcnt(0)
; GCN-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:4
; GCN-NEXT:    v_cvt_f16_f32_e32 v45, v1
; GCN-NEXT:    v_cvt_f16_f32_e32 v44, v0
; GCN-NEXT:    v_cvt_f16_f32_e32 v43, v3
; GCN-NEXT:    v_cvt_f16_f32_e32 v42, v2
; GCN-NEXT:    v_cvt_f16_f32_e32 v41, v5
; GCN-NEXT:    v_cvt_f16_f32_e32 v52, v4
; GCN-NEXT:    v_cvt_f16_f32_e32 v40, v7
; GCN-NEXT:    v_cvt_f16_f32_e32 v50, v6
; GCN-NEXT:    v_cvt_f16_f32_e32 v55, v9
; GCN-NEXT:    v_cvt_f16_f32_e32 v48, v8
; GCN-NEXT:    v_cvt_f16_f32_e32 v54, v11
; GCN-NEXT:    v_cvt_f16_f32_e32 v38, v10
; GCN-NEXT:    v_cvt_f16_f32_e32 v53, v13
; GCN-NEXT:    v_cvt_f16_f32_e32 v36, v12
; GCN-NEXT:    v_cvt_f16_f32_e32 v51, v15
; GCN-NEXT:    v_cvt_f16_f32_e32 v34, v14
; GCN-NEXT:    v_cvt_f16_f32_e32 v49, v17
; GCN-NEXT:    v_cvt_f16_f32_e32 v33, v16
; GCN-NEXT:    v_cvt_f16_f32_e32 v39, v19
; GCN-NEXT:    v_cvt_f16_f32_e32 v32, v18
; GCN-NEXT:    v_cvt_f16_f32_e32 v37, v21
; GCN-NEXT:    v_cvt_f16_f32_e32 v31, v20
; GCN-NEXT:    v_cvt_f16_f32_e32 v35, v23
; GCN-NEXT:    v_cvt_f16_f32_e32 v21, v22
; GCN-NEXT:    v_cvt_f16_f32_e32 v25, v25
; GCN-NEXT:    v_cvt_f16_f32_e32 v19, v24
; GCN-NEXT:    v_cvt_f16_f32_e32 v23, v27
; GCN-NEXT:    v_cvt_f16_f32_e32 v18, v26
; GCN-NEXT:    v_cvt_f16_f32_e32 v22, v29
; GCN-NEXT:    v_cvt_f16_f32_e32 v17, v28
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v47
; GCN-NEXT:    v_cvt_f16_f32_e32 v20, v46
; GCN-NEXT:    v_cvt_f16_f32_e32 v16, v30
; GCN-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB33_2
; GCN-NEXT:  ; %bb.1: ; %cmp.false
; GCN-NEXT:    v_lshlrev_b32_e32 v0, 16, v45
; GCN-NEXT:    v_lshlrev_b32_e32 v1, 16, v43
; GCN-NEXT:    v_or_b32_e32 v0, v44, v0
; GCN-NEXT:    v_or_b32_e32 v1, v42, v1
; GCN-NEXT:    v_lshlrev_b32_e32 v2, 16, v41
; GCN-NEXT:    v_lshlrev_b32_e32 v3, 16, v40
; GCN-NEXT:    v_lshlrev_b32_e32 v4, 16, v55
; GCN-NEXT:    v_lshlrev_b32_e32 v5, 16, v54
; GCN-NEXT:    v_lshlrev_b32_e32 v6, 16, v53
; GCN-NEXT:    v_lshlrev_b32_e32 v7, 16, v51
; GCN-NEXT:    v_lshlrev_b32_e32 v8, 16, v49
; GCN-NEXT:    v_lshlrev_b32_e32 v9, 16, v39
; GCN-NEXT:    v_lshlrev_b32_e32 v10, 16, v37
; GCN-NEXT:    v_lshlrev_b32_e32 v11, 16, v35
; GCN-NEXT:    v_lshlrev_b32_e32 v12, 16, v25
; GCN-NEXT:    v_lshlrev_b32_e32 v13, 16, v23
; GCN-NEXT:    v_lshlrev_b32_e32 v14, 16, v22
; GCN-NEXT:    v_lshlrev_b32_e32 v15, 16, v20
; GCN-NEXT:    v_or_b32_e32 v2, v52, v2
; GCN-NEXT:    v_or_b32_e32 v3, v50, v3
; GCN-NEXT:    v_or_b32_e32 v4, v48, v4
; GCN-NEXT:    v_or_b32_e32 v5, v38, v5
; GCN-NEXT:    v_or_b32_e32 v6, v36, v6
; GCN-NEXT:    v_or_b32_e32 v7, v34, v7
; GCN-NEXT:    v_or_b32_e32 v8, v33, v8
; GCN-NEXT:    v_or_b32_e32 v9, v32, v9
; GCN-NEXT:    v_or_b32_e32 v10, v31, v10
; GCN-NEXT:    v_or_b32_e32 v11, v21, v11
; GCN-NEXT:    v_or_b32_e32 v12, v19, v12
; GCN-NEXT:    v_or_b32_e32 v13, v18, v13
; GCN-NEXT:    v_or_b32_e32 v14, v17, v14
; GCN-NEXT:    v_or_b32_e32 v15, v16, v15
; GCN-NEXT:    ; implicit-def: $vgpr45
; GCN-NEXT:    ; implicit-def: $vgpr44
; GCN-NEXT:    ; implicit-def: $vgpr43
; GCN-NEXT:    ; implicit-def: $vgpr42
; GCN-NEXT:    ; implicit-def: $vgpr41
; GCN-NEXT:    ; implicit-def: $vgpr52
; GCN-NEXT:    ; implicit-def: $vgpr40
; GCN-NEXT:    ; implicit-def: $vgpr50
; GCN-NEXT:    ; implicit-def: $vgpr55
; GCN-NEXT:    ; implicit-def: $vgpr48
; GCN-NEXT:    ; implicit-def: $vgpr54
; GCN-NEXT:    ; implicit-def: $vgpr38
; GCN-NEXT:    ; implicit-def: $vgpr53
; GCN-NEXT:    ; implicit-def: $vgpr36
; GCN-NEXT:    ; implicit-def: $vgpr51
; GCN-NEXT:    ; implicit-def: $vgpr34
; GCN-NEXT:    ; implicit-def: $vgpr49
; GCN-NEXT:    ; implicit-def: $vgpr33
; GCN-NEXT:    ; implicit-def: $vgpr39
; GCN-NEXT:    ; implicit-def: $vgpr32
; GCN-NEXT:    ; implicit-def: $vgpr37
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    ; implicit-def: $vgpr35
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr18
; GCN-NEXT:    ; implicit-def: $vgpr22
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr20
; GCN-NEXT:    ; implicit-def: $vgpr16
; GCN-NEXT:  .LBB33_2: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB33_4
; GCN-NEXT:  ; %bb.3: ; %cmp.true
; GCN-NEXT:    v_cvt_f32_f16_e32 v0, v45
; GCN-NEXT:    v_cvt_f32_f16_e32 v1, v44
; GCN-NEXT:    v_cvt_f32_f16_e32 v2, v43
; GCN-NEXT:    v_cvt_f32_f16_e32 v3, v42
; GCN-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; GCN-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; GCN-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; GCN-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; GCN-NEXT:    v_cvt_f16_f32_e32 v0, v0
; GCN-NEXT:    v_cvt_f16_f32_e32 v1, v1
; GCN-NEXT:    v_cvt_f16_f32_e32 v2, v2
; GCN-NEXT:    v_cvt_f16_f32_e32 v3, v3
; GCN-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; GCN-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; GCN-NEXT:    v_or_b32_e32 v0, v1, v0
; GCN-NEXT:    v_or_b32_e32 v1, v3, v2
; GCN-NEXT:    v_cvt_f32_f16_e32 v2, v41
; GCN-NEXT:    v_cvt_f32_f16_e32 v3, v52
; GCN-NEXT:    v_cvt_f32_f16_e32 v4, v40
; GCN-NEXT:    v_cvt_f32_f16_e32 v5, v50
; GCN-NEXT:    v_cvt_f32_f16_e32 v6, v55
; GCN-NEXT:    v_cvt_f32_f16_e32 v7, v48
; GCN-NEXT:    v_cvt_f32_f16_e32 v8, v54
; GCN-NEXT:    v_cvt_f32_f16_e32 v9, v38
; GCN-NEXT:    v_cvt_f32_f16_e32 v10, v53
; GCN-NEXT:    v_cvt_f32_f16_e32 v11, v36
; GCN-NEXT:    v_cvt_f32_f16_e32 v12, v51
; GCN-NEXT:    v_cvt_f32_f16_e32 v13, v34
; GCN-NEXT:    v_cvt_f32_f16_e32 v14, v49
; GCN-NEXT:    v_cvt_f32_f16_e32 v15, v33
; GCN-NEXT:    v_cvt_f32_f16_e32 v24, v39
; GCN-NEXT:    v_cvt_f32_f16_e32 v26, v32
; GCN-NEXT:    v_cvt_f32_f16_e32 v27, v37
; GCN-NEXT:    v_cvt_f32_f16_e32 v28, v31
; GCN-NEXT:    v_cvt_f32_f16_e32 v29, v35
; GCN-NEXT:    v_cvt_f32_f16_e32 v21, v21
; GCN-NEXT:    v_cvt_f32_f16_e32 v25, v25
; GCN-NEXT:    v_cvt_f32_f16_e32 v19, v19
; GCN-NEXT:    v_cvt_f32_f16_e32 v23, v23
; GCN-NEXT:    v_cvt_f32_f16_e32 v18, v18
; GCN-NEXT:    v_cvt_f32_f16_e32 v22, v22
; GCN-NEXT:    v_cvt_f32_f16_e32 v17, v17
; GCN-NEXT:    v_cvt_f32_f16_e32 v20, v20
; GCN-NEXT:    v_cvt_f32_f16_e32 v16, v16
; GCN-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; GCN-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; GCN-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; GCN-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; GCN-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; GCN-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; GCN-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; GCN-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; GCN-NEXT:    v_add_f32_e32 v10, 0x38000000, v10
; GCN-NEXT:    v_add_f32_e32 v11, 0x38000000, v11
; GCN-NEXT:    v_add_f32_e32 v12, 0x38000000, v12
; GCN-NEXT:    v_add_f32_e32 v13, 0x38000000, v13
; GCN-NEXT:    v_add_f32_e32 v14, 0x38000000, v14
; GCN-NEXT:    v_add_f32_e32 v15, 0x38000000, v15
; GCN-NEXT:    v_add_f32_e32 v24, 0x38000000, v24
; GCN-NEXT:    v_add_f32_e32 v26, 0x38000000, v26
; GCN-NEXT:    v_add_f32_e32 v27, 0x38000000, v27
; GCN-NEXT:    v_add_f32_e32 v28, 0x38000000, v28
; GCN-NEXT:    v_add_f32_e32 v29, 0x38000000, v29
; GCN-NEXT:    v_add_f32_e32 v21, 0x38000000, v21
; GCN-NEXT:    v_add_f32_e32 v25, 0x38000000, v25
; GCN-NEXT:    v_add_f32_e32 v19, 0x38000000, v19
; GCN-NEXT:    v_add_f32_e32 v23, 0x38000000, v23
; GCN-NEXT:    v_add_f32_e32 v18, 0x38000000, v18
; GCN-NEXT:    v_add_f32_e32 v22, 0x38000000, v22
; GCN-NEXT:    v_add_f32_e32 v17, 0x38000000, v17
; GCN-NEXT:    v_add_f32_e32 v20, 0x38000000, v20
; GCN-NEXT:    v_add_f32_e32 v16, 0x38000000, v16
; GCN-NEXT:    v_cvt_f16_f32_e32 v2, v2
; GCN-NEXT:    v_cvt_f16_f32_e32 v3, v3
; GCN-NEXT:    v_cvt_f16_f32_e32 v4, v4
; GCN-NEXT:    v_cvt_f16_f32_e32 v5, v5
; GCN-NEXT:    v_cvt_f16_f32_e32 v6, v6
; GCN-NEXT:    v_cvt_f16_f32_e32 v7, v7
; GCN-NEXT:    v_cvt_f16_f32_e32 v8, v8
; GCN-NEXT:    v_cvt_f16_f32_e32 v9, v9
; GCN-NEXT:    v_cvt_f16_f32_e32 v10, v10
; GCN-NEXT:    v_cvt_f16_f32_e32 v11, v11
; GCN-NEXT:    v_cvt_f16_f32_e32 v12, v12
; GCN-NEXT:    v_cvt_f16_f32_e32 v13, v13
; GCN-NEXT:    v_cvt_f16_f32_e32 v14, v14
; GCN-NEXT:    v_cvt_f16_f32_e32 v15, v15
; GCN-NEXT:    v_cvt_f16_f32_e32 v24, v24
; GCN-NEXT:    v_cvt_f16_f32_e32 v26, v26
; GCN-NEXT:    v_cvt_f16_f32_e32 v27, v27
; GCN-NEXT:    v_cvt_f16_f32_e32 v28, v28
; GCN-NEXT:    v_cvt_f16_f32_e32 v29, v29
; GCN-NEXT:    v_cvt_f16_f32_e32 v21, v21
; GCN-NEXT:    v_cvt_f16_f32_e32 v25, v25
; GCN-NEXT:    v_cvt_f16_f32_e32 v19, v19
; GCN-NEXT:    v_cvt_f16_f32_e32 v23, v23
; GCN-NEXT:    v_cvt_f16_f32_e32 v18, v18
; GCN-NEXT:    v_cvt_f16_f32_e32 v22, v22
; GCN-NEXT:    v_cvt_f16_f32_e32 v17, v17
; GCN-NEXT:    v_cvt_f16_f32_e32 v20, v20
; GCN-NEXT:    v_cvt_f16_f32_e32 v16, v16
; GCN-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; GCN-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GCN-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GCN-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; GCN-NEXT:    v_lshlrev_b32_e32 v10, 16, v10
; GCN-NEXT:    v_lshlrev_b32_e32 v12, 16, v12
; GCN-NEXT:    v_lshlrev_b32_e32 v14, 16, v14
; GCN-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; GCN-NEXT:    v_lshlrev_b32_e32 v27, 16, v27
; GCN-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; GCN-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; GCN-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; GCN-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; GCN-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; GCN-NEXT:    v_or_b32_e32 v2, v3, v2
; GCN-NEXT:    v_or_b32_e32 v3, v5, v4
; GCN-NEXT:    v_or_b32_e32 v4, v7, v6
; GCN-NEXT:    v_or_b32_e32 v5, v9, v8
; GCN-NEXT:    v_or_b32_e32 v6, v11, v10
; GCN-NEXT:    v_or_b32_e32 v7, v13, v12
; GCN-NEXT:    v_or_b32_e32 v8, v15, v14
; GCN-NEXT:    v_or_b32_e32 v9, v26, v24
; GCN-NEXT:    v_or_b32_e32 v10, v28, v27
; GCN-NEXT:    v_or_b32_e32 v11, v21, v29
; GCN-NEXT:    v_or_b32_e32 v12, v19, v25
; GCN-NEXT:    v_or_b32_e32 v13, v18, v23
; GCN-NEXT:    v_or_b32_e32 v14, v17, v22
; GCN-NEXT:    v_or_b32_e32 v15, v16, v20
; GCN-NEXT:  .LBB33_4: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v32f16_to_v8f64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB33_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v16, 0x200
; VI-NEXT:    v_add_f16_sdwa v17, v15, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v15, 0x200, v15
; VI-NEXT:    v_or_b32_e32 v15, v15, v17
; VI-NEXT:    v_add_f16_sdwa v17, v14, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v14, 0x200, v14
; VI-NEXT:    v_or_b32_e32 v14, v14, v17
; VI-NEXT:    v_add_f16_sdwa v17, v13, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v13, 0x200, v13
; VI-NEXT:    v_or_b32_e32 v13, v13, v17
; VI-NEXT:    v_add_f16_sdwa v17, v12, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v12, 0x200, v12
; VI-NEXT:    v_or_b32_e32 v12, v12, v17
; VI-NEXT:    v_add_f16_sdwa v17, v11, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v11, 0x200, v11
; VI-NEXT:    v_or_b32_e32 v11, v11, v17
; VI-NEXT:    v_add_f16_sdwa v17, v10, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v10, 0x200, v10
; VI-NEXT:    v_or_b32_e32 v10, v10, v17
; VI-NEXT:    v_add_f16_sdwa v17, v9, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v9, 0x200, v9
; VI-NEXT:    v_or_b32_e32 v9, v9, v17
; VI-NEXT:    v_add_f16_sdwa v17, v8, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v8, 0x200, v8
; VI-NEXT:    v_or_b32_e32 v8, v8, v17
; VI-NEXT:    v_add_f16_sdwa v17, v7, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v7, 0x200, v7
; VI-NEXT:    v_or_b32_e32 v7, v7, v17
; VI-NEXT:    v_add_f16_sdwa v17, v6, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v6, 0x200, v6
; VI-NEXT:    v_or_b32_e32 v6, v6, v17
; VI-NEXT:    v_add_f16_sdwa v17, v5, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v5, 0x200, v5
; VI-NEXT:    v_or_b32_e32 v5, v5, v17
; VI-NEXT:    v_add_f16_sdwa v17, v4, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v4, 0x200, v4
; VI-NEXT:    v_or_b32_e32 v4, v4, v17
; VI-NEXT:    v_add_f16_sdwa v17, v3, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v3, 0x200, v3
; VI-NEXT:    v_or_b32_e32 v3, v3, v17
; VI-NEXT:    v_add_f16_sdwa v17, v2, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, 0x200, v2
; VI-NEXT:    v_or_b32_e32 v2, v2, v17
; VI-NEXT:    v_add_f16_sdwa v17, v1, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v1, 0x200, v1
; VI-NEXT:    v_add_f16_sdwa v16, v0, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v0, 0x200, v0
; VI-NEXT:    v_or_b32_e32 v1, v1, v17
; VI-NEXT:    v_or_b32_e32 v0, v0, v16
; VI-NEXT:  .LBB33_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v32f16_to_v8f64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB33_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    s_movk_i32 s6, 0x200
; GFX9-NEXT:    v_pk_add_f16 v15, v15, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v14, v14, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v13, v13, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v12, v12, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v11, v11, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v10, v10, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v9, v9, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v8, v8, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v7, v7, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, v6, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v5, v5, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v4, v4, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v3, v3, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v2, v2, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v1, v1, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v0, v0, s6 op_sel_hi:[1,0]
; GFX9-NEXT:  .LBB33_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v32f16_to_v8f64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB33_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_pk_add_f16 v15, 0x200, v15 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v14, 0x200, v14 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v13, 0x200, v13 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v12, 0x200, v12 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v11, 0x200, v11 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v10, 0x200, v10 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v9, 0x200, v9 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v8, 0x200, v8 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v7, 0x200, v7 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v6, 0x200, v6 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v5, 0x200, v5 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v4, 0x200, v4 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v3, 0x200, v3 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v2, 0x200, v2 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v1, 0x200, v1 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v0, 0x200, v0 op_sel_hi:[0,1]
; GFX11-NEXT:  .LBB33_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <32 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <32 x half> %a1 to <8 x double>
  br label %end

cmp.false:
  %a3 = bitcast <32 x half> %a to <8 x double>
  br label %end

end:
  %phi = phi <8 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x double> %phi
}

define <32 x bfloat> @v_bitcast_v8f64_to_v32bf16(<8 x double> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v8f64_to_v32bf16:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GCN-NEXT:    ; implicit-def: $vgpr55
; GCN-NEXT:    ; implicit-def: $vgpr54
; GCN-NEXT:    ; implicit-def: $vgpr53
; GCN-NEXT:    ; implicit-def: $vgpr52
; GCN-NEXT:    ; implicit-def: $vgpr51
; GCN-NEXT:    ; implicit-def: $vgpr50
; GCN-NEXT:    ; implicit-def: $vgpr49
; GCN-NEXT:    ; implicit-def: $vgpr48
; GCN-NEXT:    ; implicit-def: $vgpr39
; GCN-NEXT:    ; implicit-def: $vgpr38
; GCN-NEXT:    ; implicit-def: $vgpr37
; GCN-NEXT:    ; implicit-def: $vgpr36
; GCN-NEXT:    ; implicit-def: $vgpr35
; GCN-NEXT:    ; implicit-def: $vgpr34
; GCN-NEXT:    ; implicit-def: $vgpr33
; GCN-NEXT:    ; implicit-def: $vgpr32
; GCN-NEXT:    ; implicit-def: $vgpr16
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr18
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr20
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr22
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr24
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr26
; GCN-NEXT:    ; implicit-def: $vgpr27
; GCN-NEXT:    ; implicit-def: $vgpr28
; GCN-NEXT:    ; implicit-def: $vgpr29
; GCN-NEXT:    ; implicit-def: $vgpr30
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB34_2
; GCN-NEXT:  ; %bb.1: ; %cmp.false
; GCN-NEXT:    v_and_b32_e32 v31, 0xffff0000, v15
; GCN-NEXT:    v_lshlrev_b32_e32 v30, 16, v15
; GCN-NEXT:    v_and_b32_e32 v29, 0xffff0000, v14
; GCN-NEXT:    v_lshlrev_b32_e32 v28, 16, v14
; GCN-NEXT:    v_and_b32_e32 v27, 0xffff0000, v13
; GCN-NEXT:    v_lshlrev_b32_e32 v26, 16, v13
; GCN-NEXT:    v_and_b32_e32 v25, 0xffff0000, v12
; GCN-NEXT:    v_lshlrev_b32_e32 v24, 16, v12
; GCN-NEXT:    v_and_b32_e32 v23, 0xffff0000, v11
; GCN-NEXT:    v_lshlrev_b32_e32 v22, 16, v11
; GCN-NEXT:    v_and_b32_e32 v21, 0xffff0000, v10
; GCN-NEXT:    v_lshlrev_b32_e32 v20, 16, v10
; GCN-NEXT:    v_and_b32_e32 v19, 0xffff0000, v9
; GCN-NEXT:    v_lshlrev_b32_e32 v18, 16, v9
; GCN-NEXT:    v_and_b32_e32 v17, 0xffff0000, v8
; GCN-NEXT:    v_lshlrev_b32_e32 v16, 16, v8
; GCN-NEXT:    v_and_b32_e32 v32, 0xffff0000, v7
; GCN-NEXT:    v_lshlrev_b32_e32 v33, 16, v7
; GCN-NEXT:    v_and_b32_e32 v34, 0xffff0000, v6
; GCN-NEXT:    v_lshlrev_b32_e32 v35, 16, v6
; GCN-NEXT:    v_and_b32_e32 v36, 0xffff0000, v5
; GCN-NEXT:    v_lshlrev_b32_e32 v37, 16, v5
; GCN-NEXT:    v_and_b32_e32 v38, 0xffff0000, v4
; GCN-NEXT:    v_lshlrev_b32_e32 v39, 16, v4
; GCN-NEXT:    v_and_b32_e32 v48, 0xffff0000, v3
; GCN-NEXT:    v_lshlrev_b32_e32 v49, 16, v3
; GCN-NEXT:    v_and_b32_e32 v50, 0xffff0000, v2
; GCN-NEXT:    v_lshlrev_b32_e32 v51, 16, v2
; GCN-NEXT:    v_and_b32_e32 v52, 0xffff0000, v1
; GCN-NEXT:    v_lshlrev_b32_e32 v53, 16, v1
; GCN-NEXT:    v_and_b32_e32 v54, 0xffff0000, v0
; GCN-NEXT:    v_lshlrev_b32_e32 v55, 16, v0
; GCN-NEXT:    ; implicit-def: $vgpr0
; GCN-NEXT:    ; implicit-def: $vgpr2
; GCN-NEXT:    ; implicit-def: $vgpr4
; GCN-NEXT:    ; implicit-def: $vgpr6
; GCN-NEXT:    ; implicit-def: $vgpr8
; GCN-NEXT:    ; implicit-def: $vgpr10
; GCN-NEXT:    ; implicit-def: $vgpr12
; GCN-NEXT:    ; implicit-def: $vgpr14
; GCN-NEXT:  .LBB34_2: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB34_4
; GCN-NEXT:  ; %bb.3: ; %cmp.true
; GCN-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GCN-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GCN-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GCN-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GCN-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GCN-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GCN-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GCN-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GCN-NEXT:    v_and_b32_e32 v31, 0xffff0000, v15
; GCN-NEXT:    v_lshlrev_b32_e32 v30, 16, v15
; GCN-NEXT:    v_and_b32_e32 v29, 0xffff0000, v14
; GCN-NEXT:    v_lshlrev_b32_e32 v28, 16, v14
; GCN-NEXT:    v_and_b32_e32 v27, 0xffff0000, v13
; GCN-NEXT:    v_lshlrev_b32_e32 v26, 16, v13
; GCN-NEXT:    v_and_b32_e32 v25, 0xffff0000, v12
; GCN-NEXT:    v_lshlrev_b32_e32 v24, 16, v12
; GCN-NEXT:    v_and_b32_e32 v23, 0xffff0000, v11
; GCN-NEXT:    v_lshlrev_b32_e32 v22, 16, v11
; GCN-NEXT:    v_and_b32_e32 v21, 0xffff0000, v10
; GCN-NEXT:    v_lshlrev_b32_e32 v20, 16, v10
; GCN-NEXT:    v_and_b32_e32 v19, 0xffff0000, v9
; GCN-NEXT:    v_lshlrev_b32_e32 v18, 16, v9
; GCN-NEXT:    v_and_b32_e32 v17, 0xffff0000, v8
; GCN-NEXT:    v_lshlrev_b32_e32 v16, 16, v8
; GCN-NEXT:    v_and_b32_e32 v32, 0xffff0000, v7
; GCN-NEXT:    v_lshlrev_b32_e32 v33, 16, v7
; GCN-NEXT:    v_and_b32_e32 v34, 0xffff0000, v6
; GCN-NEXT:    v_lshlrev_b32_e32 v35, 16, v6
; GCN-NEXT:    v_and_b32_e32 v36, 0xffff0000, v5
; GCN-NEXT:    v_lshlrev_b32_e32 v37, 16, v5
; GCN-NEXT:    v_and_b32_e32 v38, 0xffff0000, v4
; GCN-NEXT:    v_lshlrev_b32_e32 v39, 16, v4
; GCN-NEXT:    v_and_b32_e32 v48, 0xffff0000, v3
; GCN-NEXT:    v_lshlrev_b32_e32 v49, 16, v3
; GCN-NEXT:    v_and_b32_e32 v50, 0xffff0000, v2
; GCN-NEXT:    v_lshlrev_b32_e32 v51, 16, v2
; GCN-NEXT:    v_and_b32_e32 v52, 0xffff0000, v1
; GCN-NEXT:    v_lshlrev_b32_e32 v53, 16, v1
; GCN-NEXT:    v_and_b32_e32 v54, 0xffff0000, v0
; GCN-NEXT:    v_lshlrev_b32_e32 v55, 16, v0
; GCN-NEXT:  .LBB34_4: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    v_mov_b32_e32 v0, v55
; GCN-NEXT:    v_mov_b32_e32 v1, v54
; GCN-NEXT:    v_mov_b32_e32 v2, v53
; GCN-NEXT:    v_mov_b32_e32 v3, v52
; GCN-NEXT:    v_mov_b32_e32 v4, v51
; GCN-NEXT:    v_mov_b32_e32 v5, v50
; GCN-NEXT:    v_mov_b32_e32 v6, v49
; GCN-NEXT:    v_mov_b32_e32 v7, v48
; GCN-NEXT:    v_mov_b32_e32 v8, v39
; GCN-NEXT:    v_mov_b32_e32 v9, v38
; GCN-NEXT:    v_mov_b32_e32 v10, v37
; GCN-NEXT:    v_mov_b32_e32 v11, v36
; GCN-NEXT:    v_mov_b32_e32 v12, v35
; GCN-NEXT:    v_mov_b32_e32 v13, v34
; GCN-NEXT:    v_mov_b32_e32 v14, v33
; GCN-NEXT:    v_mov_b32_e32 v15, v32
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v8f64_to_v32bf16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB34_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; VI-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; VI-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; VI-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; VI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; VI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; VI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; VI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; VI-NEXT:  .LBB34_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v8f64_to_v32bf16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB34_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GFX9-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GFX9-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GFX9-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GFX9-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX9-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX9-NEXT:  .LBB34_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v8f64_to_v32bf16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB34_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GFX11-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GFX11-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GFX11-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GFX11-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX11-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX11-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX11-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX11-NEXT:  .LBB34_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <8 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <8 x double> %a1 to <32 x bfloat>
  br label %end

cmp.false:
  %a3 = bitcast <8 x double> %a to <32 x bfloat>
  br label %end

end:
  %phi = phi <32 x bfloat> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x bfloat> %phi
}

define <8 x double> @v_bitcast_v32bf16_to_v8f64(<32 x bfloat> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v32bf16_to_v8f64:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GCN-NEXT:    s_waitcnt expcnt(1)
; GCN-NEXT:    buffer_load_dword v46, off, s[0:3], s32
; GCN-NEXT:    s_waitcnt expcnt(0)
; GCN-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:4
; GCN-NEXT:    v_mul_f32_e32 v44, 1.0, v1
; GCN-NEXT:    v_mul_f32_e32 v45, 1.0, v0
; GCN-NEXT:    v_mul_f32_e32 v42, 1.0, v3
; GCN-NEXT:    v_mul_f32_e32 v43, 1.0, v2
; GCN-NEXT:    v_mul_f32_e32 v41, 1.0, v5
; GCN-NEXT:    v_mul_f32_e32 v51, 1.0, v4
; GCN-NEXT:    v_mul_f32_e32 v40, 1.0, v7
; GCN-NEXT:    v_mul_f32_e32 v49, 1.0, v6
; GCN-NEXT:    v_mul_f32_e32 v55, 1.0, v9
; GCN-NEXT:    v_mul_f32_e32 v39, 1.0, v8
; GCN-NEXT:    v_mul_f32_e32 v54, 1.0, v11
; GCN-NEXT:    v_mul_f32_e32 v37, 1.0, v10
; GCN-NEXT:    v_mul_f32_e32 v53, 1.0, v13
; GCN-NEXT:    v_mul_f32_e32 v36, 1.0, v12
; GCN-NEXT:    v_mul_f32_e32 v52, 1.0, v15
; GCN-NEXT:    v_mul_f32_e32 v34, 1.0, v14
; GCN-NEXT:    v_mul_f32_e32 v50, 1.0, v17
; GCN-NEXT:    v_mul_f32_e32 v33, 1.0, v16
; GCN-NEXT:    v_mul_f32_e32 v48, 1.0, v19
; GCN-NEXT:    v_mul_f32_e32 v32, 1.0, v18
; GCN-NEXT:    v_mul_f32_e32 v38, 1.0, v21
; GCN-NEXT:    v_mul_f32_e32 v31, 1.0, v20
; GCN-NEXT:    v_mul_f32_e32 v35, 1.0, v23
; GCN-NEXT:    v_mul_f32_e32 v21, 1.0, v22
; GCN-NEXT:    v_mul_f32_e32 v25, 1.0, v25
; GCN-NEXT:    v_mul_f32_e32 v19, 1.0, v24
; GCN-NEXT:    v_mul_f32_e32 v23, 1.0, v27
; GCN-NEXT:    v_mul_f32_e32 v18, 1.0, v26
; GCN-NEXT:    v_mul_f32_e32 v22, 1.0, v29
; GCN-NEXT:    v_mul_f32_e32 v17, 1.0, v28
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v47
; GCN-NEXT:    v_mul_f32_e32 v20, 1.0, v46
; GCN-NEXT:    v_mul_f32_e32 v16, 1.0, v30
; GCN-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB35_2
; GCN-NEXT:  ; %bb.1: ; %cmp.false
; GCN-NEXT:    v_lshrrev_b32_e32 v0, 16, v44
; GCN-NEXT:    v_lshrrev_b32_e32 v1, 16, v42
; GCN-NEXT:    v_alignbit_b32 v0, v0, v45, 16
; GCN-NEXT:    v_alignbit_b32 v1, v1, v43, 16
; GCN-NEXT:    v_lshrrev_b32_e32 v2, 16, v41
; GCN-NEXT:    v_lshrrev_b32_e32 v3, 16, v40
; GCN-NEXT:    v_lshrrev_b32_e32 v4, 16, v55
; GCN-NEXT:    v_lshrrev_b32_e32 v5, 16, v54
; GCN-NEXT:    v_lshrrev_b32_e32 v6, 16, v53
; GCN-NEXT:    v_lshrrev_b32_e32 v7, 16, v52
; GCN-NEXT:    v_lshrrev_b32_e32 v8, 16, v50
; GCN-NEXT:    v_lshrrev_b32_e32 v9, 16, v48
; GCN-NEXT:    v_lshrrev_b32_e32 v10, 16, v38
; GCN-NEXT:    v_lshrrev_b32_e32 v11, 16, v35
; GCN-NEXT:    v_lshrrev_b32_e32 v12, 16, v25
; GCN-NEXT:    v_lshrrev_b32_e32 v13, 16, v23
; GCN-NEXT:    v_lshrrev_b32_e32 v14, 16, v22
; GCN-NEXT:    v_lshrrev_b32_e32 v15, 16, v20
; GCN-NEXT:    v_alignbit_b32 v2, v2, v51, 16
; GCN-NEXT:    v_alignbit_b32 v3, v3, v49, 16
; GCN-NEXT:    v_alignbit_b32 v4, v4, v39, 16
; GCN-NEXT:    v_alignbit_b32 v5, v5, v37, 16
; GCN-NEXT:    v_alignbit_b32 v6, v6, v36, 16
; GCN-NEXT:    v_alignbit_b32 v7, v7, v34, 16
; GCN-NEXT:    v_alignbit_b32 v8, v8, v33, 16
; GCN-NEXT:    v_alignbit_b32 v9, v9, v32, 16
; GCN-NEXT:    v_alignbit_b32 v10, v10, v31, 16
; GCN-NEXT:    v_alignbit_b32 v11, v11, v21, 16
; GCN-NEXT:    v_alignbit_b32 v12, v12, v19, 16
; GCN-NEXT:    v_alignbit_b32 v13, v13, v18, 16
; GCN-NEXT:    v_alignbit_b32 v14, v14, v17, 16
; GCN-NEXT:    v_alignbit_b32 v15, v15, v16, 16
; GCN-NEXT:    ; implicit-def: $vgpr44
; GCN-NEXT:    ; implicit-def: $vgpr45
; GCN-NEXT:    ; implicit-def: $vgpr42
; GCN-NEXT:    ; implicit-def: $vgpr43
; GCN-NEXT:    ; implicit-def: $vgpr41
; GCN-NEXT:    ; implicit-def: $vgpr51
; GCN-NEXT:    ; implicit-def: $vgpr40
; GCN-NEXT:    ; implicit-def: $vgpr49
; GCN-NEXT:    ; implicit-def: $vgpr55
; GCN-NEXT:    ; implicit-def: $vgpr39
; GCN-NEXT:    ; implicit-def: $vgpr54
; GCN-NEXT:    ; implicit-def: $vgpr37
; GCN-NEXT:    ; implicit-def: $vgpr53
; GCN-NEXT:    ; implicit-def: $vgpr36
; GCN-NEXT:    ; implicit-def: $vgpr52
; GCN-NEXT:    ; implicit-def: $vgpr34
; GCN-NEXT:    ; implicit-def: $vgpr50
; GCN-NEXT:    ; implicit-def: $vgpr33
; GCN-NEXT:    ; implicit-def: $vgpr48
; GCN-NEXT:    ; implicit-def: $vgpr32
; GCN-NEXT:    ; implicit-def: $vgpr38
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    ; implicit-def: $vgpr35
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr18
; GCN-NEXT:    ; implicit-def: $vgpr22
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr20
; GCN-NEXT:    ; implicit-def: $vgpr16
; GCN-NEXT:  .LBB35_2: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB35_4
; GCN-NEXT:  ; %bb.3: ; %cmp.true
; GCN-NEXT:    v_and_b32_e32 v0, 0xffff0000, v45
; GCN-NEXT:    v_and_b32_e32 v1, 0xffff0000, v44
; GCN-NEXT:    v_and_b32_e32 v2, 0xffff0000, v43
; GCN-NEXT:    v_and_b32_e32 v3, 0xffff0000, v42
; GCN-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; GCN-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GCN-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GCN-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GCN-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GCN-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; GCN-NEXT:    v_alignbit_b32 v0, v1, v0, 16
; GCN-NEXT:    v_alignbit_b32 v1, v3, v2, 16
; GCN-NEXT:    v_and_b32_e32 v2, 0xffff0000, v51
; GCN-NEXT:    v_and_b32_e32 v3, 0xffff0000, v41
; GCN-NEXT:    v_and_b32_e32 v4, 0xffff0000, v49
; GCN-NEXT:    v_and_b32_e32 v5, 0xffff0000, v40
; GCN-NEXT:    v_and_b32_e32 v6, 0xffff0000, v39
; GCN-NEXT:    v_and_b32_e32 v7, 0xffff0000, v55
; GCN-NEXT:    v_and_b32_e32 v8, 0xffff0000, v37
; GCN-NEXT:    v_and_b32_e32 v9, 0xffff0000, v54
; GCN-NEXT:    v_and_b32_e32 v10, 0xffff0000, v36
; GCN-NEXT:    v_and_b32_e32 v11, 0xffff0000, v53
; GCN-NEXT:    v_and_b32_e32 v12, 0xffff0000, v34
; GCN-NEXT:    v_and_b32_e32 v13, 0xffff0000, v52
; GCN-NEXT:    v_and_b32_e32 v14, 0xffff0000, v33
; GCN-NEXT:    v_and_b32_e32 v15, 0xffff0000, v50
; GCN-NEXT:    v_and_b32_e32 v24, 0xffff0000, v32
; GCN-NEXT:    v_and_b32_e32 v26, 0xffff0000, v48
; GCN-NEXT:    v_and_b32_e32 v27, 0xffff0000, v31
; GCN-NEXT:    v_and_b32_e32 v28, 0xffff0000, v38
; GCN-NEXT:    v_and_b32_e32 v21, 0xffff0000, v21
; GCN-NEXT:    v_and_b32_e32 v29, 0xffff0000, v35
; GCN-NEXT:    v_and_b32_e32 v19, 0xffff0000, v19
; GCN-NEXT:    v_and_b32_e32 v25, 0xffff0000, v25
; GCN-NEXT:    v_and_b32_e32 v18, 0xffff0000, v18
; GCN-NEXT:    v_and_b32_e32 v23, 0xffff0000, v23
; GCN-NEXT:    v_and_b32_e32 v17, 0xffff0000, v17
; GCN-NEXT:    v_and_b32_e32 v22, 0xffff0000, v22
; GCN-NEXT:    v_and_b32_e32 v16, 0xffff0000, v16
; GCN-NEXT:    v_and_b32_e32 v20, 0xffff0000, v20
; GCN-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GCN-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GCN-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; GCN-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GCN-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GCN-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GCN-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GCN-NEXT:    v_add_f32_e32 v9, 0x40c00000, v9
; GCN-NEXT:    v_add_f32_e32 v10, 0x40c00000, v10
; GCN-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; GCN-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; GCN-NEXT:    v_add_f32_e32 v13, 0x40c00000, v13
; GCN-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; GCN-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; GCN-NEXT:    v_add_f32_e32 v24, 0x40c00000, v24
; GCN-NEXT:    v_add_f32_e32 v26, 0x40c00000, v26
; GCN-NEXT:    v_add_f32_e32 v27, 0x40c00000, v27
; GCN-NEXT:    v_add_f32_e32 v28, 0x40c00000, v28
; GCN-NEXT:    v_add_f32_e32 v21, 0x40c00000, v21
; GCN-NEXT:    v_add_f32_e32 v29, 0x40c00000, v29
; GCN-NEXT:    v_add_f32_e32 v19, 0x40c00000, v19
; GCN-NEXT:    v_add_f32_e32 v25, 0x40c00000, v25
; GCN-NEXT:    v_add_f32_e32 v18, 0x40c00000, v18
; GCN-NEXT:    v_add_f32_e32 v23, 0x40c00000, v23
; GCN-NEXT:    v_add_f32_e32 v17, 0x40c00000, v17
; GCN-NEXT:    v_add_f32_e32 v22, 0x40c00000, v22
; GCN-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GCN-NEXT:    v_add_f32_e32 v20, 0x40c00000, v20
; GCN-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; GCN-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; GCN-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; GCN-NEXT:    v_lshrrev_b32_e32 v9, 16, v9
; GCN-NEXT:    v_lshrrev_b32_e32 v11, 16, v11
; GCN-NEXT:    v_lshrrev_b32_e32 v13, 16, v13
; GCN-NEXT:    v_lshrrev_b32_e32 v15, 16, v15
; GCN-NEXT:    v_lshrrev_b32_e32 v26, 16, v26
; GCN-NEXT:    v_lshrrev_b32_e32 v28, 16, v28
; GCN-NEXT:    v_lshrrev_b32_e32 v29, 16, v29
; GCN-NEXT:    v_lshrrev_b32_e32 v25, 16, v25
; GCN-NEXT:    v_lshrrev_b32_e32 v23, 16, v23
; GCN-NEXT:    v_lshrrev_b32_e32 v22, 16, v22
; GCN-NEXT:    v_lshrrev_b32_e32 v20, 16, v20
; GCN-NEXT:    v_alignbit_b32 v2, v3, v2, 16
; GCN-NEXT:    v_alignbit_b32 v3, v5, v4, 16
; GCN-NEXT:    v_alignbit_b32 v4, v7, v6, 16
; GCN-NEXT:    v_alignbit_b32 v5, v9, v8, 16
; GCN-NEXT:    v_alignbit_b32 v6, v11, v10, 16
; GCN-NEXT:    v_alignbit_b32 v7, v13, v12, 16
; GCN-NEXT:    v_alignbit_b32 v8, v15, v14, 16
; GCN-NEXT:    v_alignbit_b32 v9, v26, v24, 16
; GCN-NEXT:    v_alignbit_b32 v10, v28, v27, 16
; GCN-NEXT:    v_alignbit_b32 v11, v29, v21, 16
; GCN-NEXT:    v_alignbit_b32 v12, v25, v19, 16
; GCN-NEXT:    v_alignbit_b32 v13, v23, v18, 16
; GCN-NEXT:    v_alignbit_b32 v14, v22, v17, 16
; GCN-NEXT:    v_alignbit_b32 v15, v20, v16, 16
; GCN-NEXT:  .LBB35_4: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v32bf16_to_v8f64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB35_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v15
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, 0x7fff, v17
; VI-NEXT:    v_and_b32_e32 v15, 0xffff0000, v15
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v15, 16, 1
; VI-NEXT:    s_movk_i32 s6, 0x7fff
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v15
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v15
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v15, v15
; VI-NEXT:    v_cndmask_b32_e32 v15, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v15, 16, v15
; VI-NEXT:    v_alignbit_b32 v15, v15, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v14
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v14, 0xffff0000, v14
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v14, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v14
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v14
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v14, v14
; VI-NEXT:    v_cndmask_b32_e32 v14, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v14, 16, v14
; VI-NEXT:    v_alignbit_b32 v14, v14, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v13
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v13, 0xffff0000, v13
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v13, 0x40c00000, v13
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v13, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v13
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v13
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v13, v13
; VI-NEXT:    v_cndmask_b32_e32 v13, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v13, 16, v13
; VI-NEXT:    v_alignbit_b32 v13, v13, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v12
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v12, 0xffff0000, v12
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v12, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v12
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v12
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v12, v12
; VI-NEXT:    v_cndmask_b32_e32 v12, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v12, 16, v12
; VI-NEXT:    v_alignbit_b32 v12, v12, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v11
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v11, 0xffff0000, v11
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v11, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v11
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v11
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v11, v11
; VI-NEXT:    v_cndmask_b32_e32 v11, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v11, 16, v11
; VI-NEXT:    v_alignbit_b32 v11, v11, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v10
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v10, 0xffff0000, v10
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v10, 0x40c00000, v10
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v10, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v10
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v10
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v10, v10
; VI-NEXT:    v_cndmask_b32_e32 v10, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v10, 16, v10
; VI-NEXT:    v_alignbit_b32 v10, v10, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v9
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v9, 0xffff0000, v9
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v9, 0x40c00000, v9
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v9, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v9
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v9
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v9, v9
; VI-NEXT:    v_cndmask_b32_e32 v9, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v9, 16, v9
; VI-NEXT:    v_alignbit_b32 v9, v9, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v8
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v8, 0xffff0000, v8
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v8
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_cndmask_b32_e32 v8, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v8, 16, v8
; VI-NEXT:    v_alignbit_b32 v8, v8, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v7
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v7, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v7
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v7
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; VI-NEXT:    v_cndmask_b32_e32 v7, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; VI-NEXT:    v_alignbit_b32 v7, v7, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v6
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v6, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v6
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v6
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; VI-NEXT:    v_cndmask_b32_e32 v6, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_alignbit_b32 v6, v6, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v5
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v5, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v5
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v5
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; VI-NEXT:    v_cndmask_b32_e32 v5, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_alignbit_b32 v5, v5, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v4
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v4, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v4
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v4
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; VI-NEXT:    v_cndmask_b32_e32 v4, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_alignbit_b32 v4, v4, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v3
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v3
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_alignbit_b32 v3, v3, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v2
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v2
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_alignbit_b32 v2, v2, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v1
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v1, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v1
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v1
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; VI-NEXT:    v_cndmask_b32_e32 v1, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_alignbit_b32 v1, v1, v16, 16
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v0
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v0, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v0
; VI-NEXT:    v_add_u32_e32 v17, vcc, 0x7fff, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v0
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; VI-NEXT:    v_cndmask_b32_e32 v0, v17, v18, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; VI-NEXT:    v_alignbit_b32 v0, v0, v16, 16
; VI-NEXT:  .LBB35_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v32bf16_to_v8f64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB35_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v15
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    s_movk_i32 s6, 0x7fff
; GFX9-NEXT:    v_and_b32_e32 v15, 0xffff0000, v15
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v15, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v15, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v15
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v15, v15
; GFX9-NEXT:    v_cndmask_b32_e32 v15, v17, v18, vcc
; GFX9-NEXT:    s_mov_b32 s7, 0x7060302
; GFX9-NEXT:    v_perm_b32 v15, v15, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v14
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v14, 0xffff0000, v14
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v14, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v14, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v14
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v14, v14
; GFX9-NEXT:    v_cndmask_b32_e32 v14, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v14, v14, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v13
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v13, 0xffff0000, v13
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v13, 0x40c00000, v13
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v13, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v13, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v13
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v13, v13
; GFX9-NEXT:    v_cndmask_b32_e32 v13, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v13, v13, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v12
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v12, 0xffff0000, v12
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v12, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v12, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v12
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v12, v12
; GFX9-NEXT:    v_cndmask_b32_e32 v12, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v12, v12, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v11
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v11, 0xffff0000, v11
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v11, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v11, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v11
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v11, v11
; GFX9-NEXT:    v_cndmask_b32_e32 v11, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v11, v11, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v10
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v10, 0xffff0000, v10
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v10, 0x40c00000, v10
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v10, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v10, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v10
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v10, v10
; GFX9-NEXT:    v_cndmask_b32_e32 v10, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v10, v10, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v9
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v9, 0xffff0000, v9
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v9, 0x40c00000, v9
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v9, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v9, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v9
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v9, v9
; GFX9-NEXT:    v_cndmask_b32_e32 v9, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v9, v9, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v8
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v8, 0xffff0000, v8
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v8, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v8, v8, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v7
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v7, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v7, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v7
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; GFX9-NEXT:    v_cndmask_b32_e32 v7, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v7, v7, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v6
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v6, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v6, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v6
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; GFX9-NEXT:    v_cndmask_b32_e32 v6, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v6, v6, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v5
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v5, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v5, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v5, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v5, v5, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v4
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v4, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v4, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v4
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; GFX9-NEXT:    v_cndmask_b32_e32 v4, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v4, v4, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v3
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v3, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v3, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v3
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; GFX9-NEXT:    v_cndmask_b32_e32 v3, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v3, v3, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v2, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v2, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v2, v2, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v1
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v1, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v1, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v1, v1, v16, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v0
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v0, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v0, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v0
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v0, v17, v18, vcc
; GFX9-NEXT:    v_perm_b32 v0, v0, v16, s7
; GFX9-NEXT:  .LBB35_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v32bf16_to_v8f64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB35_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_lshlrev_b32_e32 v17, 16, v14
; GFX11-NEXT:    v_lshlrev_b32_e32 v16, 16, v15
; GFX11-NEXT:    v_and_b32_e32 v14, 0xffff0000, v14
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_dual_add_f32 v17, 0x40c00000, v17 :: v_dual_add_f32 v16, 0x40c00000, v16
; GFX11-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_bfe_u32 v21, v17, 16, 1
; GFX11-NEXT:    v_bfe_u32 v18, v16, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v19, 0x400000, v16
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_bfe_u32 v23, v14, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v16, v16
; GFX11-NEXT:    v_add3_u32 v21, v21, v17, 0x7fff
; GFX11-NEXT:    v_add3_u32 v18, v18, v16, 0x7fff
; GFX11-NEXT:    v_cndmask_b32_e32 v16, v18, v19, vcc_lo
; GFX11-NEXT:    v_add3_u32 v19, v23, v14, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v15, 0xffff0000, v15
; GFX11-NEXT:    v_or_b32_e32 v18, 0x400000, v17
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; GFX11-NEXT:    v_bfe_u32 v20, v15, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v15
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v15, v15
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add3_u32 v20, v20, v15, 0x7fff
; GFX11-NEXT:    v_dual_cndmask_b32 v15, v20, v22 :: v_dual_lshlrev_b32 v20, 16, v13
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v17, v17
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_perm_b32 v15, v15, v16, 0x7060302
; GFX11-NEXT:    v_dual_cndmask_b32 v17, v21, v18 :: v_dual_add_f32 v18, 0x40c00000, v20
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_bfe_u32 v16, v18, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v18
; GFX11-NEXT:    v_add3_u32 v16, v16, v18, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v13, 0xffff0000, v13
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_add_f32_e32 v13, 0x40c00000, v13
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v14
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v14, v14
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v13
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_dual_cndmask_b32 v14, v19, v22 :: v_dual_lshlrev_b32 v19, 16, v12
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-NEXT:    v_perm_b32 v14, v14, v17, 0x7060302
; GFX11-NEXT:    v_bfe_u32 v17, v13, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_dual_add_f32 v19, 0x40c00000, v19 :: v_dual_cndmask_b32 v16, v16, v20
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v13, v13
; GFX11-NEXT:    v_add3_u32 v17, v17, v13, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_bfe_u32 v22, v19, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v19
; GFX11-NEXT:    v_cndmask_b32_e32 v13, v17, v21, vcc_lo
; GFX11-NEXT:    v_lshlrev_b32_e32 v21, 16, v11
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_add3_u32 v17, v22, v19, 0x7fff
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v19, v19
; GFX11-NEXT:    v_perm_b32 v13, v13, v16, 0x7060302
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_add_f32_e32 v19, 0x40c00000, v21
; GFX11-NEXT:    v_cndmask_b32_e32 v17, v17, v20, vcc_lo
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_bfe_u32 v16, v19, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v19
; GFX11-NEXT:    v_add3_u32 v16, v16, v19, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v11, 0xffff0000, v11
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v11
; GFX11-NEXT:    v_and_b32_e32 v12, 0xffff0000, v12
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; GFX11-NEXT:    v_bfe_u32 v18, v12, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v12
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v12, v12
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add3_u32 v18, v18, v12, 0x7fff
; GFX11-NEXT:    v_cndmask_b32_e32 v12, v18, v22, vcc_lo
; GFX11-NEXT:    v_lshlrev_b32_e32 v18, 16, v10
; GFX11-NEXT:    v_and_b32_e32 v10, 0xffff0000, v10
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_perm_b32 v12, v12, v17, 0x7060302
; GFX11-NEXT:    v_bfe_u32 v17, v11, 16, 1
; GFX11-NEXT:    v_add_f32_e32 v18, 0x40c00000, v18
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_add_f32_e32 v10, 0x40c00000, v10
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v19, v19
; GFX11-NEXT:    v_add3_u32 v17, v17, v11, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_bfe_u32 v22, v18, 16, 1
; GFX11-NEXT:    v_bfe_u32 v19, v10, 16, 1
; GFX11-NEXT:    v_cndmask_b32_e32 v16, v16, v20, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v11, v11
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v18
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_4) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_add3_u32 v19, v19, v10, 0x7fff
; GFX11-NEXT:    v_cndmask_b32_e32 v11, v17, v21, vcc_lo
; GFX11-NEXT:    v_add3_u32 v17, v22, v18, 0x7fff
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v10
; GFX11-NEXT:    v_perm_b32 v11, v11, v16, 0x7060302
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_cndmask_b32_e32 v17, v17, v20, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-NEXT:    v_dual_cndmask_b32 v10, v19, v22 :: v_dual_lshlrev_b32 v21, 16, v9
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_dual_add_f32 v18, 0x40c00000, v21 :: v_dual_lshlrev_b32 v19, 16, v8
; GFX11-NEXT:    v_and_b32_e32 v8, 0xffff0000, v8
; GFX11-NEXT:    v_perm_b32 v10, v10, v17, 0x7060302
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_3) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_bfe_u32 v16, v18, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v18
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-NEXT:    v_dual_add_f32 v19, 0x40c00000, v19 :: v_dual_add_f32 v8, 0x40c00000, v8
; GFX11-NEXT:    v_add3_u32 v16, v16, v18, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v9, 0xffff0000, v9
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_bfe_u32 v22, v19, 16, 1
; GFX11-NEXT:    v_bfe_u32 v18, v8, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_dual_cndmask_b32 v16, v16, v20 :: v_dual_add_f32 v9, 0x40c00000, v9
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v19
; GFX11-NEXT:    v_add3_u32 v18, v18, v8, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_bfe_u32 v17, v9, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v9
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-NEXT:    v_add3_u32 v17, v17, v9, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_3) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_cndmask_b32_e32 v9, v17, v21, vcc_lo
; GFX11-NEXT:    v_add3_u32 v17, v22, v19, 0x7fff
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v19, v19
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v8
; GFX11-NEXT:    v_perm_b32 v9, v9, v16, 0x7060302
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_cndmask_b32_e32 v17, v17, v20, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-NEXT:    v_cndmask_b32_e32 v8, v18, v22, vcc_lo
; GFX11-NEXT:    v_lshlrev_b32_e32 v18, 16, v6
; GFX11-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; GFX11-NEXT:    v_lshlrev_b32_e32 v21, 16, v7
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_perm_b32 v8, v8, v17, 0x7060302
; GFX11-NEXT:    v_add_f32_e32 v18, 0x40c00000, v18
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_dual_add_f32 v6, 0x40c00000, v6 :: v_dual_add_f32 v19, 0x40c00000, v21
; GFX11-NEXT:    v_bfe_u32 v22, v18, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_bfe_u32 v16, v19, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v19
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v19, v19
; GFX11-NEXT:    v_add3_u32 v16, v16, v19, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; GFX11-NEXT:    v_bfe_u32 v19, v6, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_dual_cndmask_b32 v16, v16, v20 :: v_dual_add_f32 v7, 0x40c00000, v7
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v18
; GFX11-NEXT:    v_add3_u32 v19, v19, v6, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_bfe_u32 v17, v7, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v7
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-NEXT:    v_add3_u32 v17, v17, v7, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_4) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_cndmask_b32_e32 v7, v17, v21, vcc_lo
; GFX11-NEXT:    v_add3_u32 v17, v22, v18, 0x7fff
; GFX11-NEXT:    v_lshlrev_b32_e32 v21, 16, v5
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v6
; GFX11-NEXT:    v_dual_add_f32 v18, 0x40c00000, v21 :: v_dual_cndmask_b32 v17, v17, v20
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_bfe_u32 v20, v18, 16, 1
; GFX11-NEXT:    v_dual_cndmask_b32 v6, v19, v22 :: v_dual_lshlrev_b32 v19, 16, v4
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; GFX11-NEXT:    v_perm_b32 v7, v7, v16, 0x7060302
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_4) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_perm_b32 v6, v6, v17, 0x7060302
; GFX11-NEXT:    v_add_f32_e32 v17, 0x40c00000, v19
; GFX11-NEXT:    v_add3_u32 v19, v20, v18, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v18
; GFX11-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; GFX11-NEXT:    v_bfe_u32 v22, v17, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_4) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_cndmask_b32_e32 v18, v19, v20, vcc_lo
; GFX11-NEXT:    v_or_b32_e32 v19, 0x400000, v17
; GFX11-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; GFX11-NEXT:    v_lshlrev_b32_e32 v20, 16, v3
; GFX11-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; GFX11-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_bfe_u32 v16, v5, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v5
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-NEXT:    v_add3_u32 v16, v16, v5, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_cndmask_b32_e32 v5, v16, v21, vcc_lo
; GFX11-NEXT:    v_add3_u32 v16, v22, v17, 0x7fff
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v17, v17
; GFX11-NEXT:    v_perm_b32 v5, v5, v18, 0x7060302
; GFX11-NEXT:    v_bfe_u32 v18, v4, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_2) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_cndmask_b32_e32 v16, v16, v19, vcc_lo
; GFX11-NEXT:    v_or_b32_e32 v19, 0x400000, v4
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-NEXT:    v_add3_u32 v18, v18, v4, 0x7fff
; GFX11-NEXT:    v_dual_add_f32 v17, 0x40c00000, v20 :: v_dual_lshlrev_b32 v20, 16, v2
; GFX11-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_cndmask_b32_e32 v4, v18, v19, vcc_lo
; GFX11-NEXT:    v_bfe_u32 v21, v17, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-NEXT:    v_add_f32_e32 v18, 0x40c00000, v20
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v17
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v17, v17
; GFX11-NEXT:    v_perm_b32 v4, v4, v16, 0x7060302
; GFX11-NEXT:    v_add3_u32 v19, v21, v17, 0x7fff
; GFX11-NEXT:    v_bfe_u32 v21, v3, 16, 1
; GFX11-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; GFX11-NEXT:    v_bfe_u32 v22, v18, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v23, 0x400000, v18
; GFX11-NEXT:    v_cndmask_b32_e32 v17, v19, v20, vcc_lo
; GFX11-NEXT:    v_add3_u32 v19, v21, v3, 0x7fff
; GFX11-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v3
; GFX11-NEXT:    v_add3_u32 v21, v22, v18, 0x7fff
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-NEXT:    v_lshlrev_b32_e32 v22, 16, v1
; GFX11-NEXT:    v_bfe_u32 v24, v2, 16, 1
; GFX11-NEXT:    v_cndmask_b32_e32 v3, v19, v20, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_add_f32_e32 v19, 0x40c00000, v22
; GFX11-NEXT:    v_add3_u32 v20, v24, v2, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_4) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_perm_b32 v3, v3, v17, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v18, v21, v23, vcc_lo
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v2
; GFX11-NEXT:    v_bfe_u32 v22, v19, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-NEXT:    v_dual_cndmask_b32 v2, v20, v21 :: v_dual_lshlrev_b32 v23, 16, v0
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-NEXT:    v_add3_u32 v21, v22, v19, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v19
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v19, v19
; GFX11-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX11-NEXT:    v_add_f32_e32 v20, 0x40c00000, v23
; GFX11-NEXT:    v_perm_b32 v2, v2, v18, 0x7060302
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_dual_cndmask_b32 v19, v21, v22 :: v_dual_add_f32 v0, 0x40c00000, v0
; GFX11-NEXT:    v_bfe_u32 v24, v20, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v25, 0x400000, v20
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_bfe_u32 v21, v0, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v26, 0x400000, v0
; GFX11-NEXT:    v_add3_u32 v24, v24, v20, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add3_u32 v21, v21, v0, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; GFX11-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_bfe_u32 v23, v1, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-NEXT:    v_add3_u32 v22, v23, v1, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v23, 0x400000, v1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-NEXT:    v_cndmask_b32_e32 v1, v22, v23, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v20, v20
; GFX11-NEXT:    v_perm_b32 v1, v1, v19, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v20, v24, v25, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-NEXT:    v_cndmask_b32_e32 v0, v21, v26, vcc_lo
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-NEXT:    v_perm_b32 v0, v0, v20, 0x7060302
; GFX11-NEXT:  .LBB35_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <32 x bfloat> %a, splat (bfloat 0xR40C0)
  %a2 = bitcast <32 x bfloat> %a1 to <8 x double>
  br label %end

cmp.false:
  %a3 = bitcast <32 x bfloat> %a to <8 x double>
  br label %end

end:
  %phi = phi <8 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x double> %phi
}

define <32 x half> @v_bitcast_v32i16_to_v32f16(<32 x i16> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v32i16_to_v32f16:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:68 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:64 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:60 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:56 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:52 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:48 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:44 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:40 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v59, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v60, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v61, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v62, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v63, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GCN-NEXT:    s_waitcnt expcnt(1)
; GCN-NEXT:    v_mov_b32_e32 v62, v30
; GCN-NEXT:    v_mov_b32_e32 v61, v29
; GCN-NEXT:    v_mov_b32_e32 v60, v28
; GCN-NEXT:    v_mov_b32_e32 v59, v27
; GCN-NEXT:    v_mov_b32_e32 v58, v26
; GCN-NEXT:    v_mov_b32_e32 v57, v25
; GCN-NEXT:    v_mov_b32_e32 v56, v24
; GCN-NEXT:    v_mov_b32_e32 v47, v23
; GCN-NEXT:    v_mov_b32_e32 v46, v22
; GCN-NEXT:    v_mov_b32_e32 v45, v21
; GCN-NEXT:    v_mov_b32_e32 v44, v20
; GCN-NEXT:    v_mov_b32_e32 v43, v19
; GCN-NEXT:    v_mov_b32_e32 v42, v18
; GCN-NEXT:    v_mov_b32_e32 v41, v17
; GCN-NEXT:    v_mov_b32_e32 v40, v16
; GCN-NEXT:    v_mov_b32_e32 v55, v15
; GCN-NEXT:    v_mov_b32_e32 v54, v14
; GCN-NEXT:    v_mov_b32_e32 v53, v13
; GCN-NEXT:    v_mov_b32_e32 v52, v12
; GCN-NEXT:    v_mov_b32_e32 v51, v11
; GCN-NEXT:    v_mov_b32_e32 v50, v10
; GCN-NEXT:    v_mov_b32_e32 v49, v9
; GCN-NEXT:    v_mov_b32_e32 v48, v8
; GCN-NEXT:    v_mov_b32_e32 v39, v7
; GCN-NEXT:    v_mov_b32_e32 v38, v6
; GCN-NEXT:    v_mov_b32_e32 v37, v5
; GCN-NEXT:    v_mov_b32_e32 v36, v4
; GCN-NEXT:    v_mov_b32_e32 v35, v3
; GCN-NEXT:    v_mov_b32_e32 v34, v2
; GCN-NEXT:    v_mov_b32_e32 v33, v1
; GCN-NEXT:    v_mov_b32_e32 v32, v0
; GCN-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:4
; GCN-NEXT:    s_waitcnt expcnt(0)
; GCN-NEXT:    buffer_load_dword v63, off, s[0:3], s32
; GCN-NEXT:    s_waitcnt vmcnt(1)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v0
; GCN-NEXT:    ; implicit-def: $vgpr0
; GCN-NEXT:    ; implicit-def: $vgpr1
; GCN-NEXT:    ; implicit-def: $vgpr2
; GCN-NEXT:    ; implicit-def: $vgpr3
; GCN-NEXT:    ; implicit-def: $vgpr4
; GCN-NEXT:    ; implicit-def: $vgpr5
; GCN-NEXT:    ; implicit-def: $vgpr6
; GCN-NEXT:    ; implicit-def: $vgpr7
; GCN-NEXT:    ; implicit-def: $vgpr8
; GCN-NEXT:    ; implicit-def: $vgpr9
; GCN-NEXT:    ; implicit-def: $vgpr10
; GCN-NEXT:    ; implicit-def: $vgpr11
; GCN-NEXT:    ; implicit-def: $vgpr12
; GCN-NEXT:    ; implicit-def: $vgpr13
; GCN-NEXT:    ; implicit-def: $vgpr14
; GCN-NEXT:    ; implicit-def: $vgpr15
; GCN-NEXT:    ; implicit-def: $vgpr16
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr18
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr20
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr22
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr24
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr26
; GCN-NEXT:    ; implicit-def: $vgpr27
; GCN-NEXT:    ; implicit-def: $vgpr28
; GCN-NEXT:    ; implicit-def: $vgpr29
; GCN-NEXT:    ; implicit-def: $vgpr30
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB36_2
; GCN-NEXT:  ; %bb.1: ; %cmp.false
; GCN-NEXT:    v_cvt_f32_f16_e32 v0, v32
; GCN-NEXT:    v_cvt_f32_f16_e32 v1, v33
; GCN-NEXT:    v_cvt_f32_f16_e32 v2, v34
; GCN-NEXT:    v_cvt_f32_f16_e32 v3, v35
; GCN-NEXT:    v_cvt_f32_f16_e32 v4, v36
; GCN-NEXT:    v_cvt_f32_f16_e32 v5, v37
; GCN-NEXT:    v_cvt_f32_f16_e32 v6, v38
; GCN-NEXT:    v_cvt_f32_f16_e32 v7, v39
; GCN-NEXT:    v_cvt_f32_f16_e32 v8, v48
; GCN-NEXT:    v_cvt_f32_f16_e32 v9, v49
; GCN-NEXT:    v_cvt_f32_f16_e32 v10, v50
; GCN-NEXT:    v_cvt_f32_f16_e32 v11, v51
; GCN-NEXT:    v_cvt_f32_f16_e32 v12, v52
; GCN-NEXT:    v_cvt_f32_f16_e32 v13, v53
; GCN-NEXT:    v_cvt_f32_f16_e32 v14, v54
; GCN-NEXT:    v_cvt_f32_f16_e32 v15, v55
; GCN-NEXT:    v_cvt_f32_f16_e32 v16, v40
; GCN-NEXT:    v_cvt_f32_f16_e32 v17, v41
; GCN-NEXT:    v_cvt_f32_f16_e32 v18, v42
; GCN-NEXT:    v_cvt_f32_f16_e32 v19, v43
; GCN-NEXT:    v_cvt_f32_f16_e32 v20, v44
; GCN-NEXT:    v_cvt_f32_f16_e32 v21, v45
; GCN-NEXT:    v_cvt_f32_f16_e32 v22, v46
; GCN-NEXT:    v_cvt_f32_f16_e32 v23, v47
; GCN-NEXT:    v_cvt_f32_f16_e32 v24, v56
; GCN-NEXT:    v_cvt_f32_f16_e32 v25, v57
; GCN-NEXT:    v_cvt_f32_f16_e32 v26, v58
; GCN-NEXT:    v_cvt_f32_f16_e32 v27, v59
; GCN-NEXT:    v_cvt_f32_f16_e32 v28, v60
; GCN-NEXT:    v_cvt_f32_f16_e32 v29, v61
; GCN-NEXT:    v_cvt_f32_f16_e32 v30, v62
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    v_cvt_f32_f16_e32 v31, v63
; GCN-NEXT:    ; implicit-def: $vgpr32
; GCN-NEXT:    ; implicit-def: $vgpr33
; GCN-NEXT:    ; implicit-def: $vgpr34
; GCN-NEXT:    ; implicit-def: $vgpr35
; GCN-NEXT:    ; implicit-def: $vgpr36
; GCN-NEXT:    ; implicit-def: $vgpr37
; GCN-NEXT:    ; implicit-def: $vgpr38
; GCN-NEXT:    ; implicit-def: $vgpr39
; GCN-NEXT:    ; implicit-def: $vgpr48
; GCN-NEXT:    ; implicit-def: $vgpr49
; GCN-NEXT:    ; implicit-def: $vgpr50
; GCN-NEXT:    ; implicit-def: $vgpr51
; GCN-NEXT:    ; implicit-def: $vgpr52
; GCN-NEXT:    ; implicit-def: $vgpr53
; GCN-NEXT:    ; implicit-def: $vgpr54
; GCN-NEXT:    ; implicit-def: $vgpr55
; GCN-NEXT:    ; implicit-def: $vgpr40
; GCN-NEXT:    ; implicit-def: $vgpr41
; GCN-NEXT:    ; implicit-def: $vgpr42
; GCN-NEXT:    ; implicit-def: $vgpr43
; GCN-NEXT:    ; implicit-def: $vgpr44
; GCN-NEXT:    ; implicit-def: $vgpr45
; GCN-NEXT:    ; implicit-def: $vgpr46
; GCN-NEXT:    ; implicit-def: $vgpr47
; GCN-NEXT:    ; implicit-def: $vgpr56
; GCN-NEXT:    ; implicit-def: $vgpr57
; GCN-NEXT:    ; implicit-def: $vgpr58
; GCN-NEXT:    ; implicit-def: $vgpr59
; GCN-NEXT:    ; implicit-def: $vgpr60
; GCN-NEXT:    ; implicit-def: $vgpr61
; GCN-NEXT:    ; implicit-def: $vgpr62
; GCN-NEXT:    ; implicit-def: $vgpr63
; GCN-NEXT:  .LBB36_2: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB36_4
; GCN-NEXT:  ; %bb.3: ; %cmp.true
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    v_add_i32_e32 v31, vcc, 3, v63
; GCN-NEXT:    v_add_i32_e32 v30, vcc, 3, v62
; GCN-NEXT:    v_add_i32_e32 v29, vcc, 3, v61
; GCN-NEXT:    v_add_i32_e32 v28, vcc, 3, v60
; GCN-NEXT:    v_add_i32_e32 v27, vcc, 3, v59
; GCN-NEXT:    v_add_i32_e32 v26, vcc, 3, v58
; GCN-NEXT:    v_add_i32_e32 v25, vcc, 3, v57
; GCN-NEXT:    v_add_i32_e32 v24, vcc, 3, v56
; GCN-NEXT:    v_add_i32_e32 v23, vcc, 3, v47
; GCN-NEXT:    v_add_i32_e32 v22, vcc, 3, v46
; GCN-NEXT:    v_add_i32_e32 v21, vcc, 3, v45
; GCN-NEXT:    v_add_i32_e32 v20, vcc, 3, v44
; GCN-NEXT:    v_add_i32_e32 v19, vcc, 3, v43
; GCN-NEXT:    v_add_i32_e32 v18, vcc, 3, v42
; GCN-NEXT:    v_add_i32_e32 v17, vcc, 3, v41
; GCN-NEXT:    v_add_i32_e32 v16, vcc, 3, v40
; GCN-NEXT:    v_add_i32_e32 v15, vcc, 3, v55
; GCN-NEXT:    v_add_i32_e32 v14, vcc, 3, v54
; GCN-NEXT:    v_add_i32_e32 v13, vcc, 3, v53
; GCN-NEXT:    v_add_i32_e32 v12, vcc, 3, v52
; GCN-NEXT:    v_add_i32_e32 v11, vcc, 3, v51
; GCN-NEXT:    v_add_i32_e32 v10, vcc, 3, v50
; GCN-NEXT:    v_add_i32_e32 v9, vcc, 3, v49
; GCN-NEXT:    v_add_i32_e32 v8, vcc, 3, v48
; GCN-NEXT:    v_add_i32_e32 v7, vcc, 3, v39
; GCN-NEXT:    v_add_i32_e32 v6, vcc, 3, v38
; GCN-NEXT:    v_add_i32_e32 v5, vcc, 3, v37
; GCN-NEXT:    v_add_i32_e32 v4, vcc, 3, v36
; GCN-NEXT:    v_add_i32_e32 v3, vcc, 3, v35
; GCN-NEXT:    v_add_i32_e32 v2, vcc, 3, v34
; GCN-NEXT:    v_add_i32_e32 v1, vcc, 3, v33
; GCN-NEXT:    v_add_i32_e32 v0, vcc, 3, v32
; GCN-NEXT:    v_cvt_f32_f16_e32 v0, v0
; GCN-NEXT:    v_cvt_f32_f16_e32 v1, v1
; GCN-NEXT:    v_cvt_f32_f16_e32 v2, v2
; GCN-NEXT:    v_cvt_f32_f16_e32 v3, v3
; GCN-NEXT:    v_cvt_f32_f16_e32 v4, v4
; GCN-NEXT:    v_cvt_f32_f16_e32 v5, v5
; GCN-NEXT:    v_cvt_f32_f16_e32 v6, v6
; GCN-NEXT:    v_cvt_f32_f16_e32 v7, v7
; GCN-NEXT:    v_cvt_f32_f16_e32 v8, v8
; GCN-NEXT:    v_cvt_f32_f16_e32 v9, v9
; GCN-NEXT:    v_cvt_f32_f16_e32 v10, v10
; GCN-NEXT:    v_cvt_f32_f16_e32 v11, v11
; GCN-NEXT:    v_cvt_f32_f16_e32 v12, v12
; GCN-NEXT:    v_cvt_f32_f16_e32 v13, v13
; GCN-NEXT:    v_cvt_f32_f16_e32 v14, v14
; GCN-NEXT:    v_cvt_f32_f16_e32 v15, v15
; GCN-NEXT:    v_cvt_f32_f16_e32 v16, v16
; GCN-NEXT:    v_cvt_f32_f16_e32 v17, v17
; GCN-NEXT:    v_cvt_f32_f16_e32 v18, v18
; GCN-NEXT:    v_cvt_f32_f16_e32 v19, v19
; GCN-NEXT:    v_cvt_f32_f16_e32 v20, v20
; GCN-NEXT:    v_cvt_f32_f16_e32 v21, v21
; GCN-NEXT:    v_cvt_f32_f16_e32 v22, v22
; GCN-NEXT:    v_cvt_f32_f16_e32 v23, v23
; GCN-NEXT:    v_cvt_f32_f16_e32 v24, v24
; GCN-NEXT:    v_cvt_f32_f16_e32 v25, v25
; GCN-NEXT:    v_cvt_f32_f16_e32 v26, v26
; GCN-NEXT:    v_cvt_f32_f16_e32 v27, v27
; GCN-NEXT:    v_cvt_f32_f16_e32 v28, v28
; GCN-NEXT:    v_cvt_f32_f16_e32 v29, v29
; GCN-NEXT:    v_cvt_f32_f16_e32 v30, v30
; GCN-NEXT:    v_cvt_f32_f16_e32 v31, v31
; GCN-NEXT:  .LBB36_4: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    buffer_load_dword v63, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v62, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v61, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v60, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v57, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:40 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:44 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:48 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:52 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:56 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:60 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v32i16_to_v32f16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB36_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v16, 3
; VI-NEXT:    v_add_u16_sdwa v19, v15, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v15, 3, v15
; VI-NEXT:    v_or_b32_e32 v15, v15, v19
; VI-NEXT:    v_add_u16_sdwa v19, v14, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v14, 3, v14
; VI-NEXT:    v_or_b32_e32 v14, v14, v19
; VI-NEXT:    v_add_u16_sdwa v19, v13, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v13, 3, v13
; VI-NEXT:    v_or_b32_e32 v13, v13, v19
; VI-NEXT:    v_add_u16_sdwa v19, v12, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v12, 3, v12
; VI-NEXT:    v_or_b32_e32 v12, v12, v19
; VI-NEXT:    v_add_u16_sdwa v19, v11, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v11, 3, v11
; VI-NEXT:    v_or_b32_e32 v11, v11, v19
; VI-NEXT:    v_add_u16_sdwa v19, v10, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v10, 3, v10
; VI-NEXT:    v_or_b32_e32 v10, v10, v19
; VI-NEXT:    v_add_u16_sdwa v19, v9, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v9, 3, v9
; VI-NEXT:    v_or_b32_e32 v9, v9, v19
; VI-NEXT:    v_add_u16_sdwa v19, v8, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v8, 3, v8
; VI-NEXT:    v_or_b32_e32 v8, v8, v19
; VI-NEXT:    v_add_u16_sdwa v19, v7, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v7, 3, v7
; VI-NEXT:    v_or_b32_e32 v7, v7, v19
; VI-NEXT:    v_add_u16_sdwa v19, v6, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v6, 3, v6
; VI-NEXT:    v_or_b32_e32 v6, v6, v19
; VI-NEXT:    v_add_u16_sdwa v19, v5, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v5, 3, v5
; VI-NEXT:    v_or_b32_e32 v5, v5, v19
; VI-NEXT:    v_add_u16_sdwa v19, v4, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v4, 3, v4
; VI-NEXT:    v_add_u16_sdwa v17, v0, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_sdwa v18, v1, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v4, v4, v19
; VI-NEXT:    v_add_u16_sdwa v19, v2, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_sdwa v16, v3, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v3, 3, v3
; VI-NEXT:    v_add_u16_e32 v2, 3, v2
; VI-NEXT:    v_add_u16_e32 v1, 3, v1
; VI-NEXT:    v_add_u16_e32 v0, 3, v0
; VI-NEXT:    v_or_b32_e32 v3, v3, v16
; VI-NEXT:    v_or_b32_e32 v2, v2, v19
; VI-NEXT:    v_or_b32_e32 v1, v1, v18
; VI-NEXT:    v_or_b32_e32 v0, v0, v17
; VI-NEXT:  .LBB36_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v32i16_to_v32f16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB36_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_pk_add_u16 v15, v15, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v14, v14, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v13, v13, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v12, v12, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v9, v9, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v8, v8, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX9-NEXT:  .LBB36_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v32i16_to_v32f16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB36_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_pk_add_u16 v15, v15, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v14, v14, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v13, v13, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v12, v12, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v9, v9, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v8, v8, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX11-NEXT:  .LBB36_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <32 x i16> %a, splat (i16 3)
  %a2 = bitcast <32 x i16> %a1 to <32 x half>
  br label %end

cmp.false:
  %a3 = bitcast <32 x i16> %a to <32 x half>
  br label %end

end:
  %phi = phi <32 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x half> %phi
}

define <32 x i16> @v_bitcast_v32f16_to_v32i16(<32 x half> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v32f16_to_v32i16:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    buffer_load_dword v31, off, s[0:3], s32 offset:4
; GCN-NEXT:    buffer_load_dword v32, off, s[0:3], s32
; GCN-NEXT:    s_waitcnt vmcnt(1)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v31
; GCN-NEXT:    v_cvt_f16_f32_e32 v0, v0
; GCN-NEXT:    v_cvt_f16_f32_e32 v1, v1
; GCN-NEXT:    v_cvt_f16_f32_e32 v2, v2
; GCN-NEXT:    v_cvt_f16_f32_e32 v3, v3
; GCN-NEXT:    v_cvt_f16_f32_e32 v4, v4
; GCN-NEXT:    v_cvt_f16_f32_e32 v5, v5
; GCN-NEXT:    v_cvt_f16_f32_e32 v6, v6
; GCN-NEXT:    v_cvt_f16_f32_e32 v7, v7
; GCN-NEXT:    v_cvt_f16_f32_e32 v8, v8
; GCN-NEXT:    v_cvt_f16_f32_e32 v9, v9
; GCN-NEXT:    v_cvt_f16_f32_e32 v10, v10
; GCN-NEXT:    v_cvt_f16_f32_e32 v11, v11
; GCN-NEXT:    v_cvt_f16_f32_e32 v12, v12
; GCN-NEXT:    v_cvt_f16_f32_e32 v13, v13
; GCN-NEXT:    v_cvt_f16_f32_e32 v14, v14
; GCN-NEXT:    v_cvt_f16_f32_e32 v15, v15
; GCN-NEXT:    v_cvt_f16_f32_e32 v16, v16
; GCN-NEXT:    v_cvt_f16_f32_e32 v17, v17
; GCN-NEXT:    v_cvt_f16_f32_e32 v18, v18
; GCN-NEXT:    v_cvt_f16_f32_e32 v19, v19
; GCN-NEXT:    v_cvt_f16_f32_e32 v20, v20
; GCN-NEXT:    v_cvt_f16_f32_e32 v21, v21
; GCN-NEXT:    v_cvt_f16_f32_e32 v22, v22
; GCN-NEXT:    v_cvt_f16_f32_e32 v23, v23
; GCN-NEXT:    v_cvt_f16_f32_e32 v24, v24
; GCN-NEXT:    v_cvt_f16_f32_e32 v25, v25
; GCN-NEXT:    v_cvt_f16_f32_e32 v26, v26
; GCN-NEXT:    v_cvt_f16_f32_e32 v27, v27
; GCN-NEXT:    v_cvt_f16_f32_e32 v28, v28
; GCN-NEXT:    v_cvt_f16_f32_e32 v29, v29
; GCN-NEXT:    v_cvt_f16_f32_e32 v30, v30
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    v_cvt_f16_f32_e32 v31, v32
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB37_2
; GCN-NEXT:  ; %bb.1: ; %cmp.true
; GCN-NEXT:    v_cvt_f32_f16_e32 v31, v31
; GCN-NEXT:    v_cvt_f32_f16_e32 v30, v30
; GCN-NEXT:    v_add_f32_e32 v31, 0x38000000, v31
; GCN-NEXT:    v_add_f32_e32 v30, 0x38000000, v30
; GCN-NEXT:    v_cvt_f16_f32_e32 v31, v31
; GCN-NEXT:    v_cvt_f16_f32_e32 v30, v30
; GCN-NEXT:    v_lshlrev_b32_e32 v32, 16, v31
; GCN-NEXT:    v_or_b32_e32 v30, v30, v32
; GCN-NEXT:    v_cvt_f32_f16_e32 v27, v27
; GCN-NEXT:    v_cvt_f32_f16_e32 v26, v26
; GCN-NEXT:    v_add_f32_e32 v27, 0x38000000, v27
; GCN-NEXT:    v_add_f32_e32 v26, 0x38000000, v26
; GCN-NEXT:    v_cvt_f16_f32_e32 v27, v27
; GCN-NEXT:    v_cvt_f16_f32_e32 v26, v26
; GCN-NEXT:    v_lshlrev_b32_e32 v32, 16, v27
; GCN-NEXT:    v_or_b32_e32 v26, v26, v32
; GCN-NEXT:    v_cvt_f32_f16_e32 v23, v23
; GCN-NEXT:    v_cvt_f32_f16_e32 v22, v22
; GCN-NEXT:    v_add_f32_e32 v23, 0x38000000, v23
; GCN-NEXT:    v_add_f32_e32 v22, 0x38000000, v22
; GCN-NEXT:    v_cvt_f16_f32_e32 v23, v23
; GCN-NEXT:    v_cvt_f16_f32_e32 v22, v22
; GCN-NEXT:    v_lshlrev_b32_e32 v32, 16, v23
; GCN-NEXT:    v_or_b32_e32 v22, v22, v32
; GCN-NEXT:    v_cvt_f32_f16_e32 v19, v19
; GCN-NEXT:    v_cvt_f32_f16_e32 v18, v18
; GCN-NEXT:    v_add_f32_e32 v19, 0x38000000, v19
; GCN-NEXT:    v_add_f32_e32 v18, 0x38000000, v18
; GCN-NEXT:    v_cvt_f16_f32_e32 v19, v19
; GCN-NEXT:    v_cvt_f16_f32_e32 v18, v18
; GCN-NEXT:    v_lshlrev_b32_e32 v32, 16, v19
; GCN-NEXT:    v_or_b32_e32 v18, v18, v32
; GCN-NEXT:    v_cvt_f32_f16_e32 v15, v15
; GCN-NEXT:    v_cvt_f32_f16_e32 v14, v14
; GCN-NEXT:    v_add_f32_e32 v15, 0x38000000, v15
; GCN-NEXT:    v_add_f32_e32 v14, 0x38000000, v14
; GCN-NEXT:    v_cvt_f16_f32_e32 v15, v15
; GCN-NEXT:    v_cvt_f16_f32_e32 v14, v14
; GCN-NEXT:    v_lshlrev_b32_e32 v32, 16, v15
; GCN-NEXT:    v_or_b32_e32 v14, v14, v32
; GCN-NEXT:    v_cvt_f32_f16_e32 v11, v11
; GCN-NEXT:    v_cvt_f32_f16_e32 v10, v10
; GCN-NEXT:    v_add_f32_e32 v11, 0x38000000, v11
; GCN-NEXT:    v_add_f32_e32 v10, 0x38000000, v10
; GCN-NEXT:    v_cvt_f16_f32_e32 v11, v11
; GCN-NEXT:    v_cvt_f16_f32_e32 v10, v10
; GCN-NEXT:    v_lshlrev_b32_e32 v32, 16, v11
; GCN-NEXT:    v_or_b32_e32 v10, v10, v32
; GCN-NEXT:    v_cvt_f32_f16_e32 v7, v7
; GCN-NEXT:    v_cvt_f32_f16_e32 v6, v6
; GCN-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; GCN-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; GCN-NEXT:    v_cvt_f16_f32_e32 v7, v7
; GCN-NEXT:    v_cvt_f16_f32_e32 v6, v6
; GCN-NEXT:    v_lshlrev_b32_e32 v32, 16, v7
; GCN-NEXT:    v_or_b32_e32 v6, v6, v32
; GCN-NEXT:    v_cvt_f32_f16_e32 v3, v3
; GCN-NEXT:    v_cvt_f32_f16_e32 v2, v2
; GCN-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; GCN-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; GCN-NEXT:    v_cvt_f16_f32_e32 v3, v3
; GCN-NEXT:    v_cvt_f16_f32_e32 v2, v2
; GCN-NEXT:    v_lshlrev_b32_e32 v32, 16, v3
; GCN-NEXT:    v_or_b32_e32 v2, v2, v32
; GCN-NEXT:    v_cvt_f32_f16_e32 v1, v1
; GCN-NEXT:    v_cvt_f32_f16_e32 v0, v0
; GCN-NEXT:    v_cvt_f32_f16_e32 v5, v5
; GCN-NEXT:    v_cvt_f32_f16_e32 v4, v4
; GCN-NEXT:    v_cvt_f32_f16_e32 v9, v9
; GCN-NEXT:    v_cvt_f32_f16_e32 v8, v8
; GCN-NEXT:    v_cvt_f32_f16_e32 v13, v13
; GCN-NEXT:    v_cvt_f32_f16_e32 v12, v12
; GCN-NEXT:    v_cvt_f32_f16_e32 v17, v17
; GCN-NEXT:    v_cvt_f32_f16_e32 v16, v16
; GCN-NEXT:    v_cvt_f32_f16_e32 v21, v21
; GCN-NEXT:    v_cvt_f32_f16_e32 v20, v20
; GCN-NEXT:    v_cvt_f32_f16_e32 v25, v25
; GCN-NEXT:    v_cvt_f32_f16_e32 v24, v24
; GCN-NEXT:    v_cvt_f32_f16_e32 v29, v29
; GCN-NEXT:    v_cvt_f32_f16_e32 v28, v28
; GCN-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; GCN-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; GCN-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; GCN-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; GCN-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; GCN-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; GCN-NEXT:    v_add_f32_e32 v13, 0x38000000, v13
; GCN-NEXT:    v_add_f32_e32 v12, 0x38000000, v12
; GCN-NEXT:    v_add_f32_e32 v17, 0x38000000, v17
; GCN-NEXT:    v_add_f32_e32 v16, 0x38000000, v16
; GCN-NEXT:    v_add_f32_e32 v21, 0x38000000, v21
; GCN-NEXT:    v_add_f32_e32 v20, 0x38000000, v20
; GCN-NEXT:    v_add_f32_e32 v25, 0x38000000, v25
; GCN-NEXT:    v_add_f32_e32 v24, 0x38000000, v24
; GCN-NEXT:    v_add_f32_e32 v29, 0x38000000, v29
; GCN-NEXT:    v_add_f32_e32 v28, 0x38000000, v28
; GCN-NEXT:    v_cvt_f16_f32_e32 v1, v1
; GCN-NEXT:    v_cvt_f16_f32_e32 v0, v0
; GCN-NEXT:    v_cvt_f16_f32_e32 v5, v5
; GCN-NEXT:    v_cvt_f16_f32_e32 v4, v4
; GCN-NEXT:    v_cvt_f16_f32_e32 v9, v9
; GCN-NEXT:    v_cvt_f16_f32_e32 v8, v8
; GCN-NEXT:    v_cvt_f16_f32_e32 v13, v13
; GCN-NEXT:    v_cvt_f16_f32_e32 v12, v12
; GCN-NEXT:    v_cvt_f16_f32_e32 v17, v17
; GCN-NEXT:    v_cvt_f16_f32_e32 v16, v16
; GCN-NEXT:    v_cvt_f16_f32_e32 v21, v21
; GCN-NEXT:    v_cvt_f16_f32_e32 v20, v20
; GCN-NEXT:    v_cvt_f16_f32_e32 v25, v25
; GCN-NEXT:    v_cvt_f16_f32_e32 v24, v24
; GCN-NEXT:    v_cvt_f16_f32_e32 v29, v29
; GCN-NEXT:    v_cvt_f16_f32_e32 v28, v28
; GCN-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; GCN-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GCN-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; GCN-NEXT:    v_lshlrev_b32_e32 v13, 16, v13
; GCN-NEXT:    v_lshlrev_b32_e32 v17, 16, v17
; GCN-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; GCN-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; GCN-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; GCN-NEXT:    v_or_b32_e32 v0, v0, v1
; GCN-NEXT:    v_or_b32_e32 v4, v4, v5
; GCN-NEXT:    v_or_b32_e32 v8, v8, v9
; GCN-NEXT:    v_or_b32_e32 v12, v12, v13
; GCN-NEXT:    v_or_b32_e32 v16, v16, v17
; GCN-NEXT:    v_or_b32_e32 v20, v20, v21
; GCN-NEXT:    v_or_b32_e32 v24, v24, v25
; GCN-NEXT:    v_or_b32_e32 v28, v28, v29
; GCN-NEXT:    v_alignbit_b32 v1, v2, v1, 16
; GCN-NEXT:    v_alignbit_b32 v5, v6, v5, 16
; GCN-NEXT:    v_alignbit_b32 v9, v10, v9, 16
; GCN-NEXT:    v_alignbit_b32 v13, v14, v13, 16
; GCN-NEXT:    v_alignbit_b32 v17, v18, v17, 16
; GCN-NEXT:    v_alignbit_b32 v21, v22, v21, 16
; GCN-NEXT:    v_alignbit_b32 v25, v26, v25, 16
; GCN-NEXT:    v_alignbit_b32 v29, v30, v29, 16
; GCN-NEXT:  .LBB37_2: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v32f16_to_v32i16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB37_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v17, 0x200
; VI-NEXT:    v_add_f16_e32 v19, 0x200, v15
; VI-NEXT:    v_add_f16_sdwa v15, v15, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v15, v19, v15
; VI-NEXT:    v_add_f16_e32 v19, 0x200, v14
; VI-NEXT:    v_add_f16_sdwa v14, v14, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v14, v19, v14
; VI-NEXT:    v_add_f16_e32 v19, 0x200, v13
; VI-NEXT:    v_add_f16_sdwa v13, v13, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v13, v19, v13
; VI-NEXT:    v_add_f16_e32 v19, 0x200, v12
; VI-NEXT:    v_add_f16_sdwa v12, v12, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v12, v19, v12
; VI-NEXT:    v_add_f16_e32 v19, 0x200, v11
; VI-NEXT:    v_add_f16_sdwa v11, v11, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v11, v19, v11
; VI-NEXT:    v_add_f16_e32 v19, 0x200, v10
; VI-NEXT:    v_add_f16_sdwa v10, v10, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v10, v19, v10
; VI-NEXT:    v_add_f16_e32 v19, 0x200, v9
; VI-NEXT:    v_add_f16_sdwa v9, v9, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v9, v19, v9
; VI-NEXT:    v_add_f16_e32 v19, 0x200, v8
; VI-NEXT:    v_add_f16_sdwa v8, v8, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v8, v19, v8
; VI-NEXT:    v_add_f16_e32 v19, 0x200, v7
; VI-NEXT:    v_add_f16_sdwa v7, v7, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v7, v19, v7
; VI-NEXT:    v_add_f16_e32 v19, 0x200, v6
; VI-NEXT:    v_add_f16_sdwa v6, v6, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v6, v19, v6
; VI-NEXT:    v_add_f16_e32 v19, 0x200, v5
; VI-NEXT:    v_add_f16_sdwa v5, v5, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v5, v19, v5
; VI-NEXT:    v_add_f16_e32 v19, 0x200, v4
; VI-NEXT:    v_add_f16_sdwa v4, v4, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v16, 0x200, v0
; VI-NEXT:    v_add_f16_sdwa v0, v0, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v18, 0x200, v1
; VI-NEXT:    v_add_f16_sdwa v1, v1, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v4, v19, v4
; VI-NEXT:    v_add_f16_e32 v19, 0x200, v2
; VI-NEXT:    v_add_f16_sdwa v2, v2, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_sdwa v17, v3, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v3, 0x200, v3
; VI-NEXT:    v_or_b32_e32 v3, v3, v17
; VI-NEXT:    v_or_b32_e32 v2, v19, v2
; VI-NEXT:    v_or_b32_e32 v1, v18, v1
; VI-NEXT:    v_or_b32_e32 v0, v16, v0
; VI-NEXT:  .LBB37_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v32f16_to_v32i16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB37_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    s_movk_i32 s6, 0x200
; GFX9-NEXT:    v_pk_add_f16 v15, v15, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v14, v14, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v13, v13, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v12, v12, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v11, v11, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v10, v10, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v9, v9, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v8, v8, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v7, v7, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, v6, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v5, v5, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v4, v4, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v3, v3, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v2, v2, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v1, v1, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v0, v0, s6 op_sel_hi:[1,0]
; GFX9-NEXT:  .LBB37_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v32f16_to_v32i16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB37_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_pk_add_f16 v15, 0x200, v15 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v14, 0x200, v14 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v13, 0x200, v13 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v12, 0x200, v12 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v11, 0x200, v11 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v10, 0x200, v10 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v9, 0x200, v9 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v8, 0x200, v8 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v7, 0x200, v7 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v6, 0x200, v6 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v5, 0x200, v5 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v4, 0x200, v4 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v3, 0x200, v3 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v2, 0x200, v2 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v1, 0x200, v1 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v0, 0x200, v0 op_sel_hi:[0,1]
; GFX11-NEXT:  .LBB37_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <32 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <32 x half> %a1 to <32 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <32 x half> %a to <32 x i16>
  br label %end

end:
  %phi = phi <32 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x i16> %phi
}

define <32 x bfloat> @v_bitcast_v32i16_to_v32bf16(<32 x i16> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v32i16_to_v32bf16:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_mov_b32_e32 v55, v30
; GCN-NEXT:    v_mov_b32_e32 v54, v28
; GCN-NEXT:    v_mov_b32_e32 v53, v26
; GCN-NEXT:    v_mov_b32_e32 v52, v24
; GCN-NEXT:    v_mov_b32_e32 v51, v22
; GCN-NEXT:    v_mov_b32_e32 v50, v20
; GCN-NEXT:    v_mov_b32_e32 v49, v18
; GCN-NEXT:    v_mov_b32_e32 v48, v16
; GCN-NEXT:    v_mov_b32_e32 v39, v14
; GCN-NEXT:    v_mov_b32_e32 v38, v12
; GCN-NEXT:    v_mov_b32_e32 v37, v10
; GCN-NEXT:    v_mov_b32_e32 v36, v8
; GCN-NEXT:    v_mov_b32_e32 v35, v6
; GCN-NEXT:    v_mov_b32_e32 v34, v4
; GCN-NEXT:    v_mov_b32_e32 v33, v2
; GCN-NEXT:    v_mov_b32_e32 v32, v0
; GCN-NEXT:    buffer_load_dword v0, off, s[0:3], s32
; GCN-NEXT:    buffer_load_dword v2, off, s[0:3], s32 offset:4
; GCN-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; GCN-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; GCN-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GCN-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; GCN-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; GCN-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; GCN-NEXT:    v_lshlrev_b32_e32 v13, 16, v13
; GCN-NEXT:    v_lshlrev_b32_e32 v15, 16, v15
; GCN-NEXT:    v_lshlrev_b32_e32 v17, 16, v17
; GCN-NEXT:    v_lshlrev_b32_e32 v19, 16, v19
; GCN-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; GCN-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; GCN-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; GCN-NEXT:    v_lshlrev_b32_e32 v27, 16, v27
; GCN-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v2
; GCN-NEXT:    v_lshlrev_b32_e32 v31, 16, v0
; GCN-NEXT:    ; implicit-def: $vgpr0
; GCN-NEXT:    ; implicit-def: $vgpr2
; GCN-NEXT:    ; implicit-def: $vgpr4
; GCN-NEXT:    ; implicit-def: $vgpr6
; GCN-NEXT:    ; implicit-def: $vgpr8
; GCN-NEXT:    ; implicit-def: $vgpr10
; GCN-NEXT:    ; implicit-def: $vgpr12
; GCN-NEXT:    ; implicit-def: $vgpr14
; GCN-NEXT:    ; implicit-def: $vgpr16
; GCN-NEXT:    ; implicit-def: $vgpr18
; GCN-NEXT:    ; implicit-def: $vgpr20
; GCN-NEXT:    ; implicit-def: $vgpr22
; GCN-NEXT:    ; implicit-def: $vgpr24
; GCN-NEXT:    ; implicit-def: $vgpr26
; GCN-NEXT:    ; implicit-def: $vgpr28
; GCN-NEXT:    ; implicit-def: $vgpr30
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execnz .LBB38_3
; GCN-NEXT:  ; %bb.1: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execnz .LBB38_4
; GCN-NEXT:  .LBB38_2: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
; GCN-NEXT:  .LBB38_3: ; %cmp.false
; GCN-NEXT:    v_lshlrev_b32_e32 v0, 16, v32
; GCN-NEXT:    v_lshlrev_b32_e32 v2, 16, v33
; GCN-NEXT:    v_lshlrev_b32_e32 v4, 16, v34
; GCN-NEXT:    v_lshlrev_b32_e32 v6, 16, v35
; GCN-NEXT:    v_lshlrev_b32_e32 v8, 16, v36
; GCN-NEXT:    v_lshlrev_b32_e32 v10, 16, v37
; GCN-NEXT:    v_lshlrev_b32_e32 v12, 16, v38
; GCN-NEXT:    v_lshlrev_b32_e32 v14, 16, v39
; GCN-NEXT:    v_lshlrev_b32_e32 v16, 16, v48
; GCN-NEXT:    v_lshlrev_b32_e32 v18, 16, v49
; GCN-NEXT:    v_lshlrev_b32_e32 v20, 16, v50
; GCN-NEXT:    v_lshlrev_b32_e32 v22, 16, v51
; GCN-NEXT:    v_lshlrev_b32_e32 v24, 16, v52
; GCN-NEXT:    v_lshlrev_b32_e32 v26, 16, v53
; GCN-NEXT:    v_lshlrev_b32_e32 v28, 16, v54
; GCN-NEXT:    v_lshlrev_b32_e32 v30, 16, v55
; GCN-NEXT:    ; implicit-def: $vgpr32
; GCN-NEXT:    ; implicit-def: $vgpr33
; GCN-NEXT:    ; implicit-def: $vgpr34
; GCN-NEXT:    ; implicit-def: $vgpr35
; GCN-NEXT:    ; implicit-def: $vgpr36
; GCN-NEXT:    ; implicit-def: $vgpr37
; GCN-NEXT:    ; implicit-def: $vgpr38
; GCN-NEXT:    ; implicit-def: $vgpr39
; GCN-NEXT:    ; implicit-def: $vgpr48
; GCN-NEXT:    ; implicit-def: $vgpr49
; GCN-NEXT:    ; implicit-def: $vgpr50
; GCN-NEXT:    ; implicit-def: $vgpr51
; GCN-NEXT:    ; implicit-def: $vgpr52
; GCN-NEXT:    ; implicit-def: $vgpr53
; GCN-NEXT:    ; implicit-def: $vgpr54
; GCN-NEXT:    ; implicit-def: $vgpr55
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB38_2
; GCN-NEXT:  .LBB38_4: ; %cmp.true
; GCN-NEXT:    v_add_i32_e32 v0, vcc, 3, v55
; GCN-NEXT:    s_mov_b32 s6, 0x30000
; GCN-NEXT:    v_add_i32_e32 v2, vcc, 3, v54
; GCN-NEXT:    v_add_i32_e32 v4, vcc, 3, v53
; GCN-NEXT:    v_add_i32_e32 v6, vcc, 3, v52
; GCN-NEXT:    v_add_i32_e32 v8, vcc, 3, v51
; GCN-NEXT:    v_add_i32_e32 v10, vcc, 3, v50
; GCN-NEXT:    v_add_i32_e32 v12, vcc, 3, v49
; GCN-NEXT:    v_add_i32_e32 v14, vcc, 3, v48
; GCN-NEXT:    v_add_i32_e32 v16, vcc, 3, v39
; GCN-NEXT:    v_add_i32_e32 v18, vcc, 3, v38
; GCN-NEXT:    v_add_i32_e32 v20, vcc, 3, v37
; GCN-NEXT:    v_add_i32_e32 v22, vcc, 3, v36
; GCN-NEXT:    v_add_i32_e32 v24, vcc, 3, v35
; GCN-NEXT:    v_add_i32_e32 v26, vcc, 3, v34
; GCN-NEXT:    v_add_i32_e32 v28, vcc, 3, v33
; GCN-NEXT:    v_add_i32_e32 v30, vcc, 3, v32
; GCN-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GCN-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GCN-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GCN-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; GCN-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; GCN-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; GCN-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; GCN-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; GCN-NEXT:    v_and_b32_e32 v16, 0xffff, v16
; GCN-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; GCN-NEXT:    v_and_b32_e32 v20, 0xffff, v20
; GCN-NEXT:    v_and_b32_e32 v22, 0xffff, v22
; GCN-NEXT:    v_and_b32_e32 v24, 0xffff, v24
; GCN-NEXT:    v_and_b32_e32 v26, 0xffff, v26
; GCN-NEXT:    v_and_b32_e32 v28, 0xffff, v28
; GCN-NEXT:    v_and_b32_e32 v30, 0xffff, v30
; GCN-NEXT:    v_or_b32_e32 v0, v31, v0
; GCN-NEXT:    v_or_b32_e32 v2, v29, v2
; GCN-NEXT:    v_or_b32_e32 v4, v27, v4
; GCN-NEXT:    v_or_b32_e32 v6, v25, v6
; GCN-NEXT:    v_or_b32_e32 v8, v23, v8
; GCN-NEXT:    v_or_b32_e32 v10, v21, v10
; GCN-NEXT:    v_or_b32_e32 v12, v19, v12
; GCN-NEXT:    v_or_b32_e32 v14, v17, v14
; GCN-NEXT:    v_or_b32_e32 v15, v15, v16
; GCN-NEXT:    v_or_b32_e32 v13, v13, v18
; GCN-NEXT:    v_or_b32_e32 v11, v11, v20
; GCN-NEXT:    v_or_b32_e32 v9, v9, v22
; GCN-NEXT:    v_or_b32_e32 v7, v7, v24
; GCN-NEXT:    v_or_b32_e32 v5, v5, v26
; GCN-NEXT:    v_or_b32_e32 v3, v3, v28
; GCN-NEXT:    v_or_b32_e32 v1, v1, v30
; GCN-NEXT:    v_add_i32_e32 v30, vcc, 0x30000, v0
; GCN-NEXT:    v_add_i32_e32 v28, vcc, s6, v2
; GCN-NEXT:    v_add_i32_e32 v26, vcc, s6, v4
; GCN-NEXT:    v_add_i32_e32 v24, vcc, s6, v6
; GCN-NEXT:    v_add_i32_e32 v22, vcc, s6, v8
; GCN-NEXT:    v_add_i32_e32 v20, vcc, s6, v10
; GCN-NEXT:    v_add_i32_e32 v18, vcc, s6, v12
; GCN-NEXT:    v_add_i32_e32 v16, vcc, s6, v14
; GCN-NEXT:    v_add_i32_e32 v14, vcc, s6, v15
; GCN-NEXT:    v_add_i32_e32 v12, vcc, s6, v13
; GCN-NEXT:    v_add_i32_e32 v10, vcc, s6, v11
; GCN-NEXT:    v_add_i32_e32 v8, vcc, s6, v9
; GCN-NEXT:    v_add_i32_e32 v6, vcc, s6, v7
; GCN-NEXT:    v_add_i32_e32 v4, vcc, s6, v5
; GCN-NEXT:    v_add_i32_e32 v2, vcc, s6, v3
; GCN-NEXT:    v_add_i32_e32 v0, vcc, s6, v1
; GCN-NEXT:    v_and_b32_e32 v1, 0xffff0000, v0
; GCN-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; GCN-NEXT:    v_and_b32_e32 v3, 0xffff0000, v2
; GCN-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; GCN-NEXT:    v_and_b32_e32 v5, 0xffff0000, v4
; GCN-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GCN-NEXT:    v_and_b32_e32 v7, 0xffff0000, v6
; GCN-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GCN-NEXT:    v_and_b32_e32 v9, 0xffff0000, v8
; GCN-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; GCN-NEXT:    v_and_b32_e32 v11, 0xffff0000, v10
; GCN-NEXT:    v_lshlrev_b32_e32 v10, 16, v10
; GCN-NEXT:    v_and_b32_e32 v13, 0xffff0000, v12
; GCN-NEXT:    v_lshlrev_b32_e32 v12, 16, v12
; GCN-NEXT:    v_and_b32_e32 v15, 0xffff0000, v14
; GCN-NEXT:    v_lshlrev_b32_e32 v14, 16, v14
; GCN-NEXT:    v_and_b32_e32 v17, 0xffff0000, v16
; GCN-NEXT:    v_lshlrev_b32_e32 v16, 16, v16
; GCN-NEXT:    v_and_b32_e32 v19, 0xffff0000, v18
; GCN-NEXT:    v_lshlrev_b32_e32 v18, 16, v18
; GCN-NEXT:    v_and_b32_e32 v21, 0xffff0000, v20
; GCN-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; GCN-NEXT:    v_and_b32_e32 v23, 0xffff0000, v22
; GCN-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; GCN-NEXT:    v_and_b32_e32 v25, 0xffff0000, v24
; GCN-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; GCN-NEXT:    v_and_b32_e32 v27, 0xffff0000, v26
; GCN-NEXT:    v_lshlrev_b32_e32 v26, 16, v26
; GCN-NEXT:    v_and_b32_e32 v29, 0xffff0000, v28
; GCN-NEXT:    v_lshlrev_b32_e32 v28, 16, v28
; GCN-NEXT:    v_and_b32_e32 v31, 0xffff0000, v30
; GCN-NEXT:    v_lshlrev_b32_e32 v30, 16, v30
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v32i16_to_v32bf16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB38_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v16, 3
; VI-NEXT:    v_add_u16_sdwa v19, v15, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v15, 3, v15
; VI-NEXT:    v_or_b32_e32 v15, v15, v19
; VI-NEXT:    v_add_u16_sdwa v19, v14, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v14, 3, v14
; VI-NEXT:    v_or_b32_e32 v14, v14, v19
; VI-NEXT:    v_add_u16_sdwa v19, v13, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v13, 3, v13
; VI-NEXT:    v_or_b32_e32 v13, v13, v19
; VI-NEXT:    v_add_u16_sdwa v19, v12, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v12, 3, v12
; VI-NEXT:    v_or_b32_e32 v12, v12, v19
; VI-NEXT:    v_add_u16_sdwa v19, v11, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v11, 3, v11
; VI-NEXT:    v_or_b32_e32 v11, v11, v19
; VI-NEXT:    v_add_u16_sdwa v19, v10, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v10, 3, v10
; VI-NEXT:    v_or_b32_e32 v10, v10, v19
; VI-NEXT:    v_add_u16_sdwa v19, v9, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v9, 3, v9
; VI-NEXT:    v_or_b32_e32 v9, v9, v19
; VI-NEXT:    v_add_u16_sdwa v19, v8, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v8, 3, v8
; VI-NEXT:    v_or_b32_e32 v8, v8, v19
; VI-NEXT:    v_add_u16_sdwa v19, v7, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v7, 3, v7
; VI-NEXT:    v_or_b32_e32 v7, v7, v19
; VI-NEXT:    v_add_u16_sdwa v19, v6, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v6, 3, v6
; VI-NEXT:    v_or_b32_e32 v6, v6, v19
; VI-NEXT:    v_add_u16_sdwa v19, v5, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v5, 3, v5
; VI-NEXT:    v_or_b32_e32 v5, v5, v19
; VI-NEXT:    v_add_u16_sdwa v19, v4, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v4, 3, v4
; VI-NEXT:    v_add_u16_sdwa v17, v0, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_sdwa v18, v1, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v4, v4, v19
; VI-NEXT:    v_add_u16_sdwa v19, v2, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_sdwa v16, v3, v16 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v3, 3, v3
; VI-NEXT:    v_add_u16_e32 v2, 3, v2
; VI-NEXT:    v_add_u16_e32 v1, 3, v1
; VI-NEXT:    v_add_u16_e32 v0, 3, v0
; VI-NEXT:    v_or_b32_e32 v3, v3, v16
; VI-NEXT:    v_or_b32_e32 v2, v2, v19
; VI-NEXT:    v_or_b32_e32 v1, v1, v18
; VI-NEXT:    v_or_b32_e32 v0, v0, v17
; VI-NEXT:  .LBB38_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v32i16_to_v32bf16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB38_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_pk_add_u16 v15, v15, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v14, v14, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v13, v13, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v12, v12, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v9, v9, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v8, v8, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX9-NEXT:  .LBB38_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v32i16_to_v32bf16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB38_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_pk_add_u16 v15, v15, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v14, v14, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v13, v13, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v12, v12, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v9, v9, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v8, v8, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX11-NEXT:  .LBB38_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <32 x i16> %a, splat (i16 3)
  %a2 = bitcast <32 x i16> %a1 to <32 x bfloat>
  br label %end

cmp.false:
  %a3 = bitcast <32 x i16> %a to <32 x bfloat>
  br label %end

end:
  %phi = phi <32 x bfloat> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x bfloat> %phi
}

define <32 x i16> @v_bitcast_v32bf16_to_v32i16(<32 x bfloat> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v32bf16_to_v32i16:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:68 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:64 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:60 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:56 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:52 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:48 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:44 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:40 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v59, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v60, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v61, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v62, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v63, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_load_dword v31, off, s[0:3], s32
; GCN-NEXT:    buffer_load_dword v55, off, s[0:3], s32 offset:4
; GCN-NEXT:    s_waitcnt expcnt(0)
; GCN-NEXT:    v_mul_f32_e32 v63, 1.0, v0
; GCN-NEXT:    v_mul_f32_e32 v62, 1.0, v1
; GCN-NEXT:    v_mul_f32_e32 v33, 1.0, v2
; GCN-NEXT:    v_mul_f32_e32 v32, 1.0, v3
; GCN-NEXT:    v_mul_f32_e32 v61, 1.0, v4
; GCN-NEXT:    v_mul_f32_e32 v60, 1.0, v5
; GCN-NEXT:    v_mul_f32_e32 v35, 1.0, v6
; GCN-NEXT:    v_mul_f32_e32 v34, 1.0, v7
; GCN-NEXT:    v_mul_f32_e32 v59, 1.0, v8
; GCN-NEXT:    v_mul_f32_e32 v58, 1.0, v9
; GCN-NEXT:    v_mul_f32_e32 v37, 1.0, v10
; GCN-NEXT:    v_mul_f32_e32 v36, 1.0, v11
; GCN-NEXT:    v_mul_f32_e32 v57, 1.0, v12
; GCN-NEXT:    v_mul_f32_e32 v56, 1.0, v13
; GCN-NEXT:    v_mul_f32_e32 v39, 1.0, v14
; GCN-NEXT:    v_mul_f32_e32 v38, 1.0, v15
; GCN-NEXT:    v_mul_f32_e32 v47, 1.0, v16
; GCN-NEXT:    v_mul_f32_e32 v46, 1.0, v17
; GCN-NEXT:    v_mul_f32_e32 v49, 1.0, v18
; GCN-NEXT:    v_mul_f32_e32 v48, 1.0, v19
; GCN-NEXT:    v_mul_f32_e32 v45, 1.0, v20
; GCN-NEXT:    v_mul_f32_e32 v44, 1.0, v21
; GCN-NEXT:    v_mul_f32_e32 v51, 1.0, v22
; GCN-NEXT:    v_mul_f32_e32 v50, 1.0, v23
; GCN-NEXT:    v_mul_f32_e32 v43, 1.0, v24
; GCN-NEXT:    v_mul_f32_e32 v42, 1.0, v25
; GCN-NEXT:    v_mul_f32_e32 v53, 1.0, v26
; GCN-NEXT:    v_mul_f32_e32 v52, 1.0, v27
; GCN-NEXT:    v_mul_f32_e32 v41, 1.0, v28
; GCN-NEXT:    v_mul_f32_e32 v40, 1.0, v29
; GCN-NEXT:    v_mul_f32_e32 v54, 1.0, v30
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v55
; GCN-NEXT:    v_mul_f32_e32 v55, 1.0, v31
; GCN-NEXT:    ; implicit-def: $vgpr0
; GCN-NEXT:    ; implicit-def: $vgpr1
; GCN-NEXT:    ; implicit-def: $vgpr2
; GCN-NEXT:    ; implicit-def: $vgpr3
; GCN-NEXT:    ; implicit-def: $vgpr4
; GCN-NEXT:    ; implicit-def: $vgpr5
; GCN-NEXT:    ; implicit-def: $vgpr6
; GCN-NEXT:    ; implicit-def: $vgpr7
; GCN-NEXT:    ; implicit-def: $vgpr8
; GCN-NEXT:    ; implicit-def: $vgpr9
; GCN-NEXT:    ; implicit-def: $vgpr10
; GCN-NEXT:    ; implicit-def: $vgpr11
; GCN-NEXT:    ; implicit-def: $vgpr12
; GCN-NEXT:    ; implicit-def: $vgpr13
; GCN-NEXT:    ; implicit-def: $vgpr14
; GCN-NEXT:    ; implicit-def: $vgpr15
; GCN-NEXT:    ; implicit-def: $vgpr16
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr18
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr20
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr22
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr24
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr26
; GCN-NEXT:    ; implicit-def: $vgpr27
; GCN-NEXT:    ; implicit-def: $vgpr28
; GCN-NEXT:    ; implicit-def: $vgpr29
; GCN-NEXT:    ; implicit-def: $vgpr30
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB39_2
; GCN-NEXT:  ; %bb.1: ; %cmp.false
; GCN-NEXT:    v_lshrrev_b32_e32 v0, 16, v63
; GCN-NEXT:    v_lshrrev_b32_e32 v1, 16, v62
; GCN-NEXT:    v_lshrrev_b32_e32 v2, 16, v33
; GCN-NEXT:    v_lshrrev_b32_e32 v3, 16, v32
; GCN-NEXT:    v_lshrrev_b32_e32 v4, 16, v61
; GCN-NEXT:    v_lshrrev_b32_e32 v5, 16, v60
; GCN-NEXT:    v_lshrrev_b32_e32 v6, 16, v35
; GCN-NEXT:    v_lshrrev_b32_e32 v7, 16, v34
; GCN-NEXT:    v_lshrrev_b32_e32 v8, 16, v59
; GCN-NEXT:    v_lshrrev_b32_e32 v9, 16, v58
; GCN-NEXT:    v_lshrrev_b32_e32 v10, 16, v37
; GCN-NEXT:    v_lshrrev_b32_e32 v11, 16, v36
; GCN-NEXT:    v_lshrrev_b32_e32 v12, 16, v57
; GCN-NEXT:    v_lshrrev_b32_e32 v13, 16, v56
; GCN-NEXT:    v_lshrrev_b32_e32 v14, 16, v39
; GCN-NEXT:    v_lshrrev_b32_e32 v15, 16, v38
; GCN-NEXT:    v_lshrrev_b32_e32 v16, 16, v47
; GCN-NEXT:    v_lshrrev_b32_e32 v17, 16, v46
; GCN-NEXT:    v_lshrrev_b32_e32 v18, 16, v49
; GCN-NEXT:    v_lshrrev_b32_e32 v19, 16, v48
; GCN-NEXT:    v_lshrrev_b32_e32 v20, 16, v45
; GCN-NEXT:    v_lshrrev_b32_e32 v21, 16, v44
; GCN-NEXT:    v_lshrrev_b32_e32 v22, 16, v51
; GCN-NEXT:    v_lshrrev_b32_e32 v23, 16, v50
; GCN-NEXT:    v_lshrrev_b32_e32 v24, 16, v43
; GCN-NEXT:    v_lshrrev_b32_e32 v25, 16, v42
; GCN-NEXT:    v_lshrrev_b32_e32 v26, 16, v53
; GCN-NEXT:    v_lshrrev_b32_e32 v27, 16, v52
; GCN-NEXT:    v_lshrrev_b32_e32 v28, 16, v41
; GCN-NEXT:    v_lshrrev_b32_e32 v29, 16, v40
; GCN-NEXT:    v_lshrrev_b32_e32 v30, 16, v54
; GCN-NEXT:    v_lshrrev_b32_e32 v31, 16, v55
; GCN-NEXT:    ; implicit-def: $vgpr63
; GCN-NEXT:    ; implicit-def: $vgpr62
; GCN-NEXT:    ; implicit-def: $vgpr33
; GCN-NEXT:    ; implicit-def: $vgpr32
; GCN-NEXT:    ; implicit-def: $vgpr61
; GCN-NEXT:    ; implicit-def: $vgpr60
; GCN-NEXT:    ; implicit-def: $vgpr35
; GCN-NEXT:    ; implicit-def: $vgpr34
; GCN-NEXT:    ; implicit-def: $vgpr59
; GCN-NEXT:    ; implicit-def: $vgpr58
; GCN-NEXT:    ; implicit-def: $vgpr37
; GCN-NEXT:    ; implicit-def: $vgpr36
; GCN-NEXT:    ; implicit-def: $vgpr57
; GCN-NEXT:    ; implicit-def: $vgpr56
; GCN-NEXT:    ; implicit-def: $vgpr39
; GCN-NEXT:    ; implicit-def: $vgpr38
; GCN-NEXT:    ; implicit-def: $vgpr47
; GCN-NEXT:    ; implicit-def: $vgpr46
; GCN-NEXT:    ; implicit-def: $vgpr49
; GCN-NEXT:    ; implicit-def: $vgpr48
; GCN-NEXT:    ; implicit-def: $vgpr45
; GCN-NEXT:    ; implicit-def: $vgpr44
; GCN-NEXT:    ; implicit-def: $vgpr51
; GCN-NEXT:    ; implicit-def: $vgpr50
; GCN-NEXT:    ; implicit-def: $vgpr43
; GCN-NEXT:    ; implicit-def: $vgpr42
; GCN-NEXT:    ; implicit-def: $vgpr53
; GCN-NEXT:    ; implicit-def: $vgpr52
; GCN-NEXT:    ; implicit-def: $vgpr41
; GCN-NEXT:    ; implicit-def: $vgpr40
; GCN-NEXT:    ; implicit-def: $vgpr54
; GCN-NEXT:    ; implicit-def: $vgpr55
; GCN-NEXT:  .LBB39_2: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB39_4
; GCN-NEXT:  ; %bb.3: ; %cmp.true
; GCN-NEXT:    v_and_b32_e32 v0, 0xffff0000, v63
; GCN-NEXT:    v_and_b32_e32 v1, 0xffff0000, v62
; GCN-NEXT:    v_and_b32_e32 v2, 0xffff0000, v61
; GCN-NEXT:    v_and_b32_e32 v3, 0xffff0000, v60
; GCN-NEXT:    v_and_b32_e32 v4, 0xffff0000, v59
; GCN-NEXT:    v_and_b32_e32 v5, 0xffff0000, v58
; GCN-NEXT:    v_and_b32_e32 v6, 0xffff0000, v57
; GCN-NEXT:    v_and_b32_e32 v7, 0xffff0000, v56
; GCN-NEXT:    v_and_b32_e32 v8, 0xffff0000, v47
; GCN-NEXT:    v_and_b32_e32 v9, 0xffff0000, v46
; GCN-NEXT:    v_and_b32_e32 v10, 0xffff0000, v45
; GCN-NEXT:    v_and_b32_e32 v11, 0xffff0000, v44
; GCN-NEXT:    v_and_b32_e32 v12, 0xffff0000, v43
; GCN-NEXT:    v_and_b32_e32 v13, 0xffff0000, v42
; GCN-NEXT:    v_and_b32_e32 v14, 0xffff0000, v41
; GCN-NEXT:    v_and_b32_e32 v15, 0xffff0000, v40
; GCN-NEXT:    v_and_b32_e32 v16, 0xffff0000, v54
; GCN-NEXT:    v_and_b32_e32 v17, 0xffff0000, v55
; GCN-NEXT:    v_and_b32_e32 v18, 0xffff0000, v53
; GCN-NEXT:    v_and_b32_e32 v19, 0xffff0000, v52
; GCN-NEXT:    v_and_b32_e32 v20, 0xffff0000, v51
; GCN-NEXT:    v_and_b32_e32 v21, 0xffff0000, v50
; GCN-NEXT:    v_and_b32_e32 v22, 0xffff0000, v49
; GCN-NEXT:    v_and_b32_e32 v23, 0xffff0000, v48
; GCN-NEXT:    v_and_b32_e32 v24, 0xffff0000, v39
; GCN-NEXT:    v_and_b32_e32 v25, 0xffff0000, v38
; GCN-NEXT:    v_and_b32_e32 v26, 0xffff0000, v37
; GCN-NEXT:    v_and_b32_e32 v27, 0xffff0000, v36
; GCN-NEXT:    v_and_b32_e32 v28, 0xffff0000, v35
; GCN-NEXT:    v_and_b32_e32 v29, 0xffff0000, v34
; GCN-NEXT:    v_and_b32_e32 v30, 0xffff0000, v33
; GCN-NEXT:    v_and_b32_e32 v31, 0xffff0000, v32
; GCN-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; GCN-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GCN-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GCN-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GCN-NEXT:    v_add_f32_e32 v32, 0x40c00000, v4
; GCN-NEXT:    v_add_f32_e32 v4, 0x40c00000, v5
; GCN-NEXT:    v_add_f32_e32 v5, 0x40c00000, v6
; GCN-NEXT:    v_add_f32_e32 v6, 0x40c00000, v7
; GCN-NEXT:    v_add_f32_e32 v33, 0x40c00000, v8
; GCN-NEXT:    v_add_f32_e32 v7, 0x40c00000, v9
; GCN-NEXT:    v_add_f32_e32 v9, 0x40c00000, v10
; GCN-NEXT:    v_add_f32_e32 v8, 0x40c00000, v11
; GCN-NEXT:    v_add_f32_e32 v10, 0x40c00000, v12
; GCN-NEXT:    v_add_f32_e32 v11, 0x40c00000, v13
; GCN-NEXT:    v_add_f32_e32 v13, 0x40c00000, v14
; GCN-NEXT:    v_add_f32_e32 v12, 0x40c00000, v15
; GCN-NEXT:    v_add_f32_e32 v14, 0x40c00000, v16
; GCN-NEXT:    v_add_f32_e32 v15, 0x40c00000, v17
; GCN-NEXT:    v_add_f32_e32 v17, 0x40c00000, v18
; GCN-NEXT:    v_add_f32_e32 v16, 0x40c00000, v19
; GCN-NEXT:    v_add_f32_e32 v18, 0x40c00000, v20
; GCN-NEXT:    v_add_f32_e32 v19, 0x40c00000, v21
; GCN-NEXT:    v_add_f32_e32 v21, 0x40c00000, v22
; GCN-NEXT:    v_add_f32_e32 v20, 0x40c00000, v23
; GCN-NEXT:    v_add_f32_e32 v34, 0x40c00000, v24
; GCN-NEXT:    v_add_f32_e32 v22, 0x40c00000, v25
; GCN-NEXT:    v_add_f32_e32 v25, 0x40c00000, v26
; GCN-NEXT:    v_add_f32_e32 v24, 0x40c00000, v27
; GCN-NEXT:    v_add_f32_e32 v35, 0x40c00000, v28
; GCN-NEXT:    v_add_f32_e32 v26, 0x40c00000, v29
; GCN-NEXT:    v_add_f32_e32 v29, 0x40c00000, v30
; GCN-NEXT:    v_add_f32_e32 v28, 0x40c00000, v31
; GCN-NEXT:    v_lshrrev_b32_e32 v30, 16, v1
; GCN-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GCN-NEXT:    v_lshrrev_b32_e32 v37, 16, v4
; GCN-NEXT:    v_lshrrev_b32_e32 v38, 16, v6
; GCN-NEXT:    v_lshrrev_b32_e32 v39, 16, v7
; GCN-NEXT:    v_lshrrev_b32_e32 v48, 16, v8
; GCN-NEXT:    v_lshrrev_b32_e32 v49, 16, v11
; GCN-NEXT:    v_lshrrev_b32_e32 v50, 16, v12
; GCN-NEXT:    v_lshrrev_b32_e32 v31, 16, v15
; GCN-NEXT:    v_and_b32_e32 v51, 0xffff0000, v12
; GCN-NEXT:    v_lshrrev_b32_e32 v27, 16, v16
; GCN-NEXT:    v_and_b32_e32 v52, 0xffff0000, v11
; GCN-NEXT:    v_lshrrev_b32_e32 v23, 16, v19
; GCN-NEXT:    v_and_b32_e32 v53, 0xffff0000, v8
; GCN-NEXT:    v_lshrrev_b32_e32 v19, 16, v20
; GCN-NEXT:    v_and_b32_e32 v54, 0xffff0000, v7
; GCN-NEXT:    v_lshrrev_b32_e32 v15, 16, v22
; GCN-NEXT:    v_and_b32_e32 v55, 0xffff0000, v6
; GCN-NEXT:    v_lshrrev_b32_e32 v11, 16, v24
; GCN-NEXT:    v_and_b32_e32 v40, 0xffff0000, v4
; GCN-NEXT:    v_lshrrev_b32_e32 v7, 16, v26
; GCN-NEXT:    v_and_b32_e32 v41, 0xffff0000, v3
; GCN-NEXT:    v_lshrrev_b32_e32 v3, 16, v28
; GCN-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; GCN-NEXT:    v_alignbit_b32 v0, v30, v0, 16
; GCN-NEXT:    v_alignbit_b32 v4, v36, v2, 16
; GCN-NEXT:    v_alignbit_b32 v8, v37, v32, 16
; GCN-NEXT:    v_alignbit_b32 v12, v38, v5, 16
; GCN-NEXT:    v_alignbit_b32 v16, v39, v33, 16
; GCN-NEXT:    v_alignbit_b32 v20, v48, v9, 16
; GCN-NEXT:    v_alignbit_b32 v24, v49, v10, 16
; GCN-NEXT:    v_alignbit_b32 v28, v50, v13, 16
; GCN-NEXT:    v_alignbit_b32 v30, v31, v14, 16
; GCN-NEXT:    v_alignbit_b32 v26, v27, v17, 16
; GCN-NEXT:    v_alignbit_b32 v22, v23, v18, 16
; GCN-NEXT:    v_alignbit_b32 v18, v19, v21, 16
; GCN-NEXT:    v_alignbit_b32 v14, v15, v34, 16
; GCN-NEXT:    v_alignbit_b32 v10, v11, v25, 16
; GCN-NEXT:    v_alignbit_b32 v6, v7, v35, 16
; GCN-NEXT:    v_alignbit_b32 v2, v3, v29, 16
; GCN-NEXT:    v_alignbit_b32 v1, v2, v1, 16
; GCN-NEXT:    v_alignbit_b32 v5, v6, v41, 16
; GCN-NEXT:    v_alignbit_b32 v9, v10, v40, 16
; GCN-NEXT:    v_alignbit_b32 v13, v14, v55, 16
; GCN-NEXT:    v_alignbit_b32 v17, v18, v54, 16
; GCN-NEXT:    v_alignbit_b32 v21, v22, v53, 16
; GCN-NEXT:    v_alignbit_b32 v25, v26, v52, 16
; GCN-NEXT:    v_alignbit_b32 v29, v30, v51, 16
; GCN-NEXT:  .LBB39_4: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    buffer_load_dword v63, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v62, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v61, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v60, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v57, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:40 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:44 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:48 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:52 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:56 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:60 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v32bf16_to_v32i16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB39_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v0
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, 0x7fff, v17
; VI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v0, 16, 1
; VI-NEXT:    s_movk_i32 s6, 0x7fff
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v0
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v0
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; VI-NEXT:    v_cndmask_b32_e32 v0, v17, v18, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v17, 16, v1
; VI-NEXT:    v_add_f32_e32 v17, 0x40c00000, v17
; VI-NEXT:    v_bfe_u32 v18, v17, 16, 1
; VI-NEXT:    v_add_u32_e32 v18, vcc, v18, v17
; VI-NEXT:    v_add_u32_e32 v18, vcc, s6, v18
; VI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; VI-NEXT:    v_or_b32_e32 v19, 0x400000, v17
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v17, v17
; VI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; VI-NEXT:    v_cndmask_b32_e32 v17, v18, v19, vcc
; VI-NEXT:    v_bfe_u32 v18, v1, 16, 1
; VI-NEXT:    v_add_u32_e32 v18, vcc, v18, v1
; VI-NEXT:    v_add_u32_e32 v18, vcc, s6, v18
; VI-NEXT:    v_or_b32_e32 v19, 0x400000, v1
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; VI-NEXT:    v_cndmask_b32_e32 v1, v18, v19, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v18, 16, v2
; VI-NEXT:    v_add_f32_e32 v18, 0x40c00000, v18
; VI-NEXT:    v_bfe_u32 v19, v18, 16, 1
; VI-NEXT:    v_add_u32_e32 v19, vcc, v19, v18
; VI-NEXT:    v_add_u32_e32 v19, vcc, s6, v19
; VI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; VI-NEXT:    v_or_b32_e32 v20, 0x400000, v18
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v18, v18
; VI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; VI-NEXT:    v_cndmask_b32_e32 v18, v19, v20, vcc
; VI-NEXT:    v_bfe_u32 v19, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v19, vcc, v19, v2
; VI-NEXT:    v_add_u32_e32 v19, vcc, s6, v19
; VI-NEXT:    v_or_b32_e32 v20, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v19, v20, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v19, 16, v3
; VI-NEXT:    v_add_f32_e32 v19, 0x40c00000, v19
; VI-NEXT:    v_bfe_u32 v20, v19, 16, 1
; VI-NEXT:    v_add_u32_e32 v20, vcc, v20, v19
; VI-NEXT:    v_add_u32_e32 v20, vcc, s6, v20
; VI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; VI-NEXT:    v_or_b32_e32 v21, 0x400000, v19
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v19, v19
; VI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; VI-NEXT:    v_cndmask_b32_e32 v19, v20, v21, vcc
; VI-NEXT:    v_bfe_u32 v20, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v20, vcc, v20, v3
; VI-NEXT:    v_add_u32_e32 v20, vcc, s6, v20
; VI-NEXT:    v_or_b32_e32 v21, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v20, v21, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v4
; VI-NEXT:    v_add_f32_e32 v20, 0x40c00000, v20
; VI-NEXT:    v_bfe_u32 v21, v20, 16, 1
; VI-NEXT:    v_add_u32_e32 v21, vcc, v21, v20
; VI-NEXT:    v_add_u32_e32 v21, vcc, s6, v21
; VI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; VI-NEXT:    v_or_b32_e32 v22, 0x400000, v20
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v20, v20
; VI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; VI-NEXT:    v_cndmask_b32_e32 v20, v21, v22, vcc
; VI-NEXT:    v_bfe_u32 v21, v4, 16, 1
; VI-NEXT:    v_add_u32_e32 v21, vcc, v21, v4
; VI-NEXT:    v_add_u32_e32 v21, vcc, s6, v21
; VI-NEXT:    v_or_b32_e32 v22, 0x400000, v4
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; VI-NEXT:    v_cndmask_b32_e32 v4, v21, v22, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v21, 16, v5
; VI-NEXT:    v_add_f32_e32 v21, 0x40c00000, v21
; VI-NEXT:    v_bfe_u32 v22, v21, 16, 1
; VI-NEXT:    v_add_u32_e32 v22, vcc, v22, v21
; VI-NEXT:    v_add_u32_e32 v22, vcc, s6, v22
; VI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; VI-NEXT:    v_or_b32_e32 v23, 0x400000, v21
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v21, v21
; VI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; VI-NEXT:    v_cndmask_b32_e32 v21, v22, v23, vcc
; VI-NEXT:    v_bfe_u32 v22, v5, 16, 1
; VI-NEXT:    v_add_u32_e32 v22, vcc, v22, v5
; VI-NEXT:    v_add_u32_e32 v22, vcc, s6, v22
; VI-NEXT:    v_or_b32_e32 v23, 0x400000, v5
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; VI-NEXT:    v_cndmask_b32_e32 v5, v22, v23, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v22, 16, v6
; VI-NEXT:    v_add_f32_e32 v22, 0x40c00000, v22
; VI-NEXT:    v_bfe_u32 v23, v22, 16, 1
; VI-NEXT:    v_add_u32_e32 v23, vcc, v23, v22
; VI-NEXT:    v_add_u32_e32 v23, vcc, s6, v23
; VI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; VI-NEXT:    v_or_b32_e32 v24, 0x400000, v22
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v22, v22
; VI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; VI-NEXT:    v_cndmask_b32_e32 v22, v23, v24, vcc
; VI-NEXT:    v_bfe_u32 v23, v6, 16, 1
; VI-NEXT:    v_add_u32_e32 v23, vcc, v23, v6
; VI-NEXT:    v_add_u32_e32 v23, vcc, s6, v23
; VI-NEXT:    v_or_b32_e32 v24, 0x400000, v6
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; VI-NEXT:    v_cndmask_b32_e32 v6, v23, v24, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v23, 16, v7
; VI-NEXT:    v_add_f32_e32 v23, 0x40c00000, v23
; VI-NEXT:    v_bfe_u32 v24, v23, 16, 1
; VI-NEXT:    v_add_u32_e32 v24, vcc, v24, v23
; VI-NEXT:    v_add_u32_e32 v24, vcc, s6, v24
; VI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; VI-NEXT:    v_or_b32_e32 v25, 0x400000, v23
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v23, v23
; VI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; VI-NEXT:    v_cndmask_b32_e32 v23, v24, v25, vcc
; VI-NEXT:    v_bfe_u32 v24, v7, 16, 1
; VI-NEXT:    v_add_u32_e32 v24, vcc, v24, v7
; VI-NEXT:    v_add_u32_e32 v24, vcc, s6, v24
; VI-NEXT:    v_or_b32_e32 v25, 0x400000, v7
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; VI-NEXT:    v_cndmask_b32_e32 v7, v24, v25, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v24, 16, v8
; VI-NEXT:    v_add_f32_e32 v24, 0x40c00000, v24
; VI-NEXT:    v_bfe_u32 v25, v24, 16, 1
; VI-NEXT:    v_add_u32_e32 v25, vcc, v25, v24
; VI-NEXT:    v_add_u32_e32 v25, vcc, s6, v25
; VI-NEXT:    v_and_b32_e32 v8, 0xffff0000, v8
; VI-NEXT:    v_or_b32_e32 v26, 0x400000, v24
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v24, v24
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_cndmask_b32_e32 v24, v25, v26, vcc
; VI-NEXT:    v_bfe_u32 v25, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v25, vcc, v25, v8
; VI-NEXT:    v_add_u32_e32 v25, vcc, s6, v25
; VI-NEXT:    v_or_b32_e32 v26, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_cndmask_b32_e32 v8, v25, v26, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v25, 16, v9
; VI-NEXT:    v_add_f32_e32 v25, 0x40c00000, v25
; VI-NEXT:    v_bfe_u32 v26, v25, 16, 1
; VI-NEXT:    v_add_u32_e32 v26, vcc, v26, v25
; VI-NEXT:    v_add_u32_e32 v26, vcc, s6, v26
; VI-NEXT:    v_and_b32_e32 v9, 0xffff0000, v9
; VI-NEXT:    v_or_b32_e32 v27, 0x400000, v25
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v25, v25
; VI-NEXT:    v_add_f32_e32 v9, 0x40c00000, v9
; VI-NEXT:    v_cndmask_b32_e32 v25, v26, v27, vcc
; VI-NEXT:    v_bfe_u32 v26, v9, 16, 1
; VI-NEXT:    v_add_u32_e32 v26, vcc, v26, v9
; VI-NEXT:    v_add_u32_e32 v26, vcc, s6, v26
; VI-NEXT:    v_or_b32_e32 v27, 0x400000, v9
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v9, v9
; VI-NEXT:    v_cndmask_b32_e32 v9, v26, v27, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v26, 16, v10
; VI-NEXT:    v_add_f32_e32 v26, 0x40c00000, v26
; VI-NEXT:    v_bfe_u32 v27, v26, 16, 1
; VI-NEXT:    v_add_u32_e32 v27, vcc, v27, v26
; VI-NEXT:    v_add_u32_e32 v27, vcc, s6, v27
; VI-NEXT:    v_and_b32_e32 v10, 0xffff0000, v10
; VI-NEXT:    v_or_b32_e32 v28, 0x400000, v26
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v26, v26
; VI-NEXT:    v_add_f32_e32 v10, 0x40c00000, v10
; VI-NEXT:    v_cndmask_b32_e32 v26, v27, v28, vcc
; VI-NEXT:    v_bfe_u32 v27, v10, 16, 1
; VI-NEXT:    v_add_u32_e32 v27, vcc, v27, v10
; VI-NEXT:    v_add_u32_e32 v27, vcc, s6, v27
; VI-NEXT:    v_or_b32_e32 v28, 0x400000, v10
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v10, v10
; VI-NEXT:    v_cndmask_b32_e32 v10, v27, v28, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v27, 16, v11
; VI-NEXT:    v_add_f32_e32 v27, 0x40c00000, v27
; VI-NEXT:    v_bfe_u32 v28, v27, 16, 1
; VI-NEXT:    v_add_u32_e32 v28, vcc, v28, v27
; VI-NEXT:    v_add_u32_e32 v28, vcc, s6, v28
; VI-NEXT:    v_and_b32_e32 v11, 0xffff0000, v11
; VI-NEXT:    v_or_b32_e32 v29, 0x400000, v27
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v27, v27
; VI-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; VI-NEXT:    v_cndmask_b32_e32 v27, v28, v29, vcc
; VI-NEXT:    v_bfe_u32 v28, v11, 16, 1
; VI-NEXT:    v_add_u32_e32 v28, vcc, v28, v11
; VI-NEXT:    v_add_u32_e32 v28, vcc, s6, v28
; VI-NEXT:    v_or_b32_e32 v29, 0x400000, v11
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v11, v11
; VI-NEXT:    v_cndmask_b32_e32 v11, v28, v29, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v28, 16, v12
; VI-NEXT:    v_add_f32_e32 v28, 0x40c00000, v28
; VI-NEXT:    v_bfe_u32 v29, v28, 16, 1
; VI-NEXT:    v_add_u32_e32 v29, vcc, v29, v28
; VI-NEXT:    v_add_u32_e32 v29, vcc, s6, v29
; VI-NEXT:    v_and_b32_e32 v12, 0xffff0000, v12
; VI-NEXT:    v_or_b32_e32 v30, 0x400000, v28
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v28, v28
; VI-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; VI-NEXT:    v_cndmask_b32_e32 v28, v29, v30, vcc
; VI-NEXT:    v_bfe_u32 v29, v12, 16, 1
; VI-NEXT:    v_add_u32_e32 v29, vcc, v29, v12
; VI-NEXT:    v_add_u32_e32 v29, vcc, s6, v29
; VI-NEXT:    v_or_b32_e32 v30, 0x400000, v12
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v12, v12
; VI-NEXT:    v_cndmask_b32_e32 v12, v29, v30, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v29, 16, v13
; VI-NEXT:    v_add_f32_e32 v29, 0x40c00000, v29
; VI-NEXT:    v_bfe_u32 v30, v29, 16, 1
; VI-NEXT:    v_add_u32_e32 v30, vcc, v30, v29
; VI-NEXT:    v_add_u32_e32 v30, vcc, s6, v30
; VI-NEXT:    v_and_b32_e32 v13, 0xffff0000, v13
; VI-NEXT:    v_or_b32_e32 v31, 0x400000, v29
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v29, v29
; VI-NEXT:    v_add_f32_e32 v13, 0x40c00000, v13
; VI-NEXT:    v_cndmask_b32_e32 v29, v30, v31, vcc
; VI-NEXT:    v_bfe_u32 v30, v13, 16, 1
; VI-NEXT:    v_add_u32_e32 v30, vcc, v30, v13
; VI-NEXT:    v_add_u32_e32 v30, vcc, s6, v30
; VI-NEXT:    v_or_b32_e32 v31, 0x400000, v13
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v13, v13
; VI-NEXT:    v_cndmask_b32_e32 v13, v30, v31, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v30, 16, v14
; VI-NEXT:    v_add_f32_e32 v30, 0x40c00000, v30
; VI-NEXT:    v_bfe_u32 v31, v30, 16, 1
; VI-NEXT:    v_add_u32_e32 v31, vcc, v31, v30
; VI-NEXT:    v_add_u32_e32 v31, vcc, s6, v31
; VI-NEXT:    v_and_b32_e32 v14, 0xffff0000, v14
; VI-NEXT:    v_or_b32_e32 v32, 0x400000, v30
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v30, v30
; VI-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; VI-NEXT:    v_cndmask_b32_e32 v30, v31, v32, vcc
; VI-NEXT:    v_bfe_u32 v31, v14, 16, 1
; VI-NEXT:    v_add_u32_e32 v31, vcc, v31, v14
; VI-NEXT:    v_add_u32_e32 v31, vcc, s6, v31
; VI-NEXT:    v_or_b32_e32 v32, 0x400000, v14
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v14, v14
; VI-NEXT:    v_cndmask_b32_e32 v14, v31, v32, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v31, 16, v15
; VI-NEXT:    v_add_f32_e32 v31, 0x40c00000, v31
; VI-NEXT:    v_bfe_u32 v32, v31, 16, 1
; VI-NEXT:    v_add_u32_e32 v32, vcc, v32, v31
; VI-NEXT:    v_add_u32_e32 v32, vcc, s6, v32
; VI-NEXT:    v_and_b32_e32 v15, 0xffff0000, v15
; VI-NEXT:    v_or_b32_e32 v33, 0x400000, v31
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v31, v31
; VI-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; VI-NEXT:    v_cndmask_b32_e32 v31, v32, v33, vcc
; VI-NEXT:    v_bfe_u32 v32, v15, 16, 1
; VI-NEXT:    v_add_u32_e32 v32, vcc, v32, v15
; VI-NEXT:    v_add_u32_e32 v32, vcc, s6, v32
; VI-NEXT:    v_or_b32_e32 v33, 0x400000, v15
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v15, v15
; VI-NEXT:    v_cndmask_b32_e32 v15, v32, v33, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v15, 16, v15
; VI-NEXT:    v_lshrrev_b32_e32 v14, 16, v14
; VI-NEXT:    v_lshrrev_b32_e32 v13, 16, v13
; VI-NEXT:    v_lshrrev_b32_e32 v12, 16, v12
; VI-NEXT:    v_lshrrev_b32_e32 v11, 16, v11
; VI-NEXT:    v_lshrrev_b32_e32 v10, 16, v10
; VI-NEXT:    v_lshrrev_b32_e32 v9, 16, v9
; VI-NEXT:    v_lshrrev_b32_e32 v8, 16, v8
; VI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; VI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_alignbit_b32 v15, v15, v31, 16
; VI-NEXT:    v_alignbit_b32 v14, v14, v30, 16
; VI-NEXT:    v_alignbit_b32 v13, v13, v29, 16
; VI-NEXT:    v_alignbit_b32 v12, v12, v28, 16
; VI-NEXT:    v_alignbit_b32 v11, v11, v27, 16
; VI-NEXT:    v_alignbit_b32 v10, v10, v26, 16
; VI-NEXT:    v_alignbit_b32 v9, v9, v25, 16
; VI-NEXT:    v_alignbit_b32 v8, v8, v24, 16
; VI-NEXT:    v_alignbit_b32 v7, v7, v23, 16
; VI-NEXT:    v_alignbit_b32 v6, v6, v22, 16
; VI-NEXT:    v_alignbit_b32 v5, v5, v21, 16
; VI-NEXT:    v_alignbit_b32 v4, v4, v20, 16
; VI-NEXT:    v_alignbit_b32 v3, v3, v19, 16
; VI-NEXT:    v_alignbit_b32 v2, v2, v18, 16
; VI-NEXT:    v_alignbit_b32 v1, v1, v17, 16
; VI-NEXT:    v_alignbit_b32 v0, v0, v16, 16
; VI-NEXT:  .LBB39_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v32bf16_to_v32i16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB39_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v0
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    s_movk_i32 s6, 0x7fff
; GFX9-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v0, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v0, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v0
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v0, v17, v18, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v17, 16, v1
; GFX9-NEXT:    v_add_f32_e32 v17, 0x40c00000, v17
; GFX9-NEXT:    v_bfe_u32 v18, v17, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; GFX9-NEXT:    v_add3_u32 v18, v18, v17, s6
; GFX9-NEXT:    v_or_b32_e32 v19, 0x400000, v17
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v17, v17
; GFX9-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v17, v18, v19, vcc
; GFX9-NEXT:    v_bfe_u32 v18, v1, 16, 1
; GFX9-NEXT:    v_add3_u32 v18, v18, v1, s6
; GFX9-NEXT:    v_or_b32_e32 v19, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v18, v19, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v18, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v18, 0x40c00000, v18
; GFX9-NEXT:    v_bfe_u32 v19, v18, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; GFX9-NEXT:    v_add3_u32 v19, v19, v18, s6
; GFX9-NEXT:    v_or_b32_e32 v20, 0x400000, v18
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v18, v18
; GFX9-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v18, v19, v20, vcc
; GFX9-NEXT:    v_bfe_u32 v19, v2, 16, 1
; GFX9-NEXT:    v_add3_u32 v19, v19, v2, s6
; GFX9-NEXT:    v_or_b32_e32 v20, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v19, v20, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v19, 16, v3
; GFX9-NEXT:    v_add_f32_e32 v19, 0x40c00000, v19
; GFX9-NEXT:    v_bfe_u32 v20, v19, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; GFX9-NEXT:    v_add3_u32 v20, v20, v19, s6
; GFX9-NEXT:    v_or_b32_e32 v21, 0x400000, v19
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v19, v19
; GFX9-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GFX9-NEXT:    v_cndmask_b32_e32 v19, v20, v21, vcc
; GFX9-NEXT:    v_bfe_u32 v20, v3, 16, 1
; GFX9-NEXT:    v_add3_u32 v20, v20, v3, s6
; GFX9-NEXT:    v_or_b32_e32 v21, 0x400000, v3
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; GFX9-NEXT:    v_cndmask_b32_e32 v3, v20, v21, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v20, 16, v4
; GFX9-NEXT:    v_add_f32_e32 v20, 0x40c00000, v20
; GFX9-NEXT:    v_bfe_u32 v21, v20, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; GFX9-NEXT:    v_add3_u32 v21, v21, v20, s6
; GFX9-NEXT:    v_or_b32_e32 v22, 0x400000, v20
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v20, v20
; GFX9-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; GFX9-NEXT:    v_cndmask_b32_e32 v20, v21, v22, vcc
; GFX9-NEXT:    v_bfe_u32 v21, v4, 16, 1
; GFX9-NEXT:    v_add3_u32 v21, v21, v4, s6
; GFX9-NEXT:    v_or_b32_e32 v22, 0x400000, v4
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; GFX9-NEXT:    v_cndmask_b32_e32 v4, v21, v22, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v21, 16, v5
; GFX9-NEXT:    v_add_f32_e32 v21, 0x40c00000, v21
; GFX9-NEXT:    v_bfe_u32 v22, v21, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; GFX9-NEXT:    v_add3_u32 v22, v22, v21, s6
; GFX9-NEXT:    v_or_b32_e32 v23, 0x400000, v21
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v21, v21
; GFX9-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v21, v22, v23, vcc
; GFX9-NEXT:    v_bfe_u32 v22, v5, 16, 1
; GFX9-NEXT:    v_add3_u32 v22, v22, v5, s6
; GFX9-NEXT:    v_or_b32_e32 v23, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v5, v22, v23, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v22, 16, v6
; GFX9-NEXT:    v_add_f32_e32 v22, 0x40c00000, v22
; GFX9-NEXT:    v_bfe_u32 v23, v22, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; GFX9-NEXT:    v_add3_u32 v23, v23, v22, s6
; GFX9-NEXT:    v_or_b32_e32 v24, 0x400000, v22
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v22, v22
; GFX9-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GFX9-NEXT:    v_cndmask_b32_e32 v22, v23, v24, vcc
; GFX9-NEXT:    v_bfe_u32 v23, v6, 16, 1
; GFX9-NEXT:    v_add3_u32 v23, v23, v6, s6
; GFX9-NEXT:    v_or_b32_e32 v24, 0x400000, v6
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; GFX9-NEXT:    v_cndmask_b32_e32 v6, v23, v24, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v23, 16, v7
; GFX9-NEXT:    v_add_f32_e32 v23, 0x40c00000, v23
; GFX9-NEXT:    v_bfe_u32 v24, v23, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; GFX9-NEXT:    v_add3_u32 v24, v24, v23, s6
; GFX9-NEXT:    v_or_b32_e32 v25, 0x400000, v23
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v23, v23
; GFX9-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GFX9-NEXT:    v_cndmask_b32_e32 v23, v24, v25, vcc
; GFX9-NEXT:    v_bfe_u32 v24, v7, 16, 1
; GFX9-NEXT:    v_add3_u32 v24, v24, v7, s6
; GFX9-NEXT:    v_or_b32_e32 v25, 0x400000, v7
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; GFX9-NEXT:    v_cndmask_b32_e32 v7, v24, v25, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v24, 16, v8
; GFX9-NEXT:    v_add_f32_e32 v24, 0x40c00000, v24
; GFX9-NEXT:    v_bfe_u32 v25, v24, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v8, 0xffff0000, v8
; GFX9-NEXT:    v_add3_u32 v25, v25, v24, s6
; GFX9-NEXT:    v_or_b32_e32 v26, 0x400000, v24
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v24, v24
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_cndmask_b32_e32 v24, v25, v26, vcc
; GFX9-NEXT:    v_bfe_u32 v25, v8, 16, 1
; GFX9-NEXT:    v_add3_u32 v25, v25, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v26, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v25, v26, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v25, 16, v9
; GFX9-NEXT:    v_add_f32_e32 v25, 0x40c00000, v25
; GFX9-NEXT:    v_bfe_u32 v26, v25, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v9, 0xffff0000, v9
; GFX9-NEXT:    v_add3_u32 v26, v26, v25, s6
; GFX9-NEXT:    v_or_b32_e32 v27, 0x400000, v25
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v25, v25
; GFX9-NEXT:    v_add_f32_e32 v9, 0x40c00000, v9
; GFX9-NEXT:    v_cndmask_b32_e32 v25, v26, v27, vcc
; GFX9-NEXT:    v_bfe_u32 v26, v9, 16, 1
; GFX9-NEXT:    v_add3_u32 v26, v26, v9, s6
; GFX9-NEXT:    v_or_b32_e32 v27, 0x400000, v9
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v9, v9
; GFX9-NEXT:    v_cndmask_b32_e32 v9, v26, v27, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v26, 16, v10
; GFX9-NEXT:    v_add_f32_e32 v26, 0x40c00000, v26
; GFX9-NEXT:    v_bfe_u32 v27, v26, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v10, 0xffff0000, v10
; GFX9-NEXT:    v_add3_u32 v27, v27, v26, s6
; GFX9-NEXT:    v_or_b32_e32 v28, 0x400000, v26
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v26, v26
; GFX9-NEXT:    v_add_f32_e32 v10, 0x40c00000, v10
; GFX9-NEXT:    v_cndmask_b32_e32 v26, v27, v28, vcc
; GFX9-NEXT:    v_bfe_u32 v27, v10, 16, 1
; GFX9-NEXT:    v_add3_u32 v27, v27, v10, s6
; GFX9-NEXT:    v_or_b32_e32 v28, 0x400000, v10
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v10, v10
; GFX9-NEXT:    v_cndmask_b32_e32 v10, v27, v28, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v27, 16, v11
; GFX9-NEXT:    v_add_f32_e32 v27, 0x40c00000, v27
; GFX9-NEXT:    v_bfe_u32 v28, v27, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v11, 0xffff0000, v11
; GFX9-NEXT:    v_add3_u32 v28, v28, v27, s6
; GFX9-NEXT:    v_or_b32_e32 v29, 0x400000, v27
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v27, v27
; GFX9-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; GFX9-NEXT:    v_cndmask_b32_e32 v27, v28, v29, vcc
; GFX9-NEXT:    v_bfe_u32 v28, v11, 16, 1
; GFX9-NEXT:    v_add3_u32 v28, v28, v11, s6
; GFX9-NEXT:    v_or_b32_e32 v29, 0x400000, v11
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v11, v11
; GFX9-NEXT:    v_cndmask_b32_e32 v11, v28, v29, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v28, 16, v12
; GFX9-NEXT:    v_add_f32_e32 v28, 0x40c00000, v28
; GFX9-NEXT:    v_bfe_u32 v29, v28, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v12, 0xffff0000, v12
; GFX9-NEXT:    v_add3_u32 v29, v29, v28, s6
; GFX9-NEXT:    v_or_b32_e32 v30, 0x400000, v28
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v28, v28
; GFX9-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; GFX9-NEXT:    v_cndmask_b32_e32 v28, v29, v30, vcc
; GFX9-NEXT:    v_bfe_u32 v29, v12, 16, 1
; GFX9-NEXT:    v_add3_u32 v29, v29, v12, s6
; GFX9-NEXT:    v_or_b32_e32 v30, 0x400000, v12
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v12, v12
; GFX9-NEXT:    v_cndmask_b32_e32 v12, v29, v30, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v29, 16, v13
; GFX9-NEXT:    v_add_f32_e32 v29, 0x40c00000, v29
; GFX9-NEXT:    v_bfe_u32 v30, v29, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v13, 0xffff0000, v13
; GFX9-NEXT:    v_add3_u32 v30, v30, v29, s6
; GFX9-NEXT:    v_or_b32_e32 v31, 0x400000, v29
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v29, v29
; GFX9-NEXT:    v_add_f32_e32 v13, 0x40c00000, v13
; GFX9-NEXT:    v_cndmask_b32_e32 v29, v30, v31, vcc
; GFX9-NEXT:    v_bfe_u32 v30, v13, 16, 1
; GFX9-NEXT:    v_add3_u32 v30, v30, v13, s6
; GFX9-NEXT:    v_or_b32_e32 v31, 0x400000, v13
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v13, v13
; GFX9-NEXT:    v_cndmask_b32_e32 v13, v30, v31, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v30, 16, v14
; GFX9-NEXT:    v_add_f32_e32 v30, 0x40c00000, v30
; GFX9-NEXT:    v_bfe_u32 v31, v30, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v14, 0xffff0000, v14
; GFX9-NEXT:    v_add3_u32 v31, v31, v30, s6
; GFX9-NEXT:    v_or_b32_e32 v32, 0x400000, v30
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v30, v30
; GFX9-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; GFX9-NEXT:    v_cndmask_b32_e32 v30, v31, v32, vcc
; GFX9-NEXT:    v_bfe_u32 v31, v14, 16, 1
; GFX9-NEXT:    v_add3_u32 v31, v31, v14, s6
; GFX9-NEXT:    v_or_b32_e32 v32, 0x400000, v14
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v14, v14
; GFX9-NEXT:    v_cndmask_b32_e32 v14, v31, v32, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v31, 16, v15
; GFX9-NEXT:    v_add_f32_e32 v31, 0x40c00000, v31
; GFX9-NEXT:    v_bfe_u32 v32, v31, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v15, 0xffff0000, v15
; GFX9-NEXT:    v_add3_u32 v32, v32, v31, s6
; GFX9-NEXT:    v_or_b32_e32 v33, 0x400000, v31
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v31, v31
; GFX9-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; GFX9-NEXT:    v_cndmask_b32_e32 v31, v32, v33, vcc
; GFX9-NEXT:    v_bfe_u32 v32, v15, 16, 1
; GFX9-NEXT:    v_add3_u32 v32, v32, v15, s6
; GFX9-NEXT:    v_or_b32_e32 v33, 0x400000, v15
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v15, v15
; GFX9-NEXT:    v_cndmask_b32_e32 v15, v32, v33, vcc
; GFX9-NEXT:    s_mov_b32 s6, 0x7060302
; GFX9-NEXT:    v_perm_b32 v15, v15, v31, s6
; GFX9-NEXT:    v_perm_b32 v14, v14, v30, s6
; GFX9-NEXT:    v_perm_b32 v13, v13, v29, s6
; GFX9-NEXT:    v_perm_b32 v12, v12, v28, s6
; GFX9-NEXT:    v_perm_b32 v11, v11, v27, s6
; GFX9-NEXT:    v_perm_b32 v10, v10, v26, s6
; GFX9-NEXT:    v_perm_b32 v9, v9, v25, s6
; GFX9-NEXT:    v_perm_b32 v8, v8, v24, s6
; GFX9-NEXT:    v_perm_b32 v7, v7, v23, s6
; GFX9-NEXT:    v_perm_b32 v6, v6, v22, s6
; GFX9-NEXT:    v_perm_b32 v5, v5, v21, s6
; GFX9-NEXT:    v_perm_b32 v4, v4, v20, s6
; GFX9-NEXT:    v_perm_b32 v3, v3, v19, s6
; GFX9-NEXT:    v_perm_b32 v2, v2, v18, s6
; GFX9-NEXT:    v_perm_b32 v1, v1, v17, s6
; GFX9-NEXT:    v_perm_b32 v0, v0, v16, s6
; GFX9-NEXT:  .LBB39_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v32bf16_to_v32i16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB39_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_lshlrev_b32_e32 v17, 16, v1
; GFX11-NEXT:    v_lshlrev_b32_e32 v16, 16, v0
; GFX11-NEXT:    v_lshlrev_b32_e32 v24, 16, v5
; GFX11-NEXT:    v_lshlrev_b32_e32 v26, 16, v7
; GFX11-NEXT:    v_lshlrev_b32_e32 v28, 16, v9
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_dual_add_f32 v17, 0x40c00000, v17 :: v_dual_add_f32 v16, 0x40c00000, v16
; GFX11-NEXT:    v_lshlrev_b32_e32 v30, 16, v11
; GFX11-NEXT:    v_dual_add_f32 v24, 0x40c00000, v24 :: v_dual_lshlrev_b32 v25, 16, v6
; GFX11-NEXT:    v_bfe_u32 v21, v17, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_bfe_u32 v19, v16, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v16
; GFX11-NEXT:    v_add_f32_e32 v25, 0x40c00000, v25
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v16, v16
; GFX11-NEXT:    v_add3_u32 v21, v21, v17, 0x7fff
; GFX11-NEXT:    v_add3_u32 v19, v19, v16, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; GFX11-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; GFX11-NEXT:    v_dual_add_f32 v26, 0x40c00000, v26 :: v_dual_lshlrev_b32 v27, 16, v8
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-NEXT:    v_cndmask_b32_e32 v16, v19, v22, vcc_lo
; GFX11-NEXT:    v_or_b32_e32 v19, 0x400000, v17
; GFX11-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX11-NEXT:    v_dual_add_f32 v1, 0x40c00000, v1 :: v_dual_lshlrev_b32 v22, 16, v3
; GFX11-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; GFX11-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; GFX11-NEXT:    v_and_b32_e32 v8, 0xffff0000, v8
; GFX11-NEXT:    v_add_f32_e32 v27, 0x40c00000, v27
; GFX11-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GFX11-NEXT:    v_lshlrev_b32_e32 v29, 16, v10
; GFX11-NEXT:    v_bfe_u32 v20, v0, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v23, 0x400000, v0
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX11-NEXT:    v_dual_add_f32 v28, 0x40c00000, v28 :: v_dual_add_f32 v29, 0x40c00000, v29
; GFX11-NEXT:    v_add3_u32 v20, v20, v0, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v10, 0xffff0000, v10
; GFX11-NEXT:    v_dual_add_f32 v30, 0x40c00000, v30 :: v_dual_lshlrev_b32 v31, 16, v12
; GFX11-NEXT:    v_and_b32_e32 v12, 0xffff0000, v12
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_dual_cndmask_b32 v0, v20, v23 :: v_dual_lshlrev_b32 v23, 16, v4
; GFX11-NEXT:    v_bfe_u32 v20, v1, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v17, v17
; GFX11-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; GFX11-NEXT:    v_dual_add_f32 v10, 0x40c00000, v10 :: v_dual_add_f32 v23, 0x40c00000, v23
; GFX11-NEXT:    v_perm_b32 v0, v0, v16, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v17, v21, v19, vcc_lo
; GFX11-NEXT:    v_add3_u32 v19, v20, v1, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-NEXT:    v_lshlrev_b32_e32 v18, 16, v2
; GFX11-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; GFX11-NEXT:    v_dual_add_f32 v4, 0x40c00000, v4 :: v_dual_add_f32 v31, 0x40c00000, v31
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_dual_cndmask_b32 v1, v19, v20 :: v_dual_add_f32 v18, 0x40c00000, v18
; GFX11-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GFX11-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; GFX11-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; GFX11-NEXT:    v_add_f32_e32 v22, 0x40c00000, v22
; GFX11-NEXT:    v_bfe_u32 v21, v18, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v18
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX11-NEXT:    v_or_b32_e32 v33, 0x400000, v31
; GFX11-NEXT:    v_add3_u32 v19, v21, v18, 0x7fff
; GFX11-NEXT:    v_bfe_u32 v21, v2, 16, 1
; GFX11-NEXT:    v_bfe_u32 v34, v12, 16, 1
; GFX11-NEXT:    v_perm_b32 v1, v1, v17, 0x7060302
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_dual_cndmask_b32 v18, v19, v20 :: v_dual_and_b32 v7, 0xffff0000, v7
; GFX11-NEXT:    v_add3_u32 v19, v21, v2, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v2
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-NEXT:    v_bfe_u32 v21, v22, 16, 1
; GFX11-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GFX11-NEXT:    v_and_b32_e32 v9, 0xffff0000, v9
; GFX11-NEXT:    v_dual_cndmask_b32 v2, v19, v20 :: v_dual_and_b32 v11, 0xffff0000, v11
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-NEXT:    v_add3_u32 v19, v21, v22, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v22
; GFX11-NEXT:    v_bfe_u32 v21, v3, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v22, v22
; GFX11-NEXT:    v_bfe_u32 v22, v23, 16, 1
; GFX11-NEXT:    v_add_f32_e32 v9, 0x40c00000, v9
; GFX11-NEXT:    v_perm_b32 v2, v2, v18, 0x7060302
; GFX11-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; GFX11-NEXT:    v_cndmask_b32_e32 v19, v19, v20, vcc_lo
; GFX11-NEXT:    v_add3_u32 v20, v21, v3, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v3
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-NEXT:    v_or_b32_e32 v32, 0x400000, v11
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-NEXT:    v_cndmask_b32_e32 v3, v20, v21, vcc_lo
; GFX11-NEXT:    v_add3_u32 v20, v22, v23, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v23
; GFX11-NEXT:    v_bfe_u32 v22, v4, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v23, v23
; GFX11-NEXT:    v_bfe_u32 v23, v24, 16, 1
; GFX11-NEXT:    v_perm_b32 v3, v3, v19, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v20, v20, v21, vcc_lo
; GFX11-NEXT:    v_add3_u32 v21, v22, v4, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v4
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-NEXT:    v_cndmask_b32_e32 v4, v21, v22, vcc_lo
; GFX11-NEXT:    v_add3_u32 v21, v23, v24, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v24
; GFX11-NEXT:    v_bfe_u32 v23, v5, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v24, v24
; GFX11-NEXT:    v_bfe_u32 v24, v25, 16, 1
; GFX11-NEXT:    v_perm_b32 v4, v4, v20, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v21, v21, v22, vcc_lo
; GFX11-NEXT:    v_add3_u32 v22, v23, v5, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v23, 0x400000, v5
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-NEXT:    v_cndmask_b32_e32 v5, v22, v23, vcc_lo
; GFX11-NEXT:    v_add3_u32 v22, v24, v25, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v23, 0x400000, v25
; GFX11-NEXT:    v_bfe_u32 v24, v6, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v25, v25
; GFX11-NEXT:    v_bfe_u32 v25, v26, 16, 1
; GFX11-NEXT:    v_perm_b32 v5, v5, v21, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v22, v22, v23, vcc_lo
; GFX11-NEXT:    v_add3_u32 v23, v24, v6, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v24, 0x400000, v6
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-NEXT:    v_cndmask_b32_e32 v6, v23, v24, vcc_lo
; GFX11-NEXT:    v_add3_u32 v23, v25, v26, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v24, 0x400000, v26
; GFX11-NEXT:    v_bfe_u32 v25, v7, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v26, v26
; GFX11-NEXT:    v_bfe_u32 v26, v27, 16, 1
; GFX11-NEXT:    v_perm_b32 v6, v6, v22, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v23, v23, v24, vcc_lo
; GFX11-NEXT:    v_add3_u32 v24, v25, v7, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v25, 0x400000, v7
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-NEXT:    v_cndmask_b32_e32 v7, v24, v25, vcc_lo
; GFX11-NEXT:    v_add3_u32 v24, v26, v27, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v25, 0x400000, v27
; GFX11-NEXT:    v_bfe_u32 v26, v8, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v27, v27
; GFX11-NEXT:    v_bfe_u32 v27, v28, 16, 1
; GFX11-NEXT:    v_perm_b32 v7, v7, v23, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v24, v24, v25, vcc_lo
; GFX11-NEXT:    v_add3_u32 v25, v26, v8, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v26, 0x400000, v8
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-NEXT:    v_cndmask_b32_e32 v8, v25, v26, vcc_lo
; GFX11-NEXT:    v_add3_u32 v25, v27, v28, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v26, 0x400000, v28
; GFX11-NEXT:    v_bfe_u32 v27, v9, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v28, v28
; GFX11-NEXT:    v_bfe_u32 v28, v29, 16, 1
; GFX11-NEXT:    v_perm_b32 v8, v8, v24, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v25, v25, v26, vcc_lo
; GFX11-NEXT:    v_add3_u32 v26, v27, v9, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v27, 0x400000, v9
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-NEXT:    v_cndmask_b32_e32 v9, v26, v27, vcc_lo
; GFX11-NEXT:    v_add3_u32 v26, v28, v29, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v27, 0x400000, v29
; GFX11-NEXT:    v_bfe_u32 v28, v10, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v29, v29
; GFX11-NEXT:    v_bfe_u32 v29, v30, 16, 1
; GFX11-NEXT:    v_perm_b32 v9, v9, v25, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v26, v26, v27, vcc_lo
; GFX11-NEXT:    v_add3_u32 v27, v28, v10, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v28, 0x400000, v10
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-NEXT:    v_cndmask_b32_e32 v10, v27, v28, vcc_lo
; GFX11-NEXT:    v_add3_u32 v27, v29, v30, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v28, 0x400000, v30
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v30, v30
; GFX11-NEXT:    v_bfe_u32 v30, v31, 16, 1
; GFX11-NEXT:    v_bfe_u32 v29, v11, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_dual_cndmask_b32 v27, v27, v28 :: v_dual_lshlrev_b32 v28, 16, v13
; GFX11-NEXT:    v_add3_u32 v30, v30, v31, 0x7fff
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v31, v31
; GFX11-NEXT:    v_and_b32_e32 v13, 0xffff0000, v13
; GFX11-NEXT:    v_add3_u32 v31, v34, v12, 0x7fff
; GFX11-NEXT:    v_add_f32_e32 v28, 0x40c00000, v28
; GFX11-NEXT:    v_add3_u32 v29, v29, v11, 0x7fff
; GFX11-NEXT:    v_cndmask_b32_e32 v30, v30, v33, vcc_lo
; GFX11-NEXT:    v_or_b32_e32 v33, 0x400000, v12
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v12, v12
; GFX11-NEXT:    v_bfe_u32 v35, v28, 16, 1
; GFX11-NEXT:    v_add_f32_e32 v13, 0x40c00000, v13
; GFX11-NEXT:    v_or_b32_e32 v36, 0x400000, v28
; GFX11-NEXT:    v_cndmask_b32_e32 v12, v31, v33, vcc_lo
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-NEXT:    v_add3_u32 v34, v35, v28, 0x7fff
; GFX11-NEXT:    v_lshlrev_b32_e32 v35, 16, v14
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v28, v28
; GFX11-NEXT:    v_and_b32_e32 v14, 0xffff0000, v14
; GFX11-NEXT:    v_bfe_u32 v37, v13, 16, 1
; GFX11-NEXT:    v_perm_b32 v10, v10, v26, 0x7060302
; GFX11-NEXT:    v_dual_add_f32 v31, 0x40c00000, v35 :: v_dual_cndmask_b32 v28, v34, v36
; GFX11-NEXT:    v_lshlrev_b32_e32 v34, 16, v15
; GFX11-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; GFX11-NEXT:    v_add3_u32 v33, v37, v13, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-NEXT:    v_bfe_u32 v35, v31, 16, 1
; GFX11-NEXT:    v_and_b32_e32 v15, 0xffff0000, v15
; GFX11-NEXT:    v_add_f32_e32 v34, 0x40c00000, v34
; GFX11-NEXT:    v_or_b32_e32 v37, 0x400000, v31
; GFX11-NEXT:    v_bfe_u32 v38, v14, 16, 1
; GFX11-NEXT:    v_add3_u32 v35, v35, v31, 0x7fff
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v31, v31
; GFX11-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; GFX11-NEXT:    v_bfe_u32 v39, v34, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v48, 0x400000, v34
; GFX11-NEXT:    v_or_b32_e32 v36, 0x400000, v13
; GFX11-NEXT:    v_cndmask_b32_e32 v31, v35, v37, vcc_lo
; GFX11-NEXT:    v_add3_u32 v37, v38, v14, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v38, 0x400000, v14
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v14, v14
; GFX11-NEXT:    v_bfe_u32 v35, v15, 16, 1
; GFX11-NEXT:    v_add3_u32 v39, v39, v34, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v49, 0x400000, v15
; GFX11-NEXT:    v_cndmask_b32_e32 v14, v37, v38, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v34, v34
; GFX11-NEXT:    v_add3_u32 v35, v35, v15, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_perm_b32 v14, v14, v31, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v34, v39, v48, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v15, v15
; GFX11-NEXT:    v_cndmask_b32_e32 v15, v35, v49, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v13, v13
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_3) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_perm_b32 v15, v15, v34, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v13, v33, v36, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v11, v11
; GFX11-NEXT:    v_perm_b32 v12, v12, v30, 0x7060302
; GFX11-NEXT:    v_perm_b32 v13, v13, v28, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v11, v29, v32, vcc_lo
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-NEXT:    v_perm_b32 v11, v11, v27, 0x7060302
; GFX11-NEXT:  .LBB39_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <32 x bfloat> %a, splat (bfloat 0xR40C0)
  %a2 = bitcast <32 x bfloat> %a1 to <32 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <32 x bfloat> %a to <32 x i16>
  br label %end

end:
  %phi = phi <32 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x i16> %phi
}

define <32 x bfloat> @v_bitcast_v32f16_to_v32bf16(<32 x half> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v32f16_to_v32bf16:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:68 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:64 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:60 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:56 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:52 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:48 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:44 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:40 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v59, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v60, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v61, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v62, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v63, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_load_dword v31, off, s[0:3], s32
; GCN-NEXT:    s_waitcnt expcnt(0)
; GCN-NEXT:    buffer_load_dword v63, off, s[0:3], s32 offset:4
; GCN-NEXT:    v_cvt_f16_f32_e32 v32, v0
; GCN-NEXT:    v_cvt_f16_f32_e32 v33, v1
; GCN-NEXT:    v_cvt_f16_f32_e32 v34, v2
; GCN-NEXT:    v_cvt_f16_f32_e32 v35, v3
; GCN-NEXT:    v_cvt_f16_f32_e32 v36, v4
; GCN-NEXT:    v_cvt_f16_f32_e32 v37, v5
; GCN-NEXT:    v_cvt_f16_f32_e32 v38, v6
; GCN-NEXT:    v_cvt_f16_f32_e32 v39, v7
; GCN-NEXT:    v_cvt_f16_f32_e32 v48, v8
; GCN-NEXT:    v_cvt_f16_f32_e32 v49, v9
; GCN-NEXT:    v_cvt_f16_f32_e32 v50, v10
; GCN-NEXT:    v_cvt_f16_f32_e32 v51, v11
; GCN-NEXT:    v_cvt_f16_f32_e32 v52, v12
; GCN-NEXT:    v_cvt_f16_f32_e32 v53, v13
; GCN-NEXT:    v_cvt_f16_f32_e32 v54, v14
; GCN-NEXT:    v_cvt_f16_f32_e32 v55, v15
; GCN-NEXT:    v_cvt_f16_f32_e32 v40, v16
; GCN-NEXT:    v_cvt_f16_f32_e32 v41, v17
; GCN-NEXT:    v_cvt_f16_f32_e32 v42, v18
; GCN-NEXT:    v_cvt_f16_f32_e32 v43, v19
; GCN-NEXT:    v_cvt_f16_f32_e32 v44, v20
; GCN-NEXT:    v_cvt_f16_f32_e32 v45, v21
; GCN-NEXT:    v_cvt_f16_f32_e32 v46, v22
; GCN-NEXT:    v_cvt_f16_f32_e32 v47, v23
; GCN-NEXT:    v_cvt_f16_f32_e32 v56, v24
; GCN-NEXT:    v_cvt_f16_f32_e32 v57, v25
; GCN-NEXT:    v_cvt_f16_f32_e32 v58, v26
; GCN-NEXT:    v_cvt_f16_f32_e32 v59, v27
; GCN-NEXT:    v_cvt_f16_f32_e32 v60, v28
; GCN-NEXT:    v_cvt_f16_f32_e32 v61, v29
; GCN-NEXT:    v_cvt_f16_f32_e32 v62, v30
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v63
; GCN-NEXT:    v_cvt_f16_f32_e32 v63, v31
; GCN-NEXT:    ; implicit-def: $vgpr0
; GCN-NEXT:    ; implicit-def: $vgpr1
; GCN-NEXT:    ; implicit-def: $vgpr2
; GCN-NEXT:    ; implicit-def: $vgpr3
; GCN-NEXT:    ; implicit-def: $vgpr4
; GCN-NEXT:    ; implicit-def: $vgpr5
; GCN-NEXT:    ; implicit-def: $vgpr6
; GCN-NEXT:    ; implicit-def: $vgpr7
; GCN-NEXT:    ; implicit-def: $vgpr8
; GCN-NEXT:    ; implicit-def: $vgpr9
; GCN-NEXT:    ; implicit-def: $vgpr10
; GCN-NEXT:    ; implicit-def: $vgpr11
; GCN-NEXT:    ; implicit-def: $vgpr12
; GCN-NEXT:    ; implicit-def: $vgpr13
; GCN-NEXT:    ; implicit-def: $vgpr14
; GCN-NEXT:    ; implicit-def: $vgpr15
; GCN-NEXT:    ; implicit-def: $vgpr16
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr18
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr20
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr22
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr24
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr26
; GCN-NEXT:    ; implicit-def: $vgpr27
; GCN-NEXT:    ; implicit-def: $vgpr28
; GCN-NEXT:    ; implicit-def: $vgpr29
; GCN-NEXT:    ; implicit-def: $vgpr30
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB40_2
; GCN-NEXT:  ; %bb.1: ; %cmp.false
; GCN-NEXT:    v_lshlrev_b32_e32 v0, 16, v32
; GCN-NEXT:    v_lshlrev_b32_e32 v1, 16, v33
; GCN-NEXT:    v_lshlrev_b32_e32 v2, 16, v34
; GCN-NEXT:    v_lshlrev_b32_e32 v3, 16, v35
; GCN-NEXT:    v_lshlrev_b32_e32 v4, 16, v36
; GCN-NEXT:    v_lshlrev_b32_e32 v5, 16, v37
; GCN-NEXT:    v_lshlrev_b32_e32 v6, 16, v38
; GCN-NEXT:    v_lshlrev_b32_e32 v7, 16, v39
; GCN-NEXT:    v_lshlrev_b32_e32 v8, 16, v48
; GCN-NEXT:    v_lshlrev_b32_e32 v9, 16, v49
; GCN-NEXT:    v_lshlrev_b32_e32 v10, 16, v50
; GCN-NEXT:    v_lshlrev_b32_e32 v11, 16, v51
; GCN-NEXT:    v_lshlrev_b32_e32 v12, 16, v52
; GCN-NEXT:    v_lshlrev_b32_e32 v13, 16, v53
; GCN-NEXT:    v_lshlrev_b32_e32 v14, 16, v54
; GCN-NEXT:    v_lshlrev_b32_e32 v15, 16, v55
; GCN-NEXT:    v_lshlrev_b32_e32 v16, 16, v40
; GCN-NEXT:    v_lshlrev_b32_e32 v17, 16, v41
; GCN-NEXT:    v_lshlrev_b32_e32 v18, 16, v42
; GCN-NEXT:    v_lshlrev_b32_e32 v19, 16, v43
; GCN-NEXT:    v_lshlrev_b32_e32 v20, 16, v44
; GCN-NEXT:    v_lshlrev_b32_e32 v21, 16, v45
; GCN-NEXT:    v_lshlrev_b32_e32 v22, 16, v46
; GCN-NEXT:    v_lshlrev_b32_e32 v23, 16, v47
; GCN-NEXT:    v_lshlrev_b32_e32 v24, 16, v56
; GCN-NEXT:    v_lshlrev_b32_e32 v25, 16, v57
; GCN-NEXT:    v_lshlrev_b32_e32 v26, 16, v58
; GCN-NEXT:    v_lshlrev_b32_e32 v27, 16, v59
; GCN-NEXT:    v_lshlrev_b32_e32 v28, 16, v60
; GCN-NEXT:    v_lshlrev_b32_e32 v29, 16, v61
; GCN-NEXT:    v_lshlrev_b32_e32 v30, 16, v62
; GCN-NEXT:    v_lshlrev_b32_e32 v31, 16, v63
; GCN-NEXT:    ; implicit-def: $vgpr32
; GCN-NEXT:    ; implicit-def: $vgpr33
; GCN-NEXT:    ; implicit-def: $vgpr34
; GCN-NEXT:    ; implicit-def: $vgpr35
; GCN-NEXT:    ; implicit-def: $vgpr36
; GCN-NEXT:    ; implicit-def: $vgpr37
; GCN-NEXT:    ; implicit-def: $vgpr38
; GCN-NEXT:    ; implicit-def: $vgpr39
; GCN-NEXT:    ; implicit-def: $vgpr48
; GCN-NEXT:    ; implicit-def: $vgpr49
; GCN-NEXT:    ; implicit-def: $vgpr50
; GCN-NEXT:    ; implicit-def: $vgpr51
; GCN-NEXT:    ; implicit-def: $vgpr52
; GCN-NEXT:    ; implicit-def: $vgpr53
; GCN-NEXT:    ; implicit-def: $vgpr54
; GCN-NEXT:    ; implicit-def: $vgpr55
; GCN-NEXT:    ; implicit-def: $vgpr40
; GCN-NEXT:    ; implicit-def: $vgpr41
; GCN-NEXT:    ; implicit-def: $vgpr42
; GCN-NEXT:    ; implicit-def: $vgpr43
; GCN-NEXT:    ; implicit-def: $vgpr44
; GCN-NEXT:    ; implicit-def: $vgpr45
; GCN-NEXT:    ; implicit-def: $vgpr46
; GCN-NEXT:    ; implicit-def: $vgpr47
; GCN-NEXT:    ; implicit-def: $vgpr56
; GCN-NEXT:    ; implicit-def: $vgpr57
; GCN-NEXT:    ; implicit-def: $vgpr58
; GCN-NEXT:    ; implicit-def: $vgpr59
; GCN-NEXT:    ; implicit-def: $vgpr60
; GCN-NEXT:    ; implicit-def: $vgpr61
; GCN-NEXT:    ; implicit-def: $vgpr62
; GCN-NEXT:    ; implicit-def: $vgpr63
; GCN-NEXT:  .LBB40_2: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB40_4
; GCN-NEXT:  ; %bb.3: ; %cmp.true
; GCN-NEXT:    v_cvt_f32_f16_e32 v0, v63
; GCN-NEXT:    v_cvt_f32_f16_e32 v1, v62
; GCN-NEXT:    v_cvt_f32_f16_e32 v2, v61
; GCN-NEXT:    v_cvt_f32_f16_e32 v3, v60
; GCN-NEXT:    v_cvt_f32_f16_e32 v4, v59
; GCN-NEXT:    v_cvt_f32_f16_e32 v5, v58
; GCN-NEXT:    v_cvt_f32_f16_e32 v6, v57
; GCN-NEXT:    v_cvt_f32_f16_e32 v7, v56
; GCN-NEXT:    v_cvt_f32_f16_e32 v8, v47
; GCN-NEXT:    v_cvt_f32_f16_e32 v9, v46
; GCN-NEXT:    v_cvt_f32_f16_e32 v10, v45
; GCN-NEXT:    v_cvt_f32_f16_e32 v11, v44
; GCN-NEXT:    v_cvt_f32_f16_e32 v12, v43
; GCN-NEXT:    v_cvt_f32_f16_e32 v13, v42
; GCN-NEXT:    v_cvt_f32_f16_e32 v14, v41
; GCN-NEXT:    v_cvt_f32_f16_e32 v15, v40
; GCN-NEXT:    v_cvt_f32_f16_e32 v16, v55
; GCN-NEXT:    v_cvt_f32_f16_e32 v17, v54
; GCN-NEXT:    v_cvt_f32_f16_e32 v18, v53
; GCN-NEXT:    v_cvt_f32_f16_e32 v19, v52
; GCN-NEXT:    v_cvt_f32_f16_e32 v20, v51
; GCN-NEXT:    v_cvt_f32_f16_e32 v21, v50
; GCN-NEXT:    v_cvt_f32_f16_e32 v22, v49
; GCN-NEXT:    v_cvt_f32_f16_e32 v23, v48
; GCN-NEXT:    v_cvt_f32_f16_e32 v24, v39
; GCN-NEXT:    v_cvt_f32_f16_e32 v25, v38
; GCN-NEXT:    v_cvt_f32_f16_e32 v26, v37
; GCN-NEXT:    v_cvt_f32_f16_e32 v27, v36
; GCN-NEXT:    v_cvt_f32_f16_e32 v28, v35
; GCN-NEXT:    v_cvt_f32_f16_e32 v29, v34
; GCN-NEXT:    v_cvt_f32_f16_e32 v30, v33
; GCN-NEXT:    v_cvt_f32_f16_e32 v31, v32
; GCN-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; GCN-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; GCN-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; GCN-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; GCN-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; GCN-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; GCN-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; GCN-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; GCN-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; GCN-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; GCN-NEXT:    v_add_f32_e32 v10, 0x38000000, v10
; GCN-NEXT:    v_add_f32_e32 v11, 0x38000000, v11
; GCN-NEXT:    v_add_f32_e32 v12, 0x38000000, v12
; GCN-NEXT:    v_add_f32_e32 v13, 0x38000000, v13
; GCN-NEXT:    v_add_f32_e32 v14, 0x38000000, v14
; GCN-NEXT:    v_add_f32_e32 v15, 0x38000000, v15
; GCN-NEXT:    v_add_f32_e32 v16, 0x38000000, v16
; GCN-NEXT:    v_add_f32_e32 v17, 0x38000000, v17
; GCN-NEXT:    v_add_f32_e32 v18, 0x38000000, v18
; GCN-NEXT:    v_add_f32_e32 v19, 0x38000000, v19
; GCN-NEXT:    v_add_f32_e32 v20, 0x38000000, v20
; GCN-NEXT:    v_add_f32_e32 v21, 0x38000000, v21
; GCN-NEXT:    v_add_f32_e32 v22, 0x38000000, v22
; GCN-NEXT:    v_add_f32_e32 v23, 0x38000000, v23
; GCN-NEXT:    v_add_f32_e32 v24, 0x38000000, v24
; GCN-NEXT:    v_add_f32_e32 v25, 0x38000000, v25
; GCN-NEXT:    v_add_f32_e32 v26, 0x38000000, v26
; GCN-NEXT:    v_add_f32_e32 v27, 0x38000000, v27
; GCN-NEXT:    v_add_f32_e32 v28, 0x38000000, v28
; GCN-NEXT:    v_add_f32_e32 v29, 0x38000000, v29
; GCN-NEXT:    v_add_f32_e32 v30, 0x38000000, v30
; GCN-NEXT:    v_add_f32_e32 v31, 0x38000000, v31
; GCN-NEXT:    v_cvt_f16_f32_e32 v31, v31
; GCN-NEXT:    v_cvt_f16_f32_e32 v30, v30
; GCN-NEXT:    v_cvt_f16_f32_e32 v29, v29
; GCN-NEXT:    v_cvt_f16_f32_e32 v28, v28
; GCN-NEXT:    v_cvt_f16_f32_e32 v27, v27
; GCN-NEXT:    v_cvt_f16_f32_e32 v26, v26
; GCN-NEXT:    v_cvt_f16_f32_e32 v25, v25
; GCN-NEXT:    v_cvt_f16_f32_e32 v24, v24
; GCN-NEXT:    v_cvt_f16_f32_e32 v23, v23
; GCN-NEXT:    v_cvt_f16_f32_e32 v22, v22
; GCN-NEXT:    v_cvt_f16_f32_e32 v21, v21
; GCN-NEXT:    v_cvt_f16_f32_e32 v20, v20
; GCN-NEXT:    v_cvt_f16_f32_e32 v19, v19
; GCN-NEXT:    v_cvt_f16_f32_e32 v18, v18
; GCN-NEXT:    v_cvt_f16_f32_e32 v17, v17
; GCN-NEXT:    v_cvt_f16_f32_e32 v16, v16
; GCN-NEXT:    v_cvt_f16_f32_e32 v32, v15
; GCN-NEXT:    v_cvt_f16_f32_e32 v33, v14
; GCN-NEXT:    v_cvt_f16_f32_e32 v34, v13
; GCN-NEXT:    v_cvt_f16_f32_e32 v35, v12
; GCN-NEXT:    v_cvt_f16_f32_e32 v36, v11
; GCN-NEXT:    v_cvt_f16_f32_e32 v37, v10
; GCN-NEXT:    v_cvt_f16_f32_e32 v38, v9
; GCN-NEXT:    v_cvt_f16_f32_e32 v39, v8
; GCN-NEXT:    v_cvt_f16_f32_e32 v48, v7
; GCN-NEXT:    v_cvt_f16_f32_e32 v49, v6
; GCN-NEXT:    v_cvt_f16_f32_e32 v50, v5
; GCN-NEXT:    v_cvt_f16_f32_e32 v51, v4
; GCN-NEXT:    v_cvt_f16_f32_e32 v52, v3
; GCN-NEXT:    v_cvt_f16_f32_e32 v53, v2
; GCN-NEXT:    v_cvt_f16_f32_e32 v54, v1
; GCN-NEXT:    v_cvt_f16_f32_e32 v55, v0
; GCN-NEXT:    v_lshlrev_b32_e32 v0, 16, v31
; GCN-NEXT:    v_lshlrev_b32_e32 v1, 16, v30
; GCN-NEXT:    v_lshlrev_b32_e32 v2, 16, v29
; GCN-NEXT:    v_lshlrev_b32_e32 v3, 16, v28
; GCN-NEXT:    v_lshlrev_b32_e32 v4, 16, v27
; GCN-NEXT:    v_lshlrev_b32_e32 v5, 16, v26
; GCN-NEXT:    v_lshlrev_b32_e32 v6, 16, v25
; GCN-NEXT:    v_lshlrev_b32_e32 v7, 16, v24
; GCN-NEXT:    v_lshlrev_b32_e32 v8, 16, v23
; GCN-NEXT:    v_lshlrev_b32_e32 v9, 16, v22
; GCN-NEXT:    v_lshlrev_b32_e32 v10, 16, v21
; GCN-NEXT:    v_lshlrev_b32_e32 v11, 16, v20
; GCN-NEXT:    v_lshlrev_b32_e32 v12, 16, v19
; GCN-NEXT:    v_lshlrev_b32_e32 v13, 16, v18
; GCN-NEXT:    v_lshlrev_b32_e32 v14, 16, v17
; GCN-NEXT:    v_lshlrev_b32_e32 v15, 16, v16
; GCN-NEXT:    v_lshlrev_b32_e32 v16, 16, v32
; GCN-NEXT:    v_lshlrev_b32_e32 v17, 16, v33
; GCN-NEXT:    v_lshlrev_b32_e32 v18, 16, v34
; GCN-NEXT:    v_lshlrev_b32_e32 v19, 16, v35
; GCN-NEXT:    v_lshlrev_b32_e32 v20, 16, v36
; GCN-NEXT:    v_lshlrev_b32_e32 v21, 16, v37
; GCN-NEXT:    v_lshlrev_b32_e32 v22, 16, v38
; GCN-NEXT:    v_lshlrev_b32_e32 v23, 16, v39
; GCN-NEXT:    v_lshlrev_b32_e32 v24, 16, v48
; GCN-NEXT:    v_lshlrev_b32_e32 v25, 16, v49
; GCN-NEXT:    v_lshlrev_b32_e32 v26, 16, v50
; GCN-NEXT:    v_lshlrev_b32_e32 v27, 16, v51
; GCN-NEXT:    v_lshlrev_b32_e32 v28, 16, v52
; GCN-NEXT:    v_lshlrev_b32_e32 v29, 16, v53
; GCN-NEXT:    v_lshlrev_b32_e32 v30, 16, v54
; GCN-NEXT:    v_lshlrev_b32_e32 v31, 16, v55
; GCN-NEXT:  .LBB40_4: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    buffer_load_dword v63, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v62, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v61, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v60, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v57, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:40 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:44 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:48 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:52 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:56 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:60 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v32f16_to_v32bf16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB40_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v17, 0x200
; VI-NEXT:    v_add_f16_e32 v19, 0x200, v15
; VI-NEXT:    v_add_f16_sdwa v15, v15, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v15, v19, v15
; VI-NEXT:    v_add_f16_e32 v19, 0x200, v14
; VI-NEXT:    v_add_f16_sdwa v14, v14, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v14, v19, v14
; VI-NEXT:    v_add_f16_e32 v19, 0x200, v13
; VI-NEXT:    v_add_f16_sdwa v13, v13, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v13, v19, v13
; VI-NEXT:    v_add_f16_e32 v19, 0x200, v12
; VI-NEXT:    v_add_f16_sdwa v12, v12, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v12, v19, v12
; VI-NEXT:    v_add_f16_e32 v19, 0x200, v11
; VI-NEXT:    v_add_f16_sdwa v11, v11, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v11, v19, v11
; VI-NEXT:    v_add_f16_e32 v19, 0x200, v10
; VI-NEXT:    v_add_f16_sdwa v10, v10, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v10, v19, v10
; VI-NEXT:    v_add_f16_e32 v19, 0x200, v9
; VI-NEXT:    v_add_f16_sdwa v9, v9, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v9, v19, v9
; VI-NEXT:    v_add_f16_e32 v19, 0x200, v8
; VI-NEXT:    v_add_f16_sdwa v8, v8, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v8, v19, v8
; VI-NEXT:    v_add_f16_e32 v19, 0x200, v7
; VI-NEXT:    v_add_f16_sdwa v7, v7, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v7, v19, v7
; VI-NEXT:    v_add_f16_e32 v19, 0x200, v6
; VI-NEXT:    v_add_f16_sdwa v6, v6, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v6, v19, v6
; VI-NEXT:    v_add_f16_e32 v19, 0x200, v5
; VI-NEXT:    v_add_f16_sdwa v5, v5, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v5, v19, v5
; VI-NEXT:    v_add_f16_e32 v19, 0x200, v4
; VI-NEXT:    v_add_f16_sdwa v4, v4, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v16, 0x200, v0
; VI-NEXT:    v_add_f16_sdwa v0, v0, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v18, 0x200, v1
; VI-NEXT:    v_add_f16_sdwa v1, v1, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v4, v19, v4
; VI-NEXT:    v_add_f16_e32 v19, 0x200, v2
; VI-NEXT:    v_add_f16_sdwa v2, v2, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_sdwa v17, v3, v17 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v3, 0x200, v3
; VI-NEXT:    v_or_b32_e32 v3, v3, v17
; VI-NEXT:    v_or_b32_e32 v2, v19, v2
; VI-NEXT:    v_or_b32_e32 v1, v18, v1
; VI-NEXT:    v_or_b32_e32 v0, v16, v0
; VI-NEXT:  .LBB40_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v32f16_to_v32bf16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB40_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    s_movk_i32 s6, 0x200
; GFX9-NEXT:    v_pk_add_f16 v15, v15, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v14, v14, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v13, v13, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v12, v12, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v11, v11, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v10, v10, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v9, v9, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v8, v8, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v7, v7, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, v6, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v5, v5, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v4, v4, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v3, v3, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v2, v2, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v1, v1, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v0, v0, s6 op_sel_hi:[1,0]
; GFX9-NEXT:  .LBB40_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v32f16_to_v32bf16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB40_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_pk_add_f16 v15, 0x200, v15 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v14, 0x200, v14 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v13, 0x200, v13 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v12, 0x200, v12 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v11, 0x200, v11 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v10, 0x200, v10 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v9, 0x200, v9 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v8, 0x200, v8 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v7, 0x200, v7 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v6, 0x200, v6 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v5, 0x200, v5 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v4, 0x200, v4 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v3, 0x200, v3 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v2, 0x200, v2 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v1, 0x200, v1 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v0, 0x200, v0 op_sel_hi:[0,1]
; GFX11-NEXT:  .LBB40_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <32 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <32 x half> %a1 to <32 x bfloat>
  br label %end

cmp.false:
  %a3 = bitcast <32 x half> %a to <32 x bfloat>
  br label %end

end:
  %phi = phi <32 x bfloat> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x bfloat> %phi
}

define <32 x half> @v_bitcast_v32bf16_to_v32f16(<32 x bfloat> %a, i32 %b) {
; GCN-LABEL: v_bitcast_v32bf16_to_v32f16:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:68 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:64 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:60 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:56 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:52 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:48 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:44 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:40 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v59, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v60, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v61, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v62, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_store_dword v63, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GCN-NEXT:    buffer_load_dword v31, off, s[0:3], s32
; GCN-NEXT:    s_waitcnt expcnt(0)
; GCN-NEXT:    buffer_load_dword v63, off, s[0:3], s32 offset:4
; GCN-NEXT:    v_mul_f32_e32 v32, 1.0, v0
; GCN-NEXT:    v_mul_f32_e32 v33, 1.0, v1
; GCN-NEXT:    v_mul_f32_e32 v34, 1.0, v2
; GCN-NEXT:    v_mul_f32_e32 v35, 1.0, v3
; GCN-NEXT:    v_mul_f32_e32 v36, 1.0, v4
; GCN-NEXT:    v_mul_f32_e32 v37, 1.0, v5
; GCN-NEXT:    v_mul_f32_e32 v38, 1.0, v6
; GCN-NEXT:    v_mul_f32_e32 v39, 1.0, v7
; GCN-NEXT:    v_mul_f32_e32 v48, 1.0, v8
; GCN-NEXT:    v_mul_f32_e32 v49, 1.0, v9
; GCN-NEXT:    v_mul_f32_e32 v50, 1.0, v10
; GCN-NEXT:    v_mul_f32_e32 v51, 1.0, v11
; GCN-NEXT:    v_mul_f32_e32 v52, 1.0, v12
; GCN-NEXT:    v_mul_f32_e32 v53, 1.0, v13
; GCN-NEXT:    v_mul_f32_e32 v54, 1.0, v14
; GCN-NEXT:    v_mul_f32_e32 v55, 1.0, v15
; GCN-NEXT:    v_mul_f32_e32 v40, 1.0, v16
; GCN-NEXT:    v_mul_f32_e32 v41, 1.0, v17
; GCN-NEXT:    v_mul_f32_e32 v42, 1.0, v18
; GCN-NEXT:    v_mul_f32_e32 v43, 1.0, v19
; GCN-NEXT:    v_mul_f32_e32 v44, 1.0, v20
; GCN-NEXT:    v_mul_f32_e32 v45, 1.0, v21
; GCN-NEXT:    v_mul_f32_e32 v46, 1.0, v22
; GCN-NEXT:    v_mul_f32_e32 v47, 1.0, v23
; GCN-NEXT:    v_mul_f32_e32 v56, 1.0, v24
; GCN-NEXT:    v_mul_f32_e32 v57, 1.0, v25
; GCN-NEXT:    v_mul_f32_e32 v58, 1.0, v26
; GCN-NEXT:    v_mul_f32_e32 v59, 1.0, v27
; GCN-NEXT:    v_mul_f32_e32 v60, 1.0, v28
; GCN-NEXT:    v_mul_f32_e32 v61, 1.0, v29
; GCN-NEXT:    v_mul_f32_e32 v62, 1.0, v30
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v63
; GCN-NEXT:    v_mul_f32_e32 v63, 1.0, v31
; GCN-NEXT:    ; implicit-def: $vgpr0
; GCN-NEXT:    ; implicit-def: $vgpr1
; GCN-NEXT:    ; implicit-def: $vgpr2
; GCN-NEXT:    ; implicit-def: $vgpr3
; GCN-NEXT:    ; implicit-def: $vgpr4
; GCN-NEXT:    ; implicit-def: $vgpr5
; GCN-NEXT:    ; implicit-def: $vgpr6
; GCN-NEXT:    ; implicit-def: $vgpr7
; GCN-NEXT:    ; implicit-def: $vgpr8
; GCN-NEXT:    ; implicit-def: $vgpr9
; GCN-NEXT:    ; implicit-def: $vgpr10
; GCN-NEXT:    ; implicit-def: $vgpr11
; GCN-NEXT:    ; implicit-def: $vgpr12
; GCN-NEXT:    ; implicit-def: $vgpr13
; GCN-NEXT:    ; implicit-def: $vgpr14
; GCN-NEXT:    ; implicit-def: $vgpr15
; GCN-NEXT:    ; implicit-def: $vgpr16
; GCN-NEXT:    ; implicit-def: $vgpr17
; GCN-NEXT:    ; implicit-def: $vgpr18
; GCN-NEXT:    ; implicit-def: $vgpr19
; GCN-NEXT:    ; implicit-def: $vgpr20
; GCN-NEXT:    ; implicit-def: $vgpr21
; GCN-NEXT:    ; implicit-def: $vgpr22
; GCN-NEXT:    ; implicit-def: $vgpr23
; GCN-NEXT:    ; implicit-def: $vgpr24
; GCN-NEXT:    ; implicit-def: $vgpr25
; GCN-NEXT:    ; implicit-def: $vgpr26
; GCN-NEXT:    ; implicit-def: $vgpr27
; GCN-NEXT:    ; implicit-def: $vgpr28
; GCN-NEXT:    ; implicit-def: $vgpr29
; GCN-NEXT:    ; implicit-def: $vgpr30
; GCN-NEXT:    ; implicit-def: $vgpr31
; GCN-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GCN-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB41_2
; GCN-NEXT:  ; %bb.1: ; %cmp.false
; GCN-NEXT:    v_lshrrev_b32_e32 v0, 16, v32
; GCN-NEXT:    v_lshrrev_b32_e32 v1, 16, v33
; GCN-NEXT:    v_lshrrev_b32_e32 v2, 16, v34
; GCN-NEXT:    v_lshrrev_b32_e32 v3, 16, v35
; GCN-NEXT:    v_lshrrev_b32_e32 v4, 16, v36
; GCN-NEXT:    v_lshrrev_b32_e32 v5, 16, v37
; GCN-NEXT:    v_lshrrev_b32_e32 v6, 16, v38
; GCN-NEXT:    v_lshrrev_b32_e32 v7, 16, v39
; GCN-NEXT:    v_lshrrev_b32_e32 v8, 16, v48
; GCN-NEXT:    v_lshrrev_b32_e32 v9, 16, v49
; GCN-NEXT:    v_lshrrev_b32_e32 v10, 16, v50
; GCN-NEXT:    v_lshrrev_b32_e32 v11, 16, v51
; GCN-NEXT:    v_lshrrev_b32_e32 v12, 16, v52
; GCN-NEXT:    v_lshrrev_b32_e32 v13, 16, v53
; GCN-NEXT:    v_lshrrev_b32_e32 v14, 16, v54
; GCN-NEXT:    v_lshrrev_b32_e32 v15, 16, v55
; GCN-NEXT:    v_lshrrev_b32_e32 v16, 16, v40
; GCN-NEXT:    v_lshrrev_b32_e32 v17, 16, v41
; GCN-NEXT:    v_lshrrev_b32_e32 v18, 16, v42
; GCN-NEXT:    v_lshrrev_b32_e32 v19, 16, v43
; GCN-NEXT:    v_lshrrev_b32_e32 v20, 16, v44
; GCN-NEXT:    v_lshrrev_b32_e32 v21, 16, v45
; GCN-NEXT:    v_lshrrev_b32_e32 v22, 16, v46
; GCN-NEXT:    v_lshrrev_b32_e32 v23, 16, v47
; GCN-NEXT:    v_lshrrev_b32_e32 v24, 16, v56
; GCN-NEXT:    v_lshrrev_b32_e32 v25, 16, v57
; GCN-NEXT:    v_lshrrev_b32_e32 v26, 16, v58
; GCN-NEXT:    v_lshrrev_b32_e32 v27, 16, v59
; GCN-NEXT:    v_lshrrev_b32_e32 v28, 16, v60
; GCN-NEXT:    v_lshrrev_b32_e32 v29, 16, v61
; GCN-NEXT:    v_lshrrev_b32_e32 v30, 16, v62
; GCN-NEXT:    v_lshrrev_b32_e32 v31, 16, v63
; GCN-NEXT:    v_cvt_f32_f16_e32 v0, v0
; GCN-NEXT:    v_cvt_f32_f16_e32 v1, v1
; GCN-NEXT:    v_cvt_f32_f16_e32 v2, v2
; GCN-NEXT:    v_cvt_f32_f16_e32 v3, v3
; GCN-NEXT:    v_cvt_f32_f16_e32 v4, v4
; GCN-NEXT:    v_cvt_f32_f16_e32 v5, v5
; GCN-NEXT:    v_cvt_f32_f16_e32 v6, v6
; GCN-NEXT:    v_cvt_f32_f16_e32 v7, v7
; GCN-NEXT:    v_cvt_f32_f16_e32 v8, v8
; GCN-NEXT:    v_cvt_f32_f16_e32 v9, v9
; GCN-NEXT:    v_cvt_f32_f16_e32 v10, v10
; GCN-NEXT:    v_cvt_f32_f16_e32 v11, v11
; GCN-NEXT:    v_cvt_f32_f16_e32 v12, v12
; GCN-NEXT:    v_cvt_f32_f16_e32 v13, v13
; GCN-NEXT:    v_cvt_f32_f16_e32 v14, v14
; GCN-NEXT:    v_cvt_f32_f16_e32 v15, v15
; GCN-NEXT:    v_cvt_f32_f16_e32 v16, v16
; GCN-NEXT:    v_cvt_f32_f16_e32 v17, v17
; GCN-NEXT:    v_cvt_f32_f16_e32 v18, v18
; GCN-NEXT:    v_cvt_f32_f16_e32 v19, v19
; GCN-NEXT:    v_cvt_f32_f16_e32 v20, v20
; GCN-NEXT:    v_cvt_f32_f16_e32 v21, v21
; GCN-NEXT:    v_cvt_f32_f16_e32 v22, v22
; GCN-NEXT:    v_cvt_f32_f16_e32 v23, v23
; GCN-NEXT:    v_cvt_f32_f16_e32 v24, v24
; GCN-NEXT:    v_cvt_f32_f16_e32 v25, v25
; GCN-NEXT:    v_cvt_f32_f16_e32 v26, v26
; GCN-NEXT:    v_cvt_f32_f16_e32 v27, v27
; GCN-NEXT:    v_cvt_f32_f16_e32 v28, v28
; GCN-NEXT:    v_cvt_f32_f16_e32 v29, v29
; GCN-NEXT:    v_cvt_f32_f16_e32 v30, v30
; GCN-NEXT:    v_cvt_f32_f16_e32 v31, v31
; GCN-NEXT:    ; implicit-def: $vgpr32
; GCN-NEXT:    ; implicit-def: $vgpr33
; GCN-NEXT:    ; implicit-def: $vgpr34
; GCN-NEXT:    ; implicit-def: $vgpr35
; GCN-NEXT:    ; implicit-def: $vgpr36
; GCN-NEXT:    ; implicit-def: $vgpr37
; GCN-NEXT:    ; implicit-def: $vgpr38
; GCN-NEXT:    ; implicit-def: $vgpr39
; GCN-NEXT:    ; implicit-def: $vgpr48
; GCN-NEXT:    ; implicit-def: $vgpr49
; GCN-NEXT:    ; implicit-def: $vgpr50
; GCN-NEXT:    ; implicit-def: $vgpr51
; GCN-NEXT:    ; implicit-def: $vgpr52
; GCN-NEXT:    ; implicit-def: $vgpr53
; GCN-NEXT:    ; implicit-def: $vgpr54
; GCN-NEXT:    ; implicit-def: $vgpr55
; GCN-NEXT:    ; implicit-def: $vgpr40
; GCN-NEXT:    ; implicit-def: $vgpr41
; GCN-NEXT:    ; implicit-def: $vgpr42
; GCN-NEXT:    ; implicit-def: $vgpr43
; GCN-NEXT:    ; implicit-def: $vgpr44
; GCN-NEXT:    ; implicit-def: $vgpr45
; GCN-NEXT:    ; implicit-def: $vgpr46
; GCN-NEXT:    ; implicit-def: $vgpr47
; GCN-NEXT:    ; implicit-def: $vgpr56
; GCN-NEXT:    ; implicit-def: $vgpr57
; GCN-NEXT:    ; implicit-def: $vgpr58
; GCN-NEXT:    ; implicit-def: $vgpr59
; GCN-NEXT:    ; implicit-def: $vgpr60
; GCN-NEXT:    ; implicit-def: $vgpr61
; GCN-NEXT:    ; implicit-def: $vgpr62
; GCN-NEXT:    ; implicit-def: $vgpr63
; GCN-NEXT:  .LBB41_2: ; %Flow
; GCN-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GCN-NEXT:    s_cbranch_execz .LBB41_4
; GCN-NEXT:  ; %bb.3: ; %cmp.true
; GCN-NEXT:    v_and_b32_e32 v0, 0xffff0000, v63
; GCN-NEXT:    v_and_b32_e32 v1, 0xffff0000, v62
; GCN-NEXT:    v_and_b32_e32 v2, 0xffff0000, v61
; GCN-NEXT:    v_and_b32_e32 v3, 0xffff0000, v60
; GCN-NEXT:    v_and_b32_e32 v4, 0xffff0000, v59
; GCN-NEXT:    v_and_b32_e32 v5, 0xffff0000, v58
; GCN-NEXT:    v_and_b32_e32 v6, 0xffff0000, v57
; GCN-NEXT:    v_and_b32_e32 v7, 0xffff0000, v56
; GCN-NEXT:    v_and_b32_e32 v8, 0xffff0000, v47
; GCN-NEXT:    v_and_b32_e32 v9, 0xffff0000, v46
; GCN-NEXT:    v_and_b32_e32 v10, 0xffff0000, v45
; GCN-NEXT:    v_and_b32_e32 v11, 0xffff0000, v44
; GCN-NEXT:    v_and_b32_e32 v12, 0xffff0000, v43
; GCN-NEXT:    v_and_b32_e32 v13, 0xffff0000, v42
; GCN-NEXT:    v_and_b32_e32 v14, 0xffff0000, v41
; GCN-NEXT:    v_and_b32_e32 v15, 0xffff0000, v40
; GCN-NEXT:    v_and_b32_e32 v16, 0xffff0000, v55
; GCN-NEXT:    v_and_b32_e32 v17, 0xffff0000, v54
; GCN-NEXT:    v_and_b32_e32 v18, 0xffff0000, v53
; GCN-NEXT:    v_and_b32_e32 v19, 0xffff0000, v52
; GCN-NEXT:    v_and_b32_e32 v20, 0xffff0000, v51
; GCN-NEXT:    v_and_b32_e32 v21, 0xffff0000, v50
; GCN-NEXT:    v_and_b32_e32 v22, 0xffff0000, v49
; GCN-NEXT:    v_and_b32_e32 v23, 0xffff0000, v48
; GCN-NEXT:    v_and_b32_e32 v24, 0xffff0000, v39
; GCN-NEXT:    v_and_b32_e32 v25, 0xffff0000, v38
; GCN-NEXT:    v_and_b32_e32 v26, 0xffff0000, v37
; GCN-NEXT:    v_and_b32_e32 v27, 0xffff0000, v36
; GCN-NEXT:    v_and_b32_e32 v28, 0xffff0000, v35
; GCN-NEXT:    v_and_b32_e32 v29, 0xffff0000, v34
; GCN-NEXT:    v_and_b32_e32 v30, 0xffff0000, v33
; GCN-NEXT:    v_and_b32_e32 v31, 0xffff0000, v32
; GCN-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; GCN-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GCN-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GCN-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GCN-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; GCN-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GCN-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GCN-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GCN-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GCN-NEXT:    v_add_f32_e32 v9, 0x40c00000, v9
; GCN-NEXT:    v_add_f32_e32 v10, 0x40c00000, v10
; GCN-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; GCN-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; GCN-NEXT:    v_add_f32_e32 v13, 0x40c00000, v13
; GCN-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; GCN-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; GCN-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GCN-NEXT:    v_add_f32_e32 v17, 0x40c00000, v17
; GCN-NEXT:    v_add_f32_e32 v18, 0x40c00000, v18
; GCN-NEXT:    v_add_f32_e32 v19, 0x40c00000, v19
; GCN-NEXT:    v_add_f32_e32 v20, 0x40c00000, v20
; GCN-NEXT:    v_add_f32_e32 v21, 0x40c00000, v21
; GCN-NEXT:    v_add_f32_e32 v22, 0x40c00000, v22
; GCN-NEXT:    v_add_f32_e32 v23, 0x40c00000, v23
; GCN-NEXT:    v_add_f32_e32 v24, 0x40c00000, v24
; GCN-NEXT:    v_add_f32_e32 v25, 0x40c00000, v25
; GCN-NEXT:    v_add_f32_e32 v26, 0x40c00000, v26
; GCN-NEXT:    v_add_f32_e32 v27, 0x40c00000, v27
; GCN-NEXT:    v_add_f32_e32 v28, 0x40c00000, v28
; GCN-NEXT:    v_add_f32_e32 v29, 0x40c00000, v29
; GCN-NEXT:    v_add_f32_e32 v30, 0x40c00000, v30
; GCN-NEXT:    v_add_f32_e32 v31, 0x40c00000, v31
; GCN-NEXT:    v_lshrrev_b32_e32 v32, 16, v0
; GCN-NEXT:    v_lshrrev_b32_e32 v33, 16, v1
; GCN-NEXT:    v_lshrrev_b32_e32 v34, 16, v2
; GCN-NEXT:    v_lshrrev_b32_e32 v35, 16, v3
; GCN-NEXT:    v_lshrrev_b32_e32 v36, 16, v4
; GCN-NEXT:    v_lshrrev_b32_e32 v37, 16, v5
; GCN-NEXT:    v_lshrrev_b32_e32 v38, 16, v6
; GCN-NEXT:    v_lshrrev_b32_e32 v39, 16, v7
; GCN-NEXT:    v_lshrrev_b32_e32 v48, 16, v8
; GCN-NEXT:    v_lshrrev_b32_e32 v49, 16, v9
; GCN-NEXT:    v_lshrrev_b32_e32 v50, 16, v10
; GCN-NEXT:    v_lshrrev_b32_e32 v51, 16, v11
; GCN-NEXT:    v_lshrrev_b32_e32 v52, 16, v12
; GCN-NEXT:    v_lshrrev_b32_e32 v53, 16, v13
; GCN-NEXT:    v_lshrrev_b32_e32 v54, 16, v14
; GCN-NEXT:    v_lshrrev_b32_e32 v55, 16, v15
; GCN-NEXT:    v_lshrrev_b32_e32 v15, 16, v16
; GCN-NEXT:    v_lshrrev_b32_e32 v14, 16, v17
; GCN-NEXT:    v_lshrrev_b32_e32 v13, 16, v18
; GCN-NEXT:    v_lshrrev_b32_e32 v12, 16, v19
; GCN-NEXT:    v_lshrrev_b32_e32 v11, 16, v20
; GCN-NEXT:    v_lshrrev_b32_e32 v10, 16, v21
; GCN-NEXT:    v_lshrrev_b32_e32 v9, 16, v22
; GCN-NEXT:    v_lshrrev_b32_e32 v8, 16, v23
; GCN-NEXT:    v_lshrrev_b32_e32 v7, 16, v24
; GCN-NEXT:    v_lshrrev_b32_e32 v6, 16, v25
; GCN-NEXT:    v_lshrrev_b32_e32 v5, 16, v26
; GCN-NEXT:    v_lshrrev_b32_e32 v4, 16, v27
; GCN-NEXT:    v_lshrrev_b32_e32 v3, 16, v28
; GCN-NEXT:    v_lshrrev_b32_e32 v2, 16, v29
; GCN-NEXT:    v_lshrrev_b32_e32 v1, 16, v30
; GCN-NEXT:    v_lshrrev_b32_e32 v0, 16, v31
; GCN-NEXT:    v_cvt_f32_f16_e32 v0, v0
; GCN-NEXT:    v_cvt_f32_f16_e32 v1, v1
; GCN-NEXT:    v_cvt_f32_f16_e32 v2, v2
; GCN-NEXT:    v_cvt_f32_f16_e32 v3, v3
; GCN-NEXT:    v_cvt_f32_f16_e32 v4, v4
; GCN-NEXT:    v_cvt_f32_f16_e32 v5, v5
; GCN-NEXT:    v_cvt_f32_f16_e32 v6, v6
; GCN-NEXT:    v_cvt_f32_f16_e32 v7, v7
; GCN-NEXT:    v_cvt_f32_f16_e32 v8, v8
; GCN-NEXT:    v_cvt_f32_f16_e32 v9, v9
; GCN-NEXT:    v_cvt_f32_f16_e32 v10, v10
; GCN-NEXT:    v_cvt_f32_f16_e32 v11, v11
; GCN-NEXT:    v_cvt_f32_f16_e32 v12, v12
; GCN-NEXT:    v_cvt_f32_f16_e32 v13, v13
; GCN-NEXT:    v_cvt_f32_f16_e32 v14, v14
; GCN-NEXT:    v_cvt_f32_f16_e32 v15, v15
; GCN-NEXT:    v_cvt_f32_f16_e32 v16, v55
; GCN-NEXT:    v_cvt_f32_f16_e32 v17, v54
; GCN-NEXT:    v_cvt_f32_f16_e32 v18, v53
; GCN-NEXT:    v_cvt_f32_f16_e32 v19, v52
; GCN-NEXT:    v_cvt_f32_f16_e32 v20, v51
; GCN-NEXT:    v_cvt_f32_f16_e32 v21, v50
; GCN-NEXT:    v_cvt_f32_f16_e32 v22, v49
; GCN-NEXT:    v_cvt_f32_f16_e32 v23, v48
; GCN-NEXT:    v_cvt_f32_f16_e32 v24, v39
; GCN-NEXT:    v_cvt_f32_f16_e32 v25, v38
; GCN-NEXT:    v_cvt_f32_f16_e32 v26, v37
; GCN-NEXT:    v_cvt_f32_f16_e32 v27, v36
; GCN-NEXT:    v_cvt_f32_f16_e32 v28, v35
; GCN-NEXT:    v_cvt_f32_f16_e32 v29, v34
; GCN-NEXT:    v_cvt_f32_f16_e32 v30, v33
; GCN-NEXT:    v_cvt_f32_f16_e32 v31, v32
; GCN-NEXT:  .LBB41_4: ; %end
; GCN-NEXT:    s_or_b64 exec, exec, s[4:5]
; GCN-NEXT:    buffer_load_dword v63, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v62, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v61, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v60, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v57, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:40 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:44 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:48 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:52 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:56 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:60 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; GCN-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: v_bitcast_v32bf16_to_v32f16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB41_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v0
; VI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; VI-NEXT:    v_bfe_u32 v17, v16, 16, 1
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v16
; VI-NEXT:    v_add_u32_e32 v17, vcc, 0x7fff, v17
; VI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; VI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; VI-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; VI-NEXT:    v_bfe_u32 v17, v0, 16, 1
; VI-NEXT:    s_movk_i32 s6, 0x7fff
; VI-NEXT:    v_add_u32_e32 v17, vcc, v17, v0
; VI-NEXT:    v_add_u32_e32 v17, vcc, s6, v17
; VI-NEXT:    v_or_b32_e32 v18, 0x400000, v0
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; VI-NEXT:    v_cndmask_b32_e32 v0, v17, v18, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v17, 16, v1
; VI-NEXT:    v_add_f32_e32 v17, 0x40c00000, v17
; VI-NEXT:    v_bfe_u32 v18, v17, 16, 1
; VI-NEXT:    v_add_u32_e32 v18, vcc, v18, v17
; VI-NEXT:    v_add_u32_e32 v18, vcc, s6, v18
; VI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; VI-NEXT:    v_or_b32_e32 v19, 0x400000, v17
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v17, v17
; VI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; VI-NEXT:    v_cndmask_b32_e32 v17, v18, v19, vcc
; VI-NEXT:    v_bfe_u32 v18, v1, 16, 1
; VI-NEXT:    v_add_u32_e32 v18, vcc, v18, v1
; VI-NEXT:    v_add_u32_e32 v18, vcc, s6, v18
; VI-NEXT:    v_or_b32_e32 v19, 0x400000, v1
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; VI-NEXT:    v_cndmask_b32_e32 v1, v18, v19, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v18, 16, v2
; VI-NEXT:    v_add_f32_e32 v18, 0x40c00000, v18
; VI-NEXT:    v_bfe_u32 v19, v18, 16, 1
; VI-NEXT:    v_add_u32_e32 v19, vcc, v19, v18
; VI-NEXT:    v_add_u32_e32 v19, vcc, s6, v19
; VI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; VI-NEXT:    v_or_b32_e32 v20, 0x400000, v18
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v18, v18
; VI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; VI-NEXT:    v_cndmask_b32_e32 v18, v19, v20, vcc
; VI-NEXT:    v_bfe_u32 v19, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v19, vcc, v19, v2
; VI-NEXT:    v_add_u32_e32 v19, vcc, s6, v19
; VI-NEXT:    v_or_b32_e32 v20, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v19, v20, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v19, 16, v3
; VI-NEXT:    v_add_f32_e32 v19, 0x40c00000, v19
; VI-NEXT:    v_bfe_u32 v20, v19, 16, 1
; VI-NEXT:    v_add_u32_e32 v20, vcc, v20, v19
; VI-NEXT:    v_add_u32_e32 v20, vcc, s6, v20
; VI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; VI-NEXT:    v_or_b32_e32 v21, 0x400000, v19
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v19, v19
; VI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; VI-NEXT:    v_cndmask_b32_e32 v19, v20, v21, vcc
; VI-NEXT:    v_bfe_u32 v20, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v20, vcc, v20, v3
; VI-NEXT:    v_add_u32_e32 v20, vcc, s6, v20
; VI-NEXT:    v_or_b32_e32 v21, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v20, v21, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v4
; VI-NEXT:    v_add_f32_e32 v20, 0x40c00000, v20
; VI-NEXT:    v_bfe_u32 v21, v20, 16, 1
; VI-NEXT:    v_add_u32_e32 v21, vcc, v21, v20
; VI-NEXT:    v_add_u32_e32 v21, vcc, s6, v21
; VI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; VI-NEXT:    v_or_b32_e32 v22, 0x400000, v20
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v20, v20
; VI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; VI-NEXT:    v_cndmask_b32_e32 v20, v21, v22, vcc
; VI-NEXT:    v_bfe_u32 v21, v4, 16, 1
; VI-NEXT:    v_add_u32_e32 v21, vcc, v21, v4
; VI-NEXT:    v_add_u32_e32 v21, vcc, s6, v21
; VI-NEXT:    v_or_b32_e32 v22, 0x400000, v4
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; VI-NEXT:    v_cndmask_b32_e32 v4, v21, v22, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v21, 16, v5
; VI-NEXT:    v_add_f32_e32 v21, 0x40c00000, v21
; VI-NEXT:    v_bfe_u32 v22, v21, 16, 1
; VI-NEXT:    v_add_u32_e32 v22, vcc, v22, v21
; VI-NEXT:    v_add_u32_e32 v22, vcc, s6, v22
; VI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; VI-NEXT:    v_or_b32_e32 v23, 0x400000, v21
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v21, v21
; VI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; VI-NEXT:    v_cndmask_b32_e32 v21, v22, v23, vcc
; VI-NEXT:    v_bfe_u32 v22, v5, 16, 1
; VI-NEXT:    v_add_u32_e32 v22, vcc, v22, v5
; VI-NEXT:    v_add_u32_e32 v22, vcc, s6, v22
; VI-NEXT:    v_or_b32_e32 v23, 0x400000, v5
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; VI-NEXT:    v_cndmask_b32_e32 v5, v22, v23, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v22, 16, v6
; VI-NEXT:    v_add_f32_e32 v22, 0x40c00000, v22
; VI-NEXT:    v_bfe_u32 v23, v22, 16, 1
; VI-NEXT:    v_add_u32_e32 v23, vcc, v23, v22
; VI-NEXT:    v_add_u32_e32 v23, vcc, s6, v23
; VI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; VI-NEXT:    v_or_b32_e32 v24, 0x400000, v22
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v22, v22
; VI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; VI-NEXT:    v_cndmask_b32_e32 v22, v23, v24, vcc
; VI-NEXT:    v_bfe_u32 v23, v6, 16, 1
; VI-NEXT:    v_add_u32_e32 v23, vcc, v23, v6
; VI-NEXT:    v_add_u32_e32 v23, vcc, s6, v23
; VI-NEXT:    v_or_b32_e32 v24, 0x400000, v6
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; VI-NEXT:    v_cndmask_b32_e32 v6, v23, v24, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v23, 16, v7
; VI-NEXT:    v_add_f32_e32 v23, 0x40c00000, v23
; VI-NEXT:    v_bfe_u32 v24, v23, 16, 1
; VI-NEXT:    v_add_u32_e32 v24, vcc, v24, v23
; VI-NEXT:    v_add_u32_e32 v24, vcc, s6, v24
; VI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; VI-NEXT:    v_or_b32_e32 v25, 0x400000, v23
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v23, v23
; VI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; VI-NEXT:    v_cndmask_b32_e32 v23, v24, v25, vcc
; VI-NEXT:    v_bfe_u32 v24, v7, 16, 1
; VI-NEXT:    v_add_u32_e32 v24, vcc, v24, v7
; VI-NEXT:    v_add_u32_e32 v24, vcc, s6, v24
; VI-NEXT:    v_or_b32_e32 v25, 0x400000, v7
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; VI-NEXT:    v_cndmask_b32_e32 v7, v24, v25, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v24, 16, v8
; VI-NEXT:    v_add_f32_e32 v24, 0x40c00000, v24
; VI-NEXT:    v_bfe_u32 v25, v24, 16, 1
; VI-NEXT:    v_add_u32_e32 v25, vcc, v25, v24
; VI-NEXT:    v_add_u32_e32 v25, vcc, s6, v25
; VI-NEXT:    v_and_b32_e32 v8, 0xffff0000, v8
; VI-NEXT:    v_or_b32_e32 v26, 0x400000, v24
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v24, v24
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_cndmask_b32_e32 v24, v25, v26, vcc
; VI-NEXT:    v_bfe_u32 v25, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v25, vcc, v25, v8
; VI-NEXT:    v_add_u32_e32 v25, vcc, s6, v25
; VI-NEXT:    v_or_b32_e32 v26, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_cndmask_b32_e32 v8, v25, v26, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v25, 16, v9
; VI-NEXT:    v_add_f32_e32 v25, 0x40c00000, v25
; VI-NEXT:    v_bfe_u32 v26, v25, 16, 1
; VI-NEXT:    v_add_u32_e32 v26, vcc, v26, v25
; VI-NEXT:    v_add_u32_e32 v26, vcc, s6, v26
; VI-NEXT:    v_and_b32_e32 v9, 0xffff0000, v9
; VI-NEXT:    v_or_b32_e32 v27, 0x400000, v25
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v25, v25
; VI-NEXT:    v_add_f32_e32 v9, 0x40c00000, v9
; VI-NEXT:    v_cndmask_b32_e32 v25, v26, v27, vcc
; VI-NEXT:    v_bfe_u32 v26, v9, 16, 1
; VI-NEXT:    v_add_u32_e32 v26, vcc, v26, v9
; VI-NEXT:    v_add_u32_e32 v26, vcc, s6, v26
; VI-NEXT:    v_or_b32_e32 v27, 0x400000, v9
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v9, v9
; VI-NEXT:    v_cndmask_b32_e32 v9, v26, v27, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v26, 16, v10
; VI-NEXT:    v_add_f32_e32 v26, 0x40c00000, v26
; VI-NEXT:    v_bfe_u32 v27, v26, 16, 1
; VI-NEXT:    v_add_u32_e32 v27, vcc, v27, v26
; VI-NEXT:    v_add_u32_e32 v27, vcc, s6, v27
; VI-NEXT:    v_and_b32_e32 v10, 0xffff0000, v10
; VI-NEXT:    v_or_b32_e32 v28, 0x400000, v26
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v26, v26
; VI-NEXT:    v_add_f32_e32 v10, 0x40c00000, v10
; VI-NEXT:    v_cndmask_b32_e32 v26, v27, v28, vcc
; VI-NEXT:    v_bfe_u32 v27, v10, 16, 1
; VI-NEXT:    v_add_u32_e32 v27, vcc, v27, v10
; VI-NEXT:    v_add_u32_e32 v27, vcc, s6, v27
; VI-NEXT:    v_or_b32_e32 v28, 0x400000, v10
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v10, v10
; VI-NEXT:    v_cndmask_b32_e32 v10, v27, v28, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v27, 16, v11
; VI-NEXT:    v_add_f32_e32 v27, 0x40c00000, v27
; VI-NEXT:    v_bfe_u32 v28, v27, 16, 1
; VI-NEXT:    v_add_u32_e32 v28, vcc, v28, v27
; VI-NEXT:    v_add_u32_e32 v28, vcc, s6, v28
; VI-NEXT:    v_and_b32_e32 v11, 0xffff0000, v11
; VI-NEXT:    v_or_b32_e32 v29, 0x400000, v27
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v27, v27
; VI-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; VI-NEXT:    v_cndmask_b32_e32 v27, v28, v29, vcc
; VI-NEXT:    v_bfe_u32 v28, v11, 16, 1
; VI-NEXT:    v_add_u32_e32 v28, vcc, v28, v11
; VI-NEXT:    v_add_u32_e32 v28, vcc, s6, v28
; VI-NEXT:    v_or_b32_e32 v29, 0x400000, v11
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v11, v11
; VI-NEXT:    v_cndmask_b32_e32 v11, v28, v29, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v28, 16, v12
; VI-NEXT:    v_add_f32_e32 v28, 0x40c00000, v28
; VI-NEXT:    v_bfe_u32 v29, v28, 16, 1
; VI-NEXT:    v_add_u32_e32 v29, vcc, v29, v28
; VI-NEXT:    v_add_u32_e32 v29, vcc, s6, v29
; VI-NEXT:    v_and_b32_e32 v12, 0xffff0000, v12
; VI-NEXT:    v_or_b32_e32 v30, 0x400000, v28
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v28, v28
; VI-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; VI-NEXT:    v_cndmask_b32_e32 v28, v29, v30, vcc
; VI-NEXT:    v_bfe_u32 v29, v12, 16, 1
; VI-NEXT:    v_add_u32_e32 v29, vcc, v29, v12
; VI-NEXT:    v_add_u32_e32 v29, vcc, s6, v29
; VI-NEXT:    v_or_b32_e32 v30, 0x400000, v12
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v12, v12
; VI-NEXT:    v_cndmask_b32_e32 v12, v29, v30, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v29, 16, v13
; VI-NEXT:    v_add_f32_e32 v29, 0x40c00000, v29
; VI-NEXT:    v_bfe_u32 v30, v29, 16, 1
; VI-NEXT:    v_add_u32_e32 v30, vcc, v30, v29
; VI-NEXT:    v_add_u32_e32 v30, vcc, s6, v30
; VI-NEXT:    v_and_b32_e32 v13, 0xffff0000, v13
; VI-NEXT:    v_or_b32_e32 v31, 0x400000, v29
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v29, v29
; VI-NEXT:    v_add_f32_e32 v13, 0x40c00000, v13
; VI-NEXT:    v_cndmask_b32_e32 v29, v30, v31, vcc
; VI-NEXT:    v_bfe_u32 v30, v13, 16, 1
; VI-NEXT:    v_add_u32_e32 v30, vcc, v30, v13
; VI-NEXT:    v_add_u32_e32 v30, vcc, s6, v30
; VI-NEXT:    v_or_b32_e32 v31, 0x400000, v13
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v13, v13
; VI-NEXT:    v_cndmask_b32_e32 v13, v30, v31, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v30, 16, v14
; VI-NEXT:    v_add_f32_e32 v30, 0x40c00000, v30
; VI-NEXT:    v_bfe_u32 v31, v30, 16, 1
; VI-NEXT:    v_add_u32_e32 v31, vcc, v31, v30
; VI-NEXT:    v_add_u32_e32 v31, vcc, s6, v31
; VI-NEXT:    v_and_b32_e32 v14, 0xffff0000, v14
; VI-NEXT:    v_or_b32_e32 v32, 0x400000, v30
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v30, v30
; VI-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; VI-NEXT:    v_cndmask_b32_e32 v30, v31, v32, vcc
; VI-NEXT:    v_bfe_u32 v31, v14, 16, 1
; VI-NEXT:    v_add_u32_e32 v31, vcc, v31, v14
; VI-NEXT:    v_add_u32_e32 v31, vcc, s6, v31
; VI-NEXT:    v_or_b32_e32 v32, 0x400000, v14
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v14, v14
; VI-NEXT:    v_cndmask_b32_e32 v14, v31, v32, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v31, 16, v15
; VI-NEXT:    v_add_f32_e32 v31, 0x40c00000, v31
; VI-NEXT:    v_bfe_u32 v32, v31, 16, 1
; VI-NEXT:    v_add_u32_e32 v32, vcc, v32, v31
; VI-NEXT:    v_add_u32_e32 v32, vcc, s6, v32
; VI-NEXT:    v_and_b32_e32 v15, 0xffff0000, v15
; VI-NEXT:    v_or_b32_e32 v33, 0x400000, v31
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v31, v31
; VI-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; VI-NEXT:    v_cndmask_b32_e32 v31, v32, v33, vcc
; VI-NEXT:    v_bfe_u32 v32, v15, 16, 1
; VI-NEXT:    v_add_u32_e32 v32, vcc, v32, v15
; VI-NEXT:    v_add_u32_e32 v32, vcc, s6, v32
; VI-NEXT:    v_or_b32_e32 v33, 0x400000, v15
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v15, v15
; VI-NEXT:    v_cndmask_b32_e32 v15, v32, v33, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v15, 16, v15
; VI-NEXT:    v_lshrrev_b32_e32 v14, 16, v14
; VI-NEXT:    v_lshrrev_b32_e32 v13, 16, v13
; VI-NEXT:    v_lshrrev_b32_e32 v12, 16, v12
; VI-NEXT:    v_lshrrev_b32_e32 v11, 16, v11
; VI-NEXT:    v_lshrrev_b32_e32 v10, 16, v10
; VI-NEXT:    v_lshrrev_b32_e32 v9, 16, v9
; VI-NEXT:    v_lshrrev_b32_e32 v8, 16, v8
; VI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; VI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_alignbit_b32 v15, v15, v31, 16
; VI-NEXT:    v_alignbit_b32 v14, v14, v30, 16
; VI-NEXT:    v_alignbit_b32 v13, v13, v29, 16
; VI-NEXT:    v_alignbit_b32 v12, v12, v28, 16
; VI-NEXT:    v_alignbit_b32 v11, v11, v27, 16
; VI-NEXT:    v_alignbit_b32 v10, v10, v26, 16
; VI-NEXT:    v_alignbit_b32 v9, v9, v25, 16
; VI-NEXT:    v_alignbit_b32 v8, v8, v24, 16
; VI-NEXT:    v_alignbit_b32 v7, v7, v23, 16
; VI-NEXT:    v_alignbit_b32 v6, v6, v22, 16
; VI-NEXT:    v_alignbit_b32 v5, v5, v21, 16
; VI-NEXT:    v_alignbit_b32 v4, v4, v20, 16
; VI-NEXT:    v_alignbit_b32 v3, v3, v19, 16
; VI-NEXT:    v_alignbit_b32 v2, v2, v18, 16
; VI-NEXT:    v_alignbit_b32 v1, v1, v17, 16
; VI-NEXT:    v_alignbit_b32 v0, v0, v16, 16
; VI-NEXT:  .LBB41_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: v_bitcast_v32bf16_to_v32f16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v16
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB41_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_lshlrev_b32_e32 v16, 16, v0
; GFX9-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX9-NEXT:    v_bfe_u32 v17, v16, 16, 1
; GFX9-NEXT:    s_movk_i32 s6, 0x7fff
; GFX9-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX9-NEXT:    v_add3_u32 v17, v17, v16, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v16
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v16, v16
; GFX9-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v17, v18, vcc
; GFX9-NEXT:    v_bfe_u32 v17, v0, 16, 1
; GFX9-NEXT:    v_add3_u32 v17, v17, v0, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v0
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v0, v17, v18, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v17, 16, v1
; GFX9-NEXT:    v_add_f32_e32 v17, 0x40c00000, v17
; GFX9-NEXT:    v_bfe_u32 v18, v17, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; GFX9-NEXT:    v_add3_u32 v18, v18, v17, s6
; GFX9-NEXT:    v_or_b32_e32 v19, 0x400000, v17
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v17, v17
; GFX9-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v17, v18, v19, vcc
; GFX9-NEXT:    v_bfe_u32 v18, v1, 16, 1
; GFX9-NEXT:    v_add3_u32 v18, v18, v1, s6
; GFX9-NEXT:    v_or_b32_e32 v19, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v18, v19, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v18, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v18, 0x40c00000, v18
; GFX9-NEXT:    v_bfe_u32 v19, v18, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; GFX9-NEXT:    v_add3_u32 v19, v19, v18, s6
; GFX9-NEXT:    v_or_b32_e32 v20, 0x400000, v18
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v18, v18
; GFX9-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v18, v19, v20, vcc
; GFX9-NEXT:    v_bfe_u32 v19, v2, 16, 1
; GFX9-NEXT:    v_add3_u32 v19, v19, v2, s6
; GFX9-NEXT:    v_or_b32_e32 v20, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v19, v20, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v19, 16, v3
; GFX9-NEXT:    v_add_f32_e32 v19, 0x40c00000, v19
; GFX9-NEXT:    v_bfe_u32 v20, v19, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; GFX9-NEXT:    v_add3_u32 v20, v20, v19, s6
; GFX9-NEXT:    v_or_b32_e32 v21, 0x400000, v19
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v19, v19
; GFX9-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GFX9-NEXT:    v_cndmask_b32_e32 v19, v20, v21, vcc
; GFX9-NEXT:    v_bfe_u32 v20, v3, 16, 1
; GFX9-NEXT:    v_add3_u32 v20, v20, v3, s6
; GFX9-NEXT:    v_or_b32_e32 v21, 0x400000, v3
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; GFX9-NEXT:    v_cndmask_b32_e32 v3, v20, v21, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v20, 16, v4
; GFX9-NEXT:    v_add_f32_e32 v20, 0x40c00000, v20
; GFX9-NEXT:    v_bfe_u32 v21, v20, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; GFX9-NEXT:    v_add3_u32 v21, v21, v20, s6
; GFX9-NEXT:    v_or_b32_e32 v22, 0x400000, v20
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v20, v20
; GFX9-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; GFX9-NEXT:    v_cndmask_b32_e32 v20, v21, v22, vcc
; GFX9-NEXT:    v_bfe_u32 v21, v4, 16, 1
; GFX9-NEXT:    v_add3_u32 v21, v21, v4, s6
; GFX9-NEXT:    v_or_b32_e32 v22, 0x400000, v4
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; GFX9-NEXT:    v_cndmask_b32_e32 v4, v21, v22, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v21, 16, v5
; GFX9-NEXT:    v_add_f32_e32 v21, 0x40c00000, v21
; GFX9-NEXT:    v_bfe_u32 v22, v21, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; GFX9-NEXT:    v_add3_u32 v22, v22, v21, s6
; GFX9-NEXT:    v_or_b32_e32 v23, 0x400000, v21
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v21, v21
; GFX9-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v21, v22, v23, vcc
; GFX9-NEXT:    v_bfe_u32 v22, v5, 16, 1
; GFX9-NEXT:    v_add3_u32 v22, v22, v5, s6
; GFX9-NEXT:    v_or_b32_e32 v23, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v5, v22, v23, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v22, 16, v6
; GFX9-NEXT:    v_add_f32_e32 v22, 0x40c00000, v22
; GFX9-NEXT:    v_bfe_u32 v23, v22, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; GFX9-NEXT:    v_add3_u32 v23, v23, v22, s6
; GFX9-NEXT:    v_or_b32_e32 v24, 0x400000, v22
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v22, v22
; GFX9-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GFX9-NEXT:    v_cndmask_b32_e32 v22, v23, v24, vcc
; GFX9-NEXT:    v_bfe_u32 v23, v6, 16, 1
; GFX9-NEXT:    v_add3_u32 v23, v23, v6, s6
; GFX9-NEXT:    v_or_b32_e32 v24, 0x400000, v6
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; GFX9-NEXT:    v_cndmask_b32_e32 v6, v23, v24, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v23, 16, v7
; GFX9-NEXT:    v_add_f32_e32 v23, 0x40c00000, v23
; GFX9-NEXT:    v_bfe_u32 v24, v23, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; GFX9-NEXT:    v_add3_u32 v24, v24, v23, s6
; GFX9-NEXT:    v_or_b32_e32 v25, 0x400000, v23
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v23, v23
; GFX9-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GFX9-NEXT:    v_cndmask_b32_e32 v23, v24, v25, vcc
; GFX9-NEXT:    v_bfe_u32 v24, v7, 16, 1
; GFX9-NEXT:    v_add3_u32 v24, v24, v7, s6
; GFX9-NEXT:    v_or_b32_e32 v25, 0x400000, v7
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; GFX9-NEXT:    v_cndmask_b32_e32 v7, v24, v25, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v24, 16, v8
; GFX9-NEXT:    v_add_f32_e32 v24, 0x40c00000, v24
; GFX9-NEXT:    v_bfe_u32 v25, v24, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v8, 0xffff0000, v8
; GFX9-NEXT:    v_add3_u32 v25, v25, v24, s6
; GFX9-NEXT:    v_or_b32_e32 v26, 0x400000, v24
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v24, v24
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_cndmask_b32_e32 v24, v25, v26, vcc
; GFX9-NEXT:    v_bfe_u32 v25, v8, 16, 1
; GFX9-NEXT:    v_add3_u32 v25, v25, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v26, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v25, v26, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v25, 16, v9
; GFX9-NEXT:    v_add_f32_e32 v25, 0x40c00000, v25
; GFX9-NEXT:    v_bfe_u32 v26, v25, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v9, 0xffff0000, v9
; GFX9-NEXT:    v_add3_u32 v26, v26, v25, s6
; GFX9-NEXT:    v_or_b32_e32 v27, 0x400000, v25
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v25, v25
; GFX9-NEXT:    v_add_f32_e32 v9, 0x40c00000, v9
; GFX9-NEXT:    v_cndmask_b32_e32 v25, v26, v27, vcc
; GFX9-NEXT:    v_bfe_u32 v26, v9, 16, 1
; GFX9-NEXT:    v_add3_u32 v26, v26, v9, s6
; GFX9-NEXT:    v_or_b32_e32 v27, 0x400000, v9
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v9, v9
; GFX9-NEXT:    v_cndmask_b32_e32 v9, v26, v27, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v26, 16, v10
; GFX9-NEXT:    v_add_f32_e32 v26, 0x40c00000, v26
; GFX9-NEXT:    v_bfe_u32 v27, v26, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v10, 0xffff0000, v10
; GFX9-NEXT:    v_add3_u32 v27, v27, v26, s6
; GFX9-NEXT:    v_or_b32_e32 v28, 0x400000, v26
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v26, v26
; GFX9-NEXT:    v_add_f32_e32 v10, 0x40c00000, v10
; GFX9-NEXT:    v_cndmask_b32_e32 v26, v27, v28, vcc
; GFX9-NEXT:    v_bfe_u32 v27, v10, 16, 1
; GFX9-NEXT:    v_add3_u32 v27, v27, v10, s6
; GFX9-NEXT:    v_or_b32_e32 v28, 0x400000, v10
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v10, v10
; GFX9-NEXT:    v_cndmask_b32_e32 v10, v27, v28, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v27, 16, v11
; GFX9-NEXT:    v_add_f32_e32 v27, 0x40c00000, v27
; GFX9-NEXT:    v_bfe_u32 v28, v27, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v11, 0xffff0000, v11
; GFX9-NEXT:    v_add3_u32 v28, v28, v27, s6
; GFX9-NEXT:    v_or_b32_e32 v29, 0x400000, v27
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v27, v27
; GFX9-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; GFX9-NEXT:    v_cndmask_b32_e32 v27, v28, v29, vcc
; GFX9-NEXT:    v_bfe_u32 v28, v11, 16, 1
; GFX9-NEXT:    v_add3_u32 v28, v28, v11, s6
; GFX9-NEXT:    v_or_b32_e32 v29, 0x400000, v11
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v11, v11
; GFX9-NEXT:    v_cndmask_b32_e32 v11, v28, v29, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v28, 16, v12
; GFX9-NEXT:    v_add_f32_e32 v28, 0x40c00000, v28
; GFX9-NEXT:    v_bfe_u32 v29, v28, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v12, 0xffff0000, v12
; GFX9-NEXT:    v_add3_u32 v29, v29, v28, s6
; GFX9-NEXT:    v_or_b32_e32 v30, 0x400000, v28
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v28, v28
; GFX9-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; GFX9-NEXT:    v_cndmask_b32_e32 v28, v29, v30, vcc
; GFX9-NEXT:    v_bfe_u32 v29, v12, 16, 1
; GFX9-NEXT:    v_add3_u32 v29, v29, v12, s6
; GFX9-NEXT:    v_or_b32_e32 v30, 0x400000, v12
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v12, v12
; GFX9-NEXT:    v_cndmask_b32_e32 v12, v29, v30, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v29, 16, v13
; GFX9-NEXT:    v_add_f32_e32 v29, 0x40c00000, v29
; GFX9-NEXT:    v_bfe_u32 v30, v29, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v13, 0xffff0000, v13
; GFX9-NEXT:    v_add3_u32 v30, v30, v29, s6
; GFX9-NEXT:    v_or_b32_e32 v31, 0x400000, v29
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v29, v29
; GFX9-NEXT:    v_add_f32_e32 v13, 0x40c00000, v13
; GFX9-NEXT:    v_cndmask_b32_e32 v29, v30, v31, vcc
; GFX9-NEXT:    v_bfe_u32 v30, v13, 16, 1
; GFX9-NEXT:    v_add3_u32 v30, v30, v13, s6
; GFX9-NEXT:    v_or_b32_e32 v31, 0x400000, v13
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v13, v13
; GFX9-NEXT:    v_cndmask_b32_e32 v13, v30, v31, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v30, 16, v14
; GFX9-NEXT:    v_add_f32_e32 v30, 0x40c00000, v30
; GFX9-NEXT:    v_bfe_u32 v31, v30, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v14, 0xffff0000, v14
; GFX9-NEXT:    v_add3_u32 v31, v31, v30, s6
; GFX9-NEXT:    v_or_b32_e32 v32, 0x400000, v30
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v30, v30
; GFX9-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; GFX9-NEXT:    v_cndmask_b32_e32 v30, v31, v32, vcc
; GFX9-NEXT:    v_bfe_u32 v31, v14, 16, 1
; GFX9-NEXT:    v_add3_u32 v31, v31, v14, s6
; GFX9-NEXT:    v_or_b32_e32 v32, 0x400000, v14
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v14, v14
; GFX9-NEXT:    v_cndmask_b32_e32 v14, v31, v32, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v31, 16, v15
; GFX9-NEXT:    v_add_f32_e32 v31, 0x40c00000, v31
; GFX9-NEXT:    v_bfe_u32 v32, v31, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v15, 0xffff0000, v15
; GFX9-NEXT:    v_add3_u32 v32, v32, v31, s6
; GFX9-NEXT:    v_or_b32_e32 v33, 0x400000, v31
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v31, v31
; GFX9-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; GFX9-NEXT:    v_cndmask_b32_e32 v31, v32, v33, vcc
; GFX9-NEXT:    v_bfe_u32 v32, v15, 16, 1
; GFX9-NEXT:    v_add3_u32 v32, v32, v15, s6
; GFX9-NEXT:    v_or_b32_e32 v33, 0x400000, v15
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v15, v15
; GFX9-NEXT:    v_cndmask_b32_e32 v15, v32, v33, vcc
; GFX9-NEXT:    s_mov_b32 s6, 0x7060302
; GFX9-NEXT:    v_perm_b32 v15, v15, v31, s6
; GFX9-NEXT:    v_perm_b32 v14, v14, v30, s6
; GFX9-NEXT:    v_perm_b32 v13, v13, v29, s6
; GFX9-NEXT:    v_perm_b32 v12, v12, v28, s6
; GFX9-NEXT:    v_perm_b32 v11, v11, v27, s6
; GFX9-NEXT:    v_perm_b32 v10, v10, v26, s6
; GFX9-NEXT:    v_perm_b32 v9, v9, v25, s6
; GFX9-NEXT:    v_perm_b32 v8, v8, v24, s6
; GFX9-NEXT:    v_perm_b32 v7, v7, v23, s6
; GFX9-NEXT:    v_perm_b32 v6, v6, v22, s6
; GFX9-NEXT:    v_perm_b32 v5, v5, v21, s6
; GFX9-NEXT:    v_perm_b32 v4, v4, v20, s6
; GFX9-NEXT:    v_perm_b32 v3, v3, v19, s6
; GFX9-NEXT:    v_perm_b32 v2, v2, v18, s6
; GFX9-NEXT:    v_perm_b32 v1, v1, v17, s6
; GFX9-NEXT:    v_perm_b32 v0, v0, v16, s6
; GFX9-NEXT:  .LBB41_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: v_bitcast_v32bf16_to_v32f16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v16
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB41_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_lshlrev_b32_e32 v17, 16, v1
; GFX11-NEXT:    v_lshlrev_b32_e32 v16, 16, v0
; GFX11-NEXT:    v_lshlrev_b32_e32 v24, 16, v5
; GFX11-NEXT:    v_lshlrev_b32_e32 v26, 16, v7
; GFX11-NEXT:    v_lshlrev_b32_e32 v28, 16, v9
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_dual_add_f32 v17, 0x40c00000, v17 :: v_dual_add_f32 v16, 0x40c00000, v16
; GFX11-NEXT:    v_lshlrev_b32_e32 v30, 16, v11
; GFX11-NEXT:    v_dual_add_f32 v24, 0x40c00000, v24 :: v_dual_lshlrev_b32 v25, 16, v6
; GFX11-NEXT:    v_bfe_u32 v21, v17, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_bfe_u32 v19, v16, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v16
; GFX11-NEXT:    v_add_f32_e32 v25, 0x40c00000, v25
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v16, v16
; GFX11-NEXT:    v_add3_u32 v21, v21, v17, 0x7fff
; GFX11-NEXT:    v_add3_u32 v19, v19, v16, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; GFX11-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; GFX11-NEXT:    v_dual_add_f32 v26, 0x40c00000, v26 :: v_dual_lshlrev_b32 v27, 16, v8
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-NEXT:    v_cndmask_b32_e32 v16, v19, v22, vcc_lo
; GFX11-NEXT:    v_or_b32_e32 v19, 0x400000, v17
; GFX11-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX11-NEXT:    v_dual_add_f32 v1, 0x40c00000, v1 :: v_dual_lshlrev_b32 v22, 16, v3
; GFX11-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; GFX11-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; GFX11-NEXT:    v_and_b32_e32 v8, 0xffff0000, v8
; GFX11-NEXT:    v_add_f32_e32 v27, 0x40c00000, v27
; GFX11-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GFX11-NEXT:    v_lshlrev_b32_e32 v29, 16, v10
; GFX11-NEXT:    v_bfe_u32 v20, v0, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v23, 0x400000, v0
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX11-NEXT:    v_dual_add_f32 v28, 0x40c00000, v28 :: v_dual_add_f32 v29, 0x40c00000, v29
; GFX11-NEXT:    v_add3_u32 v20, v20, v0, 0x7fff
; GFX11-NEXT:    v_and_b32_e32 v10, 0xffff0000, v10
; GFX11-NEXT:    v_dual_add_f32 v30, 0x40c00000, v30 :: v_dual_lshlrev_b32 v31, 16, v12
; GFX11-NEXT:    v_and_b32_e32 v12, 0xffff0000, v12
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_dual_cndmask_b32 v0, v20, v23 :: v_dual_lshlrev_b32 v23, 16, v4
; GFX11-NEXT:    v_bfe_u32 v20, v1, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v17, v17
; GFX11-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; GFX11-NEXT:    v_dual_add_f32 v10, 0x40c00000, v10 :: v_dual_add_f32 v23, 0x40c00000, v23
; GFX11-NEXT:    v_perm_b32 v0, v0, v16, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v17, v21, v19, vcc_lo
; GFX11-NEXT:    v_add3_u32 v19, v20, v1, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-NEXT:    v_lshlrev_b32_e32 v18, 16, v2
; GFX11-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; GFX11-NEXT:    v_dual_add_f32 v4, 0x40c00000, v4 :: v_dual_add_f32 v31, 0x40c00000, v31
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_dual_cndmask_b32 v1, v19, v20 :: v_dual_add_f32 v18, 0x40c00000, v18
; GFX11-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GFX11-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; GFX11-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; GFX11-NEXT:    v_add_f32_e32 v22, 0x40c00000, v22
; GFX11-NEXT:    v_bfe_u32 v21, v18, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v18
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX11-NEXT:    v_or_b32_e32 v33, 0x400000, v31
; GFX11-NEXT:    v_add3_u32 v19, v21, v18, 0x7fff
; GFX11-NEXT:    v_bfe_u32 v21, v2, 16, 1
; GFX11-NEXT:    v_bfe_u32 v34, v12, 16, 1
; GFX11-NEXT:    v_perm_b32 v1, v1, v17, 0x7060302
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_dual_cndmask_b32 v18, v19, v20 :: v_dual_and_b32 v7, 0xffff0000, v7
; GFX11-NEXT:    v_add3_u32 v19, v21, v2, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v2
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-NEXT:    v_bfe_u32 v21, v22, 16, 1
; GFX11-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GFX11-NEXT:    v_and_b32_e32 v9, 0xffff0000, v9
; GFX11-NEXT:    v_dual_cndmask_b32 v2, v19, v20 :: v_dual_and_b32 v11, 0xffff0000, v11
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-NEXT:    v_add3_u32 v19, v21, v22, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v20, 0x400000, v22
; GFX11-NEXT:    v_bfe_u32 v21, v3, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v22, v22
; GFX11-NEXT:    v_bfe_u32 v22, v23, 16, 1
; GFX11-NEXT:    v_add_f32_e32 v9, 0x40c00000, v9
; GFX11-NEXT:    v_perm_b32 v2, v2, v18, 0x7060302
; GFX11-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; GFX11-NEXT:    v_cndmask_b32_e32 v19, v19, v20, vcc_lo
; GFX11-NEXT:    v_add3_u32 v20, v21, v3, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v3
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-NEXT:    v_or_b32_e32 v32, 0x400000, v11
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-NEXT:    v_cndmask_b32_e32 v3, v20, v21, vcc_lo
; GFX11-NEXT:    v_add3_u32 v20, v22, v23, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v21, 0x400000, v23
; GFX11-NEXT:    v_bfe_u32 v22, v4, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v23, v23
; GFX11-NEXT:    v_bfe_u32 v23, v24, 16, 1
; GFX11-NEXT:    v_perm_b32 v3, v3, v19, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v20, v20, v21, vcc_lo
; GFX11-NEXT:    v_add3_u32 v21, v22, v4, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v4
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-NEXT:    v_cndmask_b32_e32 v4, v21, v22, vcc_lo
; GFX11-NEXT:    v_add3_u32 v21, v23, v24, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v22, 0x400000, v24
; GFX11-NEXT:    v_bfe_u32 v23, v5, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v24, v24
; GFX11-NEXT:    v_bfe_u32 v24, v25, 16, 1
; GFX11-NEXT:    v_perm_b32 v4, v4, v20, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v21, v21, v22, vcc_lo
; GFX11-NEXT:    v_add3_u32 v22, v23, v5, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v23, 0x400000, v5
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-NEXT:    v_cndmask_b32_e32 v5, v22, v23, vcc_lo
; GFX11-NEXT:    v_add3_u32 v22, v24, v25, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v23, 0x400000, v25
; GFX11-NEXT:    v_bfe_u32 v24, v6, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v25, v25
; GFX11-NEXT:    v_bfe_u32 v25, v26, 16, 1
; GFX11-NEXT:    v_perm_b32 v5, v5, v21, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v22, v22, v23, vcc_lo
; GFX11-NEXT:    v_add3_u32 v23, v24, v6, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v24, 0x400000, v6
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-NEXT:    v_cndmask_b32_e32 v6, v23, v24, vcc_lo
; GFX11-NEXT:    v_add3_u32 v23, v25, v26, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v24, 0x400000, v26
; GFX11-NEXT:    v_bfe_u32 v25, v7, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v26, v26
; GFX11-NEXT:    v_bfe_u32 v26, v27, 16, 1
; GFX11-NEXT:    v_perm_b32 v6, v6, v22, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v23, v23, v24, vcc_lo
; GFX11-NEXT:    v_add3_u32 v24, v25, v7, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v25, 0x400000, v7
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-NEXT:    v_cndmask_b32_e32 v7, v24, v25, vcc_lo
; GFX11-NEXT:    v_add3_u32 v24, v26, v27, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v25, 0x400000, v27
; GFX11-NEXT:    v_bfe_u32 v26, v8, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v27, v27
; GFX11-NEXT:    v_bfe_u32 v27, v28, 16, 1
; GFX11-NEXT:    v_perm_b32 v7, v7, v23, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v24, v24, v25, vcc_lo
; GFX11-NEXT:    v_add3_u32 v25, v26, v8, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v26, 0x400000, v8
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-NEXT:    v_cndmask_b32_e32 v8, v25, v26, vcc_lo
; GFX11-NEXT:    v_add3_u32 v25, v27, v28, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v26, 0x400000, v28
; GFX11-NEXT:    v_bfe_u32 v27, v9, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v28, v28
; GFX11-NEXT:    v_bfe_u32 v28, v29, 16, 1
; GFX11-NEXT:    v_perm_b32 v8, v8, v24, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v25, v25, v26, vcc_lo
; GFX11-NEXT:    v_add3_u32 v26, v27, v9, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v27, 0x400000, v9
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-NEXT:    v_cndmask_b32_e32 v9, v26, v27, vcc_lo
; GFX11-NEXT:    v_add3_u32 v26, v28, v29, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v27, 0x400000, v29
; GFX11-NEXT:    v_bfe_u32 v28, v10, 16, 1
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v29, v29
; GFX11-NEXT:    v_bfe_u32 v29, v30, 16, 1
; GFX11-NEXT:    v_perm_b32 v9, v9, v25, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v26, v26, v27, vcc_lo
; GFX11-NEXT:    v_add3_u32 v27, v28, v10, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v28, 0x400000, v10
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-NEXT:    v_cndmask_b32_e32 v10, v27, v28, vcc_lo
; GFX11-NEXT:    v_add3_u32 v27, v29, v30, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v28, 0x400000, v30
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v30, v30
; GFX11-NEXT:    v_bfe_u32 v30, v31, 16, 1
; GFX11-NEXT:    v_bfe_u32 v29, v11, 16, 1
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_dual_cndmask_b32 v27, v27, v28 :: v_dual_lshlrev_b32 v28, 16, v13
; GFX11-NEXT:    v_add3_u32 v30, v30, v31, 0x7fff
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v31, v31
; GFX11-NEXT:    v_and_b32_e32 v13, 0xffff0000, v13
; GFX11-NEXT:    v_add3_u32 v31, v34, v12, 0x7fff
; GFX11-NEXT:    v_add_f32_e32 v28, 0x40c00000, v28
; GFX11-NEXT:    v_add3_u32 v29, v29, v11, 0x7fff
; GFX11-NEXT:    v_cndmask_b32_e32 v30, v30, v33, vcc_lo
; GFX11-NEXT:    v_or_b32_e32 v33, 0x400000, v12
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v12, v12
; GFX11-NEXT:    v_bfe_u32 v35, v28, 16, 1
; GFX11-NEXT:    v_add_f32_e32 v13, 0x40c00000, v13
; GFX11-NEXT:    v_or_b32_e32 v36, 0x400000, v28
; GFX11-NEXT:    v_cndmask_b32_e32 v12, v31, v33, vcc_lo
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-NEXT:    v_add3_u32 v34, v35, v28, 0x7fff
; GFX11-NEXT:    v_lshlrev_b32_e32 v35, 16, v14
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v28, v28
; GFX11-NEXT:    v_and_b32_e32 v14, 0xffff0000, v14
; GFX11-NEXT:    v_bfe_u32 v37, v13, 16, 1
; GFX11-NEXT:    v_perm_b32 v10, v10, v26, 0x7060302
; GFX11-NEXT:    v_dual_add_f32 v31, 0x40c00000, v35 :: v_dual_cndmask_b32 v28, v34, v36
; GFX11-NEXT:    v_lshlrev_b32_e32 v34, 16, v15
; GFX11-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; GFX11-NEXT:    v_add3_u32 v33, v37, v13, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-NEXT:    v_bfe_u32 v35, v31, 16, 1
; GFX11-NEXT:    v_and_b32_e32 v15, 0xffff0000, v15
; GFX11-NEXT:    v_add_f32_e32 v34, 0x40c00000, v34
; GFX11-NEXT:    v_or_b32_e32 v37, 0x400000, v31
; GFX11-NEXT:    v_bfe_u32 v38, v14, 16, 1
; GFX11-NEXT:    v_add3_u32 v35, v35, v31, 0x7fff
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v31, v31
; GFX11-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; GFX11-NEXT:    v_bfe_u32 v39, v34, 16, 1
; GFX11-NEXT:    v_or_b32_e32 v48, 0x400000, v34
; GFX11-NEXT:    v_or_b32_e32 v36, 0x400000, v13
; GFX11-NEXT:    v_cndmask_b32_e32 v31, v35, v37, vcc_lo
; GFX11-NEXT:    v_add3_u32 v37, v38, v14, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v38, 0x400000, v14
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v14, v14
; GFX11-NEXT:    v_bfe_u32 v35, v15, 16, 1
; GFX11-NEXT:    v_add3_u32 v39, v39, v34, 0x7fff
; GFX11-NEXT:    v_or_b32_e32 v49, 0x400000, v15
; GFX11-NEXT:    v_cndmask_b32_e32 v14, v37, v38, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v34, v34
; GFX11-NEXT:    v_add3_u32 v35, v35, v15, 0x7fff
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_perm_b32 v14, v14, v31, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v34, v39, v48, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v15, v15
; GFX11-NEXT:    v_cndmask_b32_e32 v15, v35, v49, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v13, v13
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_3) | instid1(VALU_DEP_3)
; GFX11-NEXT:    v_perm_b32 v15, v15, v34, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v13, v33, v36, vcc_lo
; GFX11-NEXT:    v_cmp_u_f32_e32 vcc_lo, v11, v11
; GFX11-NEXT:    v_perm_b32 v12, v12, v30, 0x7060302
; GFX11-NEXT:    v_perm_b32 v13, v13, v28, 0x7060302
; GFX11-NEXT:    v_cndmask_b32_e32 v11, v29, v32, vcc_lo
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-NEXT:    v_perm_b32 v11, v11, v27, 0x7060302
; GFX11-NEXT:  .LBB41_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <32 x bfloat> %a, splat (bfloat 0xR40C0)
  %a2 = bitcast <32 x bfloat> %a1 to <32 x half>
  br label %end

cmp.false:
  %a3 = bitcast <32 x bfloat> %a to <32 x half>
  br label %end

end:
  %phi = phi <32 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x half> %phi
}
