# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=amdgcn -mcpu=gfx950 -run-pass='phi-node-elimination,register-coalescer' %s -o - | FileCheck %s

# For now, the eliminate-save-restore pattern can be processed by `register-coalescer`.
# For example, if the input is:
# v_mov tmp, orig         ; save
# orig = op0(tmp)   ...    ; modify (overwrites orig, reads tmp)
# op1(orig, )              ; uses of orig
# v_mov orig, tmp         ; restore
#
# then theoutput is transformed into:
#
# tmp = op0(orig, )        ; write to tmp instead
# op1(tmp)               ; replace uses of orig with tmp
# save and restore movs are dead
#
# This mir test is added to make sure can if `register-coalescer` is changed in the future.

name:            eliminate_save_restore
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: eliminate_save_restore
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $vgpr0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[V_MOV_B32_e32_:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 21, implicit $exec
  ; CHECK-NEXT:   S_BRANCH %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %other:vgpr_32 = V_MOV_B32_e32 42, implicit $exec
  ; CHECK-NEXT:   %orig:vgpr_32 = V_ADD_U32_e32 [[V_MOV_B32_e32_]], %other, implicit $exec
  ; CHECK-NEXT:   dead [[V_MUL_LO_U32_e64_:%[0-9]+]]:vgpr_32 = V_MUL_LO_U32_e64 %orig, %orig, implicit $exec
  ; CHECK-NEXT:   S_BRANCH %bb.1
  bb.0:
    successors: %bb.1(0x40000000)
    liveins: $vgpr0
    %orig_0:vgpr_32 = V_MOV_B32_e32 21, implicit $exec
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.1(0x40000000)
    %tmp:vgpr_32 = PHI %orig_0, %bb.0, %orig_next, %bb.1
    %other:vgpr_32 = V_MOV_B32_e32 42, implicit $exec
    %orig:vgpr_32 = V_ADD_U32_e32 %tmp, %other, implicit $exec
    %unused:vgpr_32 = V_MUL_LO_U32_e64 %orig, %orig, implicit $exec
    %orig_next:vgpr_32 = COPY %tmp, implicit $exec
    S_BRANCH %bb.1
...
