; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --scrub-attributes --version 5
; REQUIRES: amdgpu-registered-target

; RUN: opt -S -mtriple=amdgcn-amd-amdhsa -mcpu=gfx906 -passes='amdgpu-expand-feature-predicates' %s -o - | FileCheck --check-prefix=GFX906 %s
; RUN: opt -S -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1201 -passes='amdgpu-expand-feature-predicates' %s -o - | FileCheck --check-prefix=GFX1201 %s

@llvm.amdgcn.is.gfx906 = external addrspace(1) externally_initialized constant i1
@llvm.amdgcn.is.gfx1201 = external addrspace(1) externally_initialized constant i1

define external void @extern_linkage() {
; GFX906-LABEL: define void @extern_linkage(
; GFX906-SAME: ) #[[ATTR0:[0-9]+]] {
; GFX906-NEXT:  [[ENTRY:.*:]]
; GFX906-NEXT:    ret void
;
; GFX1201-LABEL: define void @extern_linkage(
; GFX1201-SAME: ) #[[ATTR0:[0-9]+]] {
; GFX1201-NEXT:  [[ENTRY:.*:]]
; GFX1201-NEXT:    ret void
;
entry:
  ret void
}

define private void @non_predicated_uses() {
; GFX906-LABEL: define private void @non_predicated_uses(
; GFX906-SAME: ) #[[ATTR0]] {
; GFX906-NEXT:  [[ENTRY:.*:]]
; GFX906-NEXT:    ret void
;
; GFX1201-LABEL: define private void @non_predicated_uses(
; GFX1201-SAME: ) #[[ATTR0]] {
; GFX1201-NEXT:  [[ENTRY:.*:]]
; GFX1201-NEXT:    ret void
;
entry:
  ret void
}

define internal void @remove_on_906() {
; GFX1201-LABEL: define internal void @remove_on_906(
; GFX1201-SAME: ) #[[ATTR0]] {
; GFX1201-NEXT:  [[ENTRY:.*:]]
; GFX1201-NEXT:    ret void
;
entry:
  ret void
}

define internal void @remove_on_1201() {
; GFX906-LABEL: define internal void @remove_on_1201(
; GFX906-SAME: ) #[[ATTR0]] {
; GFX906-NEXT:  [[ENTRY:.*:]]
; GFX906-NEXT:    ret void
;
entry:
  ret void
}

define void @foo() {
; GFX906-LABEL: define void @foo(
; GFX906-SAME: ) #[[ATTR0]] {
; GFX906-NEXT:  [[ENTRY:.*:]]
; GFX906-NEXT:    call void @non_predicated_uses()
; GFX906-NEXT:    br label %[[NOT_GFX1201:.*]]
; GFX906:       [[NOT_GFX1201]]:
; GFX906-NEXT:    br label %[[GFX906:.*]]
; GFX906:       [[GFX906]]:
; GFX906-NEXT:    call void @remove_on_1201()
; GFX906-NEXT:    br label %[[END:.*]]
; GFX906:       [[END]]:
; GFX906-NEXT:    ret void
;
; GFX1201-LABEL: define void @foo(
; GFX1201-SAME: ) #[[ATTR0]] {
; GFX1201-NEXT:  [[ENTRY:.*:]]
; GFX1201-NEXT:    call void @non_predicated_uses()
; GFX1201-NEXT:    br label %[[GFX1201:.*]]
; GFX1201:       [[GFX1201]]:
; GFX1201-NEXT:    call void @remove_on_906()
; GFX1201-NEXT:    br label %[[END:.*]]
; GFX1201:       [[END]]:
; GFX1201-NEXT:    ret void
;
entry:
  call void @non_predicated_uses()
  %0 = load i1, ptr addrspace(1) @llvm.amdgcn.is.gfx1201, align 1
  br i1 %0, label %gfx1201, label %not.gfx1201

gfx1201:
  call void @remove_on_906()
  br label %end

not.gfx1201:
  %1 = load i1, ptr addrspace(1) @llvm.amdgcn.is.gfx906, align 1
  br i1 %1, label %gfx906, label %end

gfx906:
  call void @remove_on_1201()
  br label %end

end:
  ret void
}
