; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5

; RUN: llc -mtriple=amdgcn -mcpu=tahiti < %s | FileCheck -check-prefix=SI %s
; RUN: llc -mtriple=amdgcn -mcpu=tonga < %s | FileCheck -check-prefix=VI %s
; RUN: llc -mtriple=amdgcn -mcpu=gfx900 < %s | FileCheck -check-prefix=GFX9 %s
; RUN: llc -mtriple=amdgcn -mcpu=gfx1100 -mattr=+real-true16 < %s | FileCheck -check-prefixes=GFX11,GFX11-TRUE16 %s
; RUN: llc -mtriple=amdgcn -mcpu=gfx1100 -mattr=-real-true16 < %s | FileCheck -check-prefixes=GFX11,GFX11-FAKE16 %s

define <8 x float> @bitcast_v8i32_to_v8f32(<8 x i32> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v8i32_to_v8f32:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:  ; %bb.1: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v7
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v5
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v3
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v1
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:  ; %bb.2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v8i32_to_v8f32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v7, vcc, 3, v7
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_add_u32_e32 v5, vcc, 3, v5
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_add_u32_e32 v3, vcc, 3, v3
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_add_u32_e32 v1, vcc, 3, v1
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:  ; %bb.2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v8i32_to_v8f32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_u32_e32 v7, 3, v7
; GFX9-NEXT:    v_add_u32_e32 v6, 3, v6
; GFX9-NEXT:    v_add_u32_e32 v5, 3, v5
; GFX9-NEXT:    v_add_u32_e32 v4, 3, v4
; GFX9-NEXT:    v_add_u32_e32 v3, 3, v3
; GFX9-NEXT:    v_add_u32_e32 v2, 3, v2
; GFX9-NEXT:    v_add_u32_e32 v1, 3, v1
; GFX9-NEXT:    v_add_u32_e32 v0, 3, v0
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v8i32_to_v8f32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB0_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_nc_u32_e32 v7, 3, v7
; GFX11-NEXT:    v_add_nc_u32_e32 v6, 3, v6
; GFX11-NEXT:    v_add_nc_u32_e32 v5, 3, v5
; GFX11-NEXT:    v_add_nc_u32_e32 v4, 3, v4
; GFX11-NEXT:    v_add_nc_u32_e32 v3, 3, v3
; GFX11-NEXT:    v_add_nc_u32_e32 v2, 3, v2
; GFX11-NEXT:    v_add_nc_u32_e32 v1, 3, v1
; GFX11-NEXT:    v_add_nc_u32_e32 v0, 3, v0
; GFX11-NEXT:  .LBB0_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <8 x i32> %a, splat (i32 3)
  %a2 = bitcast <8 x i32> %a1 to <8 x float>
  br label %end

cmp.false:
  %a3 = bitcast <8 x i32> %a to <8 x float>
  br label %end

end:
  %phi = phi <8 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x float> %phi
}

define inreg <8 x float> @bitcast_v8i32_to_v8f32_scalar(<8 x i32> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v8i32_to_v8f32_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB1_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_cbranch_execnz .LBB1_3
; SI-NEXT:  .LBB1_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s23, s23, 3
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_add_i32 s21, s21, 3
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_add_i32 s19, s19, 3
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_add_i32 s17, s17, 3
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:  .LBB1_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v2, s18
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v4, s20
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v6, s22
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB1_4:
; SI-NEXT:    s_branch .LBB1_2
;
; VI-LABEL: bitcast_v8i32_to_v8f32_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB1_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB1_3
; VI-NEXT:  .LBB1_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s23, s23, 3
; VI-NEXT:    s_add_i32 s22, s22, 3
; VI-NEXT:    s_add_i32 s21, s21, 3
; VI-NEXT:    s_add_i32 s20, s20, 3
; VI-NEXT:    s_add_i32 s19, s19, 3
; VI-NEXT:    s_add_i32 s18, s18, 3
; VI-NEXT:    s_add_i32 s17, s17, 3
; VI-NEXT:    s_add_i32 s16, s16, 3
; VI-NEXT:  .LBB1_3: ; %end
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB1_4:
; VI-NEXT:    s_branch .LBB1_2
;
; GFX9-LABEL: bitcast_v8i32_to_v8f32_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB1_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB1_3
; GFX9-NEXT:  .LBB1_2: ; %cmp.true
; GFX9-NEXT:    s_add_i32 s23, s23, 3
; GFX9-NEXT:    s_add_i32 s22, s22, 3
; GFX9-NEXT:    s_add_i32 s21, s21, 3
; GFX9-NEXT:    s_add_i32 s20, s20, 3
; GFX9-NEXT:    s_add_i32 s19, s19, 3
; GFX9-NEXT:    s_add_i32 s18, s18, 3
; GFX9-NEXT:    s_add_i32 s17, s17, 3
; GFX9-NEXT:    s_add_i32 s16, s16, 3
; GFX9-NEXT:  .LBB1_3: ; %end
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB1_4:
; GFX9-NEXT:    s_branch .LBB1_2
;
; GFX11-LABEL: bitcast_v8i32_to_v8f32_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s4, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB1_4
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s4
; GFX11-NEXT:    s_cbranch_vccnz .LBB1_3
; GFX11-NEXT:  .LBB1_2: ; %cmp.true
; GFX11-NEXT:    s_add_i32 s19, s19, 3
; GFX11-NEXT:    s_add_i32 s18, s18, 3
; GFX11-NEXT:    s_add_i32 s17, s17, 3
; GFX11-NEXT:    s_add_i32 s16, s16, 3
; GFX11-NEXT:    s_add_i32 s3, s3, 3
; GFX11-NEXT:    s_add_i32 s2, s2, 3
; GFX11-NEXT:    s_add_i32 s1, s1, 3
; GFX11-NEXT:    s_add_i32 s0, s0, 3
; GFX11-NEXT:  .LBB1_3: ; %end
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s16 :: v_dual_mov_b32 v5, s17
; GFX11-NEXT:    v_dual_mov_b32 v6, s18 :: v_dual_mov_b32 v7, s19
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB1_4:
; GFX11-NEXT:    s_branch .LBB1_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <8 x i32> %a, splat (i32 3)
  %a2 = bitcast <8 x i32> %a1 to <8 x float>
  br label %end

cmp.false:
  %a3 = bitcast <8 x i32> %a to <8 x float>
  br label %end

end:
  %phi = phi <8 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x float> %phi
}

define <8 x i32> @bitcast_v8f32_to_v8i32(<8 x float> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v8f32_to_v8i32:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:  ; %bb.1: ; %cmp.true
; SI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; SI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; SI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; SI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; SI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; SI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; SI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; SI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; SI-NEXT:  ; %bb.2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v8f32_to_v8i32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; VI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; VI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; VI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; VI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; VI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; VI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; VI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; VI-NEXT:  ; %bb.2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v8f32_to_v8i32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e32 v7, 1.0, v7
; GFX9-NEXT:    v_add_f32_e32 v6, 1.0, v6
; GFX9-NEXT:    v_add_f32_e32 v5, 1.0, v5
; GFX9-NEXT:    v_add_f32_e32 v4, 1.0, v4
; GFX9-NEXT:    v_add_f32_e32 v3, 1.0, v3
; GFX9-NEXT:    v_add_f32_e32 v2, 1.0, v2
; GFX9-NEXT:    v_add_f32_e32 v1, 1.0, v1
; GFX9-NEXT:    v_add_f32_e32 v0, 1.0, v0
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v8f32_to_v8i32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_dual_add_f32 v7, 1.0, v7 :: v_dual_add_f32 v6, 1.0, v6
; GFX11-NEXT:    v_dual_add_f32 v5, 1.0, v5 :: v_dual_add_f32 v4, 1.0, v4
; GFX11-NEXT:    v_dual_add_f32 v3, 1.0, v3 :: v_dual_add_f32 v2, 1.0, v2
; GFX11-NEXT:    v_dual_add_f32 v1, 1.0, v1 :: v_dual_add_f32 v0, 1.0, v0
; GFX11-NEXT:  ; %bb.2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <8 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <8 x float> %a1 to <8 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <8 x float> %a to <8 x i32>
  br label %end

end:
  %phi = phi <8 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x i32> %phi
}

define inreg <8 x i32> @bitcast_v8f32_to_v8i32_scalar(<8 x float> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v8f32_to_v8i32_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB3_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_cbranch_execnz .LBB3_4
; SI-NEXT:  .LBB3_2: ; %cmp.true
; SI-NEXT:    v_add_f32_e64 v7, s23, 1.0
; SI-NEXT:    v_add_f32_e64 v6, s22, 1.0
; SI-NEXT:    v_add_f32_e64 v5, s21, 1.0
; SI-NEXT:    v_add_f32_e64 v4, s20, 1.0
; SI-NEXT:    v_add_f32_e64 v3, s19, 1.0
; SI-NEXT:    v_add_f32_e64 v2, s18, 1.0
; SI-NEXT:    v_add_f32_e64 v1, s17, 1.0
; SI-NEXT:    v_add_f32_e64 v0, s16, 1.0
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB3_3:
; SI-NEXT:    s_branch .LBB3_2
; SI-NEXT:  .LBB3_4:
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v2, s18
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v4, s20
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v6, s22
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v8f32_to_v8i32_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB3_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB3_4
; VI-NEXT:  .LBB3_2: ; %cmp.true
; VI-NEXT:    v_add_f32_e64 v7, s23, 1.0
; VI-NEXT:    v_add_f32_e64 v6, s22, 1.0
; VI-NEXT:    v_add_f32_e64 v5, s21, 1.0
; VI-NEXT:    v_add_f32_e64 v4, s20, 1.0
; VI-NEXT:    v_add_f32_e64 v3, s19, 1.0
; VI-NEXT:    v_add_f32_e64 v2, s18, 1.0
; VI-NEXT:    v_add_f32_e64 v1, s17, 1.0
; VI-NEXT:    v_add_f32_e64 v0, s16, 1.0
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB3_3:
; VI-NEXT:    s_branch .LBB3_2
; VI-NEXT:  .LBB3_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v8f32_to_v8i32_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB3_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB3_4
; GFX9-NEXT:  .LBB3_2: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e64 v7, s23, 1.0
; GFX9-NEXT:    v_add_f32_e64 v6, s22, 1.0
; GFX9-NEXT:    v_add_f32_e64 v5, s21, 1.0
; GFX9-NEXT:    v_add_f32_e64 v4, s20, 1.0
; GFX9-NEXT:    v_add_f32_e64 v3, s19, 1.0
; GFX9-NEXT:    v_add_f32_e64 v2, s18, 1.0
; GFX9-NEXT:    v_add_f32_e64 v1, s17, 1.0
; GFX9-NEXT:    v_add_f32_e64 v0, s16, 1.0
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB3_3:
; GFX9-NEXT:    s_branch .LBB3_2
; GFX9-NEXT:  .LBB3_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v8f32_to_v8i32_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s7, s19
; GFX11-NEXT:    s_mov_b32 s6, s18
; GFX11-NEXT:    s_mov_b32 s5, s17
; GFX11-NEXT:    s_mov_b32 s4, s16
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s8, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB3_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-NEXT:    s_cbranch_vccnz .LBB3_4
; GFX11-NEXT:  .LBB3_2: ; %cmp.true
; GFX11-NEXT:    v_add_f32_e64 v7, s7, 1.0
; GFX11-NEXT:    v_add_f32_e64 v6, s6, 1.0
; GFX11-NEXT:    v_add_f32_e64 v5, s5, 1.0
; GFX11-NEXT:    v_add_f32_e64 v4, s4, 1.0
; GFX11-NEXT:    v_add_f32_e64 v3, s3, 1.0
; GFX11-NEXT:    v_add_f32_e64 v2, s2, 1.0
; GFX11-NEXT:    v_add_f32_e64 v1, s1, 1.0
; GFX11-NEXT:    v_add_f32_e64 v0, s0, 1.0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB3_3:
; GFX11-NEXT:    s_branch .LBB3_2
; GFX11-NEXT:  .LBB3_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <8 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <8 x float> %a1 to <8 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <8 x float> %a to <8 x i32>
  br label %end

end:
  %phi = phi <8 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x i32> %phi
}

define <4 x i64> @bitcast_v8i32_to_v4i64(<8 x i32> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v8i32_to_v4i64:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:  ; %bb.1: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v7
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v5
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v3
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v1
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:  ; %bb.2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v8i32_to_v4i64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v7, vcc, 3, v7
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_add_u32_e32 v5, vcc, 3, v5
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_add_u32_e32 v3, vcc, 3, v3
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_add_u32_e32 v1, vcc, 3, v1
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:  ; %bb.2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v8i32_to_v4i64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_u32_e32 v7, 3, v7
; GFX9-NEXT:    v_add_u32_e32 v6, 3, v6
; GFX9-NEXT:    v_add_u32_e32 v5, 3, v5
; GFX9-NEXT:    v_add_u32_e32 v4, 3, v4
; GFX9-NEXT:    v_add_u32_e32 v3, 3, v3
; GFX9-NEXT:    v_add_u32_e32 v2, 3, v2
; GFX9-NEXT:    v_add_u32_e32 v1, 3, v1
; GFX9-NEXT:    v_add_u32_e32 v0, 3, v0
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v8i32_to_v4i64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB4_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_nc_u32_e32 v7, 3, v7
; GFX11-NEXT:    v_add_nc_u32_e32 v6, 3, v6
; GFX11-NEXT:    v_add_nc_u32_e32 v5, 3, v5
; GFX11-NEXT:    v_add_nc_u32_e32 v4, 3, v4
; GFX11-NEXT:    v_add_nc_u32_e32 v3, 3, v3
; GFX11-NEXT:    v_add_nc_u32_e32 v2, 3, v2
; GFX11-NEXT:    v_add_nc_u32_e32 v1, 3, v1
; GFX11-NEXT:    v_add_nc_u32_e32 v0, 3, v0
; GFX11-NEXT:  .LBB4_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <8 x i32> %a, splat (i32 3)
  %a2 = bitcast <8 x i32> %a1 to <4 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <8 x i32> %a to <4 x i64>
  br label %end

end:
  %phi = phi <4 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x i64> %phi
}

define inreg <4 x i64> @bitcast_v8i32_to_v4i64_scalar(<8 x i32> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v8i32_to_v4i64_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB5_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_cbranch_execnz .LBB5_3
; SI-NEXT:  .LBB5_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s23, s23, 3
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_add_i32 s21, s21, 3
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_add_i32 s19, s19, 3
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_add_i32 s17, s17, 3
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:  .LBB5_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v2, s18
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v4, s20
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v6, s22
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB5_4:
; SI-NEXT:    s_branch .LBB5_2
;
; VI-LABEL: bitcast_v8i32_to_v4i64_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB5_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB5_3
; VI-NEXT:  .LBB5_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s23, s23, 3
; VI-NEXT:    s_add_i32 s22, s22, 3
; VI-NEXT:    s_add_i32 s21, s21, 3
; VI-NEXT:    s_add_i32 s20, s20, 3
; VI-NEXT:    s_add_i32 s19, s19, 3
; VI-NEXT:    s_add_i32 s18, s18, 3
; VI-NEXT:    s_add_i32 s17, s17, 3
; VI-NEXT:    s_add_i32 s16, s16, 3
; VI-NEXT:  .LBB5_3: ; %end
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB5_4:
; VI-NEXT:    s_branch .LBB5_2
;
; GFX9-LABEL: bitcast_v8i32_to_v4i64_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB5_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB5_3
; GFX9-NEXT:  .LBB5_2: ; %cmp.true
; GFX9-NEXT:    s_add_i32 s23, s23, 3
; GFX9-NEXT:    s_add_i32 s22, s22, 3
; GFX9-NEXT:    s_add_i32 s21, s21, 3
; GFX9-NEXT:    s_add_i32 s20, s20, 3
; GFX9-NEXT:    s_add_i32 s19, s19, 3
; GFX9-NEXT:    s_add_i32 s18, s18, 3
; GFX9-NEXT:    s_add_i32 s17, s17, 3
; GFX9-NEXT:    s_add_i32 s16, s16, 3
; GFX9-NEXT:  .LBB5_3: ; %end
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB5_4:
; GFX9-NEXT:    s_branch .LBB5_2
;
; GFX11-LABEL: bitcast_v8i32_to_v4i64_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s4, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB5_4
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s4
; GFX11-NEXT:    s_cbranch_vccnz .LBB5_3
; GFX11-NEXT:  .LBB5_2: ; %cmp.true
; GFX11-NEXT:    s_add_i32 s19, s19, 3
; GFX11-NEXT:    s_add_i32 s18, s18, 3
; GFX11-NEXT:    s_add_i32 s17, s17, 3
; GFX11-NEXT:    s_add_i32 s16, s16, 3
; GFX11-NEXT:    s_add_i32 s3, s3, 3
; GFX11-NEXT:    s_add_i32 s2, s2, 3
; GFX11-NEXT:    s_add_i32 s1, s1, 3
; GFX11-NEXT:    s_add_i32 s0, s0, 3
; GFX11-NEXT:  .LBB5_3: ; %end
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s16 :: v_dual_mov_b32 v5, s17
; GFX11-NEXT:    v_dual_mov_b32 v6, s18 :: v_dual_mov_b32 v7, s19
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB5_4:
; GFX11-NEXT:    s_branch .LBB5_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <8 x i32> %a, splat (i32 3)
  %a2 = bitcast <8 x i32> %a1 to <4 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <8 x i32> %a to <4 x i64>
  br label %end

end:
  %phi = phi <4 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x i64> %phi
}

define <8 x i32> @bitcast_v4i64_to_v8i32(<4 x i64> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v4i64_to_v8i32:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:  ; %bb.1: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; SI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; SI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; SI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; SI-NEXT:  ; %bb.2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v4i64_to_v8i32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-NEXT:  ; %bb.2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v4i64_to_v8i32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_co_u32_e32 v6, vcc, 3, v6
; GFX9-NEXT:    v_addc_co_u32_e32 v7, vcc, 0, v7, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v4, vcc, 3, v4
; GFX9-NEXT:    v_addc_co_u32_e32 v5, vcc, 0, v5, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v2, vcc, 3, v2
; GFX9-NEXT:    v_addc_co_u32_e32 v3, vcc, 0, v3, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v0, vcc, 3, v0
; GFX9-NEXT:    v_addc_co_u32_e32 v1, vcc, 0, v1, vcc
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v4i64_to_v8i32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB6_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_co_u32 v6, vcc_lo, v6, 3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_co_ci_u32_e64 v7, null, 0, v7, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v4, vcc_lo, v4, 3
; GFX11-NEXT:    v_add_co_ci_u32_e64 v5, null, 0, v5, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v2, vcc_lo, v2, 3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_co_ci_u32_e64 v3, null, 0, v3, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v0, vcc_lo, v0, 3
; GFX11-NEXT:    v_add_co_ci_u32_e64 v1, null, 0, v1, vcc_lo
; GFX11-NEXT:  .LBB6_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <4 x i64> %a, splat (i64 3)
  %a2 = bitcast <4 x i64> %a1 to <8 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <4 x i64> %a to <8 x i32>
  br label %end

end:
  %phi = phi <8 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x i32> %phi
}

define inreg <8 x i32> @bitcast_v4i64_to_v8i32_scalar(<4 x i64> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v4i64_to_v8i32_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB7_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_cbranch_execnz .LBB7_3
; SI-NEXT:  .LBB7_2: ; %cmp.true
; SI-NEXT:    s_add_u32 s22, s22, 3
; SI-NEXT:    s_addc_u32 s23, s23, 0
; SI-NEXT:    s_add_u32 s20, s20, 3
; SI-NEXT:    s_addc_u32 s21, s21, 0
; SI-NEXT:    s_add_u32 s18, s18, 3
; SI-NEXT:    s_addc_u32 s19, s19, 0
; SI-NEXT:    s_add_u32 s16, s16, 3
; SI-NEXT:    s_addc_u32 s17, s17, 0
; SI-NEXT:  .LBB7_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v2, s18
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v4, s20
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v6, s22
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB7_4:
; SI-NEXT:    s_branch .LBB7_2
;
; VI-LABEL: bitcast_v4i64_to_v8i32_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB7_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB7_3
; VI-NEXT:  .LBB7_2: ; %cmp.true
; VI-NEXT:    s_add_u32 s22, s22, 3
; VI-NEXT:    s_addc_u32 s23, s23, 0
; VI-NEXT:    s_add_u32 s20, s20, 3
; VI-NEXT:    s_addc_u32 s21, s21, 0
; VI-NEXT:    s_add_u32 s18, s18, 3
; VI-NEXT:    s_addc_u32 s19, s19, 0
; VI-NEXT:    s_add_u32 s16, s16, 3
; VI-NEXT:    s_addc_u32 s17, s17, 0
; VI-NEXT:  .LBB7_3: ; %end
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB7_4:
; VI-NEXT:    s_branch .LBB7_2
;
; GFX9-LABEL: bitcast_v4i64_to_v8i32_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB7_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB7_3
; GFX9-NEXT:  .LBB7_2: ; %cmp.true
; GFX9-NEXT:    s_add_u32 s22, s22, 3
; GFX9-NEXT:    s_addc_u32 s23, s23, 0
; GFX9-NEXT:    s_add_u32 s20, s20, 3
; GFX9-NEXT:    s_addc_u32 s21, s21, 0
; GFX9-NEXT:    s_add_u32 s18, s18, 3
; GFX9-NEXT:    s_addc_u32 s19, s19, 0
; GFX9-NEXT:    s_add_u32 s16, s16, 3
; GFX9-NEXT:    s_addc_u32 s17, s17, 0
; GFX9-NEXT:  .LBB7_3: ; %end
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB7_4:
; GFX9-NEXT:    s_branch .LBB7_2
;
; GFX11-LABEL: bitcast_v4i64_to_v8i32_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s4, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB7_4
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s4
; GFX11-NEXT:    s_cbranch_vccnz .LBB7_3
; GFX11-NEXT:  .LBB7_2: ; %cmp.true
; GFX11-NEXT:    s_add_u32 s18, s18, 3
; GFX11-NEXT:    s_addc_u32 s19, s19, 0
; GFX11-NEXT:    s_add_u32 s16, s16, 3
; GFX11-NEXT:    s_addc_u32 s17, s17, 0
; GFX11-NEXT:    s_add_u32 s2, s2, 3
; GFX11-NEXT:    s_addc_u32 s3, s3, 0
; GFX11-NEXT:    s_add_u32 s0, s0, 3
; GFX11-NEXT:    s_addc_u32 s1, s1, 0
; GFX11-NEXT:  .LBB7_3: ; %end
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s16 :: v_dual_mov_b32 v5, s17
; GFX11-NEXT:    v_dual_mov_b32 v6, s18 :: v_dual_mov_b32 v7, s19
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB7_4:
; GFX11-NEXT:    s_branch .LBB7_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <4 x i64> %a, splat (i64 3)
  %a2 = bitcast <4 x i64> %a1 to <8 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <4 x i64> %a to <8 x i32>
  br label %end

end:
  %phi = phi <8 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x i32> %phi
}

define <4 x double> @bitcast_v8i32_to_v4f64(<8 x i32> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v8i32_to_v4f64:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:  ; %bb.1: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v7
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v5
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v3
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v1
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:  ; %bb.2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v8i32_to_v4f64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v7, vcc, 3, v7
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_add_u32_e32 v5, vcc, 3, v5
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_add_u32_e32 v3, vcc, 3, v3
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_add_u32_e32 v1, vcc, 3, v1
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:  ; %bb.2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v8i32_to_v4f64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_u32_e32 v7, 3, v7
; GFX9-NEXT:    v_add_u32_e32 v6, 3, v6
; GFX9-NEXT:    v_add_u32_e32 v5, 3, v5
; GFX9-NEXT:    v_add_u32_e32 v4, 3, v4
; GFX9-NEXT:    v_add_u32_e32 v3, 3, v3
; GFX9-NEXT:    v_add_u32_e32 v2, 3, v2
; GFX9-NEXT:    v_add_u32_e32 v1, 3, v1
; GFX9-NEXT:    v_add_u32_e32 v0, 3, v0
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v8i32_to_v4f64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB8_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_nc_u32_e32 v7, 3, v7
; GFX11-NEXT:    v_add_nc_u32_e32 v6, 3, v6
; GFX11-NEXT:    v_add_nc_u32_e32 v5, 3, v5
; GFX11-NEXT:    v_add_nc_u32_e32 v4, 3, v4
; GFX11-NEXT:    v_add_nc_u32_e32 v3, 3, v3
; GFX11-NEXT:    v_add_nc_u32_e32 v2, 3, v2
; GFX11-NEXT:    v_add_nc_u32_e32 v1, 3, v1
; GFX11-NEXT:    v_add_nc_u32_e32 v0, 3, v0
; GFX11-NEXT:  .LBB8_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <8 x i32> %a, splat (i32 3)
  %a2 = bitcast <8 x i32> %a1 to <4 x double>
  br label %end

cmp.false:
  %a3 = bitcast <8 x i32> %a to <4 x double>
  br label %end

end:
  %phi = phi <4 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x double> %phi
}

define inreg <4 x double> @bitcast_v8i32_to_v4f64_scalar(<8 x i32> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v8i32_to_v4f64_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB9_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_cbranch_execnz .LBB9_3
; SI-NEXT:  .LBB9_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s23, s23, 3
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_add_i32 s21, s21, 3
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_add_i32 s19, s19, 3
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_add_i32 s17, s17, 3
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:  .LBB9_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v2, s18
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v4, s20
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v6, s22
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB9_4:
; SI-NEXT:    s_branch .LBB9_2
;
; VI-LABEL: bitcast_v8i32_to_v4f64_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB9_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB9_3
; VI-NEXT:  .LBB9_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s23, s23, 3
; VI-NEXT:    s_add_i32 s22, s22, 3
; VI-NEXT:    s_add_i32 s21, s21, 3
; VI-NEXT:    s_add_i32 s20, s20, 3
; VI-NEXT:    s_add_i32 s19, s19, 3
; VI-NEXT:    s_add_i32 s18, s18, 3
; VI-NEXT:    s_add_i32 s17, s17, 3
; VI-NEXT:    s_add_i32 s16, s16, 3
; VI-NEXT:  .LBB9_3: ; %end
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB9_4:
; VI-NEXT:    s_branch .LBB9_2
;
; GFX9-LABEL: bitcast_v8i32_to_v4f64_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB9_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB9_3
; GFX9-NEXT:  .LBB9_2: ; %cmp.true
; GFX9-NEXT:    s_add_i32 s23, s23, 3
; GFX9-NEXT:    s_add_i32 s22, s22, 3
; GFX9-NEXT:    s_add_i32 s21, s21, 3
; GFX9-NEXT:    s_add_i32 s20, s20, 3
; GFX9-NEXT:    s_add_i32 s19, s19, 3
; GFX9-NEXT:    s_add_i32 s18, s18, 3
; GFX9-NEXT:    s_add_i32 s17, s17, 3
; GFX9-NEXT:    s_add_i32 s16, s16, 3
; GFX9-NEXT:  .LBB9_3: ; %end
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB9_4:
; GFX9-NEXT:    s_branch .LBB9_2
;
; GFX11-LABEL: bitcast_v8i32_to_v4f64_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s4, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB9_4
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s4
; GFX11-NEXT:    s_cbranch_vccnz .LBB9_3
; GFX11-NEXT:  .LBB9_2: ; %cmp.true
; GFX11-NEXT:    s_add_i32 s19, s19, 3
; GFX11-NEXT:    s_add_i32 s18, s18, 3
; GFX11-NEXT:    s_add_i32 s17, s17, 3
; GFX11-NEXT:    s_add_i32 s16, s16, 3
; GFX11-NEXT:    s_add_i32 s3, s3, 3
; GFX11-NEXT:    s_add_i32 s2, s2, 3
; GFX11-NEXT:    s_add_i32 s1, s1, 3
; GFX11-NEXT:    s_add_i32 s0, s0, 3
; GFX11-NEXT:  .LBB9_3: ; %end
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s16 :: v_dual_mov_b32 v5, s17
; GFX11-NEXT:    v_dual_mov_b32 v6, s18 :: v_dual_mov_b32 v7, s19
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB9_4:
; GFX11-NEXT:    s_branch .LBB9_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <8 x i32> %a, splat (i32 3)
  %a2 = bitcast <8 x i32> %a1 to <4 x double>
  br label %end

cmp.false:
  %a3 = bitcast <8 x i32> %a to <4 x double>
  br label %end

end:
  %phi = phi <4 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x double> %phi
}

define <8 x i32> @bitcast_v4f64_to_v8i32(<4 x double> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v4f64_to_v8i32:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:  ; %bb.1: ; %cmp.true
; SI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; SI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; SI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; SI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; SI-NEXT:  ; %bb.2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v4f64_to_v8i32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB10_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; VI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; VI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; VI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; VI-NEXT:  .LBB10_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v4f64_to_v8i32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB10_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX9-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX9-NEXT:  .LBB10_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v4f64_to_v8i32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB10_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX11-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX11-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX11-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX11-NEXT:  .LBB10_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <4 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <4 x double> %a1 to <8 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <4 x double> %a to <8 x i32>
  br label %end

end:
  %phi = phi <8 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x i32> %phi
}

define inreg <8 x i32> @bitcast_v4f64_to_v8i32_scalar(<4 x double> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v4f64_to_v8i32_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB11_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_cbranch_execnz .LBB11_4
; SI-NEXT:  .LBB11_2: ; %cmp.true
; SI-NEXT:    v_add_f64 v[6:7], s[22:23], 1.0
; SI-NEXT:    v_add_f64 v[4:5], s[20:21], 1.0
; SI-NEXT:    v_add_f64 v[2:3], s[18:19], 1.0
; SI-NEXT:    v_add_f64 v[0:1], s[16:17], 1.0
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB11_3:
; SI-NEXT:    s_branch .LBB11_2
; SI-NEXT:  .LBB11_4:
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v2, s18
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v4, s20
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v6, s22
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v4f64_to_v8i32_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB11_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB11_4
; VI-NEXT:  .LBB11_2: ; %cmp.true
; VI-NEXT:    v_add_f64 v[6:7], s[22:23], 1.0
; VI-NEXT:    v_add_f64 v[4:5], s[20:21], 1.0
; VI-NEXT:    v_add_f64 v[2:3], s[18:19], 1.0
; VI-NEXT:    v_add_f64 v[0:1], s[16:17], 1.0
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB11_3:
; VI-NEXT:    s_branch .LBB11_2
; VI-NEXT:  .LBB11_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v4f64_to_v8i32_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB11_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB11_4
; GFX9-NEXT:  .LBB11_2: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[6:7], s[22:23], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], s[20:21], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], s[18:19], 1.0
; GFX9-NEXT:    v_add_f64 v[0:1], s[16:17], 1.0
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB11_3:
; GFX9-NEXT:    s_branch .LBB11_2
; GFX9-NEXT:  .LBB11_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v4f64_to_v8i32_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s7, s19
; GFX11-NEXT:    s_mov_b32 s6, s18
; GFX11-NEXT:    s_mov_b32 s5, s17
; GFX11-NEXT:    s_mov_b32 s4, s16
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s8, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB11_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-NEXT:    s_cbranch_vccnz .LBB11_4
; GFX11-NEXT:  .LBB11_2: ; %cmp.true
; GFX11-NEXT:    v_add_f64 v[6:7], s[6:7], 1.0
; GFX11-NEXT:    v_add_f64 v[4:5], s[4:5], 1.0
; GFX11-NEXT:    v_add_f64 v[2:3], s[2:3], 1.0
; GFX11-NEXT:    v_add_f64 v[0:1], s[0:1], 1.0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB11_3:
; GFX11-NEXT:    s_branch .LBB11_2
; GFX11-NEXT:  .LBB11_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <4 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <4 x double> %a1 to <8 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <4 x double> %a to <8 x i32>
  br label %end

end:
  %phi = phi <8 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x i32> %phi
}

define <16 x i16> @bitcast_v8i32_to_v16i16(<8 x i32> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v8i32_to_v16i16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_alignbit_b32 v8, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v9, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v10, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v13, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v1
; SI-NEXT:  ; %bb.2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB12_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v1
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v3
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v5
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v7
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; SI-NEXT:    v_alignbit_b32 v8, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v9, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v10, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v13, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v1
; SI-NEXT:  .LBB12_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v13
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v10
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_or_b32_e32 v0, v0, v13
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v15
; SI-NEXT:    v_or_b32_e32 v2, v2, v10
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v14
; SI-NEXT:    v_or_b32_e32 v4, v4, v9
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v12
; SI-NEXT:    v_or_b32_e32 v6, v6, v8
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v11
; SI-NEXT:    v_or_b32_e32 v1, v1, v13
; SI-NEXT:    v_or_b32_e32 v3, v3, v10
; SI-NEXT:    v_or_b32_e32 v5, v5, v9
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v8i32_to_v16i16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v7, vcc, 3, v7
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_add_u32_e32 v5, vcc, 3, v5
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_add_u32_e32 v3, vcc, 3, v3
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_add_u32_e32 v1, vcc, 3, v1
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:  ; %bb.2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v8i32_to_v16i16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_u32_e32 v7, 3, v7
; GFX9-NEXT:    v_add_u32_e32 v6, 3, v6
; GFX9-NEXT:    v_add_u32_e32 v5, 3, v5
; GFX9-NEXT:    v_add_u32_e32 v4, 3, v4
; GFX9-NEXT:    v_add_u32_e32 v3, 3, v3
; GFX9-NEXT:    v_add_u32_e32 v2, 3, v2
; GFX9-NEXT:    v_add_u32_e32 v1, 3, v1
; GFX9-NEXT:    v_add_u32_e32 v0, 3, v0
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v8i32_to_v16i16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB12_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_nc_u32_e32 v7, 3, v7
; GFX11-NEXT:    v_add_nc_u32_e32 v6, 3, v6
; GFX11-NEXT:    v_add_nc_u32_e32 v5, 3, v5
; GFX11-NEXT:    v_add_nc_u32_e32 v4, 3, v4
; GFX11-NEXT:    v_add_nc_u32_e32 v3, 3, v3
; GFX11-NEXT:    v_add_nc_u32_e32 v2, 3, v2
; GFX11-NEXT:    v_add_nc_u32_e32 v1, 3, v1
; GFX11-NEXT:    v_add_nc_u32_e32 v0, 3, v0
; GFX11-NEXT:  .LBB12_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <8 x i32> %a, splat (i32 3)
  %a2 = bitcast <8 x i32> %a1 to <16 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <8 x i32> %a to <16 x i16>
  br label %end

end:
  %phi = phi <16 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x i16> %phi
}

define inreg <16 x i16> @bitcast_v8i32_to_v16i16_scalar(<8 x i32> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v8i32_to_v16i16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB13_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_lshr_b32 s14, s23, 16
; SI-NEXT:    s_lshr_b32 s15, s21, 16
; SI-NEXT:    s_lshr_b32 s24, s19, 16
; SI-NEXT:    s_lshr_b32 s25, s17, 16
; SI-NEXT:    s_lshr_b64 s[4:5], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[6:7], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[8:9], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[10:11], s[16:17], 16
; SI-NEXT:    s_cbranch_execnz .LBB13_3
; SI-NEXT:  .LBB13_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s17, s17, 3
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    s_add_i32 s19, s19, 3
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_add_i32 s21, s21, 3
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_add_i32 s23, s23, 3
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_lshr_b64 s[4:5], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[6:7], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[8:9], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[10:11], s[16:17], 16
; SI-NEXT:    s_lshr_b32 s14, s23, 16
; SI-NEXT:    s_lshr_b32 s15, s21, 16
; SI-NEXT:    s_lshr_b32 s24, s19, 16
; SI-NEXT:    s_lshr_b32 s25, s17, 16
; SI-NEXT:  .LBB13_3: ; %end
; SI-NEXT:    s_and_b32 s5, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s10, 16
; SI-NEXT:    s_or_b32 s5, s5, s7
; SI-NEXT:    s_and_b32 s7, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s9, s25, 16
; SI-NEXT:    s_or_b32 s7, s7, s9
; SI-NEXT:    s_and_b32 s9, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s8, s8, 16
; SI-NEXT:    s_or_b32 s8, s9, s8
; SI-NEXT:    s_and_b32 s9, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s24, 16
; SI-NEXT:    s_or_b32 s9, s9, s10
; SI-NEXT:    s_and_b32 s10, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s6, s6, 16
; SI-NEXT:    s_or_b32 s6, s10, s6
; SI-NEXT:    s_and_b32 s10, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s11, s15, 16
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_and_b32 s11, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s4, s4, 16
; SI-NEXT:    s_or_b32 s4, s11, s4
; SI-NEXT:    s_and_b32 s11, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s14, 16
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    v_mov_b32_e32 v0, s5
; SI-NEXT:    v_mov_b32_e32 v1, s7
; SI-NEXT:    v_mov_b32_e32 v2, s8
; SI-NEXT:    v_mov_b32_e32 v3, s9
; SI-NEXT:    v_mov_b32_e32 v4, s6
; SI-NEXT:    v_mov_b32_e32 v5, s10
; SI-NEXT:    v_mov_b32_e32 v6, s4
; SI-NEXT:    v_mov_b32_e32 v7, s11
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB13_4:
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr25
; SI-NEXT:    ; implicit-def: $sgpr8
; SI-NEXT:    ; implicit-def: $sgpr24
; SI-NEXT:    ; implicit-def: $sgpr6
; SI-NEXT:    ; implicit-def: $sgpr15
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    s_branch .LBB13_2
;
; VI-LABEL: bitcast_v8i32_to_v16i16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB13_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB13_3
; VI-NEXT:  .LBB13_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s23, s23, 3
; VI-NEXT:    s_add_i32 s22, s22, 3
; VI-NEXT:    s_add_i32 s21, s21, 3
; VI-NEXT:    s_add_i32 s20, s20, 3
; VI-NEXT:    s_add_i32 s19, s19, 3
; VI-NEXT:    s_add_i32 s18, s18, 3
; VI-NEXT:    s_add_i32 s17, s17, 3
; VI-NEXT:    s_add_i32 s16, s16, 3
; VI-NEXT:  .LBB13_3: ; %end
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB13_4:
; VI-NEXT:    s_branch .LBB13_2
;
; GFX9-LABEL: bitcast_v8i32_to_v16i16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB13_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB13_3
; GFX9-NEXT:  .LBB13_2: ; %cmp.true
; GFX9-NEXT:    s_add_i32 s23, s23, 3
; GFX9-NEXT:    s_add_i32 s22, s22, 3
; GFX9-NEXT:    s_add_i32 s21, s21, 3
; GFX9-NEXT:    s_add_i32 s20, s20, 3
; GFX9-NEXT:    s_add_i32 s19, s19, 3
; GFX9-NEXT:    s_add_i32 s18, s18, 3
; GFX9-NEXT:    s_add_i32 s17, s17, 3
; GFX9-NEXT:    s_add_i32 s16, s16, 3
; GFX9-NEXT:  .LBB13_3: ; %end
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB13_4:
; GFX9-NEXT:    s_branch .LBB13_2
;
; GFX11-LABEL: bitcast_v8i32_to_v16i16_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s4, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB13_4
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s4
; GFX11-NEXT:    s_cbranch_vccnz .LBB13_3
; GFX11-NEXT:  .LBB13_2: ; %cmp.true
; GFX11-NEXT:    s_add_i32 s19, s19, 3
; GFX11-NEXT:    s_add_i32 s18, s18, 3
; GFX11-NEXT:    s_add_i32 s17, s17, 3
; GFX11-NEXT:    s_add_i32 s16, s16, 3
; GFX11-NEXT:    s_add_i32 s3, s3, 3
; GFX11-NEXT:    s_add_i32 s2, s2, 3
; GFX11-NEXT:    s_add_i32 s1, s1, 3
; GFX11-NEXT:    s_add_i32 s0, s0, 3
; GFX11-NEXT:  .LBB13_3: ; %end
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s16 :: v_dual_mov_b32 v5, s17
; GFX11-NEXT:    v_dual_mov_b32 v6, s18 :: v_dual_mov_b32 v7, s19
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB13_4:
; GFX11-NEXT:    s_branch .LBB13_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <8 x i32> %a, splat (i32 3)
  %a2 = bitcast <8 x i32> %a1 to <16 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <8 x i32> %a to <16 x i16>
  br label %end

end:
  %phi = phi <16 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x i16> %phi
}

define <8 x i32> @bitcast_v16i16_to_v8i32(<16 x i16> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v16i16_to_v8i32:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_mov_b32_e32 v16, v7
; SI-NEXT:    v_mov_b32_e32 v9, v6
; SI-NEXT:    v_mov_b32_e32 v10, v5
; SI-NEXT:    v_mov_b32_e32 v11, v4
; SI-NEXT:    v_mov_b32_e32 v12, v3
; SI-NEXT:    v_mov_b32_e32 v13, v2
; SI-NEXT:    v_mov_b32_e32 v14, v1
; SI-NEXT:    v_mov_b32_e32 v15, v0
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v16
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v10
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v12
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v14
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v15
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v7
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v6
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v5
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v4
; SI-NEXT:    v_lshlrev_b32_e32 v19, 16, v3
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v2
; SI-NEXT:    v_lshlrev_b32_e32 v17, 16, v1
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v0
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB14_3
; SI-NEXT:  ; %bb.1: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB14_4
; SI-NEXT:  .LBB14_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB14_3: ; %cmp.false
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v15
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v14
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v13
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v12
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v11
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v10
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v9
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v16
; SI-NEXT:    v_or_b32_e32 v0, v0, v23
; SI-NEXT:    v_or_b32_e32 v1, v1, v22
; SI-NEXT:    v_or_b32_e32 v2, v2, v21
; SI-NEXT:    v_or_b32_e32 v3, v3, v20
; SI-NEXT:    v_or_b32_e32 v4, v4, v19
; SI-NEXT:    v_or_b32_e32 v5, v5, v18
; SI-NEXT:    v_or_b32_e32 v6, v6, v17
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB14_2
; SI-NEXT:  .LBB14_4: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v15
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v14
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v13
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v12
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v11
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v10
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v9
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v16
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_or_b32_e32 v0, v23, v0
; SI-NEXT:    s_mov_b32 s6, 0x30000
; SI-NEXT:    v_or_b32_e32 v1, v22, v1
; SI-NEXT:    v_or_b32_e32 v2, v21, v2
; SI-NEXT:    v_or_b32_e32 v3, v20, v3
; SI-NEXT:    v_or_b32_e32 v4, v19, v4
; SI-NEXT:    v_or_b32_e32 v5, v18, v5
; SI-NEXT:    v_or_b32_e32 v6, v17, v6
; SI-NEXT:    v_or_b32_e32 v7, v8, v7
; SI-NEXT:    v_add_i32_e32 v0, vcc, 0x30000, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, s6, v1
; SI-NEXT:    v_add_i32_e32 v2, vcc, s6, v2
; SI-NEXT:    v_add_i32_e32 v3, vcc, s6, v3
; SI-NEXT:    v_add_i32_e32 v4, vcc, s6, v4
; SI-NEXT:    v_add_i32_e32 v5, vcc, 0x30000, v5
; SI-NEXT:    v_add_i32_e32 v6, vcc, 0x30000, v6
; SI-NEXT:    v_add_i32_e32 v7, vcc, 0x30000, v7
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16i16_to_v8i32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB14_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v9, 3
; VI-NEXT:    v_add_u16_e32 v8, 3, v7
; VI-NEXT:    v_add_u16_sdwa v7, v7, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v7, v8, v7
; VI-NEXT:    v_add_u16_e32 v8, 3, v6
; VI-NEXT:    v_add_u16_sdwa v6, v6, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v6, v8, v6
; VI-NEXT:    v_add_u16_e32 v8, 3, v5
; VI-NEXT:    v_add_u16_sdwa v5, v5, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v5, v8, v5
; VI-NEXT:    v_add_u16_e32 v8, 3, v4
; VI-NEXT:    v_add_u16_sdwa v4, v4, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v4, v8, v4
; VI-NEXT:    v_add_u16_e32 v8, 3, v3
; VI-NEXT:    v_add_u16_sdwa v3, v3, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v3, v8, v3
; VI-NEXT:    v_add_u16_e32 v8, 3, v2
; VI-NEXT:    v_add_u16_sdwa v2, v2, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v2, v8, v2
; VI-NEXT:    v_add_u16_e32 v8, 3, v1
; VI-NEXT:    v_add_u16_sdwa v1, v1, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v1, v8, v1
; VI-NEXT:    v_add_u16_e32 v8, 3, v0
; VI-NEXT:    v_add_u16_sdwa v0, v0, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v0, v8, v0
; VI-NEXT:  .LBB14_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16i16_to_v8i32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v16i16_to_v8i32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB14_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX11-NEXT:  .LBB14_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <16 x i16> %a, splat (i16 3)
  %a2 = bitcast <16 x i16> %a1 to <8 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <16 x i16> %a to <8 x i32>
  br label %end

end:
  %phi = phi <8 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x i32> %phi
}

define inreg <8 x i32> @bitcast_v16i16_to_v8i32_scalar(<16 x i16> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v16i16_to_v8i32_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_lshr_b32 s14, s23, 16
; SI-NEXT:    s_lshr_b32 s15, s22, 16
; SI-NEXT:    s_lshr_b32 s25, s21, 16
; SI-NEXT:    s_lshr_b32 s26, s20, 16
; SI-NEXT:    s_lshr_b32 s27, s19, 16
; SI-NEXT:    s_lshr_b32 s28, s18, 16
; SI-NEXT:    s_lshr_b32 s29, s17, 16
; SI-NEXT:    s_lshr_b32 s40, s16, 16
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB15_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s40, 16
; SI-NEXT:    s_or_b32 s4, s4, s5
; SI-NEXT:    s_and_b32 s5, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s6, s29, 16
; SI-NEXT:    s_or_b32 s5, s5, s6
; SI-NEXT:    s_and_b32 s6, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s28, 16
; SI-NEXT:    s_or_b32 s6, s6, s7
; SI-NEXT:    s_and_b32 s7, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s8, s27, 16
; SI-NEXT:    s_or_b32 s7, s7, s8
; SI-NEXT:    s_and_b32 s8, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s9, s26, 16
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_and_b32 s9, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s25, 16
; SI-NEXT:    s_or_b32 s9, s9, s10
; SI-NEXT:    s_and_b32 s10, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s11, s15, 16
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_and_b32 s11, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s14, 16
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    s_cbranch_execnz .LBB15_3
; SI-NEXT:  .LBB15_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s40, 16
; SI-NEXT:    s_add_i32 s17, s17, 3
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_and_b32 s5, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s6, s29, 16
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_or_b32 s5, s6, s5
; SI-NEXT:    s_and_b32 s6, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s28, 16
; SI-NEXT:    s_add_i32 s19, s19, 3
; SI-NEXT:    s_or_b32 s6, s7, s6
; SI-NEXT:    s_and_b32 s7, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s8, s27, 16
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_or_b32 s7, s8, s7
; SI-NEXT:    s_and_b32 s8, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s9, s26, 16
; SI-NEXT:    s_add_i32 s21, s21, 3
; SI-NEXT:    s_or_b32 s8, s9, s8
; SI-NEXT:    s_and_b32 s9, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s25, 16
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_or_b32 s9, s10, s9
; SI-NEXT:    s_and_b32 s10, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s11, s15, 16
; SI-NEXT:    s_add_i32 s23, s23, 3
; SI-NEXT:    s_or_b32 s10, s11, s10
; SI-NEXT:    s_and_b32 s11, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s14, 16
; SI-NEXT:    s_or_b32 s11, s12, s11
; SI-NEXT:    s_add_i32 s4, s4, 0x30000
; SI-NEXT:    s_add_i32 s5, s5, 0x30000
; SI-NEXT:    s_add_i32 s6, s6, 0x30000
; SI-NEXT:    s_add_i32 s7, s7, 0x30000
; SI-NEXT:    s_add_i32 s8, s8, 0x30000
; SI-NEXT:    s_add_i32 s9, s9, 0x30000
; SI-NEXT:    s_add_i32 s10, s10, 0x30000
; SI-NEXT:    s_add_i32 s11, s11, 0x30000
; SI-NEXT:  .LBB15_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v0, s4
; SI-NEXT:    v_mov_b32_e32 v1, s5
; SI-NEXT:    v_mov_b32_e32 v2, s6
; SI-NEXT:    v_mov_b32_e32 v3, s7
; SI-NEXT:    v_mov_b32_e32 v4, s8
; SI-NEXT:    v_mov_b32_e32 v5, s9
; SI-NEXT:    v_mov_b32_e32 v6, s10
; SI-NEXT:    v_mov_b32_e32 v7, s11
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB15_4:
; SI-NEXT:    ; implicit-def: $sgpr4_sgpr5_sgpr6_sgpr7_sgpr8_sgpr9_sgpr10_sgpr11
; SI-NEXT:    s_branch .LBB15_2
;
; VI-LABEL: bitcast_v16i16_to_v8i32_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB15_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB15_3
; VI-NEXT:  .LBB15_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s5, s23, 3
; VI-NEXT:    s_and_b32 s4, s23, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s22, 3
; VI-NEXT:    s_add_i32 s23, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s22, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s21, 3
; VI-NEXT:    s_add_i32 s22, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s21, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s20, 3
; VI-NEXT:    s_add_i32 s21, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s20, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s19, 3
; VI-NEXT:    s_add_i32 s20, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s19, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s18, 3
; VI-NEXT:    s_add_i32 s19, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s18, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s17, 3
; VI-NEXT:    s_add_i32 s18, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s17, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s16, 3
; VI-NEXT:    s_add_i32 s17, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s16, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s16, s4, 0x30000
; VI-NEXT:  .LBB15_3: ; %end
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB15_4:
; VI-NEXT:    s_branch .LBB15_2
;
; GFX9-LABEL: bitcast_v16i16_to_v8i32_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB15_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB15_4
; GFX9-NEXT:  .LBB15_2: ; %cmp.true
; GFX9-NEXT:    v_pk_add_u16 v7, s23, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, s22, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v5, s21, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v4, s20, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v3, s19, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v2, s18, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v1, s17, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v0, s16, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB15_3:
; GFX9-NEXT:    s_branch .LBB15_2
; GFX9-NEXT:  .LBB15_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v16i16_to_v8i32_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s7, s19
; GFX11-NEXT:    s_mov_b32 s6, s18
; GFX11-NEXT:    s_mov_b32 s5, s17
; GFX11-NEXT:    s_mov_b32 s4, s16
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s8, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB15_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-NEXT:    s_cbranch_vccnz .LBB15_4
; GFX11-NEXT:  .LBB15_2: ; %cmp.true
; GFX11-NEXT:    v_pk_add_u16 v7, s7, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v6, s6, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v5, s5, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v4, s4, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v3, s3, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v2, s2, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v1, s1, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v0, s0, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB15_3:
; GFX11-NEXT:    s_branch .LBB15_2
; GFX11-NEXT:  .LBB15_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <16 x i16> %a, splat (i16 3)
  %a2 = bitcast <16 x i16> %a1 to <8 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <16 x i16> %a to <8 x i32>
  br label %end

end:
  %phi = phi <8 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x i32> %phi
}

define <16 x half> @bitcast_v8i32_to_v16f16(<8 x i32> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v8i32_to_v16f16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_alignbit_b32 v8, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v9, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v10, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v13, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v1
; SI-NEXT:  ; %bb.2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB16_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v1
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v3
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v5
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v7
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; SI-NEXT:    v_alignbit_b32 v8, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v9, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v10, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v13, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v1
; SI-NEXT:  .LBB16_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v13
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v10
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_or_b32_e32 v0, v0, v13
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v15
; SI-NEXT:    v_or_b32_e32 v2, v2, v10
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v14
; SI-NEXT:    v_or_b32_e32 v4, v4, v9
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v12
; SI-NEXT:    v_or_b32_e32 v6, v6, v8
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v11
; SI-NEXT:    v_or_b32_e32 v1, v1, v13
; SI-NEXT:    v_or_b32_e32 v3, v3, v10
; SI-NEXT:    v_or_b32_e32 v5, v5, v9
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v8i32_to_v16f16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v7, vcc, 3, v7
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_add_u32_e32 v5, vcc, 3, v5
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_add_u32_e32 v3, vcc, 3, v3
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_add_u32_e32 v1, vcc, 3, v1
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:  ; %bb.2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v8i32_to_v16f16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_u32_e32 v7, 3, v7
; GFX9-NEXT:    v_add_u32_e32 v6, 3, v6
; GFX9-NEXT:    v_add_u32_e32 v5, 3, v5
; GFX9-NEXT:    v_add_u32_e32 v4, 3, v4
; GFX9-NEXT:    v_add_u32_e32 v3, 3, v3
; GFX9-NEXT:    v_add_u32_e32 v2, 3, v2
; GFX9-NEXT:    v_add_u32_e32 v1, 3, v1
; GFX9-NEXT:    v_add_u32_e32 v0, 3, v0
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v8i32_to_v16f16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB16_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_nc_u32_e32 v7, 3, v7
; GFX11-NEXT:    v_add_nc_u32_e32 v6, 3, v6
; GFX11-NEXT:    v_add_nc_u32_e32 v5, 3, v5
; GFX11-NEXT:    v_add_nc_u32_e32 v4, 3, v4
; GFX11-NEXT:    v_add_nc_u32_e32 v3, 3, v3
; GFX11-NEXT:    v_add_nc_u32_e32 v2, 3, v2
; GFX11-NEXT:    v_add_nc_u32_e32 v1, 3, v1
; GFX11-NEXT:    v_add_nc_u32_e32 v0, 3, v0
; GFX11-NEXT:  .LBB16_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <8 x i32> %a, splat (i32 3)
  %a2 = bitcast <8 x i32> %a1 to <16 x half>
  br label %end

cmp.false:
  %a3 = bitcast <8 x i32> %a to <16 x half>
  br label %end

end:
  %phi = phi <16 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x half> %phi
}

define inreg <16 x half> @bitcast_v8i32_to_v16f16_scalar(<8 x i32> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v8i32_to_v16f16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB17_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_lshr_b32 s14, s23, 16
; SI-NEXT:    s_lshr_b32 s15, s21, 16
; SI-NEXT:    s_lshr_b32 s24, s19, 16
; SI-NEXT:    s_lshr_b32 s25, s17, 16
; SI-NEXT:    s_lshr_b64 s[4:5], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[6:7], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[8:9], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[10:11], s[16:17], 16
; SI-NEXT:    s_cbranch_execnz .LBB17_3
; SI-NEXT:  .LBB17_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s17, s17, 3
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    s_add_i32 s19, s19, 3
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_add_i32 s21, s21, 3
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_add_i32 s23, s23, 3
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_lshr_b64 s[4:5], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[6:7], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[8:9], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[10:11], s[16:17], 16
; SI-NEXT:    s_lshr_b32 s14, s23, 16
; SI-NEXT:    s_lshr_b32 s15, s21, 16
; SI-NEXT:    s_lshr_b32 s24, s19, 16
; SI-NEXT:    s_lshr_b32 s25, s17, 16
; SI-NEXT:  .LBB17_3: ; %end
; SI-NEXT:    s_and_b32 s5, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s10, 16
; SI-NEXT:    s_or_b32 s5, s5, s7
; SI-NEXT:    s_and_b32 s7, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s9, s25, 16
; SI-NEXT:    s_or_b32 s7, s7, s9
; SI-NEXT:    s_and_b32 s9, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s8, s8, 16
; SI-NEXT:    s_or_b32 s8, s9, s8
; SI-NEXT:    s_and_b32 s9, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s24, 16
; SI-NEXT:    s_or_b32 s9, s9, s10
; SI-NEXT:    s_and_b32 s10, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s6, s6, 16
; SI-NEXT:    s_or_b32 s6, s10, s6
; SI-NEXT:    s_and_b32 s10, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s11, s15, 16
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_and_b32 s11, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s4, s4, 16
; SI-NEXT:    s_or_b32 s4, s11, s4
; SI-NEXT:    s_and_b32 s11, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s14, 16
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    v_mov_b32_e32 v0, s5
; SI-NEXT:    v_mov_b32_e32 v1, s7
; SI-NEXT:    v_mov_b32_e32 v2, s8
; SI-NEXT:    v_mov_b32_e32 v3, s9
; SI-NEXT:    v_mov_b32_e32 v4, s6
; SI-NEXT:    v_mov_b32_e32 v5, s10
; SI-NEXT:    v_mov_b32_e32 v6, s4
; SI-NEXT:    v_mov_b32_e32 v7, s11
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB17_4:
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr25
; SI-NEXT:    ; implicit-def: $sgpr8
; SI-NEXT:    ; implicit-def: $sgpr24
; SI-NEXT:    ; implicit-def: $sgpr6
; SI-NEXT:    ; implicit-def: $sgpr15
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    s_branch .LBB17_2
;
; VI-LABEL: bitcast_v8i32_to_v16f16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB17_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB17_3
; VI-NEXT:  .LBB17_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s23, s23, 3
; VI-NEXT:    s_add_i32 s22, s22, 3
; VI-NEXT:    s_add_i32 s21, s21, 3
; VI-NEXT:    s_add_i32 s20, s20, 3
; VI-NEXT:    s_add_i32 s19, s19, 3
; VI-NEXT:    s_add_i32 s18, s18, 3
; VI-NEXT:    s_add_i32 s17, s17, 3
; VI-NEXT:    s_add_i32 s16, s16, 3
; VI-NEXT:  .LBB17_3: ; %end
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB17_4:
; VI-NEXT:    s_branch .LBB17_2
;
; GFX9-LABEL: bitcast_v8i32_to_v16f16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB17_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB17_3
; GFX9-NEXT:  .LBB17_2: ; %cmp.true
; GFX9-NEXT:    s_add_i32 s23, s23, 3
; GFX9-NEXT:    s_add_i32 s22, s22, 3
; GFX9-NEXT:    s_add_i32 s21, s21, 3
; GFX9-NEXT:    s_add_i32 s20, s20, 3
; GFX9-NEXT:    s_add_i32 s19, s19, 3
; GFX9-NEXT:    s_add_i32 s18, s18, 3
; GFX9-NEXT:    s_add_i32 s17, s17, 3
; GFX9-NEXT:    s_add_i32 s16, s16, 3
; GFX9-NEXT:  .LBB17_3: ; %end
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB17_4:
; GFX9-NEXT:    s_branch .LBB17_2
;
; GFX11-LABEL: bitcast_v8i32_to_v16f16_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s4, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB17_4
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s4
; GFX11-NEXT:    s_cbranch_vccnz .LBB17_3
; GFX11-NEXT:  .LBB17_2: ; %cmp.true
; GFX11-NEXT:    s_add_i32 s19, s19, 3
; GFX11-NEXT:    s_add_i32 s18, s18, 3
; GFX11-NEXT:    s_add_i32 s17, s17, 3
; GFX11-NEXT:    s_add_i32 s16, s16, 3
; GFX11-NEXT:    s_add_i32 s3, s3, 3
; GFX11-NEXT:    s_add_i32 s2, s2, 3
; GFX11-NEXT:    s_add_i32 s1, s1, 3
; GFX11-NEXT:    s_add_i32 s0, s0, 3
; GFX11-NEXT:  .LBB17_3: ; %end
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s16 :: v_dual_mov_b32 v5, s17
; GFX11-NEXT:    v_dual_mov_b32 v6, s18 :: v_dual_mov_b32 v7, s19
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB17_4:
; GFX11-NEXT:    s_branch .LBB17_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <8 x i32> %a, splat (i32 3)
  %a2 = bitcast <8 x i32> %a1 to <16 x half>
  br label %end

cmp.false:
  %a3 = bitcast <8 x i32> %a to <16 x half>
  br label %end

end:
  %phi = phi <16 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x half> %phi
}

define <8 x i32> @bitcast_v16f16_to_v8i32(<16 x half> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v16f16_to_v8i32:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_mov_b32_e32 v16, v7
; SI-NEXT:    v_mov_b32_e32 v9, v6
; SI-NEXT:    v_mov_b32_e32 v10, v5
; SI-NEXT:    v_mov_b32_e32 v11, v4
; SI-NEXT:    v_mov_b32_e32 v12, v3
; SI-NEXT:    v_mov_b32_e32 v13, v2
; SI-NEXT:    v_mov_b32_e32 v14, v1
; SI-NEXT:    v_mov_b32_e32 v15, v0
; SI-NEXT:    v_lshrrev_b32_e32 v17, 16, v16
; SI-NEXT:    v_lshrrev_b32_e32 v18, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v19, 16, v10
; SI-NEXT:    v_lshrrev_b32_e32 v20, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v21, 16, v12
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v23, 16, v14
; SI-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB18_3
; SI-NEXT:  ; %bb.1: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB18_4
; SI-NEXT:  .LBB18_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB18_3: ; %cmp.false
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v15
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v24
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v14
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v23
; SI-NEXT:    v_or_b32_e32 v0, v0, v1
; SI-NEXT:    v_or_b32_e32 v1, v2, v3
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v13
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v22
; SI-NEXT:    v_or_b32_e32 v2, v2, v3
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v12
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v21
; SI-NEXT:    v_or_b32_e32 v3, v3, v4
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v11
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v20
; SI-NEXT:    v_or_b32_e32 v4, v4, v5
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v10
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v19
; SI-NEXT:    v_or_b32_e32 v5, v5, v6
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v9
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v18
; SI-NEXT:    v_or_b32_e32 v6, v6, v7
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v16
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v17
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr24
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB18_2
; SI-NEXT:  .LBB18_4: ; %cmp.true
; SI-NEXT:    v_cvt_f32_f16_e32 v0, v24
; SI-NEXT:    v_cvt_f32_f16_e32 v2, v23
; SI-NEXT:    v_cvt_f32_f16_e32 v1, v15
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v14
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_or_b32_e32 v0, v1, v0
; SI-NEXT:    v_or_b32_e32 v1, v3, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v2, v22
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v13
; SI-NEXT:    v_cvt_f32_f16_e32 v4, v21
; SI-NEXT:    v_cvt_f32_f16_e32 v5, v20
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_or_b32_e32 v2, v3, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v12
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v6, v11
; SI-NEXT:    v_cvt_f32_f16_e32 v7, v10
; SI-NEXT:    v_cvt_f32_f16_e32 v8, v17
; SI-NEXT:    v_or_b32_e32 v3, v3, v4
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v5, v19
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_or_b32_e32 v4, v6, v4
; SI-NEXT:    v_cvt_f32_f16_e32 v6, v18
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_or_b32_e32 v5, v7, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v7, v9
; SI-NEXT:    v_cvt_f32_f16_e32 v9, v16
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v8, v8
; SI-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v9
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_or_b32_e32 v6, v7, v6
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v8
; SI-NEXT:    v_or_b32_e32 v7, v9, v7
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16f16_to_v8i32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB18_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v8, 0x200
; VI-NEXT:    v_add_f16_sdwa v9, v7, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v7, 0x200, v7
; VI-NEXT:    v_or_b32_e32 v7, v7, v9
; VI-NEXT:    v_add_f16_sdwa v9, v6, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v6, 0x200, v6
; VI-NEXT:    v_or_b32_e32 v6, v6, v9
; VI-NEXT:    v_add_f16_sdwa v9, v5, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v5, 0x200, v5
; VI-NEXT:    v_or_b32_e32 v5, v5, v9
; VI-NEXT:    v_add_f16_sdwa v9, v4, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v4, 0x200, v4
; VI-NEXT:    v_or_b32_e32 v4, v4, v9
; VI-NEXT:    v_add_f16_sdwa v9, v3, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v3, 0x200, v3
; VI-NEXT:    v_or_b32_e32 v3, v3, v9
; VI-NEXT:    v_add_f16_sdwa v9, v2, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, 0x200, v2
; VI-NEXT:    v_or_b32_e32 v2, v2, v9
; VI-NEXT:    v_add_f16_sdwa v9, v1, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v1, 0x200, v1
; VI-NEXT:    v_add_f16_sdwa v8, v0, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v0, 0x200, v0
; VI-NEXT:    v_or_b32_e32 v1, v1, v9
; VI-NEXT:    v_or_b32_e32 v0, v0, v8
; VI-NEXT:  .LBB18_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16f16_to_v8i32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    s_movk_i32 s6, 0x200
; GFX9-NEXT:    v_pk_add_f16 v7, v7, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, v6, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v5, v5, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v4, v4, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v3, v3, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v2, v2, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v1, v1, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v0, v0, s6 op_sel_hi:[1,0]
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v16f16_to_v8i32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB18_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_pk_add_f16 v7, 0x200, v7 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v6, 0x200, v6 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v5, 0x200, v5 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v4, 0x200, v4 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v3, 0x200, v3 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v2, 0x200, v2 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v1, 0x200, v1 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v0, 0x200, v0 op_sel_hi:[0,1]
; GFX11-NEXT:  .LBB18_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <16 x half> %a1 to <8 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <16 x half> %a to <8 x i32>
  br label %end

end:
  %phi = phi <8 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x i32> %phi
}

define inreg <8 x i32> @bitcast_v16f16_to_v8i32_scalar(<16 x half> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v16f16_to_v8i32_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_lshr_b32 s14, s23, 16
; SI-NEXT:    s_lshr_b32 s15, s22, 16
; SI-NEXT:    s_lshr_b32 s25, s21, 16
; SI-NEXT:    s_lshr_b32 s26, s20, 16
; SI-NEXT:    s_lshr_b32 s27, s19, 16
; SI-NEXT:    s_lshr_b32 s28, s18, 16
; SI-NEXT:    s_lshr_b32 s29, s17, 16
; SI-NEXT:    s_lshr_b32 s40, s16, 16
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB19_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s40, 16
; SI-NEXT:    s_or_b32 s4, s4, s5
; SI-NEXT:    s_and_b32 s5, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s6, s29, 16
; SI-NEXT:    s_or_b32 s5, s5, s6
; SI-NEXT:    s_and_b32 s6, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s28, 16
; SI-NEXT:    s_or_b32 s6, s6, s7
; SI-NEXT:    s_and_b32 s7, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s8, s27, 16
; SI-NEXT:    s_or_b32 s7, s7, s8
; SI-NEXT:    s_and_b32 s8, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s9, s26, 16
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_and_b32 s9, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s25, 16
; SI-NEXT:    s_or_b32 s9, s9, s10
; SI-NEXT:    s_and_b32 s10, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s11, s15, 16
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_and_b32 s11, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s14, 16
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    s_cbranch_execnz .LBB19_4
; SI-NEXT:  .LBB19_2: ; %cmp.true
; SI-NEXT:    v_cvt_f32_f16_e32 v0, s40
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s16
; SI-NEXT:    v_cvt_f32_f16_e32 v2, s29
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s17
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_cvt_f32_f16_e32 v4, s18
; SI-NEXT:    v_or_b32_e32 v0, v1, v0
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v2, s28
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_or_b32_e32 v1, v3, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s27
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_or_b32_e32 v2, v4, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v4, s19
; SI-NEXT:    v_cvt_f32_f16_e32 v5, s26
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v6, s20
; SI-NEXT:    v_or_b32_e32 v3, v4, v3
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v5, s25
; SI-NEXT:    v_cvt_f32_f16_e32 v7, s21
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_or_b32_e32 v4, v6, v4
; SI-NEXT:    v_cvt_f32_f16_e32 v6, s15
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_or_b32_e32 v5, v7, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v7, s22
; SI-NEXT:    v_cvt_f32_f16_e32 v8, s14
; SI-NEXT:    v_cvt_f32_f16_e32 v9, s23
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v8, v8
; SI-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v9
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_or_b32_e32 v6, v7, v6
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v8
; SI-NEXT:    v_or_b32_e32 v7, v9, v7
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB19_3:
; SI-NEXT:    ; implicit-def: $sgpr4_sgpr5_sgpr6_sgpr7_sgpr8_sgpr9_sgpr10_sgpr11
; SI-NEXT:    s_branch .LBB19_2
; SI-NEXT:  .LBB19_4:
; SI-NEXT:    v_mov_b32_e32 v0, s4
; SI-NEXT:    v_mov_b32_e32 v1, s5
; SI-NEXT:    v_mov_b32_e32 v2, s6
; SI-NEXT:    v_mov_b32_e32 v3, s7
; SI-NEXT:    v_mov_b32_e32 v4, s8
; SI-NEXT:    v_mov_b32_e32 v5, s9
; SI-NEXT:    v_mov_b32_e32 v6, s10
; SI-NEXT:    v_mov_b32_e32 v7, s11
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16f16_to_v8i32_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB19_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB19_4
; VI-NEXT:  .LBB19_2: ; %cmp.true
; VI-NEXT:    s_lshr_b32 s4, s23, 16
; VI-NEXT:    v_mov_b32_e32 v0, 0x200
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, s23, v0
; VI-NEXT:    s_lshr_b32 s4, s22, 16
; VI-NEXT:    v_or_b32_e32 v7, v2, v1
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, s22, v0
; VI-NEXT:    s_lshr_b32 s4, s21, 16
; VI-NEXT:    v_or_b32_e32 v6, v2, v1
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, s21, v0
; VI-NEXT:    s_lshr_b32 s4, s20, 16
; VI-NEXT:    v_or_b32_e32 v5, v2, v1
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, s20, v0
; VI-NEXT:    s_lshr_b32 s4, s19, 16
; VI-NEXT:    v_or_b32_e32 v4, v2, v1
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, s19, v0
; VI-NEXT:    s_lshr_b32 s4, s18, 16
; VI-NEXT:    v_or_b32_e32 v3, v2, v1
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, s18, v0
; VI-NEXT:    s_lshr_b32 s4, s17, 16
; VI-NEXT:    v_or_b32_e32 v2, v2, v1
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v8, s17, v0
; VI-NEXT:    s_lshr_b32 s4, s16, 16
; VI-NEXT:    v_or_b32_e32 v1, v8, v1
; VI-NEXT:    v_mov_b32_e32 v8, s4
; VI-NEXT:    v_add_f16_sdwa v8, v8, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v0, s16, v0
; VI-NEXT:    v_or_b32_e32 v0, v0, v8
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB19_3:
; VI-NEXT:    s_branch .LBB19_2
; VI-NEXT:  .LBB19_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16f16_to_v8i32_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB19_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB19_4
; GFX9-NEXT:  .LBB19_2: ; %cmp.true
; GFX9-NEXT:    v_mov_b32_e32 v0, 0x200
; GFX9-NEXT:    v_pk_add_f16 v7, s23, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, s22, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v5, s21, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v4, s20, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v3, s19, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v2, s18, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v1, s17, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v0, s16, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB19_3:
; GFX9-NEXT:    s_branch .LBB19_2
; GFX9-NEXT:  .LBB19_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v16f16_to_v8i32_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s7, s19
; GFX11-NEXT:    s_mov_b32 s6, s18
; GFX11-NEXT:    s_mov_b32 s5, s17
; GFX11-NEXT:    s_mov_b32 s4, s16
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s8, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB19_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-NEXT:    s_cbranch_vccnz .LBB19_4
; GFX11-NEXT:  .LBB19_2: ; %cmp.true
; GFX11-NEXT:    v_pk_add_f16 v7, 0x200, s7 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v6, 0x200, s6 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v5, 0x200, s5 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v4, 0x200, s4 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v3, 0x200, s3 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v2, 0x200, s2 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v1, 0x200, s1 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v0, 0x200, s0 op_sel_hi:[0,1]
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB19_3:
; GFX11-NEXT:    s_branch .LBB19_2
; GFX11-NEXT:  .LBB19_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <16 x half> %a1 to <8 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <16 x half> %a to <8 x i32>
  br label %end

end:
  %phi = phi <8 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x i32> %phi
}

define <16 x bfloat> @bitcast_v8i32_to_v16bf16(<8 x i32> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v8i32_to_v16bf16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB20_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_and_b32_e32 v9, 0xffff0000, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v7
; SI-NEXT:    v_and_b32_e32 v11, 0xffff0000, v6
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v6
; SI-NEXT:    v_and_b32_e32 v13, 0xffff0000, v5
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v5
; SI-NEXT:    v_and_b32_e32 v15, 0xffff0000, v4
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v4
; SI-NEXT:    v_and_b32_e32 v17, 0xffff0000, v3
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v3
; SI-NEXT:    v_and_b32_e32 v19, 0xffff0000, v2
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v2
; SI-NEXT:    v_and_b32_e32 v21, 0xffff0000, v1
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v1
; SI-NEXT:    v_and_b32_e32 v23, 0xffff0000, v0
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v0
; SI-NEXT:    ; implicit-def: $vgpr0
; SI-NEXT:    ; implicit-def: $vgpr1
; SI-NEXT:    ; implicit-def: $vgpr2
; SI-NEXT:    ; implicit-def: $vgpr3
; SI-NEXT:    ; implicit-def: $vgpr4
; SI-NEXT:    ; implicit-def: $vgpr5
; SI-NEXT:    ; implicit-def: $vgpr6
; SI-NEXT:    ; implicit-def: $vgpr7
; SI-NEXT:  .LBB20_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB20_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v1
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v3
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v5
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v7
; SI-NEXT:    v_and_b32_e32 v9, 0xffff0000, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v7
; SI-NEXT:    v_and_b32_e32 v11, 0xffff0000, v6
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v6
; SI-NEXT:    v_and_b32_e32 v13, 0xffff0000, v5
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v5
; SI-NEXT:    v_and_b32_e32 v15, 0xffff0000, v4
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v4
; SI-NEXT:    v_and_b32_e32 v17, 0xffff0000, v3
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v3
; SI-NEXT:    v_and_b32_e32 v19, 0xffff0000, v2
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v2
; SI-NEXT:    v_and_b32_e32 v21, 0xffff0000, v1
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v1
; SI-NEXT:    v_and_b32_e32 v23, 0xffff0000, v0
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v0
; SI-NEXT:  .LBB20_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_mul_f32_e32 v0, 1.0, v23
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_mul_f32_e32 v1, 1.0, v22
; SI-NEXT:    v_alignbit_b32 v0, v0, v1, 16
; SI-NEXT:    v_mul_f32_e32 v1, 1.0, v21
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_mul_f32_e32 v2, 1.0, v20
; SI-NEXT:    v_alignbit_b32 v1, v1, v2, 16
; SI-NEXT:    v_mul_f32_e32 v2, 1.0, v19
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_mul_f32_e32 v3, 1.0, v18
; SI-NEXT:    v_alignbit_b32 v2, v2, v3, 16
; SI-NEXT:    v_mul_f32_e32 v3, 1.0, v17
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_mul_f32_e32 v4, 1.0, v16
; SI-NEXT:    v_alignbit_b32 v3, v3, v4, 16
; SI-NEXT:    v_mul_f32_e32 v4, 1.0, v15
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_mul_f32_e32 v5, 1.0, v14
; SI-NEXT:    v_alignbit_b32 v4, v4, v5, 16
; SI-NEXT:    v_mul_f32_e32 v5, 1.0, v13
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_mul_f32_e32 v6, 1.0, v12
; SI-NEXT:    v_alignbit_b32 v5, v5, v6, 16
; SI-NEXT:    v_mul_f32_e32 v6, 1.0, v11
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_mul_f32_e32 v7, 1.0, v10
; SI-NEXT:    v_alignbit_b32 v6, v6, v7, 16
; SI-NEXT:    v_mul_f32_e32 v7, 1.0, v9
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_mul_f32_e32 v8, 1.0, v8
; SI-NEXT:    v_alignbit_b32 v7, v7, v8, 16
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v8i32_to_v16bf16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v7, vcc, 3, v7
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_add_u32_e32 v5, vcc, 3, v5
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_add_u32_e32 v3, vcc, 3, v3
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_add_u32_e32 v1, vcc, 3, v1
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:  ; %bb.2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v8i32_to_v16bf16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_u32_e32 v7, 3, v7
; GFX9-NEXT:    v_add_u32_e32 v6, 3, v6
; GFX9-NEXT:    v_add_u32_e32 v5, 3, v5
; GFX9-NEXT:    v_add_u32_e32 v4, 3, v4
; GFX9-NEXT:    v_add_u32_e32 v3, 3, v3
; GFX9-NEXT:    v_add_u32_e32 v2, 3, v2
; GFX9-NEXT:    v_add_u32_e32 v1, 3, v1
; GFX9-NEXT:    v_add_u32_e32 v0, 3, v0
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v8i32_to_v16bf16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB20_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_nc_u32_e32 v7, 3, v7
; GFX11-NEXT:    v_add_nc_u32_e32 v6, 3, v6
; GFX11-NEXT:    v_add_nc_u32_e32 v5, 3, v5
; GFX11-NEXT:    v_add_nc_u32_e32 v4, 3, v4
; GFX11-NEXT:    v_add_nc_u32_e32 v3, 3, v3
; GFX11-NEXT:    v_add_nc_u32_e32 v2, 3, v2
; GFX11-NEXT:    v_add_nc_u32_e32 v1, 3, v1
; GFX11-NEXT:    v_add_nc_u32_e32 v0, 3, v0
; GFX11-NEXT:  .LBB20_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <8 x i32> %a, splat (i32 3)
  %a2 = bitcast <8 x i32> %a1 to <16 x bfloat>
  br label %end

cmp.false:
  %a3 = bitcast <8 x i32> %a to <16 x bfloat>
  br label %end

end:
  %phi = phi <16 x bfloat> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x bfloat> %phi
}

define inreg <16 x bfloat> @bitcast_v8i32_to_v16bf16_scalar(<8 x i32> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v8i32_to_v16bf16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB21_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s7, s23, 0xffff0000
; SI-NEXT:    s_lshl_b32 s6, s23, 16
; SI-NEXT:    s_and_b32 s9, s22, 0xffff0000
; SI-NEXT:    s_lshl_b32 s8, s22, 16
; SI-NEXT:    s_and_b32 s11, s21, 0xffff0000
; SI-NEXT:    s_lshl_b32 s10, s21, 16
; SI-NEXT:    s_and_b32 s13, s20, 0xffff0000
; SI-NEXT:    s_lshl_b32 s12, s20, 16
; SI-NEXT:    s_and_b32 s15, s19, 0xffff0000
; SI-NEXT:    s_lshl_b32 s14, s19, 16
; SI-NEXT:    s_and_b32 s25, s18, 0xffff0000
; SI-NEXT:    s_lshl_b32 s24, s18, 16
; SI-NEXT:    s_and_b32 s27, s17, 0xffff0000
; SI-NEXT:    s_lshl_b32 s26, s17, 16
; SI-NEXT:    s_and_b32 s29, s16, 0xffff0000
; SI-NEXT:    s_lshl_b32 s28, s16, 16
; SI-NEXT:    s_cbranch_execnz .LBB21_3
; SI-NEXT:  .LBB21_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    s_add_i32 s17, s17, 3
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_add_i32 s19, s19, 3
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_add_i32 s21, s21, 3
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_add_i32 s23, s23, 3
; SI-NEXT:    s_and_b32 s7, s23, 0xffff0000
; SI-NEXT:    s_lshl_b32 s6, s23, 16
; SI-NEXT:    s_and_b32 s9, s22, 0xffff0000
; SI-NEXT:    s_lshl_b32 s8, s22, 16
; SI-NEXT:    s_and_b32 s11, s21, 0xffff0000
; SI-NEXT:    s_lshl_b32 s10, s21, 16
; SI-NEXT:    s_and_b32 s13, s20, 0xffff0000
; SI-NEXT:    s_lshl_b32 s12, s20, 16
; SI-NEXT:    s_and_b32 s15, s19, 0xffff0000
; SI-NEXT:    s_lshl_b32 s14, s19, 16
; SI-NEXT:    s_and_b32 s25, s18, 0xffff0000
; SI-NEXT:    s_lshl_b32 s24, s18, 16
; SI-NEXT:    s_and_b32 s27, s17, 0xffff0000
; SI-NEXT:    s_lshl_b32 s26, s17, 16
; SI-NEXT:    s_and_b32 s29, s16, 0xffff0000
; SI-NEXT:    s_lshl_b32 s28, s16, 16
; SI-NEXT:  .LBB21_3: ; %end
; SI-NEXT:    v_mul_f32_e64 v0, 1.0, s29
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v0
; SI-NEXT:    v_mul_f32_e64 v0, 1.0, s28
; SI-NEXT:    v_lshr_b64 v[0:1], v[0:1], 16
; SI-NEXT:    v_mul_f32_e64 v1, 1.0, s27
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v1
; SI-NEXT:    v_mul_f32_e64 v1, 1.0, s26
; SI-NEXT:    v_lshr_b64 v[1:2], v[1:2], 16
; SI-NEXT:    v_mul_f32_e64 v2, 1.0, s25
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v2
; SI-NEXT:    v_mul_f32_e64 v2, 1.0, s24
; SI-NEXT:    v_lshr_b64 v[2:3], v[2:3], 16
; SI-NEXT:    v_mul_f32_e64 v3, 1.0, s15
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v3
; SI-NEXT:    v_mul_f32_e64 v3, 1.0, s14
; SI-NEXT:    v_lshr_b64 v[3:4], v[3:4], 16
; SI-NEXT:    v_mul_f32_e64 v4, 1.0, s13
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v4
; SI-NEXT:    v_mul_f32_e64 v4, 1.0, s12
; SI-NEXT:    v_lshr_b64 v[4:5], v[4:5], 16
; SI-NEXT:    v_mul_f32_e64 v5, 1.0, s11
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v5
; SI-NEXT:    v_mul_f32_e64 v5, 1.0, s10
; SI-NEXT:    v_lshr_b64 v[5:6], v[5:6], 16
; SI-NEXT:    v_mul_f32_e64 v6, 1.0, s9
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v6
; SI-NEXT:    v_mul_f32_e64 v6, 1.0, s8
; SI-NEXT:    v_lshr_b64 v[6:7], v[6:7], 16
; SI-NEXT:    v_mul_f32_e64 v7, 1.0, s7
; SI-NEXT:    v_lshrrev_b32_e32 v8, 16, v7
; SI-NEXT:    v_mul_f32_e64 v7, 1.0, s6
; SI-NEXT:    v_lshr_b64 v[7:8], v[7:8], 16
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB21_4:
; SI-NEXT:    ; implicit-def: $sgpr28
; SI-NEXT:    ; implicit-def: $sgpr29
; SI-NEXT:    ; implicit-def: $sgpr26
; SI-NEXT:    ; implicit-def: $sgpr27
; SI-NEXT:    ; implicit-def: $sgpr24
; SI-NEXT:    ; implicit-def: $sgpr25
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr15
; SI-NEXT:    ; implicit-def: $sgpr12
; SI-NEXT:    ; implicit-def: $sgpr13
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr11
; SI-NEXT:    ; implicit-def: $sgpr8
; SI-NEXT:    ; implicit-def: $sgpr9
; SI-NEXT:    ; implicit-def: $sgpr6
; SI-NEXT:    ; implicit-def: $sgpr7
; SI-NEXT:    s_branch .LBB21_2
;
; VI-LABEL: bitcast_v8i32_to_v16bf16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB21_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB21_3
; VI-NEXT:  .LBB21_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s23, s23, 3
; VI-NEXT:    s_add_i32 s22, s22, 3
; VI-NEXT:    s_add_i32 s21, s21, 3
; VI-NEXT:    s_add_i32 s20, s20, 3
; VI-NEXT:    s_add_i32 s19, s19, 3
; VI-NEXT:    s_add_i32 s18, s18, 3
; VI-NEXT:    s_add_i32 s17, s17, 3
; VI-NEXT:    s_add_i32 s16, s16, 3
; VI-NEXT:  .LBB21_3: ; %end
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB21_4:
; VI-NEXT:    s_branch .LBB21_2
;
; GFX9-LABEL: bitcast_v8i32_to_v16bf16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB21_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB21_3
; GFX9-NEXT:  .LBB21_2: ; %cmp.true
; GFX9-NEXT:    s_add_i32 s23, s23, 3
; GFX9-NEXT:    s_add_i32 s22, s22, 3
; GFX9-NEXT:    s_add_i32 s21, s21, 3
; GFX9-NEXT:    s_add_i32 s20, s20, 3
; GFX9-NEXT:    s_add_i32 s19, s19, 3
; GFX9-NEXT:    s_add_i32 s18, s18, 3
; GFX9-NEXT:    s_add_i32 s17, s17, 3
; GFX9-NEXT:    s_add_i32 s16, s16, 3
; GFX9-NEXT:  .LBB21_3: ; %end
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB21_4:
; GFX9-NEXT:    s_branch .LBB21_2
;
; GFX11-LABEL: bitcast_v8i32_to_v16bf16_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s4, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB21_4
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s4
; GFX11-NEXT:    s_cbranch_vccnz .LBB21_3
; GFX11-NEXT:  .LBB21_2: ; %cmp.true
; GFX11-NEXT:    s_add_i32 s19, s19, 3
; GFX11-NEXT:    s_add_i32 s18, s18, 3
; GFX11-NEXT:    s_add_i32 s17, s17, 3
; GFX11-NEXT:    s_add_i32 s16, s16, 3
; GFX11-NEXT:    s_add_i32 s3, s3, 3
; GFX11-NEXT:    s_add_i32 s2, s2, 3
; GFX11-NEXT:    s_add_i32 s1, s1, 3
; GFX11-NEXT:    s_add_i32 s0, s0, 3
; GFX11-NEXT:  .LBB21_3: ; %end
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s16 :: v_dual_mov_b32 v5, s17
; GFX11-NEXT:    v_dual_mov_b32 v6, s18 :: v_dual_mov_b32 v7, s19
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB21_4:
; GFX11-NEXT:    s_branch .LBB21_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <8 x i32> %a, splat (i32 3)
  %a2 = bitcast <8 x i32> %a1 to <16 x bfloat>
  br label %end

cmp.false:
  %a3 = bitcast <8 x i32> %a to <16 x bfloat>
  br label %end

end:
  %phi = phi <16 x bfloat> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x bfloat> %phi
}

define <8 x i32> @bitcast_v16bf16_to_v8i32(<16 x bfloat> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v16bf16_to_v8i32:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_and_b32_e32 v9, 0xffff0000, v7
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_and_b32_e32 v10, 0xffff0000, v6
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_and_b32_e32 v11, 0xffff0000, v5
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v12, 0xffff0000, v4
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_and_b32_e32 v13, 0xffff0000, v3
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v14, 0xffff0000, v2
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_and_b32_e32 v15, 0xffff0000, v1
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_and_b32_e32 v16, 0xffff0000, v0
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    v_mul_f32_e32 v22, 1.0, v16
; SI-NEXT:    v_mul_f32_e32 v23, 1.0, v0
; SI-NEXT:    v_mul_f32_e32 v20, 1.0, v15
; SI-NEXT:    v_mul_f32_e32 v21, 1.0, v1
; SI-NEXT:    v_mul_f32_e32 v18, 1.0, v14
; SI-NEXT:    v_mul_f32_e32 v19, 1.0, v2
; SI-NEXT:    v_mul_f32_e32 v16, 1.0, v13
; SI-NEXT:    v_mul_f32_e32 v17, 1.0, v3
; SI-NEXT:    v_mul_f32_e32 v14, 1.0, v12
; SI-NEXT:    v_mul_f32_e32 v15, 1.0, v4
; SI-NEXT:    v_mul_f32_e32 v12, 1.0, v11
; SI-NEXT:    v_mul_f32_e32 v13, 1.0, v5
; SI-NEXT:    v_mul_f32_e32 v10, 1.0, v10
; SI-NEXT:    v_mul_f32_e32 v11, 1.0, v6
; SI-NEXT:    v_mul_f32_e32 v8, 1.0, v9
; SI-NEXT:    v_mul_f32_e32 v9, 1.0, v7
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB22_3
; SI-NEXT:  ; %bb.1: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB22_4
; SI-NEXT:  .LBB22_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB22_3: ; %cmp.false
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v22
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v20
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v18
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v16
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v14
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v12
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v10
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v8
; SI-NEXT:    v_alignbit_b32 v0, v0, v23, 16
; SI-NEXT:    v_alignbit_b32 v1, v1, v21, 16
; SI-NEXT:    v_alignbit_b32 v2, v2, v19, 16
; SI-NEXT:    v_alignbit_b32 v3, v3, v17, 16
; SI-NEXT:    v_alignbit_b32 v4, v4, v15, 16
; SI-NEXT:    v_alignbit_b32 v5, v5, v13, 16
; SI-NEXT:    v_alignbit_b32 v6, v6, v11, 16
; SI-NEXT:    v_alignbit_b32 v7, v7, v9, 16
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB22_2
; SI-NEXT:  .LBB22_4: ; %cmp.true
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v22
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v20
; SI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v23
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v21
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_alignbit_b32 v0, v1, v0, 16
; SI-NEXT:    v_alignbit_b32 v1, v3, v2, 16
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v18
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v19
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v16
; SI-NEXT:    v_alignbit_b32 v2, v3, v2, 16
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v17
; SI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v14
; SI-NEXT:    v_alignbit_b32 v3, v4, v3, 16
; SI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v15
; SI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; SI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v12
; SI-NEXT:    v_alignbit_b32 v4, v5, v4, 16
; SI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v13
; SI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; SI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v10
; SI-NEXT:    v_alignbit_b32 v5, v6, v5, 16
; SI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v11
; SI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; SI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_and_b32_e32 v8, 0xffff0000, v8
; SI-NEXT:    v_alignbit_b32 v6, v7, v6, 16
; SI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v9
; SI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; SI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; SI-NEXT:    v_lshrrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_alignbit_b32 v7, v8, v7, 16
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16bf16_to_v8i32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB22_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v7
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, 0x7fff, v9
; VI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v7, 16, 1
; VI-NEXT:    s_movk_i32 s6, 0x7fff
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v7
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v7
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; VI-NEXT:    v_cndmask_b32_e32 v7, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; VI-NEXT:    v_alignbit_b32 v7, v7, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v6
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v6, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v6
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v6
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; VI-NEXT:    v_cndmask_b32_e32 v6, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_alignbit_b32 v6, v6, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v5
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v5, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v5
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v5
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; VI-NEXT:    v_cndmask_b32_e32 v5, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_alignbit_b32 v5, v5, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v4
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v4, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v4
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v4
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; VI-NEXT:    v_cndmask_b32_e32 v4, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_alignbit_b32 v4, v4, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v3
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v3
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_alignbit_b32 v3, v3, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v2
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v2
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_alignbit_b32 v2, v2, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v1
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v1, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v1
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v1
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; VI-NEXT:    v_cndmask_b32_e32 v1, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_alignbit_b32 v1, v1, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v0
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v0, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v0
; VI-NEXT:    v_add_u32_e32 v9, vcc, 0x7fff, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v0
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; VI-NEXT:    v_cndmask_b32_e32 v0, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; VI-NEXT:    v_alignbit_b32 v0, v0, v8, 16
; VI-NEXT:  .LBB22_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16bf16_to_v8i32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB22_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v7
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    s_movk_i32 s6, 0x7fff
; GFX9-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v7, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v7, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v7
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; GFX9-NEXT:    v_cndmask_b32_e32 v7, v9, v10, vcc
; GFX9-NEXT:    s_mov_b32 s7, 0x7060302
; GFX9-NEXT:    v_perm_b32 v7, v7, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v6
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v6, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v6, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v6
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; GFX9-NEXT:    v_cndmask_b32_e32 v6, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v6, v6, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v5
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v5, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v5, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v5, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v5, v5, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v4
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v4, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v4, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v4
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; GFX9-NEXT:    v_cndmask_b32_e32 v4, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v4, v4, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v3
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v3, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v3, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v3
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; GFX9-NEXT:    v_cndmask_b32_e32 v3, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v3, v3, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v2, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v2, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v2, v2, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v1
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v1, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v1, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v1, v1, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v0
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v0, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v0, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v0
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v0, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v0, v0, v8, s7
; GFX9-NEXT:  .LBB22_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v16bf16_to_v8i32:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v8
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
; GFX11-TRUE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v15, v7 :: v_dual_mov_b32 v14, v6
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v13, v5 :: v_dual_mov_b32 v12, v4
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v11, v3 :: v_dual_mov_b32 v10, v2
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v9, v1 :: v_dual_mov_b32 v8, v0
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr7
; GFX11-TRUE16-NEXT:  ; %bb.2: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB22_4
; GFX11-TRUE16-NEXT:  ; %bb.3: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v9, 0xffff0000, v6
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v8, 16, v7
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v10, 0xffff0000, v5
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v9, 0x40c00000, v9 :: v_dual_add_f32 v8, 0x40c00000, v8
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v15, v9, 16, 1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v11, v8, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v14, 0x400000, v8
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add3_u32 v11, v11, v8, 0x7fff
; GFX11-TRUE16-NEXT:    v_dual_cndmask_b32 v8, v11, v14 :: v_dual_and_b32 v7, 0xffff0000, v7
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v7, 0x40c00000, v7 :: v_dual_lshlrev_b32 v6, 16, v6
; GFX11-TRUE16-NEXT:    v_add3_u32 v11, v15, v9, 0x7fff
; GFX11-TRUE16-NEXT:    v_bfe_u32 v12, v7, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v13, 0x400000, v7
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add3_u32 v12, v12, v7, 0x7fff
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v6, 0x40c00000, v6 :: v_dual_cndmask_b32 v15, v12, v13
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v16, v6, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v17, 0x400000, v6
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v15.l, v8.h
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v9
; GFX11-TRUE16-NEXT:    v_add3_u32 v14, v16, v6, 0x7fff
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v6, v14, v17, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v7, 0x40c00000, v10
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v9, 0xffff0000, v4
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v14, v11, v8, vcc_lo
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v10, v7, 16, 1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v8, v5, 16, 1
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v14.l, v6.h
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v9, 0x40c00000, v9 :: v_dual_add_f32 v4, 0x40c00000, v4
; GFX11-TRUE16-NEXT:    v_add3_u32 v6, v10, v7, 0x7fff
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_add3_u32 v8, v8, v5, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v10, 0x400000, v5
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v11, 0x400000, v7
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v5, v8, v10, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-TRUE16-NEXT:    v_bfe_u32 v7, v4, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v4
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v10, 0x400000, v9
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v13, v6, v11, vcc_lo
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_add3_u32 v7, v7, v4, 0x7fff
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-TRUE16-NEXT:    v_bfe_u32 v6, v9, 16, 1
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v11, 0xffff0000, v2
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v4, v7, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v13.l, v5.h
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v5, 0xffff0000, v3
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_2) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v2, 0x40c00000, v2 :: v_dual_lshlrev_b32 v3, 16, v3
; GFX11-TRUE16-NEXT:    v_add3_u32 v6, v6, v9, 0x7fff
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v3, 0x40c00000, v3 :: v_dual_cndmask_b32 v12, v6, v10
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v6, 0x40c00000, v11
; GFX11-TRUE16-NEXT:    v_bfe_u32 v7, v5, 16, 1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v8, v3, 16, 1
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v12.l, v4.h
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v9, 0x400000, v5
; GFX11-TRUE16-NEXT:    v_add3_u32 v4, v7, v5, 0x7fff
; GFX11-TRUE16-NEXT:    v_add3_u32 v7, v8, v3, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v3
; GFX11-TRUE16-NEXT:    v_bfe_u32 v10, v6, 16, 1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v3, v7, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, 0x400000, v6
; GFX11-TRUE16-NEXT:    v_bfe_u32 v7, v2, 16, 1
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v11, v4, v9, vcc_lo
; GFX11-TRUE16-NEXT:    v_add3_u32 v4, v10, v6, 0x7fff
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v11.l, v3.h
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v3, 0xffff0000, v1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v3, 0x40c00000, v3 :: v_dual_lshlrev_b32 v6, 16, v0
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v10, v4, v5, vcc_lo
; GFX11-TRUE16-NEXT:    v_add3_u32 v4, v7, v2, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, 0x400000, v2
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v7, 0x400000, v3
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v2, v4, v5, vcc_lo
; GFX11-TRUE16-NEXT:    v_bfe_u32 v4, v3, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v5, 0x40c00000, v6
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v10.l, v2.h
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_4) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_add3_u32 v4, v4, v3, 0x7fff
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v6, v5, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v16, 0x400000, v5
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v0, 0x40c00000, v0 :: v_dual_add_f32 v1, 0x40c00000, v1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_add3_u32 v6, v6, v5, 0x7fff
; GFX11-TRUE16-NEXT:    v_bfe_u32 v9, v0, 16, 1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-TRUE16-NEXT:    v_add3_u32 v2, v2, v1, 0x7fff
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v2, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-TRUE16-NEXT:    v_add3_u32 v2, v9, v0, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v0
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v5, v6, v16, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v9, v4, v7, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v9.l, v1.h
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v8, v2, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v8.l, v5.h
; GFX11-TRUE16-NEXT:  .LBB22_4: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v0, v8 :: v_dual_mov_b32 v1, v9
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v2, v10 :: v_dual_mov_b32 v3, v11
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v4, v12 :: v_dual_mov_b32 v5, v13
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v6, v14 :: v_dual_mov_b32 v7, v15
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v16bf16_to_v8i32:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-FAKE16-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB22_2
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v9, 16, v6
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v8, 16, v7
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v9, 0x40c00000, v9 :: v_dual_add_f32 v8, 0x40c00000, v8
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v9, 16, 1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v10, v8, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, 0x400000, v8
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v15, v6, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-FAKE16-NEXT:    v_add3_u32 v13, v13, v9, 0x7fff
; GFX11-FAKE16-NEXT:    v_add3_u32 v10, v10, v8, 0x7fff
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v8, v10, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_add3_u32 v11, v15, v6, 0x7fff
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v10, 0x400000, v9
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GFX11-FAKE16-NEXT:    v_bfe_u32 v12, v7, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v14, 0x400000, v7
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_add3_u32 v12, v12, v7, 0x7fff
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v7, v12, v14 :: v_dual_lshlrev_b32 v12, 16, v5
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v7, v8, 0x7060302
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v14, 0x400000, v6
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v9, v13, v10 :: v_dual_add_f32 v10, 0x40c00000, v12
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v8, v5, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v13, 0x400000, v5
; GFX11-FAKE16-NEXT:    v_bfe_u32 v12, v10, 16, 1
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v6, v11, v14 :: v_dual_lshlrev_b32 v11, 16, v4
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-FAKE16-NEXT:    v_add3_u32 v8, v8, v5, 0x7fff
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v6, v9, 0x7060302
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v9, 0x40c00000, v11 :: v_dual_add_f32 v4, 0x40c00000, v4
; GFX11-FAKE16-NEXT:    v_add3_u32 v11, v12, v10, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, 0x400000, v10
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v14, v9, 16, 1
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v10, v11, v12, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, 0x400000, v9
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v12, 16, v3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v5, v8, v13, vcc_lo
; GFX11-FAKE16-NEXT:    v_add3_u32 v8, v14, v9, 0x7fff
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v9, 0x40c00000, v12 :: v_dual_lshlrev_b32 v12, 16, v2
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v5, v10, 0x7060302
; GFX11-FAKE16-NEXT:    v_bfe_u32 v10, v4, 16, 1
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v8, v8, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, 0x400000, v4
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v9, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-FAKE16-NEXT:    v_add3_u32 v10, v10, v4, 0x7fff
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v4, v10, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v10, 0x40c00000, v12
; GFX11-FAKE16-NEXT:    v_add3_u32 v11, v13, v9, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, 0x400000, v9
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v3, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-FAKE16-NEXT:    v_bfe_u32 v14, v10, 16, 1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v9, v11, v12, vcc_lo
; GFX11-FAKE16-NEXT:    v_add3_u32 v11, v13, v3, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, 0x400000, v3
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; GFX11-FAKE16-NEXT:    v_add3_u32 v13, v14, v10, 0x7fff
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v14, 16, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v3, v11, v12 :: v_dual_add_f32 v2, 0x40c00000, v2
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v4, v8, 0x7060302
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v11, 0x40c00000, v14
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v15, 0x400000, v10
; GFX11-FAKE16-NEXT:    v_bfe_u32 v16, v2, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-FAKE16-NEXT:    v_bfe_u32 v14, v11, 16, 1
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v3, v9, 0x7060302
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_add3_u32 v12, v16, v2, 0x7fff
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v10, v13, v15 :: v_dual_lshlrev_b32 v15, 16, v0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v13, 0x400000, v2
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v2, v12, v13, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v12, 0x40c00000, v15
; GFX11-FAKE16-NEXT:    v_add3_u32 v13, v14, v11, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v14, 0x400000, v11
; GFX11-FAKE16-NEXT:    v_bfe_u32 v15, v1, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v11, v11
; GFX11-FAKE16-NEXT:    v_bfe_u32 v16, v12, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v17, 0x400000, v12
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v2, v10, 0x7060302
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v11, v13, v14, vcc_lo
; GFX11-FAKE16-NEXT:    v_add3_u32 v14, v15, v1, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v15, 0x400000, v1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX11-FAKE16-NEXT:    v_add3_u32 v16, v16, v12, 0x7fff
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v1, v14, v15 :: v_dual_add_f32 v0, 0x40c00000, v0
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v12, v12
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v1, v11, 0x7060302
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_3) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v0, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v18, 0x400000, v0
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v12, v16, v17, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-FAKE16-NEXT:    v_add3_u32 v13, v13, v0, 0x7fff
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v0, v13, v18, vcc_lo
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v0, v12, 0x7060302
; GFX11-FAKE16-NEXT:  .LBB22_2: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x bfloat> %a, splat (bfloat 0xR40C0)
  %a2 = bitcast <16 x bfloat> %a1 to <8 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <16 x bfloat> %a to <8 x i32>
  br label %end

end:
  %phi = phi <8 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x i32> %phi
}

define inreg <8 x i32> @bitcast_v16bf16_to_v8i32_scalar(<16 x bfloat> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v16bf16_to_v8i32_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_and_b32 s4, s23, 0xffff0000
; SI-NEXT:    s_lshl_b32 s5, s23, 16
; SI-NEXT:    s_and_b32 s6, s22, 0xffff0000
; SI-NEXT:    s_lshl_b32 s7, s22, 16
; SI-NEXT:    s_and_b32 s8, s21, 0xffff0000
; SI-NEXT:    s_lshl_b32 s9, s21, 16
; SI-NEXT:    s_and_b32 s10, s20, 0xffff0000
; SI-NEXT:    s_lshl_b32 s11, s20, 16
; SI-NEXT:    s_and_b32 s12, s19, 0xffff0000
; SI-NEXT:    s_lshl_b32 s13, s19, 16
; SI-NEXT:    s_and_b32 s14, s18, 0xffff0000
; SI-NEXT:    s_lshl_b32 s15, s18, 16
; SI-NEXT:    s_and_b32 s18, s17, 0xffff0000
; SI-NEXT:    s_lshl_b32 s17, s17, 16
; SI-NEXT:    s_and_b32 s19, s16, 0xffff0000
; SI-NEXT:    s_lshl_b32 s16, s16, 16
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    v_mul_f32_e64 v32, 1.0, s19
; SI-NEXT:    v_mul_f32_e64 v23, 1.0, s16
; SI-NEXT:    v_mul_f32_e64 v31, 1.0, s18
; SI-NEXT:    v_mul_f32_e64 v21, 1.0, s17
; SI-NEXT:    v_mul_f32_e64 v30, 1.0, s14
; SI-NEXT:    v_mul_f32_e64 v19, 1.0, s15
; SI-NEXT:    v_mul_f32_e64 v29, 1.0, s12
; SI-NEXT:    v_mul_f32_e64 v17, 1.0, s13
; SI-NEXT:    v_mul_f32_e64 v28, 1.0, s10
; SI-NEXT:    v_mul_f32_e64 v15, 1.0, s11
; SI-NEXT:    v_mul_f32_e64 v27, 1.0, s8
; SI-NEXT:    v_mul_f32_e64 v13, 1.0, s9
; SI-NEXT:    v_mul_f32_e64 v26, 1.0, s6
; SI-NEXT:    v_mul_f32_e64 v25, 1.0, s4
; SI-NEXT:    v_mul_f32_e64 v11, 1.0, s7
; SI-NEXT:    v_mul_f32_e64 v9, 1.0, s5
; SI-NEXT:    s_cbranch_scc0 .LBB23_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_lshrrev_b32_e32 v24, 16, v32
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v31
; SI-NEXT:    v_lshr_b64 v[0:1], v[23:24], 16
; SI-NEXT:    v_lshr_b64 v[1:2], v[21:22], 16
; SI-NEXT:    v_lshrrev_b32_e32 v20, 16, v30
; SI-NEXT:    v_lshr_b64 v[2:3], v[19:20], 16
; SI-NEXT:    v_lshrrev_b32_e32 v18, 16, v29
; SI-NEXT:    v_lshr_b64 v[3:4], v[17:18], 16
; SI-NEXT:    v_lshrrev_b32_e32 v16, 16, v28
; SI-NEXT:    v_lshr_b64 v[4:5], v[15:16], 16
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v27
; SI-NEXT:    v_lshr_b64 v[5:6], v[13:14], 16
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v26
; SI-NEXT:    v_lshr_b64 v[6:7], v[11:12], 16
; SI-NEXT:    v_lshrrev_b32_e32 v10, 16, v25
; SI-NEXT:    v_lshr_b64 v[7:8], v[9:10], 16
; SI-NEXT:    s_cbranch_execnz .LBB23_3
; SI-NEXT:  .LBB23_2: ; %cmp.true
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v32
; SI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v23
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v31
; SI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v21
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_lshr_b64 v[0:1], v[0:1], 16
; SI-NEXT:    v_lshr_b64 v[1:2], v[2:3], 16
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v30
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v19
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_lshr_b64 v[2:3], v[2:3], 16
; SI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v29
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v17
; SI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_lshr_b64 v[3:4], v[3:4], 16
; SI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v28
; SI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v15
; SI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; SI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_lshr_b64 v[4:5], v[4:5], 16
; SI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v27
; SI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v13
; SI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; SI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_lshr_b64 v[5:6], v[5:6], 16
; SI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v26
; SI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v11
; SI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; SI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_lshr_b64 v[6:7], v[6:7], 16
; SI-NEXT:    v_and_b32_e32 v8, 0xffff0000, v25
; SI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v9
; SI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; SI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; SI-NEXT:    v_lshrrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_lshr_b64 v[7:8], v[7:8], 16
; SI-NEXT:  .LBB23_3: ; %end
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB23_4:
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; SI-NEXT:    s_branch .LBB23_2
;
; VI-LABEL: bitcast_v16bf16_to_v8i32_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB23_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB23_4
; VI-NEXT:  .LBB23_2: ; %cmp.true
; VI-NEXT:    s_lshl_b32 s4, s23, 16
; VI-NEXT:    v_mov_b32_e32 v8, 0x40c00000
; VI-NEXT:    v_add_f32_e32 v0, s4, v8
; VI-NEXT:    v_bfe_u32 v1, v0, 16, 1
; VI-NEXT:    v_add_u32_e32 v1, vcc, v1, v0
; VI-NEXT:    v_add_u32_e32 v1, vcc, 0x7fff, v1
; VI-NEXT:    v_or_b32_e32 v2, 0x400000, v0
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; VI-NEXT:    s_and_b32 s4, s23, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v0, v1, v2, vcc
; VI-NEXT:    v_add_f32_e32 v1, s4, v8
; VI-NEXT:    v_bfe_u32 v2, v1, 16, 1
; VI-NEXT:    v_add_u32_e32 v2, vcc, v2, v1
; VI-NEXT:    v_add_u32_e32 v2, vcc, 0x7fff, v2
; VI-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; VI-NEXT:    s_lshl_b32 s4, s22, 16
; VI-NEXT:    v_cndmask_b32_e32 v1, v2, v3, vcc
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    s_and_b32 s4, s22, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; VI-NEXT:    v_add_f32_e32 v3, s4, v8
; VI-NEXT:    v_bfe_u32 v4, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v4, vcc, v4, v3
; VI-NEXT:    v_add_u32_e32 v4, vcc, 0x7fff, v4
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v4, v5, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    s_lshl_b32 s4, s21, 16
; VI-NEXT:    v_lshrrev_b64 v[6:7], 16, v[2:3]
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    s_and_b32 s4, s21, 0xffff0000
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_cndmask_b32_e32 v9, v3, v4, vcc
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; VI-NEXT:    s_lshl_b32 s4, s20, 16
; VI-NEXT:    v_lshrrev_b32_e32 v10, 16, v2
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    s_and_b32 s4, s20, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; VI-NEXT:    v_add_f32_e32 v3, s4, v8
; VI-NEXT:    v_bfe_u32 v4, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v4, vcc, v4, v3
; VI-NEXT:    v_add_u32_e32 v4, vcc, 0x7fff, v4
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v4, v5, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    s_lshl_b32 s4, s19, 16
; VI-NEXT:    v_lshrrev_b64 v[4:5], 16, v[2:3]
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    s_and_b32 s4, s19, 0xffff0000
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_cndmask_b32_e32 v11, v3, v5, vcc
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v5, vcc
; VI-NEXT:    s_lshl_b32 s4, s18, 16
; VI-NEXT:    v_lshrrev_b32_e32 v12, 16, v2
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    s_and_b32 s4, s18, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v5, vcc
; VI-NEXT:    v_add_f32_e32 v3, s4, v8
; VI-NEXT:    v_bfe_u32 v5, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v3
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    v_or_b32_e32 v7, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v5, v7, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_lshrrev_b64 v[2:3], 16, v[2:3]
; VI-NEXT:    s_lshl_b32 s4, s17, 16
; VI-NEXT:    v_add_f32_e32 v3, s4, v8
; VI-NEXT:    v_bfe_u32 v5, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v3
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    s_and_b32 s4, s17, 0xffff0000
; VI-NEXT:    v_or_b32_e32 v7, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_add_f32_e32 v3, s4, v8
; VI-NEXT:    v_cndmask_b32_e32 v13, v5, v7, vcc
; VI-NEXT:    v_bfe_u32 v5, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v3
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    v_or_b32_e32 v7, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v5, v7, vcc
; VI-NEXT:    s_lshl_b32 s4, s16, 16
; VI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; VI-NEXT:    v_add_f32_e32 v3, s4, v8
; VI-NEXT:    v_bfe_u32 v5, v3, 16, 1
; VI-NEXT:    s_and_b32 s6, s16, 0xffff0000
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v3
; VI-NEXT:    v_or_b32_e32 v15, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e64 s[4:5], v3, v3
; VI-NEXT:    v_add_f32_e32 v3, s6, v8
; VI-NEXT:    v_bfe_u32 v7, v3, 16, 1
; VI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_add_u32_e32 v7, vcc, v7, v3
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    v_add_u32_e32 v16, vcc, 0x7fff, v7
; VI-NEXT:    v_lshrrev_b64 v[7:8], 16, v[0:1]
; VI-NEXT:    v_or_b32_e32 v17, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_lshrrev_b64 v[8:9], 16, v[9:10]
; VI-NEXT:    v_lshrrev_b64 v[9:10], 16, v[11:12]
; VI-NEXT:    v_cndmask_b32_e32 v1, v16, v17, vcc
; VI-NEXT:    v_lshrrev_b64 v[10:11], 16, v[13:14]
; VI-NEXT:    v_cndmask_b32_e64 v0, v5, v15, s[4:5]
; VI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_lshrrev_b64 v[0:1], 16, v[0:1]
; VI-NEXT:    v_mov_b32_e32 v1, v10
; VI-NEXT:    v_mov_b32_e32 v3, v9
; VI-NEXT:    v_mov_b32_e32 v5, v8
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB23_3:
; VI-NEXT:    s_branch .LBB23_2
; VI-NEXT:  .LBB23_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16bf16_to_v8i32_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB23_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB23_4
; GFX9-NEXT:  .LBB23_2: ; %cmp.true
; GFX9-NEXT:    s_and_b32 s4, s23, 0xffff0000
; GFX9-NEXT:    v_mov_b32_e32 v0, 0x40c00000
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v1
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s23, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v2, v3, vcc
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v0
; GFX9-NEXT:    v_bfe_u32 v3, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v3, v3, v2
; GFX9-NEXT:    v_add_u32_e32 v3, 0x7fff, v3
; GFX9-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; GFX9-NEXT:    v_mov_b32_e32 v8, 0xffff
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v2, v8, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s22, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v7, v1, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v1
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s22, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v2, v3, vcc
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v0
; GFX9-NEXT:    v_bfe_u32 v3, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v3, v3, v2
; GFX9-NEXT:    v_add_u32_e32 v3, 0x7fff, v3
; GFX9-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v2, v8, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s21, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v6, v1, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v1
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s21, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v2, v3, vcc
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v0
; GFX9-NEXT:    v_bfe_u32 v3, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v3, v3, v2
; GFX9-NEXT:    v_add_u32_e32 v3, 0x7fff, v3
; GFX9-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v2, v8, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s20, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v5, v1, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v1
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s20, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v2, v3, vcc
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v0
; GFX9-NEXT:    v_bfe_u32 v3, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v3, v3, v2
; GFX9-NEXT:    v_add_u32_e32 v3, 0x7fff, v3
; GFX9-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v2, v8, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s19, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v4, v1, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v1
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s19, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v2, v3, vcc
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v0
; GFX9-NEXT:    v_bfe_u32 v3, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v3, v3, v2
; GFX9-NEXT:    v_add_u32_e32 v3, 0x7fff, v3
; GFX9-NEXT:    v_or_b32_e32 v9, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v3, v9, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v2, v8, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s18, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v3, v1, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v1
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v9, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s18, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v2, v9, vcc
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v0
; GFX9-NEXT:    v_bfe_u32 v9, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v9, v9, v2
; GFX9-NEXT:    v_add_u32_e32 v9, 0x7fff, v9
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v9, v10, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v2, v8, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s17, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v2, v1, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v9, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v9, v9, v1
; GFX9-NEXT:    v_add_u32_e32 v9, 0x7fff, v9
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s17, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v9, v10, vcc
; GFX9-NEXT:    v_add_f32_e32 v9, s4, v0
; GFX9-NEXT:    v_bfe_u32 v10, v9, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v10, v10, v9
; GFX9-NEXT:    v_add_u32_e32 v10, 0x7fff, v10
; GFX9-NEXT:    v_or_b32_e32 v11, 0x400000, v9
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v9, v9
; GFX9-NEXT:    v_cndmask_b32_e32 v9, v10, v11, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v9, v8, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s16, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v1, v1, 16, v9
; GFX9-NEXT:    v_add_f32_e32 v9, s4, v0
; GFX9-NEXT:    v_bfe_u32 v10, v9, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v10, v10, v9
; GFX9-NEXT:    s_lshl_b32 s4, s16, 16
; GFX9-NEXT:    v_add_u32_e32 v10, 0x7fff, v10
; GFX9-NEXT:    v_or_b32_e32 v11, 0x400000, v9
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v9, v9
; GFX9-NEXT:    v_add_f32_e32 v0, s4, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v9, v10, v11, vcc
; GFX9-NEXT:    v_bfe_u32 v10, v0, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v10, v10, v0
; GFX9-NEXT:    v_add_u32_e32 v10, 0x7fff, v10
; GFX9-NEXT:    v_or_b32_e32 v11, 0x400000, v0
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v0, v10, v11, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v9, 16, v9
; GFX9-NEXT:    v_and_b32_sdwa v0, v8, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    v_lshl_or_b32 v0, v9, 16, v0
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB23_3:
; GFX9-NEXT:    s_branch .LBB23_2
; GFX9-NEXT:  .LBB23_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v16bf16_to_v8i32_scalar:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_mov_b32 s7, s19
; GFX11-TRUE16-NEXT:    s_mov_b32 s6, s18
; GFX11-TRUE16-NEXT:    s_mov_b32 s5, s17
; GFX11-TRUE16-NEXT:    s_mov_b32 s4, s16
; GFX11-TRUE16-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-TRUE16-NEXT:    s_mov_b32 s8, 0
; GFX11-TRUE16-NEXT:    s_cbranch_scc0 .LBB23_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-TRUE16-NEXT:    s_cbranch_vccnz .LBB23_4
; GFX11-TRUE16-NEXT:  .LBB23_2: ; %cmp.true
; GFX11-TRUE16-NEXT:    s_and_b32 s8, s7, 0xffff0000
; GFX11-TRUE16-NEXT:    s_lshl_b32 s7, s7, 16
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v0, 0x40c00000, s8
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v1, 0x40c00000, s7
; GFX11-TRUE16-NEXT:    s_and_b32 s7, s6, 0xffff0000
; GFX11-TRUE16-NEXT:    s_lshl_b32 s6, s6, 16
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v4, 0x40c00000, s7
; GFX11-TRUE16-NEXT:    v_bfe_u32 v2, v0, 16, 1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v3, v1, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v5, 0x40c00000, s6
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v6, 0x400000, v0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v7, v4, 16, 1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, v2, v0
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v9, v5, 16, 1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v7, v7, v4
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v2
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, v3, v1
; GFX11-TRUE16-NEXT:    s_and_b32 s6, s5, 0xffff0000
; GFX11-TRUE16-NEXT:    s_lshl_b32 s5, s5, 16
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_dual_cndmask_b32 v0, v2, v6 :: v_dual_add_nc_u32 v3, 0x7fff, v3
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, 0x7fff, v7
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v3, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v3, 0x400000, v4
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, v9, v5
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v8, 0x40c00000, s5
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v7, 16, v1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v9, 0x400000, v5
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v3, v6, v3, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, 0x7fff, v2
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v2, 0x40c00000, s6
; GFX11-TRUE16-NEXT:    v_bfe_u32 v6, v8, 16, 1
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v7.h, v0.l
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v1, v9, vcc_lo
; GFX11-TRUE16-NEXT:    v_bfe_u32 v4, v2, 16, 1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v0, v6, v8
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-TRUE16-NEXT:    s_and_b32 s5, s4, 0xffff0000
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v6, 16, v1
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v6.h, v3.l
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v3, 0x400000, v2
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v4, v4, v2
; GFX11-TRUE16-NEXT:    s_lshl_b32 s4, s4, 16
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v0, 0x7fff, v0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v9, 0x40c00000, s4
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, 0x400000, v8
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, 0x7fff, v4
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v4, 0x40c00000, s5
; GFX11-TRUE16-NEXT:    s_and_b32 s4, s3, 0xffff0000
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v10, 0x400000, v9
; GFX11-TRUE16-NEXT:    s_lshl_b32 s3, s3, 16
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v1, v3, vcc_lo
; GFX11-TRUE16-NEXT:    v_bfe_u32 v2, v4, 16, 1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-TRUE16-NEXT:    v_bfe_u32 v3, v9, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v4
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, v2, v4
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v0, v0, v5, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, v3, v9
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v2
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v5, 16, v0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v0, 0x40c00000, s4
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v3
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v5.h, v1.l
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v2, v2, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-TRUE16-NEXT:    v_bfe_u32 v11, v0, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v1, 0x40c00000, s3
; GFX11-TRUE16-NEXT:    s_and_b32 s3, s2, 0xffff0000
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v3, v3, v10, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v8, v11, v0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v9, v1, 16, 1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-TRUE16-NEXT:    s_lshl_b32 s2, s2, 16
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v4, 16, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v8
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v0
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v4.h, v2.l
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v2, 0x40c00000, s3
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v10, 0x400000, v1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_dual_cndmask_b32 v0, v3, v8 :: v_dual_add_nc_u32 v3, v9, v1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v8, v2, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v9, 0x40c00000, s2
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-TRUE16-NEXT:    s_and_b32 s2, s1, 0xffff0000
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v8, v8, v2
; GFX11-TRUE16-NEXT:    v_bfe_u32 v11, v9, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v12, 0x400000, v2
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v3, v10, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v10, 0x40c00000, s2
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v8, 0x7fff, v8
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v11, v11, v9
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v3, 16, v1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v1, v10, 16, 1
; GFX11-TRUE16-NEXT:    s_lshl_b32 s1, s1, 16
; GFX11-TRUE16-NEXT:    s_and_b32 s2, s0, 0xffff0000
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v2, v8, v12, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v8, 0x7fff, v11
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v11, 0x400000, v9
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, v1, v10
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v3.h, v0.l
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v2
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v9, 0x40c00000, s2
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v2, v8, v11, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v8, 0x40c00000, s1
; GFX11-TRUE16-NEXT:    s_lshl_b32 s0, s0, 16
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, 0x7fff, v1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v11, 0x400000, v10
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v12, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v13, v8, 16, 1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v14, v9, 16, 1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v15, 0x400000, v8
; GFX11-TRUE16-NEXT:    v_bfe_u32 v10, v12, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v16, 0x400000, v12
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v1, v11, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v11, v13, v8
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v13, v14, v9
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.h, v0.l
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v14, 16, v1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, v10, v12
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v10, 0x7fff, v11
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v11, 0x7fff, v13
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v13, 0x400000, v9
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, 0x7fff, v1
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v9, v11, v13, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_3) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v9, 16, v9
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v8, v10, v15, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v12, v12
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v10, v1, v16, vcc_lo
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v1, 16, v8
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v1.h, v14.l
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v10
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.h, v9.l
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB23_3:
; GFX11-TRUE16-NEXT:    s_branch .LBB23_2
; GFX11-TRUE16-NEXT:  .LBB23_4:
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v16bf16_to_v8i32_scalar:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    s_mov_b32 s7, s19
; GFX11-FAKE16-NEXT:    s_mov_b32 s6, s18
; GFX11-FAKE16-NEXT:    s_mov_b32 s5, s17
; GFX11-FAKE16-NEXT:    s_mov_b32 s4, s16
; GFX11-FAKE16-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-FAKE16-NEXT:    s_mov_b32 s8, 0
; GFX11-FAKE16-NEXT:    s_cbranch_scc0 .LBB23_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-FAKE16-NEXT:    s_cbranch_vccnz .LBB23_4
; GFX11-FAKE16-NEXT:  .LBB23_2: ; %cmp.true
; GFX11-FAKE16-NEXT:    s_lshl_b32 s8, s7, 16
; GFX11-FAKE16-NEXT:    s_and_b32 s7, s7, 0xffff0000
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v0, 0x40c00000, s8
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v1, 0x40c00000, s7
; GFX11-FAKE16-NEXT:    s_and_b32 s8, s6, 0xffff0000
; GFX11-FAKE16-NEXT:    s_lshl_b32 s6, s6, 16
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v3, 0x40c00000, s8
; GFX11-FAKE16-NEXT:    v_bfe_u32 v2, v0, 16, 1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v4, v1, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v9, 0x400000, v1
; GFX11-FAKE16-NEXT:    s_and_b32 s7, s5, 0xffff0000
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v5, 0x40c00000, s6
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v6, 0x40c00000, s7
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, v4, v1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v8, 0x400000, v0
; GFX11-FAKE16-NEXT:    v_bfe_u32 v10, v3, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-FAKE16-NEXT:    s_lshl_b32 s5, s5, 16
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, 0x7fff, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, v2, v0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v7, 0x40c00000, s5
; GFX11-FAKE16-NEXT:    v_bfe_u32 v11, v6, 16, 1
; GFX11-FAKE16-NEXT:    s_and_b32 s5, s4, 0xffff0000
; GFX11-FAKE16-NEXT:    s_lshl_b32 s4, s4, 16
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v2
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_4) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v0, v2, v8, vcc_lo
; GFX11-FAKE16-NEXT:    v_bfe_u32 v2, v5, 16, 1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v8, v10, v3
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v10, 0x400000, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, v2, v5
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v1, v4, v9 :: v_dual_add_nc_u32 v8, 0x7fff, v8
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, 0x400000, v3
; GFX11-FAKE16-NEXT:    v_bfe_u32 v9, v7, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v3, v8, v4 :: v_dual_add_nc_u32 v4, v9, v7
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v5, v11, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v8, 0x400000, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, 0x7fff, v4
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v2, v2, v10 :: v_dual_add_nc_u32 v5, 0x7fff, v5
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v9, 0x400000, v6
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v10, 0x40c00000, s4
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v4, v4, v8, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v8, 0x40c00000, s5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v7, v1, 16, v0
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v5, v5, v9, vcc_lo
; GFX11-FAKE16-NEXT:    v_bfe_u32 v9, v10, 16, 1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v6, v8, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-FAKE16-NEXT:    s_and_b32 s4, s3, 0xffff0000
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v0, v9, v10
; GFX11-FAKE16-NEXT:    s_lshl_b32 s3, s3, 16
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v9, 0x40c00000, s3
; GFX11-FAKE16-NEXT:    s_and_b32 s3, s2, 0xffff0000
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v0, 0x7fff, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v11, v6, v8
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v6, v3, 16, v2
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, 0x400000, v10
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, 0x400000, v8
; GFX11-FAKE16-NEXT:    s_lshl_b32 s2, s2, 16
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, 0x400000, v9
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v0, v0, v3, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v1, 0x7fff, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v8, 0x40c00000, s3
; GFX11-FAKE16-NEXT:    v_bfe_u32 v3, v9, 16, 1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v1, v1, v2 :: v_dual_and_b32 v4, 0xffff, v4
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v10, v8, 16, 1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v5, v5, 16, v4
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v4, 0x40c00000, s4
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v10, v10, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v2, v4, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, 0x400000, v4
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, v2, v4
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v4, 0x40c00000, s2
; GFX11-FAKE16-NEXT:    s_and_b32 s2, s1, 0xffff0000
; GFX11-FAKE16-NEXT:    s_lshl_b32 s1, s1, 16
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, v3, v9
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v13, 0x40c00000, s1
; GFX11-FAKE16-NEXT:    s_lshl_b32 s1, s0, 16
; GFX11-FAKE16-NEXT:    s_and_b32 s0, s0, 0xffff0000
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v2, v2, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v9, 0x7fff, v10
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v3
; GFX11-FAKE16-NEXT:    v_bfe_u32 v11, v4, 16, 1
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v14, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v18, 0x400000, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v3, v3, v12, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-FAKE16-NEXT:    v_bfe_u32 v16, v14, 16, 1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v8, v9, v10 :: v_dual_add_nc_u32 v9, v11, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, 0x400000, v4
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v10, 0x40c00000, s2
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v16, v16, v14
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v9, 0x7fff, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v8, 16, v8
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v12, v10, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v17, 0x400000, v10
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v4, v9, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v9, 0x40c00000, s1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v11, v13, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v13, v13
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v12, v12, v10
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v15, v9, 16, 1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v11, v11, v13
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v19, 0x400000, v9
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v12, 0x7fff, v12
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v13, 0x7fff, v16
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v15, v15, v9
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v11, 0x7fff, v11
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v16, 0x400000, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v15, 0x7fff, v15
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v11, v11, v18, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v11, 16, v11
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v9, v15, v19, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v9, 16, v9
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v10, v12, v17, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v14, v14
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v10, 16, v10
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v12, v13, v16, vcc_lo
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v13, 0xffff, v4
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v4, v1, 16, v0
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v3, v2, 16, v3
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v1, v10, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v12, 16, v12
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v2, v8, 16, v13
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v0, v12, 16, v9
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB23_3:
; GFX11-FAKE16-NEXT:    s_branch .LBB23_2
; GFX11-FAKE16-NEXT:  .LBB23_4:
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x bfloat> %a, splat (bfloat 0xR40C0)
  %a2 = bitcast <16 x bfloat> %a1 to <8 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <16 x bfloat> %a to <8 x i32>
  br label %end

end:
  %phi = phi <8 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x i32> %phi
}

define <32 x i8> @bitcast_v8i32_to_v32i8(<8 x i32> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v8i32_to_v32i8:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_mov_b32_e32 v28, v7
; SI-NEXT:    v_mov_b32_e32 v24, v6
; SI-NEXT:    v_mov_b32_e32 v20, v5
; SI-NEXT:    v_mov_b32_e32 v16, v4
; SI-NEXT:    v_mov_b32_e32 v12, v3
; SI-NEXT:    v_mov_b32_e32 v32, v2
; SI-NEXT:    v_mov_b32_e32 v4, v1
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    ; implicit-def: $vgpr1
; SI-NEXT:    ; implicit-def: $vgpr2
; SI-NEXT:    ; implicit-def: $vgpr3
; SI-NEXT:    ; implicit-def: $vgpr5
; SI-NEXT:    ; implicit-def: $vgpr6
; SI-NEXT:    ; implicit-def: $vgpr7
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr25
; SI-NEXT:    ; implicit-def: $vgpr26
; SI-NEXT:    ; implicit-def: $vgpr27
; SI-NEXT:    ; implicit-def: $vgpr29
; SI-NEXT:    ; implicit-def: $vgpr30
; SI-NEXT:    ; implicit-def: $vgpr31
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB24_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_alignbit_b32 v27, v28, v24, 24
; SI-NEXT:    v_alignbit_b32 v26, v28, v24, 16
; SI-NEXT:    v_alignbit_b32 v25, v28, v24, 8
; SI-NEXT:    v_alignbit_b32 v19, v20, v16, 24
; SI-NEXT:    v_alignbit_b32 v18, v20, v16, 16
; SI-NEXT:    v_alignbit_b32 v17, v20, v16, 8
; SI-NEXT:    v_alignbit_b32 v11, v12, v32, 24
; SI-NEXT:    v_alignbit_b32 v10, v12, v32, 16
; SI-NEXT:    v_alignbit_b32 v9, v12, v32, 8
; SI-NEXT:    v_alignbit_b32 v3, v4, v0, 24
; SI-NEXT:    v_alignbit_b32 v2, v4, v0, 16
; SI-NEXT:    v_alignbit_b32 v1, v4, v0, 8
; SI-NEXT:    v_lshrrev_b32_e32 v31, 24, v28
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v28
; SI-NEXT:    v_lshrrev_b32_e32 v29, 8, v28
; SI-NEXT:    v_lshrrev_b32_e32 v23, 24, v20
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v20
; SI-NEXT:    v_lshrrev_b32_e32 v21, 8, v20
; SI-NEXT:    v_lshrrev_b32_e32 v15, 24, v12
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v12
; SI-NEXT:    v_lshrrev_b32_e32 v13, 8, v12
; SI-NEXT:    v_lshrrev_b32_e32 v7, 24, v4
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v4
; SI-NEXT:    v_lshrrev_b32_e32 v5, 8, v4
; SI-NEXT:  .LBB24_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB24_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:    v_add_i32_e32 v12, vcc, 3, v12
; SI-NEXT:    v_add_i32_e32 v32, vcc, 3, v32
; SI-NEXT:    v_add_i32_e32 v20, vcc, 3, v20
; SI-NEXT:    v_add_i32_e32 v16, vcc, 3, v16
; SI-NEXT:    v_add_i32_e32 v28, vcc, 3, v28
; SI-NEXT:    v_add_i32_e32 v24, vcc, 3, v24
; SI-NEXT:    v_alignbit_b32 v27, v28, v24, 24
; SI-NEXT:    v_alignbit_b32 v26, v28, v24, 16
; SI-NEXT:    v_alignbit_b32 v25, v28, v24, 8
; SI-NEXT:    v_alignbit_b32 v19, v20, v16, 24
; SI-NEXT:    v_alignbit_b32 v18, v20, v16, 16
; SI-NEXT:    v_alignbit_b32 v17, v20, v16, 8
; SI-NEXT:    v_alignbit_b32 v11, v12, v32, 24
; SI-NEXT:    v_alignbit_b32 v10, v12, v32, 16
; SI-NEXT:    v_alignbit_b32 v9, v12, v32, 8
; SI-NEXT:    v_alignbit_b32 v3, v4, v0, 24
; SI-NEXT:    v_alignbit_b32 v2, v4, v0, 16
; SI-NEXT:    v_alignbit_b32 v1, v4, v0, 8
; SI-NEXT:    v_lshrrev_b32_e32 v31, 24, v28
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v28
; SI-NEXT:    v_lshrrev_b32_e32 v29, 8, v28
; SI-NEXT:    v_lshrrev_b32_e32 v23, 24, v20
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v20
; SI-NEXT:    v_lshrrev_b32_e32 v21, 8, v20
; SI-NEXT:    v_lshrrev_b32_e32 v15, 24, v12
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v12
; SI-NEXT:    v_lshrrev_b32_e32 v13, 8, v12
; SI-NEXT:    v_lshrrev_b32_e32 v7, 24, v4
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v4
; SI-NEXT:    v_lshrrev_b32_e32 v5, 8, v4
; SI-NEXT:  .LBB24_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_mov_b32_e32 v8, v32
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v8i32_to_v32i8:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_mov_b32_e32 v33, v5
; VI-NEXT:    v_mov_b32_e32 v32, v4
; VI-NEXT:    v_mov_b32_e32 v35, v3
; VI-NEXT:    v_mov_b32_e32 v34, v2
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr2
; VI-NEXT:    ; implicit-def: $vgpr5
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr9
; VI-NEXT:    ; implicit-def: $vgpr10
; VI-NEXT:    ; implicit-def: $vgpr13
; VI-NEXT:    ; implicit-def: $vgpr14
; VI-NEXT:    ; implicit-def: $vgpr15
; VI-NEXT:    ; implicit-def: $vgpr17
; VI-NEXT:    ; implicit-def: $vgpr18
; VI-NEXT:    ; implicit-def: $vgpr21
; VI-NEXT:    ; implicit-def: $vgpr22
; VI-NEXT:    ; implicit-def: $vgpr23
; VI-NEXT:    ; implicit-def: $vgpr25
; VI-NEXT:    ; implicit-def: $vgpr26
; VI-NEXT:    ; implicit-def: $vgpr29
; VI-NEXT:    ; implicit-def: $vgpr30
; VI-NEXT:    ; implicit-def: $vgpr31
; VI-NEXT:    ; implicit-def: $vgpr3
; VI-NEXT:    ; implicit-def: $vgpr11
; VI-NEXT:    ; implicit-def: $vgpr19
; VI-NEXT:    ; implicit-def: $vgpr27
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB24_2
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v25, 8, v6
; VI-NEXT:    v_lshrrev_b32_e32 v23, 24, v33
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v33
; VI-NEXT:    v_lshrrev_b32_e32 v21, 8, v33
; VI-NEXT:    v_lshrrev_b32_e32 v18, 16, v32
; VI-NEXT:    v_lshrrev_b32_e32 v17, 8, v32
; VI-NEXT:    v_lshrrev_b32_e32 v15, 24, v35
; VI-NEXT:    v_lshrrev_b32_e32 v14, 16, v35
; VI-NEXT:    v_lshrrev_b32_e32 v13, 8, v35
; VI-NEXT:    v_lshrrev_b32_e32 v10, 16, v34
; VI-NEXT:    v_lshrrev_b32_e32 v9, 8, v34
; VI-NEXT:    v_lshrrev_b32_e32 v36, 24, v1
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; VI-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; VI-NEXT:    v_lshrrev_b32_e32 v38, 8, v0
; VI-NEXT:    v_lshrrev_b64 v[27:28], 24, v[6:7]
; VI-NEXT:    v_lshrrev_b64 v[19:20], 24, v[32:33]
; VI-NEXT:    v_lshrrev_b64 v[11:12], 24, v[34:35]
; VI-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; VI-NEXT:  .LBB24_2: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB24_4
; VI-NEXT:  ; %bb.3: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v1, vcc, 3, v1
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:    v_add_u32_e32 v35, vcc, 3, v35
; VI-NEXT:    v_add_u32_e32 v34, vcc, 3, v34
; VI-NEXT:    v_add_u32_e32 v33, vcc, 3, v33
; VI-NEXT:    v_add_u32_e32 v32, vcc, 3, v32
; VI-NEXT:    v_add_u32_e32 v7, vcc, 3, v7
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_lshrrev_b64 v[27:28], 24, v[6:7]
; VI-NEXT:    v_lshrrev_b64 v[19:20], 24, v[32:33]
; VI-NEXT:    v_lshrrev_b64 v[11:12], 24, v[34:35]
; VI-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; VI-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v25, 8, v6
; VI-NEXT:    v_lshrrev_b32_e32 v23, 24, v33
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v33
; VI-NEXT:    v_lshrrev_b32_e32 v21, 8, v33
; VI-NEXT:    v_lshrrev_b32_e32 v18, 16, v32
; VI-NEXT:    v_lshrrev_b32_e32 v17, 8, v32
; VI-NEXT:    v_lshrrev_b32_e32 v15, 24, v35
; VI-NEXT:    v_lshrrev_b32_e32 v14, 16, v35
; VI-NEXT:    v_lshrrev_b32_e32 v13, 8, v35
; VI-NEXT:    v_lshrrev_b32_e32 v10, 16, v34
; VI-NEXT:    v_lshrrev_b32_e32 v9, 8, v34
; VI-NEXT:    v_lshrrev_b32_e32 v36, 24, v1
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; VI-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; VI-NEXT:    v_lshrrev_b32_e32 v38, 8, v0
; VI-NEXT:  .LBB24_4: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    v_mov_b32_e32 v4, v1
; VI-NEXT:    v_mov_b32_e32 v8, v34
; VI-NEXT:    v_mov_b32_e32 v12, v35
; VI-NEXT:    v_mov_b32_e32 v16, v32
; VI-NEXT:    v_mov_b32_e32 v20, v33
; VI-NEXT:    v_mov_b32_e32 v24, v6
; VI-NEXT:    v_mov_b32_e32 v28, v7
; VI-NEXT:    v_mov_b32_e32 v1, v38
; VI-NEXT:    v_mov_b32_e32 v6, v37
; VI-NEXT:    v_mov_b32_e32 v7, v36
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v8i32_to_v32i8:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_mov_b32_e32 v33, v5
; GFX9-NEXT:    v_mov_b32_e32 v32, v4
; GFX9-NEXT:    v_mov_b32_e32 v35, v3
; GFX9-NEXT:    v_mov_b32_e32 v34, v2
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr2
; GFX9-NEXT:    ; implicit-def: $vgpr5
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr9
; GFX9-NEXT:    ; implicit-def: $vgpr10
; GFX9-NEXT:    ; implicit-def: $vgpr13
; GFX9-NEXT:    ; implicit-def: $vgpr14
; GFX9-NEXT:    ; implicit-def: $vgpr15
; GFX9-NEXT:    ; implicit-def: $vgpr17
; GFX9-NEXT:    ; implicit-def: $vgpr18
; GFX9-NEXT:    ; implicit-def: $vgpr21
; GFX9-NEXT:    ; implicit-def: $vgpr22
; GFX9-NEXT:    ; implicit-def: $vgpr23
; GFX9-NEXT:    ; implicit-def: $vgpr25
; GFX9-NEXT:    ; implicit-def: $vgpr26
; GFX9-NEXT:    ; implicit-def: $vgpr29
; GFX9-NEXT:    ; implicit-def: $vgpr30
; GFX9-NEXT:    ; implicit-def: $vgpr31
; GFX9-NEXT:    ; implicit-def: $vgpr3
; GFX9-NEXT:    ; implicit-def: $vgpr11
; GFX9-NEXT:    ; implicit-def: $vgpr19
; GFX9-NEXT:    ; implicit-def: $vgpr27
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB24_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 8, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 24, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 8, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v18, 16, v32
; GFX9-NEXT:    v_lshrrev_b32_e32 v17, 8, v32
; GFX9-NEXT:    v_lshrrev_b32_e32 v15, 24, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v14, 16, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v13, 8, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v10, 16, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v9, 8, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 24, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 8, v0
; GFX9-NEXT:    v_lshrrev_b64 v[27:28], 24, v[6:7]
; GFX9-NEXT:    v_lshrrev_b64 v[19:20], 24, v[32:33]
; GFX9-NEXT:    v_lshrrev_b64 v[11:12], 24, v[34:35]
; GFX9-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; GFX9-NEXT:  .LBB24_2: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB24_4
; GFX9-NEXT:  ; %bb.3: ; %cmp.true
; GFX9-NEXT:    v_add_u32_e32 v1, 3, v1
; GFX9-NEXT:    v_add_u32_e32 v0, 3, v0
; GFX9-NEXT:    v_add_u32_e32 v35, 3, v35
; GFX9-NEXT:    v_add_u32_e32 v34, 3, v34
; GFX9-NEXT:    v_add_u32_e32 v33, 3, v33
; GFX9-NEXT:    v_add_u32_e32 v32, 3, v32
; GFX9-NEXT:    v_add_u32_e32 v7, 3, v7
; GFX9-NEXT:    v_add_u32_e32 v6, 3, v6
; GFX9-NEXT:    v_lshrrev_b64 v[27:28], 24, v[6:7]
; GFX9-NEXT:    v_lshrrev_b64 v[19:20], 24, v[32:33]
; GFX9-NEXT:    v_lshrrev_b64 v[11:12], 24, v[34:35]
; GFX9-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 8, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 24, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 8, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v18, 16, v32
; GFX9-NEXT:    v_lshrrev_b32_e32 v17, 8, v32
; GFX9-NEXT:    v_lshrrev_b32_e32 v15, 24, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v14, 16, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v13, 8, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v10, 16, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v9, 8, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 24, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 8, v0
; GFX9-NEXT:  .LBB24_4: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    v_mov_b32_e32 v4, v1
; GFX9-NEXT:    v_mov_b32_e32 v8, v34
; GFX9-NEXT:    v_mov_b32_e32 v12, v35
; GFX9-NEXT:    v_mov_b32_e32 v16, v32
; GFX9-NEXT:    v_mov_b32_e32 v20, v33
; GFX9-NEXT:    v_mov_b32_e32 v24, v6
; GFX9-NEXT:    v_mov_b32_e32 v28, v7
; GFX9-NEXT:    v_mov_b32_e32 v1, v38
; GFX9-NEXT:    v_mov_b32_e32 v6, v37
; GFX9-NEXT:    v_mov_b32_e32 v7, v36
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v8i32_to_v32i8:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v33, v7 :: v_dual_mov_b32 v32, v6
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v27, v5 :: v_dual_mov_b32 v26, v4
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v19, v3 :: v_dual_mov_b32 v18, v2
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v11, v1 :: v_dual_mov_b32 v10, v0
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr1_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr3_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr5_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr7_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr36_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr15_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr17_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr35_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr21_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr23_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr25_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr34_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr29_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr31_lo16
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB24_2
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[34:35], 24, v[32:33]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[35:36], 24, v[26:27]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v27
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v27
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v26
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v18
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[36:37], 24, v[18:19]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[10:11]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v10
; GFX11-TRUE16-NEXT:  .LBB24_2: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB24_4
; GFX11-TRUE16-NEXT:  ; %bb.3: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v33, 3, v33
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v32, 3, v32
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v27, 3, v27
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v26, 3, v26
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v11, 3, v11
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v19, 3, v19
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v18, 3, v18
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v10, 3, v10
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[34:35], 24, v[32:33]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[35:36], 24, v[26:27]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[36:37], 24, v[18:19]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[10:11]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v27
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v27
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v26
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v18
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v10
; GFX11-TRUE16-NEXT:  .LBB24_4: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.l, v10.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.l, v10.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v4.l, v11.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v6.l, v11.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v8.l, v18.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v10.l, v18.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v11.l, v36.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v12.l, v19.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v14.l, v19.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v16.l, v26.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v18.l, v26.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v19.l, v35.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v20.l, v27.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v22.l, v27.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v24.l, v32.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v26.l, v32.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v27.l, v34.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v28.l, v33.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v30.l, v33.h
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v8i32_to_v32i8:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v33, v7 :: v_dual_mov_b32 v32, v6
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v35, v5 :: v_dual_mov_b32 v34, v4
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v37, v3 :: v_dual_mov_b32 v36, v2
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v39, v1 :: v_dual_mov_b32 v38, v0
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v8
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr1
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr2
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr3
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr5
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr6
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr7
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr9
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr10
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr11
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr13
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr14
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr15
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr17
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr18
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr19
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr21
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr22
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr23
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr25
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr26
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr27
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr29
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr30
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr31
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB24_2
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v32
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v18, 16, v34
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v34
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v14, 16, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v10, 16, v36
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v36
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v6, 16, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v38
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[27:28], 24, v[32:33]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[19:20], 24, v[34:35]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[11:12], 24, v[36:37]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[38:39]
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v38
; GFX11-FAKE16-NEXT:  .LBB24_2: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB24_4
; GFX11-FAKE16-NEXT:  ; %bb.3: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v39, 3, v39
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v37, 3, v37
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v35, 3, v35
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v33, 3, v33
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v32, 3, v32
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v34, 3, v34
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v36, 3, v36
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v38, 3, v38
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[27:28], 24, v[32:33]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[19:20], 24, v[34:35]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[11:12], 24, v[36:37]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[38:39]
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v32
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v18, 16, v34
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v34
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v14, 16, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v10, 16, v36
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v36
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v6, 16, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v38
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v38
; GFX11-FAKE16-NEXT:  .LBB24_4: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v0, v38
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v4, v39
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v8, v36
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v12, v37
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v16, v34
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v20, v35
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v24, v32
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v28, v33
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <8 x i32> %a, splat (i32 3)
  %a2 = bitcast <8 x i32> %a1 to <32 x i8>
  br label %end

cmp.false:
  %a3 = bitcast <8 x i32> %a to <32 x i8>
  br label %end

end:
  %phi = phi <32 x i8> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x i8> %phi
}

define inreg <32 x i8> @bitcast_v8i32_to_v32i8_scalar(<8 x i32> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v8i32_to_v32i8_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB25_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_lshr_b32 s56, s23, 24
; SI-NEXT:    s_lshr_b32 s57, s23, 16
; SI-NEXT:    s_lshr_b32 s58, s23, 8
; SI-NEXT:    s_lshr_b32 s59, s21, 24
; SI-NEXT:    s_lshr_b32 s60, s21, 16
; SI-NEXT:    s_lshr_b32 s61, s21, 8
; SI-NEXT:    s_lshr_b32 s62, s19, 24
; SI-NEXT:    s_lshr_b32 s63, s19, 16
; SI-NEXT:    s_lshr_b32 s72, s19, 8
; SI-NEXT:    s_lshr_b32 s73, s17, 24
; SI-NEXT:    s_lshr_b32 s74, s17, 16
; SI-NEXT:    s_lshr_b32 s75, s17, 8
; SI-NEXT:    s_lshr_b64 s[4:5], s[22:23], 24
; SI-NEXT:    s_lshr_b64 s[6:7], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[8:9], s[22:23], 8
; SI-NEXT:    s_lshr_b64 s[10:11], s[20:21], 24
; SI-NEXT:    s_lshr_b64 s[12:13], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[14:15], s[20:21], 8
; SI-NEXT:    s_lshr_b64 s[24:25], s[18:19], 24
; SI-NEXT:    s_lshr_b64 s[26:27], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[28:29], s[18:19], 8
; SI-NEXT:    s_lshr_b64 s[40:41], s[16:17], 24
; SI-NEXT:    s_lshr_b64 s[42:43], s[16:17], 16
; SI-NEXT:    s_lshr_b64 s[44:45], s[16:17], 8
; SI-NEXT:    s_cbranch_execnz .LBB25_3
; SI-NEXT:  .LBB25_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s17, s17, 3
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    s_add_i32 s19, s19, 3
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_add_i32 s21, s21, 3
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_add_i32 s23, s23, 3
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_lshr_b64 s[4:5], s[22:23], 24
; SI-NEXT:    s_lshr_b64 s[6:7], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[8:9], s[22:23], 8
; SI-NEXT:    s_lshr_b64 s[10:11], s[20:21], 24
; SI-NEXT:    s_lshr_b64 s[12:13], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[14:15], s[20:21], 8
; SI-NEXT:    s_lshr_b64 s[24:25], s[18:19], 24
; SI-NEXT:    s_lshr_b64 s[26:27], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[28:29], s[18:19], 8
; SI-NEXT:    s_lshr_b64 s[40:41], s[16:17], 24
; SI-NEXT:    s_lshr_b64 s[42:43], s[16:17], 16
; SI-NEXT:    s_lshr_b64 s[44:45], s[16:17], 8
; SI-NEXT:    s_lshr_b32 s56, s23, 24
; SI-NEXT:    s_lshr_b32 s57, s23, 16
; SI-NEXT:    s_lshr_b32 s58, s23, 8
; SI-NEXT:    s_lshr_b32 s59, s21, 24
; SI-NEXT:    s_lshr_b32 s60, s21, 16
; SI-NEXT:    s_lshr_b32 s61, s21, 8
; SI-NEXT:    s_lshr_b32 s62, s19, 24
; SI-NEXT:    s_lshr_b32 s63, s19, 16
; SI-NEXT:    s_lshr_b32 s72, s19, 8
; SI-NEXT:    s_lshr_b32 s73, s17, 24
; SI-NEXT:    s_lshr_b32 s74, s17, 16
; SI-NEXT:    s_lshr_b32 s75, s17, 8
; SI-NEXT:  .LBB25_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v1, s44
; SI-NEXT:    v_mov_b32_e32 v2, s42
; SI-NEXT:    v_mov_b32_e32 v3, s40
; SI-NEXT:    v_mov_b32_e32 v4, s17
; SI-NEXT:    v_mov_b32_e32 v5, s75
; SI-NEXT:    v_mov_b32_e32 v6, s74
; SI-NEXT:    v_mov_b32_e32 v7, s73
; SI-NEXT:    v_mov_b32_e32 v8, s18
; SI-NEXT:    v_mov_b32_e32 v9, s28
; SI-NEXT:    v_mov_b32_e32 v10, s26
; SI-NEXT:    v_mov_b32_e32 v11, s24
; SI-NEXT:    v_mov_b32_e32 v12, s19
; SI-NEXT:    v_mov_b32_e32 v13, s72
; SI-NEXT:    v_mov_b32_e32 v14, s63
; SI-NEXT:    v_mov_b32_e32 v15, s62
; SI-NEXT:    v_mov_b32_e32 v16, s20
; SI-NEXT:    v_mov_b32_e32 v17, s14
; SI-NEXT:    v_mov_b32_e32 v18, s12
; SI-NEXT:    v_mov_b32_e32 v19, s10
; SI-NEXT:    v_mov_b32_e32 v20, s21
; SI-NEXT:    v_mov_b32_e32 v21, s61
; SI-NEXT:    v_mov_b32_e32 v22, s60
; SI-NEXT:    v_mov_b32_e32 v23, s59
; SI-NEXT:    v_mov_b32_e32 v24, s22
; SI-NEXT:    v_mov_b32_e32 v25, s8
; SI-NEXT:    v_mov_b32_e32 v26, s6
; SI-NEXT:    v_mov_b32_e32 v27, s4
; SI-NEXT:    v_mov_b32_e32 v28, s23
; SI-NEXT:    v_mov_b32_e32 v29, s58
; SI-NEXT:    v_mov_b32_e32 v30, s57
; SI-NEXT:    v_mov_b32_e32 v31, s56
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB25_4:
; SI-NEXT:    ; implicit-def: $sgpr44
; SI-NEXT:    ; implicit-def: $sgpr42
; SI-NEXT:    ; implicit-def: $sgpr40
; SI-NEXT:    ; implicit-def: $sgpr75
; SI-NEXT:    ; implicit-def: $sgpr74
; SI-NEXT:    ; implicit-def: $sgpr73
; SI-NEXT:    ; implicit-def: $sgpr28
; SI-NEXT:    ; implicit-def: $sgpr26
; SI-NEXT:    ; implicit-def: $sgpr24
; SI-NEXT:    ; implicit-def: $sgpr72
; SI-NEXT:    ; implicit-def: $sgpr63
; SI-NEXT:    ; implicit-def: $sgpr62
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr12
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr61
; SI-NEXT:    ; implicit-def: $sgpr60
; SI-NEXT:    ; implicit-def: $sgpr59
; SI-NEXT:    ; implicit-def: $sgpr8
; SI-NEXT:    ; implicit-def: $sgpr6
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr58
; SI-NEXT:    ; implicit-def: $sgpr57
; SI-NEXT:    ; implicit-def: $sgpr56
; SI-NEXT:    s_branch .LBB25_2
;
; VI-LABEL: bitcast_v8i32_to_v32i8_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB25_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_lshr_b32 s14, s23, 24
; VI-NEXT:    s_lshr_b32 s15, s23, 16
; VI-NEXT:    s_lshr_b32 s24, s23, 8
; VI-NEXT:    s_lshr_b32 s25, s22, 16
; VI-NEXT:    s_lshr_b32 s26, s22, 8
; VI-NEXT:    s_lshr_b32 s27, s21, 24
; VI-NEXT:    s_lshr_b32 s28, s21, 16
; VI-NEXT:    s_lshr_b32 s29, s21, 8
; VI-NEXT:    s_lshr_b32 s40, s20, 16
; VI-NEXT:    s_lshr_b32 s41, s20, 8
; VI-NEXT:    s_lshr_b32 s42, s19, 24
; VI-NEXT:    s_lshr_b32 s43, s19, 16
; VI-NEXT:    s_lshr_b32 s44, s19, 8
; VI-NEXT:    s_lshr_b32 s45, s18, 16
; VI-NEXT:    s_lshr_b32 s46, s18, 8
; VI-NEXT:    s_lshr_b32 s47, s17, 24
; VI-NEXT:    s_lshr_b32 s56, s17, 16
; VI-NEXT:    s_lshr_b32 s57, s17, 8
; VI-NEXT:    s_lshr_b32 s58, s16, 16
; VI-NEXT:    s_lshr_b32 s59, s16, 8
; VI-NEXT:    s_lshr_b64 s[4:5], s[22:23], 24
; VI-NEXT:    s_lshr_b64 s[6:7], s[20:21], 24
; VI-NEXT:    s_lshr_b64 s[8:9], s[18:19], 24
; VI-NEXT:    s_lshr_b64 s[10:11], s[16:17], 24
; VI-NEXT:    s_cbranch_execnz .LBB25_3
; VI-NEXT:  .LBB25_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s17, s17, 3
; VI-NEXT:    s_add_i32 s16, s16, 3
; VI-NEXT:    s_add_i32 s19, s19, 3
; VI-NEXT:    s_add_i32 s18, s18, 3
; VI-NEXT:    s_add_i32 s21, s21, 3
; VI-NEXT:    s_add_i32 s20, s20, 3
; VI-NEXT:    s_add_i32 s23, s23, 3
; VI-NEXT:    s_add_i32 s22, s22, 3
; VI-NEXT:    s_lshr_b64 s[4:5], s[22:23], 24
; VI-NEXT:    s_lshr_b64 s[6:7], s[20:21], 24
; VI-NEXT:    s_lshr_b64 s[8:9], s[18:19], 24
; VI-NEXT:    s_lshr_b64 s[10:11], s[16:17], 24
; VI-NEXT:    s_lshr_b32 s14, s23, 24
; VI-NEXT:    s_lshr_b32 s15, s23, 16
; VI-NEXT:    s_lshr_b32 s24, s23, 8
; VI-NEXT:    s_lshr_b32 s25, s22, 16
; VI-NEXT:    s_lshr_b32 s26, s22, 8
; VI-NEXT:    s_lshr_b32 s27, s21, 24
; VI-NEXT:    s_lshr_b32 s28, s21, 16
; VI-NEXT:    s_lshr_b32 s29, s21, 8
; VI-NEXT:    s_lshr_b32 s40, s20, 16
; VI-NEXT:    s_lshr_b32 s41, s20, 8
; VI-NEXT:    s_lshr_b32 s42, s19, 24
; VI-NEXT:    s_lshr_b32 s43, s19, 16
; VI-NEXT:    s_lshr_b32 s44, s19, 8
; VI-NEXT:    s_lshr_b32 s45, s18, 16
; VI-NEXT:    s_lshr_b32 s46, s18, 8
; VI-NEXT:    s_lshr_b32 s47, s17, 24
; VI-NEXT:    s_lshr_b32 s56, s17, 16
; VI-NEXT:    s_lshr_b32 s57, s17, 8
; VI-NEXT:    s_lshr_b32 s58, s16, 16
; VI-NEXT:    s_lshr_b32 s59, s16, 8
; VI-NEXT:  .LBB25_3: ; %end
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s59
; VI-NEXT:    v_mov_b32_e32 v2, s58
; VI-NEXT:    v_mov_b32_e32 v3, s10
; VI-NEXT:    v_mov_b32_e32 v4, s17
; VI-NEXT:    v_mov_b32_e32 v5, s57
; VI-NEXT:    v_mov_b32_e32 v6, s56
; VI-NEXT:    v_mov_b32_e32 v7, s47
; VI-NEXT:    v_mov_b32_e32 v8, s18
; VI-NEXT:    v_mov_b32_e32 v9, s46
; VI-NEXT:    v_mov_b32_e32 v10, s45
; VI-NEXT:    v_mov_b32_e32 v11, s8
; VI-NEXT:    v_mov_b32_e32 v12, s19
; VI-NEXT:    v_mov_b32_e32 v13, s44
; VI-NEXT:    v_mov_b32_e32 v14, s43
; VI-NEXT:    v_mov_b32_e32 v15, s42
; VI-NEXT:    v_mov_b32_e32 v16, s20
; VI-NEXT:    v_mov_b32_e32 v17, s41
; VI-NEXT:    v_mov_b32_e32 v18, s40
; VI-NEXT:    v_mov_b32_e32 v19, s6
; VI-NEXT:    v_mov_b32_e32 v20, s21
; VI-NEXT:    v_mov_b32_e32 v21, s29
; VI-NEXT:    v_mov_b32_e32 v22, s28
; VI-NEXT:    v_mov_b32_e32 v23, s27
; VI-NEXT:    v_mov_b32_e32 v24, s22
; VI-NEXT:    v_mov_b32_e32 v25, s26
; VI-NEXT:    v_mov_b32_e32 v26, s25
; VI-NEXT:    v_mov_b32_e32 v27, s4
; VI-NEXT:    v_mov_b32_e32 v28, s23
; VI-NEXT:    v_mov_b32_e32 v29, s24
; VI-NEXT:    v_mov_b32_e32 v30, s15
; VI-NEXT:    v_mov_b32_e32 v31, s14
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB25_4:
; VI-NEXT:    ; implicit-def: $sgpr59
; VI-NEXT:    ; implicit-def: $sgpr58
; VI-NEXT:    ; implicit-def: $sgpr10
; VI-NEXT:    ; implicit-def: $sgpr57
; VI-NEXT:    ; implicit-def: $sgpr56
; VI-NEXT:    ; implicit-def: $sgpr47
; VI-NEXT:    ; implicit-def: $sgpr46
; VI-NEXT:    ; implicit-def: $sgpr45
; VI-NEXT:    ; implicit-def: $sgpr8
; VI-NEXT:    ; implicit-def: $sgpr44
; VI-NEXT:    ; implicit-def: $sgpr43
; VI-NEXT:    ; implicit-def: $sgpr42
; VI-NEXT:    ; implicit-def: $sgpr41
; VI-NEXT:    ; implicit-def: $sgpr40
; VI-NEXT:    ; implicit-def: $sgpr6
; VI-NEXT:    ; implicit-def: $sgpr29
; VI-NEXT:    ; implicit-def: $sgpr28
; VI-NEXT:    ; implicit-def: $sgpr27
; VI-NEXT:    ; implicit-def: $sgpr26
; VI-NEXT:    ; implicit-def: $sgpr25
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr24
; VI-NEXT:    ; implicit-def: $sgpr15
; VI-NEXT:    ; implicit-def: $sgpr14
; VI-NEXT:    s_branch .LBB25_2
;
; GFX9-LABEL: bitcast_v8i32_to_v32i8_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB25_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_lshr_b32 s14, s23, 24
; GFX9-NEXT:    s_lshr_b32 s15, s23, 16
; GFX9-NEXT:    s_lshr_b32 s24, s23, 8
; GFX9-NEXT:    s_lshr_b32 s25, s22, 16
; GFX9-NEXT:    s_lshr_b32 s26, s22, 8
; GFX9-NEXT:    s_lshr_b32 s27, s21, 24
; GFX9-NEXT:    s_lshr_b32 s28, s21, 16
; GFX9-NEXT:    s_lshr_b32 s29, s21, 8
; GFX9-NEXT:    s_lshr_b32 s40, s20, 16
; GFX9-NEXT:    s_lshr_b32 s41, s20, 8
; GFX9-NEXT:    s_lshr_b32 s42, s19, 24
; GFX9-NEXT:    s_lshr_b32 s43, s19, 16
; GFX9-NEXT:    s_lshr_b32 s44, s19, 8
; GFX9-NEXT:    s_lshr_b32 s45, s18, 16
; GFX9-NEXT:    s_lshr_b32 s46, s18, 8
; GFX9-NEXT:    s_lshr_b32 s47, s17, 24
; GFX9-NEXT:    s_lshr_b32 s56, s17, 16
; GFX9-NEXT:    s_lshr_b32 s57, s17, 8
; GFX9-NEXT:    s_lshr_b32 s58, s16, 16
; GFX9-NEXT:    s_lshr_b32 s59, s16, 8
; GFX9-NEXT:    s_lshr_b64 s[4:5], s[22:23], 24
; GFX9-NEXT:    s_lshr_b64 s[6:7], s[20:21], 24
; GFX9-NEXT:    s_lshr_b64 s[8:9], s[18:19], 24
; GFX9-NEXT:    s_lshr_b64 s[10:11], s[16:17], 24
; GFX9-NEXT:    s_cbranch_execnz .LBB25_3
; GFX9-NEXT:  .LBB25_2: ; %cmp.true
; GFX9-NEXT:    s_add_i32 s17, s17, 3
; GFX9-NEXT:    s_add_i32 s16, s16, 3
; GFX9-NEXT:    s_add_i32 s19, s19, 3
; GFX9-NEXT:    s_add_i32 s18, s18, 3
; GFX9-NEXT:    s_add_i32 s21, s21, 3
; GFX9-NEXT:    s_add_i32 s20, s20, 3
; GFX9-NEXT:    s_add_i32 s23, s23, 3
; GFX9-NEXT:    s_add_i32 s22, s22, 3
; GFX9-NEXT:    s_lshr_b64 s[4:5], s[22:23], 24
; GFX9-NEXT:    s_lshr_b64 s[6:7], s[20:21], 24
; GFX9-NEXT:    s_lshr_b64 s[8:9], s[18:19], 24
; GFX9-NEXT:    s_lshr_b64 s[10:11], s[16:17], 24
; GFX9-NEXT:    s_lshr_b32 s14, s23, 24
; GFX9-NEXT:    s_lshr_b32 s15, s23, 16
; GFX9-NEXT:    s_lshr_b32 s24, s23, 8
; GFX9-NEXT:    s_lshr_b32 s25, s22, 16
; GFX9-NEXT:    s_lshr_b32 s26, s22, 8
; GFX9-NEXT:    s_lshr_b32 s27, s21, 24
; GFX9-NEXT:    s_lshr_b32 s28, s21, 16
; GFX9-NEXT:    s_lshr_b32 s29, s21, 8
; GFX9-NEXT:    s_lshr_b32 s40, s20, 16
; GFX9-NEXT:    s_lshr_b32 s41, s20, 8
; GFX9-NEXT:    s_lshr_b32 s42, s19, 24
; GFX9-NEXT:    s_lshr_b32 s43, s19, 16
; GFX9-NEXT:    s_lshr_b32 s44, s19, 8
; GFX9-NEXT:    s_lshr_b32 s45, s18, 16
; GFX9-NEXT:    s_lshr_b32 s46, s18, 8
; GFX9-NEXT:    s_lshr_b32 s47, s17, 24
; GFX9-NEXT:    s_lshr_b32 s56, s17, 16
; GFX9-NEXT:    s_lshr_b32 s57, s17, 8
; GFX9-NEXT:    s_lshr_b32 s58, s16, 16
; GFX9-NEXT:    s_lshr_b32 s59, s16, 8
; GFX9-NEXT:  .LBB25_3: ; %end
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s59
; GFX9-NEXT:    v_mov_b32_e32 v2, s58
; GFX9-NEXT:    v_mov_b32_e32 v3, s10
; GFX9-NEXT:    v_mov_b32_e32 v4, s17
; GFX9-NEXT:    v_mov_b32_e32 v5, s57
; GFX9-NEXT:    v_mov_b32_e32 v6, s56
; GFX9-NEXT:    v_mov_b32_e32 v7, s47
; GFX9-NEXT:    v_mov_b32_e32 v8, s18
; GFX9-NEXT:    v_mov_b32_e32 v9, s46
; GFX9-NEXT:    v_mov_b32_e32 v10, s45
; GFX9-NEXT:    v_mov_b32_e32 v11, s8
; GFX9-NEXT:    v_mov_b32_e32 v12, s19
; GFX9-NEXT:    v_mov_b32_e32 v13, s44
; GFX9-NEXT:    v_mov_b32_e32 v14, s43
; GFX9-NEXT:    v_mov_b32_e32 v15, s42
; GFX9-NEXT:    v_mov_b32_e32 v16, s20
; GFX9-NEXT:    v_mov_b32_e32 v17, s41
; GFX9-NEXT:    v_mov_b32_e32 v18, s40
; GFX9-NEXT:    v_mov_b32_e32 v19, s6
; GFX9-NEXT:    v_mov_b32_e32 v20, s21
; GFX9-NEXT:    v_mov_b32_e32 v21, s29
; GFX9-NEXT:    v_mov_b32_e32 v22, s28
; GFX9-NEXT:    v_mov_b32_e32 v23, s27
; GFX9-NEXT:    v_mov_b32_e32 v24, s22
; GFX9-NEXT:    v_mov_b32_e32 v25, s26
; GFX9-NEXT:    v_mov_b32_e32 v26, s25
; GFX9-NEXT:    v_mov_b32_e32 v27, s4
; GFX9-NEXT:    v_mov_b32_e32 v28, s23
; GFX9-NEXT:    v_mov_b32_e32 v29, s24
; GFX9-NEXT:    v_mov_b32_e32 v30, s15
; GFX9-NEXT:    v_mov_b32_e32 v31, s14
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB25_4:
; GFX9-NEXT:    ; implicit-def: $sgpr59
; GFX9-NEXT:    ; implicit-def: $sgpr58
; GFX9-NEXT:    ; implicit-def: $sgpr10
; GFX9-NEXT:    ; implicit-def: $sgpr57
; GFX9-NEXT:    ; implicit-def: $sgpr56
; GFX9-NEXT:    ; implicit-def: $sgpr47
; GFX9-NEXT:    ; implicit-def: $sgpr46
; GFX9-NEXT:    ; implicit-def: $sgpr45
; GFX9-NEXT:    ; implicit-def: $sgpr8
; GFX9-NEXT:    ; implicit-def: $sgpr44
; GFX9-NEXT:    ; implicit-def: $sgpr43
; GFX9-NEXT:    ; implicit-def: $sgpr42
; GFX9-NEXT:    ; implicit-def: $sgpr41
; GFX9-NEXT:    ; implicit-def: $sgpr40
; GFX9-NEXT:    ; implicit-def: $sgpr6
; GFX9-NEXT:    ; implicit-def: $sgpr29
; GFX9-NEXT:    ; implicit-def: $sgpr28
; GFX9-NEXT:    ; implicit-def: $sgpr27
; GFX9-NEXT:    ; implicit-def: $sgpr26
; GFX9-NEXT:    ; implicit-def: $sgpr25
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr24
; GFX9-NEXT:    ; implicit-def: $sgpr15
; GFX9-NEXT:    ; implicit-def: $sgpr14
; GFX9-NEXT:    s_branch .LBB25_2
;
; GFX11-LABEL: bitcast_v8i32_to_v32i8_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s46, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB25_4
; GFX11-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-NEXT:    s_lshr_b32 s12, s19, 24
; GFX11-NEXT:    s_lshr_b32 s13, s19, 16
; GFX11-NEXT:    s_lshr_b32 s14, s19, 8
; GFX11-NEXT:    s_lshr_b32 s15, s18, 16
; GFX11-NEXT:    s_lshr_b32 s20, s18, 8
; GFX11-NEXT:    s_lshr_b32 s21, s17, 24
; GFX11-NEXT:    s_lshr_b32 s22, s17, 16
; GFX11-NEXT:    s_lshr_b32 s23, s17, 8
; GFX11-NEXT:    s_lshr_b32 s24, s16, 16
; GFX11-NEXT:    s_lshr_b32 s25, s16, 8
; GFX11-NEXT:    s_lshr_b32 s26, s3, 24
; GFX11-NEXT:    s_lshr_b32 s27, s3, 16
; GFX11-NEXT:    s_lshr_b32 s28, s3, 8
; GFX11-NEXT:    s_lshr_b32 s29, s2, 16
; GFX11-NEXT:    s_lshr_b32 s40, s2, 8
; GFX11-NEXT:    s_lshr_b32 s41, s1, 24
; GFX11-NEXT:    s_lshr_b32 s42, s1, 16
; GFX11-NEXT:    s_lshr_b32 s43, s1, 8
; GFX11-NEXT:    s_lshr_b32 s44, s0, 16
; GFX11-NEXT:    s_lshr_b32 s45, s0, 8
; GFX11-NEXT:    s_lshr_b64 s[4:5], s[18:19], 24
; GFX11-NEXT:    s_lshr_b64 s[6:7], s[16:17], 24
; GFX11-NEXT:    s_lshr_b64 s[8:9], s[2:3], 24
; GFX11-NEXT:    s_lshr_b64 s[10:11], s[0:1], 24
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s46
; GFX11-NEXT:    s_cbranch_vccnz .LBB25_3
; GFX11-NEXT:  .LBB25_2: ; %cmp.true
; GFX11-NEXT:    s_add_i32 s1, s1, 3
; GFX11-NEXT:    s_add_i32 s0, s0, 3
; GFX11-NEXT:    s_add_i32 s3, s3, 3
; GFX11-NEXT:    s_add_i32 s2, s2, 3
; GFX11-NEXT:    s_add_i32 s17, s17, 3
; GFX11-NEXT:    s_add_i32 s19, s19, 3
; GFX11-NEXT:    s_add_i32 s18, s18, 3
; GFX11-NEXT:    s_add_i32 s16, s16, 3
; GFX11-NEXT:    s_lshr_b64 s[4:5], s[18:19], 24
; GFX11-NEXT:    s_lshr_b64 s[6:7], s[16:17], 24
; GFX11-NEXT:    s_lshr_b64 s[8:9], s[2:3], 24
; GFX11-NEXT:    s_lshr_b64 s[10:11], s[0:1], 24
; GFX11-NEXT:    s_lshr_b32 s12, s19, 24
; GFX11-NEXT:    s_lshr_b32 s13, s19, 16
; GFX11-NEXT:    s_lshr_b32 s14, s19, 8
; GFX11-NEXT:    s_lshr_b32 s15, s18, 16
; GFX11-NEXT:    s_lshr_b32 s20, s18, 8
; GFX11-NEXT:    s_lshr_b32 s21, s17, 24
; GFX11-NEXT:    s_lshr_b32 s22, s17, 16
; GFX11-NEXT:    s_lshr_b32 s23, s17, 8
; GFX11-NEXT:    s_lshr_b32 s24, s16, 16
; GFX11-NEXT:    s_lshr_b32 s25, s16, 8
; GFX11-NEXT:    s_lshr_b32 s26, s3, 24
; GFX11-NEXT:    s_lshr_b32 s27, s3, 16
; GFX11-NEXT:    s_lshr_b32 s28, s3, 8
; GFX11-NEXT:    s_lshr_b32 s29, s2, 16
; GFX11-NEXT:    s_lshr_b32 s40, s2, 8
; GFX11-NEXT:    s_lshr_b32 s41, s1, 24
; GFX11-NEXT:    s_lshr_b32 s42, s1, 16
; GFX11-NEXT:    s_lshr_b32 s43, s1, 8
; GFX11-NEXT:    s_lshr_b32 s44, s0, 16
; GFX11-NEXT:    s_lshr_b32 s45, s0, 8
; GFX11-NEXT:  .LBB25_3: ; %end
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s45
; GFX11-NEXT:    v_dual_mov_b32 v2, s44 :: v_dual_mov_b32 v3, s10
; GFX11-NEXT:    v_dual_mov_b32 v4, s1 :: v_dual_mov_b32 v5, s43
; GFX11-NEXT:    v_dual_mov_b32 v6, s42 :: v_dual_mov_b32 v7, s41
; GFX11-NEXT:    v_dual_mov_b32 v8, s2 :: v_dual_mov_b32 v9, s40
; GFX11-NEXT:    v_dual_mov_b32 v10, s29 :: v_dual_mov_b32 v11, s8
; GFX11-NEXT:    v_dual_mov_b32 v12, s3 :: v_dual_mov_b32 v13, s28
; GFX11-NEXT:    v_dual_mov_b32 v14, s27 :: v_dual_mov_b32 v15, s26
; GFX11-NEXT:    v_dual_mov_b32 v16, s16 :: v_dual_mov_b32 v17, s25
; GFX11-NEXT:    v_dual_mov_b32 v18, s24 :: v_dual_mov_b32 v19, s6
; GFX11-NEXT:    v_dual_mov_b32 v20, s17 :: v_dual_mov_b32 v21, s23
; GFX11-NEXT:    v_dual_mov_b32 v22, s22 :: v_dual_mov_b32 v23, s21
; GFX11-NEXT:    v_dual_mov_b32 v24, s18 :: v_dual_mov_b32 v25, s20
; GFX11-NEXT:    v_dual_mov_b32 v26, s15 :: v_dual_mov_b32 v27, s4
; GFX11-NEXT:    v_dual_mov_b32 v28, s19 :: v_dual_mov_b32 v29, s14
; GFX11-NEXT:    v_dual_mov_b32 v30, s13 :: v_dual_mov_b32 v31, s12
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB25_4:
; GFX11-NEXT:    ; implicit-def: $sgpr45
; GFX11-NEXT:    ; implicit-def: $sgpr44
; GFX11-NEXT:    ; implicit-def: $sgpr10
; GFX11-NEXT:    ; implicit-def: $sgpr43
; GFX11-NEXT:    ; implicit-def: $sgpr42
; GFX11-NEXT:    ; implicit-def: $sgpr41
; GFX11-NEXT:    ; implicit-def: $sgpr40
; GFX11-NEXT:    ; implicit-def: $sgpr29
; GFX11-NEXT:    ; implicit-def: $sgpr8
; GFX11-NEXT:    ; implicit-def: $sgpr28
; GFX11-NEXT:    ; implicit-def: $sgpr27
; GFX11-NEXT:    ; implicit-def: $sgpr26
; GFX11-NEXT:    ; implicit-def: $sgpr25
; GFX11-NEXT:    ; implicit-def: $sgpr24
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr23
; GFX11-NEXT:    ; implicit-def: $sgpr22
; GFX11-NEXT:    ; implicit-def: $sgpr21
; GFX11-NEXT:    ; implicit-def: $sgpr20
; GFX11-NEXT:    ; implicit-def: $sgpr15
; GFX11-NEXT:    ; implicit-def: $sgpr4
; GFX11-NEXT:    ; implicit-def: $sgpr14
; GFX11-NEXT:    ; implicit-def: $sgpr13
; GFX11-NEXT:    ; implicit-def: $sgpr12
; GFX11-NEXT:    s_branch .LBB25_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <8 x i32> %a, splat (i32 3)
  %a2 = bitcast <8 x i32> %a1 to <32 x i8>
  br label %end

cmp.false:
  %a3 = bitcast <8 x i32> %a to <32 x i8>
  br label %end

end:
  %phi = phi <32 x i8> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x i8> %phi
}

define <8 x i32> @bitcast_v32i8_to_v8i32(<32 x i8> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v32i8_to_v8i32:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_mov_b32_e32 v32, v2
; SI-NEXT:    v_mov_b32_e32 v31, v0
; SI-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:4
; SI-NEXT:    buffer_load_dword v2, off, s[0:3], s32
; SI-NEXT:    v_mov_b32_e32 v34, v6
; SI-NEXT:    v_mov_b32_e32 v33, v4
; SI-NEXT:    v_lshlrev_b32_e32 v52, 8, v1
; SI-NEXT:    v_lshlrev_b32_e32 v51, 24, v3
; SI-NEXT:    v_lshlrev_b32_e32 v50, 8, v5
; SI-NEXT:    v_lshlrev_b32_e32 v49, 24, v7
; SI-NEXT:    v_lshlrev_b32_e32 v48, 8, v9
; SI-NEXT:    v_lshlrev_b32_e32 v39, 24, v11
; SI-NEXT:    v_lshlrev_b32_e32 v38, 8, v13
; SI-NEXT:    v_lshlrev_b32_e32 v37, 24, v15
; SI-NEXT:    v_lshlrev_b32_e32 v36, 8, v17
; SI-NEXT:    v_lshlrev_b32_e32 v35, 24, v19
; SI-NEXT:    v_lshlrev_b32_e32 v19, 8, v21
; SI-NEXT:    v_lshlrev_b32_e32 v17, 24, v23
; SI-NEXT:    v_lshlrev_b32_e32 v15, 8, v25
; SI-NEXT:    v_lshlrev_b32_e32 v13, 24, v27
; SI-NEXT:    v_lshlrev_b32_e32 v11, 8, v29
; SI-NEXT:    s_waitcnt vmcnt(1)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v0
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_lshlrev_b32_e32 v9, 24, v2
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB26_3
; SI-NEXT:  ; %bb.1: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB26_4
; SI-NEXT:  .LBB26_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB26_3: ; %cmp.false
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v31
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v32
; SI-NEXT:    v_or_b32_e32 v0, v0, v52
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_or_b32_e32 v1, v51, v1
; SI-NEXT:    v_or_b32_e32 v0, v0, v1
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v33
; SI-NEXT:    v_and_b32_e32 v2, 0xff, v34
; SI-NEXT:    v_or_b32_e32 v1, v1, v50
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_or_b32_e32 v2, v49, v2
; SI-NEXT:    v_or_b32_e32 v1, v1, v2
; SI-NEXT:    v_and_b32_e32 v2, 0xff, v8
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v10
; SI-NEXT:    v_or_b32_e32 v2, v2, v48
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_or_b32_e32 v3, v39, v3
; SI-NEXT:    v_or_b32_e32 v2, v2, v3
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v12
; SI-NEXT:    v_and_b32_e32 v4, 0xff, v14
; SI-NEXT:    v_or_b32_e32 v3, v3, v38
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_or_b32_e32 v4, v37, v4
; SI-NEXT:    v_or_b32_e32 v3, v3, v4
; SI-NEXT:    v_and_b32_e32 v4, 0xff, v16
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v18
; SI-NEXT:    v_or_b32_e32 v4, v4, v36
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_or_b32_e32 v5, v35, v5
; SI-NEXT:    v_or_b32_e32 v4, v4, v5
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v20
; SI-NEXT:    v_and_b32_e32 v6, 0xff, v22
; SI-NEXT:    v_or_b32_e32 v5, v5, v19
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_or_b32_e32 v6, v17, v6
; SI-NEXT:    v_or_b32_e32 v5, v5, v6
; SI-NEXT:    v_and_b32_e32 v6, 0xff, v24
; SI-NEXT:    v_and_b32_e32 v7, 0xff, v26
; SI-NEXT:    v_or_b32_e32 v6, v6, v15
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_or_b32_e32 v7, v13, v7
; SI-NEXT:    v_or_b32_e32 v6, v6, v7
; SI-NEXT:    v_and_b32_e32 v7, 0xff, v28
; SI-NEXT:    v_and_b32_e32 v8, 0xff, v30
; SI-NEXT:    v_or_b32_e32 v7, v7, v11
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_or_b32_e32 v8, v9, v8
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    ; implicit-def: $vgpr31
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr24
; SI-NEXT:    ; implicit-def: $vgpr26
; SI-NEXT:    ; implicit-def: $vgpr28
; SI-NEXT:    ; implicit-def: $vgpr30
; SI-NEXT:    ; implicit-def: $vgpr52
; SI-NEXT:    ; implicit-def: $vgpr51
; SI-NEXT:    ; implicit-def: $vgpr50
; SI-NEXT:    ; implicit-def: $vgpr49
; SI-NEXT:    ; implicit-def: $vgpr48
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB26_2
; SI-NEXT:  .LBB26_4: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v31
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v32
; SI-NEXT:    v_or_b32_e32 v0, v52, v0
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v1
; SI-NEXT:    v_add_i32_e32 v0, vcc, 0x300, v0
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_or_b32_e32 v1, v51, v1
; SI-NEXT:    v_or_b32_e32 v0, v1, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v33
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v1
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v34
; SI-NEXT:    s_movk_i32 s6, 0x300
; SI-NEXT:    v_or_b32_e32 v1, v50, v1
; SI-NEXT:    v_and_b32_e32 v2, 0xff, v2
; SI-NEXT:    v_add_i32_e32 v1, vcc, s6, v1
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_or_b32_e32 v2, v49, v2
; SI-NEXT:    v_or_b32_e32 v1, v2, v1
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v8
; SI-NEXT:    v_and_b32_e32 v2, 0xff, v2
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v10
; SI-NEXT:    v_or_b32_e32 v2, v48, v2
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v3
; SI-NEXT:    v_add_i32_e32 v2, vcc, s6, v2
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_or_b32_e32 v3, v39, v3
; SI-NEXT:    v_or_b32_e32 v2, v3, v2
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v12
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v3
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v14
; SI-NEXT:    v_or_b32_e32 v3, v38, v3
; SI-NEXT:    v_and_b32_e32 v4, 0xff, v4
; SI-NEXT:    v_add_i32_e32 v3, vcc, s6, v3
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_or_b32_e32 v4, v37, v4
; SI-NEXT:    v_or_b32_e32 v3, v4, v3
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v16
; SI-NEXT:    v_and_b32_e32 v4, 0xff, v4
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v18
; SI-NEXT:    v_or_b32_e32 v4, v36, v4
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v5
; SI-NEXT:    v_add_i32_e32 v4, vcc, s6, v4
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_or_b32_e32 v5, v35, v5
; SI-NEXT:    v_or_b32_e32 v4, v5, v4
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v20
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v5
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v22
; SI-NEXT:    v_or_b32_e32 v5, v19, v5
; SI-NEXT:    v_and_b32_e32 v6, 0xff, v6
; SI-NEXT:    v_add_i32_e32 v5, vcc, s6, v5
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_or_b32_e32 v6, v17, v6
; SI-NEXT:    v_or_b32_e32 v5, v6, v5
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v24
; SI-NEXT:    v_and_b32_e32 v6, 0xff, v6
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v26
; SI-NEXT:    v_or_b32_e32 v6, v15, v6
; SI-NEXT:    v_and_b32_e32 v7, 0xff, v7
; SI-NEXT:    v_add_i32_e32 v6, vcc, s6, v6
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_or_b32_e32 v7, v13, v7
; SI-NEXT:    v_or_b32_e32 v6, v7, v6
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v28
; SI-NEXT:    v_and_b32_e32 v7, 0xff, v7
; SI-NEXT:    v_add_i32_e32 v8, vcc, 3, v30
; SI-NEXT:    v_or_b32_e32 v7, v11, v7
; SI-NEXT:    v_and_b32_e32 v8, 0xff, v8
; SI-NEXT:    v_add_i32_e32 v7, vcc, 0x300, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_or_b32_e32 v8, v9, v8
; SI-NEXT:    s_mov_b32 s7, 0x3000000
; SI-NEXT:    v_or_b32_e32 v7, v8, v7
; SI-NEXT:    v_add_i32_e32 v0, vcc, s7, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, s7, v1
; SI-NEXT:    v_add_i32_e32 v2, vcc, s7, v2
; SI-NEXT:    v_add_i32_e32 v3, vcc, s7, v3
; SI-NEXT:    v_add_i32_e32 v4, vcc, s7, v4
; SI-NEXT:    v_add_i32_e32 v5, vcc, s7, v5
; SI-NEXT:    v_add_i32_e32 v6, vcc, 0x3000000, v6
; SI-NEXT:    v_add_i32_e32 v7, vcc, 0x3000000, v7
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v32i8_to_v8i32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_mov_b32_e32 v38, v0
; VI-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:4
; VI-NEXT:    buffer_load_ushort v39, off, s[0:3], s32
; VI-NEXT:    v_mov_b32_e32 v31, v7
; VI-NEXT:    v_mov_b32_e32 v32, v6
; VI-NEXT:    v_mov_b32_e32 v33, v5
; VI-NEXT:    v_mov_b32_e32 v34, v4
; VI-NEXT:    v_mov_b32_e32 v35, v3
; VI-NEXT:    v_mov_b32_e32 v36, v2
; VI-NEXT:    v_mov_b32_e32 v37, v1
; VI-NEXT:    s_waitcnt vmcnt(1)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v0
; VI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execnz .LBB26_3
; VI-NEXT:  ; %bb.1: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execnz .LBB26_4
; VI-NEXT:  .LBB26_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB26_3: ; %cmp.false
; VI-NEXT:    s_mov_b32 s6, 0xc0c0004
; VI-NEXT:    v_perm_b32 v1, v36, v35, s6
; VI-NEXT:    v_perm_b32 v0, v38, v37, s6
; VI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_perm_b32 v2, v32, v31, s6
; VI-NEXT:    v_or_b32_e32 v0, v0, v1
; VI-NEXT:    v_perm_b32 v1, v34, v33, s6
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_perm_b32 v3, v10, v11, s6
; VI-NEXT:    v_or_b32_e32 v1, v1, v2
; VI-NEXT:    v_perm_b32 v2, v8, v9, s6
; VI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_perm_b32 v4, v14, v15, s6
; VI-NEXT:    v_or_b32_e32 v2, v2, v3
; VI-NEXT:    v_perm_b32 v3, v12, v13, s6
; VI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_perm_b32 v5, v18, v19, s6
; VI-NEXT:    v_or_b32_e32 v3, v3, v4
; VI-NEXT:    v_perm_b32 v4, v16, v17, s6
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_perm_b32 v6, v22, v23, s6
; VI-NEXT:    v_or_b32_e32 v4, v4, v5
; VI-NEXT:    v_perm_b32 v5, v20, v21, s6
; VI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_perm_b32 v7, v26, v27, s6
; VI-NEXT:    v_or_b32_e32 v5, v5, v6
; VI-NEXT:    v_perm_b32 v6, v24, v25, s6
; VI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    v_perm_b32 v8, v30, v39, s6
; VI-NEXT:    v_or_b32_e32 v6, v6, v7
; VI-NEXT:    v_perm_b32 v7, v28, v29, s6
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; VI-NEXT:    v_or_b32_e32 v7, v7, v8
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr35
; VI-NEXT:    ; implicit-def: $vgpr34
; VI-NEXT:    ; implicit-def: $vgpr33
; VI-NEXT:    ; implicit-def: $vgpr32
; VI-NEXT:    ; implicit-def: $vgpr31
; VI-NEXT:    ; implicit-def: $vgpr8
; VI-NEXT:    ; implicit-def: $vgpr9
; VI-NEXT:    ; implicit-def: $vgpr10
; VI-NEXT:    ; implicit-def: $vgpr11
; VI-NEXT:    ; implicit-def: $vgpr12
; VI-NEXT:    ; implicit-def: $vgpr13
; VI-NEXT:    ; implicit-def: $vgpr14
; VI-NEXT:    ; implicit-def: $vgpr15
; VI-NEXT:    ; implicit-def: $vgpr16
; VI-NEXT:    ; implicit-def: $vgpr17
; VI-NEXT:    ; implicit-def: $vgpr18
; VI-NEXT:    ; implicit-def: $vgpr19
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr21
; VI-NEXT:    ; implicit-def: $vgpr22
; VI-NEXT:    ; implicit-def: $vgpr23
; VI-NEXT:    ; implicit-def: $vgpr24
; VI-NEXT:    ; implicit-def: $vgpr25
; VI-NEXT:    ; implicit-def: $vgpr26
; VI-NEXT:    ; implicit-def: $vgpr27
; VI-NEXT:    ; implicit-def: $vgpr28
; VI-NEXT:    ; implicit-def: $vgpr29
; VI-NEXT:    ; implicit-def: $vgpr30
; VI-NEXT:    ; implicit-def: $vgpr39
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB26_2
; VI-NEXT:  .LBB26_4: ; %cmp.true
; VI-NEXT:    v_add_u16_e32 v0, 3, v38
; VI-NEXT:    v_lshlrev_b16_e32 v1, 8, v37
; VI-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v1, 3, v36
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v35
; VI-NEXT:    v_or_b32_sdwa v1, v2, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_mov_b32_e32 v7, 0x300
; VI-NEXT:    v_add_u16_e32 v2, 3, v34
; VI-NEXT:    v_lshlrev_b16_e32 v3, 8, v33
; VI-NEXT:    v_add_u16_e32 v0, 0x300, v0
; VI-NEXT:    v_add_u16_sdwa v1, v1, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v2, v3, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_or_b32_e32 v0, v0, v1
; VI-NEXT:    v_add_u16_e32 v1, 0x300, v2
; VI-NEXT:    v_add_u16_e32 v2, 3, v32
; VI-NEXT:    v_lshlrev_b16_e32 v3, 8, v31
; VI-NEXT:    v_or_b32_sdwa v2, v3, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_sdwa v2, v2, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v1, v1, v2
; VI-NEXT:    v_add_u16_e32 v2, 3, v8
; VI-NEXT:    v_lshlrev_b16_e32 v3, 8, v9
; VI-NEXT:    v_or_b32_sdwa v2, v3, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v3, 3, v10
; VI-NEXT:    v_lshlrev_b16_e32 v4, 8, v11
; VI-NEXT:    v_or_b32_sdwa v3, v4, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v2, 0x300, v2
; VI-NEXT:    v_add_u16_sdwa v3, v3, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v2, v2, v3
; VI-NEXT:    v_add_u16_e32 v3, 3, v12
; VI-NEXT:    v_lshlrev_b16_e32 v4, 8, v13
; VI-NEXT:    v_or_b32_sdwa v3, v4, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v4, 3, v14
; VI-NEXT:    v_lshlrev_b16_e32 v5, 8, v15
; VI-NEXT:    v_or_b32_sdwa v4, v5, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v3, 0x300, v3
; VI-NEXT:    v_add_u16_sdwa v4, v4, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v3, v3, v4
; VI-NEXT:    v_add_u16_e32 v4, 3, v16
; VI-NEXT:    v_lshlrev_b16_e32 v5, 8, v17
; VI-NEXT:    v_or_b32_sdwa v4, v5, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v5, 3, v18
; VI-NEXT:    v_lshlrev_b16_e32 v6, 8, v19
; VI-NEXT:    v_or_b32_sdwa v5, v6, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v4, 0x300, v4
; VI-NEXT:    v_add_u16_sdwa v5, v5, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v4, v4, v5
; VI-NEXT:    v_add_u16_e32 v5, 3, v20
; VI-NEXT:    v_lshlrev_b16_e32 v6, 8, v21
; VI-NEXT:    v_or_b32_sdwa v5, v6, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v6, 3, v22
; VI-NEXT:    v_lshlrev_b16_e32 v8, 8, v23
; VI-NEXT:    v_or_b32_sdwa v6, v8, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v5, 0x300, v5
; VI-NEXT:    v_add_u16_sdwa v6, v6, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v5, v5, v6
; VI-NEXT:    v_add_u16_e32 v6, 3, v24
; VI-NEXT:    v_lshlrev_b16_e32 v8, 8, v25
; VI-NEXT:    v_or_b32_sdwa v6, v8, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v8, 3, v26
; VI-NEXT:    v_lshlrev_b16_e32 v9, 8, v27
; VI-NEXT:    v_or_b32_sdwa v8, v9, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v6, 0x300, v6
; VI-NEXT:    v_add_u16_sdwa v8, v8, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v6, v6, v8
; VI-NEXT:    v_add_u16_e32 v8, 3, v28
; VI-NEXT:    v_lshlrev_b16_e32 v9, 8, v29
; VI-NEXT:    v_or_b32_sdwa v8, v9, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v9, 3, v30
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    v_lshlrev_b16_e32 v10, 8, v39
; VI-NEXT:    v_or_b32_sdwa v9, v10, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v8, 0x300, v8
; VI-NEXT:    v_add_u16_sdwa v7, v9, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v7, v8, v7
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v32i8_to_v8i32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_mov_b32_e32 v38, v0
; GFX9-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:4
; GFX9-NEXT:    buffer_load_ushort v39, off, s[0:3], s32
; GFX9-NEXT:    v_mov_b32_e32 v31, v7
; GFX9-NEXT:    v_mov_b32_e32 v32, v6
; GFX9-NEXT:    v_mov_b32_e32 v33, v5
; GFX9-NEXT:    v_mov_b32_e32 v34, v4
; GFX9-NEXT:    v_mov_b32_e32 v35, v3
; GFX9-NEXT:    v_mov_b32_e32 v36, v2
; GFX9-NEXT:    v_mov_b32_e32 v37, v1
; GFX9-NEXT:    s_waitcnt vmcnt(1)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v0
; GFX9-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execnz .LBB26_3
; GFX9-NEXT:  ; %bb.1: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execnz .LBB26_4
; GFX9-NEXT:  .LBB26_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB26_3: ; %cmp.false
; GFX9-NEXT:    s_mov_b32 s6, 0xc0c0004
; GFX9-NEXT:    v_perm_b32 v0, v38, v37, s6
; GFX9-NEXT:    v_perm_b32 v1, v36, v35, s6
; GFX9-NEXT:    v_lshl_or_b32 v0, v1, 16, v0
; GFX9-NEXT:    v_perm_b32 v1, v34, v33, s6
; GFX9-NEXT:    v_perm_b32 v2, v32, v31, s6
; GFX9-NEXT:    v_lshl_or_b32 v1, v2, 16, v1
; GFX9-NEXT:    v_perm_b32 v2, v8, v9, s6
; GFX9-NEXT:    v_perm_b32 v3, v10, v11, s6
; GFX9-NEXT:    v_lshl_or_b32 v2, v3, 16, v2
; GFX9-NEXT:    v_perm_b32 v3, v12, v13, s6
; GFX9-NEXT:    v_perm_b32 v4, v14, v15, s6
; GFX9-NEXT:    v_lshl_or_b32 v3, v4, 16, v3
; GFX9-NEXT:    v_perm_b32 v4, v16, v17, s6
; GFX9-NEXT:    v_perm_b32 v5, v18, v19, s6
; GFX9-NEXT:    v_lshl_or_b32 v4, v5, 16, v4
; GFX9-NEXT:    v_perm_b32 v5, v20, v21, s6
; GFX9-NEXT:    v_perm_b32 v6, v22, v23, s6
; GFX9-NEXT:    v_lshl_or_b32 v5, v6, 16, v5
; GFX9-NEXT:    v_perm_b32 v6, v24, v25, s6
; GFX9-NEXT:    v_perm_b32 v7, v26, v27, s6
; GFX9-NEXT:    v_lshl_or_b32 v6, v7, 16, v6
; GFX9-NEXT:    v_perm_b32 v7, v28, v29, s6
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    v_perm_b32 v8, v30, v39, s6
; GFX9-NEXT:    v_lshl_or_b32 v7, v8, 16, v7
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr35
; GFX9-NEXT:    ; implicit-def: $vgpr34
; GFX9-NEXT:    ; implicit-def: $vgpr33
; GFX9-NEXT:    ; implicit-def: $vgpr32
; GFX9-NEXT:    ; implicit-def: $vgpr31
; GFX9-NEXT:    ; implicit-def: $vgpr8
; GFX9-NEXT:    ; implicit-def: $vgpr9
; GFX9-NEXT:    ; implicit-def: $vgpr10
; GFX9-NEXT:    ; implicit-def: $vgpr11
; GFX9-NEXT:    ; implicit-def: $vgpr12
; GFX9-NEXT:    ; implicit-def: $vgpr13
; GFX9-NEXT:    ; implicit-def: $vgpr14
; GFX9-NEXT:    ; implicit-def: $vgpr15
; GFX9-NEXT:    ; implicit-def: $vgpr16
; GFX9-NEXT:    ; implicit-def: $vgpr17
; GFX9-NEXT:    ; implicit-def: $vgpr18
; GFX9-NEXT:    ; implicit-def: $vgpr19
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr21
; GFX9-NEXT:    ; implicit-def: $vgpr22
; GFX9-NEXT:    ; implicit-def: $vgpr23
; GFX9-NEXT:    ; implicit-def: $vgpr24
; GFX9-NEXT:    ; implicit-def: $vgpr25
; GFX9-NEXT:    ; implicit-def: $vgpr26
; GFX9-NEXT:    ; implicit-def: $vgpr27
; GFX9-NEXT:    ; implicit-def: $vgpr28
; GFX9-NEXT:    ; implicit-def: $vgpr29
; GFX9-NEXT:    ; implicit-def: $vgpr30
; GFX9-NEXT:    ; implicit-def: $vgpr39
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB26_2
; GFX9-NEXT:  .LBB26_4: ; %cmp.true
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v38
; GFX9-NEXT:    v_lshlrev_b16_e32 v1, 8, v37
; GFX9-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v1, 3, v36
; GFX9-NEXT:    v_lshlrev_b16_e32 v2, 8, v35
; GFX9-NEXT:    s_movk_i32 s6, 0x300
; GFX9-NEXT:    v_or_b32_sdwa v1, v2, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v0, 0x300, v0
; GFX9-NEXT:    v_add_u16_sdwa v1, v1, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v0, v0, v1
; GFX9-NEXT:    v_add_u16_e32 v1, 3, v34
; GFX9-NEXT:    v_lshlrev_b16_e32 v2, 8, v33
; GFX9-NEXT:    v_or_b32_sdwa v1, v2, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v2, 3, v32
; GFX9-NEXT:    v_lshlrev_b16_e32 v3, 8, v31
; GFX9-NEXT:    v_or_b32_sdwa v2, v3, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v1, 0x300, v1
; GFX9-NEXT:    v_add_u16_sdwa v2, v2, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v1, v1, v2
; GFX9-NEXT:    v_add_u16_e32 v2, 3, v8
; GFX9-NEXT:    v_lshlrev_b16_e32 v3, 8, v9
; GFX9-NEXT:    v_or_b32_sdwa v2, v3, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v3, 3, v10
; GFX9-NEXT:    v_lshlrev_b16_e32 v4, 8, v11
; GFX9-NEXT:    v_or_b32_sdwa v3, v4, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v2, 0x300, v2
; GFX9-NEXT:    v_add_u16_sdwa v3, v3, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v2, v2, v3
; GFX9-NEXT:    v_add_u16_e32 v3, 3, v12
; GFX9-NEXT:    v_lshlrev_b16_e32 v4, 8, v13
; GFX9-NEXT:    v_or_b32_sdwa v3, v4, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v4, 3, v14
; GFX9-NEXT:    v_lshlrev_b16_e32 v5, 8, v15
; GFX9-NEXT:    v_or_b32_sdwa v4, v5, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v3, 0x300, v3
; GFX9-NEXT:    v_add_u16_sdwa v4, v4, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v3, v3, v4
; GFX9-NEXT:    v_add_u16_e32 v4, 3, v16
; GFX9-NEXT:    v_lshlrev_b16_e32 v5, 8, v17
; GFX9-NEXT:    v_or_b32_sdwa v4, v5, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v5, 3, v18
; GFX9-NEXT:    v_lshlrev_b16_e32 v6, 8, v19
; GFX9-NEXT:    v_or_b32_sdwa v5, v6, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v4, 0x300, v4
; GFX9-NEXT:    v_add_u16_sdwa v5, v5, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v4, v4, v5
; GFX9-NEXT:    v_add_u16_e32 v5, 3, v20
; GFX9-NEXT:    v_lshlrev_b16_e32 v6, 8, v21
; GFX9-NEXT:    v_or_b32_sdwa v5, v6, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v6, 3, v22
; GFX9-NEXT:    v_lshlrev_b16_e32 v7, 8, v23
; GFX9-NEXT:    v_or_b32_sdwa v6, v7, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v5, 0x300, v5
; GFX9-NEXT:    v_add_u16_sdwa v6, v6, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v5, v5, v6
; GFX9-NEXT:    v_add_u16_e32 v6, 3, v24
; GFX9-NEXT:    v_lshlrev_b16_e32 v7, 8, v25
; GFX9-NEXT:    v_or_b32_sdwa v6, v7, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v7, 3, v26
; GFX9-NEXT:    v_lshlrev_b16_e32 v8, 8, v27
; GFX9-NEXT:    v_or_b32_sdwa v7, v8, v7 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v6, 0x300, v6
; GFX9-NEXT:    v_add_u16_sdwa v7, v7, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v6, v6, v7
; GFX9-NEXT:    v_add_u16_e32 v7, 3, v28
; GFX9-NEXT:    v_lshlrev_b16_e32 v8, 8, v29
; GFX9-NEXT:    v_or_b32_sdwa v7, v8, v7 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v8, 3, v30
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    v_lshlrev_b16_e32 v9, 8, v39
; GFX9-NEXT:    v_or_b32_sdwa v8, v9, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v7, 0x300, v7
; GFX9-NEXT:    v_add_u16_sdwa v8, v8, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v7, v7, v8
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v32i8_to_v8i32:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_clause 0x1
; GFX11-TRUE16-NEXT:    scratch_load_b32 v48, off, s32 offset:4
; GFX11-TRUE16-NEXT:    scratch_load_d16_b16 v31, off, s32
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v32.l, v7.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v33.l, v6.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v34.l, v5.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v35.l, v4.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v36.l, v3.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v37.l, v2.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v38.l, v1.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v39.l, v0.l
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(1)
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v48
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB26_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB26_4
; GFX11-TRUE16-NEXT:  .LBB26_2: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB26_3: ; %cmp.false
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr39_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr38_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v0, v39, v38, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr37_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr36_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, v37, v36, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr35_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr34_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v2, v35, v34, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr33_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr32_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v3, v33, v32, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr8_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v4, v8, v9, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr10_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr11_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, v10, v11, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr12_hi16
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v0, v1, 16, v0
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr14_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr15_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr16_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr17_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr18_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr19_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v6, v18, v19, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v1, v3, 16, v2
; GFX11-TRUE16-NEXT:    v_perm_b32 v3, v12, v13, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v2, v5, 16, v4
; GFX11-TRUE16-NEXT:    v_perm_b32 v4, v14, v15, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, v16, v17, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr21_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v7, v20, v21, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr22_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr23_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v8, v22, v23, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr24_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr25_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v9, v24, v25, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr26_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr27_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v10, v26, v27, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr28_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr29_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v11, v28, v29, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr30_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr31_hi16
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-TRUE16-NEXT:    v_perm_b32 v12, v30, v31, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v3, v4, 16, v3
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v4, v6, 16, v5
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v5, v8, 16, v7
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v6, v10, 16, v9
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v7, v12, 16, v11
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr39_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr38_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr37_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr36_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr35_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr34_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr33_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr32_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr8_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr10_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr11_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr12_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr14_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr15_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr16_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr17_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr18_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr19_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr21_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr22_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr23_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr24_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr25_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr26_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr27_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr28_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr29_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr30_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr31_lo16
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB26_2
; GFX11-TRUE16-NEXT:  .LBB26_4: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.l, v39.l, 3
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v0.h, 8, v38.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.l, v37.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.l, v35.l, 3
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v1.h, 8, v36.l
; GFX11-TRUE16-NEXT:    v_and_b16 v0.l, 0xff, v0.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v2.h, 8, v34.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v3.l, v33.l, 3
; GFX11-TRUE16-NEXT:    v_and_b16 v1.l, 0xff, v1.l
; GFX11-TRUE16-NEXT:    v_and_b16 v2.l, 0xff, v2.l
; GFX11-TRUE16-NEXT:    v_or_b16 v0.l, v0.h, v0.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.h, v8.l, 3
; GFX11-TRUE16-NEXT:    v_and_b16 v3.l, 0xff, v3.l
; GFX11-TRUE16-NEXT:    v_or_b16 v1.l, v1.h, v1.l
; GFX11-TRUE16-NEXT:    v_or_b16 v1.h, v2.h, v2.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v2.l, 8, v32.l
; GFX11-TRUE16-NEXT:    v_and_b16 v2.h, 0xff, v0.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v3.h, 8, v9.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v4.l, v10.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.h, 0x300, v1.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.l, 0x300, v1.h
; GFX11-TRUE16-NEXT:    v_or_b16 v1.h, v2.l, v3.l
; GFX11-TRUE16-NEXT:    v_or_b16 v2.l, v3.h, v2.h
; GFX11-TRUE16-NEXT:    v_and_b16 v2.h, 0xff, v4.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v3.l, 8, v11.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v3.h, v12.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v4.l, v14.l, 3
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v4.h, 8, v15.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v5.l, v16.l, 3
; GFX11-TRUE16-NEXT:    v_or_b16 v2.h, v3.l, v2.h
; GFX11-TRUE16-NEXT:    v_and_b16 v3.l, 0xff, v3.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v3.h, 8, v13.l
; GFX11-TRUE16-NEXT:    v_and_b16 v4.l, 0xff, v4.l
; GFX11-TRUE16-NEXT:    v_and_b16 v5.l, 0xff, v5.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v5.h, 8, v17.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v6.l, 8, v19.l
; GFX11-TRUE16-NEXT:    v_or_b16 v3.l, v3.h, v3.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v3.h, v18.l, 3
; GFX11-TRUE16-NEXT:    v_or_b16 v4.l, v4.h, v4.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v4.h, v20.l, 3
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v6.h, 8, v21.l
; GFX11-TRUE16-NEXT:    v_or_b16 v5.l, v5.h, v5.l
; GFX11-TRUE16-NEXT:    v_and_b16 v3.h, 0xff, v3.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v7.l, v26.l, 3
; GFX11-TRUE16-NEXT:    v_and_b16 v4.h, 0xff, v4.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v7.h, v28.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v8.h, v30.l, 3
; GFX11-TRUE16-NEXT:    v_or_b16 v5.h, v6.l, v3.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v3.h, 0x300, v4.l
; GFX11-TRUE16-NEXT:    v_or_b16 v6.l, v6.h, v4.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v6.h, v22.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v4.l, 0x300, v5.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v4.h, 0x300, v5.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v5.h, v24.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v5.l, 0x300, v6.l
; GFX11-TRUE16-NEXT:    v_and_b16 v6.l, 0xff, v6.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v6.h, 8, v23.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v8.l, 8, v25.l
; GFX11-TRUE16-NEXT:    v_and_b16 v5.h, 0xff, v5.h
; GFX11-TRUE16-NEXT:    v_and_b16 v7.l, 0xff, v7.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v9.l, 8, v27.l
; GFX11-TRUE16-NEXT:    v_and_b16 v7.h, 0xff, v7.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v9.h, 8, v29.l
; GFX11-TRUE16-NEXT:    v_and_b16 v8.h, 0xff, v8.h
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v10.l, 8, v31.l
; GFX11-TRUE16-NEXT:    v_or_b16 v6.l, v6.h, v6.l
; GFX11-TRUE16-NEXT:    v_or_b16 v6.h, v8.l, v5.h
; GFX11-TRUE16-NEXT:    v_or_b16 v7.l, v9.l, v7.l
; GFX11-TRUE16-NEXT:    v_or_b16 v7.h, v9.h, v7.h
; GFX11-TRUE16-NEXT:    v_or_b16 v8.l, v10.l, v8.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.l, 0x300, v0.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.h, 0x300, v1.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.l, 0x300, v2.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.h, 0x300, v2.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v3.l, 0x300, v3.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v5.h, 0x300, v6.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v6.l, 0x300, v6.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v6.h, 0x300, v7.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v7.l, 0x300, v7.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v7.h, 0x300, v8.l
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v32i8_to_v8i32:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v37, v1 :: v_dual_mov_b32 v38, v0
; GFX11-FAKE16-NEXT:    s_clause 0x1
; GFX11-FAKE16-NEXT:    scratch_load_b32 v0, off, s32 offset:4
; GFX11-FAKE16-NEXT:    scratch_load_u16 v39, off, s32
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v31, v7 :: v_dual_mov_b32 v32, v6
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v33, v5 :: v_dual_mov_b32 v34, v4
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v35, v3 :: v_dual_mov_b32 v36, v2
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(1)
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v0
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB26_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB26_4
; GFX11-FAKE16-NEXT:  .LBB26_2: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB26_3: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v38, v37, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v36, v35, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v34, v33, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v32, v31, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v8, v9, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v10, v11, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v0, v1, 16, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v18, v19, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v1, v3, 16, v2
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v12, v13, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v2, v5, 16, v4
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v14, v15, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v16, v17, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v20, v21, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, v22, v23, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, v24, v25, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, v26, v27, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, v28, v29, 0xc0c0004
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, v30, v39, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v3, v4, 16, v3
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v4, v6, 16, v5
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v5, v8, 16, v7
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v6, v10, 16, v9
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v7, v12, 16, v11
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr38
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr37
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr36
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr35
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr34
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr33
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr32
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr31
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr8
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr9
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr10
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr11
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr12
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr13
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr14
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr15
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr16
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr17
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr18
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr19
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr21
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr22
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr23
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr24
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr25
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr26
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr27
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr28
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr29
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr30
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr39
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB26_2
; GFX11-FAKE16-NEXT:  .LBB26_4: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v0, v38, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v2, v36, 3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v1, 8, v37
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v3, 8, v35
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v4, v34, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xff, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v6, v32, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xff, v2
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v5, 8, v33
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v7, 8, v31
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v1, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v1, v8, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xff, v4
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v6, 0xff, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, v3, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, v10, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v0, 0x300, v0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, v5, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v5, v7, v6
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v2, 0x300, v2
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v1, 0xff, v1
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v6, 8, v9
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xff, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v7, 8, v11
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v1, v6, v1
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v4, 0x300, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v7, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v5, 0x300, v5
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v0, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v2, 0x300, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, 0x300, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v6, v12, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v8, 8, v17
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v1, v4, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v4, v14, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xff, v6
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v6, 8, v13
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, v2, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, v16, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xff, v4
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v7, 8, v15
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v5, v6, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v6, v18, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xff, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v9, 8, v19
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, v7, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v7, v20, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v6, 0xff, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v8, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v10, 8, v21
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v8, v22, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v7, 0xff, v7
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v6, v9, v6
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, 0x300, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v11, v26, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v12, v28, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v14, v30, 3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v7, v10, v7
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v9, 0xffff, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, v24, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v8, 0xff, v8
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v10, 8, v23
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v13, 8, v25
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v11, 0xff, v11
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xff, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v15, 8, v27
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v12, 0xff, v12
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v16, 8, v29
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v14, 0xff, v14
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v17, 8, v39
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v8, v10, v8
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v13, v3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v10, v15, v11
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, v16, v12
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, v17, v14
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v5, 0x300, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v4, 0x300, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v6, 0x300, v6
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v7, 0x300, v7
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v8, 0x300, v8
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, 0x300, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v10, 0x300, v10
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v11, 0x300, v11
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v12, 0x300, v12
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v13, 0xffff, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v10, 16, v10
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v12, 16, v12
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v5, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, v9, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v5, v7, v8
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v6, v13, v10
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v7, v11, v12
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <32 x i8> %a, splat (i8 3)
  %a2 = bitcast <32 x i8> %a1 to <8 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <32 x i8> %a to <8 x i32>
  br label %end

end:
  %phi = phi <8 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x i32> %phi
}

define inreg <8 x i32> @bitcast_v32i8_to_v8i32_scalar(<32 x i8> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v32i8_to_v8i32_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_readfirstlane_b32 s4, v18
; SI-NEXT:    v_readfirstlane_b32 s14, v17
; SI-NEXT:    v_readfirstlane_b32 s15, v16
; SI-NEXT:    v_readfirstlane_b32 s40, v15
; SI-NEXT:    v_readfirstlane_b32 s41, v14
; SI-NEXT:    v_readfirstlane_b32 s42, v13
; SI-NEXT:    v_readfirstlane_b32 s43, v12
; SI-NEXT:    v_readfirstlane_b32 s44, v11
; SI-NEXT:    v_readfirstlane_b32 s45, v10
; SI-NEXT:    v_readfirstlane_b32 s46, v9
; SI-NEXT:    v_readfirstlane_b32 s47, v8
; SI-NEXT:    v_readfirstlane_b32 s56, v7
; SI-NEXT:    v_readfirstlane_b32 s57, v6
; SI-NEXT:    v_readfirstlane_b32 s58, v5
; SI-NEXT:    v_readfirstlane_b32 s59, v4
; SI-NEXT:    v_readfirstlane_b32 s60, v3
; SI-NEXT:    v_readfirstlane_b32 s61, v2
; SI-NEXT:    v_readfirstlane_b32 s62, v1
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    v_readfirstlane_b32 s63, v0
; SI-NEXT:    s_cbranch_scc0 .LBB27_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s4, s16, 0xff
; SI-NEXT:    s_lshl_b32 s5, s17, 8
; SI-NEXT:    s_or_b32 s4, s4, s5
; SI-NEXT:    s_and_b32 s5, s18, 0xff
; SI-NEXT:    s_lshl_b32 s5, s5, 16
; SI-NEXT:    s_lshl_b32 s6, s19, 24
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_or_b32 s5, s6, s5
; SI-NEXT:    s_or_b32 s4, s4, s5
; SI-NEXT:    s_and_b32 s5, s20, 0xff
; SI-NEXT:    s_lshl_b32 s6, s21, 8
; SI-NEXT:    s_or_b32 s5, s5, s6
; SI-NEXT:    s_and_b32 s6, s22, 0xff
; SI-NEXT:    s_lshl_b32 s6, s6, 16
; SI-NEXT:    s_lshl_b32 s7, s23, 24
; SI-NEXT:    s_and_b32 s5, s5, 0xffff
; SI-NEXT:    s_or_b32 s6, s7, s6
; SI-NEXT:    s_or_b32 s5, s5, s6
; SI-NEXT:    s_and_b32 s6, s24, 0xff
; SI-NEXT:    s_lshl_b32 s7, s25, 8
; SI-NEXT:    s_or_b32 s6, s6, s7
; SI-NEXT:    s_and_b32 s7, s26, 0xff
; SI-NEXT:    s_lshl_b32 s7, s7, 16
; SI-NEXT:    s_lshl_b32 s8, s27, 24
; SI-NEXT:    s_and_b32 s6, s6, 0xffff
; SI-NEXT:    s_or_b32 s7, s8, s7
; SI-NEXT:    s_or_b32 s6, s6, s7
; SI-NEXT:    s_and_b32 s7, s28, 0xff
; SI-NEXT:    s_lshl_b32 s8, s29, 8
; SI-NEXT:    s_or_b32 s7, s7, s8
; SI-NEXT:    s_and_b32 s8, s63, 0xff
; SI-NEXT:    s_lshl_b32 s8, s8, 16
; SI-NEXT:    s_lshl_b32 s9, s62, 24
; SI-NEXT:    s_and_b32 s7, s7, 0xffff
; SI-NEXT:    s_or_b32 s8, s9, s8
; SI-NEXT:    s_or_b32 s7, s7, s8
; SI-NEXT:    s_and_b32 s8, s61, 0xff
; SI-NEXT:    s_lshl_b32 s9, s60, 8
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_and_b32 s9, s59, 0xff
; SI-NEXT:    s_lshl_b32 s9, s9, 16
; SI-NEXT:    s_lshl_b32 s10, s58, 24
; SI-NEXT:    s_and_b32 s8, s8, 0xffff
; SI-NEXT:    s_or_b32 s9, s10, s9
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_and_b32 s9, s57, 0xff
; SI-NEXT:    s_lshl_b32 s10, s56, 8
; SI-NEXT:    s_or_b32 s9, s9, s10
; SI-NEXT:    s_and_b32 s10, s47, 0xff
; SI-NEXT:    s_lshl_b32 s10, s10, 16
; SI-NEXT:    s_lshl_b32 s11, s46, 24
; SI-NEXT:    s_and_b32 s9, s9, 0xffff
; SI-NEXT:    s_or_b32 s10, s11, s10
; SI-NEXT:    s_or_b32 s9, s9, s10
; SI-NEXT:    s_and_b32 s10, s45, 0xff
; SI-NEXT:    s_lshl_b32 s11, s44, 8
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_and_b32 s11, s43, 0xff
; SI-NEXT:    s_lshl_b32 s11, s11, 16
; SI-NEXT:    s_lshl_b32 s12, s42, 24
; SI-NEXT:    s_and_b32 s10, s10, 0xffff
; SI-NEXT:    s_or_b32 s11, s12, s11
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_and_b32 s11, s41, 0xff
; SI-NEXT:    s_lshl_b32 s12, s40, 8
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    s_and_b32 s12, s15, 0xff
; SI-NEXT:    s_lshl_b32 s12, s12, 16
; SI-NEXT:    s_lshl_b32 s13, s14, 24
; SI-NEXT:    s_and_b32 s11, s11, 0xffff
; SI-NEXT:    s_or_b32 s12, s13, s12
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    s_cbranch_execnz .LBB27_3
; SI-NEXT:  .LBB27_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    s_and_b32 s4, s16, 0xff
; SI-NEXT:    s_lshl_b32 s5, s17, 8
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_and_b32 s6, s18, 0xff
; SI-NEXT:    s_addk_i32 s4, 0x300
; SI-NEXT:    s_lshl_b32 s5, s19, 24
; SI-NEXT:    s_lshl_b32 s6, s6, 16
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_or_b32 s5, s5, s6
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_and_b32 s5, s20, 0xff
; SI-NEXT:    s_lshl_b32 s6, s21, 8
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_or_b32 s5, s6, s5
; SI-NEXT:    s_and_b32 s7, s22, 0xff
; SI-NEXT:    s_addk_i32 s5, 0x300
; SI-NEXT:    s_lshl_b32 s6, s23, 24
; SI-NEXT:    s_lshl_b32 s7, s7, 16
; SI-NEXT:    s_and_b32 s5, s5, 0xffff
; SI-NEXT:    s_or_b32 s6, s6, s7
; SI-NEXT:    s_add_i32 s24, s24, 3
; SI-NEXT:    s_or_b32 s5, s6, s5
; SI-NEXT:    s_and_b32 s6, s24, 0xff
; SI-NEXT:    s_lshl_b32 s7, s25, 8
; SI-NEXT:    s_add_i32 s26, s26, 3
; SI-NEXT:    s_or_b32 s6, s7, s6
; SI-NEXT:    s_and_b32 s8, s26, 0xff
; SI-NEXT:    s_addk_i32 s6, 0x300
; SI-NEXT:    s_lshl_b32 s7, s27, 24
; SI-NEXT:    s_lshl_b32 s8, s8, 16
; SI-NEXT:    s_and_b32 s6, s6, 0xffff
; SI-NEXT:    s_or_b32 s7, s7, s8
; SI-NEXT:    s_add_i32 s28, s28, 3
; SI-NEXT:    s_or_b32 s6, s7, s6
; SI-NEXT:    s_and_b32 s7, s28, 0xff
; SI-NEXT:    s_lshl_b32 s8, s29, 8
; SI-NEXT:    s_add_i32 s63, s63, 3
; SI-NEXT:    s_or_b32 s7, s8, s7
; SI-NEXT:    s_and_b32 s9, s63, 0xff
; SI-NEXT:    s_addk_i32 s7, 0x300
; SI-NEXT:    s_lshl_b32 s8, s62, 24
; SI-NEXT:    s_lshl_b32 s9, s9, 16
; SI-NEXT:    s_and_b32 s7, s7, 0xffff
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_add_i32 s61, s61, 3
; SI-NEXT:    s_or_b32 s7, s8, s7
; SI-NEXT:    s_and_b32 s8, s61, 0xff
; SI-NEXT:    s_lshl_b32 s9, s60, 8
; SI-NEXT:    s_add_i32 s59, s59, 3
; SI-NEXT:    s_or_b32 s8, s9, s8
; SI-NEXT:    s_and_b32 s10, s59, 0xff
; SI-NEXT:    s_addk_i32 s8, 0x300
; SI-NEXT:    s_lshl_b32 s9, s58, 24
; SI-NEXT:    s_lshl_b32 s10, s10, 16
; SI-NEXT:    s_and_b32 s8, s8, 0xffff
; SI-NEXT:    s_or_b32 s9, s9, s10
; SI-NEXT:    s_add_i32 s57, s57, 3
; SI-NEXT:    s_or_b32 s8, s9, s8
; SI-NEXT:    s_and_b32 s9, s57, 0xff
; SI-NEXT:    s_lshl_b32 s10, s56, 8
; SI-NEXT:    s_add_i32 s47, s47, 3
; SI-NEXT:    s_or_b32 s9, s10, s9
; SI-NEXT:    s_and_b32 s11, s47, 0xff
; SI-NEXT:    s_addk_i32 s9, 0x300
; SI-NEXT:    s_lshl_b32 s10, s46, 24
; SI-NEXT:    s_lshl_b32 s11, s11, 16
; SI-NEXT:    s_and_b32 s9, s9, 0xffff
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_add_i32 s45, s45, 3
; SI-NEXT:    s_or_b32 s9, s10, s9
; SI-NEXT:    s_and_b32 s10, s45, 0xff
; SI-NEXT:    s_lshl_b32 s11, s44, 8
; SI-NEXT:    s_add_i32 s43, s43, 3
; SI-NEXT:    s_or_b32 s10, s11, s10
; SI-NEXT:    s_and_b32 s12, s43, 0xff
; SI-NEXT:    s_addk_i32 s10, 0x300
; SI-NEXT:    s_lshl_b32 s11, s42, 24
; SI-NEXT:    s_lshl_b32 s12, s12, 16
; SI-NEXT:    s_and_b32 s10, s10, 0xffff
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    s_add_i32 s41, s41, 3
; SI-NEXT:    s_or_b32 s10, s11, s10
; SI-NEXT:    s_and_b32 s11, s41, 0xff
; SI-NEXT:    s_lshl_b32 s12, s40, 8
; SI-NEXT:    s_add_i32 s15, s15, 3
; SI-NEXT:    s_or_b32 s11, s12, s11
; SI-NEXT:    s_and_b32 s13, s15, 0xff
; SI-NEXT:    s_addk_i32 s11, 0x300
; SI-NEXT:    s_lshl_b32 s12, s14, 24
; SI-NEXT:    s_lshl_b32 s13, s13, 16
; SI-NEXT:    s_and_b32 s11, s11, 0xffff
; SI-NEXT:    s_or_b32 s12, s12, s13
; SI-NEXT:    s_or_b32 s11, s12, s11
; SI-NEXT:    s_add_i32 s4, s4, 0x3000000
; SI-NEXT:    s_add_i32 s5, s5, 0x3000000
; SI-NEXT:    s_add_i32 s6, s6, 0x3000000
; SI-NEXT:    s_add_i32 s7, s7, 0x3000000
; SI-NEXT:    s_add_i32 s8, s8, 0x3000000
; SI-NEXT:    s_add_i32 s9, s9, 0x3000000
; SI-NEXT:    s_add_i32 s10, s10, 0x3000000
; SI-NEXT:    s_add_i32 s11, s11, 0x3000000
; SI-NEXT:  .LBB27_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v0, s4
; SI-NEXT:    v_mov_b32_e32 v1, s5
; SI-NEXT:    v_mov_b32_e32 v2, s6
; SI-NEXT:    v_mov_b32_e32 v3, s7
; SI-NEXT:    v_mov_b32_e32 v4, s8
; SI-NEXT:    v_mov_b32_e32 v5, s9
; SI-NEXT:    v_mov_b32_e32 v6, s10
; SI-NEXT:    v_mov_b32_e32 v7, s11
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB27_4:
; SI-NEXT:    ; implicit-def: $sgpr4_sgpr5_sgpr6_sgpr7_sgpr8_sgpr9_sgpr10_sgpr11
; SI-NEXT:    s_branch .LBB27_2
;
; VI-LABEL: bitcast_v32i8_to_v8i32_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_readfirstlane_b32 s4, v18
; VI-NEXT:    v_readfirstlane_b32 s6, v17
; VI-NEXT:    v_readfirstlane_b32 s7, v16
; VI-NEXT:    v_readfirstlane_b32 s8, v15
; VI-NEXT:    v_readfirstlane_b32 s9, v14
; VI-NEXT:    v_readfirstlane_b32 s10, v13
; VI-NEXT:    v_readfirstlane_b32 s11, v12
; VI-NEXT:    v_readfirstlane_b32 s12, v11
; VI-NEXT:    v_readfirstlane_b32 s13, v10
; VI-NEXT:    v_readfirstlane_b32 s14, v9
; VI-NEXT:    v_readfirstlane_b32 s15, v8
; VI-NEXT:    v_readfirstlane_b32 s40, v7
; VI-NEXT:    v_readfirstlane_b32 s41, v6
; VI-NEXT:    v_readfirstlane_b32 s42, v5
; VI-NEXT:    v_readfirstlane_b32 s43, v4
; VI-NEXT:    v_readfirstlane_b32 s44, v3
; VI-NEXT:    v_readfirstlane_b32 s45, v2
; VI-NEXT:    v_readfirstlane_b32 s46, v1
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    v_readfirstlane_b32 s47, v0
; VI-NEXT:    s_cbranch_scc0 .LBB27_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_mov_b32_e32 v7, 0xc0c0004
; VI-NEXT:    v_mov_b32_e32 v1, s19
; VI-NEXT:    v_mov_b32_e32 v0, s17
; VI-NEXT:    v_perm_b32 v1, s18, v1, v7
; VI-NEXT:    v_perm_b32 v0, s16, v0, v7
; VI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_mov_b32_e32 v2, s23
; VI-NEXT:    v_or_b32_e32 v0, v0, v1
; VI-NEXT:    v_mov_b32_e32 v1, s21
; VI-NEXT:    v_perm_b32 v2, s22, v2, v7
; VI-NEXT:    v_perm_b32 v1, s20, v1, v7
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_mov_b32_e32 v3, s27
; VI-NEXT:    v_or_b32_e32 v1, v1, v2
; VI-NEXT:    v_mov_b32_e32 v2, s25
; VI-NEXT:    v_perm_b32 v3, s26, v3, v7
; VI-NEXT:    v_perm_b32 v2, s24, v2, v7
; VI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_mov_b32_e32 v4, s46
; VI-NEXT:    v_or_b32_e32 v2, v2, v3
; VI-NEXT:    v_mov_b32_e32 v3, s29
; VI-NEXT:    v_perm_b32 v4, s47, v4, v7
; VI-NEXT:    v_perm_b32 v3, s28, v3, v7
; VI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_mov_b32_e32 v5, s42
; VI-NEXT:    v_or_b32_e32 v3, v3, v4
; VI-NEXT:    v_mov_b32_e32 v4, s44
; VI-NEXT:    v_perm_b32 v5, s43, v5, v7
; VI-NEXT:    v_perm_b32 v4, s45, v4, v7
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_mov_b32_e32 v6, s14
; VI-NEXT:    v_or_b32_e32 v4, v4, v5
; VI-NEXT:    v_mov_b32_e32 v5, s40
; VI-NEXT:    v_perm_b32 v6, s15, v6, v7
; VI-NEXT:    v_perm_b32 v5, s41, v5, v7
; VI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_mov_b32_e32 v8, s10
; VI-NEXT:    v_or_b32_e32 v5, v5, v6
; VI-NEXT:    v_mov_b32_e32 v6, s12
; VI-NEXT:    v_perm_b32 v8, s11, v8, v7
; VI-NEXT:    v_perm_b32 v6, s13, v6, v7
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; VI-NEXT:    v_or_b32_e32 v6, v6, v8
; VI-NEXT:    v_mov_b32_e32 v8, s8
; VI-NEXT:    v_mov_b32_e32 v9, s6
; VI-NEXT:    v_perm_b32 v8, s9, v8, v7
; VI-NEXT:    v_perm_b32 v7, s7, v9, v7
; VI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; VI-NEXT:    v_or_b32_e32 v7, v8, v7
; VI-NEXT:    s_cbranch_execnz .LBB27_3
; VI-NEXT:  .LBB27_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s16, s16, 3
; VI-NEXT:    v_mov_b32_e32 v0, s17
; VI-NEXT:    v_mov_b32_e32 v7, 0xc0c0004
; VI-NEXT:    s_add_i32 s18, s18, 3
; VI-NEXT:    v_mov_b32_e32 v1, s19
; VI-NEXT:    v_perm_b32 v0, s16, v0, v7
; VI-NEXT:    v_perm_b32 v1, s18, v1, v7
; VI-NEXT:    v_add_u32_e32 v0, vcc, 0x300, v0
; VI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s20, s20, 3
; VI-NEXT:    v_mov_b32_e32 v1, s21
; VI-NEXT:    s_add_i32 s22, s22, 3
; VI-NEXT:    v_mov_b32_e32 v2, s23
; VI-NEXT:    v_perm_b32 v1, s20, v1, v7
; VI-NEXT:    v_perm_b32 v2, s22, v2, v7
; VI-NEXT:    v_add_u32_e32 v1, vcc, 0x300, v1
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_or_b32_sdwa v1, v2, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s24, s24, 3
; VI-NEXT:    v_mov_b32_e32 v2, s25
; VI-NEXT:    s_add_i32 s26, s26, 3
; VI-NEXT:    v_mov_b32_e32 v3, s27
; VI-NEXT:    v_perm_b32 v2, s24, v2, v7
; VI-NEXT:    v_perm_b32 v3, s26, v3, v7
; VI-NEXT:    v_add_u32_e32 v2, vcc, 0x300, v2
; VI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_or_b32_sdwa v2, v3, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s28, s28, 3
; VI-NEXT:    v_mov_b32_e32 v3, s29
; VI-NEXT:    s_add_i32 s47, s47, 3
; VI-NEXT:    v_mov_b32_e32 v4, s46
; VI-NEXT:    v_perm_b32 v3, s28, v3, v7
; VI-NEXT:    v_perm_b32 v4, s47, v4, v7
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x300, v3
; VI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_or_b32_sdwa v3, v4, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s45, s45, 3
; VI-NEXT:    v_mov_b32_e32 v4, s44
; VI-NEXT:    s_add_i32 s43, s43, 3
; VI-NEXT:    v_mov_b32_e32 v5, s42
; VI-NEXT:    v_perm_b32 v4, s45, v4, v7
; VI-NEXT:    v_perm_b32 v5, s43, v5, v7
; VI-NEXT:    v_add_u32_e32 v4, vcc, 0x300, v4
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_or_b32_sdwa v4, v5, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s41, s41, 3
; VI-NEXT:    v_mov_b32_e32 v5, s40
; VI-NEXT:    s_add_i32 s15, s15, 3
; VI-NEXT:    v_mov_b32_e32 v6, s14
; VI-NEXT:    v_perm_b32 v5, s41, v5, v7
; VI-NEXT:    v_perm_b32 v6, s15, v6, v7
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x300, v5
; VI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_or_b32_sdwa v5, v6, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s13, s13, 3
; VI-NEXT:    v_mov_b32_e32 v6, s12
; VI-NEXT:    s_add_i32 s11, s11, 3
; VI-NEXT:    v_mov_b32_e32 v8, s10
; VI-NEXT:    v_perm_b32 v6, s13, v6, v7
; VI-NEXT:    v_perm_b32 v8, s11, v8, v7
; VI-NEXT:    v_add_u32_e32 v6, vcc, 0x300, v6
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; VI-NEXT:    v_or_b32_sdwa v6, v8, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s9, s9, 3
; VI-NEXT:    v_mov_b32_e32 v8, s8
; VI-NEXT:    s_add_i32 s7, s7, 3
; VI-NEXT:    v_mov_b32_e32 v9, s6
; VI-NEXT:    v_perm_b32 v8, s9, v8, v7
; VI-NEXT:    v_perm_b32 v7, s7, v9, v7
; VI-NEXT:    v_add_u32_e32 v8, vcc, 0x300, v8
; VI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; VI-NEXT:    v_or_b32_sdwa v7, v7, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_add_u32_e32 v0, vcc, 0x3000000, v0
; VI-NEXT:    v_add_u32_e32 v1, vcc, 0x3000000, v1
; VI-NEXT:    v_add_u32_e32 v2, vcc, 0x3000000, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x3000000, v3
; VI-NEXT:    v_add_u32_e32 v4, vcc, 0x3000000, v4
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x3000000, v5
; VI-NEXT:    v_add_u32_e32 v6, vcc, 0x3000000, v6
; VI-NEXT:    v_add_u32_e32 v7, vcc, 0x3000000, v7
; VI-NEXT:  .LBB27_3: ; %end
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB27_4:
; VI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; VI-NEXT:    s_branch .LBB27_2
;
; GFX9-LABEL: bitcast_v32i8_to_v8i32_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_readfirstlane_b32 s4, v18
; GFX9-NEXT:    v_readfirstlane_b32 s6, v17
; GFX9-NEXT:    v_readfirstlane_b32 s7, v16
; GFX9-NEXT:    v_readfirstlane_b32 s8, v15
; GFX9-NEXT:    v_readfirstlane_b32 s9, v14
; GFX9-NEXT:    v_readfirstlane_b32 s10, v13
; GFX9-NEXT:    v_readfirstlane_b32 s11, v12
; GFX9-NEXT:    v_readfirstlane_b32 s12, v11
; GFX9-NEXT:    v_readfirstlane_b32 s13, v10
; GFX9-NEXT:    v_readfirstlane_b32 s14, v9
; GFX9-NEXT:    v_readfirstlane_b32 s15, v8
; GFX9-NEXT:    v_readfirstlane_b32 s40, v7
; GFX9-NEXT:    v_readfirstlane_b32 s41, v6
; GFX9-NEXT:    v_readfirstlane_b32 s42, v5
; GFX9-NEXT:    v_readfirstlane_b32 s43, v4
; GFX9-NEXT:    v_readfirstlane_b32 s44, v3
; GFX9-NEXT:    v_readfirstlane_b32 s45, v2
; GFX9-NEXT:    v_readfirstlane_b32 s46, v1
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    v_readfirstlane_b32 s47, v0
; GFX9-NEXT:    s_cbranch_scc0 .LBB27_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    v_mov_b32_e32 v7, 0xc0c0004
; GFX9-NEXT:    v_mov_b32_e32 v1, s19
; GFX9-NEXT:    v_mov_b32_e32 v0, s17
; GFX9-NEXT:    v_perm_b32 v1, s18, v1, v7
; GFX9-NEXT:    v_perm_b32 v0, s16, v0, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_mov_b32_e32 v2, s23
; GFX9-NEXT:    v_or_b32_e32 v0, v0, v1
; GFX9-NEXT:    v_mov_b32_e32 v1, s21
; GFX9-NEXT:    v_perm_b32 v2, s22, v2, v7
; GFX9-NEXT:    v_perm_b32 v1, s20, v1, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; GFX9-NEXT:    v_mov_b32_e32 v3, s27
; GFX9-NEXT:    v_or_b32_e32 v1, v1, v2
; GFX9-NEXT:    v_mov_b32_e32 v2, s25
; GFX9-NEXT:    v_perm_b32 v3, s26, v3, v7
; GFX9-NEXT:    v_perm_b32 v2, s24, v2, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; GFX9-NEXT:    v_mov_b32_e32 v4, s46
; GFX9-NEXT:    v_or_b32_e32 v2, v2, v3
; GFX9-NEXT:    v_mov_b32_e32 v3, s29
; GFX9-NEXT:    v_perm_b32 v4, s47, v4, v7
; GFX9-NEXT:    v_perm_b32 v3, s28, v3, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX9-NEXT:    v_mov_b32_e32 v5, s42
; GFX9-NEXT:    v_or_b32_e32 v3, v3, v4
; GFX9-NEXT:    v_mov_b32_e32 v4, s44
; GFX9-NEXT:    v_perm_b32 v5, s43, v5, v7
; GFX9-NEXT:    v_perm_b32 v4, s45, v4, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX9-NEXT:    v_mov_b32_e32 v6, s14
; GFX9-NEXT:    v_or_b32_e32 v4, v4, v5
; GFX9-NEXT:    v_mov_b32_e32 v5, s40
; GFX9-NEXT:    v_perm_b32 v6, s15, v6, v7
; GFX9-NEXT:    v_perm_b32 v5, s41, v5, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GFX9-NEXT:    v_mov_b32_e32 v8, s10
; GFX9-NEXT:    v_or_b32_e32 v5, v5, v6
; GFX9-NEXT:    v_mov_b32_e32 v6, s12
; GFX9-NEXT:    v_perm_b32 v8, s11, v8, v7
; GFX9-NEXT:    v_perm_b32 v6, s13, v6, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; GFX9-NEXT:    v_or_b32_e32 v6, v6, v8
; GFX9-NEXT:    v_mov_b32_e32 v8, s8
; GFX9-NEXT:    v_mov_b32_e32 v9, s6
; GFX9-NEXT:    v_perm_b32 v8, s9, v8, v7
; GFX9-NEXT:    v_perm_b32 v7, s7, v9, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; GFX9-NEXT:    v_or_b32_e32 v7, v8, v7
; GFX9-NEXT:    s_cbranch_execnz .LBB27_3
; GFX9-NEXT:  .LBB27_2: ; %cmp.true
; GFX9-NEXT:    s_add_i32 s16, s16, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s17
; GFX9-NEXT:    v_mov_b32_e32 v7, 0xc0c0004
; GFX9-NEXT:    s_add_i32 s18, s18, 3
; GFX9-NEXT:    v_mov_b32_e32 v1, s19
; GFX9-NEXT:    v_perm_b32 v0, s16, v0, v7
; GFX9-NEXT:    s_movk_i32 s4, 0x300
; GFX9-NEXT:    v_perm_b32 v1, s18, v1, v7
; GFX9-NEXT:    v_add_u32_e32 v0, 0x300, v0
; GFX9-NEXT:    v_add_u32_sdwa v1, v1, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v0, v0, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s20, s20, 3
; GFX9-NEXT:    v_mov_b32_e32 v1, s21
; GFX9-NEXT:    s_add_i32 s22, s22, 3
; GFX9-NEXT:    v_mov_b32_e32 v2, s23
; GFX9-NEXT:    v_perm_b32 v1, s20, v1, v7
; GFX9-NEXT:    v_perm_b32 v2, s22, v2, v7
; GFX9-NEXT:    v_add_u32_e32 v1, 0x300, v1
; GFX9-NEXT:    v_add_u32_sdwa v2, v2, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v1, v1, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s24, s24, 3
; GFX9-NEXT:    v_mov_b32_e32 v2, s25
; GFX9-NEXT:    s_add_i32 s26, s26, 3
; GFX9-NEXT:    v_mov_b32_e32 v3, s27
; GFX9-NEXT:    v_perm_b32 v2, s24, v2, v7
; GFX9-NEXT:    v_perm_b32 v3, s26, v3, v7
; GFX9-NEXT:    v_add_u32_e32 v2, 0x300, v2
; GFX9-NEXT:    v_add_u32_sdwa v3, v3, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v2, v2, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s28, s28, 3
; GFX9-NEXT:    v_mov_b32_e32 v3, s29
; GFX9-NEXT:    s_add_i32 s47, s47, 3
; GFX9-NEXT:    v_mov_b32_e32 v4, s46
; GFX9-NEXT:    v_perm_b32 v3, s28, v3, v7
; GFX9-NEXT:    v_perm_b32 v4, s47, v4, v7
; GFX9-NEXT:    v_add_u32_e32 v3, 0x300, v3
; GFX9-NEXT:    v_add_u32_sdwa v4, v4, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v3, v3, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s45, s45, 3
; GFX9-NEXT:    v_mov_b32_e32 v4, s44
; GFX9-NEXT:    s_add_i32 s43, s43, 3
; GFX9-NEXT:    v_mov_b32_e32 v5, s42
; GFX9-NEXT:    v_perm_b32 v4, s45, v4, v7
; GFX9-NEXT:    v_perm_b32 v5, s43, v5, v7
; GFX9-NEXT:    v_add_u32_e32 v4, 0x300, v4
; GFX9-NEXT:    v_add_u32_sdwa v5, v5, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v4, v4, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s41, s41, 3
; GFX9-NEXT:    v_mov_b32_e32 v5, s40
; GFX9-NEXT:    s_add_i32 s15, s15, 3
; GFX9-NEXT:    v_mov_b32_e32 v6, s14
; GFX9-NEXT:    v_perm_b32 v5, s41, v5, v7
; GFX9-NEXT:    v_perm_b32 v6, s15, v6, v7
; GFX9-NEXT:    v_add_u32_e32 v5, 0x300, v5
; GFX9-NEXT:    v_add_u32_sdwa v6, v6, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v5, v5, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s13, s13, 3
; GFX9-NEXT:    v_mov_b32_e32 v6, s12
; GFX9-NEXT:    s_add_i32 s11, s11, 3
; GFX9-NEXT:    v_mov_b32_e32 v8, s10
; GFX9-NEXT:    v_perm_b32 v6, s13, v6, v7
; GFX9-NEXT:    v_perm_b32 v8, s11, v8, v7
; GFX9-NEXT:    v_add_u32_e32 v6, 0x300, v6
; GFX9-NEXT:    v_add_u32_sdwa v8, v8, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v6, v6, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s9, s9, 3
; GFX9-NEXT:    v_mov_b32_e32 v8, s8
; GFX9-NEXT:    s_add_i32 s7, s7, 3
; GFX9-NEXT:    v_mov_b32_e32 v9, s6
; GFX9-NEXT:    v_perm_b32 v8, s9, v8, v7
; GFX9-NEXT:    v_perm_b32 v7, s7, v9, v7
; GFX9-NEXT:    v_add_u32_e32 v8, 0x300, v8
; GFX9-NEXT:    v_add_u32_sdwa v7, v7, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v7, v8, v7 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:  .LBB27_3: ; %end
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB27_4:
; GFX9-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX9-NEXT:    s_branch .LBB27_2
;
; GFX11-TRUE16-LABEL: bitcast_v32i8_to_v8i32_scalar:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s42, v14
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s4, v13
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr12_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s5, v12
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr11_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s6, v11
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr10_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s7, v10
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s8, v9
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr8_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s9, v8
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr7_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s10, v7
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr6_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s11, v6
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr5_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s12, v5
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr4_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s13, v4
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr3_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s14, v3
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr2_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s15, v2
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr1_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s40, v1
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr0_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s41, v0
; GFX11-TRUE16-NEXT:    s_cmp_lg_u32 s42, 0
; GFX11-TRUE16-NEXT:    s_mov_b32 s42, 0
; GFX11-TRUE16-NEXT:    s_cbranch_scc0 .LBB27_4
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v3, 0xc0c0004
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_perm_b32 v4, s18, s19, v3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, s2, s3, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, s22, s23, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v0, s0, s1, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v2, s16, s17, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v6, s20, s21, v3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX11-TRUE16-NEXT:    v_perm_b32 v8, s26, s27, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v9, s41, s40, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v11, s5, s4, v3
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v0, v0, v1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v1, v2, v4
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v2, v6, v5
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v8
; GFX11-TRUE16-NEXT:    v_perm_b32 v6, s13, s12, v3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v8, 16, v9
; GFX11-TRUE16-NEXT:    v_perm_b32 v9, s9, s8, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v7, s24, s25, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, s28, s29, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v10, s15, s14, v3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GFX11-TRUE16-NEXT:    v_perm_b32 v12, s11, s10, v3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; GFX11-TRUE16-NEXT:    v_perm_b32 v13, s7, s6, v3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v3, v7, v4
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v4, v5, v8
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, v10, v6
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v6, v12, v9
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v7, v13, v11
; GFX11-TRUE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s42
; GFX11-TRUE16-NEXT:    s_cbranch_vccnz .LBB27_3
; GFX11-TRUE16-NEXT:  .LBB27_2: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v3, 0xc0c0004
; GFX11-TRUE16-NEXT:    s_add_i32 s18, s18, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s0, s0, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s2, s2, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s16, s16, 3
; GFX11-TRUE16-NEXT:    v_perm_b32 v4, s18, s19, v3
; GFX11-TRUE16-NEXT:    s_add_i32 s20, s20, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s22, s22, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s24, s24, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s26, s26, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v4, 0x300, v4
; GFX11-TRUE16-NEXT:    s_add_i32 s28, s28, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s41, s41, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s15, s15, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s13, s13, 3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX11-TRUE16-NEXT:    v_perm_b32 v0, s0, s1, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, s2, s3, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v2, s16, s17, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, s20, s21, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v6, s22, s23, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v0, 0x300, v0
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, 0x300, v1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, 0x300, v2
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v5, 0x300, v5
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, 0x300, v6
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GFX11-TRUE16-NEXT:    s_add_i32 s11, s11, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s9, s9, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s7, s7, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s5, s5, 3
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v0, v0, v1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v1, v2, v4
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v2, v5, v6
; GFX11-TRUE16-NEXT:    v_perm_b32 v4, s24, s25, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, s26, s27, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v6, s28, s29, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v7, s41, s40, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v8, s15, s14, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v9, s13, s12, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v10, s11, s10, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v11, s9, s8, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v12, s7, s6, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v3, s5, s4, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v4, 0x300, v4
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v5, 0x300, v5
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, 0x300, v6
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v7, 0x300, v7
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v8, 0x300, v8
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v9, 0x300, v9
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v10, 0x300, v10
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v11, 0x300, v11
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v12, 0x300, v12
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 0x300, v3
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v13, 16, v3
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v3, v4, v5
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v4, v6, v7
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, v8, v9
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v6, v10, v11
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v7, v12, v13
; GFX11-TRUE16-NEXT:  .LBB27_3: ; %end
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB27_4:
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-TRUE16-NEXT:    s_branch .LBB27_2
;
; GFX11-FAKE16-LABEL: bitcast_v32i8_to_v8i32_scalar:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s42, v14
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s4, v13
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s5, v12
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s6, v11
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s7, v10
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s8, v9
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s9, v8
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s10, v7
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s11, v6
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s12, v5
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s13, v4
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s14, v3
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s15, v2
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s40, v1
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s41, v0
; GFX11-FAKE16-NEXT:    s_cmp_lg_u32 s42, 0
; GFX11-FAKE16-NEXT:    s_mov_b32 s42, 0
; GFX11-FAKE16-NEXT:    s_cbranch_scc0 .LBB27_4
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v3, 0xc0c0004
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, s18, s19, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, s2, s3, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, s22, s23, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, s0, s1, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, s16, s17, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, s20, s21, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, s26, s27, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, s41, s40, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, s5, s4, v3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v0, v1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v1, v2, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, v6, v5
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v8
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, s13, s12, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v8, 16, v9
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, s9, s8, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, s24, s25, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, s28, s29, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, s15, s14, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, s11, s10, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, s7, s6, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v7, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, v5, v8
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v5, v10, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v6, v12, v9
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v7, v13, v11
; GFX11-FAKE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s42
; GFX11-FAKE16-NEXT:    s_cbranch_vccnz .LBB27_3
; GFX11-FAKE16-NEXT:  .LBB27_2: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v3, 0xc0c0004
; GFX11-FAKE16-NEXT:    s_add_i32 s18, s18, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s0, s0, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s2, s2, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s16, s16, 3
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, s18, s19, v3
; GFX11-FAKE16-NEXT:    s_add_i32 s20, s20, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s22, s22, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s24, s24, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s26, s26, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, 0x300, v4
; GFX11-FAKE16-NEXT:    s_add_i32 s28, s28, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s41, s41, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s15, s15, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s13, s13, 3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, s0, s1, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, s2, s3, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, s16, s17, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, s20, s21, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, s22, s23, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v0, 0x300, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v1, 0x300, v1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, 0x300, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v5, 0x300, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v6, 0x300, v6
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GFX11-FAKE16-NEXT:    s_add_i32 s11, s11, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s9, s9, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s7, s7, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s5, s5, 3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v0, v1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v1, v2, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, v5, v6
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, s24, s25, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, s26, s27, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, s28, s29, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, s41, s40, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, s15, s14, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, s13, s12, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, s11, s10, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, s9, s8, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, s7, s6, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, s5, s4, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, 0x300, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v5, 0x300, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v6, 0x300, v6
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v7, 0x300, v7
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v8, 0x300, v8
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v9, 0x300, v9
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v10, 0x300, v10
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v11, 0x300, v11
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v12, 0x300, v12
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, 0x300, v3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v13, 16, v3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v4, v5
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, v6, v7
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v5, v8, v9
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v6, v10, v11
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v7, v12, v13
; GFX11-FAKE16-NEXT:  .LBB27_3: ; %end
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB27_4:
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-FAKE16-NEXT:    s_branch .LBB27_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <32 x i8> %a, splat (i8 3)
  %a2 = bitcast <32 x i8> %a1 to <8 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <32 x i8> %a to <8 x i32>
  br label %end

end:
  %phi = phi <8 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x i32> %phi
}

define <4 x i64> @bitcast_v8f32_to_v4i64(<8 x float> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v8f32_to_v4i64:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:  ; %bb.1: ; %cmp.true
; SI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; SI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; SI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; SI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; SI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; SI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; SI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; SI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; SI-NEXT:  ; %bb.2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v8f32_to_v4i64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; VI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; VI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; VI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; VI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; VI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; VI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; VI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; VI-NEXT:  ; %bb.2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v8f32_to_v4i64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e32 v7, 1.0, v7
; GFX9-NEXT:    v_add_f32_e32 v6, 1.0, v6
; GFX9-NEXT:    v_add_f32_e32 v5, 1.0, v5
; GFX9-NEXT:    v_add_f32_e32 v4, 1.0, v4
; GFX9-NEXT:    v_add_f32_e32 v3, 1.0, v3
; GFX9-NEXT:    v_add_f32_e32 v2, 1.0, v2
; GFX9-NEXT:    v_add_f32_e32 v1, 1.0, v1
; GFX9-NEXT:    v_add_f32_e32 v0, 1.0, v0
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v8f32_to_v4i64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_dual_add_f32 v7, 1.0, v7 :: v_dual_add_f32 v6, 1.0, v6
; GFX11-NEXT:    v_dual_add_f32 v5, 1.0, v5 :: v_dual_add_f32 v4, 1.0, v4
; GFX11-NEXT:    v_dual_add_f32 v3, 1.0, v3 :: v_dual_add_f32 v2, 1.0, v2
; GFX11-NEXT:    v_dual_add_f32 v1, 1.0, v1 :: v_dual_add_f32 v0, 1.0, v0
; GFX11-NEXT:  ; %bb.2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <8 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <8 x float> %a1 to <4 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <8 x float> %a to <4 x i64>
  br label %end

end:
  %phi = phi <4 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x i64> %phi
}

define inreg <4 x i64> @bitcast_v8f32_to_v4i64_scalar(<8 x float> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v8f32_to_v4i64_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB29_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_cbranch_execnz .LBB29_4
; SI-NEXT:  .LBB29_2: ; %cmp.true
; SI-NEXT:    v_add_f32_e64 v7, s23, 1.0
; SI-NEXT:    v_add_f32_e64 v6, s22, 1.0
; SI-NEXT:    v_add_f32_e64 v5, s21, 1.0
; SI-NEXT:    v_add_f32_e64 v4, s20, 1.0
; SI-NEXT:    v_add_f32_e64 v3, s19, 1.0
; SI-NEXT:    v_add_f32_e64 v2, s18, 1.0
; SI-NEXT:    v_add_f32_e64 v1, s17, 1.0
; SI-NEXT:    v_add_f32_e64 v0, s16, 1.0
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB29_3:
; SI-NEXT:    s_branch .LBB29_2
; SI-NEXT:  .LBB29_4:
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v2, s18
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v4, s20
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v6, s22
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v8f32_to_v4i64_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB29_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB29_4
; VI-NEXT:  .LBB29_2: ; %cmp.true
; VI-NEXT:    v_add_f32_e64 v7, s23, 1.0
; VI-NEXT:    v_add_f32_e64 v6, s22, 1.0
; VI-NEXT:    v_add_f32_e64 v5, s21, 1.0
; VI-NEXT:    v_add_f32_e64 v4, s20, 1.0
; VI-NEXT:    v_add_f32_e64 v3, s19, 1.0
; VI-NEXT:    v_add_f32_e64 v2, s18, 1.0
; VI-NEXT:    v_add_f32_e64 v1, s17, 1.0
; VI-NEXT:    v_add_f32_e64 v0, s16, 1.0
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB29_3:
; VI-NEXT:    s_branch .LBB29_2
; VI-NEXT:  .LBB29_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v8f32_to_v4i64_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB29_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB29_4
; GFX9-NEXT:  .LBB29_2: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e64 v7, s23, 1.0
; GFX9-NEXT:    v_add_f32_e64 v6, s22, 1.0
; GFX9-NEXT:    v_add_f32_e64 v5, s21, 1.0
; GFX9-NEXT:    v_add_f32_e64 v4, s20, 1.0
; GFX9-NEXT:    v_add_f32_e64 v3, s19, 1.0
; GFX9-NEXT:    v_add_f32_e64 v2, s18, 1.0
; GFX9-NEXT:    v_add_f32_e64 v1, s17, 1.0
; GFX9-NEXT:    v_add_f32_e64 v0, s16, 1.0
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB29_3:
; GFX9-NEXT:    s_branch .LBB29_2
; GFX9-NEXT:  .LBB29_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v8f32_to_v4i64_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s7, s19
; GFX11-NEXT:    s_mov_b32 s6, s18
; GFX11-NEXT:    s_mov_b32 s5, s17
; GFX11-NEXT:    s_mov_b32 s4, s16
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s8, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB29_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-NEXT:    s_cbranch_vccnz .LBB29_4
; GFX11-NEXT:  .LBB29_2: ; %cmp.true
; GFX11-NEXT:    v_add_f32_e64 v7, s7, 1.0
; GFX11-NEXT:    v_add_f32_e64 v6, s6, 1.0
; GFX11-NEXT:    v_add_f32_e64 v5, s5, 1.0
; GFX11-NEXT:    v_add_f32_e64 v4, s4, 1.0
; GFX11-NEXT:    v_add_f32_e64 v3, s3, 1.0
; GFX11-NEXT:    v_add_f32_e64 v2, s2, 1.0
; GFX11-NEXT:    v_add_f32_e64 v1, s1, 1.0
; GFX11-NEXT:    v_add_f32_e64 v0, s0, 1.0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB29_3:
; GFX11-NEXT:    s_branch .LBB29_2
; GFX11-NEXT:  .LBB29_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <8 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <8 x float> %a1 to <4 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <8 x float> %a to <4 x i64>
  br label %end

end:
  %phi = phi <4 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x i64> %phi
}

define <8 x float> @bitcast_v4i64_to_v8f32(<4 x i64> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v4i64_to_v8f32:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:  ; %bb.1: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; SI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; SI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; SI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; SI-NEXT:  ; %bb.2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v4i64_to_v8f32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-NEXT:  ; %bb.2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v4i64_to_v8f32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_co_u32_e32 v6, vcc, 3, v6
; GFX9-NEXT:    v_addc_co_u32_e32 v7, vcc, 0, v7, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v4, vcc, 3, v4
; GFX9-NEXT:    v_addc_co_u32_e32 v5, vcc, 0, v5, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v2, vcc, 3, v2
; GFX9-NEXT:    v_addc_co_u32_e32 v3, vcc, 0, v3, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v0, vcc, 3, v0
; GFX9-NEXT:    v_addc_co_u32_e32 v1, vcc, 0, v1, vcc
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v4i64_to_v8f32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB30_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_co_u32 v6, vcc_lo, v6, 3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_co_ci_u32_e64 v7, null, 0, v7, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v4, vcc_lo, v4, 3
; GFX11-NEXT:    v_add_co_ci_u32_e64 v5, null, 0, v5, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v2, vcc_lo, v2, 3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_co_ci_u32_e64 v3, null, 0, v3, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v0, vcc_lo, v0, 3
; GFX11-NEXT:    v_add_co_ci_u32_e64 v1, null, 0, v1, vcc_lo
; GFX11-NEXT:  .LBB30_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <4 x i64> %a, splat (i64 3)
  %a2 = bitcast <4 x i64> %a1 to <8 x float>
  br label %end

cmp.false:
  %a3 = bitcast <4 x i64> %a to <8 x float>
  br label %end

end:
  %phi = phi <8 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x float> %phi
}

define inreg <8 x float> @bitcast_v4i64_to_v8f32_scalar(<4 x i64> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v4i64_to_v8f32_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB31_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_cbranch_execnz .LBB31_3
; SI-NEXT:  .LBB31_2: ; %cmp.true
; SI-NEXT:    s_add_u32 s22, s22, 3
; SI-NEXT:    s_addc_u32 s23, s23, 0
; SI-NEXT:    s_add_u32 s20, s20, 3
; SI-NEXT:    s_addc_u32 s21, s21, 0
; SI-NEXT:    s_add_u32 s18, s18, 3
; SI-NEXT:    s_addc_u32 s19, s19, 0
; SI-NEXT:    s_add_u32 s16, s16, 3
; SI-NEXT:    s_addc_u32 s17, s17, 0
; SI-NEXT:  .LBB31_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v2, s18
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v4, s20
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v6, s22
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB31_4:
; SI-NEXT:    s_branch .LBB31_2
;
; VI-LABEL: bitcast_v4i64_to_v8f32_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB31_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB31_3
; VI-NEXT:  .LBB31_2: ; %cmp.true
; VI-NEXT:    s_add_u32 s22, s22, 3
; VI-NEXT:    s_addc_u32 s23, s23, 0
; VI-NEXT:    s_add_u32 s20, s20, 3
; VI-NEXT:    s_addc_u32 s21, s21, 0
; VI-NEXT:    s_add_u32 s18, s18, 3
; VI-NEXT:    s_addc_u32 s19, s19, 0
; VI-NEXT:    s_add_u32 s16, s16, 3
; VI-NEXT:    s_addc_u32 s17, s17, 0
; VI-NEXT:  .LBB31_3: ; %end
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB31_4:
; VI-NEXT:    s_branch .LBB31_2
;
; GFX9-LABEL: bitcast_v4i64_to_v8f32_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB31_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB31_3
; GFX9-NEXT:  .LBB31_2: ; %cmp.true
; GFX9-NEXT:    s_add_u32 s22, s22, 3
; GFX9-NEXT:    s_addc_u32 s23, s23, 0
; GFX9-NEXT:    s_add_u32 s20, s20, 3
; GFX9-NEXT:    s_addc_u32 s21, s21, 0
; GFX9-NEXT:    s_add_u32 s18, s18, 3
; GFX9-NEXT:    s_addc_u32 s19, s19, 0
; GFX9-NEXT:    s_add_u32 s16, s16, 3
; GFX9-NEXT:    s_addc_u32 s17, s17, 0
; GFX9-NEXT:  .LBB31_3: ; %end
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB31_4:
; GFX9-NEXT:    s_branch .LBB31_2
;
; GFX11-LABEL: bitcast_v4i64_to_v8f32_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s4, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB31_4
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s4
; GFX11-NEXT:    s_cbranch_vccnz .LBB31_3
; GFX11-NEXT:  .LBB31_2: ; %cmp.true
; GFX11-NEXT:    s_add_u32 s18, s18, 3
; GFX11-NEXT:    s_addc_u32 s19, s19, 0
; GFX11-NEXT:    s_add_u32 s16, s16, 3
; GFX11-NEXT:    s_addc_u32 s17, s17, 0
; GFX11-NEXT:    s_add_u32 s2, s2, 3
; GFX11-NEXT:    s_addc_u32 s3, s3, 0
; GFX11-NEXT:    s_add_u32 s0, s0, 3
; GFX11-NEXT:    s_addc_u32 s1, s1, 0
; GFX11-NEXT:  .LBB31_3: ; %end
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s16 :: v_dual_mov_b32 v5, s17
; GFX11-NEXT:    v_dual_mov_b32 v6, s18 :: v_dual_mov_b32 v7, s19
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB31_4:
; GFX11-NEXT:    s_branch .LBB31_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <4 x i64> %a, splat (i64 3)
  %a2 = bitcast <4 x i64> %a1 to <8 x float>
  br label %end

cmp.false:
  %a3 = bitcast <4 x i64> %a to <8 x float>
  br label %end

end:
  %phi = phi <8 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x float> %phi
}

define <4 x double> @bitcast_v8f32_to_v4f64(<8 x float> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v8f32_to_v4f64:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:  ; %bb.1: ; %cmp.true
; SI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; SI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; SI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; SI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; SI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; SI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; SI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; SI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; SI-NEXT:  ; %bb.2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v8f32_to_v4f64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; VI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; VI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; VI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; VI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; VI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; VI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; VI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; VI-NEXT:  ; %bb.2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v8f32_to_v4f64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e32 v7, 1.0, v7
; GFX9-NEXT:    v_add_f32_e32 v6, 1.0, v6
; GFX9-NEXT:    v_add_f32_e32 v5, 1.0, v5
; GFX9-NEXT:    v_add_f32_e32 v4, 1.0, v4
; GFX9-NEXT:    v_add_f32_e32 v3, 1.0, v3
; GFX9-NEXT:    v_add_f32_e32 v2, 1.0, v2
; GFX9-NEXT:    v_add_f32_e32 v1, 1.0, v1
; GFX9-NEXT:    v_add_f32_e32 v0, 1.0, v0
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v8f32_to_v4f64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_dual_add_f32 v7, 1.0, v7 :: v_dual_add_f32 v6, 1.0, v6
; GFX11-NEXT:    v_dual_add_f32 v5, 1.0, v5 :: v_dual_add_f32 v4, 1.0, v4
; GFX11-NEXT:    v_dual_add_f32 v3, 1.0, v3 :: v_dual_add_f32 v2, 1.0, v2
; GFX11-NEXT:    v_dual_add_f32 v1, 1.0, v1 :: v_dual_add_f32 v0, 1.0, v0
; GFX11-NEXT:  ; %bb.2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <8 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <8 x float> %a1 to <4 x double>
  br label %end

cmp.false:
  %a3 = bitcast <8 x float> %a to <4 x double>
  br label %end

end:
  %phi = phi <4 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x double> %phi
}

define inreg <4 x double> @bitcast_v8f32_to_v4f64_scalar(<8 x float> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v8f32_to_v4f64_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB33_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_cbranch_execnz .LBB33_4
; SI-NEXT:  .LBB33_2: ; %cmp.true
; SI-NEXT:    v_add_f32_e64 v7, s23, 1.0
; SI-NEXT:    v_add_f32_e64 v6, s22, 1.0
; SI-NEXT:    v_add_f32_e64 v5, s21, 1.0
; SI-NEXT:    v_add_f32_e64 v4, s20, 1.0
; SI-NEXT:    v_add_f32_e64 v3, s19, 1.0
; SI-NEXT:    v_add_f32_e64 v2, s18, 1.0
; SI-NEXT:    v_add_f32_e64 v1, s17, 1.0
; SI-NEXT:    v_add_f32_e64 v0, s16, 1.0
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB33_3:
; SI-NEXT:    s_branch .LBB33_2
; SI-NEXT:  .LBB33_4:
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v2, s18
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v4, s20
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v6, s22
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v8f32_to_v4f64_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB33_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB33_4
; VI-NEXT:  .LBB33_2: ; %cmp.true
; VI-NEXT:    v_add_f32_e64 v7, s23, 1.0
; VI-NEXT:    v_add_f32_e64 v6, s22, 1.0
; VI-NEXT:    v_add_f32_e64 v5, s21, 1.0
; VI-NEXT:    v_add_f32_e64 v4, s20, 1.0
; VI-NEXT:    v_add_f32_e64 v3, s19, 1.0
; VI-NEXT:    v_add_f32_e64 v2, s18, 1.0
; VI-NEXT:    v_add_f32_e64 v1, s17, 1.0
; VI-NEXT:    v_add_f32_e64 v0, s16, 1.0
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB33_3:
; VI-NEXT:    s_branch .LBB33_2
; VI-NEXT:  .LBB33_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v8f32_to_v4f64_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB33_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB33_4
; GFX9-NEXT:  .LBB33_2: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e64 v7, s23, 1.0
; GFX9-NEXT:    v_add_f32_e64 v6, s22, 1.0
; GFX9-NEXT:    v_add_f32_e64 v5, s21, 1.0
; GFX9-NEXT:    v_add_f32_e64 v4, s20, 1.0
; GFX9-NEXT:    v_add_f32_e64 v3, s19, 1.0
; GFX9-NEXT:    v_add_f32_e64 v2, s18, 1.0
; GFX9-NEXT:    v_add_f32_e64 v1, s17, 1.0
; GFX9-NEXT:    v_add_f32_e64 v0, s16, 1.0
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB33_3:
; GFX9-NEXT:    s_branch .LBB33_2
; GFX9-NEXT:  .LBB33_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v8f32_to_v4f64_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s7, s19
; GFX11-NEXT:    s_mov_b32 s6, s18
; GFX11-NEXT:    s_mov_b32 s5, s17
; GFX11-NEXT:    s_mov_b32 s4, s16
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s8, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB33_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-NEXT:    s_cbranch_vccnz .LBB33_4
; GFX11-NEXT:  .LBB33_2: ; %cmp.true
; GFX11-NEXT:    v_add_f32_e64 v7, s7, 1.0
; GFX11-NEXT:    v_add_f32_e64 v6, s6, 1.0
; GFX11-NEXT:    v_add_f32_e64 v5, s5, 1.0
; GFX11-NEXT:    v_add_f32_e64 v4, s4, 1.0
; GFX11-NEXT:    v_add_f32_e64 v3, s3, 1.0
; GFX11-NEXT:    v_add_f32_e64 v2, s2, 1.0
; GFX11-NEXT:    v_add_f32_e64 v1, s1, 1.0
; GFX11-NEXT:    v_add_f32_e64 v0, s0, 1.0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB33_3:
; GFX11-NEXT:    s_branch .LBB33_2
; GFX11-NEXT:  .LBB33_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <8 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <8 x float> %a1 to <4 x double>
  br label %end

cmp.false:
  %a3 = bitcast <8 x float> %a to <4 x double>
  br label %end

end:
  %phi = phi <4 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x double> %phi
}

define <8 x float> @bitcast_v4f64_to_v8f32(<4 x double> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v4f64_to_v8f32:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:  ; %bb.1: ; %cmp.true
; SI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; SI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; SI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; SI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; SI-NEXT:  ; %bb.2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v4f64_to_v8f32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB34_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; VI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; VI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; VI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; VI-NEXT:  .LBB34_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v4f64_to_v8f32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB34_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX9-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX9-NEXT:  .LBB34_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v4f64_to_v8f32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB34_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX11-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX11-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX11-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX11-NEXT:  .LBB34_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <4 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <4 x double> %a1 to <8 x float>
  br label %end

cmp.false:
  %a3 = bitcast <4 x double> %a to <8 x float>
  br label %end

end:
  %phi = phi <8 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x float> %phi
}

define inreg <8 x float> @bitcast_v4f64_to_v8f32_scalar(<4 x double> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v4f64_to_v8f32_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB35_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_cbranch_execnz .LBB35_4
; SI-NEXT:  .LBB35_2: ; %cmp.true
; SI-NEXT:    v_add_f64 v[6:7], s[22:23], 1.0
; SI-NEXT:    v_add_f64 v[4:5], s[20:21], 1.0
; SI-NEXT:    v_add_f64 v[2:3], s[18:19], 1.0
; SI-NEXT:    v_add_f64 v[0:1], s[16:17], 1.0
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB35_3:
; SI-NEXT:    s_branch .LBB35_2
; SI-NEXT:  .LBB35_4:
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v2, s18
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v4, s20
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v6, s22
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v4f64_to_v8f32_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB35_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB35_4
; VI-NEXT:  .LBB35_2: ; %cmp.true
; VI-NEXT:    v_add_f64 v[6:7], s[22:23], 1.0
; VI-NEXT:    v_add_f64 v[4:5], s[20:21], 1.0
; VI-NEXT:    v_add_f64 v[2:3], s[18:19], 1.0
; VI-NEXT:    v_add_f64 v[0:1], s[16:17], 1.0
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB35_3:
; VI-NEXT:    s_branch .LBB35_2
; VI-NEXT:  .LBB35_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v4f64_to_v8f32_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB35_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB35_4
; GFX9-NEXT:  .LBB35_2: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[6:7], s[22:23], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], s[20:21], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], s[18:19], 1.0
; GFX9-NEXT:    v_add_f64 v[0:1], s[16:17], 1.0
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB35_3:
; GFX9-NEXT:    s_branch .LBB35_2
; GFX9-NEXT:  .LBB35_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v4f64_to_v8f32_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s7, s19
; GFX11-NEXT:    s_mov_b32 s6, s18
; GFX11-NEXT:    s_mov_b32 s5, s17
; GFX11-NEXT:    s_mov_b32 s4, s16
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s8, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB35_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-NEXT:    s_cbranch_vccnz .LBB35_4
; GFX11-NEXT:  .LBB35_2: ; %cmp.true
; GFX11-NEXT:    v_add_f64 v[6:7], s[6:7], 1.0
; GFX11-NEXT:    v_add_f64 v[4:5], s[4:5], 1.0
; GFX11-NEXT:    v_add_f64 v[2:3], s[2:3], 1.0
; GFX11-NEXT:    v_add_f64 v[0:1], s[0:1], 1.0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB35_3:
; GFX11-NEXT:    s_branch .LBB35_2
; GFX11-NEXT:  .LBB35_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <4 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <4 x double> %a1 to <8 x float>
  br label %end

cmp.false:
  %a3 = bitcast <4 x double> %a to <8 x float>
  br label %end

end:
  %phi = phi <8 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x float> %phi
}

define <16 x i16> @bitcast_v8f32_to_v16i16(<8 x float> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v8f32_to_v16i16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_alignbit_b32 v8, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v9, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v10, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v13, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v1
; SI-NEXT:  ; %bb.2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB36_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; SI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; SI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; SI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; SI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; SI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; SI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; SI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; SI-NEXT:    v_alignbit_b32 v8, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v9, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v10, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v13, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v1
; SI-NEXT:  .LBB36_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v13
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v10
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_or_b32_e32 v0, v0, v13
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v15
; SI-NEXT:    v_or_b32_e32 v2, v2, v10
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v14
; SI-NEXT:    v_or_b32_e32 v4, v4, v9
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v12
; SI-NEXT:    v_or_b32_e32 v6, v6, v8
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v11
; SI-NEXT:    v_or_b32_e32 v1, v1, v13
; SI-NEXT:    v_or_b32_e32 v3, v3, v10
; SI-NEXT:    v_or_b32_e32 v5, v5, v9
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v8f32_to_v16i16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; VI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; VI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; VI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; VI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; VI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; VI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; VI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; VI-NEXT:  ; %bb.2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v8f32_to_v16i16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e32 v7, 1.0, v7
; GFX9-NEXT:    v_add_f32_e32 v6, 1.0, v6
; GFX9-NEXT:    v_add_f32_e32 v5, 1.0, v5
; GFX9-NEXT:    v_add_f32_e32 v4, 1.0, v4
; GFX9-NEXT:    v_add_f32_e32 v3, 1.0, v3
; GFX9-NEXT:    v_add_f32_e32 v2, 1.0, v2
; GFX9-NEXT:    v_add_f32_e32 v1, 1.0, v1
; GFX9-NEXT:    v_add_f32_e32 v0, 1.0, v0
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v8f32_to_v16i16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_dual_add_f32 v7, 1.0, v7 :: v_dual_add_f32 v6, 1.0, v6
; GFX11-NEXT:    v_dual_add_f32 v5, 1.0, v5 :: v_dual_add_f32 v4, 1.0, v4
; GFX11-NEXT:    v_dual_add_f32 v3, 1.0, v3 :: v_dual_add_f32 v2, 1.0, v2
; GFX11-NEXT:    v_dual_add_f32 v1, 1.0, v1 :: v_dual_add_f32 v0, 1.0, v0
; GFX11-NEXT:  ; %bb.2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <8 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <8 x float> %a1 to <16 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <8 x float> %a to <16 x i16>
  br label %end

end:
  %phi = phi <16 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x i16> %phi
}

define inreg <16 x i16> @bitcast_v8f32_to_v16i16_scalar(<8 x float> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v8f32_to_v16i16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB37_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_lshr_b32 s25, s23, 16
; SI-NEXT:    s_lshr_b32 s24, s21, 16
; SI-NEXT:    s_lshr_b32 s15, s19, 16
; SI-NEXT:    s_lshr_b32 s14, s17, 16
; SI-NEXT:    s_lshr_b64 s[4:5], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[6:7], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[8:9], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[10:11], s[16:17], 16
; SI-NEXT:    s_cbranch_execnz .LBB37_4
; SI-NEXT:  .LBB37_2: ; %cmp.true
; SI-NEXT:    v_add_f32_e64 v7, s23, 1.0
; SI-NEXT:    v_add_f32_e64 v6, s22, 1.0
; SI-NEXT:    v_add_f32_e64 v5, s21, 1.0
; SI-NEXT:    v_add_f32_e64 v4, s20, 1.0
; SI-NEXT:    v_lshr_b64 v[8:9], v[6:7], 16
; SI-NEXT:    v_add_f32_e64 v3, s19, 1.0
; SI-NEXT:    v_add_f32_e64 v2, s18, 1.0
; SI-NEXT:    v_lshr_b64 v[9:10], v[4:5], 16
; SI-NEXT:    v_add_f32_e64 v1, s17, 1.0
; SI-NEXT:    v_add_f32_e64 v0, s16, 1.0
; SI-NEXT:    v_lshr_b64 v[10:11], v[2:3], 16
; SI-NEXT:    v_lshr_b64 v[11:12], v[0:1], 16
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v13, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v1
; SI-NEXT:    s_branch .LBB37_5
; SI-NEXT:  .LBB37_3:
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr8
; SI-NEXT:    ; implicit-def: $sgpr15
; SI-NEXT:    ; implicit-def: $sgpr6
; SI-NEXT:    ; implicit-def: $sgpr24
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr25
; SI-NEXT:    s_branch .LBB37_2
; SI-NEXT:  .LBB37_4:
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v2, s18
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v4, s20
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v6, s22
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    v_mov_b32_e32 v15, s14
; SI-NEXT:    v_mov_b32_e32 v14, s15
; SI-NEXT:    v_mov_b32_e32 v13, s24
; SI-NEXT:    v_mov_b32_e32 v12, s25
; SI-NEXT:    v_mov_b32_e32 v8, s4
; SI-NEXT:    v_mov_b32_e32 v9, s6
; SI-NEXT:    v_mov_b32_e32 v10, s8
; SI-NEXT:    v_mov_b32_e32 v11, s10
; SI-NEXT:  .LBB37_5: ; %end
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v10
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_or_b32_e32 v0, v0, v11
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v15
; SI-NEXT:    v_or_b32_e32 v2, v2, v10
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v14
; SI-NEXT:    v_or_b32_e32 v4, v4, v9
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v13
; SI-NEXT:    v_or_b32_e32 v6, v6, v8
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v12
; SI-NEXT:    v_or_b32_e32 v1, v1, v11
; SI-NEXT:    v_or_b32_e32 v3, v3, v10
; SI-NEXT:    v_or_b32_e32 v5, v5, v9
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v8f32_to_v16i16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB37_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB37_4
; VI-NEXT:  .LBB37_2: ; %cmp.true
; VI-NEXT:    v_add_f32_e64 v7, s23, 1.0
; VI-NEXT:    v_add_f32_e64 v6, s22, 1.0
; VI-NEXT:    v_add_f32_e64 v5, s21, 1.0
; VI-NEXT:    v_add_f32_e64 v4, s20, 1.0
; VI-NEXT:    v_add_f32_e64 v3, s19, 1.0
; VI-NEXT:    v_add_f32_e64 v2, s18, 1.0
; VI-NEXT:    v_add_f32_e64 v1, s17, 1.0
; VI-NEXT:    v_add_f32_e64 v0, s16, 1.0
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB37_3:
; VI-NEXT:    s_branch .LBB37_2
; VI-NEXT:  .LBB37_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v8f32_to_v16i16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB37_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB37_4
; GFX9-NEXT:  .LBB37_2: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e64 v7, s23, 1.0
; GFX9-NEXT:    v_add_f32_e64 v6, s22, 1.0
; GFX9-NEXT:    v_add_f32_e64 v5, s21, 1.0
; GFX9-NEXT:    v_add_f32_e64 v4, s20, 1.0
; GFX9-NEXT:    v_add_f32_e64 v3, s19, 1.0
; GFX9-NEXT:    v_add_f32_e64 v2, s18, 1.0
; GFX9-NEXT:    v_add_f32_e64 v1, s17, 1.0
; GFX9-NEXT:    v_add_f32_e64 v0, s16, 1.0
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB37_3:
; GFX9-NEXT:    s_branch .LBB37_2
; GFX9-NEXT:  .LBB37_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v8f32_to_v16i16_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s7, s19
; GFX11-NEXT:    s_mov_b32 s6, s18
; GFX11-NEXT:    s_mov_b32 s5, s17
; GFX11-NEXT:    s_mov_b32 s4, s16
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s8, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB37_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-NEXT:    s_cbranch_vccnz .LBB37_4
; GFX11-NEXT:  .LBB37_2: ; %cmp.true
; GFX11-NEXT:    v_add_f32_e64 v7, s7, 1.0
; GFX11-NEXT:    v_add_f32_e64 v6, s6, 1.0
; GFX11-NEXT:    v_add_f32_e64 v5, s5, 1.0
; GFX11-NEXT:    v_add_f32_e64 v4, s4, 1.0
; GFX11-NEXT:    v_add_f32_e64 v3, s3, 1.0
; GFX11-NEXT:    v_add_f32_e64 v2, s2, 1.0
; GFX11-NEXT:    v_add_f32_e64 v1, s1, 1.0
; GFX11-NEXT:    v_add_f32_e64 v0, s0, 1.0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB37_3:
; GFX11-NEXT:    s_branch .LBB37_2
; GFX11-NEXT:  .LBB37_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <8 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <8 x float> %a1 to <16 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <8 x float> %a to <16 x i16>
  br label %end

end:
  %phi = phi <16 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x i16> %phi
}

define <8 x float> @bitcast_v16i16_to_v8f32(<16 x i16> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v16i16_to_v8f32:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_mov_b32_e32 v16, v7
; SI-NEXT:    v_mov_b32_e32 v9, v6
; SI-NEXT:    v_mov_b32_e32 v10, v5
; SI-NEXT:    v_mov_b32_e32 v11, v4
; SI-NEXT:    v_mov_b32_e32 v12, v3
; SI-NEXT:    v_mov_b32_e32 v13, v2
; SI-NEXT:    v_mov_b32_e32 v14, v1
; SI-NEXT:    v_mov_b32_e32 v15, v0
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v16
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v10
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v12
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v14
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v15
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v7
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v6
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v5
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v4
; SI-NEXT:    v_lshlrev_b32_e32 v19, 16, v3
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v2
; SI-NEXT:    v_lshlrev_b32_e32 v17, 16, v1
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v0
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB38_3
; SI-NEXT:  ; %bb.1: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB38_4
; SI-NEXT:  .LBB38_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB38_3: ; %cmp.false
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v15
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v14
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v13
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v12
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v11
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v10
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v9
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v16
; SI-NEXT:    v_or_b32_e32 v0, v0, v23
; SI-NEXT:    v_or_b32_e32 v1, v1, v22
; SI-NEXT:    v_or_b32_e32 v2, v2, v21
; SI-NEXT:    v_or_b32_e32 v3, v3, v20
; SI-NEXT:    v_or_b32_e32 v4, v4, v19
; SI-NEXT:    v_or_b32_e32 v5, v5, v18
; SI-NEXT:    v_or_b32_e32 v6, v6, v17
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB38_2
; SI-NEXT:  .LBB38_4: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v15
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v14
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v13
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v12
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v11
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v10
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v9
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v16
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_or_b32_e32 v0, v23, v0
; SI-NEXT:    s_mov_b32 s6, 0x30000
; SI-NEXT:    v_or_b32_e32 v1, v22, v1
; SI-NEXT:    v_or_b32_e32 v2, v21, v2
; SI-NEXT:    v_or_b32_e32 v3, v20, v3
; SI-NEXT:    v_or_b32_e32 v4, v19, v4
; SI-NEXT:    v_or_b32_e32 v5, v18, v5
; SI-NEXT:    v_or_b32_e32 v6, v17, v6
; SI-NEXT:    v_or_b32_e32 v7, v8, v7
; SI-NEXT:    v_add_i32_e32 v0, vcc, 0x30000, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, s6, v1
; SI-NEXT:    v_add_i32_e32 v2, vcc, s6, v2
; SI-NEXT:    v_add_i32_e32 v3, vcc, s6, v3
; SI-NEXT:    v_add_i32_e32 v4, vcc, s6, v4
; SI-NEXT:    v_add_i32_e32 v5, vcc, 0x30000, v5
; SI-NEXT:    v_add_i32_e32 v6, vcc, 0x30000, v6
; SI-NEXT:    v_add_i32_e32 v7, vcc, 0x30000, v7
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16i16_to_v8f32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB38_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v9, 3
; VI-NEXT:    v_add_u16_e32 v8, 3, v7
; VI-NEXT:    v_add_u16_sdwa v7, v7, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v7, v8, v7
; VI-NEXT:    v_add_u16_e32 v8, 3, v6
; VI-NEXT:    v_add_u16_sdwa v6, v6, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v6, v8, v6
; VI-NEXT:    v_add_u16_e32 v8, 3, v5
; VI-NEXT:    v_add_u16_sdwa v5, v5, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v5, v8, v5
; VI-NEXT:    v_add_u16_e32 v8, 3, v4
; VI-NEXT:    v_add_u16_sdwa v4, v4, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v4, v8, v4
; VI-NEXT:    v_add_u16_e32 v8, 3, v3
; VI-NEXT:    v_add_u16_sdwa v3, v3, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v3, v8, v3
; VI-NEXT:    v_add_u16_e32 v8, 3, v2
; VI-NEXT:    v_add_u16_sdwa v2, v2, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v2, v8, v2
; VI-NEXT:    v_add_u16_e32 v8, 3, v1
; VI-NEXT:    v_add_u16_sdwa v1, v1, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v1, v8, v1
; VI-NEXT:    v_add_u16_e32 v8, 3, v0
; VI-NEXT:    v_add_u16_sdwa v0, v0, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v0, v8, v0
; VI-NEXT:  .LBB38_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16i16_to_v8f32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v16i16_to_v8f32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB38_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX11-NEXT:  .LBB38_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <16 x i16> %a, splat (i16 3)
  %a2 = bitcast <16 x i16> %a1 to <8 x float>
  br label %end

cmp.false:
  %a3 = bitcast <16 x i16> %a to <8 x float>
  br label %end

end:
  %phi = phi <8 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x float> %phi
}

define inreg <8 x float> @bitcast_v16i16_to_v8f32_scalar(<16 x i16> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v16i16_to_v8f32_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_lshr_b32 s14, s23, 16
; SI-NEXT:    s_lshr_b32 s15, s22, 16
; SI-NEXT:    s_lshr_b32 s25, s21, 16
; SI-NEXT:    s_lshr_b32 s26, s20, 16
; SI-NEXT:    s_lshr_b32 s27, s19, 16
; SI-NEXT:    s_lshr_b32 s28, s18, 16
; SI-NEXT:    s_lshr_b32 s29, s17, 16
; SI-NEXT:    s_lshr_b32 s40, s16, 16
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB39_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s40, 16
; SI-NEXT:    s_or_b32 s4, s4, s5
; SI-NEXT:    s_and_b32 s5, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s6, s29, 16
; SI-NEXT:    s_or_b32 s5, s5, s6
; SI-NEXT:    s_and_b32 s6, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s28, 16
; SI-NEXT:    s_or_b32 s6, s6, s7
; SI-NEXT:    s_and_b32 s7, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s8, s27, 16
; SI-NEXT:    s_or_b32 s7, s7, s8
; SI-NEXT:    s_and_b32 s8, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s9, s26, 16
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_and_b32 s9, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s25, 16
; SI-NEXT:    s_or_b32 s9, s9, s10
; SI-NEXT:    s_and_b32 s10, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s11, s15, 16
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_and_b32 s11, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s14, 16
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    s_cbranch_execnz .LBB39_3
; SI-NEXT:  .LBB39_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s40, 16
; SI-NEXT:    s_add_i32 s17, s17, 3
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_and_b32 s5, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s6, s29, 16
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_or_b32 s5, s6, s5
; SI-NEXT:    s_and_b32 s6, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s28, 16
; SI-NEXT:    s_add_i32 s19, s19, 3
; SI-NEXT:    s_or_b32 s6, s7, s6
; SI-NEXT:    s_and_b32 s7, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s8, s27, 16
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_or_b32 s7, s8, s7
; SI-NEXT:    s_and_b32 s8, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s9, s26, 16
; SI-NEXT:    s_add_i32 s21, s21, 3
; SI-NEXT:    s_or_b32 s8, s9, s8
; SI-NEXT:    s_and_b32 s9, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s25, 16
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_or_b32 s9, s10, s9
; SI-NEXT:    s_and_b32 s10, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s11, s15, 16
; SI-NEXT:    s_add_i32 s23, s23, 3
; SI-NEXT:    s_or_b32 s10, s11, s10
; SI-NEXT:    s_and_b32 s11, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s14, 16
; SI-NEXT:    s_or_b32 s11, s12, s11
; SI-NEXT:    s_add_i32 s4, s4, 0x30000
; SI-NEXT:    s_add_i32 s5, s5, 0x30000
; SI-NEXT:    s_add_i32 s6, s6, 0x30000
; SI-NEXT:    s_add_i32 s7, s7, 0x30000
; SI-NEXT:    s_add_i32 s8, s8, 0x30000
; SI-NEXT:    s_add_i32 s9, s9, 0x30000
; SI-NEXT:    s_add_i32 s10, s10, 0x30000
; SI-NEXT:    s_add_i32 s11, s11, 0x30000
; SI-NEXT:  .LBB39_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v0, s4
; SI-NEXT:    v_mov_b32_e32 v1, s5
; SI-NEXT:    v_mov_b32_e32 v2, s6
; SI-NEXT:    v_mov_b32_e32 v3, s7
; SI-NEXT:    v_mov_b32_e32 v4, s8
; SI-NEXT:    v_mov_b32_e32 v5, s9
; SI-NEXT:    v_mov_b32_e32 v6, s10
; SI-NEXT:    v_mov_b32_e32 v7, s11
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB39_4:
; SI-NEXT:    ; implicit-def: $sgpr4_sgpr5_sgpr6_sgpr7_sgpr8_sgpr9_sgpr10_sgpr11
; SI-NEXT:    s_branch .LBB39_2
;
; VI-LABEL: bitcast_v16i16_to_v8f32_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB39_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB39_3
; VI-NEXT:  .LBB39_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s5, s23, 3
; VI-NEXT:    s_and_b32 s4, s23, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s22, 3
; VI-NEXT:    s_add_i32 s23, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s22, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s21, 3
; VI-NEXT:    s_add_i32 s22, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s21, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s20, 3
; VI-NEXT:    s_add_i32 s21, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s20, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s19, 3
; VI-NEXT:    s_add_i32 s20, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s19, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s18, 3
; VI-NEXT:    s_add_i32 s19, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s18, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s17, 3
; VI-NEXT:    s_add_i32 s18, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s17, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s16, 3
; VI-NEXT:    s_add_i32 s17, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s16, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s16, s4, 0x30000
; VI-NEXT:  .LBB39_3: ; %end
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB39_4:
; VI-NEXT:    s_branch .LBB39_2
;
; GFX9-LABEL: bitcast_v16i16_to_v8f32_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB39_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB39_4
; GFX9-NEXT:  .LBB39_2: ; %cmp.true
; GFX9-NEXT:    v_pk_add_u16 v7, s23, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, s22, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v5, s21, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v4, s20, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v3, s19, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v2, s18, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v1, s17, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v0, s16, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB39_3:
; GFX9-NEXT:    s_branch .LBB39_2
; GFX9-NEXT:  .LBB39_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v16i16_to_v8f32_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s7, s19
; GFX11-NEXT:    s_mov_b32 s6, s18
; GFX11-NEXT:    s_mov_b32 s5, s17
; GFX11-NEXT:    s_mov_b32 s4, s16
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s8, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB39_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-NEXT:    s_cbranch_vccnz .LBB39_4
; GFX11-NEXT:  .LBB39_2: ; %cmp.true
; GFX11-NEXT:    v_pk_add_u16 v7, s7, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v6, s6, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v5, s5, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v4, s4, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v3, s3, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v2, s2, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v1, s1, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v0, s0, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB39_3:
; GFX11-NEXT:    s_branch .LBB39_2
; GFX11-NEXT:  .LBB39_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <16 x i16> %a, splat (i16 3)
  %a2 = bitcast <16 x i16> %a1 to <8 x float>
  br label %end

cmp.false:
  %a3 = bitcast <16 x i16> %a to <8 x float>
  br label %end

end:
  %phi = phi <8 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x float> %phi
}

define <16 x half> @bitcast_v8f32_to_v16f16(<8 x float> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v8f32_to_v16f16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_alignbit_b32 v8, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v9, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v10, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v13, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v1
; SI-NEXT:  ; %bb.2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB40_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; SI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; SI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; SI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; SI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; SI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; SI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; SI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; SI-NEXT:    v_alignbit_b32 v8, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v9, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v10, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v13, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v1
; SI-NEXT:  .LBB40_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v13
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v10
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_or_b32_e32 v0, v0, v13
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v15
; SI-NEXT:    v_or_b32_e32 v2, v2, v10
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v14
; SI-NEXT:    v_or_b32_e32 v4, v4, v9
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v12
; SI-NEXT:    v_or_b32_e32 v6, v6, v8
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v11
; SI-NEXT:    v_or_b32_e32 v1, v1, v13
; SI-NEXT:    v_or_b32_e32 v3, v3, v10
; SI-NEXT:    v_or_b32_e32 v5, v5, v9
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v8f32_to_v16f16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; VI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; VI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; VI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; VI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; VI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; VI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; VI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; VI-NEXT:  ; %bb.2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v8f32_to_v16f16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e32 v7, 1.0, v7
; GFX9-NEXT:    v_add_f32_e32 v6, 1.0, v6
; GFX9-NEXT:    v_add_f32_e32 v5, 1.0, v5
; GFX9-NEXT:    v_add_f32_e32 v4, 1.0, v4
; GFX9-NEXT:    v_add_f32_e32 v3, 1.0, v3
; GFX9-NEXT:    v_add_f32_e32 v2, 1.0, v2
; GFX9-NEXT:    v_add_f32_e32 v1, 1.0, v1
; GFX9-NEXT:    v_add_f32_e32 v0, 1.0, v0
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v8f32_to_v16f16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_dual_add_f32 v7, 1.0, v7 :: v_dual_add_f32 v6, 1.0, v6
; GFX11-NEXT:    v_dual_add_f32 v5, 1.0, v5 :: v_dual_add_f32 v4, 1.0, v4
; GFX11-NEXT:    v_dual_add_f32 v3, 1.0, v3 :: v_dual_add_f32 v2, 1.0, v2
; GFX11-NEXT:    v_dual_add_f32 v1, 1.0, v1 :: v_dual_add_f32 v0, 1.0, v0
; GFX11-NEXT:  ; %bb.2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <8 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <8 x float> %a1 to <16 x half>
  br label %end

cmp.false:
  %a3 = bitcast <8 x float> %a to <16 x half>
  br label %end

end:
  %phi = phi <16 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x half> %phi
}

define inreg <16 x half> @bitcast_v8f32_to_v16f16_scalar(<8 x float> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v8f32_to_v16f16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB41_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_lshr_b32 s25, s23, 16
; SI-NEXT:    s_lshr_b32 s24, s21, 16
; SI-NEXT:    s_lshr_b32 s15, s19, 16
; SI-NEXT:    s_lshr_b32 s14, s17, 16
; SI-NEXT:    s_lshr_b64 s[4:5], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[6:7], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[8:9], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[10:11], s[16:17], 16
; SI-NEXT:    s_cbranch_execnz .LBB41_4
; SI-NEXT:  .LBB41_2: ; %cmp.true
; SI-NEXT:    v_add_f32_e64 v7, s23, 1.0
; SI-NEXT:    v_add_f32_e64 v6, s22, 1.0
; SI-NEXT:    v_add_f32_e64 v5, s21, 1.0
; SI-NEXT:    v_add_f32_e64 v4, s20, 1.0
; SI-NEXT:    v_lshr_b64 v[8:9], v[6:7], 16
; SI-NEXT:    v_add_f32_e64 v3, s19, 1.0
; SI-NEXT:    v_add_f32_e64 v2, s18, 1.0
; SI-NEXT:    v_lshr_b64 v[9:10], v[4:5], 16
; SI-NEXT:    v_add_f32_e64 v1, s17, 1.0
; SI-NEXT:    v_add_f32_e64 v0, s16, 1.0
; SI-NEXT:    v_lshr_b64 v[10:11], v[2:3], 16
; SI-NEXT:    v_lshr_b64 v[11:12], v[0:1], 16
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v13, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v1
; SI-NEXT:    s_branch .LBB41_5
; SI-NEXT:  .LBB41_3:
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr8
; SI-NEXT:    ; implicit-def: $sgpr15
; SI-NEXT:    ; implicit-def: $sgpr6
; SI-NEXT:    ; implicit-def: $sgpr24
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr25
; SI-NEXT:    s_branch .LBB41_2
; SI-NEXT:  .LBB41_4:
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v2, s18
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v4, s20
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v6, s22
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    v_mov_b32_e32 v15, s14
; SI-NEXT:    v_mov_b32_e32 v14, s15
; SI-NEXT:    v_mov_b32_e32 v13, s24
; SI-NEXT:    v_mov_b32_e32 v12, s25
; SI-NEXT:    v_mov_b32_e32 v8, s4
; SI-NEXT:    v_mov_b32_e32 v9, s6
; SI-NEXT:    v_mov_b32_e32 v10, s8
; SI-NEXT:    v_mov_b32_e32 v11, s10
; SI-NEXT:  .LBB41_5: ; %end
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v10
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_or_b32_e32 v0, v0, v11
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v15
; SI-NEXT:    v_or_b32_e32 v2, v2, v10
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v14
; SI-NEXT:    v_or_b32_e32 v4, v4, v9
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v13
; SI-NEXT:    v_or_b32_e32 v6, v6, v8
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v12
; SI-NEXT:    v_or_b32_e32 v1, v1, v11
; SI-NEXT:    v_or_b32_e32 v3, v3, v10
; SI-NEXT:    v_or_b32_e32 v5, v5, v9
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v8f32_to_v16f16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB41_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB41_4
; VI-NEXT:  .LBB41_2: ; %cmp.true
; VI-NEXT:    v_add_f32_e64 v7, s23, 1.0
; VI-NEXT:    v_add_f32_e64 v6, s22, 1.0
; VI-NEXT:    v_add_f32_e64 v5, s21, 1.0
; VI-NEXT:    v_add_f32_e64 v4, s20, 1.0
; VI-NEXT:    v_add_f32_e64 v3, s19, 1.0
; VI-NEXT:    v_add_f32_e64 v2, s18, 1.0
; VI-NEXT:    v_add_f32_e64 v1, s17, 1.0
; VI-NEXT:    v_add_f32_e64 v0, s16, 1.0
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB41_3:
; VI-NEXT:    s_branch .LBB41_2
; VI-NEXT:  .LBB41_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v8f32_to_v16f16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB41_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB41_4
; GFX9-NEXT:  .LBB41_2: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e64 v7, s23, 1.0
; GFX9-NEXT:    v_add_f32_e64 v6, s22, 1.0
; GFX9-NEXT:    v_add_f32_e64 v5, s21, 1.0
; GFX9-NEXT:    v_add_f32_e64 v4, s20, 1.0
; GFX9-NEXT:    v_add_f32_e64 v3, s19, 1.0
; GFX9-NEXT:    v_add_f32_e64 v2, s18, 1.0
; GFX9-NEXT:    v_add_f32_e64 v1, s17, 1.0
; GFX9-NEXT:    v_add_f32_e64 v0, s16, 1.0
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB41_3:
; GFX9-NEXT:    s_branch .LBB41_2
; GFX9-NEXT:  .LBB41_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v8f32_to_v16f16_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s7, s19
; GFX11-NEXT:    s_mov_b32 s6, s18
; GFX11-NEXT:    s_mov_b32 s5, s17
; GFX11-NEXT:    s_mov_b32 s4, s16
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s8, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB41_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-NEXT:    s_cbranch_vccnz .LBB41_4
; GFX11-NEXT:  .LBB41_2: ; %cmp.true
; GFX11-NEXT:    v_add_f32_e64 v7, s7, 1.0
; GFX11-NEXT:    v_add_f32_e64 v6, s6, 1.0
; GFX11-NEXT:    v_add_f32_e64 v5, s5, 1.0
; GFX11-NEXT:    v_add_f32_e64 v4, s4, 1.0
; GFX11-NEXT:    v_add_f32_e64 v3, s3, 1.0
; GFX11-NEXT:    v_add_f32_e64 v2, s2, 1.0
; GFX11-NEXT:    v_add_f32_e64 v1, s1, 1.0
; GFX11-NEXT:    v_add_f32_e64 v0, s0, 1.0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB41_3:
; GFX11-NEXT:    s_branch .LBB41_2
; GFX11-NEXT:  .LBB41_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <8 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <8 x float> %a1 to <16 x half>
  br label %end

cmp.false:
  %a3 = bitcast <8 x float> %a to <16 x half>
  br label %end

end:
  %phi = phi <16 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x half> %phi
}

define <8 x float> @bitcast_v16f16_to_v8f32(<16 x half> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v16f16_to_v8f32:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_mov_b32_e32 v16, v7
; SI-NEXT:    v_mov_b32_e32 v9, v6
; SI-NEXT:    v_mov_b32_e32 v10, v5
; SI-NEXT:    v_mov_b32_e32 v11, v4
; SI-NEXT:    v_mov_b32_e32 v12, v3
; SI-NEXT:    v_mov_b32_e32 v13, v2
; SI-NEXT:    v_mov_b32_e32 v14, v1
; SI-NEXT:    v_mov_b32_e32 v15, v0
; SI-NEXT:    v_lshrrev_b32_e32 v17, 16, v16
; SI-NEXT:    v_lshrrev_b32_e32 v18, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v19, 16, v10
; SI-NEXT:    v_lshrrev_b32_e32 v20, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v21, 16, v12
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v23, 16, v14
; SI-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB42_3
; SI-NEXT:  ; %bb.1: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB42_4
; SI-NEXT:  .LBB42_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB42_3: ; %cmp.false
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v15
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v24
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v14
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v23
; SI-NEXT:    v_or_b32_e32 v0, v0, v1
; SI-NEXT:    v_or_b32_e32 v1, v2, v3
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v13
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v22
; SI-NEXT:    v_or_b32_e32 v2, v2, v3
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v12
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v21
; SI-NEXT:    v_or_b32_e32 v3, v3, v4
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v11
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v20
; SI-NEXT:    v_or_b32_e32 v4, v4, v5
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v10
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v19
; SI-NEXT:    v_or_b32_e32 v5, v5, v6
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v9
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v18
; SI-NEXT:    v_or_b32_e32 v6, v6, v7
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v16
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v17
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr24
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB42_2
; SI-NEXT:  .LBB42_4: ; %cmp.true
; SI-NEXT:    v_cvt_f32_f16_e32 v0, v24
; SI-NEXT:    v_cvt_f32_f16_e32 v2, v23
; SI-NEXT:    v_cvt_f32_f16_e32 v1, v15
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v14
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_or_b32_e32 v0, v1, v0
; SI-NEXT:    v_or_b32_e32 v1, v3, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v2, v22
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v13
; SI-NEXT:    v_cvt_f32_f16_e32 v4, v21
; SI-NEXT:    v_cvt_f32_f16_e32 v5, v20
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_or_b32_e32 v2, v3, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v12
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v6, v11
; SI-NEXT:    v_cvt_f32_f16_e32 v7, v10
; SI-NEXT:    v_cvt_f32_f16_e32 v8, v17
; SI-NEXT:    v_or_b32_e32 v3, v3, v4
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v5, v19
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_or_b32_e32 v4, v6, v4
; SI-NEXT:    v_cvt_f32_f16_e32 v6, v18
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_or_b32_e32 v5, v7, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v7, v9
; SI-NEXT:    v_cvt_f32_f16_e32 v9, v16
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v8, v8
; SI-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v9
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_or_b32_e32 v6, v7, v6
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v8
; SI-NEXT:    v_or_b32_e32 v7, v9, v7
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16f16_to_v8f32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB42_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v8, 0x200
; VI-NEXT:    v_add_f16_sdwa v9, v7, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v7, 0x200, v7
; VI-NEXT:    v_or_b32_e32 v7, v7, v9
; VI-NEXT:    v_add_f16_sdwa v9, v6, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v6, 0x200, v6
; VI-NEXT:    v_or_b32_e32 v6, v6, v9
; VI-NEXT:    v_add_f16_sdwa v9, v5, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v5, 0x200, v5
; VI-NEXT:    v_or_b32_e32 v5, v5, v9
; VI-NEXT:    v_add_f16_sdwa v9, v4, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v4, 0x200, v4
; VI-NEXT:    v_or_b32_e32 v4, v4, v9
; VI-NEXT:    v_add_f16_sdwa v9, v3, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v3, 0x200, v3
; VI-NEXT:    v_or_b32_e32 v3, v3, v9
; VI-NEXT:    v_add_f16_sdwa v9, v2, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, 0x200, v2
; VI-NEXT:    v_or_b32_e32 v2, v2, v9
; VI-NEXT:    v_add_f16_sdwa v9, v1, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v1, 0x200, v1
; VI-NEXT:    v_add_f16_sdwa v8, v0, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v0, 0x200, v0
; VI-NEXT:    v_or_b32_e32 v1, v1, v9
; VI-NEXT:    v_or_b32_e32 v0, v0, v8
; VI-NEXT:  .LBB42_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16f16_to_v8f32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    s_movk_i32 s6, 0x200
; GFX9-NEXT:    v_pk_add_f16 v7, v7, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, v6, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v5, v5, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v4, v4, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v3, v3, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v2, v2, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v1, v1, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v0, v0, s6 op_sel_hi:[1,0]
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v16f16_to_v8f32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB42_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_pk_add_f16 v7, 0x200, v7 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v6, 0x200, v6 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v5, 0x200, v5 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v4, 0x200, v4 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v3, 0x200, v3 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v2, 0x200, v2 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v1, 0x200, v1 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v0, 0x200, v0 op_sel_hi:[0,1]
; GFX11-NEXT:  .LBB42_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <16 x half> %a1 to <8 x float>
  br label %end

cmp.false:
  %a3 = bitcast <16 x half> %a to <8 x float>
  br label %end

end:
  %phi = phi <8 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x float> %phi
}

define inreg <8 x float> @bitcast_v16f16_to_v8f32_scalar(<16 x half> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v16f16_to_v8f32_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_lshr_b32 s14, s23, 16
; SI-NEXT:    s_lshr_b32 s15, s22, 16
; SI-NEXT:    s_lshr_b32 s25, s21, 16
; SI-NEXT:    s_lshr_b32 s26, s20, 16
; SI-NEXT:    s_lshr_b32 s27, s19, 16
; SI-NEXT:    s_lshr_b32 s28, s18, 16
; SI-NEXT:    s_lshr_b32 s29, s17, 16
; SI-NEXT:    s_lshr_b32 s40, s16, 16
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB43_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s40, 16
; SI-NEXT:    s_or_b32 s4, s4, s5
; SI-NEXT:    s_and_b32 s5, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s6, s29, 16
; SI-NEXT:    s_or_b32 s5, s5, s6
; SI-NEXT:    s_and_b32 s6, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s28, 16
; SI-NEXT:    s_or_b32 s6, s6, s7
; SI-NEXT:    s_and_b32 s7, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s8, s27, 16
; SI-NEXT:    s_or_b32 s7, s7, s8
; SI-NEXT:    s_and_b32 s8, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s9, s26, 16
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_and_b32 s9, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s25, 16
; SI-NEXT:    s_or_b32 s9, s9, s10
; SI-NEXT:    s_and_b32 s10, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s11, s15, 16
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_and_b32 s11, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s14, 16
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    s_cbranch_execnz .LBB43_4
; SI-NEXT:  .LBB43_2: ; %cmp.true
; SI-NEXT:    v_cvt_f32_f16_e32 v0, s40
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s16
; SI-NEXT:    v_cvt_f32_f16_e32 v2, s29
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s17
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_cvt_f32_f16_e32 v4, s18
; SI-NEXT:    v_or_b32_e32 v0, v1, v0
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v2, s28
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_or_b32_e32 v1, v3, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s27
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_or_b32_e32 v2, v4, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v4, s19
; SI-NEXT:    v_cvt_f32_f16_e32 v5, s26
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v6, s20
; SI-NEXT:    v_or_b32_e32 v3, v4, v3
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v5, s25
; SI-NEXT:    v_cvt_f32_f16_e32 v7, s21
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_or_b32_e32 v4, v6, v4
; SI-NEXT:    v_cvt_f32_f16_e32 v6, s15
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_or_b32_e32 v5, v7, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v7, s22
; SI-NEXT:    v_cvt_f32_f16_e32 v8, s14
; SI-NEXT:    v_cvt_f32_f16_e32 v9, s23
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v8, v8
; SI-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v9
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_or_b32_e32 v6, v7, v6
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v8
; SI-NEXT:    v_or_b32_e32 v7, v9, v7
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB43_3:
; SI-NEXT:    ; implicit-def: $sgpr4_sgpr5_sgpr6_sgpr7_sgpr8_sgpr9_sgpr10_sgpr11
; SI-NEXT:    s_branch .LBB43_2
; SI-NEXT:  .LBB43_4:
; SI-NEXT:    v_mov_b32_e32 v0, s4
; SI-NEXT:    v_mov_b32_e32 v1, s5
; SI-NEXT:    v_mov_b32_e32 v2, s6
; SI-NEXT:    v_mov_b32_e32 v3, s7
; SI-NEXT:    v_mov_b32_e32 v4, s8
; SI-NEXT:    v_mov_b32_e32 v5, s9
; SI-NEXT:    v_mov_b32_e32 v6, s10
; SI-NEXT:    v_mov_b32_e32 v7, s11
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16f16_to_v8f32_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB43_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB43_4
; VI-NEXT:  .LBB43_2: ; %cmp.true
; VI-NEXT:    s_lshr_b32 s4, s23, 16
; VI-NEXT:    v_mov_b32_e32 v0, 0x200
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, s23, v0
; VI-NEXT:    s_lshr_b32 s4, s22, 16
; VI-NEXT:    v_or_b32_e32 v7, v2, v1
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, s22, v0
; VI-NEXT:    s_lshr_b32 s4, s21, 16
; VI-NEXT:    v_or_b32_e32 v6, v2, v1
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, s21, v0
; VI-NEXT:    s_lshr_b32 s4, s20, 16
; VI-NEXT:    v_or_b32_e32 v5, v2, v1
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, s20, v0
; VI-NEXT:    s_lshr_b32 s4, s19, 16
; VI-NEXT:    v_or_b32_e32 v4, v2, v1
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, s19, v0
; VI-NEXT:    s_lshr_b32 s4, s18, 16
; VI-NEXT:    v_or_b32_e32 v3, v2, v1
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, s18, v0
; VI-NEXT:    s_lshr_b32 s4, s17, 16
; VI-NEXT:    v_or_b32_e32 v2, v2, v1
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v8, s17, v0
; VI-NEXT:    s_lshr_b32 s4, s16, 16
; VI-NEXT:    v_or_b32_e32 v1, v8, v1
; VI-NEXT:    v_mov_b32_e32 v8, s4
; VI-NEXT:    v_add_f16_sdwa v8, v8, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v0, s16, v0
; VI-NEXT:    v_or_b32_e32 v0, v0, v8
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB43_3:
; VI-NEXT:    s_branch .LBB43_2
; VI-NEXT:  .LBB43_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16f16_to_v8f32_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB43_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB43_4
; GFX9-NEXT:  .LBB43_2: ; %cmp.true
; GFX9-NEXT:    v_mov_b32_e32 v0, 0x200
; GFX9-NEXT:    v_pk_add_f16 v7, s23, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, s22, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v5, s21, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v4, s20, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v3, s19, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v2, s18, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v1, s17, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v0, s16, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB43_3:
; GFX9-NEXT:    s_branch .LBB43_2
; GFX9-NEXT:  .LBB43_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v16f16_to_v8f32_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s7, s19
; GFX11-NEXT:    s_mov_b32 s6, s18
; GFX11-NEXT:    s_mov_b32 s5, s17
; GFX11-NEXT:    s_mov_b32 s4, s16
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s8, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB43_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-NEXT:    s_cbranch_vccnz .LBB43_4
; GFX11-NEXT:  .LBB43_2: ; %cmp.true
; GFX11-NEXT:    v_pk_add_f16 v7, 0x200, s7 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v6, 0x200, s6 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v5, 0x200, s5 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v4, 0x200, s4 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v3, 0x200, s3 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v2, 0x200, s2 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v1, 0x200, s1 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v0, 0x200, s0 op_sel_hi:[0,1]
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB43_3:
; GFX11-NEXT:    s_branch .LBB43_2
; GFX11-NEXT:  .LBB43_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <16 x half> %a1 to <8 x float>
  br label %end

cmp.false:
  %a3 = bitcast <16 x half> %a to <8 x float>
  br label %end

end:
  %phi = phi <8 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x float> %phi
}

define <16 x bfloat> @bitcast_v8f32_to_v16bf16(<8 x float> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v8f32_to_v16bf16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB44_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_and_b32_e32 v9, 0xffff0000, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v7
; SI-NEXT:    v_and_b32_e32 v11, 0xffff0000, v6
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v6
; SI-NEXT:    v_and_b32_e32 v13, 0xffff0000, v5
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v5
; SI-NEXT:    v_and_b32_e32 v15, 0xffff0000, v4
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v4
; SI-NEXT:    v_and_b32_e32 v17, 0xffff0000, v3
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v3
; SI-NEXT:    v_and_b32_e32 v19, 0xffff0000, v2
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v2
; SI-NEXT:    v_and_b32_e32 v21, 0xffff0000, v1
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v1
; SI-NEXT:    v_and_b32_e32 v23, 0xffff0000, v0
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v0
; SI-NEXT:    ; implicit-def: $vgpr0
; SI-NEXT:    ; implicit-def: $vgpr1
; SI-NEXT:    ; implicit-def: $vgpr2
; SI-NEXT:    ; implicit-def: $vgpr3
; SI-NEXT:    ; implicit-def: $vgpr4
; SI-NEXT:    ; implicit-def: $vgpr5
; SI-NEXT:    ; implicit-def: $vgpr6
; SI-NEXT:    ; implicit-def: $vgpr7
; SI-NEXT:  .LBB44_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB44_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; SI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; SI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; SI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; SI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; SI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; SI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; SI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; SI-NEXT:    v_and_b32_e32 v9, 0xffff0000, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v7
; SI-NEXT:    v_and_b32_e32 v11, 0xffff0000, v6
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v6
; SI-NEXT:    v_and_b32_e32 v13, 0xffff0000, v5
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v5
; SI-NEXT:    v_and_b32_e32 v15, 0xffff0000, v4
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v4
; SI-NEXT:    v_and_b32_e32 v17, 0xffff0000, v3
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v3
; SI-NEXT:    v_and_b32_e32 v19, 0xffff0000, v2
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v2
; SI-NEXT:    v_and_b32_e32 v21, 0xffff0000, v1
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v1
; SI-NEXT:    v_and_b32_e32 v23, 0xffff0000, v0
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v0
; SI-NEXT:  .LBB44_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_mul_f32_e32 v0, 1.0, v23
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_mul_f32_e32 v1, 1.0, v22
; SI-NEXT:    v_alignbit_b32 v0, v0, v1, 16
; SI-NEXT:    v_mul_f32_e32 v1, 1.0, v21
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_mul_f32_e32 v2, 1.0, v20
; SI-NEXT:    v_alignbit_b32 v1, v1, v2, 16
; SI-NEXT:    v_mul_f32_e32 v2, 1.0, v19
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_mul_f32_e32 v3, 1.0, v18
; SI-NEXT:    v_alignbit_b32 v2, v2, v3, 16
; SI-NEXT:    v_mul_f32_e32 v3, 1.0, v17
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_mul_f32_e32 v4, 1.0, v16
; SI-NEXT:    v_alignbit_b32 v3, v3, v4, 16
; SI-NEXT:    v_mul_f32_e32 v4, 1.0, v15
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_mul_f32_e32 v5, 1.0, v14
; SI-NEXT:    v_alignbit_b32 v4, v4, v5, 16
; SI-NEXT:    v_mul_f32_e32 v5, 1.0, v13
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_mul_f32_e32 v6, 1.0, v12
; SI-NEXT:    v_alignbit_b32 v5, v5, v6, 16
; SI-NEXT:    v_mul_f32_e32 v6, 1.0, v11
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_mul_f32_e32 v7, 1.0, v10
; SI-NEXT:    v_alignbit_b32 v6, v6, v7, 16
; SI-NEXT:    v_mul_f32_e32 v7, 1.0, v9
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_mul_f32_e32 v8, 1.0, v8
; SI-NEXT:    v_alignbit_b32 v7, v7, v8, 16
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v8f32_to_v16bf16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; VI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; VI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; VI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; VI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; VI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; VI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; VI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; VI-NEXT:  ; %bb.2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v8f32_to_v16bf16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e32 v7, 1.0, v7
; GFX9-NEXT:    v_add_f32_e32 v6, 1.0, v6
; GFX9-NEXT:    v_add_f32_e32 v5, 1.0, v5
; GFX9-NEXT:    v_add_f32_e32 v4, 1.0, v4
; GFX9-NEXT:    v_add_f32_e32 v3, 1.0, v3
; GFX9-NEXT:    v_add_f32_e32 v2, 1.0, v2
; GFX9-NEXT:    v_add_f32_e32 v1, 1.0, v1
; GFX9-NEXT:    v_add_f32_e32 v0, 1.0, v0
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v8f32_to_v16bf16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_dual_add_f32 v7, 1.0, v7 :: v_dual_add_f32 v6, 1.0, v6
; GFX11-NEXT:    v_dual_add_f32 v5, 1.0, v5 :: v_dual_add_f32 v4, 1.0, v4
; GFX11-NEXT:    v_dual_add_f32 v3, 1.0, v3 :: v_dual_add_f32 v2, 1.0, v2
; GFX11-NEXT:    v_dual_add_f32 v1, 1.0, v1 :: v_dual_add_f32 v0, 1.0, v0
; GFX11-NEXT:  ; %bb.2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <8 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <8 x float> %a1 to <16 x bfloat>
  br label %end

cmp.false:
  %a3 = bitcast <8 x float> %a to <16 x bfloat>
  br label %end

end:
  %phi = phi <16 x bfloat> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x bfloat> %phi
}

define inreg <16 x bfloat> @bitcast_v8f32_to_v16bf16_scalar(<8 x float> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v8f32_to_v16bf16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB45_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s6, s23, 0xffff0000
; SI-NEXT:    s_lshl_b32 s7, s23, 16
; SI-NEXT:    s_and_b32 s8, s22, 0xffff0000
; SI-NEXT:    s_lshl_b32 s9, s22, 16
; SI-NEXT:    s_and_b32 s10, s21, 0xffff0000
; SI-NEXT:    s_lshl_b32 s11, s21, 16
; SI-NEXT:    s_and_b32 s12, s20, 0xffff0000
; SI-NEXT:    s_lshl_b32 s13, s20, 16
; SI-NEXT:    s_and_b32 s14, s19, 0xffff0000
; SI-NEXT:    s_lshl_b32 s15, s19, 16
; SI-NEXT:    s_and_b32 s24, s18, 0xffff0000
; SI-NEXT:    s_lshl_b32 s25, s18, 16
; SI-NEXT:    s_and_b32 s26, s17, 0xffff0000
; SI-NEXT:    s_lshl_b32 s27, s17, 16
; SI-NEXT:    s_and_b32 s28, s16, 0xffff0000
; SI-NEXT:    s_lshl_b32 s29, s16, 16
; SI-NEXT:    s_cbranch_execnz .LBB45_4
; SI-NEXT:  .LBB45_2: ; %cmp.true
; SI-NEXT:    v_add_f32_e64 v0, s16, 1.0
; SI-NEXT:    v_add_f32_e64 v1, s17, 1.0
; SI-NEXT:    v_add_f32_e64 v2, s18, 1.0
; SI-NEXT:    v_add_f32_e64 v3, s19, 1.0
; SI-NEXT:    v_add_f32_e64 v4, s20, 1.0
; SI-NEXT:    v_add_f32_e64 v5, s21, 1.0
; SI-NEXT:    v_add_f32_e64 v6, s22, 1.0
; SI-NEXT:    v_add_f32_e64 v7, s23, 1.0
; SI-NEXT:    v_and_b32_e32 v9, 0xffff0000, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v7
; SI-NEXT:    v_and_b32_e32 v10, 0xffff0000, v6
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v6
; SI-NEXT:    v_and_b32_e32 v11, 0xffff0000, v5
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v5
; SI-NEXT:    v_and_b32_e32 v12, 0xffff0000, v4
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v4
; SI-NEXT:    v_and_b32_e32 v13, 0xffff0000, v3
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v3
; SI-NEXT:    v_and_b32_e32 v14, 0xffff0000, v2
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v2
; SI-NEXT:    v_and_b32_e32 v15, 0xffff0000, v1
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v1
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v0
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    s_branch .LBB45_5
; SI-NEXT:  .LBB45_3:
; SI-NEXT:    ; implicit-def: $sgpr29
; SI-NEXT:    ; implicit-def: $sgpr28
; SI-NEXT:    ; implicit-def: $sgpr27
; SI-NEXT:    ; implicit-def: $sgpr26
; SI-NEXT:    ; implicit-def: $sgpr25
; SI-NEXT:    ; implicit-def: $sgpr24
; SI-NEXT:    ; implicit-def: $sgpr15
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr13
; SI-NEXT:    ; implicit-def: $sgpr12
; SI-NEXT:    ; implicit-def: $sgpr11
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr9
; SI-NEXT:    ; implicit-def: $sgpr8
; SI-NEXT:    ; implicit-def: $sgpr7
; SI-NEXT:    ; implicit-def: $sgpr6
; SI-NEXT:    s_branch .LBB45_2
; SI-NEXT:  .LBB45_4:
; SI-NEXT:    v_mov_b32_e32 v0, s29
; SI-NEXT:    v_mov_b32_e32 v1, s28
; SI-NEXT:    v_mov_b32_e32 v2, s27
; SI-NEXT:    v_mov_b32_e32 v15, s26
; SI-NEXT:    v_mov_b32_e32 v3, s25
; SI-NEXT:    v_mov_b32_e32 v14, s24
; SI-NEXT:    v_mov_b32_e32 v4, s15
; SI-NEXT:    v_mov_b32_e32 v13, s14
; SI-NEXT:    v_mov_b32_e32 v5, s13
; SI-NEXT:    v_mov_b32_e32 v12, s12
; SI-NEXT:    v_mov_b32_e32 v6, s11
; SI-NEXT:    v_mov_b32_e32 v11, s10
; SI-NEXT:    v_mov_b32_e32 v7, s9
; SI-NEXT:    v_mov_b32_e32 v10, s8
; SI-NEXT:    v_mov_b32_e32 v8, s7
; SI-NEXT:    v_mov_b32_e32 v9, s6
; SI-NEXT:  .LBB45_5: ; %end
; SI-NEXT:    v_mul_f32_e32 v1, 1.0, v1
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_mul_f32_e32 v0, 1.0, v0
; SI-NEXT:    v_lshr_b64 v[0:1], v[0:1], 16
; SI-NEXT:    v_mul_f32_e32 v1, 1.0, v15
; SI-NEXT:    v_lshrrev_b32_e32 v16, 16, v1
; SI-NEXT:    v_mul_f32_e32 v15, 1.0, v2
; SI-NEXT:    v_lshr_b64 v[1:2], v[15:16], 16
; SI-NEXT:    v_mul_f32_e32 v2, 1.0, v14
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v2
; SI-NEXT:    v_mul_f32_e32 v14, 1.0, v3
; SI-NEXT:    v_lshr_b64 v[2:3], v[14:15], 16
; SI-NEXT:    v_mul_f32_e32 v3, 1.0, v13
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; SI-NEXT:    v_mul_f32_e32 v13, 1.0, v4
; SI-NEXT:    v_lshr_b64 v[3:4], v[13:14], 16
; SI-NEXT:    v_mul_f32_e32 v4, 1.0, v12
; SI-NEXT:    v_lshrrev_b32_e32 v13, 16, v4
; SI-NEXT:    v_mul_f32_e32 v12, 1.0, v5
; SI-NEXT:    v_lshr_b64 v[4:5], v[12:13], 16
; SI-NEXT:    v_mul_f32_e32 v5, 1.0, v11
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v5
; SI-NEXT:    v_mul_f32_e32 v11, 1.0, v6
; SI-NEXT:    v_lshr_b64 v[5:6], v[11:12], 16
; SI-NEXT:    v_mul_f32_e32 v6, 1.0, v10
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v6
; SI-NEXT:    v_mul_f32_e32 v10, 1.0, v7
; SI-NEXT:    v_lshr_b64 v[6:7], v[10:11], 16
; SI-NEXT:    v_mul_f32_e32 v7, 1.0, v9
; SI-NEXT:    v_lshrrev_b32_e32 v9, 16, v7
; SI-NEXT:    v_mul_f32_e32 v8, 1.0, v8
; SI-NEXT:    v_lshr_b64 v[7:8], v[8:9], 16
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v8f32_to_v16bf16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB45_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB45_4
; VI-NEXT:  .LBB45_2: ; %cmp.true
; VI-NEXT:    v_add_f32_e64 v7, s23, 1.0
; VI-NEXT:    v_add_f32_e64 v6, s22, 1.0
; VI-NEXT:    v_add_f32_e64 v5, s21, 1.0
; VI-NEXT:    v_add_f32_e64 v4, s20, 1.0
; VI-NEXT:    v_add_f32_e64 v3, s19, 1.0
; VI-NEXT:    v_add_f32_e64 v2, s18, 1.0
; VI-NEXT:    v_add_f32_e64 v1, s17, 1.0
; VI-NEXT:    v_add_f32_e64 v0, s16, 1.0
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB45_3:
; VI-NEXT:    s_branch .LBB45_2
; VI-NEXT:  .LBB45_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v8f32_to_v16bf16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB45_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB45_4
; GFX9-NEXT:  .LBB45_2: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e64 v7, s23, 1.0
; GFX9-NEXT:    v_add_f32_e64 v6, s22, 1.0
; GFX9-NEXT:    v_add_f32_e64 v5, s21, 1.0
; GFX9-NEXT:    v_add_f32_e64 v4, s20, 1.0
; GFX9-NEXT:    v_add_f32_e64 v3, s19, 1.0
; GFX9-NEXT:    v_add_f32_e64 v2, s18, 1.0
; GFX9-NEXT:    v_add_f32_e64 v1, s17, 1.0
; GFX9-NEXT:    v_add_f32_e64 v0, s16, 1.0
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB45_3:
; GFX9-NEXT:    s_branch .LBB45_2
; GFX9-NEXT:  .LBB45_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v8f32_to_v16bf16_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s7, s19
; GFX11-NEXT:    s_mov_b32 s6, s18
; GFX11-NEXT:    s_mov_b32 s5, s17
; GFX11-NEXT:    s_mov_b32 s4, s16
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s8, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB45_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-NEXT:    s_cbranch_vccnz .LBB45_4
; GFX11-NEXT:  .LBB45_2: ; %cmp.true
; GFX11-NEXT:    v_add_f32_e64 v7, s7, 1.0
; GFX11-NEXT:    v_add_f32_e64 v6, s6, 1.0
; GFX11-NEXT:    v_add_f32_e64 v5, s5, 1.0
; GFX11-NEXT:    v_add_f32_e64 v4, s4, 1.0
; GFX11-NEXT:    v_add_f32_e64 v3, s3, 1.0
; GFX11-NEXT:    v_add_f32_e64 v2, s2, 1.0
; GFX11-NEXT:    v_add_f32_e64 v1, s1, 1.0
; GFX11-NEXT:    v_add_f32_e64 v0, s0, 1.0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB45_3:
; GFX11-NEXT:    s_branch .LBB45_2
; GFX11-NEXT:  .LBB45_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <8 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <8 x float> %a1 to <16 x bfloat>
  br label %end

cmp.false:
  %a3 = bitcast <8 x float> %a to <16 x bfloat>
  br label %end

end:
  %phi = phi <16 x bfloat> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x bfloat> %phi
}

define <8 x float> @bitcast_v16bf16_to_v8f32(<16 x bfloat> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v16bf16_to_v8f32:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_and_b32_e32 v9, 0xffff0000, v7
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_and_b32_e32 v10, 0xffff0000, v6
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_and_b32_e32 v11, 0xffff0000, v5
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v12, 0xffff0000, v4
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_and_b32_e32 v13, 0xffff0000, v3
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v14, 0xffff0000, v2
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_and_b32_e32 v15, 0xffff0000, v1
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_and_b32_e32 v16, 0xffff0000, v0
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    v_mul_f32_e32 v22, 1.0, v16
; SI-NEXT:    v_mul_f32_e32 v23, 1.0, v0
; SI-NEXT:    v_mul_f32_e32 v20, 1.0, v15
; SI-NEXT:    v_mul_f32_e32 v21, 1.0, v1
; SI-NEXT:    v_mul_f32_e32 v18, 1.0, v14
; SI-NEXT:    v_mul_f32_e32 v19, 1.0, v2
; SI-NEXT:    v_mul_f32_e32 v16, 1.0, v13
; SI-NEXT:    v_mul_f32_e32 v17, 1.0, v3
; SI-NEXT:    v_mul_f32_e32 v14, 1.0, v12
; SI-NEXT:    v_mul_f32_e32 v15, 1.0, v4
; SI-NEXT:    v_mul_f32_e32 v12, 1.0, v11
; SI-NEXT:    v_mul_f32_e32 v13, 1.0, v5
; SI-NEXT:    v_mul_f32_e32 v10, 1.0, v10
; SI-NEXT:    v_mul_f32_e32 v11, 1.0, v6
; SI-NEXT:    v_mul_f32_e32 v8, 1.0, v9
; SI-NEXT:    v_mul_f32_e32 v9, 1.0, v7
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB46_3
; SI-NEXT:  ; %bb.1: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB46_4
; SI-NEXT:  .LBB46_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB46_3: ; %cmp.false
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v22
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v20
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v18
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v16
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v14
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v12
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v10
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v8
; SI-NEXT:    v_alignbit_b32 v0, v0, v23, 16
; SI-NEXT:    v_alignbit_b32 v1, v1, v21, 16
; SI-NEXT:    v_alignbit_b32 v2, v2, v19, 16
; SI-NEXT:    v_alignbit_b32 v3, v3, v17, 16
; SI-NEXT:    v_alignbit_b32 v4, v4, v15, 16
; SI-NEXT:    v_alignbit_b32 v5, v5, v13, 16
; SI-NEXT:    v_alignbit_b32 v6, v6, v11, 16
; SI-NEXT:    v_alignbit_b32 v7, v7, v9, 16
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB46_2
; SI-NEXT:  .LBB46_4: ; %cmp.true
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v22
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v20
; SI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v23
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v21
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_alignbit_b32 v0, v1, v0, 16
; SI-NEXT:    v_alignbit_b32 v1, v3, v2, 16
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v18
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v19
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v16
; SI-NEXT:    v_alignbit_b32 v2, v3, v2, 16
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v17
; SI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v14
; SI-NEXT:    v_alignbit_b32 v3, v4, v3, 16
; SI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v15
; SI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; SI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v12
; SI-NEXT:    v_alignbit_b32 v4, v5, v4, 16
; SI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v13
; SI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; SI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v10
; SI-NEXT:    v_alignbit_b32 v5, v6, v5, 16
; SI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v11
; SI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; SI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_and_b32_e32 v8, 0xffff0000, v8
; SI-NEXT:    v_alignbit_b32 v6, v7, v6, 16
; SI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v9
; SI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; SI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; SI-NEXT:    v_lshrrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_alignbit_b32 v7, v8, v7, 16
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16bf16_to_v8f32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB46_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v7
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, 0x7fff, v9
; VI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v7, 16, 1
; VI-NEXT:    s_movk_i32 s6, 0x7fff
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v7
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v7
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; VI-NEXT:    v_cndmask_b32_e32 v7, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; VI-NEXT:    v_alignbit_b32 v7, v7, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v6
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v6, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v6
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v6
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; VI-NEXT:    v_cndmask_b32_e32 v6, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_alignbit_b32 v6, v6, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v5
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v5, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v5
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v5
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; VI-NEXT:    v_cndmask_b32_e32 v5, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_alignbit_b32 v5, v5, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v4
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v4, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v4
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v4
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; VI-NEXT:    v_cndmask_b32_e32 v4, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_alignbit_b32 v4, v4, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v3
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v3
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_alignbit_b32 v3, v3, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v2
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v2
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_alignbit_b32 v2, v2, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v1
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v1, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v1
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v1
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; VI-NEXT:    v_cndmask_b32_e32 v1, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_alignbit_b32 v1, v1, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v0
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v0, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v0
; VI-NEXT:    v_add_u32_e32 v9, vcc, 0x7fff, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v0
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; VI-NEXT:    v_cndmask_b32_e32 v0, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; VI-NEXT:    v_alignbit_b32 v0, v0, v8, 16
; VI-NEXT:  .LBB46_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16bf16_to_v8f32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB46_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v7
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    s_movk_i32 s6, 0x7fff
; GFX9-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v7, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v7, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v7
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; GFX9-NEXT:    v_cndmask_b32_e32 v7, v9, v10, vcc
; GFX9-NEXT:    s_mov_b32 s7, 0x7060302
; GFX9-NEXT:    v_perm_b32 v7, v7, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v6
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v6, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v6, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v6
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; GFX9-NEXT:    v_cndmask_b32_e32 v6, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v6, v6, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v5
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v5, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v5, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v5, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v5, v5, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v4
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v4, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v4, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v4
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; GFX9-NEXT:    v_cndmask_b32_e32 v4, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v4, v4, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v3
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v3, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v3, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v3
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; GFX9-NEXT:    v_cndmask_b32_e32 v3, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v3, v3, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v2, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v2, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v2, v2, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v1
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v1, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v1, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v1, v1, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v0
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v0, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v0, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v0
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v0, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v0, v0, v8, s7
; GFX9-NEXT:  .LBB46_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v16bf16_to_v8f32:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v8
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
; GFX11-TRUE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v15, v7 :: v_dual_mov_b32 v14, v6
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v13, v5 :: v_dual_mov_b32 v12, v4
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v11, v3 :: v_dual_mov_b32 v10, v2
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v9, v1 :: v_dual_mov_b32 v8, v0
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr7
; GFX11-TRUE16-NEXT:  ; %bb.2: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB46_4
; GFX11-TRUE16-NEXT:  ; %bb.3: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v9, 0xffff0000, v6
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v8, 16, v7
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v10, 0xffff0000, v5
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v9, 0x40c00000, v9 :: v_dual_add_f32 v8, 0x40c00000, v8
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v15, v9, 16, 1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v11, v8, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v14, 0x400000, v8
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add3_u32 v11, v11, v8, 0x7fff
; GFX11-TRUE16-NEXT:    v_dual_cndmask_b32 v8, v11, v14 :: v_dual_and_b32 v7, 0xffff0000, v7
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v7, 0x40c00000, v7 :: v_dual_lshlrev_b32 v6, 16, v6
; GFX11-TRUE16-NEXT:    v_add3_u32 v11, v15, v9, 0x7fff
; GFX11-TRUE16-NEXT:    v_bfe_u32 v12, v7, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v13, 0x400000, v7
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add3_u32 v12, v12, v7, 0x7fff
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v6, 0x40c00000, v6 :: v_dual_cndmask_b32 v15, v12, v13
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v16, v6, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v17, 0x400000, v6
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v15.l, v8.h
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v9
; GFX11-TRUE16-NEXT:    v_add3_u32 v14, v16, v6, 0x7fff
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v6, v14, v17, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v7, 0x40c00000, v10
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v9, 0xffff0000, v4
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v14, v11, v8, vcc_lo
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v10, v7, 16, 1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v8, v5, 16, 1
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v14.l, v6.h
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v9, 0x40c00000, v9 :: v_dual_add_f32 v4, 0x40c00000, v4
; GFX11-TRUE16-NEXT:    v_add3_u32 v6, v10, v7, 0x7fff
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_add3_u32 v8, v8, v5, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v10, 0x400000, v5
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v11, 0x400000, v7
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v5, v8, v10, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-TRUE16-NEXT:    v_bfe_u32 v7, v4, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v4
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v10, 0x400000, v9
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v13, v6, v11, vcc_lo
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_add3_u32 v7, v7, v4, 0x7fff
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-TRUE16-NEXT:    v_bfe_u32 v6, v9, 16, 1
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v11, 0xffff0000, v2
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v4, v7, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v13.l, v5.h
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v5, 0xffff0000, v3
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_2) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v2, 0x40c00000, v2 :: v_dual_lshlrev_b32 v3, 16, v3
; GFX11-TRUE16-NEXT:    v_add3_u32 v6, v6, v9, 0x7fff
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v3, 0x40c00000, v3 :: v_dual_cndmask_b32 v12, v6, v10
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v6, 0x40c00000, v11
; GFX11-TRUE16-NEXT:    v_bfe_u32 v7, v5, 16, 1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v8, v3, 16, 1
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v12.l, v4.h
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v9, 0x400000, v5
; GFX11-TRUE16-NEXT:    v_add3_u32 v4, v7, v5, 0x7fff
; GFX11-TRUE16-NEXT:    v_add3_u32 v7, v8, v3, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v3
; GFX11-TRUE16-NEXT:    v_bfe_u32 v10, v6, 16, 1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v3, v7, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, 0x400000, v6
; GFX11-TRUE16-NEXT:    v_bfe_u32 v7, v2, 16, 1
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v11, v4, v9, vcc_lo
; GFX11-TRUE16-NEXT:    v_add3_u32 v4, v10, v6, 0x7fff
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v11.l, v3.h
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v3, 0xffff0000, v1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v3, 0x40c00000, v3 :: v_dual_lshlrev_b32 v6, 16, v0
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v10, v4, v5, vcc_lo
; GFX11-TRUE16-NEXT:    v_add3_u32 v4, v7, v2, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, 0x400000, v2
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v7, 0x400000, v3
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v2, v4, v5, vcc_lo
; GFX11-TRUE16-NEXT:    v_bfe_u32 v4, v3, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v5, 0x40c00000, v6
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v10.l, v2.h
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_4) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_add3_u32 v4, v4, v3, 0x7fff
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v6, v5, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v16, 0x400000, v5
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v0, 0x40c00000, v0 :: v_dual_add_f32 v1, 0x40c00000, v1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_add3_u32 v6, v6, v5, 0x7fff
; GFX11-TRUE16-NEXT:    v_bfe_u32 v9, v0, 16, 1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-TRUE16-NEXT:    v_add3_u32 v2, v2, v1, 0x7fff
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v2, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-TRUE16-NEXT:    v_add3_u32 v2, v9, v0, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v0
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v5, v6, v16, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v9, v4, v7, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v9.l, v1.h
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v8, v2, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v8.l, v5.h
; GFX11-TRUE16-NEXT:  .LBB46_4: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v0, v8 :: v_dual_mov_b32 v1, v9
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v2, v10 :: v_dual_mov_b32 v3, v11
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v4, v12 :: v_dual_mov_b32 v5, v13
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v6, v14 :: v_dual_mov_b32 v7, v15
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v16bf16_to_v8f32:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-FAKE16-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB46_2
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v9, 16, v6
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v8, 16, v7
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v9, 0x40c00000, v9 :: v_dual_add_f32 v8, 0x40c00000, v8
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v9, 16, 1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v10, v8, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, 0x400000, v8
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v15, v6, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-FAKE16-NEXT:    v_add3_u32 v13, v13, v9, 0x7fff
; GFX11-FAKE16-NEXT:    v_add3_u32 v10, v10, v8, 0x7fff
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v8, v10, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_add3_u32 v11, v15, v6, 0x7fff
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v10, 0x400000, v9
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GFX11-FAKE16-NEXT:    v_bfe_u32 v12, v7, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v14, 0x400000, v7
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_add3_u32 v12, v12, v7, 0x7fff
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v7, v12, v14 :: v_dual_lshlrev_b32 v12, 16, v5
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v7, v8, 0x7060302
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v14, 0x400000, v6
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v9, v13, v10 :: v_dual_add_f32 v10, 0x40c00000, v12
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v8, v5, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v13, 0x400000, v5
; GFX11-FAKE16-NEXT:    v_bfe_u32 v12, v10, 16, 1
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v6, v11, v14 :: v_dual_lshlrev_b32 v11, 16, v4
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-FAKE16-NEXT:    v_add3_u32 v8, v8, v5, 0x7fff
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v6, v9, 0x7060302
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v9, 0x40c00000, v11 :: v_dual_add_f32 v4, 0x40c00000, v4
; GFX11-FAKE16-NEXT:    v_add3_u32 v11, v12, v10, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, 0x400000, v10
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v14, v9, 16, 1
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v10, v11, v12, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, 0x400000, v9
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v12, 16, v3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v5, v8, v13, vcc_lo
; GFX11-FAKE16-NEXT:    v_add3_u32 v8, v14, v9, 0x7fff
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v9, 0x40c00000, v12 :: v_dual_lshlrev_b32 v12, 16, v2
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v5, v10, 0x7060302
; GFX11-FAKE16-NEXT:    v_bfe_u32 v10, v4, 16, 1
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v8, v8, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, 0x400000, v4
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v9, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-FAKE16-NEXT:    v_add3_u32 v10, v10, v4, 0x7fff
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v4, v10, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v10, 0x40c00000, v12
; GFX11-FAKE16-NEXT:    v_add3_u32 v11, v13, v9, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, 0x400000, v9
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v3, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-FAKE16-NEXT:    v_bfe_u32 v14, v10, 16, 1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v9, v11, v12, vcc_lo
; GFX11-FAKE16-NEXT:    v_add3_u32 v11, v13, v3, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, 0x400000, v3
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; GFX11-FAKE16-NEXT:    v_add3_u32 v13, v14, v10, 0x7fff
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v14, 16, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v3, v11, v12 :: v_dual_add_f32 v2, 0x40c00000, v2
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v4, v8, 0x7060302
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v11, 0x40c00000, v14
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v15, 0x400000, v10
; GFX11-FAKE16-NEXT:    v_bfe_u32 v16, v2, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-FAKE16-NEXT:    v_bfe_u32 v14, v11, 16, 1
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v3, v9, 0x7060302
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_add3_u32 v12, v16, v2, 0x7fff
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v10, v13, v15 :: v_dual_lshlrev_b32 v15, 16, v0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v13, 0x400000, v2
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v2, v12, v13, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v12, 0x40c00000, v15
; GFX11-FAKE16-NEXT:    v_add3_u32 v13, v14, v11, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v14, 0x400000, v11
; GFX11-FAKE16-NEXT:    v_bfe_u32 v15, v1, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v11, v11
; GFX11-FAKE16-NEXT:    v_bfe_u32 v16, v12, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v17, 0x400000, v12
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v2, v10, 0x7060302
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v11, v13, v14, vcc_lo
; GFX11-FAKE16-NEXT:    v_add3_u32 v14, v15, v1, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v15, 0x400000, v1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX11-FAKE16-NEXT:    v_add3_u32 v16, v16, v12, 0x7fff
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v1, v14, v15 :: v_dual_add_f32 v0, 0x40c00000, v0
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v12, v12
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v1, v11, 0x7060302
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_3) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v0, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v18, 0x400000, v0
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v12, v16, v17, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-FAKE16-NEXT:    v_add3_u32 v13, v13, v0, 0x7fff
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v0, v13, v18, vcc_lo
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v0, v12, 0x7060302
; GFX11-FAKE16-NEXT:  .LBB46_2: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x bfloat> %a, splat (bfloat 0xR40C0)
  %a2 = bitcast <16 x bfloat> %a1 to <8 x float>
  br label %end

cmp.false:
  %a3 = bitcast <16 x bfloat> %a to <8 x float>
  br label %end

end:
  %phi = phi <8 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x float> %phi
}

define inreg <8 x float> @bitcast_v16bf16_to_v8f32_scalar(<16 x bfloat> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v16bf16_to_v8f32_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_and_b32 s4, s23, 0xffff0000
; SI-NEXT:    s_lshl_b32 s5, s23, 16
; SI-NEXT:    s_and_b32 s6, s22, 0xffff0000
; SI-NEXT:    s_lshl_b32 s7, s22, 16
; SI-NEXT:    s_and_b32 s8, s21, 0xffff0000
; SI-NEXT:    s_lshl_b32 s9, s21, 16
; SI-NEXT:    s_and_b32 s10, s20, 0xffff0000
; SI-NEXT:    s_lshl_b32 s11, s20, 16
; SI-NEXT:    s_and_b32 s12, s19, 0xffff0000
; SI-NEXT:    s_lshl_b32 s13, s19, 16
; SI-NEXT:    s_and_b32 s14, s18, 0xffff0000
; SI-NEXT:    s_lshl_b32 s15, s18, 16
; SI-NEXT:    s_and_b32 s18, s17, 0xffff0000
; SI-NEXT:    s_lshl_b32 s17, s17, 16
; SI-NEXT:    s_and_b32 s19, s16, 0xffff0000
; SI-NEXT:    s_lshl_b32 s16, s16, 16
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    v_mul_f32_e64 v32, 1.0, s19
; SI-NEXT:    v_mul_f32_e64 v23, 1.0, s16
; SI-NEXT:    v_mul_f32_e64 v31, 1.0, s18
; SI-NEXT:    v_mul_f32_e64 v21, 1.0, s17
; SI-NEXT:    v_mul_f32_e64 v30, 1.0, s14
; SI-NEXT:    v_mul_f32_e64 v19, 1.0, s15
; SI-NEXT:    v_mul_f32_e64 v29, 1.0, s12
; SI-NEXT:    v_mul_f32_e64 v17, 1.0, s13
; SI-NEXT:    v_mul_f32_e64 v28, 1.0, s10
; SI-NEXT:    v_mul_f32_e64 v15, 1.0, s11
; SI-NEXT:    v_mul_f32_e64 v27, 1.0, s8
; SI-NEXT:    v_mul_f32_e64 v13, 1.0, s9
; SI-NEXT:    v_mul_f32_e64 v26, 1.0, s6
; SI-NEXT:    v_mul_f32_e64 v25, 1.0, s4
; SI-NEXT:    v_mul_f32_e64 v11, 1.0, s7
; SI-NEXT:    v_mul_f32_e64 v9, 1.0, s5
; SI-NEXT:    s_cbranch_scc0 .LBB47_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_lshrrev_b32_e32 v24, 16, v32
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v31
; SI-NEXT:    v_lshr_b64 v[0:1], v[23:24], 16
; SI-NEXT:    v_lshr_b64 v[1:2], v[21:22], 16
; SI-NEXT:    v_lshrrev_b32_e32 v20, 16, v30
; SI-NEXT:    v_lshr_b64 v[2:3], v[19:20], 16
; SI-NEXT:    v_lshrrev_b32_e32 v18, 16, v29
; SI-NEXT:    v_lshr_b64 v[3:4], v[17:18], 16
; SI-NEXT:    v_lshrrev_b32_e32 v16, 16, v28
; SI-NEXT:    v_lshr_b64 v[4:5], v[15:16], 16
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v27
; SI-NEXT:    v_lshr_b64 v[5:6], v[13:14], 16
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v26
; SI-NEXT:    v_lshr_b64 v[6:7], v[11:12], 16
; SI-NEXT:    v_lshrrev_b32_e32 v10, 16, v25
; SI-NEXT:    v_lshr_b64 v[7:8], v[9:10], 16
; SI-NEXT:    s_cbranch_execnz .LBB47_3
; SI-NEXT:  .LBB47_2: ; %cmp.true
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v32
; SI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v23
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v31
; SI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v21
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_lshr_b64 v[0:1], v[0:1], 16
; SI-NEXT:    v_lshr_b64 v[1:2], v[2:3], 16
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v30
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v19
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_lshr_b64 v[2:3], v[2:3], 16
; SI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v29
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v17
; SI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_lshr_b64 v[3:4], v[3:4], 16
; SI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v28
; SI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v15
; SI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; SI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_lshr_b64 v[4:5], v[4:5], 16
; SI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v27
; SI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v13
; SI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; SI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_lshr_b64 v[5:6], v[5:6], 16
; SI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v26
; SI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v11
; SI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; SI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_lshr_b64 v[6:7], v[6:7], 16
; SI-NEXT:    v_and_b32_e32 v8, 0xffff0000, v25
; SI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v9
; SI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; SI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; SI-NEXT:    v_lshrrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_lshr_b64 v[7:8], v[7:8], 16
; SI-NEXT:  .LBB47_3: ; %end
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB47_4:
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; SI-NEXT:    s_branch .LBB47_2
;
; VI-LABEL: bitcast_v16bf16_to_v8f32_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB47_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB47_4
; VI-NEXT:  .LBB47_2: ; %cmp.true
; VI-NEXT:    s_lshl_b32 s4, s23, 16
; VI-NEXT:    v_mov_b32_e32 v8, 0x40c00000
; VI-NEXT:    v_add_f32_e32 v0, s4, v8
; VI-NEXT:    v_bfe_u32 v1, v0, 16, 1
; VI-NEXT:    v_add_u32_e32 v1, vcc, v1, v0
; VI-NEXT:    v_add_u32_e32 v1, vcc, 0x7fff, v1
; VI-NEXT:    v_or_b32_e32 v2, 0x400000, v0
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; VI-NEXT:    s_and_b32 s4, s23, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v0, v1, v2, vcc
; VI-NEXT:    v_add_f32_e32 v1, s4, v8
; VI-NEXT:    v_bfe_u32 v2, v1, 16, 1
; VI-NEXT:    v_add_u32_e32 v2, vcc, v2, v1
; VI-NEXT:    v_add_u32_e32 v2, vcc, 0x7fff, v2
; VI-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; VI-NEXT:    s_lshl_b32 s4, s22, 16
; VI-NEXT:    v_cndmask_b32_e32 v1, v2, v3, vcc
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    s_and_b32 s4, s22, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; VI-NEXT:    v_add_f32_e32 v3, s4, v8
; VI-NEXT:    v_bfe_u32 v4, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v4, vcc, v4, v3
; VI-NEXT:    v_add_u32_e32 v4, vcc, 0x7fff, v4
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v4, v5, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    s_lshl_b32 s4, s21, 16
; VI-NEXT:    v_lshrrev_b64 v[6:7], 16, v[2:3]
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    s_and_b32 s4, s21, 0xffff0000
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_cndmask_b32_e32 v9, v3, v4, vcc
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; VI-NEXT:    s_lshl_b32 s4, s20, 16
; VI-NEXT:    v_lshrrev_b32_e32 v10, 16, v2
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    s_and_b32 s4, s20, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; VI-NEXT:    v_add_f32_e32 v3, s4, v8
; VI-NEXT:    v_bfe_u32 v4, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v4, vcc, v4, v3
; VI-NEXT:    v_add_u32_e32 v4, vcc, 0x7fff, v4
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v4, v5, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    s_lshl_b32 s4, s19, 16
; VI-NEXT:    v_lshrrev_b64 v[4:5], 16, v[2:3]
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    s_and_b32 s4, s19, 0xffff0000
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_cndmask_b32_e32 v11, v3, v5, vcc
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v5, vcc
; VI-NEXT:    s_lshl_b32 s4, s18, 16
; VI-NEXT:    v_lshrrev_b32_e32 v12, 16, v2
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    s_and_b32 s4, s18, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v5, vcc
; VI-NEXT:    v_add_f32_e32 v3, s4, v8
; VI-NEXT:    v_bfe_u32 v5, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v3
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    v_or_b32_e32 v7, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v5, v7, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_lshrrev_b64 v[2:3], 16, v[2:3]
; VI-NEXT:    s_lshl_b32 s4, s17, 16
; VI-NEXT:    v_add_f32_e32 v3, s4, v8
; VI-NEXT:    v_bfe_u32 v5, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v3
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    s_and_b32 s4, s17, 0xffff0000
; VI-NEXT:    v_or_b32_e32 v7, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_add_f32_e32 v3, s4, v8
; VI-NEXT:    v_cndmask_b32_e32 v13, v5, v7, vcc
; VI-NEXT:    v_bfe_u32 v5, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v3
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    v_or_b32_e32 v7, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v5, v7, vcc
; VI-NEXT:    s_lshl_b32 s4, s16, 16
; VI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; VI-NEXT:    v_add_f32_e32 v3, s4, v8
; VI-NEXT:    v_bfe_u32 v5, v3, 16, 1
; VI-NEXT:    s_and_b32 s6, s16, 0xffff0000
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v3
; VI-NEXT:    v_or_b32_e32 v15, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e64 s[4:5], v3, v3
; VI-NEXT:    v_add_f32_e32 v3, s6, v8
; VI-NEXT:    v_bfe_u32 v7, v3, 16, 1
; VI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_add_u32_e32 v7, vcc, v7, v3
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    v_add_u32_e32 v16, vcc, 0x7fff, v7
; VI-NEXT:    v_lshrrev_b64 v[7:8], 16, v[0:1]
; VI-NEXT:    v_or_b32_e32 v17, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_lshrrev_b64 v[8:9], 16, v[9:10]
; VI-NEXT:    v_lshrrev_b64 v[9:10], 16, v[11:12]
; VI-NEXT:    v_cndmask_b32_e32 v1, v16, v17, vcc
; VI-NEXT:    v_lshrrev_b64 v[10:11], 16, v[13:14]
; VI-NEXT:    v_cndmask_b32_e64 v0, v5, v15, s[4:5]
; VI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_lshrrev_b64 v[0:1], 16, v[0:1]
; VI-NEXT:    v_mov_b32_e32 v1, v10
; VI-NEXT:    v_mov_b32_e32 v3, v9
; VI-NEXT:    v_mov_b32_e32 v5, v8
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB47_3:
; VI-NEXT:    s_branch .LBB47_2
; VI-NEXT:  .LBB47_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16bf16_to_v8f32_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB47_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB47_4
; GFX9-NEXT:  .LBB47_2: ; %cmp.true
; GFX9-NEXT:    s_and_b32 s4, s23, 0xffff0000
; GFX9-NEXT:    v_mov_b32_e32 v0, 0x40c00000
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v1
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s23, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v2, v3, vcc
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v0
; GFX9-NEXT:    v_bfe_u32 v3, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v3, v3, v2
; GFX9-NEXT:    v_add_u32_e32 v3, 0x7fff, v3
; GFX9-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; GFX9-NEXT:    v_mov_b32_e32 v8, 0xffff
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v2, v8, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s22, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v7, v1, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v1
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s22, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v2, v3, vcc
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v0
; GFX9-NEXT:    v_bfe_u32 v3, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v3, v3, v2
; GFX9-NEXT:    v_add_u32_e32 v3, 0x7fff, v3
; GFX9-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v2, v8, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s21, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v6, v1, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v1
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s21, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v2, v3, vcc
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v0
; GFX9-NEXT:    v_bfe_u32 v3, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v3, v3, v2
; GFX9-NEXT:    v_add_u32_e32 v3, 0x7fff, v3
; GFX9-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v2, v8, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s20, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v5, v1, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v1
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s20, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v2, v3, vcc
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v0
; GFX9-NEXT:    v_bfe_u32 v3, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v3, v3, v2
; GFX9-NEXT:    v_add_u32_e32 v3, 0x7fff, v3
; GFX9-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v2, v8, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s19, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v4, v1, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v1
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s19, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v2, v3, vcc
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v0
; GFX9-NEXT:    v_bfe_u32 v3, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v3, v3, v2
; GFX9-NEXT:    v_add_u32_e32 v3, 0x7fff, v3
; GFX9-NEXT:    v_or_b32_e32 v9, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v3, v9, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v2, v8, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s18, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v3, v1, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v1
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v9, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s18, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v2, v9, vcc
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v0
; GFX9-NEXT:    v_bfe_u32 v9, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v9, v9, v2
; GFX9-NEXT:    v_add_u32_e32 v9, 0x7fff, v9
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v9, v10, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v2, v8, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s17, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v2, v1, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v9, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v9, v9, v1
; GFX9-NEXT:    v_add_u32_e32 v9, 0x7fff, v9
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s17, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v9, v10, vcc
; GFX9-NEXT:    v_add_f32_e32 v9, s4, v0
; GFX9-NEXT:    v_bfe_u32 v10, v9, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v10, v10, v9
; GFX9-NEXT:    v_add_u32_e32 v10, 0x7fff, v10
; GFX9-NEXT:    v_or_b32_e32 v11, 0x400000, v9
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v9, v9
; GFX9-NEXT:    v_cndmask_b32_e32 v9, v10, v11, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v9, v8, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s16, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v1, v1, 16, v9
; GFX9-NEXT:    v_add_f32_e32 v9, s4, v0
; GFX9-NEXT:    v_bfe_u32 v10, v9, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v10, v10, v9
; GFX9-NEXT:    s_lshl_b32 s4, s16, 16
; GFX9-NEXT:    v_add_u32_e32 v10, 0x7fff, v10
; GFX9-NEXT:    v_or_b32_e32 v11, 0x400000, v9
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v9, v9
; GFX9-NEXT:    v_add_f32_e32 v0, s4, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v9, v10, v11, vcc
; GFX9-NEXT:    v_bfe_u32 v10, v0, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v10, v10, v0
; GFX9-NEXT:    v_add_u32_e32 v10, 0x7fff, v10
; GFX9-NEXT:    v_or_b32_e32 v11, 0x400000, v0
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v0, v10, v11, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v9, 16, v9
; GFX9-NEXT:    v_and_b32_sdwa v0, v8, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    v_lshl_or_b32 v0, v9, 16, v0
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB47_3:
; GFX9-NEXT:    s_branch .LBB47_2
; GFX9-NEXT:  .LBB47_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v16bf16_to_v8f32_scalar:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_mov_b32 s7, s19
; GFX11-TRUE16-NEXT:    s_mov_b32 s6, s18
; GFX11-TRUE16-NEXT:    s_mov_b32 s5, s17
; GFX11-TRUE16-NEXT:    s_mov_b32 s4, s16
; GFX11-TRUE16-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-TRUE16-NEXT:    s_mov_b32 s8, 0
; GFX11-TRUE16-NEXT:    s_cbranch_scc0 .LBB47_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-TRUE16-NEXT:    s_cbranch_vccnz .LBB47_4
; GFX11-TRUE16-NEXT:  .LBB47_2: ; %cmp.true
; GFX11-TRUE16-NEXT:    s_and_b32 s8, s7, 0xffff0000
; GFX11-TRUE16-NEXT:    s_lshl_b32 s7, s7, 16
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v0, 0x40c00000, s8
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v1, 0x40c00000, s7
; GFX11-TRUE16-NEXT:    s_and_b32 s7, s6, 0xffff0000
; GFX11-TRUE16-NEXT:    s_lshl_b32 s6, s6, 16
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v4, 0x40c00000, s7
; GFX11-TRUE16-NEXT:    v_bfe_u32 v2, v0, 16, 1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v3, v1, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v5, 0x40c00000, s6
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v6, 0x400000, v0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v7, v4, 16, 1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, v2, v0
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v9, v5, 16, 1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v7, v7, v4
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v2
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, v3, v1
; GFX11-TRUE16-NEXT:    s_and_b32 s6, s5, 0xffff0000
; GFX11-TRUE16-NEXT:    s_lshl_b32 s5, s5, 16
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_dual_cndmask_b32 v0, v2, v6 :: v_dual_add_nc_u32 v3, 0x7fff, v3
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, 0x7fff, v7
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v3, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v3, 0x400000, v4
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, v9, v5
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v8, 0x40c00000, s5
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v7, 16, v1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v9, 0x400000, v5
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v3, v6, v3, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, 0x7fff, v2
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v2, 0x40c00000, s6
; GFX11-TRUE16-NEXT:    v_bfe_u32 v6, v8, 16, 1
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v7.h, v0.l
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v1, v9, vcc_lo
; GFX11-TRUE16-NEXT:    v_bfe_u32 v4, v2, 16, 1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v0, v6, v8
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-TRUE16-NEXT:    s_and_b32 s5, s4, 0xffff0000
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v6, 16, v1
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v6.h, v3.l
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v3, 0x400000, v2
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v4, v4, v2
; GFX11-TRUE16-NEXT:    s_lshl_b32 s4, s4, 16
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v0, 0x7fff, v0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v9, 0x40c00000, s4
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, 0x400000, v8
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, 0x7fff, v4
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v4, 0x40c00000, s5
; GFX11-TRUE16-NEXT:    s_and_b32 s4, s3, 0xffff0000
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v10, 0x400000, v9
; GFX11-TRUE16-NEXT:    s_lshl_b32 s3, s3, 16
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v1, v3, vcc_lo
; GFX11-TRUE16-NEXT:    v_bfe_u32 v2, v4, 16, 1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-TRUE16-NEXT:    v_bfe_u32 v3, v9, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v4
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, v2, v4
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v0, v0, v5, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, v3, v9
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v2
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v5, 16, v0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v0, 0x40c00000, s4
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v3
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v5.h, v1.l
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v2, v2, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-TRUE16-NEXT:    v_bfe_u32 v11, v0, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v1, 0x40c00000, s3
; GFX11-TRUE16-NEXT:    s_and_b32 s3, s2, 0xffff0000
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v3, v3, v10, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v8, v11, v0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v9, v1, 16, 1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-TRUE16-NEXT:    s_lshl_b32 s2, s2, 16
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v4, 16, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v8
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v0
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v4.h, v2.l
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v2, 0x40c00000, s3
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v10, 0x400000, v1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_dual_cndmask_b32 v0, v3, v8 :: v_dual_add_nc_u32 v3, v9, v1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v8, v2, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v9, 0x40c00000, s2
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-TRUE16-NEXT:    s_and_b32 s2, s1, 0xffff0000
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v8, v8, v2
; GFX11-TRUE16-NEXT:    v_bfe_u32 v11, v9, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v12, 0x400000, v2
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v3, v10, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v10, 0x40c00000, s2
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v8, 0x7fff, v8
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v11, v11, v9
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v3, 16, v1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v1, v10, 16, 1
; GFX11-TRUE16-NEXT:    s_lshl_b32 s1, s1, 16
; GFX11-TRUE16-NEXT:    s_and_b32 s2, s0, 0xffff0000
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v2, v8, v12, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v8, 0x7fff, v11
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v11, 0x400000, v9
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, v1, v10
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v3.h, v0.l
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v2
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v9, 0x40c00000, s2
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v2, v8, v11, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v8, 0x40c00000, s1
; GFX11-TRUE16-NEXT:    s_lshl_b32 s0, s0, 16
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, 0x7fff, v1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v11, 0x400000, v10
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v12, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v13, v8, 16, 1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v14, v9, 16, 1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v15, 0x400000, v8
; GFX11-TRUE16-NEXT:    v_bfe_u32 v10, v12, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v16, 0x400000, v12
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v1, v11, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v11, v13, v8
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v13, v14, v9
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.h, v0.l
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v14, 16, v1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, v10, v12
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v10, 0x7fff, v11
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v11, 0x7fff, v13
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v13, 0x400000, v9
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, 0x7fff, v1
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v9, v11, v13, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_3) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v9, 16, v9
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v8, v10, v15, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v12, v12
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v10, v1, v16, vcc_lo
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v1, 16, v8
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v1.h, v14.l
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v10
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.h, v9.l
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB47_3:
; GFX11-TRUE16-NEXT:    s_branch .LBB47_2
; GFX11-TRUE16-NEXT:  .LBB47_4:
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v16bf16_to_v8f32_scalar:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    s_mov_b32 s7, s19
; GFX11-FAKE16-NEXT:    s_mov_b32 s6, s18
; GFX11-FAKE16-NEXT:    s_mov_b32 s5, s17
; GFX11-FAKE16-NEXT:    s_mov_b32 s4, s16
; GFX11-FAKE16-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-FAKE16-NEXT:    s_mov_b32 s8, 0
; GFX11-FAKE16-NEXT:    s_cbranch_scc0 .LBB47_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-FAKE16-NEXT:    s_cbranch_vccnz .LBB47_4
; GFX11-FAKE16-NEXT:  .LBB47_2: ; %cmp.true
; GFX11-FAKE16-NEXT:    s_lshl_b32 s8, s7, 16
; GFX11-FAKE16-NEXT:    s_and_b32 s7, s7, 0xffff0000
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v0, 0x40c00000, s8
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v1, 0x40c00000, s7
; GFX11-FAKE16-NEXT:    s_and_b32 s8, s6, 0xffff0000
; GFX11-FAKE16-NEXT:    s_lshl_b32 s6, s6, 16
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v3, 0x40c00000, s8
; GFX11-FAKE16-NEXT:    v_bfe_u32 v2, v0, 16, 1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v4, v1, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v9, 0x400000, v1
; GFX11-FAKE16-NEXT:    s_and_b32 s7, s5, 0xffff0000
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v5, 0x40c00000, s6
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v6, 0x40c00000, s7
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, v4, v1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v8, 0x400000, v0
; GFX11-FAKE16-NEXT:    v_bfe_u32 v10, v3, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-FAKE16-NEXT:    s_lshl_b32 s5, s5, 16
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, 0x7fff, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, v2, v0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v7, 0x40c00000, s5
; GFX11-FAKE16-NEXT:    v_bfe_u32 v11, v6, 16, 1
; GFX11-FAKE16-NEXT:    s_and_b32 s5, s4, 0xffff0000
; GFX11-FAKE16-NEXT:    s_lshl_b32 s4, s4, 16
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v2
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_4) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v0, v2, v8, vcc_lo
; GFX11-FAKE16-NEXT:    v_bfe_u32 v2, v5, 16, 1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v8, v10, v3
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v10, 0x400000, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, v2, v5
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v1, v4, v9 :: v_dual_add_nc_u32 v8, 0x7fff, v8
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, 0x400000, v3
; GFX11-FAKE16-NEXT:    v_bfe_u32 v9, v7, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v3, v8, v4 :: v_dual_add_nc_u32 v4, v9, v7
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v5, v11, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v8, 0x400000, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, 0x7fff, v4
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v2, v2, v10 :: v_dual_add_nc_u32 v5, 0x7fff, v5
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v9, 0x400000, v6
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v10, 0x40c00000, s4
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v4, v4, v8, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v8, 0x40c00000, s5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v7, v1, 16, v0
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v5, v5, v9, vcc_lo
; GFX11-FAKE16-NEXT:    v_bfe_u32 v9, v10, 16, 1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v6, v8, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-FAKE16-NEXT:    s_and_b32 s4, s3, 0xffff0000
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v0, v9, v10
; GFX11-FAKE16-NEXT:    s_lshl_b32 s3, s3, 16
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v9, 0x40c00000, s3
; GFX11-FAKE16-NEXT:    s_and_b32 s3, s2, 0xffff0000
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v0, 0x7fff, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v11, v6, v8
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v6, v3, 16, v2
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, 0x400000, v10
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, 0x400000, v8
; GFX11-FAKE16-NEXT:    s_lshl_b32 s2, s2, 16
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, 0x400000, v9
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v0, v0, v3, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v1, 0x7fff, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v8, 0x40c00000, s3
; GFX11-FAKE16-NEXT:    v_bfe_u32 v3, v9, 16, 1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v1, v1, v2 :: v_dual_and_b32 v4, 0xffff, v4
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v10, v8, 16, 1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v5, v5, 16, v4
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v4, 0x40c00000, s4
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v10, v10, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v2, v4, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, 0x400000, v4
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, v2, v4
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v4, 0x40c00000, s2
; GFX11-FAKE16-NEXT:    s_and_b32 s2, s1, 0xffff0000
; GFX11-FAKE16-NEXT:    s_lshl_b32 s1, s1, 16
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, v3, v9
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v13, 0x40c00000, s1
; GFX11-FAKE16-NEXT:    s_lshl_b32 s1, s0, 16
; GFX11-FAKE16-NEXT:    s_and_b32 s0, s0, 0xffff0000
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v2, v2, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v9, 0x7fff, v10
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v3
; GFX11-FAKE16-NEXT:    v_bfe_u32 v11, v4, 16, 1
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v14, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v18, 0x400000, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v3, v3, v12, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-FAKE16-NEXT:    v_bfe_u32 v16, v14, 16, 1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v8, v9, v10 :: v_dual_add_nc_u32 v9, v11, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, 0x400000, v4
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v10, 0x40c00000, s2
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v16, v16, v14
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v9, 0x7fff, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v8, 16, v8
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v12, v10, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v17, 0x400000, v10
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v4, v9, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v9, 0x40c00000, s1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v11, v13, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v13, v13
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v12, v12, v10
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v15, v9, 16, 1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v11, v11, v13
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v19, 0x400000, v9
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v12, 0x7fff, v12
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v13, 0x7fff, v16
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v15, v15, v9
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v11, 0x7fff, v11
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v16, 0x400000, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v15, 0x7fff, v15
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v11, v11, v18, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v11, 16, v11
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v9, v15, v19, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v9, 16, v9
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v10, v12, v17, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v14, v14
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v10, 16, v10
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v12, v13, v16, vcc_lo
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v13, 0xffff, v4
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v4, v1, 16, v0
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v3, v2, 16, v3
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v1, v10, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v12, 16, v12
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v2, v8, 16, v13
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v0, v12, 16, v9
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB47_3:
; GFX11-FAKE16-NEXT:    s_branch .LBB47_2
; GFX11-FAKE16-NEXT:  .LBB47_4:
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x bfloat> %a, splat (bfloat 0xR40C0)
  %a2 = bitcast <16 x bfloat> %a1 to <8 x float>
  br label %end

cmp.false:
  %a3 = bitcast <16 x bfloat> %a to <8 x float>
  br label %end

end:
  %phi = phi <8 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x float> %phi
}

define <32 x i8> @bitcast_v8f32_to_v32i8(<8 x float> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v8f32_to_v32i8:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_mov_b32_e32 v28, v7
; SI-NEXT:    v_mov_b32_e32 v24, v6
; SI-NEXT:    v_mov_b32_e32 v20, v5
; SI-NEXT:    v_mov_b32_e32 v16, v4
; SI-NEXT:    v_mov_b32_e32 v12, v3
; SI-NEXT:    v_mov_b32_e32 v32, v2
; SI-NEXT:    v_mov_b32_e32 v4, v1
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    ; implicit-def: $vgpr1
; SI-NEXT:    ; implicit-def: $vgpr2
; SI-NEXT:    ; implicit-def: $vgpr3
; SI-NEXT:    ; implicit-def: $vgpr5
; SI-NEXT:    ; implicit-def: $vgpr6
; SI-NEXT:    ; implicit-def: $vgpr7
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr25
; SI-NEXT:    ; implicit-def: $vgpr26
; SI-NEXT:    ; implicit-def: $vgpr27
; SI-NEXT:    ; implicit-def: $vgpr29
; SI-NEXT:    ; implicit-def: $vgpr30
; SI-NEXT:    ; implicit-def: $vgpr31
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB48_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_alignbit_b32 v27, v28, v24, 24
; SI-NEXT:    v_alignbit_b32 v26, v28, v24, 16
; SI-NEXT:    v_alignbit_b32 v25, v28, v24, 8
; SI-NEXT:    v_alignbit_b32 v19, v20, v16, 24
; SI-NEXT:    v_alignbit_b32 v18, v20, v16, 16
; SI-NEXT:    v_alignbit_b32 v17, v20, v16, 8
; SI-NEXT:    v_alignbit_b32 v11, v12, v32, 24
; SI-NEXT:    v_alignbit_b32 v10, v12, v32, 16
; SI-NEXT:    v_alignbit_b32 v9, v12, v32, 8
; SI-NEXT:    v_alignbit_b32 v3, v4, v0, 24
; SI-NEXT:    v_alignbit_b32 v2, v4, v0, 16
; SI-NEXT:    v_alignbit_b32 v1, v4, v0, 8
; SI-NEXT:    v_lshrrev_b32_e32 v31, 24, v28
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v28
; SI-NEXT:    v_lshrrev_b32_e32 v29, 8, v28
; SI-NEXT:    v_lshrrev_b32_e32 v23, 24, v20
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v20
; SI-NEXT:    v_lshrrev_b32_e32 v21, 8, v20
; SI-NEXT:    v_lshrrev_b32_e32 v15, 24, v12
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v12
; SI-NEXT:    v_lshrrev_b32_e32 v13, 8, v12
; SI-NEXT:    v_lshrrev_b32_e32 v7, 24, v4
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v4
; SI-NEXT:    v_lshrrev_b32_e32 v5, 8, v4
; SI-NEXT:  .LBB48_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB48_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; SI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; SI-NEXT:    v_add_f32_e32 v12, 1.0, v12
; SI-NEXT:    v_add_f32_e32 v32, 1.0, v32
; SI-NEXT:    v_add_f32_e32 v20, 1.0, v20
; SI-NEXT:    v_add_f32_e32 v16, 1.0, v16
; SI-NEXT:    v_add_f32_e32 v28, 1.0, v28
; SI-NEXT:    v_add_f32_e32 v24, 1.0, v24
; SI-NEXT:    v_alignbit_b32 v27, v28, v24, 24
; SI-NEXT:    v_alignbit_b32 v26, v28, v24, 16
; SI-NEXT:    v_alignbit_b32 v25, v28, v24, 8
; SI-NEXT:    v_alignbit_b32 v19, v20, v16, 24
; SI-NEXT:    v_alignbit_b32 v18, v20, v16, 16
; SI-NEXT:    v_alignbit_b32 v17, v20, v16, 8
; SI-NEXT:    v_alignbit_b32 v11, v12, v32, 24
; SI-NEXT:    v_alignbit_b32 v10, v12, v32, 16
; SI-NEXT:    v_alignbit_b32 v9, v12, v32, 8
; SI-NEXT:    v_alignbit_b32 v3, v4, v0, 24
; SI-NEXT:    v_alignbit_b32 v2, v4, v0, 16
; SI-NEXT:    v_alignbit_b32 v1, v4, v0, 8
; SI-NEXT:    v_lshrrev_b32_e32 v31, 24, v28
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v28
; SI-NEXT:    v_lshrrev_b32_e32 v29, 8, v28
; SI-NEXT:    v_lshrrev_b32_e32 v23, 24, v20
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v20
; SI-NEXT:    v_lshrrev_b32_e32 v21, 8, v20
; SI-NEXT:    v_lshrrev_b32_e32 v15, 24, v12
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v12
; SI-NEXT:    v_lshrrev_b32_e32 v13, 8, v12
; SI-NEXT:    v_lshrrev_b32_e32 v7, 24, v4
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v4
; SI-NEXT:    v_lshrrev_b32_e32 v5, 8, v4
; SI-NEXT:  .LBB48_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_mov_b32_e32 v8, v32
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v8f32_to_v32i8:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_mov_b32_e32 v33, v5
; VI-NEXT:    v_mov_b32_e32 v32, v4
; VI-NEXT:    v_mov_b32_e32 v35, v3
; VI-NEXT:    v_mov_b32_e32 v34, v2
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr2
; VI-NEXT:    ; implicit-def: $vgpr5
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr9
; VI-NEXT:    ; implicit-def: $vgpr10
; VI-NEXT:    ; implicit-def: $vgpr13
; VI-NEXT:    ; implicit-def: $vgpr14
; VI-NEXT:    ; implicit-def: $vgpr15
; VI-NEXT:    ; implicit-def: $vgpr17
; VI-NEXT:    ; implicit-def: $vgpr18
; VI-NEXT:    ; implicit-def: $vgpr21
; VI-NEXT:    ; implicit-def: $vgpr22
; VI-NEXT:    ; implicit-def: $vgpr23
; VI-NEXT:    ; implicit-def: $vgpr25
; VI-NEXT:    ; implicit-def: $vgpr26
; VI-NEXT:    ; implicit-def: $vgpr29
; VI-NEXT:    ; implicit-def: $vgpr30
; VI-NEXT:    ; implicit-def: $vgpr31
; VI-NEXT:    ; implicit-def: $vgpr3
; VI-NEXT:    ; implicit-def: $vgpr11
; VI-NEXT:    ; implicit-def: $vgpr19
; VI-NEXT:    ; implicit-def: $vgpr27
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB48_2
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v25, 8, v6
; VI-NEXT:    v_lshrrev_b32_e32 v23, 24, v33
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v33
; VI-NEXT:    v_lshrrev_b32_e32 v21, 8, v33
; VI-NEXT:    v_lshrrev_b32_e32 v18, 16, v32
; VI-NEXT:    v_lshrrev_b32_e32 v17, 8, v32
; VI-NEXT:    v_lshrrev_b32_e32 v15, 24, v35
; VI-NEXT:    v_lshrrev_b32_e32 v14, 16, v35
; VI-NEXT:    v_lshrrev_b32_e32 v13, 8, v35
; VI-NEXT:    v_lshrrev_b32_e32 v10, 16, v34
; VI-NEXT:    v_lshrrev_b32_e32 v9, 8, v34
; VI-NEXT:    v_lshrrev_b32_e32 v36, 24, v1
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; VI-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; VI-NEXT:    v_lshrrev_b32_e32 v38, 8, v0
; VI-NEXT:    v_lshrrev_b64 v[27:28], 24, v[6:7]
; VI-NEXT:    v_lshrrev_b64 v[19:20], 24, v[32:33]
; VI-NEXT:    v_lshrrev_b64 v[11:12], 24, v[34:35]
; VI-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; VI-NEXT:  .LBB48_2: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB48_4
; VI-NEXT:  ; %bb.3: ; %cmp.true
; VI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; VI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; VI-NEXT:    v_add_f32_e32 v35, 1.0, v35
; VI-NEXT:    v_add_f32_e32 v34, 1.0, v34
; VI-NEXT:    v_add_f32_e32 v33, 1.0, v33
; VI-NEXT:    v_add_f32_e32 v32, 1.0, v32
; VI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; VI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; VI-NEXT:    v_lshrrev_b64 v[27:28], 24, v[6:7]
; VI-NEXT:    v_lshrrev_b64 v[19:20], 24, v[32:33]
; VI-NEXT:    v_lshrrev_b64 v[11:12], 24, v[34:35]
; VI-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; VI-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v25, 8, v6
; VI-NEXT:    v_lshrrev_b32_e32 v23, 24, v33
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v33
; VI-NEXT:    v_lshrrev_b32_e32 v21, 8, v33
; VI-NEXT:    v_lshrrev_b32_e32 v18, 16, v32
; VI-NEXT:    v_lshrrev_b32_e32 v17, 8, v32
; VI-NEXT:    v_lshrrev_b32_e32 v15, 24, v35
; VI-NEXT:    v_lshrrev_b32_e32 v14, 16, v35
; VI-NEXT:    v_lshrrev_b32_e32 v13, 8, v35
; VI-NEXT:    v_lshrrev_b32_e32 v10, 16, v34
; VI-NEXT:    v_lshrrev_b32_e32 v9, 8, v34
; VI-NEXT:    v_lshrrev_b32_e32 v36, 24, v1
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; VI-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; VI-NEXT:    v_lshrrev_b32_e32 v38, 8, v0
; VI-NEXT:  .LBB48_4: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    v_mov_b32_e32 v4, v1
; VI-NEXT:    v_mov_b32_e32 v8, v34
; VI-NEXT:    v_mov_b32_e32 v12, v35
; VI-NEXT:    v_mov_b32_e32 v16, v32
; VI-NEXT:    v_mov_b32_e32 v20, v33
; VI-NEXT:    v_mov_b32_e32 v24, v6
; VI-NEXT:    v_mov_b32_e32 v28, v7
; VI-NEXT:    v_mov_b32_e32 v1, v38
; VI-NEXT:    v_mov_b32_e32 v6, v37
; VI-NEXT:    v_mov_b32_e32 v7, v36
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v8f32_to_v32i8:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_mov_b32_e32 v33, v5
; GFX9-NEXT:    v_mov_b32_e32 v32, v4
; GFX9-NEXT:    v_mov_b32_e32 v35, v3
; GFX9-NEXT:    v_mov_b32_e32 v34, v2
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr2
; GFX9-NEXT:    ; implicit-def: $vgpr5
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr9
; GFX9-NEXT:    ; implicit-def: $vgpr10
; GFX9-NEXT:    ; implicit-def: $vgpr13
; GFX9-NEXT:    ; implicit-def: $vgpr14
; GFX9-NEXT:    ; implicit-def: $vgpr15
; GFX9-NEXT:    ; implicit-def: $vgpr17
; GFX9-NEXT:    ; implicit-def: $vgpr18
; GFX9-NEXT:    ; implicit-def: $vgpr21
; GFX9-NEXT:    ; implicit-def: $vgpr22
; GFX9-NEXT:    ; implicit-def: $vgpr23
; GFX9-NEXT:    ; implicit-def: $vgpr25
; GFX9-NEXT:    ; implicit-def: $vgpr26
; GFX9-NEXT:    ; implicit-def: $vgpr29
; GFX9-NEXT:    ; implicit-def: $vgpr30
; GFX9-NEXT:    ; implicit-def: $vgpr31
; GFX9-NEXT:    ; implicit-def: $vgpr3
; GFX9-NEXT:    ; implicit-def: $vgpr11
; GFX9-NEXT:    ; implicit-def: $vgpr19
; GFX9-NEXT:    ; implicit-def: $vgpr27
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB48_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 8, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 24, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 8, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v18, 16, v32
; GFX9-NEXT:    v_lshrrev_b32_e32 v17, 8, v32
; GFX9-NEXT:    v_lshrrev_b32_e32 v15, 24, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v14, 16, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v13, 8, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v10, 16, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v9, 8, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 24, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 8, v0
; GFX9-NEXT:    v_lshrrev_b64 v[27:28], 24, v[6:7]
; GFX9-NEXT:    v_lshrrev_b64 v[19:20], 24, v[32:33]
; GFX9-NEXT:    v_lshrrev_b64 v[11:12], 24, v[34:35]
; GFX9-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; GFX9-NEXT:  .LBB48_2: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB48_4
; GFX9-NEXT:  ; %bb.3: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e32 v1, 1.0, v1
; GFX9-NEXT:    v_add_f32_e32 v0, 1.0, v0
; GFX9-NEXT:    v_add_f32_e32 v35, 1.0, v35
; GFX9-NEXT:    v_add_f32_e32 v34, 1.0, v34
; GFX9-NEXT:    v_add_f32_e32 v33, 1.0, v33
; GFX9-NEXT:    v_add_f32_e32 v32, 1.0, v32
; GFX9-NEXT:    v_add_f32_e32 v7, 1.0, v7
; GFX9-NEXT:    v_add_f32_e32 v6, 1.0, v6
; GFX9-NEXT:    v_lshrrev_b64 v[27:28], 24, v[6:7]
; GFX9-NEXT:    v_lshrrev_b64 v[19:20], 24, v[32:33]
; GFX9-NEXT:    v_lshrrev_b64 v[11:12], 24, v[34:35]
; GFX9-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 8, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 24, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 8, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v18, 16, v32
; GFX9-NEXT:    v_lshrrev_b32_e32 v17, 8, v32
; GFX9-NEXT:    v_lshrrev_b32_e32 v15, 24, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v14, 16, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v13, 8, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v10, 16, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v9, 8, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 24, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 8, v0
; GFX9-NEXT:  .LBB48_4: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    v_mov_b32_e32 v4, v1
; GFX9-NEXT:    v_mov_b32_e32 v8, v34
; GFX9-NEXT:    v_mov_b32_e32 v12, v35
; GFX9-NEXT:    v_mov_b32_e32 v16, v32
; GFX9-NEXT:    v_mov_b32_e32 v20, v33
; GFX9-NEXT:    v_mov_b32_e32 v24, v6
; GFX9-NEXT:    v_mov_b32_e32 v28, v7
; GFX9-NEXT:    v_mov_b32_e32 v1, v38
; GFX9-NEXT:    v_mov_b32_e32 v6, v37
; GFX9-NEXT:    v_mov_b32_e32 v7, v36
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v8f32_to_v32i8:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v33, v7 :: v_dual_mov_b32 v32, v6
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v27, v5 :: v_dual_mov_b32 v26, v4
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v19, v3 :: v_dual_mov_b32 v18, v2
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v11, v1 :: v_dual_mov_b32 v10, v0
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr1_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr3_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr5_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr7_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr36_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr15_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr17_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr35_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr21_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr23_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr25_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr34_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr29_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr31_lo16
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB48_2
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[34:35], 24, v[32:33]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[35:36], 24, v[26:27]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v27
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v27
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v26
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v18
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[36:37], 24, v[18:19]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[10:11]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v10
; GFX11-TRUE16-NEXT:  .LBB48_2: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB48_4
; GFX11-TRUE16-NEXT:  ; %bb.3: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v11, 1.0, v11 :: v_dual_add_f32 v32, 1.0, v32
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v33, 1.0, v33 :: v_dual_add_f32 v10, 1.0, v10
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v19, 1.0, v19 :: v_dual_add_f32 v26, 1.0, v26
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v27, 1.0, v27 :: v_dual_add_f32 v18, 1.0, v18
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[34:35], 24, v[32:33]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[10:11]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[35:36], 24, v[26:27]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[36:37], 24, v[18:19]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v27
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v27
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v26
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v18
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v10
; GFX11-TRUE16-NEXT:  .LBB48_4: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.l, v10.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.l, v10.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v4.l, v11.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v6.l, v11.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v8.l, v18.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v10.l, v18.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v11.l, v36.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v12.l, v19.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v14.l, v19.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v16.l, v26.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v18.l, v26.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v19.l, v35.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v20.l, v27.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v22.l, v27.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v24.l, v32.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v26.l, v32.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v27.l, v34.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v28.l, v33.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v30.l, v33.h
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v8f32_to_v32i8:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v33, v7 :: v_dual_mov_b32 v32, v6
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v35, v5 :: v_dual_mov_b32 v34, v4
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v37, v3 :: v_dual_mov_b32 v36, v2
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v39, v1 :: v_dual_mov_b32 v38, v0
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v8
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr1
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr2
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr3
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr5
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr6
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr7
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr9
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr10
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr11
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr13
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr14
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr15
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr17
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr18
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr19
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr21
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr22
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr23
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr25
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr26
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr27
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr29
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr30
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr31
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB48_2
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v32
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v18, 16, v34
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v34
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v14, 16, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v10, 16, v36
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v36
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v6, 16, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v38
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[27:28], 24, v[32:33]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[19:20], 24, v[34:35]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[11:12], 24, v[36:37]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[38:39]
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v38
; GFX11-FAKE16-NEXT:  .LBB48_2: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB48_4
; GFX11-FAKE16-NEXT:  ; %bb.3: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v39, 1.0, v39 :: v_dual_add_f32 v32, 1.0, v32
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v37, 1.0, v37 :: v_dual_add_f32 v34, 1.0, v34
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v35, 1.0, v35 :: v_dual_add_f32 v36, 1.0, v36
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v33, 1.0, v33 :: v_dual_add_f32 v38, 1.0, v38
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v32
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[19:20], 24, v[34:35]
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[11:12], 24, v[36:37]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[27:28], 24, v[32:33]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[38:39]
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v18, 16, v34
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v34
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v14, 16, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v10, 16, v36
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v36
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v6, 16, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v38
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v38
; GFX11-FAKE16-NEXT:  .LBB48_4: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v0, v38
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v4, v39
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v8, v36
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v12, v37
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v16, v34
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v20, v35
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v24, v32
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v28, v33
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <8 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <8 x float> %a1 to <32 x i8>
  br label %end

cmp.false:
  %a3 = bitcast <8 x float> %a to <32 x i8>
  br label %end

end:
  %phi = phi <32 x i8> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x i8> %phi
}

define inreg <32 x i8> @bitcast_v8f32_to_v32i8_scalar(<8 x float> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v8f32_to_v32i8_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB49_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_lshr_b32 s72, s23, 24
; SI-NEXT:    s_lshr_b32 s74, s23, 16
; SI-NEXT:    s_lshr_b32 s75, s23, 8
; SI-NEXT:    s_lshr_b32 s61, s21, 24
; SI-NEXT:    s_lshr_b32 s63, s21, 16
; SI-NEXT:    s_lshr_b32 s73, s21, 8
; SI-NEXT:    s_lshr_b32 s58, s19, 24
; SI-NEXT:    s_lshr_b32 s60, s19, 16
; SI-NEXT:    s_lshr_b32 s62, s19, 8
; SI-NEXT:    s_lshr_b32 s56, s17, 24
; SI-NEXT:    s_lshr_b32 s57, s17, 16
; SI-NEXT:    s_lshr_b32 s59, s17, 8
; SI-NEXT:    s_lshr_b64 s[40:41], s[22:23], 24
; SI-NEXT:    s_lshr_b64 s[42:43], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[44:45], s[22:23], 8
; SI-NEXT:    s_lshr_b64 s[24:25], s[20:21], 24
; SI-NEXT:    s_lshr_b64 s[26:27], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[28:29], s[20:21], 8
; SI-NEXT:    s_lshr_b64 s[10:11], s[18:19], 24
; SI-NEXT:    s_lshr_b64 s[12:13], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[14:15], s[18:19], 8
; SI-NEXT:    s_lshr_b64 s[4:5], s[16:17], 24
; SI-NEXT:    s_lshr_b64 s[6:7], s[16:17], 16
; SI-NEXT:    s_lshr_b64 s[8:9], s[16:17], 8
; SI-NEXT:    s_cbranch_execnz .LBB49_4
; SI-NEXT:  .LBB49_2: ; %cmp.true
; SI-NEXT:    v_add_f32_e64 v39, s17, 1.0
; SI-NEXT:    v_add_f32_e64 v38, s16, 1.0
; SI-NEXT:    v_add_f32_e64 v49, s23, 1.0
; SI-NEXT:    v_add_f32_e64 v48, s22, 1.0
; SI-NEXT:    v_add_f32_e64 v35, s19, 1.0
; SI-NEXT:    v_add_f32_e64 v34, s18, 1.0
; SI-NEXT:    v_add_f32_e64 v37, s21, 1.0
; SI-NEXT:    v_add_f32_e64 v36, s20, 1.0
; SI-NEXT:    v_lshr_b64 v[27:28], v[48:49], 24
; SI-NEXT:    v_lshr_b64 v[24:25], v[48:49], 16
; SI-NEXT:    v_lshr_b64 v[0:1], v[38:39], 16
; SI-NEXT:    v_lshr_b64 v[25:26], v[48:49], 8
; SI-NEXT:    v_lshr_b64 v[19:20], v[36:37], 24
; SI-NEXT:    v_lshr_b64 v[32:33], v[36:37], 16
; SI-NEXT:    v_lshr_b64 v[17:18], v[36:37], 8
; SI-NEXT:    v_lshr_b64 v[11:12], v[34:35], 24
; SI-NEXT:    v_lshr_b64 v[28:29], v[34:35], 16
; SI-NEXT:    v_lshr_b64 v[9:10], v[34:35], 8
; SI-NEXT:    v_lshr_b64 v[3:4], v[38:39], 24
; SI-NEXT:    v_lshr_b64 v[1:2], v[38:39], 8
; SI-NEXT:    v_lshrrev_b32_e32 v31, 24, v49
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v49
; SI-NEXT:    v_lshrrev_b32_e32 v29, 8, v49
; SI-NEXT:    v_lshrrev_b32_e32 v23, 24, v37
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v37
; SI-NEXT:    v_lshrrev_b32_e32 v21, 8, v37
; SI-NEXT:    v_lshrrev_b32_e32 v15, 24, v35
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v35
; SI-NEXT:    v_lshrrev_b32_e32 v13, 8, v35
; SI-NEXT:    v_lshrrev_b32_e32 v7, 24, v39
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v39
; SI-NEXT:    v_lshrrev_b32_e32 v5, 8, v39
; SI-NEXT:    s_branch .LBB49_5
; SI-NEXT:  .LBB49_3:
; SI-NEXT:    ; implicit-def: $sgpr8
; SI-NEXT:    ; implicit-def: $sgpr6
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr59
; SI-NEXT:    ; implicit-def: $sgpr57
; SI-NEXT:    ; implicit-def: $sgpr56
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr12
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr62
; SI-NEXT:    ; implicit-def: $sgpr60
; SI-NEXT:    ; implicit-def: $sgpr58
; SI-NEXT:    ; implicit-def: $sgpr28
; SI-NEXT:    ; implicit-def: $sgpr26
; SI-NEXT:    ; implicit-def: $sgpr24
; SI-NEXT:    ; implicit-def: $sgpr73
; SI-NEXT:    ; implicit-def: $sgpr63
; SI-NEXT:    ; implicit-def: $sgpr61
; SI-NEXT:    ; implicit-def: $sgpr44
; SI-NEXT:    ; implicit-def: $sgpr42
; SI-NEXT:    ; implicit-def: $sgpr40
; SI-NEXT:    ; implicit-def: $sgpr75
; SI-NEXT:    ; implicit-def: $sgpr74
; SI-NEXT:    ; implicit-def: $sgpr72
; SI-NEXT:    s_branch .LBB49_2
; SI-NEXT:  .LBB49_4:
; SI-NEXT:    v_mov_b32_e32 v38, s16
; SI-NEXT:    v_mov_b32_e32 v39, s17
; SI-NEXT:    v_mov_b32_e32 v34, s18
; SI-NEXT:    v_mov_b32_e32 v35, s19
; SI-NEXT:    v_mov_b32_e32 v36, s20
; SI-NEXT:    v_mov_b32_e32 v37, s21
; SI-NEXT:    v_mov_b32_e32 v48, s22
; SI-NEXT:    v_mov_b32_e32 v49, s23
; SI-NEXT:    v_mov_b32_e32 v5, s59
; SI-NEXT:    v_mov_b32_e32 v6, s57
; SI-NEXT:    v_mov_b32_e32 v7, s56
; SI-NEXT:    v_mov_b32_e32 v13, s62
; SI-NEXT:    v_mov_b32_e32 v14, s60
; SI-NEXT:    v_mov_b32_e32 v15, s58
; SI-NEXT:    v_mov_b32_e32 v21, s73
; SI-NEXT:    v_mov_b32_e32 v22, s63
; SI-NEXT:    v_mov_b32_e32 v23, s61
; SI-NEXT:    v_mov_b32_e32 v29, s75
; SI-NEXT:    v_mov_b32_e32 v30, s74
; SI-NEXT:    v_mov_b32_e32 v31, s72
; SI-NEXT:    v_mov_b32_e32 v27, s40
; SI-NEXT:    v_mov_b32_e32 v24, s42
; SI-NEXT:    v_mov_b32_e32 v25, s44
; SI-NEXT:    v_mov_b32_e32 v19, s24
; SI-NEXT:    v_mov_b32_e32 v32, s26
; SI-NEXT:    v_mov_b32_e32 v17, s28
; SI-NEXT:    v_mov_b32_e32 v11, s10
; SI-NEXT:    v_mov_b32_e32 v28, s12
; SI-NEXT:    v_mov_b32_e32 v9, s14
; SI-NEXT:    v_mov_b32_e32 v3, s4
; SI-NEXT:    v_mov_b32_e32 v0, s6
; SI-NEXT:    v_mov_b32_e32 v1, s8
; SI-NEXT:  .LBB49_5: ; %end
; SI-NEXT:    v_mov_b32_e32 v2, v0
; SI-NEXT:    v_mov_b32_e32 v0, v38
; SI-NEXT:    v_mov_b32_e32 v4, v39
; SI-NEXT:    v_mov_b32_e32 v10, v28
; SI-NEXT:    v_mov_b32_e32 v8, v34
; SI-NEXT:    v_mov_b32_e32 v12, v35
; SI-NEXT:    v_mov_b32_e32 v18, v32
; SI-NEXT:    v_mov_b32_e32 v16, v36
; SI-NEXT:    v_mov_b32_e32 v20, v37
; SI-NEXT:    v_mov_b32_e32 v26, v24
; SI-NEXT:    v_mov_b32_e32 v24, v48
; SI-NEXT:    v_mov_b32_e32 v28, v49
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v8f32_to_v32i8_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB49_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_lshr_b32 s14, s23, 24
; VI-NEXT:    s_lshr_b32 s15, s23, 16
; VI-NEXT:    s_lshr_b32 s25, s23, 8
; VI-NEXT:    s_lshr_b32 s24, s22, 16
; VI-NEXT:    s_lshr_b32 s26, s22, 8
; VI-NEXT:    s_lshr_b32 s27, s21, 24
; VI-NEXT:    s_lshr_b32 s28, s21, 16
; VI-NEXT:    s_lshr_b32 s40, s21, 8
; VI-NEXT:    s_lshr_b32 s29, s20, 16
; VI-NEXT:    s_lshr_b32 s41, s20, 8
; VI-NEXT:    s_lshr_b32 s42, s19, 24
; VI-NEXT:    s_lshr_b32 s43, s19, 16
; VI-NEXT:    s_lshr_b32 s45, s19, 8
; VI-NEXT:    s_lshr_b32 s44, s18, 16
; VI-NEXT:    s_lshr_b32 s46, s18, 8
; VI-NEXT:    s_lshr_b32 s47, s17, 24
; VI-NEXT:    s_lshr_b32 s56, s17, 16
; VI-NEXT:    s_lshr_b32 s58, s17, 8
; VI-NEXT:    s_lshr_b32 s57, s16, 16
; VI-NEXT:    s_lshr_b32 s59, s16, 8
; VI-NEXT:    s_lshr_b64 s[10:11], s[22:23], 24
; VI-NEXT:    s_lshr_b64 s[8:9], s[20:21], 24
; VI-NEXT:    s_lshr_b64 s[6:7], s[18:19], 24
; VI-NEXT:    s_lshr_b64 s[4:5], s[16:17], 24
; VI-NEXT:    s_cbranch_execnz .LBB49_4
; VI-NEXT:  .LBB49_2: ; %cmp.true
; VI-NEXT:    v_add_f32_e64 v1, s17, 1.0
; VI-NEXT:    v_add_f32_e64 v0, s16, 1.0
; VI-NEXT:    v_add_f32_e64 v9, s19, 1.0
; VI-NEXT:    v_add_f32_e64 v8, s18, 1.0
; VI-NEXT:    v_add_f32_e64 v17, s21, 1.0
; VI-NEXT:    v_add_f32_e64 v16, s20, 1.0
; VI-NEXT:    v_add_f32_e64 v25, s23, 1.0
; VI-NEXT:    v_add_f32_e64 v24, s22, 1.0
; VI-NEXT:    v_lshrrev_b64 v[27:28], 24, v[24:25]
; VI-NEXT:    v_lshrrev_b64 v[19:20], 24, v[16:17]
; VI-NEXT:    v_lshrrev_b64 v[11:12], 24, v[8:9]
; VI-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; VI-NEXT:    v_lshrrev_b32_e32 v31, 24, v25
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v25
; VI-NEXT:    v_lshrrev_b32_e32 v29, 8, v25
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v24
; VI-NEXT:    v_lshrrev_b32_e32 v32, 8, v24
; VI-NEXT:    v_lshrrev_b32_e32 v23, 24, v17
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; VI-NEXT:    v_lshrrev_b32_e32 v21, 8, v17
; VI-NEXT:    v_lshrrev_b32_e32 v18, 16, v16
; VI-NEXT:    v_lshrrev_b32_e32 v33, 8, v16
; VI-NEXT:    v_lshrrev_b32_e32 v15, 24, v9
; VI-NEXT:    v_lshrrev_b32_e32 v14, 16, v9
; VI-NEXT:    v_lshrrev_b32_e32 v13, 8, v9
; VI-NEXT:    v_lshrrev_b32_e32 v10, 16, v8
; VI-NEXT:    v_lshrrev_b32_e32 v34, 8, v8
; VI-NEXT:    v_lshrrev_b32_e32 v7, 24, v1
; VI-NEXT:    v_lshrrev_b32_e32 v6, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; VI-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; VI-NEXT:    v_lshrrev_b32_e32 v35, 8, v0
; VI-NEXT:    s_branch .LBB49_5
; VI-NEXT:  .LBB49_3:
; VI-NEXT:    ; implicit-def: $sgpr59
; VI-NEXT:    ; implicit-def: $sgpr57
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr58
; VI-NEXT:    ; implicit-def: $sgpr56
; VI-NEXT:    ; implicit-def: $sgpr47
; VI-NEXT:    ; implicit-def: $sgpr46
; VI-NEXT:    ; implicit-def: $sgpr44
; VI-NEXT:    ; implicit-def: $sgpr6
; VI-NEXT:    ; implicit-def: $sgpr45
; VI-NEXT:    ; implicit-def: $sgpr43
; VI-NEXT:    ; implicit-def: $sgpr42
; VI-NEXT:    ; implicit-def: $sgpr41
; VI-NEXT:    ; implicit-def: $sgpr29
; VI-NEXT:    ; implicit-def: $sgpr8
; VI-NEXT:    ; implicit-def: $sgpr40
; VI-NEXT:    ; implicit-def: $sgpr28
; VI-NEXT:    ; implicit-def: $sgpr27
; VI-NEXT:    ; implicit-def: $sgpr26
; VI-NEXT:    ; implicit-def: $sgpr24
; VI-NEXT:    ; implicit-def: $sgpr10
; VI-NEXT:    ; implicit-def: $sgpr25
; VI-NEXT:    ; implicit-def: $sgpr15
; VI-NEXT:    ; implicit-def: $sgpr14
; VI-NEXT:    s_branch .LBB49_2
; VI-NEXT:  .LBB49_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v8, s18
; VI-NEXT:    v_mov_b32_e32 v9, s19
; VI-NEXT:    v_mov_b32_e32 v16, s20
; VI-NEXT:    v_mov_b32_e32 v17, s21
; VI-NEXT:    v_mov_b32_e32 v24, s22
; VI-NEXT:    v_mov_b32_e32 v25, s23
; VI-NEXT:    v_mov_b32_e32 v35, s59
; VI-NEXT:    v_mov_b32_e32 v2, s57
; VI-NEXT:    v_mov_b32_e32 v5, s58
; VI-NEXT:    v_mov_b32_e32 v6, s56
; VI-NEXT:    v_mov_b32_e32 v7, s47
; VI-NEXT:    v_mov_b32_e32 v34, s46
; VI-NEXT:    v_mov_b32_e32 v10, s44
; VI-NEXT:    v_mov_b32_e32 v13, s45
; VI-NEXT:    v_mov_b32_e32 v14, s43
; VI-NEXT:    v_mov_b32_e32 v15, s42
; VI-NEXT:    v_mov_b32_e32 v33, s41
; VI-NEXT:    v_mov_b32_e32 v18, s29
; VI-NEXT:    v_mov_b32_e32 v21, s40
; VI-NEXT:    v_mov_b32_e32 v22, s28
; VI-NEXT:    v_mov_b32_e32 v23, s27
; VI-NEXT:    v_mov_b32_e32 v32, s26
; VI-NEXT:    v_mov_b32_e32 v26, s24
; VI-NEXT:    v_mov_b32_e32 v29, s25
; VI-NEXT:    v_mov_b32_e32 v30, s15
; VI-NEXT:    v_mov_b32_e32 v31, s14
; VI-NEXT:    v_mov_b32_e32 v27, s10
; VI-NEXT:    v_mov_b32_e32 v19, s8
; VI-NEXT:    v_mov_b32_e32 v11, s6
; VI-NEXT:    v_mov_b32_e32 v3, s4
; VI-NEXT:  .LBB49_5: ; %end
; VI-NEXT:    v_mov_b32_e32 v4, v1
; VI-NEXT:    v_mov_b32_e32 v12, v9
; VI-NEXT:    v_mov_b32_e32 v20, v17
; VI-NEXT:    v_mov_b32_e32 v28, v25
; VI-NEXT:    v_mov_b32_e32 v1, v35
; VI-NEXT:    v_mov_b32_e32 v9, v34
; VI-NEXT:    v_mov_b32_e32 v17, v33
; VI-NEXT:    v_mov_b32_e32 v25, v32
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v8f32_to_v32i8_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB49_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_lshr_b32 s14, s23, 24
; GFX9-NEXT:    s_lshr_b32 s15, s23, 16
; GFX9-NEXT:    s_lshr_b32 s25, s23, 8
; GFX9-NEXT:    s_lshr_b32 s24, s22, 16
; GFX9-NEXT:    s_lshr_b32 s26, s22, 8
; GFX9-NEXT:    s_lshr_b32 s27, s21, 24
; GFX9-NEXT:    s_lshr_b32 s28, s21, 16
; GFX9-NEXT:    s_lshr_b32 s40, s21, 8
; GFX9-NEXT:    s_lshr_b32 s29, s20, 16
; GFX9-NEXT:    s_lshr_b32 s41, s20, 8
; GFX9-NEXT:    s_lshr_b32 s42, s19, 24
; GFX9-NEXT:    s_lshr_b32 s43, s19, 16
; GFX9-NEXT:    s_lshr_b32 s45, s19, 8
; GFX9-NEXT:    s_lshr_b32 s44, s18, 16
; GFX9-NEXT:    s_lshr_b32 s46, s18, 8
; GFX9-NEXT:    s_lshr_b32 s47, s17, 24
; GFX9-NEXT:    s_lshr_b32 s56, s17, 16
; GFX9-NEXT:    s_lshr_b32 s58, s17, 8
; GFX9-NEXT:    s_lshr_b32 s57, s16, 16
; GFX9-NEXT:    s_lshr_b32 s59, s16, 8
; GFX9-NEXT:    s_lshr_b64 s[10:11], s[22:23], 24
; GFX9-NEXT:    s_lshr_b64 s[8:9], s[20:21], 24
; GFX9-NEXT:    s_lshr_b64 s[6:7], s[18:19], 24
; GFX9-NEXT:    s_lshr_b64 s[4:5], s[16:17], 24
; GFX9-NEXT:    s_cbranch_execnz .LBB49_4
; GFX9-NEXT:  .LBB49_2: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e64 v1, s17, 1.0
; GFX9-NEXT:    v_add_f32_e64 v0, s16, 1.0
; GFX9-NEXT:    v_add_f32_e64 v9, s19, 1.0
; GFX9-NEXT:    v_add_f32_e64 v8, s18, 1.0
; GFX9-NEXT:    v_add_f32_e64 v17, s21, 1.0
; GFX9-NEXT:    v_add_f32_e64 v16, s20, 1.0
; GFX9-NEXT:    v_add_f32_e64 v25, s23, 1.0
; GFX9-NEXT:    v_add_f32_e64 v24, s22, 1.0
; GFX9-NEXT:    v_lshrrev_b64 v[27:28], 24, v[24:25]
; GFX9-NEXT:    v_lshrrev_b64 v[19:20], 24, v[16:17]
; GFX9-NEXT:    v_lshrrev_b64 v[11:12], 24, v[8:9]
; GFX9-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 24, v25
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v25
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 8, v25
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v24
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 8, v24
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 24, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 8, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v18, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 8, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v15, 24, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v14, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v13, 8, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v10, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 8, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v7, 24, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v6, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 8, v0
; GFX9-NEXT:    s_branch .LBB49_5
; GFX9-NEXT:  .LBB49_3:
; GFX9-NEXT:    ; implicit-def: $sgpr59
; GFX9-NEXT:    ; implicit-def: $sgpr57
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr58
; GFX9-NEXT:    ; implicit-def: $sgpr56
; GFX9-NEXT:    ; implicit-def: $sgpr47
; GFX9-NEXT:    ; implicit-def: $sgpr46
; GFX9-NEXT:    ; implicit-def: $sgpr44
; GFX9-NEXT:    ; implicit-def: $sgpr6
; GFX9-NEXT:    ; implicit-def: $sgpr45
; GFX9-NEXT:    ; implicit-def: $sgpr43
; GFX9-NEXT:    ; implicit-def: $sgpr42
; GFX9-NEXT:    ; implicit-def: $sgpr41
; GFX9-NEXT:    ; implicit-def: $sgpr29
; GFX9-NEXT:    ; implicit-def: $sgpr8
; GFX9-NEXT:    ; implicit-def: $sgpr40
; GFX9-NEXT:    ; implicit-def: $sgpr28
; GFX9-NEXT:    ; implicit-def: $sgpr27
; GFX9-NEXT:    ; implicit-def: $sgpr26
; GFX9-NEXT:    ; implicit-def: $sgpr24
; GFX9-NEXT:    ; implicit-def: $sgpr10
; GFX9-NEXT:    ; implicit-def: $sgpr25
; GFX9-NEXT:    ; implicit-def: $sgpr15
; GFX9-NEXT:    ; implicit-def: $sgpr14
; GFX9-NEXT:    s_branch .LBB49_2
; GFX9-NEXT:  .LBB49_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v8, s18
; GFX9-NEXT:    v_mov_b32_e32 v9, s19
; GFX9-NEXT:    v_mov_b32_e32 v16, s20
; GFX9-NEXT:    v_mov_b32_e32 v17, s21
; GFX9-NEXT:    v_mov_b32_e32 v24, s22
; GFX9-NEXT:    v_mov_b32_e32 v25, s23
; GFX9-NEXT:    v_mov_b32_e32 v35, s59
; GFX9-NEXT:    v_mov_b32_e32 v2, s57
; GFX9-NEXT:    v_mov_b32_e32 v5, s58
; GFX9-NEXT:    v_mov_b32_e32 v6, s56
; GFX9-NEXT:    v_mov_b32_e32 v7, s47
; GFX9-NEXT:    v_mov_b32_e32 v34, s46
; GFX9-NEXT:    v_mov_b32_e32 v10, s44
; GFX9-NEXT:    v_mov_b32_e32 v13, s45
; GFX9-NEXT:    v_mov_b32_e32 v14, s43
; GFX9-NEXT:    v_mov_b32_e32 v15, s42
; GFX9-NEXT:    v_mov_b32_e32 v33, s41
; GFX9-NEXT:    v_mov_b32_e32 v18, s29
; GFX9-NEXT:    v_mov_b32_e32 v21, s40
; GFX9-NEXT:    v_mov_b32_e32 v22, s28
; GFX9-NEXT:    v_mov_b32_e32 v23, s27
; GFX9-NEXT:    v_mov_b32_e32 v32, s26
; GFX9-NEXT:    v_mov_b32_e32 v26, s24
; GFX9-NEXT:    v_mov_b32_e32 v29, s25
; GFX9-NEXT:    v_mov_b32_e32 v30, s15
; GFX9-NEXT:    v_mov_b32_e32 v31, s14
; GFX9-NEXT:    v_mov_b32_e32 v27, s10
; GFX9-NEXT:    v_mov_b32_e32 v19, s8
; GFX9-NEXT:    v_mov_b32_e32 v11, s6
; GFX9-NEXT:    v_mov_b32_e32 v3, s4
; GFX9-NEXT:  .LBB49_5: ; %end
; GFX9-NEXT:    v_mov_b32_e32 v4, v1
; GFX9-NEXT:    v_mov_b32_e32 v12, v9
; GFX9-NEXT:    v_mov_b32_e32 v20, v17
; GFX9-NEXT:    v_mov_b32_e32 v28, v25
; GFX9-NEXT:    v_mov_b32_e32 v1, v35
; GFX9-NEXT:    v_mov_b32_e32 v9, v34
; GFX9-NEXT:    v_mov_b32_e32 v17, v33
; GFX9-NEXT:    v_mov_b32_e32 v25, v32
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v8f32_to_v32i8_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s12, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB49_3
; GFX11-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-NEXT:    s_lshr_b32 s13, s19, 24
; GFX11-NEXT:    s_lshr_b32 s14, s19, 16
; GFX11-NEXT:    s_lshr_b32 s20, s19, 8
; GFX11-NEXT:    s_lshr_b32 s15, s18, 16
; GFX11-NEXT:    s_lshr_b32 s21, s18, 8
; GFX11-NEXT:    s_lshr_b32 s22, s17, 24
; GFX11-NEXT:    s_lshr_b32 s23, s17, 16
; GFX11-NEXT:    s_lshr_b32 s25, s17, 8
; GFX11-NEXT:    s_lshr_b32 s24, s16, 16
; GFX11-NEXT:    s_lshr_b32 s26, s16, 8
; GFX11-NEXT:    s_lshr_b32 s27, s3, 24
; GFX11-NEXT:    s_lshr_b32 s28, s3, 16
; GFX11-NEXT:    s_lshr_b32 s40, s3, 8
; GFX11-NEXT:    s_lshr_b32 s29, s2, 16
; GFX11-NEXT:    s_lshr_b32 s41, s2, 8
; GFX11-NEXT:    s_lshr_b32 s42, s1, 24
; GFX11-NEXT:    s_lshr_b32 s43, s1, 16
; GFX11-NEXT:    s_lshr_b32 s45, s1, 8
; GFX11-NEXT:    s_lshr_b32 s44, s0, 16
; GFX11-NEXT:    s_lshr_b32 s46, s0, 8
; GFX11-NEXT:    s_lshr_b64 s[10:11], s[18:19], 24
; GFX11-NEXT:    s_lshr_b64 s[8:9], s[16:17], 24
; GFX11-NEXT:    s_lshr_b64 s[6:7], s[2:3], 24
; GFX11-NEXT:    s_lshr_b64 s[4:5], s[0:1], 24
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s12
; GFX11-NEXT:    s_cbranch_vccnz .LBB49_4
; GFX11-NEXT:  .LBB49_2: ; %cmp.true
; GFX11-NEXT:    v_add_f32_e64 v39, s1, 1.0
; GFX11-NEXT:    v_add_f32_e64 v37, s3, 1.0
; GFX11-NEXT:    v_add_f32_e64 v35, s17, 1.0
; GFX11-NEXT:    v_add_f32_e64 v33, s19, 1.0
; GFX11-NEXT:    v_add_f32_e64 v32, s18, 1.0
; GFX11-NEXT:    v_add_f32_e64 v34, s16, 1.0
; GFX11-NEXT:    v_add_f32_e64 v36, s2, 1.0
; GFX11-NEXT:    v_add_f32_e64 v38, s0, 1.0
; GFX11-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-NEXT:    v_lshrrev_b64 v[27:28], 24, v[32:33]
; GFX11-NEXT:    v_lshrrev_b64 v[19:20], 24, v[34:35]
; GFX11-NEXT:    v_lshrrev_b64 v[11:12], 24, v[36:37]
; GFX11-NEXT:    v_lshrrev_b64 v[3:4], 24, v[38:39]
; GFX11-NEXT:    v_lshrrev_b32_e32 v30, 16, v33
; GFX11-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-NEXT:    v_lshrrev_b32_e32 v26, 16, v32
; GFX11-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-NEXT:    v_lshrrev_b32_e32 v23, 24, v35
; GFX11-NEXT:    v_lshrrev_b32_e32 v22, 16, v35
; GFX11-NEXT:    v_lshrrev_b32_e32 v21, 8, v35
; GFX11-NEXT:    v_lshrrev_b32_e32 v18, 16, v34
; GFX11-NEXT:    v_lshrrev_b32_e32 v17, 8, v34
; GFX11-NEXT:    v_lshrrev_b32_e32 v15, 24, v37
; GFX11-NEXT:    v_lshrrev_b32_e32 v14, 16, v37
; GFX11-NEXT:    v_lshrrev_b32_e32 v13, 8, v37
; GFX11-NEXT:    v_lshrrev_b32_e32 v10, 16, v36
; GFX11-NEXT:    v_lshrrev_b32_e32 v9, 8, v36
; GFX11-NEXT:    v_lshrrev_b32_e32 v7, 24, v39
; GFX11-NEXT:    v_lshrrev_b32_e32 v6, 16, v39
; GFX11-NEXT:    v_lshrrev_b32_e32 v5, 8, v39
; GFX11-NEXT:    v_lshrrev_b32_e32 v2, 16, v38
; GFX11-NEXT:    v_lshrrev_b32_e32 v1, 8, v38
; GFX11-NEXT:    s_branch .LBB49_5
; GFX11-NEXT:  .LBB49_3:
; GFX11-NEXT:    ; implicit-def: $sgpr46
; GFX11-NEXT:    ; implicit-def: $sgpr44
; GFX11-NEXT:    ; implicit-def: $sgpr4
; GFX11-NEXT:    ; implicit-def: $sgpr45
; GFX11-NEXT:    ; implicit-def: $sgpr43
; GFX11-NEXT:    ; implicit-def: $sgpr42
; GFX11-NEXT:    ; implicit-def: $sgpr41
; GFX11-NEXT:    ; implicit-def: $sgpr29
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr40
; GFX11-NEXT:    ; implicit-def: $sgpr28
; GFX11-NEXT:    ; implicit-def: $sgpr27
; GFX11-NEXT:    ; implicit-def: $sgpr26
; GFX11-NEXT:    ; implicit-def: $sgpr24
; GFX11-NEXT:    ; implicit-def: $sgpr8
; GFX11-NEXT:    ; implicit-def: $sgpr25
; GFX11-NEXT:    ; implicit-def: $sgpr23
; GFX11-NEXT:    ; implicit-def: $sgpr22
; GFX11-NEXT:    ; implicit-def: $sgpr21
; GFX11-NEXT:    ; implicit-def: $sgpr15
; GFX11-NEXT:    ; implicit-def: $sgpr10
; GFX11-NEXT:    ; implicit-def: $sgpr20
; GFX11-NEXT:    ; implicit-def: $sgpr14
; GFX11-NEXT:    ; implicit-def: $sgpr13
; GFX11-NEXT:    s_branch .LBB49_2
; GFX11-NEXT:  .LBB49_4:
; GFX11-NEXT:    v_dual_mov_b32 v38, s0 :: v_dual_mov_b32 v39, s1
; GFX11-NEXT:    v_dual_mov_b32 v36, s2 :: v_dual_mov_b32 v37, s3
; GFX11-NEXT:    v_dual_mov_b32 v34, s16 :: v_dual_mov_b32 v35, s17
; GFX11-NEXT:    v_dual_mov_b32 v32, s18 :: v_dual_mov_b32 v33, s19
; GFX11-NEXT:    v_dual_mov_b32 v1, s46 :: v_dual_mov_b32 v2, s44
; GFX11-NEXT:    v_dual_mov_b32 v5, s45 :: v_dual_mov_b32 v6, s43
; GFX11-NEXT:    v_dual_mov_b32 v7, s42 :: v_dual_mov_b32 v10, s29
; GFX11-NEXT:    v_dual_mov_b32 v9, s41 :: v_dual_mov_b32 v14, s28
; GFX11-NEXT:    v_dual_mov_b32 v13, s40 :: v_dual_mov_b32 v18, s24
; GFX11-NEXT:    v_dual_mov_b32 v15, s27 :: v_dual_mov_b32 v22, s23
; GFX11-NEXT:    v_dual_mov_b32 v17, s26 :: v_dual_mov_b32 v26, s15
; GFX11-NEXT:    v_dual_mov_b32 v21, s25 :: v_dual_mov_b32 v30, s14
; GFX11-NEXT:    v_mov_b32_e32 v23, s22
; GFX11-NEXT:    v_mov_b32_e32 v25, s21
; GFX11-NEXT:    v_mov_b32_e32 v29, s20
; GFX11-NEXT:    v_mov_b32_e32 v31, s13
; GFX11-NEXT:    v_mov_b32_e32 v27, s10
; GFX11-NEXT:    v_mov_b32_e32 v19, s8
; GFX11-NEXT:    v_mov_b32_e32 v11, s6
; GFX11-NEXT:    v_mov_b32_e32 v3, s4
; GFX11-NEXT:  .LBB49_5: ; %end
; GFX11-NEXT:    v_mov_b32_e32 v0, v38
; GFX11-NEXT:    v_mov_b32_e32 v4, v39
; GFX11-NEXT:    v_mov_b32_e32 v8, v36
; GFX11-NEXT:    v_mov_b32_e32 v12, v37
; GFX11-NEXT:    v_mov_b32_e32 v16, v34
; GFX11-NEXT:    v_mov_b32_e32 v20, v35
; GFX11-NEXT:    v_mov_b32_e32 v24, v32
; GFX11-NEXT:    v_mov_b32_e32 v28, v33
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <8 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <8 x float> %a1 to <32 x i8>
  br label %end

cmp.false:
  %a3 = bitcast <8 x float> %a to <32 x i8>
  br label %end

end:
  %phi = phi <32 x i8> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x i8> %phi
}

define <8 x float> @bitcast_v32i8_to_v8f32(<32 x i8> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v32i8_to_v8f32:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_mov_b32_e32 v32, v2
; SI-NEXT:    v_mov_b32_e32 v31, v0
; SI-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:4
; SI-NEXT:    buffer_load_dword v2, off, s[0:3], s32
; SI-NEXT:    v_mov_b32_e32 v34, v6
; SI-NEXT:    v_mov_b32_e32 v33, v4
; SI-NEXT:    v_lshlrev_b32_e32 v52, 8, v1
; SI-NEXT:    v_lshlrev_b32_e32 v51, 24, v3
; SI-NEXT:    v_lshlrev_b32_e32 v50, 8, v5
; SI-NEXT:    v_lshlrev_b32_e32 v49, 24, v7
; SI-NEXT:    v_lshlrev_b32_e32 v48, 8, v9
; SI-NEXT:    v_lshlrev_b32_e32 v39, 24, v11
; SI-NEXT:    v_lshlrev_b32_e32 v38, 8, v13
; SI-NEXT:    v_lshlrev_b32_e32 v37, 24, v15
; SI-NEXT:    v_lshlrev_b32_e32 v36, 8, v17
; SI-NEXT:    v_lshlrev_b32_e32 v35, 24, v19
; SI-NEXT:    v_lshlrev_b32_e32 v19, 8, v21
; SI-NEXT:    v_lshlrev_b32_e32 v17, 24, v23
; SI-NEXT:    v_lshlrev_b32_e32 v15, 8, v25
; SI-NEXT:    v_lshlrev_b32_e32 v13, 24, v27
; SI-NEXT:    v_lshlrev_b32_e32 v11, 8, v29
; SI-NEXT:    s_waitcnt vmcnt(1)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v0
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_lshlrev_b32_e32 v9, 24, v2
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB50_3
; SI-NEXT:  ; %bb.1: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB50_4
; SI-NEXT:  .LBB50_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB50_3: ; %cmp.false
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v31
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v32
; SI-NEXT:    v_or_b32_e32 v0, v0, v52
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_or_b32_e32 v1, v51, v1
; SI-NEXT:    v_or_b32_e32 v0, v0, v1
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v33
; SI-NEXT:    v_and_b32_e32 v2, 0xff, v34
; SI-NEXT:    v_or_b32_e32 v1, v1, v50
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_or_b32_e32 v2, v49, v2
; SI-NEXT:    v_or_b32_e32 v1, v1, v2
; SI-NEXT:    v_and_b32_e32 v2, 0xff, v8
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v10
; SI-NEXT:    v_or_b32_e32 v2, v2, v48
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_or_b32_e32 v3, v39, v3
; SI-NEXT:    v_or_b32_e32 v2, v2, v3
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v12
; SI-NEXT:    v_and_b32_e32 v4, 0xff, v14
; SI-NEXT:    v_or_b32_e32 v3, v3, v38
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_or_b32_e32 v4, v37, v4
; SI-NEXT:    v_or_b32_e32 v3, v3, v4
; SI-NEXT:    v_and_b32_e32 v4, 0xff, v16
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v18
; SI-NEXT:    v_or_b32_e32 v4, v4, v36
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_or_b32_e32 v5, v35, v5
; SI-NEXT:    v_or_b32_e32 v4, v4, v5
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v20
; SI-NEXT:    v_and_b32_e32 v6, 0xff, v22
; SI-NEXT:    v_or_b32_e32 v5, v5, v19
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_or_b32_e32 v6, v17, v6
; SI-NEXT:    v_or_b32_e32 v5, v5, v6
; SI-NEXT:    v_and_b32_e32 v6, 0xff, v24
; SI-NEXT:    v_and_b32_e32 v7, 0xff, v26
; SI-NEXT:    v_or_b32_e32 v6, v6, v15
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_or_b32_e32 v7, v13, v7
; SI-NEXT:    v_or_b32_e32 v6, v6, v7
; SI-NEXT:    v_and_b32_e32 v7, 0xff, v28
; SI-NEXT:    v_and_b32_e32 v8, 0xff, v30
; SI-NEXT:    v_or_b32_e32 v7, v7, v11
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_or_b32_e32 v8, v9, v8
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    ; implicit-def: $vgpr31
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr24
; SI-NEXT:    ; implicit-def: $vgpr26
; SI-NEXT:    ; implicit-def: $vgpr28
; SI-NEXT:    ; implicit-def: $vgpr30
; SI-NEXT:    ; implicit-def: $vgpr52
; SI-NEXT:    ; implicit-def: $vgpr51
; SI-NEXT:    ; implicit-def: $vgpr50
; SI-NEXT:    ; implicit-def: $vgpr49
; SI-NEXT:    ; implicit-def: $vgpr48
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB50_2
; SI-NEXT:  .LBB50_4: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v31
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v32
; SI-NEXT:    v_or_b32_e32 v0, v52, v0
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v1
; SI-NEXT:    v_add_i32_e32 v0, vcc, 0x300, v0
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_or_b32_e32 v1, v51, v1
; SI-NEXT:    v_or_b32_e32 v0, v1, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v33
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v1
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v34
; SI-NEXT:    s_movk_i32 s6, 0x300
; SI-NEXT:    v_or_b32_e32 v1, v50, v1
; SI-NEXT:    v_and_b32_e32 v2, 0xff, v2
; SI-NEXT:    v_add_i32_e32 v1, vcc, s6, v1
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_or_b32_e32 v2, v49, v2
; SI-NEXT:    v_or_b32_e32 v1, v2, v1
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v8
; SI-NEXT:    v_and_b32_e32 v2, 0xff, v2
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v10
; SI-NEXT:    v_or_b32_e32 v2, v48, v2
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v3
; SI-NEXT:    v_add_i32_e32 v2, vcc, s6, v2
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_or_b32_e32 v3, v39, v3
; SI-NEXT:    v_or_b32_e32 v2, v3, v2
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v12
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v3
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v14
; SI-NEXT:    v_or_b32_e32 v3, v38, v3
; SI-NEXT:    v_and_b32_e32 v4, 0xff, v4
; SI-NEXT:    v_add_i32_e32 v3, vcc, s6, v3
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_or_b32_e32 v4, v37, v4
; SI-NEXT:    v_or_b32_e32 v3, v4, v3
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v16
; SI-NEXT:    v_and_b32_e32 v4, 0xff, v4
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v18
; SI-NEXT:    v_or_b32_e32 v4, v36, v4
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v5
; SI-NEXT:    v_add_i32_e32 v4, vcc, s6, v4
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_or_b32_e32 v5, v35, v5
; SI-NEXT:    v_or_b32_e32 v4, v5, v4
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v20
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v5
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v22
; SI-NEXT:    v_or_b32_e32 v5, v19, v5
; SI-NEXT:    v_and_b32_e32 v6, 0xff, v6
; SI-NEXT:    v_add_i32_e32 v5, vcc, s6, v5
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_or_b32_e32 v6, v17, v6
; SI-NEXT:    v_or_b32_e32 v5, v6, v5
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v24
; SI-NEXT:    v_and_b32_e32 v6, 0xff, v6
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v26
; SI-NEXT:    v_or_b32_e32 v6, v15, v6
; SI-NEXT:    v_and_b32_e32 v7, 0xff, v7
; SI-NEXT:    v_add_i32_e32 v6, vcc, s6, v6
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_or_b32_e32 v7, v13, v7
; SI-NEXT:    v_or_b32_e32 v6, v7, v6
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v28
; SI-NEXT:    v_and_b32_e32 v7, 0xff, v7
; SI-NEXT:    v_add_i32_e32 v8, vcc, 3, v30
; SI-NEXT:    v_or_b32_e32 v7, v11, v7
; SI-NEXT:    v_and_b32_e32 v8, 0xff, v8
; SI-NEXT:    v_add_i32_e32 v7, vcc, 0x300, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_or_b32_e32 v8, v9, v8
; SI-NEXT:    s_mov_b32 s7, 0x3000000
; SI-NEXT:    v_or_b32_e32 v7, v8, v7
; SI-NEXT:    v_add_i32_e32 v0, vcc, s7, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, s7, v1
; SI-NEXT:    v_add_i32_e32 v2, vcc, s7, v2
; SI-NEXT:    v_add_i32_e32 v3, vcc, s7, v3
; SI-NEXT:    v_add_i32_e32 v4, vcc, s7, v4
; SI-NEXT:    v_add_i32_e32 v5, vcc, s7, v5
; SI-NEXT:    v_add_i32_e32 v6, vcc, 0x3000000, v6
; SI-NEXT:    v_add_i32_e32 v7, vcc, 0x3000000, v7
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v32i8_to_v8f32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_mov_b32_e32 v38, v0
; VI-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:4
; VI-NEXT:    buffer_load_ushort v39, off, s[0:3], s32
; VI-NEXT:    v_mov_b32_e32 v31, v7
; VI-NEXT:    v_mov_b32_e32 v32, v6
; VI-NEXT:    v_mov_b32_e32 v33, v5
; VI-NEXT:    v_mov_b32_e32 v34, v4
; VI-NEXT:    v_mov_b32_e32 v35, v3
; VI-NEXT:    v_mov_b32_e32 v36, v2
; VI-NEXT:    v_mov_b32_e32 v37, v1
; VI-NEXT:    s_waitcnt vmcnt(1)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v0
; VI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execnz .LBB50_3
; VI-NEXT:  ; %bb.1: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execnz .LBB50_4
; VI-NEXT:  .LBB50_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB50_3: ; %cmp.false
; VI-NEXT:    s_mov_b32 s6, 0xc0c0004
; VI-NEXT:    v_perm_b32 v1, v36, v35, s6
; VI-NEXT:    v_perm_b32 v0, v38, v37, s6
; VI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_perm_b32 v2, v32, v31, s6
; VI-NEXT:    v_or_b32_e32 v0, v0, v1
; VI-NEXT:    v_perm_b32 v1, v34, v33, s6
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_perm_b32 v3, v10, v11, s6
; VI-NEXT:    v_or_b32_e32 v1, v1, v2
; VI-NEXT:    v_perm_b32 v2, v8, v9, s6
; VI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_perm_b32 v4, v14, v15, s6
; VI-NEXT:    v_or_b32_e32 v2, v2, v3
; VI-NEXT:    v_perm_b32 v3, v12, v13, s6
; VI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_perm_b32 v5, v18, v19, s6
; VI-NEXT:    v_or_b32_e32 v3, v3, v4
; VI-NEXT:    v_perm_b32 v4, v16, v17, s6
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_perm_b32 v6, v22, v23, s6
; VI-NEXT:    v_or_b32_e32 v4, v4, v5
; VI-NEXT:    v_perm_b32 v5, v20, v21, s6
; VI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_perm_b32 v7, v26, v27, s6
; VI-NEXT:    v_or_b32_e32 v5, v5, v6
; VI-NEXT:    v_perm_b32 v6, v24, v25, s6
; VI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    v_perm_b32 v8, v30, v39, s6
; VI-NEXT:    v_or_b32_e32 v6, v6, v7
; VI-NEXT:    v_perm_b32 v7, v28, v29, s6
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; VI-NEXT:    v_or_b32_e32 v7, v7, v8
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr35
; VI-NEXT:    ; implicit-def: $vgpr34
; VI-NEXT:    ; implicit-def: $vgpr33
; VI-NEXT:    ; implicit-def: $vgpr32
; VI-NEXT:    ; implicit-def: $vgpr31
; VI-NEXT:    ; implicit-def: $vgpr8
; VI-NEXT:    ; implicit-def: $vgpr9
; VI-NEXT:    ; implicit-def: $vgpr10
; VI-NEXT:    ; implicit-def: $vgpr11
; VI-NEXT:    ; implicit-def: $vgpr12
; VI-NEXT:    ; implicit-def: $vgpr13
; VI-NEXT:    ; implicit-def: $vgpr14
; VI-NEXT:    ; implicit-def: $vgpr15
; VI-NEXT:    ; implicit-def: $vgpr16
; VI-NEXT:    ; implicit-def: $vgpr17
; VI-NEXT:    ; implicit-def: $vgpr18
; VI-NEXT:    ; implicit-def: $vgpr19
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr21
; VI-NEXT:    ; implicit-def: $vgpr22
; VI-NEXT:    ; implicit-def: $vgpr23
; VI-NEXT:    ; implicit-def: $vgpr24
; VI-NEXT:    ; implicit-def: $vgpr25
; VI-NEXT:    ; implicit-def: $vgpr26
; VI-NEXT:    ; implicit-def: $vgpr27
; VI-NEXT:    ; implicit-def: $vgpr28
; VI-NEXT:    ; implicit-def: $vgpr29
; VI-NEXT:    ; implicit-def: $vgpr30
; VI-NEXT:    ; implicit-def: $vgpr39
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB50_2
; VI-NEXT:  .LBB50_4: ; %cmp.true
; VI-NEXT:    v_add_u16_e32 v0, 3, v38
; VI-NEXT:    v_lshlrev_b16_e32 v1, 8, v37
; VI-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v1, 3, v36
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v35
; VI-NEXT:    v_or_b32_sdwa v1, v2, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_mov_b32_e32 v7, 0x300
; VI-NEXT:    v_add_u16_e32 v2, 3, v34
; VI-NEXT:    v_lshlrev_b16_e32 v3, 8, v33
; VI-NEXT:    v_add_u16_e32 v0, 0x300, v0
; VI-NEXT:    v_add_u16_sdwa v1, v1, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v2, v3, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_or_b32_e32 v0, v0, v1
; VI-NEXT:    v_add_u16_e32 v1, 0x300, v2
; VI-NEXT:    v_add_u16_e32 v2, 3, v32
; VI-NEXT:    v_lshlrev_b16_e32 v3, 8, v31
; VI-NEXT:    v_or_b32_sdwa v2, v3, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_sdwa v2, v2, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v1, v1, v2
; VI-NEXT:    v_add_u16_e32 v2, 3, v8
; VI-NEXT:    v_lshlrev_b16_e32 v3, 8, v9
; VI-NEXT:    v_or_b32_sdwa v2, v3, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v3, 3, v10
; VI-NEXT:    v_lshlrev_b16_e32 v4, 8, v11
; VI-NEXT:    v_or_b32_sdwa v3, v4, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v2, 0x300, v2
; VI-NEXT:    v_add_u16_sdwa v3, v3, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v2, v2, v3
; VI-NEXT:    v_add_u16_e32 v3, 3, v12
; VI-NEXT:    v_lshlrev_b16_e32 v4, 8, v13
; VI-NEXT:    v_or_b32_sdwa v3, v4, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v4, 3, v14
; VI-NEXT:    v_lshlrev_b16_e32 v5, 8, v15
; VI-NEXT:    v_or_b32_sdwa v4, v5, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v3, 0x300, v3
; VI-NEXT:    v_add_u16_sdwa v4, v4, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v3, v3, v4
; VI-NEXT:    v_add_u16_e32 v4, 3, v16
; VI-NEXT:    v_lshlrev_b16_e32 v5, 8, v17
; VI-NEXT:    v_or_b32_sdwa v4, v5, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v5, 3, v18
; VI-NEXT:    v_lshlrev_b16_e32 v6, 8, v19
; VI-NEXT:    v_or_b32_sdwa v5, v6, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v4, 0x300, v4
; VI-NEXT:    v_add_u16_sdwa v5, v5, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v4, v4, v5
; VI-NEXT:    v_add_u16_e32 v5, 3, v20
; VI-NEXT:    v_lshlrev_b16_e32 v6, 8, v21
; VI-NEXT:    v_or_b32_sdwa v5, v6, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v6, 3, v22
; VI-NEXT:    v_lshlrev_b16_e32 v8, 8, v23
; VI-NEXT:    v_or_b32_sdwa v6, v8, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v5, 0x300, v5
; VI-NEXT:    v_add_u16_sdwa v6, v6, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v5, v5, v6
; VI-NEXT:    v_add_u16_e32 v6, 3, v24
; VI-NEXT:    v_lshlrev_b16_e32 v8, 8, v25
; VI-NEXT:    v_or_b32_sdwa v6, v8, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v8, 3, v26
; VI-NEXT:    v_lshlrev_b16_e32 v9, 8, v27
; VI-NEXT:    v_or_b32_sdwa v8, v9, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v6, 0x300, v6
; VI-NEXT:    v_add_u16_sdwa v8, v8, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v6, v6, v8
; VI-NEXT:    v_add_u16_e32 v8, 3, v28
; VI-NEXT:    v_lshlrev_b16_e32 v9, 8, v29
; VI-NEXT:    v_or_b32_sdwa v8, v9, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v9, 3, v30
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    v_lshlrev_b16_e32 v10, 8, v39
; VI-NEXT:    v_or_b32_sdwa v9, v10, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v8, 0x300, v8
; VI-NEXT:    v_add_u16_sdwa v7, v9, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v7, v8, v7
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v32i8_to_v8f32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_mov_b32_e32 v38, v0
; GFX9-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:4
; GFX9-NEXT:    buffer_load_ushort v39, off, s[0:3], s32
; GFX9-NEXT:    v_mov_b32_e32 v31, v7
; GFX9-NEXT:    v_mov_b32_e32 v32, v6
; GFX9-NEXT:    v_mov_b32_e32 v33, v5
; GFX9-NEXT:    v_mov_b32_e32 v34, v4
; GFX9-NEXT:    v_mov_b32_e32 v35, v3
; GFX9-NEXT:    v_mov_b32_e32 v36, v2
; GFX9-NEXT:    v_mov_b32_e32 v37, v1
; GFX9-NEXT:    s_waitcnt vmcnt(1)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v0
; GFX9-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execnz .LBB50_3
; GFX9-NEXT:  ; %bb.1: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execnz .LBB50_4
; GFX9-NEXT:  .LBB50_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB50_3: ; %cmp.false
; GFX9-NEXT:    s_mov_b32 s6, 0xc0c0004
; GFX9-NEXT:    v_perm_b32 v0, v38, v37, s6
; GFX9-NEXT:    v_perm_b32 v1, v36, v35, s6
; GFX9-NEXT:    v_lshl_or_b32 v0, v1, 16, v0
; GFX9-NEXT:    v_perm_b32 v1, v34, v33, s6
; GFX9-NEXT:    v_perm_b32 v2, v32, v31, s6
; GFX9-NEXT:    v_lshl_or_b32 v1, v2, 16, v1
; GFX9-NEXT:    v_perm_b32 v2, v8, v9, s6
; GFX9-NEXT:    v_perm_b32 v3, v10, v11, s6
; GFX9-NEXT:    v_lshl_or_b32 v2, v3, 16, v2
; GFX9-NEXT:    v_perm_b32 v3, v12, v13, s6
; GFX9-NEXT:    v_perm_b32 v4, v14, v15, s6
; GFX9-NEXT:    v_lshl_or_b32 v3, v4, 16, v3
; GFX9-NEXT:    v_perm_b32 v4, v16, v17, s6
; GFX9-NEXT:    v_perm_b32 v5, v18, v19, s6
; GFX9-NEXT:    v_lshl_or_b32 v4, v5, 16, v4
; GFX9-NEXT:    v_perm_b32 v5, v20, v21, s6
; GFX9-NEXT:    v_perm_b32 v6, v22, v23, s6
; GFX9-NEXT:    v_lshl_or_b32 v5, v6, 16, v5
; GFX9-NEXT:    v_perm_b32 v6, v24, v25, s6
; GFX9-NEXT:    v_perm_b32 v7, v26, v27, s6
; GFX9-NEXT:    v_lshl_or_b32 v6, v7, 16, v6
; GFX9-NEXT:    v_perm_b32 v7, v28, v29, s6
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    v_perm_b32 v8, v30, v39, s6
; GFX9-NEXT:    v_lshl_or_b32 v7, v8, 16, v7
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr35
; GFX9-NEXT:    ; implicit-def: $vgpr34
; GFX9-NEXT:    ; implicit-def: $vgpr33
; GFX9-NEXT:    ; implicit-def: $vgpr32
; GFX9-NEXT:    ; implicit-def: $vgpr31
; GFX9-NEXT:    ; implicit-def: $vgpr8
; GFX9-NEXT:    ; implicit-def: $vgpr9
; GFX9-NEXT:    ; implicit-def: $vgpr10
; GFX9-NEXT:    ; implicit-def: $vgpr11
; GFX9-NEXT:    ; implicit-def: $vgpr12
; GFX9-NEXT:    ; implicit-def: $vgpr13
; GFX9-NEXT:    ; implicit-def: $vgpr14
; GFX9-NEXT:    ; implicit-def: $vgpr15
; GFX9-NEXT:    ; implicit-def: $vgpr16
; GFX9-NEXT:    ; implicit-def: $vgpr17
; GFX9-NEXT:    ; implicit-def: $vgpr18
; GFX9-NEXT:    ; implicit-def: $vgpr19
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr21
; GFX9-NEXT:    ; implicit-def: $vgpr22
; GFX9-NEXT:    ; implicit-def: $vgpr23
; GFX9-NEXT:    ; implicit-def: $vgpr24
; GFX9-NEXT:    ; implicit-def: $vgpr25
; GFX9-NEXT:    ; implicit-def: $vgpr26
; GFX9-NEXT:    ; implicit-def: $vgpr27
; GFX9-NEXT:    ; implicit-def: $vgpr28
; GFX9-NEXT:    ; implicit-def: $vgpr29
; GFX9-NEXT:    ; implicit-def: $vgpr30
; GFX9-NEXT:    ; implicit-def: $vgpr39
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB50_2
; GFX9-NEXT:  .LBB50_4: ; %cmp.true
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v38
; GFX9-NEXT:    v_lshlrev_b16_e32 v1, 8, v37
; GFX9-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v1, 3, v36
; GFX9-NEXT:    v_lshlrev_b16_e32 v2, 8, v35
; GFX9-NEXT:    s_movk_i32 s6, 0x300
; GFX9-NEXT:    v_or_b32_sdwa v1, v2, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v0, 0x300, v0
; GFX9-NEXT:    v_add_u16_sdwa v1, v1, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v0, v0, v1
; GFX9-NEXT:    v_add_u16_e32 v1, 3, v34
; GFX9-NEXT:    v_lshlrev_b16_e32 v2, 8, v33
; GFX9-NEXT:    v_or_b32_sdwa v1, v2, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v2, 3, v32
; GFX9-NEXT:    v_lshlrev_b16_e32 v3, 8, v31
; GFX9-NEXT:    v_or_b32_sdwa v2, v3, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v1, 0x300, v1
; GFX9-NEXT:    v_add_u16_sdwa v2, v2, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v1, v1, v2
; GFX9-NEXT:    v_add_u16_e32 v2, 3, v8
; GFX9-NEXT:    v_lshlrev_b16_e32 v3, 8, v9
; GFX9-NEXT:    v_or_b32_sdwa v2, v3, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v3, 3, v10
; GFX9-NEXT:    v_lshlrev_b16_e32 v4, 8, v11
; GFX9-NEXT:    v_or_b32_sdwa v3, v4, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v2, 0x300, v2
; GFX9-NEXT:    v_add_u16_sdwa v3, v3, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v2, v2, v3
; GFX9-NEXT:    v_add_u16_e32 v3, 3, v12
; GFX9-NEXT:    v_lshlrev_b16_e32 v4, 8, v13
; GFX9-NEXT:    v_or_b32_sdwa v3, v4, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v4, 3, v14
; GFX9-NEXT:    v_lshlrev_b16_e32 v5, 8, v15
; GFX9-NEXT:    v_or_b32_sdwa v4, v5, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v3, 0x300, v3
; GFX9-NEXT:    v_add_u16_sdwa v4, v4, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v3, v3, v4
; GFX9-NEXT:    v_add_u16_e32 v4, 3, v16
; GFX9-NEXT:    v_lshlrev_b16_e32 v5, 8, v17
; GFX9-NEXT:    v_or_b32_sdwa v4, v5, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v5, 3, v18
; GFX9-NEXT:    v_lshlrev_b16_e32 v6, 8, v19
; GFX9-NEXT:    v_or_b32_sdwa v5, v6, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v4, 0x300, v4
; GFX9-NEXT:    v_add_u16_sdwa v5, v5, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v4, v4, v5
; GFX9-NEXT:    v_add_u16_e32 v5, 3, v20
; GFX9-NEXT:    v_lshlrev_b16_e32 v6, 8, v21
; GFX9-NEXT:    v_or_b32_sdwa v5, v6, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v6, 3, v22
; GFX9-NEXT:    v_lshlrev_b16_e32 v7, 8, v23
; GFX9-NEXT:    v_or_b32_sdwa v6, v7, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v5, 0x300, v5
; GFX9-NEXT:    v_add_u16_sdwa v6, v6, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v5, v5, v6
; GFX9-NEXT:    v_add_u16_e32 v6, 3, v24
; GFX9-NEXT:    v_lshlrev_b16_e32 v7, 8, v25
; GFX9-NEXT:    v_or_b32_sdwa v6, v7, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v7, 3, v26
; GFX9-NEXT:    v_lshlrev_b16_e32 v8, 8, v27
; GFX9-NEXT:    v_or_b32_sdwa v7, v8, v7 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v6, 0x300, v6
; GFX9-NEXT:    v_add_u16_sdwa v7, v7, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v6, v6, v7
; GFX9-NEXT:    v_add_u16_e32 v7, 3, v28
; GFX9-NEXT:    v_lshlrev_b16_e32 v8, 8, v29
; GFX9-NEXT:    v_or_b32_sdwa v7, v8, v7 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v8, 3, v30
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    v_lshlrev_b16_e32 v9, 8, v39
; GFX9-NEXT:    v_or_b32_sdwa v8, v9, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v7, 0x300, v7
; GFX9-NEXT:    v_add_u16_sdwa v8, v8, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v7, v7, v8
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v32i8_to_v8f32:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_clause 0x1
; GFX11-TRUE16-NEXT:    scratch_load_b32 v48, off, s32 offset:4
; GFX11-TRUE16-NEXT:    scratch_load_d16_b16 v31, off, s32
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v32.l, v7.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v33.l, v6.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v34.l, v5.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v35.l, v4.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v36.l, v3.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v37.l, v2.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v38.l, v1.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v39.l, v0.l
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(1)
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v48
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB50_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB50_4
; GFX11-TRUE16-NEXT:  .LBB50_2: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB50_3: ; %cmp.false
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr39_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr38_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v0, v39, v38, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr37_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr36_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, v37, v36, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr35_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr34_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v2, v35, v34, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr33_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr32_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v3, v33, v32, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr8_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v4, v8, v9, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr10_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr11_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, v10, v11, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr12_hi16
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v0, v1, 16, v0
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr14_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr15_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr16_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr17_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr18_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr19_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v6, v18, v19, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v1, v3, 16, v2
; GFX11-TRUE16-NEXT:    v_perm_b32 v3, v12, v13, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v2, v5, 16, v4
; GFX11-TRUE16-NEXT:    v_perm_b32 v4, v14, v15, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, v16, v17, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr21_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v7, v20, v21, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr22_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr23_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v8, v22, v23, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr24_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr25_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v9, v24, v25, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr26_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr27_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v10, v26, v27, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr28_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr29_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v11, v28, v29, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr30_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr31_hi16
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-TRUE16-NEXT:    v_perm_b32 v12, v30, v31, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v3, v4, 16, v3
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v4, v6, 16, v5
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v5, v8, 16, v7
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v6, v10, 16, v9
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v7, v12, 16, v11
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr39_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr38_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr37_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr36_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr35_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr34_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr33_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr32_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr8_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr10_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr11_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr12_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr14_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr15_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr16_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr17_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr18_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr19_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr21_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr22_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr23_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr24_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr25_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr26_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr27_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr28_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr29_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr30_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr31_lo16
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB50_2
; GFX11-TRUE16-NEXT:  .LBB50_4: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.l, v39.l, 3
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v0.h, 8, v38.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.l, v37.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.l, v35.l, 3
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v1.h, 8, v36.l
; GFX11-TRUE16-NEXT:    v_and_b16 v0.l, 0xff, v0.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v2.h, 8, v34.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v3.l, v33.l, 3
; GFX11-TRUE16-NEXT:    v_and_b16 v1.l, 0xff, v1.l
; GFX11-TRUE16-NEXT:    v_and_b16 v2.l, 0xff, v2.l
; GFX11-TRUE16-NEXT:    v_or_b16 v0.l, v0.h, v0.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.h, v8.l, 3
; GFX11-TRUE16-NEXT:    v_and_b16 v3.l, 0xff, v3.l
; GFX11-TRUE16-NEXT:    v_or_b16 v1.l, v1.h, v1.l
; GFX11-TRUE16-NEXT:    v_or_b16 v1.h, v2.h, v2.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v2.l, 8, v32.l
; GFX11-TRUE16-NEXT:    v_and_b16 v2.h, 0xff, v0.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v3.h, 8, v9.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v4.l, v10.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.h, 0x300, v1.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.l, 0x300, v1.h
; GFX11-TRUE16-NEXT:    v_or_b16 v1.h, v2.l, v3.l
; GFX11-TRUE16-NEXT:    v_or_b16 v2.l, v3.h, v2.h
; GFX11-TRUE16-NEXT:    v_and_b16 v2.h, 0xff, v4.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v3.l, 8, v11.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v3.h, v12.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v4.l, v14.l, 3
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v4.h, 8, v15.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v5.l, v16.l, 3
; GFX11-TRUE16-NEXT:    v_or_b16 v2.h, v3.l, v2.h
; GFX11-TRUE16-NEXT:    v_and_b16 v3.l, 0xff, v3.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v3.h, 8, v13.l
; GFX11-TRUE16-NEXT:    v_and_b16 v4.l, 0xff, v4.l
; GFX11-TRUE16-NEXT:    v_and_b16 v5.l, 0xff, v5.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v5.h, 8, v17.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v6.l, 8, v19.l
; GFX11-TRUE16-NEXT:    v_or_b16 v3.l, v3.h, v3.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v3.h, v18.l, 3
; GFX11-TRUE16-NEXT:    v_or_b16 v4.l, v4.h, v4.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v4.h, v20.l, 3
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v6.h, 8, v21.l
; GFX11-TRUE16-NEXT:    v_or_b16 v5.l, v5.h, v5.l
; GFX11-TRUE16-NEXT:    v_and_b16 v3.h, 0xff, v3.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v7.l, v26.l, 3
; GFX11-TRUE16-NEXT:    v_and_b16 v4.h, 0xff, v4.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v7.h, v28.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v8.h, v30.l, 3
; GFX11-TRUE16-NEXT:    v_or_b16 v5.h, v6.l, v3.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v3.h, 0x300, v4.l
; GFX11-TRUE16-NEXT:    v_or_b16 v6.l, v6.h, v4.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v6.h, v22.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v4.l, 0x300, v5.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v4.h, 0x300, v5.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v5.h, v24.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v5.l, 0x300, v6.l
; GFX11-TRUE16-NEXT:    v_and_b16 v6.l, 0xff, v6.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v6.h, 8, v23.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v8.l, 8, v25.l
; GFX11-TRUE16-NEXT:    v_and_b16 v5.h, 0xff, v5.h
; GFX11-TRUE16-NEXT:    v_and_b16 v7.l, 0xff, v7.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v9.l, 8, v27.l
; GFX11-TRUE16-NEXT:    v_and_b16 v7.h, 0xff, v7.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v9.h, 8, v29.l
; GFX11-TRUE16-NEXT:    v_and_b16 v8.h, 0xff, v8.h
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v10.l, 8, v31.l
; GFX11-TRUE16-NEXT:    v_or_b16 v6.l, v6.h, v6.l
; GFX11-TRUE16-NEXT:    v_or_b16 v6.h, v8.l, v5.h
; GFX11-TRUE16-NEXT:    v_or_b16 v7.l, v9.l, v7.l
; GFX11-TRUE16-NEXT:    v_or_b16 v7.h, v9.h, v7.h
; GFX11-TRUE16-NEXT:    v_or_b16 v8.l, v10.l, v8.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.l, 0x300, v0.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.h, 0x300, v1.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.l, 0x300, v2.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.h, 0x300, v2.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v3.l, 0x300, v3.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v5.h, 0x300, v6.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v6.l, 0x300, v6.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v6.h, 0x300, v7.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v7.l, 0x300, v7.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v7.h, 0x300, v8.l
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v32i8_to_v8f32:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v37, v1 :: v_dual_mov_b32 v38, v0
; GFX11-FAKE16-NEXT:    s_clause 0x1
; GFX11-FAKE16-NEXT:    scratch_load_b32 v0, off, s32 offset:4
; GFX11-FAKE16-NEXT:    scratch_load_u16 v39, off, s32
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v31, v7 :: v_dual_mov_b32 v32, v6
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v33, v5 :: v_dual_mov_b32 v34, v4
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v35, v3 :: v_dual_mov_b32 v36, v2
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(1)
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v0
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB50_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB50_4
; GFX11-FAKE16-NEXT:  .LBB50_2: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB50_3: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v38, v37, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v36, v35, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v34, v33, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v32, v31, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v8, v9, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v10, v11, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v0, v1, 16, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v18, v19, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v1, v3, 16, v2
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v12, v13, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v2, v5, 16, v4
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v14, v15, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v16, v17, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v20, v21, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, v22, v23, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, v24, v25, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, v26, v27, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, v28, v29, 0xc0c0004
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, v30, v39, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v3, v4, 16, v3
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v4, v6, 16, v5
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v5, v8, 16, v7
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v6, v10, 16, v9
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v7, v12, 16, v11
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr38
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr37
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr36
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr35
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr34
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr33
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr32
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr31
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr8
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr9
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr10
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr11
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr12
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr13
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr14
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr15
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr16
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr17
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr18
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr19
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr21
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr22
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr23
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr24
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr25
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr26
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr27
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr28
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr29
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr30
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr39
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB50_2
; GFX11-FAKE16-NEXT:  .LBB50_4: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v0, v38, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v2, v36, 3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v1, 8, v37
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v3, 8, v35
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v4, v34, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xff, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v6, v32, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xff, v2
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v5, 8, v33
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v7, 8, v31
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v1, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v1, v8, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xff, v4
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v6, 0xff, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, v3, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, v10, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v0, 0x300, v0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, v5, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v5, v7, v6
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v2, 0x300, v2
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v1, 0xff, v1
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v6, 8, v9
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xff, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v7, 8, v11
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v1, v6, v1
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v4, 0x300, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v7, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v5, 0x300, v5
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v0, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v2, 0x300, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, 0x300, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v6, v12, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v8, 8, v17
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v1, v4, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v4, v14, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xff, v6
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v6, 8, v13
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, v2, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, v16, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xff, v4
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v7, 8, v15
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v5, v6, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v6, v18, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xff, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v9, 8, v19
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, v7, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v7, v20, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v6, 0xff, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v8, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v10, 8, v21
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v8, v22, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v7, 0xff, v7
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v6, v9, v6
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, 0x300, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v11, v26, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v12, v28, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v14, v30, 3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v7, v10, v7
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v9, 0xffff, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, v24, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v8, 0xff, v8
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v10, 8, v23
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v13, 8, v25
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v11, 0xff, v11
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xff, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v15, 8, v27
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v12, 0xff, v12
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v16, 8, v29
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v14, 0xff, v14
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v17, 8, v39
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v8, v10, v8
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v13, v3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v10, v15, v11
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, v16, v12
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, v17, v14
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v5, 0x300, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v4, 0x300, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v6, 0x300, v6
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v7, 0x300, v7
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v8, 0x300, v8
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, 0x300, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v10, 0x300, v10
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v11, 0x300, v11
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v12, 0x300, v12
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v13, 0xffff, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v10, 16, v10
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v12, 16, v12
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v5, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, v9, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v5, v7, v8
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v6, v13, v10
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v7, v11, v12
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <32 x i8> %a, splat (i8 3)
  %a2 = bitcast <32 x i8> %a1 to <8 x float>
  br label %end

cmp.false:
  %a3 = bitcast <32 x i8> %a to <8 x float>
  br label %end

end:
  %phi = phi <8 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x float> %phi
}

define inreg <8 x float> @bitcast_v32i8_to_v8f32_scalar(<32 x i8> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v32i8_to_v8f32_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_readfirstlane_b32 s4, v18
; SI-NEXT:    v_readfirstlane_b32 s14, v17
; SI-NEXT:    v_readfirstlane_b32 s15, v16
; SI-NEXT:    v_readfirstlane_b32 s40, v15
; SI-NEXT:    v_readfirstlane_b32 s41, v14
; SI-NEXT:    v_readfirstlane_b32 s42, v13
; SI-NEXT:    v_readfirstlane_b32 s43, v12
; SI-NEXT:    v_readfirstlane_b32 s44, v11
; SI-NEXT:    v_readfirstlane_b32 s45, v10
; SI-NEXT:    v_readfirstlane_b32 s46, v9
; SI-NEXT:    v_readfirstlane_b32 s47, v8
; SI-NEXT:    v_readfirstlane_b32 s56, v7
; SI-NEXT:    v_readfirstlane_b32 s57, v6
; SI-NEXT:    v_readfirstlane_b32 s58, v5
; SI-NEXT:    v_readfirstlane_b32 s59, v4
; SI-NEXT:    v_readfirstlane_b32 s60, v3
; SI-NEXT:    v_readfirstlane_b32 s61, v2
; SI-NEXT:    v_readfirstlane_b32 s62, v1
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    v_readfirstlane_b32 s63, v0
; SI-NEXT:    s_cbranch_scc0 .LBB51_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s4, s16, 0xff
; SI-NEXT:    s_lshl_b32 s5, s17, 8
; SI-NEXT:    s_or_b32 s4, s4, s5
; SI-NEXT:    s_and_b32 s5, s18, 0xff
; SI-NEXT:    s_lshl_b32 s5, s5, 16
; SI-NEXT:    s_lshl_b32 s6, s19, 24
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_or_b32 s5, s6, s5
; SI-NEXT:    s_or_b32 s4, s4, s5
; SI-NEXT:    s_and_b32 s5, s20, 0xff
; SI-NEXT:    s_lshl_b32 s6, s21, 8
; SI-NEXT:    s_or_b32 s5, s5, s6
; SI-NEXT:    s_and_b32 s6, s22, 0xff
; SI-NEXT:    s_lshl_b32 s6, s6, 16
; SI-NEXT:    s_lshl_b32 s7, s23, 24
; SI-NEXT:    s_and_b32 s5, s5, 0xffff
; SI-NEXT:    s_or_b32 s6, s7, s6
; SI-NEXT:    s_or_b32 s5, s5, s6
; SI-NEXT:    s_and_b32 s6, s24, 0xff
; SI-NEXT:    s_lshl_b32 s7, s25, 8
; SI-NEXT:    s_or_b32 s6, s6, s7
; SI-NEXT:    s_and_b32 s7, s26, 0xff
; SI-NEXT:    s_lshl_b32 s7, s7, 16
; SI-NEXT:    s_lshl_b32 s8, s27, 24
; SI-NEXT:    s_and_b32 s6, s6, 0xffff
; SI-NEXT:    s_or_b32 s7, s8, s7
; SI-NEXT:    s_or_b32 s6, s6, s7
; SI-NEXT:    s_and_b32 s7, s28, 0xff
; SI-NEXT:    s_lshl_b32 s8, s29, 8
; SI-NEXT:    s_or_b32 s7, s7, s8
; SI-NEXT:    s_and_b32 s8, s63, 0xff
; SI-NEXT:    s_lshl_b32 s8, s8, 16
; SI-NEXT:    s_lshl_b32 s9, s62, 24
; SI-NEXT:    s_and_b32 s7, s7, 0xffff
; SI-NEXT:    s_or_b32 s8, s9, s8
; SI-NEXT:    s_or_b32 s7, s7, s8
; SI-NEXT:    s_and_b32 s8, s61, 0xff
; SI-NEXT:    s_lshl_b32 s9, s60, 8
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_and_b32 s9, s59, 0xff
; SI-NEXT:    s_lshl_b32 s9, s9, 16
; SI-NEXT:    s_lshl_b32 s10, s58, 24
; SI-NEXT:    s_and_b32 s8, s8, 0xffff
; SI-NEXT:    s_or_b32 s9, s10, s9
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_and_b32 s9, s57, 0xff
; SI-NEXT:    s_lshl_b32 s10, s56, 8
; SI-NEXT:    s_or_b32 s9, s9, s10
; SI-NEXT:    s_and_b32 s10, s47, 0xff
; SI-NEXT:    s_lshl_b32 s10, s10, 16
; SI-NEXT:    s_lshl_b32 s11, s46, 24
; SI-NEXT:    s_and_b32 s9, s9, 0xffff
; SI-NEXT:    s_or_b32 s10, s11, s10
; SI-NEXT:    s_or_b32 s9, s9, s10
; SI-NEXT:    s_and_b32 s10, s45, 0xff
; SI-NEXT:    s_lshl_b32 s11, s44, 8
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_and_b32 s11, s43, 0xff
; SI-NEXT:    s_lshl_b32 s11, s11, 16
; SI-NEXT:    s_lshl_b32 s12, s42, 24
; SI-NEXT:    s_and_b32 s10, s10, 0xffff
; SI-NEXT:    s_or_b32 s11, s12, s11
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_and_b32 s11, s41, 0xff
; SI-NEXT:    s_lshl_b32 s12, s40, 8
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    s_and_b32 s12, s15, 0xff
; SI-NEXT:    s_lshl_b32 s12, s12, 16
; SI-NEXT:    s_lshl_b32 s13, s14, 24
; SI-NEXT:    s_and_b32 s11, s11, 0xffff
; SI-NEXT:    s_or_b32 s12, s13, s12
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    s_cbranch_execnz .LBB51_3
; SI-NEXT:  .LBB51_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    s_and_b32 s4, s16, 0xff
; SI-NEXT:    s_lshl_b32 s5, s17, 8
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_and_b32 s6, s18, 0xff
; SI-NEXT:    s_addk_i32 s4, 0x300
; SI-NEXT:    s_lshl_b32 s5, s19, 24
; SI-NEXT:    s_lshl_b32 s6, s6, 16
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_or_b32 s5, s5, s6
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_and_b32 s5, s20, 0xff
; SI-NEXT:    s_lshl_b32 s6, s21, 8
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_or_b32 s5, s6, s5
; SI-NEXT:    s_and_b32 s7, s22, 0xff
; SI-NEXT:    s_addk_i32 s5, 0x300
; SI-NEXT:    s_lshl_b32 s6, s23, 24
; SI-NEXT:    s_lshl_b32 s7, s7, 16
; SI-NEXT:    s_and_b32 s5, s5, 0xffff
; SI-NEXT:    s_or_b32 s6, s6, s7
; SI-NEXT:    s_add_i32 s24, s24, 3
; SI-NEXT:    s_or_b32 s5, s6, s5
; SI-NEXT:    s_and_b32 s6, s24, 0xff
; SI-NEXT:    s_lshl_b32 s7, s25, 8
; SI-NEXT:    s_add_i32 s26, s26, 3
; SI-NEXT:    s_or_b32 s6, s7, s6
; SI-NEXT:    s_and_b32 s8, s26, 0xff
; SI-NEXT:    s_addk_i32 s6, 0x300
; SI-NEXT:    s_lshl_b32 s7, s27, 24
; SI-NEXT:    s_lshl_b32 s8, s8, 16
; SI-NEXT:    s_and_b32 s6, s6, 0xffff
; SI-NEXT:    s_or_b32 s7, s7, s8
; SI-NEXT:    s_add_i32 s28, s28, 3
; SI-NEXT:    s_or_b32 s6, s7, s6
; SI-NEXT:    s_and_b32 s7, s28, 0xff
; SI-NEXT:    s_lshl_b32 s8, s29, 8
; SI-NEXT:    s_add_i32 s63, s63, 3
; SI-NEXT:    s_or_b32 s7, s8, s7
; SI-NEXT:    s_and_b32 s9, s63, 0xff
; SI-NEXT:    s_addk_i32 s7, 0x300
; SI-NEXT:    s_lshl_b32 s8, s62, 24
; SI-NEXT:    s_lshl_b32 s9, s9, 16
; SI-NEXT:    s_and_b32 s7, s7, 0xffff
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_add_i32 s61, s61, 3
; SI-NEXT:    s_or_b32 s7, s8, s7
; SI-NEXT:    s_and_b32 s8, s61, 0xff
; SI-NEXT:    s_lshl_b32 s9, s60, 8
; SI-NEXT:    s_add_i32 s59, s59, 3
; SI-NEXT:    s_or_b32 s8, s9, s8
; SI-NEXT:    s_and_b32 s10, s59, 0xff
; SI-NEXT:    s_addk_i32 s8, 0x300
; SI-NEXT:    s_lshl_b32 s9, s58, 24
; SI-NEXT:    s_lshl_b32 s10, s10, 16
; SI-NEXT:    s_and_b32 s8, s8, 0xffff
; SI-NEXT:    s_or_b32 s9, s9, s10
; SI-NEXT:    s_add_i32 s57, s57, 3
; SI-NEXT:    s_or_b32 s8, s9, s8
; SI-NEXT:    s_and_b32 s9, s57, 0xff
; SI-NEXT:    s_lshl_b32 s10, s56, 8
; SI-NEXT:    s_add_i32 s47, s47, 3
; SI-NEXT:    s_or_b32 s9, s10, s9
; SI-NEXT:    s_and_b32 s11, s47, 0xff
; SI-NEXT:    s_addk_i32 s9, 0x300
; SI-NEXT:    s_lshl_b32 s10, s46, 24
; SI-NEXT:    s_lshl_b32 s11, s11, 16
; SI-NEXT:    s_and_b32 s9, s9, 0xffff
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_add_i32 s45, s45, 3
; SI-NEXT:    s_or_b32 s9, s10, s9
; SI-NEXT:    s_and_b32 s10, s45, 0xff
; SI-NEXT:    s_lshl_b32 s11, s44, 8
; SI-NEXT:    s_add_i32 s43, s43, 3
; SI-NEXT:    s_or_b32 s10, s11, s10
; SI-NEXT:    s_and_b32 s12, s43, 0xff
; SI-NEXT:    s_addk_i32 s10, 0x300
; SI-NEXT:    s_lshl_b32 s11, s42, 24
; SI-NEXT:    s_lshl_b32 s12, s12, 16
; SI-NEXT:    s_and_b32 s10, s10, 0xffff
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    s_add_i32 s41, s41, 3
; SI-NEXT:    s_or_b32 s10, s11, s10
; SI-NEXT:    s_and_b32 s11, s41, 0xff
; SI-NEXT:    s_lshl_b32 s12, s40, 8
; SI-NEXT:    s_add_i32 s15, s15, 3
; SI-NEXT:    s_or_b32 s11, s12, s11
; SI-NEXT:    s_and_b32 s13, s15, 0xff
; SI-NEXT:    s_addk_i32 s11, 0x300
; SI-NEXT:    s_lshl_b32 s12, s14, 24
; SI-NEXT:    s_lshl_b32 s13, s13, 16
; SI-NEXT:    s_and_b32 s11, s11, 0xffff
; SI-NEXT:    s_or_b32 s12, s12, s13
; SI-NEXT:    s_or_b32 s11, s12, s11
; SI-NEXT:    s_add_i32 s4, s4, 0x3000000
; SI-NEXT:    s_add_i32 s5, s5, 0x3000000
; SI-NEXT:    s_add_i32 s6, s6, 0x3000000
; SI-NEXT:    s_add_i32 s7, s7, 0x3000000
; SI-NEXT:    s_add_i32 s8, s8, 0x3000000
; SI-NEXT:    s_add_i32 s9, s9, 0x3000000
; SI-NEXT:    s_add_i32 s10, s10, 0x3000000
; SI-NEXT:    s_add_i32 s11, s11, 0x3000000
; SI-NEXT:  .LBB51_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v0, s4
; SI-NEXT:    v_mov_b32_e32 v1, s5
; SI-NEXT:    v_mov_b32_e32 v2, s6
; SI-NEXT:    v_mov_b32_e32 v3, s7
; SI-NEXT:    v_mov_b32_e32 v4, s8
; SI-NEXT:    v_mov_b32_e32 v5, s9
; SI-NEXT:    v_mov_b32_e32 v6, s10
; SI-NEXT:    v_mov_b32_e32 v7, s11
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB51_4:
; SI-NEXT:    ; implicit-def: $sgpr4_sgpr5_sgpr6_sgpr7_sgpr8_sgpr9_sgpr10_sgpr11
; SI-NEXT:    s_branch .LBB51_2
;
; VI-LABEL: bitcast_v32i8_to_v8f32_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_readfirstlane_b32 s4, v18
; VI-NEXT:    v_readfirstlane_b32 s6, v17
; VI-NEXT:    v_readfirstlane_b32 s7, v16
; VI-NEXT:    v_readfirstlane_b32 s8, v15
; VI-NEXT:    v_readfirstlane_b32 s9, v14
; VI-NEXT:    v_readfirstlane_b32 s10, v13
; VI-NEXT:    v_readfirstlane_b32 s11, v12
; VI-NEXT:    v_readfirstlane_b32 s12, v11
; VI-NEXT:    v_readfirstlane_b32 s13, v10
; VI-NEXT:    v_readfirstlane_b32 s14, v9
; VI-NEXT:    v_readfirstlane_b32 s15, v8
; VI-NEXT:    v_readfirstlane_b32 s40, v7
; VI-NEXT:    v_readfirstlane_b32 s41, v6
; VI-NEXT:    v_readfirstlane_b32 s42, v5
; VI-NEXT:    v_readfirstlane_b32 s43, v4
; VI-NEXT:    v_readfirstlane_b32 s44, v3
; VI-NEXT:    v_readfirstlane_b32 s45, v2
; VI-NEXT:    v_readfirstlane_b32 s46, v1
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    v_readfirstlane_b32 s47, v0
; VI-NEXT:    s_cbranch_scc0 .LBB51_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_mov_b32_e32 v7, 0xc0c0004
; VI-NEXT:    v_mov_b32_e32 v1, s19
; VI-NEXT:    v_mov_b32_e32 v0, s17
; VI-NEXT:    v_perm_b32 v1, s18, v1, v7
; VI-NEXT:    v_perm_b32 v0, s16, v0, v7
; VI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_mov_b32_e32 v2, s23
; VI-NEXT:    v_or_b32_e32 v0, v0, v1
; VI-NEXT:    v_mov_b32_e32 v1, s21
; VI-NEXT:    v_perm_b32 v2, s22, v2, v7
; VI-NEXT:    v_perm_b32 v1, s20, v1, v7
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_mov_b32_e32 v3, s27
; VI-NEXT:    v_or_b32_e32 v1, v1, v2
; VI-NEXT:    v_mov_b32_e32 v2, s25
; VI-NEXT:    v_perm_b32 v3, s26, v3, v7
; VI-NEXT:    v_perm_b32 v2, s24, v2, v7
; VI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_mov_b32_e32 v4, s46
; VI-NEXT:    v_or_b32_e32 v2, v2, v3
; VI-NEXT:    v_mov_b32_e32 v3, s29
; VI-NEXT:    v_perm_b32 v4, s47, v4, v7
; VI-NEXT:    v_perm_b32 v3, s28, v3, v7
; VI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_mov_b32_e32 v5, s42
; VI-NEXT:    v_or_b32_e32 v3, v3, v4
; VI-NEXT:    v_mov_b32_e32 v4, s44
; VI-NEXT:    v_perm_b32 v5, s43, v5, v7
; VI-NEXT:    v_perm_b32 v4, s45, v4, v7
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_mov_b32_e32 v6, s14
; VI-NEXT:    v_or_b32_e32 v4, v4, v5
; VI-NEXT:    v_mov_b32_e32 v5, s40
; VI-NEXT:    v_perm_b32 v6, s15, v6, v7
; VI-NEXT:    v_perm_b32 v5, s41, v5, v7
; VI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_mov_b32_e32 v8, s10
; VI-NEXT:    v_or_b32_e32 v5, v5, v6
; VI-NEXT:    v_mov_b32_e32 v6, s12
; VI-NEXT:    v_perm_b32 v8, s11, v8, v7
; VI-NEXT:    v_perm_b32 v6, s13, v6, v7
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; VI-NEXT:    v_or_b32_e32 v6, v6, v8
; VI-NEXT:    v_mov_b32_e32 v8, s8
; VI-NEXT:    v_mov_b32_e32 v9, s6
; VI-NEXT:    v_perm_b32 v8, s9, v8, v7
; VI-NEXT:    v_perm_b32 v7, s7, v9, v7
; VI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; VI-NEXT:    v_or_b32_e32 v7, v8, v7
; VI-NEXT:    s_cbranch_execnz .LBB51_3
; VI-NEXT:  .LBB51_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s16, s16, 3
; VI-NEXT:    v_mov_b32_e32 v0, s17
; VI-NEXT:    v_mov_b32_e32 v7, 0xc0c0004
; VI-NEXT:    s_add_i32 s18, s18, 3
; VI-NEXT:    v_mov_b32_e32 v1, s19
; VI-NEXT:    v_perm_b32 v0, s16, v0, v7
; VI-NEXT:    v_perm_b32 v1, s18, v1, v7
; VI-NEXT:    v_add_u32_e32 v0, vcc, 0x300, v0
; VI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s20, s20, 3
; VI-NEXT:    v_mov_b32_e32 v1, s21
; VI-NEXT:    s_add_i32 s22, s22, 3
; VI-NEXT:    v_mov_b32_e32 v2, s23
; VI-NEXT:    v_perm_b32 v1, s20, v1, v7
; VI-NEXT:    v_perm_b32 v2, s22, v2, v7
; VI-NEXT:    v_add_u32_e32 v1, vcc, 0x300, v1
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_or_b32_sdwa v1, v2, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s24, s24, 3
; VI-NEXT:    v_mov_b32_e32 v2, s25
; VI-NEXT:    s_add_i32 s26, s26, 3
; VI-NEXT:    v_mov_b32_e32 v3, s27
; VI-NEXT:    v_perm_b32 v2, s24, v2, v7
; VI-NEXT:    v_perm_b32 v3, s26, v3, v7
; VI-NEXT:    v_add_u32_e32 v2, vcc, 0x300, v2
; VI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_or_b32_sdwa v2, v3, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s28, s28, 3
; VI-NEXT:    v_mov_b32_e32 v3, s29
; VI-NEXT:    s_add_i32 s47, s47, 3
; VI-NEXT:    v_mov_b32_e32 v4, s46
; VI-NEXT:    v_perm_b32 v3, s28, v3, v7
; VI-NEXT:    v_perm_b32 v4, s47, v4, v7
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x300, v3
; VI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_or_b32_sdwa v3, v4, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s45, s45, 3
; VI-NEXT:    v_mov_b32_e32 v4, s44
; VI-NEXT:    s_add_i32 s43, s43, 3
; VI-NEXT:    v_mov_b32_e32 v5, s42
; VI-NEXT:    v_perm_b32 v4, s45, v4, v7
; VI-NEXT:    v_perm_b32 v5, s43, v5, v7
; VI-NEXT:    v_add_u32_e32 v4, vcc, 0x300, v4
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_or_b32_sdwa v4, v5, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s41, s41, 3
; VI-NEXT:    v_mov_b32_e32 v5, s40
; VI-NEXT:    s_add_i32 s15, s15, 3
; VI-NEXT:    v_mov_b32_e32 v6, s14
; VI-NEXT:    v_perm_b32 v5, s41, v5, v7
; VI-NEXT:    v_perm_b32 v6, s15, v6, v7
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x300, v5
; VI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_or_b32_sdwa v5, v6, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s13, s13, 3
; VI-NEXT:    v_mov_b32_e32 v6, s12
; VI-NEXT:    s_add_i32 s11, s11, 3
; VI-NEXT:    v_mov_b32_e32 v8, s10
; VI-NEXT:    v_perm_b32 v6, s13, v6, v7
; VI-NEXT:    v_perm_b32 v8, s11, v8, v7
; VI-NEXT:    v_add_u32_e32 v6, vcc, 0x300, v6
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; VI-NEXT:    v_or_b32_sdwa v6, v8, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s9, s9, 3
; VI-NEXT:    v_mov_b32_e32 v8, s8
; VI-NEXT:    s_add_i32 s7, s7, 3
; VI-NEXT:    v_mov_b32_e32 v9, s6
; VI-NEXT:    v_perm_b32 v8, s9, v8, v7
; VI-NEXT:    v_perm_b32 v7, s7, v9, v7
; VI-NEXT:    v_add_u32_e32 v8, vcc, 0x300, v8
; VI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; VI-NEXT:    v_or_b32_sdwa v7, v7, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_add_u32_e32 v0, vcc, 0x3000000, v0
; VI-NEXT:    v_add_u32_e32 v1, vcc, 0x3000000, v1
; VI-NEXT:    v_add_u32_e32 v2, vcc, 0x3000000, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x3000000, v3
; VI-NEXT:    v_add_u32_e32 v4, vcc, 0x3000000, v4
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x3000000, v5
; VI-NEXT:    v_add_u32_e32 v6, vcc, 0x3000000, v6
; VI-NEXT:    v_add_u32_e32 v7, vcc, 0x3000000, v7
; VI-NEXT:  .LBB51_3: ; %end
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB51_4:
; VI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; VI-NEXT:    s_branch .LBB51_2
;
; GFX9-LABEL: bitcast_v32i8_to_v8f32_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_readfirstlane_b32 s4, v18
; GFX9-NEXT:    v_readfirstlane_b32 s6, v17
; GFX9-NEXT:    v_readfirstlane_b32 s7, v16
; GFX9-NEXT:    v_readfirstlane_b32 s8, v15
; GFX9-NEXT:    v_readfirstlane_b32 s9, v14
; GFX9-NEXT:    v_readfirstlane_b32 s10, v13
; GFX9-NEXT:    v_readfirstlane_b32 s11, v12
; GFX9-NEXT:    v_readfirstlane_b32 s12, v11
; GFX9-NEXT:    v_readfirstlane_b32 s13, v10
; GFX9-NEXT:    v_readfirstlane_b32 s14, v9
; GFX9-NEXT:    v_readfirstlane_b32 s15, v8
; GFX9-NEXT:    v_readfirstlane_b32 s40, v7
; GFX9-NEXT:    v_readfirstlane_b32 s41, v6
; GFX9-NEXT:    v_readfirstlane_b32 s42, v5
; GFX9-NEXT:    v_readfirstlane_b32 s43, v4
; GFX9-NEXT:    v_readfirstlane_b32 s44, v3
; GFX9-NEXT:    v_readfirstlane_b32 s45, v2
; GFX9-NEXT:    v_readfirstlane_b32 s46, v1
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    v_readfirstlane_b32 s47, v0
; GFX9-NEXT:    s_cbranch_scc0 .LBB51_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    v_mov_b32_e32 v7, 0xc0c0004
; GFX9-NEXT:    v_mov_b32_e32 v1, s19
; GFX9-NEXT:    v_mov_b32_e32 v0, s17
; GFX9-NEXT:    v_perm_b32 v1, s18, v1, v7
; GFX9-NEXT:    v_perm_b32 v0, s16, v0, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_mov_b32_e32 v2, s23
; GFX9-NEXT:    v_or_b32_e32 v0, v0, v1
; GFX9-NEXT:    v_mov_b32_e32 v1, s21
; GFX9-NEXT:    v_perm_b32 v2, s22, v2, v7
; GFX9-NEXT:    v_perm_b32 v1, s20, v1, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; GFX9-NEXT:    v_mov_b32_e32 v3, s27
; GFX9-NEXT:    v_or_b32_e32 v1, v1, v2
; GFX9-NEXT:    v_mov_b32_e32 v2, s25
; GFX9-NEXT:    v_perm_b32 v3, s26, v3, v7
; GFX9-NEXT:    v_perm_b32 v2, s24, v2, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; GFX9-NEXT:    v_mov_b32_e32 v4, s46
; GFX9-NEXT:    v_or_b32_e32 v2, v2, v3
; GFX9-NEXT:    v_mov_b32_e32 v3, s29
; GFX9-NEXT:    v_perm_b32 v4, s47, v4, v7
; GFX9-NEXT:    v_perm_b32 v3, s28, v3, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX9-NEXT:    v_mov_b32_e32 v5, s42
; GFX9-NEXT:    v_or_b32_e32 v3, v3, v4
; GFX9-NEXT:    v_mov_b32_e32 v4, s44
; GFX9-NEXT:    v_perm_b32 v5, s43, v5, v7
; GFX9-NEXT:    v_perm_b32 v4, s45, v4, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX9-NEXT:    v_mov_b32_e32 v6, s14
; GFX9-NEXT:    v_or_b32_e32 v4, v4, v5
; GFX9-NEXT:    v_mov_b32_e32 v5, s40
; GFX9-NEXT:    v_perm_b32 v6, s15, v6, v7
; GFX9-NEXT:    v_perm_b32 v5, s41, v5, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GFX9-NEXT:    v_mov_b32_e32 v8, s10
; GFX9-NEXT:    v_or_b32_e32 v5, v5, v6
; GFX9-NEXT:    v_mov_b32_e32 v6, s12
; GFX9-NEXT:    v_perm_b32 v8, s11, v8, v7
; GFX9-NEXT:    v_perm_b32 v6, s13, v6, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; GFX9-NEXT:    v_or_b32_e32 v6, v6, v8
; GFX9-NEXT:    v_mov_b32_e32 v8, s8
; GFX9-NEXT:    v_mov_b32_e32 v9, s6
; GFX9-NEXT:    v_perm_b32 v8, s9, v8, v7
; GFX9-NEXT:    v_perm_b32 v7, s7, v9, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; GFX9-NEXT:    v_or_b32_e32 v7, v8, v7
; GFX9-NEXT:    s_cbranch_execnz .LBB51_3
; GFX9-NEXT:  .LBB51_2: ; %cmp.true
; GFX9-NEXT:    s_add_i32 s16, s16, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s17
; GFX9-NEXT:    v_mov_b32_e32 v7, 0xc0c0004
; GFX9-NEXT:    s_add_i32 s18, s18, 3
; GFX9-NEXT:    v_mov_b32_e32 v1, s19
; GFX9-NEXT:    v_perm_b32 v0, s16, v0, v7
; GFX9-NEXT:    s_movk_i32 s4, 0x300
; GFX9-NEXT:    v_perm_b32 v1, s18, v1, v7
; GFX9-NEXT:    v_add_u32_e32 v0, 0x300, v0
; GFX9-NEXT:    v_add_u32_sdwa v1, v1, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v0, v0, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s20, s20, 3
; GFX9-NEXT:    v_mov_b32_e32 v1, s21
; GFX9-NEXT:    s_add_i32 s22, s22, 3
; GFX9-NEXT:    v_mov_b32_e32 v2, s23
; GFX9-NEXT:    v_perm_b32 v1, s20, v1, v7
; GFX9-NEXT:    v_perm_b32 v2, s22, v2, v7
; GFX9-NEXT:    v_add_u32_e32 v1, 0x300, v1
; GFX9-NEXT:    v_add_u32_sdwa v2, v2, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v1, v1, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s24, s24, 3
; GFX9-NEXT:    v_mov_b32_e32 v2, s25
; GFX9-NEXT:    s_add_i32 s26, s26, 3
; GFX9-NEXT:    v_mov_b32_e32 v3, s27
; GFX9-NEXT:    v_perm_b32 v2, s24, v2, v7
; GFX9-NEXT:    v_perm_b32 v3, s26, v3, v7
; GFX9-NEXT:    v_add_u32_e32 v2, 0x300, v2
; GFX9-NEXT:    v_add_u32_sdwa v3, v3, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v2, v2, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s28, s28, 3
; GFX9-NEXT:    v_mov_b32_e32 v3, s29
; GFX9-NEXT:    s_add_i32 s47, s47, 3
; GFX9-NEXT:    v_mov_b32_e32 v4, s46
; GFX9-NEXT:    v_perm_b32 v3, s28, v3, v7
; GFX9-NEXT:    v_perm_b32 v4, s47, v4, v7
; GFX9-NEXT:    v_add_u32_e32 v3, 0x300, v3
; GFX9-NEXT:    v_add_u32_sdwa v4, v4, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v3, v3, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s45, s45, 3
; GFX9-NEXT:    v_mov_b32_e32 v4, s44
; GFX9-NEXT:    s_add_i32 s43, s43, 3
; GFX9-NEXT:    v_mov_b32_e32 v5, s42
; GFX9-NEXT:    v_perm_b32 v4, s45, v4, v7
; GFX9-NEXT:    v_perm_b32 v5, s43, v5, v7
; GFX9-NEXT:    v_add_u32_e32 v4, 0x300, v4
; GFX9-NEXT:    v_add_u32_sdwa v5, v5, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v4, v4, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s41, s41, 3
; GFX9-NEXT:    v_mov_b32_e32 v5, s40
; GFX9-NEXT:    s_add_i32 s15, s15, 3
; GFX9-NEXT:    v_mov_b32_e32 v6, s14
; GFX9-NEXT:    v_perm_b32 v5, s41, v5, v7
; GFX9-NEXT:    v_perm_b32 v6, s15, v6, v7
; GFX9-NEXT:    v_add_u32_e32 v5, 0x300, v5
; GFX9-NEXT:    v_add_u32_sdwa v6, v6, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v5, v5, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s13, s13, 3
; GFX9-NEXT:    v_mov_b32_e32 v6, s12
; GFX9-NEXT:    s_add_i32 s11, s11, 3
; GFX9-NEXT:    v_mov_b32_e32 v8, s10
; GFX9-NEXT:    v_perm_b32 v6, s13, v6, v7
; GFX9-NEXT:    v_perm_b32 v8, s11, v8, v7
; GFX9-NEXT:    v_add_u32_e32 v6, 0x300, v6
; GFX9-NEXT:    v_add_u32_sdwa v8, v8, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v6, v6, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s9, s9, 3
; GFX9-NEXT:    v_mov_b32_e32 v8, s8
; GFX9-NEXT:    s_add_i32 s7, s7, 3
; GFX9-NEXT:    v_mov_b32_e32 v9, s6
; GFX9-NEXT:    v_perm_b32 v8, s9, v8, v7
; GFX9-NEXT:    v_perm_b32 v7, s7, v9, v7
; GFX9-NEXT:    v_add_u32_e32 v8, 0x300, v8
; GFX9-NEXT:    v_add_u32_sdwa v7, v7, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v7, v8, v7 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:  .LBB51_3: ; %end
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB51_4:
; GFX9-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX9-NEXT:    s_branch .LBB51_2
;
; GFX11-TRUE16-LABEL: bitcast_v32i8_to_v8f32_scalar:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s42, v14
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s4, v13
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr12_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s5, v12
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr11_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s6, v11
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr10_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s7, v10
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s8, v9
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr8_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s9, v8
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr7_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s10, v7
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr6_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s11, v6
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr5_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s12, v5
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr4_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s13, v4
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr3_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s14, v3
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr2_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s15, v2
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr1_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s40, v1
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr0_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s41, v0
; GFX11-TRUE16-NEXT:    s_cmp_lg_u32 s42, 0
; GFX11-TRUE16-NEXT:    s_mov_b32 s42, 0
; GFX11-TRUE16-NEXT:    s_cbranch_scc0 .LBB51_4
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v3, 0xc0c0004
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_perm_b32 v4, s18, s19, v3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, s2, s3, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, s22, s23, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v0, s0, s1, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v2, s16, s17, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v6, s20, s21, v3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX11-TRUE16-NEXT:    v_perm_b32 v8, s26, s27, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v9, s41, s40, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v11, s5, s4, v3
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v0, v0, v1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v1, v2, v4
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v2, v6, v5
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v8
; GFX11-TRUE16-NEXT:    v_perm_b32 v6, s13, s12, v3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v8, 16, v9
; GFX11-TRUE16-NEXT:    v_perm_b32 v9, s9, s8, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v7, s24, s25, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, s28, s29, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v10, s15, s14, v3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GFX11-TRUE16-NEXT:    v_perm_b32 v12, s11, s10, v3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; GFX11-TRUE16-NEXT:    v_perm_b32 v13, s7, s6, v3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v3, v7, v4
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v4, v5, v8
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, v10, v6
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v6, v12, v9
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v7, v13, v11
; GFX11-TRUE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s42
; GFX11-TRUE16-NEXT:    s_cbranch_vccnz .LBB51_3
; GFX11-TRUE16-NEXT:  .LBB51_2: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v3, 0xc0c0004
; GFX11-TRUE16-NEXT:    s_add_i32 s18, s18, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s0, s0, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s2, s2, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s16, s16, 3
; GFX11-TRUE16-NEXT:    v_perm_b32 v4, s18, s19, v3
; GFX11-TRUE16-NEXT:    s_add_i32 s20, s20, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s22, s22, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s24, s24, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s26, s26, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v4, 0x300, v4
; GFX11-TRUE16-NEXT:    s_add_i32 s28, s28, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s41, s41, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s15, s15, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s13, s13, 3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX11-TRUE16-NEXT:    v_perm_b32 v0, s0, s1, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, s2, s3, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v2, s16, s17, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, s20, s21, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v6, s22, s23, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v0, 0x300, v0
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, 0x300, v1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, 0x300, v2
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v5, 0x300, v5
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, 0x300, v6
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GFX11-TRUE16-NEXT:    s_add_i32 s11, s11, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s9, s9, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s7, s7, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s5, s5, 3
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v0, v0, v1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v1, v2, v4
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v2, v5, v6
; GFX11-TRUE16-NEXT:    v_perm_b32 v4, s24, s25, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, s26, s27, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v6, s28, s29, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v7, s41, s40, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v8, s15, s14, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v9, s13, s12, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v10, s11, s10, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v11, s9, s8, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v12, s7, s6, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v3, s5, s4, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v4, 0x300, v4
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v5, 0x300, v5
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, 0x300, v6
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v7, 0x300, v7
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v8, 0x300, v8
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v9, 0x300, v9
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v10, 0x300, v10
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v11, 0x300, v11
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v12, 0x300, v12
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 0x300, v3
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v13, 16, v3
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v3, v4, v5
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v4, v6, v7
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, v8, v9
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v6, v10, v11
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v7, v12, v13
; GFX11-TRUE16-NEXT:  .LBB51_3: ; %end
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB51_4:
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-TRUE16-NEXT:    s_branch .LBB51_2
;
; GFX11-FAKE16-LABEL: bitcast_v32i8_to_v8f32_scalar:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s42, v14
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s4, v13
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s5, v12
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s6, v11
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s7, v10
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s8, v9
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s9, v8
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s10, v7
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s11, v6
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s12, v5
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s13, v4
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s14, v3
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s15, v2
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s40, v1
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s41, v0
; GFX11-FAKE16-NEXT:    s_cmp_lg_u32 s42, 0
; GFX11-FAKE16-NEXT:    s_mov_b32 s42, 0
; GFX11-FAKE16-NEXT:    s_cbranch_scc0 .LBB51_4
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v3, 0xc0c0004
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, s18, s19, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, s2, s3, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, s22, s23, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, s0, s1, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, s16, s17, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, s20, s21, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, s26, s27, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, s41, s40, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, s5, s4, v3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v0, v1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v1, v2, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, v6, v5
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v8
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, s13, s12, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v8, 16, v9
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, s9, s8, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, s24, s25, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, s28, s29, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, s15, s14, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, s11, s10, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, s7, s6, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v7, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, v5, v8
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v5, v10, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v6, v12, v9
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v7, v13, v11
; GFX11-FAKE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s42
; GFX11-FAKE16-NEXT:    s_cbranch_vccnz .LBB51_3
; GFX11-FAKE16-NEXT:  .LBB51_2: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v3, 0xc0c0004
; GFX11-FAKE16-NEXT:    s_add_i32 s18, s18, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s0, s0, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s2, s2, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s16, s16, 3
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, s18, s19, v3
; GFX11-FAKE16-NEXT:    s_add_i32 s20, s20, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s22, s22, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s24, s24, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s26, s26, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, 0x300, v4
; GFX11-FAKE16-NEXT:    s_add_i32 s28, s28, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s41, s41, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s15, s15, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s13, s13, 3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, s0, s1, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, s2, s3, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, s16, s17, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, s20, s21, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, s22, s23, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v0, 0x300, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v1, 0x300, v1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, 0x300, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v5, 0x300, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v6, 0x300, v6
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GFX11-FAKE16-NEXT:    s_add_i32 s11, s11, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s9, s9, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s7, s7, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s5, s5, 3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v0, v1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v1, v2, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, v5, v6
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, s24, s25, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, s26, s27, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, s28, s29, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, s41, s40, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, s15, s14, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, s13, s12, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, s11, s10, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, s9, s8, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, s7, s6, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, s5, s4, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, 0x300, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v5, 0x300, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v6, 0x300, v6
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v7, 0x300, v7
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v8, 0x300, v8
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v9, 0x300, v9
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v10, 0x300, v10
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v11, 0x300, v11
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v12, 0x300, v12
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, 0x300, v3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v13, 16, v3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v4, v5
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, v6, v7
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v5, v8, v9
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v6, v10, v11
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v7, v12, v13
; GFX11-FAKE16-NEXT:  .LBB51_3: ; %end
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB51_4:
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-FAKE16-NEXT:    s_branch .LBB51_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <32 x i8> %a, splat (i8 3)
  %a2 = bitcast <32 x i8> %a1 to <8 x float>
  br label %end

cmp.false:
  %a3 = bitcast <32 x i8> %a to <8 x float>
  br label %end

end:
  %phi = phi <8 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <8 x float> %phi
}

define <4 x double> @bitcast_v4i64_to_v4f64(<4 x i64> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v4i64_to_v4f64:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:  ; %bb.1: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; SI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; SI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; SI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; SI-NEXT:  ; %bb.2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v4i64_to_v4f64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; VI-NEXT:  ; %bb.2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v4i64_to_v4f64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_co_u32_e32 v0, vcc, 3, v0
; GFX9-NEXT:    v_addc_co_u32_e32 v1, vcc, 0, v1, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v2, vcc, 3, v2
; GFX9-NEXT:    v_addc_co_u32_e32 v3, vcc, 0, v3, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v4, vcc, 3, v4
; GFX9-NEXT:    v_addc_co_u32_e32 v5, vcc, 0, v5, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v6, vcc, 3, v6
; GFX9-NEXT:    v_addc_co_u32_e32 v7, vcc, 0, v7, vcc
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v4i64_to_v4f64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB52_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_co_u32 v0, vcc_lo, v0, 3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_co_ci_u32_e64 v1, null, 0, v1, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v2, vcc_lo, v2, 3
; GFX11-NEXT:    v_add_co_ci_u32_e64 v3, null, 0, v3, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v4, vcc_lo, v4, 3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_co_ci_u32_e64 v5, null, 0, v5, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v6, vcc_lo, v6, 3
; GFX11-NEXT:    v_add_co_ci_u32_e64 v7, null, 0, v7, vcc_lo
; GFX11-NEXT:  .LBB52_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <4 x i64> %a, splat (i64 3)
  %a2 = bitcast <4 x i64> %a1 to <4 x double>
  br label %end

cmp.false:
  %a3 = bitcast <4 x i64> %a to <4 x double>
  br label %end

end:
  %phi = phi <4 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x double> %phi
}

define inreg <4 x double> @bitcast_v4i64_to_v4f64_scalar(<4 x i64> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v4i64_to_v4f64_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB53_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_cbranch_execnz .LBB53_3
; SI-NEXT:  .LBB53_2: ; %cmp.true
; SI-NEXT:    s_add_u32 s16, s16, 3
; SI-NEXT:    s_addc_u32 s17, s17, 0
; SI-NEXT:    s_add_u32 s18, s18, 3
; SI-NEXT:    s_addc_u32 s19, s19, 0
; SI-NEXT:    s_add_u32 s20, s20, 3
; SI-NEXT:    s_addc_u32 s21, s21, 0
; SI-NEXT:    s_add_u32 s22, s22, 3
; SI-NEXT:    s_addc_u32 s23, s23, 0
; SI-NEXT:  .LBB53_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v2, s18
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v4, s20
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v6, s22
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB53_4:
; SI-NEXT:    s_branch .LBB53_2
;
; VI-LABEL: bitcast_v4i64_to_v4f64_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB53_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB53_3
; VI-NEXT:  .LBB53_2: ; %cmp.true
; VI-NEXT:    s_add_u32 s16, s16, 3
; VI-NEXT:    s_addc_u32 s17, s17, 0
; VI-NEXT:    s_add_u32 s18, s18, 3
; VI-NEXT:    s_addc_u32 s19, s19, 0
; VI-NEXT:    s_add_u32 s20, s20, 3
; VI-NEXT:    s_addc_u32 s21, s21, 0
; VI-NEXT:    s_add_u32 s22, s22, 3
; VI-NEXT:    s_addc_u32 s23, s23, 0
; VI-NEXT:  .LBB53_3: ; %end
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB53_4:
; VI-NEXT:    s_branch .LBB53_2
;
; GFX9-LABEL: bitcast_v4i64_to_v4f64_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB53_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB53_3
; GFX9-NEXT:  .LBB53_2: ; %cmp.true
; GFX9-NEXT:    s_add_u32 s16, s16, 3
; GFX9-NEXT:    s_addc_u32 s17, s17, 0
; GFX9-NEXT:    s_add_u32 s18, s18, 3
; GFX9-NEXT:    s_addc_u32 s19, s19, 0
; GFX9-NEXT:    s_add_u32 s20, s20, 3
; GFX9-NEXT:    s_addc_u32 s21, s21, 0
; GFX9-NEXT:    s_add_u32 s22, s22, 3
; GFX9-NEXT:    s_addc_u32 s23, s23, 0
; GFX9-NEXT:  .LBB53_3: ; %end
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB53_4:
; GFX9-NEXT:    s_branch .LBB53_2
;
; GFX11-LABEL: bitcast_v4i64_to_v4f64_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s4, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB53_4
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s4
; GFX11-NEXT:    s_cbranch_vccnz .LBB53_3
; GFX11-NEXT:  .LBB53_2: ; %cmp.true
; GFX11-NEXT:    s_add_u32 s0, s0, 3
; GFX11-NEXT:    s_addc_u32 s1, s1, 0
; GFX11-NEXT:    s_add_u32 s2, s2, 3
; GFX11-NEXT:    s_addc_u32 s3, s3, 0
; GFX11-NEXT:    s_add_u32 s16, s16, 3
; GFX11-NEXT:    s_addc_u32 s17, s17, 0
; GFX11-NEXT:    s_add_u32 s18, s18, 3
; GFX11-NEXT:    s_addc_u32 s19, s19, 0
; GFX11-NEXT:  .LBB53_3: ; %end
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s16 :: v_dual_mov_b32 v5, s17
; GFX11-NEXT:    v_dual_mov_b32 v6, s18 :: v_dual_mov_b32 v7, s19
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB53_4:
; GFX11-NEXT:    s_branch .LBB53_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <4 x i64> %a, splat (i64 3)
  %a2 = bitcast <4 x i64> %a1 to <4 x double>
  br label %end

cmp.false:
  %a3 = bitcast <4 x i64> %a to <4 x double>
  br label %end

end:
  %phi = phi <4 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x double> %phi
}

define <4 x i64> @bitcast_v4f64_to_v4i64(<4 x double> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v4f64_to_v4i64:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:  ; %bb.1: ; %cmp.true
; SI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; SI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; SI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; SI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; SI-NEXT:  ; %bb.2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v4f64_to_v4i64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB54_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; VI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; VI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; VI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; VI-NEXT:  .LBB54_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v4f64_to_v4i64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB54_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX9-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX9-NEXT:  .LBB54_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v4f64_to_v4i64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB54_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX11-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX11-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX11-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX11-NEXT:  .LBB54_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <4 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <4 x double> %a1 to <4 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <4 x double> %a to <4 x i64>
  br label %end

end:
  %phi = phi <4 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x i64> %phi
}

define inreg <4 x i64> @bitcast_v4f64_to_v4i64_scalar(<4 x double> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v4f64_to_v4i64_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB55_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_cbranch_execnz .LBB55_4
; SI-NEXT:  .LBB55_2: ; %cmp.true
; SI-NEXT:    v_add_f64 v[0:1], s[16:17], 1.0
; SI-NEXT:    v_add_f64 v[2:3], s[18:19], 1.0
; SI-NEXT:    v_add_f64 v[4:5], s[20:21], 1.0
; SI-NEXT:    v_add_f64 v[6:7], s[22:23], 1.0
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB55_3:
; SI-NEXT:    s_branch .LBB55_2
; SI-NEXT:  .LBB55_4:
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v2, s18
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v4, s20
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v6, s22
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v4f64_to_v4i64_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB55_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB55_4
; VI-NEXT:  .LBB55_2: ; %cmp.true
; VI-NEXT:    v_add_f64 v[0:1], s[16:17], 1.0
; VI-NEXT:    v_add_f64 v[2:3], s[18:19], 1.0
; VI-NEXT:    v_add_f64 v[4:5], s[20:21], 1.0
; VI-NEXT:    v_add_f64 v[6:7], s[22:23], 1.0
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB55_3:
; VI-NEXT:    s_branch .LBB55_2
; VI-NEXT:  .LBB55_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v4f64_to_v4i64_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB55_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB55_4
; GFX9-NEXT:  .LBB55_2: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[0:1], s[16:17], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], s[18:19], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], s[20:21], 1.0
; GFX9-NEXT:    v_add_f64 v[6:7], s[22:23], 1.0
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB55_3:
; GFX9-NEXT:    s_branch .LBB55_2
; GFX9-NEXT:  .LBB55_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v4f64_to_v4i64_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s7, s19
; GFX11-NEXT:    s_mov_b32 s6, s18
; GFX11-NEXT:    s_mov_b32 s5, s17
; GFX11-NEXT:    s_mov_b32 s4, s16
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s8, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB55_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-NEXT:    s_cbranch_vccnz .LBB55_4
; GFX11-NEXT:  .LBB55_2: ; %cmp.true
; GFX11-NEXT:    v_add_f64 v[0:1], s[0:1], 1.0
; GFX11-NEXT:    v_add_f64 v[2:3], s[2:3], 1.0
; GFX11-NEXT:    v_add_f64 v[4:5], s[4:5], 1.0
; GFX11-NEXT:    v_add_f64 v[6:7], s[6:7], 1.0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB55_3:
; GFX11-NEXT:    s_branch .LBB55_2
; GFX11-NEXT:  .LBB55_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <4 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <4 x double> %a1 to <4 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <4 x double> %a to <4 x i64>
  br label %end

end:
  %phi = phi <4 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x i64> %phi
}

define <16 x i16> @bitcast_v4i64_to_v16i16(<4 x i64> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v4i64_to_v16i16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_alignbit_b32 v8, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v9, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v10, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v13, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v1
; SI-NEXT:  ; %bb.2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB56_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; SI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; SI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; SI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; SI-NEXT:    v_alignbit_b32 v8, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v9, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v10, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v13, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v1
; SI-NEXT:  .LBB56_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v13
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v10
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_or_b32_e32 v0, v0, v13
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v15
; SI-NEXT:    v_or_b32_e32 v2, v2, v10
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v14
; SI-NEXT:    v_or_b32_e32 v4, v4, v9
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v12
; SI-NEXT:    v_or_b32_e32 v6, v6, v8
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v11
; SI-NEXT:    v_or_b32_e32 v1, v1, v13
; SI-NEXT:    v_or_b32_e32 v3, v3, v10
; SI-NEXT:    v_or_b32_e32 v5, v5, v9
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v4i64_to_v16i16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-NEXT:  ; %bb.2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v4i64_to_v16i16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_co_u32_e32 v6, vcc, 3, v6
; GFX9-NEXT:    v_addc_co_u32_e32 v7, vcc, 0, v7, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v4, vcc, 3, v4
; GFX9-NEXT:    v_addc_co_u32_e32 v5, vcc, 0, v5, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v2, vcc, 3, v2
; GFX9-NEXT:    v_addc_co_u32_e32 v3, vcc, 0, v3, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v0, vcc, 3, v0
; GFX9-NEXT:    v_addc_co_u32_e32 v1, vcc, 0, v1, vcc
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v4i64_to_v16i16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB56_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_co_u32 v6, vcc_lo, v6, 3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_co_ci_u32_e64 v7, null, 0, v7, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v4, vcc_lo, v4, 3
; GFX11-NEXT:    v_add_co_ci_u32_e64 v5, null, 0, v5, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v2, vcc_lo, v2, 3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_co_ci_u32_e64 v3, null, 0, v3, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v0, vcc_lo, v0, 3
; GFX11-NEXT:    v_add_co_ci_u32_e64 v1, null, 0, v1, vcc_lo
; GFX11-NEXT:  .LBB56_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <4 x i64> %a, splat (i64 3)
  %a2 = bitcast <4 x i64> %a1 to <16 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <4 x i64> %a to <16 x i16>
  br label %end

end:
  %phi = phi <16 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x i16> %phi
}

define inreg <16 x i16> @bitcast_v4i64_to_v16i16_scalar(<4 x i64> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v4i64_to_v16i16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB57_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_lshr_b32 s14, s23, 16
; SI-NEXT:    s_lshr_b32 s15, s21, 16
; SI-NEXT:    s_lshr_b32 s24, s19, 16
; SI-NEXT:    s_lshr_b32 s25, s17, 16
; SI-NEXT:    s_lshr_b64 s[4:5], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[6:7], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[8:9], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[10:11], s[16:17], 16
; SI-NEXT:    s_cbranch_execnz .LBB57_3
; SI-NEXT:  .LBB57_2: ; %cmp.true
; SI-NEXT:    s_add_u32 s22, s22, 3
; SI-NEXT:    s_addc_u32 s23, s23, 0
; SI-NEXT:    s_add_u32 s20, s20, 3
; SI-NEXT:    s_addc_u32 s21, s21, 0
; SI-NEXT:    s_add_u32 s18, s18, 3
; SI-NEXT:    s_addc_u32 s19, s19, 0
; SI-NEXT:    s_add_u32 s16, s16, 3
; SI-NEXT:    s_addc_u32 s17, s17, 0
; SI-NEXT:    s_lshr_b32 s14, s23, 16
; SI-NEXT:    s_lshr_b32 s15, s21, 16
; SI-NEXT:    s_lshr_b32 s24, s19, 16
; SI-NEXT:    s_lshr_b32 s25, s17, 16
; SI-NEXT:    s_lshr_b64 s[4:5], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[6:7], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[8:9], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[10:11], s[16:17], 16
; SI-NEXT:  .LBB57_3: ; %end
; SI-NEXT:    s_and_b32 s5, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s10, 16
; SI-NEXT:    s_or_b32 s5, s5, s7
; SI-NEXT:    s_and_b32 s7, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s9, s25, 16
; SI-NEXT:    s_or_b32 s7, s7, s9
; SI-NEXT:    s_and_b32 s9, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s8, s8, 16
; SI-NEXT:    s_or_b32 s8, s9, s8
; SI-NEXT:    s_and_b32 s9, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s24, 16
; SI-NEXT:    s_or_b32 s9, s9, s10
; SI-NEXT:    s_and_b32 s10, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s6, s6, 16
; SI-NEXT:    s_or_b32 s6, s10, s6
; SI-NEXT:    s_and_b32 s10, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s11, s15, 16
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_and_b32 s11, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s4, s4, 16
; SI-NEXT:    s_or_b32 s4, s11, s4
; SI-NEXT:    s_and_b32 s11, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s14, 16
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    v_mov_b32_e32 v0, s5
; SI-NEXT:    v_mov_b32_e32 v1, s7
; SI-NEXT:    v_mov_b32_e32 v2, s8
; SI-NEXT:    v_mov_b32_e32 v3, s9
; SI-NEXT:    v_mov_b32_e32 v4, s6
; SI-NEXT:    v_mov_b32_e32 v5, s10
; SI-NEXT:    v_mov_b32_e32 v6, s4
; SI-NEXT:    v_mov_b32_e32 v7, s11
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB57_4:
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr25
; SI-NEXT:    ; implicit-def: $sgpr8
; SI-NEXT:    ; implicit-def: $sgpr24
; SI-NEXT:    ; implicit-def: $sgpr6
; SI-NEXT:    ; implicit-def: $sgpr15
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    s_branch .LBB57_2
;
; VI-LABEL: bitcast_v4i64_to_v16i16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB57_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB57_3
; VI-NEXT:  .LBB57_2: ; %cmp.true
; VI-NEXT:    s_add_u32 s22, s22, 3
; VI-NEXT:    s_addc_u32 s23, s23, 0
; VI-NEXT:    s_add_u32 s20, s20, 3
; VI-NEXT:    s_addc_u32 s21, s21, 0
; VI-NEXT:    s_add_u32 s18, s18, 3
; VI-NEXT:    s_addc_u32 s19, s19, 0
; VI-NEXT:    s_add_u32 s16, s16, 3
; VI-NEXT:    s_addc_u32 s17, s17, 0
; VI-NEXT:  .LBB57_3: ; %end
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB57_4:
; VI-NEXT:    s_branch .LBB57_2
;
; GFX9-LABEL: bitcast_v4i64_to_v16i16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB57_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB57_3
; GFX9-NEXT:  .LBB57_2: ; %cmp.true
; GFX9-NEXT:    s_add_u32 s22, s22, 3
; GFX9-NEXT:    s_addc_u32 s23, s23, 0
; GFX9-NEXT:    s_add_u32 s20, s20, 3
; GFX9-NEXT:    s_addc_u32 s21, s21, 0
; GFX9-NEXT:    s_add_u32 s18, s18, 3
; GFX9-NEXT:    s_addc_u32 s19, s19, 0
; GFX9-NEXT:    s_add_u32 s16, s16, 3
; GFX9-NEXT:    s_addc_u32 s17, s17, 0
; GFX9-NEXT:  .LBB57_3: ; %end
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB57_4:
; GFX9-NEXT:    s_branch .LBB57_2
;
; GFX11-LABEL: bitcast_v4i64_to_v16i16_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s4, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB57_4
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s4
; GFX11-NEXT:    s_cbranch_vccnz .LBB57_3
; GFX11-NEXT:  .LBB57_2: ; %cmp.true
; GFX11-NEXT:    s_add_u32 s18, s18, 3
; GFX11-NEXT:    s_addc_u32 s19, s19, 0
; GFX11-NEXT:    s_add_u32 s16, s16, 3
; GFX11-NEXT:    s_addc_u32 s17, s17, 0
; GFX11-NEXT:    s_add_u32 s2, s2, 3
; GFX11-NEXT:    s_addc_u32 s3, s3, 0
; GFX11-NEXT:    s_add_u32 s0, s0, 3
; GFX11-NEXT:    s_addc_u32 s1, s1, 0
; GFX11-NEXT:  .LBB57_3: ; %end
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s16 :: v_dual_mov_b32 v5, s17
; GFX11-NEXT:    v_dual_mov_b32 v6, s18 :: v_dual_mov_b32 v7, s19
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB57_4:
; GFX11-NEXT:    s_branch .LBB57_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <4 x i64> %a, splat (i64 3)
  %a2 = bitcast <4 x i64> %a1 to <16 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <4 x i64> %a to <16 x i16>
  br label %end

end:
  %phi = phi <16 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x i16> %phi
}

define <4 x i64> @bitcast_v16i16_to_v4i64(<16 x i16> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v16i16_to_v4i64:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_mov_b32_e32 v16, v7
; SI-NEXT:    v_mov_b32_e32 v9, v6
; SI-NEXT:    v_mov_b32_e32 v10, v5
; SI-NEXT:    v_mov_b32_e32 v11, v4
; SI-NEXT:    v_mov_b32_e32 v12, v3
; SI-NEXT:    v_mov_b32_e32 v13, v2
; SI-NEXT:    v_mov_b32_e32 v14, v1
; SI-NEXT:    v_mov_b32_e32 v15, v0
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v16
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v10
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v12
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v14
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v15
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v7
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v6
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v5
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v4
; SI-NEXT:    v_lshlrev_b32_e32 v19, 16, v3
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v2
; SI-NEXT:    v_lshlrev_b32_e32 v17, 16, v1
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v0
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB58_3
; SI-NEXT:  ; %bb.1: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB58_4
; SI-NEXT:  .LBB58_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB58_3: ; %cmp.false
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v15
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v14
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v13
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v12
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v11
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v10
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v9
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v16
; SI-NEXT:    v_or_b32_e32 v0, v0, v23
; SI-NEXT:    v_or_b32_e32 v1, v1, v22
; SI-NEXT:    v_or_b32_e32 v2, v2, v21
; SI-NEXT:    v_or_b32_e32 v3, v3, v20
; SI-NEXT:    v_or_b32_e32 v4, v4, v19
; SI-NEXT:    v_or_b32_e32 v5, v5, v18
; SI-NEXT:    v_or_b32_e32 v6, v6, v17
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB58_2
; SI-NEXT:  .LBB58_4: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v15
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v14
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v13
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v12
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v11
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v10
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v9
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v16
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_or_b32_e32 v0, v23, v0
; SI-NEXT:    s_mov_b32 s6, 0x30000
; SI-NEXT:    v_or_b32_e32 v1, v22, v1
; SI-NEXT:    v_or_b32_e32 v2, v21, v2
; SI-NEXT:    v_or_b32_e32 v3, v20, v3
; SI-NEXT:    v_or_b32_e32 v4, v19, v4
; SI-NEXT:    v_or_b32_e32 v5, v18, v5
; SI-NEXT:    v_or_b32_e32 v6, v17, v6
; SI-NEXT:    v_or_b32_e32 v7, v8, v7
; SI-NEXT:    v_add_i32_e32 v0, vcc, 0x30000, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, s6, v1
; SI-NEXT:    v_add_i32_e32 v2, vcc, s6, v2
; SI-NEXT:    v_add_i32_e32 v3, vcc, s6, v3
; SI-NEXT:    v_add_i32_e32 v4, vcc, s6, v4
; SI-NEXT:    v_add_i32_e32 v5, vcc, 0x30000, v5
; SI-NEXT:    v_add_i32_e32 v6, vcc, 0x30000, v6
; SI-NEXT:    v_add_i32_e32 v7, vcc, 0x30000, v7
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16i16_to_v4i64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB58_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v9, 3
; VI-NEXT:    v_add_u16_e32 v8, 3, v7
; VI-NEXT:    v_add_u16_sdwa v7, v7, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v7, v8, v7
; VI-NEXT:    v_add_u16_e32 v8, 3, v6
; VI-NEXT:    v_add_u16_sdwa v6, v6, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v6, v8, v6
; VI-NEXT:    v_add_u16_e32 v8, 3, v5
; VI-NEXT:    v_add_u16_sdwa v5, v5, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v5, v8, v5
; VI-NEXT:    v_add_u16_e32 v8, 3, v4
; VI-NEXT:    v_add_u16_sdwa v4, v4, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v4, v8, v4
; VI-NEXT:    v_add_u16_e32 v8, 3, v3
; VI-NEXT:    v_add_u16_sdwa v3, v3, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v3, v8, v3
; VI-NEXT:    v_add_u16_e32 v8, 3, v2
; VI-NEXT:    v_add_u16_sdwa v2, v2, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v2, v8, v2
; VI-NEXT:    v_add_u16_e32 v8, 3, v1
; VI-NEXT:    v_add_u16_sdwa v1, v1, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v1, v8, v1
; VI-NEXT:    v_add_u16_e32 v8, 3, v0
; VI-NEXT:    v_add_u16_sdwa v0, v0, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v0, v8, v0
; VI-NEXT:  .LBB58_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16i16_to_v4i64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v16i16_to_v4i64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB58_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX11-NEXT:  .LBB58_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <16 x i16> %a, splat (i16 3)
  %a2 = bitcast <16 x i16> %a1 to <4 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <16 x i16> %a to <4 x i64>
  br label %end

end:
  %phi = phi <4 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x i64> %phi
}

define inreg <4 x i64> @bitcast_v16i16_to_v4i64_scalar(<16 x i16> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v16i16_to_v4i64_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_lshr_b32 s14, s23, 16
; SI-NEXT:    s_lshr_b32 s15, s22, 16
; SI-NEXT:    s_lshr_b32 s25, s21, 16
; SI-NEXT:    s_lshr_b32 s26, s20, 16
; SI-NEXT:    s_lshr_b32 s27, s19, 16
; SI-NEXT:    s_lshr_b32 s28, s18, 16
; SI-NEXT:    s_lshr_b32 s29, s17, 16
; SI-NEXT:    s_lshr_b32 s40, s16, 16
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB59_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s40, 16
; SI-NEXT:    s_or_b32 s4, s4, s5
; SI-NEXT:    s_and_b32 s5, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s6, s29, 16
; SI-NEXT:    s_or_b32 s5, s5, s6
; SI-NEXT:    s_and_b32 s6, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s28, 16
; SI-NEXT:    s_or_b32 s6, s6, s7
; SI-NEXT:    s_and_b32 s7, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s8, s27, 16
; SI-NEXT:    s_or_b32 s7, s7, s8
; SI-NEXT:    s_and_b32 s8, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s9, s26, 16
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_and_b32 s9, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s25, 16
; SI-NEXT:    s_or_b32 s9, s9, s10
; SI-NEXT:    s_and_b32 s10, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s11, s15, 16
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_and_b32 s11, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s14, 16
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    s_cbranch_execnz .LBB59_3
; SI-NEXT:  .LBB59_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s40, 16
; SI-NEXT:    s_add_i32 s17, s17, 3
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_and_b32 s5, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s6, s29, 16
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_or_b32 s5, s6, s5
; SI-NEXT:    s_and_b32 s6, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s28, 16
; SI-NEXT:    s_add_i32 s19, s19, 3
; SI-NEXT:    s_or_b32 s6, s7, s6
; SI-NEXT:    s_and_b32 s7, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s8, s27, 16
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_or_b32 s7, s8, s7
; SI-NEXT:    s_and_b32 s8, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s9, s26, 16
; SI-NEXT:    s_add_i32 s21, s21, 3
; SI-NEXT:    s_or_b32 s8, s9, s8
; SI-NEXT:    s_and_b32 s9, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s25, 16
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_or_b32 s9, s10, s9
; SI-NEXT:    s_and_b32 s10, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s11, s15, 16
; SI-NEXT:    s_add_i32 s23, s23, 3
; SI-NEXT:    s_or_b32 s10, s11, s10
; SI-NEXT:    s_and_b32 s11, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s14, 16
; SI-NEXT:    s_or_b32 s11, s12, s11
; SI-NEXT:    s_add_i32 s4, s4, 0x30000
; SI-NEXT:    s_add_i32 s5, s5, 0x30000
; SI-NEXT:    s_add_i32 s6, s6, 0x30000
; SI-NEXT:    s_add_i32 s7, s7, 0x30000
; SI-NEXT:    s_add_i32 s8, s8, 0x30000
; SI-NEXT:    s_add_i32 s9, s9, 0x30000
; SI-NEXT:    s_add_i32 s10, s10, 0x30000
; SI-NEXT:    s_add_i32 s11, s11, 0x30000
; SI-NEXT:  .LBB59_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v0, s4
; SI-NEXT:    v_mov_b32_e32 v1, s5
; SI-NEXT:    v_mov_b32_e32 v2, s6
; SI-NEXT:    v_mov_b32_e32 v3, s7
; SI-NEXT:    v_mov_b32_e32 v4, s8
; SI-NEXT:    v_mov_b32_e32 v5, s9
; SI-NEXT:    v_mov_b32_e32 v6, s10
; SI-NEXT:    v_mov_b32_e32 v7, s11
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB59_4:
; SI-NEXT:    ; implicit-def: $sgpr4_sgpr5_sgpr6_sgpr7_sgpr8_sgpr9_sgpr10_sgpr11
; SI-NEXT:    s_branch .LBB59_2
;
; VI-LABEL: bitcast_v16i16_to_v4i64_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB59_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB59_3
; VI-NEXT:  .LBB59_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s5, s23, 3
; VI-NEXT:    s_and_b32 s4, s23, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s22, 3
; VI-NEXT:    s_add_i32 s23, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s22, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s21, 3
; VI-NEXT:    s_add_i32 s22, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s21, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s20, 3
; VI-NEXT:    s_add_i32 s21, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s20, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s19, 3
; VI-NEXT:    s_add_i32 s20, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s19, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s18, 3
; VI-NEXT:    s_add_i32 s19, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s18, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s17, 3
; VI-NEXT:    s_add_i32 s18, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s17, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s16, 3
; VI-NEXT:    s_add_i32 s17, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s16, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s16, s4, 0x30000
; VI-NEXT:  .LBB59_3: ; %end
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB59_4:
; VI-NEXT:    s_branch .LBB59_2
;
; GFX9-LABEL: bitcast_v16i16_to_v4i64_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB59_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB59_4
; GFX9-NEXT:  .LBB59_2: ; %cmp.true
; GFX9-NEXT:    v_pk_add_u16 v7, s23, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, s22, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v5, s21, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v4, s20, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v3, s19, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v2, s18, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v1, s17, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v0, s16, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB59_3:
; GFX9-NEXT:    s_branch .LBB59_2
; GFX9-NEXT:  .LBB59_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v16i16_to_v4i64_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s7, s19
; GFX11-NEXT:    s_mov_b32 s6, s18
; GFX11-NEXT:    s_mov_b32 s5, s17
; GFX11-NEXT:    s_mov_b32 s4, s16
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s8, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB59_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-NEXT:    s_cbranch_vccnz .LBB59_4
; GFX11-NEXT:  .LBB59_2: ; %cmp.true
; GFX11-NEXT:    v_pk_add_u16 v7, s7, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v6, s6, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v5, s5, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v4, s4, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v3, s3, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v2, s2, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v1, s1, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v0, s0, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB59_3:
; GFX11-NEXT:    s_branch .LBB59_2
; GFX11-NEXT:  .LBB59_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <16 x i16> %a, splat (i16 3)
  %a2 = bitcast <16 x i16> %a1 to <4 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <16 x i16> %a to <4 x i64>
  br label %end

end:
  %phi = phi <4 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x i64> %phi
}

define <16 x half> @bitcast_v4i64_to_v16f16(<4 x i64> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v4i64_to_v16f16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_alignbit_b32 v8, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v9, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v10, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v13, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v1
; SI-NEXT:  ; %bb.2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB60_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; SI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; SI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; SI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; SI-NEXT:    v_alignbit_b32 v8, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v9, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v10, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v13, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v1
; SI-NEXT:  .LBB60_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v13
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v10
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_or_b32_e32 v0, v0, v13
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v15
; SI-NEXT:    v_or_b32_e32 v2, v2, v10
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v14
; SI-NEXT:    v_or_b32_e32 v4, v4, v9
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v12
; SI-NEXT:    v_or_b32_e32 v6, v6, v8
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v11
; SI-NEXT:    v_or_b32_e32 v1, v1, v13
; SI-NEXT:    v_or_b32_e32 v3, v3, v10
; SI-NEXT:    v_or_b32_e32 v5, v5, v9
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v4i64_to_v16f16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-NEXT:  ; %bb.2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v4i64_to_v16f16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_co_u32_e32 v6, vcc, 3, v6
; GFX9-NEXT:    v_addc_co_u32_e32 v7, vcc, 0, v7, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v4, vcc, 3, v4
; GFX9-NEXT:    v_addc_co_u32_e32 v5, vcc, 0, v5, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v2, vcc, 3, v2
; GFX9-NEXT:    v_addc_co_u32_e32 v3, vcc, 0, v3, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v0, vcc, 3, v0
; GFX9-NEXT:    v_addc_co_u32_e32 v1, vcc, 0, v1, vcc
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v4i64_to_v16f16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB60_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_co_u32 v6, vcc_lo, v6, 3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_co_ci_u32_e64 v7, null, 0, v7, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v4, vcc_lo, v4, 3
; GFX11-NEXT:    v_add_co_ci_u32_e64 v5, null, 0, v5, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v2, vcc_lo, v2, 3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_co_ci_u32_e64 v3, null, 0, v3, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v0, vcc_lo, v0, 3
; GFX11-NEXT:    v_add_co_ci_u32_e64 v1, null, 0, v1, vcc_lo
; GFX11-NEXT:  .LBB60_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <4 x i64> %a, splat (i64 3)
  %a2 = bitcast <4 x i64> %a1 to <16 x half>
  br label %end

cmp.false:
  %a3 = bitcast <4 x i64> %a to <16 x half>
  br label %end

end:
  %phi = phi <16 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x half> %phi
}

define inreg <16 x half> @bitcast_v4i64_to_v16f16_scalar(<4 x i64> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v4i64_to_v16f16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB61_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_lshr_b32 s14, s23, 16
; SI-NEXT:    s_lshr_b32 s15, s21, 16
; SI-NEXT:    s_lshr_b32 s24, s19, 16
; SI-NEXT:    s_lshr_b32 s25, s17, 16
; SI-NEXT:    s_lshr_b64 s[4:5], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[6:7], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[8:9], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[10:11], s[16:17], 16
; SI-NEXT:    s_cbranch_execnz .LBB61_3
; SI-NEXT:  .LBB61_2: ; %cmp.true
; SI-NEXT:    s_add_u32 s22, s22, 3
; SI-NEXT:    s_addc_u32 s23, s23, 0
; SI-NEXT:    s_add_u32 s20, s20, 3
; SI-NEXT:    s_addc_u32 s21, s21, 0
; SI-NEXT:    s_add_u32 s18, s18, 3
; SI-NEXT:    s_addc_u32 s19, s19, 0
; SI-NEXT:    s_add_u32 s16, s16, 3
; SI-NEXT:    s_addc_u32 s17, s17, 0
; SI-NEXT:    s_lshr_b32 s14, s23, 16
; SI-NEXT:    s_lshr_b32 s15, s21, 16
; SI-NEXT:    s_lshr_b32 s24, s19, 16
; SI-NEXT:    s_lshr_b32 s25, s17, 16
; SI-NEXT:    s_lshr_b64 s[4:5], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[6:7], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[8:9], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[10:11], s[16:17], 16
; SI-NEXT:  .LBB61_3: ; %end
; SI-NEXT:    s_and_b32 s5, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s10, 16
; SI-NEXT:    s_or_b32 s5, s5, s7
; SI-NEXT:    s_and_b32 s7, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s9, s25, 16
; SI-NEXT:    s_or_b32 s7, s7, s9
; SI-NEXT:    s_and_b32 s9, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s8, s8, 16
; SI-NEXT:    s_or_b32 s8, s9, s8
; SI-NEXT:    s_and_b32 s9, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s24, 16
; SI-NEXT:    s_or_b32 s9, s9, s10
; SI-NEXT:    s_and_b32 s10, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s6, s6, 16
; SI-NEXT:    s_or_b32 s6, s10, s6
; SI-NEXT:    s_and_b32 s10, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s11, s15, 16
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_and_b32 s11, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s4, s4, 16
; SI-NEXT:    s_or_b32 s4, s11, s4
; SI-NEXT:    s_and_b32 s11, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s14, 16
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    v_mov_b32_e32 v0, s5
; SI-NEXT:    v_mov_b32_e32 v1, s7
; SI-NEXT:    v_mov_b32_e32 v2, s8
; SI-NEXT:    v_mov_b32_e32 v3, s9
; SI-NEXT:    v_mov_b32_e32 v4, s6
; SI-NEXT:    v_mov_b32_e32 v5, s10
; SI-NEXT:    v_mov_b32_e32 v6, s4
; SI-NEXT:    v_mov_b32_e32 v7, s11
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB61_4:
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr25
; SI-NEXT:    ; implicit-def: $sgpr8
; SI-NEXT:    ; implicit-def: $sgpr24
; SI-NEXT:    ; implicit-def: $sgpr6
; SI-NEXT:    ; implicit-def: $sgpr15
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    s_branch .LBB61_2
;
; VI-LABEL: bitcast_v4i64_to_v16f16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB61_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB61_3
; VI-NEXT:  .LBB61_2: ; %cmp.true
; VI-NEXT:    s_add_u32 s22, s22, 3
; VI-NEXT:    s_addc_u32 s23, s23, 0
; VI-NEXT:    s_add_u32 s20, s20, 3
; VI-NEXT:    s_addc_u32 s21, s21, 0
; VI-NEXT:    s_add_u32 s18, s18, 3
; VI-NEXT:    s_addc_u32 s19, s19, 0
; VI-NEXT:    s_add_u32 s16, s16, 3
; VI-NEXT:    s_addc_u32 s17, s17, 0
; VI-NEXT:  .LBB61_3: ; %end
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB61_4:
; VI-NEXT:    s_branch .LBB61_2
;
; GFX9-LABEL: bitcast_v4i64_to_v16f16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB61_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB61_3
; GFX9-NEXT:  .LBB61_2: ; %cmp.true
; GFX9-NEXT:    s_add_u32 s22, s22, 3
; GFX9-NEXT:    s_addc_u32 s23, s23, 0
; GFX9-NEXT:    s_add_u32 s20, s20, 3
; GFX9-NEXT:    s_addc_u32 s21, s21, 0
; GFX9-NEXT:    s_add_u32 s18, s18, 3
; GFX9-NEXT:    s_addc_u32 s19, s19, 0
; GFX9-NEXT:    s_add_u32 s16, s16, 3
; GFX9-NEXT:    s_addc_u32 s17, s17, 0
; GFX9-NEXT:  .LBB61_3: ; %end
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB61_4:
; GFX9-NEXT:    s_branch .LBB61_2
;
; GFX11-LABEL: bitcast_v4i64_to_v16f16_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s4, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB61_4
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s4
; GFX11-NEXT:    s_cbranch_vccnz .LBB61_3
; GFX11-NEXT:  .LBB61_2: ; %cmp.true
; GFX11-NEXT:    s_add_u32 s18, s18, 3
; GFX11-NEXT:    s_addc_u32 s19, s19, 0
; GFX11-NEXT:    s_add_u32 s16, s16, 3
; GFX11-NEXT:    s_addc_u32 s17, s17, 0
; GFX11-NEXT:    s_add_u32 s2, s2, 3
; GFX11-NEXT:    s_addc_u32 s3, s3, 0
; GFX11-NEXT:    s_add_u32 s0, s0, 3
; GFX11-NEXT:    s_addc_u32 s1, s1, 0
; GFX11-NEXT:  .LBB61_3: ; %end
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s16 :: v_dual_mov_b32 v5, s17
; GFX11-NEXT:    v_dual_mov_b32 v6, s18 :: v_dual_mov_b32 v7, s19
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB61_4:
; GFX11-NEXT:    s_branch .LBB61_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <4 x i64> %a, splat (i64 3)
  %a2 = bitcast <4 x i64> %a1 to <16 x half>
  br label %end

cmp.false:
  %a3 = bitcast <4 x i64> %a to <16 x half>
  br label %end

end:
  %phi = phi <16 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x half> %phi
}

define <4 x i64> @bitcast_v16f16_to_v4i64(<16 x half> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v16f16_to_v4i64:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_mov_b32_e32 v16, v7
; SI-NEXT:    v_mov_b32_e32 v9, v6
; SI-NEXT:    v_mov_b32_e32 v10, v5
; SI-NEXT:    v_mov_b32_e32 v11, v4
; SI-NEXT:    v_mov_b32_e32 v12, v3
; SI-NEXT:    v_mov_b32_e32 v13, v2
; SI-NEXT:    v_mov_b32_e32 v14, v1
; SI-NEXT:    v_mov_b32_e32 v15, v0
; SI-NEXT:    v_lshrrev_b32_e32 v17, 16, v16
; SI-NEXT:    v_lshrrev_b32_e32 v18, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v19, 16, v10
; SI-NEXT:    v_lshrrev_b32_e32 v20, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v21, 16, v12
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v23, 16, v14
; SI-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB62_3
; SI-NEXT:  ; %bb.1: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB62_4
; SI-NEXT:  .LBB62_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB62_3: ; %cmp.false
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v15
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v24
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v14
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v23
; SI-NEXT:    v_or_b32_e32 v0, v0, v1
; SI-NEXT:    v_or_b32_e32 v1, v2, v3
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v13
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v22
; SI-NEXT:    v_or_b32_e32 v2, v2, v3
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v12
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v21
; SI-NEXT:    v_or_b32_e32 v3, v3, v4
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v11
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v20
; SI-NEXT:    v_or_b32_e32 v4, v4, v5
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v10
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v19
; SI-NEXT:    v_or_b32_e32 v5, v5, v6
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v9
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v18
; SI-NEXT:    v_or_b32_e32 v6, v6, v7
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v16
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v17
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr24
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB62_2
; SI-NEXT:  .LBB62_4: ; %cmp.true
; SI-NEXT:    v_cvt_f32_f16_e32 v0, v24
; SI-NEXT:    v_cvt_f32_f16_e32 v2, v23
; SI-NEXT:    v_cvt_f32_f16_e32 v1, v15
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v14
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_or_b32_e32 v0, v1, v0
; SI-NEXT:    v_or_b32_e32 v1, v3, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v2, v22
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v13
; SI-NEXT:    v_cvt_f32_f16_e32 v4, v21
; SI-NEXT:    v_cvt_f32_f16_e32 v5, v20
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_or_b32_e32 v2, v3, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v12
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v6, v11
; SI-NEXT:    v_cvt_f32_f16_e32 v7, v10
; SI-NEXT:    v_cvt_f32_f16_e32 v8, v17
; SI-NEXT:    v_or_b32_e32 v3, v3, v4
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v5, v19
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_or_b32_e32 v4, v6, v4
; SI-NEXT:    v_cvt_f32_f16_e32 v6, v18
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_or_b32_e32 v5, v7, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v7, v9
; SI-NEXT:    v_cvt_f32_f16_e32 v9, v16
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v8, v8
; SI-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v9
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_or_b32_e32 v6, v7, v6
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v8
; SI-NEXT:    v_or_b32_e32 v7, v9, v7
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16f16_to_v4i64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB62_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v8, 0x200
; VI-NEXT:    v_add_f16_sdwa v9, v7, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v7, 0x200, v7
; VI-NEXT:    v_or_b32_e32 v7, v7, v9
; VI-NEXT:    v_add_f16_sdwa v9, v6, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v6, 0x200, v6
; VI-NEXT:    v_or_b32_e32 v6, v6, v9
; VI-NEXT:    v_add_f16_sdwa v9, v5, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v5, 0x200, v5
; VI-NEXT:    v_or_b32_e32 v5, v5, v9
; VI-NEXT:    v_add_f16_sdwa v9, v4, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v4, 0x200, v4
; VI-NEXT:    v_or_b32_e32 v4, v4, v9
; VI-NEXT:    v_add_f16_sdwa v9, v3, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v3, 0x200, v3
; VI-NEXT:    v_or_b32_e32 v3, v3, v9
; VI-NEXT:    v_add_f16_sdwa v9, v2, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, 0x200, v2
; VI-NEXT:    v_or_b32_e32 v2, v2, v9
; VI-NEXT:    v_add_f16_sdwa v9, v1, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v1, 0x200, v1
; VI-NEXT:    v_add_f16_sdwa v8, v0, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v0, 0x200, v0
; VI-NEXT:    v_or_b32_e32 v1, v1, v9
; VI-NEXT:    v_or_b32_e32 v0, v0, v8
; VI-NEXT:  .LBB62_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16f16_to_v4i64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    s_movk_i32 s6, 0x200
; GFX9-NEXT:    v_pk_add_f16 v7, v7, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, v6, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v5, v5, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v4, v4, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v3, v3, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v2, v2, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v1, v1, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v0, v0, s6 op_sel_hi:[1,0]
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v16f16_to_v4i64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB62_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_pk_add_f16 v7, 0x200, v7 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v6, 0x200, v6 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v5, 0x200, v5 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v4, 0x200, v4 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v3, 0x200, v3 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v2, 0x200, v2 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v1, 0x200, v1 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v0, 0x200, v0 op_sel_hi:[0,1]
; GFX11-NEXT:  .LBB62_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <16 x half> %a1 to <4 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <16 x half> %a to <4 x i64>
  br label %end

end:
  %phi = phi <4 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x i64> %phi
}

define inreg <4 x i64> @bitcast_v16f16_to_v4i64_scalar(<16 x half> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v16f16_to_v4i64_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_lshr_b32 s14, s23, 16
; SI-NEXT:    s_lshr_b32 s15, s22, 16
; SI-NEXT:    s_lshr_b32 s25, s21, 16
; SI-NEXT:    s_lshr_b32 s26, s20, 16
; SI-NEXT:    s_lshr_b32 s27, s19, 16
; SI-NEXT:    s_lshr_b32 s28, s18, 16
; SI-NEXT:    s_lshr_b32 s29, s17, 16
; SI-NEXT:    s_lshr_b32 s40, s16, 16
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB63_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s40, 16
; SI-NEXT:    s_or_b32 s4, s4, s5
; SI-NEXT:    s_and_b32 s5, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s6, s29, 16
; SI-NEXT:    s_or_b32 s5, s5, s6
; SI-NEXT:    s_and_b32 s6, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s28, 16
; SI-NEXT:    s_or_b32 s6, s6, s7
; SI-NEXT:    s_and_b32 s7, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s8, s27, 16
; SI-NEXT:    s_or_b32 s7, s7, s8
; SI-NEXT:    s_and_b32 s8, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s9, s26, 16
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_and_b32 s9, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s25, 16
; SI-NEXT:    s_or_b32 s9, s9, s10
; SI-NEXT:    s_and_b32 s10, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s11, s15, 16
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_and_b32 s11, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s14, 16
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    s_cbranch_execnz .LBB63_4
; SI-NEXT:  .LBB63_2: ; %cmp.true
; SI-NEXT:    v_cvt_f32_f16_e32 v0, s40
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s16
; SI-NEXT:    v_cvt_f32_f16_e32 v2, s29
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s17
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_cvt_f32_f16_e32 v4, s18
; SI-NEXT:    v_or_b32_e32 v0, v1, v0
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v2, s28
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_or_b32_e32 v1, v3, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s27
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_or_b32_e32 v2, v4, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v4, s19
; SI-NEXT:    v_cvt_f32_f16_e32 v5, s26
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v6, s20
; SI-NEXT:    v_or_b32_e32 v3, v4, v3
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v5, s25
; SI-NEXT:    v_cvt_f32_f16_e32 v7, s21
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_or_b32_e32 v4, v6, v4
; SI-NEXT:    v_cvt_f32_f16_e32 v6, s15
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_or_b32_e32 v5, v7, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v7, s22
; SI-NEXT:    v_cvt_f32_f16_e32 v8, s14
; SI-NEXT:    v_cvt_f32_f16_e32 v9, s23
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v8, v8
; SI-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v9
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_or_b32_e32 v6, v7, v6
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v8
; SI-NEXT:    v_or_b32_e32 v7, v9, v7
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB63_3:
; SI-NEXT:    ; implicit-def: $sgpr4_sgpr5_sgpr6_sgpr7_sgpr8_sgpr9_sgpr10_sgpr11
; SI-NEXT:    s_branch .LBB63_2
; SI-NEXT:  .LBB63_4:
; SI-NEXT:    v_mov_b32_e32 v0, s4
; SI-NEXT:    v_mov_b32_e32 v1, s5
; SI-NEXT:    v_mov_b32_e32 v2, s6
; SI-NEXT:    v_mov_b32_e32 v3, s7
; SI-NEXT:    v_mov_b32_e32 v4, s8
; SI-NEXT:    v_mov_b32_e32 v5, s9
; SI-NEXT:    v_mov_b32_e32 v6, s10
; SI-NEXT:    v_mov_b32_e32 v7, s11
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16f16_to_v4i64_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB63_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB63_4
; VI-NEXT:  .LBB63_2: ; %cmp.true
; VI-NEXT:    s_lshr_b32 s4, s23, 16
; VI-NEXT:    v_mov_b32_e32 v0, 0x200
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, s23, v0
; VI-NEXT:    s_lshr_b32 s4, s22, 16
; VI-NEXT:    v_or_b32_e32 v7, v2, v1
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, s22, v0
; VI-NEXT:    s_lshr_b32 s4, s21, 16
; VI-NEXT:    v_or_b32_e32 v6, v2, v1
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, s21, v0
; VI-NEXT:    s_lshr_b32 s4, s20, 16
; VI-NEXT:    v_or_b32_e32 v5, v2, v1
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, s20, v0
; VI-NEXT:    s_lshr_b32 s4, s19, 16
; VI-NEXT:    v_or_b32_e32 v4, v2, v1
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, s19, v0
; VI-NEXT:    s_lshr_b32 s4, s18, 16
; VI-NEXT:    v_or_b32_e32 v3, v2, v1
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, s18, v0
; VI-NEXT:    s_lshr_b32 s4, s17, 16
; VI-NEXT:    v_or_b32_e32 v2, v2, v1
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v8, s17, v0
; VI-NEXT:    s_lshr_b32 s4, s16, 16
; VI-NEXT:    v_or_b32_e32 v1, v8, v1
; VI-NEXT:    v_mov_b32_e32 v8, s4
; VI-NEXT:    v_add_f16_sdwa v8, v8, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v0, s16, v0
; VI-NEXT:    v_or_b32_e32 v0, v0, v8
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB63_3:
; VI-NEXT:    s_branch .LBB63_2
; VI-NEXT:  .LBB63_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16f16_to_v4i64_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB63_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB63_4
; GFX9-NEXT:  .LBB63_2: ; %cmp.true
; GFX9-NEXT:    v_mov_b32_e32 v0, 0x200
; GFX9-NEXT:    v_pk_add_f16 v7, s23, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, s22, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v5, s21, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v4, s20, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v3, s19, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v2, s18, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v1, s17, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v0, s16, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB63_3:
; GFX9-NEXT:    s_branch .LBB63_2
; GFX9-NEXT:  .LBB63_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v16f16_to_v4i64_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s7, s19
; GFX11-NEXT:    s_mov_b32 s6, s18
; GFX11-NEXT:    s_mov_b32 s5, s17
; GFX11-NEXT:    s_mov_b32 s4, s16
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s8, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB63_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-NEXT:    s_cbranch_vccnz .LBB63_4
; GFX11-NEXT:  .LBB63_2: ; %cmp.true
; GFX11-NEXT:    v_pk_add_f16 v7, 0x200, s7 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v6, 0x200, s6 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v5, 0x200, s5 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v4, 0x200, s4 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v3, 0x200, s3 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v2, 0x200, s2 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v1, 0x200, s1 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v0, 0x200, s0 op_sel_hi:[0,1]
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB63_3:
; GFX11-NEXT:    s_branch .LBB63_2
; GFX11-NEXT:  .LBB63_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <16 x half> %a1 to <4 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <16 x half> %a to <4 x i64>
  br label %end

end:
  %phi = phi <4 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x i64> %phi
}

define <16 x bfloat> @bitcast_v4i64_to_v16bf16(<4 x i64> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v4i64_to_v16bf16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB64_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_and_b32_e32 v9, 0xffff0000, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v7
; SI-NEXT:    v_and_b32_e32 v11, 0xffff0000, v6
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v6
; SI-NEXT:    v_and_b32_e32 v13, 0xffff0000, v5
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v5
; SI-NEXT:    v_and_b32_e32 v15, 0xffff0000, v4
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v4
; SI-NEXT:    v_and_b32_e32 v17, 0xffff0000, v3
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v3
; SI-NEXT:    v_and_b32_e32 v19, 0xffff0000, v2
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v2
; SI-NEXT:    v_and_b32_e32 v21, 0xffff0000, v1
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v1
; SI-NEXT:    v_and_b32_e32 v23, 0xffff0000, v0
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v0
; SI-NEXT:    ; implicit-def: $vgpr0
; SI-NEXT:    ; implicit-def: $vgpr1
; SI-NEXT:    ; implicit-def: $vgpr2
; SI-NEXT:    ; implicit-def: $vgpr3
; SI-NEXT:    ; implicit-def: $vgpr4
; SI-NEXT:    ; implicit-def: $vgpr5
; SI-NEXT:    ; implicit-def: $vgpr6
; SI-NEXT:    ; implicit-def: $vgpr7
; SI-NEXT:  .LBB64_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB64_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; SI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; SI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; SI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; SI-NEXT:    v_and_b32_e32 v9, 0xffff0000, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v7
; SI-NEXT:    v_and_b32_e32 v11, 0xffff0000, v6
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v6
; SI-NEXT:    v_and_b32_e32 v13, 0xffff0000, v5
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v5
; SI-NEXT:    v_and_b32_e32 v15, 0xffff0000, v4
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v4
; SI-NEXT:    v_and_b32_e32 v17, 0xffff0000, v3
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v3
; SI-NEXT:    v_and_b32_e32 v19, 0xffff0000, v2
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v2
; SI-NEXT:    v_and_b32_e32 v21, 0xffff0000, v1
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v1
; SI-NEXT:    v_and_b32_e32 v23, 0xffff0000, v0
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v0
; SI-NEXT:  .LBB64_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_mul_f32_e32 v0, 1.0, v23
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_mul_f32_e32 v1, 1.0, v22
; SI-NEXT:    v_alignbit_b32 v0, v0, v1, 16
; SI-NEXT:    v_mul_f32_e32 v1, 1.0, v21
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_mul_f32_e32 v2, 1.0, v20
; SI-NEXT:    v_alignbit_b32 v1, v1, v2, 16
; SI-NEXT:    v_mul_f32_e32 v2, 1.0, v19
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_mul_f32_e32 v3, 1.0, v18
; SI-NEXT:    v_alignbit_b32 v2, v2, v3, 16
; SI-NEXT:    v_mul_f32_e32 v3, 1.0, v17
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_mul_f32_e32 v4, 1.0, v16
; SI-NEXT:    v_alignbit_b32 v3, v3, v4, 16
; SI-NEXT:    v_mul_f32_e32 v4, 1.0, v15
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_mul_f32_e32 v5, 1.0, v14
; SI-NEXT:    v_alignbit_b32 v4, v4, v5, 16
; SI-NEXT:    v_mul_f32_e32 v5, 1.0, v13
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_mul_f32_e32 v6, 1.0, v12
; SI-NEXT:    v_alignbit_b32 v5, v5, v6, 16
; SI-NEXT:    v_mul_f32_e32 v6, 1.0, v11
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_mul_f32_e32 v7, 1.0, v10
; SI-NEXT:    v_alignbit_b32 v6, v6, v7, 16
; SI-NEXT:    v_mul_f32_e32 v7, 1.0, v9
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_mul_f32_e32 v8, 1.0, v8
; SI-NEXT:    v_alignbit_b32 v7, v7, v8, 16
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v4i64_to_v16bf16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-NEXT:  ; %bb.2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v4i64_to_v16bf16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_co_u32_e32 v6, vcc, 3, v6
; GFX9-NEXT:    v_addc_co_u32_e32 v7, vcc, 0, v7, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v4, vcc, 3, v4
; GFX9-NEXT:    v_addc_co_u32_e32 v5, vcc, 0, v5, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v2, vcc, 3, v2
; GFX9-NEXT:    v_addc_co_u32_e32 v3, vcc, 0, v3, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v0, vcc, 3, v0
; GFX9-NEXT:    v_addc_co_u32_e32 v1, vcc, 0, v1, vcc
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v4i64_to_v16bf16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB64_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_co_u32 v6, vcc_lo, v6, 3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_co_ci_u32_e64 v7, null, 0, v7, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v4, vcc_lo, v4, 3
; GFX11-NEXT:    v_add_co_ci_u32_e64 v5, null, 0, v5, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v2, vcc_lo, v2, 3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_co_ci_u32_e64 v3, null, 0, v3, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v0, vcc_lo, v0, 3
; GFX11-NEXT:    v_add_co_ci_u32_e64 v1, null, 0, v1, vcc_lo
; GFX11-NEXT:  .LBB64_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <4 x i64> %a, splat (i64 3)
  %a2 = bitcast <4 x i64> %a1 to <16 x bfloat>
  br label %end

cmp.false:
  %a3 = bitcast <4 x i64> %a to <16 x bfloat>
  br label %end

end:
  %phi = phi <16 x bfloat> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x bfloat> %phi
}

define inreg <16 x bfloat> @bitcast_v4i64_to_v16bf16_scalar(<4 x i64> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v4i64_to_v16bf16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB65_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s7, s23, 0xffff0000
; SI-NEXT:    s_lshl_b32 s6, s23, 16
; SI-NEXT:    s_and_b32 s9, s22, 0xffff0000
; SI-NEXT:    s_lshl_b32 s8, s22, 16
; SI-NEXT:    s_and_b32 s11, s21, 0xffff0000
; SI-NEXT:    s_lshl_b32 s10, s21, 16
; SI-NEXT:    s_and_b32 s13, s20, 0xffff0000
; SI-NEXT:    s_lshl_b32 s12, s20, 16
; SI-NEXT:    s_and_b32 s15, s19, 0xffff0000
; SI-NEXT:    s_lshl_b32 s14, s19, 16
; SI-NEXT:    s_and_b32 s25, s18, 0xffff0000
; SI-NEXT:    s_lshl_b32 s24, s18, 16
; SI-NEXT:    s_and_b32 s27, s17, 0xffff0000
; SI-NEXT:    s_lshl_b32 s26, s17, 16
; SI-NEXT:    s_and_b32 s29, s16, 0xffff0000
; SI-NEXT:    s_lshl_b32 s28, s16, 16
; SI-NEXT:    s_cbranch_execnz .LBB65_3
; SI-NEXT:  .LBB65_2: ; %cmp.true
; SI-NEXT:    s_add_u32 s4, s16, 3
; SI-NEXT:    s_addc_u32 s5, s17, 0
; SI-NEXT:    s_add_u32 s16, s18, 3
; SI-NEXT:    s_addc_u32 s14, s19, 0
; SI-NEXT:    s_add_u32 s12, s20, 3
; SI-NEXT:    s_addc_u32 s10, s21, 0
; SI-NEXT:    s_add_u32 s8, s22, 3
; SI-NEXT:    s_addc_u32 s6, s23, 0
; SI-NEXT:    s_and_b32 s7, s6, 0xffff0000
; SI-NEXT:    s_lshl_b32 s6, s6, 16
; SI-NEXT:    s_and_b32 s9, s8, 0xffff0000
; SI-NEXT:    s_lshl_b32 s8, s8, 16
; SI-NEXT:    s_and_b32 s11, s10, 0xffff0000
; SI-NEXT:    s_lshl_b32 s10, s10, 16
; SI-NEXT:    s_and_b32 s13, s12, 0xffff0000
; SI-NEXT:    s_lshl_b32 s12, s12, 16
; SI-NEXT:    s_and_b32 s15, s14, 0xffff0000
; SI-NEXT:    s_lshl_b32 s14, s14, 16
; SI-NEXT:    s_and_b32 s25, s16, 0xffff0000
; SI-NEXT:    s_lshl_b32 s24, s16, 16
; SI-NEXT:    s_and_b32 s27, s5, 0xffff0000
; SI-NEXT:    s_lshl_b32 s26, s5, 16
; SI-NEXT:    s_and_b32 s29, s4, 0xffff0000
; SI-NEXT:    s_lshl_b32 s28, s4, 16
; SI-NEXT:  .LBB65_3: ; %end
; SI-NEXT:    v_mul_f32_e64 v0, 1.0, s29
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v0
; SI-NEXT:    v_mul_f32_e64 v0, 1.0, s28
; SI-NEXT:    v_lshr_b64 v[0:1], v[0:1], 16
; SI-NEXT:    v_mul_f32_e64 v1, 1.0, s27
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v1
; SI-NEXT:    v_mul_f32_e64 v1, 1.0, s26
; SI-NEXT:    v_lshr_b64 v[1:2], v[1:2], 16
; SI-NEXT:    v_mul_f32_e64 v2, 1.0, s25
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v2
; SI-NEXT:    v_mul_f32_e64 v2, 1.0, s24
; SI-NEXT:    v_lshr_b64 v[2:3], v[2:3], 16
; SI-NEXT:    v_mul_f32_e64 v3, 1.0, s15
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v3
; SI-NEXT:    v_mul_f32_e64 v3, 1.0, s14
; SI-NEXT:    v_lshr_b64 v[3:4], v[3:4], 16
; SI-NEXT:    v_mul_f32_e64 v4, 1.0, s13
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v4
; SI-NEXT:    v_mul_f32_e64 v4, 1.0, s12
; SI-NEXT:    v_lshr_b64 v[4:5], v[4:5], 16
; SI-NEXT:    v_mul_f32_e64 v5, 1.0, s11
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v5
; SI-NEXT:    v_mul_f32_e64 v5, 1.0, s10
; SI-NEXT:    v_lshr_b64 v[5:6], v[5:6], 16
; SI-NEXT:    v_mul_f32_e64 v6, 1.0, s9
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v6
; SI-NEXT:    v_mul_f32_e64 v6, 1.0, s8
; SI-NEXT:    v_lshr_b64 v[6:7], v[6:7], 16
; SI-NEXT:    v_mul_f32_e64 v7, 1.0, s7
; SI-NEXT:    v_lshrrev_b32_e32 v8, 16, v7
; SI-NEXT:    v_mul_f32_e64 v7, 1.0, s6
; SI-NEXT:    v_lshr_b64 v[7:8], v[7:8], 16
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB65_4:
; SI-NEXT:    ; implicit-def: $sgpr28
; SI-NEXT:    ; implicit-def: $sgpr29
; SI-NEXT:    ; implicit-def: $sgpr26
; SI-NEXT:    ; implicit-def: $sgpr27
; SI-NEXT:    ; implicit-def: $sgpr24
; SI-NEXT:    ; implicit-def: $sgpr25
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr15
; SI-NEXT:    ; implicit-def: $sgpr12
; SI-NEXT:    ; implicit-def: $sgpr13
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr11
; SI-NEXT:    ; implicit-def: $sgpr8
; SI-NEXT:    ; implicit-def: $sgpr9
; SI-NEXT:    ; implicit-def: $sgpr6
; SI-NEXT:    ; implicit-def: $sgpr7
; SI-NEXT:    s_branch .LBB65_2
;
; VI-LABEL: bitcast_v4i64_to_v16bf16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB65_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB65_3
; VI-NEXT:  .LBB65_2: ; %cmp.true
; VI-NEXT:    s_add_u32 s22, s22, 3
; VI-NEXT:    s_addc_u32 s23, s23, 0
; VI-NEXT:    s_add_u32 s20, s20, 3
; VI-NEXT:    s_addc_u32 s21, s21, 0
; VI-NEXT:    s_add_u32 s18, s18, 3
; VI-NEXT:    s_addc_u32 s19, s19, 0
; VI-NEXT:    s_add_u32 s16, s16, 3
; VI-NEXT:    s_addc_u32 s17, s17, 0
; VI-NEXT:  .LBB65_3: ; %end
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB65_4:
; VI-NEXT:    s_branch .LBB65_2
;
; GFX9-LABEL: bitcast_v4i64_to_v16bf16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB65_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB65_3
; GFX9-NEXT:  .LBB65_2: ; %cmp.true
; GFX9-NEXT:    s_add_u32 s22, s22, 3
; GFX9-NEXT:    s_addc_u32 s23, s23, 0
; GFX9-NEXT:    s_add_u32 s20, s20, 3
; GFX9-NEXT:    s_addc_u32 s21, s21, 0
; GFX9-NEXT:    s_add_u32 s18, s18, 3
; GFX9-NEXT:    s_addc_u32 s19, s19, 0
; GFX9-NEXT:    s_add_u32 s16, s16, 3
; GFX9-NEXT:    s_addc_u32 s17, s17, 0
; GFX9-NEXT:  .LBB65_3: ; %end
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB65_4:
; GFX9-NEXT:    s_branch .LBB65_2
;
; GFX11-LABEL: bitcast_v4i64_to_v16bf16_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s4, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB65_4
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s4
; GFX11-NEXT:    s_cbranch_vccnz .LBB65_3
; GFX11-NEXT:  .LBB65_2: ; %cmp.true
; GFX11-NEXT:    s_add_u32 s18, s18, 3
; GFX11-NEXT:    s_addc_u32 s19, s19, 0
; GFX11-NEXT:    s_add_u32 s16, s16, 3
; GFX11-NEXT:    s_addc_u32 s17, s17, 0
; GFX11-NEXT:    s_add_u32 s2, s2, 3
; GFX11-NEXT:    s_addc_u32 s3, s3, 0
; GFX11-NEXT:    s_add_u32 s0, s0, 3
; GFX11-NEXT:    s_addc_u32 s1, s1, 0
; GFX11-NEXT:  .LBB65_3: ; %end
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s16 :: v_dual_mov_b32 v5, s17
; GFX11-NEXT:    v_dual_mov_b32 v6, s18 :: v_dual_mov_b32 v7, s19
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB65_4:
; GFX11-NEXT:    s_branch .LBB65_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <4 x i64> %a, splat (i64 3)
  %a2 = bitcast <4 x i64> %a1 to <16 x bfloat>
  br label %end

cmp.false:
  %a3 = bitcast <4 x i64> %a to <16 x bfloat>
  br label %end

end:
  %phi = phi <16 x bfloat> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x bfloat> %phi
}

define <4 x i64> @bitcast_v16bf16_to_v4i64(<16 x bfloat> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v16bf16_to_v4i64:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_and_b32_e32 v9, 0xffff0000, v7
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_and_b32_e32 v10, 0xffff0000, v6
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_and_b32_e32 v11, 0xffff0000, v5
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v12, 0xffff0000, v4
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_and_b32_e32 v13, 0xffff0000, v3
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v14, 0xffff0000, v2
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_and_b32_e32 v15, 0xffff0000, v1
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_and_b32_e32 v16, 0xffff0000, v0
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    v_mul_f32_e32 v22, 1.0, v16
; SI-NEXT:    v_mul_f32_e32 v23, 1.0, v0
; SI-NEXT:    v_mul_f32_e32 v20, 1.0, v15
; SI-NEXT:    v_mul_f32_e32 v21, 1.0, v1
; SI-NEXT:    v_mul_f32_e32 v18, 1.0, v14
; SI-NEXT:    v_mul_f32_e32 v19, 1.0, v2
; SI-NEXT:    v_mul_f32_e32 v16, 1.0, v13
; SI-NEXT:    v_mul_f32_e32 v17, 1.0, v3
; SI-NEXT:    v_mul_f32_e32 v14, 1.0, v12
; SI-NEXT:    v_mul_f32_e32 v15, 1.0, v4
; SI-NEXT:    v_mul_f32_e32 v12, 1.0, v11
; SI-NEXT:    v_mul_f32_e32 v13, 1.0, v5
; SI-NEXT:    v_mul_f32_e32 v10, 1.0, v10
; SI-NEXT:    v_mul_f32_e32 v11, 1.0, v6
; SI-NEXT:    v_mul_f32_e32 v8, 1.0, v9
; SI-NEXT:    v_mul_f32_e32 v9, 1.0, v7
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB66_3
; SI-NEXT:  ; %bb.1: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB66_4
; SI-NEXT:  .LBB66_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB66_3: ; %cmp.false
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v22
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v20
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v18
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v16
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v14
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v12
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v10
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v8
; SI-NEXT:    v_alignbit_b32 v0, v0, v23, 16
; SI-NEXT:    v_alignbit_b32 v1, v1, v21, 16
; SI-NEXT:    v_alignbit_b32 v2, v2, v19, 16
; SI-NEXT:    v_alignbit_b32 v3, v3, v17, 16
; SI-NEXT:    v_alignbit_b32 v4, v4, v15, 16
; SI-NEXT:    v_alignbit_b32 v5, v5, v13, 16
; SI-NEXT:    v_alignbit_b32 v6, v6, v11, 16
; SI-NEXT:    v_alignbit_b32 v7, v7, v9, 16
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB66_2
; SI-NEXT:  .LBB66_4: ; %cmp.true
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v22
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v20
; SI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v23
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v21
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_alignbit_b32 v0, v1, v0, 16
; SI-NEXT:    v_alignbit_b32 v1, v3, v2, 16
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v18
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v19
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v16
; SI-NEXT:    v_alignbit_b32 v2, v3, v2, 16
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v17
; SI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v14
; SI-NEXT:    v_alignbit_b32 v3, v4, v3, 16
; SI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v15
; SI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; SI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v12
; SI-NEXT:    v_alignbit_b32 v4, v5, v4, 16
; SI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v13
; SI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; SI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v10
; SI-NEXT:    v_alignbit_b32 v5, v6, v5, 16
; SI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v11
; SI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; SI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_and_b32_e32 v8, 0xffff0000, v8
; SI-NEXT:    v_alignbit_b32 v6, v7, v6, 16
; SI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v9
; SI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; SI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; SI-NEXT:    v_lshrrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_alignbit_b32 v7, v8, v7, 16
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16bf16_to_v4i64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB66_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v7
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, 0x7fff, v9
; VI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v7, 16, 1
; VI-NEXT:    s_movk_i32 s6, 0x7fff
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v7
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v7
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; VI-NEXT:    v_cndmask_b32_e32 v7, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; VI-NEXT:    v_alignbit_b32 v7, v7, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v6
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v6, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v6
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v6
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; VI-NEXT:    v_cndmask_b32_e32 v6, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_alignbit_b32 v6, v6, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v5
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v5, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v5
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v5
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; VI-NEXT:    v_cndmask_b32_e32 v5, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_alignbit_b32 v5, v5, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v4
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v4, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v4
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v4
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; VI-NEXT:    v_cndmask_b32_e32 v4, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_alignbit_b32 v4, v4, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v3
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v3
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_alignbit_b32 v3, v3, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v2
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v2
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_alignbit_b32 v2, v2, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v1
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v1, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v1
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v1
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; VI-NEXT:    v_cndmask_b32_e32 v1, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_alignbit_b32 v1, v1, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v0
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v0, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v0
; VI-NEXT:    v_add_u32_e32 v9, vcc, 0x7fff, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v0
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; VI-NEXT:    v_cndmask_b32_e32 v0, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; VI-NEXT:    v_alignbit_b32 v0, v0, v8, 16
; VI-NEXT:  .LBB66_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16bf16_to_v4i64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB66_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v7
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    s_movk_i32 s6, 0x7fff
; GFX9-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v7, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v7, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v7
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; GFX9-NEXT:    v_cndmask_b32_e32 v7, v9, v10, vcc
; GFX9-NEXT:    s_mov_b32 s7, 0x7060302
; GFX9-NEXT:    v_perm_b32 v7, v7, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v6
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v6, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v6, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v6
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; GFX9-NEXT:    v_cndmask_b32_e32 v6, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v6, v6, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v5
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v5, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v5, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v5, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v5, v5, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v4
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v4, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v4, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v4
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; GFX9-NEXT:    v_cndmask_b32_e32 v4, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v4, v4, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v3
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v3, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v3, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v3
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; GFX9-NEXT:    v_cndmask_b32_e32 v3, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v3, v3, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v2, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v2, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v2, v2, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v1
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v1, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v1, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v1, v1, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v0
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v0, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v0, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v0
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v0, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v0, v0, v8, s7
; GFX9-NEXT:  .LBB66_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v16bf16_to_v4i64:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v8
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
; GFX11-TRUE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v15, v7 :: v_dual_mov_b32 v14, v6
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v13, v5 :: v_dual_mov_b32 v12, v4
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v11, v3 :: v_dual_mov_b32 v10, v2
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v9, v1 :: v_dual_mov_b32 v8, v0
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr7
; GFX11-TRUE16-NEXT:  ; %bb.2: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB66_4
; GFX11-TRUE16-NEXT:  ; %bb.3: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v9, 0xffff0000, v6
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v8, 16, v7
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v10, 0xffff0000, v5
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v9, 0x40c00000, v9 :: v_dual_add_f32 v8, 0x40c00000, v8
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v15, v9, 16, 1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v11, v8, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v14, 0x400000, v8
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add3_u32 v11, v11, v8, 0x7fff
; GFX11-TRUE16-NEXT:    v_dual_cndmask_b32 v8, v11, v14 :: v_dual_and_b32 v7, 0xffff0000, v7
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v7, 0x40c00000, v7 :: v_dual_lshlrev_b32 v6, 16, v6
; GFX11-TRUE16-NEXT:    v_add3_u32 v11, v15, v9, 0x7fff
; GFX11-TRUE16-NEXT:    v_bfe_u32 v12, v7, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v13, 0x400000, v7
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add3_u32 v12, v12, v7, 0x7fff
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v6, 0x40c00000, v6 :: v_dual_cndmask_b32 v15, v12, v13
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v16, v6, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v17, 0x400000, v6
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v15.l, v8.h
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v9
; GFX11-TRUE16-NEXT:    v_add3_u32 v14, v16, v6, 0x7fff
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v6, v14, v17, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v7, 0x40c00000, v10
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v9, 0xffff0000, v4
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v14, v11, v8, vcc_lo
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v10, v7, 16, 1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v8, v5, 16, 1
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v14.l, v6.h
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v9, 0x40c00000, v9 :: v_dual_add_f32 v4, 0x40c00000, v4
; GFX11-TRUE16-NEXT:    v_add3_u32 v6, v10, v7, 0x7fff
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_add3_u32 v8, v8, v5, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v10, 0x400000, v5
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v11, 0x400000, v7
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v5, v8, v10, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-TRUE16-NEXT:    v_bfe_u32 v7, v4, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v4
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v10, 0x400000, v9
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v13, v6, v11, vcc_lo
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_add3_u32 v7, v7, v4, 0x7fff
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-TRUE16-NEXT:    v_bfe_u32 v6, v9, 16, 1
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v11, 0xffff0000, v2
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v4, v7, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v13.l, v5.h
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v5, 0xffff0000, v3
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_2) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v2, 0x40c00000, v2 :: v_dual_lshlrev_b32 v3, 16, v3
; GFX11-TRUE16-NEXT:    v_add3_u32 v6, v6, v9, 0x7fff
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v3, 0x40c00000, v3 :: v_dual_cndmask_b32 v12, v6, v10
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v6, 0x40c00000, v11
; GFX11-TRUE16-NEXT:    v_bfe_u32 v7, v5, 16, 1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v8, v3, 16, 1
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v12.l, v4.h
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v9, 0x400000, v5
; GFX11-TRUE16-NEXT:    v_add3_u32 v4, v7, v5, 0x7fff
; GFX11-TRUE16-NEXT:    v_add3_u32 v7, v8, v3, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v3
; GFX11-TRUE16-NEXT:    v_bfe_u32 v10, v6, 16, 1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v3, v7, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, 0x400000, v6
; GFX11-TRUE16-NEXT:    v_bfe_u32 v7, v2, 16, 1
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v11, v4, v9, vcc_lo
; GFX11-TRUE16-NEXT:    v_add3_u32 v4, v10, v6, 0x7fff
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v11.l, v3.h
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v3, 0xffff0000, v1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v3, 0x40c00000, v3 :: v_dual_lshlrev_b32 v6, 16, v0
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v10, v4, v5, vcc_lo
; GFX11-TRUE16-NEXT:    v_add3_u32 v4, v7, v2, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, 0x400000, v2
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v7, 0x400000, v3
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v2, v4, v5, vcc_lo
; GFX11-TRUE16-NEXT:    v_bfe_u32 v4, v3, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v5, 0x40c00000, v6
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v10.l, v2.h
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_4) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_add3_u32 v4, v4, v3, 0x7fff
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v6, v5, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v16, 0x400000, v5
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v0, 0x40c00000, v0 :: v_dual_add_f32 v1, 0x40c00000, v1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_add3_u32 v6, v6, v5, 0x7fff
; GFX11-TRUE16-NEXT:    v_bfe_u32 v9, v0, 16, 1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-TRUE16-NEXT:    v_add3_u32 v2, v2, v1, 0x7fff
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v2, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-TRUE16-NEXT:    v_add3_u32 v2, v9, v0, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v0
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v5, v6, v16, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v9, v4, v7, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v9.l, v1.h
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v8, v2, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v8.l, v5.h
; GFX11-TRUE16-NEXT:  .LBB66_4: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v0, v8 :: v_dual_mov_b32 v1, v9
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v2, v10 :: v_dual_mov_b32 v3, v11
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v4, v12 :: v_dual_mov_b32 v5, v13
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v6, v14 :: v_dual_mov_b32 v7, v15
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v16bf16_to_v4i64:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-FAKE16-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB66_2
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v9, 16, v6
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v8, 16, v7
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v9, 0x40c00000, v9 :: v_dual_add_f32 v8, 0x40c00000, v8
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v9, 16, 1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v10, v8, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, 0x400000, v8
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v15, v6, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-FAKE16-NEXT:    v_add3_u32 v13, v13, v9, 0x7fff
; GFX11-FAKE16-NEXT:    v_add3_u32 v10, v10, v8, 0x7fff
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v8, v10, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_add3_u32 v11, v15, v6, 0x7fff
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v10, 0x400000, v9
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GFX11-FAKE16-NEXT:    v_bfe_u32 v12, v7, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v14, 0x400000, v7
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_add3_u32 v12, v12, v7, 0x7fff
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v7, v12, v14 :: v_dual_lshlrev_b32 v12, 16, v5
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v7, v8, 0x7060302
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v14, 0x400000, v6
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v9, v13, v10 :: v_dual_add_f32 v10, 0x40c00000, v12
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v8, v5, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v13, 0x400000, v5
; GFX11-FAKE16-NEXT:    v_bfe_u32 v12, v10, 16, 1
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v6, v11, v14 :: v_dual_lshlrev_b32 v11, 16, v4
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-FAKE16-NEXT:    v_add3_u32 v8, v8, v5, 0x7fff
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v6, v9, 0x7060302
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v9, 0x40c00000, v11 :: v_dual_add_f32 v4, 0x40c00000, v4
; GFX11-FAKE16-NEXT:    v_add3_u32 v11, v12, v10, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, 0x400000, v10
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v14, v9, 16, 1
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v10, v11, v12, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, 0x400000, v9
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v12, 16, v3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v5, v8, v13, vcc_lo
; GFX11-FAKE16-NEXT:    v_add3_u32 v8, v14, v9, 0x7fff
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v9, 0x40c00000, v12 :: v_dual_lshlrev_b32 v12, 16, v2
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v5, v10, 0x7060302
; GFX11-FAKE16-NEXT:    v_bfe_u32 v10, v4, 16, 1
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v8, v8, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, 0x400000, v4
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v9, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-FAKE16-NEXT:    v_add3_u32 v10, v10, v4, 0x7fff
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v4, v10, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v10, 0x40c00000, v12
; GFX11-FAKE16-NEXT:    v_add3_u32 v11, v13, v9, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, 0x400000, v9
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v3, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-FAKE16-NEXT:    v_bfe_u32 v14, v10, 16, 1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v9, v11, v12, vcc_lo
; GFX11-FAKE16-NEXT:    v_add3_u32 v11, v13, v3, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, 0x400000, v3
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; GFX11-FAKE16-NEXT:    v_add3_u32 v13, v14, v10, 0x7fff
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v14, 16, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v3, v11, v12 :: v_dual_add_f32 v2, 0x40c00000, v2
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v4, v8, 0x7060302
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v11, 0x40c00000, v14
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v15, 0x400000, v10
; GFX11-FAKE16-NEXT:    v_bfe_u32 v16, v2, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-FAKE16-NEXT:    v_bfe_u32 v14, v11, 16, 1
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v3, v9, 0x7060302
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_add3_u32 v12, v16, v2, 0x7fff
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v10, v13, v15 :: v_dual_lshlrev_b32 v15, 16, v0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v13, 0x400000, v2
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v2, v12, v13, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v12, 0x40c00000, v15
; GFX11-FAKE16-NEXT:    v_add3_u32 v13, v14, v11, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v14, 0x400000, v11
; GFX11-FAKE16-NEXT:    v_bfe_u32 v15, v1, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v11, v11
; GFX11-FAKE16-NEXT:    v_bfe_u32 v16, v12, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v17, 0x400000, v12
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v2, v10, 0x7060302
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v11, v13, v14, vcc_lo
; GFX11-FAKE16-NEXT:    v_add3_u32 v14, v15, v1, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v15, 0x400000, v1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX11-FAKE16-NEXT:    v_add3_u32 v16, v16, v12, 0x7fff
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v1, v14, v15 :: v_dual_add_f32 v0, 0x40c00000, v0
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v12, v12
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v1, v11, 0x7060302
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_3) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v0, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v18, 0x400000, v0
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v12, v16, v17, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-FAKE16-NEXT:    v_add3_u32 v13, v13, v0, 0x7fff
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v0, v13, v18, vcc_lo
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v0, v12, 0x7060302
; GFX11-FAKE16-NEXT:  .LBB66_2: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x bfloat> %a, splat (bfloat 0xR40C0)
  %a2 = bitcast <16 x bfloat> %a1 to <4 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <16 x bfloat> %a to <4 x i64>
  br label %end

end:
  %phi = phi <4 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x i64> %phi
}

define inreg <4 x i64> @bitcast_v16bf16_to_v4i64_scalar(<16 x bfloat> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v16bf16_to_v4i64_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_and_b32 s4, s23, 0xffff0000
; SI-NEXT:    s_lshl_b32 s5, s23, 16
; SI-NEXT:    s_and_b32 s6, s22, 0xffff0000
; SI-NEXT:    s_lshl_b32 s7, s22, 16
; SI-NEXT:    s_and_b32 s8, s21, 0xffff0000
; SI-NEXT:    s_lshl_b32 s9, s21, 16
; SI-NEXT:    s_and_b32 s10, s20, 0xffff0000
; SI-NEXT:    s_lshl_b32 s11, s20, 16
; SI-NEXT:    s_and_b32 s12, s19, 0xffff0000
; SI-NEXT:    s_lshl_b32 s13, s19, 16
; SI-NEXT:    s_and_b32 s14, s18, 0xffff0000
; SI-NEXT:    s_lshl_b32 s15, s18, 16
; SI-NEXT:    s_and_b32 s18, s17, 0xffff0000
; SI-NEXT:    s_lshl_b32 s17, s17, 16
; SI-NEXT:    s_and_b32 s19, s16, 0xffff0000
; SI-NEXT:    s_lshl_b32 s16, s16, 16
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    v_mul_f32_e64 v32, 1.0, s19
; SI-NEXT:    v_mul_f32_e64 v23, 1.0, s16
; SI-NEXT:    v_mul_f32_e64 v31, 1.0, s18
; SI-NEXT:    v_mul_f32_e64 v21, 1.0, s17
; SI-NEXT:    v_mul_f32_e64 v30, 1.0, s14
; SI-NEXT:    v_mul_f32_e64 v19, 1.0, s15
; SI-NEXT:    v_mul_f32_e64 v29, 1.0, s12
; SI-NEXT:    v_mul_f32_e64 v17, 1.0, s13
; SI-NEXT:    v_mul_f32_e64 v28, 1.0, s10
; SI-NEXT:    v_mul_f32_e64 v15, 1.0, s11
; SI-NEXT:    v_mul_f32_e64 v27, 1.0, s8
; SI-NEXT:    v_mul_f32_e64 v13, 1.0, s9
; SI-NEXT:    v_mul_f32_e64 v26, 1.0, s6
; SI-NEXT:    v_mul_f32_e64 v25, 1.0, s4
; SI-NEXT:    v_mul_f32_e64 v11, 1.0, s7
; SI-NEXT:    v_mul_f32_e64 v9, 1.0, s5
; SI-NEXT:    s_cbranch_scc0 .LBB67_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_lshrrev_b32_e32 v24, 16, v32
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v31
; SI-NEXT:    v_lshr_b64 v[0:1], v[23:24], 16
; SI-NEXT:    v_lshr_b64 v[1:2], v[21:22], 16
; SI-NEXT:    v_lshrrev_b32_e32 v20, 16, v30
; SI-NEXT:    v_lshr_b64 v[2:3], v[19:20], 16
; SI-NEXT:    v_lshrrev_b32_e32 v18, 16, v29
; SI-NEXT:    v_lshr_b64 v[3:4], v[17:18], 16
; SI-NEXT:    v_lshrrev_b32_e32 v16, 16, v28
; SI-NEXT:    v_lshr_b64 v[4:5], v[15:16], 16
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v27
; SI-NEXT:    v_lshr_b64 v[5:6], v[13:14], 16
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v26
; SI-NEXT:    v_lshr_b64 v[6:7], v[11:12], 16
; SI-NEXT:    v_lshrrev_b32_e32 v10, 16, v25
; SI-NEXT:    v_lshr_b64 v[7:8], v[9:10], 16
; SI-NEXT:    s_cbranch_execnz .LBB67_3
; SI-NEXT:  .LBB67_2: ; %cmp.true
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v32
; SI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v23
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v31
; SI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v21
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_lshr_b64 v[0:1], v[0:1], 16
; SI-NEXT:    v_lshr_b64 v[1:2], v[2:3], 16
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v30
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v19
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_lshr_b64 v[2:3], v[2:3], 16
; SI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v29
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v17
; SI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_lshr_b64 v[3:4], v[3:4], 16
; SI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v28
; SI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v15
; SI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; SI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_lshr_b64 v[4:5], v[4:5], 16
; SI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v27
; SI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v13
; SI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; SI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_lshr_b64 v[5:6], v[5:6], 16
; SI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v26
; SI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v11
; SI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; SI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_lshr_b64 v[6:7], v[6:7], 16
; SI-NEXT:    v_and_b32_e32 v8, 0xffff0000, v25
; SI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v9
; SI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; SI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; SI-NEXT:    v_lshrrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_lshr_b64 v[7:8], v[7:8], 16
; SI-NEXT:  .LBB67_3: ; %end
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB67_4:
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; SI-NEXT:    s_branch .LBB67_2
;
; VI-LABEL: bitcast_v16bf16_to_v4i64_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB67_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB67_4
; VI-NEXT:  .LBB67_2: ; %cmp.true
; VI-NEXT:    s_lshl_b32 s4, s23, 16
; VI-NEXT:    v_mov_b32_e32 v8, 0x40c00000
; VI-NEXT:    v_add_f32_e32 v0, s4, v8
; VI-NEXT:    v_bfe_u32 v1, v0, 16, 1
; VI-NEXT:    v_add_u32_e32 v1, vcc, v1, v0
; VI-NEXT:    v_add_u32_e32 v1, vcc, 0x7fff, v1
; VI-NEXT:    v_or_b32_e32 v2, 0x400000, v0
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; VI-NEXT:    s_and_b32 s4, s23, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v0, v1, v2, vcc
; VI-NEXT:    v_add_f32_e32 v1, s4, v8
; VI-NEXT:    v_bfe_u32 v2, v1, 16, 1
; VI-NEXT:    v_add_u32_e32 v2, vcc, v2, v1
; VI-NEXT:    v_add_u32_e32 v2, vcc, 0x7fff, v2
; VI-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; VI-NEXT:    s_lshl_b32 s4, s22, 16
; VI-NEXT:    v_cndmask_b32_e32 v1, v2, v3, vcc
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    s_and_b32 s4, s22, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; VI-NEXT:    v_add_f32_e32 v3, s4, v8
; VI-NEXT:    v_bfe_u32 v4, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v4, vcc, v4, v3
; VI-NEXT:    v_add_u32_e32 v4, vcc, 0x7fff, v4
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v4, v5, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    s_lshl_b32 s4, s21, 16
; VI-NEXT:    v_lshrrev_b64 v[6:7], 16, v[2:3]
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    s_and_b32 s4, s21, 0xffff0000
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_cndmask_b32_e32 v9, v3, v4, vcc
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; VI-NEXT:    s_lshl_b32 s4, s20, 16
; VI-NEXT:    v_lshrrev_b32_e32 v10, 16, v2
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    s_and_b32 s4, s20, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; VI-NEXT:    v_add_f32_e32 v3, s4, v8
; VI-NEXT:    v_bfe_u32 v4, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v4, vcc, v4, v3
; VI-NEXT:    v_add_u32_e32 v4, vcc, 0x7fff, v4
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v4, v5, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    s_lshl_b32 s4, s19, 16
; VI-NEXT:    v_lshrrev_b64 v[4:5], 16, v[2:3]
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    s_and_b32 s4, s19, 0xffff0000
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_cndmask_b32_e32 v11, v3, v5, vcc
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v5, vcc
; VI-NEXT:    s_lshl_b32 s4, s18, 16
; VI-NEXT:    v_lshrrev_b32_e32 v12, 16, v2
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    s_and_b32 s4, s18, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v5, vcc
; VI-NEXT:    v_add_f32_e32 v3, s4, v8
; VI-NEXT:    v_bfe_u32 v5, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v3
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    v_or_b32_e32 v7, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v5, v7, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_lshrrev_b64 v[2:3], 16, v[2:3]
; VI-NEXT:    s_lshl_b32 s4, s17, 16
; VI-NEXT:    v_add_f32_e32 v3, s4, v8
; VI-NEXT:    v_bfe_u32 v5, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v3
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    s_and_b32 s4, s17, 0xffff0000
; VI-NEXT:    v_or_b32_e32 v7, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_add_f32_e32 v3, s4, v8
; VI-NEXT:    v_cndmask_b32_e32 v13, v5, v7, vcc
; VI-NEXT:    v_bfe_u32 v5, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v3
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    v_or_b32_e32 v7, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v5, v7, vcc
; VI-NEXT:    s_lshl_b32 s4, s16, 16
; VI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; VI-NEXT:    v_add_f32_e32 v3, s4, v8
; VI-NEXT:    v_bfe_u32 v5, v3, 16, 1
; VI-NEXT:    s_and_b32 s6, s16, 0xffff0000
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v3
; VI-NEXT:    v_or_b32_e32 v15, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e64 s[4:5], v3, v3
; VI-NEXT:    v_add_f32_e32 v3, s6, v8
; VI-NEXT:    v_bfe_u32 v7, v3, 16, 1
; VI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_add_u32_e32 v7, vcc, v7, v3
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    v_add_u32_e32 v16, vcc, 0x7fff, v7
; VI-NEXT:    v_lshrrev_b64 v[7:8], 16, v[0:1]
; VI-NEXT:    v_or_b32_e32 v17, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_lshrrev_b64 v[8:9], 16, v[9:10]
; VI-NEXT:    v_lshrrev_b64 v[9:10], 16, v[11:12]
; VI-NEXT:    v_cndmask_b32_e32 v1, v16, v17, vcc
; VI-NEXT:    v_lshrrev_b64 v[10:11], 16, v[13:14]
; VI-NEXT:    v_cndmask_b32_e64 v0, v5, v15, s[4:5]
; VI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_lshrrev_b64 v[0:1], 16, v[0:1]
; VI-NEXT:    v_mov_b32_e32 v1, v10
; VI-NEXT:    v_mov_b32_e32 v3, v9
; VI-NEXT:    v_mov_b32_e32 v5, v8
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB67_3:
; VI-NEXT:    s_branch .LBB67_2
; VI-NEXT:  .LBB67_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16bf16_to_v4i64_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB67_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB67_4
; GFX9-NEXT:  .LBB67_2: ; %cmp.true
; GFX9-NEXT:    s_and_b32 s4, s23, 0xffff0000
; GFX9-NEXT:    v_mov_b32_e32 v0, 0x40c00000
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v1
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s23, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v2, v3, vcc
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v0
; GFX9-NEXT:    v_bfe_u32 v3, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v3, v3, v2
; GFX9-NEXT:    v_add_u32_e32 v3, 0x7fff, v3
; GFX9-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; GFX9-NEXT:    v_mov_b32_e32 v8, 0xffff
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v2, v8, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s22, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v7, v1, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v1
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s22, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v2, v3, vcc
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v0
; GFX9-NEXT:    v_bfe_u32 v3, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v3, v3, v2
; GFX9-NEXT:    v_add_u32_e32 v3, 0x7fff, v3
; GFX9-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v2, v8, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s21, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v6, v1, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v1
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s21, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v2, v3, vcc
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v0
; GFX9-NEXT:    v_bfe_u32 v3, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v3, v3, v2
; GFX9-NEXT:    v_add_u32_e32 v3, 0x7fff, v3
; GFX9-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v2, v8, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s20, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v5, v1, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v1
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s20, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v2, v3, vcc
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v0
; GFX9-NEXT:    v_bfe_u32 v3, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v3, v3, v2
; GFX9-NEXT:    v_add_u32_e32 v3, 0x7fff, v3
; GFX9-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v2, v8, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s19, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v4, v1, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v1
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s19, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v2, v3, vcc
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v0
; GFX9-NEXT:    v_bfe_u32 v3, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v3, v3, v2
; GFX9-NEXT:    v_add_u32_e32 v3, 0x7fff, v3
; GFX9-NEXT:    v_or_b32_e32 v9, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v3, v9, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v2, v8, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s18, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v3, v1, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v1
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v9, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s18, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v2, v9, vcc
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v0
; GFX9-NEXT:    v_bfe_u32 v9, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v9, v9, v2
; GFX9-NEXT:    v_add_u32_e32 v9, 0x7fff, v9
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v9, v10, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v2, v8, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s17, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v2, v1, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v9, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v9, v9, v1
; GFX9-NEXT:    v_add_u32_e32 v9, 0x7fff, v9
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s17, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v9, v10, vcc
; GFX9-NEXT:    v_add_f32_e32 v9, s4, v0
; GFX9-NEXT:    v_bfe_u32 v10, v9, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v10, v10, v9
; GFX9-NEXT:    v_add_u32_e32 v10, 0x7fff, v10
; GFX9-NEXT:    v_or_b32_e32 v11, 0x400000, v9
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v9, v9
; GFX9-NEXT:    v_cndmask_b32_e32 v9, v10, v11, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v9, v8, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s16, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v1, v1, 16, v9
; GFX9-NEXT:    v_add_f32_e32 v9, s4, v0
; GFX9-NEXT:    v_bfe_u32 v10, v9, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v10, v10, v9
; GFX9-NEXT:    s_lshl_b32 s4, s16, 16
; GFX9-NEXT:    v_add_u32_e32 v10, 0x7fff, v10
; GFX9-NEXT:    v_or_b32_e32 v11, 0x400000, v9
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v9, v9
; GFX9-NEXT:    v_add_f32_e32 v0, s4, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v9, v10, v11, vcc
; GFX9-NEXT:    v_bfe_u32 v10, v0, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v10, v10, v0
; GFX9-NEXT:    v_add_u32_e32 v10, 0x7fff, v10
; GFX9-NEXT:    v_or_b32_e32 v11, 0x400000, v0
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v0, v10, v11, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v9, 16, v9
; GFX9-NEXT:    v_and_b32_sdwa v0, v8, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    v_lshl_or_b32 v0, v9, 16, v0
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB67_3:
; GFX9-NEXT:    s_branch .LBB67_2
; GFX9-NEXT:  .LBB67_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v16bf16_to_v4i64_scalar:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_mov_b32 s7, s19
; GFX11-TRUE16-NEXT:    s_mov_b32 s6, s18
; GFX11-TRUE16-NEXT:    s_mov_b32 s5, s17
; GFX11-TRUE16-NEXT:    s_mov_b32 s4, s16
; GFX11-TRUE16-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-TRUE16-NEXT:    s_mov_b32 s8, 0
; GFX11-TRUE16-NEXT:    s_cbranch_scc0 .LBB67_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-TRUE16-NEXT:    s_cbranch_vccnz .LBB67_4
; GFX11-TRUE16-NEXT:  .LBB67_2: ; %cmp.true
; GFX11-TRUE16-NEXT:    s_and_b32 s8, s7, 0xffff0000
; GFX11-TRUE16-NEXT:    s_lshl_b32 s7, s7, 16
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v0, 0x40c00000, s8
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v1, 0x40c00000, s7
; GFX11-TRUE16-NEXT:    s_and_b32 s7, s6, 0xffff0000
; GFX11-TRUE16-NEXT:    s_lshl_b32 s6, s6, 16
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v4, 0x40c00000, s7
; GFX11-TRUE16-NEXT:    v_bfe_u32 v2, v0, 16, 1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v3, v1, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v5, 0x40c00000, s6
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v6, 0x400000, v0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v7, v4, 16, 1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, v2, v0
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v9, v5, 16, 1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v7, v7, v4
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v2
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, v3, v1
; GFX11-TRUE16-NEXT:    s_and_b32 s6, s5, 0xffff0000
; GFX11-TRUE16-NEXT:    s_lshl_b32 s5, s5, 16
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_dual_cndmask_b32 v0, v2, v6 :: v_dual_add_nc_u32 v3, 0x7fff, v3
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, 0x7fff, v7
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v3, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v3, 0x400000, v4
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, v9, v5
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v8, 0x40c00000, s5
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v7, 16, v1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v9, 0x400000, v5
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v3, v6, v3, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, 0x7fff, v2
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v2, 0x40c00000, s6
; GFX11-TRUE16-NEXT:    v_bfe_u32 v6, v8, 16, 1
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v7.h, v0.l
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v1, v9, vcc_lo
; GFX11-TRUE16-NEXT:    v_bfe_u32 v4, v2, 16, 1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v0, v6, v8
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-TRUE16-NEXT:    s_and_b32 s5, s4, 0xffff0000
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v6, 16, v1
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v6.h, v3.l
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v3, 0x400000, v2
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v4, v4, v2
; GFX11-TRUE16-NEXT:    s_lshl_b32 s4, s4, 16
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v0, 0x7fff, v0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v9, 0x40c00000, s4
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, 0x400000, v8
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, 0x7fff, v4
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v4, 0x40c00000, s5
; GFX11-TRUE16-NEXT:    s_and_b32 s4, s3, 0xffff0000
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v10, 0x400000, v9
; GFX11-TRUE16-NEXT:    s_lshl_b32 s3, s3, 16
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v1, v3, vcc_lo
; GFX11-TRUE16-NEXT:    v_bfe_u32 v2, v4, 16, 1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-TRUE16-NEXT:    v_bfe_u32 v3, v9, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v4
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, v2, v4
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v0, v0, v5, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, v3, v9
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v2
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v5, 16, v0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v0, 0x40c00000, s4
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v3
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v5.h, v1.l
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v2, v2, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-TRUE16-NEXT:    v_bfe_u32 v11, v0, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v1, 0x40c00000, s3
; GFX11-TRUE16-NEXT:    s_and_b32 s3, s2, 0xffff0000
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v3, v3, v10, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v8, v11, v0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v9, v1, 16, 1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-TRUE16-NEXT:    s_lshl_b32 s2, s2, 16
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v4, 16, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v8
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v0
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v4.h, v2.l
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v2, 0x40c00000, s3
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v10, 0x400000, v1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_dual_cndmask_b32 v0, v3, v8 :: v_dual_add_nc_u32 v3, v9, v1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v8, v2, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v9, 0x40c00000, s2
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-TRUE16-NEXT:    s_and_b32 s2, s1, 0xffff0000
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v8, v8, v2
; GFX11-TRUE16-NEXT:    v_bfe_u32 v11, v9, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v12, 0x400000, v2
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v3, v10, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v10, 0x40c00000, s2
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v8, 0x7fff, v8
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v11, v11, v9
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v3, 16, v1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v1, v10, 16, 1
; GFX11-TRUE16-NEXT:    s_lshl_b32 s1, s1, 16
; GFX11-TRUE16-NEXT:    s_and_b32 s2, s0, 0xffff0000
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v2, v8, v12, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v8, 0x7fff, v11
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v11, 0x400000, v9
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, v1, v10
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v3.h, v0.l
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v2
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v9, 0x40c00000, s2
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v2, v8, v11, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v8, 0x40c00000, s1
; GFX11-TRUE16-NEXT:    s_lshl_b32 s0, s0, 16
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, 0x7fff, v1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v11, 0x400000, v10
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v12, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v13, v8, 16, 1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v14, v9, 16, 1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v15, 0x400000, v8
; GFX11-TRUE16-NEXT:    v_bfe_u32 v10, v12, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v16, 0x400000, v12
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v1, v11, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v11, v13, v8
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v13, v14, v9
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.h, v0.l
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v14, 16, v1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, v10, v12
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v10, 0x7fff, v11
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v11, 0x7fff, v13
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v13, 0x400000, v9
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, 0x7fff, v1
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v9, v11, v13, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_3) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v9, 16, v9
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v8, v10, v15, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v12, v12
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v10, v1, v16, vcc_lo
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v1, 16, v8
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v1.h, v14.l
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v10
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.h, v9.l
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB67_3:
; GFX11-TRUE16-NEXT:    s_branch .LBB67_2
; GFX11-TRUE16-NEXT:  .LBB67_4:
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v16bf16_to_v4i64_scalar:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    s_mov_b32 s7, s19
; GFX11-FAKE16-NEXT:    s_mov_b32 s6, s18
; GFX11-FAKE16-NEXT:    s_mov_b32 s5, s17
; GFX11-FAKE16-NEXT:    s_mov_b32 s4, s16
; GFX11-FAKE16-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-FAKE16-NEXT:    s_mov_b32 s8, 0
; GFX11-FAKE16-NEXT:    s_cbranch_scc0 .LBB67_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-FAKE16-NEXT:    s_cbranch_vccnz .LBB67_4
; GFX11-FAKE16-NEXT:  .LBB67_2: ; %cmp.true
; GFX11-FAKE16-NEXT:    s_lshl_b32 s8, s7, 16
; GFX11-FAKE16-NEXT:    s_and_b32 s7, s7, 0xffff0000
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v0, 0x40c00000, s8
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v1, 0x40c00000, s7
; GFX11-FAKE16-NEXT:    s_and_b32 s8, s6, 0xffff0000
; GFX11-FAKE16-NEXT:    s_lshl_b32 s6, s6, 16
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v3, 0x40c00000, s8
; GFX11-FAKE16-NEXT:    v_bfe_u32 v2, v0, 16, 1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v4, v1, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v9, 0x400000, v1
; GFX11-FAKE16-NEXT:    s_and_b32 s7, s5, 0xffff0000
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v5, 0x40c00000, s6
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v6, 0x40c00000, s7
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, v4, v1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v8, 0x400000, v0
; GFX11-FAKE16-NEXT:    v_bfe_u32 v10, v3, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-FAKE16-NEXT:    s_lshl_b32 s5, s5, 16
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, 0x7fff, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, v2, v0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v7, 0x40c00000, s5
; GFX11-FAKE16-NEXT:    v_bfe_u32 v11, v6, 16, 1
; GFX11-FAKE16-NEXT:    s_and_b32 s5, s4, 0xffff0000
; GFX11-FAKE16-NEXT:    s_lshl_b32 s4, s4, 16
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v2
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_4) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v0, v2, v8, vcc_lo
; GFX11-FAKE16-NEXT:    v_bfe_u32 v2, v5, 16, 1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v8, v10, v3
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v10, 0x400000, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, v2, v5
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v1, v4, v9 :: v_dual_add_nc_u32 v8, 0x7fff, v8
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, 0x400000, v3
; GFX11-FAKE16-NEXT:    v_bfe_u32 v9, v7, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v3, v8, v4 :: v_dual_add_nc_u32 v4, v9, v7
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v5, v11, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v8, 0x400000, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, 0x7fff, v4
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v2, v2, v10 :: v_dual_add_nc_u32 v5, 0x7fff, v5
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v9, 0x400000, v6
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v10, 0x40c00000, s4
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v4, v4, v8, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v8, 0x40c00000, s5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v7, v1, 16, v0
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v5, v5, v9, vcc_lo
; GFX11-FAKE16-NEXT:    v_bfe_u32 v9, v10, 16, 1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v6, v8, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-FAKE16-NEXT:    s_and_b32 s4, s3, 0xffff0000
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v0, v9, v10
; GFX11-FAKE16-NEXT:    s_lshl_b32 s3, s3, 16
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v9, 0x40c00000, s3
; GFX11-FAKE16-NEXT:    s_and_b32 s3, s2, 0xffff0000
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v0, 0x7fff, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v11, v6, v8
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v6, v3, 16, v2
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, 0x400000, v10
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, 0x400000, v8
; GFX11-FAKE16-NEXT:    s_lshl_b32 s2, s2, 16
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, 0x400000, v9
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v0, v0, v3, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v1, 0x7fff, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v8, 0x40c00000, s3
; GFX11-FAKE16-NEXT:    v_bfe_u32 v3, v9, 16, 1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v1, v1, v2 :: v_dual_and_b32 v4, 0xffff, v4
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v10, v8, 16, 1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v5, v5, 16, v4
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v4, 0x40c00000, s4
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v10, v10, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v2, v4, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, 0x400000, v4
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, v2, v4
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v4, 0x40c00000, s2
; GFX11-FAKE16-NEXT:    s_and_b32 s2, s1, 0xffff0000
; GFX11-FAKE16-NEXT:    s_lshl_b32 s1, s1, 16
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, v3, v9
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v13, 0x40c00000, s1
; GFX11-FAKE16-NEXT:    s_lshl_b32 s1, s0, 16
; GFX11-FAKE16-NEXT:    s_and_b32 s0, s0, 0xffff0000
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v2, v2, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v9, 0x7fff, v10
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v3
; GFX11-FAKE16-NEXT:    v_bfe_u32 v11, v4, 16, 1
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v14, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v18, 0x400000, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v3, v3, v12, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-FAKE16-NEXT:    v_bfe_u32 v16, v14, 16, 1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v8, v9, v10 :: v_dual_add_nc_u32 v9, v11, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, 0x400000, v4
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v10, 0x40c00000, s2
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v16, v16, v14
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v9, 0x7fff, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v8, 16, v8
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v12, v10, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v17, 0x400000, v10
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v4, v9, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v9, 0x40c00000, s1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v11, v13, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v13, v13
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v12, v12, v10
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v15, v9, 16, 1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v11, v11, v13
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v19, 0x400000, v9
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v12, 0x7fff, v12
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v13, 0x7fff, v16
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v15, v15, v9
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v11, 0x7fff, v11
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v16, 0x400000, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v15, 0x7fff, v15
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v11, v11, v18, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v11, 16, v11
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v9, v15, v19, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v9, 16, v9
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v10, v12, v17, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v14, v14
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v10, 16, v10
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v12, v13, v16, vcc_lo
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v13, 0xffff, v4
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v4, v1, 16, v0
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v3, v2, 16, v3
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v1, v10, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v12, 16, v12
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v2, v8, 16, v13
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v0, v12, 16, v9
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB67_3:
; GFX11-FAKE16-NEXT:    s_branch .LBB67_2
; GFX11-FAKE16-NEXT:  .LBB67_4:
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x bfloat> %a, splat (bfloat 0xR40C0)
  %a2 = bitcast <16 x bfloat> %a1 to <4 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <16 x bfloat> %a to <4 x i64>
  br label %end

end:
  %phi = phi <4 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x i64> %phi
}

define <32 x i8> @bitcast_v4i64_to_v32i8(<4 x i64> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v4i64_to_v32i8:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_mov_b32_e32 v28, v7
; SI-NEXT:    v_mov_b32_e32 v24, v6
; SI-NEXT:    v_mov_b32_e32 v20, v5
; SI-NEXT:    v_mov_b32_e32 v16, v4
; SI-NEXT:    v_mov_b32_e32 v12, v3
; SI-NEXT:    v_mov_b32_e32 v32, v2
; SI-NEXT:    v_mov_b32_e32 v4, v1
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    ; implicit-def: $vgpr1
; SI-NEXT:    ; implicit-def: $vgpr2
; SI-NEXT:    ; implicit-def: $vgpr3
; SI-NEXT:    ; implicit-def: $vgpr5
; SI-NEXT:    ; implicit-def: $vgpr6
; SI-NEXT:    ; implicit-def: $vgpr7
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr25
; SI-NEXT:    ; implicit-def: $vgpr26
; SI-NEXT:    ; implicit-def: $vgpr27
; SI-NEXT:    ; implicit-def: $vgpr29
; SI-NEXT:    ; implicit-def: $vgpr30
; SI-NEXT:    ; implicit-def: $vgpr31
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB68_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_alignbit_b32 v27, v28, v24, 24
; SI-NEXT:    v_alignbit_b32 v26, v28, v24, 16
; SI-NEXT:    v_alignbit_b32 v25, v28, v24, 8
; SI-NEXT:    v_alignbit_b32 v19, v20, v16, 24
; SI-NEXT:    v_alignbit_b32 v18, v20, v16, 16
; SI-NEXT:    v_alignbit_b32 v17, v20, v16, 8
; SI-NEXT:    v_alignbit_b32 v11, v12, v32, 24
; SI-NEXT:    v_alignbit_b32 v10, v12, v32, 16
; SI-NEXT:    v_alignbit_b32 v9, v12, v32, 8
; SI-NEXT:    v_alignbit_b32 v3, v4, v0, 24
; SI-NEXT:    v_alignbit_b32 v2, v4, v0, 16
; SI-NEXT:    v_alignbit_b32 v1, v4, v0, 8
; SI-NEXT:    v_lshrrev_b32_e32 v31, 24, v28
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v28
; SI-NEXT:    v_lshrrev_b32_e32 v29, 8, v28
; SI-NEXT:    v_lshrrev_b32_e32 v23, 24, v20
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v20
; SI-NEXT:    v_lshrrev_b32_e32 v21, 8, v20
; SI-NEXT:    v_lshrrev_b32_e32 v15, 24, v12
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v12
; SI-NEXT:    v_lshrrev_b32_e32 v13, 8, v12
; SI-NEXT:    v_lshrrev_b32_e32 v7, 24, v4
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v4
; SI-NEXT:    v_lshrrev_b32_e32 v5, 8, v4
; SI-NEXT:  .LBB68_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB68_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:    v_addc_u32_e32 v4, vcc, 0, v4, vcc
; SI-NEXT:    v_add_i32_e32 v32, vcc, 3, v32
; SI-NEXT:    v_addc_u32_e32 v12, vcc, 0, v12, vcc
; SI-NEXT:    v_add_i32_e32 v16, vcc, 3, v16
; SI-NEXT:    v_addc_u32_e32 v20, vcc, 0, v20, vcc
; SI-NEXT:    v_add_i32_e32 v24, vcc, 3, v24
; SI-NEXT:    v_addc_u32_e32 v28, vcc, 0, v28, vcc
; SI-NEXT:    v_alignbit_b32 v27, v28, v24, 24
; SI-NEXT:    v_alignbit_b32 v26, v28, v24, 16
; SI-NEXT:    v_alignbit_b32 v25, v28, v24, 8
; SI-NEXT:    v_alignbit_b32 v19, v20, v16, 24
; SI-NEXT:    v_alignbit_b32 v18, v20, v16, 16
; SI-NEXT:    v_alignbit_b32 v17, v20, v16, 8
; SI-NEXT:    v_alignbit_b32 v11, v12, v32, 24
; SI-NEXT:    v_alignbit_b32 v10, v12, v32, 16
; SI-NEXT:    v_alignbit_b32 v9, v12, v32, 8
; SI-NEXT:    v_alignbit_b32 v3, v4, v0, 24
; SI-NEXT:    v_alignbit_b32 v2, v4, v0, 16
; SI-NEXT:    v_alignbit_b32 v1, v4, v0, 8
; SI-NEXT:    v_lshrrev_b32_e32 v31, 24, v28
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v28
; SI-NEXT:    v_lshrrev_b32_e32 v29, 8, v28
; SI-NEXT:    v_lshrrev_b32_e32 v23, 24, v20
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v20
; SI-NEXT:    v_lshrrev_b32_e32 v21, 8, v20
; SI-NEXT:    v_lshrrev_b32_e32 v15, 24, v12
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v12
; SI-NEXT:    v_lshrrev_b32_e32 v13, 8, v12
; SI-NEXT:    v_lshrrev_b32_e32 v7, 24, v4
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v4
; SI-NEXT:    v_lshrrev_b32_e32 v5, 8, v4
; SI-NEXT:  .LBB68_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_mov_b32_e32 v8, v32
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v4i64_to_v32i8:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_mov_b32_e32 v33, v5
; VI-NEXT:    v_mov_b32_e32 v32, v4
; VI-NEXT:    v_mov_b32_e32 v35, v3
; VI-NEXT:    v_mov_b32_e32 v34, v2
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr2
; VI-NEXT:    ; implicit-def: $vgpr5
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr9
; VI-NEXT:    ; implicit-def: $vgpr10
; VI-NEXT:    ; implicit-def: $vgpr13
; VI-NEXT:    ; implicit-def: $vgpr14
; VI-NEXT:    ; implicit-def: $vgpr15
; VI-NEXT:    ; implicit-def: $vgpr17
; VI-NEXT:    ; implicit-def: $vgpr18
; VI-NEXT:    ; implicit-def: $vgpr21
; VI-NEXT:    ; implicit-def: $vgpr22
; VI-NEXT:    ; implicit-def: $vgpr23
; VI-NEXT:    ; implicit-def: $vgpr25
; VI-NEXT:    ; implicit-def: $vgpr26
; VI-NEXT:    ; implicit-def: $vgpr29
; VI-NEXT:    ; implicit-def: $vgpr30
; VI-NEXT:    ; implicit-def: $vgpr31
; VI-NEXT:    ; implicit-def: $vgpr3
; VI-NEXT:    ; implicit-def: $vgpr11
; VI-NEXT:    ; implicit-def: $vgpr19
; VI-NEXT:    ; implicit-def: $vgpr27
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB68_2
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v25, 8, v6
; VI-NEXT:    v_lshrrev_b32_e32 v23, 24, v33
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v33
; VI-NEXT:    v_lshrrev_b32_e32 v21, 8, v33
; VI-NEXT:    v_lshrrev_b32_e32 v18, 16, v32
; VI-NEXT:    v_lshrrev_b32_e32 v17, 8, v32
; VI-NEXT:    v_lshrrev_b32_e32 v15, 24, v35
; VI-NEXT:    v_lshrrev_b32_e32 v14, 16, v35
; VI-NEXT:    v_lshrrev_b32_e32 v13, 8, v35
; VI-NEXT:    v_lshrrev_b32_e32 v10, 16, v34
; VI-NEXT:    v_lshrrev_b32_e32 v9, 8, v34
; VI-NEXT:    v_lshrrev_b32_e32 v36, 24, v1
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; VI-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; VI-NEXT:    v_lshrrev_b32_e32 v38, 8, v0
; VI-NEXT:    v_lshrrev_b64 v[27:28], 24, v[6:7]
; VI-NEXT:    v_lshrrev_b64 v[19:20], 24, v[32:33]
; VI-NEXT:    v_lshrrev_b64 v[11:12], 24, v[34:35]
; VI-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; VI-NEXT:  .LBB68_2: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB68_4
; VI-NEXT:  ; %bb.3: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-NEXT:    v_add_u32_e32 v34, vcc, 3, v34
; VI-NEXT:    v_addc_u32_e32 v35, vcc, 0, v35, vcc
; VI-NEXT:    v_add_u32_e32 v32, vcc, 3, v32
; VI-NEXT:    v_addc_u32_e32 v33, vcc, 0, v33, vcc
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; VI-NEXT:    v_lshrrev_b64 v[27:28], 24, v[6:7]
; VI-NEXT:    v_lshrrev_b64 v[19:20], 24, v[32:33]
; VI-NEXT:    v_lshrrev_b64 v[11:12], 24, v[34:35]
; VI-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; VI-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v25, 8, v6
; VI-NEXT:    v_lshrrev_b32_e32 v23, 24, v33
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v33
; VI-NEXT:    v_lshrrev_b32_e32 v21, 8, v33
; VI-NEXT:    v_lshrrev_b32_e32 v18, 16, v32
; VI-NEXT:    v_lshrrev_b32_e32 v17, 8, v32
; VI-NEXT:    v_lshrrev_b32_e32 v15, 24, v35
; VI-NEXT:    v_lshrrev_b32_e32 v14, 16, v35
; VI-NEXT:    v_lshrrev_b32_e32 v13, 8, v35
; VI-NEXT:    v_lshrrev_b32_e32 v10, 16, v34
; VI-NEXT:    v_lshrrev_b32_e32 v9, 8, v34
; VI-NEXT:    v_lshrrev_b32_e32 v36, 24, v1
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; VI-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; VI-NEXT:    v_lshrrev_b32_e32 v38, 8, v0
; VI-NEXT:  .LBB68_4: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    v_mov_b32_e32 v4, v1
; VI-NEXT:    v_mov_b32_e32 v8, v34
; VI-NEXT:    v_mov_b32_e32 v12, v35
; VI-NEXT:    v_mov_b32_e32 v16, v32
; VI-NEXT:    v_mov_b32_e32 v20, v33
; VI-NEXT:    v_mov_b32_e32 v24, v6
; VI-NEXT:    v_mov_b32_e32 v28, v7
; VI-NEXT:    v_mov_b32_e32 v1, v38
; VI-NEXT:    v_mov_b32_e32 v6, v37
; VI-NEXT:    v_mov_b32_e32 v7, v36
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v4i64_to_v32i8:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_mov_b32_e32 v33, v5
; GFX9-NEXT:    v_mov_b32_e32 v32, v4
; GFX9-NEXT:    v_mov_b32_e32 v35, v3
; GFX9-NEXT:    v_mov_b32_e32 v34, v2
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr2
; GFX9-NEXT:    ; implicit-def: $vgpr5
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr9
; GFX9-NEXT:    ; implicit-def: $vgpr10
; GFX9-NEXT:    ; implicit-def: $vgpr13
; GFX9-NEXT:    ; implicit-def: $vgpr14
; GFX9-NEXT:    ; implicit-def: $vgpr15
; GFX9-NEXT:    ; implicit-def: $vgpr17
; GFX9-NEXT:    ; implicit-def: $vgpr18
; GFX9-NEXT:    ; implicit-def: $vgpr21
; GFX9-NEXT:    ; implicit-def: $vgpr22
; GFX9-NEXT:    ; implicit-def: $vgpr23
; GFX9-NEXT:    ; implicit-def: $vgpr25
; GFX9-NEXT:    ; implicit-def: $vgpr26
; GFX9-NEXT:    ; implicit-def: $vgpr29
; GFX9-NEXT:    ; implicit-def: $vgpr30
; GFX9-NEXT:    ; implicit-def: $vgpr31
; GFX9-NEXT:    ; implicit-def: $vgpr3
; GFX9-NEXT:    ; implicit-def: $vgpr11
; GFX9-NEXT:    ; implicit-def: $vgpr19
; GFX9-NEXT:    ; implicit-def: $vgpr27
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB68_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 8, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 24, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 8, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v18, 16, v32
; GFX9-NEXT:    v_lshrrev_b32_e32 v17, 8, v32
; GFX9-NEXT:    v_lshrrev_b32_e32 v15, 24, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v14, 16, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v13, 8, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v10, 16, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v9, 8, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 24, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 8, v0
; GFX9-NEXT:    v_lshrrev_b64 v[27:28], 24, v[6:7]
; GFX9-NEXT:    v_lshrrev_b64 v[19:20], 24, v[32:33]
; GFX9-NEXT:    v_lshrrev_b64 v[11:12], 24, v[34:35]
; GFX9-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; GFX9-NEXT:  .LBB68_2: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB68_4
; GFX9-NEXT:  ; %bb.3: ; %cmp.true
; GFX9-NEXT:    v_add_co_u32_e32 v0, vcc, 3, v0
; GFX9-NEXT:    v_addc_co_u32_e32 v1, vcc, 0, v1, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v34, vcc, 3, v34
; GFX9-NEXT:    v_addc_co_u32_e32 v35, vcc, 0, v35, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v32, vcc, 3, v32
; GFX9-NEXT:    v_addc_co_u32_e32 v33, vcc, 0, v33, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v6, vcc, 3, v6
; GFX9-NEXT:    v_addc_co_u32_e32 v7, vcc, 0, v7, vcc
; GFX9-NEXT:    v_lshrrev_b64 v[27:28], 24, v[6:7]
; GFX9-NEXT:    v_lshrrev_b64 v[19:20], 24, v[32:33]
; GFX9-NEXT:    v_lshrrev_b64 v[11:12], 24, v[34:35]
; GFX9-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 8, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 24, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 8, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v18, 16, v32
; GFX9-NEXT:    v_lshrrev_b32_e32 v17, 8, v32
; GFX9-NEXT:    v_lshrrev_b32_e32 v15, 24, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v14, 16, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v13, 8, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v10, 16, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v9, 8, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 24, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 8, v0
; GFX9-NEXT:  .LBB68_4: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    v_mov_b32_e32 v4, v1
; GFX9-NEXT:    v_mov_b32_e32 v8, v34
; GFX9-NEXT:    v_mov_b32_e32 v12, v35
; GFX9-NEXT:    v_mov_b32_e32 v16, v32
; GFX9-NEXT:    v_mov_b32_e32 v20, v33
; GFX9-NEXT:    v_mov_b32_e32 v24, v6
; GFX9-NEXT:    v_mov_b32_e32 v28, v7
; GFX9-NEXT:    v_mov_b32_e32 v1, v38
; GFX9-NEXT:    v_mov_b32_e32 v6, v37
; GFX9-NEXT:    v_mov_b32_e32 v7, v36
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v4i64_to_v32i8:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v33, v7 :: v_dual_mov_b32 v32, v6
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v27, v5 :: v_dual_mov_b32 v26, v4
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v19, v3 :: v_dual_mov_b32 v18, v2
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v11, v1 :: v_dual_mov_b32 v10, v0
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr1_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr3_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr5_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr7_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr36_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr15_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr17_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr35_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr21_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr23_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr25_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr34_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr29_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr31_lo16
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB68_2
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[34:35], 24, v[32:33]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[35:36], 24, v[26:27]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v27
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v27
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v26
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v18
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[36:37], 24, v[18:19]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[10:11]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v10
; GFX11-TRUE16-NEXT:  .LBB68_2: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB68_4
; GFX11-TRUE16-NEXT:  ; %bb.3: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_add_co_u32 v18, vcc_lo, v18, 3
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add_co_ci_u32_e64 v19, null, 0, v19, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_co_u32 v26, vcc_lo, v26, 3
; GFX11-TRUE16-NEXT:    v_add_co_ci_u32_e64 v27, null, 0, v27, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_co_u32 v32, vcc_lo, v32, 3
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add_co_ci_u32_e64 v33, null, 0, v33, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_co_u32 v10, vcc_lo, v10, 3
; GFX11-TRUE16-NEXT:    v_add_co_ci_u32_e64 v11, null, 0, v11, vcc_lo
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[34:35], 24, v[32:33]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[35:36], 24, v[26:27]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[36:37], 24, v[18:19]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[10:11]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v27
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v27
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v26
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v18
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v10
; GFX11-TRUE16-NEXT:  .LBB68_4: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.l, v10.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.l, v10.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v4.l, v11.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v6.l, v11.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v8.l, v18.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v10.l, v18.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v11.l, v36.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v12.l, v19.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v14.l, v19.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v16.l, v26.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v18.l, v26.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v19.l, v35.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v20.l, v27.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v22.l, v27.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v24.l, v32.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v26.l, v32.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v27.l, v34.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v28.l, v33.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v30.l, v33.h
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v4i64_to_v32i8:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v33, v7 :: v_dual_mov_b32 v32, v6
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v35, v5 :: v_dual_mov_b32 v34, v4
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v37, v3 :: v_dual_mov_b32 v36, v2
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v39, v1 :: v_dual_mov_b32 v38, v0
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v8
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr1
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr2
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr3
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr5
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr6
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr7
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr9
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr10
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr11
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr13
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr14
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr15
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr17
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr18
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr19
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr21
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr22
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr23
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr25
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr26
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr27
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr29
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr30
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr31
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB68_2
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v32
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v18, 16, v34
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v34
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v14, 16, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v10, 16, v36
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v36
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v6, 16, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v38
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[27:28], 24, v[32:33]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[19:20], 24, v[34:35]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[11:12], 24, v[36:37]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[38:39]
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v38
; GFX11-FAKE16-NEXT:  .LBB68_2: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB68_4
; GFX11-FAKE16-NEXT:  ; %bb.3: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_add_co_u32 v36, vcc_lo, v36, 3
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_add_co_ci_u32_e64 v37, null, 0, v37, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_co_u32 v34, vcc_lo, v34, 3
; GFX11-FAKE16-NEXT:    v_add_co_ci_u32_e64 v35, null, 0, v35, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_co_u32 v32, vcc_lo, v32, 3
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_add_co_ci_u32_e64 v33, null, 0, v33, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_co_u32 v38, vcc_lo, v38, 3
; GFX11-FAKE16-NEXT:    v_add_co_ci_u32_e64 v39, null, 0, v39, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[27:28], 24, v[32:33]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[19:20], 24, v[34:35]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[11:12], 24, v[36:37]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[38:39]
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v32
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v18, 16, v34
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v34
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v14, 16, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v10, 16, v36
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v36
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v6, 16, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v38
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v38
; GFX11-FAKE16-NEXT:  .LBB68_4: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v0, v38
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v4, v39
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v8, v36
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v12, v37
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v16, v34
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v20, v35
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v24, v32
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v28, v33
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <4 x i64> %a, splat (i64 3)
  %a2 = bitcast <4 x i64> %a1 to <32 x i8>
  br label %end

cmp.false:
  %a3 = bitcast <4 x i64> %a to <32 x i8>
  br label %end

end:
  %phi = phi <32 x i8> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x i8> %phi
}

define inreg <32 x i8> @bitcast_v4i64_to_v32i8_scalar(<4 x i64> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v4i64_to_v32i8_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB69_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_lshr_b32 s56, s23, 24
; SI-NEXT:    s_lshr_b32 s57, s23, 16
; SI-NEXT:    s_lshr_b32 s58, s23, 8
; SI-NEXT:    s_lshr_b32 s59, s21, 24
; SI-NEXT:    s_lshr_b32 s60, s21, 16
; SI-NEXT:    s_lshr_b32 s61, s21, 8
; SI-NEXT:    s_lshr_b32 s62, s19, 24
; SI-NEXT:    s_lshr_b32 s63, s19, 16
; SI-NEXT:    s_lshr_b32 s72, s19, 8
; SI-NEXT:    s_lshr_b32 s73, s17, 24
; SI-NEXT:    s_lshr_b32 s74, s17, 16
; SI-NEXT:    s_lshr_b32 s75, s17, 8
; SI-NEXT:    s_lshr_b64 s[4:5], s[22:23], 24
; SI-NEXT:    s_lshr_b64 s[6:7], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[8:9], s[22:23], 8
; SI-NEXT:    s_lshr_b64 s[10:11], s[20:21], 24
; SI-NEXT:    s_lshr_b64 s[12:13], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[14:15], s[20:21], 8
; SI-NEXT:    s_lshr_b64 s[24:25], s[18:19], 24
; SI-NEXT:    s_lshr_b64 s[26:27], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[28:29], s[18:19], 8
; SI-NEXT:    s_lshr_b64 s[40:41], s[16:17], 24
; SI-NEXT:    s_lshr_b64 s[42:43], s[16:17], 16
; SI-NEXT:    s_lshr_b64 s[44:45], s[16:17], 8
; SI-NEXT:    s_cbranch_execnz .LBB69_3
; SI-NEXT:  .LBB69_2: ; %cmp.true
; SI-NEXT:    s_add_u32 s22, s22, 3
; SI-NEXT:    s_addc_u32 s23, s23, 0
; SI-NEXT:    s_add_u32 s20, s20, 3
; SI-NEXT:    s_addc_u32 s21, s21, 0
; SI-NEXT:    s_add_u32 s18, s18, 3
; SI-NEXT:    s_addc_u32 s19, s19, 0
; SI-NEXT:    s_add_u32 s16, s16, 3
; SI-NEXT:    s_addc_u32 s17, s17, 0
; SI-NEXT:    s_lshr_b32 s56, s23, 24
; SI-NEXT:    s_lshr_b32 s57, s23, 16
; SI-NEXT:    s_lshr_b32 s58, s23, 8
; SI-NEXT:    s_lshr_b32 s59, s21, 24
; SI-NEXT:    s_lshr_b32 s60, s21, 16
; SI-NEXT:    s_lshr_b32 s61, s21, 8
; SI-NEXT:    s_lshr_b32 s62, s19, 24
; SI-NEXT:    s_lshr_b32 s63, s19, 16
; SI-NEXT:    s_lshr_b32 s72, s19, 8
; SI-NEXT:    s_lshr_b32 s73, s17, 24
; SI-NEXT:    s_lshr_b32 s74, s17, 16
; SI-NEXT:    s_lshr_b32 s75, s17, 8
; SI-NEXT:    s_lshr_b64 s[4:5], s[22:23], 24
; SI-NEXT:    s_lshr_b64 s[6:7], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[8:9], s[22:23], 8
; SI-NEXT:    s_lshr_b64 s[10:11], s[20:21], 24
; SI-NEXT:    s_lshr_b64 s[12:13], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[14:15], s[20:21], 8
; SI-NEXT:    s_lshr_b64 s[24:25], s[18:19], 24
; SI-NEXT:    s_lshr_b64 s[26:27], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[28:29], s[18:19], 8
; SI-NEXT:    s_lshr_b64 s[40:41], s[16:17], 24
; SI-NEXT:    s_lshr_b64 s[42:43], s[16:17], 16
; SI-NEXT:    s_lshr_b64 s[44:45], s[16:17], 8
; SI-NEXT:  .LBB69_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v1, s44
; SI-NEXT:    v_mov_b32_e32 v2, s42
; SI-NEXT:    v_mov_b32_e32 v3, s40
; SI-NEXT:    v_mov_b32_e32 v4, s17
; SI-NEXT:    v_mov_b32_e32 v5, s75
; SI-NEXT:    v_mov_b32_e32 v6, s74
; SI-NEXT:    v_mov_b32_e32 v7, s73
; SI-NEXT:    v_mov_b32_e32 v8, s18
; SI-NEXT:    v_mov_b32_e32 v9, s28
; SI-NEXT:    v_mov_b32_e32 v10, s26
; SI-NEXT:    v_mov_b32_e32 v11, s24
; SI-NEXT:    v_mov_b32_e32 v12, s19
; SI-NEXT:    v_mov_b32_e32 v13, s72
; SI-NEXT:    v_mov_b32_e32 v14, s63
; SI-NEXT:    v_mov_b32_e32 v15, s62
; SI-NEXT:    v_mov_b32_e32 v16, s20
; SI-NEXT:    v_mov_b32_e32 v17, s14
; SI-NEXT:    v_mov_b32_e32 v18, s12
; SI-NEXT:    v_mov_b32_e32 v19, s10
; SI-NEXT:    v_mov_b32_e32 v20, s21
; SI-NEXT:    v_mov_b32_e32 v21, s61
; SI-NEXT:    v_mov_b32_e32 v22, s60
; SI-NEXT:    v_mov_b32_e32 v23, s59
; SI-NEXT:    v_mov_b32_e32 v24, s22
; SI-NEXT:    v_mov_b32_e32 v25, s8
; SI-NEXT:    v_mov_b32_e32 v26, s6
; SI-NEXT:    v_mov_b32_e32 v27, s4
; SI-NEXT:    v_mov_b32_e32 v28, s23
; SI-NEXT:    v_mov_b32_e32 v29, s58
; SI-NEXT:    v_mov_b32_e32 v30, s57
; SI-NEXT:    v_mov_b32_e32 v31, s56
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB69_4:
; SI-NEXT:    ; implicit-def: $sgpr44
; SI-NEXT:    ; implicit-def: $sgpr42
; SI-NEXT:    ; implicit-def: $sgpr40
; SI-NEXT:    ; implicit-def: $sgpr75
; SI-NEXT:    ; implicit-def: $sgpr74
; SI-NEXT:    ; implicit-def: $sgpr73
; SI-NEXT:    ; implicit-def: $sgpr28
; SI-NEXT:    ; implicit-def: $sgpr26
; SI-NEXT:    ; implicit-def: $sgpr24
; SI-NEXT:    ; implicit-def: $sgpr72
; SI-NEXT:    ; implicit-def: $sgpr63
; SI-NEXT:    ; implicit-def: $sgpr62
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr12
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr61
; SI-NEXT:    ; implicit-def: $sgpr60
; SI-NEXT:    ; implicit-def: $sgpr59
; SI-NEXT:    ; implicit-def: $sgpr8
; SI-NEXT:    ; implicit-def: $sgpr6
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr58
; SI-NEXT:    ; implicit-def: $sgpr57
; SI-NEXT:    ; implicit-def: $sgpr56
; SI-NEXT:    s_branch .LBB69_2
;
; VI-LABEL: bitcast_v4i64_to_v32i8_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB69_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_lshr_b32 s14, s23, 24
; VI-NEXT:    s_lshr_b32 s15, s23, 16
; VI-NEXT:    s_lshr_b32 s24, s23, 8
; VI-NEXT:    s_lshr_b32 s25, s22, 16
; VI-NEXT:    s_lshr_b32 s26, s22, 8
; VI-NEXT:    s_lshr_b32 s27, s21, 24
; VI-NEXT:    s_lshr_b32 s28, s21, 16
; VI-NEXT:    s_lshr_b32 s29, s21, 8
; VI-NEXT:    s_lshr_b32 s40, s20, 16
; VI-NEXT:    s_lshr_b32 s41, s20, 8
; VI-NEXT:    s_lshr_b32 s42, s19, 24
; VI-NEXT:    s_lshr_b32 s43, s19, 16
; VI-NEXT:    s_lshr_b32 s44, s19, 8
; VI-NEXT:    s_lshr_b32 s45, s18, 16
; VI-NEXT:    s_lshr_b32 s46, s18, 8
; VI-NEXT:    s_lshr_b32 s47, s17, 24
; VI-NEXT:    s_lshr_b32 s56, s17, 16
; VI-NEXT:    s_lshr_b32 s57, s17, 8
; VI-NEXT:    s_lshr_b32 s58, s16, 16
; VI-NEXT:    s_lshr_b32 s59, s16, 8
; VI-NEXT:    s_lshr_b64 s[4:5], s[22:23], 24
; VI-NEXT:    s_lshr_b64 s[6:7], s[20:21], 24
; VI-NEXT:    s_lshr_b64 s[8:9], s[18:19], 24
; VI-NEXT:    s_lshr_b64 s[10:11], s[16:17], 24
; VI-NEXT:    s_cbranch_execnz .LBB69_3
; VI-NEXT:  .LBB69_2: ; %cmp.true
; VI-NEXT:    s_add_u32 s16, s16, 3
; VI-NEXT:    s_addc_u32 s17, s17, 0
; VI-NEXT:    s_add_u32 s18, s18, 3
; VI-NEXT:    s_addc_u32 s19, s19, 0
; VI-NEXT:    s_add_u32 s20, s20, 3
; VI-NEXT:    s_addc_u32 s21, s21, 0
; VI-NEXT:    s_add_u32 s22, s22, 3
; VI-NEXT:    s_addc_u32 s23, s23, 0
; VI-NEXT:    s_lshr_b64 s[4:5], s[22:23], 24
; VI-NEXT:    s_lshr_b64 s[6:7], s[20:21], 24
; VI-NEXT:    s_lshr_b64 s[8:9], s[18:19], 24
; VI-NEXT:    s_lshr_b64 s[10:11], s[16:17], 24
; VI-NEXT:    s_lshr_b32 s14, s23, 24
; VI-NEXT:    s_lshr_b32 s15, s23, 16
; VI-NEXT:    s_lshr_b32 s24, s23, 8
; VI-NEXT:    s_lshr_b32 s25, s22, 16
; VI-NEXT:    s_lshr_b32 s26, s22, 8
; VI-NEXT:    s_lshr_b32 s27, s21, 24
; VI-NEXT:    s_lshr_b32 s28, s21, 16
; VI-NEXT:    s_lshr_b32 s29, s21, 8
; VI-NEXT:    s_lshr_b32 s40, s20, 16
; VI-NEXT:    s_lshr_b32 s41, s20, 8
; VI-NEXT:    s_lshr_b32 s42, s19, 24
; VI-NEXT:    s_lshr_b32 s43, s19, 16
; VI-NEXT:    s_lshr_b32 s44, s19, 8
; VI-NEXT:    s_lshr_b32 s45, s18, 16
; VI-NEXT:    s_lshr_b32 s46, s18, 8
; VI-NEXT:    s_lshr_b32 s47, s17, 24
; VI-NEXT:    s_lshr_b32 s56, s17, 16
; VI-NEXT:    s_lshr_b32 s57, s17, 8
; VI-NEXT:    s_lshr_b32 s58, s16, 16
; VI-NEXT:    s_lshr_b32 s59, s16, 8
; VI-NEXT:  .LBB69_3: ; %end
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s59
; VI-NEXT:    v_mov_b32_e32 v2, s58
; VI-NEXT:    v_mov_b32_e32 v3, s10
; VI-NEXT:    v_mov_b32_e32 v4, s17
; VI-NEXT:    v_mov_b32_e32 v5, s57
; VI-NEXT:    v_mov_b32_e32 v6, s56
; VI-NEXT:    v_mov_b32_e32 v7, s47
; VI-NEXT:    v_mov_b32_e32 v8, s18
; VI-NEXT:    v_mov_b32_e32 v9, s46
; VI-NEXT:    v_mov_b32_e32 v10, s45
; VI-NEXT:    v_mov_b32_e32 v11, s8
; VI-NEXT:    v_mov_b32_e32 v12, s19
; VI-NEXT:    v_mov_b32_e32 v13, s44
; VI-NEXT:    v_mov_b32_e32 v14, s43
; VI-NEXT:    v_mov_b32_e32 v15, s42
; VI-NEXT:    v_mov_b32_e32 v16, s20
; VI-NEXT:    v_mov_b32_e32 v17, s41
; VI-NEXT:    v_mov_b32_e32 v18, s40
; VI-NEXT:    v_mov_b32_e32 v19, s6
; VI-NEXT:    v_mov_b32_e32 v20, s21
; VI-NEXT:    v_mov_b32_e32 v21, s29
; VI-NEXT:    v_mov_b32_e32 v22, s28
; VI-NEXT:    v_mov_b32_e32 v23, s27
; VI-NEXT:    v_mov_b32_e32 v24, s22
; VI-NEXT:    v_mov_b32_e32 v25, s26
; VI-NEXT:    v_mov_b32_e32 v26, s25
; VI-NEXT:    v_mov_b32_e32 v27, s4
; VI-NEXT:    v_mov_b32_e32 v28, s23
; VI-NEXT:    v_mov_b32_e32 v29, s24
; VI-NEXT:    v_mov_b32_e32 v30, s15
; VI-NEXT:    v_mov_b32_e32 v31, s14
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB69_4:
; VI-NEXT:    ; implicit-def: $sgpr59
; VI-NEXT:    ; implicit-def: $sgpr58
; VI-NEXT:    ; implicit-def: $sgpr10
; VI-NEXT:    ; implicit-def: $sgpr57
; VI-NEXT:    ; implicit-def: $sgpr56
; VI-NEXT:    ; implicit-def: $sgpr47
; VI-NEXT:    ; implicit-def: $sgpr46
; VI-NEXT:    ; implicit-def: $sgpr45
; VI-NEXT:    ; implicit-def: $sgpr8
; VI-NEXT:    ; implicit-def: $sgpr44
; VI-NEXT:    ; implicit-def: $sgpr43
; VI-NEXT:    ; implicit-def: $sgpr42
; VI-NEXT:    ; implicit-def: $sgpr41
; VI-NEXT:    ; implicit-def: $sgpr40
; VI-NEXT:    ; implicit-def: $sgpr6
; VI-NEXT:    ; implicit-def: $sgpr29
; VI-NEXT:    ; implicit-def: $sgpr28
; VI-NEXT:    ; implicit-def: $sgpr27
; VI-NEXT:    ; implicit-def: $sgpr26
; VI-NEXT:    ; implicit-def: $sgpr25
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr24
; VI-NEXT:    ; implicit-def: $sgpr15
; VI-NEXT:    ; implicit-def: $sgpr14
; VI-NEXT:    s_branch .LBB69_2
;
; GFX9-LABEL: bitcast_v4i64_to_v32i8_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB69_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_lshr_b32 s14, s23, 24
; GFX9-NEXT:    s_lshr_b32 s15, s23, 16
; GFX9-NEXT:    s_lshr_b32 s24, s23, 8
; GFX9-NEXT:    s_lshr_b32 s25, s22, 16
; GFX9-NEXT:    s_lshr_b32 s26, s22, 8
; GFX9-NEXT:    s_lshr_b32 s27, s21, 24
; GFX9-NEXT:    s_lshr_b32 s28, s21, 16
; GFX9-NEXT:    s_lshr_b32 s29, s21, 8
; GFX9-NEXT:    s_lshr_b32 s40, s20, 16
; GFX9-NEXT:    s_lshr_b32 s41, s20, 8
; GFX9-NEXT:    s_lshr_b32 s42, s19, 24
; GFX9-NEXT:    s_lshr_b32 s43, s19, 16
; GFX9-NEXT:    s_lshr_b32 s44, s19, 8
; GFX9-NEXT:    s_lshr_b32 s45, s18, 16
; GFX9-NEXT:    s_lshr_b32 s46, s18, 8
; GFX9-NEXT:    s_lshr_b32 s47, s17, 24
; GFX9-NEXT:    s_lshr_b32 s56, s17, 16
; GFX9-NEXT:    s_lshr_b32 s57, s17, 8
; GFX9-NEXT:    s_lshr_b32 s58, s16, 16
; GFX9-NEXT:    s_lshr_b32 s59, s16, 8
; GFX9-NEXT:    s_lshr_b64 s[4:5], s[22:23], 24
; GFX9-NEXT:    s_lshr_b64 s[6:7], s[20:21], 24
; GFX9-NEXT:    s_lshr_b64 s[8:9], s[18:19], 24
; GFX9-NEXT:    s_lshr_b64 s[10:11], s[16:17], 24
; GFX9-NEXT:    s_cbranch_execnz .LBB69_3
; GFX9-NEXT:  .LBB69_2: ; %cmp.true
; GFX9-NEXT:    s_add_u32 s16, s16, 3
; GFX9-NEXT:    s_addc_u32 s17, s17, 0
; GFX9-NEXT:    s_add_u32 s18, s18, 3
; GFX9-NEXT:    s_addc_u32 s19, s19, 0
; GFX9-NEXT:    s_add_u32 s20, s20, 3
; GFX9-NEXT:    s_addc_u32 s21, s21, 0
; GFX9-NEXT:    s_add_u32 s22, s22, 3
; GFX9-NEXT:    s_addc_u32 s23, s23, 0
; GFX9-NEXT:    s_lshr_b64 s[4:5], s[22:23], 24
; GFX9-NEXT:    s_lshr_b64 s[6:7], s[20:21], 24
; GFX9-NEXT:    s_lshr_b64 s[8:9], s[18:19], 24
; GFX9-NEXT:    s_lshr_b64 s[10:11], s[16:17], 24
; GFX9-NEXT:    s_lshr_b32 s14, s23, 24
; GFX9-NEXT:    s_lshr_b32 s15, s23, 16
; GFX9-NEXT:    s_lshr_b32 s24, s23, 8
; GFX9-NEXT:    s_lshr_b32 s25, s22, 16
; GFX9-NEXT:    s_lshr_b32 s26, s22, 8
; GFX9-NEXT:    s_lshr_b32 s27, s21, 24
; GFX9-NEXT:    s_lshr_b32 s28, s21, 16
; GFX9-NEXT:    s_lshr_b32 s29, s21, 8
; GFX9-NEXT:    s_lshr_b32 s40, s20, 16
; GFX9-NEXT:    s_lshr_b32 s41, s20, 8
; GFX9-NEXT:    s_lshr_b32 s42, s19, 24
; GFX9-NEXT:    s_lshr_b32 s43, s19, 16
; GFX9-NEXT:    s_lshr_b32 s44, s19, 8
; GFX9-NEXT:    s_lshr_b32 s45, s18, 16
; GFX9-NEXT:    s_lshr_b32 s46, s18, 8
; GFX9-NEXT:    s_lshr_b32 s47, s17, 24
; GFX9-NEXT:    s_lshr_b32 s56, s17, 16
; GFX9-NEXT:    s_lshr_b32 s57, s17, 8
; GFX9-NEXT:    s_lshr_b32 s58, s16, 16
; GFX9-NEXT:    s_lshr_b32 s59, s16, 8
; GFX9-NEXT:  .LBB69_3: ; %end
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s59
; GFX9-NEXT:    v_mov_b32_e32 v2, s58
; GFX9-NEXT:    v_mov_b32_e32 v3, s10
; GFX9-NEXT:    v_mov_b32_e32 v4, s17
; GFX9-NEXT:    v_mov_b32_e32 v5, s57
; GFX9-NEXT:    v_mov_b32_e32 v6, s56
; GFX9-NEXT:    v_mov_b32_e32 v7, s47
; GFX9-NEXT:    v_mov_b32_e32 v8, s18
; GFX9-NEXT:    v_mov_b32_e32 v9, s46
; GFX9-NEXT:    v_mov_b32_e32 v10, s45
; GFX9-NEXT:    v_mov_b32_e32 v11, s8
; GFX9-NEXT:    v_mov_b32_e32 v12, s19
; GFX9-NEXT:    v_mov_b32_e32 v13, s44
; GFX9-NEXT:    v_mov_b32_e32 v14, s43
; GFX9-NEXT:    v_mov_b32_e32 v15, s42
; GFX9-NEXT:    v_mov_b32_e32 v16, s20
; GFX9-NEXT:    v_mov_b32_e32 v17, s41
; GFX9-NEXT:    v_mov_b32_e32 v18, s40
; GFX9-NEXT:    v_mov_b32_e32 v19, s6
; GFX9-NEXT:    v_mov_b32_e32 v20, s21
; GFX9-NEXT:    v_mov_b32_e32 v21, s29
; GFX9-NEXT:    v_mov_b32_e32 v22, s28
; GFX9-NEXT:    v_mov_b32_e32 v23, s27
; GFX9-NEXT:    v_mov_b32_e32 v24, s22
; GFX9-NEXT:    v_mov_b32_e32 v25, s26
; GFX9-NEXT:    v_mov_b32_e32 v26, s25
; GFX9-NEXT:    v_mov_b32_e32 v27, s4
; GFX9-NEXT:    v_mov_b32_e32 v28, s23
; GFX9-NEXT:    v_mov_b32_e32 v29, s24
; GFX9-NEXT:    v_mov_b32_e32 v30, s15
; GFX9-NEXT:    v_mov_b32_e32 v31, s14
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB69_4:
; GFX9-NEXT:    ; implicit-def: $sgpr59
; GFX9-NEXT:    ; implicit-def: $sgpr58
; GFX9-NEXT:    ; implicit-def: $sgpr10
; GFX9-NEXT:    ; implicit-def: $sgpr57
; GFX9-NEXT:    ; implicit-def: $sgpr56
; GFX9-NEXT:    ; implicit-def: $sgpr47
; GFX9-NEXT:    ; implicit-def: $sgpr46
; GFX9-NEXT:    ; implicit-def: $sgpr45
; GFX9-NEXT:    ; implicit-def: $sgpr8
; GFX9-NEXT:    ; implicit-def: $sgpr44
; GFX9-NEXT:    ; implicit-def: $sgpr43
; GFX9-NEXT:    ; implicit-def: $sgpr42
; GFX9-NEXT:    ; implicit-def: $sgpr41
; GFX9-NEXT:    ; implicit-def: $sgpr40
; GFX9-NEXT:    ; implicit-def: $sgpr6
; GFX9-NEXT:    ; implicit-def: $sgpr29
; GFX9-NEXT:    ; implicit-def: $sgpr28
; GFX9-NEXT:    ; implicit-def: $sgpr27
; GFX9-NEXT:    ; implicit-def: $sgpr26
; GFX9-NEXT:    ; implicit-def: $sgpr25
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr24
; GFX9-NEXT:    ; implicit-def: $sgpr15
; GFX9-NEXT:    ; implicit-def: $sgpr14
; GFX9-NEXT:    s_branch .LBB69_2
;
; GFX11-LABEL: bitcast_v4i64_to_v32i8_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s46, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB69_4
; GFX11-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-NEXT:    s_lshr_b32 s12, s19, 24
; GFX11-NEXT:    s_lshr_b32 s13, s19, 16
; GFX11-NEXT:    s_lshr_b32 s14, s19, 8
; GFX11-NEXT:    s_lshr_b32 s15, s18, 16
; GFX11-NEXT:    s_lshr_b32 s20, s18, 8
; GFX11-NEXT:    s_lshr_b32 s21, s17, 24
; GFX11-NEXT:    s_lshr_b32 s22, s17, 16
; GFX11-NEXT:    s_lshr_b32 s23, s17, 8
; GFX11-NEXT:    s_lshr_b32 s24, s16, 16
; GFX11-NEXT:    s_lshr_b32 s25, s16, 8
; GFX11-NEXT:    s_lshr_b32 s26, s3, 24
; GFX11-NEXT:    s_lshr_b32 s27, s3, 16
; GFX11-NEXT:    s_lshr_b32 s28, s3, 8
; GFX11-NEXT:    s_lshr_b32 s29, s2, 16
; GFX11-NEXT:    s_lshr_b32 s40, s2, 8
; GFX11-NEXT:    s_lshr_b32 s41, s1, 24
; GFX11-NEXT:    s_lshr_b32 s42, s1, 16
; GFX11-NEXT:    s_lshr_b32 s43, s1, 8
; GFX11-NEXT:    s_lshr_b32 s44, s0, 16
; GFX11-NEXT:    s_lshr_b32 s45, s0, 8
; GFX11-NEXT:    s_lshr_b64 s[4:5], s[18:19], 24
; GFX11-NEXT:    s_lshr_b64 s[6:7], s[16:17], 24
; GFX11-NEXT:    s_lshr_b64 s[8:9], s[2:3], 24
; GFX11-NEXT:    s_lshr_b64 s[10:11], s[0:1], 24
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s46
; GFX11-NEXT:    s_cbranch_vccnz .LBB69_3
; GFX11-NEXT:  .LBB69_2: ; %cmp.true
; GFX11-NEXT:    s_add_u32 s0, s0, 3
; GFX11-NEXT:    s_addc_u32 s1, s1, 0
; GFX11-NEXT:    s_add_u32 s2, s2, 3
; GFX11-NEXT:    s_addc_u32 s3, s3, 0
; GFX11-NEXT:    s_add_u32 s16, s16, 3
; GFX11-NEXT:    s_addc_u32 s17, s17, 0
; GFX11-NEXT:    s_add_u32 s18, s18, 3
; GFX11-NEXT:    s_addc_u32 s19, s19, 0
; GFX11-NEXT:    s_lshr_b64 s[6:7], s[16:17], 24
; GFX11-NEXT:    s_lshr_b64 s[4:5], s[18:19], 24
; GFX11-NEXT:    s_lshr_b64 s[8:9], s[2:3], 24
; GFX11-NEXT:    s_lshr_b64 s[10:11], s[0:1], 24
; GFX11-NEXT:    s_lshr_b32 s12, s19, 24
; GFX11-NEXT:    s_lshr_b32 s13, s19, 16
; GFX11-NEXT:    s_lshr_b32 s14, s19, 8
; GFX11-NEXT:    s_lshr_b32 s15, s18, 16
; GFX11-NEXT:    s_lshr_b32 s20, s18, 8
; GFX11-NEXT:    s_lshr_b32 s21, s17, 24
; GFX11-NEXT:    s_lshr_b32 s22, s17, 16
; GFX11-NEXT:    s_lshr_b32 s23, s17, 8
; GFX11-NEXT:    s_lshr_b32 s24, s16, 16
; GFX11-NEXT:    s_lshr_b32 s25, s16, 8
; GFX11-NEXT:    s_lshr_b32 s26, s3, 24
; GFX11-NEXT:    s_lshr_b32 s27, s3, 16
; GFX11-NEXT:    s_lshr_b32 s28, s3, 8
; GFX11-NEXT:    s_lshr_b32 s29, s2, 16
; GFX11-NEXT:    s_lshr_b32 s40, s2, 8
; GFX11-NEXT:    s_lshr_b32 s41, s1, 24
; GFX11-NEXT:    s_lshr_b32 s42, s1, 16
; GFX11-NEXT:    s_lshr_b32 s43, s1, 8
; GFX11-NEXT:    s_lshr_b32 s44, s0, 16
; GFX11-NEXT:    s_lshr_b32 s45, s0, 8
; GFX11-NEXT:  .LBB69_3: ; %end
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s45
; GFX11-NEXT:    v_dual_mov_b32 v2, s44 :: v_dual_mov_b32 v3, s10
; GFX11-NEXT:    v_dual_mov_b32 v4, s1 :: v_dual_mov_b32 v5, s43
; GFX11-NEXT:    v_dual_mov_b32 v6, s42 :: v_dual_mov_b32 v7, s41
; GFX11-NEXT:    v_dual_mov_b32 v8, s2 :: v_dual_mov_b32 v9, s40
; GFX11-NEXT:    v_dual_mov_b32 v10, s29 :: v_dual_mov_b32 v11, s8
; GFX11-NEXT:    v_dual_mov_b32 v12, s3 :: v_dual_mov_b32 v13, s28
; GFX11-NEXT:    v_dual_mov_b32 v14, s27 :: v_dual_mov_b32 v15, s26
; GFX11-NEXT:    v_dual_mov_b32 v16, s16 :: v_dual_mov_b32 v17, s25
; GFX11-NEXT:    v_dual_mov_b32 v18, s24 :: v_dual_mov_b32 v19, s6
; GFX11-NEXT:    v_dual_mov_b32 v20, s17 :: v_dual_mov_b32 v21, s23
; GFX11-NEXT:    v_dual_mov_b32 v22, s22 :: v_dual_mov_b32 v23, s21
; GFX11-NEXT:    v_dual_mov_b32 v24, s18 :: v_dual_mov_b32 v25, s20
; GFX11-NEXT:    v_dual_mov_b32 v26, s15 :: v_dual_mov_b32 v27, s4
; GFX11-NEXT:    v_dual_mov_b32 v28, s19 :: v_dual_mov_b32 v29, s14
; GFX11-NEXT:    v_dual_mov_b32 v30, s13 :: v_dual_mov_b32 v31, s12
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB69_4:
; GFX11-NEXT:    ; implicit-def: $sgpr45
; GFX11-NEXT:    ; implicit-def: $sgpr44
; GFX11-NEXT:    ; implicit-def: $sgpr10
; GFX11-NEXT:    ; implicit-def: $sgpr43
; GFX11-NEXT:    ; implicit-def: $sgpr42
; GFX11-NEXT:    ; implicit-def: $sgpr41
; GFX11-NEXT:    ; implicit-def: $sgpr40
; GFX11-NEXT:    ; implicit-def: $sgpr29
; GFX11-NEXT:    ; implicit-def: $sgpr8
; GFX11-NEXT:    ; implicit-def: $sgpr28
; GFX11-NEXT:    ; implicit-def: $sgpr27
; GFX11-NEXT:    ; implicit-def: $sgpr26
; GFX11-NEXT:    ; implicit-def: $sgpr25
; GFX11-NEXT:    ; implicit-def: $sgpr24
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr23
; GFX11-NEXT:    ; implicit-def: $sgpr22
; GFX11-NEXT:    ; implicit-def: $sgpr21
; GFX11-NEXT:    ; implicit-def: $sgpr20
; GFX11-NEXT:    ; implicit-def: $sgpr15
; GFX11-NEXT:    ; implicit-def: $sgpr4
; GFX11-NEXT:    ; implicit-def: $sgpr14
; GFX11-NEXT:    ; implicit-def: $sgpr13
; GFX11-NEXT:    ; implicit-def: $sgpr12
; GFX11-NEXT:    s_branch .LBB69_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <4 x i64> %a, splat (i64 3)
  %a2 = bitcast <4 x i64> %a1 to <32 x i8>
  br label %end

cmp.false:
  %a3 = bitcast <4 x i64> %a to <32 x i8>
  br label %end

end:
  %phi = phi <32 x i8> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x i8> %phi
}

define <4 x i64> @bitcast_v32i8_to_v4i64(<32 x i8> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v32i8_to_v4i64:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_mov_b32_e32 v32, v2
; SI-NEXT:    v_mov_b32_e32 v31, v0
; SI-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:4
; SI-NEXT:    buffer_load_dword v2, off, s[0:3], s32
; SI-NEXT:    v_mov_b32_e32 v34, v6
; SI-NEXT:    v_mov_b32_e32 v33, v4
; SI-NEXT:    v_lshlrev_b32_e32 v52, 8, v1
; SI-NEXT:    v_lshlrev_b32_e32 v51, 24, v3
; SI-NEXT:    v_lshlrev_b32_e32 v50, 8, v5
; SI-NEXT:    v_lshlrev_b32_e32 v49, 24, v7
; SI-NEXT:    v_lshlrev_b32_e32 v48, 8, v9
; SI-NEXT:    v_lshlrev_b32_e32 v39, 24, v11
; SI-NEXT:    v_lshlrev_b32_e32 v38, 8, v13
; SI-NEXT:    v_lshlrev_b32_e32 v37, 24, v15
; SI-NEXT:    v_lshlrev_b32_e32 v36, 8, v17
; SI-NEXT:    v_lshlrev_b32_e32 v35, 24, v19
; SI-NEXT:    v_lshlrev_b32_e32 v19, 8, v21
; SI-NEXT:    v_lshlrev_b32_e32 v17, 24, v23
; SI-NEXT:    v_lshlrev_b32_e32 v15, 8, v25
; SI-NEXT:    v_lshlrev_b32_e32 v13, 24, v27
; SI-NEXT:    v_lshlrev_b32_e32 v11, 8, v29
; SI-NEXT:    s_waitcnt vmcnt(1)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v0
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_lshlrev_b32_e32 v9, 24, v2
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB70_3
; SI-NEXT:  ; %bb.1: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB70_4
; SI-NEXT:  .LBB70_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB70_3: ; %cmp.false
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v31
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v32
; SI-NEXT:    v_or_b32_e32 v0, v0, v52
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_or_b32_e32 v1, v51, v1
; SI-NEXT:    v_or_b32_e32 v0, v0, v1
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v33
; SI-NEXT:    v_and_b32_e32 v2, 0xff, v34
; SI-NEXT:    v_or_b32_e32 v1, v1, v50
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_or_b32_e32 v2, v49, v2
; SI-NEXT:    v_or_b32_e32 v1, v1, v2
; SI-NEXT:    v_and_b32_e32 v2, 0xff, v8
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v10
; SI-NEXT:    v_or_b32_e32 v2, v2, v48
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_or_b32_e32 v3, v39, v3
; SI-NEXT:    v_or_b32_e32 v2, v2, v3
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v12
; SI-NEXT:    v_and_b32_e32 v4, 0xff, v14
; SI-NEXT:    v_or_b32_e32 v3, v3, v38
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_or_b32_e32 v4, v37, v4
; SI-NEXT:    v_or_b32_e32 v3, v3, v4
; SI-NEXT:    v_and_b32_e32 v4, 0xff, v16
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v18
; SI-NEXT:    v_or_b32_e32 v4, v4, v36
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_or_b32_e32 v5, v35, v5
; SI-NEXT:    v_or_b32_e32 v4, v4, v5
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v20
; SI-NEXT:    v_and_b32_e32 v6, 0xff, v22
; SI-NEXT:    v_or_b32_e32 v5, v5, v19
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_or_b32_e32 v6, v17, v6
; SI-NEXT:    v_or_b32_e32 v5, v5, v6
; SI-NEXT:    v_and_b32_e32 v6, 0xff, v24
; SI-NEXT:    v_and_b32_e32 v7, 0xff, v26
; SI-NEXT:    v_or_b32_e32 v6, v6, v15
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_or_b32_e32 v7, v13, v7
; SI-NEXT:    v_or_b32_e32 v6, v6, v7
; SI-NEXT:    v_and_b32_e32 v7, 0xff, v28
; SI-NEXT:    v_and_b32_e32 v8, 0xff, v30
; SI-NEXT:    v_or_b32_e32 v7, v7, v11
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_or_b32_e32 v8, v9, v8
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    ; implicit-def: $vgpr31
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr24
; SI-NEXT:    ; implicit-def: $vgpr26
; SI-NEXT:    ; implicit-def: $vgpr28
; SI-NEXT:    ; implicit-def: $vgpr30
; SI-NEXT:    ; implicit-def: $vgpr52
; SI-NEXT:    ; implicit-def: $vgpr51
; SI-NEXT:    ; implicit-def: $vgpr50
; SI-NEXT:    ; implicit-def: $vgpr49
; SI-NEXT:    ; implicit-def: $vgpr48
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB70_2
; SI-NEXT:  .LBB70_4: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v31
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v32
; SI-NEXT:    v_or_b32_e32 v0, v52, v0
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v1
; SI-NEXT:    v_add_i32_e32 v0, vcc, 0x300, v0
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_or_b32_e32 v1, v51, v1
; SI-NEXT:    v_or_b32_e32 v0, v1, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v33
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v1
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v34
; SI-NEXT:    s_movk_i32 s6, 0x300
; SI-NEXT:    v_or_b32_e32 v1, v50, v1
; SI-NEXT:    v_and_b32_e32 v2, 0xff, v2
; SI-NEXT:    v_add_i32_e32 v1, vcc, s6, v1
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_or_b32_e32 v2, v49, v2
; SI-NEXT:    v_or_b32_e32 v1, v2, v1
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v8
; SI-NEXT:    v_and_b32_e32 v2, 0xff, v2
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v10
; SI-NEXT:    v_or_b32_e32 v2, v48, v2
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v3
; SI-NEXT:    v_add_i32_e32 v2, vcc, s6, v2
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_or_b32_e32 v3, v39, v3
; SI-NEXT:    v_or_b32_e32 v2, v3, v2
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v12
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v3
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v14
; SI-NEXT:    v_or_b32_e32 v3, v38, v3
; SI-NEXT:    v_and_b32_e32 v4, 0xff, v4
; SI-NEXT:    v_add_i32_e32 v3, vcc, s6, v3
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_or_b32_e32 v4, v37, v4
; SI-NEXT:    v_or_b32_e32 v3, v4, v3
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v16
; SI-NEXT:    v_and_b32_e32 v4, 0xff, v4
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v18
; SI-NEXT:    v_or_b32_e32 v4, v36, v4
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v5
; SI-NEXT:    v_add_i32_e32 v4, vcc, s6, v4
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_or_b32_e32 v5, v35, v5
; SI-NEXT:    v_or_b32_e32 v4, v5, v4
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v20
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v5
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v22
; SI-NEXT:    v_or_b32_e32 v5, v19, v5
; SI-NEXT:    v_and_b32_e32 v6, 0xff, v6
; SI-NEXT:    v_add_i32_e32 v5, vcc, s6, v5
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_or_b32_e32 v6, v17, v6
; SI-NEXT:    v_or_b32_e32 v5, v6, v5
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v24
; SI-NEXT:    v_and_b32_e32 v6, 0xff, v6
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v26
; SI-NEXT:    v_or_b32_e32 v6, v15, v6
; SI-NEXT:    v_and_b32_e32 v7, 0xff, v7
; SI-NEXT:    v_add_i32_e32 v6, vcc, s6, v6
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_or_b32_e32 v7, v13, v7
; SI-NEXT:    v_or_b32_e32 v6, v7, v6
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v28
; SI-NEXT:    v_and_b32_e32 v7, 0xff, v7
; SI-NEXT:    v_add_i32_e32 v8, vcc, 3, v30
; SI-NEXT:    v_or_b32_e32 v7, v11, v7
; SI-NEXT:    v_and_b32_e32 v8, 0xff, v8
; SI-NEXT:    v_add_i32_e32 v7, vcc, 0x300, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_or_b32_e32 v8, v9, v8
; SI-NEXT:    s_mov_b32 s7, 0x3000000
; SI-NEXT:    v_or_b32_e32 v7, v8, v7
; SI-NEXT:    v_add_i32_e32 v0, vcc, s7, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, s7, v1
; SI-NEXT:    v_add_i32_e32 v2, vcc, s7, v2
; SI-NEXT:    v_add_i32_e32 v3, vcc, s7, v3
; SI-NEXT:    v_add_i32_e32 v4, vcc, s7, v4
; SI-NEXT:    v_add_i32_e32 v5, vcc, s7, v5
; SI-NEXT:    v_add_i32_e32 v6, vcc, 0x3000000, v6
; SI-NEXT:    v_add_i32_e32 v7, vcc, 0x3000000, v7
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v32i8_to_v4i64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_mov_b32_e32 v38, v0
; VI-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:4
; VI-NEXT:    buffer_load_ushort v39, off, s[0:3], s32
; VI-NEXT:    v_mov_b32_e32 v31, v7
; VI-NEXT:    v_mov_b32_e32 v32, v6
; VI-NEXT:    v_mov_b32_e32 v33, v5
; VI-NEXT:    v_mov_b32_e32 v34, v4
; VI-NEXT:    v_mov_b32_e32 v35, v3
; VI-NEXT:    v_mov_b32_e32 v36, v2
; VI-NEXT:    v_mov_b32_e32 v37, v1
; VI-NEXT:    s_waitcnt vmcnt(1)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v0
; VI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execnz .LBB70_3
; VI-NEXT:  ; %bb.1: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execnz .LBB70_4
; VI-NEXT:  .LBB70_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB70_3: ; %cmp.false
; VI-NEXT:    s_mov_b32 s6, 0xc0c0004
; VI-NEXT:    v_perm_b32 v1, v36, v35, s6
; VI-NEXT:    v_perm_b32 v0, v38, v37, s6
; VI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_perm_b32 v2, v32, v31, s6
; VI-NEXT:    v_or_b32_e32 v0, v0, v1
; VI-NEXT:    v_perm_b32 v1, v34, v33, s6
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_perm_b32 v3, v10, v11, s6
; VI-NEXT:    v_or_b32_e32 v1, v1, v2
; VI-NEXT:    v_perm_b32 v2, v8, v9, s6
; VI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_perm_b32 v4, v14, v15, s6
; VI-NEXT:    v_or_b32_e32 v2, v2, v3
; VI-NEXT:    v_perm_b32 v3, v12, v13, s6
; VI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_perm_b32 v5, v18, v19, s6
; VI-NEXT:    v_or_b32_e32 v3, v3, v4
; VI-NEXT:    v_perm_b32 v4, v16, v17, s6
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_perm_b32 v6, v22, v23, s6
; VI-NEXT:    v_or_b32_e32 v4, v4, v5
; VI-NEXT:    v_perm_b32 v5, v20, v21, s6
; VI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_perm_b32 v7, v26, v27, s6
; VI-NEXT:    v_or_b32_e32 v5, v5, v6
; VI-NEXT:    v_perm_b32 v6, v24, v25, s6
; VI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    v_perm_b32 v8, v30, v39, s6
; VI-NEXT:    v_or_b32_e32 v6, v6, v7
; VI-NEXT:    v_perm_b32 v7, v28, v29, s6
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; VI-NEXT:    v_or_b32_e32 v7, v7, v8
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr35
; VI-NEXT:    ; implicit-def: $vgpr34
; VI-NEXT:    ; implicit-def: $vgpr33
; VI-NEXT:    ; implicit-def: $vgpr32
; VI-NEXT:    ; implicit-def: $vgpr31
; VI-NEXT:    ; implicit-def: $vgpr8
; VI-NEXT:    ; implicit-def: $vgpr9
; VI-NEXT:    ; implicit-def: $vgpr10
; VI-NEXT:    ; implicit-def: $vgpr11
; VI-NEXT:    ; implicit-def: $vgpr12
; VI-NEXT:    ; implicit-def: $vgpr13
; VI-NEXT:    ; implicit-def: $vgpr14
; VI-NEXT:    ; implicit-def: $vgpr15
; VI-NEXT:    ; implicit-def: $vgpr16
; VI-NEXT:    ; implicit-def: $vgpr17
; VI-NEXT:    ; implicit-def: $vgpr18
; VI-NEXT:    ; implicit-def: $vgpr19
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr21
; VI-NEXT:    ; implicit-def: $vgpr22
; VI-NEXT:    ; implicit-def: $vgpr23
; VI-NEXT:    ; implicit-def: $vgpr24
; VI-NEXT:    ; implicit-def: $vgpr25
; VI-NEXT:    ; implicit-def: $vgpr26
; VI-NEXT:    ; implicit-def: $vgpr27
; VI-NEXT:    ; implicit-def: $vgpr28
; VI-NEXT:    ; implicit-def: $vgpr29
; VI-NEXT:    ; implicit-def: $vgpr30
; VI-NEXT:    ; implicit-def: $vgpr39
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB70_2
; VI-NEXT:  .LBB70_4: ; %cmp.true
; VI-NEXT:    v_add_u16_e32 v0, 3, v38
; VI-NEXT:    v_lshlrev_b16_e32 v1, 8, v37
; VI-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v1, 3, v36
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v35
; VI-NEXT:    v_or_b32_sdwa v1, v2, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_mov_b32_e32 v7, 0x300
; VI-NEXT:    v_add_u16_e32 v2, 3, v34
; VI-NEXT:    v_lshlrev_b16_e32 v3, 8, v33
; VI-NEXT:    v_add_u16_e32 v0, 0x300, v0
; VI-NEXT:    v_add_u16_sdwa v1, v1, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v2, v3, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_or_b32_e32 v0, v0, v1
; VI-NEXT:    v_add_u16_e32 v1, 0x300, v2
; VI-NEXT:    v_add_u16_e32 v2, 3, v32
; VI-NEXT:    v_lshlrev_b16_e32 v3, 8, v31
; VI-NEXT:    v_or_b32_sdwa v2, v3, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_sdwa v2, v2, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v1, v1, v2
; VI-NEXT:    v_add_u16_e32 v2, 3, v8
; VI-NEXT:    v_lshlrev_b16_e32 v3, 8, v9
; VI-NEXT:    v_or_b32_sdwa v2, v3, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v3, 3, v10
; VI-NEXT:    v_lshlrev_b16_e32 v4, 8, v11
; VI-NEXT:    v_or_b32_sdwa v3, v4, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v2, 0x300, v2
; VI-NEXT:    v_add_u16_sdwa v3, v3, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v2, v2, v3
; VI-NEXT:    v_add_u16_e32 v3, 3, v12
; VI-NEXT:    v_lshlrev_b16_e32 v4, 8, v13
; VI-NEXT:    v_or_b32_sdwa v3, v4, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v4, 3, v14
; VI-NEXT:    v_lshlrev_b16_e32 v5, 8, v15
; VI-NEXT:    v_or_b32_sdwa v4, v5, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v3, 0x300, v3
; VI-NEXT:    v_add_u16_sdwa v4, v4, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v3, v3, v4
; VI-NEXT:    v_add_u16_e32 v4, 3, v16
; VI-NEXT:    v_lshlrev_b16_e32 v5, 8, v17
; VI-NEXT:    v_or_b32_sdwa v4, v5, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v5, 3, v18
; VI-NEXT:    v_lshlrev_b16_e32 v6, 8, v19
; VI-NEXT:    v_or_b32_sdwa v5, v6, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v4, 0x300, v4
; VI-NEXT:    v_add_u16_sdwa v5, v5, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v4, v4, v5
; VI-NEXT:    v_add_u16_e32 v5, 3, v20
; VI-NEXT:    v_lshlrev_b16_e32 v6, 8, v21
; VI-NEXT:    v_or_b32_sdwa v5, v6, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v6, 3, v22
; VI-NEXT:    v_lshlrev_b16_e32 v8, 8, v23
; VI-NEXT:    v_or_b32_sdwa v6, v8, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v5, 0x300, v5
; VI-NEXT:    v_add_u16_sdwa v6, v6, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v5, v5, v6
; VI-NEXT:    v_add_u16_e32 v6, 3, v24
; VI-NEXT:    v_lshlrev_b16_e32 v8, 8, v25
; VI-NEXT:    v_or_b32_sdwa v6, v8, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v8, 3, v26
; VI-NEXT:    v_lshlrev_b16_e32 v9, 8, v27
; VI-NEXT:    v_or_b32_sdwa v8, v9, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v6, 0x300, v6
; VI-NEXT:    v_add_u16_sdwa v8, v8, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v6, v6, v8
; VI-NEXT:    v_add_u16_e32 v8, 3, v28
; VI-NEXT:    v_lshlrev_b16_e32 v9, 8, v29
; VI-NEXT:    v_or_b32_sdwa v8, v9, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v9, 3, v30
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    v_lshlrev_b16_e32 v10, 8, v39
; VI-NEXT:    v_or_b32_sdwa v9, v10, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v8, 0x300, v8
; VI-NEXT:    v_add_u16_sdwa v7, v9, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v7, v8, v7
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v32i8_to_v4i64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_mov_b32_e32 v38, v0
; GFX9-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:4
; GFX9-NEXT:    buffer_load_ushort v39, off, s[0:3], s32
; GFX9-NEXT:    v_mov_b32_e32 v31, v7
; GFX9-NEXT:    v_mov_b32_e32 v32, v6
; GFX9-NEXT:    v_mov_b32_e32 v33, v5
; GFX9-NEXT:    v_mov_b32_e32 v34, v4
; GFX9-NEXT:    v_mov_b32_e32 v35, v3
; GFX9-NEXT:    v_mov_b32_e32 v36, v2
; GFX9-NEXT:    v_mov_b32_e32 v37, v1
; GFX9-NEXT:    s_waitcnt vmcnt(1)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v0
; GFX9-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execnz .LBB70_3
; GFX9-NEXT:  ; %bb.1: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execnz .LBB70_4
; GFX9-NEXT:  .LBB70_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB70_3: ; %cmp.false
; GFX9-NEXT:    s_mov_b32 s6, 0xc0c0004
; GFX9-NEXT:    v_perm_b32 v0, v38, v37, s6
; GFX9-NEXT:    v_perm_b32 v1, v36, v35, s6
; GFX9-NEXT:    v_lshl_or_b32 v0, v1, 16, v0
; GFX9-NEXT:    v_perm_b32 v1, v34, v33, s6
; GFX9-NEXT:    v_perm_b32 v2, v32, v31, s6
; GFX9-NEXT:    v_lshl_or_b32 v1, v2, 16, v1
; GFX9-NEXT:    v_perm_b32 v2, v8, v9, s6
; GFX9-NEXT:    v_perm_b32 v3, v10, v11, s6
; GFX9-NEXT:    v_lshl_or_b32 v2, v3, 16, v2
; GFX9-NEXT:    v_perm_b32 v3, v12, v13, s6
; GFX9-NEXT:    v_perm_b32 v4, v14, v15, s6
; GFX9-NEXT:    v_lshl_or_b32 v3, v4, 16, v3
; GFX9-NEXT:    v_perm_b32 v4, v16, v17, s6
; GFX9-NEXT:    v_perm_b32 v5, v18, v19, s6
; GFX9-NEXT:    v_lshl_or_b32 v4, v5, 16, v4
; GFX9-NEXT:    v_perm_b32 v5, v20, v21, s6
; GFX9-NEXT:    v_perm_b32 v6, v22, v23, s6
; GFX9-NEXT:    v_lshl_or_b32 v5, v6, 16, v5
; GFX9-NEXT:    v_perm_b32 v6, v24, v25, s6
; GFX9-NEXT:    v_perm_b32 v7, v26, v27, s6
; GFX9-NEXT:    v_lshl_or_b32 v6, v7, 16, v6
; GFX9-NEXT:    v_perm_b32 v7, v28, v29, s6
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    v_perm_b32 v8, v30, v39, s6
; GFX9-NEXT:    v_lshl_or_b32 v7, v8, 16, v7
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr35
; GFX9-NEXT:    ; implicit-def: $vgpr34
; GFX9-NEXT:    ; implicit-def: $vgpr33
; GFX9-NEXT:    ; implicit-def: $vgpr32
; GFX9-NEXT:    ; implicit-def: $vgpr31
; GFX9-NEXT:    ; implicit-def: $vgpr8
; GFX9-NEXT:    ; implicit-def: $vgpr9
; GFX9-NEXT:    ; implicit-def: $vgpr10
; GFX9-NEXT:    ; implicit-def: $vgpr11
; GFX9-NEXT:    ; implicit-def: $vgpr12
; GFX9-NEXT:    ; implicit-def: $vgpr13
; GFX9-NEXT:    ; implicit-def: $vgpr14
; GFX9-NEXT:    ; implicit-def: $vgpr15
; GFX9-NEXT:    ; implicit-def: $vgpr16
; GFX9-NEXT:    ; implicit-def: $vgpr17
; GFX9-NEXT:    ; implicit-def: $vgpr18
; GFX9-NEXT:    ; implicit-def: $vgpr19
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr21
; GFX9-NEXT:    ; implicit-def: $vgpr22
; GFX9-NEXT:    ; implicit-def: $vgpr23
; GFX9-NEXT:    ; implicit-def: $vgpr24
; GFX9-NEXT:    ; implicit-def: $vgpr25
; GFX9-NEXT:    ; implicit-def: $vgpr26
; GFX9-NEXT:    ; implicit-def: $vgpr27
; GFX9-NEXT:    ; implicit-def: $vgpr28
; GFX9-NEXT:    ; implicit-def: $vgpr29
; GFX9-NEXT:    ; implicit-def: $vgpr30
; GFX9-NEXT:    ; implicit-def: $vgpr39
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB70_2
; GFX9-NEXT:  .LBB70_4: ; %cmp.true
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v38
; GFX9-NEXT:    v_lshlrev_b16_e32 v1, 8, v37
; GFX9-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v1, 3, v36
; GFX9-NEXT:    v_lshlrev_b16_e32 v2, 8, v35
; GFX9-NEXT:    s_movk_i32 s6, 0x300
; GFX9-NEXT:    v_or_b32_sdwa v1, v2, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v0, 0x300, v0
; GFX9-NEXT:    v_add_u16_sdwa v1, v1, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v0, v0, v1
; GFX9-NEXT:    v_add_u16_e32 v1, 3, v34
; GFX9-NEXT:    v_lshlrev_b16_e32 v2, 8, v33
; GFX9-NEXT:    v_or_b32_sdwa v1, v2, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v2, 3, v32
; GFX9-NEXT:    v_lshlrev_b16_e32 v3, 8, v31
; GFX9-NEXT:    v_or_b32_sdwa v2, v3, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v1, 0x300, v1
; GFX9-NEXT:    v_add_u16_sdwa v2, v2, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v1, v1, v2
; GFX9-NEXT:    v_add_u16_e32 v2, 3, v8
; GFX9-NEXT:    v_lshlrev_b16_e32 v3, 8, v9
; GFX9-NEXT:    v_or_b32_sdwa v2, v3, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v3, 3, v10
; GFX9-NEXT:    v_lshlrev_b16_e32 v4, 8, v11
; GFX9-NEXT:    v_or_b32_sdwa v3, v4, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v2, 0x300, v2
; GFX9-NEXT:    v_add_u16_sdwa v3, v3, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v2, v2, v3
; GFX9-NEXT:    v_add_u16_e32 v3, 3, v12
; GFX9-NEXT:    v_lshlrev_b16_e32 v4, 8, v13
; GFX9-NEXT:    v_or_b32_sdwa v3, v4, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v4, 3, v14
; GFX9-NEXT:    v_lshlrev_b16_e32 v5, 8, v15
; GFX9-NEXT:    v_or_b32_sdwa v4, v5, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v3, 0x300, v3
; GFX9-NEXT:    v_add_u16_sdwa v4, v4, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v3, v3, v4
; GFX9-NEXT:    v_add_u16_e32 v4, 3, v16
; GFX9-NEXT:    v_lshlrev_b16_e32 v5, 8, v17
; GFX9-NEXT:    v_or_b32_sdwa v4, v5, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v5, 3, v18
; GFX9-NEXT:    v_lshlrev_b16_e32 v6, 8, v19
; GFX9-NEXT:    v_or_b32_sdwa v5, v6, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v4, 0x300, v4
; GFX9-NEXT:    v_add_u16_sdwa v5, v5, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v4, v4, v5
; GFX9-NEXT:    v_add_u16_e32 v5, 3, v20
; GFX9-NEXT:    v_lshlrev_b16_e32 v6, 8, v21
; GFX9-NEXT:    v_or_b32_sdwa v5, v6, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v6, 3, v22
; GFX9-NEXT:    v_lshlrev_b16_e32 v7, 8, v23
; GFX9-NEXT:    v_or_b32_sdwa v6, v7, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v5, 0x300, v5
; GFX9-NEXT:    v_add_u16_sdwa v6, v6, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v5, v5, v6
; GFX9-NEXT:    v_add_u16_e32 v6, 3, v24
; GFX9-NEXT:    v_lshlrev_b16_e32 v7, 8, v25
; GFX9-NEXT:    v_or_b32_sdwa v6, v7, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v7, 3, v26
; GFX9-NEXT:    v_lshlrev_b16_e32 v8, 8, v27
; GFX9-NEXT:    v_or_b32_sdwa v7, v8, v7 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v6, 0x300, v6
; GFX9-NEXT:    v_add_u16_sdwa v7, v7, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v6, v6, v7
; GFX9-NEXT:    v_add_u16_e32 v7, 3, v28
; GFX9-NEXT:    v_lshlrev_b16_e32 v8, 8, v29
; GFX9-NEXT:    v_or_b32_sdwa v7, v8, v7 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v8, 3, v30
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    v_lshlrev_b16_e32 v9, 8, v39
; GFX9-NEXT:    v_or_b32_sdwa v8, v9, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v7, 0x300, v7
; GFX9-NEXT:    v_add_u16_sdwa v8, v8, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v7, v7, v8
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v32i8_to_v4i64:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_clause 0x1
; GFX11-TRUE16-NEXT:    scratch_load_b32 v48, off, s32 offset:4
; GFX11-TRUE16-NEXT:    scratch_load_d16_b16 v31, off, s32
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v32.l, v7.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v33.l, v6.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v34.l, v5.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v35.l, v4.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v36.l, v3.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v37.l, v2.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v38.l, v1.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v39.l, v0.l
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(1)
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v48
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB70_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB70_4
; GFX11-TRUE16-NEXT:  .LBB70_2: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB70_3: ; %cmp.false
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr39_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr38_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v0, v39, v38, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr37_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr36_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, v37, v36, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr35_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr34_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v2, v35, v34, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr33_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr32_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v3, v33, v32, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr8_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v4, v8, v9, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr10_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr11_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, v10, v11, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr12_hi16
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v0, v1, 16, v0
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr14_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr15_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr16_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr17_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr18_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr19_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v6, v18, v19, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v1, v3, 16, v2
; GFX11-TRUE16-NEXT:    v_perm_b32 v3, v12, v13, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v2, v5, 16, v4
; GFX11-TRUE16-NEXT:    v_perm_b32 v4, v14, v15, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, v16, v17, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr21_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v7, v20, v21, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr22_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr23_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v8, v22, v23, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr24_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr25_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v9, v24, v25, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr26_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr27_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v10, v26, v27, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr28_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr29_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v11, v28, v29, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr30_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr31_hi16
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-TRUE16-NEXT:    v_perm_b32 v12, v30, v31, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v3, v4, 16, v3
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v4, v6, 16, v5
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v5, v8, 16, v7
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v6, v10, 16, v9
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v7, v12, 16, v11
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr39_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr38_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr37_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr36_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr35_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr34_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr33_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr32_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr8_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr10_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr11_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr12_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr14_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr15_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr16_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr17_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr18_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr19_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr21_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr22_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr23_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr24_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr25_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr26_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr27_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr28_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr29_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr30_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr31_lo16
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB70_2
; GFX11-TRUE16-NEXT:  .LBB70_4: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.l, v39.l, 3
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v0.h, 8, v38.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.l, v37.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.l, v35.l, 3
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v1.h, 8, v36.l
; GFX11-TRUE16-NEXT:    v_and_b16 v0.l, 0xff, v0.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v2.h, 8, v34.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v3.l, v33.l, 3
; GFX11-TRUE16-NEXT:    v_and_b16 v1.l, 0xff, v1.l
; GFX11-TRUE16-NEXT:    v_and_b16 v2.l, 0xff, v2.l
; GFX11-TRUE16-NEXT:    v_or_b16 v0.l, v0.h, v0.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.h, v8.l, 3
; GFX11-TRUE16-NEXT:    v_and_b16 v3.l, 0xff, v3.l
; GFX11-TRUE16-NEXT:    v_or_b16 v1.l, v1.h, v1.l
; GFX11-TRUE16-NEXT:    v_or_b16 v1.h, v2.h, v2.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v2.l, 8, v32.l
; GFX11-TRUE16-NEXT:    v_and_b16 v2.h, 0xff, v0.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v3.h, 8, v9.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v4.l, v10.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.h, 0x300, v1.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.l, 0x300, v1.h
; GFX11-TRUE16-NEXT:    v_or_b16 v1.h, v2.l, v3.l
; GFX11-TRUE16-NEXT:    v_or_b16 v2.l, v3.h, v2.h
; GFX11-TRUE16-NEXT:    v_and_b16 v2.h, 0xff, v4.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v3.l, 8, v11.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v3.h, v12.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v4.l, v14.l, 3
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v4.h, 8, v15.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v5.l, v16.l, 3
; GFX11-TRUE16-NEXT:    v_or_b16 v2.h, v3.l, v2.h
; GFX11-TRUE16-NEXT:    v_and_b16 v3.l, 0xff, v3.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v3.h, 8, v13.l
; GFX11-TRUE16-NEXT:    v_and_b16 v4.l, 0xff, v4.l
; GFX11-TRUE16-NEXT:    v_and_b16 v5.l, 0xff, v5.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v5.h, 8, v17.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v6.l, 8, v19.l
; GFX11-TRUE16-NEXT:    v_or_b16 v3.l, v3.h, v3.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v3.h, v18.l, 3
; GFX11-TRUE16-NEXT:    v_or_b16 v4.l, v4.h, v4.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v4.h, v20.l, 3
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v6.h, 8, v21.l
; GFX11-TRUE16-NEXT:    v_or_b16 v5.l, v5.h, v5.l
; GFX11-TRUE16-NEXT:    v_and_b16 v3.h, 0xff, v3.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v7.l, v26.l, 3
; GFX11-TRUE16-NEXT:    v_and_b16 v4.h, 0xff, v4.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v7.h, v28.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v8.h, v30.l, 3
; GFX11-TRUE16-NEXT:    v_or_b16 v5.h, v6.l, v3.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v3.h, 0x300, v4.l
; GFX11-TRUE16-NEXT:    v_or_b16 v6.l, v6.h, v4.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v6.h, v22.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v4.l, 0x300, v5.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v4.h, 0x300, v5.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v5.h, v24.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v5.l, 0x300, v6.l
; GFX11-TRUE16-NEXT:    v_and_b16 v6.l, 0xff, v6.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v6.h, 8, v23.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v8.l, 8, v25.l
; GFX11-TRUE16-NEXT:    v_and_b16 v5.h, 0xff, v5.h
; GFX11-TRUE16-NEXT:    v_and_b16 v7.l, 0xff, v7.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v9.l, 8, v27.l
; GFX11-TRUE16-NEXT:    v_and_b16 v7.h, 0xff, v7.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v9.h, 8, v29.l
; GFX11-TRUE16-NEXT:    v_and_b16 v8.h, 0xff, v8.h
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v10.l, 8, v31.l
; GFX11-TRUE16-NEXT:    v_or_b16 v6.l, v6.h, v6.l
; GFX11-TRUE16-NEXT:    v_or_b16 v6.h, v8.l, v5.h
; GFX11-TRUE16-NEXT:    v_or_b16 v7.l, v9.l, v7.l
; GFX11-TRUE16-NEXT:    v_or_b16 v7.h, v9.h, v7.h
; GFX11-TRUE16-NEXT:    v_or_b16 v8.l, v10.l, v8.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.l, 0x300, v0.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.h, 0x300, v1.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.l, 0x300, v2.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.h, 0x300, v2.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v3.l, 0x300, v3.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v5.h, 0x300, v6.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v6.l, 0x300, v6.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v6.h, 0x300, v7.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v7.l, 0x300, v7.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v7.h, 0x300, v8.l
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v32i8_to_v4i64:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v37, v1 :: v_dual_mov_b32 v38, v0
; GFX11-FAKE16-NEXT:    s_clause 0x1
; GFX11-FAKE16-NEXT:    scratch_load_b32 v0, off, s32 offset:4
; GFX11-FAKE16-NEXT:    scratch_load_u16 v39, off, s32
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v31, v7 :: v_dual_mov_b32 v32, v6
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v33, v5 :: v_dual_mov_b32 v34, v4
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v35, v3 :: v_dual_mov_b32 v36, v2
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(1)
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v0
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB70_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB70_4
; GFX11-FAKE16-NEXT:  .LBB70_2: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB70_3: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v38, v37, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v36, v35, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v34, v33, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v32, v31, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v8, v9, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v10, v11, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v0, v1, 16, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v18, v19, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v1, v3, 16, v2
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v12, v13, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v2, v5, 16, v4
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v14, v15, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v16, v17, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v20, v21, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, v22, v23, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, v24, v25, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, v26, v27, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, v28, v29, 0xc0c0004
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, v30, v39, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v3, v4, 16, v3
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v4, v6, 16, v5
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v5, v8, 16, v7
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v6, v10, 16, v9
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v7, v12, 16, v11
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr38
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr37
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr36
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr35
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr34
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr33
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr32
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr31
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr8
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr9
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr10
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr11
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr12
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr13
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr14
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr15
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr16
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr17
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr18
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr19
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr21
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr22
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr23
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr24
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr25
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr26
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr27
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr28
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr29
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr30
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr39
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB70_2
; GFX11-FAKE16-NEXT:  .LBB70_4: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v0, v38, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v2, v36, 3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v1, 8, v37
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v3, 8, v35
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v4, v34, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xff, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v6, v32, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xff, v2
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v5, 8, v33
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v7, 8, v31
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v1, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v1, v8, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xff, v4
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v6, 0xff, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, v3, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, v10, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v0, 0x300, v0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, v5, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v5, v7, v6
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v2, 0x300, v2
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v1, 0xff, v1
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v6, 8, v9
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xff, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v7, 8, v11
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v1, v6, v1
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v4, 0x300, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v7, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v5, 0x300, v5
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v0, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v2, 0x300, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, 0x300, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v6, v12, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v8, 8, v17
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v1, v4, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v4, v14, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xff, v6
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v6, 8, v13
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, v2, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, v16, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xff, v4
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v7, 8, v15
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v5, v6, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v6, v18, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xff, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v9, 8, v19
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, v7, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v7, v20, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v6, 0xff, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v8, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v10, 8, v21
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v8, v22, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v7, 0xff, v7
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v6, v9, v6
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, 0x300, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v11, v26, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v12, v28, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v14, v30, 3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v7, v10, v7
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v9, 0xffff, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, v24, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v8, 0xff, v8
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v10, 8, v23
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v13, 8, v25
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v11, 0xff, v11
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xff, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v15, 8, v27
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v12, 0xff, v12
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v16, 8, v29
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v14, 0xff, v14
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v17, 8, v39
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v8, v10, v8
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v13, v3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v10, v15, v11
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, v16, v12
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, v17, v14
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v5, 0x300, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v4, 0x300, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v6, 0x300, v6
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v7, 0x300, v7
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v8, 0x300, v8
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, 0x300, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v10, 0x300, v10
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v11, 0x300, v11
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v12, 0x300, v12
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v13, 0xffff, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v10, 16, v10
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v12, 16, v12
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v5, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, v9, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v5, v7, v8
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v6, v13, v10
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v7, v11, v12
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <32 x i8> %a, splat (i8 3)
  %a2 = bitcast <32 x i8> %a1 to <4 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <32 x i8> %a to <4 x i64>
  br label %end

end:
  %phi = phi <4 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x i64> %phi
}

define inreg <4 x i64> @bitcast_v32i8_to_v4i64_scalar(<32 x i8> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v32i8_to_v4i64_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_readfirstlane_b32 s4, v18
; SI-NEXT:    v_readfirstlane_b32 s14, v17
; SI-NEXT:    v_readfirstlane_b32 s15, v16
; SI-NEXT:    v_readfirstlane_b32 s40, v15
; SI-NEXT:    v_readfirstlane_b32 s41, v14
; SI-NEXT:    v_readfirstlane_b32 s42, v13
; SI-NEXT:    v_readfirstlane_b32 s43, v12
; SI-NEXT:    v_readfirstlane_b32 s44, v11
; SI-NEXT:    v_readfirstlane_b32 s45, v10
; SI-NEXT:    v_readfirstlane_b32 s46, v9
; SI-NEXT:    v_readfirstlane_b32 s47, v8
; SI-NEXT:    v_readfirstlane_b32 s56, v7
; SI-NEXT:    v_readfirstlane_b32 s57, v6
; SI-NEXT:    v_readfirstlane_b32 s58, v5
; SI-NEXT:    v_readfirstlane_b32 s59, v4
; SI-NEXT:    v_readfirstlane_b32 s60, v3
; SI-NEXT:    v_readfirstlane_b32 s61, v2
; SI-NEXT:    v_readfirstlane_b32 s62, v1
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    v_readfirstlane_b32 s63, v0
; SI-NEXT:    s_cbranch_scc0 .LBB71_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s4, s16, 0xff
; SI-NEXT:    s_lshl_b32 s5, s17, 8
; SI-NEXT:    s_or_b32 s4, s4, s5
; SI-NEXT:    s_and_b32 s5, s18, 0xff
; SI-NEXT:    s_lshl_b32 s5, s5, 16
; SI-NEXT:    s_lshl_b32 s6, s19, 24
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_or_b32 s5, s6, s5
; SI-NEXT:    s_or_b32 s4, s4, s5
; SI-NEXT:    s_and_b32 s5, s20, 0xff
; SI-NEXT:    s_lshl_b32 s6, s21, 8
; SI-NEXT:    s_or_b32 s5, s5, s6
; SI-NEXT:    s_and_b32 s6, s22, 0xff
; SI-NEXT:    s_lshl_b32 s6, s6, 16
; SI-NEXT:    s_lshl_b32 s7, s23, 24
; SI-NEXT:    s_and_b32 s5, s5, 0xffff
; SI-NEXT:    s_or_b32 s6, s7, s6
; SI-NEXT:    s_or_b32 s5, s5, s6
; SI-NEXT:    s_and_b32 s6, s24, 0xff
; SI-NEXT:    s_lshl_b32 s7, s25, 8
; SI-NEXT:    s_or_b32 s6, s6, s7
; SI-NEXT:    s_and_b32 s7, s26, 0xff
; SI-NEXT:    s_lshl_b32 s7, s7, 16
; SI-NEXT:    s_lshl_b32 s8, s27, 24
; SI-NEXT:    s_and_b32 s6, s6, 0xffff
; SI-NEXT:    s_or_b32 s7, s8, s7
; SI-NEXT:    s_or_b32 s6, s6, s7
; SI-NEXT:    s_and_b32 s7, s28, 0xff
; SI-NEXT:    s_lshl_b32 s8, s29, 8
; SI-NEXT:    s_or_b32 s7, s7, s8
; SI-NEXT:    s_and_b32 s8, s63, 0xff
; SI-NEXT:    s_lshl_b32 s8, s8, 16
; SI-NEXT:    s_lshl_b32 s9, s62, 24
; SI-NEXT:    s_and_b32 s7, s7, 0xffff
; SI-NEXT:    s_or_b32 s8, s9, s8
; SI-NEXT:    s_or_b32 s7, s7, s8
; SI-NEXT:    s_and_b32 s8, s61, 0xff
; SI-NEXT:    s_lshl_b32 s9, s60, 8
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_and_b32 s9, s59, 0xff
; SI-NEXT:    s_lshl_b32 s9, s9, 16
; SI-NEXT:    s_lshl_b32 s10, s58, 24
; SI-NEXT:    s_and_b32 s8, s8, 0xffff
; SI-NEXT:    s_or_b32 s9, s10, s9
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_and_b32 s9, s57, 0xff
; SI-NEXT:    s_lshl_b32 s10, s56, 8
; SI-NEXT:    s_or_b32 s9, s9, s10
; SI-NEXT:    s_and_b32 s10, s47, 0xff
; SI-NEXT:    s_lshl_b32 s10, s10, 16
; SI-NEXT:    s_lshl_b32 s11, s46, 24
; SI-NEXT:    s_and_b32 s9, s9, 0xffff
; SI-NEXT:    s_or_b32 s10, s11, s10
; SI-NEXT:    s_or_b32 s9, s9, s10
; SI-NEXT:    s_and_b32 s10, s45, 0xff
; SI-NEXT:    s_lshl_b32 s11, s44, 8
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_and_b32 s11, s43, 0xff
; SI-NEXT:    s_lshl_b32 s11, s11, 16
; SI-NEXT:    s_lshl_b32 s12, s42, 24
; SI-NEXT:    s_and_b32 s10, s10, 0xffff
; SI-NEXT:    s_or_b32 s11, s12, s11
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_and_b32 s11, s41, 0xff
; SI-NEXT:    s_lshl_b32 s12, s40, 8
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    s_and_b32 s12, s15, 0xff
; SI-NEXT:    s_lshl_b32 s12, s12, 16
; SI-NEXT:    s_lshl_b32 s13, s14, 24
; SI-NEXT:    s_and_b32 s11, s11, 0xffff
; SI-NEXT:    s_or_b32 s12, s13, s12
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    s_cbranch_execnz .LBB71_3
; SI-NEXT:  .LBB71_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    s_and_b32 s4, s16, 0xff
; SI-NEXT:    s_lshl_b32 s5, s17, 8
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_and_b32 s6, s18, 0xff
; SI-NEXT:    s_addk_i32 s4, 0x300
; SI-NEXT:    s_lshl_b32 s5, s19, 24
; SI-NEXT:    s_lshl_b32 s6, s6, 16
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_or_b32 s5, s5, s6
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_and_b32 s5, s20, 0xff
; SI-NEXT:    s_lshl_b32 s6, s21, 8
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_or_b32 s5, s6, s5
; SI-NEXT:    s_and_b32 s7, s22, 0xff
; SI-NEXT:    s_addk_i32 s5, 0x300
; SI-NEXT:    s_lshl_b32 s6, s23, 24
; SI-NEXT:    s_lshl_b32 s7, s7, 16
; SI-NEXT:    s_and_b32 s5, s5, 0xffff
; SI-NEXT:    s_or_b32 s6, s6, s7
; SI-NEXT:    s_add_i32 s24, s24, 3
; SI-NEXT:    s_or_b32 s5, s6, s5
; SI-NEXT:    s_and_b32 s6, s24, 0xff
; SI-NEXT:    s_lshl_b32 s7, s25, 8
; SI-NEXT:    s_add_i32 s26, s26, 3
; SI-NEXT:    s_or_b32 s6, s7, s6
; SI-NEXT:    s_and_b32 s8, s26, 0xff
; SI-NEXT:    s_addk_i32 s6, 0x300
; SI-NEXT:    s_lshl_b32 s7, s27, 24
; SI-NEXT:    s_lshl_b32 s8, s8, 16
; SI-NEXT:    s_and_b32 s6, s6, 0xffff
; SI-NEXT:    s_or_b32 s7, s7, s8
; SI-NEXT:    s_add_i32 s28, s28, 3
; SI-NEXT:    s_or_b32 s6, s7, s6
; SI-NEXT:    s_and_b32 s7, s28, 0xff
; SI-NEXT:    s_lshl_b32 s8, s29, 8
; SI-NEXT:    s_add_i32 s63, s63, 3
; SI-NEXT:    s_or_b32 s7, s8, s7
; SI-NEXT:    s_and_b32 s9, s63, 0xff
; SI-NEXT:    s_addk_i32 s7, 0x300
; SI-NEXT:    s_lshl_b32 s8, s62, 24
; SI-NEXT:    s_lshl_b32 s9, s9, 16
; SI-NEXT:    s_and_b32 s7, s7, 0xffff
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_add_i32 s61, s61, 3
; SI-NEXT:    s_or_b32 s7, s8, s7
; SI-NEXT:    s_and_b32 s8, s61, 0xff
; SI-NEXT:    s_lshl_b32 s9, s60, 8
; SI-NEXT:    s_add_i32 s59, s59, 3
; SI-NEXT:    s_or_b32 s8, s9, s8
; SI-NEXT:    s_and_b32 s10, s59, 0xff
; SI-NEXT:    s_addk_i32 s8, 0x300
; SI-NEXT:    s_lshl_b32 s9, s58, 24
; SI-NEXT:    s_lshl_b32 s10, s10, 16
; SI-NEXT:    s_and_b32 s8, s8, 0xffff
; SI-NEXT:    s_or_b32 s9, s9, s10
; SI-NEXT:    s_add_i32 s57, s57, 3
; SI-NEXT:    s_or_b32 s8, s9, s8
; SI-NEXT:    s_and_b32 s9, s57, 0xff
; SI-NEXT:    s_lshl_b32 s10, s56, 8
; SI-NEXT:    s_add_i32 s47, s47, 3
; SI-NEXT:    s_or_b32 s9, s10, s9
; SI-NEXT:    s_and_b32 s11, s47, 0xff
; SI-NEXT:    s_addk_i32 s9, 0x300
; SI-NEXT:    s_lshl_b32 s10, s46, 24
; SI-NEXT:    s_lshl_b32 s11, s11, 16
; SI-NEXT:    s_and_b32 s9, s9, 0xffff
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_add_i32 s45, s45, 3
; SI-NEXT:    s_or_b32 s9, s10, s9
; SI-NEXT:    s_and_b32 s10, s45, 0xff
; SI-NEXT:    s_lshl_b32 s11, s44, 8
; SI-NEXT:    s_add_i32 s43, s43, 3
; SI-NEXT:    s_or_b32 s10, s11, s10
; SI-NEXT:    s_and_b32 s12, s43, 0xff
; SI-NEXT:    s_addk_i32 s10, 0x300
; SI-NEXT:    s_lshl_b32 s11, s42, 24
; SI-NEXT:    s_lshl_b32 s12, s12, 16
; SI-NEXT:    s_and_b32 s10, s10, 0xffff
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    s_add_i32 s41, s41, 3
; SI-NEXT:    s_or_b32 s10, s11, s10
; SI-NEXT:    s_and_b32 s11, s41, 0xff
; SI-NEXT:    s_lshl_b32 s12, s40, 8
; SI-NEXT:    s_add_i32 s15, s15, 3
; SI-NEXT:    s_or_b32 s11, s12, s11
; SI-NEXT:    s_and_b32 s13, s15, 0xff
; SI-NEXT:    s_addk_i32 s11, 0x300
; SI-NEXT:    s_lshl_b32 s12, s14, 24
; SI-NEXT:    s_lshl_b32 s13, s13, 16
; SI-NEXT:    s_and_b32 s11, s11, 0xffff
; SI-NEXT:    s_or_b32 s12, s12, s13
; SI-NEXT:    s_or_b32 s11, s12, s11
; SI-NEXT:    s_add_i32 s4, s4, 0x3000000
; SI-NEXT:    s_add_i32 s5, s5, 0x3000000
; SI-NEXT:    s_add_i32 s6, s6, 0x3000000
; SI-NEXT:    s_add_i32 s7, s7, 0x3000000
; SI-NEXT:    s_add_i32 s8, s8, 0x3000000
; SI-NEXT:    s_add_i32 s9, s9, 0x3000000
; SI-NEXT:    s_add_i32 s10, s10, 0x3000000
; SI-NEXT:    s_add_i32 s11, s11, 0x3000000
; SI-NEXT:  .LBB71_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v0, s4
; SI-NEXT:    v_mov_b32_e32 v1, s5
; SI-NEXT:    v_mov_b32_e32 v2, s6
; SI-NEXT:    v_mov_b32_e32 v3, s7
; SI-NEXT:    v_mov_b32_e32 v4, s8
; SI-NEXT:    v_mov_b32_e32 v5, s9
; SI-NEXT:    v_mov_b32_e32 v6, s10
; SI-NEXT:    v_mov_b32_e32 v7, s11
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB71_4:
; SI-NEXT:    ; implicit-def: $sgpr4_sgpr5_sgpr6_sgpr7_sgpr8_sgpr9_sgpr10_sgpr11
; SI-NEXT:    s_branch .LBB71_2
;
; VI-LABEL: bitcast_v32i8_to_v4i64_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_readfirstlane_b32 s4, v18
; VI-NEXT:    v_readfirstlane_b32 s6, v17
; VI-NEXT:    v_readfirstlane_b32 s7, v16
; VI-NEXT:    v_readfirstlane_b32 s8, v15
; VI-NEXT:    v_readfirstlane_b32 s9, v14
; VI-NEXT:    v_readfirstlane_b32 s10, v13
; VI-NEXT:    v_readfirstlane_b32 s11, v12
; VI-NEXT:    v_readfirstlane_b32 s12, v11
; VI-NEXT:    v_readfirstlane_b32 s13, v10
; VI-NEXT:    v_readfirstlane_b32 s14, v9
; VI-NEXT:    v_readfirstlane_b32 s15, v8
; VI-NEXT:    v_readfirstlane_b32 s40, v7
; VI-NEXT:    v_readfirstlane_b32 s41, v6
; VI-NEXT:    v_readfirstlane_b32 s42, v5
; VI-NEXT:    v_readfirstlane_b32 s43, v4
; VI-NEXT:    v_readfirstlane_b32 s44, v3
; VI-NEXT:    v_readfirstlane_b32 s45, v2
; VI-NEXT:    v_readfirstlane_b32 s46, v1
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    v_readfirstlane_b32 s47, v0
; VI-NEXT:    s_cbranch_scc0 .LBB71_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_mov_b32_e32 v7, 0xc0c0004
; VI-NEXT:    v_mov_b32_e32 v1, s19
; VI-NEXT:    v_mov_b32_e32 v0, s17
; VI-NEXT:    v_perm_b32 v1, s18, v1, v7
; VI-NEXT:    v_perm_b32 v0, s16, v0, v7
; VI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_mov_b32_e32 v2, s23
; VI-NEXT:    v_or_b32_e32 v0, v0, v1
; VI-NEXT:    v_mov_b32_e32 v1, s21
; VI-NEXT:    v_perm_b32 v2, s22, v2, v7
; VI-NEXT:    v_perm_b32 v1, s20, v1, v7
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_mov_b32_e32 v3, s27
; VI-NEXT:    v_or_b32_e32 v1, v1, v2
; VI-NEXT:    v_mov_b32_e32 v2, s25
; VI-NEXT:    v_perm_b32 v3, s26, v3, v7
; VI-NEXT:    v_perm_b32 v2, s24, v2, v7
; VI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_mov_b32_e32 v4, s46
; VI-NEXT:    v_or_b32_e32 v2, v2, v3
; VI-NEXT:    v_mov_b32_e32 v3, s29
; VI-NEXT:    v_perm_b32 v4, s47, v4, v7
; VI-NEXT:    v_perm_b32 v3, s28, v3, v7
; VI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_mov_b32_e32 v5, s42
; VI-NEXT:    v_or_b32_e32 v3, v3, v4
; VI-NEXT:    v_mov_b32_e32 v4, s44
; VI-NEXT:    v_perm_b32 v5, s43, v5, v7
; VI-NEXT:    v_perm_b32 v4, s45, v4, v7
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_mov_b32_e32 v6, s14
; VI-NEXT:    v_or_b32_e32 v4, v4, v5
; VI-NEXT:    v_mov_b32_e32 v5, s40
; VI-NEXT:    v_perm_b32 v6, s15, v6, v7
; VI-NEXT:    v_perm_b32 v5, s41, v5, v7
; VI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_mov_b32_e32 v8, s10
; VI-NEXT:    v_or_b32_e32 v5, v5, v6
; VI-NEXT:    v_mov_b32_e32 v6, s12
; VI-NEXT:    v_perm_b32 v8, s11, v8, v7
; VI-NEXT:    v_perm_b32 v6, s13, v6, v7
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; VI-NEXT:    v_or_b32_e32 v6, v6, v8
; VI-NEXT:    v_mov_b32_e32 v8, s8
; VI-NEXT:    v_mov_b32_e32 v9, s6
; VI-NEXT:    v_perm_b32 v8, s9, v8, v7
; VI-NEXT:    v_perm_b32 v7, s7, v9, v7
; VI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; VI-NEXT:    v_or_b32_e32 v7, v8, v7
; VI-NEXT:    s_cbranch_execnz .LBB71_3
; VI-NEXT:  .LBB71_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s16, s16, 3
; VI-NEXT:    v_mov_b32_e32 v0, s17
; VI-NEXT:    v_mov_b32_e32 v7, 0xc0c0004
; VI-NEXT:    s_add_i32 s18, s18, 3
; VI-NEXT:    v_mov_b32_e32 v1, s19
; VI-NEXT:    v_perm_b32 v0, s16, v0, v7
; VI-NEXT:    v_perm_b32 v1, s18, v1, v7
; VI-NEXT:    v_add_u32_e32 v0, vcc, 0x300, v0
; VI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s20, s20, 3
; VI-NEXT:    v_mov_b32_e32 v1, s21
; VI-NEXT:    s_add_i32 s22, s22, 3
; VI-NEXT:    v_mov_b32_e32 v2, s23
; VI-NEXT:    v_perm_b32 v1, s20, v1, v7
; VI-NEXT:    v_perm_b32 v2, s22, v2, v7
; VI-NEXT:    v_add_u32_e32 v1, vcc, 0x300, v1
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_or_b32_sdwa v1, v2, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s24, s24, 3
; VI-NEXT:    v_mov_b32_e32 v2, s25
; VI-NEXT:    s_add_i32 s26, s26, 3
; VI-NEXT:    v_mov_b32_e32 v3, s27
; VI-NEXT:    v_perm_b32 v2, s24, v2, v7
; VI-NEXT:    v_perm_b32 v3, s26, v3, v7
; VI-NEXT:    v_add_u32_e32 v2, vcc, 0x300, v2
; VI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_or_b32_sdwa v2, v3, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s28, s28, 3
; VI-NEXT:    v_mov_b32_e32 v3, s29
; VI-NEXT:    s_add_i32 s47, s47, 3
; VI-NEXT:    v_mov_b32_e32 v4, s46
; VI-NEXT:    v_perm_b32 v3, s28, v3, v7
; VI-NEXT:    v_perm_b32 v4, s47, v4, v7
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x300, v3
; VI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_or_b32_sdwa v3, v4, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s45, s45, 3
; VI-NEXT:    v_mov_b32_e32 v4, s44
; VI-NEXT:    s_add_i32 s43, s43, 3
; VI-NEXT:    v_mov_b32_e32 v5, s42
; VI-NEXT:    v_perm_b32 v4, s45, v4, v7
; VI-NEXT:    v_perm_b32 v5, s43, v5, v7
; VI-NEXT:    v_add_u32_e32 v4, vcc, 0x300, v4
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_or_b32_sdwa v4, v5, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s41, s41, 3
; VI-NEXT:    v_mov_b32_e32 v5, s40
; VI-NEXT:    s_add_i32 s15, s15, 3
; VI-NEXT:    v_mov_b32_e32 v6, s14
; VI-NEXT:    v_perm_b32 v5, s41, v5, v7
; VI-NEXT:    v_perm_b32 v6, s15, v6, v7
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x300, v5
; VI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_or_b32_sdwa v5, v6, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s13, s13, 3
; VI-NEXT:    v_mov_b32_e32 v6, s12
; VI-NEXT:    s_add_i32 s11, s11, 3
; VI-NEXT:    v_mov_b32_e32 v8, s10
; VI-NEXT:    v_perm_b32 v6, s13, v6, v7
; VI-NEXT:    v_perm_b32 v8, s11, v8, v7
; VI-NEXT:    v_add_u32_e32 v6, vcc, 0x300, v6
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; VI-NEXT:    v_or_b32_sdwa v6, v8, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s9, s9, 3
; VI-NEXT:    v_mov_b32_e32 v8, s8
; VI-NEXT:    s_add_i32 s7, s7, 3
; VI-NEXT:    v_mov_b32_e32 v9, s6
; VI-NEXT:    v_perm_b32 v8, s9, v8, v7
; VI-NEXT:    v_perm_b32 v7, s7, v9, v7
; VI-NEXT:    v_add_u32_e32 v8, vcc, 0x300, v8
; VI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; VI-NEXT:    v_or_b32_sdwa v7, v7, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_add_u32_e32 v0, vcc, 0x3000000, v0
; VI-NEXT:    v_add_u32_e32 v1, vcc, 0x3000000, v1
; VI-NEXT:    v_add_u32_e32 v2, vcc, 0x3000000, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x3000000, v3
; VI-NEXT:    v_add_u32_e32 v4, vcc, 0x3000000, v4
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x3000000, v5
; VI-NEXT:    v_add_u32_e32 v6, vcc, 0x3000000, v6
; VI-NEXT:    v_add_u32_e32 v7, vcc, 0x3000000, v7
; VI-NEXT:  .LBB71_3: ; %end
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB71_4:
; VI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; VI-NEXT:    s_branch .LBB71_2
;
; GFX9-LABEL: bitcast_v32i8_to_v4i64_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_readfirstlane_b32 s4, v18
; GFX9-NEXT:    v_readfirstlane_b32 s6, v17
; GFX9-NEXT:    v_readfirstlane_b32 s7, v16
; GFX9-NEXT:    v_readfirstlane_b32 s8, v15
; GFX9-NEXT:    v_readfirstlane_b32 s9, v14
; GFX9-NEXT:    v_readfirstlane_b32 s10, v13
; GFX9-NEXT:    v_readfirstlane_b32 s11, v12
; GFX9-NEXT:    v_readfirstlane_b32 s12, v11
; GFX9-NEXT:    v_readfirstlane_b32 s13, v10
; GFX9-NEXT:    v_readfirstlane_b32 s14, v9
; GFX9-NEXT:    v_readfirstlane_b32 s15, v8
; GFX9-NEXT:    v_readfirstlane_b32 s40, v7
; GFX9-NEXT:    v_readfirstlane_b32 s41, v6
; GFX9-NEXT:    v_readfirstlane_b32 s42, v5
; GFX9-NEXT:    v_readfirstlane_b32 s43, v4
; GFX9-NEXT:    v_readfirstlane_b32 s44, v3
; GFX9-NEXT:    v_readfirstlane_b32 s45, v2
; GFX9-NEXT:    v_readfirstlane_b32 s46, v1
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    v_readfirstlane_b32 s47, v0
; GFX9-NEXT:    s_cbranch_scc0 .LBB71_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    v_mov_b32_e32 v7, 0xc0c0004
; GFX9-NEXT:    v_mov_b32_e32 v1, s19
; GFX9-NEXT:    v_mov_b32_e32 v0, s17
; GFX9-NEXT:    v_perm_b32 v1, s18, v1, v7
; GFX9-NEXT:    v_perm_b32 v0, s16, v0, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_mov_b32_e32 v2, s23
; GFX9-NEXT:    v_or_b32_e32 v0, v0, v1
; GFX9-NEXT:    v_mov_b32_e32 v1, s21
; GFX9-NEXT:    v_perm_b32 v2, s22, v2, v7
; GFX9-NEXT:    v_perm_b32 v1, s20, v1, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; GFX9-NEXT:    v_mov_b32_e32 v3, s27
; GFX9-NEXT:    v_or_b32_e32 v1, v1, v2
; GFX9-NEXT:    v_mov_b32_e32 v2, s25
; GFX9-NEXT:    v_perm_b32 v3, s26, v3, v7
; GFX9-NEXT:    v_perm_b32 v2, s24, v2, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; GFX9-NEXT:    v_mov_b32_e32 v4, s46
; GFX9-NEXT:    v_or_b32_e32 v2, v2, v3
; GFX9-NEXT:    v_mov_b32_e32 v3, s29
; GFX9-NEXT:    v_perm_b32 v4, s47, v4, v7
; GFX9-NEXT:    v_perm_b32 v3, s28, v3, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX9-NEXT:    v_mov_b32_e32 v5, s42
; GFX9-NEXT:    v_or_b32_e32 v3, v3, v4
; GFX9-NEXT:    v_mov_b32_e32 v4, s44
; GFX9-NEXT:    v_perm_b32 v5, s43, v5, v7
; GFX9-NEXT:    v_perm_b32 v4, s45, v4, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX9-NEXT:    v_mov_b32_e32 v6, s14
; GFX9-NEXT:    v_or_b32_e32 v4, v4, v5
; GFX9-NEXT:    v_mov_b32_e32 v5, s40
; GFX9-NEXT:    v_perm_b32 v6, s15, v6, v7
; GFX9-NEXT:    v_perm_b32 v5, s41, v5, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GFX9-NEXT:    v_mov_b32_e32 v8, s10
; GFX9-NEXT:    v_or_b32_e32 v5, v5, v6
; GFX9-NEXT:    v_mov_b32_e32 v6, s12
; GFX9-NEXT:    v_perm_b32 v8, s11, v8, v7
; GFX9-NEXT:    v_perm_b32 v6, s13, v6, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; GFX9-NEXT:    v_or_b32_e32 v6, v6, v8
; GFX9-NEXT:    v_mov_b32_e32 v8, s8
; GFX9-NEXT:    v_mov_b32_e32 v9, s6
; GFX9-NEXT:    v_perm_b32 v8, s9, v8, v7
; GFX9-NEXT:    v_perm_b32 v7, s7, v9, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; GFX9-NEXT:    v_or_b32_e32 v7, v8, v7
; GFX9-NEXT:    s_cbranch_execnz .LBB71_3
; GFX9-NEXT:  .LBB71_2: ; %cmp.true
; GFX9-NEXT:    s_add_i32 s16, s16, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s17
; GFX9-NEXT:    v_mov_b32_e32 v7, 0xc0c0004
; GFX9-NEXT:    s_add_i32 s18, s18, 3
; GFX9-NEXT:    v_mov_b32_e32 v1, s19
; GFX9-NEXT:    v_perm_b32 v0, s16, v0, v7
; GFX9-NEXT:    s_movk_i32 s4, 0x300
; GFX9-NEXT:    v_perm_b32 v1, s18, v1, v7
; GFX9-NEXT:    v_add_u32_e32 v0, 0x300, v0
; GFX9-NEXT:    v_add_u32_sdwa v1, v1, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v0, v0, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s20, s20, 3
; GFX9-NEXT:    v_mov_b32_e32 v1, s21
; GFX9-NEXT:    s_add_i32 s22, s22, 3
; GFX9-NEXT:    v_mov_b32_e32 v2, s23
; GFX9-NEXT:    v_perm_b32 v1, s20, v1, v7
; GFX9-NEXT:    v_perm_b32 v2, s22, v2, v7
; GFX9-NEXT:    v_add_u32_e32 v1, 0x300, v1
; GFX9-NEXT:    v_add_u32_sdwa v2, v2, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v1, v1, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s24, s24, 3
; GFX9-NEXT:    v_mov_b32_e32 v2, s25
; GFX9-NEXT:    s_add_i32 s26, s26, 3
; GFX9-NEXT:    v_mov_b32_e32 v3, s27
; GFX9-NEXT:    v_perm_b32 v2, s24, v2, v7
; GFX9-NEXT:    v_perm_b32 v3, s26, v3, v7
; GFX9-NEXT:    v_add_u32_e32 v2, 0x300, v2
; GFX9-NEXT:    v_add_u32_sdwa v3, v3, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v2, v2, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s28, s28, 3
; GFX9-NEXT:    v_mov_b32_e32 v3, s29
; GFX9-NEXT:    s_add_i32 s47, s47, 3
; GFX9-NEXT:    v_mov_b32_e32 v4, s46
; GFX9-NEXT:    v_perm_b32 v3, s28, v3, v7
; GFX9-NEXT:    v_perm_b32 v4, s47, v4, v7
; GFX9-NEXT:    v_add_u32_e32 v3, 0x300, v3
; GFX9-NEXT:    v_add_u32_sdwa v4, v4, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v3, v3, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s45, s45, 3
; GFX9-NEXT:    v_mov_b32_e32 v4, s44
; GFX9-NEXT:    s_add_i32 s43, s43, 3
; GFX9-NEXT:    v_mov_b32_e32 v5, s42
; GFX9-NEXT:    v_perm_b32 v4, s45, v4, v7
; GFX9-NEXT:    v_perm_b32 v5, s43, v5, v7
; GFX9-NEXT:    v_add_u32_e32 v4, 0x300, v4
; GFX9-NEXT:    v_add_u32_sdwa v5, v5, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v4, v4, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s41, s41, 3
; GFX9-NEXT:    v_mov_b32_e32 v5, s40
; GFX9-NEXT:    s_add_i32 s15, s15, 3
; GFX9-NEXT:    v_mov_b32_e32 v6, s14
; GFX9-NEXT:    v_perm_b32 v5, s41, v5, v7
; GFX9-NEXT:    v_perm_b32 v6, s15, v6, v7
; GFX9-NEXT:    v_add_u32_e32 v5, 0x300, v5
; GFX9-NEXT:    v_add_u32_sdwa v6, v6, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v5, v5, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s13, s13, 3
; GFX9-NEXT:    v_mov_b32_e32 v6, s12
; GFX9-NEXT:    s_add_i32 s11, s11, 3
; GFX9-NEXT:    v_mov_b32_e32 v8, s10
; GFX9-NEXT:    v_perm_b32 v6, s13, v6, v7
; GFX9-NEXT:    v_perm_b32 v8, s11, v8, v7
; GFX9-NEXT:    v_add_u32_e32 v6, 0x300, v6
; GFX9-NEXT:    v_add_u32_sdwa v8, v8, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v6, v6, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s9, s9, 3
; GFX9-NEXT:    v_mov_b32_e32 v8, s8
; GFX9-NEXT:    s_add_i32 s7, s7, 3
; GFX9-NEXT:    v_mov_b32_e32 v9, s6
; GFX9-NEXT:    v_perm_b32 v8, s9, v8, v7
; GFX9-NEXT:    v_perm_b32 v7, s7, v9, v7
; GFX9-NEXT:    v_add_u32_e32 v8, 0x300, v8
; GFX9-NEXT:    v_add_u32_sdwa v7, v7, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v7, v8, v7 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:  .LBB71_3: ; %end
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB71_4:
; GFX9-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX9-NEXT:    s_branch .LBB71_2
;
; GFX11-TRUE16-LABEL: bitcast_v32i8_to_v4i64_scalar:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s42, v14
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s4, v13
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr12_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s5, v12
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr11_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s6, v11
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr10_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s7, v10
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s8, v9
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr8_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s9, v8
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr7_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s10, v7
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr6_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s11, v6
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr5_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s12, v5
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr4_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s13, v4
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr3_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s14, v3
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr2_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s15, v2
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr1_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s40, v1
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr0_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s41, v0
; GFX11-TRUE16-NEXT:    s_cmp_lg_u32 s42, 0
; GFX11-TRUE16-NEXT:    s_mov_b32 s42, 0
; GFX11-TRUE16-NEXT:    s_cbranch_scc0 .LBB71_4
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v3, 0xc0c0004
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_perm_b32 v4, s18, s19, v3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, s2, s3, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, s22, s23, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v0, s0, s1, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v2, s16, s17, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v6, s20, s21, v3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX11-TRUE16-NEXT:    v_perm_b32 v8, s26, s27, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v9, s41, s40, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v11, s5, s4, v3
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v0, v0, v1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v1, v2, v4
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v2, v6, v5
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v8
; GFX11-TRUE16-NEXT:    v_perm_b32 v6, s13, s12, v3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v8, 16, v9
; GFX11-TRUE16-NEXT:    v_perm_b32 v9, s9, s8, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v7, s24, s25, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, s28, s29, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v10, s15, s14, v3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GFX11-TRUE16-NEXT:    v_perm_b32 v12, s11, s10, v3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; GFX11-TRUE16-NEXT:    v_perm_b32 v13, s7, s6, v3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v3, v7, v4
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v4, v5, v8
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, v10, v6
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v6, v12, v9
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v7, v13, v11
; GFX11-TRUE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s42
; GFX11-TRUE16-NEXT:    s_cbranch_vccnz .LBB71_3
; GFX11-TRUE16-NEXT:  .LBB71_2: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v3, 0xc0c0004
; GFX11-TRUE16-NEXT:    s_add_i32 s18, s18, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s0, s0, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s2, s2, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s16, s16, 3
; GFX11-TRUE16-NEXT:    v_perm_b32 v4, s18, s19, v3
; GFX11-TRUE16-NEXT:    s_add_i32 s20, s20, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s22, s22, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s24, s24, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s26, s26, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v4, 0x300, v4
; GFX11-TRUE16-NEXT:    s_add_i32 s28, s28, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s41, s41, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s15, s15, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s13, s13, 3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX11-TRUE16-NEXT:    v_perm_b32 v0, s0, s1, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, s2, s3, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v2, s16, s17, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, s20, s21, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v6, s22, s23, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v0, 0x300, v0
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, 0x300, v1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, 0x300, v2
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v5, 0x300, v5
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, 0x300, v6
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GFX11-TRUE16-NEXT:    s_add_i32 s11, s11, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s9, s9, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s7, s7, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s5, s5, 3
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v0, v0, v1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v1, v2, v4
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v2, v5, v6
; GFX11-TRUE16-NEXT:    v_perm_b32 v4, s24, s25, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, s26, s27, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v6, s28, s29, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v7, s41, s40, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v8, s15, s14, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v9, s13, s12, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v10, s11, s10, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v11, s9, s8, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v12, s7, s6, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v3, s5, s4, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v4, 0x300, v4
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v5, 0x300, v5
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, 0x300, v6
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v7, 0x300, v7
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v8, 0x300, v8
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v9, 0x300, v9
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v10, 0x300, v10
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v11, 0x300, v11
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v12, 0x300, v12
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 0x300, v3
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v13, 16, v3
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v3, v4, v5
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v4, v6, v7
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, v8, v9
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v6, v10, v11
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v7, v12, v13
; GFX11-TRUE16-NEXT:  .LBB71_3: ; %end
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB71_4:
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-TRUE16-NEXT:    s_branch .LBB71_2
;
; GFX11-FAKE16-LABEL: bitcast_v32i8_to_v4i64_scalar:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s42, v14
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s4, v13
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s5, v12
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s6, v11
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s7, v10
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s8, v9
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s9, v8
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s10, v7
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s11, v6
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s12, v5
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s13, v4
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s14, v3
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s15, v2
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s40, v1
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s41, v0
; GFX11-FAKE16-NEXT:    s_cmp_lg_u32 s42, 0
; GFX11-FAKE16-NEXT:    s_mov_b32 s42, 0
; GFX11-FAKE16-NEXT:    s_cbranch_scc0 .LBB71_4
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v3, 0xc0c0004
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, s18, s19, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, s2, s3, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, s22, s23, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, s0, s1, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, s16, s17, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, s20, s21, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, s26, s27, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, s41, s40, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, s5, s4, v3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v0, v1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v1, v2, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, v6, v5
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v8
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, s13, s12, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v8, 16, v9
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, s9, s8, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, s24, s25, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, s28, s29, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, s15, s14, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, s11, s10, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, s7, s6, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v7, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, v5, v8
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v5, v10, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v6, v12, v9
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v7, v13, v11
; GFX11-FAKE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s42
; GFX11-FAKE16-NEXT:    s_cbranch_vccnz .LBB71_3
; GFX11-FAKE16-NEXT:  .LBB71_2: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v3, 0xc0c0004
; GFX11-FAKE16-NEXT:    s_add_i32 s18, s18, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s0, s0, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s2, s2, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s16, s16, 3
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, s18, s19, v3
; GFX11-FAKE16-NEXT:    s_add_i32 s20, s20, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s22, s22, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s24, s24, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s26, s26, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, 0x300, v4
; GFX11-FAKE16-NEXT:    s_add_i32 s28, s28, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s41, s41, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s15, s15, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s13, s13, 3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, s0, s1, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, s2, s3, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, s16, s17, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, s20, s21, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, s22, s23, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v0, 0x300, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v1, 0x300, v1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, 0x300, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v5, 0x300, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v6, 0x300, v6
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GFX11-FAKE16-NEXT:    s_add_i32 s11, s11, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s9, s9, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s7, s7, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s5, s5, 3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v0, v1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v1, v2, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, v5, v6
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, s24, s25, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, s26, s27, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, s28, s29, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, s41, s40, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, s15, s14, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, s13, s12, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, s11, s10, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, s9, s8, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, s7, s6, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, s5, s4, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, 0x300, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v5, 0x300, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v6, 0x300, v6
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v7, 0x300, v7
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v8, 0x300, v8
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v9, 0x300, v9
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v10, 0x300, v10
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v11, 0x300, v11
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v12, 0x300, v12
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, 0x300, v3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v13, 16, v3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v4, v5
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, v6, v7
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v5, v8, v9
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v6, v10, v11
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v7, v12, v13
; GFX11-FAKE16-NEXT:  .LBB71_3: ; %end
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB71_4:
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-FAKE16-NEXT:    s_branch .LBB71_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <32 x i8> %a, splat (i8 3)
  %a2 = bitcast <32 x i8> %a1 to <4 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <32 x i8> %a to <4 x i64>
  br label %end

end:
  %phi = phi <4 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x i64> %phi
}

define <16 x i16> @bitcast_v4f64_to_v16i16(<4 x double> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v4f64_to_v16i16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_alignbit_b32 v8, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v9, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v10, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v13, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v1
; SI-NEXT:  ; %bb.2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB72_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; SI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; SI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; SI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; SI-NEXT:    v_alignbit_b32 v8, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v9, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v10, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v13, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v1
; SI-NEXT:  .LBB72_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v13
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v10
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_or_b32_e32 v0, v0, v13
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v15
; SI-NEXT:    v_or_b32_e32 v2, v2, v10
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v14
; SI-NEXT:    v_or_b32_e32 v4, v4, v9
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v12
; SI-NEXT:    v_or_b32_e32 v6, v6, v8
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v11
; SI-NEXT:    v_or_b32_e32 v1, v1, v13
; SI-NEXT:    v_or_b32_e32 v3, v3, v10
; SI-NEXT:    v_or_b32_e32 v5, v5, v9
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v4f64_to_v16i16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB72_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; VI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; VI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; VI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; VI-NEXT:  .LBB72_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v4f64_to_v16i16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB72_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX9-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX9-NEXT:  .LBB72_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v4f64_to_v16i16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB72_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX11-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX11-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX11-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX11-NEXT:  .LBB72_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <4 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <4 x double> %a1 to <16 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <4 x double> %a to <16 x i16>
  br label %end

end:
  %phi = phi <16 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x i16> %phi
}

define inreg <16 x i16> @bitcast_v4f64_to_v16i16_scalar(<4 x double> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v4f64_to_v16i16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB73_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_lshr_b32 s25, s23, 16
; SI-NEXT:    s_lshr_b32 s24, s21, 16
; SI-NEXT:    s_lshr_b32 s15, s19, 16
; SI-NEXT:    s_lshr_b32 s14, s17, 16
; SI-NEXT:    s_lshr_b64 s[4:5], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[6:7], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[8:9], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[10:11], s[16:17], 16
; SI-NEXT:    s_cbranch_execnz .LBB73_4
; SI-NEXT:  .LBB73_2: ; %cmp.true
; SI-NEXT:    v_add_f64 v[6:7], s[22:23], 1.0
; SI-NEXT:    v_add_f64 v[4:5], s[20:21], 1.0
; SI-NEXT:    v_add_f64 v[2:3], s[18:19], 1.0
; SI-NEXT:    v_lshr_b64 v[8:9], v[6:7], 16
; SI-NEXT:    v_add_f64 v[0:1], s[16:17], 1.0
; SI-NEXT:    v_lshr_b64 v[9:10], v[4:5], 16
; SI-NEXT:    v_lshr_b64 v[10:11], v[2:3], 16
; SI-NEXT:    v_lshr_b64 v[11:12], v[0:1], 16
; SI-NEXT:    v_lshrrev_b32_e32 v13, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v1
; SI-NEXT:    s_branch .LBB73_5
; SI-NEXT:  .LBB73_3:
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr8
; SI-NEXT:    ; implicit-def: $sgpr15
; SI-NEXT:    ; implicit-def: $sgpr6
; SI-NEXT:    ; implicit-def: $sgpr24
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr25
; SI-NEXT:    s_branch .LBB73_2
; SI-NEXT:  .LBB73_4:
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v2, s18
; SI-NEXT:    v_mov_b32_e32 v4, s20
; SI-NEXT:    v_mov_b32_e32 v6, s22
; SI-NEXT:    v_mov_b32_e32 v13, s25
; SI-NEXT:    v_mov_b32_e32 v14, s24
; SI-NEXT:    v_mov_b32_e32 v15, s15
; SI-NEXT:    v_mov_b32_e32 v12, s14
; SI-NEXT:    v_mov_b32_e32 v11, s10
; SI-NEXT:    v_mov_b32_e32 v10, s8
; SI-NEXT:    v_mov_b32_e32 v9, s6
; SI-NEXT:    v_mov_b32_e32 v8, s4
; SI-NEXT:  .LBB73_5: ; %end
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v10
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_or_b32_e32 v0, v0, v11
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v12
; SI-NEXT:    v_or_b32_e32 v2, v2, v10
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v15
; SI-NEXT:    v_or_b32_e32 v4, v4, v9
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v14
; SI-NEXT:    v_or_b32_e32 v6, v6, v8
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v13
; SI-NEXT:    v_or_b32_e32 v1, v1, v11
; SI-NEXT:    v_or_b32_e32 v3, v3, v10
; SI-NEXT:    v_or_b32_e32 v5, v5, v9
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v4f64_to_v16i16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB73_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB73_4
; VI-NEXT:  .LBB73_2: ; %cmp.true
; VI-NEXT:    v_add_f64 v[6:7], s[22:23], 1.0
; VI-NEXT:    v_add_f64 v[4:5], s[20:21], 1.0
; VI-NEXT:    v_add_f64 v[2:3], s[18:19], 1.0
; VI-NEXT:    v_add_f64 v[0:1], s[16:17], 1.0
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB73_3:
; VI-NEXT:    s_branch .LBB73_2
; VI-NEXT:  .LBB73_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v4f64_to_v16i16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB73_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB73_4
; GFX9-NEXT:  .LBB73_2: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[6:7], s[22:23], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], s[20:21], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], s[18:19], 1.0
; GFX9-NEXT:    v_add_f64 v[0:1], s[16:17], 1.0
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB73_3:
; GFX9-NEXT:    s_branch .LBB73_2
; GFX9-NEXT:  .LBB73_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v4f64_to_v16i16_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s7, s19
; GFX11-NEXT:    s_mov_b32 s6, s18
; GFX11-NEXT:    s_mov_b32 s5, s17
; GFX11-NEXT:    s_mov_b32 s4, s16
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s8, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB73_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-NEXT:    s_cbranch_vccnz .LBB73_4
; GFX11-NEXT:  .LBB73_2: ; %cmp.true
; GFX11-NEXT:    v_add_f64 v[6:7], s[6:7], 1.0
; GFX11-NEXT:    v_add_f64 v[4:5], s[4:5], 1.0
; GFX11-NEXT:    v_add_f64 v[2:3], s[2:3], 1.0
; GFX11-NEXT:    v_add_f64 v[0:1], s[0:1], 1.0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB73_3:
; GFX11-NEXT:    s_branch .LBB73_2
; GFX11-NEXT:  .LBB73_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <4 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <4 x double> %a1 to <16 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <4 x double> %a to <16 x i16>
  br label %end

end:
  %phi = phi <16 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x i16> %phi
}

define <4 x double> @bitcast_v16i16_to_v4f64(<16 x i16> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v16i16_to_v4f64:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_mov_b32_e32 v16, v7
; SI-NEXT:    v_mov_b32_e32 v9, v6
; SI-NEXT:    v_mov_b32_e32 v10, v5
; SI-NEXT:    v_mov_b32_e32 v11, v4
; SI-NEXT:    v_mov_b32_e32 v12, v3
; SI-NEXT:    v_mov_b32_e32 v13, v2
; SI-NEXT:    v_mov_b32_e32 v14, v1
; SI-NEXT:    v_mov_b32_e32 v15, v0
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v16
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v10
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v12
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v14
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v15
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v7
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v6
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v5
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v4
; SI-NEXT:    v_lshlrev_b32_e32 v19, 16, v3
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v2
; SI-NEXT:    v_lshlrev_b32_e32 v17, 16, v1
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v0
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB74_3
; SI-NEXT:  ; %bb.1: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB74_4
; SI-NEXT:  .LBB74_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB74_3: ; %cmp.false
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v15
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v14
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v13
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v12
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v11
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v10
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v9
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v16
; SI-NEXT:    v_or_b32_e32 v0, v0, v23
; SI-NEXT:    v_or_b32_e32 v1, v1, v22
; SI-NEXT:    v_or_b32_e32 v2, v2, v21
; SI-NEXT:    v_or_b32_e32 v3, v3, v20
; SI-NEXT:    v_or_b32_e32 v4, v4, v19
; SI-NEXT:    v_or_b32_e32 v5, v5, v18
; SI-NEXT:    v_or_b32_e32 v6, v6, v17
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB74_2
; SI-NEXT:  .LBB74_4: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v15
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v14
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v13
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v12
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v11
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v10
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v9
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v16
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_or_b32_e32 v0, v23, v0
; SI-NEXT:    s_mov_b32 s6, 0x30000
; SI-NEXT:    v_or_b32_e32 v1, v22, v1
; SI-NEXT:    v_or_b32_e32 v2, v21, v2
; SI-NEXT:    v_or_b32_e32 v3, v20, v3
; SI-NEXT:    v_or_b32_e32 v4, v19, v4
; SI-NEXT:    v_or_b32_e32 v5, v18, v5
; SI-NEXT:    v_or_b32_e32 v6, v17, v6
; SI-NEXT:    v_or_b32_e32 v7, v8, v7
; SI-NEXT:    v_add_i32_e32 v0, vcc, 0x30000, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, s6, v1
; SI-NEXT:    v_add_i32_e32 v2, vcc, s6, v2
; SI-NEXT:    v_add_i32_e32 v3, vcc, s6, v3
; SI-NEXT:    v_add_i32_e32 v4, vcc, s6, v4
; SI-NEXT:    v_add_i32_e32 v5, vcc, 0x30000, v5
; SI-NEXT:    v_add_i32_e32 v6, vcc, 0x30000, v6
; SI-NEXT:    v_add_i32_e32 v7, vcc, 0x30000, v7
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16i16_to_v4f64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB74_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v9, 3
; VI-NEXT:    v_add_u16_e32 v8, 3, v7
; VI-NEXT:    v_add_u16_sdwa v7, v7, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v7, v8, v7
; VI-NEXT:    v_add_u16_e32 v8, 3, v6
; VI-NEXT:    v_add_u16_sdwa v6, v6, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v6, v8, v6
; VI-NEXT:    v_add_u16_e32 v8, 3, v5
; VI-NEXT:    v_add_u16_sdwa v5, v5, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v5, v8, v5
; VI-NEXT:    v_add_u16_e32 v8, 3, v4
; VI-NEXT:    v_add_u16_sdwa v4, v4, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v4, v8, v4
; VI-NEXT:    v_add_u16_e32 v8, 3, v3
; VI-NEXT:    v_add_u16_sdwa v3, v3, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v3, v8, v3
; VI-NEXT:    v_add_u16_e32 v8, 3, v2
; VI-NEXT:    v_add_u16_sdwa v2, v2, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v2, v8, v2
; VI-NEXT:    v_add_u16_e32 v8, 3, v1
; VI-NEXT:    v_add_u16_sdwa v1, v1, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v1, v8, v1
; VI-NEXT:    v_add_u16_e32 v8, 3, v0
; VI-NEXT:    v_add_u16_sdwa v0, v0, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v0, v8, v0
; VI-NEXT:  .LBB74_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16i16_to_v4f64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v16i16_to_v4f64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB74_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX11-NEXT:  .LBB74_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <16 x i16> %a, splat (i16 3)
  %a2 = bitcast <16 x i16> %a1 to <4 x double>
  br label %end

cmp.false:
  %a3 = bitcast <16 x i16> %a to <4 x double>
  br label %end

end:
  %phi = phi <4 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x double> %phi
}

define inreg <4 x double> @bitcast_v16i16_to_v4f64_scalar(<16 x i16> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v16i16_to_v4f64_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_lshr_b32 s14, s23, 16
; SI-NEXT:    s_lshr_b32 s15, s22, 16
; SI-NEXT:    s_lshr_b32 s25, s21, 16
; SI-NEXT:    s_lshr_b32 s26, s20, 16
; SI-NEXT:    s_lshr_b32 s27, s19, 16
; SI-NEXT:    s_lshr_b32 s28, s18, 16
; SI-NEXT:    s_lshr_b32 s29, s17, 16
; SI-NEXT:    s_lshr_b32 s40, s16, 16
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB75_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s40, 16
; SI-NEXT:    s_or_b32 s4, s4, s5
; SI-NEXT:    s_and_b32 s5, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s6, s29, 16
; SI-NEXT:    s_or_b32 s5, s5, s6
; SI-NEXT:    s_and_b32 s6, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s28, 16
; SI-NEXT:    s_or_b32 s6, s6, s7
; SI-NEXT:    s_and_b32 s7, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s8, s27, 16
; SI-NEXT:    s_or_b32 s7, s7, s8
; SI-NEXT:    s_and_b32 s8, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s9, s26, 16
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_and_b32 s9, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s25, 16
; SI-NEXT:    s_or_b32 s9, s9, s10
; SI-NEXT:    s_and_b32 s10, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s11, s15, 16
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_and_b32 s11, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s14, 16
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    s_cbranch_execnz .LBB75_3
; SI-NEXT:  .LBB75_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s40, 16
; SI-NEXT:    s_add_i32 s17, s17, 3
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_and_b32 s5, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s6, s29, 16
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_or_b32 s5, s6, s5
; SI-NEXT:    s_and_b32 s6, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s28, 16
; SI-NEXT:    s_add_i32 s19, s19, 3
; SI-NEXT:    s_or_b32 s6, s7, s6
; SI-NEXT:    s_and_b32 s7, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s8, s27, 16
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_or_b32 s7, s8, s7
; SI-NEXT:    s_and_b32 s8, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s9, s26, 16
; SI-NEXT:    s_add_i32 s21, s21, 3
; SI-NEXT:    s_or_b32 s8, s9, s8
; SI-NEXT:    s_and_b32 s9, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s25, 16
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_or_b32 s9, s10, s9
; SI-NEXT:    s_and_b32 s10, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s11, s15, 16
; SI-NEXT:    s_add_i32 s23, s23, 3
; SI-NEXT:    s_or_b32 s10, s11, s10
; SI-NEXT:    s_and_b32 s11, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s14, 16
; SI-NEXT:    s_or_b32 s11, s12, s11
; SI-NEXT:    s_add_i32 s4, s4, 0x30000
; SI-NEXT:    s_add_i32 s5, s5, 0x30000
; SI-NEXT:    s_add_i32 s6, s6, 0x30000
; SI-NEXT:    s_add_i32 s7, s7, 0x30000
; SI-NEXT:    s_add_i32 s8, s8, 0x30000
; SI-NEXT:    s_add_i32 s9, s9, 0x30000
; SI-NEXT:    s_add_i32 s10, s10, 0x30000
; SI-NEXT:    s_add_i32 s11, s11, 0x30000
; SI-NEXT:  .LBB75_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v0, s4
; SI-NEXT:    v_mov_b32_e32 v1, s5
; SI-NEXT:    v_mov_b32_e32 v2, s6
; SI-NEXT:    v_mov_b32_e32 v3, s7
; SI-NEXT:    v_mov_b32_e32 v4, s8
; SI-NEXT:    v_mov_b32_e32 v5, s9
; SI-NEXT:    v_mov_b32_e32 v6, s10
; SI-NEXT:    v_mov_b32_e32 v7, s11
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB75_4:
; SI-NEXT:    ; implicit-def: $sgpr4_sgpr5_sgpr6_sgpr7_sgpr8_sgpr9_sgpr10_sgpr11
; SI-NEXT:    s_branch .LBB75_2
;
; VI-LABEL: bitcast_v16i16_to_v4f64_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB75_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB75_3
; VI-NEXT:  .LBB75_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s5, s23, 3
; VI-NEXT:    s_and_b32 s4, s23, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s22, 3
; VI-NEXT:    s_add_i32 s23, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s22, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s21, 3
; VI-NEXT:    s_add_i32 s22, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s21, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s20, 3
; VI-NEXT:    s_add_i32 s21, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s20, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s19, 3
; VI-NEXT:    s_add_i32 s20, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s19, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s18, 3
; VI-NEXT:    s_add_i32 s19, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s18, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s17, 3
; VI-NEXT:    s_add_i32 s18, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s17, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s16, 3
; VI-NEXT:    s_add_i32 s17, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s16, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s16, s4, 0x30000
; VI-NEXT:  .LBB75_3: ; %end
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB75_4:
; VI-NEXT:    s_branch .LBB75_2
;
; GFX9-LABEL: bitcast_v16i16_to_v4f64_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB75_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB75_4
; GFX9-NEXT:  .LBB75_2: ; %cmp.true
; GFX9-NEXT:    v_pk_add_u16 v7, s23, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, s22, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v5, s21, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v4, s20, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v3, s19, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v2, s18, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v1, s17, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v0, s16, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB75_3:
; GFX9-NEXT:    s_branch .LBB75_2
; GFX9-NEXT:  .LBB75_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v16i16_to_v4f64_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s7, s19
; GFX11-NEXT:    s_mov_b32 s6, s18
; GFX11-NEXT:    s_mov_b32 s5, s17
; GFX11-NEXT:    s_mov_b32 s4, s16
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s8, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB75_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-NEXT:    s_cbranch_vccnz .LBB75_4
; GFX11-NEXT:  .LBB75_2: ; %cmp.true
; GFX11-NEXT:    v_pk_add_u16 v7, s7, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v6, s6, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v5, s5, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v4, s4, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v3, s3, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v2, s2, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v1, s1, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v0, s0, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB75_3:
; GFX11-NEXT:    s_branch .LBB75_2
; GFX11-NEXT:  .LBB75_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <16 x i16> %a, splat (i16 3)
  %a2 = bitcast <16 x i16> %a1 to <4 x double>
  br label %end

cmp.false:
  %a3 = bitcast <16 x i16> %a to <4 x double>
  br label %end

end:
  %phi = phi <4 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x double> %phi
}

define <16 x half> @bitcast_v4f64_to_v16f16(<4 x double> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v4f64_to_v16f16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_alignbit_b32 v8, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v9, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v10, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v13, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v1
; SI-NEXT:  ; %bb.2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB76_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; SI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; SI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; SI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; SI-NEXT:    v_alignbit_b32 v8, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v9, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v10, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v13, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v1
; SI-NEXT:  .LBB76_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v13
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v10
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_or_b32_e32 v0, v0, v13
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v15
; SI-NEXT:    v_or_b32_e32 v2, v2, v10
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v14
; SI-NEXT:    v_or_b32_e32 v4, v4, v9
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v12
; SI-NEXT:    v_or_b32_e32 v6, v6, v8
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v11
; SI-NEXT:    v_or_b32_e32 v1, v1, v13
; SI-NEXT:    v_or_b32_e32 v3, v3, v10
; SI-NEXT:    v_or_b32_e32 v5, v5, v9
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v4f64_to_v16f16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB76_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; VI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; VI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; VI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; VI-NEXT:  .LBB76_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v4f64_to_v16f16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB76_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX9-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX9-NEXT:  .LBB76_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v4f64_to_v16f16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB76_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX11-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX11-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX11-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX11-NEXT:  .LBB76_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <4 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <4 x double> %a1 to <16 x half>
  br label %end

cmp.false:
  %a3 = bitcast <4 x double> %a to <16 x half>
  br label %end

end:
  %phi = phi <16 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x half> %phi
}

define inreg <16 x half> @bitcast_v4f64_to_v16f16_scalar(<4 x double> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v4f64_to_v16f16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB77_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_lshr_b32 s25, s23, 16
; SI-NEXT:    s_lshr_b32 s24, s21, 16
; SI-NEXT:    s_lshr_b32 s15, s19, 16
; SI-NEXT:    s_lshr_b32 s14, s17, 16
; SI-NEXT:    s_lshr_b64 s[4:5], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[6:7], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[8:9], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[10:11], s[16:17], 16
; SI-NEXT:    s_cbranch_execnz .LBB77_4
; SI-NEXT:  .LBB77_2: ; %cmp.true
; SI-NEXT:    v_add_f64 v[6:7], s[22:23], 1.0
; SI-NEXT:    v_add_f64 v[4:5], s[20:21], 1.0
; SI-NEXT:    v_add_f64 v[2:3], s[18:19], 1.0
; SI-NEXT:    v_lshr_b64 v[8:9], v[6:7], 16
; SI-NEXT:    v_add_f64 v[0:1], s[16:17], 1.0
; SI-NEXT:    v_lshr_b64 v[9:10], v[4:5], 16
; SI-NEXT:    v_lshr_b64 v[10:11], v[2:3], 16
; SI-NEXT:    v_lshr_b64 v[11:12], v[0:1], 16
; SI-NEXT:    v_lshrrev_b32_e32 v13, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v1
; SI-NEXT:    s_branch .LBB77_5
; SI-NEXT:  .LBB77_3:
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr8
; SI-NEXT:    ; implicit-def: $sgpr15
; SI-NEXT:    ; implicit-def: $sgpr6
; SI-NEXT:    ; implicit-def: $sgpr24
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr25
; SI-NEXT:    s_branch .LBB77_2
; SI-NEXT:  .LBB77_4:
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v2, s18
; SI-NEXT:    v_mov_b32_e32 v4, s20
; SI-NEXT:    v_mov_b32_e32 v6, s22
; SI-NEXT:    v_mov_b32_e32 v13, s25
; SI-NEXT:    v_mov_b32_e32 v14, s24
; SI-NEXT:    v_mov_b32_e32 v15, s15
; SI-NEXT:    v_mov_b32_e32 v12, s14
; SI-NEXT:    v_mov_b32_e32 v11, s10
; SI-NEXT:    v_mov_b32_e32 v10, s8
; SI-NEXT:    v_mov_b32_e32 v9, s6
; SI-NEXT:    v_mov_b32_e32 v8, s4
; SI-NEXT:  .LBB77_5: ; %end
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v10
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_or_b32_e32 v0, v0, v11
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v12
; SI-NEXT:    v_or_b32_e32 v2, v2, v10
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v15
; SI-NEXT:    v_or_b32_e32 v4, v4, v9
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v14
; SI-NEXT:    v_or_b32_e32 v6, v6, v8
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v13
; SI-NEXT:    v_or_b32_e32 v1, v1, v11
; SI-NEXT:    v_or_b32_e32 v3, v3, v10
; SI-NEXT:    v_or_b32_e32 v5, v5, v9
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v4f64_to_v16f16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB77_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB77_4
; VI-NEXT:  .LBB77_2: ; %cmp.true
; VI-NEXT:    v_add_f64 v[6:7], s[22:23], 1.0
; VI-NEXT:    v_add_f64 v[4:5], s[20:21], 1.0
; VI-NEXT:    v_add_f64 v[2:3], s[18:19], 1.0
; VI-NEXT:    v_add_f64 v[0:1], s[16:17], 1.0
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB77_3:
; VI-NEXT:    s_branch .LBB77_2
; VI-NEXT:  .LBB77_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v4f64_to_v16f16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB77_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB77_4
; GFX9-NEXT:  .LBB77_2: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[6:7], s[22:23], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], s[20:21], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], s[18:19], 1.0
; GFX9-NEXT:    v_add_f64 v[0:1], s[16:17], 1.0
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB77_3:
; GFX9-NEXT:    s_branch .LBB77_2
; GFX9-NEXT:  .LBB77_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v4f64_to_v16f16_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s7, s19
; GFX11-NEXT:    s_mov_b32 s6, s18
; GFX11-NEXT:    s_mov_b32 s5, s17
; GFX11-NEXT:    s_mov_b32 s4, s16
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s8, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB77_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-NEXT:    s_cbranch_vccnz .LBB77_4
; GFX11-NEXT:  .LBB77_2: ; %cmp.true
; GFX11-NEXT:    v_add_f64 v[6:7], s[6:7], 1.0
; GFX11-NEXT:    v_add_f64 v[4:5], s[4:5], 1.0
; GFX11-NEXT:    v_add_f64 v[2:3], s[2:3], 1.0
; GFX11-NEXT:    v_add_f64 v[0:1], s[0:1], 1.0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB77_3:
; GFX11-NEXT:    s_branch .LBB77_2
; GFX11-NEXT:  .LBB77_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <4 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <4 x double> %a1 to <16 x half>
  br label %end

cmp.false:
  %a3 = bitcast <4 x double> %a to <16 x half>
  br label %end

end:
  %phi = phi <16 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x half> %phi
}

define <4 x double> @bitcast_v16f16_to_v4f64(<16 x half> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v16f16_to_v4f64:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_mov_b32_e32 v16, v7
; SI-NEXT:    v_mov_b32_e32 v9, v6
; SI-NEXT:    v_mov_b32_e32 v10, v5
; SI-NEXT:    v_mov_b32_e32 v11, v4
; SI-NEXT:    v_mov_b32_e32 v12, v3
; SI-NEXT:    v_mov_b32_e32 v13, v2
; SI-NEXT:    v_mov_b32_e32 v14, v1
; SI-NEXT:    v_mov_b32_e32 v15, v0
; SI-NEXT:    v_lshrrev_b32_e32 v17, 16, v16
; SI-NEXT:    v_lshrrev_b32_e32 v18, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v19, 16, v10
; SI-NEXT:    v_lshrrev_b32_e32 v20, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v21, 16, v12
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v23, 16, v14
; SI-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB78_3
; SI-NEXT:  ; %bb.1: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB78_4
; SI-NEXT:  .LBB78_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB78_3: ; %cmp.false
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v15
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v24
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v14
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v23
; SI-NEXT:    v_or_b32_e32 v0, v0, v1
; SI-NEXT:    v_or_b32_e32 v1, v2, v3
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v13
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v22
; SI-NEXT:    v_or_b32_e32 v2, v2, v3
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v12
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v21
; SI-NEXT:    v_or_b32_e32 v3, v3, v4
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v11
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v20
; SI-NEXT:    v_or_b32_e32 v4, v4, v5
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v10
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v19
; SI-NEXT:    v_or_b32_e32 v5, v5, v6
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v9
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v18
; SI-NEXT:    v_or_b32_e32 v6, v6, v7
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v16
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v17
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr24
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB78_2
; SI-NEXT:  .LBB78_4: ; %cmp.true
; SI-NEXT:    v_cvt_f32_f16_e32 v0, v24
; SI-NEXT:    v_cvt_f32_f16_e32 v2, v23
; SI-NEXT:    v_cvt_f32_f16_e32 v1, v15
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v14
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_or_b32_e32 v0, v1, v0
; SI-NEXT:    v_or_b32_e32 v1, v3, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v2, v22
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v13
; SI-NEXT:    v_cvt_f32_f16_e32 v4, v21
; SI-NEXT:    v_cvt_f32_f16_e32 v5, v20
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_or_b32_e32 v2, v3, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v12
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v6, v11
; SI-NEXT:    v_cvt_f32_f16_e32 v7, v10
; SI-NEXT:    v_cvt_f32_f16_e32 v8, v17
; SI-NEXT:    v_or_b32_e32 v3, v3, v4
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v5, v19
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_or_b32_e32 v4, v6, v4
; SI-NEXT:    v_cvt_f32_f16_e32 v6, v18
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_or_b32_e32 v5, v7, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v7, v9
; SI-NEXT:    v_cvt_f32_f16_e32 v9, v16
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v8, v8
; SI-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v9
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_or_b32_e32 v6, v7, v6
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v8
; SI-NEXT:    v_or_b32_e32 v7, v9, v7
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16f16_to_v4f64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB78_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v8, 0x200
; VI-NEXT:    v_add_f16_sdwa v9, v7, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v7, 0x200, v7
; VI-NEXT:    v_or_b32_e32 v7, v7, v9
; VI-NEXT:    v_add_f16_sdwa v9, v6, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v6, 0x200, v6
; VI-NEXT:    v_or_b32_e32 v6, v6, v9
; VI-NEXT:    v_add_f16_sdwa v9, v5, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v5, 0x200, v5
; VI-NEXT:    v_or_b32_e32 v5, v5, v9
; VI-NEXT:    v_add_f16_sdwa v9, v4, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v4, 0x200, v4
; VI-NEXT:    v_or_b32_e32 v4, v4, v9
; VI-NEXT:    v_add_f16_sdwa v9, v3, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v3, 0x200, v3
; VI-NEXT:    v_or_b32_e32 v3, v3, v9
; VI-NEXT:    v_add_f16_sdwa v9, v2, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, 0x200, v2
; VI-NEXT:    v_or_b32_e32 v2, v2, v9
; VI-NEXT:    v_add_f16_sdwa v9, v1, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v1, 0x200, v1
; VI-NEXT:    v_add_f16_sdwa v8, v0, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v0, 0x200, v0
; VI-NEXT:    v_or_b32_e32 v1, v1, v9
; VI-NEXT:    v_or_b32_e32 v0, v0, v8
; VI-NEXT:  .LBB78_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16f16_to_v4f64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    s_movk_i32 s6, 0x200
; GFX9-NEXT:    v_pk_add_f16 v7, v7, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, v6, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v5, v5, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v4, v4, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v3, v3, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v2, v2, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v1, v1, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v0, v0, s6 op_sel_hi:[1,0]
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v16f16_to_v4f64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB78_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_pk_add_f16 v7, 0x200, v7 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v6, 0x200, v6 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v5, 0x200, v5 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v4, 0x200, v4 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v3, 0x200, v3 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v2, 0x200, v2 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v1, 0x200, v1 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v0, 0x200, v0 op_sel_hi:[0,1]
; GFX11-NEXT:  .LBB78_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <16 x half> %a1 to <4 x double>
  br label %end

cmp.false:
  %a3 = bitcast <16 x half> %a to <4 x double>
  br label %end

end:
  %phi = phi <4 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x double> %phi
}

define inreg <4 x double> @bitcast_v16f16_to_v4f64_scalar(<16 x half> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v16f16_to_v4f64_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_lshr_b32 s14, s23, 16
; SI-NEXT:    s_lshr_b32 s15, s22, 16
; SI-NEXT:    s_lshr_b32 s25, s21, 16
; SI-NEXT:    s_lshr_b32 s26, s20, 16
; SI-NEXT:    s_lshr_b32 s27, s19, 16
; SI-NEXT:    s_lshr_b32 s28, s18, 16
; SI-NEXT:    s_lshr_b32 s29, s17, 16
; SI-NEXT:    s_lshr_b32 s40, s16, 16
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB79_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s40, 16
; SI-NEXT:    s_or_b32 s4, s4, s5
; SI-NEXT:    s_and_b32 s5, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s6, s29, 16
; SI-NEXT:    s_or_b32 s5, s5, s6
; SI-NEXT:    s_and_b32 s6, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s28, 16
; SI-NEXT:    s_or_b32 s6, s6, s7
; SI-NEXT:    s_and_b32 s7, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s8, s27, 16
; SI-NEXT:    s_or_b32 s7, s7, s8
; SI-NEXT:    s_and_b32 s8, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s9, s26, 16
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_and_b32 s9, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s25, 16
; SI-NEXT:    s_or_b32 s9, s9, s10
; SI-NEXT:    s_and_b32 s10, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s11, s15, 16
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_and_b32 s11, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s14, 16
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    s_cbranch_execnz .LBB79_4
; SI-NEXT:  .LBB79_2: ; %cmp.true
; SI-NEXT:    v_cvt_f32_f16_e32 v0, s40
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s16
; SI-NEXT:    v_cvt_f32_f16_e32 v2, s29
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s17
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_cvt_f32_f16_e32 v4, s18
; SI-NEXT:    v_or_b32_e32 v0, v1, v0
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v2, s28
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_or_b32_e32 v1, v3, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s27
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_or_b32_e32 v2, v4, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v4, s19
; SI-NEXT:    v_cvt_f32_f16_e32 v5, s26
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v6, s20
; SI-NEXT:    v_or_b32_e32 v3, v4, v3
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v5, s25
; SI-NEXT:    v_cvt_f32_f16_e32 v7, s21
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_or_b32_e32 v4, v6, v4
; SI-NEXT:    v_cvt_f32_f16_e32 v6, s15
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_or_b32_e32 v5, v7, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v7, s22
; SI-NEXT:    v_cvt_f32_f16_e32 v8, s14
; SI-NEXT:    v_cvt_f32_f16_e32 v9, s23
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v8, v8
; SI-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v9
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_or_b32_e32 v6, v7, v6
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v8
; SI-NEXT:    v_or_b32_e32 v7, v9, v7
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB79_3:
; SI-NEXT:    ; implicit-def: $sgpr4_sgpr5_sgpr6_sgpr7_sgpr8_sgpr9_sgpr10_sgpr11
; SI-NEXT:    s_branch .LBB79_2
; SI-NEXT:  .LBB79_4:
; SI-NEXT:    v_mov_b32_e32 v0, s4
; SI-NEXT:    v_mov_b32_e32 v1, s5
; SI-NEXT:    v_mov_b32_e32 v2, s6
; SI-NEXT:    v_mov_b32_e32 v3, s7
; SI-NEXT:    v_mov_b32_e32 v4, s8
; SI-NEXT:    v_mov_b32_e32 v5, s9
; SI-NEXT:    v_mov_b32_e32 v6, s10
; SI-NEXT:    v_mov_b32_e32 v7, s11
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16f16_to_v4f64_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB79_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB79_4
; VI-NEXT:  .LBB79_2: ; %cmp.true
; VI-NEXT:    s_lshr_b32 s4, s23, 16
; VI-NEXT:    v_mov_b32_e32 v0, 0x200
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, s23, v0
; VI-NEXT:    s_lshr_b32 s4, s22, 16
; VI-NEXT:    v_or_b32_e32 v7, v2, v1
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, s22, v0
; VI-NEXT:    s_lshr_b32 s4, s21, 16
; VI-NEXT:    v_or_b32_e32 v6, v2, v1
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, s21, v0
; VI-NEXT:    s_lshr_b32 s4, s20, 16
; VI-NEXT:    v_or_b32_e32 v5, v2, v1
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, s20, v0
; VI-NEXT:    s_lshr_b32 s4, s19, 16
; VI-NEXT:    v_or_b32_e32 v4, v2, v1
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, s19, v0
; VI-NEXT:    s_lshr_b32 s4, s18, 16
; VI-NEXT:    v_or_b32_e32 v3, v2, v1
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, s18, v0
; VI-NEXT:    s_lshr_b32 s4, s17, 16
; VI-NEXT:    v_or_b32_e32 v2, v2, v1
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    v_add_f16_sdwa v1, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v8, s17, v0
; VI-NEXT:    s_lshr_b32 s4, s16, 16
; VI-NEXT:    v_or_b32_e32 v1, v8, v1
; VI-NEXT:    v_mov_b32_e32 v8, s4
; VI-NEXT:    v_add_f16_sdwa v8, v8, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v0, s16, v0
; VI-NEXT:    v_or_b32_e32 v0, v0, v8
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB79_3:
; VI-NEXT:    s_branch .LBB79_2
; VI-NEXT:  .LBB79_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16f16_to_v4f64_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB79_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB79_4
; GFX9-NEXT:  .LBB79_2: ; %cmp.true
; GFX9-NEXT:    v_mov_b32_e32 v0, 0x200
; GFX9-NEXT:    v_pk_add_f16 v7, s23, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, s22, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v5, s21, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v4, s20, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v3, s19, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v2, s18, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v1, s17, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v0, s16, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB79_3:
; GFX9-NEXT:    s_branch .LBB79_2
; GFX9-NEXT:  .LBB79_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v16f16_to_v4f64_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s7, s19
; GFX11-NEXT:    s_mov_b32 s6, s18
; GFX11-NEXT:    s_mov_b32 s5, s17
; GFX11-NEXT:    s_mov_b32 s4, s16
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s8, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB79_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-NEXT:    s_cbranch_vccnz .LBB79_4
; GFX11-NEXT:  .LBB79_2: ; %cmp.true
; GFX11-NEXT:    v_pk_add_f16 v7, 0x200, s7 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v6, 0x200, s6 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v5, 0x200, s5 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v4, 0x200, s4 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v3, 0x200, s3 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v2, 0x200, s2 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v1, 0x200, s1 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v0, 0x200, s0 op_sel_hi:[0,1]
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB79_3:
; GFX11-NEXT:    s_branch .LBB79_2
; GFX11-NEXT:  .LBB79_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <16 x half> %a1 to <4 x double>
  br label %end

cmp.false:
  %a3 = bitcast <16 x half> %a to <4 x double>
  br label %end

end:
  %phi = phi <4 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x double> %phi
}

define <16 x bfloat> @bitcast_v4f64_to_v16bf16(<4 x double> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v4f64_to_v16bf16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB80_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_and_b32_e32 v9, 0xffff0000, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v7
; SI-NEXT:    v_and_b32_e32 v11, 0xffff0000, v6
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v6
; SI-NEXT:    v_and_b32_e32 v13, 0xffff0000, v5
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v5
; SI-NEXT:    v_and_b32_e32 v15, 0xffff0000, v4
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v4
; SI-NEXT:    v_and_b32_e32 v17, 0xffff0000, v3
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v3
; SI-NEXT:    v_and_b32_e32 v19, 0xffff0000, v2
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v2
; SI-NEXT:    v_and_b32_e32 v21, 0xffff0000, v1
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v1
; SI-NEXT:    v_and_b32_e32 v23, 0xffff0000, v0
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v0
; SI-NEXT:    ; implicit-def: $vgpr0
; SI-NEXT:    ; implicit-def: $vgpr2
; SI-NEXT:    ; implicit-def: $vgpr4
; SI-NEXT:    ; implicit-def: $vgpr6
; SI-NEXT:  .LBB80_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB80_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; SI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; SI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; SI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; SI-NEXT:    v_and_b32_e32 v9, 0xffff0000, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v7
; SI-NEXT:    v_and_b32_e32 v11, 0xffff0000, v6
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v6
; SI-NEXT:    v_and_b32_e32 v13, 0xffff0000, v5
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v5
; SI-NEXT:    v_and_b32_e32 v15, 0xffff0000, v4
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v4
; SI-NEXT:    v_and_b32_e32 v17, 0xffff0000, v3
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v3
; SI-NEXT:    v_and_b32_e32 v19, 0xffff0000, v2
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v2
; SI-NEXT:    v_and_b32_e32 v21, 0xffff0000, v1
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v1
; SI-NEXT:    v_and_b32_e32 v23, 0xffff0000, v0
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v0
; SI-NEXT:  .LBB80_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_mul_f32_e32 v0, 1.0, v23
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_mul_f32_e32 v1, 1.0, v22
; SI-NEXT:    v_alignbit_b32 v0, v0, v1, 16
; SI-NEXT:    v_mul_f32_e32 v1, 1.0, v21
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_mul_f32_e32 v2, 1.0, v20
; SI-NEXT:    v_alignbit_b32 v1, v1, v2, 16
; SI-NEXT:    v_mul_f32_e32 v2, 1.0, v19
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_mul_f32_e32 v3, 1.0, v18
; SI-NEXT:    v_alignbit_b32 v2, v2, v3, 16
; SI-NEXT:    v_mul_f32_e32 v3, 1.0, v17
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_mul_f32_e32 v4, 1.0, v16
; SI-NEXT:    v_alignbit_b32 v3, v3, v4, 16
; SI-NEXT:    v_mul_f32_e32 v4, 1.0, v15
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_mul_f32_e32 v5, 1.0, v14
; SI-NEXT:    v_alignbit_b32 v4, v4, v5, 16
; SI-NEXT:    v_mul_f32_e32 v5, 1.0, v13
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_mul_f32_e32 v6, 1.0, v12
; SI-NEXT:    v_alignbit_b32 v5, v5, v6, 16
; SI-NEXT:    v_mul_f32_e32 v6, 1.0, v11
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_mul_f32_e32 v7, 1.0, v10
; SI-NEXT:    v_alignbit_b32 v6, v6, v7, 16
; SI-NEXT:    v_mul_f32_e32 v7, 1.0, v9
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_mul_f32_e32 v8, 1.0, v8
; SI-NEXT:    v_alignbit_b32 v7, v7, v8, 16
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v4f64_to_v16bf16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB80_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; VI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; VI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; VI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; VI-NEXT:  .LBB80_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v4f64_to_v16bf16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB80_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX9-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX9-NEXT:  .LBB80_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v4f64_to_v16bf16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB80_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX11-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX11-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX11-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX11-NEXT:  .LBB80_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <4 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <4 x double> %a1 to <16 x bfloat>
  br label %end

cmp.false:
  %a3 = bitcast <4 x double> %a to <16 x bfloat>
  br label %end

end:
  %phi = phi <16 x bfloat> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x bfloat> %phi
}

define inreg <16 x bfloat> @bitcast_v4f64_to_v16bf16_scalar(<4 x double> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v4f64_to_v16bf16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB81_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s29, s23, 0xffff0000
; SI-NEXT:    s_lshl_b32 s28, s23, 16
; SI-NEXT:    s_and_b32 s27, s22, 0xffff0000
; SI-NEXT:    s_lshl_b32 s26, s22, 16
; SI-NEXT:    s_and_b32 s25, s21, 0xffff0000
; SI-NEXT:    s_lshl_b32 s24, s21, 16
; SI-NEXT:    s_and_b32 s15, s20, 0xffff0000
; SI-NEXT:    s_lshl_b32 s14, s20, 16
; SI-NEXT:    s_and_b32 s13, s19, 0xffff0000
; SI-NEXT:    s_lshl_b32 s12, s19, 16
; SI-NEXT:    s_and_b32 s11, s18, 0xffff0000
; SI-NEXT:    s_lshl_b32 s10, s18, 16
; SI-NEXT:    s_and_b32 s9, s17, 0xffff0000
; SI-NEXT:    s_lshl_b32 s8, s17, 16
; SI-NEXT:    s_and_b32 s7, s16, 0xffff0000
; SI-NEXT:    s_lshl_b32 s6, s16, 16
; SI-NEXT:    s_cbranch_execnz .LBB81_4
; SI-NEXT:  .LBB81_2: ; %cmp.true
; SI-NEXT:    v_add_f64 v[0:1], s[16:17], 1.0
; SI-NEXT:    v_add_f64 v[2:3], s[18:19], 1.0
; SI-NEXT:    v_add_f64 v[4:5], s[22:23], 1.0
; SI-NEXT:    v_add_f64 v[13:14], s[20:21], 1.0
; SI-NEXT:    v_and_b32_e32 v9, 0xffff0000, v5
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v5
; SI-NEXT:    v_and_b32_e32 v10, 0xffff0000, v4
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v4
; SI-NEXT:    v_and_b32_e32 v11, 0xffff0000, v14
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v14
; SI-NEXT:    v_and_b32_e32 v12, 0xffff0000, v13
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v13
; SI-NEXT:    v_and_b32_e32 v13, 0xffff0000, v3
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v3
; SI-NEXT:    v_and_b32_e32 v14, 0xffff0000, v2
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v2
; SI-NEXT:    v_and_b32_e32 v15, 0xffff0000, v1
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v1
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v0
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    s_branch .LBB81_5
; SI-NEXT:  .LBB81_3:
; SI-NEXT:    ; implicit-def: $sgpr6
; SI-NEXT:    ; implicit-def: $sgpr7
; SI-NEXT:    ; implicit-def: $sgpr8
; SI-NEXT:    ; implicit-def: $sgpr9
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr11
; SI-NEXT:    ; implicit-def: $sgpr12
; SI-NEXT:    ; implicit-def: $sgpr13
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr15
; SI-NEXT:    ; implicit-def: $sgpr24
; SI-NEXT:    ; implicit-def: $sgpr25
; SI-NEXT:    ; implicit-def: $sgpr26
; SI-NEXT:    ; implicit-def: $sgpr27
; SI-NEXT:    ; implicit-def: $sgpr28
; SI-NEXT:    ; implicit-def: $sgpr29
; SI-NEXT:    s_branch .LBB81_2
; SI-NEXT:  .LBB81_4:
; SI-NEXT:    v_mov_b32_e32 v9, s29
; SI-NEXT:    v_mov_b32_e32 v8, s28
; SI-NEXT:    v_mov_b32_e32 v10, s27
; SI-NEXT:    v_mov_b32_e32 v7, s26
; SI-NEXT:    v_mov_b32_e32 v11, s25
; SI-NEXT:    v_mov_b32_e32 v6, s24
; SI-NEXT:    v_mov_b32_e32 v12, s15
; SI-NEXT:    v_mov_b32_e32 v5, s14
; SI-NEXT:    v_mov_b32_e32 v13, s13
; SI-NEXT:    v_mov_b32_e32 v4, s12
; SI-NEXT:    v_mov_b32_e32 v14, s11
; SI-NEXT:    v_mov_b32_e32 v3, s10
; SI-NEXT:    v_mov_b32_e32 v15, s9
; SI-NEXT:    v_mov_b32_e32 v2, s8
; SI-NEXT:    v_mov_b32_e32 v1, s7
; SI-NEXT:    v_mov_b32_e32 v0, s6
; SI-NEXT:  .LBB81_5: ; %end
; SI-NEXT:    v_mul_f32_e32 v1, 1.0, v1
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_mul_f32_e32 v0, 1.0, v0
; SI-NEXT:    v_lshr_b64 v[0:1], v[0:1], 16
; SI-NEXT:    v_mul_f32_e32 v1, 1.0, v15
; SI-NEXT:    v_lshrrev_b32_e32 v16, 16, v1
; SI-NEXT:    v_mul_f32_e32 v15, 1.0, v2
; SI-NEXT:    v_lshr_b64 v[1:2], v[15:16], 16
; SI-NEXT:    v_mul_f32_e32 v2, 1.0, v14
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v2
; SI-NEXT:    v_mul_f32_e32 v14, 1.0, v3
; SI-NEXT:    v_lshr_b64 v[2:3], v[14:15], 16
; SI-NEXT:    v_mul_f32_e32 v3, 1.0, v13
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; SI-NEXT:    v_mul_f32_e32 v13, 1.0, v4
; SI-NEXT:    v_lshr_b64 v[3:4], v[13:14], 16
; SI-NEXT:    v_mul_f32_e32 v4, 1.0, v12
; SI-NEXT:    v_lshrrev_b32_e32 v13, 16, v4
; SI-NEXT:    v_mul_f32_e32 v12, 1.0, v5
; SI-NEXT:    v_lshr_b64 v[4:5], v[12:13], 16
; SI-NEXT:    v_mul_f32_e32 v5, 1.0, v11
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v5
; SI-NEXT:    v_mul_f32_e32 v11, 1.0, v6
; SI-NEXT:    v_lshr_b64 v[5:6], v[11:12], 16
; SI-NEXT:    v_mul_f32_e32 v6, 1.0, v10
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v6
; SI-NEXT:    v_mul_f32_e32 v10, 1.0, v7
; SI-NEXT:    v_lshr_b64 v[6:7], v[10:11], 16
; SI-NEXT:    v_mul_f32_e32 v7, 1.0, v9
; SI-NEXT:    v_lshrrev_b32_e32 v9, 16, v7
; SI-NEXT:    v_mul_f32_e32 v8, 1.0, v8
; SI-NEXT:    v_lshr_b64 v[7:8], v[8:9], 16
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v4f64_to_v16bf16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB81_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB81_4
; VI-NEXT:  .LBB81_2: ; %cmp.true
; VI-NEXT:    v_add_f64 v[6:7], s[22:23], 1.0
; VI-NEXT:    v_add_f64 v[4:5], s[20:21], 1.0
; VI-NEXT:    v_add_f64 v[2:3], s[18:19], 1.0
; VI-NEXT:    v_add_f64 v[0:1], s[16:17], 1.0
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB81_3:
; VI-NEXT:    s_branch .LBB81_2
; VI-NEXT:  .LBB81_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v4f64_to_v16bf16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB81_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB81_4
; GFX9-NEXT:  .LBB81_2: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[6:7], s[22:23], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], s[20:21], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], s[18:19], 1.0
; GFX9-NEXT:    v_add_f64 v[0:1], s[16:17], 1.0
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB81_3:
; GFX9-NEXT:    s_branch .LBB81_2
; GFX9-NEXT:  .LBB81_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v4f64_to_v16bf16_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s7, s19
; GFX11-NEXT:    s_mov_b32 s6, s18
; GFX11-NEXT:    s_mov_b32 s5, s17
; GFX11-NEXT:    s_mov_b32 s4, s16
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s8, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB81_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-NEXT:    s_cbranch_vccnz .LBB81_4
; GFX11-NEXT:  .LBB81_2: ; %cmp.true
; GFX11-NEXT:    v_add_f64 v[6:7], s[6:7], 1.0
; GFX11-NEXT:    v_add_f64 v[4:5], s[4:5], 1.0
; GFX11-NEXT:    v_add_f64 v[2:3], s[2:3], 1.0
; GFX11-NEXT:    v_add_f64 v[0:1], s[0:1], 1.0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB81_3:
; GFX11-NEXT:    s_branch .LBB81_2
; GFX11-NEXT:  .LBB81_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <4 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <4 x double> %a1 to <16 x bfloat>
  br label %end

cmp.false:
  %a3 = bitcast <4 x double> %a to <16 x bfloat>
  br label %end

end:
  %phi = phi <16 x bfloat> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x bfloat> %phi
}

define <4 x double> @bitcast_v16bf16_to_v4f64(<16 x bfloat> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v16bf16_to_v4f64:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_and_b32_e32 v9, 0xffff0000, v7
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_and_b32_e32 v10, 0xffff0000, v6
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_and_b32_e32 v11, 0xffff0000, v5
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v12, 0xffff0000, v4
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_and_b32_e32 v13, 0xffff0000, v3
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v14, 0xffff0000, v2
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_and_b32_e32 v15, 0xffff0000, v1
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_and_b32_e32 v16, 0xffff0000, v0
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    v_mul_f32_e32 v22, 1.0, v16
; SI-NEXT:    v_mul_f32_e32 v23, 1.0, v0
; SI-NEXT:    v_mul_f32_e32 v20, 1.0, v15
; SI-NEXT:    v_mul_f32_e32 v21, 1.0, v1
; SI-NEXT:    v_mul_f32_e32 v18, 1.0, v14
; SI-NEXT:    v_mul_f32_e32 v19, 1.0, v2
; SI-NEXT:    v_mul_f32_e32 v16, 1.0, v13
; SI-NEXT:    v_mul_f32_e32 v17, 1.0, v3
; SI-NEXT:    v_mul_f32_e32 v14, 1.0, v12
; SI-NEXT:    v_mul_f32_e32 v15, 1.0, v4
; SI-NEXT:    v_mul_f32_e32 v12, 1.0, v11
; SI-NEXT:    v_mul_f32_e32 v13, 1.0, v5
; SI-NEXT:    v_mul_f32_e32 v10, 1.0, v10
; SI-NEXT:    v_mul_f32_e32 v11, 1.0, v6
; SI-NEXT:    v_mul_f32_e32 v8, 1.0, v9
; SI-NEXT:    v_mul_f32_e32 v9, 1.0, v7
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB82_3
; SI-NEXT:  ; %bb.1: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB82_4
; SI-NEXT:  .LBB82_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB82_3: ; %cmp.false
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v22
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v20
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v18
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v16
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v14
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v12
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v10
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v8
; SI-NEXT:    v_alignbit_b32 v0, v0, v23, 16
; SI-NEXT:    v_alignbit_b32 v1, v1, v21, 16
; SI-NEXT:    v_alignbit_b32 v2, v2, v19, 16
; SI-NEXT:    v_alignbit_b32 v3, v3, v17, 16
; SI-NEXT:    v_alignbit_b32 v4, v4, v15, 16
; SI-NEXT:    v_alignbit_b32 v5, v5, v13, 16
; SI-NEXT:    v_alignbit_b32 v6, v6, v11, 16
; SI-NEXT:    v_alignbit_b32 v7, v7, v9, 16
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB82_2
; SI-NEXT:  .LBB82_4: ; %cmp.true
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v22
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v20
; SI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v23
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v21
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_alignbit_b32 v0, v1, v0, 16
; SI-NEXT:    v_alignbit_b32 v1, v3, v2, 16
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v18
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v19
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v16
; SI-NEXT:    v_alignbit_b32 v2, v3, v2, 16
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v17
; SI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v14
; SI-NEXT:    v_alignbit_b32 v3, v4, v3, 16
; SI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v15
; SI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; SI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v12
; SI-NEXT:    v_alignbit_b32 v4, v5, v4, 16
; SI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v13
; SI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; SI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v10
; SI-NEXT:    v_alignbit_b32 v5, v6, v5, 16
; SI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v11
; SI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; SI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_and_b32_e32 v8, 0xffff0000, v8
; SI-NEXT:    v_alignbit_b32 v6, v7, v6, 16
; SI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v9
; SI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; SI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; SI-NEXT:    v_lshrrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_alignbit_b32 v7, v8, v7, 16
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16bf16_to_v4f64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB82_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v7
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, 0x7fff, v9
; VI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v7, 16, 1
; VI-NEXT:    s_movk_i32 s6, 0x7fff
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v7
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v7
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; VI-NEXT:    v_cndmask_b32_e32 v7, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; VI-NEXT:    v_alignbit_b32 v7, v7, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v6
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v6, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v6
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v6
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; VI-NEXT:    v_cndmask_b32_e32 v6, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_alignbit_b32 v6, v6, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v5
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v5, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v5
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v5
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; VI-NEXT:    v_cndmask_b32_e32 v5, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_alignbit_b32 v5, v5, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v4
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v4, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v4
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v4
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; VI-NEXT:    v_cndmask_b32_e32 v4, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_alignbit_b32 v4, v4, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v3
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v3
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_alignbit_b32 v3, v3, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v2
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v2
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_alignbit_b32 v2, v2, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v1
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v1, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v1
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v1
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; VI-NEXT:    v_cndmask_b32_e32 v1, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_alignbit_b32 v1, v1, v8, 16
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v0
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v0, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v0
; VI-NEXT:    v_add_u32_e32 v9, vcc, 0x7fff, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v0
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; VI-NEXT:    v_cndmask_b32_e32 v0, v9, v10, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; VI-NEXT:    v_alignbit_b32 v0, v0, v8, 16
; VI-NEXT:  .LBB82_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16bf16_to_v4f64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB82_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v7
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    s_movk_i32 s6, 0x7fff
; GFX9-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v7, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v7, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v7
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; GFX9-NEXT:    v_cndmask_b32_e32 v7, v9, v10, vcc
; GFX9-NEXT:    s_mov_b32 s7, 0x7060302
; GFX9-NEXT:    v_perm_b32 v7, v7, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v6
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v6, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v6, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v6
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; GFX9-NEXT:    v_cndmask_b32_e32 v6, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v6, v6, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v5
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v5, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v5, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v5, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v5, v5, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v4
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v4, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v4, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v4
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; GFX9-NEXT:    v_cndmask_b32_e32 v4, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v4, v4, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v3
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v3, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v3, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v3
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; GFX9-NEXT:    v_cndmask_b32_e32 v3, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v3, v3, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v2, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v2, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v2, v2, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v1
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v1, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v1, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v1, v1, v8, s7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v0
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v0, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v0, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v0
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v0, v9, v10, vcc
; GFX9-NEXT:    v_perm_b32 v0, v0, v8, s7
; GFX9-NEXT:  .LBB82_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v16bf16_to_v4f64:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v8
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
; GFX11-TRUE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v15, v7 :: v_dual_mov_b32 v14, v6
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v13, v5 :: v_dual_mov_b32 v12, v4
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v11, v3 :: v_dual_mov_b32 v10, v2
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v9, v1 :: v_dual_mov_b32 v8, v0
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr7
; GFX11-TRUE16-NEXT:  ; %bb.2: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB82_4
; GFX11-TRUE16-NEXT:  ; %bb.3: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v9, 0xffff0000, v6
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v8, 16, v7
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v10, 0xffff0000, v5
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v9, 0x40c00000, v9 :: v_dual_add_f32 v8, 0x40c00000, v8
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v15, v9, 16, 1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v11, v8, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v14, 0x400000, v8
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add3_u32 v11, v11, v8, 0x7fff
; GFX11-TRUE16-NEXT:    v_dual_cndmask_b32 v8, v11, v14 :: v_dual_and_b32 v7, 0xffff0000, v7
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v7, 0x40c00000, v7 :: v_dual_lshlrev_b32 v6, 16, v6
; GFX11-TRUE16-NEXT:    v_add3_u32 v11, v15, v9, 0x7fff
; GFX11-TRUE16-NEXT:    v_bfe_u32 v12, v7, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v13, 0x400000, v7
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add3_u32 v12, v12, v7, 0x7fff
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v6, 0x40c00000, v6 :: v_dual_cndmask_b32 v15, v12, v13
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v16, v6, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v17, 0x400000, v6
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v15.l, v8.h
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v9
; GFX11-TRUE16-NEXT:    v_add3_u32 v14, v16, v6, 0x7fff
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v6, v14, v17, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v7, 0x40c00000, v10
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v9, 0xffff0000, v4
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v14, v11, v8, vcc_lo
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v10, v7, 16, 1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v8, v5, 16, 1
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v14.l, v6.h
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v9, 0x40c00000, v9 :: v_dual_add_f32 v4, 0x40c00000, v4
; GFX11-TRUE16-NEXT:    v_add3_u32 v6, v10, v7, 0x7fff
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_add3_u32 v8, v8, v5, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v10, 0x400000, v5
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v11, 0x400000, v7
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v5, v8, v10, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-TRUE16-NEXT:    v_bfe_u32 v7, v4, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v4
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v10, 0x400000, v9
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v13, v6, v11, vcc_lo
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_add3_u32 v7, v7, v4, 0x7fff
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-TRUE16-NEXT:    v_bfe_u32 v6, v9, 16, 1
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v11, 0xffff0000, v2
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v4, v7, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v13.l, v5.h
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v5, 0xffff0000, v3
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_2) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v2, 0x40c00000, v2 :: v_dual_lshlrev_b32 v3, 16, v3
; GFX11-TRUE16-NEXT:    v_add3_u32 v6, v6, v9, 0x7fff
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v3, 0x40c00000, v3 :: v_dual_cndmask_b32 v12, v6, v10
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v6, 0x40c00000, v11
; GFX11-TRUE16-NEXT:    v_bfe_u32 v7, v5, 16, 1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v8, v3, 16, 1
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v12.l, v4.h
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v9, 0x400000, v5
; GFX11-TRUE16-NEXT:    v_add3_u32 v4, v7, v5, 0x7fff
; GFX11-TRUE16-NEXT:    v_add3_u32 v7, v8, v3, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v3
; GFX11-TRUE16-NEXT:    v_bfe_u32 v10, v6, 16, 1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v3, v7, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, 0x400000, v6
; GFX11-TRUE16-NEXT:    v_bfe_u32 v7, v2, 16, 1
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v11, v4, v9, vcc_lo
; GFX11-TRUE16-NEXT:    v_add3_u32 v4, v10, v6, 0x7fff
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v11.l, v3.h
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v3, 0xffff0000, v1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v3, 0x40c00000, v3 :: v_dual_lshlrev_b32 v6, 16, v0
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v10, v4, v5, vcc_lo
; GFX11-TRUE16-NEXT:    v_add3_u32 v4, v7, v2, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, 0x400000, v2
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v7, 0x400000, v3
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v2, v4, v5, vcc_lo
; GFX11-TRUE16-NEXT:    v_bfe_u32 v4, v3, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v5, 0x40c00000, v6
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v10.l, v2.h
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_4) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_add3_u32 v4, v4, v3, 0x7fff
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v6, v5, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v16, 0x400000, v5
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v0, 0x40c00000, v0 :: v_dual_add_f32 v1, 0x40c00000, v1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_add3_u32 v6, v6, v5, 0x7fff
; GFX11-TRUE16-NEXT:    v_bfe_u32 v9, v0, 16, 1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-TRUE16-NEXT:    v_add3_u32 v2, v2, v1, 0x7fff
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v2, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-TRUE16-NEXT:    v_add3_u32 v2, v9, v0, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v0
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v5, v6, v16, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v9, v4, v7, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v9.l, v1.h
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v8, v2, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v8.l, v5.h
; GFX11-TRUE16-NEXT:  .LBB82_4: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v0, v8 :: v_dual_mov_b32 v1, v9
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v2, v10 :: v_dual_mov_b32 v3, v11
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v4, v12 :: v_dual_mov_b32 v5, v13
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v6, v14 :: v_dual_mov_b32 v7, v15
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v16bf16_to_v4f64:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-FAKE16-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB82_2
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v9, 16, v6
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v8, 16, v7
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v9, 0x40c00000, v9 :: v_dual_add_f32 v8, 0x40c00000, v8
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v9, 16, 1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v10, v8, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, 0x400000, v8
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v15, v6, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-FAKE16-NEXT:    v_add3_u32 v13, v13, v9, 0x7fff
; GFX11-FAKE16-NEXT:    v_add3_u32 v10, v10, v8, 0x7fff
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v8, v10, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_add3_u32 v11, v15, v6, 0x7fff
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v10, 0x400000, v9
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GFX11-FAKE16-NEXT:    v_bfe_u32 v12, v7, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v14, 0x400000, v7
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_add3_u32 v12, v12, v7, 0x7fff
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v7, v12, v14 :: v_dual_lshlrev_b32 v12, 16, v5
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v7, v8, 0x7060302
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v14, 0x400000, v6
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v9, v13, v10 :: v_dual_add_f32 v10, 0x40c00000, v12
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v8, v5, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v13, 0x400000, v5
; GFX11-FAKE16-NEXT:    v_bfe_u32 v12, v10, 16, 1
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v6, v11, v14 :: v_dual_lshlrev_b32 v11, 16, v4
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-FAKE16-NEXT:    v_add3_u32 v8, v8, v5, 0x7fff
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v6, v9, 0x7060302
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v9, 0x40c00000, v11 :: v_dual_add_f32 v4, 0x40c00000, v4
; GFX11-FAKE16-NEXT:    v_add3_u32 v11, v12, v10, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, 0x400000, v10
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v14, v9, 16, 1
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v10, v11, v12, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, 0x400000, v9
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v12, 16, v3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v5, v8, v13, vcc_lo
; GFX11-FAKE16-NEXT:    v_add3_u32 v8, v14, v9, 0x7fff
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v9, 0x40c00000, v12 :: v_dual_lshlrev_b32 v12, 16, v2
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v5, v10, 0x7060302
; GFX11-FAKE16-NEXT:    v_bfe_u32 v10, v4, 16, 1
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v8, v8, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, 0x400000, v4
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v9, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-FAKE16-NEXT:    v_add3_u32 v10, v10, v4, 0x7fff
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v4, v10, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v10, 0x40c00000, v12
; GFX11-FAKE16-NEXT:    v_add3_u32 v11, v13, v9, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, 0x400000, v9
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v3, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-FAKE16-NEXT:    v_bfe_u32 v14, v10, 16, 1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v9, v11, v12, vcc_lo
; GFX11-FAKE16-NEXT:    v_add3_u32 v11, v13, v3, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, 0x400000, v3
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; GFX11-FAKE16-NEXT:    v_add3_u32 v13, v14, v10, 0x7fff
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v14, 16, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v3, v11, v12 :: v_dual_add_f32 v2, 0x40c00000, v2
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v4, v8, 0x7060302
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v11, 0x40c00000, v14
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v15, 0x400000, v10
; GFX11-FAKE16-NEXT:    v_bfe_u32 v16, v2, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-FAKE16-NEXT:    v_bfe_u32 v14, v11, 16, 1
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v3, v9, 0x7060302
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_add3_u32 v12, v16, v2, 0x7fff
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v10, v13, v15 :: v_dual_lshlrev_b32 v15, 16, v0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v13, 0x400000, v2
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v2, v12, v13, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v12, 0x40c00000, v15
; GFX11-FAKE16-NEXT:    v_add3_u32 v13, v14, v11, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v14, 0x400000, v11
; GFX11-FAKE16-NEXT:    v_bfe_u32 v15, v1, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v11, v11
; GFX11-FAKE16-NEXT:    v_bfe_u32 v16, v12, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v17, 0x400000, v12
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v2, v10, 0x7060302
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v11, v13, v14, vcc_lo
; GFX11-FAKE16-NEXT:    v_add3_u32 v14, v15, v1, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v15, 0x400000, v1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX11-FAKE16-NEXT:    v_add3_u32 v16, v16, v12, 0x7fff
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v1, v14, v15 :: v_dual_add_f32 v0, 0x40c00000, v0
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v12, v12
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v1, v11, 0x7060302
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_3) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v0, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v18, 0x400000, v0
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v12, v16, v17, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-FAKE16-NEXT:    v_add3_u32 v13, v13, v0, 0x7fff
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v0, v13, v18, vcc_lo
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v0, v12, 0x7060302
; GFX11-FAKE16-NEXT:  .LBB82_2: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x bfloat> %a, splat (bfloat 0xR40C0)
  %a2 = bitcast <16 x bfloat> %a1 to <4 x double>
  br label %end

cmp.false:
  %a3 = bitcast <16 x bfloat> %a to <4 x double>
  br label %end

end:
  %phi = phi <4 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x double> %phi
}

define inreg <4 x double> @bitcast_v16bf16_to_v4f64_scalar(<16 x bfloat> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v16bf16_to_v4f64_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_and_b32 s4, s23, 0xffff0000
; SI-NEXT:    s_lshl_b32 s5, s23, 16
; SI-NEXT:    s_and_b32 s6, s22, 0xffff0000
; SI-NEXT:    s_lshl_b32 s7, s22, 16
; SI-NEXT:    s_and_b32 s8, s21, 0xffff0000
; SI-NEXT:    s_lshl_b32 s9, s21, 16
; SI-NEXT:    s_and_b32 s10, s20, 0xffff0000
; SI-NEXT:    s_lshl_b32 s11, s20, 16
; SI-NEXT:    s_and_b32 s12, s19, 0xffff0000
; SI-NEXT:    s_lshl_b32 s13, s19, 16
; SI-NEXT:    s_and_b32 s14, s18, 0xffff0000
; SI-NEXT:    s_lshl_b32 s15, s18, 16
; SI-NEXT:    s_and_b32 s18, s17, 0xffff0000
; SI-NEXT:    s_lshl_b32 s17, s17, 16
; SI-NEXT:    s_and_b32 s19, s16, 0xffff0000
; SI-NEXT:    s_lshl_b32 s16, s16, 16
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    v_mul_f32_e64 v32, 1.0, s19
; SI-NEXT:    v_mul_f32_e64 v23, 1.0, s16
; SI-NEXT:    v_mul_f32_e64 v31, 1.0, s18
; SI-NEXT:    v_mul_f32_e64 v21, 1.0, s17
; SI-NEXT:    v_mul_f32_e64 v30, 1.0, s14
; SI-NEXT:    v_mul_f32_e64 v19, 1.0, s15
; SI-NEXT:    v_mul_f32_e64 v29, 1.0, s12
; SI-NEXT:    v_mul_f32_e64 v17, 1.0, s13
; SI-NEXT:    v_mul_f32_e64 v28, 1.0, s10
; SI-NEXT:    v_mul_f32_e64 v15, 1.0, s11
; SI-NEXT:    v_mul_f32_e64 v27, 1.0, s8
; SI-NEXT:    v_mul_f32_e64 v13, 1.0, s9
; SI-NEXT:    v_mul_f32_e64 v26, 1.0, s6
; SI-NEXT:    v_mul_f32_e64 v25, 1.0, s4
; SI-NEXT:    v_mul_f32_e64 v11, 1.0, s7
; SI-NEXT:    v_mul_f32_e64 v9, 1.0, s5
; SI-NEXT:    s_cbranch_scc0 .LBB83_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_lshrrev_b32_e32 v24, 16, v32
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v31
; SI-NEXT:    v_lshr_b64 v[0:1], v[23:24], 16
; SI-NEXT:    v_lshr_b64 v[1:2], v[21:22], 16
; SI-NEXT:    v_lshrrev_b32_e32 v20, 16, v30
; SI-NEXT:    v_lshr_b64 v[2:3], v[19:20], 16
; SI-NEXT:    v_lshrrev_b32_e32 v18, 16, v29
; SI-NEXT:    v_lshr_b64 v[3:4], v[17:18], 16
; SI-NEXT:    v_lshrrev_b32_e32 v16, 16, v28
; SI-NEXT:    v_lshr_b64 v[4:5], v[15:16], 16
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v27
; SI-NEXT:    v_lshr_b64 v[5:6], v[13:14], 16
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v26
; SI-NEXT:    v_lshr_b64 v[6:7], v[11:12], 16
; SI-NEXT:    v_lshrrev_b32_e32 v10, 16, v25
; SI-NEXT:    v_lshr_b64 v[7:8], v[9:10], 16
; SI-NEXT:    s_cbranch_execnz .LBB83_3
; SI-NEXT:  .LBB83_2: ; %cmp.true
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v32
; SI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v23
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v31
; SI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v21
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_lshr_b64 v[0:1], v[0:1], 16
; SI-NEXT:    v_lshr_b64 v[1:2], v[2:3], 16
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v30
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v19
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_lshr_b64 v[2:3], v[2:3], 16
; SI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v29
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v17
; SI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_lshr_b64 v[3:4], v[3:4], 16
; SI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v28
; SI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v15
; SI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; SI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_lshr_b64 v[4:5], v[4:5], 16
; SI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v27
; SI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v13
; SI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; SI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_lshr_b64 v[5:6], v[5:6], 16
; SI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v26
; SI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v11
; SI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; SI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_lshr_b64 v[6:7], v[6:7], 16
; SI-NEXT:    v_and_b32_e32 v8, 0xffff0000, v25
; SI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v9
; SI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; SI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; SI-NEXT:    v_lshrrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_lshr_b64 v[7:8], v[7:8], 16
; SI-NEXT:  .LBB83_3: ; %end
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB83_4:
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; SI-NEXT:    s_branch .LBB83_2
;
; VI-LABEL: bitcast_v16bf16_to_v4f64_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB83_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB83_4
; VI-NEXT:  .LBB83_2: ; %cmp.true
; VI-NEXT:    s_lshl_b32 s4, s23, 16
; VI-NEXT:    v_mov_b32_e32 v8, 0x40c00000
; VI-NEXT:    v_add_f32_e32 v0, s4, v8
; VI-NEXT:    v_bfe_u32 v1, v0, 16, 1
; VI-NEXT:    v_add_u32_e32 v1, vcc, v1, v0
; VI-NEXT:    v_add_u32_e32 v1, vcc, 0x7fff, v1
; VI-NEXT:    v_or_b32_e32 v2, 0x400000, v0
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; VI-NEXT:    s_and_b32 s4, s23, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v0, v1, v2, vcc
; VI-NEXT:    v_add_f32_e32 v1, s4, v8
; VI-NEXT:    v_bfe_u32 v2, v1, 16, 1
; VI-NEXT:    v_add_u32_e32 v2, vcc, v2, v1
; VI-NEXT:    v_add_u32_e32 v2, vcc, 0x7fff, v2
; VI-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; VI-NEXT:    s_lshl_b32 s4, s22, 16
; VI-NEXT:    v_cndmask_b32_e32 v1, v2, v3, vcc
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    s_and_b32 s4, s22, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; VI-NEXT:    v_add_f32_e32 v3, s4, v8
; VI-NEXT:    v_bfe_u32 v4, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v4, vcc, v4, v3
; VI-NEXT:    v_add_u32_e32 v4, vcc, 0x7fff, v4
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v4, v5, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    s_lshl_b32 s4, s21, 16
; VI-NEXT:    v_lshrrev_b64 v[6:7], 16, v[2:3]
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    s_and_b32 s4, s21, 0xffff0000
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_cndmask_b32_e32 v9, v3, v4, vcc
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; VI-NEXT:    s_lshl_b32 s4, s20, 16
; VI-NEXT:    v_lshrrev_b32_e32 v10, 16, v2
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    s_and_b32 s4, s20, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; VI-NEXT:    v_add_f32_e32 v3, s4, v8
; VI-NEXT:    v_bfe_u32 v4, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v4, vcc, v4, v3
; VI-NEXT:    v_add_u32_e32 v4, vcc, 0x7fff, v4
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v4, v5, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    s_lshl_b32 s4, s19, 16
; VI-NEXT:    v_lshrrev_b64 v[4:5], 16, v[2:3]
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    s_and_b32 s4, s19, 0xffff0000
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_cndmask_b32_e32 v11, v3, v5, vcc
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v5, vcc
; VI-NEXT:    s_lshl_b32 s4, s18, 16
; VI-NEXT:    v_lshrrev_b32_e32 v12, 16, v2
; VI-NEXT:    v_add_f32_e32 v2, s4, v8
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    s_and_b32 s4, s18, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v5, vcc
; VI-NEXT:    v_add_f32_e32 v3, s4, v8
; VI-NEXT:    v_bfe_u32 v5, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v3
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    v_or_b32_e32 v7, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v5, v7, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_lshrrev_b64 v[2:3], 16, v[2:3]
; VI-NEXT:    s_lshl_b32 s4, s17, 16
; VI-NEXT:    v_add_f32_e32 v3, s4, v8
; VI-NEXT:    v_bfe_u32 v5, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v3
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    s_and_b32 s4, s17, 0xffff0000
; VI-NEXT:    v_or_b32_e32 v7, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_add_f32_e32 v3, s4, v8
; VI-NEXT:    v_cndmask_b32_e32 v13, v5, v7, vcc
; VI-NEXT:    v_bfe_u32 v5, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v3
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    v_or_b32_e32 v7, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v5, v7, vcc
; VI-NEXT:    s_lshl_b32 s4, s16, 16
; VI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; VI-NEXT:    v_add_f32_e32 v3, s4, v8
; VI-NEXT:    v_bfe_u32 v5, v3, 16, 1
; VI-NEXT:    s_and_b32 s6, s16, 0xffff0000
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v3
; VI-NEXT:    v_or_b32_e32 v15, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e64 s[4:5], v3, v3
; VI-NEXT:    v_add_f32_e32 v3, s6, v8
; VI-NEXT:    v_bfe_u32 v7, v3, 16, 1
; VI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_add_u32_e32 v7, vcc, v7, v3
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    v_add_u32_e32 v16, vcc, 0x7fff, v7
; VI-NEXT:    v_lshrrev_b64 v[7:8], 16, v[0:1]
; VI-NEXT:    v_or_b32_e32 v17, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_lshrrev_b64 v[8:9], 16, v[9:10]
; VI-NEXT:    v_lshrrev_b64 v[9:10], 16, v[11:12]
; VI-NEXT:    v_cndmask_b32_e32 v1, v16, v17, vcc
; VI-NEXT:    v_lshrrev_b64 v[10:11], 16, v[13:14]
; VI-NEXT:    v_cndmask_b32_e64 v0, v5, v15, s[4:5]
; VI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_lshrrev_b64 v[0:1], 16, v[0:1]
; VI-NEXT:    v_mov_b32_e32 v1, v10
; VI-NEXT:    v_mov_b32_e32 v3, v9
; VI-NEXT:    v_mov_b32_e32 v5, v8
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB83_3:
; VI-NEXT:    s_branch .LBB83_2
; VI-NEXT:  .LBB83_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16bf16_to_v4f64_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB83_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB83_4
; GFX9-NEXT:  .LBB83_2: ; %cmp.true
; GFX9-NEXT:    s_and_b32 s4, s23, 0xffff0000
; GFX9-NEXT:    v_mov_b32_e32 v0, 0x40c00000
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v1
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s23, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v2, v3, vcc
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v0
; GFX9-NEXT:    v_bfe_u32 v3, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v3, v3, v2
; GFX9-NEXT:    v_add_u32_e32 v3, 0x7fff, v3
; GFX9-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; GFX9-NEXT:    v_mov_b32_e32 v8, 0xffff
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v2, v8, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s22, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v7, v1, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v1
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s22, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v2, v3, vcc
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v0
; GFX9-NEXT:    v_bfe_u32 v3, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v3, v3, v2
; GFX9-NEXT:    v_add_u32_e32 v3, 0x7fff, v3
; GFX9-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v2, v8, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s21, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v6, v1, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v1
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s21, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v2, v3, vcc
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v0
; GFX9-NEXT:    v_bfe_u32 v3, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v3, v3, v2
; GFX9-NEXT:    v_add_u32_e32 v3, 0x7fff, v3
; GFX9-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v2, v8, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s20, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v5, v1, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v1
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s20, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v2, v3, vcc
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v0
; GFX9-NEXT:    v_bfe_u32 v3, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v3, v3, v2
; GFX9-NEXT:    v_add_u32_e32 v3, 0x7fff, v3
; GFX9-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v2, v8, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s19, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v4, v1, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v1
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s19, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v2, v3, vcc
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v0
; GFX9-NEXT:    v_bfe_u32 v3, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v3, v3, v2
; GFX9-NEXT:    v_add_u32_e32 v3, 0x7fff, v3
; GFX9-NEXT:    v_or_b32_e32 v9, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v3, v9, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v2, v8, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s18, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v3, v1, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v1
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v9, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s18, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v2, v9, vcc
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v0
; GFX9-NEXT:    v_bfe_u32 v9, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v9, v9, v2
; GFX9-NEXT:    v_add_u32_e32 v9, 0x7fff, v9
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v9, v10, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v2, v8, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s17, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v2, v1, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v0
; GFX9-NEXT:    v_bfe_u32 v9, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v9, v9, v1
; GFX9-NEXT:    v_add_u32_e32 v9, 0x7fff, v9
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    s_lshl_b32 s4, s17, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v9, v10, vcc
; GFX9-NEXT:    v_add_f32_e32 v9, s4, v0
; GFX9-NEXT:    v_bfe_u32 v10, v9, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v10, v10, v9
; GFX9-NEXT:    v_add_u32_e32 v10, 0x7fff, v10
; GFX9-NEXT:    v_or_b32_e32 v11, 0x400000, v9
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v9, v9
; GFX9-NEXT:    v_cndmask_b32_e32 v9, v10, v11, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_b32_sdwa v9, v8, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    s_and_b32 s4, s16, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v1, v1, 16, v9
; GFX9-NEXT:    v_add_f32_e32 v9, s4, v0
; GFX9-NEXT:    v_bfe_u32 v10, v9, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v10, v10, v9
; GFX9-NEXT:    s_lshl_b32 s4, s16, 16
; GFX9-NEXT:    v_add_u32_e32 v10, 0x7fff, v10
; GFX9-NEXT:    v_or_b32_e32 v11, 0x400000, v9
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v9, v9
; GFX9-NEXT:    v_add_f32_e32 v0, s4, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v9, v10, v11, vcc
; GFX9-NEXT:    v_bfe_u32 v10, v0, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v10, v10, v0
; GFX9-NEXT:    v_add_u32_e32 v10, 0x7fff, v10
; GFX9-NEXT:    v_or_b32_e32 v11, 0x400000, v0
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v0, v10, v11, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v9, 16, v9
; GFX9-NEXT:    v_and_b32_sdwa v0, v8, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    v_lshl_or_b32 v0, v9, 16, v0
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB83_3:
; GFX9-NEXT:    s_branch .LBB83_2
; GFX9-NEXT:  .LBB83_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v16bf16_to_v4f64_scalar:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_mov_b32 s7, s19
; GFX11-TRUE16-NEXT:    s_mov_b32 s6, s18
; GFX11-TRUE16-NEXT:    s_mov_b32 s5, s17
; GFX11-TRUE16-NEXT:    s_mov_b32 s4, s16
; GFX11-TRUE16-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-TRUE16-NEXT:    s_mov_b32 s8, 0
; GFX11-TRUE16-NEXT:    s_cbranch_scc0 .LBB83_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-TRUE16-NEXT:    s_cbranch_vccnz .LBB83_4
; GFX11-TRUE16-NEXT:  .LBB83_2: ; %cmp.true
; GFX11-TRUE16-NEXT:    s_and_b32 s8, s7, 0xffff0000
; GFX11-TRUE16-NEXT:    s_lshl_b32 s7, s7, 16
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v0, 0x40c00000, s8
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v1, 0x40c00000, s7
; GFX11-TRUE16-NEXT:    s_and_b32 s7, s6, 0xffff0000
; GFX11-TRUE16-NEXT:    s_lshl_b32 s6, s6, 16
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v4, 0x40c00000, s7
; GFX11-TRUE16-NEXT:    v_bfe_u32 v2, v0, 16, 1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v3, v1, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v5, 0x40c00000, s6
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v6, 0x400000, v0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v7, v4, 16, 1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, v2, v0
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v9, v5, 16, 1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v7, v7, v4
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v2
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, v3, v1
; GFX11-TRUE16-NEXT:    s_and_b32 s6, s5, 0xffff0000
; GFX11-TRUE16-NEXT:    s_lshl_b32 s5, s5, 16
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_dual_cndmask_b32 v0, v2, v6 :: v_dual_add_nc_u32 v3, 0x7fff, v3
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, 0x7fff, v7
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v3, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v3, 0x400000, v4
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, v9, v5
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v8, 0x40c00000, s5
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v7, 16, v1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v9, 0x400000, v5
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v3, v6, v3, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, 0x7fff, v2
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v2, 0x40c00000, s6
; GFX11-TRUE16-NEXT:    v_bfe_u32 v6, v8, 16, 1
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v7.h, v0.l
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v1, v9, vcc_lo
; GFX11-TRUE16-NEXT:    v_bfe_u32 v4, v2, 16, 1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v0, v6, v8
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-TRUE16-NEXT:    s_and_b32 s5, s4, 0xffff0000
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v6, 16, v1
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v6.h, v3.l
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v3, 0x400000, v2
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v4, v4, v2
; GFX11-TRUE16-NEXT:    s_lshl_b32 s4, s4, 16
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v0, 0x7fff, v0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v9, 0x40c00000, s4
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, 0x400000, v8
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, 0x7fff, v4
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v4, 0x40c00000, s5
; GFX11-TRUE16-NEXT:    s_and_b32 s4, s3, 0xffff0000
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v10, 0x400000, v9
; GFX11-TRUE16-NEXT:    s_lshl_b32 s3, s3, 16
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v1, v3, vcc_lo
; GFX11-TRUE16-NEXT:    v_bfe_u32 v2, v4, 16, 1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-TRUE16-NEXT:    v_bfe_u32 v3, v9, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v4
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, v2, v4
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v0, v0, v5, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, v3, v9
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v2
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v5, 16, v0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v0, 0x40c00000, s4
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v3
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v5.h, v1.l
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v2, v2, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-TRUE16-NEXT:    v_bfe_u32 v11, v0, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v1, 0x40c00000, s3
; GFX11-TRUE16-NEXT:    s_and_b32 s3, s2, 0xffff0000
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v3, v3, v10, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v8, v11, v0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v9, v1, 16, 1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-TRUE16-NEXT:    s_lshl_b32 s2, s2, 16
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v4, 16, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v8
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v0
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v4.h, v2.l
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v2, 0x40c00000, s3
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v10, 0x400000, v1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_dual_cndmask_b32 v0, v3, v8 :: v_dual_add_nc_u32 v3, v9, v1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v8, v2, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v9, 0x40c00000, s2
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-TRUE16-NEXT:    s_and_b32 s2, s1, 0xffff0000
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v8, v8, v2
; GFX11-TRUE16-NEXT:    v_bfe_u32 v11, v9, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v12, 0x400000, v2
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v3, v10, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v10, 0x40c00000, s2
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v8, 0x7fff, v8
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v11, v11, v9
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v3, 16, v1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v1, v10, 16, 1
; GFX11-TRUE16-NEXT:    s_lshl_b32 s1, s1, 16
; GFX11-TRUE16-NEXT:    s_and_b32 s2, s0, 0xffff0000
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v2, v8, v12, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v8, 0x7fff, v11
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v11, 0x400000, v9
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, v1, v10
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v3.h, v0.l
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v2
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v9, 0x40c00000, s2
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v2, v8, v11, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v8, 0x40c00000, s1
; GFX11-TRUE16-NEXT:    s_lshl_b32 s0, s0, 16
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, 0x7fff, v1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v11, 0x400000, v10
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v12, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v13, v8, 16, 1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v14, v9, 16, 1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v15, 0x400000, v8
; GFX11-TRUE16-NEXT:    v_bfe_u32 v10, v12, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v16, 0x400000, v12
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v1, v11, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v11, v13, v8
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v13, v14, v9
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.h, v0.l
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v14, 16, v1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, v10, v12
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v10, 0x7fff, v11
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v11, 0x7fff, v13
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v13, 0x400000, v9
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, 0x7fff, v1
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v9, v11, v13, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_3) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v9, 16, v9
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v8, v10, v15, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v12, v12
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v10, v1, v16, vcc_lo
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v1, 16, v8
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v1.h, v14.l
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v10
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.h, v9.l
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB83_3:
; GFX11-TRUE16-NEXT:    s_branch .LBB83_2
; GFX11-TRUE16-NEXT:  .LBB83_4:
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v16bf16_to_v4f64_scalar:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    s_mov_b32 s7, s19
; GFX11-FAKE16-NEXT:    s_mov_b32 s6, s18
; GFX11-FAKE16-NEXT:    s_mov_b32 s5, s17
; GFX11-FAKE16-NEXT:    s_mov_b32 s4, s16
; GFX11-FAKE16-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-FAKE16-NEXT:    s_mov_b32 s8, 0
; GFX11-FAKE16-NEXT:    s_cbranch_scc0 .LBB83_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-FAKE16-NEXT:    s_cbranch_vccnz .LBB83_4
; GFX11-FAKE16-NEXT:  .LBB83_2: ; %cmp.true
; GFX11-FAKE16-NEXT:    s_lshl_b32 s8, s7, 16
; GFX11-FAKE16-NEXT:    s_and_b32 s7, s7, 0xffff0000
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v0, 0x40c00000, s8
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v1, 0x40c00000, s7
; GFX11-FAKE16-NEXT:    s_and_b32 s8, s6, 0xffff0000
; GFX11-FAKE16-NEXT:    s_lshl_b32 s6, s6, 16
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v3, 0x40c00000, s8
; GFX11-FAKE16-NEXT:    v_bfe_u32 v2, v0, 16, 1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v4, v1, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v9, 0x400000, v1
; GFX11-FAKE16-NEXT:    s_and_b32 s7, s5, 0xffff0000
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v5, 0x40c00000, s6
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v6, 0x40c00000, s7
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, v4, v1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v8, 0x400000, v0
; GFX11-FAKE16-NEXT:    v_bfe_u32 v10, v3, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-FAKE16-NEXT:    s_lshl_b32 s5, s5, 16
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, 0x7fff, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, v2, v0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v7, 0x40c00000, s5
; GFX11-FAKE16-NEXT:    v_bfe_u32 v11, v6, 16, 1
; GFX11-FAKE16-NEXT:    s_and_b32 s5, s4, 0xffff0000
; GFX11-FAKE16-NEXT:    s_lshl_b32 s4, s4, 16
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v2
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_4) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v0, v2, v8, vcc_lo
; GFX11-FAKE16-NEXT:    v_bfe_u32 v2, v5, 16, 1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v8, v10, v3
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v10, 0x400000, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, v2, v5
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v1, v4, v9 :: v_dual_add_nc_u32 v8, 0x7fff, v8
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, 0x400000, v3
; GFX11-FAKE16-NEXT:    v_bfe_u32 v9, v7, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v3, v8, v4 :: v_dual_add_nc_u32 v4, v9, v7
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v5, v11, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v8, 0x400000, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, 0x7fff, v4
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v2, v2, v10 :: v_dual_add_nc_u32 v5, 0x7fff, v5
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v9, 0x400000, v6
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v10, 0x40c00000, s4
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v4, v4, v8, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v8, 0x40c00000, s5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v7, v1, 16, v0
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v5, v5, v9, vcc_lo
; GFX11-FAKE16-NEXT:    v_bfe_u32 v9, v10, 16, 1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v6, v8, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-FAKE16-NEXT:    s_and_b32 s4, s3, 0xffff0000
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v0, v9, v10
; GFX11-FAKE16-NEXT:    s_lshl_b32 s3, s3, 16
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v9, 0x40c00000, s3
; GFX11-FAKE16-NEXT:    s_and_b32 s3, s2, 0xffff0000
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v0, 0x7fff, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v11, v6, v8
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v6, v3, 16, v2
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, 0x400000, v10
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, 0x400000, v8
; GFX11-FAKE16-NEXT:    s_lshl_b32 s2, s2, 16
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, 0x400000, v9
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v0, v0, v3, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v1, 0x7fff, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v8, 0x40c00000, s3
; GFX11-FAKE16-NEXT:    v_bfe_u32 v3, v9, 16, 1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v1, v1, v2 :: v_dual_and_b32 v4, 0xffff, v4
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v10, v8, 16, 1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v5, v5, 16, v4
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v4, 0x40c00000, s4
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v10, v10, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v2, v4, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, 0x400000, v4
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, v2, v4
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v4, 0x40c00000, s2
; GFX11-FAKE16-NEXT:    s_and_b32 s2, s1, 0xffff0000
; GFX11-FAKE16-NEXT:    s_lshl_b32 s1, s1, 16
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, v3, v9
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v13, 0x40c00000, s1
; GFX11-FAKE16-NEXT:    s_lshl_b32 s1, s0, 16
; GFX11-FAKE16-NEXT:    s_and_b32 s0, s0, 0xffff0000
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v2, v2, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v9, 0x7fff, v10
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v3
; GFX11-FAKE16-NEXT:    v_bfe_u32 v11, v4, 16, 1
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v14, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v18, 0x400000, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v3, v3, v12, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-FAKE16-NEXT:    v_bfe_u32 v16, v14, 16, 1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v8, v9, v10 :: v_dual_add_nc_u32 v9, v11, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, 0x400000, v4
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v10, 0x40c00000, s2
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v16, v16, v14
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v9, 0x7fff, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v8, 16, v8
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v12, v10, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v17, 0x400000, v10
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v4, v9, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v9, 0x40c00000, s1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v11, v13, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v13, v13
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v12, v12, v10
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v15, v9, 16, 1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v11, v11, v13
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v19, 0x400000, v9
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v12, 0x7fff, v12
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v13, 0x7fff, v16
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v15, v15, v9
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v11, 0x7fff, v11
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v16, 0x400000, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v15, 0x7fff, v15
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v11, v11, v18, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v11, 16, v11
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v9, v15, v19, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v9, 16, v9
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v10, v12, v17, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v14, v14
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v10, 16, v10
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v12, v13, v16, vcc_lo
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v13, 0xffff, v4
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v4, v1, 16, v0
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v3, v2, 16, v3
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v1, v10, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v12, 16, v12
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v2, v8, 16, v13
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v0, v12, 16, v9
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB83_3:
; GFX11-FAKE16-NEXT:    s_branch .LBB83_2
; GFX11-FAKE16-NEXT:  .LBB83_4:
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x bfloat> %a, splat (bfloat 0xR40C0)
  %a2 = bitcast <16 x bfloat> %a1 to <4 x double>
  br label %end

cmp.false:
  %a3 = bitcast <16 x bfloat> %a to <4 x double>
  br label %end

end:
  %phi = phi <4 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x double> %phi
}

define <32 x i8> @bitcast_v4f64_to_v32i8(<4 x double> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v4f64_to_v32i8:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_mov_b32_e32 v35, v5
; SI-NEXT:    v_mov_b32_e32 v34, v4
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr5
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr25
; SI-NEXT:    ; implicit-def: $vgpr26
; SI-NEXT:    ; implicit-def: $vgpr27
; SI-NEXT:    ; implicit-def: $vgpr29
; SI-NEXT:    ; implicit-def: $vgpr30
; SI-NEXT:    ; implicit-def: $vgpr31
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB84_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_alignbit_b32 v27, v7, v6, 24
; SI-NEXT:    v_alignbit_b32 v26, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v25, v7, v6, 8
; SI-NEXT:    v_alignbit_b32 v19, v35, v34, 24
; SI-NEXT:    v_alignbit_b32 v18, v35, v34, 16
; SI-NEXT:    v_alignbit_b32 v17, v35, v34, 8
; SI-NEXT:    v_alignbit_b32 v11, v3, v2, 24
; SI-NEXT:    v_alignbit_b32 v10, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v9, v3, v2, 8
; SI-NEXT:    v_alignbit_b32 v38, v1, v0, 24
; SI-NEXT:    v_alignbit_b32 v32, v1, v0, 16
; SI-NEXT:    v_alignbit_b32 v33, v1, v0, 8
; SI-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; SI-NEXT:    v_lshrrev_b32_e32 v23, 24, v35
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v35
; SI-NEXT:    v_lshrrev_b32_e32 v21, 8, v35
; SI-NEXT:    v_lshrrev_b32_e32 v15, 24, v3
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v13, 8, v3
; SI-NEXT:    v_lshrrev_b32_e32 v36, 24, v1
; SI-NEXT:    v_lshrrev_b32_e32 v37, 16, v1
; SI-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; SI-NEXT:  .LBB84_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB84_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; SI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; SI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; SI-NEXT:    v_add_f64 v[34:35], v[34:35], 1.0
; SI-NEXT:    v_alignbit_b32 v27, v7, v6, 24
; SI-NEXT:    v_alignbit_b32 v26, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v25, v7, v6, 8
; SI-NEXT:    v_alignbit_b32 v19, v35, v34, 24
; SI-NEXT:    v_alignbit_b32 v18, v35, v34, 16
; SI-NEXT:    v_alignbit_b32 v17, v35, v34, 8
; SI-NEXT:    v_alignbit_b32 v11, v3, v2, 24
; SI-NEXT:    v_alignbit_b32 v10, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v9, v3, v2, 8
; SI-NEXT:    v_alignbit_b32 v38, v1, v0, 24
; SI-NEXT:    v_alignbit_b32 v32, v1, v0, 16
; SI-NEXT:    v_alignbit_b32 v33, v1, v0, 8
; SI-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; SI-NEXT:    v_lshrrev_b32_e32 v23, 24, v35
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v35
; SI-NEXT:    v_lshrrev_b32_e32 v21, 8, v35
; SI-NEXT:    v_lshrrev_b32_e32 v15, 24, v3
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v13, 8, v3
; SI-NEXT:    v_lshrrev_b32_e32 v36, 24, v1
; SI-NEXT:    v_lshrrev_b32_e32 v37, 16, v1
; SI-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; SI-NEXT:  .LBB84_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_mov_b32_e32 v4, v1
; SI-NEXT:    v_mov_b32_e32 v8, v2
; SI-NEXT:    v_mov_b32_e32 v12, v3
; SI-NEXT:    v_mov_b32_e32 v16, v34
; SI-NEXT:    v_mov_b32_e32 v20, v35
; SI-NEXT:    v_mov_b32_e32 v24, v6
; SI-NEXT:    v_mov_b32_e32 v28, v7
; SI-NEXT:    v_mov_b32_e32 v1, v33
; SI-NEXT:    v_mov_b32_e32 v2, v32
; SI-NEXT:    v_mov_b32_e32 v3, v38
; SI-NEXT:    v_mov_b32_e32 v6, v37
; SI-NEXT:    v_mov_b32_e32 v7, v36
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v4f64_to_v32i8:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_mov_b32_e32 v33, v5
; VI-NEXT:    v_mov_b32_e32 v32, v4
; VI-NEXT:    v_mov_b32_e32 v35, v3
; VI-NEXT:    v_mov_b32_e32 v34, v2
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr2
; VI-NEXT:    ; implicit-def: $vgpr5
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr9
; VI-NEXT:    ; implicit-def: $vgpr10
; VI-NEXT:    ; implicit-def: $vgpr13
; VI-NEXT:    ; implicit-def: $vgpr14
; VI-NEXT:    ; implicit-def: $vgpr15
; VI-NEXT:    ; implicit-def: $vgpr17
; VI-NEXT:    ; implicit-def: $vgpr18
; VI-NEXT:    ; implicit-def: $vgpr21
; VI-NEXT:    ; implicit-def: $vgpr22
; VI-NEXT:    ; implicit-def: $vgpr23
; VI-NEXT:    ; implicit-def: $vgpr25
; VI-NEXT:    ; implicit-def: $vgpr26
; VI-NEXT:    ; implicit-def: $vgpr29
; VI-NEXT:    ; implicit-def: $vgpr30
; VI-NEXT:    ; implicit-def: $vgpr31
; VI-NEXT:    ; implicit-def: $vgpr3
; VI-NEXT:    ; implicit-def: $vgpr11
; VI-NEXT:    ; implicit-def: $vgpr19
; VI-NEXT:    ; implicit-def: $vgpr27
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB84_2
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v25, 8, v6
; VI-NEXT:    v_lshrrev_b32_e32 v23, 24, v33
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v33
; VI-NEXT:    v_lshrrev_b32_e32 v21, 8, v33
; VI-NEXT:    v_lshrrev_b32_e32 v18, 16, v32
; VI-NEXT:    v_lshrrev_b32_e32 v17, 8, v32
; VI-NEXT:    v_lshrrev_b32_e32 v15, 24, v35
; VI-NEXT:    v_lshrrev_b32_e32 v14, 16, v35
; VI-NEXT:    v_lshrrev_b32_e32 v13, 8, v35
; VI-NEXT:    v_lshrrev_b32_e32 v10, 16, v34
; VI-NEXT:    v_lshrrev_b32_e32 v9, 8, v34
; VI-NEXT:    v_lshrrev_b32_e32 v36, 24, v1
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; VI-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; VI-NEXT:    v_lshrrev_b32_e32 v38, 8, v0
; VI-NEXT:    v_lshrrev_b64 v[27:28], 24, v[6:7]
; VI-NEXT:    v_lshrrev_b64 v[19:20], 24, v[32:33]
; VI-NEXT:    v_lshrrev_b64 v[11:12], 24, v[34:35]
; VI-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; VI-NEXT:  .LBB84_2: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB84_4
; VI-NEXT:  ; %bb.3: ; %cmp.true
; VI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; VI-NEXT:    v_add_f64 v[32:33], v[32:33], 1.0
; VI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; VI-NEXT:    v_add_f64 v[34:35], v[34:35], 1.0
; VI-NEXT:    v_lshrrev_b64 v[27:28], 24, v[6:7]
; VI-NEXT:    v_lshrrev_b64 v[19:20], 24, v[32:33]
; VI-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; VI-NEXT:    v_lshrrev_b64 v[11:12], 24, v[34:35]
; VI-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v25, 8, v6
; VI-NEXT:    v_lshrrev_b32_e32 v23, 24, v33
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v33
; VI-NEXT:    v_lshrrev_b32_e32 v21, 8, v33
; VI-NEXT:    v_lshrrev_b32_e32 v18, 16, v32
; VI-NEXT:    v_lshrrev_b32_e32 v17, 8, v32
; VI-NEXT:    v_lshrrev_b32_e32 v15, 24, v35
; VI-NEXT:    v_lshrrev_b32_e32 v14, 16, v35
; VI-NEXT:    v_lshrrev_b32_e32 v13, 8, v35
; VI-NEXT:    v_lshrrev_b32_e32 v10, 16, v34
; VI-NEXT:    v_lshrrev_b32_e32 v9, 8, v34
; VI-NEXT:    v_lshrrev_b32_e32 v36, 24, v1
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; VI-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; VI-NEXT:    v_lshrrev_b32_e32 v38, 8, v0
; VI-NEXT:  .LBB84_4: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    v_mov_b32_e32 v4, v1
; VI-NEXT:    v_mov_b32_e32 v8, v34
; VI-NEXT:    v_mov_b32_e32 v12, v35
; VI-NEXT:    v_mov_b32_e32 v16, v32
; VI-NEXT:    v_mov_b32_e32 v20, v33
; VI-NEXT:    v_mov_b32_e32 v24, v6
; VI-NEXT:    v_mov_b32_e32 v28, v7
; VI-NEXT:    v_mov_b32_e32 v1, v38
; VI-NEXT:    v_mov_b32_e32 v6, v37
; VI-NEXT:    v_mov_b32_e32 v7, v36
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v4f64_to_v32i8:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_mov_b32_e32 v33, v5
; GFX9-NEXT:    v_mov_b32_e32 v32, v4
; GFX9-NEXT:    v_mov_b32_e32 v35, v3
; GFX9-NEXT:    v_mov_b32_e32 v34, v2
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr2
; GFX9-NEXT:    ; implicit-def: $vgpr5
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr9
; GFX9-NEXT:    ; implicit-def: $vgpr10
; GFX9-NEXT:    ; implicit-def: $vgpr13
; GFX9-NEXT:    ; implicit-def: $vgpr14
; GFX9-NEXT:    ; implicit-def: $vgpr15
; GFX9-NEXT:    ; implicit-def: $vgpr17
; GFX9-NEXT:    ; implicit-def: $vgpr18
; GFX9-NEXT:    ; implicit-def: $vgpr21
; GFX9-NEXT:    ; implicit-def: $vgpr22
; GFX9-NEXT:    ; implicit-def: $vgpr23
; GFX9-NEXT:    ; implicit-def: $vgpr25
; GFX9-NEXT:    ; implicit-def: $vgpr26
; GFX9-NEXT:    ; implicit-def: $vgpr29
; GFX9-NEXT:    ; implicit-def: $vgpr30
; GFX9-NEXT:    ; implicit-def: $vgpr31
; GFX9-NEXT:    ; implicit-def: $vgpr3
; GFX9-NEXT:    ; implicit-def: $vgpr11
; GFX9-NEXT:    ; implicit-def: $vgpr19
; GFX9-NEXT:    ; implicit-def: $vgpr27
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB84_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 8, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 24, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 8, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v18, 16, v32
; GFX9-NEXT:    v_lshrrev_b32_e32 v17, 8, v32
; GFX9-NEXT:    v_lshrrev_b32_e32 v15, 24, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v14, 16, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v13, 8, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v10, 16, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v9, 8, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 24, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 8, v0
; GFX9-NEXT:    v_lshrrev_b64 v[27:28], 24, v[6:7]
; GFX9-NEXT:    v_lshrrev_b64 v[19:20], 24, v[32:33]
; GFX9-NEXT:    v_lshrrev_b64 v[11:12], 24, v[34:35]
; GFX9-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; GFX9-NEXT:  .LBB84_2: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB84_4
; GFX9-NEXT:  ; %bb.3: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX9-NEXT:    v_add_f64 v[32:33], v[32:33], 1.0
; GFX9-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX9-NEXT:    v_add_f64 v[34:35], v[34:35], 1.0
; GFX9-NEXT:    v_lshrrev_b64 v[27:28], 24, v[6:7]
; GFX9-NEXT:    v_lshrrev_b64 v[19:20], 24, v[32:33]
; GFX9-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; GFX9-NEXT:    v_lshrrev_b64 v[11:12], 24, v[34:35]
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 8, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 24, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 8, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v18, 16, v32
; GFX9-NEXT:    v_lshrrev_b32_e32 v17, 8, v32
; GFX9-NEXT:    v_lshrrev_b32_e32 v15, 24, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v14, 16, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v13, 8, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v10, 16, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v9, 8, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 24, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 8, v0
; GFX9-NEXT:  .LBB84_4: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    v_mov_b32_e32 v4, v1
; GFX9-NEXT:    v_mov_b32_e32 v8, v34
; GFX9-NEXT:    v_mov_b32_e32 v12, v35
; GFX9-NEXT:    v_mov_b32_e32 v16, v32
; GFX9-NEXT:    v_mov_b32_e32 v20, v33
; GFX9-NEXT:    v_mov_b32_e32 v24, v6
; GFX9-NEXT:    v_mov_b32_e32 v28, v7
; GFX9-NEXT:    v_mov_b32_e32 v1, v38
; GFX9-NEXT:    v_mov_b32_e32 v6, v37
; GFX9-NEXT:    v_mov_b32_e32 v7, v36
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v4f64_to_v32i8:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v33, v7 :: v_dual_mov_b32 v32, v6
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v27, v5 :: v_dual_mov_b32 v26, v4
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v19, v3 :: v_dual_mov_b32 v18, v2
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v11, v1 :: v_dual_mov_b32 v10, v0
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr1_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr3_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr5_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr7_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr36_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr15_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr17_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr35_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr21_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr23_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr25_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr34_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr29_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr31_lo16
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB84_2
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[34:35], 24, v[32:33]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[35:36], 24, v[26:27]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v27
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v27
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v26
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v18
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[36:37], 24, v[18:19]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[10:11]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v10
; GFX11-TRUE16-NEXT:  .LBB84_2: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB84_4
; GFX11-TRUE16-NEXT:  ; %bb.3: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_add_f64 v[32:33], v[32:33], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[26:27], v[26:27], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[18:19], v[18:19], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[34:35], 24, v[32:33]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[35:36], 24, v[26:27]
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[36:37], 24, v[18:19]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[10:11]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v27
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v27
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v26
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v18
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v10
; GFX11-TRUE16-NEXT:  .LBB84_4: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.l, v10.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.l, v10.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v4.l, v11.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v6.l, v11.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v8.l, v18.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v10.l, v18.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v11.l, v36.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v12.l, v19.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v14.l, v19.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v16.l, v26.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v18.l, v26.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v19.l, v35.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v20.l, v27.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v22.l, v27.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v24.l, v32.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v26.l, v32.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v27.l, v34.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v28.l, v33.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v30.l, v33.h
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v4f64_to_v32i8:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v33, v7 :: v_dual_mov_b32 v32, v6
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v35, v5 :: v_dual_mov_b32 v34, v4
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v37, v3 :: v_dual_mov_b32 v36, v2
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v39, v1 :: v_dual_mov_b32 v38, v0
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v8
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr1
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr2
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr3
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr5
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr6
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr7
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr9
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr10
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr11
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr13
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr14
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr15
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr17
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr18
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr19
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr21
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr22
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr23
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr25
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr26
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr27
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr29
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr30
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr31
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB84_2
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v32
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v18, 16, v34
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v34
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v14, 16, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v10, 16, v36
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v36
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v6, 16, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v38
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[27:28], 24, v[32:33]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[19:20], 24, v[34:35]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[11:12], 24, v[36:37]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[38:39]
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v38
; GFX11-FAKE16-NEXT:  .LBB84_2: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB84_4
; GFX11-FAKE16-NEXT:  ; %bb.3: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_add_f64 v[32:33], v[32:33], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[34:35], v[34:35], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[36:37], v[36:37], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[38:39], v[38:39], 1.0
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[27:28], 24, v[32:33]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[19:20], 24, v[34:35]
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[11:12], 24, v[36:37]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[38:39]
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v32
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v18, 16, v34
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v34
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v14, 16, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v10, 16, v36
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v36
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v6, 16, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v38
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v38
; GFX11-FAKE16-NEXT:  .LBB84_4: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v0, v38
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v4, v39
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v8, v36
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v12, v37
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v16, v34
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v20, v35
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v24, v32
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v28, v33
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <4 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <4 x double> %a1 to <32 x i8>
  br label %end

cmp.false:
  %a3 = bitcast <4 x double> %a to <32 x i8>
  br label %end

end:
  %phi = phi <32 x i8> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x i8> %phi
}

define inreg <32 x i8> @bitcast_v4f64_to_v32i8_scalar(<4 x double> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v4f64_to_v32i8_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB85_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_lshr_b32 s75, s23, 24
; SI-NEXT:    s_lshr_b32 s74, s23, 16
; SI-NEXT:    s_lshr_b32 s73, s23, 8
; SI-NEXT:    s_lshr_b32 s72, s21, 24
; SI-NEXT:    s_lshr_b32 s63, s21, 16
; SI-NEXT:    s_lshr_b32 s62, s21, 8
; SI-NEXT:    s_lshr_b32 s61, s19, 24
; SI-NEXT:    s_lshr_b32 s60, s19, 16
; SI-NEXT:    s_lshr_b32 s59, s19, 8
; SI-NEXT:    s_lshr_b32 s58, s17, 24
; SI-NEXT:    s_lshr_b32 s57, s17, 16
; SI-NEXT:    s_lshr_b32 s56, s17, 8
; SI-NEXT:    s_lshr_b64 s[4:5], s[22:23], 24
; SI-NEXT:    s_lshr_b64 s[6:7], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[8:9], s[22:23], 8
; SI-NEXT:    s_lshr_b64 s[10:11], s[20:21], 24
; SI-NEXT:    s_lshr_b64 s[12:13], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[14:15], s[20:21], 8
; SI-NEXT:    s_lshr_b64 s[24:25], s[18:19], 24
; SI-NEXT:    s_lshr_b64 s[26:27], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[28:29], s[18:19], 8
; SI-NEXT:    s_lshr_b64 s[40:41], s[16:17], 24
; SI-NEXT:    s_lshr_b64 s[42:43], s[16:17], 16
; SI-NEXT:    s_lshr_b64 s[44:45], s[16:17], 8
; SI-NEXT:    s_cbranch_execnz .LBB85_4
; SI-NEXT:  .LBB85_2: ; %cmp.true
; SI-NEXT:    v_add_f64 v[50:51], s[22:23], 1.0
; SI-NEXT:    v_add_f64 v[37:38], s[20:21], 1.0
; SI-NEXT:    v_add_f64 v[48:49], s[16:17], 1.0
; SI-NEXT:    v_add_f64 v[35:36], s[18:19], 1.0
; SI-NEXT:    v_lshr_b64 v[24:25], v[50:51], 16
; SI-NEXT:    v_lshr_b64 v[32:33], v[37:38], 16
; SI-NEXT:    v_lshr_b64 v[0:1], v[48:49], 16
; SI-NEXT:    v_lshr_b64 v[27:28], v[50:51], 24
; SI-NEXT:    v_lshr_b64 v[25:26], v[50:51], 8
; SI-NEXT:    v_lshr_b64 v[19:20], v[37:38], 24
; SI-NEXT:    v_lshr_b64 v[17:18], v[37:38], 8
; SI-NEXT:    v_lshr_b64 v[11:12], v[35:36], 24
; SI-NEXT:    v_lshr_b64 v[33:34], v[35:36], 16
; SI-NEXT:    v_lshr_b64 v[9:10], v[35:36], 8
; SI-NEXT:    v_lshr_b64 v[3:4], v[48:49], 24
; SI-NEXT:    v_lshr_b64 v[1:2], v[48:49], 8
; SI-NEXT:    v_lshrrev_b32_e32 v31, 24, v51
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v51
; SI-NEXT:    v_lshrrev_b32_e32 v29, 8, v51
; SI-NEXT:    v_lshrrev_b32_e32 v23, 24, v38
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v38
; SI-NEXT:    v_lshrrev_b32_e32 v21, 8, v38
; SI-NEXT:    v_lshrrev_b32_e32 v15, 24, v36
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v36
; SI-NEXT:    v_lshrrev_b32_e32 v13, 8, v36
; SI-NEXT:    v_lshrrev_b32_e32 v7, 24, v49
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v49
; SI-NEXT:    v_lshrrev_b32_e32 v5, 8, v49
; SI-NEXT:    s_branch .LBB85_5
; SI-NEXT:  .LBB85_3:
; SI-NEXT:    ; implicit-def: $sgpr44
; SI-NEXT:    ; implicit-def: $sgpr42
; SI-NEXT:    ; implicit-def: $sgpr40
; SI-NEXT:    ; implicit-def: $sgpr56
; SI-NEXT:    ; implicit-def: $sgpr57
; SI-NEXT:    ; implicit-def: $sgpr58
; SI-NEXT:    ; implicit-def: $sgpr28
; SI-NEXT:    ; implicit-def: $sgpr26
; SI-NEXT:    ; implicit-def: $sgpr24
; SI-NEXT:    ; implicit-def: $sgpr59
; SI-NEXT:    ; implicit-def: $sgpr60
; SI-NEXT:    ; implicit-def: $sgpr61
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr12
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr62
; SI-NEXT:    ; implicit-def: $sgpr63
; SI-NEXT:    ; implicit-def: $sgpr72
; SI-NEXT:    ; implicit-def: $sgpr8
; SI-NEXT:    ; implicit-def: $sgpr6
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr73
; SI-NEXT:    ; implicit-def: $sgpr74
; SI-NEXT:    ; implicit-def: $sgpr75
; SI-NEXT:    s_branch .LBB85_2
; SI-NEXT:  .LBB85_4:
; SI-NEXT:    v_mov_b32_e32 v51, s23
; SI-NEXT:    v_mov_b32_e32 v38, s21
; SI-NEXT:    v_mov_b32_e32 v36, s19
; SI-NEXT:    v_mov_b32_e32 v49, s17
; SI-NEXT:    v_mov_b32_e32 v48, s16
; SI-NEXT:    v_mov_b32_e32 v35, s18
; SI-NEXT:    v_mov_b32_e32 v37, s20
; SI-NEXT:    v_mov_b32_e32 v50, s22
; SI-NEXT:    v_mov_b32_e32 v31, s75
; SI-NEXT:    v_mov_b32_e32 v30, s74
; SI-NEXT:    v_mov_b32_e32 v29, s73
; SI-NEXT:    v_mov_b32_e32 v23, s72
; SI-NEXT:    v_mov_b32_e32 v22, s63
; SI-NEXT:    v_mov_b32_e32 v21, s62
; SI-NEXT:    v_mov_b32_e32 v15, s61
; SI-NEXT:    v_mov_b32_e32 v14, s60
; SI-NEXT:    v_mov_b32_e32 v13, s59
; SI-NEXT:    v_mov_b32_e32 v7, s58
; SI-NEXT:    v_mov_b32_e32 v6, s57
; SI-NEXT:    v_mov_b32_e32 v5, s56
; SI-NEXT:    v_mov_b32_e32 v1, s44
; SI-NEXT:    v_mov_b32_e32 v0, s42
; SI-NEXT:    v_mov_b32_e32 v3, s40
; SI-NEXT:    v_mov_b32_e32 v9, s28
; SI-NEXT:    v_mov_b32_e32 v33, s26
; SI-NEXT:    v_mov_b32_e32 v11, s24
; SI-NEXT:    v_mov_b32_e32 v17, s14
; SI-NEXT:    v_mov_b32_e32 v32, s12
; SI-NEXT:    v_mov_b32_e32 v19, s10
; SI-NEXT:    v_mov_b32_e32 v25, s8
; SI-NEXT:    v_mov_b32_e32 v24, s6
; SI-NEXT:    v_mov_b32_e32 v27, s4
; SI-NEXT:  .LBB85_5: ; %end
; SI-NEXT:    v_mov_b32_e32 v2, v0
; SI-NEXT:    v_mov_b32_e32 v0, v48
; SI-NEXT:    v_mov_b32_e32 v4, v49
; SI-NEXT:    v_mov_b32_e32 v10, v33
; SI-NEXT:    v_mov_b32_e32 v8, v35
; SI-NEXT:    v_mov_b32_e32 v12, v36
; SI-NEXT:    v_mov_b32_e32 v18, v32
; SI-NEXT:    v_mov_b32_e32 v16, v37
; SI-NEXT:    v_mov_b32_e32 v20, v38
; SI-NEXT:    v_mov_b32_e32 v26, v24
; SI-NEXT:    v_mov_b32_e32 v24, v50
; SI-NEXT:    v_mov_b32_e32 v28, v51
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v4f64_to_v32i8_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB85_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_lshr_b32 s43, s23, 24
; VI-NEXT:    s_lshr_b32 s42, s23, 16
; VI-NEXT:    s_lshr_b32 s41, s23, 8
; VI-NEXT:    s_lshr_b32 s45, s22, 16
; VI-NEXT:    s_lshr_b32 s44, s22, 8
; VI-NEXT:    s_lshr_b32 s40, s21, 24
; VI-NEXT:    s_lshr_b32 s29, s21, 16
; VI-NEXT:    s_lshr_b32 s28, s21, 8
; VI-NEXT:    s_lshr_b32 s47, s20, 16
; VI-NEXT:    s_lshr_b32 s46, s20, 8
; VI-NEXT:    s_lshr_b32 s27, s19, 24
; VI-NEXT:    s_lshr_b32 s26, s19, 16
; VI-NEXT:    s_lshr_b32 s25, s19, 8
; VI-NEXT:    s_lshr_b32 s57, s18, 16
; VI-NEXT:    s_lshr_b32 s56, s18, 8
; VI-NEXT:    s_lshr_b32 s24, s17, 24
; VI-NEXT:    s_lshr_b32 s15, s17, 16
; VI-NEXT:    s_lshr_b32 s14, s17, 8
; VI-NEXT:    s_lshr_b32 s59, s16, 16
; VI-NEXT:    s_lshr_b32 s58, s16, 8
; VI-NEXT:    s_lshr_b64 s[10:11], s[22:23], 24
; VI-NEXT:    s_lshr_b64 s[8:9], s[20:21], 24
; VI-NEXT:    s_lshr_b64 s[6:7], s[18:19], 24
; VI-NEXT:    s_lshr_b64 s[4:5], s[16:17], 24
; VI-NEXT:    s_cbranch_execnz .LBB85_4
; VI-NEXT:  .LBB85_2: ; %cmp.true
; VI-NEXT:    v_add_f64 v[0:1], s[16:17], 1.0
; VI-NEXT:    v_add_f64 v[8:9], s[18:19], 1.0
; VI-NEXT:    v_add_f64 v[16:17], s[20:21], 1.0
; VI-NEXT:    v_add_f64 v[24:25], s[22:23], 1.0
; VI-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; VI-NEXT:    v_lshrrev_b64 v[11:12], 24, v[8:9]
; VI-NEXT:    v_lshrrev_b64 v[19:20], 24, v[16:17]
; VI-NEXT:    v_lshrrev_b64 v[27:28], 24, v[24:25]
; VI-NEXT:    v_lshrrev_b32_e32 v31, 24, v25
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v25
; VI-NEXT:    v_lshrrev_b32_e32 v29, 8, v25
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v24
; VI-NEXT:    v_lshrrev_b32_e32 v32, 8, v24
; VI-NEXT:    v_lshrrev_b32_e32 v23, 24, v17
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; VI-NEXT:    v_lshrrev_b32_e32 v21, 8, v17
; VI-NEXT:    v_lshrrev_b32_e32 v18, 16, v16
; VI-NEXT:    v_lshrrev_b32_e32 v33, 8, v16
; VI-NEXT:    v_lshrrev_b32_e32 v15, 24, v9
; VI-NEXT:    v_lshrrev_b32_e32 v14, 16, v9
; VI-NEXT:    v_lshrrev_b32_e32 v13, 8, v9
; VI-NEXT:    v_lshrrev_b32_e32 v10, 16, v8
; VI-NEXT:    v_lshrrev_b32_e32 v34, 8, v8
; VI-NEXT:    v_lshrrev_b32_e32 v7, 24, v1
; VI-NEXT:    v_lshrrev_b32_e32 v6, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; VI-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; VI-NEXT:    v_lshrrev_b32_e32 v35, 8, v0
; VI-NEXT:    s_branch .LBB85_5
; VI-NEXT:  .LBB85_3:
; VI-NEXT:    ; implicit-def: $sgpr58
; VI-NEXT:    ; implicit-def: $sgpr59
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr14
; VI-NEXT:    ; implicit-def: $sgpr15
; VI-NEXT:    ; implicit-def: $sgpr24
; VI-NEXT:    ; implicit-def: $sgpr56
; VI-NEXT:    ; implicit-def: $sgpr57
; VI-NEXT:    ; implicit-def: $sgpr6
; VI-NEXT:    ; implicit-def: $sgpr25
; VI-NEXT:    ; implicit-def: $sgpr26
; VI-NEXT:    ; implicit-def: $sgpr27
; VI-NEXT:    ; implicit-def: $sgpr46
; VI-NEXT:    ; implicit-def: $sgpr47
; VI-NEXT:    ; implicit-def: $sgpr8
; VI-NEXT:    ; implicit-def: $sgpr28
; VI-NEXT:    ; implicit-def: $sgpr29
; VI-NEXT:    ; implicit-def: $sgpr40
; VI-NEXT:    ; implicit-def: $sgpr44
; VI-NEXT:    ; implicit-def: $sgpr45
; VI-NEXT:    ; implicit-def: $sgpr10
; VI-NEXT:    ; implicit-def: $sgpr41
; VI-NEXT:    ; implicit-def: $sgpr42
; VI-NEXT:    ; implicit-def: $sgpr43
; VI-NEXT:    s_branch .LBB85_2
; VI-NEXT:  .LBB85_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v8, s18
; VI-NEXT:    v_mov_b32_e32 v16, s20
; VI-NEXT:    v_mov_b32_e32 v24, s22
; VI-NEXT:    v_mov_b32_e32 v25, s23
; VI-NEXT:    v_mov_b32_e32 v17, s21
; VI-NEXT:    v_mov_b32_e32 v9, s19
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s59
; VI-NEXT:    v_mov_b32_e32 v35, s58
; VI-NEXT:    v_mov_b32_e32 v10, s57
; VI-NEXT:    v_mov_b32_e32 v34, s56
; VI-NEXT:    v_mov_b32_e32 v18, s47
; VI-NEXT:    v_mov_b32_e32 v33, s46
; VI-NEXT:    v_mov_b32_e32 v26, s45
; VI-NEXT:    v_mov_b32_e32 v32, s44
; VI-NEXT:    v_mov_b32_e32 v31, s43
; VI-NEXT:    v_mov_b32_e32 v30, s42
; VI-NEXT:    v_mov_b32_e32 v29, s41
; VI-NEXT:    v_mov_b32_e32 v23, s40
; VI-NEXT:    v_mov_b32_e32 v22, s29
; VI-NEXT:    v_mov_b32_e32 v21, s28
; VI-NEXT:    v_mov_b32_e32 v15, s27
; VI-NEXT:    v_mov_b32_e32 v14, s26
; VI-NEXT:    v_mov_b32_e32 v13, s25
; VI-NEXT:    v_mov_b32_e32 v7, s24
; VI-NEXT:    v_mov_b32_e32 v6, s15
; VI-NEXT:    v_mov_b32_e32 v5, s14
; VI-NEXT:    v_mov_b32_e32 v3, s4
; VI-NEXT:    v_mov_b32_e32 v11, s6
; VI-NEXT:    v_mov_b32_e32 v19, s8
; VI-NEXT:    v_mov_b32_e32 v27, s10
; VI-NEXT:  .LBB85_5: ; %end
; VI-NEXT:    v_mov_b32_e32 v4, v1
; VI-NEXT:    v_mov_b32_e32 v12, v9
; VI-NEXT:    v_mov_b32_e32 v20, v17
; VI-NEXT:    v_mov_b32_e32 v28, v25
; VI-NEXT:    v_mov_b32_e32 v1, v35
; VI-NEXT:    v_mov_b32_e32 v9, v34
; VI-NEXT:    v_mov_b32_e32 v17, v33
; VI-NEXT:    v_mov_b32_e32 v25, v32
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v4f64_to_v32i8_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB85_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_lshr_b32 s43, s23, 24
; GFX9-NEXT:    s_lshr_b32 s42, s23, 16
; GFX9-NEXT:    s_lshr_b32 s41, s23, 8
; GFX9-NEXT:    s_lshr_b32 s45, s22, 16
; GFX9-NEXT:    s_lshr_b32 s44, s22, 8
; GFX9-NEXT:    s_lshr_b32 s40, s21, 24
; GFX9-NEXT:    s_lshr_b32 s29, s21, 16
; GFX9-NEXT:    s_lshr_b32 s28, s21, 8
; GFX9-NEXT:    s_lshr_b32 s47, s20, 16
; GFX9-NEXT:    s_lshr_b32 s46, s20, 8
; GFX9-NEXT:    s_lshr_b32 s27, s19, 24
; GFX9-NEXT:    s_lshr_b32 s26, s19, 16
; GFX9-NEXT:    s_lshr_b32 s25, s19, 8
; GFX9-NEXT:    s_lshr_b32 s57, s18, 16
; GFX9-NEXT:    s_lshr_b32 s56, s18, 8
; GFX9-NEXT:    s_lshr_b32 s24, s17, 24
; GFX9-NEXT:    s_lshr_b32 s15, s17, 16
; GFX9-NEXT:    s_lshr_b32 s14, s17, 8
; GFX9-NEXT:    s_lshr_b32 s59, s16, 16
; GFX9-NEXT:    s_lshr_b32 s58, s16, 8
; GFX9-NEXT:    s_lshr_b64 s[10:11], s[22:23], 24
; GFX9-NEXT:    s_lshr_b64 s[8:9], s[20:21], 24
; GFX9-NEXT:    s_lshr_b64 s[6:7], s[18:19], 24
; GFX9-NEXT:    s_lshr_b64 s[4:5], s[16:17], 24
; GFX9-NEXT:    s_cbranch_execnz .LBB85_4
; GFX9-NEXT:  .LBB85_2: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[0:1], s[16:17], 1.0
; GFX9-NEXT:    v_add_f64 v[8:9], s[18:19], 1.0
; GFX9-NEXT:    v_add_f64 v[16:17], s[20:21], 1.0
; GFX9-NEXT:    v_add_f64 v[24:25], s[22:23], 1.0
; GFX9-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; GFX9-NEXT:    v_lshrrev_b64 v[11:12], 24, v[8:9]
; GFX9-NEXT:    v_lshrrev_b64 v[19:20], 24, v[16:17]
; GFX9-NEXT:    v_lshrrev_b64 v[27:28], 24, v[24:25]
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 24, v25
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v25
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 8, v25
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v24
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 8, v24
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 24, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 8, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v18, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 8, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v15, 24, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v14, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v13, 8, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v10, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 8, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v7, 24, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v6, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 8, v0
; GFX9-NEXT:    s_branch .LBB85_5
; GFX9-NEXT:  .LBB85_3:
; GFX9-NEXT:    ; implicit-def: $sgpr58
; GFX9-NEXT:    ; implicit-def: $sgpr59
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr14
; GFX9-NEXT:    ; implicit-def: $sgpr15
; GFX9-NEXT:    ; implicit-def: $sgpr24
; GFX9-NEXT:    ; implicit-def: $sgpr56
; GFX9-NEXT:    ; implicit-def: $sgpr57
; GFX9-NEXT:    ; implicit-def: $sgpr6
; GFX9-NEXT:    ; implicit-def: $sgpr25
; GFX9-NEXT:    ; implicit-def: $sgpr26
; GFX9-NEXT:    ; implicit-def: $sgpr27
; GFX9-NEXT:    ; implicit-def: $sgpr46
; GFX9-NEXT:    ; implicit-def: $sgpr47
; GFX9-NEXT:    ; implicit-def: $sgpr8
; GFX9-NEXT:    ; implicit-def: $sgpr28
; GFX9-NEXT:    ; implicit-def: $sgpr29
; GFX9-NEXT:    ; implicit-def: $sgpr40
; GFX9-NEXT:    ; implicit-def: $sgpr44
; GFX9-NEXT:    ; implicit-def: $sgpr45
; GFX9-NEXT:    ; implicit-def: $sgpr10
; GFX9-NEXT:    ; implicit-def: $sgpr41
; GFX9-NEXT:    ; implicit-def: $sgpr42
; GFX9-NEXT:    ; implicit-def: $sgpr43
; GFX9-NEXT:    s_branch .LBB85_2
; GFX9-NEXT:  .LBB85_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v8, s18
; GFX9-NEXT:    v_mov_b32_e32 v16, s20
; GFX9-NEXT:    v_mov_b32_e32 v24, s22
; GFX9-NEXT:    v_mov_b32_e32 v25, s23
; GFX9-NEXT:    v_mov_b32_e32 v17, s21
; GFX9-NEXT:    v_mov_b32_e32 v9, s19
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s59
; GFX9-NEXT:    v_mov_b32_e32 v35, s58
; GFX9-NEXT:    v_mov_b32_e32 v10, s57
; GFX9-NEXT:    v_mov_b32_e32 v34, s56
; GFX9-NEXT:    v_mov_b32_e32 v18, s47
; GFX9-NEXT:    v_mov_b32_e32 v33, s46
; GFX9-NEXT:    v_mov_b32_e32 v26, s45
; GFX9-NEXT:    v_mov_b32_e32 v32, s44
; GFX9-NEXT:    v_mov_b32_e32 v31, s43
; GFX9-NEXT:    v_mov_b32_e32 v30, s42
; GFX9-NEXT:    v_mov_b32_e32 v29, s41
; GFX9-NEXT:    v_mov_b32_e32 v23, s40
; GFX9-NEXT:    v_mov_b32_e32 v22, s29
; GFX9-NEXT:    v_mov_b32_e32 v21, s28
; GFX9-NEXT:    v_mov_b32_e32 v15, s27
; GFX9-NEXT:    v_mov_b32_e32 v14, s26
; GFX9-NEXT:    v_mov_b32_e32 v13, s25
; GFX9-NEXT:    v_mov_b32_e32 v7, s24
; GFX9-NEXT:    v_mov_b32_e32 v6, s15
; GFX9-NEXT:    v_mov_b32_e32 v5, s14
; GFX9-NEXT:    v_mov_b32_e32 v3, s4
; GFX9-NEXT:    v_mov_b32_e32 v11, s6
; GFX9-NEXT:    v_mov_b32_e32 v19, s8
; GFX9-NEXT:    v_mov_b32_e32 v27, s10
; GFX9-NEXT:  .LBB85_5: ; %end
; GFX9-NEXT:    v_mov_b32_e32 v4, v1
; GFX9-NEXT:    v_mov_b32_e32 v12, v9
; GFX9-NEXT:    v_mov_b32_e32 v20, v17
; GFX9-NEXT:    v_mov_b32_e32 v28, v25
; GFX9-NEXT:    v_mov_b32_e32 v1, v35
; GFX9-NEXT:    v_mov_b32_e32 v9, v34
; GFX9-NEXT:    v_mov_b32_e32 v17, v33
; GFX9-NEXT:    v_mov_b32_e32 v25, v32
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v4f64_to_v32i8_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s12, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB85_3
; GFX11-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-NEXT:    s_lshr_b32 s28, s19, 24
; GFX11-NEXT:    s_lshr_b32 s27, s19, 16
; GFX11-NEXT:    s_lshr_b32 s26, s19, 8
; GFX11-NEXT:    s_lshr_b32 s40, s18, 16
; GFX11-NEXT:    s_lshr_b32 s29, s18, 8
; GFX11-NEXT:    s_lshr_b32 s25, s17, 24
; GFX11-NEXT:    s_lshr_b32 s24, s17, 16
; GFX11-NEXT:    s_lshr_b32 s23, s17, 8
; GFX11-NEXT:    s_lshr_b32 s42, s16, 16
; GFX11-NEXT:    s_lshr_b32 s41, s16, 8
; GFX11-NEXT:    s_lshr_b32 s22, s3, 24
; GFX11-NEXT:    s_lshr_b32 s21, s3, 16
; GFX11-NEXT:    s_lshr_b32 s20, s3, 8
; GFX11-NEXT:    s_lshr_b32 s44, s2, 16
; GFX11-NEXT:    s_lshr_b32 s43, s2, 8
; GFX11-NEXT:    s_lshr_b32 s15, s1, 24
; GFX11-NEXT:    s_lshr_b32 s14, s1, 16
; GFX11-NEXT:    s_lshr_b32 s13, s1, 8
; GFX11-NEXT:    s_lshr_b32 s46, s0, 16
; GFX11-NEXT:    s_lshr_b32 s45, s0, 8
; GFX11-NEXT:    s_lshr_b64 s[10:11], s[18:19], 24
; GFX11-NEXT:    s_lshr_b64 s[8:9], s[16:17], 24
; GFX11-NEXT:    s_lshr_b64 s[6:7], s[2:3], 24
; GFX11-NEXT:    s_lshr_b64 s[4:5], s[0:1], 24
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s12
; GFX11-NEXT:    s_cbranch_vccnz .LBB85_4
; GFX11-NEXT:  .LBB85_2: ; %cmp.true
; GFX11-NEXT:    v_add_f64 v[32:33], s[18:19], 1.0
; GFX11-NEXT:    v_add_f64 v[34:35], s[16:17], 1.0
; GFX11-NEXT:    v_add_f64 v[36:37], s[2:3], 1.0
; GFX11-NEXT:    v_add_f64 v[38:39], s[0:1], 1.0
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_lshrrev_b64 v[27:28], 24, v[32:33]
; GFX11-NEXT:    v_lshrrev_b64 v[19:20], 24, v[34:35]
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-NEXT:    v_lshrrev_b64 v[11:12], 24, v[36:37]
; GFX11-NEXT:    v_lshrrev_b64 v[3:4], 24, v[38:39]
; GFX11-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-NEXT:    v_lshrrev_b32_e32 v30, 16, v33
; GFX11-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-NEXT:    v_lshrrev_b32_e32 v26, 16, v32
; GFX11-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-NEXT:    v_lshrrev_b32_e32 v23, 24, v35
; GFX11-NEXT:    v_lshrrev_b32_e32 v22, 16, v35
; GFX11-NEXT:    v_lshrrev_b32_e32 v21, 8, v35
; GFX11-NEXT:    v_lshrrev_b32_e32 v18, 16, v34
; GFX11-NEXT:    v_lshrrev_b32_e32 v17, 8, v34
; GFX11-NEXT:    v_lshrrev_b32_e32 v15, 24, v37
; GFX11-NEXT:    v_lshrrev_b32_e32 v14, 16, v37
; GFX11-NEXT:    v_lshrrev_b32_e32 v13, 8, v37
; GFX11-NEXT:    v_lshrrev_b32_e32 v10, 16, v36
; GFX11-NEXT:    v_lshrrev_b32_e32 v9, 8, v36
; GFX11-NEXT:    v_lshrrev_b32_e32 v7, 24, v39
; GFX11-NEXT:    v_lshrrev_b32_e32 v6, 16, v39
; GFX11-NEXT:    v_lshrrev_b32_e32 v5, 8, v39
; GFX11-NEXT:    v_lshrrev_b32_e32 v2, 16, v38
; GFX11-NEXT:    v_lshrrev_b32_e32 v1, 8, v38
; GFX11-NEXT:    s_branch .LBB85_5
; GFX11-NEXT:  .LBB85_3:
; GFX11-NEXT:    ; implicit-def: $sgpr45
; GFX11-NEXT:    ; implicit-def: $sgpr46
; GFX11-NEXT:    ; implicit-def: $sgpr4
; GFX11-NEXT:    ; implicit-def: $sgpr13
; GFX11-NEXT:    ; implicit-def: $sgpr14
; GFX11-NEXT:    ; implicit-def: $sgpr15
; GFX11-NEXT:    ; implicit-def: $sgpr43
; GFX11-NEXT:    ; implicit-def: $sgpr44
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr20
; GFX11-NEXT:    ; implicit-def: $sgpr21
; GFX11-NEXT:    ; implicit-def: $sgpr22
; GFX11-NEXT:    ; implicit-def: $sgpr41
; GFX11-NEXT:    ; implicit-def: $sgpr42
; GFX11-NEXT:    ; implicit-def: $sgpr8
; GFX11-NEXT:    ; implicit-def: $sgpr23
; GFX11-NEXT:    ; implicit-def: $sgpr24
; GFX11-NEXT:    ; implicit-def: $sgpr25
; GFX11-NEXT:    ; implicit-def: $sgpr29
; GFX11-NEXT:    ; implicit-def: $sgpr40
; GFX11-NEXT:    ; implicit-def: $sgpr10
; GFX11-NEXT:    ; implicit-def: $sgpr26
; GFX11-NEXT:    ; implicit-def: $sgpr27
; GFX11-NEXT:    ; implicit-def: $sgpr28
; GFX11-NEXT:    s_branch .LBB85_2
; GFX11-NEXT:  .LBB85_4:
; GFX11-NEXT:    v_dual_mov_b32 v38, s0 :: v_dual_mov_b32 v33, s19
; GFX11-NEXT:    v_dual_mov_b32 v36, s2 :: v_dual_mov_b32 v35, s17
; GFX11-NEXT:    v_dual_mov_b32 v34, s16 :: v_dual_mov_b32 v37, s3
; GFX11-NEXT:    v_dual_mov_b32 v32, s18 :: v_dual_mov_b32 v39, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s46 :: v_dual_mov_b32 v1, s45
; GFX11-NEXT:    v_dual_mov_b32 v10, s44 :: v_dual_mov_b32 v9, s43
; GFX11-NEXT:    v_dual_mov_b32 v18, s42 :: v_dual_mov_b32 v17, s41
; GFX11-NEXT:    v_dual_mov_b32 v26, s40 :: v_dual_mov_b32 v25, s29
; GFX11-NEXT:    v_dual_mov_b32 v3, s4 :: v_dual_mov_b32 v30, s27
; GFX11-NEXT:    v_dual_mov_b32 v11, s6 :: v_dual_mov_b32 v22, s24
; GFX11-NEXT:    v_dual_mov_b32 v19, s8 :: v_dual_mov_b32 v14, s21
; GFX11-NEXT:    v_dual_mov_b32 v27, s10 :: v_dual_mov_b32 v6, s14
; GFX11-NEXT:    v_mov_b32_e32 v31, s28
; GFX11-NEXT:    v_mov_b32_e32 v29, s26
; GFX11-NEXT:    v_mov_b32_e32 v23, s25
; GFX11-NEXT:    v_mov_b32_e32 v21, s23
; GFX11-NEXT:    v_mov_b32_e32 v15, s22
; GFX11-NEXT:    v_mov_b32_e32 v13, s20
; GFX11-NEXT:    v_mov_b32_e32 v7, s15
; GFX11-NEXT:    v_mov_b32_e32 v5, s13
; GFX11-NEXT:  .LBB85_5: ; %end
; GFX11-NEXT:    v_mov_b32_e32 v0, v38
; GFX11-NEXT:    v_mov_b32_e32 v4, v39
; GFX11-NEXT:    v_mov_b32_e32 v8, v36
; GFX11-NEXT:    v_mov_b32_e32 v12, v37
; GFX11-NEXT:    v_mov_b32_e32 v16, v34
; GFX11-NEXT:    v_mov_b32_e32 v20, v35
; GFX11-NEXT:    v_mov_b32_e32 v24, v32
; GFX11-NEXT:    v_mov_b32_e32 v28, v33
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <4 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <4 x double> %a1 to <32 x i8>
  br label %end

cmp.false:
  %a3 = bitcast <4 x double> %a to <32 x i8>
  br label %end

end:
  %phi = phi <32 x i8> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x i8> %phi
}

define <4 x double> @bitcast_v32i8_to_v4f64(<32 x i8> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v32i8_to_v4f64:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_mov_b32_e32 v32, v2
; SI-NEXT:    v_mov_b32_e32 v31, v0
; SI-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:4
; SI-NEXT:    buffer_load_dword v2, off, s[0:3], s32
; SI-NEXT:    v_mov_b32_e32 v34, v6
; SI-NEXT:    v_mov_b32_e32 v33, v4
; SI-NEXT:    v_lshlrev_b32_e32 v52, 8, v1
; SI-NEXT:    v_lshlrev_b32_e32 v51, 24, v3
; SI-NEXT:    v_lshlrev_b32_e32 v50, 8, v5
; SI-NEXT:    v_lshlrev_b32_e32 v49, 24, v7
; SI-NEXT:    v_lshlrev_b32_e32 v48, 8, v9
; SI-NEXT:    v_lshlrev_b32_e32 v39, 24, v11
; SI-NEXT:    v_lshlrev_b32_e32 v38, 8, v13
; SI-NEXT:    v_lshlrev_b32_e32 v37, 24, v15
; SI-NEXT:    v_lshlrev_b32_e32 v36, 8, v17
; SI-NEXT:    v_lshlrev_b32_e32 v35, 24, v19
; SI-NEXT:    v_lshlrev_b32_e32 v19, 8, v21
; SI-NEXT:    v_lshlrev_b32_e32 v17, 24, v23
; SI-NEXT:    v_lshlrev_b32_e32 v15, 8, v25
; SI-NEXT:    v_lshlrev_b32_e32 v13, 24, v27
; SI-NEXT:    v_lshlrev_b32_e32 v11, 8, v29
; SI-NEXT:    s_waitcnt vmcnt(1)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v0
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_lshlrev_b32_e32 v9, 24, v2
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB86_3
; SI-NEXT:  ; %bb.1: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB86_4
; SI-NEXT:  .LBB86_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB86_3: ; %cmp.false
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v31
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v32
; SI-NEXT:    v_or_b32_e32 v0, v0, v52
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_or_b32_e32 v1, v51, v1
; SI-NEXT:    v_or_b32_e32 v0, v0, v1
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v33
; SI-NEXT:    v_and_b32_e32 v2, 0xff, v34
; SI-NEXT:    v_or_b32_e32 v1, v1, v50
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_or_b32_e32 v2, v49, v2
; SI-NEXT:    v_or_b32_e32 v1, v1, v2
; SI-NEXT:    v_and_b32_e32 v2, 0xff, v8
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v10
; SI-NEXT:    v_or_b32_e32 v2, v2, v48
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_or_b32_e32 v3, v39, v3
; SI-NEXT:    v_or_b32_e32 v2, v2, v3
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v12
; SI-NEXT:    v_and_b32_e32 v4, 0xff, v14
; SI-NEXT:    v_or_b32_e32 v3, v3, v38
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_or_b32_e32 v4, v37, v4
; SI-NEXT:    v_or_b32_e32 v3, v3, v4
; SI-NEXT:    v_and_b32_e32 v4, 0xff, v16
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v18
; SI-NEXT:    v_or_b32_e32 v4, v4, v36
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_or_b32_e32 v5, v35, v5
; SI-NEXT:    v_or_b32_e32 v4, v4, v5
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v20
; SI-NEXT:    v_and_b32_e32 v6, 0xff, v22
; SI-NEXT:    v_or_b32_e32 v5, v5, v19
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_or_b32_e32 v6, v17, v6
; SI-NEXT:    v_or_b32_e32 v5, v5, v6
; SI-NEXT:    v_and_b32_e32 v6, 0xff, v24
; SI-NEXT:    v_and_b32_e32 v7, 0xff, v26
; SI-NEXT:    v_or_b32_e32 v6, v6, v15
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_or_b32_e32 v7, v13, v7
; SI-NEXT:    v_or_b32_e32 v6, v6, v7
; SI-NEXT:    v_and_b32_e32 v7, 0xff, v28
; SI-NEXT:    v_and_b32_e32 v8, 0xff, v30
; SI-NEXT:    v_or_b32_e32 v7, v7, v11
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_or_b32_e32 v8, v9, v8
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    ; implicit-def: $vgpr31
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr24
; SI-NEXT:    ; implicit-def: $vgpr26
; SI-NEXT:    ; implicit-def: $vgpr28
; SI-NEXT:    ; implicit-def: $vgpr30
; SI-NEXT:    ; implicit-def: $vgpr52
; SI-NEXT:    ; implicit-def: $vgpr51
; SI-NEXT:    ; implicit-def: $vgpr50
; SI-NEXT:    ; implicit-def: $vgpr49
; SI-NEXT:    ; implicit-def: $vgpr48
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB86_2
; SI-NEXT:  .LBB86_4: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v31
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v32
; SI-NEXT:    v_or_b32_e32 v0, v52, v0
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v1
; SI-NEXT:    v_add_i32_e32 v0, vcc, 0x300, v0
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_or_b32_e32 v1, v51, v1
; SI-NEXT:    v_or_b32_e32 v0, v1, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v33
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v1
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v34
; SI-NEXT:    s_movk_i32 s6, 0x300
; SI-NEXT:    v_or_b32_e32 v1, v50, v1
; SI-NEXT:    v_and_b32_e32 v2, 0xff, v2
; SI-NEXT:    v_add_i32_e32 v1, vcc, s6, v1
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_or_b32_e32 v2, v49, v2
; SI-NEXT:    v_or_b32_e32 v1, v2, v1
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v8
; SI-NEXT:    v_and_b32_e32 v2, 0xff, v2
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v10
; SI-NEXT:    v_or_b32_e32 v2, v48, v2
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v3
; SI-NEXT:    v_add_i32_e32 v2, vcc, s6, v2
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_or_b32_e32 v3, v39, v3
; SI-NEXT:    v_or_b32_e32 v2, v3, v2
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v12
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v3
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v14
; SI-NEXT:    v_or_b32_e32 v3, v38, v3
; SI-NEXT:    v_and_b32_e32 v4, 0xff, v4
; SI-NEXT:    v_add_i32_e32 v3, vcc, s6, v3
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_or_b32_e32 v4, v37, v4
; SI-NEXT:    v_or_b32_e32 v3, v4, v3
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v16
; SI-NEXT:    v_and_b32_e32 v4, 0xff, v4
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v18
; SI-NEXT:    v_or_b32_e32 v4, v36, v4
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v5
; SI-NEXT:    v_add_i32_e32 v4, vcc, s6, v4
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_or_b32_e32 v5, v35, v5
; SI-NEXT:    v_or_b32_e32 v4, v5, v4
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v20
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v5
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v22
; SI-NEXT:    v_or_b32_e32 v5, v19, v5
; SI-NEXT:    v_and_b32_e32 v6, 0xff, v6
; SI-NEXT:    v_add_i32_e32 v5, vcc, s6, v5
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_or_b32_e32 v6, v17, v6
; SI-NEXT:    v_or_b32_e32 v5, v6, v5
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v24
; SI-NEXT:    v_and_b32_e32 v6, 0xff, v6
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v26
; SI-NEXT:    v_or_b32_e32 v6, v15, v6
; SI-NEXT:    v_and_b32_e32 v7, 0xff, v7
; SI-NEXT:    v_add_i32_e32 v6, vcc, s6, v6
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_or_b32_e32 v7, v13, v7
; SI-NEXT:    v_or_b32_e32 v6, v7, v6
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v28
; SI-NEXT:    v_and_b32_e32 v7, 0xff, v7
; SI-NEXT:    v_add_i32_e32 v8, vcc, 3, v30
; SI-NEXT:    v_or_b32_e32 v7, v11, v7
; SI-NEXT:    v_and_b32_e32 v8, 0xff, v8
; SI-NEXT:    v_add_i32_e32 v7, vcc, 0x300, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_or_b32_e32 v8, v9, v8
; SI-NEXT:    s_mov_b32 s7, 0x3000000
; SI-NEXT:    v_or_b32_e32 v7, v8, v7
; SI-NEXT:    v_add_i32_e32 v0, vcc, s7, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, s7, v1
; SI-NEXT:    v_add_i32_e32 v2, vcc, s7, v2
; SI-NEXT:    v_add_i32_e32 v3, vcc, s7, v3
; SI-NEXT:    v_add_i32_e32 v4, vcc, s7, v4
; SI-NEXT:    v_add_i32_e32 v5, vcc, s7, v5
; SI-NEXT:    v_add_i32_e32 v6, vcc, 0x3000000, v6
; SI-NEXT:    v_add_i32_e32 v7, vcc, 0x3000000, v7
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v32i8_to_v4f64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_mov_b32_e32 v38, v0
; VI-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:4
; VI-NEXT:    buffer_load_ushort v39, off, s[0:3], s32
; VI-NEXT:    v_mov_b32_e32 v31, v7
; VI-NEXT:    v_mov_b32_e32 v32, v6
; VI-NEXT:    v_mov_b32_e32 v33, v5
; VI-NEXT:    v_mov_b32_e32 v34, v4
; VI-NEXT:    v_mov_b32_e32 v35, v3
; VI-NEXT:    v_mov_b32_e32 v36, v2
; VI-NEXT:    v_mov_b32_e32 v37, v1
; VI-NEXT:    s_waitcnt vmcnt(1)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v0
; VI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execnz .LBB86_3
; VI-NEXT:  ; %bb.1: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execnz .LBB86_4
; VI-NEXT:  .LBB86_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB86_3: ; %cmp.false
; VI-NEXT:    s_mov_b32 s6, 0xc0c0004
; VI-NEXT:    v_perm_b32 v1, v36, v35, s6
; VI-NEXT:    v_perm_b32 v0, v38, v37, s6
; VI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_perm_b32 v2, v32, v31, s6
; VI-NEXT:    v_or_b32_e32 v0, v0, v1
; VI-NEXT:    v_perm_b32 v1, v34, v33, s6
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_perm_b32 v3, v10, v11, s6
; VI-NEXT:    v_or_b32_e32 v1, v1, v2
; VI-NEXT:    v_perm_b32 v2, v8, v9, s6
; VI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_perm_b32 v4, v14, v15, s6
; VI-NEXT:    v_or_b32_e32 v2, v2, v3
; VI-NEXT:    v_perm_b32 v3, v12, v13, s6
; VI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_perm_b32 v5, v18, v19, s6
; VI-NEXT:    v_or_b32_e32 v3, v3, v4
; VI-NEXT:    v_perm_b32 v4, v16, v17, s6
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_perm_b32 v6, v22, v23, s6
; VI-NEXT:    v_or_b32_e32 v4, v4, v5
; VI-NEXT:    v_perm_b32 v5, v20, v21, s6
; VI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_perm_b32 v7, v26, v27, s6
; VI-NEXT:    v_or_b32_e32 v5, v5, v6
; VI-NEXT:    v_perm_b32 v6, v24, v25, s6
; VI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    v_perm_b32 v8, v30, v39, s6
; VI-NEXT:    v_or_b32_e32 v6, v6, v7
; VI-NEXT:    v_perm_b32 v7, v28, v29, s6
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; VI-NEXT:    v_or_b32_e32 v7, v7, v8
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr35
; VI-NEXT:    ; implicit-def: $vgpr34
; VI-NEXT:    ; implicit-def: $vgpr33
; VI-NEXT:    ; implicit-def: $vgpr32
; VI-NEXT:    ; implicit-def: $vgpr31
; VI-NEXT:    ; implicit-def: $vgpr8
; VI-NEXT:    ; implicit-def: $vgpr9
; VI-NEXT:    ; implicit-def: $vgpr10
; VI-NEXT:    ; implicit-def: $vgpr11
; VI-NEXT:    ; implicit-def: $vgpr12
; VI-NEXT:    ; implicit-def: $vgpr13
; VI-NEXT:    ; implicit-def: $vgpr14
; VI-NEXT:    ; implicit-def: $vgpr15
; VI-NEXT:    ; implicit-def: $vgpr16
; VI-NEXT:    ; implicit-def: $vgpr17
; VI-NEXT:    ; implicit-def: $vgpr18
; VI-NEXT:    ; implicit-def: $vgpr19
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr21
; VI-NEXT:    ; implicit-def: $vgpr22
; VI-NEXT:    ; implicit-def: $vgpr23
; VI-NEXT:    ; implicit-def: $vgpr24
; VI-NEXT:    ; implicit-def: $vgpr25
; VI-NEXT:    ; implicit-def: $vgpr26
; VI-NEXT:    ; implicit-def: $vgpr27
; VI-NEXT:    ; implicit-def: $vgpr28
; VI-NEXT:    ; implicit-def: $vgpr29
; VI-NEXT:    ; implicit-def: $vgpr30
; VI-NEXT:    ; implicit-def: $vgpr39
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB86_2
; VI-NEXT:  .LBB86_4: ; %cmp.true
; VI-NEXT:    v_add_u16_e32 v0, 3, v38
; VI-NEXT:    v_lshlrev_b16_e32 v1, 8, v37
; VI-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v1, 3, v36
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v35
; VI-NEXT:    v_or_b32_sdwa v1, v2, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_mov_b32_e32 v7, 0x300
; VI-NEXT:    v_add_u16_e32 v2, 3, v34
; VI-NEXT:    v_lshlrev_b16_e32 v3, 8, v33
; VI-NEXT:    v_add_u16_e32 v0, 0x300, v0
; VI-NEXT:    v_add_u16_sdwa v1, v1, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v2, v3, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_or_b32_e32 v0, v0, v1
; VI-NEXT:    v_add_u16_e32 v1, 0x300, v2
; VI-NEXT:    v_add_u16_e32 v2, 3, v32
; VI-NEXT:    v_lshlrev_b16_e32 v3, 8, v31
; VI-NEXT:    v_or_b32_sdwa v2, v3, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_sdwa v2, v2, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v1, v1, v2
; VI-NEXT:    v_add_u16_e32 v2, 3, v8
; VI-NEXT:    v_lshlrev_b16_e32 v3, 8, v9
; VI-NEXT:    v_or_b32_sdwa v2, v3, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v3, 3, v10
; VI-NEXT:    v_lshlrev_b16_e32 v4, 8, v11
; VI-NEXT:    v_or_b32_sdwa v3, v4, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v2, 0x300, v2
; VI-NEXT:    v_add_u16_sdwa v3, v3, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v2, v2, v3
; VI-NEXT:    v_add_u16_e32 v3, 3, v12
; VI-NEXT:    v_lshlrev_b16_e32 v4, 8, v13
; VI-NEXT:    v_or_b32_sdwa v3, v4, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v4, 3, v14
; VI-NEXT:    v_lshlrev_b16_e32 v5, 8, v15
; VI-NEXT:    v_or_b32_sdwa v4, v5, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v3, 0x300, v3
; VI-NEXT:    v_add_u16_sdwa v4, v4, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v3, v3, v4
; VI-NEXT:    v_add_u16_e32 v4, 3, v16
; VI-NEXT:    v_lshlrev_b16_e32 v5, 8, v17
; VI-NEXT:    v_or_b32_sdwa v4, v5, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v5, 3, v18
; VI-NEXT:    v_lshlrev_b16_e32 v6, 8, v19
; VI-NEXT:    v_or_b32_sdwa v5, v6, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v4, 0x300, v4
; VI-NEXT:    v_add_u16_sdwa v5, v5, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v4, v4, v5
; VI-NEXT:    v_add_u16_e32 v5, 3, v20
; VI-NEXT:    v_lshlrev_b16_e32 v6, 8, v21
; VI-NEXT:    v_or_b32_sdwa v5, v6, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v6, 3, v22
; VI-NEXT:    v_lshlrev_b16_e32 v8, 8, v23
; VI-NEXT:    v_or_b32_sdwa v6, v8, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v5, 0x300, v5
; VI-NEXT:    v_add_u16_sdwa v6, v6, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v5, v5, v6
; VI-NEXT:    v_add_u16_e32 v6, 3, v24
; VI-NEXT:    v_lshlrev_b16_e32 v8, 8, v25
; VI-NEXT:    v_or_b32_sdwa v6, v8, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v8, 3, v26
; VI-NEXT:    v_lshlrev_b16_e32 v9, 8, v27
; VI-NEXT:    v_or_b32_sdwa v8, v9, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v6, 0x300, v6
; VI-NEXT:    v_add_u16_sdwa v8, v8, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v6, v6, v8
; VI-NEXT:    v_add_u16_e32 v8, 3, v28
; VI-NEXT:    v_lshlrev_b16_e32 v9, 8, v29
; VI-NEXT:    v_or_b32_sdwa v8, v9, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v9, 3, v30
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    v_lshlrev_b16_e32 v10, 8, v39
; VI-NEXT:    v_or_b32_sdwa v9, v10, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v8, 0x300, v8
; VI-NEXT:    v_add_u16_sdwa v7, v9, v7 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v7, v8, v7
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v32i8_to_v4f64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_mov_b32_e32 v38, v0
; GFX9-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:4
; GFX9-NEXT:    buffer_load_ushort v39, off, s[0:3], s32
; GFX9-NEXT:    v_mov_b32_e32 v31, v7
; GFX9-NEXT:    v_mov_b32_e32 v32, v6
; GFX9-NEXT:    v_mov_b32_e32 v33, v5
; GFX9-NEXT:    v_mov_b32_e32 v34, v4
; GFX9-NEXT:    v_mov_b32_e32 v35, v3
; GFX9-NEXT:    v_mov_b32_e32 v36, v2
; GFX9-NEXT:    v_mov_b32_e32 v37, v1
; GFX9-NEXT:    s_waitcnt vmcnt(1)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v0
; GFX9-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execnz .LBB86_3
; GFX9-NEXT:  ; %bb.1: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execnz .LBB86_4
; GFX9-NEXT:  .LBB86_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB86_3: ; %cmp.false
; GFX9-NEXT:    s_mov_b32 s6, 0xc0c0004
; GFX9-NEXT:    v_perm_b32 v0, v38, v37, s6
; GFX9-NEXT:    v_perm_b32 v1, v36, v35, s6
; GFX9-NEXT:    v_lshl_or_b32 v0, v1, 16, v0
; GFX9-NEXT:    v_perm_b32 v1, v34, v33, s6
; GFX9-NEXT:    v_perm_b32 v2, v32, v31, s6
; GFX9-NEXT:    v_lshl_or_b32 v1, v2, 16, v1
; GFX9-NEXT:    v_perm_b32 v2, v8, v9, s6
; GFX9-NEXT:    v_perm_b32 v3, v10, v11, s6
; GFX9-NEXT:    v_lshl_or_b32 v2, v3, 16, v2
; GFX9-NEXT:    v_perm_b32 v3, v12, v13, s6
; GFX9-NEXT:    v_perm_b32 v4, v14, v15, s6
; GFX9-NEXT:    v_lshl_or_b32 v3, v4, 16, v3
; GFX9-NEXT:    v_perm_b32 v4, v16, v17, s6
; GFX9-NEXT:    v_perm_b32 v5, v18, v19, s6
; GFX9-NEXT:    v_lshl_or_b32 v4, v5, 16, v4
; GFX9-NEXT:    v_perm_b32 v5, v20, v21, s6
; GFX9-NEXT:    v_perm_b32 v6, v22, v23, s6
; GFX9-NEXT:    v_lshl_or_b32 v5, v6, 16, v5
; GFX9-NEXT:    v_perm_b32 v6, v24, v25, s6
; GFX9-NEXT:    v_perm_b32 v7, v26, v27, s6
; GFX9-NEXT:    v_lshl_or_b32 v6, v7, 16, v6
; GFX9-NEXT:    v_perm_b32 v7, v28, v29, s6
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    v_perm_b32 v8, v30, v39, s6
; GFX9-NEXT:    v_lshl_or_b32 v7, v8, 16, v7
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr35
; GFX9-NEXT:    ; implicit-def: $vgpr34
; GFX9-NEXT:    ; implicit-def: $vgpr33
; GFX9-NEXT:    ; implicit-def: $vgpr32
; GFX9-NEXT:    ; implicit-def: $vgpr31
; GFX9-NEXT:    ; implicit-def: $vgpr8
; GFX9-NEXT:    ; implicit-def: $vgpr9
; GFX9-NEXT:    ; implicit-def: $vgpr10
; GFX9-NEXT:    ; implicit-def: $vgpr11
; GFX9-NEXT:    ; implicit-def: $vgpr12
; GFX9-NEXT:    ; implicit-def: $vgpr13
; GFX9-NEXT:    ; implicit-def: $vgpr14
; GFX9-NEXT:    ; implicit-def: $vgpr15
; GFX9-NEXT:    ; implicit-def: $vgpr16
; GFX9-NEXT:    ; implicit-def: $vgpr17
; GFX9-NEXT:    ; implicit-def: $vgpr18
; GFX9-NEXT:    ; implicit-def: $vgpr19
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr21
; GFX9-NEXT:    ; implicit-def: $vgpr22
; GFX9-NEXT:    ; implicit-def: $vgpr23
; GFX9-NEXT:    ; implicit-def: $vgpr24
; GFX9-NEXT:    ; implicit-def: $vgpr25
; GFX9-NEXT:    ; implicit-def: $vgpr26
; GFX9-NEXT:    ; implicit-def: $vgpr27
; GFX9-NEXT:    ; implicit-def: $vgpr28
; GFX9-NEXT:    ; implicit-def: $vgpr29
; GFX9-NEXT:    ; implicit-def: $vgpr30
; GFX9-NEXT:    ; implicit-def: $vgpr39
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB86_2
; GFX9-NEXT:  .LBB86_4: ; %cmp.true
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v38
; GFX9-NEXT:    v_lshlrev_b16_e32 v1, 8, v37
; GFX9-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v1, 3, v36
; GFX9-NEXT:    v_lshlrev_b16_e32 v2, 8, v35
; GFX9-NEXT:    s_movk_i32 s6, 0x300
; GFX9-NEXT:    v_or_b32_sdwa v1, v2, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v0, 0x300, v0
; GFX9-NEXT:    v_add_u16_sdwa v1, v1, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v0, v0, v1
; GFX9-NEXT:    v_add_u16_e32 v1, 3, v34
; GFX9-NEXT:    v_lshlrev_b16_e32 v2, 8, v33
; GFX9-NEXT:    v_or_b32_sdwa v1, v2, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v2, 3, v32
; GFX9-NEXT:    v_lshlrev_b16_e32 v3, 8, v31
; GFX9-NEXT:    v_or_b32_sdwa v2, v3, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v1, 0x300, v1
; GFX9-NEXT:    v_add_u16_sdwa v2, v2, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v1, v1, v2
; GFX9-NEXT:    v_add_u16_e32 v2, 3, v8
; GFX9-NEXT:    v_lshlrev_b16_e32 v3, 8, v9
; GFX9-NEXT:    v_or_b32_sdwa v2, v3, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v3, 3, v10
; GFX9-NEXT:    v_lshlrev_b16_e32 v4, 8, v11
; GFX9-NEXT:    v_or_b32_sdwa v3, v4, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v2, 0x300, v2
; GFX9-NEXT:    v_add_u16_sdwa v3, v3, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v2, v2, v3
; GFX9-NEXT:    v_add_u16_e32 v3, 3, v12
; GFX9-NEXT:    v_lshlrev_b16_e32 v4, 8, v13
; GFX9-NEXT:    v_or_b32_sdwa v3, v4, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v4, 3, v14
; GFX9-NEXT:    v_lshlrev_b16_e32 v5, 8, v15
; GFX9-NEXT:    v_or_b32_sdwa v4, v5, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v3, 0x300, v3
; GFX9-NEXT:    v_add_u16_sdwa v4, v4, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v3, v3, v4
; GFX9-NEXT:    v_add_u16_e32 v4, 3, v16
; GFX9-NEXT:    v_lshlrev_b16_e32 v5, 8, v17
; GFX9-NEXT:    v_or_b32_sdwa v4, v5, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v5, 3, v18
; GFX9-NEXT:    v_lshlrev_b16_e32 v6, 8, v19
; GFX9-NEXT:    v_or_b32_sdwa v5, v6, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v4, 0x300, v4
; GFX9-NEXT:    v_add_u16_sdwa v5, v5, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v4, v4, v5
; GFX9-NEXT:    v_add_u16_e32 v5, 3, v20
; GFX9-NEXT:    v_lshlrev_b16_e32 v6, 8, v21
; GFX9-NEXT:    v_or_b32_sdwa v5, v6, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v6, 3, v22
; GFX9-NEXT:    v_lshlrev_b16_e32 v7, 8, v23
; GFX9-NEXT:    v_or_b32_sdwa v6, v7, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v5, 0x300, v5
; GFX9-NEXT:    v_add_u16_sdwa v6, v6, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v5, v5, v6
; GFX9-NEXT:    v_add_u16_e32 v6, 3, v24
; GFX9-NEXT:    v_lshlrev_b16_e32 v7, 8, v25
; GFX9-NEXT:    v_or_b32_sdwa v6, v7, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v7, 3, v26
; GFX9-NEXT:    v_lshlrev_b16_e32 v8, 8, v27
; GFX9-NEXT:    v_or_b32_sdwa v7, v8, v7 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v6, 0x300, v6
; GFX9-NEXT:    v_add_u16_sdwa v7, v7, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v6, v6, v7
; GFX9-NEXT:    v_add_u16_e32 v7, 3, v28
; GFX9-NEXT:    v_lshlrev_b16_e32 v8, 8, v29
; GFX9-NEXT:    v_or_b32_sdwa v7, v8, v7 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v8, 3, v30
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    v_lshlrev_b16_e32 v9, 8, v39
; GFX9-NEXT:    v_or_b32_sdwa v8, v9, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v7, 0x300, v7
; GFX9-NEXT:    v_add_u16_sdwa v8, v8, s6 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_e32 v7, v7, v8
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v32i8_to_v4f64:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_clause 0x1
; GFX11-TRUE16-NEXT:    scratch_load_b32 v48, off, s32 offset:4
; GFX11-TRUE16-NEXT:    scratch_load_d16_b16 v31, off, s32
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v32.l, v7.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v33.l, v6.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v34.l, v5.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v35.l, v4.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v36.l, v3.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v37.l, v2.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v38.l, v1.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v39.l, v0.l
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(1)
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v48
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB86_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB86_4
; GFX11-TRUE16-NEXT:  .LBB86_2: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB86_3: ; %cmp.false
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr39_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr38_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v0, v39, v38, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr37_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr36_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, v37, v36, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr35_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr34_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v2, v35, v34, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr33_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr32_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v3, v33, v32, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr8_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v4, v8, v9, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr10_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr11_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, v10, v11, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr12_hi16
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v0, v1, 16, v0
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr14_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr15_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr16_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr17_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr18_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr19_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v6, v18, v19, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v1, v3, 16, v2
; GFX11-TRUE16-NEXT:    v_perm_b32 v3, v12, v13, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v2, v5, 16, v4
; GFX11-TRUE16-NEXT:    v_perm_b32 v4, v14, v15, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, v16, v17, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr21_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v7, v20, v21, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr22_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr23_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v8, v22, v23, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr24_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr25_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v9, v24, v25, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr26_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr27_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v10, v26, v27, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr28_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr29_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v11, v28, v29, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr30_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr31_hi16
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-TRUE16-NEXT:    v_perm_b32 v12, v30, v31, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v3, v4, 16, v3
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v4, v6, 16, v5
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v5, v8, 16, v7
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v6, v10, 16, v9
; GFX11-TRUE16-NEXT:    v_lshl_or_b32 v7, v12, 16, v11
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr39_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr38_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr37_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr36_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr35_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr34_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr33_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr32_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr8_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr10_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr11_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr12_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr14_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr15_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr16_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr17_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr18_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr19_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr21_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr22_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr23_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr24_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr25_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr26_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr27_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr28_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr29_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr30_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr31_lo16
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB86_2
; GFX11-TRUE16-NEXT:  .LBB86_4: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.l, v39.l, 3
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v0.h, 8, v38.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.l, v37.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.l, v35.l, 3
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v1.h, 8, v36.l
; GFX11-TRUE16-NEXT:    v_and_b16 v0.l, 0xff, v0.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v2.h, 8, v34.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v3.l, v33.l, 3
; GFX11-TRUE16-NEXT:    v_and_b16 v1.l, 0xff, v1.l
; GFX11-TRUE16-NEXT:    v_and_b16 v2.l, 0xff, v2.l
; GFX11-TRUE16-NEXT:    v_or_b16 v0.l, v0.h, v0.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.h, v8.l, 3
; GFX11-TRUE16-NEXT:    v_and_b16 v3.l, 0xff, v3.l
; GFX11-TRUE16-NEXT:    v_or_b16 v1.l, v1.h, v1.l
; GFX11-TRUE16-NEXT:    v_or_b16 v1.h, v2.h, v2.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v2.l, 8, v32.l
; GFX11-TRUE16-NEXT:    v_and_b16 v2.h, 0xff, v0.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v3.h, 8, v9.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v4.l, v10.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.h, 0x300, v1.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.l, 0x300, v1.h
; GFX11-TRUE16-NEXT:    v_or_b16 v1.h, v2.l, v3.l
; GFX11-TRUE16-NEXT:    v_or_b16 v2.l, v3.h, v2.h
; GFX11-TRUE16-NEXT:    v_and_b16 v2.h, 0xff, v4.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v3.l, 8, v11.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v3.h, v12.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v4.l, v14.l, 3
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v4.h, 8, v15.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v5.l, v16.l, 3
; GFX11-TRUE16-NEXT:    v_or_b16 v2.h, v3.l, v2.h
; GFX11-TRUE16-NEXT:    v_and_b16 v3.l, 0xff, v3.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v3.h, 8, v13.l
; GFX11-TRUE16-NEXT:    v_and_b16 v4.l, 0xff, v4.l
; GFX11-TRUE16-NEXT:    v_and_b16 v5.l, 0xff, v5.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v5.h, 8, v17.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v6.l, 8, v19.l
; GFX11-TRUE16-NEXT:    v_or_b16 v3.l, v3.h, v3.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v3.h, v18.l, 3
; GFX11-TRUE16-NEXT:    v_or_b16 v4.l, v4.h, v4.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v4.h, v20.l, 3
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v6.h, 8, v21.l
; GFX11-TRUE16-NEXT:    v_or_b16 v5.l, v5.h, v5.l
; GFX11-TRUE16-NEXT:    v_and_b16 v3.h, 0xff, v3.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v7.l, v26.l, 3
; GFX11-TRUE16-NEXT:    v_and_b16 v4.h, 0xff, v4.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v7.h, v28.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v8.h, v30.l, 3
; GFX11-TRUE16-NEXT:    v_or_b16 v5.h, v6.l, v3.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v3.h, 0x300, v4.l
; GFX11-TRUE16-NEXT:    v_or_b16 v6.l, v6.h, v4.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v6.h, v22.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v4.l, 0x300, v5.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v4.h, 0x300, v5.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v5.h, v24.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v5.l, 0x300, v6.l
; GFX11-TRUE16-NEXT:    v_and_b16 v6.l, 0xff, v6.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v6.h, 8, v23.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v8.l, 8, v25.l
; GFX11-TRUE16-NEXT:    v_and_b16 v5.h, 0xff, v5.h
; GFX11-TRUE16-NEXT:    v_and_b16 v7.l, 0xff, v7.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v9.l, 8, v27.l
; GFX11-TRUE16-NEXT:    v_and_b16 v7.h, 0xff, v7.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v9.h, 8, v29.l
; GFX11-TRUE16-NEXT:    v_and_b16 v8.h, 0xff, v8.h
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v10.l, 8, v31.l
; GFX11-TRUE16-NEXT:    v_or_b16 v6.l, v6.h, v6.l
; GFX11-TRUE16-NEXT:    v_or_b16 v6.h, v8.l, v5.h
; GFX11-TRUE16-NEXT:    v_or_b16 v7.l, v9.l, v7.l
; GFX11-TRUE16-NEXT:    v_or_b16 v7.h, v9.h, v7.h
; GFX11-TRUE16-NEXT:    v_or_b16 v8.l, v10.l, v8.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.l, 0x300, v0.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.h, 0x300, v1.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.l, 0x300, v2.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.h, 0x300, v2.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v3.l, 0x300, v3.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v5.h, 0x300, v6.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v6.l, 0x300, v6.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v6.h, 0x300, v7.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v7.l, 0x300, v7.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v7.h, 0x300, v8.l
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v32i8_to_v4f64:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v37, v1 :: v_dual_mov_b32 v38, v0
; GFX11-FAKE16-NEXT:    s_clause 0x1
; GFX11-FAKE16-NEXT:    scratch_load_b32 v0, off, s32 offset:4
; GFX11-FAKE16-NEXT:    scratch_load_u16 v39, off, s32
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v31, v7 :: v_dual_mov_b32 v32, v6
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v33, v5 :: v_dual_mov_b32 v34, v4
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v35, v3 :: v_dual_mov_b32 v36, v2
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(1)
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v0
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB86_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB86_4
; GFX11-FAKE16-NEXT:  .LBB86_2: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB86_3: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v38, v37, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v36, v35, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v34, v33, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v32, v31, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v8, v9, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v10, v11, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v0, v1, 16, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v18, v19, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v1, v3, 16, v2
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v12, v13, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v2, v5, 16, v4
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v14, v15, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v16, v17, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v20, v21, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, v22, v23, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, v24, v25, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, v26, v27, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, v28, v29, 0xc0c0004
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, v30, v39, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v3, v4, 16, v3
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v4, v6, 16, v5
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v5, v8, 16, v7
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v6, v10, 16, v9
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v7, v12, 16, v11
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr38
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr37
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr36
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr35
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr34
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr33
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr32
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr31
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr8
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr9
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr10
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr11
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr12
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr13
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr14
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr15
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr16
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr17
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr18
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr19
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr21
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr22
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr23
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr24
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr25
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr26
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr27
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr28
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr29
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr30
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr39
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB86_2
; GFX11-FAKE16-NEXT:  .LBB86_4: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v0, v38, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v2, v36, 3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v1, 8, v37
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v3, 8, v35
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v4, v34, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xff, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v6, v32, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xff, v2
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v5, 8, v33
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v7, 8, v31
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v1, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v1, v8, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xff, v4
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v6, 0xff, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, v3, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, v10, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v0, 0x300, v0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, v5, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v5, v7, v6
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v2, 0x300, v2
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v1, 0xff, v1
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v6, 8, v9
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xff, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v7, 8, v11
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v1, v6, v1
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v4, 0x300, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v7, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v5, 0x300, v5
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v0, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v2, 0x300, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, 0x300, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v6, v12, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v8, 8, v17
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v1, v4, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v4, v14, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xff, v6
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v6, 8, v13
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, v2, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, v16, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xff, v4
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v7, 8, v15
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v5, v6, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v6, v18, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xff, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v9, 8, v19
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, v7, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v7, v20, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v6, 0xff, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v8, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v10, 8, v21
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v8, v22, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v7, 0xff, v7
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v6, v9, v6
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, 0x300, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v11, v26, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v12, v28, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v14, v30, 3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v7, v10, v7
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v9, 0xffff, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, v24, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v8, 0xff, v8
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v10, 8, v23
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v13, 8, v25
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v11, 0xff, v11
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xff, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v15, 8, v27
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v12, 0xff, v12
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v16, 8, v29
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v14, 0xff, v14
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v17, 8, v39
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v8, v10, v8
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v13, v3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v10, v15, v11
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, v16, v12
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, v17, v14
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v5, 0x300, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v4, 0x300, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v6, 0x300, v6
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v7, 0x300, v7
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v8, 0x300, v8
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, 0x300, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v10, 0x300, v10
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v11, 0x300, v11
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v12, 0x300, v12
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v13, 0xffff, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v10, 16, v10
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v12, 16, v12
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v5, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, v9, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v5, v7, v8
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v6, v13, v10
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v7, v11, v12
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <32 x i8> %a, splat (i8 3)
  %a2 = bitcast <32 x i8> %a1 to <4 x double>
  br label %end

cmp.false:
  %a3 = bitcast <32 x i8> %a to <4 x double>
  br label %end

end:
  %phi = phi <4 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x double> %phi
}

define inreg <4 x double> @bitcast_v32i8_to_v4f64_scalar(<32 x i8> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v32i8_to_v4f64_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_readfirstlane_b32 s4, v18
; SI-NEXT:    v_readfirstlane_b32 s14, v17
; SI-NEXT:    v_readfirstlane_b32 s15, v16
; SI-NEXT:    v_readfirstlane_b32 s40, v15
; SI-NEXT:    v_readfirstlane_b32 s41, v14
; SI-NEXT:    v_readfirstlane_b32 s42, v13
; SI-NEXT:    v_readfirstlane_b32 s43, v12
; SI-NEXT:    v_readfirstlane_b32 s44, v11
; SI-NEXT:    v_readfirstlane_b32 s45, v10
; SI-NEXT:    v_readfirstlane_b32 s46, v9
; SI-NEXT:    v_readfirstlane_b32 s47, v8
; SI-NEXT:    v_readfirstlane_b32 s56, v7
; SI-NEXT:    v_readfirstlane_b32 s57, v6
; SI-NEXT:    v_readfirstlane_b32 s58, v5
; SI-NEXT:    v_readfirstlane_b32 s59, v4
; SI-NEXT:    v_readfirstlane_b32 s60, v3
; SI-NEXT:    v_readfirstlane_b32 s61, v2
; SI-NEXT:    v_readfirstlane_b32 s62, v1
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    v_readfirstlane_b32 s63, v0
; SI-NEXT:    s_cbranch_scc0 .LBB87_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s4, s16, 0xff
; SI-NEXT:    s_lshl_b32 s5, s17, 8
; SI-NEXT:    s_or_b32 s4, s4, s5
; SI-NEXT:    s_and_b32 s5, s18, 0xff
; SI-NEXT:    s_lshl_b32 s5, s5, 16
; SI-NEXT:    s_lshl_b32 s6, s19, 24
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_or_b32 s5, s6, s5
; SI-NEXT:    s_or_b32 s4, s4, s5
; SI-NEXT:    s_and_b32 s5, s20, 0xff
; SI-NEXT:    s_lshl_b32 s6, s21, 8
; SI-NEXT:    s_or_b32 s5, s5, s6
; SI-NEXT:    s_and_b32 s6, s22, 0xff
; SI-NEXT:    s_lshl_b32 s6, s6, 16
; SI-NEXT:    s_lshl_b32 s7, s23, 24
; SI-NEXT:    s_and_b32 s5, s5, 0xffff
; SI-NEXT:    s_or_b32 s6, s7, s6
; SI-NEXT:    s_or_b32 s5, s5, s6
; SI-NEXT:    s_and_b32 s6, s24, 0xff
; SI-NEXT:    s_lshl_b32 s7, s25, 8
; SI-NEXT:    s_or_b32 s6, s6, s7
; SI-NEXT:    s_and_b32 s7, s26, 0xff
; SI-NEXT:    s_lshl_b32 s7, s7, 16
; SI-NEXT:    s_lshl_b32 s8, s27, 24
; SI-NEXT:    s_and_b32 s6, s6, 0xffff
; SI-NEXT:    s_or_b32 s7, s8, s7
; SI-NEXT:    s_or_b32 s6, s6, s7
; SI-NEXT:    s_and_b32 s7, s28, 0xff
; SI-NEXT:    s_lshl_b32 s8, s29, 8
; SI-NEXT:    s_or_b32 s7, s7, s8
; SI-NEXT:    s_and_b32 s8, s63, 0xff
; SI-NEXT:    s_lshl_b32 s8, s8, 16
; SI-NEXT:    s_lshl_b32 s9, s62, 24
; SI-NEXT:    s_and_b32 s7, s7, 0xffff
; SI-NEXT:    s_or_b32 s8, s9, s8
; SI-NEXT:    s_or_b32 s7, s7, s8
; SI-NEXT:    s_and_b32 s8, s61, 0xff
; SI-NEXT:    s_lshl_b32 s9, s60, 8
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_and_b32 s9, s59, 0xff
; SI-NEXT:    s_lshl_b32 s9, s9, 16
; SI-NEXT:    s_lshl_b32 s10, s58, 24
; SI-NEXT:    s_and_b32 s8, s8, 0xffff
; SI-NEXT:    s_or_b32 s9, s10, s9
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_and_b32 s9, s57, 0xff
; SI-NEXT:    s_lshl_b32 s10, s56, 8
; SI-NEXT:    s_or_b32 s9, s9, s10
; SI-NEXT:    s_and_b32 s10, s47, 0xff
; SI-NEXT:    s_lshl_b32 s10, s10, 16
; SI-NEXT:    s_lshl_b32 s11, s46, 24
; SI-NEXT:    s_and_b32 s9, s9, 0xffff
; SI-NEXT:    s_or_b32 s10, s11, s10
; SI-NEXT:    s_or_b32 s9, s9, s10
; SI-NEXT:    s_and_b32 s10, s45, 0xff
; SI-NEXT:    s_lshl_b32 s11, s44, 8
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_and_b32 s11, s43, 0xff
; SI-NEXT:    s_lshl_b32 s11, s11, 16
; SI-NEXT:    s_lshl_b32 s12, s42, 24
; SI-NEXT:    s_and_b32 s10, s10, 0xffff
; SI-NEXT:    s_or_b32 s11, s12, s11
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_and_b32 s11, s41, 0xff
; SI-NEXT:    s_lshl_b32 s12, s40, 8
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    s_and_b32 s12, s15, 0xff
; SI-NEXT:    s_lshl_b32 s12, s12, 16
; SI-NEXT:    s_lshl_b32 s13, s14, 24
; SI-NEXT:    s_and_b32 s11, s11, 0xffff
; SI-NEXT:    s_or_b32 s12, s13, s12
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    s_cbranch_execnz .LBB87_3
; SI-NEXT:  .LBB87_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    s_and_b32 s4, s16, 0xff
; SI-NEXT:    s_lshl_b32 s5, s17, 8
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_and_b32 s6, s18, 0xff
; SI-NEXT:    s_addk_i32 s4, 0x300
; SI-NEXT:    s_lshl_b32 s5, s19, 24
; SI-NEXT:    s_lshl_b32 s6, s6, 16
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_or_b32 s5, s5, s6
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_and_b32 s5, s20, 0xff
; SI-NEXT:    s_lshl_b32 s6, s21, 8
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_or_b32 s5, s6, s5
; SI-NEXT:    s_and_b32 s7, s22, 0xff
; SI-NEXT:    s_addk_i32 s5, 0x300
; SI-NEXT:    s_lshl_b32 s6, s23, 24
; SI-NEXT:    s_lshl_b32 s7, s7, 16
; SI-NEXT:    s_and_b32 s5, s5, 0xffff
; SI-NEXT:    s_or_b32 s6, s6, s7
; SI-NEXT:    s_add_i32 s24, s24, 3
; SI-NEXT:    s_or_b32 s5, s6, s5
; SI-NEXT:    s_and_b32 s6, s24, 0xff
; SI-NEXT:    s_lshl_b32 s7, s25, 8
; SI-NEXT:    s_add_i32 s26, s26, 3
; SI-NEXT:    s_or_b32 s6, s7, s6
; SI-NEXT:    s_and_b32 s8, s26, 0xff
; SI-NEXT:    s_addk_i32 s6, 0x300
; SI-NEXT:    s_lshl_b32 s7, s27, 24
; SI-NEXT:    s_lshl_b32 s8, s8, 16
; SI-NEXT:    s_and_b32 s6, s6, 0xffff
; SI-NEXT:    s_or_b32 s7, s7, s8
; SI-NEXT:    s_add_i32 s28, s28, 3
; SI-NEXT:    s_or_b32 s6, s7, s6
; SI-NEXT:    s_and_b32 s7, s28, 0xff
; SI-NEXT:    s_lshl_b32 s8, s29, 8
; SI-NEXT:    s_add_i32 s63, s63, 3
; SI-NEXT:    s_or_b32 s7, s8, s7
; SI-NEXT:    s_and_b32 s9, s63, 0xff
; SI-NEXT:    s_addk_i32 s7, 0x300
; SI-NEXT:    s_lshl_b32 s8, s62, 24
; SI-NEXT:    s_lshl_b32 s9, s9, 16
; SI-NEXT:    s_and_b32 s7, s7, 0xffff
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_add_i32 s61, s61, 3
; SI-NEXT:    s_or_b32 s7, s8, s7
; SI-NEXT:    s_and_b32 s8, s61, 0xff
; SI-NEXT:    s_lshl_b32 s9, s60, 8
; SI-NEXT:    s_add_i32 s59, s59, 3
; SI-NEXT:    s_or_b32 s8, s9, s8
; SI-NEXT:    s_and_b32 s10, s59, 0xff
; SI-NEXT:    s_addk_i32 s8, 0x300
; SI-NEXT:    s_lshl_b32 s9, s58, 24
; SI-NEXT:    s_lshl_b32 s10, s10, 16
; SI-NEXT:    s_and_b32 s8, s8, 0xffff
; SI-NEXT:    s_or_b32 s9, s9, s10
; SI-NEXT:    s_add_i32 s57, s57, 3
; SI-NEXT:    s_or_b32 s8, s9, s8
; SI-NEXT:    s_and_b32 s9, s57, 0xff
; SI-NEXT:    s_lshl_b32 s10, s56, 8
; SI-NEXT:    s_add_i32 s47, s47, 3
; SI-NEXT:    s_or_b32 s9, s10, s9
; SI-NEXT:    s_and_b32 s11, s47, 0xff
; SI-NEXT:    s_addk_i32 s9, 0x300
; SI-NEXT:    s_lshl_b32 s10, s46, 24
; SI-NEXT:    s_lshl_b32 s11, s11, 16
; SI-NEXT:    s_and_b32 s9, s9, 0xffff
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_add_i32 s45, s45, 3
; SI-NEXT:    s_or_b32 s9, s10, s9
; SI-NEXT:    s_and_b32 s10, s45, 0xff
; SI-NEXT:    s_lshl_b32 s11, s44, 8
; SI-NEXT:    s_add_i32 s43, s43, 3
; SI-NEXT:    s_or_b32 s10, s11, s10
; SI-NEXT:    s_and_b32 s12, s43, 0xff
; SI-NEXT:    s_addk_i32 s10, 0x300
; SI-NEXT:    s_lshl_b32 s11, s42, 24
; SI-NEXT:    s_lshl_b32 s12, s12, 16
; SI-NEXT:    s_and_b32 s10, s10, 0xffff
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    s_add_i32 s41, s41, 3
; SI-NEXT:    s_or_b32 s10, s11, s10
; SI-NEXT:    s_and_b32 s11, s41, 0xff
; SI-NEXT:    s_lshl_b32 s12, s40, 8
; SI-NEXT:    s_add_i32 s15, s15, 3
; SI-NEXT:    s_or_b32 s11, s12, s11
; SI-NEXT:    s_and_b32 s13, s15, 0xff
; SI-NEXT:    s_addk_i32 s11, 0x300
; SI-NEXT:    s_lshl_b32 s12, s14, 24
; SI-NEXT:    s_lshl_b32 s13, s13, 16
; SI-NEXT:    s_and_b32 s11, s11, 0xffff
; SI-NEXT:    s_or_b32 s12, s12, s13
; SI-NEXT:    s_or_b32 s11, s12, s11
; SI-NEXT:    s_add_i32 s4, s4, 0x3000000
; SI-NEXT:    s_add_i32 s5, s5, 0x3000000
; SI-NEXT:    s_add_i32 s6, s6, 0x3000000
; SI-NEXT:    s_add_i32 s7, s7, 0x3000000
; SI-NEXT:    s_add_i32 s8, s8, 0x3000000
; SI-NEXT:    s_add_i32 s9, s9, 0x3000000
; SI-NEXT:    s_add_i32 s10, s10, 0x3000000
; SI-NEXT:    s_add_i32 s11, s11, 0x3000000
; SI-NEXT:  .LBB87_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v0, s4
; SI-NEXT:    v_mov_b32_e32 v1, s5
; SI-NEXT:    v_mov_b32_e32 v2, s6
; SI-NEXT:    v_mov_b32_e32 v3, s7
; SI-NEXT:    v_mov_b32_e32 v4, s8
; SI-NEXT:    v_mov_b32_e32 v5, s9
; SI-NEXT:    v_mov_b32_e32 v6, s10
; SI-NEXT:    v_mov_b32_e32 v7, s11
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB87_4:
; SI-NEXT:    ; implicit-def: $sgpr4_sgpr5_sgpr6_sgpr7_sgpr8_sgpr9_sgpr10_sgpr11
; SI-NEXT:    s_branch .LBB87_2
;
; VI-LABEL: bitcast_v32i8_to_v4f64_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_readfirstlane_b32 s4, v18
; VI-NEXT:    v_readfirstlane_b32 s6, v17
; VI-NEXT:    v_readfirstlane_b32 s7, v16
; VI-NEXT:    v_readfirstlane_b32 s8, v15
; VI-NEXT:    v_readfirstlane_b32 s9, v14
; VI-NEXT:    v_readfirstlane_b32 s10, v13
; VI-NEXT:    v_readfirstlane_b32 s11, v12
; VI-NEXT:    v_readfirstlane_b32 s12, v11
; VI-NEXT:    v_readfirstlane_b32 s13, v10
; VI-NEXT:    v_readfirstlane_b32 s14, v9
; VI-NEXT:    v_readfirstlane_b32 s15, v8
; VI-NEXT:    v_readfirstlane_b32 s40, v7
; VI-NEXT:    v_readfirstlane_b32 s41, v6
; VI-NEXT:    v_readfirstlane_b32 s42, v5
; VI-NEXT:    v_readfirstlane_b32 s43, v4
; VI-NEXT:    v_readfirstlane_b32 s44, v3
; VI-NEXT:    v_readfirstlane_b32 s45, v2
; VI-NEXT:    v_readfirstlane_b32 s46, v1
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    v_readfirstlane_b32 s47, v0
; VI-NEXT:    s_cbranch_scc0 .LBB87_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_mov_b32_e32 v7, 0xc0c0004
; VI-NEXT:    v_mov_b32_e32 v1, s19
; VI-NEXT:    v_mov_b32_e32 v0, s17
; VI-NEXT:    v_perm_b32 v1, s18, v1, v7
; VI-NEXT:    v_perm_b32 v0, s16, v0, v7
; VI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_mov_b32_e32 v2, s23
; VI-NEXT:    v_or_b32_e32 v0, v0, v1
; VI-NEXT:    v_mov_b32_e32 v1, s21
; VI-NEXT:    v_perm_b32 v2, s22, v2, v7
; VI-NEXT:    v_perm_b32 v1, s20, v1, v7
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_mov_b32_e32 v3, s27
; VI-NEXT:    v_or_b32_e32 v1, v1, v2
; VI-NEXT:    v_mov_b32_e32 v2, s25
; VI-NEXT:    v_perm_b32 v3, s26, v3, v7
; VI-NEXT:    v_perm_b32 v2, s24, v2, v7
; VI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_mov_b32_e32 v4, s46
; VI-NEXT:    v_or_b32_e32 v2, v2, v3
; VI-NEXT:    v_mov_b32_e32 v3, s29
; VI-NEXT:    v_perm_b32 v4, s47, v4, v7
; VI-NEXT:    v_perm_b32 v3, s28, v3, v7
; VI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_mov_b32_e32 v5, s42
; VI-NEXT:    v_or_b32_e32 v3, v3, v4
; VI-NEXT:    v_mov_b32_e32 v4, s44
; VI-NEXT:    v_perm_b32 v5, s43, v5, v7
; VI-NEXT:    v_perm_b32 v4, s45, v4, v7
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_mov_b32_e32 v6, s14
; VI-NEXT:    v_or_b32_e32 v4, v4, v5
; VI-NEXT:    v_mov_b32_e32 v5, s40
; VI-NEXT:    v_perm_b32 v6, s15, v6, v7
; VI-NEXT:    v_perm_b32 v5, s41, v5, v7
; VI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_mov_b32_e32 v8, s10
; VI-NEXT:    v_or_b32_e32 v5, v5, v6
; VI-NEXT:    v_mov_b32_e32 v6, s12
; VI-NEXT:    v_perm_b32 v8, s11, v8, v7
; VI-NEXT:    v_perm_b32 v6, s13, v6, v7
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; VI-NEXT:    v_or_b32_e32 v6, v6, v8
; VI-NEXT:    v_mov_b32_e32 v8, s8
; VI-NEXT:    v_mov_b32_e32 v9, s6
; VI-NEXT:    v_perm_b32 v8, s9, v8, v7
; VI-NEXT:    v_perm_b32 v7, s7, v9, v7
; VI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; VI-NEXT:    v_or_b32_e32 v7, v8, v7
; VI-NEXT:    s_cbranch_execnz .LBB87_3
; VI-NEXT:  .LBB87_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s16, s16, 3
; VI-NEXT:    v_mov_b32_e32 v0, s17
; VI-NEXT:    v_mov_b32_e32 v7, 0xc0c0004
; VI-NEXT:    s_add_i32 s18, s18, 3
; VI-NEXT:    v_mov_b32_e32 v1, s19
; VI-NEXT:    v_perm_b32 v0, s16, v0, v7
; VI-NEXT:    v_perm_b32 v1, s18, v1, v7
; VI-NEXT:    v_add_u32_e32 v0, vcc, 0x300, v0
; VI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s20, s20, 3
; VI-NEXT:    v_mov_b32_e32 v1, s21
; VI-NEXT:    s_add_i32 s22, s22, 3
; VI-NEXT:    v_mov_b32_e32 v2, s23
; VI-NEXT:    v_perm_b32 v1, s20, v1, v7
; VI-NEXT:    v_perm_b32 v2, s22, v2, v7
; VI-NEXT:    v_add_u32_e32 v1, vcc, 0x300, v1
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_or_b32_sdwa v1, v2, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s24, s24, 3
; VI-NEXT:    v_mov_b32_e32 v2, s25
; VI-NEXT:    s_add_i32 s26, s26, 3
; VI-NEXT:    v_mov_b32_e32 v3, s27
; VI-NEXT:    v_perm_b32 v2, s24, v2, v7
; VI-NEXT:    v_perm_b32 v3, s26, v3, v7
; VI-NEXT:    v_add_u32_e32 v2, vcc, 0x300, v2
; VI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_or_b32_sdwa v2, v3, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s28, s28, 3
; VI-NEXT:    v_mov_b32_e32 v3, s29
; VI-NEXT:    s_add_i32 s47, s47, 3
; VI-NEXT:    v_mov_b32_e32 v4, s46
; VI-NEXT:    v_perm_b32 v3, s28, v3, v7
; VI-NEXT:    v_perm_b32 v4, s47, v4, v7
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x300, v3
; VI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_or_b32_sdwa v3, v4, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s45, s45, 3
; VI-NEXT:    v_mov_b32_e32 v4, s44
; VI-NEXT:    s_add_i32 s43, s43, 3
; VI-NEXT:    v_mov_b32_e32 v5, s42
; VI-NEXT:    v_perm_b32 v4, s45, v4, v7
; VI-NEXT:    v_perm_b32 v5, s43, v5, v7
; VI-NEXT:    v_add_u32_e32 v4, vcc, 0x300, v4
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_or_b32_sdwa v4, v5, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s41, s41, 3
; VI-NEXT:    v_mov_b32_e32 v5, s40
; VI-NEXT:    s_add_i32 s15, s15, 3
; VI-NEXT:    v_mov_b32_e32 v6, s14
; VI-NEXT:    v_perm_b32 v5, s41, v5, v7
; VI-NEXT:    v_perm_b32 v6, s15, v6, v7
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x300, v5
; VI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_or_b32_sdwa v5, v6, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s13, s13, 3
; VI-NEXT:    v_mov_b32_e32 v6, s12
; VI-NEXT:    s_add_i32 s11, s11, 3
; VI-NEXT:    v_mov_b32_e32 v8, s10
; VI-NEXT:    v_perm_b32 v6, s13, v6, v7
; VI-NEXT:    v_perm_b32 v8, s11, v8, v7
; VI-NEXT:    v_add_u32_e32 v6, vcc, 0x300, v6
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; VI-NEXT:    v_or_b32_sdwa v6, v8, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    s_add_i32 s9, s9, 3
; VI-NEXT:    v_mov_b32_e32 v8, s8
; VI-NEXT:    s_add_i32 s7, s7, 3
; VI-NEXT:    v_mov_b32_e32 v9, s6
; VI-NEXT:    v_perm_b32 v8, s9, v8, v7
; VI-NEXT:    v_perm_b32 v7, s7, v9, v7
; VI-NEXT:    v_add_u32_e32 v8, vcc, 0x300, v8
; VI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; VI-NEXT:    v_or_b32_sdwa v7, v7, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_add_u32_e32 v0, vcc, 0x3000000, v0
; VI-NEXT:    v_add_u32_e32 v1, vcc, 0x3000000, v1
; VI-NEXT:    v_add_u32_e32 v2, vcc, 0x3000000, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x3000000, v3
; VI-NEXT:    v_add_u32_e32 v4, vcc, 0x3000000, v4
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x3000000, v5
; VI-NEXT:    v_add_u32_e32 v6, vcc, 0x3000000, v6
; VI-NEXT:    v_add_u32_e32 v7, vcc, 0x3000000, v7
; VI-NEXT:  .LBB87_3: ; %end
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB87_4:
; VI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; VI-NEXT:    s_branch .LBB87_2
;
; GFX9-LABEL: bitcast_v32i8_to_v4f64_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_readfirstlane_b32 s4, v18
; GFX9-NEXT:    v_readfirstlane_b32 s6, v17
; GFX9-NEXT:    v_readfirstlane_b32 s7, v16
; GFX9-NEXT:    v_readfirstlane_b32 s8, v15
; GFX9-NEXT:    v_readfirstlane_b32 s9, v14
; GFX9-NEXT:    v_readfirstlane_b32 s10, v13
; GFX9-NEXT:    v_readfirstlane_b32 s11, v12
; GFX9-NEXT:    v_readfirstlane_b32 s12, v11
; GFX9-NEXT:    v_readfirstlane_b32 s13, v10
; GFX9-NEXT:    v_readfirstlane_b32 s14, v9
; GFX9-NEXT:    v_readfirstlane_b32 s15, v8
; GFX9-NEXT:    v_readfirstlane_b32 s40, v7
; GFX9-NEXT:    v_readfirstlane_b32 s41, v6
; GFX9-NEXT:    v_readfirstlane_b32 s42, v5
; GFX9-NEXT:    v_readfirstlane_b32 s43, v4
; GFX9-NEXT:    v_readfirstlane_b32 s44, v3
; GFX9-NEXT:    v_readfirstlane_b32 s45, v2
; GFX9-NEXT:    v_readfirstlane_b32 s46, v1
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    v_readfirstlane_b32 s47, v0
; GFX9-NEXT:    s_cbranch_scc0 .LBB87_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    v_mov_b32_e32 v7, 0xc0c0004
; GFX9-NEXT:    v_mov_b32_e32 v1, s19
; GFX9-NEXT:    v_mov_b32_e32 v0, s17
; GFX9-NEXT:    v_perm_b32 v1, s18, v1, v7
; GFX9-NEXT:    v_perm_b32 v0, s16, v0, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_mov_b32_e32 v2, s23
; GFX9-NEXT:    v_or_b32_e32 v0, v0, v1
; GFX9-NEXT:    v_mov_b32_e32 v1, s21
; GFX9-NEXT:    v_perm_b32 v2, s22, v2, v7
; GFX9-NEXT:    v_perm_b32 v1, s20, v1, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; GFX9-NEXT:    v_mov_b32_e32 v3, s27
; GFX9-NEXT:    v_or_b32_e32 v1, v1, v2
; GFX9-NEXT:    v_mov_b32_e32 v2, s25
; GFX9-NEXT:    v_perm_b32 v3, s26, v3, v7
; GFX9-NEXT:    v_perm_b32 v2, s24, v2, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; GFX9-NEXT:    v_mov_b32_e32 v4, s46
; GFX9-NEXT:    v_or_b32_e32 v2, v2, v3
; GFX9-NEXT:    v_mov_b32_e32 v3, s29
; GFX9-NEXT:    v_perm_b32 v4, s47, v4, v7
; GFX9-NEXT:    v_perm_b32 v3, s28, v3, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX9-NEXT:    v_mov_b32_e32 v5, s42
; GFX9-NEXT:    v_or_b32_e32 v3, v3, v4
; GFX9-NEXT:    v_mov_b32_e32 v4, s44
; GFX9-NEXT:    v_perm_b32 v5, s43, v5, v7
; GFX9-NEXT:    v_perm_b32 v4, s45, v4, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX9-NEXT:    v_mov_b32_e32 v6, s14
; GFX9-NEXT:    v_or_b32_e32 v4, v4, v5
; GFX9-NEXT:    v_mov_b32_e32 v5, s40
; GFX9-NEXT:    v_perm_b32 v6, s15, v6, v7
; GFX9-NEXT:    v_perm_b32 v5, s41, v5, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GFX9-NEXT:    v_mov_b32_e32 v8, s10
; GFX9-NEXT:    v_or_b32_e32 v5, v5, v6
; GFX9-NEXT:    v_mov_b32_e32 v6, s12
; GFX9-NEXT:    v_perm_b32 v8, s11, v8, v7
; GFX9-NEXT:    v_perm_b32 v6, s13, v6, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; GFX9-NEXT:    v_or_b32_e32 v6, v6, v8
; GFX9-NEXT:    v_mov_b32_e32 v8, s8
; GFX9-NEXT:    v_mov_b32_e32 v9, s6
; GFX9-NEXT:    v_perm_b32 v8, s9, v8, v7
; GFX9-NEXT:    v_perm_b32 v7, s7, v9, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; GFX9-NEXT:    v_or_b32_e32 v7, v8, v7
; GFX9-NEXT:    s_cbranch_execnz .LBB87_3
; GFX9-NEXT:  .LBB87_2: ; %cmp.true
; GFX9-NEXT:    s_add_i32 s16, s16, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s17
; GFX9-NEXT:    v_mov_b32_e32 v7, 0xc0c0004
; GFX9-NEXT:    s_add_i32 s18, s18, 3
; GFX9-NEXT:    v_mov_b32_e32 v1, s19
; GFX9-NEXT:    v_perm_b32 v0, s16, v0, v7
; GFX9-NEXT:    s_movk_i32 s4, 0x300
; GFX9-NEXT:    v_perm_b32 v1, s18, v1, v7
; GFX9-NEXT:    v_add_u32_e32 v0, 0x300, v0
; GFX9-NEXT:    v_add_u32_sdwa v1, v1, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v0, v0, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s20, s20, 3
; GFX9-NEXT:    v_mov_b32_e32 v1, s21
; GFX9-NEXT:    s_add_i32 s22, s22, 3
; GFX9-NEXT:    v_mov_b32_e32 v2, s23
; GFX9-NEXT:    v_perm_b32 v1, s20, v1, v7
; GFX9-NEXT:    v_perm_b32 v2, s22, v2, v7
; GFX9-NEXT:    v_add_u32_e32 v1, 0x300, v1
; GFX9-NEXT:    v_add_u32_sdwa v2, v2, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v1, v1, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s24, s24, 3
; GFX9-NEXT:    v_mov_b32_e32 v2, s25
; GFX9-NEXT:    s_add_i32 s26, s26, 3
; GFX9-NEXT:    v_mov_b32_e32 v3, s27
; GFX9-NEXT:    v_perm_b32 v2, s24, v2, v7
; GFX9-NEXT:    v_perm_b32 v3, s26, v3, v7
; GFX9-NEXT:    v_add_u32_e32 v2, 0x300, v2
; GFX9-NEXT:    v_add_u32_sdwa v3, v3, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v2, v2, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s28, s28, 3
; GFX9-NEXT:    v_mov_b32_e32 v3, s29
; GFX9-NEXT:    s_add_i32 s47, s47, 3
; GFX9-NEXT:    v_mov_b32_e32 v4, s46
; GFX9-NEXT:    v_perm_b32 v3, s28, v3, v7
; GFX9-NEXT:    v_perm_b32 v4, s47, v4, v7
; GFX9-NEXT:    v_add_u32_e32 v3, 0x300, v3
; GFX9-NEXT:    v_add_u32_sdwa v4, v4, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v3, v3, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s45, s45, 3
; GFX9-NEXT:    v_mov_b32_e32 v4, s44
; GFX9-NEXT:    s_add_i32 s43, s43, 3
; GFX9-NEXT:    v_mov_b32_e32 v5, s42
; GFX9-NEXT:    v_perm_b32 v4, s45, v4, v7
; GFX9-NEXT:    v_perm_b32 v5, s43, v5, v7
; GFX9-NEXT:    v_add_u32_e32 v4, 0x300, v4
; GFX9-NEXT:    v_add_u32_sdwa v5, v5, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v4, v4, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s41, s41, 3
; GFX9-NEXT:    v_mov_b32_e32 v5, s40
; GFX9-NEXT:    s_add_i32 s15, s15, 3
; GFX9-NEXT:    v_mov_b32_e32 v6, s14
; GFX9-NEXT:    v_perm_b32 v5, s41, v5, v7
; GFX9-NEXT:    v_perm_b32 v6, s15, v6, v7
; GFX9-NEXT:    v_add_u32_e32 v5, 0x300, v5
; GFX9-NEXT:    v_add_u32_sdwa v6, v6, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v5, v5, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s13, s13, 3
; GFX9-NEXT:    v_mov_b32_e32 v6, s12
; GFX9-NEXT:    s_add_i32 s11, s11, 3
; GFX9-NEXT:    v_mov_b32_e32 v8, s10
; GFX9-NEXT:    v_perm_b32 v6, s13, v6, v7
; GFX9-NEXT:    v_perm_b32 v8, s11, v8, v7
; GFX9-NEXT:    v_add_u32_e32 v6, 0x300, v6
; GFX9-NEXT:    v_add_u32_sdwa v8, v8, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v6, v6, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:    s_add_i32 s9, s9, 3
; GFX9-NEXT:    v_mov_b32_e32 v8, s8
; GFX9-NEXT:    s_add_i32 s7, s7, 3
; GFX9-NEXT:    v_mov_b32_e32 v9, s6
; GFX9-NEXT:    v_perm_b32 v8, s9, v8, v7
; GFX9-NEXT:    v_perm_b32 v7, s7, v9, v7
; GFX9-NEXT:    v_add_u32_e32 v8, 0x300, v8
; GFX9-NEXT:    v_add_u32_sdwa v7, v7, s4 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v7, v8, v7 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; GFX9-NEXT:  .LBB87_3: ; %end
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB87_4:
; GFX9-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX9-NEXT:    s_branch .LBB87_2
;
; GFX11-TRUE16-LABEL: bitcast_v32i8_to_v4f64_scalar:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s42, v14
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s4, v13
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr12_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s5, v12
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr11_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s6, v11
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr10_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s7, v10
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s8, v9
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr8_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s9, v8
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr7_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s10, v7
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr6_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s11, v6
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr5_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s12, v5
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr4_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s13, v4
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr3_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s14, v3
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr2_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s15, v2
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr1_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s40, v1
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr0_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s41, v0
; GFX11-TRUE16-NEXT:    s_cmp_lg_u32 s42, 0
; GFX11-TRUE16-NEXT:    s_mov_b32 s42, 0
; GFX11-TRUE16-NEXT:    s_cbranch_scc0 .LBB87_4
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v3, 0xc0c0004
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_perm_b32 v4, s18, s19, v3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, s2, s3, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, s22, s23, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v0, s0, s1, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v2, s16, s17, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v6, s20, s21, v3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX11-TRUE16-NEXT:    v_perm_b32 v8, s26, s27, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v9, s41, s40, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v11, s5, s4, v3
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v0, v0, v1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v1, v2, v4
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v2, v6, v5
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v8
; GFX11-TRUE16-NEXT:    v_perm_b32 v6, s13, s12, v3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v8, 16, v9
; GFX11-TRUE16-NEXT:    v_perm_b32 v9, s9, s8, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v7, s24, s25, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, s28, s29, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v10, s15, s14, v3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GFX11-TRUE16-NEXT:    v_perm_b32 v12, s11, s10, v3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; GFX11-TRUE16-NEXT:    v_perm_b32 v13, s7, s6, v3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v3, v7, v4
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v4, v5, v8
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, v10, v6
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v6, v12, v9
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v7, v13, v11
; GFX11-TRUE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s42
; GFX11-TRUE16-NEXT:    s_cbranch_vccnz .LBB87_3
; GFX11-TRUE16-NEXT:  .LBB87_2: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v3, 0xc0c0004
; GFX11-TRUE16-NEXT:    s_add_i32 s18, s18, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s0, s0, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s2, s2, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s16, s16, 3
; GFX11-TRUE16-NEXT:    v_perm_b32 v4, s18, s19, v3
; GFX11-TRUE16-NEXT:    s_add_i32 s20, s20, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s22, s22, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s24, s24, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s26, s26, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v4, 0x300, v4
; GFX11-TRUE16-NEXT:    s_add_i32 s28, s28, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s41, s41, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s15, s15, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s13, s13, 3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX11-TRUE16-NEXT:    v_perm_b32 v0, s0, s1, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, s2, s3, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v2, s16, s17, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, s20, s21, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v6, s22, s23, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v0, 0x300, v0
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, 0x300, v1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, 0x300, v2
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v5, 0x300, v5
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, 0x300, v6
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GFX11-TRUE16-NEXT:    s_add_i32 s11, s11, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s9, s9, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s7, s7, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s5, s5, 3
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v0, v0, v1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v1, v2, v4
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v2, v5, v6
; GFX11-TRUE16-NEXT:    v_perm_b32 v4, s24, s25, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, s26, s27, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v6, s28, s29, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v7, s41, s40, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v8, s15, s14, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v9, s13, s12, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v10, s11, s10, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v11, s9, s8, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v12, s7, s6, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v3, s5, s4, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v4, 0x300, v4
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v5, 0x300, v5
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, 0x300, v6
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v7, 0x300, v7
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v8, 0x300, v8
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v9, 0x300, v9
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v10, 0x300, v10
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v11, 0x300, v11
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v12, 0x300, v12
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 0x300, v3
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v13, 16, v3
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v3, v4, v5
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v4, v6, v7
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, v8, v9
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v6, v10, v11
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v7, v12, v13
; GFX11-TRUE16-NEXT:  .LBB87_3: ; %end
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB87_4:
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-TRUE16-NEXT:    s_branch .LBB87_2
;
; GFX11-FAKE16-LABEL: bitcast_v32i8_to_v4f64_scalar:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s42, v14
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s4, v13
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s5, v12
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s6, v11
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s7, v10
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s8, v9
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s9, v8
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s10, v7
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s11, v6
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s12, v5
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s13, v4
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s14, v3
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s15, v2
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s40, v1
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s41, v0
; GFX11-FAKE16-NEXT:    s_cmp_lg_u32 s42, 0
; GFX11-FAKE16-NEXT:    s_mov_b32 s42, 0
; GFX11-FAKE16-NEXT:    s_cbranch_scc0 .LBB87_4
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v3, 0xc0c0004
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, s18, s19, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, s2, s3, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, s22, s23, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, s0, s1, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, s16, s17, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, s20, s21, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, s26, s27, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, s41, s40, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, s5, s4, v3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v0, v1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v1, v2, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, v6, v5
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v8
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, s13, s12, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v8, 16, v9
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, s9, s8, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, s24, s25, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, s28, s29, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, s15, s14, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, s11, s10, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, s7, s6, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v7, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, v5, v8
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v5, v10, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v6, v12, v9
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v7, v13, v11
; GFX11-FAKE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s42
; GFX11-FAKE16-NEXT:    s_cbranch_vccnz .LBB87_3
; GFX11-FAKE16-NEXT:  .LBB87_2: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v3, 0xc0c0004
; GFX11-FAKE16-NEXT:    s_add_i32 s18, s18, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s0, s0, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s2, s2, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s16, s16, 3
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, s18, s19, v3
; GFX11-FAKE16-NEXT:    s_add_i32 s20, s20, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s22, s22, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s24, s24, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s26, s26, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, 0x300, v4
; GFX11-FAKE16-NEXT:    s_add_i32 s28, s28, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s41, s41, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s15, s15, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s13, s13, 3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, s0, s1, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, s2, s3, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, s16, s17, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, s20, s21, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, s22, s23, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v0, 0x300, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v1, 0x300, v1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, 0x300, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v5, 0x300, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v6, 0x300, v6
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; GFX11-FAKE16-NEXT:    s_add_i32 s11, s11, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s9, s9, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s7, s7, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s5, s5, 3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v0, v1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v1, v2, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, v5, v6
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, s24, s25, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, s26, s27, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, s28, s29, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, s41, s40, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, s15, s14, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, s13, s12, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, s11, s10, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, s9, s8, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, s7, s6, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, s5, s4, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, 0x300, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v5, 0x300, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v6, 0x300, v6
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v7, 0x300, v7
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v8, 0x300, v8
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v9, 0x300, v9
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v10, 0x300, v10
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v11, 0x300, v11
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v12, 0x300, v12
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, 0x300, v3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v13, 16, v3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v4, v5
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, v6, v7
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v5, v8, v9
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v6, v10, v11
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v7, v12, v13
; GFX11-FAKE16-NEXT:  .LBB87_3: ; %end
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB87_4:
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-FAKE16-NEXT:    s_branch .LBB87_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <32 x i8> %a, splat (i8 3)
  %a2 = bitcast <32 x i8> %a1 to <4 x double>
  br label %end

cmp.false:
  %a3 = bitcast <32 x i8> %a to <4 x double>
  br label %end

end:
  %phi = phi <4 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <4 x double> %phi
}

define <16 x half> @bitcast_v16i16_to_v16f16(<16 x i16> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v16i16_to_v16f16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v9, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v6
; SI-NEXT:    v_lshrrev_b32_e32 v10, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v13, 16, v4
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v2
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v1
; SI-NEXT:    v_lshrrev_b32_e32 v16, 16, v0
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    v_lshlrev_b32_e32 v25, 16, v14
; SI-NEXT:    v_lshlrev_b32_e32 v24, 16, v16
; SI-NEXT:    v_lshlrev_b32_e32 v27, 16, v11
; SI-NEXT:    v_lshlrev_b32_e32 v26, 16, v15
; SI-NEXT:    v_lshlrev_b32_e32 v29, 16, v10
; SI-NEXT:    v_lshlrev_b32_e32 v28, 16, v13
; SI-NEXT:    v_lshlrev_b32_e32 v31, 16, v9
; SI-NEXT:    v_lshlrev_b32_e32 v30, 16, v12
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB88_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_or_b32_e32 v17, v1, v25
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v3
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_or_b32_e32 v15, v1, v27
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v5
; SI-NEXT:    v_or_b32_e32 v22, v0, v24
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v2
; SI-NEXT:    v_or_b32_e32 v13, v1, v29
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v7
; SI-NEXT:    v_or_b32_e32 v18, v0, v26
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v4
; SI-NEXT:    v_or_b32_e32 v8, v1, v31
; SI-NEXT:    v_or_b32_e32 v16, v0, v28
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v6
; SI-NEXT:    v_alignbit_b32 v19, v17, v24, 16
; SI-NEXT:    v_alignbit_b32 v20, v15, v26, 16
; SI-NEXT:    v_alignbit_b32 v21, v13, v28, 16
; SI-NEXT:    v_alignbit_b32 v23, v8, v30, 16
; SI-NEXT:    v_or_b32_e32 v12, v0, v30
; SI-NEXT:    ; implicit-def: $vgpr0
; SI-NEXT:    ; implicit-def: $vgpr1
; SI-NEXT:    ; implicit-def: $vgpr2
; SI-NEXT:    ; implicit-def: $vgpr3
; SI-NEXT:    ; implicit-def: $vgpr4
; SI-NEXT:    ; implicit-def: $vgpr5
; SI-NEXT:    ; implicit-def: $vgpr6
; SI-NEXT:    ; implicit-def: $vgpr7
; SI-NEXT:    ; implicit-def: $vgpr25
; SI-NEXT:    ; implicit-def: $vgpr24
; SI-NEXT:    ; implicit-def: $vgpr27
; SI-NEXT:    ; implicit-def: $vgpr26
; SI-NEXT:    ; implicit-def: $vgpr29
; SI-NEXT:    ; implicit-def: $vgpr28
; SI-NEXT:    ; implicit-def: $vgpr31
; SI-NEXT:    ; implicit-def: $vgpr30
; SI-NEXT:  .LBB88_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB88_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_or_b32_e32 v6, v30, v6
; SI-NEXT:    s_mov_b32 s6, 0x30000
; SI-NEXT:    v_or_b32_e32 v4, v28, v4
; SI-NEXT:    v_or_b32_e32 v2, v26, v2
; SI-NEXT:    v_or_b32_e32 v0, v24, v0
; SI-NEXT:    v_add_i32_e32 v12, vcc, 0x30000, v6
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v7
; SI-NEXT:    v_add_i32_e32 v16, vcc, s6, v4
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v5
; SI-NEXT:    v_add_i32_e32 v18, vcc, s6, v2
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v3
; SI-NEXT:    v_add_i32_e32 v22, vcc, s6, v0
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v1
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_or_b32_e32 v6, v31, v6
; SI-NEXT:    v_or_b32_e32 v4, v29, v4
; SI-NEXT:    v_or_b32_e32 v2, v27, v2
; SI-NEXT:    v_or_b32_e32 v0, v25, v0
; SI-NEXT:    v_add_i32_e32 v8, vcc, s6, v6
; SI-NEXT:    v_add_i32_e32 v13, vcc, s6, v4
; SI-NEXT:    v_add_i32_e32 v15, vcc, s6, v2
; SI-NEXT:    v_add_i32_e32 v17, vcc, s6, v0
; SI-NEXT:    v_alignbit_b32 v19, v17, v22, 16
; SI-NEXT:    v_alignbit_b32 v20, v15, v18, 16
; SI-NEXT:    v_alignbit_b32 v21, v13, v16, 16
; SI-NEXT:    v_alignbit_b32 v23, v8, v12, 16
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v17
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v15
; SI-NEXT:    v_lshrrev_b32_e32 v10, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v9, 16, v8
; SI-NEXT:  .LBB88_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v22
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v19
; SI-NEXT:    v_or_b32_e32 v0, v0, v1
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v17
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v14
; SI-NEXT:    v_or_b32_e32 v1, v1, v2
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v18
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v20
; SI-NEXT:    v_or_b32_e32 v2, v2, v3
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v15
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v11
; SI-NEXT:    v_or_b32_e32 v3, v3, v4
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v16
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v21
; SI-NEXT:    v_or_b32_e32 v4, v4, v5
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v13
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v10
; SI-NEXT:    v_or_b32_e32 v5, v5, v6
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v12
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v23
; SI-NEXT:    v_or_b32_e32 v6, v6, v7
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v8
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v9
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16i16_to_v16f16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB88_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v8, 3
; VI-NEXT:    v_add_u16_sdwa v9, v0, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_sdwa v10, v1, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_sdwa v11, v2, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_sdwa v12, v3, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_sdwa v13, v4, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_sdwa v14, v5, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_sdwa v15, v6, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_sdwa v8, v7, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v7, 3, v7
; VI-NEXT:    v_add_u16_e32 v6, 3, v6
; VI-NEXT:    v_add_u16_e32 v5, 3, v5
; VI-NEXT:    v_add_u16_e32 v4, 3, v4
; VI-NEXT:    v_add_u16_e32 v3, 3, v3
; VI-NEXT:    v_add_u16_e32 v2, 3, v2
; VI-NEXT:    v_add_u16_e32 v1, 3, v1
; VI-NEXT:    v_add_u16_e32 v0, 3, v0
; VI-NEXT:    v_or_b32_e32 v7, v7, v8
; VI-NEXT:    v_or_b32_e32 v6, v6, v15
; VI-NEXT:    v_or_b32_e32 v5, v5, v14
; VI-NEXT:    v_or_b32_e32 v4, v4, v13
; VI-NEXT:    v_or_b32_e32 v3, v3, v12
; VI-NEXT:    v_or_b32_e32 v2, v2, v11
; VI-NEXT:    v_or_b32_e32 v1, v1, v10
; VI-NEXT:    v_or_b32_e32 v0, v0, v9
; VI-NEXT:  .LBB88_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16i16_to_v16f16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v16i16_to_v16f16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB88_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX11-NEXT:  .LBB88_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <16 x i16> %a, splat (i16 3)
  %a2 = bitcast <16 x i16> %a1 to <16 x half>
  br label %end

cmp.false:
  %a3 = bitcast <16 x i16> %a to <16 x half>
  br label %end

end:
  %phi = phi <16 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x half> %phi
}

define inreg <16 x half> @bitcast_v16i16_to_v16f16_scalar(<16 x i16> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v16i16_to_v16f16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_lshr_b32 s43, s23, 16
; SI-NEXT:    s_lshr_b32 s47, s22, 16
; SI-NEXT:    s_lshr_b32 s42, s21, 16
; SI-NEXT:    s_lshr_b32 s46, s20, 16
; SI-NEXT:    s_lshr_b32 s41, s19, 16
; SI-NEXT:    s_lshr_b32 s45, s18, 16
; SI-NEXT:    s_lshr_b32 s40, s17, 16
; SI-NEXT:    s_lshr_b32 s44, s16, 16
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB89_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s5, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s40, 16
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s56, s44, 16
; SI-NEXT:    s_or_b32 s57, s5, s7
; SI-NEXT:    s_and_b32 s5, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s41, 16
; SI-NEXT:    s_or_b32 s10, s4, s56
; SI-NEXT:    s_and_b32 s4, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s58, s45, 16
; SI-NEXT:    s_or_b32 s59, s5, s7
; SI-NEXT:    s_and_b32 s5, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s42, 16
; SI-NEXT:    s_or_b32 s8, s4, s58
; SI-NEXT:    s_and_b32 s4, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s60, s46, 16
; SI-NEXT:    s_or_b32 s61, s5, s7
; SI-NEXT:    s_and_b32 s5, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s43, 16
; SI-NEXT:    s_or_b32 s6, s4, s60
; SI-NEXT:    s_and_b32 s4, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s62, s47, 16
; SI-NEXT:    s_or_b32 s63, s5, s7
; SI-NEXT:    s_or_b32 s4, s4, s62
; SI-NEXT:    s_lshr_b64 s[12:13], s[56:57], 16
; SI-NEXT:    s_lshr_b64 s[14:15], s[58:59], 16
; SI-NEXT:    s_lshr_b64 s[24:25], s[60:61], 16
; SI-NEXT:    s_lshr_b64 s[26:27], s[62:63], 16
; SI-NEXT:    s_mov_b32 s11, s57
; SI-NEXT:    s_mov_b32 s9, s59
; SI-NEXT:    s_mov_b32 s7, s61
; SI-NEXT:    s_mov_b32 s5, s63
; SI-NEXT:    s_cbranch_execnz .LBB89_3
; SI-NEXT:  .LBB89_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_and_b32 s4, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s47, 16
; SI-NEXT:    s_add_i32 s23, s23, 3
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_and_b32 s5, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s6, s43, 16
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_or_b32 s5, s6, s5
; SI-NEXT:    s_and_b32 s6, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s46, 16
; SI-NEXT:    s_add_i32 s21, s21, 3
; SI-NEXT:    s_or_b32 s6, s7, s6
; SI-NEXT:    s_and_b32 s7, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s8, s42, 16
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_or_b32 s7, s8, s7
; SI-NEXT:    s_and_b32 s8, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s9, s45, 16
; SI-NEXT:    s_add_i32 s19, s19, 3
; SI-NEXT:    s_or_b32 s8, s9, s8
; SI-NEXT:    s_and_b32 s9, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s41, 16
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    s_or_b32 s9, s10, s9
; SI-NEXT:    s_and_b32 s10, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s11, s44, 16
; SI-NEXT:    s_add_i32 s17, s17, 3
; SI-NEXT:    s_or_b32 s10, s11, s10
; SI-NEXT:    s_and_b32 s11, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s40, 16
; SI-NEXT:    s_or_b32 s11, s12, s11
; SI-NEXT:    s_add_i32 s4, s4, 0x30000
; SI-NEXT:    s_add_i32 s5, s5, 0x30000
; SI-NEXT:    s_add_i32 s6, s6, 0x30000
; SI-NEXT:    s_add_i32 s7, s7, 0x30000
; SI-NEXT:    s_add_i32 s8, s8, 0x30000
; SI-NEXT:    s_add_i32 s9, s9, 0x30000
; SI-NEXT:    s_add_i32 s10, s10, 0x30000
; SI-NEXT:    s_add_i32 s11, s11, 0x30000
; SI-NEXT:    s_lshr_b64 s[12:13], s[10:11], 16
; SI-NEXT:    s_lshr_b64 s[14:15], s[8:9], 16
; SI-NEXT:    s_lshr_b64 s[24:25], s[6:7], 16
; SI-NEXT:    s_lshr_b64 s[26:27], s[4:5], 16
; SI-NEXT:    s_lshr_b32 s40, s11, 16
; SI-NEXT:    s_lshr_b32 s41, s9, 16
; SI-NEXT:    s_lshr_b32 s42, s7, 16
; SI-NEXT:    s_lshr_b32 s43, s5, 16
; SI-NEXT:  .LBB89_3: ; %end
; SI-NEXT:    s_and_b32 s10, s10, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s12, 16
; SI-NEXT:    s_or_b32 s10, s10, s12
; SI-NEXT:    s_and_b32 s11, s11, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s40, 16
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    s_and_b32 s8, s8, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s14, 16
; SI-NEXT:    s_or_b32 s8, s8, s12
; SI-NEXT:    s_and_b32 s9, s9, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s41, 16
; SI-NEXT:    s_or_b32 s9, s9, s12
; SI-NEXT:    s_and_b32 s6, s6, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s24, 16
; SI-NEXT:    s_or_b32 s6, s6, s12
; SI-NEXT:    s_and_b32 s7, s7, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s42, 16
; SI-NEXT:    s_or_b32 s7, s7, s12
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s26, 16
; SI-NEXT:    s_or_b32 s4, s4, s12
; SI-NEXT:    s_and_b32 s5, s5, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s43, 16
; SI-NEXT:    s_or_b32 s5, s5, s12
; SI-NEXT:    v_mov_b32_e32 v0, s10
; SI-NEXT:    v_mov_b32_e32 v1, s11
; SI-NEXT:    v_mov_b32_e32 v2, s8
; SI-NEXT:    v_mov_b32_e32 v3, s9
; SI-NEXT:    v_mov_b32_e32 v4, s6
; SI-NEXT:    v_mov_b32_e32 v5, s7
; SI-NEXT:    v_mov_b32_e32 v6, s4
; SI-NEXT:    v_mov_b32_e32 v7, s5
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB89_4:
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr12
; SI-NEXT:    ; implicit-def: $sgpr8
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr6
; SI-NEXT:    ; implicit-def: $sgpr24
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr26
; SI-NEXT:    s_branch .LBB89_2
;
; VI-LABEL: bitcast_v16i16_to_v16f16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB89_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB89_3
; VI-NEXT:  .LBB89_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s5, s16, 3
; VI-NEXT:    s_and_b32 s6, s17, 0xffff0000
; VI-NEXT:    s_add_i32 s7, s17, 3
; VI-NEXT:    s_add_i32 s9, s18, 3
; VI-NEXT:    s_and_b32 s10, s19, 0xffff0000
; VI-NEXT:    s_add_i32 s11, s19, 3
; VI-NEXT:    s_add_i32 s13, s20, 3
; VI-NEXT:    s_add_i32 s15, s21, 3
; VI-NEXT:    s_add_i32 s17, s22, 3
; VI-NEXT:    s_add_i32 s19, s23, 3
; VI-NEXT:    s_and_b32 s4, s16, 0xffff0000
; VI-NEXT:    s_and_b32 s8, s18, 0xffff0000
; VI-NEXT:    s_and_b32 s12, s20, 0xffff0000
; VI-NEXT:    s_and_b32 s14, s21, 0xffff0000
; VI-NEXT:    s_and_b32 s16, s22, 0xffff0000
; VI-NEXT:    s_and_b32 s18, s23, 0xffff0000
; VI-NEXT:    s_and_b32 s19, s19, 0xffff
; VI-NEXT:    s_and_b32 s17, s17, 0xffff
; VI-NEXT:    s_and_b32 s15, s15, 0xffff
; VI-NEXT:    s_and_b32 s13, s13, 0xffff
; VI-NEXT:    s_and_b32 s11, s11, 0xffff
; VI-NEXT:    s_and_b32 s9, s9, 0xffff
; VI-NEXT:    s_and_b32 s7, s7, 0xffff
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s18, s18, s19
; VI-NEXT:    s_or_b32 s16, s16, s17
; VI-NEXT:    s_or_b32 s14, s14, s15
; VI-NEXT:    s_or_b32 s12, s12, s13
; VI-NEXT:    s_or_b32 s10, s10, s11
; VI-NEXT:    s_or_b32 s8, s8, s9
; VI-NEXT:    s_or_b32 s6, s6, s7
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s23, s18, 0x30000
; VI-NEXT:    s_add_i32 s22, s16, 0x30000
; VI-NEXT:    s_add_i32 s21, s14, 0x30000
; VI-NEXT:    s_add_i32 s20, s12, 0x30000
; VI-NEXT:    s_add_i32 s19, s10, 0x30000
; VI-NEXT:    s_add_i32 s18, s8, 0x30000
; VI-NEXT:    s_add_i32 s17, s6, 0x30000
; VI-NEXT:    s_add_i32 s16, s4, 0x30000
; VI-NEXT:  .LBB89_3: ; %end
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB89_4:
; VI-NEXT:    s_branch .LBB89_2
;
; GFX9-LABEL: bitcast_v16i16_to_v16f16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB89_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB89_4
; GFX9-NEXT:  .LBB89_2: ; %cmp.true
; GFX9-NEXT:    v_pk_add_u16 v7, s23, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, s22, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v5, s21, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v4, s20, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v3, s19, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v2, s18, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v1, s17, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v0, s16, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB89_3:
; GFX9-NEXT:    s_branch .LBB89_2
; GFX9-NEXT:  .LBB89_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v16i16_to_v16f16_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s7, s19
; GFX11-NEXT:    s_mov_b32 s6, s18
; GFX11-NEXT:    s_mov_b32 s5, s17
; GFX11-NEXT:    s_mov_b32 s4, s16
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s8, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB89_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-NEXT:    s_cbranch_vccnz .LBB89_4
; GFX11-NEXT:  .LBB89_2: ; %cmp.true
; GFX11-NEXT:    v_pk_add_u16 v7, s7, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v6, s6, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v5, s5, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v4, s4, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v3, s3, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v2, s2, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v1, s1, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v0, s0, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB89_3:
; GFX11-NEXT:    s_branch .LBB89_2
; GFX11-NEXT:  .LBB89_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <16 x i16> %a, splat (i16 3)
  %a2 = bitcast <16 x i16> %a1 to <16 x half>
  br label %end

cmp.false:
  %a3 = bitcast <16 x i16> %a to <16 x half>
  br label %end

end:
  %phi = phi <16 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x half> %phi
}

define <16 x i16> @bitcast_v16f16_to_v16i16(<16 x half> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v16f16_to_v16i16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v9, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v13, 16, v6
; SI-NEXT:    v_lshrrev_b32_e32 v10, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v4
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v2
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v1
; SI-NEXT:    v_lshrrev_b32_e32 v16, 16, v0
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB90_2
; SI-NEXT:  ; %bb.1: ; %cmp.true
; SI-NEXT:    v_cvt_f32_f16_e32 v9, v9
; SI-NEXT:    v_cvt_f32_f16_e32 v7, v7
; SI-NEXT:    v_cvt_f32_f16_e32 v10, v10
; SI-NEXT:    v_cvt_f32_f16_e32 v5, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v11, v11
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v12, v12
; SI-NEXT:    v_cvt_f32_f16_e32 v8, v16
; SI-NEXT:    v_cvt_f32_f16_e32 v15, v15
; SI-NEXT:    v_cvt_f32_f16_e32 v14, v14
; SI-NEXT:    v_cvt_f32_f16_e32 v13, v13
; SI-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; SI-NEXT:    v_cvt_f32_f16_e32 v1, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v0, v0
; SI-NEXT:    v_cvt_f32_f16_e32 v2, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v4, v4
; SI-NEXT:    v_cvt_f32_f16_e32 v6, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v9
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_add_f32_e32 v10, 0x38000000, v10
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v10, v10
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_add_f32_e32 v11, 0x38000000, v11
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v11, v11
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_add_f32_e32 v12, 0x38000000, v12
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_add_f32_e32 v15, 0x38000000, v15
; SI-NEXT:    v_add_f32_e32 v14, 0x38000000, v14
; SI-NEXT:    v_add_f32_e32 v13, 0x38000000, v13
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v12, v12
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v8, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v15, v15
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v14, v14
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_cvt_f16_f32_e32 v13, v13
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_or_b32_e32 v7, v7, v16
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v10
; SI-NEXT:    v_or_b32_e32 v5, v5, v16
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v11
; SI-NEXT:    v_or_b32_e32 v3, v3, v16
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v12
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_lshlrev_b32_e32 v15, 16, v15
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v14
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v13
; SI-NEXT:    v_or_b32_e32 v1, v1, v16
; SI-NEXT:    v_or_b32_e32 v0, v0, v8
; SI-NEXT:    v_or_b32_e32 v2, v2, v15
; SI-NEXT:    v_or_b32_e32 v4, v4, v14
; SI-NEXT:    v_or_b32_e32 v6, v6, v13
; SI-NEXT:    v_alignbit_b32 v16, v1, v8, 16
; SI-NEXT:    v_alignbit_b32 v15, v3, v15, 16
; SI-NEXT:    v_alignbit_b32 v14, v5, v14, 16
; SI-NEXT:    v_alignbit_b32 v13, v7, v13, 16
; SI-NEXT:  .LBB90_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v16
; SI-NEXT:    v_or_b32_e32 v0, v0, v8
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v12
; SI-NEXT:    v_or_b32_e32 v1, v1, v8
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v15
; SI-NEXT:    v_or_b32_e32 v2, v2, v8
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v11
; SI-NEXT:    v_or_b32_e32 v3, v3, v8
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v14
; SI-NEXT:    v_or_b32_e32 v4, v4, v8
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v10
; SI-NEXT:    v_or_b32_e32 v5, v5, v8
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v13
; SI-NEXT:    v_or_b32_e32 v6, v6, v8
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v9
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16f16_to_v16i16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB90_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v9, 0x200
; VI-NEXT:    v_add_f16_e32 v8, 0x200, v0
; VI-NEXT:    v_add_f16_sdwa v0, v0, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v10, 0x200, v1
; VI-NEXT:    v_add_f16_sdwa v1, v1, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v11, 0x200, v2
; VI-NEXT:    v_add_f16_sdwa v2, v2, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v12, 0x200, v3
; VI-NEXT:    v_add_f16_sdwa v3, v3, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v13, 0x200, v4
; VI-NEXT:    v_add_f16_sdwa v4, v4, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v14, 0x200, v5
; VI-NEXT:    v_add_f16_sdwa v5, v5, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v15, 0x200, v6
; VI-NEXT:    v_add_f16_sdwa v6, v6, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v16, 0x200, v7
; VI-NEXT:    v_add_f16_sdwa v7, v7, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v7, v16, v7
; VI-NEXT:    v_or_b32_e32 v6, v15, v6
; VI-NEXT:    v_or_b32_e32 v5, v14, v5
; VI-NEXT:    v_or_b32_e32 v4, v13, v4
; VI-NEXT:    v_or_b32_e32 v3, v12, v3
; VI-NEXT:    v_or_b32_e32 v2, v11, v2
; VI-NEXT:    v_or_b32_e32 v1, v10, v1
; VI-NEXT:    v_or_b32_e32 v0, v8, v0
; VI-NEXT:  .LBB90_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16f16_to_v16i16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    s_movk_i32 s6, 0x200
; GFX9-NEXT:    v_pk_add_f16 v7, v7, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, v6, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v5, v5, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v4, v4, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v3, v3, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v2, v2, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v1, v1, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v0, v0, s6 op_sel_hi:[1,0]
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v16f16_to_v16i16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB90_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_pk_add_f16 v7, 0x200, v7 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v6, 0x200, v6 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v5, 0x200, v5 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v4, 0x200, v4 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v3, 0x200, v3 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v2, 0x200, v2 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v1, 0x200, v1 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v0, 0x200, v0 op_sel_hi:[0,1]
; GFX11-NEXT:  .LBB90_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <16 x half> %a1 to <16 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <16 x half> %a to <16 x i16>
  br label %end

end:
  %phi = phi <16 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x i16> %phi
}

define inreg <16 x i16> @bitcast_v16f16_to_v16i16_scalar(<16 x half> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v16f16_to_v16i16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_lshr_b32 s10, s23, 16
; SI-NEXT:    s_lshr_b32 s9, s22, 16
; SI-NEXT:    s_lshr_b32 s8, s21, 16
; SI-NEXT:    s_lshr_b32 s11, s20, 16
; SI-NEXT:    s_lshr_b32 s7, s19, 16
; SI-NEXT:    s_lshr_b32 s12, s18, 16
; SI-NEXT:    s_lshr_b32 s6, s17, 16
; SI-NEXT:    s_lshr_b32 s13, s16, 16
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB91_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_cbranch_execnz .LBB91_4
; SI-NEXT:  .LBB91_2: ; %cmp.true
; SI-NEXT:    v_cvt_f32_f16_e32 v0, s13
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s16
; SI-NEXT:    v_cvt_f32_f16_e32 v2, s12
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s18
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_or_b32_e32 v16, v1, v0
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s11
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v4, s20
; SI-NEXT:    v_or_b32_e32 v19, v3, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s9
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v4
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v1
; SI-NEXT:    v_or_b32_e32 v18, v5, v4
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s22
; SI-NEXT:    v_cvt_f32_f16_e32 v5, s10
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s23
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v17, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v5, s8
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v7, s21
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_or_b32_e32 v20, v1, v6
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v17
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v21, v5
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v7
; SI-NEXT:    v_or_b32_e32 v7, v3, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s7
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v21
; SI-NEXT:    v_cvt_f32_f16_e32 v8, s17
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_or_b32_e32 v5, v5, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s19
; SI-NEXT:    v_cvt_f16_f32_e32 v22, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s6
; SI-NEXT:    v_lshr_b64 v[10:11], v[4:5], 16
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v23, v1
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v22
; SI-NEXT:    v_or_b32_e32 v3, v3, v8
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v23
; SI-NEXT:    v_or_b32_e32 v1, v1, v8
; SI-NEXT:    v_lshr_b64 v[14:15], v[0:1], 16
; SI-NEXT:    v_lshr_b64 v[12:13], v[2:3], 16
; SI-NEXT:    v_lshr_b64 v[8:9], v[6:7], 16
; SI-NEXT:    s_branch .LBB91_5
; SI-NEXT:  .LBB91_3:
; SI-NEXT:    s_branch .LBB91_2
; SI-NEXT:  .LBB91_4:
; SI-NEXT:    v_mov_b32_e32 v17, s10
; SI-NEXT:    v_mov_b32_e32 v21, s8
; SI-NEXT:    v_mov_b32_e32 v22, s7
; SI-NEXT:    v_mov_b32_e32 v23, s6
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    v_mov_b32_e32 v20, s22
; SI-NEXT:    v_mov_b32_e32 v18, s20
; SI-NEXT:    v_mov_b32_e32 v19, s18
; SI-NEXT:    v_mov_b32_e32 v16, s16
; SI-NEXT:    v_mov_b32_e32 v14, s13
; SI-NEXT:    v_mov_b32_e32 v12, s12
; SI-NEXT:    v_mov_b32_e32 v10, s11
; SI-NEXT:    v_mov_b32_e32 v8, s9
; SI-NEXT:  .LBB91_5: ; %end
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v14
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v16
; SI-NEXT:    v_or_b32_e32 v0, v2, v0
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v23
; SI-NEXT:    v_or_b32_e32 v1, v1, v2
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v19
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v12
; SI-NEXT:    v_or_b32_e32 v2, v2, v4
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v22
; SI-NEXT:    v_or_b32_e32 v3, v3, v4
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v18
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v10
; SI-NEXT:    v_or_b32_e32 v4, v4, v6
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v21
; SI-NEXT:    v_or_b32_e32 v5, v5, v6
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v20
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_or_b32_e32 v6, v6, v8
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v17
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16f16_to_v16i16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB91_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB91_4
; VI-NEXT:  .LBB91_2: ; %cmp.true
; VI-NEXT:    s_lshr_b32 s4, s16, 16
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    s_lshr_b32 s4, s17, 16
; VI-NEXT:    v_mov_b32_e32 v2, s4
; VI-NEXT:    s_lshr_b32 s4, s18, 16
; VI-NEXT:    s_lshr_b32 s5, s22, 16
; VI-NEXT:    v_mov_b32_e32 v0, 0x200
; VI-NEXT:    v_mov_b32_e32 v3, s4
; VI-NEXT:    s_lshr_b32 s4, s19, 16
; VI-NEXT:    v_mov_b32_e32 v6, s5
; VI-NEXT:    s_lshr_b32 s5, s23, 16
; VI-NEXT:    v_mov_b32_e32 v4, s4
; VI-NEXT:    s_lshr_b32 s4, s20, 16
; VI-NEXT:    v_add_f16_e32 v5, s22, v0
; VI-NEXT:    v_add_f16_sdwa v6, v6, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_mov_b32_e32 v13, s5
; VI-NEXT:    v_add_f16_e32 v7, s23, v0
; VI-NEXT:    v_add_f16_sdwa v13, v13, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v6, v5, v6
; VI-NEXT:    v_mov_b32_e32 v5, s4
; VI-NEXT:    s_lshr_b32 s4, s21, 16
; VI-NEXT:    v_or_b32_e32 v7, v7, v13
; VI-NEXT:    v_add_f16_sdwa v13, v5, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_mov_b32_e32 v5, s4
; VI-NEXT:    v_add_f16_e32 v8, s16, v0
; VI-NEXT:    v_add_f16_sdwa v9, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v1, s17, v0
; VI-NEXT:    v_add_f16_sdwa v10, v2, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, s18, v0
; VI-NEXT:    v_add_f16_sdwa v11, v3, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v3, s19, v0
; VI-NEXT:    v_add_f16_sdwa v12, v4, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v4, s20, v0
; VI-NEXT:    v_add_f16_sdwa v5, v5, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v0, s21, v0
; VI-NEXT:    v_or_b32_e32 v5, v0, v5
; VI-NEXT:    v_or_b32_e32 v4, v4, v13
; VI-NEXT:    v_or_b32_e32 v3, v3, v12
; VI-NEXT:    v_or_b32_e32 v2, v2, v11
; VI-NEXT:    v_or_b32_e32 v1, v1, v10
; VI-NEXT:    v_or_b32_e32 v0, v8, v9
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB91_3:
; VI-NEXT:    s_branch .LBB91_2
; VI-NEXT:  .LBB91_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16f16_to_v16i16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB91_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB91_4
; GFX9-NEXT:  .LBB91_2: ; %cmp.true
; GFX9-NEXT:    v_mov_b32_e32 v0, 0x200
; GFX9-NEXT:    v_pk_add_f16 v7, s23, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, s22, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v5, s21, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v4, s20, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v3, s19, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v2, s18, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v1, s17, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v0, s16, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB91_3:
; GFX9-NEXT:    s_branch .LBB91_2
; GFX9-NEXT:  .LBB91_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v16f16_to_v16i16_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s7, s19
; GFX11-NEXT:    s_mov_b32 s6, s18
; GFX11-NEXT:    s_mov_b32 s5, s17
; GFX11-NEXT:    s_mov_b32 s4, s16
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s8, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB91_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-NEXT:    s_cbranch_vccnz .LBB91_4
; GFX11-NEXT:  .LBB91_2: ; %cmp.true
; GFX11-NEXT:    v_pk_add_f16 v7, 0x200, s7 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v6, 0x200, s6 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v5, 0x200, s5 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v4, 0x200, s4 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v3, 0x200, s3 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v2, 0x200, s2 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v1, 0x200, s1 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v0, 0x200, s0 op_sel_hi:[0,1]
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB91_3:
; GFX11-NEXT:    s_branch .LBB91_2
; GFX11-NEXT:  .LBB91_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <16 x half> %a1 to <16 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <16 x half> %a to <16 x i16>
  br label %end

end:
  %phi = phi <16 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x i16> %phi
}

define <16 x bfloat> @bitcast_v16i16_to_v16bf16(<16 x i16> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v16i16_to_v16bf16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v6
; SI-NEXT:    v_lshrrev_b32_e32 v13, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v4
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v10, 16, v2
; SI-NEXT:    v_lshrrev_b32_e32 v9, 16, v1
; SI-NEXT:    v_lshrrev_b32_e32 v16, 16, v0
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v16
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v10
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v12
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v13
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v14
; SI-NEXT:    v_lshlrev_b32_e32 v15, 16, v15
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v0
; SI-NEXT:    v_lshlrev_b32_e32 v17, 16, v1
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v2
; SI-NEXT:    v_lshlrev_b32_e32 v19, 16, v3
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v4
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v5
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v6
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v7
; SI-NEXT:    ; implicit-def: $vgpr0
; SI-NEXT:    ; implicit-def: $vgpr1
; SI-NEXT:    ; implicit-def: $vgpr2
; SI-NEXT:    ; implicit-def: $vgpr3
; SI-NEXT:    ; implicit-def: $vgpr4
; SI-NEXT:    ; implicit-def: $vgpr5
; SI-NEXT:    ; implicit-def: $vgpr6
; SI-NEXT:    ; implicit-def: $vgpr7
; SI-NEXT:  ; %bb.2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB92_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v7
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v5
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v3
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v1
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_or_b32_e32 v7, v15, v7
; SI-NEXT:    s_mov_b32 s6, 0x30000
; SI-NEXT:    v_or_b32_e32 v6, v14, v6
; SI-NEXT:    v_or_b32_e32 v5, v13, v5
; SI-NEXT:    v_or_b32_e32 v4, v12, v4
; SI-NEXT:    v_or_b32_e32 v3, v11, v3
; SI-NEXT:    v_or_b32_e32 v2, v10, v2
; SI-NEXT:    v_or_b32_e32 v1, v9, v1
; SI-NEXT:    v_or_b32_e32 v0, v8, v0
; SI-NEXT:    v_add_i32_e32 v7, vcc, 0x30000, v7
; SI-NEXT:    v_add_i32_e32 v6, vcc, s6, v6
; SI-NEXT:    v_add_i32_e32 v5, vcc, s6, v5
; SI-NEXT:    v_add_i32_e32 v4, vcc, s6, v4
; SI-NEXT:    v_add_i32_e32 v3, vcc, s6, v3
; SI-NEXT:    v_add_i32_e32 v2, vcc, s6, v2
; SI-NEXT:    v_add_i32_e32 v1, vcc, s6, v1
; SI-NEXT:    v_add_i32_e32 v0, vcc, s6, v0
; SI-NEXT:    v_and_b32_e32 v8, 0xffff0000, v0
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v0
; SI-NEXT:    v_and_b32_e32 v9, 0xffff0000, v1
; SI-NEXT:    v_lshlrev_b32_e32 v17, 16, v1
; SI-NEXT:    v_and_b32_e32 v10, 0xffff0000, v2
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v2
; SI-NEXT:    v_and_b32_e32 v11, 0xffff0000, v3
; SI-NEXT:    v_lshlrev_b32_e32 v19, 16, v3
; SI-NEXT:    v_and_b32_e32 v12, 0xffff0000, v4
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v4
; SI-NEXT:    v_and_b32_e32 v13, 0xffff0000, v5
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v5
; SI-NEXT:    v_and_b32_e32 v14, 0xffff0000, v6
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v6
; SI-NEXT:    v_and_b32_e32 v15, 0xffff0000, v7
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v7
; SI-NEXT:  .LBB92_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_mul_f32_e32 v0, 1.0, v8
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_mul_f32_e32 v1, 1.0, v16
; SI-NEXT:    v_alignbit_b32 v0, v0, v1, 16
; SI-NEXT:    v_mul_f32_e32 v1, 1.0, v9
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_mul_f32_e32 v2, 1.0, v17
; SI-NEXT:    v_alignbit_b32 v1, v1, v2, 16
; SI-NEXT:    v_mul_f32_e32 v2, 1.0, v10
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_mul_f32_e32 v3, 1.0, v18
; SI-NEXT:    v_alignbit_b32 v2, v2, v3, 16
; SI-NEXT:    v_mul_f32_e32 v3, 1.0, v11
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_mul_f32_e32 v4, 1.0, v19
; SI-NEXT:    v_alignbit_b32 v3, v3, v4, 16
; SI-NEXT:    v_mul_f32_e32 v4, 1.0, v12
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_mul_f32_e32 v5, 1.0, v20
; SI-NEXT:    v_alignbit_b32 v4, v4, v5, 16
; SI-NEXT:    v_mul_f32_e32 v5, 1.0, v13
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_mul_f32_e32 v6, 1.0, v21
; SI-NEXT:    v_alignbit_b32 v5, v5, v6, 16
; SI-NEXT:    v_mul_f32_e32 v6, 1.0, v14
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_mul_f32_e32 v7, 1.0, v22
; SI-NEXT:    v_alignbit_b32 v6, v6, v7, 16
; SI-NEXT:    v_mul_f32_e32 v7, 1.0, v15
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_mul_f32_e32 v8, 1.0, v23
; SI-NEXT:    v_alignbit_b32 v7, v7, v8, 16
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16i16_to_v16bf16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB92_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v8, 3
; VI-NEXT:    v_add_u16_sdwa v9, v0, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_sdwa v10, v1, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_sdwa v11, v2, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_sdwa v12, v3, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_sdwa v13, v4, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_sdwa v14, v5, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_sdwa v15, v6, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_sdwa v8, v7, v8 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v7, 3, v7
; VI-NEXT:    v_add_u16_e32 v6, 3, v6
; VI-NEXT:    v_add_u16_e32 v5, 3, v5
; VI-NEXT:    v_add_u16_e32 v4, 3, v4
; VI-NEXT:    v_add_u16_e32 v3, 3, v3
; VI-NEXT:    v_add_u16_e32 v2, 3, v2
; VI-NEXT:    v_add_u16_e32 v1, 3, v1
; VI-NEXT:    v_add_u16_e32 v0, 3, v0
; VI-NEXT:    v_or_b32_e32 v7, v7, v8
; VI-NEXT:    v_or_b32_e32 v6, v6, v15
; VI-NEXT:    v_or_b32_e32 v5, v5, v14
; VI-NEXT:    v_or_b32_e32 v4, v4, v13
; VI-NEXT:    v_or_b32_e32 v3, v3, v12
; VI-NEXT:    v_or_b32_e32 v2, v2, v11
; VI-NEXT:    v_or_b32_e32 v1, v1, v10
; VI-NEXT:    v_or_b32_e32 v0, v0, v9
; VI-NEXT:  .LBB92_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16i16_to_v16bf16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v16i16_to_v16bf16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB92_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX11-NEXT:  .LBB92_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <16 x i16> %a, splat (i16 3)
  %a2 = bitcast <16 x i16> %a1 to <16 x bfloat>
  br label %end

cmp.false:
  %a3 = bitcast <16 x i16> %a to <16 x bfloat>
  br label %end

end:
  %phi = phi <16 x bfloat> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x bfloat> %phi
}

define inreg <16 x bfloat> @bitcast_v16i16_to_v16bf16_scalar(<16 x i16> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v16i16_to_v16bf16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_lshr_b32 s47, s23, 16
; SI-NEXT:    s_lshr_b32 s46, s22, 16
; SI-NEXT:    s_lshr_b32 s45, s21, 16
; SI-NEXT:    s_lshr_b32 s44, s20, 16
; SI-NEXT:    s_lshr_b32 s43, s19, 16
; SI-NEXT:    s_lshr_b32 s42, s18, 16
; SI-NEXT:    s_lshr_b32 s41, s17, 16
; SI-NEXT:    s_lshr_b32 s40, s16, 16
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB93_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_lshl_b32 s25, s16, 16
; SI-NEXT:    s_lshl_b32 s29, s40, 16
; SI-NEXT:    s_lshl_b32 s15, s17, 16
; SI-NEXT:    s_lshl_b32 s28, s41, 16
; SI-NEXT:    s_lshl_b32 s13, s18, 16
; SI-NEXT:    s_lshl_b32 s27, s42, 16
; SI-NEXT:    s_lshl_b32 s11, s19, 16
; SI-NEXT:    s_lshl_b32 s26, s43, 16
; SI-NEXT:    s_lshl_b32 s10, s20, 16
; SI-NEXT:    s_lshl_b32 s24, s44, 16
; SI-NEXT:    s_lshl_b32 s8, s21, 16
; SI-NEXT:    s_lshl_b32 s14, s45, 16
; SI-NEXT:    s_lshl_b32 s7, s22, 16
; SI-NEXT:    s_lshl_b32 s12, s46, 16
; SI-NEXT:    s_lshl_b32 s6, s23, 16
; SI-NEXT:    s_lshl_b32 s9, s47, 16
; SI-NEXT:    s_cbranch_execnz .LBB93_3
; SI-NEXT:  .LBB93_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s23, s23, 3
; SI-NEXT:    s_and_b32 s4, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s47, 16
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_and_b32 s5, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s6, s46, 16
; SI-NEXT:    s_add_i32 s21, s21, 3
; SI-NEXT:    s_or_b32 s5, s6, s5
; SI-NEXT:    s_and_b32 s6, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s45, 16
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_or_b32 s6, s7, s6
; SI-NEXT:    s_and_b32 s7, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s8, s44, 16
; SI-NEXT:    s_add_i32 s19, s19, 3
; SI-NEXT:    s_or_b32 s7, s8, s7
; SI-NEXT:    s_and_b32 s8, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s9, s43, 16
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_or_b32 s8, s9, s8
; SI-NEXT:    s_and_b32 s9, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s42, 16
; SI-NEXT:    s_add_i32 s17, s17, 3
; SI-NEXT:    s_or_b32 s9, s10, s9
; SI-NEXT:    s_and_b32 s10, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s11, s41, 16
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    s_or_b32 s10, s11, s10
; SI-NEXT:    s_and_b32 s11, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s40, 16
; SI-NEXT:    s_or_b32 s11, s12, s11
; SI-NEXT:    s_add_i32 s4, s4, 0x30000
; SI-NEXT:    s_add_i32 s5, s5, 0x30000
; SI-NEXT:    s_add_i32 s6, s6, 0x30000
; SI-NEXT:    s_add_i32 s7, s7, 0x30000
; SI-NEXT:    s_add_i32 s8, s8, 0x30000
; SI-NEXT:    s_add_i32 s9, s9, 0x30000
; SI-NEXT:    s_add_i32 s10, s10, 0x30000
; SI-NEXT:    s_add_i32 s11, s11, 0x30000
; SI-NEXT:    s_and_b32 s29, s11, 0xffff0000
; SI-NEXT:    s_lshl_b32 s25, s11, 16
; SI-NEXT:    s_and_b32 s28, s10, 0xffff0000
; SI-NEXT:    s_lshl_b32 s15, s10, 16
; SI-NEXT:    s_and_b32 s27, s9, 0xffff0000
; SI-NEXT:    s_lshl_b32 s13, s9, 16
; SI-NEXT:    s_and_b32 s26, s8, 0xffff0000
; SI-NEXT:    s_lshl_b32 s11, s8, 16
; SI-NEXT:    s_and_b32 s24, s7, 0xffff0000
; SI-NEXT:    s_lshl_b32 s10, s7, 16
; SI-NEXT:    s_and_b32 s14, s6, 0xffff0000
; SI-NEXT:    s_lshl_b32 s8, s6, 16
; SI-NEXT:    s_and_b32 s12, s5, 0xffff0000
; SI-NEXT:    s_lshl_b32 s7, s5, 16
; SI-NEXT:    s_and_b32 s9, s4, 0xffff0000
; SI-NEXT:    s_lshl_b32 s6, s4, 16
; SI-NEXT:  .LBB93_3: ; %end
; SI-NEXT:    v_mul_f32_e64 v0, 1.0, s29
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v0
; SI-NEXT:    v_mul_f32_e64 v0, 1.0, s25
; SI-NEXT:    v_lshr_b64 v[0:1], v[0:1], 16
; SI-NEXT:    v_mul_f32_e64 v1, 1.0, s28
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v1
; SI-NEXT:    v_mul_f32_e64 v1, 1.0, s15
; SI-NEXT:    v_lshr_b64 v[1:2], v[1:2], 16
; SI-NEXT:    v_mul_f32_e64 v2, 1.0, s27
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v2
; SI-NEXT:    v_mul_f32_e64 v2, 1.0, s13
; SI-NEXT:    v_lshr_b64 v[2:3], v[2:3], 16
; SI-NEXT:    v_mul_f32_e64 v3, 1.0, s26
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v3
; SI-NEXT:    v_mul_f32_e64 v3, 1.0, s11
; SI-NEXT:    v_lshr_b64 v[3:4], v[3:4], 16
; SI-NEXT:    v_mul_f32_e64 v4, 1.0, s24
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v4
; SI-NEXT:    v_mul_f32_e64 v4, 1.0, s10
; SI-NEXT:    v_lshr_b64 v[4:5], v[4:5], 16
; SI-NEXT:    v_mul_f32_e64 v5, 1.0, s14
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v5
; SI-NEXT:    v_mul_f32_e64 v5, 1.0, s8
; SI-NEXT:    v_lshr_b64 v[5:6], v[5:6], 16
; SI-NEXT:    v_mul_f32_e64 v6, 1.0, s12
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v6
; SI-NEXT:    v_mul_f32_e64 v6, 1.0, s7
; SI-NEXT:    v_lshr_b64 v[6:7], v[6:7], 16
; SI-NEXT:    v_mul_f32_e64 v7, 1.0, s9
; SI-NEXT:    v_lshrrev_b32_e32 v8, 16, v7
; SI-NEXT:    v_mul_f32_e64 v7, 1.0, s6
; SI-NEXT:    v_lshr_b64 v[7:8], v[7:8], 16
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB93_4:
; SI-NEXT:    ; implicit-def: $sgpr25
; SI-NEXT:    ; implicit-def: $sgpr29
; SI-NEXT:    ; implicit-def: $sgpr15
; SI-NEXT:    ; implicit-def: $sgpr28
; SI-NEXT:    ; implicit-def: $sgpr13
; SI-NEXT:    ; implicit-def: $sgpr27
; SI-NEXT:    ; implicit-def: $sgpr11
; SI-NEXT:    ; implicit-def: $sgpr26
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr24
; SI-NEXT:    ; implicit-def: $sgpr8
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr7
; SI-NEXT:    ; implicit-def: $sgpr12
; SI-NEXT:    ; implicit-def: $sgpr6
; SI-NEXT:    ; implicit-def: $sgpr9
; SI-NEXT:    s_branch .LBB93_2
;
; VI-LABEL: bitcast_v16i16_to_v16bf16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB93_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB93_3
; VI-NEXT:  .LBB93_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s5, s16, 3
; VI-NEXT:    s_and_b32 s6, s17, 0xffff0000
; VI-NEXT:    s_add_i32 s7, s17, 3
; VI-NEXT:    s_add_i32 s9, s18, 3
; VI-NEXT:    s_and_b32 s10, s19, 0xffff0000
; VI-NEXT:    s_add_i32 s11, s19, 3
; VI-NEXT:    s_add_i32 s13, s20, 3
; VI-NEXT:    s_add_i32 s15, s21, 3
; VI-NEXT:    s_add_i32 s17, s22, 3
; VI-NEXT:    s_add_i32 s19, s23, 3
; VI-NEXT:    s_and_b32 s4, s16, 0xffff0000
; VI-NEXT:    s_and_b32 s8, s18, 0xffff0000
; VI-NEXT:    s_and_b32 s12, s20, 0xffff0000
; VI-NEXT:    s_and_b32 s14, s21, 0xffff0000
; VI-NEXT:    s_and_b32 s16, s22, 0xffff0000
; VI-NEXT:    s_and_b32 s18, s23, 0xffff0000
; VI-NEXT:    s_and_b32 s19, s19, 0xffff
; VI-NEXT:    s_and_b32 s17, s17, 0xffff
; VI-NEXT:    s_and_b32 s15, s15, 0xffff
; VI-NEXT:    s_and_b32 s13, s13, 0xffff
; VI-NEXT:    s_and_b32 s11, s11, 0xffff
; VI-NEXT:    s_and_b32 s9, s9, 0xffff
; VI-NEXT:    s_and_b32 s7, s7, 0xffff
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s18, s18, s19
; VI-NEXT:    s_or_b32 s16, s16, s17
; VI-NEXT:    s_or_b32 s14, s14, s15
; VI-NEXT:    s_or_b32 s12, s12, s13
; VI-NEXT:    s_or_b32 s10, s10, s11
; VI-NEXT:    s_or_b32 s8, s8, s9
; VI-NEXT:    s_or_b32 s6, s6, s7
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s23, s18, 0x30000
; VI-NEXT:    s_add_i32 s22, s16, 0x30000
; VI-NEXT:    s_add_i32 s21, s14, 0x30000
; VI-NEXT:    s_add_i32 s20, s12, 0x30000
; VI-NEXT:    s_add_i32 s19, s10, 0x30000
; VI-NEXT:    s_add_i32 s18, s8, 0x30000
; VI-NEXT:    s_add_i32 s17, s6, 0x30000
; VI-NEXT:    s_add_i32 s16, s4, 0x30000
; VI-NEXT:  .LBB93_3: ; %end
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB93_4:
; VI-NEXT:    s_branch .LBB93_2
;
; GFX9-LABEL: bitcast_v16i16_to_v16bf16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB93_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB93_4
; GFX9-NEXT:  .LBB93_2: ; %cmp.true
; GFX9-NEXT:    v_pk_add_u16 v7, s23, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, s22, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v5, s21, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v4, s20, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v3, s19, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v2, s18, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v1, s17, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v0, s16, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB93_3:
; GFX9-NEXT:    s_branch .LBB93_2
; GFX9-NEXT:  .LBB93_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v16i16_to_v16bf16_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s7, s19
; GFX11-NEXT:    s_mov_b32 s6, s18
; GFX11-NEXT:    s_mov_b32 s5, s17
; GFX11-NEXT:    s_mov_b32 s4, s16
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s8, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB93_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-NEXT:    s_cbranch_vccnz .LBB93_4
; GFX11-NEXT:  .LBB93_2: ; %cmp.true
; GFX11-NEXT:    v_pk_add_u16 v7, s7, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v6, s6, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v5, s5, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v4, s4, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v3, s3, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v2, s2, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v1, s1, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v0, s0, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB93_3:
; GFX11-NEXT:    s_branch .LBB93_2
; GFX11-NEXT:  .LBB93_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <16 x i16> %a, splat (i16 3)
  %a2 = bitcast <16 x i16> %a1 to <16 x bfloat>
  br label %end

cmp.false:
  %a3 = bitcast <16 x i16> %a to <16 x bfloat>
  br label %end

end:
  %phi = phi <16 x bfloat> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x bfloat> %phi
}

define <16 x i16> @bitcast_v16bf16_to_v16i16(<16 x bfloat> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v16bf16_to_v16i16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_and_b32_e32 v9, 0xffff0000, v7
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_and_b32_e32 v10, 0xffff0000, v6
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_and_b32_e32 v11, 0xffff0000, v5
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v12, 0xffff0000, v4
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_and_b32_e32 v13, 0xffff0000, v3
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v14, 0xffff0000, v2
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_and_b32_e32 v15, 0xffff0000, v1
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_and_b32_e32 v16, 0xffff0000, v0
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    v_mul_f32_e32 v31, 1.0, v0
; SI-NEXT:    v_mul_f32_e32 v30, 1.0, v16
; SI-NEXT:    v_mul_f32_e32 v16, 1.0, v1
; SI-NEXT:    v_mul_f32_e32 v15, 1.0, v15
; SI-NEXT:    v_mul_f32_e32 v29, 1.0, v2
; SI-NEXT:    v_mul_f32_e32 v28, 1.0, v14
; SI-NEXT:    v_mul_f32_e32 v19, 1.0, v3
; SI-NEXT:    v_mul_f32_e32 v18, 1.0, v13
; SI-NEXT:    v_mul_f32_e32 v27, 1.0, v4
; SI-NEXT:    v_mul_f32_e32 v26, 1.0, v12
; SI-NEXT:    v_mul_f32_e32 v21, 1.0, v5
; SI-NEXT:    v_mul_f32_e32 v20, 1.0, v11
; SI-NEXT:    v_mul_f32_e32 v25, 1.0, v6
; SI-NEXT:    v_mul_f32_e32 v24, 1.0, v10
; SI-NEXT:    v_mul_f32_e32 v23, 1.0, v7
; SI-NEXT:    v_mul_f32_e32 v22, 1.0, v9
; SI-NEXT:    ; implicit-def: $vgpr0
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr1
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr2
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr3
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr4
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr5
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr6
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr7
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB94_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v31
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v30
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v16
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v15
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v29
; SI-NEXT:    v_lshrrev_b32_e32 v13, 16, v28
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v19
; SI-NEXT:    v_lshrrev_b32_e32 v10, 16, v18
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v27
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v26
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v21
; SI-NEXT:    v_lshrrev_b32_e32 v9, 16, v20
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v25
; SI-NEXT:    v_lshrrev_b32_e32 v17, 16, v24
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v23
; SI-NEXT:    v_lshrrev_b32_e32 v8, 16, v22
; SI-NEXT:    ; implicit-def: $vgpr31
; SI-NEXT:    ; implicit-def: $vgpr30
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr29
; SI-NEXT:    ; implicit-def: $vgpr28
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr27
; SI-NEXT:    ; implicit-def: $vgpr26
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr25
; SI-NEXT:    ; implicit-def: $vgpr24
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:  .LBB94_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB94_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v30
; SI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v31
; SI-NEXT:    v_add_f32_e32 v12, 0x40c00000, v1
; SI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v12
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v28
; SI-NEXT:    v_alignbit_b32 v0, v1, v0, 16
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v29
; SI-NEXT:    v_add_f32_e32 v11, 0x40c00000, v2
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v11
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v26
; SI-NEXT:    v_alignbit_b32 v2, v2, v1, 16
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v27
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v3
; SI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v24
; SI-NEXT:    v_alignbit_b32 v4, v4, v1, 16
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v25
; SI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v5
; SI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v22
; SI-NEXT:    v_alignbit_b32 v6, v6, v1, 16
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v23
; SI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_lshrrev_b32_e32 v8, 16, v7
; SI-NEXT:    v_and_b32_e32 v17, 0xffff0000, v5
; SI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v20
; SI-NEXT:    v_alignbit_b32 v7, v8, v1, 16
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v21
; SI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_lshrrev_b32_e32 v9, 16, v5
; SI-NEXT:    v_and_b32_e32 v14, 0xffff0000, v3
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v18
; SI-NEXT:    v_alignbit_b32 v5, v9, v1, 16
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v19
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_lshrrev_b32_e32 v10, 16, v3
; SI-NEXT:    v_and_b32_e32 v13, 0xffff0000, v11
; SI-NEXT:    v_and_b32_e32 v11, 0xffff0000, v15
; SI-NEXT:    v_alignbit_b32 v3, v10, v1, 16
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v16
; SI-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v11
; SI-NEXT:    v_alignbit_b32 v1, v11, v1, 16
; SI-NEXT:    v_and_b32_e32 v12, 0xffff0000, v12
; SI-NEXT:    v_alignbit_b32 v12, v1, v12, 16
; SI-NEXT:    v_alignbit_b32 v13, v3, v13, 16
; SI-NEXT:    v_alignbit_b32 v14, v5, v14, 16
; SI-NEXT:    v_alignbit_b32 v17, v7, v17, 16
; SI-NEXT:  .LBB94_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v10
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v12
; SI-NEXT:    v_or_b32_e32 v1, v1, v11
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v13
; SI-NEXT:    v_or_b32_e32 v3, v3, v10
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v14
; SI-NEXT:    v_or_b32_e32 v5, v5, v9
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v17
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_or_b32_e32 v0, v0, v12
; SI-NEXT:    v_or_b32_e32 v2, v2, v11
; SI-NEXT:    v_or_b32_e32 v4, v4, v10
; SI-NEXT:    v_or_b32_e32 v6, v6, v9
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16bf16_to_v16i16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB94_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v0
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, 0x7fff, v9
; VI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v0, 16, 1
; VI-NEXT:    s_movk_i32 s6, 0x7fff
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v0
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v0
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; VI-NEXT:    v_cndmask_b32_e32 v0, v9, v10, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v9, 16, v1
; VI-NEXT:    v_add_f32_e32 v9, 0x40c00000, v9
; VI-NEXT:    v_bfe_u32 v10, v9, 16, 1
; VI-NEXT:    v_add_u32_e32 v10, vcc, v10, v9
; VI-NEXT:    v_add_u32_e32 v10, vcc, s6, v10
; VI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; VI-NEXT:    v_or_b32_e32 v11, 0x400000, v9
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v9, v9
; VI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; VI-NEXT:    v_cndmask_b32_e32 v9, v10, v11, vcc
; VI-NEXT:    v_bfe_u32 v10, v1, 16, 1
; VI-NEXT:    v_add_u32_e32 v10, vcc, v10, v1
; VI-NEXT:    v_add_u32_e32 v10, vcc, s6, v10
; VI-NEXT:    v_or_b32_e32 v11, 0x400000, v1
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; VI-NEXT:    v_cndmask_b32_e32 v1, v10, v11, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v10, 16, v2
; VI-NEXT:    v_add_f32_e32 v10, 0x40c00000, v10
; VI-NEXT:    v_bfe_u32 v11, v10, 16, 1
; VI-NEXT:    v_add_u32_e32 v11, vcc, v11, v10
; VI-NEXT:    v_add_u32_e32 v11, vcc, s6, v11
; VI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; VI-NEXT:    v_or_b32_e32 v12, 0x400000, v10
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v10, v10
; VI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; VI-NEXT:    v_cndmask_b32_e32 v10, v11, v12, vcc
; VI-NEXT:    v_bfe_u32 v11, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v11, vcc, v11, v2
; VI-NEXT:    v_add_u32_e32 v11, vcc, s6, v11
; VI-NEXT:    v_or_b32_e32 v12, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v11, v12, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v11, 16, v3
; VI-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; VI-NEXT:    v_bfe_u32 v12, v11, 16, 1
; VI-NEXT:    v_add_u32_e32 v12, vcc, v12, v11
; VI-NEXT:    v_add_u32_e32 v12, vcc, s6, v12
; VI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; VI-NEXT:    v_or_b32_e32 v13, 0x400000, v11
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v11, v11
; VI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; VI-NEXT:    v_cndmask_b32_e32 v11, v12, v13, vcc
; VI-NEXT:    v_bfe_u32 v12, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v12, vcc, v12, v3
; VI-NEXT:    v_add_u32_e32 v12, vcc, s6, v12
; VI-NEXT:    v_or_b32_e32 v13, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v12, v13, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v12, 16, v4
; VI-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; VI-NEXT:    v_bfe_u32 v13, v12, 16, 1
; VI-NEXT:    v_add_u32_e32 v13, vcc, v13, v12
; VI-NEXT:    v_add_u32_e32 v13, vcc, s6, v13
; VI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; VI-NEXT:    v_or_b32_e32 v14, 0x400000, v12
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v12, v12
; VI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; VI-NEXT:    v_cndmask_b32_e32 v12, v13, v14, vcc
; VI-NEXT:    v_bfe_u32 v13, v4, 16, 1
; VI-NEXT:    v_add_u32_e32 v13, vcc, v13, v4
; VI-NEXT:    v_add_u32_e32 v13, vcc, s6, v13
; VI-NEXT:    v_or_b32_e32 v14, 0x400000, v4
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; VI-NEXT:    v_cndmask_b32_e32 v4, v13, v14, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v13, 16, v5
; VI-NEXT:    v_add_f32_e32 v13, 0x40c00000, v13
; VI-NEXT:    v_bfe_u32 v14, v13, 16, 1
; VI-NEXT:    v_add_u32_e32 v14, vcc, v14, v13
; VI-NEXT:    v_add_u32_e32 v14, vcc, s6, v14
; VI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; VI-NEXT:    v_or_b32_e32 v15, 0x400000, v13
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v13, v13
; VI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; VI-NEXT:    v_cndmask_b32_e32 v13, v14, v15, vcc
; VI-NEXT:    v_bfe_u32 v14, v5, 16, 1
; VI-NEXT:    v_add_u32_e32 v14, vcc, v14, v5
; VI-NEXT:    v_add_u32_e32 v14, vcc, s6, v14
; VI-NEXT:    v_or_b32_e32 v15, 0x400000, v5
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; VI-NEXT:    v_cndmask_b32_e32 v5, v14, v15, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v14, 16, v6
; VI-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; VI-NEXT:    v_bfe_u32 v15, v14, 16, 1
; VI-NEXT:    v_add_u32_e32 v15, vcc, v15, v14
; VI-NEXT:    v_add_u32_e32 v15, vcc, s6, v15
; VI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; VI-NEXT:    v_or_b32_e32 v16, 0x400000, v14
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v14, v14
; VI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; VI-NEXT:    v_cndmask_b32_e32 v14, v15, v16, vcc
; VI-NEXT:    v_bfe_u32 v15, v6, 16, 1
; VI-NEXT:    v_add_u32_e32 v15, vcc, v15, v6
; VI-NEXT:    v_add_u32_e32 v15, vcc, s6, v15
; VI-NEXT:    v_or_b32_e32 v16, 0x400000, v6
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; VI-NEXT:    v_cndmask_b32_e32 v6, v15, v16, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v15, 16, v7
; VI-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; VI-NEXT:    v_bfe_u32 v16, v15, 16, 1
; VI-NEXT:    v_add_u32_e32 v16, vcc, v16, v15
; VI-NEXT:    v_add_u32_e32 v16, vcc, s6, v16
; VI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; VI-NEXT:    v_or_b32_e32 v17, 0x400000, v15
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v15, v15
; VI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; VI-NEXT:    v_cndmask_b32_e32 v15, v16, v17, vcc
; VI-NEXT:    v_bfe_u32 v16, v7, 16, 1
; VI-NEXT:    v_add_u32_e32 v16, vcc, v16, v7
; VI-NEXT:    v_add_u32_e32 v16, vcc, 0x7fff, v16
; VI-NEXT:    v_or_b32_e32 v17, 0x400000, v7
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; VI-NEXT:    v_cndmask_b32_e32 v7, v16, v17, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; VI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_lshrrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; VI-NEXT:    v_alignbit_b32 v7, v7, v15, 16
; VI-NEXT:    v_alignbit_b32 v6, v6, v14, 16
; VI-NEXT:    v_alignbit_b32 v5, v5, v13, 16
; VI-NEXT:    v_alignbit_b32 v4, v4, v12, 16
; VI-NEXT:    v_alignbit_b32 v3, v3, v11, 16
; VI-NEXT:    v_alignbit_b32 v2, v2, v10, 16
; VI-NEXT:    v_alignbit_b32 v1, v1, v9, 16
; VI-NEXT:    v_alignbit_b32 v0, v0, v8, 16
; VI-NEXT:  .LBB94_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16bf16_to_v16i16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB94_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v0
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    s_movk_i32 s6, 0x7fff
; GFX9-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v0, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v0, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v0
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v0, v9, v10, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v9, 16, v1
; GFX9-NEXT:    v_add_f32_e32 v9, 0x40c00000, v9
; GFX9-NEXT:    v_bfe_u32 v10, v9, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; GFX9-NEXT:    v_add3_u32 v10, v10, v9, s6
; GFX9-NEXT:    v_or_b32_e32 v11, 0x400000, v9
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v9, v9
; GFX9-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v9, v10, v11, vcc
; GFX9-NEXT:    v_bfe_u32 v10, v1, 16, 1
; GFX9-NEXT:    v_add3_u32 v10, v10, v1, s6
; GFX9-NEXT:    v_or_b32_e32 v11, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v10, v11, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v10, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v10, 0x40c00000, v10
; GFX9-NEXT:    v_bfe_u32 v11, v10, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; GFX9-NEXT:    v_add3_u32 v11, v11, v10, s6
; GFX9-NEXT:    v_or_b32_e32 v12, 0x400000, v10
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v10, v10
; GFX9-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v10, v11, v12, vcc
; GFX9-NEXT:    v_bfe_u32 v11, v2, 16, 1
; GFX9-NEXT:    v_add3_u32 v11, v11, v2, s6
; GFX9-NEXT:    v_or_b32_e32 v12, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v11, v12, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v11, 16, v3
; GFX9-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; GFX9-NEXT:    v_bfe_u32 v12, v11, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; GFX9-NEXT:    v_add3_u32 v12, v12, v11, s6
; GFX9-NEXT:    v_or_b32_e32 v13, 0x400000, v11
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v11, v11
; GFX9-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GFX9-NEXT:    v_cndmask_b32_e32 v11, v12, v13, vcc
; GFX9-NEXT:    v_bfe_u32 v12, v3, 16, 1
; GFX9-NEXT:    v_add3_u32 v12, v12, v3, s6
; GFX9-NEXT:    v_or_b32_e32 v13, 0x400000, v3
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; GFX9-NEXT:    v_cndmask_b32_e32 v3, v12, v13, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v12, 16, v4
; GFX9-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; GFX9-NEXT:    v_bfe_u32 v13, v12, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; GFX9-NEXT:    v_add3_u32 v13, v13, v12, s6
; GFX9-NEXT:    v_or_b32_e32 v14, 0x400000, v12
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v12, v12
; GFX9-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; GFX9-NEXT:    v_cndmask_b32_e32 v12, v13, v14, vcc
; GFX9-NEXT:    v_bfe_u32 v13, v4, 16, 1
; GFX9-NEXT:    v_add3_u32 v13, v13, v4, s6
; GFX9-NEXT:    v_or_b32_e32 v14, 0x400000, v4
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; GFX9-NEXT:    v_cndmask_b32_e32 v4, v13, v14, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v13, 16, v5
; GFX9-NEXT:    v_add_f32_e32 v13, 0x40c00000, v13
; GFX9-NEXT:    v_bfe_u32 v14, v13, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; GFX9-NEXT:    v_add3_u32 v14, v14, v13, s6
; GFX9-NEXT:    v_or_b32_e32 v15, 0x400000, v13
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v13, v13
; GFX9-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v13, v14, v15, vcc
; GFX9-NEXT:    v_bfe_u32 v14, v5, 16, 1
; GFX9-NEXT:    v_add3_u32 v14, v14, v5, s6
; GFX9-NEXT:    v_or_b32_e32 v15, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v5, v14, v15, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v14, 16, v6
; GFX9-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; GFX9-NEXT:    v_bfe_u32 v15, v14, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; GFX9-NEXT:    v_add3_u32 v15, v15, v14, s6
; GFX9-NEXT:    v_or_b32_e32 v16, 0x400000, v14
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v14, v14
; GFX9-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GFX9-NEXT:    v_cndmask_b32_e32 v14, v15, v16, vcc
; GFX9-NEXT:    v_bfe_u32 v15, v6, 16, 1
; GFX9-NEXT:    v_add3_u32 v15, v15, v6, s6
; GFX9-NEXT:    v_or_b32_e32 v16, 0x400000, v6
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; GFX9-NEXT:    v_cndmask_b32_e32 v6, v15, v16, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v15, 16, v7
; GFX9-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; GFX9-NEXT:    v_bfe_u32 v16, v15, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; GFX9-NEXT:    v_add3_u32 v16, v16, v15, s6
; GFX9-NEXT:    v_or_b32_e32 v17, 0x400000, v15
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v15, v15
; GFX9-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GFX9-NEXT:    v_cndmask_b32_e32 v15, v16, v17, vcc
; GFX9-NEXT:    v_bfe_u32 v16, v7, 16, 1
; GFX9-NEXT:    v_add3_u32 v16, v16, v7, s6
; GFX9-NEXT:    v_or_b32_e32 v17, 0x400000, v7
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; GFX9-NEXT:    v_cndmask_b32_e32 v7, v16, v17, vcc
; GFX9-NEXT:    s_mov_b32 s6, 0x7060302
; GFX9-NEXT:    v_perm_b32 v7, v7, v15, s6
; GFX9-NEXT:    v_perm_b32 v6, v6, v14, s6
; GFX9-NEXT:    v_perm_b32 v5, v5, v13, s6
; GFX9-NEXT:    v_perm_b32 v4, v4, v12, s6
; GFX9-NEXT:    v_perm_b32 v3, v3, v11, s6
; GFX9-NEXT:    v_perm_b32 v2, v2, v10, s6
; GFX9-NEXT:    v_perm_b32 v1, v1, v9, s6
; GFX9-NEXT:    v_perm_b32 v0, v0, v8, s6
; GFX9-NEXT:  .LBB94_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v16bf16_to_v16i16:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB94_2
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v9, 16, v1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v9, 0x40c00000, v9 :: v_dual_lshlrev_b32 v8, 16, v0
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v14, v9, 16, 1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v11, v8, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v12, 0x400000, v8
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v16, 0x400000, v9
; GFX11-TRUE16-NEXT:    v_add3_u32 v14, v14, v9, 0x7fff
; GFX11-TRUE16-NEXT:    v_add3_u32 v11, v11, v8, 0x7fff
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_dual_cndmask_b32 v8, v11, v12 :: v_dual_and_b32 v1, 0xffff0000, v1
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v1, 0x40c00000, v1 :: v_dual_lshlrev_b32 v10, 16, v2
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v12, 16, v3
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v11, v1, 16, 1
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v12, 0x40c00000, v12 :: v_dual_add_f32 v3, 0x40c00000, v3
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GFX11-TRUE16-NEXT:    v_add3_u32 v11, v11, v1, 0x7fff
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v13, v0, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v15, 0x400000, v0
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add3_u32 v13, v13, v0, 0x7fff
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v0, v13, v15, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v13, 0x400000, v1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v15, v12, 16, 1
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.l, v8.h
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v9, v14, v16, vcc_lo
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v16, 16, v4
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v10, 0x40c00000, v10
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v14, v10, 16, 1
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v11, v13, vcc_lo
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v13, 0x400000, v10
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v1.l, v9.h
; GFX11-TRUE16-NEXT:    v_add3_u32 v11, v14, v10, 0x7fff
; GFX11-TRUE16-NEXT:    v_bfe_u32 v14, v2, 16, 1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v10, v11, v13, vcc_lo
; GFX11-TRUE16-NEXT:    v_add3_u32 v11, v14, v2, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v13, 0x400000, v2
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-TRUE16-NEXT:    v_add3_u32 v14, v15, v12, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v15, 0x400000, v12
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v2, v11, v13, vcc_lo
; GFX11-TRUE16-NEXT:    v_bfe_u32 v11, v3, 16, 1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v12, v12
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.l, v10.h
; GFX11-TRUE16-NEXT:    v_add3_u32 v11, v11, v3, 0x7fff
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v12, v14, v15, vcc_lo
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v14, 0x400000, v3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v15, 16, v5
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v3, v11, v14, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v11, 0x40c00000, v15
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v13, 0x40c00000, v16
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v3.l, v12.h
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v18, 0x400000, v11
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v16, v13, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v15, 0x400000, v13
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v13, v13
; GFX11-TRUE16-NEXT:    v_bfe_u32 v17, v11, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; GFX11-TRUE16-NEXT:    v_add3_u32 v14, v16, v13, 0x7fff
; GFX11-TRUE16-NEXT:    v_bfe_u32 v19, v5, 16, 1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v16, v4, 16, 1
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v13, v14, v15, vcc_lo
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v15, 0x400000, v4
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_add3_u32 v14, v16, v4, 0x7fff
; GFX11-TRUE16-NEXT:    v_add3_u32 v16, v17, v11, 0x7fff
; GFX11-TRUE16-NEXT:    v_dual_cndmask_b32 v4, v14, v15 :: v_dual_lshlrev_b32 v17, 16, v6
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v11, v11
; GFX11-TRUE16-NEXT:    v_add3_u32 v15, v19, v5, 0x7fff
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v4.l, v13.h
; GFX11-TRUE16-NEXT:    v_dual_cndmask_b32 v11, v16, v18 :: v_dual_lshlrev_b32 v18, 16, v7
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v14, 0x40c00000, v17
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v16, 0x400000, v5
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GFX11-TRUE16-NEXT:    v_bfe_u32 v17, v14, 16, 1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_2) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v5, v15, v16, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v15, 0x40c00000, v18
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v14, v14
; GFX11-TRUE16-NEXT:    v_add3_u32 v16, v17, v14, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v17, 0x400000, v14
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v21, 0x400000, v7
; GFX11-TRUE16-NEXT:    v_bfe_u32 v19, v15, 16, 1
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v5.l, v11.h
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v14, v16, v17, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v15, v15
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; GFX11-TRUE16-NEXT:    v_bfe_u32 v16, v7, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_add3_u32 v16, v16, v7, 0x7fff
; GFX11-TRUE16-NEXT:    v_bfe_u32 v18, v6, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v20, 0x400000, v6
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_2) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add3_u32 v17, v18, v6, 0x7fff
; GFX11-TRUE16-NEXT:    v_add3_u32 v18, v19, v15, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v19, 0x400000, v15
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v15, v18, v19, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v6, v17, v20, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v6.l, v14.h
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v7, v16, v21, vcc_lo
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v7.l, v15.h
; GFX11-TRUE16-NEXT:  .LBB94_2: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v16bf16_to_v16i16:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-FAKE16-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB94_2
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v9, 16, v1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v9, 0x40c00000, v9 :: v_dual_lshlrev_b32 v8, 16, v0
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v9, 16, 1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v11, v8, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v14, 0x400000, v8
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_add3_u32 v13, v13, v9, 0x7fff
; GFX11-FAKE16-NEXT:    v_add3_u32 v11, v11, v8, 0x7fff
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v8, v11, v14 :: v_dual_and_b32 v1, 0xffff0000, v1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, 0x400000, v9
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v1, 0x40c00000, v1 :: v_dual_lshlrev_b32 v14, 16, v3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v14, 0x40c00000, v14 :: v_dual_add_f32 v3, 0x40c00000, v3
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_2) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v12, v0, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v15, 0x400000, v0
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v16, 0x400000, v3
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_add3_u32 v12, v12, v0, 0x7fff
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v0, v12, v15 :: v_dual_lshlrev_b32 v15, 16, v4
; GFX11-FAKE16-NEXT:    v_bfe_u32 v12, v1, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v0, v8, 0x7060302
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v9, v13, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_add3_u32 v11, v12, v1, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, 0x400000, v1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v10, 16, v2
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v17, 0x400000, v15
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v1, v11, v12 :: v_dual_add_f32 v10, 0x40c00000, v10
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v18, v4, 16, 1
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v1, v9, 0x7060302
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v10, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, 0x400000, v10
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-FAKE16-NEXT:    v_add3_u32 v11, v13, v10, 0x7fff
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v2, 16, 1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v10, v11, v12, vcc_lo
; GFX11-FAKE16-NEXT:    v_add3_u32 v11, v13, v2, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, 0x400000, v2
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v14, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v2, v11, v12, vcc_lo
; GFX11-FAKE16-NEXT:    v_add3_u32 v11, v13, v14, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, 0x400000, v14
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v14, v14
; GFX11-FAKE16-NEXT:    v_bfe_u32 v14, v15, 16, 1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v3, 16, 1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v11, v11, v12 :: v_dual_lshlrev_b32 v12, 16, v5
; GFX11-FAKE16-NEXT:    v_add3_u32 v14, v14, v15, 0x7fff
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v15, v15
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; GFX11-FAKE16-NEXT:    v_add3_u32 v15, v18, v4, 0x7fff
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; GFX11-FAKE16-NEXT:    v_add3_u32 v13, v13, v3, 0x7fff
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v14, v14, v17, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v2, v10, 0x7060302
; GFX11-FAKE16-NEXT:    v_bfe_u32 v19, v12, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v20, 0x400000, v12
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v21, v5, 16, 1
; GFX11-FAKE16-NEXT:    v_add3_u32 v18, v19, v12, 0x7fff
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v19, 16, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v17, 0x400000, v4
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v4, v15, v17 :: v_dual_add_f32 v15, 0x40c00000, v19
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v12, v12
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GFX11-FAKE16-NEXT:    v_add3_u32 v17, v21, v5, 0x7fff
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v19, v15, 16, 1
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v12, v18, v20, vcc_lo
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v18, 16, v7
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v21, 0x400000, v15
; GFX11-FAKE16-NEXT:    v_add3_u32 v19, v19, v15, 0x7fff
; GFX11-FAKE16-NEXT:    v_bfe_u32 v22, v6, 16, 1
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v18, 0x40c00000, v18
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v15, v15
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v20, 0x400000, v5
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v23, v18, 16, 1
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v15, v19, v21, vcc_lo
; GFX11-FAKE16-NEXT:    v_add3_u32 v21, v22, v6, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v22, 0x400000, v6
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-FAKE16-NEXT:    v_bfe_u32 v19, v7, 16, 1
; GFX11-FAKE16-NEXT:    v_add3_u32 v23, v23, v18, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v24, 0x400000, v18
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v25, 0x400000, v7
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v6, v21, v22, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-FAKE16-NEXT:    v_add3_u32 v19, v19, v7, 0x7fff
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v6, v15, 0x7060302
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v18, v23, v24, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v7, v19, v25, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_3) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v7, v18, 0x7060302
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v5, v17, v20, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v4, v14, 0x7060302
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v5, v12, 0x7060302
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v3, v13, v16, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v3, v11, 0x7060302
; GFX11-FAKE16-NEXT:  .LBB94_2: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x bfloat> %a, splat (bfloat 0xR40C0)
  %a2 = bitcast <16 x bfloat> %a1 to <16 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <16 x bfloat> %a to <16 x i16>
  br label %end

end:
  %phi = phi <16 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x i16> %phi
}

define inreg <16 x i16> @bitcast_v16bf16_to_v16i16_scalar(<16 x bfloat> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v16bf16_to_v16i16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_and_b32 s4, s23, 0xffff0000
; SI-NEXT:    s_lshl_b32 s5, s23, 16
; SI-NEXT:    s_and_b32 s6, s22, 0xffff0000
; SI-NEXT:    s_lshl_b32 s7, s22, 16
; SI-NEXT:    s_and_b32 s8, s21, 0xffff0000
; SI-NEXT:    s_lshl_b32 s9, s21, 16
; SI-NEXT:    s_and_b32 s10, s20, 0xffff0000
; SI-NEXT:    s_lshl_b32 s11, s20, 16
; SI-NEXT:    s_and_b32 s12, s19, 0xffff0000
; SI-NEXT:    s_lshl_b32 s13, s19, 16
; SI-NEXT:    s_and_b32 s14, s18, 0xffff0000
; SI-NEXT:    s_lshl_b32 s15, s18, 16
; SI-NEXT:    s_and_b32 s18, s17, 0xffff0000
; SI-NEXT:    s_lshl_b32 s17, s17, 16
; SI-NEXT:    s_and_b32 s19, s16, 0xffff0000
; SI-NEXT:    s_lshl_b32 s16, s16, 16
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    v_mul_f32_e64 v31, 1.0, s16
; SI-NEXT:    v_mul_f32_e64 v1, 1.0, s19
; SI-NEXT:    v_mul_f32_e64 v21, 1.0, s17
; SI-NEXT:    v_mul_f32_e64 v12, 1.0, s18
; SI-NEXT:    v_mul_f32_e64 v30, 1.0, s15
; SI-NEXT:    v_mul_f32_e64 v6, 1.0, s14
; SI-NEXT:    v_mul_f32_e64 v4, 1.0, s13
; SI-NEXT:    v_mul_f32_e64 v2, 1.0, s12
; SI-NEXT:    v_mul_f32_e64 v29, 1.0, s11
; SI-NEXT:    v_mul_f32_e64 v28, 1.0, s10
; SI-NEXT:    v_mul_f32_e64 v17, 1.0, s9
; SI-NEXT:    v_mul_f32_e64 v10, 1.0, s8
; SI-NEXT:    v_mul_f32_e64 v27, 1.0, s7
; SI-NEXT:    v_mul_f32_e64 v15, 1.0, s6
; SI-NEXT:    v_mul_f32_e64 v19, 1.0, s5
; SI-NEXT:    v_mul_f32_e64 v8, 1.0, s4
; SI-NEXT:    s_cbranch_scc0 .LBB95_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v31
; SI-NEXT:    v_lshrrev_b32_e32 v23, 16, v1
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v12
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v30
; SI-NEXT:    v_lshrrev_b32_e32 v24, 16, v6
; SI-NEXT:    v_lshrrev_b32_e32 v20, 16, v2
; SI-NEXT:    v_lshrrev_b32_e32 v13, 16, v29
; SI-NEXT:    v_lshrrev_b32_e32 v25, 16, v28
; SI-NEXT:    v_lshrrev_b32_e32 v18, 16, v10
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v27
; SI-NEXT:    v_lshrrev_b32_e32 v26, 16, v15
; SI-NEXT:    v_lshrrev_b32_e32 v16, 16, v8
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v21
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v4
; SI-NEXT:    v_lshrrev_b32_e32 v9, 16, v17
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v19
; SI-NEXT:    s_cbranch_execnz .LBB95_3
; SI-NEXT:  .LBB95_2: ; %cmp.true
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; SI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v31
; SI-NEXT:    v_add_f32_e32 v23, 0x40c00000, v1
; SI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v23
; SI-NEXT:    v_lshr_b64 v[0:1], v[0:1], 16
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v30
; SI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v1
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v6
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v1
; SI-NEXT:    v_lshr_b64 v[5:6], v[5:6], 16
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v29
; SI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v3
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v28
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v3
; SI-NEXT:    v_lshr_b64 v[13:14], v[6:7], 16
; SI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v15
; SI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v27
; SI-NEXT:    v_add_f32_e32 v9, 0x40c00000, v7
; SI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v9
; SI-NEXT:    v_lshr_b64 v[14:15], v[6:7], 16
; SI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v19
; SI-NEXT:    v_add_f32_e32 v15, 0x40c00000, v6
; SI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v8
; SI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; SI-NEXT:    v_lshrrev_b32_e32 v16, 16, v6
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; SI-NEXT:    v_lshr_b64 v[7:8], v[15:16], 16
; SI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; SI-NEXT:    v_and_b32_e32 v8, 0xffff0000, v17
; SI-NEXT:    v_lshrrev_b32_e32 v20, 16, v2
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v1
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v21
; SI-NEXT:    v_add_f32_e32 v17, 0x40c00000, v8
; SI-NEXT:    v_and_b32_e32 v8, 0xffff0000, v10
; SI-NEXT:    v_add_f32_e32 v21, 0x40c00000, v1
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v12
; SI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_lshrrev_b32_e32 v18, 16, v8
; SI-NEXT:    v_and_b32_e32 v8, 0xffff0000, v3
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v4
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v1
; SI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v9
; SI-NEXT:    v_lshr_b64 v[9:10], v[17:18], 16
; SI-NEXT:    v_add_f32_e32 v19, 0x40c00000, v3
; SI-NEXT:    v_lshr_b64 v[11:12], v[21:22], 16
; SI-NEXT:    v_lshr_b64 v[3:4], v[19:20], 16
; SI-NEXT:    v_and_b32_e32 v10, 0xffff0000, v23
; SI-NEXT:    v_lshr_b64 v[23:24], v[10:11], 16
; SI-NEXT:    v_lshr_b64 v[24:25], v[2:3], 16
; SI-NEXT:    v_lshr_b64 v[25:26], v[8:9], 16
; SI-NEXT:    v_lshr_b64 v[26:27], v[6:7], 16
; SI-NEXT:  .LBB95_3: ; %end
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v23
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v11
; SI-NEXT:    v_or_b32_e32 v0, v0, v2
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v22
; SI-NEXT:    v_or_b32_e32 v1, v1, v2
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v24
; SI-NEXT:    v_or_b32_e32 v2, v2, v4
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v20
; SI-NEXT:    v_or_b32_e32 v3, v3, v4
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v13
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v25
; SI-NEXT:    v_or_b32_e32 v4, v4, v5
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v9
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v18
; SI-NEXT:    v_or_b32_e32 v5, v5, v6
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v14
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v26
; SI-NEXT:    v_or_b32_e32 v6, v6, v8
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v16
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB95_4:
; SI-NEXT:    ; implicit-def: $vgpr0
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr5
; SI-NEXT:    ; implicit-def: $vgpr24
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr25
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr26
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr3
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr7
; SI-NEXT:    s_branch .LBB95_2
;
; VI-LABEL: bitcast_v16bf16_to_v16i16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB95_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB95_4
; VI-NEXT:  .LBB95_2: ; %cmp.true
; VI-NEXT:    s_lshl_b32 s4, s16, 16
; VI-NEXT:    v_mov_b32_e32 v10, 0x40c00000
; VI-NEXT:    v_add_f32_e32 v0, s4, v10
; VI-NEXT:    v_bfe_u32 v1, v0, 16, 1
; VI-NEXT:    v_add_u32_e32 v1, vcc, v1, v0
; VI-NEXT:    v_add_u32_e32 v1, vcc, 0x7fff, v1
; VI-NEXT:    v_or_b32_e32 v2, 0x400000, v0
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; VI-NEXT:    s_and_b32 s4, s16, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v0, v1, v2, vcc
; VI-NEXT:    v_add_f32_e32 v1, s4, v10
; VI-NEXT:    v_bfe_u32 v2, v1, 16, 1
; VI-NEXT:    v_add_u32_e32 v2, vcc, v2, v1
; VI-NEXT:    v_add_u32_e32 v2, vcc, 0x7fff, v2
; VI-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; VI-NEXT:    s_lshl_b32 s4, s17, 16
; VI-NEXT:    v_cndmask_b32_e32 v1, v2, v3, vcc
; VI-NEXT:    v_add_f32_e32 v2, s4, v10
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    s_and_b32 s4, s17, 0xffff0000
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_add_f32_e32 v2, s4, v10
; VI-NEXT:    v_cndmask_b32_e32 v8, v3, v4, vcc
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; VI-NEXT:    s_lshl_b32 s4, s18, 16
; VI-NEXT:    v_lshrrev_b32_e32 v9, 16, v2
; VI-NEXT:    v_add_f32_e32 v2, s4, v10
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    s_and_b32 s4, s18, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; VI-NEXT:    v_add_f32_e32 v3, s4, v10
; VI-NEXT:    v_bfe_u32 v4, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v4, vcc, v4, v3
; VI-NEXT:    v_add_u32_e32 v4, vcc, 0x7fff, v4
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    s_lshl_b32 s4, s19, 16
; VI-NEXT:    v_cndmask_b32_e32 v3, v4, v5, vcc
; VI-NEXT:    v_add_f32_e32 v4, s4, v10
; VI-NEXT:    v_bfe_u32 v5, v4, 16, 1
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v4
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    s_and_b32 s4, s19, 0xffff0000
; VI-NEXT:    v_or_b32_e32 v6, 0x400000, v4
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; VI-NEXT:    v_add_f32_e32 v4, s4, v10
; VI-NEXT:    v_cndmask_b32_e32 v11, v5, v6, vcc
; VI-NEXT:    v_bfe_u32 v5, v4, 16, 1
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v4
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    v_or_b32_e32 v6, 0x400000, v4
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; VI-NEXT:    v_cndmask_b32_e32 v4, v5, v6, vcc
; VI-NEXT:    s_lshl_b32 s4, s20, 16
; VI-NEXT:    v_lshrrev_b32_e32 v12, 16, v4
; VI-NEXT:    v_add_f32_e32 v4, s4, v10
; VI-NEXT:    v_bfe_u32 v5, v4, 16, 1
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v4
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    v_or_b32_e32 v6, 0x400000, v4
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; VI-NEXT:    s_and_b32 s4, s20, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v4, v5, v6, vcc
; VI-NEXT:    v_add_f32_e32 v5, s4, v10
; VI-NEXT:    v_bfe_u32 v6, v5, 16, 1
; VI-NEXT:    v_add_u32_e32 v6, vcc, v6, v5
; VI-NEXT:    v_add_u32_e32 v6, vcc, 0x7fff, v6
; VI-NEXT:    s_and_b32 s5, s21, 0xffff0000
; VI-NEXT:    v_or_b32_e32 v7, 0x400000, v5
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; VI-NEXT:    v_add_f32_e32 v13, s5, v10
; VI-NEXT:    s_lshl_b32 s5, s22, 16
; VI-NEXT:    v_cndmask_b32_e32 v5, v6, v7, vcc
; VI-NEXT:    v_add_f32_e32 v6, s5, v10
; VI-NEXT:    v_bfe_u32 v7, v6, 16, 1
; VI-NEXT:    v_add_u32_e32 v7, vcc, v7, v6
; VI-NEXT:    v_add_u32_e32 v7, vcc, 0x7fff, v7
; VI-NEXT:    v_or_b32_e32 v14, 0x400000, v6
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; VI-NEXT:    s_and_b32 s5, s22, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v6, v7, v14, vcc
; VI-NEXT:    v_add_f32_e32 v7, s5, v10
; VI-NEXT:    v_bfe_u32 v14, v7, 16, 1
; VI-NEXT:    v_add_u32_e32 v14, vcc, v14, v7
; VI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_add_u32_e32 v14, vcc, 0x7fff, v14
; VI-NEXT:    v_or_b32_e32 v15, 0x400000, v7
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; VI-NEXT:    v_lshrrev_b64 v[4:5], 16, v[4:5]
; VI-NEXT:    v_cndmask_b32_e32 v7, v14, v15, vcc
; VI-NEXT:    v_bfe_u32 v5, v13, 16, 1
; VI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v13
; VI-NEXT:    s_lshl_b32 s4, s21, 16
; VI-NEXT:    v_lshrrev_b64 v[6:7], 16, v[6:7]
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    v_or_b32_e32 v7, 0x400000, v13
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v13, v13
; VI-NEXT:    v_add_f32_e32 v13, s4, v10
; VI-NEXT:    v_cndmask_b32_e32 v5, v5, v7, vcc
; VI-NEXT:    v_bfe_u32 v7, v13, 16, 1
; VI-NEXT:    v_add_u32_e32 v7, vcc, v7, v13
; VI-NEXT:    v_add_u32_e32 v7, vcc, 0x7fff, v7
; VI-NEXT:    v_or_b32_e32 v14, 0x400000, v13
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v13, v13
; VI-NEXT:    s_and_b32 s4, s23, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v13, v7, v14, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v14, 16, v5
; VI-NEXT:    v_add_f32_e32 v5, s4, v10
; VI-NEXT:    v_bfe_u32 v7, v5, 16, 1
; VI-NEXT:    v_add_u32_e32 v7, vcc, v7, v5
; VI-NEXT:    v_add_u32_e32 v7, vcc, 0x7fff, v7
; VI-NEXT:    v_or_b32_e32 v15, 0x400000, v5
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; VI-NEXT:    s_lshl_b32 s4, s23, 16
; VI-NEXT:    v_cndmask_b32_e32 v5, v7, v15, vcc
; VI-NEXT:    v_add_f32_e32 v7, s4, v10
; VI-NEXT:    v_bfe_u32 v10, v7, 16, 1
; VI-NEXT:    v_add_u32_e32 v10, vcc, v10, v7
; VI-NEXT:    v_add_u32_e32 v10, vcc, 0x7fff, v10
; VI-NEXT:    v_or_b32_e32 v15, 0x400000, v7
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; VI-NEXT:    v_cndmask_b32_e32 v15, v10, v15, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v16, 16, v5
; VI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_lshrrev_b64 v[15:16], 16, v[15:16]
; VI-NEXT:    v_lshrrev_b64 v[13:14], 16, v[13:14]
; VI-NEXT:    v_lshrrev_b64 v[10:11], 16, v[11:12]
; VI-NEXT:    v_lshrrev_b64 v[7:8], 16, v[8:9]
; VI-NEXT:    v_lshrrev_b64 v[2:3], 16, v[2:3]
; VI-NEXT:    v_lshrrev_b64 v[0:1], 16, v[0:1]
; VI-NEXT:    v_mov_b32_e32 v1, v7
; VI-NEXT:    v_mov_b32_e32 v3, v10
; VI-NEXT:    v_mov_b32_e32 v5, v13
; VI-NEXT:    v_mov_b32_e32 v7, v15
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB95_3:
; VI-NEXT:    s_branch .LBB95_2
; VI-NEXT:  .LBB95_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16bf16_to_v16i16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB95_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB95_4
; GFX9-NEXT:  .LBB95_2: ; %cmp.true
; GFX9-NEXT:    s_and_b32 s4, s16, 0xffff0000
; GFX9-NEXT:    v_mov_b32_e32 v1, 0x40c00000
; GFX9-NEXT:    v_add_f32_e32 v0, s4, v1
; GFX9-NEXT:    v_bfe_u32 v2, v0, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v0
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v3, 0x400000, v0
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; GFX9-NEXT:    s_lshl_b32 s4, s16, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v0, v2, v3, vcc
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v1
; GFX9-NEXT:    v_bfe_u32 v3, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v3, v3, v2
; GFX9-NEXT:    s_and_b32 s4, s17, 0xffff0000
; GFX9-NEXT:    v_add_u32_e32 v3, 0x7fff, v3
; GFX9-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v3, v4, vcc
; GFX9-NEXT:    v_bfe_u32 v3, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v3, v3, v2
; GFX9-NEXT:    s_lshl_b32 s4, s17, 16
; GFX9-NEXT:    v_add_u32_e32 v3, 0x7fff, v3
; GFX9-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v9, v3, v4, vcc
; GFX9-NEXT:    v_bfe_u32 v3, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v3, v3, v2
; GFX9-NEXT:    s_and_b32 s4, s18, 0xffff0000
; GFX9-NEXT:    v_add_u32_e32 v3, 0x7fff, v3
; GFX9-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_add_f32_e32 v2, s4, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v10, v3, v4, vcc
; GFX9-NEXT:    v_bfe_u32 v3, v2, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v3, v3, v2
; GFX9-NEXT:    v_add_u32_e32 v3, 0x7fff, v3
; GFX9-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    s_lshl_b32 s4, s18, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; GFX9-NEXT:    v_add_f32_e32 v3, s4, v1
; GFX9-NEXT:    v_bfe_u32 v4, v3, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v4, v4, v3
; GFX9-NEXT:    s_and_b32 s4, s19, 0xffff0000
; GFX9-NEXT:    v_add_u32_e32 v4, 0x7fff, v4
; GFX9-NEXT:    v_or_b32_e32 v5, 0x400000, v3
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; GFX9-NEXT:    v_add_f32_e32 v3, s4, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v11, v4, v5, vcc
; GFX9-NEXT:    v_bfe_u32 v4, v3, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v4, v4, v3
; GFX9-NEXT:    v_add_u32_e32 v4, 0x7fff, v4
; GFX9-NEXT:    v_or_b32_e32 v5, 0x400000, v3
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; GFX9-NEXT:    s_lshl_b32 s4, s19, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v3, v4, v5, vcc
; GFX9-NEXT:    v_add_f32_e32 v4, s4, v1
; GFX9-NEXT:    v_bfe_u32 v5, v4, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v5, v5, v4
; GFX9-NEXT:    s_and_b32 s5, s22, 0xffff0000
; GFX9-NEXT:    v_add_u32_e32 v5, 0x7fff, v5
; GFX9-NEXT:    v_or_b32_e32 v6, 0x400000, v4
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; GFX9-NEXT:    v_add_f32_e32 v4, s5, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v12, v5, v6, vcc
; GFX9-NEXT:    v_bfe_u32 v5, v4, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v5, v5, v4
; GFX9-NEXT:    v_add_u32_e32 v5, 0x7fff, v5
; GFX9-NEXT:    v_or_b32_e32 v6, 0x400000, v4
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; GFX9-NEXT:    s_lshl_b32 s5, s22, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v4, v5, v6, vcc
; GFX9-NEXT:    v_add_f32_e32 v5, s5, v1
; GFX9-NEXT:    v_bfe_u32 v6, v5, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v6, v6, v5
; GFX9-NEXT:    v_add_u32_e32 v6, 0x7fff, v6
; GFX9-NEXT:    v_or_b32_e32 v7, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    s_and_b32 s5, s23, 0xffff0000
; GFX9-NEXT:    v_cndmask_b32_e32 v5, v6, v7, vcc
; GFX9-NEXT:    v_add_f32_e32 v6, s5, v1
; GFX9-NEXT:    v_bfe_u32 v7, v6, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v7, v7, v6
; GFX9-NEXT:    v_add_u32_e32 v7, 0x7fff, v7
; GFX9-NEXT:    v_or_b32_e32 v13, 0x400000, v6
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; GFX9-NEXT:    s_lshl_b32 s5, s23, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v6, v7, v13, vcc
; GFX9-NEXT:    v_add_f32_e32 v7, s5, v1
; GFX9-NEXT:    v_bfe_u32 v13, v7, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v13, v13, v7
; GFX9-NEXT:    v_add_u32_e32 v13, 0x7fff, v13
; GFX9-NEXT:    v_or_b32_e32 v14, 0x400000, v7
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; GFX9-NEXT:    v_cndmask_b32_e32 v7, v13, v14, vcc
; GFX9-NEXT:    s_and_b32 s4, s21, 0xffff0000
; GFX9-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; GFX9-NEXT:    v_mov_b32_e32 v13, 0xffff0000
; GFX9-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; GFX9-NEXT:    v_and_or_b32 v7, v6, v13, v7
; GFX9-NEXT:    v_and_or_b32 v6, v4, v13, v5
; GFX9-NEXT:    v_add_f32_e32 v4, s4, v1
; GFX9-NEXT:    v_bfe_u32 v5, v4, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v5, v5, v4
; GFX9-NEXT:    v_add_u32_e32 v5, 0x7fff, v5
; GFX9-NEXT:    v_or_b32_e32 v14, 0x400000, v4
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; GFX9-NEXT:    s_lshl_b32 s4, s21, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v4, v5, v14, vcc
; GFX9-NEXT:    v_add_f32_e32 v5, s4, v1
; GFX9-NEXT:    v_bfe_u32 v14, v5, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v14, v14, v5
; GFX9-NEXT:    v_add_u32_e32 v14, 0x7fff, v14
; GFX9-NEXT:    v_or_b32_e32 v15, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v5, v14, v15, vcc
; GFX9-NEXT:    s_and_b32 s4, s20, 0xffff0000
; GFX9-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; GFX9-NEXT:    v_and_or_b32 v5, v4, v13, v5
; GFX9-NEXT:    v_add_f32_e32 v4, s4, v1
; GFX9-NEXT:    v_bfe_u32 v14, v4, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v14, v14, v4
; GFX9-NEXT:    s_lshl_b32 s4, s20, 16
; GFX9-NEXT:    v_add_u32_e32 v14, 0x7fff, v14
; GFX9-NEXT:    v_or_b32_e32 v15, 0x400000, v4
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v4, v14, v15, vcc
; GFX9-NEXT:    v_bfe_u32 v14, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v14, v14, v1
; GFX9-NEXT:    v_add_u32_e32 v14, 0x7fff, v14
; GFX9-NEXT:    v_or_b32_e32 v15, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v14, v15, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX9-NEXT:    v_and_or_b32 v4, v4, v13, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v12
; GFX9-NEXT:    v_and_or_b32 v3, v3, v13, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v11
; GFX9-NEXT:    v_and_or_b32 v2, v2, v13, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v8, 16, v8
; GFX9-NEXT:    v_and_or_b32 v1, v9, v13, v1
; GFX9-NEXT:    v_and_or_b32 v0, v0, v13, v8
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB95_3:
; GFX9-NEXT:    s_branch .LBB95_2
; GFX9-NEXT:  .LBB95_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v16bf16_to_v16i16_scalar:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_mov_b32 s7, s19
; GFX11-TRUE16-NEXT:    s_mov_b32 s6, s18
; GFX11-TRUE16-NEXT:    s_mov_b32 s5, s17
; GFX11-TRUE16-NEXT:    s_mov_b32 s4, s16
; GFX11-TRUE16-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-TRUE16-NEXT:    s_mov_b32 s8, 0
; GFX11-TRUE16-NEXT:    s_cbranch_scc0 .LBB95_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-TRUE16-NEXT:    s_cbranch_vccnz .LBB95_4
; GFX11-TRUE16-NEXT:  .LBB95_2: ; %cmp.true
; GFX11-TRUE16-NEXT:    s_and_b32 s8, s0, 0xffff0000
; GFX11-TRUE16-NEXT:    s_lshl_b32 s0, s0, 16
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v0, 0x40c00000, s8
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v1, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    s_and_b32 s8, s1, 0xffff0000
; GFX11-TRUE16-NEXT:    s_lshl_b32 s0, s1, 16
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v2, 0x40c00000, s8
; GFX11-TRUE16-NEXT:    v_bfe_u32 v3, v0, 16, 1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v5, v1, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v4, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v7, 0x400000, v0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v6, v2, 16, 1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, v3, v0
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v10, v4, 16, 1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, v6, v2
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v5, v5, v1
; GFX11-TRUE16-NEXT:    s_and_b32 s0, s2, 0xffff0000
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v9, 0x400000, v2
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, 0x7fff, v6
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_dual_cndmask_b32 v0, v3, v7 :: v_dual_add_nc_u32 v5, 0x7fff, v5
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, v10, v4
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v7, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    s_lshl_b32 s0, s2, 16
; GFX11-TRUE16-NEXT:    s_and_b32 s1, s5, 0xffff0000
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v8, v5, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, 0x400000, v4
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v3
; GFX11-TRUE16-NEXT:    v_bfe_u32 v3, v7, 16, 1
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.l, v8.h
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v6, v9, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v6, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-TRUE16-NEXT:    s_and_b32 s0, s3, 0xffff0000
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, v3, v7
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v9, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    s_lshl_b32 s0, s3, 16
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v10, v2, v5, vcc_lo
; GFX11-TRUE16-NEXT:    v_bfe_u32 v2, v6, 16, 1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v3
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v4, 0x400000, v7
; GFX11-TRUE16-NEXT:    v_bfe_u32 v5, v9, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v12, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v11, v2, v6
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-TRUE16-NEXT:    s_and_b32 s0, s4, 0xffff0000
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v13, 0x400000, v9
; GFX11-TRUE16-NEXT:    v_bfe_u32 v7, v12, 16, 1
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v1.l, v10.h
; GFX11-TRUE16-NEXT:    v_dual_cndmask_b32 v2, v3, v4 :: v_dual_add_nc_u32 v3, v5, v9
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v4, 0x7fff, v11
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, 0x400000, v6
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v11, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v7, v7, v12
; GFX11-TRUE16-NEXT:    s_lshl_b32 s0, s4, 16
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v14, v4, v5, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-TRUE16-NEXT:    v_bfe_u32 v4, v11, 16, 1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v5, 0x7fff, v7
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v6, 0x400000, v12
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v7, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v3, v3, v13, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v12, v12
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v4, v4, v11
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v9, 0x40c00000, s1
; GFX11-TRUE16-NEXT:    s_lshl_b32 s0, s5, 16
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v13, 0x400000, v11
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v12, v5, v6, vcc_lo
; GFX11-TRUE16-NEXT:    v_bfe_u32 v5, v7, 16, 1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v4, 0x7fff, v4
; GFX11-TRUE16-NEXT:    v_bfe_u32 v6, v9, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v15, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v11, v11
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v5, v5, v7
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v16, 0x400000, v9
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, v6, v9
; GFX11-TRUE16-NEXT:    v_bfe_u32 v11, v15, 16, 1
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v4, v4, v13, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v5, 0x7fff, v5
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v13, 0x400000, v7
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, 0x7fff, v6
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v11, v11, v15
; GFX11-TRUE16-NEXT:    s_and_b32 s0, s6, 0xffff0000
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v3.l, v12.h
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v13, v5, v13, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v7, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    s_lshl_b32 s0, s6, 16
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.l, v14.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v4.l, v13.h
; GFX11-TRUE16-NEXT:    v_dual_cndmask_b32 v5, v6, v16 :: v_dual_add_nc_u32 v6, 0x7fff, v11
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v11, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    s_lshl_b32 s0, s7, 16
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v16, 0x400000, v15
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v17, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v15, v15
; GFX11-TRUE16-NEXT:    v_bfe_u32 v18, v11, 16, 1
; GFX11-TRUE16-NEXT:    s_and_b32 s0, s7, 0xffff0000
; GFX11-TRUE16-NEXT:    v_bfe_u32 v9, v7, 16, 1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v20, v17, 16, 1
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v15, v6, v16, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, v18, v11
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v19, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v21, 0x400000, v11
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v18, v20, v17
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v11, v11
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, 0x7fff, v6
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v9, v9, v7
; GFX11-TRUE16-NEXT:    v_bfe_u32 v16, v19, 16, 1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v18, 0x7fff, v18
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v22, 0x400000, v17
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v11, v6, v21, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v17, v17
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v9, 0x7fff, v9
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v20, 0x400000, v7
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v16, v16, v19
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v21, 0x400000, v19
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v17, v18, v22, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v5.l, v15.h
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v16, 0x7fff, v16
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v6, v9, v20, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v19, v19
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v6.l, v11.h
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v7, v16, v21, vcc_lo
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v7.l, v17.h
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB95_3:
; GFX11-TRUE16-NEXT:    s_branch .LBB95_2
; GFX11-TRUE16-NEXT:  .LBB95_4:
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v16bf16_to_v16i16_scalar:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    s_mov_b32 s7, s19
; GFX11-FAKE16-NEXT:    s_mov_b32 s6, s18
; GFX11-FAKE16-NEXT:    s_mov_b32 s5, s17
; GFX11-FAKE16-NEXT:    s_mov_b32 s4, s16
; GFX11-FAKE16-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-FAKE16-NEXT:    s_mov_b32 s8, 0
; GFX11-FAKE16-NEXT:    s_cbranch_scc0 .LBB95_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-FAKE16-NEXT:    s_cbranch_vccnz .LBB95_4
; GFX11-FAKE16-NEXT:  .LBB95_2: ; %cmp.true
; GFX11-FAKE16-NEXT:    s_and_b32 s8, s0, 0xffff0000
; GFX11-FAKE16-NEXT:    s_lshl_b32 s0, s0, 16
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v0, 0x40c00000, s8
; GFX11-FAKE16-NEXT:    s_and_b32 s8, s1, 0xffff0000
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v1, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v2, 0x40c00000, s8
; GFX11-FAKE16-NEXT:    s_lshl_b32 s0, s1, 16
; GFX11-FAKE16-NEXT:    v_bfe_u32 v3, v0, 16, 1
; GFX11-FAKE16-NEXT:    s_and_b32 s1, s2, 0xffff0000
; GFX11-FAKE16-NEXT:    v_bfe_u32 v4, v1, 16, 1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v5, v2, 16, 1
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v7, 0x40c00000, s1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, v3, v0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v8, 0x400000, v0
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v6, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, 0x400000, v7
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v5, v5, v2
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v9, 0x400000, v1
; GFX11-FAKE16-NEXT:    s_lshl_b32 s0, s2, 16
; GFX11-FAKE16-NEXT:    s_and_b32 s1, s5, 0xffff0000
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_4) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v0, v3, v8 :: v_dual_add_nc_u32 v5, 0x7fff, v5
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, 0x400000, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, v4, v1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v8, v6, 16, 1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, 0x7fff, v4
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v1, v4, v9, vcc_lo
; GFX11-FAKE16-NEXT:    v_bfe_u32 v4, v7, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, v8, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v8, 0x400000, v6
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v9, v5, v3, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, v4, v7
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v4, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    s_and_b32 s0, s3, 0xffff0000
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v2
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v5, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    v_bfe_u32 v10, v4, 16, 1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v3
; GFX11-FAKE16-NEXT:    s_lshl_b32 s0, s3, 16
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v2, v2, v8, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v6, v10, v4
; GFX11-FAKE16-NEXT:    v_bfe_u32 v12, v5, 16, 1
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v7, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v10, 0x400000, v4
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v8, v3, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v6, 0x7fff, v6
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-FAKE16-NEXT:    s_and_b32 s0, s4, 0xffff0000
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, v12, v5
; GFX11-FAKE16-NEXT:    v_bfe_u32 v12, v7, 16, 1
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v13, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    s_lshl_b32 s0, s4, 16
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v4, v6, v10, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v10, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, 0x400000, v5
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v5, v12, v7
; GFX11-FAKE16-NEXT:    v_bfe_u32 v14, v10, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, 0x400000, v7
; GFX11-FAKE16-NEXT:    s_lshl_b32 s0, s5, 16
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v3, v3, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v11, 0x40c00000, s1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v5, 0x7fff, v5
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v7, v14, v10
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v17, 0x400000, v10
; GFX11-FAKE16-NEXT:    v_bfe_u32 v15, v11, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v18, 0x400000, v11
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v12, v5, v12, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v5, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v7, 0x7fff, v7
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v14, v15, v11
; GFX11-FAKE16-NEXT:    s_and_b32 s0, s6, 0xffff0000
; GFX11-FAKE16-NEXT:    v_bfe_u32 v16, v5, 16, 1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v6, v13, 16, 1
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v10, v7, v17, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v7, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    s_lshl_b32 s0, s6, 16
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v14, 0x7fff, v14
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v11, v11
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v16, v16, v5
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v17, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    s_lshl_b32 s0, s7, 16
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v6, v6, v13
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v11, v14, v18 :: v_dual_add_nc_u32 v14, 0x7fff, v16
; GFX11-FAKE16-NEXT:    v_bfe_u32 v16, v7, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v18, 0x400000, v5
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v19, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    v_bfe_u32 v20, v17, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v16, v16, v7
; GFX11-FAKE16-NEXT:    s_and_b32 s0, s7, 0xffff0000
; GFX11-FAKE16-NEXT:    v_bfe_u32 v22, v19, 16, 1
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v21, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v5, v14, v18 :: v_dual_add_nc_u32 v14, v20, v17
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v23, 0x400000, v17
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v20, v22, v19
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v17, v17
; GFX11-FAKE16-NEXT:    v_bfe_u32 v18, v21, 16, 1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v14, 0x7fff, v14
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v24, 0x400000, v19
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v20, 0x7fff, v20
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v16, 0x7fff, v16
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v22, 0x400000, v7
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v14, v14, v23, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v19, v19
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v18, v18, v21
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v6, 0x7fff, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v15, 0x400000, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v14, 16, v14
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v19, v20, v24, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v17, 0x7fff, v18
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v18, 0x400000, v21
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v10, 16, v10
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v16, v16, v22, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v21, v21
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_and_or_b32 v5, 0xffff0000, v11, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v11, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v12, 16, v4
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v7, v17, v18, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v13, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v17, 16, v19
; GFX11-FAKE16-NEXT:    v_and_or_b32 v3, 0xffff0000, v3, v11
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v13, v6, v15, vcc_lo
; GFX11-FAKE16-NEXT:    v_and_or_b32 v6, 0xffff0000, v16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v14, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v15, 16, v1
; GFX11-FAKE16-NEXT:    v_and_or_b32 v7, 0xffff0000, v7, v17
; GFX11-FAKE16-NEXT:    v_and_or_b32 v4, 0xffff0000, v13, v10
; GFX11-FAKE16-NEXT:    v_and_or_b32 v2, 0xffff0000, v8, v12
; GFX11-FAKE16-NEXT:    v_and_or_b32 v1, 0xffff0000, v9, v14
; GFX11-FAKE16-NEXT:    v_and_or_b32 v0, 0xffff0000, v0, v15
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB95_3:
; GFX11-FAKE16-NEXT:    s_branch .LBB95_2
; GFX11-FAKE16-NEXT:  .LBB95_4:
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x bfloat> %a, splat (bfloat 0xR40C0)
  %a2 = bitcast <16 x bfloat> %a1 to <16 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <16 x bfloat> %a to <16 x i16>
  br label %end

end:
  %phi = phi <16 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x i16> %phi
}

define <32 x i8> @bitcast_v16i16_to_v32i8(<16 x i16> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v16i16_to_v32i8:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_mov_b32_e32 v35, v7
; SI-NEXT:    v_mov_b32_e32 v39, v6
; SI-NEXT:    v_mov_b32_e32 v34, v5
; SI-NEXT:    v_mov_b32_e32 v38, v4
; SI-NEXT:    v_mov_b32_e32 v33, v3
; SI-NEXT:    v_mov_b32_e32 v37, v2
; SI-NEXT:    v_mov_b32_e32 v32, v1
; SI-NEXT:    v_mov_b32_e32 v36, v0
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v35
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v39
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v34
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v38
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v33
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v37
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v32
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v36
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    v_lshlrev_b32_e32 v49, 16, v3
; SI-NEXT:    v_lshlrev_b32_e32 v48, 16, v6
; SI-NEXT:    v_lshlrev_b32_e32 v51, 16, v2
; SI-NEXT:    v_lshlrev_b32_e32 v50, 16, v14
; SI-NEXT:    v_lshlrev_b32_e32 v53, 16, v1
; SI-NEXT:    v_lshlrev_b32_e32 v52, 16, v22
; SI-NEXT:    v_lshlrev_b32_e32 v55, 16, v0
; SI-NEXT:    v_lshlrev_b32_e32 v54, 16, v30
; SI-NEXT:    ; implicit-def: $vgpr0
; SI-NEXT:    ; implicit-def: $vgpr1
; SI-NEXT:    ; implicit-def: $vgpr2
; SI-NEXT:    ; implicit-def: $vgpr3
; SI-NEXT:    ; implicit-def: $vgpr4
; SI-NEXT:    ; implicit-def: $vgpr5
; SI-NEXT:    ; implicit-def: $vgpr7
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr24
; SI-NEXT:    ; implicit-def: $vgpr25
; SI-NEXT:    ; implicit-def: $vgpr26
; SI-NEXT:    ; implicit-def: $vgpr27
; SI-NEXT:    ; implicit-def: $vgpr28
; SI-NEXT:    ; implicit-def: $vgpr29
; SI-NEXT:    ; implicit-def: $vgpr31
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB96_3
; SI-NEXT:  ; %bb.1: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB96_4
; SI-NEXT:  .LBB96_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB96_3: ; %cmp.false
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v37
; SI-NEXT:    v_or_b32_e32 v8, v5, v51
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v33
; SI-NEXT:    v_or_b32_e32 v12, v5, v50
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v38
; SI-NEXT:    v_or_b32_e32 v16, v5, v53
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v34
; SI-NEXT:    v_or_b32_e32 v20, v5, v52
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v39
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v36
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v32
; SI-NEXT:    v_or_b32_e32 v24, v5, v55
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v35
; SI-NEXT:    v_or_b32_e32 v0, v0, v49
; SI-NEXT:    v_or_b32_e32 v4, v1, v48
; SI-NEXT:    v_or_b32_e32 v28, v5, v54
; SI-NEXT:    v_alignbit_b32 v3, v4, v0, 24
; SI-NEXT:    v_alignbit_b32 v2, v4, v0, 16
; SI-NEXT:    v_alignbit_b32 v1, v4, v0, 8
; SI-NEXT:    v_alignbit_b32 v11, v12, v8, 24
; SI-NEXT:    v_alignbit_b32 v10, v12, v8, 16
; SI-NEXT:    v_alignbit_b32 v9, v12, v8, 8
; SI-NEXT:    v_alignbit_b32 v19, v20, v16, 24
; SI-NEXT:    v_alignbit_b32 v18, v20, v16, 16
; SI-NEXT:    v_alignbit_b32 v17, v20, v16, 8
; SI-NEXT:    v_alignbit_b32 v27, v28, v24, 24
; SI-NEXT:    v_alignbit_b32 v26, v28, v24, 16
; SI-NEXT:    v_alignbit_b32 v25, v28, v24, 8
; SI-NEXT:    v_lshrrev_b32_e32 v5, 8, v4
; SI-NEXT:    v_lshrrev_b32_e32 v13, 8, v12
; SI-NEXT:    v_lshrrev_b32_e32 v21, 8, v20
; SI-NEXT:    v_lshrrev_b32_e32 v29, 8, v28
; SI-NEXT:    v_bfe_u32 v7, v6, 8, 8
; SI-NEXT:    v_bfe_u32 v15, v14, 8, 8
; SI-NEXT:    v_bfe_u32 v23, v22, 8, 8
; SI-NEXT:    v_bfe_u32 v31, v30, 8, 8
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr49
; SI-NEXT:    ; implicit-def: $vgpr48
; SI-NEXT:    ; implicit-def: $vgpr51
; SI-NEXT:    ; implicit-def: $vgpr50
; SI-NEXT:    ; implicit-def: $vgpr53
; SI-NEXT:    ; implicit-def: $vgpr52
; SI-NEXT:    ; implicit-def: $vgpr55
; SI-NEXT:    ; implicit-def: $vgpr54
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB96_2
; SI-NEXT:  .LBB96_4: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v39
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_or_b32_e32 v0, v55, v0
; SI-NEXT:    v_add_i32_e32 v24, vcc, 0x30000, v0
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v35
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    s_mov_b32 s6, 0x30000
; SI-NEXT:    v_or_b32_e32 v0, v54, v0
; SI-NEXT:    v_add_i32_e32 v28, vcc, s6, v0
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v38
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_or_b32_e32 v0, v53, v0
; SI-NEXT:    v_add_i32_e32 v16, vcc, s6, v0
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v34
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_or_b32_e32 v0, v52, v0
; SI-NEXT:    v_add_i32_e32 v20, vcc, s6, v0
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v37
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_or_b32_e32 v0, v51, v0
; SI-NEXT:    v_add_i32_e32 v8, vcc, s6, v0
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v33
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_or_b32_e32 v0, v50, v0
; SI-NEXT:    v_add_i32_e32 v12, vcc, s6, v0
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v36
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v32
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_or_b32_e32 v0, v49, v0
; SI-NEXT:    v_or_b32_e32 v1, v48, v1
; SI-NEXT:    v_add_i32_e32 v0, vcc, s6, v0
; SI-NEXT:    v_add_i32_e32 v4, vcc, s6, v1
; SI-NEXT:    v_alignbit_b32 v3, v4, v0, 24
; SI-NEXT:    v_alignbit_b32 v2, v4, v0, 16
; SI-NEXT:    v_alignbit_b32 v1, v4, v0, 8
; SI-NEXT:    v_alignbit_b32 v11, v12, v8, 24
; SI-NEXT:    v_alignbit_b32 v10, v12, v8, 16
; SI-NEXT:    v_alignbit_b32 v9, v12, v8, 8
; SI-NEXT:    v_alignbit_b32 v19, v20, v16, 24
; SI-NEXT:    v_alignbit_b32 v18, v20, v16, 16
; SI-NEXT:    v_alignbit_b32 v17, v20, v16, 8
; SI-NEXT:    v_alignbit_b32 v27, v28, v24, 24
; SI-NEXT:    v_alignbit_b32 v26, v28, v24, 16
; SI-NEXT:    v_alignbit_b32 v25, v28, v24, 8
; SI-NEXT:    v_lshrrev_b32_e32 v7, 24, v4
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v4
; SI-NEXT:    v_lshrrev_b32_e32 v5, 8, v4
; SI-NEXT:    v_lshrrev_b32_e32 v15, 24, v12
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v12
; SI-NEXT:    v_lshrrev_b32_e32 v13, 8, v12
; SI-NEXT:    v_lshrrev_b32_e32 v23, 24, v20
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v20
; SI-NEXT:    v_lshrrev_b32_e32 v21, 8, v20
; SI-NEXT:    v_lshrrev_b32_e32 v31, 24, v28
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v28
; SI-NEXT:    v_lshrrev_b32_e32 v29, 8, v28
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16i16_to_v32i8:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v5
; VI-NEXT:    v_lshrrev_b32_e32 v18, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; VI-NEXT:    v_lshrrev_b32_e32 v10, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v36, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v32, 16, v0
; VI-NEXT:    ; implicit-def: $vgpr50
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr48
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr39
; VI-NEXT:    ; implicit-def: $vgpr8
; VI-NEXT:    ; implicit-def: $vgpr9
; VI-NEXT:    ; implicit-def: $vgpr35
; VI-NEXT:    ; implicit-def: $vgpr13
; VI-NEXT:    ; implicit-def: $vgpr15
; VI-NEXT:    ; implicit-def: $vgpr16
; VI-NEXT:    ; implicit-def: $vgpr17
; VI-NEXT:    ; implicit-def: $vgpr49
; VI-NEXT:    ; implicit-def: $vgpr21
; VI-NEXT:    ; implicit-def: $vgpr23
; VI-NEXT:    ; implicit-def: $vgpr24
; VI-NEXT:    ; implicit-def: $vgpr25
; VI-NEXT:    ; implicit-def: $vgpr51
; VI-NEXT:    ; implicit-def: $vgpr29
; VI-NEXT:    ; implicit-def: $vgpr31
; VI-NEXT:    ; implicit-def: $vgpr33
; VI-NEXT:    ; implicit-def: $vgpr11
; VI-NEXT:    ; implicit-def: $vgpr19
; VI-NEXT:    ; implicit-def: $vgpr27
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB96_2
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; VI-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; VI-NEXT:    v_lshrrev_b32_e32 v25, 8, v6
; VI-NEXT:    v_lshrrev_b32_e32 v23, 24, v5
; VI-NEXT:    v_lshrrev_b32_e32 v21, 8, v5
; VI-NEXT:    v_lshrrev_b32_e32 v17, 8, v4
; VI-NEXT:    v_lshrrev_b32_e32 v15, 24, v3
; VI-NEXT:    v_lshrrev_b32_e32 v13, 8, v3
; VI-NEXT:    v_lshrrev_b32_e32 v9, 8, v2
; VI-NEXT:    v_lshrrev_b32_e32 v39, 24, v1
; VI-NEXT:    v_lshrrev_b32_e32 v37, 8, v1
; VI-NEXT:    v_lshrrev_b32_e32 v38, 8, v0
; VI-NEXT:    v_lshrrev_b64 v[27:28], 24, v[6:7]
; VI-NEXT:    v_lshrrev_b64 v[19:20], 24, v[4:5]
; VI-NEXT:    v_lshrrev_b64 v[11:12], 24, v[2:3]
; VI-NEXT:    v_lshrrev_b64 v[33:34], 24, v[0:1]
; VI-NEXT:    v_mov_b32_e32 v50, v0
; VI-NEXT:    v_mov_b32_e32 v48, v1
; VI-NEXT:    v_mov_b32_e32 v8, v2
; VI-NEXT:    v_mov_b32_e32 v35, v3
; VI-NEXT:    v_mov_b32_e32 v16, v4
; VI-NEXT:    v_mov_b32_e32 v49, v5
; VI-NEXT:    v_mov_b32_e32 v24, v6
; VI-NEXT:    v_mov_b32_e32 v51, v7
; VI-NEXT:    ; implicit-def: $vgpr1
; VI-NEXT:    ; implicit-def: $vgpr3
; VI-NEXT:    ; implicit-def: $vgpr5
; VI-NEXT:    ; implicit-def: $vgpr7
; VI-NEXT:  .LBB96_2: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB96_4
; VI-NEXT:  ; %bb.3: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v9, 3
; VI-NEXT:    v_add_u16_sdwa v36, v1, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_sdwa v32, v0, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_sdwa v14, v3, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_sdwa v10, v2, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_sdwa v22, v5, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_sdwa v18, v4, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_sdwa v30, v7, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_sdwa v26, v6, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v48, 3, v1
; VI-NEXT:    v_lshlrev_b32_e32 v1, 16, v36
; VI-NEXT:    v_add_u16_e32 v50, 3, v0
; VI-NEXT:    v_lshlrev_b32_e32 v0, 16, v32
; VI-NEXT:    v_add_u16_e32 v35, 3, v3
; VI-NEXT:    v_lshlrev_b32_e32 v3, 16, v14
; VI-NEXT:    v_add_u16_e32 v8, 3, v2
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v10
; VI-NEXT:    v_add_u16_e32 v49, 3, v5
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v22
; VI-NEXT:    v_add_u16_e32 v16, 3, v4
; VI-NEXT:    v_lshlrev_b32_e32 v4, 16, v18
; VI-NEXT:    v_add_u16_e32 v51, 3, v7
; VI-NEXT:    v_lshlrev_b32_e32 v7, 16, v30
; VI-NEXT:    v_add_u16_e32 v24, 3, v6
; VI-NEXT:    v_lshlrev_b32_e32 v6, 16, v26
; VI-NEXT:    v_or_b32_e32 v1, v48, v1
; VI-NEXT:    v_or_b32_e32 v0, v50, v0
; VI-NEXT:    v_or_b32_e32 v3, v35, v3
; VI-NEXT:    v_or_b32_e32 v2, v8, v2
; VI-NEXT:    v_or_b32_e32 v5, v49, v5
; VI-NEXT:    v_or_b32_e32 v4, v16, v4
; VI-NEXT:    v_or_b32_e32 v7, v51, v7
; VI-NEXT:    v_or_b32_e32 v6, v24, v6
; VI-NEXT:    v_lshrrev_b64 v[27:28], 24, v[6:7]
; VI-NEXT:    v_lshrrev_b64 v[19:20], 24, v[4:5]
; VI-NEXT:    v_lshrrev_b64 v[11:12], 24, v[2:3]
; VI-NEXT:    v_lshrrev_b64 v[33:34], 24, v[0:1]
; VI-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; VI-NEXT:    v_lshrrev_b32_e32 v25, 8, v6
; VI-NEXT:    v_lshrrev_b32_e32 v21, 8, v5
; VI-NEXT:    v_lshrrev_b32_e32 v17, 8, v4
; VI-NEXT:    v_lshrrev_b32_e32 v13, 8, v3
; VI-NEXT:    v_lshrrev_b32_e32 v9, 8, v2
; VI-NEXT:    v_lshrrev_b32_e32 v37, 8, v1
; VI-NEXT:    v_lshrrev_b32_e32 v38, 8, v0
; VI-NEXT:    v_bfe_u32 v31, v30, 8, 8
; VI-NEXT:    v_bfe_u32 v23, v22, 8, 8
; VI-NEXT:    v_bfe_u32 v15, v14, 8, 8
; VI-NEXT:    v_bfe_u32 v39, v36, 8, 8
; VI-NEXT:  .LBB96_4: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    v_mov_b32_e32 v0, v50
; VI-NEXT:    v_mov_b32_e32 v1, v38
; VI-NEXT:    v_mov_b32_e32 v2, v32
; VI-NEXT:    v_mov_b32_e32 v3, v33
; VI-NEXT:    v_mov_b32_e32 v4, v48
; VI-NEXT:    v_mov_b32_e32 v5, v37
; VI-NEXT:    v_mov_b32_e32 v6, v36
; VI-NEXT:    v_mov_b32_e32 v7, v39
; VI-NEXT:    v_mov_b32_e32 v12, v35
; VI-NEXT:    v_mov_b32_e32 v20, v49
; VI-NEXT:    v_mov_b32_e32 v28, v51
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16i16_to_v32i8:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_mov_b32_e32 v33, v5
; GFX9-NEXT:    v_mov_b32_e32 v32, v4
; GFX9-NEXT:    v_mov_b32_e32 v35, v3
; GFX9-NEXT:    v_mov_b32_e32 v34, v2
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr2
; GFX9-NEXT:    ; implicit-def: $vgpr5
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr9
; GFX9-NEXT:    ; implicit-def: $vgpr10
; GFX9-NEXT:    ; implicit-def: $vgpr13
; GFX9-NEXT:    ; implicit-def: $vgpr14
; GFX9-NEXT:    ; implicit-def: $vgpr15
; GFX9-NEXT:    ; implicit-def: $vgpr17
; GFX9-NEXT:    ; implicit-def: $vgpr18
; GFX9-NEXT:    ; implicit-def: $vgpr21
; GFX9-NEXT:    ; implicit-def: $vgpr22
; GFX9-NEXT:    ; implicit-def: $vgpr23
; GFX9-NEXT:    ; implicit-def: $vgpr25
; GFX9-NEXT:    ; implicit-def: $vgpr26
; GFX9-NEXT:    ; implicit-def: $vgpr29
; GFX9-NEXT:    ; implicit-def: $vgpr30
; GFX9-NEXT:    ; implicit-def: $vgpr31
; GFX9-NEXT:    ; implicit-def: $vgpr3
; GFX9-NEXT:    ; implicit-def: $vgpr11
; GFX9-NEXT:    ; implicit-def: $vgpr19
; GFX9-NEXT:    ; implicit-def: $vgpr27
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB96_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 8, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 24, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 8, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v18, 16, v32
; GFX9-NEXT:    v_lshrrev_b32_e32 v17, 8, v32
; GFX9-NEXT:    v_lshrrev_b32_e32 v15, 24, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v14, 16, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v13, 8, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v10, 16, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v9, 8, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 24, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 8, v0
; GFX9-NEXT:    v_lshrrev_b64 v[27:28], 24, v[6:7]
; GFX9-NEXT:    v_lshrrev_b64 v[19:20], 24, v[32:33]
; GFX9-NEXT:    v_lshrrev_b64 v[11:12], 24, v[34:35]
; GFX9-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; GFX9-NEXT:  .LBB96_2: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB96_4
; GFX9-NEXT:  ; %bb.3: ; %cmp.true
; GFX9-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v35, v35, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v34, v34, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v33, v33, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v32, v32, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_lshrrev_b64 v[27:28], 24, v[6:7]
; GFX9-NEXT:    v_lshrrev_b64 v[19:20], 24, v[32:33]
; GFX9-NEXT:    v_lshrrev_b64 v[11:12], 24, v[34:35]
; GFX9-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 8, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 24, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 8, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v18, 16, v32
; GFX9-NEXT:    v_lshrrev_b32_e32 v17, 8, v32
; GFX9-NEXT:    v_lshrrev_b32_e32 v15, 24, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v14, 16, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v13, 8, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v10, 16, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v9, 8, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 24, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 8, v0
; GFX9-NEXT:  .LBB96_4: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    v_mov_b32_e32 v4, v1
; GFX9-NEXT:    v_mov_b32_e32 v8, v34
; GFX9-NEXT:    v_mov_b32_e32 v12, v35
; GFX9-NEXT:    v_mov_b32_e32 v16, v32
; GFX9-NEXT:    v_mov_b32_e32 v20, v33
; GFX9-NEXT:    v_mov_b32_e32 v24, v6
; GFX9-NEXT:    v_mov_b32_e32 v28, v7
; GFX9-NEXT:    v_mov_b32_e32 v1, v38
; GFX9-NEXT:    v_mov_b32_e32 v6, v37
; GFX9-NEXT:    v_mov_b32_e32 v7, v36
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v16i16_to_v32i8:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v33, v7 :: v_dual_mov_b32 v32, v6
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v27, v5 :: v_dual_mov_b32 v26, v4
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v19, v3 :: v_dual_mov_b32 v18, v2
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v11, v1 :: v_dual_mov_b32 v10, v0
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr1_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr3_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr5_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr7_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr36_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr15_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr17_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr35_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr21_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr23_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr25_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr34_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr29_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr31_lo16
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB96_2
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[34:35], 24, v[32:33]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[35:36], 24, v[26:27]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v27
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v27
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v26
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v18
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[36:37], 24, v[18:19]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[10:11]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v10
; GFX11-TRUE16-NEXT:  .LBB96_2: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB96_4
; GFX11-TRUE16-NEXT:  ; %bb.3: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v33, v33, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v32, v32, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v27, v27, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v26, v26, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v19, v19, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v18, v18, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[34:35], 24, v[32:33]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[35:36], 24, v[26:27]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[36:37], 24, v[18:19]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[10:11]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v27
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v27
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v26
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v18
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v10
; GFX11-TRUE16-NEXT:  .LBB96_4: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.l, v10.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.l, v10.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v4.l, v11.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v6.l, v11.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v8.l, v18.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v10.l, v18.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v11.l, v36.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v12.l, v19.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v14.l, v19.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v16.l, v26.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v18.l, v26.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v19.l, v35.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v20.l, v27.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v22.l, v27.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v24.l, v32.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v26.l, v32.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v27.l, v34.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v28.l, v33.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v30.l, v33.h
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v16i16_to_v32i8:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v33, v7 :: v_dual_mov_b32 v32, v6
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v35, v5 :: v_dual_mov_b32 v34, v4
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v37, v3 :: v_dual_mov_b32 v36, v2
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v39, v1 :: v_dual_mov_b32 v38, v0
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v8
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr1
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr2
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr3
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr5
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr6
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr7
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr9
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr10
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr11
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr13
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr14
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr15
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr17
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr18
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr19
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr21
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr22
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr23
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr25
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr26
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr27
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr29
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr30
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr31
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB96_2
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v32
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v18, 16, v34
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v34
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v14, 16, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v10, 16, v36
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v36
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v6, 16, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v38
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[27:28], 24, v[32:33]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[19:20], 24, v[34:35]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[11:12], 24, v[36:37]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[38:39]
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v38
; GFX11-FAKE16-NEXT:  .LBB96_2: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB96_4
; GFX11-FAKE16-NEXT:  ; %bb.3: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v39, v39, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v37, v37, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v35, v35, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v33, v33, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v32, v32, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v34, v34, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v36, v36, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v38, v38, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[27:28], 24, v[32:33]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[19:20], 24, v[34:35]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[11:12], 24, v[36:37]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[38:39]
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v32
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v18, 16, v34
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v34
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v14, 16, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v10, 16, v36
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v36
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v6, 16, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v38
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v38
; GFX11-FAKE16-NEXT:  .LBB96_4: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v0, v38
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v4, v39
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v8, v36
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v12, v37
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v16, v34
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v20, v35
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v24, v32
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v28, v33
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <16 x i16> %a, splat (i16 3)
  %a2 = bitcast <16 x i16> %a1 to <32 x i8>
  br label %end

cmp.false:
  %a3 = bitcast <16 x i16> %a to <32 x i8>
  br label %end

end:
  %phi = phi <32 x i8> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x i8> %phi
}

define inreg <32 x i8> @bitcast_v16i16_to_v32i8_scalar(<16 x i16> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v16i16_to_v32i8_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_lshr_b32 s75, s23, 16
; SI-NEXT:    s_lshr_b32 s79, s22, 16
; SI-NEXT:    s_lshr_b32 s74, s21, 16
; SI-NEXT:    s_lshr_b32 s78, s20, 16
; SI-NEXT:    s_lshr_b32 s73, s19, 16
; SI-NEXT:    s_lshr_b32 s77, s18, 16
; SI-NEXT:    s_lshr_b32 s72, s17, 16
; SI-NEXT:    s_lshr_b32 s76, s16, 16
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB97_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s76, 16
; SI-NEXT:    s_or_b32 s4, s4, s5
; SI-NEXT:    s_and_b32 s5, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s6, s72, 16
; SI-NEXT:    s_or_b32 s5, s5, s6
; SI-NEXT:    s_and_b32 s6, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s77, 16
; SI-NEXT:    s_or_b32 s6, s6, s7
; SI-NEXT:    s_and_b32 s7, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s8, s73, 16
; SI-NEXT:    s_or_b32 s7, s7, s8
; SI-NEXT:    s_and_b32 s8, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s9, s78, 16
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_and_b32 s9, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s74, 16
; SI-NEXT:    s_lshr_b64 s[12:13], s[4:5], 24
; SI-NEXT:    s_or_b32 s9, s9, s10
; SI-NEXT:    s_and_b32 s10, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s11, s79, 16
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_and_b32 s11, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s13, s75, 16
; SI-NEXT:    s_lshr_b64 s[14:15], s[4:5], 16
; SI-NEXT:    s_lshr_b64 s[24:25], s[4:5], 8
; SI-NEXT:    s_lshr_b64 s[26:27], s[6:7], 24
; SI-NEXT:    s_lshr_b64 s[28:29], s[6:7], 16
; SI-NEXT:    s_lshr_b64 s[40:41], s[6:7], 8
; SI-NEXT:    s_or_b32 s11, s11, s13
; SI-NEXT:    s_lshr_b32 s13, s5, 8
; SI-NEXT:    s_lshr_b32 s25, s7, 8
; SI-NEXT:    s_lshr_b32 s29, s9, 8
; SI-NEXT:    s_lshr_b32 s88, s11, 8
; SI-NEXT:    s_bfe_u32 s15, s72, 0x80008
; SI-NEXT:    s_bfe_u32 s27, s73, 0x80008
; SI-NEXT:    s_bfe_u32 s41, s74, 0x80008
; SI-NEXT:    s_bfe_u32 s89, s75, 0x80008
; SI-NEXT:    s_lshr_b64 s[42:43], s[8:9], 24
; SI-NEXT:    s_lshr_b64 s[44:45], s[8:9], 16
; SI-NEXT:    s_lshr_b64 s[46:47], s[8:9], 8
; SI-NEXT:    s_lshr_b64 s[56:57], s[10:11], 24
; SI-NEXT:    s_lshr_b64 s[58:59], s[10:11], 16
; SI-NEXT:    s_lshr_b64 s[60:61], s[10:11], 8
; SI-NEXT:    s_cbranch_execnz .LBB97_3
; SI-NEXT:  .LBB97_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_and_b32 s4, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s79, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s23, s23, 3
; SI-NEXT:    s_add_i32 s10, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s75, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_add_i32 s11, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s78, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s21, s21, 3
; SI-NEXT:    s_add_i32 s8, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s74, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_add_i32 s9, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s77, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s19, s19, 3
; SI-NEXT:    s_add_i32 s6, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s73, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    s_add_i32 s7, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s76, 16
; SI-NEXT:    s_add_i32 s17, s17, 3
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_and_b32 s5, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s72, 16
; SI-NEXT:    s_or_b32 s5, s12, s5
; SI-NEXT:    s_add_i32 s4, s4, 0x30000
; SI-NEXT:    s_add_i32 s5, s5, 0x30000
; SI-NEXT:    s_lshr_b64 s[12:13], s[4:5], 24
; SI-NEXT:    s_lshr_b64 s[14:15], s[4:5], 16
; SI-NEXT:    s_lshr_b64 s[24:25], s[4:5], 8
; SI-NEXT:    s_lshr_b64 s[26:27], s[6:7], 24
; SI-NEXT:    s_lshr_b64 s[28:29], s[6:7], 16
; SI-NEXT:    s_lshr_b64 s[40:41], s[6:7], 8
; SI-NEXT:    s_lshr_b64 s[42:43], s[8:9], 24
; SI-NEXT:    s_lshr_b64 s[44:45], s[8:9], 16
; SI-NEXT:    s_lshr_b64 s[46:47], s[8:9], 8
; SI-NEXT:    s_lshr_b64 s[56:57], s[10:11], 24
; SI-NEXT:    s_lshr_b64 s[58:59], s[10:11], 16
; SI-NEXT:    s_lshr_b64 s[60:61], s[10:11], 8
; SI-NEXT:    s_lshr_b32 s15, s5, 24
; SI-NEXT:    s_lshr_b32 s72, s5, 16
; SI-NEXT:    s_lshr_b32 s13, s5, 8
; SI-NEXT:    s_lshr_b32 s27, s7, 24
; SI-NEXT:    s_lshr_b32 s73, s7, 16
; SI-NEXT:    s_lshr_b32 s25, s7, 8
; SI-NEXT:    s_lshr_b32 s41, s9, 24
; SI-NEXT:    s_lshr_b32 s74, s9, 16
; SI-NEXT:    s_lshr_b32 s29, s9, 8
; SI-NEXT:    s_lshr_b32 s89, s11, 24
; SI-NEXT:    s_lshr_b32 s75, s11, 16
; SI-NEXT:    s_lshr_b32 s88, s11, 8
; SI-NEXT:  .LBB97_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v0, s4
; SI-NEXT:    v_mov_b32_e32 v1, s24
; SI-NEXT:    v_mov_b32_e32 v2, s14
; SI-NEXT:    v_mov_b32_e32 v3, s12
; SI-NEXT:    v_mov_b32_e32 v4, s5
; SI-NEXT:    v_mov_b32_e32 v5, s13
; SI-NEXT:    v_mov_b32_e32 v6, s72
; SI-NEXT:    v_mov_b32_e32 v7, s15
; SI-NEXT:    v_mov_b32_e32 v8, s6
; SI-NEXT:    v_mov_b32_e32 v9, s40
; SI-NEXT:    v_mov_b32_e32 v10, s28
; SI-NEXT:    v_mov_b32_e32 v11, s26
; SI-NEXT:    v_mov_b32_e32 v12, s7
; SI-NEXT:    v_mov_b32_e32 v13, s25
; SI-NEXT:    v_mov_b32_e32 v14, s73
; SI-NEXT:    v_mov_b32_e32 v15, s27
; SI-NEXT:    v_mov_b32_e32 v16, s8
; SI-NEXT:    v_mov_b32_e32 v17, s46
; SI-NEXT:    v_mov_b32_e32 v18, s44
; SI-NEXT:    v_mov_b32_e32 v19, s42
; SI-NEXT:    v_mov_b32_e32 v20, s9
; SI-NEXT:    v_mov_b32_e32 v21, s29
; SI-NEXT:    v_mov_b32_e32 v22, s74
; SI-NEXT:    v_mov_b32_e32 v23, s41
; SI-NEXT:    v_mov_b32_e32 v24, s10
; SI-NEXT:    v_mov_b32_e32 v25, s60
; SI-NEXT:    v_mov_b32_e32 v26, s58
; SI-NEXT:    v_mov_b32_e32 v27, s56
; SI-NEXT:    v_mov_b32_e32 v28, s11
; SI-NEXT:    v_mov_b32_e32 v29, s88
; SI-NEXT:    v_mov_b32_e32 v30, s75
; SI-NEXT:    v_mov_b32_e32 v31, s89
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB97_4:
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr24
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr12
; SI-NEXT:    ; implicit-def: $sgpr13
; SI-NEXT:    ; implicit-def: $sgpr15
; SI-NEXT:    ; implicit-def: $sgpr6
; SI-NEXT:    ; implicit-def: $sgpr40
; SI-NEXT:    ; implicit-def: $sgpr28
; SI-NEXT:    ; implicit-def: $sgpr26
; SI-NEXT:    ; implicit-def: $sgpr25
; SI-NEXT:    ; implicit-def: $sgpr27
; SI-NEXT:    ; implicit-def: $sgpr8
; SI-NEXT:    ; implicit-def: $sgpr46
; SI-NEXT:    ; implicit-def: $sgpr44
; SI-NEXT:    ; implicit-def: $sgpr42
; SI-NEXT:    ; implicit-def: $sgpr29
; SI-NEXT:    ; implicit-def: $sgpr41
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr60
; SI-NEXT:    ; implicit-def: $sgpr58
; SI-NEXT:    ; implicit-def: $sgpr56
; SI-NEXT:    ; implicit-def: $sgpr88
; SI-NEXT:    ; implicit-def: $sgpr89
; SI-NEXT:    s_branch .LBB97_2
;
; VI-LABEL: bitcast_v16i16_to_v32i8_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB97_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_lshr_b32 s14, s23, 24
; VI-NEXT:    s_lshr_b32 s15, s23, 16
; VI-NEXT:    s_lshr_b32 s24, s23, 8
; VI-NEXT:    s_lshr_b32 s25, s22, 16
; VI-NEXT:    s_lshr_b32 s26, s22, 8
; VI-NEXT:    s_lshr_b32 s27, s21, 24
; VI-NEXT:    s_lshr_b32 s28, s21, 16
; VI-NEXT:    s_lshr_b32 s29, s21, 8
; VI-NEXT:    s_lshr_b32 s40, s20, 16
; VI-NEXT:    s_lshr_b32 s41, s20, 8
; VI-NEXT:    s_lshr_b32 s42, s19, 24
; VI-NEXT:    s_lshr_b32 s43, s19, 16
; VI-NEXT:    s_lshr_b32 s44, s19, 8
; VI-NEXT:    s_lshr_b32 s45, s18, 16
; VI-NEXT:    s_lshr_b32 s46, s18, 8
; VI-NEXT:    s_lshr_b32 s47, s17, 24
; VI-NEXT:    s_lshr_b32 s56, s17, 16
; VI-NEXT:    s_lshr_b32 s57, s17, 8
; VI-NEXT:    s_lshr_b32 s58, s16, 16
; VI-NEXT:    s_lshr_b32 s59, s16, 8
; VI-NEXT:    s_lshr_b64 s[4:5], s[22:23], 24
; VI-NEXT:    s_lshr_b64 s[6:7], s[20:21], 24
; VI-NEXT:    s_lshr_b64 s[8:9], s[18:19], 24
; VI-NEXT:    s_lshr_b64 s[10:11], s[16:17], 24
; VI-NEXT:    s_cbranch_execnz .LBB97_3
; VI-NEXT:  .LBB97_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s5, s17, 3
; VI-NEXT:    s_and_b32 s4, s17, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s16, 3
; VI-NEXT:    s_add_i32 s17, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s16, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s19, 3
; VI-NEXT:    s_add_i32 s16, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s19, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s18, 3
; VI-NEXT:    s_add_i32 s19, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s18, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s21, 3
; VI-NEXT:    s_add_i32 s18, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s21, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s20, 3
; VI-NEXT:    s_add_i32 s21, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s20, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s23, 3
; VI-NEXT:    s_add_i32 s20, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s23, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s5, s22, 3
; VI-NEXT:    s_add_i32 s23, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s22, 0xffff0000
; VI-NEXT:    s_and_b32 s5, s5, 0xffff
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_add_i32 s22, s4, 0x30000
; VI-NEXT:    s_lshr_b64 s[4:5], s[22:23], 24
; VI-NEXT:    s_lshr_b64 s[6:7], s[20:21], 24
; VI-NEXT:    s_lshr_b64 s[8:9], s[18:19], 24
; VI-NEXT:    s_lshr_b64 s[10:11], s[16:17], 24
; VI-NEXT:    s_lshr_b32 s14, s23, 24
; VI-NEXT:    s_lshr_b32 s15, s23, 16
; VI-NEXT:    s_lshr_b32 s24, s23, 8
; VI-NEXT:    s_lshr_b32 s25, s22, 16
; VI-NEXT:    s_lshr_b32 s26, s22, 8
; VI-NEXT:    s_lshr_b32 s27, s21, 24
; VI-NEXT:    s_lshr_b32 s28, s21, 16
; VI-NEXT:    s_lshr_b32 s29, s21, 8
; VI-NEXT:    s_lshr_b32 s40, s20, 16
; VI-NEXT:    s_lshr_b32 s41, s20, 8
; VI-NEXT:    s_lshr_b32 s42, s19, 24
; VI-NEXT:    s_lshr_b32 s43, s19, 16
; VI-NEXT:    s_lshr_b32 s44, s19, 8
; VI-NEXT:    s_lshr_b32 s45, s18, 16
; VI-NEXT:    s_lshr_b32 s46, s18, 8
; VI-NEXT:    s_lshr_b32 s47, s17, 24
; VI-NEXT:    s_lshr_b32 s56, s17, 16
; VI-NEXT:    s_lshr_b32 s57, s17, 8
; VI-NEXT:    s_lshr_b32 s58, s16, 16
; VI-NEXT:    s_lshr_b32 s59, s16, 8
; VI-NEXT:  .LBB97_3: ; %end
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s59
; VI-NEXT:    v_mov_b32_e32 v2, s58
; VI-NEXT:    v_mov_b32_e32 v3, s10
; VI-NEXT:    v_mov_b32_e32 v4, s17
; VI-NEXT:    v_mov_b32_e32 v5, s57
; VI-NEXT:    v_mov_b32_e32 v6, s56
; VI-NEXT:    v_mov_b32_e32 v7, s47
; VI-NEXT:    v_mov_b32_e32 v8, s18
; VI-NEXT:    v_mov_b32_e32 v9, s46
; VI-NEXT:    v_mov_b32_e32 v10, s45
; VI-NEXT:    v_mov_b32_e32 v11, s8
; VI-NEXT:    v_mov_b32_e32 v12, s19
; VI-NEXT:    v_mov_b32_e32 v13, s44
; VI-NEXT:    v_mov_b32_e32 v14, s43
; VI-NEXT:    v_mov_b32_e32 v15, s42
; VI-NEXT:    v_mov_b32_e32 v16, s20
; VI-NEXT:    v_mov_b32_e32 v17, s41
; VI-NEXT:    v_mov_b32_e32 v18, s40
; VI-NEXT:    v_mov_b32_e32 v19, s6
; VI-NEXT:    v_mov_b32_e32 v20, s21
; VI-NEXT:    v_mov_b32_e32 v21, s29
; VI-NEXT:    v_mov_b32_e32 v22, s28
; VI-NEXT:    v_mov_b32_e32 v23, s27
; VI-NEXT:    v_mov_b32_e32 v24, s22
; VI-NEXT:    v_mov_b32_e32 v25, s26
; VI-NEXT:    v_mov_b32_e32 v26, s25
; VI-NEXT:    v_mov_b32_e32 v27, s4
; VI-NEXT:    v_mov_b32_e32 v28, s23
; VI-NEXT:    v_mov_b32_e32 v29, s24
; VI-NEXT:    v_mov_b32_e32 v30, s15
; VI-NEXT:    v_mov_b32_e32 v31, s14
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB97_4:
; VI-NEXT:    ; implicit-def: $sgpr59
; VI-NEXT:    ; implicit-def: $sgpr58
; VI-NEXT:    ; implicit-def: $sgpr10
; VI-NEXT:    ; implicit-def: $sgpr57
; VI-NEXT:    ; implicit-def: $sgpr56
; VI-NEXT:    ; implicit-def: $sgpr47
; VI-NEXT:    ; implicit-def: $sgpr46
; VI-NEXT:    ; implicit-def: $sgpr45
; VI-NEXT:    ; implicit-def: $sgpr8
; VI-NEXT:    ; implicit-def: $sgpr44
; VI-NEXT:    ; implicit-def: $sgpr43
; VI-NEXT:    ; implicit-def: $sgpr42
; VI-NEXT:    ; implicit-def: $sgpr41
; VI-NEXT:    ; implicit-def: $sgpr40
; VI-NEXT:    ; implicit-def: $sgpr6
; VI-NEXT:    ; implicit-def: $sgpr29
; VI-NEXT:    ; implicit-def: $sgpr28
; VI-NEXT:    ; implicit-def: $sgpr27
; VI-NEXT:    ; implicit-def: $sgpr26
; VI-NEXT:    ; implicit-def: $sgpr25
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr24
; VI-NEXT:    ; implicit-def: $sgpr15
; VI-NEXT:    ; implicit-def: $sgpr14
; VI-NEXT:    s_branch .LBB97_2
;
; GFX9-LABEL: bitcast_v16i16_to_v32i8_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB97_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_lshr_b32 s14, s23, 24
; GFX9-NEXT:    s_lshr_b32 s15, s23, 16
; GFX9-NEXT:    s_lshr_b32 s25, s23, 8
; GFX9-NEXT:    s_lshr_b32 s24, s22, 16
; GFX9-NEXT:    s_lshr_b32 s26, s22, 8
; GFX9-NEXT:    s_lshr_b32 s27, s21, 24
; GFX9-NEXT:    s_lshr_b32 s28, s21, 16
; GFX9-NEXT:    s_lshr_b32 s40, s21, 8
; GFX9-NEXT:    s_lshr_b32 s29, s20, 16
; GFX9-NEXT:    s_lshr_b32 s41, s20, 8
; GFX9-NEXT:    s_lshr_b32 s42, s19, 24
; GFX9-NEXT:    s_lshr_b32 s43, s19, 16
; GFX9-NEXT:    s_lshr_b32 s45, s19, 8
; GFX9-NEXT:    s_lshr_b32 s44, s18, 16
; GFX9-NEXT:    s_lshr_b32 s46, s18, 8
; GFX9-NEXT:    s_lshr_b32 s47, s17, 24
; GFX9-NEXT:    s_lshr_b32 s56, s17, 16
; GFX9-NEXT:    s_lshr_b32 s58, s17, 8
; GFX9-NEXT:    s_lshr_b32 s57, s16, 16
; GFX9-NEXT:    s_lshr_b32 s59, s16, 8
; GFX9-NEXT:    s_lshr_b64 s[10:11], s[22:23], 24
; GFX9-NEXT:    s_lshr_b64 s[8:9], s[20:21], 24
; GFX9-NEXT:    s_lshr_b64 s[6:7], s[18:19], 24
; GFX9-NEXT:    s_lshr_b64 s[4:5], s[16:17], 24
; GFX9-NEXT:    s_cbranch_execnz .LBB97_4
; GFX9-NEXT:  .LBB97_2: ; %cmp.true
; GFX9-NEXT:    v_pk_add_u16 v1, s17, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v0, s16, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v9, s19, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v8, s18, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v17, s21, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v16, s20, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v25, s23, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v24, s22, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_lshrrev_b64 v[27:28], 24, v[24:25]
; GFX9-NEXT:    v_lshrrev_b64 v[19:20], 24, v[16:17]
; GFX9-NEXT:    v_lshrrev_b64 v[11:12], 24, v[8:9]
; GFX9-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 24, v25
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v25
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 8, v25
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v24
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 8, v24
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 24, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 8, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v18, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 8, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v15, 24, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v14, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v13, 8, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v10, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 8, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v7, 24, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v6, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 8, v0
; GFX9-NEXT:    s_branch .LBB97_5
; GFX9-NEXT:  .LBB97_3:
; GFX9-NEXT:    ; implicit-def: $sgpr59
; GFX9-NEXT:    ; implicit-def: $sgpr57
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr58
; GFX9-NEXT:    ; implicit-def: $sgpr56
; GFX9-NEXT:    ; implicit-def: $sgpr47
; GFX9-NEXT:    ; implicit-def: $sgpr46
; GFX9-NEXT:    ; implicit-def: $sgpr44
; GFX9-NEXT:    ; implicit-def: $sgpr6
; GFX9-NEXT:    ; implicit-def: $sgpr45
; GFX9-NEXT:    ; implicit-def: $sgpr43
; GFX9-NEXT:    ; implicit-def: $sgpr42
; GFX9-NEXT:    ; implicit-def: $sgpr41
; GFX9-NEXT:    ; implicit-def: $sgpr29
; GFX9-NEXT:    ; implicit-def: $sgpr8
; GFX9-NEXT:    ; implicit-def: $sgpr40
; GFX9-NEXT:    ; implicit-def: $sgpr28
; GFX9-NEXT:    ; implicit-def: $sgpr27
; GFX9-NEXT:    ; implicit-def: $sgpr26
; GFX9-NEXT:    ; implicit-def: $sgpr24
; GFX9-NEXT:    ; implicit-def: $sgpr10
; GFX9-NEXT:    ; implicit-def: $sgpr25
; GFX9-NEXT:    ; implicit-def: $sgpr15
; GFX9-NEXT:    ; implicit-def: $sgpr14
; GFX9-NEXT:    s_branch .LBB97_2
; GFX9-NEXT:  .LBB97_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v8, s18
; GFX9-NEXT:    v_mov_b32_e32 v9, s19
; GFX9-NEXT:    v_mov_b32_e32 v16, s20
; GFX9-NEXT:    v_mov_b32_e32 v17, s21
; GFX9-NEXT:    v_mov_b32_e32 v24, s22
; GFX9-NEXT:    v_mov_b32_e32 v25, s23
; GFX9-NEXT:    v_mov_b32_e32 v35, s59
; GFX9-NEXT:    v_mov_b32_e32 v2, s57
; GFX9-NEXT:    v_mov_b32_e32 v5, s58
; GFX9-NEXT:    v_mov_b32_e32 v6, s56
; GFX9-NEXT:    v_mov_b32_e32 v7, s47
; GFX9-NEXT:    v_mov_b32_e32 v34, s46
; GFX9-NEXT:    v_mov_b32_e32 v10, s44
; GFX9-NEXT:    v_mov_b32_e32 v13, s45
; GFX9-NEXT:    v_mov_b32_e32 v14, s43
; GFX9-NEXT:    v_mov_b32_e32 v15, s42
; GFX9-NEXT:    v_mov_b32_e32 v33, s41
; GFX9-NEXT:    v_mov_b32_e32 v18, s29
; GFX9-NEXT:    v_mov_b32_e32 v21, s40
; GFX9-NEXT:    v_mov_b32_e32 v22, s28
; GFX9-NEXT:    v_mov_b32_e32 v23, s27
; GFX9-NEXT:    v_mov_b32_e32 v32, s26
; GFX9-NEXT:    v_mov_b32_e32 v26, s24
; GFX9-NEXT:    v_mov_b32_e32 v29, s25
; GFX9-NEXT:    v_mov_b32_e32 v30, s15
; GFX9-NEXT:    v_mov_b32_e32 v31, s14
; GFX9-NEXT:    v_mov_b32_e32 v27, s10
; GFX9-NEXT:    v_mov_b32_e32 v19, s8
; GFX9-NEXT:    v_mov_b32_e32 v11, s6
; GFX9-NEXT:    v_mov_b32_e32 v3, s4
; GFX9-NEXT:  .LBB97_5: ; %end
; GFX9-NEXT:    v_mov_b32_e32 v4, v1
; GFX9-NEXT:    v_mov_b32_e32 v12, v9
; GFX9-NEXT:    v_mov_b32_e32 v20, v17
; GFX9-NEXT:    v_mov_b32_e32 v28, v25
; GFX9-NEXT:    v_mov_b32_e32 v1, v35
; GFX9-NEXT:    v_mov_b32_e32 v9, v34
; GFX9-NEXT:    v_mov_b32_e32 v17, v33
; GFX9-NEXT:    v_mov_b32_e32 v25, v32
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v16i16_to_v32i8_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s12, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB97_3
; GFX11-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-NEXT:    s_lshr_b32 s13, s19, 24
; GFX11-NEXT:    s_lshr_b32 s14, s19, 16
; GFX11-NEXT:    s_lshr_b32 s20, s19, 8
; GFX11-NEXT:    s_lshr_b32 s15, s18, 16
; GFX11-NEXT:    s_lshr_b32 s21, s18, 8
; GFX11-NEXT:    s_lshr_b32 s22, s17, 24
; GFX11-NEXT:    s_lshr_b32 s23, s17, 16
; GFX11-NEXT:    s_lshr_b32 s25, s17, 8
; GFX11-NEXT:    s_lshr_b32 s24, s16, 16
; GFX11-NEXT:    s_lshr_b32 s26, s16, 8
; GFX11-NEXT:    s_lshr_b32 s27, s3, 24
; GFX11-NEXT:    s_lshr_b32 s28, s3, 16
; GFX11-NEXT:    s_lshr_b32 s40, s3, 8
; GFX11-NEXT:    s_lshr_b32 s29, s2, 16
; GFX11-NEXT:    s_lshr_b32 s41, s2, 8
; GFX11-NEXT:    s_lshr_b32 s42, s1, 24
; GFX11-NEXT:    s_lshr_b32 s43, s1, 16
; GFX11-NEXT:    s_lshr_b32 s45, s1, 8
; GFX11-NEXT:    s_lshr_b32 s44, s0, 16
; GFX11-NEXT:    s_lshr_b32 s46, s0, 8
; GFX11-NEXT:    s_lshr_b64 s[10:11], s[18:19], 24
; GFX11-NEXT:    s_lshr_b64 s[8:9], s[16:17], 24
; GFX11-NEXT:    s_lshr_b64 s[6:7], s[2:3], 24
; GFX11-NEXT:    s_lshr_b64 s[4:5], s[0:1], 24
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s12
; GFX11-NEXT:    s_cbranch_vccnz .LBB97_4
; GFX11-NEXT:  .LBB97_2: ; %cmp.true
; GFX11-NEXT:    v_pk_add_u16 v39, s1, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v37, s3, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v35, s17, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v33, s19, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v32, s18, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v34, s16, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v36, s2, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v38, s0, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-NEXT:    v_lshrrev_b64 v[27:28], 24, v[32:33]
; GFX11-NEXT:    v_lshrrev_b64 v[19:20], 24, v[34:35]
; GFX11-NEXT:    v_lshrrev_b64 v[11:12], 24, v[36:37]
; GFX11-NEXT:    v_lshrrev_b64 v[3:4], 24, v[38:39]
; GFX11-NEXT:    v_lshrrev_b32_e32 v30, 16, v33
; GFX11-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-NEXT:    v_lshrrev_b32_e32 v26, 16, v32
; GFX11-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-NEXT:    v_lshrrev_b32_e32 v23, 24, v35
; GFX11-NEXT:    v_lshrrev_b32_e32 v22, 16, v35
; GFX11-NEXT:    v_lshrrev_b32_e32 v21, 8, v35
; GFX11-NEXT:    v_lshrrev_b32_e32 v18, 16, v34
; GFX11-NEXT:    v_lshrrev_b32_e32 v17, 8, v34
; GFX11-NEXT:    v_lshrrev_b32_e32 v15, 24, v37
; GFX11-NEXT:    v_lshrrev_b32_e32 v14, 16, v37
; GFX11-NEXT:    v_lshrrev_b32_e32 v13, 8, v37
; GFX11-NEXT:    v_lshrrev_b32_e32 v10, 16, v36
; GFX11-NEXT:    v_lshrrev_b32_e32 v9, 8, v36
; GFX11-NEXT:    v_lshrrev_b32_e32 v7, 24, v39
; GFX11-NEXT:    v_lshrrev_b32_e32 v6, 16, v39
; GFX11-NEXT:    v_lshrrev_b32_e32 v5, 8, v39
; GFX11-NEXT:    v_lshrrev_b32_e32 v2, 16, v38
; GFX11-NEXT:    v_lshrrev_b32_e32 v1, 8, v38
; GFX11-NEXT:    s_branch .LBB97_5
; GFX11-NEXT:  .LBB97_3:
; GFX11-NEXT:    ; implicit-def: $sgpr46
; GFX11-NEXT:    ; implicit-def: $sgpr44
; GFX11-NEXT:    ; implicit-def: $sgpr4
; GFX11-NEXT:    ; implicit-def: $sgpr45
; GFX11-NEXT:    ; implicit-def: $sgpr43
; GFX11-NEXT:    ; implicit-def: $sgpr42
; GFX11-NEXT:    ; implicit-def: $sgpr41
; GFX11-NEXT:    ; implicit-def: $sgpr29
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr40
; GFX11-NEXT:    ; implicit-def: $sgpr28
; GFX11-NEXT:    ; implicit-def: $sgpr27
; GFX11-NEXT:    ; implicit-def: $sgpr26
; GFX11-NEXT:    ; implicit-def: $sgpr24
; GFX11-NEXT:    ; implicit-def: $sgpr8
; GFX11-NEXT:    ; implicit-def: $sgpr25
; GFX11-NEXT:    ; implicit-def: $sgpr23
; GFX11-NEXT:    ; implicit-def: $sgpr22
; GFX11-NEXT:    ; implicit-def: $sgpr21
; GFX11-NEXT:    ; implicit-def: $sgpr15
; GFX11-NEXT:    ; implicit-def: $sgpr10
; GFX11-NEXT:    ; implicit-def: $sgpr20
; GFX11-NEXT:    ; implicit-def: $sgpr14
; GFX11-NEXT:    ; implicit-def: $sgpr13
; GFX11-NEXT:    s_branch .LBB97_2
; GFX11-NEXT:  .LBB97_4:
; GFX11-NEXT:    v_dual_mov_b32 v38, s0 :: v_dual_mov_b32 v39, s1
; GFX11-NEXT:    v_dual_mov_b32 v36, s2 :: v_dual_mov_b32 v37, s3
; GFX11-NEXT:    v_dual_mov_b32 v34, s16 :: v_dual_mov_b32 v35, s17
; GFX11-NEXT:    v_dual_mov_b32 v32, s18 :: v_dual_mov_b32 v33, s19
; GFX11-NEXT:    v_dual_mov_b32 v1, s46 :: v_dual_mov_b32 v2, s44
; GFX11-NEXT:    v_dual_mov_b32 v5, s45 :: v_dual_mov_b32 v6, s43
; GFX11-NEXT:    v_dual_mov_b32 v7, s42 :: v_dual_mov_b32 v10, s29
; GFX11-NEXT:    v_dual_mov_b32 v9, s41 :: v_dual_mov_b32 v14, s28
; GFX11-NEXT:    v_dual_mov_b32 v13, s40 :: v_dual_mov_b32 v18, s24
; GFX11-NEXT:    v_dual_mov_b32 v15, s27 :: v_dual_mov_b32 v22, s23
; GFX11-NEXT:    v_dual_mov_b32 v17, s26 :: v_dual_mov_b32 v26, s15
; GFX11-NEXT:    v_dual_mov_b32 v21, s25 :: v_dual_mov_b32 v30, s14
; GFX11-NEXT:    v_mov_b32_e32 v23, s22
; GFX11-NEXT:    v_mov_b32_e32 v25, s21
; GFX11-NEXT:    v_mov_b32_e32 v29, s20
; GFX11-NEXT:    v_mov_b32_e32 v31, s13
; GFX11-NEXT:    v_mov_b32_e32 v27, s10
; GFX11-NEXT:    v_mov_b32_e32 v19, s8
; GFX11-NEXT:    v_mov_b32_e32 v11, s6
; GFX11-NEXT:    v_mov_b32_e32 v3, s4
; GFX11-NEXT:  .LBB97_5: ; %end
; GFX11-NEXT:    v_mov_b32_e32 v0, v38
; GFX11-NEXT:    v_mov_b32_e32 v4, v39
; GFX11-NEXT:    v_mov_b32_e32 v8, v36
; GFX11-NEXT:    v_mov_b32_e32 v12, v37
; GFX11-NEXT:    v_mov_b32_e32 v16, v34
; GFX11-NEXT:    v_mov_b32_e32 v20, v35
; GFX11-NEXT:    v_mov_b32_e32 v24, v32
; GFX11-NEXT:    v_mov_b32_e32 v28, v33
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <16 x i16> %a, splat (i16 3)
  %a2 = bitcast <16 x i16> %a1 to <32 x i8>
  br label %end

cmp.false:
  %a3 = bitcast <16 x i16> %a to <32 x i8>
  br label %end

end:
  %phi = phi <32 x i8> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x i8> %phi
}

define <16 x i16> @bitcast_v32i8_to_v16i16(<32 x i8> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v32i8_to_v16i16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    buffer_load_dword v38, off, s[0:3], s32 offset:4
; SI-NEXT:    buffer_load_dword v39, off, s[0:3], s32
; SI-NEXT:    v_lshlrev_b32_e32 v32, 8, v5
; SI-NEXT:    v_lshlrev_b32_e32 v31, 24, v7
; SI-NEXT:    v_lshlrev_b32_e32 v33, 24, v3
; SI-NEXT:    v_lshlrev_b32_e32 v35, 8, v13
; SI-NEXT:    v_lshlrev_b32_e32 v34, 24, v15
; SI-NEXT:    v_lshlrev_b32_e32 v36, 24, v11
; SI-NEXT:    v_lshlrev_b32_e32 v50, 8, v21
; SI-NEXT:    v_lshlrev_b32_e32 v37, 24, v23
; SI-NEXT:    v_lshlrev_b32_e32 v51, 24, v19
; SI-NEXT:    v_lshlrev_b32_e32 v53, 8, v29
; SI-NEXT:    v_lshlrev_b32_e32 v54, 24, v27
; SI-NEXT:    v_lshlrev_b32_e32 v19, 8, v1
; SI-NEXT:    v_lshlrev_b32_e32 v27, 8, v9
; SI-NEXT:    v_lshlrev_b32_e32 v49, 8, v17
; SI-NEXT:    v_lshlrev_b32_e32 v55, 8, v25
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr1
; SI-NEXT:    ; implicit-def: $vgpr29
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr3
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr5
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr25
; SI-NEXT:    ; implicit-def: $vgpr7
; SI-NEXT:    ; implicit-def: $vgpr48
; SI-NEXT:    s_waitcnt vmcnt(1)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v38
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_lshlrev_b32_e32 v52, 24, v39
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB98_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_and_b32_e32 v2, 0xff, v2
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v14
; SI-NEXT:    v_or_b32_e32 v0, v0, v19
; SI-NEXT:    v_or_b32_e32 v2, v33, v2
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v6
; SI-NEXT:    v_or_b32_e32 v6, v34, v5
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v10
; SI-NEXT:    v_or_b32_e32 v23, v0, v2
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v8
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v7, 0xff, v22
; SI-NEXT:    v_or_b32_e32 v0, v0, v27
; SI-NEXT:    v_or_b32_e32 v9, v36, v5
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v20
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_or_b32_e32 v5, v5, v50
; SI-NEXT:    v_or_b32_e32 v10, v37, v7
; SI-NEXT:    v_and_b32_e32 v7, 0xff, v18
; SI-NEXT:    v_or_b32_e32 v15, v0, v9
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v16
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_or_b32_e32 v0, v0, v49
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v4
; SI-NEXT:    v_or_b32_e32 v4, v31, v3
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v12
; SI-NEXT:    v_or_b32_e32 v5, v5, v10
; SI-NEXT:    v_or_b32_e32 v11, v51, v7
; SI-NEXT:    v_and_b32_e32 v7, 0xff, v28
; SI-NEXT:    v_and_b32_e32 v12, 0xff, v30
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_or_b32_e32 v1, v1, v32
; SI-NEXT:    v_or_b32_e32 v3, v3, v35
; SI-NEXT:    v_alignbit_b32 v21, v5, v11, 16
; SI-NEXT:    v_or_b32_e32 v7, v7, v53
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v12
; SI-NEXT:    v_and_b32_e32 v14, 0xff, v26
; SI-NEXT:    v_or_b32_e32 v11, v0, v11
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v24
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_or_b32_e32 v12, v52, v12
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v14
; SI-NEXT:    v_or_b32_e32 v0, v0, v55
; SI-NEXT:    v_or_b32_e32 v1, v1, v4
; SI-NEXT:    v_or_b32_e32 v3, v3, v6
; SI-NEXT:    v_or_b32_e32 v7, v7, v12
; SI-NEXT:    v_or_b32_e32 v14, v54, v14
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_alignbit_b32 v13, v1, v2, 16
; SI-NEXT:    v_alignbit_b32 v17, v3, v9, 16
; SI-NEXT:    v_alignbit_b32 v25, v7, v14, 16
; SI-NEXT:    v_or_b32_e32 v9, v0, v14
; SI-NEXT:    v_lshrrev_b32_e32 v29, 16, v4
; SI-NEXT:    v_lshrrev_b32_e32 v38, 16, v6
; SI-NEXT:    v_lshrrev_b32_e32 v39, 16, v10
; SI-NEXT:    v_lshrrev_b32_e32 v48, 16, v12
; SI-NEXT:    ; implicit-def: $vgpr0
; SI-NEXT:    ; implicit-def: $vgpr2
; SI-NEXT:    ; implicit-def: $vgpr4
; SI-NEXT:    ; implicit-def: $vgpr6
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr24
; SI-NEXT:    ; implicit-def: $vgpr26
; SI-NEXT:    ; implicit-def: $vgpr28
; SI-NEXT:    ; implicit-def: $vgpr30
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; implicit-def: $vgpr31
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr50
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr51
; SI-NEXT:    ; implicit-def: $vgpr53
; SI-NEXT:    ; implicit-def: $vgpr52
; SI-NEXT:    ; implicit-def: $vgpr54
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr27
; SI-NEXT:    ; implicit-def: $vgpr49
; SI-NEXT:    ; implicit-def: $vgpr55
; SI-NEXT:  .LBB98_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB98_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v24
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v1
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v26
; SI-NEXT:    v_or_b32_e32 v1, v55, v1
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v3
; SI-NEXT:    v_add_i32_e32 v1, vcc, 0x300, v1
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_or_b32_e32 v3, v54, v3
; SI-NEXT:    v_or_b32_e32 v1, v3, v1
; SI-NEXT:    s_mov_b32 s7, 0x3000000
; SI-NEXT:    v_add_i32_e32 v9, vcc, s7, v1
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v28
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v1
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v30
; SI-NEXT:    s_movk_i32 s6, 0x300
; SI-NEXT:    v_or_b32_e32 v1, v53, v1
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v3
; SI-NEXT:    v_add_i32_e32 v1, vcc, s6, v1
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_or_b32_e32 v3, v52, v3
; SI-NEXT:    v_or_b32_e32 v1, v3, v1
; SI-NEXT:    v_add_i32_e32 v7, vcc, s7, v1
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v16
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v1
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v18
; SI-NEXT:    v_or_b32_e32 v1, v49, v1
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v3
; SI-NEXT:    v_add_i32_e32 v1, vcc, s6, v1
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_or_b32_e32 v3, v51, v3
; SI-NEXT:    v_or_b32_e32 v1, v3, v1
; SI-NEXT:    v_add_i32_e32 v11, vcc, s7, v1
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v20
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v1
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v22
; SI-NEXT:    v_or_b32_e32 v1, v50, v1
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v3
; SI-NEXT:    v_add_i32_e32 v1, vcc, s6, v1
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_or_b32_e32 v3, v37, v3
; SI-NEXT:    v_or_b32_e32 v1, v3, v1
; SI-NEXT:    v_add_i32_e32 v5, vcc, s7, v1
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v8
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v1
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v10
; SI-NEXT:    v_or_b32_e32 v1, v27, v1
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v3
; SI-NEXT:    v_add_i32_e32 v1, vcc, s6, v1
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_or_b32_e32 v3, v36, v3
; SI-NEXT:    v_or_b32_e32 v1, v3, v1
; SI-NEXT:    v_add_i32_e32 v15, vcc, s7, v1
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v12
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v1
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v14
; SI-NEXT:    v_or_b32_e32 v1, v35, v1
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v3
; SI-NEXT:    v_add_i32_e32 v1, vcc, s6, v1
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_or_b32_e32 v3, v34, v3
; SI-NEXT:    v_or_b32_e32 v1, v3, v1
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:    v_add_i32_e32 v3, vcc, s7, v1
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v2
; SI-NEXT:    v_or_b32_e32 v0, v19, v0
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v1
; SI-NEXT:    v_add_i32_e32 v0, vcc, s6, v0
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_or_b32_e32 v1, v33, v1
; SI-NEXT:    v_or_b32_e32 v0, v1, v0
; SI-NEXT:    v_add_i32_e32 v23, vcc, s7, v0
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v4
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v6
; SI-NEXT:    v_or_b32_e32 v0, v32, v0
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v1
; SI-NEXT:    v_add_i32_e32 v0, vcc, s6, v0
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_or_b32_e32 v1, v31, v1
; SI-NEXT:    v_or_b32_e32 v0, v1, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, s7, v0
; SI-NEXT:    v_alignbit_b32 v13, v1, v23, 16
; SI-NEXT:    v_alignbit_b32 v17, v3, v15, 16
; SI-NEXT:    v_alignbit_b32 v21, v5, v11, 16
; SI-NEXT:    v_alignbit_b32 v25, v7, v9, 16
; SI-NEXT:    v_lshrrev_b32_e32 v29, 16, v1
; SI-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v39, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v48, 16, v7
; SI-NEXT:  .LBB98_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v23
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v13
; SI-NEXT:    v_or_b32_e32 v0, v0, v2
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v29
; SI-NEXT:    v_or_b32_e32 v1, v1, v2
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v15
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v17
; SI-NEXT:    v_or_b32_e32 v2, v2, v4
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v38
; SI-NEXT:    v_or_b32_e32 v3, v3, v4
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v11
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v21
; SI-NEXT:    v_or_b32_e32 v4, v4, v6
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v39
; SI-NEXT:    v_or_b32_e32 v5, v5, v6
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v9
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v25
; SI-NEXT:    v_or_b32_e32 v6, v6, v8
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v48
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v32i8_to_v16i16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_mov_b32_e32 v32, v0
; VI-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:4
; VI-NEXT:    buffer_load_ushort v39, off, s[0:3], s32
; VI-NEXT:    v_mov_b32_e32 v33, v7
; VI-NEXT:    v_mov_b32_e32 v31, v6
; VI-NEXT:    v_mov_b32_e32 v37, v5
; VI-NEXT:    v_mov_b32_e32 v36, v4
; VI-NEXT:    v_mov_b32_e32 v35, v3
; VI-NEXT:    v_mov_b32_e32 v34, v2
; VI-NEXT:    v_mov_b32_e32 v38, v1
; VI-NEXT:    s_waitcnt vmcnt(1)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v0
; VI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execnz .LBB98_3
; VI-NEXT:  ; %bb.1: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execnz .LBB98_4
; VI-NEXT:  .LBB98_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB98_3: ; %cmp.false
; VI-NEXT:    s_mov_b32 s6, 0xc0c0004
; VI-NEXT:    v_perm_b32 v1, v34, v35, s6
; VI-NEXT:    v_perm_b32 v0, v32, v38, s6
; VI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_perm_b32 v2, v31, v33, s6
; VI-NEXT:    v_or_b32_e32 v0, v0, v1
; VI-NEXT:    v_perm_b32 v1, v36, v37, s6
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_perm_b32 v3, v10, v11, s6
; VI-NEXT:    v_or_b32_e32 v1, v1, v2
; VI-NEXT:    v_perm_b32 v2, v8, v9, s6
; VI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_perm_b32 v4, v14, v15, s6
; VI-NEXT:    v_or_b32_e32 v2, v2, v3
; VI-NEXT:    v_perm_b32 v3, v12, v13, s6
; VI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_perm_b32 v5, v18, v19, s6
; VI-NEXT:    v_or_b32_e32 v3, v3, v4
; VI-NEXT:    v_perm_b32 v4, v16, v17, s6
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_perm_b32 v6, v22, v23, s6
; VI-NEXT:    v_or_b32_e32 v4, v4, v5
; VI-NEXT:    v_perm_b32 v5, v20, v21, s6
; VI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_perm_b32 v7, v26, v27, s6
; VI-NEXT:    v_or_b32_e32 v5, v5, v6
; VI-NEXT:    v_perm_b32 v6, v24, v25, s6
; VI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    v_perm_b32 v8, v30, v39, s6
; VI-NEXT:    v_or_b32_e32 v6, v6, v7
; VI-NEXT:    v_perm_b32 v7, v28, v29, s6
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; VI-NEXT:    v_or_b32_e32 v7, v7, v8
; VI-NEXT:    ; implicit-def: $vgpr32
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr34
; VI-NEXT:    ; implicit-def: $vgpr35
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr31
; VI-NEXT:    ; implicit-def: $vgpr33
; VI-NEXT:    ; implicit-def: $vgpr8
; VI-NEXT:    ; implicit-def: $vgpr9
; VI-NEXT:    ; implicit-def: $vgpr10
; VI-NEXT:    ; implicit-def: $vgpr11
; VI-NEXT:    ; implicit-def: $vgpr12
; VI-NEXT:    ; implicit-def: $vgpr13
; VI-NEXT:    ; implicit-def: $vgpr14
; VI-NEXT:    ; implicit-def: $vgpr15
; VI-NEXT:    ; implicit-def: $vgpr16
; VI-NEXT:    ; implicit-def: $vgpr17
; VI-NEXT:    ; implicit-def: $vgpr18
; VI-NEXT:    ; implicit-def: $vgpr19
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr21
; VI-NEXT:    ; implicit-def: $vgpr22
; VI-NEXT:    ; implicit-def: $vgpr23
; VI-NEXT:    ; implicit-def: $vgpr24
; VI-NEXT:    ; implicit-def: $vgpr25
; VI-NEXT:    ; implicit-def: $vgpr26
; VI-NEXT:    ; implicit-def: $vgpr27
; VI-NEXT:    ; implicit-def: $vgpr28
; VI-NEXT:    ; implicit-def: $vgpr29
; VI-NEXT:    ; implicit-def: $vgpr30
; VI-NEXT:    ; implicit-def: $vgpr39
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB98_2
; VI-NEXT:  .LBB98_4: ; %cmp.true
; VI-NEXT:    v_add_u16_e32 v0, 3, v30
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    v_lshlrev_b16_e32 v1, 8, v39
; VI-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_mov_b32_e32 v1, 0x300
; VI-NEXT:    v_add_u16_sdwa v7, v0, v1 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v0, 3, v28
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v29
; VI-NEXT:    v_or_b32_sdwa v28, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v0, 3, v26
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v27
; VI-NEXT:    v_or_b32_sdwa v0, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_sdwa v6, v0, v1 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v0, 3, v24
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v25
; VI-NEXT:    v_or_b32_sdwa v24, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v0, 3, v22
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v23
; VI-NEXT:    v_or_b32_sdwa v0, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_sdwa v5, v0, v1 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v0, 3, v20
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v21
; VI-NEXT:    v_or_b32_sdwa v20, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v0, 3, v18
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v19
; VI-NEXT:    v_or_b32_sdwa v0, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_sdwa v4, v0, v1 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v0, 3, v16
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v17
; VI-NEXT:    v_or_b32_sdwa v16, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v0, 3, v14
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v15
; VI-NEXT:    v_or_b32_sdwa v0, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_sdwa v3, v0, v1 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v0, 3, v12
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v13
; VI-NEXT:    v_or_b32_sdwa v12, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v0, 3, v10
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v11
; VI-NEXT:    v_or_b32_sdwa v0, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_sdwa v2, v0, v1 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v0, 3, v8
; VI-NEXT:    v_lshlrev_b16_e32 v8, 8, v9
; VI-NEXT:    v_or_b32_sdwa v8, v8, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v0, 3, v31
; VI-NEXT:    v_lshlrev_b16_e32 v9, 8, v33
; VI-NEXT:    v_or_b32_sdwa v0, v9, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_sdwa v9, v0, v1 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v0, 3, v36
; VI-NEXT:    v_lshlrev_b16_e32 v10, 8, v37
; VI-NEXT:    v_or_b32_sdwa v10, v10, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v0, 3, v34
; VI-NEXT:    v_lshlrev_b16_e32 v11, 8, v35
; VI-NEXT:    v_add_u16_e32 v8, 0x300, v8
; VI-NEXT:    v_or_b32_sdwa v0, v11, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_or_b32_e32 v2, v8, v2
; VI-NEXT:    v_add_u16_e32 v8, 0x300, v12
; VI-NEXT:    v_add_u16_sdwa v0, v0, v1 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v1, 3, v32
; VI-NEXT:    v_lshlrev_b16_e32 v11, 8, v38
; VI-NEXT:    v_or_b32_e32 v3, v8, v3
; VI-NEXT:    v_add_u16_e32 v8, 0x300, v16
; VI-NEXT:    v_or_b32_sdwa v1, v11, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_or_b32_e32 v4, v8, v4
; VI-NEXT:    v_add_u16_e32 v8, 0x300, v20
; VI-NEXT:    v_add_u16_e32 v1, 0x300, v1
; VI-NEXT:    v_or_b32_e32 v5, v8, v5
; VI-NEXT:    v_add_u16_e32 v8, 0x300, v24
; VI-NEXT:    v_or_b32_e32 v0, v1, v0
; VI-NEXT:    v_add_u16_e32 v1, 0x300, v10
; VI-NEXT:    v_or_b32_e32 v6, v8, v6
; VI-NEXT:    v_add_u16_e32 v8, 0x300, v28
; VI-NEXT:    v_or_b32_e32 v1, v1, v9
; VI-NEXT:    v_or_b32_e32 v7, v8, v7
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v32i8_to_v16i16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_mov_b32_e32 v37, v1
; GFX9-NEXT:    v_mov_b32_e32 v36, v0
; GFX9-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:4
; GFX9-NEXT:    buffer_load_ushort v1, off, s[0:3], s32
; GFX9-NEXT:    v_mov_b32_e32 v38, v7
; GFX9-NEXT:    v_mov_b32_e32 v31, v6
; GFX9-NEXT:    v_mov_b32_e32 v33, v5
; GFX9-NEXT:    v_mov_b32_e32 v34, v4
; GFX9-NEXT:    v_mov_b32_e32 v32, v3
; GFX9-NEXT:    v_mov_b32_e32 v35, v2
; GFX9-NEXT:    v_lshlrev_b16_e32 v39, 8, v17
; GFX9-NEXT:    v_lshlrev_b16_e32 v17, 8, v19
; GFX9-NEXT:    v_lshlrev_b16_e32 v19, 8, v23
; GFX9-NEXT:    v_lshlrev_b16_e32 v25, 8, v25
; GFX9-NEXT:    v_lshlrev_b16_e32 v23, 8, v27
; GFX9-NEXT:    s_waitcnt vmcnt(1)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v0
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    v_lshlrev_b16_e32 v27, 8, v1
; GFX9-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execnz .LBB98_3
; GFX9-NEXT:  ; %bb.1: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execnz .LBB98_4
; GFX9-NEXT:  .LBB98_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB98_3: ; %cmp.false
; GFX9-NEXT:    s_mov_b32 s6, 0xc0c0004
; GFX9-NEXT:    v_perm_b32 v0, v36, v37, s6
; GFX9-NEXT:    v_perm_b32 v1, v35, v32, s6
; GFX9-NEXT:    s_mov_b32 s7, 0x5040100
; GFX9-NEXT:    v_perm_b32 v0, v1, v0, s7
; GFX9-NEXT:    v_perm_b32 v1, v34, v33, s6
; GFX9-NEXT:    v_perm_b32 v2, v31, v38, s6
; GFX9-NEXT:    v_perm_b32 v1, v2, v1, s7
; GFX9-NEXT:    v_perm_b32 v2, v8, v9, s6
; GFX9-NEXT:    v_perm_b32 v3, v10, v11, s6
; GFX9-NEXT:    v_perm_b32 v2, v3, v2, s7
; GFX9-NEXT:    v_perm_b32 v3, v12, v13, s6
; GFX9-NEXT:    v_perm_b32 v4, v14, v15, s6
; GFX9-NEXT:    v_perm_b32 v3, v4, v3, s7
; GFX9-NEXT:    v_or_b32_sdwa v4, v16, v39 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:BYTE_0 src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v5, v18, v17 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:BYTE_0 src1_sel:DWORD
; GFX9-NEXT:    v_perm_b32 v4, v5, v4, s7
; GFX9-NEXT:    v_or_b32_sdwa v5, v22, v19 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:BYTE_0 src1_sel:DWORD
; GFX9-NEXT:    v_perm_b32 v6, v20, v21, s6
; GFX9-NEXT:    v_perm_b32 v5, v5, v6, s7
; GFX9-NEXT:    v_or_b32_sdwa v6, v24, v25 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:BYTE_0 src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v7, v26, v23 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:BYTE_0 src1_sel:DWORD
; GFX9-NEXT:    v_perm_b32 v6, v7, v6, s7
; GFX9-NEXT:    v_or_b32_sdwa v7, v30, v27 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:BYTE_0 src1_sel:DWORD
; GFX9-NEXT:    v_perm_b32 v8, v28, v29, s6
; GFX9-NEXT:    v_perm_b32 v7, v7, v8, s7
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr35
; GFX9-NEXT:    ; implicit-def: $vgpr32
; GFX9-NEXT:    ; implicit-def: $vgpr34
; GFX9-NEXT:    ; implicit-def: $vgpr33
; GFX9-NEXT:    ; implicit-def: $vgpr31
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr8
; GFX9-NEXT:    ; implicit-def: $vgpr9
; GFX9-NEXT:    ; implicit-def: $vgpr10
; GFX9-NEXT:    ; implicit-def: $vgpr11
; GFX9-NEXT:    ; implicit-def: $vgpr12
; GFX9-NEXT:    ; implicit-def: $vgpr13
; GFX9-NEXT:    ; implicit-def: $vgpr14
; GFX9-NEXT:    ; implicit-def: $vgpr15
; GFX9-NEXT:    ; implicit-def: $vgpr16
; GFX9-NEXT:    ; implicit-def: $vgpr18
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr21
; GFX9-NEXT:    ; implicit-def: $vgpr22
; GFX9-NEXT:    ; implicit-def: $vgpr24
; GFX9-NEXT:    ; implicit-def: $vgpr26
; GFX9-NEXT:    ; implicit-def: $vgpr28
; GFX9-NEXT:    ; implicit-def: $vgpr29
; GFX9-NEXT:    ; implicit-def: $vgpr30
; GFX9-NEXT:    ; implicit-def: $vgpr39
; GFX9-NEXT:    ; implicit-def: $vgpr17
; GFX9-NEXT:    ; implicit-def: $vgpr19
; GFX9-NEXT:    ; implicit-def: $vgpr25
; GFX9-NEXT:    ; implicit-def: $vgpr23
; GFX9-NEXT:    ; implicit-def: $vgpr27
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB98_2
; GFX9-NEXT:  .LBB98_4: ; %cmp.true
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v28
; GFX9-NEXT:    v_lshlrev_b16_e32 v1, 8, v29
; GFX9-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v7, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v30
; GFX9-NEXT:    v_or_b32_sdwa v0, v27, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v27, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v24
; GFX9-NEXT:    v_or_b32_sdwa v0, v25, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v6, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v26
; GFX9-NEXT:    v_or_b32_sdwa v0, v23, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v23, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v20
; GFX9-NEXT:    v_lshlrev_b16_e32 v1, 8, v21
; GFX9-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v5, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v22
; GFX9-NEXT:    v_or_b32_sdwa v0, v19, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v19, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v16
; GFX9-NEXT:    v_or_b32_sdwa v0, v39, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v4, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v18
; GFX9-NEXT:    v_or_b32_sdwa v0, v17, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v16, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v12
; GFX9-NEXT:    v_lshlrev_b16_e32 v1, 8, v13
; GFX9-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v3, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v14
; GFX9-NEXT:    v_lshlrev_b16_e32 v1, 8, v15
; GFX9-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v12, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v8
; GFX9-NEXT:    v_lshlrev_b16_e32 v1, 8, v9
; GFX9-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v2, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v10
; GFX9-NEXT:    v_lshlrev_b16_e32 v1, 8, v11
; GFX9-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v8, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v34
; GFX9-NEXT:    v_lshlrev_b16_e32 v1, 8, v33
; GFX9-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v1, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v31
; GFX9-NEXT:    v_lshlrev_b16_e32 v9, 8, v38
; GFX9-NEXT:    v_or_b32_sdwa v0, v9, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v9, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v36
; GFX9-NEXT:    v_lshlrev_b16_e32 v10, 8, v37
; GFX9-NEXT:    v_or_b32_sdwa v0, v10, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v10, 3, v35
; GFX9-NEXT:    v_lshlrev_b16_e32 v11, 8, v32
; GFX9-NEXT:    v_or_b32_sdwa v10, v11, v10 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v0, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v10, 0x300, v10
; GFX9-NEXT:    s_mov_b32 s6, 0x5040100
; GFX9-NEXT:    v_perm_b32 v0, v10, v0, s6
; GFX9-NEXT:    v_perm_b32 v1, v9, v1, s6
; GFX9-NEXT:    v_perm_b32 v2, v8, v2, s6
; GFX9-NEXT:    v_perm_b32 v3, v12, v3, s6
; GFX9-NEXT:    v_perm_b32 v4, v16, v4, s6
; GFX9-NEXT:    v_perm_b32 v5, v19, v5, s6
; GFX9-NEXT:    v_perm_b32 v6, v23, v6, s6
; GFX9-NEXT:    v_perm_b32 v7, v27, v7, s6
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v32i8_to_v16i16:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_clause 0x1
; GFX11-TRUE16-NEXT:    scratch_load_b32 v37, off, s32 offset:4
; GFX11-TRUE16-NEXT:    scratch_load_d16_hi_b16 v31, off, s32
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v27.h, v27.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v25.h, v25.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v23.h, v23.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v19.h, v19.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v17.h, v17.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v34.l, v29.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v36.l, v28.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v33.l, v20.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v17.l, v15.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v28.l, v14.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v25.l, v12.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v15.l, v11.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v27.l, v10.l
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v31.l, v9.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v35.l, v8.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v14.l, v7.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v29.l, v6.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v11.l, v5.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v19.l, v4.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v23.l, v3.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v32.l, v2.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v12.l, v1.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v20.l, v0.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v9.l, 8, v17.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v8.l, 8, v19.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v8.h, 8, v23.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v10.l, 8, v25.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v9.h, 8, v27.h
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v10.h, 8, v31.h
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v37
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB98_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB98_4
; GFX11-TRUE16-NEXT:  .LBB98_2: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB98_3: ; %cmp.false
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr29_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr14_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v3, v29, v14, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr28_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr17_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v6, v28, v17, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr19_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr11_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, v19, v11, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr32_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr23_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v2, v32, v23, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr27_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr15_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v4, v27, v15, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v1.h, v3.l
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr25_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v3, v25, v13, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_and_b16 v5.l, 0xff, v22.l
; GFX11-TRUE16-NEXT:    v_and_b16 v4.h, 0xff, v18.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v3.h, v6.l
; GFX11-TRUE16-NEXT:    v_and_b16 v6.l, 0xff, v30.l
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr12_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v0, v20, v12, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.h, v2.l
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr35_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr31_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v2, v35, v31, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_or_b16 v6.h, v5.l, v8.h
; GFX11-TRUE16-NEXT:    v_and_b16 v7.l, 0xff, v24.l
; GFX11-TRUE16-NEXT:    v_and_b16 v7.h, 0xff, v26.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.h, v4.l
; GFX11-TRUE16-NEXT:    v_and_b16 v4.l, 0xff, v16.l
; GFX11-TRUE16-NEXT:    v_or_b16 v4.h, v4.h, v8.l
; GFX11-TRUE16-NEXT:    v_or_b16 v8.l, v6.l, v10.h
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr33_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr21_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, v33, v21, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v5.h, v6.h
; GFX11-TRUE16-NEXT:    v_or_b16 v6.l, v7.l, v10.l
; GFX11-TRUE16-NEXT:    v_or_b16 v6.h, v7.h, v9.h
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr36_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr34_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v7, v36, v34, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_or_b16 v4.l, v4.l, v9.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v7.h, v8.l
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr12_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr32_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr23_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr19_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr11_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr29_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr14_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr35_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr31_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr27_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr15_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr25_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr28_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr17_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr16_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr18_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr33_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr21_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr22_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr24_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr26_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr36_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr34_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr30_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr8_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr8_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr10_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr10_hi16
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB98_2
; GFX11-TRUE16-NEXT:  .LBB98_4: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.l, v36.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.h, v30.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.h, v24.l, 3
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v1.l, 8, v34.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.l, v26.l, 3
; GFX11-TRUE16-NEXT:    v_and_b16 v0.l, 0xff, v0.l
; GFX11-TRUE16-NEXT:    v_and_b16 v0.h, 0xff, v0.h
; GFX11-TRUE16-NEXT:    v_and_b16 v1.h, 0xff, v1.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.h, v33.l, 3
; GFX11-TRUE16-NEXT:    v_and_b16 v2.l, 0xff, v2.l
; GFX11-TRUE16-NEXT:    v_or_b16 v0.l, v1.l, v0.l
; GFX11-TRUE16-NEXT:    v_or_b16 v0.h, v10.h, v0.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.l, v22.l, 3
; GFX11-TRUE16-NEXT:    v_or_b16 v1.h, v10.l, v1.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v3.l, 8, v17.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v7.l, 0x300, v0.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v7.h, 0x300, v0.h
; GFX11-TRUE16-NEXT:    v_and_b16 v0.l, 0xff, v2.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v0.h, 8, v21.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v6.l, 0x300, v1.h
; GFX11-TRUE16-NEXT:    v_and_b16 v1.l, 0xff, v1.l
; GFX11-TRUE16-NEXT:    v_or_b16 v1.h, v9.h, v2.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.l, v16.l, 3
; GFX11-TRUE16-NEXT:    v_or_b16 v0.l, v0.h, v0.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.h, v18.l, 3
; GFX11-TRUE16-NEXT:    v_or_b16 v1.l, v8.h, v1.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v6.h, 0x300, v1.h
; GFX11-TRUE16-NEXT:    v_and_b16 v1.h, 0xff, v2.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v5.l, 0x300, v0.l
; GFX11-TRUE16-NEXT:    v_and_b16 v0.l, 0xff, v0.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v5.h, 0x300, v1.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.h, v25.l, 3
; GFX11-TRUE16-NEXT:    v_or_b16 v1.l, v9.l, v1.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.h, v28.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.l, v35.l, 3
; GFX11-TRUE16-NEXT:    v_or_b16 v0.l, v8.l, v0.l
; GFX11-TRUE16-NEXT:    v_and_b16 v0.h, 0xff, v0.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v2.h, 8, v13.l
; GFX11-TRUE16-NEXT:    v_and_b16 v1.h, 0xff, v1.h
; GFX11-TRUE16-NEXT:    v_and_b16 v2.l, 0xff, v2.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v3.h, 8, v31.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v4.l, 0x300, v1.l
; GFX11-TRUE16-NEXT:    v_or_b16 v0.h, v2.h, v0.h
; GFX11-TRUE16-NEXT:    v_or_b16 v1.l, v3.l, v1.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v4.h, 0x300, v0.l
; GFX11-TRUE16-NEXT:    v_or_b16 v0.l, v3.h, v2.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.h, v27.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v3.l, 0x300, v0.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.h, v19.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.h, v20.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.l, 0x300, v0.l
; GFX11-TRUE16-NEXT:    v_and_b16 v0.l, 0xff, v1.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.h, v29.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v8.h, v32.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v3.h, 0x300, v1.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v1.l, 8, v15.l
; GFX11-TRUE16-NEXT:    v_and_b16 v0.h, 0xff, v0.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v8.l, 8, v11.l
; GFX11-TRUE16-NEXT:    v_and_b16 v1.h, 0xff, v1.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v9.l, 8, v14.l
; GFX11-TRUE16-NEXT:    v_and_b16 v2.h, 0xff, v2.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v9.h, 8, v12.l
; GFX11-TRUE16-NEXT:    v_and_b16 v8.h, 0xff, v8.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v10.l, 8, v23.l
; GFX11-TRUE16-NEXT:    v_or_b16 v0.l, v1.l, v0.l
; GFX11-TRUE16-NEXT:    v_or_b16 v0.h, v8.l, v0.h
; GFX11-TRUE16-NEXT:    v_or_b16 v1.h, v9.l, v1.h
; GFX11-TRUE16-NEXT:    v_or_b16 v8.l, v9.h, v2.h
; GFX11-TRUE16-NEXT:    v_or_b16 v8.h, v10.l, v8.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.h, 0x300, v0.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.l, 0x300, v0.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.h, 0x300, v1.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.l, 0x300, v8.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.h, 0x300, v8.h
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v32i8_to_v16i16:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v37, v1 :: v_dual_mov_b32 v34, v0
; GFX11-FAKE16-NEXT:    s_clause 0x1
; GFX11-FAKE16-NEXT:    scratch_load_b32 v0, off, s32 offset:4
; GFX11-FAKE16-NEXT:    scratch_load_u16 v1, off, s32
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v33, v7 :: v_dual_mov_b32 v38, v4
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v31, v6 :: v_dual_mov_b32 v36, v3
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v35, v5 :: v_dual_mov_b32 v32, v2
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v39, 8, v17
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v17, 8, v19
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v19, 8, v23
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v25, 8, v25
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v23, 8, v27
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(1)
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v0
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v27, 8, v1
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB98_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB98_4
; GFX11-FAKE16-NEXT:  .LBB98_2: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB98_3: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v34, v37, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v32, v36, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v38, v35, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v31, v33, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v8, v9, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v10, v11, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v1, v0, 0x5040100
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v8, 0xff, v24
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v3, v2, 0x5040100
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xff, v16
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v5, v4, 0x5040100
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xff, v18
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v9, 0xff, v26
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v10, 0xff, v30
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v7, v3, v39
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xff, v22
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v12, v13, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v14, v15, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, v4, v17
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, v20, v21, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, v3, v19
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v8, v8, v25
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v9, v9, v23
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v10, v10, v27
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, v28, v29, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v6, v5, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v4, v7, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v11, v12, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v9, v8, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v10, v13, 0x5040100
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr34
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr37
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr32
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr36
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr38
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr35
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr31
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr33
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr8
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr9
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr10
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr11
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr12
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr13
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr14
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr15
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr16
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr18
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr21
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr22
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr24
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr26
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr28
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr29
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr30
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr39
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr17
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr19
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr25
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr23
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr27
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB98_2
; GFX11-FAKE16-NEXT:  .LBB98_4: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v0, v28, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v1, v30, 3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v2, 8, v29
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v4, v26, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v5, v20, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xff, v0
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v1, 0xff, v1
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, v24, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v6, v22, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xff, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v2, v0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v1, v27, v1
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v2, v16, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xff, v3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, v23, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v7, 0x300, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v16, 0x300, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xff, v5
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v1, 8, v21
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xff, v2
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xff, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v25, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v9, 8, v9
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v1, v0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, v39, v2
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v1, v19, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v19, 0x300, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v6, 0x300, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v5, 0x300, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v0, v12, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v4, 0x300, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v2, v8, 3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v3, 8, v13
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v8, v14, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xff, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v12, 0x300, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xff, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v1, v18, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v13, v34, 3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v3, v0
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xff, v8
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v8, 8, v15
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, v9, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v9, v10, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v1, 0xff, v1
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v10, 0x300, v0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v8, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, v38, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v8, 0xff, v9
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v9, v31, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v14, v32, 3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v1, v17, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xff, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v15, 8, v35
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v9, 0xff, v9
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v13, 0xff, v13
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v17, 8, v37
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v14, 0xff, v14
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v18, 8, v36
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v20, 8, v33
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v11, 8, v11
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v15, v3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v13, v17, v13
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v14, v18, v14
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v9, v20, v9
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v8, v11, v8
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v2, 0x300, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, 0x300, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v11, 0x300, v13
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v13, 0x300, v14
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v9, 0x300, v9
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v8, 0x300, v8
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v14, 0x300, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v15, 0x300, v1
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v13, v11, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v9, v3, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v8, v2, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v14, v10, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v15, v4, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v12, v5, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v19, v6, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v16, v7, 0x5040100
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <32 x i8> %a, splat (i8 3)
  %a2 = bitcast <32 x i8> %a1 to <16 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <32 x i8> %a to <16 x i16>
  br label %end

end:
  %phi = phi <16 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x i16> %phi
}

define inreg <16 x i16> @bitcast_v32i8_to_v16i16_scalar(<32 x i8> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v32i8_to_v16i16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_readfirstlane_b32 s4, v18
; SI-NEXT:    v_readfirstlane_b32 s62, v17
; SI-NEXT:    v_readfirstlane_b32 s63, v16
; SI-NEXT:    v_readfirstlane_b32 s73, v15
; SI-NEXT:    v_readfirstlane_b32 s75, v14
; SI-NEXT:    v_readfirstlane_b32 s76, v13
; SI-NEXT:    v_readfirstlane_b32 s77, v12
; SI-NEXT:    v_readfirstlane_b32 s78, v11
; SI-NEXT:    v_readfirstlane_b32 s79, v10
; SI-NEXT:    v_readfirstlane_b32 s56, v9
; SI-NEXT:    v_readfirstlane_b32 s57, v8
; SI-NEXT:    v_readfirstlane_b32 s58, v7
; SI-NEXT:    v_readfirstlane_b32 s59, v6
; SI-NEXT:    v_readfirstlane_b32 s60, v5
; SI-NEXT:    v_readfirstlane_b32 s61, v4
; SI-NEXT:    v_readfirstlane_b32 s72, v3
; SI-NEXT:    v_readfirstlane_b32 s74, v2
; SI-NEXT:    v_readfirstlane_b32 s46, v1
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    v_readfirstlane_b32 s47, v0
; SI-NEXT:    s_cbranch_scc0 .LBB99_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s8, s20, 0xff
; SI-NEXT:    s_lshl_b32 s9, s21, 8
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_and_b32 s9, s22, 0xff
; SI-NEXT:    s_and_b32 s4, s16, 0xff
; SI-NEXT:    s_lshl_b32 s5, s17, 8
; SI-NEXT:    s_lshl_b32 s9, s9, 16
; SI-NEXT:    s_lshl_b32 s11, s23, 24
; SI-NEXT:    s_or_b32 s4, s4, s5
; SI-NEXT:    s_and_b32 s5, s18, 0xff
; SI-NEXT:    s_and_b32 s8, s8, 0xffff
; SI-NEXT:    s_or_b32 s44, s11, s9
; SI-NEXT:    s_lshl_b32 s5, s5, 16
; SI-NEXT:    s_lshl_b32 s6, s19, 24
; SI-NEXT:    s_or_b32 s13, s8, s44
; SI-NEXT:    s_and_b32 s8, s28, 0xff
; SI-NEXT:    s_lshl_b32 s9, s29, 8
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_or_b32 s12, s6, s5
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_and_b32 s9, s47, 0xff
; SI-NEXT:    s_or_b32 s10, s4, s12
; SI-NEXT:    s_and_b32 s4, s24, 0xff
; SI-NEXT:    s_lshl_b32 s5, s25, 8
; SI-NEXT:    s_lshl_b32 s9, s9, 16
; SI-NEXT:    s_lshl_b32 s11, s46, 24
; SI-NEXT:    s_or_b32 s4, s4, s5
; SI-NEXT:    s_and_b32 s5, s26, 0xff
; SI-NEXT:    s_and_b32 s8, s8, 0xffff
; SI-NEXT:    s_or_b32 s45, s11, s9
; SI-NEXT:    s_lshl_b32 s5, s5, 16
; SI-NEXT:    s_lshl_b32 s6, s27, 24
; SI-NEXT:    s_or_b32 s15, s8, s45
; SI-NEXT:    s_and_b32 s8, s59, 0xff
; SI-NEXT:    s_lshl_b32 s9, s58, 8
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_or_b32 s14, s6, s5
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_and_b32 s9, s57, 0xff
; SI-NEXT:    s_or_b32 s6, s4, s14
; SI-NEXT:    s_and_b32 s4, s74, 0xff
; SI-NEXT:    s_lshl_b32 s5, s72, 8
; SI-NEXT:    s_lshl_b32 s9, s9, 16
; SI-NEXT:    s_lshl_b32 s11, s56, 24
; SI-NEXT:    s_or_b32 s4, s4, s5
; SI-NEXT:    s_and_b32 s5, s61, 0xff
; SI-NEXT:    s_and_b32 s8, s8, 0xffff
; SI-NEXT:    s_or_b32 s88, s11, s9
; SI-NEXT:    s_lshl_b32 s5, s5, 16
; SI-NEXT:    s_lshl_b32 s7, s60, 24
; SI-NEXT:    s_or_b32 s41, s8, s88
; SI-NEXT:    s_and_b32 s8, s75, 0xff
; SI-NEXT:    s_lshl_b32 s9, s73, 8
; SI-NEXT:    s_or_b32 s40, s7, s5
; SI-NEXT:    s_and_b32 s5, s79, 0xff
; SI-NEXT:    s_lshl_b32 s7, s78, 8
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_and_b32 s9, s63, 0xff
; SI-NEXT:    s_or_b32 s5, s5, s7
; SI-NEXT:    s_and_b32 s7, s77, 0xff
; SI-NEXT:    s_lshl_b32 s9, s9, 16
; SI-NEXT:    s_lshl_b32 s11, s62, 24
; SI-NEXT:    s_lshl_b32 s7, s7, 16
; SI-NEXT:    s_or_b32 s89, s11, s9
; SI-NEXT:    s_lshl_b32 s9, s76, 24
; SI-NEXT:    s_or_b32 s42, s9, s7
; SI-NEXT:    s_and_b32 s7, s8, 0xffff
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_and_b32 s5, s5, 0xffff
; SI-NEXT:    s_or_b32 s43, s7, s89
; SI-NEXT:    s_or_b32 s4, s4, s40
; SI-NEXT:    s_or_b32 s8, s5, s42
; SI-NEXT:    s_mov_b32 s11, s13
; SI-NEXT:    s_lshr_b64 s[12:13], s[12:13], 16
; SI-NEXT:    s_mov_b32 s7, s15
; SI-NEXT:    s_lshr_b64 s[14:15], s[14:15], 16
; SI-NEXT:    s_mov_b32 s5, s41
; SI-NEXT:    s_lshr_b64 s[40:41], s[40:41], 16
; SI-NEXT:    s_mov_b32 s9, s43
; SI-NEXT:    s_lshr_b64 s[42:43], s[42:43], 16
; SI-NEXT:    s_lshr_b32 s15, s44, 16
; SI-NEXT:    s_lshr_b32 s41, s45, 16
; SI-NEXT:    s_lshr_b32 s43, s88, 16
; SI-NEXT:    s_lshr_b32 s13, s89, 16
; SI-NEXT:    s_cbranch_execnz .LBB99_3
; SI-NEXT:  .LBB99_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s79, s79, 3
; SI-NEXT:    s_and_b32 s4, s79, 0xff
; SI-NEXT:    s_lshl_b32 s5, s78, 8
; SI-NEXT:    s_add_i32 s77, s77, 3
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_and_b32 s6, s77, 0xff
; SI-NEXT:    s_addk_i32 s4, 0x300
; SI-NEXT:    s_lshl_b32 s5, s76, 24
; SI-NEXT:    s_lshl_b32 s6, s6, 16
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_or_b32 s5, s5, s6
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s75, s75, 3
; SI-NEXT:    s_add_i32 s8, s4, 0x3000000
; SI-NEXT:    s_and_b32 s4, s75, 0xff
; SI-NEXT:    s_lshl_b32 s5, s73, 8
; SI-NEXT:    s_add_i32 s63, s63, 3
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_and_b32 s6, s63, 0xff
; SI-NEXT:    s_addk_i32 s4, 0x300
; SI-NEXT:    s_lshl_b32 s5, s62, 24
; SI-NEXT:    s_lshl_b32 s6, s6, 16
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_or_b32 s5, s5, s6
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s74, s74, 3
; SI-NEXT:    s_add_i32 s9, s4, 0x3000000
; SI-NEXT:    s_and_b32 s4, s74, 0xff
; SI-NEXT:    s_lshl_b32 s5, s72, 8
; SI-NEXT:    s_add_i32 s61, s61, 3
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_and_b32 s6, s61, 0xff
; SI-NEXT:    s_addk_i32 s4, 0x300
; SI-NEXT:    s_lshl_b32 s5, s60, 24
; SI-NEXT:    s_lshl_b32 s6, s6, 16
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_or_b32 s5, s5, s6
; SI-NEXT:    s_add_i32 s59, s59, 3
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_and_b32 s5, s59, 0xff
; SI-NEXT:    s_lshl_b32 s6, s58, 8
; SI-NEXT:    s_add_i32 s57, s57, 3
; SI-NEXT:    s_or_b32 s5, s6, s5
; SI-NEXT:    s_and_b32 s7, s57, 0xff
; SI-NEXT:    s_addk_i32 s5, 0x300
; SI-NEXT:    s_lshl_b32 s6, s56, 24
; SI-NEXT:    s_lshl_b32 s7, s7, 16
; SI-NEXT:    s_and_b32 s5, s5, 0xffff
; SI-NEXT:    s_or_b32 s6, s6, s7
; SI-NEXT:    s_add_i32 s24, s24, 3
; SI-NEXT:    s_or_b32 s5, s6, s5
; SI-NEXT:    s_and_b32 s6, s24, 0xff
; SI-NEXT:    s_lshl_b32 s7, s25, 8
; SI-NEXT:    s_add_i32 s26, s26, 3
; SI-NEXT:    s_or_b32 s6, s7, s6
; SI-NEXT:    s_and_b32 s10, s26, 0xff
; SI-NEXT:    s_addk_i32 s6, 0x300
; SI-NEXT:    s_lshl_b32 s7, s27, 24
; SI-NEXT:    s_lshl_b32 s10, s10, 16
; SI-NEXT:    s_and_b32 s6, s6, 0xffff
; SI-NEXT:    s_or_b32 s7, s7, s10
; SI-NEXT:    s_add_i32 s28, s28, 3
; SI-NEXT:    s_or_b32 s6, s7, s6
; SI-NEXT:    s_and_b32 s7, s28, 0xff
; SI-NEXT:    s_lshl_b32 s10, s29, 8
; SI-NEXT:    s_add_i32 s47, s47, 3
; SI-NEXT:    s_or_b32 s7, s10, s7
; SI-NEXT:    s_and_b32 s11, s47, 0xff
; SI-NEXT:    s_addk_i32 s7, 0x300
; SI-NEXT:    s_lshl_b32 s10, s46, 24
; SI-NEXT:    s_lshl_b32 s11, s11, 16
; SI-NEXT:    s_and_b32 s7, s7, 0xffff
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    s_or_b32 s7, s10, s7
; SI-NEXT:    s_and_b32 s10, s16, 0xff
; SI-NEXT:    s_lshl_b32 s11, s17, 8
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_or_b32 s10, s11, s10
; SI-NEXT:    s_and_b32 s12, s18, 0xff
; SI-NEXT:    s_addk_i32 s10, 0x300
; SI-NEXT:    s_lshl_b32 s11, s19, 24
; SI-NEXT:    s_lshl_b32 s12, s12, 16
; SI-NEXT:    s_and_b32 s10, s10, 0xffff
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_or_b32 s10, s11, s10
; SI-NEXT:    s_and_b32 s11, s20, 0xff
; SI-NEXT:    s_lshl_b32 s12, s21, 8
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_or_b32 s11, s12, s11
; SI-NEXT:    s_and_b32 s13, s22, 0xff
; SI-NEXT:    s_addk_i32 s11, 0x300
; SI-NEXT:    s_lshl_b32 s12, s23, 24
; SI-NEXT:    s_lshl_b32 s13, s13, 16
; SI-NEXT:    s_and_b32 s11, s11, 0xffff
; SI-NEXT:    s_or_b32 s12, s12, s13
; SI-NEXT:    s_or_b32 s11, s12, s11
; SI-NEXT:    s_add_i32 s4, s4, 0x3000000
; SI-NEXT:    s_add_i32 s5, s5, 0x3000000
; SI-NEXT:    s_add_i32 s6, s6, 0x3000000
; SI-NEXT:    s_add_i32 s7, s7, 0x3000000
; SI-NEXT:    s_add_i32 s10, s10, 0x3000000
; SI-NEXT:    s_add_i32 s11, s11, 0x3000000
; SI-NEXT:    s_lshr_b64 s[12:13], s[10:11], 16
; SI-NEXT:    s_lshr_b64 s[14:15], s[6:7], 16
; SI-NEXT:    s_lshr_b64 s[40:41], s[4:5], 16
; SI-NEXT:    s_lshr_b64 s[42:43], s[8:9], 16
; SI-NEXT:    s_lshr_b32 s15, s11, 16
; SI-NEXT:    s_lshr_b32 s41, s7, 16
; SI-NEXT:    s_lshr_b32 s43, s5, 16
; SI-NEXT:    s_lshr_b32 s13, s9, 16
; SI-NEXT:  .LBB99_3: ; %end
; SI-NEXT:    s_and_b32 s10, s10, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s12, 16
; SI-NEXT:    s_or_b32 s10, s10, s12
; SI-NEXT:    s_and_b32 s11, s11, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s15, 16
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    s_and_b32 s6, s6, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s14, 16
; SI-NEXT:    s_or_b32 s6, s6, s12
; SI-NEXT:    s_and_b32 s7, s7, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s41, 16
; SI-NEXT:    s_or_b32 s7, s7, s12
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s40, 16
; SI-NEXT:    s_or_b32 s4, s4, s12
; SI-NEXT:    s_and_b32 s5, s5, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s43, 16
; SI-NEXT:    s_or_b32 s5, s5, s12
; SI-NEXT:    s_and_b32 s8, s8, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s42, 16
; SI-NEXT:    s_or_b32 s8, s8, s12
; SI-NEXT:    s_and_b32 s9, s9, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s13, 16
; SI-NEXT:    s_or_b32 s9, s9, s12
; SI-NEXT:    v_mov_b32_e32 v0, s10
; SI-NEXT:    v_mov_b32_e32 v1, s11
; SI-NEXT:    v_mov_b32_e32 v2, s6
; SI-NEXT:    v_mov_b32_e32 v3, s7
; SI-NEXT:    v_mov_b32_e32 v4, s4
; SI-NEXT:    v_mov_b32_e32 v5, s5
; SI-NEXT:    v_mov_b32_e32 v6, s8
; SI-NEXT:    v_mov_b32_e32 v7, s9
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB99_4:
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr12
; SI-NEXT:    ; implicit-def: $sgpr15
; SI-NEXT:    ; implicit-def: $sgpr6
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr41
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr40
; SI-NEXT:    ; implicit-def: $sgpr43
; SI-NEXT:    ; implicit-def: $sgpr8
; SI-NEXT:    ; implicit-def: $sgpr42
; SI-NEXT:    ; implicit-def: $sgpr13
; SI-NEXT:    s_branch .LBB99_2
;
; VI-LABEL: bitcast_v32i8_to_v16i16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_readfirstlane_b32 s4, v18
; VI-NEXT:    v_readfirstlane_b32 s46, v17
; VI-NEXT:    v_readfirstlane_b32 s47, v16
; VI-NEXT:    v_readfirstlane_b32 s43, v15
; VI-NEXT:    v_readfirstlane_b32 s45, v14
; VI-NEXT:    v_readfirstlane_b32 s41, v13
; VI-NEXT:    v_readfirstlane_b32 s44, v12
; VI-NEXT:    v_readfirstlane_b32 s15, v11
; VI-NEXT:    v_readfirstlane_b32 s42, v10
; VI-NEXT:    v_readfirstlane_b32 s13, v9
; VI-NEXT:    v_readfirstlane_b32 s40, v8
; VI-NEXT:    v_readfirstlane_b32 s11, v7
; VI-NEXT:    v_readfirstlane_b32 s14, v6
; VI-NEXT:    v_readfirstlane_b32 s8, v5
; VI-NEXT:    v_readfirstlane_b32 s12, v4
; VI-NEXT:    v_readfirstlane_b32 s7, v3
; VI-NEXT:    v_readfirstlane_b32 s9, v2
; VI-NEXT:    v_readfirstlane_b32 s6, v1
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    v_readfirstlane_b32 s10, v0
; VI-NEXT:    s_cbranch_scc0 .LBB99_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_mov_b32_e32 v7, 0xc0c0004
; VI-NEXT:    v_mov_b32_e32 v1, s19
; VI-NEXT:    v_mov_b32_e32 v0, s17
; VI-NEXT:    v_perm_b32 v1, s18, v1, v7
; VI-NEXT:    v_perm_b32 v0, s16, v0, v7
; VI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_mov_b32_e32 v2, s23
; VI-NEXT:    v_or_b32_e32 v0, v0, v1
; VI-NEXT:    v_mov_b32_e32 v1, s21
; VI-NEXT:    v_perm_b32 v2, s22, v2, v7
; VI-NEXT:    v_perm_b32 v1, s20, v1, v7
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_mov_b32_e32 v3, s27
; VI-NEXT:    v_or_b32_e32 v1, v1, v2
; VI-NEXT:    v_mov_b32_e32 v2, s25
; VI-NEXT:    v_perm_b32 v3, s26, v3, v7
; VI-NEXT:    v_perm_b32 v2, s24, v2, v7
; VI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_mov_b32_e32 v4, s6
; VI-NEXT:    v_or_b32_e32 v2, v2, v3
; VI-NEXT:    v_mov_b32_e32 v3, s29
; VI-NEXT:    v_perm_b32 v4, s10, v4, v7
; VI-NEXT:    v_perm_b32 v3, s28, v3, v7
; VI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_mov_b32_e32 v5, s8
; VI-NEXT:    v_or_b32_e32 v3, v3, v4
; VI-NEXT:    v_mov_b32_e32 v4, s7
; VI-NEXT:    v_perm_b32 v5, s12, v5, v7
; VI-NEXT:    v_perm_b32 v4, s9, v4, v7
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_mov_b32_e32 v6, s13
; VI-NEXT:    v_or_b32_e32 v4, v4, v5
; VI-NEXT:    v_mov_b32_e32 v5, s11
; VI-NEXT:    v_perm_b32 v6, s40, v6, v7
; VI-NEXT:    v_perm_b32 v5, s14, v5, v7
; VI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_mov_b32_e32 v8, s41
; VI-NEXT:    v_or_b32_e32 v5, v5, v6
; VI-NEXT:    v_mov_b32_e32 v6, s15
; VI-NEXT:    v_perm_b32 v8, s44, v8, v7
; VI-NEXT:    v_perm_b32 v6, s42, v6, v7
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; VI-NEXT:    v_or_b32_e32 v6, v6, v8
; VI-NEXT:    v_mov_b32_e32 v8, s43
; VI-NEXT:    v_mov_b32_e32 v9, s46
; VI-NEXT:    v_perm_b32 v8, s45, v8, v7
; VI-NEXT:    v_perm_b32 v7, s47, v9, v7
; VI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; VI-NEXT:    v_or_b32_e32 v7, v8, v7
; VI-NEXT:    s_cbranch_execnz .LBB99_3
; VI-NEXT:  .LBB99_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s47, s47, 3
; VI-NEXT:    v_mov_b32_e32 v0, s46
; VI-NEXT:    v_mov_b32_e32 v1, 0xc0c0004
; VI-NEXT:    v_perm_b32 v2, s47, v0, v1
; VI-NEXT:    s_add_i32 s45, s45, 3
; VI-NEXT:    v_mov_b32_e32 v0, s43
; VI-NEXT:    v_perm_b32 v3, s45, v0, v1
; VI-NEXT:    s_add_i32 s44, s44, 3
; VI-NEXT:    v_mov_b32_e32 v0, s41
; VI-NEXT:    v_perm_b32 v4, s44, v0, v1
; VI-NEXT:    s_add_i32 s42, s42, 3
; VI-NEXT:    v_mov_b32_e32 v0, s15
; VI-NEXT:    v_perm_b32 v5, s42, v0, v1
; VI-NEXT:    s_add_i32 s40, s40, 3
; VI-NEXT:    v_mov_b32_e32 v0, s13
; VI-NEXT:    v_perm_b32 v6, s40, v0, v1
; VI-NEXT:    s_add_i32 s14, s14, 3
; VI-NEXT:    v_mov_b32_e32 v0, s11
; VI-NEXT:    v_perm_b32 v7, s14, v0, v1
; VI-NEXT:    s_add_i32 s12, s12, 3
; VI-NEXT:    v_mov_b32_e32 v0, s8
; VI-NEXT:    v_perm_b32 v8, s12, v0, v1
; VI-NEXT:    s_add_i32 s9, s9, 3
; VI-NEXT:    v_mov_b32_e32 v0, s7
; VI-NEXT:    v_perm_b32 v9, s9, v0, v1
; VI-NEXT:    s_add_i32 s10, s10, 3
; VI-NEXT:    v_mov_b32_e32 v0, s6
; VI-NEXT:    v_perm_b32 v10, s10, v0, v1
; VI-NEXT:    s_add_i32 s28, s28, 3
; VI-NEXT:    v_mov_b32_e32 v0, s29
; VI-NEXT:    v_perm_b32 v11, s28, v0, v1
; VI-NEXT:    s_add_i32 s26, s26, 3
; VI-NEXT:    v_mov_b32_e32 v0, s27
; VI-NEXT:    v_perm_b32 v12, s26, v0, v1
; VI-NEXT:    s_add_i32 s24, s24, 3
; VI-NEXT:    v_mov_b32_e32 v0, s25
; VI-NEXT:    v_perm_b32 v13, s24, v0, v1
; VI-NEXT:    s_add_i32 s22, s22, 3
; VI-NEXT:    v_mov_b32_e32 v0, s23
; VI-NEXT:    s_add_i32 s20, s20, 3
; VI-NEXT:    v_mov_b32_e32 v14, s21
; VI-NEXT:    s_add_i32 s18, s18, 3
; VI-NEXT:    v_mov_b32_e32 v15, s19
; VI-NEXT:    s_add_i32 s16, s16, 3
; VI-NEXT:    v_mov_b32_e32 v16, s17
; VI-NEXT:    v_perm_b32 v0, s22, v0, v1
; VI-NEXT:    v_perm_b32 v14, s20, v14, v1
; VI-NEXT:    v_perm_b32 v15, s18, v15, v1
; VI-NEXT:    v_perm_b32 v1, s16, v16, v1
; VI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; VI-NEXT:    v_add_u32_e32 v14, vcc, 0x300, v14
; VI-NEXT:    v_lshlrev_b32_e32 v15, 16, v15
; VI-NEXT:    v_add_u32_e32 v1, vcc, 0x300, v1
; VI-NEXT:    v_or_b32_sdwa v1, v15, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_or_b32_sdwa v14, v0, v14 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_add_u32_e32 v0, vcc, 0x3000000, v1
; VI-NEXT:    v_add_u32_e32 v1, vcc, 0x3000000, v14
; VI-NEXT:    v_lshlrev_b32_e32 v14, 16, v2
; VI-NEXT:    v_add_u32_e32 v15, vcc, 0x300, v3
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v4
; VI-NEXT:    v_add_u32_e32 v17, vcc, 0x300, v5
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v6
; VI-NEXT:    v_add_u32_e32 v6, vcc, 0x300, v7
; VI-NEXT:    v_lshlrev_b32_e32 v4, 16, v8
; VI-NEXT:    v_add_u32_e32 v7, vcc, 0x300, v9
; VI-NEXT:    v_lshlrev_b32_e32 v3, 16, v10
; VI-NEXT:    v_add_u32_e32 v8, vcc, 0x300, v11
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v12
; VI-NEXT:    v_add_u32_e32 v9, vcc, 0x300, v13
; VI-NEXT:    v_or_b32_sdwa v2, v2, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_or_b32_sdwa v3, v3, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_or_b32_sdwa v4, v4, v7 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_or_b32_sdwa v5, v5, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_or_b32_sdwa v6, v16, v17 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_or_b32_sdwa v7, v14, v15 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_add_u32_e32 v2, vcc, 0x3000000, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x3000000, v3
; VI-NEXT:    v_add_u32_e32 v4, vcc, 0x3000000, v4
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x3000000, v5
; VI-NEXT:    v_add_u32_e32 v6, vcc, 0x3000000, v6
; VI-NEXT:    v_add_u32_e32 v7, vcc, 0x3000000, v7
; VI-NEXT:  .LBB99_3: ; %end
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB99_4:
; VI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; VI-NEXT:    s_branch .LBB99_2
;
; GFX9-LABEL: bitcast_v32i8_to_v16i16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_readfirstlane_b32 s4, v18
; GFX9-NEXT:    v_readfirstlane_b32 s41, v17
; GFX9-NEXT:    v_readfirstlane_b32 s43, v16
; GFX9-NEXT:    v_readfirstlane_b32 s46, v15
; GFX9-NEXT:    v_readfirstlane_b32 s47, v14
; GFX9-NEXT:    v_readfirstlane_b32 s13, v13
; GFX9-NEXT:    v_readfirstlane_b32 s15, v12
; GFX9-NEXT:    v_readfirstlane_b32 s44, v11
; GFX9-NEXT:    v_readfirstlane_b32 s45, v10
; GFX9-NEXT:    v_readfirstlane_b32 s10, v9
; GFX9-NEXT:    v_readfirstlane_b32 s11, v8
; GFX9-NEXT:    v_readfirstlane_b32 s40, v7
; GFX9-NEXT:    v_readfirstlane_b32 s42, v6
; GFX9-NEXT:    v_readfirstlane_b32 s7, v5
; GFX9-NEXT:    v_readfirstlane_b32 s9, v4
; GFX9-NEXT:    v_readfirstlane_b32 s12, v3
; GFX9-NEXT:    v_readfirstlane_b32 s14, v2
; GFX9-NEXT:    v_readfirstlane_b32 s6, v1
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    v_readfirstlane_b32 s8, v0
; GFX9-NEXT:    s_cbranch_scc0 .LBB99_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    v_mov_b32_e32 v0, s17
; GFX9-NEXT:    v_mov_b32_e32 v4, 0xc0c0004
; GFX9-NEXT:    v_perm_b32 v0, s16, v0, v4
; GFX9-NEXT:    v_mov_b32_e32 v1, s19
; GFX9-NEXT:    v_perm_b32 v1, s18, v1, v4
; GFX9-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX9-NEXT:    v_lshl_or_b32 v0, v1, 16, v0
; GFX9-NEXT:    v_mov_b32_e32 v1, s21
; GFX9-NEXT:    v_perm_b32 v1, s20, v1, v4
; GFX9-NEXT:    v_mov_b32_e32 v2, s23
; GFX9-NEXT:    v_perm_b32 v2, s22, v2, v4
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; GFX9-NEXT:    v_lshl_or_b32 v1, v2, 16, v1
; GFX9-NEXT:    v_mov_b32_e32 v2, s25
; GFX9-NEXT:    v_perm_b32 v2, s24, v2, v4
; GFX9-NEXT:    v_mov_b32_e32 v3, s27
; GFX9-NEXT:    v_perm_b32 v3, s26, v3, v4
; GFX9-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX9-NEXT:    v_lshl_or_b32 v2, v3, 16, v2
; GFX9-NEXT:    v_mov_b32_e32 v3, s29
; GFX9-NEXT:    v_perm_b32 v3, s28, v3, v4
; GFX9-NEXT:    v_mov_b32_e32 v5, s6
; GFX9-NEXT:    s_and_b32 s4, s14, 0xff
; GFX9-NEXT:    s_lshl_b32 s5, s12, 8
; GFX9-NEXT:    v_perm_b32 v5, s8, v5, v4
; GFX9-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GFX9-NEXT:    s_or_b32 s4, s4, s5
; GFX9-NEXT:    s_and_b32 s5, s9, 0xff
; GFX9-NEXT:    s_lshl_b32 s56, s7, 8
; GFX9-NEXT:    v_lshl_or_b32 v3, v5, 16, v3
; GFX9-NEXT:    s_or_b32 s5, s5, s56
; GFX9-NEXT:    v_mov_b32_e32 v5, s40
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s4, s5
; GFX9-NEXT:    v_perm_b32 v5, s42, v5, v4
; GFX9-NEXT:    s_and_b32 s5, s11, 0xff
; GFX9-NEXT:    s_lshl_b32 s56, s10, 8
; GFX9-NEXT:    s_or_b32 s5, s5, s56
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX9-NEXT:    v_lshl_or_b32 v5, s5, 16, v5
; GFX9-NEXT:    s_and_b32 s5, s45, 0xff
; GFX9-NEXT:    s_lshl_b32 s56, s44, 8
; GFX9-NEXT:    s_or_b32 s5, s5, s56
; GFX9-NEXT:    s_and_b32 s56, s15, 0xff
; GFX9-NEXT:    s_lshl_b32 s57, s13, 8
; GFX9-NEXT:    s_or_b32 s56, s56, s57
; GFX9-NEXT:    v_mov_b32_e32 v6, s46
; GFX9-NEXT:    s_pack_ll_b32_b16 s5, s5, s56
; GFX9-NEXT:    v_perm_b32 v4, s47, v6, v4
; GFX9-NEXT:    s_and_b32 s56, s43, 0xff
; GFX9-NEXT:    s_lshl_b32 s57, s41, 8
; GFX9-NEXT:    s_or_b32 s56, s56, s57
; GFX9-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX9-NEXT:    v_lshl_or_b32 v7, s56, 16, v4
; GFX9-NEXT:    v_mov_b32_e32 v4, s4
; GFX9-NEXT:    v_mov_b32_e32 v6, s5
; GFX9-NEXT:    s_cbranch_execnz .LBB99_3
; GFX9-NEXT:  .LBB99_2: ; %cmp.true
; GFX9-NEXT:    s_add_i32 s47, s47, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s46
; GFX9-NEXT:    v_mov_b32_e32 v2, 0xc0c0004
; GFX9-NEXT:    v_perm_b32 v3, s47, v0, v2
; GFX9-NEXT:    s_add_i32 s43, s43, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s41
; GFX9-NEXT:    v_perm_b32 v4, s43, v0, v2
; GFX9-NEXT:    s_add_i32 s45, s45, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s44
; GFX9-NEXT:    v_perm_b32 v5, s45, v0, v2
; GFX9-NEXT:    s_add_i32 s15, s15, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s13
; GFX9-NEXT:    v_perm_b32 v6, s15, v0, v2
; GFX9-NEXT:    s_add_i32 s42, s42, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s40
; GFX9-NEXT:    v_perm_b32 v7, s42, v0, v2
; GFX9-NEXT:    s_add_i32 s11, s11, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s10
; GFX9-NEXT:    v_perm_b32 v8, s11, v0, v2
; GFX9-NEXT:    s_add_i32 s14, s14, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s12
; GFX9-NEXT:    v_perm_b32 v9, s14, v0, v2
; GFX9-NEXT:    s_add_i32 s9, s9, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s7
; GFX9-NEXT:    v_perm_b32 v10, s9, v0, v2
; GFX9-NEXT:    s_add_i32 s28, s28, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s29
; GFX9-NEXT:    v_perm_b32 v11, s28, v0, v2
; GFX9-NEXT:    s_add_i32 s20, s20, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s21
; GFX9-NEXT:    v_perm_b32 v0, s20, v0, v2
; GFX9-NEXT:    v_add_u32_e32 v1, 0x300, v0
; GFX9-NEXT:    s_add_i32 s22, s22, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s23
; GFX9-NEXT:    v_perm_b32 v0, s22, v0, v2
; GFX9-NEXT:    v_add_u32_e32 v12, 0x300, v0
; GFX9-NEXT:    s_add_i32 s16, s16, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s17
; GFX9-NEXT:    v_perm_b32 v0, s16, v0, v2
; GFX9-NEXT:    s_add_i32 s18, s18, 3
; GFX9-NEXT:    v_mov_b32_e32 v13, s19
; GFX9-NEXT:    v_add_u32_e32 v0, 0x300, v0
; GFX9-NEXT:    v_perm_b32 v13, s18, v13, v2
; GFX9-NEXT:    v_add_u32_e32 v13, 0x300, v13
; GFX9-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX9-NEXT:    v_lshl_or_b32 v0, v13, 16, v0
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; GFX9-NEXT:    s_add_i32 s24, s24, 3
; GFX9-NEXT:    v_mov_b32_e32 v13, s25
; GFX9-NEXT:    v_add_u32_e32 v16, 0x300, v5
; GFX9-NEXT:    v_add_u32_e32 v5, 0x300, v7
; GFX9-NEXT:    s_add_i32 s8, s8, 3
; GFX9-NEXT:    v_lshl_or_b32 v1, v12, 16, v1
; GFX9-NEXT:    v_mov_b32_e32 v12, s6
; GFX9-NEXT:    v_perm_b32 v13, s24, v13, v2
; GFX9-NEXT:    s_add_i32 s26, s26, 3
; GFX9-NEXT:    v_mov_b32_e32 v14, s27
; GFX9-NEXT:    v_add_u32_e32 v7, 0x300, v8
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX9-NEXT:    v_perm_b32 v12, s8, v12, v2
; GFX9-NEXT:    v_perm_b32 v2, s26, v14, v2
; GFX9-NEXT:    v_add_u32_e32 v14, 0x300, v3
; GFX9-NEXT:    v_add_u32_e32 v15, 0x300, v4
; GFX9-NEXT:    v_add_u32_e32 v6, 0x300, v6
; GFX9-NEXT:    v_add_u32_e32 v4, 0x300, v9
; GFX9-NEXT:    v_add_u32_e32 v8, 0x300, v10
; GFX9-NEXT:    v_add_u32_e32 v3, 0x300, v11
; GFX9-NEXT:    v_add_u32_e32 v10, 0x300, v13
; GFX9-NEXT:    v_lshl_or_b32 v5, v7, 16, v5
; GFX9-NEXT:    v_and_b32_e32 v7, 0xffff, v16
; GFX9-NEXT:    v_add_u32_e32 v9, 0x300, v12
; GFX9-NEXT:    v_add_u32_e32 v2, 0x300, v2
; GFX9-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; GFX9-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GFX9-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX9-NEXT:    v_lshl_or_b32 v6, v6, 16, v7
; GFX9-NEXT:    v_and_b32_e32 v7, 0xffff, v14
; GFX9-NEXT:    v_lshl_or_b32 v2, v2, 16, v10
; GFX9-NEXT:    v_lshl_or_b32 v3, v9, 16, v3
; GFX9-NEXT:    v_lshl_or_b32 v4, v8, 16, v4
; GFX9-NEXT:    v_lshl_or_b32 v7, v15, 16, v7
; GFX9-NEXT:  .LBB99_3: ; %end
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB99_4:
; GFX9-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX9-NEXT:    s_branch .LBB99_2
;
; GFX11-TRUE16-LABEL: bitcast_v32i8_to_v16i16_scalar:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s42, v14
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s4, v13
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr12_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s7, v12
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr11_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s5, v11
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr10_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s8, v10
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s6, v9
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr8_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s11, v8
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr7_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s10, v7
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr6_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s14, v6
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr5_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s9, v5
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr4_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s12, v4
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr3_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s40, v3
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr2_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s41, v2
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr1_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s13, v1
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr0_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s15, v0
; GFX11-TRUE16-NEXT:    s_cmp_lg_u32 s42, 0
; GFX11-TRUE16-NEXT:    s_mov_b32 s42, 0
; GFX11-TRUE16-NEXT:    s_cbranch_scc0 .LBB99_4
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v4, 0xc0c0004
; GFX11-TRUE16-NEXT:    s_and_b32 s43, s28, 0xff
; GFX11-TRUE16-NEXT:    s_lshl_b32 s44, s29, 8
; GFX11-TRUE16-NEXT:    s_and_b32 s45, s15, 0xff
; GFX11-TRUE16-NEXT:    s_lshl_b32 s46, s13, 8
; GFX11-TRUE16-NEXT:    s_or_b32 s43, s43, s44
; GFX11-TRUE16-NEXT:    s_or_b32 s44, s45, s46
; GFX11-TRUE16-NEXT:    v_perm_b32 v6, s18, s19, v4
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s43, s43, s44
; GFX11-TRUE16-NEXT:    s_and_b32 s44, s12, 0xff
; GFX11-TRUE16-NEXT:    s_lshl_b32 s45, s9, 8
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, s2, s3, v4
; GFX11-TRUE16-NEXT:    s_or_b32 s44, s44, s45
; GFX11-TRUE16-NEXT:    s_and_b32 s45, s14, 0xff
; GFX11-TRUE16-NEXT:    s_lshl_b32 s46, s10, 8
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, s16, s17, v4
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v1.h, v6.l
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v6, s44
; GFX11-TRUE16-NEXT:    s_or_b32 s44, s45, s46
; GFX11-TRUE16-NEXT:    s_and_b32 s45, s7, 0xff
; GFX11-TRUE16-NEXT:    s_lshl_b32 s46, s4, 8
; GFX11-TRUE16-NEXT:    v_perm_b32 v0, s0, s1, v4
; GFX11-TRUE16-NEXT:    s_or_b32 s45, s45, s46
; GFX11-TRUE16-NEXT:    v_perm_b32 v7, s22, s23, v4
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.h, v5.l
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, s26, s27, v4
; GFX11-TRUE16-NEXT:    s_and_b32 s47, s11, 0xff
; GFX11-TRUE16-NEXT:    s_lshl_b32 s46, s6, 8
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v8, s45
; GFX11-TRUE16-NEXT:    s_or_b32 s45, s47, s46
; GFX11-TRUE16-NEXT:    v_perm_b32 v2, s20, s21, v4
; GFX11-TRUE16-NEXT:    v_perm_b32 v3, s24, s25, v4
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s44, s44, s45
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.h, v7.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v3.h, v5.l
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, s41, s40, v4
; GFX11-TRUE16-NEXT:    v_perm_b32 v7, s8, s5, v4
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v5.h, v6.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v7.h, v8.l
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v4, s43
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v6, s44
; GFX11-TRUE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s42
; GFX11-TRUE16-NEXT:    s_cbranch_vccnz .LBB99_3
; GFX11-TRUE16-NEXT:  .LBB99_2: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v0, 0xc0c0004
; GFX11-TRUE16-NEXT:    s_add_i32 s8, s8, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s41, s41, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s7, s7, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s11, s11, 3
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, s8, s5, v0
; GFX11-TRUE16-NEXT:    s_add_i32 s28, s28, 3
; GFX11-TRUE16-NEXT:    v_perm_b32 v2, s7, s4, v0
; GFX11-TRUE16-NEXT:    v_perm_b32 v4, s11, s6, v0
; GFX11-TRUE16-NEXT:    s_add_i32 s15, s15, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v7, 0x300, v1
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, s41, s40, v0
; GFX11-TRUE16-NEXT:    s_add_i32 s20, s20, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v9, 0x300, v2
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v10, 0x300, v4
; GFX11-TRUE16-NEXT:    v_perm_b32 v2, s15, s13, v0
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v5, 0x300, v1
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, s28, s29, v0
; GFX11-TRUE16-NEXT:    s_add_i32 s14, s14, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s12, s12, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s26, s26, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s22, s22, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v4, 0x300, v1
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, s20, s21, v0
; GFX11-TRUE16-NEXT:    s_add_i32 s2, s2, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s18, s18, 3
; GFX11-TRUE16-NEXT:    v_perm_b32 v3, s14, s10, v0
; GFX11-TRUE16-NEXT:    v_perm_b32 v8, s12, s9, v0
; GFX11-TRUE16-NEXT:    v_perm_b32 v11, s26, s27, v0
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v12, 0x300, v2
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, 0x300, v1
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, s22, s23, v0
; GFX11-TRUE16-NEXT:    v_perm_b32 v13, s2, s3, v0
; GFX11-TRUE16-NEXT:    v_perm_b32 v14, s18, s19, v0
; GFX11-TRUE16-NEXT:    s_add_i32 s24, s24, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s16, s16, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s0, s0, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, 0x300, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v3, s24, s25, v0
; GFX11-TRUE16-NEXT:    v_perm_b32 v15, s16, s17, v0
; GFX11-TRUE16-NEXT:    v_perm_b32 v0, s0, s1, v0
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v8, 0x300, v8
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v11, 0x300, v11
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v13, 0x300, v13
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v14, 0x300, v14
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v16, 0x300, v1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 0x300, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, 0x300, v15
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v0, 0x300, v0
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.h, v13.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v1.h, v14.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.h, v16.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v3.h, v11.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v4.h, v12.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v5.h, v8.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v6.h, v10.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v7.h, v9.l
; GFX11-TRUE16-NEXT:  .LBB99_3: ; %end
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB99_4:
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-TRUE16-NEXT:    s_branch .LBB99_2
;
; GFX11-FAKE16-LABEL: bitcast_v32i8_to_v16i16_scalar:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s42, v14
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s10, v13
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s14, v12
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s12, v11
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s41, v10
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s6, v9
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s11, v8
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s13, v7
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s40, v6
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s4, v5
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s7, v4
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s8, v3
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s15, v2
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s5, v1
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s9, v0
; GFX11-FAKE16-NEXT:    s_cmp_lg_u32 s42, 0
; GFX11-FAKE16-NEXT:    s_mov_b32 s42, 0
; GFX11-FAKE16-NEXT:    s_cbranch_scc0 .LBB99_4
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v4, 0xc0c0004
; GFX11-FAKE16-NEXT:    s_and_b32 s43, s28, 0xff
; GFX11-FAKE16-NEXT:    s_lshl_b32 s44, s29, 8
; GFX11-FAKE16-NEXT:    s_lshl_b32 s45, s5, 8
; GFX11-FAKE16-NEXT:    s_or_b32 s43, s43, s44
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, s0, s1, v4
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, s16, s17, v4
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, s20, s21, v4
; GFX11-FAKE16-NEXT:    s_and_b32 s44, s9, 0xff
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, s2, s3, v4
; GFX11-FAKE16-NEXT:    s_or_b32 s44, s44, s45
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, s18, s19, v4
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, s22, s23, v4
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s43, s43, s44
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX11-FAKE16-NEXT:    s_and_b32 s46, s7, 0xff
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v0, v1, 16, v0
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v1, v3, 16, v2
; GFX11-FAKE16-NEXT:    s_lshl_b32 s47, s4, 8
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v2, v6, 16, v5
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, s15, s8, v4
; GFX11-FAKE16-NEXT:    s_or_b32 s45, s46, s47
; GFX11-FAKE16-NEXT:    s_and_b32 s44, s40, 0xff
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, s24, s25, v4
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, s26, s27, v4
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, s41, s12, v4
; GFX11-FAKE16-NEXT:    s_lshl_b32 s46, s6, 8
; GFX11-FAKE16-NEXT:    s_and_b32 s47, s14, 0xff
; GFX11-FAKE16-NEXT:    s_lshl_b32 s56, s10, 8
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v5, s45, 16, v5
; GFX11-FAKE16-NEXT:    s_lshl_b32 s45, s13, 8
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX11-FAKE16-NEXT:    s_or_b32 s44, s44, s45
; GFX11-FAKE16-NEXT:    s_and_b32 s45, s11, 0xff
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(SKIP_2) | instid1(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_or_b32 s45, s45, s46
; GFX11-FAKE16-NEXT:    s_or_b32 s46, s47, s56
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s44, s44, s45
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v6, s44 :: v_dual_and_b32 v7, 0xffff, v7
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v3, v8, 16, v7
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v7, s46, 16, v4
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v4, s43
; GFX11-FAKE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s42
; GFX11-FAKE16-NEXT:    s_cbranch_vccnz .LBB99_3
; GFX11-FAKE16-NEXT:  .LBB99_2: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v0, 0xc0c0004
; GFX11-FAKE16-NEXT:    s_add_i32 s41, s41, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s14, s14, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s11, s11, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s15, s15, 3
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, s41, s12, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, s14, s10, v0
; GFX11-FAKE16-NEXT:    s_add_i32 s20, s20, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s16, s16, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s0, s0, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, 0x300, v1
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, s11, s6, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v7, 0x300, v2
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, s15, s8, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, s16, s17, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v14, s0, s1, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v9, 0x300, v1
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, s20, s21, v0
; GFX11-FAKE16-NEXT:    s_add_i32 s40, s40, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s7, s7, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s28, s28, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s9, s9, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s24, s24, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s26, s26, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s22, s22, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s18, s18, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s2, s2, 3
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, s40, s13, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, s7, s4, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, s28, s29, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, s9, s5, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v10, 0x300, v2
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, s24, s25, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, s26, s27, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v1, 0x300, v1
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, s22, s23, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v15, s18, s19, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, s2, s3, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v14, 0x300, v14
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v13, 0x300, v13
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, 0x300, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v6, 0x300, v6
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v12, 0x300, v12
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v15, 0x300, v15
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v0, 0x300, v0
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v16, 0xffff, v1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v17, 0x300, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v5, 0x300, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v8, 0x300, v8
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v11, 0x300, v11
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v0, v0, 16, v14
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v1, v15, 16, v13
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v2, v12, 16, v16
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v12, 0xffff, v17
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v13, 0xffff, v3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v14, 0xffff, v4
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v3, v11, 16, v12
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v4, v8, 16, v6
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v5, v5, 16, v10
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v6, v9, 16, v13
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v7, v7, 16, v14
; GFX11-FAKE16-NEXT:  .LBB99_3: ; %end
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB99_4:
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-FAKE16-NEXT:    s_branch .LBB99_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <32 x i8> %a, splat (i8 3)
  %a2 = bitcast <32 x i8> %a1 to <16 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <32 x i8> %a to <16 x i16>
  br label %end

end:
  %phi = phi <16 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x i16> %phi
}

define <16 x bfloat> @bitcast_v16f16_to_v16bf16(<16 x half> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v16f16_to_v16bf16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v31, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v6
; SI-NEXT:    v_lshrrev_b32_e32 v29, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v28, 16, v4
; SI-NEXT:    v_lshrrev_b32_e32 v27, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v26, 16, v2
; SI-NEXT:    v_lshrrev_b32_e32 v25, 16, v1
; SI-NEXT:    v_lshrrev_b32_e32 v24, 16, v0
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB100_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v0
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v24
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v1
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v25
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v2
; SI-NEXT:    v_lshlrev_b32_e32 v15, 16, v26
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v3
; SI-NEXT:    v_lshlrev_b32_e32 v17, 16, v27
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v4
; SI-NEXT:    v_lshlrev_b32_e32 v19, 16, v28
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v5
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v29
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v6
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v30
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v7
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v31
; SI-NEXT:    ; implicit-def: $vgpr0
; SI-NEXT:    ; implicit-def: $vgpr1
; SI-NEXT:    ; implicit-def: $vgpr2
; SI-NEXT:    ; implicit-def: $vgpr3
; SI-NEXT:    ; implicit-def: $vgpr4
; SI-NEXT:    ; implicit-def: $vgpr5
; SI-NEXT:    ; implicit-def: $vgpr6
; SI-NEXT:    ; implicit-def: $vgpr7
; SI-NEXT:    ; implicit-def: $vgpr24
; SI-NEXT:    ; implicit-def: $vgpr25
; SI-NEXT:    ; implicit-def: $vgpr26
; SI-NEXT:    ; implicit-def: $vgpr27
; SI-NEXT:    ; implicit-def: $vgpr28
; SI-NEXT:    ; implicit-def: $vgpr29
; SI-NEXT:    ; implicit-def: $vgpr30
; SI-NEXT:    ; implicit-def: $vgpr31
; SI-NEXT:  .LBB100_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB100_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_cvt_f32_f16_e32 v8, v31
; SI-NEXT:    v_cvt_f32_f16_e32 v9, v30
; SI-NEXT:    v_cvt_f32_f16_e32 v7, v7
; SI-NEXT:    v_cvt_f32_f16_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v23, v8
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v20, v8
; SI-NEXT:    v_cvt_f32_f16_e32 v8, v29
; SI-NEXT:    v_cvt_f32_f16_e32 v5, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v4, v4
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v18, v8
; SI-NEXT:    v_cvt_f32_f16_e32 v8, v28
; SI-NEXT:    v_cvt_f32_f16_e32 v2, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v1, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v9, v24
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v16, v8
; SI-NEXT:    v_cvt_f32_f16_e32 v8, v27
; SI-NEXT:    v_cvt_f32_f16_e32 v0, v0
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v14, v8
; SI-NEXT:    v_cvt_f32_f16_e32 v8, v26
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v12, v8
; SI-NEXT:    v_cvt_f32_f16_e32 v8, v25
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v10, v8
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v0
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v9
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v1
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v10
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v2
; SI-NEXT:    v_lshlrev_b32_e32 v15, 16, v12
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v3
; SI-NEXT:    v_lshlrev_b32_e32 v17, 16, v14
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v4
; SI-NEXT:    v_lshlrev_b32_e32 v19, 16, v16
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v5
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v18
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v6
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v20
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v7
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; SI-NEXT:  .LBB100_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_mul_f32_e32 v0, 1.0, v11
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_mul_f32_e32 v1, 1.0, v8
; SI-NEXT:    v_alignbit_b32 v0, v0, v1, 16
; SI-NEXT:    v_mul_f32_e32 v1, 1.0, v13
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_mul_f32_e32 v2, 1.0, v9
; SI-NEXT:    v_alignbit_b32 v1, v1, v2, 16
; SI-NEXT:    v_mul_f32_e32 v2, 1.0, v15
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_mul_f32_e32 v3, 1.0, v10
; SI-NEXT:    v_alignbit_b32 v2, v2, v3, 16
; SI-NEXT:    v_mul_f32_e32 v3, 1.0, v17
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_mul_f32_e32 v4, 1.0, v12
; SI-NEXT:    v_alignbit_b32 v3, v3, v4, 16
; SI-NEXT:    v_mul_f32_e32 v4, 1.0, v19
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_mul_f32_e32 v5, 1.0, v14
; SI-NEXT:    v_alignbit_b32 v4, v4, v5, 16
; SI-NEXT:    v_mul_f32_e32 v5, 1.0, v21
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_mul_f32_e32 v6, 1.0, v16
; SI-NEXT:    v_alignbit_b32 v5, v5, v6, 16
; SI-NEXT:    v_mul_f32_e32 v6, 1.0, v22
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_mul_f32_e32 v7, 1.0, v18
; SI-NEXT:    v_alignbit_b32 v6, v6, v7, 16
; SI-NEXT:    v_mul_f32_e32 v7, 1.0, v23
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_mul_f32_e32 v8, 1.0, v20
; SI-NEXT:    v_alignbit_b32 v7, v7, v8, 16
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16f16_to_v16bf16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB100_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v9, 0x200
; VI-NEXT:    v_add_f16_e32 v8, 0x200, v0
; VI-NEXT:    v_add_f16_sdwa v0, v0, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v10, 0x200, v1
; VI-NEXT:    v_add_f16_sdwa v1, v1, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v11, 0x200, v2
; VI-NEXT:    v_add_f16_sdwa v2, v2, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v12, 0x200, v3
; VI-NEXT:    v_add_f16_sdwa v3, v3, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v13, 0x200, v4
; VI-NEXT:    v_add_f16_sdwa v4, v4, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v14, 0x200, v5
; VI-NEXT:    v_add_f16_sdwa v5, v5, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v15, 0x200, v6
; VI-NEXT:    v_add_f16_sdwa v6, v6, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v16, 0x200, v7
; VI-NEXT:    v_add_f16_sdwa v7, v7, v9 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v7, v16, v7
; VI-NEXT:    v_or_b32_e32 v6, v15, v6
; VI-NEXT:    v_or_b32_e32 v5, v14, v5
; VI-NEXT:    v_or_b32_e32 v4, v13, v4
; VI-NEXT:    v_or_b32_e32 v3, v12, v3
; VI-NEXT:    v_or_b32_e32 v2, v11, v2
; VI-NEXT:    v_or_b32_e32 v1, v10, v1
; VI-NEXT:    v_or_b32_e32 v0, v8, v0
; VI-NEXT:  .LBB100_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16f16_to_v16bf16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    s_movk_i32 s6, 0x200
; GFX9-NEXT:    v_pk_add_f16 v7, v7, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, v6, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v5, v5, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v4, v4, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v3, v3, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v2, v2, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v1, v1, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v0, v0, s6 op_sel_hi:[1,0]
; GFX9-NEXT:  ; %bb.2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v16f16_to_v16bf16:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB100_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_pk_add_f16 v7, 0x200, v7 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v6, 0x200, v6 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v5, 0x200, v5 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v4, 0x200, v4 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v3, 0x200, v3 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v2, 0x200, v2 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v1, 0x200, v1 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v0, 0x200, v0 op_sel_hi:[0,1]
; GFX11-NEXT:  .LBB100_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <16 x half> %a1 to <16 x bfloat>
  br label %end

cmp.false:
  %a3 = bitcast <16 x half> %a to <16 x bfloat>
  br label %end

end:
  %phi = phi <16 x bfloat> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x bfloat> %phi
}

define inreg <16 x bfloat> @bitcast_v16f16_to_v16bf16_scalar(<16 x half> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v16f16_to_v16bf16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_lshr_b32 s14, s23, 16
; SI-NEXT:    s_lshr_b32 s12, s22, 16
; SI-NEXT:    s_lshr_b32 s11, s21, 16
; SI-NEXT:    s_lshr_b32 s10, s20, 16
; SI-NEXT:    s_lshr_b32 s9, s19, 16
; SI-NEXT:    s_lshr_b32 s8, s18, 16
; SI-NEXT:    s_lshr_b32 s7, s17, 16
; SI-NEXT:    s_lshr_b32 s6, s16, 16
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB101_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_lshl_b32 s13, s16, 16
; SI-NEXT:    s_lshl_b32 s15, s6, 16
; SI-NEXT:    s_lshl_b32 s24, s17, 16
; SI-NEXT:    s_lshl_b32 s25, s7, 16
; SI-NEXT:    s_lshl_b32 s26, s18, 16
; SI-NEXT:    s_lshl_b32 s27, s8, 16
; SI-NEXT:    s_lshl_b32 s28, s19, 16
; SI-NEXT:    s_lshl_b32 s29, s9, 16
; SI-NEXT:    s_lshl_b32 s40, s20, 16
; SI-NEXT:    s_lshl_b32 s41, s10, 16
; SI-NEXT:    s_lshl_b32 s42, s21, 16
; SI-NEXT:    s_lshl_b32 s43, s11, 16
; SI-NEXT:    s_lshl_b32 s44, s22, 16
; SI-NEXT:    s_lshl_b32 s45, s12, 16
; SI-NEXT:    s_lshl_b32 s46, s23, 16
; SI-NEXT:    s_lshl_b32 s47, s14, 16
; SI-NEXT:    s_cbranch_execnz .LBB101_4
; SI-NEXT:  .LBB101_2: ; %cmp.true
; SI-NEXT:    v_cvt_f32_f16_e32 v0, s14
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s23
; SI-NEXT:    v_cvt_f32_f16_e32 v2, s12
; SI-NEXT:    v_cvt_f32_f16_e32 v15, s16
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v8, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v0, s22
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v10, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s11
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v0
; SI-NEXT:    v_cvt_f32_f16_e32 v0, s21
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v11, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s10
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v0
; SI-NEXT:    v_cvt_f32_f16_e32 v0, s20
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v12, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s9
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v0
; SI-NEXT:    v_cvt_f32_f16_e32 v0, s19
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v13, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s8
; SI-NEXT:    v_cvt_f32_f16_e32 v2, s18
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v0
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v14, v0
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v0
; SI-NEXT:    v_cvt_f32_f16_e32 v0, s7
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s17
; SI-NEXT:    v_cvt_f32_f16_e32 v2, s6
; SI-NEXT:    v_add_f32_e32 v15, 0x38000000, v15
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v15, v15
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v16, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v17, v0
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v15
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v2
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v16
; SI-NEXT:    v_lshlrev_b32_e32 v15, 16, v17
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v14
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v13
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v12
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v10
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; SI-NEXT:    s_branch .LBB101_5
; SI-NEXT:  .LBB101_3:
; SI-NEXT:    ; implicit-def: $sgpr13
; SI-NEXT:    ; implicit-def: $sgpr15
; SI-NEXT:    ; implicit-def: $sgpr24
; SI-NEXT:    ; implicit-def: $sgpr25
; SI-NEXT:    ; implicit-def: $sgpr26
; SI-NEXT:    ; implicit-def: $sgpr27
; SI-NEXT:    ; implicit-def: $sgpr28
; SI-NEXT:    ; implicit-def: $sgpr29
; SI-NEXT:    ; implicit-def: $sgpr40
; SI-NEXT:    ; implicit-def: $sgpr41
; SI-NEXT:    ; implicit-def: $sgpr42
; SI-NEXT:    ; implicit-def: $sgpr43
; SI-NEXT:    ; implicit-def: $sgpr44
; SI-NEXT:    ; implicit-def: $sgpr45
; SI-NEXT:    ; implicit-def: $sgpr46
; SI-NEXT:    ; implicit-def: $sgpr47
; SI-NEXT:    s_branch .LBB101_2
; SI-NEXT:  .LBB101_4:
; SI-NEXT:    v_mov_b32_e32 v9, s47
; SI-NEXT:    v_mov_b32_e32 v8, s46
; SI-NEXT:    v_mov_b32_e32 v10, s45
; SI-NEXT:    v_mov_b32_e32 v7, s44
; SI-NEXT:    v_mov_b32_e32 v11, s43
; SI-NEXT:    v_mov_b32_e32 v6, s42
; SI-NEXT:    v_mov_b32_e32 v12, s41
; SI-NEXT:    v_mov_b32_e32 v5, s40
; SI-NEXT:    v_mov_b32_e32 v13, s29
; SI-NEXT:    v_mov_b32_e32 v4, s28
; SI-NEXT:    v_mov_b32_e32 v14, s27
; SI-NEXT:    v_mov_b32_e32 v3, s26
; SI-NEXT:    v_mov_b32_e32 v15, s25
; SI-NEXT:    v_mov_b32_e32 v2, s24
; SI-NEXT:    v_mov_b32_e32 v1, s15
; SI-NEXT:    v_mov_b32_e32 v0, s13
; SI-NEXT:  .LBB101_5: ; %end
; SI-NEXT:    v_mul_f32_e32 v1, 1.0, v1
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_mul_f32_e32 v0, 1.0, v0
; SI-NEXT:    v_lshr_b64 v[0:1], v[0:1], 16
; SI-NEXT:    v_mul_f32_e32 v1, 1.0, v15
; SI-NEXT:    v_lshrrev_b32_e32 v16, 16, v1
; SI-NEXT:    v_mul_f32_e32 v15, 1.0, v2
; SI-NEXT:    v_lshr_b64 v[1:2], v[15:16], 16
; SI-NEXT:    v_mul_f32_e32 v2, 1.0, v14
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v2
; SI-NEXT:    v_mul_f32_e32 v14, 1.0, v3
; SI-NEXT:    v_lshr_b64 v[2:3], v[14:15], 16
; SI-NEXT:    v_mul_f32_e32 v3, 1.0, v13
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; SI-NEXT:    v_mul_f32_e32 v13, 1.0, v4
; SI-NEXT:    v_lshr_b64 v[3:4], v[13:14], 16
; SI-NEXT:    v_mul_f32_e32 v4, 1.0, v12
; SI-NEXT:    v_lshrrev_b32_e32 v13, 16, v4
; SI-NEXT:    v_mul_f32_e32 v12, 1.0, v5
; SI-NEXT:    v_lshr_b64 v[4:5], v[12:13], 16
; SI-NEXT:    v_mul_f32_e32 v5, 1.0, v11
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v5
; SI-NEXT:    v_mul_f32_e32 v11, 1.0, v6
; SI-NEXT:    v_lshr_b64 v[5:6], v[11:12], 16
; SI-NEXT:    v_mul_f32_e32 v6, 1.0, v10
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v6
; SI-NEXT:    v_mul_f32_e32 v10, 1.0, v7
; SI-NEXT:    v_lshr_b64 v[6:7], v[10:11], 16
; SI-NEXT:    v_mul_f32_e32 v7, 1.0, v9
; SI-NEXT:    v_lshrrev_b32_e32 v9, 16, v7
; SI-NEXT:    v_mul_f32_e32 v8, 1.0, v8
; SI-NEXT:    v_lshr_b64 v[7:8], v[8:9], 16
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16f16_to_v16bf16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB101_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB101_4
; VI-NEXT:  .LBB101_2: ; %cmp.true
; VI-NEXT:    s_lshr_b32 s4, s16, 16
; VI-NEXT:    v_mov_b32_e32 v1, s4
; VI-NEXT:    s_lshr_b32 s4, s17, 16
; VI-NEXT:    v_mov_b32_e32 v2, s4
; VI-NEXT:    s_lshr_b32 s4, s18, 16
; VI-NEXT:    s_lshr_b32 s5, s22, 16
; VI-NEXT:    v_mov_b32_e32 v0, 0x200
; VI-NEXT:    v_mov_b32_e32 v3, s4
; VI-NEXT:    s_lshr_b32 s4, s19, 16
; VI-NEXT:    v_mov_b32_e32 v6, s5
; VI-NEXT:    s_lshr_b32 s5, s23, 16
; VI-NEXT:    v_mov_b32_e32 v4, s4
; VI-NEXT:    s_lshr_b32 s4, s20, 16
; VI-NEXT:    v_add_f16_e32 v5, s22, v0
; VI-NEXT:    v_add_f16_sdwa v6, v6, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_mov_b32_e32 v13, s5
; VI-NEXT:    v_add_f16_e32 v7, s23, v0
; VI-NEXT:    v_add_f16_sdwa v13, v13, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v6, v5, v6
; VI-NEXT:    v_mov_b32_e32 v5, s4
; VI-NEXT:    s_lshr_b32 s4, s21, 16
; VI-NEXT:    v_or_b32_e32 v7, v7, v13
; VI-NEXT:    v_add_f16_sdwa v13, v5, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_mov_b32_e32 v5, s4
; VI-NEXT:    v_add_f16_e32 v8, s16, v0
; VI-NEXT:    v_add_f16_sdwa v9, v1, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v1, s17, v0
; VI-NEXT:    v_add_f16_sdwa v10, v2, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, s18, v0
; VI-NEXT:    v_add_f16_sdwa v11, v3, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v3, s19, v0
; VI-NEXT:    v_add_f16_sdwa v12, v4, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v4, s20, v0
; VI-NEXT:    v_add_f16_sdwa v5, v5, v0 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v0, s21, v0
; VI-NEXT:    v_or_b32_e32 v5, v0, v5
; VI-NEXT:    v_or_b32_e32 v4, v4, v13
; VI-NEXT:    v_or_b32_e32 v3, v3, v12
; VI-NEXT:    v_or_b32_e32 v2, v2, v11
; VI-NEXT:    v_or_b32_e32 v1, v1, v10
; VI-NEXT:    v_or_b32_e32 v0, v8, v9
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB101_3:
; VI-NEXT:    s_branch .LBB101_2
; VI-NEXT:  .LBB101_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16f16_to_v16bf16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB101_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB101_4
; GFX9-NEXT:  .LBB101_2: ; %cmp.true
; GFX9-NEXT:    v_mov_b32_e32 v0, 0x200
; GFX9-NEXT:    v_pk_add_f16 v7, s23, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, s22, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v5, s21, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v4, s20, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v3, s19, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v2, s18, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v1, s17, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v0, s16, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB101_3:
; GFX9-NEXT:    s_branch .LBB101_2
; GFX9-NEXT:  .LBB101_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v16f16_to_v16bf16_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s7, s19
; GFX11-NEXT:    s_mov_b32 s6, s18
; GFX11-NEXT:    s_mov_b32 s5, s17
; GFX11-NEXT:    s_mov_b32 s4, s16
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s8, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB101_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-NEXT:    s_cbranch_vccnz .LBB101_4
; GFX11-NEXT:  .LBB101_2: ; %cmp.true
; GFX11-NEXT:    v_pk_add_f16 v7, 0x200, s7 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v6, 0x200, s6 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v5, 0x200, s5 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v4, 0x200, s4 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v3, 0x200, s3 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v2, 0x200, s2 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v1, 0x200, s1 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v0, 0x200, s0 op_sel_hi:[0,1]
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB101_3:
; GFX11-NEXT:    s_branch .LBB101_2
; GFX11-NEXT:  .LBB101_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <16 x half> %a1 to <16 x bfloat>
  br label %end

cmp.false:
  %a3 = bitcast <16 x half> %a to <16 x bfloat>
  br label %end

end:
  %phi = phi <16 x bfloat> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x bfloat> %phi
}

define <16 x half> @bitcast_v16bf16_to_v16f16(<16 x bfloat> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v16bf16_to_v16f16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_and_b32_e32 v9, 0xffff0000, v7
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_and_b32_e32 v10, 0xffff0000, v6
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_and_b32_e32 v11, 0xffff0000, v5
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v12, 0xffff0000, v4
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_and_b32_e32 v13, 0xffff0000, v3
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v14, 0xffff0000, v2
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_and_b32_e32 v15, 0xffff0000, v1
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_and_b32_e32 v18, 0xffff0000, v0
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    v_mul_f32_e32 v16, 1.0, v15
; SI-NEXT:    v_mul_f32_e32 v17, 1.0, v1
; SI-NEXT:    v_mul_f32_e32 v27, 1.0, v18
; SI-NEXT:    v_mul_f32_e32 v18, 1.0, v13
; SI-NEXT:    v_mul_f32_e32 v19, 1.0, v3
; SI-NEXT:    v_mul_f32_e32 v26, 1.0, v14
; SI-NEXT:    v_mul_f32_e32 v20, 1.0, v11
; SI-NEXT:    v_mul_f32_e32 v21, 1.0, v5
; SI-NEXT:    v_mul_f32_e32 v24, 1.0, v12
; SI-NEXT:    v_mul_f32_e32 v22, 1.0, v9
; SI-NEXT:    v_mul_f32_e32 v25, 1.0, v7
; SI-NEXT:    v_mul_f32_e32 v23, 1.0, v10
; SI-NEXT:    v_mul_f32_e32 v31, 1.0, v0
; SI-NEXT:    v_mul_f32_e32 v30, 1.0, v2
; SI-NEXT:    v_mul_f32_e32 v29, 1.0, v4
; SI-NEXT:    v_mul_f32_e32 v28, 1.0, v6
; SI-NEXT:    ; implicit-def: $vgpr0
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr1
; SI-NEXT:    ; implicit-def: $vgpr2
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr3
; SI-NEXT:    ; implicit-def: $vgpr4
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr6
; SI-NEXT:    ; implicit-def: $vgpr5
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr7
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB102_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v16
; SI-NEXT:    v_alignbit_b32 v11, v1, v17, 16
; SI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v27
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v18
; SI-NEXT:    v_alignbit_b32 v12, v11, v0, 16
; SI-NEXT:    v_alignbit_b32 v10, v3, v19, 16
; SI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v26
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v20
; SI-NEXT:    v_alignbit_b32 v13, v10, v0, 16
; SI-NEXT:    v_alignbit_b32 v6, v5, v21, 16
; SI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v24
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v22
; SI-NEXT:    v_alignbit_b32 v14, v6, v0, 16
; SI-NEXT:    v_alignbit_b32 v8, v7, v25, 16
; SI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v23
; SI-NEXT:    v_alignbit_b32 v15, v8, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v27
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v26
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v24
; SI-NEXT:    v_lshrrev_b32_e32 v9, 16, v23
; SI-NEXT:    v_alignbit_b32 v0, v0, v31, 16
; SI-NEXT:    v_alignbit_b32 v2, v2, v30, 16
; SI-NEXT:    v_alignbit_b32 v4, v4, v29, 16
; SI-NEXT:    v_alignbit_b32 v9, v9, v28, 16
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr27
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr26
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr24
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr25
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr31
; SI-NEXT:    ; implicit-def: $vgpr30
; SI-NEXT:    ; implicit-def: $vgpr29
; SI-NEXT:    ; implicit-def: $vgpr28
; SI-NEXT:  .LBB102_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB102_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v27
; SI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v31
; SI-NEXT:    v_add_f32_e32 v12, 0x40c00000, v1
; SI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v12
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v26
; SI-NEXT:    v_alignbit_b32 v0, v1, v0, 16
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v30
; SI-NEXT:    v_add_f32_e32 v11, 0x40c00000, v2
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v11
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v24
; SI-NEXT:    v_alignbit_b32 v2, v2, v1, 16
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v29
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v3
; SI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v23
; SI-NEXT:    v_alignbit_b32 v4, v4, v1, 16
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v28
; SI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v5
; SI-NEXT:    v_alignbit_b32 v9, v6, v1, 16
; SI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v22
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v25
; SI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v6
; SI-NEXT:    v_and_b32_e32 v15, 0xffff0000, v5
; SI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v20
; SI-NEXT:    v_alignbit_b32 v8, v7, v1, 16
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v21
; SI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v14, 0xffff0000, v3
; SI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v18
; SI-NEXT:    v_alignbit_b32 v6, v5, v1, 16
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v19
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_alignbit_b32 v10, v3, v1, 16
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v17
; SI-NEXT:    v_and_b32_e32 v13, 0xffff0000, v11
; SI-NEXT:    v_add_f32_e32 v11, 0x40c00000, v1
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v16
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_alignbit_b32 v11, v1, v11, 16
; SI-NEXT:    v_and_b32_e32 v12, 0xffff0000, v12
; SI-NEXT:    v_alignbit_b32 v12, v11, v12, 16
; SI-NEXT:    v_alignbit_b32 v13, v10, v13, 16
; SI-NEXT:    v_alignbit_b32 v14, v6, v14, 16
; SI-NEXT:    v_alignbit_b32 v15, v8, v15, 16
; SI-NEXT:  .LBB102_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v12
; SI-NEXT:    v_or_b32_e32 v1, v11, v1
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v13
; SI-NEXT:    v_or_b32_e32 v3, v10, v3
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v14
; SI-NEXT:    v_or_b32_e32 v5, v6, v5
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v9
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v15
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_or_b32_e32 v0, v0, v12
; SI-NEXT:    v_or_b32_e32 v2, v2, v11
; SI-NEXT:    v_or_b32_e32 v4, v4, v10
; SI-NEXT:    v_or_b32_e32 v6, v6, v9
; SI-NEXT:    v_or_b32_e32 v7, v8, v7
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16bf16_to_v16f16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB102_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v0
; VI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; VI-NEXT:    v_bfe_u32 v9, v8, 16, 1
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v8
; VI-NEXT:    v_add_u32_e32 v9, vcc, 0x7fff, v9
; VI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; VI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; VI-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; VI-NEXT:    v_bfe_u32 v9, v0, 16, 1
; VI-NEXT:    s_movk_i32 s6, 0x7fff
; VI-NEXT:    v_add_u32_e32 v9, vcc, v9, v0
; VI-NEXT:    v_add_u32_e32 v9, vcc, s6, v9
; VI-NEXT:    v_or_b32_e32 v10, 0x400000, v0
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; VI-NEXT:    v_cndmask_b32_e32 v0, v9, v10, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v9, 16, v1
; VI-NEXT:    v_add_f32_e32 v9, 0x40c00000, v9
; VI-NEXT:    v_bfe_u32 v10, v9, 16, 1
; VI-NEXT:    v_add_u32_e32 v10, vcc, v10, v9
; VI-NEXT:    v_add_u32_e32 v10, vcc, s6, v10
; VI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; VI-NEXT:    v_or_b32_e32 v11, 0x400000, v9
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v9, v9
; VI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; VI-NEXT:    v_cndmask_b32_e32 v9, v10, v11, vcc
; VI-NEXT:    v_bfe_u32 v10, v1, 16, 1
; VI-NEXT:    v_add_u32_e32 v10, vcc, v10, v1
; VI-NEXT:    v_add_u32_e32 v10, vcc, s6, v10
; VI-NEXT:    v_or_b32_e32 v11, 0x400000, v1
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; VI-NEXT:    v_cndmask_b32_e32 v1, v10, v11, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v10, 16, v2
; VI-NEXT:    v_add_f32_e32 v10, 0x40c00000, v10
; VI-NEXT:    v_bfe_u32 v11, v10, 16, 1
; VI-NEXT:    v_add_u32_e32 v11, vcc, v11, v10
; VI-NEXT:    v_add_u32_e32 v11, vcc, s6, v11
; VI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; VI-NEXT:    v_or_b32_e32 v12, 0x400000, v10
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v10, v10
; VI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; VI-NEXT:    v_cndmask_b32_e32 v10, v11, v12, vcc
; VI-NEXT:    v_bfe_u32 v11, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v11, vcc, v11, v2
; VI-NEXT:    v_add_u32_e32 v11, vcc, s6, v11
; VI-NEXT:    v_or_b32_e32 v12, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v11, v12, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v11, 16, v3
; VI-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; VI-NEXT:    v_bfe_u32 v12, v11, 16, 1
; VI-NEXT:    v_add_u32_e32 v12, vcc, v12, v11
; VI-NEXT:    v_add_u32_e32 v12, vcc, s6, v12
; VI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; VI-NEXT:    v_or_b32_e32 v13, 0x400000, v11
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v11, v11
; VI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; VI-NEXT:    v_cndmask_b32_e32 v11, v12, v13, vcc
; VI-NEXT:    v_bfe_u32 v12, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v12, vcc, v12, v3
; VI-NEXT:    v_add_u32_e32 v12, vcc, s6, v12
; VI-NEXT:    v_or_b32_e32 v13, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v12, v13, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v12, 16, v4
; VI-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; VI-NEXT:    v_bfe_u32 v13, v12, 16, 1
; VI-NEXT:    v_add_u32_e32 v13, vcc, v13, v12
; VI-NEXT:    v_add_u32_e32 v13, vcc, s6, v13
; VI-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; VI-NEXT:    v_or_b32_e32 v14, 0x400000, v12
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v12, v12
; VI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; VI-NEXT:    v_cndmask_b32_e32 v12, v13, v14, vcc
; VI-NEXT:    v_bfe_u32 v13, v4, 16, 1
; VI-NEXT:    v_add_u32_e32 v13, vcc, v13, v4
; VI-NEXT:    v_add_u32_e32 v13, vcc, s6, v13
; VI-NEXT:    v_or_b32_e32 v14, 0x400000, v4
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; VI-NEXT:    v_cndmask_b32_e32 v4, v13, v14, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v13, 16, v5
; VI-NEXT:    v_add_f32_e32 v13, 0x40c00000, v13
; VI-NEXT:    v_bfe_u32 v14, v13, 16, 1
; VI-NEXT:    v_add_u32_e32 v14, vcc, v14, v13
; VI-NEXT:    v_add_u32_e32 v14, vcc, s6, v14
; VI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; VI-NEXT:    v_or_b32_e32 v15, 0x400000, v13
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v13, v13
; VI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; VI-NEXT:    v_cndmask_b32_e32 v13, v14, v15, vcc
; VI-NEXT:    v_bfe_u32 v14, v5, 16, 1
; VI-NEXT:    v_add_u32_e32 v14, vcc, v14, v5
; VI-NEXT:    v_add_u32_e32 v14, vcc, s6, v14
; VI-NEXT:    v_or_b32_e32 v15, 0x400000, v5
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; VI-NEXT:    v_cndmask_b32_e32 v5, v14, v15, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v14, 16, v6
; VI-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; VI-NEXT:    v_bfe_u32 v15, v14, 16, 1
; VI-NEXT:    v_add_u32_e32 v15, vcc, v15, v14
; VI-NEXT:    v_add_u32_e32 v15, vcc, s6, v15
; VI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; VI-NEXT:    v_or_b32_e32 v16, 0x400000, v14
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v14, v14
; VI-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; VI-NEXT:    v_cndmask_b32_e32 v14, v15, v16, vcc
; VI-NEXT:    v_bfe_u32 v15, v6, 16, 1
; VI-NEXT:    v_add_u32_e32 v15, vcc, v15, v6
; VI-NEXT:    v_add_u32_e32 v15, vcc, s6, v15
; VI-NEXT:    v_or_b32_e32 v16, 0x400000, v6
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; VI-NEXT:    v_cndmask_b32_e32 v6, v15, v16, vcc
; VI-NEXT:    v_lshlrev_b32_e32 v15, 16, v7
; VI-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; VI-NEXT:    v_bfe_u32 v16, v15, 16, 1
; VI-NEXT:    v_add_u32_e32 v16, vcc, v16, v15
; VI-NEXT:    v_add_u32_e32 v16, vcc, s6, v16
; VI-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; VI-NEXT:    v_or_b32_e32 v17, 0x400000, v15
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v15, v15
; VI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; VI-NEXT:    v_cndmask_b32_e32 v15, v16, v17, vcc
; VI-NEXT:    v_bfe_u32 v16, v7, 16, 1
; VI-NEXT:    v_add_u32_e32 v16, vcc, v16, v7
; VI-NEXT:    v_add_u32_e32 v16, vcc, 0x7fff, v16
; VI-NEXT:    v_or_b32_e32 v17, 0x400000, v7
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; VI-NEXT:    v_cndmask_b32_e32 v7, v16, v17, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; VI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_lshrrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; VI-NEXT:    v_alignbit_b32 v7, v7, v15, 16
; VI-NEXT:    v_alignbit_b32 v6, v6, v14, 16
; VI-NEXT:    v_alignbit_b32 v5, v5, v13, 16
; VI-NEXT:    v_alignbit_b32 v4, v4, v12, 16
; VI-NEXT:    v_alignbit_b32 v3, v3, v11, 16
; VI-NEXT:    v_alignbit_b32 v2, v2, v10, 16
; VI-NEXT:    v_alignbit_b32 v1, v1, v9, 16
; VI-NEXT:    v_alignbit_b32 v0, v0, v8, 16
; VI-NEXT:  .LBB102_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16bf16_to_v16f16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB102_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v0
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    s_movk_i32 s6, 0x7fff
; GFX9-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v9, v10, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v0, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v0, s6
; GFX9-NEXT:    v_or_b32_e32 v10, 0x400000, v0
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v0, v9, v10, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v9, 16, v1
; GFX9-NEXT:    v_add_f32_e32 v9, 0x40c00000, v9
; GFX9-NEXT:    v_bfe_u32 v10, v9, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; GFX9-NEXT:    v_add3_u32 v10, v10, v9, s6
; GFX9-NEXT:    v_or_b32_e32 v11, 0x400000, v9
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v9, v9
; GFX9-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v9, v10, v11, vcc
; GFX9-NEXT:    v_bfe_u32 v10, v1, 16, 1
; GFX9-NEXT:    v_add3_u32 v10, v10, v1, s6
; GFX9-NEXT:    v_or_b32_e32 v11, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v10, v11, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v10, 16, v2
; GFX9-NEXT:    v_add_f32_e32 v10, 0x40c00000, v10
; GFX9-NEXT:    v_bfe_u32 v11, v10, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; GFX9-NEXT:    v_add3_u32 v11, v11, v10, s6
; GFX9-NEXT:    v_or_b32_e32 v12, 0x400000, v10
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v10, v10
; GFX9-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v10, v11, v12, vcc
; GFX9-NEXT:    v_bfe_u32 v11, v2, 16, 1
; GFX9-NEXT:    v_add3_u32 v11, v11, v2, s6
; GFX9-NEXT:    v_or_b32_e32 v12, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v11, v12, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v11, 16, v3
; GFX9-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; GFX9-NEXT:    v_bfe_u32 v12, v11, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; GFX9-NEXT:    v_add3_u32 v12, v12, v11, s6
; GFX9-NEXT:    v_or_b32_e32 v13, 0x400000, v11
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v11, v11
; GFX9-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GFX9-NEXT:    v_cndmask_b32_e32 v11, v12, v13, vcc
; GFX9-NEXT:    v_bfe_u32 v12, v3, 16, 1
; GFX9-NEXT:    v_add3_u32 v12, v12, v3, s6
; GFX9-NEXT:    v_or_b32_e32 v13, 0x400000, v3
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; GFX9-NEXT:    v_cndmask_b32_e32 v3, v12, v13, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v12, 16, v4
; GFX9-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; GFX9-NEXT:    v_bfe_u32 v13, v12, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; GFX9-NEXT:    v_add3_u32 v13, v13, v12, s6
; GFX9-NEXT:    v_or_b32_e32 v14, 0x400000, v12
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v12, v12
; GFX9-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; GFX9-NEXT:    v_cndmask_b32_e32 v12, v13, v14, vcc
; GFX9-NEXT:    v_bfe_u32 v13, v4, 16, 1
; GFX9-NEXT:    v_add3_u32 v13, v13, v4, s6
; GFX9-NEXT:    v_or_b32_e32 v14, 0x400000, v4
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; GFX9-NEXT:    v_cndmask_b32_e32 v4, v13, v14, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v13, 16, v5
; GFX9-NEXT:    v_add_f32_e32 v13, 0x40c00000, v13
; GFX9-NEXT:    v_bfe_u32 v14, v13, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; GFX9-NEXT:    v_add3_u32 v14, v14, v13, s6
; GFX9-NEXT:    v_or_b32_e32 v15, 0x400000, v13
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v13, v13
; GFX9-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v13, v14, v15, vcc
; GFX9-NEXT:    v_bfe_u32 v14, v5, 16, 1
; GFX9-NEXT:    v_add3_u32 v14, v14, v5, s6
; GFX9-NEXT:    v_or_b32_e32 v15, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v5, v14, v15, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v14, 16, v6
; GFX9-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; GFX9-NEXT:    v_bfe_u32 v15, v14, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; GFX9-NEXT:    v_add3_u32 v15, v15, v14, s6
; GFX9-NEXT:    v_or_b32_e32 v16, 0x400000, v14
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v14, v14
; GFX9-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GFX9-NEXT:    v_cndmask_b32_e32 v14, v15, v16, vcc
; GFX9-NEXT:    v_bfe_u32 v15, v6, 16, 1
; GFX9-NEXT:    v_add3_u32 v15, v15, v6, s6
; GFX9-NEXT:    v_or_b32_e32 v16, 0x400000, v6
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; GFX9-NEXT:    v_cndmask_b32_e32 v6, v15, v16, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v15, 16, v7
; GFX9-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; GFX9-NEXT:    v_bfe_u32 v16, v15, 16, 1
; GFX9-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; GFX9-NEXT:    v_add3_u32 v16, v16, v15, s6
; GFX9-NEXT:    v_or_b32_e32 v17, 0x400000, v15
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v15, v15
; GFX9-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GFX9-NEXT:    v_cndmask_b32_e32 v15, v16, v17, vcc
; GFX9-NEXT:    v_bfe_u32 v16, v7, 16, 1
; GFX9-NEXT:    v_add3_u32 v16, v16, v7, s6
; GFX9-NEXT:    v_or_b32_e32 v17, 0x400000, v7
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; GFX9-NEXT:    v_cndmask_b32_e32 v7, v16, v17, vcc
; GFX9-NEXT:    s_mov_b32 s6, 0x7060302
; GFX9-NEXT:    v_perm_b32 v7, v7, v15, s6
; GFX9-NEXT:    v_perm_b32 v6, v6, v14, s6
; GFX9-NEXT:    v_perm_b32 v5, v5, v13, s6
; GFX9-NEXT:    v_perm_b32 v4, v4, v12, s6
; GFX9-NEXT:    v_perm_b32 v3, v3, v11, s6
; GFX9-NEXT:    v_perm_b32 v2, v2, v10, s6
; GFX9-NEXT:    v_perm_b32 v1, v1, v9, s6
; GFX9-NEXT:    v_perm_b32 v0, v0, v8, s6
; GFX9-NEXT:  .LBB102_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v16bf16_to_v16f16:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v16, v7 :: v_dual_mov_b32 v15, v6
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v14, v5 :: v_dual_mov_b32 v13, v4
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v12, v3 :: v_dual_mov_b32 v11, v2
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v10, v1 :: v_dual_mov_b32 v9, v0
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB102_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB102_4
; GFX11-TRUE16-NEXT:  .LBB102_2: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB102_3: ; %cmp.false
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v0, v9 :: v_dual_mov_b32 v1, v10
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v2, v11 :: v_dual_mov_b32 v3, v12
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v4, v13 :: v_dual_mov_b32 v5, v14
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v6, v15 :: v_dual_mov_b32 v7, v16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB102_2
; GFX11-TRUE16-NEXT:  .LBB102_4: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v2, 0xffff0000, v10
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v4, 0xffff0000, v11
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v3, 16, v10
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v18, 0xffff0000, v15
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GFX11-TRUE16-NEXT:    v_bfe_u32 v8, v2, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v10, 0x400000, v2
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add3_u32 v8, v8, v2, 0x7fff
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v0, 0xffff0000, v9
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v0, 0x40c00000, v0 :: v_dual_lshlrev_b32 v1, 16, v9
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v5, v0, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v6, 0x400000, v0
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-TRUE16-NEXT:    v_add3_u32 v5, v5, v0, 0x7fff
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v1, 0x40c00000, v1 :: v_dual_cndmask_b32 v0, v5, v6
; GFX11-TRUE16-NEXT:    v_bfe_u32 v7, v1, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v9, 0x400000, v1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v6, 0xffff0000, v12
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add3_u32 v7, v7, v1, 0x7fff
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v6, 0x40c00000, v6 :: v_dual_cndmask_b32 v9, v7, v9
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v2, 0x40c00000, v4 :: v_dual_add_f32 v3, 0x40c00000, v3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v11
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v11, 16, v12
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v8, v10, vcc_lo
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v8, v2, 16, 1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v5, v3, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v7, 0x400000, v3
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v12, 0xffff0000, v13
; GFX11-TRUE16-NEXT:    v_add3_u32 v5, v5, v3, 0x7fff
; GFX11-TRUE16-NEXT:    v_add3_u32 v3, v8, v2, 0x7fff
; GFX11-TRUE16-NEXT:    v_bfe_u32 v8, v6, 16, 1
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.l, v9.h
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v10, v5, v7, vcc_lo
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, 0x400000, v2
; GFX11-TRUE16-NEXT:    v_bfe_u32 v7, v4, 16, 1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v2, v3, v5, vcc_lo
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_add3_u32 v3, v7, v4, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, 0x400000, v4
; GFX11-TRUE16-NEXT:    v_add3_u32 v7, v8, v6, 0x7fff
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v8, 0x40c00000, v11
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v11, 0x400000, v6
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_3) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v4, v8, 16, 1
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v17, v3, v5, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v5, 0x40c00000, v12 :: v_dual_lshlrev_b32 v6, 16, v13
; GFX11-TRUE16-NEXT:    v_add3_u32 v4, v4, v8, 0x7fff
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.l, v17.h
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v3, v7, v11, vcc_lo
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v7, 0xffff0000, v14
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v11, 0x400000, v8
; GFX11-TRUE16-NEXT:    v_bfe_u32 v12, v5, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v7, 0x40c00000, v7 :: v_dual_lshlrev_b32 v14, 16, v14
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v1.l, v10.h
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v8, v4, v11, vcc_lo
; GFX11-TRUE16-NEXT:    v_add3_u32 v4, v12, v5, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v11, 0x400000, v5
; GFX11-TRUE16-NEXT:    v_bfe_u32 v12, v6, 16, 1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-TRUE16-NEXT:    v_bfe_u32 v13, v7, 16, 1
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v3.l, v8.h
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_add3_u32 v5, v12, v6, 0x7fff
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v4, v4, v11, vcc_lo
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v11, 0x400000, v6
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-TRUE16-NEXT:    v_add3_u32 v12, v13, v7, 0x7fff
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v13, 0x40c00000, v14
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v14, 0x400000, v7
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v11, v5, v11, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v6, v13, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v7, 0x40c00000, v18
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v4.l, v11.h
; GFX11-TRUE16-NEXT:    v_dual_cndmask_b32 v5, v12, v14 :: v_dual_lshlrev_b32 v12, 16, v15
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_add3_u32 v6, v6, v13, 0x7fff
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v14, 16, v16
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v15, 0x400000, v13
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v13, v13
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; GFX11-TRUE16-NEXT:    v_bfe_u32 v18, v7, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v14, 0x40c00000, v14
; GFX11-TRUE16-NEXT:    v_dual_cndmask_b32 v13, v6, v15 :: v_dual_and_b32 v16, 0xffff0000, v16
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v6, v12, 16, 1
; GFX11-TRUE16-NEXT:    v_add3_u32 v15, v18, v7, 0x7fff
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v18, v14, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v20, 0x400000, v12
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v12, v12
; GFX11-TRUE16-NEXT:    v_add3_u32 v6, v6, v12, 0x7fff
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v16, 0x40c00000, v16
; GFX11-TRUE16-NEXT:    v_add3_u32 v18, v18, v14, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v22, 0x400000, v14
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v19, 0x400000, v7
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v12, v6, v20, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v14, v14
; GFX11-TRUE16-NEXT:    v_bfe_u32 v21, v16, 16, 1
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v5.l, v13.h
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v14, v18, v22, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_4) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_add3_u32 v20, v21, v16, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v21, 0x400000, v16
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v6, v15, v19, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v16, v16
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v6.l, v12.h
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v7, v20, v21, vcc_lo
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v7.l, v14.h
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v16bf16_to_v16f16:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-FAKE16-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB102_2
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v9, 16, v1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v9, 0x40c00000, v9 :: v_dual_lshlrev_b32 v8, 16, v0
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v9, 16, 1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v11, v8, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v14, 0x400000, v8
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_add3_u32 v13, v13, v9, 0x7fff
; GFX11-FAKE16-NEXT:    v_add3_u32 v11, v11, v8, 0x7fff
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v8, v11, v14 :: v_dual_and_b32 v1, 0xffff0000, v1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, 0x400000, v9
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v1, 0x40c00000, v1 :: v_dual_lshlrev_b32 v14, 16, v3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xffff0000, v3
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v14, 0x40c00000, v14 :: v_dual_add_f32 v3, 0x40c00000, v3
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_2) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v12, v0, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v15, 0x400000, v0
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v16, 0x400000, v3
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_add3_u32 v12, v12, v0, 0x7fff
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v0, v12, v15 :: v_dual_lshlrev_b32 v15, 16, v4
; GFX11-FAKE16-NEXT:    v_bfe_u32 v12, v1, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xffff0000, v4
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v0, v8, 0x7060302
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v15, 0x40c00000, v15
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v9, v13, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_add3_u32 v11, v12, v1, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, 0x400000, v1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v10, 16, v2
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff0000, v2
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v17, 0x400000, v15
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v1, v11, v12 :: v_dual_add_f32 v10, 0x40c00000, v10
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v18, v4, 16, 1
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v1, v9, 0x7060302
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v10, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, 0x400000, v10
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-FAKE16-NEXT:    v_add3_u32 v11, v13, v10, 0x7fff
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v2, 16, 1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v10, v11, v12, vcc_lo
; GFX11-FAKE16-NEXT:    v_add3_u32 v11, v13, v2, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, 0x400000, v2
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v14, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v2, v11, v12, vcc_lo
; GFX11-FAKE16-NEXT:    v_add3_u32 v11, v13, v14, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, 0x400000, v14
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v14, v14
; GFX11-FAKE16-NEXT:    v_bfe_u32 v14, v15, 16, 1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v3, 16, 1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v11, v11, v12 :: v_dual_lshlrev_b32 v12, 16, v5
; GFX11-FAKE16-NEXT:    v_add3_u32 v14, v14, v15, 0x7fff
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v15, v15
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xffff0000, v5
; GFX11-FAKE16-NEXT:    v_add3_u32 v15, v18, v4, 0x7fff
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v12, 0x40c00000, v12
; GFX11-FAKE16-NEXT:    v_add3_u32 v13, v13, v3, 0x7fff
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v14, v14, v17, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v5, 0x40c00000, v5
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v2, v10, 0x7060302
; GFX11-FAKE16-NEXT:    v_bfe_u32 v19, v12, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v20, 0x400000, v12
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v21, v5, 16, 1
; GFX11-FAKE16-NEXT:    v_add3_u32 v18, v19, v12, 0x7fff
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v19, 16, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v17, 0x400000, v4
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v4, v15, v17 :: v_dual_add_f32 v15, 0x40c00000, v19
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v12, v12
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GFX11-FAKE16-NEXT:    v_add3_u32 v17, v21, v5, 0x7fff
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v19, v15, 16, 1
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v12, v18, v20, vcc_lo
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v18, 16, v7
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v21, 0x400000, v15
; GFX11-FAKE16-NEXT:    v_add3_u32 v19, v19, v15, 0x7fff
; GFX11-FAKE16-NEXT:    v_bfe_u32 v22, v6, 16, 1
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v18, 0x40c00000, v18
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v15, v15
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v20, 0x400000, v5
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v23, v18, 16, 1
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v15, v19, v21, vcc_lo
; GFX11-FAKE16-NEXT:    v_add3_u32 v21, v22, v6, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v22, 0x400000, v6
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-FAKE16-NEXT:    v_bfe_u32 v19, v7, 16, 1
; GFX11-FAKE16-NEXT:    v_add3_u32 v23, v23, v18, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v24, 0x400000, v18
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v25, 0x400000, v7
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v6, v21, v22, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v18, v18
; GFX11-FAKE16-NEXT:    v_add3_u32 v19, v19, v7, 0x7fff
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v6, v15, 0x7060302
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v18, v23, v24, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v7, v19, v25, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_3) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v7, v18, 0x7060302
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v5, v17, v20, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v4, v14, 0x7060302
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v5, v12, 0x7060302
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v3, v13, v16, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v3, v11, 0x7060302
; GFX11-FAKE16-NEXT:  .LBB102_2: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x bfloat> %a, splat (bfloat 0xR40C0)
  %a2 = bitcast <16 x bfloat> %a1 to <16 x half>
  br label %end

cmp.false:
  %a3 = bitcast <16 x bfloat> %a to <16 x half>
  br label %end

end:
  %phi = phi <16 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x half> %phi
}

define inreg <16 x half> @bitcast_v16bf16_to_v16f16_scalar(<16 x bfloat> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v16bf16_to_v16f16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_and_b32 s4, s23, 0xffff0000
; SI-NEXT:    s_lshl_b32 s5, s23, 16
; SI-NEXT:    s_and_b32 s6, s22, 0xffff0000
; SI-NEXT:    s_lshl_b32 s7, s22, 16
; SI-NEXT:    s_and_b32 s8, s21, 0xffff0000
; SI-NEXT:    s_lshl_b32 s9, s21, 16
; SI-NEXT:    s_and_b32 s10, s20, 0xffff0000
; SI-NEXT:    s_lshl_b32 s11, s20, 16
; SI-NEXT:    s_and_b32 s12, s19, 0xffff0000
; SI-NEXT:    s_lshl_b32 s13, s19, 16
; SI-NEXT:    s_and_b32 s14, s18, 0xffff0000
; SI-NEXT:    s_lshl_b32 s15, s18, 16
; SI-NEXT:    s_and_b32 s18, s17, 0xffff0000
; SI-NEXT:    s_lshl_b32 s17, s17, 16
; SI-NEXT:    s_and_b32 s19, s16, 0xffff0000
; SI-NEXT:    s_lshl_b32 s16, s16, 16
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    v_mul_f32_e64 v51, 1.0, s19
; SI-NEXT:    v_mul_f32_e64 v36, 1.0, s18
; SI-NEXT:    v_mul_f32_e64 v0, 1.0, s17
; SI-NEXT:    v_mul_f32_e64 v50, 1.0, s14
; SI-NEXT:    v_mul_f32_e64 v37, 1.0, s12
; SI-NEXT:    v_mul_f32_e64 v19, 1.0, s13
; SI-NEXT:    v_mul_f32_e64 v49, 1.0, s10
; SI-NEXT:    v_mul_f32_e64 v38, 1.0, s8
; SI-NEXT:    v_mul_f32_e64 v17, 1.0, s9
; SI-NEXT:    v_mul_f32_e64 v48, 1.0, s6
; SI-NEXT:    v_mul_f32_e64 v39, 1.0, s4
; SI-NEXT:    v_mul_f32_e64 v15, 1.0, s5
; SI-NEXT:    v_mul_f32_e64 v31, 1.0, s16
; SI-NEXT:    v_mul_f32_e64 v29, 1.0, s15
; SI-NEXT:    v_mul_f32_e64 v27, 1.0, s11
; SI-NEXT:    v_mul_f32_e64 v24, 1.0, s7
; SI-NEXT:    s_cbranch_scc0 .LBB103_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_lshrrev_b32_e32 v20, 16, v37
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v36
; SI-NEXT:    v_lshr_b64 v[3:4], v[19:20], 16
; SI-NEXT:    v_lshrrev_b32_e32 v18, 16, v38
; SI-NEXT:    v_lshrrev_b32_e32 v16, 16, v39
; SI-NEXT:    v_lshr_b64 v[13:14], v[0:1], 16
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v50
; SI-NEXT:    v_lshr_b64 v[10:11], v[17:18], 16
; SI-NEXT:    v_lshr_b64 v[7:8], v[15:16], 16
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v50
; SI-NEXT:    v_and_b32_e32 v12, 0xffff0000, v51
; SI-NEXT:    v_and_b32_e32 v9, 0xffff0000, v49
; SI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v48
; SI-NEXT:    v_lshrrev_b32_e32 v32, 16, v51
; SI-NEXT:    v_lshrrev_b32_e32 v28, 16, v49
; SI-NEXT:    v_lshrrev_b32_e32 v25, 16, v48
; SI-NEXT:    v_lshr_b64 v[33:34], v[2:3], 16
; SI-NEXT:    v_lshr_b64 v[21:22], v[29:30], 16
; SI-NEXT:    v_lshr_b64 v[11:12], v[12:13], 16
; SI-NEXT:    v_lshr_b64 v[8:9], v[9:10], 16
; SI-NEXT:    v_lshr_b64 v[34:35], v[6:7], 16
; SI-NEXT:    v_lshr_b64 v[5:6], v[31:32], 16
; SI-NEXT:    v_lshr_b64 v[22:23], v[27:28], 16
; SI-NEXT:    v_lshr_b64 v[25:26], v[24:25], 16
; SI-NEXT:    s_cbranch_execnz .LBB103_3
; SI-NEXT:  .LBB103_2: ; %cmp.true
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v51
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v31
; SI-NEXT:    v_add_f32_e32 v12, 0x40c00000, v2
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v12
; SI-NEXT:    v_lshr_b64 v[5:6], v[1:2], 16
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v50
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v29
; SI-NEXT:    v_add_f32_e32 v13, 0x40c00000, v2
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v13
; SI-NEXT:    v_lshr_b64 v[21:22], v[1:2], 16
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v49
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v27
; SI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v2
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v3
; SI-NEXT:    v_lshr_b64 v[22:23], v[1:2], 16
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v48
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v24
; SI-NEXT:    v_add_f32_e32 v4, 0x40c00000, v2
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v4
; SI-NEXT:    v_lshr_b64 v[25:26], v[1:2], 16
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v15
; SI-NEXT:    v_add_f32_e32 v15, 0x40c00000, v1
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v39
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_lshrrev_b32_e32 v16, 16, v1
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v17
; SI-NEXT:    v_add_f32_e32 v17, 0x40c00000, v1
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v38
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_lshrrev_b32_e32 v18, 16, v1
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v19
; SI-NEXT:    v_add_f32_e32 v19, 0x40c00000, v1
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v37
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_lshrrev_b32_e32 v20, 16, v1
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v36
; SI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_and_b32_e32 v6, 0xffff0000, v4
; SI-NEXT:    v_and_b32_e32 v9, 0xffff0000, v3
; SI-NEXT:    v_lshr_b64 v[3:4], v[19:20], 16
; SI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_lshr_b64 v[7:8], v[15:16], 16
; SI-NEXT:    v_lshr_b64 v[10:11], v[17:18], 16
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v13
; SI-NEXT:    v_lshr_b64 v[13:14], v[0:1], 16
; SI-NEXT:    v_and_b32_e32 v12, 0xffff0000, v12
; SI-NEXT:    v_lshr_b64 v[33:34], v[2:3], 16
; SI-NEXT:    v_lshr_b64 v[11:12], v[12:13], 16
; SI-NEXT:    v_lshr_b64 v[8:9], v[9:10], 16
; SI-NEXT:    v_lshr_b64 v[34:35], v[6:7], 16
; SI-NEXT:  .LBB103_3: ; %end
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v13
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v11
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_or_b32_e32 v0, v0, v4
; SI-NEXT:    v_or_b32_e32 v1, v2, v1
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v21
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v33
; SI-NEXT:    v_or_b32_e32 v2, v2, v4
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v20
; SI-NEXT:    v_or_b32_e32 v3, v3, v4
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v22
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v8
; SI-NEXT:    v_or_b32_e32 v4, v4, v5
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v10
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v18
; SI-NEXT:    v_or_b32_e32 v5, v5, v6
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v25
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v34
; SI-NEXT:    v_or_b32_e32 v6, v6, v8
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v16
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB103_4:
; SI-NEXT:    ; implicit-def: $vgpr5
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr3
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr25
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr7
; SI-NEXT:    s_branch .LBB103_2
;
; VI-LABEL: bitcast_v16bf16_to_v16f16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB103_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB103_4
; VI-NEXT:  .LBB103_2: ; %cmp.true
; VI-NEXT:    s_lshl_b32 s4, s16, 16
; VI-NEXT:    v_mov_b32_e32 v10, 0x40c00000
; VI-NEXT:    v_add_f32_e32 v0, s4, v10
; VI-NEXT:    v_bfe_u32 v1, v0, 16, 1
; VI-NEXT:    v_add_u32_e32 v1, vcc, v1, v0
; VI-NEXT:    v_add_u32_e32 v1, vcc, 0x7fff, v1
; VI-NEXT:    v_or_b32_e32 v2, 0x400000, v0
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; VI-NEXT:    s_and_b32 s4, s16, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v0, v1, v2, vcc
; VI-NEXT:    v_add_f32_e32 v1, s4, v10
; VI-NEXT:    v_bfe_u32 v2, v1, 16, 1
; VI-NEXT:    v_add_u32_e32 v2, vcc, v2, v1
; VI-NEXT:    v_add_u32_e32 v2, vcc, 0x7fff, v2
; VI-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; VI-NEXT:    s_lshl_b32 s4, s17, 16
; VI-NEXT:    v_cndmask_b32_e32 v1, v2, v3, vcc
; VI-NEXT:    v_add_f32_e32 v2, s4, v10
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    s_and_b32 s4, s17, 0xffff0000
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_add_f32_e32 v2, s4, v10
; VI-NEXT:    v_cndmask_b32_e32 v8, v3, v4, vcc
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; VI-NEXT:    s_lshl_b32 s4, s18, 16
; VI-NEXT:    v_lshrrev_b32_e32 v9, 16, v2
; VI-NEXT:    v_add_f32_e32 v2, s4, v10
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    s_and_b32 s4, s18, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; VI-NEXT:    v_add_f32_e32 v3, s4, v10
; VI-NEXT:    v_bfe_u32 v4, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v4, vcc, v4, v3
; VI-NEXT:    v_add_u32_e32 v4, vcc, 0x7fff, v4
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    s_lshl_b32 s4, s19, 16
; VI-NEXT:    v_cndmask_b32_e32 v3, v4, v5, vcc
; VI-NEXT:    v_add_f32_e32 v4, s4, v10
; VI-NEXT:    v_bfe_u32 v5, v4, 16, 1
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v4
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    s_and_b32 s4, s19, 0xffff0000
; VI-NEXT:    v_or_b32_e32 v6, 0x400000, v4
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; VI-NEXT:    v_add_f32_e32 v4, s4, v10
; VI-NEXT:    v_cndmask_b32_e32 v11, v5, v6, vcc
; VI-NEXT:    v_bfe_u32 v5, v4, 16, 1
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v4
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    v_or_b32_e32 v6, 0x400000, v4
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; VI-NEXT:    v_cndmask_b32_e32 v4, v5, v6, vcc
; VI-NEXT:    s_lshl_b32 s4, s20, 16
; VI-NEXT:    v_lshrrev_b32_e32 v12, 16, v4
; VI-NEXT:    v_add_f32_e32 v4, s4, v10
; VI-NEXT:    v_bfe_u32 v5, v4, 16, 1
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v4
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    v_or_b32_e32 v6, 0x400000, v4
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; VI-NEXT:    s_and_b32 s4, s20, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v4, v5, v6, vcc
; VI-NEXT:    v_add_f32_e32 v5, s4, v10
; VI-NEXT:    v_bfe_u32 v6, v5, 16, 1
; VI-NEXT:    v_add_u32_e32 v6, vcc, v6, v5
; VI-NEXT:    v_add_u32_e32 v6, vcc, 0x7fff, v6
; VI-NEXT:    s_and_b32 s5, s21, 0xffff0000
; VI-NEXT:    v_or_b32_e32 v7, 0x400000, v5
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; VI-NEXT:    v_add_f32_e32 v13, s5, v10
; VI-NEXT:    s_lshl_b32 s5, s22, 16
; VI-NEXT:    v_cndmask_b32_e32 v5, v6, v7, vcc
; VI-NEXT:    v_add_f32_e32 v6, s5, v10
; VI-NEXT:    v_bfe_u32 v7, v6, 16, 1
; VI-NEXT:    v_add_u32_e32 v7, vcc, v7, v6
; VI-NEXT:    v_add_u32_e32 v7, vcc, 0x7fff, v7
; VI-NEXT:    v_or_b32_e32 v14, 0x400000, v6
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; VI-NEXT:    s_and_b32 s5, s22, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v6, v7, v14, vcc
; VI-NEXT:    v_add_f32_e32 v7, s5, v10
; VI-NEXT:    v_bfe_u32 v14, v7, 16, 1
; VI-NEXT:    v_add_u32_e32 v14, vcc, v14, v7
; VI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_add_u32_e32 v14, vcc, 0x7fff, v14
; VI-NEXT:    v_or_b32_e32 v15, 0x400000, v7
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; VI-NEXT:    v_lshrrev_b64 v[4:5], 16, v[4:5]
; VI-NEXT:    v_cndmask_b32_e32 v7, v14, v15, vcc
; VI-NEXT:    v_bfe_u32 v5, v13, 16, 1
; VI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v13
; VI-NEXT:    s_lshl_b32 s4, s21, 16
; VI-NEXT:    v_lshrrev_b64 v[6:7], 16, v[6:7]
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    v_or_b32_e32 v7, 0x400000, v13
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v13, v13
; VI-NEXT:    v_add_f32_e32 v13, s4, v10
; VI-NEXT:    v_cndmask_b32_e32 v5, v5, v7, vcc
; VI-NEXT:    v_bfe_u32 v7, v13, 16, 1
; VI-NEXT:    v_add_u32_e32 v7, vcc, v7, v13
; VI-NEXT:    v_add_u32_e32 v7, vcc, 0x7fff, v7
; VI-NEXT:    v_or_b32_e32 v14, 0x400000, v13
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v13, v13
; VI-NEXT:    s_and_b32 s4, s23, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v13, v7, v14, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v14, 16, v5
; VI-NEXT:    v_add_f32_e32 v5, s4, v10
; VI-NEXT:    v_bfe_u32 v7, v5, 16, 1
; VI-NEXT:    v_add_u32_e32 v7, vcc, v7, v5
; VI-NEXT:    v_add_u32_e32 v7, vcc, 0x7fff, v7
; VI-NEXT:    v_or_b32_e32 v15, 0x400000, v5
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; VI-NEXT:    s_lshl_b32 s4, s23, 16
; VI-NEXT:    v_cndmask_b32_e32 v5, v7, v15, vcc
; VI-NEXT:    v_add_f32_e32 v7, s4, v10
; VI-NEXT:    v_bfe_u32 v10, v7, 16, 1
; VI-NEXT:    v_add_u32_e32 v10, vcc, v10, v7
; VI-NEXT:    v_add_u32_e32 v10, vcc, 0x7fff, v10
; VI-NEXT:    v_or_b32_e32 v15, 0x400000, v7
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; VI-NEXT:    v_cndmask_b32_e32 v15, v10, v15, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v16, 16, v5
; VI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_lshrrev_b64 v[15:16], 16, v[15:16]
; VI-NEXT:    v_lshrrev_b64 v[13:14], 16, v[13:14]
; VI-NEXT:    v_lshrrev_b64 v[10:11], 16, v[11:12]
; VI-NEXT:    v_lshrrev_b64 v[7:8], 16, v[8:9]
; VI-NEXT:    v_lshrrev_b64 v[2:3], 16, v[2:3]
; VI-NEXT:    v_lshrrev_b64 v[0:1], 16, v[0:1]
; VI-NEXT:    v_mov_b32_e32 v1, v7
; VI-NEXT:    v_mov_b32_e32 v3, v10
; VI-NEXT:    v_mov_b32_e32 v5, v13
; VI-NEXT:    v_mov_b32_e32 v7, v15
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB103_3:
; VI-NEXT:    s_branch .LBB103_2
; VI-NEXT:  .LBB103_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16bf16_to_v16f16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB103_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB103_4
; GFX9-NEXT:  .LBB103_2: ; %cmp.true
; GFX9-NEXT:    s_and_b32 s4, s16, 0xffff0000
; GFX9-NEXT:    v_mov_b32_e32 v1, 0x40c00000
; GFX9-NEXT:    v_add_f32_e32 v0, s4, v1
; GFX9-NEXT:    v_bfe_u32 v2, v0, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v0
; GFX9-NEXT:    s_lshl_b32 s4, s16, 16
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v3, 0x400000, v0
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; GFX9-NEXT:    v_add_f32_e32 v0, s4, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v2, v3, vcc
; GFX9-NEXT:    v_bfe_u32 v3, v0, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v3, v3, v0
; GFX9-NEXT:    v_add_u32_e32 v3, 0x7fff, v3
; GFX9-NEXT:    v_or_b32_e32 v4, 0x400000, v0
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; GFX9-NEXT:    s_and_b32 s4, s17, 0xffff0000
; GFX9-NEXT:    v_cndmask_b32_e32 v0, v3, v4, vcc
; GFX9-NEXT:    v_add_f32_e32 v3, s4, v1
; GFX9-NEXT:    v_bfe_u32 v4, v3, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v4, v4, v3
; GFX9-NEXT:    v_add_u32_e32 v4, 0x7fff, v4
; GFX9-NEXT:    v_or_b32_e32 v5, 0x400000, v3
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; GFX9-NEXT:    s_lshl_b32 s4, s17, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v3, v4, v5, vcc
; GFX9-NEXT:    v_add_f32_e32 v4, s4, v1
; GFX9-NEXT:    v_bfe_u32 v5, v4, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v5, v5, v4
; GFX9-NEXT:    s_and_b32 s4, s18, 0xffff0000
; GFX9-NEXT:    v_add_u32_e32 v5, 0x7fff, v5
; GFX9-NEXT:    v_or_b32_e32 v6, 0x400000, v4
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; GFX9-NEXT:    v_add_f32_e32 v4, s4, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v8, v5, v6, vcc
; GFX9-NEXT:    v_bfe_u32 v5, v4, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v5, v5, v4
; GFX9-NEXT:    v_add_u32_e32 v5, 0x7fff, v5
; GFX9-NEXT:    v_or_b32_e32 v6, 0x400000, v4
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v4, v4
; GFX9-NEXT:    s_lshl_b32 s4, s18, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v4, v5, v6, vcc
; GFX9-NEXT:    v_add_f32_e32 v5, s4, v1
; GFX9-NEXT:    v_bfe_u32 v6, v5, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v6, v6, v5
; GFX9-NEXT:    s_and_b32 s4, s19, 0xffff0000
; GFX9-NEXT:    v_add_u32_e32 v6, 0x7fff, v6
; GFX9-NEXT:    v_or_b32_e32 v7, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    v_add_f32_e32 v5, s4, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v9, v6, v7, vcc
; GFX9-NEXT:    v_bfe_u32 v6, v5, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v6, v6, v5
; GFX9-NEXT:    s_lshl_b32 s4, s19, 16
; GFX9-NEXT:    v_add_u32_e32 v6, 0x7fff, v6
; GFX9-NEXT:    v_or_b32_e32 v7, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    v_add_f32_e32 v5, s4, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v10, v6, v7, vcc
; GFX9-NEXT:    v_bfe_u32 v6, v5, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v6, v6, v5
; GFX9-NEXT:    s_and_b32 s5, s22, 0xffff0000
; GFX9-NEXT:    v_add_u32_e32 v6, 0x7fff, v6
; GFX9-NEXT:    v_or_b32_e32 v7, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    v_add_f32_e32 v5, s5, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v11, v6, v7, vcc
; GFX9-NEXT:    v_bfe_u32 v6, v5, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v6, v6, v5
; GFX9-NEXT:    v_add_u32_e32 v6, 0x7fff, v6
; GFX9-NEXT:    v_or_b32_e32 v7, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    s_lshl_b32 s5, s22, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v5, v6, v7, vcc
; GFX9-NEXT:    v_add_f32_e32 v6, s5, v1
; GFX9-NEXT:    v_bfe_u32 v7, v6, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v7, v7, v6
; GFX9-NEXT:    v_add_u32_e32 v7, 0x7fff, v7
; GFX9-NEXT:    v_or_b32_e32 v12, 0x400000, v6
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; GFX9-NEXT:    s_and_b32 s5, s23, 0xffff0000
; GFX9-NEXT:    v_cndmask_b32_e32 v6, v7, v12, vcc
; GFX9-NEXT:    v_add_f32_e32 v7, s5, v1
; GFX9-NEXT:    v_bfe_u32 v12, v7, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v12, v12, v7
; GFX9-NEXT:    v_add_u32_e32 v12, 0x7fff, v12
; GFX9-NEXT:    v_or_b32_e32 v13, 0x400000, v7
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; GFX9-NEXT:    s_lshl_b32 s5, s23, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v7, v12, v13, vcc
; GFX9-NEXT:    v_add_f32_e32 v12, s5, v1
; GFX9-NEXT:    v_bfe_u32 v13, v12, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v13, v13, v12
; GFX9-NEXT:    v_add_u32_e32 v13, 0x7fff, v13
; GFX9-NEXT:    v_or_b32_e32 v14, 0x400000, v12
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v12, v12
; GFX9-NEXT:    v_cndmask_b32_e32 v12, v13, v14, vcc
; GFX9-NEXT:    v_mov_b32_e32 v13, 0xffff
; GFX9-NEXT:    s_and_b32 s4, s21, 0xffff0000
; GFX9-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; GFX9-NEXT:    v_and_b32_sdwa v6, v13, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; GFX9-NEXT:    v_and_b32_sdwa v12, v13, v12 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    v_lshl_or_b32 v6, v5, 16, v6
; GFX9-NEXT:    v_add_f32_e32 v5, s4, v1
; GFX9-NEXT:    v_lshl_or_b32 v7, v7, 16, v12
; GFX9-NEXT:    v_bfe_u32 v12, v5, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v12, v12, v5
; GFX9-NEXT:    v_add_u32_e32 v12, 0x7fff, v12
; GFX9-NEXT:    v_or_b32_e32 v14, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    s_lshl_b32 s4, s21, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v5, v12, v14, vcc
; GFX9-NEXT:    v_add_f32_e32 v12, s4, v1
; GFX9-NEXT:    v_bfe_u32 v14, v12, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v14, v14, v12
; GFX9-NEXT:    v_add_u32_e32 v14, 0x7fff, v14
; GFX9-NEXT:    v_or_b32_e32 v15, 0x400000, v12
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v12, v12
; GFX9-NEXT:    v_cndmask_b32_e32 v12, v14, v15, vcc
; GFX9-NEXT:    s_and_b32 s4, s20, 0xffff0000
; GFX9-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; GFX9-NEXT:    v_and_b32_sdwa v12, v13, v12 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    v_lshl_or_b32 v5, v5, 16, v12
; GFX9-NEXT:    v_add_f32_e32 v12, s4, v1
; GFX9-NEXT:    v_bfe_u32 v14, v12, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v14, v14, v12
; GFX9-NEXT:    s_lshl_b32 s4, s20, 16
; GFX9-NEXT:    v_add_u32_e32 v14, 0x7fff, v14
; GFX9-NEXT:    v_or_b32_e32 v15, 0x400000, v12
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v12, v12
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v12, v14, v15, vcc
; GFX9-NEXT:    v_bfe_u32 v14, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v14, v14, v1
; GFX9-NEXT:    v_add_u32_e32 v14, 0x7fff, v14
; GFX9-NEXT:    v_or_b32_e32 v15, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v3, 16, v10
; GFX9-NEXT:    v_cndmask_b32_e32 v10, v14, v15, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v16, 16, v2
; GFX9-NEXT:    v_lshrrev_b32_e32 v2, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v4, 16, v12
; GFX9-NEXT:    v_and_b32_sdwa v10, v13, v10 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    v_lshl_or_b32 v4, v4, 16, v10
; GFX9-NEXT:    v_and_b32_sdwa v10, v13, v11 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    v_and_b32_sdwa v9, v13, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    v_and_b32_sdwa v8, v13, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    v_and_b32_sdwa v0, v13, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; GFX9-NEXT:    v_lshl_or_b32 v3, v3, 16, v10
; GFX9-NEXT:    v_lshl_or_b32 v2, v2, 16, v9
; GFX9-NEXT:    v_lshl_or_b32 v1, v1, 16, v8
; GFX9-NEXT:    v_lshl_or_b32 v0, v16, 16, v0
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB103_3:
; GFX9-NEXT:    s_branch .LBB103_2
; GFX9-NEXT:  .LBB103_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v16bf16_to_v16f16_scalar:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_mov_b32 s7, s19
; GFX11-TRUE16-NEXT:    s_mov_b32 s6, s18
; GFX11-TRUE16-NEXT:    s_mov_b32 s5, s17
; GFX11-TRUE16-NEXT:    s_mov_b32 s4, s16
; GFX11-TRUE16-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-TRUE16-NEXT:    s_mov_b32 s8, 0
; GFX11-TRUE16-NEXT:    s_cbranch_scc0 .LBB103_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-TRUE16-NEXT:    s_cbranch_vccnz .LBB103_4
; GFX11-TRUE16-NEXT:  .LBB103_2: ; %cmp.true
; GFX11-TRUE16-NEXT:    s_and_b32 s8, s0, 0xffff0000
; GFX11-TRUE16-NEXT:    s_lshl_b32 s0, s0, 16
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v0, 0x40c00000, s8
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v1, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    s_and_b32 s0, s1, 0xffff0000
; GFX11-TRUE16-NEXT:    s_lshl_b32 s1, s1, 16
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v4, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v2, v0, 16, 1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v3, v1, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v5, 0x40c00000, s1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v6, 0x400000, v0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v7, v4, 16, 1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, v2, v0
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v9, v5, 16, 1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v7, v7, v4
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v2
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, v3, v1
; GFX11-TRUE16-NEXT:    s_and_b32 s8, s2, 0xffff0000
; GFX11-TRUE16-NEXT:    s_lshl_b32 s0, s2, 16
; GFX11-TRUE16-NEXT:    s_and_b32 s1, s5, 0xffff0000
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_dual_cndmask_b32 v0, v2, v6 :: v_dual_add_nc_u32 v3, 0x7fff, v3
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v2, 0x400000, v4
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, 0x7fff, v7
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v7, 0x40c00000, s8
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v13, 0x40c00000, s1
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v3, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, v9, v5
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v8, 16, v0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v4, v7, 16, 1
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v1
; GFX11-TRUE16-NEXT:    s_and_b32 s1, s7, 0xffff0000
; GFX11-TRUE16-NEXT:    v_dual_cndmask_b32 v1, v6, v2 :: v_dual_add_nc_u32 v2, 0x7fff, v3
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v3, 0x400000, v5
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v6, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v9, 16, v1
; GFX11-TRUE16-NEXT:    s_and_b32 s0, s3, 0xffff0000
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, 0x400000, v7
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v2, v3, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, v4, v7
; GFX11-TRUE16-NEXT:    v_bfe_u32 v3, v6, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v4, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v17, 0x40c00000, s1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v2
; GFX11-TRUE16-NEXT:    s_lshl_b32 s0, s3, 16
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, v3, v6
; GFX11-TRUE16-NEXT:    v_bfe_u32 v10, v4, 16, 1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v18, v17, 16, 1
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v2, v2, v5, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v5, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v3
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v7, 0x400000, v6
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v11, 16, v2
; GFX11-TRUE16-NEXT:    v_bfe_u32 v2, v5, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v15, 0x400000, v13
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v10, v10, v4
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v18, v18, v17
; GFX11-TRUE16-NEXT:    s_and_b32 s0, s4, 0xffff0000
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v3, v3, v7, vcc_lo
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v7, 0x400000, v4
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v12, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v18, 0x7fff, v18
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, 0x7fff, v10
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v10, v2, v5
; GFX11-TRUE16-NEXT:    s_lshl_b32 s0, s4, 16
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v3
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_dual_cndmask_b32 v3, v6, v7 :: v_dual_add_nc_u32 v4, 0x7fff, v10
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v6, 0x400000, v5
; GFX11-TRUE16-NEXT:    v_bfe_u32 v7, v12, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v10, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; GFX11-TRUE16-NEXT:    s_lshl_b32 s0, s5, 16
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v5, v7, v12
; GFX11-TRUE16-NEXT:    v_bfe_u32 v7, v13, 16, 1
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v4, v4, v6, vcc_lo
; GFX11-TRUE16-NEXT:    v_bfe_u32 v6, v10, 16, 1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v12, v12
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.h, v11.l
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v7, v7, v13
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v3, 16, v4
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v4, 0x7fff, v5
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, 0x400000, v12
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, v6, v10
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v12, 0x400000, v10
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v7, 0x7fff, v7
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v3.h, v14.l
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v4, v4, v5, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v5, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, 0x7fff, v6
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-TRUE16-NEXT:    s_and_b32 s0, s6, 0xffff0000
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v1.h, v9.l
; GFX11-TRUE16-NEXT:    v_bfe_u32 v16, v5, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v10, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v6, v6, v12, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v13, v13
; GFX11-TRUE16-NEXT:    s_lshl_b32 s0, s6, 16
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v12, v16, v5
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v13, 16, v4
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v4, 16, v6
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v7, v7, v15, vcc_lo
; GFX11-TRUE16-NEXT:    v_bfe_u32 v15, v10, 16, 1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, 0x7fff, v12
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v19, 0x400000, v10
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v16, 16, v7
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v7, 0x400000, v5
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v12, v15, v10
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v15, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    s_lshl_b32 s0, s7, 16
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v4.h, v13.l
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v5, v6, v7, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v6, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v7, v15, 16, 1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v12, 0x7fff, v12
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; GFX11-TRUE16-NEXT:    v_bfe_u32 v20, v6, 16, 1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v7, v7, v15
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v21, 0x400000, v6
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v10, v12, v19, vcc_lo
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v19, 0x400000, v17
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v17, v17
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v12, v20, v6
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v7, 0x7fff, v7
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v20, 0x400000, v15
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v10, 16, v10
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v17, v18, v19, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v15, v15
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v12, 0x7fff, v12
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v5.h, v16.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.h, v8.l
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v15, 16, v17
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v7, v7, v20, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_2) | instid1(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v6, 16, v7
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v12, v12, v21, vcc_lo
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v6.h, v10.l
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v7, 16, v12
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v7.h, v15.l
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB103_3:
; GFX11-TRUE16-NEXT:    s_branch .LBB103_2
; GFX11-TRUE16-NEXT:  .LBB103_4:
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v16bf16_to_v16f16_scalar:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    s_mov_b32 s7, s19
; GFX11-FAKE16-NEXT:    s_mov_b32 s6, s18
; GFX11-FAKE16-NEXT:    s_mov_b32 s5, s17
; GFX11-FAKE16-NEXT:    s_mov_b32 s4, s16
; GFX11-FAKE16-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-FAKE16-NEXT:    s_mov_b32 s8, 0
; GFX11-FAKE16-NEXT:    s_cbranch_scc0 .LBB103_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s8
; GFX11-FAKE16-NEXT:    s_cbranch_vccnz .LBB103_4
; GFX11-FAKE16-NEXT:  .LBB103_2: ; %cmp.true
; GFX11-FAKE16-NEXT:    s_and_b32 s8, s0, 0xffff0000
; GFX11-FAKE16-NEXT:    s_lshl_b32 s0, s0, 16
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v0, 0x40c00000, s8
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v1, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    s_and_b32 s0, s1, 0xffff0000
; GFX11-FAKE16-NEXT:    s_lshl_b32 s1, s1, 16
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v4, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    v_bfe_u32 v2, v0, 16, 1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v3, v1, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v6, 0x400000, v0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v8, 0x400000, v1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v7, v4, 16, 1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, v2, v0
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v5, 0x40c00000, s1
; GFX11-FAKE16-NEXT:    s_lshl_b32 s0, s2, 16
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v7, v7, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, v3, v1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v9, v5, 16, 1
; GFX11-FAKE16-NEXT:    s_and_b32 s8, s2, 0xffff0000
; GFX11-FAKE16-NEXT:    s_lshl_b32 s1, s4, 16
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v0, v2, v6, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, 0x400000, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v6, 0x7fff, v7
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v3
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v7, 0x40c00000, s8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v1, v3, v8, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, v9, v5
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, 0x400000, v5
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v9, 0x400000, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v2, v6, v2, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-FAKE16-NEXT:    v_bfe_u32 v6, v7, 16, 1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_2) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v8, 16, v2
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v2, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    s_and_b32 s0, s3, 0xffff0000
; GFX11-FAKE16-NEXT:    v_bfe_u32 v5, v2, 16, 1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v5, v5, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v5, 0x7fff, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v3
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_3) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v3, v3, v4 :: v_dual_add_nc_u32 v4, v6, v7
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v6, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-FAKE16-NEXT:    s_lshl_b32 s0, s3, 16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, 0x7fff, v4
; GFX11-FAKE16-NEXT:    v_bfe_u32 v10, v6, 16, 1
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v7, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    s_and_b32 s0, s4, 0xffff0000
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_3) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v4, v4, v9, vcc_lo
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v9, 0x400000, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v10, v10, v6
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v11, 16, v4
; GFX11-FAKE16-NEXT:    v_bfe_u32 v4, v7, 16, 1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v2, v5, v9 :: v_dual_add_nc_u32 v5, 0x7fff, v10
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v9, 0x400000, v6
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v10, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-FAKE16-NEXT:    s_and_b32 s0, s5, 0xffff0000
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, v4, v7
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v12, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v6, 0x400000, v7
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v5, v5, v9, vcc_lo
; GFX11-FAKE16-NEXT:    v_bfe_u32 v9, v10, 16, 1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, 0x7fff, v4
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-FAKE16-NEXT:    s_lshl_b32 s0, s5, 16
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v14, 0x400000, v10
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v7, v9, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v9, 16, v5
; GFX11-FAKE16-NEXT:    v_bfe_u32 v5, v12, 16, 1
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v4, v4, v6, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v6, 0x40c00000, s1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v7, 0x7fff, v7
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v15, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v5, v5, v12
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v6, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v10, 0x400000, v12
; GFX11-FAKE16-NEXT:    s_and_b32 s0, s6, 0xffff0000
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v5, 0x7fff, v5
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v7, v7, v14, vcc_lo
; GFX11-FAKE16-NEXT:    v_bfe_u32 v14, v15, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v12, v12
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v12, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    s_lshl_b32 s0, s6, 16
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v13, v13, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v16, 0x400000, v6
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v5, v5, v10 :: v_dual_add_nc_u32 v10, v14, v15
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v14, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    s_lshl_b32 s0, s7, 16
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v13, 0x7fff, v13
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v17, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    v_bfe_u32 v18, v14, 16, 1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v10, 0x7fff, v10
; GFX11-FAKE16-NEXT:    s_and_b32 s0, s7, 0xffff0000
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v6, v13, v16, vcc_lo
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v16, 0x400000, v15
; GFX11-FAKE16-NEXT:    v_bfe_u32 v20, v17, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v15, v15
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v15, v18, v14
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v12, 16, 1
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v19, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v18, v20, v17
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v10, v10, v16 :: v_dual_add_nc_u32 v15, 0x7fff, v15
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v21, 0x400000, v14
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v14, v14
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v13, v13, v12
; GFX11-FAKE16-NEXT:    v_bfe_u32 v16, v19, 16, 1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v18, 0x7fff, v18
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v22, 0x400000, v17
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v14, v15, v21, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v17, v17
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v13, 0x7fff, v13
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v20, 0x400000, v12
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v16, v16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v14, 16, v14
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v17, v18, v22, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v12, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v10, 16, v10
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v15, 0x7fff, v16
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v16, 0x400000, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v12, v13, v20, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v19, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v12, 16, v12
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v13, v15, v16, vcc_lo
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v15, 16, v17
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v16, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v17, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v13, 16, v13
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v6, v12, 16, v14
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v5, v5, 16, v10
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v10, 0xffff, v16
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v12, 0xffff, v4
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v7, v13, 16, v15
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v13, 0xffff, v3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v14, 0xffff, v1
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v4, v17, 16, v10
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v3, v9, 16, v12
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v2, v11, 16, v2
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v1, v8, 16, v13
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v0, v0, 16, v14
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB103_3:
; GFX11-FAKE16-NEXT:    s_branch .LBB103_2
; GFX11-FAKE16-NEXT:  .LBB103_4:
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x bfloat> %a, splat (bfloat 0xR40C0)
  %a2 = bitcast <16 x bfloat> %a1 to <16 x half>
  br label %end

cmp.false:
  %a3 = bitcast <16 x bfloat> %a to <16 x half>
  br label %end

end:
  %phi = phi <16 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x half> %phi
}

define <32 x i8> @bitcast_v16f16_to_v32i8(<16 x half> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v16f16_to_v32i8:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_mov_b32_e32 v37, v7
; SI-NEXT:    v_mov_b32_e32 v39, v6
; SI-NEXT:    v_mov_b32_e32 v36, v5
; SI-NEXT:    v_mov_b32_e32 v38, v4
; SI-NEXT:    v_mov_b32_e32 v34, v3
; SI-NEXT:    v_mov_b32_e32 v35, v2
; SI-NEXT:    v_mov_b32_e32 v32, v1
; SI-NEXT:    v_mov_b32_e32 v33, v0
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v37
; SI-NEXT:    v_lshrrev_b32_e32 v51, 16, v39
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v36
; SI-NEXT:    v_lshrrev_b32_e32 v50, 16, v38
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v34
; SI-NEXT:    v_lshrrev_b32_e32 v49, 16, v35
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v32
; SI-NEXT:    v_lshrrev_b32_e32 v48, 16, v33
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    ; implicit-def: $vgpr0
; SI-NEXT:    ; implicit-def: $vgpr1
; SI-NEXT:    ; implicit-def: $vgpr2
; SI-NEXT:    ; implicit-def: $vgpr3
; SI-NEXT:    ; implicit-def: $vgpr4
; SI-NEXT:    ; implicit-def: $vgpr5
; SI-NEXT:    ; implicit-def: $vgpr7
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr24
; SI-NEXT:    ; implicit-def: $vgpr25
; SI-NEXT:    ; implicit-def: $vgpr26
; SI-NEXT:    ; implicit-def: $vgpr27
; SI-NEXT:    ; implicit-def: $vgpr28
; SI-NEXT:    ; implicit-def: $vgpr29
; SI-NEXT:    ; implicit-def: $vgpr31
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB104_3
; SI-NEXT:  ; %bb.1: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB104_4
; SI-NEXT:  .LBB104_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB104_3: ; %cmp.false
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v35
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v49
; SI-NEXT:    v_or_b32_e32 v8, v5, v7
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v34
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v14
; SI-NEXT:    v_or_b32_e32 v12, v5, v7
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v38
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v50
; SI-NEXT:    v_or_b32_e32 v16, v5, v7
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v36
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v22
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v33
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v48
; SI-NEXT:    v_or_b32_e32 v20, v5, v7
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v39
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v51
; SI-NEXT:    v_or_b32_e32 v0, v0, v1
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v32
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v6
; SI-NEXT:    v_or_b32_e32 v24, v5, v7
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v37
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v30
; SI-NEXT:    v_or_b32_e32 v4, v1, v2
; SI-NEXT:    v_or_b32_e32 v28, v5, v7
; SI-NEXT:    v_alignbit_b32 v3, v4, v0, 24
; SI-NEXT:    v_alignbit_b32 v2, v4, v0, 16
; SI-NEXT:    v_alignbit_b32 v1, v4, v0, 8
; SI-NEXT:    v_alignbit_b32 v11, v12, v8, 24
; SI-NEXT:    v_alignbit_b32 v10, v12, v8, 16
; SI-NEXT:    v_alignbit_b32 v9, v12, v8, 8
; SI-NEXT:    v_alignbit_b32 v19, v20, v16, 24
; SI-NEXT:    v_alignbit_b32 v18, v20, v16, 16
; SI-NEXT:    v_alignbit_b32 v17, v20, v16, 8
; SI-NEXT:    v_alignbit_b32 v27, v28, v24, 24
; SI-NEXT:    v_alignbit_b32 v26, v28, v24, 16
; SI-NEXT:    v_alignbit_b32 v25, v28, v24, 8
; SI-NEXT:    v_lshrrev_b32_e32 v5, 8, v4
; SI-NEXT:    v_lshrrev_b32_e32 v13, 8, v12
; SI-NEXT:    v_lshrrev_b32_e32 v21, 8, v20
; SI-NEXT:    v_lshrrev_b32_e32 v29, 8, v28
; SI-NEXT:    v_bfe_u32 v7, v6, 8, 8
; SI-NEXT:    v_bfe_u32 v15, v14, 8, 8
; SI-NEXT:    v_bfe_u32 v23, v22, 8, 8
; SI-NEXT:    v_bfe_u32 v31, v30, 8, 8
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr48
; SI-NEXT:    ; implicit-def: $vgpr49
; SI-NEXT:    ; implicit-def: $vgpr50
; SI-NEXT:    ; implicit-def: $vgpr51
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB104_2
; SI-NEXT:  .LBB104_4: ; %cmp.true
; SI-NEXT:    v_cvt_f32_f16_e32 v0, v51
; SI-NEXT:    v_cvt_f32_f16_e32 v1, v39
; SI-NEXT:    v_cvt_f32_f16_e32 v2, v30
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v38
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v30, v2
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_cvt_f32_f16_e32 v2, v37
; SI-NEXT:    v_or_b32_e32 v24, v1, v0
; SI-NEXT:    v_cvt_f32_f16_e32 v1, v50
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v30
; SI-NEXT:    v_or_b32_e32 v28, v2, v0
; SI-NEXT:    v_cvt_f32_f16_e32 v0, v22
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_or_b32_e32 v16, v3, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v1, v36
; SI-NEXT:    v_cvt_f32_f16_e32 v2, v49
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v22, v0
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v1
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v35
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v22
; SI-NEXT:    v_or_b32_e32 v20, v0, v2
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v1, v14
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v34
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v14, v1
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_or_b32_e32 v8, v2, v0
; SI-NEXT:    v_cvt_f32_f16_e32 v0, v48
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v14
; SI-NEXT:    v_or_b32_e32 v12, v1, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v1, v33
; SI-NEXT:    v_cvt_f32_f16_e32 v2, v6
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v32
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v2
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_or_b32_e32 v0, v1, v0
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v6
; SI-NEXT:    v_or_b32_e32 v4, v2, v1
; SI-NEXT:    v_alignbit_b32 v3, v4, v0, 24
; SI-NEXT:    v_alignbit_b32 v2, v4, v0, 16
; SI-NEXT:    v_alignbit_b32 v1, v4, v0, 8
; SI-NEXT:    v_alignbit_b32 v11, v12, v8, 24
; SI-NEXT:    v_alignbit_b32 v10, v12, v8, 16
; SI-NEXT:    v_alignbit_b32 v9, v12, v8, 8
; SI-NEXT:    v_alignbit_b32 v19, v20, v16, 24
; SI-NEXT:    v_alignbit_b32 v18, v20, v16, 16
; SI-NEXT:    v_alignbit_b32 v17, v20, v16, 8
; SI-NEXT:    v_alignbit_b32 v27, v28, v24, 24
; SI-NEXT:    v_alignbit_b32 v26, v28, v24, 16
; SI-NEXT:    v_alignbit_b32 v25, v28, v24, 8
; SI-NEXT:    v_lshrrev_b32_e32 v5, 8, v4
; SI-NEXT:    v_lshrrev_b32_e32 v13, 8, v12
; SI-NEXT:    v_lshrrev_b32_e32 v21, 8, v20
; SI-NEXT:    v_lshrrev_b32_e32 v29, 8, v28
; SI-NEXT:    v_bfe_u32 v7, v6, 8, 8
; SI-NEXT:    v_bfe_u32 v15, v14, 8, 8
; SI-NEXT:    v_bfe_u32 v23, v22, 8, 8
; SI-NEXT:    v_bfe_u32 v31, v30, 8, 8
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16f16_to_v32i8:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_mov_b32_e32 v35, v5
; VI-NEXT:    v_mov_b32_e32 v34, v4
; VI-NEXT:    v_mov_b32_e32 v33, v3
; VI-NEXT:    v_mov_b32_e32 v32, v2
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v35
; VI-NEXT:    v_lshrrev_b32_e32 v18, 16, v34
; VI-NEXT:    v_lshrrev_b32_e32 v14, 16, v33
; VI-NEXT:    v_lshrrev_b32_e32 v10, 16, v32
; VI-NEXT:    v_lshrrev_b32_e32 v36, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr5
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr9
; VI-NEXT:    ; implicit-def: $vgpr13
; VI-NEXT:    ; implicit-def: $vgpr15
; VI-NEXT:    ; implicit-def: $vgpr17
; VI-NEXT:    ; implicit-def: $vgpr21
; VI-NEXT:    ; implicit-def: $vgpr23
; VI-NEXT:    ; implicit-def: $vgpr25
; VI-NEXT:    ; implicit-def: $vgpr29
; VI-NEXT:    ; implicit-def: $vgpr31
; VI-NEXT:    ; implicit-def: $vgpr3
; VI-NEXT:    ; implicit-def: $vgpr11
; VI-NEXT:    ; implicit-def: $vgpr19
; VI-NEXT:    ; implicit-def: $vgpr27
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB104_2
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; VI-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; VI-NEXT:    v_lshrrev_b32_e32 v25, 8, v6
; VI-NEXT:    v_lshrrev_b32_e32 v23, 24, v35
; VI-NEXT:    v_lshrrev_b32_e32 v21, 8, v35
; VI-NEXT:    v_lshrrev_b32_e32 v17, 8, v34
; VI-NEXT:    v_lshrrev_b32_e32 v15, 24, v33
; VI-NEXT:    v_lshrrev_b32_e32 v13, 8, v33
; VI-NEXT:    v_lshrrev_b32_e32 v9, 8, v32
; VI-NEXT:    v_lshrrev_b32_e32 v37, 24, v1
; VI-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; VI-NEXT:    v_lshrrev_b64 v[27:28], 24, v[6:7]
; VI-NEXT:    v_lshrrev_b64 v[19:20], 24, v[34:35]
; VI-NEXT:    v_lshrrev_b64 v[11:12], 24, v[32:33]
; VI-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; VI-NEXT:    v_lshrrev_b32_e32 v38, 8, v0
; VI-NEXT:  .LBB104_2: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB104_4
; VI-NEXT:  ; %bb.3: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v5, 0x200
; VI-NEXT:    v_add_f16_sdwa v14, v33, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_sdwa v36, v1, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v14
; VI-NEXT:    v_add_f16_e32 v33, 0x200, v33
; VI-NEXT:    v_add_f16_sdwa v10, v32, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v36
; VI-NEXT:    v_add_f16_e32 v1, 0x200, v1
; VI-NEXT:    v_or_b32_e32 v12, v33, v8
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v10
; VI-NEXT:    v_add_f16_e32 v32, 0x200, v32
; VI-NEXT:    v_add_f16_sdwa v22, v35, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v4, v1, v2
; VI-NEXT:    v_add_f16_sdwa v2, v0, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v11, v32, v8
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v22
; VI-NEXT:    v_add_f16_e32 v35, 0x200, v35
; VI-NEXT:    v_add_f16_sdwa v18, v34, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_sdwa v30, v7, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_sdwa v26, v6, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v3, 16, v2
; VI-NEXT:    v_add_f16_e32 v0, 0x200, v0
; VI-NEXT:    v_or_b32_e32 v9, v35, v8
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v18
; VI-NEXT:    v_add_f16_e32 v34, 0x200, v34
; VI-NEXT:    v_lshlrev_b32_e32 v13, 16, v30
; VI-NEXT:    v_add_f16_e32 v7, 0x200, v7
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v26
; VI-NEXT:    v_add_f16_e32 v6, 0x200, v6
; VI-NEXT:    v_or_b32_e32 v3, v0, v3
; VI-NEXT:    v_or_b32_e32 v8, v34, v8
; VI-NEXT:    v_or_b32_e32 v16, v7, v13
; VI-NEXT:    v_or_b32_e32 v15, v6, v5
; VI-NEXT:    v_lshrrev_b64 v[27:28], 24, v[15:16]
; VI-NEXT:    v_lshrrev_b32_e32 v21, 8, v9
; VI-NEXT:    v_lshrrev_b64 v[19:20], 24, v[8:9]
; VI-NEXT:    v_lshrrev_b32_e32 v13, 8, v12
; VI-NEXT:    v_lshrrev_b32_e32 v9, 8, v11
; VI-NEXT:    v_lshrrev_b64 v[11:12], 24, v[11:12]
; VI-NEXT:    v_lshrrev_b32_e32 v5, 8, v4
; VI-NEXT:    v_lshrrev_b32_e32 v38, 8, v3
; VI-NEXT:    v_lshrrev_b64 v[3:4], 24, v[3:4]
; VI-NEXT:    v_lshrrev_b32_e32 v29, 8, v16
; VI-NEXT:    v_lshrrev_b32_e32 v25, 8, v15
; VI-NEXT:    v_lshrrev_b32_e32 v17, 8, v8
; VI-NEXT:    v_bfe_u32 v31, v30, 8, 8
; VI-NEXT:    v_bfe_u32 v23, v22, 8, 8
; VI-NEXT:    v_bfe_u32 v15, v14, 8, 8
; VI-NEXT:    v_bfe_u32 v37, v36, 8, 8
; VI-NEXT:  .LBB104_4: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    v_mov_b32_e32 v4, v1
; VI-NEXT:    v_mov_b32_e32 v8, v32
; VI-NEXT:    v_mov_b32_e32 v12, v33
; VI-NEXT:    v_mov_b32_e32 v16, v34
; VI-NEXT:    v_mov_b32_e32 v20, v35
; VI-NEXT:    v_mov_b32_e32 v24, v6
; VI-NEXT:    v_mov_b32_e32 v28, v7
; VI-NEXT:    v_mov_b32_e32 v1, v38
; VI-NEXT:    v_mov_b32_e32 v6, v36
; VI-NEXT:    v_mov_b32_e32 v7, v37
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16f16_to_v32i8:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_mov_b32_e32 v33, v5
; GFX9-NEXT:    v_mov_b32_e32 v32, v4
; GFX9-NEXT:    v_mov_b32_e32 v35, v3
; GFX9-NEXT:    v_mov_b32_e32 v34, v2
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr2
; GFX9-NEXT:    ; implicit-def: $vgpr5
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr9
; GFX9-NEXT:    ; implicit-def: $vgpr10
; GFX9-NEXT:    ; implicit-def: $vgpr13
; GFX9-NEXT:    ; implicit-def: $vgpr14
; GFX9-NEXT:    ; implicit-def: $vgpr15
; GFX9-NEXT:    ; implicit-def: $vgpr17
; GFX9-NEXT:    ; implicit-def: $vgpr18
; GFX9-NEXT:    ; implicit-def: $vgpr21
; GFX9-NEXT:    ; implicit-def: $vgpr22
; GFX9-NEXT:    ; implicit-def: $vgpr23
; GFX9-NEXT:    ; implicit-def: $vgpr25
; GFX9-NEXT:    ; implicit-def: $vgpr26
; GFX9-NEXT:    ; implicit-def: $vgpr29
; GFX9-NEXT:    ; implicit-def: $vgpr30
; GFX9-NEXT:    ; implicit-def: $vgpr31
; GFX9-NEXT:    ; implicit-def: $vgpr3
; GFX9-NEXT:    ; implicit-def: $vgpr11
; GFX9-NEXT:    ; implicit-def: $vgpr19
; GFX9-NEXT:    ; implicit-def: $vgpr27
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB104_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 8, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 24, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 8, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v18, 16, v32
; GFX9-NEXT:    v_lshrrev_b32_e32 v17, 8, v32
; GFX9-NEXT:    v_lshrrev_b32_e32 v15, 24, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v14, 16, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v13, 8, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v10, 16, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v9, 8, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 24, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 8, v0
; GFX9-NEXT:    v_lshrrev_b64 v[27:28], 24, v[6:7]
; GFX9-NEXT:    v_lshrrev_b64 v[19:20], 24, v[32:33]
; GFX9-NEXT:    v_lshrrev_b64 v[11:12], 24, v[34:35]
; GFX9-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; GFX9-NEXT:  .LBB104_2: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB104_4
; GFX9-NEXT:  ; %bb.3: ; %cmp.true
; GFX9-NEXT:    s_movk_i32 s6, 0x200
; GFX9-NEXT:    v_pk_add_f16 v1, v1, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v0, v0, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v35, v35, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v34, v34, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v33, v33, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v32, v32, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v7, v7, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, v6, s6 op_sel_hi:[1,0]
; GFX9-NEXT:    v_lshrrev_b64 v[27:28], 24, v[6:7]
; GFX9-NEXT:    v_lshrrev_b64 v[19:20], 24, v[32:33]
; GFX9-NEXT:    v_lshrrev_b64 v[11:12], 24, v[34:35]
; GFX9-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 8, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 24, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 8, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v18, 16, v32
; GFX9-NEXT:    v_lshrrev_b32_e32 v17, 8, v32
; GFX9-NEXT:    v_lshrrev_b32_e32 v15, 24, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v14, 16, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v13, 8, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v10, 16, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v9, 8, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 24, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 8, v0
; GFX9-NEXT:  .LBB104_4: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    v_mov_b32_e32 v4, v1
; GFX9-NEXT:    v_mov_b32_e32 v8, v34
; GFX9-NEXT:    v_mov_b32_e32 v12, v35
; GFX9-NEXT:    v_mov_b32_e32 v16, v32
; GFX9-NEXT:    v_mov_b32_e32 v20, v33
; GFX9-NEXT:    v_mov_b32_e32 v24, v6
; GFX9-NEXT:    v_mov_b32_e32 v28, v7
; GFX9-NEXT:    v_mov_b32_e32 v1, v38
; GFX9-NEXT:    v_mov_b32_e32 v6, v37
; GFX9-NEXT:    v_mov_b32_e32 v7, v36
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v16f16_to_v32i8:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v33, v7 :: v_dual_mov_b32 v32, v6
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v27, v5 :: v_dual_mov_b32 v26, v4
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v19, v3 :: v_dual_mov_b32 v18, v2
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v11, v1 :: v_dual_mov_b32 v10, v0
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr1_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr3_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr5_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr7_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr36_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr15_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr17_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr35_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr21_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr23_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr25_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr34_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr29_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr31_lo16
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v8
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB104_2
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[34:35], 24, v[32:33]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[35:36], 24, v[26:27]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v27
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v27
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v26
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v18
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[36:37], 24, v[18:19]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[10:11]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v10
; GFX11-TRUE16-NEXT:  .LBB104_2: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB104_4
; GFX11-TRUE16-NEXT:  ; %bb.3: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v33, 0x200, v33 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v32, 0x200, v32 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v27, 0x200, v27 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v26, 0x200, v26 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v11, 0x200, v11 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v19, 0x200, v19 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v18, 0x200, v18 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v10, 0x200, v10 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[34:35], 24, v[32:33]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[35:36], 24, v[26:27]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[36:37], 24, v[18:19]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[10:11]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v27
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v27
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v26
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v18
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v10
; GFX11-TRUE16-NEXT:  .LBB104_4: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.l, v10.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.l, v10.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v4.l, v11.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v6.l, v11.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v8.l, v18.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v10.l, v18.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v11.l, v36.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v12.l, v19.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v14.l, v19.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v16.l, v26.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v18.l, v26.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v19.l, v35.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v20.l, v27.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v22.l, v27.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v24.l, v32.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v26.l, v32.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v27.l, v34.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v28.l, v33.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v30.l, v33.h
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v16f16_to_v32i8:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v33, v7 :: v_dual_mov_b32 v32, v6
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v35, v5 :: v_dual_mov_b32 v34, v4
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v37, v3 :: v_dual_mov_b32 v36, v2
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v39, v1 :: v_dual_mov_b32 v38, v0
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v8
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr1
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr2
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr3
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr5
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr6
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr7
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr9
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr10
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr11
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr13
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr14
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr15
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr17
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr18
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr19
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr21
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr22
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr23
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr25
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr26
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr27
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr29
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr30
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr31
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB104_2
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v32
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v18, 16, v34
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v34
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v14, 16, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v10, 16, v36
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v36
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v6, 16, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v38
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[27:28], 24, v[32:33]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[19:20], 24, v[34:35]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[11:12], 24, v[36:37]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[38:39]
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v38
; GFX11-FAKE16-NEXT:  .LBB104_2: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB104_4
; GFX11-FAKE16-NEXT:  ; %bb.3: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v39, 0x200, v39 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v37, 0x200, v37 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v35, 0x200, v35 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v33, 0x200, v33 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v32, 0x200, v32 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v34, 0x200, v34 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v36, 0x200, v36 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v38, 0x200, v38 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[27:28], 24, v[32:33]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[19:20], 24, v[34:35]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[11:12], 24, v[36:37]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[38:39]
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v32
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v18, 16, v34
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v34
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v14, 16, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v10, 16, v36
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v36
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v6, 16, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v38
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v38
; GFX11-FAKE16-NEXT:  .LBB104_4: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v0, v38
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v4, v39
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v8, v36
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v12, v37
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v16, v34
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v20, v35
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v24, v32
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v28, v33
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <16 x half> %a1 to <32 x i8>
  br label %end

cmp.false:
  %a3 = bitcast <16 x half> %a to <32 x i8>
  br label %end

end:
  %phi = phi <32 x i8> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x i8> %phi
}

define inreg <32 x i8> @bitcast_v16f16_to_v32i8_scalar(<16 x half> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v16f16_to_v32i8_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_lshr_b32 s78, s23, 16
; SI-NEXT:    s_lshr_b32 s79, s22, 16
; SI-NEXT:    s_lshr_b32 s76, s21, 16
; SI-NEXT:    s_lshr_b32 s77, s20, 16
; SI-NEXT:    s_lshr_b32 s74, s19, 16
; SI-NEXT:    s_lshr_b32 s75, s18, 16
; SI-NEXT:    s_lshr_b32 s72, s17, 16
; SI-NEXT:    s_lshr_b32 s73, s16, 16
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_cbranch_scc0 .LBB105_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s73, 16
; SI-NEXT:    s_or_b32 s10, s4, s5
; SI-NEXT:    s_and_b32 s4, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s72, 16
; SI-NEXT:    s_or_b32 s11, s4, s5
; SI-NEXT:    s_lshr_b64 s[4:5], s[10:11], 24
; SI-NEXT:    s_lshr_b64 s[6:7], s[10:11], 16
; SI-NEXT:    s_and_b32 s5, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s75, 16
; SI-NEXT:    s_or_b32 s26, s5, s7
; SI-NEXT:    s_and_b32 s5, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s74, 16
; SI-NEXT:    s_or_b32 s27, s5, s7
; SI-NEXT:    s_and_b32 s5, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s77, 16
; SI-NEXT:    s_or_b32 s44, s5, s7
; SI-NEXT:    s_and_b32 s5, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s76, 16
; SI-NEXT:    s_or_b32 s45, s5, s7
; SI-NEXT:    s_and_b32 s5, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s79, 16
; SI-NEXT:    s_or_b32 s60, s5, s7
; SI-NEXT:    s_and_b32 s5, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s78, 16
; SI-NEXT:    s_lshr_b64 s[8:9], s[10:11], 8
; SI-NEXT:    s_lshr_b64 s[12:13], s[26:27], 24
; SI-NEXT:    s_lshr_b64 s[14:15], s[26:27], 16
; SI-NEXT:    s_lshr_b64 s[24:25], s[26:27], 8
; SI-NEXT:    s_lshr_b64 s[28:29], s[44:45], 24
; SI-NEXT:    s_lshr_b64 s[40:41], s[44:45], 16
; SI-NEXT:    s_or_b32 s61, s5, s7
; SI-NEXT:    s_lshr_b64 s[42:43], s[44:45], 8
; SI-NEXT:    s_lshr_b64 s[46:47], s[60:61], 24
; SI-NEXT:    s_lshr_b64 s[56:57], s[60:61], 16
; SI-NEXT:    s_lshr_b64 s[58:59], s[60:61], 8
; SI-NEXT:    s_lshr_b32 s5, s11, 8
; SI-NEXT:    s_lshr_b32 s7, s27, 8
; SI-NEXT:    s_lshr_b32 s13, s45, 8
; SI-NEXT:    s_lshr_b32 s15, s61, 8
; SI-NEXT:    s_bfe_u32 s9, s72, 0x80008
; SI-NEXT:    s_bfe_u32 s25, s74, 0x80008
; SI-NEXT:    s_bfe_u32 s29, s76, 0x80008
; SI-NEXT:    s_bfe_u32 s41, s78, 0x80008
; SI-NEXT:    s_cbranch_execnz .LBB105_4
; SI-NEXT:  .LBB105_2: ; %cmp.true
; SI-NEXT:    v_cvt_f32_f16_e32 v0, s79
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s22
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_or_b32_e32 v33, v1, v0
; SI-NEXT:    v_cvt_f32_f16_e32 v0, s78
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s23
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v30, v0
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v30
; SI-NEXT:    v_bfe_u32 v31, v30, 8, 8
; SI-NEXT:    v_or_b32_e32 v34, v1, v0
; SI-NEXT:    v_cvt_f32_f16_e32 v0, s77
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s20
; SI-NEXT:    v_lshr_b64 v[24:25], v[33:34], 16
; SI-NEXT:    v_lshr_b64 v[27:28], v[33:34], 24
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_lshr_b64 v[25:26], v[33:34], 8
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_lshrrev_b32_e32 v29, 8, v34
; SI-NEXT:    v_or_b32_e32 v35, v1, v0
; SI-NEXT:    v_cvt_f32_f16_e32 v0, s76
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s21
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v22, v0
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v22
; SI-NEXT:    v_bfe_u32 v23, v22, 8, 8
; SI-NEXT:    v_or_b32_e32 v36, v1, v0
; SI-NEXT:    v_cvt_f32_f16_e32 v0, s75
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s18
; SI-NEXT:    v_lshr_b64 v[19:20], v[35:36], 24
; SI-NEXT:    v_lshr_b64 v[20:21], v[35:36], 16
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_lshr_b64 v[17:18], v[35:36], 8
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_lshrrev_b32_e32 v21, 8, v36
; SI-NEXT:    v_or_b32_e32 v37, v1, v0
; SI-NEXT:    v_cvt_f32_f16_e32 v0, s74
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s19
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v14, v0
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v14
; SI-NEXT:    v_bfe_u32 v15, v14, 8, 8
; SI-NEXT:    v_or_b32_e32 v38, v1, v0
; SI-NEXT:    v_cvt_f32_f16_e32 v0, s73
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s16
; SI-NEXT:    v_lshr_b64 v[11:12], v[37:38], 24
; SI-NEXT:    v_lshr_b64 v[12:13], v[37:38], 16
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_lshr_b64 v[9:10], v[37:38], 8
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_lshrrev_b32_e32 v13, 8, v38
; SI-NEXT:    v_or_b32_e32 v48, v1, v0
; SI-NEXT:    v_cvt_f32_f16_e32 v0, s72
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s17
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v0
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v6
; SI-NEXT:    v_bfe_u32 v7, v6, 8, 8
; SI-NEXT:    v_or_b32_e32 v49, v1, v0
; SI-NEXT:    v_lshr_b64 v[0:1], v[48:49], 16
; SI-NEXT:    v_lshr_b64 v[3:4], v[48:49], 24
; SI-NEXT:    v_lshr_b64 v[1:2], v[48:49], 8
; SI-NEXT:    v_lshrrev_b32_e32 v5, 8, v49
; SI-NEXT:    s_branch .LBB105_5
; SI-NEXT:  .LBB105_3:
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr8
; SI-NEXT:    ; implicit-def: $sgpr6
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr5
; SI-NEXT:    ; implicit-def: $sgpr9
; SI-NEXT:    ; implicit-def: $sgpr26
; SI-NEXT:    ; implicit-def: $sgpr24
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr12
; SI-NEXT:    ; implicit-def: $sgpr7
; SI-NEXT:    ; implicit-def: $sgpr25
; SI-NEXT:    ; implicit-def: $sgpr44
; SI-NEXT:    ; implicit-def: $sgpr42
; SI-NEXT:    ; implicit-def: $sgpr40
; SI-NEXT:    ; implicit-def: $sgpr28
; SI-NEXT:    ; implicit-def: $sgpr13
; SI-NEXT:    ; implicit-def: $sgpr29
; SI-NEXT:    ; implicit-def: $sgpr60
; SI-NEXT:    ; implicit-def: $sgpr58
; SI-NEXT:    ; implicit-def: $sgpr56
; SI-NEXT:    ; implicit-def: $sgpr46
; SI-NEXT:    ; implicit-def: $sgpr15
; SI-NEXT:    ; implicit-def: $sgpr41
; SI-NEXT:    s_branch .LBB105_2
; SI-NEXT:  .LBB105_4:
; SI-NEXT:    v_mov_b32_e32 v30, s78
; SI-NEXT:    v_mov_b32_e32 v22, s76
; SI-NEXT:    v_mov_b32_e32 v14, s74
; SI-NEXT:    v_mov_b32_e32 v6, s72
; SI-NEXT:    v_mov_b32_e32 v31, s41
; SI-NEXT:    v_mov_b32_e32 v23, s29
; SI-NEXT:    v_mov_b32_e32 v15, s25
; SI-NEXT:    v_mov_b32_e32 v7, s9
; SI-NEXT:    v_mov_b32_e32 v49, s11
; SI-NEXT:    v_mov_b32_e32 v48, s10
; SI-NEXT:    v_mov_b32_e32 v38, s27
; SI-NEXT:    v_mov_b32_e32 v37, s26
; SI-NEXT:    v_mov_b32_e32 v36, s45
; SI-NEXT:    v_mov_b32_e32 v35, s44
; SI-NEXT:    v_mov_b32_e32 v34, s61
; SI-NEXT:    v_mov_b32_e32 v33, s60
; SI-NEXT:    v_mov_b32_e32 v5, s5
; SI-NEXT:    v_mov_b32_e32 v13, s7
; SI-NEXT:    v_mov_b32_e32 v21, s13
; SI-NEXT:    v_mov_b32_e32 v29, s15
; SI-NEXT:    v_mov_b32_e32 v3, s4
; SI-NEXT:    v_mov_b32_e32 v0, s6
; SI-NEXT:    v_mov_b32_e32 v1, s8
; SI-NEXT:    v_mov_b32_e32 v11, s12
; SI-NEXT:    v_mov_b32_e32 v12, s14
; SI-NEXT:    v_mov_b32_e32 v9, s24
; SI-NEXT:    v_mov_b32_e32 v19, s28
; SI-NEXT:    v_mov_b32_e32 v20, s40
; SI-NEXT:    v_mov_b32_e32 v17, s42
; SI-NEXT:    v_mov_b32_e32 v27, s46
; SI-NEXT:    v_mov_b32_e32 v24, s56
; SI-NEXT:    v_mov_b32_e32 v25, s58
; SI-NEXT:  .LBB105_5: ; %end
; SI-NEXT:    v_mov_b32_e32 v2, v0
; SI-NEXT:    v_mov_b32_e32 v0, v48
; SI-NEXT:    v_mov_b32_e32 v4, v49
; SI-NEXT:    v_mov_b32_e32 v10, v12
; SI-NEXT:    v_mov_b32_e32 v8, v37
; SI-NEXT:    v_mov_b32_e32 v12, v38
; SI-NEXT:    v_mov_b32_e32 v18, v20
; SI-NEXT:    v_mov_b32_e32 v16, v35
; SI-NEXT:    v_mov_b32_e32 v20, v36
; SI-NEXT:    v_mov_b32_e32 v26, v24
; SI-NEXT:    v_mov_b32_e32 v24, v33
; SI-NEXT:    v_mov_b32_e32 v28, v34
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16f16_to_v32i8_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB105_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_lshr_b32 s40, s23, 24
; VI-NEXT:    s_lshr_b32 s44, s23, 16
; VI-NEXT:    s_lshr_b32 s25, s23, 8
; VI-NEXT:    s_lshr_b32 s45, s22, 16
; VI-NEXT:    s_lshr_b32 s29, s22, 8
; VI-NEXT:    s_lshr_b32 s41, s21, 24
; VI-NEXT:    s_lshr_b32 s46, s21, 16
; VI-NEXT:    s_lshr_b32 s24, s21, 8
; VI-NEXT:    s_lshr_b32 s47, s20, 16
; VI-NEXT:    s_lshr_b32 s28, s20, 8
; VI-NEXT:    s_lshr_b32 s42, s19, 24
; VI-NEXT:    s_lshr_b32 s56, s19, 16
; VI-NEXT:    s_lshr_b32 s15, s19, 8
; VI-NEXT:    s_lshr_b32 s57, s18, 16
; VI-NEXT:    s_lshr_b32 s27, s18, 8
; VI-NEXT:    s_lshr_b32 s43, s17, 24
; VI-NEXT:    s_lshr_b32 s58, s17, 16
; VI-NEXT:    s_lshr_b32 s14, s17, 8
; VI-NEXT:    s_lshr_b32 s59, s16, 16
; VI-NEXT:    s_lshr_b32 s26, s16, 8
; VI-NEXT:    s_lshr_b64 s[10:11], s[22:23], 24
; VI-NEXT:    s_lshr_b64 s[8:9], s[20:21], 24
; VI-NEXT:    s_lshr_b64 s[6:7], s[18:19], 24
; VI-NEXT:    s_lshr_b64 s[4:5], s[16:17], 24
; VI-NEXT:    s_cbranch_execnz .LBB105_4
; VI-NEXT:  .LBB105_2: ; %cmp.true
; VI-NEXT:    s_lshr_b32 s4, s17, 16
; VI-NEXT:    v_mov_b32_e32 v1, 0x200
; VI-NEXT:    v_add_f16_e32 v6, s4, v1
; VI-NEXT:    s_lshr_b32 s4, s16, 16
; VI-NEXT:    v_add_f16_e32 v2, s4, v1
; VI-NEXT:    s_lshr_b32 s4, s19, 16
; VI-NEXT:    v_add_f16_e32 v14, s4, v1
; VI-NEXT:    s_lshr_b32 s4, s18, 16
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v14
; VI-NEXT:    v_add_f16_e32 v34, s19, v1
; VI-NEXT:    v_add_f16_e32 v10, s4, v1
; VI-NEXT:    s_lshr_b32 s4, s21, 16
; VI-NEXT:    v_or_b32_e32 v12, v34, v5
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v10
; VI-NEXT:    v_add_f16_e32 v8, s18, v1
; VI-NEXT:    v_add_f16_e32 v22, s4, v1
; VI-NEXT:    s_lshr_b32 s4, s20, 16
; VI-NEXT:    v_or_b32_e32 v11, v8, v5
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v22
; VI-NEXT:    v_add_f16_e32 v33, s21, v1
; VI-NEXT:    v_add_f16_e32 v18, s4, v1
; VI-NEXT:    s_lshr_b32 s4, s23, 16
; VI-NEXT:    v_or_b32_e32 v20, v33, v5
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v18
; VI-NEXT:    v_add_f16_e32 v16, s20, v1
; VI-NEXT:    v_add_f16_e32 v30, s4, v1
; VI-NEXT:    s_lshr_b32 s4, s22, 16
; VI-NEXT:    v_lshlrev_b32_e32 v0, 16, v6
; VI-NEXT:    v_add_f16_e32 v35, s17, v1
; VI-NEXT:    v_or_b32_e32 v19, v16, v5
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v30
; VI-NEXT:    v_add_f16_e32 v32, s23, v1
; VI-NEXT:    v_add_f16_e32 v26, s4, v1
; VI-NEXT:    v_or_b32_e32 v4, v35, v0
; VI-NEXT:    v_lshlrev_b32_e32 v3, 16, v2
; VI-NEXT:    v_add_f16_e32 v0, s16, v1
; VI-NEXT:    v_or_b32_e32 v37, v32, v5
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v26
; VI-NEXT:    v_add_f16_e32 v24, s22, v1
; VI-NEXT:    v_or_b32_e32 v3, v0, v3
; VI-NEXT:    v_or_b32_e32 v36, v24, v5
; VI-NEXT:    v_lshrrev_b64 v[27:28], 24, v[36:37]
; VI-NEXT:    v_lshrrev_b32_e32 v21, 8, v20
; VI-NEXT:    v_lshrrev_b32_e32 v17, 8, v19
; VI-NEXT:    v_lshrrev_b64 v[19:20], 24, v[19:20]
; VI-NEXT:    v_lshrrev_b32_e32 v13, 8, v12
; VI-NEXT:    v_lshrrev_b32_e32 v9, 8, v11
; VI-NEXT:    v_lshrrev_b64 v[11:12], 24, v[11:12]
; VI-NEXT:    v_lshrrev_b32_e32 v5, 8, v4
; VI-NEXT:    v_lshrrev_b32_e32 v1, 8, v3
; VI-NEXT:    v_lshrrev_b64 v[3:4], 24, v[3:4]
; VI-NEXT:    v_lshrrev_b32_e32 v29, 8, v37
; VI-NEXT:    v_lshrrev_b32_e32 v25, 8, v36
; VI-NEXT:    v_bfe_u32 v31, v30, 8, 8
; VI-NEXT:    v_bfe_u32 v23, v22, 8, 8
; VI-NEXT:    v_bfe_u32 v15, v14, 8, 8
; VI-NEXT:    v_bfe_u32 v7, v6, 8, 8
; VI-NEXT:    s_branch .LBB105_5
; VI-NEXT:  .LBB105_3:
; VI-NEXT:    ; implicit-def: $sgpr26
; VI-NEXT:    ; implicit-def: $sgpr59
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr14
; VI-NEXT:    ; implicit-def: $sgpr58
; VI-NEXT:    ; implicit-def: $sgpr43
; VI-NEXT:    ; implicit-def: $sgpr27
; VI-NEXT:    ; implicit-def: $sgpr57
; VI-NEXT:    ; implicit-def: $sgpr6
; VI-NEXT:    ; implicit-def: $sgpr15
; VI-NEXT:    ; implicit-def: $sgpr56
; VI-NEXT:    ; implicit-def: $sgpr42
; VI-NEXT:    ; implicit-def: $sgpr28
; VI-NEXT:    ; implicit-def: $sgpr47
; VI-NEXT:    ; implicit-def: $sgpr8
; VI-NEXT:    ; implicit-def: $sgpr24
; VI-NEXT:    ; implicit-def: $sgpr46
; VI-NEXT:    ; implicit-def: $sgpr41
; VI-NEXT:    ; implicit-def: $sgpr29
; VI-NEXT:    ; implicit-def: $sgpr45
; VI-NEXT:    ; implicit-def: $sgpr10
; VI-NEXT:    ; implicit-def: $sgpr25
; VI-NEXT:    ; implicit-def: $sgpr44
; VI-NEXT:    ; implicit-def: $sgpr40
; VI-NEXT:    s_branch .LBB105_2
; VI-NEXT:  .LBB105_4:
; VI-NEXT:    v_mov_b32_e32 v2, s59
; VI-NEXT:    v_mov_b32_e32 v6, s58
; VI-NEXT:    v_mov_b32_e32 v10, s57
; VI-NEXT:    v_mov_b32_e32 v14, s56
; VI-NEXT:    v_mov_b32_e32 v18, s47
; VI-NEXT:    v_mov_b32_e32 v22, s46
; VI-NEXT:    v_mov_b32_e32 v26, s45
; VI-NEXT:    v_mov_b32_e32 v30, s44
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v35, s17
; VI-NEXT:    v_mov_b32_e32 v8, s18
; VI-NEXT:    v_mov_b32_e32 v34, s19
; VI-NEXT:    v_mov_b32_e32 v16, s20
; VI-NEXT:    v_mov_b32_e32 v33, s21
; VI-NEXT:    v_mov_b32_e32 v24, s22
; VI-NEXT:    v_mov_b32_e32 v32, s23
; VI-NEXT:    v_mov_b32_e32 v31, s40
; VI-NEXT:    v_mov_b32_e32 v23, s41
; VI-NEXT:    v_mov_b32_e32 v15, s42
; VI-NEXT:    v_mov_b32_e32 v7, s43
; VI-NEXT:    v_mov_b32_e32 v25, s29
; VI-NEXT:    v_mov_b32_e32 v29, s25
; VI-NEXT:    v_mov_b32_e32 v17, s28
; VI-NEXT:    v_mov_b32_e32 v21, s24
; VI-NEXT:    v_mov_b32_e32 v9, s27
; VI-NEXT:    v_mov_b32_e32 v13, s15
; VI-NEXT:    v_mov_b32_e32 v1, s26
; VI-NEXT:    v_mov_b32_e32 v5, s14
; VI-NEXT:    v_mov_b32_e32 v27, s10
; VI-NEXT:    v_mov_b32_e32 v19, s8
; VI-NEXT:    v_mov_b32_e32 v11, s6
; VI-NEXT:    v_mov_b32_e32 v3, s4
; VI-NEXT:  .LBB105_5: ; %end
; VI-NEXT:    v_mov_b32_e32 v4, v35
; VI-NEXT:    v_mov_b32_e32 v12, v34
; VI-NEXT:    v_mov_b32_e32 v20, v33
; VI-NEXT:    v_mov_b32_e32 v28, v32
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16f16_to_v32i8_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB105_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_lshr_b32 s14, s23, 24
; GFX9-NEXT:    s_lshr_b32 s15, s23, 16
; GFX9-NEXT:    s_lshr_b32 s25, s23, 8
; GFX9-NEXT:    s_lshr_b32 s24, s22, 16
; GFX9-NEXT:    s_lshr_b32 s26, s22, 8
; GFX9-NEXT:    s_lshr_b32 s27, s21, 24
; GFX9-NEXT:    s_lshr_b32 s28, s21, 16
; GFX9-NEXT:    s_lshr_b32 s40, s21, 8
; GFX9-NEXT:    s_lshr_b32 s29, s20, 16
; GFX9-NEXT:    s_lshr_b32 s41, s20, 8
; GFX9-NEXT:    s_lshr_b32 s42, s19, 24
; GFX9-NEXT:    s_lshr_b32 s43, s19, 16
; GFX9-NEXT:    s_lshr_b32 s45, s19, 8
; GFX9-NEXT:    s_lshr_b32 s44, s18, 16
; GFX9-NEXT:    s_lshr_b32 s46, s18, 8
; GFX9-NEXT:    s_lshr_b32 s47, s17, 24
; GFX9-NEXT:    s_lshr_b32 s56, s17, 16
; GFX9-NEXT:    s_lshr_b32 s58, s17, 8
; GFX9-NEXT:    s_lshr_b32 s57, s16, 16
; GFX9-NEXT:    s_lshr_b32 s59, s16, 8
; GFX9-NEXT:    s_lshr_b64 s[10:11], s[22:23], 24
; GFX9-NEXT:    s_lshr_b64 s[8:9], s[20:21], 24
; GFX9-NEXT:    s_lshr_b64 s[6:7], s[18:19], 24
; GFX9-NEXT:    s_lshr_b64 s[4:5], s[16:17], 24
; GFX9-NEXT:    s_cbranch_execnz .LBB105_4
; GFX9-NEXT:  .LBB105_2: ; %cmp.true
; GFX9-NEXT:    v_mov_b32_e32 v2, 0x200
; GFX9-NEXT:    v_pk_add_f16 v1, s17, v2 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v0, s16, v2 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v9, s19, v2 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v8, s18, v2 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v17, s21, v2 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v16, s20, v2 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v25, s23, v2 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v24, s22, v2 op_sel_hi:[1,0]
; GFX9-NEXT:    v_lshrrev_b64 v[27:28], 24, v[24:25]
; GFX9-NEXT:    v_lshrrev_b64 v[19:20], 24, v[16:17]
; GFX9-NEXT:    v_lshrrev_b64 v[11:12], 24, v[8:9]
; GFX9-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 24, v25
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v25
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 8, v25
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v24
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 8, v24
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 24, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 8, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v18, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 8, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v15, 24, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v14, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v13, 8, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v10, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 8, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v7, 24, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v6, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 8, v0
; GFX9-NEXT:    s_branch .LBB105_5
; GFX9-NEXT:  .LBB105_3:
; GFX9-NEXT:    ; implicit-def: $sgpr59
; GFX9-NEXT:    ; implicit-def: $sgpr57
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr58
; GFX9-NEXT:    ; implicit-def: $sgpr56
; GFX9-NEXT:    ; implicit-def: $sgpr47
; GFX9-NEXT:    ; implicit-def: $sgpr46
; GFX9-NEXT:    ; implicit-def: $sgpr44
; GFX9-NEXT:    ; implicit-def: $sgpr6
; GFX9-NEXT:    ; implicit-def: $sgpr45
; GFX9-NEXT:    ; implicit-def: $sgpr43
; GFX9-NEXT:    ; implicit-def: $sgpr42
; GFX9-NEXT:    ; implicit-def: $sgpr41
; GFX9-NEXT:    ; implicit-def: $sgpr29
; GFX9-NEXT:    ; implicit-def: $sgpr8
; GFX9-NEXT:    ; implicit-def: $sgpr40
; GFX9-NEXT:    ; implicit-def: $sgpr28
; GFX9-NEXT:    ; implicit-def: $sgpr27
; GFX9-NEXT:    ; implicit-def: $sgpr26
; GFX9-NEXT:    ; implicit-def: $sgpr24
; GFX9-NEXT:    ; implicit-def: $sgpr10
; GFX9-NEXT:    ; implicit-def: $sgpr25
; GFX9-NEXT:    ; implicit-def: $sgpr15
; GFX9-NEXT:    ; implicit-def: $sgpr14
; GFX9-NEXT:    s_branch .LBB105_2
; GFX9-NEXT:  .LBB105_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v8, s18
; GFX9-NEXT:    v_mov_b32_e32 v9, s19
; GFX9-NEXT:    v_mov_b32_e32 v16, s20
; GFX9-NEXT:    v_mov_b32_e32 v17, s21
; GFX9-NEXT:    v_mov_b32_e32 v24, s22
; GFX9-NEXT:    v_mov_b32_e32 v25, s23
; GFX9-NEXT:    v_mov_b32_e32 v35, s59
; GFX9-NEXT:    v_mov_b32_e32 v2, s57
; GFX9-NEXT:    v_mov_b32_e32 v5, s58
; GFX9-NEXT:    v_mov_b32_e32 v6, s56
; GFX9-NEXT:    v_mov_b32_e32 v7, s47
; GFX9-NEXT:    v_mov_b32_e32 v34, s46
; GFX9-NEXT:    v_mov_b32_e32 v10, s44
; GFX9-NEXT:    v_mov_b32_e32 v13, s45
; GFX9-NEXT:    v_mov_b32_e32 v14, s43
; GFX9-NEXT:    v_mov_b32_e32 v15, s42
; GFX9-NEXT:    v_mov_b32_e32 v33, s41
; GFX9-NEXT:    v_mov_b32_e32 v18, s29
; GFX9-NEXT:    v_mov_b32_e32 v21, s40
; GFX9-NEXT:    v_mov_b32_e32 v22, s28
; GFX9-NEXT:    v_mov_b32_e32 v23, s27
; GFX9-NEXT:    v_mov_b32_e32 v32, s26
; GFX9-NEXT:    v_mov_b32_e32 v26, s24
; GFX9-NEXT:    v_mov_b32_e32 v29, s25
; GFX9-NEXT:    v_mov_b32_e32 v30, s15
; GFX9-NEXT:    v_mov_b32_e32 v31, s14
; GFX9-NEXT:    v_mov_b32_e32 v27, s10
; GFX9-NEXT:    v_mov_b32_e32 v19, s8
; GFX9-NEXT:    v_mov_b32_e32 v11, s6
; GFX9-NEXT:    v_mov_b32_e32 v3, s4
; GFX9-NEXT:  .LBB105_5: ; %end
; GFX9-NEXT:    v_mov_b32_e32 v4, v1
; GFX9-NEXT:    v_mov_b32_e32 v12, v9
; GFX9-NEXT:    v_mov_b32_e32 v20, v17
; GFX9-NEXT:    v_mov_b32_e32 v28, v25
; GFX9-NEXT:    v_mov_b32_e32 v1, v35
; GFX9-NEXT:    v_mov_b32_e32 v9, v34
; GFX9-NEXT:    v_mov_b32_e32 v17, v33
; GFX9-NEXT:    v_mov_b32_e32 v25, v32
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v16f16_to_v32i8_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-NEXT:    s_mov_b32 s12, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB105_3
; GFX11-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-NEXT:    s_lshr_b32 s13, s19, 24
; GFX11-NEXT:    s_lshr_b32 s14, s19, 16
; GFX11-NEXT:    s_lshr_b32 s20, s19, 8
; GFX11-NEXT:    s_lshr_b32 s15, s18, 16
; GFX11-NEXT:    s_lshr_b32 s21, s18, 8
; GFX11-NEXT:    s_lshr_b32 s22, s17, 24
; GFX11-NEXT:    s_lshr_b32 s23, s17, 16
; GFX11-NEXT:    s_lshr_b32 s25, s17, 8
; GFX11-NEXT:    s_lshr_b32 s24, s16, 16
; GFX11-NEXT:    s_lshr_b32 s26, s16, 8
; GFX11-NEXT:    s_lshr_b32 s27, s3, 24
; GFX11-NEXT:    s_lshr_b32 s28, s3, 16
; GFX11-NEXT:    s_lshr_b32 s40, s3, 8
; GFX11-NEXT:    s_lshr_b32 s29, s2, 16
; GFX11-NEXT:    s_lshr_b32 s41, s2, 8
; GFX11-NEXT:    s_lshr_b32 s42, s1, 24
; GFX11-NEXT:    s_lshr_b32 s43, s1, 16
; GFX11-NEXT:    s_lshr_b32 s45, s1, 8
; GFX11-NEXT:    s_lshr_b32 s44, s0, 16
; GFX11-NEXT:    s_lshr_b32 s46, s0, 8
; GFX11-NEXT:    s_lshr_b64 s[10:11], s[18:19], 24
; GFX11-NEXT:    s_lshr_b64 s[8:9], s[16:17], 24
; GFX11-NEXT:    s_lshr_b64 s[6:7], s[2:3], 24
; GFX11-NEXT:    s_lshr_b64 s[4:5], s[0:1], 24
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s12
; GFX11-NEXT:    s_cbranch_vccnz .LBB105_4
; GFX11-NEXT:  .LBB105_2: ; %cmp.true
; GFX11-NEXT:    v_pk_add_f16 v39, 0x200, s1 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v37, 0x200, s3 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v35, 0x200, s17 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v33, 0x200, s19 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v32, 0x200, s18 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v34, 0x200, s16 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v36, 0x200, s2 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v38, 0x200, s0 op_sel_hi:[0,1]
; GFX11-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-NEXT:    v_lshrrev_b64 v[27:28], 24, v[32:33]
; GFX11-NEXT:    v_lshrrev_b64 v[19:20], 24, v[34:35]
; GFX11-NEXT:    v_lshrrev_b64 v[11:12], 24, v[36:37]
; GFX11-NEXT:    v_lshrrev_b64 v[3:4], 24, v[38:39]
; GFX11-NEXT:    v_lshrrev_b32_e32 v30, 16, v33
; GFX11-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-NEXT:    v_lshrrev_b32_e32 v26, 16, v32
; GFX11-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-NEXT:    v_lshrrev_b32_e32 v23, 24, v35
; GFX11-NEXT:    v_lshrrev_b32_e32 v22, 16, v35
; GFX11-NEXT:    v_lshrrev_b32_e32 v21, 8, v35
; GFX11-NEXT:    v_lshrrev_b32_e32 v18, 16, v34
; GFX11-NEXT:    v_lshrrev_b32_e32 v17, 8, v34
; GFX11-NEXT:    v_lshrrev_b32_e32 v15, 24, v37
; GFX11-NEXT:    v_lshrrev_b32_e32 v14, 16, v37
; GFX11-NEXT:    v_lshrrev_b32_e32 v13, 8, v37
; GFX11-NEXT:    v_lshrrev_b32_e32 v10, 16, v36
; GFX11-NEXT:    v_lshrrev_b32_e32 v9, 8, v36
; GFX11-NEXT:    v_lshrrev_b32_e32 v7, 24, v39
; GFX11-NEXT:    v_lshrrev_b32_e32 v6, 16, v39
; GFX11-NEXT:    v_lshrrev_b32_e32 v5, 8, v39
; GFX11-NEXT:    v_lshrrev_b32_e32 v2, 16, v38
; GFX11-NEXT:    v_lshrrev_b32_e32 v1, 8, v38
; GFX11-NEXT:    s_branch .LBB105_5
; GFX11-NEXT:  .LBB105_3:
; GFX11-NEXT:    ; implicit-def: $sgpr46
; GFX11-NEXT:    ; implicit-def: $sgpr44
; GFX11-NEXT:    ; implicit-def: $sgpr4
; GFX11-NEXT:    ; implicit-def: $sgpr45
; GFX11-NEXT:    ; implicit-def: $sgpr43
; GFX11-NEXT:    ; implicit-def: $sgpr42
; GFX11-NEXT:    ; implicit-def: $sgpr41
; GFX11-NEXT:    ; implicit-def: $sgpr29
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr40
; GFX11-NEXT:    ; implicit-def: $sgpr28
; GFX11-NEXT:    ; implicit-def: $sgpr27
; GFX11-NEXT:    ; implicit-def: $sgpr26
; GFX11-NEXT:    ; implicit-def: $sgpr24
; GFX11-NEXT:    ; implicit-def: $sgpr8
; GFX11-NEXT:    ; implicit-def: $sgpr25
; GFX11-NEXT:    ; implicit-def: $sgpr23
; GFX11-NEXT:    ; implicit-def: $sgpr22
; GFX11-NEXT:    ; implicit-def: $sgpr21
; GFX11-NEXT:    ; implicit-def: $sgpr15
; GFX11-NEXT:    ; implicit-def: $sgpr10
; GFX11-NEXT:    ; implicit-def: $sgpr20
; GFX11-NEXT:    ; implicit-def: $sgpr14
; GFX11-NEXT:    ; implicit-def: $sgpr13
; GFX11-NEXT:    s_branch .LBB105_2
; GFX11-NEXT:  .LBB105_4:
; GFX11-NEXT:    v_dual_mov_b32 v38, s0 :: v_dual_mov_b32 v39, s1
; GFX11-NEXT:    v_dual_mov_b32 v36, s2 :: v_dual_mov_b32 v37, s3
; GFX11-NEXT:    v_dual_mov_b32 v34, s16 :: v_dual_mov_b32 v35, s17
; GFX11-NEXT:    v_dual_mov_b32 v32, s18 :: v_dual_mov_b32 v33, s19
; GFX11-NEXT:    v_dual_mov_b32 v1, s46 :: v_dual_mov_b32 v2, s44
; GFX11-NEXT:    v_dual_mov_b32 v5, s45 :: v_dual_mov_b32 v6, s43
; GFX11-NEXT:    v_dual_mov_b32 v7, s42 :: v_dual_mov_b32 v10, s29
; GFX11-NEXT:    v_dual_mov_b32 v9, s41 :: v_dual_mov_b32 v14, s28
; GFX11-NEXT:    v_dual_mov_b32 v13, s40 :: v_dual_mov_b32 v18, s24
; GFX11-NEXT:    v_dual_mov_b32 v15, s27 :: v_dual_mov_b32 v22, s23
; GFX11-NEXT:    v_dual_mov_b32 v17, s26 :: v_dual_mov_b32 v26, s15
; GFX11-NEXT:    v_dual_mov_b32 v21, s25 :: v_dual_mov_b32 v30, s14
; GFX11-NEXT:    v_mov_b32_e32 v23, s22
; GFX11-NEXT:    v_mov_b32_e32 v25, s21
; GFX11-NEXT:    v_mov_b32_e32 v29, s20
; GFX11-NEXT:    v_mov_b32_e32 v31, s13
; GFX11-NEXT:    v_mov_b32_e32 v27, s10
; GFX11-NEXT:    v_mov_b32_e32 v19, s8
; GFX11-NEXT:    v_mov_b32_e32 v11, s6
; GFX11-NEXT:    v_mov_b32_e32 v3, s4
; GFX11-NEXT:  .LBB105_5: ; %end
; GFX11-NEXT:    v_mov_b32_e32 v0, v38
; GFX11-NEXT:    v_mov_b32_e32 v4, v39
; GFX11-NEXT:    v_mov_b32_e32 v8, v36
; GFX11-NEXT:    v_mov_b32_e32 v12, v37
; GFX11-NEXT:    v_mov_b32_e32 v16, v34
; GFX11-NEXT:    v_mov_b32_e32 v20, v35
; GFX11-NEXT:    v_mov_b32_e32 v24, v32
; GFX11-NEXT:    v_mov_b32_e32 v28, v33
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <16 x half> %a1 to <32 x i8>
  br label %end

cmp.false:
  %a3 = bitcast <16 x half> %a to <32 x i8>
  br label %end

end:
  %phi = phi <32 x i8> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x i8> %phi
}

define <16 x half> @bitcast_v32i8_to_v16f16(<32 x i8> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v32i8_to_v16f16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    buffer_load_dword v38, off, s[0:3], s32 offset:4
; SI-NEXT:    buffer_load_dword v39, off, s[0:3], s32
; SI-NEXT:    v_lshlrev_b32_e32 v32, 8, v5
; SI-NEXT:    v_lshlrev_b32_e32 v31, 24, v7
; SI-NEXT:    v_lshlrev_b32_e32 v33, 24, v3
; SI-NEXT:    v_lshlrev_b32_e32 v35, 8, v13
; SI-NEXT:    v_lshlrev_b32_e32 v34, 24, v15
; SI-NEXT:    v_lshlrev_b32_e32 v36, 24, v11
; SI-NEXT:    v_lshlrev_b32_e32 v50, 8, v21
; SI-NEXT:    v_lshlrev_b32_e32 v37, 24, v23
; SI-NEXT:    v_lshlrev_b32_e32 v51, 24, v19
; SI-NEXT:    v_lshlrev_b32_e32 v53, 8, v29
; SI-NEXT:    v_lshlrev_b32_e32 v54, 24, v27
; SI-NEXT:    v_lshlrev_b32_e32 v19, 8, v1
; SI-NEXT:    v_lshlrev_b32_e32 v27, 8, v9
; SI-NEXT:    v_lshlrev_b32_e32 v49, 8, v17
; SI-NEXT:    v_lshlrev_b32_e32 v55, 8, v25
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr1
; SI-NEXT:    ; implicit-def: $vgpr29
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr3
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr5
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr25
; SI-NEXT:    ; implicit-def: $vgpr7
; SI-NEXT:    ; implicit-def: $vgpr48
; SI-NEXT:    s_waitcnt vmcnt(1)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v38
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_lshlrev_b32_e32 v52, 24, v39
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB106_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_and_b32_e32 v2, 0xff, v2
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v14
; SI-NEXT:    v_or_b32_e32 v0, v0, v19
; SI-NEXT:    v_or_b32_e32 v2, v33, v2
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v6
; SI-NEXT:    v_or_b32_e32 v6, v34, v5
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v10
; SI-NEXT:    v_or_b32_e32 v23, v0, v2
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v8
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v7, 0xff, v22
; SI-NEXT:    v_or_b32_e32 v0, v0, v27
; SI-NEXT:    v_or_b32_e32 v9, v36, v5
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v20
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_or_b32_e32 v5, v5, v50
; SI-NEXT:    v_or_b32_e32 v10, v37, v7
; SI-NEXT:    v_and_b32_e32 v7, 0xff, v18
; SI-NEXT:    v_or_b32_e32 v15, v0, v9
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v16
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_or_b32_e32 v0, v0, v49
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v4
; SI-NEXT:    v_or_b32_e32 v4, v31, v3
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v12
; SI-NEXT:    v_or_b32_e32 v5, v5, v10
; SI-NEXT:    v_or_b32_e32 v11, v51, v7
; SI-NEXT:    v_and_b32_e32 v7, 0xff, v28
; SI-NEXT:    v_and_b32_e32 v12, 0xff, v30
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_or_b32_e32 v1, v1, v32
; SI-NEXT:    v_or_b32_e32 v3, v3, v35
; SI-NEXT:    v_alignbit_b32 v21, v5, v11, 16
; SI-NEXT:    v_or_b32_e32 v7, v7, v53
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v12
; SI-NEXT:    v_and_b32_e32 v14, 0xff, v26
; SI-NEXT:    v_or_b32_e32 v11, v0, v11
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v24
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_or_b32_e32 v12, v52, v12
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v14
; SI-NEXT:    v_or_b32_e32 v0, v0, v55
; SI-NEXT:    v_or_b32_e32 v1, v1, v4
; SI-NEXT:    v_or_b32_e32 v3, v3, v6
; SI-NEXT:    v_or_b32_e32 v7, v7, v12
; SI-NEXT:    v_or_b32_e32 v14, v54, v14
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_alignbit_b32 v13, v1, v2, 16
; SI-NEXT:    v_alignbit_b32 v17, v3, v9, 16
; SI-NEXT:    v_alignbit_b32 v25, v7, v14, 16
; SI-NEXT:    v_or_b32_e32 v9, v0, v14
; SI-NEXT:    v_lshrrev_b32_e32 v29, 16, v4
; SI-NEXT:    v_lshrrev_b32_e32 v38, 16, v6
; SI-NEXT:    v_lshrrev_b32_e32 v39, 16, v10
; SI-NEXT:    v_lshrrev_b32_e32 v48, 16, v12
; SI-NEXT:    ; implicit-def: $vgpr0
; SI-NEXT:    ; implicit-def: $vgpr2
; SI-NEXT:    ; implicit-def: $vgpr4
; SI-NEXT:    ; implicit-def: $vgpr6
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr24
; SI-NEXT:    ; implicit-def: $vgpr26
; SI-NEXT:    ; implicit-def: $vgpr28
; SI-NEXT:    ; implicit-def: $vgpr30
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; implicit-def: $vgpr31
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr50
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr51
; SI-NEXT:    ; implicit-def: $vgpr53
; SI-NEXT:    ; implicit-def: $vgpr52
; SI-NEXT:    ; implicit-def: $vgpr54
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr27
; SI-NEXT:    ; implicit-def: $vgpr49
; SI-NEXT:    ; implicit-def: $vgpr55
; SI-NEXT:  .LBB106_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB106_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v24
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v1
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v26
; SI-NEXT:    v_or_b32_e32 v1, v55, v1
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v3
; SI-NEXT:    v_add_i32_e32 v1, vcc, 0x300, v1
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_or_b32_e32 v3, v54, v3
; SI-NEXT:    v_or_b32_e32 v1, v3, v1
; SI-NEXT:    s_mov_b32 s7, 0x3000000
; SI-NEXT:    v_add_i32_e32 v9, vcc, s7, v1
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v28
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v1
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v30
; SI-NEXT:    s_movk_i32 s6, 0x300
; SI-NEXT:    v_or_b32_e32 v1, v53, v1
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v3
; SI-NEXT:    v_add_i32_e32 v1, vcc, s6, v1
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_or_b32_e32 v3, v52, v3
; SI-NEXT:    v_or_b32_e32 v1, v3, v1
; SI-NEXT:    v_add_i32_e32 v7, vcc, s7, v1
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v16
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v1
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v18
; SI-NEXT:    v_or_b32_e32 v1, v49, v1
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v3
; SI-NEXT:    v_add_i32_e32 v1, vcc, s6, v1
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_or_b32_e32 v3, v51, v3
; SI-NEXT:    v_or_b32_e32 v1, v3, v1
; SI-NEXT:    v_add_i32_e32 v11, vcc, s7, v1
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v20
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v1
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v22
; SI-NEXT:    v_or_b32_e32 v1, v50, v1
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v3
; SI-NEXT:    v_add_i32_e32 v1, vcc, s6, v1
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_or_b32_e32 v3, v37, v3
; SI-NEXT:    v_or_b32_e32 v1, v3, v1
; SI-NEXT:    v_add_i32_e32 v5, vcc, s7, v1
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v8
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v1
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v10
; SI-NEXT:    v_or_b32_e32 v1, v27, v1
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v3
; SI-NEXT:    v_add_i32_e32 v1, vcc, s6, v1
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_or_b32_e32 v3, v36, v3
; SI-NEXT:    v_or_b32_e32 v1, v3, v1
; SI-NEXT:    v_add_i32_e32 v15, vcc, s7, v1
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v12
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v1
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v14
; SI-NEXT:    v_or_b32_e32 v1, v35, v1
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v3
; SI-NEXT:    v_add_i32_e32 v1, vcc, s6, v1
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_or_b32_e32 v3, v34, v3
; SI-NEXT:    v_or_b32_e32 v1, v3, v1
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:    v_add_i32_e32 v3, vcc, s7, v1
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v2
; SI-NEXT:    v_or_b32_e32 v0, v19, v0
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v1
; SI-NEXT:    v_add_i32_e32 v0, vcc, s6, v0
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_or_b32_e32 v1, v33, v1
; SI-NEXT:    v_or_b32_e32 v0, v1, v0
; SI-NEXT:    v_add_i32_e32 v23, vcc, s7, v0
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v4
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v6
; SI-NEXT:    v_or_b32_e32 v0, v32, v0
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v1
; SI-NEXT:    v_add_i32_e32 v0, vcc, s6, v0
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_or_b32_e32 v1, v31, v1
; SI-NEXT:    v_or_b32_e32 v0, v1, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, s7, v0
; SI-NEXT:    v_alignbit_b32 v13, v1, v23, 16
; SI-NEXT:    v_alignbit_b32 v17, v3, v15, 16
; SI-NEXT:    v_alignbit_b32 v21, v5, v11, 16
; SI-NEXT:    v_alignbit_b32 v25, v7, v9, 16
; SI-NEXT:    v_lshrrev_b32_e32 v29, 16, v1
; SI-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v39, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v48, 16, v7
; SI-NEXT:  .LBB106_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v23
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v13
; SI-NEXT:    v_or_b32_e32 v0, v0, v2
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v29
; SI-NEXT:    v_or_b32_e32 v1, v1, v2
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v15
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v17
; SI-NEXT:    v_or_b32_e32 v2, v2, v4
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v38
; SI-NEXT:    v_or_b32_e32 v3, v3, v4
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v11
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v21
; SI-NEXT:    v_or_b32_e32 v4, v4, v6
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v39
; SI-NEXT:    v_or_b32_e32 v5, v5, v6
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v9
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v25
; SI-NEXT:    v_or_b32_e32 v6, v6, v8
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v48
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v32i8_to_v16f16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_mov_b32_e32 v32, v0
; VI-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:4
; VI-NEXT:    buffer_load_ushort v39, off, s[0:3], s32
; VI-NEXT:    v_mov_b32_e32 v33, v7
; VI-NEXT:    v_mov_b32_e32 v31, v6
; VI-NEXT:    v_mov_b32_e32 v37, v5
; VI-NEXT:    v_mov_b32_e32 v36, v4
; VI-NEXT:    v_mov_b32_e32 v35, v3
; VI-NEXT:    v_mov_b32_e32 v34, v2
; VI-NEXT:    v_mov_b32_e32 v38, v1
; VI-NEXT:    s_waitcnt vmcnt(1)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v0
; VI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execnz .LBB106_3
; VI-NEXT:  ; %bb.1: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execnz .LBB106_4
; VI-NEXT:  .LBB106_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB106_3: ; %cmp.false
; VI-NEXT:    s_mov_b32 s6, 0xc0c0004
; VI-NEXT:    v_perm_b32 v1, v34, v35, s6
; VI-NEXT:    v_perm_b32 v0, v32, v38, s6
; VI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_perm_b32 v2, v31, v33, s6
; VI-NEXT:    v_or_b32_e32 v0, v0, v1
; VI-NEXT:    v_perm_b32 v1, v36, v37, s6
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_perm_b32 v3, v10, v11, s6
; VI-NEXT:    v_or_b32_e32 v1, v1, v2
; VI-NEXT:    v_perm_b32 v2, v8, v9, s6
; VI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_perm_b32 v4, v14, v15, s6
; VI-NEXT:    v_or_b32_e32 v2, v2, v3
; VI-NEXT:    v_perm_b32 v3, v12, v13, s6
; VI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_perm_b32 v5, v18, v19, s6
; VI-NEXT:    v_or_b32_e32 v3, v3, v4
; VI-NEXT:    v_perm_b32 v4, v16, v17, s6
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_perm_b32 v6, v22, v23, s6
; VI-NEXT:    v_or_b32_e32 v4, v4, v5
; VI-NEXT:    v_perm_b32 v5, v20, v21, s6
; VI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_perm_b32 v7, v26, v27, s6
; VI-NEXT:    v_or_b32_e32 v5, v5, v6
; VI-NEXT:    v_perm_b32 v6, v24, v25, s6
; VI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    v_perm_b32 v8, v30, v39, s6
; VI-NEXT:    v_or_b32_e32 v6, v6, v7
; VI-NEXT:    v_perm_b32 v7, v28, v29, s6
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; VI-NEXT:    v_or_b32_e32 v7, v7, v8
; VI-NEXT:    ; implicit-def: $vgpr32
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr34
; VI-NEXT:    ; implicit-def: $vgpr35
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr31
; VI-NEXT:    ; implicit-def: $vgpr33
; VI-NEXT:    ; implicit-def: $vgpr8
; VI-NEXT:    ; implicit-def: $vgpr9
; VI-NEXT:    ; implicit-def: $vgpr10
; VI-NEXT:    ; implicit-def: $vgpr11
; VI-NEXT:    ; implicit-def: $vgpr12
; VI-NEXT:    ; implicit-def: $vgpr13
; VI-NEXT:    ; implicit-def: $vgpr14
; VI-NEXT:    ; implicit-def: $vgpr15
; VI-NEXT:    ; implicit-def: $vgpr16
; VI-NEXT:    ; implicit-def: $vgpr17
; VI-NEXT:    ; implicit-def: $vgpr18
; VI-NEXT:    ; implicit-def: $vgpr19
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr21
; VI-NEXT:    ; implicit-def: $vgpr22
; VI-NEXT:    ; implicit-def: $vgpr23
; VI-NEXT:    ; implicit-def: $vgpr24
; VI-NEXT:    ; implicit-def: $vgpr25
; VI-NEXT:    ; implicit-def: $vgpr26
; VI-NEXT:    ; implicit-def: $vgpr27
; VI-NEXT:    ; implicit-def: $vgpr28
; VI-NEXT:    ; implicit-def: $vgpr29
; VI-NEXT:    ; implicit-def: $vgpr30
; VI-NEXT:    ; implicit-def: $vgpr39
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB106_2
; VI-NEXT:  .LBB106_4: ; %cmp.true
; VI-NEXT:    v_add_u16_e32 v0, 3, v30
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    v_lshlrev_b16_e32 v1, 8, v39
; VI-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_mov_b32_e32 v1, 0x300
; VI-NEXT:    v_add_u16_sdwa v7, v0, v1 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v0, 3, v28
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v29
; VI-NEXT:    v_or_b32_sdwa v28, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v0, 3, v26
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v27
; VI-NEXT:    v_or_b32_sdwa v0, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_sdwa v6, v0, v1 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v0, 3, v24
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v25
; VI-NEXT:    v_or_b32_sdwa v24, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v0, 3, v22
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v23
; VI-NEXT:    v_or_b32_sdwa v0, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_sdwa v5, v0, v1 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v0, 3, v20
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v21
; VI-NEXT:    v_or_b32_sdwa v20, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v0, 3, v18
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v19
; VI-NEXT:    v_or_b32_sdwa v0, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_sdwa v4, v0, v1 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v0, 3, v16
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v17
; VI-NEXT:    v_or_b32_sdwa v16, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v0, 3, v14
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v15
; VI-NEXT:    v_or_b32_sdwa v0, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_sdwa v3, v0, v1 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v0, 3, v12
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v13
; VI-NEXT:    v_or_b32_sdwa v12, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v0, 3, v10
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v11
; VI-NEXT:    v_or_b32_sdwa v0, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_sdwa v2, v0, v1 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v0, 3, v8
; VI-NEXT:    v_lshlrev_b16_e32 v8, 8, v9
; VI-NEXT:    v_or_b32_sdwa v8, v8, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v0, 3, v31
; VI-NEXT:    v_lshlrev_b16_e32 v9, 8, v33
; VI-NEXT:    v_or_b32_sdwa v0, v9, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_sdwa v9, v0, v1 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v0, 3, v36
; VI-NEXT:    v_lshlrev_b16_e32 v10, 8, v37
; VI-NEXT:    v_or_b32_sdwa v10, v10, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v0, 3, v34
; VI-NEXT:    v_lshlrev_b16_e32 v11, 8, v35
; VI-NEXT:    v_add_u16_e32 v8, 0x300, v8
; VI-NEXT:    v_or_b32_sdwa v0, v11, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_or_b32_e32 v2, v8, v2
; VI-NEXT:    v_add_u16_e32 v8, 0x300, v12
; VI-NEXT:    v_add_u16_sdwa v0, v0, v1 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v1, 3, v32
; VI-NEXT:    v_lshlrev_b16_e32 v11, 8, v38
; VI-NEXT:    v_or_b32_e32 v3, v8, v3
; VI-NEXT:    v_add_u16_e32 v8, 0x300, v16
; VI-NEXT:    v_or_b32_sdwa v1, v11, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_or_b32_e32 v4, v8, v4
; VI-NEXT:    v_add_u16_e32 v8, 0x300, v20
; VI-NEXT:    v_add_u16_e32 v1, 0x300, v1
; VI-NEXT:    v_or_b32_e32 v5, v8, v5
; VI-NEXT:    v_add_u16_e32 v8, 0x300, v24
; VI-NEXT:    v_or_b32_e32 v0, v1, v0
; VI-NEXT:    v_add_u16_e32 v1, 0x300, v10
; VI-NEXT:    v_or_b32_e32 v6, v8, v6
; VI-NEXT:    v_add_u16_e32 v8, 0x300, v28
; VI-NEXT:    v_or_b32_e32 v1, v1, v9
; VI-NEXT:    v_or_b32_e32 v7, v8, v7
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v32i8_to_v16f16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_mov_b32_e32 v37, v1
; GFX9-NEXT:    v_mov_b32_e32 v36, v0
; GFX9-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:4
; GFX9-NEXT:    buffer_load_ushort v1, off, s[0:3], s32
; GFX9-NEXT:    v_mov_b32_e32 v38, v7
; GFX9-NEXT:    v_mov_b32_e32 v31, v6
; GFX9-NEXT:    v_mov_b32_e32 v33, v5
; GFX9-NEXT:    v_mov_b32_e32 v34, v4
; GFX9-NEXT:    v_mov_b32_e32 v32, v3
; GFX9-NEXT:    v_mov_b32_e32 v35, v2
; GFX9-NEXT:    v_lshlrev_b16_e32 v39, 8, v17
; GFX9-NEXT:    v_lshlrev_b16_e32 v17, 8, v19
; GFX9-NEXT:    v_lshlrev_b16_e32 v19, 8, v23
; GFX9-NEXT:    v_lshlrev_b16_e32 v25, 8, v25
; GFX9-NEXT:    v_lshlrev_b16_e32 v23, 8, v27
; GFX9-NEXT:    s_waitcnt vmcnt(1)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v0
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    v_lshlrev_b16_e32 v27, 8, v1
; GFX9-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execnz .LBB106_3
; GFX9-NEXT:  ; %bb.1: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execnz .LBB106_4
; GFX9-NEXT:  .LBB106_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB106_3: ; %cmp.false
; GFX9-NEXT:    s_mov_b32 s6, 0xc0c0004
; GFX9-NEXT:    v_perm_b32 v0, v36, v37, s6
; GFX9-NEXT:    v_perm_b32 v1, v35, v32, s6
; GFX9-NEXT:    s_mov_b32 s7, 0x5040100
; GFX9-NEXT:    v_perm_b32 v0, v1, v0, s7
; GFX9-NEXT:    v_perm_b32 v1, v34, v33, s6
; GFX9-NEXT:    v_perm_b32 v2, v31, v38, s6
; GFX9-NEXT:    v_perm_b32 v1, v2, v1, s7
; GFX9-NEXT:    v_perm_b32 v2, v8, v9, s6
; GFX9-NEXT:    v_perm_b32 v3, v10, v11, s6
; GFX9-NEXT:    v_perm_b32 v2, v3, v2, s7
; GFX9-NEXT:    v_perm_b32 v3, v12, v13, s6
; GFX9-NEXT:    v_perm_b32 v4, v14, v15, s6
; GFX9-NEXT:    v_perm_b32 v3, v4, v3, s7
; GFX9-NEXT:    v_or_b32_sdwa v4, v16, v39 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:BYTE_0 src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v5, v18, v17 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:BYTE_0 src1_sel:DWORD
; GFX9-NEXT:    v_perm_b32 v4, v5, v4, s7
; GFX9-NEXT:    v_or_b32_sdwa v5, v22, v19 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:BYTE_0 src1_sel:DWORD
; GFX9-NEXT:    v_perm_b32 v6, v20, v21, s6
; GFX9-NEXT:    v_perm_b32 v5, v5, v6, s7
; GFX9-NEXT:    v_or_b32_sdwa v6, v24, v25 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:BYTE_0 src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v7, v26, v23 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:BYTE_0 src1_sel:DWORD
; GFX9-NEXT:    v_perm_b32 v6, v7, v6, s7
; GFX9-NEXT:    v_or_b32_sdwa v7, v30, v27 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:BYTE_0 src1_sel:DWORD
; GFX9-NEXT:    v_perm_b32 v8, v28, v29, s6
; GFX9-NEXT:    v_perm_b32 v7, v7, v8, s7
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr35
; GFX9-NEXT:    ; implicit-def: $vgpr32
; GFX9-NEXT:    ; implicit-def: $vgpr34
; GFX9-NEXT:    ; implicit-def: $vgpr33
; GFX9-NEXT:    ; implicit-def: $vgpr31
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr8
; GFX9-NEXT:    ; implicit-def: $vgpr9
; GFX9-NEXT:    ; implicit-def: $vgpr10
; GFX9-NEXT:    ; implicit-def: $vgpr11
; GFX9-NEXT:    ; implicit-def: $vgpr12
; GFX9-NEXT:    ; implicit-def: $vgpr13
; GFX9-NEXT:    ; implicit-def: $vgpr14
; GFX9-NEXT:    ; implicit-def: $vgpr15
; GFX9-NEXT:    ; implicit-def: $vgpr16
; GFX9-NEXT:    ; implicit-def: $vgpr18
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr21
; GFX9-NEXT:    ; implicit-def: $vgpr22
; GFX9-NEXT:    ; implicit-def: $vgpr24
; GFX9-NEXT:    ; implicit-def: $vgpr26
; GFX9-NEXT:    ; implicit-def: $vgpr28
; GFX9-NEXT:    ; implicit-def: $vgpr29
; GFX9-NEXT:    ; implicit-def: $vgpr30
; GFX9-NEXT:    ; implicit-def: $vgpr39
; GFX9-NEXT:    ; implicit-def: $vgpr17
; GFX9-NEXT:    ; implicit-def: $vgpr19
; GFX9-NEXT:    ; implicit-def: $vgpr25
; GFX9-NEXT:    ; implicit-def: $vgpr23
; GFX9-NEXT:    ; implicit-def: $vgpr27
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB106_2
; GFX9-NEXT:  .LBB106_4: ; %cmp.true
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v28
; GFX9-NEXT:    v_lshlrev_b16_e32 v1, 8, v29
; GFX9-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v7, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v30
; GFX9-NEXT:    v_or_b32_sdwa v0, v27, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v27, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v24
; GFX9-NEXT:    v_or_b32_sdwa v0, v25, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v6, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v26
; GFX9-NEXT:    v_or_b32_sdwa v0, v23, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v23, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v20
; GFX9-NEXT:    v_lshlrev_b16_e32 v1, 8, v21
; GFX9-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v5, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v22
; GFX9-NEXT:    v_or_b32_sdwa v0, v19, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v19, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v16
; GFX9-NEXT:    v_or_b32_sdwa v0, v39, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v4, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v18
; GFX9-NEXT:    v_or_b32_sdwa v0, v17, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v16, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v12
; GFX9-NEXT:    v_lshlrev_b16_e32 v1, 8, v13
; GFX9-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v3, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v14
; GFX9-NEXT:    v_lshlrev_b16_e32 v1, 8, v15
; GFX9-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v12, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v8
; GFX9-NEXT:    v_lshlrev_b16_e32 v1, 8, v9
; GFX9-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v2, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v10
; GFX9-NEXT:    v_lshlrev_b16_e32 v1, 8, v11
; GFX9-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v8, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v34
; GFX9-NEXT:    v_lshlrev_b16_e32 v1, 8, v33
; GFX9-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v1, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v31
; GFX9-NEXT:    v_lshlrev_b16_e32 v9, 8, v38
; GFX9-NEXT:    v_or_b32_sdwa v0, v9, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v9, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v36
; GFX9-NEXT:    v_lshlrev_b16_e32 v10, 8, v37
; GFX9-NEXT:    v_or_b32_sdwa v0, v10, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v10, 3, v35
; GFX9-NEXT:    v_lshlrev_b16_e32 v11, 8, v32
; GFX9-NEXT:    v_or_b32_sdwa v10, v11, v10 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v0, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v10, 0x300, v10
; GFX9-NEXT:    s_mov_b32 s6, 0x5040100
; GFX9-NEXT:    v_perm_b32 v0, v10, v0, s6
; GFX9-NEXT:    v_perm_b32 v1, v9, v1, s6
; GFX9-NEXT:    v_perm_b32 v2, v8, v2, s6
; GFX9-NEXT:    v_perm_b32 v3, v12, v3, s6
; GFX9-NEXT:    v_perm_b32 v4, v16, v4, s6
; GFX9-NEXT:    v_perm_b32 v5, v19, v5, s6
; GFX9-NEXT:    v_perm_b32 v6, v23, v6, s6
; GFX9-NEXT:    v_perm_b32 v7, v27, v7, s6
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v32i8_to_v16f16:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_clause 0x1
; GFX11-TRUE16-NEXT:    scratch_load_b32 v37, off, s32 offset:4
; GFX11-TRUE16-NEXT:    scratch_load_d16_hi_b16 v31, off, s32
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v27.h, v27.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v25.h, v25.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v23.h, v23.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v19.h, v19.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v17.h, v17.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v34.l, v29.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v36.l, v28.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v33.l, v20.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v17.l, v15.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v28.l, v14.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v25.l, v12.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v15.l, v11.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v27.l, v10.l
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v31.l, v9.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v35.l, v8.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v14.l, v7.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v29.l, v6.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v11.l, v5.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v19.l, v4.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v23.l, v3.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v32.l, v2.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v12.l, v1.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v20.l, v0.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v9.l, 8, v17.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v8.l, 8, v19.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v8.h, 8, v23.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v10.l, 8, v25.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v9.h, 8, v27.h
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v10.h, 8, v31.h
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v37
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB106_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB106_4
; GFX11-TRUE16-NEXT:  .LBB106_2: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB106_3: ; %cmp.false
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr29_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr14_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v3, v29, v14, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr28_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr17_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v6, v28, v17, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr19_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr11_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, v19, v11, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr32_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr23_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v2, v32, v23, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr27_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr15_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v4, v27, v15, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v1.h, v3.l
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr25_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v3, v25, v13, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_and_b16 v5.l, 0xff, v22.l
; GFX11-TRUE16-NEXT:    v_and_b16 v4.h, 0xff, v18.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v3.h, v6.l
; GFX11-TRUE16-NEXT:    v_and_b16 v6.l, 0xff, v30.l
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr12_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v0, v20, v12, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.h, v2.l
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr35_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr31_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v2, v35, v31, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_or_b16 v6.h, v5.l, v8.h
; GFX11-TRUE16-NEXT:    v_and_b16 v7.l, 0xff, v24.l
; GFX11-TRUE16-NEXT:    v_and_b16 v7.h, 0xff, v26.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.h, v4.l
; GFX11-TRUE16-NEXT:    v_and_b16 v4.l, 0xff, v16.l
; GFX11-TRUE16-NEXT:    v_or_b16 v4.h, v4.h, v8.l
; GFX11-TRUE16-NEXT:    v_or_b16 v8.l, v6.l, v10.h
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr33_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr21_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, v33, v21, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v5.h, v6.h
; GFX11-TRUE16-NEXT:    v_or_b16 v6.l, v7.l, v10.l
; GFX11-TRUE16-NEXT:    v_or_b16 v6.h, v7.h, v9.h
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr36_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr34_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v7, v36, v34, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_or_b16 v4.l, v4.l, v9.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v7.h, v8.l
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr12_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr32_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr23_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr19_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr11_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr29_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr14_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr35_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr31_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr27_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr15_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr25_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr28_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr17_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr16_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr18_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr33_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr21_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr22_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr24_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr26_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr36_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr34_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr30_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr8_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr8_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr10_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr10_hi16
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB106_2
; GFX11-TRUE16-NEXT:  .LBB106_4: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.l, v36.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.h, v30.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.h, v24.l, 3
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v1.l, 8, v34.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.l, v26.l, 3
; GFX11-TRUE16-NEXT:    v_and_b16 v0.l, 0xff, v0.l
; GFX11-TRUE16-NEXT:    v_and_b16 v0.h, 0xff, v0.h
; GFX11-TRUE16-NEXT:    v_and_b16 v1.h, 0xff, v1.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.h, v33.l, 3
; GFX11-TRUE16-NEXT:    v_and_b16 v2.l, 0xff, v2.l
; GFX11-TRUE16-NEXT:    v_or_b16 v0.l, v1.l, v0.l
; GFX11-TRUE16-NEXT:    v_or_b16 v0.h, v10.h, v0.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.l, v22.l, 3
; GFX11-TRUE16-NEXT:    v_or_b16 v1.h, v10.l, v1.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v3.l, 8, v17.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v7.l, 0x300, v0.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v7.h, 0x300, v0.h
; GFX11-TRUE16-NEXT:    v_and_b16 v0.l, 0xff, v2.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v0.h, 8, v21.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v6.l, 0x300, v1.h
; GFX11-TRUE16-NEXT:    v_and_b16 v1.l, 0xff, v1.l
; GFX11-TRUE16-NEXT:    v_or_b16 v1.h, v9.h, v2.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.l, v16.l, 3
; GFX11-TRUE16-NEXT:    v_or_b16 v0.l, v0.h, v0.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.h, v18.l, 3
; GFX11-TRUE16-NEXT:    v_or_b16 v1.l, v8.h, v1.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v6.h, 0x300, v1.h
; GFX11-TRUE16-NEXT:    v_and_b16 v1.h, 0xff, v2.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v5.l, 0x300, v0.l
; GFX11-TRUE16-NEXT:    v_and_b16 v0.l, 0xff, v0.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v5.h, 0x300, v1.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.h, v25.l, 3
; GFX11-TRUE16-NEXT:    v_or_b16 v1.l, v9.l, v1.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.h, v28.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.l, v35.l, 3
; GFX11-TRUE16-NEXT:    v_or_b16 v0.l, v8.l, v0.l
; GFX11-TRUE16-NEXT:    v_and_b16 v0.h, 0xff, v0.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v2.h, 8, v13.l
; GFX11-TRUE16-NEXT:    v_and_b16 v1.h, 0xff, v1.h
; GFX11-TRUE16-NEXT:    v_and_b16 v2.l, 0xff, v2.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v3.h, 8, v31.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v4.l, 0x300, v1.l
; GFX11-TRUE16-NEXT:    v_or_b16 v0.h, v2.h, v0.h
; GFX11-TRUE16-NEXT:    v_or_b16 v1.l, v3.l, v1.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v4.h, 0x300, v0.l
; GFX11-TRUE16-NEXT:    v_or_b16 v0.l, v3.h, v2.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.h, v27.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v3.l, 0x300, v0.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.h, v19.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.h, v20.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.l, 0x300, v0.l
; GFX11-TRUE16-NEXT:    v_and_b16 v0.l, 0xff, v1.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.h, v29.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v8.h, v32.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v3.h, 0x300, v1.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v1.l, 8, v15.l
; GFX11-TRUE16-NEXT:    v_and_b16 v0.h, 0xff, v0.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v8.l, 8, v11.l
; GFX11-TRUE16-NEXT:    v_and_b16 v1.h, 0xff, v1.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v9.l, 8, v14.l
; GFX11-TRUE16-NEXT:    v_and_b16 v2.h, 0xff, v2.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v9.h, 8, v12.l
; GFX11-TRUE16-NEXT:    v_and_b16 v8.h, 0xff, v8.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v10.l, 8, v23.l
; GFX11-TRUE16-NEXT:    v_or_b16 v0.l, v1.l, v0.l
; GFX11-TRUE16-NEXT:    v_or_b16 v0.h, v8.l, v0.h
; GFX11-TRUE16-NEXT:    v_or_b16 v1.h, v9.l, v1.h
; GFX11-TRUE16-NEXT:    v_or_b16 v8.l, v9.h, v2.h
; GFX11-TRUE16-NEXT:    v_or_b16 v8.h, v10.l, v8.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.h, 0x300, v0.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.l, 0x300, v0.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.h, 0x300, v1.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.l, 0x300, v8.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.h, 0x300, v8.h
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v32i8_to_v16f16:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v37, v1 :: v_dual_mov_b32 v34, v0
; GFX11-FAKE16-NEXT:    s_clause 0x1
; GFX11-FAKE16-NEXT:    scratch_load_b32 v0, off, s32 offset:4
; GFX11-FAKE16-NEXT:    scratch_load_u16 v1, off, s32
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v33, v7 :: v_dual_mov_b32 v38, v4
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v31, v6 :: v_dual_mov_b32 v36, v3
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v35, v5 :: v_dual_mov_b32 v32, v2
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v39, 8, v17
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v17, 8, v19
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v19, 8, v23
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v25, 8, v25
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v23, 8, v27
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(1)
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v0
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v27, 8, v1
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB106_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB106_4
; GFX11-FAKE16-NEXT:  .LBB106_2: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB106_3: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v34, v37, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v32, v36, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v38, v35, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v31, v33, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v8, v9, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v10, v11, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v1, v0, 0x5040100
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v8, 0xff, v24
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v3, v2, 0x5040100
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xff, v16
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v5, v4, 0x5040100
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xff, v18
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v9, 0xff, v26
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v10, 0xff, v30
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v7, v3, v39
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xff, v22
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v12, v13, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v14, v15, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, v4, v17
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, v20, v21, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, v3, v19
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v8, v8, v25
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v9, v9, v23
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v10, v10, v27
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, v28, v29, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v6, v5, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v4, v7, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v11, v12, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v9, v8, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v10, v13, 0x5040100
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr34
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr37
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr32
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr36
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr38
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr35
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr31
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr33
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr8
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr9
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr10
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr11
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr12
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr13
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr14
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr15
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr16
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr18
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr21
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr22
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr24
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr26
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr28
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr29
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr30
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr39
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr17
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr19
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr25
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr23
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr27
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB106_2
; GFX11-FAKE16-NEXT:  .LBB106_4: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v0, v28, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v1, v30, 3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v2, 8, v29
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v4, v26, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v5, v20, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xff, v0
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v1, 0xff, v1
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, v24, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v6, v22, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xff, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v2, v0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v1, v27, v1
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v2, v16, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xff, v3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, v23, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v7, 0x300, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v16, 0x300, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xff, v5
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v1, 8, v21
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xff, v2
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xff, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v25, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v9, 8, v9
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v1, v0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, v39, v2
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v1, v19, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v19, 0x300, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v6, 0x300, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v5, 0x300, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v0, v12, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v4, 0x300, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v2, v8, 3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v3, 8, v13
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v8, v14, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xff, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v12, 0x300, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xff, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v1, v18, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v13, v34, 3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v3, v0
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xff, v8
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v8, 8, v15
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, v9, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v9, v10, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v1, 0xff, v1
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v10, 0x300, v0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v8, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, v38, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v8, 0xff, v9
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v9, v31, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v14, v32, 3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v1, v17, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xff, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v15, 8, v35
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v9, 0xff, v9
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v13, 0xff, v13
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v17, 8, v37
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v14, 0xff, v14
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v18, 8, v36
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v20, 8, v33
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v11, 8, v11
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v15, v3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v13, v17, v13
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v14, v18, v14
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v9, v20, v9
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v8, v11, v8
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v2, 0x300, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, 0x300, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v11, 0x300, v13
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v13, 0x300, v14
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v9, 0x300, v9
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v8, 0x300, v8
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v14, 0x300, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v15, 0x300, v1
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v13, v11, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v9, v3, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v8, v2, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v14, v10, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v15, v4, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v12, v5, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v19, v6, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v16, v7, 0x5040100
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <32 x i8> %a, splat (i8 3)
  %a2 = bitcast <32 x i8> %a1 to <16 x half>
  br label %end

cmp.false:
  %a3 = bitcast <32 x i8> %a to <16 x half>
  br label %end

end:
  %phi = phi <16 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x half> %phi
}

define inreg <16 x half> @bitcast_v32i8_to_v16f16_scalar(<32 x i8> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v32i8_to_v16f16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_readfirstlane_b32 s4, v18
; SI-NEXT:    v_readfirstlane_b32 s62, v17
; SI-NEXT:    v_readfirstlane_b32 s63, v16
; SI-NEXT:    v_readfirstlane_b32 s73, v15
; SI-NEXT:    v_readfirstlane_b32 s75, v14
; SI-NEXT:    v_readfirstlane_b32 s76, v13
; SI-NEXT:    v_readfirstlane_b32 s77, v12
; SI-NEXT:    v_readfirstlane_b32 s78, v11
; SI-NEXT:    v_readfirstlane_b32 s79, v10
; SI-NEXT:    v_readfirstlane_b32 s56, v9
; SI-NEXT:    v_readfirstlane_b32 s57, v8
; SI-NEXT:    v_readfirstlane_b32 s58, v7
; SI-NEXT:    v_readfirstlane_b32 s59, v6
; SI-NEXT:    v_readfirstlane_b32 s60, v5
; SI-NEXT:    v_readfirstlane_b32 s61, v4
; SI-NEXT:    v_readfirstlane_b32 s72, v3
; SI-NEXT:    v_readfirstlane_b32 s74, v2
; SI-NEXT:    v_readfirstlane_b32 s46, v1
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    v_readfirstlane_b32 s47, v0
; SI-NEXT:    s_cbranch_scc0 .LBB107_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s8, s20, 0xff
; SI-NEXT:    s_lshl_b32 s9, s21, 8
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_and_b32 s9, s22, 0xff
; SI-NEXT:    s_and_b32 s4, s16, 0xff
; SI-NEXT:    s_lshl_b32 s5, s17, 8
; SI-NEXT:    s_lshl_b32 s9, s9, 16
; SI-NEXT:    s_lshl_b32 s11, s23, 24
; SI-NEXT:    s_or_b32 s4, s4, s5
; SI-NEXT:    s_and_b32 s5, s18, 0xff
; SI-NEXT:    s_and_b32 s8, s8, 0xffff
; SI-NEXT:    s_or_b32 s44, s11, s9
; SI-NEXT:    s_lshl_b32 s5, s5, 16
; SI-NEXT:    s_lshl_b32 s6, s19, 24
; SI-NEXT:    s_or_b32 s13, s8, s44
; SI-NEXT:    s_and_b32 s8, s28, 0xff
; SI-NEXT:    s_lshl_b32 s9, s29, 8
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_or_b32 s12, s6, s5
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_and_b32 s9, s47, 0xff
; SI-NEXT:    s_or_b32 s10, s4, s12
; SI-NEXT:    s_and_b32 s4, s24, 0xff
; SI-NEXT:    s_lshl_b32 s5, s25, 8
; SI-NEXT:    s_lshl_b32 s9, s9, 16
; SI-NEXT:    s_lshl_b32 s11, s46, 24
; SI-NEXT:    s_or_b32 s4, s4, s5
; SI-NEXT:    s_and_b32 s5, s26, 0xff
; SI-NEXT:    s_and_b32 s8, s8, 0xffff
; SI-NEXT:    s_or_b32 s45, s11, s9
; SI-NEXT:    s_lshl_b32 s5, s5, 16
; SI-NEXT:    s_lshl_b32 s6, s27, 24
; SI-NEXT:    s_or_b32 s15, s8, s45
; SI-NEXT:    s_and_b32 s8, s59, 0xff
; SI-NEXT:    s_lshl_b32 s9, s58, 8
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_or_b32 s14, s6, s5
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_and_b32 s9, s57, 0xff
; SI-NEXT:    s_or_b32 s6, s4, s14
; SI-NEXT:    s_and_b32 s4, s74, 0xff
; SI-NEXT:    s_lshl_b32 s5, s72, 8
; SI-NEXT:    s_lshl_b32 s9, s9, 16
; SI-NEXT:    s_lshl_b32 s11, s56, 24
; SI-NEXT:    s_or_b32 s4, s4, s5
; SI-NEXT:    s_and_b32 s5, s61, 0xff
; SI-NEXT:    s_and_b32 s8, s8, 0xffff
; SI-NEXT:    s_or_b32 s88, s11, s9
; SI-NEXT:    s_lshl_b32 s5, s5, 16
; SI-NEXT:    s_lshl_b32 s7, s60, 24
; SI-NEXT:    s_or_b32 s41, s8, s88
; SI-NEXT:    s_and_b32 s8, s75, 0xff
; SI-NEXT:    s_lshl_b32 s9, s73, 8
; SI-NEXT:    s_or_b32 s40, s7, s5
; SI-NEXT:    s_and_b32 s5, s79, 0xff
; SI-NEXT:    s_lshl_b32 s7, s78, 8
; SI-NEXT:    s_or_b32 s8, s8, s9
; SI-NEXT:    s_and_b32 s9, s63, 0xff
; SI-NEXT:    s_or_b32 s5, s5, s7
; SI-NEXT:    s_and_b32 s7, s77, 0xff
; SI-NEXT:    s_lshl_b32 s9, s9, 16
; SI-NEXT:    s_lshl_b32 s11, s62, 24
; SI-NEXT:    s_lshl_b32 s7, s7, 16
; SI-NEXT:    s_or_b32 s89, s11, s9
; SI-NEXT:    s_lshl_b32 s9, s76, 24
; SI-NEXT:    s_or_b32 s42, s9, s7
; SI-NEXT:    s_and_b32 s7, s8, 0xffff
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_and_b32 s5, s5, 0xffff
; SI-NEXT:    s_or_b32 s43, s7, s89
; SI-NEXT:    s_or_b32 s4, s4, s40
; SI-NEXT:    s_or_b32 s8, s5, s42
; SI-NEXT:    s_mov_b32 s11, s13
; SI-NEXT:    s_lshr_b64 s[12:13], s[12:13], 16
; SI-NEXT:    s_mov_b32 s7, s15
; SI-NEXT:    s_lshr_b64 s[14:15], s[14:15], 16
; SI-NEXT:    s_mov_b32 s5, s41
; SI-NEXT:    s_lshr_b64 s[40:41], s[40:41], 16
; SI-NEXT:    s_mov_b32 s9, s43
; SI-NEXT:    s_lshr_b64 s[42:43], s[42:43], 16
; SI-NEXT:    s_lshr_b32 s15, s44, 16
; SI-NEXT:    s_lshr_b32 s41, s45, 16
; SI-NEXT:    s_lshr_b32 s43, s88, 16
; SI-NEXT:    s_lshr_b32 s13, s89, 16
; SI-NEXT:    s_cbranch_execnz .LBB107_3
; SI-NEXT:  .LBB107_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s79, s79, 3
; SI-NEXT:    s_and_b32 s4, s79, 0xff
; SI-NEXT:    s_lshl_b32 s5, s78, 8
; SI-NEXT:    s_add_i32 s77, s77, 3
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_and_b32 s6, s77, 0xff
; SI-NEXT:    s_addk_i32 s4, 0x300
; SI-NEXT:    s_lshl_b32 s5, s76, 24
; SI-NEXT:    s_lshl_b32 s6, s6, 16
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_or_b32 s5, s5, s6
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s75, s75, 3
; SI-NEXT:    s_add_i32 s8, s4, 0x3000000
; SI-NEXT:    s_and_b32 s4, s75, 0xff
; SI-NEXT:    s_lshl_b32 s5, s73, 8
; SI-NEXT:    s_add_i32 s63, s63, 3
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_and_b32 s6, s63, 0xff
; SI-NEXT:    s_addk_i32 s4, 0x300
; SI-NEXT:    s_lshl_b32 s5, s62, 24
; SI-NEXT:    s_lshl_b32 s6, s6, 16
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_or_b32 s5, s5, s6
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s74, s74, 3
; SI-NEXT:    s_add_i32 s9, s4, 0x3000000
; SI-NEXT:    s_and_b32 s4, s74, 0xff
; SI-NEXT:    s_lshl_b32 s5, s72, 8
; SI-NEXT:    s_add_i32 s61, s61, 3
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_and_b32 s6, s61, 0xff
; SI-NEXT:    s_addk_i32 s4, 0x300
; SI-NEXT:    s_lshl_b32 s5, s60, 24
; SI-NEXT:    s_lshl_b32 s6, s6, 16
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_or_b32 s5, s5, s6
; SI-NEXT:    s_add_i32 s59, s59, 3
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_and_b32 s5, s59, 0xff
; SI-NEXT:    s_lshl_b32 s6, s58, 8
; SI-NEXT:    s_add_i32 s57, s57, 3
; SI-NEXT:    s_or_b32 s5, s6, s5
; SI-NEXT:    s_and_b32 s7, s57, 0xff
; SI-NEXT:    s_addk_i32 s5, 0x300
; SI-NEXT:    s_lshl_b32 s6, s56, 24
; SI-NEXT:    s_lshl_b32 s7, s7, 16
; SI-NEXT:    s_and_b32 s5, s5, 0xffff
; SI-NEXT:    s_or_b32 s6, s6, s7
; SI-NEXT:    s_add_i32 s24, s24, 3
; SI-NEXT:    s_or_b32 s5, s6, s5
; SI-NEXT:    s_and_b32 s6, s24, 0xff
; SI-NEXT:    s_lshl_b32 s7, s25, 8
; SI-NEXT:    s_add_i32 s26, s26, 3
; SI-NEXT:    s_or_b32 s6, s7, s6
; SI-NEXT:    s_and_b32 s10, s26, 0xff
; SI-NEXT:    s_addk_i32 s6, 0x300
; SI-NEXT:    s_lshl_b32 s7, s27, 24
; SI-NEXT:    s_lshl_b32 s10, s10, 16
; SI-NEXT:    s_and_b32 s6, s6, 0xffff
; SI-NEXT:    s_or_b32 s7, s7, s10
; SI-NEXT:    s_add_i32 s28, s28, 3
; SI-NEXT:    s_or_b32 s6, s7, s6
; SI-NEXT:    s_and_b32 s7, s28, 0xff
; SI-NEXT:    s_lshl_b32 s10, s29, 8
; SI-NEXT:    s_add_i32 s47, s47, 3
; SI-NEXT:    s_or_b32 s7, s10, s7
; SI-NEXT:    s_and_b32 s11, s47, 0xff
; SI-NEXT:    s_addk_i32 s7, 0x300
; SI-NEXT:    s_lshl_b32 s10, s46, 24
; SI-NEXT:    s_lshl_b32 s11, s11, 16
; SI-NEXT:    s_and_b32 s7, s7, 0xffff
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    s_or_b32 s7, s10, s7
; SI-NEXT:    s_and_b32 s10, s16, 0xff
; SI-NEXT:    s_lshl_b32 s11, s17, 8
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_or_b32 s10, s11, s10
; SI-NEXT:    s_and_b32 s12, s18, 0xff
; SI-NEXT:    s_addk_i32 s10, 0x300
; SI-NEXT:    s_lshl_b32 s11, s19, 24
; SI-NEXT:    s_lshl_b32 s12, s12, 16
; SI-NEXT:    s_and_b32 s10, s10, 0xffff
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_or_b32 s10, s11, s10
; SI-NEXT:    s_and_b32 s11, s20, 0xff
; SI-NEXT:    s_lshl_b32 s12, s21, 8
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_or_b32 s11, s12, s11
; SI-NEXT:    s_and_b32 s13, s22, 0xff
; SI-NEXT:    s_addk_i32 s11, 0x300
; SI-NEXT:    s_lshl_b32 s12, s23, 24
; SI-NEXT:    s_lshl_b32 s13, s13, 16
; SI-NEXT:    s_and_b32 s11, s11, 0xffff
; SI-NEXT:    s_or_b32 s12, s12, s13
; SI-NEXT:    s_or_b32 s11, s12, s11
; SI-NEXT:    s_add_i32 s4, s4, 0x3000000
; SI-NEXT:    s_add_i32 s5, s5, 0x3000000
; SI-NEXT:    s_add_i32 s6, s6, 0x3000000
; SI-NEXT:    s_add_i32 s7, s7, 0x3000000
; SI-NEXT:    s_add_i32 s10, s10, 0x3000000
; SI-NEXT:    s_add_i32 s11, s11, 0x3000000
; SI-NEXT:    s_lshr_b64 s[12:13], s[10:11], 16
; SI-NEXT:    s_lshr_b64 s[14:15], s[6:7], 16
; SI-NEXT:    s_lshr_b64 s[40:41], s[4:5], 16
; SI-NEXT:    s_lshr_b64 s[42:43], s[8:9], 16
; SI-NEXT:    s_lshr_b32 s15, s11, 16
; SI-NEXT:    s_lshr_b32 s41, s7, 16
; SI-NEXT:    s_lshr_b32 s43, s5, 16
; SI-NEXT:    s_lshr_b32 s13, s9, 16
; SI-NEXT:  .LBB107_3: ; %end
; SI-NEXT:    s_and_b32 s10, s10, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s12, 16
; SI-NEXT:    s_or_b32 s10, s10, s12
; SI-NEXT:    s_and_b32 s11, s11, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s15, 16
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    s_and_b32 s6, s6, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s14, 16
; SI-NEXT:    s_or_b32 s6, s6, s12
; SI-NEXT:    s_and_b32 s7, s7, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s41, 16
; SI-NEXT:    s_or_b32 s7, s7, s12
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s40, 16
; SI-NEXT:    s_or_b32 s4, s4, s12
; SI-NEXT:    s_and_b32 s5, s5, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s43, 16
; SI-NEXT:    s_or_b32 s5, s5, s12
; SI-NEXT:    s_and_b32 s8, s8, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s42, 16
; SI-NEXT:    s_or_b32 s8, s8, s12
; SI-NEXT:    s_and_b32 s9, s9, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s13, 16
; SI-NEXT:    s_or_b32 s9, s9, s12
; SI-NEXT:    v_mov_b32_e32 v0, s10
; SI-NEXT:    v_mov_b32_e32 v1, s11
; SI-NEXT:    v_mov_b32_e32 v2, s6
; SI-NEXT:    v_mov_b32_e32 v3, s7
; SI-NEXT:    v_mov_b32_e32 v4, s4
; SI-NEXT:    v_mov_b32_e32 v5, s5
; SI-NEXT:    v_mov_b32_e32 v6, s8
; SI-NEXT:    v_mov_b32_e32 v7, s9
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB107_4:
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr12
; SI-NEXT:    ; implicit-def: $sgpr15
; SI-NEXT:    ; implicit-def: $sgpr6
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr41
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr40
; SI-NEXT:    ; implicit-def: $sgpr43
; SI-NEXT:    ; implicit-def: $sgpr8
; SI-NEXT:    ; implicit-def: $sgpr42
; SI-NEXT:    ; implicit-def: $sgpr13
; SI-NEXT:    s_branch .LBB107_2
;
; VI-LABEL: bitcast_v32i8_to_v16f16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_readfirstlane_b32 s4, v18
; VI-NEXT:    v_readfirstlane_b32 s46, v17
; VI-NEXT:    v_readfirstlane_b32 s47, v16
; VI-NEXT:    v_readfirstlane_b32 s43, v15
; VI-NEXT:    v_readfirstlane_b32 s45, v14
; VI-NEXT:    v_readfirstlane_b32 s41, v13
; VI-NEXT:    v_readfirstlane_b32 s44, v12
; VI-NEXT:    v_readfirstlane_b32 s15, v11
; VI-NEXT:    v_readfirstlane_b32 s42, v10
; VI-NEXT:    v_readfirstlane_b32 s13, v9
; VI-NEXT:    v_readfirstlane_b32 s40, v8
; VI-NEXT:    v_readfirstlane_b32 s11, v7
; VI-NEXT:    v_readfirstlane_b32 s14, v6
; VI-NEXT:    v_readfirstlane_b32 s8, v5
; VI-NEXT:    v_readfirstlane_b32 s12, v4
; VI-NEXT:    v_readfirstlane_b32 s7, v3
; VI-NEXT:    v_readfirstlane_b32 s9, v2
; VI-NEXT:    v_readfirstlane_b32 s6, v1
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    v_readfirstlane_b32 s10, v0
; VI-NEXT:    s_cbranch_scc0 .LBB107_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_mov_b32_e32 v7, 0xc0c0004
; VI-NEXT:    v_mov_b32_e32 v1, s19
; VI-NEXT:    v_mov_b32_e32 v0, s17
; VI-NEXT:    v_perm_b32 v1, s18, v1, v7
; VI-NEXT:    v_perm_b32 v0, s16, v0, v7
; VI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_mov_b32_e32 v2, s23
; VI-NEXT:    v_or_b32_e32 v0, v0, v1
; VI-NEXT:    v_mov_b32_e32 v1, s21
; VI-NEXT:    v_perm_b32 v2, s22, v2, v7
; VI-NEXT:    v_perm_b32 v1, s20, v1, v7
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_mov_b32_e32 v3, s27
; VI-NEXT:    v_or_b32_e32 v1, v1, v2
; VI-NEXT:    v_mov_b32_e32 v2, s25
; VI-NEXT:    v_perm_b32 v3, s26, v3, v7
; VI-NEXT:    v_perm_b32 v2, s24, v2, v7
; VI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_mov_b32_e32 v4, s6
; VI-NEXT:    v_or_b32_e32 v2, v2, v3
; VI-NEXT:    v_mov_b32_e32 v3, s29
; VI-NEXT:    v_perm_b32 v4, s10, v4, v7
; VI-NEXT:    v_perm_b32 v3, s28, v3, v7
; VI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_mov_b32_e32 v5, s8
; VI-NEXT:    v_or_b32_e32 v3, v3, v4
; VI-NEXT:    v_mov_b32_e32 v4, s7
; VI-NEXT:    v_perm_b32 v5, s12, v5, v7
; VI-NEXT:    v_perm_b32 v4, s9, v4, v7
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_mov_b32_e32 v6, s13
; VI-NEXT:    v_or_b32_e32 v4, v4, v5
; VI-NEXT:    v_mov_b32_e32 v5, s11
; VI-NEXT:    v_perm_b32 v6, s40, v6, v7
; VI-NEXT:    v_perm_b32 v5, s14, v5, v7
; VI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_mov_b32_e32 v8, s41
; VI-NEXT:    v_or_b32_e32 v5, v5, v6
; VI-NEXT:    v_mov_b32_e32 v6, s15
; VI-NEXT:    v_perm_b32 v8, s44, v8, v7
; VI-NEXT:    v_perm_b32 v6, s42, v6, v7
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; VI-NEXT:    v_or_b32_e32 v6, v6, v8
; VI-NEXT:    v_mov_b32_e32 v8, s43
; VI-NEXT:    v_mov_b32_e32 v9, s46
; VI-NEXT:    v_perm_b32 v8, s45, v8, v7
; VI-NEXT:    v_perm_b32 v7, s47, v9, v7
; VI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; VI-NEXT:    v_or_b32_e32 v7, v8, v7
; VI-NEXT:    s_cbranch_execnz .LBB107_3
; VI-NEXT:  .LBB107_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s47, s47, 3
; VI-NEXT:    v_mov_b32_e32 v0, s46
; VI-NEXT:    v_mov_b32_e32 v1, 0xc0c0004
; VI-NEXT:    v_perm_b32 v2, s47, v0, v1
; VI-NEXT:    s_add_i32 s45, s45, 3
; VI-NEXT:    v_mov_b32_e32 v0, s43
; VI-NEXT:    v_perm_b32 v3, s45, v0, v1
; VI-NEXT:    s_add_i32 s44, s44, 3
; VI-NEXT:    v_mov_b32_e32 v0, s41
; VI-NEXT:    v_perm_b32 v4, s44, v0, v1
; VI-NEXT:    s_add_i32 s42, s42, 3
; VI-NEXT:    v_mov_b32_e32 v0, s15
; VI-NEXT:    v_perm_b32 v5, s42, v0, v1
; VI-NEXT:    s_add_i32 s40, s40, 3
; VI-NEXT:    v_mov_b32_e32 v0, s13
; VI-NEXT:    v_perm_b32 v6, s40, v0, v1
; VI-NEXT:    s_add_i32 s14, s14, 3
; VI-NEXT:    v_mov_b32_e32 v0, s11
; VI-NEXT:    v_perm_b32 v7, s14, v0, v1
; VI-NEXT:    s_add_i32 s12, s12, 3
; VI-NEXT:    v_mov_b32_e32 v0, s8
; VI-NEXT:    v_perm_b32 v8, s12, v0, v1
; VI-NEXT:    s_add_i32 s9, s9, 3
; VI-NEXT:    v_mov_b32_e32 v0, s7
; VI-NEXT:    v_perm_b32 v9, s9, v0, v1
; VI-NEXT:    s_add_i32 s10, s10, 3
; VI-NEXT:    v_mov_b32_e32 v0, s6
; VI-NEXT:    v_perm_b32 v10, s10, v0, v1
; VI-NEXT:    s_add_i32 s28, s28, 3
; VI-NEXT:    v_mov_b32_e32 v0, s29
; VI-NEXT:    v_perm_b32 v11, s28, v0, v1
; VI-NEXT:    s_add_i32 s26, s26, 3
; VI-NEXT:    v_mov_b32_e32 v0, s27
; VI-NEXT:    v_perm_b32 v12, s26, v0, v1
; VI-NEXT:    s_add_i32 s24, s24, 3
; VI-NEXT:    v_mov_b32_e32 v0, s25
; VI-NEXT:    v_perm_b32 v13, s24, v0, v1
; VI-NEXT:    s_add_i32 s22, s22, 3
; VI-NEXT:    v_mov_b32_e32 v0, s23
; VI-NEXT:    s_add_i32 s20, s20, 3
; VI-NEXT:    v_mov_b32_e32 v14, s21
; VI-NEXT:    s_add_i32 s18, s18, 3
; VI-NEXT:    v_mov_b32_e32 v15, s19
; VI-NEXT:    s_add_i32 s16, s16, 3
; VI-NEXT:    v_mov_b32_e32 v16, s17
; VI-NEXT:    v_perm_b32 v0, s22, v0, v1
; VI-NEXT:    v_perm_b32 v14, s20, v14, v1
; VI-NEXT:    v_perm_b32 v15, s18, v15, v1
; VI-NEXT:    v_perm_b32 v1, s16, v16, v1
; VI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; VI-NEXT:    v_add_u32_e32 v14, vcc, 0x300, v14
; VI-NEXT:    v_lshlrev_b32_e32 v15, 16, v15
; VI-NEXT:    v_add_u32_e32 v1, vcc, 0x300, v1
; VI-NEXT:    v_or_b32_sdwa v1, v15, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_or_b32_sdwa v14, v0, v14 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_add_u32_e32 v0, vcc, 0x3000000, v1
; VI-NEXT:    v_add_u32_e32 v1, vcc, 0x3000000, v14
; VI-NEXT:    v_lshlrev_b32_e32 v14, 16, v2
; VI-NEXT:    v_add_u32_e32 v15, vcc, 0x300, v3
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v4
; VI-NEXT:    v_add_u32_e32 v17, vcc, 0x300, v5
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v6
; VI-NEXT:    v_add_u32_e32 v6, vcc, 0x300, v7
; VI-NEXT:    v_lshlrev_b32_e32 v4, 16, v8
; VI-NEXT:    v_add_u32_e32 v7, vcc, 0x300, v9
; VI-NEXT:    v_lshlrev_b32_e32 v3, 16, v10
; VI-NEXT:    v_add_u32_e32 v8, vcc, 0x300, v11
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v12
; VI-NEXT:    v_add_u32_e32 v9, vcc, 0x300, v13
; VI-NEXT:    v_or_b32_sdwa v2, v2, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_or_b32_sdwa v3, v3, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_or_b32_sdwa v4, v4, v7 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_or_b32_sdwa v5, v5, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_or_b32_sdwa v6, v16, v17 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_or_b32_sdwa v7, v14, v15 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_add_u32_e32 v2, vcc, 0x3000000, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x3000000, v3
; VI-NEXT:    v_add_u32_e32 v4, vcc, 0x3000000, v4
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x3000000, v5
; VI-NEXT:    v_add_u32_e32 v6, vcc, 0x3000000, v6
; VI-NEXT:    v_add_u32_e32 v7, vcc, 0x3000000, v7
; VI-NEXT:  .LBB107_3: ; %end
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB107_4:
; VI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; VI-NEXT:    s_branch .LBB107_2
;
; GFX9-LABEL: bitcast_v32i8_to_v16f16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_readfirstlane_b32 s4, v18
; GFX9-NEXT:    v_readfirstlane_b32 s41, v17
; GFX9-NEXT:    v_readfirstlane_b32 s43, v16
; GFX9-NEXT:    v_readfirstlane_b32 s46, v15
; GFX9-NEXT:    v_readfirstlane_b32 s47, v14
; GFX9-NEXT:    v_readfirstlane_b32 s13, v13
; GFX9-NEXT:    v_readfirstlane_b32 s15, v12
; GFX9-NEXT:    v_readfirstlane_b32 s44, v11
; GFX9-NEXT:    v_readfirstlane_b32 s45, v10
; GFX9-NEXT:    v_readfirstlane_b32 s10, v9
; GFX9-NEXT:    v_readfirstlane_b32 s11, v8
; GFX9-NEXT:    v_readfirstlane_b32 s40, v7
; GFX9-NEXT:    v_readfirstlane_b32 s42, v6
; GFX9-NEXT:    v_readfirstlane_b32 s7, v5
; GFX9-NEXT:    v_readfirstlane_b32 s9, v4
; GFX9-NEXT:    v_readfirstlane_b32 s12, v3
; GFX9-NEXT:    v_readfirstlane_b32 s14, v2
; GFX9-NEXT:    v_readfirstlane_b32 s6, v1
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    v_readfirstlane_b32 s8, v0
; GFX9-NEXT:    s_cbranch_scc0 .LBB107_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    v_mov_b32_e32 v0, s17
; GFX9-NEXT:    v_mov_b32_e32 v4, 0xc0c0004
; GFX9-NEXT:    v_perm_b32 v0, s16, v0, v4
; GFX9-NEXT:    v_mov_b32_e32 v1, s19
; GFX9-NEXT:    v_perm_b32 v1, s18, v1, v4
; GFX9-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX9-NEXT:    v_lshl_or_b32 v0, v1, 16, v0
; GFX9-NEXT:    v_mov_b32_e32 v1, s21
; GFX9-NEXT:    v_perm_b32 v1, s20, v1, v4
; GFX9-NEXT:    v_mov_b32_e32 v2, s23
; GFX9-NEXT:    v_perm_b32 v2, s22, v2, v4
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; GFX9-NEXT:    v_lshl_or_b32 v1, v2, 16, v1
; GFX9-NEXT:    v_mov_b32_e32 v2, s25
; GFX9-NEXT:    v_perm_b32 v2, s24, v2, v4
; GFX9-NEXT:    v_mov_b32_e32 v3, s27
; GFX9-NEXT:    v_perm_b32 v3, s26, v3, v4
; GFX9-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX9-NEXT:    v_lshl_or_b32 v2, v3, 16, v2
; GFX9-NEXT:    v_mov_b32_e32 v3, s29
; GFX9-NEXT:    v_perm_b32 v3, s28, v3, v4
; GFX9-NEXT:    v_mov_b32_e32 v5, s6
; GFX9-NEXT:    s_and_b32 s4, s14, 0xff
; GFX9-NEXT:    s_lshl_b32 s5, s12, 8
; GFX9-NEXT:    v_perm_b32 v5, s8, v5, v4
; GFX9-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GFX9-NEXT:    s_or_b32 s4, s4, s5
; GFX9-NEXT:    s_and_b32 s5, s9, 0xff
; GFX9-NEXT:    s_lshl_b32 s56, s7, 8
; GFX9-NEXT:    v_lshl_or_b32 v3, v5, 16, v3
; GFX9-NEXT:    s_or_b32 s5, s5, s56
; GFX9-NEXT:    v_mov_b32_e32 v5, s40
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s4, s5
; GFX9-NEXT:    v_perm_b32 v5, s42, v5, v4
; GFX9-NEXT:    s_and_b32 s5, s11, 0xff
; GFX9-NEXT:    s_lshl_b32 s56, s10, 8
; GFX9-NEXT:    s_or_b32 s5, s5, s56
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX9-NEXT:    v_lshl_or_b32 v5, s5, 16, v5
; GFX9-NEXT:    s_and_b32 s5, s45, 0xff
; GFX9-NEXT:    s_lshl_b32 s56, s44, 8
; GFX9-NEXT:    s_or_b32 s5, s5, s56
; GFX9-NEXT:    s_and_b32 s56, s15, 0xff
; GFX9-NEXT:    s_lshl_b32 s57, s13, 8
; GFX9-NEXT:    s_or_b32 s56, s56, s57
; GFX9-NEXT:    v_mov_b32_e32 v6, s46
; GFX9-NEXT:    s_pack_ll_b32_b16 s5, s5, s56
; GFX9-NEXT:    v_perm_b32 v4, s47, v6, v4
; GFX9-NEXT:    s_and_b32 s56, s43, 0xff
; GFX9-NEXT:    s_lshl_b32 s57, s41, 8
; GFX9-NEXT:    s_or_b32 s56, s56, s57
; GFX9-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX9-NEXT:    v_lshl_or_b32 v7, s56, 16, v4
; GFX9-NEXT:    v_mov_b32_e32 v4, s4
; GFX9-NEXT:    v_mov_b32_e32 v6, s5
; GFX9-NEXT:    s_cbranch_execnz .LBB107_3
; GFX9-NEXT:  .LBB107_2: ; %cmp.true
; GFX9-NEXT:    s_add_i32 s47, s47, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s46
; GFX9-NEXT:    v_mov_b32_e32 v2, 0xc0c0004
; GFX9-NEXT:    v_perm_b32 v3, s47, v0, v2
; GFX9-NEXT:    s_add_i32 s43, s43, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s41
; GFX9-NEXT:    v_perm_b32 v4, s43, v0, v2
; GFX9-NEXT:    s_add_i32 s45, s45, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s44
; GFX9-NEXT:    v_perm_b32 v5, s45, v0, v2
; GFX9-NEXT:    s_add_i32 s15, s15, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s13
; GFX9-NEXT:    v_perm_b32 v6, s15, v0, v2
; GFX9-NEXT:    s_add_i32 s42, s42, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s40
; GFX9-NEXT:    v_perm_b32 v7, s42, v0, v2
; GFX9-NEXT:    s_add_i32 s11, s11, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s10
; GFX9-NEXT:    v_perm_b32 v8, s11, v0, v2
; GFX9-NEXT:    s_add_i32 s14, s14, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s12
; GFX9-NEXT:    v_perm_b32 v9, s14, v0, v2
; GFX9-NEXT:    s_add_i32 s9, s9, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s7
; GFX9-NEXT:    v_perm_b32 v10, s9, v0, v2
; GFX9-NEXT:    s_add_i32 s28, s28, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s29
; GFX9-NEXT:    v_perm_b32 v11, s28, v0, v2
; GFX9-NEXT:    s_add_i32 s20, s20, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s21
; GFX9-NEXT:    v_perm_b32 v0, s20, v0, v2
; GFX9-NEXT:    v_add_u32_e32 v1, 0x300, v0
; GFX9-NEXT:    s_add_i32 s22, s22, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s23
; GFX9-NEXT:    v_perm_b32 v0, s22, v0, v2
; GFX9-NEXT:    v_add_u32_e32 v12, 0x300, v0
; GFX9-NEXT:    s_add_i32 s16, s16, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s17
; GFX9-NEXT:    v_perm_b32 v0, s16, v0, v2
; GFX9-NEXT:    s_add_i32 s18, s18, 3
; GFX9-NEXT:    v_mov_b32_e32 v13, s19
; GFX9-NEXT:    v_add_u32_e32 v0, 0x300, v0
; GFX9-NEXT:    v_perm_b32 v13, s18, v13, v2
; GFX9-NEXT:    v_add_u32_e32 v13, 0x300, v13
; GFX9-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX9-NEXT:    v_lshl_or_b32 v0, v13, 16, v0
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; GFX9-NEXT:    s_add_i32 s24, s24, 3
; GFX9-NEXT:    v_mov_b32_e32 v13, s25
; GFX9-NEXT:    v_add_u32_e32 v16, 0x300, v5
; GFX9-NEXT:    v_add_u32_e32 v5, 0x300, v7
; GFX9-NEXT:    s_add_i32 s8, s8, 3
; GFX9-NEXT:    v_lshl_or_b32 v1, v12, 16, v1
; GFX9-NEXT:    v_mov_b32_e32 v12, s6
; GFX9-NEXT:    v_perm_b32 v13, s24, v13, v2
; GFX9-NEXT:    s_add_i32 s26, s26, 3
; GFX9-NEXT:    v_mov_b32_e32 v14, s27
; GFX9-NEXT:    v_add_u32_e32 v7, 0x300, v8
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX9-NEXT:    v_perm_b32 v12, s8, v12, v2
; GFX9-NEXT:    v_perm_b32 v2, s26, v14, v2
; GFX9-NEXT:    v_add_u32_e32 v14, 0x300, v3
; GFX9-NEXT:    v_add_u32_e32 v15, 0x300, v4
; GFX9-NEXT:    v_add_u32_e32 v6, 0x300, v6
; GFX9-NEXT:    v_add_u32_e32 v4, 0x300, v9
; GFX9-NEXT:    v_add_u32_e32 v8, 0x300, v10
; GFX9-NEXT:    v_add_u32_e32 v3, 0x300, v11
; GFX9-NEXT:    v_add_u32_e32 v10, 0x300, v13
; GFX9-NEXT:    v_lshl_or_b32 v5, v7, 16, v5
; GFX9-NEXT:    v_and_b32_e32 v7, 0xffff, v16
; GFX9-NEXT:    v_add_u32_e32 v9, 0x300, v12
; GFX9-NEXT:    v_add_u32_e32 v2, 0x300, v2
; GFX9-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; GFX9-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GFX9-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX9-NEXT:    v_lshl_or_b32 v6, v6, 16, v7
; GFX9-NEXT:    v_and_b32_e32 v7, 0xffff, v14
; GFX9-NEXT:    v_lshl_or_b32 v2, v2, 16, v10
; GFX9-NEXT:    v_lshl_or_b32 v3, v9, 16, v3
; GFX9-NEXT:    v_lshl_or_b32 v4, v8, 16, v4
; GFX9-NEXT:    v_lshl_or_b32 v7, v15, 16, v7
; GFX9-NEXT:  .LBB107_3: ; %end
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB107_4:
; GFX9-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX9-NEXT:    s_branch .LBB107_2
;
; GFX11-TRUE16-LABEL: bitcast_v32i8_to_v16f16_scalar:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s42, v14
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s4, v13
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr12_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s7, v12
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr11_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s5, v11
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr10_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s8, v10
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s6, v9
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr8_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s11, v8
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr7_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s10, v7
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr6_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s14, v6
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr5_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s9, v5
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr4_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s12, v4
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr3_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s40, v3
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr2_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s41, v2
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr1_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s13, v1
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr0_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s15, v0
; GFX11-TRUE16-NEXT:    s_cmp_lg_u32 s42, 0
; GFX11-TRUE16-NEXT:    s_mov_b32 s42, 0
; GFX11-TRUE16-NEXT:    s_cbranch_scc0 .LBB107_4
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v4, 0xc0c0004
; GFX11-TRUE16-NEXT:    s_and_b32 s43, s28, 0xff
; GFX11-TRUE16-NEXT:    s_lshl_b32 s44, s29, 8
; GFX11-TRUE16-NEXT:    s_and_b32 s45, s15, 0xff
; GFX11-TRUE16-NEXT:    s_lshl_b32 s46, s13, 8
; GFX11-TRUE16-NEXT:    s_or_b32 s43, s43, s44
; GFX11-TRUE16-NEXT:    s_or_b32 s44, s45, s46
; GFX11-TRUE16-NEXT:    v_perm_b32 v6, s18, s19, v4
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s43, s43, s44
; GFX11-TRUE16-NEXT:    s_and_b32 s44, s12, 0xff
; GFX11-TRUE16-NEXT:    s_lshl_b32 s45, s9, 8
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, s2, s3, v4
; GFX11-TRUE16-NEXT:    s_or_b32 s44, s44, s45
; GFX11-TRUE16-NEXT:    s_and_b32 s45, s14, 0xff
; GFX11-TRUE16-NEXT:    s_lshl_b32 s46, s10, 8
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, s16, s17, v4
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v1.h, v6.l
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v6, s44
; GFX11-TRUE16-NEXT:    s_or_b32 s44, s45, s46
; GFX11-TRUE16-NEXT:    s_and_b32 s45, s7, 0xff
; GFX11-TRUE16-NEXT:    s_lshl_b32 s46, s4, 8
; GFX11-TRUE16-NEXT:    v_perm_b32 v0, s0, s1, v4
; GFX11-TRUE16-NEXT:    s_or_b32 s45, s45, s46
; GFX11-TRUE16-NEXT:    v_perm_b32 v7, s22, s23, v4
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.h, v5.l
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, s26, s27, v4
; GFX11-TRUE16-NEXT:    s_and_b32 s47, s11, 0xff
; GFX11-TRUE16-NEXT:    s_lshl_b32 s46, s6, 8
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v8, s45
; GFX11-TRUE16-NEXT:    s_or_b32 s45, s47, s46
; GFX11-TRUE16-NEXT:    v_perm_b32 v2, s20, s21, v4
; GFX11-TRUE16-NEXT:    v_perm_b32 v3, s24, s25, v4
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s44, s44, s45
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.h, v7.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v3.h, v5.l
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, s41, s40, v4
; GFX11-TRUE16-NEXT:    v_perm_b32 v7, s8, s5, v4
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v5.h, v6.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v7.h, v8.l
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v4, s43
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v6, s44
; GFX11-TRUE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s42
; GFX11-TRUE16-NEXT:    s_cbranch_vccnz .LBB107_3
; GFX11-TRUE16-NEXT:  .LBB107_2: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v0, 0xc0c0004
; GFX11-TRUE16-NEXT:    s_add_i32 s8, s8, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s41, s41, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s7, s7, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s11, s11, 3
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, s8, s5, v0
; GFX11-TRUE16-NEXT:    s_add_i32 s28, s28, 3
; GFX11-TRUE16-NEXT:    v_perm_b32 v2, s7, s4, v0
; GFX11-TRUE16-NEXT:    v_perm_b32 v4, s11, s6, v0
; GFX11-TRUE16-NEXT:    s_add_i32 s15, s15, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v7, 0x300, v1
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, s41, s40, v0
; GFX11-TRUE16-NEXT:    s_add_i32 s20, s20, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v9, 0x300, v2
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v10, 0x300, v4
; GFX11-TRUE16-NEXT:    v_perm_b32 v2, s15, s13, v0
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v5, 0x300, v1
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, s28, s29, v0
; GFX11-TRUE16-NEXT:    s_add_i32 s14, s14, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s12, s12, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s26, s26, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s22, s22, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v4, 0x300, v1
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, s20, s21, v0
; GFX11-TRUE16-NEXT:    s_add_i32 s2, s2, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s18, s18, 3
; GFX11-TRUE16-NEXT:    v_perm_b32 v3, s14, s10, v0
; GFX11-TRUE16-NEXT:    v_perm_b32 v8, s12, s9, v0
; GFX11-TRUE16-NEXT:    v_perm_b32 v11, s26, s27, v0
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v12, 0x300, v2
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, 0x300, v1
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, s22, s23, v0
; GFX11-TRUE16-NEXT:    v_perm_b32 v13, s2, s3, v0
; GFX11-TRUE16-NEXT:    v_perm_b32 v14, s18, s19, v0
; GFX11-TRUE16-NEXT:    s_add_i32 s24, s24, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s16, s16, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s0, s0, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, 0x300, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v3, s24, s25, v0
; GFX11-TRUE16-NEXT:    v_perm_b32 v15, s16, s17, v0
; GFX11-TRUE16-NEXT:    v_perm_b32 v0, s0, s1, v0
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v8, 0x300, v8
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v11, 0x300, v11
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v13, 0x300, v13
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v14, 0x300, v14
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v16, 0x300, v1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 0x300, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, 0x300, v15
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v0, 0x300, v0
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.h, v13.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v1.h, v14.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.h, v16.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v3.h, v11.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v4.h, v12.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v5.h, v8.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v6.h, v10.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v7.h, v9.l
; GFX11-TRUE16-NEXT:  .LBB107_3: ; %end
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB107_4:
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-TRUE16-NEXT:    s_branch .LBB107_2
;
; GFX11-FAKE16-LABEL: bitcast_v32i8_to_v16f16_scalar:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s42, v14
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s10, v13
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s14, v12
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s12, v11
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s41, v10
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s6, v9
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s11, v8
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s13, v7
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s40, v6
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s4, v5
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s7, v4
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s8, v3
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s15, v2
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s5, v1
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s9, v0
; GFX11-FAKE16-NEXT:    s_cmp_lg_u32 s42, 0
; GFX11-FAKE16-NEXT:    s_mov_b32 s42, 0
; GFX11-FAKE16-NEXT:    s_cbranch_scc0 .LBB107_4
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v4, 0xc0c0004
; GFX11-FAKE16-NEXT:    s_and_b32 s43, s28, 0xff
; GFX11-FAKE16-NEXT:    s_lshl_b32 s44, s29, 8
; GFX11-FAKE16-NEXT:    s_lshl_b32 s45, s5, 8
; GFX11-FAKE16-NEXT:    s_or_b32 s43, s43, s44
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, s0, s1, v4
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, s16, s17, v4
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, s20, s21, v4
; GFX11-FAKE16-NEXT:    s_and_b32 s44, s9, 0xff
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, s2, s3, v4
; GFX11-FAKE16-NEXT:    s_or_b32 s44, s44, s45
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, s18, s19, v4
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, s22, s23, v4
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s43, s43, s44
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX11-FAKE16-NEXT:    s_and_b32 s46, s7, 0xff
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v0, v1, 16, v0
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v1, v3, 16, v2
; GFX11-FAKE16-NEXT:    s_lshl_b32 s47, s4, 8
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v2, v6, 16, v5
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, s15, s8, v4
; GFX11-FAKE16-NEXT:    s_or_b32 s45, s46, s47
; GFX11-FAKE16-NEXT:    s_and_b32 s44, s40, 0xff
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, s24, s25, v4
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, s26, s27, v4
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, s41, s12, v4
; GFX11-FAKE16-NEXT:    s_lshl_b32 s46, s6, 8
; GFX11-FAKE16-NEXT:    s_and_b32 s47, s14, 0xff
; GFX11-FAKE16-NEXT:    s_lshl_b32 s56, s10, 8
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v5, s45, 16, v5
; GFX11-FAKE16-NEXT:    s_lshl_b32 s45, s13, 8
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX11-FAKE16-NEXT:    s_or_b32 s44, s44, s45
; GFX11-FAKE16-NEXT:    s_and_b32 s45, s11, 0xff
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(SKIP_2) | instid1(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_or_b32 s45, s45, s46
; GFX11-FAKE16-NEXT:    s_or_b32 s46, s47, s56
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s44, s44, s45
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v6, s44 :: v_dual_and_b32 v7, 0xffff, v7
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v3, v8, 16, v7
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v7, s46, 16, v4
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v4, s43
; GFX11-FAKE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s42
; GFX11-FAKE16-NEXT:    s_cbranch_vccnz .LBB107_3
; GFX11-FAKE16-NEXT:  .LBB107_2: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v0, 0xc0c0004
; GFX11-FAKE16-NEXT:    s_add_i32 s41, s41, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s14, s14, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s11, s11, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s15, s15, 3
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, s41, s12, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, s14, s10, v0
; GFX11-FAKE16-NEXT:    s_add_i32 s20, s20, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s16, s16, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s0, s0, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, 0x300, v1
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, s11, s6, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v7, 0x300, v2
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, s15, s8, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, s16, s17, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v14, s0, s1, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v9, 0x300, v1
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, s20, s21, v0
; GFX11-FAKE16-NEXT:    s_add_i32 s40, s40, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s7, s7, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s28, s28, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s9, s9, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s24, s24, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s26, s26, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s22, s22, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s18, s18, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s2, s2, 3
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, s40, s13, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, s7, s4, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, s28, s29, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, s9, s5, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v10, 0x300, v2
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, s24, s25, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, s26, s27, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v1, 0x300, v1
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, s22, s23, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v15, s18, s19, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, s2, s3, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v14, 0x300, v14
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v13, 0x300, v13
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, 0x300, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v6, 0x300, v6
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v12, 0x300, v12
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v15, 0x300, v15
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v0, 0x300, v0
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v16, 0xffff, v1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v17, 0x300, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v5, 0x300, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v8, 0x300, v8
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v11, 0x300, v11
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v0, v0, 16, v14
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v1, v15, 16, v13
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v2, v12, 16, v16
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v12, 0xffff, v17
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v13, 0xffff, v3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v14, 0xffff, v4
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v3, v11, 16, v12
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v4, v8, 16, v6
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v5, v5, 16, v10
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v6, v9, 16, v13
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v7, v7, 16, v14
; GFX11-FAKE16-NEXT:  .LBB107_3: ; %end
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB107_4:
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-FAKE16-NEXT:    s_branch .LBB107_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <32 x i8> %a, splat (i8 3)
  %a2 = bitcast <32 x i8> %a1 to <16 x half>
  br label %end

cmp.false:
  %a3 = bitcast <32 x i8> %a to <16 x half>
  br label %end

end:
  %phi = phi <16 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x half> %phi
}

define <32 x i8> @bitcast_v16bf16_to_v32i8(<16 x bfloat> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v16bf16_to_v32i8:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_and_b32_e32 v9, 0xffff0000, v7
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_and_b32_e32 v10, 0xffff0000, v6
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_and_b32_e32 v11, 0xffff0000, v5
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v12, 0xffff0000, v4
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_and_b32_e32 v13, 0xffff0000, v3
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_and_b32_e32 v14, 0xffff0000, v2
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_and_b32_e32 v15, 0xffff0000, v1
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_and_b32_e32 v16, 0xffff0000, v0
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; SI-NEXT:    v_mul_f32_e32 v35, 1.0, v16
; SI-NEXT:    v_mul_f32_e32 v36, 1.0, v0
; SI-NEXT:    v_mul_f32_e32 v32, 1.0, v15
; SI-NEXT:    v_mul_f32_e32 v34, 1.0, v1
; SI-NEXT:    v_mul_f32_e32 v39, 1.0, v14
; SI-NEXT:    v_mul_f32_e32 v48, 1.0, v2
; SI-NEXT:    v_mul_f32_e32 v33, 1.0, v13
; SI-NEXT:    v_mul_f32_e32 v38, 1.0, v3
; SI-NEXT:    v_mul_f32_e32 v51, 1.0, v12
; SI-NEXT:    v_mul_f32_e32 v52, 1.0, v4
; SI-NEXT:    v_mul_f32_e32 v37, 1.0, v11
; SI-NEXT:    v_mul_f32_e32 v50, 1.0, v5
; SI-NEXT:    v_mul_f32_e32 v54, 1.0, v10
; SI-NEXT:    v_mul_f32_e32 v55, 1.0, v6
; SI-NEXT:    v_mul_f32_e32 v49, 1.0, v9
; SI-NEXT:    v_mul_f32_e32 v53, 1.0, v7
; SI-NEXT:    ; implicit-def: $vgpr0
; SI-NEXT:    ; implicit-def: $vgpr1
; SI-NEXT:    ; implicit-def: $vgpr2
; SI-NEXT:    ; implicit-def: $vgpr3
; SI-NEXT:    ; implicit-def: $vgpr4
; SI-NEXT:    ; implicit-def: $vgpr5
; SI-NEXT:    ; implicit-def: $vgpr6
; SI-NEXT:    ; implicit-def: $vgpr7
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr24
; SI-NEXT:    ; implicit-def: $vgpr25
; SI-NEXT:    ; implicit-def: $vgpr26
; SI-NEXT:    ; implicit-def: $vgpr27
; SI-NEXT:    ; implicit-def: $vgpr28
; SI-NEXT:    ; implicit-def: $vgpr29
; SI-NEXT:    ; implicit-def: $vgpr30
; SI-NEXT:    ; implicit-def: $vgpr31
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB108_3
; SI-NEXT:  ; %bb.1: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execnz .LBB108_4
; SI-NEXT:  .LBB108_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB108_3: ; %cmp.false
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v39
; SI-NEXT:    v_alignbit_b32 v8, v5, v48, 16
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v51
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v35
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v32
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v33
; SI-NEXT:    v_alignbit_b32 v16, v5, v52, 16
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v37
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v54
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v49
; SI-NEXT:    v_alignbit_b32 v0, v0, v36, 16
; SI-NEXT:    v_alignbit_b32 v4, v6, v34, 16
; SI-NEXT:    v_alignbit_b32 v12, v14, v38, 16
; SI-NEXT:    v_alignbit_b32 v20, v22, v50, 16
; SI-NEXT:    v_alignbit_b32 v24, v5, v55, 16
; SI-NEXT:    v_alignbit_b32 v28, v30, v53, 16
; SI-NEXT:    v_alignbit_b32 v3, v4, v0, 24
; SI-NEXT:    v_alignbit_b32 v2, v4, v0, 16
; SI-NEXT:    v_alignbit_b32 v1, v4, v0, 8
; SI-NEXT:    v_alignbit_b32 v11, v12, v8, 24
; SI-NEXT:    v_alignbit_b32 v10, v12, v8, 16
; SI-NEXT:    v_alignbit_b32 v9, v12, v8, 8
; SI-NEXT:    v_alignbit_b32 v19, v20, v16, 24
; SI-NEXT:    v_alignbit_b32 v18, v20, v16, 16
; SI-NEXT:    v_alignbit_b32 v17, v20, v16, 8
; SI-NEXT:    v_alignbit_b32 v27, v28, v24, 24
; SI-NEXT:    v_alignbit_b32 v26, v28, v24, 16
; SI-NEXT:    v_alignbit_b32 v25, v28, v24, 8
; SI-NEXT:    v_lshrrev_b32_e32 v7, 24, v32
; SI-NEXT:    v_lshrrev_b32_e32 v5, 8, v4
; SI-NEXT:    v_lshrrev_b32_e32 v15, 24, v33
; SI-NEXT:    v_lshrrev_b32_e32 v13, 8, v12
; SI-NEXT:    v_lshrrev_b32_e32 v23, 24, v37
; SI-NEXT:    v_lshrrev_b32_e32 v21, 8, v20
; SI-NEXT:    v_lshrrev_b32_e32 v31, 24, v49
; SI-NEXT:    v_lshrrev_b32_e32 v29, 8, v28
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:    ; implicit-def: $vgpr48
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr51
; SI-NEXT:    ; implicit-def: $vgpr52
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr50
; SI-NEXT:    ; implicit-def: $vgpr54
; SI-NEXT:    ; implicit-def: $vgpr55
; SI-NEXT:    ; implicit-def: $vgpr49
; SI-NEXT:    ; implicit-def: $vgpr53
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB108_2
; SI-NEXT:  .LBB108_4: ; %cmp.true
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v54
; SI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v55
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_alignbit_b32 v24, v1, v0, 16
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v49
; SI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v53
; SI-NEXT:    v_add_f32_e32 v31, 0x40c00000, v1
; SI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v31
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v51
; SI-NEXT:    v_alignbit_b32 v28, v30, v0, 16
; SI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v52
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_alignbit_b32 v16, v1, v0, 16
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v37
; SI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v50
; SI-NEXT:    v_add_f32_e32 v23, 0x40c00000, v1
; SI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v23
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v39
; SI-NEXT:    v_alignbit_b32 v20, v22, v0, 16
; SI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v48
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_alignbit_b32 v8, v1, v0, 16
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v33
; SI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v38
; SI-NEXT:    v_add_f32_e32 v15, 0x40c00000, v1
; SI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v15
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v35
; SI-NEXT:    v_alignbit_b32 v12, v14, v0, 16
; SI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v36
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v32
; SI-NEXT:    v_alignbit_b32 v0, v1, v0, 16
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v34
; SI-NEXT:    v_add_f32_e32 v7, 0x40c00000, v2
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v7
; SI-NEXT:    v_alignbit_b32 v4, v6, v1, 16
; SI-NEXT:    v_alignbit_b32 v3, v4, v0, 24
; SI-NEXT:    v_alignbit_b32 v2, v4, v0, 16
; SI-NEXT:    v_alignbit_b32 v1, v4, v0, 8
; SI-NEXT:    v_alignbit_b32 v11, v12, v8, 24
; SI-NEXT:    v_alignbit_b32 v10, v12, v8, 16
; SI-NEXT:    v_alignbit_b32 v9, v12, v8, 8
; SI-NEXT:    v_alignbit_b32 v19, v20, v16, 24
; SI-NEXT:    v_alignbit_b32 v18, v20, v16, 16
; SI-NEXT:    v_alignbit_b32 v17, v20, v16, 8
; SI-NEXT:    v_alignbit_b32 v27, v28, v24, 24
; SI-NEXT:    v_alignbit_b32 v26, v28, v24, 16
; SI-NEXT:    v_alignbit_b32 v25, v28, v24, 8
; SI-NEXT:    v_lshrrev_b32_e32 v5, 8, v4
; SI-NEXT:    v_lshrrev_b32_e32 v13, 8, v12
; SI-NEXT:    v_lshrrev_b32_e32 v21, 8, v20
; SI-NEXT:    v_lshrrev_b32_e32 v29, 8, v28
; SI-NEXT:    v_lshrrev_b32_e32 v7, 24, v7
; SI-NEXT:    v_lshrrev_b32_e32 v15, 24, v15
; SI-NEXT:    v_lshrrev_b32_e32 v23, 24, v23
; SI-NEXT:    v_lshrrev_b32_e32 v31, 24, v31
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v16bf16_to_v32i8:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_mov_b32_e32 v33, v5
; VI-NEXT:    v_mov_b32_e32 v32, v4
; VI-NEXT:    v_mov_b32_e32 v35, v3
; VI-NEXT:    v_mov_b32_e32 v34, v2
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr2
; VI-NEXT:    ; implicit-def: $vgpr5
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr9
; VI-NEXT:    ; implicit-def: $vgpr10
; VI-NEXT:    ; implicit-def: $vgpr13
; VI-NEXT:    ; implicit-def: $vgpr14
; VI-NEXT:    ; implicit-def: $vgpr15
; VI-NEXT:    ; implicit-def: $vgpr17
; VI-NEXT:    ; implicit-def: $vgpr18
; VI-NEXT:    ; implicit-def: $vgpr21
; VI-NEXT:    ; implicit-def: $vgpr22
; VI-NEXT:    ; implicit-def: $vgpr23
; VI-NEXT:    ; implicit-def: $vgpr25
; VI-NEXT:    ; implicit-def: $vgpr26
; VI-NEXT:    ; implicit-def: $vgpr29
; VI-NEXT:    ; implicit-def: $vgpr30
; VI-NEXT:    ; implicit-def: $vgpr31
; VI-NEXT:    ; implicit-def: $vgpr3
; VI-NEXT:    ; implicit-def: $vgpr11
; VI-NEXT:    ; implicit-def: $vgpr19
; VI-NEXT:    ; implicit-def: $vgpr27
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB108_2
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v25, 8, v6
; VI-NEXT:    v_lshrrev_b32_e32 v23, 24, v33
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v33
; VI-NEXT:    v_lshrrev_b32_e32 v21, 8, v33
; VI-NEXT:    v_lshrrev_b32_e32 v18, 16, v32
; VI-NEXT:    v_lshrrev_b32_e32 v17, 8, v32
; VI-NEXT:    v_lshrrev_b32_e32 v15, 24, v35
; VI-NEXT:    v_lshrrev_b32_e32 v14, 16, v35
; VI-NEXT:    v_lshrrev_b32_e32 v13, 8, v35
; VI-NEXT:    v_lshrrev_b32_e32 v10, 16, v34
; VI-NEXT:    v_lshrrev_b32_e32 v9, 8, v34
; VI-NEXT:    v_lshrrev_b32_e32 v36, 24, v1
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; VI-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; VI-NEXT:    v_lshrrev_b32_e32 v38, 8, v0
; VI-NEXT:    v_lshrrev_b64 v[27:28], 24, v[6:7]
; VI-NEXT:    v_lshrrev_b64 v[19:20], 24, v[32:33]
; VI-NEXT:    v_lshrrev_b64 v[11:12], 24, v[34:35]
; VI-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; VI-NEXT:  .LBB108_2: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB108_4
; VI-NEXT:  ; %bb.3: ; %cmp.true
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v1
; VI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; VI-NEXT:    v_bfe_u32 v3, v1, 16, 1
; VI-NEXT:    s_movk_i32 s6, 0x7fff
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v1
; VI-NEXT:    v_add_u32_e32 v3, vcc, s6, v3
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v1
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; VI-NEXT:    v_cndmask_b32_e32 v1, v3, v4, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_alignbit_b32 v1, v1, v2, 16
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v0
; VI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, s6, v3
; VI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; VI-NEXT:    v_bfe_u32 v3, v0, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v0
; VI-NEXT:    v_add_u32_e32 v3, vcc, s6, v3
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v0
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; VI-NEXT:    v_cndmask_b32_e32 v0, v3, v4, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; VI-NEXT:    v_alignbit_b32 v0, v0, v2, 16
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v35
; VI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, s6, v3
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; VI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v35
; VI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; VI-NEXT:    v_bfe_u32 v4, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v4, vcc, v4, v3
; VI-NEXT:    v_add_u32_e32 v4, vcc, s6, v4
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v4, v5, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_alignbit_b32 v35, v3, v2, 16
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v34
; VI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, s6, v3
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; VI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v34
; VI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; VI-NEXT:    v_bfe_u32 v4, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v4, vcc, v4, v3
; VI-NEXT:    v_add_u32_e32 v4, vcc, s6, v4
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v4, v5, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_alignbit_b32 v34, v3, v2, 16
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v33
; VI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, s6, v3
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; VI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v33
; VI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; VI-NEXT:    v_bfe_u32 v4, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v4, vcc, v4, v3
; VI-NEXT:    v_add_u32_e32 v4, vcc, s6, v4
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v4, v5, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_alignbit_b32 v33, v3, v2, 16
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v32
; VI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, s6, v3
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; VI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v32
; VI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; VI-NEXT:    v_bfe_u32 v4, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v4, vcc, v4, v3
; VI-NEXT:    v_add_u32_e32 v4, vcc, s6, v4
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v4, v5, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_alignbit_b32 v32, v3, v2, 16
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v7
; VI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, s6, v3
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; VI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v7
; VI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; VI-NEXT:    v_bfe_u32 v4, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v4, vcc, v4, v3
; VI-NEXT:    v_add_u32_e32 v4, vcc, s6, v4
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v4, v5, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_alignbit_b32 v7, v3, v2, 16
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v6
; VI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, s6, v3
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v4, vcc
; VI-NEXT:    v_and_b32_e32 v3, 0xffff0000, v6
; VI-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; VI-NEXT:    v_bfe_u32 v4, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v4, vcc, v4, v3
; VI-NEXT:    v_add_u32_e32 v4, vcc, s6, v4
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v4, v5, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_alignbit_b32 v6, v3, v2, 16
; VI-NEXT:    v_lshrrev_b64 v[27:28], 24, v[6:7]
; VI-NEXT:    v_lshrrev_b64 v[19:20], 24, v[32:33]
; VI-NEXT:    v_lshrrev_b64 v[11:12], 24, v[34:35]
; VI-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; VI-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v25, 8, v6
; VI-NEXT:    v_lshrrev_b32_e32 v23, 24, v33
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v33
; VI-NEXT:    v_lshrrev_b32_e32 v21, 8, v33
; VI-NEXT:    v_lshrrev_b32_e32 v18, 16, v32
; VI-NEXT:    v_lshrrev_b32_e32 v17, 8, v32
; VI-NEXT:    v_lshrrev_b32_e32 v15, 24, v35
; VI-NEXT:    v_lshrrev_b32_e32 v14, 16, v35
; VI-NEXT:    v_lshrrev_b32_e32 v13, 8, v35
; VI-NEXT:    v_lshrrev_b32_e32 v10, 16, v34
; VI-NEXT:    v_lshrrev_b32_e32 v9, 8, v34
; VI-NEXT:    v_lshrrev_b32_e32 v36, 24, v1
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; VI-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; VI-NEXT:    v_lshrrev_b32_e32 v38, 8, v0
; VI-NEXT:  .LBB108_4: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    v_mov_b32_e32 v4, v1
; VI-NEXT:    v_mov_b32_e32 v8, v34
; VI-NEXT:    v_mov_b32_e32 v12, v35
; VI-NEXT:    v_mov_b32_e32 v16, v32
; VI-NEXT:    v_mov_b32_e32 v20, v33
; VI-NEXT:    v_mov_b32_e32 v24, v6
; VI-NEXT:    v_mov_b32_e32 v28, v7
; VI-NEXT:    v_mov_b32_e32 v1, v38
; VI-NEXT:    v_mov_b32_e32 v6, v37
; VI-NEXT:    v_mov_b32_e32 v7, v36
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16bf16_to_v32i8:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_mov_b32_e32 v33, v5
; GFX9-NEXT:    v_mov_b32_e32 v32, v4
; GFX9-NEXT:    v_mov_b32_e32 v36, v3
; GFX9-NEXT:    v_mov_b32_e32 v35, v2
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v8
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr2
; GFX9-NEXT:    ; implicit-def: $vgpr5
; GFX9-NEXT:    ; implicit-def: $vgpr34
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr9
; GFX9-NEXT:    ; implicit-def: $vgpr10
; GFX9-NEXT:    ; implicit-def: $vgpr13
; GFX9-NEXT:    ; implicit-def: $vgpr14
; GFX9-NEXT:    ; implicit-def: $vgpr15
; GFX9-NEXT:    ; implicit-def: $vgpr17
; GFX9-NEXT:    ; implicit-def: $vgpr18
; GFX9-NEXT:    ; implicit-def: $vgpr21
; GFX9-NEXT:    ; implicit-def: $vgpr22
; GFX9-NEXT:    ; implicit-def: $vgpr23
; GFX9-NEXT:    ; implicit-def: $vgpr25
; GFX9-NEXT:    ; implicit-def: $vgpr26
; GFX9-NEXT:    ; implicit-def: $vgpr29
; GFX9-NEXT:    ; implicit-def: $vgpr30
; GFX9-NEXT:    ; implicit-def: $vgpr31
; GFX9-NEXT:    ; implicit-def: $vgpr3
; GFX9-NEXT:    ; implicit-def: $vgpr11
; GFX9-NEXT:    ; implicit-def: $vgpr19
; GFX9-NEXT:    ; implicit-def: $vgpr27
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB108_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 8, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 24, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 8, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v18, 16, v32
; GFX9-NEXT:    v_lshrrev_b32_e32 v17, 8, v32
; GFX9-NEXT:    v_lshrrev_b32_e32 v15, 24, v36
; GFX9-NEXT:    v_lshrrev_b32_e32 v14, 16, v36
; GFX9-NEXT:    v_lshrrev_b32_e32 v13, 8, v36
; GFX9-NEXT:    v_lshrrev_b32_e32 v10, 16, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v9, 8, v35
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 24, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 8, v0
; GFX9-NEXT:    v_lshrrev_b64 v[27:28], 24, v[6:7]
; GFX9-NEXT:    v_lshrrev_b64 v[19:20], 24, v[32:33]
; GFX9-NEXT:    v_lshrrev_b64 v[11:12], 24, v[35:36]
; GFX9-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; GFX9-NEXT:  .LBB108_2: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB108_4
; GFX9-NEXT:  ; %bb.3: ; %cmp.true
; GFX9-NEXT:    v_lshlrev_b32_e32 v2, 16, v1
; GFX9-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; GFX9-NEXT:    v_bfe_u32 v3, v2, 16, 1
; GFX9-NEXT:    s_movk_i32 s6, 0x7fff
; GFX9-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GFX9-NEXT:    v_add3_u32 v3, v3, v2, s6
; GFX9-NEXT:    v_or_b32_e32 v4, 0x400000, v2
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; GFX9-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX9-NEXT:    v_cndmask_b32_e32 v4, v3, v4, vcc
; GFX9-NEXT:    v_add3_u32 v2, v2, v1, s6
; GFX9-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    v_lshlrev_b32_e32 v1, 16, v0
; GFX9-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GFX9-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v3, v2, v3, vcc
; GFX9-NEXT:    v_bfe_u32 v2, v1, 16, 1
; GFX9-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; GFX9-NEXT:    v_add3_u32 v2, v2, v1, s6
; GFX9-NEXT:    v_or_b32_e32 v5, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    v_bfe_u32 v1, v0, 16, 1
; GFX9-NEXT:    v_cndmask_b32_e32 v5, v2, v5, vcc
; GFX9-NEXT:    v_add3_u32 v1, v1, v0, s6
; GFX9-NEXT:    v_or_b32_e32 v2, 0x400000, v0
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; GFX9-NEXT:    v_lshlrev_b32_e32 v0, 16, v36
; GFX9-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v2, v1, v2, vcc
; GFX9-NEXT:    v_bfe_u32 v1, v0, 16, 1
; GFX9-NEXT:    v_add3_u32 v1, v1, v0, s6
; GFX9-NEXT:    v_or_b32_e32 v8, 0x400000, v0
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v0, v1, v8, vcc
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff0000, v36
; GFX9-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GFX9-NEXT:    v_bfe_u32 v8, v1, 16, 1
; GFX9-NEXT:    v_add3_u32 v8, v8, v1, s6
; GFX9-NEXT:    v_or_b32_e32 v9, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    v_lshlrev_b32_e32 v1, 16, v35
; GFX9-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v10, v8, v9, vcc
; GFX9-NEXT:    v_bfe_u32 v8, v1, 16, 1
; GFX9-NEXT:    v_add3_u32 v8, v8, v1, s6
; GFX9-NEXT:    v_or_b32_e32 v9, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v8, v9, vcc
; GFX9-NEXT:    v_and_b32_e32 v8, 0xffff0000, v35
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v11, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v33
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_cndmask_b32_e32 v13, v9, v11, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v11, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_and_b32_e32 v8, 0xffff0000, v33
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_cndmask_b32_e32 v14, v9, v11, vcc
; GFX9-NEXT:    v_bfe_u32 v9, v8, 16, 1
; GFX9-NEXT:    v_add3_u32 v9, v9, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v11, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_lshlrev_b32_e32 v8, 16, v32
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_cndmask_b32_e32 v15, v9, v11, vcc
; GFX9-NEXT:    v_bfe_u32 v11, v8, 16, 1
; GFX9-NEXT:    v_add3_u32 v11, v11, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v12, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_and_b32_e32 v8, 0xffff0000, v32
; GFX9-NEXT:    v_add_f32_e32 v8, 0x40c00000, v8
; GFX9-NEXT:    v_cndmask_b32_e32 v16, v11, v12, vcc
; GFX9-NEXT:    v_bfe_u32 v11, v8, 16, 1
; GFX9-NEXT:    v_add3_u32 v11, v11, v8, s6
; GFX9-NEXT:    v_or_b32_e32 v12, 0x400000, v8
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v8, v8
; GFX9-NEXT:    v_cndmask_b32_e32 v17, v11, v12, vcc
; GFX9-NEXT:    v_lshlrev_b32_e32 v11, 16, v7
; GFX9-NEXT:    v_add_f32_e32 v11, 0x40c00000, v11
; GFX9-NEXT:    v_and_b32_e32 v7, 0xffff0000, v7
; GFX9-NEXT:    v_bfe_u32 v12, v11, 16, 1
; GFX9-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GFX9-NEXT:    v_add3_u32 v12, v12, v11, s6
; GFX9-NEXT:    v_or_b32_e32 v18, 0x400000, v11
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v11, v11
; GFX9-NEXT:    v_bfe_u32 v11, v7, 16, 1
; GFX9-NEXT:    v_cndmask_b32_e32 v18, v12, v18, vcc
; GFX9-NEXT:    v_add3_u32 v11, v11, v7, s6
; GFX9-NEXT:    v_or_b32_e32 v12, 0x400000, v7
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; GFX9-NEXT:    v_lshlrev_b32_e32 v7, 16, v6
; GFX9-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GFX9-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; GFX9-NEXT:    v_cndmask_b32_e32 v19, v11, v12, vcc
; GFX9-NEXT:    v_bfe_u32 v11, v7, 16, 1
; GFX9-NEXT:    v_add_f32_e32 v6, 0x40c00000, v6
; GFX9-NEXT:    v_add3_u32 v11, v11, v7, s6
; GFX9-NEXT:    v_or_b32_e32 v12, 0x400000, v7
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; GFX9-NEXT:    v_bfe_u32 v7, v6, 16, 1
; GFX9-NEXT:    v_cndmask_b32_e32 v20, v11, v12, vcc
; GFX9-NEXT:    v_add3_u32 v7, v7, v6, s6
; GFX9-NEXT:    v_or_b32_e32 v11, 0x400000, v6
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v6, v6
; GFX9-NEXT:    s_mov_b32 s7, 0x7060302
; GFX9-NEXT:    v_cndmask_b32_e32 v21, v7, v11, vcc
; GFX9-NEXT:    v_perm_b32 v9, v15, v14, s7
; GFX9-NEXT:    v_perm_b32 v8, v17, v16, s7
; GFX9-NEXT:    v_perm_b32 v12, v19, v18, s7
; GFX9-NEXT:    v_perm_b32 v11, v21, v20, s7
; GFX9-NEXT:    v_perm_b32 v38, v10, v0, s7
; GFX9-NEXT:    v_perm_b32 v37, v13, v1, s7
; GFX9-NEXT:    v_perm_b32 v49, v3, v4, s7
; GFX9-NEXT:    v_perm_b32 v48, v2, v5, s7
; GFX9-NEXT:    v_lshrrev_b32_e32 v6, 16, v20
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v19
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 24, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 8, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 8, v11
; GFX9-NEXT:    v_lshrrev_b64 v[27:28], 24, v[11:12]
; GFX9-NEXT:    v_lshrrev_b64 v[19:20], 24, v[8:9]
; GFX9-NEXT:    v_lshrrev_b64 v[11:12], 24, v[37:38]
; GFX9-NEXT:    v_lshrrev_b64 v[3:4], 24, v[48:49]
; GFX9-NEXT:    v_lshrrev_b32_e32 v7, 16, v18
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v14
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 16, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v5
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v21
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v15
; GFX9-NEXT:    v_lshrrev_b32_e32 v18, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v14, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v10, 16, v13
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 24, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 8, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v17, 8, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v15, 24, v38
; GFX9-NEXT:    v_lshrrev_b32_e32 v13, 8, v38
; GFX9-NEXT:    v_lshrrev_b32_e32 v9, 8, v37
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 24, v49
; GFX9-NEXT:    v_lshrrev_b32_e32 v5, 8, v49
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 8, v48
; GFX9-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; GFX9-NEXT:  .LBB108_4: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    v_mov_b32_e32 v4, v1
; GFX9-NEXT:    v_mov_b32_e32 v8, v35
; GFX9-NEXT:    v_mov_b32_e32 v12, v36
; GFX9-NEXT:    v_mov_b32_e32 v16, v32
; GFX9-NEXT:    v_mov_b32_e32 v20, v33
; GFX9-NEXT:    v_mov_b32_e32 v24, v6
; GFX9-NEXT:    v_mov_b32_e32 v28, v7
; GFX9-NEXT:    v_mov_b32_e32 v1, v38
; GFX9-NEXT:    v_mov_b32_e32 v6, v34
; GFX9-NEXT:    v_mov_b32_e32 v7, v37
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v16bf16_to_v32i8:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v8
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr11_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr19_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr26_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr48_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr10_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr18_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr14_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr8_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr32_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr38_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr12_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr15_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr16_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr17_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr34_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr37_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr21_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr23_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr24_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr25_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr50_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr36_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr28_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr29_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr31_lo16
; GFX11-TRUE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB108_2
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[36:37], 24, v[6:7]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[37:38], 24, v[4:5]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v7
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v7
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v6
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v5
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v5
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v4
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v3
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v3
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v2
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v14, 24, v1
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v18, 8, v1
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v19, 8, v0
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[38:39], 24, v[2:3]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[48:49], 24, v[0:1]
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v11.h, v0.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v26.h, v0.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v10.h, v1.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v27.h, v1.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v8.h, v2.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v32.h, v2.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v12.h, v3.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v33.h, v3.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v16.h, v4.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v34.h, v4.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v20.h, v5.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v35.h, v5.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v24.h, v6.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v50.h, v6.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v28.h, v7.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v51.h, v7.h
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr1
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr3
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr5
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr7
; GFX11-TRUE16-NEXT:  .LBB108_2: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB108_4
; GFX11-TRUE16-NEXT:  ; %bb.3: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v10, 0xffff0000, v3
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v8, 16, v1
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v9, 0xffff0000, v0
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v13, 0x40c00000, v10 :: v_dual_add_f32 v8, 0x40c00000, v8
; GFX11-TRUE16-NEXT:    v_bfe_u32 v11, v8, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v14, 0x400000, v8
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add3_u32 v11, v11, v8, 0x7fff
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v1, 0xffff0000, v1
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v1, 0x40c00000, v1 :: v_dual_lshlrev_b32 v0, 16, v0
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v9, 0x40c00000, v9 :: v_dual_add_f32 v0, 0x40c00000, v0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v10, v1, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v12, 0x400000, v1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v15, v9, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v16, 0x400000, v9
; GFX11-TRUE16-NEXT:    v_bfe_u32 v8, v0, 16, 1
; GFX11-TRUE16-NEXT:    v_add3_u32 v17, v10, v1, 0x7fff
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v10, v11, v14, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-TRUE16-NEXT:    v_add3_u32 v11, v15, v9, 0x7fff
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v27, v17, v12, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v1, 0x40c00000, v3
; GFX11-TRUE16-NEXT:    v_add3_u32 v3, v8, v0, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v12, v13, 16, 1
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v26, v11, v16, vcc_lo
; GFX11-TRUE16-NEXT:    v_bfe_u32 v9, v1, 16, 1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v14, 0xffff0000, v2
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v27.l, v10.h
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_add3_u32 v0, v9, v1, 0x7fff
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v11, v3, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v3, 0x400000, v1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-TRUE16-NEXT:    v_add3_u32 v8, v12, v13, 0x7fff
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v18, 8, v27
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v26.l, v11.h
; GFX11-TRUE16-NEXT:    v_dual_cndmask_b32 v12, v0, v3 :: v_dual_and_b32 v3, 0xffff0000, v5
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v0, 16, v2
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v9, 0x40c00000, v14
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v14, 0x400000, v13
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v13, v13
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v0, 0x40c00000, v0 :: v_dual_lshlrev_b32 v5, 16, v5
; GFX11-TRUE16-NEXT:    v_bfe_u32 v1, v9, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v2, 0x400000, v9
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v33, v8, v14, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-TRUE16-NEXT:    v_bfe_u32 v8, v0, 16, 1
; GFX11-TRUE16-NEXT:    v_add3_u32 v1, v1, v9, 0x7fff
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v33.l, v12.h
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[48:49], 24, v[26:27]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v19, 8, v26
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_dual_cndmask_b32 v32, v1, v2 :: v_dual_add_f32 v1, 0x40c00000, v3
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v2, 0x40c00000, v5
; GFX11-TRUE16-NEXT:    v_add3_u32 v3, v8, v0, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, 0x400000, v0
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v13, v1, 16, 1
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v9, 0xffff0000, v4
; GFX11-TRUE16-NEXT:    v_bfe_u32 v14, v2, 16, 1
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v33
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v8, v3, v5, vcc_lo
; GFX11-TRUE16-NEXT:    v_add3_u32 v3, v13, v1, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, 0x400000, v1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v13, 0x400000, v2
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v32.l, v8.h
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v35, v3, v5, vcc_lo
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v0, 0x40c00000, v9 :: v_dual_add_f32 v1, 0x40c00000, v4
; GFX11-TRUE16-NEXT:    v_add3_u32 v9, v14, v2, 0x7fff
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v4, 0xffff0000, v7
; GFX11-TRUE16-NEXT:    v_bfe_u32 v14, v0, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v3, 0x400000, v0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v5, v1, 16, 1
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v20, v9, v13, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-TRUE16-NEXT:    v_add3_u32 v2, v14, v0, 0x7fff
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v0, 0x40c00000, v4
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v4, 16, v6
; GFX11-TRUE16-NEXT:    v_and_b32_e32 v6, 0xffff0000, v6
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v34, v2, v3, vcc_lo
; GFX11-TRUE16-NEXT:    v_lshlrev_b32_e32 v2, 16, v7
; GFX11-TRUE16-NEXT:    v_add3_u32 v3, v5, v1, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, 0x400000, v1
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v4, 0x40c00000, v4
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GFX11-TRUE16-NEXT:    v_bfe_u32 v7, v0, 16, 1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v14, 0x400000, v4
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v16, v3, v5, vcc_lo
; GFX11-TRUE16-NEXT:    v_bfe_u32 v1, v2, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e32 v5, 0x40c00000, v6
; GFX11-TRUE16-NEXT:    v_bfe_u32 v6, v4, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v9, 0x400000, v2
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-TRUE16-NEXT:    v_add3_u32 v1, v1, v2, 0x7fff
; GFX11-TRUE16-NEXT:    v_add3_u32 v3, v7, v0, 0x7fff
; GFX11-TRUE16-NEXT:    v_add3_u32 v6, v6, v4, 0x7fff
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v7, 0x400000, v0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v13, v5, 16, 1
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v28, v1, v9, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v2, 0x400000, v5
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v35.l, v20.h
; GFX11-TRUE16-NEXT:    v_add3_u32 v1, v13, v5, 0x7fff
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v34.l, v16.h
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v24, v6, v14, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v35
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v35
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v34
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v33
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v51, v3, v7, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v51.l, v28.h
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v32
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v14, 24, v27
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v50, v1, v2, vcc_lo
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v50.l, v24.h
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v51
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v51
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[36:37], 24, v[50:51]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[37:38], 24, v[34:35]
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[38:39], 24, v[32:33]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v50
; GFX11-TRUE16-NEXT:  .LBB108_4: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.l, v11.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v1.l, v19.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.l, v26.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v3.l, v48.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v4.l, v10.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v5.l, v18.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v6.l, v27.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v7.l, v14.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v8.l, v8.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v10.l, v32.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v11.l, v38.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v12.l, v12.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v14.l, v33.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v16.l, v16.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v18.l, v34.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v19.l, v37.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v20.l, v20.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v22.l, v35.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v24.l, v24.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v26.l, v50.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v27.l, v36.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v28.l, v28.h
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v30.l, v51.h
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v16bf16_to_v32i8:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v33, v7 :: v_dual_mov_b32 v32, v6
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v35, v5 :: v_dual_mov_b32 v34, v4
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v37, v3 :: v_dual_mov_b32 v36, v2
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v39, v1 :: v_dual_mov_b32 v38, v0
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v8
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr1
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr2
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr3
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr5
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr6
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr7
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr9
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr10
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr11
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr13
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr14
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr15
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr17
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr18
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr19
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr21
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr22
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr23
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr25
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr26
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr27
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr29
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr30
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr31
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB108_2
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v33
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v32
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v32
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v35
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v18, 16, v34
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v34
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v14, 16, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v37
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v10, 16, v36
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v36
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v6, 16, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v38
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[27:28], 24, v[32:33]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[19:20], 24, v[34:35]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[11:12], 24, v[36:37]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[38:39]
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v38
; GFX11-FAKE16-NEXT:  .LBB108_2: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB108_4
; GFX11-FAKE16-NEXT:  ; %bb.3: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v1, 0xffff0000, v39
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v0, 16, v39
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xffff0000, v38
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v2, 16, v38
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v14, 0xffff0000, v36
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v1, 0x40c00000, v1 :: v_dual_add_f32 v0, 0x40c00000, v0
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v3, 0x40c00000, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v15, 16, v34
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_bfe_u32 v6, v1, 16, 1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v4, v0, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v5, 0x400000, v0
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v8, 0x400000, v1
; GFX11-FAKE16-NEXT:    v_add3_u32 v6, v6, v1, 0x7fff
; GFX11-FAKE16-NEXT:    v_add3_u32 v4, v4, v0, 0x7fff
; GFX11-FAKE16-NEXT:    v_bfe_u32 v9, v3, 16, 1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_2) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v4, v4, v5, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; GFX11-FAKE16-NEXT:    v_add3_u32 v1, v9, v3, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v9, 0x400000, v3
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v4
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v5, v6, v8, vcc_lo
; GFX11-FAKE16-NEXT:    v_bfe_u32 v7, v2, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, 0x400000, v2
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v8, 0xffff0000, v37
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_add3_u32 v7, v7, v2, 0x7fff
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v11, v7, v0 :: v_dual_lshlrev_b32 v6, 16, v37
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v2, 0x40c00000, v6 :: v_dual_lshlrev_b32 v7, 16, v36
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v6, 0x40c00000, v8
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v11
; GFX11-FAKE16-NEXT:    v_bfe_u32 v8, v2, 16, 1
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v7, 0x40c00000, v7
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v10, 0x400000, v2
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v3, v1, v9, vcc_lo
; GFX11-FAKE16-NEXT:    v_bfe_u32 v9, v6, 16, 1
; GFX11-FAKE16-NEXT:    v_add3_u32 v8, v8, v2, 0x7fff
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v2, v2
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, 0x400000, v6
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v7, 16, 1
; GFX11-FAKE16-NEXT:    v_add3_u32 v9, v9, v6, 0x7fff
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v5, v4, 0x7060302
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v2, v8, v10, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v6, v6
; GFX11-FAKE16-NEXT:    v_add3_u32 v10, v13, v7, 0x7fff
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v13, 16, v35
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v3, v11, 0x7060302
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v6, v9, v12, vcc_lo
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v12, 0x400000, v7
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v9, 0x40c00000, v14
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_2) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, v6, v2, 0x7060302
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v3
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v12, v10, v12, vcc_lo
; GFX11-FAKE16-NEXT:    v_bfe_u32 v14, v9, 16, 1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v10, 0xffff0000, v35
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v7, 0x40c00000, v13
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v12
; GFX11-FAKE16-NEXT:    v_add3_u32 v13, v14, v9, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v14, 0x400000, v9
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v10, 0x40c00000, v10
; GFX11-FAKE16-NEXT:    v_bfe_u32 v16, v7, 16, 1
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[0:1]
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v9, v13, v14, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v13, 0x40c00000, v15
; GFX11-FAKE16-NEXT:    v_add3_u32 v14, v16, v7, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v15, 0x400000, v7
; GFX11-FAKE16-NEXT:    v_bfe_u32 v16, v10, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v17, 0xffff0000, v34
; GFX11-FAKE16-NEXT:    v_bfe_u32 v18, v13, 16, 1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_add3_u32 v7, v16, v10, 0x7fff
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v14, v14, v15 :: v_dual_add_f32 v15, 0x40c00000, v17
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v16, 0x400000, v10
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v10, v10
; GFX11-FAKE16-NEXT:    v_add3_u32 v17, v18, v13, 0x7fff
; GFX11-FAKE16-NEXT:    v_lshlrev_b32_e32 v18, 16, v33
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v19, 0x400000, v13
; GFX11-FAKE16-NEXT:    v_bfe_u32 v20, v15, 16, 1
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v10, v7, v16, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v13, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v14
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_add3_u32 v16, v20, v15, 0x7fff
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v13, v17, v19 :: v_dual_lshlrev_b32 v20, 16, v32
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v17, 0x400000, v15
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v19, 0xffff0000, v33
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v7, 0x40c00000, v18
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v15, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v13
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v17, v16, v17 :: v_dual_add_f32 v16, 0x40c00000, v19
; GFX11-FAKE16-NEXT:    v_bfe_u32 v18, v7, 16, 1
; GFX11-FAKE16-NEXT:    v_add_f32_e32 v19, 0x40c00000, v20
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v20, 0x400000, v7
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-FAKE16-NEXT:    v_bfe_u32 v21, v16, 16, 1
; GFX11-FAKE16-NEXT:    v_add3_u32 v18, v18, v7, 0x7fff
; GFX11-FAKE16-NEXT:    v_bfe_u32 v22, v19, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v23, 0x400000, v19
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v18, v18, v20, vcc_lo
; GFX11-FAKE16-NEXT:    v_add3_u32 v20, v21, v16, 0x7fff
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v21, 0x400000, v16
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v16, v16
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v15, 0xffff0000, v32
; GFX11-FAKE16-NEXT:    v_add3_u32 v22, v22, v19, 0x7fff
; GFX11-FAKE16-NEXT:    v_perm_b32 v16, v10, v14, 0x7060302
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v18
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v20, v20, v21 :: v_dual_add_f32 v15, 0x40c00000, v15
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v19, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v14, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v6, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v20
; GFX11-FAKE16-NEXT:    v_bfe_u32 v7, v15, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v24, 0x400000, v15
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v19, v22, v23, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v15, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v10
; GFX11-FAKE16-NEXT:    v_add3_u32 v7, v7, v15, 0x7fff
; GFX11-FAKE16-NEXT:    v_perm_b32 v15, v17, v13, 0x7060302
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v10, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v8
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v21, v7, v24, vcc_lo
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v9, v12, 0x7060302
; GFX11-FAKE16-NEXT:    v_perm_b32 v24, v20, v18, 0x7060302
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v18, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v15
; GFX11-FAKE16-NEXT:    v_perm_b32 v23, v21, v19, 0x7060302
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[19:20], 24, v[15:16]
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[11:12], 24, v[7:8]
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v21
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v24
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[27:28], 24, v[23:24]
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v24
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v23
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v0
; GFX11-FAKE16-NEXT:  .LBB108_4: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v0, v38
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v4, v39
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v8, v36
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v12, v37
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v16, v34
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v20, v35
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v24, v32
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v28, v33
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x bfloat> %a, splat (bfloat 0xR40C0)
  %a2 = bitcast <16 x bfloat> %a1 to <32 x i8>
  br label %end

cmp.false:
  %a3 = bitcast <16 x bfloat> %a to <32 x i8>
  br label %end

end:
  %phi = phi <32 x i8> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x i8> %phi
}

define inreg <32 x i8> @bitcast_v16bf16_to_v32i8_scalar(<16 x bfloat> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v16bf16_to_v32i8_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:44 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:40 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v59, off, s[0:3], s32 ; 4-byte Folded Spill
; SI-NEXT:    s_and_b32 s4, s23, 0xffff0000
; SI-NEXT:    s_lshl_b32 s5, s23, 16
; SI-NEXT:    s_and_b32 s6, s22, 0xffff0000
; SI-NEXT:    s_lshl_b32 s7, s22, 16
; SI-NEXT:    s_and_b32 s8, s21, 0xffff0000
; SI-NEXT:    s_lshl_b32 s9, s21, 16
; SI-NEXT:    s_and_b32 s10, s20, 0xffff0000
; SI-NEXT:    s_lshl_b32 s11, s20, 16
; SI-NEXT:    s_and_b32 s12, s19, 0xffff0000
; SI-NEXT:    s_lshl_b32 s13, s19, 16
; SI-NEXT:    s_and_b32 s14, s18, 0xffff0000
; SI-NEXT:    s_lshl_b32 s15, s18, 16
; SI-NEXT:    s_and_b32 s18, s17, 0xffff0000
; SI-NEXT:    s_lshl_b32 s17, s17, 16
; SI-NEXT:    s_and_b32 s19, s16, 0xffff0000
; SI-NEXT:    s_lshl_b32 s16, s16, 16
; SI-NEXT:    s_cmp_lg_u32 s24, 0
; SI-NEXT:    s_waitcnt expcnt(6)
; SI-NEXT:    v_mul_f32_e64 v45, 1.0, s19
; SI-NEXT:    v_mul_f32_e64 v0, 1.0, s16
; SI-NEXT:    v_mul_f32_e64 v32, 1.0, s18
; SI-NEXT:    v_mul_f32_e64 v5, 1.0, s17
; SI-NEXT:    s_waitcnt expcnt(4)
; SI-NEXT:    v_mul_f32_e64 v47, 1.0, s14
; SI-NEXT:    v_mul_f32_e64 v8, 1.0, s15
; SI-NEXT:    v_mul_f32_e64 v46, 1.0, s12
; SI-NEXT:    v_mul_f32_e64 v13, 1.0, s13
; SI-NEXT:    s_waitcnt expcnt(2)
; SI-NEXT:    v_mul_f32_e64 v57, 1.0, s10
; SI-NEXT:    v_mul_f32_e64 v16, 1.0, s11
; SI-NEXT:    v_mul_f32_e64 v56, 1.0, s8
; SI-NEXT:    v_mul_f32_e64 v21, 1.0, s9
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_mul_f32_e64 v59, 1.0, s6
; SI-NEXT:    v_mul_f32_e64 v58, 1.0, s4
; SI-NEXT:    v_mul_f32_e64 v24, 1.0, s7
; SI-NEXT:    v_mul_f32_e64 v29, 1.0, s5
; SI-NEXT:    s_cbranch_scc0 .LBB109_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_lshrrev_b32_e32 v9, 16, v47
; SI-NEXT:    v_lshrrev_b32_e32 v17, 16, v57
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v45
; SI-NEXT:    v_lshr_b64 v[53:54], v[8:9], 16
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v46
; SI-NEXT:    v_lshr_b64 v[39:40], v[16:17], 16
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v56
; SI-NEXT:    v_lshrrev_b32_e32 v25, 16, v59
; SI-NEXT:    v_lshr_b64 v[50:51], v[0:1], 16
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v32
; SI-NEXT:    v_lshr_b64 v[54:55], v[13:14], 16
; SI-NEXT:    v_lshr_b64 v[40:41], v[21:22], 16
; SI-NEXT:    v_lshr_b64 v[42:43], v[24:25], 16
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v58
; SI-NEXT:    v_lshr_b64 v[51:52], v[5:6], 16
; SI-NEXT:    v_lshr_b64 v[43:44], v[29:30], 16
; SI-NEXT:    v_lshr_b64 v[36:37], v[53:54], 16
; SI-NEXT:    v_lshr_b64 v[9:10], v[53:54], 8
; SI-NEXT:    v_lshr_b64 v[19:20], v[39:40], 24
; SI-NEXT:    v_lshr_b64 v[34:35], v[39:40], 16
; SI-NEXT:    v_lshr_b64 v[3:4], v[50:51], 24
; SI-NEXT:    v_lshr_b64 v[48:49], v[50:51], 16
; SI-NEXT:    v_lshr_b64 v[1:2], v[50:51], 8
; SI-NEXT:    v_lshr_b64 v[11:12], v[53:54], 24
; SI-NEXT:    v_lshrrev_b32_e32 v7, 24, v32
; SI-NEXT:    v_lshrrev_b32_e32 v15, 24, v46
; SI-NEXT:    v_lshrrev_b32_e32 v10, 8, v51
; SI-NEXT:    v_lshrrev_b32_e32 v23, 24, v56
; SI-NEXT:    v_lshrrev_b32_e32 v20, 8, v54
; SI-NEXT:    v_lshrrev_b32_e32 v31, 24, v58
; SI-NEXT:    v_lshrrev_b32_e32 v33, 8, v40
; SI-NEXT:    v_lshrrev_b32_e32 v35, 8, v43
; SI-NEXT:    v_lshr_b64 v[17:18], v[39:40], 8
; SI-NEXT:    v_lshr_b64 v[27:28], v[42:43], 24
; SI-NEXT:    v_lshr_b64 v[37:38], v[42:43], 16
; SI-NEXT:    v_lshr_b64 v[25:26], v[42:43], 8
; SI-NEXT:    s_cbranch_execnz .LBB109_3
; SI-NEXT:  .LBB109_2: ; %cmp.true
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v59
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v24
; SI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_lshr_b64 v[42:43], v[1:2], 16
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v29
; SI-NEXT:    v_add_f32_e32 v29, 0x40c00000, v1
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v58
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v57
; SI-NEXT:    v_add_f32_e32 v24, 0x40c00000, v1
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v16
; SI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_lshr_b64 v[39:40], v[1:2], 16
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v21
; SI-NEXT:    v_add_f32_e32 v21, 0x40c00000, v1
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v56
; SI-NEXT:    v_and_b32_e32 v2, 0xffff0000, v47
; SI-NEXT:    v_add_f32_e32 v16, 0x40c00000, v1
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v8
; SI-NEXT:    v_add_f32_e32 v2, 0x40c00000, v2
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_lshr_b64 v[53:54], v[1:2], 16
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v13
; SI-NEXT:    v_add_f32_e32 v13, 0x40c00000, v1
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v46
; SI-NEXT:    v_add_f32_e32 v8, 0x40c00000, v1
; SI-NEXT:    v_and_b32_e32 v1, 0xffff0000, v45
; SI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v0
; SI-NEXT:    v_add_f32_e32 v1, 0x40c00000, v1
; SI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_lshr_b64 v[50:51], v[0:1], 16
; SI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v5
; SI-NEXT:    v_add_f32_e32 v5, 0x40c00000, v0
; SI-NEXT:    v_and_b32_e32 v0, 0xffff0000, v32
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v8
; SI-NEXT:    v_add_f32_e32 v0, 0x40c00000, v0
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v24
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v16
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v0
; SI-NEXT:    v_lshr_b64 v[54:55], v[13:14], 16
; SI-NEXT:    v_lshr_b64 v[43:44], v[29:30], 16
; SI-NEXT:    v_lshr_b64 v[40:41], v[21:22], 16
; SI-NEXT:    v_lshr_b64 v[51:52], v[5:6], 16
; SI-NEXT:    v_lshr_b64 v[36:37], v[53:54], 16
; SI-NEXT:    v_lshr_b64 v[3:4], v[50:51], 24
; SI-NEXT:    v_lshr_b64 v[48:49], v[50:51], 16
; SI-NEXT:    v_lshr_b64 v[1:2], v[50:51], 8
; SI-NEXT:    v_lshr_b64 v[11:12], v[53:54], 24
; SI-NEXT:    v_lshr_b64 v[9:10], v[53:54], 8
; SI-NEXT:    v_lshr_b64 v[19:20], v[39:40], 24
; SI-NEXT:    v_lshr_b64 v[34:35], v[39:40], 16
; SI-NEXT:    v_lshr_b64 v[17:18], v[39:40], 8
; SI-NEXT:    v_lshr_b64 v[27:28], v[42:43], 24
; SI-NEXT:    v_lshr_b64 v[37:38], v[42:43], 16
; SI-NEXT:    v_lshr_b64 v[25:26], v[42:43], 8
; SI-NEXT:    v_lshrrev_b32_e32 v10, 8, v51
; SI-NEXT:    v_lshrrev_b32_e32 v20, 8, v54
; SI-NEXT:    v_lshrrev_b32_e32 v33, 8, v40
; SI-NEXT:    v_lshrrev_b32_e32 v35, 8, v43
; SI-NEXT:    v_lshrrev_b32_e32 v7, 24, v0
; SI-NEXT:    v_lshrrev_b32_e32 v15, 24, v8
; SI-NEXT:    v_lshrrev_b32_e32 v23, 24, v16
; SI-NEXT:    v_lshrrev_b32_e32 v31, 24, v24
; SI-NEXT:  .LBB109_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v13, v20
; SI-NEXT:    v_mov_b32_e32 v20, v40
; SI-NEXT:    v_mov_b32_e32 v24, v42
; SI-NEXT:    v_mov_b32_e32 v28, v43
; SI-NEXT:    buffer_load_dword v59, off, s[0:3], s32 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v57, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:40 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:44 ; 4-byte Folded Reload
; SI-NEXT:    v_mov_b32_e32 v0, v50
; SI-NEXT:    v_mov_b32_e32 v2, v48
; SI-NEXT:    v_mov_b32_e32 v4, v51
; SI-NEXT:    v_mov_b32_e32 v5, v10
; SI-NEXT:    v_mov_b32_e32 v8, v53
; SI-NEXT:    v_mov_b32_e32 v10, v36
; SI-NEXT:    v_mov_b32_e32 v12, v54
; SI-NEXT:    v_mov_b32_e32 v16, v39
; SI-NEXT:    v_mov_b32_e32 v18, v34
; SI-NEXT:    v_mov_b32_e32 v21, v33
; SI-NEXT:    v_mov_b32_e32 v26, v37
; SI-NEXT:    v_mov_b32_e32 v29, v35
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB109_4:
; SI-NEXT:    ; implicit-def: $vgpr1
; SI-NEXT:    ; implicit-def: $vgpr48
; SI-NEXT:    ; implicit-def: $vgpr3
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr7
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr31
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr25
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr27
; SI-NEXT:    ; implicit-def: $vgpr50
; SI-NEXT:    ; implicit-def: $vgpr53
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:    ; implicit-def: $vgpr42
; SI-NEXT:    s_branch .LBB109_2
;
; VI-LABEL: bitcast_v16bf16_to_v32i8_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_cmp_lg_u32 s24, 0
; VI-NEXT:    s_cbranch_scc0 .LBB109_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_lshr_b32 s57, s23, 24
; VI-NEXT:    s_lshr_b32 s56, s23, 16
; VI-NEXT:    s_lshr_b32 s47, s23, 8
; VI-NEXT:    s_lshr_b32 s59, s22, 16
; VI-NEXT:    s_lshr_b32 s58, s22, 8
; VI-NEXT:    s_lshr_b32 s44, s21, 24
; VI-NEXT:    s_lshr_b32 s43, s21, 16
; VI-NEXT:    s_lshr_b32 s42, s21, 8
; VI-NEXT:    s_lshr_b32 s46, s20, 16
; VI-NEXT:    s_lshr_b32 s45, s20, 8
; VI-NEXT:    s_lshr_b32 s29, s19, 24
; VI-NEXT:    s_lshr_b32 s28, s19, 16
; VI-NEXT:    s_lshr_b32 s27, s19, 8
; VI-NEXT:    s_lshr_b32 s41, s18, 16
; VI-NEXT:    s_lshr_b32 s40, s18, 8
; VI-NEXT:    s_lshr_b32 s24, s17, 24
; VI-NEXT:    s_lshr_b32 s15, s17, 16
; VI-NEXT:    s_lshr_b32 s14, s17, 8
; VI-NEXT:    s_lshr_b32 s26, s16, 16
; VI-NEXT:    s_lshr_b32 s25, s16, 8
; VI-NEXT:    s_lshr_b64 s[10:11], s[22:23], 24
; VI-NEXT:    s_lshr_b64 s[8:9], s[20:21], 24
; VI-NEXT:    s_lshr_b64 s[6:7], s[18:19], 24
; VI-NEXT:    s_lshr_b64 s[4:5], s[16:17], 24
; VI-NEXT:    s_cbranch_execnz .LBB109_4
; VI-NEXT:  .LBB109_2: ; %cmp.true
; VI-NEXT:    s_lshl_b32 s4, s17, 16
; VI-NEXT:    v_mov_b32_e32 v2, 0x40c00000
; VI-NEXT:    v_add_f32_e32 v0, s4, v2
; VI-NEXT:    v_bfe_u32 v1, v0, 16, 1
; VI-NEXT:    v_add_u32_e32 v1, vcc, v1, v0
; VI-NEXT:    v_add_u32_e32 v1, vcc, 0x7fff, v1
; VI-NEXT:    v_or_b32_e32 v3, 0x400000, v0
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; VI-NEXT:    s_and_b32 s4, s17, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v0, v1, v3, vcc
; VI-NEXT:    v_add_f32_e32 v1, s4, v2
; VI-NEXT:    v_bfe_u32 v3, v1, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v1
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_or_b32_e32 v4, 0x400000, v1
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; VI-NEXT:    v_cndmask_b32_e32 v1, v3, v4, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; VI-NEXT:    s_lshl_b32 s4, s16, 16
; VI-NEXT:    v_lshrrev_b64 v[4:5], 16, v[0:1]
; VI-NEXT:    v_add_f32_e32 v0, s4, v2
; VI-NEXT:    v_bfe_u32 v1, v0, 16, 1
; VI-NEXT:    v_add_u32_e32 v1, vcc, v1, v0
; VI-NEXT:    v_add_u32_e32 v1, vcc, 0x7fff, v1
; VI-NEXT:    v_or_b32_e32 v3, 0x400000, v0
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; VI-NEXT:    s_and_b32 s4, s16, 0xffff0000
; VI-NEXT:    v_cndmask_b32_e32 v0, v1, v3, vcc
; VI-NEXT:    v_add_f32_e32 v1, s4, v2
; VI-NEXT:    v_bfe_u32 v3, v1, 16, 1
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v1
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_or_b32_e32 v5, 0x400000, v1
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; VI-NEXT:    s_lshl_b32 s4, s19, 16
; VI-NEXT:    v_cndmask_b32_e32 v1, v3, v5, vcc
; VI-NEXT:    v_add_f32_e32 v3, s4, v2
; VI-NEXT:    v_bfe_u32 v5, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v3
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    s_and_b32 s4, s19, 0xffff0000
; VI-NEXT:    v_or_b32_e32 v6, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_add_f32_e32 v3, s4, v2
; VI-NEXT:    v_cndmask_b32_e32 v5, v5, v6, vcc
; VI-NEXT:    v_bfe_u32 v6, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v6, vcc, v6, v3
; VI-NEXT:    v_add_u32_e32 v6, vcc, 0x7fff, v6
; VI-NEXT:    v_or_b32_e32 v7, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v6, v7, vcc
; VI-NEXT:    s_lshl_b32 s4, s18, 16
; VI-NEXT:    v_lshrrev_b32_e32 v6, 16, v3
; VI-NEXT:    v_add_f32_e32 v3, s4, v2
; VI-NEXT:    v_lshrrev_b64 v[12:13], 16, v[5:6]
; VI-NEXT:    v_bfe_u32 v5, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v3
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    s_and_b32 s4, s18, 0xffff0000
; VI-NEXT:    v_or_b32_e32 v6, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_add_f32_e32 v3, s4, v2
; VI-NEXT:    v_cndmask_b32_e32 v5, v5, v6, vcc
; VI-NEXT:    v_bfe_u32 v6, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v6, vcc, v6, v3
; VI-NEXT:    v_add_u32_e32 v6, vcc, 0x7fff, v6
; VI-NEXT:    v_or_b32_e32 v7, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v6, v7, vcc
; VI-NEXT:    s_lshl_b32 s4, s21, 16
; VI-NEXT:    v_lshrrev_b32_e32 v6, 16, v3
; VI-NEXT:    v_add_f32_e32 v3, s4, v2
; VI-NEXT:    v_lshrrev_b64 v[8:9], 16, v[5:6]
; VI-NEXT:    v_bfe_u32 v5, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v3
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    s_and_b32 s4, s21, 0xffff0000
; VI-NEXT:    v_or_b32_e32 v6, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_add_f32_e32 v3, s4, v2
; VI-NEXT:    v_cndmask_b32_e32 v5, v5, v6, vcc
; VI-NEXT:    v_bfe_u32 v6, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v6, vcc, v6, v3
; VI-NEXT:    v_add_u32_e32 v6, vcc, 0x7fff, v6
; VI-NEXT:    v_or_b32_e32 v7, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v6, v7, vcc
; VI-NEXT:    s_lshl_b32 s4, s20, 16
; VI-NEXT:    v_lshrrev_b32_e32 v6, 16, v3
; VI-NEXT:    v_add_f32_e32 v3, s4, v2
; VI-NEXT:    v_lshrrev_b64 v[20:21], 16, v[5:6]
; VI-NEXT:    v_bfe_u32 v5, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v3
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    s_and_b32 s4, s20, 0xffff0000
; VI-NEXT:    v_or_b32_e32 v6, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_add_f32_e32 v3, s4, v2
; VI-NEXT:    v_cndmask_b32_e32 v5, v5, v6, vcc
; VI-NEXT:    v_bfe_u32 v6, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v6, vcc, v6, v3
; VI-NEXT:    v_add_u32_e32 v6, vcc, 0x7fff, v6
; VI-NEXT:    v_or_b32_e32 v7, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v6, v7, vcc
; VI-NEXT:    s_lshl_b32 s4, s23, 16
; VI-NEXT:    v_lshrrev_b32_e32 v6, 16, v3
; VI-NEXT:    v_add_f32_e32 v3, s4, v2
; VI-NEXT:    v_lshrrev_b64 v[16:17], 16, v[5:6]
; VI-NEXT:    v_bfe_u32 v5, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v3
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    s_and_b32 s4, s23, 0xffff0000
; VI-NEXT:    v_or_b32_e32 v6, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_add_f32_e32 v3, s4, v2
; VI-NEXT:    v_cndmask_b32_e32 v5, v5, v6, vcc
; VI-NEXT:    v_bfe_u32 v6, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v6, vcc, v6, v3
; VI-NEXT:    v_add_u32_e32 v6, vcc, 0x7fff, v6
; VI-NEXT:    v_or_b32_e32 v7, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_cndmask_b32_e32 v3, v6, v7, vcc
; VI-NEXT:    s_lshl_b32 s4, s22, 16
; VI-NEXT:    v_lshrrev_b32_e32 v6, 16, v3
; VI-NEXT:    v_add_f32_e32 v3, s4, v2
; VI-NEXT:    v_lshrrev_b64 v[28:29], 16, v[5:6]
; VI-NEXT:    v_bfe_u32 v5, v3, 16, 1
; VI-NEXT:    v_add_u32_e32 v5, vcc, v5, v3
; VI-NEXT:    s_and_b32 s4, s22, 0xffff0000
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x7fff, v5
; VI-NEXT:    v_add_f32_e32 v2, s4, v2
; VI-NEXT:    v_or_b32_e32 v6, 0x400000, v3
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v3, v3
; VI-NEXT:    v_bfe_u32 v3, v2, 16, 1
; VI-NEXT:    v_cndmask_b32_e32 v5, v5, v6, vcc
; VI-NEXT:    v_add_u32_e32 v3, vcc, v3, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x7fff, v3
; VI-NEXT:    v_or_b32_e32 v6, 0x400000, v2
; VI-NEXT:    v_cmp_u_f32_e32 vcc, v2, v2
; VI-NEXT:    v_cndmask_b32_e32 v2, v3, v6, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v6, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_lshrrev_b64 v[24:25], 16, v[5:6]
; VI-NEXT:    v_lshrrev_b64 v[0:1], 16, v[0:1]
; VI-NEXT:    v_mov_b32_e32 v25, v28
; VI-NEXT:    v_mov_b32_e32 v1, v4
; VI-NEXT:    v_mov_b32_e32 v9, v12
; VI-NEXT:    v_mov_b32_e32 v17, v20
; VI-NEXT:    v_lshrrev_b64 v[36:37], 24, v[24:25]
; VI-NEXT:    v_lshrrev_b64 v[37:38], 24, v[16:17]
; VI-NEXT:    v_lshrrev_b64 v[34:35], 24, v[8:9]
; VI-NEXT:    v_lshrrev_b64 v[32:33], 24, v[0:1]
; VI-NEXT:    v_lshrrev_b32_e32 v31, 24, v28
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v28
; VI-NEXT:    v_lshrrev_b32_e32 v29, 8, v28
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v24
; VI-NEXT:    v_lshrrev_b32_e32 v25, 8, v24
; VI-NEXT:    v_lshrrev_b32_e32 v23, 24, v20
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v20
; VI-NEXT:    v_lshrrev_b32_e32 v21, 8, v20
; VI-NEXT:    v_lshrrev_b32_e32 v18, 16, v16
; VI-NEXT:    v_lshrrev_b32_e32 v17, 8, v16
; VI-NEXT:    v_lshrrev_b32_e32 v15, 24, v12
; VI-NEXT:    v_lshrrev_b32_e32 v14, 16, v12
; VI-NEXT:    v_lshrrev_b32_e32 v13, 8, v12
; VI-NEXT:    v_lshrrev_b32_e32 v10, 16, v8
; VI-NEXT:    v_lshrrev_b32_e32 v9, 8, v8
; VI-NEXT:    v_lshrrev_b32_e32 v7, 24, v4
; VI-NEXT:    v_lshrrev_b32_e32 v6, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v5, 8, v4
; VI-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; VI-NEXT:    v_lshrrev_b32_e32 v1, 8, v0
; VI-NEXT:    s_branch .LBB109_5
; VI-NEXT:  .LBB109_3:
; VI-NEXT:    ; implicit-def: $sgpr25
; VI-NEXT:    ; implicit-def: $sgpr26
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr14
; VI-NEXT:    ; implicit-def: $sgpr15
; VI-NEXT:    ; implicit-def: $sgpr24
; VI-NEXT:    ; implicit-def: $sgpr40
; VI-NEXT:    ; implicit-def: $sgpr41
; VI-NEXT:    ; implicit-def: $sgpr6
; VI-NEXT:    ; implicit-def: $sgpr27
; VI-NEXT:    ; implicit-def: $sgpr28
; VI-NEXT:    ; implicit-def: $sgpr29
; VI-NEXT:    ; implicit-def: $sgpr45
; VI-NEXT:    ; implicit-def: $sgpr46
; VI-NEXT:    ; implicit-def: $sgpr8
; VI-NEXT:    ; implicit-def: $sgpr42
; VI-NEXT:    ; implicit-def: $sgpr43
; VI-NEXT:    ; implicit-def: $sgpr44
; VI-NEXT:    ; implicit-def: $sgpr58
; VI-NEXT:    ; implicit-def: $sgpr59
; VI-NEXT:    ; implicit-def: $sgpr10
; VI-NEXT:    ; implicit-def: $sgpr47
; VI-NEXT:    ; implicit-def: $sgpr56
; VI-NEXT:    ; implicit-def: $sgpr57
; VI-NEXT:    s_branch .LBB109_2
; VI-NEXT:  .LBB109_4:
; VI-NEXT:    v_mov_b32_e32 v26, s59
; VI-NEXT:    v_mov_b32_e32 v25, s58
; VI-NEXT:    v_mov_b32_e32 v31, s57
; VI-NEXT:    v_mov_b32_e32 v30, s56
; VI-NEXT:    v_mov_b32_e32 v29, s47
; VI-NEXT:    v_mov_b32_e32 v18, s46
; VI-NEXT:    v_mov_b32_e32 v17, s45
; VI-NEXT:    v_mov_b32_e32 v23, s44
; VI-NEXT:    v_mov_b32_e32 v22, s43
; VI-NEXT:    v_mov_b32_e32 v21, s42
; VI-NEXT:    v_mov_b32_e32 v10, s41
; VI-NEXT:    v_mov_b32_e32 v9, s40
; VI-NEXT:    v_mov_b32_e32 v15, s29
; VI-NEXT:    v_mov_b32_e32 v14, s28
; VI-NEXT:    v_mov_b32_e32 v13, s27
; VI-NEXT:    v_mov_b32_e32 v2, s26
; VI-NEXT:    v_mov_b32_e32 v1, s25
; VI-NEXT:    v_mov_b32_e32 v7, s24
; VI-NEXT:    v_mov_b32_e32 v6, s15
; VI-NEXT:    v_mov_b32_e32 v5, s14
; VI-NEXT:    v_mov_b32_e32 v24, s22
; VI-NEXT:    v_mov_b32_e32 v28, s23
; VI-NEXT:    v_mov_b32_e32 v16, s20
; VI-NEXT:    v_mov_b32_e32 v20, s21
; VI-NEXT:    v_mov_b32_e32 v8, s18
; VI-NEXT:    v_mov_b32_e32 v12, s19
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v4, s17
; VI-NEXT:    v_mov_b32_e32 v36, s10
; VI-NEXT:    v_mov_b32_e32 v37, s8
; VI-NEXT:    v_mov_b32_e32 v34, s6
; VI-NEXT:    v_mov_b32_e32 v32, s4
; VI-NEXT:  .LBB109_5: ; %end
; VI-NEXT:    v_mov_b32_e32 v3, v32
; VI-NEXT:    v_mov_b32_e32 v11, v34
; VI-NEXT:    v_mov_b32_e32 v19, v37
; VI-NEXT:    v_mov_b32_e32 v27, v36
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v16bf16_to_v32i8_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_cmp_lg_u32 s24, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB109_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_lshr_b32 s29, s23, 24
; GFX9-NEXT:    s_lshr_b32 s58, s23, 16
; GFX9-NEXT:    s_lshr_b32 s41, s23, 8
; GFX9-NEXT:    s_lshr_b32 s59, s22, 16
; GFX9-NEXT:    s_lshr_b32 s43, s22, 8
; GFX9-NEXT:    s_lshr_b32 s26, s21, 24
; GFX9-NEXT:    s_lshr_b32 s56, s21, 16
; GFX9-NEXT:    s_lshr_b32 s28, s21, 8
; GFX9-NEXT:    s_lshr_b32 s57, s20, 16
; GFX9-NEXT:    s_lshr_b32 s42, s20, 8
; GFX9-NEXT:    s_lshr_b32 s24, s19, 24
; GFX9-NEXT:    s_lshr_b32 s46, s19, 16
; GFX9-NEXT:    s_lshr_b32 s25, s19, 8
; GFX9-NEXT:    s_lshr_b32 s47, s18, 16
; GFX9-NEXT:    s_lshr_b32 s40, s18, 8
; GFX9-NEXT:    s_lshr_b32 s14, s17, 24
; GFX9-NEXT:    s_lshr_b32 s44, s17, 16
; GFX9-NEXT:    s_lshr_b32 s15, s17, 8
; GFX9-NEXT:    s_lshr_b32 s45, s16, 16
; GFX9-NEXT:    s_lshr_b32 s27, s16, 8
; GFX9-NEXT:    s_lshr_b64 s[10:11], s[22:23], 24
; GFX9-NEXT:    s_lshr_b64 s[8:9], s[20:21], 24
; GFX9-NEXT:    s_lshr_b64 s[6:7], s[18:19], 24
; GFX9-NEXT:    s_lshr_b64 s[4:5], s[16:17], 24
; GFX9-NEXT:    s_cbranch_execnz .LBB109_4
; GFX9-NEXT:  .LBB109_2: ; %cmp.true
; GFX9-NEXT:    s_and_b32 s4, s17, 0xffff0000
; GFX9-NEXT:    v_mov_b32_e32 v1, 0x40c00000
; GFX9-NEXT:    v_add_f32_e32 v0, s4, v1
; GFX9-NEXT:    v_bfe_u32 v2, v0, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v0
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v3, 0x400000, v0
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v0, v2, v3, vcc
; GFX9-NEXT:    s_lshl_b32 s4, s17, 16
; GFX9-NEXT:    v_lshrrev_b32_e32 v6, 16, v0
; GFX9-NEXT:    v_add_f32_e32 v0, s4, v1
; GFX9-NEXT:    v_bfe_u32 v2, v0, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v0
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v3, 0x400000, v0
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v0, v2, v3, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v0
; GFX9-NEXT:    v_and_b32_e32 v0, 0xffff, v35
; GFX9-NEXT:    s_and_b32 s4, s16, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v4, v6, 16, v0
; GFX9-NEXT:    v_add_f32_e32 v0, s4, v1
; GFX9-NEXT:    v_bfe_u32 v2, v0, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v2, v2, v0
; GFX9-NEXT:    v_add_u32_e32 v2, 0x7fff, v2
; GFX9-NEXT:    v_or_b32_e32 v3, 0x400000, v0
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; GFX9-NEXT:    v_cndmask_b32_e32 v0, v2, v3, vcc
; GFX9-NEXT:    s_lshl_b32 s4, s16, 16
; GFX9-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; GFX9-NEXT:    v_add_f32_e32 v0, s4, v1
; GFX9-NEXT:    v_bfe_u32 v3, v0, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v3, v3, v0
; GFX9-NEXT:    v_add_u32_e32 v3, 0x7fff, v3
; GFX9-NEXT:    v_or_b32_e32 v5, 0x400000, v0
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v0, v0
; GFX9-NEXT:    s_and_b32 s4, s19, 0xffff0000
; GFX9-NEXT:    v_cndmask_b32_e32 v0, v3, v5, vcc
; GFX9-NEXT:    v_add_f32_e32 v5, s4, v1
; GFX9-NEXT:    v_bfe_u32 v7, v5, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v7, v7, v5
; GFX9-NEXT:    v_add_u32_e32 v7, 0x7fff, v7
; GFX9-NEXT:    v_or_b32_e32 v8, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v5, v7, v8, vcc
; GFX9-NEXT:    s_lshl_b32 s4, s19, 16
; GFX9-NEXT:    v_lshrrev_b32_e32 v14, 16, v5
; GFX9-NEXT:    v_add_f32_e32 v5, s4, v1
; GFX9-NEXT:    v_bfe_u32 v7, v5, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v7, v7, v5
; GFX9-NEXT:    v_add_u32_e32 v7, 0x7fff, v7
; GFX9-NEXT:    v_or_b32_e32 v8, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v5, v7, v8, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff, v34
; GFX9-NEXT:    s_and_b32 s4, s18, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v12, v14, 16, v5
; GFX9-NEXT:    v_add_f32_e32 v5, s4, v1
; GFX9-NEXT:    v_bfe_u32 v7, v5, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v7, v7, v5
; GFX9-NEXT:    v_add_u32_e32 v7, 0x7fff, v7
; GFX9-NEXT:    v_or_b32_e32 v8, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v5, v7, v8, vcc
; GFX9-NEXT:    s_lshl_b32 s4, s18, 16
; GFX9-NEXT:    v_lshrrev_b32_e32 v10, 16, v5
; GFX9-NEXT:    v_add_f32_e32 v5, s4, v1
; GFX9-NEXT:    v_bfe_u32 v7, v5, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v7, v7, v5
; GFX9-NEXT:    v_add_u32_e32 v7, 0x7fff, v7
; GFX9-NEXT:    v_or_b32_e32 v8, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v5, v7, v8, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v8, 16, v5
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff, v8
; GFX9-NEXT:    s_and_b32 s4, s21, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v11, v10, 16, v5
; GFX9-NEXT:    v_add_f32_e32 v5, s4, v1
; GFX9-NEXT:    v_bfe_u32 v7, v5, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v7, v7, v5
; GFX9-NEXT:    v_add_u32_e32 v7, 0x7fff, v7
; GFX9-NEXT:    v_or_b32_e32 v9, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v5, v7, v9, vcc
; GFX9-NEXT:    s_lshl_b32 s4, s21, 16
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v5
; GFX9-NEXT:    v_add_f32_e32 v5, s4, v1
; GFX9-NEXT:    v_bfe_u32 v7, v5, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v7, v7, v5
; GFX9-NEXT:    v_add_u32_e32 v7, 0x7fff, v7
; GFX9-NEXT:    v_or_b32_e32 v9, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v5, v7, v9, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v5
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff, v33
; GFX9-NEXT:    s_and_b32 s4, s20, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v20, v22, 16, v5
; GFX9-NEXT:    v_add_f32_e32 v5, s4, v1
; GFX9-NEXT:    v_bfe_u32 v7, v5, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v7, v7, v5
; GFX9-NEXT:    v_add_u32_e32 v7, 0x7fff, v7
; GFX9-NEXT:    v_or_b32_e32 v9, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v5, v7, v9, vcc
; GFX9-NEXT:    s_lshl_b32 s4, s20, 16
; GFX9-NEXT:    v_lshrrev_b32_e32 v18, 16, v5
; GFX9-NEXT:    v_add_f32_e32 v5, s4, v1
; GFX9-NEXT:    v_bfe_u32 v7, v5, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v7, v7, v5
; GFX9-NEXT:    v_add_u32_e32 v7, 0x7fff, v7
; GFX9-NEXT:    v_or_b32_e32 v9, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    v_cndmask_b32_e32 v5, v7, v9, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v16, 16, v5
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff, v16
; GFX9-NEXT:    s_and_b32 s4, s23, 0xffff0000
; GFX9-NEXT:    v_lshl_or_b32 v19, v18, 16, v5
; GFX9-NEXT:    v_add_f32_e32 v5, s4, v1
; GFX9-NEXT:    v_bfe_u32 v7, v5, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v7, v7, v5
; GFX9-NEXT:    v_add_u32_e32 v7, 0x7fff, v7
; GFX9-NEXT:    v_or_b32_e32 v9, 0x400000, v5
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v5, v5
; GFX9-NEXT:    s_lshl_b32 s4, s23, 16
; GFX9-NEXT:    v_cndmask_b32_e32 v5, v7, v9, vcc
; GFX9-NEXT:    v_add_f32_e32 v7, s4, v1
; GFX9-NEXT:    v_bfe_u32 v9, v7, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v9, v9, v7
; GFX9-NEXT:    v_add_u32_e32 v9, 0x7fff, v9
; GFX9-NEXT:    v_or_b32_e32 v13, 0x400000, v7
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v7, v7
; GFX9-NEXT:    s_and_b32 s4, s22, 0xffff0000
; GFX9-NEXT:    v_cndmask_b32_e32 v7, v9, v13, vcc
; GFX9-NEXT:    v_add_f32_e32 v9, s4, v1
; GFX9-NEXT:    v_bfe_u32 v13, v9, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v13, v13, v9
; GFX9-NEXT:    s_lshl_b32 s4, s22, 16
; GFX9-NEXT:    v_add_u32_e32 v13, 0x7fff, v13
; GFX9-NEXT:    v_or_b32_e32 v15, 0x400000, v9
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v9, v9
; GFX9-NEXT:    v_add_f32_e32 v1, s4, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v9, v13, v15, vcc
; GFX9-NEXT:    v_bfe_u32 v13, v1, 16, 1
; GFX9-NEXT:    v_add_u32_e32 v13, v13, v1
; GFX9-NEXT:    v_add_u32_e32 v13, 0x7fff, v13
; GFX9-NEXT:    v_or_b32_e32 v15, 0x400000, v1
; GFX9-NEXT:    v_cmp_u_f32_e32 vcc, v1, v1
; GFX9-NEXT:    v_cndmask_b32_e32 v1, v13, v15, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v5
; GFX9-NEXT:    v_lshrrev_b32_e32 v24, 16, v1
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff, v32
; GFX9-NEXT:    v_and_b32_e32 v3, 0xffff, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v9
; GFX9-NEXT:    v_lshl_or_b32 v28, v30, 16, v1
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff, v24
; GFX9-NEXT:    v_lshl_or_b32 v3, v2, 16, v3
; GFX9-NEXT:    v_lshl_or_b32 v27, v26, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 24, v28
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 8, v28
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 8, v27
; GFX9-NEXT:    v_lshrrev_b64 v[27:28], 24, v[27:28]
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 24, v20
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 8, v20
; GFX9-NEXT:    v_lshrrev_b32_e32 v17, 8, v19
; GFX9-NEXT:    v_lshrrev_b64 v[19:20], 24, v[19:20]
; GFX9-NEXT:    v_lshrrev_b32_e32 v15, 24, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v13, 8, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v9, 8, v11
; GFX9-NEXT:    v_lshrrev_b64 v[11:12], 24, v[11:12]
; GFX9-NEXT:    v_lshrrev_b32_e32 v7, 24, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v5, 8, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v1, 8, v3
; GFX9-NEXT:    v_lshrrev_b64 v[3:4], 24, v[3:4]
; GFX9-NEXT:    s_branch .LBB109_5
; GFX9-NEXT:  .LBB109_3:
; GFX9-NEXT:    ; implicit-def: $sgpr27
; GFX9-NEXT:    ; implicit-def: $sgpr45
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr15
; GFX9-NEXT:    ; implicit-def: $sgpr44
; GFX9-NEXT:    ; implicit-def: $sgpr14
; GFX9-NEXT:    ; implicit-def: $sgpr40
; GFX9-NEXT:    ; implicit-def: $sgpr47
; GFX9-NEXT:    ; implicit-def: $sgpr6
; GFX9-NEXT:    ; implicit-def: $sgpr25
; GFX9-NEXT:    ; implicit-def: $sgpr46
; GFX9-NEXT:    ; implicit-def: $sgpr24
; GFX9-NEXT:    ; implicit-def: $sgpr42
; GFX9-NEXT:    ; implicit-def: $sgpr57
; GFX9-NEXT:    ; implicit-def: $sgpr8
; GFX9-NEXT:    ; implicit-def: $sgpr28
; GFX9-NEXT:    ; implicit-def: $sgpr56
; GFX9-NEXT:    ; implicit-def: $sgpr26
; GFX9-NEXT:    ; implicit-def: $sgpr43
; GFX9-NEXT:    ; implicit-def: $sgpr59
; GFX9-NEXT:    ; implicit-def: $sgpr10
; GFX9-NEXT:    ; implicit-def: $sgpr41
; GFX9-NEXT:    ; implicit-def: $sgpr58
; GFX9-NEXT:    ; implicit-def: $sgpr29
; GFX9-NEXT:    s_branch .LBB109_2
; GFX9-NEXT:  .LBB109_4:
; GFX9-NEXT:    v_mov_b32_e32 v24, s22
; GFX9-NEXT:    v_mov_b32_e32 v26, s59
; GFX9-NEXT:    v_mov_b32_e32 v32, s23
; GFX9-NEXT:    v_mov_b32_e32 v30, s58
; GFX9-NEXT:    v_mov_b32_e32 v16, s20
; GFX9-NEXT:    v_mov_b32_e32 v18, s57
; GFX9-NEXT:    v_mov_b32_e32 v33, s21
; GFX9-NEXT:    v_mov_b32_e32 v22, s56
; GFX9-NEXT:    v_mov_b32_e32 v8, s18
; GFX9-NEXT:    v_mov_b32_e32 v10, s47
; GFX9-NEXT:    v_mov_b32_e32 v34, s19
; GFX9-NEXT:    v_mov_b32_e32 v14, s46
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v2, s45
; GFX9-NEXT:    v_mov_b32_e32 v35, s17
; GFX9-NEXT:    v_mov_b32_e32 v6, s44
; GFX9-NEXT:    v_mov_b32_e32 v25, s43
; GFX9-NEXT:    v_mov_b32_e32 v31, s29
; GFX9-NEXT:    v_mov_b32_e32 v29, s41
; GFX9-NEXT:    v_mov_b32_e32 v17, s42
; GFX9-NEXT:    v_mov_b32_e32 v23, s26
; GFX9-NEXT:    v_mov_b32_e32 v21, s28
; GFX9-NEXT:    v_mov_b32_e32 v9, s40
; GFX9-NEXT:    v_mov_b32_e32 v15, s24
; GFX9-NEXT:    v_mov_b32_e32 v13, s25
; GFX9-NEXT:    v_mov_b32_e32 v1, s27
; GFX9-NEXT:    v_mov_b32_e32 v7, s14
; GFX9-NEXT:    v_mov_b32_e32 v5, s15
; GFX9-NEXT:    v_mov_b32_e32 v27, s10
; GFX9-NEXT:    v_mov_b32_e32 v19, s8
; GFX9-NEXT:    v_mov_b32_e32 v11, s6
; GFX9-NEXT:    v_mov_b32_e32 v3, s4
; GFX9-NEXT:  .LBB109_5: ; %end
; GFX9-NEXT:    v_mov_b32_e32 v4, v35
; GFX9-NEXT:    v_mov_b32_e32 v12, v34
; GFX9-NEXT:    v_mov_b32_e32 v20, v33
; GFX9-NEXT:    v_mov_b32_e32 v28, v32
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v16bf16_to_v32i8_scalar:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-TRUE16-NEXT:    s_mov_b32 s12, 0
; GFX11-TRUE16-NEXT:    s_cbranch_scc0 .LBB109_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-TRUE16-NEXT:    s_lshr_b32 s24, s19, 24
; GFX11-TRUE16-NEXT:    s_lshr_b32 s45, s19, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s26, s19, 8
; GFX11-TRUE16-NEXT:    s_lshr_b32 s46, s18, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s28, s18, 8
; GFX11-TRUE16-NEXT:    s_lshr_b32 s21, s17, 24
; GFX11-TRUE16-NEXT:    s_lshr_b32 s43, s17, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s23, s17, 8
; GFX11-TRUE16-NEXT:    s_lshr_b32 s44, s16, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s27, s16, 8
; GFX11-TRUE16-NEXT:    s_lshr_b32 s15, s3, 24
; GFX11-TRUE16-NEXT:    s_lshr_b32 s41, s3, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s20, s3, 8
; GFX11-TRUE16-NEXT:    s_lshr_b32 s42, s2, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s25, s2, 8
; GFX11-TRUE16-NEXT:    s_lshr_b32 s13, s1, 24
; GFX11-TRUE16-NEXT:    s_lshr_b32 s29, s1, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s14, s1, 8
; GFX11-TRUE16-NEXT:    s_lshr_b32 s40, s0, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s22, s0, 8
; GFX11-TRUE16-NEXT:    s_lshr_b64 s[10:11], s[18:19], 24
; GFX11-TRUE16-NEXT:    s_lshr_b64 s[8:9], s[16:17], 24
; GFX11-TRUE16-NEXT:    s_lshr_b64 s[6:7], s[2:3], 24
; GFX11-TRUE16-NEXT:    s_lshr_b64 s[4:5], s[0:1], 24
; GFX11-TRUE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s12
; GFX11-TRUE16-NEXT:    s_cbranch_vccnz .LBB109_4
; GFX11-TRUE16-NEXT:  .LBB109_2: ; %cmp.true
; GFX11-TRUE16-NEXT:    s_lshl_b32 s4, s1, 16
; GFX11-TRUE16-NEXT:    s_and_b32 s1, s1, 0xffff0000
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v0, 0x40c00000, s4
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v1, 0x40c00000, s1
; GFX11-TRUE16-NEXT:    s_and_b32 s4, s0, 0xffff0000
; GFX11-TRUE16-NEXT:    s_and_b32 s1, s3, 0xffff0000
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v3, 0x40c00000, s4
; GFX11-TRUE16-NEXT:    v_bfe_u32 v2, v0, 16, 1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v4, v1, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v6, 0x400000, v1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v0
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-TRUE16-NEXT:    s_lshl_b32 s3, s3, 16
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v4, v4, v1
; GFX11-TRUE16-NEXT:    s_lshl_b32 s0, s0, 16
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v7, 0x40c00000, s3
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v5, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    v_bfe_u32 v9, v3, 16, 1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v4, 0x7fff, v4
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, v2, v0
; GFX11-TRUE16-NEXT:    s_and_b32 s0, s2, 0xffff0000
; GFX11-TRUE16-NEXT:    v_bfe_u32 v10, v5, 16, 1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v2
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v0, v2, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, v9, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v8, v10, v5
; GFX11-TRUE16-NEXT:    v_bfe_u32 v9, v7, 16, 1
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v0
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v4, v6, vcc_lo
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v0, 0x400000, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v2
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v4, 0x7fff, v8
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v6, 16, v1
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v1, 0x40c00000, s1
; GFX11-TRUE16-NEXT:    s_lshl_b32 s1, s18, 16
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v8, 0x400000, v5
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v12, 0x40c00000, s1
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v37.l, v35.l
; GFX11-TRUE16-NEXT:    v_bfe_u32 v3, v1, 16, 1
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v0, v2, v0, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-TRUE16-NEXT:    v_bfe_u32 v13, v12, 16, 1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v5, v9, v7
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, v3, v1
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v0
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v4, v4, v8, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v13, v13, v12
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v8, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v3
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v4
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v13, 0x7fff, v13
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v4, 0x7fff, v5
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, 0x400000, v7
; GFX11-TRUE16-NEXT:    s_lshl_b32 s0, s2, 16
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v9, 0x400000, v1
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v7, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    s_and_b32 s0, s17, 0xffff0000
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v4, v4, v5, vcc_lo
; GFX11-TRUE16-NEXT:    v_bfe_u32 v5, v8, 16, 1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v37.h, v6.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v36.l, v0.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v36.h, v2.l
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v3, v9, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, v5, v8
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v4
; GFX11-TRUE16-NEXT:    v_bfe_u32 v4, v7, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v5, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v14, 16, v1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, 0x7fff, v3
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v3, 0x400000, v8
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v4, v4, v7
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-TRUE16-NEXT:    v_bfe_u32 v8, v5, 16, 1
; GFX11-TRUE16-NEXT:    s_lshl_b32 s0, s17, 16
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v39.l, v34.l
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v9, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v1, v3, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v4
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v4, 0x400000, v7
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-TRUE16-NEXT:    s_and_b32 s0, s16, 0xffff0000
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v10, 16, v1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, v8, v5
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v7, 0x400000, v5
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v3, v3, v4, vcc_lo
; GFX11-TRUE16-NEXT:    v_bfe_u32 v4, v9, 16, 1
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, 0x7fff, v1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, 0x400000, v9
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v8, 16, v3
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v3, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_2) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_dual_cndmask_b32 v1, v1, v7 :: v_dual_add_nc_u32 v4, v4, v9
; GFX11-TRUE16-NEXT:    s_lshl_b32 s0, s16, 16
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-TRUE16-NEXT:    v_bfe_u32 v11, v3, 16, 1
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_3) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v4, 0x7fff, v4
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v1
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v1, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    s_and_b32 s0, s19, 0xffff0000
; GFX11-TRUE16-NEXT:    v_dual_cndmask_b32 v4, v4, v5 :: v_dual_add_nc_u32 v7, v11, v3
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_bfe_u32 v9, v1, 16, 1
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v39.h, v14.l
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v5, 0x7fff, v7
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v7, 0x400000, v3
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v4
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v4, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    s_lshl_b32 s0, s19, 16
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v38.l, v8.l
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v3, v5, v7, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v5, v9, v1
; GFX11-TRUE16-NEXT:    v_bfe_u32 v7, v4, 16, 1
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v9, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v18, 16, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v5
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v5, 0x400000, v1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v7, v7, v4
; GFX11-TRUE16-NEXT:    s_and_b32 s0, s18, 0xffff0000
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v15, 0x400000, v4
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v11, 0x40c00000, s0
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v1, v3, v5, vcc_lo
; GFX11-TRUE16-NEXT:    v_bfe_u32 v3, v9, 16, 1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v7, 0x7fff, v7
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-TRUE16-NEXT:    v_bfe_u32 v5, v11, 16, 1
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v16, 0x400000, v11
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, v3, v9
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v49.l, v33.l
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v4, v7, v15, vcc_lo
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v7, 0x400000, v9
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v5, v5, v11
; GFX11-TRUE16-NEXT:    v_or_b32_e32 v15, 0x400000, v12
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v4
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v49.h, v22.l
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v3, v3, v7, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v12, v12
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v5, 0x7fff, v5
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v51.h, v30.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v48.h, v18.l
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v3
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v7, v13, v15, vcc_lo
; GFX11-TRUE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v11, v11
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v38.h, v10.l
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[36:37]
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v51.l, v32.l
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v7
; GFX11-TRUE16-NEXT:    v_cndmask_b32_e32 v5, v5, v16, vcc_lo
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v16, 16, v1
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[11:12], 24, v[38:39]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v51
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v50.l, v24.l
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v5
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v48.l, v16.l
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v51
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v49
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v49
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v50.h, v26.l
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[19:20], 24, v[48:49]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v48
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v39
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v39
; GFX11-TRUE16-NEXT:    v_lshrrev_b64 v[27:28], 24, v[50:51]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v50
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v38
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v37
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v37
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v36
; GFX11-TRUE16-NEXT:    s_branch .LBB109_5
; GFX11-TRUE16-NEXT:  .LBB109_3:
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr22
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr40
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr4
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr14
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr29
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr13
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr25
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr42
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr6
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr41
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr15
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr27
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr44
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr8
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr23
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr43
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr21
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr28
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr46
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr10
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr26
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr45
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr24
; GFX11-TRUE16-NEXT:    s_branch .LBB109_2
; GFX11-TRUE16-NEXT:  .LBB109_4:
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v24, s18 :: v_dual_mov_b32 v33, s17
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v26, s46 :: v_dual_mov_b32 v35, s1
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v32, s19 :: v_dual_mov_b32 v25, s28
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v30, s45 :: v_dual_mov_b32 v31, s24
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v16, s16 :: v_dual_mov_b32 v29, s26
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v18, s44 :: v_dual_mov_b32 v17, s27
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v22, s43 :: v_dual_mov_b32 v23, s21
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v8, s2 :: v_dual_mov_b32 v21, s23
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v10, s42 :: v_dual_mov_b32 v9, s25
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v34, s3 :: v_dual_mov_b32 v15, s15
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v14, s41 :: v_dual_mov_b32 v13, s20
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s22
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v2, s40 :: v_dual_mov_b32 v7, s13
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v6, s29 :: v_dual_mov_b32 v5, s14
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v27, s10
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v19, s8
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v11, s6
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v3, s4
; GFX11-TRUE16-NEXT:  .LBB109_5: ; %end
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v4, v35
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v12, v34
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v20, v33
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v28, v32
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v16bf16_to_v32i8_scalar:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    s_cmp_lg_u32 s20, 0
; GFX11-FAKE16-NEXT:    s_mov_b32 s12, 0
; GFX11-FAKE16-NEXT:    s_cbranch_scc0 .LBB109_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-FAKE16-NEXT:    s_lshr_b32 s24, s19, 24
; GFX11-FAKE16-NEXT:    s_lshr_b32 s45, s19, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s26, s19, 8
; GFX11-FAKE16-NEXT:    s_lshr_b32 s46, s18, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s28, s18, 8
; GFX11-FAKE16-NEXT:    s_lshr_b32 s21, s17, 24
; GFX11-FAKE16-NEXT:    s_lshr_b32 s43, s17, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s23, s17, 8
; GFX11-FAKE16-NEXT:    s_lshr_b32 s44, s16, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s27, s16, 8
; GFX11-FAKE16-NEXT:    s_lshr_b32 s15, s3, 24
; GFX11-FAKE16-NEXT:    s_lshr_b32 s41, s3, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s20, s3, 8
; GFX11-FAKE16-NEXT:    s_lshr_b32 s42, s2, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s25, s2, 8
; GFX11-FAKE16-NEXT:    s_lshr_b32 s13, s1, 24
; GFX11-FAKE16-NEXT:    s_lshr_b32 s29, s1, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s14, s1, 8
; GFX11-FAKE16-NEXT:    s_lshr_b32 s40, s0, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s22, s0, 8
; GFX11-FAKE16-NEXT:    s_lshr_b64 s[10:11], s[18:19], 24
; GFX11-FAKE16-NEXT:    s_lshr_b64 s[8:9], s[16:17], 24
; GFX11-FAKE16-NEXT:    s_lshr_b64 s[6:7], s[2:3], 24
; GFX11-FAKE16-NEXT:    s_lshr_b64 s[4:5], s[0:1], 24
; GFX11-FAKE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s12
; GFX11-FAKE16-NEXT:    s_cbranch_vccnz .LBB109_4
; GFX11-FAKE16-NEXT:  .LBB109_2: ; %cmp.true
; GFX11-FAKE16-NEXT:    s_lshl_b32 s4, s1, 16
; GFX11-FAKE16-NEXT:    s_and_b32 s1, s1, 0xffff0000
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v0, 0x40c00000, s4
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v1, 0x40c00000, s1
; GFX11-FAKE16-NEXT:    s_and_b32 s4, s0, 0xffff0000
; GFX11-FAKE16-NEXT:    s_lshl_b32 s0, s0, 16
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v3, 0x40c00000, s4
; GFX11-FAKE16-NEXT:    v_bfe_u32 v2, v0, 16, 1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v4, v1, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v9, 0x400000, v1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v6, 0x400000, v0
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v0, v0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v5, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, v4, v1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v10, v3, 16, 1
; GFX11-FAKE16-NEXT:    s_and_b32 s1, s3, 0xffff0000
; GFX11-FAKE16-NEXT:    s_lshl_b32 s3, s3, 16
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v7, 0x40c00000, s1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, 0x7fff, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, v2, v0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v8, 0x40c00000, s3
; GFX11-FAKE16-NEXT:    s_and_b32 s0, s2, 0xffff0000
; GFX11-FAKE16-NEXT:    v_bfe_u32 v11, v7, 16, 1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, 0x7fff, v2
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v0, v2, v6, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v1, v1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v6, v5, 16, 1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, 0x400000, v3
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_4) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v0
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v1, v4, v9 :: v_dual_add_nc_u32 v4, v10, v3
; GFX11-FAKE16-NEXT:    v_bfe_u32 v10, v8, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, 0x400000, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, 0x7fff, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v9, v6, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v6, 16, v1
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v2, v4, v2 :: v_dual_and_b32 v1, 0xffff, v35
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v9, 0x7fff, v9
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v5, v5
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v37, v6, 16, v1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v1, v10, v8
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, v11, v7
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, 0x400000, v8
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v0, v9, v0, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v8, v8
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v1, 0x7fff, v1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v5, 0x400000, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v1, v1, v4, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v7, v7
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v4, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    s_lshl_b32 s0, s2, 16
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v7, 0xffff, v0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v1
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v3, v3, v5, vcc_lo
; GFX11-FAKE16-NEXT:    v_bfe_u32 v1, v4, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v36, v2, 16, v7
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xffff, v34
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v14, 16, v3
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v3, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v1, v1, v4
; GFX11-FAKE16-NEXT:    s_and_b32 s0, s17, 0xffff0000
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v7, 24, v37
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v9, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    v_bfe_u32 v8, v3, 16, 1
; GFX11-FAKE16-NEXT:    s_lshl_b32 s0, s17, 16
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v39, v14, 16, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v1, 0x7fff, v1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v5, 0x400000, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v8, v8, v3
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v4, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    v_bfe_u32 v10, v9, 16, 1
; GFX11-FAKE16-NEXT:    s_and_b32 s0, s16, 0xffff0000
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v1, v1, v5, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v5, 0x7fff, v8
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v8, 0x400000, v3
; GFX11-FAKE16-NEXT:    v_bfe_u32 v11, v4, 16, 1
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v12, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    s_lshl_b32 s0, s16, 16
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v13, 0x400000, v9
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v11, v11, v4
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v3, v5, v8, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v5, v10, v9
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v4, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v10, 16, v1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v1, v12, 16, 1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v8, 16, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, 0x7fff, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v5, 0x7fff, v11
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, 0x400000, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v1, v1, v12
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v15, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    s_and_b32 s0, s19, 0xffff0000
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v4, v5, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v1, 0x7fff, v1
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v5, 0x400000, v12
; GFX11-FAKE16-NEXT:    v_bfe_u32 v11, v15, 16, 1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v4
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v3, v3, v13, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v12, v12
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, v11, v15
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, 0x400000, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v3
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v3, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    s_lshl_b32 s0, s19, 16
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v1, v1, v5, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v9, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    s_lshl_b32 s0, s18, 16
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v15, v15
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v12, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v18, 16, v1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v1, 0x7fff, v4
; GFX11-FAKE16-NEXT:    v_bfe_u32 v4, v3, 16, 1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v9, 16, 1
; GFX11-FAKE16-NEXT:    v_bfe_u32 v17, v12, 16, 1
; GFX11-FAKE16-NEXT:    s_and_b32 s0, s18, 0xffff0000
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v19, 0x400000, v9
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, v4, v3
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v1, v1, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v11, v13, v9
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v16, 0x40c00000, s0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v15, v17, v12
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v9, v9
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v20, 0x400000, v12
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v11, 0x7fff, v11
; GFX11-FAKE16-NEXT:    v_bfe_u32 v13, v16, 16, 1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v15, 0x7fff, v15
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, 0x7fff, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v17, 0x400000, v3
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v9, v11, v19, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v12, v12
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v13, v13, v16
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v12, v15, v20 :: v_dual_and_b32 v5, 0xffff, v33
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v3, v3
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v11, 0x7fff, v13
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v13, 0x400000, v16
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v49, v22, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v12
; GFX11-FAKE16-NEXT:    v_cndmask_b32_e32 v3, v4, v17, vcc_lo
; GFX11-FAKE16-NEXT:    v_cmp_u_f32_e32 vcc_lo, v16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v16, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 24, v49
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 8, v49
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v3
; GFX11-FAKE16-NEXT:    v_dual_cndmask_b32 v4, v11, v13 :: v_dual_and_b32 v3, 0xffff, v24
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v15, 24, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v13, 8, v39
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v5, 8, v37
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(SKIP_3) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v4
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xffff, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v9
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v9, 0xffff, v8
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v50, v26, 16, v3
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v48, v18, 16, v4
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v1, 0xffff, v32
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v38, v10, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[3:4], 24, v[36:37]
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 8, v50
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[19:20], 24, v[48:49]
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v51, v30, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[11:12], 24, v[38:39]
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v17, 8, v48
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v9, 8, v38
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v1, 8, v36
; GFX11-FAKE16-NEXT:    v_lshrrev_b64 v[27:28], 24, v[50:51]
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 24, v51
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 8, v51
; GFX11-FAKE16-NEXT:    s_branch .LBB109_5
; GFX11-FAKE16-NEXT:  .LBB109_3:
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr22
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr40
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr4
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr14
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr29
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr13
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr25
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr42
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr6
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr41
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr15
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr27
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr44
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr8
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr23
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr43
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr21
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr28
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr46
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr10
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr26
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr45
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr24
; GFX11-FAKE16-NEXT:    s_branch .LBB109_2
; GFX11-FAKE16-NEXT:  .LBB109_4:
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v24, s18 :: v_dual_mov_b32 v33, s17
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v26, s46 :: v_dual_mov_b32 v35, s1
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v32, s19 :: v_dual_mov_b32 v25, s28
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v30, s45 :: v_dual_mov_b32 v31, s24
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v16, s16 :: v_dual_mov_b32 v29, s26
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v18, s44 :: v_dual_mov_b32 v17, s27
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v22, s43 :: v_dual_mov_b32 v23, s21
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v8, s2 :: v_dual_mov_b32 v21, s23
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v10, s42 :: v_dual_mov_b32 v9, s25
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v34, s3 :: v_dual_mov_b32 v15, s15
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v14, s41 :: v_dual_mov_b32 v13, s20
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s22
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v2, s40 :: v_dual_mov_b32 v7, s13
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v6, s29 :: v_dual_mov_b32 v5, s14
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v27, s10
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v19, s8
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v11, s6
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v3, s4
; GFX11-FAKE16-NEXT:  .LBB109_5: ; %end
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v4, v35
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v12, v34
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v20, v33
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v28, v32
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <16 x bfloat> %a, splat (bfloat 0xR40C0)
  %a2 = bitcast <16 x bfloat> %a1 to <32 x i8>
  br label %end

cmp.false:
  %a3 = bitcast <16 x bfloat> %a to <32 x i8>
  br label %end

end:
  %phi = phi <32 x i8> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <32 x i8> %phi
}

define <16 x bfloat> @bitcast_v32i8_to_v16bf16(<32 x i8> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v32i8_to_v16bf16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    buffer_load_dword v33, off, s[0:3], s32 offset:4
; SI-NEXT:    buffer_load_dword v34, off, s[0:3], s32
; SI-NEXT:    v_lshlrev_b32_e32 v31, 24, v3
; SI-NEXT:    v_lshlrev_b32_e32 v36, 8, v5
; SI-NEXT:    v_lshlrev_b32_e32 v32, 24, v7
; SI-NEXT:    v_lshlrev_b32_e32 v35, 24, v11
; SI-NEXT:    v_lshlrev_b32_e32 v50, 8, v13
; SI-NEXT:    v_lshlrev_b32_e32 v48, 24, v15
; SI-NEXT:    v_lshlrev_b32_e32 v49, 24, v19
; SI-NEXT:    v_lshlrev_b32_e32 v53, 8, v21
; SI-NEXT:    v_lshlrev_b32_e32 v51, 24, v23
; SI-NEXT:    v_lshlrev_b32_e32 v52, 24, v27
; SI-NEXT:    v_lshlrev_b32_e32 v55, 8, v29
; SI-NEXT:    ; implicit-def: $vgpr3
; SI-NEXT:    ; implicit-def: $vgpr5
; SI-NEXT:    ; implicit-def: $vgpr7
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr27
; SI-NEXT:    ; implicit-def: $vgpr29
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:    s_waitcnt vmcnt(1)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v33
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_lshlrev_b32_e32 v54, 24, v34
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB110_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_lshlrev_b32_e32 v1, 24, v1
; SI-NEXT:    v_or_b32_e32 v3, v1, v0
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_or_b32_e32 v5, v31, v0
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v4
; SI-NEXT:    v_or_b32_e32 v0, v0, v36
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v0
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_or_b32_e32 v11, v32, v0
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v8
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_lshlrev_b32_e32 v1, 24, v9
; SI-NEXT:    v_or_b32_e32 v13, v1, v0
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v10
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_or_b32_e32 v15, v35, v0
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v12
; SI-NEXT:    v_or_b32_e32 v0, v0, v50
; SI-NEXT:    v_lshlrev_b32_e32 v19, 16, v0
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v14
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_or_b32_e32 v21, v48, v0
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v16
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_lshlrev_b32_e32 v1, 24, v17
; SI-NEXT:    v_or_b32_e32 v23, v1, v0
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v18
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_or_b32_e32 v27, v49, v0
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v20
; SI-NEXT:    v_or_b32_e32 v0, v0, v53
; SI-NEXT:    v_lshlrev_b32_e32 v29, 16, v0
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v22
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_or_b32_e32 v33, v51, v0
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v24
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_lshlrev_b32_e32 v1, 24, v25
; SI-NEXT:    v_or_b32_e32 v34, v1, v0
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v26
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_or_b32_e32 v37, v52, v0
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v28
; SI-NEXT:    v_or_b32_e32 v0, v0, v55
; SI-NEXT:    v_lshlrev_b32_e32 v38, 16, v0
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v30
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_or_b32_e32 v39, v54, v0
; SI-NEXT:    ; implicit-def: $vgpr0
; SI-NEXT:    ; implicit-def: $vgpr1
; SI-NEXT:    ; implicit-def: $vgpr2
; SI-NEXT:    ; implicit-def: $vgpr4
; SI-NEXT:    ; implicit-def: $vgpr6
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr24
; SI-NEXT:    ; implicit-def: $vgpr25
; SI-NEXT:    ; implicit-def: $vgpr26
; SI-NEXT:    ; implicit-def: $vgpr28
; SI-NEXT:    ; implicit-def: $vgpr30
; SI-NEXT:    ; implicit-def: $vgpr31
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr50
; SI-NEXT:    ; implicit-def: $vgpr48
; SI-NEXT:    ; implicit-def: $vgpr49
; SI-NEXT:    ; implicit-def: $vgpr53
; SI-NEXT:    ; implicit-def: $vgpr51
; SI-NEXT:    ; implicit-def: $vgpr52
; SI-NEXT:    ; implicit-def: $vgpr55
; SI-NEXT:    ; implicit-def: $vgpr54
; SI-NEXT:  .LBB110_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB110_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v28
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v3
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v30
; SI-NEXT:    v_or_b32_e32 v3, v55, v3
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v5
; SI-NEXT:    v_add_i32_e32 v3, vcc, 0x300, v3
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_or_b32_e32 v5, v54, v5
; SI-NEXT:    v_or_b32_e32 v3, v5, v3
; SI-NEXT:    s_mov_b32 s7, 0x3000000
; SI-NEXT:    v_add_i32_e32 v28, vcc, s7, v3
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v24
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v5, 8, v25
; SI-NEXT:    v_or_b32_e32 v3, v5, v3
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v26
; SI-NEXT:    s_movk_i32 s6, 0x300
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v5
; SI-NEXT:    v_add_i32_e32 v3, vcc, s6, v3
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_or_b32_e32 v5, v52, v5
; SI-NEXT:    v_or_b32_e32 v3, v5, v3
; SI-NEXT:    v_add_i32_e32 v24, vcc, s7, v3
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v20
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v3
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v22
; SI-NEXT:    v_or_b32_e32 v3, v53, v3
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v5
; SI-NEXT:    v_add_i32_e32 v3, vcc, s6, v3
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_or_b32_e32 v5, v51, v5
; SI-NEXT:    v_or_b32_e32 v3, v5, v3
; SI-NEXT:    v_add_i32_e32 v20, vcc, s7, v3
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v16
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v5, 8, v17
; SI-NEXT:    v_or_b32_e32 v3, v5, v3
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v18
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v5
; SI-NEXT:    v_add_i32_e32 v3, vcc, s6, v3
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_or_b32_e32 v5, v49, v5
; SI-NEXT:    v_or_b32_e32 v3, v5, v3
; SI-NEXT:    v_add_i32_e32 v16, vcc, s7, v3
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v12
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v3
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v14
; SI-NEXT:    v_or_b32_e32 v3, v50, v3
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v5
; SI-NEXT:    v_add_i32_e32 v3, vcc, s6, v3
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_or_b32_e32 v5, v48, v5
; SI-NEXT:    v_or_b32_e32 v3, v5, v3
; SI-NEXT:    v_add_i32_e32 v12, vcc, s7, v3
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v8
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v5, 8, v9
; SI-NEXT:    v_or_b32_e32 v3, v5, v3
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v10
; SI-NEXT:    v_and_b32_e32 v5, 0xff, v5
; SI-NEXT:    v_add_i32_e32 v3, vcc, s6, v3
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_or_b32_e32 v5, v35, v5
; SI-NEXT:    v_or_b32_e32 v3, v5, v3
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:    v_add_i32_e32 v8, vcc, s7, v3
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v4
; SI-NEXT:    v_and_b32_e32 v0, 0xff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v1, 8, v1
; SI-NEXT:    v_and_b32_e32 v3, 0xff, v3
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v6
; SI-NEXT:    v_or_b32_e32 v0, v1, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v2
; SI-NEXT:    v_or_b32_e32 v3, v36, v3
; SI-NEXT:    v_and_b32_e32 v4, 0xff, v4
; SI-NEXT:    v_and_b32_e32 v1, 0xff, v1
; SI-NEXT:    v_add_i32_e32 v3, vcc, s6, v3
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_add_i32_e32 v0, vcc, s6, v0
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_or_b32_e32 v4, v32, v4
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_or_b32_e32 v1, v31, v1
; SI-NEXT:    v_or_b32_e32 v3, v4, v3
; SI-NEXT:    v_or_b32_e32 v0, v1, v0
; SI-NEXT:    v_add_i32_e32 v4, vcc, s7, v3
; SI-NEXT:    v_add_i32_e32 v0, vcc, s7, v0
; SI-NEXT:    v_and_b32_e32 v5, 0xffff0000, v0
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v0
; SI-NEXT:    v_and_b32_e32 v11, 0xffff0000, v4
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v4
; SI-NEXT:    v_and_b32_e32 v15, 0xffff0000, v8
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v8
; SI-NEXT:    v_and_b32_e32 v21, 0xffff0000, v12
; SI-NEXT:    v_lshlrev_b32_e32 v19, 16, v12
; SI-NEXT:    v_and_b32_e32 v27, 0xffff0000, v16
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v16
; SI-NEXT:    v_and_b32_e32 v33, 0xffff0000, v20
; SI-NEXT:    v_lshlrev_b32_e32 v29, 16, v20
; SI-NEXT:    v_and_b32_e32 v37, 0xffff0000, v24
; SI-NEXT:    v_lshlrev_b32_e32 v34, 16, v24
; SI-NEXT:    v_and_b32_e32 v39, 0xffff0000, v28
; SI-NEXT:    v_lshlrev_b32_e32 v38, 16, v28
; SI-NEXT:  .LBB110_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_mul_f32_e32 v0, 1.0, v5
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_mul_f32_e32 v1, 1.0, v3
; SI-NEXT:    v_alignbit_b32 v0, v0, v1, 16
; SI-NEXT:    v_mul_f32_e32 v1, 1.0, v11
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_mul_f32_e32 v2, 1.0, v7
; SI-NEXT:    v_alignbit_b32 v1, v1, v2, 16
; SI-NEXT:    v_mul_f32_e32 v2, 1.0, v15
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_mul_f32_e32 v3, 1.0, v13
; SI-NEXT:    v_alignbit_b32 v2, v2, v3, 16
; SI-NEXT:    v_mul_f32_e32 v3, 1.0, v21
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_mul_f32_e32 v4, 1.0, v19
; SI-NEXT:    v_alignbit_b32 v3, v3, v4, 16
; SI-NEXT:    v_mul_f32_e32 v4, 1.0, v27
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_mul_f32_e32 v5, 1.0, v23
; SI-NEXT:    v_alignbit_b32 v4, v4, v5, 16
; SI-NEXT:    v_mul_f32_e32 v5, 1.0, v33
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_mul_f32_e32 v6, 1.0, v29
; SI-NEXT:    v_alignbit_b32 v5, v5, v6, 16
; SI-NEXT:    v_mul_f32_e32 v6, 1.0, v37
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_mul_f32_e32 v7, 1.0, v34
; SI-NEXT:    v_alignbit_b32 v6, v6, v7, 16
; SI-NEXT:    v_mul_f32_e32 v7, 1.0, v39
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_mul_f32_e32 v8, 1.0, v38
; SI-NEXT:    v_alignbit_b32 v7, v7, v8, 16
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v32i8_to_v16bf16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_mov_b32_e32 v32, v0
; VI-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:4
; VI-NEXT:    buffer_load_ushort v39, off, s[0:3], s32
; VI-NEXT:    v_mov_b32_e32 v33, v7
; VI-NEXT:    v_mov_b32_e32 v31, v6
; VI-NEXT:    v_mov_b32_e32 v37, v5
; VI-NEXT:    v_mov_b32_e32 v36, v4
; VI-NEXT:    v_mov_b32_e32 v35, v3
; VI-NEXT:    v_mov_b32_e32 v34, v2
; VI-NEXT:    v_mov_b32_e32 v38, v1
; VI-NEXT:    s_waitcnt vmcnt(1)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v0
; VI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execnz .LBB110_3
; VI-NEXT:  ; %bb.1: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execnz .LBB110_4
; VI-NEXT:  .LBB110_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB110_3: ; %cmp.false
; VI-NEXT:    s_mov_b32 s6, 0xc0c0004
; VI-NEXT:    v_perm_b32 v1, v34, v35, s6
; VI-NEXT:    v_perm_b32 v0, v32, v38, s6
; VI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_perm_b32 v2, v31, v33, s6
; VI-NEXT:    v_or_b32_e32 v0, v0, v1
; VI-NEXT:    v_perm_b32 v1, v36, v37, s6
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_perm_b32 v3, v10, v11, s6
; VI-NEXT:    v_or_b32_e32 v1, v1, v2
; VI-NEXT:    v_perm_b32 v2, v8, v9, s6
; VI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_perm_b32 v4, v14, v15, s6
; VI-NEXT:    v_or_b32_e32 v2, v2, v3
; VI-NEXT:    v_perm_b32 v3, v12, v13, s6
; VI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_perm_b32 v5, v18, v19, s6
; VI-NEXT:    v_or_b32_e32 v3, v3, v4
; VI-NEXT:    v_perm_b32 v4, v16, v17, s6
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_perm_b32 v6, v22, v23, s6
; VI-NEXT:    v_or_b32_e32 v4, v4, v5
; VI-NEXT:    v_perm_b32 v5, v20, v21, s6
; VI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_perm_b32 v7, v26, v27, s6
; VI-NEXT:    v_or_b32_e32 v5, v5, v6
; VI-NEXT:    v_perm_b32 v6, v24, v25, s6
; VI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    v_perm_b32 v8, v30, v39, s6
; VI-NEXT:    v_or_b32_e32 v6, v6, v7
; VI-NEXT:    v_perm_b32 v7, v28, v29, s6
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; VI-NEXT:    v_or_b32_e32 v7, v7, v8
; VI-NEXT:    ; implicit-def: $vgpr32
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr34
; VI-NEXT:    ; implicit-def: $vgpr35
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr31
; VI-NEXT:    ; implicit-def: $vgpr33
; VI-NEXT:    ; implicit-def: $vgpr8
; VI-NEXT:    ; implicit-def: $vgpr9
; VI-NEXT:    ; implicit-def: $vgpr10
; VI-NEXT:    ; implicit-def: $vgpr11
; VI-NEXT:    ; implicit-def: $vgpr12
; VI-NEXT:    ; implicit-def: $vgpr13
; VI-NEXT:    ; implicit-def: $vgpr14
; VI-NEXT:    ; implicit-def: $vgpr15
; VI-NEXT:    ; implicit-def: $vgpr16
; VI-NEXT:    ; implicit-def: $vgpr17
; VI-NEXT:    ; implicit-def: $vgpr18
; VI-NEXT:    ; implicit-def: $vgpr19
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr21
; VI-NEXT:    ; implicit-def: $vgpr22
; VI-NEXT:    ; implicit-def: $vgpr23
; VI-NEXT:    ; implicit-def: $vgpr24
; VI-NEXT:    ; implicit-def: $vgpr25
; VI-NEXT:    ; implicit-def: $vgpr26
; VI-NEXT:    ; implicit-def: $vgpr27
; VI-NEXT:    ; implicit-def: $vgpr28
; VI-NEXT:    ; implicit-def: $vgpr29
; VI-NEXT:    ; implicit-def: $vgpr30
; VI-NEXT:    ; implicit-def: $vgpr39
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB110_2
; VI-NEXT:  .LBB110_4: ; %cmp.true
; VI-NEXT:    v_add_u16_e32 v0, 3, v30
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    v_lshlrev_b16_e32 v1, 8, v39
; VI-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_mov_b32_e32 v1, 0x300
; VI-NEXT:    v_add_u16_sdwa v7, v0, v1 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v0, 3, v28
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v29
; VI-NEXT:    v_or_b32_sdwa v28, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v0, 3, v26
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v27
; VI-NEXT:    v_or_b32_sdwa v0, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_sdwa v6, v0, v1 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v0, 3, v24
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v25
; VI-NEXT:    v_or_b32_sdwa v24, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v0, 3, v22
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v23
; VI-NEXT:    v_or_b32_sdwa v0, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_sdwa v5, v0, v1 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v0, 3, v20
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v21
; VI-NEXT:    v_or_b32_sdwa v20, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v0, 3, v18
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v19
; VI-NEXT:    v_or_b32_sdwa v0, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_sdwa v4, v0, v1 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v0, 3, v16
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v17
; VI-NEXT:    v_or_b32_sdwa v16, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v0, 3, v14
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v15
; VI-NEXT:    v_or_b32_sdwa v0, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_sdwa v3, v0, v1 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v0, 3, v12
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v13
; VI-NEXT:    v_or_b32_sdwa v12, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v0, 3, v10
; VI-NEXT:    v_lshlrev_b16_e32 v2, 8, v11
; VI-NEXT:    v_or_b32_sdwa v0, v2, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_sdwa v2, v0, v1 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v0, 3, v8
; VI-NEXT:    v_lshlrev_b16_e32 v8, 8, v9
; VI-NEXT:    v_or_b32_sdwa v8, v8, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v0, 3, v31
; VI-NEXT:    v_lshlrev_b16_e32 v9, 8, v33
; VI-NEXT:    v_or_b32_sdwa v0, v9, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_sdwa v9, v0, v1 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v0, 3, v36
; VI-NEXT:    v_lshlrev_b16_e32 v10, 8, v37
; VI-NEXT:    v_or_b32_sdwa v10, v10, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_add_u16_e32 v0, 3, v34
; VI-NEXT:    v_lshlrev_b16_e32 v11, 8, v35
; VI-NEXT:    v_add_u16_e32 v8, 0x300, v8
; VI-NEXT:    v_or_b32_sdwa v0, v11, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_or_b32_e32 v2, v8, v2
; VI-NEXT:    v_add_u16_e32 v8, 0x300, v12
; VI-NEXT:    v_add_u16_sdwa v0, v0, v1 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_u16_e32 v1, 3, v32
; VI-NEXT:    v_lshlrev_b16_e32 v11, 8, v38
; VI-NEXT:    v_or_b32_e32 v3, v8, v3
; VI-NEXT:    v_add_u16_e32 v8, 0x300, v16
; VI-NEXT:    v_or_b32_sdwa v1, v11, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; VI-NEXT:    v_or_b32_e32 v4, v8, v4
; VI-NEXT:    v_add_u16_e32 v8, 0x300, v20
; VI-NEXT:    v_add_u16_e32 v1, 0x300, v1
; VI-NEXT:    v_or_b32_e32 v5, v8, v5
; VI-NEXT:    v_add_u16_e32 v8, 0x300, v24
; VI-NEXT:    v_or_b32_e32 v0, v1, v0
; VI-NEXT:    v_add_u16_e32 v1, 0x300, v10
; VI-NEXT:    v_or_b32_e32 v6, v8, v6
; VI-NEXT:    v_add_u16_e32 v8, 0x300, v28
; VI-NEXT:    v_or_b32_e32 v1, v1, v9
; VI-NEXT:    v_or_b32_e32 v7, v8, v7
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v32i8_to_v16bf16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_mov_b32_e32 v37, v1
; GFX9-NEXT:    v_mov_b32_e32 v36, v0
; GFX9-NEXT:    buffer_load_dword v0, off, s[0:3], s32 offset:4
; GFX9-NEXT:    buffer_load_ushort v1, off, s[0:3], s32
; GFX9-NEXT:    v_mov_b32_e32 v38, v7
; GFX9-NEXT:    v_mov_b32_e32 v31, v6
; GFX9-NEXT:    v_mov_b32_e32 v33, v5
; GFX9-NEXT:    v_mov_b32_e32 v34, v4
; GFX9-NEXT:    v_mov_b32_e32 v32, v3
; GFX9-NEXT:    v_mov_b32_e32 v35, v2
; GFX9-NEXT:    v_lshlrev_b16_e32 v39, 8, v17
; GFX9-NEXT:    v_lshlrev_b16_e32 v17, 8, v19
; GFX9-NEXT:    v_lshlrev_b16_e32 v19, 8, v23
; GFX9-NEXT:    v_lshlrev_b16_e32 v25, 8, v25
; GFX9-NEXT:    v_lshlrev_b16_e32 v23, 8, v27
; GFX9-NEXT:    s_waitcnt vmcnt(1)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v0
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    v_lshlrev_b16_e32 v27, 8, v1
; GFX9-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execnz .LBB110_3
; GFX9-NEXT:  ; %bb.1: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execnz .LBB110_4
; GFX9-NEXT:  .LBB110_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB110_3: ; %cmp.false
; GFX9-NEXT:    s_mov_b32 s6, 0xc0c0004
; GFX9-NEXT:    v_perm_b32 v0, v36, v37, s6
; GFX9-NEXT:    v_perm_b32 v1, v35, v32, s6
; GFX9-NEXT:    s_mov_b32 s7, 0x5040100
; GFX9-NEXT:    v_perm_b32 v0, v1, v0, s7
; GFX9-NEXT:    v_perm_b32 v1, v34, v33, s6
; GFX9-NEXT:    v_perm_b32 v2, v31, v38, s6
; GFX9-NEXT:    v_perm_b32 v1, v2, v1, s7
; GFX9-NEXT:    v_perm_b32 v2, v8, v9, s6
; GFX9-NEXT:    v_perm_b32 v3, v10, v11, s6
; GFX9-NEXT:    v_perm_b32 v2, v3, v2, s7
; GFX9-NEXT:    v_perm_b32 v3, v12, v13, s6
; GFX9-NEXT:    v_perm_b32 v4, v14, v15, s6
; GFX9-NEXT:    v_perm_b32 v3, v4, v3, s7
; GFX9-NEXT:    v_or_b32_sdwa v4, v16, v39 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:BYTE_0 src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v5, v18, v17 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:BYTE_0 src1_sel:DWORD
; GFX9-NEXT:    v_perm_b32 v4, v5, v4, s7
; GFX9-NEXT:    v_or_b32_sdwa v5, v22, v19 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:BYTE_0 src1_sel:DWORD
; GFX9-NEXT:    v_perm_b32 v6, v20, v21, s6
; GFX9-NEXT:    v_perm_b32 v5, v5, v6, s7
; GFX9-NEXT:    v_or_b32_sdwa v6, v24, v25 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:BYTE_0 src1_sel:DWORD
; GFX9-NEXT:    v_or_b32_sdwa v7, v26, v23 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:BYTE_0 src1_sel:DWORD
; GFX9-NEXT:    v_perm_b32 v6, v7, v6, s7
; GFX9-NEXT:    v_or_b32_sdwa v7, v30, v27 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:BYTE_0 src1_sel:DWORD
; GFX9-NEXT:    v_perm_b32 v8, v28, v29, s6
; GFX9-NEXT:    v_perm_b32 v7, v7, v8, s7
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr35
; GFX9-NEXT:    ; implicit-def: $vgpr32
; GFX9-NEXT:    ; implicit-def: $vgpr34
; GFX9-NEXT:    ; implicit-def: $vgpr33
; GFX9-NEXT:    ; implicit-def: $vgpr31
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr8
; GFX9-NEXT:    ; implicit-def: $vgpr9
; GFX9-NEXT:    ; implicit-def: $vgpr10
; GFX9-NEXT:    ; implicit-def: $vgpr11
; GFX9-NEXT:    ; implicit-def: $vgpr12
; GFX9-NEXT:    ; implicit-def: $vgpr13
; GFX9-NEXT:    ; implicit-def: $vgpr14
; GFX9-NEXT:    ; implicit-def: $vgpr15
; GFX9-NEXT:    ; implicit-def: $vgpr16
; GFX9-NEXT:    ; implicit-def: $vgpr18
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr21
; GFX9-NEXT:    ; implicit-def: $vgpr22
; GFX9-NEXT:    ; implicit-def: $vgpr24
; GFX9-NEXT:    ; implicit-def: $vgpr26
; GFX9-NEXT:    ; implicit-def: $vgpr28
; GFX9-NEXT:    ; implicit-def: $vgpr29
; GFX9-NEXT:    ; implicit-def: $vgpr30
; GFX9-NEXT:    ; implicit-def: $vgpr39
; GFX9-NEXT:    ; implicit-def: $vgpr17
; GFX9-NEXT:    ; implicit-def: $vgpr19
; GFX9-NEXT:    ; implicit-def: $vgpr25
; GFX9-NEXT:    ; implicit-def: $vgpr23
; GFX9-NEXT:    ; implicit-def: $vgpr27
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB110_2
; GFX9-NEXT:  .LBB110_4: ; %cmp.true
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v28
; GFX9-NEXT:    v_lshlrev_b16_e32 v1, 8, v29
; GFX9-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v7, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v30
; GFX9-NEXT:    v_or_b32_sdwa v0, v27, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v27, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v24
; GFX9-NEXT:    v_or_b32_sdwa v0, v25, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v6, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v26
; GFX9-NEXT:    v_or_b32_sdwa v0, v23, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v23, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v20
; GFX9-NEXT:    v_lshlrev_b16_e32 v1, 8, v21
; GFX9-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v5, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v22
; GFX9-NEXT:    v_or_b32_sdwa v0, v19, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v19, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v16
; GFX9-NEXT:    v_or_b32_sdwa v0, v39, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v4, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v18
; GFX9-NEXT:    v_or_b32_sdwa v0, v17, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v16, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v12
; GFX9-NEXT:    v_lshlrev_b16_e32 v1, 8, v13
; GFX9-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v3, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v14
; GFX9-NEXT:    v_lshlrev_b16_e32 v1, 8, v15
; GFX9-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v12, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v8
; GFX9-NEXT:    v_lshlrev_b16_e32 v1, 8, v9
; GFX9-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v2, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v10
; GFX9-NEXT:    v_lshlrev_b16_e32 v1, 8, v11
; GFX9-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v8, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v34
; GFX9-NEXT:    v_lshlrev_b16_e32 v1, 8, v33
; GFX9-NEXT:    v_or_b32_sdwa v0, v1, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v1, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v31
; GFX9-NEXT:    v_lshlrev_b16_e32 v9, 8, v38
; GFX9-NEXT:    v_or_b32_sdwa v0, v9, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v9, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v0, 3, v36
; GFX9-NEXT:    v_lshlrev_b16_e32 v10, 8, v37
; GFX9-NEXT:    v_or_b32_sdwa v0, v10, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v10, 3, v35
; GFX9-NEXT:    v_lshlrev_b16_e32 v11, 8, v32
; GFX9-NEXT:    v_or_b32_sdwa v10, v11, v10 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:BYTE_0
; GFX9-NEXT:    v_add_u16_e32 v0, 0x300, v0
; GFX9-NEXT:    v_add_u16_e32 v10, 0x300, v10
; GFX9-NEXT:    s_mov_b32 s6, 0x5040100
; GFX9-NEXT:    v_perm_b32 v0, v10, v0, s6
; GFX9-NEXT:    v_perm_b32 v1, v9, v1, s6
; GFX9-NEXT:    v_perm_b32 v2, v8, v2, s6
; GFX9-NEXT:    v_perm_b32 v3, v12, v3, s6
; GFX9-NEXT:    v_perm_b32 v4, v16, v4, s6
; GFX9-NEXT:    v_perm_b32 v5, v19, v5, s6
; GFX9-NEXT:    v_perm_b32 v6, v23, v6, s6
; GFX9-NEXT:    v_perm_b32 v7, v27, v7, s6
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v32i8_to_v16bf16:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_clause 0x1
; GFX11-TRUE16-NEXT:    scratch_load_b32 v37, off, s32 offset:4
; GFX11-TRUE16-NEXT:    scratch_load_d16_hi_b16 v31, off, s32
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v27.h, v27.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v25.h, v25.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v23.h, v23.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v19.h, v19.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v17.h, v17.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v34.l, v29.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v36.l, v28.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v33.l, v20.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v17.l, v15.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v28.l, v14.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v25.l, v12.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v15.l, v11.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v27.l, v10.l
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v31.l, v9.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v35.l, v8.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v14.l, v7.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v29.l, v6.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v11.l, v5.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v19.l, v4.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v23.l, v3.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v32.l, v2.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v12.l, v1.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v20.l, v0.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v9.l, 8, v17.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v8.l, 8, v19.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v8.h, 8, v23.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v10.l, 8, v25.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v9.h, 8, v27.h
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v10.h, 8, v31.h
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v37
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB110_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB110_4
; GFX11-TRUE16-NEXT:  .LBB110_2: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB110_3: ; %cmp.false
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr29_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr14_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v3, v29, v14, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr28_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr17_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v6, v28, v17, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr19_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr11_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, v19, v11, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr32_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr23_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v2, v32, v23, 0xc0c0004
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr27_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr15_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v4, v27, v15, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v1.h, v3.l
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr25_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v3, v25, v13, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_and_b16 v5.l, 0xff, v22.l
; GFX11-TRUE16-NEXT:    v_and_b16 v4.h, 0xff, v18.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v3.h, v6.l
; GFX11-TRUE16-NEXT:    v_and_b16 v6.l, 0xff, v30.l
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr12_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v0, v20, v12, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.h, v2.l
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr35_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr31_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v2, v35, v31, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_or_b16 v6.h, v5.l, v8.h
; GFX11-TRUE16-NEXT:    v_and_b16 v7.l, 0xff, v24.l
; GFX11-TRUE16-NEXT:    v_and_b16 v7.h, 0xff, v26.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.h, v4.l
; GFX11-TRUE16-NEXT:    v_and_b16 v4.l, 0xff, v16.l
; GFX11-TRUE16-NEXT:    v_or_b16 v4.h, v4.h, v8.l
; GFX11-TRUE16-NEXT:    v_or_b16 v8.l, v6.l, v10.h
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr33_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr21_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, v33, v21, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v5.h, v6.h
; GFX11-TRUE16-NEXT:    v_or_b16 v6.l, v7.l, v10.l
; GFX11-TRUE16-NEXT:    v_or_b16 v6.h, v7.h, v9.h
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr36_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr34_hi16
; GFX11-TRUE16-NEXT:    v_perm_b32 v7, v36, v34, 0xc0c0004
; GFX11-TRUE16-NEXT:    v_or_b16 v4.l, v4.l, v9.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v7.h, v8.l
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr12_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr32_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr23_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr19_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr11_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr29_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr14_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr35_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr31_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr27_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr15_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr25_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr28_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr17_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr16_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr18_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr33_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr21_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr22_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr24_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr26_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr36_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr34_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr30_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr8_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr8_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr10_lo16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_hi16
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr10_hi16
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB110_2
; GFX11-TRUE16-NEXT:  .LBB110_4: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.l, v36.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.h, v30.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.h, v24.l, 3
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v1.l, 8, v34.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.l, v26.l, 3
; GFX11-TRUE16-NEXT:    v_and_b16 v0.l, 0xff, v0.l
; GFX11-TRUE16-NEXT:    v_and_b16 v0.h, 0xff, v0.h
; GFX11-TRUE16-NEXT:    v_and_b16 v1.h, 0xff, v1.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.h, v33.l, 3
; GFX11-TRUE16-NEXT:    v_and_b16 v2.l, 0xff, v2.l
; GFX11-TRUE16-NEXT:    v_or_b16 v0.l, v1.l, v0.l
; GFX11-TRUE16-NEXT:    v_or_b16 v0.h, v10.h, v0.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.l, v22.l, 3
; GFX11-TRUE16-NEXT:    v_or_b16 v1.h, v10.l, v1.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v3.l, 8, v17.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v7.l, 0x300, v0.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v7.h, 0x300, v0.h
; GFX11-TRUE16-NEXT:    v_and_b16 v0.l, 0xff, v2.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v0.h, 8, v21.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v6.l, 0x300, v1.h
; GFX11-TRUE16-NEXT:    v_and_b16 v1.l, 0xff, v1.l
; GFX11-TRUE16-NEXT:    v_or_b16 v1.h, v9.h, v2.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.l, v16.l, 3
; GFX11-TRUE16-NEXT:    v_or_b16 v0.l, v0.h, v0.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.h, v18.l, 3
; GFX11-TRUE16-NEXT:    v_or_b16 v1.l, v8.h, v1.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v6.h, 0x300, v1.h
; GFX11-TRUE16-NEXT:    v_and_b16 v1.h, 0xff, v2.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v5.l, 0x300, v0.l
; GFX11-TRUE16-NEXT:    v_and_b16 v0.l, 0xff, v0.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v5.h, 0x300, v1.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.h, v25.l, 3
; GFX11-TRUE16-NEXT:    v_or_b16 v1.l, v9.l, v1.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.h, v28.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.l, v35.l, 3
; GFX11-TRUE16-NEXT:    v_or_b16 v0.l, v8.l, v0.l
; GFX11-TRUE16-NEXT:    v_and_b16 v0.h, 0xff, v0.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v2.h, 8, v13.l
; GFX11-TRUE16-NEXT:    v_and_b16 v1.h, 0xff, v1.h
; GFX11-TRUE16-NEXT:    v_and_b16 v2.l, 0xff, v2.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v3.h, 8, v31.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v4.l, 0x300, v1.l
; GFX11-TRUE16-NEXT:    v_or_b16 v0.h, v2.h, v0.h
; GFX11-TRUE16-NEXT:    v_or_b16 v1.l, v3.l, v1.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v4.h, 0x300, v0.l
; GFX11-TRUE16-NEXT:    v_or_b16 v0.l, v3.h, v2.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.h, v27.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v3.l, 0x300, v0.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.h, v19.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.h, v20.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.l, 0x300, v0.l
; GFX11-TRUE16-NEXT:    v_and_b16 v0.l, 0xff, v1.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.h, v29.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v8.h, v32.l, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v3.h, 0x300, v1.l
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v1.l, 8, v15.l
; GFX11-TRUE16-NEXT:    v_and_b16 v0.h, 0xff, v0.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v8.l, 8, v11.l
; GFX11-TRUE16-NEXT:    v_and_b16 v1.h, 0xff, v1.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v9.l, 8, v14.l
; GFX11-TRUE16-NEXT:    v_and_b16 v2.h, 0xff, v2.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v9.h, 8, v12.l
; GFX11-TRUE16-NEXT:    v_and_b16 v8.h, 0xff, v8.h
; GFX11-TRUE16-NEXT:    v_lshlrev_b16 v10.l, 8, v23.l
; GFX11-TRUE16-NEXT:    v_or_b16 v0.l, v1.l, v0.l
; GFX11-TRUE16-NEXT:    v_or_b16 v0.h, v8.l, v0.h
; GFX11-TRUE16-NEXT:    v_or_b16 v1.h, v9.l, v1.h
; GFX11-TRUE16-NEXT:    v_or_b16 v8.l, v9.h, v2.h
; GFX11-TRUE16-NEXT:    v_or_b16 v8.h, v10.l, v8.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v2.h, 0x300, v0.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.l, 0x300, v0.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v1.h, 0x300, v1.h
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.l, 0x300, v8.l
; GFX11-TRUE16-NEXT:    v_add_nc_u16 v0.h, 0x300, v8.h
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v32i8_to_v16bf16:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v37, v1 :: v_dual_mov_b32 v34, v0
; GFX11-FAKE16-NEXT:    s_clause 0x1
; GFX11-FAKE16-NEXT:    scratch_load_b32 v0, off, s32 offset:4
; GFX11-FAKE16-NEXT:    scratch_load_u16 v1, off, s32
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v33, v7 :: v_dual_mov_b32 v38, v4
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v31, v6 :: v_dual_mov_b32 v36, v3
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v35, v5 :: v_dual_mov_b32 v32, v2
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v39, 8, v17
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v17, 8, v19
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v19, 8, v23
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v25, 8, v25
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v23, 8, v27
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(1)
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v0
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0)
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v27, 8, v1
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB110_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB110_4
; GFX11-FAKE16-NEXT:  .LBB110_2: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB110_3: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v34, v37, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v32, v36, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v38, v35, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v31, v33, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v8, v9, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v10, v11, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v1, v0, 0x5040100
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v8, 0xff, v24
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v3, v2, 0x5040100
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xff, v16
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v5, v4, 0x5040100
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xff, v18
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v9, 0xff, v26
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v10, 0xff, v30
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v7, v3, v39
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xff, v22
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v12, v13, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v14, v15, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, v4, v17
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, v20, v21, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v11, v3, v19
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v8, v8, v25
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v9, v9, v23
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v10, v10, v27
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, v28, v29, 0xc0c0004
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v6, v5, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v4, v7, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v11, v12, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v9, v8, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v10, v13, 0x5040100
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr34
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr37
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr32
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr36
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr38
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr35
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr31
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr33
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr8
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr9
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr10
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr11
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr12
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr13
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr14
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr15
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr16
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr18
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr21
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr22
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr24
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr26
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr28
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr29
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr30
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr39
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr17
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr19
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr25
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr23
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr27
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB110_2
; GFX11-FAKE16-NEXT:  .LBB110_4: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v0, v28, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v1, v30, 3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v2, 8, v29
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v4, v26, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v5, v20, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xff, v0
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v1, 0xff, v1
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, v24, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v6, v22, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xff, v4
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v2, v0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v1, v27, v1
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v2, v16, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xff, v3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v4, v23, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v7, 0x300, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v16, 0x300, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xff, v5
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v1, 8, v21
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xff, v2
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xff, v6
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v25, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v9, 8, v9
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v1, v0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, v39, v2
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v1, v19, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v19, 0x300, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v6, 0x300, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v5, 0x300, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v0, v12, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v4, 0x300, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v2, v8, 3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v3, 8, v13
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v8, v14, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xff, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v12, 0x300, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xff, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v1, v18, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v13, v34, 3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v3, v0
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xff, v8
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v8, 8, v15
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v2, v9, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v9, v10, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v1, 0xff, v1
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v10, 0x300, v0
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v0, v8, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, v38, 3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v8, 0xff, v9
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v9, v31, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v14, v32, 3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v1, v17, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xff, v3
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v15, 8, v35
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v9, 0xff, v9
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v13, 0xff, v13
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v17, 8, v37
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v14, 0xff, v14
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v18, 8, v36
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v20, 8, v33
; GFX11-FAKE16-NEXT:    v_lshlrev_b16 v11, 8, v11
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v3, v15, v3
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v13, v17, v13
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v14, v18, v14
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v9, v20, v9
; GFX11-FAKE16-NEXT:    v_or_b32_e32 v8, v11, v8
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v2, 0x300, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v3, 0x300, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v11, 0x300, v13
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v13, 0x300, v14
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v9, 0x300, v9
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v8, 0x300, v8
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v14, 0x300, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u16 v15, 0x300, v1
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v13, v11, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v9, v3, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v8, v2, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v14, v10, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v15, v4, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v12, v5, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v19, v6, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v16, v7, 0x5040100
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <32 x i8> %a, splat (i8 3)
  %a2 = bitcast <32 x i8> %a1 to <16 x bfloat>
  br label %end

cmp.false:
  %a3 = bitcast <32 x i8> %a to <16 x bfloat>
  br label %end

end:
  %phi = phi <16 x bfloat> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x bfloat> %phi
}

define inreg <16 x bfloat> @bitcast_v32i8_to_v16bf16_scalar(<32 x i8> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v32i8_to_v16bf16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_readfirstlane_b32 s4, v18
; SI-NEXT:    v_readfirstlane_b32 s63, v17
; SI-NEXT:    v_readfirstlane_b32 s72, v16
; SI-NEXT:    v_readfirstlane_b32 s77, v15
; SI-NEXT:    v_readfirstlane_b32 s78, v14
; SI-NEXT:    v_readfirstlane_b32 s56, v13
; SI-NEXT:    v_readfirstlane_b32 s57, v12
; SI-NEXT:    v_readfirstlane_b32 s61, v11
; SI-NEXT:    v_readfirstlane_b32 s73, v10
; SI-NEXT:    v_readfirstlane_b32 s40, v9
; SI-NEXT:    v_readfirstlane_b32 s41, v8
; SI-NEXT:    v_readfirstlane_b32 s45, v7
; SI-NEXT:    v_readfirstlane_b32 s58, v6
; SI-NEXT:    v_readfirstlane_b32 s9, v5
; SI-NEXT:    v_readfirstlane_b32 s10, v4
; SI-NEXT:    v_readfirstlane_b32 s13, v3
; SI-NEXT:    v_readfirstlane_b32 s42, v2
; SI-NEXT:    v_readfirstlane_b32 s6, v1
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    v_readfirstlane_b32 s7, v0
; SI-NEXT:    s_cbranch_scc0 .LBB111_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s4, s16, 0xff
; SI-NEXT:    s_lshl_b32 s4, s4, 16
; SI-NEXT:    s_lshl_b32 s5, s17, 24
; SI-NEXT:    s_or_b32 s8, s5, s4
; SI-NEXT:    s_and_b32 s4, s18, 0xff
; SI-NEXT:    s_lshl_b32 s4, s4, 16
; SI-NEXT:    s_lshl_b32 s5, s19, 24
; SI-NEXT:    s_or_b32 s12, s5, s4
; SI-NEXT:    s_and_b32 s4, s20, 0xff
; SI-NEXT:    s_lshl_b32 s5, s21, 8
; SI-NEXT:    s_or_b32 s4, s4, s5
; SI-NEXT:    s_lshl_b32 s11, s4, 16
; SI-NEXT:    s_and_b32 s4, s22, 0xff
; SI-NEXT:    s_lshl_b32 s4, s4, 16
; SI-NEXT:    s_lshl_b32 s5, s23, 24
; SI-NEXT:    s_or_b32 s15, s5, s4
; SI-NEXT:    s_and_b32 s4, s24, 0xff
; SI-NEXT:    s_lshl_b32 s4, s4, 16
; SI-NEXT:    s_lshl_b32 s5, s25, 24
; SI-NEXT:    s_or_b32 s14, s5, s4
; SI-NEXT:    s_and_b32 s4, s26, 0xff
; SI-NEXT:    s_lshl_b32 s4, s4, 16
; SI-NEXT:    s_lshl_b32 s5, s27, 24
; SI-NEXT:    s_or_b32 s44, s5, s4
; SI-NEXT:    s_and_b32 s4, s28, 0xff
; SI-NEXT:    s_lshl_b32 s5, s29, 8
; SI-NEXT:    s_or_b32 s4, s4, s5
; SI-NEXT:    s_lshl_b32 s43, s4, 16
; SI-NEXT:    s_and_b32 s4, s7, 0xff
; SI-NEXT:    s_lshl_b32 s4, s4, 16
; SI-NEXT:    s_lshl_b32 s5, s6, 24
; SI-NEXT:    s_or_b32 s47, s5, s4
; SI-NEXT:    s_and_b32 s4, s42, 0xff
; SI-NEXT:    s_lshl_b32 s4, s4, 16
; SI-NEXT:    s_lshl_b32 s5, s13, 24
; SI-NEXT:    s_or_b32 s46, s5, s4
; SI-NEXT:    s_and_b32 s4, s10, 0xff
; SI-NEXT:    s_lshl_b32 s4, s4, 16
; SI-NEXT:    s_lshl_b32 s5, s9, 24
; SI-NEXT:    s_or_b32 s60, s5, s4
; SI-NEXT:    s_and_b32 s4, s58, 0xff
; SI-NEXT:    s_lshl_b32 s5, s45, 8
; SI-NEXT:    s_or_b32 s4, s4, s5
; SI-NEXT:    s_lshl_b32 s59, s4, 16
; SI-NEXT:    s_and_b32 s4, s41, 0xff
; SI-NEXT:    s_lshl_b32 s4, s4, 16
; SI-NEXT:    s_lshl_b32 s5, s40, 24
; SI-NEXT:    s_or_b32 s74, s5, s4
; SI-NEXT:    s_and_b32 s4, s73, 0xff
; SI-NEXT:    s_lshl_b32 s4, s4, 16
; SI-NEXT:    s_lshl_b32 s5, s61, 24
; SI-NEXT:    s_or_b32 s62, s5, s4
; SI-NEXT:    s_and_b32 s4, s57, 0xff
; SI-NEXT:    s_lshl_b32 s4, s4, 16
; SI-NEXT:    s_lshl_b32 s5, s56, 24
; SI-NEXT:    s_or_b32 s76, s5, s4
; SI-NEXT:    s_and_b32 s4, s78, 0xff
; SI-NEXT:    s_lshl_b32 s5, s77, 8
; SI-NEXT:    s_or_b32 s4, s4, s5
; SI-NEXT:    s_lshl_b32 s75, s4, 16
; SI-NEXT:    s_and_b32 s4, s72, 0xff
; SI-NEXT:    s_lshl_b32 s4, s4, 16
; SI-NEXT:    s_lshl_b32 s5, s63, 24
; SI-NEXT:    s_or_b32 s79, s5, s4
; SI-NEXT:    s_cbranch_execnz .LBB111_3
; SI-NEXT:  .LBB111_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s78, s78, 3
; SI-NEXT:    s_and_b32 s4, s78, 0xff
; SI-NEXT:    s_lshl_b32 s5, s77, 8
; SI-NEXT:    s_add_i32 s72, s72, 3
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_and_b32 s8, s72, 0xff
; SI-NEXT:    s_addk_i32 s4, 0x300
; SI-NEXT:    s_lshl_b32 s5, s63, 24
; SI-NEXT:    s_lshl_b32 s8, s8, 16
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_or_b32 s5, s5, s8
; SI-NEXT:    s_add_i32 s73, s73, 3
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_and_b32 s5, s73, 0xff
; SI-NEXT:    s_lshl_b32 s8, s61, 8
; SI-NEXT:    s_add_i32 s57, s57, 3
; SI-NEXT:    s_or_b32 s5, s8, s5
; SI-NEXT:    s_and_b32 s11, s57, 0xff
; SI-NEXT:    s_addk_i32 s5, 0x300
; SI-NEXT:    s_lshl_b32 s8, s56, 24
; SI-NEXT:    s_lshl_b32 s11, s11, 16
; SI-NEXT:    s_and_b32 s5, s5, 0xffff
; SI-NEXT:    s_or_b32 s8, s8, s11
; SI-NEXT:    s_add_i32 s58, s58, 3
; SI-NEXT:    s_or_b32 s5, s8, s5
; SI-NEXT:    s_and_b32 s8, s58, 0xff
; SI-NEXT:    s_lshl_b32 s11, s45, 8
; SI-NEXT:    s_add_i32 s41, s41, 3
; SI-NEXT:    s_or_b32 s8, s11, s8
; SI-NEXT:    s_and_b32 s12, s41, 0xff
; SI-NEXT:    s_addk_i32 s8, 0x300
; SI-NEXT:    s_lshl_b32 s11, s40, 24
; SI-NEXT:    s_lshl_b32 s12, s12, 16
; SI-NEXT:    s_and_b32 s8, s8, 0xffff
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    s_or_b32 s8, s11, s8
; SI-NEXT:    s_add_i32 s42, s42, 3
; SI-NEXT:    s_add_i32 s40, s8, 0x3000000
; SI-NEXT:    s_and_b32 s8, s42, 0xff
; SI-NEXT:    s_lshl_b32 s11, s13, 8
; SI-NEXT:    s_add_i32 s10, s10, 3
; SI-NEXT:    s_or_b32 s8, s11, s8
; SI-NEXT:    s_and_b32 s10, s10, 0xff
; SI-NEXT:    s_addk_i32 s8, 0x300
; SI-NEXT:    s_lshl_b32 s9, s9, 24
; SI-NEXT:    s_lshl_b32 s10, s10, 16
; SI-NEXT:    s_and_b32 s8, s8, 0xffff
; SI-NEXT:    s_or_b32 s9, s9, s10
; SI-NEXT:    s_or_b32 s8, s9, s8
; SI-NEXT:    s_add_i32 s28, s28, 3
; SI-NEXT:    s_add_i32 s9, s8, 0x3000000
; SI-NEXT:    s_and_b32 s8, s28, 0xff
; SI-NEXT:    s_lshl_b32 s10, s29, 8
; SI-NEXT:    s_add_i32 s7, s7, 3
; SI-NEXT:    s_or_b32 s8, s10, s8
; SI-NEXT:    s_and_b32 s7, s7, 0xff
; SI-NEXT:    s_addk_i32 s8, 0x300
; SI-NEXT:    s_lshl_b32 s6, s6, 24
; SI-NEXT:    s_lshl_b32 s7, s7, 16
; SI-NEXT:    s_and_b32 s8, s8, 0xffff
; SI-NEXT:    s_or_b32 s6, s6, s7
; SI-NEXT:    s_add_i32 s24, s24, 3
; SI-NEXT:    s_or_b32 s6, s6, s8
; SI-NEXT:    s_and_b32 s7, s24, 0xff
; SI-NEXT:    s_lshl_b32 s8, s25, 8
; SI-NEXT:    s_add_i32 s26, s26, 3
; SI-NEXT:    s_or_b32 s7, s8, s7
; SI-NEXT:    s_and_b32 s10, s26, 0xff
; SI-NEXT:    s_addk_i32 s7, 0x300
; SI-NEXT:    s_lshl_b32 s8, s27, 24
; SI-NEXT:    s_lshl_b32 s10, s10, 16
; SI-NEXT:    s_and_b32 s7, s7, 0xffff
; SI-NEXT:    s_or_b32 s8, s8, s10
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_or_b32 s7, s8, s7
; SI-NEXT:    s_and_b32 s8, s20, 0xff
; SI-NEXT:    s_lshl_b32 s10, s21, 8
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_or_b32 s8, s10, s8
; SI-NEXT:    s_and_b32 s11, s22, 0xff
; SI-NEXT:    s_addk_i32 s8, 0x300
; SI-NEXT:    s_lshl_b32 s10, s23, 24
; SI-NEXT:    s_lshl_b32 s11, s11, 16
; SI-NEXT:    s_and_b32 s8, s8, 0xffff
; SI-NEXT:    s_or_b32 s10, s10, s11
; SI-NEXT:    s_or_b32 s8, s10, s8
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    s_add_i32 s10, s8, 0x3000000
; SI-NEXT:    s_and_b32 s8, s16, 0xff
; SI-NEXT:    s_lshl_b32 s11, s17, 8
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_or_b32 s8, s11, s8
; SI-NEXT:    s_and_b32 s12, s18, 0xff
; SI-NEXT:    s_addk_i32 s8, 0x300
; SI-NEXT:    s_lshl_b32 s11, s19, 24
; SI-NEXT:    s_lshl_b32 s12, s12, 16
; SI-NEXT:    s_and_b32 s8, s8, 0xffff
; SI-NEXT:    s_or_b32 s11, s11, s12
; SI-NEXT:    s_or_b32 s8, s11, s8
; SI-NEXT:    s_add_i32 s4, s4, 0x3000000
; SI-NEXT:    s_add_i32 s5, s5, 0x3000000
; SI-NEXT:    s_add_i32 s6, s6, 0x3000000
; SI-NEXT:    s_add_i32 s7, s7, 0x3000000
; SI-NEXT:    s_add_i32 s8, s8, 0x3000000
; SI-NEXT:    s_and_b32 s12, s8, 0xffff0000
; SI-NEXT:    s_lshl_b32 s8, s8, 16
; SI-NEXT:    s_and_b32 s15, s10, 0xffff0000
; SI-NEXT:    s_lshl_b32 s11, s10, 16
; SI-NEXT:    s_and_b32 s44, s7, 0xffff0000
; SI-NEXT:    s_lshl_b32 s14, s7, 16
; SI-NEXT:    s_and_b32 s47, s6, 0xffff0000
; SI-NEXT:    s_lshl_b32 s43, s6, 16
; SI-NEXT:    s_and_b32 s60, s9, 0xffff0000
; SI-NEXT:    s_lshl_b32 s46, s9, 16
; SI-NEXT:    s_and_b32 s74, s40, 0xffff0000
; SI-NEXT:    s_lshl_b32 s59, s40, 16
; SI-NEXT:    s_and_b32 s76, s5, 0xffff0000
; SI-NEXT:    s_lshl_b32 s62, s5, 16
; SI-NEXT:    s_and_b32 s79, s4, 0xffff0000
; SI-NEXT:    s_lshl_b32 s75, s4, 16
; SI-NEXT:  .LBB111_3: ; %end
; SI-NEXT:    v_mul_f32_e64 v0, 1.0, s12
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v0
; SI-NEXT:    v_mul_f32_e64 v0, 1.0, s8
; SI-NEXT:    v_lshr_b64 v[0:1], v[0:1], 16
; SI-NEXT:    v_mul_f32_e64 v1, 1.0, s15
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v1
; SI-NEXT:    v_mul_f32_e64 v1, 1.0, s11
; SI-NEXT:    v_lshr_b64 v[1:2], v[1:2], 16
; SI-NEXT:    v_mul_f32_e64 v2, 1.0, s44
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v2
; SI-NEXT:    v_mul_f32_e64 v2, 1.0, s14
; SI-NEXT:    v_lshr_b64 v[2:3], v[2:3], 16
; SI-NEXT:    v_mul_f32_e64 v3, 1.0, s47
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v3
; SI-NEXT:    v_mul_f32_e64 v3, 1.0, s43
; SI-NEXT:    v_lshr_b64 v[3:4], v[3:4], 16
; SI-NEXT:    v_mul_f32_e64 v4, 1.0, s60
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v4
; SI-NEXT:    v_mul_f32_e64 v4, 1.0, s46
; SI-NEXT:    v_lshr_b64 v[4:5], v[4:5], 16
; SI-NEXT:    v_mul_f32_e64 v5, 1.0, s74
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v5
; SI-NEXT:    v_mul_f32_e64 v5, 1.0, s59
; SI-NEXT:    v_lshr_b64 v[5:6], v[5:6], 16
; SI-NEXT:    v_mul_f32_e64 v6, 1.0, s76
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v6
; SI-NEXT:    v_mul_f32_e64 v6, 1.0, s62
; SI-NEXT:    v_lshr_b64 v[6:7], v[6:7], 16
; SI-NEXT:    v_mul_f32_e64 v7, 1.0, s79
; SI-NEXT:    v_lshrrev_b32_e32 v8, 16, v7
; SI-NEXT:    v_mul_f32_e64 v7, 1.0, s75
; SI-NEXT:    v_lshr_b64 v[7:8], v[7:8], 16
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB111_4:
; SI-NEXT:    ; implicit-def: $sgpr8
; SI-NEXT:    ; implicit-def: $sgpr12
; SI-NEXT:    ; implicit-def: $sgpr11
; SI-NEXT:    ; implicit-def: $sgpr15
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr44
; SI-NEXT:    ; implicit-def: $sgpr43
; SI-NEXT:    ; implicit-def: $sgpr47
; SI-NEXT:    ; implicit-def: $sgpr46
; SI-NEXT:    ; implicit-def: $sgpr60
; SI-NEXT:    ; implicit-def: $sgpr59
; SI-NEXT:    ; implicit-def: $sgpr74
; SI-NEXT:    ; implicit-def: $sgpr62
; SI-NEXT:    ; implicit-def: $sgpr76
; SI-NEXT:    ; implicit-def: $sgpr75
; SI-NEXT:    ; implicit-def: $sgpr79
; SI-NEXT:    s_branch .LBB111_2
;
; VI-LABEL: bitcast_v32i8_to_v16bf16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_readfirstlane_b32 s4, v18
; VI-NEXT:    v_readfirstlane_b32 s46, v17
; VI-NEXT:    v_readfirstlane_b32 s47, v16
; VI-NEXT:    v_readfirstlane_b32 s43, v15
; VI-NEXT:    v_readfirstlane_b32 s45, v14
; VI-NEXT:    v_readfirstlane_b32 s41, v13
; VI-NEXT:    v_readfirstlane_b32 s44, v12
; VI-NEXT:    v_readfirstlane_b32 s15, v11
; VI-NEXT:    v_readfirstlane_b32 s42, v10
; VI-NEXT:    v_readfirstlane_b32 s13, v9
; VI-NEXT:    v_readfirstlane_b32 s40, v8
; VI-NEXT:    v_readfirstlane_b32 s11, v7
; VI-NEXT:    v_readfirstlane_b32 s14, v6
; VI-NEXT:    v_readfirstlane_b32 s8, v5
; VI-NEXT:    v_readfirstlane_b32 s12, v4
; VI-NEXT:    v_readfirstlane_b32 s7, v3
; VI-NEXT:    v_readfirstlane_b32 s9, v2
; VI-NEXT:    v_readfirstlane_b32 s6, v1
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    v_readfirstlane_b32 s10, v0
; VI-NEXT:    s_cbranch_scc0 .LBB111_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_mov_b32_e32 v7, 0xc0c0004
; VI-NEXT:    v_mov_b32_e32 v1, s19
; VI-NEXT:    v_mov_b32_e32 v0, s17
; VI-NEXT:    v_perm_b32 v1, s18, v1, v7
; VI-NEXT:    v_perm_b32 v0, s16, v0, v7
; VI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; VI-NEXT:    v_mov_b32_e32 v2, s23
; VI-NEXT:    v_or_b32_e32 v0, v0, v1
; VI-NEXT:    v_mov_b32_e32 v1, s21
; VI-NEXT:    v_perm_b32 v2, s22, v2, v7
; VI-NEXT:    v_perm_b32 v1, s20, v1, v7
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; VI-NEXT:    v_mov_b32_e32 v3, s27
; VI-NEXT:    v_or_b32_e32 v1, v1, v2
; VI-NEXT:    v_mov_b32_e32 v2, s25
; VI-NEXT:    v_perm_b32 v3, s26, v3, v7
; VI-NEXT:    v_perm_b32 v2, s24, v2, v7
; VI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; VI-NEXT:    v_mov_b32_e32 v4, s6
; VI-NEXT:    v_or_b32_e32 v2, v2, v3
; VI-NEXT:    v_mov_b32_e32 v3, s29
; VI-NEXT:    v_perm_b32 v4, s10, v4, v7
; VI-NEXT:    v_perm_b32 v3, s28, v3, v7
; VI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; VI-NEXT:    v_mov_b32_e32 v5, s8
; VI-NEXT:    v_or_b32_e32 v3, v3, v4
; VI-NEXT:    v_mov_b32_e32 v4, s7
; VI-NEXT:    v_perm_b32 v5, s12, v5, v7
; VI-NEXT:    v_perm_b32 v4, s9, v4, v7
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; VI-NEXT:    v_mov_b32_e32 v6, s13
; VI-NEXT:    v_or_b32_e32 v4, v4, v5
; VI-NEXT:    v_mov_b32_e32 v5, s11
; VI-NEXT:    v_perm_b32 v6, s40, v6, v7
; VI-NEXT:    v_perm_b32 v5, s14, v5, v7
; VI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; VI-NEXT:    v_mov_b32_e32 v8, s41
; VI-NEXT:    v_or_b32_e32 v5, v5, v6
; VI-NEXT:    v_mov_b32_e32 v6, s15
; VI-NEXT:    v_perm_b32 v8, s44, v8, v7
; VI-NEXT:    v_perm_b32 v6, s42, v6, v7
; VI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; VI-NEXT:    v_or_b32_e32 v6, v6, v8
; VI-NEXT:    v_mov_b32_e32 v8, s43
; VI-NEXT:    v_mov_b32_e32 v9, s46
; VI-NEXT:    v_perm_b32 v8, s45, v8, v7
; VI-NEXT:    v_perm_b32 v7, s47, v9, v7
; VI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; VI-NEXT:    v_or_b32_e32 v7, v8, v7
; VI-NEXT:    s_cbranch_execnz .LBB111_3
; VI-NEXT:  .LBB111_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s47, s47, 3
; VI-NEXT:    v_mov_b32_e32 v0, s46
; VI-NEXT:    v_mov_b32_e32 v1, 0xc0c0004
; VI-NEXT:    v_perm_b32 v2, s47, v0, v1
; VI-NEXT:    s_add_i32 s45, s45, 3
; VI-NEXT:    v_mov_b32_e32 v0, s43
; VI-NEXT:    v_perm_b32 v3, s45, v0, v1
; VI-NEXT:    s_add_i32 s44, s44, 3
; VI-NEXT:    v_mov_b32_e32 v0, s41
; VI-NEXT:    v_perm_b32 v4, s44, v0, v1
; VI-NEXT:    s_add_i32 s42, s42, 3
; VI-NEXT:    v_mov_b32_e32 v0, s15
; VI-NEXT:    v_perm_b32 v5, s42, v0, v1
; VI-NEXT:    s_add_i32 s40, s40, 3
; VI-NEXT:    v_mov_b32_e32 v0, s13
; VI-NEXT:    v_perm_b32 v6, s40, v0, v1
; VI-NEXT:    s_add_i32 s14, s14, 3
; VI-NEXT:    v_mov_b32_e32 v0, s11
; VI-NEXT:    v_perm_b32 v7, s14, v0, v1
; VI-NEXT:    s_add_i32 s12, s12, 3
; VI-NEXT:    v_mov_b32_e32 v0, s8
; VI-NEXT:    v_perm_b32 v8, s12, v0, v1
; VI-NEXT:    s_add_i32 s9, s9, 3
; VI-NEXT:    v_mov_b32_e32 v0, s7
; VI-NEXT:    v_perm_b32 v9, s9, v0, v1
; VI-NEXT:    s_add_i32 s10, s10, 3
; VI-NEXT:    v_mov_b32_e32 v0, s6
; VI-NEXT:    v_perm_b32 v10, s10, v0, v1
; VI-NEXT:    s_add_i32 s28, s28, 3
; VI-NEXT:    v_mov_b32_e32 v0, s29
; VI-NEXT:    v_perm_b32 v11, s28, v0, v1
; VI-NEXT:    s_add_i32 s26, s26, 3
; VI-NEXT:    v_mov_b32_e32 v0, s27
; VI-NEXT:    v_perm_b32 v12, s26, v0, v1
; VI-NEXT:    s_add_i32 s24, s24, 3
; VI-NEXT:    v_mov_b32_e32 v0, s25
; VI-NEXT:    v_perm_b32 v13, s24, v0, v1
; VI-NEXT:    s_add_i32 s22, s22, 3
; VI-NEXT:    v_mov_b32_e32 v0, s23
; VI-NEXT:    s_add_i32 s20, s20, 3
; VI-NEXT:    v_mov_b32_e32 v14, s21
; VI-NEXT:    s_add_i32 s18, s18, 3
; VI-NEXT:    v_mov_b32_e32 v15, s19
; VI-NEXT:    s_add_i32 s16, s16, 3
; VI-NEXT:    v_mov_b32_e32 v16, s17
; VI-NEXT:    v_perm_b32 v0, s22, v0, v1
; VI-NEXT:    v_perm_b32 v14, s20, v14, v1
; VI-NEXT:    v_perm_b32 v15, s18, v15, v1
; VI-NEXT:    v_perm_b32 v1, s16, v16, v1
; VI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; VI-NEXT:    v_add_u32_e32 v14, vcc, 0x300, v14
; VI-NEXT:    v_lshlrev_b32_e32 v15, 16, v15
; VI-NEXT:    v_add_u32_e32 v1, vcc, 0x300, v1
; VI-NEXT:    v_or_b32_sdwa v1, v15, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_or_b32_sdwa v14, v0, v14 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_add_u32_e32 v0, vcc, 0x3000000, v1
; VI-NEXT:    v_add_u32_e32 v1, vcc, 0x3000000, v14
; VI-NEXT:    v_lshlrev_b32_e32 v14, 16, v2
; VI-NEXT:    v_add_u32_e32 v15, vcc, 0x300, v3
; VI-NEXT:    v_lshlrev_b32_e32 v16, 16, v4
; VI-NEXT:    v_add_u32_e32 v17, vcc, 0x300, v5
; VI-NEXT:    v_lshlrev_b32_e32 v5, 16, v6
; VI-NEXT:    v_add_u32_e32 v6, vcc, 0x300, v7
; VI-NEXT:    v_lshlrev_b32_e32 v4, 16, v8
; VI-NEXT:    v_add_u32_e32 v7, vcc, 0x300, v9
; VI-NEXT:    v_lshlrev_b32_e32 v3, 16, v10
; VI-NEXT:    v_add_u32_e32 v8, vcc, 0x300, v11
; VI-NEXT:    v_lshlrev_b32_e32 v2, 16, v12
; VI-NEXT:    v_add_u32_e32 v9, vcc, 0x300, v13
; VI-NEXT:    v_or_b32_sdwa v2, v2, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_or_b32_sdwa v3, v3, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_or_b32_sdwa v4, v4, v7 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_or_b32_sdwa v5, v5, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_or_b32_sdwa v6, v16, v17 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_or_b32_sdwa v7, v14, v15 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_0
; VI-NEXT:    v_add_u32_e32 v2, vcc, 0x3000000, v2
; VI-NEXT:    v_add_u32_e32 v3, vcc, 0x3000000, v3
; VI-NEXT:    v_add_u32_e32 v4, vcc, 0x3000000, v4
; VI-NEXT:    v_add_u32_e32 v5, vcc, 0x3000000, v5
; VI-NEXT:    v_add_u32_e32 v6, vcc, 0x3000000, v6
; VI-NEXT:    v_add_u32_e32 v7, vcc, 0x3000000, v7
; VI-NEXT:  .LBB111_3: ; %end
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB111_4:
; VI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; VI-NEXT:    s_branch .LBB111_2
;
; GFX9-LABEL: bitcast_v32i8_to_v16bf16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_readfirstlane_b32 s4, v18
; GFX9-NEXT:    v_readfirstlane_b32 s41, v17
; GFX9-NEXT:    v_readfirstlane_b32 s43, v16
; GFX9-NEXT:    v_readfirstlane_b32 s46, v15
; GFX9-NEXT:    v_readfirstlane_b32 s47, v14
; GFX9-NEXT:    v_readfirstlane_b32 s13, v13
; GFX9-NEXT:    v_readfirstlane_b32 s15, v12
; GFX9-NEXT:    v_readfirstlane_b32 s44, v11
; GFX9-NEXT:    v_readfirstlane_b32 s45, v10
; GFX9-NEXT:    v_readfirstlane_b32 s10, v9
; GFX9-NEXT:    v_readfirstlane_b32 s11, v8
; GFX9-NEXT:    v_readfirstlane_b32 s40, v7
; GFX9-NEXT:    v_readfirstlane_b32 s42, v6
; GFX9-NEXT:    v_readfirstlane_b32 s7, v5
; GFX9-NEXT:    v_readfirstlane_b32 s9, v4
; GFX9-NEXT:    v_readfirstlane_b32 s12, v3
; GFX9-NEXT:    v_readfirstlane_b32 s14, v2
; GFX9-NEXT:    v_readfirstlane_b32 s6, v1
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    v_readfirstlane_b32 s8, v0
; GFX9-NEXT:    s_cbranch_scc0 .LBB111_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    v_mov_b32_e32 v0, s17
; GFX9-NEXT:    v_mov_b32_e32 v4, 0xc0c0004
; GFX9-NEXT:    v_perm_b32 v0, s16, v0, v4
; GFX9-NEXT:    v_mov_b32_e32 v1, s19
; GFX9-NEXT:    v_perm_b32 v1, s18, v1, v4
; GFX9-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX9-NEXT:    v_lshl_or_b32 v0, v1, 16, v0
; GFX9-NEXT:    v_mov_b32_e32 v1, s21
; GFX9-NEXT:    v_perm_b32 v1, s20, v1, v4
; GFX9-NEXT:    v_mov_b32_e32 v2, s23
; GFX9-NEXT:    v_perm_b32 v2, s22, v2, v4
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; GFX9-NEXT:    v_lshl_or_b32 v1, v2, 16, v1
; GFX9-NEXT:    v_mov_b32_e32 v2, s25
; GFX9-NEXT:    v_perm_b32 v2, s24, v2, v4
; GFX9-NEXT:    v_mov_b32_e32 v3, s27
; GFX9-NEXT:    v_perm_b32 v3, s26, v3, v4
; GFX9-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX9-NEXT:    v_lshl_or_b32 v2, v3, 16, v2
; GFX9-NEXT:    v_mov_b32_e32 v3, s29
; GFX9-NEXT:    v_perm_b32 v3, s28, v3, v4
; GFX9-NEXT:    v_mov_b32_e32 v5, s6
; GFX9-NEXT:    s_and_b32 s4, s14, 0xff
; GFX9-NEXT:    s_lshl_b32 s5, s12, 8
; GFX9-NEXT:    v_perm_b32 v5, s8, v5, v4
; GFX9-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GFX9-NEXT:    s_or_b32 s4, s4, s5
; GFX9-NEXT:    s_and_b32 s5, s9, 0xff
; GFX9-NEXT:    s_lshl_b32 s56, s7, 8
; GFX9-NEXT:    v_lshl_or_b32 v3, v5, 16, v3
; GFX9-NEXT:    s_or_b32 s5, s5, s56
; GFX9-NEXT:    v_mov_b32_e32 v5, s40
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s4, s5
; GFX9-NEXT:    v_perm_b32 v5, s42, v5, v4
; GFX9-NEXT:    s_and_b32 s5, s11, 0xff
; GFX9-NEXT:    s_lshl_b32 s56, s10, 8
; GFX9-NEXT:    s_or_b32 s5, s5, s56
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX9-NEXT:    v_lshl_or_b32 v5, s5, 16, v5
; GFX9-NEXT:    s_and_b32 s5, s45, 0xff
; GFX9-NEXT:    s_lshl_b32 s56, s44, 8
; GFX9-NEXT:    s_or_b32 s5, s5, s56
; GFX9-NEXT:    s_and_b32 s56, s15, 0xff
; GFX9-NEXT:    s_lshl_b32 s57, s13, 8
; GFX9-NEXT:    s_or_b32 s56, s56, s57
; GFX9-NEXT:    v_mov_b32_e32 v6, s46
; GFX9-NEXT:    s_pack_ll_b32_b16 s5, s5, s56
; GFX9-NEXT:    v_perm_b32 v4, s47, v6, v4
; GFX9-NEXT:    s_and_b32 s56, s43, 0xff
; GFX9-NEXT:    s_lshl_b32 s57, s41, 8
; GFX9-NEXT:    s_or_b32 s56, s56, s57
; GFX9-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX9-NEXT:    v_lshl_or_b32 v7, s56, 16, v4
; GFX9-NEXT:    v_mov_b32_e32 v4, s4
; GFX9-NEXT:    v_mov_b32_e32 v6, s5
; GFX9-NEXT:    s_cbranch_execnz .LBB111_3
; GFX9-NEXT:  .LBB111_2: ; %cmp.true
; GFX9-NEXT:    s_add_i32 s47, s47, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s46
; GFX9-NEXT:    v_mov_b32_e32 v2, 0xc0c0004
; GFX9-NEXT:    v_perm_b32 v3, s47, v0, v2
; GFX9-NEXT:    s_add_i32 s43, s43, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s41
; GFX9-NEXT:    v_perm_b32 v4, s43, v0, v2
; GFX9-NEXT:    s_add_i32 s45, s45, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s44
; GFX9-NEXT:    v_perm_b32 v5, s45, v0, v2
; GFX9-NEXT:    s_add_i32 s15, s15, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s13
; GFX9-NEXT:    v_perm_b32 v6, s15, v0, v2
; GFX9-NEXT:    s_add_i32 s42, s42, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s40
; GFX9-NEXT:    v_perm_b32 v7, s42, v0, v2
; GFX9-NEXT:    s_add_i32 s11, s11, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s10
; GFX9-NEXT:    v_perm_b32 v8, s11, v0, v2
; GFX9-NEXT:    s_add_i32 s14, s14, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s12
; GFX9-NEXT:    v_perm_b32 v9, s14, v0, v2
; GFX9-NEXT:    s_add_i32 s9, s9, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s7
; GFX9-NEXT:    v_perm_b32 v10, s9, v0, v2
; GFX9-NEXT:    s_add_i32 s28, s28, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s29
; GFX9-NEXT:    v_perm_b32 v11, s28, v0, v2
; GFX9-NEXT:    s_add_i32 s20, s20, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s21
; GFX9-NEXT:    v_perm_b32 v0, s20, v0, v2
; GFX9-NEXT:    v_add_u32_e32 v1, 0x300, v0
; GFX9-NEXT:    s_add_i32 s22, s22, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s23
; GFX9-NEXT:    v_perm_b32 v0, s22, v0, v2
; GFX9-NEXT:    v_add_u32_e32 v12, 0x300, v0
; GFX9-NEXT:    s_add_i32 s16, s16, 3
; GFX9-NEXT:    v_mov_b32_e32 v0, s17
; GFX9-NEXT:    v_perm_b32 v0, s16, v0, v2
; GFX9-NEXT:    s_add_i32 s18, s18, 3
; GFX9-NEXT:    v_mov_b32_e32 v13, s19
; GFX9-NEXT:    v_add_u32_e32 v0, 0x300, v0
; GFX9-NEXT:    v_perm_b32 v13, s18, v13, v2
; GFX9-NEXT:    v_add_u32_e32 v13, 0x300, v13
; GFX9-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX9-NEXT:    v_lshl_or_b32 v0, v13, 16, v0
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; GFX9-NEXT:    s_add_i32 s24, s24, 3
; GFX9-NEXT:    v_mov_b32_e32 v13, s25
; GFX9-NEXT:    v_add_u32_e32 v16, 0x300, v5
; GFX9-NEXT:    v_add_u32_e32 v5, 0x300, v7
; GFX9-NEXT:    s_add_i32 s8, s8, 3
; GFX9-NEXT:    v_lshl_or_b32 v1, v12, 16, v1
; GFX9-NEXT:    v_mov_b32_e32 v12, s6
; GFX9-NEXT:    v_perm_b32 v13, s24, v13, v2
; GFX9-NEXT:    s_add_i32 s26, s26, 3
; GFX9-NEXT:    v_mov_b32_e32 v14, s27
; GFX9-NEXT:    v_add_u32_e32 v7, 0x300, v8
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX9-NEXT:    v_perm_b32 v12, s8, v12, v2
; GFX9-NEXT:    v_perm_b32 v2, s26, v14, v2
; GFX9-NEXT:    v_add_u32_e32 v14, 0x300, v3
; GFX9-NEXT:    v_add_u32_e32 v15, 0x300, v4
; GFX9-NEXT:    v_add_u32_e32 v6, 0x300, v6
; GFX9-NEXT:    v_add_u32_e32 v4, 0x300, v9
; GFX9-NEXT:    v_add_u32_e32 v8, 0x300, v10
; GFX9-NEXT:    v_add_u32_e32 v3, 0x300, v11
; GFX9-NEXT:    v_add_u32_e32 v10, 0x300, v13
; GFX9-NEXT:    v_lshl_or_b32 v5, v7, 16, v5
; GFX9-NEXT:    v_and_b32_e32 v7, 0xffff, v16
; GFX9-NEXT:    v_add_u32_e32 v9, 0x300, v12
; GFX9-NEXT:    v_add_u32_e32 v2, 0x300, v2
; GFX9-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; GFX9-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GFX9-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX9-NEXT:    v_lshl_or_b32 v6, v6, 16, v7
; GFX9-NEXT:    v_and_b32_e32 v7, 0xffff, v14
; GFX9-NEXT:    v_lshl_or_b32 v2, v2, 16, v10
; GFX9-NEXT:    v_lshl_or_b32 v3, v9, 16, v3
; GFX9-NEXT:    v_lshl_or_b32 v4, v8, 16, v4
; GFX9-NEXT:    v_lshl_or_b32 v7, v15, 16, v7
; GFX9-NEXT:  .LBB111_3: ; %end
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB111_4:
; GFX9-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX9-NEXT:    s_branch .LBB111_2
;
; GFX11-TRUE16-LABEL: bitcast_v32i8_to_v16bf16_scalar:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s42, v14
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr13_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s4, v13
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr12_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s7, v12
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr11_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s5, v11
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr10_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s8, v10
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr9_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s6, v9
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr8_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s11, v8
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr7_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s10, v7
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr6_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s14, v6
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr5_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s9, v5
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr4_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s12, v4
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr3_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s40, v3
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr2_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s41, v2
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr1_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s13, v1
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr0_hi16
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s15, v0
; GFX11-TRUE16-NEXT:    s_cmp_lg_u32 s42, 0
; GFX11-TRUE16-NEXT:    s_mov_b32 s42, 0
; GFX11-TRUE16-NEXT:    s_cbranch_scc0 .LBB111_4
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v4, 0xc0c0004
; GFX11-TRUE16-NEXT:    s_and_b32 s43, s28, 0xff
; GFX11-TRUE16-NEXT:    s_lshl_b32 s44, s29, 8
; GFX11-TRUE16-NEXT:    s_and_b32 s45, s15, 0xff
; GFX11-TRUE16-NEXT:    s_lshl_b32 s46, s13, 8
; GFX11-TRUE16-NEXT:    s_or_b32 s43, s43, s44
; GFX11-TRUE16-NEXT:    s_or_b32 s44, s45, s46
; GFX11-TRUE16-NEXT:    v_perm_b32 v6, s18, s19, v4
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s43, s43, s44
; GFX11-TRUE16-NEXT:    s_and_b32 s44, s12, 0xff
; GFX11-TRUE16-NEXT:    s_lshl_b32 s45, s9, 8
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, s2, s3, v4
; GFX11-TRUE16-NEXT:    s_or_b32 s44, s44, s45
; GFX11-TRUE16-NEXT:    s_and_b32 s45, s14, 0xff
; GFX11-TRUE16-NEXT:    s_lshl_b32 s46, s10, 8
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, s16, s17, v4
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v1.h, v6.l
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v6, s44
; GFX11-TRUE16-NEXT:    s_or_b32 s44, s45, s46
; GFX11-TRUE16-NEXT:    s_and_b32 s45, s7, 0xff
; GFX11-TRUE16-NEXT:    s_lshl_b32 s46, s4, 8
; GFX11-TRUE16-NEXT:    v_perm_b32 v0, s0, s1, v4
; GFX11-TRUE16-NEXT:    s_or_b32 s45, s45, s46
; GFX11-TRUE16-NEXT:    v_perm_b32 v7, s22, s23, v4
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.h, v5.l
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, s26, s27, v4
; GFX11-TRUE16-NEXT:    s_and_b32 s47, s11, 0xff
; GFX11-TRUE16-NEXT:    s_lshl_b32 s46, s6, 8
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v8, s45
; GFX11-TRUE16-NEXT:    s_or_b32 s45, s47, s46
; GFX11-TRUE16-NEXT:    v_perm_b32 v2, s20, s21, v4
; GFX11-TRUE16-NEXT:    v_perm_b32 v3, s24, s25, v4
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s44, s44, s45
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.h, v7.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v3.h, v5.l
; GFX11-TRUE16-NEXT:    v_perm_b32 v5, s41, s40, v4
; GFX11-TRUE16-NEXT:    v_perm_b32 v7, s8, s5, v4
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v5.h, v6.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v7.h, v8.l
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v4, s43
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v6, s44
; GFX11-TRUE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s42
; GFX11-TRUE16-NEXT:    s_cbranch_vccnz .LBB111_3
; GFX11-TRUE16-NEXT:  .LBB111_2: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_mov_b32_e32 v0, 0xc0c0004
; GFX11-TRUE16-NEXT:    s_add_i32 s8, s8, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s41, s41, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s7, s7, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s11, s11, 3
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, s8, s5, v0
; GFX11-TRUE16-NEXT:    s_add_i32 s28, s28, 3
; GFX11-TRUE16-NEXT:    v_perm_b32 v2, s7, s4, v0
; GFX11-TRUE16-NEXT:    v_perm_b32 v4, s11, s6, v0
; GFX11-TRUE16-NEXT:    s_add_i32 s15, s15, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v7, 0x300, v1
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, s41, s40, v0
; GFX11-TRUE16-NEXT:    s_add_i32 s20, s20, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v9, 0x300, v2
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v10, 0x300, v4
; GFX11-TRUE16-NEXT:    v_perm_b32 v2, s15, s13, v0
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v5, 0x300, v1
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, s28, s29, v0
; GFX11-TRUE16-NEXT:    s_add_i32 s14, s14, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s12, s12, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s26, s26, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s22, s22, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v4, 0x300, v1
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, s20, s21, v0
; GFX11-TRUE16-NEXT:    s_add_i32 s2, s2, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s18, s18, 3
; GFX11-TRUE16-NEXT:    v_perm_b32 v3, s14, s10, v0
; GFX11-TRUE16-NEXT:    v_perm_b32 v8, s12, s9, v0
; GFX11-TRUE16-NEXT:    v_perm_b32 v11, s26, s27, v0
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v12, 0x300, v2
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, 0x300, v1
; GFX11-TRUE16-NEXT:    v_perm_b32 v1, s22, s23, v0
; GFX11-TRUE16-NEXT:    v_perm_b32 v13, s2, s3, v0
; GFX11-TRUE16-NEXT:    v_perm_b32 v14, s18, s19, v0
; GFX11-TRUE16-NEXT:    s_add_i32 s24, s24, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s16, s16, 3
; GFX11-TRUE16-NEXT:    s_add_i32 s0, s0, 3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, 0x300, v3
; GFX11-TRUE16-NEXT:    v_perm_b32 v3, s24, s25, v0
; GFX11-TRUE16-NEXT:    v_perm_b32 v15, s16, s17, v0
; GFX11-TRUE16-NEXT:    v_perm_b32 v0, s0, s1, v0
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v8, 0x300, v8
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v11, 0x300, v11
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v13, 0x300, v13
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v14, 0x300, v14
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v16, 0x300, v1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 0x300, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, 0x300, v15
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v0, 0x300, v0
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.h, v13.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v1.h, v14.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.h, v16.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v3.h, v11.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v4.h, v12.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v5.h, v8.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v6.h, v10.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v7.h, v9.l
; GFX11-TRUE16-NEXT:  .LBB111_3: ; %end
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB111_4:
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-TRUE16-NEXT:    s_branch .LBB111_2
;
; GFX11-FAKE16-LABEL: bitcast_v32i8_to_v16bf16_scalar:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s42, v14
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s10, v13
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s14, v12
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s12, v11
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s41, v10
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s6, v9
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s11, v8
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s13, v7
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s40, v6
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s4, v5
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s7, v4
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s8, v3
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s15, v2
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s5, v1
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s9, v0
; GFX11-FAKE16-NEXT:    s_cmp_lg_u32 s42, 0
; GFX11-FAKE16-NEXT:    s_mov_b32 s42, 0
; GFX11-FAKE16-NEXT:    s_cbranch_scc0 .LBB111_4
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v4, 0xc0c0004
; GFX11-FAKE16-NEXT:    s_and_b32 s43, s28, 0xff
; GFX11-FAKE16-NEXT:    s_lshl_b32 s44, s29, 8
; GFX11-FAKE16-NEXT:    s_lshl_b32 s45, s5, 8
; GFX11-FAKE16-NEXT:    s_or_b32 s43, s43, s44
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, s0, s1, v4
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, s16, s17, v4
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, s20, s21, v4
; GFX11-FAKE16-NEXT:    s_and_b32 s44, s9, 0xff
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, s2, s3, v4
; GFX11-FAKE16-NEXT:    s_or_b32 s44, s44, s45
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, s18, s19, v4
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, s22, s23, v4
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s43, s43, s44
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX11-FAKE16-NEXT:    s_and_b32 s46, s7, 0xff
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v0, v1, 16, v0
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v1, v3, 16, v2
; GFX11-FAKE16-NEXT:    s_lshl_b32 s47, s4, 8
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v2, v6, 16, v5
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, s15, s8, v4
; GFX11-FAKE16-NEXT:    s_or_b32 s45, s46, s47
; GFX11-FAKE16-NEXT:    s_and_b32 s44, s40, 0xff
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, s24, s25, v4
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, s26, s27, v4
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, s41, s12, v4
; GFX11-FAKE16-NEXT:    s_lshl_b32 s46, s6, 8
; GFX11-FAKE16-NEXT:    s_and_b32 s47, s14, 0xff
; GFX11-FAKE16-NEXT:    s_lshl_b32 s56, s10, 8
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v5, s45, 16, v5
; GFX11-FAKE16-NEXT:    s_lshl_b32 s45, s13, 8
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX11-FAKE16-NEXT:    s_or_b32 s44, s44, s45
; GFX11-FAKE16-NEXT:    s_and_b32 s45, s11, 0xff
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(SKIP_2) | instid1(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_or_b32 s45, s45, s46
; GFX11-FAKE16-NEXT:    s_or_b32 s46, s47, s56
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s44, s44, s45
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v6, s44 :: v_dual_and_b32 v7, 0xffff, v7
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v3, v8, 16, v7
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v7, s46, 16, v4
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v4, s43
; GFX11-FAKE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s42
; GFX11-FAKE16-NEXT:    s_cbranch_vccnz .LBB111_3
; GFX11-FAKE16-NEXT:  .LBB111_2: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_mov_b32_e32 v0, 0xc0c0004
; GFX11-FAKE16-NEXT:    s_add_i32 s41, s41, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s14, s14, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s11, s11, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s15, s15, 3
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, s41, s12, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, s14, s10, v0
; GFX11-FAKE16-NEXT:    s_add_i32 s20, s20, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s16, s16, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s0, s0, 3
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, 0x300, v1
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, s11, s6, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v7, 0x300, v2
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, s15, s8, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, s16, s17, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v14, s0, s1, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v9, 0x300, v1
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, s20, s21, v0
; GFX11-FAKE16-NEXT:    s_add_i32 s40, s40, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s7, s7, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s28, s28, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s9, s9, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s24, s24, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s26, s26, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s22, s22, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s18, s18, 3
; GFX11-FAKE16-NEXT:    s_add_i32 s2, s2, 3
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, s40, s13, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, s7, s4, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, s28, s29, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, s9, s5, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v10, 0x300, v2
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, s24, s25, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, s26, s27, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v1, 0x300, v1
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, s22, s23, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v15, s18, s19, v0
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, s2, s3, v0
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v14, 0x300, v14
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v13, 0x300, v13
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, 0x300, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v6, 0x300, v6
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v12, 0x300, v12
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v15, 0x300, v15
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v0, 0x300, v0
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v16, 0xffff, v1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v17, 0x300, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v5, 0x300, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v8, 0x300, v8
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v11, 0x300, v11
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v0, v0, 16, v14
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v1, v15, 16, v13
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v2, v12, 16, v16
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v12, 0xffff, v17
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v13, 0xffff, v3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v14, 0xffff, v4
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v3, v11, 16, v12
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v4, v8, 16, v6
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v5, v5, 16, v10
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v6, v9, 16, v13
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v7, v7, 16, v14
; GFX11-FAKE16-NEXT:  .LBB111_3: ; %end
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB111_4:
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7
; GFX11-FAKE16-NEXT:    s_branch .LBB111_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <32 x i8> %a, splat (i8 3)
  %a2 = bitcast <32 x i8> %a1 to <16 x bfloat>
  br label %end

cmp.false:
  %a3 = bitcast <32 x i8> %a to <16 x bfloat>
  br label %end

end:
  %phi = phi <16 x bfloat> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <16 x bfloat> %phi
}

attributes #0 = { nounwind }
