; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -mtriple=amdgcn-amd-amdhsa -passes=amdgpu-simplifylib %s | FileCheck %s

define float @test_tdo_scalar_f32_exp2() {
; CHECK-LABEL: define float @test_tdo_scalar_f32_exp2() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret float 1.000000e+00
;
entry:
  %c = call float @_Z4exp2f(float 0.000000e+00)
  ret float %c
}

define <3 x float> @test_tdo_v2_f32_exp2() {
; CHECK-LABEL: define <3 x float> @test_tdo_v2_f32_exp2() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret <3 x float> <float 1.000000e+00, float 1.000000e+00, float 2.000000e+00>
;
entry:
  %c = call <3 x float> @_Z4exp2Dv3_f(<3 x float> <float 0.000000e+00, float -0.000000e+00, float 1.000000e+00>)
  ret <3 x float> %c
}

define half @test_tdo_scalar_f16_exp2() {
; CHECK-LABEL: define half @test_tdo_scalar_f16_exp2() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret half 0xH3C00
;
entry:
  %c = call half @_Z4exp2Dh(half 0.000000e+00)
  ret half %c
}

define <3 x half> @test_tdo_v2_f16_exp2() {
; CHECK-LABEL: define <3 x half> @test_tdo_v2_f16_exp2() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret <3 x half> <half 0xH3C00, half 0xH3C00, half 0xH4000>
;
entry:
  %c = call <3 x half> @_Z4exp2Dv3_Dh(<3 x half> <half 0.000000e+00, half -0.000000e+00, half 1.000000e+00>)
  ret <3 x half> %c
}

define double @test_tdo_scalar_f64_exp2() {
; CHECK-LABEL: define double @test_tdo_scalar_f64_exp2() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret double 1.000000e+00
;
entry:
  %c = call double @_Z4exp2d(double 0.000000e+00)
  ret double %c
}

define <3 x double> @test_tdo_v2_f64_exp2() {
; CHECK-LABEL: define <3 x double> @test_tdo_v2_f64_exp2() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret <3 x double> <double 1.000000e+00, double 1.000000e+00, double 2.000000e+00>
;
entry:
  %c = call <3 x double> @_Z4exp2Dv3_d(<3 x double> <double 0.000000e+00, double -0.000000e+00, double 1.000000e+00>)
  ret <3 x double> %c
}

declare float        @_Z4exp2f(float)
declare <3 x float>  @_Z4exp2Dv3_f(<3 x float>)
declare half         @_Z4exp2Dh(half)
declare <3 x half>   @_Z4exp2Dv3_Dh(<3 x half>)
declare double       @_Z4exp2d(double)
declare <3 x double> @_Z4exp2Dv3_d(<3 x double>)
