; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; REQUIRES: amdgpu-registered-target

; Predicate guarding a builtin with no required target features
; (e.g. `__builtin_amdgcn_is_invocable(__builtin_amdgcn_fence)`) is
; encoded as a global named `llvm.amdgcn.has.` with an empty feature suffix.

; RUN: opt -S -mtriple=amdgcn-amd-amdhsa -mcpu=gfx906 -passes='amdgpu-expand-feature-predicates' %s -o - | FileCheck --check-prefix=GFX906 %s
; RUN: opt -S -mtriple=amdgcn-amd-amdhsa -mcpu=gfx950 -passes='amdgpu-expand-feature-predicates' %s -o - | FileCheck --check-prefix=GFX950 %s
; RUN: opt -S -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1250 -passes='amdgpu-expand-feature-predicates' %s -o - | FileCheck --check-prefix=GFX1250 %s

@llvm.amdgcn.has. = external addrspace(1) externally_initialized constant i1
@llvm.amdgcn.has.gfx1250-insts = external addrspace(1) externally_initialized constant i1

declare void @llvm.amdgcn.s.wait.asynccnt(i16 immarg)

define amdgpu_kernel void @always_invocable(ptr addrspace(1) %p) {
; GFX906-LABEL: define amdgpu_kernel void @always_invocable(
; GFX906-SAME: ptr addrspace(1) [[P:%.*]]) #[[ATTR1:[0-9]+]] {
; GFX906-NEXT:  [[ENTRY:.*:]]
; GFX906-NEXT:    br label %[[THEN:.*]]
; GFX906:       [[THEN]]:
; GFX906-NEXT:    store i32 1, ptr addrspace(1) [[P]], align 4
; GFX906-NEXT:    br label %[[SKIP:.*]]
; GFX906:       [[SKIP]]:
; GFX906-NEXT:    ret void
;
; GFX950-LABEL: define amdgpu_kernel void @always_invocable(
; GFX950-SAME: ptr addrspace(1) [[P:%.*]]) #[[ATTR1:[0-9]+]] {
; GFX950-NEXT:  [[ENTRY:.*:]]
; GFX950-NEXT:    br label %[[THEN:.*]]
; GFX950:       [[THEN]]:
; GFX950-NEXT:    store i32 1, ptr addrspace(1) [[P]], align 4
; GFX950-NEXT:    br label %[[SKIP:.*]]
; GFX950:       [[SKIP]]:
; GFX950-NEXT:    ret void
;
; GFX1250-LABEL: define amdgpu_kernel void @always_invocable(
; GFX1250-SAME: ptr addrspace(1) [[P:%.*]]) #[[ATTR1:[0-9]+]] {
; GFX1250-NEXT:  [[ENTRY:.*:]]
; GFX1250-NEXT:    br label %[[THEN:.*]]
; GFX1250:       [[THEN]]:
; GFX1250-NEXT:    store i32 1, ptr addrspace(1) [[P]], align 4
; GFX1250-NEXT:    br label %[[SKIP:.*]]
; GFX1250:       [[SKIP]]:
; GFX1250-NEXT:    ret void
;
entry:
  %has.empty = load i1, ptr addrspace(1) @llvm.amdgcn.has., align 1
  br i1 %has.empty, label %then, label %skip

then:
  store i32 1, ptr addrspace(1) %p, align 4
  br label %skip

skip:
  ret void
}

define amdgpu_kernel void @gated_asynccnt(ptr addrspace(1) %p) {
; GFX906-LABEL: define amdgpu_kernel void @gated_asynccnt(
; GFX906-SAME: ptr addrspace(1) [[P:%.*]]) #[[ATTR1]] {
; GFX906-NEXT:  [[ENTRY:.*:]]
; GFX906-NEXT:    br label %[[SKIP:.*]]
; GFX906:       [[SKIP]]:
; GFX906-NEXT:    store i32 2, ptr addrspace(1) [[P]], align 4
; GFX906-NEXT:    ret void
;
; GFX950-LABEL: define amdgpu_kernel void @gated_asynccnt(
; GFX950-SAME: ptr addrspace(1) [[P:%.*]]) #[[ATTR1]] {
; GFX950-NEXT:  [[ENTRY:.*:]]
; GFX950-NEXT:    br label %[[SKIP:.*]]
; GFX950:       [[SKIP]]:
; GFX950-NEXT:    store i32 2, ptr addrspace(1) [[P]], align 4
; GFX950-NEXT:    ret void
;
; GFX1250-LABEL: define amdgpu_kernel void @gated_asynccnt(
; GFX1250-SAME: ptr addrspace(1) [[P:%.*]]) #[[ATTR1]] {
; GFX1250-NEXT:  [[ENTRY:.*:]]
; GFX1250-NEXT:    br label %[[WAIT:.*]]
; GFX1250:       [[WAIT]]:
; GFX1250-NEXT:    call void @llvm.amdgcn.s.wait.asynccnt(i16 0)
; GFX1250-NEXT:    br label %[[SKIP:.*]]
; GFX1250:       [[SKIP]]:
; GFX1250-NEXT:    store i32 2, ptr addrspace(1) [[P]], align 4
; GFX1250-NEXT:    ret void
;
entry:
  %has.gfx1250 = load i1, ptr addrspace(1) @llvm.amdgcn.has.gfx1250-insts, align 1
  br i1 %has.gfx1250, label %wait, label %skip

wait:
  call void @llvm.amdgcn.s.wait.asynccnt(i16 0)
  br label %skip

skip:
  store i32 2, ptr addrspace(1) %p, align 4
  ret void
}
