; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -amdgpu-vector-idiom-enable -mtriple=amdgcn-amd-amdhsa -passes=amdgpu-vector-idiom -S %s | FileCheck %s
;
; Realistic testcase for accumulator vectorization based on the actual pattern
; found in the real-world code. This mimics the accumulator structure and access
; pattern that should be vectorized to reduce VGPR usage.
;
; Enhancement planned: accumulator vectorization for real-world patterns

%struct.HIP_vector_base = type { float, float, float, float }
%struct.HIP_vector_type = type { %struct.HIP_vector_base }
%"struct.fbgemm_gpu::float8" = type { [2 x %struct.HIP_vector_type] }
%"struct.fbgemm_gpu::VecNT" = type { %"struct.fbgemm_gpu::float8" }

declare void @llvm.lifetime.start.p5(i64, ptr addrspace(5) nocapture)
declare void @llvm.lifetime.end.p5(i64, ptr addrspace(5) nocapture)

; -----------------------------------------------------------------------------
; Realistic accumulator pattern: access individual float elements with byte offsets
; This matches the pattern found in the real code where accumulators are accessed
; as individual float values with getelementptr byte offsets.
; Expect: combine into <4 x float> vector operations
;
define amdgpu_kernel void @realistic_accumulator_pattern(i32 %idx) {
; CHECK-LABEL: define amdgpu_kernel void @realistic_accumulator_pattern(
; CHECK-SAME: i32 [[IDX:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ACCUMULATORS:%.*]] = alloca [4 x [1 x %"struct.fbgemm_gpu::VecNT"]], align 32, addrspace(5)
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [4 x [1 x %"struct.fbgemm_gpu::VecNT"]], ptr addrspace(5) [[ACCUMULATORS]], i32 0, i32 [[IDX]], i32 0
; CHECK-NEXT:    [[TMP0:%.*]] = load <4 x float>, ptr addrspace(5) [[ARRAYIDX]], align 32
; CHECK-NEXT:    [[TMP1:%.*]] = extractelement <4 x float> [[TMP0]], i32 3
; CHECK-NEXT:    [[TMP2:%.*]] = extractelement <4 x float> [[TMP0]], i32 2
; CHECK-NEXT:    [[TMP3:%.*]] = extractelement <4 x float> [[TMP0]], i32 1
; CHECK-NEXT:    [[TMP4:%.*]] = extractelement <4 x float> [[TMP0]], i32 0
; CHECK-NEXT:    [[GEP4:%.*]] = getelementptr inbounds i8, ptr addrspace(5) [[ARRAYIDX]], i64 4
; CHECK-NEXT:    [[GEP8:%.*]] = getelementptr inbounds i8, ptr addrspace(5) [[ARRAYIDX]], i64 8
; CHECK-NEXT:    [[GEP12:%.*]] = getelementptr inbounds i8, ptr addrspace(5) [[ARRAYIDX]], i64 12
; CHECK-NEXT:    [[GEP16:%.*]] = getelementptr inbounds i8, ptr addrspace(5) [[ARRAYIDX]], i64 16
; CHECK-NEXT:    [[TMP5:%.*]] = load <4 x float>, ptr addrspace(5) [[GEP16]], align 4
; CHECK-NEXT:    [[TMP6:%.*]] = extractelement <4 x float> [[TMP5]], i32 3
; CHECK-NEXT:    [[TMP7:%.*]] = extractelement <4 x float> [[TMP5]], i32 2
; CHECK-NEXT:    [[TMP8:%.*]] = extractelement <4 x float> [[TMP5]], i32 1
; CHECK-NEXT:    [[TMP9:%.*]] = extractelement <4 x float> [[TMP5]], i32 0
; CHECK-NEXT:    [[GEP20:%.*]] = getelementptr inbounds i8, ptr addrspace(5) [[ARRAYIDX]], i64 20
; CHECK-NEXT:    [[GEP24:%.*]] = getelementptr inbounds i8, ptr addrspace(5) [[ARRAYIDX]], i64 24
; CHECK-NEXT:    [[GEP28:%.*]] = getelementptr inbounds i8, ptr addrspace(5) [[ARRAYIDX]], i64 28
; CHECK-NEXT:    ret void
;
entry:
  %accumulators = alloca [4 x [1 x %"struct.fbgemm_gpu::VecNT"]], align 32, addrspace(5)
  %arrayidx = getelementptr inbounds [4 x [1 x %"struct.fbgemm_gpu::VecNT"]], ptr addrspace(5) %accumulators, i32 0, i32 %idx, i32 0

  ; Load individual float values with byte offsets (matches real pattern)
  %load0 = load float, ptr addrspace(5) %arrayidx, align 32
  %gep4 = getelementptr inbounds i8, ptr addrspace(5) %arrayidx, i64 4
  %load1 = load float, ptr addrspace(5) %gep4, align 4
  %gep8 = getelementptr inbounds i8, ptr addrspace(5) %arrayidx, i64 8
  %load2 = load float, ptr addrspace(5) %gep8, align 8
  %gep12 = getelementptr inbounds i8, ptr addrspace(5) %arrayidx, i64 12
  %load3 = load float, ptr addrspace(5) %gep12, align 4

  %gep16 = getelementptr inbounds i8, ptr addrspace(5) %arrayidx, i64 16
  %load4 = load float, ptr addrspace(5) %gep16, align 16
  %gep20 = getelementptr inbounds i8, ptr addrspace(5) %arrayidx, i64 20
  %load5 = load float, ptr addrspace(5) %gep20, align 4
  %gep24 = getelementptr inbounds i8, ptr addrspace(5) %arrayidx, i64 24
  %load6 = load float, ptr addrspace(5) %gep24, align 8
  %gep28 = getelementptr inbounds i8, ptr addrspace(5) %arrayidx, i64 28
  %load7 = load float, ptr addrspace(5) %gep28, align 4

  ret void
}

; -----------------------------------------------------------------------------
; Realistic accumulator pattern: stores with arithmetic operations
; This matches the pattern where accumulator values are updated with fadd operations
; Expect: vectorize the memory operations and arithmetic
;
define amdgpu_kernel void @realistic_accumulator_updates(i32 %idx, <4 x float> %input1, <4 x float> %input2) {
; CHECK-LABEL: define amdgpu_kernel void @realistic_accumulator_updates(
; CHECK-SAME: i32 [[IDX:%.*]], <4 x float> [[INPUT1:%.*]], <4 x float> [[INPUT2:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ACCUMULATORS:%.*]] = alloca [4 x [1 x %"struct.fbgemm_gpu::VecNT"]], align 32, addrspace(5)
; CHECK-NEXT:    [[ARRAYIDX:%.*]] = getelementptr inbounds [4 x [1 x %"struct.fbgemm_gpu::VecNT"]], ptr addrspace(5) [[ACCUMULATORS]], i32 0, i32 [[IDX]], i32 0
; CHECK-NEXT:    [[TMP0:%.*]] = load <4 x float>, ptr addrspace(5) [[ARRAYIDX]], align 32
; CHECK-NEXT:    [[LOAD3:%.*]] = extractelement <4 x float> [[TMP0]], i32 3
; CHECK-NEXT:    [[LOAD2:%.*]] = extractelement <4 x float> [[TMP0]], i32 2
; CHECK-NEXT:    [[LOAD1:%.*]] = extractelement <4 x float> [[TMP0]], i32 1
; CHECK-NEXT:    [[LOAD0:%.*]] = extractelement <4 x float> [[TMP0]], i32 0
; CHECK-NEXT:    [[GEP4:%.*]] = getelementptr inbounds i8, ptr addrspace(5) [[ARRAYIDX]], i64 4
; CHECK-NEXT:    [[GEP8:%.*]] = getelementptr inbounds i8, ptr addrspace(5) [[ARRAYIDX]], i64 8
; CHECK-NEXT:    [[GEP12:%.*]] = getelementptr inbounds i8, ptr addrspace(5) [[ARRAYIDX]], i64 12
; CHECK-NEXT:    [[INPUT0:%.*]] = extractelement <4 x float> [[INPUT1]], i32 0
; CHECK-NEXT:    [[INPUT1_ELEM:%.*]] = extractelement <4 x float> [[INPUT1]], i32 1
; CHECK-NEXT:    [[INPUT2_ELEM:%.*]] = extractelement <4 x float> [[INPUT1]], i32 2
; CHECK-NEXT:    [[INPUT3_ELEM:%.*]] = extractelement <4 x float> [[INPUT1]], i32 3
; CHECK-NEXT:    [[ADD0:%.*]] = fadd contract float [[LOAD0]], [[INPUT0]]
; CHECK-NEXT:    [[ADD1:%.*]] = fadd contract float [[LOAD1]], [[INPUT1_ELEM]]
; CHECK-NEXT:    [[ADD2:%.*]] = fadd contract float [[LOAD2]], [[INPUT2_ELEM]]
; CHECK-NEXT:    [[ADD3:%.*]] = fadd contract float [[LOAD3]], [[INPUT3_ELEM]]
; CHECK-NEXT:    [[TMP5:%.*]] = insertelement <4 x float> undef, float [[ADD0]], i32 0
; CHECK-NEXT:    [[TMP6:%.*]] = insertelement <4 x float> [[TMP5]], float [[ADD1]], i32 1
; CHECK-NEXT:    [[TMP7:%.*]] = insertelement <4 x float> [[TMP6]], float [[ADD2]], i32 2
; CHECK-NEXT:    [[TMP8:%.*]] = insertelement <4 x float> [[TMP7]], float [[ADD3]], i32 3
; CHECK-NEXT:    store <4 x float> [[TMP8]], ptr addrspace(5) [[ARRAYIDX]], align 4
; CHECK-NEXT:    [[GEP16:%.*]] = getelementptr inbounds i8, ptr addrspace(5) [[ARRAYIDX]], i64 16
; CHECK-NEXT:    [[TMP9:%.*]] = load <4 x float>, ptr addrspace(5) [[GEP16]], align 4
; CHECK-NEXT:    [[LOAD7:%.*]] = extractelement <4 x float> [[TMP9]], i32 3
; CHECK-NEXT:    [[LOAD6:%.*]] = extractelement <4 x float> [[TMP9]], i32 2
; CHECK-NEXT:    [[LOAD5:%.*]] = extractelement <4 x float> [[TMP9]], i32 1
; CHECK-NEXT:    [[LOAD4:%.*]] = extractelement <4 x float> [[TMP9]], i32 0
; CHECK-NEXT:    [[GEP20:%.*]] = getelementptr inbounds i8, ptr addrspace(5) [[ARRAYIDX]], i64 20
; CHECK-NEXT:    [[GEP24:%.*]] = getelementptr inbounds i8, ptr addrspace(5) [[ARRAYIDX]], i64 24
; CHECK-NEXT:    [[GEP28:%.*]] = getelementptr inbounds i8, ptr addrspace(5) [[ARRAYIDX]], i64 28
; CHECK-NEXT:    [[INPUT4:%.*]] = extractelement <4 x float> [[INPUT2]], i32 0
; CHECK-NEXT:    [[INPUT5:%.*]] = extractelement <4 x float> [[INPUT2]], i32 1
; CHECK-NEXT:    [[INPUT6:%.*]] = extractelement <4 x float> [[INPUT2]], i32 2
; CHECK-NEXT:    [[INPUT7:%.*]] = extractelement <4 x float> [[INPUT2]], i32 3
; CHECK-NEXT:    [[ADD4:%.*]] = fadd contract float [[LOAD4]], [[INPUT4]]
; CHECK-NEXT:    [[ADD5:%.*]] = fadd contract float [[LOAD5]], [[INPUT5]]
; CHECK-NEXT:    [[ADD6:%.*]] = fadd contract float [[LOAD6]], [[INPUT6]]
; CHECK-NEXT:    [[ADD7:%.*]] = fadd contract float [[LOAD7]], [[INPUT7]]
; CHECK-NEXT:    [[TMP14:%.*]] = insertelement <4 x float> undef, float [[ADD4]], i32 0
; CHECK-NEXT:    [[TMP15:%.*]] = insertelement <4 x float> [[TMP14]], float [[ADD5]], i32 1
; CHECK-NEXT:    [[TMP16:%.*]] = insertelement <4 x float> [[TMP15]], float [[ADD6]], i32 2
; CHECK-NEXT:    [[TMP17:%.*]] = insertelement <4 x float> [[TMP16]], float [[ADD7]], i32 3
; CHECK-NEXT:    store <4 x float> [[TMP17]], ptr addrspace(5) [[GEP16]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %accumulators = alloca [4 x [1 x %"struct.fbgemm_gpu::VecNT"]], align 32, addrspace(5)
  %arrayidx = getelementptr inbounds [4 x [1 x %"struct.fbgemm_gpu::VecNT"]], ptr addrspace(5) %accumulators, i32 0, i32 %idx, i32 0

  ; Load first group of accumulator values
  %load0 = load float, ptr addrspace(5) %arrayidx, align 32
  %gep4 = getelementptr inbounds i8, ptr addrspace(5) %arrayidx, i64 4
  %load1 = load float, ptr addrspace(5) %gep4, align 4
  %gep8 = getelementptr inbounds i8, ptr addrspace(5) %arrayidx, i64 8
  %load2 = load float, ptr addrspace(5) %gep8, align 8
  %gep12 = getelementptr inbounds i8, ptr addrspace(5) %arrayidx, i64 12
  %load3 = load float, ptr addrspace(5) %gep12, align 4

  ; Add input values (extract individual elements)
  %input0 = extractelement <4 x float> %input1, i32 0
  %input1_elem = extractelement <4 x float> %input1, i32 1
  %input2_elem = extractelement <4 x float> %input1, i32 2
  %input3_elem = extractelement <4 x float> %input1, i32 3

  %add0 = fadd contract float %load0, %input0
  %add1 = fadd contract float %load1, %input1_elem
  %add2 = fadd contract float %load2, %input2_elem
  %add3 = fadd contract float %load3, %input3_elem

  ; Store back
  store float %add0, ptr addrspace(5) %arrayidx, align 32
  store float %add1, ptr addrspace(5) %gep4, align 4
  store float %add2, ptr addrspace(5) %gep8, align 8
  store float %add3, ptr addrspace(5) %gep12, align 4

  ; Load second group of accumulator values
  %gep16 = getelementptr inbounds i8, ptr addrspace(5) %arrayidx, i64 16
  %load4 = load float, ptr addrspace(5) %gep16, align 16
  %gep20 = getelementptr inbounds i8, ptr addrspace(5) %arrayidx, i64 20
  %load5 = load float, ptr addrspace(5) %gep20, align 4
  %gep24 = getelementptr inbounds i8, ptr addrspace(5) %arrayidx, i64 24
  %load6 = load float, ptr addrspace(5) %gep24, align 8
  %gep28 = getelementptr inbounds i8, ptr addrspace(5) %arrayidx, i64 28
  %load7 = load float, ptr addrspace(5) %gep28, align 4

  ; Add second input values
  %input4 = extractelement <4 x float> %input2, i32 0
  %input5 = extractelement <4 x float> %input2, i32 1
  %input6 = extractelement <4 x float> %input2, i32 2
  %input7 = extractelement <4 x float> %input2, i32 3

  %add4 = fadd contract float %load4, %input4
  %add5 = fadd contract float %load5, %input5
  %add6 = fadd contract float %load6, %input6
  %add7 = fadd contract float %load7, %input7

  ; Store back
  store float %add4, ptr addrspace(5) %gep16, align 16
  store float %add5, ptr addrspace(5) %gep20, align 4
  store float %add6, ptr addrspace(5) %gep24, align 8
  store float %add7, ptr addrspace(5) %gep28, align 4

  ret void
}
