; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5

; RUN: llc -mtriple=amdgcn -mcpu=tahiti < %s | FileCheck -check-prefix=SI %s
; RUN: llc -mtriple=amdgcn -mcpu=tonga < %s | FileCheck -check-prefix=VI %s
; RUN: llc -mtriple=amdgcn -mcpu=gfx900 < %s | FileCheck -check-prefix=GFX9 %s
; RUN: llc -mtriple=amdgcn -mcpu=gfx1100 -mattr=+real-true16 < %s | FileCheck -check-prefixes=GFX11,GFX11-TRUE16 %s
; RUN: llc -mtriple=amdgcn -mcpu=gfx1100 -mattr=-real-true16 < %s | FileCheck -check-prefixes=GFX11,GFX11-FAKE16 %s

define <20 x float> @bitcast_v20i32_to_v20f32(<20 x i32> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v20i32_to_v20f32:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB0_2
; SI-NEXT:  ; %bb.1: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v19, vcc, 3, v19
; SI-NEXT:    v_add_i32_e32 v18, vcc, 3, v18
; SI-NEXT:    v_add_i32_e32 v17, vcc, 3, v17
; SI-NEXT:    v_add_i32_e32 v16, vcc, 3, v16
; SI-NEXT:    v_add_i32_e32 v15, vcc, 3, v15
; SI-NEXT:    v_add_i32_e32 v14, vcc, 3, v14
; SI-NEXT:    v_add_i32_e32 v13, vcc, 3, v13
; SI-NEXT:    v_add_i32_e32 v12, vcc, 3, v12
; SI-NEXT:    v_add_i32_e32 v11, vcc, 3, v11
; SI-NEXT:    v_add_i32_e32 v10, vcc, 3, v10
; SI-NEXT:    v_add_i32_e32 v9, vcc, 3, v9
; SI-NEXT:    v_add_i32_e32 v8, vcc, 3, v8
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v7
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v5
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v3
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v1
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:  .LBB0_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v20i32_to_v20f32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB0_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v19, vcc, 3, v19
; VI-NEXT:    v_add_u32_e32 v18, vcc, 3, v18
; VI-NEXT:    v_add_u32_e32 v17, vcc, 3, v17
; VI-NEXT:    v_add_u32_e32 v16, vcc, 3, v16
; VI-NEXT:    v_add_u32_e32 v15, vcc, 3, v15
; VI-NEXT:    v_add_u32_e32 v14, vcc, 3, v14
; VI-NEXT:    v_add_u32_e32 v13, vcc, 3, v13
; VI-NEXT:    v_add_u32_e32 v12, vcc, 3, v12
; VI-NEXT:    v_add_u32_e32 v11, vcc, 3, v11
; VI-NEXT:    v_add_u32_e32 v10, vcc, 3, v10
; VI-NEXT:    v_add_u32_e32 v9, vcc, 3, v9
; VI-NEXT:    v_add_u32_e32 v8, vcc, 3, v8
; VI-NEXT:    v_add_u32_e32 v7, vcc, 3, v7
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_add_u32_e32 v5, vcc, 3, v5
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_add_u32_e32 v3, vcc, 3, v3
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_add_u32_e32 v1, vcc, 3, v1
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:  .LBB0_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v20i32_to_v20f32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB0_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_u32_e32 v19, 3, v19
; GFX9-NEXT:    v_add_u32_e32 v18, 3, v18
; GFX9-NEXT:    v_add_u32_e32 v17, 3, v17
; GFX9-NEXT:    v_add_u32_e32 v16, 3, v16
; GFX9-NEXT:    v_add_u32_e32 v15, 3, v15
; GFX9-NEXT:    v_add_u32_e32 v14, 3, v14
; GFX9-NEXT:    v_add_u32_e32 v13, 3, v13
; GFX9-NEXT:    v_add_u32_e32 v12, 3, v12
; GFX9-NEXT:    v_add_u32_e32 v11, 3, v11
; GFX9-NEXT:    v_add_u32_e32 v10, 3, v10
; GFX9-NEXT:    v_add_u32_e32 v9, 3, v9
; GFX9-NEXT:    v_add_u32_e32 v8, 3, v8
; GFX9-NEXT:    v_add_u32_e32 v7, 3, v7
; GFX9-NEXT:    v_add_u32_e32 v6, 3, v6
; GFX9-NEXT:    v_add_u32_e32 v5, 3, v5
; GFX9-NEXT:    v_add_u32_e32 v4, 3, v4
; GFX9-NEXT:    v_add_u32_e32 v3, 3, v3
; GFX9-NEXT:    v_add_u32_e32 v2, 3, v2
; GFX9-NEXT:    v_add_u32_e32 v1, 3, v1
; GFX9-NEXT:    v_add_u32_e32 v0, 3, v0
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:  .LBB0_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v20i32_to_v20f32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB0_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_nc_u32_e32 v19, 3, v19
; GFX11-NEXT:    v_add_nc_u32_e32 v18, 3, v18
; GFX11-NEXT:    v_add_nc_u32_e32 v17, 3, v17
; GFX11-NEXT:    v_add_nc_u32_e32 v16, 3, v16
; GFX11-NEXT:    v_add_nc_u32_e32 v15, 3, v15
; GFX11-NEXT:    v_add_nc_u32_e32 v14, 3, v14
; GFX11-NEXT:    v_add_nc_u32_e32 v13, 3, v13
; GFX11-NEXT:    v_add_nc_u32_e32 v12, 3, v12
; GFX11-NEXT:    v_add_nc_u32_e32 v11, 3, v11
; GFX11-NEXT:    v_add_nc_u32_e32 v10, 3, v10
; GFX11-NEXT:    v_add_nc_u32_e32 v9, 3, v9
; GFX11-NEXT:    v_add_nc_u32_e32 v8, 3, v8
; GFX11-NEXT:    v_add_nc_u32_e32 v7, 3, v7
; GFX11-NEXT:    v_add_nc_u32_e32 v6, 3, v6
; GFX11-NEXT:    v_add_nc_u32_e32 v5, 3, v5
; GFX11-NEXT:    v_add_nc_u32_e32 v4, 3, v4
; GFX11-NEXT:    v_add_nc_u32_e32 v3, 3, v3
; GFX11-NEXT:    v_add_nc_u32_e32 v2, 3, v2
; GFX11-NEXT:    v_add_nc_u32_e32 v1, 3, v1
; GFX11-NEXT:    v_add_nc_u32_e32 v0, 3, v0
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:  .LBB0_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <20 x i32> %a, splat (i32 3)
  %a2 = bitcast <20 x i32> %a1 to <20 x float>
  br label %end

cmp.false:
  %a3 = bitcast <20 x i32> %a to <20 x float>
  br label %end

end:
  %phi = phi <20 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <20 x float> %phi
}

define inreg <20 x float> @bitcast_v20i32_to_v20f32_scalar(<20 x i32> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v20i32_to_v20f32_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_readfirstlane_b32 s4, v6
; SI-NEXT:    v_readfirstlane_b32 s6, v5
; SI-NEXT:    v_readfirstlane_b32 s7, v4
; SI-NEXT:    v_readfirstlane_b32 s8, v3
; SI-NEXT:    v_readfirstlane_b32 s9, v2
; SI-NEXT:    v_readfirstlane_b32 s10, v1
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    v_readfirstlane_b32 s11, v0
; SI-NEXT:    s_cbranch_scc0 .LBB1_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_cbranch_execnz .LBB1_3
; SI-NEXT:  .LBB1_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s6, s6, 3
; SI-NEXT:    s_add_i32 s7, s7, 3
; SI-NEXT:    s_add_i32 s8, s8, 3
; SI-NEXT:    s_add_i32 s9, s9, 3
; SI-NEXT:    s_add_i32 s10, s10, 3
; SI-NEXT:    s_add_i32 s11, s11, 3
; SI-NEXT:    s_add_i32 s29, s29, 3
; SI-NEXT:    s_add_i32 s28, s28, 3
; SI-NEXT:    s_add_i32 s27, s27, 3
; SI-NEXT:    s_add_i32 s26, s26, 3
; SI-NEXT:    s_add_i32 s25, s25, 3
; SI-NEXT:    s_add_i32 s24, s24, 3
; SI-NEXT:    s_add_i32 s23, s23, 3
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_add_i32 s21, s21, 3
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_add_i32 s19, s19, 3
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_add_i32 s17, s17, 3
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:  .LBB1_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v2, s18
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v4, s20
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v6, s22
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    v_mov_b32_e32 v8, s24
; SI-NEXT:    v_mov_b32_e32 v9, s25
; SI-NEXT:    v_mov_b32_e32 v10, s26
; SI-NEXT:    v_mov_b32_e32 v11, s27
; SI-NEXT:    v_mov_b32_e32 v12, s28
; SI-NEXT:    v_mov_b32_e32 v13, s29
; SI-NEXT:    v_mov_b32_e32 v14, s11
; SI-NEXT:    v_mov_b32_e32 v15, s10
; SI-NEXT:    v_mov_b32_e32 v16, s9
; SI-NEXT:    v_mov_b32_e32 v17, s8
; SI-NEXT:    v_mov_b32_e32 v18, s7
; SI-NEXT:    v_mov_b32_e32 v19, s6
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB1_4:
; SI-NEXT:    s_branch .LBB1_2
;
; VI-LABEL: bitcast_v20i32_to_v20f32_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    v_readfirstlane_b32 s6, v5
; VI-NEXT:    v_readfirstlane_b32 s7, v4
; VI-NEXT:    v_readfirstlane_b32 s8, v3
; VI-NEXT:    v_readfirstlane_b32 s9, v2
; VI-NEXT:    v_readfirstlane_b32 s10, v1
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    v_readfirstlane_b32 s11, v0
; VI-NEXT:    s_cbranch_scc0 .LBB1_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB1_3
; VI-NEXT:  .LBB1_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s6, s6, 3
; VI-NEXT:    s_add_i32 s7, s7, 3
; VI-NEXT:    s_add_i32 s8, s8, 3
; VI-NEXT:    s_add_i32 s9, s9, 3
; VI-NEXT:    s_add_i32 s10, s10, 3
; VI-NEXT:    s_add_i32 s11, s11, 3
; VI-NEXT:    s_add_i32 s29, s29, 3
; VI-NEXT:    s_add_i32 s28, s28, 3
; VI-NEXT:    s_add_i32 s27, s27, 3
; VI-NEXT:    s_add_i32 s26, s26, 3
; VI-NEXT:    s_add_i32 s25, s25, 3
; VI-NEXT:    s_add_i32 s24, s24, 3
; VI-NEXT:    s_add_i32 s23, s23, 3
; VI-NEXT:    s_add_i32 s22, s22, 3
; VI-NEXT:    s_add_i32 s21, s21, 3
; VI-NEXT:    s_add_i32 s20, s20, 3
; VI-NEXT:    s_add_i32 s19, s19, 3
; VI-NEXT:    s_add_i32 s18, s18, 3
; VI-NEXT:    s_add_i32 s17, s17, 3
; VI-NEXT:    s_add_i32 s16, s16, 3
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:  .LBB1_3: ; %end
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    v_mov_b32_e32 v8, s24
; VI-NEXT:    v_mov_b32_e32 v9, s25
; VI-NEXT:    v_mov_b32_e32 v10, s26
; VI-NEXT:    v_mov_b32_e32 v11, s27
; VI-NEXT:    v_mov_b32_e32 v12, s28
; VI-NEXT:    v_mov_b32_e32 v13, s29
; VI-NEXT:    v_mov_b32_e32 v14, s11
; VI-NEXT:    v_mov_b32_e32 v15, s10
; VI-NEXT:    v_mov_b32_e32 v16, s9
; VI-NEXT:    v_mov_b32_e32 v17, s8
; VI-NEXT:    v_mov_b32_e32 v18, s7
; VI-NEXT:    v_mov_b32_e32 v19, s6
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB1_4:
; VI-NEXT:    s_branch .LBB1_2
;
; GFX9-LABEL: bitcast_v20i32_to_v20f32_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_readfirstlane_b32 s4, v6
; GFX9-NEXT:    v_readfirstlane_b32 s6, v5
; GFX9-NEXT:    v_readfirstlane_b32 s7, v4
; GFX9-NEXT:    v_readfirstlane_b32 s8, v3
; GFX9-NEXT:    v_readfirstlane_b32 s9, v2
; GFX9-NEXT:    v_readfirstlane_b32 s10, v1
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    v_readfirstlane_b32 s11, v0
; GFX9-NEXT:    s_cbranch_scc0 .LBB1_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB1_3
; GFX9-NEXT:  .LBB1_2: ; %cmp.true
; GFX9-NEXT:    s_add_i32 s6, s6, 3
; GFX9-NEXT:    s_add_i32 s7, s7, 3
; GFX9-NEXT:    s_add_i32 s8, s8, 3
; GFX9-NEXT:    s_add_i32 s9, s9, 3
; GFX9-NEXT:    s_add_i32 s10, s10, 3
; GFX9-NEXT:    s_add_i32 s11, s11, 3
; GFX9-NEXT:    s_add_i32 s29, s29, 3
; GFX9-NEXT:    s_add_i32 s28, s28, 3
; GFX9-NEXT:    s_add_i32 s27, s27, 3
; GFX9-NEXT:    s_add_i32 s26, s26, 3
; GFX9-NEXT:    s_add_i32 s25, s25, 3
; GFX9-NEXT:    s_add_i32 s24, s24, 3
; GFX9-NEXT:    s_add_i32 s23, s23, 3
; GFX9-NEXT:    s_add_i32 s22, s22, 3
; GFX9-NEXT:    s_add_i32 s21, s21, 3
; GFX9-NEXT:    s_add_i32 s20, s20, 3
; GFX9-NEXT:    s_add_i32 s19, s19, 3
; GFX9-NEXT:    s_add_i32 s18, s18, 3
; GFX9-NEXT:    s_add_i32 s17, s17, 3
; GFX9-NEXT:    s_add_i32 s16, s16, 3
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:  .LBB1_3: ; %end
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    v_mov_b32_e32 v8, s24
; GFX9-NEXT:    v_mov_b32_e32 v9, s25
; GFX9-NEXT:    v_mov_b32_e32 v10, s26
; GFX9-NEXT:    v_mov_b32_e32 v11, s27
; GFX9-NEXT:    v_mov_b32_e32 v12, s28
; GFX9-NEXT:    v_mov_b32_e32 v13, s29
; GFX9-NEXT:    v_mov_b32_e32 v14, s11
; GFX9-NEXT:    v_mov_b32_e32 v15, s10
; GFX9-NEXT:    v_mov_b32_e32 v16, s9
; GFX9-NEXT:    v_mov_b32_e32 v17, s8
; GFX9-NEXT:    v_mov_b32_e32 v18, s7
; GFX9-NEXT:    v_mov_b32_e32 v19, s6
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB1_4:
; GFX9-NEXT:    s_branch .LBB1_2
;
; GFX11-LABEL: bitcast_v20i32_to_v20f32_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    v_readfirstlane_b32 s6, v2
; GFX11-NEXT:    v_readfirstlane_b32 s4, v1
; GFX11-NEXT:    v_readfirstlane_b32 s5, v0
; GFX11-NEXT:    s_cmp_lg_u32 s6, 0
; GFX11-NEXT:    s_mov_b32 s6, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB1_4
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s6
; GFX11-NEXT:    s_cbranch_vccnz .LBB1_3
; GFX11-NEXT:  .LBB1_2: ; %cmp.true
; GFX11-NEXT:    s_add_i32 s4, s4, 3
; GFX11-NEXT:    s_add_i32 s5, s5, 3
; GFX11-NEXT:    s_add_i32 s29, s29, 3
; GFX11-NEXT:    s_add_i32 s28, s28, 3
; GFX11-NEXT:    s_add_i32 s27, s27, 3
; GFX11-NEXT:    s_add_i32 s26, s26, 3
; GFX11-NEXT:    s_add_i32 s25, s25, 3
; GFX11-NEXT:    s_add_i32 s24, s24, 3
; GFX11-NEXT:    s_add_i32 s23, s23, 3
; GFX11-NEXT:    s_add_i32 s22, s22, 3
; GFX11-NEXT:    s_add_i32 s21, s21, 3
; GFX11-NEXT:    s_add_i32 s20, s20, 3
; GFX11-NEXT:    s_add_i32 s19, s19, 3
; GFX11-NEXT:    s_add_i32 s18, s18, 3
; GFX11-NEXT:    s_add_i32 s17, s17, 3
; GFX11-NEXT:    s_add_i32 s16, s16, 3
; GFX11-NEXT:    s_add_i32 s3, s3, 3
; GFX11-NEXT:    s_add_i32 s2, s2, 3
; GFX11-NEXT:    s_add_i32 s1, s1, 3
; GFX11-NEXT:    s_add_i32 s0, s0, 3
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:  .LBB1_3: ; %end
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s16 :: v_dual_mov_b32 v5, s17
; GFX11-NEXT:    v_dual_mov_b32 v6, s18 :: v_dual_mov_b32 v7, s19
; GFX11-NEXT:    v_dual_mov_b32 v8, s20 :: v_dual_mov_b32 v9, s21
; GFX11-NEXT:    v_dual_mov_b32 v10, s22 :: v_dual_mov_b32 v11, s23
; GFX11-NEXT:    v_dual_mov_b32 v12, s24 :: v_dual_mov_b32 v13, s25
; GFX11-NEXT:    v_dual_mov_b32 v14, s26 :: v_dual_mov_b32 v15, s27
; GFX11-NEXT:    v_dual_mov_b32 v16, s28 :: v_dual_mov_b32 v17, s29
; GFX11-NEXT:    v_dual_mov_b32 v18, s5 :: v_dual_mov_b32 v19, s4
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB1_4:
; GFX11-NEXT:    s_branch .LBB1_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <20 x i32> %a, splat (i32 3)
  %a2 = bitcast <20 x i32> %a1 to <20 x float>
  br label %end

cmp.false:
  %a3 = bitcast <20 x i32> %a to <20 x float>
  br label %end

end:
  %phi = phi <20 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <20 x float> %phi
}

define <20 x i32> @bitcast_v20f32_to_v20i32(<20 x float> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v20f32_to_v20i32:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB2_2
; SI-NEXT:  ; %bb.1: ; %cmp.true
; SI-NEXT:    v_add_f32_e32 v19, 1.0, v19
; SI-NEXT:    v_add_f32_e32 v18, 1.0, v18
; SI-NEXT:    v_add_f32_e32 v17, 1.0, v17
; SI-NEXT:    v_add_f32_e32 v16, 1.0, v16
; SI-NEXT:    v_add_f32_e32 v15, 1.0, v15
; SI-NEXT:    v_add_f32_e32 v14, 1.0, v14
; SI-NEXT:    v_add_f32_e32 v13, 1.0, v13
; SI-NEXT:    v_add_f32_e32 v12, 1.0, v12
; SI-NEXT:    v_add_f32_e32 v11, 1.0, v11
; SI-NEXT:    v_add_f32_e32 v10, 1.0, v10
; SI-NEXT:    v_add_f32_e32 v9, 1.0, v9
; SI-NEXT:    v_add_f32_e32 v8, 1.0, v8
; SI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; SI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; SI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; SI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; SI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; SI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; SI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; SI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:  .LBB2_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v20f32_to_v20i32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB2_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f32_e32 v19, 1.0, v19
; VI-NEXT:    v_add_f32_e32 v18, 1.0, v18
; VI-NEXT:    v_add_f32_e32 v17, 1.0, v17
; VI-NEXT:    v_add_f32_e32 v16, 1.0, v16
; VI-NEXT:    v_add_f32_e32 v15, 1.0, v15
; VI-NEXT:    v_add_f32_e32 v14, 1.0, v14
; VI-NEXT:    v_add_f32_e32 v13, 1.0, v13
; VI-NEXT:    v_add_f32_e32 v12, 1.0, v12
; VI-NEXT:    v_add_f32_e32 v11, 1.0, v11
; VI-NEXT:    v_add_f32_e32 v10, 1.0, v10
; VI-NEXT:    v_add_f32_e32 v9, 1.0, v9
; VI-NEXT:    v_add_f32_e32 v8, 1.0, v8
; VI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; VI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; VI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; VI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; VI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; VI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; VI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; VI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:  .LBB2_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v20f32_to_v20i32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB2_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e32 v19, 1.0, v19
; GFX9-NEXT:    v_add_f32_e32 v18, 1.0, v18
; GFX9-NEXT:    v_add_f32_e32 v17, 1.0, v17
; GFX9-NEXT:    v_add_f32_e32 v16, 1.0, v16
; GFX9-NEXT:    v_add_f32_e32 v15, 1.0, v15
; GFX9-NEXT:    v_add_f32_e32 v14, 1.0, v14
; GFX9-NEXT:    v_add_f32_e32 v13, 1.0, v13
; GFX9-NEXT:    v_add_f32_e32 v12, 1.0, v12
; GFX9-NEXT:    v_add_f32_e32 v11, 1.0, v11
; GFX9-NEXT:    v_add_f32_e32 v10, 1.0, v10
; GFX9-NEXT:    v_add_f32_e32 v9, 1.0, v9
; GFX9-NEXT:    v_add_f32_e32 v8, 1.0, v8
; GFX9-NEXT:    v_add_f32_e32 v7, 1.0, v7
; GFX9-NEXT:    v_add_f32_e32 v6, 1.0, v6
; GFX9-NEXT:    v_add_f32_e32 v5, 1.0, v5
; GFX9-NEXT:    v_add_f32_e32 v4, 1.0, v4
; GFX9-NEXT:    v_add_f32_e32 v3, 1.0, v3
; GFX9-NEXT:    v_add_f32_e32 v2, 1.0, v2
; GFX9-NEXT:    v_add_f32_e32 v1, 1.0, v1
; GFX9-NEXT:    v_add_f32_e32 v0, 1.0, v0
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:  .LBB2_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v20f32_to_v20i32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB2_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_dual_add_f32 v19, 1.0, v19 :: v_dual_add_f32 v18, 1.0, v18
; GFX11-NEXT:    v_dual_add_f32 v17, 1.0, v17 :: v_dual_add_f32 v16, 1.0, v16
; GFX11-NEXT:    v_dual_add_f32 v15, 1.0, v15 :: v_dual_add_f32 v14, 1.0, v14
; GFX11-NEXT:    v_dual_add_f32 v13, 1.0, v13 :: v_dual_add_f32 v12, 1.0, v12
; GFX11-NEXT:    v_dual_add_f32 v11, 1.0, v11 :: v_dual_add_f32 v10, 1.0, v10
; GFX11-NEXT:    v_dual_add_f32 v9, 1.0, v9 :: v_dual_add_f32 v8, 1.0, v8
; GFX11-NEXT:    v_dual_add_f32 v7, 1.0, v7 :: v_dual_add_f32 v6, 1.0, v6
; GFX11-NEXT:    v_dual_add_f32 v5, 1.0, v5 :: v_dual_add_f32 v4, 1.0, v4
; GFX11-NEXT:    v_dual_add_f32 v3, 1.0, v3 :: v_dual_add_f32 v2, 1.0, v2
; GFX11-NEXT:    v_dual_add_f32 v1, 1.0, v1 :: v_dual_add_f32 v0, 1.0, v0
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:  .LBB2_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <20 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <20 x float> %a1 to <20 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <20 x float> %a to <20 x i32>
  br label %end

end:
  %phi = phi <20 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <20 x i32> %phi
}

define inreg <20 x i32> @bitcast_v20f32_to_v20i32_scalar(<20 x float> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v20f32_to_v20i32_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_writelane_b32 v32, s36, 0
; SI-NEXT:    v_writelane_b32 v32, s37, 1
; SI-NEXT:    v_writelane_b32 v32, s38, 2
; SI-NEXT:    v_writelane_b32 v32, s39, 3
; SI-NEXT:    v_writelane_b32 v32, s48, 4
; SI-NEXT:    v_writelane_b32 v32, s49, 5
; SI-NEXT:    v_writelane_b32 v32, s50, 6
; SI-NEXT:    v_writelane_b32 v32, s51, 7
; SI-NEXT:    v_writelane_b32 v32, s52, 8
; SI-NEXT:    v_writelane_b32 v32, s53, 9
; SI-NEXT:    v_writelane_b32 v32, s54, 10
; SI-NEXT:    v_writelane_b32 v32, s55, 11
; SI-NEXT:    v_readfirstlane_b32 s4, v6
; SI-NEXT:    s_mov_b32 s49, s29
; SI-NEXT:    s_mov_b32 s48, s28
; SI-NEXT:    s_mov_b32 s47, s27
; SI-NEXT:    s_mov_b32 s46, s26
; SI-NEXT:    s_mov_b32 s45, s25
; SI-NEXT:    s_mov_b32 s44, s24
; SI-NEXT:    s_mov_b32 s43, s23
; SI-NEXT:    s_mov_b32 s42, s22
; SI-NEXT:    s_mov_b32 s41, s21
; SI-NEXT:    s_mov_b32 s40, s20
; SI-NEXT:    s_mov_b32 s39, s19
; SI-NEXT:    s_mov_b32 s38, s18
; SI-NEXT:    s_mov_b32 s37, s17
; SI-NEXT:    s_mov_b32 s36, s16
; SI-NEXT:    v_readfirstlane_b32 s55, v5
; SI-NEXT:    v_readfirstlane_b32 s54, v4
; SI-NEXT:    v_readfirstlane_b32 s53, v3
; SI-NEXT:    v_readfirstlane_b32 s52, v2
; SI-NEXT:    v_readfirstlane_b32 s51, v1
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    v_readfirstlane_b32 s50, v0
; SI-NEXT:    s_cbranch_scc0 .LBB3_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_cbranch_execnz .LBB3_4
; SI-NEXT:  .LBB3_2: ; %cmp.true
; SI-NEXT:    v_add_f32_e64 v19, s55, 1.0
; SI-NEXT:    v_add_f32_e64 v18, s54, 1.0
; SI-NEXT:    v_add_f32_e64 v17, s53, 1.0
; SI-NEXT:    v_add_f32_e64 v16, s52, 1.0
; SI-NEXT:    v_add_f32_e64 v15, s51, 1.0
; SI-NEXT:    v_add_f32_e64 v14, s50, 1.0
; SI-NEXT:    v_add_f32_e64 v13, s49, 1.0
; SI-NEXT:    v_add_f32_e64 v12, s48, 1.0
; SI-NEXT:    v_add_f32_e64 v11, s47, 1.0
; SI-NEXT:    v_add_f32_e64 v10, s46, 1.0
; SI-NEXT:    v_add_f32_e64 v9, s45, 1.0
; SI-NEXT:    v_add_f32_e64 v8, s44, 1.0
; SI-NEXT:    v_add_f32_e64 v7, s43, 1.0
; SI-NEXT:    v_add_f32_e64 v6, s42, 1.0
; SI-NEXT:    v_add_f32_e64 v5, s41, 1.0
; SI-NEXT:    v_add_f32_e64 v4, s40, 1.0
; SI-NEXT:    v_add_f32_e64 v3, s39, 1.0
; SI-NEXT:    v_add_f32_e64 v2, s38, 1.0
; SI-NEXT:    v_add_f32_e64 v1, s37, 1.0
; SI-NEXT:    v_add_f32_e64 v0, s36, 1.0
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    s_branch .LBB3_5
; SI-NEXT:  .LBB3_3:
; SI-NEXT:    s_branch .LBB3_2
; SI-NEXT:  .LBB3_4:
; SI-NEXT:    v_mov_b32_e32 v0, s36
; SI-NEXT:    v_mov_b32_e32 v1, s37
; SI-NEXT:    v_mov_b32_e32 v2, s38
; SI-NEXT:    v_mov_b32_e32 v3, s39
; SI-NEXT:    v_mov_b32_e32 v4, s40
; SI-NEXT:    v_mov_b32_e32 v5, s41
; SI-NEXT:    v_mov_b32_e32 v6, s42
; SI-NEXT:    v_mov_b32_e32 v7, s43
; SI-NEXT:    v_mov_b32_e32 v8, s44
; SI-NEXT:    v_mov_b32_e32 v9, s45
; SI-NEXT:    v_mov_b32_e32 v10, s46
; SI-NEXT:    v_mov_b32_e32 v11, s47
; SI-NEXT:    v_mov_b32_e32 v12, s48
; SI-NEXT:    v_mov_b32_e32 v13, s49
; SI-NEXT:    v_mov_b32_e32 v14, s50
; SI-NEXT:    v_mov_b32_e32 v15, s51
; SI-NEXT:    v_mov_b32_e32 v16, s52
; SI-NEXT:    v_mov_b32_e32 v17, s53
; SI-NEXT:    v_mov_b32_e32 v18, s54
; SI-NEXT:    v_mov_b32_e32 v19, s55
; SI-NEXT:    v_mov_b32_e32 v20, s56
; SI-NEXT:    v_mov_b32_e32 v21, s57
; SI-NEXT:    v_mov_b32_e32 v22, s58
; SI-NEXT:    v_mov_b32_e32 v23, s59
; SI-NEXT:    v_mov_b32_e32 v24, s60
; SI-NEXT:    v_mov_b32_e32 v25, s61
; SI-NEXT:    v_mov_b32_e32 v26, s62
; SI-NEXT:    v_mov_b32_e32 v27, s63
; SI-NEXT:    v_mov_b32_e32 v28, s64
; SI-NEXT:    v_mov_b32_e32 v29, s65
; SI-NEXT:    v_mov_b32_e32 v30, s66
; SI-NEXT:    v_mov_b32_e32 v31, s67
; SI-NEXT:  .LBB3_5: ; %end
; SI-NEXT:    v_readlane_b32 s55, v32, 11
; SI-NEXT:    v_readlane_b32 s54, v32, 10
; SI-NEXT:    v_readlane_b32 s53, v32, 9
; SI-NEXT:    v_readlane_b32 s52, v32, 8
; SI-NEXT:    v_readlane_b32 s51, v32, 7
; SI-NEXT:    v_readlane_b32 s50, v32, 6
; SI-NEXT:    v_readlane_b32 s49, v32, 5
; SI-NEXT:    v_readlane_b32 s48, v32, 4
; SI-NEXT:    v_readlane_b32 s39, v32, 3
; SI-NEXT:    v_readlane_b32 s38, v32, 2
; SI-NEXT:    v_readlane_b32 s37, v32, 1
; SI-NEXT:    v_readlane_b32 s36, v32, 0
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v20f32_to_v20i32_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    v_writelane_b32 v32, s36, 0
; VI-NEXT:    v_writelane_b32 v32, s37, 1
; VI-NEXT:    v_writelane_b32 v32, s38, 2
; VI-NEXT:    v_writelane_b32 v32, s39, 3
; VI-NEXT:    v_writelane_b32 v32, s48, 4
; VI-NEXT:    v_writelane_b32 v32, s49, 5
; VI-NEXT:    v_writelane_b32 v32, s50, 6
; VI-NEXT:    v_writelane_b32 v32, s51, 7
; VI-NEXT:    v_writelane_b32 v32, s52, 8
; VI-NEXT:    v_writelane_b32 v32, s53, 9
; VI-NEXT:    v_writelane_b32 v32, s54, 10
; VI-NEXT:    v_writelane_b32 v32, s55, 11
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    s_mov_b32 s49, s29
; VI-NEXT:    s_mov_b32 s48, s28
; VI-NEXT:    s_mov_b32 s47, s27
; VI-NEXT:    s_mov_b32 s46, s26
; VI-NEXT:    s_mov_b32 s45, s25
; VI-NEXT:    s_mov_b32 s44, s24
; VI-NEXT:    s_mov_b32 s43, s23
; VI-NEXT:    s_mov_b32 s42, s22
; VI-NEXT:    s_mov_b32 s41, s21
; VI-NEXT:    s_mov_b32 s40, s20
; VI-NEXT:    s_mov_b32 s39, s19
; VI-NEXT:    s_mov_b32 s38, s18
; VI-NEXT:    s_mov_b32 s37, s17
; VI-NEXT:    s_mov_b32 s36, s16
; VI-NEXT:    v_readfirstlane_b32 s55, v5
; VI-NEXT:    v_readfirstlane_b32 s54, v4
; VI-NEXT:    v_readfirstlane_b32 s53, v3
; VI-NEXT:    v_readfirstlane_b32 s52, v2
; VI-NEXT:    v_readfirstlane_b32 s51, v1
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    v_readfirstlane_b32 s50, v0
; VI-NEXT:    s_cbranch_scc0 .LBB3_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB3_4
; VI-NEXT:  .LBB3_2: ; %cmp.true
; VI-NEXT:    v_add_f32_e64 v19, s55, 1.0
; VI-NEXT:    v_add_f32_e64 v18, s54, 1.0
; VI-NEXT:    v_add_f32_e64 v17, s53, 1.0
; VI-NEXT:    v_add_f32_e64 v16, s52, 1.0
; VI-NEXT:    v_add_f32_e64 v15, s51, 1.0
; VI-NEXT:    v_add_f32_e64 v14, s50, 1.0
; VI-NEXT:    v_add_f32_e64 v13, s49, 1.0
; VI-NEXT:    v_add_f32_e64 v12, s48, 1.0
; VI-NEXT:    v_add_f32_e64 v11, s47, 1.0
; VI-NEXT:    v_add_f32_e64 v10, s46, 1.0
; VI-NEXT:    v_add_f32_e64 v9, s45, 1.0
; VI-NEXT:    v_add_f32_e64 v8, s44, 1.0
; VI-NEXT:    v_add_f32_e64 v7, s43, 1.0
; VI-NEXT:    v_add_f32_e64 v6, s42, 1.0
; VI-NEXT:    v_add_f32_e64 v5, s41, 1.0
; VI-NEXT:    v_add_f32_e64 v4, s40, 1.0
; VI-NEXT:    v_add_f32_e64 v3, s39, 1.0
; VI-NEXT:    v_add_f32_e64 v2, s38, 1.0
; VI-NEXT:    v_add_f32_e64 v1, s37, 1.0
; VI-NEXT:    v_add_f32_e64 v0, s36, 1.0
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    s_branch .LBB3_5
; VI-NEXT:  .LBB3_3:
; VI-NEXT:    s_branch .LBB3_2
; VI-NEXT:  .LBB3_4:
; VI-NEXT:    v_mov_b32_e32 v0, s36
; VI-NEXT:    v_mov_b32_e32 v1, s37
; VI-NEXT:    v_mov_b32_e32 v2, s38
; VI-NEXT:    v_mov_b32_e32 v3, s39
; VI-NEXT:    v_mov_b32_e32 v4, s40
; VI-NEXT:    v_mov_b32_e32 v5, s41
; VI-NEXT:    v_mov_b32_e32 v6, s42
; VI-NEXT:    v_mov_b32_e32 v7, s43
; VI-NEXT:    v_mov_b32_e32 v8, s44
; VI-NEXT:    v_mov_b32_e32 v9, s45
; VI-NEXT:    v_mov_b32_e32 v10, s46
; VI-NEXT:    v_mov_b32_e32 v11, s47
; VI-NEXT:    v_mov_b32_e32 v12, s48
; VI-NEXT:    v_mov_b32_e32 v13, s49
; VI-NEXT:    v_mov_b32_e32 v14, s50
; VI-NEXT:    v_mov_b32_e32 v15, s51
; VI-NEXT:    v_mov_b32_e32 v16, s52
; VI-NEXT:    v_mov_b32_e32 v17, s53
; VI-NEXT:    v_mov_b32_e32 v18, s54
; VI-NEXT:    v_mov_b32_e32 v19, s55
; VI-NEXT:    v_mov_b32_e32 v20, s56
; VI-NEXT:    v_mov_b32_e32 v21, s57
; VI-NEXT:    v_mov_b32_e32 v22, s58
; VI-NEXT:    v_mov_b32_e32 v23, s59
; VI-NEXT:    v_mov_b32_e32 v24, s60
; VI-NEXT:    v_mov_b32_e32 v25, s61
; VI-NEXT:    v_mov_b32_e32 v26, s62
; VI-NEXT:    v_mov_b32_e32 v27, s63
; VI-NEXT:    v_mov_b32_e32 v28, s64
; VI-NEXT:    v_mov_b32_e32 v29, s65
; VI-NEXT:    v_mov_b32_e32 v30, s66
; VI-NEXT:    v_mov_b32_e32 v31, s67
; VI-NEXT:  .LBB3_5: ; %end
; VI-NEXT:    v_readlane_b32 s55, v32, 11
; VI-NEXT:    v_readlane_b32 s54, v32, 10
; VI-NEXT:    v_readlane_b32 s53, v32, 9
; VI-NEXT:    v_readlane_b32 s52, v32, 8
; VI-NEXT:    v_readlane_b32 s51, v32, 7
; VI-NEXT:    v_readlane_b32 s50, v32, 6
; VI-NEXT:    v_readlane_b32 s49, v32, 5
; VI-NEXT:    v_readlane_b32 s48, v32, 4
; VI-NEXT:    v_readlane_b32 s39, v32, 3
; VI-NEXT:    v_readlane_b32 s38, v32, 2
; VI-NEXT:    v_readlane_b32 s37, v32, 1
; VI-NEXT:    v_readlane_b32 s36, v32, 0
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v20f32_to_v20i32_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    v_writelane_b32 v32, s36, 0
; GFX9-NEXT:    v_writelane_b32 v32, s37, 1
; GFX9-NEXT:    v_writelane_b32 v32, s38, 2
; GFX9-NEXT:    v_writelane_b32 v32, s39, 3
; GFX9-NEXT:    v_writelane_b32 v32, s48, 4
; GFX9-NEXT:    v_writelane_b32 v32, s49, 5
; GFX9-NEXT:    v_writelane_b32 v32, s50, 6
; GFX9-NEXT:    v_writelane_b32 v32, s51, 7
; GFX9-NEXT:    v_writelane_b32 v32, s52, 8
; GFX9-NEXT:    v_writelane_b32 v32, s53, 9
; GFX9-NEXT:    v_writelane_b32 v32, s54, 10
; GFX9-NEXT:    v_writelane_b32 v32, s55, 11
; GFX9-NEXT:    v_readfirstlane_b32 s4, v6
; GFX9-NEXT:    s_mov_b32 s49, s29
; GFX9-NEXT:    s_mov_b32 s48, s28
; GFX9-NEXT:    s_mov_b32 s47, s27
; GFX9-NEXT:    s_mov_b32 s46, s26
; GFX9-NEXT:    s_mov_b32 s45, s25
; GFX9-NEXT:    s_mov_b32 s44, s24
; GFX9-NEXT:    s_mov_b32 s43, s23
; GFX9-NEXT:    s_mov_b32 s42, s22
; GFX9-NEXT:    s_mov_b32 s41, s21
; GFX9-NEXT:    s_mov_b32 s40, s20
; GFX9-NEXT:    s_mov_b32 s39, s19
; GFX9-NEXT:    s_mov_b32 s38, s18
; GFX9-NEXT:    s_mov_b32 s37, s17
; GFX9-NEXT:    s_mov_b32 s36, s16
; GFX9-NEXT:    v_readfirstlane_b32 s55, v5
; GFX9-NEXT:    v_readfirstlane_b32 s54, v4
; GFX9-NEXT:    v_readfirstlane_b32 s53, v3
; GFX9-NEXT:    v_readfirstlane_b32 s52, v2
; GFX9-NEXT:    v_readfirstlane_b32 s51, v1
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    v_readfirstlane_b32 s50, v0
; GFX9-NEXT:    s_cbranch_scc0 .LBB3_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB3_4
; GFX9-NEXT:  .LBB3_2: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e64 v19, s55, 1.0
; GFX9-NEXT:    v_add_f32_e64 v18, s54, 1.0
; GFX9-NEXT:    v_add_f32_e64 v17, s53, 1.0
; GFX9-NEXT:    v_add_f32_e64 v16, s52, 1.0
; GFX9-NEXT:    v_add_f32_e64 v15, s51, 1.0
; GFX9-NEXT:    v_add_f32_e64 v14, s50, 1.0
; GFX9-NEXT:    v_add_f32_e64 v13, s49, 1.0
; GFX9-NEXT:    v_add_f32_e64 v12, s48, 1.0
; GFX9-NEXT:    v_add_f32_e64 v11, s47, 1.0
; GFX9-NEXT:    v_add_f32_e64 v10, s46, 1.0
; GFX9-NEXT:    v_add_f32_e64 v9, s45, 1.0
; GFX9-NEXT:    v_add_f32_e64 v8, s44, 1.0
; GFX9-NEXT:    v_add_f32_e64 v7, s43, 1.0
; GFX9-NEXT:    v_add_f32_e64 v6, s42, 1.0
; GFX9-NEXT:    v_add_f32_e64 v5, s41, 1.0
; GFX9-NEXT:    v_add_f32_e64 v4, s40, 1.0
; GFX9-NEXT:    v_add_f32_e64 v3, s39, 1.0
; GFX9-NEXT:    v_add_f32_e64 v2, s38, 1.0
; GFX9-NEXT:    v_add_f32_e64 v1, s37, 1.0
; GFX9-NEXT:    v_add_f32_e64 v0, s36, 1.0
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_branch .LBB3_5
; GFX9-NEXT:  .LBB3_3:
; GFX9-NEXT:    s_branch .LBB3_2
; GFX9-NEXT:  .LBB3_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s36
; GFX9-NEXT:    v_mov_b32_e32 v1, s37
; GFX9-NEXT:    v_mov_b32_e32 v2, s38
; GFX9-NEXT:    v_mov_b32_e32 v3, s39
; GFX9-NEXT:    v_mov_b32_e32 v4, s40
; GFX9-NEXT:    v_mov_b32_e32 v5, s41
; GFX9-NEXT:    v_mov_b32_e32 v6, s42
; GFX9-NEXT:    v_mov_b32_e32 v7, s43
; GFX9-NEXT:    v_mov_b32_e32 v8, s44
; GFX9-NEXT:    v_mov_b32_e32 v9, s45
; GFX9-NEXT:    v_mov_b32_e32 v10, s46
; GFX9-NEXT:    v_mov_b32_e32 v11, s47
; GFX9-NEXT:    v_mov_b32_e32 v12, s48
; GFX9-NEXT:    v_mov_b32_e32 v13, s49
; GFX9-NEXT:    v_mov_b32_e32 v14, s50
; GFX9-NEXT:    v_mov_b32_e32 v15, s51
; GFX9-NEXT:    v_mov_b32_e32 v16, s52
; GFX9-NEXT:    v_mov_b32_e32 v17, s53
; GFX9-NEXT:    v_mov_b32_e32 v18, s54
; GFX9-NEXT:    v_mov_b32_e32 v19, s55
; GFX9-NEXT:    v_mov_b32_e32 v20, s56
; GFX9-NEXT:    v_mov_b32_e32 v21, s57
; GFX9-NEXT:    v_mov_b32_e32 v22, s58
; GFX9-NEXT:    v_mov_b32_e32 v23, s59
; GFX9-NEXT:    v_mov_b32_e32 v24, s60
; GFX9-NEXT:    v_mov_b32_e32 v25, s61
; GFX9-NEXT:    v_mov_b32_e32 v26, s62
; GFX9-NEXT:    v_mov_b32_e32 v27, s63
; GFX9-NEXT:    v_mov_b32_e32 v28, s64
; GFX9-NEXT:    v_mov_b32_e32 v29, s65
; GFX9-NEXT:    v_mov_b32_e32 v30, s66
; GFX9-NEXT:    v_mov_b32_e32 v31, s67
; GFX9-NEXT:  .LBB3_5: ; %end
; GFX9-NEXT:    v_readlane_b32 s55, v32, 11
; GFX9-NEXT:    v_readlane_b32 s54, v32, 10
; GFX9-NEXT:    v_readlane_b32 s53, v32, 9
; GFX9-NEXT:    v_readlane_b32 s52, v32, 8
; GFX9-NEXT:    v_readlane_b32 s51, v32, 7
; GFX9-NEXT:    v_readlane_b32 s50, v32, 6
; GFX9-NEXT:    v_readlane_b32 s49, v32, 5
; GFX9-NEXT:    v_readlane_b32 s48, v32, 4
; GFX9-NEXT:    v_readlane_b32 s39, v32, 3
; GFX9-NEXT:    v_readlane_b32 s38, v32, 2
; GFX9-NEXT:    v_readlane_b32 s37, v32, 1
; GFX9-NEXT:    v_readlane_b32 s36, v32, 0
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v20f32_to_v20i32_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_xor_saveexec_b32 s4, -1
; GFX11-NEXT:    scratch_store_b32 off, v32, s32 ; 4-byte Folded Spill
; GFX11-NEXT:    s_mov_b32 exec_lo, s4
; GFX11-NEXT:    v_writelane_b32 v32, s36, 0
; GFX11-NEXT:    v_writelane_b32 v32, s37, 1
; GFX11-NEXT:    v_writelane_b32 v32, s38, 2
; GFX11-NEXT:    v_writelane_b32 v32, s39, 3
; GFX11-NEXT:    v_writelane_b32 v32, s48, 4
; GFX11-NEXT:    v_writelane_b32 v32, s49, 5
; GFX11-NEXT:    v_writelane_b32 v32, s50, 6
; GFX11-NEXT:    v_writelane_b32 v32, s51, 7
; GFX11-NEXT:    v_writelane_b32 v32, s52, 8
; GFX11-NEXT:    v_writelane_b32 v32, s53, 9
; GFX11-NEXT:    v_writelane_b32 v32, s54, 10
; GFX11-NEXT:    v_writelane_b32 v32, s55, 11
; GFX11-NEXT:    s_mov_b32 s36, s0
; GFX11-NEXT:    v_readfirstlane_b32 s0, v2
; GFX11-NEXT:    v_readfirstlane_b32 s55, v1
; GFX11-NEXT:    v_readfirstlane_b32 s54, v0
; GFX11-NEXT:    s_mov_b32 s53, s29
; GFX11-NEXT:    s_mov_b32 s52, s28
; GFX11-NEXT:    s_mov_b32 s51, s27
; GFX11-NEXT:    s_mov_b32 s50, s26
; GFX11-NEXT:    s_mov_b32 s49, s25
; GFX11-NEXT:    s_mov_b32 s48, s24
; GFX11-NEXT:    s_mov_b32 s47, s23
; GFX11-NEXT:    s_mov_b32 s46, s22
; GFX11-NEXT:    s_mov_b32 s45, s21
; GFX11-NEXT:    s_mov_b32 s44, s20
; GFX11-NEXT:    s_mov_b32 s43, s19
; GFX11-NEXT:    s_mov_b32 s42, s18
; GFX11-NEXT:    s_mov_b32 s41, s17
; GFX11-NEXT:    s_mov_b32 s40, s16
; GFX11-NEXT:    s_mov_b32 s39, s3
; GFX11-NEXT:    s_mov_b32 s38, s2
; GFX11-NEXT:    s_mov_b32 s37, s1
; GFX11-NEXT:    s_cmp_lg_u32 s0, 0
; GFX11-NEXT:    s_mov_b32 s0, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB3_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s0
; GFX11-NEXT:    s_cbranch_vccnz .LBB3_4
; GFX11-NEXT:  .LBB3_2: ; %cmp.true
; GFX11-NEXT:    v_add_f32_e64 v19, s55, 1.0
; GFX11-NEXT:    v_add_f32_e64 v18, s54, 1.0
; GFX11-NEXT:    v_add_f32_e64 v17, s53, 1.0
; GFX11-NEXT:    v_add_f32_e64 v16, s52, 1.0
; GFX11-NEXT:    v_add_f32_e64 v15, s51, 1.0
; GFX11-NEXT:    v_add_f32_e64 v14, s50, 1.0
; GFX11-NEXT:    v_add_f32_e64 v13, s49, 1.0
; GFX11-NEXT:    v_add_f32_e64 v12, s48, 1.0
; GFX11-NEXT:    v_add_f32_e64 v11, s47, 1.0
; GFX11-NEXT:    v_add_f32_e64 v10, s46, 1.0
; GFX11-NEXT:    v_add_f32_e64 v9, s45, 1.0
; GFX11-NEXT:    v_add_f32_e64 v8, s44, 1.0
; GFX11-NEXT:    v_add_f32_e64 v7, s43, 1.0
; GFX11-NEXT:    v_add_f32_e64 v6, s42, 1.0
; GFX11-NEXT:    v_add_f32_e64 v5, s41, 1.0
; GFX11-NEXT:    v_add_f32_e64 v4, s40, 1.0
; GFX11-NEXT:    v_add_f32_e64 v3, s39, 1.0
; GFX11-NEXT:    v_add_f32_e64 v2, s38, 1.0
; GFX11-NEXT:    v_add_f32_e64 v1, s37, 1.0
; GFX11-NEXT:    v_add_f32_e64 v0, s36, 1.0
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    s_branch .LBB3_5
; GFX11-NEXT:  .LBB3_3:
; GFX11-NEXT:    s_branch .LBB3_2
; GFX11-NEXT:  .LBB3_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s36 :: v_dual_mov_b32 v1, s37
; GFX11-NEXT:    v_dual_mov_b32 v2, s38 :: v_dual_mov_b32 v3, s39
; GFX11-NEXT:    v_dual_mov_b32 v4, s40 :: v_dual_mov_b32 v5, s41
; GFX11-NEXT:    v_dual_mov_b32 v6, s42 :: v_dual_mov_b32 v7, s43
; GFX11-NEXT:    v_dual_mov_b32 v8, s44 :: v_dual_mov_b32 v9, s45
; GFX11-NEXT:    v_dual_mov_b32 v10, s46 :: v_dual_mov_b32 v11, s47
; GFX11-NEXT:    v_dual_mov_b32 v12, s48 :: v_dual_mov_b32 v13, s49
; GFX11-NEXT:    v_dual_mov_b32 v14, s50 :: v_dual_mov_b32 v15, s51
; GFX11-NEXT:    v_dual_mov_b32 v16, s52 :: v_dual_mov_b32 v17, s53
; GFX11-NEXT:    v_dual_mov_b32 v18, s54 :: v_dual_mov_b32 v19, s55
; GFX11-NEXT:    v_dual_mov_b32 v20, s56 :: v_dual_mov_b32 v21, s57
; GFX11-NEXT:    v_dual_mov_b32 v22, s58 :: v_dual_mov_b32 v23, s59
; GFX11-NEXT:    v_dual_mov_b32 v24, s60 :: v_dual_mov_b32 v25, s61
; GFX11-NEXT:    v_dual_mov_b32 v26, s62 :: v_dual_mov_b32 v27, s63
; GFX11-NEXT:    v_dual_mov_b32 v28, s64 :: v_dual_mov_b32 v29, s65
; GFX11-NEXT:    v_dual_mov_b32 v30, s66 :: v_dual_mov_b32 v31, s67
; GFX11-NEXT:  .LBB3_5: ; %end
; GFX11-NEXT:    v_readlane_b32 s55, v32, 11
; GFX11-NEXT:    v_readlane_b32 s54, v32, 10
; GFX11-NEXT:    v_readlane_b32 s53, v32, 9
; GFX11-NEXT:    v_readlane_b32 s52, v32, 8
; GFX11-NEXT:    v_readlane_b32 s51, v32, 7
; GFX11-NEXT:    v_readlane_b32 s50, v32, 6
; GFX11-NEXT:    v_readlane_b32 s49, v32, 5
; GFX11-NEXT:    v_readlane_b32 s48, v32, 4
; GFX11-NEXT:    v_readlane_b32 s39, v32, 3
; GFX11-NEXT:    v_readlane_b32 s38, v32, 2
; GFX11-NEXT:    v_readlane_b32 s37, v32, 1
; GFX11-NEXT:    v_readlane_b32 s36, v32, 0
; GFX11-NEXT:    s_xor_saveexec_b32 s0, -1
; GFX11-NEXT:    scratch_load_b32 v32, off, s32 ; 4-byte Folded Reload
; GFX11-NEXT:    s_mov_b32 exec_lo, s0
; GFX11-NEXT:    s_waitcnt vmcnt(0)
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <20 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <20 x float> %a1 to <20 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <20 x float> %a to <20 x i32>
  br label %end

end:
  %phi = phi <20 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <20 x i32> %phi
}

define <10 x i64> @bitcast_v20i32_to_v10i64(<20 x i32> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v20i32_to_v10i64:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB4_2
; SI-NEXT:  ; %bb.1: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v19, vcc, 3, v19
; SI-NEXT:    v_add_i32_e32 v18, vcc, 3, v18
; SI-NEXT:    v_add_i32_e32 v17, vcc, 3, v17
; SI-NEXT:    v_add_i32_e32 v16, vcc, 3, v16
; SI-NEXT:    v_add_i32_e32 v15, vcc, 3, v15
; SI-NEXT:    v_add_i32_e32 v14, vcc, 3, v14
; SI-NEXT:    v_add_i32_e32 v13, vcc, 3, v13
; SI-NEXT:    v_add_i32_e32 v12, vcc, 3, v12
; SI-NEXT:    v_add_i32_e32 v11, vcc, 3, v11
; SI-NEXT:    v_add_i32_e32 v10, vcc, 3, v10
; SI-NEXT:    v_add_i32_e32 v9, vcc, 3, v9
; SI-NEXT:    v_add_i32_e32 v8, vcc, 3, v8
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v7
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v5
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v3
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v1
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:  .LBB4_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v20i32_to_v10i64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB4_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v19, vcc, 3, v19
; VI-NEXT:    v_add_u32_e32 v18, vcc, 3, v18
; VI-NEXT:    v_add_u32_e32 v17, vcc, 3, v17
; VI-NEXT:    v_add_u32_e32 v16, vcc, 3, v16
; VI-NEXT:    v_add_u32_e32 v15, vcc, 3, v15
; VI-NEXT:    v_add_u32_e32 v14, vcc, 3, v14
; VI-NEXT:    v_add_u32_e32 v13, vcc, 3, v13
; VI-NEXT:    v_add_u32_e32 v12, vcc, 3, v12
; VI-NEXT:    v_add_u32_e32 v11, vcc, 3, v11
; VI-NEXT:    v_add_u32_e32 v10, vcc, 3, v10
; VI-NEXT:    v_add_u32_e32 v9, vcc, 3, v9
; VI-NEXT:    v_add_u32_e32 v8, vcc, 3, v8
; VI-NEXT:    v_add_u32_e32 v7, vcc, 3, v7
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_add_u32_e32 v5, vcc, 3, v5
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_add_u32_e32 v3, vcc, 3, v3
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_add_u32_e32 v1, vcc, 3, v1
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:  .LBB4_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v20i32_to_v10i64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB4_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_u32_e32 v19, 3, v19
; GFX9-NEXT:    v_add_u32_e32 v18, 3, v18
; GFX9-NEXT:    v_add_u32_e32 v17, 3, v17
; GFX9-NEXT:    v_add_u32_e32 v16, 3, v16
; GFX9-NEXT:    v_add_u32_e32 v15, 3, v15
; GFX9-NEXT:    v_add_u32_e32 v14, 3, v14
; GFX9-NEXT:    v_add_u32_e32 v13, 3, v13
; GFX9-NEXT:    v_add_u32_e32 v12, 3, v12
; GFX9-NEXT:    v_add_u32_e32 v11, 3, v11
; GFX9-NEXT:    v_add_u32_e32 v10, 3, v10
; GFX9-NEXT:    v_add_u32_e32 v9, 3, v9
; GFX9-NEXT:    v_add_u32_e32 v8, 3, v8
; GFX9-NEXT:    v_add_u32_e32 v7, 3, v7
; GFX9-NEXT:    v_add_u32_e32 v6, 3, v6
; GFX9-NEXT:    v_add_u32_e32 v5, 3, v5
; GFX9-NEXT:    v_add_u32_e32 v4, 3, v4
; GFX9-NEXT:    v_add_u32_e32 v3, 3, v3
; GFX9-NEXT:    v_add_u32_e32 v2, 3, v2
; GFX9-NEXT:    v_add_u32_e32 v1, 3, v1
; GFX9-NEXT:    v_add_u32_e32 v0, 3, v0
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:  .LBB4_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v20i32_to_v10i64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB4_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_nc_u32_e32 v19, 3, v19
; GFX11-NEXT:    v_add_nc_u32_e32 v18, 3, v18
; GFX11-NEXT:    v_add_nc_u32_e32 v17, 3, v17
; GFX11-NEXT:    v_add_nc_u32_e32 v16, 3, v16
; GFX11-NEXT:    v_add_nc_u32_e32 v15, 3, v15
; GFX11-NEXT:    v_add_nc_u32_e32 v14, 3, v14
; GFX11-NEXT:    v_add_nc_u32_e32 v13, 3, v13
; GFX11-NEXT:    v_add_nc_u32_e32 v12, 3, v12
; GFX11-NEXT:    v_add_nc_u32_e32 v11, 3, v11
; GFX11-NEXT:    v_add_nc_u32_e32 v10, 3, v10
; GFX11-NEXT:    v_add_nc_u32_e32 v9, 3, v9
; GFX11-NEXT:    v_add_nc_u32_e32 v8, 3, v8
; GFX11-NEXT:    v_add_nc_u32_e32 v7, 3, v7
; GFX11-NEXT:    v_add_nc_u32_e32 v6, 3, v6
; GFX11-NEXT:    v_add_nc_u32_e32 v5, 3, v5
; GFX11-NEXT:    v_add_nc_u32_e32 v4, 3, v4
; GFX11-NEXT:    v_add_nc_u32_e32 v3, 3, v3
; GFX11-NEXT:    v_add_nc_u32_e32 v2, 3, v2
; GFX11-NEXT:    v_add_nc_u32_e32 v1, 3, v1
; GFX11-NEXT:    v_add_nc_u32_e32 v0, 3, v0
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:  .LBB4_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <20 x i32> %a, splat (i32 3)
  %a2 = bitcast <20 x i32> %a1 to <10 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <20 x i32> %a to <10 x i64>
  br label %end

end:
  %phi = phi <10 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <10 x i64> %phi
}

define inreg <10 x i64> @bitcast_v20i32_to_v10i64_scalar(<20 x i32> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v20i32_to_v10i64_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_readfirstlane_b32 s4, v6
; SI-NEXT:    v_readfirstlane_b32 s6, v5
; SI-NEXT:    v_readfirstlane_b32 s7, v4
; SI-NEXT:    v_readfirstlane_b32 s8, v3
; SI-NEXT:    v_readfirstlane_b32 s9, v2
; SI-NEXT:    v_readfirstlane_b32 s10, v1
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    v_readfirstlane_b32 s11, v0
; SI-NEXT:    s_cbranch_scc0 .LBB5_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_cbranch_execnz .LBB5_3
; SI-NEXT:  .LBB5_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s6, s6, 3
; SI-NEXT:    s_add_i32 s7, s7, 3
; SI-NEXT:    s_add_i32 s8, s8, 3
; SI-NEXT:    s_add_i32 s9, s9, 3
; SI-NEXT:    s_add_i32 s10, s10, 3
; SI-NEXT:    s_add_i32 s11, s11, 3
; SI-NEXT:    s_add_i32 s29, s29, 3
; SI-NEXT:    s_add_i32 s28, s28, 3
; SI-NEXT:    s_add_i32 s27, s27, 3
; SI-NEXT:    s_add_i32 s26, s26, 3
; SI-NEXT:    s_add_i32 s25, s25, 3
; SI-NEXT:    s_add_i32 s24, s24, 3
; SI-NEXT:    s_add_i32 s23, s23, 3
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_add_i32 s21, s21, 3
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_add_i32 s19, s19, 3
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_add_i32 s17, s17, 3
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:  .LBB5_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v2, s18
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v4, s20
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v6, s22
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    v_mov_b32_e32 v8, s24
; SI-NEXT:    v_mov_b32_e32 v9, s25
; SI-NEXT:    v_mov_b32_e32 v10, s26
; SI-NEXT:    v_mov_b32_e32 v11, s27
; SI-NEXT:    v_mov_b32_e32 v12, s28
; SI-NEXT:    v_mov_b32_e32 v13, s29
; SI-NEXT:    v_mov_b32_e32 v14, s11
; SI-NEXT:    v_mov_b32_e32 v15, s10
; SI-NEXT:    v_mov_b32_e32 v16, s9
; SI-NEXT:    v_mov_b32_e32 v17, s8
; SI-NEXT:    v_mov_b32_e32 v18, s7
; SI-NEXT:    v_mov_b32_e32 v19, s6
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB5_4:
; SI-NEXT:    s_branch .LBB5_2
;
; VI-LABEL: bitcast_v20i32_to_v10i64_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    v_readfirstlane_b32 s6, v5
; VI-NEXT:    v_readfirstlane_b32 s7, v4
; VI-NEXT:    v_readfirstlane_b32 s8, v3
; VI-NEXT:    v_readfirstlane_b32 s9, v2
; VI-NEXT:    v_readfirstlane_b32 s10, v1
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    v_readfirstlane_b32 s11, v0
; VI-NEXT:    s_cbranch_scc0 .LBB5_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB5_3
; VI-NEXT:  .LBB5_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s6, s6, 3
; VI-NEXT:    s_add_i32 s7, s7, 3
; VI-NEXT:    s_add_i32 s8, s8, 3
; VI-NEXT:    s_add_i32 s9, s9, 3
; VI-NEXT:    s_add_i32 s10, s10, 3
; VI-NEXT:    s_add_i32 s11, s11, 3
; VI-NEXT:    s_add_i32 s29, s29, 3
; VI-NEXT:    s_add_i32 s28, s28, 3
; VI-NEXT:    s_add_i32 s27, s27, 3
; VI-NEXT:    s_add_i32 s26, s26, 3
; VI-NEXT:    s_add_i32 s25, s25, 3
; VI-NEXT:    s_add_i32 s24, s24, 3
; VI-NEXT:    s_add_i32 s23, s23, 3
; VI-NEXT:    s_add_i32 s22, s22, 3
; VI-NEXT:    s_add_i32 s21, s21, 3
; VI-NEXT:    s_add_i32 s20, s20, 3
; VI-NEXT:    s_add_i32 s19, s19, 3
; VI-NEXT:    s_add_i32 s18, s18, 3
; VI-NEXT:    s_add_i32 s17, s17, 3
; VI-NEXT:    s_add_i32 s16, s16, 3
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:  .LBB5_3: ; %end
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    v_mov_b32_e32 v8, s24
; VI-NEXT:    v_mov_b32_e32 v9, s25
; VI-NEXT:    v_mov_b32_e32 v10, s26
; VI-NEXT:    v_mov_b32_e32 v11, s27
; VI-NEXT:    v_mov_b32_e32 v12, s28
; VI-NEXT:    v_mov_b32_e32 v13, s29
; VI-NEXT:    v_mov_b32_e32 v14, s11
; VI-NEXT:    v_mov_b32_e32 v15, s10
; VI-NEXT:    v_mov_b32_e32 v16, s9
; VI-NEXT:    v_mov_b32_e32 v17, s8
; VI-NEXT:    v_mov_b32_e32 v18, s7
; VI-NEXT:    v_mov_b32_e32 v19, s6
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB5_4:
; VI-NEXT:    s_branch .LBB5_2
;
; GFX9-LABEL: bitcast_v20i32_to_v10i64_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_readfirstlane_b32 s4, v6
; GFX9-NEXT:    v_readfirstlane_b32 s6, v5
; GFX9-NEXT:    v_readfirstlane_b32 s7, v4
; GFX9-NEXT:    v_readfirstlane_b32 s8, v3
; GFX9-NEXT:    v_readfirstlane_b32 s9, v2
; GFX9-NEXT:    v_readfirstlane_b32 s10, v1
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    v_readfirstlane_b32 s11, v0
; GFX9-NEXT:    s_cbranch_scc0 .LBB5_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB5_3
; GFX9-NEXT:  .LBB5_2: ; %cmp.true
; GFX9-NEXT:    s_add_i32 s6, s6, 3
; GFX9-NEXT:    s_add_i32 s7, s7, 3
; GFX9-NEXT:    s_add_i32 s8, s8, 3
; GFX9-NEXT:    s_add_i32 s9, s9, 3
; GFX9-NEXT:    s_add_i32 s10, s10, 3
; GFX9-NEXT:    s_add_i32 s11, s11, 3
; GFX9-NEXT:    s_add_i32 s29, s29, 3
; GFX9-NEXT:    s_add_i32 s28, s28, 3
; GFX9-NEXT:    s_add_i32 s27, s27, 3
; GFX9-NEXT:    s_add_i32 s26, s26, 3
; GFX9-NEXT:    s_add_i32 s25, s25, 3
; GFX9-NEXT:    s_add_i32 s24, s24, 3
; GFX9-NEXT:    s_add_i32 s23, s23, 3
; GFX9-NEXT:    s_add_i32 s22, s22, 3
; GFX9-NEXT:    s_add_i32 s21, s21, 3
; GFX9-NEXT:    s_add_i32 s20, s20, 3
; GFX9-NEXT:    s_add_i32 s19, s19, 3
; GFX9-NEXT:    s_add_i32 s18, s18, 3
; GFX9-NEXT:    s_add_i32 s17, s17, 3
; GFX9-NEXT:    s_add_i32 s16, s16, 3
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:  .LBB5_3: ; %end
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    v_mov_b32_e32 v8, s24
; GFX9-NEXT:    v_mov_b32_e32 v9, s25
; GFX9-NEXT:    v_mov_b32_e32 v10, s26
; GFX9-NEXT:    v_mov_b32_e32 v11, s27
; GFX9-NEXT:    v_mov_b32_e32 v12, s28
; GFX9-NEXT:    v_mov_b32_e32 v13, s29
; GFX9-NEXT:    v_mov_b32_e32 v14, s11
; GFX9-NEXT:    v_mov_b32_e32 v15, s10
; GFX9-NEXT:    v_mov_b32_e32 v16, s9
; GFX9-NEXT:    v_mov_b32_e32 v17, s8
; GFX9-NEXT:    v_mov_b32_e32 v18, s7
; GFX9-NEXT:    v_mov_b32_e32 v19, s6
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB5_4:
; GFX9-NEXT:    s_branch .LBB5_2
;
; GFX11-LABEL: bitcast_v20i32_to_v10i64_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    v_readfirstlane_b32 s6, v2
; GFX11-NEXT:    v_readfirstlane_b32 s4, v1
; GFX11-NEXT:    v_readfirstlane_b32 s5, v0
; GFX11-NEXT:    s_cmp_lg_u32 s6, 0
; GFX11-NEXT:    s_mov_b32 s6, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB5_4
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s6
; GFX11-NEXT:    s_cbranch_vccnz .LBB5_3
; GFX11-NEXT:  .LBB5_2: ; %cmp.true
; GFX11-NEXT:    s_add_i32 s4, s4, 3
; GFX11-NEXT:    s_add_i32 s5, s5, 3
; GFX11-NEXT:    s_add_i32 s29, s29, 3
; GFX11-NEXT:    s_add_i32 s28, s28, 3
; GFX11-NEXT:    s_add_i32 s27, s27, 3
; GFX11-NEXT:    s_add_i32 s26, s26, 3
; GFX11-NEXT:    s_add_i32 s25, s25, 3
; GFX11-NEXT:    s_add_i32 s24, s24, 3
; GFX11-NEXT:    s_add_i32 s23, s23, 3
; GFX11-NEXT:    s_add_i32 s22, s22, 3
; GFX11-NEXT:    s_add_i32 s21, s21, 3
; GFX11-NEXT:    s_add_i32 s20, s20, 3
; GFX11-NEXT:    s_add_i32 s19, s19, 3
; GFX11-NEXT:    s_add_i32 s18, s18, 3
; GFX11-NEXT:    s_add_i32 s17, s17, 3
; GFX11-NEXT:    s_add_i32 s16, s16, 3
; GFX11-NEXT:    s_add_i32 s3, s3, 3
; GFX11-NEXT:    s_add_i32 s2, s2, 3
; GFX11-NEXT:    s_add_i32 s1, s1, 3
; GFX11-NEXT:    s_add_i32 s0, s0, 3
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:  .LBB5_3: ; %end
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s16 :: v_dual_mov_b32 v5, s17
; GFX11-NEXT:    v_dual_mov_b32 v6, s18 :: v_dual_mov_b32 v7, s19
; GFX11-NEXT:    v_dual_mov_b32 v8, s20 :: v_dual_mov_b32 v9, s21
; GFX11-NEXT:    v_dual_mov_b32 v10, s22 :: v_dual_mov_b32 v11, s23
; GFX11-NEXT:    v_dual_mov_b32 v12, s24 :: v_dual_mov_b32 v13, s25
; GFX11-NEXT:    v_dual_mov_b32 v14, s26 :: v_dual_mov_b32 v15, s27
; GFX11-NEXT:    v_dual_mov_b32 v16, s28 :: v_dual_mov_b32 v17, s29
; GFX11-NEXT:    v_dual_mov_b32 v18, s5 :: v_dual_mov_b32 v19, s4
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB5_4:
; GFX11-NEXT:    s_branch .LBB5_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <20 x i32> %a, splat (i32 3)
  %a2 = bitcast <20 x i32> %a1 to <10 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <20 x i32> %a to <10 x i64>
  br label %end

end:
  %phi = phi <10 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <10 x i64> %phi
}

define <20 x i32> @bitcast_v10i64_to_v20i32(<10 x i64> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v10i64_to_v20i32:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB6_2
; SI-NEXT:  ; %bb.1: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v18, vcc, 3, v18
; SI-NEXT:    v_addc_u32_e32 v19, vcc, 0, v19, vcc
; SI-NEXT:    v_add_i32_e32 v16, vcc, 3, v16
; SI-NEXT:    v_addc_u32_e32 v17, vcc, 0, v17, vcc
; SI-NEXT:    v_add_i32_e32 v14, vcc, 3, v14
; SI-NEXT:    v_addc_u32_e32 v15, vcc, 0, v15, vcc
; SI-NEXT:    v_add_i32_e32 v12, vcc, 3, v12
; SI-NEXT:    v_addc_u32_e32 v13, vcc, 0, v13, vcc
; SI-NEXT:    v_add_i32_e32 v10, vcc, 3, v10
; SI-NEXT:    v_addc_u32_e32 v11, vcc, 0, v11, vcc
; SI-NEXT:    v_add_i32_e32 v8, vcc, 3, v8
; SI-NEXT:    v_addc_u32_e32 v9, vcc, 0, v9, vcc
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; SI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; SI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; SI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:  .LBB6_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v10i64_to_v20i32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB6_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v18, vcc, 3, v18
; VI-NEXT:    v_addc_u32_e32 v19, vcc, 0, v19, vcc
; VI-NEXT:    v_add_u32_e32 v16, vcc, 3, v16
; VI-NEXT:    v_addc_u32_e32 v17, vcc, 0, v17, vcc
; VI-NEXT:    v_add_u32_e32 v14, vcc, 3, v14
; VI-NEXT:    v_addc_u32_e32 v15, vcc, 0, v15, vcc
; VI-NEXT:    v_add_u32_e32 v12, vcc, 3, v12
; VI-NEXT:    v_addc_u32_e32 v13, vcc, 0, v13, vcc
; VI-NEXT:    v_add_u32_e32 v10, vcc, 3, v10
; VI-NEXT:    v_addc_u32_e32 v11, vcc, 0, v11, vcc
; VI-NEXT:    v_add_u32_e32 v8, vcc, 3, v8
; VI-NEXT:    v_addc_u32_e32 v9, vcc, 0, v9, vcc
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:  .LBB6_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v10i64_to_v20i32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB6_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_co_u32_e32 v18, vcc, 3, v18
; GFX9-NEXT:    v_addc_co_u32_e32 v19, vcc, 0, v19, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v16, vcc, 3, v16
; GFX9-NEXT:    v_addc_co_u32_e32 v17, vcc, 0, v17, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v14, vcc, 3, v14
; GFX9-NEXT:    v_addc_co_u32_e32 v15, vcc, 0, v15, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v12, vcc, 3, v12
; GFX9-NEXT:    v_addc_co_u32_e32 v13, vcc, 0, v13, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v10, vcc, 3, v10
; GFX9-NEXT:    v_addc_co_u32_e32 v11, vcc, 0, v11, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v8, vcc, 3, v8
; GFX9-NEXT:    v_addc_co_u32_e32 v9, vcc, 0, v9, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v6, vcc, 3, v6
; GFX9-NEXT:    v_addc_co_u32_e32 v7, vcc, 0, v7, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v4, vcc, 3, v4
; GFX9-NEXT:    v_addc_co_u32_e32 v5, vcc, 0, v5, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v2, vcc, 3, v2
; GFX9-NEXT:    v_addc_co_u32_e32 v3, vcc, 0, v3, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v0, vcc, 3, v0
; GFX9-NEXT:    v_addc_co_u32_e32 v1, vcc, 0, v1, vcc
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:  .LBB6_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v10i64_to_v20i32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB6_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_co_u32 v18, vcc_lo, v18, 3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_co_ci_u32_e64 v19, null, 0, v19, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v16, vcc_lo, v16, 3
; GFX11-NEXT:    v_add_co_ci_u32_e64 v17, null, 0, v17, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v14, vcc_lo, v14, 3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_co_ci_u32_e64 v15, null, 0, v15, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v12, vcc_lo, v12, 3
; GFX11-NEXT:    v_add_co_ci_u32_e64 v13, null, 0, v13, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v10, vcc_lo, v10, 3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_co_ci_u32_e64 v11, null, 0, v11, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v8, vcc_lo, v8, 3
; GFX11-NEXT:    v_add_co_ci_u32_e64 v9, null, 0, v9, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v6, vcc_lo, v6, 3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_co_ci_u32_e64 v7, null, 0, v7, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v4, vcc_lo, v4, 3
; GFX11-NEXT:    v_add_co_ci_u32_e64 v5, null, 0, v5, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v2, vcc_lo, v2, 3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_co_ci_u32_e64 v3, null, 0, v3, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v0, vcc_lo, v0, 3
; GFX11-NEXT:    v_add_co_ci_u32_e64 v1, null, 0, v1, vcc_lo
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:  .LBB6_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <10 x i64> %a, splat (i64 3)
  %a2 = bitcast <10 x i64> %a1 to <20 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <10 x i64> %a to <20 x i32>
  br label %end

end:
  %phi = phi <20 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <20 x i32> %phi
}

define inreg <20 x i32> @bitcast_v10i64_to_v20i32_scalar(<10 x i64> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v10i64_to_v20i32_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_readfirstlane_b32 s4, v6
; SI-NEXT:    v_readfirstlane_b32 s6, v5
; SI-NEXT:    v_readfirstlane_b32 s7, v4
; SI-NEXT:    v_readfirstlane_b32 s8, v3
; SI-NEXT:    v_readfirstlane_b32 s9, v2
; SI-NEXT:    v_readfirstlane_b32 s10, v1
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    v_readfirstlane_b32 s11, v0
; SI-NEXT:    s_cbranch_scc0 .LBB7_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_cbranch_execnz .LBB7_3
; SI-NEXT:  .LBB7_2: ; %cmp.true
; SI-NEXT:    s_add_u32 s7, s7, 3
; SI-NEXT:    s_addc_u32 s6, s6, 0
; SI-NEXT:    s_add_u32 s9, s9, 3
; SI-NEXT:    s_addc_u32 s8, s8, 0
; SI-NEXT:    s_add_u32 s11, s11, 3
; SI-NEXT:    s_addc_u32 s10, s10, 0
; SI-NEXT:    s_add_u32 s28, s28, 3
; SI-NEXT:    s_addc_u32 s29, s29, 0
; SI-NEXT:    s_add_u32 s26, s26, 3
; SI-NEXT:    s_addc_u32 s27, s27, 0
; SI-NEXT:    s_add_u32 s24, s24, 3
; SI-NEXT:    s_addc_u32 s25, s25, 0
; SI-NEXT:    s_add_u32 s22, s22, 3
; SI-NEXT:    s_addc_u32 s23, s23, 0
; SI-NEXT:    s_add_u32 s20, s20, 3
; SI-NEXT:    s_addc_u32 s21, s21, 0
; SI-NEXT:    s_add_u32 s18, s18, 3
; SI-NEXT:    s_addc_u32 s19, s19, 0
; SI-NEXT:    s_add_u32 s16, s16, 3
; SI-NEXT:    s_addc_u32 s17, s17, 0
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:  .LBB7_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v2, s18
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v4, s20
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v6, s22
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    v_mov_b32_e32 v8, s24
; SI-NEXT:    v_mov_b32_e32 v9, s25
; SI-NEXT:    v_mov_b32_e32 v10, s26
; SI-NEXT:    v_mov_b32_e32 v11, s27
; SI-NEXT:    v_mov_b32_e32 v12, s28
; SI-NEXT:    v_mov_b32_e32 v13, s29
; SI-NEXT:    v_mov_b32_e32 v14, s11
; SI-NEXT:    v_mov_b32_e32 v15, s10
; SI-NEXT:    v_mov_b32_e32 v16, s9
; SI-NEXT:    v_mov_b32_e32 v17, s8
; SI-NEXT:    v_mov_b32_e32 v18, s7
; SI-NEXT:    v_mov_b32_e32 v19, s6
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB7_4:
; SI-NEXT:    s_branch .LBB7_2
;
; VI-LABEL: bitcast_v10i64_to_v20i32_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    v_readfirstlane_b32 s6, v5
; VI-NEXT:    v_readfirstlane_b32 s7, v4
; VI-NEXT:    v_readfirstlane_b32 s8, v3
; VI-NEXT:    v_readfirstlane_b32 s9, v2
; VI-NEXT:    v_readfirstlane_b32 s10, v1
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    v_readfirstlane_b32 s11, v0
; VI-NEXT:    s_cbranch_scc0 .LBB7_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB7_3
; VI-NEXT:  .LBB7_2: ; %cmp.true
; VI-NEXT:    s_add_u32 s7, s7, 3
; VI-NEXT:    s_addc_u32 s6, s6, 0
; VI-NEXT:    s_add_u32 s9, s9, 3
; VI-NEXT:    s_addc_u32 s8, s8, 0
; VI-NEXT:    s_add_u32 s11, s11, 3
; VI-NEXT:    s_addc_u32 s10, s10, 0
; VI-NEXT:    s_add_u32 s28, s28, 3
; VI-NEXT:    s_addc_u32 s29, s29, 0
; VI-NEXT:    s_add_u32 s26, s26, 3
; VI-NEXT:    s_addc_u32 s27, s27, 0
; VI-NEXT:    s_add_u32 s24, s24, 3
; VI-NEXT:    s_addc_u32 s25, s25, 0
; VI-NEXT:    s_add_u32 s22, s22, 3
; VI-NEXT:    s_addc_u32 s23, s23, 0
; VI-NEXT:    s_add_u32 s20, s20, 3
; VI-NEXT:    s_addc_u32 s21, s21, 0
; VI-NEXT:    s_add_u32 s18, s18, 3
; VI-NEXT:    s_addc_u32 s19, s19, 0
; VI-NEXT:    s_add_u32 s16, s16, 3
; VI-NEXT:    s_addc_u32 s17, s17, 0
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:  .LBB7_3: ; %end
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    v_mov_b32_e32 v8, s24
; VI-NEXT:    v_mov_b32_e32 v9, s25
; VI-NEXT:    v_mov_b32_e32 v10, s26
; VI-NEXT:    v_mov_b32_e32 v11, s27
; VI-NEXT:    v_mov_b32_e32 v12, s28
; VI-NEXT:    v_mov_b32_e32 v13, s29
; VI-NEXT:    v_mov_b32_e32 v14, s11
; VI-NEXT:    v_mov_b32_e32 v15, s10
; VI-NEXT:    v_mov_b32_e32 v16, s9
; VI-NEXT:    v_mov_b32_e32 v17, s8
; VI-NEXT:    v_mov_b32_e32 v18, s7
; VI-NEXT:    v_mov_b32_e32 v19, s6
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB7_4:
; VI-NEXT:    s_branch .LBB7_2
;
; GFX9-LABEL: bitcast_v10i64_to_v20i32_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_readfirstlane_b32 s4, v6
; GFX9-NEXT:    v_readfirstlane_b32 s6, v5
; GFX9-NEXT:    v_readfirstlane_b32 s7, v4
; GFX9-NEXT:    v_readfirstlane_b32 s8, v3
; GFX9-NEXT:    v_readfirstlane_b32 s9, v2
; GFX9-NEXT:    v_readfirstlane_b32 s10, v1
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    v_readfirstlane_b32 s11, v0
; GFX9-NEXT:    s_cbranch_scc0 .LBB7_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB7_3
; GFX9-NEXT:  .LBB7_2: ; %cmp.true
; GFX9-NEXT:    s_add_u32 s7, s7, 3
; GFX9-NEXT:    s_addc_u32 s6, s6, 0
; GFX9-NEXT:    s_add_u32 s9, s9, 3
; GFX9-NEXT:    s_addc_u32 s8, s8, 0
; GFX9-NEXT:    s_add_u32 s11, s11, 3
; GFX9-NEXT:    s_addc_u32 s10, s10, 0
; GFX9-NEXT:    s_add_u32 s28, s28, 3
; GFX9-NEXT:    s_addc_u32 s29, s29, 0
; GFX9-NEXT:    s_add_u32 s26, s26, 3
; GFX9-NEXT:    s_addc_u32 s27, s27, 0
; GFX9-NEXT:    s_add_u32 s24, s24, 3
; GFX9-NEXT:    s_addc_u32 s25, s25, 0
; GFX9-NEXT:    s_add_u32 s22, s22, 3
; GFX9-NEXT:    s_addc_u32 s23, s23, 0
; GFX9-NEXT:    s_add_u32 s20, s20, 3
; GFX9-NEXT:    s_addc_u32 s21, s21, 0
; GFX9-NEXT:    s_add_u32 s18, s18, 3
; GFX9-NEXT:    s_addc_u32 s19, s19, 0
; GFX9-NEXT:    s_add_u32 s16, s16, 3
; GFX9-NEXT:    s_addc_u32 s17, s17, 0
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:  .LBB7_3: ; %end
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    v_mov_b32_e32 v8, s24
; GFX9-NEXT:    v_mov_b32_e32 v9, s25
; GFX9-NEXT:    v_mov_b32_e32 v10, s26
; GFX9-NEXT:    v_mov_b32_e32 v11, s27
; GFX9-NEXT:    v_mov_b32_e32 v12, s28
; GFX9-NEXT:    v_mov_b32_e32 v13, s29
; GFX9-NEXT:    v_mov_b32_e32 v14, s11
; GFX9-NEXT:    v_mov_b32_e32 v15, s10
; GFX9-NEXT:    v_mov_b32_e32 v16, s9
; GFX9-NEXT:    v_mov_b32_e32 v17, s8
; GFX9-NEXT:    v_mov_b32_e32 v18, s7
; GFX9-NEXT:    v_mov_b32_e32 v19, s6
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB7_4:
; GFX9-NEXT:    s_branch .LBB7_2
;
; GFX11-LABEL: bitcast_v10i64_to_v20i32_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    v_readfirstlane_b32 s6, v2
; GFX11-NEXT:    v_readfirstlane_b32 s4, v1
; GFX11-NEXT:    v_readfirstlane_b32 s5, v0
; GFX11-NEXT:    s_cmp_lg_u32 s6, 0
; GFX11-NEXT:    s_mov_b32 s6, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB7_4
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s6
; GFX11-NEXT:    s_cbranch_vccnz .LBB7_3
; GFX11-NEXT:  .LBB7_2: ; %cmp.true
; GFX11-NEXT:    s_add_u32 s5, s5, 3
; GFX11-NEXT:    s_addc_u32 s4, s4, 0
; GFX11-NEXT:    s_add_u32 s28, s28, 3
; GFX11-NEXT:    s_addc_u32 s29, s29, 0
; GFX11-NEXT:    s_add_u32 s26, s26, 3
; GFX11-NEXT:    s_addc_u32 s27, s27, 0
; GFX11-NEXT:    s_add_u32 s24, s24, 3
; GFX11-NEXT:    s_addc_u32 s25, s25, 0
; GFX11-NEXT:    s_add_u32 s22, s22, 3
; GFX11-NEXT:    s_addc_u32 s23, s23, 0
; GFX11-NEXT:    s_add_u32 s20, s20, 3
; GFX11-NEXT:    s_addc_u32 s21, s21, 0
; GFX11-NEXT:    s_add_u32 s18, s18, 3
; GFX11-NEXT:    s_addc_u32 s19, s19, 0
; GFX11-NEXT:    s_add_u32 s16, s16, 3
; GFX11-NEXT:    s_addc_u32 s17, s17, 0
; GFX11-NEXT:    s_add_u32 s2, s2, 3
; GFX11-NEXT:    s_addc_u32 s3, s3, 0
; GFX11-NEXT:    s_add_u32 s0, s0, 3
; GFX11-NEXT:    s_addc_u32 s1, s1, 0
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:  .LBB7_3: ; %end
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s16 :: v_dual_mov_b32 v5, s17
; GFX11-NEXT:    v_dual_mov_b32 v6, s18 :: v_dual_mov_b32 v7, s19
; GFX11-NEXT:    v_dual_mov_b32 v8, s20 :: v_dual_mov_b32 v9, s21
; GFX11-NEXT:    v_dual_mov_b32 v10, s22 :: v_dual_mov_b32 v11, s23
; GFX11-NEXT:    v_dual_mov_b32 v12, s24 :: v_dual_mov_b32 v13, s25
; GFX11-NEXT:    v_dual_mov_b32 v14, s26 :: v_dual_mov_b32 v15, s27
; GFX11-NEXT:    v_dual_mov_b32 v16, s28 :: v_dual_mov_b32 v17, s29
; GFX11-NEXT:    v_dual_mov_b32 v18, s5 :: v_dual_mov_b32 v19, s4
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB7_4:
; GFX11-NEXT:    s_branch .LBB7_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <10 x i64> %a, splat (i64 3)
  %a2 = bitcast <10 x i64> %a1 to <20 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <10 x i64> %a to <20 x i32>
  br label %end

end:
  %phi = phi <20 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <20 x i32> %phi
}

define <10 x double> @bitcast_v20i32_to_v10f64(<20 x i32> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v20i32_to_v10f64:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB8_2
; SI-NEXT:  ; %bb.1: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v19, vcc, 3, v19
; SI-NEXT:    v_add_i32_e32 v18, vcc, 3, v18
; SI-NEXT:    v_add_i32_e32 v17, vcc, 3, v17
; SI-NEXT:    v_add_i32_e32 v16, vcc, 3, v16
; SI-NEXT:    v_add_i32_e32 v15, vcc, 3, v15
; SI-NEXT:    v_add_i32_e32 v14, vcc, 3, v14
; SI-NEXT:    v_add_i32_e32 v13, vcc, 3, v13
; SI-NEXT:    v_add_i32_e32 v12, vcc, 3, v12
; SI-NEXT:    v_add_i32_e32 v11, vcc, 3, v11
; SI-NEXT:    v_add_i32_e32 v10, vcc, 3, v10
; SI-NEXT:    v_add_i32_e32 v9, vcc, 3, v9
; SI-NEXT:    v_add_i32_e32 v8, vcc, 3, v8
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v7
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v5
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v3
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v1
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:  .LBB8_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v20i32_to_v10f64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB8_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v19, vcc, 3, v19
; VI-NEXT:    v_add_u32_e32 v18, vcc, 3, v18
; VI-NEXT:    v_add_u32_e32 v17, vcc, 3, v17
; VI-NEXT:    v_add_u32_e32 v16, vcc, 3, v16
; VI-NEXT:    v_add_u32_e32 v15, vcc, 3, v15
; VI-NEXT:    v_add_u32_e32 v14, vcc, 3, v14
; VI-NEXT:    v_add_u32_e32 v13, vcc, 3, v13
; VI-NEXT:    v_add_u32_e32 v12, vcc, 3, v12
; VI-NEXT:    v_add_u32_e32 v11, vcc, 3, v11
; VI-NEXT:    v_add_u32_e32 v10, vcc, 3, v10
; VI-NEXT:    v_add_u32_e32 v9, vcc, 3, v9
; VI-NEXT:    v_add_u32_e32 v8, vcc, 3, v8
; VI-NEXT:    v_add_u32_e32 v7, vcc, 3, v7
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_add_u32_e32 v5, vcc, 3, v5
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_add_u32_e32 v3, vcc, 3, v3
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_add_u32_e32 v1, vcc, 3, v1
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:  .LBB8_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v20i32_to_v10f64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB8_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_u32_e32 v19, 3, v19
; GFX9-NEXT:    v_add_u32_e32 v18, 3, v18
; GFX9-NEXT:    v_add_u32_e32 v17, 3, v17
; GFX9-NEXT:    v_add_u32_e32 v16, 3, v16
; GFX9-NEXT:    v_add_u32_e32 v15, 3, v15
; GFX9-NEXT:    v_add_u32_e32 v14, 3, v14
; GFX9-NEXT:    v_add_u32_e32 v13, 3, v13
; GFX9-NEXT:    v_add_u32_e32 v12, 3, v12
; GFX9-NEXT:    v_add_u32_e32 v11, 3, v11
; GFX9-NEXT:    v_add_u32_e32 v10, 3, v10
; GFX9-NEXT:    v_add_u32_e32 v9, 3, v9
; GFX9-NEXT:    v_add_u32_e32 v8, 3, v8
; GFX9-NEXT:    v_add_u32_e32 v7, 3, v7
; GFX9-NEXT:    v_add_u32_e32 v6, 3, v6
; GFX9-NEXT:    v_add_u32_e32 v5, 3, v5
; GFX9-NEXT:    v_add_u32_e32 v4, 3, v4
; GFX9-NEXT:    v_add_u32_e32 v3, 3, v3
; GFX9-NEXT:    v_add_u32_e32 v2, 3, v2
; GFX9-NEXT:    v_add_u32_e32 v1, 3, v1
; GFX9-NEXT:    v_add_u32_e32 v0, 3, v0
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:  .LBB8_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v20i32_to_v10f64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB8_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_nc_u32_e32 v19, 3, v19
; GFX11-NEXT:    v_add_nc_u32_e32 v18, 3, v18
; GFX11-NEXT:    v_add_nc_u32_e32 v17, 3, v17
; GFX11-NEXT:    v_add_nc_u32_e32 v16, 3, v16
; GFX11-NEXT:    v_add_nc_u32_e32 v15, 3, v15
; GFX11-NEXT:    v_add_nc_u32_e32 v14, 3, v14
; GFX11-NEXT:    v_add_nc_u32_e32 v13, 3, v13
; GFX11-NEXT:    v_add_nc_u32_e32 v12, 3, v12
; GFX11-NEXT:    v_add_nc_u32_e32 v11, 3, v11
; GFX11-NEXT:    v_add_nc_u32_e32 v10, 3, v10
; GFX11-NEXT:    v_add_nc_u32_e32 v9, 3, v9
; GFX11-NEXT:    v_add_nc_u32_e32 v8, 3, v8
; GFX11-NEXT:    v_add_nc_u32_e32 v7, 3, v7
; GFX11-NEXT:    v_add_nc_u32_e32 v6, 3, v6
; GFX11-NEXT:    v_add_nc_u32_e32 v5, 3, v5
; GFX11-NEXT:    v_add_nc_u32_e32 v4, 3, v4
; GFX11-NEXT:    v_add_nc_u32_e32 v3, 3, v3
; GFX11-NEXT:    v_add_nc_u32_e32 v2, 3, v2
; GFX11-NEXT:    v_add_nc_u32_e32 v1, 3, v1
; GFX11-NEXT:    v_add_nc_u32_e32 v0, 3, v0
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:  .LBB8_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <20 x i32> %a, splat (i32 3)
  %a2 = bitcast <20 x i32> %a1 to <10 x double>
  br label %end

cmp.false:
  %a3 = bitcast <20 x i32> %a to <10 x double>
  br label %end

end:
  %phi = phi <10 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <10 x double> %phi
}

define inreg <10 x double> @bitcast_v20i32_to_v10f64_scalar(<20 x i32> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v20i32_to_v10f64_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_readfirstlane_b32 s4, v6
; SI-NEXT:    v_readfirstlane_b32 s6, v5
; SI-NEXT:    v_readfirstlane_b32 s7, v4
; SI-NEXT:    v_readfirstlane_b32 s8, v3
; SI-NEXT:    v_readfirstlane_b32 s9, v2
; SI-NEXT:    v_readfirstlane_b32 s10, v1
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    v_readfirstlane_b32 s11, v0
; SI-NEXT:    s_cbranch_scc0 .LBB9_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_cbranch_execnz .LBB9_3
; SI-NEXT:  .LBB9_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s6, s6, 3
; SI-NEXT:    s_add_i32 s7, s7, 3
; SI-NEXT:    s_add_i32 s8, s8, 3
; SI-NEXT:    s_add_i32 s9, s9, 3
; SI-NEXT:    s_add_i32 s10, s10, 3
; SI-NEXT:    s_add_i32 s11, s11, 3
; SI-NEXT:    s_add_i32 s29, s29, 3
; SI-NEXT:    s_add_i32 s28, s28, 3
; SI-NEXT:    s_add_i32 s27, s27, 3
; SI-NEXT:    s_add_i32 s26, s26, 3
; SI-NEXT:    s_add_i32 s25, s25, 3
; SI-NEXT:    s_add_i32 s24, s24, 3
; SI-NEXT:    s_add_i32 s23, s23, 3
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_add_i32 s21, s21, 3
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_add_i32 s19, s19, 3
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_add_i32 s17, s17, 3
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:  .LBB9_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v2, s18
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v4, s20
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v6, s22
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    v_mov_b32_e32 v8, s24
; SI-NEXT:    v_mov_b32_e32 v9, s25
; SI-NEXT:    v_mov_b32_e32 v10, s26
; SI-NEXT:    v_mov_b32_e32 v11, s27
; SI-NEXT:    v_mov_b32_e32 v12, s28
; SI-NEXT:    v_mov_b32_e32 v13, s29
; SI-NEXT:    v_mov_b32_e32 v14, s11
; SI-NEXT:    v_mov_b32_e32 v15, s10
; SI-NEXT:    v_mov_b32_e32 v16, s9
; SI-NEXT:    v_mov_b32_e32 v17, s8
; SI-NEXT:    v_mov_b32_e32 v18, s7
; SI-NEXT:    v_mov_b32_e32 v19, s6
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB9_4:
; SI-NEXT:    s_branch .LBB9_2
;
; VI-LABEL: bitcast_v20i32_to_v10f64_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    v_readfirstlane_b32 s6, v5
; VI-NEXT:    v_readfirstlane_b32 s7, v4
; VI-NEXT:    v_readfirstlane_b32 s8, v3
; VI-NEXT:    v_readfirstlane_b32 s9, v2
; VI-NEXT:    v_readfirstlane_b32 s10, v1
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    v_readfirstlane_b32 s11, v0
; VI-NEXT:    s_cbranch_scc0 .LBB9_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB9_3
; VI-NEXT:  .LBB9_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s6, s6, 3
; VI-NEXT:    s_add_i32 s7, s7, 3
; VI-NEXT:    s_add_i32 s8, s8, 3
; VI-NEXT:    s_add_i32 s9, s9, 3
; VI-NEXT:    s_add_i32 s10, s10, 3
; VI-NEXT:    s_add_i32 s11, s11, 3
; VI-NEXT:    s_add_i32 s29, s29, 3
; VI-NEXT:    s_add_i32 s28, s28, 3
; VI-NEXT:    s_add_i32 s27, s27, 3
; VI-NEXT:    s_add_i32 s26, s26, 3
; VI-NEXT:    s_add_i32 s25, s25, 3
; VI-NEXT:    s_add_i32 s24, s24, 3
; VI-NEXT:    s_add_i32 s23, s23, 3
; VI-NEXT:    s_add_i32 s22, s22, 3
; VI-NEXT:    s_add_i32 s21, s21, 3
; VI-NEXT:    s_add_i32 s20, s20, 3
; VI-NEXT:    s_add_i32 s19, s19, 3
; VI-NEXT:    s_add_i32 s18, s18, 3
; VI-NEXT:    s_add_i32 s17, s17, 3
; VI-NEXT:    s_add_i32 s16, s16, 3
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:  .LBB9_3: ; %end
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    v_mov_b32_e32 v8, s24
; VI-NEXT:    v_mov_b32_e32 v9, s25
; VI-NEXT:    v_mov_b32_e32 v10, s26
; VI-NEXT:    v_mov_b32_e32 v11, s27
; VI-NEXT:    v_mov_b32_e32 v12, s28
; VI-NEXT:    v_mov_b32_e32 v13, s29
; VI-NEXT:    v_mov_b32_e32 v14, s11
; VI-NEXT:    v_mov_b32_e32 v15, s10
; VI-NEXT:    v_mov_b32_e32 v16, s9
; VI-NEXT:    v_mov_b32_e32 v17, s8
; VI-NEXT:    v_mov_b32_e32 v18, s7
; VI-NEXT:    v_mov_b32_e32 v19, s6
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB9_4:
; VI-NEXT:    s_branch .LBB9_2
;
; GFX9-LABEL: bitcast_v20i32_to_v10f64_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_readfirstlane_b32 s4, v6
; GFX9-NEXT:    v_readfirstlane_b32 s6, v5
; GFX9-NEXT:    v_readfirstlane_b32 s7, v4
; GFX9-NEXT:    v_readfirstlane_b32 s8, v3
; GFX9-NEXT:    v_readfirstlane_b32 s9, v2
; GFX9-NEXT:    v_readfirstlane_b32 s10, v1
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    v_readfirstlane_b32 s11, v0
; GFX9-NEXT:    s_cbranch_scc0 .LBB9_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB9_3
; GFX9-NEXT:  .LBB9_2: ; %cmp.true
; GFX9-NEXT:    s_add_i32 s6, s6, 3
; GFX9-NEXT:    s_add_i32 s7, s7, 3
; GFX9-NEXT:    s_add_i32 s8, s8, 3
; GFX9-NEXT:    s_add_i32 s9, s9, 3
; GFX9-NEXT:    s_add_i32 s10, s10, 3
; GFX9-NEXT:    s_add_i32 s11, s11, 3
; GFX9-NEXT:    s_add_i32 s29, s29, 3
; GFX9-NEXT:    s_add_i32 s28, s28, 3
; GFX9-NEXT:    s_add_i32 s27, s27, 3
; GFX9-NEXT:    s_add_i32 s26, s26, 3
; GFX9-NEXT:    s_add_i32 s25, s25, 3
; GFX9-NEXT:    s_add_i32 s24, s24, 3
; GFX9-NEXT:    s_add_i32 s23, s23, 3
; GFX9-NEXT:    s_add_i32 s22, s22, 3
; GFX9-NEXT:    s_add_i32 s21, s21, 3
; GFX9-NEXT:    s_add_i32 s20, s20, 3
; GFX9-NEXT:    s_add_i32 s19, s19, 3
; GFX9-NEXT:    s_add_i32 s18, s18, 3
; GFX9-NEXT:    s_add_i32 s17, s17, 3
; GFX9-NEXT:    s_add_i32 s16, s16, 3
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:  .LBB9_3: ; %end
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    v_mov_b32_e32 v8, s24
; GFX9-NEXT:    v_mov_b32_e32 v9, s25
; GFX9-NEXT:    v_mov_b32_e32 v10, s26
; GFX9-NEXT:    v_mov_b32_e32 v11, s27
; GFX9-NEXT:    v_mov_b32_e32 v12, s28
; GFX9-NEXT:    v_mov_b32_e32 v13, s29
; GFX9-NEXT:    v_mov_b32_e32 v14, s11
; GFX9-NEXT:    v_mov_b32_e32 v15, s10
; GFX9-NEXT:    v_mov_b32_e32 v16, s9
; GFX9-NEXT:    v_mov_b32_e32 v17, s8
; GFX9-NEXT:    v_mov_b32_e32 v18, s7
; GFX9-NEXT:    v_mov_b32_e32 v19, s6
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB9_4:
; GFX9-NEXT:    s_branch .LBB9_2
;
; GFX11-LABEL: bitcast_v20i32_to_v10f64_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    v_readfirstlane_b32 s6, v2
; GFX11-NEXT:    v_readfirstlane_b32 s4, v1
; GFX11-NEXT:    v_readfirstlane_b32 s5, v0
; GFX11-NEXT:    s_cmp_lg_u32 s6, 0
; GFX11-NEXT:    s_mov_b32 s6, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB9_4
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s6
; GFX11-NEXT:    s_cbranch_vccnz .LBB9_3
; GFX11-NEXT:  .LBB9_2: ; %cmp.true
; GFX11-NEXT:    s_add_i32 s4, s4, 3
; GFX11-NEXT:    s_add_i32 s5, s5, 3
; GFX11-NEXT:    s_add_i32 s29, s29, 3
; GFX11-NEXT:    s_add_i32 s28, s28, 3
; GFX11-NEXT:    s_add_i32 s27, s27, 3
; GFX11-NEXT:    s_add_i32 s26, s26, 3
; GFX11-NEXT:    s_add_i32 s25, s25, 3
; GFX11-NEXT:    s_add_i32 s24, s24, 3
; GFX11-NEXT:    s_add_i32 s23, s23, 3
; GFX11-NEXT:    s_add_i32 s22, s22, 3
; GFX11-NEXT:    s_add_i32 s21, s21, 3
; GFX11-NEXT:    s_add_i32 s20, s20, 3
; GFX11-NEXT:    s_add_i32 s19, s19, 3
; GFX11-NEXT:    s_add_i32 s18, s18, 3
; GFX11-NEXT:    s_add_i32 s17, s17, 3
; GFX11-NEXT:    s_add_i32 s16, s16, 3
; GFX11-NEXT:    s_add_i32 s3, s3, 3
; GFX11-NEXT:    s_add_i32 s2, s2, 3
; GFX11-NEXT:    s_add_i32 s1, s1, 3
; GFX11-NEXT:    s_add_i32 s0, s0, 3
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:  .LBB9_3: ; %end
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s16 :: v_dual_mov_b32 v5, s17
; GFX11-NEXT:    v_dual_mov_b32 v6, s18 :: v_dual_mov_b32 v7, s19
; GFX11-NEXT:    v_dual_mov_b32 v8, s20 :: v_dual_mov_b32 v9, s21
; GFX11-NEXT:    v_dual_mov_b32 v10, s22 :: v_dual_mov_b32 v11, s23
; GFX11-NEXT:    v_dual_mov_b32 v12, s24 :: v_dual_mov_b32 v13, s25
; GFX11-NEXT:    v_dual_mov_b32 v14, s26 :: v_dual_mov_b32 v15, s27
; GFX11-NEXT:    v_dual_mov_b32 v16, s28 :: v_dual_mov_b32 v17, s29
; GFX11-NEXT:    v_dual_mov_b32 v18, s5 :: v_dual_mov_b32 v19, s4
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB9_4:
; GFX11-NEXT:    s_branch .LBB9_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <20 x i32> %a, splat (i32 3)
  %a2 = bitcast <20 x i32> %a1 to <10 x double>
  br label %end

cmp.false:
  %a3 = bitcast <20 x i32> %a to <10 x double>
  br label %end

end:
  %phi = phi <10 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <10 x double> %phi
}

define <20 x i32> @bitcast_v10f64_to_v20i32(<10 x double> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v10f64_to_v20i32:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB10_2
; SI-NEXT:  ; %bb.1: ; %cmp.true
; SI-NEXT:    v_add_f64 v[18:19], v[18:19], 1.0
; SI-NEXT:    v_add_f64 v[16:17], v[16:17], 1.0
; SI-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; SI-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; SI-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; SI-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; SI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; SI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; SI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; SI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:  .LBB10_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v10f64_to_v20i32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB10_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f64 v[18:19], v[18:19], 1.0
; VI-NEXT:    v_add_f64 v[16:17], v[16:17], 1.0
; VI-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; VI-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; VI-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; VI-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; VI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; VI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; VI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; VI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:  .LBB10_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v10f64_to_v20i32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB10_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[18:19], v[18:19], 1.0
; GFX9-NEXT:    v_add_f64 v[16:17], v[16:17], 1.0
; GFX9-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GFX9-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GFX9-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GFX9-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GFX9-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX9-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:  .LBB10_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v10f64_to_v20i32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB10_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_f64 v[18:19], v[18:19], 1.0
; GFX11-NEXT:    v_add_f64 v[16:17], v[16:17], 1.0
; GFX11-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GFX11-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GFX11-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GFX11-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GFX11-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX11-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX11-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX11-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:  .LBB10_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <10 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <10 x double> %a1 to <20 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <10 x double> %a to <20 x i32>
  br label %end

end:
  %phi = phi <20 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <20 x i32> %phi
}

define inreg <20 x i32> @bitcast_v10f64_to_v20i32_scalar(<10 x double> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v10f64_to_v20i32_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_writelane_b32 v32, s36, 0
; SI-NEXT:    v_writelane_b32 v32, s37, 1
; SI-NEXT:    v_writelane_b32 v32, s38, 2
; SI-NEXT:    v_writelane_b32 v32, s39, 3
; SI-NEXT:    v_writelane_b32 v32, s48, 4
; SI-NEXT:    v_writelane_b32 v32, s49, 5
; SI-NEXT:    v_writelane_b32 v32, s50, 6
; SI-NEXT:    v_writelane_b32 v32, s51, 7
; SI-NEXT:    v_writelane_b32 v32, s52, 8
; SI-NEXT:    v_writelane_b32 v32, s53, 9
; SI-NEXT:    v_writelane_b32 v32, s54, 10
; SI-NEXT:    v_writelane_b32 v32, s55, 11
; SI-NEXT:    v_readfirstlane_b32 s4, v6
; SI-NEXT:    s_mov_b32 s49, s29
; SI-NEXT:    s_mov_b32 s48, s28
; SI-NEXT:    s_mov_b32 s47, s27
; SI-NEXT:    s_mov_b32 s46, s26
; SI-NEXT:    s_mov_b32 s45, s25
; SI-NEXT:    s_mov_b32 s44, s24
; SI-NEXT:    s_mov_b32 s43, s23
; SI-NEXT:    s_mov_b32 s42, s22
; SI-NEXT:    s_mov_b32 s41, s21
; SI-NEXT:    s_mov_b32 s40, s20
; SI-NEXT:    s_mov_b32 s39, s19
; SI-NEXT:    s_mov_b32 s38, s18
; SI-NEXT:    s_mov_b32 s37, s17
; SI-NEXT:    s_mov_b32 s36, s16
; SI-NEXT:    v_readfirstlane_b32 s55, v5
; SI-NEXT:    v_readfirstlane_b32 s54, v4
; SI-NEXT:    v_readfirstlane_b32 s53, v3
; SI-NEXT:    v_readfirstlane_b32 s52, v2
; SI-NEXT:    v_readfirstlane_b32 s51, v1
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    v_readfirstlane_b32 s50, v0
; SI-NEXT:    s_cbranch_scc0 .LBB11_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_cbranch_execnz .LBB11_4
; SI-NEXT:  .LBB11_2: ; %cmp.true
; SI-NEXT:    v_add_f64 v[18:19], s[54:55], 1.0
; SI-NEXT:    v_add_f64 v[16:17], s[52:53], 1.0
; SI-NEXT:    v_add_f64 v[14:15], s[50:51], 1.0
; SI-NEXT:    v_add_f64 v[12:13], s[48:49], 1.0
; SI-NEXT:    v_add_f64 v[10:11], s[46:47], 1.0
; SI-NEXT:    v_add_f64 v[8:9], s[44:45], 1.0
; SI-NEXT:    v_add_f64 v[6:7], s[42:43], 1.0
; SI-NEXT:    v_add_f64 v[4:5], s[40:41], 1.0
; SI-NEXT:    v_add_f64 v[2:3], s[38:39], 1.0
; SI-NEXT:    v_add_f64 v[0:1], s[36:37], 1.0
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    s_branch .LBB11_5
; SI-NEXT:  .LBB11_3:
; SI-NEXT:    s_branch .LBB11_2
; SI-NEXT:  .LBB11_4:
; SI-NEXT:    v_mov_b32_e32 v0, s36
; SI-NEXT:    v_mov_b32_e32 v1, s37
; SI-NEXT:    v_mov_b32_e32 v2, s38
; SI-NEXT:    v_mov_b32_e32 v3, s39
; SI-NEXT:    v_mov_b32_e32 v4, s40
; SI-NEXT:    v_mov_b32_e32 v5, s41
; SI-NEXT:    v_mov_b32_e32 v6, s42
; SI-NEXT:    v_mov_b32_e32 v7, s43
; SI-NEXT:    v_mov_b32_e32 v8, s44
; SI-NEXT:    v_mov_b32_e32 v9, s45
; SI-NEXT:    v_mov_b32_e32 v10, s46
; SI-NEXT:    v_mov_b32_e32 v11, s47
; SI-NEXT:    v_mov_b32_e32 v12, s48
; SI-NEXT:    v_mov_b32_e32 v13, s49
; SI-NEXT:    v_mov_b32_e32 v14, s50
; SI-NEXT:    v_mov_b32_e32 v15, s51
; SI-NEXT:    v_mov_b32_e32 v16, s52
; SI-NEXT:    v_mov_b32_e32 v17, s53
; SI-NEXT:    v_mov_b32_e32 v18, s54
; SI-NEXT:    v_mov_b32_e32 v19, s55
; SI-NEXT:    v_mov_b32_e32 v20, s56
; SI-NEXT:    v_mov_b32_e32 v21, s57
; SI-NEXT:    v_mov_b32_e32 v22, s58
; SI-NEXT:    v_mov_b32_e32 v23, s59
; SI-NEXT:    v_mov_b32_e32 v24, s60
; SI-NEXT:    v_mov_b32_e32 v25, s61
; SI-NEXT:    v_mov_b32_e32 v26, s62
; SI-NEXT:    v_mov_b32_e32 v27, s63
; SI-NEXT:    v_mov_b32_e32 v28, s64
; SI-NEXT:    v_mov_b32_e32 v29, s65
; SI-NEXT:    v_mov_b32_e32 v30, s66
; SI-NEXT:    v_mov_b32_e32 v31, s67
; SI-NEXT:  .LBB11_5: ; %end
; SI-NEXT:    v_readlane_b32 s55, v32, 11
; SI-NEXT:    v_readlane_b32 s54, v32, 10
; SI-NEXT:    v_readlane_b32 s53, v32, 9
; SI-NEXT:    v_readlane_b32 s52, v32, 8
; SI-NEXT:    v_readlane_b32 s51, v32, 7
; SI-NEXT:    v_readlane_b32 s50, v32, 6
; SI-NEXT:    v_readlane_b32 s49, v32, 5
; SI-NEXT:    v_readlane_b32 s48, v32, 4
; SI-NEXT:    v_readlane_b32 s39, v32, 3
; SI-NEXT:    v_readlane_b32 s38, v32, 2
; SI-NEXT:    v_readlane_b32 s37, v32, 1
; SI-NEXT:    v_readlane_b32 s36, v32, 0
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v10f64_to_v20i32_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    v_writelane_b32 v32, s36, 0
; VI-NEXT:    v_writelane_b32 v32, s37, 1
; VI-NEXT:    v_writelane_b32 v32, s38, 2
; VI-NEXT:    v_writelane_b32 v32, s39, 3
; VI-NEXT:    v_writelane_b32 v32, s48, 4
; VI-NEXT:    v_writelane_b32 v32, s49, 5
; VI-NEXT:    v_writelane_b32 v32, s50, 6
; VI-NEXT:    v_writelane_b32 v32, s51, 7
; VI-NEXT:    v_writelane_b32 v32, s52, 8
; VI-NEXT:    v_writelane_b32 v32, s53, 9
; VI-NEXT:    v_writelane_b32 v32, s54, 10
; VI-NEXT:    v_writelane_b32 v32, s55, 11
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    s_mov_b32 s49, s29
; VI-NEXT:    s_mov_b32 s48, s28
; VI-NEXT:    s_mov_b32 s47, s27
; VI-NEXT:    s_mov_b32 s46, s26
; VI-NEXT:    s_mov_b32 s45, s25
; VI-NEXT:    s_mov_b32 s44, s24
; VI-NEXT:    s_mov_b32 s43, s23
; VI-NEXT:    s_mov_b32 s42, s22
; VI-NEXT:    s_mov_b32 s41, s21
; VI-NEXT:    s_mov_b32 s40, s20
; VI-NEXT:    s_mov_b32 s39, s19
; VI-NEXT:    s_mov_b32 s38, s18
; VI-NEXT:    s_mov_b32 s37, s17
; VI-NEXT:    s_mov_b32 s36, s16
; VI-NEXT:    v_readfirstlane_b32 s55, v5
; VI-NEXT:    v_readfirstlane_b32 s54, v4
; VI-NEXT:    v_readfirstlane_b32 s53, v3
; VI-NEXT:    v_readfirstlane_b32 s52, v2
; VI-NEXT:    v_readfirstlane_b32 s51, v1
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    v_readfirstlane_b32 s50, v0
; VI-NEXT:    s_cbranch_scc0 .LBB11_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB11_4
; VI-NEXT:  .LBB11_2: ; %cmp.true
; VI-NEXT:    v_add_f64 v[18:19], s[54:55], 1.0
; VI-NEXT:    v_add_f64 v[16:17], s[52:53], 1.0
; VI-NEXT:    v_add_f64 v[14:15], s[50:51], 1.0
; VI-NEXT:    v_add_f64 v[12:13], s[48:49], 1.0
; VI-NEXT:    v_add_f64 v[10:11], s[46:47], 1.0
; VI-NEXT:    v_add_f64 v[8:9], s[44:45], 1.0
; VI-NEXT:    v_add_f64 v[6:7], s[42:43], 1.0
; VI-NEXT:    v_add_f64 v[4:5], s[40:41], 1.0
; VI-NEXT:    v_add_f64 v[2:3], s[38:39], 1.0
; VI-NEXT:    v_add_f64 v[0:1], s[36:37], 1.0
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    s_branch .LBB11_5
; VI-NEXT:  .LBB11_3:
; VI-NEXT:    s_branch .LBB11_2
; VI-NEXT:  .LBB11_4:
; VI-NEXT:    v_mov_b32_e32 v0, s36
; VI-NEXT:    v_mov_b32_e32 v1, s37
; VI-NEXT:    v_mov_b32_e32 v2, s38
; VI-NEXT:    v_mov_b32_e32 v3, s39
; VI-NEXT:    v_mov_b32_e32 v4, s40
; VI-NEXT:    v_mov_b32_e32 v5, s41
; VI-NEXT:    v_mov_b32_e32 v6, s42
; VI-NEXT:    v_mov_b32_e32 v7, s43
; VI-NEXT:    v_mov_b32_e32 v8, s44
; VI-NEXT:    v_mov_b32_e32 v9, s45
; VI-NEXT:    v_mov_b32_e32 v10, s46
; VI-NEXT:    v_mov_b32_e32 v11, s47
; VI-NEXT:    v_mov_b32_e32 v12, s48
; VI-NEXT:    v_mov_b32_e32 v13, s49
; VI-NEXT:    v_mov_b32_e32 v14, s50
; VI-NEXT:    v_mov_b32_e32 v15, s51
; VI-NEXT:    v_mov_b32_e32 v16, s52
; VI-NEXT:    v_mov_b32_e32 v17, s53
; VI-NEXT:    v_mov_b32_e32 v18, s54
; VI-NEXT:    v_mov_b32_e32 v19, s55
; VI-NEXT:    v_mov_b32_e32 v20, s56
; VI-NEXT:    v_mov_b32_e32 v21, s57
; VI-NEXT:    v_mov_b32_e32 v22, s58
; VI-NEXT:    v_mov_b32_e32 v23, s59
; VI-NEXT:    v_mov_b32_e32 v24, s60
; VI-NEXT:    v_mov_b32_e32 v25, s61
; VI-NEXT:    v_mov_b32_e32 v26, s62
; VI-NEXT:    v_mov_b32_e32 v27, s63
; VI-NEXT:    v_mov_b32_e32 v28, s64
; VI-NEXT:    v_mov_b32_e32 v29, s65
; VI-NEXT:    v_mov_b32_e32 v30, s66
; VI-NEXT:    v_mov_b32_e32 v31, s67
; VI-NEXT:  .LBB11_5: ; %end
; VI-NEXT:    v_readlane_b32 s55, v32, 11
; VI-NEXT:    v_readlane_b32 s54, v32, 10
; VI-NEXT:    v_readlane_b32 s53, v32, 9
; VI-NEXT:    v_readlane_b32 s52, v32, 8
; VI-NEXT:    v_readlane_b32 s51, v32, 7
; VI-NEXT:    v_readlane_b32 s50, v32, 6
; VI-NEXT:    v_readlane_b32 s49, v32, 5
; VI-NEXT:    v_readlane_b32 s48, v32, 4
; VI-NEXT:    v_readlane_b32 s39, v32, 3
; VI-NEXT:    v_readlane_b32 s38, v32, 2
; VI-NEXT:    v_readlane_b32 s37, v32, 1
; VI-NEXT:    v_readlane_b32 s36, v32, 0
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v10f64_to_v20i32_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    v_writelane_b32 v32, s36, 0
; GFX9-NEXT:    v_writelane_b32 v32, s37, 1
; GFX9-NEXT:    v_writelane_b32 v32, s38, 2
; GFX9-NEXT:    v_writelane_b32 v32, s39, 3
; GFX9-NEXT:    v_writelane_b32 v32, s48, 4
; GFX9-NEXT:    v_writelane_b32 v32, s49, 5
; GFX9-NEXT:    v_writelane_b32 v32, s50, 6
; GFX9-NEXT:    v_writelane_b32 v32, s51, 7
; GFX9-NEXT:    v_writelane_b32 v32, s52, 8
; GFX9-NEXT:    v_writelane_b32 v32, s53, 9
; GFX9-NEXT:    v_writelane_b32 v32, s54, 10
; GFX9-NEXT:    v_writelane_b32 v32, s55, 11
; GFX9-NEXT:    v_readfirstlane_b32 s4, v6
; GFX9-NEXT:    s_mov_b32 s49, s29
; GFX9-NEXT:    s_mov_b32 s48, s28
; GFX9-NEXT:    s_mov_b32 s47, s27
; GFX9-NEXT:    s_mov_b32 s46, s26
; GFX9-NEXT:    s_mov_b32 s45, s25
; GFX9-NEXT:    s_mov_b32 s44, s24
; GFX9-NEXT:    s_mov_b32 s43, s23
; GFX9-NEXT:    s_mov_b32 s42, s22
; GFX9-NEXT:    s_mov_b32 s41, s21
; GFX9-NEXT:    s_mov_b32 s40, s20
; GFX9-NEXT:    s_mov_b32 s39, s19
; GFX9-NEXT:    s_mov_b32 s38, s18
; GFX9-NEXT:    s_mov_b32 s37, s17
; GFX9-NEXT:    s_mov_b32 s36, s16
; GFX9-NEXT:    v_readfirstlane_b32 s55, v5
; GFX9-NEXT:    v_readfirstlane_b32 s54, v4
; GFX9-NEXT:    v_readfirstlane_b32 s53, v3
; GFX9-NEXT:    v_readfirstlane_b32 s52, v2
; GFX9-NEXT:    v_readfirstlane_b32 s51, v1
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    v_readfirstlane_b32 s50, v0
; GFX9-NEXT:    s_cbranch_scc0 .LBB11_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB11_4
; GFX9-NEXT:  .LBB11_2: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[18:19], s[54:55], 1.0
; GFX9-NEXT:    v_add_f64 v[16:17], s[52:53], 1.0
; GFX9-NEXT:    v_add_f64 v[14:15], s[50:51], 1.0
; GFX9-NEXT:    v_add_f64 v[12:13], s[48:49], 1.0
; GFX9-NEXT:    v_add_f64 v[10:11], s[46:47], 1.0
; GFX9-NEXT:    v_add_f64 v[8:9], s[44:45], 1.0
; GFX9-NEXT:    v_add_f64 v[6:7], s[42:43], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], s[40:41], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], s[38:39], 1.0
; GFX9-NEXT:    v_add_f64 v[0:1], s[36:37], 1.0
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_branch .LBB11_5
; GFX9-NEXT:  .LBB11_3:
; GFX9-NEXT:    s_branch .LBB11_2
; GFX9-NEXT:  .LBB11_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s36
; GFX9-NEXT:    v_mov_b32_e32 v1, s37
; GFX9-NEXT:    v_mov_b32_e32 v2, s38
; GFX9-NEXT:    v_mov_b32_e32 v3, s39
; GFX9-NEXT:    v_mov_b32_e32 v4, s40
; GFX9-NEXT:    v_mov_b32_e32 v5, s41
; GFX9-NEXT:    v_mov_b32_e32 v6, s42
; GFX9-NEXT:    v_mov_b32_e32 v7, s43
; GFX9-NEXT:    v_mov_b32_e32 v8, s44
; GFX9-NEXT:    v_mov_b32_e32 v9, s45
; GFX9-NEXT:    v_mov_b32_e32 v10, s46
; GFX9-NEXT:    v_mov_b32_e32 v11, s47
; GFX9-NEXT:    v_mov_b32_e32 v12, s48
; GFX9-NEXT:    v_mov_b32_e32 v13, s49
; GFX9-NEXT:    v_mov_b32_e32 v14, s50
; GFX9-NEXT:    v_mov_b32_e32 v15, s51
; GFX9-NEXT:    v_mov_b32_e32 v16, s52
; GFX9-NEXT:    v_mov_b32_e32 v17, s53
; GFX9-NEXT:    v_mov_b32_e32 v18, s54
; GFX9-NEXT:    v_mov_b32_e32 v19, s55
; GFX9-NEXT:    v_mov_b32_e32 v20, s56
; GFX9-NEXT:    v_mov_b32_e32 v21, s57
; GFX9-NEXT:    v_mov_b32_e32 v22, s58
; GFX9-NEXT:    v_mov_b32_e32 v23, s59
; GFX9-NEXT:    v_mov_b32_e32 v24, s60
; GFX9-NEXT:    v_mov_b32_e32 v25, s61
; GFX9-NEXT:    v_mov_b32_e32 v26, s62
; GFX9-NEXT:    v_mov_b32_e32 v27, s63
; GFX9-NEXT:    v_mov_b32_e32 v28, s64
; GFX9-NEXT:    v_mov_b32_e32 v29, s65
; GFX9-NEXT:    v_mov_b32_e32 v30, s66
; GFX9-NEXT:    v_mov_b32_e32 v31, s67
; GFX9-NEXT:  .LBB11_5: ; %end
; GFX9-NEXT:    v_readlane_b32 s55, v32, 11
; GFX9-NEXT:    v_readlane_b32 s54, v32, 10
; GFX9-NEXT:    v_readlane_b32 s53, v32, 9
; GFX9-NEXT:    v_readlane_b32 s52, v32, 8
; GFX9-NEXT:    v_readlane_b32 s51, v32, 7
; GFX9-NEXT:    v_readlane_b32 s50, v32, 6
; GFX9-NEXT:    v_readlane_b32 s49, v32, 5
; GFX9-NEXT:    v_readlane_b32 s48, v32, 4
; GFX9-NEXT:    v_readlane_b32 s39, v32, 3
; GFX9-NEXT:    v_readlane_b32 s38, v32, 2
; GFX9-NEXT:    v_readlane_b32 s37, v32, 1
; GFX9-NEXT:    v_readlane_b32 s36, v32, 0
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v10f64_to_v20i32_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_xor_saveexec_b32 s4, -1
; GFX11-NEXT:    scratch_store_b32 off, v32, s32 ; 4-byte Folded Spill
; GFX11-NEXT:    s_mov_b32 exec_lo, s4
; GFX11-NEXT:    v_writelane_b32 v32, s36, 0
; GFX11-NEXT:    v_writelane_b32 v32, s37, 1
; GFX11-NEXT:    v_writelane_b32 v32, s38, 2
; GFX11-NEXT:    v_writelane_b32 v32, s39, 3
; GFX11-NEXT:    v_writelane_b32 v32, s48, 4
; GFX11-NEXT:    v_writelane_b32 v32, s49, 5
; GFX11-NEXT:    v_writelane_b32 v32, s50, 6
; GFX11-NEXT:    v_writelane_b32 v32, s51, 7
; GFX11-NEXT:    v_writelane_b32 v32, s52, 8
; GFX11-NEXT:    v_writelane_b32 v32, s53, 9
; GFX11-NEXT:    v_writelane_b32 v32, s54, 10
; GFX11-NEXT:    v_writelane_b32 v32, s55, 11
; GFX11-NEXT:    s_mov_b32 s36, s0
; GFX11-NEXT:    v_readfirstlane_b32 s0, v2
; GFX11-NEXT:    v_readfirstlane_b32 s55, v1
; GFX11-NEXT:    v_readfirstlane_b32 s54, v0
; GFX11-NEXT:    s_mov_b32 s53, s29
; GFX11-NEXT:    s_mov_b32 s52, s28
; GFX11-NEXT:    s_mov_b32 s51, s27
; GFX11-NEXT:    s_mov_b32 s50, s26
; GFX11-NEXT:    s_mov_b32 s49, s25
; GFX11-NEXT:    s_mov_b32 s48, s24
; GFX11-NEXT:    s_mov_b32 s47, s23
; GFX11-NEXT:    s_mov_b32 s46, s22
; GFX11-NEXT:    s_mov_b32 s45, s21
; GFX11-NEXT:    s_mov_b32 s44, s20
; GFX11-NEXT:    s_mov_b32 s43, s19
; GFX11-NEXT:    s_mov_b32 s42, s18
; GFX11-NEXT:    s_mov_b32 s41, s17
; GFX11-NEXT:    s_mov_b32 s40, s16
; GFX11-NEXT:    s_mov_b32 s39, s3
; GFX11-NEXT:    s_mov_b32 s38, s2
; GFX11-NEXT:    s_mov_b32 s37, s1
; GFX11-NEXT:    s_cmp_lg_u32 s0, 0
; GFX11-NEXT:    s_mov_b32 s0, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB11_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s0
; GFX11-NEXT:    s_cbranch_vccnz .LBB11_4
; GFX11-NEXT:  .LBB11_2: ; %cmp.true
; GFX11-NEXT:    v_add_f64 v[18:19], s[54:55], 1.0
; GFX11-NEXT:    v_add_f64 v[16:17], s[52:53], 1.0
; GFX11-NEXT:    v_add_f64 v[14:15], s[50:51], 1.0
; GFX11-NEXT:    v_add_f64 v[12:13], s[48:49], 1.0
; GFX11-NEXT:    v_add_f64 v[10:11], s[46:47], 1.0
; GFX11-NEXT:    v_add_f64 v[8:9], s[44:45], 1.0
; GFX11-NEXT:    v_add_f64 v[6:7], s[42:43], 1.0
; GFX11-NEXT:    v_add_f64 v[4:5], s[40:41], 1.0
; GFX11-NEXT:    v_add_f64 v[2:3], s[38:39], 1.0
; GFX11-NEXT:    v_add_f64 v[0:1], s[36:37], 1.0
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    s_branch .LBB11_5
; GFX11-NEXT:  .LBB11_3:
; GFX11-NEXT:    s_branch .LBB11_2
; GFX11-NEXT:  .LBB11_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s36 :: v_dual_mov_b32 v1, s37
; GFX11-NEXT:    v_dual_mov_b32 v2, s38 :: v_dual_mov_b32 v3, s39
; GFX11-NEXT:    v_dual_mov_b32 v4, s40 :: v_dual_mov_b32 v5, s41
; GFX11-NEXT:    v_dual_mov_b32 v6, s42 :: v_dual_mov_b32 v7, s43
; GFX11-NEXT:    v_dual_mov_b32 v8, s44 :: v_dual_mov_b32 v9, s45
; GFX11-NEXT:    v_dual_mov_b32 v10, s46 :: v_dual_mov_b32 v11, s47
; GFX11-NEXT:    v_dual_mov_b32 v12, s48 :: v_dual_mov_b32 v13, s49
; GFX11-NEXT:    v_dual_mov_b32 v14, s50 :: v_dual_mov_b32 v15, s51
; GFX11-NEXT:    v_dual_mov_b32 v16, s52 :: v_dual_mov_b32 v17, s53
; GFX11-NEXT:    v_dual_mov_b32 v18, s54 :: v_dual_mov_b32 v19, s55
; GFX11-NEXT:    v_dual_mov_b32 v20, s56 :: v_dual_mov_b32 v21, s57
; GFX11-NEXT:    v_dual_mov_b32 v22, s58 :: v_dual_mov_b32 v23, s59
; GFX11-NEXT:    v_dual_mov_b32 v24, s60 :: v_dual_mov_b32 v25, s61
; GFX11-NEXT:    v_dual_mov_b32 v26, s62 :: v_dual_mov_b32 v27, s63
; GFX11-NEXT:    v_dual_mov_b32 v28, s64 :: v_dual_mov_b32 v29, s65
; GFX11-NEXT:    v_dual_mov_b32 v30, s66 :: v_dual_mov_b32 v31, s67
; GFX11-NEXT:  .LBB11_5: ; %end
; GFX11-NEXT:    v_readlane_b32 s55, v32, 11
; GFX11-NEXT:    v_readlane_b32 s54, v32, 10
; GFX11-NEXT:    v_readlane_b32 s53, v32, 9
; GFX11-NEXT:    v_readlane_b32 s52, v32, 8
; GFX11-NEXT:    v_readlane_b32 s51, v32, 7
; GFX11-NEXT:    v_readlane_b32 s50, v32, 6
; GFX11-NEXT:    v_readlane_b32 s49, v32, 5
; GFX11-NEXT:    v_readlane_b32 s48, v32, 4
; GFX11-NEXT:    v_readlane_b32 s39, v32, 3
; GFX11-NEXT:    v_readlane_b32 s38, v32, 2
; GFX11-NEXT:    v_readlane_b32 s37, v32, 1
; GFX11-NEXT:    v_readlane_b32 s36, v32, 0
; GFX11-NEXT:    s_xor_saveexec_b32 s0, -1
; GFX11-NEXT:    scratch_load_b32 v32, off, s32 ; 4-byte Folded Reload
; GFX11-NEXT:    s_mov_b32 exec_lo, s0
; GFX11-NEXT:    s_waitcnt vmcnt(0)
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <10 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <10 x double> %a1 to <20 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <10 x double> %a to <20 x i32>
  br label %end

end:
  %phi = phi <20 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <20 x i32> %phi
}

define <40 x i16> @bitcast_v20i32_to_v40i16(<20 x i32> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v20i32_to_v40i16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:    ; implicit-def: $vgpr31
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr29
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr26
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr25
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr24
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr30
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr28
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr27
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB12_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_alignbit_b32 v20, v19, v18, 16
; SI-NEXT:    v_alignbit_b32 v21, v17, v16, 16
; SI-NEXT:    v_alignbit_b32 v22, v15, v14, 16
; SI-NEXT:    v_alignbit_b32 v23, v13, v12, 16
; SI-NEXT:    v_alignbit_b32 v24, v11, v10, 16
; SI-NEXT:    v_alignbit_b32 v25, v9, v8, 16
; SI-NEXT:    v_alignbit_b32 v26, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v29, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v31, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v34, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v27, 16, v19
; SI-NEXT:    v_lshrrev_b32_e32 v28, 16, v17
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v15
; SI-NEXT:    v_lshrrev_b32_e32 v32, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v33, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v35, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v36, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v37, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v39, 16, v1
; SI-NEXT:  .LBB12_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB12_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v1
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v3
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v5
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v7
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; SI-NEXT:    v_add_i32_e32 v9, vcc, 3, v9
; SI-NEXT:    v_add_i32_e32 v8, vcc, 3, v8
; SI-NEXT:    v_add_i32_e32 v11, vcc, 3, v11
; SI-NEXT:    v_add_i32_e32 v10, vcc, 3, v10
; SI-NEXT:    v_add_i32_e32 v13, vcc, 3, v13
; SI-NEXT:    v_add_i32_e32 v12, vcc, 3, v12
; SI-NEXT:    v_add_i32_e32 v15, vcc, 3, v15
; SI-NEXT:    v_add_i32_e32 v14, vcc, 3, v14
; SI-NEXT:    v_add_i32_e32 v17, vcc, 3, v17
; SI-NEXT:    v_add_i32_e32 v16, vcc, 3, v16
; SI-NEXT:    v_add_i32_e32 v19, vcc, 3, v19
; SI-NEXT:    v_add_i32_e32 v18, vcc, 3, v18
; SI-NEXT:    v_alignbit_b32 v20, v19, v18, 16
; SI-NEXT:    v_alignbit_b32 v21, v17, v16, 16
; SI-NEXT:    v_alignbit_b32 v22, v15, v14, 16
; SI-NEXT:    v_alignbit_b32 v23, v13, v12, 16
; SI-NEXT:    v_alignbit_b32 v24, v11, v10, 16
; SI-NEXT:    v_alignbit_b32 v25, v9, v8, 16
; SI-NEXT:    v_alignbit_b32 v26, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v29, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v31, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v34, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v27, 16, v19
; SI-NEXT:    v_lshrrev_b32_e32 v28, 16, v17
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v15
; SI-NEXT:    v_lshrrev_b32_e32 v32, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v33, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v35, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v36, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v37, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v39, 16, v1
; SI-NEXT:  .LBB12_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v34, 16, v34
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v31, 16, v31
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v26, 16, v26
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; SI-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; SI-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v16
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; SI-NEXT:    v_or_b32_e32 v0, v0, v34
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v34, 16, v39
; SI-NEXT:    v_or_b32_e32 v2, v2, v31
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v31, 16, v38
; SI-NEXT:    v_or_b32_e32 v4, v4, v29
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v29, 16, v37
; SI-NEXT:    v_or_b32_e32 v6, v6, v26
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v26, 16, v36
; SI-NEXT:    v_or_b32_e32 v8, v8, v25
; SI-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; SI-NEXT:    v_lshlrev_b32_e32 v25, 16, v35
; SI-NEXT:    v_or_b32_e32 v10, v10, v24
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; SI-NEXT:    v_lshlrev_b32_e32 v24, 16, v33
; SI-NEXT:    v_or_b32_e32 v12, v12, v23
; SI-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v32
; SI-NEXT:    v_or_b32_e32 v14, v14, v22
; SI-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v30
; SI-NEXT:    v_or_b32_e32 v16, v16, v21
; SI-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v28
; SI-NEXT:    v_or_b32_e32 v18, v18, v20
; SI-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v27
; SI-NEXT:    v_or_b32_e32 v1, v1, v34
; SI-NEXT:    v_or_b32_e32 v3, v3, v31
; SI-NEXT:    v_or_b32_e32 v5, v5, v29
; SI-NEXT:    v_or_b32_e32 v7, v7, v26
; SI-NEXT:    v_or_b32_e32 v9, v9, v25
; SI-NEXT:    v_or_b32_e32 v11, v11, v24
; SI-NEXT:    v_or_b32_e32 v13, v13, v23
; SI-NEXT:    v_or_b32_e32 v15, v15, v22
; SI-NEXT:    v_or_b32_e32 v17, v17, v21
; SI-NEXT:    v_or_b32_e32 v19, v19, v20
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v20i32_to_v40i16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    ; implicit-def: $vgpr39
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr35
; VI-NEXT:    ; implicit-def: $vgpr34
; VI-NEXT:    ; implicit-def: $vgpr33
; VI-NEXT:    ; implicit-def: $vgpr32
; VI-NEXT:    ; implicit-def: $vgpr31
; VI-NEXT:    ; implicit-def: $vgpr30
; VI-NEXT:    ; implicit-def: $vgpr29
; VI-NEXT:    ; implicit-def: $vgpr28
; VI-NEXT:    ; implicit-def: $vgpr27
; VI-NEXT:    ; implicit-def: $vgpr26
; VI-NEXT:    ; implicit-def: $vgpr25
; VI-NEXT:    ; implicit-def: $vgpr24
; VI-NEXT:    ; implicit-def: $vgpr23
; VI-NEXT:    ; implicit-def: $vgpr22
; VI-NEXT:    ; implicit-def: $vgpr21
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB12_2
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; VI-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; VI-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; VI-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; VI-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; VI-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; VI-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; VI-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; VI-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; VI-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; VI-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; VI-NEXT:  .LBB12_2: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB12_4
; VI-NEXT:  ; %bb.3: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v19, vcc, 3, v19
; VI-NEXT:    v_add_u32_e32 v18, vcc, 3, v18
; VI-NEXT:    v_add_u32_e32 v17, vcc, 3, v17
; VI-NEXT:    v_add_u32_e32 v16, vcc, 3, v16
; VI-NEXT:    v_add_u32_e32 v15, vcc, 3, v15
; VI-NEXT:    v_add_u32_e32 v14, vcc, 3, v14
; VI-NEXT:    v_add_u32_e32 v13, vcc, 3, v13
; VI-NEXT:    v_add_u32_e32 v12, vcc, 3, v12
; VI-NEXT:    v_add_u32_e32 v11, vcc, 3, v11
; VI-NEXT:    v_add_u32_e32 v10, vcc, 3, v10
; VI-NEXT:    v_add_u32_e32 v9, vcc, 3, v9
; VI-NEXT:    v_add_u32_e32 v8, vcc, 3, v8
; VI-NEXT:    v_add_u32_e32 v7, vcc, 3, v7
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_add_u32_e32 v5, vcc, 3, v5
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_add_u32_e32 v3, vcc, 3, v3
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_add_u32_e32 v1, vcc, 3, v1
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; VI-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; VI-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; VI-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; VI-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; VI-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; VI-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; VI-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; VI-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; VI-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; VI-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; VI-NEXT:  .LBB12_4: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    v_lshlrev_b32_e32 v39, 16, v39
; VI-NEXT:    v_lshlrev_b32_e32 v38, 16, v38
; VI-NEXT:    v_lshlrev_b32_e32 v37, 16, v37
; VI-NEXT:    v_lshlrev_b32_e32 v36, 16, v36
; VI-NEXT:    v_lshlrev_b32_e32 v35, 16, v35
; VI-NEXT:    v_lshlrev_b32_e32 v34, 16, v34
; VI-NEXT:    v_lshlrev_b32_e32 v33, 16, v33
; VI-NEXT:    v_lshlrev_b32_e32 v32, 16, v32
; VI-NEXT:    v_lshlrev_b32_e32 v31, 16, v31
; VI-NEXT:    v_lshlrev_b32_e32 v30, 16, v30
; VI-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; VI-NEXT:    v_lshlrev_b32_e32 v28, 16, v28
; VI-NEXT:    v_lshlrev_b32_e32 v27, 16, v27
; VI-NEXT:    v_lshlrev_b32_e32 v26, 16, v26
; VI-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; VI-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; VI-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; VI-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; VI-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; VI-NEXT:    v_or_b32_sdwa v0, v0, v39 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v1, v1, v38 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v2, v2, v37 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v3, v3, v36 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v4, v4, v35 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v5, v5, v34 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v6, v6, v33 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v7, v7, v32 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v8, v8, v31 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v9, v9, v30 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v10, v10, v29 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v11, v11, v28 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v12, v12, v27 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v13, v13, v26 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v14, v14, v25 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v15, v15, v24 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v16, v16, v23 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v17, v17, v22 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v18, v18, v21 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v19, v19, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v20i32_to_v40i16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    ; implicit-def: $vgpr39
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr35
; GFX9-NEXT:    ; implicit-def: $vgpr34
; GFX9-NEXT:    ; implicit-def: $vgpr33
; GFX9-NEXT:    ; implicit-def: $vgpr32
; GFX9-NEXT:    ; implicit-def: $vgpr31
; GFX9-NEXT:    ; implicit-def: $vgpr30
; GFX9-NEXT:    ; implicit-def: $vgpr29
; GFX9-NEXT:    ; implicit-def: $vgpr28
; GFX9-NEXT:    ; implicit-def: $vgpr27
; GFX9-NEXT:    ; implicit-def: $vgpr26
; GFX9-NEXT:    ; implicit-def: $vgpr25
; GFX9-NEXT:    ; implicit-def: $vgpr24
; GFX9-NEXT:    ; implicit-def: $vgpr23
; GFX9-NEXT:    ; implicit-def: $vgpr22
; GFX9-NEXT:    ; implicit-def: $vgpr21
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB12_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX9-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX9-NEXT:  .LBB12_2: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB12_4
; GFX9-NEXT:  ; %bb.3: ; %cmp.true
; GFX9-NEXT:    v_add_u32_e32 v19, 3, v19
; GFX9-NEXT:    v_add_u32_e32 v18, 3, v18
; GFX9-NEXT:    v_add_u32_e32 v17, 3, v17
; GFX9-NEXT:    v_add_u32_e32 v16, 3, v16
; GFX9-NEXT:    v_add_u32_e32 v15, 3, v15
; GFX9-NEXT:    v_add_u32_e32 v14, 3, v14
; GFX9-NEXT:    v_add_u32_e32 v13, 3, v13
; GFX9-NEXT:    v_add_u32_e32 v12, 3, v12
; GFX9-NEXT:    v_add_u32_e32 v11, 3, v11
; GFX9-NEXT:    v_add_u32_e32 v10, 3, v10
; GFX9-NEXT:    v_add_u32_e32 v9, 3, v9
; GFX9-NEXT:    v_add_u32_e32 v8, 3, v8
; GFX9-NEXT:    v_add_u32_e32 v7, 3, v7
; GFX9-NEXT:    v_add_u32_e32 v6, 3, v6
; GFX9-NEXT:    v_add_u32_e32 v5, 3, v5
; GFX9-NEXT:    v_add_u32_e32 v4, 3, v4
; GFX9-NEXT:    v_add_u32_e32 v3, 3, v3
; GFX9-NEXT:    v_add_u32_e32 v2, 3, v2
; GFX9-NEXT:    v_add_u32_e32 v1, 3, v1
; GFX9-NEXT:    v_add_u32_e32 v0, 3, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX9-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX9-NEXT:  .LBB12_4: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_mov_b32 s4, 0x5040100
; GFX9-NEXT:    v_perm_b32 v0, v39, v0, s4
; GFX9-NEXT:    v_perm_b32 v1, v38, v1, s4
; GFX9-NEXT:    v_perm_b32 v2, v37, v2, s4
; GFX9-NEXT:    v_perm_b32 v3, v36, v3, s4
; GFX9-NEXT:    v_perm_b32 v4, v35, v4, s4
; GFX9-NEXT:    v_perm_b32 v5, v34, v5, s4
; GFX9-NEXT:    v_perm_b32 v6, v33, v6, s4
; GFX9-NEXT:    v_perm_b32 v7, v32, v7, s4
; GFX9-NEXT:    v_perm_b32 v8, v31, v8, s4
; GFX9-NEXT:    v_perm_b32 v9, v30, v9, s4
; GFX9-NEXT:    v_perm_b32 v10, v29, v10, s4
; GFX9-NEXT:    v_perm_b32 v11, v28, v11, s4
; GFX9-NEXT:    v_perm_b32 v12, v27, v12, s4
; GFX9-NEXT:    v_perm_b32 v13, v26, v13, s4
; GFX9-NEXT:    v_perm_b32 v14, v25, v14, s4
; GFX9-NEXT:    v_perm_b32 v15, v24, v15, s4
; GFX9-NEXT:    v_perm_b32 v16, v23, v16, s4
; GFX9-NEXT:    v_perm_b32 v17, v22, v17, s4
; GFX9-NEXT:    v_perm_b32 v18, v21, v18, s4
; GFX9-NEXT:    v_perm_b32 v19, v20, v19, s4
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v20i32_to_v40i16:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB12_2
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v19, 3, v19
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v18, 3, v18
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v17, 3, v17
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v16, 3, v16
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v15, 3, v15
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v14, 3, v14
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v13, 3, v13
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v12, 3, v12
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v11, 3, v11
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v10, 3, v10
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v9, 3, v9
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v8, 3, v8
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v7, 3, v7
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, 3, v6
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v5, 3, v5
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v4, 3, v4
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 3, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, 3, v2
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, 3, v1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v0, 3, v0
; GFX11-TRUE16-NEXT:  .LBB12_2: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v20i32_to_v40i16:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr39
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr38
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr37
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr36
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr35
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr34
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr33
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr32
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr31
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr30
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr29
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr28
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr27
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr26
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr25
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr24
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr23
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr22
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr21
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB12_2
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX11-FAKE16-NEXT:  .LBB12_2: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB12_4
; GFX11-FAKE16-NEXT:  ; %bb.3: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v19, 3, v19
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v18, 3, v18
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v17, 3, v17
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v16, 3, v16
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v15, 3, v15
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v14, 3, v14
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v13, 3, v13
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v12, 3, v12
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v11, 3, v11
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v10, 3, v10
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v9, 3, v9
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v8, 3, v8
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v7, 3, v7
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v6, 3, v6
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v5, 3, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, 3, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, 3, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, 3, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v1, 3, v1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v0, 3, v0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX11-FAKE16-NEXT:  .LBB12_4: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v39, v0, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v38, v1, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v37, v2, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v36, v3, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v35, v4, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v34, v5, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v33, v6, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v32, v7, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, v31, v8, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, v30, v9, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, v29, v10, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, v28, v11, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, v27, v12, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, v26, v13, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v14, v25, v14, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v15, v24, v15, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v16, v23, v16, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v17, v22, v17, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v18, v21, v18, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v19, v20, v19, 0x5040100
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <20 x i32> %a, splat (i32 3)
  %a2 = bitcast <20 x i32> %a1 to <40 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <20 x i32> %a to <40 x i16>
  br label %end

end:
  %phi = phi <40 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <40 x i16> %phi
}

define inreg <40 x i16> @bitcast_v20i32_to_v40i16_scalar(<20 x i32> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v20i32_to_v40i16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_readfirstlane_b32 s8, v6
; SI-NEXT:    v_readfirstlane_b32 s5, v5
; SI-NEXT:    v_readfirstlane_b32 s4, v4
; SI-NEXT:    v_readfirstlane_b32 s7, v3
; SI-NEXT:    v_readfirstlane_b32 s6, v2
; SI-NEXT:    v_readfirstlane_b32 s9, v1
; SI-NEXT:    s_cmp_lg_u32 s8, 0
; SI-NEXT:    v_readfirstlane_b32 s8, v0
; SI-NEXT:    s_cbranch_scc0 .LBB13_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_lshr_b32 s72, s5, 16
; SI-NEXT:    s_lshr_b32 s73, s7, 16
; SI-NEXT:    s_lshr_b32 s74, s9, 16
; SI-NEXT:    s_lshr_b32 s75, s29, 16
; SI-NEXT:    s_lshr_b32 s76, s27, 16
; SI-NEXT:    s_lshr_b32 s77, s25, 16
; SI-NEXT:    s_lshr_b32 s78, s23, 16
; SI-NEXT:    s_lshr_b32 s79, s21, 16
; SI-NEXT:    s_lshr_b32 s88, s19, 16
; SI-NEXT:    s_lshr_b32 s89, s17, 16
; SI-NEXT:    s_lshr_b64 s[10:11], s[4:5], 16
; SI-NEXT:    s_lshr_b64 s[12:13], s[6:7], 16
; SI-NEXT:    s_lshr_b64 s[14:15], s[8:9], 16
; SI-NEXT:    s_lshr_b64 s[40:41], s[28:29], 16
; SI-NEXT:    s_lshr_b64 s[42:43], s[26:27], 16
; SI-NEXT:    s_lshr_b64 s[44:45], s[24:25], 16
; SI-NEXT:    s_lshr_b64 s[46:47], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[56:57], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[58:59], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[60:61], s[16:17], 16
; SI-NEXT:    s_cbranch_execnz .LBB13_3
; SI-NEXT:  .LBB13_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s17, s17, 3
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    s_add_i32 s19, s19, 3
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_add_i32 s21, s21, 3
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_add_i32 s23, s23, 3
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_add_i32 s25, s25, 3
; SI-NEXT:    s_add_i32 s24, s24, 3
; SI-NEXT:    s_add_i32 s27, s27, 3
; SI-NEXT:    s_add_i32 s26, s26, 3
; SI-NEXT:    s_add_i32 s29, s29, 3
; SI-NEXT:    s_add_i32 s28, s28, 3
; SI-NEXT:    s_add_i32 s9, s9, 3
; SI-NEXT:    s_add_i32 s8, s8, 3
; SI-NEXT:    s_add_i32 s7, s7, 3
; SI-NEXT:    s_add_i32 s6, s6, 3
; SI-NEXT:    s_add_i32 s5, s5, 3
; SI-NEXT:    s_add_i32 s4, s4, 3
; SI-NEXT:    s_lshr_b64 s[10:11], s[4:5], 16
; SI-NEXT:    s_lshr_b64 s[12:13], s[6:7], 16
; SI-NEXT:    s_lshr_b64 s[14:15], s[8:9], 16
; SI-NEXT:    s_lshr_b64 s[40:41], s[28:29], 16
; SI-NEXT:    s_lshr_b64 s[42:43], s[26:27], 16
; SI-NEXT:    s_lshr_b64 s[44:45], s[24:25], 16
; SI-NEXT:    s_lshr_b64 s[46:47], s[22:23], 16
; SI-NEXT:    s_lshr_b32 s72, s5, 16
; SI-NEXT:    s_lshr_b32 s73, s7, 16
; SI-NEXT:    s_lshr_b32 s74, s9, 16
; SI-NEXT:    s_lshr_b32 s75, s29, 16
; SI-NEXT:    s_lshr_b32 s76, s27, 16
; SI-NEXT:    s_lshr_b32 s77, s25, 16
; SI-NEXT:    s_lshr_b32 s78, s23, 16
; SI-NEXT:    s_lshr_b32 s79, s21, 16
; SI-NEXT:    s_lshr_b32 s88, s19, 16
; SI-NEXT:    s_lshr_b32 s89, s17, 16
; SI-NEXT:    s_lshr_b64 s[56:57], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[58:59], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[60:61], s[16:17], 16
; SI-NEXT:  .LBB13_3: ; %end
; SI-NEXT:    s_lshl_b32 s11, s60, 16
; SI-NEXT:    s_and_b32 s13, s16, 0xffff
; SI-NEXT:    s_or_b32 s11, s13, s11
; SI-NEXT:    s_and_b32 s13, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s15, s89, 16
; SI-NEXT:    s_or_b32 s13, s13, s15
; SI-NEXT:    s_lshl_b32 s15, s58, 16
; SI-NEXT:    s_and_b32 s16, s18, 0xffff
; SI-NEXT:    s_or_b32 s15, s16, s15
; SI-NEXT:    s_and_b32 s16, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s17, s88, 16
; SI-NEXT:    s_or_b32 s16, s16, s17
; SI-NEXT:    s_lshl_b32 s17, s56, 16
; SI-NEXT:    s_and_b32 s18, s20, 0xffff
; SI-NEXT:    s_or_b32 s17, s18, s17
; SI-NEXT:    s_and_b32 s18, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s19, s79, 16
; SI-NEXT:    s_or_b32 s18, s18, s19
; SI-NEXT:    s_and_b32 s19, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s20, s46, 16
; SI-NEXT:    s_or_b32 s19, s19, s20
; SI-NEXT:    s_and_b32 s20, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s21, s78, 16
; SI-NEXT:    s_or_b32 s20, s20, s21
; SI-NEXT:    s_and_b32 s21, s24, 0xffff
; SI-NEXT:    s_lshl_b32 s22, s44, 16
; SI-NEXT:    s_or_b32 s21, s21, s22
; SI-NEXT:    s_and_b32 s22, s25, 0xffff
; SI-NEXT:    s_lshl_b32 s23, s77, 16
; SI-NEXT:    s_or_b32 s22, s22, s23
; SI-NEXT:    s_and_b32 s23, s26, 0xffff
; SI-NEXT:    s_lshl_b32 s24, s42, 16
; SI-NEXT:    s_or_b32 s23, s23, s24
; SI-NEXT:    s_and_b32 s24, s27, 0xffff
; SI-NEXT:    s_lshl_b32 s25, s76, 16
; SI-NEXT:    s_or_b32 s24, s24, s25
; SI-NEXT:    s_and_b32 s25, s28, 0xffff
; SI-NEXT:    s_lshl_b32 s26, s40, 16
; SI-NEXT:    s_and_b32 s8, s8, 0xffff
; SI-NEXT:    s_lshl_b32 s14, s14, 16
; SI-NEXT:    s_and_b32 s6, s6, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s12, 16
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s10, 16
; SI-NEXT:    s_or_b32 s25, s25, s26
; SI-NEXT:    s_and_b32 s26, s29, 0xffff
; SI-NEXT:    s_lshl_b32 s27, s75, 16
; SI-NEXT:    s_or_b32 s8, s8, s14
; SI-NEXT:    s_and_b32 s9, s9, 0xffff
; SI-NEXT:    s_lshl_b32 s14, s74, 16
; SI-NEXT:    s_or_b32 s6, s6, s12
; SI-NEXT:    s_and_b32 s7, s7, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s73, 16
; SI-NEXT:    s_or_b32 s4, s4, s10
; SI-NEXT:    s_and_b32 s5, s5, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s72, 16
; SI-NEXT:    s_or_b32 s26, s26, s27
; SI-NEXT:    s_or_b32 s9, s9, s14
; SI-NEXT:    s_or_b32 s7, s7, s12
; SI-NEXT:    s_or_b32 s5, s5, s10
; SI-NEXT:    v_mov_b32_e32 v0, s11
; SI-NEXT:    v_mov_b32_e32 v1, s13
; SI-NEXT:    v_mov_b32_e32 v2, s15
; SI-NEXT:    v_mov_b32_e32 v3, s16
; SI-NEXT:    v_mov_b32_e32 v4, s17
; SI-NEXT:    v_mov_b32_e32 v5, s18
; SI-NEXT:    v_mov_b32_e32 v6, s19
; SI-NEXT:    v_mov_b32_e32 v7, s20
; SI-NEXT:    v_mov_b32_e32 v8, s21
; SI-NEXT:    v_mov_b32_e32 v9, s22
; SI-NEXT:    v_mov_b32_e32 v10, s23
; SI-NEXT:    v_mov_b32_e32 v11, s24
; SI-NEXT:    v_mov_b32_e32 v12, s25
; SI-NEXT:    v_mov_b32_e32 v13, s26
; SI-NEXT:    v_mov_b32_e32 v14, s8
; SI-NEXT:    v_mov_b32_e32 v15, s9
; SI-NEXT:    v_mov_b32_e32 v16, s6
; SI-NEXT:    v_mov_b32_e32 v17, s7
; SI-NEXT:    v_mov_b32_e32 v18, s4
; SI-NEXT:    v_mov_b32_e32 v19, s5
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB13_4:
; SI-NEXT:    ; implicit-def: $sgpr60
; SI-NEXT:    ; implicit-def: $sgpr89
; SI-NEXT:    ; implicit-def: $sgpr58
; SI-NEXT:    ; implicit-def: $sgpr88
; SI-NEXT:    ; implicit-def: $sgpr56
; SI-NEXT:    ; implicit-def: $sgpr79
; SI-NEXT:    ; implicit-def: $sgpr46
; SI-NEXT:    ; implicit-def: $sgpr78
; SI-NEXT:    ; implicit-def: $sgpr44
; SI-NEXT:    ; implicit-def: $sgpr77
; SI-NEXT:    ; implicit-def: $sgpr42
; SI-NEXT:    ; implicit-def: $sgpr76
; SI-NEXT:    ; implicit-def: $sgpr40
; SI-NEXT:    ; implicit-def: $sgpr75
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr74
; SI-NEXT:    ; implicit-def: $sgpr12
; SI-NEXT:    ; implicit-def: $sgpr73
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr72
; SI-NEXT:    s_branch .LBB13_2
;
; VI-LABEL: bitcast_v20i32_to_v40i16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    v_readfirstlane_b32 s6, v5
; VI-NEXT:    v_readfirstlane_b32 s7, v4
; VI-NEXT:    v_readfirstlane_b32 s8, v3
; VI-NEXT:    v_readfirstlane_b32 s9, v2
; VI-NEXT:    v_readfirstlane_b32 s10, v1
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    v_readfirstlane_b32 s11, v0
; VI-NEXT:    s_cbranch_scc0 .LBB13_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_lshr_b32 s12, s6, 16
; VI-NEXT:    s_lshr_b32 s13, s7, 16
; VI-NEXT:    s_lshr_b32 s14, s8, 16
; VI-NEXT:    s_lshr_b32 s15, s9, 16
; VI-NEXT:    s_lshr_b32 s40, s10, 16
; VI-NEXT:    s_lshr_b32 s41, s11, 16
; VI-NEXT:    s_lshr_b32 s42, s29, 16
; VI-NEXT:    s_lshr_b32 s43, s28, 16
; VI-NEXT:    s_lshr_b32 s44, s27, 16
; VI-NEXT:    s_lshr_b32 s45, s26, 16
; VI-NEXT:    s_lshr_b32 s46, s25, 16
; VI-NEXT:    s_lshr_b32 s47, s24, 16
; VI-NEXT:    s_lshr_b32 s56, s23, 16
; VI-NEXT:    s_lshr_b32 s57, s22, 16
; VI-NEXT:    s_lshr_b32 s58, s21, 16
; VI-NEXT:    s_lshr_b32 s59, s20, 16
; VI-NEXT:    s_lshr_b32 s60, s19, 16
; VI-NEXT:    s_lshr_b32 s61, s18, 16
; VI-NEXT:    s_lshr_b32 s62, s17, 16
; VI-NEXT:    s_lshr_b32 s63, s16, 16
; VI-NEXT:    s_cbranch_execnz .LBB13_3
; VI-NEXT:  .LBB13_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s6, s6, 3
; VI-NEXT:    s_add_i32 s7, s7, 3
; VI-NEXT:    s_add_i32 s8, s8, 3
; VI-NEXT:    s_add_i32 s9, s9, 3
; VI-NEXT:    s_add_i32 s10, s10, 3
; VI-NEXT:    s_add_i32 s11, s11, 3
; VI-NEXT:    s_add_i32 s29, s29, 3
; VI-NEXT:    s_add_i32 s28, s28, 3
; VI-NEXT:    s_add_i32 s27, s27, 3
; VI-NEXT:    s_add_i32 s26, s26, 3
; VI-NEXT:    s_add_i32 s25, s25, 3
; VI-NEXT:    s_add_i32 s24, s24, 3
; VI-NEXT:    s_add_i32 s23, s23, 3
; VI-NEXT:    s_add_i32 s22, s22, 3
; VI-NEXT:    s_add_i32 s21, s21, 3
; VI-NEXT:    s_add_i32 s20, s20, 3
; VI-NEXT:    s_add_i32 s19, s19, 3
; VI-NEXT:    s_add_i32 s18, s18, 3
; VI-NEXT:    s_add_i32 s17, s17, 3
; VI-NEXT:    s_add_i32 s16, s16, 3
; VI-NEXT:    s_lshr_b32 s12, s6, 16
; VI-NEXT:    s_lshr_b32 s13, s7, 16
; VI-NEXT:    s_lshr_b32 s14, s8, 16
; VI-NEXT:    s_lshr_b32 s15, s9, 16
; VI-NEXT:    s_lshr_b32 s40, s10, 16
; VI-NEXT:    s_lshr_b32 s41, s11, 16
; VI-NEXT:    s_lshr_b32 s42, s29, 16
; VI-NEXT:    s_lshr_b32 s43, s28, 16
; VI-NEXT:    s_lshr_b32 s44, s27, 16
; VI-NEXT:    s_lshr_b32 s45, s26, 16
; VI-NEXT:    s_lshr_b32 s46, s25, 16
; VI-NEXT:    s_lshr_b32 s47, s24, 16
; VI-NEXT:    s_lshr_b32 s56, s23, 16
; VI-NEXT:    s_lshr_b32 s57, s22, 16
; VI-NEXT:    s_lshr_b32 s58, s21, 16
; VI-NEXT:    s_lshr_b32 s59, s20, 16
; VI-NEXT:    s_lshr_b32 s60, s19, 16
; VI-NEXT:    s_lshr_b32 s61, s18, 16
; VI-NEXT:    s_lshr_b32 s62, s17, 16
; VI-NEXT:    s_lshr_b32 s63, s16, 16
; VI-NEXT:  .LBB13_3: ; %end
; VI-NEXT:    s_and_b32 s4, 0xffff, s16
; VI-NEXT:    s_lshl_b32 s5, s63, 16
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_and_b32 s5, 0xffff, s17
; VI-NEXT:    s_lshl_b32 s16, s62, 16
; VI-NEXT:    s_or_b32 s5, s5, s16
; VI-NEXT:    s_and_b32 s16, 0xffff, s18
; VI-NEXT:    s_lshl_b32 s17, s61, 16
; VI-NEXT:    s_or_b32 s16, s16, s17
; VI-NEXT:    s_and_b32 s17, 0xffff, s19
; VI-NEXT:    s_lshl_b32 s18, s60, 16
; VI-NEXT:    s_or_b32 s17, s17, s18
; VI-NEXT:    s_and_b32 s18, 0xffff, s20
; VI-NEXT:    s_lshl_b32 s19, s59, 16
; VI-NEXT:    s_or_b32 s18, s18, s19
; VI-NEXT:    s_and_b32 s19, 0xffff, s21
; VI-NEXT:    s_lshl_b32 s20, s58, 16
; VI-NEXT:    s_or_b32 s19, s19, s20
; VI-NEXT:    s_and_b32 s20, 0xffff, s22
; VI-NEXT:    s_lshl_b32 s21, s57, 16
; VI-NEXT:    s_or_b32 s20, s20, s21
; VI-NEXT:    s_and_b32 s21, 0xffff, s23
; VI-NEXT:    s_lshl_b32 s22, s56, 16
; VI-NEXT:    s_or_b32 s21, s21, s22
; VI-NEXT:    s_and_b32 s22, 0xffff, s24
; VI-NEXT:    s_lshl_b32 s23, s47, 16
; VI-NEXT:    s_or_b32 s22, s22, s23
; VI-NEXT:    s_and_b32 s23, 0xffff, s25
; VI-NEXT:    s_lshl_b32 s24, s46, 16
; VI-NEXT:    s_or_b32 s23, s23, s24
; VI-NEXT:    s_and_b32 s24, 0xffff, s26
; VI-NEXT:    s_lshl_b32 s25, s45, 16
; VI-NEXT:    s_or_b32 s24, s24, s25
; VI-NEXT:    s_and_b32 s25, 0xffff, s27
; VI-NEXT:    s_lshl_b32 s26, s44, 16
; VI-NEXT:    s_or_b32 s25, s25, s26
; VI-NEXT:    s_and_b32 s26, 0xffff, s28
; VI-NEXT:    s_lshl_b32 s27, s43, 16
; VI-NEXT:    s_or_b32 s26, s26, s27
; VI-NEXT:    s_and_b32 s27, 0xffff, s29
; VI-NEXT:    s_lshl_b32 s28, s42, 16
; VI-NEXT:    s_or_b32 s27, s27, s28
; VI-NEXT:    s_and_b32 s11, 0xffff, s11
; VI-NEXT:    s_lshl_b32 s28, s41, 16
; VI-NEXT:    s_or_b32 s11, s11, s28
; VI-NEXT:    s_and_b32 s10, 0xffff, s10
; VI-NEXT:    s_lshl_b32 s28, s40, 16
; VI-NEXT:    s_and_b32 s9, 0xffff, s9
; VI-NEXT:    s_lshl_b32 s15, s15, 16
; VI-NEXT:    s_and_b32 s8, 0xffff, s8
; VI-NEXT:    s_lshl_b32 s14, s14, 16
; VI-NEXT:    s_and_b32 s7, 0xffff, s7
; VI-NEXT:    s_lshl_b32 s13, s13, 16
; VI-NEXT:    s_and_b32 s6, 0xffff, s6
; VI-NEXT:    s_lshl_b32 s12, s12, 16
; VI-NEXT:    s_or_b32 s10, s10, s28
; VI-NEXT:    s_or_b32 s9, s9, s15
; VI-NEXT:    s_or_b32 s8, s8, s14
; VI-NEXT:    s_or_b32 s7, s7, s13
; VI-NEXT:    s_or_b32 s6, s6, s12
; VI-NEXT:    v_mov_b32_e32 v0, s4
; VI-NEXT:    v_mov_b32_e32 v1, s5
; VI-NEXT:    v_mov_b32_e32 v2, s16
; VI-NEXT:    v_mov_b32_e32 v3, s17
; VI-NEXT:    v_mov_b32_e32 v4, s18
; VI-NEXT:    v_mov_b32_e32 v5, s19
; VI-NEXT:    v_mov_b32_e32 v6, s20
; VI-NEXT:    v_mov_b32_e32 v7, s21
; VI-NEXT:    v_mov_b32_e32 v8, s22
; VI-NEXT:    v_mov_b32_e32 v9, s23
; VI-NEXT:    v_mov_b32_e32 v10, s24
; VI-NEXT:    v_mov_b32_e32 v11, s25
; VI-NEXT:    v_mov_b32_e32 v12, s26
; VI-NEXT:    v_mov_b32_e32 v13, s27
; VI-NEXT:    v_mov_b32_e32 v14, s11
; VI-NEXT:    v_mov_b32_e32 v15, s10
; VI-NEXT:    v_mov_b32_e32 v16, s9
; VI-NEXT:    v_mov_b32_e32 v17, s8
; VI-NEXT:    v_mov_b32_e32 v18, s7
; VI-NEXT:    v_mov_b32_e32 v19, s6
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB13_4:
; VI-NEXT:    ; implicit-def: $sgpr63
; VI-NEXT:    ; implicit-def: $sgpr62
; VI-NEXT:    ; implicit-def: $sgpr61
; VI-NEXT:    ; implicit-def: $sgpr60
; VI-NEXT:    ; implicit-def: $sgpr59
; VI-NEXT:    ; implicit-def: $sgpr58
; VI-NEXT:    ; implicit-def: $sgpr57
; VI-NEXT:    ; implicit-def: $sgpr56
; VI-NEXT:    ; implicit-def: $sgpr47
; VI-NEXT:    ; implicit-def: $sgpr46
; VI-NEXT:    ; implicit-def: $sgpr45
; VI-NEXT:    ; implicit-def: $sgpr44
; VI-NEXT:    ; implicit-def: $sgpr43
; VI-NEXT:    ; implicit-def: $sgpr42
; VI-NEXT:    ; implicit-def: $sgpr41
; VI-NEXT:    ; implicit-def: $sgpr40
; VI-NEXT:    ; implicit-def: $sgpr15
; VI-NEXT:    ; implicit-def: $sgpr14
; VI-NEXT:    ; implicit-def: $sgpr13
; VI-NEXT:    ; implicit-def: $sgpr12
; VI-NEXT:    s_branch .LBB13_2
;
; GFX9-LABEL: bitcast_v20i32_to_v40i16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_readfirstlane_b32 s4, v6
; GFX9-NEXT:    v_readfirstlane_b32 s6, v5
; GFX9-NEXT:    v_readfirstlane_b32 s7, v4
; GFX9-NEXT:    v_readfirstlane_b32 s8, v3
; GFX9-NEXT:    v_readfirstlane_b32 s9, v2
; GFX9-NEXT:    v_readfirstlane_b32 s10, v1
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    v_readfirstlane_b32 s11, v0
; GFX9-NEXT:    s_cbranch_scc0 .LBB13_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_lshr_b32 s12, s6, 16
; GFX9-NEXT:    s_lshr_b32 s13, s7, 16
; GFX9-NEXT:    s_lshr_b32 s14, s8, 16
; GFX9-NEXT:    s_lshr_b32 s15, s9, 16
; GFX9-NEXT:    s_lshr_b32 s40, s10, 16
; GFX9-NEXT:    s_lshr_b32 s41, s11, 16
; GFX9-NEXT:    s_lshr_b32 s42, s29, 16
; GFX9-NEXT:    s_lshr_b32 s43, s28, 16
; GFX9-NEXT:    s_lshr_b32 s44, s27, 16
; GFX9-NEXT:    s_lshr_b32 s45, s26, 16
; GFX9-NEXT:    s_lshr_b32 s46, s25, 16
; GFX9-NEXT:    s_lshr_b32 s47, s24, 16
; GFX9-NEXT:    s_lshr_b32 s56, s23, 16
; GFX9-NEXT:    s_lshr_b32 s57, s22, 16
; GFX9-NEXT:    s_lshr_b32 s58, s21, 16
; GFX9-NEXT:    s_lshr_b32 s59, s20, 16
; GFX9-NEXT:    s_lshr_b32 s60, s19, 16
; GFX9-NEXT:    s_lshr_b32 s61, s18, 16
; GFX9-NEXT:    s_lshr_b32 s62, s17, 16
; GFX9-NEXT:    s_lshr_b32 s63, s16, 16
; GFX9-NEXT:    s_cbranch_execnz .LBB13_3
; GFX9-NEXT:  .LBB13_2: ; %cmp.true
; GFX9-NEXT:    s_add_i32 s6, s6, 3
; GFX9-NEXT:    s_add_i32 s7, s7, 3
; GFX9-NEXT:    s_add_i32 s8, s8, 3
; GFX9-NEXT:    s_add_i32 s9, s9, 3
; GFX9-NEXT:    s_add_i32 s10, s10, 3
; GFX9-NEXT:    s_add_i32 s11, s11, 3
; GFX9-NEXT:    s_add_i32 s29, s29, 3
; GFX9-NEXT:    s_add_i32 s28, s28, 3
; GFX9-NEXT:    s_add_i32 s27, s27, 3
; GFX9-NEXT:    s_add_i32 s26, s26, 3
; GFX9-NEXT:    s_add_i32 s25, s25, 3
; GFX9-NEXT:    s_add_i32 s24, s24, 3
; GFX9-NEXT:    s_add_i32 s23, s23, 3
; GFX9-NEXT:    s_add_i32 s22, s22, 3
; GFX9-NEXT:    s_add_i32 s21, s21, 3
; GFX9-NEXT:    s_add_i32 s20, s20, 3
; GFX9-NEXT:    s_add_i32 s19, s19, 3
; GFX9-NEXT:    s_add_i32 s18, s18, 3
; GFX9-NEXT:    s_add_i32 s17, s17, 3
; GFX9-NEXT:    s_add_i32 s16, s16, 3
; GFX9-NEXT:    s_lshr_b32 s12, s6, 16
; GFX9-NEXT:    s_lshr_b32 s13, s7, 16
; GFX9-NEXT:    s_lshr_b32 s14, s8, 16
; GFX9-NEXT:    s_lshr_b32 s15, s9, 16
; GFX9-NEXT:    s_lshr_b32 s40, s10, 16
; GFX9-NEXT:    s_lshr_b32 s41, s11, 16
; GFX9-NEXT:    s_lshr_b32 s42, s29, 16
; GFX9-NEXT:    s_lshr_b32 s43, s28, 16
; GFX9-NEXT:    s_lshr_b32 s44, s27, 16
; GFX9-NEXT:    s_lshr_b32 s45, s26, 16
; GFX9-NEXT:    s_lshr_b32 s46, s25, 16
; GFX9-NEXT:    s_lshr_b32 s47, s24, 16
; GFX9-NEXT:    s_lshr_b32 s56, s23, 16
; GFX9-NEXT:    s_lshr_b32 s57, s22, 16
; GFX9-NEXT:    s_lshr_b32 s58, s21, 16
; GFX9-NEXT:    s_lshr_b32 s59, s20, 16
; GFX9-NEXT:    s_lshr_b32 s60, s19, 16
; GFX9-NEXT:    s_lshr_b32 s61, s18, 16
; GFX9-NEXT:    s_lshr_b32 s62, s17, 16
; GFX9-NEXT:    s_lshr_b32 s63, s16, 16
; GFX9-NEXT:  .LBB13_3: ; %end
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s16, s63
; GFX9-NEXT:    s_pack_ll_b32_b16 s5, s17, s62
; GFX9-NEXT:    s_pack_ll_b32_b16 s16, s18, s61
; GFX9-NEXT:    s_pack_ll_b32_b16 s17, s19, s60
; GFX9-NEXT:    s_pack_ll_b32_b16 s18, s20, s59
; GFX9-NEXT:    s_pack_ll_b32_b16 s19, s21, s58
; GFX9-NEXT:    s_pack_ll_b32_b16 s20, s22, s57
; GFX9-NEXT:    s_pack_ll_b32_b16 s21, s23, s56
; GFX9-NEXT:    s_pack_ll_b32_b16 s22, s24, s47
; GFX9-NEXT:    s_pack_ll_b32_b16 s23, s25, s46
; GFX9-NEXT:    s_pack_ll_b32_b16 s24, s26, s45
; GFX9-NEXT:    s_pack_ll_b32_b16 s25, s27, s44
; GFX9-NEXT:    s_pack_ll_b32_b16 s26, s28, s43
; GFX9-NEXT:    s_pack_ll_b32_b16 s27, s29, s42
; GFX9-NEXT:    s_pack_ll_b32_b16 s11, s11, s41
; GFX9-NEXT:    s_pack_ll_b32_b16 s10, s10, s40
; GFX9-NEXT:    s_pack_ll_b32_b16 s9, s9, s15
; GFX9-NEXT:    s_pack_ll_b32_b16 s8, s8, s14
; GFX9-NEXT:    s_pack_ll_b32_b16 s7, s7, s13
; GFX9-NEXT:    s_pack_ll_b32_b16 s6, s6, s12
; GFX9-NEXT:    v_mov_b32_e32 v0, s4
; GFX9-NEXT:    v_mov_b32_e32 v1, s5
; GFX9-NEXT:    v_mov_b32_e32 v2, s16
; GFX9-NEXT:    v_mov_b32_e32 v3, s17
; GFX9-NEXT:    v_mov_b32_e32 v4, s18
; GFX9-NEXT:    v_mov_b32_e32 v5, s19
; GFX9-NEXT:    v_mov_b32_e32 v6, s20
; GFX9-NEXT:    v_mov_b32_e32 v7, s21
; GFX9-NEXT:    v_mov_b32_e32 v8, s22
; GFX9-NEXT:    v_mov_b32_e32 v9, s23
; GFX9-NEXT:    v_mov_b32_e32 v10, s24
; GFX9-NEXT:    v_mov_b32_e32 v11, s25
; GFX9-NEXT:    v_mov_b32_e32 v12, s26
; GFX9-NEXT:    v_mov_b32_e32 v13, s27
; GFX9-NEXT:    v_mov_b32_e32 v14, s11
; GFX9-NEXT:    v_mov_b32_e32 v15, s10
; GFX9-NEXT:    v_mov_b32_e32 v16, s9
; GFX9-NEXT:    v_mov_b32_e32 v17, s8
; GFX9-NEXT:    v_mov_b32_e32 v18, s7
; GFX9-NEXT:    v_mov_b32_e32 v19, s6
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB13_4:
; GFX9-NEXT:    ; implicit-def: $sgpr63
; GFX9-NEXT:    ; implicit-def: $sgpr62
; GFX9-NEXT:    ; implicit-def: $sgpr61
; GFX9-NEXT:    ; implicit-def: $sgpr60
; GFX9-NEXT:    ; implicit-def: $sgpr59
; GFX9-NEXT:    ; implicit-def: $sgpr58
; GFX9-NEXT:    ; implicit-def: $sgpr57
; GFX9-NEXT:    ; implicit-def: $sgpr56
; GFX9-NEXT:    ; implicit-def: $sgpr47
; GFX9-NEXT:    ; implicit-def: $sgpr46
; GFX9-NEXT:    ; implicit-def: $sgpr45
; GFX9-NEXT:    ; implicit-def: $sgpr44
; GFX9-NEXT:    ; implicit-def: $sgpr43
; GFX9-NEXT:    ; implicit-def: $sgpr42
; GFX9-NEXT:    ; implicit-def: $sgpr41
; GFX9-NEXT:    ; implicit-def: $sgpr40
; GFX9-NEXT:    ; implicit-def: $sgpr15
; GFX9-NEXT:    ; implicit-def: $sgpr14
; GFX9-NEXT:    ; implicit-def: $sgpr13
; GFX9-NEXT:    ; implicit-def: $sgpr12
; GFX9-NEXT:    s_branch .LBB13_2
;
; GFX11-LABEL: bitcast_v20i32_to_v40i16_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    v_readfirstlane_b32 s6, v2
; GFX11-NEXT:    v_readfirstlane_b32 s4, v1
; GFX11-NEXT:    v_readfirstlane_b32 s5, v0
; GFX11-NEXT:    s_mov_b32 s58, 0
; GFX11-NEXT:    s_cmp_lg_u32 s6, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB13_4
; GFX11-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-NEXT:    s_lshr_b32 s6, s4, 16
; GFX11-NEXT:    s_lshr_b32 s7, s5, 16
; GFX11-NEXT:    s_lshr_b32 s8, s29, 16
; GFX11-NEXT:    s_lshr_b32 s9, s28, 16
; GFX11-NEXT:    s_lshr_b32 s10, s27, 16
; GFX11-NEXT:    s_lshr_b32 s11, s26, 16
; GFX11-NEXT:    s_lshr_b32 s12, s25, 16
; GFX11-NEXT:    s_lshr_b32 s13, s24, 16
; GFX11-NEXT:    s_lshr_b32 s14, s23, 16
; GFX11-NEXT:    s_lshr_b32 s15, s22, 16
; GFX11-NEXT:    s_lshr_b32 s40, s21, 16
; GFX11-NEXT:    s_lshr_b32 s41, s20, 16
; GFX11-NEXT:    s_lshr_b32 s42, s19, 16
; GFX11-NEXT:    s_lshr_b32 s43, s18, 16
; GFX11-NEXT:    s_lshr_b32 s44, s17, 16
; GFX11-NEXT:    s_lshr_b32 s45, s16, 16
; GFX11-NEXT:    s_lshr_b32 s46, s3, 16
; GFX11-NEXT:    s_lshr_b32 s47, s2, 16
; GFX11-NEXT:    s_lshr_b32 s56, s1, 16
; GFX11-NEXT:    s_lshr_b32 s57, s0, 16
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s58
; GFX11-NEXT:    s_cbranch_vccnz .LBB13_3
; GFX11-NEXT:  .LBB13_2: ; %cmp.true
; GFX11-NEXT:    s_add_i32 s4, s4, 3
; GFX11-NEXT:    s_add_i32 s5, s5, 3
; GFX11-NEXT:    s_add_i32 s29, s29, 3
; GFX11-NEXT:    s_add_i32 s28, s28, 3
; GFX11-NEXT:    s_add_i32 s27, s27, 3
; GFX11-NEXT:    s_add_i32 s26, s26, 3
; GFX11-NEXT:    s_add_i32 s25, s25, 3
; GFX11-NEXT:    s_add_i32 s24, s24, 3
; GFX11-NEXT:    s_add_i32 s23, s23, 3
; GFX11-NEXT:    s_add_i32 s22, s22, 3
; GFX11-NEXT:    s_add_i32 s21, s21, 3
; GFX11-NEXT:    s_add_i32 s20, s20, 3
; GFX11-NEXT:    s_add_i32 s19, s19, 3
; GFX11-NEXT:    s_add_i32 s18, s18, 3
; GFX11-NEXT:    s_add_i32 s17, s17, 3
; GFX11-NEXT:    s_add_i32 s16, s16, 3
; GFX11-NEXT:    s_add_i32 s3, s3, 3
; GFX11-NEXT:    s_add_i32 s2, s2, 3
; GFX11-NEXT:    s_add_i32 s1, s1, 3
; GFX11-NEXT:    s_add_i32 s0, s0, 3
; GFX11-NEXT:    s_lshr_b32 s6, s4, 16
; GFX11-NEXT:    s_lshr_b32 s7, s5, 16
; GFX11-NEXT:    s_lshr_b32 s8, s29, 16
; GFX11-NEXT:    s_lshr_b32 s9, s28, 16
; GFX11-NEXT:    s_lshr_b32 s10, s27, 16
; GFX11-NEXT:    s_lshr_b32 s11, s26, 16
; GFX11-NEXT:    s_lshr_b32 s12, s25, 16
; GFX11-NEXT:    s_lshr_b32 s13, s24, 16
; GFX11-NEXT:    s_lshr_b32 s14, s23, 16
; GFX11-NEXT:    s_lshr_b32 s15, s22, 16
; GFX11-NEXT:    s_lshr_b32 s40, s21, 16
; GFX11-NEXT:    s_lshr_b32 s41, s20, 16
; GFX11-NEXT:    s_lshr_b32 s42, s19, 16
; GFX11-NEXT:    s_lshr_b32 s43, s18, 16
; GFX11-NEXT:    s_lshr_b32 s44, s17, 16
; GFX11-NEXT:    s_lshr_b32 s45, s16, 16
; GFX11-NEXT:    s_lshr_b32 s46, s3, 16
; GFX11-NEXT:    s_lshr_b32 s47, s2, 16
; GFX11-NEXT:    s_lshr_b32 s56, s1, 16
; GFX11-NEXT:    s_lshr_b32 s57, s0, 16
; GFX11-NEXT:  .LBB13_3: ; %end
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_pack_ll_b32_b16 s0, s0, s57
; GFX11-NEXT:    s_pack_ll_b32_b16 s1, s1, s56
; GFX11-NEXT:    s_pack_ll_b32_b16 s2, s2, s47
; GFX11-NEXT:    s_pack_ll_b32_b16 s3, s3, s46
; GFX11-NEXT:    s_pack_ll_b32_b16 s16, s16, s45
; GFX11-NEXT:    s_pack_ll_b32_b16 s17, s17, s44
; GFX11-NEXT:    s_pack_ll_b32_b16 s18, s18, s43
; GFX11-NEXT:    s_pack_ll_b32_b16 s19, s19, s42
; GFX11-NEXT:    s_pack_ll_b32_b16 s20, s20, s41
; GFX11-NEXT:    s_pack_ll_b32_b16 s21, s21, s40
; GFX11-NEXT:    s_pack_ll_b32_b16 s15, s22, s15
; GFX11-NEXT:    s_pack_ll_b32_b16 s14, s23, s14
; GFX11-NEXT:    s_pack_ll_b32_b16 s13, s24, s13
; GFX11-NEXT:    s_pack_ll_b32_b16 s12, s25, s12
; GFX11-NEXT:    s_pack_ll_b32_b16 s11, s26, s11
; GFX11-NEXT:    s_pack_ll_b32_b16 s10, s27, s10
; GFX11-NEXT:    s_pack_ll_b32_b16 s9, s28, s9
; GFX11-NEXT:    s_pack_ll_b32_b16 s8, s29, s8
; GFX11-NEXT:    s_pack_ll_b32_b16 s5, s5, s7
; GFX11-NEXT:    s_pack_ll_b32_b16 s4, s4, s6
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s16 :: v_dual_mov_b32 v5, s17
; GFX11-NEXT:    v_dual_mov_b32 v6, s18 :: v_dual_mov_b32 v7, s19
; GFX11-NEXT:    v_dual_mov_b32 v8, s20 :: v_dual_mov_b32 v9, s21
; GFX11-NEXT:    v_dual_mov_b32 v10, s15 :: v_dual_mov_b32 v11, s14
; GFX11-NEXT:    v_dual_mov_b32 v12, s13 :: v_dual_mov_b32 v13, s12
; GFX11-NEXT:    v_dual_mov_b32 v14, s11 :: v_dual_mov_b32 v15, s10
; GFX11-NEXT:    v_dual_mov_b32 v16, s9 :: v_dual_mov_b32 v17, s8
; GFX11-NEXT:    v_dual_mov_b32 v18, s5 :: v_dual_mov_b32 v19, s4
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB13_4:
; GFX11-NEXT:    ; implicit-def: $sgpr57
; GFX11-NEXT:    ; implicit-def: $sgpr56
; GFX11-NEXT:    ; implicit-def: $sgpr47
; GFX11-NEXT:    ; implicit-def: $sgpr46
; GFX11-NEXT:    ; implicit-def: $sgpr45
; GFX11-NEXT:    ; implicit-def: $sgpr44
; GFX11-NEXT:    ; implicit-def: $sgpr43
; GFX11-NEXT:    ; implicit-def: $sgpr42
; GFX11-NEXT:    ; implicit-def: $sgpr41
; GFX11-NEXT:    ; implicit-def: $sgpr40
; GFX11-NEXT:    ; implicit-def: $sgpr15
; GFX11-NEXT:    ; implicit-def: $sgpr14
; GFX11-NEXT:    ; implicit-def: $sgpr13
; GFX11-NEXT:    ; implicit-def: $sgpr12
; GFX11-NEXT:    ; implicit-def: $sgpr11
; GFX11-NEXT:    ; implicit-def: $sgpr10
; GFX11-NEXT:    ; implicit-def: $sgpr9
; GFX11-NEXT:    ; implicit-def: $sgpr8
; GFX11-NEXT:    ; implicit-def: $sgpr7
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    s_branch .LBB13_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <20 x i32> %a, splat (i32 3)
  %a2 = bitcast <20 x i32> %a1 to <40 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <20 x i32> %a to <40 x i16>
  br label %end

end:
  %phi = phi <40 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <40 x i16> %phi
}

define <20 x i32> @bitcast_v40i16_to_v20i32(<40 x i16> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v40i16_to_v20i32:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v63, off, s[0:3], s32 ; 4-byte Folded Spill
; SI-NEXT:    v_mov_b32_e32 v32, v19
; SI-NEXT:    v_mov_b32_e32 v33, v18
; SI-NEXT:    v_mov_b32_e32 v34, v17
; SI-NEXT:    v_mov_b32_e32 v35, v16
; SI-NEXT:    v_mov_b32_e32 v36, v15
; SI-NEXT:    v_mov_b32_e32 v37, v14
; SI-NEXT:    v_mov_b32_e32 v38, v13
; SI-NEXT:    v_mov_b32_e32 v39, v12
; SI-NEXT:    v_mov_b32_e32 v48, v11
; SI-NEXT:    v_mov_b32_e32 v49, v10
; SI-NEXT:    v_mov_b32_e32 v50, v9
; SI-NEXT:    v_mov_b32_e32 v51, v8
; SI-NEXT:    v_mov_b32_e32 v52, v7
; SI-NEXT:    v_mov_b32_e32 v53, v6
; SI-NEXT:    v_mov_b32_e32 v54, v5
; SI-NEXT:    v_mov_b32_e32 v55, v4
; SI-NEXT:    v_mov_b32_e32 v40, v3
; SI-NEXT:    v_mov_b32_e32 v41, v2
; SI-NEXT:    v_mov_b32_e32 v42, v1
; SI-NEXT:    v_mov_b32_e32 v43, v0
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v32
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v33
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v34
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v35
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v36
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v37
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v38
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v39
; SI-NEXT:    v_lshrrev_b32_e32 v8, 16, v48
; SI-NEXT:    v_lshrrev_b32_e32 v9, 16, v49
; SI-NEXT:    v_lshrrev_b32_e32 v10, 16, v50
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v51
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v52
; SI-NEXT:    v_lshrrev_b32_e32 v13, 16, v53
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v54
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v55
; SI-NEXT:    v_lshrrev_b32_e32 v16, 16, v40
; SI-NEXT:    v_lshrrev_b32_e32 v17, 16, v41
; SI-NEXT:    v_lshrrev_b32_e32 v18, 16, v42
; SI-NEXT:    v_lshrrev_b32_e32 v19, 16, v43
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    s_waitcnt expcnt(4)
; SI-NEXT:    v_lshlrev_b32_e32 v59, 16, v19
; SI-NEXT:    v_lshlrev_b32_e32 v58, 16, v18
; SI-NEXT:    v_lshlrev_b32_e32 v57, 16, v17
; SI-NEXT:    v_lshlrev_b32_e32 v56, 16, v16
; SI-NEXT:    v_lshlrev_b32_e32 v47, 16, v15
; SI-NEXT:    v_lshlrev_b32_e32 v46, 16, v14
; SI-NEXT:    v_lshlrev_b32_e32 v45, 16, v13
; SI-NEXT:    v_lshlrev_b32_e32 v44, 16, v12
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshlrev_b32_e32 v63, 16, v11
; SI-NEXT:    v_lshlrev_b32_e32 v62, 16, v10
; SI-NEXT:    v_lshlrev_b32_e32 v61, 16, v9
; SI-NEXT:    v_lshlrev_b32_e32 v60, 16, v8
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:92 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:88 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:84 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:80 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:76 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:72 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:68 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:64 ; 4-byte Folded Spill
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB14_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:92 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:88 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:84 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:80 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:76 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:72 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v39
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v43
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v42
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v41
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v40
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v55
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v54
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v53
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v52
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v51
; SI-NEXT:    v_and_b32_e32 v9, 0xffff, v50
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v49
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v48
; SI-NEXT:    v_or_b32_e32 v0, v0, v59
; SI-NEXT:    v_or_b32_e32 v1, v1, v58
; SI-NEXT:    v_or_b32_e32 v2, v2, v57
; SI-NEXT:    v_or_b32_e32 v3, v3, v56
; SI-NEXT:    v_or_b32_e32 v4, v4, v47
; SI-NEXT:    v_or_b32_e32 v5, v5, v46
; SI-NEXT:    v_or_b32_e32 v6, v6, v45
; SI-NEXT:    v_or_b32_e32 v7, v7, v44
; SI-NEXT:    v_or_b32_e32 v8, v8, v63
; SI-NEXT:    v_or_b32_e32 v9, v9, v62
; SI-NEXT:    v_or_b32_e32 v10, v10, v61
; SI-NEXT:    v_or_b32_e32 v11, v11, v60
; SI-NEXT:    ; implicit-def: $vgpr43
; SI-NEXT:    ; implicit-def: $vgpr42
; SI-NEXT:    ; implicit-def: $vgpr41
; SI-NEXT:    ; implicit-def: $vgpr40
; SI-NEXT:    ; implicit-def: $vgpr55
; SI-NEXT:    ; implicit-def: $vgpr54
; SI-NEXT:    ; implicit-def: $vgpr53
; SI-NEXT:    ; implicit-def: $vgpr52
; SI-NEXT:    ; implicit-def: $vgpr51
; SI-NEXT:    ; implicit-def: $vgpr50
; SI-NEXT:    ; implicit-def: $vgpr49
; SI-NEXT:    ; implicit-def: $vgpr48
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:    ; implicit-def: $vgpr59
; SI-NEXT:    ; implicit-def: $vgpr58
; SI-NEXT:    ; implicit-def: $vgpr57
; SI-NEXT:    ; implicit-def: $vgpr56
; SI-NEXT:    ; implicit-def: $vgpr47
; SI-NEXT:    ; implicit-def: $vgpr46
; SI-NEXT:    ; implicit-def: $vgpr45
; SI-NEXT:    ; implicit-def: $vgpr44
; SI-NEXT:    ; implicit-def: $vgpr63
; SI-NEXT:    ; implicit-def: $vgpr62
; SI-NEXT:    ; implicit-def: $vgpr61
; SI-NEXT:    ; implicit-def: $vgpr60
; SI-NEXT:    s_waitcnt vmcnt(7)
; SI-NEXT:    v_or_b32_e32 v12, v12, v13
; SI-NEXT:    v_and_b32_e32 v13, 0xffff, v38
; SI-NEXT:    s_waitcnt vmcnt(6)
; SI-NEXT:    v_or_b32_e32 v13, v13, v14
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v37
; SI-NEXT:    s_waitcnt vmcnt(5)
; SI-NEXT:    v_or_b32_e32 v14, v14, v15
; SI-NEXT:    v_and_b32_e32 v15, 0xffff, v36
; SI-NEXT:    s_waitcnt vmcnt(4)
; SI-NEXT:    v_or_b32_e32 v15, v15, v16
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v35
; SI-NEXT:    s_waitcnt vmcnt(3)
; SI-NEXT:    v_or_b32_e32 v16, v16, v17
; SI-NEXT:    v_and_b32_e32 v17, 0xffff, v34
; SI-NEXT:    s_waitcnt vmcnt(2)
; SI-NEXT:    v_or_b32_e32 v17, v17, v18
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v33
; SI-NEXT:    s_waitcnt vmcnt(1)
; SI-NEXT:    v_or_b32_e32 v18, v18, v19
; SI-NEXT:    v_and_b32_e32 v19, 0xffff, v32
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_or_b32_e32 v19, v19, v20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:  .LBB14_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB14_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:92 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:88 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:84 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:80 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:76 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:72 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; SI-NEXT:    v_add_i32_e32 v12, vcc, 3, v39
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v43
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v42
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v41
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v40
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v55
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v54
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v53
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v52
; SI-NEXT:    v_add_i32_e32 v8, vcc, 3, v51
; SI-NEXT:    v_add_i32_e32 v9, vcc, 3, v50
; SI-NEXT:    v_add_i32_e32 v10, vcc, 3, v49
; SI-NEXT:    v_add_i32_e32 v11, vcc, 3, v48
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; SI-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; SI-NEXT:    v_or_b32_e32 v0, v59, v0
; SI-NEXT:    s_mov_b32 s6, 0x30000
; SI-NEXT:    v_or_b32_e32 v1, v58, v1
; SI-NEXT:    v_or_b32_e32 v2, v57, v2
; SI-NEXT:    v_or_b32_e32 v3, v56, v3
; SI-NEXT:    v_or_b32_e32 v4, v47, v4
; SI-NEXT:    v_or_b32_e32 v5, v46, v5
; SI-NEXT:    v_or_b32_e32 v6, v45, v6
; SI-NEXT:    v_or_b32_e32 v7, v44, v7
; SI-NEXT:    v_or_b32_e32 v8, v63, v8
; SI-NEXT:    v_or_b32_e32 v9, v62, v9
; SI-NEXT:    v_or_b32_e32 v10, v61, v10
; SI-NEXT:    v_or_b32_e32 v11, v60, v11
; SI-NEXT:    v_add_i32_e32 v0, vcc, 0x30000, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, s6, v1
; SI-NEXT:    v_add_i32_e32 v2, vcc, s6, v2
; SI-NEXT:    v_add_i32_e32 v3, vcc, s6, v3
; SI-NEXT:    v_add_i32_e32 v4, vcc, s6, v4
; SI-NEXT:    v_add_i32_e32 v5, vcc, s6, v5
; SI-NEXT:    v_add_i32_e32 v6, vcc, s6, v6
; SI-NEXT:    v_add_i32_e32 v7, vcc, s6, v7
; SI-NEXT:    v_add_i32_e32 v8, vcc, s6, v8
; SI-NEXT:    v_add_i32_e32 v9, vcc, s6, v9
; SI-NEXT:    s_waitcnt vmcnt(7)
; SI-NEXT:    v_or_b32_e32 v12, v13, v12
; SI-NEXT:    v_add_i32_e32 v13, vcc, 3, v38
; SI-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; SI-NEXT:    s_waitcnt vmcnt(6)
; SI-NEXT:    v_or_b32_e32 v13, v14, v13
; SI-NEXT:    v_add_i32_e32 v14, vcc, 3, v37
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; SI-NEXT:    s_waitcnt vmcnt(5)
; SI-NEXT:    v_or_b32_e32 v14, v15, v14
; SI-NEXT:    v_add_i32_e32 v15, vcc, 3, v36
; SI-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; SI-NEXT:    s_waitcnt vmcnt(4)
; SI-NEXT:    v_or_b32_e32 v15, v16, v15
; SI-NEXT:    v_add_i32_e32 v16, vcc, 3, v35
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v16
; SI-NEXT:    s_waitcnt vmcnt(3)
; SI-NEXT:    v_or_b32_e32 v16, v17, v16
; SI-NEXT:    v_add_i32_e32 v17, vcc, 3, v34
; SI-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; SI-NEXT:    s_waitcnt vmcnt(2)
; SI-NEXT:    v_or_b32_e32 v17, v18, v17
; SI-NEXT:    v_add_i32_e32 v18, vcc, 3, v33
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; SI-NEXT:    s_waitcnt vmcnt(1)
; SI-NEXT:    v_or_b32_e32 v18, v19, v18
; SI-NEXT:    v_add_i32_e32 v19, vcc, 3, v32
; SI-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_or_b32_e32 v19, v20, v19
; SI-NEXT:    v_add_i32_e32 v10, vcc, s6, v10
; SI-NEXT:    v_add_i32_e32 v11, vcc, s6, v11
; SI-NEXT:    v_add_i32_e32 v12, vcc, s6, v12
; SI-NEXT:    v_add_i32_e32 v13, vcc, s6, v13
; SI-NEXT:    v_add_i32_e32 v14, vcc, s6, v14
; SI-NEXT:    v_add_i32_e32 v15, vcc, s6, v15
; SI-NEXT:    v_add_i32_e32 v16, vcc, s6, v16
; SI-NEXT:    v_add_i32_e32 v17, vcc, s6, v17
; SI-NEXT:    v_add_i32_e32 v18, vcc, s6, v18
; SI-NEXT:    v_add_i32_e32 v19, vcc, 0x30000, v19
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:  .LBB14_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    buffer_load_dword v63, off, s[0:3], s32 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0)
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v40i16_to_v20i32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; VI-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; VI-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; VI-NEXT:    buffer_store_dword v43, off, s[0:3], s32 ; 4-byte Folded Spill
; VI-NEXT:    v_mov_b32_e32 v32, v19
; VI-NEXT:    v_mov_b32_e32 v33, v18
; VI-NEXT:    v_mov_b32_e32 v34, v17
; VI-NEXT:    v_mov_b32_e32 v35, v16
; VI-NEXT:    v_mov_b32_e32 v36, v15
; VI-NEXT:    v_mov_b32_e32 v37, v14
; VI-NEXT:    v_mov_b32_e32 v38, v13
; VI-NEXT:    v_mov_b32_e32 v39, v12
; VI-NEXT:    v_mov_b32_e32 v48, v11
; VI-NEXT:    v_mov_b32_e32 v49, v10
; VI-NEXT:    v_mov_b32_e32 v50, v9
; VI-NEXT:    v_mov_b32_e32 v51, v8
; VI-NEXT:    v_mov_b32_e32 v52, v7
; VI-NEXT:    v_mov_b32_e32 v53, v6
; VI-NEXT:    v_mov_b32_e32 v54, v5
; VI-NEXT:    v_mov_b32_e32 v55, v4
; VI-NEXT:    v_mov_b32_e32 v40, v3
; VI-NEXT:    v_mov_b32_e32 v41, v2
; VI-NEXT:    v_mov_b32_e32 v42, v1
; VI-NEXT:    v_mov_b32_e32 v43, v0
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB14_2
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_mov_b32_e32 v19, 16
; VI-NEXT:    v_lshlrev_b32_sdwa v0, v19, v43 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v1, v19, v42 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v2, v19, v41 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v3, v19, v40 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v4, v19, v55 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v5, v19, v54 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v6, v19, v53 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v7, v19, v52 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v8, v19, v51 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v9, v19, v50 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v10, v19, v49 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v11, v19, v48 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v12, v19, v39 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v13, v19, v38 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v14, v19, v37 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v15, v19, v36 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v16, v19, v35 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v17, v19, v34 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v18, v19, v33 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v19, v19, v32 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_or_b32_sdwa v0, v43, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v1, v42, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v2, v41, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v3, v40, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v4, v55, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v5, v54, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v6, v53, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v7, v52, v7 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v8, v51, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v9, v50, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v10, v49, v10 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v11, v48, v11 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v12, v39, v12 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v13, v38, v13 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v14, v37, v14 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v15, v36, v15 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v16, v35, v16 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v17, v34, v17 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v18, v33, v18 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v19, v32, v19 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr43
; VI-NEXT:    ; implicit-def: $vgpr42
; VI-NEXT:    ; implicit-def: $vgpr41
; VI-NEXT:    ; implicit-def: $vgpr40
; VI-NEXT:    ; implicit-def: $vgpr55
; VI-NEXT:    ; implicit-def: $vgpr54
; VI-NEXT:    ; implicit-def: $vgpr53
; VI-NEXT:    ; implicit-def: $vgpr52
; VI-NEXT:    ; implicit-def: $vgpr51
; VI-NEXT:    ; implicit-def: $vgpr50
; VI-NEXT:    ; implicit-def: $vgpr49
; VI-NEXT:    ; implicit-def: $vgpr48
; VI-NEXT:    ; implicit-def: $vgpr39
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr35
; VI-NEXT:    ; implicit-def: $vgpr34
; VI-NEXT:    ; implicit-def: $vgpr33
; VI-NEXT:    ; implicit-def: $vgpr32
; VI-NEXT:  .LBB14_2: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB14_4
; VI-NEXT:  ; %bb.3: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v19, 3
; VI-NEXT:    v_add_u16_e32 v0, 3, v43
; VI-NEXT:    v_add_u16_sdwa v1, v43, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v0, v0, v1
; VI-NEXT:    v_add_u16_e32 v1, 3, v42
; VI-NEXT:    v_add_u16_sdwa v2, v42, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v1, v1, v2
; VI-NEXT:    v_add_u16_e32 v2, 3, v41
; VI-NEXT:    v_add_u16_sdwa v3, v41, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v2, v2, v3
; VI-NEXT:    v_add_u16_e32 v3, 3, v40
; VI-NEXT:    v_add_u16_sdwa v4, v40, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v3, v3, v4
; VI-NEXT:    v_add_u16_e32 v4, 3, v55
; VI-NEXT:    v_add_u16_sdwa v5, v55, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v4, v4, v5
; VI-NEXT:    v_add_u16_e32 v5, 3, v54
; VI-NEXT:    v_add_u16_sdwa v6, v54, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v5, v5, v6
; VI-NEXT:    v_add_u16_e32 v6, 3, v53
; VI-NEXT:    v_add_u16_sdwa v7, v53, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v6, v6, v7
; VI-NEXT:    v_add_u16_e32 v7, 3, v52
; VI-NEXT:    v_add_u16_sdwa v8, v52, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v7, v7, v8
; VI-NEXT:    v_add_u16_e32 v8, 3, v51
; VI-NEXT:    v_add_u16_sdwa v9, v51, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v8, v8, v9
; VI-NEXT:    v_add_u16_e32 v9, 3, v50
; VI-NEXT:    v_add_u16_sdwa v10, v50, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v9, v9, v10
; VI-NEXT:    v_add_u16_e32 v10, 3, v49
; VI-NEXT:    v_add_u16_sdwa v11, v49, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v10, v10, v11
; VI-NEXT:    v_add_u16_e32 v11, 3, v48
; VI-NEXT:    v_add_u16_sdwa v12, v48, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v11, v11, v12
; VI-NEXT:    v_add_u16_e32 v12, 3, v39
; VI-NEXT:    v_add_u16_sdwa v13, v39, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v12, v12, v13
; VI-NEXT:    v_add_u16_e32 v13, 3, v38
; VI-NEXT:    v_add_u16_sdwa v14, v38, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v13, v13, v14
; VI-NEXT:    v_add_u16_e32 v14, 3, v37
; VI-NEXT:    v_add_u16_sdwa v15, v37, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v14, v14, v15
; VI-NEXT:    v_add_u16_e32 v15, 3, v36
; VI-NEXT:    v_add_u16_sdwa v16, v36, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v15, v15, v16
; VI-NEXT:    v_add_u16_e32 v16, 3, v35
; VI-NEXT:    v_add_u16_sdwa v17, v35, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v16, v16, v17
; VI-NEXT:    v_add_u16_e32 v17, 3, v34
; VI-NEXT:    v_add_u16_sdwa v18, v34, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v17, v17, v18
; VI-NEXT:    v_add_u16_e32 v18, 3, v33
; VI-NEXT:    v_add_u16_sdwa v20, v33, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v18, v18, v20
; VI-NEXT:    v_add_u16_e32 v20, 3, v32
; VI-NEXT:    v_add_u16_sdwa v19, v32, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v19, v20, v19
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:  .LBB14_4: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    buffer_load_dword v43, off, s[0:3], s32 ; 4-byte Folded Reload
; VI-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; VI-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; VI-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v40i16_to_v20i32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v63, off, s[0:3], s32 ; 4-byte Folded Spill
; GFX9-NEXT:    v_mov_b32_e32 v32, v19
; GFX9-NEXT:    v_mov_b32_e32 v33, v18
; GFX9-NEXT:    v_mov_b32_e32 v43, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v32
; GFX9-NEXT:    v_mov_b32_e32 v34, v17
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:64 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v33
; GFX9-NEXT:    v_mov_b32_e32 v35, v16
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:68 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v34
; GFX9-NEXT:    v_mov_b32_e32 v36, v15
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:72 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v35
; GFX9-NEXT:    v_mov_b32_e32 v37, v14
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:76 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v36
; GFX9-NEXT:    v_mov_b32_e32 v38, v13
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:80 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v37
; GFX9-NEXT:    v_mov_b32_e32 v39, v12
; GFX9-NEXT:    v_mov_b32_e32 v48, v11
; GFX9-NEXT:    v_mov_b32_e32 v49, v10
; GFX9-NEXT:    v_mov_b32_e32 v50, v9
; GFX9-NEXT:    v_mov_b32_e32 v51, v8
; GFX9-NEXT:    v_mov_b32_e32 v52, v7
; GFX9-NEXT:    v_mov_b32_e32 v53, v6
; GFX9-NEXT:    v_mov_b32_e32 v54, v5
; GFX9-NEXT:    v_mov_b32_e32 v55, v4
; GFX9-NEXT:    v_mov_b32_e32 v40, v3
; GFX9-NEXT:    v_mov_b32_e32 v41, v2
; GFX9-NEXT:    v_mov_b32_e32 v42, v1
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:84 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v38
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:88 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v39
; GFX9-NEXT:    v_lshrrev_b32_e32 v60, 16, v48
; GFX9-NEXT:    v_lshrrev_b32_e32 v61, 16, v49
; GFX9-NEXT:    v_lshrrev_b32_e32 v62, 16, v50
; GFX9-NEXT:    v_lshrrev_b32_e32 v63, 16, v51
; GFX9-NEXT:    v_lshrrev_b32_e32 v44, 16, v52
; GFX9-NEXT:    v_lshrrev_b32_e32 v45, 16, v53
; GFX9-NEXT:    v_lshrrev_b32_e32 v46, 16, v54
; GFX9-NEXT:    v_lshrrev_b32_e32 v47, 16, v55
; GFX9-NEXT:    v_lshrrev_b32_e32 v56, 16, v40
; GFX9-NEXT:    v_lshrrev_b32_e32 v57, 16, v41
; GFX9-NEXT:    v_lshrrev_b32_e32 v58, 16, v42
; GFX9-NEXT:    v_lshrrev_b32_e32 v59, 16, v43
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:92 ; 4-byte Folded Spill
; GFX9-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB14_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_mov_b32 s6, 0x5040100
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v12, 16, v39
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v13, 16, v38
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v14, 16, v37
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v15, 16, v36
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v16, 16, v35
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v17, 16, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v18, 16, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v19, 16, v32
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    v_perm_b32 v0, v59, v43, s6
; GFX9-NEXT:    v_perm_b32 v1, v58, v42, s6
; GFX9-NEXT:    v_perm_b32 v2, v57, v41, s6
; GFX9-NEXT:    v_perm_b32 v3, v56, v40, s6
; GFX9-NEXT:    v_perm_b32 v4, v47, v55, s6
; GFX9-NEXT:    v_perm_b32 v5, v46, v54, s6
; GFX9-NEXT:    v_perm_b32 v6, v45, v53, s6
; GFX9-NEXT:    v_perm_b32 v7, v44, v52, s6
; GFX9-NEXT:    v_perm_b32 v8, v63, v51, s6
; GFX9-NEXT:    v_perm_b32 v9, v62, v50, s6
; GFX9-NEXT:    v_perm_b32 v10, v61, v49, s6
; GFX9-NEXT:    v_perm_b32 v11, v60, v48, s6
; GFX9-NEXT:    v_perm_b32 v12, v12, v39, s6
; GFX9-NEXT:    v_perm_b32 v13, v13, v38, s6
; GFX9-NEXT:    v_perm_b32 v14, v14, v37, s6
; GFX9-NEXT:    v_perm_b32 v15, v15, v36, s6
; GFX9-NEXT:    v_perm_b32 v16, v16, v35, s6
; GFX9-NEXT:    v_perm_b32 v17, v17, v34, s6
; GFX9-NEXT:    v_perm_b32 v18, v18, v33, s6
; GFX9-NEXT:    v_perm_b32 v19, v19, v32, s6
; GFX9-NEXT:    ; implicit-def: $vgpr43
; GFX9-NEXT:    ; implicit-def: $vgpr42
; GFX9-NEXT:    ; implicit-def: $vgpr41
; GFX9-NEXT:    ; implicit-def: $vgpr40
; GFX9-NEXT:    ; implicit-def: $vgpr55
; GFX9-NEXT:    ; implicit-def: $vgpr54
; GFX9-NEXT:    ; implicit-def: $vgpr53
; GFX9-NEXT:    ; implicit-def: $vgpr52
; GFX9-NEXT:    ; implicit-def: $vgpr51
; GFX9-NEXT:    ; implicit-def: $vgpr50
; GFX9-NEXT:    ; implicit-def: $vgpr49
; GFX9-NEXT:    ; implicit-def: $vgpr48
; GFX9-NEXT:    ; implicit-def: $vgpr39
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr35
; GFX9-NEXT:    ; implicit-def: $vgpr34
; GFX9-NEXT:    ; implicit-def: $vgpr33
; GFX9-NEXT:    ; implicit-def: $vgpr32
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr60
; GFX9-NEXT:    ; implicit-def: $vgpr61
; GFX9-NEXT:    ; implicit-def: $vgpr62
; GFX9-NEXT:    ; implicit-def: $vgpr63
; GFX9-NEXT:    ; implicit-def: $vgpr44
; GFX9-NEXT:    ; implicit-def: $vgpr45
; GFX9-NEXT:    ; implicit-def: $vgpr46
; GFX9-NEXT:    ; implicit-def: $vgpr47
; GFX9-NEXT:    ; implicit-def: $vgpr56
; GFX9-NEXT:    ; implicit-def: $vgpr57
; GFX9-NEXT:    ; implicit-def: $vgpr58
; GFX9-NEXT:    ; implicit-def: $vgpr59
; GFX9-NEXT:  .LBB14_2: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB14_4
; GFX9-NEXT:  ; %bb.3: ; %cmp.true
; GFX9-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:92 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:88 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:84 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:80 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:76 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:72 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; GFX9-NEXT:    s_mov_b32 s6, 0x5040100
; GFX9-NEXT:    v_perm_b32 v0, v59, v43, s6
; GFX9-NEXT:    v_perm_b32 v1, v58, v42, s6
; GFX9-NEXT:    v_perm_b32 v2, v57, v41, s6
; GFX9-NEXT:    v_perm_b32 v3, v56, v40, s6
; GFX9-NEXT:    v_perm_b32 v4, v47, v55, s6
; GFX9-NEXT:    v_perm_b32 v5, v46, v54, s6
; GFX9-NEXT:    v_perm_b32 v6, v45, v53, s6
; GFX9-NEXT:    v_perm_b32 v7, v44, v52, s6
; GFX9-NEXT:    v_perm_b32 v8, v63, v51, s6
; GFX9-NEXT:    v_perm_b32 v9, v62, v50, s6
; GFX9-NEXT:    v_perm_b32 v10, v61, v49, s6
; GFX9-NEXT:    v_perm_b32 v11, v60, v48, s6
; GFX9-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v8, v8, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v9, v9, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_waitcnt vmcnt(7)
; GFX9-NEXT:    v_perm_b32 v12, v12, v39, s6
; GFX9-NEXT:    s_waitcnt vmcnt(6)
; GFX9-NEXT:    v_perm_b32 v13, v13, v38, s6
; GFX9-NEXT:    s_waitcnt vmcnt(5)
; GFX9-NEXT:    v_perm_b32 v14, v14, v37, s6
; GFX9-NEXT:    s_waitcnt vmcnt(4)
; GFX9-NEXT:    v_perm_b32 v15, v15, v36, s6
; GFX9-NEXT:    s_waitcnt vmcnt(3)
; GFX9-NEXT:    v_perm_b32 v16, v16, v35, s6
; GFX9-NEXT:    s_waitcnt vmcnt(2)
; GFX9-NEXT:    v_perm_b32 v17, v17, v34, s6
; GFX9-NEXT:    s_waitcnt vmcnt(1)
; GFX9-NEXT:    v_perm_b32 v18, v18, v33, s6
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    v_perm_b32 v19, v19, v32, s6
; GFX9-NEXT:    v_pk_add_u16 v12, v12, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v13, v13, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v14, v14, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v15, v15, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v16, v16, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v17, v17, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v18, v18, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v19, v19, 3 op_sel_hi:[1,0]
; GFX9-NEXT:  .LBB14_4: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    buffer_load_dword v63, off, s[0:3], s32 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Reload
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v40i16_to_v20i32:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB14_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB14_4
; GFX11-TRUE16-NEXT:  .LBB14_2: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB14_3: ; %cmp.false
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB14_2
; GFX11-TRUE16-NEXT:  .LBB14_4: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v8, v8, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v9, v9, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v12, v12, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v13, v13, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v14, v14, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v15, v15, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v16, v16, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v17, v17, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v18, v18, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v19, v19, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v40i16_to_v20i32:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v48, 16, v3
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v20
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v37, v0, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v38, v1, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v39, v2, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v48, v3, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v36, v4, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v35, v5, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v34, v6, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v33, v7, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, v32, v8, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, v31, v9, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, v30, v10, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, v29, v11, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, v28, v12, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, v27, v13, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v14, v26, v14, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v15, v25, v15, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v16, v24, v16, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v17, v23, v17, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v18, v22, v18, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v19, v21, v19, 0x5040100
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB14_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB14_4
; GFX11-FAKE16-NEXT:  .LBB14_2: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB14_3: ; %cmp.false
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB14_2
; GFX11-FAKE16-NEXT:  .LBB14_4: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v8, v8, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v9, v9, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v12, v12, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v13, v13, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v14, v14, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v15, v15, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v16, v16, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v17, v17, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v18, v18, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v19, v19, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <40 x i16> %a, splat (i16 3)
  %a2 = bitcast <40 x i16> %a1 to <20 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <40 x i16> %a to <20 x i32>
  br label %end

end:
  %phi = phi <20 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <20 x i32> %phi
}

define inreg <20 x i32> @bitcast_v40i16_to_v20i32_scalar(<40 x i16> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v40i16_to_v20i32_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_store_dword v20, off, s[0:3], s32 ; 4-byte Folded Spill
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_writelane_b32 v20, s36, 0
; SI-NEXT:    v_writelane_b32 v20, s37, 1
; SI-NEXT:    v_writelane_b32 v20, s38, 2
; SI-NEXT:    v_writelane_b32 v20, s39, 3
; SI-NEXT:    v_writelane_b32 v20, s48, 4
; SI-NEXT:    v_writelane_b32 v20, s49, 5
; SI-NEXT:    v_writelane_b32 v20, s50, 6
; SI-NEXT:    v_writelane_b32 v20, s51, 7
; SI-NEXT:    v_writelane_b32 v20, s52, 8
; SI-NEXT:    v_writelane_b32 v20, s53, 9
; SI-NEXT:    v_writelane_b32 v20, s54, 10
; SI-NEXT:    v_writelane_b32 v20, s55, 11
; SI-NEXT:    v_writelane_b32 v20, s64, 12
; SI-NEXT:    v_writelane_b32 v20, s65, 13
; SI-NEXT:    v_writelane_b32 v20, s66, 14
; SI-NEXT:    v_writelane_b32 v20, s67, 15
; SI-NEXT:    v_readfirstlane_b32 s7, v5
; SI-NEXT:    v_readfirstlane_b32 s9, v4
; SI-NEXT:    v_readfirstlane_b32 s12, v3
; SI-NEXT:    v_readfirstlane_b32 s15, v2
; SI-NEXT:    v_readfirstlane_b32 s74, v1
; SI-NEXT:    v_readfirstlane_b32 s77, v0
; SI-NEXT:    s_lshr_b32 s11, s29, 16
; SI-NEXT:    s_lshr_b32 s13, s28, 16
; SI-NEXT:    s_lshr_b32 s72, s27, 16
; SI-NEXT:    s_lshr_b32 s75, s26, 16
; SI-NEXT:    s_lshr_b32 s78, s25, 16
; SI-NEXT:    s_lshr_b32 s79, s24, 16
; SI-NEXT:    s_lshr_b32 s88, s23, 16
; SI-NEXT:    s_lshr_b32 s89, s22, 16
; SI-NEXT:    s_lshr_b32 s90, s21, 16
; SI-NEXT:    s_lshr_b32 s91, s20, 16
; SI-NEXT:    s_lshr_b32 s92, s19, 16
; SI-NEXT:    s_lshr_b32 s93, s18, 16
; SI-NEXT:    s_lshr_b32 s94, s17, 16
; SI-NEXT:    s_lshr_b32 s95, s16, 16
; SI-NEXT:    s_lshr_b32 s6, s7, 16
; SI-NEXT:    s_lshr_b32 s8, s9, 16
; SI-NEXT:    s_lshr_b32 s10, s12, 16
; SI-NEXT:    s_lshr_b32 s14, s15, 16
; SI-NEXT:    s_lshr_b32 s73, s74, 16
; SI-NEXT:    s_lshr_b32 s76, s77, 16
; SI-NEXT:    v_readfirstlane_b32 s4, v6
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    s_cbranch_scc0 .LBB15_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s95, 16
; SI-NEXT:    s_or_b32 s36, s4, s5
; SI-NEXT:    s_and_b32 s4, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s94, 16
; SI-NEXT:    s_or_b32 s37, s4, s5
; SI-NEXT:    s_and_b32 s4, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s93, 16
; SI-NEXT:    s_or_b32 s38, s4, s5
; SI-NEXT:    s_and_b32 s4, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s92, 16
; SI-NEXT:    s_or_b32 s39, s4, s5
; SI-NEXT:    s_and_b32 s4, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s91, 16
; SI-NEXT:    s_or_b32 s40, s4, s5
; SI-NEXT:    s_and_b32 s4, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s90, 16
; SI-NEXT:    s_or_b32 s41, s4, s5
; SI-NEXT:    s_and_b32 s4, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s89, 16
; SI-NEXT:    s_or_b32 s42, s4, s5
; SI-NEXT:    s_and_b32 s4, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s88, 16
; SI-NEXT:    s_or_b32 s43, s4, s5
; SI-NEXT:    s_and_b32 s4, s24, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s79, 16
; SI-NEXT:    s_or_b32 s44, s4, s5
; SI-NEXT:    s_and_b32 s4, s25, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s78, 16
; SI-NEXT:    s_or_b32 s45, s4, s5
; SI-NEXT:    s_and_b32 s4, s26, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s75, 16
; SI-NEXT:    s_or_b32 s46, s4, s5
; SI-NEXT:    s_and_b32 s4, s27, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s72, 16
; SI-NEXT:    s_or_b32 s47, s4, s5
; SI-NEXT:    s_and_b32 s4, s28, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s13, 16
; SI-NEXT:    s_or_b32 s48, s4, s5
; SI-NEXT:    s_and_b32 s4, s29, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s11, 16
; SI-NEXT:    s_or_b32 s49, s4, s5
; SI-NEXT:    s_and_b32 s4, s77, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s76, 16
; SI-NEXT:    s_or_b32 s50, s4, s5
; SI-NEXT:    s_and_b32 s4, s74, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s73, 16
; SI-NEXT:    s_or_b32 s51, s4, s5
; SI-NEXT:    s_and_b32 s4, s15, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s14, 16
; SI-NEXT:    s_or_b32 s52, s4, s5
; SI-NEXT:    s_and_b32 s4, s12, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s10, 16
; SI-NEXT:    s_or_b32 s53, s4, s5
; SI-NEXT:    s_and_b32 s4, s9, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s8, 16
; SI-NEXT:    s_or_b32 s54, s4, s5
; SI-NEXT:    s_and_b32 s4, s7, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s6, 16
; SI-NEXT:    s_or_b32 s55, s4, s5
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    s_cbranch_execnz .LBB15_3
; SI-NEXT:  .LBB15_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s95, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s17, s17, 3
; SI-NEXT:    s_add_i32 s36, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s94, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_add_i32 s37, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s93, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s19, s19, 3
; SI-NEXT:    s_add_i32 s38, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s92, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_add_i32 s39, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s91, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s21, s21, 3
; SI-NEXT:    s_add_i32 s40, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s90, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_add_i32 s41, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s89, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s23, s23, 3
; SI-NEXT:    s_add_i32 s42, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s88, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s24, s24, 3
; SI-NEXT:    s_add_i32 s43, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s24, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s79, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s25, s25, 3
; SI-NEXT:    s_add_i32 s44, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s25, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s78, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s26, s26, 3
; SI-NEXT:    s_add_i32 s45, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s26, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s75, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s27, s27, 3
; SI-NEXT:    s_add_i32 s46, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s27, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s72, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s28, s28, 3
; SI-NEXT:    s_add_i32 s47, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s28, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s13, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s29, s29, 3
; SI-NEXT:    s_add_i32 s48, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s29, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s11, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s77, s77, 3
; SI-NEXT:    s_add_i32 s49, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s77, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s76, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s74, s74, 3
; SI-NEXT:    s_add_i32 s50, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s74, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s73, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s15, s15, 3
; SI-NEXT:    s_add_i32 s51, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s15, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s14, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s12, s12, 3
; SI-NEXT:    s_add_i32 s52, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s12, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s10, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s9, s9, 3
; SI-NEXT:    s_add_i32 s53, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s9, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s8, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s7, s7, 3
; SI-NEXT:    s_add_i32 s54, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s7, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s6, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s55, s4, 0x30000
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:  .LBB15_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v0, s36
; SI-NEXT:    v_mov_b32_e32 v1, s37
; SI-NEXT:    v_mov_b32_e32 v2, s38
; SI-NEXT:    v_mov_b32_e32 v3, s39
; SI-NEXT:    v_mov_b32_e32 v4, s40
; SI-NEXT:    v_mov_b32_e32 v5, s41
; SI-NEXT:    v_mov_b32_e32 v6, s42
; SI-NEXT:    v_mov_b32_e32 v7, s43
; SI-NEXT:    v_mov_b32_e32 v8, s44
; SI-NEXT:    v_mov_b32_e32 v9, s45
; SI-NEXT:    v_mov_b32_e32 v10, s46
; SI-NEXT:    v_mov_b32_e32 v11, s47
; SI-NEXT:    v_mov_b32_e32 v12, s48
; SI-NEXT:    v_mov_b32_e32 v13, s49
; SI-NEXT:    v_mov_b32_e32 v14, s50
; SI-NEXT:    v_mov_b32_e32 v15, s51
; SI-NEXT:    v_mov_b32_e32 v16, s52
; SI-NEXT:    v_mov_b32_e32 v17, s53
; SI-NEXT:    v_mov_b32_e32 v18, s54
; SI-NEXT:    v_mov_b32_e32 v19, s55
; SI-NEXT:    v_readlane_b32 s67, v20, 15
; SI-NEXT:    v_readlane_b32 s66, v20, 14
; SI-NEXT:    v_readlane_b32 s65, v20, 13
; SI-NEXT:    v_readlane_b32 s64, v20, 12
; SI-NEXT:    v_readlane_b32 s55, v20, 11
; SI-NEXT:    v_readlane_b32 s54, v20, 10
; SI-NEXT:    v_readlane_b32 s53, v20, 9
; SI-NEXT:    v_readlane_b32 s52, v20, 8
; SI-NEXT:    v_readlane_b32 s51, v20, 7
; SI-NEXT:    v_readlane_b32 s50, v20, 6
; SI-NEXT:    v_readlane_b32 s49, v20, 5
; SI-NEXT:    v_readlane_b32 s48, v20, 4
; SI-NEXT:    v_readlane_b32 s39, v20, 3
; SI-NEXT:    v_readlane_b32 s38, v20, 2
; SI-NEXT:    v_readlane_b32 s37, v20, 1
; SI-NEXT:    v_readlane_b32 s36, v20, 0
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_load_dword v20, off, s[0:3], s32 ; 4-byte Folded Reload
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB15_4:
; SI-NEXT:    ; implicit-def: $sgpr36_sgpr37_sgpr38_sgpr39_sgpr40_sgpr41_sgpr42_sgpr43_sgpr44_sgpr45_sgpr46_sgpr47_sgpr48_sgpr49_sgpr50_sgpr51_sgpr52_sgpr53_sgpr54_sgpr55_sgpr56_sgpr57_sgpr58_sgpr59_sgpr60_sgpr61_sgpr62_sgpr63_sgpr64_sgpr65_sgpr66_sgpr67
; SI-NEXT:    s_branch .LBB15_2
;
; VI-LABEL: bitcast_v40i16_to_v20i32_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_store_dword v20, off, s[0:3], s32 ; 4-byte Folded Spill
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    v_writelane_b32 v20, s34, 0
; VI-NEXT:    v_writelane_b32 v20, s35, 1
; VI-NEXT:    v_writelane_b32 v20, s36, 2
; VI-NEXT:    v_writelane_b32 v20, s37, 3
; VI-NEXT:    v_writelane_b32 v20, s38, 4
; VI-NEXT:    v_writelane_b32 v20, s39, 5
; VI-NEXT:    v_writelane_b32 v20, s48, 6
; VI-NEXT:    v_writelane_b32 v20, s49, 7
; VI-NEXT:    v_writelane_b32 v20, s50, 8
; VI-NEXT:    v_writelane_b32 v20, s51, 9
; VI-NEXT:    v_writelane_b32 v20, s52, 10
; VI-NEXT:    v_writelane_b32 v20, s53, 11
; VI-NEXT:    v_writelane_b32 v20, s54, 12
; VI-NEXT:    v_writelane_b32 v20, s55, 13
; VI-NEXT:    v_writelane_b32 v20, s64, 14
; VI-NEXT:    v_writelane_b32 v20, s65, 15
; VI-NEXT:    v_writelane_b32 v20, s66, 16
; VI-NEXT:    v_writelane_b32 v20, s67, 17
; VI-NEXT:    v_writelane_b32 v20, s30, 18
; VI-NEXT:    v_writelane_b32 v20, s31, 19
; VI-NEXT:    v_readfirstlane_b32 s7, v5
; VI-NEXT:    v_readfirstlane_b32 s9, v4
; VI-NEXT:    v_readfirstlane_b32 s12, v3
; VI-NEXT:    v_readfirstlane_b32 s15, v2
; VI-NEXT:    v_readfirstlane_b32 s74, v1
; VI-NEXT:    v_readfirstlane_b32 s77, v0
; VI-NEXT:    s_lshr_b32 s11, s29, 16
; VI-NEXT:    s_lshr_b32 s13, s28, 16
; VI-NEXT:    s_lshr_b32 s72, s27, 16
; VI-NEXT:    s_lshr_b32 s75, s26, 16
; VI-NEXT:    s_lshr_b32 s78, s25, 16
; VI-NEXT:    s_lshr_b32 s79, s24, 16
; VI-NEXT:    s_lshr_b32 s88, s23, 16
; VI-NEXT:    s_lshr_b32 s89, s22, 16
; VI-NEXT:    s_lshr_b32 s90, s21, 16
; VI-NEXT:    s_lshr_b32 s91, s20, 16
; VI-NEXT:    s_lshr_b32 s30, s19, 16
; VI-NEXT:    s_lshr_b32 s31, s18, 16
; VI-NEXT:    s_lshr_b32 s34, s17, 16
; VI-NEXT:    s_lshr_b32 s35, s16, 16
; VI-NEXT:    s_lshr_b32 s6, s7, 16
; VI-NEXT:    s_lshr_b32 s8, s9, 16
; VI-NEXT:    s_lshr_b32 s10, s12, 16
; VI-NEXT:    s_lshr_b32 s14, s15, 16
; VI-NEXT:    s_lshr_b32 s73, s74, 16
; VI-NEXT:    s_lshr_b32 s76, s77, 16
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    s_cbranch_scc0 .LBB15_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_and_b32 s4, 0xffff, s16
; VI-NEXT:    s_lshl_b32 s5, s35, 16
; VI-NEXT:    s_or_b32 s36, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s17
; VI-NEXT:    s_lshl_b32 s5, s34, 16
; VI-NEXT:    s_or_b32 s37, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s18
; VI-NEXT:    s_lshl_b32 s5, s31, 16
; VI-NEXT:    s_or_b32 s38, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s19
; VI-NEXT:    s_lshl_b32 s5, s30, 16
; VI-NEXT:    s_or_b32 s39, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s20
; VI-NEXT:    s_lshl_b32 s5, s91, 16
; VI-NEXT:    s_or_b32 s40, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s21
; VI-NEXT:    s_lshl_b32 s5, s90, 16
; VI-NEXT:    s_or_b32 s41, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s22
; VI-NEXT:    s_lshl_b32 s5, s89, 16
; VI-NEXT:    s_or_b32 s42, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s23
; VI-NEXT:    s_lshl_b32 s5, s88, 16
; VI-NEXT:    s_or_b32 s43, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s24
; VI-NEXT:    s_lshl_b32 s5, s79, 16
; VI-NEXT:    s_or_b32 s44, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s25
; VI-NEXT:    s_lshl_b32 s5, s78, 16
; VI-NEXT:    s_or_b32 s45, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s26
; VI-NEXT:    s_lshl_b32 s5, s75, 16
; VI-NEXT:    s_or_b32 s46, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s27
; VI-NEXT:    s_lshl_b32 s5, s72, 16
; VI-NEXT:    s_or_b32 s47, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s28
; VI-NEXT:    s_lshl_b32 s5, s13, 16
; VI-NEXT:    s_or_b32 s48, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s29
; VI-NEXT:    s_lshl_b32 s5, s11, 16
; VI-NEXT:    s_or_b32 s49, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s77
; VI-NEXT:    s_lshl_b32 s5, s76, 16
; VI-NEXT:    s_or_b32 s50, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s74
; VI-NEXT:    s_lshl_b32 s5, s73, 16
; VI-NEXT:    s_or_b32 s51, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s15
; VI-NEXT:    s_lshl_b32 s5, s14, 16
; VI-NEXT:    s_or_b32 s52, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s12
; VI-NEXT:    s_lshl_b32 s5, s10, 16
; VI-NEXT:    s_or_b32 s53, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s9
; VI-NEXT:    s_lshl_b32 s5, s8, 16
; VI-NEXT:    s_or_b32 s54, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s7
; VI-NEXT:    s_lshl_b32 s5, s6, 16
; VI-NEXT:    s_or_b32 s55, s4, s5
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    s_cbranch_execnz .LBB15_3
; VI-NEXT:  .LBB15_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s16, s16, 3
; VI-NEXT:    s_and_b32 s4, s16, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s35, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s17, s17, 3
; VI-NEXT:    s_add_i32 s36, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s17, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s34, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s18, s18, 3
; VI-NEXT:    s_add_i32 s37, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s18, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s31, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s19, s19, 3
; VI-NEXT:    s_add_i32 s38, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s19, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s30, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s20, s20, 3
; VI-NEXT:    s_add_i32 s39, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s20, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s91, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s21, s21, 3
; VI-NEXT:    s_add_i32 s40, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s21, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s90, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s22, s22, 3
; VI-NEXT:    s_add_i32 s41, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s22, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s89, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s23, s23, 3
; VI-NEXT:    s_add_i32 s42, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s23, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s88, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s24, s24, 3
; VI-NEXT:    s_add_i32 s43, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s24, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s79, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s25, s25, 3
; VI-NEXT:    s_add_i32 s44, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s25, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s78, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s26, s26, 3
; VI-NEXT:    s_add_i32 s45, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s26, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s75, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s27, s27, 3
; VI-NEXT:    s_add_i32 s46, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s27, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s72, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s28, s28, 3
; VI-NEXT:    s_add_i32 s47, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s28, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s13, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s29, s29, 3
; VI-NEXT:    s_add_i32 s48, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s29, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s11, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s77, s77, 3
; VI-NEXT:    s_add_i32 s49, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s77, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s76, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s74, s74, 3
; VI-NEXT:    s_add_i32 s50, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s74, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s73, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s15, s15, 3
; VI-NEXT:    s_add_i32 s51, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s15, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s14, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s12, s12, 3
; VI-NEXT:    s_add_i32 s52, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s12, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s10, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s9, s9, 3
; VI-NEXT:    s_add_i32 s53, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s9, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s8, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s7, s7, 3
; VI-NEXT:    s_add_i32 s54, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s7, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s6, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s55, s4, 0x30000
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:  .LBB15_3: ; %end
; VI-NEXT:    v_readlane_b32 s30, v20, 18
; VI-NEXT:    v_mov_b32_e32 v0, s36
; VI-NEXT:    v_mov_b32_e32 v1, s37
; VI-NEXT:    v_mov_b32_e32 v2, s38
; VI-NEXT:    v_mov_b32_e32 v3, s39
; VI-NEXT:    v_mov_b32_e32 v4, s40
; VI-NEXT:    v_mov_b32_e32 v5, s41
; VI-NEXT:    v_mov_b32_e32 v6, s42
; VI-NEXT:    v_mov_b32_e32 v7, s43
; VI-NEXT:    v_mov_b32_e32 v8, s44
; VI-NEXT:    v_mov_b32_e32 v9, s45
; VI-NEXT:    v_mov_b32_e32 v10, s46
; VI-NEXT:    v_mov_b32_e32 v11, s47
; VI-NEXT:    v_mov_b32_e32 v12, s48
; VI-NEXT:    v_mov_b32_e32 v13, s49
; VI-NEXT:    v_mov_b32_e32 v14, s50
; VI-NEXT:    v_mov_b32_e32 v15, s51
; VI-NEXT:    v_mov_b32_e32 v16, s52
; VI-NEXT:    v_mov_b32_e32 v17, s53
; VI-NEXT:    v_mov_b32_e32 v18, s54
; VI-NEXT:    v_mov_b32_e32 v19, s55
; VI-NEXT:    v_readlane_b32 s31, v20, 19
; VI-NEXT:    v_readlane_b32 s67, v20, 17
; VI-NEXT:    v_readlane_b32 s66, v20, 16
; VI-NEXT:    v_readlane_b32 s65, v20, 15
; VI-NEXT:    v_readlane_b32 s64, v20, 14
; VI-NEXT:    v_readlane_b32 s55, v20, 13
; VI-NEXT:    v_readlane_b32 s54, v20, 12
; VI-NEXT:    v_readlane_b32 s53, v20, 11
; VI-NEXT:    v_readlane_b32 s52, v20, 10
; VI-NEXT:    v_readlane_b32 s51, v20, 9
; VI-NEXT:    v_readlane_b32 s50, v20, 8
; VI-NEXT:    v_readlane_b32 s49, v20, 7
; VI-NEXT:    v_readlane_b32 s48, v20, 6
; VI-NEXT:    v_readlane_b32 s39, v20, 5
; VI-NEXT:    v_readlane_b32 s38, v20, 4
; VI-NEXT:    v_readlane_b32 s37, v20, 3
; VI-NEXT:    v_readlane_b32 s36, v20, 2
; VI-NEXT:    v_readlane_b32 s35, v20, 1
; VI-NEXT:    v_readlane_b32 s34, v20, 0
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_load_dword v20, off, s[0:3], s32 ; 4-byte Folded Reload
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB15_4:
; VI-NEXT:    ; implicit-def: $sgpr36_sgpr37_sgpr38_sgpr39_sgpr40_sgpr41_sgpr42_sgpr43_sgpr44_sgpr45_sgpr46_sgpr47_sgpr48_sgpr49_sgpr50_sgpr51_sgpr52_sgpr53_sgpr54_sgpr55_sgpr56_sgpr57_sgpr58_sgpr59_sgpr60_sgpr61_sgpr62_sgpr63_sgpr64_sgpr65_sgpr66_sgpr67
; VI-NEXT:    s_branch .LBB15_2
;
; GFX9-LABEL: bitcast_v40i16_to_v20i32_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    v_writelane_b32 v32, s36, 0
; GFX9-NEXT:    v_writelane_b32 v32, s37, 1
; GFX9-NEXT:    v_writelane_b32 v32, s38, 2
; GFX9-NEXT:    v_writelane_b32 v32, s39, 3
; GFX9-NEXT:    v_writelane_b32 v32, s48, 4
; GFX9-NEXT:    v_writelane_b32 v32, s49, 5
; GFX9-NEXT:    v_writelane_b32 v32, s50, 6
; GFX9-NEXT:    v_writelane_b32 v32, s51, 7
; GFX9-NEXT:    v_writelane_b32 v32, s52, 8
; GFX9-NEXT:    v_writelane_b32 v32, s53, 9
; GFX9-NEXT:    v_writelane_b32 v32, s54, 10
; GFX9-NEXT:    v_writelane_b32 v32, s55, 11
; GFX9-NEXT:    v_readfirstlane_b32 s56, v5
; GFX9-NEXT:    v_readfirstlane_b32 s58, v4
; GFX9-NEXT:    v_readfirstlane_b32 s60, v3
; GFX9-NEXT:    v_readfirstlane_b32 s62, v2
; GFX9-NEXT:    v_readfirstlane_b32 s72, v1
; GFX9-NEXT:    v_readfirstlane_b32 s74, v0
; GFX9-NEXT:    s_lshr_b32 s4, s29, 16
; GFX9-NEXT:    s_lshr_b32 s5, s28, 16
; GFX9-NEXT:    s_lshr_b32 s6, s27, 16
; GFX9-NEXT:    s_lshr_b32 s7, s26, 16
; GFX9-NEXT:    s_lshr_b32 s8, s25, 16
; GFX9-NEXT:    s_lshr_b32 s9, s24, 16
; GFX9-NEXT:    s_lshr_b32 s10, s23, 16
; GFX9-NEXT:    s_lshr_b32 s11, s22, 16
; GFX9-NEXT:    s_lshr_b32 s12, s21, 16
; GFX9-NEXT:    s_lshr_b32 s13, s20, 16
; GFX9-NEXT:    s_lshr_b32 s14, s19, 16
; GFX9-NEXT:    s_lshr_b32 s15, s18, 16
; GFX9-NEXT:    s_lshr_b32 s40, s17, 16
; GFX9-NEXT:    s_lshr_b32 s41, s16, 16
; GFX9-NEXT:    s_lshr_b32 s57, s56, 16
; GFX9-NEXT:    s_lshr_b32 s59, s58, 16
; GFX9-NEXT:    s_lshr_b32 s61, s60, 16
; GFX9-NEXT:    s_lshr_b32 s63, s62, 16
; GFX9-NEXT:    s_lshr_b32 s73, s72, 16
; GFX9-NEXT:    s_lshr_b32 s75, s74, 16
; GFX9-NEXT:    v_readfirstlane_b32 s42, v6
; GFX9-NEXT:    s_cmp_lg_u32 s42, 0
; GFX9-NEXT:    s_pack_ll_b32_b16 s36, s16, s41
; GFX9-NEXT:    s_pack_ll_b32_b16 s37, s17, s40
; GFX9-NEXT:    s_pack_ll_b32_b16 s38, s18, s15
; GFX9-NEXT:    s_pack_ll_b32_b16 s39, s19, s14
; GFX9-NEXT:    s_pack_ll_b32_b16 s40, s20, s13
; GFX9-NEXT:    s_pack_ll_b32_b16 s41, s21, s12
; GFX9-NEXT:    s_pack_ll_b32_b16 s42, s22, s11
; GFX9-NEXT:    s_pack_ll_b32_b16 s43, s23, s10
; GFX9-NEXT:    s_pack_ll_b32_b16 s44, s24, s9
; GFX9-NEXT:    s_pack_ll_b32_b16 s45, s25, s8
; GFX9-NEXT:    s_pack_ll_b32_b16 s46, s26, s7
; GFX9-NEXT:    s_pack_ll_b32_b16 s47, s27, s6
; GFX9-NEXT:    s_pack_ll_b32_b16 s48, s28, s5
; GFX9-NEXT:    s_pack_ll_b32_b16 s49, s29, s4
; GFX9-NEXT:    s_pack_ll_b32_b16 s50, s74, s75
; GFX9-NEXT:    s_pack_ll_b32_b16 s51, s72, s73
; GFX9-NEXT:    s_pack_ll_b32_b16 s52, s62, s63
; GFX9-NEXT:    s_pack_ll_b32_b16 s53, s60, s61
; GFX9-NEXT:    s_pack_ll_b32_b16 s54, s58, s59
; GFX9-NEXT:    s_pack_ll_b32_b16 s55, s56, s57
; GFX9-NEXT:    s_cbranch_scc0 .LBB15_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB15_4
; GFX9-NEXT:  .LBB15_2: ; %cmp.true
; GFX9-NEXT:    v_pk_add_u16 v0, s36, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v1, s37, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v2, s38, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v3, s39, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v4, s40, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v5, s41, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, s42, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v7, s43, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v8, s44, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v9, s45, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v10, s46, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v11, s47, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v12, s48, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v13, s49, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v14, s50, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v15, s51, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v16, s52, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v17, s53, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v18, s54, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v19, s55, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_branch .LBB15_5
; GFX9-NEXT:  .LBB15_3:
; GFX9-NEXT:    s_branch .LBB15_2
; GFX9-NEXT:  .LBB15_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s36
; GFX9-NEXT:    v_mov_b32_e32 v1, s37
; GFX9-NEXT:    v_mov_b32_e32 v2, s38
; GFX9-NEXT:    v_mov_b32_e32 v3, s39
; GFX9-NEXT:    v_mov_b32_e32 v4, s40
; GFX9-NEXT:    v_mov_b32_e32 v5, s41
; GFX9-NEXT:    v_mov_b32_e32 v6, s42
; GFX9-NEXT:    v_mov_b32_e32 v7, s43
; GFX9-NEXT:    v_mov_b32_e32 v8, s44
; GFX9-NEXT:    v_mov_b32_e32 v9, s45
; GFX9-NEXT:    v_mov_b32_e32 v10, s46
; GFX9-NEXT:    v_mov_b32_e32 v11, s47
; GFX9-NEXT:    v_mov_b32_e32 v12, s48
; GFX9-NEXT:    v_mov_b32_e32 v13, s49
; GFX9-NEXT:    v_mov_b32_e32 v14, s50
; GFX9-NEXT:    v_mov_b32_e32 v15, s51
; GFX9-NEXT:    v_mov_b32_e32 v16, s52
; GFX9-NEXT:    v_mov_b32_e32 v17, s53
; GFX9-NEXT:    v_mov_b32_e32 v18, s54
; GFX9-NEXT:    v_mov_b32_e32 v19, s55
; GFX9-NEXT:    v_mov_b32_e32 v20, s56
; GFX9-NEXT:    v_mov_b32_e32 v21, s57
; GFX9-NEXT:    v_mov_b32_e32 v22, s58
; GFX9-NEXT:    v_mov_b32_e32 v23, s59
; GFX9-NEXT:    v_mov_b32_e32 v24, s60
; GFX9-NEXT:    v_mov_b32_e32 v25, s61
; GFX9-NEXT:    v_mov_b32_e32 v26, s62
; GFX9-NEXT:    v_mov_b32_e32 v27, s63
; GFX9-NEXT:    v_mov_b32_e32 v28, s64
; GFX9-NEXT:    v_mov_b32_e32 v29, s65
; GFX9-NEXT:    v_mov_b32_e32 v30, s66
; GFX9-NEXT:    v_mov_b32_e32 v31, s67
; GFX9-NEXT:  .LBB15_5: ; %end
; GFX9-NEXT:    v_readlane_b32 s55, v32, 11
; GFX9-NEXT:    v_readlane_b32 s54, v32, 10
; GFX9-NEXT:    v_readlane_b32 s53, v32, 9
; GFX9-NEXT:    v_readlane_b32 s52, v32, 8
; GFX9-NEXT:    v_readlane_b32 s51, v32, 7
; GFX9-NEXT:    v_readlane_b32 s50, v32, 6
; GFX9-NEXT:    v_readlane_b32 s49, v32, 5
; GFX9-NEXT:    v_readlane_b32 s48, v32, 4
; GFX9-NEXT:    v_readlane_b32 s39, v32, 3
; GFX9-NEXT:    v_readlane_b32 s38, v32, 2
; GFX9-NEXT:    v_readlane_b32 s37, v32, 1
; GFX9-NEXT:    v_readlane_b32 s36, v32, 0
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v40i16_to_v20i32_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    v_readfirstlane_b32 s45, v1
; GFX11-NEXT:    v_readfirstlane_b32 s46, v0
; GFX11-NEXT:    v_readfirstlane_b32 s56, v2
; GFX11-NEXT:    s_lshr_b32 s41, s29, 16
; GFX11-NEXT:    s_lshr_b32 s42, s28, 16
; GFX11-NEXT:    s_lshr_b32 s15, s27, 16
; GFX11-NEXT:    s_lshr_b32 s14, s26, 16
; GFX11-NEXT:    s_lshr_b32 s13, s25, 16
; GFX11-NEXT:    s_lshr_b32 s12, s24, 16
; GFX11-NEXT:    s_lshr_b32 s11, s23, 16
; GFX11-NEXT:    s_lshr_b32 s10, s22, 16
; GFX11-NEXT:    s_lshr_b32 s9, s21, 16
; GFX11-NEXT:    s_lshr_b32 s8, s20, 16
; GFX11-NEXT:    s_lshr_b32 s7, s19, 16
; GFX11-NEXT:    s_lshr_b32 s6, s18, 16
; GFX11-NEXT:    s_lshr_b32 s5, s17, 16
; GFX11-NEXT:    s_lshr_b32 s4, s16, 16
; GFX11-NEXT:    s_lshr_b32 s43, s3, 16
; GFX11-NEXT:    s_lshr_b32 s44, s2, 16
; GFX11-NEXT:    s_lshr_b32 s47, s1, 16
; GFX11-NEXT:    s_lshr_b32 s57, s0, 16
; GFX11-NEXT:    s_lshr_b32 s58, s45, 16
; GFX11-NEXT:    s_lshr_b32 s59, s46, 16
; GFX11-NEXT:    s_mov_b32 s40, 0
; GFX11-NEXT:    s_cmp_lg_u32 s56, 0
; GFX11-NEXT:    s_pack_ll_b32_b16 s0, s0, s57
; GFX11-NEXT:    s_pack_ll_b32_b16 s1, s1, s47
; GFX11-NEXT:    s_pack_ll_b32_b16 s2, s2, s44
; GFX11-NEXT:    s_pack_ll_b32_b16 s3, s3, s43
; GFX11-NEXT:    s_pack_ll_b32_b16 s4, s16, s4
; GFX11-NEXT:    s_pack_ll_b32_b16 s5, s17, s5
; GFX11-NEXT:    s_pack_ll_b32_b16 s6, s18, s6
; GFX11-NEXT:    s_pack_ll_b32_b16 s7, s19, s7
; GFX11-NEXT:    s_pack_ll_b32_b16 s8, s20, s8
; GFX11-NEXT:    s_pack_ll_b32_b16 s9, s21, s9
; GFX11-NEXT:    s_pack_ll_b32_b16 s10, s22, s10
; GFX11-NEXT:    s_pack_ll_b32_b16 s11, s23, s11
; GFX11-NEXT:    s_pack_ll_b32_b16 s12, s24, s12
; GFX11-NEXT:    s_pack_ll_b32_b16 s13, s25, s13
; GFX11-NEXT:    s_pack_ll_b32_b16 s14, s26, s14
; GFX11-NEXT:    s_pack_ll_b32_b16 s15, s27, s15
; GFX11-NEXT:    s_pack_ll_b32_b16 s16, s28, s42
; GFX11-NEXT:    s_pack_ll_b32_b16 s17, s29, s41
; GFX11-NEXT:    s_pack_ll_b32_b16 s18, s46, s59
; GFX11-NEXT:    s_pack_ll_b32_b16 s19, s45, s58
; GFX11-NEXT:    s_cbranch_scc0 .LBB15_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s40
; GFX11-NEXT:    s_cbranch_vccnz .LBB15_4
; GFX11-NEXT:  .LBB15_2: ; %cmp.true
; GFX11-NEXT:    v_pk_add_u16 v0, s0, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v1, s1, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v2, s2, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v3, s3, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v4, s4, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v5, s5, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v6, s6, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v7, s7, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v8, s8, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v9, s9, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v10, s10, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v11, s11, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v12, s12, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v13, s13, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v14, s14, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v15, s15, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v16, s16, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v17, s17, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v18, s18, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v19, s19, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB15_3:
; GFX11-NEXT:    s_branch .LBB15_2
; GFX11-NEXT:  .LBB15_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    v_dual_mov_b32 v8, s8 :: v_dual_mov_b32 v9, s9
; GFX11-NEXT:    v_dual_mov_b32 v10, s10 :: v_dual_mov_b32 v11, s11
; GFX11-NEXT:    v_dual_mov_b32 v12, s12 :: v_dual_mov_b32 v13, s13
; GFX11-NEXT:    v_dual_mov_b32 v14, s14 :: v_dual_mov_b32 v15, s15
; GFX11-NEXT:    v_dual_mov_b32 v16, s16 :: v_dual_mov_b32 v17, s17
; GFX11-NEXT:    v_dual_mov_b32 v18, s18 :: v_dual_mov_b32 v19, s19
; GFX11-NEXT:    v_dual_mov_b32 v20, s20 :: v_dual_mov_b32 v21, s21
; GFX11-NEXT:    v_dual_mov_b32 v22, s22 :: v_dual_mov_b32 v23, s23
; GFX11-NEXT:    v_dual_mov_b32 v24, s24 :: v_dual_mov_b32 v25, s25
; GFX11-NEXT:    v_dual_mov_b32 v26, s26 :: v_dual_mov_b32 v27, s27
; GFX11-NEXT:    v_dual_mov_b32 v28, s28 :: v_dual_mov_b32 v29, s29
; GFX11-NEXT:    v_dual_mov_b32 v30, s30 :: v_dual_mov_b32 v31, s31
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <40 x i16> %a, splat (i16 3)
  %a2 = bitcast <40 x i16> %a1 to <20 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <40 x i16> %a to <20 x i32>
  br label %end

end:
  %phi = phi <20 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <20 x i32> %phi
}

define <40 x half> @bitcast_v20i32_to_v40f16(<20 x i32> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v20i32_to_v40f16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:    ; implicit-def: $vgpr31
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr29
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr26
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr25
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr24
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr30
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr28
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr27
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB16_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_alignbit_b32 v20, v19, v18, 16
; SI-NEXT:    v_alignbit_b32 v21, v17, v16, 16
; SI-NEXT:    v_alignbit_b32 v22, v15, v14, 16
; SI-NEXT:    v_alignbit_b32 v23, v13, v12, 16
; SI-NEXT:    v_alignbit_b32 v24, v11, v10, 16
; SI-NEXT:    v_alignbit_b32 v25, v9, v8, 16
; SI-NEXT:    v_alignbit_b32 v26, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v29, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v31, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v34, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v27, 16, v19
; SI-NEXT:    v_lshrrev_b32_e32 v28, 16, v17
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v15
; SI-NEXT:    v_lshrrev_b32_e32 v32, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v33, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v35, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v36, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v37, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v39, 16, v1
; SI-NEXT:  .LBB16_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB16_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v1
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v3
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v5
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v7
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; SI-NEXT:    v_add_i32_e32 v9, vcc, 3, v9
; SI-NEXT:    v_add_i32_e32 v8, vcc, 3, v8
; SI-NEXT:    v_add_i32_e32 v11, vcc, 3, v11
; SI-NEXT:    v_add_i32_e32 v10, vcc, 3, v10
; SI-NEXT:    v_add_i32_e32 v13, vcc, 3, v13
; SI-NEXT:    v_add_i32_e32 v12, vcc, 3, v12
; SI-NEXT:    v_add_i32_e32 v15, vcc, 3, v15
; SI-NEXT:    v_add_i32_e32 v14, vcc, 3, v14
; SI-NEXT:    v_add_i32_e32 v17, vcc, 3, v17
; SI-NEXT:    v_add_i32_e32 v16, vcc, 3, v16
; SI-NEXT:    v_add_i32_e32 v19, vcc, 3, v19
; SI-NEXT:    v_add_i32_e32 v18, vcc, 3, v18
; SI-NEXT:    v_alignbit_b32 v20, v19, v18, 16
; SI-NEXT:    v_alignbit_b32 v21, v17, v16, 16
; SI-NEXT:    v_alignbit_b32 v22, v15, v14, 16
; SI-NEXT:    v_alignbit_b32 v23, v13, v12, 16
; SI-NEXT:    v_alignbit_b32 v24, v11, v10, 16
; SI-NEXT:    v_alignbit_b32 v25, v9, v8, 16
; SI-NEXT:    v_alignbit_b32 v26, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v29, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v31, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v34, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v27, 16, v19
; SI-NEXT:    v_lshrrev_b32_e32 v28, 16, v17
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v15
; SI-NEXT:    v_lshrrev_b32_e32 v32, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v33, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v35, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v36, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v37, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v39, 16, v1
; SI-NEXT:  .LBB16_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v34, 16, v34
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v31, 16, v31
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v26, 16, v26
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; SI-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; SI-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v16
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; SI-NEXT:    v_or_b32_e32 v0, v0, v34
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v34, 16, v39
; SI-NEXT:    v_or_b32_e32 v2, v2, v31
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v31, 16, v38
; SI-NEXT:    v_or_b32_e32 v4, v4, v29
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v29, 16, v37
; SI-NEXT:    v_or_b32_e32 v6, v6, v26
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v26, 16, v36
; SI-NEXT:    v_or_b32_e32 v8, v8, v25
; SI-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; SI-NEXT:    v_lshlrev_b32_e32 v25, 16, v35
; SI-NEXT:    v_or_b32_e32 v10, v10, v24
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; SI-NEXT:    v_lshlrev_b32_e32 v24, 16, v33
; SI-NEXT:    v_or_b32_e32 v12, v12, v23
; SI-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v32
; SI-NEXT:    v_or_b32_e32 v14, v14, v22
; SI-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v30
; SI-NEXT:    v_or_b32_e32 v16, v16, v21
; SI-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v28
; SI-NEXT:    v_or_b32_e32 v18, v18, v20
; SI-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v27
; SI-NEXT:    v_or_b32_e32 v1, v1, v34
; SI-NEXT:    v_or_b32_e32 v3, v3, v31
; SI-NEXT:    v_or_b32_e32 v5, v5, v29
; SI-NEXT:    v_or_b32_e32 v7, v7, v26
; SI-NEXT:    v_or_b32_e32 v9, v9, v25
; SI-NEXT:    v_or_b32_e32 v11, v11, v24
; SI-NEXT:    v_or_b32_e32 v13, v13, v23
; SI-NEXT:    v_or_b32_e32 v15, v15, v22
; SI-NEXT:    v_or_b32_e32 v17, v17, v21
; SI-NEXT:    v_or_b32_e32 v19, v19, v20
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v20i32_to_v40f16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    ; implicit-def: $vgpr39
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr35
; VI-NEXT:    ; implicit-def: $vgpr34
; VI-NEXT:    ; implicit-def: $vgpr33
; VI-NEXT:    ; implicit-def: $vgpr32
; VI-NEXT:    ; implicit-def: $vgpr31
; VI-NEXT:    ; implicit-def: $vgpr30
; VI-NEXT:    ; implicit-def: $vgpr29
; VI-NEXT:    ; implicit-def: $vgpr28
; VI-NEXT:    ; implicit-def: $vgpr27
; VI-NEXT:    ; implicit-def: $vgpr26
; VI-NEXT:    ; implicit-def: $vgpr25
; VI-NEXT:    ; implicit-def: $vgpr24
; VI-NEXT:    ; implicit-def: $vgpr23
; VI-NEXT:    ; implicit-def: $vgpr22
; VI-NEXT:    ; implicit-def: $vgpr21
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB16_2
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; VI-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; VI-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; VI-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; VI-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; VI-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; VI-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; VI-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; VI-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; VI-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; VI-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; VI-NEXT:  .LBB16_2: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB16_4
; VI-NEXT:  ; %bb.3: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v19, vcc, 3, v19
; VI-NEXT:    v_add_u32_e32 v18, vcc, 3, v18
; VI-NEXT:    v_add_u32_e32 v17, vcc, 3, v17
; VI-NEXT:    v_add_u32_e32 v16, vcc, 3, v16
; VI-NEXT:    v_add_u32_e32 v15, vcc, 3, v15
; VI-NEXT:    v_add_u32_e32 v14, vcc, 3, v14
; VI-NEXT:    v_add_u32_e32 v13, vcc, 3, v13
; VI-NEXT:    v_add_u32_e32 v12, vcc, 3, v12
; VI-NEXT:    v_add_u32_e32 v11, vcc, 3, v11
; VI-NEXT:    v_add_u32_e32 v10, vcc, 3, v10
; VI-NEXT:    v_add_u32_e32 v9, vcc, 3, v9
; VI-NEXT:    v_add_u32_e32 v8, vcc, 3, v8
; VI-NEXT:    v_add_u32_e32 v7, vcc, 3, v7
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_add_u32_e32 v5, vcc, 3, v5
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_add_u32_e32 v3, vcc, 3, v3
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_add_u32_e32 v1, vcc, 3, v1
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; VI-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; VI-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; VI-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; VI-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; VI-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; VI-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; VI-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; VI-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; VI-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; VI-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; VI-NEXT:  .LBB16_4: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    v_lshlrev_b32_e32 v39, 16, v39
; VI-NEXT:    v_lshlrev_b32_e32 v38, 16, v38
; VI-NEXT:    v_lshlrev_b32_e32 v37, 16, v37
; VI-NEXT:    v_lshlrev_b32_e32 v36, 16, v36
; VI-NEXT:    v_lshlrev_b32_e32 v35, 16, v35
; VI-NEXT:    v_lshlrev_b32_e32 v34, 16, v34
; VI-NEXT:    v_lshlrev_b32_e32 v33, 16, v33
; VI-NEXT:    v_lshlrev_b32_e32 v32, 16, v32
; VI-NEXT:    v_lshlrev_b32_e32 v31, 16, v31
; VI-NEXT:    v_lshlrev_b32_e32 v30, 16, v30
; VI-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; VI-NEXT:    v_lshlrev_b32_e32 v28, 16, v28
; VI-NEXT:    v_lshlrev_b32_e32 v27, 16, v27
; VI-NEXT:    v_lshlrev_b32_e32 v26, 16, v26
; VI-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; VI-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; VI-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; VI-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; VI-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; VI-NEXT:    v_or_b32_sdwa v0, v0, v39 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v1, v1, v38 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v2, v2, v37 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v3, v3, v36 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v4, v4, v35 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v5, v5, v34 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v6, v6, v33 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v7, v7, v32 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v8, v8, v31 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v9, v9, v30 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v10, v10, v29 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v11, v11, v28 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v12, v12, v27 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v13, v13, v26 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v14, v14, v25 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v15, v15, v24 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v16, v16, v23 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v17, v17, v22 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v18, v18, v21 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v19, v19, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v20i32_to_v40f16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    ; implicit-def: $vgpr39
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr35
; GFX9-NEXT:    ; implicit-def: $vgpr34
; GFX9-NEXT:    ; implicit-def: $vgpr33
; GFX9-NEXT:    ; implicit-def: $vgpr32
; GFX9-NEXT:    ; implicit-def: $vgpr31
; GFX9-NEXT:    ; implicit-def: $vgpr30
; GFX9-NEXT:    ; implicit-def: $vgpr29
; GFX9-NEXT:    ; implicit-def: $vgpr28
; GFX9-NEXT:    ; implicit-def: $vgpr27
; GFX9-NEXT:    ; implicit-def: $vgpr26
; GFX9-NEXT:    ; implicit-def: $vgpr25
; GFX9-NEXT:    ; implicit-def: $vgpr24
; GFX9-NEXT:    ; implicit-def: $vgpr23
; GFX9-NEXT:    ; implicit-def: $vgpr22
; GFX9-NEXT:    ; implicit-def: $vgpr21
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB16_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX9-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX9-NEXT:  .LBB16_2: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB16_4
; GFX9-NEXT:  ; %bb.3: ; %cmp.true
; GFX9-NEXT:    v_add_u32_e32 v19, 3, v19
; GFX9-NEXT:    v_add_u32_e32 v18, 3, v18
; GFX9-NEXT:    v_add_u32_e32 v17, 3, v17
; GFX9-NEXT:    v_add_u32_e32 v16, 3, v16
; GFX9-NEXT:    v_add_u32_e32 v15, 3, v15
; GFX9-NEXT:    v_add_u32_e32 v14, 3, v14
; GFX9-NEXT:    v_add_u32_e32 v13, 3, v13
; GFX9-NEXT:    v_add_u32_e32 v12, 3, v12
; GFX9-NEXT:    v_add_u32_e32 v11, 3, v11
; GFX9-NEXT:    v_add_u32_e32 v10, 3, v10
; GFX9-NEXT:    v_add_u32_e32 v9, 3, v9
; GFX9-NEXT:    v_add_u32_e32 v8, 3, v8
; GFX9-NEXT:    v_add_u32_e32 v7, 3, v7
; GFX9-NEXT:    v_add_u32_e32 v6, 3, v6
; GFX9-NEXT:    v_add_u32_e32 v5, 3, v5
; GFX9-NEXT:    v_add_u32_e32 v4, 3, v4
; GFX9-NEXT:    v_add_u32_e32 v3, 3, v3
; GFX9-NEXT:    v_add_u32_e32 v2, 3, v2
; GFX9-NEXT:    v_add_u32_e32 v1, 3, v1
; GFX9-NEXT:    v_add_u32_e32 v0, 3, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX9-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX9-NEXT:  .LBB16_4: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_mov_b32 s4, 0x5040100
; GFX9-NEXT:    v_perm_b32 v0, v39, v0, s4
; GFX9-NEXT:    v_perm_b32 v1, v38, v1, s4
; GFX9-NEXT:    v_perm_b32 v2, v37, v2, s4
; GFX9-NEXT:    v_perm_b32 v3, v36, v3, s4
; GFX9-NEXT:    v_perm_b32 v4, v35, v4, s4
; GFX9-NEXT:    v_perm_b32 v5, v34, v5, s4
; GFX9-NEXT:    v_perm_b32 v6, v33, v6, s4
; GFX9-NEXT:    v_perm_b32 v7, v32, v7, s4
; GFX9-NEXT:    v_perm_b32 v8, v31, v8, s4
; GFX9-NEXT:    v_perm_b32 v9, v30, v9, s4
; GFX9-NEXT:    v_perm_b32 v10, v29, v10, s4
; GFX9-NEXT:    v_perm_b32 v11, v28, v11, s4
; GFX9-NEXT:    v_perm_b32 v12, v27, v12, s4
; GFX9-NEXT:    v_perm_b32 v13, v26, v13, s4
; GFX9-NEXT:    v_perm_b32 v14, v25, v14, s4
; GFX9-NEXT:    v_perm_b32 v15, v24, v15, s4
; GFX9-NEXT:    v_perm_b32 v16, v23, v16, s4
; GFX9-NEXT:    v_perm_b32 v17, v22, v17, s4
; GFX9-NEXT:    v_perm_b32 v18, v21, v18, s4
; GFX9-NEXT:    v_perm_b32 v19, v20, v19, s4
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v20i32_to_v40f16:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB16_2
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v19, 3, v19
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v18, 3, v18
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v17, 3, v17
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v16, 3, v16
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v15, 3, v15
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v14, 3, v14
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v13, 3, v13
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v12, 3, v12
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v11, 3, v11
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v10, 3, v10
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v9, 3, v9
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v8, 3, v8
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v7, 3, v7
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v6, 3, v6
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v5, 3, v5
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v4, 3, v4
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v3, 3, v3
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v2, 3, v2
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v1, 3, v1
; GFX11-TRUE16-NEXT:    v_add_nc_u32_e32 v0, 3, v0
; GFX11-TRUE16-NEXT:  .LBB16_2: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v20i32_to_v40f16:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr39
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr38
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr37
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr36
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr35
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr34
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr33
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr32
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr31
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr30
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr29
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr28
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr27
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr26
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr25
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr24
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr23
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr22
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr21
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB16_2
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX11-FAKE16-NEXT:  .LBB16_2: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB16_4
; GFX11-FAKE16-NEXT:  ; %bb.3: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v19, 3, v19
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v18, 3, v18
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v17, 3, v17
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v16, 3, v16
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v15, 3, v15
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v14, 3, v14
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v13, 3, v13
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v12, 3, v12
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v11, 3, v11
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v10, 3, v10
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v9, 3, v9
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v8, 3, v8
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v7, 3, v7
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v6, 3, v6
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v5, 3, v5
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v4, 3, v4
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v3, 3, v3
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v2, 3, v2
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v1, 3, v1
; GFX11-FAKE16-NEXT:    v_add_nc_u32_e32 v0, 3, v0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX11-FAKE16-NEXT:  .LBB16_4: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v39, v0, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v38, v1, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v37, v2, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v36, v3, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v35, v4, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v34, v5, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v33, v6, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v32, v7, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, v31, v8, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, v30, v9, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, v29, v10, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, v28, v11, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, v27, v12, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, v26, v13, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v14, v25, v14, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v15, v24, v15, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v16, v23, v16, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v17, v22, v17, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v18, v21, v18, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v19, v20, v19, 0x5040100
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <20 x i32> %a, splat (i32 3)
  %a2 = bitcast <20 x i32> %a1 to <40 x half>
  br label %end

cmp.false:
  %a3 = bitcast <20 x i32> %a to <40 x half>
  br label %end

end:
  %phi = phi <40 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <40 x half> %phi
}

define inreg <40 x half> @bitcast_v20i32_to_v40f16_scalar(<20 x i32> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v20i32_to_v40f16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_readfirstlane_b32 s8, v6
; SI-NEXT:    v_readfirstlane_b32 s5, v5
; SI-NEXT:    v_readfirstlane_b32 s4, v4
; SI-NEXT:    v_readfirstlane_b32 s7, v3
; SI-NEXT:    v_readfirstlane_b32 s6, v2
; SI-NEXT:    v_readfirstlane_b32 s9, v1
; SI-NEXT:    s_cmp_lg_u32 s8, 0
; SI-NEXT:    v_readfirstlane_b32 s8, v0
; SI-NEXT:    s_cbranch_scc0 .LBB17_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_lshr_b32 s72, s5, 16
; SI-NEXT:    s_lshr_b32 s73, s7, 16
; SI-NEXT:    s_lshr_b32 s74, s9, 16
; SI-NEXT:    s_lshr_b32 s75, s29, 16
; SI-NEXT:    s_lshr_b32 s76, s27, 16
; SI-NEXT:    s_lshr_b32 s77, s25, 16
; SI-NEXT:    s_lshr_b32 s78, s23, 16
; SI-NEXT:    s_lshr_b32 s79, s21, 16
; SI-NEXT:    s_lshr_b32 s88, s19, 16
; SI-NEXT:    s_lshr_b32 s89, s17, 16
; SI-NEXT:    s_lshr_b64 s[10:11], s[4:5], 16
; SI-NEXT:    s_lshr_b64 s[12:13], s[6:7], 16
; SI-NEXT:    s_lshr_b64 s[14:15], s[8:9], 16
; SI-NEXT:    s_lshr_b64 s[40:41], s[28:29], 16
; SI-NEXT:    s_lshr_b64 s[42:43], s[26:27], 16
; SI-NEXT:    s_lshr_b64 s[44:45], s[24:25], 16
; SI-NEXT:    s_lshr_b64 s[46:47], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[56:57], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[58:59], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[60:61], s[16:17], 16
; SI-NEXT:    s_cbranch_execnz .LBB17_3
; SI-NEXT:  .LBB17_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s17, s17, 3
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    s_add_i32 s19, s19, 3
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_add_i32 s21, s21, 3
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_add_i32 s23, s23, 3
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_add_i32 s25, s25, 3
; SI-NEXT:    s_add_i32 s24, s24, 3
; SI-NEXT:    s_add_i32 s27, s27, 3
; SI-NEXT:    s_add_i32 s26, s26, 3
; SI-NEXT:    s_add_i32 s29, s29, 3
; SI-NEXT:    s_add_i32 s28, s28, 3
; SI-NEXT:    s_add_i32 s9, s9, 3
; SI-NEXT:    s_add_i32 s8, s8, 3
; SI-NEXT:    s_add_i32 s7, s7, 3
; SI-NEXT:    s_add_i32 s6, s6, 3
; SI-NEXT:    s_add_i32 s5, s5, 3
; SI-NEXT:    s_add_i32 s4, s4, 3
; SI-NEXT:    s_lshr_b64 s[10:11], s[4:5], 16
; SI-NEXT:    s_lshr_b64 s[12:13], s[6:7], 16
; SI-NEXT:    s_lshr_b64 s[14:15], s[8:9], 16
; SI-NEXT:    s_lshr_b64 s[40:41], s[28:29], 16
; SI-NEXT:    s_lshr_b64 s[42:43], s[26:27], 16
; SI-NEXT:    s_lshr_b64 s[44:45], s[24:25], 16
; SI-NEXT:    s_lshr_b64 s[46:47], s[22:23], 16
; SI-NEXT:    s_lshr_b32 s72, s5, 16
; SI-NEXT:    s_lshr_b32 s73, s7, 16
; SI-NEXT:    s_lshr_b32 s74, s9, 16
; SI-NEXT:    s_lshr_b32 s75, s29, 16
; SI-NEXT:    s_lshr_b32 s76, s27, 16
; SI-NEXT:    s_lshr_b32 s77, s25, 16
; SI-NEXT:    s_lshr_b32 s78, s23, 16
; SI-NEXT:    s_lshr_b32 s79, s21, 16
; SI-NEXT:    s_lshr_b32 s88, s19, 16
; SI-NEXT:    s_lshr_b32 s89, s17, 16
; SI-NEXT:    s_lshr_b64 s[56:57], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[58:59], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[60:61], s[16:17], 16
; SI-NEXT:  .LBB17_3: ; %end
; SI-NEXT:    s_lshl_b32 s11, s60, 16
; SI-NEXT:    s_and_b32 s13, s16, 0xffff
; SI-NEXT:    s_or_b32 s11, s13, s11
; SI-NEXT:    s_and_b32 s13, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s15, s89, 16
; SI-NEXT:    s_or_b32 s13, s13, s15
; SI-NEXT:    s_lshl_b32 s15, s58, 16
; SI-NEXT:    s_and_b32 s16, s18, 0xffff
; SI-NEXT:    s_or_b32 s15, s16, s15
; SI-NEXT:    s_and_b32 s16, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s17, s88, 16
; SI-NEXT:    s_or_b32 s16, s16, s17
; SI-NEXT:    s_lshl_b32 s17, s56, 16
; SI-NEXT:    s_and_b32 s18, s20, 0xffff
; SI-NEXT:    s_or_b32 s17, s18, s17
; SI-NEXT:    s_and_b32 s18, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s19, s79, 16
; SI-NEXT:    s_or_b32 s18, s18, s19
; SI-NEXT:    s_and_b32 s19, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s20, s46, 16
; SI-NEXT:    s_or_b32 s19, s19, s20
; SI-NEXT:    s_and_b32 s20, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s21, s78, 16
; SI-NEXT:    s_or_b32 s20, s20, s21
; SI-NEXT:    s_and_b32 s21, s24, 0xffff
; SI-NEXT:    s_lshl_b32 s22, s44, 16
; SI-NEXT:    s_or_b32 s21, s21, s22
; SI-NEXT:    s_and_b32 s22, s25, 0xffff
; SI-NEXT:    s_lshl_b32 s23, s77, 16
; SI-NEXT:    s_or_b32 s22, s22, s23
; SI-NEXT:    s_and_b32 s23, s26, 0xffff
; SI-NEXT:    s_lshl_b32 s24, s42, 16
; SI-NEXT:    s_or_b32 s23, s23, s24
; SI-NEXT:    s_and_b32 s24, s27, 0xffff
; SI-NEXT:    s_lshl_b32 s25, s76, 16
; SI-NEXT:    s_or_b32 s24, s24, s25
; SI-NEXT:    s_and_b32 s25, s28, 0xffff
; SI-NEXT:    s_lshl_b32 s26, s40, 16
; SI-NEXT:    s_and_b32 s8, s8, 0xffff
; SI-NEXT:    s_lshl_b32 s14, s14, 16
; SI-NEXT:    s_and_b32 s6, s6, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s12, 16
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s10, 16
; SI-NEXT:    s_or_b32 s25, s25, s26
; SI-NEXT:    s_and_b32 s26, s29, 0xffff
; SI-NEXT:    s_lshl_b32 s27, s75, 16
; SI-NEXT:    s_or_b32 s8, s8, s14
; SI-NEXT:    s_and_b32 s9, s9, 0xffff
; SI-NEXT:    s_lshl_b32 s14, s74, 16
; SI-NEXT:    s_or_b32 s6, s6, s12
; SI-NEXT:    s_and_b32 s7, s7, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s73, 16
; SI-NEXT:    s_or_b32 s4, s4, s10
; SI-NEXT:    s_and_b32 s5, s5, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s72, 16
; SI-NEXT:    s_or_b32 s26, s26, s27
; SI-NEXT:    s_or_b32 s9, s9, s14
; SI-NEXT:    s_or_b32 s7, s7, s12
; SI-NEXT:    s_or_b32 s5, s5, s10
; SI-NEXT:    v_mov_b32_e32 v0, s11
; SI-NEXT:    v_mov_b32_e32 v1, s13
; SI-NEXT:    v_mov_b32_e32 v2, s15
; SI-NEXT:    v_mov_b32_e32 v3, s16
; SI-NEXT:    v_mov_b32_e32 v4, s17
; SI-NEXT:    v_mov_b32_e32 v5, s18
; SI-NEXT:    v_mov_b32_e32 v6, s19
; SI-NEXT:    v_mov_b32_e32 v7, s20
; SI-NEXT:    v_mov_b32_e32 v8, s21
; SI-NEXT:    v_mov_b32_e32 v9, s22
; SI-NEXT:    v_mov_b32_e32 v10, s23
; SI-NEXT:    v_mov_b32_e32 v11, s24
; SI-NEXT:    v_mov_b32_e32 v12, s25
; SI-NEXT:    v_mov_b32_e32 v13, s26
; SI-NEXT:    v_mov_b32_e32 v14, s8
; SI-NEXT:    v_mov_b32_e32 v15, s9
; SI-NEXT:    v_mov_b32_e32 v16, s6
; SI-NEXT:    v_mov_b32_e32 v17, s7
; SI-NEXT:    v_mov_b32_e32 v18, s4
; SI-NEXT:    v_mov_b32_e32 v19, s5
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB17_4:
; SI-NEXT:    ; implicit-def: $sgpr60
; SI-NEXT:    ; implicit-def: $sgpr89
; SI-NEXT:    ; implicit-def: $sgpr58
; SI-NEXT:    ; implicit-def: $sgpr88
; SI-NEXT:    ; implicit-def: $sgpr56
; SI-NEXT:    ; implicit-def: $sgpr79
; SI-NEXT:    ; implicit-def: $sgpr46
; SI-NEXT:    ; implicit-def: $sgpr78
; SI-NEXT:    ; implicit-def: $sgpr44
; SI-NEXT:    ; implicit-def: $sgpr77
; SI-NEXT:    ; implicit-def: $sgpr42
; SI-NEXT:    ; implicit-def: $sgpr76
; SI-NEXT:    ; implicit-def: $sgpr40
; SI-NEXT:    ; implicit-def: $sgpr75
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr74
; SI-NEXT:    ; implicit-def: $sgpr12
; SI-NEXT:    ; implicit-def: $sgpr73
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr72
; SI-NEXT:    s_branch .LBB17_2
;
; VI-LABEL: bitcast_v20i32_to_v40f16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    v_readfirstlane_b32 s6, v5
; VI-NEXT:    v_readfirstlane_b32 s7, v4
; VI-NEXT:    v_readfirstlane_b32 s8, v3
; VI-NEXT:    v_readfirstlane_b32 s9, v2
; VI-NEXT:    v_readfirstlane_b32 s10, v1
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    v_readfirstlane_b32 s11, v0
; VI-NEXT:    s_cbranch_scc0 .LBB17_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_lshr_b32 s12, s6, 16
; VI-NEXT:    s_lshr_b32 s13, s7, 16
; VI-NEXT:    s_lshr_b32 s14, s8, 16
; VI-NEXT:    s_lshr_b32 s15, s9, 16
; VI-NEXT:    s_lshr_b32 s40, s10, 16
; VI-NEXT:    s_lshr_b32 s41, s11, 16
; VI-NEXT:    s_lshr_b32 s42, s29, 16
; VI-NEXT:    s_lshr_b32 s43, s28, 16
; VI-NEXT:    s_lshr_b32 s44, s27, 16
; VI-NEXT:    s_lshr_b32 s45, s26, 16
; VI-NEXT:    s_lshr_b32 s46, s25, 16
; VI-NEXT:    s_lshr_b32 s47, s24, 16
; VI-NEXT:    s_lshr_b32 s56, s23, 16
; VI-NEXT:    s_lshr_b32 s57, s22, 16
; VI-NEXT:    s_lshr_b32 s58, s21, 16
; VI-NEXT:    s_lshr_b32 s59, s20, 16
; VI-NEXT:    s_lshr_b32 s60, s19, 16
; VI-NEXT:    s_lshr_b32 s61, s18, 16
; VI-NEXT:    s_lshr_b32 s62, s17, 16
; VI-NEXT:    s_lshr_b32 s63, s16, 16
; VI-NEXT:    s_cbranch_execnz .LBB17_3
; VI-NEXT:  .LBB17_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s6, s6, 3
; VI-NEXT:    s_add_i32 s7, s7, 3
; VI-NEXT:    s_add_i32 s8, s8, 3
; VI-NEXT:    s_add_i32 s9, s9, 3
; VI-NEXT:    s_add_i32 s10, s10, 3
; VI-NEXT:    s_add_i32 s11, s11, 3
; VI-NEXT:    s_add_i32 s29, s29, 3
; VI-NEXT:    s_add_i32 s28, s28, 3
; VI-NEXT:    s_add_i32 s27, s27, 3
; VI-NEXT:    s_add_i32 s26, s26, 3
; VI-NEXT:    s_add_i32 s25, s25, 3
; VI-NEXT:    s_add_i32 s24, s24, 3
; VI-NEXT:    s_add_i32 s23, s23, 3
; VI-NEXT:    s_add_i32 s22, s22, 3
; VI-NEXT:    s_add_i32 s21, s21, 3
; VI-NEXT:    s_add_i32 s20, s20, 3
; VI-NEXT:    s_add_i32 s19, s19, 3
; VI-NEXT:    s_add_i32 s18, s18, 3
; VI-NEXT:    s_add_i32 s17, s17, 3
; VI-NEXT:    s_add_i32 s16, s16, 3
; VI-NEXT:    s_lshr_b32 s12, s6, 16
; VI-NEXT:    s_lshr_b32 s13, s7, 16
; VI-NEXT:    s_lshr_b32 s14, s8, 16
; VI-NEXT:    s_lshr_b32 s15, s9, 16
; VI-NEXT:    s_lshr_b32 s40, s10, 16
; VI-NEXT:    s_lshr_b32 s41, s11, 16
; VI-NEXT:    s_lshr_b32 s42, s29, 16
; VI-NEXT:    s_lshr_b32 s43, s28, 16
; VI-NEXT:    s_lshr_b32 s44, s27, 16
; VI-NEXT:    s_lshr_b32 s45, s26, 16
; VI-NEXT:    s_lshr_b32 s46, s25, 16
; VI-NEXT:    s_lshr_b32 s47, s24, 16
; VI-NEXT:    s_lshr_b32 s56, s23, 16
; VI-NEXT:    s_lshr_b32 s57, s22, 16
; VI-NEXT:    s_lshr_b32 s58, s21, 16
; VI-NEXT:    s_lshr_b32 s59, s20, 16
; VI-NEXT:    s_lshr_b32 s60, s19, 16
; VI-NEXT:    s_lshr_b32 s61, s18, 16
; VI-NEXT:    s_lshr_b32 s62, s17, 16
; VI-NEXT:    s_lshr_b32 s63, s16, 16
; VI-NEXT:  .LBB17_3: ; %end
; VI-NEXT:    s_and_b32 s4, 0xffff, s16
; VI-NEXT:    s_lshl_b32 s5, s63, 16
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_and_b32 s5, 0xffff, s17
; VI-NEXT:    s_lshl_b32 s16, s62, 16
; VI-NEXT:    s_or_b32 s5, s5, s16
; VI-NEXT:    s_and_b32 s16, 0xffff, s18
; VI-NEXT:    s_lshl_b32 s17, s61, 16
; VI-NEXT:    s_or_b32 s16, s16, s17
; VI-NEXT:    s_and_b32 s17, 0xffff, s19
; VI-NEXT:    s_lshl_b32 s18, s60, 16
; VI-NEXT:    s_or_b32 s17, s17, s18
; VI-NEXT:    s_and_b32 s18, 0xffff, s20
; VI-NEXT:    s_lshl_b32 s19, s59, 16
; VI-NEXT:    s_or_b32 s18, s18, s19
; VI-NEXT:    s_and_b32 s19, 0xffff, s21
; VI-NEXT:    s_lshl_b32 s20, s58, 16
; VI-NEXT:    s_or_b32 s19, s19, s20
; VI-NEXT:    s_and_b32 s20, 0xffff, s22
; VI-NEXT:    s_lshl_b32 s21, s57, 16
; VI-NEXT:    s_or_b32 s20, s20, s21
; VI-NEXT:    s_and_b32 s21, 0xffff, s23
; VI-NEXT:    s_lshl_b32 s22, s56, 16
; VI-NEXT:    s_or_b32 s21, s21, s22
; VI-NEXT:    s_and_b32 s22, 0xffff, s24
; VI-NEXT:    s_lshl_b32 s23, s47, 16
; VI-NEXT:    s_or_b32 s22, s22, s23
; VI-NEXT:    s_and_b32 s23, 0xffff, s25
; VI-NEXT:    s_lshl_b32 s24, s46, 16
; VI-NEXT:    s_or_b32 s23, s23, s24
; VI-NEXT:    s_and_b32 s24, 0xffff, s26
; VI-NEXT:    s_lshl_b32 s25, s45, 16
; VI-NEXT:    s_or_b32 s24, s24, s25
; VI-NEXT:    s_and_b32 s25, 0xffff, s27
; VI-NEXT:    s_lshl_b32 s26, s44, 16
; VI-NEXT:    s_or_b32 s25, s25, s26
; VI-NEXT:    s_and_b32 s26, 0xffff, s28
; VI-NEXT:    s_lshl_b32 s27, s43, 16
; VI-NEXT:    s_or_b32 s26, s26, s27
; VI-NEXT:    s_and_b32 s27, 0xffff, s29
; VI-NEXT:    s_lshl_b32 s28, s42, 16
; VI-NEXT:    s_or_b32 s27, s27, s28
; VI-NEXT:    s_and_b32 s11, 0xffff, s11
; VI-NEXT:    s_lshl_b32 s28, s41, 16
; VI-NEXT:    s_or_b32 s11, s11, s28
; VI-NEXT:    s_and_b32 s10, 0xffff, s10
; VI-NEXT:    s_lshl_b32 s28, s40, 16
; VI-NEXT:    s_and_b32 s9, 0xffff, s9
; VI-NEXT:    s_lshl_b32 s15, s15, 16
; VI-NEXT:    s_and_b32 s8, 0xffff, s8
; VI-NEXT:    s_lshl_b32 s14, s14, 16
; VI-NEXT:    s_and_b32 s7, 0xffff, s7
; VI-NEXT:    s_lshl_b32 s13, s13, 16
; VI-NEXT:    s_and_b32 s6, 0xffff, s6
; VI-NEXT:    s_lshl_b32 s12, s12, 16
; VI-NEXT:    s_or_b32 s10, s10, s28
; VI-NEXT:    s_or_b32 s9, s9, s15
; VI-NEXT:    s_or_b32 s8, s8, s14
; VI-NEXT:    s_or_b32 s7, s7, s13
; VI-NEXT:    s_or_b32 s6, s6, s12
; VI-NEXT:    v_mov_b32_e32 v0, s4
; VI-NEXT:    v_mov_b32_e32 v1, s5
; VI-NEXT:    v_mov_b32_e32 v2, s16
; VI-NEXT:    v_mov_b32_e32 v3, s17
; VI-NEXT:    v_mov_b32_e32 v4, s18
; VI-NEXT:    v_mov_b32_e32 v5, s19
; VI-NEXT:    v_mov_b32_e32 v6, s20
; VI-NEXT:    v_mov_b32_e32 v7, s21
; VI-NEXT:    v_mov_b32_e32 v8, s22
; VI-NEXT:    v_mov_b32_e32 v9, s23
; VI-NEXT:    v_mov_b32_e32 v10, s24
; VI-NEXT:    v_mov_b32_e32 v11, s25
; VI-NEXT:    v_mov_b32_e32 v12, s26
; VI-NEXT:    v_mov_b32_e32 v13, s27
; VI-NEXT:    v_mov_b32_e32 v14, s11
; VI-NEXT:    v_mov_b32_e32 v15, s10
; VI-NEXT:    v_mov_b32_e32 v16, s9
; VI-NEXT:    v_mov_b32_e32 v17, s8
; VI-NEXT:    v_mov_b32_e32 v18, s7
; VI-NEXT:    v_mov_b32_e32 v19, s6
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB17_4:
; VI-NEXT:    ; implicit-def: $sgpr63
; VI-NEXT:    ; implicit-def: $sgpr62
; VI-NEXT:    ; implicit-def: $sgpr61
; VI-NEXT:    ; implicit-def: $sgpr60
; VI-NEXT:    ; implicit-def: $sgpr59
; VI-NEXT:    ; implicit-def: $sgpr58
; VI-NEXT:    ; implicit-def: $sgpr57
; VI-NEXT:    ; implicit-def: $sgpr56
; VI-NEXT:    ; implicit-def: $sgpr47
; VI-NEXT:    ; implicit-def: $sgpr46
; VI-NEXT:    ; implicit-def: $sgpr45
; VI-NEXT:    ; implicit-def: $sgpr44
; VI-NEXT:    ; implicit-def: $sgpr43
; VI-NEXT:    ; implicit-def: $sgpr42
; VI-NEXT:    ; implicit-def: $sgpr41
; VI-NEXT:    ; implicit-def: $sgpr40
; VI-NEXT:    ; implicit-def: $sgpr15
; VI-NEXT:    ; implicit-def: $sgpr14
; VI-NEXT:    ; implicit-def: $sgpr13
; VI-NEXT:    ; implicit-def: $sgpr12
; VI-NEXT:    s_branch .LBB17_2
;
; GFX9-LABEL: bitcast_v20i32_to_v40f16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_readfirstlane_b32 s4, v6
; GFX9-NEXT:    v_readfirstlane_b32 s6, v5
; GFX9-NEXT:    v_readfirstlane_b32 s7, v4
; GFX9-NEXT:    v_readfirstlane_b32 s8, v3
; GFX9-NEXT:    v_readfirstlane_b32 s9, v2
; GFX9-NEXT:    v_readfirstlane_b32 s10, v1
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    v_readfirstlane_b32 s11, v0
; GFX9-NEXT:    s_cbranch_scc0 .LBB17_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_lshr_b32 s12, s6, 16
; GFX9-NEXT:    s_lshr_b32 s13, s7, 16
; GFX9-NEXT:    s_lshr_b32 s14, s8, 16
; GFX9-NEXT:    s_lshr_b32 s15, s9, 16
; GFX9-NEXT:    s_lshr_b32 s40, s10, 16
; GFX9-NEXT:    s_lshr_b32 s41, s11, 16
; GFX9-NEXT:    s_lshr_b32 s42, s29, 16
; GFX9-NEXT:    s_lshr_b32 s43, s28, 16
; GFX9-NEXT:    s_lshr_b32 s44, s27, 16
; GFX9-NEXT:    s_lshr_b32 s45, s26, 16
; GFX9-NEXT:    s_lshr_b32 s46, s25, 16
; GFX9-NEXT:    s_lshr_b32 s47, s24, 16
; GFX9-NEXT:    s_lshr_b32 s56, s23, 16
; GFX9-NEXT:    s_lshr_b32 s57, s22, 16
; GFX9-NEXT:    s_lshr_b32 s58, s21, 16
; GFX9-NEXT:    s_lshr_b32 s59, s20, 16
; GFX9-NEXT:    s_lshr_b32 s60, s19, 16
; GFX9-NEXT:    s_lshr_b32 s61, s18, 16
; GFX9-NEXT:    s_lshr_b32 s62, s17, 16
; GFX9-NEXT:    s_lshr_b32 s63, s16, 16
; GFX9-NEXT:    s_cbranch_execnz .LBB17_3
; GFX9-NEXT:  .LBB17_2: ; %cmp.true
; GFX9-NEXT:    s_add_i32 s6, s6, 3
; GFX9-NEXT:    s_add_i32 s7, s7, 3
; GFX9-NEXT:    s_add_i32 s8, s8, 3
; GFX9-NEXT:    s_add_i32 s9, s9, 3
; GFX9-NEXT:    s_add_i32 s10, s10, 3
; GFX9-NEXT:    s_add_i32 s11, s11, 3
; GFX9-NEXT:    s_add_i32 s29, s29, 3
; GFX9-NEXT:    s_add_i32 s28, s28, 3
; GFX9-NEXT:    s_add_i32 s27, s27, 3
; GFX9-NEXT:    s_add_i32 s26, s26, 3
; GFX9-NEXT:    s_add_i32 s25, s25, 3
; GFX9-NEXT:    s_add_i32 s24, s24, 3
; GFX9-NEXT:    s_add_i32 s23, s23, 3
; GFX9-NEXT:    s_add_i32 s22, s22, 3
; GFX9-NEXT:    s_add_i32 s21, s21, 3
; GFX9-NEXT:    s_add_i32 s20, s20, 3
; GFX9-NEXT:    s_add_i32 s19, s19, 3
; GFX9-NEXT:    s_add_i32 s18, s18, 3
; GFX9-NEXT:    s_add_i32 s17, s17, 3
; GFX9-NEXT:    s_add_i32 s16, s16, 3
; GFX9-NEXT:    s_lshr_b32 s12, s6, 16
; GFX9-NEXT:    s_lshr_b32 s13, s7, 16
; GFX9-NEXT:    s_lshr_b32 s14, s8, 16
; GFX9-NEXT:    s_lshr_b32 s15, s9, 16
; GFX9-NEXT:    s_lshr_b32 s40, s10, 16
; GFX9-NEXT:    s_lshr_b32 s41, s11, 16
; GFX9-NEXT:    s_lshr_b32 s42, s29, 16
; GFX9-NEXT:    s_lshr_b32 s43, s28, 16
; GFX9-NEXT:    s_lshr_b32 s44, s27, 16
; GFX9-NEXT:    s_lshr_b32 s45, s26, 16
; GFX9-NEXT:    s_lshr_b32 s46, s25, 16
; GFX9-NEXT:    s_lshr_b32 s47, s24, 16
; GFX9-NEXT:    s_lshr_b32 s56, s23, 16
; GFX9-NEXT:    s_lshr_b32 s57, s22, 16
; GFX9-NEXT:    s_lshr_b32 s58, s21, 16
; GFX9-NEXT:    s_lshr_b32 s59, s20, 16
; GFX9-NEXT:    s_lshr_b32 s60, s19, 16
; GFX9-NEXT:    s_lshr_b32 s61, s18, 16
; GFX9-NEXT:    s_lshr_b32 s62, s17, 16
; GFX9-NEXT:    s_lshr_b32 s63, s16, 16
; GFX9-NEXT:  .LBB17_3: ; %end
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s16, s63
; GFX9-NEXT:    s_pack_ll_b32_b16 s5, s17, s62
; GFX9-NEXT:    s_pack_ll_b32_b16 s16, s18, s61
; GFX9-NEXT:    s_pack_ll_b32_b16 s17, s19, s60
; GFX9-NEXT:    s_pack_ll_b32_b16 s18, s20, s59
; GFX9-NEXT:    s_pack_ll_b32_b16 s19, s21, s58
; GFX9-NEXT:    s_pack_ll_b32_b16 s20, s22, s57
; GFX9-NEXT:    s_pack_ll_b32_b16 s21, s23, s56
; GFX9-NEXT:    s_pack_ll_b32_b16 s22, s24, s47
; GFX9-NEXT:    s_pack_ll_b32_b16 s23, s25, s46
; GFX9-NEXT:    s_pack_ll_b32_b16 s24, s26, s45
; GFX9-NEXT:    s_pack_ll_b32_b16 s25, s27, s44
; GFX9-NEXT:    s_pack_ll_b32_b16 s26, s28, s43
; GFX9-NEXT:    s_pack_ll_b32_b16 s27, s29, s42
; GFX9-NEXT:    s_pack_ll_b32_b16 s11, s11, s41
; GFX9-NEXT:    s_pack_ll_b32_b16 s10, s10, s40
; GFX9-NEXT:    s_pack_ll_b32_b16 s9, s9, s15
; GFX9-NEXT:    s_pack_ll_b32_b16 s8, s8, s14
; GFX9-NEXT:    s_pack_ll_b32_b16 s7, s7, s13
; GFX9-NEXT:    s_pack_ll_b32_b16 s6, s6, s12
; GFX9-NEXT:    v_mov_b32_e32 v0, s4
; GFX9-NEXT:    v_mov_b32_e32 v1, s5
; GFX9-NEXT:    v_mov_b32_e32 v2, s16
; GFX9-NEXT:    v_mov_b32_e32 v3, s17
; GFX9-NEXT:    v_mov_b32_e32 v4, s18
; GFX9-NEXT:    v_mov_b32_e32 v5, s19
; GFX9-NEXT:    v_mov_b32_e32 v6, s20
; GFX9-NEXT:    v_mov_b32_e32 v7, s21
; GFX9-NEXT:    v_mov_b32_e32 v8, s22
; GFX9-NEXT:    v_mov_b32_e32 v9, s23
; GFX9-NEXT:    v_mov_b32_e32 v10, s24
; GFX9-NEXT:    v_mov_b32_e32 v11, s25
; GFX9-NEXT:    v_mov_b32_e32 v12, s26
; GFX9-NEXT:    v_mov_b32_e32 v13, s27
; GFX9-NEXT:    v_mov_b32_e32 v14, s11
; GFX9-NEXT:    v_mov_b32_e32 v15, s10
; GFX9-NEXT:    v_mov_b32_e32 v16, s9
; GFX9-NEXT:    v_mov_b32_e32 v17, s8
; GFX9-NEXT:    v_mov_b32_e32 v18, s7
; GFX9-NEXT:    v_mov_b32_e32 v19, s6
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB17_4:
; GFX9-NEXT:    ; implicit-def: $sgpr63
; GFX9-NEXT:    ; implicit-def: $sgpr62
; GFX9-NEXT:    ; implicit-def: $sgpr61
; GFX9-NEXT:    ; implicit-def: $sgpr60
; GFX9-NEXT:    ; implicit-def: $sgpr59
; GFX9-NEXT:    ; implicit-def: $sgpr58
; GFX9-NEXT:    ; implicit-def: $sgpr57
; GFX9-NEXT:    ; implicit-def: $sgpr56
; GFX9-NEXT:    ; implicit-def: $sgpr47
; GFX9-NEXT:    ; implicit-def: $sgpr46
; GFX9-NEXT:    ; implicit-def: $sgpr45
; GFX9-NEXT:    ; implicit-def: $sgpr44
; GFX9-NEXT:    ; implicit-def: $sgpr43
; GFX9-NEXT:    ; implicit-def: $sgpr42
; GFX9-NEXT:    ; implicit-def: $sgpr41
; GFX9-NEXT:    ; implicit-def: $sgpr40
; GFX9-NEXT:    ; implicit-def: $sgpr15
; GFX9-NEXT:    ; implicit-def: $sgpr14
; GFX9-NEXT:    ; implicit-def: $sgpr13
; GFX9-NEXT:    ; implicit-def: $sgpr12
; GFX9-NEXT:    s_branch .LBB17_2
;
; GFX11-LABEL: bitcast_v20i32_to_v40f16_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    v_readfirstlane_b32 s6, v2
; GFX11-NEXT:    v_readfirstlane_b32 s4, v1
; GFX11-NEXT:    v_readfirstlane_b32 s5, v0
; GFX11-NEXT:    s_mov_b32 s58, 0
; GFX11-NEXT:    s_cmp_lg_u32 s6, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB17_4
; GFX11-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-NEXT:    s_lshr_b32 s6, s4, 16
; GFX11-NEXT:    s_lshr_b32 s7, s5, 16
; GFX11-NEXT:    s_lshr_b32 s8, s29, 16
; GFX11-NEXT:    s_lshr_b32 s9, s28, 16
; GFX11-NEXT:    s_lshr_b32 s10, s27, 16
; GFX11-NEXT:    s_lshr_b32 s11, s26, 16
; GFX11-NEXT:    s_lshr_b32 s12, s25, 16
; GFX11-NEXT:    s_lshr_b32 s13, s24, 16
; GFX11-NEXT:    s_lshr_b32 s14, s23, 16
; GFX11-NEXT:    s_lshr_b32 s15, s22, 16
; GFX11-NEXT:    s_lshr_b32 s40, s21, 16
; GFX11-NEXT:    s_lshr_b32 s41, s20, 16
; GFX11-NEXT:    s_lshr_b32 s42, s19, 16
; GFX11-NEXT:    s_lshr_b32 s43, s18, 16
; GFX11-NEXT:    s_lshr_b32 s44, s17, 16
; GFX11-NEXT:    s_lshr_b32 s45, s16, 16
; GFX11-NEXT:    s_lshr_b32 s46, s3, 16
; GFX11-NEXT:    s_lshr_b32 s47, s2, 16
; GFX11-NEXT:    s_lshr_b32 s56, s1, 16
; GFX11-NEXT:    s_lshr_b32 s57, s0, 16
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s58
; GFX11-NEXT:    s_cbranch_vccnz .LBB17_3
; GFX11-NEXT:  .LBB17_2: ; %cmp.true
; GFX11-NEXT:    s_add_i32 s4, s4, 3
; GFX11-NEXT:    s_add_i32 s5, s5, 3
; GFX11-NEXT:    s_add_i32 s29, s29, 3
; GFX11-NEXT:    s_add_i32 s28, s28, 3
; GFX11-NEXT:    s_add_i32 s27, s27, 3
; GFX11-NEXT:    s_add_i32 s26, s26, 3
; GFX11-NEXT:    s_add_i32 s25, s25, 3
; GFX11-NEXT:    s_add_i32 s24, s24, 3
; GFX11-NEXT:    s_add_i32 s23, s23, 3
; GFX11-NEXT:    s_add_i32 s22, s22, 3
; GFX11-NEXT:    s_add_i32 s21, s21, 3
; GFX11-NEXT:    s_add_i32 s20, s20, 3
; GFX11-NEXT:    s_add_i32 s19, s19, 3
; GFX11-NEXT:    s_add_i32 s18, s18, 3
; GFX11-NEXT:    s_add_i32 s17, s17, 3
; GFX11-NEXT:    s_add_i32 s16, s16, 3
; GFX11-NEXT:    s_add_i32 s3, s3, 3
; GFX11-NEXT:    s_add_i32 s2, s2, 3
; GFX11-NEXT:    s_add_i32 s1, s1, 3
; GFX11-NEXT:    s_add_i32 s0, s0, 3
; GFX11-NEXT:    s_lshr_b32 s6, s4, 16
; GFX11-NEXT:    s_lshr_b32 s7, s5, 16
; GFX11-NEXT:    s_lshr_b32 s8, s29, 16
; GFX11-NEXT:    s_lshr_b32 s9, s28, 16
; GFX11-NEXT:    s_lshr_b32 s10, s27, 16
; GFX11-NEXT:    s_lshr_b32 s11, s26, 16
; GFX11-NEXT:    s_lshr_b32 s12, s25, 16
; GFX11-NEXT:    s_lshr_b32 s13, s24, 16
; GFX11-NEXT:    s_lshr_b32 s14, s23, 16
; GFX11-NEXT:    s_lshr_b32 s15, s22, 16
; GFX11-NEXT:    s_lshr_b32 s40, s21, 16
; GFX11-NEXT:    s_lshr_b32 s41, s20, 16
; GFX11-NEXT:    s_lshr_b32 s42, s19, 16
; GFX11-NEXT:    s_lshr_b32 s43, s18, 16
; GFX11-NEXT:    s_lshr_b32 s44, s17, 16
; GFX11-NEXT:    s_lshr_b32 s45, s16, 16
; GFX11-NEXT:    s_lshr_b32 s46, s3, 16
; GFX11-NEXT:    s_lshr_b32 s47, s2, 16
; GFX11-NEXT:    s_lshr_b32 s56, s1, 16
; GFX11-NEXT:    s_lshr_b32 s57, s0, 16
; GFX11-NEXT:  .LBB17_3: ; %end
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_pack_ll_b32_b16 s0, s0, s57
; GFX11-NEXT:    s_pack_ll_b32_b16 s1, s1, s56
; GFX11-NEXT:    s_pack_ll_b32_b16 s2, s2, s47
; GFX11-NEXT:    s_pack_ll_b32_b16 s3, s3, s46
; GFX11-NEXT:    s_pack_ll_b32_b16 s16, s16, s45
; GFX11-NEXT:    s_pack_ll_b32_b16 s17, s17, s44
; GFX11-NEXT:    s_pack_ll_b32_b16 s18, s18, s43
; GFX11-NEXT:    s_pack_ll_b32_b16 s19, s19, s42
; GFX11-NEXT:    s_pack_ll_b32_b16 s20, s20, s41
; GFX11-NEXT:    s_pack_ll_b32_b16 s21, s21, s40
; GFX11-NEXT:    s_pack_ll_b32_b16 s15, s22, s15
; GFX11-NEXT:    s_pack_ll_b32_b16 s14, s23, s14
; GFX11-NEXT:    s_pack_ll_b32_b16 s13, s24, s13
; GFX11-NEXT:    s_pack_ll_b32_b16 s12, s25, s12
; GFX11-NEXT:    s_pack_ll_b32_b16 s11, s26, s11
; GFX11-NEXT:    s_pack_ll_b32_b16 s10, s27, s10
; GFX11-NEXT:    s_pack_ll_b32_b16 s9, s28, s9
; GFX11-NEXT:    s_pack_ll_b32_b16 s8, s29, s8
; GFX11-NEXT:    s_pack_ll_b32_b16 s5, s5, s7
; GFX11-NEXT:    s_pack_ll_b32_b16 s4, s4, s6
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s16 :: v_dual_mov_b32 v5, s17
; GFX11-NEXT:    v_dual_mov_b32 v6, s18 :: v_dual_mov_b32 v7, s19
; GFX11-NEXT:    v_dual_mov_b32 v8, s20 :: v_dual_mov_b32 v9, s21
; GFX11-NEXT:    v_dual_mov_b32 v10, s15 :: v_dual_mov_b32 v11, s14
; GFX11-NEXT:    v_dual_mov_b32 v12, s13 :: v_dual_mov_b32 v13, s12
; GFX11-NEXT:    v_dual_mov_b32 v14, s11 :: v_dual_mov_b32 v15, s10
; GFX11-NEXT:    v_dual_mov_b32 v16, s9 :: v_dual_mov_b32 v17, s8
; GFX11-NEXT:    v_dual_mov_b32 v18, s5 :: v_dual_mov_b32 v19, s4
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB17_4:
; GFX11-NEXT:    ; implicit-def: $sgpr57
; GFX11-NEXT:    ; implicit-def: $sgpr56
; GFX11-NEXT:    ; implicit-def: $sgpr47
; GFX11-NEXT:    ; implicit-def: $sgpr46
; GFX11-NEXT:    ; implicit-def: $sgpr45
; GFX11-NEXT:    ; implicit-def: $sgpr44
; GFX11-NEXT:    ; implicit-def: $sgpr43
; GFX11-NEXT:    ; implicit-def: $sgpr42
; GFX11-NEXT:    ; implicit-def: $sgpr41
; GFX11-NEXT:    ; implicit-def: $sgpr40
; GFX11-NEXT:    ; implicit-def: $sgpr15
; GFX11-NEXT:    ; implicit-def: $sgpr14
; GFX11-NEXT:    ; implicit-def: $sgpr13
; GFX11-NEXT:    ; implicit-def: $sgpr12
; GFX11-NEXT:    ; implicit-def: $sgpr11
; GFX11-NEXT:    ; implicit-def: $sgpr10
; GFX11-NEXT:    ; implicit-def: $sgpr9
; GFX11-NEXT:    ; implicit-def: $sgpr8
; GFX11-NEXT:    ; implicit-def: $sgpr7
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    s_branch .LBB17_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <20 x i32> %a, splat (i32 3)
  %a2 = bitcast <20 x i32> %a1 to <40 x half>
  br label %end

cmp.false:
  %a3 = bitcast <20 x i32> %a to <40 x half>
  br label %end

end:
  %phi = phi <40 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <40 x half> %phi
}

define <20 x i32> @bitcast_v40f16_to_v20i32(<40 x half> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v40f16_to_v20i32:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v63, off, s[0:3], s32 ; 4-byte Folded Spill
; SI-NEXT:    v_mov_b32_e32 v32, v19
; SI-NEXT:    v_mov_b32_e32 v33, v18
; SI-NEXT:    v_mov_b32_e32 v43, v0
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v32
; SI-NEXT:    v_mov_b32_e32 v34, v17
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:64 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v33
; SI-NEXT:    v_mov_b32_e32 v35, v16
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:68 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v34
; SI-NEXT:    v_mov_b32_e32 v36, v15
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:72 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v35
; SI-NEXT:    v_mov_b32_e32 v37, v14
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:76 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v36
; SI-NEXT:    v_mov_b32_e32 v38, v13
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:80 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v37
; SI-NEXT:    v_mov_b32_e32 v39, v12
; SI-NEXT:    v_mov_b32_e32 v48, v11
; SI-NEXT:    v_mov_b32_e32 v49, v10
; SI-NEXT:    v_mov_b32_e32 v50, v9
; SI-NEXT:    v_mov_b32_e32 v51, v8
; SI-NEXT:    v_mov_b32_e32 v52, v7
; SI-NEXT:    v_mov_b32_e32 v53, v6
; SI-NEXT:    v_mov_b32_e32 v54, v5
; SI-NEXT:    v_mov_b32_e32 v55, v4
; SI-NEXT:    v_mov_b32_e32 v40, v3
; SI-NEXT:    v_mov_b32_e32 v41, v2
; SI-NEXT:    v_mov_b32_e32 v42, v1
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:84 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v38
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:88 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v39
; SI-NEXT:    v_lshrrev_b32_e32 v60, 16, v48
; SI-NEXT:    v_lshrrev_b32_e32 v61, 16, v49
; SI-NEXT:    v_lshrrev_b32_e32 v62, 16, v50
; SI-NEXT:    v_lshrrev_b32_e32 v63, 16, v51
; SI-NEXT:    v_lshrrev_b32_e32 v44, 16, v52
; SI-NEXT:    v_lshrrev_b32_e32 v45, 16, v53
; SI-NEXT:    v_lshrrev_b32_e32 v46, 16, v54
; SI-NEXT:    v_lshrrev_b32_e32 v47, 16, v55
; SI-NEXT:    v_lshrrev_b32_e32 v56, 16, v40
; SI-NEXT:    v_lshrrev_b32_e32 v57, 16, v41
; SI-NEXT:    v_lshrrev_b32_e32 v58, 16, v42
; SI-NEXT:    v_lshrrev_b32_e32 v59, 16, v43
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:92 ; 4-byte Folded Spill
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB18_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:92 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:88 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:84 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:80 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:76 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:72 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v43
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v59
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v42
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v58
; SI-NEXT:    v_or_b32_e32 v0, v0, v1
; SI-NEXT:    v_or_b32_e32 v1, v2, v3
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v41
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v57
; SI-NEXT:    v_or_b32_e32 v2, v2, v3
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v40
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v56
; SI-NEXT:    v_or_b32_e32 v3, v3, v4
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v55
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v47
; SI-NEXT:    v_or_b32_e32 v4, v4, v5
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v54
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v46
; SI-NEXT:    v_or_b32_e32 v5, v5, v6
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v53
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v45
; SI-NEXT:    v_or_b32_e32 v6, v6, v7
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v52
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v44
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v51
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v63
; SI-NEXT:    v_or_b32_e32 v8, v8, v9
; SI-NEXT:    v_and_b32_e32 v9, 0xffff, v50
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v62
; SI-NEXT:    v_or_b32_e32 v9, v9, v10
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v49
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v61
; SI-NEXT:    v_or_b32_e32 v10, v10, v11
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v48
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v60
; SI-NEXT:    v_or_b32_e32 v11, v11, v12
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v39
; SI-NEXT:    ; implicit-def: $vgpr43
; SI-NEXT:    ; implicit-def: $vgpr42
; SI-NEXT:    ; implicit-def: $vgpr41
; SI-NEXT:    ; implicit-def: $vgpr40
; SI-NEXT:    ; implicit-def: $vgpr55
; SI-NEXT:    ; implicit-def: $vgpr54
; SI-NEXT:    ; implicit-def: $vgpr53
; SI-NEXT:    ; implicit-def: $vgpr52
; SI-NEXT:    ; implicit-def: $vgpr51
; SI-NEXT:    ; implicit-def: $vgpr50
; SI-NEXT:    ; implicit-def: $vgpr49
; SI-NEXT:    ; implicit-def: $vgpr48
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:    ; implicit-def: $vgpr59
; SI-NEXT:    ; implicit-def: $vgpr58
; SI-NEXT:    ; implicit-def: $vgpr57
; SI-NEXT:    ; implicit-def: $vgpr56
; SI-NEXT:    ; implicit-def: $vgpr47
; SI-NEXT:    ; implicit-def: $vgpr46
; SI-NEXT:    ; implicit-def: $vgpr45
; SI-NEXT:    ; implicit-def: $vgpr44
; SI-NEXT:    ; implicit-def: $vgpr63
; SI-NEXT:    ; implicit-def: $vgpr62
; SI-NEXT:    ; implicit-def: $vgpr61
; SI-NEXT:    ; implicit-def: $vgpr60
; SI-NEXT:    s_waitcnt vmcnt(7)
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v13
; SI-NEXT:    v_or_b32_e32 v12, v12, v13
; SI-NEXT:    v_and_b32_e32 v13, 0xffff, v38
; SI-NEXT:    s_waitcnt vmcnt(6)
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v14
; SI-NEXT:    v_or_b32_e32 v13, v13, v14
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v37
; SI-NEXT:    s_waitcnt vmcnt(5)
; SI-NEXT:    v_lshlrev_b32_e32 v15, 16, v15
; SI-NEXT:    v_or_b32_e32 v14, v14, v15
; SI-NEXT:    v_and_b32_e32 v15, 0xffff, v36
; SI-NEXT:    s_waitcnt vmcnt(4)
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v16
; SI-NEXT:    v_or_b32_e32 v15, v15, v16
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v35
; SI-NEXT:    s_waitcnt vmcnt(3)
; SI-NEXT:    v_lshlrev_b32_e32 v17, 16, v17
; SI-NEXT:    v_or_b32_e32 v16, v16, v17
; SI-NEXT:    v_and_b32_e32 v17, 0xffff, v34
; SI-NEXT:    s_waitcnt vmcnt(2)
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v18
; SI-NEXT:    v_or_b32_e32 v17, v17, v18
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v33
; SI-NEXT:    s_waitcnt vmcnt(1)
; SI-NEXT:    v_lshlrev_b32_e32 v19, 16, v19
; SI-NEXT:    v_or_b32_e32 v18, v18, v19
; SI-NEXT:    v_and_b32_e32 v19, 0xffff, v32
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; SI-NEXT:    v_or_b32_e32 v19, v19, v20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:  .LBB18_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB18_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_cvt_f32_f16_e32 v0, v59
; SI-NEXT:    v_cvt_f32_f16_e32 v2, v58
; SI-NEXT:    v_cvt_f32_f16_e32 v1, v43
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v42
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_or_b32_e32 v0, v1, v0
; SI-NEXT:    v_or_b32_e32 v1, v3, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v2, v57
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v41
; SI-NEXT:    v_cvt_f32_f16_e32 v4, v40
; SI-NEXT:    v_cvt_f32_f16_e32 v5, v55
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_or_b32_e32 v2, v3, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v56
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v6, v54
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v7, v53
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_or_b32_e32 v3, v4, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v4, v47
; SI-NEXT:    v_cvt_f32_f16_e32 v8, v44
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v8, v8
; SI-NEXT:    v_cvt_f32_f16_e32 v9, v52
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_or_b32_e32 v4, v5, v4
; SI-NEXT:    v_cvt_f32_f16_e32 v5, v46
; SI-NEXT:    v_cvt_f32_f16_e32 v10, v51
; SI-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v9
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_add_f32_e32 v10, 0x38000000, v10
; SI-NEXT:    v_cvt_f16_f32_e32 v10, v10
; SI-NEXT:    v_cvt_f32_f16_e32 v11, v61
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_or_b32_e32 v5, v6, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v6, v45
; SI-NEXT:    v_cvt_f32_f16_e32 v12, v49
; SI-NEXT:    v_add_f32_e32 v11, 0x38000000, v11
; SI-NEXT:    v_cvt_f16_f32_e32 v11, v11
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v12, 0x38000000, v12
; SI-NEXT:    v_cvt_f16_f32_e32 v12, v12
; SI-NEXT:    v_cvt_f32_f16_e32 v13, v48
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_or_b32_e32 v6, v7, v6
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v8
; SI-NEXT:    v_cvt_f32_f16_e32 v8, v63
; SI-NEXT:    v_or_b32_e32 v7, v9, v7
; SI-NEXT:    v_cvt_f32_f16_e32 v9, v62
; SI-NEXT:    v_add_f32_e32 v13, 0x38000000, v13
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v8, v8
; SI-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v9
; SI-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:88 ; 4-byte Folded Reload
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_or_b32_e32 v8, v10, v8
; SI-NEXT:    v_cvt_f32_f16_e32 v10, v50
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v13, v13
; SI-NEXT:    v_cvt_f32_f16_e32 v15, v38
; SI-NEXT:    v_add_f32_e32 v10, 0x38000000, v10
; SI-NEXT:    v_cvt_f16_f32_e32 v10, v10
; SI-NEXT:    v_cvt_f32_f16_e32 v16, v37
; SI-NEXT:    v_add_f32_e32 v15, 0x38000000, v15
; SI-NEXT:    v_cvt_f16_f32_e32 v15, v15
; SI-NEXT:    v_or_b32_e32 v9, v10, v9
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v11
; SI-NEXT:    v_or_b32_e32 v10, v12, v10
; SI-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:92 ; 4-byte Folded Reload
; SI-NEXT:    v_cvt_f32_f16_e32 v11, v60
; SI-NEXT:    v_add_f32_e32 v16, 0x38000000, v16
; SI-NEXT:    v_cvt_f16_f32_e32 v16, v16
; SI-NEXT:    v_cvt_f32_f16_e32 v18, v35
; SI-NEXT:    v_add_f32_e32 v11, 0x38000000, v11
; SI-NEXT:    v_cvt_f16_f32_e32 v11, v11
; SI-NEXT:    v_cvt_f32_f16_e32 v19, v34
; SI-NEXT:    v_add_f32_e32 v18, 0x38000000, v18
; SI-NEXT:    v_cvt_f16_f32_e32 v18, v18
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; SI-NEXT:    v_or_b32_e32 v11, v13, v11
; SI-NEXT:    v_cvt_f32_f16_e32 v13, v39
; SI-NEXT:    v_add_f32_e32 v19, 0x38000000, v19
; SI-NEXT:    v_cvt_f16_f32_e32 v19, v19
; SI-NEXT:    v_cvt_f32_f16_e32 v21, v32
; SI-NEXT:    v_add_f32_e32 v13, 0x38000000, v13
; SI-NEXT:    v_cvt_f16_f32_e32 v13, v13
; SI-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:76 ; 4-byte Folded Reload
; SI-NEXT:    v_add_f32_e32 v21, 0x38000000, v21
; SI-NEXT:    v_cvt_f16_f32_e32 v21, v21
; SI-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(3)
; SI-NEXT:    v_cvt_f32_f16_e32 v14, v14
; SI-NEXT:    v_add_f32_e32 v14, 0x38000000, v14
; SI-NEXT:    v_cvt_f16_f32_e32 v14, v14
; SI-NEXT:    s_waitcnt vmcnt(2)
; SI-NEXT:    v_cvt_f32_f16_e32 v12, v12
; SI-NEXT:    v_add_f32_e32 v12, 0x38000000, v12
; SI-NEXT:    v_cvt_f16_f32_e32 v12, v12
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v12
; SI-NEXT:    v_or_b32_e32 v12, v13, v12
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v14
; SI-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:84 ; 4-byte Folded Reload
; SI-NEXT:    v_or_b32_e32 v13, v15, v13
; SI-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:80 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(3)
; SI-NEXT:    v_cvt_f32_f16_e32 v17, v17
; SI-NEXT:    s_waitcnt vmcnt(2)
; SI-NEXT:    v_cvt_f32_f16_e32 v20, v20
; SI-NEXT:    v_add_f32_e32 v17, 0x38000000, v17
; SI-NEXT:    v_cvt_f16_f32_e32 v17, v17
; SI-NEXT:    v_add_f32_e32 v20, 0x38000000, v20
; SI-NEXT:    v_cvt_f16_f32_e32 v20, v20
; SI-NEXT:    s_waitcnt vmcnt(1)
; SI-NEXT:    v_cvt_f32_f16_e32 v14, v14
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_cvt_f32_f16_e32 v15, v15
; SI-NEXT:    v_add_f32_e32 v14, 0x38000000, v14
; SI-NEXT:    v_cvt_f16_f32_e32 v14, v14
; SI-NEXT:    v_add_f32_e32 v15, 0x38000000, v15
; SI-NEXT:    v_cvt_f16_f32_e32 v15, v15
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v14
; SI-NEXT:    v_or_b32_e32 v14, v16, v14
; SI-NEXT:    v_cvt_f32_f16_e32 v16, v36
; SI-NEXT:    v_lshlrev_b32_e32 v15, 16, v15
; SI-NEXT:    v_add_f32_e32 v16, 0x38000000, v16
; SI-NEXT:    v_cvt_f16_f32_e32 v16, v16
; SI-NEXT:    v_or_b32_e32 v15, v16, v15
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v17
; SI-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:72 ; 4-byte Folded Reload
; SI-NEXT:    v_or_b32_e32 v16, v18, v16
; SI-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(1)
; SI-NEXT:    v_cvt_f32_f16_e32 v17, v17
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_cvt_f32_f16_e32 v18, v18
; SI-NEXT:    v_add_f32_e32 v17, 0x38000000, v17
; SI-NEXT:    v_cvt_f16_f32_e32 v17, v17
; SI-NEXT:    v_add_f32_e32 v18, 0x38000000, v18
; SI-NEXT:    v_cvt_f16_f32_e32 v18, v18
; SI-NEXT:    v_lshlrev_b32_e32 v17, 16, v17
; SI-NEXT:    v_or_b32_e32 v17, v19, v17
; SI-NEXT:    v_cvt_f32_f16_e32 v19, v33
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v18
; SI-NEXT:    v_add_f32_e32 v19, 0x38000000, v19
; SI-NEXT:    v_cvt_f16_f32_e32 v19, v19
; SI-NEXT:    v_or_b32_e32 v18, v19, v18
; SI-NEXT:    v_lshlrev_b32_e32 v19, 16, v20
; SI-NEXT:    v_or_b32_e32 v19, v21, v19
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:  .LBB18_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    buffer_load_dword v63, off, s[0:3], s32 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0)
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v40f16_to_v20i32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; VI-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; VI-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; VI-NEXT:    buffer_store_dword v43, off, s[0:3], s32 ; 4-byte Folded Spill
; VI-NEXT:    v_mov_b32_e32 v32, v19
; VI-NEXT:    v_mov_b32_e32 v33, v18
; VI-NEXT:    v_mov_b32_e32 v34, v17
; VI-NEXT:    v_mov_b32_e32 v35, v16
; VI-NEXT:    v_mov_b32_e32 v36, v15
; VI-NEXT:    v_mov_b32_e32 v37, v14
; VI-NEXT:    v_mov_b32_e32 v38, v13
; VI-NEXT:    v_mov_b32_e32 v39, v12
; VI-NEXT:    v_mov_b32_e32 v48, v11
; VI-NEXT:    v_mov_b32_e32 v49, v10
; VI-NEXT:    v_mov_b32_e32 v50, v9
; VI-NEXT:    v_mov_b32_e32 v51, v8
; VI-NEXT:    v_mov_b32_e32 v52, v7
; VI-NEXT:    v_mov_b32_e32 v53, v6
; VI-NEXT:    v_mov_b32_e32 v54, v5
; VI-NEXT:    v_mov_b32_e32 v55, v4
; VI-NEXT:    v_mov_b32_e32 v40, v3
; VI-NEXT:    v_mov_b32_e32 v41, v2
; VI-NEXT:    v_mov_b32_e32 v42, v1
; VI-NEXT:    v_mov_b32_e32 v43, v0
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB18_2
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_mov_b32_e32 v19, 16
; VI-NEXT:    v_lshlrev_b32_sdwa v0, v19, v43 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v1, v19, v42 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v2, v19, v41 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v3, v19, v40 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v4, v19, v55 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v5, v19, v54 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v6, v19, v53 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v7, v19, v52 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v8, v19, v51 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v9, v19, v50 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v10, v19, v49 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v11, v19, v48 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v12, v19, v39 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v13, v19, v38 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v14, v19, v37 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v15, v19, v36 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v16, v19, v35 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v17, v19, v34 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v18, v19, v33 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v19, v19, v32 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_or_b32_sdwa v0, v43, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v1, v42, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v2, v41, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v3, v40, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v4, v55, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v5, v54, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v6, v53, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v7, v52, v7 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v8, v51, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v9, v50, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v10, v49, v10 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v11, v48, v11 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v12, v39, v12 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v13, v38, v13 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v14, v37, v14 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v15, v36, v15 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v16, v35, v16 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v17, v34, v17 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v18, v33, v18 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v19, v32, v19 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr43
; VI-NEXT:    ; implicit-def: $vgpr42
; VI-NEXT:    ; implicit-def: $vgpr41
; VI-NEXT:    ; implicit-def: $vgpr40
; VI-NEXT:    ; implicit-def: $vgpr55
; VI-NEXT:    ; implicit-def: $vgpr54
; VI-NEXT:    ; implicit-def: $vgpr53
; VI-NEXT:    ; implicit-def: $vgpr52
; VI-NEXT:    ; implicit-def: $vgpr51
; VI-NEXT:    ; implicit-def: $vgpr50
; VI-NEXT:    ; implicit-def: $vgpr49
; VI-NEXT:    ; implicit-def: $vgpr48
; VI-NEXT:    ; implicit-def: $vgpr39
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr35
; VI-NEXT:    ; implicit-def: $vgpr34
; VI-NEXT:    ; implicit-def: $vgpr33
; VI-NEXT:    ; implicit-def: $vgpr32
; VI-NEXT:  .LBB18_2: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB18_4
; VI-NEXT:  ; %bb.3: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v19, 0x200
; VI-NEXT:    v_add_f16_sdwa v0, v43, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v1, 0x200, v43
; VI-NEXT:    v_or_b32_e32 v0, v1, v0
; VI-NEXT:    v_add_f16_sdwa v1, v42, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, 0x200, v42
; VI-NEXT:    v_or_b32_e32 v1, v2, v1
; VI-NEXT:    v_add_f16_sdwa v2, v41, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v3, 0x200, v41
; VI-NEXT:    v_or_b32_e32 v2, v3, v2
; VI-NEXT:    v_add_f16_sdwa v3, v40, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v4, 0x200, v40
; VI-NEXT:    v_or_b32_e32 v3, v4, v3
; VI-NEXT:    v_add_f16_sdwa v4, v55, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v5, 0x200, v55
; VI-NEXT:    v_or_b32_e32 v4, v5, v4
; VI-NEXT:    v_add_f16_sdwa v5, v54, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v6, 0x200, v54
; VI-NEXT:    v_or_b32_e32 v5, v6, v5
; VI-NEXT:    v_add_f16_sdwa v6, v53, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v7, 0x200, v53
; VI-NEXT:    v_or_b32_e32 v6, v7, v6
; VI-NEXT:    v_add_f16_sdwa v7, v52, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v8, 0x200, v52
; VI-NEXT:    v_or_b32_e32 v7, v8, v7
; VI-NEXT:    v_add_f16_sdwa v8, v51, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v9, 0x200, v51
; VI-NEXT:    v_or_b32_e32 v8, v9, v8
; VI-NEXT:    v_add_f16_sdwa v9, v50, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v10, 0x200, v50
; VI-NEXT:    v_or_b32_e32 v9, v10, v9
; VI-NEXT:    v_add_f16_sdwa v10, v49, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v11, 0x200, v49
; VI-NEXT:    v_or_b32_e32 v10, v11, v10
; VI-NEXT:    v_add_f16_sdwa v11, v48, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v12, 0x200, v48
; VI-NEXT:    v_or_b32_e32 v11, v12, v11
; VI-NEXT:    v_add_f16_sdwa v12, v39, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v13, 0x200, v39
; VI-NEXT:    v_or_b32_e32 v12, v13, v12
; VI-NEXT:    v_add_f16_sdwa v13, v38, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v14, 0x200, v38
; VI-NEXT:    v_or_b32_e32 v13, v14, v13
; VI-NEXT:    v_add_f16_sdwa v14, v37, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v15, 0x200, v37
; VI-NEXT:    v_or_b32_e32 v14, v15, v14
; VI-NEXT:    v_add_f16_sdwa v15, v36, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v16, 0x200, v36
; VI-NEXT:    v_or_b32_e32 v15, v16, v15
; VI-NEXT:    v_add_f16_sdwa v16, v35, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v17, 0x200, v35
; VI-NEXT:    v_or_b32_e32 v16, v17, v16
; VI-NEXT:    v_add_f16_sdwa v17, v34, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v18, 0x200, v34
; VI-NEXT:    v_or_b32_e32 v17, v18, v17
; VI-NEXT:    v_add_f16_sdwa v18, v33, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v20, 0x200, v33
; VI-NEXT:    v_or_b32_e32 v18, v20, v18
; VI-NEXT:    v_add_f16_sdwa v19, v32, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v20, 0x200, v32
; VI-NEXT:    v_or_b32_e32 v19, v20, v19
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:  .LBB18_4: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    buffer_load_dword v43, off, s[0:3], s32 ; 4-byte Folded Reload
; VI-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; VI-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; VI-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v40f16_to_v20i32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v63, off, s[0:3], s32 ; 4-byte Folded Spill
; GFX9-NEXT:    v_mov_b32_e32 v32, v19
; GFX9-NEXT:    v_mov_b32_e32 v33, v18
; GFX9-NEXT:    v_mov_b32_e32 v43, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v32
; GFX9-NEXT:    v_mov_b32_e32 v34, v17
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:64 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v33
; GFX9-NEXT:    v_mov_b32_e32 v35, v16
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:68 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v34
; GFX9-NEXT:    v_mov_b32_e32 v36, v15
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:72 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v35
; GFX9-NEXT:    v_mov_b32_e32 v37, v14
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:76 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v36
; GFX9-NEXT:    v_mov_b32_e32 v38, v13
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:80 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v37
; GFX9-NEXT:    v_mov_b32_e32 v39, v12
; GFX9-NEXT:    v_mov_b32_e32 v48, v11
; GFX9-NEXT:    v_mov_b32_e32 v49, v10
; GFX9-NEXT:    v_mov_b32_e32 v50, v9
; GFX9-NEXT:    v_mov_b32_e32 v51, v8
; GFX9-NEXT:    v_mov_b32_e32 v52, v7
; GFX9-NEXT:    v_mov_b32_e32 v53, v6
; GFX9-NEXT:    v_mov_b32_e32 v54, v5
; GFX9-NEXT:    v_mov_b32_e32 v55, v4
; GFX9-NEXT:    v_mov_b32_e32 v40, v3
; GFX9-NEXT:    v_mov_b32_e32 v41, v2
; GFX9-NEXT:    v_mov_b32_e32 v42, v1
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:84 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v38
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:88 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v39
; GFX9-NEXT:    v_lshrrev_b32_e32 v60, 16, v48
; GFX9-NEXT:    v_lshrrev_b32_e32 v61, 16, v49
; GFX9-NEXT:    v_lshrrev_b32_e32 v62, 16, v50
; GFX9-NEXT:    v_lshrrev_b32_e32 v63, 16, v51
; GFX9-NEXT:    v_lshrrev_b32_e32 v44, 16, v52
; GFX9-NEXT:    v_lshrrev_b32_e32 v45, 16, v53
; GFX9-NEXT:    v_lshrrev_b32_e32 v46, 16, v54
; GFX9-NEXT:    v_lshrrev_b32_e32 v47, 16, v55
; GFX9-NEXT:    v_lshrrev_b32_e32 v56, 16, v40
; GFX9-NEXT:    v_lshrrev_b32_e32 v57, 16, v41
; GFX9-NEXT:    v_lshrrev_b32_e32 v58, 16, v42
; GFX9-NEXT:    v_lshrrev_b32_e32 v59, 16, v43
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:92 ; 4-byte Folded Spill
; GFX9-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB18_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_mov_b32 s6, 0x5040100
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v12, 16, v39
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v13, 16, v38
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v14, 16, v37
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v15, 16, v36
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v16, 16, v35
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v17, 16, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v18, 16, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v19, 16, v32
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    v_perm_b32 v0, v59, v43, s6
; GFX9-NEXT:    v_perm_b32 v1, v58, v42, s6
; GFX9-NEXT:    v_perm_b32 v2, v57, v41, s6
; GFX9-NEXT:    v_perm_b32 v3, v56, v40, s6
; GFX9-NEXT:    v_perm_b32 v4, v47, v55, s6
; GFX9-NEXT:    v_perm_b32 v5, v46, v54, s6
; GFX9-NEXT:    v_perm_b32 v6, v45, v53, s6
; GFX9-NEXT:    v_perm_b32 v7, v44, v52, s6
; GFX9-NEXT:    v_perm_b32 v8, v63, v51, s6
; GFX9-NEXT:    v_perm_b32 v9, v62, v50, s6
; GFX9-NEXT:    v_perm_b32 v10, v61, v49, s6
; GFX9-NEXT:    v_perm_b32 v11, v60, v48, s6
; GFX9-NEXT:    v_perm_b32 v12, v12, v39, s6
; GFX9-NEXT:    v_perm_b32 v13, v13, v38, s6
; GFX9-NEXT:    v_perm_b32 v14, v14, v37, s6
; GFX9-NEXT:    v_perm_b32 v15, v15, v36, s6
; GFX9-NEXT:    v_perm_b32 v16, v16, v35, s6
; GFX9-NEXT:    v_perm_b32 v17, v17, v34, s6
; GFX9-NEXT:    v_perm_b32 v18, v18, v33, s6
; GFX9-NEXT:    v_perm_b32 v19, v19, v32, s6
; GFX9-NEXT:    ; implicit-def: $vgpr43
; GFX9-NEXT:    ; implicit-def: $vgpr42
; GFX9-NEXT:    ; implicit-def: $vgpr41
; GFX9-NEXT:    ; implicit-def: $vgpr40
; GFX9-NEXT:    ; implicit-def: $vgpr55
; GFX9-NEXT:    ; implicit-def: $vgpr54
; GFX9-NEXT:    ; implicit-def: $vgpr53
; GFX9-NEXT:    ; implicit-def: $vgpr52
; GFX9-NEXT:    ; implicit-def: $vgpr51
; GFX9-NEXT:    ; implicit-def: $vgpr50
; GFX9-NEXT:    ; implicit-def: $vgpr49
; GFX9-NEXT:    ; implicit-def: $vgpr48
; GFX9-NEXT:    ; implicit-def: $vgpr39
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr35
; GFX9-NEXT:    ; implicit-def: $vgpr34
; GFX9-NEXT:    ; implicit-def: $vgpr33
; GFX9-NEXT:    ; implicit-def: $vgpr32
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr60
; GFX9-NEXT:    ; implicit-def: $vgpr61
; GFX9-NEXT:    ; implicit-def: $vgpr62
; GFX9-NEXT:    ; implicit-def: $vgpr63
; GFX9-NEXT:    ; implicit-def: $vgpr44
; GFX9-NEXT:    ; implicit-def: $vgpr45
; GFX9-NEXT:    ; implicit-def: $vgpr46
; GFX9-NEXT:    ; implicit-def: $vgpr47
; GFX9-NEXT:    ; implicit-def: $vgpr56
; GFX9-NEXT:    ; implicit-def: $vgpr57
; GFX9-NEXT:    ; implicit-def: $vgpr58
; GFX9-NEXT:    ; implicit-def: $vgpr59
; GFX9-NEXT:  .LBB18_2: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB18_4
; GFX9-NEXT:  ; %bb.3: ; %cmp.true
; GFX9-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:92 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:88 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:84 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:80 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:76 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:72 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; GFX9-NEXT:    s_mov_b32 s6, 0x5040100
; GFX9-NEXT:    v_perm_b32 v0, v59, v43, s6
; GFX9-NEXT:    s_movk_i32 s7, 0x200
; GFX9-NEXT:    v_perm_b32 v1, v58, v42, s6
; GFX9-NEXT:    v_perm_b32 v2, v57, v41, s6
; GFX9-NEXT:    v_perm_b32 v3, v56, v40, s6
; GFX9-NEXT:    v_perm_b32 v4, v47, v55, s6
; GFX9-NEXT:    v_perm_b32 v5, v46, v54, s6
; GFX9-NEXT:    v_perm_b32 v6, v45, v53, s6
; GFX9-NEXT:    v_perm_b32 v7, v44, v52, s6
; GFX9-NEXT:    v_perm_b32 v8, v63, v51, s6
; GFX9-NEXT:    v_perm_b32 v9, v62, v50, s6
; GFX9-NEXT:    v_perm_b32 v10, v61, v49, s6
; GFX9-NEXT:    v_perm_b32 v11, v60, v48, s6
; GFX9-NEXT:    v_pk_add_f16 v0, v0, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v1, v1, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v2, v2, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v3, v3, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v4, v4, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v5, v5, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, v6, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v7, v7, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v8, v8, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v9, v9, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v10, v10, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v11, v11, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_waitcnt vmcnt(7)
; GFX9-NEXT:    v_perm_b32 v12, v12, v39, s6
; GFX9-NEXT:    s_waitcnt vmcnt(6)
; GFX9-NEXT:    v_perm_b32 v13, v13, v38, s6
; GFX9-NEXT:    s_waitcnt vmcnt(5)
; GFX9-NEXT:    v_perm_b32 v14, v14, v37, s6
; GFX9-NEXT:    s_waitcnt vmcnt(4)
; GFX9-NEXT:    v_perm_b32 v15, v15, v36, s6
; GFX9-NEXT:    s_waitcnt vmcnt(3)
; GFX9-NEXT:    v_perm_b32 v16, v16, v35, s6
; GFX9-NEXT:    s_waitcnt vmcnt(2)
; GFX9-NEXT:    v_perm_b32 v17, v17, v34, s6
; GFX9-NEXT:    s_waitcnt vmcnt(1)
; GFX9-NEXT:    v_perm_b32 v18, v18, v33, s6
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    v_perm_b32 v19, v19, v32, s6
; GFX9-NEXT:    v_pk_add_f16 v12, v12, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v13, v13, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v14, v14, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v15, v15, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v16, v16, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v17, v17, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v18, v18, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v19, v19, s7 op_sel_hi:[1,0]
; GFX9-NEXT:  .LBB18_4: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    buffer_load_dword v63, off, s[0:3], s32 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Reload
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v40f16_to_v20i32:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB18_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB18_4
; GFX11-TRUE16-NEXT:  .LBB18_2: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB18_3: ; %cmp.false
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB18_2
; GFX11-TRUE16-NEXT:  .LBB18_4: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v0, 0x200, v0 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v1, 0x200, v1 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v2, 0x200, v2 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v3, 0x200, v3 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v4, 0x200, v4 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v5, 0x200, v5 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v6, 0x200, v6 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v7, 0x200, v7 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v8, 0x200, v8 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v9, 0x200, v9 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v10, 0x200, v10 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v11, 0x200, v11 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v12, 0x200, v12 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v13, 0x200, v13 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v14, 0x200, v14 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v15, 0x200, v15 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v16, 0x200, v16 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v17, 0x200, v17 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v18, 0x200, v18 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v19, 0x200, v19 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v40f16_to_v20i32:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v48, 16, v3
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v20
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v37, v0, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v38, v1, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v39, v2, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v48, v3, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v36, v4, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v35, v5, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v34, v6, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v33, v7, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, v32, v8, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, v31, v9, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, v30, v10, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, v29, v11, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, v28, v12, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, v27, v13, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v14, v26, v14, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v15, v25, v15, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v16, v24, v16, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v17, v23, v17, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v18, v22, v18, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v19, v21, v19, 0x5040100
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB18_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB18_4
; GFX11-FAKE16-NEXT:  .LBB18_2: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB18_3: ; %cmp.false
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB18_2
; GFX11-FAKE16-NEXT:  .LBB18_4: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v0, 0x200, v0 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v1, 0x200, v1 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v2, 0x200, v2 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v3, 0x200, v3 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v4, 0x200, v4 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v5, 0x200, v5 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v6, 0x200, v6 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v7, 0x200, v7 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v8, 0x200, v8 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v9, 0x200, v9 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v10, 0x200, v10 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v11, 0x200, v11 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v12, 0x200, v12 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v13, 0x200, v13 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v14, 0x200, v14 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v15, 0x200, v15 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v16, 0x200, v16 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v17, 0x200, v17 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v18, 0x200, v18 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v19, 0x200, v19 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <40 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <40 x half> %a1 to <20 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <40 x half> %a to <20 x i32>
  br label %end

end:
  %phi = phi <20 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <20 x i32> %phi
}

define inreg <20 x i32> @bitcast_v40f16_to_v20i32_scalar(<40 x half> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v40f16_to_v20i32_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_writelane_b32 v32, s36, 0
; SI-NEXT:    v_writelane_b32 v32, s37, 1
; SI-NEXT:    v_writelane_b32 v32, s38, 2
; SI-NEXT:    v_writelane_b32 v32, s39, 3
; SI-NEXT:    v_writelane_b32 v32, s48, 4
; SI-NEXT:    v_writelane_b32 v32, s49, 5
; SI-NEXT:    v_writelane_b32 v32, s50, 6
; SI-NEXT:    v_writelane_b32 v32, s51, 7
; SI-NEXT:    v_writelane_b32 v32, s52, 8
; SI-NEXT:    v_writelane_b32 v32, s53, 9
; SI-NEXT:    v_writelane_b32 v32, s54, 10
; SI-NEXT:    v_writelane_b32 v32, s55, 11
; SI-NEXT:    v_writelane_b32 v32, s64, 12
; SI-NEXT:    v_writelane_b32 v32, s65, 13
; SI-NEXT:    v_writelane_b32 v32, s66, 14
; SI-NEXT:    v_writelane_b32 v32, s67, 15
; SI-NEXT:    v_readfirstlane_b32 s6, v5
; SI-NEXT:    v_readfirstlane_b32 s8, v4
; SI-NEXT:    v_readfirstlane_b32 s10, v3
; SI-NEXT:    v_readfirstlane_b32 s12, v2
; SI-NEXT:    v_readfirstlane_b32 s14, v1
; SI-NEXT:    v_readfirstlane_b32 s73, v0
; SI-NEXT:    s_lshr_b32 s72, s29, 16
; SI-NEXT:    s_lshr_b32 s75, s28, 16
; SI-NEXT:    s_lshr_b32 s76, s27, 16
; SI-NEXT:    s_lshr_b32 s77, s26, 16
; SI-NEXT:    s_lshr_b32 s78, s25, 16
; SI-NEXT:    s_lshr_b32 s79, s24, 16
; SI-NEXT:    s_lshr_b32 s88, s23, 16
; SI-NEXT:    s_lshr_b32 s89, s22, 16
; SI-NEXT:    s_lshr_b32 s90, s21, 16
; SI-NEXT:    s_lshr_b32 s91, s20, 16
; SI-NEXT:    s_lshr_b32 s92, s19, 16
; SI-NEXT:    s_lshr_b32 s93, s18, 16
; SI-NEXT:    s_lshr_b32 s94, s17, 16
; SI-NEXT:    s_lshr_b32 s95, s16, 16
; SI-NEXT:    s_lshr_b32 s7, s6, 16
; SI-NEXT:    s_lshr_b32 s9, s8, 16
; SI-NEXT:    s_lshr_b32 s11, s10, 16
; SI-NEXT:    s_lshr_b32 s13, s12, 16
; SI-NEXT:    s_lshr_b32 s15, s14, 16
; SI-NEXT:    s_lshr_b32 s74, s73, 16
; SI-NEXT:    v_readfirstlane_b32 s4, v6
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    s_cbranch_scc0 .LBB19_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s95, 16
; SI-NEXT:    s_or_b32 s36, s4, s5
; SI-NEXT:    s_and_b32 s4, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s94, 16
; SI-NEXT:    s_or_b32 s37, s4, s5
; SI-NEXT:    s_and_b32 s4, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s93, 16
; SI-NEXT:    s_or_b32 s38, s4, s5
; SI-NEXT:    s_and_b32 s4, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s92, 16
; SI-NEXT:    s_or_b32 s39, s4, s5
; SI-NEXT:    s_and_b32 s4, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s91, 16
; SI-NEXT:    s_or_b32 s40, s4, s5
; SI-NEXT:    s_and_b32 s4, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s90, 16
; SI-NEXT:    s_or_b32 s41, s4, s5
; SI-NEXT:    s_and_b32 s4, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s89, 16
; SI-NEXT:    s_or_b32 s42, s4, s5
; SI-NEXT:    s_and_b32 s4, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s88, 16
; SI-NEXT:    s_or_b32 s43, s4, s5
; SI-NEXT:    s_and_b32 s4, s24, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s79, 16
; SI-NEXT:    s_or_b32 s44, s4, s5
; SI-NEXT:    s_and_b32 s4, s25, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s78, 16
; SI-NEXT:    s_or_b32 s45, s4, s5
; SI-NEXT:    s_and_b32 s4, s26, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s77, 16
; SI-NEXT:    s_or_b32 s46, s4, s5
; SI-NEXT:    s_and_b32 s4, s27, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s76, 16
; SI-NEXT:    s_or_b32 s47, s4, s5
; SI-NEXT:    s_and_b32 s4, s28, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s75, 16
; SI-NEXT:    s_or_b32 s48, s4, s5
; SI-NEXT:    s_and_b32 s4, s29, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s72, 16
; SI-NEXT:    s_or_b32 s49, s4, s5
; SI-NEXT:    s_and_b32 s4, s73, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s74, 16
; SI-NEXT:    s_or_b32 s50, s4, s5
; SI-NEXT:    s_and_b32 s4, s14, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s15, 16
; SI-NEXT:    s_or_b32 s51, s4, s5
; SI-NEXT:    s_and_b32 s4, s12, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s13, 16
; SI-NEXT:    s_or_b32 s52, s4, s5
; SI-NEXT:    s_and_b32 s4, s10, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s11, 16
; SI-NEXT:    s_or_b32 s53, s4, s5
; SI-NEXT:    s_and_b32 s4, s8, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s9, 16
; SI-NEXT:    s_or_b32 s54, s4, s5
; SI-NEXT:    s_and_b32 s4, s6, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s7, 16
; SI-NEXT:    s_or_b32 s55, s4, s5
; SI-NEXT:    ; implicit-def: $sgpr56
; SI-NEXT:    ; implicit-def: $sgpr57
; SI-NEXT:    ; implicit-def: $sgpr58
; SI-NEXT:    ; implicit-def: $sgpr59
; SI-NEXT:    ; implicit-def: $sgpr60
; SI-NEXT:    ; implicit-def: $sgpr61
; SI-NEXT:    ; implicit-def: $sgpr62
; SI-NEXT:    ; implicit-def: $sgpr63
; SI-NEXT:    ; implicit-def: $sgpr64
; SI-NEXT:    ; implicit-def: $sgpr65
; SI-NEXT:    ; implicit-def: $sgpr66
; SI-NEXT:    ; implicit-def: $sgpr67
; SI-NEXT:    s_cbranch_execnz .LBB19_4
; SI-NEXT:  .LBB19_2: ; %cmp.true
; SI-NEXT:    v_cvt_f32_f16_e32 v0, s95
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s16
; SI-NEXT:    v_cvt_f32_f16_e32 v2, s94
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s17
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_cvt_f32_f16_e32 v4, s18
; SI-NEXT:    v_or_b32_e32 v0, v1, v0
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v2, s93
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_or_b32_e32 v1, v3, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s92
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_or_b32_e32 v2, v4, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v4, s19
; SI-NEXT:    v_cvt_f32_f16_e32 v5, s91
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v6, s20
; SI-NEXT:    v_or_b32_e32 v3, v4, v3
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v5, s90
; SI-NEXT:    v_cvt_f32_f16_e32 v7, s21
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_or_b32_e32 v4, v6, v4
; SI-NEXT:    v_cvt_f32_f16_e32 v6, s89
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_or_b32_e32 v5, v7, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v7, s22
; SI-NEXT:    v_cvt_f32_f16_e32 v8, s88
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v8, v8
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_cvt_f32_f16_e32 v9, s23
; SI-NEXT:    v_or_b32_e32 v6, v7, v6
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v8
; SI-NEXT:    v_cvt_f32_f16_e32 v8, s79
; SI-NEXT:    v_cvt_f32_f16_e32 v10, s24
; SI-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v9
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v8, v8
; SI-NEXT:    v_add_f32_e32 v10, 0x38000000, v10
; SI-NEXT:    v_cvt_f16_f32_e32 v10, v10
; SI-NEXT:    v_or_b32_e32 v7, v9, v7
; SI-NEXT:    v_cvt_f32_f16_e32 v9, s78
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_or_b32_e32 v8, v10, v8
; SI-NEXT:    v_cvt_f32_f16_e32 v10, s25
; SI-NEXT:    v_cvt_f32_f16_e32 v11, s77
; SI-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v9
; SI-NEXT:    v_add_f32_e32 v10, 0x38000000, v10
; SI-NEXT:    v_add_f32_e32 v11, 0x38000000, v11
; SI-NEXT:    v_cvt_f16_f32_e32 v10, v10
; SI-NEXT:    v_cvt_f16_f32_e32 v11, v11
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; SI-NEXT:    v_cvt_f32_f16_e32 v12, s26
; SI-NEXT:    v_or_b32_e32 v9, v10, v9
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v11
; SI-NEXT:    v_cvt_f32_f16_e32 v11, s76
; SI-NEXT:    v_cvt_f32_f16_e32 v13, s27
; SI-NEXT:    v_add_f32_e32 v12, 0x38000000, v12
; SI-NEXT:    v_cvt_f16_f32_e32 v12, v12
; SI-NEXT:    v_add_f32_e32 v11, 0x38000000, v11
; SI-NEXT:    v_cvt_f16_f32_e32 v11, v11
; SI-NEXT:    v_add_f32_e32 v13, 0x38000000, v13
; SI-NEXT:    v_cvt_f16_f32_e32 v13, v13
; SI-NEXT:    v_or_b32_e32 v10, v12, v10
; SI-NEXT:    v_cvt_f32_f16_e32 v12, s75
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; SI-NEXT:    v_or_b32_e32 v11, v13, v11
; SI-NEXT:    v_cvt_f32_f16_e32 v13, s28
; SI-NEXT:    v_cvt_f32_f16_e32 v14, s72
; SI-NEXT:    v_add_f32_e32 v12, 0x38000000, v12
; SI-NEXT:    v_cvt_f16_f32_e32 v12, v12
; SI-NEXT:    v_add_f32_e32 v13, 0x38000000, v13
; SI-NEXT:    v_add_f32_e32 v14, 0x38000000, v14
; SI-NEXT:    v_cvt_f16_f32_e32 v13, v13
; SI-NEXT:    v_cvt_f16_f32_e32 v14, v14
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v12
; SI-NEXT:    v_cvt_f32_f16_e32 v15, s29
; SI-NEXT:    v_or_b32_e32 v12, v13, v12
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v14
; SI-NEXT:    v_cvt_f32_f16_e32 v14, s74
; SI-NEXT:    v_cvt_f32_f16_e32 v16, s73
; SI-NEXT:    v_add_f32_e32 v15, 0x38000000, v15
; SI-NEXT:    v_cvt_f16_f32_e32 v15, v15
; SI-NEXT:    v_add_f32_e32 v14, 0x38000000, v14
; SI-NEXT:    v_cvt_f16_f32_e32 v14, v14
; SI-NEXT:    v_add_f32_e32 v16, 0x38000000, v16
; SI-NEXT:    v_cvt_f16_f32_e32 v16, v16
; SI-NEXT:    v_or_b32_e32 v13, v15, v13
; SI-NEXT:    v_cvt_f32_f16_e32 v15, s15
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v14
; SI-NEXT:    v_or_b32_e32 v14, v16, v14
; SI-NEXT:    v_cvt_f32_f16_e32 v16, s14
; SI-NEXT:    v_cvt_f32_f16_e32 v17, s13
; SI-NEXT:    v_add_f32_e32 v15, 0x38000000, v15
; SI-NEXT:    v_cvt_f16_f32_e32 v15, v15
; SI-NEXT:    v_add_f32_e32 v16, 0x38000000, v16
; SI-NEXT:    v_add_f32_e32 v17, 0x38000000, v17
; SI-NEXT:    v_cvt_f16_f32_e32 v16, v16
; SI-NEXT:    v_cvt_f16_f32_e32 v17, v17
; SI-NEXT:    v_lshlrev_b32_e32 v15, 16, v15
; SI-NEXT:    v_cvt_f32_f16_e32 v18, s12
; SI-NEXT:    v_or_b32_e32 v15, v16, v15
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v17
; SI-NEXT:    v_cvt_f32_f16_e32 v17, s11
; SI-NEXT:    v_cvt_f32_f16_e32 v19, s10
; SI-NEXT:    v_add_f32_e32 v18, 0x38000000, v18
; SI-NEXT:    v_cvt_f16_f32_e32 v18, v18
; SI-NEXT:    v_add_f32_e32 v17, 0x38000000, v17
; SI-NEXT:    v_cvt_f16_f32_e32 v17, v17
; SI-NEXT:    v_add_f32_e32 v19, 0x38000000, v19
; SI-NEXT:    v_cvt_f16_f32_e32 v19, v19
; SI-NEXT:    v_or_b32_e32 v16, v18, v16
; SI-NEXT:    v_cvt_f32_f16_e32 v18, s9
; SI-NEXT:    v_lshlrev_b32_e32 v17, 16, v17
; SI-NEXT:    v_or_b32_e32 v17, v19, v17
; SI-NEXT:    v_cvt_f32_f16_e32 v19, s8
; SI-NEXT:    v_cvt_f32_f16_e32 v20, s7
; SI-NEXT:    v_cvt_f32_f16_e32 v21, s6
; SI-NEXT:    v_add_f32_e32 v18, 0x38000000, v18
; SI-NEXT:    v_cvt_f16_f32_e32 v18, v18
; SI-NEXT:    v_add_f32_e32 v19, 0x38000000, v19
; SI-NEXT:    v_add_f32_e32 v20, 0x38000000, v20
; SI-NEXT:    v_cvt_f16_f32_e32 v19, v19
; SI-NEXT:    v_cvt_f16_f32_e32 v20, v20
; SI-NEXT:    v_add_f32_e32 v21, 0x38000000, v21
; SI-NEXT:    v_cvt_f16_f32_e32 v21, v21
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v18
; SI-NEXT:    v_or_b32_e32 v18, v19, v18
; SI-NEXT:    v_lshlrev_b32_e32 v19, 16, v20
; SI-NEXT:    v_or_b32_e32 v19, v21, v19
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    s_branch .LBB19_5
; SI-NEXT:  .LBB19_3:
; SI-NEXT:    ; implicit-def: $sgpr36_sgpr37_sgpr38_sgpr39_sgpr40_sgpr41_sgpr42_sgpr43_sgpr44_sgpr45_sgpr46_sgpr47_sgpr48_sgpr49_sgpr50_sgpr51_sgpr52_sgpr53_sgpr54_sgpr55_sgpr56_sgpr57_sgpr58_sgpr59_sgpr60_sgpr61_sgpr62_sgpr63_sgpr64_sgpr65_sgpr66_sgpr67
; SI-NEXT:    s_branch .LBB19_2
; SI-NEXT:  .LBB19_4:
; SI-NEXT:    v_mov_b32_e32 v0, s36
; SI-NEXT:    v_mov_b32_e32 v1, s37
; SI-NEXT:    v_mov_b32_e32 v2, s38
; SI-NEXT:    v_mov_b32_e32 v3, s39
; SI-NEXT:    v_mov_b32_e32 v4, s40
; SI-NEXT:    v_mov_b32_e32 v5, s41
; SI-NEXT:    v_mov_b32_e32 v6, s42
; SI-NEXT:    v_mov_b32_e32 v7, s43
; SI-NEXT:    v_mov_b32_e32 v8, s44
; SI-NEXT:    v_mov_b32_e32 v9, s45
; SI-NEXT:    v_mov_b32_e32 v10, s46
; SI-NEXT:    v_mov_b32_e32 v11, s47
; SI-NEXT:    v_mov_b32_e32 v12, s48
; SI-NEXT:    v_mov_b32_e32 v13, s49
; SI-NEXT:    v_mov_b32_e32 v14, s50
; SI-NEXT:    v_mov_b32_e32 v15, s51
; SI-NEXT:    v_mov_b32_e32 v16, s52
; SI-NEXT:    v_mov_b32_e32 v17, s53
; SI-NEXT:    v_mov_b32_e32 v18, s54
; SI-NEXT:    v_mov_b32_e32 v19, s55
; SI-NEXT:    v_mov_b32_e32 v20, s56
; SI-NEXT:    v_mov_b32_e32 v21, s57
; SI-NEXT:    v_mov_b32_e32 v22, s58
; SI-NEXT:    v_mov_b32_e32 v23, s59
; SI-NEXT:    v_mov_b32_e32 v24, s60
; SI-NEXT:    v_mov_b32_e32 v25, s61
; SI-NEXT:    v_mov_b32_e32 v26, s62
; SI-NEXT:    v_mov_b32_e32 v27, s63
; SI-NEXT:    v_mov_b32_e32 v28, s64
; SI-NEXT:    v_mov_b32_e32 v29, s65
; SI-NEXT:    v_mov_b32_e32 v30, s66
; SI-NEXT:    v_mov_b32_e32 v31, s67
; SI-NEXT:  .LBB19_5: ; %end
; SI-NEXT:    v_readlane_b32 s67, v32, 15
; SI-NEXT:    v_readlane_b32 s66, v32, 14
; SI-NEXT:    v_readlane_b32 s65, v32, 13
; SI-NEXT:    v_readlane_b32 s64, v32, 12
; SI-NEXT:    v_readlane_b32 s55, v32, 11
; SI-NEXT:    v_readlane_b32 s54, v32, 10
; SI-NEXT:    v_readlane_b32 s53, v32, 9
; SI-NEXT:    v_readlane_b32 s52, v32, 8
; SI-NEXT:    v_readlane_b32 s51, v32, 7
; SI-NEXT:    v_readlane_b32 s50, v32, 6
; SI-NEXT:    v_readlane_b32 s49, v32, 5
; SI-NEXT:    v_readlane_b32 s48, v32, 4
; SI-NEXT:    v_readlane_b32 s39, v32, 3
; SI-NEXT:    v_readlane_b32 s38, v32, 2
; SI-NEXT:    v_readlane_b32 s37, v32, 1
; SI-NEXT:    v_readlane_b32 s36, v32, 0
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v40f16_to_v20i32_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    v_writelane_b32 v32, s34, 0
; VI-NEXT:    v_writelane_b32 v32, s35, 1
; VI-NEXT:    v_writelane_b32 v32, s36, 2
; VI-NEXT:    v_writelane_b32 v32, s37, 3
; VI-NEXT:    v_writelane_b32 v32, s38, 4
; VI-NEXT:    v_writelane_b32 v32, s39, 5
; VI-NEXT:    v_writelane_b32 v32, s48, 6
; VI-NEXT:    v_writelane_b32 v32, s49, 7
; VI-NEXT:    v_writelane_b32 v32, s50, 8
; VI-NEXT:    v_writelane_b32 v32, s51, 9
; VI-NEXT:    v_writelane_b32 v32, s52, 10
; VI-NEXT:    v_writelane_b32 v32, s53, 11
; VI-NEXT:    v_writelane_b32 v32, s54, 12
; VI-NEXT:    v_writelane_b32 v32, s55, 13
; VI-NEXT:    v_writelane_b32 v32, s64, 14
; VI-NEXT:    v_writelane_b32 v32, s65, 15
; VI-NEXT:    v_writelane_b32 v32, s66, 16
; VI-NEXT:    v_writelane_b32 v32, s67, 17
; VI-NEXT:    v_writelane_b32 v32, s30, 18
; VI-NEXT:    v_writelane_b32 v32, s31, 19
; VI-NEXT:    v_readfirstlane_b32 s6, v5
; VI-NEXT:    v_readfirstlane_b32 s8, v4
; VI-NEXT:    v_readfirstlane_b32 s11, v3
; VI-NEXT:    v_readfirstlane_b32 s14, v2
; VI-NEXT:    v_readfirstlane_b32 s73, v1
; VI-NEXT:    v_readfirstlane_b32 s76, v0
; VI-NEXT:    s_lshr_b32 s10, s29, 16
; VI-NEXT:    s_lshr_b32 s13, s28, 16
; VI-NEXT:    s_lshr_b32 s72, s27, 16
; VI-NEXT:    s_lshr_b32 s74, s26, 16
; VI-NEXT:    s_lshr_b32 s77, s25, 16
; VI-NEXT:    s_lshr_b32 s79, s24, 16
; VI-NEXT:    s_lshr_b32 s88, s23, 16
; VI-NEXT:    s_lshr_b32 s89, s22, 16
; VI-NEXT:    s_lshr_b32 s90, s21, 16
; VI-NEXT:    s_lshr_b32 s91, s20, 16
; VI-NEXT:    s_lshr_b32 s30, s19, 16
; VI-NEXT:    s_lshr_b32 s31, s18, 16
; VI-NEXT:    s_lshr_b32 s34, s17, 16
; VI-NEXT:    s_lshr_b32 s35, s16, 16
; VI-NEXT:    s_lshr_b32 s7, s6, 16
; VI-NEXT:    s_lshr_b32 s9, s8, 16
; VI-NEXT:    s_lshr_b32 s12, s11, 16
; VI-NEXT:    s_lshr_b32 s15, s14, 16
; VI-NEXT:    s_lshr_b32 s75, s73, 16
; VI-NEXT:    s_lshr_b32 s78, s76, 16
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    s_cbranch_scc0 .LBB19_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_and_b32 s4, 0xffff, s16
; VI-NEXT:    s_lshl_b32 s5, s35, 16
; VI-NEXT:    s_or_b32 s36, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s17
; VI-NEXT:    s_lshl_b32 s5, s34, 16
; VI-NEXT:    s_or_b32 s37, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s18
; VI-NEXT:    s_lshl_b32 s5, s31, 16
; VI-NEXT:    s_or_b32 s38, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s19
; VI-NEXT:    s_lshl_b32 s5, s30, 16
; VI-NEXT:    s_or_b32 s39, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s20
; VI-NEXT:    s_lshl_b32 s5, s91, 16
; VI-NEXT:    s_or_b32 s40, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s21
; VI-NEXT:    s_lshl_b32 s5, s90, 16
; VI-NEXT:    s_or_b32 s41, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s22
; VI-NEXT:    s_lshl_b32 s5, s89, 16
; VI-NEXT:    s_or_b32 s42, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s23
; VI-NEXT:    s_lshl_b32 s5, s88, 16
; VI-NEXT:    s_or_b32 s43, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s24
; VI-NEXT:    s_lshl_b32 s5, s79, 16
; VI-NEXT:    s_or_b32 s44, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s25
; VI-NEXT:    s_lshl_b32 s5, s77, 16
; VI-NEXT:    s_or_b32 s45, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s26
; VI-NEXT:    s_lshl_b32 s5, s74, 16
; VI-NEXT:    s_or_b32 s46, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s27
; VI-NEXT:    s_lshl_b32 s5, s72, 16
; VI-NEXT:    s_or_b32 s47, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s28
; VI-NEXT:    s_lshl_b32 s5, s13, 16
; VI-NEXT:    s_or_b32 s48, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s29
; VI-NEXT:    s_lshl_b32 s5, s10, 16
; VI-NEXT:    s_or_b32 s49, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s76
; VI-NEXT:    s_lshl_b32 s5, s78, 16
; VI-NEXT:    s_or_b32 s50, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s73
; VI-NEXT:    s_lshl_b32 s5, s75, 16
; VI-NEXT:    s_or_b32 s51, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s14
; VI-NEXT:    s_lshl_b32 s5, s15, 16
; VI-NEXT:    s_or_b32 s52, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s11
; VI-NEXT:    s_lshl_b32 s5, s12, 16
; VI-NEXT:    s_or_b32 s53, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s8
; VI-NEXT:    s_lshl_b32 s5, s9, 16
; VI-NEXT:    s_or_b32 s54, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s6
; VI-NEXT:    s_lshl_b32 s5, s7, 16
; VI-NEXT:    s_or_b32 s55, s4, s5
; VI-NEXT:    ; implicit-def: $sgpr56
; VI-NEXT:    ; implicit-def: $sgpr57
; VI-NEXT:    ; implicit-def: $sgpr58
; VI-NEXT:    ; implicit-def: $sgpr59
; VI-NEXT:    ; implicit-def: $sgpr60
; VI-NEXT:    ; implicit-def: $sgpr61
; VI-NEXT:    ; implicit-def: $sgpr62
; VI-NEXT:    ; implicit-def: $sgpr63
; VI-NEXT:    ; implicit-def: $sgpr64
; VI-NEXT:    ; implicit-def: $sgpr65
; VI-NEXT:    ; implicit-def: $sgpr66
; VI-NEXT:    ; implicit-def: $sgpr67
; VI-NEXT:    s_cbranch_execnz .LBB19_4
; VI-NEXT:  .LBB19_2: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v19, 0x200
; VI-NEXT:    v_mov_b32_e32 v0, s35
; VI-NEXT:    v_mov_b32_e32 v2, s34
; VI-NEXT:    v_add_f16_sdwa v0, v0, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v1, s16, v19
; VI-NEXT:    v_add_f16_sdwa v2, v2, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v3, s17, v19
; VI-NEXT:    v_or_b32_e32 v0, v1, v0
; VI-NEXT:    v_or_b32_e32 v1, v3, v2
; VI-NEXT:    v_mov_b32_e32 v2, s31
; VI-NEXT:    v_add_f16_sdwa v2, v2, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v3, s18, v19
; VI-NEXT:    v_or_b32_e32 v2, v3, v2
; VI-NEXT:    v_mov_b32_e32 v3, s30
; VI-NEXT:    v_add_f16_sdwa v3, v3, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v4, s19, v19
; VI-NEXT:    v_or_b32_e32 v3, v4, v3
; VI-NEXT:    v_mov_b32_e32 v4, s91
; VI-NEXT:    v_add_f16_sdwa v4, v4, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v5, s20, v19
; VI-NEXT:    v_or_b32_e32 v4, v5, v4
; VI-NEXT:    v_mov_b32_e32 v5, s90
; VI-NEXT:    v_add_f16_sdwa v5, v5, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v6, s21, v19
; VI-NEXT:    v_or_b32_e32 v5, v6, v5
; VI-NEXT:    v_mov_b32_e32 v6, s89
; VI-NEXT:    v_add_f16_sdwa v6, v6, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v7, s22, v19
; VI-NEXT:    v_or_b32_e32 v6, v7, v6
; VI-NEXT:    v_mov_b32_e32 v7, s88
; VI-NEXT:    v_add_f16_sdwa v7, v7, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v8, s23, v19
; VI-NEXT:    v_or_b32_e32 v7, v8, v7
; VI-NEXT:    v_mov_b32_e32 v8, s79
; VI-NEXT:    v_add_f16_sdwa v8, v8, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v9, s24, v19
; VI-NEXT:    v_or_b32_e32 v8, v9, v8
; VI-NEXT:    v_mov_b32_e32 v9, s77
; VI-NEXT:    v_add_f16_sdwa v9, v9, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v10, s25, v19
; VI-NEXT:    v_or_b32_e32 v9, v10, v9
; VI-NEXT:    v_mov_b32_e32 v10, s74
; VI-NEXT:    v_add_f16_sdwa v10, v10, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v11, s26, v19
; VI-NEXT:    v_or_b32_e32 v10, v11, v10
; VI-NEXT:    v_mov_b32_e32 v11, s72
; VI-NEXT:    v_add_f16_sdwa v11, v11, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v12, s27, v19
; VI-NEXT:    v_or_b32_e32 v11, v12, v11
; VI-NEXT:    v_mov_b32_e32 v12, s13
; VI-NEXT:    v_add_f16_sdwa v12, v12, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v13, s28, v19
; VI-NEXT:    v_or_b32_e32 v12, v13, v12
; VI-NEXT:    v_mov_b32_e32 v13, s10
; VI-NEXT:    v_add_f16_sdwa v13, v13, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v14, s29, v19
; VI-NEXT:    v_or_b32_e32 v13, v14, v13
; VI-NEXT:    v_mov_b32_e32 v14, s78
; VI-NEXT:    v_add_f16_sdwa v14, v14, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v15, s76, v19
; VI-NEXT:    v_or_b32_e32 v14, v15, v14
; VI-NEXT:    v_mov_b32_e32 v15, s75
; VI-NEXT:    v_add_f16_sdwa v15, v15, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v16, s73, v19
; VI-NEXT:    v_or_b32_e32 v15, v16, v15
; VI-NEXT:    v_mov_b32_e32 v16, s15
; VI-NEXT:    v_add_f16_sdwa v16, v16, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v17, s14, v19
; VI-NEXT:    v_or_b32_e32 v16, v17, v16
; VI-NEXT:    v_mov_b32_e32 v17, s12
; VI-NEXT:    v_add_f16_sdwa v17, v17, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v18, s11, v19
; VI-NEXT:    v_or_b32_e32 v17, v18, v17
; VI-NEXT:    v_mov_b32_e32 v18, s9
; VI-NEXT:    v_add_f16_sdwa v18, v18, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v20, s8, v19
; VI-NEXT:    v_or_b32_e32 v18, v20, v18
; VI-NEXT:    v_mov_b32_e32 v20, s7
; VI-NEXT:    v_add_f16_sdwa v20, v20, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v19, s6, v19
; VI-NEXT:    v_or_b32_e32 v19, v19, v20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    s_branch .LBB19_5
; VI-NEXT:  .LBB19_3:
; VI-NEXT:    ; implicit-def: $sgpr36_sgpr37_sgpr38_sgpr39_sgpr40_sgpr41_sgpr42_sgpr43_sgpr44_sgpr45_sgpr46_sgpr47_sgpr48_sgpr49_sgpr50_sgpr51_sgpr52_sgpr53_sgpr54_sgpr55_sgpr56_sgpr57_sgpr58_sgpr59_sgpr60_sgpr61_sgpr62_sgpr63_sgpr64_sgpr65_sgpr66_sgpr67
; VI-NEXT:    s_branch .LBB19_2
; VI-NEXT:  .LBB19_4:
; VI-NEXT:    v_mov_b32_e32 v0, s36
; VI-NEXT:    v_mov_b32_e32 v1, s37
; VI-NEXT:    v_mov_b32_e32 v2, s38
; VI-NEXT:    v_mov_b32_e32 v3, s39
; VI-NEXT:    v_mov_b32_e32 v4, s40
; VI-NEXT:    v_mov_b32_e32 v5, s41
; VI-NEXT:    v_mov_b32_e32 v6, s42
; VI-NEXT:    v_mov_b32_e32 v7, s43
; VI-NEXT:    v_mov_b32_e32 v8, s44
; VI-NEXT:    v_mov_b32_e32 v9, s45
; VI-NEXT:    v_mov_b32_e32 v10, s46
; VI-NEXT:    v_mov_b32_e32 v11, s47
; VI-NEXT:    v_mov_b32_e32 v12, s48
; VI-NEXT:    v_mov_b32_e32 v13, s49
; VI-NEXT:    v_mov_b32_e32 v14, s50
; VI-NEXT:    v_mov_b32_e32 v15, s51
; VI-NEXT:    v_mov_b32_e32 v16, s52
; VI-NEXT:    v_mov_b32_e32 v17, s53
; VI-NEXT:    v_mov_b32_e32 v18, s54
; VI-NEXT:    v_mov_b32_e32 v19, s55
; VI-NEXT:    v_mov_b32_e32 v20, s56
; VI-NEXT:    v_mov_b32_e32 v21, s57
; VI-NEXT:    v_mov_b32_e32 v22, s58
; VI-NEXT:    v_mov_b32_e32 v23, s59
; VI-NEXT:    v_mov_b32_e32 v24, s60
; VI-NEXT:    v_mov_b32_e32 v25, s61
; VI-NEXT:    v_mov_b32_e32 v26, s62
; VI-NEXT:    v_mov_b32_e32 v27, s63
; VI-NEXT:    v_mov_b32_e32 v28, s64
; VI-NEXT:    v_mov_b32_e32 v29, s65
; VI-NEXT:    v_mov_b32_e32 v30, s66
; VI-NEXT:    v_mov_b32_e32 v31, s67
; VI-NEXT:  .LBB19_5: ; %end
; VI-NEXT:    v_readlane_b32 s30, v32, 18
; VI-NEXT:    v_readlane_b32 s31, v32, 19
; VI-NEXT:    v_readlane_b32 s67, v32, 17
; VI-NEXT:    v_readlane_b32 s66, v32, 16
; VI-NEXT:    v_readlane_b32 s65, v32, 15
; VI-NEXT:    v_readlane_b32 s64, v32, 14
; VI-NEXT:    v_readlane_b32 s55, v32, 13
; VI-NEXT:    v_readlane_b32 s54, v32, 12
; VI-NEXT:    v_readlane_b32 s53, v32, 11
; VI-NEXT:    v_readlane_b32 s52, v32, 10
; VI-NEXT:    v_readlane_b32 s51, v32, 9
; VI-NEXT:    v_readlane_b32 s50, v32, 8
; VI-NEXT:    v_readlane_b32 s49, v32, 7
; VI-NEXT:    v_readlane_b32 s48, v32, 6
; VI-NEXT:    v_readlane_b32 s39, v32, 5
; VI-NEXT:    v_readlane_b32 s38, v32, 4
; VI-NEXT:    v_readlane_b32 s37, v32, 3
; VI-NEXT:    v_readlane_b32 s36, v32, 2
; VI-NEXT:    v_readlane_b32 s35, v32, 1
; VI-NEXT:    v_readlane_b32 s34, v32, 0
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v40f16_to_v20i32_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    v_writelane_b32 v32, s36, 0
; GFX9-NEXT:    v_writelane_b32 v32, s37, 1
; GFX9-NEXT:    v_writelane_b32 v32, s38, 2
; GFX9-NEXT:    v_writelane_b32 v32, s39, 3
; GFX9-NEXT:    v_writelane_b32 v32, s48, 4
; GFX9-NEXT:    v_writelane_b32 v32, s49, 5
; GFX9-NEXT:    v_writelane_b32 v32, s50, 6
; GFX9-NEXT:    v_writelane_b32 v32, s51, 7
; GFX9-NEXT:    v_writelane_b32 v32, s52, 8
; GFX9-NEXT:    v_writelane_b32 v32, s53, 9
; GFX9-NEXT:    v_writelane_b32 v32, s54, 10
; GFX9-NEXT:    v_writelane_b32 v32, s55, 11
; GFX9-NEXT:    v_readfirstlane_b32 s56, v5
; GFX9-NEXT:    v_readfirstlane_b32 s58, v4
; GFX9-NEXT:    v_readfirstlane_b32 s60, v3
; GFX9-NEXT:    v_readfirstlane_b32 s62, v2
; GFX9-NEXT:    v_readfirstlane_b32 s72, v1
; GFX9-NEXT:    v_readfirstlane_b32 s74, v0
; GFX9-NEXT:    s_lshr_b32 s4, s29, 16
; GFX9-NEXT:    s_lshr_b32 s5, s28, 16
; GFX9-NEXT:    s_lshr_b32 s6, s27, 16
; GFX9-NEXT:    s_lshr_b32 s7, s26, 16
; GFX9-NEXT:    s_lshr_b32 s8, s25, 16
; GFX9-NEXT:    s_lshr_b32 s9, s24, 16
; GFX9-NEXT:    s_lshr_b32 s10, s23, 16
; GFX9-NEXT:    s_lshr_b32 s11, s22, 16
; GFX9-NEXT:    s_lshr_b32 s12, s21, 16
; GFX9-NEXT:    s_lshr_b32 s13, s20, 16
; GFX9-NEXT:    s_lshr_b32 s14, s19, 16
; GFX9-NEXT:    s_lshr_b32 s15, s18, 16
; GFX9-NEXT:    s_lshr_b32 s40, s17, 16
; GFX9-NEXT:    s_lshr_b32 s41, s16, 16
; GFX9-NEXT:    s_lshr_b32 s57, s56, 16
; GFX9-NEXT:    s_lshr_b32 s59, s58, 16
; GFX9-NEXT:    s_lshr_b32 s61, s60, 16
; GFX9-NEXT:    s_lshr_b32 s63, s62, 16
; GFX9-NEXT:    s_lshr_b32 s73, s72, 16
; GFX9-NEXT:    s_lshr_b32 s75, s74, 16
; GFX9-NEXT:    v_readfirstlane_b32 s42, v6
; GFX9-NEXT:    s_cmp_lg_u32 s42, 0
; GFX9-NEXT:    s_pack_ll_b32_b16 s36, s16, s41
; GFX9-NEXT:    s_pack_ll_b32_b16 s37, s17, s40
; GFX9-NEXT:    s_pack_ll_b32_b16 s38, s18, s15
; GFX9-NEXT:    s_pack_ll_b32_b16 s39, s19, s14
; GFX9-NEXT:    s_pack_ll_b32_b16 s40, s20, s13
; GFX9-NEXT:    s_pack_ll_b32_b16 s41, s21, s12
; GFX9-NEXT:    s_pack_ll_b32_b16 s42, s22, s11
; GFX9-NEXT:    s_pack_ll_b32_b16 s43, s23, s10
; GFX9-NEXT:    s_pack_ll_b32_b16 s44, s24, s9
; GFX9-NEXT:    s_pack_ll_b32_b16 s45, s25, s8
; GFX9-NEXT:    s_pack_ll_b32_b16 s46, s26, s7
; GFX9-NEXT:    s_pack_ll_b32_b16 s47, s27, s6
; GFX9-NEXT:    s_pack_ll_b32_b16 s48, s28, s5
; GFX9-NEXT:    s_pack_ll_b32_b16 s49, s29, s4
; GFX9-NEXT:    s_pack_ll_b32_b16 s50, s74, s75
; GFX9-NEXT:    s_pack_ll_b32_b16 s51, s72, s73
; GFX9-NEXT:    s_pack_ll_b32_b16 s52, s62, s63
; GFX9-NEXT:    s_pack_ll_b32_b16 s53, s60, s61
; GFX9-NEXT:    s_pack_ll_b32_b16 s54, s58, s59
; GFX9-NEXT:    s_pack_ll_b32_b16 s55, s56, s57
; GFX9-NEXT:    s_cbranch_scc0 .LBB19_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB19_4
; GFX9-NEXT:  .LBB19_2: ; %cmp.true
; GFX9-NEXT:    v_mov_b32_e32 v19, 0x200
; GFX9-NEXT:    v_pk_add_f16 v0, s36, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v1, s37, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v2, s38, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v3, s39, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v4, s40, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v5, s41, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, s42, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v7, s43, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v8, s44, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v9, s45, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v10, s46, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v11, s47, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v12, s48, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v13, s49, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v14, s50, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v15, s51, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v16, s52, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v17, s53, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v18, s54, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v19, s55, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_branch .LBB19_5
; GFX9-NEXT:  .LBB19_3:
; GFX9-NEXT:    s_branch .LBB19_2
; GFX9-NEXT:  .LBB19_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s36
; GFX9-NEXT:    v_mov_b32_e32 v1, s37
; GFX9-NEXT:    v_mov_b32_e32 v2, s38
; GFX9-NEXT:    v_mov_b32_e32 v3, s39
; GFX9-NEXT:    v_mov_b32_e32 v4, s40
; GFX9-NEXT:    v_mov_b32_e32 v5, s41
; GFX9-NEXT:    v_mov_b32_e32 v6, s42
; GFX9-NEXT:    v_mov_b32_e32 v7, s43
; GFX9-NEXT:    v_mov_b32_e32 v8, s44
; GFX9-NEXT:    v_mov_b32_e32 v9, s45
; GFX9-NEXT:    v_mov_b32_e32 v10, s46
; GFX9-NEXT:    v_mov_b32_e32 v11, s47
; GFX9-NEXT:    v_mov_b32_e32 v12, s48
; GFX9-NEXT:    v_mov_b32_e32 v13, s49
; GFX9-NEXT:    v_mov_b32_e32 v14, s50
; GFX9-NEXT:    v_mov_b32_e32 v15, s51
; GFX9-NEXT:    v_mov_b32_e32 v16, s52
; GFX9-NEXT:    v_mov_b32_e32 v17, s53
; GFX9-NEXT:    v_mov_b32_e32 v18, s54
; GFX9-NEXT:    v_mov_b32_e32 v19, s55
; GFX9-NEXT:    v_mov_b32_e32 v20, s56
; GFX9-NEXT:    v_mov_b32_e32 v21, s57
; GFX9-NEXT:    v_mov_b32_e32 v22, s58
; GFX9-NEXT:    v_mov_b32_e32 v23, s59
; GFX9-NEXT:    v_mov_b32_e32 v24, s60
; GFX9-NEXT:    v_mov_b32_e32 v25, s61
; GFX9-NEXT:    v_mov_b32_e32 v26, s62
; GFX9-NEXT:    v_mov_b32_e32 v27, s63
; GFX9-NEXT:    v_mov_b32_e32 v28, s64
; GFX9-NEXT:    v_mov_b32_e32 v29, s65
; GFX9-NEXT:    v_mov_b32_e32 v30, s66
; GFX9-NEXT:    v_mov_b32_e32 v31, s67
; GFX9-NEXT:  .LBB19_5: ; %end
; GFX9-NEXT:    v_readlane_b32 s55, v32, 11
; GFX9-NEXT:    v_readlane_b32 s54, v32, 10
; GFX9-NEXT:    v_readlane_b32 s53, v32, 9
; GFX9-NEXT:    v_readlane_b32 s52, v32, 8
; GFX9-NEXT:    v_readlane_b32 s51, v32, 7
; GFX9-NEXT:    v_readlane_b32 s50, v32, 6
; GFX9-NEXT:    v_readlane_b32 s49, v32, 5
; GFX9-NEXT:    v_readlane_b32 s48, v32, 4
; GFX9-NEXT:    v_readlane_b32 s39, v32, 3
; GFX9-NEXT:    v_readlane_b32 s38, v32, 2
; GFX9-NEXT:    v_readlane_b32 s37, v32, 1
; GFX9-NEXT:    v_readlane_b32 s36, v32, 0
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v40f16_to_v20i32_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    v_readfirstlane_b32 s45, v1
; GFX11-NEXT:    v_readfirstlane_b32 s46, v0
; GFX11-NEXT:    v_readfirstlane_b32 s56, v2
; GFX11-NEXT:    s_lshr_b32 s41, s29, 16
; GFX11-NEXT:    s_lshr_b32 s42, s28, 16
; GFX11-NEXT:    s_lshr_b32 s15, s27, 16
; GFX11-NEXT:    s_lshr_b32 s14, s26, 16
; GFX11-NEXT:    s_lshr_b32 s13, s25, 16
; GFX11-NEXT:    s_lshr_b32 s12, s24, 16
; GFX11-NEXT:    s_lshr_b32 s11, s23, 16
; GFX11-NEXT:    s_lshr_b32 s10, s22, 16
; GFX11-NEXT:    s_lshr_b32 s9, s21, 16
; GFX11-NEXT:    s_lshr_b32 s8, s20, 16
; GFX11-NEXT:    s_lshr_b32 s7, s19, 16
; GFX11-NEXT:    s_lshr_b32 s6, s18, 16
; GFX11-NEXT:    s_lshr_b32 s5, s17, 16
; GFX11-NEXT:    s_lshr_b32 s4, s16, 16
; GFX11-NEXT:    s_lshr_b32 s43, s3, 16
; GFX11-NEXT:    s_lshr_b32 s44, s2, 16
; GFX11-NEXT:    s_lshr_b32 s47, s1, 16
; GFX11-NEXT:    s_lshr_b32 s57, s0, 16
; GFX11-NEXT:    s_lshr_b32 s58, s45, 16
; GFX11-NEXT:    s_lshr_b32 s59, s46, 16
; GFX11-NEXT:    s_mov_b32 s40, 0
; GFX11-NEXT:    s_cmp_lg_u32 s56, 0
; GFX11-NEXT:    s_pack_ll_b32_b16 s0, s0, s57
; GFX11-NEXT:    s_pack_ll_b32_b16 s1, s1, s47
; GFX11-NEXT:    s_pack_ll_b32_b16 s2, s2, s44
; GFX11-NEXT:    s_pack_ll_b32_b16 s3, s3, s43
; GFX11-NEXT:    s_pack_ll_b32_b16 s4, s16, s4
; GFX11-NEXT:    s_pack_ll_b32_b16 s5, s17, s5
; GFX11-NEXT:    s_pack_ll_b32_b16 s6, s18, s6
; GFX11-NEXT:    s_pack_ll_b32_b16 s7, s19, s7
; GFX11-NEXT:    s_pack_ll_b32_b16 s8, s20, s8
; GFX11-NEXT:    s_pack_ll_b32_b16 s9, s21, s9
; GFX11-NEXT:    s_pack_ll_b32_b16 s10, s22, s10
; GFX11-NEXT:    s_pack_ll_b32_b16 s11, s23, s11
; GFX11-NEXT:    s_pack_ll_b32_b16 s12, s24, s12
; GFX11-NEXT:    s_pack_ll_b32_b16 s13, s25, s13
; GFX11-NEXT:    s_pack_ll_b32_b16 s14, s26, s14
; GFX11-NEXT:    s_pack_ll_b32_b16 s15, s27, s15
; GFX11-NEXT:    s_pack_ll_b32_b16 s16, s28, s42
; GFX11-NEXT:    s_pack_ll_b32_b16 s17, s29, s41
; GFX11-NEXT:    s_pack_ll_b32_b16 s18, s46, s59
; GFX11-NEXT:    s_pack_ll_b32_b16 s19, s45, s58
; GFX11-NEXT:    s_cbranch_scc0 .LBB19_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s40
; GFX11-NEXT:    s_cbranch_vccnz .LBB19_4
; GFX11-NEXT:  .LBB19_2: ; %cmp.true
; GFX11-NEXT:    v_pk_add_f16 v0, 0x200, s0 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v1, 0x200, s1 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v2, 0x200, s2 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v3, 0x200, s3 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v4, 0x200, s4 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v5, 0x200, s5 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v6, 0x200, s6 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v7, 0x200, s7 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v8, 0x200, s8 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v9, 0x200, s9 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v10, 0x200, s10 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v11, 0x200, s11 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v12, 0x200, s12 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v13, 0x200, s13 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v14, 0x200, s14 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v15, 0x200, s15 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v16, 0x200, s16 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v17, 0x200, s17 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v18, 0x200, s18 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v19, 0x200, s19 op_sel_hi:[0,1]
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB19_3:
; GFX11-NEXT:    s_branch .LBB19_2
; GFX11-NEXT:  .LBB19_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    v_dual_mov_b32 v8, s8 :: v_dual_mov_b32 v9, s9
; GFX11-NEXT:    v_dual_mov_b32 v10, s10 :: v_dual_mov_b32 v11, s11
; GFX11-NEXT:    v_dual_mov_b32 v12, s12 :: v_dual_mov_b32 v13, s13
; GFX11-NEXT:    v_dual_mov_b32 v14, s14 :: v_dual_mov_b32 v15, s15
; GFX11-NEXT:    v_dual_mov_b32 v16, s16 :: v_dual_mov_b32 v17, s17
; GFX11-NEXT:    v_dual_mov_b32 v18, s18 :: v_dual_mov_b32 v19, s19
; GFX11-NEXT:    v_dual_mov_b32 v20, s20 :: v_dual_mov_b32 v21, s21
; GFX11-NEXT:    v_dual_mov_b32 v22, s22 :: v_dual_mov_b32 v23, s23
; GFX11-NEXT:    v_dual_mov_b32 v24, s24 :: v_dual_mov_b32 v25, s25
; GFX11-NEXT:    v_dual_mov_b32 v26, s26 :: v_dual_mov_b32 v27, s27
; GFX11-NEXT:    v_dual_mov_b32 v28, s28 :: v_dual_mov_b32 v29, s29
; GFX11-NEXT:    v_dual_mov_b32 v30, s30 :: v_dual_mov_b32 v31, s31
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <40 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <40 x half> %a1 to <20 x i32>
  br label %end

cmp.false:
  %a3 = bitcast <40 x half> %a to <20 x i32>
  br label %end

end:
  %phi = phi <20 x i32> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <20 x i32> %phi
}

define <10 x i64> @bitcast_v20f32_to_v10i64(<20 x float> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v20f32_to_v10i64:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB20_2
; SI-NEXT:  ; %bb.1: ; %cmp.true
; SI-NEXT:    v_add_f32_e32 v19, 1.0, v19
; SI-NEXT:    v_add_f32_e32 v18, 1.0, v18
; SI-NEXT:    v_add_f32_e32 v17, 1.0, v17
; SI-NEXT:    v_add_f32_e32 v16, 1.0, v16
; SI-NEXT:    v_add_f32_e32 v15, 1.0, v15
; SI-NEXT:    v_add_f32_e32 v14, 1.0, v14
; SI-NEXT:    v_add_f32_e32 v13, 1.0, v13
; SI-NEXT:    v_add_f32_e32 v12, 1.0, v12
; SI-NEXT:    v_add_f32_e32 v11, 1.0, v11
; SI-NEXT:    v_add_f32_e32 v10, 1.0, v10
; SI-NEXT:    v_add_f32_e32 v9, 1.0, v9
; SI-NEXT:    v_add_f32_e32 v8, 1.0, v8
; SI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; SI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; SI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; SI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; SI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; SI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; SI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; SI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:  .LBB20_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v20f32_to_v10i64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB20_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f32_e32 v19, 1.0, v19
; VI-NEXT:    v_add_f32_e32 v18, 1.0, v18
; VI-NEXT:    v_add_f32_e32 v17, 1.0, v17
; VI-NEXT:    v_add_f32_e32 v16, 1.0, v16
; VI-NEXT:    v_add_f32_e32 v15, 1.0, v15
; VI-NEXT:    v_add_f32_e32 v14, 1.0, v14
; VI-NEXT:    v_add_f32_e32 v13, 1.0, v13
; VI-NEXT:    v_add_f32_e32 v12, 1.0, v12
; VI-NEXT:    v_add_f32_e32 v11, 1.0, v11
; VI-NEXT:    v_add_f32_e32 v10, 1.0, v10
; VI-NEXT:    v_add_f32_e32 v9, 1.0, v9
; VI-NEXT:    v_add_f32_e32 v8, 1.0, v8
; VI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; VI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; VI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; VI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; VI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; VI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; VI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; VI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:  .LBB20_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v20f32_to_v10i64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB20_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e32 v19, 1.0, v19
; GFX9-NEXT:    v_add_f32_e32 v18, 1.0, v18
; GFX9-NEXT:    v_add_f32_e32 v17, 1.0, v17
; GFX9-NEXT:    v_add_f32_e32 v16, 1.0, v16
; GFX9-NEXT:    v_add_f32_e32 v15, 1.0, v15
; GFX9-NEXT:    v_add_f32_e32 v14, 1.0, v14
; GFX9-NEXT:    v_add_f32_e32 v13, 1.0, v13
; GFX9-NEXT:    v_add_f32_e32 v12, 1.0, v12
; GFX9-NEXT:    v_add_f32_e32 v11, 1.0, v11
; GFX9-NEXT:    v_add_f32_e32 v10, 1.0, v10
; GFX9-NEXT:    v_add_f32_e32 v9, 1.0, v9
; GFX9-NEXT:    v_add_f32_e32 v8, 1.0, v8
; GFX9-NEXT:    v_add_f32_e32 v7, 1.0, v7
; GFX9-NEXT:    v_add_f32_e32 v6, 1.0, v6
; GFX9-NEXT:    v_add_f32_e32 v5, 1.0, v5
; GFX9-NEXT:    v_add_f32_e32 v4, 1.0, v4
; GFX9-NEXT:    v_add_f32_e32 v3, 1.0, v3
; GFX9-NEXT:    v_add_f32_e32 v2, 1.0, v2
; GFX9-NEXT:    v_add_f32_e32 v1, 1.0, v1
; GFX9-NEXT:    v_add_f32_e32 v0, 1.0, v0
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:  .LBB20_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v20f32_to_v10i64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB20_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_dual_add_f32 v19, 1.0, v19 :: v_dual_add_f32 v18, 1.0, v18
; GFX11-NEXT:    v_dual_add_f32 v17, 1.0, v17 :: v_dual_add_f32 v16, 1.0, v16
; GFX11-NEXT:    v_dual_add_f32 v15, 1.0, v15 :: v_dual_add_f32 v14, 1.0, v14
; GFX11-NEXT:    v_dual_add_f32 v13, 1.0, v13 :: v_dual_add_f32 v12, 1.0, v12
; GFX11-NEXT:    v_dual_add_f32 v11, 1.0, v11 :: v_dual_add_f32 v10, 1.0, v10
; GFX11-NEXT:    v_dual_add_f32 v9, 1.0, v9 :: v_dual_add_f32 v8, 1.0, v8
; GFX11-NEXT:    v_dual_add_f32 v7, 1.0, v7 :: v_dual_add_f32 v6, 1.0, v6
; GFX11-NEXT:    v_dual_add_f32 v5, 1.0, v5 :: v_dual_add_f32 v4, 1.0, v4
; GFX11-NEXT:    v_dual_add_f32 v3, 1.0, v3 :: v_dual_add_f32 v2, 1.0, v2
; GFX11-NEXT:    v_dual_add_f32 v1, 1.0, v1 :: v_dual_add_f32 v0, 1.0, v0
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:  .LBB20_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <20 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <20 x float> %a1 to <10 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <20 x float> %a to <10 x i64>
  br label %end

end:
  %phi = phi <10 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <10 x i64> %phi
}

define inreg <10 x i64> @bitcast_v20f32_to_v10i64_scalar(<20 x float> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v20f32_to_v10i64_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_writelane_b32 v32, s36, 0
; SI-NEXT:    v_writelane_b32 v32, s37, 1
; SI-NEXT:    v_writelane_b32 v32, s38, 2
; SI-NEXT:    v_writelane_b32 v32, s39, 3
; SI-NEXT:    v_writelane_b32 v32, s48, 4
; SI-NEXT:    v_writelane_b32 v32, s49, 5
; SI-NEXT:    v_writelane_b32 v32, s50, 6
; SI-NEXT:    v_writelane_b32 v32, s51, 7
; SI-NEXT:    v_writelane_b32 v32, s52, 8
; SI-NEXT:    v_writelane_b32 v32, s53, 9
; SI-NEXT:    v_writelane_b32 v32, s54, 10
; SI-NEXT:    v_writelane_b32 v32, s55, 11
; SI-NEXT:    v_readfirstlane_b32 s4, v6
; SI-NEXT:    s_mov_b32 s49, s29
; SI-NEXT:    s_mov_b32 s48, s28
; SI-NEXT:    s_mov_b32 s47, s27
; SI-NEXT:    s_mov_b32 s46, s26
; SI-NEXT:    s_mov_b32 s45, s25
; SI-NEXT:    s_mov_b32 s44, s24
; SI-NEXT:    s_mov_b32 s43, s23
; SI-NEXT:    s_mov_b32 s42, s22
; SI-NEXT:    s_mov_b32 s41, s21
; SI-NEXT:    s_mov_b32 s40, s20
; SI-NEXT:    s_mov_b32 s39, s19
; SI-NEXT:    s_mov_b32 s38, s18
; SI-NEXT:    s_mov_b32 s37, s17
; SI-NEXT:    s_mov_b32 s36, s16
; SI-NEXT:    v_readfirstlane_b32 s55, v5
; SI-NEXT:    v_readfirstlane_b32 s54, v4
; SI-NEXT:    v_readfirstlane_b32 s53, v3
; SI-NEXT:    v_readfirstlane_b32 s52, v2
; SI-NEXT:    v_readfirstlane_b32 s51, v1
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    v_readfirstlane_b32 s50, v0
; SI-NEXT:    s_cbranch_scc0 .LBB21_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_cbranch_execnz .LBB21_4
; SI-NEXT:  .LBB21_2: ; %cmp.true
; SI-NEXT:    v_add_f32_e64 v19, s55, 1.0
; SI-NEXT:    v_add_f32_e64 v18, s54, 1.0
; SI-NEXT:    v_add_f32_e64 v17, s53, 1.0
; SI-NEXT:    v_add_f32_e64 v16, s52, 1.0
; SI-NEXT:    v_add_f32_e64 v15, s51, 1.0
; SI-NEXT:    v_add_f32_e64 v14, s50, 1.0
; SI-NEXT:    v_add_f32_e64 v13, s49, 1.0
; SI-NEXT:    v_add_f32_e64 v12, s48, 1.0
; SI-NEXT:    v_add_f32_e64 v11, s47, 1.0
; SI-NEXT:    v_add_f32_e64 v10, s46, 1.0
; SI-NEXT:    v_add_f32_e64 v9, s45, 1.0
; SI-NEXT:    v_add_f32_e64 v8, s44, 1.0
; SI-NEXT:    v_add_f32_e64 v7, s43, 1.0
; SI-NEXT:    v_add_f32_e64 v6, s42, 1.0
; SI-NEXT:    v_add_f32_e64 v5, s41, 1.0
; SI-NEXT:    v_add_f32_e64 v4, s40, 1.0
; SI-NEXT:    v_add_f32_e64 v3, s39, 1.0
; SI-NEXT:    v_add_f32_e64 v2, s38, 1.0
; SI-NEXT:    v_add_f32_e64 v1, s37, 1.0
; SI-NEXT:    v_add_f32_e64 v0, s36, 1.0
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    s_branch .LBB21_5
; SI-NEXT:  .LBB21_3:
; SI-NEXT:    s_branch .LBB21_2
; SI-NEXT:  .LBB21_4:
; SI-NEXT:    v_mov_b32_e32 v0, s36
; SI-NEXT:    v_mov_b32_e32 v1, s37
; SI-NEXT:    v_mov_b32_e32 v2, s38
; SI-NEXT:    v_mov_b32_e32 v3, s39
; SI-NEXT:    v_mov_b32_e32 v4, s40
; SI-NEXT:    v_mov_b32_e32 v5, s41
; SI-NEXT:    v_mov_b32_e32 v6, s42
; SI-NEXT:    v_mov_b32_e32 v7, s43
; SI-NEXT:    v_mov_b32_e32 v8, s44
; SI-NEXT:    v_mov_b32_e32 v9, s45
; SI-NEXT:    v_mov_b32_e32 v10, s46
; SI-NEXT:    v_mov_b32_e32 v11, s47
; SI-NEXT:    v_mov_b32_e32 v12, s48
; SI-NEXT:    v_mov_b32_e32 v13, s49
; SI-NEXT:    v_mov_b32_e32 v14, s50
; SI-NEXT:    v_mov_b32_e32 v15, s51
; SI-NEXT:    v_mov_b32_e32 v16, s52
; SI-NEXT:    v_mov_b32_e32 v17, s53
; SI-NEXT:    v_mov_b32_e32 v18, s54
; SI-NEXT:    v_mov_b32_e32 v19, s55
; SI-NEXT:    v_mov_b32_e32 v20, s56
; SI-NEXT:    v_mov_b32_e32 v21, s57
; SI-NEXT:    v_mov_b32_e32 v22, s58
; SI-NEXT:    v_mov_b32_e32 v23, s59
; SI-NEXT:    v_mov_b32_e32 v24, s60
; SI-NEXT:    v_mov_b32_e32 v25, s61
; SI-NEXT:    v_mov_b32_e32 v26, s62
; SI-NEXT:    v_mov_b32_e32 v27, s63
; SI-NEXT:    v_mov_b32_e32 v28, s64
; SI-NEXT:    v_mov_b32_e32 v29, s65
; SI-NEXT:    v_mov_b32_e32 v30, s66
; SI-NEXT:    v_mov_b32_e32 v31, s67
; SI-NEXT:  .LBB21_5: ; %end
; SI-NEXT:    v_readlane_b32 s55, v32, 11
; SI-NEXT:    v_readlane_b32 s54, v32, 10
; SI-NEXT:    v_readlane_b32 s53, v32, 9
; SI-NEXT:    v_readlane_b32 s52, v32, 8
; SI-NEXT:    v_readlane_b32 s51, v32, 7
; SI-NEXT:    v_readlane_b32 s50, v32, 6
; SI-NEXT:    v_readlane_b32 s49, v32, 5
; SI-NEXT:    v_readlane_b32 s48, v32, 4
; SI-NEXT:    v_readlane_b32 s39, v32, 3
; SI-NEXT:    v_readlane_b32 s38, v32, 2
; SI-NEXT:    v_readlane_b32 s37, v32, 1
; SI-NEXT:    v_readlane_b32 s36, v32, 0
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v20f32_to_v10i64_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    v_writelane_b32 v32, s36, 0
; VI-NEXT:    v_writelane_b32 v32, s37, 1
; VI-NEXT:    v_writelane_b32 v32, s38, 2
; VI-NEXT:    v_writelane_b32 v32, s39, 3
; VI-NEXT:    v_writelane_b32 v32, s48, 4
; VI-NEXT:    v_writelane_b32 v32, s49, 5
; VI-NEXT:    v_writelane_b32 v32, s50, 6
; VI-NEXT:    v_writelane_b32 v32, s51, 7
; VI-NEXT:    v_writelane_b32 v32, s52, 8
; VI-NEXT:    v_writelane_b32 v32, s53, 9
; VI-NEXT:    v_writelane_b32 v32, s54, 10
; VI-NEXT:    v_writelane_b32 v32, s55, 11
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    s_mov_b32 s49, s29
; VI-NEXT:    s_mov_b32 s48, s28
; VI-NEXT:    s_mov_b32 s47, s27
; VI-NEXT:    s_mov_b32 s46, s26
; VI-NEXT:    s_mov_b32 s45, s25
; VI-NEXT:    s_mov_b32 s44, s24
; VI-NEXT:    s_mov_b32 s43, s23
; VI-NEXT:    s_mov_b32 s42, s22
; VI-NEXT:    s_mov_b32 s41, s21
; VI-NEXT:    s_mov_b32 s40, s20
; VI-NEXT:    s_mov_b32 s39, s19
; VI-NEXT:    s_mov_b32 s38, s18
; VI-NEXT:    s_mov_b32 s37, s17
; VI-NEXT:    s_mov_b32 s36, s16
; VI-NEXT:    v_readfirstlane_b32 s55, v5
; VI-NEXT:    v_readfirstlane_b32 s54, v4
; VI-NEXT:    v_readfirstlane_b32 s53, v3
; VI-NEXT:    v_readfirstlane_b32 s52, v2
; VI-NEXT:    v_readfirstlane_b32 s51, v1
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    v_readfirstlane_b32 s50, v0
; VI-NEXT:    s_cbranch_scc0 .LBB21_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB21_4
; VI-NEXT:  .LBB21_2: ; %cmp.true
; VI-NEXT:    v_add_f32_e64 v19, s55, 1.0
; VI-NEXT:    v_add_f32_e64 v18, s54, 1.0
; VI-NEXT:    v_add_f32_e64 v17, s53, 1.0
; VI-NEXT:    v_add_f32_e64 v16, s52, 1.0
; VI-NEXT:    v_add_f32_e64 v15, s51, 1.0
; VI-NEXT:    v_add_f32_e64 v14, s50, 1.0
; VI-NEXT:    v_add_f32_e64 v13, s49, 1.0
; VI-NEXT:    v_add_f32_e64 v12, s48, 1.0
; VI-NEXT:    v_add_f32_e64 v11, s47, 1.0
; VI-NEXT:    v_add_f32_e64 v10, s46, 1.0
; VI-NEXT:    v_add_f32_e64 v9, s45, 1.0
; VI-NEXT:    v_add_f32_e64 v8, s44, 1.0
; VI-NEXT:    v_add_f32_e64 v7, s43, 1.0
; VI-NEXT:    v_add_f32_e64 v6, s42, 1.0
; VI-NEXT:    v_add_f32_e64 v5, s41, 1.0
; VI-NEXT:    v_add_f32_e64 v4, s40, 1.0
; VI-NEXT:    v_add_f32_e64 v3, s39, 1.0
; VI-NEXT:    v_add_f32_e64 v2, s38, 1.0
; VI-NEXT:    v_add_f32_e64 v1, s37, 1.0
; VI-NEXT:    v_add_f32_e64 v0, s36, 1.0
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    s_branch .LBB21_5
; VI-NEXT:  .LBB21_3:
; VI-NEXT:    s_branch .LBB21_2
; VI-NEXT:  .LBB21_4:
; VI-NEXT:    v_mov_b32_e32 v0, s36
; VI-NEXT:    v_mov_b32_e32 v1, s37
; VI-NEXT:    v_mov_b32_e32 v2, s38
; VI-NEXT:    v_mov_b32_e32 v3, s39
; VI-NEXT:    v_mov_b32_e32 v4, s40
; VI-NEXT:    v_mov_b32_e32 v5, s41
; VI-NEXT:    v_mov_b32_e32 v6, s42
; VI-NEXT:    v_mov_b32_e32 v7, s43
; VI-NEXT:    v_mov_b32_e32 v8, s44
; VI-NEXT:    v_mov_b32_e32 v9, s45
; VI-NEXT:    v_mov_b32_e32 v10, s46
; VI-NEXT:    v_mov_b32_e32 v11, s47
; VI-NEXT:    v_mov_b32_e32 v12, s48
; VI-NEXT:    v_mov_b32_e32 v13, s49
; VI-NEXT:    v_mov_b32_e32 v14, s50
; VI-NEXT:    v_mov_b32_e32 v15, s51
; VI-NEXT:    v_mov_b32_e32 v16, s52
; VI-NEXT:    v_mov_b32_e32 v17, s53
; VI-NEXT:    v_mov_b32_e32 v18, s54
; VI-NEXT:    v_mov_b32_e32 v19, s55
; VI-NEXT:    v_mov_b32_e32 v20, s56
; VI-NEXT:    v_mov_b32_e32 v21, s57
; VI-NEXT:    v_mov_b32_e32 v22, s58
; VI-NEXT:    v_mov_b32_e32 v23, s59
; VI-NEXT:    v_mov_b32_e32 v24, s60
; VI-NEXT:    v_mov_b32_e32 v25, s61
; VI-NEXT:    v_mov_b32_e32 v26, s62
; VI-NEXT:    v_mov_b32_e32 v27, s63
; VI-NEXT:    v_mov_b32_e32 v28, s64
; VI-NEXT:    v_mov_b32_e32 v29, s65
; VI-NEXT:    v_mov_b32_e32 v30, s66
; VI-NEXT:    v_mov_b32_e32 v31, s67
; VI-NEXT:  .LBB21_5: ; %end
; VI-NEXT:    v_readlane_b32 s55, v32, 11
; VI-NEXT:    v_readlane_b32 s54, v32, 10
; VI-NEXT:    v_readlane_b32 s53, v32, 9
; VI-NEXT:    v_readlane_b32 s52, v32, 8
; VI-NEXT:    v_readlane_b32 s51, v32, 7
; VI-NEXT:    v_readlane_b32 s50, v32, 6
; VI-NEXT:    v_readlane_b32 s49, v32, 5
; VI-NEXT:    v_readlane_b32 s48, v32, 4
; VI-NEXT:    v_readlane_b32 s39, v32, 3
; VI-NEXT:    v_readlane_b32 s38, v32, 2
; VI-NEXT:    v_readlane_b32 s37, v32, 1
; VI-NEXT:    v_readlane_b32 s36, v32, 0
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v20f32_to_v10i64_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    v_writelane_b32 v32, s36, 0
; GFX9-NEXT:    v_writelane_b32 v32, s37, 1
; GFX9-NEXT:    v_writelane_b32 v32, s38, 2
; GFX9-NEXT:    v_writelane_b32 v32, s39, 3
; GFX9-NEXT:    v_writelane_b32 v32, s48, 4
; GFX9-NEXT:    v_writelane_b32 v32, s49, 5
; GFX9-NEXT:    v_writelane_b32 v32, s50, 6
; GFX9-NEXT:    v_writelane_b32 v32, s51, 7
; GFX9-NEXT:    v_writelane_b32 v32, s52, 8
; GFX9-NEXT:    v_writelane_b32 v32, s53, 9
; GFX9-NEXT:    v_writelane_b32 v32, s54, 10
; GFX9-NEXT:    v_writelane_b32 v32, s55, 11
; GFX9-NEXT:    v_readfirstlane_b32 s4, v6
; GFX9-NEXT:    s_mov_b32 s49, s29
; GFX9-NEXT:    s_mov_b32 s48, s28
; GFX9-NEXT:    s_mov_b32 s47, s27
; GFX9-NEXT:    s_mov_b32 s46, s26
; GFX9-NEXT:    s_mov_b32 s45, s25
; GFX9-NEXT:    s_mov_b32 s44, s24
; GFX9-NEXT:    s_mov_b32 s43, s23
; GFX9-NEXT:    s_mov_b32 s42, s22
; GFX9-NEXT:    s_mov_b32 s41, s21
; GFX9-NEXT:    s_mov_b32 s40, s20
; GFX9-NEXT:    s_mov_b32 s39, s19
; GFX9-NEXT:    s_mov_b32 s38, s18
; GFX9-NEXT:    s_mov_b32 s37, s17
; GFX9-NEXT:    s_mov_b32 s36, s16
; GFX9-NEXT:    v_readfirstlane_b32 s55, v5
; GFX9-NEXT:    v_readfirstlane_b32 s54, v4
; GFX9-NEXT:    v_readfirstlane_b32 s53, v3
; GFX9-NEXT:    v_readfirstlane_b32 s52, v2
; GFX9-NEXT:    v_readfirstlane_b32 s51, v1
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    v_readfirstlane_b32 s50, v0
; GFX9-NEXT:    s_cbranch_scc0 .LBB21_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB21_4
; GFX9-NEXT:  .LBB21_2: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e64 v19, s55, 1.0
; GFX9-NEXT:    v_add_f32_e64 v18, s54, 1.0
; GFX9-NEXT:    v_add_f32_e64 v17, s53, 1.0
; GFX9-NEXT:    v_add_f32_e64 v16, s52, 1.0
; GFX9-NEXT:    v_add_f32_e64 v15, s51, 1.0
; GFX9-NEXT:    v_add_f32_e64 v14, s50, 1.0
; GFX9-NEXT:    v_add_f32_e64 v13, s49, 1.0
; GFX9-NEXT:    v_add_f32_e64 v12, s48, 1.0
; GFX9-NEXT:    v_add_f32_e64 v11, s47, 1.0
; GFX9-NEXT:    v_add_f32_e64 v10, s46, 1.0
; GFX9-NEXT:    v_add_f32_e64 v9, s45, 1.0
; GFX9-NEXT:    v_add_f32_e64 v8, s44, 1.0
; GFX9-NEXT:    v_add_f32_e64 v7, s43, 1.0
; GFX9-NEXT:    v_add_f32_e64 v6, s42, 1.0
; GFX9-NEXT:    v_add_f32_e64 v5, s41, 1.0
; GFX9-NEXT:    v_add_f32_e64 v4, s40, 1.0
; GFX9-NEXT:    v_add_f32_e64 v3, s39, 1.0
; GFX9-NEXT:    v_add_f32_e64 v2, s38, 1.0
; GFX9-NEXT:    v_add_f32_e64 v1, s37, 1.0
; GFX9-NEXT:    v_add_f32_e64 v0, s36, 1.0
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_branch .LBB21_5
; GFX9-NEXT:  .LBB21_3:
; GFX9-NEXT:    s_branch .LBB21_2
; GFX9-NEXT:  .LBB21_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s36
; GFX9-NEXT:    v_mov_b32_e32 v1, s37
; GFX9-NEXT:    v_mov_b32_e32 v2, s38
; GFX9-NEXT:    v_mov_b32_e32 v3, s39
; GFX9-NEXT:    v_mov_b32_e32 v4, s40
; GFX9-NEXT:    v_mov_b32_e32 v5, s41
; GFX9-NEXT:    v_mov_b32_e32 v6, s42
; GFX9-NEXT:    v_mov_b32_e32 v7, s43
; GFX9-NEXT:    v_mov_b32_e32 v8, s44
; GFX9-NEXT:    v_mov_b32_e32 v9, s45
; GFX9-NEXT:    v_mov_b32_e32 v10, s46
; GFX9-NEXT:    v_mov_b32_e32 v11, s47
; GFX9-NEXT:    v_mov_b32_e32 v12, s48
; GFX9-NEXT:    v_mov_b32_e32 v13, s49
; GFX9-NEXT:    v_mov_b32_e32 v14, s50
; GFX9-NEXT:    v_mov_b32_e32 v15, s51
; GFX9-NEXT:    v_mov_b32_e32 v16, s52
; GFX9-NEXT:    v_mov_b32_e32 v17, s53
; GFX9-NEXT:    v_mov_b32_e32 v18, s54
; GFX9-NEXT:    v_mov_b32_e32 v19, s55
; GFX9-NEXT:    v_mov_b32_e32 v20, s56
; GFX9-NEXT:    v_mov_b32_e32 v21, s57
; GFX9-NEXT:    v_mov_b32_e32 v22, s58
; GFX9-NEXT:    v_mov_b32_e32 v23, s59
; GFX9-NEXT:    v_mov_b32_e32 v24, s60
; GFX9-NEXT:    v_mov_b32_e32 v25, s61
; GFX9-NEXT:    v_mov_b32_e32 v26, s62
; GFX9-NEXT:    v_mov_b32_e32 v27, s63
; GFX9-NEXT:    v_mov_b32_e32 v28, s64
; GFX9-NEXT:    v_mov_b32_e32 v29, s65
; GFX9-NEXT:    v_mov_b32_e32 v30, s66
; GFX9-NEXT:    v_mov_b32_e32 v31, s67
; GFX9-NEXT:  .LBB21_5: ; %end
; GFX9-NEXT:    v_readlane_b32 s55, v32, 11
; GFX9-NEXT:    v_readlane_b32 s54, v32, 10
; GFX9-NEXT:    v_readlane_b32 s53, v32, 9
; GFX9-NEXT:    v_readlane_b32 s52, v32, 8
; GFX9-NEXT:    v_readlane_b32 s51, v32, 7
; GFX9-NEXT:    v_readlane_b32 s50, v32, 6
; GFX9-NEXT:    v_readlane_b32 s49, v32, 5
; GFX9-NEXT:    v_readlane_b32 s48, v32, 4
; GFX9-NEXT:    v_readlane_b32 s39, v32, 3
; GFX9-NEXT:    v_readlane_b32 s38, v32, 2
; GFX9-NEXT:    v_readlane_b32 s37, v32, 1
; GFX9-NEXT:    v_readlane_b32 s36, v32, 0
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v20f32_to_v10i64_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_xor_saveexec_b32 s4, -1
; GFX11-NEXT:    scratch_store_b32 off, v32, s32 ; 4-byte Folded Spill
; GFX11-NEXT:    s_mov_b32 exec_lo, s4
; GFX11-NEXT:    v_writelane_b32 v32, s36, 0
; GFX11-NEXT:    v_writelane_b32 v32, s37, 1
; GFX11-NEXT:    v_writelane_b32 v32, s38, 2
; GFX11-NEXT:    v_writelane_b32 v32, s39, 3
; GFX11-NEXT:    v_writelane_b32 v32, s48, 4
; GFX11-NEXT:    v_writelane_b32 v32, s49, 5
; GFX11-NEXT:    v_writelane_b32 v32, s50, 6
; GFX11-NEXT:    v_writelane_b32 v32, s51, 7
; GFX11-NEXT:    v_writelane_b32 v32, s52, 8
; GFX11-NEXT:    v_writelane_b32 v32, s53, 9
; GFX11-NEXT:    v_writelane_b32 v32, s54, 10
; GFX11-NEXT:    v_writelane_b32 v32, s55, 11
; GFX11-NEXT:    s_mov_b32 s36, s0
; GFX11-NEXT:    v_readfirstlane_b32 s0, v2
; GFX11-NEXT:    v_readfirstlane_b32 s55, v1
; GFX11-NEXT:    v_readfirstlane_b32 s54, v0
; GFX11-NEXT:    s_mov_b32 s53, s29
; GFX11-NEXT:    s_mov_b32 s52, s28
; GFX11-NEXT:    s_mov_b32 s51, s27
; GFX11-NEXT:    s_mov_b32 s50, s26
; GFX11-NEXT:    s_mov_b32 s49, s25
; GFX11-NEXT:    s_mov_b32 s48, s24
; GFX11-NEXT:    s_mov_b32 s47, s23
; GFX11-NEXT:    s_mov_b32 s46, s22
; GFX11-NEXT:    s_mov_b32 s45, s21
; GFX11-NEXT:    s_mov_b32 s44, s20
; GFX11-NEXT:    s_mov_b32 s43, s19
; GFX11-NEXT:    s_mov_b32 s42, s18
; GFX11-NEXT:    s_mov_b32 s41, s17
; GFX11-NEXT:    s_mov_b32 s40, s16
; GFX11-NEXT:    s_mov_b32 s39, s3
; GFX11-NEXT:    s_mov_b32 s38, s2
; GFX11-NEXT:    s_mov_b32 s37, s1
; GFX11-NEXT:    s_cmp_lg_u32 s0, 0
; GFX11-NEXT:    s_mov_b32 s0, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB21_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s0
; GFX11-NEXT:    s_cbranch_vccnz .LBB21_4
; GFX11-NEXT:  .LBB21_2: ; %cmp.true
; GFX11-NEXT:    v_add_f32_e64 v19, s55, 1.0
; GFX11-NEXT:    v_add_f32_e64 v18, s54, 1.0
; GFX11-NEXT:    v_add_f32_e64 v17, s53, 1.0
; GFX11-NEXT:    v_add_f32_e64 v16, s52, 1.0
; GFX11-NEXT:    v_add_f32_e64 v15, s51, 1.0
; GFX11-NEXT:    v_add_f32_e64 v14, s50, 1.0
; GFX11-NEXT:    v_add_f32_e64 v13, s49, 1.0
; GFX11-NEXT:    v_add_f32_e64 v12, s48, 1.0
; GFX11-NEXT:    v_add_f32_e64 v11, s47, 1.0
; GFX11-NEXT:    v_add_f32_e64 v10, s46, 1.0
; GFX11-NEXT:    v_add_f32_e64 v9, s45, 1.0
; GFX11-NEXT:    v_add_f32_e64 v8, s44, 1.0
; GFX11-NEXT:    v_add_f32_e64 v7, s43, 1.0
; GFX11-NEXT:    v_add_f32_e64 v6, s42, 1.0
; GFX11-NEXT:    v_add_f32_e64 v5, s41, 1.0
; GFX11-NEXT:    v_add_f32_e64 v4, s40, 1.0
; GFX11-NEXT:    v_add_f32_e64 v3, s39, 1.0
; GFX11-NEXT:    v_add_f32_e64 v2, s38, 1.0
; GFX11-NEXT:    v_add_f32_e64 v1, s37, 1.0
; GFX11-NEXT:    v_add_f32_e64 v0, s36, 1.0
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    s_branch .LBB21_5
; GFX11-NEXT:  .LBB21_3:
; GFX11-NEXT:    s_branch .LBB21_2
; GFX11-NEXT:  .LBB21_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s36 :: v_dual_mov_b32 v1, s37
; GFX11-NEXT:    v_dual_mov_b32 v2, s38 :: v_dual_mov_b32 v3, s39
; GFX11-NEXT:    v_dual_mov_b32 v4, s40 :: v_dual_mov_b32 v5, s41
; GFX11-NEXT:    v_dual_mov_b32 v6, s42 :: v_dual_mov_b32 v7, s43
; GFX11-NEXT:    v_dual_mov_b32 v8, s44 :: v_dual_mov_b32 v9, s45
; GFX11-NEXT:    v_dual_mov_b32 v10, s46 :: v_dual_mov_b32 v11, s47
; GFX11-NEXT:    v_dual_mov_b32 v12, s48 :: v_dual_mov_b32 v13, s49
; GFX11-NEXT:    v_dual_mov_b32 v14, s50 :: v_dual_mov_b32 v15, s51
; GFX11-NEXT:    v_dual_mov_b32 v16, s52 :: v_dual_mov_b32 v17, s53
; GFX11-NEXT:    v_dual_mov_b32 v18, s54 :: v_dual_mov_b32 v19, s55
; GFX11-NEXT:    v_dual_mov_b32 v20, s56 :: v_dual_mov_b32 v21, s57
; GFX11-NEXT:    v_dual_mov_b32 v22, s58 :: v_dual_mov_b32 v23, s59
; GFX11-NEXT:    v_dual_mov_b32 v24, s60 :: v_dual_mov_b32 v25, s61
; GFX11-NEXT:    v_dual_mov_b32 v26, s62 :: v_dual_mov_b32 v27, s63
; GFX11-NEXT:    v_dual_mov_b32 v28, s64 :: v_dual_mov_b32 v29, s65
; GFX11-NEXT:    v_dual_mov_b32 v30, s66 :: v_dual_mov_b32 v31, s67
; GFX11-NEXT:  .LBB21_5: ; %end
; GFX11-NEXT:    v_readlane_b32 s55, v32, 11
; GFX11-NEXT:    v_readlane_b32 s54, v32, 10
; GFX11-NEXT:    v_readlane_b32 s53, v32, 9
; GFX11-NEXT:    v_readlane_b32 s52, v32, 8
; GFX11-NEXT:    v_readlane_b32 s51, v32, 7
; GFX11-NEXT:    v_readlane_b32 s50, v32, 6
; GFX11-NEXT:    v_readlane_b32 s49, v32, 5
; GFX11-NEXT:    v_readlane_b32 s48, v32, 4
; GFX11-NEXT:    v_readlane_b32 s39, v32, 3
; GFX11-NEXT:    v_readlane_b32 s38, v32, 2
; GFX11-NEXT:    v_readlane_b32 s37, v32, 1
; GFX11-NEXT:    v_readlane_b32 s36, v32, 0
; GFX11-NEXT:    s_xor_saveexec_b32 s0, -1
; GFX11-NEXT:    scratch_load_b32 v32, off, s32 ; 4-byte Folded Reload
; GFX11-NEXT:    s_mov_b32 exec_lo, s0
; GFX11-NEXT:    s_waitcnt vmcnt(0)
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <20 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <20 x float> %a1 to <10 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <20 x float> %a to <10 x i64>
  br label %end

end:
  %phi = phi <10 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <10 x i64> %phi
}

define <20 x float> @bitcast_v10i64_to_v20f32(<10 x i64> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v10i64_to_v20f32:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB22_2
; SI-NEXT:  ; %bb.1: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v18, vcc, 3, v18
; SI-NEXT:    v_addc_u32_e32 v19, vcc, 0, v19, vcc
; SI-NEXT:    v_add_i32_e32 v16, vcc, 3, v16
; SI-NEXT:    v_addc_u32_e32 v17, vcc, 0, v17, vcc
; SI-NEXT:    v_add_i32_e32 v14, vcc, 3, v14
; SI-NEXT:    v_addc_u32_e32 v15, vcc, 0, v15, vcc
; SI-NEXT:    v_add_i32_e32 v12, vcc, 3, v12
; SI-NEXT:    v_addc_u32_e32 v13, vcc, 0, v13, vcc
; SI-NEXT:    v_add_i32_e32 v10, vcc, 3, v10
; SI-NEXT:    v_addc_u32_e32 v11, vcc, 0, v11, vcc
; SI-NEXT:    v_add_i32_e32 v8, vcc, 3, v8
; SI-NEXT:    v_addc_u32_e32 v9, vcc, 0, v9, vcc
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; SI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; SI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; SI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:  .LBB22_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v10i64_to_v20f32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB22_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v18, vcc, 3, v18
; VI-NEXT:    v_addc_u32_e32 v19, vcc, 0, v19, vcc
; VI-NEXT:    v_add_u32_e32 v16, vcc, 3, v16
; VI-NEXT:    v_addc_u32_e32 v17, vcc, 0, v17, vcc
; VI-NEXT:    v_add_u32_e32 v14, vcc, 3, v14
; VI-NEXT:    v_addc_u32_e32 v15, vcc, 0, v15, vcc
; VI-NEXT:    v_add_u32_e32 v12, vcc, 3, v12
; VI-NEXT:    v_addc_u32_e32 v13, vcc, 0, v13, vcc
; VI-NEXT:    v_add_u32_e32 v10, vcc, 3, v10
; VI-NEXT:    v_addc_u32_e32 v11, vcc, 0, v11, vcc
; VI-NEXT:    v_add_u32_e32 v8, vcc, 3, v8
; VI-NEXT:    v_addc_u32_e32 v9, vcc, 0, v9, vcc
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:  .LBB22_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v10i64_to_v20f32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB22_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_co_u32_e32 v18, vcc, 3, v18
; GFX9-NEXT:    v_addc_co_u32_e32 v19, vcc, 0, v19, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v16, vcc, 3, v16
; GFX9-NEXT:    v_addc_co_u32_e32 v17, vcc, 0, v17, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v14, vcc, 3, v14
; GFX9-NEXT:    v_addc_co_u32_e32 v15, vcc, 0, v15, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v12, vcc, 3, v12
; GFX9-NEXT:    v_addc_co_u32_e32 v13, vcc, 0, v13, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v10, vcc, 3, v10
; GFX9-NEXT:    v_addc_co_u32_e32 v11, vcc, 0, v11, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v8, vcc, 3, v8
; GFX9-NEXT:    v_addc_co_u32_e32 v9, vcc, 0, v9, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v6, vcc, 3, v6
; GFX9-NEXT:    v_addc_co_u32_e32 v7, vcc, 0, v7, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v4, vcc, 3, v4
; GFX9-NEXT:    v_addc_co_u32_e32 v5, vcc, 0, v5, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v2, vcc, 3, v2
; GFX9-NEXT:    v_addc_co_u32_e32 v3, vcc, 0, v3, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v0, vcc, 3, v0
; GFX9-NEXT:    v_addc_co_u32_e32 v1, vcc, 0, v1, vcc
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:  .LBB22_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v10i64_to_v20f32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB22_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_co_u32 v18, vcc_lo, v18, 3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_co_ci_u32_e64 v19, null, 0, v19, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v16, vcc_lo, v16, 3
; GFX11-NEXT:    v_add_co_ci_u32_e64 v17, null, 0, v17, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v14, vcc_lo, v14, 3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_co_ci_u32_e64 v15, null, 0, v15, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v12, vcc_lo, v12, 3
; GFX11-NEXT:    v_add_co_ci_u32_e64 v13, null, 0, v13, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v10, vcc_lo, v10, 3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_co_ci_u32_e64 v11, null, 0, v11, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v8, vcc_lo, v8, 3
; GFX11-NEXT:    v_add_co_ci_u32_e64 v9, null, 0, v9, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v6, vcc_lo, v6, 3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_co_ci_u32_e64 v7, null, 0, v7, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v4, vcc_lo, v4, 3
; GFX11-NEXT:    v_add_co_ci_u32_e64 v5, null, 0, v5, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v2, vcc_lo, v2, 3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_co_ci_u32_e64 v3, null, 0, v3, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v0, vcc_lo, v0, 3
; GFX11-NEXT:    v_add_co_ci_u32_e64 v1, null, 0, v1, vcc_lo
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:  .LBB22_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <10 x i64> %a, splat (i64 3)
  %a2 = bitcast <10 x i64> %a1 to <20 x float>
  br label %end

cmp.false:
  %a3 = bitcast <10 x i64> %a to <20 x float>
  br label %end

end:
  %phi = phi <20 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <20 x float> %phi
}

define inreg <20 x float> @bitcast_v10i64_to_v20f32_scalar(<10 x i64> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v10i64_to_v20f32_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_readfirstlane_b32 s4, v6
; SI-NEXT:    v_readfirstlane_b32 s6, v5
; SI-NEXT:    v_readfirstlane_b32 s7, v4
; SI-NEXT:    v_readfirstlane_b32 s8, v3
; SI-NEXT:    v_readfirstlane_b32 s9, v2
; SI-NEXT:    v_readfirstlane_b32 s10, v1
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    v_readfirstlane_b32 s11, v0
; SI-NEXT:    s_cbranch_scc0 .LBB23_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_cbranch_execnz .LBB23_3
; SI-NEXT:  .LBB23_2: ; %cmp.true
; SI-NEXT:    s_add_u32 s7, s7, 3
; SI-NEXT:    s_addc_u32 s6, s6, 0
; SI-NEXT:    s_add_u32 s9, s9, 3
; SI-NEXT:    s_addc_u32 s8, s8, 0
; SI-NEXT:    s_add_u32 s11, s11, 3
; SI-NEXT:    s_addc_u32 s10, s10, 0
; SI-NEXT:    s_add_u32 s28, s28, 3
; SI-NEXT:    s_addc_u32 s29, s29, 0
; SI-NEXT:    s_add_u32 s26, s26, 3
; SI-NEXT:    s_addc_u32 s27, s27, 0
; SI-NEXT:    s_add_u32 s24, s24, 3
; SI-NEXT:    s_addc_u32 s25, s25, 0
; SI-NEXT:    s_add_u32 s22, s22, 3
; SI-NEXT:    s_addc_u32 s23, s23, 0
; SI-NEXT:    s_add_u32 s20, s20, 3
; SI-NEXT:    s_addc_u32 s21, s21, 0
; SI-NEXT:    s_add_u32 s18, s18, 3
; SI-NEXT:    s_addc_u32 s19, s19, 0
; SI-NEXT:    s_add_u32 s16, s16, 3
; SI-NEXT:    s_addc_u32 s17, s17, 0
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:  .LBB23_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v2, s18
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v4, s20
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v6, s22
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    v_mov_b32_e32 v8, s24
; SI-NEXT:    v_mov_b32_e32 v9, s25
; SI-NEXT:    v_mov_b32_e32 v10, s26
; SI-NEXT:    v_mov_b32_e32 v11, s27
; SI-NEXT:    v_mov_b32_e32 v12, s28
; SI-NEXT:    v_mov_b32_e32 v13, s29
; SI-NEXT:    v_mov_b32_e32 v14, s11
; SI-NEXT:    v_mov_b32_e32 v15, s10
; SI-NEXT:    v_mov_b32_e32 v16, s9
; SI-NEXT:    v_mov_b32_e32 v17, s8
; SI-NEXT:    v_mov_b32_e32 v18, s7
; SI-NEXT:    v_mov_b32_e32 v19, s6
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB23_4:
; SI-NEXT:    s_branch .LBB23_2
;
; VI-LABEL: bitcast_v10i64_to_v20f32_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    v_readfirstlane_b32 s6, v5
; VI-NEXT:    v_readfirstlane_b32 s7, v4
; VI-NEXT:    v_readfirstlane_b32 s8, v3
; VI-NEXT:    v_readfirstlane_b32 s9, v2
; VI-NEXT:    v_readfirstlane_b32 s10, v1
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    v_readfirstlane_b32 s11, v0
; VI-NEXT:    s_cbranch_scc0 .LBB23_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB23_3
; VI-NEXT:  .LBB23_2: ; %cmp.true
; VI-NEXT:    s_add_u32 s7, s7, 3
; VI-NEXT:    s_addc_u32 s6, s6, 0
; VI-NEXT:    s_add_u32 s9, s9, 3
; VI-NEXT:    s_addc_u32 s8, s8, 0
; VI-NEXT:    s_add_u32 s11, s11, 3
; VI-NEXT:    s_addc_u32 s10, s10, 0
; VI-NEXT:    s_add_u32 s28, s28, 3
; VI-NEXT:    s_addc_u32 s29, s29, 0
; VI-NEXT:    s_add_u32 s26, s26, 3
; VI-NEXT:    s_addc_u32 s27, s27, 0
; VI-NEXT:    s_add_u32 s24, s24, 3
; VI-NEXT:    s_addc_u32 s25, s25, 0
; VI-NEXT:    s_add_u32 s22, s22, 3
; VI-NEXT:    s_addc_u32 s23, s23, 0
; VI-NEXT:    s_add_u32 s20, s20, 3
; VI-NEXT:    s_addc_u32 s21, s21, 0
; VI-NEXT:    s_add_u32 s18, s18, 3
; VI-NEXT:    s_addc_u32 s19, s19, 0
; VI-NEXT:    s_add_u32 s16, s16, 3
; VI-NEXT:    s_addc_u32 s17, s17, 0
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:  .LBB23_3: ; %end
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    v_mov_b32_e32 v8, s24
; VI-NEXT:    v_mov_b32_e32 v9, s25
; VI-NEXT:    v_mov_b32_e32 v10, s26
; VI-NEXT:    v_mov_b32_e32 v11, s27
; VI-NEXT:    v_mov_b32_e32 v12, s28
; VI-NEXT:    v_mov_b32_e32 v13, s29
; VI-NEXT:    v_mov_b32_e32 v14, s11
; VI-NEXT:    v_mov_b32_e32 v15, s10
; VI-NEXT:    v_mov_b32_e32 v16, s9
; VI-NEXT:    v_mov_b32_e32 v17, s8
; VI-NEXT:    v_mov_b32_e32 v18, s7
; VI-NEXT:    v_mov_b32_e32 v19, s6
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB23_4:
; VI-NEXT:    s_branch .LBB23_2
;
; GFX9-LABEL: bitcast_v10i64_to_v20f32_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_readfirstlane_b32 s4, v6
; GFX9-NEXT:    v_readfirstlane_b32 s6, v5
; GFX9-NEXT:    v_readfirstlane_b32 s7, v4
; GFX9-NEXT:    v_readfirstlane_b32 s8, v3
; GFX9-NEXT:    v_readfirstlane_b32 s9, v2
; GFX9-NEXT:    v_readfirstlane_b32 s10, v1
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    v_readfirstlane_b32 s11, v0
; GFX9-NEXT:    s_cbranch_scc0 .LBB23_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB23_3
; GFX9-NEXT:  .LBB23_2: ; %cmp.true
; GFX9-NEXT:    s_add_u32 s7, s7, 3
; GFX9-NEXT:    s_addc_u32 s6, s6, 0
; GFX9-NEXT:    s_add_u32 s9, s9, 3
; GFX9-NEXT:    s_addc_u32 s8, s8, 0
; GFX9-NEXT:    s_add_u32 s11, s11, 3
; GFX9-NEXT:    s_addc_u32 s10, s10, 0
; GFX9-NEXT:    s_add_u32 s28, s28, 3
; GFX9-NEXT:    s_addc_u32 s29, s29, 0
; GFX9-NEXT:    s_add_u32 s26, s26, 3
; GFX9-NEXT:    s_addc_u32 s27, s27, 0
; GFX9-NEXT:    s_add_u32 s24, s24, 3
; GFX9-NEXT:    s_addc_u32 s25, s25, 0
; GFX9-NEXT:    s_add_u32 s22, s22, 3
; GFX9-NEXT:    s_addc_u32 s23, s23, 0
; GFX9-NEXT:    s_add_u32 s20, s20, 3
; GFX9-NEXT:    s_addc_u32 s21, s21, 0
; GFX9-NEXT:    s_add_u32 s18, s18, 3
; GFX9-NEXT:    s_addc_u32 s19, s19, 0
; GFX9-NEXT:    s_add_u32 s16, s16, 3
; GFX9-NEXT:    s_addc_u32 s17, s17, 0
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:  .LBB23_3: ; %end
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    v_mov_b32_e32 v8, s24
; GFX9-NEXT:    v_mov_b32_e32 v9, s25
; GFX9-NEXT:    v_mov_b32_e32 v10, s26
; GFX9-NEXT:    v_mov_b32_e32 v11, s27
; GFX9-NEXT:    v_mov_b32_e32 v12, s28
; GFX9-NEXT:    v_mov_b32_e32 v13, s29
; GFX9-NEXT:    v_mov_b32_e32 v14, s11
; GFX9-NEXT:    v_mov_b32_e32 v15, s10
; GFX9-NEXT:    v_mov_b32_e32 v16, s9
; GFX9-NEXT:    v_mov_b32_e32 v17, s8
; GFX9-NEXT:    v_mov_b32_e32 v18, s7
; GFX9-NEXT:    v_mov_b32_e32 v19, s6
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB23_4:
; GFX9-NEXT:    s_branch .LBB23_2
;
; GFX11-LABEL: bitcast_v10i64_to_v20f32_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    v_readfirstlane_b32 s6, v2
; GFX11-NEXT:    v_readfirstlane_b32 s4, v1
; GFX11-NEXT:    v_readfirstlane_b32 s5, v0
; GFX11-NEXT:    s_cmp_lg_u32 s6, 0
; GFX11-NEXT:    s_mov_b32 s6, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB23_4
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s6
; GFX11-NEXT:    s_cbranch_vccnz .LBB23_3
; GFX11-NEXT:  .LBB23_2: ; %cmp.true
; GFX11-NEXT:    s_add_u32 s5, s5, 3
; GFX11-NEXT:    s_addc_u32 s4, s4, 0
; GFX11-NEXT:    s_add_u32 s28, s28, 3
; GFX11-NEXT:    s_addc_u32 s29, s29, 0
; GFX11-NEXT:    s_add_u32 s26, s26, 3
; GFX11-NEXT:    s_addc_u32 s27, s27, 0
; GFX11-NEXT:    s_add_u32 s24, s24, 3
; GFX11-NEXT:    s_addc_u32 s25, s25, 0
; GFX11-NEXT:    s_add_u32 s22, s22, 3
; GFX11-NEXT:    s_addc_u32 s23, s23, 0
; GFX11-NEXT:    s_add_u32 s20, s20, 3
; GFX11-NEXT:    s_addc_u32 s21, s21, 0
; GFX11-NEXT:    s_add_u32 s18, s18, 3
; GFX11-NEXT:    s_addc_u32 s19, s19, 0
; GFX11-NEXT:    s_add_u32 s16, s16, 3
; GFX11-NEXT:    s_addc_u32 s17, s17, 0
; GFX11-NEXT:    s_add_u32 s2, s2, 3
; GFX11-NEXT:    s_addc_u32 s3, s3, 0
; GFX11-NEXT:    s_add_u32 s0, s0, 3
; GFX11-NEXT:    s_addc_u32 s1, s1, 0
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:  .LBB23_3: ; %end
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s16 :: v_dual_mov_b32 v5, s17
; GFX11-NEXT:    v_dual_mov_b32 v6, s18 :: v_dual_mov_b32 v7, s19
; GFX11-NEXT:    v_dual_mov_b32 v8, s20 :: v_dual_mov_b32 v9, s21
; GFX11-NEXT:    v_dual_mov_b32 v10, s22 :: v_dual_mov_b32 v11, s23
; GFX11-NEXT:    v_dual_mov_b32 v12, s24 :: v_dual_mov_b32 v13, s25
; GFX11-NEXT:    v_dual_mov_b32 v14, s26 :: v_dual_mov_b32 v15, s27
; GFX11-NEXT:    v_dual_mov_b32 v16, s28 :: v_dual_mov_b32 v17, s29
; GFX11-NEXT:    v_dual_mov_b32 v18, s5 :: v_dual_mov_b32 v19, s4
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB23_4:
; GFX11-NEXT:    s_branch .LBB23_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <10 x i64> %a, splat (i64 3)
  %a2 = bitcast <10 x i64> %a1 to <20 x float>
  br label %end

cmp.false:
  %a3 = bitcast <10 x i64> %a to <20 x float>
  br label %end

end:
  %phi = phi <20 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <20 x float> %phi
}

define <10 x double> @bitcast_v20f32_to_v10f64(<20 x float> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v20f32_to_v10f64:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB24_2
; SI-NEXT:  ; %bb.1: ; %cmp.true
; SI-NEXT:    v_add_f32_e32 v19, 1.0, v19
; SI-NEXT:    v_add_f32_e32 v18, 1.0, v18
; SI-NEXT:    v_add_f32_e32 v17, 1.0, v17
; SI-NEXT:    v_add_f32_e32 v16, 1.0, v16
; SI-NEXT:    v_add_f32_e32 v15, 1.0, v15
; SI-NEXT:    v_add_f32_e32 v14, 1.0, v14
; SI-NEXT:    v_add_f32_e32 v13, 1.0, v13
; SI-NEXT:    v_add_f32_e32 v12, 1.0, v12
; SI-NEXT:    v_add_f32_e32 v11, 1.0, v11
; SI-NEXT:    v_add_f32_e32 v10, 1.0, v10
; SI-NEXT:    v_add_f32_e32 v9, 1.0, v9
; SI-NEXT:    v_add_f32_e32 v8, 1.0, v8
; SI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; SI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; SI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; SI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; SI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; SI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; SI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; SI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:  .LBB24_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v20f32_to_v10f64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB24_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f32_e32 v19, 1.0, v19
; VI-NEXT:    v_add_f32_e32 v18, 1.0, v18
; VI-NEXT:    v_add_f32_e32 v17, 1.0, v17
; VI-NEXT:    v_add_f32_e32 v16, 1.0, v16
; VI-NEXT:    v_add_f32_e32 v15, 1.0, v15
; VI-NEXT:    v_add_f32_e32 v14, 1.0, v14
; VI-NEXT:    v_add_f32_e32 v13, 1.0, v13
; VI-NEXT:    v_add_f32_e32 v12, 1.0, v12
; VI-NEXT:    v_add_f32_e32 v11, 1.0, v11
; VI-NEXT:    v_add_f32_e32 v10, 1.0, v10
; VI-NEXT:    v_add_f32_e32 v9, 1.0, v9
; VI-NEXT:    v_add_f32_e32 v8, 1.0, v8
; VI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; VI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; VI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; VI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; VI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; VI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; VI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; VI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:  .LBB24_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v20f32_to_v10f64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB24_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e32 v19, 1.0, v19
; GFX9-NEXT:    v_add_f32_e32 v18, 1.0, v18
; GFX9-NEXT:    v_add_f32_e32 v17, 1.0, v17
; GFX9-NEXT:    v_add_f32_e32 v16, 1.0, v16
; GFX9-NEXT:    v_add_f32_e32 v15, 1.0, v15
; GFX9-NEXT:    v_add_f32_e32 v14, 1.0, v14
; GFX9-NEXT:    v_add_f32_e32 v13, 1.0, v13
; GFX9-NEXT:    v_add_f32_e32 v12, 1.0, v12
; GFX9-NEXT:    v_add_f32_e32 v11, 1.0, v11
; GFX9-NEXT:    v_add_f32_e32 v10, 1.0, v10
; GFX9-NEXT:    v_add_f32_e32 v9, 1.0, v9
; GFX9-NEXT:    v_add_f32_e32 v8, 1.0, v8
; GFX9-NEXT:    v_add_f32_e32 v7, 1.0, v7
; GFX9-NEXT:    v_add_f32_e32 v6, 1.0, v6
; GFX9-NEXT:    v_add_f32_e32 v5, 1.0, v5
; GFX9-NEXT:    v_add_f32_e32 v4, 1.0, v4
; GFX9-NEXT:    v_add_f32_e32 v3, 1.0, v3
; GFX9-NEXT:    v_add_f32_e32 v2, 1.0, v2
; GFX9-NEXT:    v_add_f32_e32 v1, 1.0, v1
; GFX9-NEXT:    v_add_f32_e32 v0, 1.0, v0
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:  .LBB24_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v20f32_to_v10f64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB24_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_dual_add_f32 v19, 1.0, v19 :: v_dual_add_f32 v18, 1.0, v18
; GFX11-NEXT:    v_dual_add_f32 v17, 1.0, v17 :: v_dual_add_f32 v16, 1.0, v16
; GFX11-NEXT:    v_dual_add_f32 v15, 1.0, v15 :: v_dual_add_f32 v14, 1.0, v14
; GFX11-NEXT:    v_dual_add_f32 v13, 1.0, v13 :: v_dual_add_f32 v12, 1.0, v12
; GFX11-NEXT:    v_dual_add_f32 v11, 1.0, v11 :: v_dual_add_f32 v10, 1.0, v10
; GFX11-NEXT:    v_dual_add_f32 v9, 1.0, v9 :: v_dual_add_f32 v8, 1.0, v8
; GFX11-NEXT:    v_dual_add_f32 v7, 1.0, v7 :: v_dual_add_f32 v6, 1.0, v6
; GFX11-NEXT:    v_dual_add_f32 v5, 1.0, v5 :: v_dual_add_f32 v4, 1.0, v4
; GFX11-NEXT:    v_dual_add_f32 v3, 1.0, v3 :: v_dual_add_f32 v2, 1.0, v2
; GFX11-NEXT:    v_dual_add_f32 v1, 1.0, v1 :: v_dual_add_f32 v0, 1.0, v0
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:  .LBB24_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <20 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <20 x float> %a1 to <10 x double>
  br label %end

cmp.false:
  %a3 = bitcast <20 x float> %a to <10 x double>
  br label %end

end:
  %phi = phi <10 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <10 x double> %phi
}

define inreg <10 x double> @bitcast_v20f32_to_v10f64_scalar(<20 x float> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v20f32_to_v10f64_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_writelane_b32 v32, s36, 0
; SI-NEXT:    v_writelane_b32 v32, s37, 1
; SI-NEXT:    v_writelane_b32 v32, s38, 2
; SI-NEXT:    v_writelane_b32 v32, s39, 3
; SI-NEXT:    v_writelane_b32 v32, s48, 4
; SI-NEXT:    v_writelane_b32 v32, s49, 5
; SI-NEXT:    v_writelane_b32 v32, s50, 6
; SI-NEXT:    v_writelane_b32 v32, s51, 7
; SI-NEXT:    v_writelane_b32 v32, s52, 8
; SI-NEXT:    v_writelane_b32 v32, s53, 9
; SI-NEXT:    v_writelane_b32 v32, s54, 10
; SI-NEXT:    v_writelane_b32 v32, s55, 11
; SI-NEXT:    v_readfirstlane_b32 s4, v6
; SI-NEXT:    s_mov_b32 s49, s29
; SI-NEXT:    s_mov_b32 s48, s28
; SI-NEXT:    s_mov_b32 s47, s27
; SI-NEXT:    s_mov_b32 s46, s26
; SI-NEXT:    s_mov_b32 s45, s25
; SI-NEXT:    s_mov_b32 s44, s24
; SI-NEXT:    s_mov_b32 s43, s23
; SI-NEXT:    s_mov_b32 s42, s22
; SI-NEXT:    s_mov_b32 s41, s21
; SI-NEXT:    s_mov_b32 s40, s20
; SI-NEXT:    s_mov_b32 s39, s19
; SI-NEXT:    s_mov_b32 s38, s18
; SI-NEXT:    s_mov_b32 s37, s17
; SI-NEXT:    s_mov_b32 s36, s16
; SI-NEXT:    v_readfirstlane_b32 s55, v5
; SI-NEXT:    v_readfirstlane_b32 s54, v4
; SI-NEXT:    v_readfirstlane_b32 s53, v3
; SI-NEXT:    v_readfirstlane_b32 s52, v2
; SI-NEXT:    v_readfirstlane_b32 s51, v1
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    v_readfirstlane_b32 s50, v0
; SI-NEXT:    s_cbranch_scc0 .LBB25_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_cbranch_execnz .LBB25_4
; SI-NEXT:  .LBB25_2: ; %cmp.true
; SI-NEXT:    v_add_f32_e64 v19, s55, 1.0
; SI-NEXT:    v_add_f32_e64 v18, s54, 1.0
; SI-NEXT:    v_add_f32_e64 v17, s53, 1.0
; SI-NEXT:    v_add_f32_e64 v16, s52, 1.0
; SI-NEXT:    v_add_f32_e64 v15, s51, 1.0
; SI-NEXT:    v_add_f32_e64 v14, s50, 1.0
; SI-NEXT:    v_add_f32_e64 v13, s49, 1.0
; SI-NEXT:    v_add_f32_e64 v12, s48, 1.0
; SI-NEXT:    v_add_f32_e64 v11, s47, 1.0
; SI-NEXT:    v_add_f32_e64 v10, s46, 1.0
; SI-NEXT:    v_add_f32_e64 v9, s45, 1.0
; SI-NEXT:    v_add_f32_e64 v8, s44, 1.0
; SI-NEXT:    v_add_f32_e64 v7, s43, 1.0
; SI-NEXT:    v_add_f32_e64 v6, s42, 1.0
; SI-NEXT:    v_add_f32_e64 v5, s41, 1.0
; SI-NEXT:    v_add_f32_e64 v4, s40, 1.0
; SI-NEXT:    v_add_f32_e64 v3, s39, 1.0
; SI-NEXT:    v_add_f32_e64 v2, s38, 1.0
; SI-NEXT:    v_add_f32_e64 v1, s37, 1.0
; SI-NEXT:    v_add_f32_e64 v0, s36, 1.0
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    s_branch .LBB25_5
; SI-NEXT:  .LBB25_3:
; SI-NEXT:    s_branch .LBB25_2
; SI-NEXT:  .LBB25_4:
; SI-NEXT:    v_mov_b32_e32 v0, s36
; SI-NEXT:    v_mov_b32_e32 v1, s37
; SI-NEXT:    v_mov_b32_e32 v2, s38
; SI-NEXT:    v_mov_b32_e32 v3, s39
; SI-NEXT:    v_mov_b32_e32 v4, s40
; SI-NEXT:    v_mov_b32_e32 v5, s41
; SI-NEXT:    v_mov_b32_e32 v6, s42
; SI-NEXT:    v_mov_b32_e32 v7, s43
; SI-NEXT:    v_mov_b32_e32 v8, s44
; SI-NEXT:    v_mov_b32_e32 v9, s45
; SI-NEXT:    v_mov_b32_e32 v10, s46
; SI-NEXT:    v_mov_b32_e32 v11, s47
; SI-NEXT:    v_mov_b32_e32 v12, s48
; SI-NEXT:    v_mov_b32_e32 v13, s49
; SI-NEXT:    v_mov_b32_e32 v14, s50
; SI-NEXT:    v_mov_b32_e32 v15, s51
; SI-NEXT:    v_mov_b32_e32 v16, s52
; SI-NEXT:    v_mov_b32_e32 v17, s53
; SI-NEXT:    v_mov_b32_e32 v18, s54
; SI-NEXT:    v_mov_b32_e32 v19, s55
; SI-NEXT:    v_mov_b32_e32 v20, s56
; SI-NEXT:    v_mov_b32_e32 v21, s57
; SI-NEXT:    v_mov_b32_e32 v22, s58
; SI-NEXT:    v_mov_b32_e32 v23, s59
; SI-NEXT:    v_mov_b32_e32 v24, s60
; SI-NEXT:    v_mov_b32_e32 v25, s61
; SI-NEXT:    v_mov_b32_e32 v26, s62
; SI-NEXT:    v_mov_b32_e32 v27, s63
; SI-NEXT:    v_mov_b32_e32 v28, s64
; SI-NEXT:    v_mov_b32_e32 v29, s65
; SI-NEXT:    v_mov_b32_e32 v30, s66
; SI-NEXT:    v_mov_b32_e32 v31, s67
; SI-NEXT:  .LBB25_5: ; %end
; SI-NEXT:    v_readlane_b32 s55, v32, 11
; SI-NEXT:    v_readlane_b32 s54, v32, 10
; SI-NEXT:    v_readlane_b32 s53, v32, 9
; SI-NEXT:    v_readlane_b32 s52, v32, 8
; SI-NEXT:    v_readlane_b32 s51, v32, 7
; SI-NEXT:    v_readlane_b32 s50, v32, 6
; SI-NEXT:    v_readlane_b32 s49, v32, 5
; SI-NEXT:    v_readlane_b32 s48, v32, 4
; SI-NEXT:    v_readlane_b32 s39, v32, 3
; SI-NEXT:    v_readlane_b32 s38, v32, 2
; SI-NEXT:    v_readlane_b32 s37, v32, 1
; SI-NEXT:    v_readlane_b32 s36, v32, 0
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v20f32_to_v10f64_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    v_writelane_b32 v32, s36, 0
; VI-NEXT:    v_writelane_b32 v32, s37, 1
; VI-NEXT:    v_writelane_b32 v32, s38, 2
; VI-NEXT:    v_writelane_b32 v32, s39, 3
; VI-NEXT:    v_writelane_b32 v32, s48, 4
; VI-NEXT:    v_writelane_b32 v32, s49, 5
; VI-NEXT:    v_writelane_b32 v32, s50, 6
; VI-NEXT:    v_writelane_b32 v32, s51, 7
; VI-NEXT:    v_writelane_b32 v32, s52, 8
; VI-NEXT:    v_writelane_b32 v32, s53, 9
; VI-NEXT:    v_writelane_b32 v32, s54, 10
; VI-NEXT:    v_writelane_b32 v32, s55, 11
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    s_mov_b32 s49, s29
; VI-NEXT:    s_mov_b32 s48, s28
; VI-NEXT:    s_mov_b32 s47, s27
; VI-NEXT:    s_mov_b32 s46, s26
; VI-NEXT:    s_mov_b32 s45, s25
; VI-NEXT:    s_mov_b32 s44, s24
; VI-NEXT:    s_mov_b32 s43, s23
; VI-NEXT:    s_mov_b32 s42, s22
; VI-NEXT:    s_mov_b32 s41, s21
; VI-NEXT:    s_mov_b32 s40, s20
; VI-NEXT:    s_mov_b32 s39, s19
; VI-NEXT:    s_mov_b32 s38, s18
; VI-NEXT:    s_mov_b32 s37, s17
; VI-NEXT:    s_mov_b32 s36, s16
; VI-NEXT:    v_readfirstlane_b32 s55, v5
; VI-NEXT:    v_readfirstlane_b32 s54, v4
; VI-NEXT:    v_readfirstlane_b32 s53, v3
; VI-NEXT:    v_readfirstlane_b32 s52, v2
; VI-NEXT:    v_readfirstlane_b32 s51, v1
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    v_readfirstlane_b32 s50, v0
; VI-NEXT:    s_cbranch_scc0 .LBB25_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB25_4
; VI-NEXT:  .LBB25_2: ; %cmp.true
; VI-NEXT:    v_add_f32_e64 v19, s55, 1.0
; VI-NEXT:    v_add_f32_e64 v18, s54, 1.0
; VI-NEXT:    v_add_f32_e64 v17, s53, 1.0
; VI-NEXT:    v_add_f32_e64 v16, s52, 1.0
; VI-NEXT:    v_add_f32_e64 v15, s51, 1.0
; VI-NEXT:    v_add_f32_e64 v14, s50, 1.0
; VI-NEXT:    v_add_f32_e64 v13, s49, 1.0
; VI-NEXT:    v_add_f32_e64 v12, s48, 1.0
; VI-NEXT:    v_add_f32_e64 v11, s47, 1.0
; VI-NEXT:    v_add_f32_e64 v10, s46, 1.0
; VI-NEXT:    v_add_f32_e64 v9, s45, 1.0
; VI-NEXT:    v_add_f32_e64 v8, s44, 1.0
; VI-NEXT:    v_add_f32_e64 v7, s43, 1.0
; VI-NEXT:    v_add_f32_e64 v6, s42, 1.0
; VI-NEXT:    v_add_f32_e64 v5, s41, 1.0
; VI-NEXT:    v_add_f32_e64 v4, s40, 1.0
; VI-NEXT:    v_add_f32_e64 v3, s39, 1.0
; VI-NEXT:    v_add_f32_e64 v2, s38, 1.0
; VI-NEXT:    v_add_f32_e64 v1, s37, 1.0
; VI-NEXT:    v_add_f32_e64 v0, s36, 1.0
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    s_branch .LBB25_5
; VI-NEXT:  .LBB25_3:
; VI-NEXT:    s_branch .LBB25_2
; VI-NEXT:  .LBB25_4:
; VI-NEXT:    v_mov_b32_e32 v0, s36
; VI-NEXT:    v_mov_b32_e32 v1, s37
; VI-NEXT:    v_mov_b32_e32 v2, s38
; VI-NEXT:    v_mov_b32_e32 v3, s39
; VI-NEXT:    v_mov_b32_e32 v4, s40
; VI-NEXT:    v_mov_b32_e32 v5, s41
; VI-NEXT:    v_mov_b32_e32 v6, s42
; VI-NEXT:    v_mov_b32_e32 v7, s43
; VI-NEXT:    v_mov_b32_e32 v8, s44
; VI-NEXT:    v_mov_b32_e32 v9, s45
; VI-NEXT:    v_mov_b32_e32 v10, s46
; VI-NEXT:    v_mov_b32_e32 v11, s47
; VI-NEXT:    v_mov_b32_e32 v12, s48
; VI-NEXT:    v_mov_b32_e32 v13, s49
; VI-NEXT:    v_mov_b32_e32 v14, s50
; VI-NEXT:    v_mov_b32_e32 v15, s51
; VI-NEXT:    v_mov_b32_e32 v16, s52
; VI-NEXT:    v_mov_b32_e32 v17, s53
; VI-NEXT:    v_mov_b32_e32 v18, s54
; VI-NEXT:    v_mov_b32_e32 v19, s55
; VI-NEXT:    v_mov_b32_e32 v20, s56
; VI-NEXT:    v_mov_b32_e32 v21, s57
; VI-NEXT:    v_mov_b32_e32 v22, s58
; VI-NEXT:    v_mov_b32_e32 v23, s59
; VI-NEXT:    v_mov_b32_e32 v24, s60
; VI-NEXT:    v_mov_b32_e32 v25, s61
; VI-NEXT:    v_mov_b32_e32 v26, s62
; VI-NEXT:    v_mov_b32_e32 v27, s63
; VI-NEXT:    v_mov_b32_e32 v28, s64
; VI-NEXT:    v_mov_b32_e32 v29, s65
; VI-NEXT:    v_mov_b32_e32 v30, s66
; VI-NEXT:    v_mov_b32_e32 v31, s67
; VI-NEXT:  .LBB25_5: ; %end
; VI-NEXT:    v_readlane_b32 s55, v32, 11
; VI-NEXT:    v_readlane_b32 s54, v32, 10
; VI-NEXT:    v_readlane_b32 s53, v32, 9
; VI-NEXT:    v_readlane_b32 s52, v32, 8
; VI-NEXT:    v_readlane_b32 s51, v32, 7
; VI-NEXT:    v_readlane_b32 s50, v32, 6
; VI-NEXT:    v_readlane_b32 s49, v32, 5
; VI-NEXT:    v_readlane_b32 s48, v32, 4
; VI-NEXT:    v_readlane_b32 s39, v32, 3
; VI-NEXT:    v_readlane_b32 s38, v32, 2
; VI-NEXT:    v_readlane_b32 s37, v32, 1
; VI-NEXT:    v_readlane_b32 s36, v32, 0
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v20f32_to_v10f64_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    v_writelane_b32 v32, s36, 0
; GFX9-NEXT:    v_writelane_b32 v32, s37, 1
; GFX9-NEXT:    v_writelane_b32 v32, s38, 2
; GFX9-NEXT:    v_writelane_b32 v32, s39, 3
; GFX9-NEXT:    v_writelane_b32 v32, s48, 4
; GFX9-NEXT:    v_writelane_b32 v32, s49, 5
; GFX9-NEXT:    v_writelane_b32 v32, s50, 6
; GFX9-NEXT:    v_writelane_b32 v32, s51, 7
; GFX9-NEXT:    v_writelane_b32 v32, s52, 8
; GFX9-NEXT:    v_writelane_b32 v32, s53, 9
; GFX9-NEXT:    v_writelane_b32 v32, s54, 10
; GFX9-NEXT:    v_writelane_b32 v32, s55, 11
; GFX9-NEXT:    v_readfirstlane_b32 s4, v6
; GFX9-NEXT:    s_mov_b32 s49, s29
; GFX9-NEXT:    s_mov_b32 s48, s28
; GFX9-NEXT:    s_mov_b32 s47, s27
; GFX9-NEXT:    s_mov_b32 s46, s26
; GFX9-NEXT:    s_mov_b32 s45, s25
; GFX9-NEXT:    s_mov_b32 s44, s24
; GFX9-NEXT:    s_mov_b32 s43, s23
; GFX9-NEXT:    s_mov_b32 s42, s22
; GFX9-NEXT:    s_mov_b32 s41, s21
; GFX9-NEXT:    s_mov_b32 s40, s20
; GFX9-NEXT:    s_mov_b32 s39, s19
; GFX9-NEXT:    s_mov_b32 s38, s18
; GFX9-NEXT:    s_mov_b32 s37, s17
; GFX9-NEXT:    s_mov_b32 s36, s16
; GFX9-NEXT:    v_readfirstlane_b32 s55, v5
; GFX9-NEXT:    v_readfirstlane_b32 s54, v4
; GFX9-NEXT:    v_readfirstlane_b32 s53, v3
; GFX9-NEXT:    v_readfirstlane_b32 s52, v2
; GFX9-NEXT:    v_readfirstlane_b32 s51, v1
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    v_readfirstlane_b32 s50, v0
; GFX9-NEXT:    s_cbranch_scc0 .LBB25_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB25_4
; GFX9-NEXT:  .LBB25_2: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e64 v19, s55, 1.0
; GFX9-NEXT:    v_add_f32_e64 v18, s54, 1.0
; GFX9-NEXT:    v_add_f32_e64 v17, s53, 1.0
; GFX9-NEXT:    v_add_f32_e64 v16, s52, 1.0
; GFX9-NEXT:    v_add_f32_e64 v15, s51, 1.0
; GFX9-NEXT:    v_add_f32_e64 v14, s50, 1.0
; GFX9-NEXT:    v_add_f32_e64 v13, s49, 1.0
; GFX9-NEXT:    v_add_f32_e64 v12, s48, 1.0
; GFX9-NEXT:    v_add_f32_e64 v11, s47, 1.0
; GFX9-NEXT:    v_add_f32_e64 v10, s46, 1.0
; GFX9-NEXT:    v_add_f32_e64 v9, s45, 1.0
; GFX9-NEXT:    v_add_f32_e64 v8, s44, 1.0
; GFX9-NEXT:    v_add_f32_e64 v7, s43, 1.0
; GFX9-NEXT:    v_add_f32_e64 v6, s42, 1.0
; GFX9-NEXT:    v_add_f32_e64 v5, s41, 1.0
; GFX9-NEXT:    v_add_f32_e64 v4, s40, 1.0
; GFX9-NEXT:    v_add_f32_e64 v3, s39, 1.0
; GFX9-NEXT:    v_add_f32_e64 v2, s38, 1.0
; GFX9-NEXT:    v_add_f32_e64 v1, s37, 1.0
; GFX9-NEXT:    v_add_f32_e64 v0, s36, 1.0
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_branch .LBB25_5
; GFX9-NEXT:  .LBB25_3:
; GFX9-NEXT:    s_branch .LBB25_2
; GFX9-NEXT:  .LBB25_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s36
; GFX9-NEXT:    v_mov_b32_e32 v1, s37
; GFX9-NEXT:    v_mov_b32_e32 v2, s38
; GFX9-NEXT:    v_mov_b32_e32 v3, s39
; GFX9-NEXT:    v_mov_b32_e32 v4, s40
; GFX9-NEXT:    v_mov_b32_e32 v5, s41
; GFX9-NEXT:    v_mov_b32_e32 v6, s42
; GFX9-NEXT:    v_mov_b32_e32 v7, s43
; GFX9-NEXT:    v_mov_b32_e32 v8, s44
; GFX9-NEXT:    v_mov_b32_e32 v9, s45
; GFX9-NEXT:    v_mov_b32_e32 v10, s46
; GFX9-NEXT:    v_mov_b32_e32 v11, s47
; GFX9-NEXT:    v_mov_b32_e32 v12, s48
; GFX9-NEXT:    v_mov_b32_e32 v13, s49
; GFX9-NEXT:    v_mov_b32_e32 v14, s50
; GFX9-NEXT:    v_mov_b32_e32 v15, s51
; GFX9-NEXT:    v_mov_b32_e32 v16, s52
; GFX9-NEXT:    v_mov_b32_e32 v17, s53
; GFX9-NEXT:    v_mov_b32_e32 v18, s54
; GFX9-NEXT:    v_mov_b32_e32 v19, s55
; GFX9-NEXT:    v_mov_b32_e32 v20, s56
; GFX9-NEXT:    v_mov_b32_e32 v21, s57
; GFX9-NEXT:    v_mov_b32_e32 v22, s58
; GFX9-NEXT:    v_mov_b32_e32 v23, s59
; GFX9-NEXT:    v_mov_b32_e32 v24, s60
; GFX9-NEXT:    v_mov_b32_e32 v25, s61
; GFX9-NEXT:    v_mov_b32_e32 v26, s62
; GFX9-NEXT:    v_mov_b32_e32 v27, s63
; GFX9-NEXT:    v_mov_b32_e32 v28, s64
; GFX9-NEXT:    v_mov_b32_e32 v29, s65
; GFX9-NEXT:    v_mov_b32_e32 v30, s66
; GFX9-NEXT:    v_mov_b32_e32 v31, s67
; GFX9-NEXT:  .LBB25_5: ; %end
; GFX9-NEXT:    v_readlane_b32 s55, v32, 11
; GFX9-NEXT:    v_readlane_b32 s54, v32, 10
; GFX9-NEXT:    v_readlane_b32 s53, v32, 9
; GFX9-NEXT:    v_readlane_b32 s52, v32, 8
; GFX9-NEXT:    v_readlane_b32 s51, v32, 7
; GFX9-NEXT:    v_readlane_b32 s50, v32, 6
; GFX9-NEXT:    v_readlane_b32 s49, v32, 5
; GFX9-NEXT:    v_readlane_b32 s48, v32, 4
; GFX9-NEXT:    v_readlane_b32 s39, v32, 3
; GFX9-NEXT:    v_readlane_b32 s38, v32, 2
; GFX9-NEXT:    v_readlane_b32 s37, v32, 1
; GFX9-NEXT:    v_readlane_b32 s36, v32, 0
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v20f32_to_v10f64_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_xor_saveexec_b32 s4, -1
; GFX11-NEXT:    scratch_store_b32 off, v32, s32 ; 4-byte Folded Spill
; GFX11-NEXT:    s_mov_b32 exec_lo, s4
; GFX11-NEXT:    v_writelane_b32 v32, s36, 0
; GFX11-NEXT:    v_writelane_b32 v32, s37, 1
; GFX11-NEXT:    v_writelane_b32 v32, s38, 2
; GFX11-NEXT:    v_writelane_b32 v32, s39, 3
; GFX11-NEXT:    v_writelane_b32 v32, s48, 4
; GFX11-NEXT:    v_writelane_b32 v32, s49, 5
; GFX11-NEXT:    v_writelane_b32 v32, s50, 6
; GFX11-NEXT:    v_writelane_b32 v32, s51, 7
; GFX11-NEXT:    v_writelane_b32 v32, s52, 8
; GFX11-NEXT:    v_writelane_b32 v32, s53, 9
; GFX11-NEXT:    v_writelane_b32 v32, s54, 10
; GFX11-NEXT:    v_writelane_b32 v32, s55, 11
; GFX11-NEXT:    s_mov_b32 s36, s0
; GFX11-NEXT:    v_readfirstlane_b32 s0, v2
; GFX11-NEXT:    v_readfirstlane_b32 s55, v1
; GFX11-NEXT:    v_readfirstlane_b32 s54, v0
; GFX11-NEXT:    s_mov_b32 s53, s29
; GFX11-NEXT:    s_mov_b32 s52, s28
; GFX11-NEXT:    s_mov_b32 s51, s27
; GFX11-NEXT:    s_mov_b32 s50, s26
; GFX11-NEXT:    s_mov_b32 s49, s25
; GFX11-NEXT:    s_mov_b32 s48, s24
; GFX11-NEXT:    s_mov_b32 s47, s23
; GFX11-NEXT:    s_mov_b32 s46, s22
; GFX11-NEXT:    s_mov_b32 s45, s21
; GFX11-NEXT:    s_mov_b32 s44, s20
; GFX11-NEXT:    s_mov_b32 s43, s19
; GFX11-NEXT:    s_mov_b32 s42, s18
; GFX11-NEXT:    s_mov_b32 s41, s17
; GFX11-NEXT:    s_mov_b32 s40, s16
; GFX11-NEXT:    s_mov_b32 s39, s3
; GFX11-NEXT:    s_mov_b32 s38, s2
; GFX11-NEXT:    s_mov_b32 s37, s1
; GFX11-NEXT:    s_cmp_lg_u32 s0, 0
; GFX11-NEXT:    s_mov_b32 s0, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB25_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s0
; GFX11-NEXT:    s_cbranch_vccnz .LBB25_4
; GFX11-NEXT:  .LBB25_2: ; %cmp.true
; GFX11-NEXT:    v_add_f32_e64 v19, s55, 1.0
; GFX11-NEXT:    v_add_f32_e64 v18, s54, 1.0
; GFX11-NEXT:    v_add_f32_e64 v17, s53, 1.0
; GFX11-NEXT:    v_add_f32_e64 v16, s52, 1.0
; GFX11-NEXT:    v_add_f32_e64 v15, s51, 1.0
; GFX11-NEXT:    v_add_f32_e64 v14, s50, 1.0
; GFX11-NEXT:    v_add_f32_e64 v13, s49, 1.0
; GFX11-NEXT:    v_add_f32_e64 v12, s48, 1.0
; GFX11-NEXT:    v_add_f32_e64 v11, s47, 1.0
; GFX11-NEXT:    v_add_f32_e64 v10, s46, 1.0
; GFX11-NEXT:    v_add_f32_e64 v9, s45, 1.0
; GFX11-NEXT:    v_add_f32_e64 v8, s44, 1.0
; GFX11-NEXT:    v_add_f32_e64 v7, s43, 1.0
; GFX11-NEXT:    v_add_f32_e64 v6, s42, 1.0
; GFX11-NEXT:    v_add_f32_e64 v5, s41, 1.0
; GFX11-NEXT:    v_add_f32_e64 v4, s40, 1.0
; GFX11-NEXT:    v_add_f32_e64 v3, s39, 1.0
; GFX11-NEXT:    v_add_f32_e64 v2, s38, 1.0
; GFX11-NEXT:    v_add_f32_e64 v1, s37, 1.0
; GFX11-NEXT:    v_add_f32_e64 v0, s36, 1.0
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    s_branch .LBB25_5
; GFX11-NEXT:  .LBB25_3:
; GFX11-NEXT:    s_branch .LBB25_2
; GFX11-NEXT:  .LBB25_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s36 :: v_dual_mov_b32 v1, s37
; GFX11-NEXT:    v_dual_mov_b32 v2, s38 :: v_dual_mov_b32 v3, s39
; GFX11-NEXT:    v_dual_mov_b32 v4, s40 :: v_dual_mov_b32 v5, s41
; GFX11-NEXT:    v_dual_mov_b32 v6, s42 :: v_dual_mov_b32 v7, s43
; GFX11-NEXT:    v_dual_mov_b32 v8, s44 :: v_dual_mov_b32 v9, s45
; GFX11-NEXT:    v_dual_mov_b32 v10, s46 :: v_dual_mov_b32 v11, s47
; GFX11-NEXT:    v_dual_mov_b32 v12, s48 :: v_dual_mov_b32 v13, s49
; GFX11-NEXT:    v_dual_mov_b32 v14, s50 :: v_dual_mov_b32 v15, s51
; GFX11-NEXT:    v_dual_mov_b32 v16, s52 :: v_dual_mov_b32 v17, s53
; GFX11-NEXT:    v_dual_mov_b32 v18, s54 :: v_dual_mov_b32 v19, s55
; GFX11-NEXT:    v_dual_mov_b32 v20, s56 :: v_dual_mov_b32 v21, s57
; GFX11-NEXT:    v_dual_mov_b32 v22, s58 :: v_dual_mov_b32 v23, s59
; GFX11-NEXT:    v_dual_mov_b32 v24, s60 :: v_dual_mov_b32 v25, s61
; GFX11-NEXT:    v_dual_mov_b32 v26, s62 :: v_dual_mov_b32 v27, s63
; GFX11-NEXT:    v_dual_mov_b32 v28, s64 :: v_dual_mov_b32 v29, s65
; GFX11-NEXT:    v_dual_mov_b32 v30, s66 :: v_dual_mov_b32 v31, s67
; GFX11-NEXT:  .LBB25_5: ; %end
; GFX11-NEXT:    v_readlane_b32 s55, v32, 11
; GFX11-NEXT:    v_readlane_b32 s54, v32, 10
; GFX11-NEXT:    v_readlane_b32 s53, v32, 9
; GFX11-NEXT:    v_readlane_b32 s52, v32, 8
; GFX11-NEXT:    v_readlane_b32 s51, v32, 7
; GFX11-NEXT:    v_readlane_b32 s50, v32, 6
; GFX11-NEXT:    v_readlane_b32 s49, v32, 5
; GFX11-NEXT:    v_readlane_b32 s48, v32, 4
; GFX11-NEXT:    v_readlane_b32 s39, v32, 3
; GFX11-NEXT:    v_readlane_b32 s38, v32, 2
; GFX11-NEXT:    v_readlane_b32 s37, v32, 1
; GFX11-NEXT:    v_readlane_b32 s36, v32, 0
; GFX11-NEXT:    s_xor_saveexec_b32 s0, -1
; GFX11-NEXT:    scratch_load_b32 v32, off, s32 ; 4-byte Folded Reload
; GFX11-NEXT:    s_mov_b32 exec_lo, s0
; GFX11-NEXT:    s_waitcnt vmcnt(0)
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <20 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <20 x float> %a1 to <10 x double>
  br label %end

cmp.false:
  %a3 = bitcast <20 x float> %a to <10 x double>
  br label %end

end:
  %phi = phi <10 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <10 x double> %phi
}

define <20 x float> @bitcast_v10f64_to_v20f32(<10 x double> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v10f64_to_v20f32:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB26_2
; SI-NEXT:  ; %bb.1: ; %cmp.true
; SI-NEXT:    v_add_f64 v[18:19], v[18:19], 1.0
; SI-NEXT:    v_add_f64 v[16:17], v[16:17], 1.0
; SI-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; SI-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; SI-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; SI-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; SI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; SI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; SI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; SI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:  .LBB26_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v10f64_to_v20f32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB26_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f64 v[18:19], v[18:19], 1.0
; VI-NEXT:    v_add_f64 v[16:17], v[16:17], 1.0
; VI-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; VI-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; VI-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; VI-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; VI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; VI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; VI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; VI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:  .LBB26_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v10f64_to_v20f32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB26_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[18:19], v[18:19], 1.0
; GFX9-NEXT:    v_add_f64 v[16:17], v[16:17], 1.0
; GFX9-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GFX9-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GFX9-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GFX9-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GFX9-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX9-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:  .LBB26_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v10f64_to_v20f32:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB26_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_f64 v[18:19], v[18:19], 1.0
; GFX11-NEXT:    v_add_f64 v[16:17], v[16:17], 1.0
; GFX11-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GFX11-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GFX11-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GFX11-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GFX11-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX11-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX11-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX11-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:  .LBB26_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <10 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <10 x double> %a1 to <20 x float>
  br label %end

cmp.false:
  %a3 = bitcast <10 x double> %a to <20 x float>
  br label %end

end:
  %phi = phi <20 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <20 x float> %phi
}

define inreg <20 x float> @bitcast_v10f64_to_v20f32_scalar(<10 x double> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v10f64_to_v20f32_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_writelane_b32 v32, s36, 0
; SI-NEXT:    v_writelane_b32 v32, s37, 1
; SI-NEXT:    v_writelane_b32 v32, s38, 2
; SI-NEXT:    v_writelane_b32 v32, s39, 3
; SI-NEXT:    v_writelane_b32 v32, s48, 4
; SI-NEXT:    v_writelane_b32 v32, s49, 5
; SI-NEXT:    v_writelane_b32 v32, s50, 6
; SI-NEXT:    v_writelane_b32 v32, s51, 7
; SI-NEXT:    v_writelane_b32 v32, s52, 8
; SI-NEXT:    v_writelane_b32 v32, s53, 9
; SI-NEXT:    v_writelane_b32 v32, s54, 10
; SI-NEXT:    v_writelane_b32 v32, s55, 11
; SI-NEXT:    v_readfirstlane_b32 s4, v6
; SI-NEXT:    s_mov_b32 s49, s29
; SI-NEXT:    s_mov_b32 s48, s28
; SI-NEXT:    s_mov_b32 s47, s27
; SI-NEXT:    s_mov_b32 s46, s26
; SI-NEXT:    s_mov_b32 s45, s25
; SI-NEXT:    s_mov_b32 s44, s24
; SI-NEXT:    s_mov_b32 s43, s23
; SI-NEXT:    s_mov_b32 s42, s22
; SI-NEXT:    s_mov_b32 s41, s21
; SI-NEXT:    s_mov_b32 s40, s20
; SI-NEXT:    s_mov_b32 s39, s19
; SI-NEXT:    s_mov_b32 s38, s18
; SI-NEXT:    s_mov_b32 s37, s17
; SI-NEXT:    s_mov_b32 s36, s16
; SI-NEXT:    v_readfirstlane_b32 s55, v5
; SI-NEXT:    v_readfirstlane_b32 s54, v4
; SI-NEXT:    v_readfirstlane_b32 s53, v3
; SI-NEXT:    v_readfirstlane_b32 s52, v2
; SI-NEXT:    v_readfirstlane_b32 s51, v1
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    v_readfirstlane_b32 s50, v0
; SI-NEXT:    s_cbranch_scc0 .LBB27_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_cbranch_execnz .LBB27_4
; SI-NEXT:  .LBB27_2: ; %cmp.true
; SI-NEXT:    v_add_f64 v[18:19], s[54:55], 1.0
; SI-NEXT:    v_add_f64 v[16:17], s[52:53], 1.0
; SI-NEXT:    v_add_f64 v[14:15], s[50:51], 1.0
; SI-NEXT:    v_add_f64 v[12:13], s[48:49], 1.0
; SI-NEXT:    v_add_f64 v[10:11], s[46:47], 1.0
; SI-NEXT:    v_add_f64 v[8:9], s[44:45], 1.0
; SI-NEXT:    v_add_f64 v[6:7], s[42:43], 1.0
; SI-NEXT:    v_add_f64 v[4:5], s[40:41], 1.0
; SI-NEXT:    v_add_f64 v[2:3], s[38:39], 1.0
; SI-NEXT:    v_add_f64 v[0:1], s[36:37], 1.0
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    s_branch .LBB27_5
; SI-NEXT:  .LBB27_3:
; SI-NEXT:    s_branch .LBB27_2
; SI-NEXT:  .LBB27_4:
; SI-NEXT:    v_mov_b32_e32 v0, s36
; SI-NEXT:    v_mov_b32_e32 v1, s37
; SI-NEXT:    v_mov_b32_e32 v2, s38
; SI-NEXT:    v_mov_b32_e32 v3, s39
; SI-NEXT:    v_mov_b32_e32 v4, s40
; SI-NEXT:    v_mov_b32_e32 v5, s41
; SI-NEXT:    v_mov_b32_e32 v6, s42
; SI-NEXT:    v_mov_b32_e32 v7, s43
; SI-NEXT:    v_mov_b32_e32 v8, s44
; SI-NEXT:    v_mov_b32_e32 v9, s45
; SI-NEXT:    v_mov_b32_e32 v10, s46
; SI-NEXT:    v_mov_b32_e32 v11, s47
; SI-NEXT:    v_mov_b32_e32 v12, s48
; SI-NEXT:    v_mov_b32_e32 v13, s49
; SI-NEXT:    v_mov_b32_e32 v14, s50
; SI-NEXT:    v_mov_b32_e32 v15, s51
; SI-NEXT:    v_mov_b32_e32 v16, s52
; SI-NEXT:    v_mov_b32_e32 v17, s53
; SI-NEXT:    v_mov_b32_e32 v18, s54
; SI-NEXT:    v_mov_b32_e32 v19, s55
; SI-NEXT:    v_mov_b32_e32 v20, s56
; SI-NEXT:    v_mov_b32_e32 v21, s57
; SI-NEXT:    v_mov_b32_e32 v22, s58
; SI-NEXT:    v_mov_b32_e32 v23, s59
; SI-NEXT:    v_mov_b32_e32 v24, s60
; SI-NEXT:    v_mov_b32_e32 v25, s61
; SI-NEXT:    v_mov_b32_e32 v26, s62
; SI-NEXT:    v_mov_b32_e32 v27, s63
; SI-NEXT:    v_mov_b32_e32 v28, s64
; SI-NEXT:    v_mov_b32_e32 v29, s65
; SI-NEXT:    v_mov_b32_e32 v30, s66
; SI-NEXT:    v_mov_b32_e32 v31, s67
; SI-NEXT:  .LBB27_5: ; %end
; SI-NEXT:    v_readlane_b32 s55, v32, 11
; SI-NEXT:    v_readlane_b32 s54, v32, 10
; SI-NEXT:    v_readlane_b32 s53, v32, 9
; SI-NEXT:    v_readlane_b32 s52, v32, 8
; SI-NEXT:    v_readlane_b32 s51, v32, 7
; SI-NEXT:    v_readlane_b32 s50, v32, 6
; SI-NEXT:    v_readlane_b32 s49, v32, 5
; SI-NEXT:    v_readlane_b32 s48, v32, 4
; SI-NEXT:    v_readlane_b32 s39, v32, 3
; SI-NEXT:    v_readlane_b32 s38, v32, 2
; SI-NEXT:    v_readlane_b32 s37, v32, 1
; SI-NEXT:    v_readlane_b32 s36, v32, 0
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v10f64_to_v20f32_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    v_writelane_b32 v32, s36, 0
; VI-NEXT:    v_writelane_b32 v32, s37, 1
; VI-NEXT:    v_writelane_b32 v32, s38, 2
; VI-NEXT:    v_writelane_b32 v32, s39, 3
; VI-NEXT:    v_writelane_b32 v32, s48, 4
; VI-NEXT:    v_writelane_b32 v32, s49, 5
; VI-NEXT:    v_writelane_b32 v32, s50, 6
; VI-NEXT:    v_writelane_b32 v32, s51, 7
; VI-NEXT:    v_writelane_b32 v32, s52, 8
; VI-NEXT:    v_writelane_b32 v32, s53, 9
; VI-NEXT:    v_writelane_b32 v32, s54, 10
; VI-NEXT:    v_writelane_b32 v32, s55, 11
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    s_mov_b32 s49, s29
; VI-NEXT:    s_mov_b32 s48, s28
; VI-NEXT:    s_mov_b32 s47, s27
; VI-NEXT:    s_mov_b32 s46, s26
; VI-NEXT:    s_mov_b32 s45, s25
; VI-NEXT:    s_mov_b32 s44, s24
; VI-NEXT:    s_mov_b32 s43, s23
; VI-NEXT:    s_mov_b32 s42, s22
; VI-NEXT:    s_mov_b32 s41, s21
; VI-NEXT:    s_mov_b32 s40, s20
; VI-NEXT:    s_mov_b32 s39, s19
; VI-NEXT:    s_mov_b32 s38, s18
; VI-NEXT:    s_mov_b32 s37, s17
; VI-NEXT:    s_mov_b32 s36, s16
; VI-NEXT:    v_readfirstlane_b32 s55, v5
; VI-NEXT:    v_readfirstlane_b32 s54, v4
; VI-NEXT:    v_readfirstlane_b32 s53, v3
; VI-NEXT:    v_readfirstlane_b32 s52, v2
; VI-NEXT:    v_readfirstlane_b32 s51, v1
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    v_readfirstlane_b32 s50, v0
; VI-NEXT:    s_cbranch_scc0 .LBB27_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB27_4
; VI-NEXT:  .LBB27_2: ; %cmp.true
; VI-NEXT:    v_add_f64 v[18:19], s[54:55], 1.0
; VI-NEXT:    v_add_f64 v[16:17], s[52:53], 1.0
; VI-NEXT:    v_add_f64 v[14:15], s[50:51], 1.0
; VI-NEXT:    v_add_f64 v[12:13], s[48:49], 1.0
; VI-NEXT:    v_add_f64 v[10:11], s[46:47], 1.0
; VI-NEXT:    v_add_f64 v[8:9], s[44:45], 1.0
; VI-NEXT:    v_add_f64 v[6:7], s[42:43], 1.0
; VI-NEXT:    v_add_f64 v[4:5], s[40:41], 1.0
; VI-NEXT:    v_add_f64 v[2:3], s[38:39], 1.0
; VI-NEXT:    v_add_f64 v[0:1], s[36:37], 1.0
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    s_branch .LBB27_5
; VI-NEXT:  .LBB27_3:
; VI-NEXT:    s_branch .LBB27_2
; VI-NEXT:  .LBB27_4:
; VI-NEXT:    v_mov_b32_e32 v0, s36
; VI-NEXT:    v_mov_b32_e32 v1, s37
; VI-NEXT:    v_mov_b32_e32 v2, s38
; VI-NEXT:    v_mov_b32_e32 v3, s39
; VI-NEXT:    v_mov_b32_e32 v4, s40
; VI-NEXT:    v_mov_b32_e32 v5, s41
; VI-NEXT:    v_mov_b32_e32 v6, s42
; VI-NEXT:    v_mov_b32_e32 v7, s43
; VI-NEXT:    v_mov_b32_e32 v8, s44
; VI-NEXT:    v_mov_b32_e32 v9, s45
; VI-NEXT:    v_mov_b32_e32 v10, s46
; VI-NEXT:    v_mov_b32_e32 v11, s47
; VI-NEXT:    v_mov_b32_e32 v12, s48
; VI-NEXT:    v_mov_b32_e32 v13, s49
; VI-NEXT:    v_mov_b32_e32 v14, s50
; VI-NEXT:    v_mov_b32_e32 v15, s51
; VI-NEXT:    v_mov_b32_e32 v16, s52
; VI-NEXT:    v_mov_b32_e32 v17, s53
; VI-NEXT:    v_mov_b32_e32 v18, s54
; VI-NEXT:    v_mov_b32_e32 v19, s55
; VI-NEXT:    v_mov_b32_e32 v20, s56
; VI-NEXT:    v_mov_b32_e32 v21, s57
; VI-NEXT:    v_mov_b32_e32 v22, s58
; VI-NEXT:    v_mov_b32_e32 v23, s59
; VI-NEXT:    v_mov_b32_e32 v24, s60
; VI-NEXT:    v_mov_b32_e32 v25, s61
; VI-NEXT:    v_mov_b32_e32 v26, s62
; VI-NEXT:    v_mov_b32_e32 v27, s63
; VI-NEXT:    v_mov_b32_e32 v28, s64
; VI-NEXT:    v_mov_b32_e32 v29, s65
; VI-NEXT:    v_mov_b32_e32 v30, s66
; VI-NEXT:    v_mov_b32_e32 v31, s67
; VI-NEXT:  .LBB27_5: ; %end
; VI-NEXT:    v_readlane_b32 s55, v32, 11
; VI-NEXT:    v_readlane_b32 s54, v32, 10
; VI-NEXT:    v_readlane_b32 s53, v32, 9
; VI-NEXT:    v_readlane_b32 s52, v32, 8
; VI-NEXT:    v_readlane_b32 s51, v32, 7
; VI-NEXT:    v_readlane_b32 s50, v32, 6
; VI-NEXT:    v_readlane_b32 s49, v32, 5
; VI-NEXT:    v_readlane_b32 s48, v32, 4
; VI-NEXT:    v_readlane_b32 s39, v32, 3
; VI-NEXT:    v_readlane_b32 s38, v32, 2
; VI-NEXT:    v_readlane_b32 s37, v32, 1
; VI-NEXT:    v_readlane_b32 s36, v32, 0
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v10f64_to_v20f32_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    v_writelane_b32 v32, s36, 0
; GFX9-NEXT:    v_writelane_b32 v32, s37, 1
; GFX9-NEXT:    v_writelane_b32 v32, s38, 2
; GFX9-NEXT:    v_writelane_b32 v32, s39, 3
; GFX9-NEXT:    v_writelane_b32 v32, s48, 4
; GFX9-NEXT:    v_writelane_b32 v32, s49, 5
; GFX9-NEXT:    v_writelane_b32 v32, s50, 6
; GFX9-NEXT:    v_writelane_b32 v32, s51, 7
; GFX9-NEXT:    v_writelane_b32 v32, s52, 8
; GFX9-NEXT:    v_writelane_b32 v32, s53, 9
; GFX9-NEXT:    v_writelane_b32 v32, s54, 10
; GFX9-NEXT:    v_writelane_b32 v32, s55, 11
; GFX9-NEXT:    v_readfirstlane_b32 s4, v6
; GFX9-NEXT:    s_mov_b32 s49, s29
; GFX9-NEXT:    s_mov_b32 s48, s28
; GFX9-NEXT:    s_mov_b32 s47, s27
; GFX9-NEXT:    s_mov_b32 s46, s26
; GFX9-NEXT:    s_mov_b32 s45, s25
; GFX9-NEXT:    s_mov_b32 s44, s24
; GFX9-NEXT:    s_mov_b32 s43, s23
; GFX9-NEXT:    s_mov_b32 s42, s22
; GFX9-NEXT:    s_mov_b32 s41, s21
; GFX9-NEXT:    s_mov_b32 s40, s20
; GFX9-NEXT:    s_mov_b32 s39, s19
; GFX9-NEXT:    s_mov_b32 s38, s18
; GFX9-NEXT:    s_mov_b32 s37, s17
; GFX9-NEXT:    s_mov_b32 s36, s16
; GFX9-NEXT:    v_readfirstlane_b32 s55, v5
; GFX9-NEXT:    v_readfirstlane_b32 s54, v4
; GFX9-NEXT:    v_readfirstlane_b32 s53, v3
; GFX9-NEXT:    v_readfirstlane_b32 s52, v2
; GFX9-NEXT:    v_readfirstlane_b32 s51, v1
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    v_readfirstlane_b32 s50, v0
; GFX9-NEXT:    s_cbranch_scc0 .LBB27_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB27_4
; GFX9-NEXT:  .LBB27_2: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[18:19], s[54:55], 1.0
; GFX9-NEXT:    v_add_f64 v[16:17], s[52:53], 1.0
; GFX9-NEXT:    v_add_f64 v[14:15], s[50:51], 1.0
; GFX9-NEXT:    v_add_f64 v[12:13], s[48:49], 1.0
; GFX9-NEXT:    v_add_f64 v[10:11], s[46:47], 1.0
; GFX9-NEXT:    v_add_f64 v[8:9], s[44:45], 1.0
; GFX9-NEXT:    v_add_f64 v[6:7], s[42:43], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], s[40:41], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], s[38:39], 1.0
; GFX9-NEXT:    v_add_f64 v[0:1], s[36:37], 1.0
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_branch .LBB27_5
; GFX9-NEXT:  .LBB27_3:
; GFX9-NEXT:    s_branch .LBB27_2
; GFX9-NEXT:  .LBB27_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s36
; GFX9-NEXT:    v_mov_b32_e32 v1, s37
; GFX9-NEXT:    v_mov_b32_e32 v2, s38
; GFX9-NEXT:    v_mov_b32_e32 v3, s39
; GFX9-NEXT:    v_mov_b32_e32 v4, s40
; GFX9-NEXT:    v_mov_b32_e32 v5, s41
; GFX9-NEXT:    v_mov_b32_e32 v6, s42
; GFX9-NEXT:    v_mov_b32_e32 v7, s43
; GFX9-NEXT:    v_mov_b32_e32 v8, s44
; GFX9-NEXT:    v_mov_b32_e32 v9, s45
; GFX9-NEXT:    v_mov_b32_e32 v10, s46
; GFX9-NEXT:    v_mov_b32_e32 v11, s47
; GFX9-NEXT:    v_mov_b32_e32 v12, s48
; GFX9-NEXT:    v_mov_b32_e32 v13, s49
; GFX9-NEXT:    v_mov_b32_e32 v14, s50
; GFX9-NEXT:    v_mov_b32_e32 v15, s51
; GFX9-NEXT:    v_mov_b32_e32 v16, s52
; GFX9-NEXT:    v_mov_b32_e32 v17, s53
; GFX9-NEXT:    v_mov_b32_e32 v18, s54
; GFX9-NEXT:    v_mov_b32_e32 v19, s55
; GFX9-NEXT:    v_mov_b32_e32 v20, s56
; GFX9-NEXT:    v_mov_b32_e32 v21, s57
; GFX9-NEXT:    v_mov_b32_e32 v22, s58
; GFX9-NEXT:    v_mov_b32_e32 v23, s59
; GFX9-NEXT:    v_mov_b32_e32 v24, s60
; GFX9-NEXT:    v_mov_b32_e32 v25, s61
; GFX9-NEXT:    v_mov_b32_e32 v26, s62
; GFX9-NEXT:    v_mov_b32_e32 v27, s63
; GFX9-NEXT:    v_mov_b32_e32 v28, s64
; GFX9-NEXT:    v_mov_b32_e32 v29, s65
; GFX9-NEXT:    v_mov_b32_e32 v30, s66
; GFX9-NEXT:    v_mov_b32_e32 v31, s67
; GFX9-NEXT:  .LBB27_5: ; %end
; GFX9-NEXT:    v_readlane_b32 s55, v32, 11
; GFX9-NEXT:    v_readlane_b32 s54, v32, 10
; GFX9-NEXT:    v_readlane_b32 s53, v32, 9
; GFX9-NEXT:    v_readlane_b32 s52, v32, 8
; GFX9-NEXT:    v_readlane_b32 s51, v32, 7
; GFX9-NEXT:    v_readlane_b32 s50, v32, 6
; GFX9-NEXT:    v_readlane_b32 s49, v32, 5
; GFX9-NEXT:    v_readlane_b32 s48, v32, 4
; GFX9-NEXT:    v_readlane_b32 s39, v32, 3
; GFX9-NEXT:    v_readlane_b32 s38, v32, 2
; GFX9-NEXT:    v_readlane_b32 s37, v32, 1
; GFX9-NEXT:    v_readlane_b32 s36, v32, 0
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v10f64_to_v20f32_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_xor_saveexec_b32 s4, -1
; GFX11-NEXT:    scratch_store_b32 off, v32, s32 ; 4-byte Folded Spill
; GFX11-NEXT:    s_mov_b32 exec_lo, s4
; GFX11-NEXT:    v_writelane_b32 v32, s36, 0
; GFX11-NEXT:    v_writelane_b32 v32, s37, 1
; GFX11-NEXT:    v_writelane_b32 v32, s38, 2
; GFX11-NEXT:    v_writelane_b32 v32, s39, 3
; GFX11-NEXT:    v_writelane_b32 v32, s48, 4
; GFX11-NEXT:    v_writelane_b32 v32, s49, 5
; GFX11-NEXT:    v_writelane_b32 v32, s50, 6
; GFX11-NEXT:    v_writelane_b32 v32, s51, 7
; GFX11-NEXT:    v_writelane_b32 v32, s52, 8
; GFX11-NEXT:    v_writelane_b32 v32, s53, 9
; GFX11-NEXT:    v_writelane_b32 v32, s54, 10
; GFX11-NEXT:    v_writelane_b32 v32, s55, 11
; GFX11-NEXT:    s_mov_b32 s36, s0
; GFX11-NEXT:    v_readfirstlane_b32 s0, v2
; GFX11-NEXT:    v_readfirstlane_b32 s55, v1
; GFX11-NEXT:    v_readfirstlane_b32 s54, v0
; GFX11-NEXT:    s_mov_b32 s53, s29
; GFX11-NEXT:    s_mov_b32 s52, s28
; GFX11-NEXT:    s_mov_b32 s51, s27
; GFX11-NEXT:    s_mov_b32 s50, s26
; GFX11-NEXT:    s_mov_b32 s49, s25
; GFX11-NEXT:    s_mov_b32 s48, s24
; GFX11-NEXT:    s_mov_b32 s47, s23
; GFX11-NEXT:    s_mov_b32 s46, s22
; GFX11-NEXT:    s_mov_b32 s45, s21
; GFX11-NEXT:    s_mov_b32 s44, s20
; GFX11-NEXT:    s_mov_b32 s43, s19
; GFX11-NEXT:    s_mov_b32 s42, s18
; GFX11-NEXT:    s_mov_b32 s41, s17
; GFX11-NEXT:    s_mov_b32 s40, s16
; GFX11-NEXT:    s_mov_b32 s39, s3
; GFX11-NEXT:    s_mov_b32 s38, s2
; GFX11-NEXT:    s_mov_b32 s37, s1
; GFX11-NEXT:    s_cmp_lg_u32 s0, 0
; GFX11-NEXT:    s_mov_b32 s0, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB27_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s0
; GFX11-NEXT:    s_cbranch_vccnz .LBB27_4
; GFX11-NEXT:  .LBB27_2: ; %cmp.true
; GFX11-NEXT:    v_add_f64 v[18:19], s[54:55], 1.0
; GFX11-NEXT:    v_add_f64 v[16:17], s[52:53], 1.0
; GFX11-NEXT:    v_add_f64 v[14:15], s[50:51], 1.0
; GFX11-NEXT:    v_add_f64 v[12:13], s[48:49], 1.0
; GFX11-NEXT:    v_add_f64 v[10:11], s[46:47], 1.0
; GFX11-NEXT:    v_add_f64 v[8:9], s[44:45], 1.0
; GFX11-NEXT:    v_add_f64 v[6:7], s[42:43], 1.0
; GFX11-NEXT:    v_add_f64 v[4:5], s[40:41], 1.0
; GFX11-NEXT:    v_add_f64 v[2:3], s[38:39], 1.0
; GFX11-NEXT:    v_add_f64 v[0:1], s[36:37], 1.0
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    s_branch .LBB27_5
; GFX11-NEXT:  .LBB27_3:
; GFX11-NEXT:    s_branch .LBB27_2
; GFX11-NEXT:  .LBB27_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s36 :: v_dual_mov_b32 v1, s37
; GFX11-NEXT:    v_dual_mov_b32 v2, s38 :: v_dual_mov_b32 v3, s39
; GFX11-NEXT:    v_dual_mov_b32 v4, s40 :: v_dual_mov_b32 v5, s41
; GFX11-NEXT:    v_dual_mov_b32 v6, s42 :: v_dual_mov_b32 v7, s43
; GFX11-NEXT:    v_dual_mov_b32 v8, s44 :: v_dual_mov_b32 v9, s45
; GFX11-NEXT:    v_dual_mov_b32 v10, s46 :: v_dual_mov_b32 v11, s47
; GFX11-NEXT:    v_dual_mov_b32 v12, s48 :: v_dual_mov_b32 v13, s49
; GFX11-NEXT:    v_dual_mov_b32 v14, s50 :: v_dual_mov_b32 v15, s51
; GFX11-NEXT:    v_dual_mov_b32 v16, s52 :: v_dual_mov_b32 v17, s53
; GFX11-NEXT:    v_dual_mov_b32 v18, s54 :: v_dual_mov_b32 v19, s55
; GFX11-NEXT:    v_dual_mov_b32 v20, s56 :: v_dual_mov_b32 v21, s57
; GFX11-NEXT:    v_dual_mov_b32 v22, s58 :: v_dual_mov_b32 v23, s59
; GFX11-NEXT:    v_dual_mov_b32 v24, s60 :: v_dual_mov_b32 v25, s61
; GFX11-NEXT:    v_dual_mov_b32 v26, s62 :: v_dual_mov_b32 v27, s63
; GFX11-NEXT:    v_dual_mov_b32 v28, s64 :: v_dual_mov_b32 v29, s65
; GFX11-NEXT:    v_dual_mov_b32 v30, s66 :: v_dual_mov_b32 v31, s67
; GFX11-NEXT:  .LBB27_5: ; %end
; GFX11-NEXT:    v_readlane_b32 s55, v32, 11
; GFX11-NEXT:    v_readlane_b32 s54, v32, 10
; GFX11-NEXT:    v_readlane_b32 s53, v32, 9
; GFX11-NEXT:    v_readlane_b32 s52, v32, 8
; GFX11-NEXT:    v_readlane_b32 s51, v32, 7
; GFX11-NEXT:    v_readlane_b32 s50, v32, 6
; GFX11-NEXT:    v_readlane_b32 s49, v32, 5
; GFX11-NEXT:    v_readlane_b32 s48, v32, 4
; GFX11-NEXT:    v_readlane_b32 s39, v32, 3
; GFX11-NEXT:    v_readlane_b32 s38, v32, 2
; GFX11-NEXT:    v_readlane_b32 s37, v32, 1
; GFX11-NEXT:    v_readlane_b32 s36, v32, 0
; GFX11-NEXT:    s_xor_saveexec_b32 s0, -1
; GFX11-NEXT:    scratch_load_b32 v32, off, s32 ; 4-byte Folded Reload
; GFX11-NEXT:    s_mov_b32 exec_lo, s0
; GFX11-NEXT:    s_waitcnt vmcnt(0)
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <10 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <10 x double> %a1 to <20 x float>
  br label %end

cmp.false:
  %a3 = bitcast <10 x double> %a to <20 x float>
  br label %end

end:
  %phi = phi <20 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <20 x float> %phi
}

define <40 x i16> @bitcast_v20f32_to_v40i16(<20 x float> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v20f32_to_v40i16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:    ; implicit-def: $vgpr31
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr29
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr26
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr25
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr24
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr30
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr28
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr27
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB28_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_alignbit_b32 v20, v19, v18, 16
; SI-NEXT:    v_alignbit_b32 v21, v17, v16, 16
; SI-NEXT:    v_alignbit_b32 v22, v15, v14, 16
; SI-NEXT:    v_alignbit_b32 v23, v13, v12, 16
; SI-NEXT:    v_alignbit_b32 v24, v11, v10, 16
; SI-NEXT:    v_alignbit_b32 v25, v9, v8, 16
; SI-NEXT:    v_alignbit_b32 v26, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v29, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v31, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v34, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v27, 16, v19
; SI-NEXT:    v_lshrrev_b32_e32 v28, 16, v17
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v15
; SI-NEXT:    v_lshrrev_b32_e32 v32, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v33, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v35, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v36, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v37, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v39, 16, v1
; SI-NEXT:  .LBB28_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB28_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; SI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; SI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; SI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; SI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; SI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; SI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; SI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; SI-NEXT:    v_add_f32_e32 v9, 1.0, v9
; SI-NEXT:    v_add_f32_e32 v8, 1.0, v8
; SI-NEXT:    v_add_f32_e32 v11, 1.0, v11
; SI-NEXT:    v_add_f32_e32 v10, 1.0, v10
; SI-NEXT:    v_add_f32_e32 v13, 1.0, v13
; SI-NEXT:    v_add_f32_e32 v12, 1.0, v12
; SI-NEXT:    v_add_f32_e32 v15, 1.0, v15
; SI-NEXT:    v_add_f32_e32 v14, 1.0, v14
; SI-NEXT:    v_add_f32_e32 v17, 1.0, v17
; SI-NEXT:    v_add_f32_e32 v16, 1.0, v16
; SI-NEXT:    v_add_f32_e32 v19, 1.0, v19
; SI-NEXT:    v_add_f32_e32 v18, 1.0, v18
; SI-NEXT:    v_alignbit_b32 v20, v19, v18, 16
; SI-NEXT:    v_alignbit_b32 v21, v17, v16, 16
; SI-NEXT:    v_alignbit_b32 v22, v15, v14, 16
; SI-NEXT:    v_alignbit_b32 v23, v13, v12, 16
; SI-NEXT:    v_alignbit_b32 v24, v11, v10, 16
; SI-NEXT:    v_alignbit_b32 v25, v9, v8, 16
; SI-NEXT:    v_alignbit_b32 v26, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v29, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v31, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v34, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v27, 16, v19
; SI-NEXT:    v_lshrrev_b32_e32 v28, 16, v17
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v15
; SI-NEXT:    v_lshrrev_b32_e32 v32, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v33, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v35, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v36, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v37, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v39, 16, v1
; SI-NEXT:  .LBB28_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v34, 16, v34
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v31, 16, v31
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v26, 16, v26
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; SI-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; SI-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v16
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; SI-NEXT:    v_or_b32_e32 v0, v0, v34
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v34, 16, v39
; SI-NEXT:    v_or_b32_e32 v2, v2, v31
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v31, 16, v38
; SI-NEXT:    v_or_b32_e32 v4, v4, v29
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v29, 16, v37
; SI-NEXT:    v_or_b32_e32 v6, v6, v26
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v26, 16, v36
; SI-NEXT:    v_or_b32_e32 v8, v8, v25
; SI-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; SI-NEXT:    v_lshlrev_b32_e32 v25, 16, v35
; SI-NEXT:    v_or_b32_e32 v10, v10, v24
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; SI-NEXT:    v_lshlrev_b32_e32 v24, 16, v33
; SI-NEXT:    v_or_b32_e32 v12, v12, v23
; SI-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v32
; SI-NEXT:    v_or_b32_e32 v14, v14, v22
; SI-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v30
; SI-NEXT:    v_or_b32_e32 v16, v16, v21
; SI-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v28
; SI-NEXT:    v_or_b32_e32 v18, v18, v20
; SI-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v27
; SI-NEXT:    v_or_b32_e32 v1, v1, v34
; SI-NEXT:    v_or_b32_e32 v3, v3, v31
; SI-NEXT:    v_or_b32_e32 v5, v5, v29
; SI-NEXT:    v_or_b32_e32 v7, v7, v26
; SI-NEXT:    v_or_b32_e32 v9, v9, v25
; SI-NEXT:    v_or_b32_e32 v11, v11, v24
; SI-NEXT:    v_or_b32_e32 v13, v13, v23
; SI-NEXT:    v_or_b32_e32 v15, v15, v22
; SI-NEXT:    v_or_b32_e32 v17, v17, v21
; SI-NEXT:    v_or_b32_e32 v19, v19, v20
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v20f32_to_v40i16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    ; implicit-def: $vgpr39
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr35
; VI-NEXT:    ; implicit-def: $vgpr34
; VI-NEXT:    ; implicit-def: $vgpr33
; VI-NEXT:    ; implicit-def: $vgpr32
; VI-NEXT:    ; implicit-def: $vgpr31
; VI-NEXT:    ; implicit-def: $vgpr30
; VI-NEXT:    ; implicit-def: $vgpr29
; VI-NEXT:    ; implicit-def: $vgpr28
; VI-NEXT:    ; implicit-def: $vgpr27
; VI-NEXT:    ; implicit-def: $vgpr26
; VI-NEXT:    ; implicit-def: $vgpr25
; VI-NEXT:    ; implicit-def: $vgpr24
; VI-NEXT:    ; implicit-def: $vgpr23
; VI-NEXT:    ; implicit-def: $vgpr22
; VI-NEXT:    ; implicit-def: $vgpr21
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB28_2
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; VI-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; VI-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; VI-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; VI-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; VI-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; VI-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; VI-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; VI-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; VI-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; VI-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; VI-NEXT:  .LBB28_2: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB28_4
; VI-NEXT:  ; %bb.3: ; %cmp.true
; VI-NEXT:    v_add_f32_e32 v19, 1.0, v19
; VI-NEXT:    v_add_f32_e32 v18, 1.0, v18
; VI-NEXT:    v_add_f32_e32 v17, 1.0, v17
; VI-NEXT:    v_add_f32_e32 v16, 1.0, v16
; VI-NEXT:    v_add_f32_e32 v15, 1.0, v15
; VI-NEXT:    v_add_f32_e32 v14, 1.0, v14
; VI-NEXT:    v_add_f32_e32 v13, 1.0, v13
; VI-NEXT:    v_add_f32_e32 v12, 1.0, v12
; VI-NEXT:    v_add_f32_e32 v11, 1.0, v11
; VI-NEXT:    v_add_f32_e32 v10, 1.0, v10
; VI-NEXT:    v_add_f32_e32 v9, 1.0, v9
; VI-NEXT:    v_add_f32_e32 v8, 1.0, v8
; VI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; VI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; VI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; VI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; VI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; VI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; VI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; VI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; VI-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; VI-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; VI-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; VI-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; VI-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; VI-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; VI-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; VI-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; VI-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; VI-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; VI-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; VI-NEXT:  .LBB28_4: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    v_lshlrev_b32_e32 v39, 16, v39
; VI-NEXT:    v_lshlrev_b32_e32 v38, 16, v38
; VI-NEXT:    v_lshlrev_b32_e32 v37, 16, v37
; VI-NEXT:    v_lshlrev_b32_e32 v36, 16, v36
; VI-NEXT:    v_lshlrev_b32_e32 v35, 16, v35
; VI-NEXT:    v_lshlrev_b32_e32 v34, 16, v34
; VI-NEXT:    v_lshlrev_b32_e32 v33, 16, v33
; VI-NEXT:    v_lshlrev_b32_e32 v32, 16, v32
; VI-NEXT:    v_lshlrev_b32_e32 v31, 16, v31
; VI-NEXT:    v_lshlrev_b32_e32 v30, 16, v30
; VI-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; VI-NEXT:    v_lshlrev_b32_e32 v28, 16, v28
; VI-NEXT:    v_lshlrev_b32_e32 v27, 16, v27
; VI-NEXT:    v_lshlrev_b32_e32 v26, 16, v26
; VI-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; VI-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; VI-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; VI-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; VI-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; VI-NEXT:    v_or_b32_sdwa v0, v0, v39 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v1, v1, v38 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v2, v2, v37 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v3, v3, v36 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v4, v4, v35 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v5, v5, v34 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v6, v6, v33 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v7, v7, v32 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v8, v8, v31 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v9, v9, v30 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v10, v10, v29 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v11, v11, v28 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v12, v12, v27 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v13, v13, v26 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v14, v14, v25 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v15, v15, v24 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v16, v16, v23 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v17, v17, v22 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v18, v18, v21 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v19, v19, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v20f32_to_v40i16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    ; implicit-def: $vgpr39
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr35
; GFX9-NEXT:    ; implicit-def: $vgpr34
; GFX9-NEXT:    ; implicit-def: $vgpr33
; GFX9-NEXT:    ; implicit-def: $vgpr32
; GFX9-NEXT:    ; implicit-def: $vgpr31
; GFX9-NEXT:    ; implicit-def: $vgpr30
; GFX9-NEXT:    ; implicit-def: $vgpr29
; GFX9-NEXT:    ; implicit-def: $vgpr28
; GFX9-NEXT:    ; implicit-def: $vgpr27
; GFX9-NEXT:    ; implicit-def: $vgpr26
; GFX9-NEXT:    ; implicit-def: $vgpr25
; GFX9-NEXT:    ; implicit-def: $vgpr24
; GFX9-NEXT:    ; implicit-def: $vgpr23
; GFX9-NEXT:    ; implicit-def: $vgpr22
; GFX9-NEXT:    ; implicit-def: $vgpr21
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB28_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX9-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX9-NEXT:  .LBB28_2: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB28_4
; GFX9-NEXT:  ; %bb.3: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e32 v19, 1.0, v19
; GFX9-NEXT:    v_add_f32_e32 v18, 1.0, v18
; GFX9-NEXT:    v_add_f32_e32 v17, 1.0, v17
; GFX9-NEXT:    v_add_f32_e32 v16, 1.0, v16
; GFX9-NEXT:    v_add_f32_e32 v15, 1.0, v15
; GFX9-NEXT:    v_add_f32_e32 v14, 1.0, v14
; GFX9-NEXT:    v_add_f32_e32 v13, 1.0, v13
; GFX9-NEXT:    v_add_f32_e32 v12, 1.0, v12
; GFX9-NEXT:    v_add_f32_e32 v11, 1.0, v11
; GFX9-NEXT:    v_add_f32_e32 v10, 1.0, v10
; GFX9-NEXT:    v_add_f32_e32 v9, 1.0, v9
; GFX9-NEXT:    v_add_f32_e32 v8, 1.0, v8
; GFX9-NEXT:    v_add_f32_e32 v7, 1.0, v7
; GFX9-NEXT:    v_add_f32_e32 v6, 1.0, v6
; GFX9-NEXT:    v_add_f32_e32 v5, 1.0, v5
; GFX9-NEXT:    v_add_f32_e32 v4, 1.0, v4
; GFX9-NEXT:    v_add_f32_e32 v3, 1.0, v3
; GFX9-NEXT:    v_add_f32_e32 v2, 1.0, v2
; GFX9-NEXT:    v_add_f32_e32 v1, 1.0, v1
; GFX9-NEXT:    v_add_f32_e32 v0, 1.0, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX9-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX9-NEXT:  .LBB28_4: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_mov_b32 s4, 0x5040100
; GFX9-NEXT:    v_perm_b32 v0, v39, v0, s4
; GFX9-NEXT:    v_perm_b32 v1, v38, v1, s4
; GFX9-NEXT:    v_perm_b32 v2, v37, v2, s4
; GFX9-NEXT:    v_perm_b32 v3, v36, v3, s4
; GFX9-NEXT:    v_perm_b32 v4, v35, v4, s4
; GFX9-NEXT:    v_perm_b32 v5, v34, v5, s4
; GFX9-NEXT:    v_perm_b32 v6, v33, v6, s4
; GFX9-NEXT:    v_perm_b32 v7, v32, v7, s4
; GFX9-NEXT:    v_perm_b32 v8, v31, v8, s4
; GFX9-NEXT:    v_perm_b32 v9, v30, v9, s4
; GFX9-NEXT:    v_perm_b32 v10, v29, v10, s4
; GFX9-NEXT:    v_perm_b32 v11, v28, v11, s4
; GFX9-NEXT:    v_perm_b32 v12, v27, v12, s4
; GFX9-NEXT:    v_perm_b32 v13, v26, v13, s4
; GFX9-NEXT:    v_perm_b32 v14, v25, v14, s4
; GFX9-NEXT:    v_perm_b32 v15, v24, v15, s4
; GFX9-NEXT:    v_perm_b32 v16, v23, v16, s4
; GFX9-NEXT:    v_perm_b32 v17, v22, v17, s4
; GFX9-NEXT:    v_perm_b32 v18, v21, v18, s4
; GFX9-NEXT:    v_perm_b32 v19, v20, v19, s4
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v20f32_to_v40i16:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB28_2
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v19, 1.0, v19 :: v_dual_add_f32 v18, 1.0, v18
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v17, 1.0, v17 :: v_dual_add_f32 v16, 1.0, v16
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v15, 1.0, v15 :: v_dual_add_f32 v14, 1.0, v14
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v13, 1.0, v13 :: v_dual_add_f32 v12, 1.0, v12
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v11, 1.0, v11 :: v_dual_add_f32 v10, 1.0, v10
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v9, 1.0, v9 :: v_dual_add_f32 v8, 1.0, v8
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v7, 1.0, v7 :: v_dual_add_f32 v6, 1.0, v6
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v5, 1.0, v5 :: v_dual_add_f32 v4, 1.0, v4
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v3, 1.0, v3 :: v_dual_add_f32 v2, 1.0, v2
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v1, 1.0, v1 :: v_dual_add_f32 v0, 1.0, v0
; GFX11-TRUE16-NEXT:  .LBB28_2: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v20f32_to_v40i16:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr39
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr38
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr37
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr36
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr35
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr34
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr33
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr32
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr31
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr30
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr29
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr28
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr27
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr26
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr25
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr24
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr23
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr22
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr21
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB28_2
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX11-FAKE16-NEXT:  .LBB28_2: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB28_4
; GFX11-FAKE16-NEXT:  ; %bb.3: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v19, 1.0, v19 :: v_dual_add_f32 v18, 1.0, v18
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v17, 1.0, v17 :: v_dual_add_f32 v16, 1.0, v16
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v15, 1.0, v15 :: v_dual_add_f32 v14, 1.0, v14
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v13, 1.0, v13 :: v_dual_add_f32 v12, 1.0, v12
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v11, 1.0, v11 :: v_dual_add_f32 v10, 1.0, v10
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v9, 1.0, v9 :: v_dual_add_f32 v8, 1.0, v8
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v7, 1.0, v7 :: v_dual_add_f32 v6, 1.0, v6
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v5, 1.0, v5 :: v_dual_add_f32 v4, 1.0, v4
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v3, 1.0, v3 :: v_dual_add_f32 v2, 1.0, v2
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v1, 1.0, v1 :: v_dual_add_f32 v0, 1.0, v0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX11-FAKE16-NEXT:  .LBB28_4: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v39, v0, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v38, v1, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v37, v2, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v36, v3, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v35, v4, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v34, v5, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v33, v6, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v32, v7, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, v31, v8, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, v30, v9, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, v29, v10, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, v28, v11, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, v27, v12, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, v26, v13, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v14, v25, v14, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v15, v24, v15, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v16, v23, v16, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v17, v22, v17, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v18, v21, v18, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v19, v20, v19, 0x5040100
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <20 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <20 x float> %a1 to <40 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <20 x float> %a to <40 x i16>
  br label %end

end:
  %phi = phi <40 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <40 x i16> %phi
}

define inreg <40 x i16> @bitcast_v20f32_to_v40i16_scalar(<20 x float> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v20f32_to_v40i16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_readfirstlane_b32 s8, v6
; SI-NEXT:    v_readfirstlane_b32 s5, v5
; SI-NEXT:    v_readfirstlane_b32 s4, v4
; SI-NEXT:    v_readfirstlane_b32 s7, v3
; SI-NEXT:    v_readfirstlane_b32 s6, v2
; SI-NEXT:    v_readfirstlane_b32 s9, v1
; SI-NEXT:    s_cmp_lg_u32 s8, 0
; SI-NEXT:    v_readfirstlane_b32 s8, v0
; SI-NEXT:    s_cbranch_scc0 .LBB29_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_lshr_b32 s89, s5, 16
; SI-NEXT:    s_lshr_b32 s88, s7, 16
; SI-NEXT:    s_lshr_b32 s79, s9, 16
; SI-NEXT:    s_lshr_b32 s78, s29, 16
; SI-NEXT:    s_lshr_b32 s77, s27, 16
; SI-NEXT:    s_lshr_b32 s76, s25, 16
; SI-NEXT:    s_lshr_b32 s75, s23, 16
; SI-NEXT:    s_lshr_b32 s74, s21, 16
; SI-NEXT:    s_lshr_b32 s73, s19, 16
; SI-NEXT:    s_lshr_b32 s72, s17, 16
; SI-NEXT:    s_lshr_b64 s[10:11], s[4:5], 16
; SI-NEXT:    s_lshr_b64 s[12:13], s[6:7], 16
; SI-NEXT:    s_lshr_b64 s[14:15], s[8:9], 16
; SI-NEXT:    s_lshr_b64 s[40:41], s[28:29], 16
; SI-NEXT:    s_lshr_b64 s[42:43], s[26:27], 16
; SI-NEXT:    s_lshr_b64 s[44:45], s[24:25], 16
; SI-NEXT:    s_lshr_b64 s[46:47], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[56:57], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[58:59], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[60:61], s[16:17], 16
; SI-NEXT:    s_cbranch_execnz .LBB29_4
; SI-NEXT:  .LBB29_2: ; %cmp.true
; SI-NEXT:    v_add_f32_e64 v19, s5, 1.0
; SI-NEXT:    v_add_f32_e64 v18, s4, 1.0
; SI-NEXT:    v_add_f32_e64 v17, s7, 1.0
; SI-NEXT:    v_add_f32_e64 v16, s6, 1.0
; SI-NEXT:    v_lshr_b64 v[20:21], v[18:19], 16
; SI-NEXT:    v_add_f32_e64 v15, s9, 1.0
; SI-NEXT:    v_add_f32_e64 v14, s8, 1.0
; SI-NEXT:    v_lshr_b64 v[21:22], v[16:17], 16
; SI-NEXT:    v_add_f32_e64 v13, s29, 1.0
; SI-NEXT:    v_add_f32_e64 v12, s28, 1.0
; SI-NEXT:    v_lshr_b64 v[22:23], v[14:15], 16
; SI-NEXT:    v_add_f32_e64 v11, s27, 1.0
; SI-NEXT:    v_add_f32_e64 v10, s26, 1.0
; SI-NEXT:    v_lshr_b64 v[23:24], v[12:13], 16
; SI-NEXT:    v_add_f32_e64 v9, s25, 1.0
; SI-NEXT:    v_add_f32_e64 v8, s24, 1.0
; SI-NEXT:    v_lshr_b64 v[24:25], v[10:11], 16
; SI-NEXT:    v_add_f32_e64 v7, s23, 1.0
; SI-NEXT:    v_add_f32_e64 v6, s22, 1.0
; SI-NEXT:    v_lshr_b64 v[25:26], v[8:9], 16
; SI-NEXT:    v_add_f32_e64 v5, s21, 1.0
; SI-NEXT:    v_add_f32_e64 v4, s20, 1.0
; SI-NEXT:    v_lshr_b64 v[26:27], v[6:7], 16
; SI-NEXT:    v_add_f32_e64 v3, s19, 1.0
; SI-NEXT:    v_add_f32_e64 v2, s18, 1.0
; SI-NEXT:    v_lshr_b64 v[27:28], v[4:5], 16
; SI-NEXT:    v_add_f32_e64 v1, s17, 1.0
; SI-NEXT:    v_add_f32_e64 v0, s16, 1.0
; SI-NEXT:    v_lshr_b64 v[28:29], v[2:3], 16
; SI-NEXT:    v_lshr_b64 v[29:30], v[0:1], 16
; SI-NEXT:    v_lshrrev_b32_e32 v31, 16, v19
; SI-NEXT:    v_lshrrev_b32_e32 v32, 16, v17
; SI-NEXT:    v_lshrrev_b32_e32 v33, 16, v15
; SI-NEXT:    v_lshrrev_b32_e32 v34, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v35, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v36, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v37, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v38, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v39, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v48, 16, v1
; SI-NEXT:    s_branch .LBB29_5
; SI-NEXT:  .LBB29_3:
; SI-NEXT:    ; implicit-def: $sgpr60
; SI-NEXT:    ; implicit-def: $sgpr72
; SI-NEXT:    ; implicit-def: $sgpr58
; SI-NEXT:    ; implicit-def: $sgpr73
; SI-NEXT:    ; implicit-def: $sgpr56
; SI-NEXT:    ; implicit-def: $sgpr74
; SI-NEXT:    ; implicit-def: $sgpr46
; SI-NEXT:    ; implicit-def: $sgpr75
; SI-NEXT:    ; implicit-def: $sgpr44
; SI-NEXT:    ; implicit-def: $sgpr76
; SI-NEXT:    ; implicit-def: $sgpr42
; SI-NEXT:    ; implicit-def: $sgpr77
; SI-NEXT:    ; implicit-def: $sgpr40
; SI-NEXT:    ; implicit-def: $sgpr78
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr79
; SI-NEXT:    ; implicit-def: $sgpr12
; SI-NEXT:    ; implicit-def: $sgpr88
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr89
; SI-NEXT:    s_branch .LBB29_2
; SI-NEXT:  .LBB29_4:
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v2, s18
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v4, s20
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v6, s22
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    v_mov_b32_e32 v8, s24
; SI-NEXT:    v_mov_b32_e32 v9, s25
; SI-NEXT:    v_mov_b32_e32 v10, s26
; SI-NEXT:    v_mov_b32_e32 v11, s27
; SI-NEXT:    v_mov_b32_e32 v12, s28
; SI-NEXT:    v_mov_b32_e32 v13, s29
; SI-NEXT:    v_mov_b32_e32 v14, s8
; SI-NEXT:    v_mov_b32_e32 v15, s9
; SI-NEXT:    v_mov_b32_e32 v16, s6
; SI-NEXT:    v_mov_b32_e32 v17, s7
; SI-NEXT:    v_mov_b32_e32 v18, s4
; SI-NEXT:    v_mov_b32_e32 v19, s5
; SI-NEXT:    v_mov_b32_e32 v48, s72
; SI-NEXT:    v_mov_b32_e32 v39, s73
; SI-NEXT:    v_mov_b32_e32 v38, s74
; SI-NEXT:    v_mov_b32_e32 v37, s75
; SI-NEXT:    v_mov_b32_e32 v36, s76
; SI-NEXT:    v_mov_b32_e32 v35, s77
; SI-NEXT:    v_mov_b32_e32 v34, s78
; SI-NEXT:    v_mov_b32_e32 v33, s79
; SI-NEXT:    v_mov_b32_e32 v32, s88
; SI-NEXT:    v_mov_b32_e32 v31, s89
; SI-NEXT:    v_mov_b32_e32 v20, s10
; SI-NEXT:    v_mov_b32_e32 v21, s12
; SI-NEXT:    v_mov_b32_e32 v22, s14
; SI-NEXT:    v_mov_b32_e32 v23, s40
; SI-NEXT:    v_mov_b32_e32 v24, s42
; SI-NEXT:    v_mov_b32_e32 v25, s44
; SI-NEXT:    v_mov_b32_e32 v26, s46
; SI-NEXT:    v_mov_b32_e32 v27, s56
; SI-NEXT:    v_mov_b32_e32 v28, s58
; SI-NEXT:    v_mov_b32_e32 v29, s60
; SI-NEXT:  .LBB29_5: ; %end
; SI-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v28, 16, v28
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v27, 16, v27
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_lshlrev_b32_e32 v26, 16, v26
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; SI-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v16
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; SI-NEXT:    v_or_b32_e32 v0, v0, v29
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v29, 16, v48
; SI-NEXT:    v_or_b32_e32 v2, v2, v28
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v28, 16, v39
; SI-NEXT:    v_or_b32_e32 v4, v4, v27
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v27, 16, v38
; SI-NEXT:    v_or_b32_e32 v6, v6, v26
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v26, 16, v37
; SI-NEXT:    v_or_b32_e32 v8, v8, v25
; SI-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; SI-NEXT:    v_lshlrev_b32_e32 v25, 16, v36
; SI-NEXT:    v_or_b32_e32 v10, v10, v24
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; SI-NEXT:    v_lshlrev_b32_e32 v24, 16, v35
; SI-NEXT:    v_or_b32_e32 v12, v12, v23
; SI-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v34
; SI-NEXT:    v_or_b32_e32 v14, v14, v22
; SI-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v33
; SI-NEXT:    v_or_b32_e32 v16, v16, v21
; SI-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v32
; SI-NEXT:    v_or_b32_e32 v18, v18, v20
; SI-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v31
; SI-NEXT:    v_or_b32_e32 v1, v1, v29
; SI-NEXT:    v_or_b32_e32 v3, v3, v28
; SI-NEXT:    v_or_b32_e32 v5, v5, v27
; SI-NEXT:    v_or_b32_e32 v7, v7, v26
; SI-NEXT:    v_or_b32_e32 v9, v9, v25
; SI-NEXT:    v_or_b32_e32 v11, v11, v24
; SI-NEXT:    v_or_b32_e32 v13, v13, v23
; SI-NEXT:    v_or_b32_e32 v15, v15, v22
; SI-NEXT:    v_or_b32_e32 v17, v17, v21
; SI-NEXT:    v_or_b32_e32 v19, v19, v20
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v20f32_to_v40i16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    v_readfirstlane_b32 s6, v5
; VI-NEXT:    v_readfirstlane_b32 s7, v4
; VI-NEXT:    v_readfirstlane_b32 s8, v3
; VI-NEXT:    v_readfirstlane_b32 s9, v2
; VI-NEXT:    v_readfirstlane_b32 s10, v1
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    v_readfirstlane_b32 s11, v0
; VI-NEXT:    s_cbranch_scc0 .LBB29_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_lshr_b32 s12, s6, 16
; VI-NEXT:    s_lshr_b32 s13, s7, 16
; VI-NEXT:    s_lshr_b32 s14, s8, 16
; VI-NEXT:    s_lshr_b32 s15, s9, 16
; VI-NEXT:    s_lshr_b32 s40, s10, 16
; VI-NEXT:    s_lshr_b32 s41, s11, 16
; VI-NEXT:    s_lshr_b32 s42, s29, 16
; VI-NEXT:    s_lshr_b32 s43, s28, 16
; VI-NEXT:    s_lshr_b32 s44, s27, 16
; VI-NEXT:    s_lshr_b32 s45, s26, 16
; VI-NEXT:    s_lshr_b32 s46, s25, 16
; VI-NEXT:    s_lshr_b32 s47, s24, 16
; VI-NEXT:    s_lshr_b32 s56, s23, 16
; VI-NEXT:    s_lshr_b32 s57, s22, 16
; VI-NEXT:    s_lshr_b32 s58, s21, 16
; VI-NEXT:    s_lshr_b32 s59, s20, 16
; VI-NEXT:    s_lshr_b32 s60, s19, 16
; VI-NEXT:    s_lshr_b32 s61, s18, 16
; VI-NEXT:    s_lshr_b32 s62, s17, 16
; VI-NEXT:    s_lshr_b32 s63, s16, 16
; VI-NEXT:    s_cbranch_execnz .LBB29_4
; VI-NEXT:  .LBB29_2: ; %cmp.true
; VI-NEXT:    v_add_f32_e64 v19, s6, 1.0
; VI-NEXT:    v_add_f32_e64 v18, s7, 1.0
; VI-NEXT:    v_add_f32_e64 v17, s8, 1.0
; VI-NEXT:    v_add_f32_e64 v16, s9, 1.0
; VI-NEXT:    v_add_f32_e64 v15, s10, 1.0
; VI-NEXT:    v_add_f32_e64 v14, s11, 1.0
; VI-NEXT:    v_add_f32_e64 v13, s29, 1.0
; VI-NEXT:    v_add_f32_e64 v12, s28, 1.0
; VI-NEXT:    v_add_f32_e64 v11, s27, 1.0
; VI-NEXT:    v_add_f32_e64 v10, s26, 1.0
; VI-NEXT:    v_add_f32_e64 v9, s25, 1.0
; VI-NEXT:    v_add_f32_e64 v8, s24, 1.0
; VI-NEXT:    v_add_f32_e64 v7, s23, 1.0
; VI-NEXT:    v_add_f32_e64 v6, s22, 1.0
; VI-NEXT:    v_add_f32_e64 v5, s21, 1.0
; VI-NEXT:    v_add_f32_e64 v4, s20, 1.0
; VI-NEXT:    v_add_f32_e64 v3, s19, 1.0
; VI-NEXT:    v_add_f32_e64 v2, s18, 1.0
; VI-NEXT:    v_add_f32_e64 v1, s17, 1.0
; VI-NEXT:    v_add_f32_e64 v0, s16, 1.0
; VI-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; VI-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; VI-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; VI-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; VI-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; VI-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; VI-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; VI-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; VI-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; VI-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; VI-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; VI-NEXT:    s_branch .LBB29_5
; VI-NEXT:  .LBB29_3:
; VI-NEXT:    ; implicit-def: $sgpr63
; VI-NEXT:    ; implicit-def: $sgpr62
; VI-NEXT:    ; implicit-def: $sgpr61
; VI-NEXT:    ; implicit-def: $sgpr60
; VI-NEXT:    ; implicit-def: $sgpr59
; VI-NEXT:    ; implicit-def: $sgpr58
; VI-NEXT:    ; implicit-def: $sgpr57
; VI-NEXT:    ; implicit-def: $sgpr56
; VI-NEXT:    ; implicit-def: $sgpr47
; VI-NEXT:    ; implicit-def: $sgpr46
; VI-NEXT:    ; implicit-def: $sgpr45
; VI-NEXT:    ; implicit-def: $sgpr44
; VI-NEXT:    ; implicit-def: $sgpr43
; VI-NEXT:    ; implicit-def: $sgpr42
; VI-NEXT:    ; implicit-def: $sgpr41
; VI-NEXT:    ; implicit-def: $sgpr40
; VI-NEXT:    ; implicit-def: $sgpr15
; VI-NEXT:    ; implicit-def: $sgpr14
; VI-NEXT:    ; implicit-def: $sgpr13
; VI-NEXT:    ; implicit-def: $sgpr12
; VI-NEXT:    s_branch .LBB29_2
; VI-NEXT:  .LBB29_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    v_mov_b32_e32 v8, s24
; VI-NEXT:    v_mov_b32_e32 v9, s25
; VI-NEXT:    v_mov_b32_e32 v10, s26
; VI-NEXT:    v_mov_b32_e32 v11, s27
; VI-NEXT:    v_mov_b32_e32 v12, s28
; VI-NEXT:    v_mov_b32_e32 v13, s29
; VI-NEXT:    v_mov_b32_e32 v14, s11
; VI-NEXT:    v_mov_b32_e32 v15, s10
; VI-NEXT:    v_mov_b32_e32 v16, s9
; VI-NEXT:    v_mov_b32_e32 v17, s8
; VI-NEXT:    v_mov_b32_e32 v18, s7
; VI-NEXT:    v_mov_b32_e32 v19, s6
; VI-NEXT:    v_mov_b32_e32 v39, s63
; VI-NEXT:    v_mov_b32_e32 v38, s62
; VI-NEXT:    v_mov_b32_e32 v37, s61
; VI-NEXT:    v_mov_b32_e32 v36, s60
; VI-NEXT:    v_mov_b32_e32 v35, s59
; VI-NEXT:    v_mov_b32_e32 v34, s58
; VI-NEXT:    v_mov_b32_e32 v33, s57
; VI-NEXT:    v_mov_b32_e32 v32, s56
; VI-NEXT:    v_mov_b32_e32 v31, s47
; VI-NEXT:    v_mov_b32_e32 v30, s46
; VI-NEXT:    v_mov_b32_e32 v29, s45
; VI-NEXT:    v_mov_b32_e32 v28, s44
; VI-NEXT:    v_mov_b32_e32 v27, s43
; VI-NEXT:    v_mov_b32_e32 v26, s42
; VI-NEXT:    v_mov_b32_e32 v25, s41
; VI-NEXT:    v_mov_b32_e32 v24, s40
; VI-NEXT:    v_mov_b32_e32 v23, s15
; VI-NEXT:    v_mov_b32_e32 v22, s14
; VI-NEXT:    v_mov_b32_e32 v21, s13
; VI-NEXT:    v_mov_b32_e32 v20, s12
; VI-NEXT:  .LBB29_5: ; %end
; VI-NEXT:    v_lshlrev_b32_e32 v39, 16, v39
; VI-NEXT:    v_lshlrev_b32_e32 v38, 16, v38
; VI-NEXT:    v_lshlrev_b32_e32 v37, 16, v37
; VI-NEXT:    v_lshlrev_b32_e32 v36, 16, v36
; VI-NEXT:    v_lshlrev_b32_e32 v35, 16, v35
; VI-NEXT:    v_lshlrev_b32_e32 v34, 16, v34
; VI-NEXT:    v_lshlrev_b32_e32 v33, 16, v33
; VI-NEXT:    v_lshlrev_b32_e32 v32, 16, v32
; VI-NEXT:    v_lshlrev_b32_e32 v31, 16, v31
; VI-NEXT:    v_lshlrev_b32_e32 v30, 16, v30
; VI-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; VI-NEXT:    v_lshlrev_b32_e32 v28, 16, v28
; VI-NEXT:    v_lshlrev_b32_e32 v27, 16, v27
; VI-NEXT:    v_lshlrev_b32_e32 v26, 16, v26
; VI-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; VI-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; VI-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; VI-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; VI-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; VI-NEXT:    v_or_b32_sdwa v0, v0, v39 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v1, v1, v38 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v2, v2, v37 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v3, v3, v36 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v4, v4, v35 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v5, v5, v34 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v6, v6, v33 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v7, v7, v32 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v8, v8, v31 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v9, v9, v30 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v10, v10, v29 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v11, v11, v28 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v12, v12, v27 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v13, v13, v26 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v14, v14, v25 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v15, v15, v24 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v16, v16, v23 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v17, v17, v22 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v18, v18, v21 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v19, v19, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v20f32_to_v40i16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_readfirstlane_b32 s4, v6
; GFX9-NEXT:    v_readfirstlane_b32 s6, v5
; GFX9-NEXT:    v_readfirstlane_b32 s7, v4
; GFX9-NEXT:    v_readfirstlane_b32 s8, v3
; GFX9-NEXT:    v_readfirstlane_b32 s9, v2
; GFX9-NEXT:    v_readfirstlane_b32 s10, v1
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    v_readfirstlane_b32 s11, v0
; GFX9-NEXT:    s_cbranch_scc0 .LBB29_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_lshr_b32 s12, s6, 16
; GFX9-NEXT:    s_lshr_b32 s13, s7, 16
; GFX9-NEXT:    s_lshr_b32 s14, s8, 16
; GFX9-NEXT:    s_lshr_b32 s15, s9, 16
; GFX9-NEXT:    s_lshr_b32 s40, s10, 16
; GFX9-NEXT:    s_lshr_b32 s41, s11, 16
; GFX9-NEXT:    s_lshr_b32 s42, s29, 16
; GFX9-NEXT:    s_lshr_b32 s43, s28, 16
; GFX9-NEXT:    s_lshr_b32 s44, s27, 16
; GFX9-NEXT:    s_lshr_b32 s45, s26, 16
; GFX9-NEXT:    s_lshr_b32 s46, s25, 16
; GFX9-NEXT:    s_lshr_b32 s47, s24, 16
; GFX9-NEXT:    s_lshr_b32 s56, s23, 16
; GFX9-NEXT:    s_lshr_b32 s57, s22, 16
; GFX9-NEXT:    s_lshr_b32 s58, s21, 16
; GFX9-NEXT:    s_lshr_b32 s59, s20, 16
; GFX9-NEXT:    s_lshr_b32 s60, s19, 16
; GFX9-NEXT:    s_lshr_b32 s61, s18, 16
; GFX9-NEXT:    s_lshr_b32 s62, s17, 16
; GFX9-NEXT:    s_lshr_b32 s63, s16, 16
; GFX9-NEXT:    s_cbranch_execnz .LBB29_4
; GFX9-NEXT:  .LBB29_2: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e64 v19, s6, 1.0
; GFX9-NEXT:    v_add_f32_e64 v18, s7, 1.0
; GFX9-NEXT:    v_add_f32_e64 v17, s8, 1.0
; GFX9-NEXT:    v_add_f32_e64 v16, s9, 1.0
; GFX9-NEXT:    v_add_f32_e64 v15, s10, 1.0
; GFX9-NEXT:    v_add_f32_e64 v14, s11, 1.0
; GFX9-NEXT:    v_add_f32_e64 v13, s29, 1.0
; GFX9-NEXT:    v_add_f32_e64 v12, s28, 1.0
; GFX9-NEXT:    v_add_f32_e64 v11, s27, 1.0
; GFX9-NEXT:    v_add_f32_e64 v10, s26, 1.0
; GFX9-NEXT:    v_add_f32_e64 v9, s25, 1.0
; GFX9-NEXT:    v_add_f32_e64 v8, s24, 1.0
; GFX9-NEXT:    v_add_f32_e64 v7, s23, 1.0
; GFX9-NEXT:    v_add_f32_e64 v6, s22, 1.0
; GFX9-NEXT:    v_add_f32_e64 v5, s21, 1.0
; GFX9-NEXT:    v_add_f32_e64 v4, s20, 1.0
; GFX9-NEXT:    v_add_f32_e64 v3, s19, 1.0
; GFX9-NEXT:    v_add_f32_e64 v2, s18, 1.0
; GFX9-NEXT:    v_add_f32_e64 v1, s17, 1.0
; GFX9-NEXT:    v_add_f32_e64 v0, s16, 1.0
; GFX9-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX9-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX9-NEXT:    s_branch .LBB29_5
; GFX9-NEXT:  .LBB29_3:
; GFX9-NEXT:    ; implicit-def: $sgpr63
; GFX9-NEXT:    ; implicit-def: $sgpr62
; GFX9-NEXT:    ; implicit-def: $sgpr61
; GFX9-NEXT:    ; implicit-def: $sgpr60
; GFX9-NEXT:    ; implicit-def: $sgpr59
; GFX9-NEXT:    ; implicit-def: $sgpr58
; GFX9-NEXT:    ; implicit-def: $sgpr57
; GFX9-NEXT:    ; implicit-def: $sgpr56
; GFX9-NEXT:    ; implicit-def: $sgpr47
; GFX9-NEXT:    ; implicit-def: $sgpr46
; GFX9-NEXT:    ; implicit-def: $sgpr45
; GFX9-NEXT:    ; implicit-def: $sgpr44
; GFX9-NEXT:    ; implicit-def: $sgpr43
; GFX9-NEXT:    ; implicit-def: $sgpr42
; GFX9-NEXT:    ; implicit-def: $sgpr41
; GFX9-NEXT:    ; implicit-def: $sgpr40
; GFX9-NEXT:    ; implicit-def: $sgpr15
; GFX9-NEXT:    ; implicit-def: $sgpr14
; GFX9-NEXT:    ; implicit-def: $sgpr13
; GFX9-NEXT:    ; implicit-def: $sgpr12
; GFX9-NEXT:    s_branch .LBB29_2
; GFX9-NEXT:  .LBB29_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    v_mov_b32_e32 v8, s24
; GFX9-NEXT:    v_mov_b32_e32 v9, s25
; GFX9-NEXT:    v_mov_b32_e32 v10, s26
; GFX9-NEXT:    v_mov_b32_e32 v11, s27
; GFX9-NEXT:    v_mov_b32_e32 v12, s28
; GFX9-NEXT:    v_mov_b32_e32 v13, s29
; GFX9-NEXT:    v_mov_b32_e32 v14, s11
; GFX9-NEXT:    v_mov_b32_e32 v15, s10
; GFX9-NEXT:    v_mov_b32_e32 v16, s9
; GFX9-NEXT:    v_mov_b32_e32 v17, s8
; GFX9-NEXT:    v_mov_b32_e32 v18, s7
; GFX9-NEXT:    v_mov_b32_e32 v19, s6
; GFX9-NEXT:    v_mov_b32_e32 v39, s63
; GFX9-NEXT:    v_mov_b32_e32 v38, s62
; GFX9-NEXT:    v_mov_b32_e32 v37, s61
; GFX9-NEXT:    v_mov_b32_e32 v36, s60
; GFX9-NEXT:    v_mov_b32_e32 v35, s59
; GFX9-NEXT:    v_mov_b32_e32 v34, s58
; GFX9-NEXT:    v_mov_b32_e32 v33, s57
; GFX9-NEXT:    v_mov_b32_e32 v32, s56
; GFX9-NEXT:    v_mov_b32_e32 v31, s47
; GFX9-NEXT:    v_mov_b32_e32 v30, s46
; GFX9-NEXT:    v_mov_b32_e32 v29, s45
; GFX9-NEXT:    v_mov_b32_e32 v28, s44
; GFX9-NEXT:    v_mov_b32_e32 v27, s43
; GFX9-NEXT:    v_mov_b32_e32 v26, s42
; GFX9-NEXT:    v_mov_b32_e32 v25, s41
; GFX9-NEXT:    v_mov_b32_e32 v24, s40
; GFX9-NEXT:    v_mov_b32_e32 v23, s15
; GFX9-NEXT:    v_mov_b32_e32 v22, s14
; GFX9-NEXT:    v_mov_b32_e32 v21, s13
; GFX9-NEXT:    v_mov_b32_e32 v20, s12
; GFX9-NEXT:  .LBB29_5: ; %end
; GFX9-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; GFX9-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX9-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GFX9-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX9-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; GFX9-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; GFX9-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; GFX9-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; GFX9-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; GFX9-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; GFX9-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; GFX9-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; GFX9-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; GFX9-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; GFX9-NEXT:    v_and_b32_e32 v16, 0xffff, v16
; GFX9-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; GFX9-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; GFX9-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; GFX9-NEXT:    v_lshl_or_b32 v0, v39, 16, v0
; GFX9-NEXT:    v_lshl_or_b32 v1, v38, 16, v1
; GFX9-NEXT:    v_lshl_or_b32 v2, v37, 16, v2
; GFX9-NEXT:    v_lshl_or_b32 v3, v36, 16, v3
; GFX9-NEXT:    v_lshl_or_b32 v4, v35, 16, v4
; GFX9-NEXT:    v_lshl_or_b32 v5, v34, 16, v5
; GFX9-NEXT:    v_lshl_or_b32 v6, v33, 16, v6
; GFX9-NEXT:    v_lshl_or_b32 v7, v32, 16, v7
; GFX9-NEXT:    v_lshl_or_b32 v8, v31, 16, v8
; GFX9-NEXT:    v_lshl_or_b32 v9, v30, 16, v9
; GFX9-NEXT:    v_lshl_or_b32 v10, v29, 16, v10
; GFX9-NEXT:    v_lshl_or_b32 v11, v28, 16, v11
; GFX9-NEXT:    v_lshl_or_b32 v12, v27, 16, v12
; GFX9-NEXT:    v_lshl_or_b32 v13, v26, 16, v13
; GFX9-NEXT:    v_lshl_or_b32 v14, v25, 16, v14
; GFX9-NEXT:    v_lshl_or_b32 v15, v24, 16, v15
; GFX9-NEXT:    v_lshl_or_b32 v16, v23, 16, v16
; GFX9-NEXT:    v_lshl_or_b32 v17, v22, 16, v17
; GFX9-NEXT:    v_lshl_or_b32 v18, v21, 16, v18
; GFX9-NEXT:    v_lshl_or_b32 v19, v20, 16, v19
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v20f32_to_v40i16_scalar:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s6, v2
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s4, v1
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s5, v0
; GFX11-TRUE16-NEXT:    s_cmp_lg_u32 s6, 0
; GFX11-TRUE16-NEXT:    s_mov_b32 s6, 0
; GFX11-TRUE16-NEXT:    s_cbranch_scc0 .LBB29_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-TRUE16-NEXT:    s_lshr_b32 s7, s4, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s8, s5, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s9, s29, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s10, s28, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s11, s27, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s12, s26, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s13, s25, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s14, s24, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s15, s23, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s40, s22, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s41, s21, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s42, s20, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s43, s19, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s44, s18, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s45, s17, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s46, s16, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s47, s3, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s56, s2, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s57, s1, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s58, s0, 16
; GFX11-TRUE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s6
; GFX11-TRUE16-NEXT:    s_cbranch_vccnz .LBB29_4
; GFX11-TRUE16-NEXT:  .LBB29_2: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v19, s4, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v18, s5, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v17, s29, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v16, s28, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v15, s27, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v14, s26, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v13, s25, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v12, s24, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v11, s23, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v10, s22, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v9, s21, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v8, s20, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v7, s19, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v6, s18, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v5, s17, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v4, s16, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v3, s3, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v2, s2, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v1, s1, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v0, s0, 1.0
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX11-TRUE16-NEXT:    s_branch .LBB29_5
; GFX11-TRUE16-NEXT:  .LBB29_3:
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr58
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr57
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr56
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr47
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr46
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr45
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr44
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr43
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr42
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr41
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr40
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr15
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr14
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr13
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr12
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr11
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr10
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr9
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr8
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr7
; GFX11-TRUE16-NEXT:    s_branch .LBB29_2
; GFX11-TRUE16-NEXT:  .LBB29_4:
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v4, s16 :: v_dual_mov_b32 v5, s17
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v6, s18 :: v_dual_mov_b32 v7, s19
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v8, s20 :: v_dual_mov_b32 v9, s21
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v10, s22 :: v_dual_mov_b32 v11, s23
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v12, s24 :: v_dual_mov_b32 v13, s25
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v14, s26 :: v_dual_mov_b32 v15, s27
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v16, s28 :: v_dual_mov_b32 v17, s29
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v18, s5 :: v_dual_mov_b32 v19, s4
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v39, s58 :: v_dual_mov_b32 v38, s57
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v37, s56 :: v_dual_mov_b32 v36, s47
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v35, s46 :: v_dual_mov_b32 v34, s45
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v33, s44 :: v_dual_mov_b32 v32, s43
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v31, s42 :: v_dual_mov_b32 v30, s41
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v29, s40 :: v_dual_mov_b32 v28, s15
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v27, s14 :: v_dual_mov_b32 v26, s13
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v25, s12 :: v_dual_mov_b32 v24, s11
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v23, s10 :: v_dual_mov_b32 v22, s9
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v21, s8 :: v_dual_mov_b32 v20, s7
; GFX11-TRUE16-NEXT:  .LBB29_5: ; %end
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.h, v39.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v1.h, v38.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.h, v37.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v3.h, v36.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v4.h, v35.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v5.h, v34.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v6.h, v33.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v7.h, v32.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v8.h, v31.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v9.h, v30.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v10.h, v29.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v11.h, v28.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v12.h, v27.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v13.h, v26.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v14.h, v25.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v15.h, v24.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v16.h, v23.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v17.h, v22.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v18.h, v21.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v19.h, v20.l
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v20f32_to_v40i16_scalar:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s6, v2
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s4, v1
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s5, v0
; GFX11-FAKE16-NEXT:    s_cmp_lg_u32 s6, 0
; GFX11-FAKE16-NEXT:    s_mov_b32 s6, 0
; GFX11-FAKE16-NEXT:    s_cbranch_scc0 .LBB29_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-FAKE16-NEXT:    s_lshr_b32 s7, s4, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s8, s5, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s9, s29, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s10, s28, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s11, s27, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s12, s26, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s13, s25, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s14, s24, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s15, s23, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s40, s22, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s41, s21, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s42, s20, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s43, s19, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s44, s18, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s45, s17, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s46, s16, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s47, s3, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s56, s2, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s57, s1, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s58, s0, 16
; GFX11-FAKE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s6
; GFX11-FAKE16-NEXT:    s_cbranch_vccnz .LBB29_4
; GFX11-FAKE16-NEXT:  .LBB29_2: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v15, s4, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v16, s5, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v17, s29, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v18, s28, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v19, s27, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v10, s26, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v11, s25, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v12, s24, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v13, s23, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v14, s22, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v5, s21, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v6, s20, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v7, s19, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v8, s18, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v9, s17, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v0, s16, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v1, s3, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v2, s2, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v3, s1, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v4, s0, 1.0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v20, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v4
; GFX11-FAKE16-NEXT:    s_branch .LBB29_5
; GFX11-FAKE16-NEXT:  .LBB29_3:
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr58
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr57
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr56
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr47
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr46
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr45
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr44
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr43
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr42
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr41
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr40
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr15
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr14
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr13
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr12
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr11
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr10
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr9
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr8
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr7
; GFX11-FAKE16-NEXT:    s_branch .LBB29_2
; GFX11-FAKE16-NEXT:  .LBB29_4:
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v4, s0 :: v_dual_mov_b32 v3, s1
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v1, s3
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v0, s16 :: v_dual_mov_b32 v9, s17
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v8, s18 :: v_dual_mov_b32 v7, s19
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v6, s20 :: v_dual_mov_b32 v5, s21
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v14, s22 :: v_dual_mov_b32 v13, s23
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v12, s24 :: v_dual_mov_b32 v11, s25
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v10, s26 :: v_dual_mov_b32 v19, s27
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v18, s28 :: v_dual_mov_b32 v17, s29
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v16, s5 :: v_dual_mov_b32 v15, s4
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v39, s58 :: v_dual_mov_b32 v38, s57
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v37, s56 :: v_dual_mov_b32 v36, s47
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v35, s46 :: v_dual_mov_b32 v34, s45
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v33, s44 :: v_dual_mov_b32 v32, s43
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v31, s42 :: v_dual_mov_b32 v30, s41
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v29, s40 :: v_dual_mov_b32 v28, s15
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v27, s14 :: v_dual_mov_b32 v26, s13
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v25, s12 :: v_dual_mov_b32 v24, s11
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v23, s10 :: v_dual_mov_b32 v22, s9
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v21, s8 :: v_dual_mov_b32 v20, s7
; GFX11-FAKE16-NEXT:  .LBB29_5: ; %end
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v48, 0xffff, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v49, 0xffff, v0
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v0, v39, 16, v4
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v1, v38, 16, v3
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v3, v36, 16, v48
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v4, v35, 16, v49
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v35, 0xffff, v6
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v36, 0xffff, v5
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v5, v34, 16, v9
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v6, v33, 16, v8
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v8, v31, 16, v35
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v9, v30, 16, v36
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v30, 0xffff, v11
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v31, 0xffff, v10
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v10, v29, 16, v14
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v11, v28, 16, v13
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v13, v26, 16, v30
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v14, v25, 16, v31
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v25, 0xffff, v16
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v26, 0xffff, v15
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v2, v37, 16, v2
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v7, v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v12, v27, 16, v12
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v15, v24, 16, v19
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v16, v23, 16, v18
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v17, v22, 16, v17
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v18, v21, 16, v25
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v19, v20, 16, v26
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <20 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <20 x float> %a1 to <40 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <20 x float> %a to <40 x i16>
  br label %end

end:
  %phi = phi <40 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <40 x i16> %phi
}

define <20 x float> @bitcast_v40i16_to_v20f32(<40 x i16> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v40i16_to_v20f32:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v63, off, s[0:3], s32 ; 4-byte Folded Spill
; SI-NEXT:    v_mov_b32_e32 v32, v19
; SI-NEXT:    v_mov_b32_e32 v33, v18
; SI-NEXT:    v_mov_b32_e32 v34, v17
; SI-NEXT:    v_mov_b32_e32 v35, v16
; SI-NEXT:    v_mov_b32_e32 v36, v15
; SI-NEXT:    v_mov_b32_e32 v37, v14
; SI-NEXT:    v_mov_b32_e32 v38, v13
; SI-NEXT:    v_mov_b32_e32 v39, v12
; SI-NEXT:    v_mov_b32_e32 v48, v11
; SI-NEXT:    v_mov_b32_e32 v49, v10
; SI-NEXT:    v_mov_b32_e32 v50, v9
; SI-NEXT:    v_mov_b32_e32 v51, v8
; SI-NEXT:    v_mov_b32_e32 v52, v7
; SI-NEXT:    v_mov_b32_e32 v53, v6
; SI-NEXT:    v_mov_b32_e32 v54, v5
; SI-NEXT:    v_mov_b32_e32 v55, v4
; SI-NEXT:    v_mov_b32_e32 v40, v3
; SI-NEXT:    v_mov_b32_e32 v41, v2
; SI-NEXT:    v_mov_b32_e32 v42, v1
; SI-NEXT:    v_mov_b32_e32 v43, v0
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v32
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v33
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v34
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v35
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v36
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v37
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v38
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v39
; SI-NEXT:    v_lshrrev_b32_e32 v8, 16, v48
; SI-NEXT:    v_lshrrev_b32_e32 v9, 16, v49
; SI-NEXT:    v_lshrrev_b32_e32 v10, 16, v50
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v51
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v52
; SI-NEXT:    v_lshrrev_b32_e32 v13, 16, v53
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v54
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v55
; SI-NEXT:    v_lshrrev_b32_e32 v16, 16, v40
; SI-NEXT:    v_lshrrev_b32_e32 v17, 16, v41
; SI-NEXT:    v_lshrrev_b32_e32 v18, 16, v42
; SI-NEXT:    v_lshrrev_b32_e32 v19, 16, v43
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    s_waitcnt expcnt(4)
; SI-NEXT:    v_lshlrev_b32_e32 v59, 16, v19
; SI-NEXT:    v_lshlrev_b32_e32 v58, 16, v18
; SI-NEXT:    v_lshlrev_b32_e32 v57, 16, v17
; SI-NEXT:    v_lshlrev_b32_e32 v56, 16, v16
; SI-NEXT:    v_lshlrev_b32_e32 v47, 16, v15
; SI-NEXT:    v_lshlrev_b32_e32 v46, 16, v14
; SI-NEXT:    v_lshlrev_b32_e32 v45, 16, v13
; SI-NEXT:    v_lshlrev_b32_e32 v44, 16, v12
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshlrev_b32_e32 v63, 16, v11
; SI-NEXT:    v_lshlrev_b32_e32 v62, 16, v10
; SI-NEXT:    v_lshlrev_b32_e32 v61, 16, v9
; SI-NEXT:    v_lshlrev_b32_e32 v60, 16, v8
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:92 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:88 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:84 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:80 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:76 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:72 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:68 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:64 ; 4-byte Folded Spill
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB30_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:92 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:88 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:84 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:80 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:76 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:72 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v39
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v43
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v42
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v41
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v40
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v55
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v54
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v53
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v52
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v51
; SI-NEXT:    v_and_b32_e32 v9, 0xffff, v50
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v49
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v48
; SI-NEXT:    v_or_b32_e32 v0, v0, v59
; SI-NEXT:    v_or_b32_e32 v1, v1, v58
; SI-NEXT:    v_or_b32_e32 v2, v2, v57
; SI-NEXT:    v_or_b32_e32 v3, v3, v56
; SI-NEXT:    v_or_b32_e32 v4, v4, v47
; SI-NEXT:    v_or_b32_e32 v5, v5, v46
; SI-NEXT:    v_or_b32_e32 v6, v6, v45
; SI-NEXT:    v_or_b32_e32 v7, v7, v44
; SI-NEXT:    v_or_b32_e32 v8, v8, v63
; SI-NEXT:    v_or_b32_e32 v9, v9, v62
; SI-NEXT:    v_or_b32_e32 v10, v10, v61
; SI-NEXT:    v_or_b32_e32 v11, v11, v60
; SI-NEXT:    ; implicit-def: $vgpr43
; SI-NEXT:    ; implicit-def: $vgpr42
; SI-NEXT:    ; implicit-def: $vgpr41
; SI-NEXT:    ; implicit-def: $vgpr40
; SI-NEXT:    ; implicit-def: $vgpr55
; SI-NEXT:    ; implicit-def: $vgpr54
; SI-NEXT:    ; implicit-def: $vgpr53
; SI-NEXT:    ; implicit-def: $vgpr52
; SI-NEXT:    ; implicit-def: $vgpr51
; SI-NEXT:    ; implicit-def: $vgpr50
; SI-NEXT:    ; implicit-def: $vgpr49
; SI-NEXT:    ; implicit-def: $vgpr48
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:    ; implicit-def: $vgpr59
; SI-NEXT:    ; implicit-def: $vgpr58
; SI-NEXT:    ; implicit-def: $vgpr57
; SI-NEXT:    ; implicit-def: $vgpr56
; SI-NEXT:    ; implicit-def: $vgpr47
; SI-NEXT:    ; implicit-def: $vgpr46
; SI-NEXT:    ; implicit-def: $vgpr45
; SI-NEXT:    ; implicit-def: $vgpr44
; SI-NEXT:    ; implicit-def: $vgpr63
; SI-NEXT:    ; implicit-def: $vgpr62
; SI-NEXT:    ; implicit-def: $vgpr61
; SI-NEXT:    ; implicit-def: $vgpr60
; SI-NEXT:    s_waitcnt vmcnt(7)
; SI-NEXT:    v_or_b32_e32 v12, v12, v13
; SI-NEXT:    v_and_b32_e32 v13, 0xffff, v38
; SI-NEXT:    s_waitcnt vmcnt(6)
; SI-NEXT:    v_or_b32_e32 v13, v13, v14
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v37
; SI-NEXT:    s_waitcnt vmcnt(5)
; SI-NEXT:    v_or_b32_e32 v14, v14, v15
; SI-NEXT:    v_and_b32_e32 v15, 0xffff, v36
; SI-NEXT:    s_waitcnt vmcnt(4)
; SI-NEXT:    v_or_b32_e32 v15, v15, v16
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v35
; SI-NEXT:    s_waitcnt vmcnt(3)
; SI-NEXT:    v_or_b32_e32 v16, v16, v17
; SI-NEXT:    v_and_b32_e32 v17, 0xffff, v34
; SI-NEXT:    s_waitcnt vmcnt(2)
; SI-NEXT:    v_or_b32_e32 v17, v17, v18
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v33
; SI-NEXT:    s_waitcnt vmcnt(1)
; SI-NEXT:    v_or_b32_e32 v18, v18, v19
; SI-NEXT:    v_and_b32_e32 v19, 0xffff, v32
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_or_b32_e32 v19, v19, v20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:  .LBB30_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB30_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:92 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:88 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:84 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:80 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:76 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:72 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; SI-NEXT:    v_add_i32_e32 v12, vcc, 3, v39
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v43
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v42
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v41
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v40
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v55
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v54
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v53
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v52
; SI-NEXT:    v_add_i32_e32 v8, vcc, 3, v51
; SI-NEXT:    v_add_i32_e32 v9, vcc, 3, v50
; SI-NEXT:    v_add_i32_e32 v10, vcc, 3, v49
; SI-NEXT:    v_add_i32_e32 v11, vcc, 3, v48
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; SI-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; SI-NEXT:    v_or_b32_e32 v0, v59, v0
; SI-NEXT:    s_mov_b32 s6, 0x30000
; SI-NEXT:    v_or_b32_e32 v1, v58, v1
; SI-NEXT:    v_or_b32_e32 v2, v57, v2
; SI-NEXT:    v_or_b32_e32 v3, v56, v3
; SI-NEXT:    v_or_b32_e32 v4, v47, v4
; SI-NEXT:    v_or_b32_e32 v5, v46, v5
; SI-NEXT:    v_or_b32_e32 v6, v45, v6
; SI-NEXT:    v_or_b32_e32 v7, v44, v7
; SI-NEXT:    v_or_b32_e32 v8, v63, v8
; SI-NEXT:    v_or_b32_e32 v9, v62, v9
; SI-NEXT:    v_or_b32_e32 v10, v61, v10
; SI-NEXT:    v_or_b32_e32 v11, v60, v11
; SI-NEXT:    v_add_i32_e32 v0, vcc, 0x30000, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, s6, v1
; SI-NEXT:    v_add_i32_e32 v2, vcc, s6, v2
; SI-NEXT:    v_add_i32_e32 v3, vcc, s6, v3
; SI-NEXT:    v_add_i32_e32 v4, vcc, s6, v4
; SI-NEXT:    v_add_i32_e32 v5, vcc, s6, v5
; SI-NEXT:    v_add_i32_e32 v6, vcc, s6, v6
; SI-NEXT:    v_add_i32_e32 v7, vcc, s6, v7
; SI-NEXT:    v_add_i32_e32 v8, vcc, s6, v8
; SI-NEXT:    v_add_i32_e32 v9, vcc, s6, v9
; SI-NEXT:    s_waitcnt vmcnt(7)
; SI-NEXT:    v_or_b32_e32 v12, v13, v12
; SI-NEXT:    v_add_i32_e32 v13, vcc, 3, v38
; SI-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; SI-NEXT:    s_waitcnt vmcnt(6)
; SI-NEXT:    v_or_b32_e32 v13, v14, v13
; SI-NEXT:    v_add_i32_e32 v14, vcc, 3, v37
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; SI-NEXT:    s_waitcnt vmcnt(5)
; SI-NEXT:    v_or_b32_e32 v14, v15, v14
; SI-NEXT:    v_add_i32_e32 v15, vcc, 3, v36
; SI-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; SI-NEXT:    s_waitcnt vmcnt(4)
; SI-NEXT:    v_or_b32_e32 v15, v16, v15
; SI-NEXT:    v_add_i32_e32 v16, vcc, 3, v35
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v16
; SI-NEXT:    s_waitcnt vmcnt(3)
; SI-NEXT:    v_or_b32_e32 v16, v17, v16
; SI-NEXT:    v_add_i32_e32 v17, vcc, 3, v34
; SI-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; SI-NEXT:    s_waitcnt vmcnt(2)
; SI-NEXT:    v_or_b32_e32 v17, v18, v17
; SI-NEXT:    v_add_i32_e32 v18, vcc, 3, v33
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; SI-NEXT:    s_waitcnt vmcnt(1)
; SI-NEXT:    v_or_b32_e32 v18, v19, v18
; SI-NEXT:    v_add_i32_e32 v19, vcc, 3, v32
; SI-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_or_b32_e32 v19, v20, v19
; SI-NEXT:    v_add_i32_e32 v10, vcc, s6, v10
; SI-NEXT:    v_add_i32_e32 v11, vcc, s6, v11
; SI-NEXT:    v_add_i32_e32 v12, vcc, s6, v12
; SI-NEXT:    v_add_i32_e32 v13, vcc, s6, v13
; SI-NEXT:    v_add_i32_e32 v14, vcc, s6, v14
; SI-NEXT:    v_add_i32_e32 v15, vcc, s6, v15
; SI-NEXT:    v_add_i32_e32 v16, vcc, s6, v16
; SI-NEXT:    v_add_i32_e32 v17, vcc, s6, v17
; SI-NEXT:    v_add_i32_e32 v18, vcc, s6, v18
; SI-NEXT:    v_add_i32_e32 v19, vcc, 0x30000, v19
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:  .LBB30_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    buffer_load_dword v63, off, s[0:3], s32 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0)
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v40i16_to_v20f32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; VI-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; VI-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; VI-NEXT:    buffer_store_dword v43, off, s[0:3], s32 ; 4-byte Folded Spill
; VI-NEXT:    v_mov_b32_e32 v32, v19
; VI-NEXT:    v_mov_b32_e32 v33, v18
; VI-NEXT:    v_mov_b32_e32 v34, v17
; VI-NEXT:    v_mov_b32_e32 v35, v16
; VI-NEXT:    v_mov_b32_e32 v36, v15
; VI-NEXT:    v_mov_b32_e32 v37, v14
; VI-NEXT:    v_mov_b32_e32 v38, v13
; VI-NEXT:    v_mov_b32_e32 v39, v12
; VI-NEXT:    v_mov_b32_e32 v48, v11
; VI-NEXT:    v_mov_b32_e32 v49, v10
; VI-NEXT:    v_mov_b32_e32 v50, v9
; VI-NEXT:    v_mov_b32_e32 v51, v8
; VI-NEXT:    v_mov_b32_e32 v52, v7
; VI-NEXT:    v_mov_b32_e32 v53, v6
; VI-NEXT:    v_mov_b32_e32 v54, v5
; VI-NEXT:    v_mov_b32_e32 v55, v4
; VI-NEXT:    v_mov_b32_e32 v40, v3
; VI-NEXT:    v_mov_b32_e32 v41, v2
; VI-NEXT:    v_mov_b32_e32 v42, v1
; VI-NEXT:    v_mov_b32_e32 v43, v0
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB30_2
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_mov_b32_e32 v19, 16
; VI-NEXT:    v_lshlrev_b32_sdwa v0, v19, v43 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v1, v19, v42 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v2, v19, v41 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v3, v19, v40 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v4, v19, v55 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v5, v19, v54 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v6, v19, v53 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v7, v19, v52 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v8, v19, v51 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v9, v19, v50 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v10, v19, v49 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v11, v19, v48 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v12, v19, v39 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v13, v19, v38 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v14, v19, v37 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v15, v19, v36 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v16, v19, v35 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v17, v19, v34 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v18, v19, v33 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v19, v19, v32 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_or_b32_sdwa v0, v43, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v1, v42, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v2, v41, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v3, v40, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v4, v55, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v5, v54, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v6, v53, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v7, v52, v7 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v8, v51, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v9, v50, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v10, v49, v10 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v11, v48, v11 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v12, v39, v12 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v13, v38, v13 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v14, v37, v14 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v15, v36, v15 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v16, v35, v16 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v17, v34, v17 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v18, v33, v18 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v19, v32, v19 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr43
; VI-NEXT:    ; implicit-def: $vgpr42
; VI-NEXT:    ; implicit-def: $vgpr41
; VI-NEXT:    ; implicit-def: $vgpr40
; VI-NEXT:    ; implicit-def: $vgpr55
; VI-NEXT:    ; implicit-def: $vgpr54
; VI-NEXT:    ; implicit-def: $vgpr53
; VI-NEXT:    ; implicit-def: $vgpr52
; VI-NEXT:    ; implicit-def: $vgpr51
; VI-NEXT:    ; implicit-def: $vgpr50
; VI-NEXT:    ; implicit-def: $vgpr49
; VI-NEXT:    ; implicit-def: $vgpr48
; VI-NEXT:    ; implicit-def: $vgpr39
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr35
; VI-NEXT:    ; implicit-def: $vgpr34
; VI-NEXT:    ; implicit-def: $vgpr33
; VI-NEXT:    ; implicit-def: $vgpr32
; VI-NEXT:  .LBB30_2: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB30_4
; VI-NEXT:  ; %bb.3: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v19, 3
; VI-NEXT:    v_add_u16_e32 v0, 3, v43
; VI-NEXT:    v_add_u16_sdwa v1, v43, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v0, v0, v1
; VI-NEXT:    v_add_u16_e32 v1, 3, v42
; VI-NEXT:    v_add_u16_sdwa v2, v42, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v1, v1, v2
; VI-NEXT:    v_add_u16_e32 v2, 3, v41
; VI-NEXT:    v_add_u16_sdwa v3, v41, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v2, v2, v3
; VI-NEXT:    v_add_u16_e32 v3, 3, v40
; VI-NEXT:    v_add_u16_sdwa v4, v40, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v3, v3, v4
; VI-NEXT:    v_add_u16_e32 v4, 3, v55
; VI-NEXT:    v_add_u16_sdwa v5, v55, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v4, v4, v5
; VI-NEXT:    v_add_u16_e32 v5, 3, v54
; VI-NEXT:    v_add_u16_sdwa v6, v54, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v5, v5, v6
; VI-NEXT:    v_add_u16_e32 v6, 3, v53
; VI-NEXT:    v_add_u16_sdwa v7, v53, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v6, v6, v7
; VI-NEXT:    v_add_u16_e32 v7, 3, v52
; VI-NEXT:    v_add_u16_sdwa v8, v52, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v7, v7, v8
; VI-NEXT:    v_add_u16_e32 v8, 3, v51
; VI-NEXT:    v_add_u16_sdwa v9, v51, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v8, v8, v9
; VI-NEXT:    v_add_u16_e32 v9, 3, v50
; VI-NEXT:    v_add_u16_sdwa v10, v50, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v9, v9, v10
; VI-NEXT:    v_add_u16_e32 v10, 3, v49
; VI-NEXT:    v_add_u16_sdwa v11, v49, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v10, v10, v11
; VI-NEXT:    v_add_u16_e32 v11, 3, v48
; VI-NEXT:    v_add_u16_sdwa v12, v48, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v11, v11, v12
; VI-NEXT:    v_add_u16_e32 v12, 3, v39
; VI-NEXT:    v_add_u16_sdwa v13, v39, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v12, v12, v13
; VI-NEXT:    v_add_u16_e32 v13, 3, v38
; VI-NEXT:    v_add_u16_sdwa v14, v38, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v13, v13, v14
; VI-NEXT:    v_add_u16_e32 v14, 3, v37
; VI-NEXT:    v_add_u16_sdwa v15, v37, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v14, v14, v15
; VI-NEXT:    v_add_u16_e32 v15, 3, v36
; VI-NEXT:    v_add_u16_sdwa v16, v36, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v15, v15, v16
; VI-NEXT:    v_add_u16_e32 v16, 3, v35
; VI-NEXT:    v_add_u16_sdwa v17, v35, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v16, v16, v17
; VI-NEXT:    v_add_u16_e32 v17, 3, v34
; VI-NEXT:    v_add_u16_sdwa v18, v34, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v17, v17, v18
; VI-NEXT:    v_add_u16_e32 v18, 3, v33
; VI-NEXT:    v_add_u16_sdwa v20, v33, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v18, v18, v20
; VI-NEXT:    v_add_u16_e32 v20, 3, v32
; VI-NEXT:    v_add_u16_sdwa v19, v32, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v19, v20, v19
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:  .LBB30_4: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    buffer_load_dword v43, off, s[0:3], s32 ; 4-byte Folded Reload
; VI-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; VI-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; VI-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v40i16_to_v20f32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v63, off, s[0:3], s32 ; 4-byte Folded Spill
; GFX9-NEXT:    v_mov_b32_e32 v32, v19
; GFX9-NEXT:    v_mov_b32_e32 v33, v18
; GFX9-NEXT:    v_mov_b32_e32 v43, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v32
; GFX9-NEXT:    v_mov_b32_e32 v34, v17
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:64 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v33
; GFX9-NEXT:    v_mov_b32_e32 v35, v16
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:68 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v34
; GFX9-NEXT:    v_mov_b32_e32 v36, v15
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:72 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v35
; GFX9-NEXT:    v_mov_b32_e32 v37, v14
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:76 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v36
; GFX9-NEXT:    v_mov_b32_e32 v38, v13
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:80 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v37
; GFX9-NEXT:    v_mov_b32_e32 v39, v12
; GFX9-NEXT:    v_mov_b32_e32 v48, v11
; GFX9-NEXT:    v_mov_b32_e32 v49, v10
; GFX9-NEXT:    v_mov_b32_e32 v50, v9
; GFX9-NEXT:    v_mov_b32_e32 v51, v8
; GFX9-NEXT:    v_mov_b32_e32 v52, v7
; GFX9-NEXT:    v_mov_b32_e32 v53, v6
; GFX9-NEXT:    v_mov_b32_e32 v54, v5
; GFX9-NEXT:    v_mov_b32_e32 v55, v4
; GFX9-NEXT:    v_mov_b32_e32 v40, v3
; GFX9-NEXT:    v_mov_b32_e32 v41, v2
; GFX9-NEXT:    v_mov_b32_e32 v42, v1
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:84 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v38
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:88 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v39
; GFX9-NEXT:    v_lshrrev_b32_e32 v60, 16, v48
; GFX9-NEXT:    v_lshrrev_b32_e32 v61, 16, v49
; GFX9-NEXT:    v_lshrrev_b32_e32 v62, 16, v50
; GFX9-NEXT:    v_lshrrev_b32_e32 v63, 16, v51
; GFX9-NEXT:    v_lshrrev_b32_e32 v44, 16, v52
; GFX9-NEXT:    v_lshrrev_b32_e32 v45, 16, v53
; GFX9-NEXT:    v_lshrrev_b32_e32 v46, 16, v54
; GFX9-NEXT:    v_lshrrev_b32_e32 v47, 16, v55
; GFX9-NEXT:    v_lshrrev_b32_e32 v56, 16, v40
; GFX9-NEXT:    v_lshrrev_b32_e32 v57, 16, v41
; GFX9-NEXT:    v_lshrrev_b32_e32 v58, 16, v42
; GFX9-NEXT:    v_lshrrev_b32_e32 v59, 16, v43
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:92 ; 4-byte Folded Spill
; GFX9-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB30_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_mov_b32 s6, 0x5040100
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v12, 16, v39
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v13, 16, v38
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v14, 16, v37
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v15, 16, v36
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v16, 16, v35
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v17, 16, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v18, 16, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v19, 16, v32
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    v_perm_b32 v0, v59, v43, s6
; GFX9-NEXT:    v_perm_b32 v1, v58, v42, s6
; GFX9-NEXT:    v_perm_b32 v2, v57, v41, s6
; GFX9-NEXT:    v_perm_b32 v3, v56, v40, s6
; GFX9-NEXT:    v_perm_b32 v4, v47, v55, s6
; GFX9-NEXT:    v_perm_b32 v5, v46, v54, s6
; GFX9-NEXT:    v_perm_b32 v6, v45, v53, s6
; GFX9-NEXT:    v_perm_b32 v7, v44, v52, s6
; GFX9-NEXT:    v_perm_b32 v8, v63, v51, s6
; GFX9-NEXT:    v_perm_b32 v9, v62, v50, s6
; GFX9-NEXT:    v_perm_b32 v10, v61, v49, s6
; GFX9-NEXT:    v_perm_b32 v11, v60, v48, s6
; GFX9-NEXT:    v_perm_b32 v12, v12, v39, s6
; GFX9-NEXT:    v_perm_b32 v13, v13, v38, s6
; GFX9-NEXT:    v_perm_b32 v14, v14, v37, s6
; GFX9-NEXT:    v_perm_b32 v15, v15, v36, s6
; GFX9-NEXT:    v_perm_b32 v16, v16, v35, s6
; GFX9-NEXT:    v_perm_b32 v17, v17, v34, s6
; GFX9-NEXT:    v_perm_b32 v18, v18, v33, s6
; GFX9-NEXT:    v_perm_b32 v19, v19, v32, s6
; GFX9-NEXT:    ; implicit-def: $vgpr43
; GFX9-NEXT:    ; implicit-def: $vgpr42
; GFX9-NEXT:    ; implicit-def: $vgpr41
; GFX9-NEXT:    ; implicit-def: $vgpr40
; GFX9-NEXT:    ; implicit-def: $vgpr55
; GFX9-NEXT:    ; implicit-def: $vgpr54
; GFX9-NEXT:    ; implicit-def: $vgpr53
; GFX9-NEXT:    ; implicit-def: $vgpr52
; GFX9-NEXT:    ; implicit-def: $vgpr51
; GFX9-NEXT:    ; implicit-def: $vgpr50
; GFX9-NEXT:    ; implicit-def: $vgpr49
; GFX9-NEXT:    ; implicit-def: $vgpr48
; GFX9-NEXT:    ; implicit-def: $vgpr39
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr35
; GFX9-NEXT:    ; implicit-def: $vgpr34
; GFX9-NEXT:    ; implicit-def: $vgpr33
; GFX9-NEXT:    ; implicit-def: $vgpr32
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr60
; GFX9-NEXT:    ; implicit-def: $vgpr61
; GFX9-NEXT:    ; implicit-def: $vgpr62
; GFX9-NEXT:    ; implicit-def: $vgpr63
; GFX9-NEXT:    ; implicit-def: $vgpr44
; GFX9-NEXT:    ; implicit-def: $vgpr45
; GFX9-NEXT:    ; implicit-def: $vgpr46
; GFX9-NEXT:    ; implicit-def: $vgpr47
; GFX9-NEXT:    ; implicit-def: $vgpr56
; GFX9-NEXT:    ; implicit-def: $vgpr57
; GFX9-NEXT:    ; implicit-def: $vgpr58
; GFX9-NEXT:    ; implicit-def: $vgpr59
; GFX9-NEXT:  .LBB30_2: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB30_4
; GFX9-NEXT:  ; %bb.3: ; %cmp.true
; GFX9-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:92 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:88 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:84 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:80 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:76 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:72 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; GFX9-NEXT:    s_mov_b32 s6, 0x5040100
; GFX9-NEXT:    v_perm_b32 v0, v59, v43, s6
; GFX9-NEXT:    v_perm_b32 v1, v58, v42, s6
; GFX9-NEXT:    v_perm_b32 v2, v57, v41, s6
; GFX9-NEXT:    v_perm_b32 v3, v56, v40, s6
; GFX9-NEXT:    v_perm_b32 v4, v47, v55, s6
; GFX9-NEXT:    v_perm_b32 v5, v46, v54, s6
; GFX9-NEXT:    v_perm_b32 v6, v45, v53, s6
; GFX9-NEXT:    v_perm_b32 v7, v44, v52, s6
; GFX9-NEXT:    v_perm_b32 v8, v63, v51, s6
; GFX9-NEXT:    v_perm_b32 v9, v62, v50, s6
; GFX9-NEXT:    v_perm_b32 v10, v61, v49, s6
; GFX9-NEXT:    v_perm_b32 v11, v60, v48, s6
; GFX9-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v8, v8, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v9, v9, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_waitcnt vmcnt(7)
; GFX9-NEXT:    v_perm_b32 v12, v12, v39, s6
; GFX9-NEXT:    s_waitcnt vmcnt(6)
; GFX9-NEXT:    v_perm_b32 v13, v13, v38, s6
; GFX9-NEXT:    s_waitcnt vmcnt(5)
; GFX9-NEXT:    v_perm_b32 v14, v14, v37, s6
; GFX9-NEXT:    s_waitcnt vmcnt(4)
; GFX9-NEXT:    v_perm_b32 v15, v15, v36, s6
; GFX9-NEXT:    s_waitcnt vmcnt(3)
; GFX9-NEXT:    v_perm_b32 v16, v16, v35, s6
; GFX9-NEXT:    s_waitcnt vmcnt(2)
; GFX9-NEXT:    v_perm_b32 v17, v17, v34, s6
; GFX9-NEXT:    s_waitcnt vmcnt(1)
; GFX9-NEXT:    v_perm_b32 v18, v18, v33, s6
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    v_perm_b32 v19, v19, v32, s6
; GFX9-NEXT:    v_pk_add_u16 v12, v12, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v13, v13, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v14, v14, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v15, v15, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v16, v16, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v17, v17, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v18, v18, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v19, v19, 3 op_sel_hi:[1,0]
; GFX9-NEXT:  .LBB30_4: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    buffer_load_dword v63, off, s[0:3], s32 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Reload
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v40i16_to_v20f32:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB30_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB30_4
; GFX11-TRUE16-NEXT:  .LBB30_2: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB30_3: ; %cmp.false
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB30_2
; GFX11-TRUE16-NEXT:  .LBB30_4: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v8, v8, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v9, v9, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v12, v12, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v13, v13, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v14, v14, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v15, v15, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v16, v16, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v17, v17, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v18, v18, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v19, v19, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v40i16_to_v20f32:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v48, 16, v3
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v20
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v37, v0, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v38, v1, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v39, v2, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v48, v3, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v36, v4, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v35, v5, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v34, v6, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v33, v7, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, v32, v8, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, v31, v9, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, v30, v10, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, v29, v11, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, v28, v12, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, v27, v13, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v14, v26, v14, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v15, v25, v15, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v16, v24, v16, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v17, v23, v17, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v18, v22, v18, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v19, v21, v19, 0x5040100
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB30_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB30_4
; GFX11-FAKE16-NEXT:  .LBB30_2: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB30_3: ; %cmp.false
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB30_2
; GFX11-FAKE16-NEXT:  .LBB30_4: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v8, v8, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v9, v9, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v12, v12, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v13, v13, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v14, v14, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v15, v15, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v16, v16, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v17, v17, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v18, v18, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v19, v19, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <40 x i16> %a, splat (i16 3)
  %a2 = bitcast <40 x i16> %a1 to <20 x float>
  br label %end

cmp.false:
  %a3 = bitcast <40 x i16> %a to <20 x float>
  br label %end

end:
  %phi = phi <20 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <20 x float> %phi
}

define inreg <20 x float> @bitcast_v40i16_to_v20f32_scalar(<40 x i16> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v40i16_to_v20f32_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_store_dword v20, off, s[0:3], s32 ; 4-byte Folded Spill
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_writelane_b32 v20, s36, 0
; SI-NEXT:    v_writelane_b32 v20, s37, 1
; SI-NEXT:    v_writelane_b32 v20, s38, 2
; SI-NEXT:    v_writelane_b32 v20, s39, 3
; SI-NEXT:    v_writelane_b32 v20, s48, 4
; SI-NEXT:    v_writelane_b32 v20, s49, 5
; SI-NEXT:    v_writelane_b32 v20, s50, 6
; SI-NEXT:    v_writelane_b32 v20, s51, 7
; SI-NEXT:    v_writelane_b32 v20, s52, 8
; SI-NEXT:    v_writelane_b32 v20, s53, 9
; SI-NEXT:    v_writelane_b32 v20, s54, 10
; SI-NEXT:    v_writelane_b32 v20, s55, 11
; SI-NEXT:    v_writelane_b32 v20, s64, 12
; SI-NEXT:    v_writelane_b32 v20, s65, 13
; SI-NEXT:    v_writelane_b32 v20, s66, 14
; SI-NEXT:    v_writelane_b32 v20, s67, 15
; SI-NEXT:    v_readfirstlane_b32 s7, v5
; SI-NEXT:    v_readfirstlane_b32 s9, v4
; SI-NEXT:    v_readfirstlane_b32 s12, v3
; SI-NEXT:    v_readfirstlane_b32 s15, v2
; SI-NEXT:    v_readfirstlane_b32 s74, v1
; SI-NEXT:    v_readfirstlane_b32 s77, v0
; SI-NEXT:    s_lshr_b32 s11, s29, 16
; SI-NEXT:    s_lshr_b32 s13, s28, 16
; SI-NEXT:    s_lshr_b32 s72, s27, 16
; SI-NEXT:    s_lshr_b32 s75, s26, 16
; SI-NEXT:    s_lshr_b32 s78, s25, 16
; SI-NEXT:    s_lshr_b32 s79, s24, 16
; SI-NEXT:    s_lshr_b32 s88, s23, 16
; SI-NEXT:    s_lshr_b32 s89, s22, 16
; SI-NEXT:    s_lshr_b32 s90, s21, 16
; SI-NEXT:    s_lshr_b32 s91, s20, 16
; SI-NEXT:    s_lshr_b32 s92, s19, 16
; SI-NEXT:    s_lshr_b32 s93, s18, 16
; SI-NEXT:    s_lshr_b32 s94, s17, 16
; SI-NEXT:    s_lshr_b32 s95, s16, 16
; SI-NEXT:    s_lshr_b32 s6, s7, 16
; SI-NEXT:    s_lshr_b32 s8, s9, 16
; SI-NEXT:    s_lshr_b32 s10, s12, 16
; SI-NEXT:    s_lshr_b32 s14, s15, 16
; SI-NEXT:    s_lshr_b32 s73, s74, 16
; SI-NEXT:    s_lshr_b32 s76, s77, 16
; SI-NEXT:    v_readfirstlane_b32 s4, v6
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    s_cbranch_scc0 .LBB31_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s95, 16
; SI-NEXT:    s_or_b32 s36, s4, s5
; SI-NEXT:    s_and_b32 s4, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s94, 16
; SI-NEXT:    s_or_b32 s37, s4, s5
; SI-NEXT:    s_and_b32 s4, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s93, 16
; SI-NEXT:    s_or_b32 s38, s4, s5
; SI-NEXT:    s_and_b32 s4, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s92, 16
; SI-NEXT:    s_or_b32 s39, s4, s5
; SI-NEXT:    s_and_b32 s4, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s91, 16
; SI-NEXT:    s_or_b32 s40, s4, s5
; SI-NEXT:    s_and_b32 s4, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s90, 16
; SI-NEXT:    s_or_b32 s41, s4, s5
; SI-NEXT:    s_and_b32 s4, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s89, 16
; SI-NEXT:    s_or_b32 s42, s4, s5
; SI-NEXT:    s_and_b32 s4, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s88, 16
; SI-NEXT:    s_or_b32 s43, s4, s5
; SI-NEXT:    s_and_b32 s4, s24, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s79, 16
; SI-NEXT:    s_or_b32 s44, s4, s5
; SI-NEXT:    s_and_b32 s4, s25, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s78, 16
; SI-NEXT:    s_or_b32 s45, s4, s5
; SI-NEXT:    s_and_b32 s4, s26, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s75, 16
; SI-NEXT:    s_or_b32 s46, s4, s5
; SI-NEXT:    s_and_b32 s4, s27, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s72, 16
; SI-NEXT:    s_or_b32 s47, s4, s5
; SI-NEXT:    s_and_b32 s4, s28, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s13, 16
; SI-NEXT:    s_or_b32 s48, s4, s5
; SI-NEXT:    s_and_b32 s4, s29, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s11, 16
; SI-NEXT:    s_or_b32 s49, s4, s5
; SI-NEXT:    s_and_b32 s4, s77, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s76, 16
; SI-NEXT:    s_or_b32 s50, s4, s5
; SI-NEXT:    s_and_b32 s4, s74, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s73, 16
; SI-NEXT:    s_or_b32 s51, s4, s5
; SI-NEXT:    s_and_b32 s4, s15, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s14, 16
; SI-NEXT:    s_or_b32 s52, s4, s5
; SI-NEXT:    s_and_b32 s4, s12, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s10, 16
; SI-NEXT:    s_or_b32 s53, s4, s5
; SI-NEXT:    s_and_b32 s4, s9, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s8, 16
; SI-NEXT:    s_or_b32 s54, s4, s5
; SI-NEXT:    s_and_b32 s4, s7, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s6, 16
; SI-NEXT:    s_or_b32 s55, s4, s5
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    s_cbranch_execnz .LBB31_3
; SI-NEXT:  .LBB31_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s95, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s17, s17, 3
; SI-NEXT:    s_add_i32 s36, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s94, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_add_i32 s37, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s93, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s19, s19, 3
; SI-NEXT:    s_add_i32 s38, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s92, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_add_i32 s39, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s91, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s21, s21, 3
; SI-NEXT:    s_add_i32 s40, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s90, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_add_i32 s41, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s89, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s23, s23, 3
; SI-NEXT:    s_add_i32 s42, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s88, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s24, s24, 3
; SI-NEXT:    s_add_i32 s43, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s24, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s79, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s25, s25, 3
; SI-NEXT:    s_add_i32 s44, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s25, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s78, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s26, s26, 3
; SI-NEXT:    s_add_i32 s45, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s26, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s75, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s27, s27, 3
; SI-NEXT:    s_add_i32 s46, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s27, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s72, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s28, s28, 3
; SI-NEXT:    s_add_i32 s47, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s28, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s13, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s29, s29, 3
; SI-NEXT:    s_add_i32 s48, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s29, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s11, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s77, s77, 3
; SI-NEXT:    s_add_i32 s49, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s77, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s76, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s74, s74, 3
; SI-NEXT:    s_add_i32 s50, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s74, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s73, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s15, s15, 3
; SI-NEXT:    s_add_i32 s51, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s15, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s14, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s12, s12, 3
; SI-NEXT:    s_add_i32 s52, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s12, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s10, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s9, s9, 3
; SI-NEXT:    s_add_i32 s53, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s9, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s8, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s7, s7, 3
; SI-NEXT:    s_add_i32 s54, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s7, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s6, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s55, s4, 0x30000
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:  .LBB31_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v0, s36
; SI-NEXT:    v_mov_b32_e32 v1, s37
; SI-NEXT:    v_mov_b32_e32 v2, s38
; SI-NEXT:    v_mov_b32_e32 v3, s39
; SI-NEXT:    v_mov_b32_e32 v4, s40
; SI-NEXT:    v_mov_b32_e32 v5, s41
; SI-NEXT:    v_mov_b32_e32 v6, s42
; SI-NEXT:    v_mov_b32_e32 v7, s43
; SI-NEXT:    v_mov_b32_e32 v8, s44
; SI-NEXT:    v_mov_b32_e32 v9, s45
; SI-NEXT:    v_mov_b32_e32 v10, s46
; SI-NEXT:    v_mov_b32_e32 v11, s47
; SI-NEXT:    v_mov_b32_e32 v12, s48
; SI-NEXT:    v_mov_b32_e32 v13, s49
; SI-NEXT:    v_mov_b32_e32 v14, s50
; SI-NEXT:    v_mov_b32_e32 v15, s51
; SI-NEXT:    v_mov_b32_e32 v16, s52
; SI-NEXT:    v_mov_b32_e32 v17, s53
; SI-NEXT:    v_mov_b32_e32 v18, s54
; SI-NEXT:    v_mov_b32_e32 v19, s55
; SI-NEXT:    v_readlane_b32 s67, v20, 15
; SI-NEXT:    v_readlane_b32 s66, v20, 14
; SI-NEXT:    v_readlane_b32 s65, v20, 13
; SI-NEXT:    v_readlane_b32 s64, v20, 12
; SI-NEXT:    v_readlane_b32 s55, v20, 11
; SI-NEXT:    v_readlane_b32 s54, v20, 10
; SI-NEXT:    v_readlane_b32 s53, v20, 9
; SI-NEXT:    v_readlane_b32 s52, v20, 8
; SI-NEXT:    v_readlane_b32 s51, v20, 7
; SI-NEXT:    v_readlane_b32 s50, v20, 6
; SI-NEXT:    v_readlane_b32 s49, v20, 5
; SI-NEXT:    v_readlane_b32 s48, v20, 4
; SI-NEXT:    v_readlane_b32 s39, v20, 3
; SI-NEXT:    v_readlane_b32 s38, v20, 2
; SI-NEXT:    v_readlane_b32 s37, v20, 1
; SI-NEXT:    v_readlane_b32 s36, v20, 0
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_load_dword v20, off, s[0:3], s32 ; 4-byte Folded Reload
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB31_4:
; SI-NEXT:    ; implicit-def: $sgpr36_sgpr37_sgpr38_sgpr39_sgpr40_sgpr41_sgpr42_sgpr43_sgpr44_sgpr45_sgpr46_sgpr47_sgpr48_sgpr49_sgpr50_sgpr51_sgpr52_sgpr53_sgpr54_sgpr55_sgpr56_sgpr57_sgpr58_sgpr59_sgpr60_sgpr61_sgpr62_sgpr63_sgpr64_sgpr65_sgpr66_sgpr67
; SI-NEXT:    s_branch .LBB31_2
;
; VI-LABEL: bitcast_v40i16_to_v20f32_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_store_dword v20, off, s[0:3], s32 ; 4-byte Folded Spill
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    v_writelane_b32 v20, s34, 0
; VI-NEXT:    v_writelane_b32 v20, s35, 1
; VI-NEXT:    v_writelane_b32 v20, s36, 2
; VI-NEXT:    v_writelane_b32 v20, s37, 3
; VI-NEXT:    v_writelane_b32 v20, s38, 4
; VI-NEXT:    v_writelane_b32 v20, s39, 5
; VI-NEXT:    v_writelane_b32 v20, s48, 6
; VI-NEXT:    v_writelane_b32 v20, s49, 7
; VI-NEXT:    v_writelane_b32 v20, s50, 8
; VI-NEXT:    v_writelane_b32 v20, s51, 9
; VI-NEXT:    v_writelane_b32 v20, s52, 10
; VI-NEXT:    v_writelane_b32 v20, s53, 11
; VI-NEXT:    v_writelane_b32 v20, s54, 12
; VI-NEXT:    v_writelane_b32 v20, s55, 13
; VI-NEXT:    v_writelane_b32 v20, s64, 14
; VI-NEXT:    v_writelane_b32 v20, s65, 15
; VI-NEXT:    v_writelane_b32 v20, s66, 16
; VI-NEXT:    v_writelane_b32 v20, s67, 17
; VI-NEXT:    v_writelane_b32 v20, s30, 18
; VI-NEXT:    v_writelane_b32 v20, s31, 19
; VI-NEXT:    v_readfirstlane_b32 s7, v5
; VI-NEXT:    v_readfirstlane_b32 s9, v4
; VI-NEXT:    v_readfirstlane_b32 s12, v3
; VI-NEXT:    v_readfirstlane_b32 s15, v2
; VI-NEXT:    v_readfirstlane_b32 s74, v1
; VI-NEXT:    v_readfirstlane_b32 s77, v0
; VI-NEXT:    s_lshr_b32 s11, s29, 16
; VI-NEXT:    s_lshr_b32 s13, s28, 16
; VI-NEXT:    s_lshr_b32 s72, s27, 16
; VI-NEXT:    s_lshr_b32 s75, s26, 16
; VI-NEXT:    s_lshr_b32 s78, s25, 16
; VI-NEXT:    s_lshr_b32 s79, s24, 16
; VI-NEXT:    s_lshr_b32 s88, s23, 16
; VI-NEXT:    s_lshr_b32 s89, s22, 16
; VI-NEXT:    s_lshr_b32 s90, s21, 16
; VI-NEXT:    s_lshr_b32 s91, s20, 16
; VI-NEXT:    s_lshr_b32 s30, s19, 16
; VI-NEXT:    s_lshr_b32 s31, s18, 16
; VI-NEXT:    s_lshr_b32 s34, s17, 16
; VI-NEXT:    s_lshr_b32 s35, s16, 16
; VI-NEXT:    s_lshr_b32 s6, s7, 16
; VI-NEXT:    s_lshr_b32 s8, s9, 16
; VI-NEXT:    s_lshr_b32 s10, s12, 16
; VI-NEXT:    s_lshr_b32 s14, s15, 16
; VI-NEXT:    s_lshr_b32 s73, s74, 16
; VI-NEXT:    s_lshr_b32 s76, s77, 16
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    s_cbranch_scc0 .LBB31_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_and_b32 s4, 0xffff, s16
; VI-NEXT:    s_lshl_b32 s5, s35, 16
; VI-NEXT:    s_or_b32 s36, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s17
; VI-NEXT:    s_lshl_b32 s5, s34, 16
; VI-NEXT:    s_or_b32 s37, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s18
; VI-NEXT:    s_lshl_b32 s5, s31, 16
; VI-NEXT:    s_or_b32 s38, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s19
; VI-NEXT:    s_lshl_b32 s5, s30, 16
; VI-NEXT:    s_or_b32 s39, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s20
; VI-NEXT:    s_lshl_b32 s5, s91, 16
; VI-NEXT:    s_or_b32 s40, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s21
; VI-NEXT:    s_lshl_b32 s5, s90, 16
; VI-NEXT:    s_or_b32 s41, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s22
; VI-NEXT:    s_lshl_b32 s5, s89, 16
; VI-NEXT:    s_or_b32 s42, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s23
; VI-NEXT:    s_lshl_b32 s5, s88, 16
; VI-NEXT:    s_or_b32 s43, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s24
; VI-NEXT:    s_lshl_b32 s5, s79, 16
; VI-NEXT:    s_or_b32 s44, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s25
; VI-NEXT:    s_lshl_b32 s5, s78, 16
; VI-NEXT:    s_or_b32 s45, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s26
; VI-NEXT:    s_lshl_b32 s5, s75, 16
; VI-NEXT:    s_or_b32 s46, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s27
; VI-NEXT:    s_lshl_b32 s5, s72, 16
; VI-NEXT:    s_or_b32 s47, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s28
; VI-NEXT:    s_lshl_b32 s5, s13, 16
; VI-NEXT:    s_or_b32 s48, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s29
; VI-NEXT:    s_lshl_b32 s5, s11, 16
; VI-NEXT:    s_or_b32 s49, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s77
; VI-NEXT:    s_lshl_b32 s5, s76, 16
; VI-NEXT:    s_or_b32 s50, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s74
; VI-NEXT:    s_lshl_b32 s5, s73, 16
; VI-NEXT:    s_or_b32 s51, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s15
; VI-NEXT:    s_lshl_b32 s5, s14, 16
; VI-NEXT:    s_or_b32 s52, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s12
; VI-NEXT:    s_lshl_b32 s5, s10, 16
; VI-NEXT:    s_or_b32 s53, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s9
; VI-NEXT:    s_lshl_b32 s5, s8, 16
; VI-NEXT:    s_or_b32 s54, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s7
; VI-NEXT:    s_lshl_b32 s5, s6, 16
; VI-NEXT:    s_or_b32 s55, s4, s5
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    s_cbranch_execnz .LBB31_3
; VI-NEXT:  .LBB31_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s16, s16, 3
; VI-NEXT:    s_and_b32 s4, s16, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s35, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s17, s17, 3
; VI-NEXT:    s_add_i32 s36, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s17, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s34, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s18, s18, 3
; VI-NEXT:    s_add_i32 s37, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s18, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s31, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s19, s19, 3
; VI-NEXT:    s_add_i32 s38, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s19, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s30, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s20, s20, 3
; VI-NEXT:    s_add_i32 s39, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s20, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s91, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s21, s21, 3
; VI-NEXT:    s_add_i32 s40, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s21, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s90, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s22, s22, 3
; VI-NEXT:    s_add_i32 s41, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s22, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s89, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s23, s23, 3
; VI-NEXT:    s_add_i32 s42, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s23, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s88, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s24, s24, 3
; VI-NEXT:    s_add_i32 s43, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s24, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s79, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s25, s25, 3
; VI-NEXT:    s_add_i32 s44, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s25, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s78, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s26, s26, 3
; VI-NEXT:    s_add_i32 s45, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s26, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s75, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s27, s27, 3
; VI-NEXT:    s_add_i32 s46, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s27, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s72, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s28, s28, 3
; VI-NEXT:    s_add_i32 s47, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s28, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s13, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s29, s29, 3
; VI-NEXT:    s_add_i32 s48, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s29, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s11, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s77, s77, 3
; VI-NEXT:    s_add_i32 s49, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s77, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s76, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s74, s74, 3
; VI-NEXT:    s_add_i32 s50, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s74, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s73, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s15, s15, 3
; VI-NEXT:    s_add_i32 s51, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s15, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s14, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s12, s12, 3
; VI-NEXT:    s_add_i32 s52, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s12, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s10, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s9, s9, 3
; VI-NEXT:    s_add_i32 s53, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s9, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s8, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s7, s7, 3
; VI-NEXT:    s_add_i32 s54, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s7, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s6, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s55, s4, 0x30000
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:  .LBB31_3: ; %end
; VI-NEXT:    v_readlane_b32 s30, v20, 18
; VI-NEXT:    v_mov_b32_e32 v0, s36
; VI-NEXT:    v_mov_b32_e32 v1, s37
; VI-NEXT:    v_mov_b32_e32 v2, s38
; VI-NEXT:    v_mov_b32_e32 v3, s39
; VI-NEXT:    v_mov_b32_e32 v4, s40
; VI-NEXT:    v_mov_b32_e32 v5, s41
; VI-NEXT:    v_mov_b32_e32 v6, s42
; VI-NEXT:    v_mov_b32_e32 v7, s43
; VI-NEXT:    v_mov_b32_e32 v8, s44
; VI-NEXT:    v_mov_b32_e32 v9, s45
; VI-NEXT:    v_mov_b32_e32 v10, s46
; VI-NEXT:    v_mov_b32_e32 v11, s47
; VI-NEXT:    v_mov_b32_e32 v12, s48
; VI-NEXT:    v_mov_b32_e32 v13, s49
; VI-NEXT:    v_mov_b32_e32 v14, s50
; VI-NEXT:    v_mov_b32_e32 v15, s51
; VI-NEXT:    v_mov_b32_e32 v16, s52
; VI-NEXT:    v_mov_b32_e32 v17, s53
; VI-NEXT:    v_mov_b32_e32 v18, s54
; VI-NEXT:    v_mov_b32_e32 v19, s55
; VI-NEXT:    v_readlane_b32 s31, v20, 19
; VI-NEXT:    v_readlane_b32 s67, v20, 17
; VI-NEXT:    v_readlane_b32 s66, v20, 16
; VI-NEXT:    v_readlane_b32 s65, v20, 15
; VI-NEXT:    v_readlane_b32 s64, v20, 14
; VI-NEXT:    v_readlane_b32 s55, v20, 13
; VI-NEXT:    v_readlane_b32 s54, v20, 12
; VI-NEXT:    v_readlane_b32 s53, v20, 11
; VI-NEXT:    v_readlane_b32 s52, v20, 10
; VI-NEXT:    v_readlane_b32 s51, v20, 9
; VI-NEXT:    v_readlane_b32 s50, v20, 8
; VI-NEXT:    v_readlane_b32 s49, v20, 7
; VI-NEXT:    v_readlane_b32 s48, v20, 6
; VI-NEXT:    v_readlane_b32 s39, v20, 5
; VI-NEXT:    v_readlane_b32 s38, v20, 4
; VI-NEXT:    v_readlane_b32 s37, v20, 3
; VI-NEXT:    v_readlane_b32 s36, v20, 2
; VI-NEXT:    v_readlane_b32 s35, v20, 1
; VI-NEXT:    v_readlane_b32 s34, v20, 0
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_load_dword v20, off, s[0:3], s32 ; 4-byte Folded Reload
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB31_4:
; VI-NEXT:    ; implicit-def: $sgpr36_sgpr37_sgpr38_sgpr39_sgpr40_sgpr41_sgpr42_sgpr43_sgpr44_sgpr45_sgpr46_sgpr47_sgpr48_sgpr49_sgpr50_sgpr51_sgpr52_sgpr53_sgpr54_sgpr55_sgpr56_sgpr57_sgpr58_sgpr59_sgpr60_sgpr61_sgpr62_sgpr63_sgpr64_sgpr65_sgpr66_sgpr67
; VI-NEXT:    s_branch .LBB31_2
;
; GFX9-LABEL: bitcast_v40i16_to_v20f32_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    v_writelane_b32 v32, s36, 0
; GFX9-NEXT:    v_writelane_b32 v32, s37, 1
; GFX9-NEXT:    v_writelane_b32 v32, s38, 2
; GFX9-NEXT:    v_writelane_b32 v32, s39, 3
; GFX9-NEXT:    v_writelane_b32 v32, s48, 4
; GFX9-NEXT:    v_writelane_b32 v32, s49, 5
; GFX9-NEXT:    v_writelane_b32 v32, s50, 6
; GFX9-NEXT:    v_writelane_b32 v32, s51, 7
; GFX9-NEXT:    v_writelane_b32 v32, s52, 8
; GFX9-NEXT:    v_writelane_b32 v32, s53, 9
; GFX9-NEXT:    v_writelane_b32 v32, s54, 10
; GFX9-NEXT:    v_writelane_b32 v32, s55, 11
; GFX9-NEXT:    v_readfirstlane_b32 s56, v5
; GFX9-NEXT:    v_readfirstlane_b32 s58, v4
; GFX9-NEXT:    v_readfirstlane_b32 s60, v3
; GFX9-NEXT:    v_readfirstlane_b32 s62, v2
; GFX9-NEXT:    v_readfirstlane_b32 s72, v1
; GFX9-NEXT:    v_readfirstlane_b32 s74, v0
; GFX9-NEXT:    s_lshr_b32 s4, s29, 16
; GFX9-NEXT:    s_lshr_b32 s5, s28, 16
; GFX9-NEXT:    s_lshr_b32 s6, s27, 16
; GFX9-NEXT:    s_lshr_b32 s7, s26, 16
; GFX9-NEXT:    s_lshr_b32 s8, s25, 16
; GFX9-NEXT:    s_lshr_b32 s9, s24, 16
; GFX9-NEXT:    s_lshr_b32 s10, s23, 16
; GFX9-NEXT:    s_lshr_b32 s11, s22, 16
; GFX9-NEXT:    s_lshr_b32 s12, s21, 16
; GFX9-NEXT:    s_lshr_b32 s13, s20, 16
; GFX9-NEXT:    s_lshr_b32 s14, s19, 16
; GFX9-NEXT:    s_lshr_b32 s15, s18, 16
; GFX9-NEXT:    s_lshr_b32 s40, s17, 16
; GFX9-NEXT:    s_lshr_b32 s41, s16, 16
; GFX9-NEXT:    s_lshr_b32 s57, s56, 16
; GFX9-NEXT:    s_lshr_b32 s59, s58, 16
; GFX9-NEXT:    s_lshr_b32 s61, s60, 16
; GFX9-NEXT:    s_lshr_b32 s63, s62, 16
; GFX9-NEXT:    s_lshr_b32 s73, s72, 16
; GFX9-NEXT:    s_lshr_b32 s75, s74, 16
; GFX9-NEXT:    v_readfirstlane_b32 s42, v6
; GFX9-NEXT:    s_cmp_lg_u32 s42, 0
; GFX9-NEXT:    s_pack_ll_b32_b16 s36, s16, s41
; GFX9-NEXT:    s_pack_ll_b32_b16 s37, s17, s40
; GFX9-NEXT:    s_pack_ll_b32_b16 s38, s18, s15
; GFX9-NEXT:    s_pack_ll_b32_b16 s39, s19, s14
; GFX9-NEXT:    s_pack_ll_b32_b16 s40, s20, s13
; GFX9-NEXT:    s_pack_ll_b32_b16 s41, s21, s12
; GFX9-NEXT:    s_pack_ll_b32_b16 s42, s22, s11
; GFX9-NEXT:    s_pack_ll_b32_b16 s43, s23, s10
; GFX9-NEXT:    s_pack_ll_b32_b16 s44, s24, s9
; GFX9-NEXT:    s_pack_ll_b32_b16 s45, s25, s8
; GFX9-NEXT:    s_pack_ll_b32_b16 s46, s26, s7
; GFX9-NEXT:    s_pack_ll_b32_b16 s47, s27, s6
; GFX9-NEXT:    s_pack_ll_b32_b16 s48, s28, s5
; GFX9-NEXT:    s_pack_ll_b32_b16 s49, s29, s4
; GFX9-NEXT:    s_pack_ll_b32_b16 s50, s74, s75
; GFX9-NEXT:    s_pack_ll_b32_b16 s51, s72, s73
; GFX9-NEXT:    s_pack_ll_b32_b16 s52, s62, s63
; GFX9-NEXT:    s_pack_ll_b32_b16 s53, s60, s61
; GFX9-NEXT:    s_pack_ll_b32_b16 s54, s58, s59
; GFX9-NEXT:    s_pack_ll_b32_b16 s55, s56, s57
; GFX9-NEXT:    s_cbranch_scc0 .LBB31_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB31_4
; GFX9-NEXT:  .LBB31_2: ; %cmp.true
; GFX9-NEXT:    v_pk_add_u16 v0, s36, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v1, s37, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v2, s38, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v3, s39, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v4, s40, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v5, s41, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, s42, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v7, s43, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v8, s44, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v9, s45, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v10, s46, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v11, s47, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v12, s48, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v13, s49, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v14, s50, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v15, s51, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v16, s52, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v17, s53, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v18, s54, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v19, s55, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_branch .LBB31_5
; GFX9-NEXT:  .LBB31_3:
; GFX9-NEXT:    s_branch .LBB31_2
; GFX9-NEXT:  .LBB31_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s36
; GFX9-NEXT:    v_mov_b32_e32 v1, s37
; GFX9-NEXT:    v_mov_b32_e32 v2, s38
; GFX9-NEXT:    v_mov_b32_e32 v3, s39
; GFX9-NEXT:    v_mov_b32_e32 v4, s40
; GFX9-NEXT:    v_mov_b32_e32 v5, s41
; GFX9-NEXT:    v_mov_b32_e32 v6, s42
; GFX9-NEXT:    v_mov_b32_e32 v7, s43
; GFX9-NEXT:    v_mov_b32_e32 v8, s44
; GFX9-NEXT:    v_mov_b32_e32 v9, s45
; GFX9-NEXT:    v_mov_b32_e32 v10, s46
; GFX9-NEXT:    v_mov_b32_e32 v11, s47
; GFX9-NEXT:    v_mov_b32_e32 v12, s48
; GFX9-NEXT:    v_mov_b32_e32 v13, s49
; GFX9-NEXT:    v_mov_b32_e32 v14, s50
; GFX9-NEXT:    v_mov_b32_e32 v15, s51
; GFX9-NEXT:    v_mov_b32_e32 v16, s52
; GFX9-NEXT:    v_mov_b32_e32 v17, s53
; GFX9-NEXT:    v_mov_b32_e32 v18, s54
; GFX9-NEXT:    v_mov_b32_e32 v19, s55
; GFX9-NEXT:    v_mov_b32_e32 v20, s56
; GFX9-NEXT:    v_mov_b32_e32 v21, s57
; GFX9-NEXT:    v_mov_b32_e32 v22, s58
; GFX9-NEXT:    v_mov_b32_e32 v23, s59
; GFX9-NEXT:    v_mov_b32_e32 v24, s60
; GFX9-NEXT:    v_mov_b32_e32 v25, s61
; GFX9-NEXT:    v_mov_b32_e32 v26, s62
; GFX9-NEXT:    v_mov_b32_e32 v27, s63
; GFX9-NEXT:    v_mov_b32_e32 v28, s64
; GFX9-NEXT:    v_mov_b32_e32 v29, s65
; GFX9-NEXT:    v_mov_b32_e32 v30, s66
; GFX9-NEXT:    v_mov_b32_e32 v31, s67
; GFX9-NEXT:  .LBB31_5: ; %end
; GFX9-NEXT:    v_readlane_b32 s55, v32, 11
; GFX9-NEXT:    v_readlane_b32 s54, v32, 10
; GFX9-NEXT:    v_readlane_b32 s53, v32, 9
; GFX9-NEXT:    v_readlane_b32 s52, v32, 8
; GFX9-NEXT:    v_readlane_b32 s51, v32, 7
; GFX9-NEXT:    v_readlane_b32 s50, v32, 6
; GFX9-NEXT:    v_readlane_b32 s49, v32, 5
; GFX9-NEXT:    v_readlane_b32 s48, v32, 4
; GFX9-NEXT:    v_readlane_b32 s39, v32, 3
; GFX9-NEXT:    v_readlane_b32 s38, v32, 2
; GFX9-NEXT:    v_readlane_b32 s37, v32, 1
; GFX9-NEXT:    v_readlane_b32 s36, v32, 0
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v40i16_to_v20f32_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    v_readfirstlane_b32 s45, v1
; GFX11-NEXT:    v_readfirstlane_b32 s46, v0
; GFX11-NEXT:    v_readfirstlane_b32 s56, v2
; GFX11-NEXT:    s_lshr_b32 s41, s29, 16
; GFX11-NEXT:    s_lshr_b32 s42, s28, 16
; GFX11-NEXT:    s_lshr_b32 s15, s27, 16
; GFX11-NEXT:    s_lshr_b32 s14, s26, 16
; GFX11-NEXT:    s_lshr_b32 s13, s25, 16
; GFX11-NEXT:    s_lshr_b32 s12, s24, 16
; GFX11-NEXT:    s_lshr_b32 s11, s23, 16
; GFX11-NEXT:    s_lshr_b32 s10, s22, 16
; GFX11-NEXT:    s_lshr_b32 s9, s21, 16
; GFX11-NEXT:    s_lshr_b32 s8, s20, 16
; GFX11-NEXT:    s_lshr_b32 s7, s19, 16
; GFX11-NEXT:    s_lshr_b32 s6, s18, 16
; GFX11-NEXT:    s_lshr_b32 s5, s17, 16
; GFX11-NEXT:    s_lshr_b32 s4, s16, 16
; GFX11-NEXT:    s_lshr_b32 s43, s3, 16
; GFX11-NEXT:    s_lshr_b32 s44, s2, 16
; GFX11-NEXT:    s_lshr_b32 s47, s1, 16
; GFX11-NEXT:    s_lshr_b32 s57, s0, 16
; GFX11-NEXT:    s_lshr_b32 s58, s45, 16
; GFX11-NEXT:    s_lshr_b32 s59, s46, 16
; GFX11-NEXT:    s_mov_b32 s40, 0
; GFX11-NEXT:    s_cmp_lg_u32 s56, 0
; GFX11-NEXT:    s_pack_ll_b32_b16 s0, s0, s57
; GFX11-NEXT:    s_pack_ll_b32_b16 s1, s1, s47
; GFX11-NEXT:    s_pack_ll_b32_b16 s2, s2, s44
; GFX11-NEXT:    s_pack_ll_b32_b16 s3, s3, s43
; GFX11-NEXT:    s_pack_ll_b32_b16 s4, s16, s4
; GFX11-NEXT:    s_pack_ll_b32_b16 s5, s17, s5
; GFX11-NEXT:    s_pack_ll_b32_b16 s6, s18, s6
; GFX11-NEXT:    s_pack_ll_b32_b16 s7, s19, s7
; GFX11-NEXT:    s_pack_ll_b32_b16 s8, s20, s8
; GFX11-NEXT:    s_pack_ll_b32_b16 s9, s21, s9
; GFX11-NEXT:    s_pack_ll_b32_b16 s10, s22, s10
; GFX11-NEXT:    s_pack_ll_b32_b16 s11, s23, s11
; GFX11-NEXT:    s_pack_ll_b32_b16 s12, s24, s12
; GFX11-NEXT:    s_pack_ll_b32_b16 s13, s25, s13
; GFX11-NEXT:    s_pack_ll_b32_b16 s14, s26, s14
; GFX11-NEXT:    s_pack_ll_b32_b16 s15, s27, s15
; GFX11-NEXT:    s_pack_ll_b32_b16 s16, s28, s42
; GFX11-NEXT:    s_pack_ll_b32_b16 s17, s29, s41
; GFX11-NEXT:    s_pack_ll_b32_b16 s18, s46, s59
; GFX11-NEXT:    s_pack_ll_b32_b16 s19, s45, s58
; GFX11-NEXT:    s_cbranch_scc0 .LBB31_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s40
; GFX11-NEXT:    s_cbranch_vccnz .LBB31_4
; GFX11-NEXT:  .LBB31_2: ; %cmp.true
; GFX11-NEXT:    v_pk_add_u16 v0, s0, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v1, s1, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v2, s2, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v3, s3, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v4, s4, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v5, s5, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v6, s6, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v7, s7, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v8, s8, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v9, s9, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v10, s10, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v11, s11, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v12, s12, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v13, s13, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v14, s14, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v15, s15, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v16, s16, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v17, s17, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v18, s18, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v19, s19, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB31_3:
; GFX11-NEXT:    s_branch .LBB31_2
; GFX11-NEXT:  .LBB31_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    v_dual_mov_b32 v8, s8 :: v_dual_mov_b32 v9, s9
; GFX11-NEXT:    v_dual_mov_b32 v10, s10 :: v_dual_mov_b32 v11, s11
; GFX11-NEXT:    v_dual_mov_b32 v12, s12 :: v_dual_mov_b32 v13, s13
; GFX11-NEXT:    v_dual_mov_b32 v14, s14 :: v_dual_mov_b32 v15, s15
; GFX11-NEXT:    v_dual_mov_b32 v16, s16 :: v_dual_mov_b32 v17, s17
; GFX11-NEXT:    v_dual_mov_b32 v18, s18 :: v_dual_mov_b32 v19, s19
; GFX11-NEXT:    v_dual_mov_b32 v20, s20 :: v_dual_mov_b32 v21, s21
; GFX11-NEXT:    v_dual_mov_b32 v22, s22 :: v_dual_mov_b32 v23, s23
; GFX11-NEXT:    v_dual_mov_b32 v24, s24 :: v_dual_mov_b32 v25, s25
; GFX11-NEXT:    v_dual_mov_b32 v26, s26 :: v_dual_mov_b32 v27, s27
; GFX11-NEXT:    v_dual_mov_b32 v28, s28 :: v_dual_mov_b32 v29, s29
; GFX11-NEXT:    v_dual_mov_b32 v30, s30 :: v_dual_mov_b32 v31, s31
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <40 x i16> %a, splat (i16 3)
  %a2 = bitcast <40 x i16> %a1 to <20 x float>
  br label %end

cmp.false:
  %a3 = bitcast <40 x i16> %a to <20 x float>
  br label %end

end:
  %phi = phi <20 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <20 x float> %phi
}

define <40 x half> @bitcast_v20f32_to_v40f16(<20 x float> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v20f32_to_v40f16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:    ; implicit-def: $vgpr31
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr29
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr26
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr25
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr24
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr30
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr28
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr27
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB32_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_alignbit_b32 v20, v19, v18, 16
; SI-NEXT:    v_alignbit_b32 v21, v17, v16, 16
; SI-NEXT:    v_alignbit_b32 v22, v15, v14, 16
; SI-NEXT:    v_alignbit_b32 v23, v13, v12, 16
; SI-NEXT:    v_alignbit_b32 v24, v11, v10, 16
; SI-NEXT:    v_alignbit_b32 v25, v9, v8, 16
; SI-NEXT:    v_alignbit_b32 v26, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v29, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v31, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v34, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v27, 16, v19
; SI-NEXT:    v_lshrrev_b32_e32 v28, 16, v17
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v15
; SI-NEXT:    v_lshrrev_b32_e32 v32, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v33, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v35, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v36, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v37, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v39, 16, v1
; SI-NEXT:  .LBB32_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB32_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; SI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; SI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; SI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; SI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; SI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; SI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; SI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; SI-NEXT:    v_add_f32_e32 v9, 1.0, v9
; SI-NEXT:    v_add_f32_e32 v8, 1.0, v8
; SI-NEXT:    v_add_f32_e32 v11, 1.0, v11
; SI-NEXT:    v_add_f32_e32 v10, 1.0, v10
; SI-NEXT:    v_add_f32_e32 v13, 1.0, v13
; SI-NEXT:    v_add_f32_e32 v12, 1.0, v12
; SI-NEXT:    v_add_f32_e32 v15, 1.0, v15
; SI-NEXT:    v_add_f32_e32 v14, 1.0, v14
; SI-NEXT:    v_add_f32_e32 v17, 1.0, v17
; SI-NEXT:    v_add_f32_e32 v16, 1.0, v16
; SI-NEXT:    v_add_f32_e32 v19, 1.0, v19
; SI-NEXT:    v_add_f32_e32 v18, 1.0, v18
; SI-NEXT:    v_alignbit_b32 v20, v19, v18, 16
; SI-NEXT:    v_alignbit_b32 v21, v17, v16, 16
; SI-NEXT:    v_alignbit_b32 v22, v15, v14, 16
; SI-NEXT:    v_alignbit_b32 v23, v13, v12, 16
; SI-NEXT:    v_alignbit_b32 v24, v11, v10, 16
; SI-NEXT:    v_alignbit_b32 v25, v9, v8, 16
; SI-NEXT:    v_alignbit_b32 v26, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v29, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v31, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v34, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v27, 16, v19
; SI-NEXT:    v_lshrrev_b32_e32 v28, 16, v17
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v15
; SI-NEXT:    v_lshrrev_b32_e32 v32, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v33, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v35, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v36, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v37, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v39, 16, v1
; SI-NEXT:  .LBB32_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v34, 16, v34
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v31, 16, v31
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v26, 16, v26
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; SI-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; SI-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v16
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; SI-NEXT:    v_or_b32_e32 v0, v0, v34
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v34, 16, v39
; SI-NEXT:    v_or_b32_e32 v2, v2, v31
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v31, 16, v38
; SI-NEXT:    v_or_b32_e32 v4, v4, v29
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v29, 16, v37
; SI-NEXT:    v_or_b32_e32 v6, v6, v26
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v26, 16, v36
; SI-NEXT:    v_or_b32_e32 v8, v8, v25
; SI-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; SI-NEXT:    v_lshlrev_b32_e32 v25, 16, v35
; SI-NEXT:    v_or_b32_e32 v10, v10, v24
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; SI-NEXT:    v_lshlrev_b32_e32 v24, 16, v33
; SI-NEXT:    v_or_b32_e32 v12, v12, v23
; SI-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v32
; SI-NEXT:    v_or_b32_e32 v14, v14, v22
; SI-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v30
; SI-NEXT:    v_or_b32_e32 v16, v16, v21
; SI-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v28
; SI-NEXT:    v_or_b32_e32 v18, v18, v20
; SI-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v27
; SI-NEXT:    v_or_b32_e32 v1, v1, v34
; SI-NEXT:    v_or_b32_e32 v3, v3, v31
; SI-NEXT:    v_or_b32_e32 v5, v5, v29
; SI-NEXT:    v_or_b32_e32 v7, v7, v26
; SI-NEXT:    v_or_b32_e32 v9, v9, v25
; SI-NEXT:    v_or_b32_e32 v11, v11, v24
; SI-NEXT:    v_or_b32_e32 v13, v13, v23
; SI-NEXT:    v_or_b32_e32 v15, v15, v22
; SI-NEXT:    v_or_b32_e32 v17, v17, v21
; SI-NEXT:    v_or_b32_e32 v19, v19, v20
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v20f32_to_v40f16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    ; implicit-def: $vgpr39
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr35
; VI-NEXT:    ; implicit-def: $vgpr34
; VI-NEXT:    ; implicit-def: $vgpr33
; VI-NEXT:    ; implicit-def: $vgpr32
; VI-NEXT:    ; implicit-def: $vgpr31
; VI-NEXT:    ; implicit-def: $vgpr30
; VI-NEXT:    ; implicit-def: $vgpr29
; VI-NEXT:    ; implicit-def: $vgpr28
; VI-NEXT:    ; implicit-def: $vgpr27
; VI-NEXT:    ; implicit-def: $vgpr26
; VI-NEXT:    ; implicit-def: $vgpr25
; VI-NEXT:    ; implicit-def: $vgpr24
; VI-NEXT:    ; implicit-def: $vgpr23
; VI-NEXT:    ; implicit-def: $vgpr22
; VI-NEXT:    ; implicit-def: $vgpr21
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB32_2
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; VI-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; VI-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; VI-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; VI-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; VI-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; VI-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; VI-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; VI-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; VI-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; VI-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; VI-NEXT:  .LBB32_2: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB32_4
; VI-NEXT:  ; %bb.3: ; %cmp.true
; VI-NEXT:    v_add_f32_e32 v19, 1.0, v19
; VI-NEXT:    v_add_f32_e32 v18, 1.0, v18
; VI-NEXT:    v_add_f32_e32 v17, 1.0, v17
; VI-NEXT:    v_add_f32_e32 v16, 1.0, v16
; VI-NEXT:    v_add_f32_e32 v15, 1.0, v15
; VI-NEXT:    v_add_f32_e32 v14, 1.0, v14
; VI-NEXT:    v_add_f32_e32 v13, 1.0, v13
; VI-NEXT:    v_add_f32_e32 v12, 1.0, v12
; VI-NEXT:    v_add_f32_e32 v11, 1.0, v11
; VI-NEXT:    v_add_f32_e32 v10, 1.0, v10
; VI-NEXT:    v_add_f32_e32 v9, 1.0, v9
; VI-NEXT:    v_add_f32_e32 v8, 1.0, v8
; VI-NEXT:    v_add_f32_e32 v7, 1.0, v7
; VI-NEXT:    v_add_f32_e32 v6, 1.0, v6
; VI-NEXT:    v_add_f32_e32 v5, 1.0, v5
; VI-NEXT:    v_add_f32_e32 v4, 1.0, v4
; VI-NEXT:    v_add_f32_e32 v3, 1.0, v3
; VI-NEXT:    v_add_f32_e32 v2, 1.0, v2
; VI-NEXT:    v_add_f32_e32 v1, 1.0, v1
; VI-NEXT:    v_add_f32_e32 v0, 1.0, v0
; VI-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; VI-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; VI-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; VI-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; VI-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; VI-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; VI-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; VI-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; VI-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; VI-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; VI-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; VI-NEXT:  .LBB32_4: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    v_lshlrev_b32_e32 v39, 16, v39
; VI-NEXT:    v_lshlrev_b32_e32 v38, 16, v38
; VI-NEXT:    v_lshlrev_b32_e32 v37, 16, v37
; VI-NEXT:    v_lshlrev_b32_e32 v36, 16, v36
; VI-NEXT:    v_lshlrev_b32_e32 v35, 16, v35
; VI-NEXT:    v_lshlrev_b32_e32 v34, 16, v34
; VI-NEXT:    v_lshlrev_b32_e32 v33, 16, v33
; VI-NEXT:    v_lshlrev_b32_e32 v32, 16, v32
; VI-NEXT:    v_lshlrev_b32_e32 v31, 16, v31
; VI-NEXT:    v_lshlrev_b32_e32 v30, 16, v30
; VI-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; VI-NEXT:    v_lshlrev_b32_e32 v28, 16, v28
; VI-NEXT:    v_lshlrev_b32_e32 v27, 16, v27
; VI-NEXT:    v_lshlrev_b32_e32 v26, 16, v26
; VI-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; VI-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; VI-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; VI-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; VI-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; VI-NEXT:    v_or_b32_sdwa v0, v0, v39 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v1, v1, v38 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v2, v2, v37 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v3, v3, v36 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v4, v4, v35 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v5, v5, v34 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v6, v6, v33 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v7, v7, v32 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v8, v8, v31 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v9, v9, v30 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v10, v10, v29 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v11, v11, v28 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v12, v12, v27 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v13, v13, v26 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v14, v14, v25 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v15, v15, v24 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v16, v16, v23 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v17, v17, v22 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v18, v18, v21 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v19, v19, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v20f32_to_v40f16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    ; implicit-def: $vgpr39
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr35
; GFX9-NEXT:    ; implicit-def: $vgpr34
; GFX9-NEXT:    ; implicit-def: $vgpr33
; GFX9-NEXT:    ; implicit-def: $vgpr32
; GFX9-NEXT:    ; implicit-def: $vgpr31
; GFX9-NEXT:    ; implicit-def: $vgpr30
; GFX9-NEXT:    ; implicit-def: $vgpr29
; GFX9-NEXT:    ; implicit-def: $vgpr28
; GFX9-NEXT:    ; implicit-def: $vgpr27
; GFX9-NEXT:    ; implicit-def: $vgpr26
; GFX9-NEXT:    ; implicit-def: $vgpr25
; GFX9-NEXT:    ; implicit-def: $vgpr24
; GFX9-NEXT:    ; implicit-def: $vgpr23
; GFX9-NEXT:    ; implicit-def: $vgpr22
; GFX9-NEXT:    ; implicit-def: $vgpr21
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB32_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX9-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX9-NEXT:  .LBB32_2: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB32_4
; GFX9-NEXT:  ; %bb.3: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e32 v19, 1.0, v19
; GFX9-NEXT:    v_add_f32_e32 v18, 1.0, v18
; GFX9-NEXT:    v_add_f32_e32 v17, 1.0, v17
; GFX9-NEXT:    v_add_f32_e32 v16, 1.0, v16
; GFX9-NEXT:    v_add_f32_e32 v15, 1.0, v15
; GFX9-NEXT:    v_add_f32_e32 v14, 1.0, v14
; GFX9-NEXT:    v_add_f32_e32 v13, 1.0, v13
; GFX9-NEXT:    v_add_f32_e32 v12, 1.0, v12
; GFX9-NEXT:    v_add_f32_e32 v11, 1.0, v11
; GFX9-NEXT:    v_add_f32_e32 v10, 1.0, v10
; GFX9-NEXT:    v_add_f32_e32 v9, 1.0, v9
; GFX9-NEXT:    v_add_f32_e32 v8, 1.0, v8
; GFX9-NEXT:    v_add_f32_e32 v7, 1.0, v7
; GFX9-NEXT:    v_add_f32_e32 v6, 1.0, v6
; GFX9-NEXT:    v_add_f32_e32 v5, 1.0, v5
; GFX9-NEXT:    v_add_f32_e32 v4, 1.0, v4
; GFX9-NEXT:    v_add_f32_e32 v3, 1.0, v3
; GFX9-NEXT:    v_add_f32_e32 v2, 1.0, v2
; GFX9-NEXT:    v_add_f32_e32 v1, 1.0, v1
; GFX9-NEXT:    v_add_f32_e32 v0, 1.0, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX9-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX9-NEXT:  .LBB32_4: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_mov_b32 s4, 0x5040100
; GFX9-NEXT:    v_perm_b32 v0, v39, v0, s4
; GFX9-NEXT:    v_perm_b32 v1, v38, v1, s4
; GFX9-NEXT:    v_perm_b32 v2, v37, v2, s4
; GFX9-NEXT:    v_perm_b32 v3, v36, v3, s4
; GFX9-NEXT:    v_perm_b32 v4, v35, v4, s4
; GFX9-NEXT:    v_perm_b32 v5, v34, v5, s4
; GFX9-NEXT:    v_perm_b32 v6, v33, v6, s4
; GFX9-NEXT:    v_perm_b32 v7, v32, v7, s4
; GFX9-NEXT:    v_perm_b32 v8, v31, v8, s4
; GFX9-NEXT:    v_perm_b32 v9, v30, v9, s4
; GFX9-NEXT:    v_perm_b32 v10, v29, v10, s4
; GFX9-NEXT:    v_perm_b32 v11, v28, v11, s4
; GFX9-NEXT:    v_perm_b32 v12, v27, v12, s4
; GFX9-NEXT:    v_perm_b32 v13, v26, v13, s4
; GFX9-NEXT:    v_perm_b32 v14, v25, v14, s4
; GFX9-NEXT:    v_perm_b32 v15, v24, v15, s4
; GFX9-NEXT:    v_perm_b32 v16, v23, v16, s4
; GFX9-NEXT:    v_perm_b32 v17, v22, v17, s4
; GFX9-NEXT:    v_perm_b32 v18, v21, v18, s4
; GFX9-NEXT:    v_perm_b32 v19, v20, v19, s4
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v20f32_to_v40f16:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB32_2
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v19, 1.0, v19 :: v_dual_add_f32 v18, 1.0, v18
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v17, 1.0, v17 :: v_dual_add_f32 v16, 1.0, v16
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v15, 1.0, v15 :: v_dual_add_f32 v14, 1.0, v14
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v13, 1.0, v13 :: v_dual_add_f32 v12, 1.0, v12
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v11, 1.0, v11 :: v_dual_add_f32 v10, 1.0, v10
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v9, 1.0, v9 :: v_dual_add_f32 v8, 1.0, v8
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v7, 1.0, v7 :: v_dual_add_f32 v6, 1.0, v6
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v5, 1.0, v5 :: v_dual_add_f32 v4, 1.0, v4
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v3, 1.0, v3 :: v_dual_add_f32 v2, 1.0, v2
; GFX11-TRUE16-NEXT:    v_dual_add_f32 v1, 1.0, v1 :: v_dual_add_f32 v0, 1.0, v0
; GFX11-TRUE16-NEXT:  .LBB32_2: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v20f32_to_v40f16:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr39
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr38
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr37
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr36
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr35
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr34
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr33
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr32
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr31
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr30
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr29
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr28
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr27
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr26
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr25
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr24
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr23
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr22
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr21
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB32_2
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX11-FAKE16-NEXT:  .LBB32_2: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB32_4
; GFX11-FAKE16-NEXT:  ; %bb.3: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v19, 1.0, v19 :: v_dual_add_f32 v18, 1.0, v18
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v17, 1.0, v17 :: v_dual_add_f32 v16, 1.0, v16
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v15, 1.0, v15 :: v_dual_add_f32 v14, 1.0, v14
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v13, 1.0, v13 :: v_dual_add_f32 v12, 1.0, v12
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v11, 1.0, v11 :: v_dual_add_f32 v10, 1.0, v10
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v9, 1.0, v9 :: v_dual_add_f32 v8, 1.0, v8
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v7, 1.0, v7 :: v_dual_add_f32 v6, 1.0, v6
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v5, 1.0, v5 :: v_dual_add_f32 v4, 1.0, v4
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v3, 1.0, v3 :: v_dual_add_f32 v2, 1.0, v2
; GFX11-FAKE16-NEXT:    v_dual_add_f32 v1, 1.0, v1 :: v_dual_add_f32 v0, 1.0, v0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX11-FAKE16-NEXT:  .LBB32_4: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v39, v0, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v38, v1, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v37, v2, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v36, v3, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v35, v4, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v34, v5, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v33, v6, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v32, v7, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, v31, v8, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, v30, v9, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, v29, v10, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, v28, v11, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, v27, v12, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, v26, v13, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v14, v25, v14, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v15, v24, v15, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v16, v23, v16, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v17, v22, v17, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v18, v21, v18, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v19, v20, v19, 0x5040100
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <20 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <20 x float> %a1 to <40 x half>
  br label %end

cmp.false:
  %a3 = bitcast <20 x float> %a to <40 x half>
  br label %end

end:
  %phi = phi <40 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <40 x half> %phi
}

define inreg <40 x half> @bitcast_v20f32_to_v40f16_scalar(<20 x float> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v20f32_to_v40f16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_readfirstlane_b32 s8, v6
; SI-NEXT:    v_readfirstlane_b32 s5, v5
; SI-NEXT:    v_readfirstlane_b32 s4, v4
; SI-NEXT:    v_readfirstlane_b32 s7, v3
; SI-NEXT:    v_readfirstlane_b32 s6, v2
; SI-NEXT:    v_readfirstlane_b32 s9, v1
; SI-NEXT:    s_cmp_lg_u32 s8, 0
; SI-NEXT:    v_readfirstlane_b32 s8, v0
; SI-NEXT:    s_cbranch_scc0 .LBB33_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_lshr_b32 s89, s5, 16
; SI-NEXT:    s_lshr_b32 s88, s7, 16
; SI-NEXT:    s_lshr_b32 s79, s9, 16
; SI-NEXT:    s_lshr_b32 s78, s29, 16
; SI-NEXT:    s_lshr_b32 s77, s27, 16
; SI-NEXT:    s_lshr_b32 s76, s25, 16
; SI-NEXT:    s_lshr_b32 s75, s23, 16
; SI-NEXT:    s_lshr_b32 s74, s21, 16
; SI-NEXT:    s_lshr_b32 s73, s19, 16
; SI-NEXT:    s_lshr_b32 s72, s17, 16
; SI-NEXT:    s_lshr_b64 s[10:11], s[4:5], 16
; SI-NEXT:    s_lshr_b64 s[12:13], s[6:7], 16
; SI-NEXT:    s_lshr_b64 s[14:15], s[8:9], 16
; SI-NEXT:    s_lshr_b64 s[40:41], s[28:29], 16
; SI-NEXT:    s_lshr_b64 s[42:43], s[26:27], 16
; SI-NEXT:    s_lshr_b64 s[44:45], s[24:25], 16
; SI-NEXT:    s_lshr_b64 s[46:47], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[56:57], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[58:59], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[60:61], s[16:17], 16
; SI-NEXT:    s_cbranch_execnz .LBB33_4
; SI-NEXT:  .LBB33_2: ; %cmp.true
; SI-NEXT:    v_add_f32_e64 v19, s5, 1.0
; SI-NEXT:    v_add_f32_e64 v18, s4, 1.0
; SI-NEXT:    v_add_f32_e64 v17, s7, 1.0
; SI-NEXT:    v_add_f32_e64 v16, s6, 1.0
; SI-NEXT:    v_lshr_b64 v[20:21], v[18:19], 16
; SI-NEXT:    v_add_f32_e64 v15, s9, 1.0
; SI-NEXT:    v_add_f32_e64 v14, s8, 1.0
; SI-NEXT:    v_lshr_b64 v[21:22], v[16:17], 16
; SI-NEXT:    v_add_f32_e64 v13, s29, 1.0
; SI-NEXT:    v_add_f32_e64 v12, s28, 1.0
; SI-NEXT:    v_lshr_b64 v[22:23], v[14:15], 16
; SI-NEXT:    v_add_f32_e64 v11, s27, 1.0
; SI-NEXT:    v_add_f32_e64 v10, s26, 1.0
; SI-NEXT:    v_lshr_b64 v[23:24], v[12:13], 16
; SI-NEXT:    v_add_f32_e64 v9, s25, 1.0
; SI-NEXT:    v_add_f32_e64 v8, s24, 1.0
; SI-NEXT:    v_lshr_b64 v[24:25], v[10:11], 16
; SI-NEXT:    v_add_f32_e64 v7, s23, 1.0
; SI-NEXT:    v_add_f32_e64 v6, s22, 1.0
; SI-NEXT:    v_lshr_b64 v[25:26], v[8:9], 16
; SI-NEXT:    v_add_f32_e64 v5, s21, 1.0
; SI-NEXT:    v_add_f32_e64 v4, s20, 1.0
; SI-NEXT:    v_lshr_b64 v[26:27], v[6:7], 16
; SI-NEXT:    v_add_f32_e64 v3, s19, 1.0
; SI-NEXT:    v_add_f32_e64 v2, s18, 1.0
; SI-NEXT:    v_lshr_b64 v[27:28], v[4:5], 16
; SI-NEXT:    v_add_f32_e64 v1, s17, 1.0
; SI-NEXT:    v_add_f32_e64 v0, s16, 1.0
; SI-NEXT:    v_lshr_b64 v[28:29], v[2:3], 16
; SI-NEXT:    v_lshr_b64 v[29:30], v[0:1], 16
; SI-NEXT:    v_lshrrev_b32_e32 v31, 16, v19
; SI-NEXT:    v_lshrrev_b32_e32 v32, 16, v17
; SI-NEXT:    v_lshrrev_b32_e32 v33, 16, v15
; SI-NEXT:    v_lshrrev_b32_e32 v34, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v35, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v36, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v37, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v38, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v39, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v48, 16, v1
; SI-NEXT:    s_branch .LBB33_5
; SI-NEXT:  .LBB33_3:
; SI-NEXT:    ; implicit-def: $sgpr60
; SI-NEXT:    ; implicit-def: $sgpr72
; SI-NEXT:    ; implicit-def: $sgpr58
; SI-NEXT:    ; implicit-def: $sgpr73
; SI-NEXT:    ; implicit-def: $sgpr56
; SI-NEXT:    ; implicit-def: $sgpr74
; SI-NEXT:    ; implicit-def: $sgpr46
; SI-NEXT:    ; implicit-def: $sgpr75
; SI-NEXT:    ; implicit-def: $sgpr44
; SI-NEXT:    ; implicit-def: $sgpr76
; SI-NEXT:    ; implicit-def: $sgpr42
; SI-NEXT:    ; implicit-def: $sgpr77
; SI-NEXT:    ; implicit-def: $sgpr40
; SI-NEXT:    ; implicit-def: $sgpr78
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr79
; SI-NEXT:    ; implicit-def: $sgpr12
; SI-NEXT:    ; implicit-def: $sgpr88
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr89
; SI-NEXT:    s_branch .LBB33_2
; SI-NEXT:  .LBB33_4:
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v2, s18
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v4, s20
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v6, s22
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    v_mov_b32_e32 v8, s24
; SI-NEXT:    v_mov_b32_e32 v9, s25
; SI-NEXT:    v_mov_b32_e32 v10, s26
; SI-NEXT:    v_mov_b32_e32 v11, s27
; SI-NEXT:    v_mov_b32_e32 v12, s28
; SI-NEXT:    v_mov_b32_e32 v13, s29
; SI-NEXT:    v_mov_b32_e32 v14, s8
; SI-NEXT:    v_mov_b32_e32 v15, s9
; SI-NEXT:    v_mov_b32_e32 v16, s6
; SI-NEXT:    v_mov_b32_e32 v17, s7
; SI-NEXT:    v_mov_b32_e32 v18, s4
; SI-NEXT:    v_mov_b32_e32 v19, s5
; SI-NEXT:    v_mov_b32_e32 v48, s72
; SI-NEXT:    v_mov_b32_e32 v39, s73
; SI-NEXT:    v_mov_b32_e32 v38, s74
; SI-NEXT:    v_mov_b32_e32 v37, s75
; SI-NEXT:    v_mov_b32_e32 v36, s76
; SI-NEXT:    v_mov_b32_e32 v35, s77
; SI-NEXT:    v_mov_b32_e32 v34, s78
; SI-NEXT:    v_mov_b32_e32 v33, s79
; SI-NEXT:    v_mov_b32_e32 v32, s88
; SI-NEXT:    v_mov_b32_e32 v31, s89
; SI-NEXT:    v_mov_b32_e32 v20, s10
; SI-NEXT:    v_mov_b32_e32 v21, s12
; SI-NEXT:    v_mov_b32_e32 v22, s14
; SI-NEXT:    v_mov_b32_e32 v23, s40
; SI-NEXT:    v_mov_b32_e32 v24, s42
; SI-NEXT:    v_mov_b32_e32 v25, s44
; SI-NEXT:    v_mov_b32_e32 v26, s46
; SI-NEXT:    v_mov_b32_e32 v27, s56
; SI-NEXT:    v_mov_b32_e32 v28, s58
; SI-NEXT:    v_mov_b32_e32 v29, s60
; SI-NEXT:  .LBB33_5: ; %end
; SI-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v28, 16, v28
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v27, 16, v27
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_lshlrev_b32_e32 v26, 16, v26
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; SI-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v16
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; SI-NEXT:    v_or_b32_e32 v0, v0, v29
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v29, 16, v48
; SI-NEXT:    v_or_b32_e32 v2, v2, v28
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v28, 16, v39
; SI-NEXT:    v_or_b32_e32 v4, v4, v27
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v27, 16, v38
; SI-NEXT:    v_or_b32_e32 v6, v6, v26
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v26, 16, v37
; SI-NEXT:    v_or_b32_e32 v8, v8, v25
; SI-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; SI-NEXT:    v_lshlrev_b32_e32 v25, 16, v36
; SI-NEXT:    v_or_b32_e32 v10, v10, v24
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; SI-NEXT:    v_lshlrev_b32_e32 v24, 16, v35
; SI-NEXT:    v_or_b32_e32 v12, v12, v23
; SI-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v34
; SI-NEXT:    v_or_b32_e32 v14, v14, v22
; SI-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v33
; SI-NEXT:    v_or_b32_e32 v16, v16, v21
; SI-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v32
; SI-NEXT:    v_or_b32_e32 v18, v18, v20
; SI-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v31
; SI-NEXT:    v_or_b32_e32 v1, v1, v29
; SI-NEXT:    v_or_b32_e32 v3, v3, v28
; SI-NEXT:    v_or_b32_e32 v5, v5, v27
; SI-NEXT:    v_or_b32_e32 v7, v7, v26
; SI-NEXT:    v_or_b32_e32 v9, v9, v25
; SI-NEXT:    v_or_b32_e32 v11, v11, v24
; SI-NEXT:    v_or_b32_e32 v13, v13, v23
; SI-NEXT:    v_or_b32_e32 v15, v15, v22
; SI-NEXT:    v_or_b32_e32 v17, v17, v21
; SI-NEXT:    v_or_b32_e32 v19, v19, v20
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v20f32_to_v40f16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    v_readfirstlane_b32 s6, v5
; VI-NEXT:    v_readfirstlane_b32 s7, v4
; VI-NEXT:    v_readfirstlane_b32 s8, v3
; VI-NEXT:    v_readfirstlane_b32 s9, v2
; VI-NEXT:    v_readfirstlane_b32 s10, v1
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    v_readfirstlane_b32 s11, v0
; VI-NEXT:    s_cbranch_scc0 .LBB33_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_lshr_b32 s12, s6, 16
; VI-NEXT:    s_lshr_b32 s13, s7, 16
; VI-NEXT:    s_lshr_b32 s14, s8, 16
; VI-NEXT:    s_lshr_b32 s15, s9, 16
; VI-NEXT:    s_lshr_b32 s40, s10, 16
; VI-NEXT:    s_lshr_b32 s41, s11, 16
; VI-NEXT:    s_lshr_b32 s42, s29, 16
; VI-NEXT:    s_lshr_b32 s43, s28, 16
; VI-NEXT:    s_lshr_b32 s44, s27, 16
; VI-NEXT:    s_lshr_b32 s45, s26, 16
; VI-NEXT:    s_lshr_b32 s46, s25, 16
; VI-NEXT:    s_lshr_b32 s47, s24, 16
; VI-NEXT:    s_lshr_b32 s56, s23, 16
; VI-NEXT:    s_lshr_b32 s57, s22, 16
; VI-NEXT:    s_lshr_b32 s58, s21, 16
; VI-NEXT:    s_lshr_b32 s59, s20, 16
; VI-NEXT:    s_lshr_b32 s60, s19, 16
; VI-NEXT:    s_lshr_b32 s61, s18, 16
; VI-NEXT:    s_lshr_b32 s62, s17, 16
; VI-NEXT:    s_lshr_b32 s63, s16, 16
; VI-NEXT:    s_cbranch_execnz .LBB33_4
; VI-NEXT:  .LBB33_2: ; %cmp.true
; VI-NEXT:    v_add_f32_e64 v19, s6, 1.0
; VI-NEXT:    v_add_f32_e64 v18, s7, 1.0
; VI-NEXT:    v_add_f32_e64 v17, s8, 1.0
; VI-NEXT:    v_add_f32_e64 v16, s9, 1.0
; VI-NEXT:    v_add_f32_e64 v15, s10, 1.0
; VI-NEXT:    v_add_f32_e64 v14, s11, 1.0
; VI-NEXT:    v_add_f32_e64 v13, s29, 1.0
; VI-NEXT:    v_add_f32_e64 v12, s28, 1.0
; VI-NEXT:    v_add_f32_e64 v11, s27, 1.0
; VI-NEXT:    v_add_f32_e64 v10, s26, 1.0
; VI-NEXT:    v_add_f32_e64 v9, s25, 1.0
; VI-NEXT:    v_add_f32_e64 v8, s24, 1.0
; VI-NEXT:    v_add_f32_e64 v7, s23, 1.0
; VI-NEXT:    v_add_f32_e64 v6, s22, 1.0
; VI-NEXT:    v_add_f32_e64 v5, s21, 1.0
; VI-NEXT:    v_add_f32_e64 v4, s20, 1.0
; VI-NEXT:    v_add_f32_e64 v3, s19, 1.0
; VI-NEXT:    v_add_f32_e64 v2, s18, 1.0
; VI-NEXT:    v_add_f32_e64 v1, s17, 1.0
; VI-NEXT:    v_add_f32_e64 v0, s16, 1.0
; VI-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; VI-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; VI-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; VI-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; VI-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; VI-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; VI-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; VI-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; VI-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; VI-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; VI-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; VI-NEXT:    s_branch .LBB33_5
; VI-NEXT:  .LBB33_3:
; VI-NEXT:    ; implicit-def: $sgpr63
; VI-NEXT:    ; implicit-def: $sgpr62
; VI-NEXT:    ; implicit-def: $sgpr61
; VI-NEXT:    ; implicit-def: $sgpr60
; VI-NEXT:    ; implicit-def: $sgpr59
; VI-NEXT:    ; implicit-def: $sgpr58
; VI-NEXT:    ; implicit-def: $sgpr57
; VI-NEXT:    ; implicit-def: $sgpr56
; VI-NEXT:    ; implicit-def: $sgpr47
; VI-NEXT:    ; implicit-def: $sgpr46
; VI-NEXT:    ; implicit-def: $sgpr45
; VI-NEXT:    ; implicit-def: $sgpr44
; VI-NEXT:    ; implicit-def: $sgpr43
; VI-NEXT:    ; implicit-def: $sgpr42
; VI-NEXT:    ; implicit-def: $sgpr41
; VI-NEXT:    ; implicit-def: $sgpr40
; VI-NEXT:    ; implicit-def: $sgpr15
; VI-NEXT:    ; implicit-def: $sgpr14
; VI-NEXT:    ; implicit-def: $sgpr13
; VI-NEXT:    ; implicit-def: $sgpr12
; VI-NEXT:    s_branch .LBB33_2
; VI-NEXT:  .LBB33_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    v_mov_b32_e32 v8, s24
; VI-NEXT:    v_mov_b32_e32 v9, s25
; VI-NEXT:    v_mov_b32_e32 v10, s26
; VI-NEXT:    v_mov_b32_e32 v11, s27
; VI-NEXT:    v_mov_b32_e32 v12, s28
; VI-NEXT:    v_mov_b32_e32 v13, s29
; VI-NEXT:    v_mov_b32_e32 v14, s11
; VI-NEXT:    v_mov_b32_e32 v15, s10
; VI-NEXT:    v_mov_b32_e32 v16, s9
; VI-NEXT:    v_mov_b32_e32 v17, s8
; VI-NEXT:    v_mov_b32_e32 v18, s7
; VI-NEXT:    v_mov_b32_e32 v19, s6
; VI-NEXT:    v_mov_b32_e32 v39, s63
; VI-NEXT:    v_mov_b32_e32 v38, s62
; VI-NEXT:    v_mov_b32_e32 v37, s61
; VI-NEXT:    v_mov_b32_e32 v36, s60
; VI-NEXT:    v_mov_b32_e32 v35, s59
; VI-NEXT:    v_mov_b32_e32 v34, s58
; VI-NEXT:    v_mov_b32_e32 v33, s57
; VI-NEXT:    v_mov_b32_e32 v32, s56
; VI-NEXT:    v_mov_b32_e32 v31, s47
; VI-NEXT:    v_mov_b32_e32 v30, s46
; VI-NEXT:    v_mov_b32_e32 v29, s45
; VI-NEXT:    v_mov_b32_e32 v28, s44
; VI-NEXT:    v_mov_b32_e32 v27, s43
; VI-NEXT:    v_mov_b32_e32 v26, s42
; VI-NEXT:    v_mov_b32_e32 v25, s41
; VI-NEXT:    v_mov_b32_e32 v24, s40
; VI-NEXT:    v_mov_b32_e32 v23, s15
; VI-NEXT:    v_mov_b32_e32 v22, s14
; VI-NEXT:    v_mov_b32_e32 v21, s13
; VI-NEXT:    v_mov_b32_e32 v20, s12
; VI-NEXT:  .LBB33_5: ; %end
; VI-NEXT:    v_lshlrev_b32_e32 v39, 16, v39
; VI-NEXT:    v_lshlrev_b32_e32 v38, 16, v38
; VI-NEXT:    v_lshlrev_b32_e32 v37, 16, v37
; VI-NEXT:    v_lshlrev_b32_e32 v36, 16, v36
; VI-NEXT:    v_lshlrev_b32_e32 v35, 16, v35
; VI-NEXT:    v_lshlrev_b32_e32 v34, 16, v34
; VI-NEXT:    v_lshlrev_b32_e32 v33, 16, v33
; VI-NEXT:    v_lshlrev_b32_e32 v32, 16, v32
; VI-NEXT:    v_lshlrev_b32_e32 v31, 16, v31
; VI-NEXT:    v_lshlrev_b32_e32 v30, 16, v30
; VI-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; VI-NEXT:    v_lshlrev_b32_e32 v28, 16, v28
; VI-NEXT:    v_lshlrev_b32_e32 v27, 16, v27
; VI-NEXT:    v_lshlrev_b32_e32 v26, 16, v26
; VI-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; VI-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; VI-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; VI-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; VI-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; VI-NEXT:    v_or_b32_sdwa v0, v0, v39 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v1, v1, v38 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v2, v2, v37 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v3, v3, v36 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v4, v4, v35 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v5, v5, v34 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v6, v6, v33 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v7, v7, v32 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v8, v8, v31 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v9, v9, v30 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v10, v10, v29 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v11, v11, v28 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v12, v12, v27 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v13, v13, v26 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v14, v14, v25 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v15, v15, v24 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v16, v16, v23 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v17, v17, v22 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v18, v18, v21 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v19, v19, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v20f32_to_v40f16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_readfirstlane_b32 s4, v6
; GFX9-NEXT:    v_readfirstlane_b32 s6, v5
; GFX9-NEXT:    v_readfirstlane_b32 s7, v4
; GFX9-NEXT:    v_readfirstlane_b32 s8, v3
; GFX9-NEXT:    v_readfirstlane_b32 s9, v2
; GFX9-NEXT:    v_readfirstlane_b32 s10, v1
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    v_readfirstlane_b32 s11, v0
; GFX9-NEXT:    s_cbranch_scc0 .LBB33_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_lshr_b32 s12, s6, 16
; GFX9-NEXT:    s_lshr_b32 s13, s7, 16
; GFX9-NEXT:    s_lshr_b32 s14, s8, 16
; GFX9-NEXT:    s_lshr_b32 s15, s9, 16
; GFX9-NEXT:    s_lshr_b32 s40, s10, 16
; GFX9-NEXT:    s_lshr_b32 s41, s11, 16
; GFX9-NEXT:    s_lshr_b32 s42, s29, 16
; GFX9-NEXT:    s_lshr_b32 s43, s28, 16
; GFX9-NEXT:    s_lshr_b32 s44, s27, 16
; GFX9-NEXT:    s_lshr_b32 s45, s26, 16
; GFX9-NEXT:    s_lshr_b32 s46, s25, 16
; GFX9-NEXT:    s_lshr_b32 s47, s24, 16
; GFX9-NEXT:    s_lshr_b32 s56, s23, 16
; GFX9-NEXT:    s_lshr_b32 s57, s22, 16
; GFX9-NEXT:    s_lshr_b32 s58, s21, 16
; GFX9-NEXT:    s_lshr_b32 s59, s20, 16
; GFX9-NEXT:    s_lshr_b32 s60, s19, 16
; GFX9-NEXT:    s_lshr_b32 s61, s18, 16
; GFX9-NEXT:    s_lshr_b32 s62, s17, 16
; GFX9-NEXT:    s_lshr_b32 s63, s16, 16
; GFX9-NEXT:    s_cbranch_execnz .LBB33_4
; GFX9-NEXT:  .LBB33_2: ; %cmp.true
; GFX9-NEXT:    v_add_f32_e64 v19, s6, 1.0
; GFX9-NEXT:    v_add_f32_e64 v18, s7, 1.0
; GFX9-NEXT:    v_add_f32_e64 v17, s8, 1.0
; GFX9-NEXT:    v_add_f32_e64 v16, s9, 1.0
; GFX9-NEXT:    v_add_f32_e64 v15, s10, 1.0
; GFX9-NEXT:    v_add_f32_e64 v14, s11, 1.0
; GFX9-NEXT:    v_add_f32_e64 v13, s29, 1.0
; GFX9-NEXT:    v_add_f32_e64 v12, s28, 1.0
; GFX9-NEXT:    v_add_f32_e64 v11, s27, 1.0
; GFX9-NEXT:    v_add_f32_e64 v10, s26, 1.0
; GFX9-NEXT:    v_add_f32_e64 v9, s25, 1.0
; GFX9-NEXT:    v_add_f32_e64 v8, s24, 1.0
; GFX9-NEXT:    v_add_f32_e64 v7, s23, 1.0
; GFX9-NEXT:    v_add_f32_e64 v6, s22, 1.0
; GFX9-NEXT:    v_add_f32_e64 v5, s21, 1.0
; GFX9-NEXT:    v_add_f32_e64 v4, s20, 1.0
; GFX9-NEXT:    v_add_f32_e64 v3, s19, 1.0
; GFX9-NEXT:    v_add_f32_e64 v2, s18, 1.0
; GFX9-NEXT:    v_add_f32_e64 v1, s17, 1.0
; GFX9-NEXT:    v_add_f32_e64 v0, s16, 1.0
; GFX9-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX9-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX9-NEXT:    s_branch .LBB33_5
; GFX9-NEXT:  .LBB33_3:
; GFX9-NEXT:    ; implicit-def: $sgpr63
; GFX9-NEXT:    ; implicit-def: $sgpr62
; GFX9-NEXT:    ; implicit-def: $sgpr61
; GFX9-NEXT:    ; implicit-def: $sgpr60
; GFX9-NEXT:    ; implicit-def: $sgpr59
; GFX9-NEXT:    ; implicit-def: $sgpr58
; GFX9-NEXT:    ; implicit-def: $sgpr57
; GFX9-NEXT:    ; implicit-def: $sgpr56
; GFX9-NEXT:    ; implicit-def: $sgpr47
; GFX9-NEXT:    ; implicit-def: $sgpr46
; GFX9-NEXT:    ; implicit-def: $sgpr45
; GFX9-NEXT:    ; implicit-def: $sgpr44
; GFX9-NEXT:    ; implicit-def: $sgpr43
; GFX9-NEXT:    ; implicit-def: $sgpr42
; GFX9-NEXT:    ; implicit-def: $sgpr41
; GFX9-NEXT:    ; implicit-def: $sgpr40
; GFX9-NEXT:    ; implicit-def: $sgpr15
; GFX9-NEXT:    ; implicit-def: $sgpr14
; GFX9-NEXT:    ; implicit-def: $sgpr13
; GFX9-NEXT:    ; implicit-def: $sgpr12
; GFX9-NEXT:    s_branch .LBB33_2
; GFX9-NEXT:  .LBB33_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    v_mov_b32_e32 v8, s24
; GFX9-NEXT:    v_mov_b32_e32 v9, s25
; GFX9-NEXT:    v_mov_b32_e32 v10, s26
; GFX9-NEXT:    v_mov_b32_e32 v11, s27
; GFX9-NEXT:    v_mov_b32_e32 v12, s28
; GFX9-NEXT:    v_mov_b32_e32 v13, s29
; GFX9-NEXT:    v_mov_b32_e32 v14, s11
; GFX9-NEXT:    v_mov_b32_e32 v15, s10
; GFX9-NEXT:    v_mov_b32_e32 v16, s9
; GFX9-NEXT:    v_mov_b32_e32 v17, s8
; GFX9-NEXT:    v_mov_b32_e32 v18, s7
; GFX9-NEXT:    v_mov_b32_e32 v19, s6
; GFX9-NEXT:    v_mov_b32_e32 v39, s63
; GFX9-NEXT:    v_mov_b32_e32 v38, s62
; GFX9-NEXT:    v_mov_b32_e32 v37, s61
; GFX9-NEXT:    v_mov_b32_e32 v36, s60
; GFX9-NEXT:    v_mov_b32_e32 v35, s59
; GFX9-NEXT:    v_mov_b32_e32 v34, s58
; GFX9-NEXT:    v_mov_b32_e32 v33, s57
; GFX9-NEXT:    v_mov_b32_e32 v32, s56
; GFX9-NEXT:    v_mov_b32_e32 v31, s47
; GFX9-NEXT:    v_mov_b32_e32 v30, s46
; GFX9-NEXT:    v_mov_b32_e32 v29, s45
; GFX9-NEXT:    v_mov_b32_e32 v28, s44
; GFX9-NEXT:    v_mov_b32_e32 v27, s43
; GFX9-NEXT:    v_mov_b32_e32 v26, s42
; GFX9-NEXT:    v_mov_b32_e32 v25, s41
; GFX9-NEXT:    v_mov_b32_e32 v24, s40
; GFX9-NEXT:    v_mov_b32_e32 v23, s15
; GFX9-NEXT:    v_mov_b32_e32 v22, s14
; GFX9-NEXT:    v_mov_b32_e32 v21, s13
; GFX9-NEXT:    v_mov_b32_e32 v20, s12
; GFX9-NEXT:  .LBB33_5: ; %end
; GFX9-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; GFX9-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX9-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GFX9-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX9-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; GFX9-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; GFX9-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; GFX9-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; GFX9-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; GFX9-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; GFX9-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; GFX9-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; GFX9-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; GFX9-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; GFX9-NEXT:    v_and_b32_e32 v16, 0xffff, v16
; GFX9-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; GFX9-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; GFX9-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; GFX9-NEXT:    v_lshl_or_b32 v0, v39, 16, v0
; GFX9-NEXT:    v_lshl_or_b32 v1, v38, 16, v1
; GFX9-NEXT:    v_lshl_or_b32 v2, v37, 16, v2
; GFX9-NEXT:    v_lshl_or_b32 v3, v36, 16, v3
; GFX9-NEXT:    v_lshl_or_b32 v4, v35, 16, v4
; GFX9-NEXT:    v_lshl_or_b32 v5, v34, 16, v5
; GFX9-NEXT:    v_lshl_or_b32 v6, v33, 16, v6
; GFX9-NEXT:    v_lshl_or_b32 v7, v32, 16, v7
; GFX9-NEXT:    v_lshl_or_b32 v8, v31, 16, v8
; GFX9-NEXT:    v_lshl_or_b32 v9, v30, 16, v9
; GFX9-NEXT:    v_lshl_or_b32 v10, v29, 16, v10
; GFX9-NEXT:    v_lshl_or_b32 v11, v28, 16, v11
; GFX9-NEXT:    v_lshl_or_b32 v12, v27, 16, v12
; GFX9-NEXT:    v_lshl_or_b32 v13, v26, 16, v13
; GFX9-NEXT:    v_lshl_or_b32 v14, v25, 16, v14
; GFX9-NEXT:    v_lshl_or_b32 v15, v24, 16, v15
; GFX9-NEXT:    v_lshl_or_b32 v16, v23, 16, v16
; GFX9-NEXT:    v_lshl_or_b32 v17, v22, 16, v17
; GFX9-NEXT:    v_lshl_or_b32 v18, v21, 16, v18
; GFX9-NEXT:    v_lshl_or_b32 v19, v20, 16, v19
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v20f32_to_v40f16_scalar:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s6, v2
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s4, v1
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s5, v0
; GFX11-TRUE16-NEXT:    s_cmp_lg_u32 s6, 0
; GFX11-TRUE16-NEXT:    s_mov_b32 s6, 0
; GFX11-TRUE16-NEXT:    s_cbranch_scc0 .LBB33_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-TRUE16-NEXT:    s_lshr_b32 s7, s4, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s8, s5, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s9, s29, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s10, s28, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s11, s27, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s12, s26, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s13, s25, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s14, s24, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s15, s23, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s40, s22, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s41, s21, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s42, s20, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s43, s19, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s44, s18, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s45, s17, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s46, s16, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s47, s3, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s56, s2, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s57, s1, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s58, s0, 16
; GFX11-TRUE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s6
; GFX11-TRUE16-NEXT:    s_cbranch_vccnz .LBB33_4
; GFX11-TRUE16-NEXT:  .LBB33_2: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v19, s4, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v18, s5, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v17, s29, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v16, s28, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v15, s27, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v14, s26, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v13, s25, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v12, s24, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v11, s23, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v10, s22, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v9, s21, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v8, s20, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v7, s19, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v6, s18, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v5, s17, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v4, s16, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v3, s3, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v2, s2, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v1, s1, 1.0
; GFX11-TRUE16-NEXT:    v_add_f32_e64 v0, s0, 1.0
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX11-TRUE16-NEXT:    s_branch .LBB33_5
; GFX11-TRUE16-NEXT:  .LBB33_3:
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr58
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr57
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr56
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr47
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr46
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr45
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr44
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr43
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr42
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr41
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr40
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr15
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr14
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr13
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr12
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr11
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr10
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr9
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr8
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr7
; GFX11-TRUE16-NEXT:    s_branch .LBB33_2
; GFX11-TRUE16-NEXT:  .LBB33_4:
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v4, s16 :: v_dual_mov_b32 v5, s17
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v6, s18 :: v_dual_mov_b32 v7, s19
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v8, s20 :: v_dual_mov_b32 v9, s21
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v10, s22 :: v_dual_mov_b32 v11, s23
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v12, s24 :: v_dual_mov_b32 v13, s25
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v14, s26 :: v_dual_mov_b32 v15, s27
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v16, s28 :: v_dual_mov_b32 v17, s29
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v18, s5 :: v_dual_mov_b32 v19, s4
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v39, s58 :: v_dual_mov_b32 v38, s57
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v37, s56 :: v_dual_mov_b32 v36, s47
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v35, s46 :: v_dual_mov_b32 v34, s45
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v33, s44 :: v_dual_mov_b32 v32, s43
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v31, s42 :: v_dual_mov_b32 v30, s41
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v29, s40 :: v_dual_mov_b32 v28, s15
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v27, s14 :: v_dual_mov_b32 v26, s13
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v25, s12 :: v_dual_mov_b32 v24, s11
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v23, s10 :: v_dual_mov_b32 v22, s9
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v21, s8 :: v_dual_mov_b32 v20, s7
; GFX11-TRUE16-NEXT:  .LBB33_5: ; %end
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.h, v39.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v1.h, v38.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.h, v37.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v3.h, v36.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v4.h, v35.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v5.h, v34.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v6.h, v33.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v7.h, v32.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v8.h, v31.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v9.h, v30.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v10.h, v29.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v11.h, v28.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v12.h, v27.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v13.h, v26.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v14.h, v25.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v15.h, v24.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v16.h, v23.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v17.h, v22.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v18.h, v21.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v19.h, v20.l
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v20f32_to_v40f16_scalar:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s6, v2
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s4, v1
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s5, v0
; GFX11-FAKE16-NEXT:    s_cmp_lg_u32 s6, 0
; GFX11-FAKE16-NEXT:    s_mov_b32 s6, 0
; GFX11-FAKE16-NEXT:    s_cbranch_scc0 .LBB33_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-FAKE16-NEXT:    s_lshr_b32 s7, s4, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s8, s5, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s9, s29, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s10, s28, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s11, s27, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s12, s26, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s13, s25, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s14, s24, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s15, s23, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s40, s22, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s41, s21, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s42, s20, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s43, s19, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s44, s18, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s45, s17, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s46, s16, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s47, s3, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s56, s2, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s57, s1, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s58, s0, 16
; GFX11-FAKE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s6
; GFX11-FAKE16-NEXT:    s_cbranch_vccnz .LBB33_4
; GFX11-FAKE16-NEXT:  .LBB33_2: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v15, s4, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v16, s5, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v17, s29, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v18, s28, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v19, s27, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v10, s26, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v11, s25, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v12, s24, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v13, s23, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v14, s22, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v5, s21, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v6, s20, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v7, s19, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v8, s18, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v9, s17, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v0, s16, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v1, s3, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v2, s2, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v3, s1, 1.0
; GFX11-FAKE16-NEXT:    v_add_f32_e64 v4, s0, 1.0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v20, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v4
; GFX11-FAKE16-NEXT:    s_branch .LBB33_5
; GFX11-FAKE16-NEXT:  .LBB33_3:
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr58
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr57
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr56
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr47
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr46
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr45
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr44
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr43
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr42
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr41
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr40
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr15
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr14
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr13
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr12
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr11
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr10
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr9
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr8
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr7
; GFX11-FAKE16-NEXT:    s_branch .LBB33_2
; GFX11-FAKE16-NEXT:  .LBB33_4:
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v4, s0 :: v_dual_mov_b32 v3, s1
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v1, s3
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v0, s16 :: v_dual_mov_b32 v9, s17
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v8, s18 :: v_dual_mov_b32 v7, s19
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v6, s20 :: v_dual_mov_b32 v5, s21
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v14, s22 :: v_dual_mov_b32 v13, s23
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v12, s24 :: v_dual_mov_b32 v11, s25
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v10, s26 :: v_dual_mov_b32 v19, s27
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v18, s28 :: v_dual_mov_b32 v17, s29
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v16, s5 :: v_dual_mov_b32 v15, s4
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v39, s58 :: v_dual_mov_b32 v38, s57
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v37, s56 :: v_dual_mov_b32 v36, s47
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v35, s46 :: v_dual_mov_b32 v34, s45
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v33, s44 :: v_dual_mov_b32 v32, s43
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v31, s42 :: v_dual_mov_b32 v30, s41
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v29, s40 :: v_dual_mov_b32 v28, s15
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v27, s14 :: v_dual_mov_b32 v26, s13
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v25, s12 :: v_dual_mov_b32 v24, s11
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v23, s10 :: v_dual_mov_b32 v22, s9
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v21, s8 :: v_dual_mov_b32 v20, s7
; GFX11-FAKE16-NEXT:  .LBB33_5: ; %end
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v48, 0xffff, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v49, 0xffff, v0
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v0, v39, 16, v4
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v1, v38, 16, v3
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v3, v36, 16, v48
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v4, v35, 16, v49
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v35, 0xffff, v6
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v36, 0xffff, v5
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v5, v34, 16, v9
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v6, v33, 16, v8
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v8, v31, 16, v35
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v9, v30, 16, v36
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v30, 0xffff, v11
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v31, 0xffff, v10
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v10, v29, 16, v14
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v11, v28, 16, v13
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v13, v26, 16, v30
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v14, v25, 16, v31
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v25, 0xffff, v16
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v26, 0xffff, v15
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v2, v37, 16, v2
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v7, v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v12, v27, 16, v12
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v15, v24, 16, v19
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v16, v23, 16, v18
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v17, v22, 16, v17
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v18, v21, 16, v25
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v19, v20, 16, v26
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <20 x float> %a, splat (float 1.000000e+00)
  %a2 = bitcast <20 x float> %a1 to <40 x half>
  br label %end

cmp.false:
  %a3 = bitcast <20 x float> %a to <40 x half>
  br label %end

end:
  %phi = phi <40 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <40 x half> %phi
}

define <20 x float> @bitcast_v40f16_to_v20f32(<40 x half> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v40f16_to_v20f32:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v63, off, s[0:3], s32 ; 4-byte Folded Spill
; SI-NEXT:    v_mov_b32_e32 v32, v19
; SI-NEXT:    v_mov_b32_e32 v33, v18
; SI-NEXT:    v_mov_b32_e32 v43, v0
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v32
; SI-NEXT:    v_mov_b32_e32 v34, v17
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:64 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v33
; SI-NEXT:    v_mov_b32_e32 v35, v16
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:68 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v34
; SI-NEXT:    v_mov_b32_e32 v36, v15
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:72 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v35
; SI-NEXT:    v_mov_b32_e32 v37, v14
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:76 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v36
; SI-NEXT:    v_mov_b32_e32 v38, v13
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:80 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v37
; SI-NEXT:    v_mov_b32_e32 v39, v12
; SI-NEXT:    v_mov_b32_e32 v48, v11
; SI-NEXT:    v_mov_b32_e32 v49, v10
; SI-NEXT:    v_mov_b32_e32 v50, v9
; SI-NEXT:    v_mov_b32_e32 v51, v8
; SI-NEXT:    v_mov_b32_e32 v52, v7
; SI-NEXT:    v_mov_b32_e32 v53, v6
; SI-NEXT:    v_mov_b32_e32 v54, v5
; SI-NEXT:    v_mov_b32_e32 v55, v4
; SI-NEXT:    v_mov_b32_e32 v40, v3
; SI-NEXT:    v_mov_b32_e32 v41, v2
; SI-NEXT:    v_mov_b32_e32 v42, v1
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:84 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v38
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:88 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v39
; SI-NEXT:    v_lshrrev_b32_e32 v60, 16, v48
; SI-NEXT:    v_lshrrev_b32_e32 v61, 16, v49
; SI-NEXT:    v_lshrrev_b32_e32 v62, 16, v50
; SI-NEXT:    v_lshrrev_b32_e32 v63, 16, v51
; SI-NEXT:    v_lshrrev_b32_e32 v44, 16, v52
; SI-NEXT:    v_lshrrev_b32_e32 v45, 16, v53
; SI-NEXT:    v_lshrrev_b32_e32 v46, 16, v54
; SI-NEXT:    v_lshrrev_b32_e32 v47, 16, v55
; SI-NEXT:    v_lshrrev_b32_e32 v56, 16, v40
; SI-NEXT:    v_lshrrev_b32_e32 v57, 16, v41
; SI-NEXT:    v_lshrrev_b32_e32 v58, 16, v42
; SI-NEXT:    v_lshrrev_b32_e32 v59, 16, v43
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:92 ; 4-byte Folded Spill
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB34_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:92 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:88 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:84 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:80 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:76 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:72 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v43
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v59
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v42
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v58
; SI-NEXT:    v_or_b32_e32 v0, v0, v1
; SI-NEXT:    v_or_b32_e32 v1, v2, v3
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v41
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v57
; SI-NEXT:    v_or_b32_e32 v2, v2, v3
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v40
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v56
; SI-NEXT:    v_or_b32_e32 v3, v3, v4
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v55
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v47
; SI-NEXT:    v_or_b32_e32 v4, v4, v5
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v54
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v46
; SI-NEXT:    v_or_b32_e32 v5, v5, v6
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v53
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v45
; SI-NEXT:    v_or_b32_e32 v6, v6, v7
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v52
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v44
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v51
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v63
; SI-NEXT:    v_or_b32_e32 v8, v8, v9
; SI-NEXT:    v_and_b32_e32 v9, 0xffff, v50
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v62
; SI-NEXT:    v_or_b32_e32 v9, v9, v10
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v49
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v61
; SI-NEXT:    v_or_b32_e32 v10, v10, v11
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v48
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v60
; SI-NEXT:    v_or_b32_e32 v11, v11, v12
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v39
; SI-NEXT:    ; implicit-def: $vgpr43
; SI-NEXT:    ; implicit-def: $vgpr42
; SI-NEXT:    ; implicit-def: $vgpr41
; SI-NEXT:    ; implicit-def: $vgpr40
; SI-NEXT:    ; implicit-def: $vgpr55
; SI-NEXT:    ; implicit-def: $vgpr54
; SI-NEXT:    ; implicit-def: $vgpr53
; SI-NEXT:    ; implicit-def: $vgpr52
; SI-NEXT:    ; implicit-def: $vgpr51
; SI-NEXT:    ; implicit-def: $vgpr50
; SI-NEXT:    ; implicit-def: $vgpr49
; SI-NEXT:    ; implicit-def: $vgpr48
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:    ; implicit-def: $vgpr59
; SI-NEXT:    ; implicit-def: $vgpr58
; SI-NEXT:    ; implicit-def: $vgpr57
; SI-NEXT:    ; implicit-def: $vgpr56
; SI-NEXT:    ; implicit-def: $vgpr47
; SI-NEXT:    ; implicit-def: $vgpr46
; SI-NEXT:    ; implicit-def: $vgpr45
; SI-NEXT:    ; implicit-def: $vgpr44
; SI-NEXT:    ; implicit-def: $vgpr63
; SI-NEXT:    ; implicit-def: $vgpr62
; SI-NEXT:    ; implicit-def: $vgpr61
; SI-NEXT:    ; implicit-def: $vgpr60
; SI-NEXT:    s_waitcnt vmcnt(7)
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v13
; SI-NEXT:    v_or_b32_e32 v12, v12, v13
; SI-NEXT:    v_and_b32_e32 v13, 0xffff, v38
; SI-NEXT:    s_waitcnt vmcnt(6)
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v14
; SI-NEXT:    v_or_b32_e32 v13, v13, v14
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v37
; SI-NEXT:    s_waitcnt vmcnt(5)
; SI-NEXT:    v_lshlrev_b32_e32 v15, 16, v15
; SI-NEXT:    v_or_b32_e32 v14, v14, v15
; SI-NEXT:    v_and_b32_e32 v15, 0xffff, v36
; SI-NEXT:    s_waitcnt vmcnt(4)
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v16
; SI-NEXT:    v_or_b32_e32 v15, v15, v16
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v35
; SI-NEXT:    s_waitcnt vmcnt(3)
; SI-NEXT:    v_lshlrev_b32_e32 v17, 16, v17
; SI-NEXT:    v_or_b32_e32 v16, v16, v17
; SI-NEXT:    v_and_b32_e32 v17, 0xffff, v34
; SI-NEXT:    s_waitcnt vmcnt(2)
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v18
; SI-NEXT:    v_or_b32_e32 v17, v17, v18
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v33
; SI-NEXT:    s_waitcnt vmcnt(1)
; SI-NEXT:    v_lshlrev_b32_e32 v19, 16, v19
; SI-NEXT:    v_or_b32_e32 v18, v18, v19
; SI-NEXT:    v_and_b32_e32 v19, 0xffff, v32
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; SI-NEXT:    v_or_b32_e32 v19, v19, v20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:  .LBB34_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB34_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_cvt_f32_f16_e32 v0, v59
; SI-NEXT:    v_cvt_f32_f16_e32 v2, v58
; SI-NEXT:    v_cvt_f32_f16_e32 v1, v43
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v42
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_or_b32_e32 v0, v1, v0
; SI-NEXT:    v_or_b32_e32 v1, v3, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v2, v57
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v41
; SI-NEXT:    v_cvt_f32_f16_e32 v4, v40
; SI-NEXT:    v_cvt_f32_f16_e32 v5, v55
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_or_b32_e32 v2, v3, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v56
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v6, v54
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v7, v53
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_or_b32_e32 v3, v4, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v4, v47
; SI-NEXT:    v_cvt_f32_f16_e32 v8, v44
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v8, v8
; SI-NEXT:    v_cvt_f32_f16_e32 v9, v52
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_or_b32_e32 v4, v5, v4
; SI-NEXT:    v_cvt_f32_f16_e32 v5, v46
; SI-NEXT:    v_cvt_f32_f16_e32 v10, v51
; SI-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v9
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_add_f32_e32 v10, 0x38000000, v10
; SI-NEXT:    v_cvt_f16_f32_e32 v10, v10
; SI-NEXT:    v_cvt_f32_f16_e32 v11, v61
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_or_b32_e32 v5, v6, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v6, v45
; SI-NEXT:    v_cvt_f32_f16_e32 v12, v49
; SI-NEXT:    v_add_f32_e32 v11, 0x38000000, v11
; SI-NEXT:    v_cvt_f16_f32_e32 v11, v11
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v12, 0x38000000, v12
; SI-NEXT:    v_cvt_f16_f32_e32 v12, v12
; SI-NEXT:    v_cvt_f32_f16_e32 v13, v48
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_or_b32_e32 v6, v7, v6
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v8
; SI-NEXT:    v_cvt_f32_f16_e32 v8, v63
; SI-NEXT:    v_or_b32_e32 v7, v9, v7
; SI-NEXT:    v_cvt_f32_f16_e32 v9, v62
; SI-NEXT:    v_add_f32_e32 v13, 0x38000000, v13
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v8, v8
; SI-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v9
; SI-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:88 ; 4-byte Folded Reload
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_or_b32_e32 v8, v10, v8
; SI-NEXT:    v_cvt_f32_f16_e32 v10, v50
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v13, v13
; SI-NEXT:    v_cvt_f32_f16_e32 v15, v38
; SI-NEXT:    v_add_f32_e32 v10, 0x38000000, v10
; SI-NEXT:    v_cvt_f16_f32_e32 v10, v10
; SI-NEXT:    v_cvt_f32_f16_e32 v16, v37
; SI-NEXT:    v_add_f32_e32 v15, 0x38000000, v15
; SI-NEXT:    v_cvt_f16_f32_e32 v15, v15
; SI-NEXT:    v_or_b32_e32 v9, v10, v9
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v11
; SI-NEXT:    v_or_b32_e32 v10, v12, v10
; SI-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:92 ; 4-byte Folded Reload
; SI-NEXT:    v_cvt_f32_f16_e32 v11, v60
; SI-NEXT:    v_add_f32_e32 v16, 0x38000000, v16
; SI-NEXT:    v_cvt_f16_f32_e32 v16, v16
; SI-NEXT:    v_cvt_f32_f16_e32 v18, v35
; SI-NEXT:    v_add_f32_e32 v11, 0x38000000, v11
; SI-NEXT:    v_cvt_f16_f32_e32 v11, v11
; SI-NEXT:    v_cvt_f32_f16_e32 v19, v34
; SI-NEXT:    v_add_f32_e32 v18, 0x38000000, v18
; SI-NEXT:    v_cvt_f16_f32_e32 v18, v18
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; SI-NEXT:    v_or_b32_e32 v11, v13, v11
; SI-NEXT:    v_cvt_f32_f16_e32 v13, v39
; SI-NEXT:    v_add_f32_e32 v19, 0x38000000, v19
; SI-NEXT:    v_cvt_f16_f32_e32 v19, v19
; SI-NEXT:    v_cvt_f32_f16_e32 v21, v32
; SI-NEXT:    v_add_f32_e32 v13, 0x38000000, v13
; SI-NEXT:    v_cvt_f16_f32_e32 v13, v13
; SI-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:76 ; 4-byte Folded Reload
; SI-NEXT:    v_add_f32_e32 v21, 0x38000000, v21
; SI-NEXT:    v_cvt_f16_f32_e32 v21, v21
; SI-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(3)
; SI-NEXT:    v_cvt_f32_f16_e32 v14, v14
; SI-NEXT:    v_add_f32_e32 v14, 0x38000000, v14
; SI-NEXT:    v_cvt_f16_f32_e32 v14, v14
; SI-NEXT:    s_waitcnt vmcnt(2)
; SI-NEXT:    v_cvt_f32_f16_e32 v12, v12
; SI-NEXT:    v_add_f32_e32 v12, 0x38000000, v12
; SI-NEXT:    v_cvt_f16_f32_e32 v12, v12
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v12
; SI-NEXT:    v_or_b32_e32 v12, v13, v12
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v14
; SI-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:84 ; 4-byte Folded Reload
; SI-NEXT:    v_or_b32_e32 v13, v15, v13
; SI-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:80 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(3)
; SI-NEXT:    v_cvt_f32_f16_e32 v17, v17
; SI-NEXT:    s_waitcnt vmcnt(2)
; SI-NEXT:    v_cvt_f32_f16_e32 v20, v20
; SI-NEXT:    v_add_f32_e32 v17, 0x38000000, v17
; SI-NEXT:    v_cvt_f16_f32_e32 v17, v17
; SI-NEXT:    v_add_f32_e32 v20, 0x38000000, v20
; SI-NEXT:    v_cvt_f16_f32_e32 v20, v20
; SI-NEXT:    s_waitcnt vmcnt(1)
; SI-NEXT:    v_cvt_f32_f16_e32 v14, v14
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_cvt_f32_f16_e32 v15, v15
; SI-NEXT:    v_add_f32_e32 v14, 0x38000000, v14
; SI-NEXT:    v_cvt_f16_f32_e32 v14, v14
; SI-NEXT:    v_add_f32_e32 v15, 0x38000000, v15
; SI-NEXT:    v_cvt_f16_f32_e32 v15, v15
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v14
; SI-NEXT:    v_or_b32_e32 v14, v16, v14
; SI-NEXT:    v_cvt_f32_f16_e32 v16, v36
; SI-NEXT:    v_lshlrev_b32_e32 v15, 16, v15
; SI-NEXT:    v_add_f32_e32 v16, 0x38000000, v16
; SI-NEXT:    v_cvt_f16_f32_e32 v16, v16
; SI-NEXT:    v_or_b32_e32 v15, v16, v15
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v17
; SI-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:72 ; 4-byte Folded Reload
; SI-NEXT:    v_or_b32_e32 v16, v18, v16
; SI-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(1)
; SI-NEXT:    v_cvt_f32_f16_e32 v17, v17
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_cvt_f32_f16_e32 v18, v18
; SI-NEXT:    v_add_f32_e32 v17, 0x38000000, v17
; SI-NEXT:    v_cvt_f16_f32_e32 v17, v17
; SI-NEXT:    v_add_f32_e32 v18, 0x38000000, v18
; SI-NEXT:    v_cvt_f16_f32_e32 v18, v18
; SI-NEXT:    v_lshlrev_b32_e32 v17, 16, v17
; SI-NEXT:    v_or_b32_e32 v17, v19, v17
; SI-NEXT:    v_cvt_f32_f16_e32 v19, v33
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v18
; SI-NEXT:    v_add_f32_e32 v19, 0x38000000, v19
; SI-NEXT:    v_cvt_f16_f32_e32 v19, v19
; SI-NEXT:    v_or_b32_e32 v18, v19, v18
; SI-NEXT:    v_lshlrev_b32_e32 v19, 16, v20
; SI-NEXT:    v_or_b32_e32 v19, v21, v19
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:  .LBB34_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    buffer_load_dword v63, off, s[0:3], s32 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0)
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v40f16_to_v20f32:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; VI-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; VI-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; VI-NEXT:    buffer_store_dword v43, off, s[0:3], s32 ; 4-byte Folded Spill
; VI-NEXT:    v_mov_b32_e32 v32, v19
; VI-NEXT:    v_mov_b32_e32 v33, v18
; VI-NEXT:    v_mov_b32_e32 v34, v17
; VI-NEXT:    v_mov_b32_e32 v35, v16
; VI-NEXT:    v_mov_b32_e32 v36, v15
; VI-NEXT:    v_mov_b32_e32 v37, v14
; VI-NEXT:    v_mov_b32_e32 v38, v13
; VI-NEXT:    v_mov_b32_e32 v39, v12
; VI-NEXT:    v_mov_b32_e32 v48, v11
; VI-NEXT:    v_mov_b32_e32 v49, v10
; VI-NEXT:    v_mov_b32_e32 v50, v9
; VI-NEXT:    v_mov_b32_e32 v51, v8
; VI-NEXT:    v_mov_b32_e32 v52, v7
; VI-NEXT:    v_mov_b32_e32 v53, v6
; VI-NEXT:    v_mov_b32_e32 v54, v5
; VI-NEXT:    v_mov_b32_e32 v55, v4
; VI-NEXT:    v_mov_b32_e32 v40, v3
; VI-NEXT:    v_mov_b32_e32 v41, v2
; VI-NEXT:    v_mov_b32_e32 v42, v1
; VI-NEXT:    v_mov_b32_e32 v43, v0
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB34_2
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_mov_b32_e32 v19, 16
; VI-NEXT:    v_lshlrev_b32_sdwa v0, v19, v43 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v1, v19, v42 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v2, v19, v41 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v3, v19, v40 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v4, v19, v55 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v5, v19, v54 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v6, v19, v53 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v7, v19, v52 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v8, v19, v51 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v9, v19, v50 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v10, v19, v49 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v11, v19, v48 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v12, v19, v39 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v13, v19, v38 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v14, v19, v37 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v15, v19, v36 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v16, v19, v35 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v17, v19, v34 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v18, v19, v33 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v19, v19, v32 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_or_b32_sdwa v0, v43, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v1, v42, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v2, v41, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v3, v40, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v4, v55, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v5, v54, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v6, v53, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v7, v52, v7 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v8, v51, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v9, v50, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v10, v49, v10 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v11, v48, v11 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v12, v39, v12 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v13, v38, v13 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v14, v37, v14 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v15, v36, v15 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v16, v35, v16 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v17, v34, v17 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v18, v33, v18 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v19, v32, v19 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr43
; VI-NEXT:    ; implicit-def: $vgpr42
; VI-NEXT:    ; implicit-def: $vgpr41
; VI-NEXT:    ; implicit-def: $vgpr40
; VI-NEXT:    ; implicit-def: $vgpr55
; VI-NEXT:    ; implicit-def: $vgpr54
; VI-NEXT:    ; implicit-def: $vgpr53
; VI-NEXT:    ; implicit-def: $vgpr52
; VI-NEXT:    ; implicit-def: $vgpr51
; VI-NEXT:    ; implicit-def: $vgpr50
; VI-NEXT:    ; implicit-def: $vgpr49
; VI-NEXT:    ; implicit-def: $vgpr48
; VI-NEXT:    ; implicit-def: $vgpr39
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr35
; VI-NEXT:    ; implicit-def: $vgpr34
; VI-NEXT:    ; implicit-def: $vgpr33
; VI-NEXT:    ; implicit-def: $vgpr32
; VI-NEXT:  .LBB34_2: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB34_4
; VI-NEXT:  ; %bb.3: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v19, 0x200
; VI-NEXT:    v_add_f16_sdwa v0, v43, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v1, 0x200, v43
; VI-NEXT:    v_or_b32_e32 v0, v1, v0
; VI-NEXT:    v_add_f16_sdwa v1, v42, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, 0x200, v42
; VI-NEXT:    v_or_b32_e32 v1, v2, v1
; VI-NEXT:    v_add_f16_sdwa v2, v41, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v3, 0x200, v41
; VI-NEXT:    v_or_b32_e32 v2, v3, v2
; VI-NEXT:    v_add_f16_sdwa v3, v40, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v4, 0x200, v40
; VI-NEXT:    v_or_b32_e32 v3, v4, v3
; VI-NEXT:    v_add_f16_sdwa v4, v55, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v5, 0x200, v55
; VI-NEXT:    v_or_b32_e32 v4, v5, v4
; VI-NEXT:    v_add_f16_sdwa v5, v54, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v6, 0x200, v54
; VI-NEXT:    v_or_b32_e32 v5, v6, v5
; VI-NEXT:    v_add_f16_sdwa v6, v53, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v7, 0x200, v53
; VI-NEXT:    v_or_b32_e32 v6, v7, v6
; VI-NEXT:    v_add_f16_sdwa v7, v52, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v8, 0x200, v52
; VI-NEXT:    v_or_b32_e32 v7, v8, v7
; VI-NEXT:    v_add_f16_sdwa v8, v51, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v9, 0x200, v51
; VI-NEXT:    v_or_b32_e32 v8, v9, v8
; VI-NEXT:    v_add_f16_sdwa v9, v50, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v10, 0x200, v50
; VI-NEXT:    v_or_b32_e32 v9, v10, v9
; VI-NEXT:    v_add_f16_sdwa v10, v49, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v11, 0x200, v49
; VI-NEXT:    v_or_b32_e32 v10, v11, v10
; VI-NEXT:    v_add_f16_sdwa v11, v48, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v12, 0x200, v48
; VI-NEXT:    v_or_b32_e32 v11, v12, v11
; VI-NEXT:    v_add_f16_sdwa v12, v39, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v13, 0x200, v39
; VI-NEXT:    v_or_b32_e32 v12, v13, v12
; VI-NEXT:    v_add_f16_sdwa v13, v38, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v14, 0x200, v38
; VI-NEXT:    v_or_b32_e32 v13, v14, v13
; VI-NEXT:    v_add_f16_sdwa v14, v37, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v15, 0x200, v37
; VI-NEXT:    v_or_b32_e32 v14, v15, v14
; VI-NEXT:    v_add_f16_sdwa v15, v36, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v16, 0x200, v36
; VI-NEXT:    v_or_b32_e32 v15, v16, v15
; VI-NEXT:    v_add_f16_sdwa v16, v35, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v17, 0x200, v35
; VI-NEXT:    v_or_b32_e32 v16, v17, v16
; VI-NEXT:    v_add_f16_sdwa v17, v34, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v18, 0x200, v34
; VI-NEXT:    v_or_b32_e32 v17, v18, v17
; VI-NEXT:    v_add_f16_sdwa v18, v33, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v20, 0x200, v33
; VI-NEXT:    v_or_b32_e32 v18, v20, v18
; VI-NEXT:    v_add_f16_sdwa v19, v32, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v20, 0x200, v32
; VI-NEXT:    v_or_b32_e32 v19, v20, v19
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:  .LBB34_4: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    buffer_load_dword v43, off, s[0:3], s32 ; 4-byte Folded Reload
; VI-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; VI-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; VI-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v40f16_to_v20f32:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v63, off, s[0:3], s32 ; 4-byte Folded Spill
; GFX9-NEXT:    v_mov_b32_e32 v32, v19
; GFX9-NEXT:    v_mov_b32_e32 v33, v18
; GFX9-NEXT:    v_mov_b32_e32 v43, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v32
; GFX9-NEXT:    v_mov_b32_e32 v34, v17
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:64 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v33
; GFX9-NEXT:    v_mov_b32_e32 v35, v16
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:68 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v34
; GFX9-NEXT:    v_mov_b32_e32 v36, v15
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:72 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v35
; GFX9-NEXT:    v_mov_b32_e32 v37, v14
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:76 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v36
; GFX9-NEXT:    v_mov_b32_e32 v38, v13
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:80 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v37
; GFX9-NEXT:    v_mov_b32_e32 v39, v12
; GFX9-NEXT:    v_mov_b32_e32 v48, v11
; GFX9-NEXT:    v_mov_b32_e32 v49, v10
; GFX9-NEXT:    v_mov_b32_e32 v50, v9
; GFX9-NEXT:    v_mov_b32_e32 v51, v8
; GFX9-NEXT:    v_mov_b32_e32 v52, v7
; GFX9-NEXT:    v_mov_b32_e32 v53, v6
; GFX9-NEXT:    v_mov_b32_e32 v54, v5
; GFX9-NEXT:    v_mov_b32_e32 v55, v4
; GFX9-NEXT:    v_mov_b32_e32 v40, v3
; GFX9-NEXT:    v_mov_b32_e32 v41, v2
; GFX9-NEXT:    v_mov_b32_e32 v42, v1
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:84 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v38
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:88 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v39
; GFX9-NEXT:    v_lshrrev_b32_e32 v60, 16, v48
; GFX9-NEXT:    v_lshrrev_b32_e32 v61, 16, v49
; GFX9-NEXT:    v_lshrrev_b32_e32 v62, 16, v50
; GFX9-NEXT:    v_lshrrev_b32_e32 v63, 16, v51
; GFX9-NEXT:    v_lshrrev_b32_e32 v44, 16, v52
; GFX9-NEXT:    v_lshrrev_b32_e32 v45, 16, v53
; GFX9-NEXT:    v_lshrrev_b32_e32 v46, 16, v54
; GFX9-NEXT:    v_lshrrev_b32_e32 v47, 16, v55
; GFX9-NEXT:    v_lshrrev_b32_e32 v56, 16, v40
; GFX9-NEXT:    v_lshrrev_b32_e32 v57, 16, v41
; GFX9-NEXT:    v_lshrrev_b32_e32 v58, 16, v42
; GFX9-NEXT:    v_lshrrev_b32_e32 v59, 16, v43
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:92 ; 4-byte Folded Spill
; GFX9-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB34_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_mov_b32 s6, 0x5040100
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v12, 16, v39
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v13, 16, v38
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v14, 16, v37
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v15, 16, v36
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v16, 16, v35
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v17, 16, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v18, 16, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v19, 16, v32
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    v_perm_b32 v0, v59, v43, s6
; GFX9-NEXT:    v_perm_b32 v1, v58, v42, s6
; GFX9-NEXT:    v_perm_b32 v2, v57, v41, s6
; GFX9-NEXT:    v_perm_b32 v3, v56, v40, s6
; GFX9-NEXT:    v_perm_b32 v4, v47, v55, s6
; GFX9-NEXT:    v_perm_b32 v5, v46, v54, s6
; GFX9-NEXT:    v_perm_b32 v6, v45, v53, s6
; GFX9-NEXT:    v_perm_b32 v7, v44, v52, s6
; GFX9-NEXT:    v_perm_b32 v8, v63, v51, s6
; GFX9-NEXT:    v_perm_b32 v9, v62, v50, s6
; GFX9-NEXT:    v_perm_b32 v10, v61, v49, s6
; GFX9-NEXT:    v_perm_b32 v11, v60, v48, s6
; GFX9-NEXT:    v_perm_b32 v12, v12, v39, s6
; GFX9-NEXT:    v_perm_b32 v13, v13, v38, s6
; GFX9-NEXT:    v_perm_b32 v14, v14, v37, s6
; GFX9-NEXT:    v_perm_b32 v15, v15, v36, s6
; GFX9-NEXT:    v_perm_b32 v16, v16, v35, s6
; GFX9-NEXT:    v_perm_b32 v17, v17, v34, s6
; GFX9-NEXT:    v_perm_b32 v18, v18, v33, s6
; GFX9-NEXT:    v_perm_b32 v19, v19, v32, s6
; GFX9-NEXT:    ; implicit-def: $vgpr43
; GFX9-NEXT:    ; implicit-def: $vgpr42
; GFX9-NEXT:    ; implicit-def: $vgpr41
; GFX9-NEXT:    ; implicit-def: $vgpr40
; GFX9-NEXT:    ; implicit-def: $vgpr55
; GFX9-NEXT:    ; implicit-def: $vgpr54
; GFX9-NEXT:    ; implicit-def: $vgpr53
; GFX9-NEXT:    ; implicit-def: $vgpr52
; GFX9-NEXT:    ; implicit-def: $vgpr51
; GFX9-NEXT:    ; implicit-def: $vgpr50
; GFX9-NEXT:    ; implicit-def: $vgpr49
; GFX9-NEXT:    ; implicit-def: $vgpr48
; GFX9-NEXT:    ; implicit-def: $vgpr39
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr35
; GFX9-NEXT:    ; implicit-def: $vgpr34
; GFX9-NEXT:    ; implicit-def: $vgpr33
; GFX9-NEXT:    ; implicit-def: $vgpr32
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr60
; GFX9-NEXT:    ; implicit-def: $vgpr61
; GFX9-NEXT:    ; implicit-def: $vgpr62
; GFX9-NEXT:    ; implicit-def: $vgpr63
; GFX9-NEXT:    ; implicit-def: $vgpr44
; GFX9-NEXT:    ; implicit-def: $vgpr45
; GFX9-NEXT:    ; implicit-def: $vgpr46
; GFX9-NEXT:    ; implicit-def: $vgpr47
; GFX9-NEXT:    ; implicit-def: $vgpr56
; GFX9-NEXT:    ; implicit-def: $vgpr57
; GFX9-NEXT:    ; implicit-def: $vgpr58
; GFX9-NEXT:    ; implicit-def: $vgpr59
; GFX9-NEXT:  .LBB34_2: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB34_4
; GFX9-NEXT:  ; %bb.3: ; %cmp.true
; GFX9-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:92 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:88 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:84 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:80 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:76 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:72 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; GFX9-NEXT:    s_mov_b32 s6, 0x5040100
; GFX9-NEXT:    v_perm_b32 v0, v59, v43, s6
; GFX9-NEXT:    s_movk_i32 s7, 0x200
; GFX9-NEXT:    v_perm_b32 v1, v58, v42, s6
; GFX9-NEXT:    v_perm_b32 v2, v57, v41, s6
; GFX9-NEXT:    v_perm_b32 v3, v56, v40, s6
; GFX9-NEXT:    v_perm_b32 v4, v47, v55, s6
; GFX9-NEXT:    v_perm_b32 v5, v46, v54, s6
; GFX9-NEXT:    v_perm_b32 v6, v45, v53, s6
; GFX9-NEXT:    v_perm_b32 v7, v44, v52, s6
; GFX9-NEXT:    v_perm_b32 v8, v63, v51, s6
; GFX9-NEXT:    v_perm_b32 v9, v62, v50, s6
; GFX9-NEXT:    v_perm_b32 v10, v61, v49, s6
; GFX9-NEXT:    v_perm_b32 v11, v60, v48, s6
; GFX9-NEXT:    v_pk_add_f16 v0, v0, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v1, v1, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v2, v2, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v3, v3, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v4, v4, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v5, v5, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, v6, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v7, v7, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v8, v8, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v9, v9, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v10, v10, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v11, v11, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_waitcnt vmcnt(7)
; GFX9-NEXT:    v_perm_b32 v12, v12, v39, s6
; GFX9-NEXT:    s_waitcnt vmcnt(6)
; GFX9-NEXT:    v_perm_b32 v13, v13, v38, s6
; GFX9-NEXT:    s_waitcnt vmcnt(5)
; GFX9-NEXT:    v_perm_b32 v14, v14, v37, s6
; GFX9-NEXT:    s_waitcnt vmcnt(4)
; GFX9-NEXT:    v_perm_b32 v15, v15, v36, s6
; GFX9-NEXT:    s_waitcnt vmcnt(3)
; GFX9-NEXT:    v_perm_b32 v16, v16, v35, s6
; GFX9-NEXT:    s_waitcnt vmcnt(2)
; GFX9-NEXT:    v_perm_b32 v17, v17, v34, s6
; GFX9-NEXT:    s_waitcnt vmcnt(1)
; GFX9-NEXT:    v_perm_b32 v18, v18, v33, s6
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    v_perm_b32 v19, v19, v32, s6
; GFX9-NEXT:    v_pk_add_f16 v12, v12, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v13, v13, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v14, v14, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v15, v15, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v16, v16, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v17, v17, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v18, v18, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v19, v19, s7 op_sel_hi:[1,0]
; GFX9-NEXT:  .LBB34_4: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    buffer_load_dword v63, off, s[0:3], s32 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Reload
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v40f16_to_v20f32:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB34_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB34_4
; GFX11-TRUE16-NEXT:  .LBB34_2: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB34_3: ; %cmp.false
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB34_2
; GFX11-TRUE16-NEXT:  .LBB34_4: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v0, 0x200, v0 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v1, 0x200, v1 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v2, 0x200, v2 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v3, 0x200, v3 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v4, 0x200, v4 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v5, 0x200, v5 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v6, 0x200, v6 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v7, 0x200, v7 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v8, 0x200, v8 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v9, 0x200, v9 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v10, 0x200, v10 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v11, 0x200, v11 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v12, 0x200, v12 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v13, 0x200, v13 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v14, 0x200, v14 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v15, 0x200, v15 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v16, 0x200, v16 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v17, 0x200, v17 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v18, 0x200, v18 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v19, 0x200, v19 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v40f16_to_v20f32:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v48, 16, v3
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v20
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v37, v0, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v38, v1, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v39, v2, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v48, v3, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v36, v4, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v35, v5, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v34, v6, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v33, v7, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, v32, v8, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, v31, v9, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, v30, v10, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, v29, v11, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, v28, v12, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, v27, v13, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v14, v26, v14, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v15, v25, v15, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v16, v24, v16, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v17, v23, v17, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v18, v22, v18, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v19, v21, v19, 0x5040100
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB34_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB34_4
; GFX11-FAKE16-NEXT:  .LBB34_2: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB34_3: ; %cmp.false
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB34_2
; GFX11-FAKE16-NEXT:  .LBB34_4: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v0, 0x200, v0 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v1, 0x200, v1 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v2, 0x200, v2 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v3, 0x200, v3 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v4, 0x200, v4 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v5, 0x200, v5 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v6, 0x200, v6 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v7, 0x200, v7 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v8, 0x200, v8 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v9, 0x200, v9 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v10, 0x200, v10 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v11, 0x200, v11 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v12, 0x200, v12 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v13, 0x200, v13 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v14, 0x200, v14 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v15, 0x200, v15 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v16, 0x200, v16 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v17, 0x200, v17 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v18, 0x200, v18 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v19, 0x200, v19 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <40 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <40 x half> %a1 to <20 x float>
  br label %end

cmp.false:
  %a3 = bitcast <40 x half> %a to <20 x float>
  br label %end

end:
  %phi = phi <20 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <20 x float> %phi
}

define inreg <20 x float> @bitcast_v40f16_to_v20f32_scalar(<40 x half> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v40f16_to_v20f32_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_writelane_b32 v32, s36, 0
; SI-NEXT:    v_writelane_b32 v32, s37, 1
; SI-NEXT:    v_writelane_b32 v32, s38, 2
; SI-NEXT:    v_writelane_b32 v32, s39, 3
; SI-NEXT:    v_writelane_b32 v32, s48, 4
; SI-NEXT:    v_writelane_b32 v32, s49, 5
; SI-NEXT:    v_writelane_b32 v32, s50, 6
; SI-NEXT:    v_writelane_b32 v32, s51, 7
; SI-NEXT:    v_writelane_b32 v32, s52, 8
; SI-NEXT:    v_writelane_b32 v32, s53, 9
; SI-NEXT:    v_writelane_b32 v32, s54, 10
; SI-NEXT:    v_writelane_b32 v32, s55, 11
; SI-NEXT:    v_writelane_b32 v32, s64, 12
; SI-NEXT:    v_writelane_b32 v32, s65, 13
; SI-NEXT:    v_writelane_b32 v32, s66, 14
; SI-NEXT:    v_writelane_b32 v32, s67, 15
; SI-NEXT:    v_readfirstlane_b32 s6, v5
; SI-NEXT:    v_readfirstlane_b32 s8, v4
; SI-NEXT:    v_readfirstlane_b32 s10, v3
; SI-NEXT:    v_readfirstlane_b32 s12, v2
; SI-NEXT:    v_readfirstlane_b32 s14, v1
; SI-NEXT:    v_readfirstlane_b32 s73, v0
; SI-NEXT:    s_lshr_b32 s72, s29, 16
; SI-NEXT:    s_lshr_b32 s75, s28, 16
; SI-NEXT:    s_lshr_b32 s76, s27, 16
; SI-NEXT:    s_lshr_b32 s77, s26, 16
; SI-NEXT:    s_lshr_b32 s78, s25, 16
; SI-NEXT:    s_lshr_b32 s79, s24, 16
; SI-NEXT:    s_lshr_b32 s88, s23, 16
; SI-NEXT:    s_lshr_b32 s89, s22, 16
; SI-NEXT:    s_lshr_b32 s90, s21, 16
; SI-NEXT:    s_lshr_b32 s91, s20, 16
; SI-NEXT:    s_lshr_b32 s92, s19, 16
; SI-NEXT:    s_lshr_b32 s93, s18, 16
; SI-NEXT:    s_lshr_b32 s94, s17, 16
; SI-NEXT:    s_lshr_b32 s95, s16, 16
; SI-NEXT:    s_lshr_b32 s7, s6, 16
; SI-NEXT:    s_lshr_b32 s9, s8, 16
; SI-NEXT:    s_lshr_b32 s11, s10, 16
; SI-NEXT:    s_lshr_b32 s13, s12, 16
; SI-NEXT:    s_lshr_b32 s15, s14, 16
; SI-NEXT:    s_lshr_b32 s74, s73, 16
; SI-NEXT:    v_readfirstlane_b32 s4, v6
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    s_cbranch_scc0 .LBB35_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s95, 16
; SI-NEXT:    s_or_b32 s36, s4, s5
; SI-NEXT:    s_and_b32 s4, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s94, 16
; SI-NEXT:    s_or_b32 s37, s4, s5
; SI-NEXT:    s_and_b32 s4, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s93, 16
; SI-NEXT:    s_or_b32 s38, s4, s5
; SI-NEXT:    s_and_b32 s4, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s92, 16
; SI-NEXT:    s_or_b32 s39, s4, s5
; SI-NEXT:    s_and_b32 s4, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s91, 16
; SI-NEXT:    s_or_b32 s40, s4, s5
; SI-NEXT:    s_and_b32 s4, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s90, 16
; SI-NEXT:    s_or_b32 s41, s4, s5
; SI-NEXT:    s_and_b32 s4, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s89, 16
; SI-NEXT:    s_or_b32 s42, s4, s5
; SI-NEXT:    s_and_b32 s4, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s88, 16
; SI-NEXT:    s_or_b32 s43, s4, s5
; SI-NEXT:    s_and_b32 s4, s24, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s79, 16
; SI-NEXT:    s_or_b32 s44, s4, s5
; SI-NEXT:    s_and_b32 s4, s25, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s78, 16
; SI-NEXT:    s_or_b32 s45, s4, s5
; SI-NEXT:    s_and_b32 s4, s26, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s77, 16
; SI-NEXT:    s_or_b32 s46, s4, s5
; SI-NEXT:    s_and_b32 s4, s27, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s76, 16
; SI-NEXT:    s_or_b32 s47, s4, s5
; SI-NEXT:    s_and_b32 s4, s28, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s75, 16
; SI-NEXT:    s_or_b32 s48, s4, s5
; SI-NEXT:    s_and_b32 s4, s29, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s72, 16
; SI-NEXT:    s_or_b32 s49, s4, s5
; SI-NEXT:    s_and_b32 s4, s73, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s74, 16
; SI-NEXT:    s_or_b32 s50, s4, s5
; SI-NEXT:    s_and_b32 s4, s14, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s15, 16
; SI-NEXT:    s_or_b32 s51, s4, s5
; SI-NEXT:    s_and_b32 s4, s12, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s13, 16
; SI-NEXT:    s_or_b32 s52, s4, s5
; SI-NEXT:    s_and_b32 s4, s10, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s11, 16
; SI-NEXT:    s_or_b32 s53, s4, s5
; SI-NEXT:    s_and_b32 s4, s8, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s9, 16
; SI-NEXT:    s_or_b32 s54, s4, s5
; SI-NEXT:    s_and_b32 s4, s6, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s7, 16
; SI-NEXT:    s_or_b32 s55, s4, s5
; SI-NEXT:    ; implicit-def: $sgpr56
; SI-NEXT:    ; implicit-def: $sgpr57
; SI-NEXT:    ; implicit-def: $sgpr58
; SI-NEXT:    ; implicit-def: $sgpr59
; SI-NEXT:    ; implicit-def: $sgpr60
; SI-NEXT:    ; implicit-def: $sgpr61
; SI-NEXT:    ; implicit-def: $sgpr62
; SI-NEXT:    ; implicit-def: $sgpr63
; SI-NEXT:    ; implicit-def: $sgpr64
; SI-NEXT:    ; implicit-def: $sgpr65
; SI-NEXT:    ; implicit-def: $sgpr66
; SI-NEXT:    ; implicit-def: $sgpr67
; SI-NEXT:    s_cbranch_execnz .LBB35_4
; SI-NEXT:  .LBB35_2: ; %cmp.true
; SI-NEXT:    v_cvt_f32_f16_e32 v0, s95
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s16
; SI-NEXT:    v_cvt_f32_f16_e32 v2, s94
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s17
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_cvt_f32_f16_e32 v4, s18
; SI-NEXT:    v_or_b32_e32 v0, v1, v0
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v2, s93
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_or_b32_e32 v1, v3, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s92
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_or_b32_e32 v2, v4, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v4, s19
; SI-NEXT:    v_cvt_f32_f16_e32 v5, s91
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v6, s20
; SI-NEXT:    v_or_b32_e32 v3, v4, v3
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v5, s90
; SI-NEXT:    v_cvt_f32_f16_e32 v7, s21
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_or_b32_e32 v4, v6, v4
; SI-NEXT:    v_cvt_f32_f16_e32 v6, s89
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_or_b32_e32 v5, v7, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v7, s22
; SI-NEXT:    v_cvt_f32_f16_e32 v8, s88
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v8, v8
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_cvt_f32_f16_e32 v9, s23
; SI-NEXT:    v_or_b32_e32 v6, v7, v6
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v8
; SI-NEXT:    v_cvt_f32_f16_e32 v8, s79
; SI-NEXT:    v_cvt_f32_f16_e32 v10, s24
; SI-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v9
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v8, v8
; SI-NEXT:    v_add_f32_e32 v10, 0x38000000, v10
; SI-NEXT:    v_cvt_f16_f32_e32 v10, v10
; SI-NEXT:    v_or_b32_e32 v7, v9, v7
; SI-NEXT:    v_cvt_f32_f16_e32 v9, s78
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_or_b32_e32 v8, v10, v8
; SI-NEXT:    v_cvt_f32_f16_e32 v10, s25
; SI-NEXT:    v_cvt_f32_f16_e32 v11, s77
; SI-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v9
; SI-NEXT:    v_add_f32_e32 v10, 0x38000000, v10
; SI-NEXT:    v_add_f32_e32 v11, 0x38000000, v11
; SI-NEXT:    v_cvt_f16_f32_e32 v10, v10
; SI-NEXT:    v_cvt_f16_f32_e32 v11, v11
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; SI-NEXT:    v_cvt_f32_f16_e32 v12, s26
; SI-NEXT:    v_or_b32_e32 v9, v10, v9
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v11
; SI-NEXT:    v_cvt_f32_f16_e32 v11, s76
; SI-NEXT:    v_cvt_f32_f16_e32 v13, s27
; SI-NEXT:    v_add_f32_e32 v12, 0x38000000, v12
; SI-NEXT:    v_cvt_f16_f32_e32 v12, v12
; SI-NEXT:    v_add_f32_e32 v11, 0x38000000, v11
; SI-NEXT:    v_cvt_f16_f32_e32 v11, v11
; SI-NEXT:    v_add_f32_e32 v13, 0x38000000, v13
; SI-NEXT:    v_cvt_f16_f32_e32 v13, v13
; SI-NEXT:    v_or_b32_e32 v10, v12, v10
; SI-NEXT:    v_cvt_f32_f16_e32 v12, s75
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; SI-NEXT:    v_or_b32_e32 v11, v13, v11
; SI-NEXT:    v_cvt_f32_f16_e32 v13, s28
; SI-NEXT:    v_cvt_f32_f16_e32 v14, s72
; SI-NEXT:    v_add_f32_e32 v12, 0x38000000, v12
; SI-NEXT:    v_cvt_f16_f32_e32 v12, v12
; SI-NEXT:    v_add_f32_e32 v13, 0x38000000, v13
; SI-NEXT:    v_add_f32_e32 v14, 0x38000000, v14
; SI-NEXT:    v_cvt_f16_f32_e32 v13, v13
; SI-NEXT:    v_cvt_f16_f32_e32 v14, v14
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v12
; SI-NEXT:    v_cvt_f32_f16_e32 v15, s29
; SI-NEXT:    v_or_b32_e32 v12, v13, v12
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v14
; SI-NEXT:    v_cvt_f32_f16_e32 v14, s74
; SI-NEXT:    v_cvt_f32_f16_e32 v16, s73
; SI-NEXT:    v_add_f32_e32 v15, 0x38000000, v15
; SI-NEXT:    v_cvt_f16_f32_e32 v15, v15
; SI-NEXT:    v_add_f32_e32 v14, 0x38000000, v14
; SI-NEXT:    v_cvt_f16_f32_e32 v14, v14
; SI-NEXT:    v_add_f32_e32 v16, 0x38000000, v16
; SI-NEXT:    v_cvt_f16_f32_e32 v16, v16
; SI-NEXT:    v_or_b32_e32 v13, v15, v13
; SI-NEXT:    v_cvt_f32_f16_e32 v15, s15
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v14
; SI-NEXT:    v_or_b32_e32 v14, v16, v14
; SI-NEXT:    v_cvt_f32_f16_e32 v16, s14
; SI-NEXT:    v_cvt_f32_f16_e32 v17, s13
; SI-NEXT:    v_add_f32_e32 v15, 0x38000000, v15
; SI-NEXT:    v_cvt_f16_f32_e32 v15, v15
; SI-NEXT:    v_add_f32_e32 v16, 0x38000000, v16
; SI-NEXT:    v_add_f32_e32 v17, 0x38000000, v17
; SI-NEXT:    v_cvt_f16_f32_e32 v16, v16
; SI-NEXT:    v_cvt_f16_f32_e32 v17, v17
; SI-NEXT:    v_lshlrev_b32_e32 v15, 16, v15
; SI-NEXT:    v_cvt_f32_f16_e32 v18, s12
; SI-NEXT:    v_or_b32_e32 v15, v16, v15
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v17
; SI-NEXT:    v_cvt_f32_f16_e32 v17, s11
; SI-NEXT:    v_cvt_f32_f16_e32 v19, s10
; SI-NEXT:    v_add_f32_e32 v18, 0x38000000, v18
; SI-NEXT:    v_cvt_f16_f32_e32 v18, v18
; SI-NEXT:    v_add_f32_e32 v17, 0x38000000, v17
; SI-NEXT:    v_cvt_f16_f32_e32 v17, v17
; SI-NEXT:    v_add_f32_e32 v19, 0x38000000, v19
; SI-NEXT:    v_cvt_f16_f32_e32 v19, v19
; SI-NEXT:    v_or_b32_e32 v16, v18, v16
; SI-NEXT:    v_cvt_f32_f16_e32 v18, s9
; SI-NEXT:    v_lshlrev_b32_e32 v17, 16, v17
; SI-NEXT:    v_or_b32_e32 v17, v19, v17
; SI-NEXT:    v_cvt_f32_f16_e32 v19, s8
; SI-NEXT:    v_cvt_f32_f16_e32 v20, s7
; SI-NEXT:    v_cvt_f32_f16_e32 v21, s6
; SI-NEXT:    v_add_f32_e32 v18, 0x38000000, v18
; SI-NEXT:    v_cvt_f16_f32_e32 v18, v18
; SI-NEXT:    v_add_f32_e32 v19, 0x38000000, v19
; SI-NEXT:    v_add_f32_e32 v20, 0x38000000, v20
; SI-NEXT:    v_cvt_f16_f32_e32 v19, v19
; SI-NEXT:    v_cvt_f16_f32_e32 v20, v20
; SI-NEXT:    v_add_f32_e32 v21, 0x38000000, v21
; SI-NEXT:    v_cvt_f16_f32_e32 v21, v21
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v18
; SI-NEXT:    v_or_b32_e32 v18, v19, v18
; SI-NEXT:    v_lshlrev_b32_e32 v19, 16, v20
; SI-NEXT:    v_or_b32_e32 v19, v21, v19
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    s_branch .LBB35_5
; SI-NEXT:  .LBB35_3:
; SI-NEXT:    ; implicit-def: $sgpr36_sgpr37_sgpr38_sgpr39_sgpr40_sgpr41_sgpr42_sgpr43_sgpr44_sgpr45_sgpr46_sgpr47_sgpr48_sgpr49_sgpr50_sgpr51_sgpr52_sgpr53_sgpr54_sgpr55_sgpr56_sgpr57_sgpr58_sgpr59_sgpr60_sgpr61_sgpr62_sgpr63_sgpr64_sgpr65_sgpr66_sgpr67
; SI-NEXT:    s_branch .LBB35_2
; SI-NEXT:  .LBB35_4:
; SI-NEXT:    v_mov_b32_e32 v0, s36
; SI-NEXT:    v_mov_b32_e32 v1, s37
; SI-NEXT:    v_mov_b32_e32 v2, s38
; SI-NEXT:    v_mov_b32_e32 v3, s39
; SI-NEXT:    v_mov_b32_e32 v4, s40
; SI-NEXT:    v_mov_b32_e32 v5, s41
; SI-NEXT:    v_mov_b32_e32 v6, s42
; SI-NEXT:    v_mov_b32_e32 v7, s43
; SI-NEXT:    v_mov_b32_e32 v8, s44
; SI-NEXT:    v_mov_b32_e32 v9, s45
; SI-NEXT:    v_mov_b32_e32 v10, s46
; SI-NEXT:    v_mov_b32_e32 v11, s47
; SI-NEXT:    v_mov_b32_e32 v12, s48
; SI-NEXT:    v_mov_b32_e32 v13, s49
; SI-NEXT:    v_mov_b32_e32 v14, s50
; SI-NEXT:    v_mov_b32_e32 v15, s51
; SI-NEXT:    v_mov_b32_e32 v16, s52
; SI-NEXT:    v_mov_b32_e32 v17, s53
; SI-NEXT:    v_mov_b32_e32 v18, s54
; SI-NEXT:    v_mov_b32_e32 v19, s55
; SI-NEXT:    v_mov_b32_e32 v20, s56
; SI-NEXT:    v_mov_b32_e32 v21, s57
; SI-NEXT:    v_mov_b32_e32 v22, s58
; SI-NEXT:    v_mov_b32_e32 v23, s59
; SI-NEXT:    v_mov_b32_e32 v24, s60
; SI-NEXT:    v_mov_b32_e32 v25, s61
; SI-NEXT:    v_mov_b32_e32 v26, s62
; SI-NEXT:    v_mov_b32_e32 v27, s63
; SI-NEXT:    v_mov_b32_e32 v28, s64
; SI-NEXT:    v_mov_b32_e32 v29, s65
; SI-NEXT:    v_mov_b32_e32 v30, s66
; SI-NEXT:    v_mov_b32_e32 v31, s67
; SI-NEXT:  .LBB35_5: ; %end
; SI-NEXT:    v_readlane_b32 s67, v32, 15
; SI-NEXT:    v_readlane_b32 s66, v32, 14
; SI-NEXT:    v_readlane_b32 s65, v32, 13
; SI-NEXT:    v_readlane_b32 s64, v32, 12
; SI-NEXT:    v_readlane_b32 s55, v32, 11
; SI-NEXT:    v_readlane_b32 s54, v32, 10
; SI-NEXT:    v_readlane_b32 s53, v32, 9
; SI-NEXT:    v_readlane_b32 s52, v32, 8
; SI-NEXT:    v_readlane_b32 s51, v32, 7
; SI-NEXT:    v_readlane_b32 s50, v32, 6
; SI-NEXT:    v_readlane_b32 s49, v32, 5
; SI-NEXT:    v_readlane_b32 s48, v32, 4
; SI-NEXT:    v_readlane_b32 s39, v32, 3
; SI-NEXT:    v_readlane_b32 s38, v32, 2
; SI-NEXT:    v_readlane_b32 s37, v32, 1
; SI-NEXT:    v_readlane_b32 s36, v32, 0
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v40f16_to_v20f32_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    v_writelane_b32 v32, s34, 0
; VI-NEXT:    v_writelane_b32 v32, s35, 1
; VI-NEXT:    v_writelane_b32 v32, s36, 2
; VI-NEXT:    v_writelane_b32 v32, s37, 3
; VI-NEXT:    v_writelane_b32 v32, s38, 4
; VI-NEXT:    v_writelane_b32 v32, s39, 5
; VI-NEXT:    v_writelane_b32 v32, s48, 6
; VI-NEXT:    v_writelane_b32 v32, s49, 7
; VI-NEXT:    v_writelane_b32 v32, s50, 8
; VI-NEXT:    v_writelane_b32 v32, s51, 9
; VI-NEXT:    v_writelane_b32 v32, s52, 10
; VI-NEXT:    v_writelane_b32 v32, s53, 11
; VI-NEXT:    v_writelane_b32 v32, s54, 12
; VI-NEXT:    v_writelane_b32 v32, s55, 13
; VI-NEXT:    v_writelane_b32 v32, s64, 14
; VI-NEXT:    v_writelane_b32 v32, s65, 15
; VI-NEXT:    v_writelane_b32 v32, s66, 16
; VI-NEXT:    v_writelane_b32 v32, s67, 17
; VI-NEXT:    v_writelane_b32 v32, s30, 18
; VI-NEXT:    v_writelane_b32 v32, s31, 19
; VI-NEXT:    v_readfirstlane_b32 s6, v5
; VI-NEXT:    v_readfirstlane_b32 s8, v4
; VI-NEXT:    v_readfirstlane_b32 s11, v3
; VI-NEXT:    v_readfirstlane_b32 s14, v2
; VI-NEXT:    v_readfirstlane_b32 s73, v1
; VI-NEXT:    v_readfirstlane_b32 s76, v0
; VI-NEXT:    s_lshr_b32 s10, s29, 16
; VI-NEXT:    s_lshr_b32 s13, s28, 16
; VI-NEXT:    s_lshr_b32 s72, s27, 16
; VI-NEXT:    s_lshr_b32 s74, s26, 16
; VI-NEXT:    s_lshr_b32 s77, s25, 16
; VI-NEXT:    s_lshr_b32 s79, s24, 16
; VI-NEXT:    s_lshr_b32 s88, s23, 16
; VI-NEXT:    s_lshr_b32 s89, s22, 16
; VI-NEXT:    s_lshr_b32 s90, s21, 16
; VI-NEXT:    s_lshr_b32 s91, s20, 16
; VI-NEXT:    s_lshr_b32 s30, s19, 16
; VI-NEXT:    s_lshr_b32 s31, s18, 16
; VI-NEXT:    s_lshr_b32 s34, s17, 16
; VI-NEXT:    s_lshr_b32 s35, s16, 16
; VI-NEXT:    s_lshr_b32 s7, s6, 16
; VI-NEXT:    s_lshr_b32 s9, s8, 16
; VI-NEXT:    s_lshr_b32 s12, s11, 16
; VI-NEXT:    s_lshr_b32 s15, s14, 16
; VI-NEXT:    s_lshr_b32 s75, s73, 16
; VI-NEXT:    s_lshr_b32 s78, s76, 16
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    s_cbranch_scc0 .LBB35_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_and_b32 s4, 0xffff, s16
; VI-NEXT:    s_lshl_b32 s5, s35, 16
; VI-NEXT:    s_or_b32 s36, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s17
; VI-NEXT:    s_lshl_b32 s5, s34, 16
; VI-NEXT:    s_or_b32 s37, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s18
; VI-NEXT:    s_lshl_b32 s5, s31, 16
; VI-NEXT:    s_or_b32 s38, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s19
; VI-NEXT:    s_lshl_b32 s5, s30, 16
; VI-NEXT:    s_or_b32 s39, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s20
; VI-NEXT:    s_lshl_b32 s5, s91, 16
; VI-NEXT:    s_or_b32 s40, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s21
; VI-NEXT:    s_lshl_b32 s5, s90, 16
; VI-NEXT:    s_or_b32 s41, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s22
; VI-NEXT:    s_lshl_b32 s5, s89, 16
; VI-NEXT:    s_or_b32 s42, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s23
; VI-NEXT:    s_lshl_b32 s5, s88, 16
; VI-NEXT:    s_or_b32 s43, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s24
; VI-NEXT:    s_lshl_b32 s5, s79, 16
; VI-NEXT:    s_or_b32 s44, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s25
; VI-NEXT:    s_lshl_b32 s5, s77, 16
; VI-NEXT:    s_or_b32 s45, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s26
; VI-NEXT:    s_lshl_b32 s5, s74, 16
; VI-NEXT:    s_or_b32 s46, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s27
; VI-NEXT:    s_lshl_b32 s5, s72, 16
; VI-NEXT:    s_or_b32 s47, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s28
; VI-NEXT:    s_lshl_b32 s5, s13, 16
; VI-NEXT:    s_or_b32 s48, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s29
; VI-NEXT:    s_lshl_b32 s5, s10, 16
; VI-NEXT:    s_or_b32 s49, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s76
; VI-NEXT:    s_lshl_b32 s5, s78, 16
; VI-NEXT:    s_or_b32 s50, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s73
; VI-NEXT:    s_lshl_b32 s5, s75, 16
; VI-NEXT:    s_or_b32 s51, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s14
; VI-NEXT:    s_lshl_b32 s5, s15, 16
; VI-NEXT:    s_or_b32 s52, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s11
; VI-NEXT:    s_lshl_b32 s5, s12, 16
; VI-NEXT:    s_or_b32 s53, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s8
; VI-NEXT:    s_lshl_b32 s5, s9, 16
; VI-NEXT:    s_or_b32 s54, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s6
; VI-NEXT:    s_lshl_b32 s5, s7, 16
; VI-NEXT:    s_or_b32 s55, s4, s5
; VI-NEXT:    ; implicit-def: $sgpr56
; VI-NEXT:    ; implicit-def: $sgpr57
; VI-NEXT:    ; implicit-def: $sgpr58
; VI-NEXT:    ; implicit-def: $sgpr59
; VI-NEXT:    ; implicit-def: $sgpr60
; VI-NEXT:    ; implicit-def: $sgpr61
; VI-NEXT:    ; implicit-def: $sgpr62
; VI-NEXT:    ; implicit-def: $sgpr63
; VI-NEXT:    ; implicit-def: $sgpr64
; VI-NEXT:    ; implicit-def: $sgpr65
; VI-NEXT:    ; implicit-def: $sgpr66
; VI-NEXT:    ; implicit-def: $sgpr67
; VI-NEXT:    s_cbranch_execnz .LBB35_4
; VI-NEXT:  .LBB35_2: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v19, 0x200
; VI-NEXT:    v_mov_b32_e32 v0, s35
; VI-NEXT:    v_mov_b32_e32 v2, s34
; VI-NEXT:    v_add_f16_sdwa v0, v0, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v1, s16, v19
; VI-NEXT:    v_add_f16_sdwa v2, v2, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v3, s17, v19
; VI-NEXT:    v_or_b32_e32 v0, v1, v0
; VI-NEXT:    v_or_b32_e32 v1, v3, v2
; VI-NEXT:    v_mov_b32_e32 v2, s31
; VI-NEXT:    v_add_f16_sdwa v2, v2, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v3, s18, v19
; VI-NEXT:    v_or_b32_e32 v2, v3, v2
; VI-NEXT:    v_mov_b32_e32 v3, s30
; VI-NEXT:    v_add_f16_sdwa v3, v3, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v4, s19, v19
; VI-NEXT:    v_or_b32_e32 v3, v4, v3
; VI-NEXT:    v_mov_b32_e32 v4, s91
; VI-NEXT:    v_add_f16_sdwa v4, v4, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v5, s20, v19
; VI-NEXT:    v_or_b32_e32 v4, v5, v4
; VI-NEXT:    v_mov_b32_e32 v5, s90
; VI-NEXT:    v_add_f16_sdwa v5, v5, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v6, s21, v19
; VI-NEXT:    v_or_b32_e32 v5, v6, v5
; VI-NEXT:    v_mov_b32_e32 v6, s89
; VI-NEXT:    v_add_f16_sdwa v6, v6, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v7, s22, v19
; VI-NEXT:    v_or_b32_e32 v6, v7, v6
; VI-NEXT:    v_mov_b32_e32 v7, s88
; VI-NEXT:    v_add_f16_sdwa v7, v7, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v8, s23, v19
; VI-NEXT:    v_or_b32_e32 v7, v8, v7
; VI-NEXT:    v_mov_b32_e32 v8, s79
; VI-NEXT:    v_add_f16_sdwa v8, v8, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v9, s24, v19
; VI-NEXT:    v_or_b32_e32 v8, v9, v8
; VI-NEXT:    v_mov_b32_e32 v9, s77
; VI-NEXT:    v_add_f16_sdwa v9, v9, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v10, s25, v19
; VI-NEXT:    v_or_b32_e32 v9, v10, v9
; VI-NEXT:    v_mov_b32_e32 v10, s74
; VI-NEXT:    v_add_f16_sdwa v10, v10, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v11, s26, v19
; VI-NEXT:    v_or_b32_e32 v10, v11, v10
; VI-NEXT:    v_mov_b32_e32 v11, s72
; VI-NEXT:    v_add_f16_sdwa v11, v11, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v12, s27, v19
; VI-NEXT:    v_or_b32_e32 v11, v12, v11
; VI-NEXT:    v_mov_b32_e32 v12, s13
; VI-NEXT:    v_add_f16_sdwa v12, v12, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v13, s28, v19
; VI-NEXT:    v_or_b32_e32 v12, v13, v12
; VI-NEXT:    v_mov_b32_e32 v13, s10
; VI-NEXT:    v_add_f16_sdwa v13, v13, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v14, s29, v19
; VI-NEXT:    v_or_b32_e32 v13, v14, v13
; VI-NEXT:    v_mov_b32_e32 v14, s78
; VI-NEXT:    v_add_f16_sdwa v14, v14, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v15, s76, v19
; VI-NEXT:    v_or_b32_e32 v14, v15, v14
; VI-NEXT:    v_mov_b32_e32 v15, s75
; VI-NEXT:    v_add_f16_sdwa v15, v15, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v16, s73, v19
; VI-NEXT:    v_or_b32_e32 v15, v16, v15
; VI-NEXT:    v_mov_b32_e32 v16, s15
; VI-NEXT:    v_add_f16_sdwa v16, v16, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v17, s14, v19
; VI-NEXT:    v_or_b32_e32 v16, v17, v16
; VI-NEXT:    v_mov_b32_e32 v17, s12
; VI-NEXT:    v_add_f16_sdwa v17, v17, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v18, s11, v19
; VI-NEXT:    v_or_b32_e32 v17, v18, v17
; VI-NEXT:    v_mov_b32_e32 v18, s9
; VI-NEXT:    v_add_f16_sdwa v18, v18, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v20, s8, v19
; VI-NEXT:    v_or_b32_e32 v18, v20, v18
; VI-NEXT:    v_mov_b32_e32 v20, s7
; VI-NEXT:    v_add_f16_sdwa v20, v20, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v19, s6, v19
; VI-NEXT:    v_or_b32_e32 v19, v19, v20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    s_branch .LBB35_5
; VI-NEXT:  .LBB35_3:
; VI-NEXT:    ; implicit-def: $sgpr36_sgpr37_sgpr38_sgpr39_sgpr40_sgpr41_sgpr42_sgpr43_sgpr44_sgpr45_sgpr46_sgpr47_sgpr48_sgpr49_sgpr50_sgpr51_sgpr52_sgpr53_sgpr54_sgpr55_sgpr56_sgpr57_sgpr58_sgpr59_sgpr60_sgpr61_sgpr62_sgpr63_sgpr64_sgpr65_sgpr66_sgpr67
; VI-NEXT:    s_branch .LBB35_2
; VI-NEXT:  .LBB35_4:
; VI-NEXT:    v_mov_b32_e32 v0, s36
; VI-NEXT:    v_mov_b32_e32 v1, s37
; VI-NEXT:    v_mov_b32_e32 v2, s38
; VI-NEXT:    v_mov_b32_e32 v3, s39
; VI-NEXT:    v_mov_b32_e32 v4, s40
; VI-NEXT:    v_mov_b32_e32 v5, s41
; VI-NEXT:    v_mov_b32_e32 v6, s42
; VI-NEXT:    v_mov_b32_e32 v7, s43
; VI-NEXT:    v_mov_b32_e32 v8, s44
; VI-NEXT:    v_mov_b32_e32 v9, s45
; VI-NEXT:    v_mov_b32_e32 v10, s46
; VI-NEXT:    v_mov_b32_e32 v11, s47
; VI-NEXT:    v_mov_b32_e32 v12, s48
; VI-NEXT:    v_mov_b32_e32 v13, s49
; VI-NEXT:    v_mov_b32_e32 v14, s50
; VI-NEXT:    v_mov_b32_e32 v15, s51
; VI-NEXT:    v_mov_b32_e32 v16, s52
; VI-NEXT:    v_mov_b32_e32 v17, s53
; VI-NEXT:    v_mov_b32_e32 v18, s54
; VI-NEXT:    v_mov_b32_e32 v19, s55
; VI-NEXT:    v_mov_b32_e32 v20, s56
; VI-NEXT:    v_mov_b32_e32 v21, s57
; VI-NEXT:    v_mov_b32_e32 v22, s58
; VI-NEXT:    v_mov_b32_e32 v23, s59
; VI-NEXT:    v_mov_b32_e32 v24, s60
; VI-NEXT:    v_mov_b32_e32 v25, s61
; VI-NEXT:    v_mov_b32_e32 v26, s62
; VI-NEXT:    v_mov_b32_e32 v27, s63
; VI-NEXT:    v_mov_b32_e32 v28, s64
; VI-NEXT:    v_mov_b32_e32 v29, s65
; VI-NEXT:    v_mov_b32_e32 v30, s66
; VI-NEXT:    v_mov_b32_e32 v31, s67
; VI-NEXT:  .LBB35_5: ; %end
; VI-NEXT:    v_readlane_b32 s30, v32, 18
; VI-NEXT:    v_readlane_b32 s31, v32, 19
; VI-NEXT:    v_readlane_b32 s67, v32, 17
; VI-NEXT:    v_readlane_b32 s66, v32, 16
; VI-NEXT:    v_readlane_b32 s65, v32, 15
; VI-NEXT:    v_readlane_b32 s64, v32, 14
; VI-NEXT:    v_readlane_b32 s55, v32, 13
; VI-NEXT:    v_readlane_b32 s54, v32, 12
; VI-NEXT:    v_readlane_b32 s53, v32, 11
; VI-NEXT:    v_readlane_b32 s52, v32, 10
; VI-NEXT:    v_readlane_b32 s51, v32, 9
; VI-NEXT:    v_readlane_b32 s50, v32, 8
; VI-NEXT:    v_readlane_b32 s49, v32, 7
; VI-NEXT:    v_readlane_b32 s48, v32, 6
; VI-NEXT:    v_readlane_b32 s39, v32, 5
; VI-NEXT:    v_readlane_b32 s38, v32, 4
; VI-NEXT:    v_readlane_b32 s37, v32, 3
; VI-NEXT:    v_readlane_b32 s36, v32, 2
; VI-NEXT:    v_readlane_b32 s35, v32, 1
; VI-NEXT:    v_readlane_b32 s34, v32, 0
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v40f16_to_v20f32_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    v_writelane_b32 v32, s36, 0
; GFX9-NEXT:    v_writelane_b32 v32, s37, 1
; GFX9-NEXT:    v_writelane_b32 v32, s38, 2
; GFX9-NEXT:    v_writelane_b32 v32, s39, 3
; GFX9-NEXT:    v_writelane_b32 v32, s48, 4
; GFX9-NEXT:    v_writelane_b32 v32, s49, 5
; GFX9-NEXT:    v_writelane_b32 v32, s50, 6
; GFX9-NEXT:    v_writelane_b32 v32, s51, 7
; GFX9-NEXT:    v_writelane_b32 v32, s52, 8
; GFX9-NEXT:    v_writelane_b32 v32, s53, 9
; GFX9-NEXT:    v_writelane_b32 v32, s54, 10
; GFX9-NEXT:    v_writelane_b32 v32, s55, 11
; GFX9-NEXT:    v_readfirstlane_b32 s56, v5
; GFX9-NEXT:    v_readfirstlane_b32 s58, v4
; GFX9-NEXT:    v_readfirstlane_b32 s60, v3
; GFX9-NEXT:    v_readfirstlane_b32 s62, v2
; GFX9-NEXT:    v_readfirstlane_b32 s72, v1
; GFX9-NEXT:    v_readfirstlane_b32 s74, v0
; GFX9-NEXT:    s_lshr_b32 s4, s29, 16
; GFX9-NEXT:    s_lshr_b32 s5, s28, 16
; GFX9-NEXT:    s_lshr_b32 s6, s27, 16
; GFX9-NEXT:    s_lshr_b32 s7, s26, 16
; GFX9-NEXT:    s_lshr_b32 s8, s25, 16
; GFX9-NEXT:    s_lshr_b32 s9, s24, 16
; GFX9-NEXT:    s_lshr_b32 s10, s23, 16
; GFX9-NEXT:    s_lshr_b32 s11, s22, 16
; GFX9-NEXT:    s_lshr_b32 s12, s21, 16
; GFX9-NEXT:    s_lshr_b32 s13, s20, 16
; GFX9-NEXT:    s_lshr_b32 s14, s19, 16
; GFX9-NEXT:    s_lshr_b32 s15, s18, 16
; GFX9-NEXT:    s_lshr_b32 s40, s17, 16
; GFX9-NEXT:    s_lshr_b32 s41, s16, 16
; GFX9-NEXT:    s_lshr_b32 s57, s56, 16
; GFX9-NEXT:    s_lshr_b32 s59, s58, 16
; GFX9-NEXT:    s_lshr_b32 s61, s60, 16
; GFX9-NEXT:    s_lshr_b32 s63, s62, 16
; GFX9-NEXT:    s_lshr_b32 s73, s72, 16
; GFX9-NEXT:    s_lshr_b32 s75, s74, 16
; GFX9-NEXT:    v_readfirstlane_b32 s42, v6
; GFX9-NEXT:    s_cmp_lg_u32 s42, 0
; GFX9-NEXT:    s_pack_ll_b32_b16 s36, s16, s41
; GFX9-NEXT:    s_pack_ll_b32_b16 s37, s17, s40
; GFX9-NEXT:    s_pack_ll_b32_b16 s38, s18, s15
; GFX9-NEXT:    s_pack_ll_b32_b16 s39, s19, s14
; GFX9-NEXT:    s_pack_ll_b32_b16 s40, s20, s13
; GFX9-NEXT:    s_pack_ll_b32_b16 s41, s21, s12
; GFX9-NEXT:    s_pack_ll_b32_b16 s42, s22, s11
; GFX9-NEXT:    s_pack_ll_b32_b16 s43, s23, s10
; GFX9-NEXT:    s_pack_ll_b32_b16 s44, s24, s9
; GFX9-NEXT:    s_pack_ll_b32_b16 s45, s25, s8
; GFX9-NEXT:    s_pack_ll_b32_b16 s46, s26, s7
; GFX9-NEXT:    s_pack_ll_b32_b16 s47, s27, s6
; GFX9-NEXT:    s_pack_ll_b32_b16 s48, s28, s5
; GFX9-NEXT:    s_pack_ll_b32_b16 s49, s29, s4
; GFX9-NEXT:    s_pack_ll_b32_b16 s50, s74, s75
; GFX9-NEXT:    s_pack_ll_b32_b16 s51, s72, s73
; GFX9-NEXT:    s_pack_ll_b32_b16 s52, s62, s63
; GFX9-NEXT:    s_pack_ll_b32_b16 s53, s60, s61
; GFX9-NEXT:    s_pack_ll_b32_b16 s54, s58, s59
; GFX9-NEXT:    s_pack_ll_b32_b16 s55, s56, s57
; GFX9-NEXT:    s_cbranch_scc0 .LBB35_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB35_4
; GFX9-NEXT:  .LBB35_2: ; %cmp.true
; GFX9-NEXT:    v_mov_b32_e32 v19, 0x200
; GFX9-NEXT:    v_pk_add_f16 v0, s36, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v1, s37, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v2, s38, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v3, s39, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v4, s40, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v5, s41, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, s42, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v7, s43, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v8, s44, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v9, s45, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v10, s46, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v11, s47, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v12, s48, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v13, s49, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v14, s50, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v15, s51, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v16, s52, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v17, s53, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v18, s54, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v19, s55, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_branch .LBB35_5
; GFX9-NEXT:  .LBB35_3:
; GFX9-NEXT:    s_branch .LBB35_2
; GFX9-NEXT:  .LBB35_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s36
; GFX9-NEXT:    v_mov_b32_e32 v1, s37
; GFX9-NEXT:    v_mov_b32_e32 v2, s38
; GFX9-NEXT:    v_mov_b32_e32 v3, s39
; GFX9-NEXT:    v_mov_b32_e32 v4, s40
; GFX9-NEXT:    v_mov_b32_e32 v5, s41
; GFX9-NEXT:    v_mov_b32_e32 v6, s42
; GFX9-NEXT:    v_mov_b32_e32 v7, s43
; GFX9-NEXT:    v_mov_b32_e32 v8, s44
; GFX9-NEXT:    v_mov_b32_e32 v9, s45
; GFX9-NEXT:    v_mov_b32_e32 v10, s46
; GFX9-NEXT:    v_mov_b32_e32 v11, s47
; GFX9-NEXT:    v_mov_b32_e32 v12, s48
; GFX9-NEXT:    v_mov_b32_e32 v13, s49
; GFX9-NEXT:    v_mov_b32_e32 v14, s50
; GFX9-NEXT:    v_mov_b32_e32 v15, s51
; GFX9-NEXT:    v_mov_b32_e32 v16, s52
; GFX9-NEXT:    v_mov_b32_e32 v17, s53
; GFX9-NEXT:    v_mov_b32_e32 v18, s54
; GFX9-NEXT:    v_mov_b32_e32 v19, s55
; GFX9-NEXT:    v_mov_b32_e32 v20, s56
; GFX9-NEXT:    v_mov_b32_e32 v21, s57
; GFX9-NEXT:    v_mov_b32_e32 v22, s58
; GFX9-NEXT:    v_mov_b32_e32 v23, s59
; GFX9-NEXT:    v_mov_b32_e32 v24, s60
; GFX9-NEXT:    v_mov_b32_e32 v25, s61
; GFX9-NEXT:    v_mov_b32_e32 v26, s62
; GFX9-NEXT:    v_mov_b32_e32 v27, s63
; GFX9-NEXT:    v_mov_b32_e32 v28, s64
; GFX9-NEXT:    v_mov_b32_e32 v29, s65
; GFX9-NEXT:    v_mov_b32_e32 v30, s66
; GFX9-NEXT:    v_mov_b32_e32 v31, s67
; GFX9-NEXT:  .LBB35_5: ; %end
; GFX9-NEXT:    v_readlane_b32 s55, v32, 11
; GFX9-NEXT:    v_readlane_b32 s54, v32, 10
; GFX9-NEXT:    v_readlane_b32 s53, v32, 9
; GFX9-NEXT:    v_readlane_b32 s52, v32, 8
; GFX9-NEXT:    v_readlane_b32 s51, v32, 7
; GFX9-NEXT:    v_readlane_b32 s50, v32, 6
; GFX9-NEXT:    v_readlane_b32 s49, v32, 5
; GFX9-NEXT:    v_readlane_b32 s48, v32, 4
; GFX9-NEXT:    v_readlane_b32 s39, v32, 3
; GFX9-NEXT:    v_readlane_b32 s38, v32, 2
; GFX9-NEXT:    v_readlane_b32 s37, v32, 1
; GFX9-NEXT:    v_readlane_b32 s36, v32, 0
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v40f16_to_v20f32_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    v_readfirstlane_b32 s45, v1
; GFX11-NEXT:    v_readfirstlane_b32 s46, v0
; GFX11-NEXT:    v_readfirstlane_b32 s56, v2
; GFX11-NEXT:    s_lshr_b32 s41, s29, 16
; GFX11-NEXT:    s_lshr_b32 s42, s28, 16
; GFX11-NEXT:    s_lshr_b32 s15, s27, 16
; GFX11-NEXT:    s_lshr_b32 s14, s26, 16
; GFX11-NEXT:    s_lshr_b32 s13, s25, 16
; GFX11-NEXT:    s_lshr_b32 s12, s24, 16
; GFX11-NEXT:    s_lshr_b32 s11, s23, 16
; GFX11-NEXT:    s_lshr_b32 s10, s22, 16
; GFX11-NEXT:    s_lshr_b32 s9, s21, 16
; GFX11-NEXT:    s_lshr_b32 s8, s20, 16
; GFX11-NEXT:    s_lshr_b32 s7, s19, 16
; GFX11-NEXT:    s_lshr_b32 s6, s18, 16
; GFX11-NEXT:    s_lshr_b32 s5, s17, 16
; GFX11-NEXT:    s_lshr_b32 s4, s16, 16
; GFX11-NEXT:    s_lshr_b32 s43, s3, 16
; GFX11-NEXT:    s_lshr_b32 s44, s2, 16
; GFX11-NEXT:    s_lshr_b32 s47, s1, 16
; GFX11-NEXT:    s_lshr_b32 s57, s0, 16
; GFX11-NEXT:    s_lshr_b32 s58, s45, 16
; GFX11-NEXT:    s_lshr_b32 s59, s46, 16
; GFX11-NEXT:    s_mov_b32 s40, 0
; GFX11-NEXT:    s_cmp_lg_u32 s56, 0
; GFX11-NEXT:    s_pack_ll_b32_b16 s0, s0, s57
; GFX11-NEXT:    s_pack_ll_b32_b16 s1, s1, s47
; GFX11-NEXT:    s_pack_ll_b32_b16 s2, s2, s44
; GFX11-NEXT:    s_pack_ll_b32_b16 s3, s3, s43
; GFX11-NEXT:    s_pack_ll_b32_b16 s4, s16, s4
; GFX11-NEXT:    s_pack_ll_b32_b16 s5, s17, s5
; GFX11-NEXT:    s_pack_ll_b32_b16 s6, s18, s6
; GFX11-NEXT:    s_pack_ll_b32_b16 s7, s19, s7
; GFX11-NEXT:    s_pack_ll_b32_b16 s8, s20, s8
; GFX11-NEXT:    s_pack_ll_b32_b16 s9, s21, s9
; GFX11-NEXT:    s_pack_ll_b32_b16 s10, s22, s10
; GFX11-NEXT:    s_pack_ll_b32_b16 s11, s23, s11
; GFX11-NEXT:    s_pack_ll_b32_b16 s12, s24, s12
; GFX11-NEXT:    s_pack_ll_b32_b16 s13, s25, s13
; GFX11-NEXT:    s_pack_ll_b32_b16 s14, s26, s14
; GFX11-NEXT:    s_pack_ll_b32_b16 s15, s27, s15
; GFX11-NEXT:    s_pack_ll_b32_b16 s16, s28, s42
; GFX11-NEXT:    s_pack_ll_b32_b16 s17, s29, s41
; GFX11-NEXT:    s_pack_ll_b32_b16 s18, s46, s59
; GFX11-NEXT:    s_pack_ll_b32_b16 s19, s45, s58
; GFX11-NEXT:    s_cbranch_scc0 .LBB35_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s40
; GFX11-NEXT:    s_cbranch_vccnz .LBB35_4
; GFX11-NEXT:  .LBB35_2: ; %cmp.true
; GFX11-NEXT:    v_pk_add_f16 v0, 0x200, s0 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v1, 0x200, s1 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v2, 0x200, s2 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v3, 0x200, s3 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v4, 0x200, s4 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v5, 0x200, s5 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v6, 0x200, s6 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v7, 0x200, s7 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v8, 0x200, s8 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v9, 0x200, s9 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v10, 0x200, s10 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v11, 0x200, s11 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v12, 0x200, s12 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v13, 0x200, s13 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v14, 0x200, s14 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v15, 0x200, s15 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v16, 0x200, s16 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v17, 0x200, s17 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v18, 0x200, s18 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v19, 0x200, s19 op_sel_hi:[0,1]
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB35_3:
; GFX11-NEXT:    s_branch .LBB35_2
; GFX11-NEXT:  .LBB35_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    v_dual_mov_b32 v8, s8 :: v_dual_mov_b32 v9, s9
; GFX11-NEXT:    v_dual_mov_b32 v10, s10 :: v_dual_mov_b32 v11, s11
; GFX11-NEXT:    v_dual_mov_b32 v12, s12 :: v_dual_mov_b32 v13, s13
; GFX11-NEXT:    v_dual_mov_b32 v14, s14 :: v_dual_mov_b32 v15, s15
; GFX11-NEXT:    v_dual_mov_b32 v16, s16 :: v_dual_mov_b32 v17, s17
; GFX11-NEXT:    v_dual_mov_b32 v18, s18 :: v_dual_mov_b32 v19, s19
; GFX11-NEXT:    v_dual_mov_b32 v20, s20 :: v_dual_mov_b32 v21, s21
; GFX11-NEXT:    v_dual_mov_b32 v22, s22 :: v_dual_mov_b32 v23, s23
; GFX11-NEXT:    v_dual_mov_b32 v24, s24 :: v_dual_mov_b32 v25, s25
; GFX11-NEXT:    v_dual_mov_b32 v26, s26 :: v_dual_mov_b32 v27, s27
; GFX11-NEXT:    v_dual_mov_b32 v28, s28 :: v_dual_mov_b32 v29, s29
; GFX11-NEXT:    v_dual_mov_b32 v30, s30 :: v_dual_mov_b32 v31, s31
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <40 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <40 x half> %a1 to <20 x float>
  br label %end

cmp.false:
  %a3 = bitcast <40 x half> %a to <20 x float>
  br label %end

end:
  %phi = phi <20 x float> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <20 x float> %phi
}

define <10 x double> @bitcast_v10i64_to_v10f64(<10 x i64> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v10i64_to_v10f64:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB36_2
; SI-NEXT:  ; %bb.1: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; SI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; SI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; SI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; SI-NEXT:    v_add_i32_e32 v8, vcc, 3, v8
; SI-NEXT:    v_addc_u32_e32 v9, vcc, 0, v9, vcc
; SI-NEXT:    v_add_i32_e32 v10, vcc, 3, v10
; SI-NEXT:    v_addc_u32_e32 v11, vcc, 0, v11, vcc
; SI-NEXT:    v_add_i32_e32 v12, vcc, 3, v12
; SI-NEXT:    v_addc_u32_e32 v13, vcc, 0, v13, vcc
; SI-NEXT:    v_add_i32_e32 v14, vcc, 3, v14
; SI-NEXT:    v_addc_u32_e32 v15, vcc, 0, v15, vcc
; SI-NEXT:    v_add_i32_e32 v16, vcc, 3, v16
; SI-NEXT:    v_addc_u32_e32 v17, vcc, 0, v17, vcc
; SI-NEXT:    v_add_i32_e32 v18, vcc, 3, v18
; SI-NEXT:    v_addc_u32_e32 v19, vcc, 0, v19, vcc
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:  .LBB36_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v10i64_to_v10f64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB36_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; VI-NEXT:    v_add_u32_e32 v8, vcc, 3, v8
; VI-NEXT:    v_addc_u32_e32 v9, vcc, 0, v9, vcc
; VI-NEXT:    v_add_u32_e32 v10, vcc, 3, v10
; VI-NEXT:    v_addc_u32_e32 v11, vcc, 0, v11, vcc
; VI-NEXT:    v_add_u32_e32 v12, vcc, 3, v12
; VI-NEXT:    v_addc_u32_e32 v13, vcc, 0, v13, vcc
; VI-NEXT:    v_add_u32_e32 v14, vcc, 3, v14
; VI-NEXT:    v_addc_u32_e32 v15, vcc, 0, v15, vcc
; VI-NEXT:    v_add_u32_e32 v16, vcc, 3, v16
; VI-NEXT:    v_addc_u32_e32 v17, vcc, 0, v17, vcc
; VI-NEXT:    v_add_u32_e32 v18, vcc, 3, v18
; VI-NEXT:    v_addc_u32_e32 v19, vcc, 0, v19, vcc
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:  .LBB36_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v10i64_to_v10f64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB36_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_co_u32_e32 v0, vcc, 3, v0
; GFX9-NEXT:    v_addc_co_u32_e32 v1, vcc, 0, v1, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v2, vcc, 3, v2
; GFX9-NEXT:    v_addc_co_u32_e32 v3, vcc, 0, v3, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v4, vcc, 3, v4
; GFX9-NEXT:    v_addc_co_u32_e32 v5, vcc, 0, v5, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v6, vcc, 3, v6
; GFX9-NEXT:    v_addc_co_u32_e32 v7, vcc, 0, v7, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v8, vcc, 3, v8
; GFX9-NEXT:    v_addc_co_u32_e32 v9, vcc, 0, v9, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v10, vcc, 3, v10
; GFX9-NEXT:    v_addc_co_u32_e32 v11, vcc, 0, v11, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v12, vcc, 3, v12
; GFX9-NEXT:    v_addc_co_u32_e32 v13, vcc, 0, v13, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v14, vcc, 3, v14
; GFX9-NEXT:    v_addc_co_u32_e32 v15, vcc, 0, v15, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v16, vcc, 3, v16
; GFX9-NEXT:    v_addc_co_u32_e32 v17, vcc, 0, v17, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v18, vcc, 3, v18
; GFX9-NEXT:    v_addc_co_u32_e32 v19, vcc, 0, v19, vcc
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:  .LBB36_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v10i64_to_v10f64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB36_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_co_u32 v0, vcc_lo, v0, 3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_co_ci_u32_e64 v1, null, 0, v1, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v2, vcc_lo, v2, 3
; GFX11-NEXT:    v_add_co_ci_u32_e64 v3, null, 0, v3, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v4, vcc_lo, v4, 3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_co_ci_u32_e64 v5, null, 0, v5, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v6, vcc_lo, v6, 3
; GFX11-NEXT:    v_add_co_ci_u32_e64 v7, null, 0, v7, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v8, vcc_lo, v8, 3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_co_ci_u32_e64 v9, null, 0, v9, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v10, vcc_lo, v10, 3
; GFX11-NEXT:    v_add_co_ci_u32_e64 v11, null, 0, v11, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v12, vcc_lo, v12, 3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_co_ci_u32_e64 v13, null, 0, v13, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v14, vcc_lo, v14, 3
; GFX11-NEXT:    v_add_co_ci_u32_e64 v15, null, 0, v15, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v16, vcc_lo, v16, 3
; GFX11-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-NEXT:    v_add_co_ci_u32_e64 v17, null, 0, v17, vcc_lo
; GFX11-NEXT:    v_add_co_u32 v18, vcc_lo, v18, 3
; GFX11-NEXT:    v_add_co_ci_u32_e64 v19, null, 0, v19, vcc_lo
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:  .LBB36_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <10 x i64> %a, splat (i64 3)
  %a2 = bitcast <10 x i64> %a1 to <10 x double>
  br label %end

cmp.false:
  %a3 = bitcast <10 x i64> %a to <10 x double>
  br label %end

end:
  %phi = phi <10 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <10 x double> %phi
}

define inreg <10 x double> @bitcast_v10i64_to_v10f64_scalar(<10 x i64> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v10i64_to_v10f64_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_readfirstlane_b32 s4, v6
; SI-NEXT:    v_readfirstlane_b32 s6, v5
; SI-NEXT:    v_readfirstlane_b32 s7, v4
; SI-NEXT:    v_readfirstlane_b32 s8, v3
; SI-NEXT:    v_readfirstlane_b32 s9, v2
; SI-NEXT:    v_readfirstlane_b32 s10, v1
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    v_readfirstlane_b32 s11, v0
; SI-NEXT:    s_cbranch_scc0 .LBB37_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_cbranch_execnz .LBB37_3
; SI-NEXT:  .LBB37_2: ; %cmp.true
; SI-NEXT:    s_add_u32 s16, s16, 3
; SI-NEXT:    s_addc_u32 s17, s17, 0
; SI-NEXT:    s_add_u32 s18, s18, 3
; SI-NEXT:    s_addc_u32 s19, s19, 0
; SI-NEXT:    s_add_u32 s20, s20, 3
; SI-NEXT:    s_addc_u32 s21, s21, 0
; SI-NEXT:    s_add_u32 s22, s22, 3
; SI-NEXT:    s_addc_u32 s23, s23, 0
; SI-NEXT:    s_add_u32 s24, s24, 3
; SI-NEXT:    s_addc_u32 s25, s25, 0
; SI-NEXT:    s_add_u32 s26, s26, 3
; SI-NEXT:    s_addc_u32 s27, s27, 0
; SI-NEXT:    s_add_u32 s28, s28, 3
; SI-NEXT:    s_addc_u32 s29, s29, 0
; SI-NEXT:    s_add_u32 s11, s11, 3
; SI-NEXT:    s_addc_u32 s10, s10, 0
; SI-NEXT:    s_add_u32 s9, s9, 3
; SI-NEXT:    s_addc_u32 s8, s8, 0
; SI-NEXT:    s_add_u32 s7, s7, 3
; SI-NEXT:    s_addc_u32 s6, s6, 0
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:  .LBB37_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v2, s18
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v4, s20
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v6, s22
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    v_mov_b32_e32 v8, s24
; SI-NEXT:    v_mov_b32_e32 v9, s25
; SI-NEXT:    v_mov_b32_e32 v10, s26
; SI-NEXT:    v_mov_b32_e32 v11, s27
; SI-NEXT:    v_mov_b32_e32 v12, s28
; SI-NEXT:    v_mov_b32_e32 v13, s29
; SI-NEXT:    v_mov_b32_e32 v14, s11
; SI-NEXT:    v_mov_b32_e32 v15, s10
; SI-NEXT:    v_mov_b32_e32 v16, s9
; SI-NEXT:    v_mov_b32_e32 v17, s8
; SI-NEXT:    v_mov_b32_e32 v18, s7
; SI-NEXT:    v_mov_b32_e32 v19, s6
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB37_4:
; SI-NEXT:    s_branch .LBB37_2
;
; VI-LABEL: bitcast_v10i64_to_v10f64_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    v_readfirstlane_b32 s6, v5
; VI-NEXT:    v_readfirstlane_b32 s7, v4
; VI-NEXT:    v_readfirstlane_b32 s8, v3
; VI-NEXT:    v_readfirstlane_b32 s9, v2
; VI-NEXT:    v_readfirstlane_b32 s10, v1
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    v_readfirstlane_b32 s11, v0
; VI-NEXT:    s_cbranch_scc0 .LBB37_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB37_3
; VI-NEXT:  .LBB37_2: ; %cmp.true
; VI-NEXT:    s_add_u32 s16, s16, 3
; VI-NEXT:    s_addc_u32 s17, s17, 0
; VI-NEXT:    s_add_u32 s18, s18, 3
; VI-NEXT:    s_addc_u32 s19, s19, 0
; VI-NEXT:    s_add_u32 s20, s20, 3
; VI-NEXT:    s_addc_u32 s21, s21, 0
; VI-NEXT:    s_add_u32 s22, s22, 3
; VI-NEXT:    s_addc_u32 s23, s23, 0
; VI-NEXT:    s_add_u32 s24, s24, 3
; VI-NEXT:    s_addc_u32 s25, s25, 0
; VI-NEXT:    s_add_u32 s26, s26, 3
; VI-NEXT:    s_addc_u32 s27, s27, 0
; VI-NEXT:    s_add_u32 s28, s28, 3
; VI-NEXT:    s_addc_u32 s29, s29, 0
; VI-NEXT:    s_add_u32 s11, s11, 3
; VI-NEXT:    s_addc_u32 s10, s10, 0
; VI-NEXT:    s_add_u32 s9, s9, 3
; VI-NEXT:    s_addc_u32 s8, s8, 0
; VI-NEXT:    s_add_u32 s7, s7, 3
; VI-NEXT:    s_addc_u32 s6, s6, 0
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:  .LBB37_3: ; %end
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    v_mov_b32_e32 v8, s24
; VI-NEXT:    v_mov_b32_e32 v9, s25
; VI-NEXT:    v_mov_b32_e32 v10, s26
; VI-NEXT:    v_mov_b32_e32 v11, s27
; VI-NEXT:    v_mov_b32_e32 v12, s28
; VI-NEXT:    v_mov_b32_e32 v13, s29
; VI-NEXT:    v_mov_b32_e32 v14, s11
; VI-NEXT:    v_mov_b32_e32 v15, s10
; VI-NEXT:    v_mov_b32_e32 v16, s9
; VI-NEXT:    v_mov_b32_e32 v17, s8
; VI-NEXT:    v_mov_b32_e32 v18, s7
; VI-NEXT:    v_mov_b32_e32 v19, s6
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB37_4:
; VI-NEXT:    s_branch .LBB37_2
;
; GFX9-LABEL: bitcast_v10i64_to_v10f64_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_readfirstlane_b32 s4, v6
; GFX9-NEXT:    v_readfirstlane_b32 s6, v5
; GFX9-NEXT:    v_readfirstlane_b32 s7, v4
; GFX9-NEXT:    v_readfirstlane_b32 s8, v3
; GFX9-NEXT:    v_readfirstlane_b32 s9, v2
; GFX9-NEXT:    v_readfirstlane_b32 s10, v1
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    v_readfirstlane_b32 s11, v0
; GFX9-NEXT:    s_cbranch_scc0 .LBB37_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB37_3
; GFX9-NEXT:  .LBB37_2: ; %cmp.true
; GFX9-NEXT:    s_add_u32 s16, s16, 3
; GFX9-NEXT:    s_addc_u32 s17, s17, 0
; GFX9-NEXT:    s_add_u32 s18, s18, 3
; GFX9-NEXT:    s_addc_u32 s19, s19, 0
; GFX9-NEXT:    s_add_u32 s20, s20, 3
; GFX9-NEXT:    s_addc_u32 s21, s21, 0
; GFX9-NEXT:    s_add_u32 s22, s22, 3
; GFX9-NEXT:    s_addc_u32 s23, s23, 0
; GFX9-NEXT:    s_add_u32 s24, s24, 3
; GFX9-NEXT:    s_addc_u32 s25, s25, 0
; GFX9-NEXT:    s_add_u32 s26, s26, 3
; GFX9-NEXT:    s_addc_u32 s27, s27, 0
; GFX9-NEXT:    s_add_u32 s28, s28, 3
; GFX9-NEXT:    s_addc_u32 s29, s29, 0
; GFX9-NEXT:    s_add_u32 s11, s11, 3
; GFX9-NEXT:    s_addc_u32 s10, s10, 0
; GFX9-NEXT:    s_add_u32 s9, s9, 3
; GFX9-NEXT:    s_addc_u32 s8, s8, 0
; GFX9-NEXT:    s_add_u32 s7, s7, 3
; GFX9-NEXT:    s_addc_u32 s6, s6, 0
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:    ; implicit-def: $sgpr4
; GFX9-NEXT:  .LBB37_3: ; %end
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    v_mov_b32_e32 v8, s24
; GFX9-NEXT:    v_mov_b32_e32 v9, s25
; GFX9-NEXT:    v_mov_b32_e32 v10, s26
; GFX9-NEXT:    v_mov_b32_e32 v11, s27
; GFX9-NEXT:    v_mov_b32_e32 v12, s28
; GFX9-NEXT:    v_mov_b32_e32 v13, s29
; GFX9-NEXT:    v_mov_b32_e32 v14, s11
; GFX9-NEXT:    v_mov_b32_e32 v15, s10
; GFX9-NEXT:    v_mov_b32_e32 v16, s9
; GFX9-NEXT:    v_mov_b32_e32 v17, s8
; GFX9-NEXT:    v_mov_b32_e32 v18, s7
; GFX9-NEXT:    v_mov_b32_e32 v19, s6
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB37_4:
; GFX9-NEXT:    s_branch .LBB37_2
;
; GFX11-LABEL: bitcast_v10i64_to_v10f64_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    v_readfirstlane_b32 s6, v2
; GFX11-NEXT:    v_readfirstlane_b32 s4, v1
; GFX11-NEXT:    v_readfirstlane_b32 s5, v0
; GFX11-NEXT:    s_cmp_lg_u32 s6, 0
; GFX11-NEXT:    s_mov_b32 s6, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB37_4
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s6
; GFX11-NEXT:    s_cbranch_vccnz .LBB37_3
; GFX11-NEXT:  .LBB37_2: ; %cmp.true
; GFX11-NEXT:    s_add_u32 s0, s0, 3
; GFX11-NEXT:    s_addc_u32 s1, s1, 0
; GFX11-NEXT:    s_add_u32 s2, s2, 3
; GFX11-NEXT:    s_addc_u32 s3, s3, 0
; GFX11-NEXT:    s_add_u32 s16, s16, 3
; GFX11-NEXT:    s_addc_u32 s17, s17, 0
; GFX11-NEXT:    s_add_u32 s18, s18, 3
; GFX11-NEXT:    s_addc_u32 s19, s19, 0
; GFX11-NEXT:    s_add_u32 s20, s20, 3
; GFX11-NEXT:    s_addc_u32 s21, s21, 0
; GFX11-NEXT:    s_add_u32 s22, s22, 3
; GFX11-NEXT:    s_addc_u32 s23, s23, 0
; GFX11-NEXT:    s_add_u32 s24, s24, 3
; GFX11-NEXT:    s_addc_u32 s25, s25, 0
; GFX11-NEXT:    s_add_u32 s26, s26, 3
; GFX11-NEXT:    s_addc_u32 s27, s27, 0
; GFX11-NEXT:    s_add_u32 s28, s28, 3
; GFX11-NEXT:    s_addc_u32 s29, s29, 0
; GFX11-NEXT:    s_add_u32 s5, s5, 3
; GFX11-NEXT:    s_addc_u32 s4, s4, 0
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:  .LBB37_3: ; %end
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s16 :: v_dual_mov_b32 v5, s17
; GFX11-NEXT:    v_dual_mov_b32 v6, s18 :: v_dual_mov_b32 v7, s19
; GFX11-NEXT:    v_dual_mov_b32 v8, s20 :: v_dual_mov_b32 v9, s21
; GFX11-NEXT:    v_dual_mov_b32 v10, s22 :: v_dual_mov_b32 v11, s23
; GFX11-NEXT:    v_dual_mov_b32 v12, s24 :: v_dual_mov_b32 v13, s25
; GFX11-NEXT:    v_dual_mov_b32 v14, s26 :: v_dual_mov_b32 v15, s27
; GFX11-NEXT:    v_dual_mov_b32 v16, s28 :: v_dual_mov_b32 v17, s29
; GFX11-NEXT:    v_dual_mov_b32 v18, s5 :: v_dual_mov_b32 v19, s4
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB37_4:
; GFX11-NEXT:    s_branch .LBB37_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <10 x i64> %a, splat (i64 3)
  %a2 = bitcast <10 x i64> %a1 to <10 x double>
  br label %end

cmp.false:
  %a3 = bitcast <10 x i64> %a to <10 x double>
  br label %end

end:
  %phi = phi <10 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <10 x double> %phi
}

define <10 x i64> @bitcast_v10f64_to_v10i64(<10 x double> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v10f64_to_v10i64:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB38_2
; SI-NEXT:  ; %bb.1: ; %cmp.true
; SI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; SI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; SI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; SI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; SI-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; SI-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; SI-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; SI-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; SI-NEXT:    v_add_f64 v[16:17], v[16:17], 1.0
; SI-NEXT:    v_add_f64 v[18:19], v[18:19], 1.0
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:  .LBB38_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v10f64_to_v10i64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB38_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; VI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; VI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; VI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; VI-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; VI-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; VI-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; VI-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; VI-NEXT:    v_add_f64 v[16:17], v[16:17], 1.0
; VI-NEXT:    v_add_f64 v[18:19], v[18:19], 1.0
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:  .LBB38_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v10f64_to_v10i64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB38_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX9-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX9-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GFX9-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GFX9-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GFX9-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GFX9-NEXT:    v_add_f64 v[16:17], v[16:17], 1.0
; GFX9-NEXT:    v_add_f64 v[18:19], v[18:19], 1.0
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:  .LBB38_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v10f64_to_v10i64:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-NEXT:    s_cbranch_execz .LBB38_2
; GFX11-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX11-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX11-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX11-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX11-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GFX11-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GFX11-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GFX11-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GFX11-NEXT:    v_add_f64 v[16:17], v[16:17], 1.0
; GFX11-NEXT:    v_add_f64 v[18:19], v[18:19], 1.0
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:  .LBB38_2: ; %end
; GFX11-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <10 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <10 x double> %a1 to <10 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <10 x double> %a to <10 x i64>
  br label %end

end:
  %phi = phi <10 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <10 x i64> %phi
}

define inreg <10 x i64> @bitcast_v10f64_to_v10i64_scalar(<10 x double> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v10f64_to_v10i64_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_writelane_b32 v32, s36, 0
; SI-NEXT:    v_writelane_b32 v32, s37, 1
; SI-NEXT:    v_writelane_b32 v32, s38, 2
; SI-NEXT:    v_writelane_b32 v32, s39, 3
; SI-NEXT:    v_writelane_b32 v32, s48, 4
; SI-NEXT:    v_writelane_b32 v32, s49, 5
; SI-NEXT:    v_writelane_b32 v32, s50, 6
; SI-NEXT:    v_writelane_b32 v32, s51, 7
; SI-NEXT:    v_writelane_b32 v32, s52, 8
; SI-NEXT:    v_writelane_b32 v32, s53, 9
; SI-NEXT:    v_writelane_b32 v32, s54, 10
; SI-NEXT:    v_writelane_b32 v32, s55, 11
; SI-NEXT:    v_readfirstlane_b32 s4, v6
; SI-NEXT:    s_mov_b32 s49, s29
; SI-NEXT:    s_mov_b32 s48, s28
; SI-NEXT:    s_mov_b32 s47, s27
; SI-NEXT:    s_mov_b32 s46, s26
; SI-NEXT:    s_mov_b32 s45, s25
; SI-NEXT:    s_mov_b32 s44, s24
; SI-NEXT:    s_mov_b32 s43, s23
; SI-NEXT:    s_mov_b32 s42, s22
; SI-NEXT:    s_mov_b32 s41, s21
; SI-NEXT:    s_mov_b32 s40, s20
; SI-NEXT:    s_mov_b32 s39, s19
; SI-NEXT:    s_mov_b32 s38, s18
; SI-NEXT:    s_mov_b32 s37, s17
; SI-NEXT:    s_mov_b32 s36, s16
; SI-NEXT:    v_readfirstlane_b32 s55, v5
; SI-NEXT:    v_readfirstlane_b32 s54, v4
; SI-NEXT:    v_readfirstlane_b32 s53, v3
; SI-NEXT:    v_readfirstlane_b32 s52, v2
; SI-NEXT:    v_readfirstlane_b32 s51, v1
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    v_readfirstlane_b32 s50, v0
; SI-NEXT:    s_cbranch_scc0 .LBB39_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_cbranch_execnz .LBB39_4
; SI-NEXT:  .LBB39_2: ; %cmp.true
; SI-NEXT:    v_add_f64 v[0:1], s[36:37], 1.0
; SI-NEXT:    v_add_f64 v[2:3], s[38:39], 1.0
; SI-NEXT:    v_add_f64 v[4:5], s[40:41], 1.0
; SI-NEXT:    v_add_f64 v[6:7], s[42:43], 1.0
; SI-NEXT:    v_add_f64 v[8:9], s[44:45], 1.0
; SI-NEXT:    v_add_f64 v[10:11], s[46:47], 1.0
; SI-NEXT:    v_add_f64 v[12:13], s[48:49], 1.0
; SI-NEXT:    v_add_f64 v[14:15], s[50:51], 1.0
; SI-NEXT:    v_add_f64 v[16:17], s[52:53], 1.0
; SI-NEXT:    v_add_f64 v[18:19], s[54:55], 1.0
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    s_branch .LBB39_5
; SI-NEXT:  .LBB39_3:
; SI-NEXT:    s_branch .LBB39_2
; SI-NEXT:  .LBB39_4:
; SI-NEXT:    v_mov_b32_e32 v0, s36
; SI-NEXT:    v_mov_b32_e32 v1, s37
; SI-NEXT:    v_mov_b32_e32 v2, s38
; SI-NEXT:    v_mov_b32_e32 v3, s39
; SI-NEXT:    v_mov_b32_e32 v4, s40
; SI-NEXT:    v_mov_b32_e32 v5, s41
; SI-NEXT:    v_mov_b32_e32 v6, s42
; SI-NEXT:    v_mov_b32_e32 v7, s43
; SI-NEXT:    v_mov_b32_e32 v8, s44
; SI-NEXT:    v_mov_b32_e32 v9, s45
; SI-NEXT:    v_mov_b32_e32 v10, s46
; SI-NEXT:    v_mov_b32_e32 v11, s47
; SI-NEXT:    v_mov_b32_e32 v12, s48
; SI-NEXT:    v_mov_b32_e32 v13, s49
; SI-NEXT:    v_mov_b32_e32 v14, s50
; SI-NEXT:    v_mov_b32_e32 v15, s51
; SI-NEXT:    v_mov_b32_e32 v16, s52
; SI-NEXT:    v_mov_b32_e32 v17, s53
; SI-NEXT:    v_mov_b32_e32 v18, s54
; SI-NEXT:    v_mov_b32_e32 v19, s55
; SI-NEXT:    v_mov_b32_e32 v20, s56
; SI-NEXT:    v_mov_b32_e32 v21, s57
; SI-NEXT:    v_mov_b32_e32 v22, s58
; SI-NEXT:    v_mov_b32_e32 v23, s59
; SI-NEXT:    v_mov_b32_e32 v24, s60
; SI-NEXT:    v_mov_b32_e32 v25, s61
; SI-NEXT:    v_mov_b32_e32 v26, s62
; SI-NEXT:    v_mov_b32_e32 v27, s63
; SI-NEXT:    v_mov_b32_e32 v28, s64
; SI-NEXT:    v_mov_b32_e32 v29, s65
; SI-NEXT:    v_mov_b32_e32 v30, s66
; SI-NEXT:    v_mov_b32_e32 v31, s67
; SI-NEXT:  .LBB39_5: ; %end
; SI-NEXT:    v_readlane_b32 s55, v32, 11
; SI-NEXT:    v_readlane_b32 s54, v32, 10
; SI-NEXT:    v_readlane_b32 s53, v32, 9
; SI-NEXT:    v_readlane_b32 s52, v32, 8
; SI-NEXT:    v_readlane_b32 s51, v32, 7
; SI-NEXT:    v_readlane_b32 s50, v32, 6
; SI-NEXT:    v_readlane_b32 s49, v32, 5
; SI-NEXT:    v_readlane_b32 s48, v32, 4
; SI-NEXT:    v_readlane_b32 s39, v32, 3
; SI-NEXT:    v_readlane_b32 s38, v32, 2
; SI-NEXT:    v_readlane_b32 s37, v32, 1
; SI-NEXT:    v_readlane_b32 s36, v32, 0
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v10f64_to_v10i64_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    v_writelane_b32 v32, s36, 0
; VI-NEXT:    v_writelane_b32 v32, s37, 1
; VI-NEXT:    v_writelane_b32 v32, s38, 2
; VI-NEXT:    v_writelane_b32 v32, s39, 3
; VI-NEXT:    v_writelane_b32 v32, s48, 4
; VI-NEXT:    v_writelane_b32 v32, s49, 5
; VI-NEXT:    v_writelane_b32 v32, s50, 6
; VI-NEXT:    v_writelane_b32 v32, s51, 7
; VI-NEXT:    v_writelane_b32 v32, s52, 8
; VI-NEXT:    v_writelane_b32 v32, s53, 9
; VI-NEXT:    v_writelane_b32 v32, s54, 10
; VI-NEXT:    v_writelane_b32 v32, s55, 11
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    s_mov_b32 s49, s29
; VI-NEXT:    s_mov_b32 s48, s28
; VI-NEXT:    s_mov_b32 s47, s27
; VI-NEXT:    s_mov_b32 s46, s26
; VI-NEXT:    s_mov_b32 s45, s25
; VI-NEXT:    s_mov_b32 s44, s24
; VI-NEXT:    s_mov_b32 s43, s23
; VI-NEXT:    s_mov_b32 s42, s22
; VI-NEXT:    s_mov_b32 s41, s21
; VI-NEXT:    s_mov_b32 s40, s20
; VI-NEXT:    s_mov_b32 s39, s19
; VI-NEXT:    s_mov_b32 s38, s18
; VI-NEXT:    s_mov_b32 s37, s17
; VI-NEXT:    s_mov_b32 s36, s16
; VI-NEXT:    v_readfirstlane_b32 s55, v5
; VI-NEXT:    v_readfirstlane_b32 s54, v4
; VI-NEXT:    v_readfirstlane_b32 s53, v3
; VI-NEXT:    v_readfirstlane_b32 s52, v2
; VI-NEXT:    v_readfirstlane_b32 s51, v1
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    v_readfirstlane_b32 s50, v0
; VI-NEXT:    s_cbranch_scc0 .LBB39_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB39_4
; VI-NEXT:  .LBB39_2: ; %cmp.true
; VI-NEXT:    v_add_f64 v[0:1], s[36:37], 1.0
; VI-NEXT:    v_add_f64 v[2:3], s[38:39], 1.0
; VI-NEXT:    v_add_f64 v[4:5], s[40:41], 1.0
; VI-NEXT:    v_add_f64 v[6:7], s[42:43], 1.0
; VI-NEXT:    v_add_f64 v[8:9], s[44:45], 1.0
; VI-NEXT:    v_add_f64 v[10:11], s[46:47], 1.0
; VI-NEXT:    v_add_f64 v[12:13], s[48:49], 1.0
; VI-NEXT:    v_add_f64 v[14:15], s[50:51], 1.0
; VI-NEXT:    v_add_f64 v[16:17], s[52:53], 1.0
; VI-NEXT:    v_add_f64 v[18:19], s[54:55], 1.0
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    s_branch .LBB39_5
; VI-NEXT:  .LBB39_3:
; VI-NEXT:    s_branch .LBB39_2
; VI-NEXT:  .LBB39_4:
; VI-NEXT:    v_mov_b32_e32 v0, s36
; VI-NEXT:    v_mov_b32_e32 v1, s37
; VI-NEXT:    v_mov_b32_e32 v2, s38
; VI-NEXT:    v_mov_b32_e32 v3, s39
; VI-NEXT:    v_mov_b32_e32 v4, s40
; VI-NEXT:    v_mov_b32_e32 v5, s41
; VI-NEXT:    v_mov_b32_e32 v6, s42
; VI-NEXT:    v_mov_b32_e32 v7, s43
; VI-NEXT:    v_mov_b32_e32 v8, s44
; VI-NEXT:    v_mov_b32_e32 v9, s45
; VI-NEXT:    v_mov_b32_e32 v10, s46
; VI-NEXT:    v_mov_b32_e32 v11, s47
; VI-NEXT:    v_mov_b32_e32 v12, s48
; VI-NEXT:    v_mov_b32_e32 v13, s49
; VI-NEXT:    v_mov_b32_e32 v14, s50
; VI-NEXT:    v_mov_b32_e32 v15, s51
; VI-NEXT:    v_mov_b32_e32 v16, s52
; VI-NEXT:    v_mov_b32_e32 v17, s53
; VI-NEXT:    v_mov_b32_e32 v18, s54
; VI-NEXT:    v_mov_b32_e32 v19, s55
; VI-NEXT:    v_mov_b32_e32 v20, s56
; VI-NEXT:    v_mov_b32_e32 v21, s57
; VI-NEXT:    v_mov_b32_e32 v22, s58
; VI-NEXT:    v_mov_b32_e32 v23, s59
; VI-NEXT:    v_mov_b32_e32 v24, s60
; VI-NEXT:    v_mov_b32_e32 v25, s61
; VI-NEXT:    v_mov_b32_e32 v26, s62
; VI-NEXT:    v_mov_b32_e32 v27, s63
; VI-NEXT:    v_mov_b32_e32 v28, s64
; VI-NEXT:    v_mov_b32_e32 v29, s65
; VI-NEXT:    v_mov_b32_e32 v30, s66
; VI-NEXT:    v_mov_b32_e32 v31, s67
; VI-NEXT:  .LBB39_5: ; %end
; VI-NEXT:    v_readlane_b32 s55, v32, 11
; VI-NEXT:    v_readlane_b32 s54, v32, 10
; VI-NEXT:    v_readlane_b32 s53, v32, 9
; VI-NEXT:    v_readlane_b32 s52, v32, 8
; VI-NEXT:    v_readlane_b32 s51, v32, 7
; VI-NEXT:    v_readlane_b32 s50, v32, 6
; VI-NEXT:    v_readlane_b32 s49, v32, 5
; VI-NEXT:    v_readlane_b32 s48, v32, 4
; VI-NEXT:    v_readlane_b32 s39, v32, 3
; VI-NEXT:    v_readlane_b32 s38, v32, 2
; VI-NEXT:    v_readlane_b32 s37, v32, 1
; VI-NEXT:    v_readlane_b32 s36, v32, 0
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v10f64_to_v10i64_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    v_writelane_b32 v32, s36, 0
; GFX9-NEXT:    v_writelane_b32 v32, s37, 1
; GFX9-NEXT:    v_writelane_b32 v32, s38, 2
; GFX9-NEXT:    v_writelane_b32 v32, s39, 3
; GFX9-NEXT:    v_writelane_b32 v32, s48, 4
; GFX9-NEXT:    v_writelane_b32 v32, s49, 5
; GFX9-NEXT:    v_writelane_b32 v32, s50, 6
; GFX9-NEXT:    v_writelane_b32 v32, s51, 7
; GFX9-NEXT:    v_writelane_b32 v32, s52, 8
; GFX9-NEXT:    v_writelane_b32 v32, s53, 9
; GFX9-NEXT:    v_writelane_b32 v32, s54, 10
; GFX9-NEXT:    v_writelane_b32 v32, s55, 11
; GFX9-NEXT:    v_readfirstlane_b32 s4, v6
; GFX9-NEXT:    s_mov_b32 s49, s29
; GFX9-NEXT:    s_mov_b32 s48, s28
; GFX9-NEXT:    s_mov_b32 s47, s27
; GFX9-NEXT:    s_mov_b32 s46, s26
; GFX9-NEXT:    s_mov_b32 s45, s25
; GFX9-NEXT:    s_mov_b32 s44, s24
; GFX9-NEXT:    s_mov_b32 s43, s23
; GFX9-NEXT:    s_mov_b32 s42, s22
; GFX9-NEXT:    s_mov_b32 s41, s21
; GFX9-NEXT:    s_mov_b32 s40, s20
; GFX9-NEXT:    s_mov_b32 s39, s19
; GFX9-NEXT:    s_mov_b32 s38, s18
; GFX9-NEXT:    s_mov_b32 s37, s17
; GFX9-NEXT:    s_mov_b32 s36, s16
; GFX9-NEXT:    v_readfirstlane_b32 s55, v5
; GFX9-NEXT:    v_readfirstlane_b32 s54, v4
; GFX9-NEXT:    v_readfirstlane_b32 s53, v3
; GFX9-NEXT:    v_readfirstlane_b32 s52, v2
; GFX9-NEXT:    v_readfirstlane_b32 s51, v1
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    v_readfirstlane_b32 s50, v0
; GFX9-NEXT:    s_cbranch_scc0 .LBB39_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB39_4
; GFX9-NEXT:  .LBB39_2: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[0:1], s[36:37], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], s[38:39], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], s[40:41], 1.0
; GFX9-NEXT:    v_add_f64 v[6:7], s[42:43], 1.0
; GFX9-NEXT:    v_add_f64 v[8:9], s[44:45], 1.0
; GFX9-NEXT:    v_add_f64 v[10:11], s[46:47], 1.0
; GFX9-NEXT:    v_add_f64 v[12:13], s[48:49], 1.0
; GFX9-NEXT:    v_add_f64 v[14:15], s[50:51], 1.0
; GFX9-NEXT:    v_add_f64 v[16:17], s[52:53], 1.0
; GFX9-NEXT:    v_add_f64 v[18:19], s[54:55], 1.0
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_branch .LBB39_5
; GFX9-NEXT:  .LBB39_3:
; GFX9-NEXT:    s_branch .LBB39_2
; GFX9-NEXT:  .LBB39_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s36
; GFX9-NEXT:    v_mov_b32_e32 v1, s37
; GFX9-NEXT:    v_mov_b32_e32 v2, s38
; GFX9-NEXT:    v_mov_b32_e32 v3, s39
; GFX9-NEXT:    v_mov_b32_e32 v4, s40
; GFX9-NEXT:    v_mov_b32_e32 v5, s41
; GFX9-NEXT:    v_mov_b32_e32 v6, s42
; GFX9-NEXT:    v_mov_b32_e32 v7, s43
; GFX9-NEXT:    v_mov_b32_e32 v8, s44
; GFX9-NEXT:    v_mov_b32_e32 v9, s45
; GFX9-NEXT:    v_mov_b32_e32 v10, s46
; GFX9-NEXT:    v_mov_b32_e32 v11, s47
; GFX9-NEXT:    v_mov_b32_e32 v12, s48
; GFX9-NEXT:    v_mov_b32_e32 v13, s49
; GFX9-NEXT:    v_mov_b32_e32 v14, s50
; GFX9-NEXT:    v_mov_b32_e32 v15, s51
; GFX9-NEXT:    v_mov_b32_e32 v16, s52
; GFX9-NEXT:    v_mov_b32_e32 v17, s53
; GFX9-NEXT:    v_mov_b32_e32 v18, s54
; GFX9-NEXT:    v_mov_b32_e32 v19, s55
; GFX9-NEXT:    v_mov_b32_e32 v20, s56
; GFX9-NEXT:    v_mov_b32_e32 v21, s57
; GFX9-NEXT:    v_mov_b32_e32 v22, s58
; GFX9-NEXT:    v_mov_b32_e32 v23, s59
; GFX9-NEXT:    v_mov_b32_e32 v24, s60
; GFX9-NEXT:    v_mov_b32_e32 v25, s61
; GFX9-NEXT:    v_mov_b32_e32 v26, s62
; GFX9-NEXT:    v_mov_b32_e32 v27, s63
; GFX9-NEXT:    v_mov_b32_e32 v28, s64
; GFX9-NEXT:    v_mov_b32_e32 v29, s65
; GFX9-NEXT:    v_mov_b32_e32 v30, s66
; GFX9-NEXT:    v_mov_b32_e32 v31, s67
; GFX9-NEXT:  .LBB39_5: ; %end
; GFX9-NEXT:    v_readlane_b32 s55, v32, 11
; GFX9-NEXT:    v_readlane_b32 s54, v32, 10
; GFX9-NEXT:    v_readlane_b32 s53, v32, 9
; GFX9-NEXT:    v_readlane_b32 s52, v32, 8
; GFX9-NEXT:    v_readlane_b32 s51, v32, 7
; GFX9-NEXT:    v_readlane_b32 s50, v32, 6
; GFX9-NEXT:    v_readlane_b32 s49, v32, 5
; GFX9-NEXT:    v_readlane_b32 s48, v32, 4
; GFX9-NEXT:    v_readlane_b32 s39, v32, 3
; GFX9-NEXT:    v_readlane_b32 s38, v32, 2
; GFX9-NEXT:    v_readlane_b32 s37, v32, 1
; GFX9-NEXT:    v_readlane_b32 s36, v32, 0
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v10f64_to_v10i64_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    s_xor_saveexec_b32 s4, -1
; GFX11-NEXT:    scratch_store_b32 off, v32, s32 ; 4-byte Folded Spill
; GFX11-NEXT:    s_mov_b32 exec_lo, s4
; GFX11-NEXT:    v_writelane_b32 v32, s36, 0
; GFX11-NEXT:    v_writelane_b32 v32, s37, 1
; GFX11-NEXT:    v_writelane_b32 v32, s38, 2
; GFX11-NEXT:    v_writelane_b32 v32, s39, 3
; GFX11-NEXT:    v_writelane_b32 v32, s48, 4
; GFX11-NEXT:    v_writelane_b32 v32, s49, 5
; GFX11-NEXT:    v_writelane_b32 v32, s50, 6
; GFX11-NEXT:    v_writelane_b32 v32, s51, 7
; GFX11-NEXT:    v_writelane_b32 v32, s52, 8
; GFX11-NEXT:    v_writelane_b32 v32, s53, 9
; GFX11-NEXT:    v_writelane_b32 v32, s54, 10
; GFX11-NEXT:    v_writelane_b32 v32, s55, 11
; GFX11-NEXT:    s_mov_b32 s36, s0
; GFX11-NEXT:    v_readfirstlane_b32 s0, v2
; GFX11-NEXT:    v_readfirstlane_b32 s55, v1
; GFX11-NEXT:    v_readfirstlane_b32 s54, v0
; GFX11-NEXT:    s_mov_b32 s53, s29
; GFX11-NEXT:    s_mov_b32 s52, s28
; GFX11-NEXT:    s_mov_b32 s51, s27
; GFX11-NEXT:    s_mov_b32 s50, s26
; GFX11-NEXT:    s_mov_b32 s49, s25
; GFX11-NEXT:    s_mov_b32 s48, s24
; GFX11-NEXT:    s_mov_b32 s47, s23
; GFX11-NEXT:    s_mov_b32 s46, s22
; GFX11-NEXT:    s_mov_b32 s45, s21
; GFX11-NEXT:    s_mov_b32 s44, s20
; GFX11-NEXT:    s_mov_b32 s43, s19
; GFX11-NEXT:    s_mov_b32 s42, s18
; GFX11-NEXT:    s_mov_b32 s41, s17
; GFX11-NEXT:    s_mov_b32 s40, s16
; GFX11-NEXT:    s_mov_b32 s39, s3
; GFX11-NEXT:    s_mov_b32 s38, s2
; GFX11-NEXT:    s_mov_b32 s37, s1
; GFX11-NEXT:    s_cmp_lg_u32 s0, 0
; GFX11-NEXT:    s_mov_b32 s0, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB39_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s0
; GFX11-NEXT:    s_cbranch_vccnz .LBB39_4
; GFX11-NEXT:  .LBB39_2: ; %cmp.true
; GFX11-NEXT:    v_add_f64 v[0:1], s[36:37], 1.0
; GFX11-NEXT:    v_add_f64 v[2:3], s[38:39], 1.0
; GFX11-NEXT:    v_add_f64 v[4:5], s[40:41], 1.0
; GFX11-NEXT:    v_add_f64 v[6:7], s[42:43], 1.0
; GFX11-NEXT:    v_add_f64 v[8:9], s[44:45], 1.0
; GFX11-NEXT:    v_add_f64 v[10:11], s[46:47], 1.0
; GFX11-NEXT:    v_add_f64 v[12:13], s[48:49], 1.0
; GFX11-NEXT:    v_add_f64 v[14:15], s[50:51], 1.0
; GFX11-NEXT:    v_add_f64 v[16:17], s[52:53], 1.0
; GFX11-NEXT:    v_add_f64 v[18:19], s[54:55], 1.0
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    s_branch .LBB39_5
; GFX11-NEXT:  .LBB39_3:
; GFX11-NEXT:    s_branch .LBB39_2
; GFX11-NEXT:  .LBB39_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s36 :: v_dual_mov_b32 v1, s37
; GFX11-NEXT:    v_dual_mov_b32 v2, s38 :: v_dual_mov_b32 v3, s39
; GFX11-NEXT:    v_dual_mov_b32 v4, s40 :: v_dual_mov_b32 v5, s41
; GFX11-NEXT:    v_dual_mov_b32 v6, s42 :: v_dual_mov_b32 v7, s43
; GFX11-NEXT:    v_dual_mov_b32 v8, s44 :: v_dual_mov_b32 v9, s45
; GFX11-NEXT:    v_dual_mov_b32 v10, s46 :: v_dual_mov_b32 v11, s47
; GFX11-NEXT:    v_dual_mov_b32 v12, s48 :: v_dual_mov_b32 v13, s49
; GFX11-NEXT:    v_dual_mov_b32 v14, s50 :: v_dual_mov_b32 v15, s51
; GFX11-NEXT:    v_dual_mov_b32 v16, s52 :: v_dual_mov_b32 v17, s53
; GFX11-NEXT:    v_dual_mov_b32 v18, s54 :: v_dual_mov_b32 v19, s55
; GFX11-NEXT:    v_dual_mov_b32 v20, s56 :: v_dual_mov_b32 v21, s57
; GFX11-NEXT:    v_dual_mov_b32 v22, s58 :: v_dual_mov_b32 v23, s59
; GFX11-NEXT:    v_dual_mov_b32 v24, s60 :: v_dual_mov_b32 v25, s61
; GFX11-NEXT:    v_dual_mov_b32 v26, s62 :: v_dual_mov_b32 v27, s63
; GFX11-NEXT:    v_dual_mov_b32 v28, s64 :: v_dual_mov_b32 v29, s65
; GFX11-NEXT:    v_dual_mov_b32 v30, s66 :: v_dual_mov_b32 v31, s67
; GFX11-NEXT:  .LBB39_5: ; %end
; GFX11-NEXT:    v_readlane_b32 s55, v32, 11
; GFX11-NEXT:    v_readlane_b32 s54, v32, 10
; GFX11-NEXT:    v_readlane_b32 s53, v32, 9
; GFX11-NEXT:    v_readlane_b32 s52, v32, 8
; GFX11-NEXT:    v_readlane_b32 s51, v32, 7
; GFX11-NEXT:    v_readlane_b32 s50, v32, 6
; GFX11-NEXT:    v_readlane_b32 s49, v32, 5
; GFX11-NEXT:    v_readlane_b32 s48, v32, 4
; GFX11-NEXT:    v_readlane_b32 s39, v32, 3
; GFX11-NEXT:    v_readlane_b32 s38, v32, 2
; GFX11-NEXT:    v_readlane_b32 s37, v32, 1
; GFX11-NEXT:    v_readlane_b32 s36, v32, 0
; GFX11-NEXT:    s_xor_saveexec_b32 s0, -1
; GFX11-NEXT:    scratch_load_b32 v32, off, s32 ; 4-byte Folded Reload
; GFX11-NEXT:    s_mov_b32 exec_lo, s0
; GFX11-NEXT:    s_waitcnt vmcnt(0)
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <10 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <10 x double> %a1 to <10 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <10 x double> %a to <10 x i64>
  br label %end

end:
  %phi = phi <10 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <10 x i64> %phi
}

define <40 x i16> @bitcast_v10i64_to_v40i16(<10 x i64> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v10i64_to_v40i16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:    ; implicit-def: $vgpr31
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr28
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr26
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr25
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr24
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr30
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr29
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr27
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB40_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_alignbit_b32 v20, v19, v18, 16
; SI-NEXT:    v_alignbit_b32 v21, v17, v16, 16
; SI-NEXT:    v_alignbit_b32 v22, v15, v14, 16
; SI-NEXT:    v_alignbit_b32 v23, v13, v12, 16
; SI-NEXT:    v_alignbit_b32 v24, v11, v10, 16
; SI-NEXT:    v_alignbit_b32 v25, v9, v8, 16
; SI-NEXT:    v_alignbit_b32 v26, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v28, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v31, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v34, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v27, 16, v19
; SI-NEXT:    v_lshrrev_b32_e32 v29, 16, v17
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v15
; SI-NEXT:    v_lshrrev_b32_e32 v32, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v33, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v35, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v36, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v37, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v39, 16, v1
; SI-NEXT:  .LBB40_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB40_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; SI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; SI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; SI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; SI-NEXT:    v_add_i32_e32 v8, vcc, 3, v8
; SI-NEXT:    v_addc_u32_e32 v9, vcc, 0, v9, vcc
; SI-NEXT:    v_add_i32_e32 v10, vcc, 3, v10
; SI-NEXT:    v_addc_u32_e32 v11, vcc, 0, v11, vcc
; SI-NEXT:    v_add_i32_e32 v12, vcc, 3, v12
; SI-NEXT:    v_addc_u32_e32 v13, vcc, 0, v13, vcc
; SI-NEXT:    v_add_i32_e32 v14, vcc, 3, v14
; SI-NEXT:    v_addc_u32_e32 v15, vcc, 0, v15, vcc
; SI-NEXT:    v_add_i32_e32 v16, vcc, 3, v16
; SI-NEXT:    v_addc_u32_e32 v17, vcc, 0, v17, vcc
; SI-NEXT:    v_add_i32_e32 v18, vcc, 3, v18
; SI-NEXT:    v_addc_u32_e32 v19, vcc, 0, v19, vcc
; SI-NEXT:    v_alignbit_b32 v20, v19, v18, 16
; SI-NEXT:    v_alignbit_b32 v21, v17, v16, 16
; SI-NEXT:    v_alignbit_b32 v22, v15, v14, 16
; SI-NEXT:    v_alignbit_b32 v23, v13, v12, 16
; SI-NEXT:    v_alignbit_b32 v24, v11, v10, 16
; SI-NEXT:    v_alignbit_b32 v25, v9, v8, 16
; SI-NEXT:    v_alignbit_b32 v26, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v28, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v31, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v34, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v27, 16, v19
; SI-NEXT:    v_lshrrev_b32_e32 v29, 16, v17
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v15
; SI-NEXT:    v_lshrrev_b32_e32 v32, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v33, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v35, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v36, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v37, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v39, 16, v1
; SI-NEXT:  .LBB40_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v34, 16, v34
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v31, 16, v31
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_lshlrev_b32_e32 v28, 16, v28
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v26, 16, v26
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; SI-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; SI-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v16
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; SI-NEXT:    v_or_b32_e32 v0, v0, v34
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v34, 16, v39
; SI-NEXT:    v_or_b32_e32 v2, v2, v31
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v31, 16, v38
; SI-NEXT:    v_or_b32_e32 v4, v4, v28
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v28, 16, v37
; SI-NEXT:    v_or_b32_e32 v6, v6, v26
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v26, 16, v36
; SI-NEXT:    v_or_b32_e32 v8, v8, v25
; SI-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; SI-NEXT:    v_lshlrev_b32_e32 v25, 16, v35
; SI-NEXT:    v_or_b32_e32 v10, v10, v24
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; SI-NEXT:    v_lshlrev_b32_e32 v24, 16, v33
; SI-NEXT:    v_or_b32_e32 v12, v12, v23
; SI-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v32
; SI-NEXT:    v_or_b32_e32 v14, v14, v22
; SI-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v30
; SI-NEXT:    v_or_b32_e32 v16, v16, v21
; SI-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v29
; SI-NEXT:    v_or_b32_e32 v18, v18, v20
; SI-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v27
; SI-NEXT:    v_or_b32_e32 v1, v1, v34
; SI-NEXT:    v_or_b32_e32 v3, v3, v31
; SI-NEXT:    v_or_b32_e32 v5, v5, v28
; SI-NEXT:    v_or_b32_e32 v7, v7, v26
; SI-NEXT:    v_or_b32_e32 v9, v9, v25
; SI-NEXT:    v_or_b32_e32 v11, v11, v24
; SI-NEXT:    v_or_b32_e32 v13, v13, v23
; SI-NEXT:    v_or_b32_e32 v15, v15, v22
; SI-NEXT:    v_or_b32_e32 v17, v17, v21
; SI-NEXT:    v_or_b32_e32 v19, v19, v20
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v10i64_to_v40i16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    ; implicit-def: $vgpr39
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr35
; VI-NEXT:    ; implicit-def: $vgpr34
; VI-NEXT:    ; implicit-def: $vgpr33
; VI-NEXT:    ; implicit-def: $vgpr32
; VI-NEXT:    ; implicit-def: $vgpr31
; VI-NEXT:    ; implicit-def: $vgpr30
; VI-NEXT:    ; implicit-def: $vgpr29
; VI-NEXT:    ; implicit-def: $vgpr28
; VI-NEXT:    ; implicit-def: $vgpr27
; VI-NEXT:    ; implicit-def: $vgpr26
; VI-NEXT:    ; implicit-def: $vgpr25
; VI-NEXT:    ; implicit-def: $vgpr24
; VI-NEXT:    ; implicit-def: $vgpr23
; VI-NEXT:    ; implicit-def: $vgpr22
; VI-NEXT:    ; implicit-def: $vgpr21
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB40_2
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; VI-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; VI-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; VI-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; VI-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; VI-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; VI-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; VI-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; VI-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; VI-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; VI-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; VI-NEXT:  .LBB40_2: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB40_4
; VI-NEXT:  ; %bb.3: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v18, vcc, 3, v18
; VI-NEXT:    v_addc_u32_e32 v19, vcc, 0, v19, vcc
; VI-NEXT:    v_add_u32_e32 v16, vcc, 3, v16
; VI-NEXT:    v_addc_u32_e32 v17, vcc, 0, v17, vcc
; VI-NEXT:    v_add_u32_e32 v14, vcc, 3, v14
; VI-NEXT:    v_addc_u32_e32 v15, vcc, 0, v15, vcc
; VI-NEXT:    v_add_u32_e32 v12, vcc, 3, v12
; VI-NEXT:    v_addc_u32_e32 v13, vcc, 0, v13, vcc
; VI-NEXT:    v_add_u32_e32 v10, vcc, 3, v10
; VI-NEXT:    v_addc_u32_e32 v11, vcc, 0, v11, vcc
; VI-NEXT:    v_add_u32_e32 v8, vcc, 3, v8
; VI-NEXT:    v_addc_u32_e32 v9, vcc, 0, v9, vcc
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; VI-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; VI-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; VI-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; VI-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; VI-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; VI-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; VI-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; VI-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; VI-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; VI-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; VI-NEXT:  .LBB40_4: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    v_lshlrev_b32_e32 v39, 16, v39
; VI-NEXT:    v_lshlrev_b32_e32 v38, 16, v38
; VI-NEXT:    v_lshlrev_b32_e32 v37, 16, v37
; VI-NEXT:    v_lshlrev_b32_e32 v36, 16, v36
; VI-NEXT:    v_lshlrev_b32_e32 v35, 16, v35
; VI-NEXT:    v_lshlrev_b32_e32 v34, 16, v34
; VI-NEXT:    v_lshlrev_b32_e32 v33, 16, v33
; VI-NEXT:    v_lshlrev_b32_e32 v32, 16, v32
; VI-NEXT:    v_lshlrev_b32_e32 v31, 16, v31
; VI-NEXT:    v_lshlrev_b32_e32 v30, 16, v30
; VI-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; VI-NEXT:    v_lshlrev_b32_e32 v28, 16, v28
; VI-NEXT:    v_lshlrev_b32_e32 v27, 16, v27
; VI-NEXT:    v_lshlrev_b32_e32 v26, 16, v26
; VI-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; VI-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; VI-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; VI-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; VI-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; VI-NEXT:    v_or_b32_sdwa v0, v0, v39 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v1, v1, v38 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v2, v2, v37 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v3, v3, v36 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v4, v4, v35 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v5, v5, v34 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v6, v6, v33 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v7, v7, v32 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v8, v8, v31 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v9, v9, v30 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v10, v10, v29 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v11, v11, v28 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v12, v12, v27 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v13, v13, v26 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v14, v14, v25 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v15, v15, v24 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v16, v16, v23 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v17, v17, v22 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v18, v18, v21 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v19, v19, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v10i64_to_v40i16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    ; implicit-def: $vgpr39
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr35
; GFX9-NEXT:    ; implicit-def: $vgpr34
; GFX9-NEXT:    ; implicit-def: $vgpr33
; GFX9-NEXT:    ; implicit-def: $vgpr32
; GFX9-NEXT:    ; implicit-def: $vgpr31
; GFX9-NEXT:    ; implicit-def: $vgpr30
; GFX9-NEXT:    ; implicit-def: $vgpr29
; GFX9-NEXT:    ; implicit-def: $vgpr28
; GFX9-NEXT:    ; implicit-def: $vgpr27
; GFX9-NEXT:    ; implicit-def: $vgpr26
; GFX9-NEXT:    ; implicit-def: $vgpr25
; GFX9-NEXT:    ; implicit-def: $vgpr24
; GFX9-NEXT:    ; implicit-def: $vgpr23
; GFX9-NEXT:    ; implicit-def: $vgpr22
; GFX9-NEXT:    ; implicit-def: $vgpr21
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB40_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX9-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX9-NEXT:  .LBB40_2: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB40_4
; GFX9-NEXT:  ; %bb.3: ; %cmp.true
; GFX9-NEXT:    v_add_co_u32_e32 v18, vcc, 3, v18
; GFX9-NEXT:    v_addc_co_u32_e32 v19, vcc, 0, v19, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v16, vcc, 3, v16
; GFX9-NEXT:    v_addc_co_u32_e32 v17, vcc, 0, v17, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v14, vcc, 3, v14
; GFX9-NEXT:    v_addc_co_u32_e32 v15, vcc, 0, v15, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v12, vcc, 3, v12
; GFX9-NEXT:    v_addc_co_u32_e32 v13, vcc, 0, v13, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v10, vcc, 3, v10
; GFX9-NEXT:    v_addc_co_u32_e32 v11, vcc, 0, v11, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v8, vcc, 3, v8
; GFX9-NEXT:    v_addc_co_u32_e32 v9, vcc, 0, v9, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v6, vcc, 3, v6
; GFX9-NEXT:    v_addc_co_u32_e32 v7, vcc, 0, v7, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v4, vcc, 3, v4
; GFX9-NEXT:    v_addc_co_u32_e32 v5, vcc, 0, v5, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v2, vcc, 3, v2
; GFX9-NEXT:    v_addc_co_u32_e32 v3, vcc, 0, v3, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v0, vcc, 3, v0
; GFX9-NEXT:    v_addc_co_u32_e32 v1, vcc, 0, v1, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX9-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX9-NEXT:  .LBB40_4: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_mov_b32 s4, 0x5040100
; GFX9-NEXT:    v_perm_b32 v0, v39, v0, s4
; GFX9-NEXT:    v_perm_b32 v1, v38, v1, s4
; GFX9-NEXT:    v_perm_b32 v2, v37, v2, s4
; GFX9-NEXT:    v_perm_b32 v3, v36, v3, s4
; GFX9-NEXT:    v_perm_b32 v4, v35, v4, s4
; GFX9-NEXT:    v_perm_b32 v5, v34, v5, s4
; GFX9-NEXT:    v_perm_b32 v6, v33, v6, s4
; GFX9-NEXT:    v_perm_b32 v7, v32, v7, s4
; GFX9-NEXT:    v_perm_b32 v8, v31, v8, s4
; GFX9-NEXT:    v_perm_b32 v9, v30, v9, s4
; GFX9-NEXT:    v_perm_b32 v10, v29, v10, s4
; GFX9-NEXT:    v_perm_b32 v11, v28, v11, s4
; GFX9-NEXT:    v_perm_b32 v12, v27, v12, s4
; GFX9-NEXT:    v_perm_b32 v13, v26, v13, s4
; GFX9-NEXT:    v_perm_b32 v14, v25, v14, s4
; GFX9-NEXT:    v_perm_b32 v15, v24, v15, s4
; GFX9-NEXT:    v_perm_b32 v16, v23, v16, s4
; GFX9-NEXT:    v_perm_b32 v17, v22, v17, s4
; GFX9-NEXT:    v_perm_b32 v18, v21, v18, s4
; GFX9-NEXT:    v_perm_b32 v19, v20, v19, s4
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v10i64_to_v40i16:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB40_2
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_add_co_u32 v18, vcc_lo, v18, 3
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add_co_ci_u32_e64 v19, null, 0, v19, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_co_u32 v16, vcc_lo, v16, 3
; GFX11-TRUE16-NEXT:    v_add_co_ci_u32_e64 v17, null, 0, v17, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_co_u32 v14, vcc_lo, v14, 3
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add_co_ci_u32_e64 v15, null, 0, v15, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_co_u32 v12, vcc_lo, v12, 3
; GFX11-TRUE16-NEXT:    v_add_co_ci_u32_e64 v13, null, 0, v13, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_co_u32 v10, vcc_lo, v10, 3
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add_co_ci_u32_e64 v11, null, 0, v11, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_co_u32 v8, vcc_lo, v8, 3
; GFX11-TRUE16-NEXT:    v_add_co_ci_u32_e64 v9, null, 0, v9, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_co_u32 v6, vcc_lo, v6, 3
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add_co_ci_u32_e64 v7, null, 0, v7, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_co_u32 v4, vcc_lo, v4, 3
; GFX11-TRUE16-NEXT:    v_add_co_ci_u32_e64 v5, null, 0, v5, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_co_u32 v2, vcc_lo, v2, 3
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add_co_ci_u32_e64 v3, null, 0, v3, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_co_u32 v0, vcc_lo, v0, 3
; GFX11-TRUE16-NEXT:    v_add_co_ci_u32_e64 v1, null, 0, v1, vcc_lo
; GFX11-TRUE16-NEXT:  .LBB40_2: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v10i64_to_v40i16:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr39
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr38
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr37
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr36
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr35
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr34
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr33
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr32
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr31
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr30
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr29
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr28
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr27
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr26
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr25
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr24
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr23
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr22
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr21
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB40_2
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX11-FAKE16-NEXT:  .LBB40_2: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB40_4
; GFX11-FAKE16-NEXT:  ; %bb.3: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_add_co_u32 v18, vcc_lo, v18, 3
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_add_co_ci_u32_e64 v19, null, 0, v19, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_co_u32 v16, vcc_lo, v16, 3
; GFX11-FAKE16-NEXT:    v_add_co_ci_u32_e64 v17, null, 0, v17, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_co_u32 v14, vcc_lo, v14, 3
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_add_co_ci_u32_e64 v15, null, 0, v15, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_co_u32 v12, vcc_lo, v12, 3
; GFX11-FAKE16-NEXT:    v_add_co_ci_u32_e64 v13, null, 0, v13, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_co_u32 v10, vcc_lo, v10, 3
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_add_co_ci_u32_e64 v11, null, 0, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_co_u32 v8, vcc_lo, v8, 3
; GFX11-FAKE16-NEXT:    v_add_co_ci_u32_e64 v9, null, 0, v9, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_co_u32 v6, vcc_lo, v6, 3
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_add_co_ci_u32_e64 v7, null, 0, v7, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_co_u32 v4, vcc_lo, v4, 3
; GFX11-FAKE16-NEXT:    v_add_co_ci_u32_e64 v5, null, 0, v5, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_co_u32 v2, vcc_lo, v2, 3
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_add_co_ci_u32_e64 v3, null, 0, v3, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_co_u32 v0, vcc_lo, v0, 3
; GFX11-FAKE16-NEXT:    v_add_co_ci_u32_e64 v1, null, 0, v1, vcc_lo
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX11-FAKE16-NEXT:  .LBB40_4: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v39, v0, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v38, v1, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v37, v2, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v36, v3, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v35, v4, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v34, v5, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v33, v6, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v32, v7, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, v31, v8, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, v30, v9, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, v29, v10, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, v28, v11, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, v27, v12, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, v26, v13, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v14, v25, v14, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v15, v24, v15, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v16, v23, v16, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v17, v22, v17, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v18, v21, v18, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v19, v20, v19, 0x5040100
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <10 x i64> %a, splat (i64 3)
  %a2 = bitcast <10 x i64> %a1 to <40 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <10 x i64> %a to <40 x i16>
  br label %end

end:
  %phi = phi <40 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <40 x i16> %phi
}

define inreg <40 x i16> @bitcast_v10i64_to_v40i16_scalar(<10 x i64> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v10i64_to_v40i16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_readfirstlane_b32 s8, v6
; SI-NEXT:    v_readfirstlane_b32 s5, v5
; SI-NEXT:    v_readfirstlane_b32 s4, v4
; SI-NEXT:    v_readfirstlane_b32 s7, v3
; SI-NEXT:    v_readfirstlane_b32 s6, v2
; SI-NEXT:    v_readfirstlane_b32 s9, v1
; SI-NEXT:    s_cmp_lg_u32 s8, 0
; SI-NEXT:    v_readfirstlane_b32 s8, v0
; SI-NEXT:    s_cbranch_scc0 .LBB41_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_lshr_b32 s72, s5, 16
; SI-NEXT:    s_lshr_b32 s73, s7, 16
; SI-NEXT:    s_lshr_b32 s74, s9, 16
; SI-NEXT:    s_lshr_b32 s75, s29, 16
; SI-NEXT:    s_lshr_b32 s76, s27, 16
; SI-NEXT:    s_lshr_b32 s77, s25, 16
; SI-NEXT:    s_lshr_b32 s78, s23, 16
; SI-NEXT:    s_lshr_b32 s79, s21, 16
; SI-NEXT:    s_lshr_b32 s88, s19, 16
; SI-NEXT:    s_lshr_b32 s89, s17, 16
; SI-NEXT:    s_lshr_b64 s[10:11], s[4:5], 16
; SI-NEXT:    s_lshr_b64 s[12:13], s[6:7], 16
; SI-NEXT:    s_lshr_b64 s[14:15], s[8:9], 16
; SI-NEXT:    s_lshr_b64 s[40:41], s[28:29], 16
; SI-NEXT:    s_lshr_b64 s[42:43], s[26:27], 16
; SI-NEXT:    s_lshr_b64 s[44:45], s[24:25], 16
; SI-NEXT:    s_lshr_b64 s[46:47], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[56:57], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[58:59], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[60:61], s[16:17], 16
; SI-NEXT:    s_cbranch_execnz .LBB41_3
; SI-NEXT:  .LBB41_2: ; %cmp.true
; SI-NEXT:    s_add_u32 s4, s4, 3
; SI-NEXT:    s_addc_u32 s5, s5, 0
; SI-NEXT:    s_add_u32 s6, s6, 3
; SI-NEXT:    s_addc_u32 s7, s7, 0
; SI-NEXT:    s_add_u32 s8, s8, 3
; SI-NEXT:    s_addc_u32 s9, s9, 0
; SI-NEXT:    s_add_u32 s28, s28, 3
; SI-NEXT:    s_addc_u32 s29, s29, 0
; SI-NEXT:    s_add_u32 s26, s26, 3
; SI-NEXT:    s_addc_u32 s27, s27, 0
; SI-NEXT:    s_add_u32 s24, s24, 3
; SI-NEXT:    s_addc_u32 s25, s25, 0
; SI-NEXT:    s_add_u32 s22, s22, 3
; SI-NEXT:    s_addc_u32 s23, s23, 0
; SI-NEXT:    s_add_u32 s20, s20, 3
; SI-NEXT:    s_addc_u32 s21, s21, 0
; SI-NEXT:    s_add_u32 s18, s18, 3
; SI-NEXT:    s_addc_u32 s19, s19, 0
; SI-NEXT:    s_add_u32 s16, s16, 3
; SI-NEXT:    s_addc_u32 s17, s17, 0
; SI-NEXT:    s_lshr_b32 s72, s5, 16
; SI-NEXT:    s_lshr_b32 s73, s7, 16
; SI-NEXT:    s_lshr_b32 s74, s9, 16
; SI-NEXT:    s_lshr_b32 s75, s29, 16
; SI-NEXT:    s_lshr_b32 s76, s27, 16
; SI-NEXT:    s_lshr_b32 s77, s25, 16
; SI-NEXT:    s_lshr_b32 s78, s23, 16
; SI-NEXT:    s_lshr_b32 s79, s21, 16
; SI-NEXT:    s_lshr_b32 s88, s19, 16
; SI-NEXT:    s_lshr_b32 s89, s17, 16
; SI-NEXT:    s_lshr_b64 s[10:11], s[4:5], 16
; SI-NEXT:    s_lshr_b64 s[12:13], s[6:7], 16
; SI-NEXT:    s_lshr_b64 s[14:15], s[8:9], 16
; SI-NEXT:    s_lshr_b64 s[40:41], s[28:29], 16
; SI-NEXT:    s_lshr_b64 s[42:43], s[26:27], 16
; SI-NEXT:    s_lshr_b64 s[44:45], s[24:25], 16
; SI-NEXT:    s_lshr_b64 s[46:47], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[56:57], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[58:59], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[60:61], s[16:17], 16
; SI-NEXT:  .LBB41_3: ; %end
; SI-NEXT:    s_lshl_b32 s11, s60, 16
; SI-NEXT:    s_and_b32 s13, s16, 0xffff
; SI-NEXT:    s_or_b32 s11, s13, s11
; SI-NEXT:    s_and_b32 s13, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s15, s89, 16
; SI-NEXT:    s_or_b32 s13, s13, s15
; SI-NEXT:    s_lshl_b32 s15, s58, 16
; SI-NEXT:    s_and_b32 s16, s18, 0xffff
; SI-NEXT:    s_or_b32 s15, s16, s15
; SI-NEXT:    s_and_b32 s16, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s17, s88, 16
; SI-NEXT:    s_or_b32 s16, s16, s17
; SI-NEXT:    s_lshl_b32 s17, s56, 16
; SI-NEXT:    s_and_b32 s18, s20, 0xffff
; SI-NEXT:    s_or_b32 s17, s18, s17
; SI-NEXT:    s_and_b32 s18, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s19, s79, 16
; SI-NEXT:    s_or_b32 s18, s18, s19
; SI-NEXT:    s_and_b32 s19, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s20, s46, 16
; SI-NEXT:    s_or_b32 s19, s19, s20
; SI-NEXT:    s_and_b32 s20, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s21, s78, 16
; SI-NEXT:    s_or_b32 s20, s20, s21
; SI-NEXT:    s_and_b32 s21, s24, 0xffff
; SI-NEXT:    s_lshl_b32 s22, s44, 16
; SI-NEXT:    s_or_b32 s21, s21, s22
; SI-NEXT:    s_and_b32 s22, s25, 0xffff
; SI-NEXT:    s_lshl_b32 s23, s77, 16
; SI-NEXT:    s_or_b32 s22, s22, s23
; SI-NEXT:    s_and_b32 s23, s26, 0xffff
; SI-NEXT:    s_lshl_b32 s24, s42, 16
; SI-NEXT:    s_or_b32 s23, s23, s24
; SI-NEXT:    s_and_b32 s24, s27, 0xffff
; SI-NEXT:    s_lshl_b32 s25, s76, 16
; SI-NEXT:    s_or_b32 s24, s24, s25
; SI-NEXT:    s_and_b32 s25, s28, 0xffff
; SI-NEXT:    s_lshl_b32 s26, s40, 16
; SI-NEXT:    s_and_b32 s8, s8, 0xffff
; SI-NEXT:    s_lshl_b32 s14, s14, 16
; SI-NEXT:    s_and_b32 s6, s6, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s12, 16
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s10, 16
; SI-NEXT:    s_or_b32 s25, s25, s26
; SI-NEXT:    s_and_b32 s26, s29, 0xffff
; SI-NEXT:    s_lshl_b32 s27, s75, 16
; SI-NEXT:    s_or_b32 s8, s8, s14
; SI-NEXT:    s_and_b32 s9, s9, 0xffff
; SI-NEXT:    s_lshl_b32 s14, s74, 16
; SI-NEXT:    s_or_b32 s6, s6, s12
; SI-NEXT:    s_and_b32 s7, s7, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s73, 16
; SI-NEXT:    s_or_b32 s4, s4, s10
; SI-NEXT:    s_and_b32 s5, s5, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s72, 16
; SI-NEXT:    s_or_b32 s26, s26, s27
; SI-NEXT:    s_or_b32 s9, s9, s14
; SI-NEXT:    s_or_b32 s7, s7, s12
; SI-NEXT:    s_or_b32 s5, s5, s10
; SI-NEXT:    v_mov_b32_e32 v0, s11
; SI-NEXT:    v_mov_b32_e32 v1, s13
; SI-NEXT:    v_mov_b32_e32 v2, s15
; SI-NEXT:    v_mov_b32_e32 v3, s16
; SI-NEXT:    v_mov_b32_e32 v4, s17
; SI-NEXT:    v_mov_b32_e32 v5, s18
; SI-NEXT:    v_mov_b32_e32 v6, s19
; SI-NEXT:    v_mov_b32_e32 v7, s20
; SI-NEXT:    v_mov_b32_e32 v8, s21
; SI-NEXT:    v_mov_b32_e32 v9, s22
; SI-NEXT:    v_mov_b32_e32 v10, s23
; SI-NEXT:    v_mov_b32_e32 v11, s24
; SI-NEXT:    v_mov_b32_e32 v12, s25
; SI-NEXT:    v_mov_b32_e32 v13, s26
; SI-NEXT:    v_mov_b32_e32 v14, s8
; SI-NEXT:    v_mov_b32_e32 v15, s9
; SI-NEXT:    v_mov_b32_e32 v16, s6
; SI-NEXT:    v_mov_b32_e32 v17, s7
; SI-NEXT:    v_mov_b32_e32 v18, s4
; SI-NEXT:    v_mov_b32_e32 v19, s5
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB41_4:
; SI-NEXT:    ; implicit-def: $sgpr60
; SI-NEXT:    ; implicit-def: $sgpr89
; SI-NEXT:    ; implicit-def: $sgpr58
; SI-NEXT:    ; implicit-def: $sgpr88
; SI-NEXT:    ; implicit-def: $sgpr56
; SI-NEXT:    ; implicit-def: $sgpr79
; SI-NEXT:    ; implicit-def: $sgpr46
; SI-NEXT:    ; implicit-def: $sgpr78
; SI-NEXT:    ; implicit-def: $sgpr44
; SI-NEXT:    ; implicit-def: $sgpr77
; SI-NEXT:    ; implicit-def: $sgpr42
; SI-NEXT:    ; implicit-def: $sgpr76
; SI-NEXT:    ; implicit-def: $sgpr40
; SI-NEXT:    ; implicit-def: $sgpr75
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr74
; SI-NEXT:    ; implicit-def: $sgpr12
; SI-NEXT:    ; implicit-def: $sgpr73
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr72
; SI-NEXT:    s_branch .LBB41_2
;
; VI-LABEL: bitcast_v10i64_to_v40i16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    v_readfirstlane_b32 s6, v5
; VI-NEXT:    v_readfirstlane_b32 s7, v4
; VI-NEXT:    v_readfirstlane_b32 s8, v3
; VI-NEXT:    v_readfirstlane_b32 s9, v2
; VI-NEXT:    v_readfirstlane_b32 s10, v1
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    v_readfirstlane_b32 s11, v0
; VI-NEXT:    s_cbranch_scc0 .LBB41_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_lshr_b32 s12, s6, 16
; VI-NEXT:    s_lshr_b32 s13, s7, 16
; VI-NEXT:    s_lshr_b32 s14, s8, 16
; VI-NEXT:    s_lshr_b32 s15, s9, 16
; VI-NEXT:    s_lshr_b32 s40, s10, 16
; VI-NEXT:    s_lshr_b32 s41, s11, 16
; VI-NEXT:    s_lshr_b32 s42, s29, 16
; VI-NEXT:    s_lshr_b32 s43, s28, 16
; VI-NEXT:    s_lshr_b32 s44, s27, 16
; VI-NEXT:    s_lshr_b32 s45, s26, 16
; VI-NEXT:    s_lshr_b32 s46, s25, 16
; VI-NEXT:    s_lshr_b32 s47, s24, 16
; VI-NEXT:    s_lshr_b32 s56, s23, 16
; VI-NEXT:    s_lshr_b32 s57, s22, 16
; VI-NEXT:    s_lshr_b32 s58, s21, 16
; VI-NEXT:    s_lshr_b32 s59, s20, 16
; VI-NEXT:    s_lshr_b32 s60, s19, 16
; VI-NEXT:    s_lshr_b32 s61, s18, 16
; VI-NEXT:    s_lshr_b32 s62, s17, 16
; VI-NEXT:    s_lshr_b32 s63, s16, 16
; VI-NEXT:    s_cbranch_execnz .LBB41_3
; VI-NEXT:  .LBB41_2: ; %cmp.true
; VI-NEXT:    s_add_u32 s7, s7, 3
; VI-NEXT:    s_addc_u32 s6, s6, 0
; VI-NEXT:    s_add_u32 s9, s9, 3
; VI-NEXT:    s_addc_u32 s8, s8, 0
; VI-NEXT:    s_add_u32 s11, s11, 3
; VI-NEXT:    s_addc_u32 s10, s10, 0
; VI-NEXT:    s_add_u32 s28, s28, 3
; VI-NEXT:    s_addc_u32 s29, s29, 0
; VI-NEXT:    s_add_u32 s26, s26, 3
; VI-NEXT:    s_addc_u32 s27, s27, 0
; VI-NEXT:    s_add_u32 s24, s24, 3
; VI-NEXT:    s_addc_u32 s25, s25, 0
; VI-NEXT:    s_add_u32 s22, s22, 3
; VI-NEXT:    s_addc_u32 s23, s23, 0
; VI-NEXT:    s_add_u32 s20, s20, 3
; VI-NEXT:    s_addc_u32 s21, s21, 0
; VI-NEXT:    s_add_u32 s18, s18, 3
; VI-NEXT:    s_addc_u32 s19, s19, 0
; VI-NEXT:    s_add_u32 s16, s16, 3
; VI-NEXT:    s_addc_u32 s17, s17, 0
; VI-NEXT:    s_lshr_b32 s12, s6, 16
; VI-NEXT:    s_lshr_b32 s13, s7, 16
; VI-NEXT:    s_lshr_b32 s14, s8, 16
; VI-NEXT:    s_lshr_b32 s15, s9, 16
; VI-NEXT:    s_lshr_b32 s40, s10, 16
; VI-NEXT:    s_lshr_b32 s41, s11, 16
; VI-NEXT:    s_lshr_b32 s42, s29, 16
; VI-NEXT:    s_lshr_b32 s43, s28, 16
; VI-NEXT:    s_lshr_b32 s44, s27, 16
; VI-NEXT:    s_lshr_b32 s45, s26, 16
; VI-NEXT:    s_lshr_b32 s46, s25, 16
; VI-NEXT:    s_lshr_b32 s47, s24, 16
; VI-NEXT:    s_lshr_b32 s56, s23, 16
; VI-NEXT:    s_lshr_b32 s57, s22, 16
; VI-NEXT:    s_lshr_b32 s58, s21, 16
; VI-NEXT:    s_lshr_b32 s59, s20, 16
; VI-NEXT:    s_lshr_b32 s60, s19, 16
; VI-NEXT:    s_lshr_b32 s61, s18, 16
; VI-NEXT:    s_lshr_b32 s62, s17, 16
; VI-NEXT:    s_lshr_b32 s63, s16, 16
; VI-NEXT:  .LBB41_3: ; %end
; VI-NEXT:    s_and_b32 s4, 0xffff, s16
; VI-NEXT:    s_lshl_b32 s5, s63, 16
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_and_b32 s5, 0xffff, s17
; VI-NEXT:    s_lshl_b32 s16, s62, 16
; VI-NEXT:    s_or_b32 s5, s5, s16
; VI-NEXT:    s_and_b32 s16, 0xffff, s18
; VI-NEXT:    s_lshl_b32 s17, s61, 16
; VI-NEXT:    s_or_b32 s16, s16, s17
; VI-NEXT:    s_and_b32 s17, 0xffff, s19
; VI-NEXT:    s_lshl_b32 s18, s60, 16
; VI-NEXT:    s_or_b32 s17, s17, s18
; VI-NEXT:    s_and_b32 s18, 0xffff, s20
; VI-NEXT:    s_lshl_b32 s19, s59, 16
; VI-NEXT:    s_or_b32 s18, s18, s19
; VI-NEXT:    s_and_b32 s19, 0xffff, s21
; VI-NEXT:    s_lshl_b32 s20, s58, 16
; VI-NEXT:    s_or_b32 s19, s19, s20
; VI-NEXT:    s_and_b32 s20, 0xffff, s22
; VI-NEXT:    s_lshl_b32 s21, s57, 16
; VI-NEXT:    s_or_b32 s20, s20, s21
; VI-NEXT:    s_and_b32 s21, 0xffff, s23
; VI-NEXT:    s_lshl_b32 s22, s56, 16
; VI-NEXT:    s_or_b32 s21, s21, s22
; VI-NEXT:    s_and_b32 s22, 0xffff, s24
; VI-NEXT:    s_lshl_b32 s23, s47, 16
; VI-NEXT:    s_or_b32 s22, s22, s23
; VI-NEXT:    s_and_b32 s23, 0xffff, s25
; VI-NEXT:    s_lshl_b32 s24, s46, 16
; VI-NEXT:    s_or_b32 s23, s23, s24
; VI-NEXT:    s_and_b32 s24, 0xffff, s26
; VI-NEXT:    s_lshl_b32 s25, s45, 16
; VI-NEXT:    s_or_b32 s24, s24, s25
; VI-NEXT:    s_and_b32 s25, 0xffff, s27
; VI-NEXT:    s_lshl_b32 s26, s44, 16
; VI-NEXT:    s_or_b32 s25, s25, s26
; VI-NEXT:    s_and_b32 s26, 0xffff, s28
; VI-NEXT:    s_lshl_b32 s27, s43, 16
; VI-NEXT:    s_or_b32 s26, s26, s27
; VI-NEXT:    s_and_b32 s27, 0xffff, s29
; VI-NEXT:    s_lshl_b32 s28, s42, 16
; VI-NEXT:    s_or_b32 s27, s27, s28
; VI-NEXT:    s_and_b32 s11, 0xffff, s11
; VI-NEXT:    s_lshl_b32 s28, s41, 16
; VI-NEXT:    s_or_b32 s11, s11, s28
; VI-NEXT:    s_and_b32 s10, 0xffff, s10
; VI-NEXT:    s_lshl_b32 s28, s40, 16
; VI-NEXT:    s_and_b32 s9, 0xffff, s9
; VI-NEXT:    s_lshl_b32 s15, s15, 16
; VI-NEXT:    s_and_b32 s8, 0xffff, s8
; VI-NEXT:    s_lshl_b32 s14, s14, 16
; VI-NEXT:    s_and_b32 s7, 0xffff, s7
; VI-NEXT:    s_lshl_b32 s13, s13, 16
; VI-NEXT:    s_and_b32 s6, 0xffff, s6
; VI-NEXT:    s_lshl_b32 s12, s12, 16
; VI-NEXT:    s_or_b32 s10, s10, s28
; VI-NEXT:    s_or_b32 s9, s9, s15
; VI-NEXT:    s_or_b32 s8, s8, s14
; VI-NEXT:    s_or_b32 s7, s7, s13
; VI-NEXT:    s_or_b32 s6, s6, s12
; VI-NEXT:    v_mov_b32_e32 v0, s4
; VI-NEXT:    v_mov_b32_e32 v1, s5
; VI-NEXT:    v_mov_b32_e32 v2, s16
; VI-NEXT:    v_mov_b32_e32 v3, s17
; VI-NEXT:    v_mov_b32_e32 v4, s18
; VI-NEXT:    v_mov_b32_e32 v5, s19
; VI-NEXT:    v_mov_b32_e32 v6, s20
; VI-NEXT:    v_mov_b32_e32 v7, s21
; VI-NEXT:    v_mov_b32_e32 v8, s22
; VI-NEXT:    v_mov_b32_e32 v9, s23
; VI-NEXT:    v_mov_b32_e32 v10, s24
; VI-NEXT:    v_mov_b32_e32 v11, s25
; VI-NEXT:    v_mov_b32_e32 v12, s26
; VI-NEXT:    v_mov_b32_e32 v13, s27
; VI-NEXT:    v_mov_b32_e32 v14, s11
; VI-NEXT:    v_mov_b32_e32 v15, s10
; VI-NEXT:    v_mov_b32_e32 v16, s9
; VI-NEXT:    v_mov_b32_e32 v17, s8
; VI-NEXT:    v_mov_b32_e32 v18, s7
; VI-NEXT:    v_mov_b32_e32 v19, s6
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB41_4:
; VI-NEXT:    ; implicit-def: $sgpr63
; VI-NEXT:    ; implicit-def: $sgpr62
; VI-NEXT:    ; implicit-def: $sgpr61
; VI-NEXT:    ; implicit-def: $sgpr60
; VI-NEXT:    ; implicit-def: $sgpr59
; VI-NEXT:    ; implicit-def: $sgpr58
; VI-NEXT:    ; implicit-def: $sgpr57
; VI-NEXT:    ; implicit-def: $sgpr56
; VI-NEXT:    ; implicit-def: $sgpr47
; VI-NEXT:    ; implicit-def: $sgpr46
; VI-NEXT:    ; implicit-def: $sgpr45
; VI-NEXT:    ; implicit-def: $sgpr44
; VI-NEXT:    ; implicit-def: $sgpr43
; VI-NEXT:    ; implicit-def: $sgpr42
; VI-NEXT:    ; implicit-def: $sgpr41
; VI-NEXT:    ; implicit-def: $sgpr40
; VI-NEXT:    ; implicit-def: $sgpr15
; VI-NEXT:    ; implicit-def: $sgpr14
; VI-NEXT:    ; implicit-def: $sgpr13
; VI-NEXT:    ; implicit-def: $sgpr12
; VI-NEXT:    s_branch .LBB41_2
;
; GFX9-LABEL: bitcast_v10i64_to_v40i16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_readfirstlane_b32 s4, v6
; GFX9-NEXT:    v_readfirstlane_b32 s6, v5
; GFX9-NEXT:    v_readfirstlane_b32 s7, v4
; GFX9-NEXT:    v_readfirstlane_b32 s8, v3
; GFX9-NEXT:    v_readfirstlane_b32 s9, v2
; GFX9-NEXT:    v_readfirstlane_b32 s10, v1
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    v_readfirstlane_b32 s11, v0
; GFX9-NEXT:    s_cbranch_scc0 .LBB41_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_lshr_b32 s12, s6, 16
; GFX9-NEXT:    s_lshr_b32 s13, s7, 16
; GFX9-NEXT:    s_lshr_b32 s14, s8, 16
; GFX9-NEXT:    s_lshr_b32 s15, s9, 16
; GFX9-NEXT:    s_lshr_b32 s40, s10, 16
; GFX9-NEXT:    s_lshr_b32 s41, s11, 16
; GFX9-NEXT:    s_lshr_b32 s42, s29, 16
; GFX9-NEXT:    s_lshr_b32 s43, s28, 16
; GFX9-NEXT:    s_lshr_b32 s44, s27, 16
; GFX9-NEXT:    s_lshr_b32 s45, s26, 16
; GFX9-NEXT:    s_lshr_b32 s46, s25, 16
; GFX9-NEXT:    s_lshr_b32 s47, s24, 16
; GFX9-NEXT:    s_lshr_b32 s56, s23, 16
; GFX9-NEXT:    s_lshr_b32 s57, s22, 16
; GFX9-NEXT:    s_lshr_b32 s58, s21, 16
; GFX9-NEXT:    s_lshr_b32 s59, s20, 16
; GFX9-NEXT:    s_lshr_b32 s60, s19, 16
; GFX9-NEXT:    s_lshr_b32 s61, s18, 16
; GFX9-NEXT:    s_lshr_b32 s62, s17, 16
; GFX9-NEXT:    s_lshr_b32 s63, s16, 16
; GFX9-NEXT:    s_cbranch_execnz .LBB41_3
; GFX9-NEXT:  .LBB41_2: ; %cmp.true
; GFX9-NEXT:    s_add_u32 s7, s7, 3
; GFX9-NEXT:    s_addc_u32 s6, s6, 0
; GFX9-NEXT:    s_add_u32 s9, s9, 3
; GFX9-NEXT:    s_addc_u32 s8, s8, 0
; GFX9-NEXT:    s_add_u32 s11, s11, 3
; GFX9-NEXT:    s_addc_u32 s10, s10, 0
; GFX9-NEXT:    s_add_u32 s28, s28, 3
; GFX9-NEXT:    s_addc_u32 s29, s29, 0
; GFX9-NEXT:    s_add_u32 s26, s26, 3
; GFX9-NEXT:    s_addc_u32 s27, s27, 0
; GFX9-NEXT:    s_add_u32 s24, s24, 3
; GFX9-NEXT:    s_addc_u32 s25, s25, 0
; GFX9-NEXT:    s_add_u32 s22, s22, 3
; GFX9-NEXT:    s_addc_u32 s23, s23, 0
; GFX9-NEXT:    s_add_u32 s20, s20, 3
; GFX9-NEXT:    s_addc_u32 s21, s21, 0
; GFX9-NEXT:    s_add_u32 s18, s18, 3
; GFX9-NEXT:    s_addc_u32 s19, s19, 0
; GFX9-NEXT:    s_add_u32 s16, s16, 3
; GFX9-NEXT:    s_addc_u32 s17, s17, 0
; GFX9-NEXT:    s_lshr_b32 s12, s6, 16
; GFX9-NEXT:    s_lshr_b32 s13, s7, 16
; GFX9-NEXT:    s_lshr_b32 s14, s8, 16
; GFX9-NEXT:    s_lshr_b32 s15, s9, 16
; GFX9-NEXT:    s_lshr_b32 s40, s10, 16
; GFX9-NEXT:    s_lshr_b32 s41, s11, 16
; GFX9-NEXT:    s_lshr_b32 s42, s29, 16
; GFX9-NEXT:    s_lshr_b32 s43, s28, 16
; GFX9-NEXT:    s_lshr_b32 s44, s27, 16
; GFX9-NEXT:    s_lshr_b32 s45, s26, 16
; GFX9-NEXT:    s_lshr_b32 s46, s25, 16
; GFX9-NEXT:    s_lshr_b32 s47, s24, 16
; GFX9-NEXT:    s_lshr_b32 s56, s23, 16
; GFX9-NEXT:    s_lshr_b32 s57, s22, 16
; GFX9-NEXT:    s_lshr_b32 s58, s21, 16
; GFX9-NEXT:    s_lshr_b32 s59, s20, 16
; GFX9-NEXT:    s_lshr_b32 s60, s19, 16
; GFX9-NEXT:    s_lshr_b32 s61, s18, 16
; GFX9-NEXT:    s_lshr_b32 s62, s17, 16
; GFX9-NEXT:    s_lshr_b32 s63, s16, 16
; GFX9-NEXT:  .LBB41_3: ; %end
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s16, s63
; GFX9-NEXT:    s_pack_ll_b32_b16 s5, s17, s62
; GFX9-NEXT:    s_pack_ll_b32_b16 s16, s18, s61
; GFX9-NEXT:    s_pack_ll_b32_b16 s17, s19, s60
; GFX9-NEXT:    s_pack_ll_b32_b16 s18, s20, s59
; GFX9-NEXT:    s_pack_ll_b32_b16 s19, s21, s58
; GFX9-NEXT:    s_pack_ll_b32_b16 s20, s22, s57
; GFX9-NEXT:    s_pack_ll_b32_b16 s21, s23, s56
; GFX9-NEXT:    s_pack_ll_b32_b16 s22, s24, s47
; GFX9-NEXT:    s_pack_ll_b32_b16 s23, s25, s46
; GFX9-NEXT:    s_pack_ll_b32_b16 s24, s26, s45
; GFX9-NEXT:    s_pack_ll_b32_b16 s25, s27, s44
; GFX9-NEXT:    s_pack_ll_b32_b16 s26, s28, s43
; GFX9-NEXT:    s_pack_ll_b32_b16 s27, s29, s42
; GFX9-NEXT:    s_pack_ll_b32_b16 s11, s11, s41
; GFX9-NEXT:    s_pack_ll_b32_b16 s10, s10, s40
; GFX9-NEXT:    s_pack_ll_b32_b16 s9, s9, s15
; GFX9-NEXT:    s_pack_ll_b32_b16 s8, s8, s14
; GFX9-NEXT:    s_pack_ll_b32_b16 s7, s7, s13
; GFX9-NEXT:    s_pack_ll_b32_b16 s6, s6, s12
; GFX9-NEXT:    v_mov_b32_e32 v0, s4
; GFX9-NEXT:    v_mov_b32_e32 v1, s5
; GFX9-NEXT:    v_mov_b32_e32 v2, s16
; GFX9-NEXT:    v_mov_b32_e32 v3, s17
; GFX9-NEXT:    v_mov_b32_e32 v4, s18
; GFX9-NEXT:    v_mov_b32_e32 v5, s19
; GFX9-NEXT:    v_mov_b32_e32 v6, s20
; GFX9-NEXT:    v_mov_b32_e32 v7, s21
; GFX9-NEXT:    v_mov_b32_e32 v8, s22
; GFX9-NEXT:    v_mov_b32_e32 v9, s23
; GFX9-NEXT:    v_mov_b32_e32 v10, s24
; GFX9-NEXT:    v_mov_b32_e32 v11, s25
; GFX9-NEXT:    v_mov_b32_e32 v12, s26
; GFX9-NEXT:    v_mov_b32_e32 v13, s27
; GFX9-NEXT:    v_mov_b32_e32 v14, s11
; GFX9-NEXT:    v_mov_b32_e32 v15, s10
; GFX9-NEXT:    v_mov_b32_e32 v16, s9
; GFX9-NEXT:    v_mov_b32_e32 v17, s8
; GFX9-NEXT:    v_mov_b32_e32 v18, s7
; GFX9-NEXT:    v_mov_b32_e32 v19, s6
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB41_4:
; GFX9-NEXT:    ; implicit-def: $sgpr63
; GFX9-NEXT:    ; implicit-def: $sgpr62
; GFX9-NEXT:    ; implicit-def: $sgpr61
; GFX9-NEXT:    ; implicit-def: $sgpr60
; GFX9-NEXT:    ; implicit-def: $sgpr59
; GFX9-NEXT:    ; implicit-def: $sgpr58
; GFX9-NEXT:    ; implicit-def: $sgpr57
; GFX9-NEXT:    ; implicit-def: $sgpr56
; GFX9-NEXT:    ; implicit-def: $sgpr47
; GFX9-NEXT:    ; implicit-def: $sgpr46
; GFX9-NEXT:    ; implicit-def: $sgpr45
; GFX9-NEXT:    ; implicit-def: $sgpr44
; GFX9-NEXT:    ; implicit-def: $sgpr43
; GFX9-NEXT:    ; implicit-def: $sgpr42
; GFX9-NEXT:    ; implicit-def: $sgpr41
; GFX9-NEXT:    ; implicit-def: $sgpr40
; GFX9-NEXT:    ; implicit-def: $sgpr15
; GFX9-NEXT:    ; implicit-def: $sgpr14
; GFX9-NEXT:    ; implicit-def: $sgpr13
; GFX9-NEXT:    ; implicit-def: $sgpr12
; GFX9-NEXT:    s_branch .LBB41_2
;
; GFX11-LABEL: bitcast_v10i64_to_v40i16_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    v_readfirstlane_b32 s6, v2
; GFX11-NEXT:    v_readfirstlane_b32 s4, v1
; GFX11-NEXT:    v_readfirstlane_b32 s5, v0
; GFX11-NEXT:    s_mov_b32 s58, 0
; GFX11-NEXT:    s_cmp_lg_u32 s6, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB41_4
; GFX11-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-NEXT:    s_lshr_b32 s6, s4, 16
; GFX11-NEXT:    s_lshr_b32 s7, s5, 16
; GFX11-NEXT:    s_lshr_b32 s8, s29, 16
; GFX11-NEXT:    s_lshr_b32 s9, s28, 16
; GFX11-NEXT:    s_lshr_b32 s10, s27, 16
; GFX11-NEXT:    s_lshr_b32 s11, s26, 16
; GFX11-NEXT:    s_lshr_b32 s12, s25, 16
; GFX11-NEXT:    s_lshr_b32 s13, s24, 16
; GFX11-NEXT:    s_lshr_b32 s14, s23, 16
; GFX11-NEXT:    s_lshr_b32 s15, s22, 16
; GFX11-NEXT:    s_lshr_b32 s40, s21, 16
; GFX11-NEXT:    s_lshr_b32 s41, s20, 16
; GFX11-NEXT:    s_lshr_b32 s42, s19, 16
; GFX11-NEXT:    s_lshr_b32 s43, s18, 16
; GFX11-NEXT:    s_lshr_b32 s44, s17, 16
; GFX11-NEXT:    s_lshr_b32 s45, s16, 16
; GFX11-NEXT:    s_lshr_b32 s46, s3, 16
; GFX11-NEXT:    s_lshr_b32 s47, s2, 16
; GFX11-NEXT:    s_lshr_b32 s56, s1, 16
; GFX11-NEXT:    s_lshr_b32 s57, s0, 16
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s58
; GFX11-NEXT:    s_cbranch_vccnz .LBB41_3
; GFX11-NEXT:  .LBB41_2: ; %cmp.true
; GFX11-NEXT:    s_add_u32 s5, s5, 3
; GFX11-NEXT:    s_addc_u32 s4, s4, 0
; GFX11-NEXT:    s_add_u32 s28, s28, 3
; GFX11-NEXT:    s_addc_u32 s29, s29, 0
; GFX11-NEXT:    s_add_u32 s26, s26, 3
; GFX11-NEXT:    s_addc_u32 s27, s27, 0
; GFX11-NEXT:    s_add_u32 s24, s24, 3
; GFX11-NEXT:    s_addc_u32 s25, s25, 0
; GFX11-NEXT:    s_add_u32 s22, s22, 3
; GFX11-NEXT:    s_addc_u32 s23, s23, 0
; GFX11-NEXT:    s_add_u32 s20, s20, 3
; GFX11-NEXT:    s_addc_u32 s21, s21, 0
; GFX11-NEXT:    s_add_u32 s18, s18, 3
; GFX11-NEXT:    s_addc_u32 s19, s19, 0
; GFX11-NEXT:    s_add_u32 s16, s16, 3
; GFX11-NEXT:    s_addc_u32 s17, s17, 0
; GFX11-NEXT:    s_add_u32 s2, s2, 3
; GFX11-NEXT:    s_addc_u32 s3, s3, 0
; GFX11-NEXT:    s_add_u32 s0, s0, 3
; GFX11-NEXT:    s_addc_u32 s1, s1, 0
; GFX11-NEXT:    s_lshr_b32 s6, s4, 16
; GFX11-NEXT:    s_lshr_b32 s7, s5, 16
; GFX11-NEXT:    s_lshr_b32 s8, s29, 16
; GFX11-NEXT:    s_lshr_b32 s9, s28, 16
; GFX11-NEXT:    s_lshr_b32 s10, s27, 16
; GFX11-NEXT:    s_lshr_b32 s11, s26, 16
; GFX11-NEXT:    s_lshr_b32 s12, s25, 16
; GFX11-NEXT:    s_lshr_b32 s13, s24, 16
; GFX11-NEXT:    s_lshr_b32 s14, s23, 16
; GFX11-NEXT:    s_lshr_b32 s15, s22, 16
; GFX11-NEXT:    s_lshr_b32 s40, s21, 16
; GFX11-NEXT:    s_lshr_b32 s41, s20, 16
; GFX11-NEXT:    s_lshr_b32 s42, s19, 16
; GFX11-NEXT:    s_lshr_b32 s43, s18, 16
; GFX11-NEXT:    s_lshr_b32 s44, s17, 16
; GFX11-NEXT:    s_lshr_b32 s45, s16, 16
; GFX11-NEXT:    s_lshr_b32 s46, s3, 16
; GFX11-NEXT:    s_lshr_b32 s47, s2, 16
; GFX11-NEXT:    s_lshr_b32 s56, s1, 16
; GFX11-NEXT:    s_lshr_b32 s57, s0, 16
; GFX11-NEXT:  .LBB41_3: ; %end
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_pack_ll_b32_b16 s0, s0, s57
; GFX11-NEXT:    s_pack_ll_b32_b16 s1, s1, s56
; GFX11-NEXT:    s_pack_ll_b32_b16 s2, s2, s47
; GFX11-NEXT:    s_pack_ll_b32_b16 s3, s3, s46
; GFX11-NEXT:    s_pack_ll_b32_b16 s16, s16, s45
; GFX11-NEXT:    s_pack_ll_b32_b16 s17, s17, s44
; GFX11-NEXT:    s_pack_ll_b32_b16 s18, s18, s43
; GFX11-NEXT:    s_pack_ll_b32_b16 s19, s19, s42
; GFX11-NEXT:    s_pack_ll_b32_b16 s20, s20, s41
; GFX11-NEXT:    s_pack_ll_b32_b16 s21, s21, s40
; GFX11-NEXT:    s_pack_ll_b32_b16 s15, s22, s15
; GFX11-NEXT:    s_pack_ll_b32_b16 s14, s23, s14
; GFX11-NEXT:    s_pack_ll_b32_b16 s13, s24, s13
; GFX11-NEXT:    s_pack_ll_b32_b16 s12, s25, s12
; GFX11-NEXT:    s_pack_ll_b32_b16 s11, s26, s11
; GFX11-NEXT:    s_pack_ll_b32_b16 s10, s27, s10
; GFX11-NEXT:    s_pack_ll_b32_b16 s9, s28, s9
; GFX11-NEXT:    s_pack_ll_b32_b16 s8, s29, s8
; GFX11-NEXT:    s_pack_ll_b32_b16 s5, s5, s7
; GFX11-NEXT:    s_pack_ll_b32_b16 s4, s4, s6
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s16 :: v_dual_mov_b32 v5, s17
; GFX11-NEXT:    v_dual_mov_b32 v6, s18 :: v_dual_mov_b32 v7, s19
; GFX11-NEXT:    v_dual_mov_b32 v8, s20 :: v_dual_mov_b32 v9, s21
; GFX11-NEXT:    v_dual_mov_b32 v10, s15 :: v_dual_mov_b32 v11, s14
; GFX11-NEXT:    v_dual_mov_b32 v12, s13 :: v_dual_mov_b32 v13, s12
; GFX11-NEXT:    v_dual_mov_b32 v14, s11 :: v_dual_mov_b32 v15, s10
; GFX11-NEXT:    v_dual_mov_b32 v16, s9 :: v_dual_mov_b32 v17, s8
; GFX11-NEXT:    v_dual_mov_b32 v18, s5 :: v_dual_mov_b32 v19, s4
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB41_4:
; GFX11-NEXT:    ; implicit-def: $sgpr57
; GFX11-NEXT:    ; implicit-def: $sgpr56
; GFX11-NEXT:    ; implicit-def: $sgpr47
; GFX11-NEXT:    ; implicit-def: $sgpr46
; GFX11-NEXT:    ; implicit-def: $sgpr45
; GFX11-NEXT:    ; implicit-def: $sgpr44
; GFX11-NEXT:    ; implicit-def: $sgpr43
; GFX11-NEXT:    ; implicit-def: $sgpr42
; GFX11-NEXT:    ; implicit-def: $sgpr41
; GFX11-NEXT:    ; implicit-def: $sgpr40
; GFX11-NEXT:    ; implicit-def: $sgpr15
; GFX11-NEXT:    ; implicit-def: $sgpr14
; GFX11-NEXT:    ; implicit-def: $sgpr13
; GFX11-NEXT:    ; implicit-def: $sgpr12
; GFX11-NEXT:    ; implicit-def: $sgpr11
; GFX11-NEXT:    ; implicit-def: $sgpr10
; GFX11-NEXT:    ; implicit-def: $sgpr9
; GFX11-NEXT:    ; implicit-def: $sgpr8
; GFX11-NEXT:    ; implicit-def: $sgpr7
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    s_branch .LBB41_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <10 x i64> %a, splat (i64 3)
  %a2 = bitcast <10 x i64> %a1 to <40 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <10 x i64> %a to <40 x i16>
  br label %end

end:
  %phi = phi <40 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <40 x i16> %phi
}

define <10 x i64> @bitcast_v40i16_to_v10i64(<40 x i16> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v40i16_to_v10i64:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v63, off, s[0:3], s32 ; 4-byte Folded Spill
; SI-NEXT:    v_mov_b32_e32 v32, v19
; SI-NEXT:    v_mov_b32_e32 v33, v18
; SI-NEXT:    v_mov_b32_e32 v34, v17
; SI-NEXT:    v_mov_b32_e32 v35, v16
; SI-NEXT:    v_mov_b32_e32 v36, v15
; SI-NEXT:    v_mov_b32_e32 v37, v14
; SI-NEXT:    v_mov_b32_e32 v38, v13
; SI-NEXT:    v_mov_b32_e32 v39, v12
; SI-NEXT:    v_mov_b32_e32 v48, v11
; SI-NEXT:    v_mov_b32_e32 v49, v10
; SI-NEXT:    v_mov_b32_e32 v50, v9
; SI-NEXT:    v_mov_b32_e32 v51, v8
; SI-NEXT:    v_mov_b32_e32 v52, v7
; SI-NEXT:    v_mov_b32_e32 v53, v6
; SI-NEXT:    v_mov_b32_e32 v54, v5
; SI-NEXT:    v_mov_b32_e32 v55, v4
; SI-NEXT:    v_mov_b32_e32 v40, v3
; SI-NEXT:    v_mov_b32_e32 v41, v2
; SI-NEXT:    v_mov_b32_e32 v42, v1
; SI-NEXT:    v_mov_b32_e32 v43, v0
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v32
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v33
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v34
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v35
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v36
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v37
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v38
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v39
; SI-NEXT:    v_lshrrev_b32_e32 v8, 16, v48
; SI-NEXT:    v_lshrrev_b32_e32 v9, 16, v49
; SI-NEXT:    v_lshrrev_b32_e32 v10, 16, v50
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v51
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v52
; SI-NEXT:    v_lshrrev_b32_e32 v13, 16, v53
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v54
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v55
; SI-NEXT:    v_lshrrev_b32_e32 v16, 16, v40
; SI-NEXT:    v_lshrrev_b32_e32 v17, 16, v41
; SI-NEXT:    v_lshrrev_b32_e32 v18, 16, v42
; SI-NEXT:    v_lshrrev_b32_e32 v19, 16, v43
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    s_waitcnt expcnt(4)
; SI-NEXT:    v_lshlrev_b32_e32 v59, 16, v19
; SI-NEXT:    v_lshlrev_b32_e32 v58, 16, v18
; SI-NEXT:    v_lshlrev_b32_e32 v57, 16, v17
; SI-NEXT:    v_lshlrev_b32_e32 v56, 16, v16
; SI-NEXT:    v_lshlrev_b32_e32 v47, 16, v15
; SI-NEXT:    v_lshlrev_b32_e32 v46, 16, v14
; SI-NEXT:    v_lshlrev_b32_e32 v45, 16, v13
; SI-NEXT:    v_lshlrev_b32_e32 v44, 16, v12
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshlrev_b32_e32 v63, 16, v11
; SI-NEXT:    v_lshlrev_b32_e32 v62, 16, v10
; SI-NEXT:    v_lshlrev_b32_e32 v61, 16, v9
; SI-NEXT:    v_lshlrev_b32_e32 v60, 16, v8
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:92 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:88 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:84 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:80 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:76 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:72 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:68 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:64 ; 4-byte Folded Spill
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB42_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:92 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:88 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:84 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:80 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:76 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:72 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v39
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v43
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v42
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v41
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v40
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v55
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v54
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v53
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v52
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v51
; SI-NEXT:    v_and_b32_e32 v9, 0xffff, v50
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v49
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v48
; SI-NEXT:    v_or_b32_e32 v0, v0, v59
; SI-NEXT:    v_or_b32_e32 v1, v1, v58
; SI-NEXT:    v_or_b32_e32 v2, v2, v57
; SI-NEXT:    v_or_b32_e32 v3, v3, v56
; SI-NEXT:    v_or_b32_e32 v4, v4, v47
; SI-NEXT:    v_or_b32_e32 v5, v5, v46
; SI-NEXT:    v_or_b32_e32 v6, v6, v45
; SI-NEXT:    v_or_b32_e32 v7, v7, v44
; SI-NEXT:    v_or_b32_e32 v8, v8, v63
; SI-NEXT:    v_or_b32_e32 v9, v9, v62
; SI-NEXT:    v_or_b32_e32 v10, v10, v61
; SI-NEXT:    v_or_b32_e32 v11, v11, v60
; SI-NEXT:    ; implicit-def: $vgpr43
; SI-NEXT:    ; implicit-def: $vgpr42
; SI-NEXT:    ; implicit-def: $vgpr41
; SI-NEXT:    ; implicit-def: $vgpr40
; SI-NEXT:    ; implicit-def: $vgpr55
; SI-NEXT:    ; implicit-def: $vgpr54
; SI-NEXT:    ; implicit-def: $vgpr53
; SI-NEXT:    ; implicit-def: $vgpr52
; SI-NEXT:    ; implicit-def: $vgpr51
; SI-NEXT:    ; implicit-def: $vgpr50
; SI-NEXT:    ; implicit-def: $vgpr49
; SI-NEXT:    ; implicit-def: $vgpr48
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:    ; implicit-def: $vgpr59
; SI-NEXT:    ; implicit-def: $vgpr58
; SI-NEXT:    ; implicit-def: $vgpr57
; SI-NEXT:    ; implicit-def: $vgpr56
; SI-NEXT:    ; implicit-def: $vgpr47
; SI-NEXT:    ; implicit-def: $vgpr46
; SI-NEXT:    ; implicit-def: $vgpr45
; SI-NEXT:    ; implicit-def: $vgpr44
; SI-NEXT:    ; implicit-def: $vgpr63
; SI-NEXT:    ; implicit-def: $vgpr62
; SI-NEXT:    ; implicit-def: $vgpr61
; SI-NEXT:    ; implicit-def: $vgpr60
; SI-NEXT:    s_waitcnt vmcnt(7)
; SI-NEXT:    v_or_b32_e32 v12, v12, v13
; SI-NEXT:    v_and_b32_e32 v13, 0xffff, v38
; SI-NEXT:    s_waitcnt vmcnt(6)
; SI-NEXT:    v_or_b32_e32 v13, v13, v14
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v37
; SI-NEXT:    s_waitcnt vmcnt(5)
; SI-NEXT:    v_or_b32_e32 v14, v14, v15
; SI-NEXT:    v_and_b32_e32 v15, 0xffff, v36
; SI-NEXT:    s_waitcnt vmcnt(4)
; SI-NEXT:    v_or_b32_e32 v15, v15, v16
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v35
; SI-NEXT:    s_waitcnt vmcnt(3)
; SI-NEXT:    v_or_b32_e32 v16, v16, v17
; SI-NEXT:    v_and_b32_e32 v17, 0xffff, v34
; SI-NEXT:    s_waitcnt vmcnt(2)
; SI-NEXT:    v_or_b32_e32 v17, v17, v18
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v33
; SI-NEXT:    s_waitcnt vmcnt(1)
; SI-NEXT:    v_or_b32_e32 v18, v18, v19
; SI-NEXT:    v_and_b32_e32 v19, 0xffff, v32
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_or_b32_e32 v19, v19, v20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:  .LBB42_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB42_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:92 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:88 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:84 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:80 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:76 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:72 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; SI-NEXT:    v_add_i32_e32 v12, vcc, 3, v39
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v43
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v42
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v41
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v40
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v55
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v54
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v53
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v52
; SI-NEXT:    v_add_i32_e32 v8, vcc, 3, v51
; SI-NEXT:    v_add_i32_e32 v9, vcc, 3, v50
; SI-NEXT:    v_add_i32_e32 v10, vcc, 3, v49
; SI-NEXT:    v_add_i32_e32 v11, vcc, 3, v48
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; SI-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; SI-NEXT:    v_or_b32_e32 v0, v59, v0
; SI-NEXT:    s_mov_b32 s6, 0x30000
; SI-NEXT:    v_or_b32_e32 v1, v58, v1
; SI-NEXT:    v_or_b32_e32 v2, v57, v2
; SI-NEXT:    v_or_b32_e32 v3, v56, v3
; SI-NEXT:    v_or_b32_e32 v4, v47, v4
; SI-NEXT:    v_or_b32_e32 v5, v46, v5
; SI-NEXT:    v_or_b32_e32 v6, v45, v6
; SI-NEXT:    v_or_b32_e32 v7, v44, v7
; SI-NEXT:    v_or_b32_e32 v8, v63, v8
; SI-NEXT:    v_or_b32_e32 v9, v62, v9
; SI-NEXT:    v_or_b32_e32 v10, v61, v10
; SI-NEXT:    v_or_b32_e32 v11, v60, v11
; SI-NEXT:    v_add_i32_e32 v0, vcc, 0x30000, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, s6, v1
; SI-NEXT:    v_add_i32_e32 v2, vcc, s6, v2
; SI-NEXT:    v_add_i32_e32 v3, vcc, s6, v3
; SI-NEXT:    v_add_i32_e32 v4, vcc, s6, v4
; SI-NEXT:    v_add_i32_e32 v5, vcc, s6, v5
; SI-NEXT:    v_add_i32_e32 v6, vcc, s6, v6
; SI-NEXT:    v_add_i32_e32 v7, vcc, s6, v7
; SI-NEXT:    v_add_i32_e32 v8, vcc, s6, v8
; SI-NEXT:    v_add_i32_e32 v9, vcc, s6, v9
; SI-NEXT:    s_waitcnt vmcnt(7)
; SI-NEXT:    v_or_b32_e32 v12, v13, v12
; SI-NEXT:    v_add_i32_e32 v13, vcc, 3, v38
; SI-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; SI-NEXT:    s_waitcnt vmcnt(6)
; SI-NEXT:    v_or_b32_e32 v13, v14, v13
; SI-NEXT:    v_add_i32_e32 v14, vcc, 3, v37
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; SI-NEXT:    s_waitcnt vmcnt(5)
; SI-NEXT:    v_or_b32_e32 v14, v15, v14
; SI-NEXT:    v_add_i32_e32 v15, vcc, 3, v36
; SI-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; SI-NEXT:    s_waitcnt vmcnt(4)
; SI-NEXT:    v_or_b32_e32 v15, v16, v15
; SI-NEXT:    v_add_i32_e32 v16, vcc, 3, v35
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v16
; SI-NEXT:    s_waitcnt vmcnt(3)
; SI-NEXT:    v_or_b32_e32 v16, v17, v16
; SI-NEXT:    v_add_i32_e32 v17, vcc, 3, v34
; SI-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; SI-NEXT:    s_waitcnt vmcnt(2)
; SI-NEXT:    v_or_b32_e32 v17, v18, v17
; SI-NEXT:    v_add_i32_e32 v18, vcc, 3, v33
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; SI-NEXT:    s_waitcnt vmcnt(1)
; SI-NEXT:    v_or_b32_e32 v18, v19, v18
; SI-NEXT:    v_add_i32_e32 v19, vcc, 3, v32
; SI-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_or_b32_e32 v19, v20, v19
; SI-NEXT:    v_add_i32_e32 v10, vcc, s6, v10
; SI-NEXT:    v_add_i32_e32 v11, vcc, s6, v11
; SI-NEXT:    v_add_i32_e32 v12, vcc, s6, v12
; SI-NEXT:    v_add_i32_e32 v13, vcc, s6, v13
; SI-NEXT:    v_add_i32_e32 v14, vcc, s6, v14
; SI-NEXT:    v_add_i32_e32 v15, vcc, s6, v15
; SI-NEXT:    v_add_i32_e32 v16, vcc, s6, v16
; SI-NEXT:    v_add_i32_e32 v17, vcc, s6, v17
; SI-NEXT:    v_add_i32_e32 v18, vcc, s6, v18
; SI-NEXT:    v_add_i32_e32 v19, vcc, 0x30000, v19
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:  .LBB42_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    buffer_load_dword v63, off, s[0:3], s32 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0)
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v40i16_to_v10i64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; VI-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; VI-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; VI-NEXT:    buffer_store_dword v43, off, s[0:3], s32 ; 4-byte Folded Spill
; VI-NEXT:    v_mov_b32_e32 v32, v19
; VI-NEXT:    v_mov_b32_e32 v33, v18
; VI-NEXT:    v_mov_b32_e32 v34, v17
; VI-NEXT:    v_mov_b32_e32 v35, v16
; VI-NEXT:    v_mov_b32_e32 v36, v15
; VI-NEXT:    v_mov_b32_e32 v37, v14
; VI-NEXT:    v_mov_b32_e32 v38, v13
; VI-NEXT:    v_mov_b32_e32 v39, v12
; VI-NEXT:    v_mov_b32_e32 v48, v11
; VI-NEXT:    v_mov_b32_e32 v49, v10
; VI-NEXT:    v_mov_b32_e32 v50, v9
; VI-NEXT:    v_mov_b32_e32 v51, v8
; VI-NEXT:    v_mov_b32_e32 v52, v7
; VI-NEXT:    v_mov_b32_e32 v53, v6
; VI-NEXT:    v_mov_b32_e32 v54, v5
; VI-NEXT:    v_mov_b32_e32 v55, v4
; VI-NEXT:    v_mov_b32_e32 v40, v3
; VI-NEXT:    v_mov_b32_e32 v41, v2
; VI-NEXT:    v_mov_b32_e32 v42, v1
; VI-NEXT:    v_mov_b32_e32 v43, v0
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB42_2
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_mov_b32_e32 v19, 16
; VI-NEXT:    v_lshlrev_b32_sdwa v0, v19, v43 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v1, v19, v42 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v2, v19, v41 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v3, v19, v40 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v4, v19, v55 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v5, v19, v54 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v6, v19, v53 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v7, v19, v52 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v8, v19, v51 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v9, v19, v50 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v10, v19, v49 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v11, v19, v48 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v12, v19, v39 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v13, v19, v38 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v14, v19, v37 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v15, v19, v36 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v16, v19, v35 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v17, v19, v34 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v18, v19, v33 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v19, v19, v32 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_or_b32_sdwa v0, v43, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v1, v42, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v2, v41, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v3, v40, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v4, v55, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v5, v54, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v6, v53, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v7, v52, v7 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v8, v51, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v9, v50, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v10, v49, v10 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v11, v48, v11 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v12, v39, v12 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v13, v38, v13 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v14, v37, v14 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v15, v36, v15 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v16, v35, v16 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v17, v34, v17 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v18, v33, v18 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v19, v32, v19 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr43
; VI-NEXT:    ; implicit-def: $vgpr42
; VI-NEXT:    ; implicit-def: $vgpr41
; VI-NEXT:    ; implicit-def: $vgpr40
; VI-NEXT:    ; implicit-def: $vgpr55
; VI-NEXT:    ; implicit-def: $vgpr54
; VI-NEXT:    ; implicit-def: $vgpr53
; VI-NEXT:    ; implicit-def: $vgpr52
; VI-NEXT:    ; implicit-def: $vgpr51
; VI-NEXT:    ; implicit-def: $vgpr50
; VI-NEXT:    ; implicit-def: $vgpr49
; VI-NEXT:    ; implicit-def: $vgpr48
; VI-NEXT:    ; implicit-def: $vgpr39
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr35
; VI-NEXT:    ; implicit-def: $vgpr34
; VI-NEXT:    ; implicit-def: $vgpr33
; VI-NEXT:    ; implicit-def: $vgpr32
; VI-NEXT:  .LBB42_2: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB42_4
; VI-NEXT:  ; %bb.3: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v19, 3
; VI-NEXT:    v_add_u16_e32 v0, 3, v43
; VI-NEXT:    v_add_u16_sdwa v1, v43, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v0, v0, v1
; VI-NEXT:    v_add_u16_e32 v1, 3, v42
; VI-NEXT:    v_add_u16_sdwa v2, v42, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v1, v1, v2
; VI-NEXT:    v_add_u16_e32 v2, 3, v41
; VI-NEXT:    v_add_u16_sdwa v3, v41, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v2, v2, v3
; VI-NEXT:    v_add_u16_e32 v3, 3, v40
; VI-NEXT:    v_add_u16_sdwa v4, v40, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v3, v3, v4
; VI-NEXT:    v_add_u16_e32 v4, 3, v55
; VI-NEXT:    v_add_u16_sdwa v5, v55, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v4, v4, v5
; VI-NEXT:    v_add_u16_e32 v5, 3, v54
; VI-NEXT:    v_add_u16_sdwa v6, v54, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v5, v5, v6
; VI-NEXT:    v_add_u16_e32 v6, 3, v53
; VI-NEXT:    v_add_u16_sdwa v7, v53, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v6, v6, v7
; VI-NEXT:    v_add_u16_e32 v7, 3, v52
; VI-NEXT:    v_add_u16_sdwa v8, v52, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v7, v7, v8
; VI-NEXT:    v_add_u16_e32 v8, 3, v51
; VI-NEXT:    v_add_u16_sdwa v9, v51, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v8, v8, v9
; VI-NEXT:    v_add_u16_e32 v9, 3, v50
; VI-NEXT:    v_add_u16_sdwa v10, v50, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v9, v9, v10
; VI-NEXT:    v_add_u16_e32 v10, 3, v49
; VI-NEXT:    v_add_u16_sdwa v11, v49, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v10, v10, v11
; VI-NEXT:    v_add_u16_e32 v11, 3, v48
; VI-NEXT:    v_add_u16_sdwa v12, v48, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v11, v11, v12
; VI-NEXT:    v_add_u16_e32 v12, 3, v39
; VI-NEXT:    v_add_u16_sdwa v13, v39, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v12, v12, v13
; VI-NEXT:    v_add_u16_e32 v13, 3, v38
; VI-NEXT:    v_add_u16_sdwa v14, v38, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v13, v13, v14
; VI-NEXT:    v_add_u16_e32 v14, 3, v37
; VI-NEXT:    v_add_u16_sdwa v15, v37, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v14, v14, v15
; VI-NEXT:    v_add_u16_e32 v15, 3, v36
; VI-NEXT:    v_add_u16_sdwa v16, v36, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v15, v15, v16
; VI-NEXT:    v_add_u16_e32 v16, 3, v35
; VI-NEXT:    v_add_u16_sdwa v17, v35, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v16, v16, v17
; VI-NEXT:    v_add_u16_e32 v17, 3, v34
; VI-NEXT:    v_add_u16_sdwa v18, v34, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v17, v17, v18
; VI-NEXT:    v_add_u16_e32 v18, 3, v33
; VI-NEXT:    v_add_u16_sdwa v20, v33, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v18, v18, v20
; VI-NEXT:    v_add_u16_e32 v20, 3, v32
; VI-NEXT:    v_add_u16_sdwa v19, v32, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v19, v20, v19
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:  .LBB42_4: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    buffer_load_dword v43, off, s[0:3], s32 ; 4-byte Folded Reload
; VI-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; VI-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; VI-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v40i16_to_v10i64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v63, off, s[0:3], s32 ; 4-byte Folded Spill
; GFX9-NEXT:    v_mov_b32_e32 v32, v19
; GFX9-NEXT:    v_mov_b32_e32 v33, v18
; GFX9-NEXT:    v_mov_b32_e32 v43, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v32
; GFX9-NEXT:    v_mov_b32_e32 v34, v17
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:64 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v33
; GFX9-NEXT:    v_mov_b32_e32 v35, v16
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:68 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v34
; GFX9-NEXT:    v_mov_b32_e32 v36, v15
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:72 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v35
; GFX9-NEXT:    v_mov_b32_e32 v37, v14
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:76 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v36
; GFX9-NEXT:    v_mov_b32_e32 v38, v13
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:80 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v37
; GFX9-NEXT:    v_mov_b32_e32 v39, v12
; GFX9-NEXT:    v_mov_b32_e32 v48, v11
; GFX9-NEXT:    v_mov_b32_e32 v49, v10
; GFX9-NEXT:    v_mov_b32_e32 v50, v9
; GFX9-NEXT:    v_mov_b32_e32 v51, v8
; GFX9-NEXT:    v_mov_b32_e32 v52, v7
; GFX9-NEXT:    v_mov_b32_e32 v53, v6
; GFX9-NEXT:    v_mov_b32_e32 v54, v5
; GFX9-NEXT:    v_mov_b32_e32 v55, v4
; GFX9-NEXT:    v_mov_b32_e32 v40, v3
; GFX9-NEXT:    v_mov_b32_e32 v41, v2
; GFX9-NEXT:    v_mov_b32_e32 v42, v1
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:84 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v38
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:88 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v39
; GFX9-NEXT:    v_lshrrev_b32_e32 v60, 16, v48
; GFX9-NEXT:    v_lshrrev_b32_e32 v61, 16, v49
; GFX9-NEXT:    v_lshrrev_b32_e32 v62, 16, v50
; GFX9-NEXT:    v_lshrrev_b32_e32 v63, 16, v51
; GFX9-NEXT:    v_lshrrev_b32_e32 v44, 16, v52
; GFX9-NEXT:    v_lshrrev_b32_e32 v45, 16, v53
; GFX9-NEXT:    v_lshrrev_b32_e32 v46, 16, v54
; GFX9-NEXT:    v_lshrrev_b32_e32 v47, 16, v55
; GFX9-NEXT:    v_lshrrev_b32_e32 v56, 16, v40
; GFX9-NEXT:    v_lshrrev_b32_e32 v57, 16, v41
; GFX9-NEXT:    v_lshrrev_b32_e32 v58, 16, v42
; GFX9-NEXT:    v_lshrrev_b32_e32 v59, 16, v43
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:92 ; 4-byte Folded Spill
; GFX9-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB42_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_mov_b32 s6, 0x5040100
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v12, 16, v39
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v13, 16, v38
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v14, 16, v37
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v15, 16, v36
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v16, 16, v35
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v17, 16, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v18, 16, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v19, 16, v32
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    v_perm_b32 v0, v59, v43, s6
; GFX9-NEXT:    v_perm_b32 v1, v58, v42, s6
; GFX9-NEXT:    v_perm_b32 v2, v57, v41, s6
; GFX9-NEXT:    v_perm_b32 v3, v56, v40, s6
; GFX9-NEXT:    v_perm_b32 v4, v47, v55, s6
; GFX9-NEXT:    v_perm_b32 v5, v46, v54, s6
; GFX9-NEXT:    v_perm_b32 v6, v45, v53, s6
; GFX9-NEXT:    v_perm_b32 v7, v44, v52, s6
; GFX9-NEXT:    v_perm_b32 v8, v63, v51, s6
; GFX9-NEXT:    v_perm_b32 v9, v62, v50, s6
; GFX9-NEXT:    v_perm_b32 v10, v61, v49, s6
; GFX9-NEXT:    v_perm_b32 v11, v60, v48, s6
; GFX9-NEXT:    v_perm_b32 v12, v12, v39, s6
; GFX9-NEXT:    v_perm_b32 v13, v13, v38, s6
; GFX9-NEXT:    v_perm_b32 v14, v14, v37, s6
; GFX9-NEXT:    v_perm_b32 v15, v15, v36, s6
; GFX9-NEXT:    v_perm_b32 v16, v16, v35, s6
; GFX9-NEXT:    v_perm_b32 v17, v17, v34, s6
; GFX9-NEXT:    v_perm_b32 v18, v18, v33, s6
; GFX9-NEXT:    v_perm_b32 v19, v19, v32, s6
; GFX9-NEXT:    ; implicit-def: $vgpr43
; GFX9-NEXT:    ; implicit-def: $vgpr42
; GFX9-NEXT:    ; implicit-def: $vgpr41
; GFX9-NEXT:    ; implicit-def: $vgpr40
; GFX9-NEXT:    ; implicit-def: $vgpr55
; GFX9-NEXT:    ; implicit-def: $vgpr54
; GFX9-NEXT:    ; implicit-def: $vgpr53
; GFX9-NEXT:    ; implicit-def: $vgpr52
; GFX9-NEXT:    ; implicit-def: $vgpr51
; GFX9-NEXT:    ; implicit-def: $vgpr50
; GFX9-NEXT:    ; implicit-def: $vgpr49
; GFX9-NEXT:    ; implicit-def: $vgpr48
; GFX9-NEXT:    ; implicit-def: $vgpr39
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr35
; GFX9-NEXT:    ; implicit-def: $vgpr34
; GFX9-NEXT:    ; implicit-def: $vgpr33
; GFX9-NEXT:    ; implicit-def: $vgpr32
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr60
; GFX9-NEXT:    ; implicit-def: $vgpr61
; GFX9-NEXT:    ; implicit-def: $vgpr62
; GFX9-NEXT:    ; implicit-def: $vgpr63
; GFX9-NEXT:    ; implicit-def: $vgpr44
; GFX9-NEXT:    ; implicit-def: $vgpr45
; GFX9-NEXT:    ; implicit-def: $vgpr46
; GFX9-NEXT:    ; implicit-def: $vgpr47
; GFX9-NEXT:    ; implicit-def: $vgpr56
; GFX9-NEXT:    ; implicit-def: $vgpr57
; GFX9-NEXT:    ; implicit-def: $vgpr58
; GFX9-NEXT:    ; implicit-def: $vgpr59
; GFX9-NEXT:  .LBB42_2: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB42_4
; GFX9-NEXT:  ; %bb.3: ; %cmp.true
; GFX9-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:92 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:88 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:84 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:80 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:76 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:72 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; GFX9-NEXT:    s_mov_b32 s6, 0x5040100
; GFX9-NEXT:    v_perm_b32 v0, v59, v43, s6
; GFX9-NEXT:    v_perm_b32 v1, v58, v42, s6
; GFX9-NEXT:    v_perm_b32 v2, v57, v41, s6
; GFX9-NEXT:    v_perm_b32 v3, v56, v40, s6
; GFX9-NEXT:    v_perm_b32 v4, v47, v55, s6
; GFX9-NEXT:    v_perm_b32 v5, v46, v54, s6
; GFX9-NEXT:    v_perm_b32 v6, v45, v53, s6
; GFX9-NEXT:    v_perm_b32 v7, v44, v52, s6
; GFX9-NEXT:    v_perm_b32 v8, v63, v51, s6
; GFX9-NEXT:    v_perm_b32 v9, v62, v50, s6
; GFX9-NEXT:    v_perm_b32 v10, v61, v49, s6
; GFX9-NEXT:    v_perm_b32 v11, v60, v48, s6
; GFX9-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v8, v8, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v9, v9, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_waitcnt vmcnt(7)
; GFX9-NEXT:    v_perm_b32 v12, v12, v39, s6
; GFX9-NEXT:    s_waitcnt vmcnt(6)
; GFX9-NEXT:    v_perm_b32 v13, v13, v38, s6
; GFX9-NEXT:    s_waitcnt vmcnt(5)
; GFX9-NEXT:    v_perm_b32 v14, v14, v37, s6
; GFX9-NEXT:    s_waitcnt vmcnt(4)
; GFX9-NEXT:    v_perm_b32 v15, v15, v36, s6
; GFX9-NEXT:    s_waitcnt vmcnt(3)
; GFX9-NEXT:    v_perm_b32 v16, v16, v35, s6
; GFX9-NEXT:    s_waitcnt vmcnt(2)
; GFX9-NEXT:    v_perm_b32 v17, v17, v34, s6
; GFX9-NEXT:    s_waitcnt vmcnt(1)
; GFX9-NEXT:    v_perm_b32 v18, v18, v33, s6
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    v_perm_b32 v19, v19, v32, s6
; GFX9-NEXT:    v_pk_add_u16 v12, v12, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v13, v13, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v14, v14, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v15, v15, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v16, v16, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v17, v17, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v18, v18, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v19, v19, 3 op_sel_hi:[1,0]
; GFX9-NEXT:  .LBB42_4: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    buffer_load_dword v63, off, s[0:3], s32 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Reload
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v40i16_to_v10i64:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB42_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB42_4
; GFX11-TRUE16-NEXT:  .LBB42_2: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB42_3: ; %cmp.false
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB42_2
; GFX11-TRUE16-NEXT:  .LBB42_4: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v8, v8, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v9, v9, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v12, v12, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v13, v13, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v14, v14, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v15, v15, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v16, v16, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v17, v17, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v18, v18, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v19, v19, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v40i16_to_v10i64:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v48, 16, v3
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v20
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v37, v0, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v38, v1, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v39, v2, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v48, v3, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v36, v4, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v35, v5, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v34, v6, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v33, v7, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, v32, v8, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, v31, v9, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, v30, v10, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, v29, v11, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, v28, v12, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, v27, v13, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v14, v26, v14, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v15, v25, v15, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v16, v24, v16, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v17, v23, v17, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v18, v22, v18, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v19, v21, v19, 0x5040100
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB42_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB42_4
; GFX11-FAKE16-NEXT:  .LBB42_2: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB42_3: ; %cmp.false
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB42_2
; GFX11-FAKE16-NEXT:  .LBB42_4: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v8, v8, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v9, v9, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v12, v12, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v13, v13, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v14, v14, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v15, v15, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v16, v16, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v17, v17, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v18, v18, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v19, v19, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <40 x i16> %a, splat (i16 3)
  %a2 = bitcast <40 x i16> %a1 to <10 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <40 x i16> %a to <10 x i64>
  br label %end

end:
  %phi = phi <10 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <10 x i64> %phi
}

define inreg <10 x i64> @bitcast_v40i16_to_v10i64_scalar(<40 x i16> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v40i16_to_v10i64_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_store_dword v20, off, s[0:3], s32 ; 4-byte Folded Spill
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_writelane_b32 v20, s36, 0
; SI-NEXT:    v_writelane_b32 v20, s37, 1
; SI-NEXT:    v_writelane_b32 v20, s38, 2
; SI-NEXT:    v_writelane_b32 v20, s39, 3
; SI-NEXT:    v_writelane_b32 v20, s48, 4
; SI-NEXT:    v_writelane_b32 v20, s49, 5
; SI-NEXT:    v_writelane_b32 v20, s50, 6
; SI-NEXT:    v_writelane_b32 v20, s51, 7
; SI-NEXT:    v_writelane_b32 v20, s52, 8
; SI-NEXT:    v_writelane_b32 v20, s53, 9
; SI-NEXT:    v_writelane_b32 v20, s54, 10
; SI-NEXT:    v_writelane_b32 v20, s55, 11
; SI-NEXT:    v_writelane_b32 v20, s64, 12
; SI-NEXT:    v_writelane_b32 v20, s65, 13
; SI-NEXT:    v_writelane_b32 v20, s66, 14
; SI-NEXT:    v_writelane_b32 v20, s67, 15
; SI-NEXT:    v_readfirstlane_b32 s7, v5
; SI-NEXT:    v_readfirstlane_b32 s9, v4
; SI-NEXT:    v_readfirstlane_b32 s12, v3
; SI-NEXT:    v_readfirstlane_b32 s15, v2
; SI-NEXT:    v_readfirstlane_b32 s74, v1
; SI-NEXT:    v_readfirstlane_b32 s77, v0
; SI-NEXT:    s_lshr_b32 s11, s29, 16
; SI-NEXT:    s_lshr_b32 s13, s28, 16
; SI-NEXT:    s_lshr_b32 s72, s27, 16
; SI-NEXT:    s_lshr_b32 s75, s26, 16
; SI-NEXT:    s_lshr_b32 s78, s25, 16
; SI-NEXT:    s_lshr_b32 s79, s24, 16
; SI-NEXT:    s_lshr_b32 s88, s23, 16
; SI-NEXT:    s_lshr_b32 s89, s22, 16
; SI-NEXT:    s_lshr_b32 s90, s21, 16
; SI-NEXT:    s_lshr_b32 s91, s20, 16
; SI-NEXT:    s_lshr_b32 s92, s19, 16
; SI-NEXT:    s_lshr_b32 s93, s18, 16
; SI-NEXT:    s_lshr_b32 s94, s17, 16
; SI-NEXT:    s_lshr_b32 s95, s16, 16
; SI-NEXT:    s_lshr_b32 s6, s7, 16
; SI-NEXT:    s_lshr_b32 s8, s9, 16
; SI-NEXT:    s_lshr_b32 s10, s12, 16
; SI-NEXT:    s_lshr_b32 s14, s15, 16
; SI-NEXT:    s_lshr_b32 s73, s74, 16
; SI-NEXT:    s_lshr_b32 s76, s77, 16
; SI-NEXT:    v_readfirstlane_b32 s4, v6
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    s_cbranch_scc0 .LBB43_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s95, 16
; SI-NEXT:    s_or_b32 s36, s4, s5
; SI-NEXT:    s_and_b32 s4, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s94, 16
; SI-NEXT:    s_or_b32 s37, s4, s5
; SI-NEXT:    s_and_b32 s4, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s93, 16
; SI-NEXT:    s_or_b32 s38, s4, s5
; SI-NEXT:    s_and_b32 s4, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s92, 16
; SI-NEXT:    s_or_b32 s39, s4, s5
; SI-NEXT:    s_and_b32 s4, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s91, 16
; SI-NEXT:    s_or_b32 s40, s4, s5
; SI-NEXT:    s_and_b32 s4, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s90, 16
; SI-NEXT:    s_or_b32 s41, s4, s5
; SI-NEXT:    s_and_b32 s4, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s89, 16
; SI-NEXT:    s_or_b32 s42, s4, s5
; SI-NEXT:    s_and_b32 s4, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s88, 16
; SI-NEXT:    s_or_b32 s43, s4, s5
; SI-NEXT:    s_and_b32 s4, s24, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s79, 16
; SI-NEXT:    s_or_b32 s44, s4, s5
; SI-NEXT:    s_and_b32 s4, s25, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s78, 16
; SI-NEXT:    s_or_b32 s45, s4, s5
; SI-NEXT:    s_and_b32 s4, s26, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s75, 16
; SI-NEXT:    s_or_b32 s46, s4, s5
; SI-NEXT:    s_and_b32 s4, s27, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s72, 16
; SI-NEXT:    s_or_b32 s47, s4, s5
; SI-NEXT:    s_and_b32 s4, s28, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s13, 16
; SI-NEXT:    s_or_b32 s48, s4, s5
; SI-NEXT:    s_and_b32 s4, s29, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s11, 16
; SI-NEXT:    s_or_b32 s49, s4, s5
; SI-NEXT:    s_and_b32 s4, s77, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s76, 16
; SI-NEXT:    s_or_b32 s50, s4, s5
; SI-NEXT:    s_and_b32 s4, s74, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s73, 16
; SI-NEXT:    s_or_b32 s51, s4, s5
; SI-NEXT:    s_and_b32 s4, s15, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s14, 16
; SI-NEXT:    s_or_b32 s52, s4, s5
; SI-NEXT:    s_and_b32 s4, s12, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s10, 16
; SI-NEXT:    s_or_b32 s53, s4, s5
; SI-NEXT:    s_and_b32 s4, s9, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s8, 16
; SI-NEXT:    s_or_b32 s54, s4, s5
; SI-NEXT:    s_and_b32 s4, s7, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s6, 16
; SI-NEXT:    s_or_b32 s55, s4, s5
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    s_cbranch_execnz .LBB43_3
; SI-NEXT:  .LBB43_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s95, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s17, s17, 3
; SI-NEXT:    s_add_i32 s36, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s94, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_add_i32 s37, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s93, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s19, s19, 3
; SI-NEXT:    s_add_i32 s38, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s92, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_add_i32 s39, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s91, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s21, s21, 3
; SI-NEXT:    s_add_i32 s40, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s90, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_add_i32 s41, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s89, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s23, s23, 3
; SI-NEXT:    s_add_i32 s42, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s88, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s24, s24, 3
; SI-NEXT:    s_add_i32 s43, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s24, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s79, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s25, s25, 3
; SI-NEXT:    s_add_i32 s44, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s25, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s78, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s26, s26, 3
; SI-NEXT:    s_add_i32 s45, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s26, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s75, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s27, s27, 3
; SI-NEXT:    s_add_i32 s46, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s27, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s72, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s28, s28, 3
; SI-NEXT:    s_add_i32 s47, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s28, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s13, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s29, s29, 3
; SI-NEXT:    s_add_i32 s48, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s29, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s11, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s77, s77, 3
; SI-NEXT:    s_add_i32 s49, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s77, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s76, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s74, s74, 3
; SI-NEXT:    s_add_i32 s50, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s74, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s73, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s15, s15, 3
; SI-NEXT:    s_add_i32 s51, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s15, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s14, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s12, s12, 3
; SI-NEXT:    s_add_i32 s52, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s12, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s10, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s9, s9, 3
; SI-NEXT:    s_add_i32 s53, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s9, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s8, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s7, s7, 3
; SI-NEXT:    s_add_i32 s54, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s7, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s6, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s55, s4, 0x30000
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:  .LBB43_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v0, s36
; SI-NEXT:    v_mov_b32_e32 v1, s37
; SI-NEXT:    v_mov_b32_e32 v2, s38
; SI-NEXT:    v_mov_b32_e32 v3, s39
; SI-NEXT:    v_mov_b32_e32 v4, s40
; SI-NEXT:    v_mov_b32_e32 v5, s41
; SI-NEXT:    v_mov_b32_e32 v6, s42
; SI-NEXT:    v_mov_b32_e32 v7, s43
; SI-NEXT:    v_mov_b32_e32 v8, s44
; SI-NEXT:    v_mov_b32_e32 v9, s45
; SI-NEXT:    v_mov_b32_e32 v10, s46
; SI-NEXT:    v_mov_b32_e32 v11, s47
; SI-NEXT:    v_mov_b32_e32 v12, s48
; SI-NEXT:    v_mov_b32_e32 v13, s49
; SI-NEXT:    v_mov_b32_e32 v14, s50
; SI-NEXT:    v_mov_b32_e32 v15, s51
; SI-NEXT:    v_mov_b32_e32 v16, s52
; SI-NEXT:    v_mov_b32_e32 v17, s53
; SI-NEXT:    v_mov_b32_e32 v18, s54
; SI-NEXT:    v_mov_b32_e32 v19, s55
; SI-NEXT:    v_readlane_b32 s67, v20, 15
; SI-NEXT:    v_readlane_b32 s66, v20, 14
; SI-NEXT:    v_readlane_b32 s65, v20, 13
; SI-NEXT:    v_readlane_b32 s64, v20, 12
; SI-NEXT:    v_readlane_b32 s55, v20, 11
; SI-NEXT:    v_readlane_b32 s54, v20, 10
; SI-NEXT:    v_readlane_b32 s53, v20, 9
; SI-NEXT:    v_readlane_b32 s52, v20, 8
; SI-NEXT:    v_readlane_b32 s51, v20, 7
; SI-NEXT:    v_readlane_b32 s50, v20, 6
; SI-NEXT:    v_readlane_b32 s49, v20, 5
; SI-NEXT:    v_readlane_b32 s48, v20, 4
; SI-NEXT:    v_readlane_b32 s39, v20, 3
; SI-NEXT:    v_readlane_b32 s38, v20, 2
; SI-NEXT:    v_readlane_b32 s37, v20, 1
; SI-NEXT:    v_readlane_b32 s36, v20, 0
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_load_dword v20, off, s[0:3], s32 ; 4-byte Folded Reload
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB43_4:
; SI-NEXT:    ; implicit-def: $sgpr36_sgpr37_sgpr38_sgpr39_sgpr40_sgpr41_sgpr42_sgpr43_sgpr44_sgpr45_sgpr46_sgpr47_sgpr48_sgpr49_sgpr50_sgpr51_sgpr52_sgpr53_sgpr54_sgpr55_sgpr56_sgpr57_sgpr58_sgpr59_sgpr60_sgpr61_sgpr62_sgpr63_sgpr64_sgpr65_sgpr66_sgpr67
; SI-NEXT:    s_branch .LBB43_2
;
; VI-LABEL: bitcast_v40i16_to_v10i64_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_store_dword v20, off, s[0:3], s32 ; 4-byte Folded Spill
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    v_writelane_b32 v20, s34, 0
; VI-NEXT:    v_writelane_b32 v20, s35, 1
; VI-NEXT:    v_writelane_b32 v20, s36, 2
; VI-NEXT:    v_writelane_b32 v20, s37, 3
; VI-NEXT:    v_writelane_b32 v20, s38, 4
; VI-NEXT:    v_writelane_b32 v20, s39, 5
; VI-NEXT:    v_writelane_b32 v20, s48, 6
; VI-NEXT:    v_writelane_b32 v20, s49, 7
; VI-NEXT:    v_writelane_b32 v20, s50, 8
; VI-NEXT:    v_writelane_b32 v20, s51, 9
; VI-NEXT:    v_writelane_b32 v20, s52, 10
; VI-NEXT:    v_writelane_b32 v20, s53, 11
; VI-NEXT:    v_writelane_b32 v20, s54, 12
; VI-NEXT:    v_writelane_b32 v20, s55, 13
; VI-NEXT:    v_writelane_b32 v20, s64, 14
; VI-NEXT:    v_writelane_b32 v20, s65, 15
; VI-NEXT:    v_writelane_b32 v20, s66, 16
; VI-NEXT:    v_writelane_b32 v20, s67, 17
; VI-NEXT:    v_writelane_b32 v20, s30, 18
; VI-NEXT:    v_writelane_b32 v20, s31, 19
; VI-NEXT:    v_readfirstlane_b32 s7, v5
; VI-NEXT:    v_readfirstlane_b32 s9, v4
; VI-NEXT:    v_readfirstlane_b32 s12, v3
; VI-NEXT:    v_readfirstlane_b32 s15, v2
; VI-NEXT:    v_readfirstlane_b32 s74, v1
; VI-NEXT:    v_readfirstlane_b32 s77, v0
; VI-NEXT:    s_lshr_b32 s11, s29, 16
; VI-NEXT:    s_lshr_b32 s13, s28, 16
; VI-NEXT:    s_lshr_b32 s72, s27, 16
; VI-NEXT:    s_lshr_b32 s75, s26, 16
; VI-NEXT:    s_lshr_b32 s78, s25, 16
; VI-NEXT:    s_lshr_b32 s79, s24, 16
; VI-NEXT:    s_lshr_b32 s88, s23, 16
; VI-NEXT:    s_lshr_b32 s89, s22, 16
; VI-NEXT:    s_lshr_b32 s90, s21, 16
; VI-NEXT:    s_lshr_b32 s91, s20, 16
; VI-NEXT:    s_lshr_b32 s30, s19, 16
; VI-NEXT:    s_lshr_b32 s31, s18, 16
; VI-NEXT:    s_lshr_b32 s34, s17, 16
; VI-NEXT:    s_lshr_b32 s35, s16, 16
; VI-NEXT:    s_lshr_b32 s6, s7, 16
; VI-NEXT:    s_lshr_b32 s8, s9, 16
; VI-NEXT:    s_lshr_b32 s10, s12, 16
; VI-NEXT:    s_lshr_b32 s14, s15, 16
; VI-NEXT:    s_lshr_b32 s73, s74, 16
; VI-NEXT:    s_lshr_b32 s76, s77, 16
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    s_cbranch_scc0 .LBB43_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_and_b32 s4, 0xffff, s16
; VI-NEXT:    s_lshl_b32 s5, s35, 16
; VI-NEXT:    s_or_b32 s36, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s17
; VI-NEXT:    s_lshl_b32 s5, s34, 16
; VI-NEXT:    s_or_b32 s37, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s18
; VI-NEXT:    s_lshl_b32 s5, s31, 16
; VI-NEXT:    s_or_b32 s38, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s19
; VI-NEXT:    s_lshl_b32 s5, s30, 16
; VI-NEXT:    s_or_b32 s39, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s20
; VI-NEXT:    s_lshl_b32 s5, s91, 16
; VI-NEXT:    s_or_b32 s40, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s21
; VI-NEXT:    s_lshl_b32 s5, s90, 16
; VI-NEXT:    s_or_b32 s41, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s22
; VI-NEXT:    s_lshl_b32 s5, s89, 16
; VI-NEXT:    s_or_b32 s42, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s23
; VI-NEXT:    s_lshl_b32 s5, s88, 16
; VI-NEXT:    s_or_b32 s43, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s24
; VI-NEXT:    s_lshl_b32 s5, s79, 16
; VI-NEXT:    s_or_b32 s44, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s25
; VI-NEXT:    s_lshl_b32 s5, s78, 16
; VI-NEXT:    s_or_b32 s45, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s26
; VI-NEXT:    s_lshl_b32 s5, s75, 16
; VI-NEXT:    s_or_b32 s46, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s27
; VI-NEXT:    s_lshl_b32 s5, s72, 16
; VI-NEXT:    s_or_b32 s47, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s28
; VI-NEXT:    s_lshl_b32 s5, s13, 16
; VI-NEXT:    s_or_b32 s48, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s29
; VI-NEXT:    s_lshl_b32 s5, s11, 16
; VI-NEXT:    s_or_b32 s49, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s77
; VI-NEXT:    s_lshl_b32 s5, s76, 16
; VI-NEXT:    s_or_b32 s50, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s74
; VI-NEXT:    s_lshl_b32 s5, s73, 16
; VI-NEXT:    s_or_b32 s51, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s15
; VI-NEXT:    s_lshl_b32 s5, s14, 16
; VI-NEXT:    s_or_b32 s52, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s12
; VI-NEXT:    s_lshl_b32 s5, s10, 16
; VI-NEXT:    s_or_b32 s53, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s9
; VI-NEXT:    s_lshl_b32 s5, s8, 16
; VI-NEXT:    s_or_b32 s54, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s7
; VI-NEXT:    s_lshl_b32 s5, s6, 16
; VI-NEXT:    s_or_b32 s55, s4, s5
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    s_cbranch_execnz .LBB43_3
; VI-NEXT:  .LBB43_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s16, s16, 3
; VI-NEXT:    s_and_b32 s4, s16, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s35, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s17, s17, 3
; VI-NEXT:    s_add_i32 s36, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s17, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s34, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s18, s18, 3
; VI-NEXT:    s_add_i32 s37, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s18, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s31, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s19, s19, 3
; VI-NEXT:    s_add_i32 s38, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s19, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s30, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s20, s20, 3
; VI-NEXT:    s_add_i32 s39, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s20, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s91, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s21, s21, 3
; VI-NEXT:    s_add_i32 s40, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s21, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s90, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s22, s22, 3
; VI-NEXT:    s_add_i32 s41, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s22, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s89, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s23, s23, 3
; VI-NEXT:    s_add_i32 s42, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s23, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s88, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s24, s24, 3
; VI-NEXT:    s_add_i32 s43, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s24, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s79, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s25, s25, 3
; VI-NEXT:    s_add_i32 s44, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s25, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s78, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s26, s26, 3
; VI-NEXT:    s_add_i32 s45, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s26, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s75, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s27, s27, 3
; VI-NEXT:    s_add_i32 s46, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s27, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s72, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s28, s28, 3
; VI-NEXT:    s_add_i32 s47, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s28, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s13, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s29, s29, 3
; VI-NEXT:    s_add_i32 s48, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s29, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s11, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s77, s77, 3
; VI-NEXT:    s_add_i32 s49, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s77, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s76, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s74, s74, 3
; VI-NEXT:    s_add_i32 s50, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s74, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s73, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s15, s15, 3
; VI-NEXT:    s_add_i32 s51, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s15, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s14, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s12, s12, 3
; VI-NEXT:    s_add_i32 s52, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s12, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s10, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s9, s9, 3
; VI-NEXT:    s_add_i32 s53, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s9, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s8, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s7, s7, 3
; VI-NEXT:    s_add_i32 s54, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s7, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s6, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s55, s4, 0x30000
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:  .LBB43_3: ; %end
; VI-NEXT:    v_readlane_b32 s30, v20, 18
; VI-NEXT:    v_mov_b32_e32 v0, s36
; VI-NEXT:    v_mov_b32_e32 v1, s37
; VI-NEXT:    v_mov_b32_e32 v2, s38
; VI-NEXT:    v_mov_b32_e32 v3, s39
; VI-NEXT:    v_mov_b32_e32 v4, s40
; VI-NEXT:    v_mov_b32_e32 v5, s41
; VI-NEXT:    v_mov_b32_e32 v6, s42
; VI-NEXT:    v_mov_b32_e32 v7, s43
; VI-NEXT:    v_mov_b32_e32 v8, s44
; VI-NEXT:    v_mov_b32_e32 v9, s45
; VI-NEXT:    v_mov_b32_e32 v10, s46
; VI-NEXT:    v_mov_b32_e32 v11, s47
; VI-NEXT:    v_mov_b32_e32 v12, s48
; VI-NEXT:    v_mov_b32_e32 v13, s49
; VI-NEXT:    v_mov_b32_e32 v14, s50
; VI-NEXT:    v_mov_b32_e32 v15, s51
; VI-NEXT:    v_mov_b32_e32 v16, s52
; VI-NEXT:    v_mov_b32_e32 v17, s53
; VI-NEXT:    v_mov_b32_e32 v18, s54
; VI-NEXT:    v_mov_b32_e32 v19, s55
; VI-NEXT:    v_readlane_b32 s31, v20, 19
; VI-NEXT:    v_readlane_b32 s67, v20, 17
; VI-NEXT:    v_readlane_b32 s66, v20, 16
; VI-NEXT:    v_readlane_b32 s65, v20, 15
; VI-NEXT:    v_readlane_b32 s64, v20, 14
; VI-NEXT:    v_readlane_b32 s55, v20, 13
; VI-NEXT:    v_readlane_b32 s54, v20, 12
; VI-NEXT:    v_readlane_b32 s53, v20, 11
; VI-NEXT:    v_readlane_b32 s52, v20, 10
; VI-NEXT:    v_readlane_b32 s51, v20, 9
; VI-NEXT:    v_readlane_b32 s50, v20, 8
; VI-NEXT:    v_readlane_b32 s49, v20, 7
; VI-NEXT:    v_readlane_b32 s48, v20, 6
; VI-NEXT:    v_readlane_b32 s39, v20, 5
; VI-NEXT:    v_readlane_b32 s38, v20, 4
; VI-NEXT:    v_readlane_b32 s37, v20, 3
; VI-NEXT:    v_readlane_b32 s36, v20, 2
; VI-NEXT:    v_readlane_b32 s35, v20, 1
; VI-NEXT:    v_readlane_b32 s34, v20, 0
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_load_dword v20, off, s[0:3], s32 ; 4-byte Folded Reload
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB43_4:
; VI-NEXT:    ; implicit-def: $sgpr36_sgpr37_sgpr38_sgpr39_sgpr40_sgpr41_sgpr42_sgpr43_sgpr44_sgpr45_sgpr46_sgpr47_sgpr48_sgpr49_sgpr50_sgpr51_sgpr52_sgpr53_sgpr54_sgpr55_sgpr56_sgpr57_sgpr58_sgpr59_sgpr60_sgpr61_sgpr62_sgpr63_sgpr64_sgpr65_sgpr66_sgpr67
; VI-NEXT:    s_branch .LBB43_2
;
; GFX9-LABEL: bitcast_v40i16_to_v10i64_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    v_writelane_b32 v32, s36, 0
; GFX9-NEXT:    v_writelane_b32 v32, s37, 1
; GFX9-NEXT:    v_writelane_b32 v32, s38, 2
; GFX9-NEXT:    v_writelane_b32 v32, s39, 3
; GFX9-NEXT:    v_writelane_b32 v32, s48, 4
; GFX9-NEXT:    v_writelane_b32 v32, s49, 5
; GFX9-NEXT:    v_writelane_b32 v32, s50, 6
; GFX9-NEXT:    v_writelane_b32 v32, s51, 7
; GFX9-NEXT:    v_writelane_b32 v32, s52, 8
; GFX9-NEXT:    v_writelane_b32 v32, s53, 9
; GFX9-NEXT:    v_writelane_b32 v32, s54, 10
; GFX9-NEXT:    v_writelane_b32 v32, s55, 11
; GFX9-NEXT:    v_readfirstlane_b32 s56, v5
; GFX9-NEXT:    v_readfirstlane_b32 s58, v4
; GFX9-NEXT:    v_readfirstlane_b32 s60, v3
; GFX9-NEXT:    v_readfirstlane_b32 s62, v2
; GFX9-NEXT:    v_readfirstlane_b32 s72, v1
; GFX9-NEXT:    v_readfirstlane_b32 s74, v0
; GFX9-NEXT:    s_lshr_b32 s4, s29, 16
; GFX9-NEXT:    s_lshr_b32 s5, s28, 16
; GFX9-NEXT:    s_lshr_b32 s6, s27, 16
; GFX9-NEXT:    s_lshr_b32 s7, s26, 16
; GFX9-NEXT:    s_lshr_b32 s8, s25, 16
; GFX9-NEXT:    s_lshr_b32 s9, s24, 16
; GFX9-NEXT:    s_lshr_b32 s10, s23, 16
; GFX9-NEXT:    s_lshr_b32 s11, s22, 16
; GFX9-NEXT:    s_lshr_b32 s12, s21, 16
; GFX9-NEXT:    s_lshr_b32 s13, s20, 16
; GFX9-NEXT:    s_lshr_b32 s14, s19, 16
; GFX9-NEXT:    s_lshr_b32 s15, s18, 16
; GFX9-NEXT:    s_lshr_b32 s40, s17, 16
; GFX9-NEXT:    s_lshr_b32 s41, s16, 16
; GFX9-NEXT:    s_lshr_b32 s57, s56, 16
; GFX9-NEXT:    s_lshr_b32 s59, s58, 16
; GFX9-NEXT:    s_lshr_b32 s61, s60, 16
; GFX9-NEXT:    s_lshr_b32 s63, s62, 16
; GFX9-NEXT:    s_lshr_b32 s73, s72, 16
; GFX9-NEXT:    s_lshr_b32 s75, s74, 16
; GFX9-NEXT:    v_readfirstlane_b32 s42, v6
; GFX9-NEXT:    s_cmp_lg_u32 s42, 0
; GFX9-NEXT:    s_pack_ll_b32_b16 s36, s16, s41
; GFX9-NEXT:    s_pack_ll_b32_b16 s37, s17, s40
; GFX9-NEXT:    s_pack_ll_b32_b16 s38, s18, s15
; GFX9-NEXT:    s_pack_ll_b32_b16 s39, s19, s14
; GFX9-NEXT:    s_pack_ll_b32_b16 s40, s20, s13
; GFX9-NEXT:    s_pack_ll_b32_b16 s41, s21, s12
; GFX9-NEXT:    s_pack_ll_b32_b16 s42, s22, s11
; GFX9-NEXT:    s_pack_ll_b32_b16 s43, s23, s10
; GFX9-NEXT:    s_pack_ll_b32_b16 s44, s24, s9
; GFX9-NEXT:    s_pack_ll_b32_b16 s45, s25, s8
; GFX9-NEXT:    s_pack_ll_b32_b16 s46, s26, s7
; GFX9-NEXT:    s_pack_ll_b32_b16 s47, s27, s6
; GFX9-NEXT:    s_pack_ll_b32_b16 s48, s28, s5
; GFX9-NEXT:    s_pack_ll_b32_b16 s49, s29, s4
; GFX9-NEXT:    s_pack_ll_b32_b16 s50, s74, s75
; GFX9-NEXT:    s_pack_ll_b32_b16 s51, s72, s73
; GFX9-NEXT:    s_pack_ll_b32_b16 s52, s62, s63
; GFX9-NEXT:    s_pack_ll_b32_b16 s53, s60, s61
; GFX9-NEXT:    s_pack_ll_b32_b16 s54, s58, s59
; GFX9-NEXT:    s_pack_ll_b32_b16 s55, s56, s57
; GFX9-NEXT:    s_cbranch_scc0 .LBB43_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB43_4
; GFX9-NEXT:  .LBB43_2: ; %cmp.true
; GFX9-NEXT:    v_pk_add_u16 v0, s36, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v1, s37, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v2, s38, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v3, s39, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v4, s40, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v5, s41, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, s42, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v7, s43, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v8, s44, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v9, s45, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v10, s46, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v11, s47, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v12, s48, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v13, s49, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v14, s50, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v15, s51, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v16, s52, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v17, s53, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v18, s54, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v19, s55, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_branch .LBB43_5
; GFX9-NEXT:  .LBB43_3:
; GFX9-NEXT:    s_branch .LBB43_2
; GFX9-NEXT:  .LBB43_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s36
; GFX9-NEXT:    v_mov_b32_e32 v1, s37
; GFX9-NEXT:    v_mov_b32_e32 v2, s38
; GFX9-NEXT:    v_mov_b32_e32 v3, s39
; GFX9-NEXT:    v_mov_b32_e32 v4, s40
; GFX9-NEXT:    v_mov_b32_e32 v5, s41
; GFX9-NEXT:    v_mov_b32_e32 v6, s42
; GFX9-NEXT:    v_mov_b32_e32 v7, s43
; GFX9-NEXT:    v_mov_b32_e32 v8, s44
; GFX9-NEXT:    v_mov_b32_e32 v9, s45
; GFX9-NEXT:    v_mov_b32_e32 v10, s46
; GFX9-NEXT:    v_mov_b32_e32 v11, s47
; GFX9-NEXT:    v_mov_b32_e32 v12, s48
; GFX9-NEXT:    v_mov_b32_e32 v13, s49
; GFX9-NEXT:    v_mov_b32_e32 v14, s50
; GFX9-NEXT:    v_mov_b32_e32 v15, s51
; GFX9-NEXT:    v_mov_b32_e32 v16, s52
; GFX9-NEXT:    v_mov_b32_e32 v17, s53
; GFX9-NEXT:    v_mov_b32_e32 v18, s54
; GFX9-NEXT:    v_mov_b32_e32 v19, s55
; GFX9-NEXT:    v_mov_b32_e32 v20, s56
; GFX9-NEXT:    v_mov_b32_e32 v21, s57
; GFX9-NEXT:    v_mov_b32_e32 v22, s58
; GFX9-NEXT:    v_mov_b32_e32 v23, s59
; GFX9-NEXT:    v_mov_b32_e32 v24, s60
; GFX9-NEXT:    v_mov_b32_e32 v25, s61
; GFX9-NEXT:    v_mov_b32_e32 v26, s62
; GFX9-NEXT:    v_mov_b32_e32 v27, s63
; GFX9-NEXT:    v_mov_b32_e32 v28, s64
; GFX9-NEXT:    v_mov_b32_e32 v29, s65
; GFX9-NEXT:    v_mov_b32_e32 v30, s66
; GFX9-NEXT:    v_mov_b32_e32 v31, s67
; GFX9-NEXT:  .LBB43_5: ; %end
; GFX9-NEXT:    v_readlane_b32 s55, v32, 11
; GFX9-NEXT:    v_readlane_b32 s54, v32, 10
; GFX9-NEXT:    v_readlane_b32 s53, v32, 9
; GFX9-NEXT:    v_readlane_b32 s52, v32, 8
; GFX9-NEXT:    v_readlane_b32 s51, v32, 7
; GFX9-NEXT:    v_readlane_b32 s50, v32, 6
; GFX9-NEXT:    v_readlane_b32 s49, v32, 5
; GFX9-NEXT:    v_readlane_b32 s48, v32, 4
; GFX9-NEXT:    v_readlane_b32 s39, v32, 3
; GFX9-NEXT:    v_readlane_b32 s38, v32, 2
; GFX9-NEXT:    v_readlane_b32 s37, v32, 1
; GFX9-NEXT:    v_readlane_b32 s36, v32, 0
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v40i16_to_v10i64_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    v_readfirstlane_b32 s45, v1
; GFX11-NEXT:    v_readfirstlane_b32 s46, v0
; GFX11-NEXT:    v_readfirstlane_b32 s56, v2
; GFX11-NEXT:    s_lshr_b32 s41, s29, 16
; GFX11-NEXT:    s_lshr_b32 s42, s28, 16
; GFX11-NEXT:    s_lshr_b32 s15, s27, 16
; GFX11-NEXT:    s_lshr_b32 s14, s26, 16
; GFX11-NEXT:    s_lshr_b32 s13, s25, 16
; GFX11-NEXT:    s_lshr_b32 s12, s24, 16
; GFX11-NEXT:    s_lshr_b32 s11, s23, 16
; GFX11-NEXT:    s_lshr_b32 s10, s22, 16
; GFX11-NEXT:    s_lshr_b32 s9, s21, 16
; GFX11-NEXT:    s_lshr_b32 s8, s20, 16
; GFX11-NEXT:    s_lshr_b32 s7, s19, 16
; GFX11-NEXT:    s_lshr_b32 s6, s18, 16
; GFX11-NEXT:    s_lshr_b32 s5, s17, 16
; GFX11-NEXT:    s_lshr_b32 s4, s16, 16
; GFX11-NEXT:    s_lshr_b32 s43, s3, 16
; GFX11-NEXT:    s_lshr_b32 s44, s2, 16
; GFX11-NEXT:    s_lshr_b32 s47, s1, 16
; GFX11-NEXT:    s_lshr_b32 s57, s0, 16
; GFX11-NEXT:    s_lshr_b32 s58, s45, 16
; GFX11-NEXT:    s_lshr_b32 s59, s46, 16
; GFX11-NEXT:    s_mov_b32 s40, 0
; GFX11-NEXT:    s_cmp_lg_u32 s56, 0
; GFX11-NEXT:    s_pack_ll_b32_b16 s0, s0, s57
; GFX11-NEXT:    s_pack_ll_b32_b16 s1, s1, s47
; GFX11-NEXT:    s_pack_ll_b32_b16 s2, s2, s44
; GFX11-NEXT:    s_pack_ll_b32_b16 s3, s3, s43
; GFX11-NEXT:    s_pack_ll_b32_b16 s4, s16, s4
; GFX11-NEXT:    s_pack_ll_b32_b16 s5, s17, s5
; GFX11-NEXT:    s_pack_ll_b32_b16 s6, s18, s6
; GFX11-NEXT:    s_pack_ll_b32_b16 s7, s19, s7
; GFX11-NEXT:    s_pack_ll_b32_b16 s8, s20, s8
; GFX11-NEXT:    s_pack_ll_b32_b16 s9, s21, s9
; GFX11-NEXT:    s_pack_ll_b32_b16 s10, s22, s10
; GFX11-NEXT:    s_pack_ll_b32_b16 s11, s23, s11
; GFX11-NEXT:    s_pack_ll_b32_b16 s12, s24, s12
; GFX11-NEXT:    s_pack_ll_b32_b16 s13, s25, s13
; GFX11-NEXT:    s_pack_ll_b32_b16 s14, s26, s14
; GFX11-NEXT:    s_pack_ll_b32_b16 s15, s27, s15
; GFX11-NEXT:    s_pack_ll_b32_b16 s16, s28, s42
; GFX11-NEXT:    s_pack_ll_b32_b16 s17, s29, s41
; GFX11-NEXT:    s_pack_ll_b32_b16 s18, s46, s59
; GFX11-NEXT:    s_pack_ll_b32_b16 s19, s45, s58
; GFX11-NEXT:    s_cbranch_scc0 .LBB43_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s40
; GFX11-NEXT:    s_cbranch_vccnz .LBB43_4
; GFX11-NEXT:  .LBB43_2: ; %cmp.true
; GFX11-NEXT:    v_pk_add_u16 v0, s0, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v1, s1, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v2, s2, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v3, s3, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v4, s4, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v5, s5, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v6, s6, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v7, s7, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v8, s8, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v9, s9, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v10, s10, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v11, s11, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v12, s12, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v13, s13, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v14, s14, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v15, s15, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v16, s16, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v17, s17, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v18, s18, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v19, s19, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB43_3:
; GFX11-NEXT:    s_branch .LBB43_2
; GFX11-NEXT:  .LBB43_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    v_dual_mov_b32 v8, s8 :: v_dual_mov_b32 v9, s9
; GFX11-NEXT:    v_dual_mov_b32 v10, s10 :: v_dual_mov_b32 v11, s11
; GFX11-NEXT:    v_dual_mov_b32 v12, s12 :: v_dual_mov_b32 v13, s13
; GFX11-NEXT:    v_dual_mov_b32 v14, s14 :: v_dual_mov_b32 v15, s15
; GFX11-NEXT:    v_dual_mov_b32 v16, s16 :: v_dual_mov_b32 v17, s17
; GFX11-NEXT:    v_dual_mov_b32 v18, s18 :: v_dual_mov_b32 v19, s19
; GFX11-NEXT:    v_dual_mov_b32 v20, s20 :: v_dual_mov_b32 v21, s21
; GFX11-NEXT:    v_dual_mov_b32 v22, s22 :: v_dual_mov_b32 v23, s23
; GFX11-NEXT:    v_dual_mov_b32 v24, s24 :: v_dual_mov_b32 v25, s25
; GFX11-NEXT:    v_dual_mov_b32 v26, s26 :: v_dual_mov_b32 v27, s27
; GFX11-NEXT:    v_dual_mov_b32 v28, s28 :: v_dual_mov_b32 v29, s29
; GFX11-NEXT:    v_dual_mov_b32 v30, s30 :: v_dual_mov_b32 v31, s31
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <40 x i16> %a, splat (i16 3)
  %a2 = bitcast <40 x i16> %a1 to <10 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <40 x i16> %a to <10 x i64>
  br label %end

end:
  %phi = phi <10 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <10 x i64> %phi
}

define <40 x half> @bitcast_v10i64_to_v40f16(<10 x i64> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v10i64_to_v40f16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:    ; implicit-def: $vgpr31
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr28
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr26
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr25
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr24
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr30
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr29
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr27
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB44_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_alignbit_b32 v20, v19, v18, 16
; SI-NEXT:    v_alignbit_b32 v21, v17, v16, 16
; SI-NEXT:    v_alignbit_b32 v22, v15, v14, 16
; SI-NEXT:    v_alignbit_b32 v23, v13, v12, 16
; SI-NEXT:    v_alignbit_b32 v24, v11, v10, 16
; SI-NEXT:    v_alignbit_b32 v25, v9, v8, 16
; SI-NEXT:    v_alignbit_b32 v26, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v28, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v31, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v34, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v27, 16, v19
; SI-NEXT:    v_lshrrev_b32_e32 v29, 16, v17
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v15
; SI-NEXT:    v_lshrrev_b32_e32 v32, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v33, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v35, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v36, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v37, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v39, 16, v1
; SI-NEXT:  .LBB44_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB44_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; SI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; SI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; SI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; SI-NEXT:    v_add_i32_e32 v8, vcc, 3, v8
; SI-NEXT:    v_addc_u32_e32 v9, vcc, 0, v9, vcc
; SI-NEXT:    v_add_i32_e32 v10, vcc, 3, v10
; SI-NEXT:    v_addc_u32_e32 v11, vcc, 0, v11, vcc
; SI-NEXT:    v_add_i32_e32 v12, vcc, 3, v12
; SI-NEXT:    v_addc_u32_e32 v13, vcc, 0, v13, vcc
; SI-NEXT:    v_add_i32_e32 v14, vcc, 3, v14
; SI-NEXT:    v_addc_u32_e32 v15, vcc, 0, v15, vcc
; SI-NEXT:    v_add_i32_e32 v16, vcc, 3, v16
; SI-NEXT:    v_addc_u32_e32 v17, vcc, 0, v17, vcc
; SI-NEXT:    v_add_i32_e32 v18, vcc, 3, v18
; SI-NEXT:    v_addc_u32_e32 v19, vcc, 0, v19, vcc
; SI-NEXT:    v_alignbit_b32 v20, v19, v18, 16
; SI-NEXT:    v_alignbit_b32 v21, v17, v16, 16
; SI-NEXT:    v_alignbit_b32 v22, v15, v14, 16
; SI-NEXT:    v_alignbit_b32 v23, v13, v12, 16
; SI-NEXT:    v_alignbit_b32 v24, v11, v10, 16
; SI-NEXT:    v_alignbit_b32 v25, v9, v8, 16
; SI-NEXT:    v_alignbit_b32 v26, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v28, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v31, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v34, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v27, 16, v19
; SI-NEXT:    v_lshrrev_b32_e32 v29, 16, v17
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v15
; SI-NEXT:    v_lshrrev_b32_e32 v32, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v33, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v35, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v36, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v37, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v39, 16, v1
; SI-NEXT:  .LBB44_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v34, 16, v34
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v31, 16, v31
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_lshlrev_b32_e32 v28, 16, v28
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v26, 16, v26
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; SI-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; SI-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v16
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; SI-NEXT:    v_or_b32_e32 v0, v0, v34
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v34, 16, v39
; SI-NEXT:    v_or_b32_e32 v2, v2, v31
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v31, 16, v38
; SI-NEXT:    v_or_b32_e32 v4, v4, v28
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v28, 16, v37
; SI-NEXT:    v_or_b32_e32 v6, v6, v26
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v26, 16, v36
; SI-NEXT:    v_or_b32_e32 v8, v8, v25
; SI-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; SI-NEXT:    v_lshlrev_b32_e32 v25, 16, v35
; SI-NEXT:    v_or_b32_e32 v10, v10, v24
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; SI-NEXT:    v_lshlrev_b32_e32 v24, 16, v33
; SI-NEXT:    v_or_b32_e32 v12, v12, v23
; SI-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v32
; SI-NEXT:    v_or_b32_e32 v14, v14, v22
; SI-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v30
; SI-NEXT:    v_or_b32_e32 v16, v16, v21
; SI-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v29
; SI-NEXT:    v_or_b32_e32 v18, v18, v20
; SI-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v27
; SI-NEXT:    v_or_b32_e32 v1, v1, v34
; SI-NEXT:    v_or_b32_e32 v3, v3, v31
; SI-NEXT:    v_or_b32_e32 v5, v5, v28
; SI-NEXT:    v_or_b32_e32 v7, v7, v26
; SI-NEXT:    v_or_b32_e32 v9, v9, v25
; SI-NEXT:    v_or_b32_e32 v11, v11, v24
; SI-NEXT:    v_or_b32_e32 v13, v13, v23
; SI-NEXT:    v_or_b32_e32 v15, v15, v22
; SI-NEXT:    v_or_b32_e32 v17, v17, v21
; SI-NEXT:    v_or_b32_e32 v19, v19, v20
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v10i64_to_v40f16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    ; implicit-def: $vgpr39
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr35
; VI-NEXT:    ; implicit-def: $vgpr34
; VI-NEXT:    ; implicit-def: $vgpr33
; VI-NEXT:    ; implicit-def: $vgpr32
; VI-NEXT:    ; implicit-def: $vgpr31
; VI-NEXT:    ; implicit-def: $vgpr30
; VI-NEXT:    ; implicit-def: $vgpr29
; VI-NEXT:    ; implicit-def: $vgpr28
; VI-NEXT:    ; implicit-def: $vgpr27
; VI-NEXT:    ; implicit-def: $vgpr26
; VI-NEXT:    ; implicit-def: $vgpr25
; VI-NEXT:    ; implicit-def: $vgpr24
; VI-NEXT:    ; implicit-def: $vgpr23
; VI-NEXT:    ; implicit-def: $vgpr22
; VI-NEXT:    ; implicit-def: $vgpr21
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB44_2
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; VI-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; VI-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; VI-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; VI-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; VI-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; VI-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; VI-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; VI-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; VI-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; VI-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; VI-NEXT:  .LBB44_2: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB44_4
; VI-NEXT:  ; %bb.3: ; %cmp.true
; VI-NEXT:    v_add_u32_e32 v18, vcc, 3, v18
; VI-NEXT:    v_addc_u32_e32 v19, vcc, 0, v19, vcc
; VI-NEXT:    v_add_u32_e32 v16, vcc, 3, v16
; VI-NEXT:    v_addc_u32_e32 v17, vcc, 0, v17, vcc
; VI-NEXT:    v_add_u32_e32 v14, vcc, 3, v14
; VI-NEXT:    v_addc_u32_e32 v15, vcc, 0, v15, vcc
; VI-NEXT:    v_add_u32_e32 v12, vcc, 3, v12
; VI-NEXT:    v_addc_u32_e32 v13, vcc, 0, v13, vcc
; VI-NEXT:    v_add_u32_e32 v10, vcc, 3, v10
; VI-NEXT:    v_addc_u32_e32 v11, vcc, 0, v11, vcc
; VI-NEXT:    v_add_u32_e32 v8, vcc, 3, v8
; VI-NEXT:    v_addc_u32_e32 v9, vcc, 0, v9, vcc
; VI-NEXT:    v_add_u32_e32 v6, vcc, 3, v6
; VI-NEXT:    v_addc_u32_e32 v7, vcc, 0, v7, vcc
; VI-NEXT:    v_add_u32_e32 v4, vcc, 3, v4
; VI-NEXT:    v_addc_u32_e32 v5, vcc, 0, v5, vcc
; VI-NEXT:    v_add_u32_e32 v2, vcc, 3, v2
; VI-NEXT:    v_addc_u32_e32 v3, vcc, 0, v3, vcc
; VI-NEXT:    v_add_u32_e32 v0, vcc, 3, v0
; VI-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; VI-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; VI-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; VI-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; VI-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; VI-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; VI-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; VI-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; VI-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; VI-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; VI-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; VI-NEXT:  .LBB44_4: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    v_lshlrev_b32_e32 v39, 16, v39
; VI-NEXT:    v_lshlrev_b32_e32 v38, 16, v38
; VI-NEXT:    v_lshlrev_b32_e32 v37, 16, v37
; VI-NEXT:    v_lshlrev_b32_e32 v36, 16, v36
; VI-NEXT:    v_lshlrev_b32_e32 v35, 16, v35
; VI-NEXT:    v_lshlrev_b32_e32 v34, 16, v34
; VI-NEXT:    v_lshlrev_b32_e32 v33, 16, v33
; VI-NEXT:    v_lshlrev_b32_e32 v32, 16, v32
; VI-NEXT:    v_lshlrev_b32_e32 v31, 16, v31
; VI-NEXT:    v_lshlrev_b32_e32 v30, 16, v30
; VI-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; VI-NEXT:    v_lshlrev_b32_e32 v28, 16, v28
; VI-NEXT:    v_lshlrev_b32_e32 v27, 16, v27
; VI-NEXT:    v_lshlrev_b32_e32 v26, 16, v26
; VI-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; VI-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; VI-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; VI-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; VI-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; VI-NEXT:    v_or_b32_sdwa v0, v0, v39 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v1, v1, v38 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v2, v2, v37 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v3, v3, v36 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v4, v4, v35 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v5, v5, v34 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v6, v6, v33 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v7, v7, v32 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v8, v8, v31 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v9, v9, v30 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v10, v10, v29 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v11, v11, v28 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v12, v12, v27 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v13, v13, v26 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v14, v14, v25 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v15, v15, v24 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v16, v16, v23 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v17, v17, v22 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v18, v18, v21 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v19, v19, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v10i64_to_v40f16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    ; implicit-def: $vgpr39
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr35
; GFX9-NEXT:    ; implicit-def: $vgpr34
; GFX9-NEXT:    ; implicit-def: $vgpr33
; GFX9-NEXT:    ; implicit-def: $vgpr32
; GFX9-NEXT:    ; implicit-def: $vgpr31
; GFX9-NEXT:    ; implicit-def: $vgpr30
; GFX9-NEXT:    ; implicit-def: $vgpr29
; GFX9-NEXT:    ; implicit-def: $vgpr28
; GFX9-NEXT:    ; implicit-def: $vgpr27
; GFX9-NEXT:    ; implicit-def: $vgpr26
; GFX9-NEXT:    ; implicit-def: $vgpr25
; GFX9-NEXT:    ; implicit-def: $vgpr24
; GFX9-NEXT:    ; implicit-def: $vgpr23
; GFX9-NEXT:    ; implicit-def: $vgpr22
; GFX9-NEXT:    ; implicit-def: $vgpr21
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB44_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX9-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX9-NEXT:  .LBB44_2: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB44_4
; GFX9-NEXT:  ; %bb.3: ; %cmp.true
; GFX9-NEXT:    v_add_co_u32_e32 v18, vcc, 3, v18
; GFX9-NEXT:    v_addc_co_u32_e32 v19, vcc, 0, v19, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v16, vcc, 3, v16
; GFX9-NEXT:    v_addc_co_u32_e32 v17, vcc, 0, v17, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v14, vcc, 3, v14
; GFX9-NEXT:    v_addc_co_u32_e32 v15, vcc, 0, v15, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v12, vcc, 3, v12
; GFX9-NEXT:    v_addc_co_u32_e32 v13, vcc, 0, v13, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v10, vcc, 3, v10
; GFX9-NEXT:    v_addc_co_u32_e32 v11, vcc, 0, v11, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v8, vcc, 3, v8
; GFX9-NEXT:    v_addc_co_u32_e32 v9, vcc, 0, v9, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v6, vcc, 3, v6
; GFX9-NEXT:    v_addc_co_u32_e32 v7, vcc, 0, v7, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v4, vcc, 3, v4
; GFX9-NEXT:    v_addc_co_u32_e32 v5, vcc, 0, v5, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v2, vcc, 3, v2
; GFX9-NEXT:    v_addc_co_u32_e32 v3, vcc, 0, v3, vcc
; GFX9-NEXT:    v_add_co_u32_e32 v0, vcc, 3, v0
; GFX9-NEXT:    v_addc_co_u32_e32 v1, vcc, 0, v1, vcc
; GFX9-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX9-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX9-NEXT:  .LBB44_4: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_mov_b32 s4, 0x5040100
; GFX9-NEXT:    v_perm_b32 v0, v39, v0, s4
; GFX9-NEXT:    v_perm_b32 v1, v38, v1, s4
; GFX9-NEXT:    v_perm_b32 v2, v37, v2, s4
; GFX9-NEXT:    v_perm_b32 v3, v36, v3, s4
; GFX9-NEXT:    v_perm_b32 v4, v35, v4, s4
; GFX9-NEXT:    v_perm_b32 v5, v34, v5, s4
; GFX9-NEXT:    v_perm_b32 v6, v33, v6, s4
; GFX9-NEXT:    v_perm_b32 v7, v32, v7, s4
; GFX9-NEXT:    v_perm_b32 v8, v31, v8, s4
; GFX9-NEXT:    v_perm_b32 v9, v30, v9, s4
; GFX9-NEXT:    v_perm_b32 v10, v29, v10, s4
; GFX9-NEXT:    v_perm_b32 v11, v28, v11, s4
; GFX9-NEXT:    v_perm_b32 v12, v27, v12, s4
; GFX9-NEXT:    v_perm_b32 v13, v26, v13, s4
; GFX9-NEXT:    v_perm_b32 v14, v25, v14, s4
; GFX9-NEXT:    v_perm_b32 v15, v24, v15, s4
; GFX9-NEXT:    v_perm_b32 v16, v23, v16, s4
; GFX9-NEXT:    v_perm_b32 v17, v22, v17, s4
; GFX9-NEXT:    v_perm_b32 v18, v21, v18, s4
; GFX9-NEXT:    v_perm_b32 v19, v20, v19, s4
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v10i64_to_v40f16:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB44_2
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_add_co_u32 v18, vcc_lo, v18, 3
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add_co_ci_u32_e64 v19, null, 0, v19, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_co_u32 v16, vcc_lo, v16, 3
; GFX11-TRUE16-NEXT:    v_add_co_ci_u32_e64 v17, null, 0, v17, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_co_u32 v14, vcc_lo, v14, 3
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add_co_ci_u32_e64 v15, null, 0, v15, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_co_u32 v12, vcc_lo, v12, 3
; GFX11-TRUE16-NEXT:    v_add_co_ci_u32_e64 v13, null, 0, v13, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_co_u32 v10, vcc_lo, v10, 3
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add_co_ci_u32_e64 v11, null, 0, v11, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_co_u32 v8, vcc_lo, v8, 3
; GFX11-TRUE16-NEXT:    v_add_co_ci_u32_e64 v9, null, 0, v9, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_co_u32 v6, vcc_lo, v6, 3
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add_co_ci_u32_e64 v7, null, 0, v7, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_co_u32 v4, vcc_lo, v4, 3
; GFX11-TRUE16-NEXT:    v_add_co_ci_u32_e64 v5, null, 0, v5, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_co_u32 v2, vcc_lo, v2, 3
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-TRUE16-NEXT:    v_add_co_ci_u32_e64 v3, null, 0, v3, vcc_lo
; GFX11-TRUE16-NEXT:    v_add_co_u32 v0, vcc_lo, v0, 3
; GFX11-TRUE16-NEXT:    v_add_co_ci_u32_e64 v1, null, 0, v1, vcc_lo
; GFX11-TRUE16-NEXT:  .LBB44_2: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v10i64_to_v40f16:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr39
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr38
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr37
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr36
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr35
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr34
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr33
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr32
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr31
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr30
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr29
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr28
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr27
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr26
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr25
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr24
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr23
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr22
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr21
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB44_2
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX11-FAKE16-NEXT:  .LBB44_2: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB44_4
; GFX11-FAKE16-NEXT:  ; %bb.3: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_add_co_u32 v18, vcc_lo, v18, 3
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_add_co_ci_u32_e64 v19, null, 0, v19, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_co_u32 v16, vcc_lo, v16, 3
; GFX11-FAKE16-NEXT:    v_add_co_ci_u32_e64 v17, null, 0, v17, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_co_u32 v14, vcc_lo, v14, 3
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_add_co_ci_u32_e64 v15, null, 0, v15, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_co_u32 v12, vcc_lo, v12, 3
; GFX11-FAKE16-NEXT:    v_add_co_ci_u32_e64 v13, null, 0, v13, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_co_u32 v10, vcc_lo, v10, 3
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_add_co_ci_u32_e64 v11, null, 0, v11, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_co_u32 v8, vcc_lo, v8, 3
; GFX11-FAKE16-NEXT:    v_add_co_ci_u32_e64 v9, null, 0, v9, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_co_u32 v6, vcc_lo, v6, 3
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_add_co_ci_u32_e64 v7, null, 0, v7, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_co_u32 v4, vcc_lo, v4, 3
; GFX11-FAKE16-NEXT:    v_add_co_ci_u32_e64 v5, null, 0, v5, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_co_u32 v2, vcc_lo, v2, 3
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX11-FAKE16-NEXT:    v_add_co_ci_u32_e64 v3, null, 0, v3, vcc_lo
; GFX11-FAKE16-NEXT:    v_add_co_u32 v0, vcc_lo, v0, 3
; GFX11-FAKE16-NEXT:    v_add_co_ci_u32_e64 v1, null, 0, v1, vcc_lo
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX11-FAKE16-NEXT:  .LBB44_4: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v39, v0, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v38, v1, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v37, v2, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v36, v3, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v35, v4, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v34, v5, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v33, v6, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v32, v7, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, v31, v8, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, v30, v9, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, v29, v10, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, v28, v11, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, v27, v12, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, v26, v13, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v14, v25, v14, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v15, v24, v15, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v16, v23, v16, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v17, v22, v17, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v18, v21, v18, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v19, v20, v19, 0x5040100
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <10 x i64> %a, splat (i64 3)
  %a2 = bitcast <10 x i64> %a1 to <40 x half>
  br label %end

cmp.false:
  %a3 = bitcast <10 x i64> %a to <40 x half>
  br label %end

end:
  %phi = phi <40 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <40 x half> %phi
}

define inreg <40 x half> @bitcast_v10i64_to_v40f16_scalar(<10 x i64> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v10i64_to_v40f16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_readfirstlane_b32 s8, v6
; SI-NEXT:    v_readfirstlane_b32 s5, v5
; SI-NEXT:    v_readfirstlane_b32 s4, v4
; SI-NEXT:    v_readfirstlane_b32 s7, v3
; SI-NEXT:    v_readfirstlane_b32 s6, v2
; SI-NEXT:    v_readfirstlane_b32 s9, v1
; SI-NEXT:    s_cmp_lg_u32 s8, 0
; SI-NEXT:    v_readfirstlane_b32 s8, v0
; SI-NEXT:    s_cbranch_scc0 .LBB45_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_lshr_b32 s72, s5, 16
; SI-NEXT:    s_lshr_b32 s73, s7, 16
; SI-NEXT:    s_lshr_b32 s74, s9, 16
; SI-NEXT:    s_lshr_b32 s75, s29, 16
; SI-NEXT:    s_lshr_b32 s76, s27, 16
; SI-NEXT:    s_lshr_b32 s77, s25, 16
; SI-NEXT:    s_lshr_b32 s78, s23, 16
; SI-NEXT:    s_lshr_b32 s79, s21, 16
; SI-NEXT:    s_lshr_b32 s88, s19, 16
; SI-NEXT:    s_lshr_b32 s89, s17, 16
; SI-NEXT:    s_lshr_b64 s[10:11], s[4:5], 16
; SI-NEXT:    s_lshr_b64 s[12:13], s[6:7], 16
; SI-NEXT:    s_lshr_b64 s[14:15], s[8:9], 16
; SI-NEXT:    s_lshr_b64 s[40:41], s[28:29], 16
; SI-NEXT:    s_lshr_b64 s[42:43], s[26:27], 16
; SI-NEXT:    s_lshr_b64 s[44:45], s[24:25], 16
; SI-NEXT:    s_lshr_b64 s[46:47], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[56:57], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[58:59], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[60:61], s[16:17], 16
; SI-NEXT:    s_cbranch_execnz .LBB45_3
; SI-NEXT:  .LBB45_2: ; %cmp.true
; SI-NEXT:    s_add_u32 s4, s4, 3
; SI-NEXT:    s_addc_u32 s5, s5, 0
; SI-NEXT:    s_add_u32 s6, s6, 3
; SI-NEXT:    s_addc_u32 s7, s7, 0
; SI-NEXT:    s_add_u32 s8, s8, 3
; SI-NEXT:    s_addc_u32 s9, s9, 0
; SI-NEXT:    s_add_u32 s28, s28, 3
; SI-NEXT:    s_addc_u32 s29, s29, 0
; SI-NEXT:    s_add_u32 s26, s26, 3
; SI-NEXT:    s_addc_u32 s27, s27, 0
; SI-NEXT:    s_add_u32 s24, s24, 3
; SI-NEXT:    s_addc_u32 s25, s25, 0
; SI-NEXT:    s_add_u32 s22, s22, 3
; SI-NEXT:    s_addc_u32 s23, s23, 0
; SI-NEXT:    s_add_u32 s20, s20, 3
; SI-NEXT:    s_addc_u32 s21, s21, 0
; SI-NEXT:    s_add_u32 s18, s18, 3
; SI-NEXT:    s_addc_u32 s19, s19, 0
; SI-NEXT:    s_add_u32 s16, s16, 3
; SI-NEXT:    s_addc_u32 s17, s17, 0
; SI-NEXT:    s_lshr_b32 s72, s5, 16
; SI-NEXT:    s_lshr_b32 s73, s7, 16
; SI-NEXT:    s_lshr_b32 s74, s9, 16
; SI-NEXT:    s_lshr_b32 s75, s29, 16
; SI-NEXT:    s_lshr_b32 s76, s27, 16
; SI-NEXT:    s_lshr_b32 s77, s25, 16
; SI-NEXT:    s_lshr_b32 s78, s23, 16
; SI-NEXT:    s_lshr_b32 s79, s21, 16
; SI-NEXT:    s_lshr_b32 s88, s19, 16
; SI-NEXT:    s_lshr_b32 s89, s17, 16
; SI-NEXT:    s_lshr_b64 s[10:11], s[4:5], 16
; SI-NEXT:    s_lshr_b64 s[12:13], s[6:7], 16
; SI-NEXT:    s_lshr_b64 s[14:15], s[8:9], 16
; SI-NEXT:    s_lshr_b64 s[40:41], s[28:29], 16
; SI-NEXT:    s_lshr_b64 s[42:43], s[26:27], 16
; SI-NEXT:    s_lshr_b64 s[44:45], s[24:25], 16
; SI-NEXT:    s_lshr_b64 s[46:47], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[56:57], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[58:59], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[60:61], s[16:17], 16
; SI-NEXT:  .LBB45_3: ; %end
; SI-NEXT:    s_lshl_b32 s11, s60, 16
; SI-NEXT:    s_and_b32 s13, s16, 0xffff
; SI-NEXT:    s_or_b32 s11, s13, s11
; SI-NEXT:    s_and_b32 s13, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s15, s89, 16
; SI-NEXT:    s_or_b32 s13, s13, s15
; SI-NEXT:    s_lshl_b32 s15, s58, 16
; SI-NEXT:    s_and_b32 s16, s18, 0xffff
; SI-NEXT:    s_or_b32 s15, s16, s15
; SI-NEXT:    s_and_b32 s16, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s17, s88, 16
; SI-NEXT:    s_or_b32 s16, s16, s17
; SI-NEXT:    s_lshl_b32 s17, s56, 16
; SI-NEXT:    s_and_b32 s18, s20, 0xffff
; SI-NEXT:    s_or_b32 s17, s18, s17
; SI-NEXT:    s_and_b32 s18, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s19, s79, 16
; SI-NEXT:    s_or_b32 s18, s18, s19
; SI-NEXT:    s_and_b32 s19, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s20, s46, 16
; SI-NEXT:    s_or_b32 s19, s19, s20
; SI-NEXT:    s_and_b32 s20, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s21, s78, 16
; SI-NEXT:    s_or_b32 s20, s20, s21
; SI-NEXT:    s_and_b32 s21, s24, 0xffff
; SI-NEXT:    s_lshl_b32 s22, s44, 16
; SI-NEXT:    s_or_b32 s21, s21, s22
; SI-NEXT:    s_and_b32 s22, s25, 0xffff
; SI-NEXT:    s_lshl_b32 s23, s77, 16
; SI-NEXT:    s_or_b32 s22, s22, s23
; SI-NEXT:    s_and_b32 s23, s26, 0xffff
; SI-NEXT:    s_lshl_b32 s24, s42, 16
; SI-NEXT:    s_or_b32 s23, s23, s24
; SI-NEXT:    s_and_b32 s24, s27, 0xffff
; SI-NEXT:    s_lshl_b32 s25, s76, 16
; SI-NEXT:    s_or_b32 s24, s24, s25
; SI-NEXT:    s_and_b32 s25, s28, 0xffff
; SI-NEXT:    s_lshl_b32 s26, s40, 16
; SI-NEXT:    s_and_b32 s8, s8, 0xffff
; SI-NEXT:    s_lshl_b32 s14, s14, 16
; SI-NEXT:    s_and_b32 s6, s6, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s12, 16
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s10, 16
; SI-NEXT:    s_or_b32 s25, s25, s26
; SI-NEXT:    s_and_b32 s26, s29, 0xffff
; SI-NEXT:    s_lshl_b32 s27, s75, 16
; SI-NEXT:    s_or_b32 s8, s8, s14
; SI-NEXT:    s_and_b32 s9, s9, 0xffff
; SI-NEXT:    s_lshl_b32 s14, s74, 16
; SI-NEXT:    s_or_b32 s6, s6, s12
; SI-NEXT:    s_and_b32 s7, s7, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s73, 16
; SI-NEXT:    s_or_b32 s4, s4, s10
; SI-NEXT:    s_and_b32 s5, s5, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s72, 16
; SI-NEXT:    s_or_b32 s26, s26, s27
; SI-NEXT:    s_or_b32 s9, s9, s14
; SI-NEXT:    s_or_b32 s7, s7, s12
; SI-NEXT:    s_or_b32 s5, s5, s10
; SI-NEXT:    v_mov_b32_e32 v0, s11
; SI-NEXT:    v_mov_b32_e32 v1, s13
; SI-NEXT:    v_mov_b32_e32 v2, s15
; SI-NEXT:    v_mov_b32_e32 v3, s16
; SI-NEXT:    v_mov_b32_e32 v4, s17
; SI-NEXT:    v_mov_b32_e32 v5, s18
; SI-NEXT:    v_mov_b32_e32 v6, s19
; SI-NEXT:    v_mov_b32_e32 v7, s20
; SI-NEXT:    v_mov_b32_e32 v8, s21
; SI-NEXT:    v_mov_b32_e32 v9, s22
; SI-NEXT:    v_mov_b32_e32 v10, s23
; SI-NEXT:    v_mov_b32_e32 v11, s24
; SI-NEXT:    v_mov_b32_e32 v12, s25
; SI-NEXT:    v_mov_b32_e32 v13, s26
; SI-NEXT:    v_mov_b32_e32 v14, s8
; SI-NEXT:    v_mov_b32_e32 v15, s9
; SI-NEXT:    v_mov_b32_e32 v16, s6
; SI-NEXT:    v_mov_b32_e32 v17, s7
; SI-NEXT:    v_mov_b32_e32 v18, s4
; SI-NEXT:    v_mov_b32_e32 v19, s5
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB45_4:
; SI-NEXT:    ; implicit-def: $sgpr60
; SI-NEXT:    ; implicit-def: $sgpr89
; SI-NEXT:    ; implicit-def: $sgpr58
; SI-NEXT:    ; implicit-def: $sgpr88
; SI-NEXT:    ; implicit-def: $sgpr56
; SI-NEXT:    ; implicit-def: $sgpr79
; SI-NEXT:    ; implicit-def: $sgpr46
; SI-NEXT:    ; implicit-def: $sgpr78
; SI-NEXT:    ; implicit-def: $sgpr44
; SI-NEXT:    ; implicit-def: $sgpr77
; SI-NEXT:    ; implicit-def: $sgpr42
; SI-NEXT:    ; implicit-def: $sgpr76
; SI-NEXT:    ; implicit-def: $sgpr40
; SI-NEXT:    ; implicit-def: $sgpr75
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr74
; SI-NEXT:    ; implicit-def: $sgpr12
; SI-NEXT:    ; implicit-def: $sgpr73
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr72
; SI-NEXT:    s_branch .LBB45_2
;
; VI-LABEL: bitcast_v10i64_to_v40f16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    v_readfirstlane_b32 s6, v5
; VI-NEXT:    v_readfirstlane_b32 s7, v4
; VI-NEXT:    v_readfirstlane_b32 s8, v3
; VI-NEXT:    v_readfirstlane_b32 s9, v2
; VI-NEXT:    v_readfirstlane_b32 s10, v1
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    v_readfirstlane_b32 s11, v0
; VI-NEXT:    s_cbranch_scc0 .LBB45_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_lshr_b32 s12, s6, 16
; VI-NEXT:    s_lshr_b32 s13, s7, 16
; VI-NEXT:    s_lshr_b32 s14, s8, 16
; VI-NEXT:    s_lshr_b32 s15, s9, 16
; VI-NEXT:    s_lshr_b32 s40, s10, 16
; VI-NEXT:    s_lshr_b32 s41, s11, 16
; VI-NEXT:    s_lshr_b32 s42, s29, 16
; VI-NEXT:    s_lshr_b32 s43, s28, 16
; VI-NEXT:    s_lshr_b32 s44, s27, 16
; VI-NEXT:    s_lshr_b32 s45, s26, 16
; VI-NEXT:    s_lshr_b32 s46, s25, 16
; VI-NEXT:    s_lshr_b32 s47, s24, 16
; VI-NEXT:    s_lshr_b32 s56, s23, 16
; VI-NEXT:    s_lshr_b32 s57, s22, 16
; VI-NEXT:    s_lshr_b32 s58, s21, 16
; VI-NEXT:    s_lshr_b32 s59, s20, 16
; VI-NEXT:    s_lshr_b32 s60, s19, 16
; VI-NEXT:    s_lshr_b32 s61, s18, 16
; VI-NEXT:    s_lshr_b32 s62, s17, 16
; VI-NEXT:    s_lshr_b32 s63, s16, 16
; VI-NEXT:    s_cbranch_execnz .LBB45_3
; VI-NEXT:  .LBB45_2: ; %cmp.true
; VI-NEXT:    s_add_u32 s7, s7, 3
; VI-NEXT:    s_addc_u32 s6, s6, 0
; VI-NEXT:    s_add_u32 s9, s9, 3
; VI-NEXT:    s_addc_u32 s8, s8, 0
; VI-NEXT:    s_add_u32 s11, s11, 3
; VI-NEXT:    s_addc_u32 s10, s10, 0
; VI-NEXT:    s_add_u32 s28, s28, 3
; VI-NEXT:    s_addc_u32 s29, s29, 0
; VI-NEXT:    s_add_u32 s26, s26, 3
; VI-NEXT:    s_addc_u32 s27, s27, 0
; VI-NEXT:    s_add_u32 s24, s24, 3
; VI-NEXT:    s_addc_u32 s25, s25, 0
; VI-NEXT:    s_add_u32 s22, s22, 3
; VI-NEXT:    s_addc_u32 s23, s23, 0
; VI-NEXT:    s_add_u32 s20, s20, 3
; VI-NEXT:    s_addc_u32 s21, s21, 0
; VI-NEXT:    s_add_u32 s18, s18, 3
; VI-NEXT:    s_addc_u32 s19, s19, 0
; VI-NEXT:    s_add_u32 s16, s16, 3
; VI-NEXT:    s_addc_u32 s17, s17, 0
; VI-NEXT:    s_lshr_b32 s12, s6, 16
; VI-NEXT:    s_lshr_b32 s13, s7, 16
; VI-NEXT:    s_lshr_b32 s14, s8, 16
; VI-NEXT:    s_lshr_b32 s15, s9, 16
; VI-NEXT:    s_lshr_b32 s40, s10, 16
; VI-NEXT:    s_lshr_b32 s41, s11, 16
; VI-NEXT:    s_lshr_b32 s42, s29, 16
; VI-NEXT:    s_lshr_b32 s43, s28, 16
; VI-NEXT:    s_lshr_b32 s44, s27, 16
; VI-NEXT:    s_lshr_b32 s45, s26, 16
; VI-NEXT:    s_lshr_b32 s46, s25, 16
; VI-NEXT:    s_lshr_b32 s47, s24, 16
; VI-NEXT:    s_lshr_b32 s56, s23, 16
; VI-NEXT:    s_lshr_b32 s57, s22, 16
; VI-NEXT:    s_lshr_b32 s58, s21, 16
; VI-NEXT:    s_lshr_b32 s59, s20, 16
; VI-NEXT:    s_lshr_b32 s60, s19, 16
; VI-NEXT:    s_lshr_b32 s61, s18, 16
; VI-NEXT:    s_lshr_b32 s62, s17, 16
; VI-NEXT:    s_lshr_b32 s63, s16, 16
; VI-NEXT:  .LBB45_3: ; %end
; VI-NEXT:    s_and_b32 s4, 0xffff, s16
; VI-NEXT:    s_lshl_b32 s5, s63, 16
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_and_b32 s5, 0xffff, s17
; VI-NEXT:    s_lshl_b32 s16, s62, 16
; VI-NEXT:    s_or_b32 s5, s5, s16
; VI-NEXT:    s_and_b32 s16, 0xffff, s18
; VI-NEXT:    s_lshl_b32 s17, s61, 16
; VI-NEXT:    s_or_b32 s16, s16, s17
; VI-NEXT:    s_and_b32 s17, 0xffff, s19
; VI-NEXT:    s_lshl_b32 s18, s60, 16
; VI-NEXT:    s_or_b32 s17, s17, s18
; VI-NEXT:    s_and_b32 s18, 0xffff, s20
; VI-NEXT:    s_lshl_b32 s19, s59, 16
; VI-NEXT:    s_or_b32 s18, s18, s19
; VI-NEXT:    s_and_b32 s19, 0xffff, s21
; VI-NEXT:    s_lshl_b32 s20, s58, 16
; VI-NEXT:    s_or_b32 s19, s19, s20
; VI-NEXT:    s_and_b32 s20, 0xffff, s22
; VI-NEXT:    s_lshl_b32 s21, s57, 16
; VI-NEXT:    s_or_b32 s20, s20, s21
; VI-NEXT:    s_and_b32 s21, 0xffff, s23
; VI-NEXT:    s_lshl_b32 s22, s56, 16
; VI-NEXT:    s_or_b32 s21, s21, s22
; VI-NEXT:    s_and_b32 s22, 0xffff, s24
; VI-NEXT:    s_lshl_b32 s23, s47, 16
; VI-NEXT:    s_or_b32 s22, s22, s23
; VI-NEXT:    s_and_b32 s23, 0xffff, s25
; VI-NEXT:    s_lshl_b32 s24, s46, 16
; VI-NEXT:    s_or_b32 s23, s23, s24
; VI-NEXT:    s_and_b32 s24, 0xffff, s26
; VI-NEXT:    s_lshl_b32 s25, s45, 16
; VI-NEXT:    s_or_b32 s24, s24, s25
; VI-NEXT:    s_and_b32 s25, 0xffff, s27
; VI-NEXT:    s_lshl_b32 s26, s44, 16
; VI-NEXT:    s_or_b32 s25, s25, s26
; VI-NEXT:    s_and_b32 s26, 0xffff, s28
; VI-NEXT:    s_lshl_b32 s27, s43, 16
; VI-NEXT:    s_or_b32 s26, s26, s27
; VI-NEXT:    s_and_b32 s27, 0xffff, s29
; VI-NEXT:    s_lshl_b32 s28, s42, 16
; VI-NEXT:    s_or_b32 s27, s27, s28
; VI-NEXT:    s_and_b32 s11, 0xffff, s11
; VI-NEXT:    s_lshl_b32 s28, s41, 16
; VI-NEXT:    s_or_b32 s11, s11, s28
; VI-NEXT:    s_and_b32 s10, 0xffff, s10
; VI-NEXT:    s_lshl_b32 s28, s40, 16
; VI-NEXT:    s_and_b32 s9, 0xffff, s9
; VI-NEXT:    s_lshl_b32 s15, s15, 16
; VI-NEXT:    s_and_b32 s8, 0xffff, s8
; VI-NEXT:    s_lshl_b32 s14, s14, 16
; VI-NEXT:    s_and_b32 s7, 0xffff, s7
; VI-NEXT:    s_lshl_b32 s13, s13, 16
; VI-NEXT:    s_and_b32 s6, 0xffff, s6
; VI-NEXT:    s_lshl_b32 s12, s12, 16
; VI-NEXT:    s_or_b32 s10, s10, s28
; VI-NEXT:    s_or_b32 s9, s9, s15
; VI-NEXT:    s_or_b32 s8, s8, s14
; VI-NEXT:    s_or_b32 s7, s7, s13
; VI-NEXT:    s_or_b32 s6, s6, s12
; VI-NEXT:    v_mov_b32_e32 v0, s4
; VI-NEXT:    v_mov_b32_e32 v1, s5
; VI-NEXT:    v_mov_b32_e32 v2, s16
; VI-NEXT:    v_mov_b32_e32 v3, s17
; VI-NEXT:    v_mov_b32_e32 v4, s18
; VI-NEXT:    v_mov_b32_e32 v5, s19
; VI-NEXT:    v_mov_b32_e32 v6, s20
; VI-NEXT:    v_mov_b32_e32 v7, s21
; VI-NEXT:    v_mov_b32_e32 v8, s22
; VI-NEXT:    v_mov_b32_e32 v9, s23
; VI-NEXT:    v_mov_b32_e32 v10, s24
; VI-NEXT:    v_mov_b32_e32 v11, s25
; VI-NEXT:    v_mov_b32_e32 v12, s26
; VI-NEXT:    v_mov_b32_e32 v13, s27
; VI-NEXT:    v_mov_b32_e32 v14, s11
; VI-NEXT:    v_mov_b32_e32 v15, s10
; VI-NEXT:    v_mov_b32_e32 v16, s9
; VI-NEXT:    v_mov_b32_e32 v17, s8
; VI-NEXT:    v_mov_b32_e32 v18, s7
; VI-NEXT:    v_mov_b32_e32 v19, s6
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB45_4:
; VI-NEXT:    ; implicit-def: $sgpr63
; VI-NEXT:    ; implicit-def: $sgpr62
; VI-NEXT:    ; implicit-def: $sgpr61
; VI-NEXT:    ; implicit-def: $sgpr60
; VI-NEXT:    ; implicit-def: $sgpr59
; VI-NEXT:    ; implicit-def: $sgpr58
; VI-NEXT:    ; implicit-def: $sgpr57
; VI-NEXT:    ; implicit-def: $sgpr56
; VI-NEXT:    ; implicit-def: $sgpr47
; VI-NEXT:    ; implicit-def: $sgpr46
; VI-NEXT:    ; implicit-def: $sgpr45
; VI-NEXT:    ; implicit-def: $sgpr44
; VI-NEXT:    ; implicit-def: $sgpr43
; VI-NEXT:    ; implicit-def: $sgpr42
; VI-NEXT:    ; implicit-def: $sgpr41
; VI-NEXT:    ; implicit-def: $sgpr40
; VI-NEXT:    ; implicit-def: $sgpr15
; VI-NEXT:    ; implicit-def: $sgpr14
; VI-NEXT:    ; implicit-def: $sgpr13
; VI-NEXT:    ; implicit-def: $sgpr12
; VI-NEXT:    s_branch .LBB45_2
;
; GFX9-LABEL: bitcast_v10i64_to_v40f16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_readfirstlane_b32 s4, v6
; GFX9-NEXT:    v_readfirstlane_b32 s6, v5
; GFX9-NEXT:    v_readfirstlane_b32 s7, v4
; GFX9-NEXT:    v_readfirstlane_b32 s8, v3
; GFX9-NEXT:    v_readfirstlane_b32 s9, v2
; GFX9-NEXT:    v_readfirstlane_b32 s10, v1
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    v_readfirstlane_b32 s11, v0
; GFX9-NEXT:    s_cbranch_scc0 .LBB45_4
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_lshr_b32 s12, s6, 16
; GFX9-NEXT:    s_lshr_b32 s13, s7, 16
; GFX9-NEXT:    s_lshr_b32 s14, s8, 16
; GFX9-NEXT:    s_lshr_b32 s15, s9, 16
; GFX9-NEXT:    s_lshr_b32 s40, s10, 16
; GFX9-NEXT:    s_lshr_b32 s41, s11, 16
; GFX9-NEXT:    s_lshr_b32 s42, s29, 16
; GFX9-NEXT:    s_lshr_b32 s43, s28, 16
; GFX9-NEXT:    s_lshr_b32 s44, s27, 16
; GFX9-NEXT:    s_lshr_b32 s45, s26, 16
; GFX9-NEXT:    s_lshr_b32 s46, s25, 16
; GFX9-NEXT:    s_lshr_b32 s47, s24, 16
; GFX9-NEXT:    s_lshr_b32 s56, s23, 16
; GFX9-NEXT:    s_lshr_b32 s57, s22, 16
; GFX9-NEXT:    s_lshr_b32 s58, s21, 16
; GFX9-NEXT:    s_lshr_b32 s59, s20, 16
; GFX9-NEXT:    s_lshr_b32 s60, s19, 16
; GFX9-NEXT:    s_lshr_b32 s61, s18, 16
; GFX9-NEXT:    s_lshr_b32 s62, s17, 16
; GFX9-NEXT:    s_lshr_b32 s63, s16, 16
; GFX9-NEXT:    s_cbranch_execnz .LBB45_3
; GFX9-NEXT:  .LBB45_2: ; %cmp.true
; GFX9-NEXT:    s_add_u32 s7, s7, 3
; GFX9-NEXT:    s_addc_u32 s6, s6, 0
; GFX9-NEXT:    s_add_u32 s9, s9, 3
; GFX9-NEXT:    s_addc_u32 s8, s8, 0
; GFX9-NEXT:    s_add_u32 s11, s11, 3
; GFX9-NEXT:    s_addc_u32 s10, s10, 0
; GFX9-NEXT:    s_add_u32 s28, s28, 3
; GFX9-NEXT:    s_addc_u32 s29, s29, 0
; GFX9-NEXT:    s_add_u32 s26, s26, 3
; GFX9-NEXT:    s_addc_u32 s27, s27, 0
; GFX9-NEXT:    s_add_u32 s24, s24, 3
; GFX9-NEXT:    s_addc_u32 s25, s25, 0
; GFX9-NEXT:    s_add_u32 s22, s22, 3
; GFX9-NEXT:    s_addc_u32 s23, s23, 0
; GFX9-NEXT:    s_add_u32 s20, s20, 3
; GFX9-NEXT:    s_addc_u32 s21, s21, 0
; GFX9-NEXT:    s_add_u32 s18, s18, 3
; GFX9-NEXT:    s_addc_u32 s19, s19, 0
; GFX9-NEXT:    s_add_u32 s16, s16, 3
; GFX9-NEXT:    s_addc_u32 s17, s17, 0
; GFX9-NEXT:    s_lshr_b32 s12, s6, 16
; GFX9-NEXT:    s_lshr_b32 s13, s7, 16
; GFX9-NEXT:    s_lshr_b32 s14, s8, 16
; GFX9-NEXT:    s_lshr_b32 s15, s9, 16
; GFX9-NEXT:    s_lshr_b32 s40, s10, 16
; GFX9-NEXT:    s_lshr_b32 s41, s11, 16
; GFX9-NEXT:    s_lshr_b32 s42, s29, 16
; GFX9-NEXT:    s_lshr_b32 s43, s28, 16
; GFX9-NEXT:    s_lshr_b32 s44, s27, 16
; GFX9-NEXT:    s_lshr_b32 s45, s26, 16
; GFX9-NEXT:    s_lshr_b32 s46, s25, 16
; GFX9-NEXT:    s_lshr_b32 s47, s24, 16
; GFX9-NEXT:    s_lshr_b32 s56, s23, 16
; GFX9-NEXT:    s_lshr_b32 s57, s22, 16
; GFX9-NEXT:    s_lshr_b32 s58, s21, 16
; GFX9-NEXT:    s_lshr_b32 s59, s20, 16
; GFX9-NEXT:    s_lshr_b32 s60, s19, 16
; GFX9-NEXT:    s_lshr_b32 s61, s18, 16
; GFX9-NEXT:    s_lshr_b32 s62, s17, 16
; GFX9-NEXT:    s_lshr_b32 s63, s16, 16
; GFX9-NEXT:  .LBB45_3: ; %end
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s16, s63
; GFX9-NEXT:    s_pack_ll_b32_b16 s5, s17, s62
; GFX9-NEXT:    s_pack_ll_b32_b16 s16, s18, s61
; GFX9-NEXT:    s_pack_ll_b32_b16 s17, s19, s60
; GFX9-NEXT:    s_pack_ll_b32_b16 s18, s20, s59
; GFX9-NEXT:    s_pack_ll_b32_b16 s19, s21, s58
; GFX9-NEXT:    s_pack_ll_b32_b16 s20, s22, s57
; GFX9-NEXT:    s_pack_ll_b32_b16 s21, s23, s56
; GFX9-NEXT:    s_pack_ll_b32_b16 s22, s24, s47
; GFX9-NEXT:    s_pack_ll_b32_b16 s23, s25, s46
; GFX9-NEXT:    s_pack_ll_b32_b16 s24, s26, s45
; GFX9-NEXT:    s_pack_ll_b32_b16 s25, s27, s44
; GFX9-NEXT:    s_pack_ll_b32_b16 s26, s28, s43
; GFX9-NEXT:    s_pack_ll_b32_b16 s27, s29, s42
; GFX9-NEXT:    s_pack_ll_b32_b16 s11, s11, s41
; GFX9-NEXT:    s_pack_ll_b32_b16 s10, s10, s40
; GFX9-NEXT:    s_pack_ll_b32_b16 s9, s9, s15
; GFX9-NEXT:    s_pack_ll_b32_b16 s8, s8, s14
; GFX9-NEXT:    s_pack_ll_b32_b16 s7, s7, s13
; GFX9-NEXT:    s_pack_ll_b32_b16 s6, s6, s12
; GFX9-NEXT:    v_mov_b32_e32 v0, s4
; GFX9-NEXT:    v_mov_b32_e32 v1, s5
; GFX9-NEXT:    v_mov_b32_e32 v2, s16
; GFX9-NEXT:    v_mov_b32_e32 v3, s17
; GFX9-NEXT:    v_mov_b32_e32 v4, s18
; GFX9-NEXT:    v_mov_b32_e32 v5, s19
; GFX9-NEXT:    v_mov_b32_e32 v6, s20
; GFX9-NEXT:    v_mov_b32_e32 v7, s21
; GFX9-NEXT:    v_mov_b32_e32 v8, s22
; GFX9-NEXT:    v_mov_b32_e32 v9, s23
; GFX9-NEXT:    v_mov_b32_e32 v10, s24
; GFX9-NEXT:    v_mov_b32_e32 v11, s25
; GFX9-NEXT:    v_mov_b32_e32 v12, s26
; GFX9-NEXT:    v_mov_b32_e32 v13, s27
; GFX9-NEXT:    v_mov_b32_e32 v14, s11
; GFX9-NEXT:    v_mov_b32_e32 v15, s10
; GFX9-NEXT:    v_mov_b32_e32 v16, s9
; GFX9-NEXT:    v_mov_b32_e32 v17, s8
; GFX9-NEXT:    v_mov_b32_e32 v18, s7
; GFX9-NEXT:    v_mov_b32_e32 v19, s6
; GFX9-NEXT:    s_setpc_b64 s[30:31]
; GFX9-NEXT:  .LBB45_4:
; GFX9-NEXT:    ; implicit-def: $sgpr63
; GFX9-NEXT:    ; implicit-def: $sgpr62
; GFX9-NEXT:    ; implicit-def: $sgpr61
; GFX9-NEXT:    ; implicit-def: $sgpr60
; GFX9-NEXT:    ; implicit-def: $sgpr59
; GFX9-NEXT:    ; implicit-def: $sgpr58
; GFX9-NEXT:    ; implicit-def: $sgpr57
; GFX9-NEXT:    ; implicit-def: $sgpr56
; GFX9-NEXT:    ; implicit-def: $sgpr47
; GFX9-NEXT:    ; implicit-def: $sgpr46
; GFX9-NEXT:    ; implicit-def: $sgpr45
; GFX9-NEXT:    ; implicit-def: $sgpr44
; GFX9-NEXT:    ; implicit-def: $sgpr43
; GFX9-NEXT:    ; implicit-def: $sgpr42
; GFX9-NEXT:    ; implicit-def: $sgpr41
; GFX9-NEXT:    ; implicit-def: $sgpr40
; GFX9-NEXT:    ; implicit-def: $sgpr15
; GFX9-NEXT:    ; implicit-def: $sgpr14
; GFX9-NEXT:    ; implicit-def: $sgpr13
; GFX9-NEXT:    ; implicit-def: $sgpr12
; GFX9-NEXT:    s_branch .LBB45_2
;
; GFX11-LABEL: bitcast_v10i64_to_v40f16_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    v_readfirstlane_b32 s6, v2
; GFX11-NEXT:    v_readfirstlane_b32 s4, v1
; GFX11-NEXT:    v_readfirstlane_b32 s5, v0
; GFX11-NEXT:    s_mov_b32 s58, 0
; GFX11-NEXT:    s_cmp_lg_u32 s6, 0
; GFX11-NEXT:    s_cbranch_scc0 .LBB45_4
; GFX11-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-NEXT:    s_lshr_b32 s6, s4, 16
; GFX11-NEXT:    s_lshr_b32 s7, s5, 16
; GFX11-NEXT:    s_lshr_b32 s8, s29, 16
; GFX11-NEXT:    s_lshr_b32 s9, s28, 16
; GFX11-NEXT:    s_lshr_b32 s10, s27, 16
; GFX11-NEXT:    s_lshr_b32 s11, s26, 16
; GFX11-NEXT:    s_lshr_b32 s12, s25, 16
; GFX11-NEXT:    s_lshr_b32 s13, s24, 16
; GFX11-NEXT:    s_lshr_b32 s14, s23, 16
; GFX11-NEXT:    s_lshr_b32 s15, s22, 16
; GFX11-NEXT:    s_lshr_b32 s40, s21, 16
; GFX11-NEXT:    s_lshr_b32 s41, s20, 16
; GFX11-NEXT:    s_lshr_b32 s42, s19, 16
; GFX11-NEXT:    s_lshr_b32 s43, s18, 16
; GFX11-NEXT:    s_lshr_b32 s44, s17, 16
; GFX11-NEXT:    s_lshr_b32 s45, s16, 16
; GFX11-NEXT:    s_lshr_b32 s46, s3, 16
; GFX11-NEXT:    s_lshr_b32 s47, s2, 16
; GFX11-NEXT:    s_lshr_b32 s56, s1, 16
; GFX11-NEXT:    s_lshr_b32 s57, s0, 16
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s58
; GFX11-NEXT:    s_cbranch_vccnz .LBB45_3
; GFX11-NEXT:  .LBB45_2: ; %cmp.true
; GFX11-NEXT:    s_add_u32 s5, s5, 3
; GFX11-NEXT:    s_addc_u32 s4, s4, 0
; GFX11-NEXT:    s_add_u32 s28, s28, 3
; GFX11-NEXT:    s_addc_u32 s29, s29, 0
; GFX11-NEXT:    s_add_u32 s26, s26, 3
; GFX11-NEXT:    s_addc_u32 s27, s27, 0
; GFX11-NEXT:    s_add_u32 s24, s24, 3
; GFX11-NEXT:    s_addc_u32 s25, s25, 0
; GFX11-NEXT:    s_add_u32 s22, s22, 3
; GFX11-NEXT:    s_addc_u32 s23, s23, 0
; GFX11-NEXT:    s_add_u32 s20, s20, 3
; GFX11-NEXT:    s_addc_u32 s21, s21, 0
; GFX11-NEXT:    s_add_u32 s18, s18, 3
; GFX11-NEXT:    s_addc_u32 s19, s19, 0
; GFX11-NEXT:    s_add_u32 s16, s16, 3
; GFX11-NEXT:    s_addc_u32 s17, s17, 0
; GFX11-NEXT:    s_add_u32 s2, s2, 3
; GFX11-NEXT:    s_addc_u32 s3, s3, 0
; GFX11-NEXT:    s_add_u32 s0, s0, 3
; GFX11-NEXT:    s_addc_u32 s1, s1, 0
; GFX11-NEXT:    s_lshr_b32 s6, s4, 16
; GFX11-NEXT:    s_lshr_b32 s7, s5, 16
; GFX11-NEXT:    s_lshr_b32 s8, s29, 16
; GFX11-NEXT:    s_lshr_b32 s9, s28, 16
; GFX11-NEXT:    s_lshr_b32 s10, s27, 16
; GFX11-NEXT:    s_lshr_b32 s11, s26, 16
; GFX11-NEXT:    s_lshr_b32 s12, s25, 16
; GFX11-NEXT:    s_lshr_b32 s13, s24, 16
; GFX11-NEXT:    s_lshr_b32 s14, s23, 16
; GFX11-NEXT:    s_lshr_b32 s15, s22, 16
; GFX11-NEXT:    s_lshr_b32 s40, s21, 16
; GFX11-NEXT:    s_lshr_b32 s41, s20, 16
; GFX11-NEXT:    s_lshr_b32 s42, s19, 16
; GFX11-NEXT:    s_lshr_b32 s43, s18, 16
; GFX11-NEXT:    s_lshr_b32 s44, s17, 16
; GFX11-NEXT:    s_lshr_b32 s45, s16, 16
; GFX11-NEXT:    s_lshr_b32 s46, s3, 16
; GFX11-NEXT:    s_lshr_b32 s47, s2, 16
; GFX11-NEXT:    s_lshr_b32 s56, s1, 16
; GFX11-NEXT:    s_lshr_b32 s57, s0, 16
; GFX11-NEXT:  .LBB45_3: ; %end
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    s_pack_ll_b32_b16 s0, s0, s57
; GFX11-NEXT:    s_pack_ll_b32_b16 s1, s1, s56
; GFX11-NEXT:    s_pack_ll_b32_b16 s2, s2, s47
; GFX11-NEXT:    s_pack_ll_b32_b16 s3, s3, s46
; GFX11-NEXT:    s_pack_ll_b32_b16 s16, s16, s45
; GFX11-NEXT:    s_pack_ll_b32_b16 s17, s17, s44
; GFX11-NEXT:    s_pack_ll_b32_b16 s18, s18, s43
; GFX11-NEXT:    s_pack_ll_b32_b16 s19, s19, s42
; GFX11-NEXT:    s_pack_ll_b32_b16 s20, s20, s41
; GFX11-NEXT:    s_pack_ll_b32_b16 s21, s21, s40
; GFX11-NEXT:    s_pack_ll_b32_b16 s15, s22, s15
; GFX11-NEXT:    s_pack_ll_b32_b16 s14, s23, s14
; GFX11-NEXT:    s_pack_ll_b32_b16 s13, s24, s13
; GFX11-NEXT:    s_pack_ll_b32_b16 s12, s25, s12
; GFX11-NEXT:    s_pack_ll_b32_b16 s11, s26, s11
; GFX11-NEXT:    s_pack_ll_b32_b16 s10, s27, s10
; GFX11-NEXT:    s_pack_ll_b32_b16 s9, s28, s9
; GFX11-NEXT:    s_pack_ll_b32_b16 s8, s29, s8
; GFX11-NEXT:    s_pack_ll_b32_b16 s5, s5, s7
; GFX11-NEXT:    s_pack_ll_b32_b16 s4, s4, s6
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s16 :: v_dual_mov_b32 v5, s17
; GFX11-NEXT:    v_dual_mov_b32 v6, s18 :: v_dual_mov_b32 v7, s19
; GFX11-NEXT:    v_dual_mov_b32 v8, s20 :: v_dual_mov_b32 v9, s21
; GFX11-NEXT:    v_dual_mov_b32 v10, s15 :: v_dual_mov_b32 v11, s14
; GFX11-NEXT:    v_dual_mov_b32 v12, s13 :: v_dual_mov_b32 v13, s12
; GFX11-NEXT:    v_dual_mov_b32 v14, s11 :: v_dual_mov_b32 v15, s10
; GFX11-NEXT:    v_dual_mov_b32 v16, s9 :: v_dual_mov_b32 v17, s8
; GFX11-NEXT:    v_dual_mov_b32 v18, s5 :: v_dual_mov_b32 v19, s4
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB45_4:
; GFX11-NEXT:    ; implicit-def: $sgpr57
; GFX11-NEXT:    ; implicit-def: $sgpr56
; GFX11-NEXT:    ; implicit-def: $sgpr47
; GFX11-NEXT:    ; implicit-def: $sgpr46
; GFX11-NEXT:    ; implicit-def: $sgpr45
; GFX11-NEXT:    ; implicit-def: $sgpr44
; GFX11-NEXT:    ; implicit-def: $sgpr43
; GFX11-NEXT:    ; implicit-def: $sgpr42
; GFX11-NEXT:    ; implicit-def: $sgpr41
; GFX11-NEXT:    ; implicit-def: $sgpr40
; GFX11-NEXT:    ; implicit-def: $sgpr15
; GFX11-NEXT:    ; implicit-def: $sgpr14
; GFX11-NEXT:    ; implicit-def: $sgpr13
; GFX11-NEXT:    ; implicit-def: $sgpr12
; GFX11-NEXT:    ; implicit-def: $sgpr11
; GFX11-NEXT:    ; implicit-def: $sgpr10
; GFX11-NEXT:    ; implicit-def: $sgpr9
; GFX11-NEXT:    ; implicit-def: $sgpr8
; GFX11-NEXT:    ; implicit-def: $sgpr7
; GFX11-NEXT:    ; implicit-def: $sgpr6
; GFX11-NEXT:    s_branch .LBB45_2
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <10 x i64> %a, splat (i64 3)
  %a2 = bitcast <10 x i64> %a1 to <40 x half>
  br label %end

cmp.false:
  %a3 = bitcast <10 x i64> %a to <40 x half>
  br label %end

end:
  %phi = phi <40 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <40 x half> %phi
}

define <10 x i64> @bitcast_v40f16_to_v10i64(<40 x half> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v40f16_to_v10i64:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v63, off, s[0:3], s32 ; 4-byte Folded Spill
; SI-NEXT:    v_mov_b32_e32 v32, v19
; SI-NEXT:    v_mov_b32_e32 v33, v18
; SI-NEXT:    v_mov_b32_e32 v43, v0
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v32
; SI-NEXT:    v_mov_b32_e32 v34, v17
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:64 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v33
; SI-NEXT:    v_mov_b32_e32 v35, v16
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:68 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v34
; SI-NEXT:    v_mov_b32_e32 v36, v15
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:72 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v35
; SI-NEXT:    v_mov_b32_e32 v37, v14
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:76 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v36
; SI-NEXT:    v_mov_b32_e32 v38, v13
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:80 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v37
; SI-NEXT:    v_mov_b32_e32 v39, v12
; SI-NEXT:    v_mov_b32_e32 v48, v11
; SI-NEXT:    v_mov_b32_e32 v49, v10
; SI-NEXT:    v_mov_b32_e32 v50, v9
; SI-NEXT:    v_mov_b32_e32 v51, v8
; SI-NEXT:    v_mov_b32_e32 v52, v7
; SI-NEXT:    v_mov_b32_e32 v53, v6
; SI-NEXT:    v_mov_b32_e32 v54, v5
; SI-NEXT:    v_mov_b32_e32 v55, v4
; SI-NEXT:    v_mov_b32_e32 v40, v3
; SI-NEXT:    v_mov_b32_e32 v41, v2
; SI-NEXT:    v_mov_b32_e32 v42, v1
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:84 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v38
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:88 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v39
; SI-NEXT:    v_lshrrev_b32_e32 v60, 16, v48
; SI-NEXT:    v_lshrrev_b32_e32 v61, 16, v49
; SI-NEXT:    v_lshrrev_b32_e32 v62, 16, v50
; SI-NEXT:    v_lshrrev_b32_e32 v63, 16, v51
; SI-NEXT:    v_lshrrev_b32_e32 v44, 16, v52
; SI-NEXT:    v_lshrrev_b32_e32 v45, 16, v53
; SI-NEXT:    v_lshrrev_b32_e32 v46, 16, v54
; SI-NEXT:    v_lshrrev_b32_e32 v47, 16, v55
; SI-NEXT:    v_lshrrev_b32_e32 v56, 16, v40
; SI-NEXT:    v_lshrrev_b32_e32 v57, 16, v41
; SI-NEXT:    v_lshrrev_b32_e32 v58, 16, v42
; SI-NEXT:    v_lshrrev_b32_e32 v59, 16, v43
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:92 ; 4-byte Folded Spill
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB46_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:92 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:88 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:84 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:80 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:76 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:72 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v43
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v59
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v42
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v58
; SI-NEXT:    v_or_b32_e32 v0, v0, v1
; SI-NEXT:    v_or_b32_e32 v1, v2, v3
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v41
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v57
; SI-NEXT:    v_or_b32_e32 v2, v2, v3
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v40
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v56
; SI-NEXT:    v_or_b32_e32 v3, v3, v4
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v55
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v47
; SI-NEXT:    v_or_b32_e32 v4, v4, v5
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v54
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v46
; SI-NEXT:    v_or_b32_e32 v5, v5, v6
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v53
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v45
; SI-NEXT:    v_or_b32_e32 v6, v6, v7
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v52
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v44
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v51
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v63
; SI-NEXT:    v_or_b32_e32 v8, v8, v9
; SI-NEXT:    v_and_b32_e32 v9, 0xffff, v50
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v62
; SI-NEXT:    v_or_b32_e32 v9, v9, v10
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v49
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v61
; SI-NEXT:    v_or_b32_e32 v10, v10, v11
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v48
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v60
; SI-NEXT:    v_or_b32_e32 v11, v11, v12
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v39
; SI-NEXT:    ; implicit-def: $vgpr43
; SI-NEXT:    ; implicit-def: $vgpr42
; SI-NEXT:    ; implicit-def: $vgpr41
; SI-NEXT:    ; implicit-def: $vgpr40
; SI-NEXT:    ; implicit-def: $vgpr55
; SI-NEXT:    ; implicit-def: $vgpr54
; SI-NEXT:    ; implicit-def: $vgpr53
; SI-NEXT:    ; implicit-def: $vgpr52
; SI-NEXT:    ; implicit-def: $vgpr51
; SI-NEXT:    ; implicit-def: $vgpr50
; SI-NEXT:    ; implicit-def: $vgpr49
; SI-NEXT:    ; implicit-def: $vgpr48
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:    ; implicit-def: $vgpr59
; SI-NEXT:    ; implicit-def: $vgpr58
; SI-NEXT:    ; implicit-def: $vgpr57
; SI-NEXT:    ; implicit-def: $vgpr56
; SI-NEXT:    ; implicit-def: $vgpr47
; SI-NEXT:    ; implicit-def: $vgpr46
; SI-NEXT:    ; implicit-def: $vgpr45
; SI-NEXT:    ; implicit-def: $vgpr44
; SI-NEXT:    ; implicit-def: $vgpr63
; SI-NEXT:    ; implicit-def: $vgpr62
; SI-NEXT:    ; implicit-def: $vgpr61
; SI-NEXT:    ; implicit-def: $vgpr60
; SI-NEXT:    s_waitcnt vmcnt(7)
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v13
; SI-NEXT:    v_or_b32_e32 v12, v12, v13
; SI-NEXT:    v_and_b32_e32 v13, 0xffff, v38
; SI-NEXT:    s_waitcnt vmcnt(6)
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v14
; SI-NEXT:    v_or_b32_e32 v13, v13, v14
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v37
; SI-NEXT:    s_waitcnt vmcnt(5)
; SI-NEXT:    v_lshlrev_b32_e32 v15, 16, v15
; SI-NEXT:    v_or_b32_e32 v14, v14, v15
; SI-NEXT:    v_and_b32_e32 v15, 0xffff, v36
; SI-NEXT:    s_waitcnt vmcnt(4)
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v16
; SI-NEXT:    v_or_b32_e32 v15, v15, v16
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v35
; SI-NEXT:    s_waitcnt vmcnt(3)
; SI-NEXT:    v_lshlrev_b32_e32 v17, 16, v17
; SI-NEXT:    v_or_b32_e32 v16, v16, v17
; SI-NEXT:    v_and_b32_e32 v17, 0xffff, v34
; SI-NEXT:    s_waitcnt vmcnt(2)
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v18
; SI-NEXT:    v_or_b32_e32 v17, v17, v18
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v33
; SI-NEXT:    s_waitcnt vmcnt(1)
; SI-NEXT:    v_lshlrev_b32_e32 v19, 16, v19
; SI-NEXT:    v_or_b32_e32 v18, v18, v19
; SI-NEXT:    v_and_b32_e32 v19, 0xffff, v32
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; SI-NEXT:    v_or_b32_e32 v19, v19, v20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:  .LBB46_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB46_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_cvt_f32_f16_e32 v0, v59
; SI-NEXT:    v_cvt_f32_f16_e32 v2, v58
; SI-NEXT:    v_cvt_f32_f16_e32 v1, v43
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v42
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_or_b32_e32 v0, v1, v0
; SI-NEXT:    v_or_b32_e32 v1, v3, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v2, v57
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v41
; SI-NEXT:    v_cvt_f32_f16_e32 v4, v40
; SI-NEXT:    v_cvt_f32_f16_e32 v5, v55
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_or_b32_e32 v2, v3, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v56
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v6, v54
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v7, v53
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_or_b32_e32 v3, v4, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v4, v47
; SI-NEXT:    v_cvt_f32_f16_e32 v8, v44
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v8, v8
; SI-NEXT:    v_cvt_f32_f16_e32 v9, v52
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_or_b32_e32 v4, v5, v4
; SI-NEXT:    v_cvt_f32_f16_e32 v5, v46
; SI-NEXT:    v_cvt_f32_f16_e32 v10, v51
; SI-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v9
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_add_f32_e32 v10, 0x38000000, v10
; SI-NEXT:    v_cvt_f16_f32_e32 v10, v10
; SI-NEXT:    v_cvt_f32_f16_e32 v11, v61
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_or_b32_e32 v5, v6, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v6, v45
; SI-NEXT:    v_cvt_f32_f16_e32 v12, v49
; SI-NEXT:    v_add_f32_e32 v11, 0x38000000, v11
; SI-NEXT:    v_cvt_f16_f32_e32 v11, v11
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v12, 0x38000000, v12
; SI-NEXT:    v_cvt_f16_f32_e32 v12, v12
; SI-NEXT:    v_cvt_f32_f16_e32 v13, v48
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_or_b32_e32 v6, v7, v6
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v8
; SI-NEXT:    v_cvt_f32_f16_e32 v8, v63
; SI-NEXT:    v_or_b32_e32 v7, v9, v7
; SI-NEXT:    v_cvt_f32_f16_e32 v9, v62
; SI-NEXT:    v_add_f32_e32 v13, 0x38000000, v13
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v8, v8
; SI-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v9
; SI-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:88 ; 4-byte Folded Reload
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_or_b32_e32 v8, v10, v8
; SI-NEXT:    v_cvt_f32_f16_e32 v10, v50
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v13, v13
; SI-NEXT:    v_cvt_f32_f16_e32 v15, v38
; SI-NEXT:    v_add_f32_e32 v10, 0x38000000, v10
; SI-NEXT:    v_cvt_f16_f32_e32 v10, v10
; SI-NEXT:    v_cvt_f32_f16_e32 v16, v37
; SI-NEXT:    v_add_f32_e32 v15, 0x38000000, v15
; SI-NEXT:    v_cvt_f16_f32_e32 v15, v15
; SI-NEXT:    v_or_b32_e32 v9, v10, v9
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v11
; SI-NEXT:    v_or_b32_e32 v10, v12, v10
; SI-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:92 ; 4-byte Folded Reload
; SI-NEXT:    v_cvt_f32_f16_e32 v11, v60
; SI-NEXT:    v_add_f32_e32 v16, 0x38000000, v16
; SI-NEXT:    v_cvt_f16_f32_e32 v16, v16
; SI-NEXT:    v_cvt_f32_f16_e32 v18, v35
; SI-NEXT:    v_add_f32_e32 v11, 0x38000000, v11
; SI-NEXT:    v_cvt_f16_f32_e32 v11, v11
; SI-NEXT:    v_cvt_f32_f16_e32 v19, v34
; SI-NEXT:    v_add_f32_e32 v18, 0x38000000, v18
; SI-NEXT:    v_cvt_f16_f32_e32 v18, v18
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; SI-NEXT:    v_or_b32_e32 v11, v13, v11
; SI-NEXT:    v_cvt_f32_f16_e32 v13, v39
; SI-NEXT:    v_add_f32_e32 v19, 0x38000000, v19
; SI-NEXT:    v_cvt_f16_f32_e32 v19, v19
; SI-NEXT:    v_cvt_f32_f16_e32 v21, v32
; SI-NEXT:    v_add_f32_e32 v13, 0x38000000, v13
; SI-NEXT:    v_cvt_f16_f32_e32 v13, v13
; SI-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:76 ; 4-byte Folded Reload
; SI-NEXT:    v_add_f32_e32 v21, 0x38000000, v21
; SI-NEXT:    v_cvt_f16_f32_e32 v21, v21
; SI-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(3)
; SI-NEXT:    v_cvt_f32_f16_e32 v14, v14
; SI-NEXT:    v_add_f32_e32 v14, 0x38000000, v14
; SI-NEXT:    v_cvt_f16_f32_e32 v14, v14
; SI-NEXT:    s_waitcnt vmcnt(2)
; SI-NEXT:    v_cvt_f32_f16_e32 v12, v12
; SI-NEXT:    v_add_f32_e32 v12, 0x38000000, v12
; SI-NEXT:    v_cvt_f16_f32_e32 v12, v12
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v12
; SI-NEXT:    v_or_b32_e32 v12, v13, v12
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v14
; SI-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:84 ; 4-byte Folded Reload
; SI-NEXT:    v_or_b32_e32 v13, v15, v13
; SI-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:80 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(3)
; SI-NEXT:    v_cvt_f32_f16_e32 v17, v17
; SI-NEXT:    s_waitcnt vmcnt(2)
; SI-NEXT:    v_cvt_f32_f16_e32 v20, v20
; SI-NEXT:    v_add_f32_e32 v17, 0x38000000, v17
; SI-NEXT:    v_cvt_f16_f32_e32 v17, v17
; SI-NEXT:    v_add_f32_e32 v20, 0x38000000, v20
; SI-NEXT:    v_cvt_f16_f32_e32 v20, v20
; SI-NEXT:    s_waitcnt vmcnt(1)
; SI-NEXT:    v_cvt_f32_f16_e32 v14, v14
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_cvt_f32_f16_e32 v15, v15
; SI-NEXT:    v_add_f32_e32 v14, 0x38000000, v14
; SI-NEXT:    v_cvt_f16_f32_e32 v14, v14
; SI-NEXT:    v_add_f32_e32 v15, 0x38000000, v15
; SI-NEXT:    v_cvt_f16_f32_e32 v15, v15
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v14
; SI-NEXT:    v_or_b32_e32 v14, v16, v14
; SI-NEXT:    v_cvt_f32_f16_e32 v16, v36
; SI-NEXT:    v_lshlrev_b32_e32 v15, 16, v15
; SI-NEXT:    v_add_f32_e32 v16, 0x38000000, v16
; SI-NEXT:    v_cvt_f16_f32_e32 v16, v16
; SI-NEXT:    v_or_b32_e32 v15, v16, v15
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v17
; SI-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:72 ; 4-byte Folded Reload
; SI-NEXT:    v_or_b32_e32 v16, v18, v16
; SI-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(1)
; SI-NEXT:    v_cvt_f32_f16_e32 v17, v17
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_cvt_f32_f16_e32 v18, v18
; SI-NEXT:    v_add_f32_e32 v17, 0x38000000, v17
; SI-NEXT:    v_cvt_f16_f32_e32 v17, v17
; SI-NEXT:    v_add_f32_e32 v18, 0x38000000, v18
; SI-NEXT:    v_cvt_f16_f32_e32 v18, v18
; SI-NEXT:    v_lshlrev_b32_e32 v17, 16, v17
; SI-NEXT:    v_or_b32_e32 v17, v19, v17
; SI-NEXT:    v_cvt_f32_f16_e32 v19, v33
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v18
; SI-NEXT:    v_add_f32_e32 v19, 0x38000000, v19
; SI-NEXT:    v_cvt_f16_f32_e32 v19, v19
; SI-NEXT:    v_or_b32_e32 v18, v19, v18
; SI-NEXT:    v_lshlrev_b32_e32 v19, 16, v20
; SI-NEXT:    v_or_b32_e32 v19, v21, v19
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:  .LBB46_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    buffer_load_dword v63, off, s[0:3], s32 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0)
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v40f16_to_v10i64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; VI-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; VI-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; VI-NEXT:    buffer_store_dword v43, off, s[0:3], s32 ; 4-byte Folded Spill
; VI-NEXT:    v_mov_b32_e32 v32, v19
; VI-NEXT:    v_mov_b32_e32 v33, v18
; VI-NEXT:    v_mov_b32_e32 v34, v17
; VI-NEXT:    v_mov_b32_e32 v35, v16
; VI-NEXT:    v_mov_b32_e32 v36, v15
; VI-NEXT:    v_mov_b32_e32 v37, v14
; VI-NEXT:    v_mov_b32_e32 v38, v13
; VI-NEXT:    v_mov_b32_e32 v39, v12
; VI-NEXT:    v_mov_b32_e32 v48, v11
; VI-NEXT:    v_mov_b32_e32 v49, v10
; VI-NEXT:    v_mov_b32_e32 v50, v9
; VI-NEXT:    v_mov_b32_e32 v51, v8
; VI-NEXT:    v_mov_b32_e32 v52, v7
; VI-NEXT:    v_mov_b32_e32 v53, v6
; VI-NEXT:    v_mov_b32_e32 v54, v5
; VI-NEXT:    v_mov_b32_e32 v55, v4
; VI-NEXT:    v_mov_b32_e32 v40, v3
; VI-NEXT:    v_mov_b32_e32 v41, v2
; VI-NEXT:    v_mov_b32_e32 v42, v1
; VI-NEXT:    v_mov_b32_e32 v43, v0
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB46_2
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_mov_b32_e32 v19, 16
; VI-NEXT:    v_lshlrev_b32_sdwa v0, v19, v43 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v1, v19, v42 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v2, v19, v41 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v3, v19, v40 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v4, v19, v55 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v5, v19, v54 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v6, v19, v53 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v7, v19, v52 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v8, v19, v51 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v9, v19, v50 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v10, v19, v49 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v11, v19, v48 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v12, v19, v39 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v13, v19, v38 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v14, v19, v37 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v15, v19, v36 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v16, v19, v35 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v17, v19, v34 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v18, v19, v33 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v19, v19, v32 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_or_b32_sdwa v0, v43, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v1, v42, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v2, v41, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v3, v40, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v4, v55, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v5, v54, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v6, v53, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v7, v52, v7 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v8, v51, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v9, v50, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v10, v49, v10 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v11, v48, v11 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v12, v39, v12 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v13, v38, v13 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v14, v37, v14 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v15, v36, v15 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v16, v35, v16 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v17, v34, v17 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v18, v33, v18 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v19, v32, v19 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr43
; VI-NEXT:    ; implicit-def: $vgpr42
; VI-NEXT:    ; implicit-def: $vgpr41
; VI-NEXT:    ; implicit-def: $vgpr40
; VI-NEXT:    ; implicit-def: $vgpr55
; VI-NEXT:    ; implicit-def: $vgpr54
; VI-NEXT:    ; implicit-def: $vgpr53
; VI-NEXT:    ; implicit-def: $vgpr52
; VI-NEXT:    ; implicit-def: $vgpr51
; VI-NEXT:    ; implicit-def: $vgpr50
; VI-NEXT:    ; implicit-def: $vgpr49
; VI-NEXT:    ; implicit-def: $vgpr48
; VI-NEXT:    ; implicit-def: $vgpr39
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr35
; VI-NEXT:    ; implicit-def: $vgpr34
; VI-NEXT:    ; implicit-def: $vgpr33
; VI-NEXT:    ; implicit-def: $vgpr32
; VI-NEXT:  .LBB46_2: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB46_4
; VI-NEXT:  ; %bb.3: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v19, 0x200
; VI-NEXT:    v_add_f16_sdwa v0, v43, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v1, 0x200, v43
; VI-NEXT:    v_or_b32_e32 v0, v1, v0
; VI-NEXT:    v_add_f16_sdwa v1, v42, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, 0x200, v42
; VI-NEXT:    v_or_b32_e32 v1, v2, v1
; VI-NEXT:    v_add_f16_sdwa v2, v41, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v3, 0x200, v41
; VI-NEXT:    v_or_b32_e32 v2, v3, v2
; VI-NEXT:    v_add_f16_sdwa v3, v40, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v4, 0x200, v40
; VI-NEXT:    v_or_b32_e32 v3, v4, v3
; VI-NEXT:    v_add_f16_sdwa v4, v55, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v5, 0x200, v55
; VI-NEXT:    v_or_b32_e32 v4, v5, v4
; VI-NEXT:    v_add_f16_sdwa v5, v54, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v6, 0x200, v54
; VI-NEXT:    v_or_b32_e32 v5, v6, v5
; VI-NEXT:    v_add_f16_sdwa v6, v53, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v7, 0x200, v53
; VI-NEXT:    v_or_b32_e32 v6, v7, v6
; VI-NEXT:    v_add_f16_sdwa v7, v52, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v8, 0x200, v52
; VI-NEXT:    v_or_b32_e32 v7, v8, v7
; VI-NEXT:    v_add_f16_sdwa v8, v51, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v9, 0x200, v51
; VI-NEXT:    v_or_b32_e32 v8, v9, v8
; VI-NEXT:    v_add_f16_sdwa v9, v50, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v10, 0x200, v50
; VI-NEXT:    v_or_b32_e32 v9, v10, v9
; VI-NEXT:    v_add_f16_sdwa v10, v49, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v11, 0x200, v49
; VI-NEXT:    v_or_b32_e32 v10, v11, v10
; VI-NEXT:    v_add_f16_sdwa v11, v48, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v12, 0x200, v48
; VI-NEXT:    v_or_b32_e32 v11, v12, v11
; VI-NEXT:    v_add_f16_sdwa v12, v39, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v13, 0x200, v39
; VI-NEXT:    v_or_b32_e32 v12, v13, v12
; VI-NEXT:    v_add_f16_sdwa v13, v38, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v14, 0x200, v38
; VI-NEXT:    v_or_b32_e32 v13, v14, v13
; VI-NEXT:    v_add_f16_sdwa v14, v37, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v15, 0x200, v37
; VI-NEXT:    v_or_b32_e32 v14, v15, v14
; VI-NEXT:    v_add_f16_sdwa v15, v36, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v16, 0x200, v36
; VI-NEXT:    v_or_b32_e32 v15, v16, v15
; VI-NEXT:    v_add_f16_sdwa v16, v35, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v17, 0x200, v35
; VI-NEXT:    v_or_b32_e32 v16, v17, v16
; VI-NEXT:    v_add_f16_sdwa v17, v34, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v18, 0x200, v34
; VI-NEXT:    v_or_b32_e32 v17, v18, v17
; VI-NEXT:    v_add_f16_sdwa v18, v33, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v20, 0x200, v33
; VI-NEXT:    v_or_b32_e32 v18, v20, v18
; VI-NEXT:    v_add_f16_sdwa v19, v32, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v20, 0x200, v32
; VI-NEXT:    v_or_b32_e32 v19, v20, v19
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:  .LBB46_4: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    buffer_load_dword v43, off, s[0:3], s32 ; 4-byte Folded Reload
; VI-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; VI-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; VI-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v40f16_to_v10i64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v63, off, s[0:3], s32 ; 4-byte Folded Spill
; GFX9-NEXT:    v_mov_b32_e32 v32, v19
; GFX9-NEXT:    v_mov_b32_e32 v33, v18
; GFX9-NEXT:    v_mov_b32_e32 v43, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v32
; GFX9-NEXT:    v_mov_b32_e32 v34, v17
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:64 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v33
; GFX9-NEXT:    v_mov_b32_e32 v35, v16
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:68 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v34
; GFX9-NEXT:    v_mov_b32_e32 v36, v15
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:72 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v35
; GFX9-NEXT:    v_mov_b32_e32 v37, v14
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:76 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v36
; GFX9-NEXT:    v_mov_b32_e32 v38, v13
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:80 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v37
; GFX9-NEXT:    v_mov_b32_e32 v39, v12
; GFX9-NEXT:    v_mov_b32_e32 v48, v11
; GFX9-NEXT:    v_mov_b32_e32 v49, v10
; GFX9-NEXT:    v_mov_b32_e32 v50, v9
; GFX9-NEXT:    v_mov_b32_e32 v51, v8
; GFX9-NEXT:    v_mov_b32_e32 v52, v7
; GFX9-NEXT:    v_mov_b32_e32 v53, v6
; GFX9-NEXT:    v_mov_b32_e32 v54, v5
; GFX9-NEXT:    v_mov_b32_e32 v55, v4
; GFX9-NEXT:    v_mov_b32_e32 v40, v3
; GFX9-NEXT:    v_mov_b32_e32 v41, v2
; GFX9-NEXT:    v_mov_b32_e32 v42, v1
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:84 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v38
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:88 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v39
; GFX9-NEXT:    v_lshrrev_b32_e32 v60, 16, v48
; GFX9-NEXT:    v_lshrrev_b32_e32 v61, 16, v49
; GFX9-NEXT:    v_lshrrev_b32_e32 v62, 16, v50
; GFX9-NEXT:    v_lshrrev_b32_e32 v63, 16, v51
; GFX9-NEXT:    v_lshrrev_b32_e32 v44, 16, v52
; GFX9-NEXT:    v_lshrrev_b32_e32 v45, 16, v53
; GFX9-NEXT:    v_lshrrev_b32_e32 v46, 16, v54
; GFX9-NEXT:    v_lshrrev_b32_e32 v47, 16, v55
; GFX9-NEXT:    v_lshrrev_b32_e32 v56, 16, v40
; GFX9-NEXT:    v_lshrrev_b32_e32 v57, 16, v41
; GFX9-NEXT:    v_lshrrev_b32_e32 v58, 16, v42
; GFX9-NEXT:    v_lshrrev_b32_e32 v59, 16, v43
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:92 ; 4-byte Folded Spill
; GFX9-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB46_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_mov_b32 s6, 0x5040100
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v12, 16, v39
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v13, 16, v38
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v14, 16, v37
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v15, 16, v36
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v16, 16, v35
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v17, 16, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v18, 16, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v19, 16, v32
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    v_perm_b32 v0, v59, v43, s6
; GFX9-NEXT:    v_perm_b32 v1, v58, v42, s6
; GFX9-NEXT:    v_perm_b32 v2, v57, v41, s6
; GFX9-NEXT:    v_perm_b32 v3, v56, v40, s6
; GFX9-NEXT:    v_perm_b32 v4, v47, v55, s6
; GFX9-NEXT:    v_perm_b32 v5, v46, v54, s6
; GFX9-NEXT:    v_perm_b32 v6, v45, v53, s6
; GFX9-NEXT:    v_perm_b32 v7, v44, v52, s6
; GFX9-NEXT:    v_perm_b32 v8, v63, v51, s6
; GFX9-NEXT:    v_perm_b32 v9, v62, v50, s6
; GFX9-NEXT:    v_perm_b32 v10, v61, v49, s6
; GFX9-NEXT:    v_perm_b32 v11, v60, v48, s6
; GFX9-NEXT:    v_perm_b32 v12, v12, v39, s6
; GFX9-NEXT:    v_perm_b32 v13, v13, v38, s6
; GFX9-NEXT:    v_perm_b32 v14, v14, v37, s6
; GFX9-NEXT:    v_perm_b32 v15, v15, v36, s6
; GFX9-NEXT:    v_perm_b32 v16, v16, v35, s6
; GFX9-NEXT:    v_perm_b32 v17, v17, v34, s6
; GFX9-NEXT:    v_perm_b32 v18, v18, v33, s6
; GFX9-NEXT:    v_perm_b32 v19, v19, v32, s6
; GFX9-NEXT:    ; implicit-def: $vgpr43
; GFX9-NEXT:    ; implicit-def: $vgpr42
; GFX9-NEXT:    ; implicit-def: $vgpr41
; GFX9-NEXT:    ; implicit-def: $vgpr40
; GFX9-NEXT:    ; implicit-def: $vgpr55
; GFX9-NEXT:    ; implicit-def: $vgpr54
; GFX9-NEXT:    ; implicit-def: $vgpr53
; GFX9-NEXT:    ; implicit-def: $vgpr52
; GFX9-NEXT:    ; implicit-def: $vgpr51
; GFX9-NEXT:    ; implicit-def: $vgpr50
; GFX9-NEXT:    ; implicit-def: $vgpr49
; GFX9-NEXT:    ; implicit-def: $vgpr48
; GFX9-NEXT:    ; implicit-def: $vgpr39
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr35
; GFX9-NEXT:    ; implicit-def: $vgpr34
; GFX9-NEXT:    ; implicit-def: $vgpr33
; GFX9-NEXT:    ; implicit-def: $vgpr32
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr60
; GFX9-NEXT:    ; implicit-def: $vgpr61
; GFX9-NEXT:    ; implicit-def: $vgpr62
; GFX9-NEXT:    ; implicit-def: $vgpr63
; GFX9-NEXT:    ; implicit-def: $vgpr44
; GFX9-NEXT:    ; implicit-def: $vgpr45
; GFX9-NEXT:    ; implicit-def: $vgpr46
; GFX9-NEXT:    ; implicit-def: $vgpr47
; GFX9-NEXT:    ; implicit-def: $vgpr56
; GFX9-NEXT:    ; implicit-def: $vgpr57
; GFX9-NEXT:    ; implicit-def: $vgpr58
; GFX9-NEXT:    ; implicit-def: $vgpr59
; GFX9-NEXT:  .LBB46_2: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB46_4
; GFX9-NEXT:  ; %bb.3: ; %cmp.true
; GFX9-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:92 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:88 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:84 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:80 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:76 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:72 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; GFX9-NEXT:    s_mov_b32 s6, 0x5040100
; GFX9-NEXT:    v_perm_b32 v0, v59, v43, s6
; GFX9-NEXT:    s_movk_i32 s7, 0x200
; GFX9-NEXT:    v_perm_b32 v1, v58, v42, s6
; GFX9-NEXT:    v_perm_b32 v2, v57, v41, s6
; GFX9-NEXT:    v_perm_b32 v3, v56, v40, s6
; GFX9-NEXT:    v_perm_b32 v4, v47, v55, s6
; GFX9-NEXT:    v_perm_b32 v5, v46, v54, s6
; GFX9-NEXT:    v_perm_b32 v6, v45, v53, s6
; GFX9-NEXT:    v_perm_b32 v7, v44, v52, s6
; GFX9-NEXT:    v_perm_b32 v8, v63, v51, s6
; GFX9-NEXT:    v_perm_b32 v9, v62, v50, s6
; GFX9-NEXT:    v_perm_b32 v10, v61, v49, s6
; GFX9-NEXT:    v_perm_b32 v11, v60, v48, s6
; GFX9-NEXT:    v_pk_add_f16 v0, v0, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v1, v1, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v2, v2, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v3, v3, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v4, v4, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v5, v5, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, v6, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v7, v7, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v8, v8, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v9, v9, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v10, v10, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v11, v11, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_waitcnt vmcnt(7)
; GFX9-NEXT:    v_perm_b32 v12, v12, v39, s6
; GFX9-NEXT:    s_waitcnt vmcnt(6)
; GFX9-NEXT:    v_perm_b32 v13, v13, v38, s6
; GFX9-NEXT:    s_waitcnt vmcnt(5)
; GFX9-NEXT:    v_perm_b32 v14, v14, v37, s6
; GFX9-NEXT:    s_waitcnt vmcnt(4)
; GFX9-NEXT:    v_perm_b32 v15, v15, v36, s6
; GFX9-NEXT:    s_waitcnt vmcnt(3)
; GFX9-NEXT:    v_perm_b32 v16, v16, v35, s6
; GFX9-NEXT:    s_waitcnt vmcnt(2)
; GFX9-NEXT:    v_perm_b32 v17, v17, v34, s6
; GFX9-NEXT:    s_waitcnt vmcnt(1)
; GFX9-NEXT:    v_perm_b32 v18, v18, v33, s6
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    v_perm_b32 v19, v19, v32, s6
; GFX9-NEXT:    v_pk_add_f16 v12, v12, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v13, v13, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v14, v14, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v15, v15, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v16, v16, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v17, v17, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v18, v18, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v19, v19, s7 op_sel_hi:[1,0]
; GFX9-NEXT:  .LBB46_4: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    buffer_load_dword v63, off, s[0:3], s32 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Reload
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v40f16_to_v10i64:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB46_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB46_4
; GFX11-TRUE16-NEXT:  .LBB46_2: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB46_3: ; %cmp.false
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB46_2
; GFX11-TRUE16-NEXT:  .LBB46_4: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v0, 0x200, v0 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v1, 0x200, v1 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v2, 0x200, v2 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v3, 0x200, v3 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v4, 0x200, v4 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v5, 0x200, v5 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v6, 0x200, v6 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v7, 0x200, v7 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v8, 0x200, v8 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v9, 0x200, v9 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v10, 0x200, v10 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v11, 0x200, v11 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v12, 0x200, v12 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v13, 0x200, v13 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v14, 0x200, v14 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v15, 0x200, v15 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v16, 0x200, v16 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v17, 0x200, v17 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v18, 0x200, v18 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v19, 0x200, v19 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v40f16_to_v10i64:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v48, 16, v3
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v20
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v37, v0, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v38, v1, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v39, v2, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v48, v3, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v36, v4, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v35, v5, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v34, v6, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v33, v7, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, v32, v8, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, v31, v9, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, v30, v10, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, v29, v11, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, v28, v12, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, v27, v13, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v14, v26, v14, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v15, v25, v15, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v16, v24, v16, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v17, v23, v17, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v18, v22, v18, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v19, v21, v19, 0x5040100
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB46_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB46_4
; GFX11-FAKE16-NEXT:  .LBB46_2: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB46_3: ; %cmp.false
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB46_2
; GFX11-FAKE16-NEXT:  .LBB46_4: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v0, 0x200, v0 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v1, 0x200, v1 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v2, 0x200, v2 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v3, 0x200, v3 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v4, 0x200, v4 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v5, 0x200, v5 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v6, 0x200, v6 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v7, 0x200, v7 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v8, 0x200, v8 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v9, 0x200, v9 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v10, 0x200, v10 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v11, 0x200, v11 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v12, 0x200, v12 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v13, 0x200, v13 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v14, 0x200, v14 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v15, 0x200, v15 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v16, 0x200, v16 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v17, 0x200, v17 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v18, 0x200, v18 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v19, 0x200, v19 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <40 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <40 x half> %a1 to <10 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <40 x half> %a to <10 x i64>
  br label %end

end:
  %phi = phi <10 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <10 x i64> %phi
}

define inreg <10 x i64> @bitcast_v40f16_to_v10i64_scalar(<40 x half> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v40f16_to_v10i64_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_writelane_b32 v32, s36, 0
; SI-NEXT:    v_writelane_b32 v32, s37, 1
; SI-NEXT:    v_writelane_b32 v32, s38, 2
; SI-NEXT:    v_writelane_b32 v32, s39, 3
; SI-NEXT:    v_writelane_b32 v32, s48, 4
; SI-NEXT:    v_writelane_b32 v32, s49, 5
; SI-NEXT:    v_writelane_b32 v32, s50, 6
; SI-NEXT:    v_writelane_b32 v32, s51, 7
; SI-NEXT:    v_writelane_b32 v32, s52, 8
; SI-NEXT:    v_writelane_b32 v32, s53, 9
; SI-NEXT:    v_writelane_b32 v32, s54, 10
; SI-NEXT:    v_writelane_b32 v32, s55, 11
; SI-NEXT:    v_writelane_b32 v32, s64, 12
; SI-NEXT:    v_writelane_b32 v32, s65, 13
; SI-NEXT:    v_writelane_b32 v32, s66, 14
; SI-NEXT:    v_writelane_b32 v32, s67, 15
; SI-NEXT:    v_readfirstlane_b32 s6, v5
; SI-NEXT:    v_readfirstlane_b32 s8, v4
; SI-NEXT:    v_readfirstlane_b32 s10, v3
; SI-NEXT:    v_readfirstlane_b32 s12, v2
; SI-NEXT:    v_readfirstlane_b32 s14, v1
; SI-NEXT:    v_readfirstlane_b32 s73, v0
; SI-NEXT:    s_lshr_b32 s72, s29, 16
; SI-NEXT:    s_lshr_b32 s75, s28, 16
; SI-NEXT:    s_lshr_b32 s76, s27, 16
; SI-NEXT:    s_lshr_b32 s77, s26, 16
; SI-NEXT:    s_lshr_b32 s78, s25, 16
; SI-NEXT:    s_lshr_b32 s79, s24, 16
; SI-NEXT:    s_lshr_b32 s88, s23, 16
; SI-NEXT:    s_lshr_b32 s89, s22, 16
; SI-NEXT:    s_lshr_b32 s90, s21, 16
; SI-NEXT:    s_lshr_b32 s91, s20, 16
; SI-NEXT:    s_lshr_b32 s92, s19, 16
; SI-NEXT:    s_lshr_b32 s93, s18, 16
; SI-NEXT:    s_lshr_b32 s94, s17, 16
; SI-NEXT:    s_lshr_b32 s95, s16, 16
; SI-NEXT:    s_lshr_b32 s7, s6, 16
; SI-NEXT:    s_lshr_b32 s9, s8, 16
; SI-NEXT:    s_lshr_b32 s11, s10, 16
; SI-NEXT:    s_lshr_b32 s13, s12, 16
; SI-NEXT:    s_lshr_b32 s15, s14, 16
; SI-NEXT:    s_lshr_b32 s74, s73, 16
; SI-NEXT:    v_readfirstlane_b32 s4, v6
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    s_cbranch_scc0 .LBB47_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s95, 16
; SI-NEXT:    s_or_b32 s36, s4, s5
; SI-NEXT:    s_and_b32 s4, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s94, 16
; SI-NEXT:    s_or_b32 s37, s4, s5
; SI-NEXT:    s_and_b32 s4, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s93, 16
; SI-NEXT:    s_or_b32 s38, s4, s5
; SI-NEXT:    s_and_b32 s4, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s92, 16
; SI-NEXT:    s_or_b32 s39, s4, s5
; SI-NEXT:    s_and_b32 s4, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s91, 16
; SI-NEXT:    s_or_b32 s40, s4, s5
; SI-NEXT:    s_and_b32 s4, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s90, 16
; SI-NEXT:    s_or_b32 s41, s4, s5
; SI-NEXT:    s_and_b32 s4, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s89, 16
; SI-NEXT:    s_or_b32 s42, s4, s5
; SI-NEXT:    s_and_b32 s4, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s88, 16
; SI-NEXT:    s_or_b32 s43, s4, s5
; SI-NEXT:    s_and_b32 s4, s24, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s79, 16
; SI-NEXT:    s_or_b32 s44, s4, s5
; SI-NEXT:    s_and_b32 s4, s25, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s78, 16
; SI-NEXT:    s_or_b32 s45, s4, s5
; SI-NEXT:    s_and_b32 s4, s26, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s77, 16
; SI-NEXT:    s_or_b32 s46, s4, s5
; SI-NEXT:    s_and_b32 s4, s27, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s76, 16
; SI-NEXT:    s_or_b32 s47, s4, s5
; SI-NEXT:    s_and_b32 s4, s28, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s75, 16
; SI-NEXT:    s_or_b32 s48, s4, s5
; SI-NEXT:    s_and_b32 s4, s29, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s72, 16
; SI-NEXT:    s_or_b32 s49, s4, s5
; SI-NEXT:    s_and_b32 s4, s73, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s74, 16
; SI-NEXT:    s_or_b32 s50, s4, s5
; SI-NEXT:    s_and_b32 s4, s14, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s15, 16
; SI-NEXT:    s_or_b32 s51, s4, s5
; SI-NEXT:    s_and_b32 s4, s12, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s13, 16
; SI-NEXT:    s_or_b32 s52, s4, s5
; SI-NEXT:    s_and_b32 s4, s10, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s11, 16
; SI-NEXT:    s_or_b32 s53, s4, s5
; SI-NEXT:    s_and_b32 s4, s8, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s9, 16
; SI-NEXT:    s_or_b32 s54, s4, s5
; SI-NEXT:    s_and_b32 s4, s6, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s7, 16
; SI-NEXT:    s_or_b32 s55, s4, s5
; SI-NEXT:    ; implicit-def: $sgpr56
; SI-NEXT:    ; implicit-def: $sgpr57
; SI-NEXT:    ; implicit-def: $sgpr58
; SI-NEXT:    ; implicit-def: $sgpr59
; SI-NEXT:    ; implicit-def: $sgpr60
; SI-NEXT:    ; implicit-def: $sgpr61
; SI-NEXT:    ; implicit-def: $sgpr62
; SI-NEXT:    ; implicit-def: $sgpr63
; SI-NEXT:    ; implicit-def: $sgpr64
; SI-NEXT:    ; implicit-def: $sgpr65
; SI-NEXT:    ; implicit-def: $sgpr66
; SI-NEXT:    ; implicit-def: $sgpr67
; SI-NEXT:    s_cbranch_execnz .LBB47_4
; SI-NEXT:  .LBB47_2: ; %cmp.true
; SI-NEXT:    v_cvt_f32_f16_e32 v0, s95
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s16
; SI-NEXT:    v_cvt_f32_f16_e32 v2, s94
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s17
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_cvt_f32_f16_e32 v4, s18
; SI-NEXT:    v_or_b32_e32 v0, v1, v0
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v2, s93
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_or_b32_e32 v1, v3, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s92
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_or_b32_e32 v2, v4, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v4, s19
; SI-NEXT:    v_cvt_f32_f16_e32 v5, s91
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v6, s20
; SI-NEXT:    v_or_b32_e32 v3, v4, v3
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v5, s90
; SI-NEXT:    v_cvt_f32_f16_e32 v7, s21
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_or_b32_e32 v4, v6, v4
; SI-NEXT:    v_cvt_f32_f16_e32 v6, s89
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_or_b32_e32 v5, v7, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v7, s22
; SI-NEXT:    v_cvt_f32_f16_e32 v8, s88
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v8, v8
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_cvt_f32_f16_e32 v9, s23
; SI-NEXT:    v_or_b32_e32 v6, v7, v6
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v8
; SI-NEXT:    v_cvt_f32_f16_e32 v8, s79
; SI-NEXT:    v_cvt_f32_f16_e32 v10, s24
; SI-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v9
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v8, v8
; SI-NEXT:    v_add_f32_e32 v10, 0x38000000, v10
; SI-NEXT:    v_cvt_f16_f32_e32 v10, v10
; SI-NEXT:    v_or_b32_e32 v7, v9, v7
; SI-NEXT:    v_cvt_f32_f16_e32 v9, s78
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_or_b32_e32 v8, v10, v8
; SI-NEXT:    v_cvt_f32_f16_e32 v10, s25
; SI-NEXT:    v_cvt_f32_f16_e32 v11, s77
; SI-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v9
; SI-NEXT:    v_add_f32_e32 v10, 0x38000000, v10
; SI-NEXT:    v_add_f32_e32 v11, 0x38000000, v11
; SI-NEXT:    v_cvt_f16_f32_e32 v10, v10
; SI-NEXT:    v_cvt_f16_f32_e32 v11, v11
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; SI-NEXT:    v_cvt_f32_f16_e32 v12, s26
; SI-NEXT:    v_or_b32_e32 v9, v10, v9
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v11
; SI-NEXT:    v_cvt_f32_f16_e32 v11, s76
; SI-NEXT:    v_cvt_f32_f16_e32 v13, s27
; SI-NEXT:    v_add_f32_e32 v12, 0x38000000, v12
; SI-NEXT:    v_cvt_f16_f32_e32 v12, v12
; SI-NEXT:    v_add_f32_e32 v11, 0x38000000, v11
; SI-NEXT:    v_cvt_f16_f32_e32 v11, v11
; SI-NEXT:    v_add_f32_e32 v13, 0x38000000, v13
; SI-NEXT:    v_cvt_f16_f32_e32 v13, v13
; SI-NEXT:    v_or_b32_e32 v10, v12, v10
; SI-NEXT:    v_cvt_f32_f16_e32 v12, s75
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; SI-NEXT:    v_or_b32_e32 v11, v13, v11
; SI-NEXT:    v_cvt_f32_f16_e32 v13, s28
; SI-NEXT:    v_cvt_f32_f16_e32 v14, s72
; SI-NEXT:    v_add_f32_e32 v12, 0x38000000, v12
; SI-NEXT:    v_cvt_f16_f32_e32 v12, v12
; SI-NEXT:    v_add_f32_e32 v13, 0x38000000, v13
; SI-NEXT:    v_add_f32_e32 v14, 0x38000000, v14
; SI-NEXT:    v_cvt_f16_f32_e32 v13, v13
; SI-NEXT:    v_cvt_f16_f32_e32 v14, v14
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v12
; SI-NEXT:    v_cvt_f32_f16_e32 v15, s29
; SI-NEXT:    v_or_b32_e32 v12, v13, v12
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v14
; SI-NEXT:    v_cvt_f32_f16_e32 v14, s74
; SI-NEXT:    v_cvt_f32_f16_e32 v16, s73
; SI-NEXT:    v_add_f32_e32 v15, 0x38000000, v15
; SI-NEXT:    v_cvt_f16_f32_e32 v15, v15
; SI-NEXT:    v_add_f32_e32 v14, 0x38000000, v14
; SI-NEXT:    v_cvt_f16_f32_e32 v14, v14
; SI-NEXT:    v_add_f32_e32 v16, 0x38000000, v16
; SI-NEXT:    v_cvt_f16_f32_e32 v16, v16
; SI-NEXT:    v_or_b32_e32 v13, v15, v13
; SI-NEXT:    v_cvt_f32_f16_e32 v15, s15
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v14
; SI-NEXT:    v_or_b32_e32 v14, v16, v14
; SI-NEXT:    v_cvt_f32_f16_e32 v16, s14
; SI-NEXT:    v_cvt_f32_f16_e32 v17, s13
; SI-NEXT:    v_add_f32_e32 v15, 0x38000000, v15
; SI-NEXT:    v_cvt_f16_f32_e32 v15, v15
; SI-NEXT:    v_add_f32_e32 v16, 0x38000000, v16
; SI-NEXT:    v_add_f32_e32 v17, 0x38000000, v17
; SI-NEXT:    v_cvt_f16_f32_e32 v16, v16
; SI-NEXT:    v_cvt_f16_f32_e32 v17, v17
; SI-NEXT:    v_lshlrev_b32_e32 v15, 16, v15
; SI-NEXT:    v_cvt_f32_f16_e32 v18, s12
; SI-NEXT:    v_or_b32_e32 v15, v16, v15
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v17
; SI-NEXT:    v_cvt_f32_f16_e32 v17, s11
; SI-NEXT:    v_cvt_f32_f16_e32 v19, s10
; SI-NEXT:    v_add_f32_e32 v18, 0x38000000, v18
; SI-NEXT:    v_cvt_f16_f32_e32 v18, v18
; SI-NEXT:    v_add_f32_e32 v17, 0x38000000, v17
; SI-NEXT:    v_cvt_f16_f32_e32 v17, v17
; SI-NEXT:    v_add_f32_e32 v19, 0x38000000, v19
; SI-NEXT:    v_cvt_f16_f32_e32 v19, v19
; SI-NEXT:    v_or_b32_e32 v16, v18, v16
; SI-NEXT:    v_cvt_f32_f16_e32 v18, s9
; SI-NEXT:    v_lshlrev_b32_e32 v17, 16, v17
; SI-NEXT:    v_or_b32_e32 v17, v19, v17
; SI-NEXT:    v_cvt_f32_f16_e32 v19, s8
; SI-NEXT:    v_cvt_f32_f16_e32 v20, s7
; SI-NEXT:    v_cvt_f32_f16_e32 v21, s6
; SI-NEXT:    v_add_f32_e32 v18, 0x38000000, v18
; SI-NEXT:    v_cvt_f16_f32_e32 v18, v18
; SI-NEXT:    v_add_f32_e32 v19, 0x38000000, v19
; SI-NEXT:    v_add_f32_e32 v20, 0x38000000, v20
; SI-NEXT:    v_cvt_f16_f32_e32 v19, v19
; SI-NEXT:    v_cvt_f16_f32_e32 v20, v20
; SI-NEXT:    v_add_f32_e32 v21, 0x38000000, v21
; SI-NEXT:    v_cvt_f16_f32_e32 v21, v21
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v18
; SI-NEXT:    v_or_b32_e32 v18, v19, v18
; SI-NEXT:    v_lshlrev_b32_e32 v19, 16, v20
; SI-NEXT:    v_or_b32_e32 v19, v21, v19
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    s_branch .LBB47_5
; SI-NEXT:  .LBB47_3:
; SI-NEXT:    ; implicit-def: $sgpr36_sgpr37_sgpr38_sgpr39_sgpr40_sgpr41_sgpr42_sgpr43_sgpr44_sgpr45_sgpr46_sgpr47_sgpr48_sgpr49_sgpr50_sgpr51_sgpr52_sgpr53_sgpr54_sgpr55_sgpr56_sgpr57_sgpr58_sgpr59_sgpr60_sgpr61_sgpr62_sgpr63_sgpr64_sgpr65_sgpr66_sgpr67
; SI-NEXT:    s_branch .LBB47_2
; SI-NEXT:  .LBB47_4:
; SI-NEXT:    v_mov_b32_e32 v0, s36
; SI-NEXT:    v_mov_b32_e32 v1, s37
; SI-NEXT:    v_mov_b32_e32 v2, s38
; SI-NEXT:    v_mov_b32_e32 v3, s39
; SI-NEXT:    v_mov_b32_e32 v4, s40
; SI-NEXT:    v_mov_b32_e32 v5, s41
; SI-NEXT:    v_mov_b32_e32 v6, s42
; SI-NEXT:    v_mov_b32_e32 v7, s43
; SI-NEXT:    v_mov_b32_e32 v8, s44
; SI-NEXT:    v_mov_b32_e32 v9, s45
; SI-NEXT:    v_mov_b32_e32 v10, s46
; SI-NEXT:    v_mov_b32_e32 v11, s47
; SI-NEXT:    v_mov_b32_e32 v12, s48
; SI-NEXT:    v_mov_b32_e32 v13, s49
; SI-NEXT:    v_mov_b32_e32 v14, s50
; SI-NEXT:    v_mov_b32_e32 v15, s51
; SI-NEXT:    v_mov_b32_e32 v16, s52
; SI-NEXT:    v_mov_b32_e32 v17, s53
; SI-NEXT:    v_mov_b32_e32 v18, s54
; SI-NEXT:    v_mov_b32_e32 v19, s55
; SI-NEXT:    v_mov_b32_e32 v20, s56
; SI-NEXT:    v_mov_b32_e32 v21, s57
; SI-NEXT:    v_mov_b32_e32 v22, s58
; SI-NEXT:    v_mov_b32_e32 v23, s59
; SI-NEXT:    v_mov_b32_e32 v24, s60
; SI-NEXT:    v_mov_b32_e32 v25, s61
; SI-NEXT:    v_mov_b32_e32 v26, s62
; SI-NEXT:    v_mov_b32_e32 v27, s63
; SI-NEXT:    v_mov_b32_e32 v28, s64
; SI-NEXT:    v_mov_b32_e32 v29, s65
; SI-NEXT:    v_mov_b32_e32 v30, s66
; SI-NEXT:    v_mov_b32_e32 v31, s67
; SI-NEXT:  .LBB47_5: ; %end
; SI-NEXT:    v_readlane_b32 s67, v32, 15
; SI-NEXT:    v_readlane_b32 s66, v32, 14
; SI-NEXT:    v_readlane_b32 s65, v32, 13
; SI-NEXT:    v_readlane_b32 s64, v32, 12
; SI-NEXT:    v_readlane_b32 s55, v32, 11
; SI-NEXT:    v_readlane_b32 s54, v32, 10
; SI-NEXT:    v_readlane_b32 s53, v32, 9
; SI-NEXT:    v_readlane_b32 s52, v32, 8
; SI-NEXT:    v_readlane_b32 s51, v32, 7
; SI-NEXT:    v_readlane_b32 s50, v32, 6
; SI-NEXT:    v_readlane_b32 s49, v32, 5
; SI-NEXT:    v_readlane_b32 s48, v32, 4
; SI-NEXT:    v_readlane_b32 s39, v32, 3
; SI-NEXT:    v_readlane_b32 s38, v32, 2
; SI-NEXT:    v_readlane_b32 s37, v32, 1
; SI-NEXT:    v_readlane_b32 s36, v32, 0
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v40f16_to_v10i64_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    v_writelane_b32 v32, s34, 0
; VI-NEXT:    v_writelane_b32 v32, s35, 1
; VI-NEXT:    v_writelane_b32 v32, s36, 2
; VI-NEXT:    v_writelane_b32 v32, s37, 3
; VI-NEXT:    v_writelane_b32 v32, s38, 4
; VI-NEXT:    v_writelane_b32 v32, s39, 5
; VI-NEXT:    v_writelane_b32 v32, s48, 6
; VI-NEXT:    v_writelane_b32 v32, s49, 7
; VI-NEXT:    v_writelane_b32 v32, s50, 8
; VI-NEXT:    v_writelane_b32 v32, s51, 9
; VI-NEXT:    v_writelane_b32 v32, s52, 10
; VI-NEXT:    v_writelane_b32 v32, s53, 11
; VI-NEXT:    v_writelane_b32 v32, s54, 12
; VI-NEXT:    v_writelane_b32 v32, s55, 13
; VI-NEXT:    v_writelane_b32 v32, s64, 14
; VI-NEXT:    v_writelane_b32 v32, s65, 15
; VI-NEXT:    v_writelane_b32 v32, s66, 16
; VI-NEXT:    v_writelane_b32 v32, s67, 17
; VI-NEXT:    v_writelane_b32 v32, s30, 18
; VI-NEXT:    v_writelane_b32 v32, s31, 19
; VI-NEXT:    v_readfirstlane_b32 s6, v5
; VI-NEXT:    v_readfirstlane_b32 s8, v4
; VI-NEXT:    v_readfirstlane_b32 s11, v3
; VI-NEXT:    v_readfirstlane_b32 s14, v2
; VI-NEXT:    v_readfirstlane_b32 s73, v1
; VI-NEXT:    v_readfirstlane_b32 s76, v0
; VI-NEXT:    s_lshr_b32 s10, s29, 16
; VI-NEXT:    s_lshr_b32 s13, s28, 16
; VI-NEXT:    s_lshr_b32 s72, s27, 16
; VI-NEXT:    s_lshr_b32 s74, s26, 16
; VI-NEXT:    s_lshr_b32 s77, s25, 16
; VI-NEXT:    s_lshr_b32 s79, s24, 16
; VI-NEXT:    s_lshr_b32 s88, s23, 16
; VI-NEXT:    s_lshr_b32 s89, s22, 16
; VI-NEXT:    s_lshr_b32 s90, s21, 16
; VI-NEXT:    s_lshr_b32 s91, s20, 16
; VI-NEXT:    s_lshr_b32 s30, s19, 16
; VI-NEXT:    s_lshr_b32 s31, s18, 16
; VI-NEXT:    s_lshr_b32 s34, s17, 16
; VI-NEXT:    s_lshr_b32 s35, s16, 16
; VI-NEXT:    s_lshr_b32 s7, s6, 16
; VI-NEXT:    s_lshr_b32 s9, s8, 16
; VI-NEXT:    s_lshr_b32 s12, s11, 16
; VI-NEXT:    s_lshr_b32 s15, s14, 16
; VI-NEXT:    s_lshr_b32 s75, s73, 16
; VI-NEXT:    s_lshr_b32 s78, s76, 16
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    s_cbranch_scc0 .LBB47_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_and_b32 s4, 0xffff, s16
; VI-NEXT:    s_lshl_b32 s5, s35, 16
; VI-NEXT:    s_or_b32 s36, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s17
; VI-NEXT:    s_lshl_b32 s5, s34, 16
; VI-NEXT:    s_or_b32 s37, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s18
; VI-NEXT:    s_lshl_b32 s5, s31, 16
; VI-NEXT:    s_or_b32 s38, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s19
; VI-NEXT:    s_lshl_b32 s5, s30, 16
; VI-NEXT:    s_or_b32 s39, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s20
; VI-NEXT:    s_lshl_b32 s5, s91, 16
; VI-NEXT:    s_or_b32 s40, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s21
; VI-NEXT:    s_lshl_b32 s5, s90, 16
; VI-NEXT:    s_or_b32 s41, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s22
; VI-NEXT:    s_lshl_b32 s5, s89, 16
; VI-NEXT:    s_or_b32 s42, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s23
; VI-NEXT:    s_lshl_b32 s5, s88, 16
; VI-NEXT:    s_or_b32 s43, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s24
; VI-NEXT:    s_lshl_b32 s5, s79, 16
; VI-NEXT:    s_or_b32 s44, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s25
; VI-NEXT:    s_lshl_b32 s5, s77, 16
; VI-NEXT:    s_or_b32 s45, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s26
; VI-NEXT:    s_lshl_b32 s5, s74, 16
; VI-NEXT:    s_or_b32 s46, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s27
; VI-NEXT:    s_lshl_b32 s5, s72, 16
; VI-NEXT:    s_or_b32 s47, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s28
; VI-NEXT:    s_lshl_b32 s5, s13, 16
; VI-NEXT:    s_or_b32 s48, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s29
; VI-NEXT:    s_lshl_b32 s5, s10, 16
; VI-NEXT:    s_or_b32 s49, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s76
; VI-NEXT:    s_lshl_b32 s5, s78, 16
; VI-NEXT:    s_or_b32 s50, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s73
; VI-NEXT:    s_lshl_b32 s5, s75, 16
; VI-NEXT:    s_or_b32 s51, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s14
; VI-NEXT:    s_lshl_b32 s5, s15, 16
; VI-NEXT:    s_or_b32 s52, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s11
; VI-NEXT:    s_lshl_b32 s5, s12, 16
; VI-NEXT:    s_or_b32 s53, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s8
; VI-NEXT:    s_lshl_b32 s5, s9, 16
; VI-NEXT:    s_or_b32 s54, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s6
; VI-NEXT:    s_lshl_b32 s5, s7, 16
; VI-NEXT:    s_or_b32 s55, s4, s5
; VI-NEXT:    ; implicit-def: $sgpr56
; VI-NEXT:    ; implicit-def: $sgpr57
; VI-NEXT:    ; implicit-def: $sgpr58
; VI-NEXT:    ; implicit-def: $sgpr59
; VI-NEXT:    ; implicit-def: $sgpr60
; VI-NEXT:    ; implicit-def: $sgpr61
; VI-NEXT:    ; implicit-def: $sgpr62
; VI-NEXT:    ; implicit-def: $sgpr63
; VI-NEXT:    ; implicit-def: $sgpr64
; VI-NEXT:    ; implicit-def: $sgpr65
; VI-NEXT:    ; implicit-def: $sgpr66
; VI-NEXT:    ; implicit-def: $sgpr67
; VI-NEXT:    s_cbranch_execnz .LBB47_4
; VI-NEXT:  .LBB47_2: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v19, 0x200
; VI-NEXT:    v_mov_b32_e32 v0, s35
; VI-NEXT:    v_mov_b32_e32 v2, s34
; VI-NEXT:    v_add_f16_sdwa v0, v0, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v1, s16, v19
; VI-NEXT:    v_add_f16_sdwa v2, v2, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v3, s17, v19
; VI-NEXT:    v_or_b32_e32 v0, v1, v0
; VI-NEXT:    v_or_b32_e32 v1, v3, v2
; VI-NEXT:    v_mov_b32_e32 v2, s31
; VI-NEXT:    v_add_f16_sdwa v2, v2, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v3, s18, v19
; VI-NEXT:    v_or_b32_e32 v2, v3, v2
; VI-NEXT:    v_mov_b32_e32 v3, s30
; VI-NEXT:    v_add_f16_sdwa v3, v3, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v4, s19, v19
; VI-NEXT:    v_or_b32_e32 v3, v4, v3
; VI-NEXT:    v_mov_b32_e32 v4, s91
; VI-NEXT:    v_add_f16_sdwa v4, v4, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v5, s20, v19
; VI-NEXT:    v_or_b32_e32 v4, v5, v4
; VI-NEXT:    v_mov_b32_e32 v5, s90
; VI-NEXT:    v_add_f16_sdwa v5, v5, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v6, s21, v19
; VI-NEXT:    v_or_b32_e32 v5, v6, v5
; VI-NEXT:    v_mov_b32_e32 v6, s89
; VI-NEXT:    v_add_f16_sdwa v6, v6, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v7, s22, v19
; VI-NEXT:    v_or_b32_e32 v6, v7, v6
; VI-NEXT:    v_mov_b32_e32 v7, s88
; VI-NEXT:    v_add_f16_sdwa v7, v7, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v8, s23, v19
; VI-NEXT:    v_or_b32_e32 v7, v8, v7
; VI-NEXT:    v_mov_b32_e32 v8, s79
; VI-NEXT:    v_add_f16_sdwa v8, v8, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v9, s24, v19
; VI-NEXT:    v_or_b32_e32 v8, v9, v8
; VI-NEXT:    v_mov_b32_e32 v9, s77
; VI-NEXT:    v_add_f16_sdwa v9, v9, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v10, s25, v19
; VI-NEXT:    v_or_b32_e32 v9, v10, v9
; VI-NEXT:    v_mov_b32_e32 v10, s74
; VI-NEXT:    v_add_f16_sdwa v10, v10, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v11, s26, v19
; VI-NEXT:    v_or_b32_e32 v10, v11, v10
; VI-NEXT:    v_mov_b32_e32 v11, s72
; VI-NEXT:    v_add_f16_sdwa v11, v11, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v12, s27, v19
; VI-NEXT:    v_or_b32_e32 v11, v12, v11
; VI-NEXT:    v_mov_b32_e32 v12, s13
; VI-NEXT:    v_add_f16_sdwa v12, v12, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v13, s28, v19
; VI-NEXT:    v_or_b32_e32 v12, v13, v12
; VI-NEXT:    v_mov_b32_e32 v13, s10
; VI-NEXT:    v_add_f16_sdwa v13, v13, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v14, s29, v19
; VI-NEXT:    v_or_b32_e32 v13, v14, v13
; VI-NEXT:    v_mov_b32_e32 v14, s78
; VI-NEXT:    v_add_f16_sdwa v14, v14, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v15, s76, v19
; VI-NEXT:    v_or_b32_e32 v14, v15, v14
; VI-NEXT:    v_mov_b32_e32 v15, s75
; VI-NEXT:    v_add_f16_sdwa v15, v15, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v16, s73, v19
; VI-NEXT:    v_or_b32_e32 v15, v16, v15
; VI-NEXT:    v_mov_b32_e32 v16, s15
; VI-NEXT:    v_add_f16_sdwa v16, v16, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v17, s14, v19
; VI-NEXT:    v_or_b32_e32 v16, v17, v16
; VI-NEXT:    v_mov_b32_e32 v17, s12
; VI-NEXT:    v_add_f16_sdwa v17, v17, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v18, s11, v19
; VI-NEXT:    v_or_b32_e32 v17, v18, v17
; VI-NEXT:    v_mov_b32_e32 v18, s9
; VI-NEXT:    v_add_f16_sdwa v18, v18, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v20, s8, v19
; VI-NEXT:    v_or_b32_e32 v18, v20, v18
; VI-NEXT:    v_mov_b32_e32 v20, s7
; VI-NEXT:    v_add_f16_sdwa v20, v20, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v19, s6, v19
; VI-NEXT:    v_or_b32_e32 v19, v19, v20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    s_branch .LBB47_5
; VI-NEXT:  .LBB47_3:
; VI-NEXT:    ; implicit-def: $sgpr36_sgpr37_sgpr38_sgpr39_sgpr40_sgpr41_sgpr42_sgpr43_sgpr44_sgpr45_sgpr46_sgpr47_sgpr48_sgpr49_sgpr50_sgpr51_sgpr52_sgpr53_sgpr54_sgpr55_sgpr56_sgpr57_sgpr58_sgpr59_sgpr60_sgpr61_sgpr62_sgpr63_sgpr64_sgpr65_sgpr66_sgpr67
; VI-NEXT:    s_branch .LBB47_2
; VI-NEXT:  .LBB47_4:
; VI-NEXT:    v_mov_b32_e32 v0, s36
; VI-NEXT:    v_mov_b32_e32 v1, s37
; VI-NEXT:    v_mov_b32_e32 v2, s38
; VI-NEXT:    v_mov_b32_e32 v3, s39
; VI-NEXT:    v_mov_b32_e32 v4, s40
; VI-NEXT:    v_mov_b32_e32 v5, s41
; VI-NEXT:    v_mov_b32_e32 v6, s42
; VI-NEXT:    v_mov_b32_e32 v7, s43
; VI-NEXT:    v_mov_b32_e32 v8, s44
; VI-NEXT:    v_mov_b32_e32 v9, s45
; VI-NEXT:    v_mov_b32_e32 v10, s46
; VI-NEXT:    v_mov_b32_e32 v11, s47
; VI-NEXT:    v_mov_b32_e32 v12, s48
; VI-NEXT:    v_mov_b32_e32 v13, s49
; VI-NEXT:    v_mov_b32_e32 v14, s50
; VI-NEXT:    v_mov_b32_e32 v15, s51
; VI-NEXT:    v_mov_b32_e32 v16, s52
; VI-NEXT:    v_mov_b32_e32 v17, s53
; VI-NEXT:    v_mov_b32_e32 v18, s54
; VI-NEXT:    v_mov_b32_e32 v19, s55
; VI-NEXT:    v_mov_b32_e32 v20, s56
; VI-NEXT:    v_mov_b32_e32 v21, s57
; VI-NEXT:    v_mov_b32_e32 v22, s58
; VI-NEXT:    v_mov_b32_e32 v23, s59
; VI-NEXT:    v_mov_b32_e32 v24, s60
; VI-NEXT:    v_mov_b32_e32 v25, s61
; VI-NEXT:    v_mov_b32_e32 v26, s62
; VI-NEXT:    v_mov_b32_e32 v27, s63
; VI-NEXT:    v_mov_b32_e32 v28, s64
; VI-NEXT:    v_mov_b32_e32 v29, s65
; VI-NEXT:    v_mov_b32_e32 v30, s66
; VI-NEXT:    v_mov_b32_e32 v31, s67
; VI-NEXT:  .LBB47_5: ; %end
; VI-NEXT:    v_readlane_b32 s30, v32, 18
; VI-NEXT:    v_readlane_b32 s31, v32, 19
; VI-NEXT:    v_readlane_b32 s67, v32, 17
; VI-NEXT:    v_readlane_b32 s66, v32, 16
; VI-NEXT:    v_readlane_b32 s65, v32, 15
; VI-NEXT:    v_readlane_b32 s64, v32, 14
; VI-NEXT:    v_readlane_b32 s55, v32, 13
; VI-NEXT:    v_readlane_b32 s54, v32, 12
; VI-NEXT:    v_readlane_b32 s53, v32, 11
; VI-NEXT:    v_readlane_b32 s52, v32, 10
; VI-NEXT:    v_readlane_b32 s51, v32, 9
; VI-NEXT:    v_readlane_b32 s50, v32, 8
; VI-NEXT:    v_readlane_b32 s49, v32, 7
; VI-NEXT:    v_readlane_b32 s48, v32, 6
; VI-NEXT:    v_readlane_b32 s39, v32, 5
; VI-NEXT:    v_readlane_b32 s38, v32, 4
; VI-NEXT:    v_readlane_b32 s37, v32, 3
; VI-NEXT:    v_readlane_b32 s36, v32, 2
; VI-NEXT:    v_readlane_b32 s35, v32, 1
; VI-NEXT:    v_readlane_b32 s34, v32, 0
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v40f16_to_v10i64_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    v_writelane_b32 v32, s36, 0
; GFX9-NEXT:    v_writelane_b32 v32, s37, 1
; GFX9-NEXT:    v_writelane_b32 v32, s38, 2
; GFX9-NEXT:    v_writelane_b32 v32, s39, 3
; GFX9-NEXT:    v_writelane_b32 v32, s48, 4
; GFX9-NEXT:    v_writelane_b32 v32, s49, 5
; GFX9-NEXT:    v_writelane_b32 v32, s50, 6
; GFX9-NEXT:    v_writelane_b32 v32, s51, 7
; GFX9-NEXT:    v_writelane_b32 v32, s52, 8
; GFX9-NEXT:    v_writelane_b32 v32, s53, 9
; GFX9-NEXT:    v_writelane_b32 v32, s54, 10
; GFX9-NEXT:    v_writelane_b32 v32, s55, 11
; GFX9-NEXT:    v_readfirstlane_b32 s56, v5
; GFX9-NEXT:    v_readfirstlane_b32 s58, v4
; GFX9-NEXT:    v_readfirstlane_b32 s60, v3
; GFX9-NEXT:    v_readfirstlane_b32 s62, v2
; GFX9-NEXT:    v_readfirstlane_b32 s72, v1
; GFX9-NEXT:    v_readfirstlane_b32 s74, v0
; GFX9-NEXT:    s_lshr_b32 s4, s29, 16
; GFX9-NEXT:    s_lshr_b32 s5, s28, 16
; GFX9-NEXT:    s_lshr_b32 s6, s27, 16
; GFX9-NEXT:    s_lshr_b32 s7, s26, 16
; GFX9-NEXT:    s_lshr_b32 s8, s25, 16
; GFX9-NEXT:    s_lshr_b32 s9, s24, 16
; GFX9-NEXT:    s_lshr_b32 s10, s23, 16
; GFX9-NEXT:    s_lshr_b32 s11, s22, 16
; GFX9-NEXT:    s_lshr_b32 s12, s21, 16
; GFX9-NEXT:    s_lshr_b32 s13, s20, 16
; GFX9-NEXT:    s_lshr_b32 s14, s19, 16
; GFX9-NEXT:    s_lshr_b32 s15, s18, 16
; GFX9-NEXT:    s_lshr_b32 s40, s17, 16
; GFX9-NEXT:    s_lshr_b32 s41, s16, 16
; GFX9-NEXT:    s_lshr_b32 s57, s56, 16
; GFX9-NEXT:    s_lshr_b32 s59, s58, 16
; GFX9-NEXT:    s_lshr_b32 s61, s60, 16
; GFX9-NEXT:    s_lshr_b32 s63, s62, 16
; GFX9-NEXT:    s_lshr_b32 s73, s72, 16
; GFX9-NEXT:    s_lshr_b32 s75, s74, 16
; GFX9-NEXT:    v_readfirstlane_b32 s42, v6
; GFX9-NEXT:    s_cmp_lg_u32 s42, 0
; GFX9-NEXT:    s_pack_ll_b32_b16 s36, s16, s41
; GFX9-NEXT:    s_pack_ll_b32_b16 s37, s17, s40
; GFX9-NEXT:    s_pack_ll_b32_b16 s38, s18, s15
; GFX9-NEXT:    s_pack_ll_b32_b16 s39, s19, s14
; GFX9-NEXT:    s_pack_ll_b32_b16 s40, s20, s13
; GFX9-NEXT:    s_pack_ll_b32_b16 s41, s21, s12
; GFX9-NEXT:    s_pack_ll_b32_b16 s42, s22, s11
; GFX9-NEXT:    s_pack_ll_b32_b16 s43, s23, s10
; GFX9-NEXT:    s_pack_ll_b32_b16 s44, s24, s9
; GFX9-NEXT:    s_pack_ll_b32_b16 s45, s25, s8
; GFX9-NEXT:    s_pack_ll_b32_b16 s46, s26, s7
; GFX9-NEXT:    s_pack_ll_b32_b16 s47, s27, s6
; GFX9-NEXT:    s_pack_ll_b32_b16 s48, s28, s5
; GFX9-NEXT:    s_pack_ll_b32_b16 s49, s29, s4
; GFX9-NEXT:    s_pack_ll_b32_b16 s50, s74, s75
; GFX9-NEXT:    s_pack_ll_b32_b16 s51, s72, s73
; GFX9-NEXT:    s_pack_ll_b32_b16 s52, s62, s63
; GFX9-NEXT:    s_pack_ll_b32_b16 s53, s60, s61
; GFX9-NEXT:    s_pack_ll_b32_b16 s54, s58, s59
; GFX9-NEXT:    s_pack_ll_b32_b16 s55, s56, s57
; GFX9-NEXT:    s_cbranch_scc0 .LBB47_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB47_4
; GFX9-NEXT:  .LBB47_2: ; %cmp.true
; GFX9-NEXT:    v_mov_b32_e32 v19, 0x200
; GFX9-NEXT:    v_pk_add_f16 v0, s36, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v1, s37, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v2, s38, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v3, s39, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v4, s40, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v5, s41, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, s42, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v7, s43, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v8, s44, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v9, s45, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v10, s46, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v11, s47, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v12, s48, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v13, s49, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v14, s50, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v15, s51, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v16, s52, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v17, s53, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v18, s54, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v19, s55, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_branch .LBB47_5
; GFX9-NEXT:  .LBB47_3:
; GFX9-NEXT:    s_branch .LBB47_2
; GFX9-NEXT:  .LBB47_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s36
; GFX9-NEXT:    v_mov_b32_e32 v1, s37
; GFX9-NEXT:    v_mov_b32_e32 v2, s38
; GFX9-NEXT:    v_mov_b32_e32 v3, s39
; GFX9-NEXT:    v_mov_b32_e32 v4, s40
; GFX9-NEXT:    v_mov_b32_e32 v5, s41
; GFX9-NEXT:    v_mov_b32_e32 v6, s42
; GFX9-NEXT:    v_mov_b32_e32 v7, s43
; GFX9-NEXT:    v_mov_b32_e32 v8, s44
; GFX9-NEXT:    v_mov_b32_e32 v9, s45
; GFX9-NEXT:    v_mov_b32_e32 v10, s46
; GFX9-NEXT:    v_mov_b32_e32 v11, s47
; GFX9-NEXT:    v_mov_b32_e32 v12, s48
; GFX9-NEXT:    v_mov_b32_e32 v13, s49
; GFX9-NEXT:    v_mov_b32_e32 v14, s50
; GFX9-NEXT:    v_mov_b32_e32 v15, s51
; GFX9-NEXT:    v_mov_b32_e32 v16, s52
; GFX9-NEXT:    v_mov_b32_e32 v17, s53
; GFX9-NEXT:    v_mov_b32_e32 v18, s54
; GFX9-NEXT:    v_mov_b32_e32 v19, s55
; GFX9-NEXT:    v_mov_b32_e32 v20, s56
; GFX9-NEXT:    v_mov_b32_e32 v21, s57
; GFX9-NEXT:    v_mov_b32_e32 v22, s58
; GFX9-NEXT:    v_mov_b32_e32 v23, s59
; GFX9-NEXT:    v_mov_b32_e32 v24, s60
; GFX9-NEXT:    v_mov_b32_e32 v25, s61
; GFX9-NEXT:    v_mov_b32_e32 v26, s62
; GFX9-NEXT:    v_mov_b32_e32 v27, s63
; GFX9-NEXT:    v_mov_b32_e32 v28, s64
; GFX9-NEXT:    v_mov_b32_e32 v29, s65
; GFX9-NEXT:    v_mov_b32_e32 v30, s66
; GFX9-NEXT:    v_mov_b32_e32 v31, s67
; GFX9-NEXT:  .LBB47_5: ; %end
; GFX9-NEXT:    v_readlane_b32 s55, v32, 11
; GFX9-NEXT:    v_readlane_b32 s54, v32, 10
; GFX9-NEXT:    v_readlane_b32 s53, v32, 9
; GFX9-NEXT:    v_readlane_b32 s52, v32, 8
; GFX9-NEXT:    v_readlane_b32 s51, v32, 7
; GFX9-NEXT:    v_readlane_b32 s50, v32, 6
; GFX9-NEXT:    v_readlane_b32 s49, v32, 5
; GFX9-NEXT:    v_readlane_b32 s48, v32, 4
; GFX9-NEXT:    v_readlane_b32 s39, v32, 3
; GFX9-NEXT:    v_readlane_b32 s38, v32, 2
; GFX9-NEXT:    v_readlane_b32 s37, v32, 1
; GFX9-NEXT:    v_readlane_b32 s36, v32, 0
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v40f16_to_v10i64_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    v_readfirstlane_b32 s45, v1
; GFX11-NEXT:    v_readfirstlane_b32 s46, v0
; GFX11-NEXT:    v_readfirstlane_b32 s56, v2
; GFX11-NEXT:    s_lshr_b32 s41, s29, 16
; GFX11-NEXT:    s_lshr_b32 s42, s28, 16
; GFX11-NEXT:    s_lshr_b32 s15, s27, 16
; GFX11-NEXT:    s_lshr_b32 s14, s26, 16
; GFX11-NEXT:    s_lshr_b32 s13, s25, 16
; GFX11-NEXT:    s_lshr_b32 s12, s24, 16
; GFX11-NEXT:    s_lshr_b32 s11, s23, 16
; GFX11-NEXT:    s_lshr_b32 s10, s22, 16
; GFX11-NEXT:    s_lshr_b32 s9, s21, 16
; GFX11-NEXT:    s_lshr_b32 s8, s20, 16
; GFX11-NEXT:    s_lshr_b32 s7, s19, 16
; GFX11-NEXT:    s_lshr_b32 s6, s18, 16
; GFX11-NEXT:    s_lshr_b32 s5, s17, 16
; GFX11-NEXT:    s_lshr_b32 s4, s16, 16
; GFX11-NEXT:    s_lshr_b32 s43, s3, 16
; GFX11-NEXT:    s_lshr_b32 s44, s2, 16
; GFX11-NEXT:    s_lshr_b32 s47, s1, 16
; GFX11-NEXT:    s_lshr_b32 s57, s0, 16
; GFX11-NEXT:    s_lshr_b32 s58, s45, 16
; GFX11-NEXT:    s_lshr_b32 s59, s46, 16
; GFX11-NEXT:    s_mov_b32 s40, 0
; GFX11-NEXT:    s_cmp_lg_u32 s56, 0
; GFX11-NEXT:    s_pack_ll_b32_b16 s0, s0, s57
; GFX11-NEXT:    s_pack_ll_b32_b16 s1, s1, s47
; GFX11-NEXT:    s_pack_ll_b32_b16 s2, s2, s44
; GFX11-NEXT:    s_pack_ll_b32_b16 s3, s3, s43
; GFX11-NEXT:    s_pack_ll_b32_b16 s4, s16, s4
; GFX11-NEXT:    s_pack_ll_b32_b16 s5, s17, s5
; GFX11-NEXT:    s_pack_ll_b32_b16 s6, s18, s6
; GFX11-NEXT:    s_pack_ll_b32_b16 s7, s19, s7
; GFX11-NEXT:    s_pack_ll_b32_b16 s8, s20, s8
; GFX11-NEXT:    s_pack_ll_b32_b16 s9, s21, s9
; GFX11-NEXT:    s_pack_ll_b32_b16 s10, s22, s10
; GFX11-NEXT:    s_pack_ll_b32_b16 s11, s23, s11
; GFX11-NEXT:    s_pack_ll_b32_b16 s12, s24, s12
; GFX11-NEXT:    s_pack_ll_b32_b16 s13, s25, s13
; GFX11-NEXT:    s_pack_ll_b32_b16 s14, s26, s14
; GFX11-NEXT:    s_pack_ll_b32_b16 s15, s27, s15
; GFX11-NEXT:    s_pack_ll_b32_b16 s16, s28, s42
; GFX11-NEXT:    s_pack_ll_b32_b16 s17, s29, s41
; GFX11-NEXT:    s_pack_ll_b32_b16 s18, s46, s59
; GFX11-NEXT:    s_pack_ll_b32_b16 s19, s45, s58
; GFX11-NEXT:    s_cbranch_scc0 .LBB47_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s40
; GFX11-NEXT:    s_cbranch_vccnz .LBB47_4
; GFX11-NEXT:  .LBB47_2: ; %cmp.true
; GFX11-NEXT:    v_pk_add_f16 v0, 0x200, s0 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v1, 0x200, s1 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v2, 0x200, s2 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v3, 0x200, s3 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v4, 0x200, s4 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v5, 0x200, s5 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v6, 0x200, s6 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v7, 0x200, s7 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v8, 0x200, s8 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v9, 0x200, s9 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v10, 0x200, s10 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v11, 0x200, s11 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v12, 0x200, s12 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v13, 0x200, s13 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v14, 0x200, s14 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v15, 0x200, s15 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v16, 0x200, s16 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v17, 0x200, s17 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v18, 0x200, s18 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v19, 0x200, s19 op_sel_hi:[0,1]
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB47_3:
; GFX11-NEXT:    s_branch .LBB47_2
; GFX11-NEXT:  .LBB47_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    v_dual_mov_b32 v8, s8 :: v_dual_mov_b32 v9, s9
; GFX11-NEXT:    v_dual_mov_b32 v10, s10 :: v_dual_mov_b32 v11, s11
; GFX11-NEXT:    v_dual_mov_b32 v12, s12 :: v_dual_mov_b32 v13, s13
; GFX11-NEXT:    v_dual_mov_b32 v14, s14 :: v_dual_mov_b32 v15, s15
; GFX11-NEXT:    v_dual_mov_b32 v16, s16 :: v_dual_mov_b32 v17, s17
; GFX11-NEXT:    v_dual_mov_b32 v18, s18 :: v_dual_mov_b32 v19, s19
; GFX11-NEXT:    v_dual_mov_b32 v20, s20 :: v_dual_mov_b32 v21, s21
; GFX11-NEXT:    v_dual_mov_b32 v22, s22 :: v_dual_mov_b32 v23, s23
; GFX11-NEXT:    v_dual_mov_b32 v24, s24 :: v_dual_mov_b32 v25, s25
; GFX11-NEXT:    v_dual_mov_b32 v26, s26 :: v_dual_mov_b32 v27, s27
; GFX11-NEXT:    v_dual_mov_b32 v28, s28 :: v_dual_mov_b32 v29, s29
; GFX11-NEXT:    v_dual_mov_b32 v30, s30 :: v_dual_mov_b32 v31, s31
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <40 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <40 x half> %a1 to <10 x i64>
  br label %end

cmp.false:
  %a3 = bitcast <40 x half> %a to <10 x i64>
  br label %end

end:
  %phi = phi <10 x i64> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <10 x i64> %phi
}

define <40 x i16> @bitcast_v10f64_to_v40i16(<10 x double> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v10f64_to_v40i16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr29
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr26
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr25
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    ; implicit-def: $vgpr24
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr31
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr30
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr28
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr27
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB48_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_alignbit_b32 v20, v19, v18, 16
; SI-NEXT:    v_alignbit_b32 v21, v17, v16, 16
; SI-NEXT:    v_alignbit_b32 v22, v15, v14, 16
; SI-NEXT:    v_alignbit_b32 v23, v13, v12, 16
; SI-NEXT:    v_alignbit_b32 v24, v11, v10, 16
; SI-NEXT:    v_alignbit_b32 v25, v9, v8, 16
; SI-NEXT:    v_alignbit_b32 v26, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v29, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v32, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v35, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v27, 16, v19
; SI-NEXT:    v_lshrrev_b32_e32 v28, 16, v17
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v15
; SI-NEXT:    v_lshrrev_b32_e32 v31, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v33, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v34, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v36, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v37, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v39, 16, v1
; SI-NEXT:  .LBB48_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB48_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; SI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; SI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; SI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; SI-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; SI-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; SI-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; SI-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; SI-NEXT:    v_add_f64 v[18:19], v[18:19], 1.0
; SI-NEXT:    v_add_f64 v[16:17], v[16:17], 1.0
; SI-NEXT:    v_alignbit_b32 v20, v19, v18, 16
; SI-NEXT:    v_alignbit_b32 v21, v17, v16, 16
; SI-NEXT:    v_alignbit_b32 v22, v15, v14, 16
; SI-NEXT:    v_alignbit_b32 v23, v13, v12, 16
; SI-NEXT:    v_alignbit_b32 v24, v11, v10, 16
; SI-NEXT:    v_alignbit_b32 v25, v9, v8, 16
; SI-NEXT:    v_alignbit_b32 v26, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v29, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v32, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v35, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v27, 16, v19
; SI-NEXT:    v_lshrrev_b32_e32 v28, 16, v17
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v15
; SI-NEXT:    v_lshrrev_b32_e32 v31, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v33, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v34, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v36, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v37, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v39, 16, v1
; SI-NEXT:  .LBB48_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_lshlrev_b32_e32 v35, 16, v35
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v32, 16, v32
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_lshlrev_b32_e32 v26, 16, v26
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; SI-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v16
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; SI-NEXT:    v_or_b32_e32 v0, v0, v35
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v35, 16, v39
; SI-NEXT:    v_or_b32_e32 v2, v2, v32
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v32, 16, v38
; SI-NEXT:    v_or_b32_e32 v4, v4, v29
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v29, 16, v37
; SI-NEXT:    v_or_b32_e32 v6, v6, v26
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v26, 16, v36
; SI-NEXT:    v_or_b32_e32 v8, v8, v25
; SI-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; SI-NEXT:    v_lshlrev_b32_e32 v25, 16, v34
; SI-NEXT:    v_or_b32_e32 v10, v10, v24
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; SI-NEXT:    v_lshlrev_b32_e32 v24, 16, v33
; SI-NEXT:    v_or_b32_e32 v12, v12, v23
; SI-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v31
; SI-NEXT:    v_or_b32_e32 v14, v14, v22
; SI-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v30
; SI-NEXT:    v_or_b32_e32 v16, v16, v21
; SI-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v28
; SI-NEXT:    v_or_b32_e32 v18, v18, v20
; SI-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v27
; SI-NEXT:    v_or_b32_e32 v1, v1, v35
; SI-NEXT:    v_or_b32_e32 v3, v3, v32
; SI-NEXT:    v_or_b32_e32 v5, v5, v29
; SI-NEXT:    v_or_b32_e32 v7, v7, v26
; SI-NEXT:    v_or_b32_e32 v9, v9, v25
; SI-NEXT:    v_or_b32_e32 v11, v11, v24
; SI-NEXT:    v_or_b32_e32 v13, v13, v23
; SI-NEXT:    v_or_b32_e32 v15, v15, v22
; SI-NEXT:    v_or_b32_e32 v17, v17, v21
; SI-NEXT:    v_or_b32_e32 v19, v19, v20
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v10f64_to_v40i16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    ; implicit-def: $vgpr39
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr35
; VI-NEXT:    ; implicit-def: $vgpr34
; VI-NEXT:    ; implicit-def: $vgpr33
; VI-NEXT:    ; implicit-def: $vgpr32
; VI-NEXT:    ; implicit-def: $vgpr31
; VI-NEXT:    ; implicit-def: $vgpr30
; VI-NEXT:    ; implicit-def: $vgpr29
; VI-NEXT:    ; implicit-def: $vgpr28
; VI-NEXT:    ; implicit-def: $vgpr27
; VI-NEXT:    ; implicit-def: $vgpr26
; VI-NEXT:    ; implicit-def: $vgpr25
; VI-NEXT:    ; implicit-def: $vgpr24
; VI-NEXT:    ; implicit-def: $vgpr23
; VI-NEXT:    ; implicit-def: $vgpr22
; VI-NEXT:    ; implicit-def: $vgpr21
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB48_2
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; VI-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; VI-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; VI-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; VI-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; VI-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; VI-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; VI-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; VI-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; VI-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; VI-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; VI-NEXT:  .LBB48_2: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB48_4
; VI-NEXT:  ; %bb.3: ; %cmp.true
; VI-NEXT:    v_add_f64 v[18:19], v[18:19], 1.0
; VI-NEXT:    v_add_f64 v[16:17], v[16:17], 1.0
; VI-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; VI-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; VI-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; VI-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; VI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; VI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; VI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; VI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; VI-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; VI-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; VI-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; VI-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; VI-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; VI-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; VI-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; VI-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; VI-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; VI-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; VI-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; VI-NEXT:  .LBB48_4: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    v_lshlrev_b32_e32 v39, 16, v39
; VI-NEXT:    v_lshlrev_b32_e32 v38, 16, v38
; VI-NEXT:    v_lshlrev_b32_e32 v37, 16, v37
; VI-NEXT:    v_lshlrev_b32_e32 v36, 16, v36
; VI-NEXT:    v_lshlrev_b32_e32 v35, 16, v35
; VI-NEXT:    v_lshlrev_b32_e32 v34, 16, v34
; VI-NEXT:    v_lshlrev_b32_e32 v33, 16, v33
; VI-NEXT:    v_lshlrev_b32_e32 v32, 16, v32
; VI-NEXT:    v_lshlrev_b32_e32 v31, 16, v31
; VI-NEXT:    v_lshlrev_b32_e32 v30, 16, v30
; VI-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; VI-NEXT:    v_lshlrev_b32_e32 v28, 16, v28
; VI-NEXT:    v_lshlrev_b32_e32 v27, 16, v27
; VI-NEXT:    v_lshlrev_b32_e32 v26, 16, v26
; VI-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; VI-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; VI-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; VI-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; VI-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; VI-NEXT:    v_or_b32_sdwa v0, v0, v39 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v1, v1, v38 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v2, v2, v37 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v3, v3, v36 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v4, v4, v35 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v5, v5, v34 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v6, v6, v33 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v7, v7, v32 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v8, v8, v31 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v9, v9, v30 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v10, v10, v29 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v11, v11, v28 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v12, v12, v27 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v13, v13, v26 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v14, v14, v25 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v15, v15, v24 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v16, v16, v23 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v17, v17, v22 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v18, v18, v21 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v19, v19, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v10f64_to_v40i16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    ; implicit-def: $vgpr39
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr35
; GFX9-NEXT:    ; implicit-def: $vgpr34
; GFX9-NEXT:    ; implicit-def: $vgpr33
; GFX9-NEXT:    ; implicit-def: $vgpr32
; GFX9-NEXT:    ; implicit-def: $vgpr31
; GFX9-NEXT:    ; implicit-def: $vgpr30
; GFX9-NEXT:    ; implicit-def: $vgpr29
; GFX9-NEXT:    ; implicit-def: $vgpr28
; GFX9-NEXT:    ; implicit-def: $vgpr27
; GFX9-NEXT:    ; implicit-def: $vgpr26
; GFX9-NEXT:    ; implicit-def: $vgpr25
; GFX9-NEXT:    ; implicit-def: $vgpr24
; GFX9-NEXT:    ; implicit-def: $vgpr23
; GFX9-NEXT:    ; implicit-def: $vgpr22
; GFX9-NEXT:    ; implicit-def: $vgpr21
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB48_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX9-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX9-NEXT:  .LBB48_2: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB48_4
; GFX9-NEXT:  ; %bb.3: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[18:19], v[18:19], 1.0
; GFX9-NEXT:    v_add_f64 v[16:17], v[16:17], 1.0
; GFX9-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GFX9-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GFX9-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GFX9-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GFX9-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX9-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX9-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX9-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX9-NEXT:  .LBB48_4: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_mov_b32 s4, 0x5040100
; GFX9-NEXT:    v_perm_b32 v0, v39, v0, s4
; GFX9-NEXT:    v_perm_b32 v1, v38, v1, s4
; GFX9-NEXT:    v_perm_b32 v2, v37, v2, s4
; GFX9-NEXT:    v_perm_b32 v3, v36, v3, s4
; GFX9-NEXT:    v_perm_b32 v4, v35, v4, s4
; GFX9-NEXT:    v_perm_b32 v5, v34, v5, s4
; GFX9-NEXT:    v_perm_b32 v6, v33, v6, s4
; GFX9-NEXT:    v_perm_b32 v7, v32, v7, s4
; GFX9-NEXT:    v_perm_b32 v8, v31, v8, s4
; GFX9-NEXT:    v_perm_b32 v9, v30, v9, s4
; GFX9-NEXT:    v_perm_b32 v10, v29, v10, s4
; GFX9-NEXT:    v_perm_b32 v11, v28, v11, s4
; GFX9-NEXT:    v_perm_b32 v12, v27, v12, s4
; GFX9-NEXT:    v_perm_b32 v13, v26, v13, s4
; GFX9-NEXT:    v_perm_b32 v14, v25, v14, s4
; GFX9-NEXT:    v_perm_b32 v15, v24, v15, s4
; GFX9-NEXT:    v_perm_b32 v16, v23, v16, s4
; GFX9-NEXT:    v_perm_b32 v17, v22, v17, s4
; GFX9-NEXT:    v_perm_b32 v18, v21, v18, s4
; GFX9-NEXT:    v_perm_b32 v19, v20, v19, s4
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v10f64_to_v40i16:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB48_2
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_add_f64 v[18:19], v[18:19], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[16:17], v[16:17], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX11-TRUE16-NEXT:  .LBB48_2: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v10f64_to_v40i16:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr39
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr38
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr37
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr36
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr35
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr34
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr33
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr32
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr31
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr30
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr29
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr28
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr27
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr26
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr25
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr24
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr23
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr22
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr21
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB48_2
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX11-FAKE16-NEXT:  .LBB48_2: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB48_4
; GFX11-FAKE16-NEXT:  ; %bb.3: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_add_f64 v[18:19], v[18:19], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[16:17], v[16:17], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX11-FAKE16-NEXT:  .LBB48_4: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v39, v0, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v38, v1, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v37, v2, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v36, v3, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v35, v4, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v34, v5, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v33, v6, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v32, v7, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, v31, v8, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, v30, v9, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, v29, v10, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, v28, v11, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, v27, v12, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, v26, v13, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v14, v25, v14, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v15, v24, v15, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v16, v23, v16, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v17, v22, v17, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v18, v21, v18, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v19, v20, v19, 0x5040100
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <10 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <10 x double> %a1 to <40 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <10 x double> %a to <40 x i16>
  br label %end

end:
  %phi = phi <40 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <40 x i16> %phi
}

define inreg <40 x i16> @bitcast_v10f64_to_v40i16_scalar(<10 x double> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v10f64_to_v40i16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_readfirstlane_b32 s4, v6
; SI-NEXT:    v_readfirstlane_b32 s9, v5
; SI-NEXT:    v_readfirstlane_b32 s8, v4
; SI-NEXT:    v_readfirstlane_b32 s7, v3
; SI-NEXT:    v_readfirstlane_b32 s6, v2
; SI-NEXT:    v_readfirstlane_b32 s5, v1
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    v_readfirstlane_b32 s4, v0
; SI-NEXT:    s_cbranch_scc0 .LBB49_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_lshr_b32 s89, s9, 16
; SI-NEXT:    s_lshr_b32 s88, s7, 16
; SI-NEXT:    s_lshr_b32 s79, s5, 16
; SI-NEXT:    s_lshr_b32 s78, s29, 16
; SI-NEXT:    s_lshr_b32 s77, s27, 16
; SI-NEXT:    s_lshr_b32 s76, s25, 16
; SI-NEXT:    s_lshr_b32 s75, s23, 16
; SI-NEXT:    s_lshr_b32 s74, s21, 16
; SI-NEXT:    s_lshr_b32 s73, s19, 16
; SI-NEXT:    s_lshr_b32 s72, s17, 16
; SI-NEXT:    s_lshr_b64 s[10:11], s[8:9], 16
; SI-NEXT:    s_lshr_b64 s[12:13], s[6:7], 16
; SI-NEXT:    s_lshr_b64 s[14:15], s[4:5], 16
; SI-NEXT:    s_lshr_b64 s[40:41], s[28:29], 16
; SI-NEXT:    s_lshr_b64 s[42:43], s[26:27], 16
; SI-NEXT:    s_lshr_b64 s[44:45], s[24:25], 16
; SI-NEXT:    s_lshr_b64 s[46:47], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[56:57], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[58:59], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[60:61], s[16:17], 16
; SI-NEXT:    s_cbranch_execnz .LBB49_4
; SI-NEXT:  .LBB49_2: ; %cmp.true
; SI-NEXT:    v_add_f64 v[18:19], s[8:9], 1.0
; SI-NEXT:    v_add_f64 v[16:17], s[6:7], 1.0
; SI-NEXT:    v_add_f64 v[14:15], s[4:5], 1.0
; SI-NEXT:    v_lshr_b64 v[20:21], v[18:19], 16
; SI-NEXT:    v_add_f64 v[12:13], s[28:29], 1.0
; SI-NEXT:    v_lshr_b64 v[21:22], v[16:17], 16
; SI-NEXT:    v_add_f64 v[10:11], s[26:27], 1.0
; SI-NEXT:    v_lshr_b64 v[22:23], v[14:15], 16
; SI-NEXT:    v_add_f64 v[8:9], s[24:25], 1.0
; SI-NEXT:    v_lshr_b64 v[23:24], v[12:13], 16
; SI-NEXT:    v_add_f64 v[6:7], s[22:23], 1.0
; SI-NEXT:    v_lshr_b64 v[24:25], v[10:11], 16
; SI-NEXT:    v_add_f64 v[4:5], s[20:21], 1.0
; SI-NEXT:    v_lshr_b64 v[25:26], v[8:9], 16
; SI-NEXT:    v_add_f64 v[2:3], s[18:19], 1.0
; SI-NEXT:    v_lshr_b64 v[26:27], v[6:7], 16
; SI-NEXT:    v_add_f64 v[0:1], s[16:17], 1.0
; SI-NEXT:    v_lshr_b64 v[27:28], v[4:5], 16
; SI-NEXT:    v_lshr_b64 v[28:29], v[2:3], 16
; SI-NEXT:    v_lshr_b64 v[29:30], v[0:1], 16
; SI-NEXT:    v_lshrrev_b32_e32 v31, 16, v19
; SI-NEXT:    v_lshrrev_b32_e32 v32, 16, v17
; SI-NEXT:    v_lshrrev_b32_e32 v33, 16, v15
; SI-NEXT:    v_lshrrev_b32_e32 v34, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v35, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v36, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v37, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v38, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v39, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v48, 16, v1
; SI-NEXT:    s_branch .LBB49_5
; SI-NEXT:  .LBB49_3:
; SI-NEXT:    ; implicit-def: $sgpr60
; SI-NEXT:    ; implicit-def: $sgpr72
; SI-NEXT:    ; implicit-def: $sgpr58
; SI-NEXT:    ; implicit-def: $sgpr73
; SI-NEXT:    ; implicit-def: $sgpr56
; SI-NEXT:    ; implicit-def: $sgpr74
; SI-NEXT:    ; implicit-def: $sgpr46
; SI-NEXT:    ; implicit-def: $sgpr75
; SI-NEXT:    ; implicit-def: $sgpr44
; SI-NEXT:    ; implicit-def: $sgpr76
; SI-NEXT:    ; implicit-def: $sgpr42
; SI-NEXT:    ; implicit-def: $sgpr77
; SI-NEXT:    ; implicit-def: $sgpr40
; SI-NEXT:    ; implicit-def: $sgpr78
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr79
; SI-NEXT:    ; implicit-def: $sgpr12
; SI-NEXT:    ; implicit-def: $sgpr88
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr89
; SI-NEXT:    s_branch .LBB49_2
; SI-NEXT:  .LBB49_4:
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v2, s18
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v4, s20
; SI-NEXT:    v_mov_b32_e32 v19, s9
; SI-NEXT:    v_mov_b32_e32 v17, s7
; SI-NEXT:    v_mov_b32_e32 v15, s5
; SI-NEXT:    v_mov_b32_e32 v13, s29
; SI-NEXT:    v_mov_b32_e32 v11, s27
; SI-NEXT:    v_mov_b32_e32 v9, s25
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    v_mov_b32_e32 v6, s22
; SI-NEXT:    v_mov_b32_e32 v8, s24
; SI-NEXT:    v_mov_b32_e32 v10, s26
; SI-NEXT:    v_mov_b32_e32 v12, s28
; SI-NEXT:    v_mov_b32_e32 v14, s4
; SI-NEXT:    v_mov_b32_e32 v16, s6
; SI-NEXT:    v_mov_b32_e32 v18, s8
; SI-NEXT:    v_mov_b32_e32 v31, s89
; SI-NEXT:    v_mov_b32_e32 v32, s88
; SI-NEXT:    v_mov_b32_e32 v33, s79
; SI-NEXT:    v_mov_b32_e32 v34, s78
; SI-NEXT:    v_mov_b32_e32 v35, s77
; SI-NEXT:    v_mov_b32_e32 v36, s76
; SI-NEXT:    v_mov_b32_e32 v37, s75
; SI-NEXT:    v_mov_b32_e32 v38, s74
; SI-NEXT:    v_mov_b32_e32 v39, s73
; SI-NEXT:    v_mov_b32_e32 v48, s72
; SI-NEXT:    v_mov_b32_e32 v29, s60
; SI-NEXT:    v_mov_b32_e32 v28, s58
; SI-NEXT:    v_mov_b32_e32 v27, s56
; SI-NEXT:    v_mov_b32_e32 v26, s46
; SI-NEXT:    v_mov_b32_e32 v25, s44
; SI-NEXT:    v_mov_b32_e32 v24, s42
; SI-NEXT:    v_mov_b32_e32 v23, s40
; SI-NEXT:    v_mov_b32_e32 v22, s14
; SI-NEXT:    v_mov_b32_e32 v21, s12
; SI-NEXT:    v_mov_b32_e32 v20, s10
; SI-NEXT:  .LBB49_5: ; %end
; SI-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v28, 16, v28
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v27, 16, v27
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v26, 16, v26
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; SI-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; SI-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v16
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; SI-NEXT:    v_or_b32_e32 v0, v0, v29
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v29, 16, v48
; SI-NEXT:    v_or_b32_e32 v2, v2, v28
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v28, 16, v39
; SI-NEXT:    v_or_b32_e32 v4, v4, v27
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v27, 16, v38
; SI-NEXT:    v_or_b32_e32 v6, v6, v26
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v26, 16, v37
; SI-NEXT:    v_or_b32_e32 v8, v8, v25
; SI-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; SI-NEXT:    v_lshlrev_b32_e32 v25, 16, v36
; SI-NEXT:    v_or_b32_e32 v10, v10, v24
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; SI-NEXT:    v_lshlrev_b32_e32 v24, 16, v35
; SI-NEXT:    v_or_b32_e32 v12, v12, v23
; SI-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v34
; SI-NEXT:    v_or_b32_e32 v14, v14, v22
; SI-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v33
; SI-NEXT:    v_or_b32_e32 v16, v16, v21
; SI-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v32
; SI-NEXT:    v_or_b32_e32 v18, v18, v20
; SI-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v31
; SI-NEXT:    v_or_b32_e32 v1, v1, v29
; SI-NEXT:    v_or_b32_e32 v3, v3, v28
; SI-NEXT:    v_or_b32_e32 v5, v5, v27
; SI-NEXT:    v_or_b32_e32 v7, v7, v26
; SI-NEXT:    v_or_b32_e32 v9, v9, v25
; SI-NEXT:    v_or_b32_e32 v11, v11, v24
; SI-NEXT:    v_or_b32_e32 v13, v13, v23
; SI-NEXT:    v_or_b32_e32 v15, v15, v22
; SI-NEXT:    v_or_b32_e32 v17, v17, v21
; SI-NEXT:    v_or_b32_e32 v19, v19, v20
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v10f64_to_v40i16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    v_readfirstlane_b32 s9, v5
; VI-NEXT:    v_readfirstlane_b32 s8, v4
; VI-NEXT:    v_readfirstlane_b32 s7, v3
; VI-NEXT:    v_readfirstlane_b32 s6, v2
; VI-NEXT:    v_readfirstlane_b32 s5, v1
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    v_readfirstlane_b32 s4, v0
; VI-NEXT:    s_cbranch_scc0 .LBB49_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_lshr_b32 s12, s9, 16
; VI-NEXT:    s_lshr_b32 s46, s8, 16
; VI-NEXT:    s_lshr_b32 s13, s7, 16
; VI-NEXT:    s_lshr_b32 s47, s6, 16
; VI-NEXT:    s_lshr_b32 s14, s5, 16
; VI-NEXT:    s_lshr_b32 s56, s4, 16
; VI-NEXT:    s_lshr_b32 s15, s29, 16
; VI-NEXT:    s_lshr_b32 s57, s28, 16
; VI-NEXT:    s_lshr_b32 s40, s27, 16
; VI-NEXT:    s_lshr_b32 s58, s26, 16
; VI-NEXT:    s_lshr_b32 s41, s25, 16
; VI-NEXT:    s_lshr_b32 s59, s24, 16
; VI-NEXT:    s_lshr_b32 s42, s23, 16
; VI-NEXT:    s_lshr_b32 s60, s22, 16
; VI-NEXT:    s_lshr_b32 s43, s21, 16
; VI-NEXT:    s_lshr_b32 s61, s20, 16
; VI-NEXT:    s_lshr_b32 s44, s19, 16
; VI-NEXT:    s_lshr_b32 s62, s18, 16
; VI-NEXT:    s_lshr_b32 s45, s17, 16
; VI-NEXT:    s_lshr_b32 s63, s16, 16
; VI-NEXT:    s_cbranch_execnz .LBB49_4
; VI-NEXT:  .LBB49_2: ; %cmp.true
; VI-NEXT:    v_add_f64 v[18:19], s[8:9], 1.0
; VI-NEXT:    v_add_f64 v[16:17], s[6:7], 1.0
; VI-NEXT:    v_add_f64 v[14:15], s[4:5], 1.0
; VI-NEXT:    v_add_f64 v[12:13], s[28:29], 1.0
; VI-NEXT:    v_add_f64 v[10:11], s[26:27], 1.0
; VI-NEXT:    v_add_f64 v[8:9], s[24:25], 1.0
; VI-NEXT:    v_add_f64 v[6:7], s[22:23], 1.0
; VI-NEXT:    v_add_f64 v[4:5], s[20:21], 1.0
; VI-NEXT:    v_add_f64 v[2:3], s[18:19], 1.0
; VI-NEXT:    v_add_f64 v[0:1], s[16:17], 1.0
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v19
; VI-NEXT:    v_lshrrev_b32_e32 v20, 16, v18
; VI-NEXT:    v_lshrrev_b32_e32 v24, 16, v17
; VI-NEXT:    v_lshrrev_b32_e32 v21, 16, v16
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v15
; VI-NEXT:    v_lshrrev_b32_e32 v23, 16, v14
; VI-NEXT:    v_lshrrev_b32_e32 v28, 16, v13
; VI-NEXT:    v_lshrrev_b32_e32 v25, 16, v12
; VI-NEXT:    v_lshrrev_b32_e32 v29, 16, v11
; VI-NEXT:    v_lshrrev_b32_e32 v27, 16, v10
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; VI-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; VI-NEXT:    v_lshrrev_b32_e32 v34, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v32, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v36, 16, v5
; VI-NEXT:    v_lshrrev_b32_e32 v33, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; VI-NEXT:    v_lshrrev_b32_e32 v35, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v39, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v0
; VI-NEXT:    s_branch .LBB49_5
; VI-NEXT:  .LBB49_3:
; VI-NEXT:    ; implicit-def: $sgpr63
; VI-NEXT:    ; implicit-def: $sgpr45
; VI-NEXT:    ; implicit-def: $sgpr62
; VI-NEXT:    ; implicit-def: $sgpr44
; VI-NEXT:    ; implicit-def: $sgpr61
; VI-NEXT:    ; implicit-def: $sgpr43
; VI-NEXT:    ; implicit-def: $sgpr60
; VI-NEXT:    ; implicit-def: $sgpr42
; VI-NEXT:    ; implicit-def: $sgpr59
; VI-NEXT:    ; implicit-def: $sgpr41
; VI-NEXT:    ; implicit-def: $sgpr58
; VI-NEXT:    ; implicit-def: $sgpr40
; VI-NEXT:    ; implicit-def: $sgpr57
; VI-NEXT:    ; implicit-def: $sgpr15
; VI-NEXT:    ; implicit-def: $sgpr56
; VI-NEXT:    ; implicit-def: $sgpr14
; VI-NEXT:    ; implicit-def: $sgpr47
; VI-NEXT:    ; implicit-def: $sgpr13
; VI-NEXT:    ; implicit-def: $sgpr46
; VI-NEXT:    ; implicit-def: $sgpr12
; VI-NEXT:    s_branch .LBB49_2
; VI-NEXT:  .LBB49_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v8, s24
; VI-NEXT:    v_mov_b32_e32 v10, s26
; VI-NEXT:    v_mov_b32_e32 v12, s28
; VI-NEXT:    v_mov_b32_e32 v14, s4
; VI-NEXT:    v_mov_b32_e32 v16, s6
; VI-NEXT:    v_mov_b32_e32 v18, s8
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    v_mov_b32_e32 v9, s25
; VI-NEXT:    v_mov_b32_e32 v11, s27
; VI-NEXT:    v_mov_b32_e32 v13, s29
; VI-NEXT:    v_mov_b32_e32 v15, s5
; VI-NEXT:    v_mov_b32_e32 v17, s7
; VI-NEXT:    v_mov_b32_e32 v19, s9
; VI-NEXT:    v_mov_b32_e32 v37, s63
; VI-NEXT:    v_mov_b32_e32 v35, s62
; VI-NEXT:    v_mov_b32_e32 v33, s61
; VI-NEXT:    v_mov_b32_e32 v32, s60
; VI-NEXT:    v_mov_b32_e32 v31, s59
; VI-NEXT:    v_mov_b32_e32 v27, s58
; VI-NEXT:    v_mov_b32_e32 v25, s57
; VI-NEXT:    v_mov_b32_e32 v23, s56
; VI-NEXT:    v_mov_b32_e32 v21, s47
; VI-NEXT:    v_mov_b32_e32 v20, s46
; VI-NEXT:    v_mov_b32_e32 v39, s45
; VI-NEXT:    v_mov_b32_e32 v38, s44
; VI-NEXT:    v_mov_b32_e32 v36, s43
; VI-NEXT:    v_mov_b32_e32 v34, s42
; VI-NEXT:    v_mov_b32_e32 v30, s41
; VI-NEXT:    v_mov_b32_e32 v29, s40
; VI-NEXT:    v_mov_b32_e32 v28, s15
; VI-NEXT:    v_mov_b32_e32 v26, s14
; VI-NEXT:    v_mov_b32_e32 v24, s13
; VI-NEXT:    v_mov_b32_e32 v22, s12
; VI-NEXT:  .LBB49_5: ; %end
; VI-NEXT:    v_lshlrev_b32_e32 v37, 16, v37
; VI-NEXT:    v_lshlrev_b32_e32 v35, 16, v35
; VI-NEXT:    v_lshlrev_b32_e32 v33, 16, v33
; VI-NEXT:    v_lshlrev_b32_e32 v32, 16, v32
; VI-NEXT:    v_lshlrev_b32_e32 v27, 16, v27
; VI-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; VI-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; VI-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; VI-NEXT:    v_or_b32_sdwa v0, v0, v37 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v37, 16, v39
; VI-NEXT:    v_or_b32_sdwa v2, v2, v35 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v35, 16, v38
; VI-NEXT:    v_or_b32_sdwa v4, v4, v33 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v33, 16, v36
; VI-NEXT:    v_or_b32_sdwa v6, v6, v32 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v32, 16, v34
; VI-NEXT:    v_lshlrev_b32_e32 v31, 16, v31
; VI-NEXT:    v_lshlrev_b32_e32 v30, 16, v30
; VI-NEXT:    v_or_b32_sdwa v10, v10, v27 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v27, 16, v29
; VI-NEXT:    v_or_b32_sdwa v12, v12, v25 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v25, 16, v28
; VI-NEXT:    v_or_b32_sdwa v14, v14, v23 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v23, 16, v26
; VI-NEXT:    v_or_b32_sdwa v16, v16, v21 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v21, 16, v24
; VI-NEXT:    v_or_b32_sdwa v18, v18, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v22
; VI-NEXT:    v_or_b32_sdwa v1, v1, v37 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v3, v3, v35 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v5, v5, v33 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v7, v7, v32 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v8, v8, v31 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v9, v9, v30 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v11, v11, v27 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v13, v13, v25 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v15, v15, v23 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v17, v17, v21 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v19, v19, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v10f64_to_v40i16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_readfirstlane_b32 s4, v6
; GFX9-NEXT:    v_readfirstlane_b32 s9, v5
; GFX9-NEXT:    v_readfirstlane_b32 s8, v4
; GFX9-NEXT:    v_readfirstlane_b32 s7, v3
; GFX9-NEXT:    v_readfirstlane_b32 s6, v2
; GFX9-NEXT:    v_readfirstlane_b32 s5, v1
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    v_readfirstlane_b32 s4, v0
; GFX9-NEXT:    s_cbranch_scc0 .LBB49_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_lshr_b32 s12, s9, 16
; GFX9-NEXT:    s_lshr_b32 s46, s8, 16
; GFX9-NEXT:    s_lshr_b32 s13, s7, 16
; GFX9-NEXT:    s_lshr_b32 s47, s6, 16
; GFX9-NEXT:    s_lshr_b32 s14, s5, 16
; GFX9-NEXT:    s_lshr_b32 s56, s4, 16
; GFX9-NEXT:    s_lshr_b32 s15, s29, 16
; GFX9-NEXT:    s_lshr_b32 s57, s28, 16
; GFX9-NEXT:    s_lshr_b32 s40, s27, 16
; GFX9-NEXT:    s_lshr_b32 s58, s26, 16
; GFX9-NEXT:    s_lshr_b32 s41, s25, 16
; GFX9-NEXT:    s_lshr_b32 s59, s24, 16
; GFX9-NEXT:    s_lshr_b32 s42, s23, 16
; GFX9-NEXT:    s_lshr_b32 s60, s22, 16
; GFX9-NEXT:    s_lshr_b32 s43, s21, 16
; GFX9-NEXT:    s_lshr_b32 s61, s20, 16
; GFX9-NEXT:    s_lshr_b32 s44, s19, 16
; GFX9-NEXT:    s_lshr_b32 s62, s18, 16
; GFX9-NEXT:    s_lshr_b32 s45, s17, 16
; GFX9-NEXT:    s_lshr_b32 s63, s16, 16
; GFX9-NEXT:    s_cbranch_execnz .LBB49_4
; GFX9-NEXT:  .LBB49_2: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[18:19], s[8:9], 1.0
; GFX9-NEXT:    v_add_f64 v[16:17], s[6:7], 1.0
; GFX9-NEXT:    v_add_f64 v[14:15], s[4:5], 1.0
; GFX9-NEXT:    v_add_f64 v[12:13], s[28:29], 1.0
; GFX9-NEXT:    v_add_f64 v[10:11], s[26:27], 1.0
; GFX9-NEXT:    v_add_f64 v[8:9], s[24:25], 1.0
; GFX9-NEXT:    v_add_f64 v[6:7], s[22:23], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], s[20:21], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], s[18:19], 1.0
; GFX9-NEXT:    v_add_f64 v[0:1], s[16:17], 1.0
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v19
; GFX9-NEXT:    v_lshrrev_b32_e32 v20, 16, v18
; GFX9-NEXT:    v_lshrrev_b32_e32 v24, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v15
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 16, v14
; GFX9-NEXT:    v_lshrrev_b32_e32 v28, 16, v13
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 16, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 16, v11
; GFX9-NEXT:    v_lshrrev_b32_e32 v27, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 16, v5
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v2
; GFX9-NEXT:    v_lshrrev_b32_e32 v39, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v0
; GFX9-NEXT:    s_branch .LBB49_5
; GFX9-NEXT:  .LBB49_3:
; GFX9-NEXT:    ; implicit-def: $sgpr63
; GFX9-NEXT:    ; implicit-def: $sgpr45
; GFX9-NEXT:    ; implicit-def: $sgpr62
; GFX9-NEXT:    ; implicit-def: $sgpr44
; GFX9-NEXT:    ; implicit-def: $sgpr61
; GFX9-NEXT:    ; implicit-def: $sgpr43
; GFX9-NEXT:    ; implicit-def: $sgpr60
; GFX9-NEXT:    ; implicit-def: $sgpr42
; GFX9-NEXT:    ; implicit-def: $sgpr59
; GFX9-NEXT:    ; implicit-def: $sgpr41
; GFX9-NEXT:    ; implicit-def: $sgpr58
; GFX9-NEXT:    ; implicit-def: $sgpr40
; GFX9-NEXT:    ; implicit-def: $sgpr57
; GFX9-NEXT:    ; implicit-def: $sgpr15
; GFX9-NEXT:    ; implicit-def: $sgpr56
; GFX9-NEXT:    ; implicit-def: $sgpr14
; GFX9-NEXT:    ; implicit-def: $sgpr47
; GFX9-NEXT:    ; implicit-def: $sgpr13
; GFX9-NEXT:    ; implicit-def: $sgpr46
; GFX9-NEXT:    ; implicit-def: $sgpr12
; GFX9-NEXT:    s_branch .LBB49_2
; GFX9-NEXT:  .LBB49_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v8, s24
; GFX9-NEXT:    v_mov_b32_e32 v10, s26
; GFX9-NEXT:    v_mov_b32_e32 v12, s28
; GFX9-NEXT:    v_mov_b32_e32 v14, s4
; GFX9-NEXT:    v_mov_b32_e32 v16, s6
; GFX9-NEXT:    v_mov_b32_e32 v18, s8
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    v_mov_b32_e32 v9, s25
; GFX9-NEXT:    v_mov_b32_e32 v11, s27
; GFX9-NEXT:    v_mov_b32_e32 v13, s29
; GFX9-NEXT:    v_mov_b32_e32 v15, s5
; GFX9-NEXT:    v_mov_b32_e32 v17, s7
; GFX9-NEXT:    v_mov_b32_e32 v19, s9
; GFX9-NEXT:    v_mov_b32_e32 v37, s63
; GFX9-NEXT:    v_mov_b32_e32 v35, s62
; GFX9-NEXT:    v_mov_b32_e32 v33, s61
; GFX9-NEXT:    v_mov_b32_e32 v32, s60
; GFX9-NEXT:    v_mov_b32_e32 v31, s59
; GFX9-NEXT:    v_mov_b32_e32 v27, s58
; GFX9-NEXT:    v_mov_b32_e32 v25, s57
; GFX9-NEXT:    v_mov_b32_e32 v23, s56
; GFX9-NEXT:    v_mov_b32_e32 v21, s47
; GFX9-NEXT:    v_mov_b32_e32 v20, s46
; GFX9-NEXT:    v_mov_b32_e32 v39, s45
; GFX9-NEXT:    v_mov_b32_e32 v38, s44
; GFX9-NEXT:    v_mov_b32_e32 v36, s43
; GFX9-NEXT:    v_mov_b32_e32 v34, s42
; GFX9-NEXT:    v_mov_b32_e32 v30, s41
; GFX9-NEXT:    v_mov_b32_e32 v29, s40
; GFX9-NEXT:    v_mov_b32_e32 v28, s15
; GFX9-NEXT:    v_mov_b32_e32 v26, s14
; GFX9-NEXT:    v_mov_b32_e32 v24, s13
; GFX9-NEXT:    v_mov_b32_e32 v22, s12
; GFX9-NEXT:  .LBB49_5: ; %end
; GFX9-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; GFX9-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX9-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GFX9-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX9-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; GFX9-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; GFX9-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; GFX9-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; GFX9-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; GFX9-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; GFX9-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; GFX9-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; GFX9-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; GFX9-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; GFX9-NEXT:    v_and_b32_e32 v16, 0xffff, v16
; GFX9-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; GFX9-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; GFX9-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; GFX9-NEXT:    v_lshl_or_b32 v0, v37, 16, v0
; GFX9-NEXT:    v_lshl_or_b32 v1, v39, 16, v1
; GFX9-NEXT:    v_lshl_or_b32 v2, v35, 16, v2
; GFX9-NEXT:    v_lshl_or_b32 v3, v38, 16, v3
; GFX9-NEXT:    v_lshl_or_b32 v4, v33, 16, v4
; GFX9-NEXT:    v_lshl_or_b32 v5, v36, 16, v5
; GFX9-NEXT:    v_lshl_or_b32 v6, v32, 16, v6
; GFX9-NEXT:    v_lshl_or_b32 v7, v34, 16, v7
; GFX9-NEXT:    v_lshl_or_b32 v8, v31, 16, v8
; GFX9-NEXT:    v_lshl_or_b32 v9, v30, 16, v9
; GFX9-NEXT:    v_lshl_or_b32 v10, v27, 16, v10
; GFX9-NEXT:    v_lshl_or_b32 v11, v29, 16, v11
; GFX9-NEXT:    v_lshl_or_b32 v12, v25, 16, v12
; GFX9-NEXT:    v_lshl_or_b32 v13, v28, 16, v13
; GFX9-NEXT:    v_lshl_or_b32 v14, v23, 16, v14
; GFX9-NEXT:    v_lshl_or_b32 v15, v26, 16, v15
; GFX9-NEXT:    v_lshl_or_b32 v16, v21, 16, v16
; GFX9-NEXT:    v_lshl_or_b32 v17, v24, 16, v17
; GFX9-NEXT:    v_lshl_or_b32 v18, v20, 16, v18
; GFX9-NEXT:    v_lshl_or_b32 v19, v22, 16, v19
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v10f64_to_v40i16_scalar:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s6, v2
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s5, v1
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s4, v0
; GFX11-TRUE16-NEXT:    s_cmp_lg_u32 s6, 0
; GFX11-TRUE16-NEXT:    s_mov_b32 s6, 0
; GFX11-TRUE16-NEXT:    s_cbranch_scc0 .LBB49_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-TRUE16-NEXT:    s_lshr_b32 s7, s5, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s41, s4, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s8, s29, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s42, s28, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s9, s27, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s43, s26, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s10, s25, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s44, s24, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s11, s23, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s45, s22, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s12, s21, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s46, s20, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s13, s19, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s47, s18, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s14, s17, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s56, s16, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s15, s3, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s57, s2, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s40, s1, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s58, s0, 16
; GFX11-TRUE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s6
; GFX11-TRUE16-NEXT:    s_cbranch_vccnz .LBB49_4
; GFX11-TRUE16-NEXT:  .LBB49_2: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_add_f64 v[18:19], s[4:5], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[16:17], s[28:29], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[14:15], s[26:27], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[12:13], s[24:25], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[10:11], s[22:23], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[8:9], s[20:21], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[6:7], s[18:19], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[4:5], s[16:17], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[2:3], s[2:3], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[0:1], s[0:1], 1.0
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v20, 16, v18
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v17
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v16
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v15
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v14
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v13
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v12
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v10
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v9
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v8
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v7
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v6
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v5
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v4
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v2
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v1
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v0
; GFX11-TRUE16-NEXT:    s_branch .LBB49_5
; GFX11-TRUE16-NEXT:  .LBB49_3:
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr58
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr40
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr57
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr15
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr56
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr14
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr47
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr13
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr46
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr12
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr45
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr11
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr44
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr10
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr43
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr9
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr42
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr8
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr41
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr7
; GFX11-TRUE16-NEXT:    s_branch .LBB49_2
; GFX11-TRUE16-NEXT:  .LBB49_4:
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v4, s16 :: v_dual_mov_b32 v5, s17
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v6, s18 :: v_dual_mov_b32 v7, s19
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v8, s20 :: v_dual_mov_b32 v9, s21
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v10, s22 :: v_dual_mov_b32 v11, s23
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v12, s24 :: v_dual_mov_b32 v13, s25
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v14, s26 :: v_dual_mov_b32 v15, s27
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v16, s28 :: v_dual_mov_b32 v17, s29
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v18, s4 :: v_dual_mov_b32 v19, s5
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v37, s58 :: v_dual_mov_b32 v20, s41
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v35, s57 :: v_dual_mov_b32 v38, s15
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v33, s56 :: v_dual_mov_b32 v36, s14
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v31, s47 :: v_dual_mov_b32 v34, s13
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v29, s46 :: v_dual_mov_b32 v32, s12
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v27, s45 :: v_dual_mov_b32 v30, s11
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v25, s44 :: v_dual_mov_b32 v28, s10
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v23, s43 :: v_dual_mov_b32 v26, s9
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v21, s42 :: v_dual_mov_b32 v24, s8
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v39, s40 :: v_dual_mov_b32 v22, s7
; GFX11-TRUE16-NEXT:  .LBB49_5: ; %end
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.h, v37.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v1.h, v39.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.h, v35.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v3.h, v38.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v4.h, v33.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v5.h, v36.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v6.h, v31.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v7.h, v34.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v8.h, v29.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v9.h, v32.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v10.h, v27.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v11.h, v30.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v12.h, v25.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v13.h, v28.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v14.h, v23.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v15.h, v26.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v16.h, v21.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v17.h, v24.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v18.h, v20.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v19.h, v22.l
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v10f64_to_v40i16_scalar:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s6, v2
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s5, v1
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s4, v0
; GFX11-FAKE16-NEXT:    s_cmp_lg_u32 s6, 0
; GFX11-FAKE16-NEXT:    s_mov_b32 s6, 0
; GFX11-FAKE16-NEXT:    s_cbranch_scc0 .LBB49_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-FAKE16-NEXT:    s_lshr_b32 s7, s5, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s41, s4, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s8, s29, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s42, s28, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s9, s27, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s43, s26, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s10, s25, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s44, s24, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s11, s23, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s45, s22, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s12, s21, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s46, s20, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s13, s19, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s47, s18, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s14, s17, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s56, s16, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s15, s3, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s57, s2, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s40, s1, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s58, s0, 16
; GFX11-FAKE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s6
; GFX11-FAKE16-NEXT:    s_cbranch_vccnz .LBB49_4
; GFX11-FAKE16-NEXT:  .LBB49_2: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_add_f64 v[15:16], s[4:5], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[17:18], s[28:29], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[19:20], s[26:27], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[10:11], s[24:25], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[12:13], s[22:23], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[5:6], s[20:21], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[7:8], s[18:19], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[21:22], s[16:17], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[0:1], s[2:3], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[2:3], s[0:1], 1.0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v20
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v14, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v9, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v22
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v4, 16, v21
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v3
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX11-FAKE16-NEXT:    s_branch .LBB49_5
; GFX11-FAKE16-NEXT:  .LBB49_3:
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr58
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr40
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr57
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr15
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr56
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr14
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr47
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr13
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr46
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr12
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr45
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr11
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr44
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr10
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr43
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr9
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr42
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr8
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr41
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr7
; GFX11-FAKE16-NEXT:    s_branch .LBB49_2
; GFX11-FAKE16-NEXT:  .LBB49_4:
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v2, s0 :: v_dual_mov_b32 v21, s16
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v0, s2 :: v_dual_mov_b32 v7, s18
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v5, s20 :: v_dual_mov_b32 v12, s22
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v10, s24 :: v_dual_mov_b32 v19, s26
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v17, s28 :: v_dual_mov_b32 v22, s17
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v15, s4 :: v_dual_mov_b32 v8, s19
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v3, s1 :: v_dual_mov_b32 v6, s21
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v1, s3 :: v_dual_mov_b32 v20, s27
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v13, s23 :: v_dual_mov_b32 v18, s29
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v11, s25 :: v_dual_mov_b32 v16, s5
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v37, s58 :: v_dual_mov_b32 v36, s57
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v4, s56 :: v_dual_mov_b32 v9, s46
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v32, s47 :: v_dual_mov_b32 v29, s45
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v28, s44 :: v_dual_mov_b32 v23, s41
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v14, s43 :: v_dual_mov_b32 v39, s40
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v24, s42 :: v_dual_mov_b32 v35, s14
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v38, s15 :: v_dual_mov_b32 v33, s12
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v34, s13 :: v_dual_mov_b32 v31, s11
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v30, s10 :: v_dual_mov_b32 v27, s9
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v26, s8 :: v_dual_mov_b32 v25, s7
; GFX11-FAKE16-NEXT:  .LBB49_5: ; %end
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v21, 0xffff, v21
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v48, 0xffff, v0
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v4, v4, 16, v21
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v21, 0xffff, v22
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v22, 0xffff, v5
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v5, v35, 16, v21
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v21, 0xffff, v10
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v49, 0xffff, v1
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v0, v37, 16, v2
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v2, v36, 16, v48
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v36, 0xffff, v6
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v6, v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v7, v34, 16, v8
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v8, v9, 16, v22
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v22, 0xffff, v11
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v10, v29, 16, v12
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v12, v28, 16, v21
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v14, v14, 16, v19
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v19, 0xffff, v20
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v20, 0xffff, v15
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v21, 0xffff, v16
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v1, v39, 16, v3
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v3, v38, 16, v49
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v9, v33, 16, v36
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v11, v31, 16, v13
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v13, v30, 16, v22
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v15, v27, 16, v19
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v16, v24, 16, v17
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v17, v26, 16, v18
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v18, v23, 16, v20
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v19, v25, 16, v21
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <10 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <10 x double> %a1 to <40 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <10 x double> %a to <40 x i16>
  br label %end

end:
  %phi = phi <40 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <40 x i16> %phi
}

define <10 x double> @bitcast_v40i16_to_v10f64(<40 x i16> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v40i16_to_v10f64:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v63, off, s[0:3], s32 ; 4-byte Folded Spill
; SI-NEXT:    v_mov_b32_e32 v32, v19
; SI-NEXT:    v_mov_b32_e32 v33, v18
; SI-NEXT:    v_mov_b32_e32 v34, v17
; SI-NEXT:    v_mov_b32_e32 v35, v16
; SI-NEXT:    v_mov_b32_e32 v36, v15
; SI-NEXT:    v_mov_b32_e32 v37, v14
; SI-NEXT:    v_mov_b32_e32 v38, v13
; SI-NEXT:    v_mov_b32_e32 v39, v12
; SI-NEXT:    v_mov_b32_e32 v48, v11
; SI-NEXT:    v_mov_b32_e32 v49, v10
; SI-NEXT:    v_mov_b32_e32 v50, v9
; SI-NEXT:    v_mov_b32_e32 v51, v8
; SI-NEXT:    v_mov_b32_e32 v52, v7
; SI-NEXT:    v_mov_b32_e32 v53, v6
; SI-NEXT:    v_mov_b32_e32 v54, v5
; SI-NEXT:    v_mov_b32_e32 v55, v4
; SI-NEXT:    v_mov_b32_e32 v40, v3
; SI-NEXT:    v_mov_b32_e32 v41, v2
; SI-NEXT:    v_mov_b32_e32 v42, v1
; SI-NEXT:    v_mov_b32_e32 v43, v0
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v32
; SI-NEXT:    v_lshrrev_b32_e32 v1, 16, v33
; SI-NEXT:    v_lshrrev_b32_e32 v2, 16, v34
; SI-NEXT:    v_lshrrev_b32_e32 v3, 16, v35
; SI-NEXT:    v_lshrrev_b32_e32 v4, 16, v36
; SI-NEXT:    v_lshrrev_b32_e32 v5, 16, v37
; SI-NEXT:    v_lshrrev_b32_e32 v6, 16, v38
; SI-NEXT:    v_lshrrev_b32_e32 v7, 16, v39
; SI-NEXT:    v_lshrrev_b32_e32 v8, 16, v48
; SI-NEXT:    v_lshrrev_b32_e32 v9, 16, v49
; SI-NEXT:    v_lshrrev_b32_e32 v10, 16, v50
; SI-NEXT:    v_lshrrev_b32_e32 v11, 16, v51
; SI-NEXT:    v_lshrrev_b32_e32 v12, 16, v52
; SI-NEXT:    v_lshrrev_b32_e32 v13, 16, v53
; SI-NEXT:    v_lshrrev_b32_e32 v14, 16, v54
; SI-NEXT:    v_lshrrev_b32_e32 v15, 16, v55
; SI-NEXT:    v_lshrrev_b32_e32 v16, 16, v40
; SI-NEXT:    v_lshrrev_b32_e32 v17, 16, v41
; SI-NEXT:    v_lshrrev_b32_e32 v18, 16, v42
; SI-NEXT:    v_lshrrev_b32_e32 v19, 16, v43
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    s_waitcnt expcnt(4)
; SI-NEXT:    v_lshlrev_b32_e32 v59, 16, v19
; SI-NEXT:    v_lshlrev_b32_e32 v58, 16, v18
; SI-NEXT:    v_lshlrev_b32_e32 v57, 16, v17
; SI-NEXT:    v_lshlrev_b32_e32 v56, 16, v16
; SI-NEXT:    v_lshlrev_b32_e32 v47, 16, v15
; SI-NEXT:    v_lshlrev_b32_e32 v46, 16, v14
; SI-NEXT:    v_lshlrev_b32_e32 v45, 16, v13
; SI-NEXT:    v_lshlrev_b32_e32 v44, 16, v12
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshlrev_b32_e32 v63, 16, v11
; SI-NEXT:    v_lshlrev_b32_e32 v62, 16, v10
; SI-NEXT:    v_lshlrev_b32_e32 v61, 16, v9
; SI-NEXT:    v_lshlrev_b32_e32 v60, 16, v8
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    buffer_store_dword v7, off, s[0:3], s32 offset:92 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v6, off, s[0:3], s32 offset:88 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v5, off, s[0:3], s32 offset:84 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v4, off, s[0:3], s32 offset:80 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v3, off, s[0:3], s32 offset:76 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v2, off, s[0:3], s32 offset:72 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:68 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:64 ; 4-byte Folded Spill
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB50_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:92 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:88 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:84 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:80 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:76 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:72 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v39
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v43
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v42
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v41
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v40
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v55
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v54
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v53
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v52
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v51
; SI-NEXT:    v_and_b32_e32 v9, 0xffff, v50
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v49
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v48
; SI-NEXT:    v_or_b32_e32 v0, v0, v59
; SI-NEXT:    v_or_b32_e32 v1, v1, v58
; SI-NEXT:    v_or_b32_e32 v2, v2, v57
; SI-NEXT:    v_or_b32_e32 v3, v3, v56
; SI-NEXT:    v_or_b32_e32 v4, v4, v47
; SI-NEXT:    v_or_b32_e32 v5, v5, v46
; SI-NEXT:    v_or_b32_e32 v6, v6, v45
; SI-NEXT:    v_or_b32_e32 v7, v7, v44
; SI-NEXT:    v_or_b32_e32 v8, v8, v63
; SI-NEXT:    v_or_b32_e32 v9, v9, v62
; SI-NEXT:    v_or_b32_e32 v10, v10, v61
; SI-NEXT:    v_or_b32_e32 v11, v11, v60
; SI-NEXT:    ; implicit-def: $vgpr43
; SI-NEXT:    ; implicit-def: $vgpr42
; SI-NEXT:    ; implicit-def: $vgpr41
; SI-NEXT:    ; implicit-def: $vgpr40
; SI-NEXT:    ; implicit-def: $vgpr55
; SI-NEXT:    ; implicit-def: $vgpr54
; SI-NEXT:    ; implicit-def: $vgpr53
; SI-NEXT:    ; implicit-def: $vgpr52
; SI-NEXT:    ; implicit-def: $vgpr51
; SI-NEXT:    ; implicit-def: $vgpr50
; SI-NEXT:    ; implicit-def: $vgpr49
; SI-NEXT:    ; implicit-def: $vgpr48
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:    ; implicit-def: $vgpr59
; SI-NEXT:    ; implicit-def: $vgpr58
; SI-NEXT:    ; implicit-def: $vgpr57
; SI-NEXT:    ; implicit-def: $vgpr56
; SI-NEXT:    ; implicit-def: $vgpr47
; SI-NEXT:    ; implicit-def: $vgpr46
; SI-NEXT:    ; implicit-def: $vgpr45
; SI-NEXT:    ; implicit-def: $vgpr44
; SI-NEXT:    ; implicit-def: $vgpr63
; SI-NEXT:    ; implicit-def: $vgpr62
; SI-NEXT:    ; implicit-def: $vgpr61
; SI-NEXT:    ; implicit-def: $vgpr60
; SI-NEXT:    s_waitcnt vmcnt(7)
; SI-NEXT:    v_or_b32_e32 v12, v12, v13
; SI-NEXT:    v_and_b32_e32 v13, 0xffff, v38
; SI-NEXT:    s_waitcnt vmcnt(6)
; SI-NEXT:    v_or_b32_e32 v13, v13, v14
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v37
; SI-NEXT:    s_waitcnt vmcnt(5)
; SI-NEXT:    v_or_b32_e32 v14, v14, v15
; SI-NEXT:    v_and_b32_e32 v15, 0xffff, v36
; SI-NEXT:    s_waitcnt vmcnt(4)
; SI-NEXT:    v_or_b32_e32 v15, v15, v16
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v35
; SI-NEXT:    s_waitcnt vmcnt(3)
; SI-NEXT:    v_or_b32_e32 v16, v16, v17
; SI-NEXT:    v_and_b32_e32 v17, 0xffff, v34
; SI-NEXT:    s_waitcnt vmcnt(2)
; SI-NEXT:    v_or_b32_e32 v17, v17, v18
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v33
; SI-NEXT:    s_waitcnt vmcnt(1)
; SI-NEXT:    v_or_b32_e32 v18, v18, v19
; SI-NEXT:    v_and_b32_e32 v19, 0xffff, v32
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_or_b32_e32 v19, v19, v20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:  .LBB50_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB50_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:92 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:88 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:84 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:80 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:76 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:72 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; SI-NEXT:    v_add_i32_e32 v12, vcc, 3, v39
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v43
; SI-NEXT:    v_add_i32_e32 v1, vcc, 3, v42
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v41
; SI-NEXT:    v_add_i32_e32 v3, vcc, 3, v40
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v55
; SI-NEXT:    v_add_i32_e32 v5, vcc, 3, v54
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v53
; SI-NEXT:    v_add_i32_e32 v7, vcc, 3, v52
; SI-NEXT:    v_add_i32_e32 v8, vcc, 3, v51
; SI-NEXT:    v_add_i32_e32 v9, vcc, 3, v50
; SI-NEXT:    v_add_i32_e32 v10, vcc, 3, v49
; SI-NEXT:    v_add_i32_e32 v11, vcc, 3, v48
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; SI-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; SI-NEXT:    v_or_b32_e32 v0, v59, v0
; SI-NEXT:    s_mov_b32 s6, 0x30000
; SI-NEXT:    v_or_b32_e32 v1, v58, v1
; SI-NEXT:    v_or_b32_e32 v2, v57, v2
; SI-NEXT:    v_or_b32_e32 v3, v56, v3
; SI-NEXT:    v_or_b32_e32 v4, v47, v4
; SI-NEXT:    v_or_b32_e32 v5, v46, v5
; SI-NEXT:    v_or_b32_e32 v6, v45, v6
; SI-NEXT:    v_or_b32_e32 v7, v44, v7
; SI-NEXT:    v_or_b32_e32 v8, v63, v8
; SI-NEXT:    v_or_b32_e32 v9, v62, v9
; SI-NEXT:    v_or_b32_e32 v10, v61, v10
; SI-NEXT:    v_or_b32_e32 v11, v60, v11
; SI-NEXT:    v_add_i32_e32 v0, vcc, 0x30000, v0
; SI-NEXT:    v_add_i32_e32 v1, vcc, s6, v1
; SI-NEXT:    v_add_i32_e32 v2, vcc, s6, v2
; SI-NEXT:    v_add_i32_e32 v3, vcc, s6, v3
; SI-NEXT:    v_add_i32_e32 v4, vcc, s6, v4
; SI-NEXT:    v_add_i32_e32 v5, vcc, s6, v5
; SI-NEXT:    v_add_i32_e32 v6, vcc, s6, v6
; SI-NEXT:    v_add_i32_e32 v7, vcc, s6, v7
; SI-NEXT:    v_add_i32_e32 v8, vcc, s6, v8
; SI-NEXT:    v_add_i32_e32 v9, vcc, s6, v9
; SI-NEXT:    s_waitcnt vmcnt(7)
; SI-NEXT:    v_or_b32_e32 v12, v13, v12
; SI-NEXT:    v_add_i32_e32 v13, vcc, 3, v38
; SI-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; SI-NEXT:    s_waitcnt vmcnt(6)
; SI-NEXT:    v_or_b32_e32 v13, v14, v13
; SI-NEXT:    v_add_i32_e32 v14, vcc, 3, v37
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; SI-NEXT:    s_waitcnt vmcnt(5)
; SI-NEXT:    v_or_b32_e32 v14, v15, v14
; SI-NEXT:    v_add_i32_e32 v15, vcc, 3, v36
; SI-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; SI-NEXT:    s_waitcnt vmcnt(4)
; SI-NEXT:    v_or_b32_e32 v15, v16, v15
; SI-NEXT:    v_add_i32_e32 v16, vcc, 3, v35
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v16
; SI-NEXT:    s_waitcnt vmcnt(3)
; SI-NEXT:    v_or_b32_e32 v16, v17, v16
; SI-NEXT:    v_add_i32_e32 v17, vcc, 3, v34
; SI-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; SI-NEXT:    s_waitcnt vmcnt(2)
; SI-NEXT:    v_or_b32_e32 v17, v18, v17
; SI-NEXT:    v_add_i32_e32 v18, vcc, 3, v33
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; SI-NEXT:    s_waitcnt vmcnt(1)
; SI-NEXT:    v_or_b32_e32 v18, v19, v18
; SI-NEXT:    v_add_i32_e32 v19, vcc, 3, v32
; SI-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_or_b32_e32 v19, v20, v19
; SI-NEXT:    v_add_i32_e32 v10, vcc, s6, v10
; SI-NEXT:    v_add_i32_e32 v11, vcc, s6, v11
; SI-NEXT:    v_add_i32_e32 v12, vcc, s6, v12
; SI-NEXT:    v_add_i32_e32 v13, vcc, s6, v13
; SI-NEXT:    v_add_i32_e32 v14, vcc, s6, v14
; SI-NEXT:    v_add_i32_e32 v15, vcc, s6, v15
; SI-NEXT:    v_add_i32_e32 v16, vcc, s6, v16
; SI-NEXT:    v_add_i32_e32 v17, vcc, s6, v17
; SI-NEXT:    v_add_i32_e32 v18, vcc, s6, v18
; SI-NEXT:    v_add_i32_e32 v19, vcc, 0x30000, v19
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:  .LBB50_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    buffer_load_dword v63, off, s[0:3], s32 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0)
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v40i16_to_v10f64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; VI-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; VI-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; VI-NEXT:    buffer_store_dword v43, off, s[0:3], s32 ; 4-byte Folded Spill
; VI-NEXT:    v_mov_b32_e32 v32, v19
; VI-NEXT:    v_mov_b32_e32 v33, v18
; VI-NEXT:    v_mov_b32_e32 v34, v17
; VI-NEXT:    v_mov_b32_e32 v35, v16
; VI-NEXT:    v_mov_b32_e32 v36, v15
; VI-NEXT:    v_mov_b32_e32 v37, v14
; VI-NEXT:    v_mov_b32_e32 v38, v13
; VI-NEXT:    v_mov_b32_e32 v39, v12
; VI-NEXT:    v_mov_b32_e32 v48, v11
; VI-NEXT:    v_mov_b32_e32 v49, v10
; VI-NEXT:    v_mov_b32_e32 v50, v9
; VI-NEXT:    v_mov_b32_e32 v51, v8
; VI-NEXT:    v_mov_b32_e32 v52, v7
; VI-NEXT:    v_mov_b32_e32 v53, v6
; VI-NEXT:    v_mov_b32_e32 v54, v5
; VI-NEXT:    v_mov_b32_e32 v55, v4
; VI-NEXT:    v_mov_b32_e32 v40, v3
; VI-NEXT:    v_mov_b32_e32 v41, v2
; VI-NEXT:    v_mov_b32_e32 v42, v1
; VI-NEXT:    v_mov_b32_e32 v43, v0
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB50_2
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_mov_b32_e32 v19, 16
; VI-NEXT:    v_lshlrev_b32_sdwa v0, v19, v43 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v1, v19, v42 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v2, v19, v41 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v3, v19, v40 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v4, v19, v55 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v5, v19, v54 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v6, v19, v53 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v7, v19, v52 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v8, v19, v51 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v9, v19, v50 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v10, v19, v49 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v11, v19, v48 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v12, v19, v39 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v13, v19, v38 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v14, v19, v37 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v15, v19, v36 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v16, v19, v35 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v17, v19, v34 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v18, v19, v33 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v19, v19, v32 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_or_b32_sdwa v0, v43, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v1, v42, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v2, v41, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v3, v40, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v4, v55, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v5, v54, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v6, v53, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v7, v52, v7 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v8, v51, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v9, v50, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v10, v49, v10 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v11, v48, v11 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v12, v39, v12 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v13, v38, v13 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v14, v37, v14 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v15, v36, v15 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v16, v35, v16 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v17, v34, v17 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v18, v33, v18 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v19, v32, v19 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr43
; VI-NEXT:    ; implicit-def: $vgpr42
; VI-NEXT:    ; implicit-def: $vgpr41
; VI-NEXT:    ; implicit-def: $vgpr40
; VI-NEXT:    ; implicit-def: $vgpr55
; VI-NEXT:    ; implicit-def: $vgpr54
; VI-NEXT:    ; implicit-def: $vgpr53
; VI-NEXT:    ; implicit-def: $vgpr52
; VI-NEXT:    ; implicit-def: $vgpr51
; VI-NEXT:    ; implicit-def: $vgpr50
; VI-NEXT:    ; implicit-def: $vgpr49
; VI-NEXT:    ; implicit-def: $vgpr48
; VI-NEXT:    ; implicit-def: $vgpr39
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr35
; VI-NEXT:    ; implicit-def: $vgpr34
; VI-NEXT:    ; implicit-def: $vgpr33
; VI-NEXT:    ; implicit-def: $vgpr32
; VI-NEXT:  .LBB50_2: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB50_4
; VI-NEXT:  ; %bb.3: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v19, 3
; VI-NEXT:    v_add_u16_e32 v0, 3, v43
; VI-NEXT:    v_add_u16_sdwa v1, v43, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v0, v0, v1
; VI-NEXT:    v_add_u16_e32 v1, 3, v42
; VI-NEXT:    v_add_u16_sdwa v2, v42, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v1, v1, v2
; VI-NEXT:    v_add_u16_e32 v2, 3, v41
; VI-NEXT:    v_add_u16_sdwa v3, v41, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v2, v2, v3
; VI-NEXT:    v_add_u16_e32 v3, 3, v40
; VI-NEXT:    v_add_u16_sdwa v4, v40, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v3, v3, v4
; VI-NEXT:    v_add_u16_e32 v4, 3, v55
; VI-NEXT:    v_add_u16_sdwa v5, v55, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v4, v4, v5
; VI-NEXT:    v_add_u16_e32 v5, 3, v54
; VI-NEXT:    v_add_u16_sdwa v6, v54, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v5, v5, v6
; VI-NEXT:    v_add_u16_e32 v6, 3, v53
; VI-NEXT:    v_add_u16_sdwa v7, v53, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v6, v6, v7
; VI-NEXT:    v_add_u16_e32 v7, 3, v52
; VI-NEXT:    v_add_u16_sdwa v8, v52, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v7, v7, v8
; VI-NEXT:    v_add_u16_e32 v8, 3, v51
; VI-NEXT:    v_add_u16_sdwa v9, v51, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v8, v8, v9
; VI-NEXT:    v_add_u16_e32 v9, 3, v50
; VI-NEXT:    v_add_u16_sdwa v10, v50, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v9, v9, v10
; VI-NEXT:    v_add_u16_e32 v10, 3, v49
; VI-NEXT:    v_add_u16_sdwa v11, v49, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v10, v10, v11
; VI-NEXT:    v_add_u16_e32 v11, 3, v48
; VI-NEXT:    v_add_u16_sdwa v12, v48, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v11, v11, v12
; VI-NEXT:    v_add_u16_e32 v12, 3, v39
; VI-NEXT:    v_add_u16_sdwa v13, v39, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v12, v12, v13
; VI-NEXT:    v_add_u16_e32 v13, 3, v38
; VI-NEXT:    v_add_u16_sdwa v14, v38, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v13, v13, v14
; VI-NEXT:    v_add_u16_e32 v14, 3, v37
; VI-NEXT:    v_add_u16_sdwa v15, v37, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v14, v14, v15
; VI-NEXT:    v_add_u16_e32 v15, 3, v36
; VI-NEXT:    v_add_u16_sdwa v16, v36, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v15, v15, v16
; VI-NEXT:    v_add_u16_e32 v16, 3, v35
; VI-NEXT:    v_add_u16_sdwa v17, v35, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v16, v16, v17
; VI-NEXT:    v_add_u16_e32 v17, 3, v34
; VI-NEXT:    v_add_u16_sdwa v18, v34, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v17, v17, v18
; VI-NEXT:    v_add_u16_e32 v18, 3, v33
; VI-NEXT:    v_add_u16_sdwa v20, v33, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v18, v18, v20
; VI-NEXT:    v_add_u16_e32 v20, 3, v32
; VI-NEXT:    v_add_u16_sdwa v19, v32, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_or_b32_e32 v19, v20, v19
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:  .LBB50_4: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    buffer_load_dword v43, off, s[0:3], s32 ; 4-byte Folded Reload
; VI-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; VI-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; VI-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v40i16_to_v10f64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v63, off, s[0:3], s32 ; 4-byte Folded Spill
; GFX9-NEXT:    v_mov_b32_e32 v32, v19
; GFX9-NEXT:    v_mov_b32_e32 v33, v18
; GFX9-NEXT:    v_mov_b32_e32 v43, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v32
; GFX9-NEXT:    v_mov_b32_e32 v34, v17
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:64 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v33
; GFX9-NEXT:    v_mov_b32_e32 v35, v16
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:68 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v34
; GFX9-NEXT:    v_mov_b32_e32 v36, v15
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:72 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v35
; GFX9-NEXT:    v_mov_b32_e32 v37, v14
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:76 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v36
; GFX9-NEXT:    v_mov_b32_e32 v38, v13
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:80 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v37
; GFX9-NEXT:    v_mov_b32_e32 v39, v12
; GFX9-NEXT:    v_mov_b32_e32 v48, v11
; GFX9-NEXT:    v_mov_b32_e32 v49, v10
; GFX9-NEXT:    v_mov_b32_e32 v50, v9
; GFX9-NEXT:    v_mov_b32_e32 v51, v8
; GFX9-NEXT:    v_mov_b32_e32 v52, v7
; GFX9-NEXT:    v_mov_b32_e32 v53, v6
; GFX9-NEXT:    v_mov_b32_e32 v54, v5
; GFX9-NEXT:    v_mov_b32_e32 v55, v4
; GFX9-NEXT:    v_mov_b32_e32 v40, v3
; GFX9-NEXT:    v_mov_b32_e32 v41, v2
; GFX9-NEXT:    v_mov_b32_e32 v42, v1
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:84 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v38
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:88 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v39
; GFX9-NEXT:    v_lshrrev_b32_e32 v60, 16, v48
; GFX9-NEXT:    v_lshrrev_b32_e32 v61, 16, v49
; GFX9-NEXT:    v_lshrrev_b32_e32 v62, 16, v50
; GFX9-NEXT:    v_lshrrev_b32_e32 v63, 16, v51
; GFX9-NEXT:    v_lshrrev_b32_e32 v44, 16, v52
; GFX9-NEXT:    v_lshrrev_b32_e32 v45, 16, v53
; GFX9-NEXT:    v_lshrrev_b32_e32 v46, 16, v54
; GFX9-NEXT:    v_lshrrev_b32_e32 v47, 16, v55
; GFX9-NEXT:    v_lshrrev_b32_e32 v56, 16, v40
; GFX9-NEXT:    v_lshrrev_b32_e32 v57, 16, v41
; GFX9-NEXT:    v_lshrrev_b32_e32 v58, 16, v42
; GFX9-NEXT:    v_lshrrev_b32_e32 v59, 16, v43
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:92 ; 4-byte Folded Spill
; GFX9-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB50_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_mov_b32 s6, 0x5040100
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v12, 16, v39
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v13, 16, v38
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v14, 16, v37
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v15, 16, v36
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v16, 16, v35
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v17, 16, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v18, 16, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v19, 16, v32
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    v_perm_b32 v0, v59, v43, s6
; GFX9-NEXT:    v_perm_b32 v1, v58, v42, s6
; GFX9-NEXT:    v_perm_b32 v2, v57, v41, s6
; GFX9-NEXT:    v_perm_b32 v3, v56, v40, s6
; GFX9-NEXT:    v_perm_b32 v4, v47, v55, s6
; GFX9-NEXT:    v_perm_b32 v5, v46, v54, s6
; GFX9-NEXT:    v_perm_b32 v6, v45, v53, s6
; GFX9-NEXT:    v_perm_b32 v7, v44, v52, s6
; GFX9-NEXT:    v_perm_b32 v8, v63, v51, s6
; GFX9-NEXT:    v_perm_b32 v9, v62, v50, s6
; GFX9-NEXT:    v_perm_b32 v10, v61, v49, s6
; GFX9-NEXT:    v_perm_b32 v11, v60, v48, s6
; GFX9-NEXT:    v_perm_b32 v12, v12, v39, s6
; GFX9-NEXT:    v_perm_b32 v13, v13, v38, s6
; GFX9-NEXT:    v_perm_b32 v14, v14, v37, s6
; GFX9-NEXT:    v_perm_b32 v15, v15, v36, s6
; GFX9-NEXT:    v_perm_b32 v16, v16, v35, s6
; GFX9-NEXT:    v_perm_b32 v17, v17, v34, s6
; GFX9-NEXT:    v_perm_b32 v18, v18, v33, s6
; GFX9-NEXT:    v_perm_b32 v19, v19, v32, s6
; GFX9-NEXT:    ; implicit-def: $vgpr43
; GFX9-NEXT:    ; implicit-def: $vgpr42
; GFX9-NEXT:    ; implicit-def: $vgpr41
; GFX9-NEXT:    ; implicit-def: $vgpr40
; GFX9-NEXT:    ; implicit-def: $vgpr55
; GFX9-NEXT:    ; implicit-def: $vgpr54
; GFX9-NEXT:    ; implicit-def: $vgpr53
; GFX9-NEXT:    ; implicit-def: $vgpr52
; GFX9-NEXT:    ; implicit-def: $vgpr51
; GFX9-NEXT:    ; implicit-def: $vgpr50
; GFX9-NEXT:    ; implicit-def: $vgpr49
; GFX9-NEXT:    ; implicit-def: $vgpr48
; GFX9-NEXT:    ; implicit-def: $vgpr39
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr35
; GFX9-NEXT:    ; implicit-def: $vgpr34
; GFX9-NEXT:    ; implicit-def: $vgpr33
; GFX9-NEXT:    ; implicit-def: $vgpr32
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr60
; GFX9-NEXT:    ; implicit-def: $vgpr61
; GFX9-NEXT:    ; implicit-def: $vgpr62
; GFX9-NEXT:    ; implicit-def: $vgpr63
; GFX9-NEXT:    ; implicit-def: $vgpr44
; GFX9-NEXT:    ; implicit-def: $vgpr45
; GFX9-NEXT:    ; implicit-def: $vgpr46
; GFX9-NEXT:    ; implicit-def: $vgpr47
; GFX9-NEXT:    ; implicit-def: $vgpr56
; GFX9-NEXT:    ; implicit-def: $vgpr57
; GFX9-NEXT:    ; implicit-def: $vgpr58
; GFX9-NEXT:    ; implicit-def: $vgpr59
; GFX9-NEXT:  .LBB50_2: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB50_4
; GFX9-NEXT:  ; %bb.3: ; %cmp.true
; GFX9-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:92 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:88 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:84 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:80 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:76 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:72 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; GFX9-NEXT:    s_mov_b32 s6, 0x5040100
; GFX9-NEXT:    v_perm_b32 v0, v59, v43, s6
; GFX9-NEXT:    v_perm_b32 v1, v58, v42, s6
; GFX9-NEXT:    v_perm_b32 v2, v57, v41, s6
; GFX9-NEXT:    v_perm_b32 v3, v56, v40, s6
; GFX9-NEXT:    v_perm_b32 v4, v47, v55, s6
; GFX9-NEXT:    v_perm_b32 v5, v46, v54, s6
; GFX9-NEXT:    v_perm_b32 v6, v45, v53, s6
; GFX9-NEXT:    v_perm_b32 v7, v44, v52, s6
; GFX9-NEXT:    v_perm_b32 v8, v63, v51, s6
; GFX9-NEXT:    v_perm_b32 v9, v62, v50, s6
; GFX9-NEXT:    v_perm_b32 v10, v61, v49, s6
; GFX9-NEXT:    v_perm_b32 v11, v60, v48, s6
; GFX9-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v8, v8, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v9, v9, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_waitcnt vmcnt(7)
; GFX9-NEXT:    v_perm_b32 v12, v12, v39, s6
; GFX9-NEXT:    s_waitcnt vmcnt(6)
; GFX9-NEXT:    v_perm_b32 v13, v13, v38, s6
; GFX9-NEXT:    s_waitcnt vmcnt(5)
; GFX9-NEXT:    v_perm_b32 v14, v14, v37, s6
; GFX9-NEXT:    s_waitcnt vmcnt(4)
; GFX9-NEXT:    v_perm_b32 v15, v15, v36, s6
; GFX9-NEXT:    s_waitcnt vmcnt(3)
; GFX9-NEXT:    v_perm_b32 v16, v16, v35, s6
; GFX9-NEXT:    s_waitcnt vmcnt(2)
; GFX9-NEXT:    v_perm_b32 v17, v17, v34, s6
; GFX9-NEXT:    s_waitcnt vmcnt(1)
; GFX9-NEXT:    v_perm_b32 v18, v18, v33, s6
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    v_perm_b32 v19, v19, v32, s6
; GFX9-NEXT:    v_pk_add_u16 v12, v12, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v13, v13, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v14, v14, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v15, v15, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v16, v16, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v17, v17, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v18, v18, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v19, v19, 3 op_sel_hi:[1,0]
; GFX9-NEXT:  .LBB50_4: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    buffer_load_dword v63, off, s[0:3], s32 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Reload
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v40i16_to_v10f64:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB50_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB50_4
; GFX11-TRUE16-NEXT:  .LBB50_2: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB50_3: ; %cmp.false
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB50_2
; GFX11-TRUE16-NEXT:  .LBB50_4: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v8, v8, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v9, v9, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v12, v12, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v13, v13, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v14, v14, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v15, v15, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v16, v16, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v17, v17, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v18, v18, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v19, v19, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v40i16_to_v10f64:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v48, 16, v3
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v20
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v37, v0, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v38, v1, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v39, v2, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v48, v3, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v36, v4, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v35, v5, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v34, v6, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v33, v7, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, v32, v8, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, v31, v9, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, v30, v10, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, v29, v11, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, v28, v12, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, v27, v13, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v14, v26, v14, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v15, v25, v15, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v16, v24, v16, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v17, v23, v17, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v18, v22, v18, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v19, v21, v19, 0x5040100
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB50_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB50_4
; GFX11-FAKE16-NEXT:  .LBB50_2: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB50_3: ; %cmp.false
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB50_2
; GFX11-FAKE16-NEXT:  .LBB50_4: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v8, v8, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v9, v9, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v12, v12, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v13, v13, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v14, v14, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v15, v15, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v16, v16, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v17, v17, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v18, v18, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v19, v19, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <40 x i16> %a, splat (i16 3)
  %a2 = bitcast <40 x i16> %a1 to <10 x double>
  br label %end

cmp.false:
  %a3 = bitcast <40 x i16> %a to <10 x double>
  br label %end

end:
  %phi = phi <10 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <10 x double> %phi
}

define inreg <10 x double> @bitcast_v40i16_to_v10f64_scalar(<40 x i16> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v40i16_to_v10f64_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_store_dword v20, off, s[0:3], s32 ; 4-byte Folded Spill
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_writelane_b32 v20, s36, 0
; SI-NEXT:    v_writelane_b32 v20, s37, 1
; SI-NEXT:    v_writelane_b32 v20, s38, 2
; SI-NEXT:    v_writelane_b32 v20, s39, 3
; SI-NEXT:    v_writelane_b32 v20, s48, 4
; SI-NEXT:    v_writelane_b32 v20, s49, 5
; SI-NEXT:    v_writelane_b32 v20, s50, 6
; SI-NEXT:    v_writelane_b32 v20, s51, 7
; SI-NEXT:    v_writelane_b32 v20, s52, 8
; SI-NEXT:    v_writelane_b32 v20, s53, 9
; SI-NEXT:    v_writelane_b32 v20, s54, 10
; SI-NEXT:    v_writelane_b32 v20, s55, 11
; SI-NEXT:    v_writelane_b32 v20, s64, 12
; SI-NEXT:    v_writelane_b32 v20, s65, 13
; SI-NEXT:    v_writelane_b32 v20, s66, 14
; SI-NEXT:    v_writelane_b32 v20, s67, 15
; SI-NEXT:    v_readfirstlane_b32 s7, v5
; SI-NEXT:    v_readfirstlane_b32 s9, v4
; SI-NEXT:    v_readfirstlane_b32 s12, v3
; SI-NEXT:    v_readfirstlane_b32 s15, v2
; SI-NEXT:    v_readfirstlane_b32 s74, v1
; SI-NEXT:    v_readfirstlane_b32 s77, v0
; SI-NEXT:    s_lshr_b32 s11, s29, 16
; SI-NEXT:    s_lshr_b32 s13, s28, 16
; SI-NEXT:    s_lshr_b32 s72, s27, 16
; SI-NEXT:    s_lshr_b32 s75, s26, 16
; SI-NEXT:    s_lshr_b32 s78, s25, 16
; SI-NEXT:    s_lshr_b32 s79, s24, 16
; SI-NEXT:    s_lshr_b32 s88, s23, 16
; SI-NEXT:    s_lshr_b32 s89, s22, 16
; SI-NEXT:    s_lshr_b32 s90, s21, 16
; SI-NEXT:    s_lshr_b32 s91, s20, 16
; SI-NEXT:    s_lshr_b32 s92, s19, 16
; SI-NEXT:    s_lshr_b32 s93, s18, 16
; SI-NEXT:    s_lshr_b32 s94, s17, 16
; SI-NEXT:    s_lshr_b32 s95, s16, 16
; SI-NEXT:    s_lshr_b32 s6, s7, 16
; SI-NEXT:    s_lshr_b32 s8, s9, 16
; SI-NEXT:    s_lshr_b32 s10, s12, 16
; SI-NEXT:    s_lshr_b32 s14, s15, 16
; SI-NEXT:    s_lshr_b32 s73, s74, 16
; SI-NEXT:    s_lshr_b32 s76, s77, 16
; SI-NEXT:    v_readfirstlane_b32 s4, v6
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    s_cbranch_scc0 .LBB51_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s95, 16
; SI-NEXT:    s_or_b32 s36, s4, s5
; SI-NEXT:    s_and_b32 s4, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s94, 16
; SI-NEXT:    s_or_b32 s37, s4, s5
; SI-NEXT:    s_and_b32 s4, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s93, 16
; SI-NEXT:    s_or_b32 s38, s4, s5
; SI-NEXT:    s_and_b32 s4, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s92, 16
; SI-NEXT:    s_or_b32 s39, s4, s5
; SI-NEXT:    s_and_b32 s4, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s91, 16
; SI-NEXT:    s_or_b32 s40, s4, s5
; SI-NEXT:    s_and_b32 s4, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s90, 16
; SI-NEXT:    s_or_b32 s41, s4, s5
; SI-NEXT:    s_and_b32 s4, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s89, 16
; SI-NEXT:    s_or_b32 s42, s4, s5
; SI-NEXT:    s_and_b32 s4, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s88, 16
; SI-NEXT:    s_or_b32 s43, s4, s5
; SI-NEXT:    s_and_b32 s4, s24, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s79, 16
; SI-NEXT:    s_or_b32 s44, s4, s5
; SI-NEXT:    s_and_b32 s4, s25, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s78, 16
; SI-NEXT:    s_or_b32 s45, s4, s5
; SI-NEXT:    s_and_b32 s4, s26, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s75, 16
; SI-NEXT:    s_or_b32 s46, s4, s5
; SI-NEXT:    s_and_b32 s4, s27, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s72, 16
; SI-NEXT:    s_or_b32 s47, s4, s5
; SI-NEXT:    s_and_b32 s4, s28, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s13, 16
; SI-NEXT:    s_or_b32 s48, s4, s5
; SI-NEXT:    s_and_b32 s4, s29, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s11, 16
; SI-NEXT:    s_or_b32 s49, s4, s5
; SI-NEXT:    s_and_b32 s4, s77, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s76, 16
; SI-NEXT:    s_or_b32 s50, s4, s5
; SI-NEXT:    s_and_b32 s4, s74, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s73, 16
; SI-NEXT:    s_or_b32 s51, s4, s5
; SI-NEXT:    s_and_b32 s4, s15, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s14, 16
; SI-NEXT:    s_or_b32 s52, s4, s5
; SI-NEXT:    s_and_b32 s4, s12, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s10, 16
; SI-NEXT:    s_or_b32 s53, s4, s5
; SI-NEXT:    s_and_b32 s4, s9, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s8, 16
; SI-NEXT:    s_or_b32 s54, s4, s5
; SI-NEXT:    s_and_b32 s4, s7, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s6, 16
; SI-NEXT:    s_or_b32 s55, s4, s5
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    s_cbranch_execnz .LBB51_3
; SI-NEXT:  .LBB51_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s95, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s17, s17, 3
; SI-NEXT:    s_add_i32 s36, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s94, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_add_i32 s37, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s93, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s19, s19, 3
; SI-NEXT:    s_add_i32 s38, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s92, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_add_i32 s39, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s91, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s21, s21, 3
; SI-NEXT:    s_add_i32 s40, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s90, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_add_i32 s41, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s89, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s23, s23, 3
; SI-NEXT:    s_add_i32 s42, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s88, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s24, s24, 3
; SI-NEXT:    s_add_i32 s43, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s24, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s79, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s25, s25, 3
; SI-NEXT:    s_add_i32 s44, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s25, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s78, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s26, s26, 3
; SI-NEXT:    s_add_i32 s45, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s26, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s75, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s27, s27, 3
; SI-NEXT:    s_add_i32 s46, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s27, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s72, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s28, s28, 3
; SI-NEXT:    s_add_i32 s47, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s28, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s13, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s29, s29, 3
; SI-NEXT:    s_add_i32 s48, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s29, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s11, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s77, s77, 3
; SI-NEXT:    s_add_i32 s49, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s77, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s76, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s74, s74, 3
; SI-NEXT:    s_add_i32 s50, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s74, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s73, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s15, s15, 3
; SI-NEXT:    s_add_i32 s51, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s15, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s14, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s12, s12, 3
; SI-NEXT:    s_add_i32 s52, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s12, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s10, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s9, s9, 3
; SI-NEXT:    s_add_i32 s53, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s9, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s8, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s7, s7, 3
; SI-NEXT:    s_add_i32 s54, s4, 0x30000
; SI-NEXT:    s_and_b32 s4, s7, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s6, 16
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_add_i32 s55, s4, 0x30000
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:  .LBB51_3: ; %end
; SI-NEXT:    v_mov_b32_e32 v0, s36
; SI-NEXT:    v_mov_b32_e32 v1, s37
; SI-NEXT:    v_mov_b32_e32 v2, s38
; SI-NEXT:    v_mov_b32_e32 v3, s39
; SI-NEXT:    v_mov_b32_e32 v4, s40
; SI-NEXT:    v_mov_b32_e32 v5, s41
; SI-NEXT:    v_mov_b32_e32 v6, s42
; SI-NEXT:    v_mov_b32_e32 v7, s43
; SI-NEXT:    v_mov_b32_e32 v8, s44
; SI-NEXT:    v_mov_b32_e32 v9, s45
; SI-NEXT:    v_mov_b32_e32 v10, s46
; SI-NEXT:    v_mov_b32_e32 v11, s47
; SI-NEXT:    v_mov_b32_e32 v12, s48
; SI-NEXT:    v_mov_b32_e32 v13, s49
; SI-NEXT:    v_mov_b32_e32 v14, s50
; SI-NEXT:    v_mov_b32_e32 v15, s51
; SI-NEXT:    v_mov_b32_e32 v16, s52
; SI-NEXT:    v_mov_b32_e32 v17, s53
; SI-NEXT:    v_mov_b32_e32 v18, s54
; SI-NEXT:    v_mov_b32_e32 v19, s55
; SI-NEXT:    v_readlane_b32 s67, v20, 15
; SI-NEXT:    v_readlane_b32 s66, v20, 14
; SI-NEXT:    v_readlane_b32 s65, v20, 13
; SI-NEXT:    v_readlane_b32 s64, v20, 12
; SI-NEXT:    v_readlane_b32 s55, v20, 11
; SI-NEXT:    v_readlane_b32 s54, v20, 10
; SI-NEXT:    v_readlane_b32 s53, v20, 9
; SI-NEXT:    v_readlane_b32 s52, v20, 8
; SI-NEXT:    v_readlane_b32 s51, v20, 7
; SI-NEXT:    v_readlane_b32 s50, v20, 6
; SI-NEXT:    v_readlane_b32 s49, v20, 5
; SI-NEXT:    v_readlane_b32 s48, v20, 4
; SI-NEXT:    v_readlane_b32 s39, v20, 3
; SI-NEXT:    v_readlane_b32 s38, v20, 2
; SI-NEXT:    v_readlane_b32 s37, v20, 1
; SI-NEXT:    v_readlane_b32 s36, v20, 0
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_load_dword v20, off, s[0:3], s32 ; 4-byte Folded Reload
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB51_4:
; SI-NEXT:    ; implicit-def: $sgpr36_sgpr37_sgpr38_sgpr39_sgpr40_sgpr41_sgpr42_sgpr43_sgpr44_sgpr45_sgpr46_sgpr47_sgpr48_sgpr49_sgpr50_sgpr51_sgpr52_sgpr53_sgpr54_sgpr55_sgpr56_sgpr57_sgpr58_sgpr59_sgpr60_sgpr61_sgpr62_sgpr63_sgpr64_sgpr65_sgpr66_sgpr67
; SI-NEXT:    s_branch .LBB51_2
;
; VI-LABEL: bitcast_v40i16_to_v10f64_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_store_dword v20, off, s[0:3], s32 ; 4-byte Folded Spill
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    v_writelane_b32 v20, s34, 0
; VI-NEXT:    v_writelane_b32 v20, s35, 1
; VI-NEXT:    v_writelane_b32 v20, s36, 2
; VI-NEXT:    v_writelane_b32 v20, s37, 3
; VI-NEXT:    v_writelane_b32 v20, s38, 4
; VI-NEXT:    v_writelane_b32 v20, s39, 5
; VI-NEXT:    v_writelane_b32 v20, s48, 6
; VI-NEXT:    v_writelane_b32 v20, s49, 7
; VI-NEXT:    v_writelane_b32 v20, s50, 8
; VI-NEXT:    v_writelane_b32 v20, s51, 9
; VI-NEXT:    v_writelane_b32 v20, s52, 10
; VI-NEXT:    v_writelane_b32 v20, s53, 11
; VI-NEXT:    v_writelane_b32 v20, s54, 12
; VI-NEXT:    v_writelane_b32 v20, s55, 13
; VI-NEXT:    v_writelane_b32 v20, s64, 14
; VI-NEXT:    v_writelane_b32 v20, s65, 15
; VI-NEXT:    v_writelane_b32 v20, s66, 16
; VI-NEXT:    v_writelane_b32 v20, s67, 17
; VI-NEXT:    v_writelane_b32 v20, s30, 18
; VI-NEXT:    v_writelane_b32 v20, s31, 19
; VI-NEXT:    v_readfirstlane_b32 s7, v5
; VI-NEXT:    v_readfirstlane_b32 s9, v4
; VI-NEXT:    v_readfirstlane_b32 s12, v3
; VI-NEXT:    v_readfirstlane_b32 s15, v2
; VI-NEXT:    v_readfirstlane_b32 s74, v1
; VI-NEXT:    v_readfirstlane_b32 s77, v0
; VI-NEXT:    s_lshr_b32 s11, s29, 16
; VI-NEXT:    s_lshr_b32 s13, s28, 16
; VI-NEXT:    s_lshr_b32 s72, s27, 16
; VI-NEXT:    s_lshr_b32 s75, s26, 16
; VI-NEXT:    s_lshr_b32 s78, s25, 16
; VI-NEXT:    s_lshr_b32 s79, s24, 16
; VI-NEXT:    s_lshr_b32 s88, s23, 16
; VI-NEXT:    s_lshr_b32 s89, s22, 16
; VI-NEXT:    s_lshr_b32 s90, s21, 16
; VI-NEXT:    s_lshr_b32 s91, s20, 16
; VI-NEXT:    s_lshr_b32 s30, s19, 16
; VI-NEXT:    s_lshr_b32 s31, s18, 16
; VI-NEXT:    s_lshr_b32 s34, s17, 16
; VI-NEXT:    s_lshr_b32 s35, s16, 16
; VI-NEXT:    s_lshr_b32 s6, s7, 16
; VI-NEXT:    s_lshr_b32 s8, s9, 16
; VI-NEXT:    s_lshr_b32 s10, s12, 16
; VI-NEXT:    s_lshr_b32 s14, s15, 16
; VI-NEXT:    s_lshr_b32 s73, s74, 16
; VI-NEXT:    s_lshr_b32 s76, s77, 16
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    s_cbranch_scc0 .LBB51_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_and_b32 s4, 0xffff, s16
; VI-NEXT:    s_lshl_b32 s5, s35, 16
; VI-NEXT:    s_or_b32 s36, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s17
; VI-NEXT:    s_lshl_b32 s5, s34, 16
; VI-NEXT:    s_or_b32 s37, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s18
; VI-NEXT:    s_lshl_b32 s5, s31, 16
; VI-NEXT:    s_or_b32 s38, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s19
; VI-NEXT:    s_lshl_b32 s5, s30, 16
; VI-NEXT:    s_or_b32 s39, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s20
; VI-NEXT:    s_lshl_b32 s5, s91, 16
; VI-NEXT:    s_or_b32 s40, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s21
; VI-NEXT:    s_lshl_b32 s5, s90, 16
; VI-NEXT:    s_or_b32 s41, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s22
; VI-NEXT:    s_lshl_b32 s5, s89, 16
; VI-NEXT:    s_or_b32 s42, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s23
; VI-NEXT:    s_lshl_b32 s5, s88, 16
; VI-NEXT:    s_or_b32 s43, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s24
; VI-NEXT:    s_lshl_b32 s5, s79, 16
; VI-NEXT:    s_or_b32 s44, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s25
; VI-NEXT:    s_lshl_b32 s5, s78, 16
; VI-NEXT:    s_or_b32 s45, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s26
; VI-NEXT:    s_lshl_b32 s5, s75, 16
; VI-NEXT:    s_or_b32 s46, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s27
; VI-NEXT:    s_lshl_b32 s5, s72, 16
; VI-NEXT:    s_or_b32 s47, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s28
; VI-NEXT:    s_lshl_b32 s5, s13, 16
; VI-NEXT:    s_or_b32 s48, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s29
; VI-NEXT:    s_lshl_b32 s5, s11, 16
; VI-NEXT:    s_or_b32 s49, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s77
; VI-NEXT:    s_lshl_b32 s5, s76, 16
; VI-NEXT:    s_or_b32 s50, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s74
; VI-NEXT:    s_lshl_b32 s5, s73, 16
; VI-NEXT:    s_or_b32 s51, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s15
; VI-NEXT:    s_lshl_b32 s5, s14, 16
; VI-NEXT:    s_or_b32 s52, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s12
; VI-NEXT:    s_lshl_b32 s5, s10, 16
; VI-NEXT:    s_or_b32 s53, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s9
; VI-NEXT:    s_lshl_b32 s5, s8, 16
; VI-NEXT:    s_or_b32 s54, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s7
; VI-NEXT:    s_lshl_b32 s5, s6, 16
; VI-NEXT:    s_or_b32 s55, s4, s5
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    s_cbranch_execnz .LBB51_3
; VI-NEXT:  .LBB51_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s16, s16, 3
; VI-NEXT:    s_and_b32 s4, s16, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s35, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s17, s17, 3
; VI-NEXT:    s_add_i32 s36, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s17, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s34, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s18, s18, 3
; VI-NEXT:    s_add_i32 s37, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s18, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s31, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s19, s19, 3
; VI-NEXT:    s_add_i32 s38, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s19, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s30, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s20, s20, 3
; VI-NEXT:    s_add_i32 s39, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s20, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s91, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s21, s21, 3
; VI-NEXT:    s_add_i32 s40, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s21, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s90, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s22, s22, 3
; VI-NEXT:    s_add_i32 s41, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s22, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s89, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s23, s23, 3
; VI-NEXT:    s_add_i32 s42, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s23, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s88, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s24, s24, 3
; VI-NEXT:    s_add_i32 s43, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s24, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s79, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s25, s25, 3
; VI-NEXT:    s_add_i32 s44, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s25, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s78, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s26, s26, 3
; VI-NEXT:    s_add_i32 s45, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s26, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s75, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s27, s27, 3
; VI-NEXT:    s_add_i32 s46, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s27, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s72, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s28, s28, 3
; VI-NEXT:    s_add_i32 s47, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s28, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s13, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s29, s29, 3
; VI-NEXT:    s_add_i32 s48, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s29, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s11, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s77, s77, 3
; VI-NEXT:    s_add_i32 s49, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s77, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s76, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s74, s74, 3
; VI-NEXT:    s_add_i32 s50, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s74, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s73, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s15, s15, 3
; VI-NEXT:    s_add_i32 s51, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s15, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s14, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s12, s12, 3
; VI-NEXT:    s_add_i32 s52, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s12, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s10, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s9, s9, 3
; VI-NEXT:    s_add_i32 s53, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s9, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s8, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s7, s7, 3
; VI-NEXT:    s_add_i32 s54, s4, 0x30000
; VI-NEXT:    s_and_b32 s4, s7, 0xffff
; VI-NEXT:    s_lshl_b32 s5, s6, 16
; VI-NEXT:    s_or_b32 s4, s5, s4
; VI-NEXT:    s_add_i32 s55, s4, 0x30000
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:    ; implicit-def: $sgpr4
; VI-NEXT:  .LBB51_3: ; %end
; VI-NEXT:    v_readlane_b32 s30, v20, 18
; VI-NEXT:    v_mov_b32_e32 v0, s36
; VI-NEXT:    v_mov_b32_e32 v1, s37
; VI-NEXT:    v_mov_b32_e32 v2, s38
; VI-NEXT:    v_mov_b32_e32 v3, s39
; VI-NEXT:    v_mov_b32_e32 v4, s40
; VI-NEXT:    v_mov_b32_e32 v5, s41
; VI-NEXT:    v_mov_b32_e32 v6, s42
; VI-NEXT:    v_mov_b32_e32 v7, s43
; VI-NEXT:    v_mov_b32_e32 v8, s44
; VI-NEXT:    v_mov_b32_e32 v9, s45
; VI-NEXT:    v_mov_b32_e32 v10, s46
; VI-NEXT:    v_mov_b32_e32 v11, s47
; VI-NEXT:    v_mov_b32_e32 v12, s48
; VI-NEXT:    v_mov_b32_e32 v13, s49
; VI-NEXT:    v_mov_b32_e32 v14, s50
; VI-NEXT:    v_mov_b32_e32 v15, s51
; VI-NEXT:    v_mov_b32_e32 v16, s52
; VI-NEXT:    v_mov_b32_e32 v17, s53
; VI-NEXT:    v_mov_b32_e32 v18, s54
; VI-NEXT:    v_mov_b32_e32 v19, s55
; VI-NEXT:    v_readlane_b32 s31, v20, 19
; VI-NEXT:    v_readlane_b32 s67, v20, 17
; VI-NEXT:    v_readlane_b32 s66, v20, 16
; VI-NEXT:    v_readlane_b32 s65, v20, 15
; VI-NEXT:    v_readlane_b32 s64, v20, 14
; VI-NEXT:    v_readlane_b32 s55, v20, 13
; VI-NEXT:    v_readlane_b32 s54, v20, 12
; VI-NEXT:    v_readlane_b32 s53, v20, 11
; VI-NEXT:    v_readlane_b32 s52, v20, 10
; VI-NEXT:    v_readlane_b32 s51, v20, 9
; VI-NEXT:    v_readlane_b32 s50, v20, 8
; VI-NEXT:    v_readlane_b32 s49, v20, 7
; VI-NEXT:    v_readlane_b32 s48, v20, 6
; VI-NEXT:    v_readlane_b32 s39, v20, 5
; VI-NEXT:    v_readlane_b32 s38, v20, 4
; VI-NEXT:    v_readlane_b32 s37, v20, 3
; VI-NEXT:    v_readlane_b32 s36, v20, 2
; VI-NEXT:    v_readlane_b32 s35, v20, 1
; VI-NEXT:    v_readlane_b32 s34, v20, 0
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_load_dword v20, off, s[0:3], s32 ; 4-byte Folded Reload
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB51_4:
; VI-NEXT:    ; implicit-def: $sgpr36_sgpr37_sgpr38_sgpr39_sgpr40_sgpr41_sgpr42_sgpr43_sgpr44_sgpr45_sgpr46_sgpr47_sgpr48_sgpr49_sgpr50_sgpr51_sgpr52_sgpr53_sgpr54_sgpr55_sgpr56_sgpr57_sgpr58_sgpr59_sgpr60_sgpr61_sgpr62_sgpr63_sgpr64_sgpr65_sgpr66_sgpr67
; VI-NEXT:    s_branch .LBB51_2
;
; GFX9-LABEL: bitcast_v40i16_to_v10f64_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    v_writelane_b32 v32, s36, 0
; GFX9-NEXT:    v_writelane_b32 v32, s37, 1
; GFX9-NEXT:    v_writelane_b32 v32, s38, 2
; GFX9-NEXT:    v_writelane_b32 v32, s39, 3
; GFX9-NEXT:    v_writelane_b32 v32, s48, 4
; GFX9-NEXT:    v_writelane_b32 v32, s49, 5
; GFX9-NEXT:    v_writelane_b32 v32, s50, 6
; GFX9-NEXT:    v_writelane_b32 v32, s51, 7
; GFX9-NEXT:    v_writelane_b32 v32, s52, 8
; GFX9-NEXT:    v_writelane_b32 v32, s53, 9
; GFX9-NEXT:    v_writelane_b32 v32, s54, 10
; GFX9-NEXT:    v_writelane_b32 v32, s55, 11
; GFX9-NEXT:    v_readfirstlane_b32 s56, v5
; GFX9-NEXT:    v_readfirstlane_b32 s58, v4
; GFX9-NEXT:    v_readfirstlane_b32 s60, v3
; GFX9-NEXT:    v_readfirstlane_b32 s62, v2
; GFX9-NEXT:    v_readfirstlane_b32 s72, v1
; GFX9-NEXT:    v_readfirstlane_b32 s74, v0
; GFX9-NEXT:    s_lshr_b32 s4, s29, 16
; GFX9-NEXT:    s_lshr_b32 s5, s28, 16
; GFX9-NEXT:    s_lshr_b32 s6, s27, 16
; GFX9-NEXT:    s_lshr_b32 s7, s26, 16
; GFX9-NEXT:    s_lshr_b32 s8, s25, 16
; GFX9-NEXT:    s_lshr_b32 s9, s24, 16
; GFX9-NEXT:    s_lshr_b32 s10, s23, 16
; GFX9-NEXT:    s_lshr_b32 s11, s22, 16
; GFX9-NEXT:    s_lshr_b32 s12, s21, 16
; GFX9-NEXT:    s_lshr_b32 s13, s20, 16
; GFX9-NEXT:    s_lshr_b32 s14, s19, 16
; GFX9-NEXT:    s_lshr_b32 s15, s18, 16
; GFX9-NEXT:    s_lshr_b32 s40, s17, 16
; GFX9-NEXT:    s_lshr_b32 s41, s16, 16
; GFX9-NEXT:    s_lshr_b32 s57, s56, 16
; GFX9-NEXT:    s_lshr_b32 s59, s58, 16
; GFX9-NEXT:    s_lshr_b32 s61, s60, 16
; GFX9-NEXT:    s_lshr_b32 s63, s62, 16
; GFX9-NEXT:    s_lshr_b32 s73, s72, 16
; GFX9-NEXT:    s_lshr_b32 s75, s74, 16
; GFX9-NEXT:    v_readfirstlane_b32 s42, v6
; GFX9-NEXT:    s_cmp_lg_u32 s42, 0
; GFX9-NEXT:    s_pack_ll_b32_b16 s36, s16, s41
; GFX9-NEXT:    s_pack_ll_b32_b16 s37, s17, s40
; GFX9-NEXT:    s_pack_ll_b32_b16 s38, s18, s15
; GFX9-NEXT:    s_pack_ll_b32_b16 s39, s19, s14
; GFX9-NEXT:    s_pack_ll_b32_b16 s40, s20, s13
; GFX9-NEXT:    s_pack_ll_b32_b16 s41, s21, s12
; GFX9-NEXT:    s_pack_ll_b32_b16 s42, s22, s11
; GFX9-NEXT:    s_pack_ll_b32_b16 s43, s23, s10
; GFX9-NEXT:    s_pack_ll_b32_b16 s44, s24, s9
; GFX9-NEXT:    s_pack_ll_b32_b16 s45, s25, s8
; GFX9-NEXT:    s_pack_ll_b32_b16 s46, s26, s7
; GFX9-NEXT:    s_pack_ll_b32_b16 s47, s27, s6
; GFX9-NEXT:    s_pack_ll_b32_b16 s48, s28, s5
; GFX9-NEXT:    s_pack_ll_b32_b16 s49, s29, s4
; GFX9-NEXT:    s_pack_ll_b32_b16 s50, s74, s75
; GFX9-NEXT:    s_pack_ll_b32_b16 s51, s72, s73
; GFX9-NEXT:    s_pack_ll_b32_b16 s52, s62, s63
; GFX9-NEXT:    s_pack_ll_b32_b16 s53, s60, s61
; GFX9-NEXT:    s_pack_ll_b32_b16 s54, s58, s59
; GFX9-NEXT:    s_pack_ll_b32_b16 s55, s56, s57
; GFX9-NEXT:    s_cbranch_scc0 .LBB51_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB51_4
; GFX9-NEXT:  .LBB51_2: ; %cmp.true
; GFX9-NEXT:    v_pk_add_u16 v0, s36, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v1, s37, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v2, s38, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v3, s39, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v4, s40, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v5, s41, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, s42, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v7, s43, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v8, s44, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v9, s45, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v10, s46, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v11, s47, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v12, s48, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v13, s49, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v14, s50, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v15, s51, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v16, s52, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v17, s53, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v18, s54, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v19, s55, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_branch .LBB51_5
; GFX9-NEXT:  .LBB51_3:
; GFX9-NEXT:    s_branch .LBB51_2
; GFX9-NEXT:  .LBB51_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s36
; GFX9-NEXT:    v_mov_b32_e32 v1, s37
; GFX9-NEXT:    v_mov_b32_e32 v2, s38
; GFX9-NEXT:    v_mov_b32_e32 v3, s39
; GFX9-NEXT:    v_mov_b32_e32 v4, s40
; GFX9-NEXT:    v_mov_b32_e32 v5, s41
; GFX9-NEXT:    v_mov_b32_e32 v6, s42
; GFX9-NEXT:    v_mov_b32_e32 v7, s43
; GFX9-NEXT:    v_mov_b32_e32 v8, s44
; GFX9-NEXT:    v_mov_b32_e32 v9, s45
; GFX9-NEXT:    v_mov_b32_e32 v10, s46
; GFX9-NEXT:    v_mov_b32_e32 v11, s47
; GFX9-NEXT:    v_mov_b32_e32 v12, s48
; GFX9-NEXT:    v_mov_b32_e32 v13, s49
; GFX9-NEXT:    v_mov_b32_e32 v14, s50
; GFX9-NEXT:    v_mov_b32_e32 v15, s51
; GFX9-NEXT:    v_mov_b32_e32 v16, s52
; GFX9-NEXT:    v_mov_b32_e32 v17, s53
; GFX9-NEXT:    v_mov_b32_e32 v18, s54
; GFX9-NEXT:    v_mov_b32_e32 v19, s55
; GFX9-NEXT:    v_mov_b32_e32 v20, s56
; GFX9-NEXT:    v_mov_b32_e32 v21, s57
; GFX9-NEXT:    v_mov_b32_e32 v22, s58
; GFX9-NEXT:    v_mov_b32_e32 v23, s59
; GFX9-NEXT:    v_mov_b32_e32 v24, s60
; GFX9-NEXT:    v_mov_b32_e32 v25, s61
; GFX9-NEXT:    v_mov_b32_e32 v26, s62
; GFX9-NEXT:    v_mov_b32_e32 v27, s63
; GFX9-NEXT:    v_mov_b32_e32 v28, s64
; GFX9-NEXT:    v_mov_b32_e32 v29, s65
; GFX9-NEXT:    v_mov_b32_e32 v30, s66
; GFX9-NEXT:    v_mov_b32_e32 v31, s67
; GFX9-NEXT:  .LBB51_5: ; %end
; GFX9-NEXT:    v_readlane_b32 s55, v32, 11
; GFX9-NEXT:    v_readlane_b32 s54, v32, 10
; GFX9-NEXT:    v_readlane_b32 s53, v32, 9
; GFX9-NEXT:    v_readlane_b32 s52, v32, 8
; GFX9-NEXT:    v_readlane_b32 s51, v32, 7
; GFX9-NEXT:    v_readlane_b32 s50, v32, 6
; GFX9-NEXT:    v_readlane_b32 s49, v32, 5
; GFX9-NEXT:    v_readlane_b32 s48, v32, 4
; GFX9-NEXT:    v_readlane_b32 s39, v32, 3
; GFX9-NEXT:    v_readlane_b32 s38, v32, 2
; GFX9-NEXT:    v_readlane_b32 s37, v32, 1
; GFX9-NEXT:    v_readlane_b32 s36, v32, 0
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v40i16_to_v10f64_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    v_readfirstlane_b32 s45, v1
; GFX11-NEXT:    v_readfirstlane_b32 s46, v0
; GFX11-NEXT:    v_readfirstlane_b32 s56, v2
; GFX11-NEXT:    s_lshr_b32 s41, s29, 16
; GFX11-NEXT:    s_lshr_b32 s42, s28, 16
; GFX11-NEXT:    s_lshr_b32 s15, s27, 16
; GFX11-NEXT:    s_lshr_b32 s14, s26, 16
; GFX11-NEXT:    s_lshr_b32 s13, s25, 16
; GFX11-NEXT:    s_lshr_b32 s12, s24, 16
; GFX11-NEXT:    s_lshr_b32 s11, s23, 16
; GFX11-NEXT:    s_lshr_b32 s10, s22, 16
; GFX11-NEXT:    s_lshr_b32 s9, s21, 16
; GFX11-NEXT:    s_lshr_b32 s8, s20, 16
; GFX11-NEXT:    s_lshr_b32 s7, s19, 16
; GFX11-NEXT:    s_lshr_b32 s6, s18, 16
; GFX11-NEXT:    s_lshr_b32 s5, s17, 16
; GFX11-NEXT:    s_lshr_b32 s4, s16, 16
; GFX11-NEXT:    s_lshr_b32 s43, s3, 16
; GFX11-NEXT:    s_lshr_b32 s44, s2, 16
; GFX11-NEXT:    s_lshr_b32 s47, s1, 16
; GFX11-NEXT:    s_lshr_b32 s57, s0, 16
; GFX11-NEXT:    s_lshr_b32 s58, s45, 16
; GFX11-NEXT:    s_lshr_b32 s59, s46, 16
; GFX11-NEXT:    s_mov_b32 s40, 0
; GFX11-NEXT:    s_cmp_lg_u32 s56, 0
; GFX11-NEXT:    s_pack_ll_b32_b16 s0, s0, s57
; GFX11-NEXT:    s_pack_ll_b32_b16 s1, s1, s47
; GFX11-NEXT:    s_pack_ll_b32_b16 s2, s2, s44
; GFX11-NEXT:    s_pack_ll_b32_b16 s3, s3, s43
; GFX11-NEXT:    s_pack_ll_b32_b16 s4, s16, s4
; GFX11-NEXT:    s_pack_ll_b32_b16 s5, s17, s5
; GFX11-NEXT:    s_pack_ll_b32_b16 s6, s18, s6
; GFX11-NEXT:    s_pack_ll_b32_b16 s7, s19, s7
; GFX11-NEXT:    s_pack_ll_b32_b16 s8, s20, s8
; GFX11-NEXT:    s_pack_ll_b32_b16 s9, s21, s9
; GFX11-NEXT:    s_pack_ll_b32_b16 s10, s22, s10
; GFX11-NEXT:    s_pack_ll_b32_b16 s11, s23, s11
; GFX11-NEXT:    s_pack_ll_b32_b16 s12, s24, s12
; GFX11-NEXT:    s_pack_ll_b32_b16 s13, s25, s13
; GFX11-NEXT:    s_pack_ll_b32_b16 s14, s26, s14
; GFX11-NEXT:    s_pack_ll_b32_b16 s15, s27, s15
; GFX11-NEXT:    s_pack_ll_b32_b16 s16, s28, s42
; GFX11-NEXT:    s_pack_ll_b32_b16 s17, s29, s41
; GFX11-NEXT:    s_pack_ll_b32_b16 s18, s46, s59
; GFX11-NEXT:    s_pack_ll_b32_b16 s19, s45, s58
; GFX11-NEXT:    s_cbranch_scc0 .LBB51_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s40
; GFX11-NEXT:    s_cbranch_vccnz .LBB51_4
; GFX11-NEXT:  .LBB51_2: ; %cmp.true
; GFX11-NEXT:    v_pk_add_u16 v0, s0, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v1, s1, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v2, s2, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v3, s3, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v4, s4, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v5, s5, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v6, s6, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v7, s7, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v8, s8, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v9, s9, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v10, s10, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v11, s11, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v12, s12, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v13, s13, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v14, s14, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v15, s15, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v16, s16, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v17, s17, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v18, s18, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    v_pk_add_u16 v19, s19, 3 op_sel_hi:[1,0]
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB51_3:
; GFX11-NEXT:    s_branch .LBB51_2
; GFX11-NEXT:  .LBB51_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    v_dual_mov_b32 v8, s8 :: v_dual_mov_b32 v9, s9
; GFX11-NEXT:    v_dual_mov_b32 v10, s10 :: v_dual_mov_b32 v11, s11
; GFX11-NEXT:    v_dual_mov_b32 v12, s12 :: v_dual_mov_b32 v13, s13
; GFX11-NEXT:    v_dual_mov_b32 v14, s14 :: v_dual_mov_b32 v15, s15
; GFX11-NEXT:    v_dual_mov_b32 v16, s16 :: v_dual_mov_b32 v17, s17
; GFX11-NEXT:    v_dual_mov_b32 v18, s18 :: v_dual_mov_b32 v19, s19
; GFX11-NEXT:    v_dual_mov_b32 v20, s20 :: v_dual_mov_b32 v21, s21
; GFX11-NEXT:    v_dual_mov_b32 v22, s22 :: v_dual_mov_b32 v23, s23
; GFX11-NEXT:    v_dual_mov_b32 v24, s24 :: v_dual_mov_b32 v25, s25
; GFX11-NEXT:    v_dual_mov_b32 v26, s26 :: v_dual_mov_b32 v27, s27
; GFX11-NEXT:    v_dual_mov_b32 v28, s28 :: v_dual_mov_b32 v29, s29
; GFX11-NEXT:    v_dual_mov_b32 v30, s30 :: v_dual_mov_b32 v31, s31
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <40 x i16> %a, splat (i16 3)
  %a2 = bitcast <40 x i16> %a1 to <10 x double>
  br label %end

cmp.false:
  %a3 = bitcast <40 x i16> %a to <10 x double>
  br label %end

end:
  %phi = phi <10 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <10 x double> %phi
}

define <40 x half> @bitcast_v10f64_to_v40f16(<10 x double> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v10f64_to_v40f16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr29
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr26
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr25
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    ; implicit-def: $vgpr24
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr23
; SI-NEXT:    ; implicit-def: $vgpr31
; SI-NEXT:    ; implicit-def: $vgpr22
; SI-NEXT:    ; implicit-def: $vgpr30
; SI-NEXT:    ; implicit-def: $vgpr21
; SI-NEXT:    ; implicit-def: $vgpr28
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr27
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB52_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_alignbit_b32 v20, v19, v18, 16
; SI-NEXT:    v_alignbit_b32 v21, v17, v16, 16
; SI-NEXT:    v_alignbit_b32 v22, v15, v14, 16
; SI-NEXT:    v_alignbit_b32 v23, v13, v12, 16
; SI-NEXT:    v_alignbit_b32 v24, v11, v10, 16
; SI-NEXT:    v_alignbit_b32 v25, v9, v8, 16
; SI-NEXT:    v_alignbit_b32 v26, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v29, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v32, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v35, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v27, 16, v19
; SI-NEXT:    v_lshrrev_b32_e32 v28, 16, v17
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v15
; SI-NEXT:    v_lshrrev_b32_e32 v31, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v33, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v34, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v36, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v37, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v39, 16, v1
; SI-NEXT:  .LBB52_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB52_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; SI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; SI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; SI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; SI-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; SI-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; SI-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; SI-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; SI-NEXT:    v_add_f64 v[18:19], v[18:19], 1.0
; SI-NEXT:    v_add_f64 v[16:17], v[16:17], 1.0
; SI-NEXT:    v_alignbit_b32 v20, v19, v18, 16
; SI-NEXT:    v_alignbit_b32 v21, v17, v16, 16
; SI-NEXT:    v_alignbit_b32 v22, v15, v14, 16
; SI-NEXT:    v_alignbit_b32 v23, v13, v12, 16
; SI-NEXT:    v_alignbit_b32 v24, v11, v10, 16
; SI-NEXT:    v_alignbit_b32 v25, v9, v8, 16
; SI-NEXT:    v_alignbit_b32 v26, v7, v6, 16
; SI-NEXT:    v_alignbit_b32 v29, v5, v4, 16
; SI-NEXT:    v_alignbit_b32 v32, v3, v2, 16
; SI-NEXT:    v_alignbit_b32 v35, v1, v0, 16
; SI-NEXT:    v_lshrrev_b32_e32 v27, 16, v19
; SI-NEXT:    v_lshrrev_b32_e32 v28, 16, v17
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v15
; SI-NEXT:    v_lshrrev_b32_e32 v31, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v33, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v34, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v36, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v37, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v39, 16, v1
; SI-NEXT:  .LBB52_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_lshlrev_b32_e32 v35, 16, v35
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v32, 16, v32
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_lshlrev_b32_e32 v26, 16, v26
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; SI-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v16
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; SI-NEXT:    v_or_b32_e32 v0, v0, v35
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v35, 16, v39
; SI-NEXT:    v_or_b32_e32 v2, v2, v32
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v32, 16, v38
; SI-NEXT:    v_or_b32_e32 v4, v4, v29
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v29, 16, v37
; SI-NEXT:    v_or_b32_e32 v6, v6, v26
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v26, 16, v36
; SI-NEXT:    v_or_b32_e32 v8, v8, v25
; SI-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; SI-NEXT:    v_lshlrev_b32_e32 v25, 16, v34
; SI-NEXT:    v_or_b32_e32 v10, v10, v24
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; SI-NEXT:    v_lshlrev_b32_e32 v24, 16, v33
; SI-NEXT:    v_or_b32_e32 v12, v12, v23
; SI-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v31
; SI-NEXT:    v_or_b32_e32 v14, v14, v22
; SI-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v30
; SI-NEXT:    v_or_b32_e32 v16, v16, v21
; SI-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v28
; SI-NEXT:    v_or_b32_e32 v18, v18, v20
; SI-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v27
; SI-NEXT:    v_or_b32_e32 v1, v1, v35
; SI-NEXT:    v_or_b32_e32 v3, v3, v32
; SI-NEXT:    v_or_b32_e32 v5, v5, v29
; SI-NEXT:    v_or_b32_e32 v7, v7, v26
; SI-NEXT:    v_or_b32_e32 v9, v9, v25
; SI-NEXT:    v_or_b32_e32 v11, v11, v24
; SI-NEXT:    v_or_b32_e32 v13, v13, v23
; SI-NEXT:    v_or_b32_e32 v15, v15, v22
; SI-NEXT:    v_or_b32_e32 v17, v17, v21
; SI-NEXT:    v_or_b32_e32 v19, v19, v20
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v10f64_to_v40f16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    ; implicit-def: $vgpr39
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr35
; VI-NEXT:    ; implicit-def: $vgpr34
; VI-NEXT:    ; implicit-def: $vgpr33
; VI-NEXT:    ; implicit-def: $vgpr32
; VI-NEXT:    ; implicit-def: $vgpr31
; VI-NEXT:    ; implicit-def: $vgpr30
; VI-NEXT:    ; implicit-def: $vgpr29
; VI-NEXT:    ; implicit-def: $vgpr28
; VI-NEXT:    ; implicit-def: $vgpr27
; VI-NEXT:    ; implicit-def: $vgpr26
; VI-NEXT:    ; implicit-def: $vgpr25
; VI-NEXT:    ; implicit-def: $vgpr24
; VI-NEXT:    ; implicit-def: $vgpr23
; VI-NEXT:    ; implicit-def: $vgpr22
; VI-NEXT:    ; implicit-def: $vgpr21
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB52_2
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; VI-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; VI-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; VI-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; VI-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; VI-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; VI-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; VI-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; VI-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; VI-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; VI-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; VI-NEXT:  .LBB52_2: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB52_4
; VI-NEXT:  ; %bb.3: ; %cmp.true
; VI-NEXT:    v_add_f64 v[18:19], v[18:19], 1.0
; VI-NEXT:    v_add_f64 v[16:17], v[16:17], 1.0
; VI-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; VI-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; VI-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; VI-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; VI-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; VI-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; VI-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; VI-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; VI-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; VI-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; VI-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; VI-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; VI-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; VI-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; VI-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; VI-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; VI-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; VI-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; VI-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; VI-NEXT:  .LBB52_4: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    v_lshlrev_b32_e32 v39, 16, v39
; VI-NEXT:    v_lshlrev_b32_e32 v38, 16, v38
; VI-NEXT:    v_lshlrev_b32_e32 v37, 16, v37
; VI-NEXT:    v_lshlrev_b32_e32 v36, 16, v36
; VI-NEXT:    v_lshlrev_b32_e32 v35, 16, v35
; VI-NEXT:    v_lshlrev_b32_e32 v34, 16, v34
; VI-NEXT:    v_lshlrev_b32_e32 v33, 16, v33
; VI-NEXT:    v_lshlrev_b32_e32 v32, 16, v32
; VI-NEXT:    v_lshlrev_b32_e32 v31, 16, v31
; VI-NEXT:    v_lshlrev_b32_e32 v30, 16, v30
; VI-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; VI-NEXT:    v_lshlrev_b32_e32 v28, 16, v28
; VI-NEXT:    v_lshlrev_b32_e32 v27, 16, v27
; VI-NEXT:    v_lshlrev_b32_e32 v26, 16, v26
; VI-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; VI-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; VI-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; VI-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; VI-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; VI-NEXT:    v_or_b32_sdwa v0, v0, v39 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v1, v1, v38 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v2, v2, v37 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v3, v3, v36 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v4, v4, v35 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v5, v5, v34 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v6, v6, v33 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v7, v7, v32 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v8, v8, v31 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v9, v9, v30 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v10, v10, v29 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v11, v11, v28 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v12, v12, v27 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v13, v13, v26 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v14, v14, v25 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v15, v15, v24 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v16, v16, v23 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v17, v17, v22 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v18, v18, v21 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v19, v19, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v10f64_to_v40f16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    ; implicit-def: $vgpr39
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr35
; GFX9-NEXT:    ; implicit-def: $vgpr34
; GFX9-NEXT:    ; implicit-def: $vgpr33
; GFX9-NEXT:    ; implicit-def: $vgpr32
; GFX9-NEXT:    ; implicit-def: $vgpr31
; GFX9-NEXT:    ; implicit-def: $vgpr30
; GFX9-NEXT:    ; implicit-def: $vgpr29
; GFX9-NEXT:    ; implicit-def: $vgpr28
; GFX9-NEXT:    ; implicit-def: $vgpr27
; GFX9-NEXT:    ; implicit-def: $vgpr26
; GFX9-NEXT:    ; implicit-def: $vgpr25
; GFX9-NEXT:    ; implicit-def: $vgpr24
; GFX9-NEXT:    ; implicit-def: $vgpr23
; GFX9-NEXT:    ; implicit-def: $vgpr22
; GFX9-NEXT:    ; implicit-def: $vgpr21
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB52_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX9-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX9-NEXT:  .LBB52_2: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB52_4
; GFX9-NEXT:  ; %bb.3: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[18:19], v[18:19], 1.0
; GFX9-NEXT:    v_add_f64 v[16:17], v[16:17], 1.0
; GFX9-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GFX9-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GFX9-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GFX9-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GFX9-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX9-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX9-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX9-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX9-NEXT:  .LBB52_4: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_mov_b32 s4, 0x5040100
; GFX9-NEXT:    v_perm_b32 v0, v39, v0, s4
; GFX9-NEXT:    v_perm_b32 v1, v38, v1, s4
; GFX9-NEXT:    v_perm_b32 v2, v37, v2, s4
; GFX9-NEXT:    v_perm_b32 v3, v36, v3, s4
; GFX9-NEXT:    v_perm_b32 v4, v35, v4, s4
; GFX9-NEXT:    v_perm_b32 v5, v34, v5, s4
; GFX9-NEXT:    v_perm_b32 v6, v33, v6, s4
; GFX9-NEXT:    v_perm_b32 v7, v32, v7, s4
; GFX9-NEXT:    v_perm_b32 v8, v31, v8, s4
; GFX9-NEXT:    v_perm_b32 v9, v30, v9, s4
; GFX9-NEXT:    v_perm_b32 v10, v29, v10, s4
; GFX9-NEXT:    v_perm_b32 v11, v28, v11, s4
; GFX9-NEXT:    v_perm_b32 v12, v27, v12, s4
; GFX9-NEXT:    v_perm_b32 v13, v26, v13, s4
; GFX9-NEXT:    v_perm_b32 v14, v25, v14, s4
; GFX9-NEXT:    v_perm_b32 v15, v24, v15, s4
; GFX9-NEXT:    v_perm_b32 v16, v23, v16, s4
; GFX9-NEXT:    v_perm_b32 v17, v22, v17, s4
; GFX9-NEXT:    v_perm_b32 v18, v21, v18, s4
; GFX9-NEXT:    v_perm_b32 v19, v20, v19, s4
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v10f64_to_v40f16:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB52_2
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_add_f64 v[18:19], v[18:19], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[16:17], v[16:17], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX11-TRUE16-NEXT:  .LBB52_2: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v10f64_to_v40f16:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr39
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr38
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr37
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr36
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr35
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr34
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr33
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr32
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr31
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr30
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr29
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr28
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr27
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr26
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr25
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr24
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr23
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr22
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr21
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB52_2
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX11-FAKE16-NEXT:  .LBB52_2: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB52_4
; GFX11-FAKE16-NEXT:  ; %bb.3: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_add_f64 v[18:19], v[18:19], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[16:17], v[16:17], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[14:15], v[14:15], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[12:13], v[12:13], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[10:11], v[10:11], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[8:9], v[8:9], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[6:7], v[6:7], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[4:5], v[4:5], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[2:3], v[2:3], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[0:1], v[0:1], 1.0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX11-FAKE16-NEXT:  .LBB52_4: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v39, v0, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v38, v1, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v37, v2, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v36, v3, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v35, v4, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v34, v5, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v33, v6, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v32, v7, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, v31, v8, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, v30, v9, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, v29, v10, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, v28, v11, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, v27, v12, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, v26, v13, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v14, v25, v14, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v15, v24, v15, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v16, v23, v16, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v17, v22, v17, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v18, v21, v18, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v19, v20, v19, 0x5040100
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <10 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <10 x double> %a1 to <40 x half>
  br label %end

cmp.false:
  %a3 = bitcast <10 x double> %a to <40 x half>
  br label %end

end:
  %phi = phi <40 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <40 x half> %phi
}

define inreg <40 x half> @bitcast_v10f64_to_v40f16_scalar(<10 x double> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v10f64_to_v40f16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_readfirstlane_b32 s4, v6
; SI-NEXT:    v_readfirstlane_b32 s9, v5
; SI-NEXT:    v_readfirstlane_b32 s8, v4
; SI-NEXT:    v_readfirstlane_b32 s7, v3
; SI-NEXT:    v_readfirstlane_b32 s6, v2
; SI-NEXT:    v_readfirstlane_b32 s5, v1
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    v_readfirstlane_b32 s4, v0
; SI-NEXT:    s_cbranch_scc0 .LBB53_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_lshr_b32 s89, s9, 16
; SI-NEXT:    s_lshr_b32 s88, s7, 16
; SI-NEXT:    s_lshr_b32 s79, s5, 16
; SI-NEXT:    s_lshr_b32 s78, s29, 16
; SI-NEXT:    s_lshr_b32 s77, s27, 16
; SI-NEXT:    s_lshr_b32 s76, s25, 16
; SI-NEXT:    s_lshr_b32 s75, s23, 16
; SI-NEXT:    s_lshr_b32 s74, s21, 16
; SI-NEXT:    s_lshr_b32 s73, s19, 16
; SI-NEXT:    s_lshr_b32 s72, s17, 16
; SI-NEXT:    s_lshr_b64 s[10:11], s[8:9], 16
; SI-NEXT:    s_lshr_b64 s[12:13], s[6:7], 16
; SI-NEXT:    s_lshr_b64 s[14:15], s[4:5], 16
; SI-NEXT:    s_lshr_b64 s[40:41], s[28:29], 16
; SI-NEXT:    s_lshr_b64 s[42:43], s[26:27], 16
; SI-NEXT:    s_lshr_b64 s[44:45], s[24:25], 16
; SI-NEXT:    s_lshr_b64 s[46:47], s[22:23], 16
; SI-NEXT:    s_lshr_b64 s[56:57], s[20:21], 16
; SI-NEXT:    s_lshr_b64 s[58:59], s[18:19], 16
; SI-NEXT:    s_lshr_b64 s[60:61], s[16:17], 16
; SI-NEXT:    s_cbranch_execnz .LBB53_4
; SI-NEXT:  .LBB53_2: ; %cmp.true
; SI-NEXT:    v_add_f64 v[18:19], s[8:9], 1.0
; SI-NEXT:    v_add_f64 v[16:17], s[6:7], 1.0
; SI-NEXT:    v_add_f64 v[14:15], s[4:5], 1.0
; SI-NEXT:    v_lshr_b64 v[20:21], v[18:19], 16
; SI-NEXT:    v_add_f64 v[12:13], s[28:29], 1.0
; SI-NEXT:    v_lshr_b64 v[21:22], v[16:17], 16
; SI-NEXT:    v_add_f64 v[10:11], s[26:27], 1.0
; SI-NEXT:    v_lshr_b64 v[22:23], v[14:15], 16
; SI-NEXT:    v_add_f64 v[8:9], s[24:25], 1.0
; SI-NEXT:    v_lshr_b64 v[23:24], v[12:13], 16
; SI-NEXT:    v_add_f64 v[6:7], s[22:23], 1.0
; SI-NEXT:    v_lshr_b64 v[24:25], v[10:11], 16
; SI-NEXT:    v_add_f64 v[4:5], s[20:21], 1.0
; SI-NEXT:    v_lshr_b64 v[25:26], v[8:9], 16
; SI-NEXT:    v_add_f64 v[2:3], s[18:19], 1.0
; SI-NEXT:    v_lshr_b64 v[26:27], v[6:7], 16
; SI-NEXT:    v_add_f64 v[0:1], s[16:17], 1.0
; SI-NEXT:    v_lshr_b64 v[27:28], v[4:5], 16
; SI-NEXT:    v_lshr_b64 v[28:29], v[2:3], 16
; SI-NEXT:    v_lshr_b64 v[29:30], v[0:1], 16
; SI-NEXT:    v_lshrrev_b32_e32 v31, 16, v19
; SI-NEXT:    v_lshrrev_b32_e32 v32, 16, v17
; SI-NEXT:    v_lshrrev_b32_e32 v33, 16, v15
; SI-NEXT:    v_lshrrev_b32_e32 v34, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v35, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v36, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v37, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v38, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v39, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v48, 16, v1
; SI-NEXT:    s_branch .LBB53_5
; SI-NEXT:  .LBB53_3:
; SI-NEXT:    ; implicit-def: $sgpr60
; SI-NEXT:    ; implicit-def: $sgpr72
; SI-NEXT:    ; implicit-def: $sgpr58
; SI-NEXT:    ; implicit-def: $sgpr73
; SI-NEXT:    ; implicit-def: $sgpr56
; SI-NEXT:    ; implicit-def: $sgpr74
; SI-NEXT:    ; implicit-def: $sgpr46
; SI-NEXT:    ; implicit-def: $sgpr75
; SI-NEXT:    ; implicit-def: $sgpr44
; SI-NEXT:    ; implicit-def: $sgpr76
; SI-NEXT:    ; implicit-def: $sgpr42
; SI-NEXT:    ; implicit-def: $sgpr77
; SI-NEXT:    ; implicit-def: $sgpr40
; SI-NEXT:    ; implicit-def: $sgpr78
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr79
; SI-NEXT:    ; implicit-def: $sgpr12
; SI-NEXT:    ; implicit-def: $sgpr88
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr89
; SI-NEXT:    s_branch .LBB53_2
; SI-NEXT:  .LBB53_4:
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v2, s18
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v4, s20
; SI-NEXT:    v_mov_b32_e32 v19, s9
; SI-NEXT:    v_mov_b32_e32 v17, s7
; SI-NEXT:    v_mov_b32_e32 v15, s5
; SI-NEXT:    v_mov_b32_e32 v13, s29
; SI-NEXT:    v_mov_b32_e32 v11, s27
; SI-NEXT:    v_mov_b32_e32 v9, s25
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    v_mov_b32_e32 v6, s22
; SI-NEXT:    v_mov_b32_e32 v8, s24
; SI-NEXT:    v_mov_b32_e32 v10, s26
; SI-NEXT:    v_mov_b32_e32 v12, s28
; SI-NEXT:    v_mov_b32_e32 v14, s4
; SI-NEXT:    v_mov_b32_e32 v16, s6
; SI-NEXT:    v_mov_b32_e32 v18, s8
; SI-NEXT:    v_mov_b32_e32 v31, s89
; SI-NEXT:    v_mov_b32_e32 v32, s88
; SI-NEXT:    v_mov_b32_e32 v33, s79
; SI-NEXT:    v_mov_b32_e32 v34, s78
; SI-NEXT:    v_mov_b32_e32 v35, s77
; SI-NEXT:    v_mov_b32_e32 v36, s76
; SI-NEXT:    v_mov_b32_e32 v37, s75
; SI-NEXT:    v_mov_b32_e32 v38, s74
; SI-NEXT:    v_mov_b32_e32 v39, s73
; SI-NEXT:    v_mov_b32_e32 v48, s72
; SI-NEXT:    v_mov_b32_e32 v29, s60
; SI-NEXT:    v_mov_b32_e32 v28, s58
; SI-NEXT:    v_mov_b32_e32 v27, s56
; SI-NEXT:    v_mov_b32_e32 v26, s46
; SI-NEXT:    v_mov_b32_e32 v25, s44
; SI-NEXT:    v_mov_b32_e32 v24, s42
; SI-NEXT:    v_mov_b32_e32 v23, s40
; SI-NEXT:    v_mov_b32_e32 v22, s14
; SI-NEXT:    v_mov_b32_e32 v21, s12
; SI-NEXT:    v_mov_b32_e32 v20, s10
; SI-NEXT:  .LBB53_5: ; %end
; SI-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v28, 16, v28
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v27, 16, v27
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v26, 16, v26
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; SI-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; SI-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v16
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; SI-NEXT:    v_or_b32_e32 v0, v0, v29
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v29, 16, v48
; SI-NEXT:    v_or_b32_e32 v2, v2, v28
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v28, 16, v39
; SI-NEXT:    v_or_b32_e32 v4, v4, v27
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v27, 16, v38
; SI-NEXT:    v_or_b32_e32 v6, v6, v26
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v26, 16, v37
; SI-NEXT:    v_or_b32_e32 v8, v8, v25
; SI-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; SI-NEXT:    v_lshlrev_b32_e32 v25, 16, v36
; SI-NEXT:    v_or_b32_e32 v10, v10, v24
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; SI-NEXT:    v_lshlrev_b32_e32 v24, 16, v35
; SI-NEXT:    v_or_b32_e32 v12, v12, v23
; SI-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v34
; SI-NEXT:    v_or_b32_e32 v14, v14, v22
; SI-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; SI-NEXT:    v_lshlrev_b32_e32 v22, 16, v33
; SI-NEXT:    v_or_b32_e32 v16, v16, v21
; SI-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; SI-NEXT:    v_lshlrev_b32_e32 v21, 16, v32
; SI-NEXT:    v_or_b32_e32 v18, v18, v20
; SI-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v31
; SI-NEXT:    v_or_b32_e32 v1, v1, v29
; SI-NEXT:    v_or_b32_e32 v3, v3, v28
; SI-NEXT:    v_or_b32_e32 v5, v5, v27
; SI-NEXT:    v_or_b32_e32 v7, v7, v26
; SI-NEXT:    v_or_b32_e32 v9, v9, v25
; SI-NEXT:    v_or_b32_e32 v11, v11, v24
; SI-NEXT:    v_or_b32_e32 v13, v13, v23
; SI-NEXT:    v_or_b32_e32 v15, v15, v22
; SI-NEXT:    v_or_b32_e32 v17, v17, v21
; SI-NEXT:    v_or_b32_e32 v19, v19, v20
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v10f64_to_v40f16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    v_readfirstlane_b32 s9, v5
; VI-NEXT:    v_readfirstlane_b32 s8, v4
; VI-NEXT:    v_readfirstlane_b32 s7, v3
; VI-NEXT:    v_readfirstlane_b32 s6, v2
; VI-NEXT:    v_readfirstlane_b32 s5, v1
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    v_readfirstlane_b32 s4, v0
; VI-NEXT:    s_cbranch_scc0 .LBB53_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_lshr_b32 s12, s9, 16
; VI-NEXT:    s_lshr_b32 s46, s8, 16
; VI-NEXT:    s_lshr_b32 s13, s7, 16
; VI-NEXT:    s_lshr_b32 s47, s6, 16
; VI-NEXT:    s_lshr_b32 s14, s5, 16
; VI-NEXT:    s_lshr_b32 s56, s4, 16
; VI-NEXT:    s_lshr_b32 s15, s29, 16
; VI-NEXT:    s_lshr_b32 s57, s28, 16
; VI-NEXT:    s_lshr_b32 s40, s27, 16
; VI-NEXT:    s_lshr_b32 s58, s26, 16
; VI-NEXT:    s_lshr_b32 s41, s25, 16
; VI-NEXT:    s_lshr_b32 s59, s24, 16
; VI-NEXT:    s_lshr_b32 s42, s23, 16
; VI-NEXT:    s_lshr_b32 s60, s22, 16
; VI-NEXT:    s_lshr_b32 s43, s21, 16
; VI-NEXT:    s_lshr_b32 s61, s20, 16
; VI-NEXT:    s_lshr_b32 s44, s19, 16
; VI-NEXT:    s_lshr_b32 s62, s18, 16
; VI-NEXT:    s_lshr_b32 s45, s17, 16
; VI-NEXT:    s_lshr_b32 s63, s16, 16
; VI-NEXT:    s_cbranch_execnz .LBB53_4
; VI-NEXT:  .LBB53_2: ; %cmp.true
; VI-NEXT:    v_add_f64 v[18:19], s[8:9], 1.0
; VI-NEXT:    v_add_f64 v[16:17], s[6:7], 1.0
; VI-NEXT:    v_add_f64 v[14:15], s[4:5], 1.0
; VI-NEXT:    v_add_f64 v[12:13], s[28:29], 1.0
; VI-NEXT:    v_add_f64 v[10:11], s[26:27], 1.0
; VI-NEXT:    v_add_f64 v[8:9], s[24:25], 1.0
; VI-NEXT:    v_add_f64 v[6:7], s[22:23], 1.0
; VI-NEXT:    v_add_f64 v[4:5], s[20:21], 1.0
; VI-NEXT:    v_add_f64 v[2:3], s[18:19], 1.0
; VI-NEXT:    v_add_f64 v[0:1], s[16:17], 1.0
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v19
; VI-NEXT:    v_lshrrev_b32_e32 v20, 16, v18
; VI-NEXT:    v_lshrrev_b32_e32 v24, 16, v17
; VI-NEXT:    v_lshrrev_b32_e32 v21, 16, v16
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v15
; VI-NEXT:    v_lshrrev_b32_e32 v23, 16, v14
; VI-NEXT:    v_lshrrev_b32_e32 v28, 16, v13
; VI-NEXT:    v_lshrrev_b32_e32 v25, 16, v12
; VI-NEXT:    v_lshrrev_b32_e32 v29, 16, v11
; VI-NEXT:    v_lshrrev_b32_e32 v27, 16, v10
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; VI-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; VI-NEXT:    v_lshrrev_b32_e32 v34, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v32, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v36, 16, v5
; VI-NEXT:    v_lshrrev_b32_e32 v33, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; VI-NEXT:    v_lshrrev_b32_e32 v35, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v39, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v0
; VI-NEXT:    s_branch .LBB53_5
; VI-NEXT:  .LBB53_3:
; VI-NEXT:    ; implicit-def: $sgpr63
; VI-NEXT:    ; implicit-def: $sgpr45
; VI-NEXT:    ; implicit-def: $sgpr62
; VI-NEXT:    ; implicit-def: $sgpr44
; VI-NEXT:    ; implicit-def: $sgpr61
; VI-NEXT:    ; implicit-def: $sgpr43
; VI-NEXT:    ; implicit-def: $sgpr60
; VI-NEXT:    ; implicit-def: $sgpr42
; VI-NEXT:    ; implicit-def: $sgpr59
; VI-NEXT:    ; implicit-def: $sgpr41
; VI-NEXT:    ; implicit-def: $sgpr58
; VI-NEXT:    ; implicit-def: $sgpr40
; VI-NEXT:    ; implicit-def: $sgpr57
; VI-NEXT:    ; implicit-def: $sgpr15
; VI-NEXT:    ; implicit-def: $sgpr56
; VI-NEXT:    ; implicit-def: $sgpr14
; VI-NEXT:    ; implicit-def: $sgpr47
; VI-NEXT:    ; implicit-def: $sgpr13
; VI-NEXT:    ; implicit-def: $sgpr46
; VI-NEXT:    ; implicit-def: $sgpr12
; VI-NEXT:    s_branch .LBB53_2
; VI-NEXT:  .LBB53_4:
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v8, s24
; VI-NEXT:    v_mov_b32_e32 v10, s26
; VI-NEXT:    v_mov_b32_e32 v12, s28
; VI-NEXT:    v_mov_b32_e32 v14, s4
; VI-NEXT:    v_mov_b32_e32 v16, s6
; VI-NEXT:    v_mov_b32_e32 v18, s8
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    v_mov_b32_e32 v9, s25
; VI-NEXT:    v_mov_b32_e32 v11, s27
; VI-NEXT:    v_mov_b32_e32 v13, s29
; VI-NEXT:    v_mov_b32_e32 v15, s5
; VI-NEXT:    v_mov_b32_e32 v17, s7
; VI-NEXT:    v_mov_b32_e32 v19, s9
; VI-NEXT:    v_mov_b32_e32 v37, s63
; VI-NEXT:    v_mov_b32_e32 v35, s62
; VI-NEXT:    v_mov_b32_e32 v33, s61
; VI-NEXT:    v_mov_b32_e32 v32, s60
; VI-NEXT:    v_mov_b32_e32 v31, s59
; VI-NEXT:    v_mov_b32_e32 v27, s58
; VI-NEXT:    v_mov_b32_e32 v25, s57
; VI-NEXT:    v_mov_b32_e32 v23, s56
; VI-NEXT:    v_mov_b32_e32 v21, s47
; VI-NEXT:    v_mov_b32_e32 v20, s46
; VI-NEXT:    v_mov_b32_e32 v39, s45
; VI-NEXT:    v_mov_b32_e32 v38, s44
; VI-NEXT:    v_mov_b32_e32 v36, s43
; VI-NEXT:    v_mov_b32_e32 v34, s42
; VI-NEXT:    v_mov_b32_e32 v30, s41
; VI-NEXT:    v_mov_b32_e32 v29, s40
; VI-NEXT:    v_mov_b32_e32 v28, s15
; VI-NEXT:    v_mov_b32_e32 v26, s14
; VI-NEXT:    v_mov_b32_e32 v24, s13
; VI-NEXT:    v_mov_b32_e32 v22, s12
; VI-NEXT:  .LBB53_5: ; %end
; VI-NEXT:    v_lshlrev_b32_e32 v37, 16, v37
; VI-NEXT:    v_lshlrev_b32_e32 v35, 16, v35
; VI-NEXT:    v_lshlrev_b32_e32 v33, 16, v33
; VI-NEXT:    v_lshlrev_b32_e32 v32, 16, v32
; VI-NEXT:    v_lshlrev_b32_e32 v27, 16, v27
; VI-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; VI-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; VI-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; VI-NEXT:    v_or_b32_sdwa v0, v0, v37 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v37, 16, v39
; VI-NEXT:    v_or_b32_sdwa v2, v2, v35 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v35, 16, v38
; VI-NEXT:    v_or_b32_sdwa v4, v4, v33 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v33, 16, v36
; VI-NEXT:    v_or_b32_sdwa v6, v6, v32 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v32, 16, v34
; VI-NEXT:    v_lshlrev_b32_e32 v31, 16, v31
; VI-NEXT:    v_lshlrev_b32_e32 v30, 16, v30
; VI-NEXT:    v_or_b32_sdwa v10, v10, v27 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v27, 16, v29
; VI-NEXT:    v_or_b32_sdwa v12, v12, v25 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v25, 16, v28
; VI-NEXT:    v_or_b32_sdwa v14, v14, v23 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v23, 16, v26
; VI-NEXT:    v_or_b32_sdwa v16, v16, v21 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v21, 16, v24
; VI-NEXT:    v_or_b32_sdwa v18, v18, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v22
; VI-NEXT:    v_or_b32_sdwa v1, v1, v37 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v3, v3, v35 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v5, v5, v33 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v7, v7, v32 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v8, v8, v31 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v9, v9, v30 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v11, v11, v27 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v13, v13, v25 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v15, v15, v23 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v17, v17, v21 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v19, v19, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v10f64_to_v40f16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_readfirstlane_b32 s4, v6
; GFX9-NEXT:    v_readfirstlane_b32 s9, v5
; GFX9-NEXT:    v_readfirstlane_b32 s8, v4
; GFX9-NEXT:    v_readfirstlane_b32 s7, v3
; GFX9-NEXT:    v_readfirstlane_b32 s6, v2
; GFX9-NEXT:    v_readfirstlane_b32 s5, v1
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    v_readfirstlane_b32 s4, v0
; GFX9-NEXT:    s_cbranch_scc0 .LBB53_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_lshr_b32 s12, s9, 16
; GFX9-NEXT:    s_lshr_b32 s46, s8, 16
; GFX9-NEXT:    s_lshr_b32 s13, s7, 16
; GFX9-NEXT:    s_lshr_b32 s47, s6, 16
; GFX9-NEXT:    s_lshr_b32 s14, s5, 16
; GFX9-NEXT:    s_lshr_b32 s56, s4, 16
; GFX9-NEXT:    s_lshr_b32 s15, s29, 16
; GFX9-NEXT:    s_lshr_b32 s57, s28, 16
; GFX9-NEXT:    s_lshr_b32 s40, s27, 16
; GFX9-NEXT:    s_lshr_b32 s58, s26, 16
; GFX9-NEXT:    s_lshr_b32 s41, s25, 16
; GFX9-NEXT:    s_lshr_b32 s59, s24, 16
; GFX9-NEXT:    s_lshr_b32 s42, s23, 16
; GFX9-NEXT:    s_lshr_b32 s60, s22, 16
; GFX9-NEXT:    s_lshr_b32 s43, s21, 16
; GFX9-NEXT:    s_lshr_b32 s61, s20, 16
; GFX9-NEXT:    s_lshr_b32 s44, s19, 16
; GFX9-NEXT:    s_lshr_b32 s62, s18, 16
; GFX9-NEXT:    s_lshr_b32 s45, s17, 16
; GFX9-NEXT:    s_lshr_b32 s63, s16, 16
; GFX9-NEXT:    s_cbranch_execnz .LBB53_4
; GFX9-NEXT:  .LBB53_2: ; %cmp.true
; GFX9-NEXT:    v_add_f64 v[18:19], s[8:9], 1.0
; GFX9-NEXT:    v_add_f64 v[16:17], s[6:7], 1.0
; GFX9-NEXT:    v_add_f64 v[14:15], s[4:5], 1.0
; GFX9-NEXT:    v_add_f64 v[12:13], s[28:29], 1.0
; GFX9-NEXT:    v_add_f64 v[10:11], s[26:27], 1.0
; GFX9-NEXT:    v_add_f64 v[8:9], s[24:25], 1.0
; GFX9-NEXT:    v_add_f64 v[6:7], s[22:23], 1.0
; GFX9-NEXT:    v_add_f64 v[4:5], s[20:21], 1.0
; GFX9-NEXT:    v_add_f64 v[2:3], s[18:19], 1.0
; GFX9-NEXT:    v_add_f64 v[0:1], s[16:17], 1.0
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v19
; GFX9-NEXT:    v_lshrrev_b32_e32 v20, 16, v18
; GFX9-NEXT:    v_lshrrev_b32_e32 v24, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v15
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 16, v14
; GFX9-NEXT:    v_lshrrev_b32_e32 v28, 16, v13
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 16, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 16, v11
; GFX9-NEXT:    v_lshrrev_b32_e32 v27, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 16, v5
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v2
; GFX9-NEXT:    v_lshrrev_b32_e32 v39, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v0
; GFX9-NEXT:    s_branch .LBB53_5
; GFX9-NEXT:  .LBB53_3:
; GFX9-NEXT:    ; implicit-def: $sgpr63
; GFX9-NEXT:    ; implicit-def: $sgpr45
; GFX9-NEXT:    ; implicit-def: $sgpr62
; GFX9-NEXT:    ; implicit-def: $sgpr44
; GFX9-NEXT:    ; implicit-def: $sgpr61
; GFX9-NEXT:    ; implicit-def: $sgpr43
; GFX9-NEXT:    ; implicit-def: $sgpr60
; GFX9-NEXT:    ; implicit-def: $sgpr42
; GFX9-NEXT:    ; implicit-def: $sgpr59
; GFX9-NEXT:    ; implicit-def: $sgpr41
; GFX9-NEXT:    ; implicit-def: $sgpr58
; GFX9-NEXT:    ; implicit-def: $sgpr40
; GFX9-NEXT:    ; implicit-def: $sgpr57
; GFX9-NEXT:    ; implicit-def: $sgpr15
; GFX9-NEXT:    ; implicit-def: $sgpr56
; GFX9-NEXT:    ; implicit-def: $sgpr14
; GFX9-NEXT:    ; implicit-def: $sgpr47
; GFX9-NEXT:    ; implicit-def: $sgpr13
; GFX9-NEXT:    ; implicit-def: $sgpr46
; GFX9-NEXT:    ; implicit-def: $sgpr12
; GFX9-NEXT:    s_branch .LBB53_2
; GFX9-NEXT:  .LBB53_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v8, s24
; GFX9-NEXT:    v_mov_b32_e32 v10, s26
; GFX9-NEXT:    v_mov_b32_e32 v12, s28
; GFX9-NEXT:    v_mov_b32_e32 v14, s4
; GFX9-NEXT:    v_mov_b32_e32 v16, s6
; GFX9-NEXT:    v_mov_b32_e32 v18, s8
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    v_mov_b32_e32 v9, s25
; GFX9-NEXT:    v_mov_b32_e32 v11, s27
; GFX9-NEXT:    v_mov_b32_e32 v13, s29
; GFX9-NEXT:    v_mov_b32_e32 v15, s5
; GFX9-NEXT:    v_mov_b32_e32 v17, s7
; GFX9-NEXT:    v_mov_b32_e32 v19, s9
; GFX9-NEXT:    v_mov_b32_e32 v37, s63
; GFX9-NEXT:    v_mov_b32_e32 v35, s62
; GFX9-NEXT:    v_mov_b32_e32 v33, s61
; GFX9-NEXT:    v_mov_b32_e32 v32, s60
; GFX9-NEXT:    v_mov_b32_e32 v31, s59
; GFX9-NEXT:    v_mov_b32_e32 v27, s58
; GFX9-NEXT:    v_mov_b32_e32 v25, s57
; GFX9-NEXT:    v_mov_b32_e32 v23, s56
; GFX9-NEXT:    v_mov_b32_e32 v21, s47
; GFX9-NEXT:    v_mov_b32_e32 v20, s46
; GFX9-NEXT:    v_mov_b32_e32 v39, s45
; GFX9-NEXT:    v_mov_b32_e32 v38, s44
; GFX9-NEXT:    v_mov_b32_e32 v36, s43
; GFX9-NEXT:    v_mov_b32_e32 v34, s42
; GFX9-NEXT:    v_mov_b32_e32 v30, s41
; GFX9-NEXT:    v_mov_b32_e32 v29, s40
; GFX9-NEXT:    v_mov_b32_e32 v28, s15
; GFX9-NEXT:    v_mov_b32_e32 v26, s14
; GFX9-NEXT:    v_mov_b32_e32 v24, s13
; GFX9-NEXT:    v_mov_b32_e32 v22, s12
; GFX9-NEXT:  .LBB53_5: ; %end
; GFX9-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; GFX9-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX9-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GFX9-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX9-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; GFX9-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; GFX9-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; GFX9-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; GFX9-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; GFX9-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; GFX9-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; GFX9-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; GFX9-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; GFX9-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; GFX9-NEXT:    v_and_b32_e32 v16, 0xffff, v16
; GFX9-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; GFX9-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; GFX9-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; GFX9-NEXT:    v_lshl_or_b32 v0, v37, 16, v0
; GFX9-NEXT:    v_lshl_or_b32 v1, v39, 16, v1
; GFX9-NEXT:    v_lshl_or_b32 v2, v35, 16, v2
; GFX9-NEXT:    v_lshl_or_b32 v3, v38, 16, v3
; GFX9-NEXT:    v_lshl_or_b32 v4, v33, 16, v4
; GFX9-NEXT:    v_lshl_or_b32 v5, v36, 16, v5
; GFX9-NEXT:    v_lshl_or_b32 v6, v32, 16, v6
; GFX9-NEXT:    v_lshl_or_b32 v7, v34, 16, v7
; GFX9-NEXT:    v_lshl_or_b32 v8, v31, 16, v8
; GFX9-NEXT:    v_lshl_or_b32 v9, v30, 16, v9
; GFX9-NEXT:    v_lshl_or_b32 v10, v27, 16, v10
; GFX9-NEXT:    v_lshl_or_b32 v11, v29, 16, v11
; GFX9-NEXT:    v_lshl_or_b32 v12, v25, 16, v12
; GFX9-NEXT:    v_lshl_or_b32 v13, v28, 16, v13
; GFX9-NEXT:    v_lshl_or_b32 v14, v23, 16, v14
; GFX9-NEXT:    v_lshl_or_b32 v15, v26, 16, v15
; GFX9-NEXT:    v_lshl_or_b32 v16, v21, 16, v16
; GFX9-NEXT:    v_lshl_or_b32 v17, v24, 16, v17
; GFX9-NEXT:    v_lshl_or_b32 v18, v20, 16, v18
; GFX9-NEXT:    v_lshl_or_b32 v19, v22, 16, v19
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v10f64_to_v40f16_scalar:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s6, v2
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s5, v1
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s4, v0
; GFX11-TRUE16-NEXT:    s_cmp_lg_u32 s6, 0
; GFX11-TRUE16-NEXT:    s_mov_b32 s6, 0
; GFX11-TRUE16-NEXT:    s_cbranch_scc0 .LBB53_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-TRUE16-NEXT:    s_lshr_b32 s7, s5, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s41, s4, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s8, s29, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s42, s28, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s9, s27, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s43, s26, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s10, s25, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s44, s24, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s11, s23, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s45, s22, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s12, s21, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s46, s20, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s13, s19, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s47, s18, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s14, s17, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s56, s16, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s15, s3, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s57, s2, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s40, s1, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s58, s0, 16
; GFX11-TRUE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s6
; GFX11-TRUE16-NEXT:    s_cbranch_vccnz .LBB53_4
; GFX11-TRUE16-NEXT:  .LBB53_2: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_add_f64 v[18:19], s[4:5], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[16:17], s[28:29], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[14:15], s[26:27], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[12:13], s[24:25], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[10:11], s[22:23], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[8:9], s[20:21], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[6:7], s[18:19], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[4:5], s[16:17], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[2:3], s[2:3], 1.0
; GFX11-TRUE16-NEXT:    v_add_f64 v[0:1], s[0:1], 1.0
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v19
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v20, 16, v18
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v17
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v16
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v15
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v14
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v13
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v12
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v10
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v9
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v8
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v7
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v6
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v5
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v4
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v2
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v1
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v0
; GFX11-TRUE16-NEXT:    s_branch .LBB53_5
; GFX11-TRUE16-NEXT:  .LBB53_3:
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr58
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr40
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr57
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr15
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr56
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr14
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr47
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr13
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr46
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr12
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr45
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr11
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr44
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr10
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr43
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr9
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr42
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr8
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr41
; GFX11-TRUE16-NEXT:    ; implicit-def: $sgpr7
; GFX11-TRUE16-NEXT:    s_branch .LBB53_2
; GFX11-TRUE16-NEXT:  .LBB53_4:
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v4, s16 :: v_dual_mov_b32 v5, s17
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v6, s18 :: v_dual_mov_b32 v7, s19
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v8, s20 :: v_dual_mov_b32 v9, s21
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v10, s22 :: v_dual_mov_b32 v11, s23
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v12, s24 :: v_dual_mov_b32 v13, s25
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v14, s26 :: v_dual_mov_b32 v15, s27
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v16, s28 :: v_dual_mov_b32 v17, s29
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v18, s4 :: v_dual_mov_b32 v19, s5
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v37, s58 :: v_dual_mov_b32 v20, s41
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v35, s57 :: v_dual_mov_b32 v38, s15
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v33, s56 :: v_dual_mov_b32 v36, s14
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v31, s47 :: v_dual_mov_b32 v34, s13
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v29, s46 :: v_dual_mov_b32 v32, s12
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v27, s45 :: v_dual_mov_b32 v30, s11
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v25, s44 :: v_dual_mov_b32 v28, s10
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v23, s43 :: v_dual_mov_b32 v26, s9
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v21, s42 :: v_dual_mov_b32 v24, s8
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v39, s40 :: v_dual_mov_b32 v22, s7
; GFX11-TRUE16-NEXT:  .LBB53_5: ; %end
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.h, v37.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v1.h, v39.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.h, v35.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v3.h, v38.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v4.h, v33.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v5.h, v36.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v6.h, v31.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v7.h, v34.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v8.h, v29.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v9.h, v32.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v10.h, v27.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v11.h, v30.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v12.h, v25.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v13.h, v28.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v14.h, v23.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v15.h, v26.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v16.h, v21.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v17.h, v24.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v18.h, v20.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v19.h, v22.l
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v10f64_to_v40f16_scalar:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s6, v2
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s5, v1
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s4, v0
; GFX11-FAKE16-NEXT:    s_cmp_lg_u32 s6, 0
; GFX11-FAKE16-NEXT:    s_mov_b32 s6, 0
; GFX11-FAKE16-NEXT:    s_cbranch_scc0 .LBB53_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.false
; GFX11-FAKE16-NEXT:    s_lshr_b32 s7, s5, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s41, s4, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s8, s29, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s42, s28, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s9, s27, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s43, s26, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s10, s25, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s44, s24, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s11, s23, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s45, s22, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s12, s21, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s46, s20, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s13, s19, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s47, s18, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s14, s17, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s56, s16, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s15, s3, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s57, s2, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s40, s1, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s58, s0, 16
; GFX11-FAKE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s6
; GFX11-FAKE16-NEXT:    s_cbranch_vccnz .LBB53_4
; GFX11-FAKE16-NEXT:  .LBB53_2: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_add_f64 v[15:16], s[4:5], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[17:18], s[28:29], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[19:20], s[26:27], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[10:11], s[24:25], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[12:13], s[22:23], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[5:6], s[20:21], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[7:8], s[18:19], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[21:22], s[16:17], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[0:1], s[2:3], 1.0
; GFX11-FAKE16-NEXT:    v_add_f64 v[2:3], s[0:1], 1.0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v20
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v14, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v9, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v22
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v4, 16, v21
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v3
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX11-FAKE16-NEXT:    s_branch .LBB53_5
; GFX11-FAKE16-NEXT:  .LBB53_3:
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr58
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr40
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr57
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr15
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr56
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr14
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr47
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr13
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr46
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr12
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr45
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr11
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr44
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr10
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr43
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr9
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr42
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr8
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr41
; GFX11-FAKE16-NEXT:    ; implicit-def: $sgpr7
; GFX11-FAKE16-NEXT:    s_branch .LBB53_2
; GFX11-FAKE16-NEXT:  .LBB53_4:
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v2, s0 :: v_dual_mov_b32 v21, s16
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v0, s2 :: v_dual_mov_b32 v7, s18
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v5, s20 :: v_dual_mov_b32 v12, s22
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v10, s24 :: v_dual_mov_b32 v19, s26
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v17, s28 :: v_dual_mov_b32 v22, s17
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v15, s4 :: v_dual_mov_b32 v8, s19
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v3, s1 :: v_dual_mov_b32 v6, s21
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v1, s3 :: v_dual_mov_b32 v20, s27
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v13, s23 :: v_dual_mov_b32 v18, s29
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v11, s25 :: v_dual_mov_b32 v16, s5
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v37, s58 :: v_dual_mov_b32 v36, s57
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v4, s56 :: v_dual_mov_b32 v9, s46
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v32, s47 :: v_dual_mov_b32 v29, s45
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v28, s44 :: v_dual_mov_b32 v23, s41
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v14, s43 :: v_dual_mov_b32 v39, s40
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v24, s42 :: v_dual_mov_b32 v35, s14
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v38, s15 :: v_dual_mov_b32 v33, s12
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v34, s13 :: v_dual_mov_b32 v31, s11
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v30, s10 :: v_dual_mov_b32 v27, s9
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v26, s8 :: v_dual_mov_b32 v25, s7
; GFX11-FAKE16-NEXT:  .LBB53_5: ; %end
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v21, 0xffff, v21
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v48, 0xffff, v0
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v4, v4, 16, v21
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v21, 0xffff, v22
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v22, 0xffff, v5
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v5, v35, 16, v21
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v21, 0xffff, v10
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v49, 0xffff, v1
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v0, v37, 16, v2
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v2, v36, 16, v48
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v36, 0xffff, v6
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v6, v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v7, v34, 16, v8
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v8, v9, 16, v22
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v22, 0xffff, v11
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v10, v29, 16, v12
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v12, v28, 16, v21
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v14, v14, 16, v19
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v19, 0xffff, v20
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v20, 0xffff, v15
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v21, 0xffff, v16
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v1, v39, 16, v3
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v3, v38, 16, v49
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v9, v33, 16, v36
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v11, v31, 16, v13
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v13, v30, 16, v22
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v15, v27, 16, v19
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v16, v24, 16, v17
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v17, v26, 16, v18
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v18, v23, 16, v20
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v19, v25, 16, v21
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <10 x double> %a, splat (double 1.000000e+00)
  %a2 = bitcast <10 x double> %a1 to <40 x half>
  br label %end

cmp.false:
  %a3 = bitcast <10 x double> %a to <40 x half>
  br label %end

end:
  %phi = phi <40 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <40 x half> %phi
}

define <10 x double> @bitcast_v40f16_to_v10f64(<40 x half> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v40f16_to_v10f64:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v63, off, s[0:3], s32 ; 4-byte Folded Spill
; SI-NEXT:    v_mov_b32_e32 v32, v19
; SI-NEXT:    v_mov_b32_e32 v33, v18
; SI-NEXT:    v_mov_b32_e32 v43, v0
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v32
; SI-NEXT:    v_mov_b32_e32 v34, v17
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:64 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v33
; SI-NEXT:    v_mov_b32_e32 v35, v16
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:68 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v34
; SI-NEXT:    v_mov_b32_e32 v36, v15
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:72 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v35
; SI-NEXT:    v_mov_b32_e32 v37, v14
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:76 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v36
; SI-NEXT:    v_mov_b32_e32 v38, v13
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:80 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v37
; SI-NEXT:    v_mov_b32_e32 v39, v12
; SI-NEXT:    v_mov_b32_e32 v48, v11
; SI-NEXT:    v_mov_b32_e32 v49, v10
; SI-NEXT:    v_mov_b32_e32 v50, v9
; SI-NEXT:    v_mov_b32_e32 v51, v8
; SI-NEXT:    v_mov_b32_e32 v52, v7
; SI-NEXT:    v_mov_b32_e32 v53, v6
; SI-NEXT:    v_mov_b32_e32 v54, v5
; SI-NEXT:    v_mov_b32_e32 v55, v4
; SI-NEXT:    v_mov_b32_e32 v40, v3
; SI-NEXT:    v_mov_b32_e32 v41, v2
; SI-NEXT:    v_mov_b32_e32 v42, v1
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:84 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v38
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:88 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v0, 16, v39
; SI-NEXT:    v_lshrrev_b32_e32 v60, 16, v48
; SI-NEXT:    v_lshrrev_b32_e32 v61, 16, v49
; SI-NEXT:    v_lshrrev_b32_e32 v62, 16, v50
; SI-NEXT:    v_lshrrev_b32_e32 v63, 16, v51
; SI-NEXT:    v_lshrrev_b32_e32 v44, 16, v52
; SI-NEXT:    v_lshrrev_b32_e32 v45, 16, v53
; SI-NEXT:    v_lshrrev_b32_e32 v46, 16, v54
; SI-NEXT:    v_lshrrev_b32_e32 v47, 16, v55
; SI-NEXT:    v_lshrrev_b32_e32 v56, 16, v40
; SI-NEXT:    v_lshrrev_b32_e32 v57, 16, v41
; SI-NEXT:    v_lshrrev_b32_e32 v58, 16, v42
; SI-NEXT:    v_lshrrev_b32_e32 v59, 16, v43
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:92 ; 4-byte Folded Spill
; SI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB54_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:92 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:88 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:84 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:80 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:76 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:72 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v43
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v59
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v42
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v58
; SI-NEXT:    v_or_b32_e32 v0, v0, v1
; SI-NEXT:    v_or_b32_e32 v1, v2, v3
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v41
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v57
; SI-NEXT:    v_or_b32_e32 v2, v2, v3
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v40
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v56
; SI-NEXT:    v_or_b32_e32 v3, v3, v4
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v55
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v47
; SI-NEXT:    v_or_b32_e32 v4, v4, v5
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v54
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v46
; SI-NEXT:    v_or_b32_e32 v5, v5, v6
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v53
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v45
; SI-NEXT:    v_or_b32_e32 v6, v6, v7
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v52
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v44
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v51
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v63
; SI-NEXT:    v_or_b32_e32 v8, v8, v9
; SI-NEXT:    v_and_b32_e32 v9, 0xffff, v50
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v62
; SI-NEXT:    v_or_b32_e32 v9, v9, v10
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v49
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v61
; SI-NEXT:    v_or_b32_e32 v10, v10, v11
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v48
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v60
; SI-NEXT:    v_or_b32_e32 v11, v11, v12
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v39
; SI-NEXT:    ; implicit-def: $vgpr43
; SI-NEXT:    ; implicit-def: $vgpr42
; SI-NEXT:    ; implicit-def: $vgpr41
; SI-NEXT:    ; implicit-def: $vgpr40
; SI-NEXT:    ; implicit-def: $vgpr55
; SI-NEXT:    ; implicit-def: $vgpr54
; SI-NEXT:    ; implicit-def: $vgpr53
; SI-NEXT:    ; implicit-def: $vgpr52
; SI-NEXT:    ; implicit-def: $vgpr51
; SI-NEXT:    ; implicit-def: $vgpr50
; SI-NEXT:    ; implicit-def: $vgpr49
; SI-NEXT:    ; implicit-def: $vgpr48
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:    ; implicit-def: $vgpr59
; SI-NEXT:    ; implicit-def: $vgpr58
; SI-NEXT:    ; implicit-def: $vgpr57
; SI-NEXT:    ; implicit-def: $vgpr56
; SI-NEXT:    ; implicit-def: $vgpr47
; SI-NEXT:    ; implicit-def: $vgpr46
; SI-NEXT:    ; implicit-def: $vgpr45
; SI-NEXT:    ; implicit-def: $vgpr44
; SI-NEXT:    ; implicit-def: $vgpr63
; SI-NEXT:    ; implicit-def: $vgpr62
; SI-NEXT:    ; implicit-def: $vgpr61
; SI-NEXT:    ; implicit-def: $vgpr60
; SI-NEXT:    s_waitcnt vmcnt(7)
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v13
; SI-NEXT:    v_or_b32_e32 v12, v12, v13
; SI-NEXT:    v_and_b32_e32 v13, 0xffff, v38
; SI-NEXT:    s_waitcnt vmcnt(6)
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v14
; SI-NEXT:    v_or_b32_e32 v13, v13, v14
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v37
; SI-NEXT:    s_waitcnt vmcnt(5)
; SI-NEXT:    v_lshlrev_b32_e32 v15, 16, v15
; SI-NEXT:    v_or_b32_e32 v14, v14, v15
; SI-NEXT:    v_and_b32_e32 v15, 0xffff, v36
; SI-NEXT:    s_waitcnt vmcnt(4)
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v16
; SI-NEXT:    v_or_b32_e32 v15, v15, v16
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v35
; SI-NEXT:    s_waitcnt vmcnt(3)
; SI-NEXT:    v_lshlrev_b32_e32 v17, 16, v17
; SI-NEXT:    v_or_b32_e32 v16, v16, v17
; SI-NEXT:    v_and_b32_e32 v17, 0xffff, v34
; SI-NEXT:    s_waitcnt vmcnt(2)
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v18
; SI-NEXT:    v_or_b32_e32 v17, v17, v18
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v33
; SI-NEXT:    s_waitcnt vmcnt(1)
; SI-NEXT:    v_lshlrev_b32_e32 v19, 16, v19
; SI-NEXT:    v_or_b32_e32 v18, v18, v19
; SI-NEXT:    v_and_b32_e32 v19, 0xffff, v32
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; SI-NEXT:    v_or_b32_e32 v19, v19, v20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr37
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr34
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:  .LBB54_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB54_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_cvt_f32_f16_e32 v0, v59
; SI-NEXT:    v_cvt_f32_f16_e32 v2, v58
; SI-NEXT:    v_cvt_f32_f16_e32 v1, v43
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v42
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_or_b32_e32 v0, v1, v0
; SI-NEXT:    v_or_b32_e32 v1, v3, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v2, v57
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v41
; SI-NEXT:    v_cvt_f32_f16_e32 v4, v40
; SI-NEXT:    v_cvt_f32_f16_e32 v5, v55
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_or_b32_e32 v2, v3, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v56
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v6, v54
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v7, v53
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_or_b32_e32 v3, v4, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v4, v47
; SI-NEXT:    v_cvt_f32_f16_e32 v8, v44
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v8, v8
; SI-NEXT:    v_cvt_f32_f16_e32 v9, v52
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v4
; SI-NEXT:    v_or_b32_e32 v4, v5, v4
; SI-NEXT:    v_cvt_f32_f16_e32 v5, v46
; SI-NEXT:    v_cvt_f32_f16_e32 v10, v51
; SI-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v9
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_add_f32_e32 v10, 0x38000000, v10
; SI-NEXT:    v_cvt_f16_f32_e32 v10, v10
; SI-NEXT:    v_cvt_f32_f16_e32 v11, v61
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_or_b32_e32 v5, v6, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v6, v45
; SI-NEXT:    v_cvt_f32_f16_e32 v12, v49
; SI-NEXT:    v_add_f32_e32 v11, 0x38000000, v11
; SI-NEXT:    v_cvt_f16_f32_e32 v11, v11
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v12, 0x38000000, v12
; SI-NEXT:    v_cvt_f16_f32_e32 v12, v12
; SI-NEXT:    v_cvt_f32_f16_e32 v13, v48
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_or_b32_e32 v6, v7, v6
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v8
; SI-NEXT:    v_cvt_f32_f16_e32 v8, v63
; SI-NEXT:    v_or_b32_e32 v7, v9, v7
; SI-NEXT:    v_cvt_f32_f16_e32 v9, v62
; SI-NEXT:    v_add_f32_e32 v13, 0x38000000, v13
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v8, v8
; SI-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v9
; SI-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:88 ; 4-byte Folded Reload
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_or_b32_e32 v8, v10, v8
; SI-NEXT:    v_cvt_f32_f16_e32 v10, v50
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v13, v13
; SI-NEXT:    v_cvt_f32_f16_e32 v15, v38
; SI-NEXT:    v_add_f32_e32 v10, 0x38000000, v10
; SI-NEXT:    v_cvt_f16_f32_e32 v10, v10
; SI-NEXT:    v_cvt_f32_f16_e32 v16, v37
; SI-NEXT:    v_add_f32_e32 v15, 0x38000000, v15
; SI-NEXT:    v_cvt_f16_f32_e32 v15, v15
; SI-NEXT:    v_or_b32_e32 v9, v10, v9
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v11
; SI-NEXT:    v_or_b32_e32 v10, v12, v10
; SI-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:92 ; 4-byte Folded Reload
; SI-NEXT:    v_cvt_f32_f16_e32 v11, v60
; SI-NEXT:    v_add_f32_e32 v16, 0x38000000, v16
; SI-NEXT:    v_cvt_f16_f32_e32 v16, v16
; SI-NEXT:    v_cvt_f32_f16_e32 v18, v35
; SI-NEXT:    v_add_f32_e32 v11, 0x38000000, v11
; SI-NEXT:    v_cvt_f16_f32_e32 v11, v11
; SI-NEXT:    v_cvt_f32_f16_e32 v19, v34
; SI-NEXT:    v_add_f32_e32 v18, 0x38000000, v18
; SI-NEXT:    v_cvt_f16_f32_e32 v18, v18
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; SI-NEXT:    v_or_b32_e32 v11, v13, v11
; SI-NEXT:    v_cvt_f32_f16_e32 v13, v39
; SI-NEXT:    v_add_f32_e32 v19, 0x38000000, v19
; SI-NEXT:    v_cvt_f16_f32_e32 v19, v19
; SI-NEXT:    v_cvt_f32_f16_e32 v21, v32
; SI-NEXT:    v_add_f32_e32 v13, 0x38000000, v13
; SI-NEXT:    v_cvt_f16_f32_e32 v13, v13
; SI-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:76 ; 4-byte Folded Reload
; SI-NEXT:    v_add_f32_e32 v21, 0x38000000, v21
; SI-NEXT:    v_cvt_f16_f32_e32 v21, v21
; SI-NEXT:    buffer_load_dword v20, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(3)
; SI-NEXT:    v_cvt_f32_f16_e32 v14, v14
; SI-NEXT:    v_add_f32_e32 v14, 0x38000000, v14
; SI-NEXT:    v_cvt_f16_f32_e32 v14, v14
; SI-NEXT:    s_waitcnt vmcnt(2)
; SI-NEXT:    v_cvt_f32_f16_e32 v12, v12
; SI-NEXT:    v_add_f32_e32 v12, 0x38000000, v12
; SI-NEXT:    v_cvt_f16_f32_e32 v12, v12
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v12
; SI-NEXT:    v_or_b32_e32 v12, v13, v12
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v14
; SI-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:84 ; 4-byte Folded Reload
; SI-NEXT:    v_or_b32_e32 v13, v15, v13
; SI-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:80 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(3)
; SI-NEXT:    v_cvt_f32_f16_e32 v17, v17
; SI-NEXT:    s_waitcnt vmcnt(2)
; SI-NEXT:    v_cvt_f32_f16_e32 v20, v20
; SI-NEXT:    v_add_f32_e32 v17, 0x38000000, v17
; SI-NEXT:    v_cvt_f16_f32_e32 v17, v17
; SI-NEXT:    v_add_f32_e32 v20, 0x38000000, v20
; SI-NEXT:    v_cvt_f16_f32_e32 v20, v20
; SI-NEXT:    s_waitcnt vmcnt(1)
; SI-NEXT:    v_cvt_f32_f16_e32 v14, v14
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_cvt_f32_f16_e32 v15, v15
; SI-NEXT:    v_add_f32_e32 v14, 0x38000000, v14
; SI-NEXT:    v_cvt_f16_f32_e32 v14, v14
; SI-NEXT:    v_add_f32_e32 v15, 0x38000000, v15
; SI-NEXT:    v_cvt_f16_f32_e32 v15, v15
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v14
; SI-NEXT:    v_or_b32_e32 v14, v16, v14
; SI-NEXT:    v_cvt_f32_f16_e32 v16, v36
; SI-NEXT:    v_lshlrev_b32_e32 v15, 16, v15
; SI-NEXT:    v_add_f32_e32 v16, 0x38000000, v16
; SI-NEXT:    v_cvt_f16_f32_e32 v16, v16
; SI-NEXT:    v_or_b32_e32 v15, v16, v15
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v17
; SI-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:72 ; 4-byte Folded Reload
; SI-NEXT:    v_or_b32_e32 v16, v18, v16
; SI-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(1)
; SI-NEXT:    v_cvt_f32_f16_e32 v17, v17
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_cvt_f32_f16_e32 v18, v18
; SI-NEXT:    v_add_f32_e32 v17, 0x38000000, v17
; SI-NEXT:    v_cvt_f16_f32_e32 v17, v17
; SI-NEXT:    v_add_f32_e32 v18, 0x38000000, v18
; SI-NEXT:    v_cvt_f16_f32_e32 v18, v18
; SI-NEXT:    v_lshlrev_b32_e32 v17, 16, v17
; SI-NEXT:    v_or_b32_e32 v17, v19, v17
; SI-NEXT:    v_cvt_f32_f16_e32 v19, v33
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v18
; SI-NEXT:    v_add_f32_e32 v19, 0x38000000, v19
; SI-NEXT:    v_cvt_f16_f32_e32 v19, v19
; SI-NEXT:    v_or_b32_e32 v18, v19, v18
; SI-NEXT:    v_lshlrev_b32_e32 v19, 16, v20
; SI-NEXT:    v_or_b32_e32 v19, v21, v19
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:  .LBB54_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    buffer_load_dword v63, off, s[0:3], s32 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0)
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v40f16_to_v10f64:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; VI-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; VI-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; VI-NEXT:    buffer_store_dword v43, off, s[0:3], s32 ; 4-byte Folded Spill
; VI-NEXT:    v_mov_b32_e32 v32, v19
; VI-NEXT:    v_mov_b32_e32 v33, v18
; VI-NEXT:    v_mov_b32_e32 v34, v17
; VI-NEXT:    v_mov_b32_e32 v35, v16
; VI-NEXT:    v_mov_b32_e32 v36, v15
; VI-NEXT:    v_mov_b32_e32 v37, v14
; VI-NEXT:    v_mov_b32_e32 v38, v13
; VI-NEXT:    v_mov_b32_e32 v39, v12
; VI-NEXT:    v_mov_b32_e32 v48, v11
; VI-NEXT:    v_mov_b32_e32 v49, v10
; VI-NEXT:    v_mov_b32_e32 v50, v9
; VI-NEXT:    v_mov_b32_e32 v51, v8
; VI-NEXT:    v_mov_b32_e32 v52, v7
; VI-NEXT:    v_mov_b32_e32 v53, v6
; VI-NEXT:    v_mov_b32_e32 v54, v5
; VI-NEXT:    v_mov_b32_e32 v55, v4
; VI-NEXT:    v_mov_b32_e32 v40, v3
; VI-NEXT:    v_mov_b32_e32 v41, v2
; VI-NEXT:    v_mov_b32_e32 v42, v1
; VI-NEXT:    v_mov_b32_e32 v43, v0
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB54_2
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    v_mov_b32_e32 v19, 16
; VI-NEXT:    v_lshlrev_b32_sdwa v0, v19, v43 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v1, v19, v42 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v2, v19, v41 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v3, v19, v40 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v4, v19, v55 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v5, v19, v54 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v6, v19, v53 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v7, v19, v52 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v8, v19, v51 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v9, v19, v50 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v10, v19, v49 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v11, v19, v48 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v12, v19, v39 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v13, v19, v38 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v14, v19, v37 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v15, v19, v36 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v16, v19, v35 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v17, v19, v34 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v18, v19, v33 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_lshlrev_b32_sdwa v19, v19, v32 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:WORD_1
; VI-NEXT:    v_or_b32_sdwa v0, v43, v0 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v1, v42, v1 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v2, v41, v2 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v3, v40, v3 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v4, v55, v4 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v5, v54, v5 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v6, v53, v6 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v7, v52, v7 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v8, v51, v8 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v9, v50, v9 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v10, v49, v10 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v11, v48, v11 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v12, v39, v12 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v13, v38, v13 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v14, v37, v14 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v15, v36, v15 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v16, v35, v16 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v17, v34, v17 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v18, v33, v18 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v19, v32, v19 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr43
; VI-NEXT:    ; implicit-def: $vgpr42
; VI-NEXT:    ; implicit-def: $vgpr41
; VI-NEXT:    ; implicit-def: $vgpr40
; VI-NEXT:    ; implicit-def: $vgpr55
; VI-NEXT:    ; implicit-def: $vgpr54
; VI-NEXT:    ; implicit-def: $vgpr53
; VI-NEXT:    ; implicit-def: $vgpr52
; VI-NEXT:    ; implicit-def: $vgpr51
; VI-NEXT:    ; implicit-def: $vgpr50
; VI-NEXT:    ; implicit-def: $vgpr49
; VI-NEXT:    ; implicit-def: $vgpr48
; VI-NEXT:    ; implicit-def: $vgpr39
; VI-NEXT:    ; implicit-def: $vgpr38
; VI-NEXT:    ; implicit-def: $vgpr37
; VI-NEXT:    ; implicit-def: $vgpr36
; VI-NEXT:    ; implicit-def: $vgpr35
; VI-NEXT:    ; implicit-def: $vgpr34
; VI-NEXT:    ; implicit-def: $vgpr33
; VI-NEXT:    ; implicit-def: $vgpr32
; VI-NEXT:  .LBB54_2: ; %Flow
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB54_4
; VI-NEXT:  ; %bb.3: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v19, 0x200
; VI-NEXT:    v_add_f16_sdwa v0, v43, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v1, 0x200, v43
; VI-NEXT:    v_or_b32_e32 v0, v1, v0
; VI-NEXT:    v_add_f16_sdwa v1, v42, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v2, 0x200, v42
; VI-NEXT:    v_or_b32_e32 v1, v2, v1
; VI-NEXT:    v_add_f16_sdwa v2, v41, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v3, 0x200, v41
; VI-NEXT:    v_or_b32_e32 v2, v3, v2
; VI-NEXT:    v_add_f16_sdwa v3, v40, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v4, 0x200, v40
; VI-NEXT:    v_or_b32_e32 v3, v4, v3
; VI-NEXT:    v_add_f16_sdwa v4, v55, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v5, 0x200, v55
; VI-NEXT:    v_or_b32_e32 v4, v5, v4
; VI-NEXT:    v_add_f16_sdwa v5, v54, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v6, 0x200, v54
; VI-NEXT:    v_or_b32_e32 v5, v6, v5
; VI-NEXT:    v_add_f16_sdwa v6, v53, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v7, 0x200, v53
; VI-NEXT:    v_or_b32_e32 v6, v7, v6
; VI-NEXT:    v_add_f16_sdwa v7, v52, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v8, 0x200, v52
; VI-NEXT:    v_or_b32_e32 v7, v8, v7
; VI-NEXT:    v_add_f16_sdwa v8, v51, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v9, 0x200, v51
; VI-NEXT:    v_or_b32_e32 v8, v9, v8
; VI-NEXT:    v_add_f16_sdwa v9, v50, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v10, 0x200, v50
; VI-NEXT:    v_or_b32_e32 v9, v10, v9
; VI-NEXT:    v_add_f16_sdwa v10, v49, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v11, 0x200, v49
; VI-NEXT:    v_or_b32_e32 v10, v11, v10
; VI-NEXT:    v_add_f16_sdwa v11, v48, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v12, 0x200, v48
; VI-NEXT:    v_or_b32_e32 v11, v12, v11
; VI-NEXT:    v_add_f16_sdwa v12, v39, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v13, 0x200, v39
; VI-NEXT:    v_or_b32_e32 v12, v13, v12
; VI-NEXT:    v_add_f16_sdwa v13, v38, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v14, 0x200, v38
; VI-NEXT:    v_or_b32_e32 v13, v14, v13
; VI-NEXT:    v_add_f16_sdwa v14, v37, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v15, 0x200, v37
; VI-NEXT:    v_or_b32_e32 v14, v15, v14
; VI-NEXT:    v_add_f16_sdwa v15, v36, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v16, 0x200, v36
; VI-NEXT:    v_or_b32_e32 v15, v16, v15
; VI-NEXT:    v_add_f16_sdwa v16, v35, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v17, 0x200, v35
; VI-NEXT:    v_or_b32_e32 v16, v17, v16
; VI-NEXT:    v_add_f16_sdwa v17, v34, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v18, 0x200, v34
; VI-NEXT:    v_or_b32_e32 v17, v18, v17
; VI-NEXT:    v_add_f16_sdwa v18, v33, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v20, 0x200, v33
; VI-NEXT:    v_or_b32_e32 v18, v20, v18
; VI-NEXT:    v_add_f16_sdwa v19, v32, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:WORD_1 src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v20, 0x200, v32
; VI-NEXT:    v_or_b32_e32 v19, v20, v19
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:  .LBB54_4: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    buffer_load_dword v43, off, s[0:3], s32 ; 4-byte Folded Reload
; VI-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; VI-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; VI-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v40f16_to_v10f64:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; GFX9-NEXT:    buffer_store_dword v63, off, s[0:3], s32 ; 4-byte Folded Spill
; GFX9-NEXT:    v_mov_b32_e32 v32, v19
; GFX9-NEXT:    v_mov_b32_e32 v33, v18
; GFX9-NEXT:    v_mov_b32_e32 v43, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v32
; GFX9-NEXT:    v_mov_b32_e32 v34, v17
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:64 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v33
; GFX9-NEXT:    v_mov_b32_e32 v35, v16
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:68 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v34
; GFX9-NEXT:    v_mov_b32_e32 v36, v15
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:72 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v35
; GFX9-NEXT:    v_mov_b32_e32 v37, v14
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:76 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v36
; GFX9-NEXT:    v_mov_b32_e32 v38, v13
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:80 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v37
; GFX9-NEXT:    v_mov_b32_e32 v39, v12
; GFX9-NEXT:    v_mov_b32_e32 v48, v11
; GFX9-NEXT:    v_mov_b32_e32 v49, v10
; GFX9-NEXT:    v_mov_b32_e32 v50, v9
; GFX9-NEXT:    v_mov_b32_e32 v51, v8
; GFX9-NEXT:    v_mov_b32_e32 v52, v7
; GFX9-NEXT:    v_mov_b32_e32 v53, v6
; GFX9-NEXT:    v_mov_b32_e32 v54, v5
; GFX9-NEXT:    v_mov_b32_e32 v55, v4
; GFX9-NEXT:    v_mov_b32_e32 v40, v3
; GFX9-NEXT:    v_mov_b32_e32 v41, v2
; GFX9-NEXT:    v_mov_b32_e32 v42, v1
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:84 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v38
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:88 ; 4-byte Folded Spill
; GFX9-NEXT:    v_lshrrev_b32_e32 v0, 16, v39
; GFX9-NEXT:    v_lshrrev_b32_e32 v60, 16, v48
; GFX9-NEXT:    v_lshrrev_b32_e32 v61, 16, v49
; GFX9-NEXT:    v_lshrrev_b32_e32 v62, 16, v50
; GFX9-NEXT:    v_lshrrev_b32_e32 v63, 16, v51
; GFX9-NEXT:    v_lshrrev_b32_e32 v44, 16, v52
; GFX9-NEXT:    v_lshrrev_b32_e32 v45, 16, v53
; GFX9-NEXT:    v_lshrrev_b32_e32 v46, 16, v54
; GFX9-NEXT:    v_lshrrev_b32_e32 v47, 16, v55
; GFX9-NEXT:    v_lshrrev_b32_e32 v56, 16, v40
; GFX9-NEXT:    v_lshrrev_b32_e32 v57, 16, v41
; GFX9-NEXT:    v_lshrrev_b32_e32 v58, 16, v42
; GFX9-NEXT:    v_lshrrev_b32_e32 v59, 16, v43
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:92 ; 4-byte Folded Spill
; GFX9-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23_vgpr24_vgpr25_vgpr26_vgpr27_vgpr28_vgpr29_vgpr30_vgpr31
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB54_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_mov_b32 s6, 0x5040100
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v12, 16, v39
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v13, 16, v38
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v14, 16, v37
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v15, 16, v36
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v16, 16, v35
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    v_lshrrev_b32_e32 v17, 16, v34
; GFX9-NEXT:    v_lshrrev_b32_e32 v18, 16, v33
; GFX9-NEXT:    v_lshrrev_b32_e32 v19, 16, v32
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    v_perm_b32 v0, v59, v43, s6
; GFX9-NEXT:    v_perm_b32 v1, v58, v42, s6
; GFX9-NEXT:    v_perm_b32 v2, v57, v41, s6
; GFX9-NEXT:    v_perm_b32 v3, v56, v40, s6
; GFX9-NEXT:    v_perm_b32 v4, v47, v55, s6
; GFX9-NEXT:    v_perm_b32 v5, v46, v54, s6
; GFX9-NEXT:    v_perm_b32 v6, v45, v53, s6
; GFX9-NEXT:    v_perm_b32 v7, v44, v52, s6
; GFX9-NEXT:    v_perm_b32 v8, v63, v51, s6
; GFX9-NEXT:    v_perm_b32 v9, v62, v50, s6
; GFX9-NEXT:    v_perm_b32 v10, v61, v49, s6
; GFX9-NEXT:    v_perm_b32 v11, v60, v48, s6
; GFX9-NEXT:    v_perm_b32 v12, v12, v39, s6
; GFX9-NEXT:    v_perm_b32 v13, v13, v38, s6
; GFX9-NEXT:    v_perm_b32 v14, v14, v37, s6
; GFX9-NEXT:    v_perm_b32 v15, v15, v36, s6
; GFX9-NEXT:    v_perm_b32 v16, v16, v35, s6
; GFX9-NEXT:    v_perm_b32 v17, v17, v34, s6
; GFX9-NEXT:    v_perm_b32 v18, v18, v33, s6
; GFX9-NEXT:    v_perm_b32 v19, v19, v32, s6
; GFX9-NEXT:    ; implicit-def: $vgpr43
; GFX9-NEXT:    ; implicit-def: $vgpr42
; GFX9-NEXT:    ; implicit-def: $vgpr41
; GFX9-NEXT:    ; implicit-def: $vgpr40
; GFX9-NEXT:    ; implicit-def: $vgpr55
; GFX9-NEXT:    ; implicit-def: $vgpr54
; GFX9-NEXT:    ; implicit-def: $vgpr53
; GFX9-NEXT:    ; implicit-def: $vgpr52
; GFX9-NEXT:    ; implicit-def: $vgpr51
; GFX9-NEXT:    ; implicit-def: $vgpr50
; GFX9-NEXT:    ; implicit-def: $vgpr49
; GFX9-NEXT:    ; implicit-def: $vgpr48
; GFX9-NEXT:    ; implicit-def: $vgpr39
; GFX9-NEXT:    ; implicit-def: $vgpr38
; GFX9-NEXT:    ; implicit-def: $vgpr37
; GFX9-NEXT:    ; implicit-def: $vgpr36
; GFX9-NEXT:    ; implicit-def: $vgpr35
; GFX9-NEXT:    ; implicit-def: $vgpr34
; GFX9-NEXT:    ; implicit-def: $vgpr33
; GFX9-NEXT:    ; implicit-def: $vgpr32
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; kill: killed $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr60
; GFX9-NEXT:    ; implicit-def: $vgpr61
; GFX9-NEXT:    ; implicit-def: $vgpr62
; GFX9-NEXT:    ; implicit-def: $vgpr63
; GFX9-NEXT:    ; implicit-def: $vgpr44
; GFX9-NEXT:    ; implicit-def: $vgpr45
; GFX9-NEXT:    ; implicit-def: $vgpr46
; GFX9-NEXT:    ; implicit-def: $vgpr47
; GFX9-NEXT:    ; implicit-def: $vgpr56
; GFX9-NEXT:    ; implicit-def: $vgpr57
; GFX9-NEXT:    ; implicit-def: $vgpr58
; GFX9-NEXT:    ; implicit-def: $vgpr59
; GFX9-NEXT:  .LBB54_2: ; %Flow
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB54_4
; GFX9-NEXT:  ; %bb.3: ; %cmp.true
; GFX9-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:92 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:88 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:84 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:80 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:76 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:72 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; GFX9-NEXT:    s_mov_b32 s6, 0x5040100
; GFX9-NEXT:    v_perm_b32 v0, v59, v43, s6
; GFX9-NEXT:    s_movk_i32 s7, 0x200
; GFX9-NEXT:    v_perm_b32 v1, v58, v42, s6
; GFX9-NEXT:    v_perm_b32 v2, v57, v41, s6
; GFX9-NEXT:    v_perm_b32 v3, v56, v40, s6
; GFX9-NEXT:    v_perm_b32 v4, v47, v55, s6
; GFX9-NEXT:    v_perm_b32 v5, v46, v54, s6
; GFX9-NEXT:    v_perm_b32 v6, v45, v53, s6
; GFX9-NEXT:    v_perm_b32 v7, v44, v52, s6
; GFX9-NEXT:    v_perm_b32 v8, v63, v51, s6
; GFX9-NEXT:    v_perm_b32 v9, v62, v50, s6
; GFX9-NEXT:    v_perm_b32 v10, v61, v49, s6
; GFX9-NEXT:    v_perm_b32 v11, v60, v48, s6
; GFX9-NEXT:    v_pk_add_f16 v0, v0, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v1, v1, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v2, v2, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v3, v3, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v4, v4, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v5, v5, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, v6, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v7, v7, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v8, v8, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v9, v9, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v10, v10, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v11, v11, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_waitcnt vmcnt(7)
; GFX9-NEXT:    v_perm_b32 v12, v12, v39, s6
; GFX9-NEXT:    s_waitcnt vmcnt(6)
; GFX9-NEXT:    v_perm_b32 v13, v13, v38, s6
; GFX9-NEXT:    s_waitcnt vmcnt(5)
; GFX9-NEXT:    v_perm_b32 v14, v14, v37, s6
; GFX9-NEXT:    s_waitcnt vmcnt(4)
; GFX9-NEXT:    v_perm_b32 v15, v15, v36, s6
; GFX9-NEXT:    s_waitcnt vmcnt(3)
; GFX9-NEXT:    v_perm_b32 v16, v16, v35, s6
; GFX9-NEXT:    s_waitcnt vmcnt(2)
; GFX9-NEXT:    v_perm_b32 v17, v17, v34, s6
; GFX9-NEXT:    s_waitcnt vmcnt(1)
; GFX9-NEXT:    v_perm_b32 v18, v18, v33, s6
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    v_perm_b32 v19, v19, v32, s6
; GFX9-NEXT:    v_pk_add_f16 v12, v12, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v13, v13, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v14, v14, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v15, v15, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v16, v16, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v17, v17, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v18, v18, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v19, v19, s7 op_sel_hi:[1,0]
; GFX9-NEXT:  .LBB54_4: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    buffer_load_dword v63, off, s[0:3], s32 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Reload
; GFX9-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Reload
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v40f16_to_v10f64:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB54_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execnz .LBB54_4
; GFX11-TRUE16-NEXT:  .LBB54_2: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-TRUE16-NEXT:  .LBB54_3: ; %cmp.false
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB54_2
; GFX11-TRUE16-NEXT:  .LBB54_4: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v0, 0x200, v0 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v1, 0x200, v1 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v2, 0x200, v2 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v3, 0x200, v3 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v4, 0x200, v4 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v5, 0x200, v5 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v6, 0x200, v6 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v7, 0x200, v7 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v8, 0x200, v8 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v9, 0x200, v9 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v10, 0x200, v10 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v11, 0x200, v11 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v12, 0x200, v12 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v13, 0x200, v13 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v14, 0x200, v14 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v15, 0x200, v15 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v16, 0x200, v16 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v17, 0x200, v17 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v18, 0x200, v18 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v19, 0x200, v19 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v40f16_to_v10f64:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v48, 16, v3
; GFX11-FAKE16-NEXT:    v_cmp_ne_u32_e32 vcc_lo, 0, v20
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v37, v0, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v38, v1, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v39, v2, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v48, v3, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v36, v4, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v35, v5, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v34, v6, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v33, v7, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, v32, v8, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, v31, v9, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, v30, v10, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, v29, v11, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, v28, v12, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, v27, v13, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v14, v26, v14, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v15, v25, v15, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v16, v24, v16, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v17, v23, v17, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v18, v22, v18, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v19, v21, v19, 0x5040100
; GFX11-FAKE16-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB54_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execnz .LBB54_4
; GFX11-FAKE16-NEXT:  .LBB54_2: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
; GFX11-FAKE16-NEXT:  .LBB54_3: ; %cmp.false
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB54_2
; GFX11-FAKE16-NEXT:  .LBB54_4: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v0, 0x200, v0 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v1, 0x200, v1 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v2, 0x200, v2 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v3, 0x200, v3 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v4, 0x200, v4 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v5, 0x200, v5 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v6, 0x200, v6 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v7, 0x200, v7 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v8, 0x200, v8 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v9, 0x200, v9 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v10, 0x200, v10 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v11, 0x200, v11 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v12, 0x200, v12 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v13, 0x200, v13 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v14, 0x200, v14 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v15, 0x200, v15 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v16, 0x200, v16 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v17, 0x200, v17 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v18, 0x200, v18 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v19, 0x200, v19 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    ; implicit-def: $vgpr20
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <40 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <40 x half> %a1 to <10 x double>
  br label %end

cmp.false:
  %a3 = bitcast <40 x half> %a to <10 x double>
  br label %end

end:
  %phi = phi <10 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <10 x double> %phi
}

define inreg <10 x double> @bitcast_v40f16_to_v10f64_scalar(<40 x half> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v40f16_to_v10f64_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_writelane_b32 v32, s36, 0
; SI-NEXT:    v_writelane_b32 v32, s37, 1
; SI-NEXT:    v_writelane_b32 v32, s38, 2
; SI-NEXT:    v_writelane_b32 v32, s39, 3
; SI-NEXT:    v_writelane_b32 v32, s48, 4
; SI-NEXT:    v_writelane_b32 v32, s49, 5
; SI-NEXT:    v_writelane_b32 v32, s50, 6
; SI-NEXT:    v_writelane_b32 v32, s51, 7
; SI-NEXT:    v_writelane_b32 v32, s52, 8
; SI-NEXT:    v_writelane_b32 v32, s53, 9
; SI-NEXT:    v_writelane_b32 v32, s54, 10
; SI-NEXT:    v_writelane_b32 v32, s55, 11
; SI-NEXT:    v_writelane_b32 v32, s64, 12
; SI-NEXT:    v_writelane_b32 v32, s65, 13
; SI-NEXT:    v_writelane_b32 v32, s66, 14
; SI-NEXT:    v_writelane_b32 v32, s67, 15
; SI-NEXT:    v_readfirstlane_b32 s6, v5
; SI-NEXT:    v_readfirstlane_b32 s8, v4
; SI-NEXT:    v_readfirstlane_b32 s10, v3
; SI-NEXT:    v_readfirstlane_b32 s12, v2
; SI-NEXT:    v_readfirstlane_b32 s14, v1
; SI-NEXT:    v_readfirstlane_b32 s73, v0
; SI-NEXT:    s_lshr_b32 s72, s29, 16
; SI-NEXT:    s_lshr_b32 s75, s28, 16
; SI-NEXT:    s_lshr_b32 s76, s27, 16
; SI-NEXT:    s_lshr_b32 s77, s26, 16
; SI-NEXT:    s_lshr_b32 s78, s25, 16
; SI-NEXT:    s_lshr_b32 s79, s24, 16
; SI-NEXT:    s_lshr_b32 s88, s23, 16
; SI-NEXT:    s_lshr_b32 s89, s22, 16
; SI-NEXT:    s_lshr_b32 s90, s21, 16
; SI-NEXT:    s_lshr_b32 s91, s20, 16
; SI-NEXT:    s_lshr_b32 s92, s19, 16
; SI-NEXT:    s_lshr_b32 s93, s18, 16
; SI-NEXT:    s_lshr_b32 s94, s17, 16
; SI-NEXT:    s_lshr_b32 s95, s16, 16
; SI-NEXT:    s_lshr_b32 s7, s6, 16
; SI-NEXT:    s_lshr_b32 s9, s8, 16
; SI-NEXT:    s_lshr_b32 s11, s10, 16
; SI-NEXT:    s_lshr_b32 s13, s12, 16
; SI-NEXT:    s_lshr_b32 s15, s14, 16
; SI-NEXT:    s_lshr_b32 s74, s73, 16
; SI-NEXT:    v_readfirstlane_b32 s4, v6
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    s_cbranch_scc0 .LBB55_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s4, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s95, 16
; SI-NEXT:    s_or_b32 s36, s4, s5
; SI-NEXT:    s_and_b32 s4, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s94, 16
; SI-NEXT:    s_or_b32 s37, s4, s5
; SI-NEXT:    s_and_b32 s4, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s93, 16
; SI-NEXT:    s_or_b32 s38, s4, s5
; SI-NEXT:    s_and_b32 s4, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s92, 16
; SI-NEXT:    s_or_b32 s39, s4, s5
; SI-NEXT:    s_and_b32 s4, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s91, 16
; SI-NEXT:    s_or_b32 s40, s4, s5
; SI-NEXT:    s_and_b32 s4, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s90, 16
; SI-NEXT:    s_or_b32 s41, s4, s5
; SI-NEXT:    s_and_b32 s4, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s89, 16
; SI-NEXT:    s_or_b32 s42, s4, s5
; SI-NEXT:    s_and_b32 s4, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s88, 16
; SI-NEXT:    s_or_b32 s43, s4, s5
; SI-NEXT:    s_and_b32 s4, s24, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s79, 16
; SI-NEXT:    s_or_b32 s44, s4, s5
; SI-NEXT:    s_and_b32 s4, s25, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s78, 16
; SI-NEXT:    s_or_b32 s45, s4, s5
; SI-NEXT:    s_and_b32 s4, s26, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s77, 16
; SI-NEXT:    s_or_b32 s46, s4, s5
; SI-NEXT:    s_and_b32 s4, s27, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s76, 16
; SI-NEXT:    s_or_b32 s47, s4, s5
; SI-NEXT:    s_and_b32 s4, s28, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s75, 16
; SI-NEXT:    s_or_b32 s48, s4, s5
; SI-NEXT:    s_and_b32 s4, s29, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s72, 16
; SI-NEXT:    s_or_b32 s49, s4, s5
; SI-NEXT:    s_and_b32 s4, s73, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s74, 16
; SI-NEXT:    s_or_b32 s50, s4, s5
; SI-NEXT:    s_and_b32 s4, s14, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s15, 16
; SI-NEXT:    s_or_b32 s51, s4, s5
; SI-NEXT:    s_and_b32 s4, s12, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s13, 16
; SI-NEXT:    s_or_b32 s52, s4, s5
; SI-NEXT:    s_and_b32 s4, s10, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s11, 16
; SI-NEXT:    s_or_b32 s53, s4, s5
; SI-NEXT:    s_and_b32 s4, s8, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s9, 16
; SI-NEXT:    s_or_b32 s54, s4, s5
; SI-NEXT:    s_and_b32 s4, s6, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s7, 16
; SI-NEXT:    s_or_b32 s55, s4, s5
; SI-NEXT:    ; implicit-def: $sgpr56
; SI-NEXT:    ; implicit-def: $sgpr57
; SI-NEXT:    ; implicit-def: $sgpr58
; SI-NEXT:    ; implicit-def: $sgpr59
; SI-NEXT:    ; implicit-def: $sgpr60
; SI-NEXT:    ; implicit-def: $sgpr61
; SI-NEXT:    ; implicit-def: $sgpr62
; SI-NEXT:    ; implicit-def: $sgpr63
; SI-NEXT:    ; implicit-def: $sgpr64
; SI-NEXT:    ; implicit-def: $sgpr65
; SI-NEXT:    ; implicit-def: $sgpr66
; SI-NEXT:    ; implicit-def: $sgpr67
; SI-NEXT:    s_cbranch_execnz .LBB55_4
; SI-NEXT:  .LBB55_2: ; %cmp.true
; SI-NEXT:    v_cvt_f32_f16_e32 v0, s95
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s16
; SI-NEXT:    v_cvt_f32_f16_e32 v2, s94
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s17
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_cvt_f32_f16_e32 v4, s18
; SI-NEXT:    v_or_b32_e32 v0, v1, v0
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v2, s93
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_or_b32_e32 v1, v3, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s92
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_or_b32_e32 v2, v4, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v4, s19
; SI-NEXT:    v_cvt_f32_f16_e32 v5, s91
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v6, s20
; SI-NEXT:    v_or_b32_e32 v3, v4, v3
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v5, s90
; SI-NEXT:    v_cvt_f32_f16_e32 v7, s21
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_or_b32_e32 v4, v6, v4
; SI-NEXT:    v_cvt_f32_f16_e32 v6, s89
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_or_b32_e32 v5, v7, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v7, s22
; SI-NEXT:    v_cvt_f32_f16_e32 v8, s88
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v8, v8
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v6
; SI-NEXT:    v_cvt_f32_f16_e32 v9, s23
; SI-NEXT:    v_or_b32_e32 v6, v7, v6
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v8
; SI-NEXT:    v_cvt_f32_f16_e32 v8, s79
; SI-NEXT:    v_cvt_f32_f16_e32 v10, s24
; SI-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v9
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v8, v8
; SI-NEXT:    v_add_f32_e32 v10, 0x38000000, v10
; SI-NEXT:    v_cvt_f16_f32_e32 v10, v10
; SI-NEXT:    v_or_b32_e32 v7, v9, v7
; SI-NEXT:    v_cvt_f32_f16_e32 v9, s78
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v8
; SI-NEXT:    v_or_b32_e32 v8, v10, v8
; SI-NEXT:    v_cvt_f32_f16_e32 v10, s25
; SI-NEXT:    v_cvt_f32_f16_e32 v11, s77
; SI-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v9
; SI-NEXT:    v_add_f32_e32 v10, 0x38000000, v10
; SI-NEXT:    v_add_f32_e32 v11, 0x38000000, v11
; SI-NEXT:    v_cvt_f16_f32_e32 v10, v10
; SI-NEXT:    v_cvt_f16_f32_e32 v11, v11
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; SI-NEXT:    v_cvt_f32_f16_e32 v12, s26
; SI-NEXT:    v_or_b32_e32 v9, v10, v9
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v11
; SI-NEXT:    v_cvt_f32_f16_e32 v11, s76
; SI-NEXT:    v_cvt_f32_f16_e32 v13, s27
; SI-NEXT:    v_add_f32_e32 v12, 0x38000000, v12
; SI-NEXT:    v_cvt_f16_f32_e32 v12, v12
; SI-NEXT:    v_add_f32_e32 v11, 0x38000000, v11
; SI-NEXT:    v_cvt_f16_f32_e32 v11, v11
; SI-NEXT:    v_add_f32_e32 v13, 0x38000000, v13
; SI-NEXT:    v_cvt_f16_f32_e32 v13, v13
; SI-NEXT:    v_or_b32_e32 v10, v12, v10
; SI-NEXT:    v_cvt_f32_f16_e32 v12, s75
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; SI-NEXT:    v_or_b32_e32 v11, v13, v11
; SI-NEXT:    v_cvt_f32_f16_e32 v13, s28
; SI-NEXT:    v_cvt_f32_f16_e32 v14, s72
; SI-NEXT:    v_add_f32_e32 v12, 0x38000000, v12
; SI-NEXT:    v_cvt_f16_f32_e32 v12, v12
; SI-NEXT:    v_add_f32_e32 v13, 0x38000000, v13
; SI-NEXT:    v_add_f32_e32 v14, 0x38000000, v14
; SI-NEXT:    v_cvt_f16_f32_e32 v13, v13
; SI-NEXT:    v_cvt_f16_f32_e32 v14, v14
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v12
; SI-NEXT:    v_cvt_f32_f16_e32 v15, s29
; SI-NEXT:    v_or_b32_e32 v12, v13, v12
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v14
; SI-NEXT:    v_cvt_f32_f16_e32 v14, s74
; SI-NEXT:    v_cvt_f32_f16_e32 v16, s73
; SI-NEXT:    v_add_f32_e32 v15, 0x38000000, v15
; SI-NEXT:    v_cvt_f16_f32_e32 v15, v15
; SI-NEXT:    v_add_f32_e32 v14, 0x38000000, v14
; SI-NEXT:    v_cvt_f16_f32_e32 v14, v14
; SI-NEXT:    v_add_f32_e32 v16, 0x38000000, v16
; SI-NEXT:    v_cvt_f16_f32_e32 v16, v16
; SI-NEXT:    v_or_b32_e32 v13, v15, v13
; SI-NEXT:    v_cvt_f32_f16_e32 v15, s15
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v14
; SI-NEXT:    v_or_b32_e32 v14, v16, v14
; SI-NEXT:    v_cvt_f32_f16_e32 v16, s14
; SI-NEXT:    v_cvt_f32_f16_e32 v17, s13
; SI-NEXT:    v_add_f32_e32 v15, 0x38000000, v15
; SI-NEXT:    v_cvt_f16_f32_e32 v15, v15
; SI-NEXT:    v_add_f32_e32 v16, 0x38000000, v16
; SI-NEXT:    v_add_f32_e32 v17, 0x38000000, v17
; SI-NEXT:    v_cvt_f16_f32_e32 v16, v16
; SI-NEXT:    v_cvt_f16_f32_e32 v17, v17
; SI-NEXT:    v_lshlrev_b32_e32 v15, 16, v15
; SI-NEXT:    v_cvt_f32_f16_e32 v18, s12
; SI-NEXT:    v_or_b32_e32 v15, v16, v15
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v17
; SI-NEXT:    v_cvt_f32_f16_e32 v17, s11
; SI-NEXT:    v_cvt_f32_f16_e32 v19, s10
; SI-NEXT:    v_add_f32_e32 v18, 0x38000000, v18
; SI-NEXT:    v_cvt_f16_f32_e32 v18, v18
; SI-NEXT:    v_add_f32_e32 v17, 0x38000000, v17
; SI-NEXT:    v_cvt_f16_f32_e32 v17, v17
; SI-NEXT:    v_add_f32_e32 v19, 0x38000000, v19
; SI-NEXT:    v_cvt_f16_f32_e32 v19, v19
; SI-NEXT:    v_or_b32_e32 v16, v18, v16
; SI-NEXT:    v_cvt_f32_f16_e32 v18, s9
; SI-NEXT:    v_lshlrev_b32_e32 v17, 16, v17
; SI-NEXT:    v_or_b32_e32 v17, v19, v17
; SI-NEXT:    v_cvt_f32_f16_e32 v19, s8
; SI-NEXT:    v_cvt_f32_f16_e32 v20, s7
; SI-NEXT:    v_cvt_f32_f16_e32 v21, s6
; SI-NEXT:    v_add_f32_e32 v18, 0x38000000, v18
; SI-NEXT:    v_cvt_f16_f32_e32 v18, v18
; SI-NEXT:    v_add_f32_e32 v19, 0x38000000, v19
; SI-NEXT:    v_add_f32_e32 v20, 0x38000000, v20
; SI-NEXT:    v_cvt_f16_f32_e32 v19, v19
; SI-NEXT:    v_cvt_f16_f32_e32 v20, v20
; SI-NEXT:    v_add_f32_e32 v21, 0x38000000, v21
; SI-NEXT:    v_cvt_f16_f32_e32 v21, v21
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v18
; SI-NEXT:    v_or_b32_e32 v18, v19, v18
; SI-NEXT:    v_lshlrev_b32_e32 v19, 16, v20
; SI-NEXT:    v_or_b32_e32 v19, v21, v19
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    s_branch .LBB55_5
; SI-NEXT:  .LBB55_3:
; SI-NEXT:    ; implicit-def: $sgpr36_sgpr37_sgpr38_sgpr39_sgpr40_sgpr41_sgpr42_sgpr43_sgpr44_sgpr45_sgpr46_sgpr47_sgpr48_sgpr49_sgpr50_sgpr51_sgpr52_sgpr53_sgpr54_sgpr55_sgpr56_sgpr57_sgpr58_sgpr59_sgpr60_sgpr61_sgpr62_sgpr63_sgpr64_sgpr65_sgpr66_sgpr67
; SI-NEXT:    s_branch .LBB55_2
; SI-NEXT:  .LBB55_4:
; SI-NEXT:    v_mov_b32_e32 v0, s36
; SI-NEXT:    v_mov_b32_e32 v1, s37
; SI-NEXT:    v_mov_b32_e32 v2, s38
; SI-NEXT:    v_mov_b32_e32 v3, s39
; SI-NEXT:    v_mov_b32_e32 v4, s40
; SI-NEXT:    v_mov_b32_e32 v5, s41
; SI-NEXT:    v_mov_b32_e32 v6, s42
; SI-NEXT:    v_mov_b32_e32 v7, s43
; SI-NEXT:    v_mov_b32_e32 v8, s44
; SI-NEXT:    v_mov_b32_e32 v9, s45
; SI-NEXT:    v_mov_b32_e32 v10, s46
; SI-NEXT:    v_mov_b32_e32 v11, s47
; SI-NEXT:    v_mov_b32_e32 v12, s48
; SI-NEXT:    v_mov_b32_e32 v13, s49
; SI-NEXT:    v_mov_b32_e32 v14, s50
; SI-NEXT:    v_mov_b32_e32 v15, s51
; SI-NEXT:    v_mov_b32_e32 v16, s52
; SI-NEXT:    v_mov_b32_e32 v17, s53
; SI-NEXT:    v_mov_b32_e32 v18, s54
; SI-NEXT:    v_mov_b32_e32 v19, s55
; SI-NEXT:    v_mov_b32_e32 v20, s56
; SI-NEXT:    v_mov_b32_e32 v21, s57
; SI-NEXT:    v_mov_b32_e32 v22, s58
; SI-NEXT:    v_mov_b32_e32 v23, s59
; SI-NEXT:    v_mov_b32_e32 v24, s60
; SI-NEXT:    v_mov_b32_e32 v25, s61
; SI-NEXT:    v_mov_b32_e32 v26, s62
; SI-NEXT:    v_mov_b32_e32 v27, s63
; SI-NEXT:    v_mov_b32_e32 v28, s64
; SI-NEXT:    v_mov_b32_e32 v29, s65
; SI-NEXT:    v_mov_b32_e32 v30, s66
; SI-NEXT:    v_mov_b32_e32 v31, s67
; SI-NEXT:  .LBB55_5: ; %end
; SI-NEXT:    v_readlane_b32 s67, v32, 15
; SI-NEXT:    v_readlane_b32 s66, v32, 14
; SI-NEXT:    v_readlane_b32 s65, v32, 13
; SI-NEXT:    v_readlane_b32 s64, v32, 12
; SI-NEXT:    v_readlane_b32 s55, v32, 11
; SI-NEXT:    v_readlane_b32 s54, v32, 10
; SI-NEXT:    v_readlane_b32 s53, v32, 9
; SI-NEXT:    v_readlane_b32 s52, v32, 8
; SI-NEXT:    v_readlane_b32 s51, v32, 7
; SI-NEXT:    v_readlane_b32 s50, v32, 6
; SI-NEXT:    v_readlane_b32 s49, v32, 5
; SI-NEXT:    v_readlane_b32 s48, v32, 4
; SI-NEXT:    v_readlane_b32 s39, v32, 3
; SI-NEXT:    v_readlane_b32 s38, v32, 2
; SI-NEXT:    v_readlane_b32 s37, v32, 1
; SI-NEXT:    v_readlane_b32 s36, v32, 0
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v40f16_to_v10f64_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    v_writelane_b32 v32, s34, 0
; VI-NEXT:    v_writelane_b32 v32, s35, 1
; VI-NEXT:    v_writelane_b32 v32, s36, 2
; VI-NEXT:    v_writelane_b32 v32, s37, 3
; VI-NEXT:    v_writelane_b32 v32, s38, 4
; VI-NEXT:    v_writelane_b32 v32, s39, 5
; VI-NEXT:    v_writelane_b32 v32, s48, 6
; VI-NEXT:    v_writelane_b32 v32, s49, 7
; VI-NEXT:    v_writelane_b32 v32, s50, 8
; VI-NEXT:    v_writelane_b32 v32, s51, 9
; VI-NEXT:    v_writelane_b32 v32, s52, 10
; VI-NEXT:    v_writelane_b32 v32, s53, 11
; VI-NEXT:    v_writelane_b32 v32, s54, 12
; VI-NEXT:    v_writelane_b32 v32, s55, 13
; VI-NEXT:    v_writelane_b32 v32, s64, 14
; VI-NEXT:    v_writelane_b32 v32, s65, 15
; VI-NEXT:    v_writelane_b32 v32, s66, 16
; VI-NEXT:    v_writelane_b32 v32, s67, 17
; VI-NEXT:    v_writelane_b32 v32, s30, 18
; VI-NEXT:    v_writelane_b32 v32, s31, 19
; VI-NEXT:    v_readfirstlane_b32 s6, v5
; VI-NEXT:    v_readfirstlane_b32 s8, v4
; VI-NEXT:    v_readfirstlane_b32 s11, v3
; VI-NEXT:    v_readfirstlane_b32 s14, v2
; VI-NEXT:    v_readfirstlane_b32 s73, v1
; VI-NEXT:    v_readfirstlane_b32 s76, v0
; VI-NEXT:    s_lshr_b32 s10, s29, 16
; VI-NEXT:    s_lshr_b32 s13, s28, 16
; VI-NEXT:    s_lshr_b32 s72, s27, 16
; VI-NEXT:    s_lshr_b32 s74, s26, 16
; VI-NEXT:    s_lshr_b32 s77, s25, 16
; VI-NEXT:    s_lshr_b32 s79, s24, 16
; VI-NEXT:    s_lshr_b32 s88, s23, 16
; VI-NEXT:    s_lshr_b32 s89, s22, 16
; VI-NEXT:    s_lshr_b32 s90, s21, 16
; VI-NEXT:    s_lshr_b32 s91, s20, 16
; VI-NEXT:    s_lshr_b32 s30, s19, 16
; VI-NEXT:    s_lshr_b32 s31, s18, 16
; VI-NEXT:    s_lshr_b32 s34, s17, 16
; VI-NEXT:    s_lshr_b32 s35, s16, 16
; VI-NEXT:    s_lshr_b32 s7, s6, 16
; VI-NEXT:    s_lshr_b32 s9, s8, 16
; VI-NEXT:    s_lshr_b32 s12, s11, 16
; VI-NEXT:    s_lshr_b32 s15, s14, 16
; VI-NEXT:    s_lshr_b32 s75, s73, 16
; VI-NEXT:    s_lshr_b32 s78, s76, 16
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    s_cbranch_scc0 .LBB55_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_and_b32 s4, 0xffff, s16
; VI-NEXT:    s_lshl_b32 s5, s35, 16
; VI-NEXT:    s_or_b32 s36, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s17
; VI-NEXT:    s_lshl_b32 s5, s34, 16
; VI-NEXT:    s_or_b32 s37, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s18
; VI-NEXT:    s_lshl_b32 s5, s31, 16
; VI-NEXT:    s_or_b32 s38, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s19
; VI-NEXT:    s_lshl_b32 s5, s30, 16
; VI-NEXT:    s_or_b32 s39, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s20
; VI-NEXT:    s_lshl_b32 s5, s91, 16
; VI-NEXT:    s_or_b32 s40, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s21
; VI-NEXT:    s_lshl_b32 s5, s90, 16
; VI-NEXT:    s_or_b32 s41, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s22
; VI-NEXT:    s_lshl_b32 s5, s89, 16
; VI-NEXT:    s_or_b32 s42, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s23
; VI-NEXT:    s_lshl_b32 s5, s88, 16
; VI-NEXT:    s_or_b32 s43, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s24
; VI-NEXT:    s_lshl_b32 s5, s79, 16
; VI-NEXT:    s_or_b32 s44, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s25
; VI-NEXT:    s_lshl_b32 s5, s77, 16
; VI-NEXT:    s_or_b32 s45, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s26
; VI-NEXT:    s_lshl_b32 s5, s74, 16
; VI-NEXT:    s_or_b32 s46, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s27
; VI-NEXT:    s_lshl_b32 s5, s72, 16
; VI-NEXT:    s_or_b32 s47, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s28
; VI-NEXT:    s_lshl_b32 s5, s13, 16
; VI-NEXT:    s_or_b32 s48, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s29
; VI-NEXT:    s_lshl_b32 s5, s10, 16
; VI-NEXT:    s_or_b32 s49, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s76
; VI-NEXT:    s_lshl_b32 s5, s78, 16
; VI-NEXT:    s_or_b32 s50, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s73
; VI-NEXT:    s_lshl_b32 s5, s75, 16
; VI-NEXT:    s_or_b32 s51, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s14
; VI-NEXT:    s_lshl_b32 s5, s15, 16
; VI-NEXT:    s_or_b32 s52, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s11
; VI-NEXT:    s_lshl_b32 s5, s12, 16
; VI-NEXT:    s_or_b32 s53, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s8
; VI-NEXT:    s_lshl_b32 s5, s9, 16
; VI-NEXT:    s_or_b32 s54, s4, s5
; VI-NEXT:    s_and_b32 s4, 0xffff, s6
; VI-NEXT:    s_lshl_b32 s5, s7, 16
; VI-NEXT:    s_or_b32 s55, s4, s5
; VI-NEXT:    ; implicit-def: $sgpr56
; VI-NEXT:    ; implicit-def: $sgpr57
; VI-NEXT:    ; implicit-def: $sgpr58
; VI-NEXT:    ; implicit-def: $sgpr59
; VI-NEXT:    ; implicit-def: $sgpr60
; VI-NEXT:    ; implicit-def: $sgpr61
; VI-NEXT:    ; implicit-def: $sgpr62
; VI-NEXT:    ; implicit-def: $sgpr63
; VI-NEXT:    ; implicit-def: $sgpr64
; VI-NEXT:    ; implicit-def: $sgpr65
; VI-NEXT:    ; implicit-def: $sgpr66
; VI-NEXT:    ; implicit-def: $sgpr67
; VI-NEXT:    s_cbranch_execnz .LBB55_4
; VI-NEXT:  .LBB55_2: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v19, 0x200
; VI-NEXT:    v_mov_b32_e32 v0, s35
; VI-NEXT:    v_mov_b32_e32 v2, s34
; VI-NEXT:    v_add_f16_sdwa v0, v0, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v1, s16, v19
; VI-NEXT:    v_add_f16_sdwa v2, v2, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v3, s17, v19
; VI-NEXT:    v_or_b32_e32 v0, v1, v0
; VI-NEXT:    v_or_b32_e32 v1, v3, v2
; VI-NEXT:    v_mov_b32_e32 v2, s31
; VI-NEXT:    v_add_f16_sdwa v2, v2, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v3, s18, v19
; VI-NEXT:    v_or_b32_e32 v2, v3, v2
; VI-NEXT:    v_mov_b32_e32 v3, s30
; VI-NEXT:    v_add_f16_sdwa v3, v3, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v4, s19, v19
; VI-NEXT:    v_or_b32_e32 v3, v4, v3
; VI-NEXT:    v_mov_b32_e32 v4, s91
; VI-NEXT:    v_add_f16_sdwa v4, v4, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v5, s20, v19
; VI-NEXT:    v_or_b32_e32 v4, v5, v4
; VI-NEXT:    v_mov_b32_e32 v5, s90
; VI-NEXT:    v_add_f16_sdwa v5, v5, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v6, s21, v19
; VI-NEXT:    v_or_b32_e32 v5, v6, v5
; VI-NEXT:    v_mov_b32_e32 v6, s89
; VI-NEXT:    v_add_f16_sdwa v6, v6, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v7, s22, v19
; VI-NEXT:    v_or_b32_e32 v6, v7, v6
; VI-NEXT:    v_mov_b32_e32 v7, s88
; VI-NEXT:    v_add_f16_sdwa v7, v7, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v8, s23, v19
; VI-NEXT:    v_or_b32_e32 v7, v8, v7
; VI-NEXT:    v_mov_b32_e32 v8, s79
; VI-NEXT:    v_add_f16_sdwa v8, v8, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v9, s24, v19
; VI-NEXT:    v_or_b32_e32 v8, v9, v8
; VI-NEXT:    v_mov_b32_e32 v9, s77
; VI-NEXT:    v_add_f16_sdwa v9, v9, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v10, s25, v19
; VI-NEXT:    v_or_b32_e32 v9, v10, v9
; VI-NEXT:    v_mov_b32_e32 v10, s74
; VI-NEXT:    v_add_f16_sdwa v10, v10, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v11, s26, v19
; VI-NEXT:    v_or_b32_e32 v10, v11, v10
; VI-NEXT:    v_mov_b32_e32 v11, s72
; VI-NEXT:    v_add_f16_sdwa v11, v11, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v12, s27, v19
; VI-NEXT:    v_or_b32_e32 v11, v12, v11
; VI-NEXT:    v_mov_b32_e32 v12, s13
; VI-NEXT:    v_add_f16_sdwa v12, v12, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v13, s28, v19
; VI-NEXT:    v_or_b32_e32 v12, v13, v12
; VI-NEXT:    v_mov_b32_e32 v13, s10
; VI-NEXT:    v_add_f16_sdwa v13, v13, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v14, s29, v19
; VI-NEXT:    v_or_b32_e32 v13, v14, v13
; VI-NEXT:    v_mov_b32_e32 v14, s78
; VI-NEXT:    v_add_f16_sdwa v14, v14, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v15, s76, v19
; VI-NEXT:    v_or_b32_e32 v14, v15, v14
; VI-NEXT:    v_mov_b32_e32 v15, s75
; VI-NEXT:    v_add_f16_sdwa v15, v15, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v16, s73, v19
; VI-NEXT:    v_or_b32_e32 v15, v16, v15
; VI-NEXT:    v_mov_b32_e32 v16, s15
; VI-NEXT:    v_add_f16_sdwa v16, v16, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v17, s14, v19
; VI-NEXT:    v_or_b32_e32 v16, v17, v16
; VI-NEXT:    v_mov_b32_e32 v17, s12
; VI-NEXT:    v_add_f16_sdwa v17, v17, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v18, s11, v19
; VI-NEXT:    v_or_b32_e32 v17, v18, v17
; VI-NEXT:    v_mov_b32_e32 v18, s9
; VI-NEXT:    v_add_f16_sdwa v18, v18, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v20, s8, v19
; VI-NEXT:    v_or_b32_e32 v18, v20, v18
; VI-NEXT:    v_mov_b32_e32 v20, s7
; VI-NEXT:    v_add_f16_sdwa v20, v20, v19 dst_sel:WORD_1 dst_unused:UNUSED_PAD src0_sel:DWORD src1_sel:DWORD
; VI-NEXT:    v_add_f16_e32 v19, s6, v19
; VI-NEXT:    v_or_b32_e32 v19, v19, v20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    ; implicit-def: $vgpr20
; VI-NEXT:    s_branch .LBB55_5
; VI-NEXT:  .LBB55_3:
; VI-NEXT:    ; implicit-def: $sgpr36_sgpr37_sgpr38_sgpr39_sgpr40_sgpr41_sgpr42_sgpr43_sgpr44_sgpr45_sgpr46_sgpr47_sgpr48_sgpr49_sgpr50_sgpr51_sgpr52_sgpr53_sgpr54_sgpr55_sgpr56_sgpr57_sgpr58_sgpr59_sgpr60_sgpr61_sgpr62_sgpr63_sgpr64_sgpr65_sgpr66_sgpr67
; VI-NEXT:    s_branch .LBB55_2
; VI-NEXT:  .LBB55_4:
; VI-NEXT:    v_mov_b32_e32 v0, s36
; VI-NEXT:    v_mov_b32_e32 v1, s37
; VI-NEXT:    v_mov_b32_e32 v2, s38
; VI-NEXT:    v_mov_b32_e32 v3, s39
; VI-NEXT:    v_mov_b32_e32 v4, s40
; VI-NEXT:    v_mov_b32_e32 v5, s41
; VI-NEXT:    v_mov_b32_e32 v6, s42
; VI-NEXT:    v_mov_b32_e32 v7, s43
; VI-NEXT:    v_mov_b32_e32 v8, s44
; VI-NEXT:    v_mov_b32_e32 v9, s45
; VI-NEXT:    v_mov_b32_e32 v10, s46
; VI-NEXT:    v_mov_b32_e32 v11, s47
; VI-NEXT:    v_mov_b32_e32 v12, s48
; VI-NEXT:    v_mov_b32_e32 v13, s49
; VI-NEXT:    v_mov_b32_e32 v14, s50
; VI-NEXT:    v_mov_b32_e32 v15, s51
; VI-NEXT:    v_mov_b32_e32 v16, s52
; VI-NEXT:    v_mov_b32_e32 v17, s53
; VI-NEXT:    v_mov_b32_e32 v18, s54
; VI-NEXT:    v_mov_b32_e32 v19, s55
; VI-NEXT:    v_mov_b32_e32 v20, s56
; VI-NEXT:    v_mov_b32_e32 v21, s57
; VI-NEXT:    v_mov_b32_e32 v22, s58
; VI-NEXT:    v_mov_b32_e32 v23, s59
; VI-NEXT:    v_mov_b32_e32 v24, s60
; VI-NEXT:    v_mov_b32_e32 v25, s61
; VI-NEXT:    v_mov_b32_e32 v26, s62
; VI-NEXT:    v_mov_b32_e32 v27, s63
; VI-NEXT:    v_mov_b32_e32 v28, s64
; VI-NEXT:    v_mov_b32_e32 v29, s65
; VI-NEXT:    v_mov_b32_e32 v30, s66
; VI-NEXT:    v_mov_b32_e32 v31, s67
; VI-NEXT:  .LBB55_5: ; %end
; VI-NEXT:    v_readlane_b32 s30, v32, 18
; VI-NEXT:    v_readlane_b32 s31, v32, 19
; VI-NEXT:    v_readlane_b32 s67, v32, 17
; VI-NEXT:    v_readlane_b32 s66, v32, 16
; VI-NEXT:    v_readlane_b32 s65, v32, 15
; VI-NEXT:    v_readlane_b32 s64, v32, 14
; VI-NEXT:    v_readlane_b32 s55, v32, 13
; VI-NEXT:    v_readlane_b32 s54, v32, 12
; VI-NEXT:    v_readlane_b32 s53, v32, 11
; VI-NEXT:    v_readlane_b32 s52, v32, 10
; VI-NEXT:    v_readlane_b32 s51, v32, 9
; VI-NEXT:    v_readlane_b32 s50, v32, 8
; VI-NEXT:    v_readlane_b32 s49, v32, 7
; VI-NEXT:    v_readlane_b32 s48, v32, 6
; VI-NEXT:    v_readlane_b32 s39, v32, 5
; VI-NEXT:    v_readlane_b32 s38, v32, 4
; VI-NEXT:    v_readlane_b32 s37, v32, 3
; VI-NEXT:    v_readlane_b32 s36, v32, 2
; VI-NEXT:    v_readlane_b32 s35, v32, 1
; VI-NEXT:    v_readlane_b32 s34, v32, 0
; VI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; VI-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; VI-NEXT:    s_mov_b64 exec, s[4:5]
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v40f16_to_v10f64_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_store_dword v32, off, s[0:3], s32 ; 4-byte Folded Spill
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    v_writelane_b32 v32, s36, 0
; GFX9-NEXT:    v_writelane_b32 v32, s37, 1
; GFX9-NEXT:    v_writelane_b32 v32, s38, 2
; GFX9-NEXT:    v_writelane_b32 v32, s39, 3
; GFX9-NEXT:    v_writelane_b32 v32, s48, 4
; GFX9-NEXT:    v_writelane_b32 v32, s49, 5
; GFX9-NEXT:    v_writelane_b32 v32, s50, 6
; GFX9-NEXT:    v_writelane_b32 v32, s51, 7
; GFX9-NEXT:    v_writelane_b32 v32, s52, 8
; GFX9-NEXT:    v_writelane_b32 v32, s53, 9
; GFX9-NEXT:    v_writelane_b32 v32, s54, 10
; GFX9-NEXT:    v_writelane_b32 v32, s55, 11
; GFX9-NEXT:    v_readfirstlane_b32 s56, v5
; GFX9-NEXT:    v_readfirstlane_b32 s58, v4
; GFX9-NEXT:    v_readfirstlane_b32 s60, v3
; GFX9-NEXT:    v_readfirstlane_b32 s62, v2
; GFX9-NEXT:    v_readfirstlane_b32 s72, v1
; GFX9-NEXT:    v_readfirstlane_b32 s74, v0
; GFX9-NEXT:    s_lshr_b32 s4, s29, 16
; GFX9-NEXT:    s_lshr_b32 s5, s28, 16
; GFX9-NEXT:    s_lshr_b32 s6, s27, 16
; GFX9-NEXT:    s_lshr_b32 s7, s26, 16
; GFX9-NEXT:    s_lshr_b32 s8, s25, 16
; GFX9-NEXT:    s_lshr_b32 s9, s24, 16
; GFX9-NEXT:    s_lshr_b32 s10, s23, 16
; GFX9-NEXT:    s_lshr_b32 s11, s22, 16
; GFX9-NEXT:    s_lshr_b32 s12, s21, 16
; GFX9-NEXT:    s_lshr_b32 s13, s20, 16
; GFX9-NEXT:    s_lshr_b32 s14, s19, 16
; GFX9-NEXT:    s_lshr_b32 s15, s18, 16
; GFX9-NEXT:    s_lshr_b32 s40, s17, 16
; GFX9-NEXT:    s_lshr_b32 s41, s16, 16
; GFX9-NEXT:    s_lshr_b32 s57, s56, 16
; GFX9-NEXT:    s_lshr_b32 s59, s58, 16
; GFX9-NEXT:    s_lshr_b32 s61, s60, 16
; GFX9-NEXT:    s_lshr_b32 s63, s62, 16
; GFX9-NEXT:    s_lshr_b32 s73, s72, 16
; GFX9-NEXT:    s_lshr_b32 s75, s74, 16
; GFX9-NEXT:    v_readfirstlane_b32 s42, v6
; GFX9-NEXT:    s_cmp_lg_u32 s42, 0
; GFX9-NEXT:    s_pack_ll_b32_b16 s36, s16, s41
; GFX9-NEXT:    s_pack_ll_b32_b16 s37, s17, s40
; GFX9-NEXT:    s_pack_ll_b32_b16 s38, s18, s15
; GFX9-NEXT:    s_pack_ll_b32_b16 s39, s19, s14
; GFX9-NEXT:    s_pack_ll_b32_b16 s40, s20, s13
; GFX9-NEXT:    s_pack_ll_b32_b16 s41, s21, s12
; GFX9-NEXT:    s_pack_ll_b32_b16 s42, s22, s11
; GFX9-NEXT:    s_pack_ll_b32_b16 s43, s23, s10
; GFX9-NEXT:    s_pack_ll_b32_b16 s44, s24, s9
; GFX9-NEXT:    s_pack_ll_b32_b16 s45, s25, s8
; GFX9-NEXT:    s_pack_ll_b32_b16 s46, s26, s7
; GFX9-NEXT:    s_pack_ll_b32_b16 s47, s27, s6
; GFX9-NEXT:    s_pack_ll_b32_b16 s48, s28, s5
; GFX9-NEXT:    s_pack_ll_b32_b16 s49, s29, s4
; GFX9-NEXT:    s_pack_ll_b32_b16 s50, s74, s75
; GFX9-NEXT:    s_pack_ll_b32_b16 s51, s72, s73
; GFX9-NEXT:    s_pack_ll_b32_b16 s52, s62, s63
; GFX9-NEXT:    s_pack_ll_b32_b16 s53, s60, s61
; GFX9-NEXT:    s_pack_ll_b32_b16 s54, s58, s59
; GFX9-NEXT:    s_pack_ll_b32_b16 s55, s56, s57
; GFX9-NEXT:    s_cbranch_scc0 .LBB55_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB55_4
; GFX9-NEXT:  .LBB55_2: ; %cmp.true
; GFX9-NEXT:    v_mov_b32_e32 v19, 0x200
; GFX9-NEXT:    v_pk_add_f16 v0, s36, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v1, s37, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v2, s38, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v3, s39, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v4, s40, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v5, s41, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, s42, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v7, s43, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v8, s44, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v9, s45, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v10, s46, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v11, s47, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v12, s48, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v13, s49, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v14, s50, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v15, s51, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v16, s52, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v17, s53, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v18, s54, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v19, s55, v19 op_sel_hi:[1,0]
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    ; implicit-def: $vgpr20
; GFX9-NEXT:    s_branch .LBB55_5
; GFX9-NEXT:  .LBB55_3:
; GFX9-NEXT:    s_branch .LBB55_2
; GFX9-NEXT:  .LBB55_4:
; GFX9-NEXT:    v_mov_b32_e32 v0, s36
; GFX9-NEXT:    v_mov_b32_e32 v1, s37
; GFX9-NEXT:    v_mov_b32_e32 v2, s38
; GFX9-NEXT:    v_mov_b32_e32 v3, s39
; GFX9-NEXT:    v_mov_b32_e32 v4, s40
; GFX9-NEXT:    v_mov_b32_e32 v5, s41
; GFX9-NEXT:    v_mov_b32_e32 v6, s42
; GFX9-NEXT:    v_mov_b32_e32 v7, s43
; GFX9-NEXT:    v_mov_b32_e32 v8, s44
; GFX9-NEXT:    v_mov_b32_e32 v9, s45
; GFX9-NEXT:    v_mov_b32_e32 v10, s46
; GFX9-NEXT:    v_mov_b32_e32 v11, s47
; GFX9-NEXT:    v_mov_b32_e32 v12, s48
; GFX9-NEXT:    v_mov_b32_e32 v13, s49
; GFX9-NEXT:    v_mov_b32_e32 v14, s50
; GFX9-NEXT:    v_mov_b32_e32 v15, s51
; GFX9-NEXT:    v_mov_b32_e32 v16, s52
; GFX9-NEXT:    v_mov_b32_e32 v17, s53
; GFX9-NEXT:    v_mov_b32_e32 v18, s54
; GFX9-NEXT:    v_mov_b32_e32 v19, s55
; GFX9-NEXT:    v_mov_b32_e32 v20, s56
; GFX9-NEXT:    v_mov_b32_e32 v21, s57
; GFX9-NEXT:    v_mov_b32_e32 v22, s58
; GFX9-NEXT:    v_mov_b32_e32 v23, s59
; GFX9-NEXT:    v_mov_b32_e32 v24, s60
; GFX9-NEXT:    v_mov_b32_e32 v25, s61
; GFX9-NEXT:    v_mov_b32_e32 v26, s62
; GFX9-NEXT:    v_mov_b32_e32 v27, s63
; GFX9-NEXT:    v_mov_b32_e32 v28, s64
; GFX9-NEXT:    v_mov_b32_e32 v29, s65
; GFX9-NEXT:    v_mov_b32_e32 v30, s66
; GFX9-NEXT:    v_mov_b32_e32 v31, s67
; GFX9-NEXT:  .LBB55_5: ; %end
; GFX9-NEXT:    v_readlane_b32 s55, v32, 11
; GFX9-NEXT:    v_readlane_b32 s54, v32, 10
; GFX9-NEXT:    v_readlane_b32 s53, v32, 9
; GFX9-NEXT:    v_readlane_b32 s52, v32, 8
; GFX9-NEXT:    v_readlane_b32 s51, v32, 7
; GFX9-NEXT:    v_readlane_b32 s50, v32, 6
; GFX9-NEXT:    v_readlane_b32 s49, v32, 5
; GFX9-NEXT:    v_readlane_b32 s48, v32, 4
; GFX9-NEXT:    v_readlane_b32 s39, v32, 3
; GFX9-NEXT:    v_readlane_b32 s38, v32, 2
; GFX9-NEXT:    v_readlane_b32 s37, v32, 1
; GFX9-NEXT:    v_readlane_b32 s36, v32, 0
; GFX9-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; GFX9-NEXT:    buffer_load_dword v32, off, s[0:3], s32 ; 4-byte Folded Reload
; GFX9-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-LABEL: bitcast_v40f16_to_v10f64_scalar:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-NEXT:    v_readfirstlane_b32 s45, v1
; GFX11-NEXT:    v_readfirstlane_b32 s46, v0
; GFX11-NEXT:    v_readfirstlane_b32 s56, v2
; GFX11-NEXT:    s_lshr_b32 s41, s29, 16
; GFX11-NEXT:    s_lshr_b32 s42, s28, 16
; GFX11-NEXT:    s_lshr_b32 s15, s27, 16
; GFX11-NEXT:    s_lshr_b32 s14, s26, 16
; GFX11-NEXT:    s_lshr_b32 s13, s25, 16
; GFX11-NEXT:    s_lshr_b32 s12, s24, 16
; GFX11-NEXT:    s_lshr_b32 s11, s23, 16
; GFX11-NEXT:    s_lshr_b32 s10, s22, 16
; GFX11-NEXT:    s_lshr_b32 s9, s21, 16
; GFX11-NEXT:    s_lshr_b32 s8, s20, 16
; GFX11-NEXT:    s_lshr_b32 s7, s19, 16
; GFX11-NEXT:    s_lshr_b32 s6, s18, 16
; GFX11-NEXT:    s_lshr_b32 s5, s17, 16
; GFX11-NEXT:    s_lshr_b32 s4, s16, 16
; GFX11-NEXT:    s_lshr_b32 s43, s3, 16
; GFX11-NEXT:    s_lshr_b32 s44, s2, 16
; GFX11-NEXT:    s_lshr_b32 s47, s1, 16
; GFX11-NEXT:    s_lshr_b32 s57, s0, 16
; GFX11-NEXT:    s_lshr_b32 s58, s45, 16
; GFX11-NEXT:    s_lshr_b32 s59, s46, 16
; GFX11-NEXT:    s_mov_b32 s40, 0
; GFX11-NEXT:    s_cmp_lg_u32 s56, 0
; GFX11-NEXT:    s_pack_ll_b32_b16 s0, s0, s57
; GFX11-NEXT:    s_pack_ll_b32_b16 s1, s1, s47
; GFX11-NEXT:    s_pack_ll_b32_b16 s2, s2, s44
; GFX11-NEXT:    s_pack_ll_b32_b16 s3, s3, s43
; GFX11-NEXT:    s_pack_ll_b32_b16 s4, s16, s4
; GFX11-NEXT:    s_pack_ll_b32_b16 s5, s17, s5
; GFX11-NEXT:    s_pack_ll_b32_b16 s6, s18, s6
; GFX11-NEXT:    s_pack_ll_b32_b16 s7, s19, s7
; GFX11-NEXT:    s_pack_ll_b32_b16 s8, s20, s8
; GFX11-NEXT:    s_pack_ll_b32_b16 s9, s21, s9
; GFX11-NEXT:    s_pack_ll_b32_b16 s10, s22, s10
; GFX11-NEXT:    s_pack_ll_b32_b16 s11, s23, s11
; GFX11-NEXT:    s_pack_ll_b32_b16 s12, s24, s12
; GFX11-NEXT:    s_pack_ll_b32_b16 s13, s25, s13
; GFX11-NEXT:    s_pack_ll_b32_b16 s14, s26, s14
; GFX11-NEXT:    s_pack_ll_b32_b16 s15, s27, s15
; GFX11-NEXT:    s_pack_ll_b32_b16 s16, s28, s42
; GFX11-NEXT:    s_pack_ll_b32_b16 s17, s29, s41
; GFX11-NEXT:    s_pack_ll_b32_b16 s18, s46, s59
; GFX11-NEXT:    s_pack_ll_b32_b16 s19, s45, s58
; GFX11-NEXT:    s_cbranch_scc0 .LBB55_3
; GFX11-NEXT:  ; %bb.1: ; %Flow
; GFX11-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s40
; GFX11-NEXT:    s_cbranch_vccnz .LBB55_4
; GFX11-NEXT:  .LBB55_2: ; %cmp.true
; GFX11-NEXT:    v_pk_add_f16 v0, 0x200, s0 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v1, 0x200, s1 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v2, 0x200, s2 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v3, 0x200, s3 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v4, 0x200, s4 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v5, 0x200, s5 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v6, 0x200, s6 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v7, 0x200, s7 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v8, 0x200, s8 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v9, 0x200, s9 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v10, 0x200, s10 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v11, 0x200, s11 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v12, 0x200, s12 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v13, 0x200, s13 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v14, 0x200, s14 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v15, 0x200, s15 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v16, 0x200, s16 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v17, 0x200, s17 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v18, 0x200, s18 op_sel_hi:[0,1]
; GFX11-NEXT:    v_pk_add_f16 v19, 0x200, s19 op_sel_hi:[0,1]
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    ; implicit-def: $vgpr20
; GFX11-NEXT:    s_setpc_b64 s[30:31]
; GFX11-NEXT:  .LBB55_3:
; GFX11-NEXT:    s_branch .LBB55_2
; GFX11-NEXT:  .LBB55_4:
; GFX11-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX11-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX11-NEXT:    v_dual_mov_b32 v4, s4 :: v_dual_mov_b32 v5, s5
; GFX11-NEXT:    v_dual_mov_b32 v6, s6 :: v_dual_mov_b32 v7, s7
; GFX11-NEXT:    v_dual_mov_b32 v8, s8 :: v_dual_mov_b32 v9, s9
; GFX11-NEXT:    v_dual_mov_b32 v10, s10 :: v_dual_mov_b32 v11, s11
; GFX11-NEXT:    v_dual_mov_b32 v12, s12 :: v_dual_mov_b32 v13, s13
; GFX11-NEXT:    v_dual_mov_b32 v14, s14 :: v_dual_mov_b32 v15, s15
; GFX11-NEXT:    v_dual_mov_b32 v16, s16 :: v_dual_mov_b32 v17, s17
; GFX11-NEXT:    v_dual_mov_b32 v18, s18 :: v_dual_mov_b32 v19, s19
; GFX11-NEXT:    v_dual_mov_b32 v20, s20 :: v_dual_mov_b32 v21, s21
; GFX11-NEXT:    v_dual_mov_b32 v22, s22 :: v_dual_mov_b32 v23, s23
; GFX11-NEXT:    v_dual_mov_b32 v24, s24 :: v_dual_mov_b32 v25, s25
; GFX11-NEXT:    v_dual_mov_b32 v26, s26 :: v_dual_mov_b32 v27, s27
; GFX11-NEXT:    v_dual_mov_b32 v28, s28 :: v_dual_mov_b32 v29, s29
; GFX11-NEXT:    v_dual_mov_b32 v30, s30 :: v_dual_mov_b32 v31, s31
; GFX11-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <40 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <40 x half> %a1 to <10 x double>
  br label %end

cmp.false:
  %a3 = bitcast <40 x half> %a to <10 x double>
  br label %end

end:
  %phi = phi <10 x double> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <10 x double> %phi
}

define <40 x half> @bitcast_v40i16_to_v40f16(<40 x i16> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v40i16_to_v40f16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v63, off, s[0:3], s32 ; 4-byte Folded Spill
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    v_lshrrev_b32_e32 v21, 16, v19
; SI-NEXT:    v_lshrrev_b32_e32 v25, 16, v18
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; SI-NEXT:    v_lshrrev_b32_e32 v27, 16, v16
; SI-NEXT:    v_lshrrev_b32_e32 v23, 16, v15
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v14
; SI-NEXT:    v_lshrrev_b32_e32 v24, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v32, 16, v12
; SI-NEXT:    v_lshrrev_b32_e32 v26, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; SI-NEXT:    v_lshrrev_b32_e32 v28, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v33, 16, v8
; SI-NEXT:    v_lshrrev_b32_e32 v31, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v35, 16, v6
; SI-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; SI-NEXT:    v_lshrrev_b32_e32 v36, 16, v4
; SI-NEXT:    v_lshrrev_b32_e32 v37, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v38, 16, v2
; SI-NEXT:    v_lshrrev_b32_e32 v48, 16, v1
; SI-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshlrev_b32_e32 v63, 16, v48
; SI-NEXT:    v_lshlrev_b32_e32 v60, 16, v39
; SI-NEXT:    v_lshlrev_b32_e32 v40, 16, v37
; SI-NEXT:    v_lshlrev_b32_e32 v61, 16, v38
; SI-NEXT:    v_lshlrev_b32_e32 v42, 16, v34
; SI-NEXT:    v_lshlrev_b32_e32 v62, 16, v36
; SI-NEXT:    v_lshlrev_b32_e32 v45, 16, v31
; SI-NEXT:    v_lshlrev_b32_e32 v54, 16, v35
; SI-NEXT:    v_lshlrev_b32_e32 v46, 16, v28
; SI-NEXT:    v_lshlrev_b32_e32 v41, 16, v33
; SI-NEXT:    v_lshlrev_b32_e32 v57, 16, v26
; SI-NEXT:    v_lshlrev_b32_e32 v44, 16, v29
; SI-NEXT:    v_lshlrev_b32_e32 v29, 16, v24
; SI-NEXT:    v_lshlrev_b32_e32 v47, 16, v32
; SI-NEXT:    v_lshlrev_b32_e32 v35, 16, v23
; SI-NEXT:    v_lshlrev_b32_e32 v58, 16, v30
; SI-NEXT:    v_lshlrev_b32_e32 v50, 16, v22
; SI-NEXT:    v_lshlrev_b32_e32 v32, 16, v27
; SI-NEXT:    v_lshlrev_b32_e32 v52, 16, v21
; SI-NEXT:    v_lshlrev_b32_e32 v39, 16, v25
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr59
; SI-NEXT:    ; implicit-def: $vgpr53
; SI-NEXT:    ; implicit-def: $vgpr56
; SI-NEXT:    ; implicit-def: $vgpr51
; SI-NEXT:    ; implicit-def: $vgpr43
; SI-NEXT:    ; implicit-def: $vgpr49
; SI-NEXT:    ; implicit-def: $vgpr55
; SI-NEXT:    ; implicit-def: $vgpr38
; SI-NEXT:    ; implicit-def: $vgpr36
; SI-NEXT:    ; implicit-def: $vgpr33
; SI-NEXT:    ; implicit-def: $vgpr30
; SI-NEXT:    ; implicit-def: $vgpr27
; SI-NEXT:    ; implicit-def: $vgpr25
; SI-NEXT:    ; kill: killed $vgpr20
; SI-NEXT:    ; implicit-def: $vgpr20
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB56_2
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_or_b32_e32 v53, v1, v63
; SI-NEXT:    v_alignbit_b32 v1, v53, v60, 16
; SI-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:88 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v3
; SI-NEXT:    v_or_b32_e32 v51, v1, v40
; SI-NEXT:    v_alignbit_b32 v1, v51, v61, 16
; SI-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:92 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v5
; SI-NEXT:    v_or_b32_e32 v49, v1, v42
; SI-NEXT:    v_alignbit_b32 v1, v49, v62, 16
; SI-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:96 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v7
; SI-NEXT:    v_or_b32_e32 v38, v1, v45
; SI-NEXT:    v_alignbit_b32 v1, v38, v54, 16
; SI-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:100 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v9
; SI-NEXT:    v_or_b32_e32 v36, v1, v46
; SI-NEXT:    v_alignbit_b32 v1, v36, v41, 16
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:104 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v11
; SI-NEXT:    v_or_b32_e32 v59, v0, v60
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v2
; SI-NEXT:    v_or_b32_e32 v33, v1, v57
; SI-NEXT:    v_or_b32_e32 v56, v0, v61
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v4
; SI-NEXT:    v_alignbit_b32 v1, v33, v44, 16
; SI-NEXT:    v_or_b32_e32 v43, v0, v62
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v6
; SI-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:108 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v13
; SI-NEXT:    v_or_b32_e32 v55, v0, v54
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v8
; SI-NEXT:    v_or_b32_e32 v30, v1, v29
; SI-NEXT:    v_or_b32_e32 v0, v0, v41
; SI-NEXT:    v_alignbit_b32 v1, v30, v47, 16
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:84 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v10
; SI-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:112 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v15
; SI-NEXT:    v_or_b32_e32 v0, v0, v44
; SI-NEXT:    v_or_b32_e32 v27, v1, v35
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:80 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v12
; SI-NEXT:    v_alignbit_b32 v1, v27, v58, 16
; SI-NEXT:    v_or_b32_e32 v0, v0, v47
; SI-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:116 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v17
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:76 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v14
; SI-NEXT:    v_or_b32_e32 v25, v1, v50
; SI-NEXT:    v_or_b32_e32 v0, v0, v58
; SI-NEXT:    v_alignbit_b32 v1, v25, v32, 16
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:72 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v16
; SI-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:120 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v19
; SI-NEXT:    v_or_b32_e32 v0, v0, v32
; SI-NEXT:    v_or_b32_e32 v20, v1, v52
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:68 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v18
; SI-NEXT:    v_alignbit_b32 v1, v20, v39, 16
; SI-NEXT:    v_or_b32_e32 v0, v0, v39
; SI-NEXT:    buffer_store_dword v1, off, s[0:3], s32 offset:124 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:64 ; 4-byte Folded Spill
; SI-NEXT:    ; implicit-def: $vgpr0
; SI-NEXT:    ; implicit-def: $vgpr1
; SI-NEXT:    ; implicit-def: $vgpr2
; SI-NEXT:    ; implicit-def: $vgpr3
; SI-NEXT:    ; implicit-def: $vgpr4
; SI-NEXT:    ; implicit-def: $vgpr5
; SI-NEXT:    ; implicit-def: $vgpr6
; SI-NEXT:    ; implicit-def: $vgpr7
; SI-NEXT:    ; implicit-def: $vgpr8
; SI-NEXT:    ; implicit-def: $vgpr9
; SI-NEXT:    ; implicit-def: $vgpr10
; SI-NEXT:    ; implicit-def: $vgpr11
; SI-NEXT:    ; implicit-def: $vgpr12
; SI-NEXT:    ; implicit-def: $vgpr13
; SI-NEXT:    ; implicit-def: $vgpr14
; SI-NEXT:    ; implicit-def: $vgpr15
; SI-NEXT:    ; implicit-def: $vgpr16
; SI-NEXT:    ; implicit-def: $vgpr17
; SI-NEXT:    ; implicit-def: $vgpr18
; SI-NEXT:    ; implicit-def: $vgpr19
; SI-NEXT:    ; implicit-def: $vgpr63
; SI-NEXT:    ; implicit-def: $vgpr60
; SI-NEXT:    ; implicit-def: $vgpr40
; SI-NEXT:    ; implicit-def: $vgpr61
; SI-NEXT:    ; implicit-def: $vgpr42
; SI-NEXT:    ; implicit-def: $vgpr62
; SI-NEXT:    ; implicit-def: $vgpr45
; SI-NEXT:    ; implicit-def: $vgpr54
; SI-NEXT:    ; implicit-def: $vgpr46
; SI-NEXT:    ; implicit-def: $vgpr41
; SI-NEXT:    ; implicit-def: $vgpr57
; SI-NEXT:    ; implicit-def: $vgpr44
; SI-NEXT:    ; implicit-def: $vgpr29
; SI-NEXT:    ; implicit-def: $vgpr47
; SI-NEXT:    ; implicit-def: $vgpr35
; SI-NEXT:    ; implicit-def: $vgpr58
; SI-NEXT:    ; implicit-def: $vgpr50
; SI-NEXT:    ; implicit-def: $vgpr32
; SI-NEXT:    ; implicit-def: $vgpr52
; SI-NEXT:    ; implicit-def: $vgpr39
; SI-NEXT:  .LBB56_2: ; %Flow
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB56_4
; SI-NEXT:  ; %bb.3: ; %cmp.true
; SI-NEXT:    v_add_i32_e32 v18, vcc, 3, v18
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; SI-NEXT:    v_or_b32_e32 v18, v39, v18
; SI-NEXT:    v_add_i32_e32 v21, vcc, 0x30000, v18
; SI-NEXT:    v_add_i32_e32 v18, vcc, 3, v19
; SI-NEXT:    v_add_i32_e32 v16, vcc, 3, v16
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v16
; SI-NEXT:    s_mov_b32 s6, 0x30000
; SI-NEXT:    v_or_b32_e32 v18, v52, v18
; SI-NEXT:    v_or_b32_e32 v16, v32, v16
; SI-NEXT:    v_add_i32_e32 v20, vcc, s6, v18
; SI-NEXT:    v_add_i32_e32 v18, vcc, s6, v16
; SI-NEXT:    v_add_i32_e32 v16, vcc, 3, v17
; SI-NEXT:    v_add_i32_e32 v14, vcc, 3, v14
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v16
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; SI-NEXT:    v_or_b32_e32 v16, v50, v16
; SI-NEXT:    v_or_b32_e32 v14, v58, v14
; SI-NEXT:    v_add_i32_e32 v25, vcc, s6, v16
; SI-NEXT:    v_add_i32_e32 v16, vcc, s6, v14
; SI-NEXT:    v_add_i32_e32 v14, vcc, 3, v15
; SI-NEXT:    v_add_i32_e32 v12, vcc, 3, v12
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; SI-NEXT:    v_or_b32_e32 v14, v35, v14
; SI-NEXT:    v_or_b32_e32 v12, v47, v12
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v0
; SI-NEXT:    v_add_i32_e32 v27, vcc, s6, v14
; SI-NEXT:    v_add_i32_e32 v14, vcc, s6, v12
; SI-NEXT:    v_add_i32_e32 v12, vcc, 3, v13
; SI-NEXT:    v_add_i32_e32 v10, vcc, 3, v10
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v2
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v4
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_or_b32_e32 v0, v60, v0
; SI-NEXT:    v_or_b32_e32 v12, v29, v12
; SI-NEXT:    v_or_b32_e32 v10, v44, v10
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v6
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_or_b32_e32 v2, v61, v2
; SI-NEXT:    v_add_i32_e32 v59, vcc, s6, v0
; SI-NEXT:    v_add_i32_e32 v0, vcc, 3, v1
; SI-NEXT:    v_add_i32_e32 v30, vcc, s6, v12
; SI-NEXT:    v_add_i32_e32 v12, vcc, s6, v10
; SI-NEXT:    v_add_i32_e32 v10, vcc, 3, v11
; SI-NEXT:    v_add_i32_e32 v8, vcc, 3, v8
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_or_b32_e32 v4, v62, v4
; SI-NEXT:    v_add_i32_e32 v56, vcc, s6, v2
; SI-NEXT:    v_add_i32_e32 v2, vcc, 3, v3
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; SI-NEXT:    v_or_b32_e32 v6, v54, v6
; SI-NEXT:    v_add_i32_e32 v43, vcc, s6, v4
; SI-NEXT:    v_add_i32_e32 v4, vcc, 3, v5
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_or_b32_e32 v0, v63, v0
; SI-NEXT:    v_or_b32_e32 v10, v57, v10
; SI-NEXT:    v_or_b32_e32 v8, v41, v8
; SI-NEXT:    v_add_i32_e32 v55, vcc, s6, v6
; SI-NEXT:    v_add_i32_e32 v6, vcc, 3, v7
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_or_b32_e32 v2, v40, v2
; SI-NEXT:    v_add_i32_e32 v53, vcc, s6, v0
; SI-NEXT:    v_add_i32_e32 v33, vcc, s6, v10
; SI-NEXT:    v_add_i32_e32 v10, vcc, s6, v8
; SI-NEXT:    v_add_i32_e32 v8, vcc, 3, v9
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_or_b32_e32 v4, v42, v4
; SI-NEXT:    v_add_i32_e32 v51, vcc, s6, v2
; SI-NEXT:    v_alignbit_b32 v0, v53, v59, 16
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; SI-NEXT:    v_or_b32_e32 v6, v45, v6
; SI-NEXT:    v_add_i32_e32 v49, vcc, s6, v4
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:88 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_alignbit_b32 v0, v51, v56, 16
; SI-NEXT:    v_or_b32_e32 v8, v46, v8
; SI-NEXT:    v_add_i32_e32 v38, vcc, s6, v6
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:92 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_alignbit_b32 v0, v49, v43, 16
; SI-NEXT:    v_add_i32_e32 v36, vcc, s6, v8
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:96 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_alignbit_b32 v0, v38, v55, 16
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:100 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v10, off, s[0:3], s32 offset:84 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(1)
; SI-NEXT:    v_alignbit_b32 v0, v36, v10, 16
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:104 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v12, off, s[0:3], s32 offset:80 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(1)
; SI-NEXT:    v_alignbit_b32 v0, v33, v12, 16
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:108 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v14, off, s[0:3], s32 offset:76 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(1)
; SI-NEXT:    v_alignbit_b32 v0, v30, v14, 16
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:112 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v16, off, s[0:3], s32 offset:72 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(1)
; SI-NEXT:    v_alignbit_b32 v0, v27, v16, 16
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:116 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v18, off, s[0:3], s32 offset:68 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(1)
; SI-NEXT:    v_alignbit_b32 v0, v25, v18, 16
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:120 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v21, off, s[0:3], s32 offset:64 ; 4-byte Folded Spill
; SI-NEXT:    s_waitcnt expcnt(1)
; SI-NEXT:    v_alignbit_b32 v0, v20, v21, 16
; SI-NEXT:    v_lshrrev_b32_e32 v48, 16, v53
; SI-NEXT:    v_lshrrev_b32_e32 v37, 16, v51
; SI-NEXT:    v_lshrrev_b32_e32 v34, 16, v49
; SI-NEXT:    v_lshrrev_b32_e32 v31, 16, v38
; SI-NEXT:    v_lshrrev_b32_e32 v28, 16, v36
; SI-NEXT:    v_lshrrev_b32_e32 v26, 16, v33
; SI-NEXT:    v_lshrrev_b32_e32 v24, 16, v30
; SI-NEXT:    v_lshrrev_b32_e32 v23, 16, v27
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v25
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v21, 16, v20
; SI-NEXT:    buffer_store_dword v0, off, s[0:3], s32 offset:124 ; 4-byte Folded Spill
; SI-NEXT:  .LBB56_4: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    s_waitcnt expcnt(1)
; SI-NEXT:    buffer_load_dword v1, off, s[0:3], s32 offset:88 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v3, off, s[0:3], s32 offset:92 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v5, off, s[0:3], s32 offset:96 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v7, off, s[0:3], s32 offset:100 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v59
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v48
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v37
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v34
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v31
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v28
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v26
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v24
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v23
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v22
; SI-NEXT:    buffer_load_dword v9, off, s[0:3], s32 offset:104 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v11, off, s[0:3], s32 offset:108 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v13, off, s[0:3], s32 offset:112 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v15, off, s[0:3], s32 offset:116 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v17, off, s[0:3], s32 offset:120 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v19, off, s[0:3], s32 offset:124 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(9)
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v1
; SI-NEXT:    v_or_b32_e32 v0, v0, v1
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v53
; SI-NEXT:    v_or_b32_e32 v1, v1, v2
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v56
; SI-NEXT:    s_waitcnt vmcnt(8)
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v3
; SI-NEXT:    v_or_b32_e32 v2, v2, v3
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v51
; SI-NEXT:    v_or_b32_e32 v3, v3, v4
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v43
; SI-NEXT:    s_waitcnt vmcnt(7)
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v5
; SI-NEXT:    v_or_b32_e32 v4, v4, v5
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v49
; SI-NEXT:    v_or_b32_e32 v5, v5, v6
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v55
; SI-NEXT:    s_waitcnt vmcnt(6)
; SI-NEXT:    v_lshlrev_b32_e32 v7, 16, v7
; SI-NEXT:    v_or_b32_e32 v6, v6, v7
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v38
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    buffer_load_dword v8, off, s[0:3], s32 offset:84 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(6)
; SI-NEXT:    v_lshlrev_b32_e32 v9, 16, v9
; SI-NEXT:    s_waitcnt vmcnt(5)
; SI-NEXT:    v_lshlrev_b32_e32 v11, 16, v11
; SI-NEXT:    s_waitcnt vmcnt(4)
; SI-NEXT:    v_lshlrev_b32_e32 v13, 16, v13
; SI-NEXT:    s_waitcnt vmcnt(3)
; SI-NEXT:    v_lshlrev_b32_e32 v15, 16, v15
; SI-NEXT:    buffer_load_dword v63, off, s[0:3], s32 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v62, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v61, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v60, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v59, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v57, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:40 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:44 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:48 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:52 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:56 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:60 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(14)
; SI-NEXT:    v_lshlrev_b32_e32 v17, 16, v17
; SI-NEXT:    v_lshlrev_b32_e32 v19, 16, v19
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; SI-NEXT:    v_or_b32_e32 v8, v8, v9
; SI-NEXT:    v_and_b32_e32 v9, 0xffff, v36
; SI-NEXT:    v_or_b32_e32 v9, v9, v10
; SI-NEXT:    buffer_load_dword v10, off, s[0:3], s32 offset:80 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; SI-NEXT:    v_or_b32_e32 v10, v10, v11
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v33
; SI-NEXT:    v_or_b32_e32 v11, v11, v12
; SI-NEXT:    buffer_load_dword v12, off, s[0:3], s32 offset:76 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; SI-NEXT:    v_or_b32_e32 v12, v12, v13
; SI-NEXT:    v_and_b32_e32 v13, 0xffff, v30
; SI-NEXT:    v_or_b32_e32 v13, v13, v14
; SI-NEXT:    buffer_load_dword v14, off, s[0:3], s32 offset:72 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; SI-NEXT:    v_or_b32_e32 v14, v14, v15
; SI-NEXT:    v_and_b32_e32 v15, 0xffff, v27
; SI-NEXT:    v_or_b32_e32 v15, v15, v16
; SI-NEXT:    buffer_load_dword v16, off, s[0:3], s32 offset:68 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v16
; SI-NEXT:    v_or_b32_e32 v16, v16, v17
; SI-NEXT:    v_and_b32_e32 v17, 0xffff, v25
; SI-NEXT:    v_or_b32_e32 v17, v17, v18
; SI-NEXT:    buffer_load_dword v18, off, s[0:3], s32 offset:64 ; 4-byte Folded Reload
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; SI-NEXT:    v_or_b32_e32 v18, v18, v19
; SI-NEXT:    v_and_b32_e32 v19, 0xffff, v20
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v21
; SI-NEXT:    v_or_b32_e32 v19, v19, v20
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v40i16_to_v40f16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_lshrrev_b32_e32 v21, 16, v19
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v18
; VI-NEXT:    v_lshrrev_b32_e32 v23, 16, v17
; VI-NEXT:    v_lshrrev_b32_e32 v24, 16, v16
; VI-NEXT:    v_lshrrev_b32_e32 v25, 16, v15
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v14
; VI-NEXT:    v_lshrrev_b32_e32 v27, 16, v13
; VI-NEXT:    v_lshrrev_b32_e32 v28, 16, v12
; VI-NEXT:    v_lshrrev_b32_e32 v29, 16, v11
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v10
; VI-NEXT:    v_lshrrev_b32_e32 v31, 16, v9
; VI-NEXT:    v_lshrrev_b32_e32 v32, 16, v8
; VI-NEXT:    v_lshrrev_b32_e32 v33, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v34, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v35, 16, v5
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    v_lshrrev_b32_e32 v20, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB56_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_u16_e32 v0, 3, v0
; VI-NEXT:    v_add_u16_e32 v39, 3, v39
; VI-NEXT:    v_add_u16_e32 v1, 3, v1
; VI-NEXT:    v_add_u16_e32 v38, 3, v38
; VI-NEXT:    v_add_u16_e32 v2, 3, v2
; VI-NEXT:    v_add_u16_e32 v37, 3, v37
; VI-NEXT:    v_add_u16_e32 v3, 3, v3
; VI-NEXT:    v_add_u16_e32 v36, 3, v36
; VI-NEXT:    v_add_u16_e32 v4, 3, v4
; VI-NEXT:    v_add_u16_e32 v20, 3, v20
; VI-NEXT:    v_add_u16_e32 v5, 3, v5
; VI-NEXT:    v_add_u16_e32 v35, 3, v35
; VI-NEXT:    v_add_u16_e32 v6, 3, v6
; VI-NEXT:    v_add_u16_e32 v34, 3, v34
; VI-NEXT:    v_add_u16_e32 v7, 3, v7
; VI-NEXT:    v_add_u16_e32 v33, 3, v33
; VI-NEXT:    v_add_u16_e32 v8, 3, v8
; VI-NEXT:    v_add_u16_e32 v32, 3, v32
; VI-NEXT:    v_add_u16_e32 v9, 3, v9
; VI-NEXT:    v_add_u16_e32 v31, 3, v31
; VI-NEXT:    v_add_u16_e32 v10, 3, v10
; VI-NEXT:    v_add_u16_e32 v30, 3, v30
; VI-NEXT:    v_add_u16_e32 v11, 3, v11
; VI-NEXT:    v_add_u16_e32 v29, 3, v29
; VI-NEXT:    v_add_u16_e32 v12, 3, v12
; VI-NEXT:    v_add_u16_e32 v28, 3, v28
; VI-NEXT:    v_add_u16_e32 v13, 3, v13
; VI-NEXT:    v_add_u16_e32 v27, 3, v27
; VI-NEXT:    v_add_u16_e32 v14, 3, v14
; VI-NEXT:    v_add_u16_e32 v26, 3, v26
; VI-NEXT:    v_add_u16_e32 v15, 3, v15
; VI-NEXT:    v_add_u16_e32 v25, 3, v25
; VI-NEXT:    v_add_u16_e32 v16, 3, v16
; VI-NEXT:    v_add_u16_e32 v24, 3, v24
; VI-NEXT:    v_add_u16_e32 v17, 3, v17
; VI-NEXT:    v_add_u16_e32 v23, 3, v23
; VI-NEXT:    v_add_u16_e32 v18, 3, v18
; VI-NEXT:    v_add_u16_e32 v22, 3, v22
; VI-NEXT:    v_add_u16_e32 v19, 3, v19
; VI-NEXT:    v_add_u16_e32 v21, 3, v21
; VI-NEXT:  .LBB56_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; VI-NEXT:    v_or_b32_sdwa v4, v4, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v35
; VI-NEXT:    v_or_b32_sdwa v5, v5, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v34
; VI-NEXT:    v_or_b32_sdwa v6, v6, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v33
; VI-NEXT:    v_or_b32_sdwa v7, v7, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v32
; VI-NEXT:    v_or_b32_sdwa v8, v8, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v31
; VI-NEXT:    v_or_b32_sdwa v9, v9, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v30
; VI-NEXT:    v_or_b32_sdwa v10, v10, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v29
; VI-NEXT:    v_or_b32_sdwa v11, v11, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v28
; VI-NEXT:    v_or_b32_sdwa v12, v12, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v27
; VI-NEXT:    v_or_b32_sdwa v13, v13, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v26
; VI-NEXT:    v_or_b32_sdwa v14, v14, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v25
; VI-NEXT:    v_or_b32_sdwa v15, v15, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v24
; VI-NEXT:    v_or_b32_sdwa v16, v16, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v23
; VI-NEXT:    v_or_b32_sdwa v17, v17, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v22
; VI-NEXT:    v_lshlrev_b32_e32 v39, 16, v39
; VI-NEXT:    v_lshlrev_b32_e32 v38, 16, v38
; VI-NEXT:    v_lshlrev_b32_e32 v37, 16, v37
; VI-NEXT:    v_lshlrev_b32_e32 v36, 16, v36
; VI-NEXT:    v_or_b32_sdwa v18, v18, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v21
; VI-NEXT:    v_or_b32_sdwa v0, v0, v39 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v1, v1, v38 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v2, v2, v37 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v3, v3, v36 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v19, v19, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v40i16_to_v40f16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_lshrrev_b32_e32 v39, 16, v19
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 16, v18
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v15
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v14
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v13
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 16, v11
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v28, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v27, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v24, 16, v5
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v2
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v20, 16, v0
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB56_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    s_mov_b32 s6, 0x5040100
; GFX9-NEXT:    v_perm_b32 v19, v39, v19, s6
; GFX9-NEXT:    v_perm_b32 v18, v38, v18, s6
; GFX9-NEXT:    v_perm_b32 v17, v37, v17, s6
; GFX9-NEXT:    v_perm_b32 v16, v36, v16, s6
; GFX9-NEXT:    v_perm_b32 v15, v35, v15, s6
; GFX9-NEXT:    v_perm_b32 v14, v34, v14, s6
; GFX9-NEXT:    v_perm_b32 v13, v33, v13, s6
; GFX9-NEXT:    v_perm_b32 v12, v32, v12, s6
; GFX9-NEXT:    v_perm_b32 v11, v31, v11, s6
; GFX9-NEXT:    v_perm_b32 v10, v30, v10, s6
; GFX9-NEXT:    v_perm_b32 v9, v29, v9, s6
; GFX9-NEXT:    v_perm_b32 v8, v28, v8, s6
; GFX9-NEXT:    v_perm_b32 v7, v27, v7, s6
; GFX9-NEXT:    v_perm_b32 v6, v26, v6, s6
; GFX9-NEXT:    v_perm_b32 v5, v24, v5, s6
; GFX9-NEXT:    v_perm_b32 v4, v25, v4, s6
; GFX9-NEXT:    v_perm_b32 v3, v23, v3, s6
; GFX9-NEXT:    v_perm_b32 v2, v22, v2, s6
; GFX9-NEXT:    v_perm_b32 v1, v21, v1, s6
; GFX9-NEXT:    v_perm_b32 v0, v20, v0, s6
; GFX9-NEXT:    v_pk_add_u16 v19, v19, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v18, v18, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v17, v17, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v16, v16, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v15, v15, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v14, v14, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v13, v13, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v12, v12, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v9, v9, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v8, v8, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_lshrrev_b32_e32 v20, 16, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v2
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v24, 16, v5
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v27, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v28, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 16, v11
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v13
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v14
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v15
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 16, v18
; GFX9-NEXT:    v_lshrrev_b32_e32 v39, 16, v19
; GFX9-NEXT:  .LBB56_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_mov_b32 s4, 0x5040100
; GFX9-NEXT:    v_perm_b32 v0, v20, v0, s4
; GFX9-NEXT:    v_perm_b32 v1, v21, v1, s4
; GFX9-NEXT:    v_perm_b32 v2, v22, v2, s4
; GFX9-NEXT:    v_perm_b32 v3, v23, v3, s4
; GFX9-NEXT:    v_perm_b32 v4, v25, v4, s4
; GFX9-NEXT:    v_perm_b32 v5, v24, v5, s4
; GFX9-NEXT:    v_perm_b32 v6, v26, v6, s4
; GFX9-NEXT:    v_perm_b32 v7, v27, v7, s4
; GFX9-NEXT:    v_perm_b32 v8, v28, v8, s4
; GFX9-NEXT:    v_perm_b32 v9, v29, v9, s4
; GFX9-NEXT:    v_perm_b32 v10, v30, v10, s4
; GFX9-NEXT:    v_perm_b32 v11, v31, v11, s4
; GFX9-NEXT:    v_perm_b32 v12, v32, v12, s4
; GFX9-NEXT:    v_perm_b32 v13, v33, v13, s4
; GFX9-NEXT:    v_perm_b32 v14, v34, v14, s4
; GFX9-NEXT:    v_perm_b32 v15, v35, v15, s4
; GFX9-NEXT:    v_perm_b32 v16, v36, v16, s4
; GFX9-NEXT:    v_perm_b32 v17, v37, v17, s4
; GFX9-NEXT:    v_perm_b32 v18, v38, v18, s4
; GFX9-NEXT:    v_perm_b32 v19, v39, v19, s4
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v40i16_to_v40f16:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB56_2
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v19, v19, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v18, v18, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v17, v17, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v16, v16, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v15, v15, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v14, v14, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v13, v13, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v12, v12, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v9, v9, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v8, v8, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:  .LBB56_2: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v40i16_to_v40f16:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v48, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v3
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v0
; GFX11-FAKE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-FAKE16-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB56_2
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_perm_b32 v19, v48, v19, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v18, v39, v18, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v17, v38, v17, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v16, v37, v16, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v15, v36, v15, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v14, v35, v14, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, v34, v13, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, v33, v12, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, v32, v11, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, v31, v10, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, v30, v9, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, v29, v8, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v28, v7, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v27, v6, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v26, v5, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v21, v0, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v22, v1, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v23, v2, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v24, v3, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v25, v4, 0x5040100
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v19, v19, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v18, v18, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v17, v17, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v16, v16, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v15, v15, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v14, v14, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v13, v13, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v12, v12, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v11, v11, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v10, v10, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v9, v9, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v8, v8, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v7, v7, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v6, v6, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v5, v5, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v0, v0, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v1, v1, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v2, v2, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v3, v3, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v4, v4, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v3
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v48, 16, v19
; GFX11-FAKE16-NEXT:  .LBB56_2: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v21, v0, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v22, v1, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v23, v2, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v24, v3, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v25, v4, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v26, v5, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v27, v6, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v28, v7, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, v29, v8, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, v30, v9, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, v31, v10, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, v32, v11, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, v33, v12, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, v34, v13, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v14, v35, v14, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v15, v36, v15, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v16, v37, v16, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v17, v38, v17, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v18, v39, v18, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v19, v48, v19, 0x5040100
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <40 x i16> %a, splat (i16 3)
  %a2 = bitcast <40 x i16> %a1 to <40 x half>
  br label %end

cmp.false:
  %a3 = bitcast <40 x i16> %a to <40 x half>
  br label %end

end:
  %phi = phi <40 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <40 x half> %phi
}

define inreg <40 x half> @bitcast_v40i16_to_v40f16_scalar(<40 x i16> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v40i16_to_v40f16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_store_dword v20, off, s[0:3], s32 ; 4-byte Folded Spill
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_writelane_b32 v20, s34, 0
; SI-NEXT:    v_writelane_b32 v20, s35, 1
; SI-NEXT:    v_writelane_b32 v20, s36, 2
; SI-NEXT:    v_writelane_b32 v20, s37, 3
; SI-NEXT:    v_writelane_b32 v20, s38, 4
; SI-NEXT:    v_writelane_b32 v20, s39, 5
; SI-NEXT:    v_writelane_b32 v20, s48, 6
; SI-NEXT:    v_writelane_b32 v20, s49, 7
; SI-NEXT:    v_writelane_b32 v20, s50, 8
; SI-NEXT:    v_writelane_b32 v20, s51, 9
; SI-NEXT:    v_writelane_b32 v20, s52, 10
; SI-NEXT:    v_writelane_b32 v20, s53, 11
; SI-NEXT:    v_writelane_b32 v20, s54, 12
; SI-NEXT:    v_writelane_b32 v20, s55, 13
; SI-NEXT:    v_writelane_b32 v20, s64, 14
; SI-NEXT:    v_writelane_b32 v20, s65, 15
; SI-NEXT:    v_writelane_b32 v20, s66, 16
; SI-NEXT:    v_writelane_b32 v20, s67, 17
; SI-NEXT:    v_writelane_b32 v20, s68, 18
; SI-NEXT:    v_writelane_b32 v20, s69, 19
; SI-NEXT:    v_writelane_b32 v20, s70, 20
; SI-NEXT:    v_writelane_b32 v20, s71, 21
; SI-NEXT:    v_writelane_b32 v20, s30, 22
; SI-NEXT:    v_writelane_b32 v20, s31, 23
; SI-NEXT:    v_readfirstlane_b32 s69, v5
; SI-NEXT:    v_readfirstlane_b32 s71, v4
; SI-NEXT:    v_readfirstlane_b32 s66, v3
; SI-NEXT:    v_readfirstlane_b32 s68, v2
; SI-NEXT:    v_readfirstlane_b32 s55, v1
; SI-NEXT:    v_readfirstlane_b32 s65, v0
; SI-NEXT:    s_lshr_b32 s36, s29, 16
; SI-NEXT:    s_lshr_b32 s54, s28, 16
; SI-NEXT:    s_lshr_b32 s35, s27, 16
; SI-NEXT:    s_lshr_b32 s53, s26, 16
; SI-NEXT:    s_lshr_b32 s34, s25, 16
; SI-NEXT:    s_lshr_b32 s52, s24, 16
; SI-NEXT:    s_lshr_b32 s31, s23, 16
; SI-NEXT:    s_lshr_b32 s51, s22, 16
; SI-NEXT:    s_lshr_b32 s30, s21, 16
; SI-NEXT:    s_lshr_b32 s50, s20, 16
; SI-NEXT:    s_lshr_b32 s95, s19, 16
; SI-NEXT:    s_lshr_b32 s49, s18, 16
; SI-NEXT:    s_lshr_b32 s94, s17, 16
; SI-NEXT:    s_lshr_b32 s48, s16, 16
; SI-NEXT:    s_lshr_b32 s39, s69, 16
; SI-NEXT:    s_lshr_b32 s70, s71, 16
; SI-NEXT:    s_lshr_b32 s38, s66, 16
; SI-NEXT:    s_lshr_b32 s67, s68, 16
; SI-NEXT:    s_lshr_b32 s37, s55, 16
; SI-NEXT:    s_lshr_b32 s64, s65, 16
; SI-NEXT:    v_readfirstlane_b32 s4, v6
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    s_cbranch_scc0 .LBB57_4
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_and_b32 s5, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s94, 16
; SI-NEXT:    s_or_b32 s47, s5, s7
; SI-NEXT:    s_and_b32 s5, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s95, 16
; SI-NEXT:    s_or_b32 s43, s5, s7
; SI-NEXT:    s_and_b32 s5, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s30, 16
; SI-NEXT:    s_or_b32 s41, s5, s7
; SI-NEXT:    s_and_b32 s5, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s31, 16
; SI-NEXT:    s_or_b32 s15, s5, s7
; SI-NEXT:    s_and_b32 s5, s25, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s34, 16
; SI-NEXT:    s_or_b32 s13, s5, s7
; SI-NEXT:    s_and_b32 s5, s27, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s35, 16
; SI-NEXT:    s_or_b32 s11, s5, s7
; SI-NEXT:    s_and_b32 s5, s29, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s36, 16
; SI-NEXT:    s_or_b32 s9, s5, s7
; SI-NEXT:    s_and_b32 s5, s55, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s37, 16
; SI-NEXT:    s_or_b32 s7, s5, s7
; SI-NEXT:    s_and_b32 s5, s66, 0xffff
; SI-NEXT:    s_lshl_b32 s45, s38, 16
; SI-NEXT:    s_and_b32 s44, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s46, s48, 16
; SI-NEXT:    s_or_b32 s5, s5, s45
; SI-NEXT:    s_and_b32 s45, s69, 0xffff
; SI-NEXT:    s_lshl_b32 s56, s39, 16
; SI-NEXT:    s_lshl_b32 s42, s49, 16
; SI-NEXT:    s_or_b32 s91, s45, s56
; SI-NEXT:    s_or_b32 s44, s44, s46
; SI-NEXT:    s_lshr_b64 s[56:57], s[46:47], 16
; SI-NEXT:    s_and_b32 s46, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s40, s50, 16
; SI-NEXT:    s_or_b32 s46, s46, s42
; SI-NEXT:    s_lshr_b64 s[58:59], s[42:43], 16
; SI-NEXT:    s_and_b32 s42, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s14, s51, 16
; SI-NEXT:    s_or_b32 s42, s42, s40
; SI-NEXT:    s_lshr_b64 s[60:61], s[40:41], 16
; SI-NEXT:    s_and_b32 s40, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s52, 16
; SI-NEXT:    s_or_b32 s40, s40, s14
; SI-NEXT:    s_lshr_b64 s[62:63], s[14:15], 16
; SI-NEXT:    s_and_b32 s14, s24, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s53, 16
; SI-NEXT:    s_or_b32 s14, s14, s12
; SI-NEXT:    s_lshr_b64 s[72:73], s[12:13], 16
; SI-NEXT:    s_and_b32 s12, s26, 0xffff
; SI-NEXT:    s_lshl_b32 s8, s54, 16
; SI-NEXT:    s_or_b32 s12, s12, s10
; SI-NEXT:    s_lshr_b64 s[74:75], s[10:11], 16
; SI-NEXT:    s_and_b32 s10, s28, 0xffff
; SI-NEXT:    s_lshl_b32 s6, s64, 16
; SI-NEXT:    s_or_b32 s10, s10, s8
; SI-NEXT:    s_lshr_b64 s[76:77], s[8:9], 16
; SI-NEXT:    s_and_b32 s8, s65, 0xffff
; SI-NEXT:    s_lshl_b32 s4, s67, 16
; SI-NEXT:    s_or_b32 s8, s8, s6
; SI-NEXT:    s_lshr_b64 s[78:79], s[6:7], 16
; SI-NEXT:    s_and_b32 s6, s68, 0xffff
; SI-NEXT:    s_lshl_b32 s90, s70, 16
; SI-NEXT:    s_or_b32 s6, s6, s4
; SI-NEXT:    s_lshr_b64 s[88:89], s[4:5], 16
; SI-NEXT:    s_and_b32 s4, s71, 0xffff
; SI-NEXT:    s_mov_b32 s45, s47
; SI-NEXT:    s_mov_b32 s47, s43
; SI-NEXT:    s_mov_b32 s43, s41
; SI-NEXT:    s_mov_b32 s41, s15
; SI-NEXT:    s_mov_b32 s15, s13
; SI-NEXT:    s_mov_b32 s13, s11
; SI-NEXT:    s_mov_b32 s11, s9
; SI-NEXT:    s_mov_b32 s9, s7
; SI-NEXT:    s_mov_b32 s7, s5
; SI-NEXT:    s_or_b32 s4, s4, s90
; SI-NEXT:    s_mov_b32 s5, s91
; SI-NEXT:    s_lshr_b64 s[90:91], s[90:91], 16
; SI-NEXT:    s_cbranch_execnz .LBB57_3
; SI-NEXT:  .LBB57_2: ; %cmp.true
; SI-NEXT:    s_add_i32 s71, s71, 3
; SI-NEXT:    s_and_b32 s4, s71, 0xffff
; SI-NEXT:    s_lshl_b32 s5, s70, 16
; SI-NEXT:    s_add_i32 s69, s69, 3
; SI-NEXT:    s_or_b32 s4, s5, s4
; SI-NEXT:    s_and_b32 s5, s69, 0xffff
; SI-NEXT:    s_lshl_b32 s6, s39, 16
; SI-NEXT:    s_add_i32 s68, s68, 3
; SI-NEXT:    s_or_b32 s5, s6, s5
; SI-NEXT:    s_and_b32 s6, s68, 0xffff
; SI-NEXT:    s_lshl_b32 s7, s67, 16
; SI-NEXT:    s_add_i32 s66, s66, 3
; SI-NEXT:    s_or_b32 s6, s7, s6
; SI-NEXT:    s_and_b32 s7, s66, 0xffff
; SI-NEXT:    s_lshl_b32 s8, s38, 16
; SI-NEXT:    s_add_i32 s65, s65, 3
; SI-NEXT:    s_or_b32 s7, s8, s7
; SI-NEXT:    s_and_b32 s8, s65, 0xffff
; SI-NEXT:    s_lshl_b32 s9, s64, 16
; SI-NEXT:    s_add_i32 s55, s55, 3
; SI-NEXT:    s_or_b32 s8, s9, s8
; SI-NEXT:    s_and_b32 s9, s55, 0xffff
; SI-NEXT:    s_lshl_b32 s10, s37, 16
; SI-NEXT:    s_add_i32 s28, s28, 3
; SI-NEXT:    s_or_b32 s9, s10, s9
; SI-NEXT:    s_and_b32 s10, s28, 0xffff
; SI-NEXT:    s_lshl_b32 s11, s54, 16
; SI-NEXT:    s_add_i32 s29, s29, 3
; SI-NEXT:    s_or_b32 s10, s11, s10
; SI-NEXT:    s_and_b32 s11, s29, 0xffff
; SI-NEXT:    s_lshl_b32 s12, s36, 16
; SI-NEXT:    s_add_i32 s26, s26, 3
; SI-NEXT:    s_or_b32 s11, s12, s11
; SI-NEXT:    s_and_b32 s12, s26, 0xffff
; SI-NEXT:    s_lshl_b32 s13, s53, 16
; SI-NEXT:    s_add_i32 s27, s27, 3
; SI-NEXT:    s_or_b32 s12, s13, s12
; SI-NEXT:    s_and_b32 s13, s27, 0xffff
; SI-NEXT:    s_lshl_b32 s14, s35, 16
; SI-NEXT:    s_add_i32 s24, s24, 3
; SI-NEXT:    s_or_b32 s13, s14, s13
; SI-NEXT:    s_and_b32 s14, s24, 0xffff
; SI-NEXT:    s_lshl_b32 s15, s52, 16
; SI-NEXT:    s_add_i32 s25, s25, 3
; SI-NEXT:    s_or_b32 s14, s15, s14
; SI-NEXT:    s_and_b32 s15, s25, 0xffff
; SI-NEXT:    s_lshl_b32 s24, s34, 16
; SI-NEXT:    s_add_i32 s22, s22, 3
; SI-NEXT:    s_or_b32 s15, s24, s15
; SI-NEXT:    s_and_b32 s22, s22, 0xffff
; SI-NEXT:    s_lshl_b32 s24, s51, 16
; SI-NEXT:    s_or_b32 s22, s24, s22
; SI-NEXT:    s_add_i32 s23, s23, 3
; SI-NEXT:    s_add_i32 s40, s22, 0x30000
; SI-NEXT:    s_and_b32 s22, s23, 0xffff
; SI-NEXT:    s_lshl_b32 s23, s31, 16
; SI-NEXT:    s_or_b32 s22, s23, s22
; SI-NEXT:    s_add_i32 s20, s20, 3
; SI-NEXT:    s_add_i32 s41, s22, 0x30000
; SI-NEXT:    s_and_b32 s20, s20, 0xffff
; SI-NEXT:    s_lshl_b32 s22, s50, 16
; SI-NEXT:    s_or_b32 s20, s22, s20
; SI-NEXT:    s_add_i32 s21, s21, 3
; SI-NEXT:    s_add_i32 s42, s20, 0x30000
; SI-NEXT:    s_and_b32 s20, s21, 0xffff
; SI-NEXT:    s_lshl_b32 s21, s30, 16
; SI-NEXT:    s_or_b32 s20, s21, s20
; SI-NEXT:    s_add_i32 s18, s18, 3
; SI-NEXT:    s_add_i32 s43, s20, 0x30000
; SI-NEXT:    s_and_b32 s18, s18, 0xffff
; SI-NEXT:    s_lshl_b32 s20, s49, 16
; SI-NEXT:    s_or_b32 s18, s20, s18
; SI-NEXT:    s_add_i32 s19, s19, 3
; SI-NEXT:    s_add_i32 s46, s18, 0x30000
; SI-NEXT:    s_and_b32 s18, s19, 0xffff
; SI-NEXT:    s_lshl_b32 s19, s95, 16
; SI-NEXT:    s_or_b32 s18, s19, s18
; SI-NEXT:    s_add_i32 s16, s16, 3
; SI-NEXT:    s_add_i32 s47, s18, 0x30000
; SI-NEXT:    s_and_b32 s16, s16, 0xffff
; SI-NEXT:    s_lshl_b32 s18, s48, 16
; SI-NEXT:    s_or_b32 s16, s18, s16
; SI-NEXT:    s_add_i32 s17, s17, 3
; SI-NEXT:    s_add_i32 s44, s16, 0x30000
; SI-NEXT:    s_and_b32 s16, s17, 0xffff
; SI-NEXT:    s_lshl_b32 s17, s94, 16
; SI-NEXT:    s_or_b32 s16, s17, s16
; SI-NEXT:    s_add_i32 s4, s4, 0x30000
; SI-NEXT:    s_add_i32 s5, s5, 0x30000
; SI-NEXT:    s_add_i32 s6, s6, 0x30000
; SI-NEXT:    s_add_i32 s7, s7, 0x30000
; SI-NEXT:    s_add_i32 s8, s8, 0x30000
; SI-NEXT:    s_add_i32 s9, s9, 0x30000
; SI-NEXT:    s_add_i32 s10, s10, 0x30000
; SI-NEXT:    s_add_i32 s11, s11, 0x30000
; SI-NEXT:    s_add_i32 s12, s12, 0x30000
; SI-NEXT:    s_add_i32 s13, s13, 0x30000
; SI-NEXT:    s_add_i32 s14, s14, 0x30000
; SI-NEXT:    s_add_i32 s15, s15, 0x30000
; SI-NEXT:    s_add_i32 s45, s16, 0x30000
; SI-NEXT:    s_lshr_b64 s[56:57], s[44:45], 16
; SI-NEXT:    s_lshr_b64 s[58:59], s[46:47], 16
; SI-NEXT:    s_lshr_b64 s[60:61], s[42:43], 16
; SI-NEXT:    s_lshr_b64 s[62:63], s[40:41], 16
; SI-NEXT:    s_lshr_b64 s[72:73], s[14:15], 16
; SI-NEXT:    s_lshr_b64 s[74:75], s[12:13], 16
; SI-NEXT:    s_lshr_b64 s[76:77], s[10:11], 16
; SI-NEXT:    s_lshr_b64 s[78:79], s[8:9], 16
; SI-NEXT:    s_lshr_b64 s[88:89], s[6:7], 16
; SI-NEXT:    s_lshr_b64 s[90:91], s[4:5], 16
; SI-NEXT:    s_lshr_b32 s94, s45, 16
; SI-NEXT:    s_lshr_b32 s95, s47, 16
; SI-NEXT:    s_lshr_b32 s30, s43, 16
; SI-NEXT:    s_lshr_b32 s31, s41, 16
; SI-NEXT:    s_lshr_b32 s34, s15, 16
; SI-NEXT:    s_lshr_b32 s35, s13, 16
; SI-NEXT:    s_lshr_b32 s36, s11, 16
; SI-NEXT:    s_lshr_b32 s37, s9, 16
; SI-NEXT:    s_lshr_b32 s38, s7, 16
; SI-NEXT:    s_lshr_b32 s39, s5, 16
; SI-NEXT:  .LBB57_3: ; %end
; SI-NEXT:    s_and_b32 s16, s44, 0xffff
; SI-NEXT:    s_lshl_b32 s17, s56, 16
; SI-NEXT:    s_or_b32 s16, s16, s17
; SI-NEXT:    s_and_b32 s17, s45, 0xffff
; SI-NEXT:    s_lshl_b32 s18, s94, 16
; SI-NEXT:    s_or_b32 s17, s17, s18
; SI-NEXT:    s_and_b32 s18, s46, 0xffff
; SI-NEXT:    s_lshl_b32 s19, s58, 16
; SI-NEXT:    s_or_b32 s18, s18, s19
; SI-NEXT:    s_and_b32 s19, s47, 0xffff
; SI-NEXT:    s_lshl_b32 s20, s95, 16
; SI-NEXT:    s_or_b32 s19, s19, s20
; SI-NEXT:    s_and_b32 s20, s42, 0xffff
; SI-NEXT:    s_lshl_b32 s21, s60, 16
; SI-NEXT:    s_or_b32 s20, s20, s21
; SI-NEXT:    s_and_b32 s21, s43, 0xffff
; SI-NEXT:    s_lshl_b32 s22, s30, 16
; SI-NEXT:    s_or_b32 s21, s21, s22
; SI-NEXT:    s_and_b32 s22, s40, 0xffff
; SI-NEXT:    s_lshl_b32 s23, s62, 16
; SI-NEXT:    s_or_b32 s22, s22, s23
; SI-NEXT:    s_and_b32 s23, s41, 0xffff
; SI-NEXT:    s_lshl_b32 s24, s31, 16
; SI-NEXT:    s_or_b32 s23, s23, s24
; SI-NEXT:    s_and_b32 s14, s14, 0xffff
; SI-NEXT:    s_lshl_b32 s24, s72, 16
; SI-NEXT:    s_or_b32 s14, s14, s24
; SI-NEXT:    s_and_b32 s15, s15, 0xffff
; SI-NEXT:    s_lshl_b32 s24, s34, 16
; SI-NEXT:    s_or_b32 s15, s15, s24
; SI-NEXT:    s_and_b32 s12, s12, 0xffff
; SI-NEXT:    s_lshl_b32 s24, s74, 16
; SI-NEXT:    s_or_b32 s12, s12, s24
; SI-NEXT:    s_and_b32 s13, s13, 0xffff
; SI-NEXT:    s_lshl_b32 s24, s35, 16
; SI-NEXT:    s_or_b32 s13, s13, s24
; SI-NEXT:    s_and_b32 s10, s10, 0xffff
; SI-NEXT:    s_lshl_b32 s24, s76, 16
; SI-NEXT:    s_or_b32 s10, s10, s24
; SI-NEXT:    s_and_b32 s11, s11, 0xffff
; SI-NEXT:    s_lshl_b32 s24, s36, 16
; SI-NEXT:    s_or_b32 s11, s11, s24
; SI-NEXT:    s_and_b32 s8, s8, 0xffff
; SI-NEXT:    s_lshl_b32 s24, s78, 16
; SI-NEXT:    s_or_b32 s8, s8, s24
; SI-NEXT:    s_and_b32 s9, s9, 0xffff
; SI-NEXT:    s_lshl_b32 s24, s37, 16
; SI-NEXT:    s_or_b32 s9, s9, s24
; SI-NEXT:    s_and_b32 s6, s6, 0xffff
; SI-NEXT:    s_lshl_b32 s24, s88, 16
; SI-NEXT:    s_or_b32 s6, s6, s24
; SI-NEXT:    s_and_b32 s7, s7, 0xffff
; SI-NEXT:    s_lshl_b32 s24, s38, 16
; SI-NEXT:    s_or_b32 s7, s7, s24
; SI-NEXT:    s_and_b32 s4, s4, 0xffff
; SI-NEXT:    s_lshl_b32 s24, s90, 16
; SI-NEXT:    s_or_b32 s4, s4, s24
; SI-NEXT:    s_and_b32 s5, s5, 0xffff
; SI-NEXT:    s_lshl_b32 s24, s39, 16
; SI-NEXT:    s_or_b32 s5, s5, s24
; SI-NEXT:    v_readlane_b32 s30, v20, 22
; SI-NEXT:    v_mov_b32_e32 v0, s16
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v2, s18
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v4, s20
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v6, s22
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    v_mov_b32_e32 v8, s14
; SI-NEXT:    v_mov_b32_e32 v9, s15
; SI-NEXT:    v_mov_b32_e32 v10, s12
; SI-NEXT:    v_mov_b32_e32 v11, s13
; SI-NEXT:    v_mov_b32_e32 v12, s10
; SI-NEXT:    v_mov_b32_e32 v13, s11
; SI-NEXT:    v_mov_b32_e32 v14, s8
; SI-NEXT:    v_mov_b32_e32 v15, s9
; SI-NEXT:    v_mov_b32_e32 v16, s6
; SI-NEXT:    v_mov_b32_e32 v17, s7
; SI-NEXT:    v_mov_b32_e32 v18, s4
; SI-NEXT:    v_mov_b32_e32 v19, s5
; SI-NEXT:    v_readlane_b32 s31, v20, 23
; SI-NEXT:    v_readlane_b32 s71, v20, 21
; SI-NEXT:    v_readlane_b32 s70, v20, 20
; SI-NEXT:    v_readlane_b32 s69, v20, 19
; SI-NEXT:    v_readlane_b32 s68, v20, 18
; SI-NEXT:    v_readlane_b32 s67, v20, 17
; SI-NEXT:    v_readlane_b32 s66, v20, 16
; SI-NEXT:    v_readlane_b32 s65, v20, 15
; SI-NEXT:    v_readlane_b32 s64, v20, 14
; SI-NEXT:    v_readlane_b32 s55, v20, 13
; SI-NEXT:    v_readlane_b32 s54, v20, 12
; SI-NEXT:    v_readlane_b32 s53, v20, 11
; SI-NEXT:    v_readlane_b32 s52, v20, 10
; SI-NEXT:    v_readlane_b32 s51, v20, 9
; SI-NEXT:    v_readlane_b32 s50, v20, 8
; SI-NEXT:    v_readlane_b32 s49, v20, 7
; SI-NEXT:    v_readlane_b32 s48, v20, 6
; SI-NEXT:    v_readlane_b32 s39, v20, 5
; SI-NEXT:    v_readlane_b32 s38, v20, 4
; SI-NEXT:    v_readlane_b32 s37, v20, 3
; SI-NEXT:    v_readlane_b32 s36, v20, 2
; SI-NEXT:    v_readlane_b32 s35, v20, 1
; SI-NEXT:    v_readlane_b32 s34, v20, 0
; SI-NEXT:    s_xor_saveexec_b64 s[4:5], -1
; SI-NEXT:    buffer_load_dword v20, off, s[0:3], s32 ; 4-byte Folded Reload
; SI-NEXT:    s_mov_b64 exec, s[4:5]
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    s_setpc_b64 s[30:31]
; SI-NEXT:  .LBB57_4:
; SI-NEXT:    ; implicit-def: $sgpr44
; SI-NEXT:    ; implicit-def: $sgpr56
; SI-NEXT:    ; implicit-def: $sgpr46
; SI-NEXT:    ; implicit-def: $sgpr58
; SI-NEXT:    ; implicit-def: $sgpr42
; SI-NEXT:    ; implicit-def: $sgpr60
; SI-NEXT:    ; implicit-def: $sgpr40
; SI-NEXT:    ; implicit-def: $sgpr62
; SI-NEXT:    ; implicit-def: $sgpr14
; SI-NEXT:    ; implicit-def: $sgpr72
; SI-NEXT:    ; implicit-def: $sgpr12
; SI-NEXT:    ; implicit-def: $sgpr74
; SI-NEXT:    ; implicit-def: $sgpr10
; SI-NEXT:    ; implicit-def: $sgpr76
; SI-NEXT:    ; implicit-def: $sgpr8
; SI-NEXT:    ; implicit-def: $sgpr78
; SI-NEXT:    ; implicit-def: $sgpr6
; SI-NEXT:    ; implicit-def: $sgpr88
; SI-NEXT:    ; implicit-def: $sgpr4
; SI-NEXT:    ; implicit-def: $sgpr90
; SI-NEXT:    s_branch .LBB57_2
;
; VI-LABEL: bitcast_v40i16_to_v40f16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_readfirstlane_b32 s7, v5
; VI-NEXT:    v_readfirstlane_b32 s9, v4
; VI-NEXT:    v_readfirstlane_b32 s12, v3
; VI-NEXT:    v_readfirstlane_b32 s40, v2
; VI-NEXT:    v_readfirstlane_b32 s43, v1
; VI-NEXT:    v_readfirstlane_b32 s46, v0
; VI-NEXT:    s_lshr_b32 s8, s29, 16
; VI-NEXT:    s_lshr_b32 s11, s28, 16
; VI-NEXT:    s_lshr_b32 s14, s27, 16
; VI-NEXT:    s_lshr_b32 s15, s26, 16
; VI-NEXT:    s_lshr_b32 s42, s25, 16
; VI-NEXT:    s_lshr_b32 s45, s24, 16
; VI-NEXT:    s_lshr_b32 s56, s23, 16
; VI-NEXT:    s_lshr_b32 s57, s22, 16
; VI-NEXT:    s_lshr_b32 s58, s21, 16
; VI-NEXT:    s_lshr_b32 s59, s20, 16
; VI-NEXT:    s_lshr_b32 s60, s19, 16
; VI-NEXT:    s_lshr_b32 s61, s18, 16
; VI-NEXT:    s_lshr_b32 s62, s17, 16
; VI-NEXT:    s_lshr_b32 s63, s16, 16
; VI-NEXT:    s_lshr_b32 s6, s7, 16
; VI-NEXT:    s_lshr_b32 s10, s9, 16
; VI-NEXT:    s_lshr_b32 s13, s12, 16
; VI-NEXT:    s_lshr_b32 s41, s40, 16
; VI-NEXT:    s_lshr_b32 s44, s43, 16
; VI-NEXT:    s_lshr_b32 s47, s46, 16
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    s_cbranch_scc0 .LBB57_4
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB57_3
; VI-NEXT:  .LBB57_2: ; %cmp.true
; VI-NEXT:    s_add_i32 s16, s16, 3
; VI-NEXT:    s_add_i32 s63, s63, 3
; VI-NEXT:    s_add_i32 s17, s17, 3
; VI-NEXT:    s_add_i32 s62, s62, 3
; VI-NEXT:    s_add_i32 s18, s18, 3
; VI-NEXT:    s_add_i32 s61, s61, 3
; VI-NEXT:    s_add_i32 s19, s19, 3
; VI-NEXT:    s_add_i32 s60, s60, 3
; VI-NEXT:    s_add_i32 s20, s20, 3
; VI-NEXT:    s_add_i32 s59, s59, 3
; VI-NEXT:    s_add_i32 s21, s21, 3
; VI-NEXT:    s_add_i32 s58, s58, 3
; VI-NEXT:    s_add_i32 s22, s22, 3
; VI-NEXT:    s_add_i32 s57, s57, 3
; VI-NEXT:    s_add_i32 s23, s23, 3
; VI-NEXT:    s_add_i32 s56, s56, 3
; VI-NEXT:    s_add_i32 s24, s24, 3
; VI-NEXT:    s_add_i32 s45, s45, 3
; VI-NEXT:    s_add_i32 s25, s25, 3
; VI-NEXT:    s_add_i32 s42, s42, 3
; VI-NEXT:    s_add_i32 s26, s26, 3
; VI-NEXT:    s_add_i32 s15, s15, 3
; VI-NEXT:    s_add_i32 s27, s27, 3
; VI-NEXT:    s_add_i32 s14, s14, 3
; VI-NEXT:    s_add_i32 s28, s28, 3
; VI-NEXT:    s_add_i32 s11, s11, 3
; VI-NEXT:    s_add_i32 s29, s29, 3
; VI-NEXT:    s_add_i32 s8, s8, 3
; VI-NEXT:    s_add_i32 s46, s46, 3
; VI-NEXT:    s_add_i32 s47, s47, 3
; VI-NEXT:    s_add_i32 s43, s43, 3
; VI-NEXT:    s_add_i32 s44, s44, 3
; VI-NEXT:    s_add_i32 s40, s40, 3
; VI-NEXT:    s_add_i32 s41, s41, 3
; VI-NEXT:    s_add_i32 s12, s12, 3
; VI-NEXT:    s_add_i32 s13, s13, 3
; VI-NEXT:    s_add_i32 s9, s9, 3
; VI-NEXT:    s_add_i32 s10, s10, 3
; VI-NEXT:    s_add_i32 s7, s7, 3
; VI-NEXT:    s_add_i32 s6, s6, 3
; VI-NEXT:  .LBB57_3: ; %end
; VI-NEXT:    s_and_b32 s4, 0xffff, s16
; VI-NEXT:    s_lshl_b32 s5, s63, 16
; VI-NEXT:    s_or_b32 s4, s4, s5
; VI-NEXT:    s_and_b32 s5, 0xffff, s17
; VI-NEXT:    s_lshl_b32 s16, s62, 16
; VI-NEXT:    s_or_b32 s5, s5, s16
; VI-NEXT:    s_and_b32 s16, 0xffff, s18
; VI-NEXT:    s_lshl_b32 s17, s61, 16
; VI-NEXT:    s_or_b32 s16, s16, s17
; VI-NEXT:    s_and_b32 s17, 0xffff, s19
; VI-NEXT:    s_lshl_b32 s18, s60, 16
; VI-NEXT:    s_or_b32 s17, s17, s18
; VI-NEXT:    s_and_b32 s18, 0xffff, s20
; VI-NEXT:    s_lshl_b32 s19, s59, 16
; VI-NEXT:    s_or_b32 s18, s18, s19
; VI-NEXT:    s_and_b32 s19, 0xffff, s21
; VI-NEXT:    s_lshl_b32 s20, s58, 16
; VI-NEXT:    s_or_b32 s19, s19, s20
; VI-NEXT:    s_and_b32 s20, 0xffff, s22
; VI-NEXT:    s_lshl_b32 s21, s57, 16
; VI-NEXT:    s_or_b32 s20, s20, s21
; VI-NEXT:    s_and_b32 s21, 0xffff, s23
; VI-NEXT:    s_lshl_b32 s22, s56, 16
; VI-NEXT:    s_or_b32 s21, s21, s22
; VI-NEXT:    s_and_b32 s22, 0xffff, s24
; VI-NEXT:    s_lshl_b32 s23, s45, 16
; VI-NEXT:    s_or_b32 s22, s22, s23
; VI-NEXT:    s_and_b32 s23, 0xffff, s25
; VI-NEXT:    s_lshl_b32 s24, s42, 16
; VI-NEXT:    s_or_b32 s23, s23, s24
; VI-NEXT:    s_and_b32 s24, 0xffff, s26
; VI-NEXT:    s_lshl_b32 s15, s15, 16
; VI-NEXT:    s_or_b32 s15, s24, s15
; VI-NEXT:    s_and_b32 s24, 0xffff, s27
; VI-NEXT:    s_lshl_b32 s14, s14, 16
; VI-NEXT:    s_or_b32 s14, s24, s14
; VI-NEXT:    s_and_b32 s24, 0xffff, s28
; VI-NEXT:    s_lshl_b32 s11, s11, 16
; VI-NEXT:    s_or_b32 s11, s24, s11
; VI-NEXT:    s_and_b32 s24, 0xffff, s29
; VI-NEXT:    s_lshl_b32 s8, s8, 16
; VI-NEXT:    s_or_b32 s8, s24, s8
; VI-NEXT:    s_and_b32 s24, 0xffff, s46
; VI-NEXT:    s_lshl_b32 s25, s47, 16
; VI-NEXT:    s_or_b32 s24, s24, s25
; VI-NEXT:    s_and_b32 s25, 0xffff, s43
; VI-NEXT:    s_lshl_b32 s26, s44, 16
; VI-NEXT:    s_or_b32 s25, s25, s26
; VI-NEXT:    s_and_b32 s26, 0xffff, s40
; VI-NEXT:    s_lshl_b32 s27, s41, 16
; VI-NEXT:    s_and_b32 s12, 0xffff, s12
; VI-NEXT:    s_lshl_b32 s13, s13, 16
; VI-NEXT:    s_and_b32 s9, 0xffff, s9
; VI-NEXT:    s_lshl_b32 s10, s10, 16
; VI-NEXT:    s_and_b32 s7, 0xffff, s7
; VI-NEXT:    s_lshl_b32 s6, s6, 16
; VI-NEXT:    s_or_b32 s26, s26, s27
; VI-NEXT:    s_or_b32 s12, s12, s13
; VI-NEXT:    s_or_b32 s9, s9, s10
; VI-NEXT:    s_or_b32 s6, s7, s6
; VI-NEXT:    v_mov_b32_e32 v0, s4
; VI-NEXT:    v_mov_b32_e32 v1, s5
; VI-NEXT:    v_mov_b32_e32 v2, s16
; VI-NEXT:    v_mov_b32_e32 v3, s17
; VI-NEXT:    v_mov_b32_e32 v4, s18
; VI-NEXT:    v_mov_b32_e32 v5, s19
; VI-NEXT:    v_mov_b32_e32 v6, s20
; VI-NEXT:    v_mov_b32_e32 v7, s21
; VI-NEXT:    v_mov_b32_e32 v8, s22
; VI-NEXT:    v_mov_b32_e32 v9, s23
; VI-NEXT:    v_mov_b32_e32 v10, s15
; VI-NEXT:    v_mov_b32_e32 v11, s14
; VI-NEXT:    v_mov_b32_e32 v12, s11
; VI-NEXT:    v_mov_b32_e32 v13, s8
; VI-NEXT:    v_mov_b32_e32 v14, s24
; VI-NEXT:    v_mov_b32_e32 v15, s25
; VI-NEXT:    v_mov_b32_e32 v16, s26
; VI-NEXT:    v_mov_b32_e32 v17, s12
; VI-NEXT:    v_mov_b32_e32 v18, s9
; VI-NEXT:    v_mov_b32_e32 v19, s6
; VI-NEXT:    s_setpc_b64 s[30:31]
; VI-NEXT:  .LBB57_4:
; VI-NEXT:    s_branch .LBB57_2
;
; GFX9-LABEL: bitcast_v40i16_to_v40f16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_readfirstlane_b32 s63, v5
; GFX9-NEXT:    v_readfirstlane_b32 s62, v4
; GFX9-NEXT:    v_readfirstlane_b32 s61, v3
; GFX9-NEXT:    v_readfirstlane_b32 s60, v2
; GFX9-NEXT:    v_readfirstlane_b32 s59, v1
; GFX9-NEXT:    v_readfirstlane_b32 s58, v0
; GFX9-NEXT:    s_lshr_b32 s43, s29, 16
; GFX9-NEXT:    s_lshr_b32 s42, s28, 16
; GFX9-NEXT:    s_lshr_b32 s41, s27, 16
; GFX9-NEXT:    s_lshr_b32 s40, s26, 16
; GFX9-NEXT:    s_lshr_b32 s15, s25, 16
; GFX9-NEXT:    s_lshr_b32 s14, s24, 16
; GFX9-NEXT:    s_lshr_b32 s13, s23, 16
; GFX9-NEXT:    s_lshr_b32 s12, s22, 16
; GFX9-NEXT:    s_lshr_b32 s11, s21, 16
; GFX9-NEXT:    s_lshr_b32 s10, s20, 16
; GFX9-NEXT:    s_lshr_b32 s9, s19, 16
; GFX9-NEXT:    s_lshr_b32 s8, s18, 16
; GFX9-NEXT:    s_lshr_b32 s7, s17, 16
; GFX9-NEXT:    s_lshr_b32 s6, s16, 16
; GFX9-NEXT:    s_lshr_b32 s57, s63, 16
; GFX9-NEXT:    s_lshr_b32 s56, s62, 16
; GFX9-NEXT:    s_lshr_b32 s47, s61, 16
; GFX9-NEXT:    s_lshr_b32 s46, s60, 16
; GFX9-NEXT:    s_lshr_b32 s45, s59, 16
; GFX9-NEXT:    s_lshr_b32 s44, s58, 16
; GFX9-NEXT:    v_readfirstlane_b32 s4, v6
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB57_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB57_4
; GFX9-NEXT:  .LBB57_2: ; %cmp.true
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s63, s57
; GFX9-NEXT:    v_pk_add_u16 v19, s4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s62, s56
; GFX9-NEXT:    v_pk_add_u16 v18, s4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s61, s47
; GFX9-NEXT:    v_pk_add_u16 v17, s4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s60, s46
; GFX9-NEXT:    v_pk_add_u16 v16, s4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s59, s45
; GFX9-NEXT:    v_pk_add_u16 v15, s4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s58, s44
; GFX9-NEXT:    v_pk_add_u16 v14, s4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s29, s43
; GFX9-NEXT:    v_pk_add_u16 v13, s4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s28, s42
; GFX9-NEXT:    v_pk_add_u16 v12, s4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s27, s41
; GFX9-NEXT:    v_pk_add_u16 v11, s4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s26, s40
; GFX9-NEXT:    v_pk_add_u16 v10, s4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s25, s15
; GFX9-NEXT:    v_pk_add_u16 v9, s4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s24, s14
; GFX9-NEXT:    v_pk_add_u16 v8, s4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s23, s13
; GFX9-NEXT:    v_pk_add_u16 v7, s4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s22, s12
; GFX9-NEXT:    v_pk_add_u16 v6, s4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s21, s11
; GFX9-NEXT:    v_pk_add_u16 v5, s4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s20, s10
; GFX9-NEXT:    v_pk_add_u16 v4, s4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s19, s9
; GFX9-NEXT:    v_pk_add_u16 v3, s4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s18, s8
; GFX9-NEXT:    v_pk_add_u16 v2, s4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s17, s7
; GFX9-NEXT:    v_pk_add_u16 v1, s4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s16, s6
; GFX9-NEXT:    v_pk_add_u16 v0, s4, 3 op_sel_hi:[1,0]
; GFX9-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX9-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX9-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX9-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX9-NEXT:    s_branch .LBB57_5
; GFX9-NEXT:  .LBB57_3:
; GFX9-NEXT:    s_branch .LBB57_2
; GFX9-NEXT:  .LBB57_4:
; GFX9-NEXT:    v_mov_b32_e32 v19, s63
; GFX9-NEXT:    v_mov_b32_e32 v18, s62
; GFX9-NEXT:    v_mov_b32_e32 v17, s61
; GFX9-NEXT:    v_mov_b32_e32 v16, s60
; GFX9-NEXT:    v_mov_b32_e32 v15, s59
; GFX9-NEXT:    v_mov_b32_e32 v14, s58
; GFX9-NEXT:    v_mov_b32_e32 v13, s29
; GFX9-NEXT:    v_mov_b32_e32 v12, s28
; GFX9-NEXT:    v_mov_b32_e32 v11, s27
; GFX9-NEXT:    v_mov_b32_e32 v10, s26
; GFX9-NEXT:    v_mov_b32_e32 v9, s25
; GFX9-NEXT:    v_mov_b32_e32 v8, s24
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v20, s57
; GFX9-NEXT:    v_mov_b32_e32 v21, s56
; GFX9-NEXT:    v_mov_b32_e32 v22, s47
; GFX9-NEXT:    v_mov_b32_e32 v23, s46
; GFX9-NEXT:    v_mov_b32_e32 v24, s45
; GFX9-NEXT:    v_mov_b32_e32 v25, s44
; GFX9-NEXT:    v_mov_b32_e32 v26, s43
; GFX9-NEXT:    v_mov_b32_e32 v27, s42
; GFX9-NEXT:    v_mov_b32_e32 v28, s41
; GFX9-NEXT:    v_mov_b32_e32 v29, s40
; GFX9-NEXT:    v_mov_b32_e32 v30, s15
; GFX9-NEXT:    v_mov_b32_e32 v31, s14
; GFX9-NEXT:    v_mov_b32_e32 v32, s13
; GFX9-NEXT:    v_mov_b32_e32 v33, s12
; GFX9-NEXT:    v_mov_b32_e32 v34, s11
; GFX9-NEXT:    v_mov_b32_e32 v35, s10
; GFX9-NEXT:    v_mov_b32_e32 v36, s9
; GFX9-NEXT:    v_mov_b32_e32 v37, s8
; GFX9-NEXT:    v_mov_b32_e32 v38, s7
; GFX9-NEXT:    v_mov_b32_e32 v39, s6
; GFX9-NEXT:  .LBB57_5: ; %end
; GFX9-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; GFX9-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX9-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GFX9-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX9-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; GFX9-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; GFX9-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; GFX9-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; GFX9-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; GFX9-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; GFX9-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; GFX9-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; GFX9-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; GFX9-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; GFX9-NEXT:    v_and_b32_e32 v16, 0xffff, v16
; GFX9-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; GFX9-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; GFX9-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; GFX9-NEXT:    v_lshl_or_b32 v0, v39, 16, v0
; GFX9-NEXT:    v_lshl_or_b32 v1, v38, 16, v1
; GFX9-NEXT:    v_lshl_or_b32 v2, v37, 16, v2
; GFX9-NEXT:    v_lshl_or_b32 v3, v36, 16, v3
; GFX9-NEXT:    v_lshl_or_b32 v4, v35, 16, v4
; GFX9-NEXT:    v_lshl_or_b32 v5, v34, 16, v5
; GFX9-NEXT:    v_lshl_or_b32 v6, v33, 16, v6
; GFX9-NEXT:    v_lshl_or_b32 v7, v32, 16, v7
; GFX9-NEXT:    v_lshl_or_b32 v8, v31, 16, v8
; GFX9-NEXT:    v_lshl_or_b32 v9, v30, 16, v9
; GFX9-NEXT:    v_lshl_or_b32 v10, v29, 16, v10
; GFX9-NEXT:    v_lshl_or_b32 v11, v28, 16, v11
; GFX9-NEXT:    v_lshl_or_b32 v12, v27, 16, v12
; GFX9-NEXT:    v_lshl_or_b32 v13, v26, 16, v13
; GFX9-NEXT:    v_lshl_or_b32 v14, v25, 16, v14
; GFX9-NEXT:    v_lshl_or_b32 v15, v24, 16, v15
; GFX9-NEXT:    v_lshl_or_b32 v16, v23, 16, v16
; GFX9-NEXT:    v_lshl_or_b32 v17, v22, 16, v17
; GFX9-NEXT:    v_lshl_or_b32 v18, v21, 16, v18
; GFX9-NEXT:    v_lshl_or_b32 v19, v20, 16, v19
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v40i16_to_v40f16_scalar:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s57, v1
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s56, v0
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s58, v2
; GFX11-TRUE16-NEXT:    s_lshr_b32 s45, s29, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s44, s28, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s43, s27, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s42, s26, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s41, s25, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s40, s24, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s15, s23, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s14, s22, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s13, s21, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s12, s20, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s11, s19, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s10, s18, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s9, s17, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s8, s16, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s6, s3, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s4, s2, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s5, s1, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s7, s0, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s47, s57, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s46, s56, 16
; GFX11-TRUE16-NEXT:    s_cmp_lg_u32 s58, 0
; GFX11-TRUE16-NEXT:    s_mov_b32 s58, 0
; GFX11-TRUE16-NEXT:    s_cbranch_scc0 .LBB57_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s58
; GFX11-TRUE16-NEXT:    s_cbranch_vccnz .LBB57_4
; GFX11-TRUE16-NEXT:  .LBB57_2: ; %cmp.true
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s47, s57, s47
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s46, s56, s46
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s29, s29, s45
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s28, s28, s44
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s27, s27, s43
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s26, s26, s42
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s25, s25, s41
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s24, s24, s40
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s15, s23, s15
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s14, s22, s14
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s13, s21, s13
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s12, s20, s12
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s11, s19, s11
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s10, s18, s10
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s9, s17, s9
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s8, s16, s8
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s3, s3, s6
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s2, s2, s4
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s0, s0, s7
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s1, s1, s5
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v19, s47, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v18, s46, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v17, s29, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v16, s28, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v15, s27, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v14, s26, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v13, s25, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v12, s24, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v11, s15, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v10, s14, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v9, s13, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v8, s12, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v7, s11, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v6, s10, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v5, s9, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v0, s0, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v1, s1, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v2, s2, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v3, s3, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_pk_add_u16 v4, s8, 3 op_sel_hi:[1,0]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX11-TRUE16-NEXT:    s_branch .LBB57_5
; GFX11-TRUE16-NEXT:  .LBB57_3:
; GFX11-TRUE16-NEXT:    s_branch .LBB57_2
; GFX11-TRUE16-NEXT:  .LBB57_4:
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v19, s57 :: v_dual_mov_b32 v18, s56
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v17, s29 :: v_dual_mov_b32 v16, s28
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v15, s27 :: v_dual_mov_b32 v14, s26
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v13, s25 :: v_dual_mov_b32 v12, s24
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v11, s23 :: v_dual_mov_b32 v10, s22
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v9, s21 :: v_dual_mov_b32 v8, s20
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v7, s19 :: v_dual_mov_b32 v6, s18
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v5, s17 :: v_dual_mov_b32 v4, s16
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v3, s3 :: v_dual_mov_b32 v2, s2
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v1, s1 :: v_dual_mov_b32 v0, s0
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v20, s47 :: v_dual_mov_b32 v21, s46
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v22, s45 :: v_dual_mov_b32 v23, s44
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v24, s43 :: v_dual_mov_b32 v25, s42
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v26, s41 :: v_dual_mov_b32 v27, s40
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v28, s15 :: v_dual_mov_b32 v29, s14
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v30, s13 :: v_dual_mov_b32 v31, s12
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v32, s11 :: v_dual_mov_b32 v33, s10
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v34, s9 :: v_dual_mov_b32 v35, s8
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v36, s6 :: v_dual_mov_b32 v37, s4
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v38, s5 :: v_dual_mov_b32 v39, s7
; GFX11-TRUE16-NEXT:  .LBB57_5: ; %end
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.h, v39.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v1.h, v38.l
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.h, v37.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v3.h, v36.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v4.h, v35.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v5.h, v34.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v6.h, v33.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v7.h, v32.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v8.h, v31.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v9.h, v30.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v10.h, v29.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v11.h, v28.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v12.h, v27.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v13.h, v26.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v14.h, v25.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v15.h, v24.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v16.h, v23.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v17.h, v22.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v18.h, v21.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v19.h, v20.l
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v40i16_to_v40f16_scalar:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s57, v1
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s56, v0
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s58, v2
; GFX11-FAKE16-NEXT:    s_lshr_b32 s45, s29, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s44, s28, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s43, s27, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s42, s26, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s41, s25, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s40, s24, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s15, s23, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s14, s22, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s13, s21, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s12, s20, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s11, s19, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s10, s18, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s9, s17, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s8, s16, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s6, s3, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s4, s2, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s5, s1, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s7, s0, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s47, s57, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s46, s56, 16
; GFX11-FAKE16-NEXT:    s_cmp_lg_u32 s58, 0
; GFX11-FAKE16-NEXT:    s_mov_b32 s58, 0
; GFX11-FAKE16-NEXT:    s_cbranch_scc0 .LBB57_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s58
; GFX11-FAKE16-NEXT:    s_cbranch_vccnz .LBB57_4
; GFX11-FAKE16-NEXT:  .LBB57_2: ; %cmp.true
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s47, s57, s47
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s46, s56, s46
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s29, s29, s45
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s28, s28, s44
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s27, s27, s43
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s26, s26, s42
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s25, s25, s41
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s24, s24, s40
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s15, s23, s15
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s14, s22, s14
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s13, s21, s13
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s12, s20, s12
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s11, s19, s11
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s10, s18, s10
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s9, s17, s9
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s8, s16, s8
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s3, s3, s6
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s2, s2, s4
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s0, s0, s7
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s1, s1, s5
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v15, s47, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v16, s46, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v17, s29, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v18, s28, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v19, s27, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v10, s26, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v11, s25, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v12, s24, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v13, s15, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v14, s14, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v5, s13, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v6, s12, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v7, s11, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v8, s10, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v9, s9, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v4, s0, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v3, s1, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v2, s2, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v1, s3, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_pk_add_u16 v0, s8, 3 op_sel_hi:[1,0]
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v20, 16, v15
; GFX11-FAKE16-NEXT:    s_branch .LBB57_5
; GFX11-FAKE16-NEXT:  .LBB57_3:
; GFX11-FAKE16-NEXT:    s_branch .LBB57_2
; GFX11-FAKE16-NEXT:  .LBB57_4:
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v15, s57 :: v_dual_mov_b32 v16, s56
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v17, s29 :: v_dual_mov_b32 v18, s28
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v19, s27 :: v_dual_mov_b32 v10, s26
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v11, s25 :: v_dual_mov_b32 v12, s24
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v13, s23 :: v_dual_mov_b32 v14, s22
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v5, s21 :: v_dual_mov_b32 v6, s20
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v7, s19 :: v_dual_mov_b32 v8, s18
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v9, s17 :: v_dual_mov_b32 v0, s16
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v1, s3 :: v_dual_mov_b32 v2, s2
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v3, s1 :: v_dual_mov_b32 v4, s0
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v20, s47 :: v_dual_mov_b32 v21, s46
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v22, s45 :: v_dual_mov_b32 v23, s44
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v24, s43 :: v_dual_mov_b32 v25, s42
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v26, s41 :: v_dual_mov_b32 v27, s40
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v28, s15 :: v_dual_mov_b32 v29, s14
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v30, s13 :: v_dual_mov_b32 v31, s12
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v32, s11 :: v_dual_mov_b32 v33, s10
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v34, s9 :: v_dual_mov_b32 v35, s8
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v36, s6 :: v_dual_mov_b32 v37, s4
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v38, s5 :: v_dual_mov_b32 v39, s7
; GFX11-FAKE16-NEXT:  .LBB57_5: ; %end
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v48, 0xffff, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v49, 0xffff, v0
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v0, v39, 16, v4
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v1, v38, 16, v3
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v3, v36, 16, v48
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v4, v35, 16, v49
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v35, 0xffff, v6
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v36, 0xffff, v5
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v5, v34, 16, v9
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v6, v33, 16, v8
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v8, v31, 16, v35
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v9, v30, 16, v36
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v30, 0xffff, v11
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v31, 0xffff, v10
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v10, v29, 16, v14
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v11, v28, 16, v13
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v13, v26, 16, v30
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v14, v25, 16, v31
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v25, 0xffff, v16
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v26, 0xffff, v15
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v2, v37, 16, v2
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v7, v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v12, v27, 16, v12
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v15, v24, 16, v19
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v16, v23, 16, v18
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v17, v22, 16, v17
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v18, v21, 16, v25
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v19, v20, 16, v26
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = add <40 x i16> %a, splat (i16 3)
  %a2 = bitcast <40 x i16> %a1 to <40 x half>
  br label %end

cmp.false:
  %a3 = bitcast <40 x i16> %a to <40 x half>
  br label %end

end:
  %phi = phi <40 x half> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <40 x half> %phi
}

define <40 x i16> @bitcast_v40f16_to_v40i16(<40 x half> %a, i32 %b) #0 {
; SI-LABEL: bitcast_v40f16_to_v40i16:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    v_lshrrev_b32_e32 v21, 16, v19
; SI-NEXT:    v_lshrrev_b32_e32 v24, 16, v18
; SI-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; SI-NEXT:    v_lshrrev_b32_e32 v26, 16, v16
; SI-NEXT:    v_lshrrev_b32_e32 v23, 16, v15
; SI-NEXT:    v_lshrrev_b32_e32 v29, 16, v14
; SI-NEXT:    v_lshrrev_b32_e32 v25, 16, v13
; SI-NEXT:    v_lshrrev_b32_e32 v32, 16, v12
; SI-NEXT:    v_lshrrev_b32_e32 v27, 16, v11
; SI-NEXT:    v_lshrrev_b32_e32 v33, 16, v10
; SI-NEXT:    v_lshrrev_b32_e32 v28, 16, v9
; SI-NEXT:    v_lshrrev_b32_e32 v35, 16, v8
; SI-NEXT:    v_lshrrev_b32_e32 v30, 16, v7
; SI-NEXT:    v_lshrrev_b32_e32 v36, 16, v6
; SI-NEXT:    v_lshrrev_b32_e32 v31, 16, v5
; SI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; SI-NEXT:    v_lshrrev_b32_e32 v37, 16, v4
; SI-NEXT:    v_lshrrev_b32_e32 v20, 16, v3
; SI-NEXT:    v_lshrrev_b32_e32 v38, 16, v2
; SI-NEXT:    v_lshrrev_b32_e32 v34, 16, v1
; SI-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; SI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; SI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; SI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; SI-NEXT:    s_cbranch_execz .LBB58_2
; SI-NEXT:  ; %bb.1: ; %cmp.true
; SI-NEXT:    v_cvt_f32_f16_e32 v21, v21
; SI-NEXT:    v_cvt_f32_f16_e32 v19, v19
; SI-NEXT:    v_cvt_f32_f16_e32 v22, v22
; SI-NEXT:    v_cvt_f32_f16_e32 v17, v17
; SI-NEXT:    v_cvt_f32_f16_e32 v23, v23
; SI-NEXT:    v_cvt_f32_f16_e32 v15, v15
; SI-NEXT:    v_cvt_f32_f16_e32 v25, v25
; SI-NEXT:    v_add_f32_e32 v21, 0x38000000, v21
; SI-NEXT:    v_cvt_f32_f16_e32 v13, v13
; SI-NEXT:    v_cvt_f32_f16_e32 v27, v27
; SI-NEXT:    v_add_f32_e32 v19, 0x38000000, v19
; SI-NEXT:    v_cvt_f16_f32_e32 v21, v21
; SI-NEXT:    v_add_f32_e32 v22, 0x38000000, v22
; SI-NEXT:    v_cvt_f32_f16_e32 v11, v11
; SI-NEXT:    v_cvt_f32_f16_e32 v28, v28
; SI-NEXT:    v_cvt_f16_f32_e32 v19, v19
; SI-NEXT:    v_cvt_f16_f32_e32 v22, v22
; SI-NEXT:    v_add_f32_e32 v17, 0x38000000, v17
; SI-NEXT:    v_add_f32_e32 v23, 0x38000000, v23
; SI-NEXT:    v_cvt_f32_f16_e32 v9, v9
; SI-NEXT:    v_cvt_f32_f16_e32 v30, v30
; SI-NEXT:    v_cvt_f16_f32_e32 v17, v17
; SI-NEXT:    v_cvt_f16_f32_e32 v23, v23
; SI-NEXT:    v_add_f32_e32 v15, 0x38000000, v15
; SI-NEXT:    v_add_f32_e32 v25, 0x38000000, v25
; SI-NEXT:    v_cvt_f32_f16_e32 v7, v7
; SI-NEXT:    v_cvt_f32_f16_e32 v31, v31
; SI-NEXT:    v_cvt_f16_f32_e32 v15, v15
; SI-NEXT:    v_cvt_f16_f32_e32 v25, v25
; SI-NEXT:    v_add_f32_e32 v13, 0x38000000, v13
; SI-NEXT:    v_add_f32_e32 v27, 0x38000000, v27
; SI-NEXT:    v_cvt_f32_f16_e32 v5, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v20, v20
; SI-NEXT:    v_lshlrev_b32_e32 v48, 16, v21
; SI-NEXT:    v_cvt_f16_f32_e32 v13, v13
; SI-NEXT:    v_cvt_f16_f32_e32 v27, v27
; SI-NEXT:    v_add_f32_e32 v11, 0x38000000, v11
; SI-NEXT:    v_add_f32_e32 v28, 0x38000000, v28
; SI-NEXT:    v_cvt_f32_f16_e32 v3, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v34, v34
; SI-NEXT:    v_or_b32_e32 v19, v19, v48
; SI-NEXT:    v_lshlrev_b32_e32 v48, 16, v22
; SI-NEXT:    v_cvt_f16_f32_e32 v11, v11
; SI-NEXT:    v_cvt_f16_f32_e32 v28, v28
; SI-NEXT:    v_add_f32_e32 v9, 0x38000000, v9
; SI-NEXT:    v_add_f32_e32 v30, 0x38000000, v30
; SI-NEXT:    v_cvt_f32_f16_e32 v1, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v39, v39
; SI-NEXT:    v_cvt_f32_f16_e32 v38, v38
; SI-NEXT:    v_cvt_f32_f16_e32 v37, v37
; SI-NEXT:    v_cvt_f32_f16_e32 v36, v36
; SI-NEXT:    v_cvt_f32_f16_e32 v35, v35
; SI-NEXT:    v_cvt_f32_f16_e32 v33, v33
; SI-NEXT:    v_cvt_f32_f16_e32 v32, v32
; SI-NEXT:    v_cvt_f32_f16_e32 v29, v29
; SI-NEXT:    v_cvt_f32_f16_e32 v26, v26
; SI-NEXT:    v_cvt_f32_f16_e32 v24, v24
; SI-NEXT:    v_or_b32_e32 v17, v17, v48
; SI-NEXT:    v_lshlrev_b32_e32 v48, 16, v23
; SI-NEXT:    v_cvt_f16_f32_e32 v9, v9
; SI-NEXT:    v_cvt_f16_f32_e32 v30, v30
; SI-NEXT:    v_add_f32_e32 v7, 0x38000000, v7
; SI-NEXT:    v_add_f32_e32 v31, 0x38000000, v31
; SI-NEXT:    v_cvt_f32_f16_e32 v0, v0
; SI-NEXT:    v_cvt_f32_f16_e32 v2, v2
; SI-NEXT:    v_cvt_f32_f16_e32 v4, v4
; SI-NEXT:    v_cvt_f32_f16_e32 v6, v6
; SI-NEXT:    v_cvt_f32_f16_e32 v8, v8
; SI-NEXT:    v_cvt_f32_f16_e32 v10, v10
; SI-NEXT:    v_cvt_f32_f16_e32 v12, v12
; SI-NEXT:    v_cvt_f32_f16_e32 v14, v14
; SI-NEXT:    v_cvt_f32_f16_e32 v16, v16
; SI-NEXT:    v_cvt_f32_f16_e32 v18, v18
; SI-NEXT:    v_or_b32_e32 v15, v15, v48
; SI-NEXT:    v_lshlrev_b32_e32 v48, 16, v25
; SI-NEXT:    v_cvt_f16_f32_e32 v7, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v31, v31
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_add_f32_e32 v20, 0x38000000, v20
; SI-NEXT:    v_or_b32_e32 v13, v13, v48
; SI-NEXT:    v_lshlrev_b32_e32 v48, 16, v27
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v20, v20
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_add_f32_e32 v34, 0x38000000, v34
; SI-NEXT:    v_or_b32_e32 v11, v11, v48
; SI-NEXT:    v_lshlrev_b32_e32 v48, 16, v28
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v34, v34
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_add_f32_e32 v39, 0x38000000, v39
; SI-NEXT:    v_add_f32_e32 v38, 0x38000000, v38
; SI-NEXT:    v_add_f32_e32 v37, 0x38000000, v37
; SI-NEXT:    v_add_f32_e32 v36, 0x38000000, v36
; SI-NEXT:    v_add_f32_e32 v35, 0x38000000, v35
; SI-NEXT:    v_add_f32_e32 v33, 0x38000000, v33
; SI-NEXT:    v_add_f32_e32 v32, 0x38000000, v32
; SI-NEXT:    v_add_f32_e32 v29, 0x38000000, v29
; SI-NEXT:    v_add_f32_e32 v26, 0x38000000, v26
; SI-NEXT:    v_add_f32_e32 v24, 0x38000000, v24
; SI-NEXT:    v_or_b32_e32 v9, v9, v48
; SI-NEXT:    v_lshlrev_b32_e32 v48, 16, v30
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v39, v39
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v38, v38
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v37, v37
; SI-NEXT:    v_add_f32_e32 v4, 0x38000000, v4
; SI-NEXT:    v_cvt_f16_f32_e32 v36, v36
; SI-NEXT:    v_add_f32_e32 v6, 0x38000000, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v35, v35
; SI-NEXT:    v_add_f32_e32 v8, 0x38000000, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v33, v33
; SI-NEXT:    v_add_f32_e32 v10, 0x38000000, v10
; SI-NEXT:    v_cvt_f16_f32_e32 v32, v32
; SI-NEXT:    v_add_f32_e32 v12, 0x38000000, v12
; SI-NEXT:    v_cvt_f16_f32_e32 v29, v29
; SI-NEXT:    v_add_f32_e32 v14, 0x38000000, v14
; SI-NEXT:    v_cvt_f16_f32_e32 v26, v26
; SI-NEXT:    v_add_f32_e32 v16, 0x38000000, v16
; SI-NEXT:    v_cvt_f16_f32_e32 v24, v24
; SI-NEXT:    v_add_f32_e32 v18, 0x38000000, v18
; SI-NEXT:    v_or_b32_e32 v7, v7, v48
; SI-NEXT:    v_lshlrev_b32_e32 v48, 16, v31
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v4, v4
; SI-NEXT:    v_cvt_f16_f32_e32 v6, v6
; SI-NEXT:    v_cvt_f16_f32_e32 v8, v8
; SI-NEXT:    v_cvt_f16_f32_e32 v10, v10
; SI-NEXT:    v_cvt_f16_f32_e32 v12, v12
; SI-NEXT:    v_cvt_f16_f32_e32 v14, v14
; SI-NEXT:    v_cvt_f16_f32_e32 v16, v16
; SI-NEXT:    v_cvt_f16_f32_e32 v18, v18
; SI-NEXT:    v_or_b32_e32 v5, v5, v48
; SI-NEXT:    v_lshlrev_b32_e32 v48, 16, v20
; SI-NEXT:    v_or_b32_e32 v3, v3, v48
; SI-NEXT:    v_lshlrev_b32_e32 v48, 16, v34
; SI-NEXT:    v_or_b32_e32 v1, v1, v48
; SI-NEXT:    v_lshlrev_b32_e32 v39, 16, v39
; SI-NEXT:    v_lshlrev_b32_e32 v38, 16, v38
; SI-NEXT:    v_lshlrev_b32_e32 v37, 16, v37
; SI-NEXT:    v_lshlrev_b32_e32 v36, 16, v36
; SI-NEXT:    v_lshlrev_b32_e32 v35, 16, v35
; SI-NEXT:    v_lshlrev_b32_e32 v33, 16, v33
; SI-NEXT:    v_lshlrev_b32_e32 v32, 16, v32
; SI-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; SI-NEXT:    v_lshlrev_b32_e32 v26, 16, v26
; SI-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; SI-NEXT:    v_or_b32_e32 v0, v0, v39
; SI-NEXT:    v_or_b32_e32 v2, v2, v38
; SI-NEXT:    v_or_b32_e32 v4, v4, v37
; SI-NEXT:    v_or_b32_e32 v6, v6, v36
; SI-NEXT:    v_or_b32_e32 v8, v8, v35
; SI-NEXT:    v_or_b32_e32 v10, v10, v33
; SI-NEXT:    v_or_b32_e32 v12, v12, v32
; SI-NEXT:    v_or_b32_e32 v14, v14, v29
; SI-NEXT:    v_or_b32_e32 v16, v16, v26
; SI-NEXT:    v_or_b32_e32 v18, v18, v24
; SI-NEXT:    v_alignbit_b32 v39, v1, v39, 16
; SI-NEXT:    v_alignbit_b32 v38, v3, v38, 16
; SI-NEXT:    v_alignbit_b32 v37, v5, v37, 16
; SI-NEXT:    v_alignbit_b32 v36, v7, v36, 16
; SI-NEXT:    v_alignbit_b32 v35, v9, v35, 16
; SI-NEXT:    v_alignbit_b32 v33, v11, v33, 16
; SI-NEXT:    v_alignbit_b32 v32, v13, v32, 16
; SI-NEXT:    v_alignbit_b32 v29, v15, v29, 16
; SI-NEXT:    v_alignbit_b32 v26, v17, v26, 16
; SI-NEXT:    v_alignbit_b32 v24, v19, v24, 16
; SI-NEXT:  .LBB58_2: ; %end
; SI-NEXT:    s_or_b64 exec, exec, s[4:5]
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; SI-NEXT:    v_or_b32_e32 v3, v3, v20
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v37
; SI-NEXT:    v_or_b32_e32 v4, v4, v20
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v31
; SI-NEXT:    v_or_b32_e32 v5, v5, v20
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v36
; SI-NEXT:    v_or_b32_e32 v6, v6, v20
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v30
; SI-NEXT:    v_or_b32_e32 v7, v7, v20
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v35
; SI-NEXT:    v_or_b32_e32 v8, v8, v20
; SI-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v28
; SI-NEXT:    v_or_b32_e32 v9, v9, v20
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v33
; SI-NEXT:    v_or_b32_e32 v10, v10, v20
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v27
; SI-NEXT:    v_or_b32_e32 v11, v11, v20
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v32
; SI-NEXT:    v_or_b32_e32 v12, v12, v20
; SI-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v25
; SI-NEXT:    v_or_b32_e32 v13, v13, v20
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v29
; SI-NEXT:    v_or_b32_e32 v14, v14, v20
; SI-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v23
; SI-NEXT:    v_or_b32_e32 v15, v15, v20
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v16
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v26
; SI-NEXT:    v_or_b32_e32 v16, v16, v20
; SI-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v22
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v34, 16, v34
; SI-NEXT:    v_or_b32_e32 v17, v17, v20
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v24
; SI-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; SI-NEXT:    v_lshlrev_b32_e32 v39, 16, v39
; SI-NEXT:    v_or_b32_e32 v1, v1, v34
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; SI-NEXT:    v_lshlrev_b32_e32 v34, 16, v38
; SI-NEXT:    v_or_b32_e32 v18, v18, v20
; SI-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v21
; SI-NEXT:    v_or_b32_e32 v0, v0, v39
; SI-NEXT:    v_or_b32_e32 v2, v2, v34
; SI-NEXT:    v_or_b32_e32 v19, v19, v20
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v40f16_to_v40i16:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_lshrrev_b32_e32 v21, 16, v19
; VI-NEXT:    v_lshrrev_b32_e32 v22, 16, v18
; VI-NEXT:    v_lshrrev_b32_e32 v23, 16, v17
; VI-NEXT:    v_lshrrev_b32_e32 v24, 16, v16
; VI-NEXT:    v_lshrrev_b32_e32 v25, 16, v15
; VI-NEXT:    v_lshrrev_b32_e32 v26, 16, v14
; VI-NEXT:    v_lshrrev_b32_e32 v27, 16, v13
; VI-NEXT:    v_lshrrev_b32_e32 v28, 16, v12
; VI-NEXT:    v_lshrrev_b32_e32 v29, 16, v11
; VI-NEXT:    v_lshrrev_b32_e32 v30, 16, v10
; VI-NEXT:    v_lshrrev_b32_e32 v31, 16, v9
; VI-NEXT:    v_lshrrev_b32_e32 v32, 16, v8
; VI-NEXT:    v_lshrrev_b32_e32 v33, 16, v7
; VI-NEXT:    v_lshrrev_b32_e32 v34, 16, v6
; VI-NEXT:    v_lshrrev_b32_e32 v35, 16, v5
; VI-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; VI-NEXT:    v_lshrrev_b32_e32 v20, 16, v4
; VI-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; VI-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; VI-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; VI-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; VI-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; VI-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; VI-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; VI-NEXT:    s_cbranch_execz .LBB58_2
; VI-NEXT:  ; %bb.1: ; %cmp.true
; VI-NEXT:    v_add_f16_e32 v0, 0x200, v0
; VI-NEXT:    v_add_f16_e32 v39, 0x200, v39
; VI-NEXT:    v_add_f16_e32 v1, 0x200, v1
; VI-NEXT:    v_add_f16_e32 v38, 0x200, v38
; VI-NEXT:    v_add_f16_e32 v2, 0x200, v2
; VI-NEXT:    v_add_f16_e32 v37, 0x200, v37
; VI-NEXT:    v_add_f16_e32 v3, 0x200, v3
; VI-NEXT:    v_add_f16_e32 v36, 0x200, v36
; VI-NEXT:    v_add_f16_e32 v4, 0x200, v4
; VI-NEXT:    v_add_f16_e32 v20, 0x200, v20
; VI-NEXT:    v_add_f16_e32 v5, 0x200, v5
; VI-NEXT:    v_add_f16_e32 v35, 0x200, v35
; VI-NEXT:    v_add_f16_e32 v6, 0x200, v6
; VI-NEXT:    v_add_f16_e32 v34, 0x200, v34
; VI-NEXT:    v_add_f16_e32 v7, 0x200, v7
; VI-NEXT:    v_add_f16_e32 v33, 0x200, v33
; VI-NEXT:    v_add_f16_e32 v8, 0x200, v8
; VI-NEXT:    v_add_f16_e32 v32, 0x200, v32
; VI-NEXT:    v_add_f16_e32 v9, 0x200, v9
; VI-NEXT:    v_add_f16_e32 v31, 0x200, v31
; VI-NEXT:    v_add_f16_e32 v10, 0x200, v10
; VI-NEXT:    v_add_f16_e32 v30, 0x200, v30
; VI-NEXT:    v_add_f16_e32 v11, 0x200, v11
; VI-NEXT:    v_add_f16_e32 v29, 0x200, v29
; VI-NEXT:    v_add_f16_e32 v12, 0x200, v12
; VI-NEXT:    v_add_f16_e32 v28, 0x200, v28
; VI-NEXT:    v_add_f16_e32 v13, 0x200, v13
; VI-NEXT:    v_add_f16_e32 v27, 0x200, v27
; VI-NEXT:    v_add_f16_e32 v14, 0x200, v14
; VI-NEXT:    v_add_f16_e32 v26, 0x200, v26
; VI-NEXT:    v_add_f16_e32 v15, 0x200, v15
; VI-NEXT:    v_add_f16_e32 v25, 0x200, v25
; VI-NEXT:    v_add_f16_e32 v16, 0x200, v16
; VI-NEXT:    v_add_f16_e32 v24, 0x200, v24
; VI-NEXT:    v_add_f16_e32 v17, 0x200, v17
; VI-NEXT:    v_add_f16_e32 v23, 0x200, v23
; VI-NEXT:    v_add_f16_e32 v18, 0x200, v18
; VI-NEXT:    v_add_f16_e32 v22, 0x200, v22
; VI-NEXT:    v_add_f16_e32 v19, 0x200, v19
; VI-NEXT:    v_add_f16_e32 v21, 0x200, v21
; VI-NEXT:  .LBB58_2: ; %end
; VI-NEXT:    s_or_b64 exec, exec, s[4:5]
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; VI-NEXT:    v_or_b32_sdwa v4, v4, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v35
; VI-NEXT:    v_or_b32_sdwa v5, v5, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v34
; VI-NEXT:    v_or_b32_sdwa v6, v6, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v33
; VI-NEXT:    v_or_b32_sdwa v7, v7, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v32
; VI-NEXT:    v_or_b32_sdwa v8, v8, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v31
; VI-NEXT:    v_or_b32_sdwa v9, v9, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v30
; VI-NEXT:    v_or_b32_sdwa v10, v10, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v29
; VI-NEXT:    v_or_b32_sdwa v11, v11, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v28
; VI-NEXT:    v_or_b32_sdwa v12, v12, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v27
; VI-NEXT:    v_or_b32_sdwa v13, v13, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v26
; VI-NEXT:    v_or_b32_sdwa v14, v14, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v25
; VI-NEXT:    v_or_b32_sdwa v15, v15, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v24
; VI-NEXT:    v_or_b32_sdwa v16, v16, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v23
; VI-NEXT:    v_or_b32_sdwa v17, v17, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v22
; VI-NEXT:    v_lshlrev_b32_e32 v39, 16, v39
; VI-NEXT:    v_lshlrev_b32_e32 v38, 16, v38
; VI-NEXT:    v_lshlrev_b32_e32 v37, 16, v37
; VI-NEXT:    v_lshlrev_b32_e32 v36, 16, v36
; VI-NEXT:    v_or_b32_sdwa v18, v18, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v21
; VI-NEXT:    v_or_b32_sdwa v0, v0, v39 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v1, v1, v38 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v2, v2, v37 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v3, v3, v36 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v19, v19, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v40f16_to_v40i16:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_lshrrev_b32_e32 v39, 16, v19
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 16, v18
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v15
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v14
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v13
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 16, v11
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v28, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v27, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v24, 16, v5
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v20
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v2
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v20, 16, v0
; GFX9-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX9-NEXT:    s_xor_b64 s[4:5], exec, s[4:5]
; GFX9-NEXT:    s_andn2_saveexec_b64 s[4:5], s[4:5]
; GFX9-NEXT:    s_cbranch_execz .LBB58_2
; GFX9-NEXT:  ; %bb.1: ; %cmp.true
; GFX9-NEXT:    s_mov_b32 s6, 0x5040100
; GFX9-NEXT:    v_perm_b32 v19, v39, v19, s6
; GFX9-NEXT:    v_perm_b32 v18, v38, v18, s6
; GFX9-NEXT:    v_perm_b32 v17, v37, v17, s6
; GFX9-NEXT:    v_perm_b32 v16, v36, v16, s6
; GFX9-NEXT:    v_perm_b32 v15, v35, v15, s6
; GFX9-NEXT:    v_perm_b32 v14, v34, v14, s6
; GFX9-NEXT:    v_perm_b32 v13, v33, v13, s6
; GFX9-NEXT:    v_perm_b32 v12, v32, v12, s6
; GFX9-NEXT:    v_perm_b32 v11, v31, v11, s6
; GFX9-NEXT:    v_perm_b32 v10, v30, v10, s6
; GFX9-NEXT:    v_perm_b32 v9, v29, v9, s6
; GFX9-NEXT:    s_movk_i32 s7, 0x200
; GFX9-NEXT:    v_perm_b32 v8, v28, v8, s6
; GFX9-NEXT:    v_perm_b32 v7, v27, v7, s6
; GFX9-NEXT:    v_perm_b32 v6, v26, v6, s6
; GFX9-NEXT:    v_perm_b32 v5, v24, v5, s6
; GFX9-NEXT:    v_perm_b32 v4, v25, v4, s6
; GFX9-NEXT:    v_perm_b32 v3, v23, v3, s6
; GFX9-NEXT:    v_perm_b32 v2, v22, v2, s6
; GFX9-NEXT:    v_perm_b32 v1, v21, v1, s6
; GFX9-NEXT:    v_perm_b32 v0, v20, v0, s6
; GFX9-NEXT:    v_pk_add_f16 v19, v19, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v18, v18, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v17, v17, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v16, v16, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v15, v15, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v14, v14, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v13, v13, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v12, v12, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v11, v11, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v10, v10, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v9, v9, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v8, v8, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v7, v7, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v6, v6, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v5, v5, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v4, v4, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v3, v3, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v2, v2, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v1, v1, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_pk_add_f16 v0, v0, s7 op_sel_hi:[1,0]
; GFX9-NEXT:    v_lshrrev_b32_e32 v20, 16, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v2
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v24, 16, v5
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v27, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v28, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 16, v11
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v13
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v14
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v15
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 16, v18
; GFX9-NEXT:    v_lshrrev_b32_e32 v39, 16, v19
; GFX9-NEXT:  .LBB58_2: ; %end
; GFX9-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX9-NEXT:    s_mov_b32 s4, 0x5040100
; GFX9-NEXT:    v_perm_b32 v0, v20, v0, s4
; GFX9-NEXT:    v_perm_b32 v1, v21, v1, s4
; GFX9-NEXT:    v_perm_b32 v2, v22, v2, s4
; GFX9-NEXT:    v_perm_b32 v3, v23, v3, s4
; GFX9-NEXT:    v_perm_b32 v4, v25, v4, s4
; GFX9-NEXT:    v_perm_b32 v5, v24, v5, s4
; GFX9-NEXT:    v_perm_b32 v6, v26, v6, s4
; GFX9-NEXT:    v_perm_b32 v7, v27, v7, s4
; GFX9-NEXT:    v_perm_b32 v8, v28, v8, s4
; GFX9-NEXT:    v_perm_b32 v9, v29, v9, s4
; GFX9-NEXT:    v_perm_b32 v10, v30, v10, s4
; GFX9-NEXT:    v_perm_b32 v11, v31, v11, s4
; GFX9-NEXT:    v_perm_b32 v12, v32, v12, s4
; GFX9-NEXT:    v_perm_b32 v13, v33, v13, s4
; GFX9-NEXT:    v_perm_b32 v14, v34, v14, s4
; GFX9-NEXT:    v_perm_b32 v15, v35, v15, s4
; GFX9-NEXT:    v_perm_b32 v16, v36, v16, s4
; GFX9-NEXT:    v_perm_b32 v17, v37, v17, s4
; GFX9-NEXT:    v_perm_b32 v18, v38, v18, s4
; GFX9-NEXT:    v_perm_b32 v19, v39, v19, s4
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v40f16_to_v40i16:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-TRUE16-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-TRUE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-TRUE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-TRUE16-NEXT:    s_cbranch_execz .LBB58_2
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v19, 0x200, v19 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v18, 0x200, v18 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v17, 0x200, v17 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v16, 0x200, v16 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v15, 0x200, v15 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v14, 0x200, v14 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v13, 0x200, v13 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v12, 0x200, v12 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v11, 0x200, v11 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v10, 0x200, v10 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v9, 0x200, v9 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v8, 0x200, v8 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v7, 0x200, v7 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v6, 0x200, v6 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v5, 0x200, v5 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v4, 0x200, v4 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v3, 0x200, v3 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v2, 0x200, v2 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v1, 0x200, v1 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v0, 0x200, v0 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:  .LBB58_2: ; %end
; GFX11-TRUE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v40f16_to_v40i16:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v48, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v3
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v0
; GFX11-FAKE16-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-FAKE16-NEXT:    v_cmpx_ne_u32_e32 0, v20
; GFX11-FAKE16-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX11-FAKE16-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-FAKE16-NEXT:    s_and_not1_saveexec_b32 s0, s0
; GFX11-FAKE16-NEXT:    s_cbranch_execz .LBB58_2
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %cmp.true
; GFX11-FAKE16-NEXT:    v_perm_b32 v19, v48, v19, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v18, v39, v18, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v17, v38, v17, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v16, v37, v16, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v15, v36, v15, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v14, v35, v14, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, v34, v13, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, v33, v12, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, v32, v11, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, v31, v10, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, v30, v9, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, v29, v8, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v28, v7, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v27, v6, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v26, v5, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v21, v0, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v22, v1, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v23, v2, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v24, v3, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v25, v4, 0x5040100
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v19, 0x200, v19 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v18, 0x200, v18 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v17, 0x200, v17 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v16, 0x200, v16 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v15, 0x200, v15 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v14, 0x200, v14 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v13, 0x200, v13 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v12, 0x200, v12 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v11, 0x200, v11 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v10, 0x200, v10 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v9, 0x200, v9 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v8, 0x200, v8 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v7, 0x200, v7 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v6, 0x200, v6 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v5, 0x200, v5 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v0, 0x200, v0 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v1, 0x200, v1 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v2, 0x200, v2 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v3, 0x200, v3 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v4, 0x200, v4 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v3
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v15
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v48, 16, v19
; GFX11-FAKE16-NEXT:  .LBB58_2: ; %end
; GFX11-FAKE16-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX11-FAKE16-NEXT:    v_perm_b32 v0, v21, v0, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v1, v22, v1, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v2, v23, v2, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v3, v24, v3, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v4, v25, v4, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v5, v26, v5, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v6, v27, v6, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v7, v28, v7, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v8, v29, v8, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v9, v30, v9, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v10, v31, v10, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v11, v32, v11, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v12, v33, v12, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v13, v34, v13, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v14, v35, v14, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v15, v36, v15, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v16, v37, v16, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v17, v38, v17, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v18, v39, v18, 0x5040100
; GFX11-FAKE16-NEXT:    v_perm_b32 v19, v48, v19, 0x5040100
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <40 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <40 x half> %a1 to <40 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <40 x half> %a to <40 x i16>
  br label %end

end:
  %phi = phi <40 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <40 x i16> %phi
}

define inreg <40 x i16> @bitcast_v40f16_to_v40i16_scalar(<40 x half> inreg %a, i32 inreg %b) #0 {
; SI-LABEL: bitcast_v40f16_to_v40i16_scalar:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:44 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:40 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v42, off, s[0:3], s32 offset:36 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v43, off, s[0:3], s32 offset:32 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v44, off, s[0:3], s32 offset:28 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v45, off, s[0:3], s32 offset:24 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v46, off, s[0:3], s32 offset:20 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v47, off, s[0:3], s32 offset:16 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v56, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v57, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v58, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; SI-NEXT:    buffer_store_dword v59, off, s[0:3], s32 ; 4-byte Folded Spill
; SI-NEXT:    v_readfirstlane_b32 s9, v5
; SI-NEXT:    v_readfirstlane_b32 s6, v4
; SI-NEXT:    v_readfirstlane_b32 s10, v3
; SI-NEXT:    v_readfirstlane_b32 s7, v2
; SI-NEXT:    v_readfirstlane_b32 s41, v1
; SI-NEXT:    v_readfirstlane_b32 s8, v0
; SI-NEXT:    s_lshr_b32 s42, s29, 16
; SI-NEXT:    s_lshr_b32 s46, s28, 16
; SI-NEXT:    s_lshr_b32 s40, s27, 16
; SI-NEXT:    s_lshr_b32 s57, s26, 16
; SI-NEXT:    s_lshr_b32 s15, s25, 16
; SI-NEXT:    s_lshr_b32 s59, s24, 16
; SI-NEXT:    s_lshr_b32 s14, s23, 16
; SI-NEXT:    s_lshr_b32 s60, s22, 16
; SI-NEXT:    s_lshr_b32 s13, s21, 16
; SI-NEXT:    s_lshr_b32 s61, s20, 16
; SI-NEXT:    s_lshr_b32 s12, s19, 16
; SI-NEXT:    s_lshr_b32 s62, s18, 16
; SI-NEXT:    s_lshr_b32 s11, s17, 16
; SI-NEXT:    s_lshr_b32 s63, s16, 16
; SI-NEXT:    s_lshr_b32 s58, s9, 16
; SI-NEXT:    s_lshr_b32 s44, s6, 16
; SI-NEXT:    s_lshr_b32 s43, s10, 16
; SI-NEXT:    s_lshr_b32 s45, s7, 16
; SI-NEXT:    s_lshr_b32 s47, s41, 16
; SI-NEXT:    s_lshr_b32 s56, s8, 16
; SI-NEXT:    v_readfirstlane_b32 s4, v6
; SI-NEXT:    s_cmp_lg_u32 s4, 0
; SI-NEXT:    s_cbranch_scc0 .LBB59_3
; SI-NEXT:  ; %bb.1: ; %cmp.false
; SI-NEXT:    s_cbranch_execnz .LBB59_4
; SI-NEXT:  .LBB59_2: ; %cmp.true
; SI-NEXT:    v_cvt_f32_f16_e32 v0, s63
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s16
; SI-NEXT:    v_cvt_f32_f16_e32 v2, s62
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s18
; SI-NEXT:    v_add_f32_e32 v0, 0x38000000, v0
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v0, v0
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_add_f32_e32 v2, 0x38000000, v2
; SI-NEXT:    v_cvt_f16_f32_e32 v2, v2
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; SI-NEXT:    v_or_b32_e32 v48, v1, v0
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s61
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v5, s20
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v2
; SI-NEXT:    v_or_b32_e32 v49, v3, v2
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v5
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s60
; SI-NEXT:    v_cvt_f16_f32_e32 v20, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s59
; SI-NEXT:    v_cvt_f32_f16_e32 v5, s22
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v21, 0x38000000, v5
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s57
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s46
; SI-NEXT:    v_cvt_f32_f16_e32 v5, s56
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v7, s45
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v1
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v7
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s44
; SI-NEXT:    v_cvt_f16_f32_e32 v16, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s58
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v5, s47
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v18, v3
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v50, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s41
; SI-NEXT:    v_cvt_f32_f16_e32 v5, s42
; SI-NEXT:    v_cvt_f32_f16_e32 v7, s29
; SI-NEXT:    v_cvt_f16_f32_e32 v51, v3
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_cvt_f16_f32_e32 v52, v5
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v51
; SI-NEXT:    v_or_b32_e32 v15, v1, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s40
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v52
; SI-NEXT:    v_or_b32_e32 v13, v5, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s27
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v5, s15
; SI-NEXT:    v_cvt_f16_f32_e32 v53, v1
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v54, v3
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v53
; SI-NEXT:    v_cvt_f32_f16_e32 v5, s25
; SI-NEXT:    v_or_b32_e32 v11, v1, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s14
; SI-NEXT:    v_cvt_f32_f16_e32 v7, s23
; SI-NEXT:    v_add_f32_e32 v5, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v5, v5
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v55, v3
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v7
; SI-NEXT:    v_cvt_f16_f32_e32 v3, v3
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v54
; SI-NEXT:    v_or_b32_e32 v9, v5, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v1, s13
; SI-NEXT:    v_lshlrev_b32_e32 v5, 16, v55
; SI-NEXT:    v_or_b32_e32 v7, v3, v5
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s21
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v5, s12
; SI-NEXT:    v_cvt_f16_f32_e32 v41, v1
; SI-NEXT:    v_add_f32_e32 v1, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v1, v1
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v5
; SI-NEXT:    v_cvt_f16_f32_e32 v42, v3
; SI-NEXT:    v_lshlrev_b32_e32 v3, 16, v41
; SI-NEXT:    v_cvt_f32_f16_e32 v19, s19
; SI-NEXT:    v_or_b32_e32 v5, v1, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v3, s11
; SI-NEXT:    v_cvt_f32_f16_e32 v23, s17
; SI-NEXT:    v_add_f32_e32 v19, 0x38000000, v19
; SI-NEXT:    v_cvt_f16_f32_e32 v19, v19
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v3
; SI-NEXT:    v_cvt_f16_f32_e32 v43, v3
; SI-NEXT:    v_add_f32_e32 v3, 0x38000000, v23
; SI-NEXT:    v_cvt_f16_f32_e32 v23, v3
; SI-NEXT:    v_cvt_f32_f16_e32 v17, s43
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v42
; SI-NEXT:    v_or_b32_e32 v3, v19, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v19, s10
; SI-NEXT:    v_lshlrev_b32_e32 v1, 16, v43
; SI-NEXT:    v_or_b32_e32 v1, v23, v1
; SI-NEXT:    v_cvt_f32_f16_e32 v23, s9
; SI-NEXT:    v_add_f32_e32 v17, 0x38000000, v17
; SI-NEXT:    v_cvt_f16_f32_e32 v40, v17
; SI-NEXT:    v_add_f32_e32 v17, 0x38000000, v19
; SI-NEXT:    v_cvt_f16_f32_e32 v17, v17
; SI-NEXT:    v_add_f32_e32 v19, 0x38000000, v23
; SI-NEXT:    v_cvt_f16_f32_e32 v19, v19
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v40
; SI-NEXT:    v_or_b32_e32 v17, v17, v23
; SI-NEXT:    v_lshlrev_b32_e32 v23, 16, v50
; SI-NEXT:    v_cvt_f32_f16_e32 v22, s24
; SI-NEXT:    v_or_b32_e32 v19, v19, v23
; SI-NEXT:    v_cvt_f32_f16_e32 v23, s26
; SI-NEXT:    v_cvt_f16_f32_e32 v21, v21
; SI-NEXT:    v_add_f32_e32 v22, 0x38000000, v22
; SI-NEXT:    v_cvt_f16_f32_e32 v22, v22
; SI-NEXT:    v_add_f32_e32 v23, 0x38000000, v23
; SI-NEXT:    v_cvt_f16_f32_e32 v23, v23
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_or_b32_e32 v59, v20, v4
; SI-NEXT:    v_or_b32_e32 v57, v21, v6
; SI-NEXT:    v_cvt_f32_f16_e32 v20, s28
; SI-NEXT:    v_or_b32_e32 v56, v22, v8
; SI-NEXT:    v_or_b32_e32 v46, v23, v10
; SI-NEXT:    v_cvt_f32_f16_e32 v21, s8
; SI-NEXT:    v_cvt_f32_f16_e32 v22, s7
; SI-NEXT:    v_cvt_f32_f16_e32 v23, s6
; SI-NEXT:    v_add_f32_e32 v20, 0x38000000, v20
; SI-NEXT:    v_add_f32_e32 v21, 0x38000000, v21
; SI-NEXT:    v_add_f32_e32 v22, 0x38000000, v22
; SI-NEXT:    v_add_f32_e32 v23, 0x38000000, v23
; SI-NEXT:    v_cvt_f16_f32_e32 v20, v20
; SI-NEXT:    v_cvt_f16_f32_e32 v21, v21
; SI-NEXT:    v_cvt_f16_f32_e32 v22, v22
; SI-NEXT:    v_cvt_f16_f32_e32 v23, v23
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v16
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v18
; SI-NEXT:    v_or_b32_e32 v58, v20, v12
; SI-NEXT:    v_or_b32_e32 v47, v21, v14
; SI-NEXT:    v_or_b32_e32 v45, v22, v16
; SI-NEXT:    v_or_b32_e32 v44, v23, v18
; SI-NEXT:    v_lshr_b64 v[38:39], v[0:1], 16
; SI-NEXT:    v_lshr_b64 v[36:37], v[2:3], 16
; SI-NEXT:    v_lshr_b64 v[34:35], v[4:5], 16
; SI-NEXT:    v_lshr_b64 v[32:33], v[6:7], 16
; SI-NEXT:    v_lshr_b64 v[30:31], v[8:9], 16
; SI-NEXT:    v_lshr_b64 v[28:29], v[10:11], 16
; SI-NEXT:    v_lshr_b64 v[26:27], v[12:13], 16
; SI-NEXT:    v_lshr_b64 v[24:25], v[14:15], 16
; SI-NEXT:    v_lshr_b64 v[22:23], v[16:17], 16
; SI-NEXT:    v_lshr_b64 v[20:21], v[18:19], 16
; SI-NEXT:    s_branch .LBB59_5
; SI-NEXT:  .LBB59_3:
; SI-NEXT:    s_branch .LBB59_2
; SI-NEXT:  .LBB59_4:
; SI-NEXT:    v_mov_b32_e32 v50, s58
; SI-NEXT:    v_mov_b32_e32 v40, s43
; SI-NEXT:    v_mov_b32_e32 v51, s47
; SI-NEXT:    v_mov_b32_e32 v52, s42
; SI-NEXT:    v_mov_b32_e32 v53, s40
; SI-NEXT:    v_mov_b32_e32 v54, s15
; SI-NEXT:    v_mov_b32_e32 v55, s14
; SI-NEXT:    v_mov_b32_e32 v41, s13
; SI-NEXT:    v_mov_b32_e32 v42, s12
; SI-NEXT:    v_mov_b32_e32 v43, s11
; SI-NEXT:    v_mov_b32_e32 v44, s6
; SI-NEXT:    s_waitcnt expcnt(6)
; SI-NEXT:    v_mov_b32_e32 v45, s7
; SI-NEXT:    s_waitcnt expcnt(4)
; SI-NEXT:    v_mov_b32_e32 v47, s8
; SI-NEXT:    s_waitcnt expcnt(1)
; SI-NEXT:    v_mov_b32_e32 v58, s28
; SI-NEXT:    v_mov_b32_e32 v46, s26
; SI-NEXT:    v_mov_b32_e32 v56, s24
; SI-NEXT:    v_mov_b32_e32 v57, s22
; SI-NEXT:    s_waitcnt expcnt(0)
; SI-NEXT:    v_mov_b32_e32 v59, s20
; SI-NEXT:    v_mov_b32_e32 v49, s18
; SI-NEXT:    v_mov_b32_e32 v48, s16
; SI-NEXT:    v_mov_b32_e32 v1, s17
; SI-NEXT:    v_mov_b32_e32 v3, s19
; SI-NEXT:    v_mov_b32_e32 v5, s21
; SI-NEXT:    v_mov_b32_e32 v7, s23
; SI-NEXT:    v_mov_b32_e32 v9, s25
; SI-NEXT:    v_mov_b32_e32 v11, s27
; SI-NEXT:    v_mov_b32_e32 v13, s29
; SI-NEXT:    v_mov_b32_e32 v15, s41
; SI-NEXT:    v_mov_b32_e32 v17, s10
; SI-NEXT:    v_mov_b32_e32 v19, s9
; SI-NEXT:    v_mov_b32_e32 v38, s63
; SI-NEXT:    v_mov_b32_e32 v36, s62
; SI-NEXT:    v_mov_b32_e32 v34, s61
; SI-NEXT:    v_mov_b32_e32 v32, s60
; SI-NEXT:    v_mov_b32_e32 v30, s59
; SI-NEXT:    v_mov_b32_e32 v28, s57
; SI-NEXT:    v_mov_b32_e32 v26, s46
; SI-NEXT:    v_mov_b32_e32 v24, s56
; SI-NEXT:    v_mov_b32_e32 v22, s45
; SI-NEXT:    v_mov_b32_e32 v20, s44
; SI-NEXT:  .LBB59_5: ; %end
; SI-NEXT:    v_lshlrev_b32_e32 v0, 16, v38
; SI-NEXT:    v_and_b32_e32 v2, 0xffff, v48
; SI-NEXT:    v_or_b32_e32 v0, v2, v0
; SI-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v43
; SI-NEXT:    v_or_b32_e32 v1, v1, v2
; SI-NEXT:    v_lshlrev_b32_e32 v2, 16, v36
; SI-NEXT:    v_and_b32_e32 v4, 0xffff, v49
; SI-NEXT:    v_or_b32_e32 v2, v4, v2
; SI-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v42
; SI-NEXT:    v_or_b32_e32 v3, v3, v4
; SI-NEXT:    v_lshlrev_b32_e32 v4, 16, v34
; SI-NEXT:    v_and_b32_e32 v6, 0xffff, v59
; SI-NEXT:    v_or_b32_e32 v4, v6, v4
; SI-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v41
; SI-NEXT:    v_or_b32_e32 v5, v5, v6
; SI-NEXT:    v_lshlrev_b32_e32 v6, 16, v32
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v57
; SI-NEXT:    v_or_b32_e32 v6, v8, v6
; SI-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; SI-NEXT:    v_lshlrev_b32_e32 v8, 16, v55
; SI-NEXT:    v_or_b32_e32 v7, v7, v8
; SI-NEXT:    v_and_b32_e32 v8, 0xffff, v56
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v30
; SI-NEXT:    v_or_b32_e32 v8, v8, v10
; SI-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; SI-NEXT:    v_lshlrev_b32_e32 v10, 16, v54
; SI-NEXT:    v_or_b32_e32 v9, v9, v10
; SI-NEXT:    v_and_b32_e32 v10, 0xffff, v46
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v28
; SI-NEXT:    v_or_b32_e32 v10, v10, v12
; SI-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; SI-NEXT:    v_lshlrev_b32_e32 v12, 16, v53
; SI-NEXT:    v_or_b32_e32 v11, v11, v12
; SI-NEXT:    v_and_b32_e32 v12, 0xffff, v58
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v26
; SI-NEXT:    v_or_b32_e32 v12, v12, v14
; SI-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; SI-NEXT:    v_lshlrev_b32_e32 v14, 16, v52
; SI-NEXT:    v_or_b32_e32 v13, v13, v14
; SI-NEXT:    v_and_b32_e32 v14, 0xffff, v47
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v24
; SI-NEXT:    v_or_b32_e32 v14, v14, v16
; SI-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; SI-NEXT:    v_lshlrev_b32_e32 v16, 16, v51
; SI-NEXT:    v_or_b32_e32 v15, v15, v16
; SI-NEXT:    v_and_b32_e32 v16, 0xffff, v45
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v22
; SI-NEXT:    v_or_b32_e32 v16, v16, v18
; SI-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; SI-NEXT:    v_lshlrev_b32_e32 v18, 16, v40
; SI-NEXT:    v_or_b32_e32 v17, v17, v18
; SI-NEXT:    v_and_b32_e32 v18, 0xffff, v44
; SI-NEXT:    buffer_load_dword v59, off, s[0:3], s32 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v58, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v57, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v56, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v47, off, s[0:3], s32 offset:16 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v46, off, s[0:3], s32 offset:20 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v45, off, s[0:3], s32 offset:24 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v44, off, s[0:3], s32 offset:28 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v43, off, s[0:3], s32 offset:32 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v42, off, s[0:3], s32 offset:36 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:40 ; 4-byte Folded Reload
; SI-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:44 ; 4-byte Folded Reload
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; SI-NEXT:    v_or_b32_e32 v18, v18, v20
; SI-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; SI-NEXT:    v_lshlrev_b32_e32 v20, 16, v50
; SI-NEXT:    v_or_b32_e32 v19, v19, v20
; SI-NEXT:    s_waitcnt vmcnt(0)
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: bitcast_v40f16_to_v40i16_scalar:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    v_readfirstlane_b32 s44, v5
; VI-NEXT:    v_readfirstlane_b32 s46, v4
; VI-NEXT:    v_readfirstlane_b32 s56, v3
; VI-NEXT:    v_readfirstlane_b32 s58, v2
; VI-NEXT:    v_readfirstlane_b32 s60, v1
; VI-NEXT:    v_readfirstlane_b32 s62, v0
; VI-NEXT:    s_lshr_b32 s6, s29, 16
; VI-NEXT:    s_lshr_b32 s7, s28, 16
; VI-NEXT:    s_lshr_b32 s8, s27, 16
; VI-NEXT:    s_lshr_b32 s9, s26, 16
; VI-NEXT:    s_lshr_b32 s10, s25, 16
; VI-NEXT:    s_lshr_b32 s11, s24, 16
; VI-NEXT:    s_lshr_b32 s12, s23, 16
; VI-NEXT:    s_lshr_b32 s13, s22, 16
; VI-NEXT:    s_lshr_b32 s14, s21, 16
; VI-NEXT:    s_lshr_b32 s15, s20, 16
; VI-NEXT:    s_lshr_b32 s40, s19, 16
; VI-NEXT:    s_lshr_b32 s41, s18, 16
; VI-NEXT:    s_lshr_b32 s42, s17, 16
; VI-NEXT:    s_lshr_b32 s43, s16, 16
; VI-NEXT:    s_lshr_b32 s45, s44, 16
; VI-NEXT:    s_lshr_b32 s47, s46, 16
; VI-NEXT:    s_lshr_b32 s57, s56, 16
; VI-NEXT:    s_lshr_b32 s59, s58, 16
; VI-NEXT:    s_lshr_b32 s61, s60, 16
; VI-NEXT:    s_lshr_b32 s63, s62, 16
; VI-NEXT:    v_readfirstlane_b32 s4, v6
; VI-NEXT:    s_cmp_lg_u32 s4, 0
; VI-NEXT:    s_cbranch_scc0 .LBB59_3
; VI-NEXT:  ; %bb.1: ; %cmp.false
; VI-NEXT:    s_cbranch_execnz .LBB59_4
; VI-NEXT:  .LBB59_2: ; %cmp.true
; VI-NEXT:    v_mov_b32_e32 v20, 0x200
; VI-NEXT:    v_add_f16_e32 v0, s16, v20
; VI-NEXT:    v_add_f16_e32 v39, s43, v20
; VI-NEXT:    v_add_f16_e32 v1, s17, v20
; VI-NEXT:    v_add_f16_e32 v38, s42, v20
; VI-NEXT:    v_add_f16_e32 v2, s18, v20
; VI-NEXT:    v_add_f16_e32 v37, s41, v20
; VI-NEXT:    v_add_f16_e32 v3, s19, v20
; VI-NEXT:    v_add_f16_e32 v36, s40, v20
; VI-NEXT:    v_add_f16_e32 v4, s20, v20
; VI-NEXT:    v_add_f16_e32 v35, s15, v20
; VI-NEXT:    v_add_f16_e32 v5, s21, v20
; VI-NEXT:    v_add_f16_e32 v34, s14, v20
; VI-NEXT:    v_add_f16_e32 v6, s22, v20
; VI-NEXT:    v_add_f16_e32 v33, s13, v20
; VI-NEXT:    v_add_f16_e32 v7, s23, v20
; VI-NEXT:    v_add_f16_e32 v32, s12, v20
; VI-NEXT:    v_add_f16_e32 v8, s24, v20
; VI-NEXT:    v_add_f16_e32 v31, s11, v20
; VI-NEXT:    v_add_f16_e32 v9, s25, v20
; VI-NEXT:    v_add_f16_e32 v30, s10, v20
; VI-NEXT:    v_add_f16_e32 v10, s26, v20
; VI-NEXT:    v_add_f16_e32 v29, s9, v20
; VI-NEXT:    v_add_f16_e32 v11, s27, v20
; VI-NEXT:    v_add_f16_e32 v28, s8, v20
; VI-NEXT:    v_add_f16_e32 v12, s28, v20
; VI-NEXT:    v_add_f16_e32 v27, s7, v20
; VI-NEXT:    v_add_f16_e32 v13, s29, v20
; VI-NEXT:    v_add_f16_e32 v26, s6, v20
; VI-NEXT:    v_add_f16_e32 v14, s62, v20
; VI-NEXT:    v_add_f16_e32 v25, s63, v20
; VI-NEXT:    v_add_f16_e32 v15, s60, v20
; VI-NEXT:    v_add_f16_e32 v24, s61, v20
; VI-NEXT:    v_add_f16_e32 v16, s58, v20
; VI-NEXT:    v_add_f16_e32 v23, s59, v20
; VI-NEXT:    v_add_f16_e32 v17, s56, v20
; VI-NEXT:    v_add_f16_e32 v22, s57, v20
; VI-NEXT:    v_add_f16_e32 v18, s46, v20
; VI-NEXT:    v_add_f16_e32 v21, s47, v20
; VI-NEXT:    v_add_f16_e32 v19, s44, v20
; VI-NEXT:    v_add_f16_e32 v20, s45, v20
; VI-NEXT:    s_branch .LBB59_5
; VI-NEXT:  .LBB59_3:
; VI-NEXT:    s_branch .LBB59_2
; VI-NEXT:  .LBB59_4:
; VI-NEXT:    v_mov_b32_e32 v20, s45
; VI-NEXT:    v_mov_b32_e32 v19, s44
; VI-NEXT:    v_mov_b32_e32 v21, s47
; VI-NEXT:    v_mov_b32_e32 v18, s46
; VI-NEXT:    v_mov_b32_e32 v22, s57
; VI-NEXT:    v_mov_b32_e32 v17, s56
; VI-NEXT:    v_mov_b32_e32 v23, s59
; VI-NEXT:    v_mov_b32_e32 v16, s58
; VI-NEXT:    v_mov_b32_e32 v24, s61
; VI-NEXT:    v_mov_b32_e32 v15, s60
; VI-NEXT:    v_mov_b32_e32 v25, s63
; VI-NEXT:    v_mov_b32_e32 v14, s62
; VI-NEXT:    v_mov_b32_e32 v26, s6
; VI-NEXT:    v_mov_b32_e32 v13, s29
; VI-NEXT:    v_mov_b32_e32 v27, s7
; VI-NEXT:    v_mov_b32_e32 v12, s28
; VI-NEXT:    v_mov_b32_e32 v28, s8
; VI-NEXT:    v_mov_b32_e32 v11, s27
; VI-NEXT:    v_mov_b32_e32 v29, s9
; VI-NEXT:    v_mov_b32_e32 v10, s26
; VI-NEXT:    v_mov_b32_e32 v30, s10
; VI-NEXT:    v_mov_b32_e32 v9, s25
; VI-NEXT:    v_mov_b32_e32 v31, s11
; VI-NEXT:    v_mov_b32_e32 v8, s24
; VI-NEXT:    v_mov_b32_e32 v32, s12
; VI-NEXT:    v_mov_b32_e32 v7, s23
; VI-NEXT:    v_mov_b32_e32 v33, s13
; VI-NEXT:    v_mov_b32_e32 v6, s22
; VI-NEXT:    v_mov_b32_e32 v34, s14
; VI-NEXT:    v_mov_b32_e32 v5, s21
; VI-NEXT:    v_mov_b32_e32 v35, s15
; VI-NEXT:    v_mov_b32_e32 v4, s20
; VI-NEXT:    v_mov_b32_e32 v36, s40
; VI-NEXT:    v_mov_b32_e32 v3, s19
; VI-NEXT:    v_mov_b32_e32 v37, s41
; VI-NEXT:    v_mov_b32_e32 v2, s18
; VI-NEXT:    v_mov_b32_e32 v38, s42
; VI-NEXT:    v_mov_b32_e32 v1, s17
; VI-NEXT:    v_mov_b32_e32 v39, s43
; VI-NEXT:    v_mov_b32_e32 v0, s16
; VI-NEXT:  .LBB59_5: ; %end
; VI-NEXT:    v_lshlrev_b32_e32 v39, 16, v39
; VI-NEXT:    v_lshlrev_b32_e32 v38, 16, v38
; VI-NEXT:    v_lshlrev_b32_e32 v37, 16, v37
; VI-NEXT:    v_lshlrev_b32_e32 v36, 16, v36
; VI-NEXT:    v_lshlrev_b32_e32 v35, 16, v35
; VI-NEXT:    v_lshlrev_b32_e32 v34, 16, v34
; VI-NEXT:    v_lshlrev_b32_e32 v33, 16, v33
; VI-NEXT:    v_lshlrev_b32_e32 v32, 16, v32
; VI-NEXT:    v_lshlrev_b32_e32 v31, 16, v31
; VI-NEXT:    v_lshlrev_b32_e32 v30, 16, v30
; VI-NEXT:    v_lshlrev_b32_e32 v29, 16, v29
; VI-NEXT:    v_lshlrev_b32_e32 v28, 16, v28
; VI-NEXT:    v_lshlrev_b32_e32 v27, 16, v27
; VI-NEXT:    v_lshlrev_b32_e32 v26, 16, v26
; VI-NEXT:    v_lshlrev_b32_e32 v25, 16, v25
; VI-NEXT:    v_lshlrev_b32_e32 v24, 16, v24
; VI-NEXT:    v_lshlrev_b32_e32 v23, 16, v23
; VI-NEXT:    v_lshlrev_b32_e32 v22, 16, v22
; VI-NEXT:    v_lshlrev_b32_e32 v21, 16, v21
; VI-NEXT:    v_lshlrev_b32_e32 v20, 16, v20
; VI-NEXT:    v_or_b32_sdwa v0, v0, v39 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v1, v1, v38 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v2, v2, v37 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v3, v3, v36 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v4, v4, v35 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v5, v5, v34 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v6, v6, v33 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v7, v7, v32 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v8, v8, v31 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v9, v9, v30 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v10, v10, v29 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v11, v11, v28 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v12, v12, v27 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v13, v13, v26 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v14, v14, v25 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v15, v15, v24 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v16, v16, v23 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v17, v17, v22 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v18, v18, v21 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    v_or_b32_sdwa v19, v19, v20 dst_sel:DWORD dst_unused:UNUSED_PAD src0_sel:WORD_0 src1_sel:DWORD
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; GFX9-LABEL: bitcast_v40f16_to_v40i16_scalar:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_readfirstlane_b32 s63, v5
; GFX9-NEXT:    v_readfirstlane_b32 s62, v4
; GFX9-NEXT:    v_readfirstlane_b32 s61, v3
; GFX9-NEXT:    v_readfirstlane_b32 s60, v2
; GFX9-NEXT:    v_readfirstlane_b32 s59, v1
; GFX9-NEXT:    v_readfirstlane_b32 s58, v0
; GFX9-NEXT:    s_lshr_b32 s43, s29, 16
; GFX9-NEXT:    s_lshr_b32 s42, s28, 16
; GFX9-NEXT:    s_lshr_b32 s41, s27, 16
; GFX9-NEXT:    s_lshr_b32 s40, s26, 16
; GFX9-NEXT:    s_lshr_b32 s15, s25, 16
; GFX9-NEXT:    s_lshr_b32 s14, s24, 16
; GFX9-NEXT:    s_lshr_b32 s13, s23, 16
; GFX9-NEXT:    s_lshr_b32 s12, s22, 16
; GFX9-NEXT:    s_lshr_b32 s11, s21, 16
; GFX9-NEXT:    s_lshr_b32 s10, s20, 16
; GFX9-NEXT:    s_lshr_b32 s9, s19, 16
; GFX9-NEXT:    s_lshr_b32 s8, s18, 16
; GFX9-NEXT:    s_lshr_b32 s7, s17, 16
; GFX9-NEXT:    s_lshr_b32 s6, s16, 16
; GFX9-NEXT:    s_lshr_b32 s57, s63, 16
; GFX9-NEXT:    s_lshr_b32 s56, s62, 16
; GFX9-NEXT:    s_lshr_b32 s47, s61, 16
; GFX9-NEXT:    s_lshr_b32 s46, s60, 16
; GFX9-NEXT:    s_lshr_b32 s45, s59, 16
; GFX9-NEXT:    s_lshr_b32 s44, s58, 16
; GFX9-NEXT:    v_readfirstlane_b32 s4, v6
; GFX9-NEXT:    s_cmp_lg_u32 s4, 0
; GFX9-NEXT:    s_cbranch_scc0 .LBB59_3
; GFX9-NEXT:  ; %bb.1: ; %cmp.false
; GFX9-NEXT:    s_cbranch_execnz .LBB59_4
; GFX9-NEXT:  .LBB59_2: ; %cmp.true
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s63, s57
; GFX9-NEXT:    v_mov_b32_e32 v0, 0x200
; GFX9-NEXT:    v_pk_add_f16 v19, s4, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s62, s56
; GFX9-NEXT:    v_pk_add_f16 v18, s4, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s61, s47
; GFX9-NEXT:    v_pk_add_f16 v17, s4, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s60, s46
; GFX9-NEXT:    v_pk_add_f16 v16, s4, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s59, s45
; GFX9-NEXT:    v_pk_add_f16 v15, s4, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s58, s44
; GFX9-NEXT:    v_pk_add_f16 v14, s4, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s29, s43
; GFX9-NEXT:    v_pk_add_f16 v13, s4, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s28, s42
; GFX9-NEXT:    v_pk_add_f16 v12, s4, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s27, s41
; GFX9-NEXT:    v_pk_add_f16 v11, s4, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s26, s40
; GFX9-NEXT:    v_pk_add_f16 v10, s4, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s25, s15
; GFX9-NEXT:    v_pk_add_f16 v9, s4, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s24, s14
; GFX9-NEXT:    v_pk_add_f16 v8, s4, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s23, s13
; GFX9-NEXT:    v_pk_add_f16 v7, s4, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s22, s12
; GFX9-NEXT:    v_pk_add_f16 v6, s4, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s21, s11
; GFX9-NEXT:    v_pk_add_f16 v5, s4, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s20, s10
; GFX9-NEXT:    v_pk_add_f16 v4, s4, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s19, s9
; GFX9-NEXT:    v_pk_add_f16 v3, s4, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s18, s8
; GFX9-NEXT:    v_pk_add_f16 v2, s4, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s17, s7
; GFX9-NEXT:    v_pk_add_f16 v1, s4, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    s_pack_ll_b32_b16 s4, s16, s6
; GFX9-NEXT:    v_pk_add_f16 v0, s4, v0 op_sel_hi:[1,0]
; GFX9-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX9-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX9-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX9-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX9-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX9-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX9-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX9-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX9-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX9-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX9-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX9-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX9-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX9-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX9-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX9-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX9-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX9-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX9-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX9-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX9-NEXT:    s_branch .LBB59_5
; GFX9-NEXT:  .LBB59_3:
; GFX9-NEXT:    s_branch .LBB59_2
; GFX9-NEXT:  .LBB59_4:
; GFX9-NEXT:    v_mov_b32_e32 v19, s63
; GFX9-NEXT:    v_mov_b32_e32 v18, s62
; GFX9-NEXT:    v_mov_b32_e32 v17, s61
; GFX9-NEXT:    v_mov_b32_e32 v16, s60
; GFX9-NEXT:    v_mov_b32_e32 v15, s59
; GFX9-NEXT:    v_mov_b32_e32 v14, s58
; GFX9-NEXT:    v_mov_b32_e32 v13, s29
; GFX9-NEXT:    v_mov_b32_e32 v12, s28
; GFX9-NEXT:    v_mov_b32_e32 v11, s27
; GFX9-NEXT:    v_mov_b32_e32 v10, s26
; GFX9-NEXT:    v_mov_b32_e32 v9, s25
; GFX9-NEXT:    v_mov_b32_e32 v8, s24
; GFX9-NEXT:    v_mov_b32_e32 v7, s23
; GFX9-NEXT:    v_mov_b32_e32 v6, s22
; GFX9-NEXT:    v_mov_b32_e32 v5, s21
; GFX9-NEXT:    v_mov_b32_e32 v4, s20
; GFX9-NEXT:    v_mov_b32_e32 v3, s19
; GFX9-NEXT:    v_mov_b32_e32 v2, s18
; GFX9-NEXT:    v_mov_b32_e32 v1, s17
; GFX9-NEXT:    v_mov_b32_e32 v0, s16
; GFX9-NEXT:    v_mov_b32_e32 v20, s57
; GFX9-NEXT:    v_mov_b32_e32 v21, s56
; GFX9-NEXT:    v_mov_b32_e32 v22, s47
; GFX9-NEXT:    v_mov_b32_e32 v23, s46
; GFX9-NEXT:    v_mov_b32_e32 v24, s45
; GFX9-NEXT:    v_mov_b32_e32 v25, s44
; GFX9-NEXT:    v_mov_b32_e32 v26, s43
; GFX9-NEXT:    v_mov_b32_e32 v27, s42
; GFX9-NEXT:    v_mov_b32_e32 v28, s41
; GFX9-NEXT:    v_mov_b32_e32 v29, s40
; GFX9-NEXT:    v_mov_b32_e32 v30, s15
; GFX9-NEXT:    v_mov_b32_e32 v31, s14
; GFX9-NEXT:    v_mov_b32_e32 v32, s13
; GFX9-NEXT:    v_mov_b32_e32 v33, s12
; GFX9-NEXT:    v_mov_b32_e32 v34, s11
; GFX9-NEXT:    v_mov_b32_e32 v35, s10
; GFX9-NEXT:    v_mov_b32_e32 v36, s9
; GFX9-NEXT:    v_mov_b32_e32 v37, s8
; GFX9-NEXT:    v_mov_b32_e32 v38, s7
; GFX9-NEXT:    v_mov_b32_e32 v39, s6
; GFX9-NEXT:  .LBB59_5: ; %end
; GFX9-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX9-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; GFX9-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX9-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GFX9-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX9-NEXT:    v_and_b32_e32 v5, 0xffff, v5
; GFX9-NEXT:    v_and_b32_e32 v6, 0xffff, v6
; GFX9-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; GFX9-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; GFX9-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; GFX9-NEXT:    v_and_b32_e32 v10, 0xffff, v10
; GFX9-NEXT:    v_and_b32_e32 v11, 0xffff, v11
; GFX9-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; GFX9-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; GFX9-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; GFX9-NEXT:    v_and_b32_e32 v15, 0xffff, v15
; GFX9-NEXT:    v_and_b32_e32 v16, 0xffff, v16
; GFX9-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; GFX9-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; GFX9-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; GFX9-NEXT:    v_lshl_or_b32 v0, v39, 16, v0
; GFX9-NEXT:    v_lshl_or_b32 v1, v38, 16, v1
; GFX9-NEXT:    v_lshl_or_b32 v2, v37, 16, v2
; GFX9-NEXT:    v_lshl_or_b32 v3, v36, 16, v3
; GFX9-NEXT:    v_lshl_or_b32 v4, v35, 16, v4
; GFX9-NEXT:    v_lshl_or_b32 v5, v34, 16, v5
; GFX9-NEXT:    v_lshl_or_b32 v6, v33, 16, v6
; GFX9-NEXT:    v_lshl_or_b32 v7, v32, 16, v7
; GFX9-NEXT:    v_lshl_or_b32 v8, v31, 16, v8
; GFX9-NEXT:    v_lshl_or_b32 v9, v30, 16, v9
; GFX9-NEXT:    v_lshl_or_b32 v10, v29, 16, v10
; GFX9-NEXT:    v_lshl_or_b32 v11, v28, 16, v11
; GFX9-NEXT:    v_lshl_or_b32 v12, v27, 16, v12
; GFX9-NEXT:    v_lshl_or_b32 v13, v26, 16, v13
; GFX9-NEXT:    v_lshl_or_b32 v14, v25, 16, v14
; GFX9-NEXT:    v_lshl_or_b32 v15, v24, 16, v15
; GFX9-NEXT:    v_lshl_or_b32 v16, v23, 16, v16
; GFX9-NEXT:    v_lshl_or_b32 v17, v22, 16, v17
; GFX9-NEXT:    v_lshl_or_b32 v18, v21, 16, v18
; GFX9-NEXT:    v_lshl_or_b32 v19, v20, 16, v19
; GFX9-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-TRUE16-LABEL: bitcast_v40f16_to_v40i16_scalar:
; GFX11-TRUE16:       ; %bb.0:
; GFX11-TRUE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s57, v1
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s56, v0
; GFX11-TRUE16-NEXT:    v_readfirstlane_b32 s58, v2
; GFX11-TRUE16-NEXT:    s_lshr_b32 s45, s29, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s44, s28, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s43, s27, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s42, s26, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s41, s25, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s40, s24, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s15, s23, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s14, s22, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s13, s21, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s12, s20, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s11, s19, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s10, s18, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s9, s17, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s8, s16, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s6, s3, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s4, s2, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s5, s1, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s7, s0, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s47, s57, 16
; GFX11-TRUE16-NEXT:    s_lshr_b32 s46, s56, 16
; GFX11-TRUE16-NEXT:    s_cmp_lg_u32 s58, 0
; GFX11-TRUE16-NEXT:    s_mov_b32 s58, 0
; GFX11-TRUE16-NEXT:    s_cbranch_scc0 .LBB59_3
; GFX11-TRUE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-TRUE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s58
; GFX11-TRUE16-NEXT:    s_cbranch_vccnz .LBB59_4
; GFX11-TRUE16-NEXT:  .LBB59_2: ; %cmp.true
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s47, s57, s47
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s46, s56, s46
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s29, s29, s45
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s28, s28, s44
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s27, s27, s43
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s26, s26, s42
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s25, s25, s41
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s24, s24, s40
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s15, s23, s15
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s14, s22, s14
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s13, s21, s13
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s12, s20, s12
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s11, s19, s11
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s10, s18, s10
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s9, s17, s9
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s8, s16, s8
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s3, s3, s6
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s2, s2, s4
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s0, s0, s7
; GFX11-TRUE16-NEXT:    s_pack_ll_b32_b16 s1, s1, s5
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v19, 0x200, s47 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v18, 0x200, s46 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v17, 0x200, s29 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v16, 0x200, s28 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v15, 0x200, s27 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v14, 0x200, s26 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v13, 0x200, s25 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v12, 0x200, s24 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v11, 0x200, s15 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v10, 0x200, s14 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v9, 0x200, s13 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v8, 0x200, s12 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v7, 0x200, s11 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v6, 0x200, s10 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v5, 0x200, s9 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v0, 0x200, s0 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v1, 0x200, s1 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v2, 0x200, s2 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v3, 0x200, s3 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_pk_add_f16 v4, 0x200, s8 op_sel_hi:[0,1]
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v0
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v1
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v3
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v4
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v5
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v6
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v8
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v9
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v10
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v11
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v13
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v14
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v15
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v16
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v18
; GFX11-TRUE16-NEXT:    v_lshrrev_b32_e32 v20, 16, v19
; GFX11-TRUE16-NEXT:    s_branch .LBB59_5
; GFX11-TRUE16-NEXT:  .LBB59_3:
; GFX11-TRUE16-NEXT:    s_branch .LBB59_2
; GFX11-TRUE16-NEXT:  .LBB59_4:
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v19, s57 :: v_dual_mov_b32 v18, s56
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v17, s29 :: v_dual_mov_b32 v16, s28
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v15, s27 :: v_dual_mov_b32 v14, s26
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v13, s25 :: v_dual_mov_b32 v12, s24
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v11, s23 :: v_dual_mov_b32 v10, s22
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v9, s21 :: v_dual_mov_b32 v8, s20
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v7, s19 :: v_dual_mov_b32 v6, s18
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v5, s17 :: v_dual_mov_b32 v4, s16
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v3, s3 :: v_dual_mov_b32 v2, s2
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v1, s1 :: v_dual_mov_b32 v0, s0
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v20, s47 :: v_dual_mov_b32 v21, s46
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v22, s45 :: v_dual_mov_b32 v23, s44
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v24, s43 :: v_dual_mov_b32 v25, s42
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v26, s41 :: v_dual_mov_b32 v27, s40
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v28, s15 :: v_dual_mov_b32 v29, s14
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v30, s13 :: v_dual_mov_b32 v31, s12
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v32, s11 :: v_dual_mov_b32 v33, s10
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v34, s9 :: v_dual_mov_b32 v35, s8
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v36, s6 :: v_dual_mov_b32 v37, s4
; GFX11-TRUE16-NEXT:    v_dual_mov_b32 v38, s5 :: v_dual_mov_b32 v39, s7
; GFX11-TRUE16-NEXT:  .LBB59_5: ; %end
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v0.h, v39.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v1.h, v38.l
; GFX11-TRUE16-NEXT:    s_delay_alu instid0(VALU_DEP_4)
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v2.h, v37.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v3.h, v36.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v4.h, v35.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v5.h, v34.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v6.h, v33.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v7.h, v32.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v8.h, v31.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v9.h, v30.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v10.h, v29.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v11.h, v28.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v12.h, v27.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v13.h, v26.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v14.h, v25.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v15.h, v24.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v16.h, v23.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v17.h, v22.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v18.h, v21.l
; GFX11-TRUE16-NEXT:    v_mov_b16_e32 v19.h, v20.l
; GFX11-TRUE16-NEXT:    s_setpc_b64 s[30:31]
;
; GFX11-FAKE16-LABEL: bitcast_v40f16_to_v40i16_scalar:
; GFX11-FAKE16:       ; %bb.0:
; GFX11-FAKE16-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s57, v1
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s56, v0
; GFX11-FAKE16-NEXT:    v_readfirstlane_b32 s58, v2
; GFX11-FAKE16-NEXT:    s_lshr_b32 s45, s29, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s44, s28, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s43, s27, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s42, s26, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s41, s25, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s40, s24, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s15, s23, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s14, s22, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s13, s21, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s12, s20, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s11, s19, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s10, s18, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s9, s17, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s8, s16, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s6, s3, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s4, s2, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s5, s1, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s7, s0, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s47, s57, 16
; GFX11-FAKE16-NEXT:    s_lshr_b32 s46, s56, 16
; GFX11-FAKE16-NEXT:    s_cmp_lg_u32 s58, 0
; GFX11-FAKE16-NEXT:    s_mov_b32 s58, 0
; GFX11-FAKE16-NEXT:    s_cbranch_scc0 .LBB59_3
; GFX11-FAKE16-NEXT:  ; %bb.1: ; %Flow
; GFX11-FAKE16-NEXT:    s_and_not1_b32 vcc_lo, exec_lo, s58
; GFX11-FAKE16-NEXT:    s_cbranch_vccnz .LBB59_4
; GFX11-FAKE16-NEXT:  .LBB59_2: ; %cmp.true
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s47, s57, s47
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s46, s56, s46
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s29, s29, s45
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s28, s28, s44
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s27, s27, s43
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s26, s26, s42
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s25, s25, s41
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s24, s24, s40
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s15, s23, s15
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s14, s22, s14
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s13, s21, s13
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s12, s20, s12
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s11, s19, s11
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s10, s18, s10
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s9, s17, s9
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s8, s16, s8
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s3, s3, s6
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s2, s2, s4
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s0, s0, s7
; GFX11-FAKE16-NEXT:    s_pack_ll_b32_b16 s1, s1, s5
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v15, 0x200, s47 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v16, 0x200, s46 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v17, 0x200, s29 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v18, 0x200, s28 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v19, 0x200, s27 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v10, 0x200, s26 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v11, 0x200, s25 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v12, 0x200, s24 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v13, 0x200, s15 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v14, 0x200, s14 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v5, 0x200, s13 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v6, 0x200, s12 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v7, 0x200, s11 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v8, 0x200, s10 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v9, 0x200, s9 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v4, 0x200, s0 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v3, 0x200, s1 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v2, 0x200, s2 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v1, 0x200, s3 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_pk_add_f16 v0, 0x200, s8 op_sel_hi:[0,1]
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v39, 16, v4
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v38, 16, v3
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v37, 16, v2
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v36, 16, v1
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v35, 16, v0
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v34, 16, v9
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v33, 16, v8
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v31, 16, v6
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v30, 16, v5
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v29, 16, v14
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v28, 16, v13
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v27, 16, v12
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v26, 16, v11
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v25, 16, v10
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v24, 16, v19
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v23, 16, v18
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v22, 16, v17
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v21, 16, v16
; GFX11-FAKE16-NEXT:    v_lshrrev_b32_e32 v20, 16, v15
; GFX11-FAKE16-NEXT:    s_branch .LBB59_5
; GFX11-FAKE16-NEXT:  .LBB59_3:
; GFX11-FAKE16-NEXT:    s_branch .LBB59_2
; GFX11-FAKE16-NEXT:  .LBB59_4:
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v15, s57 :: v_dual_mov_b32 v16, s56
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v17, s29 :: v_dual_mov_b32 v18, s28
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v19, s27 :: v_dual_mov_b32 v10, s26
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v11, s25 :: v_dual_mov_b32 v12, s24
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v13, s23 :: v_dual_mov_b32 v14, s22
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v5, s21 :: v_dual_mov_b32 v6, s20
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v7, s19 :: v_dual_mov_b32 v8, s18
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v9, s17 :: v_dual_mov_b32 v0, s16
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v1, s3 :: v_dual_mov_b32 v2, s2
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v3, s1 :: v_dual_mov_b32 v4, s0
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v20, s47 :: v_dual_mov_b32 v21, s46
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v22, s45 :: v_dual_mov_b32 v23, s44
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v24, s43 :: v_dual_mov_b32 v25, s42
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v26, s41 :: v_dual_mov_b32 v27, s40
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v28, s15 :: v_dual_mov_b32 v29, s14
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v30, s13 :: v_dual_mov_b32 v31, s12
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v32, s11 :: v_dual_mov_b32 v33, s10
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v34, s9 :: v_dual_mov_b32 v35, s8
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v36, s6 :: v_dual_mov_b32 v37, s4
; GFX11-FAKE16-NEXT:    v_dual_mov_b32 v38, s5 :: v_dual_mov_b32 v39, s7
; GFX11-FAKE16-NEXT:  .LBB59_5: ; %end
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v4, 0xffff, v4
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v48, 0xffff, v1
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v49, 0xffff, v0
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v9, 0xffff, v9
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v0, v39, 16, v4
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v1, v38, 16, v3
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v3, v36, 16, v48
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v4, v35, 16, v49
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v8, 0xffff, v8
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v35, 0xffff, v6
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v36, 0xffff, v5
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v5, v34, 16, v9
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v14, 0xffff, v14
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v6, v33, 16, v8
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v8, v31, 16, v35
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v9, v30, 16, v36
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v13, 0xffff, v13
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v30, 0xffff, v11
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v31, 0xffff, v10
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v7, 0xffff, v7
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v12, 0xffff, v12
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v10, v29, 16, v14
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v11, v28, 16, v13
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v13, v26, 16, v30
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v14, v25, 16, v31
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v19, 0xffff, v19
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v18, 0xffff, v18
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v17, 0xffff, v17
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v25, 0xffff, v16
; GFX11-FAKE16-NEXT:    v_and_b32_e32 v26, 0xffff, v15
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v2, v37, 16, v2
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v7, v32, 16, v7
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v12, v27, 16, v12
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v15, v24, 16, v19
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v16, v23, 16, v18
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v17, v22, 16, v17
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v18, v21, 16, v25
; GFX11-FAKE16-NEXT:    v_lshl_or_b32 v19, v20, 16, v26
; GFX11-FAKE16-NEXT:    s_setpc_b64 s[30:31]
  %cmp = icmp eq i32 %b, 0
  br i1 %cmp, label %cmp.true, label %cmp.false

cmp.true:
  %a1 = fadd <40 x half> %a, splat (half 0xH0200)
  %a2 = bitcast <40 x half> %a1 to <40 x i16>
  br label %end

cmp.false:
  %a3 = bitcast <40 x half> %a to <40 x i16>
  br label %end

end:
  %phi = phi <40 x i16> [ %a2, %cmp.true ], [ %a3, %cmp.false ]
  ret <40 x i16> %phi
}

attributes #0 = { nounwind }
