; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-attributes --check-globals all --version 5
; RUN: opt -S -mtriple=amdgcn-amd-amdhsa -mcpu=gfx942 -passes='amdgpu-attributor' %s -o - | FileCheck %s

; Verify that AAAddressSpace does not rewrite pointer address spaces in
; sanitized functions. After SW LDS lowering, LDS accesses become global
; (addrspace 1) memory accesses. If AAAddressSpace is allowed to run on
; sanitized functions, it may infer a narrower address space from the
; underlying LDS object and insert addrspacecast instructions that redirect
; accesses to the wrong memory, producing silently wrong results.
;
; The non-sanitized variant (@load_from_lds_flat) shows AAAddressSpace
; working correctly: it narrows the flat (addrspace 0) pointer to local
; (addrspace 3) since the only underlying object is an LDS global.
;
; The sanitized variant (@load_from_lds_flat_asan) must NOT have any
; addrspacecast inserted by the attributor.

@lds_global = internal addrspace(3) global i32 poison, align 4

; Without sanitizer: AAAddressSpace is expected to insert an addrspacecast,
; narrowing the flat pointer to addrspace(3).
;.
; CHECK: @lds_global = internal addrspace(3) global i32 poison, align 4
;.
define i32 @load_from_lds_flat() {
; CHECK-LABEL: define i32 @load_from_lds_flat(
; CHECK-SAME: ) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    [[VAL:%.*]] = load i32, ptr addrspace(3) @lds_global, align 4, !noalias.addrspace [[META0:![0-9]+]]
; CHECK-NEXT:    ret i32 [[VAL]]
;
  %flat = addrspacecast ptr addrspace(3) @lds_global to ptr
  %val = load i32, ptr %flat, align 4
  ret i32 %val
}

; With sanitizer: AAAddressSpace must be skipped. The flat pointer must
; remain flat — no addrspacecast must be inserted by the attributor.
define i32 @load_from_lds_flat_asan() #0 {
; CHECK: Function Attrs: sanitize_address
; CHECK-LABEL: define i32 @load_from_lds_flat_asan(
; CHECK-SAME: ) #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:    [[FLAT:%.*]] = addrspacecast ptr addrspace(3) @lds_global to ptr
; CHECK-NEXT:    [[VAL:%.*]] = load i32, ptr [[FLAT]], align 4
; CHECK-NEXT:    ret i32 [[VAL]]
;
  %flat = addrspacecast ptr addrspace(3) @lds_global to ptr
  %val = load i32, ptr %flat, align 4
  ret i32 %val
}

attributes #0 = { sanitize_address }

;.
; CHECK: attributes #[[ATTR0]] = { "amdgpu-agpr-alloc"="0" "amdgpu-no-cluster-id-x" "amdgpu-no-cluster-id-y" "amdgpu-no-cluster-id-z" "amdgpu-no-completion-action" "amdgpu-no-default-queue" "amdgpu-no-dispatch-id" "amdgpu-no-dispatch-ptr" "amdgpu-no-flat-scratch-init" "amdgpu-no-heap-ptr" "amdgpu-no-hostcall-ptr" "amdgpu-no-lds-kernel-id" "amdgpu-no-multigrid-sync-arg" "amdgpu-no-queue-ptr" "amdgpu-no-workgroup-id-x" "amdgpu-no-workgroup-id-y" "amdgpu-no-workgroup-id-z" "amdgpu-no-workitem-id-x" "amdgpu-no-workitem-id-y" "amdgpu-no-workitem-id-z" "amdgpu-no-wwm" "target-cpu"="gfx942" }
; CHECK: attributes #[[ATTR1]] = { sanitize_address "amdgpu-no-cluster-id-x" "amdgpu-no-cluster-id-y" "amdgpu-no-cluster-id-z" "amdgpu-no-completion-action" "amdgpu-no-default-queue" "amdgpu-no-dispatch-id" "amdgpu-no-dispatch-ptr" "amdgpu-no-heap-ptr" "amdgpu-no-lds-kernel-id" "amdgpu-no-multigrid-sync-arg" "amdgpu-no-queue-ptr" "amdgpu-no-workgroup-id-x" "amdgpu-no-workgroup-id-y" "amdgpu-no-workgroup-id-z" "amdgpu-no-workitem-id-x" "amdgpu-no-workitem-id-y" "amdgpu-no-workitem-id-z" "amdgpu-no-wwm" "target-cpu"="gfx942" }
;.
; CHECK: [[META0]] = !{i32 1, i32 3, i32 4, i32 10}
;.
