; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx950 --stop-after=register-coalescer  --verify-machineinstrs < %s | FileCheck %s

define amdgpu_kernel void @test_basic_case(ptr addrspace(1) %out, ptr addrspace(1) %in, i32 %n, i32 %m) {
; CHECK-LABEL: name: test_basic_case
; CHECK: bb.0.entry:
; CHECK-NEXT:   successors: %bb.1(0x80000000)
; CHECK-NEXT:   liveins: $sgpr4_sgpr5
; CHECK-NEXT: {{  $}}
; CHECK-NEXT:   [[COPY:%[0-9]+]]:sgpr_64(p4) = COPY $sgpr4_sgpr5
; CHECK-NEXT:   [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec = S_LOAD_DWORDX2_IMM [[COPY]](p4), 16, 0 :: (dereferenceable invariant load (s64) from %ir.n.kernarg.offset, align 16, addrspace 4)
; CHECK-NEXT:   [[S_MUL_I32_:%[0-9]+]]:sreg_32 = S_MUL_I32 [[S_LOAD_DWORDX2_IMM]].sub1, [[S_LOAD_DWORDX2_IMM]].sub1
; CHECK-NEXT:   [[S_ADD_I32_:%[0-9]+]]:sreg_32 = S_ADD_I32 [[S_LOAD_DWORDX2_IMM]].sub0, [[S_MUL_I32_]], implicit-def dead $scc
; CHECK-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
; CHECK-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 0
; CHECK-NEXT: {{  $}}
; CHECK-NEXT: bb.1.loop:
; CHECK-NEXT:   successors: %bb.2(0x04000000), %bb.1(0x7c000000)
; CHECK-NEXT: {{  $}}
; CHECK-NEXT:   [[COPY1:%[0-9]+]]:sreg_32 = COPY [[S_MOV_B32_]]
; CHECK-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_ADD_I32 [[S_MOV_B32_1]], 1, implicit-def dead $scc
; CHECK-NEXT:   S_CMP_LT_I32 [[S_MOV_B32_1]], [[S_LOAD_DWORDX2_IMM]].sub0, implicit-def $scc
; CHECK-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = COPY [[S_ADD_I32_]]
; CHECK-NEXT:   S_CBRANCH_SCC1 %bb.1, implicit killed $scc
; CHECK-NEXT:   S_BRANCH %bb.2
; CHECK-NEXT: {{  $}}
; CHECK-NEXT: bb.2.exit:
; CHECK-NEXT:   [[S_LOAD_DWORDX2_IMM1:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM [[COPY]](p4), 0, 0 :: (dereferenceable invariant load (s64) from %ir.out.kernarg.offset1, align 16, addrspace 4)
; CHECK-NEXT:   [[AV_MOV_:%[0-9]+]]:vgpr_32 = AV_MOV_B32_IMM_PSEUDO 0, implicit $exec
; CHECK-NEXT:   [[COPY2:%[0-9]+]]:av_32 = COPY [[COPY1]]
; CHECK-NEXT:   GLOBAL_STORE_DWORD_SADDR [[AV_MOV_]], [[COPY2]], [[S_LOAD_DWORDX2_IMM1]], 0, 0, implicit $exec :: (store (s32) into %ir.out.load, addrspace 1)
; CHECK-NEXT:   S_ENDPGM 0
entry:
  %orig_0 = add i32 %m, 0
  br label %loop

loop:
  %i = phi i32 [ 0, %entry ], [ %i.next, %loop ]
  %tmp = phi i32 [%orig_0, %entry ], [ %orig.next, %loop ]
  %result = phi i32 [0, %entry], [%result.next, %loop ]

  ; pattern
  %orig = mul i32 %m, %m
  %result.next = add i32 %n, %orig

  ; restore value %tmp, which is the value of %orig_0 in the loop header
  %orig.next = add i32 %tmp, 0

  %i.next = add i32 %i, 1
  %cond = icmp slt i32 %i.next, %n
  br i1 %cond, label %loop, label %exit

exit:
  store i32 %result, ptr addrspace(1) %out
  ret void
}
