; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -mtriple=amdgcn-amd-amdhsa -passes=amdgpu-simplifylib %s | FileCheck %s

define float @test_tdo_scalar_f32_tgamma() {
; CHECK-LABEL: define float @test_tdo_scalar_f32_tgamma() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret float 1.000000e+00
;
entry:
  %c = call float @_Z6tgammaf(float 1.000000e+00)
  ret float %c
}

define <4 x float> @test_tdo_v2_f32_tgamma() {
; CHECK-LABEL: define <4 x float> @test_tdo_v2_f32_tgamma() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret <4 x float> <float 1.000000e+00, float 1.000000e+00, float 2.000000e+00, float 6.000000e+00>
;
entry:
  %c = call <4 x float> @_Z6tgammaDv4_f(<4 x float> <float 1.000000e+00, float 2.000000e+00, float 3.000000e+00, float 4.000000e+00>)
  ret <4 x float> %c
}

define half @test_tdo_scalar_f16_tgamma() {
; CHECK-LABEL: define half @test_tdo_scalar_f16_tgamma() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret half 1.000000e+00
;
entry:
  %c = call half @_Z6tgammaDh(half 1.000000e+00)
  ret half %c
}

define <4 x half> @test_tdo_v2_f16_tgamma() {
; CHECK-LABEL: define <4 x half> @test_tdo_v2_f16_tgamma() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret <4 x half> <half 1.000000e+00, half 1.000000e+00, half 2.000000e+00, half 6.000000e+00>
;
entry:
  %c = call <4 x half> @_Z6tgammaDv4_Dh(<4 x half> <half 1.000000e+00, half 2.000000e+00, half 3.000000e+00, half 4.000000e+00>)
  ret <4 x half> %c
}

define double @test_tdo_scalar_f64_tgamma() {
; CHECK-LABEL: define double @test_tdo_scalar_f64_tgamma() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret double 1.000000e+00
;
entry:
  %c = call double @_Z6tgammad(double 1.000000e+00)
  ret double %c
}

define <4 x double> @test_tdo_v2_f64_tgamma() {
; CHECK-LABEL: define <4 x double> @test_tdo_v2_f64_tgamma() {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret <4 x double> <double 1.000000e+00, double 1.000000e+00, double 2.000000e+00, double 6.000000e+00>
;
entry:
  %c = call <4 x double> @_Z6tgammaDv4_d(<4 x double> <double 1.000000e+00, double 2.000000e+00, double 3.000000e+00, double 4.000000e+00>)
  ret <4 x double> %c
}

declare float        @_Z6tgammaf(float)
declare <4 x float>  @_Z6tgammaDv4_f(<4 x float>)
declare half         @_Z6tgammaDh(half)
declare <4 x half>   @_Z6tgammaDv4_Dh(<4 x half>)
declare double       @_Z6tgammad(double)
declare <4 x double> @_Z6tgammaDv4_d(<4 x double>)
