; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
;
; RUN: llc -mtriple=amdgcn -mcpu=gfx1010 -mattr=+wavefrontsize32 -mattr=-flat-for-global -amdgpu-atomic-optimizer-strategy=DPP < %s | FileCheck -enable-var-scope -check-prefixes=GFX1032 %s
; RUN: llc -mtriple=amdgcn -mcpu=gfx1010 -mattr=+wavefrontsize64 -mattr=-flat-for-global -amdgpu-atomic-optimizer-strategy=DPP < %s | FileCheck -enable-var-scope -check-prefixes=GFX1064 %s
; RUN: llc -mtriple=amdgcn -mcpu=gfx900 -mattr=-flat-for-global -amdgpu-atomic-optimizer-strategy=DPP < %s | FileCheck -enable-var-scope -check-prefixes=GFX900 %s
;
; Test the !amdgpu.atomic.lds.dpp instruction metadata, which controls
; the DPP-based atomic optimization for LDS atomics.
;
; !{!"dynamic"}: use DPP only when active lanes > 5 (hardcoded),
;   otherwise each lane does its own atomic.
; !{!"none"}: skip DPP optimization entirely for this atomic.

declare i32 @llvm.amdgcn.workitem.id.x()

@local_var32 = addrspace(3) global i32 undef, align 4

; Test 1: divergent i32 add with result used -- dynamic threshold branch expected
define amdgpu_kernel void @add_i32_varying(ptr addrspace(1) %out) {
; GFX1032-LABEL: add_i32_varying:
; GFX1032:       ; %bb.0: ; %entry
; GFX1032-NEXT:    s_bcnt1_i32_b32 s0, exec_lo
; GFX1032-NEXT:    s_cmp_lt_u32 s0, 6
; GFX1032-NEXT:    s_cbranch_scc0 .LBB0_2
; GFX1032-NEXT:  ; %bb.1:
; GFX1032-NEXT:    v_mov_b32_e32 v4, 0
; GFX1032-NEXT:    ds_add_rtn_u32 v4, v4, v0
; GFX1032-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1032-NEXT:    buffer_gl0_inv
; GFX1032-NEXT:    s_cbranch_execz .LBB0_3
; GFX1032-NEXT:    s_branch .LBB0_6
; GFX1032-NEXT:  .LBB0_2:
; GFX1032-NEXT:    ; implicit-def: $vgpr4
; GFX1032-NEXT:  .LBB0_3:
; GFX1032-NEXT:    s_or_saveexec_b32 s0, -1
; GFX1032-NEXT:    v_cndmask_b32_e64 v1, 0, v0, s0
; GFX1032-NEXT:    v_mov_b32_e32 v3, 0
; GFX1032-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_shr:1 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1032-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_shr:2 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1032-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_shr:4 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1032-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_shr:8 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1032-NEXT:    v_permlanex16_b32 v2, v1, -1, -1
; GFX1032-NEXT:    v_add_nc_u32_dpp v1, v2, v1 quad_perm:[0,1,2,3] row_mask:0xa bank_mask:0xf
; GFX1032-NEXT:    v_readlane_b32 s2, v1, 31
; GFX1032-NEXT:    v_mov_b32_dpp v3, v1 row_shr:1 row_mask:0xf bank_mask:0xf
; GFX1032-NEXT:    v_readlane_b32 s1, v1, 15
; GFX1032-NEXT:    s_mov_b32 exec_lo, s0
; GFX1032-NEXT:    v_mbcnt_lo_u32_b32 v4, exec_lo, 0
; GFX1032-NEXT:    v_mov_b32_e32 v0, 0
; GFX1032-NEXT:    s_or_saveexec_b32 s0, -1
; GFX1032-NEXT:    v_writelane_b32 v3, s1, 16
; GFX1032-NEXT:    s_mov_b32 exec_lo, s0
; GFX1032-NEXT:    v_cmp_eq_u32_e32 vcc_lo, 0, v4
; GFX1032-NEXT:    ; implicit-def: $vgpr4
; GFX1032-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX1032-NEXT:    s_cbranch_execz .LBB0_5
; GFX1032-NEXT:  ; %bb.4:
; GFX1032-NEXT:    v_mov_b32_e32 v4, s2
; GFX1032-NEXT:    s_waitcnt_vscnt null, 0x0
; GFX1032-NEXT:    ds_add_rtn_u32 v4, v0, v4
; GFX1032-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1032-NEXT:    buffer_gl0_inv
; GFX1032-NEXT:  .LBB0_5:
; GFX1032-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX1032-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX1032-NEXT:    v_readfirstlane_b32 s0, v4
; GFX1032-NEXT:    v_mov_b32_e32 v0, v3
; GFX1032-NEXT:    v_add_nc_u32_e32 v4, s0, v0
; GFX1032-NEXT:  .LBB0_6:
; GFX1032-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x24
; GFX1032-NEXT:    s_mov_b32 s3, 0x31016000
; GFX1032-NEXT:    s_mov_b32 s2, -1
; GFX1032-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1032-NEXT:    buffer_store_dword v4, off, s[0:3], 0
; GFX1032-NEXT:    s_endpgm
;
; GFX1064-LABEL: add_i32_varying:
; GFX1064:       ; %bb.0: ; %entry
; GFX1064-NEXT:    s_bcnt1_i32_b64 s0, exec
; GFX1064-NEXT:    s_cmp_lt_u32 s0, 6
; GFX1064-NEXT:    s_cbranch_scc0 .LBB0_2
; GFX1064-NEXT:  ; %bb.1:
; GFX1064-NEXT:    v_mov_b32_e32 v4, 0
; GFX1064-NEXT:    ds_add_rtn_u32 v4, v4, v0
; GFX1064-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1064-NEXT:    buffer_gl0_inv
; GFX1064-NEXT:    s_cbranch_execz .LBB0_3
; GFX1064-NEXT:    s_branch .LBB0_6
; GFX1064-NEXT:  .LBB0_2:
; GFX1064-NEXT:    ; implicit-def: $vgpr4
; GFX1064-NEXT:  .LBB0_3:
; GFX1064-NEXT:    s_or_saveexec_b64 s[0:1], -1
; GFX1064-NEXT:    v_cndmask_b32_e64 v1, 0, v0, s[0:1]
; GFX1064-NEXT:    v_mov_b32_e32 v3, 0
; GFX1064-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_shr:1 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1064-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_shr:2 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1064-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_shr:4 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1064-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_shr:8 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1064-NEXT:    v_permlanex16_b32 v2, v1, -1, -1
; GFX1064-NEXT:    v_add_nc_u32_dpp v1, v2, v1 quad_perm:[0,1,2,3] row_mask:0xa bank_mask:0xf
; GFX1064-NEXT:    v_readlane_b32 s2, v1, 31
; GFX1064-NEXT:    v_mov_b32_e32 v2, s2
; GFX1064-NEXT:    v_add_nc_u32_dpp v1, v2, v1 quad_perm:[0,1,2,3] row_mask:0xc bank_mask:0xf
; GFX1064-NEXT:    v_mov_b32_dpp v3, v1 row_shr:1 row_mask:0xf bank_mask:0xf
; GFX1064-NEXT:    v_readlane_b32 s2, v1, 15
; GFX1064-NEXT:    v_readlane_b32 s3, v1, 31
; GFX1064-NEXT:    v_writelane_b32 v3, s2, 16
; GFX1064-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1064-NEXT:    v_mbcnt_lo_u32_b32 v0, exec_lo, 0
; GFX1064-NEXT:    s_or_saveexec_b64 s[0:1], -1
; GFX1064-NEXT:    v_readlane_b32 s2, v1, 63
; GFX1064-NEXT:    v_readlane_b32 s6, v1, 47
; GFX1064-NEXT:    v_writelane_b32 v3, s3, 32
; GFX1064-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1064-NEXT:    v_mbcnt_hi_u32_b32 v4, exec_hi, v0
; GFX1064-NEXT:    v_mov_b32_e32 v0, 0
; GFX1064-NEXT:    s_or_saveexec_b64 s[0:1], -1
; GFX1064-NEXT:    v_writelane_b32 v3, s6, 48
; GFX1064-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1064-NEXT:    v_cmp_eq_u32_e32 vcc, 0, v4
; GFX1064-NEXT:    ; implicit-def: $vgpr4
; GFX1064-NEXT:    s_and_saveexec_b64 s[0:1], vcc
; GFX1064-NEXT:    s_cbranch_execz .LBB0_5
; GFX1064-NEXT:  ; %bb.4:
; GFX1064-NEXT:    v_mov_b32_e32 v4, s2
; GFX1064-NEXT:    s_waitcnt_vscnt null, 0x0
; GFX1064-NEXT:    ds_add_rtn_u32 v4, v0, v4
; GFX1064-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1064-NEXT:    buffer_gl0_inv
; GFX1064-NEXT:  .LBB0_5:
; GFX1064-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX1064-NEXT:    s_or_b64 exec, exec, s[0:1]
; GFX1064-NEXT:    v_readfirstlane_b32 s0, v4
; GFX1064-NEXT:    v_mov_b32_e32 v0, v3
; GFX1064-NEXT:    v_add_nc_u32_e32 v4, s0, v0
; GFX1064-NEXT:  .LBB0_6:
; GFX1064-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x24
; GFX1064-NEXT:    s_mov_b32 s3, 0x31016000
; GFX1064-NEXT:    s_mov_b32 s2, -1
; GFX1064-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1064-NEXT:    buffer_store_dword v4, off, s[0:3], 0
; GFX1064-NEXT:    s_endpgm
;
; GFX900-LABEL: add_i32_varying:
; GFX900:       ; %bb.0: ; %entry
; GFX900-NEXT:    s_bcnt1_i32_b64 s0, exec
; GFX900-NEXT:    s_cmp_lt_u32 s0, 6
; GFX900-NEXT:    s_cbranch_scc0 .LBB0_2
; GFX900-NEXT:  ; %bb.1:
; GFX900-NEXT:    v_mov_b32_e32 v3, 0
; GFX900-NEXT:    ds_add_rtn_u32 v3, v3, v0
; GFX900-NEXT:    s_waitcnt lgkmcnt(0)
; GFX900-NEXT:    s_cbranch_execz .LBB0_3
; GFX900-NEXT:    s_branch .LBB0_6
; GFX900-NEXT:  .LBB0_2:
; GFX900-NEXT:    ; implicit-def: $vgpr3
; GFX900-NEXT:  .LBB0_3:
; GFX900-NEXT:    v_mov_b32_e32 v3, 0
; GFX900-NEXT:    v_mbcnt_lo_u32_b32 v4, exec_lo, 0
; GFX900-NEXT:    v_mbcnt_hi_u32_b32 v4, exec_hi, v4
; GFX900-NEXT:    s_or_saveexec_b64 s[0:1], -1
; GFX900-NEXT:    v_cndmask_b32_e64 v1, 0, v0, s[0:1]
; GFX900-NEXT:    v_mov_b32_e32 v2, 0
; GFX900-NEXT:    s_nop 0
; GFX900-NEXT:    v_add_u32_dpp v1, v1, v1 row_shr:1 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_add_u32_dpp v1, v1, v1 row_shr:2 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_add_u32_dpp v1, v1, v1 row_shr:4 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_add_u32_dpp v1, v1, v1 row_shr:8 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_add_u32_dpp v1, v1, v1 row_bcast:15 row_mask:0xa bank_mask:0xf
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_add_u32_dpp v1, v1, v1 row_bcast:31 row_mask:0xc bank_mask:0xf
; GFX900-NEXT:    v_readlane_b32 s2, v1, 63
; GFX900-NEXT:    s_nop 0
; GFX900-NEXT:    v_mov_b32_dpp v2, v1 wave_shr:1 row_mask:0xf bank_mask:0xf
; GFX900-NEXT:    s_mov_b64 exec, s[0:1]
; GFX900-NEXT:    v_cmp_eq_u32_e32 vcc, 0, v4
; GFX900-NEXT:    ; implicit-def: $vgpr0
; GFX900-NEXT:    s_and_saveexec_b64 s[0:1], vcc
; GFX900-NEXT:    s_cbranch_execz .LBB0_5
; GFX900-NEXT:  ; %bb.4:
; GFX900-NEXT:    v_mov_b32_e32 v0, s2
; GFX900-NEXT:    ds_add_rtn_u32 v0, v3, v0
; GFX900-NEXT:    s_waitcnt lgkmcnt(0)
; GFX900-NEXT:  .LBB0_5:
; GFX900-NEXT:    s_or_b64 exec, exec, s[0:1]
; GFX900-NEXT:    v_readfirstlane_b32 s0, v0
; GFX900-NEXT:    v_mov_b32_e32 v0, v2
; GFX900-NEXT:    v_add_u32_e32 v3, s0, v0
; GFX900-NEXT:  .LBB0_6:
; GFX900-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x24
; GFX900-NEXT:    s_mov_b32 s3, 0xf000
; GFX900-NEXT:    s_mov_b32 s2, -1
; GFX900-NEXT:    s_waitcnt lgkmcnt(0)
; GFX900-NEXT:    buffer_store_dword v3, off, s[0:3], 0
; GFX900-NEXT:    s_endpgm
entry:
  %lane = call i32 @llvm.amdgcn.workitem.id.x()
  %old = atomicrmw add ptr addrspace(3) @local_var32, i32 %lane acq_rel, !amdgpu.atomic.lds.dpp !0
  store i32 %old, ptr addrspace(1) %out
  ret void
}

; Test 2: divergent i32 sub with result used
define amdgpu_kernel void @sub_i32_varying(ptr addrspace(1) %out) {
; GFX1032-LABEL: sub_i32_varying:
; GFX1032:       ; %bb.0: ; %entry
; GFX1032-NEXT:    s_bcnt1_i32_b32 s0, exec_lo
; GFX1032-NEXT:    s_cmp_lt_u32 s0, 6
; GFX1032-NEXT:    s_cbranch_scc0 .LBB1_2
; GFX1032-NEXT:  ; %bb.1:
; GFX1032-NEXT:    v_mov_b32_e32 v4, 0
; GFX1032-NEXT:    ds_sub_rtn_u32 v4, v4, v0
; GFX1032-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1032-NEXT:    buffer_gl0_inv
; GFX1032-NEXT:    s_cbranch_execz .LBB1_3
; GFX1032-NEXT:    s_branch .LBB1_6
; GFX1032-NEXT:  .LBB1_2:
; GFX1032-NEXT:    ; implicit-def: $vgpr4
; GFX1032-NEXT:  .LBB1_3:
; GFX1032-NEXT:    s_or_saveexec_b32 s0, -1
; GFX1032-NEXT:    v_cndmask_b32_e64 v1, 0, v0, s0
; GFX1032-NEXT:    v_mov_b32_e32 v3, 0
; GFX1032-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_shr:1 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1032-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_shr:2 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1032-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_shr:4 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1032-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_shr:8 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1032-NEXT:    v_permlanex16_b32 v2, v1, -1, -1
; GFX1032-NEXT:    v_add_nc_u32_dpp v1, v2, v1 quad_perm:[0,1,2,3] row_mask:0xa bank_mask:0xf
; GFX1032-NEXT:    v_readlane_b32 s2, v1, 31
; GFX1032-NEXT:    v_mov_b32_dpp v3, v1 row_shr:1 row_mask:0xf bank_mask:0xf
; GFX1032-NEXT:    v_readlane_b32 s1, v1, 15
; GFX1032-NEXT:    s_mov_b32 exec_lo, s0
; GFX1032-NEXT:    v_mbcnt_lo_u32_b32 v4, exec_lo, 0
; GFX1032-NEXT:    v_mov_b32_e32 v0, 0
; GFX1032-NEXT:    s_or_saveexec_b32 s0, -1
; GFX1032-NEXT:    v_writelane_b32 v3, s1, 16
; GFX1032-NEXT:    s_mov_b32 exec_lo, s0
; GFX1032-NEXT:    v_cmp_eq_u32_e32 vcc_lo, 0, v4
; GFX1032-NEXT:    ; implicit-def: $vgpr4
; GFX1032-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX1032-NEXT:    s_cbranch_execz .LBB1_5
; GFX1032-NEXT:  ; %bb.4:
; GFX1032-NEXT:    v_mov_b32_e32 v4, s2
; GFX1032-NEXT:    s_waitcnt_vscnt null, 0x0
; GFX1032-NEXT:    ds_sub_rtn_u32 v4, v0, v4
; GFX1032-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1032-NEXT:    buffer_gl0_inv
; GFX1032-NEXT:  .LBB1_5:
; GFX1032-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX1032-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX1032-NEXT:    v_readfirstlane_b32 s0, v4
; GFX1032-NEXT:    v_mov_b32_e32 v0, v3
; GFX1032-NEXT:    v_sub_nc_u32_e32 v4, s0, v0
; GFX1032-NEXT:  .LBB1_6:
; GFX1032-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x24
; GFX1032-NEXT:    s_mov_b32 s3, 0x31016000
; GFX1032-NEXT:    s_mov_b32 s2, -1
; GFX1032-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1032-NEXT:    buffer_store_dword v4, off, s[0:3], 0
; GFX1032-NEXT:    s_endpgm
;
; GFX1064-LABEL: sub_i32_varying:
; GFX1064:       ; %bb.0: ; %entry
; GFX1064-NEXT:    s_bcnt1_i32_b64 s0, exec
; GFX1064-NEXT:    s_cmp_lt_u32 s0, 6
; GFX1064-NEXT:    s_cbranch_scc0 .LBB1_2
; GFX1064-NEXT:  ; %bb.1:
; GFX1064-NEXT:    v_mov_b32_e32 v4, 0
; GFX1064-NEXT:    ds_sub_rtn_u32 v4, v4, v0
; GFX1064-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1064-NEXT:    buffer_gl0_inv
; GFX1064-NEXT:    s_cbranch_execz .LBB1_3
; GFX1064-NEXT:    s_branch .LBB1_6
; GFX1064-NEXT:  .LBB1_2:
; GFX1064-NEXT:    ; implicit-def: $vgpr4
; GFX1064-NEXT:  .LBB1_3:
; GFX1064-NEXT:    s_or_saveexec_b64 s[0:1], -1
; GFX1064-NEXT:    v_cndmask_b32_e64 v1, 0, v0, s[0:1]
; GFX1064-NEXT:    v_mov_b32_e32 v3, 0
; GFX1064-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_shr:1 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1064-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_shr:2 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1064-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_shr:4 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1064-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_shr:8 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1064-NEXT:    v_permlanex16_b32 v2, v1, -1, -1
; GFX1064-NEXT:    v_add_nc_u32_dpp v1, v2, v1 quad_perm:[0,1,2,3] row_mask:0xa bank_mask:0xf
; GFX1064-NEXT:    v_readlane_b32 s2, v1, 31
; GFX1064-NEXT:    v_mov_b32_e32 v2, s2
; GFX1064-NEXT:    v_add_nc_u32_dpp v1, v2, v1 quad_perm:[0,1,2,3] row_mask:0xc bank_mask:0xf
; GFX1064-NEXT:    v_mov_b32_dpp v3, v1 row_shr:1 row_mask:0xf bank_mask:0xf
; GFX1064-NEXT:    v_readlane_b32 s2, v1, 15
; GFX1064-NEXT:    v_readlane_b32 s3, v1, 31
; GFX1064-NEXT:    v_writelane_b32 v3, s2, 16
; GFX1064-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1064-NEXT:    v_mbcnt_lo_u32_b32 v0, exec_lo, 0
; GFX1064-NEXT:    s_or_saveexec_b64 s[0:1], -1
; GFX1064-NEXT:    v_readlane_b32 s2, v1, 63
; GFX1064-NEXT:    v_readlane_b32 s6, v1, 47
; GFX1064-NEXT:    v_writelane_b32 v3, s3, 32
; GFX1064-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1064-NEXT:    v_mbcnt_hi_u32_b32 v4, exec_hi, v0
; GFX1064-NEXT:    v_mov_b32_e32 v0, 0
; GFX1064-NEXT:    s_or_saveexec_b64 s[0:1], -1
; GFX1064-NEXT:    v_writelane_b32 v3, s6, 48
; GFX1064-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1064-NEXT:    v_cmp_eq_u32_e32 vcc, 0, v4
; GFX1064-NEXT:    ; implicit-def: $vgpr4
; GFX1064-NEXT:    s_and_saveexec_b64 s[0:1], vcc
; GFX1064-NEXT:    s_cbranch_execz .LBB1_5
; GFX1064-NEXT:  ; %bb.4:
; GFX1064-NEXT:    v_mov_b32_e32 v4, s2
; GFX1064-NEXT:    s_waitcnt_vscnt null, 0x0
; GFX1064-NEXT:    ds_sub_rtn_u32 v4, v0, v4
; GFX1064-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1064-NEXT:    buffer_gl0_inv
; GFX1064-NEXT:  .LBB1_5:
; GFX1064-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX1064-NEXT:    s_or_b64 exec, exec, s[0:1]
; GFX1064-NEXT:    v_readfirstlane_b32 s0, v4
; GFX1064-NEXT:    v_mov_b32_e32 v0, v3
; GFX1064-NEXT:    v_sub_nc_u32_e32 v4, s0, v0
; GFX1064-NEXT:  .LBB1_6:
; GFX1064-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x24
; GFX1064-NEXT:    s_mov_b32 s3, 0x31016000
; GFX1064-NEXT:    s_mov_b32 s2, -1
; GFX1064-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1064-NEXT:    buffer_store_dword v4, off, s[0:3], 0
; GFX1064-NEXT:    s_endpgm
;
; GFX900-LABEL: sub_i32_varying:
; GFX900:       ; %bb.0: ; %entry
; GFX900-NEXT:    s_bcnt1_i32_b64 s0, exec
; GFX900-NEXT:    s_cmp_lt_u32 s0, 6
; GFX900-NEXT:    s_cbranch_scc0 .LBB1_2
; GFX900-NEXT:  ; %bb.1:
; GFX900-NEXT:    v_mov_b32_e32 v3, 0
; GFX900-NEXT:    ds_sub_rtn_u32 v3, v3, v0
; GFX900-NEXT:    s_waitcnt lgkmcnt(0)
; GFX900-NEXT:    s_cbranch_execz .LBB1_3
; GFX900-NEXT:    s_branch .LBB1_6
; GFX900-NEXT:  .LBB1_2:
; GFX900-NEXT:    ; implicit-def: $vgpr3
; GFX900-NEXT:  .LBB1_3:
; GFX900-NEXT:    v_mov_b32_e32 v3, 0
; GFX900-NEXT:    v_mbcnt_lo_u32_b32 v4, exec_lo, 0
; GFX900-NEXT:    v_mbcnt_hi_u32_b32 v4, exec_hi, v4
; GFX900-NEXT:    s_or_saveexec_b64 s[0:1], -1
; GFX900-NEXT:    v_cndmask_b32_e64 v1, 0, v0, s[0:1]
; GFX900-NEXT:    v_mov_b32_e32 v2, 0
; GFX900-NEXT:    s_nop 0
; GFX900-NEXT:    v_add_u32_dpp v1, v1, v1 row_shr:1 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_add_u32_dpp v1, v1, v1 row_shr:2 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_add_u32_dpp v1, v1, v1 row_shr:4 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_add_u32_dpp v1, v1, v1 row_shr:8 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_add_u32_dpp v1, v1, v1 row_bcast:15 row_mask:0xa bank_mask:0xf
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_add_u32_dpp v1, v1, v1 row_bcast:31 row_mask:0xc bank_mask:0xf
; GFX900-NEXT:    v_readlane_b32 s2, v1, 63
; GFX900-NEXT:    s_nop 0
; GFX900-NEXT:    v_mov_b32_dpp v2, v1 wave_shr:1 row_mask:0xf bank_mask:0xf
; GFX900-NEXT:    s_mov_b64 exec, s[0:1]
; GFX900-NEXT:    v_cmp_eq_u32_e32 vcc, 0, v4
; GFX900-NEXT:    ; implicit-def: $vgpr0
; GFX900-NEXT:    s_and_saveexec_b64 s[0:1], vcc
; GFX900-NEXT:    s_cbranch_execz .LBB1_5
; GFX900-NEXT:  ; %bb.4:
; GFX900-NEXT:    v_mov_b32_e32 v0, s2
; GFX900-NEXT:    ds_sub_rtn_u32 v0, v3, v0
; GFX900-NEXT:    s_waitcnt lgkmcnt(0)
; GFX900-NEXT:  .LBB1_5:
; GFX900-NEXT:    s_or_b64 exec, exec, s[0:1]
; GFX900-NEXT:    v_readfirstlane_b32 s0, v0
; GFX900-NEXT:    v_mov_b32_e32 v0, v2
; GFX900-NEXT:    v_sub_u32_e32 v3, s0, v0
; GFX900-NEXT:  .LBB1_6:
; GFX900-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x24
; GFX900-NEXT:    s_mov_b32 s3, 0xf000
; GFX900-NEXT:    s_mov_b32 s2, -1
; GFX900-NEXT:    s_waitcnt lgkmcnt(0)
; GFX900-NEXT:    buffer_store_dword v3, off, s[0:3], 0
; GFX900-NEXT:    s_endpgm
entry:
  %lane = call i32 @llvm.amdgcn.workitem.id.x()
  %old = atomicrmw sub ptr addrspace(3) @local_var32, i32 %lane acq_rel, !amdgpu.atomic.lds.dpp !0
  store i32 %old, ptr addrspace(1) %out
  ret void
}

; Test 3: divergent i32 add without result used (NeedResult=false)
define amdgpu_kernel void @add_i32_varying_nouse() #0 {
; GFX1032-LABEL: add_i32_varying_nouse:
; GFX1032:       ; %bb.0: ; %entry
; GFX1032-NEXT:    s_bcnt1_i32_b32 s0, exec_lo
; GFX1032-NEXT:    s_cmp_lt_u32 s0, 6
; GFX1032-NEXT:    s_mov_b32 s0, -1
; GFX1032-NEXT:    s_cbranch_scc0 .LBB2_2
; GFX1032-NEXT:  ; %bb.1:
; GFX1032-NEXT:    v_mov_b32_e32 v3, 0
; GFX1032-NEXT:    s_mov_b32 s0, 0
; GFX1032-NEXT:    ds_add_u32 v3, v0
; GFX1032-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1032-NEXT:    buffer_gl0_inv
; GFX1032-NEXT:  .LBB2_2: ; %Flow1
; GFX1032-NEXT:    s_andn2_b32 vcc_lo, exec_lo, s0
; GFX1032-NEXT:    s_cbranch_vccnz .LBB2_5
; GFX1032-NEXT:  ; %bb.3:
; GFX1032-NEXT:    s_or_saveexec_b32 s0, -1
; GFX1032-NEXT:    v_cndmask_b32_e64 v1, 0, v0, s0
; GFX1032-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_xmask:1 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1032-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_xmask:2 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1032-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_xmask:4 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1032-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_xmask:8 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1032-NEXT:    v_permlanex16_b32 v2, v1, 0, 0
; GFX1032-NEXT:    v_add_nc_u32_e32 v1, v1, v2
; GFX1032-NEXT:    s_mov_b32 exec_lo, s0
; GFX1032-NEXT:    v_mbcnt_lo_u32_b32 v4, exec_lo, 0
; GFX1032-NEXT:    v_mov_b32_e32 v0, 0
; GFX1032-NEXT:    v_mov_b32_e32 v3, v1
; GFX1032-NEXT:    v_cmp_eq_u32_e32 vcc_lo, 0, v4
; GFX1032-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX1032-NEXT:    s_cbranch_execz .LBB2_5
; GFX1032-NEXT:  ; %bb.4:
; GFX1032-NEXT:    s_waitcnt_vscnt null, 0x0
; GFX1032-NEXT:    ds_add_u32 v0, v3
; GFX1032-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1032-NEXT:    buffer_gl0_inv
; GFX1032-NEXT:  .LBB2_5:
; GFX1032-NEXT:    s_endpgm
;
; GFX1064-LABEL: add_i32_varying_nouse:
; GFX1064:       ; %bb.0: ; %entry
; GFX1064-NEXT:    s_bcnt1_i32_b64 s0, exec
; GFX1064-NEXT:    s_cmp_lt_u32 s0, 6
; GFX1064-NEXT:    s_mov_b64 s[0:1], -1
; GFX1064-NEXT:    s_cbranch_scc0 .LBB2_2
; GFX1064-NEXT:  ; %bb.1:
; GFX1064-NEXT:    v_mov_b32_e32 v3, 0
; GFX1064-NEXT:    s_mov_b64 s[0:1], 0
; GFX1064-NEXT:    ds_add_u32 v3, v0
; GFX1064-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1064-NEXT:    buffer_gl0_inv
; GFX1064-NEXT:  .LBB2_2: ; %Flow1
; GFX1064-NEXT:    s_andn2_b64 vcc, exec, s[0:1]
; GFX1064-NEXT:    s_cbranch_vccnz .LBB2_5
; GFX1064-NEXT:  ; %bb.3:
; GFX1064-NEXT:    s_or_saveexec_b64 s[0:1], -1
; GFX1064-NEXT:    v_cndmask_b32_e64 v1, 0, v0, s[0:1]
; GFX1064-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_xmask:1 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1064-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_xmask:2 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1064-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_xmask:4 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1064-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_xmask:8 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1064-NEXT:    v_permlanex16_b32 v2, v1, 0, 0
; GFX1064-NEXT:    v_add_nc_u32_e32 v1, v1, v2
; GFX1064-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1064-NEXT:    v_mbcnt_lo_u32_b32 v0, exec_lo, 0
; GFX1064-NEXT:    s_or_saveexec_b64 s[0:1], -1
; GFX1064-NEXT:    v_readlane_b32 s2, v1, 0
; GFX1064-NEXT:    v_readlane_b32 s3, v1, 32
; GFX1064-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1064-NEXT:    v_mbcnt_hi_u32_b32 v3, exec_hi, v0
; GFX1064-NEXT:    v_mov_b32_e32 v0, 0
; GFX1064-NEXT:    s_add_i32 s0, s2, s3
; GFX1064-NEXT:    v_cmp_eq_u32_e32 vcc, 0, v3
; GFX1064-NEXT:    s_and_saveexec_b64 s[2:3], vcc
; GFX1064-NEXT:    s_cbranch_execz .LBB2_5
; GFX1064-NEXT:  ; %bb.4:
; GFX1064-NEXT:    v_mov_b32_e32 v3, s0
; GFX1064-NEXT:    s_waitcnt_vscnt null, 0x0
; GFX1064-NEXT:    ds_add_u32 v0, v3
; GFX1064-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1064-NEXT:    buffer_gl0_inv
; GFX1064-NEXT:  .LBB2_5:
; GFX1064-NEXT:    s_endpgm
;
; GFX900-LABEL: add_i32_varying_nouse:
; GFX900:       ; %bb.0: ; %entry
; GFX900-NEXT:    s_bcnt1_i32_b64 s0, exec
; GFX900-NEXT:    s_cmp_lt_u32 s0, 6
; GFX900-NEXT:    s_mov_b64 s[0:1], -1
; GFX900-NEXT:    s_cbranch_scc0 .LBB2_2
; GFX900-NEXT:  ; %bb.1:
; GFX900-NEXT:    v_mov_b32_e32 v2, 0
; GFX900-NEXT:    ds_add_u32 v2, v0
; GFX900-NEXT:    s_waitcnt lgkmcnt(0)
; GFX900-NEXT:    s_mov_b64 s[0:1], 0
; GFX900-NEXT:  .LBB2_2: ; %Flow1
; GFX900-NEXT:    s_andn2_b64 vcc, exec, s[0:1]
; GFX900-NEXT:    s_cbranch_vccnz .LBB2_5
; GFX900-NEXT:  ; %bb.3:
; GFX900-NEXT:    v_mov_b32_e32 v2, 0
; GFX900-NEXT:    v_mbcnt_lo_u32_b32 v3, exec_lo, 0
; GFX900-NEXT:    v_mbcnt_hi_u32_b32 v3, exec_hi, v3
; GFX900-NEXT:    s_or_saveexec_b64 s[0:1], -1
; GFX900-NEXT:    v_cndmask_b32_e64 v1, 0, v0, s[0:1]
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_add_u32_dpp v1, v1, v1 row_shr:1 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_add_u32_dpp v1, v1, v1 row_shr:2 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_add_u32_dpp v1, v1, v1 row_shr:4 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_add_u32_dpp v1, v1, v1 row_shr:8 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_add_u32_dpp v1, v1, v1 row_bcast:15 row_mask:0xa bank_mask:0xf
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_add_u32_dpp v1, v1, v1 row_bcast:31 row_mask:0xc bank_mask:0xf
; GFX900-NEXT:    v_readlane_b32 s2, v1, 63
; GFX900-NEXT:    s_mov_b64 exec, s[0:1]
; GFX900-NEXT:    s_mov_b32 s0, s2
; GFX900-NEXT:    v_cmp_eq_u32_e32 vcc, 0, v3
; GFX900-NEXT:    s_and_saveexec_b64 s[2:3], vcc
; GFX900-NEXT:    s_cbranch_execz .LBB2_5
; GFX900-NEXT:  ; %bb.4:
; GFX900-NEXT:    v_mov_b32_e32 v0, s0
; GFX900-NEXT:    ds_add_u32 v2, v0
; GFX900-NEXT:    s_waitcnt lgkmcnt(0)
; GFX900-NEXT:  .LBB2_5:
; GFX900-NEXT:    s_endpgm
entry:
  %lane = call i32 @llvm.amdgcn.workitem.id.x()
  %old = atomicrmw add ptr addrspace(3) @local_var32, i32 %lane acq_rel, !amdgpu.atomic.lds.dpp !0
  ret void
}

; Test 4: uniform i32 add with dynamic metadata -- metadata ignored (not divergent)
define amdgpu_kernel void @add_i32_uniform(ptr addrspace(1) %out, i32 %additive) {
; GFX1032-LABEL: add_i32_uniform:
; GFX1032:       ; %bb.0: ; %entry
; GFX1032-NEXT:    s_load_dword s0, s[4:5], 0x2c
; GFX1032-NEXT:    s_mov_b32 s2, exec_lo
; GFX1032-NEXT:    ; implicit-def: $vgpr1
; GFX1032-NEXT:    v_mbcnt_lo_u32_b32 v0, s2, 0
; GFX1032-NEXT:    v_cmp_eq_u32_e32 vcc_lo, 0, v0
; GFX1032-NEXT:    s_and_saveexec_b32 s1, vcc_lo
; GFX1032-NEXT:    s_cbranch_execz .LBB3_2
; GFX1032-NEXT:  ; %bb.1:
; GFX1032-NEXT:    s_bcnt1_i32_b32 s2, s2
; GFX1032-NEXT:    v_mov_b32_e32 v1, 0
; GFX1032-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1032-NEXT:    s_mul_i32 s2, s0, s2
; GFX1032-NEXT:    v_mov_b32_e32 v2, s2
; GFX1032-NEXT:    ds_add_rtn_u32 v1, v1, v2
; GFX1032-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1032-NEXT:    buffer_gl0_inv
; GFX1032-NEXT:  .LBB3_2:
; GFX1032-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX1032-NEXT:    s_or_b32 exec_lo, exec_lo, s1
; GFX1032-NEXT:    s_load_dwordx2 s[8:9], s[4:5], 0x24
; GFX1032-NEXT:    v_readfirstlane_b32 s2, v1
; GFX1032-NEXT:    s_mov_b32 s11, 0x31016000
; GFX1032-NEXT:    s_mov_b32 s10, -1
; GFX1032-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1032-NEXT:    v_mad_u64_u32 v[0:1], s0, s0, v0, s[2:3]
; GFX1032-NEXT:    buffer_store_dword v0, off, s[8:11], 0
; GFX1032-NEXT:    s_endpgm
;
; GFX1064-LABEL: add_i32_uniform:
; GFX1064:       ; %bb.0: ; %entry
; GFX1064-NEXT:    s_load_dword s6, s[4:5], 0x2c
; GFX1064-NEXT:    s_mov_b64 s[2:3], exec
; GFX1064-NEXT:    ; implicit-def: $vgpr1
; GFX1064-NEXT:    v_mbcnt_lo_u32_b32 v0, s2, 0
; GFX1064-NEXT:    v_mbcnt_hi_u32_b32 v0, s3, v0
; GFX1064-NEXT:    v_cmp_eq_u32_e32 vcc, 0, v0
; GFX1064-NEXT:    s_and_saveexec_b64 s[0:1], vcc
; GFX1064-NEXT:    s_cbranch_execz .LBB3_2
; GFX1064-NEXT:  ; %bb.1:
; GFX1064-NEXT:    s_bcnt1_i32_b64 s2, s[2:3]
; GFX1064-NEXT:    v_mov_b32_e32 v1, 0
; GFX1064-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1064-NEXT:    s_mul_i32 s2, s6, s2
; GFX1064-NEXT:    v_mov_b32_e32 v2, s2
; GFX1064-NEXT:    ds_add_rtn_u32 v1, v1, v2
; GFX1064-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1064-NEXT:    buffer_gl0_inv
; GFX1064-NEXT:  .LBB3_2:
; GFX1064-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX1064-NEXT:    s_or_b64 exec, exec, s[0:1]
; GFX1064-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x24
; GFX1064-NEXT:    v_readfirstlane_b32 s2, v1
; GFX1064-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1064-NEXT:    v_mad_u64_u32 v[0:1], s[2:3], s6, v0, s[2:3]
; GFX1064-NEXT:    s_mov_b32 s3, 0x31016000
; GFX1064-NEXT:    s_mov_b32 s2, -1
; GFX1064-NEXT:    buffer_store_dword v0, off, s[0:3], 0
; GFX1064-NEXT:    s_endpgm
;
; GFX900-LABEL: add_i32_uniform:
; GFX900:       ; %bb.0: ; %entry
; GFX900-NEXT:    s_load_dword s6, s[4:5], 0x2c
; GFX900-NEXT:    s_mov_b64 s[2:3], exec
; GFX900-NEXT:    v_mbcnt_lo_u32_b32 v0, s2, 0
; GFX900-NEXT:    v_mbcnt_hi_u32_b32 v0, s3, v0
; GFX900-NEXT:    v_cmp_eq_u32_e32 vcc, 0, v0
; GFX900-NEXT:    ; implicit-def: $vgpr1
; GFX900-NEXT:    s_and_saveexec_b64 s[0:1], vcc
; GFX900-NEXT:    s_cbranch_execz .LBB3_2
; GFX900-NEXT:  ; %bb.1:
; GFX900-NEXT:    s_bcnt1_i32_b64 s2, s[2:3]
; GFX900-NEXT:    s_waitcnt lgkmcnt(0)
; GFX900-NEXT:    s_mul_i32 s2, s6, s2
; GFX900-NEXT:    v_mov_b32_e32 v1, 0
; GFX900-NEXT:    v_mov_b32_e32 v2, s2
; GFX900-NEXT:    ds_add_rtn_u32 v1, v1, v2
; GFX900-NEXT:    s_waitcnt lgkmcnt(0)
; GFX900-NEXT:  .LBB3_2:
; GFX900-NEXT:    s_or_b64 exec, exec, s[0:1]
; GFX900-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x24
; GFX900-NEXT:    s_waitcnt lgkmcnt(0)
; GFX900-NEXT:    v_mul_lo_u32 v0, s6, v0
; GFX900-NEXT:    v_readfirstlane_b32 s4, v1
; GFX900-NEXT:    s_mov_b32 s3, 0xf000
; GFX900-NEXT:    s_mov_b32 s2, -1
; GFX900-NEXT:    v_add_u32_e32 v0, s4, v0
; GFX900-NEXT:    buffer_store_dword v0, off, s[0:3], 0
; GFX900-NEXT:    s_endpgm
entry:
  %old = atomicrmw add ptr addrspace(3) @local_var32, i32 %additive acq_rel, !amdgpu.atomic.lds.dpp !0
  store i32 %old, ptr addrspace(1) %out
  ret void
}

; Test 5: divergent float fadd with result used -- dynamic threshold branch expected
define amdgpu_kernel void @fadd_f32_varying(ptr addrspace(1) %out) {
; GFX1032-LABEL: fadd_f32_varying:
; GFX1032:       ; %bb.0: ; %entry
; GFX1032-NEXT:    v_cvt_f32_i32_e32 v0, v0
; GFX1032-NEXT:    s_bcnt1_i32_b32 s0, exec_lo
; GFX1032-NEXT:    s_cmp_lt_u32 s0, 6
; GFX1032-NEXT:    s_cbranch_scc0 .LBB4_2
; GFX1032-NEXT:  ; %bb.1:
; GFX1032-NEXT:    v_mov_b32_e32 v4, 0
; GFX1032-NEXT:    ds_add_rtn_f32 v4, v4, v0
; GFX1032-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1032-NEXT:    buffer_gl0_inv
; GFX1032-NEXT:    s_cbranch_execz .LBB4_3
; GFX1032-NEXT:    s_branch .LBB4_6
; GFX1032-NEXT:  .LBB4_2:
; GFX1032-NEXT:    ; implicit-def: $vgpr4
; GFX1032-NEXT:  .LBB4_3:
; GFX1032-NEXT:    s_or_saveexec_b32 s0, -1
; GFX1032-NEXT:    v_cndmask_b32_e64 v1, 0x80000000, v0, s0
; GFX1032-NEXT:    v_bfrev_b32_e32 v2, 1
; GFX1032-NEXT:    v_bfrev_b32_e32 v3, 1
; GFX1032-NEXT:    v_mov_b32_dpp v2, v1 row_shr:1 row_mask:0xf bank_mask:0xf
; GFX1032-NEXT:    v_add_f32_e32 v1, v1, v2
; GFX1032-NEXT:    v_bfrev_b32_e32 v2, 1
; GFX1032-NEXT:    v_mov_b32_dpp v3, v1 row_shr:2 row_mask:0xf bank_mask:0xf
; GFX1032-NEXT:    v_add_f32_e32 v1, v1, v3
; GFX1032-NEXT:    v_bfrev_b32_e32 v3, 1
; GFX1032-NEXT:    v_mov_b32_dpp v2, v1 row_shr:4 row_mask:0xf bank_mask:0xf
; GFX1032-NEXT:    v_add_f32_e32 v1, v1, v2
; GFX1032-NEXT:    v_bfrev_b32_e32 v2, 1
; GFX1032-NEXT:    v_mov_b32_dpp v3, v1 row_shr:8 row_mask:0xf bank_mask:0xf
; GFX1032-NEXT:    v_add_f32_e32 v1, v1, v3
; GFX1032-NEXT:    v_permlanex16_b32 v3, v1, -1, -1
; GFX1032-NEXT:    v_mov_b32_dpp v2, v3 quad_perm:[0,1,2,3] row_mask:0xa bank_mask:0xf
; GFX1032-NEXT:    v_bfrev_b32_e32 v3, 1
; GFX1032-NEXT:    v_add_f32_e32 v1, v1, v2
; GFX1032-NEXT:    v_readlane_b32 s2, v1, 31
; GFX1032-NEXT:    v_mov_b32_dpp v3, v1 row_shr:1 row_mask:0xf bank_mask:0xf
; GFX1032-NEXT:    v_readlane_b32 s1, v1, 15
; GFX1032-NEXT:    s_mov_b32 exec_lo, s0
; GFX1032-NEXT:    v_mbcnt_lo_u32_b32 v0, exec_lo, 0
; GFX1032-NEXT:    s_or_saveexec_b32 s0, -1
; GFX1032-NEXT:    v_writelane_b32 v3, s1, 16
; GFX1032-NEXT:    s_mov_b32 exec_lo, s0
; GFX1032-NEXT:    v_cmp_eq_u32_e32 vcc_lo, 0, v0
; GFX1032-NEXT:    ; implicit-def: $vgpr0
; GFX1032-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX1032-NEXT:    s_cbranch_execz .LBB4_5
; GFX1032-NEXT:  ; %bb.4:
; GFX1032-NEXT:    v_mov_b32_e32 v0, 0
; GFX1032-NEXT:    v_mov_b32_e32 v4, s2
; GFX1032-NEXT:    s_waitcnt_vscnt null, 0x0
; GFX1032-NEXT:    ds_add_rtn_f32 v0, v0, v4
; GFX1032-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1032-NEXT:    buffer_gl0_inv
; GFX1032-NEXT:  .LBB4_5:
; GFX1032-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX1032-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX1032-NEXT:    v_readfirstlane_b32 s0, v0
; GFX1032-NEXT:    v_mov_b32_e32 v0, v3
; GFX1032-NEXT:    v_add_f32_e32 v0, s0, v0
; GFX1032-NEXT:    v_cndmask_b32_e64 v4, v0, s0, vcc_lo
; GFX1032-NEXT:  .LBB4_6:
; GFX1032-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x24
; GFX1032-NEXT:    s_mov_b32 s3, 0x31016000
; GFX1032-NEXT:    s_mov_b32 s2, -1
; GFX1032-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1032-NEXT:    buffer_store_dword v4, off, s[0:3], 0
; GFX1032-NEXT:    s_endpgm
;
; GFX1064-LABEL: fadd_f32_varying:
; GFX1064:       ; %bb.0: ; %entry
; GFX1064-NEXT:    v_cvt_f32_i32_e32 v0, v0
; GFX1064-NEXT:    s_bcnt1_i32_b64 s0, exec
; GFX1064-NEXT:    s_cmp_lt_u32 s0, 6
; GFX1064-NEXT:    s_cbranch_scc0 .LBB4_2
; GFX1064-NEXT:  ; %bb.1:
; GFX1064-NEXT:    v_mov_b32_e32 v4, 0
; GFX1064-NEXT:    ds_add_rtn_f32 v4, v4, v0
; GFX1064-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1064-NEXT:    buffer_gl0_inv
; GFX1064-NEXT:    s_cbranch_execz .LBB4_3
; GFX1064-NEXT:    s_branch .LBB4_6
; GFX1064-NEXT:  .LBB4_2:
; GFX1064-NEXT:    ; implicit-def: $vgpr4
; GFX1064-NEXT:  .LBB4_3:
; GFX1064-NEXT:    s_or_saveexec_b64 s[0:1], -1
; GFX1064-NEXT:    v_cndmask_b32_e64 v1, 0x80000000, v0, s[0:1]
; GFX1064-NEXT:    v_bfrev_b32_e32 v2, 1
; GFX1064-NEXT:    v_bfrev_b32_e32 v3, 1
; GFX1064-NEXT:    v_mov_b32_dpp v2, v1 row_shr:1 row_mask:0xf bank_mask:0xf
; GFX1064-NEXT:    v_add_f32_e32 v1, v1, v2
; GFX1064-NEXT:    v_bfrev_b32_e32 v2, 1
; GFX1064-NEXT:    v_mov_b32_dpp v3, v1 row_shr:2 row_mask:0xf bank_mask:0xf
; GFX1064-NEXT:    v_add_f32_e32 v1, v1, v3
; GFX1064-NEXT:    v_bfrev_b32_e32 v3, 1
; GFX1064-NEXT:    v_mov_b32_dpp v2, v1 row_shr:4 row_mask:0xf bank_mask:0xf
; GFX1064-NEXT:    v_add_f32_e32 v1, v1, v2
; GFX1064-NEXT:    v_bfrev_b32_e32 v2, 1
; GFX1064-NEXT:    v_mov_b32_dpp v3, v1 row_shr:8 row_mask:0xf bank_mask:0xf
; GFX1064-NEXT:    v_add_f32_e32 v1, v1, v3
; GFX1064-NEXT:    v_permlanex16_b32 v3, v1, -1, -1
; GFX1064-NEXT:    v_mov_b32_dpp v2, v3 quad_perm:[0,1,2,3] row_mask:0xa bank_mask:0xf
; GFX1064-NEXT:    v_add_f32_e32 v1, v1, v2
; GFX1064-NEXT:    v_bfrev_b32_e32 v2, 1
; GFX1064-NEXT:    v_readlane_b32 s2, v1, 31
; GFX1064-NEXT:    v_mov_b32_e32 v3, s2
; GFX1064-NEXT:    v_mov_b32_dpp v2, v3 quad_perm:[0,1,2,3] row_mask:0xc bank_mask:0xf
; GFX1064-NEXT:    v_bfrev_b32_e32 v3, 1
; GFX1064-NEXT:    v_add_f32_e32 v1, v1, v2
; GFX1064-NEXT:    v_mov_b32_dpp v3, v1 row_shr:1 row_mask:0xf bank_mask:0xf
; GFX1064-NEXT:    v_readlane_b32 s2, v1, 15
; GFX1064-NEXT:    v_readlane_b32 s3, v1, 31
; GFX1064-NEXT:    v_writelane_b32 v3, s2, 16
; GFX1064-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1064-NEXT:    v_mbcnt_lo_u32_b32 v0, exec_lo, 0
; GFX1064-NEXT:    s_or_saveexec_b64 s[0:1], -1
; GFX1064-NEXT:    v_readlane_b32 s2, v1, 63
; GFX1064-NEXT:    v_readlane_b32 s6, v1, 47
; GFX1064-NEXT:    v_writelane_b32 v3, s3, 32
; GFX1064-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1064-NEXT:    v_mbcnt_hi_u32_b32 v0, exec_hi, v0
; GFX1064-NEXT:    s_or_saveexec_b64 s[0:1], -1
; GFX1064-NEXT:    v_writelane_b32 v3, s6, 48
; GFX1064-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1064-NEXT:    v_cmp_eq_u32_e32 vcc, 0, v0
; GFX1064-NEXT:    ; implicit-def: $vgpr0
; GFX1064-NEXT:    s_and_saveexec_b64 s[0:1], vcc
; GFX1064-NEXT:    s_cbranch_execz .LBB4_5
; GFX1064-NEXT:  ; %bb.4:
; GFX1064-NEXT:    v_mov_b32_e32 v0, 0
; GFX1064-NEXT:    v_mov_b32_e32 v4, s2
; GFX1064-NEXT:    s_waitcnt_vscnt null, 0x0
; GFX1064-NEXT:    ds_add_rtn_f32 v0, v0, v4
; GFX1064-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1064-NEXT:    buffer_gl0_inv
; GFX1064-NEXT:  .LBB4_5:
; GFX1064-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX1064-NEXT:    s_or_b64 exec, exec, s[0:1]
; GFX1064-NEXT:    v_readfirstlane_b32 s0, v0
; GFX1064-NEXT:    v_mov_b32_e32 v0, v3
; GFX1064-NEXT:    v_add_f32_e32 v0, s0, v0
; GFX1064-NEXT:    v_cndmask_b32_e64 v4, v0, s0, vcc
; GFX1064-NEXT:  .LBB4_6:
; GFX1064-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x24
; GFX1064-NEXT:    s_mov_b32 s3, 0x31016000
; GFX1064-NEXT:    s_mov_b32 s2, -1
; GFX1064-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1064-NEXT:    buffer_store_dword v4, off, s[0:3], 0
; GFX1064-NEXT:    s_endpgm
;
; GFX900-LABEL: fadd_f32_varying:
; GFX900:       ; %bb.0: ; %entry
; GFX900-NEXT:    v_cvt_f32_i32_e32 v0, v0
; GFX900-NEXT:    s_bcnt1_i32_b64 s0, exec
; GFX900-NEXT:    s_cmp_lt_u32 s0, 6
; GFX900-NEXT:    s_cbranch_scc0 .LBB4_2
; GFX900-NEXT:  ; %bb.1:
; GFX900-NEXT:    v_mov_b32_e32 v4, 0
; GFX900-NEXT:    ds_add_rtn_f32 v4, v4, v0
; GFX900-NEXT:    s_waitcnt lgkmcnt(0)
; GFX900-NEXT:    s_cbranch_execz .LBB4_3
; GFX900-NEXT:    s_branch .LBB4_6
; GFX900-NEXT:  .LBB4_2:
; GFX900-NEXT:    ; implicit-def: $vgpr4
; GFX900-NEXT:  .LBB4_3:
; GFX900-NEXT:    v_mbcnt_lo_u32_b32 v4, exec_lo, 0
; GFX900-NEXT:    v_mbcnt_hi_u32_b32 v4, exec_hi, v4
; GFX900-NEXT:    s_or_saveexec_b64 s[0:1], -1
; GFX900-NEXT:    v_bfrev_b32_e32 v1, 1
; GFX900-NEXT:    v_cndmask_b32_e64 v2, v1, v0, s[0:1]
; GFX900-NEXT:    v_bfrev_b32_e32 v3, 1
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_mov_b32_dpp v3, v2 row_shr:1 row_mask:0xf bank_mask:0xf
; GFX900-NEXT:    v_add_f32_e32 v2, v2, v3
; GFX900-NEXT:    v_bfrev_b32_e32 v3, 1
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_mov_b32_dpp v3, v2 row_shr:2 row_mask:0xf bank_mask:0xf
; GFX900-NEXT:    v_add_f32_e32 v2, v2, v3
; GFX900-NEXT:    v_bfrev_b32_e32 v3, 1
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_mov_b32_dpp v3, v2 row_shr:4 row_mask:0xf bank_mask:0xf
; GFX900-NEXT:    v_add_f32_e32 v2, v2, v3
; GFX900-NEXT:    v_bfrev_b32_e32 v3, 1
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_mov_b32_dpp v3, v2 row_shr:8 row_mask:0xf bank_mask:0xf
; GFX900-NEXT:    v_add_f32_e32 v2, v2, v3
; GFX900-NEXT:    v_bfrev_b32_e32 v3, 1
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_mov_b32_dpp v3, v2 row_bcast:15 row_mask:0xa bank_mask:0xf
; GFX900-NEXT:    v_add_f32_e32 v2, v2, v3
; GFX900-NEXT:    v_bfrev_b32_e32 v3, 1
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_mov_b32_dpp v3, v2 row_bcast:31 row_mask:0xc bank_mask:0xf
; GFX900-NEXT:    v_add_f32_e32 v2, v2, v3
; GFX900-NEXT:    v_readlane_b32 s2, v2, 63
; GFX900-NEXT:    s_nop 0
; GFX900-NEXT:    v_mov_b32_dpp v1, v2 wave_shr:1 row_mask:0xf bank_mask:0xf
; GFX900-NEXT:    s_mov_b64 exec, s[0:1]
; GFX900-NEXT:    v_cmp_eq_u32_e32 vcc, 0, v4
; GFX900-NEXT:    ; implicit-def: $vgpr0
; GFX900-NEXT:    s_and_saveexec_b64 s[0:1], vcc
; GFX900-NEXT:    s_cbranch_execz .LBB4_5
; GFX900-NEXT:  ; %bb.4:
; GFX900-NEXT:    v_mov_b32_e32 v0, 0
; GFX900-NEXT:    v_mov_b32_e32 v4, s2
; GFX900-NEXT:    ds_add_rtn_f32 v0, v0, v4
; GFX900-NEXT:    s_waitcnt lgkmcnt(0)
; GFX900-NEXT:  .LBB4_5:
; GFX900-NEXT:    s_or_b64 exec, exec, s[0:1]
; GFX900-NEXT:    v_readfirstlane_b32 s0, v0
; GFX900-NEXT:    v_mov_b32_e32 v0, v1
; GFX900-NEXT:    v_add_f32_e32 v0, s0, v0
; GFX900-NEXT:    v_mov_b32_e32 v4, s0
; GFX900-NEXT:    v_cndmask_b32_e32 v4, v0, v4, vcc
; GFX900-NEXT:  .LBB4_6:
; GFX900-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x24
; GFX900-NEXT:    s_mov_b32 s3, 0xf000
; GFX900-NEXT:    s_mov_b32 s2, -1
; GFX900-NEXT:    s_waitcnt lgkmcnt(0)
; GFX900-NEXT:    buffer_store_dword v4, off, s[0:3], 0
; GFX900-NEXT:    s_endpgm
entry:
  %lane = call i32 @llvm.amdgcn.workitem.id.x()
  %conv = sitofp i32 %lane to float
  %rmw = atomicrmw fadd ptr addrspace(3) @local_var32, float %conv syncscope("agent") acq_rel, !amdgpu.atomic.lds.dpp !0
  store float %rmw, ptr addrspace(1) %out
  ret void
}

; Test 6: divergent i32 add on GLOBAL memory -- should NOT be affected by metadata
define amdgpu_kernel void @add_i32_varying_global(ptr addrspace(1) %out, ptr addrspace(1) %inout) {
; GFX1032-LABEL: add_i32_varying_global:
; GFX1032:       ; %bb.0: ; %entry
; GFX1032-NEXT:    s_or_saveexec_b32 s0, -1
; GFX1032-NEXT:    v_cndmask_b32_e64 v1, 0, v0, s0
; GFX1032-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_shr:1 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1032-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_shr:2 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1032-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_shr:4 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1032-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_shr:8 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1032-NEXT:    v_permlanex16_b32 v2, v1, -1, -1
; GFX1032-NEXT:    s_mov_b32 exec_lo, s0
; GFX1032-NEXT:    s_load_dwordx4 s[0:3], s[4:5], 0x24
; GFX1032-NEXT:    s_or_saveexec_b32 s4, -1
; GFX1032-NEXT:    v_add_nc_u32_dpp v1, v2, v1 quad_perm:[0,1,2,3] row_mask:0xa bank_mask:0xf
; GFX1032-NEXT:    v_mov_b32_e32 v3, 0
; GFX1032-NEXT:    v_readlane_b32 s6, v1, 31
; GFX1032-NEXT:    v_mov_b32_dpp v3, v1 row_shr:1 row_mask:0xf bank_mask:0xf
; GFX1032-NEXT:    v_readlane_b32 s5, v1, 15
; GFX1032-NEXT:    s_mov_b32 exec_lo, s4
; GFX1032-NEXT:    v_mbcnt_lo_u32_b32 v0, exec_lo, 0
; GFX1032-NEXT:    s_or_saveexec_b32 s4, -1
; GFX1032-NEXT:    v_writelane_b32 v3, s5, 16
; GFX1032-NEXT:    s_mov_b32 exec_lo, s4
; GFX1032-NEXT:    v_cmp_eq_u32_e32 vcc_lo, 0, v0
; GFX1032-NEXT:    s_mov_b32 s4, s6
; GFX1032-NEXT:    s_mov_b32 s6, -1
; GFX1032-NEXT:    ; implicit-def: $vgpr0
; GFX1032-NEXT:    s_and_saveexec_b32 s8, vcc_lo
; GFX1032-NEXT:    s_cbranch_execz .LBB5_2
; GFX1032-NEXT:  ; %bb.1:
; GFX1032-NEXT:    v_mov_b32_e32 v0, s4
; GFX1032-NEXT:    s_mov_b32 s7, 0x31016000
; GFX1032-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1032-NEXT:    s_mov_b32 s4, s2
; GFX1032-NEXT:    s_mov_b32 s5, s3
; GFX1032-NEXT:    buffer_atomic_add v0, off, s[4:7], 0 glc
; GFX1032-NEXT:    s_waitcnt vmcnt(0)
; GFX1032-NEXT:    buffer_gl1_inv
; GFX1032-NEXT:    buffer_gl0_inv
; GFX1032-NEXT:  .LBB5_2:
; GFX1032-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX1032-NEXT:    s_or_b32 exec_lo, exec_lo, s8
; GFX1032-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1032-NEXT:    v_readfirstlane_b32 s2, v0
; GFX1032-NEXT:    v_mov_b32_e32 v0, v3
; GFX1032-NEXT:    s_mov_b32 s3, 0x31016000
; GFX1032-NEXT:    v_add_nc_u32_e32 v0, s2, v0
; GFX1032-NEXT:    s_mov_b32 s2, s6
; GFX1032-NEXT:    buffer_store_dword v0, off, s[0:3], 0
; GFX1032-NEXT:    s_endpgm
;
; GFX1064-LABEL: add_i32_varying_global:
; GFX1064:       ; %bb.0: ; %entry
; GFX1064-NEXT:    s_or_saveexec_b64 s[0:1], -1
; GFX1064-NEXT:    v_cndmask_b32_e64 v1, 0, v0, s[0:1]
; GFX1064-NEXT:    v_mov_b32_e32 v3, 0
; GFX1064-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_shr:1 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1064-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_shr:2 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1064-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_shr:4 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1064-NEXT:    v_add_nc_u32_dpp v1, v1, v1 row_shr:8 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX1064-NEXT:    v_permlanex16_b32 v2, v1, -1, -1
; GFX1064-NEXT:    v_add_nc_u32_dpp v1, v2, v1 quad_perm:[0,1,2,3] row_mask:0xa bank_mask:0xf
; GFX1064-NEXT:    v_readlane_b32 s2, v1, 31
; GFX1064-NEXT:    v_mov_b32_e32 v2, s2
; GFX1064-NEXT:    v_add_nc_u32_dpp v1, v2, v1 quad_perm:[0,1,2,3] row_mask:0xc bank_mask:0xf
; GFX1064-NEXT:    v_readlane_b32 s6, v1, 15
; GFX1064-NEXT:    v_mov_b32_dpp v3, v1 row_shr:1 row_mask:0xf bank_mask:0xf
; GFX1064-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1064-NEXT:    s_load_dwordx4 s[0:3], s[4:5], 0x24
; GFX1064-NEXT:    s_or_saveexec_b64 s[4:5], -1
; GFX1064-NEXT:    v_readlane_b32 s7, v1, 31
; GFX1064-NEXT:    v_writelane_b32 v3, s6, 16
; GFX1064-NEXT:    s_mov_b64 exec, s[4:5]
; GFX1064-NEXT:    v_mbcnt_lo_u32_b32 v0, exec_lo, 0
; GFX1064-NEXT:    s_or_saveexec_b64 s[4:5], -1
; GFX1064-NEXT:    v_readlane_b32 s8, v1, 47
; GFX1064-NEXT:    v_readlane_b32 s9, v1, 63
; GFX1064-NEXT:    v_writelane_b32 v3, s7, 32
; GFX1064-NEXT:    s_mov_b64 exec, s[4:5]
; GFX1064-NEXT:    v_mbcnt_hi_u32_b32 v0, exec_hi, v0
; GFX1064-NEXT:    s_or_saveexec_b64 s[6:7], -1
; GFX1064-NEXT:    s_mov_b32 s4, s9
; GFX1064-NEXT:    v_writelane_b32 v3, s8, 48
; GFX1064-NEXT:    s_mov_b64 exec, s[6:7]
; GFX1064-NEXT:    v_cmp_eq_u32_e32 vcc, 0, v0
; GFX1064-NEXT:    s_mov_b32 s6, -1
; GFX1064-NEXT:    ; implicit-def: $vgpr0
; GFX1064-NEXT:    s_and_saveexec_b64 s[8:9], vcc
; GFX1064-NEXT:    s_cbranch_execz .LBB5_2
; GFX1064-NEXT:  ; %bb.1:
; GFX1064-NEXT:    v_mov_b32_e32 v0, s4
; GFX1064-NEXT:    s_mov_b32 s7, 0x31016000
; GFX1064-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1064-NEXT:    s_mov_b32 s4, s2
; GFX1064-NEXT:    s_mov_b32 s5, s3
; GFX1064-NEXT:    buffer_atomic_add v0, off, s[4:7], 0 glc
; GFX1064-NEXT:    s_waitcnt vmcnt(0)
; GFX1064-NEXT:    buffer_gl1_inv
; GFX1064-NEXT:    buffer_gl0_inv
; GFX1064-NEXT:  .LBB5_2:
; GFX1064-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX1064-NEXT:    s_or_b64 exec, exec, s[8:9]
; GFX1064-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1064-NEXT:    v_readfirstlane_b32 s2, v0
; GFX1064-NEXT:    v_mov_b32_e32 v0, v3
; GFX1064-NEXT:    s_mov_b32 s3, 0x31016000
; GFX1064-NEXT:    v_add_nc_u32_e32 v0, s2, v0
; GFX1064-NEXT:    s_mov_b32 s2, s6
; GFX1064-NEXT:    buffer_store_dword v0, off, s[0:3], 0
; GFX1064-NEXT:    s_endpgm
;
; GFX900-LABEL: add_i32_varying_global:
; GFX900:       ; %bb.0: ; %entry
; GFX900-NEXT:    s_load_dwordx4 s[0:3], s[4:5], 0x24
; GFX900-NEXT:    s_or_saveexec_b64 s[4:5], -1
; GFX900-NEXT:    v_mov_b32_e32 v1, 0
; GFX900-NEXT:    s_mov_b64 exec, s[4:5]
; GFX900-NEXT:    v_mbcnt_lo_u32_b32 v3, exec_lo, 0
; GFX900-NEXT:    v_mbcnt_hi_u32_b32 v3, exec_hi, v3
; GFX900-NEXT:    s_or_saveexec_b64 s[4:5], -1
; GFX900-NEXT:    v_cndmask_b32_e64 v2, 0, v0, s[4:5]
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_add_u32_dpp v2, v2, v2 row_shr:1 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_add_u32_dpp v2, v2, v2 row_shr:2 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_add_u32_dpp v2, v2, v2 row_shr:4 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_add_u32_dpp v2, v2, v2 row_shr:8 row_mask:0xf bank_mask:0xf bound_ctrl:1
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_add_u32_dpp v2, v2, v2 row_bcast:15 row_mask:0xa bank_mask:0xf
; GFX900-NEXT:    s_nop 1
; GFX900-NEXT:    v_add_u32_dpp v2, v2, v2 row_bcast:31 row_mask:0xc bank_mask:0xf
; GFX900-NEXT:    v_readlane_b32 s6, v2, 63
; GFX900-NEXT:    s_nop 0
; GFX900-NEXT:    v_mov_b32_dpp v1, v2 wave_shr:1 row_mask:0xf bank_mask:0xf
; GFX900-NEXT:    s_mov_b64 exec, s[4:5]
; GFX900-NEXT:    v_cmp_eq_u32_e32 vcc, 0, v3
; GFX900-NEXT:    ; implicit-def: $vgpr0
; GFX900-NEXT:    s_and_saveexec_b64 s[4:5], vcc
; GFX900-NEXT:    s_cbranch_execz .LBB5_2
; GFX900-NEXT:  ; %bb.1:
; GFX900-NEXT:    s_mov_b32 s11, 0xf000
; GFX900-NEXT:    s_mov_b32 s10, -1
; GFX900-NEXT:    s_waitcnt lgkmcnt(0)
; GFX900-NEXT:    s_mov_b32 s8, s2
; GFX900-NEXT:    s_mov_b32 s9, s3
; GFX900-NEXT:    v_mov_b32_e32 v0, s6
; GFX900-NEXT:    buffer_atomic_add v0, off, s[8:11], 0 glc
; GFX900-NEXT:    s_waitcnt vmcnt(0)
; GFX900-NEXT:    buffer_wbinvl1_vol
; GFX900-NEXT:  .LBB5_2:
; GFX900-NEXT:    s_or_b64 exec, exec, s[4:5]
; GFX900-NEXT:    v_readfirstlane_b32 s4, v0
; GFX900-NEXT:    v_mov_b32_e32 v0, v1
; GFX900-NEXT:    s_waitcnt lgkmcnt(0)
; GFX900-NEXT:    s_mov_b32 s3, 0xf000
; GFX900-NEXT:    s_mov_b32 s2, -1
; GFX900-NEXT:    v_add_u32_e32 v0, s4, v0
; GFX900-NEXT:    buffer_store_dword v0, off, s[0:3], 0
; GFX900-NEXT:    s_endpgm
entry:
  %lane = call i32 @llvm.amdgcn.workitem.id.x()
  %old = atomicrmw add ptr addrspace(1) %inout, i32 %lane acq_rel, !amdgpu.atomic.lds.dpp !0
  store i32 %old, ptr addrspace(1) %out
  ret void
}

; Test 7: !amdgpu.atomic.lds.dpp !{!"none"} disables DPP -- plain atomic expected
define amdgpu_kernel void @add_i32_varying_no_lds_dpp(ptr addrspace(1) %out) {
; GFX1032-LABEL: add_i32_varying_no_lds_dpp:
; GFX1032:       ; %bb.0: ; %entry
; GFX1032-NEXT:    v_mov_b32_e32 v1, 0
; GFX1032-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x24
; GFX1032-NEXT:    s_mov_b32 s3, 0x31016000
; GFX1032-NEXT:    s_mov_b32 s2, -1
; GFX1032-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1032-NEXT:    ds_add_rtn_u32 v0, v1, v0
; GFX1032-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1032-NEXT:    buffer_gl0_inv
; GFX1032-NEXT:    buffer_store_dword v0, off, s[0:3], 0
; GFX1032-NEXT:    s_endpgm
;
; GFX1064-LABEL: add_i32_varying_no_lds_dpp:
; GFX1064:       ; %bb.0: ; %entry
; GFX1064-NEXT:    v_mov_b32_e32 v1, 0
; GFX1064-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x24
; GFX1064-NEXT:    s_mov_b32 s3, 0x31016000
; GFX1064-NEXT:    s_mov_b32 s2, -1
; GFX1064-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1064-NEXT:    ds_add_rtn_u32 v0, v1, v0
; GFX1064-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1064-NEXT:    buffer_gl0_inv
; GFX1064-NEXT:    buffer_store_dword v0, off, s[0:3], 0
; GFX1064-NEXT:    s_endpgm
;
; GFX900-LABEL: add_i32_varying_no_lds_dpp:
; GFX900:       ; %bb.0: ; %entry
; GFX900-NEXT:    v_mov_b32_e32 v1, 0
; GFX900-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x24
; GFX900-NEXT:    s_waitcnt lgkmcnt(0)
; GFX900-NEXT:    ds_add_rtn_u32 v0, v1, v0
; GFX900-NEXT:    s_waitcnt lgkmcnt(0)
; GFX900-NEXT:    s_mov_b32 s3, 0xf000
; GFX900-NEXT:    s_mov_b32 s2, -1
; GFX900-NEXT:    buffer_store_dword v0, off, s[0:3], 0
; GFX900-NEXT:    s_endpgm
entry:
  %lane = call i32 @llvm.amdgcn.workitem.id.x()
  %old = atomicrmw add ptr addrspace(3) @local_var32, i32 %lane acq_rel, !amdgpu.atomic.lds.dpp !1
  store i32 %old, ptr addrspace(1) %out
  ret void
}

!0 = !{!"dynamic"}
!1 = !{!"none"}
