# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -march=amdgcn -mcpu=gfx1300 -verify-machineinstrs -run-pass=bundle-indexed-load-store -o - %s | FileCheck -check-prefixes=GCN %s
# RUN: llc -march=amdgcn -mcpu=gfx1300 -verify-machineinstrs -start-before=bundle-indexed-load-store -stop-after=amdgpu-idx-reg-alloc -o - %s | FileCheck -check-prefixes=ALLOC %s
# RUN: llc -march=amdgcn -mcpu=gfx1300 -verify-machineinstrs -start-before=bundle-indexed-load-store -stop-after=amdgpu-lower-vgpr-encoding -o - %s | FileCheck -check-prefixes=LOWERED %s

---
name:            same-bb-vopm-bpermute
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: same-bb-vopm-bpermute
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 3, implicit-def $scc
    ; GCN-NEXT: [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def $scc
    ; GCN-NEXT: BUNDLE implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHL_B32_2]], implicit $exec, implicit [[S_LSHL_B32_1]], implicit [[S_LSHL_B32_]] {
    ; GCN-NEXT:   $stg_srcb = V_LOAD_IDX [[S_LSHL_B32_2]], 10, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_1]], 0, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_dsta = V_BPERMUTE_B32 internal $stg_srca, internal $stg_srcb, 0, 0, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_]], 0, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: same-bb-vopm-bpermute
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 3, implicit-def $scc
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_1]]
    ; ALLOC-NEXT: [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def $scc
    ; ALLOC-NEXT: $idx3 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_2]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def $stg_dsta, implicit $idx3, implicit $exec, implicit $idx2, implicit $idx1 {
    ; ALLOC-NEXT:   $stg_srcb = V_LOAD_IDX $idx3, 10, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx2, 0, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta = V_BPERMUTE_B32 internal $stg_srca, internal $stg_srcb, 0, 0, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 0, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: same-bb-vopm-bpermute
    ; LOWERED: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr1 = S_LSHL_B32 1, 3, implicit-def dead $scc
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 4, implicit-def dead $scc
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    ; LOWERED-NEXT: $idx3 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: undef $vgpr0 = V_BPERMUTE_B32 undef $vgpr0, undef $vgpr10, 801, 0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:sreg_32_xexec_hi = S_LSHL_B32 1, 3, implicit-def $scc
    %2:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def $scc
    %3:vgpr_32 = V_LOAD_IDX %1, 0, implicit $exec :: (load (s32), addrspace 10)
    %4:vgpr_32 = V_LOAD_IDX %2, 10, implicit $exec :: (load (s32), addrspace 10)
    %5:vgpr_32 = V_BPERMUTE_B32 %3:vgpr_32, %4:vgpr_32, 0, 0, implicit $exec
    V_STORE_IDX %5:vgpr_32, %0, 0, implicit $exec :: (store (s32), addrspace 10)
...

---
name:            same-bb-vopm-convolve
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: same-bb-vopm-convolve
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 3, implicit-def $scc
    ; GCN-NEXT: [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def $scc
    ; GCN-NEXT: BUNDLE implicit-def dead $stg_srcf, implicit-def dead $stg_srce, implicit-def dead $stg_srcd, implicit-def dead $stg_srcc, implicit-def dead $stg_srcb, implicit-def dead $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHL_B32_1]], implicit $exec, implicit [[S_LSHL_B32_2]], implicit [[S_LSHL_B32_]] {
    ; GCN-NEXT:   $stg_srcf = V_LOAD_IDX [[S_LSHL_B32_1]], 4, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srce = V_LOAD_IDX [[S_LSHL_B32_2]], 5, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srcd = V_LOAD_IDX [[S_LSHL_B32_2]], 6, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srcc = V_LOAD_IDX [[S_LSHL_B32_2]], 7, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srcb = V_LOAD_IDX [[S_LSHL_B32_2]], 8, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_2]], 12, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; GCN-NEXT:   $stg_dsta = V_CONVOLVE_BF16_BF16_1x1_4x4_ITER_4 internal killed $stg_srca, internal killed $stg_srcb, internal killed $stg_srcc, internal killed $stg_srcd, internal killed $stg_srce, internal killed $stg_srcf, 12290, -1, 0, 0, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_]], 0, implicit $exec :: (store (s128), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: same-bb-vopm-convolve
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 3, implicit-def $scc
    ; ALLOC-NEXT: $idx3 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_1]]
    ; ALLOC-NEXT: [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def $scc
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_2]]
    ; ALLOC-NEXT: BUNDLE implicit-def dead $stg_srcf, implicit-def dead $stg_srce, implicit-def dead $stg_srcd, implicit-def dead $stg_srcc, implicit-def dead $stg_srcb, implicit-def dead $stg_srca, implicit-def $stg_dsta, implicit $idx3, implicit $exec, implicit $idx2, implicit $idx1 {
    ; ALLOC-NEXT:   $stg_srcf = V_LOAD_IDX $idx3, 4, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srce = V_LOAD_IDX $idx2, 5, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srcd = V_LOAD_IDX $idx2, 6, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srcc = V_LOAD_IDX $idx2, 7, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srcb = V_LOAD_IDX $idx2, 8, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx2, 12, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta = V_CONVOLVE_BF16_BF16_1x1_4x4_ITER_4 internal killed $stg_srca, internal killed $stg_srcb, internal killed $stg_srcc, internal killed $stg_srcd, internal killed $stg_srce, internal killed $stg_srcf, 12290, -1, 0, 0, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 0, implicit $exec :: (store (s128), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: same-bb-vopm-convolve
    ; LOWERED: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr1 = S_LSHL_B32 1, 3, implicit-def dead $scc
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 4, implicit-def dead $scc
    ; LOWERED-NEXT: $idx3 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: undef $vgpr0_vgpr1_vgpr2_vgpr3 = V_CONVOLVE_BF16_BF16_1x1_4x4_ITER_4 killed undef $vgpr12_vgpr13_vgpr14_vgpr15, killed undef $vgpr8_vgpr9_vgpr10_vgpr11, killed undef $vgpr7, killed undef $vgpr6, killed undef $vgpr5, killed undef $vgpr4, 12290, -1, 52568609, 0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:sreg_32_xexec_hi = S_LSHL_B32 1, 3, implicit-def $scc
    %2:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def $scc
    %3:vreg_128_align2 = V_LOAD_IDX %2:sreg_32_xexec_hi, 12, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    %4:vreg_128_align2 = V_LOAD_IDX %2:sreg_32_xexec_hi, 8, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    %5:vgpr_32 = V_LOAD_IDX %2:sreg_32_xexec_hi, 7, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    %6:vgpr_32 = V_LOAD_IDX %2:sreg_32_xexec_hi, 6, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    %7:vgpr_32 = V_LOAD_IDX %2:sreg_32_xexec_hi, 5, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    %8:vgpr_32 = V_LOAD_IDX %1:sreg_32_xexec_hi, 4, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    %9:vreg_128_align2 = V_CONVOLVE_BF16_BF16_1x1_4x4_ITER_4 killed %3:vreg_128_align2, killed %4:vreg_128_align2, killed %5:vgpr_32, killed %6:vgpr_32, killed %7:vgpr_32, killed %8:vgpr_32, 12290, -1, 0, 0, implicit $exec
    V_STORE_IDX %9:vreg_128_align2, %0:sreg_32_xexec_hi, 0, implicit $exec :: (store (s128), addrspace 10)
...

---
name:            same-bb-vopm-fma-from-tensor
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: same-bb-vopm-fma-from-tensor
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def $scc
    ; GCN-NEXT: BUNDLE implicit-def dead $stg_srcc, implicit-def dead $stg_srcb, implicit-def dead $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHL_B32_1]], implicit $exec, implicit [[S_LSHL_B32_]] {
    ; GCN-NEXT:   $stg_srcc = V_LOAD_IDX [[S_LSHL_B32_1]], 12, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; GCN-NEXT:   $stg_srcb = V_LOAD_IDX [[S_LSHL_B32_1]], 7, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_1]], 8, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; GCN-NEXT:   $stg_dsta = nnan ninf nsz arcp contract afn reassoc V_FMA_FROM_TENSOR_F32_F16_regular internal killed $stg_srca, internal killed $stg_srcb, internal killed $stg_srcc, 2, 0, 0, 0, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_]], 0, implicit $exec :: (store (s128), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: same-bb-vopm-fma-from-tensor
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def $scc
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_1]]
    ; ALLOC-NEXT: BUNDLE implicit-def dead $stg_srcc, implicit-def dead $stg_srcb, implicit-def dead $stg_srca, implicit-def $stg_dsta, implicit $idx2, implicit $exec, implicit $idx1 {
    ; ALLOC-NEXT:   $stg_srcc = V_LOAD_IDX $idx2, 12, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; ALLOC-NEXT:   $stg_srcb = V_LOAD_IDX $idx2, 7, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx2, 8, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta = nnan ninf nsz arcp contract afn reassoc V_FMA_FROM_TENSOR_F32_F16_regular internal killed $stg_srca, internal killed $stg_srcb, internal killed $stg_srcc, 2, 0, 0, 0, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 0, implicit $exec :: (store (s128), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: same-bb-vopm-fma-from-tensor
    ; LOWERED: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr1 = S_LSHL_B32 1, 4, implicit-def dead $scc
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    ; LOWERED-NEXT: undef $vgpr0_vgpr1 = nnan ninf nsz arcp contract afn reassoc V_FMA_FROM_TENSOR_F32_F16_regular killed undef $vgpr8_vgpr9, killed undef $vgpr7, killed undef $vgpr12_vgpr13, 2, 0, 131617, 0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def $scc
    %2:vreg_64_align2 = V_LOAD_IDX %1:sreg_32_xexec_hi, 12, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    %3:vreg_64_align2 = V_LOAD_IDX %1:sreg_32_xexec_hi, 8, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    %4:vgpr_32 = V_LOAD_IDX %1:sreg_32_xexec_hi, 7, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    %5:vreg_64_align2 = nnan ninf nsz arcp contract afn reassoc V_FMA_FROM_TENSOR_F32_F16_regular killed %3:vreg_64_align2, killed %4:vgpr_32, killed %2:vreg_64_align2, 2, 0, 0, 0, implicit $exec
    V_STORE_IDX %5:vreg_64_align2, %0:sreg_32_xexec_hi, 0, implicit $exec :: (store (s128), addrspace 10)
...


---
name:            same-bb-vopm-wmma
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: same-bb-vopm-wmma
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def $scc
    ; GCN-NEXT: BUNDLE implicit-def $stg_srcc, implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def early-clobber $stg_dsta, implicit [[S_LSHL_B32_1]], implicit $exec, implicit [[S_LSHL_B32_]] {
    ; GCN-NEXT:   $stg_srcc = V_LOAD_IDX [[S_LSHL_B32_1]], 16, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; GCN-NEXT:   $stg_srcb = V_LOAD_IDX [[S_LSHL_B32_1]], 8, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_1]], 12, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; GCN-NEXT:   early-clobber $stg_dsta = V_WMMA_F32_16X16X16_FP8_FP8_threeaddr internal $stg_srca, internal $stg_srcb, internal $stg_srcc, -1, 0, 0, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_]], 0, implicit $exec :: (store (s128), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: same-bb-vopm-wmma
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def $scc
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_1]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srcc, implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def early-clobber $stg_dsta, implicit $idx2, implicit $exec, implicit $idx1 {
    ; ALLOC-NEXT:   $stg_srcc = V_LOAD_IDX $idx2, 16, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; ALLOC-NEXT:   $stg_srcb = V_LOAD_IDX $idx2, 8, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx2, 12, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; ALLOC-NEXT:   early-clobber $stg_dsta = V_WMMA_F32_16X16X16_FP8_FP8_threeaddr internal $stg_srca, internal $stg_srcb, internal $stg_srcc, -1, 0, 0, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 0, implicit $exec :: (store (s128), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: same-bb-vopm-wmma
    ; LOWERED: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr1 = S_LSHL_B32 1, 4, implicit-def dead $scc
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    ; LOWERED-NEXT: undef early-clobber $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7 = V_WMMA_F32_16X16X16_FP8_FP8_threeaddr undef $vgpr12_vgpr13, undef $vgpr8_vgpr9, undef $vgpr16_vgpr17_vgpr18_vgpr19_vgpr20_vgpr21_vgpr22_vgpr23, -1, 8737, 0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def $scc
    %2:vreg_64_align2 = V_LOAD_IDX %1:sreg_32_xexec_hi, 12, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    %3:vreg_64_align2 = V_LOAD_IDX %1:sreg_32_xexec_hi, 8, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    %4:vreg_256_align2 = V_LOAD_IDX %1:sreg_32_xexec_hi, 16, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    early-clobber %5:vreg_256_align2 = V_WMMA_F32_16X16X16_FP8_FP8_threeaddr %2:vreg_64_align2, %3:vreg_64_align2, %4:vreg_256_align2, -1, 0, 0,implicit $exec
    V_STORE_IDX %5:vreg_256_align2, %0:sreg_32_xexec_hi, 0, implicit $exec :: (store (s128), addrspace 10)
...

---
name:            max-indexes-vopm-convolve
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: max-indexes-vopm-convolve
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 3, implicit-def $scc
    ; GCN-NEXT: [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def $scc
    ; GCN-NEXT: [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 5, implicit-def $scc
    ; GCN-NEXT: BUNDLE implicit-def dead $stg_srcf, implicit-def dead $stg_srce, implicit-def dead $stg_srcd, implicit-def dead $stg_srcc, implicit-def dead $stg_srcb, implicit-def dead $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHL_B32_3]], implicit $exec, implicit [[S_LSHL_B32_2]], implicit [[S_LSHL_B32_1]], implicit [[S_LSHL_B32_]] {
    ; GCN-NEXT:   $stg_srcf = V_LOAD_IDX [[S_LSHL_B32_3]], 4, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srce = V_LOAD_IDX [[S_LSHL_B32_2]], 5, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srcd = V_LOAD_IDX [[S_LSHL_B32_1]], 6, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srcc = V_LOAD_IDX [[S_LSHL_B32_1]], 7, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srcb = V_LOAD_IDX [[S_LSHL_B32_]], 8, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 12, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; GCN-NEXT:   $stg_dsta = V_CONVOLVE_BF16_BF16_1x1_4x4_ITER_4 internal killed $stg_srca, internal killed $stg_srcb, internal killed $stg_srcc, internal killed $stg_srcd, internal killed $stg_srce, internal killed $stg_srcf, 12290, -1, 0, 0, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_]], 0, implicit $exec :: (store (s128), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: max-indexes-vopm-convolve
    ; ALLOC: $idx0 = S_SET_GPR_IDX_U32 0
    ; ALLOC-NEXT: [[COPY:%[0-9]+]]:sreg_32_xm0_xexec = COPY $idx0
    ; ALLOC-NEXT: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 3, implicit-def $scc
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_1]]
    ; ALLOC-NEXT: [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def $scc
    ; ALLOC-NEXT: $idx3 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_2]]
    ; ALLOC-NEXT: [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 5, implicit-def $scc
    ; ALLOC-NEXT: $idx0 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_3]]
    ; ALLOC-NEXT: BUNDLE implicit-def dead $stg_srcf, implicit-def dead $stg_srce, implicit-def dead $stg_srcd, implicit-def dead $stg_srcc, implicit-def dead $stg_srcb, implicit-def dead $stg_srca, implicit-def $stg_dsta, implicit $idx0, implicit $exec, implicit $idx3, implicit $idx2, implicit $idx1 {
    ; ALLOC-NEXT:   $stg_srcf = V_LOAD_IDX $idx0, 4, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srce = V_LOAD_IDX $idx3, 5, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srcd = V_LOAD_IDX $idx2, 6, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srcc = V_LOAD_IDX $idx2, 7, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srcb = V_LOAD_IDX $idx1, 8, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx1, 12, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta = V_CONVOLVE_BF16_BF16_1x1_4x4_ITER_4 internal killed $stg_srca, internal killed $stg_srcb, internal killed $stg_srcc, internal killed $stg_srcd, internal killed $stg_srce, internal killed $stg_srcf, 12290, -1, 0, 0, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 0, implicit $exec :: (store (s128), addrspace 10)
    ; ALLOC-NEXT: }
    ; ALLOC-NEXT: $idx0 = S_SET_GPR_IDX_U32 [[COPY]]
    ;
    ; LOWERED-LABEL: name: max-indexes-vopm-convolve
    ; LOWERED: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $sgpr1 = S_GETREG_B32 63532, implicit $mode
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 3, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr2 = S_LSHL_B32 1, 4, implicit-def dead $scc
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 5, implicit-def dead $scc
    ; LOWERED-NEXT: $idx3 = S_SET_GPR_IDX_U32 killed renamable $sgpr2
    ; LOWERED-NEXT: $idx0 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: undef $vgpr0_vgpr1_vgpr2_vgpr3 = V_CONVOLVE_BF16_BF16_1x1_4x4_ITER_4 killed undef $vgpr12_vgpr13_vgpr14_vgpr15, killed undef $vgpr8_vgpr9_vgpr10_vgpr11, killed undef $vgpr7, killed undef $vgpr6, killed undef $vgpr5, killed undef $vgpr4, 12290, -1, 3285265, 0, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: dead $idx0 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:sreg_32_xexec_hi = S_LSHL_B32 1, 3, implicit-def $scc
    %2:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def $scc
    %3:sreg_32_xexec_hi = S_LSHL_B32 1, 5, implicit-def $scc
    %6:vreg_128_align2 = V_LOAD_IDX %0:sreg_32_xexec_hi, 12, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    %7:vreg_128_align2 = V_LOAD_IDX %0:sreg_32_xexec_hi, 8, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    %8:vgpr_32 = V_LOAD_IDX %1:sreg_32_xexec_hi, 7, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    %9:vgpr_32 = V_LOAD_IDX %1:sreg_32_xexec_hi, 6, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    %10:vgpr_32 = V_LOAD_IDX %2:sreg_32_xexec_hi, 5, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    %11:vgpr_32 = V_LOAD_IDX %3:sreg_32_xexec_hi, 4, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    %12:vreg_128_align2 = V_CONVOLVE_BF16_BF16_1x1_4x4_ITER_4 killed %6:vreg_128_align2, killed %7:vreg_128_align2, killed %8:vgpr_32, killed %9:vgpr_32, killed %10:vgpr_32, killed %11:vgpr_32, 12290, -1, 0, 0, implicit $exec
    V_STORE_IDX %12:vreg_128_align2, %0:sreg_32_xexec_hi, 0, implicit $exec :: (store (s128), addrspace 10)
...

---
name:            too-many-vgpr-ops-no-idx0
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: too-many-vgpr-ops-no-idx0
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 3, implicit-def $scc
    ; GCN-NEXT: [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def $scc
    ; GCN-NEXT: [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 5, implicit-def $scc
    ; GCN-NEXT: [[S_LSHL_B32_4:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 6, implicit-def $scc
    ; GCN-NEXT: [[V_LOAD_IDX:%[0-9]+]]:vgpr_32 = V_LOAD_IDX [[S_LSHL_B32_2]], 6, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; GCN-NEXT: [[V_LOAD_IDX1:%[0-9]+]]:vgpr_32 = V_LOAD_IDX [[S_LSHL_B32_4]], 4, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; GCN-NEXT: BUNDLE implicit-def dead $stg_srcd, implicit-def dead $stg_srcc, implicit-def dead $stg_srcb, implicit-def dead $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHL_B32_3]], implicit $exec, implicit [[S_LSHL_B32_1]], implicit killed [[V_LOAD_IDX]], implicit killed [[V_LOAD_IDX1]], implicit [[S_LSHL_B32_]] {
    ; GCN-NEXT:   $stg_srcd = V_LOAD_IDX [[S_LSHL_B32_3]], 5, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srcc = V_LOAD_IDX [[S_LSHL_B32_3]], 7, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srcb = V_LOAD_IDX [[S_LSHL_B32_1]], 8, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_1]], 12, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; GCN-NEXT:   $stg_dsta = V_CONVOLVE_BF16_BF16_1x1_4x4_ITER_4 internal killed $stg_srca, internal killed $stg_srcb, internal killed $stg_srcc, killed [[V_LOAD_IDX]], internal killed $stg_srcd, killed [[V_LOAD_IDX1]], 12290, -1, 0, 0, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_]], 0, implicit $exec :: (store (s128), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: too-many-vgpr-ops-no-idx0
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 3, implicit-def $scc
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_1]]
    ; ALLOC-NEXT: [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_2]]
    ; ALLOC-NEXT: [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 5, implicit-def $scc
    ; ALLOC-NEXT: $idx3 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_3]]
    ; ALLOC-NEXT: [[S_LSHL_B32_4:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 6, implicit-def $scc
    ; ALLOC-NEXT: [[V_LOAD_IDX:%[0-9]+]]:vgpr_32 = V_LOAD_IDX $idx1, 6, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_4]]
    ; ALLOC-NEXT: [[V_LOAD_IDX1:%[0-9]+]]:vgpr_32 = V_LOAD_IDX $idx1, 4, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: BUNDLE implicit-def dead $stg_srcd, implicit-def dead $stg_srcc, implicit-def dead $stg_srcb, implicit-def dead $stg_srca, implicit-def $stg_dsta, implicit $idx3, implicit $exec, implicit $idx2, implicit killed [[V_LOAD_IDX]], implicit killed [[V_LOAD_IDX1]], implicit $idx1 {
    ; ALLOC-NEXT:   $stg_srcd = V_LOAD_IDX $idx3, 5, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srcc = V_LOAD_IDX $idx3, 7, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srcb = V_LOAD_IDX $idx2, 8, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx2, 12, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta = V_CONVOLVE_BF16_BF16_1x1_4x4_ITER_4 internal killed $stg_srca, internal killed $stg_srcb, internal killed $stg_srcc, killed [[V_LOAD_IDX]], internal killed $stg_srcd, killed [[V_LOAD_IDX1]], 12290, -1, 0, 0, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 0, implicit $exec :: (store (s128), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: too-many-vgpr-ops-no-idx0
    ; LOWERED: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 3, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr1 = S_LSHL_B32 1, 4, implicit-def dead $scc
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 5, implicit-def dead $scc
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    ; LOWERED-NEXT: $idx3 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 6, implicit-def dead $scc
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 1
    ; LOWERED-NEXT: $vgpr0 = V_MOV_B32_e32 undef $vgpr6, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $vgpr1 = V_MOV_B32_e32 undef $vgpr4, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: undef $vgpr0_vgpr1_vgpr2_vgpr3 = V_CONVOLVE_BF16_BF16_1x1_4x4_ITER_4 killed undef $vgpr12_vgpr13_vgpr14_vgpr15, killed undef $vgpr8_vgpr9_vgpr10_vgpr11, killed undef $vgpr7, killed $vgpr0, killed undef $vgpr5, killed $vgpr1, 12290, -1, 3158561, 0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:sreg_32_xexec_hi = S_LSHL_B32 1, 3, implicit-def $scc
    %2:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def $scc
    %3:sreg_32_xexec_hi = S_LSHL_B32 1, 5, implicit-def $scc
    %4:sreg_32_xexec_hi = S_LSHL_B32 1, 6, implicit-def $scc
    %6:vreg_128_align2 = V_LOAD_IDX %1:sreg_32_xexec_hi, 12, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    %7:vreg_128_align2 = V_LOAD_IDX %1:sreg_32_xexec_hi, 8, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    %8:vgpr_32 = V_LOAD_IDX %3:sreg_32_xexec_hi, 7, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    %9:vgpr_32 = V_LOAD_IDX %2:sreg_32_xexec_hi, 6, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    %10:vgpr_32 = V_LOAD_IDX %3:sreg_32_xexec_hi, 5, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    %11:vgpr_32 = V_LOAD_IDX %4:sreg_32_xexec_hi, 4, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    %12:vreg_128_align2 = V_CONVOLVE_BF16_BF16_1x1_4x4_ITER_4 killed %6:vreg_128_align2, killed %7:vreg_128_align2, killed %8:vgpr_32, killed %9:vgpr_32, killed %10:vgpr_32, killed %11:vgpr_32, 12290, -1, 0, 0, implicit $exec
    V_STORE_IDX %12:vreg_128_align2, %0:sreg_32_xexec_hi, 0, implicit $exec :: (store (s128), addrspace 10)
...

---
name:            private-op-no-idx0
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: private-op-no-idx0
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 3, implicit-def $scc
    ; GCN-NEXT: [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def $scc
    ; GCN-NEXT: [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 5, implicit-def $scc
    ; GCN-NEXT: [[V_LOAD_IDX:%[0-9]+]]:vgpr_32 = V_LOAD_IDX [[S_LSHL_B32_2]], 5, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; GCN-NEXT: [[V_MOV_B32_e32_:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 [[S_LSHL_B32_3]], implicit $exec
    ; GCN-NEXT: BUNDLE implicit-def dead $stg_srcd, implicit-def dead $stg_srcc, implicit-def dead $stg_srcb, implicit-def dead $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHL_B32_1]], implicit $exec, implicit [[S_LSHL_B32_]], implicit killed [[V_LOAD_IDX]], implicit killed [[V_MOV_B32_e32_]], implicit [[S_LSHL_B32_3]] {
    ; GCN-NEXT:   $stg_srcd = V_LOAD_IDX [[S_LSHL_B32_1]], 6, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srcc = V_LOAD_IDX [[S_LSHL_B32_1]], 7, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srcb = V_LOAD_IDX [[S_LSHL_B32_]], 8, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 12, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; GCN-NEXT:   $stg_dsta = V_CONVOLVE_BF16_BF16_1x1_4x4_ITER_4 internal killed $stg_srca, internal killed $stg_srcb, internal killed $stg_srcc, internal killed $stg_srcd, killed [[V_LOAD_IDX]], killed [[V_MOV_B32_e32_]], 12290, -1, 0, 0, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_3]], 0, implicit $exec :: (store (s128), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: private-op-no-idx0
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 3, implicit-def $scc
    ; ALLOC-NEXT: $idx3 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_1]]
    ; ALLOC-NEXT: [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_2]]
    ; ALLOC-NEXT: [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 5, implicit-def $scc
    ; ALLOC-NEXT: [[V_LOAD_IDX:%[0-9]+]]:vgpr_32 = V_LOAD_IDX $idx1, 5, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_3]]
    ; ALLOC-NEXT: [[V_MOV_B32_e32_:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 [[S_LSHL_B32_3]], implicit $exec
    ; ALLOC-NEXT: BUNDLE implicit-def dead $stg_srcd, implicit-def dead $stg_srcc, implicit-def dead $stg_srcb, implicit-def dead $stg_srca, implicit-def $stg_dsta, implicit $idx3, implicit $exec, implicit $idx2, implicit killed [[V_LOAD_IDX]], implicit killed [[V_MOV_B32_e32_]], implicit $idx1 {
    ; ALLOC-NEXT:   $stg_srcd = V_LOAD_IDX $idx3, 6, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srcc = V_LOAD_IDX $idx3, 7, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srcb = V_LOAD_IDX $idx2, 8, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx2, 12, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta = V_CONVOLVE_BF16_BF16_1x1_4x4_ITER_4 internal killed $stg_srca, internal killed $stg_srcb, internal killed $stg_srcc, internal killed $stg_srcd, killed [[V_LOAD_IDX]], killed [[V_MOV_B32_e32_]], 12290, -1, 0, 0, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 0, implicit $exec :: (store (s128), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: private-op-no-idx0
    ; LOWERED: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr1 = S_LSHL_B32 1, 3, implicit-def dead $scc
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 4, implicit-def dead $scc
    ; LOWERED-NEXT: $idx3 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 5, implicit-def dead $scc
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 1
    ; LOWERED-NEXT: $vgpr0 = V_MOV_B32_e32 undef $vgpr5, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: renamable $vgpr1 = V_MOV_B32_e32 $sgpr0, implicit $exec
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: undef $vgpr0_vgpr1_vgpr2_vgpr3 = V_CONVOLVE_BF16_BF16_1x1_4x4_ITER_4 killed undef $vgpr12_vgpr13_vgpr14_vgpr15, killed undef $vgpr8_vgpr9_vgpr10_vgpr11, killed undef $vgpr7, killed undef $vgpr6, killed $vgpr0, killed $vgpr1, 12290, -1, 209441, 0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:sreg_32_xexec_hi = S_LSHL_B32 1, 3, implicit-def $scc
    %2:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def $scc
    %3:sreg_32_xexec_hi = S_LSHL_B32 1, 5, implicit-def $scc
    %6:vreg_128_align2 = V_LOAD_IDX %0:sreg_32_xexec_hi, 12, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    %7:vreg_128_align2 = V_LOAD_IDX %0:sreg_32_xexec_hi, 8, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    %8:vgpr_32 = V_LOAD_IDX %1:sreg_32_xexec_hi, 7, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    %9:vgpr_32 = V_LOAD_IDX %1:sreg_32_xexec_hi, 6, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    %10:vgpr_32 = V_LOAD_IDX %2:sreg_32_xexec_hi, 5, implicit $exec :: (dereferenceable load (s32), addrspace 10)
    %11:vgpr_32 = V_MOV_B32_e32 %3:sreg_32_xexec_hi, implicit $exec
    %12:vreg_128_align2 = V_CONVOLVE_BF16_BF16_1x1_4x4_ITER_4 killed %6:vreg_128_align2, killed %7:vreg_128_align2, killed %8:vgpr_32, killed %9:vgpr_32, killed %10:vgpr_32, killed %11:vgpr_32, 12290, -1, 0, 0, implicit $exec
    V_STORE_IDX %12:vreg_128_align2, %3:sreg_32_xexec_hi, 0, implicit $exec :: (store (s128), addrspace 10)
...

---
name:            multiple-defs-vopm-cvt-to-tensor
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |
  bb.0:
    ; GCN-LABEL: name: multiple-defs-vopm-cvt-to-tensor
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit-def $stg_dstb, implicit [[S_LSHL_B32_]], implicit $exec {
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 0, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; GCN-NEXT:   $stg_dsta, $stg_dstb = V_CVT_TO_TENSOR_F16_F32_4x2x16 internal $stg_srca, 1, 3, -1, 0, 0, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_]], 3, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dstb, [[S_LSHL_B32_]], 4, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ; GCN-NEXT: BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit-def $stg_dstb, implicit [[S_LSHL_B32_]], implicit $exec {
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 0, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; GCN-NEXT:   $stg_dsta, $stg_dstb = V_CVT_TO_TENSOR_F16_F32_4x2x16 internal $stg_srca, 1, 3, -1, 0, 0, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_]], 4, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dstb, [[S_LSHL_B32_]], 3, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: multiple-defs-vopm-cvt-to-tensor
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit-def $stg_dstb, implicit $idx1, implicit $exec {
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx1, 0, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta, $stg_dstb = V_CVT_TO_TENSOR_F16_F32_4x2x16 internal $stg_srca, 1, 3, -1, 0, 0, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 3, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dstb, $idx1, 4, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit-def $stg_dstb, implicit $idx1, implicit $exec {
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx1, 0, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta, $stg_dstb = V_CVT_TO_TENSOR_F16_F32_4x2x16 internal $stg_srca, 1, 3, -1, 0, 0, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 4, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dstb, $idx1, 3, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: multiple-defs-vopm-cvt-to-tensor
    ; LOWERED: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: undef $vgpr3, undef $vgpr4 = V_CVT_TO_TENSOR_F16_F32_4x2x16 undef $vgpr0_vgpr1_vgpr2_vgpr3, 1, 3, -1, 4113, 0, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: undef $vgpr4, undef $vgpr3 = V_CVT_TO_TENSOR_F16_F32_4x2x16 undef $vgpr0_vgpr1_vgpr2_vgpr3, 1, 3, -1, 4113, 0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:vreg_128_align2 = V_LOAD_IDX %0:sreg_32_xexec_hi, 0, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    %2:vgpr_32, %3:vgpr_32 = V_CVT_TO_TENSOR_F16_F32_4x2x16 %1, 1, 3, -1, 0, 0, implicit $exec
    V_STORE_IDX %2:vgpr_32, %0:sreg_32_xexec_hi, 3, implicit $exec :: (store (s32), addrspace 10)
    V_STORE_IDX %3:vgpr_32, %0:sreg_32_xexec_hi, 4, implicit $exec :: (store (s32), addrspace 10)
    %4:vreg_128_align2 = V_LOAD_IDX %0:sreg_32_xexec_hi, 0, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    %5:vgpr_32, %6:vgpr_32 = V_CVT_TO_TENSOR_F16_F32_4x2x16 %4, 1, 3, -1, 0, 0, implicit $exec
    V_STORE_IDX %5:vgpr_32, %0:sreg_32_xexec_hi, 4, implicit $exec :: (store (s32), addrspace 10)
    V_STORE_IDX %6:vgpr_32, %0:sreg_32_xexec_hi, 3, implicit $exec :: (store (s32), addrspace 10)
...

---
name:            multiple-defs-vopm-cvt-to-tensor-swapped
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |
  bb.0:
    ; GCN-LABEL: name: multiple-defs-vopm-cvt-to-tensor-swapped
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit-def $stg_dstb, implicit [[S_LSHL_B32_]], implicit $exec {
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 0, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; GCN-NEXT:   $stg_dsta, $stg_dstb = V_CVT_TO_TENSOR_F16_F32_4x2x16 internal $stg_srca, 1, 3, -1, 0, 0, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_]], 3, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dstb, [[S_LSHL_B32_]], 4, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ; GCN-NEXT: BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit-def $stg_dstb, implicit [[S_LSHL_B32_]], implicit $exec {
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 0, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; GCN-NEXT:   $stg_dsta, $stg_dstb = V_CVT_TO_TENSOR_F16_F32_4x2x16 internal $stg_srca, 1, 3, -1, 0, 0, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dstb, [[S_LSHL_B32_]], 4, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_]], 3, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: multiple-defs-vopm-cvt-to-tensor-swapped
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit-def $stg_dstb, implicit $idx1, implicit $exec {
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx1, 0, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta, $stg_dstb = V_CVT_TO_TENSOR_F16_F32_4x2x16 internal $stg_srca, 1, 3, -1, 0, 0, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 3, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dstb, $idx1, 4, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit-def $stg_dstb, implicit $idx1, implicit $exec {
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx1, 0, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta, $stg_dstb = V_CVT_TO_TENSOR_F16_F32_4x2x16 internal $stg_srca, 1, 3, -1, 0, 0, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dstb, $idx1, 4, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 3, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: multiple-defs-vopm-cvt-to-tensor-swapped
    ; LOWERED: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: undef $vgpr3, undef $vgpr4 = V_CVT_TO_TENSOR_F16_F32_4x2x16 undef $vgpr0_vgpr1_vgpr2_vgpr3, 1, 3, -1, 4113, 0, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: undef $vgpr3, undef $vgpr4 = V_CVT_TO_TENSOR_F16_F32_4x2x16 undef $vgpr0_vgpr1_vgpr2_vgpr3, 1, 3, -1, 4113, 0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:vreg_128_align2 = V_LOAD_IDX %0:sreg_32_xexec_hi, 0, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    %2:vgpr_32, %3:vgpr_32 = V_CVT_TO_TENSOR_F16_F32_4x2x16 %1, 1, 3, -1, 0, 0, implicit $exec
    V_STORE_IDX %2:vgpr_32, %0:sreg_32_xexec_hi, 3, implicit $exec :: (store (s32), addrspace 10)
    V_STORE_IDX %3:vgpr_32, %0:sreg_32_xexec_hi, 4, implicit $exec :: (store (s32), addrspace 10)
    %4:vreg_128_align2 = V_LOAD_IDX %0:sreg_32_xexec_hi, 0, implicit $exec :: (dereferenceable load (s128), addrspace 10)
    %6:vgpr_32, %5:vgpr_32 = V_CVT_TO_TENSOR_F16_F32_4x2x16 %4, 1, 3, -1, 0, 0, implicit $exec
    V_STORE_IDX %5:vgpr_32, %0:sreg_32_xexec_hi, 4, implicit $exec :: (store (s32), addrspace 10)
    V_STORE_IDX %6:vgpr_32, %0:sreg_32_xexec_hi, 3, implicit $exec :: (store (s32), addrspace 10)
...
