# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -march=amdgcn -mcpu=gfx1300 -verify-machineinstrs -run-pass=bundle-indexed-load-store -o - %s | FileCheck -check-prefixes=GCN %s
# RUN: llc -march=amdgcn -mcpu=gfx1300 -verify-machineinstrs -start-before=bundle-indexed-load-store -stop-after=amdgpu-idx-reg-alloc -o - %s | FileCheck -check-prefixes=ALLOC %s
# RUN: llc -march=amdgcn -mcpu=gfx1300 -verify-machineinstrs -start-before=bundle-indexed-load-store -stop-after=amdgpu-lower-vgpr-encoding -o - %s | FileCheck -check-prefixes=LOWERED %s

---
name:            same-bb-load-trivial
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: same-bb-load-trivial
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: BUNDLE implicit-def $stg_srca, implicit-def %2, implicit [[S_LSHL_B32_]], implicit $exec {
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 0, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 12345, internal $stg_srca, implicit $exec
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: same-bb-load-trivial
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srca, implicit-def %2, implicit $idx1, implicit $exec {
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx1, 0, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 12345, internal $stg_srca, implicit $exec
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: same-bb-load-trivial
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 4
    ; LOWERED-NEXT: renamable $vgpr0 = V_MAX_U32_e64 12345, undef $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:vgpr_32 = V_LOAD_IDX %0, 0, implicit $exec :: (load (s32), addrspace 10)
    %2:vgpr_32 = V_MAX_U32_e64 12345, %1, implicit $exec
...

---
name:            same-bb-store-trivial
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: same-bb-store-trivial
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY [[S_LSHL_B32_]]
    ; GCN-NEXT: BUNDLE implicit-def $stg_dsta, implicit [[COPY]], implicit $exec, implicit [[S_LSHL_B32_]] {
    ; GCN-NEXT:   $stg_dsta = V_MAX_U32_e64 12345, [[COPY]], implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_]], 0, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: same-bb-store-trivial
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_dsta, implicit $idx1, implicit $exec, implicit [[S_LSHL_B32_]] {
    ; ALLOC-NEXT:   $stg_dsta = V_MAX_U32_e64 12345, [[S_LSHL_B32_]], implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 0, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: same-bb-store-trivial
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 renamable $sgpr0
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 64
    ; LOWERED-NEXT: undef $vgpr0 = V_MAX_U32_e64 12345, killed $sgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:vgpr_32 = COPY %0:sreg_32_xexec_hi
    %2:vgpr_32 = V_MAX_U32_e64 12345, %1, implicit $exec
    V_STORE_IDX %2:vgpr_32, %0, 0, implicit $exec :: (store (s32), addrspace 10)
...

---
name:            same-bb-store-out-of-order
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: same-bb-store-out-of-order
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY [[S_LSHL_B32_]]
    ; GCN-NEXT: [[S_ADD_I32_:%[0-9]+]]:sreg_32_xexec_hi = S_ADD_I32 [[S_LSHL_B32_]], 429496640, implicit-def dead $scc
    ; GCN-NEXT: [[S_ADD_I32_1:%[0-9]+]]:sreg_32_xexec_hi = S_ADD_I32 [[S_LSHL_B32_]], 5, implicit-def dead $scc
    ; GCN-NEXT: BUNDLE implicit-def $stg_dsta, implicit [[COPY]], implicit $exec, implicit [[S_ADD_I32_]] {
    ; GCN-NEXT:   $stg_dsta = V_MAX_U32_e64 12345, [[COPY]], implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_ADD_I32_]], 0, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: same-bb-store-out-of-order
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: [[S_ADD_I32_:%[0-9]+]]:sreg_32_xexec_hi = S_ADD_I32 [[S_LSHL_B32_]], 429496640, implicit-def dead $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_ADD_I32_]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_dsta, implicit [[S_LSHL_B32_]], implicit $exec, implicit $idx1 {
    ; ALLOC-NEXT:   $stg_dsta = V_MAX_U32_e64 12345, [[S_LSHL_B32_]], implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 0, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: same-bb-store-out-of-order
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr1
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr1 = S_ADD_I32 renamable $sgpr0, 429496640, implicit-def dead $scc
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 64
    ; LOWERED-NEXT: undef $vgpr0 = V_MAX_U32_e64 12345, killed $sgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:vgpr_32 = COPY %0:sreg_32_xexec_hi
    %2:vgpr_32 = V_MAX_U32_e64 12345, %1, implicit $exec
    %4:sreg_32_xexec_hi = S_ADD_I32 %0, 429496640, implicit-def dead $scc
    %5:sreg_32_xexec_hi = S_ADD_I32 %0, 5, implicit-def dead $scc
    V_STORE_IDX %2:vgpr_32, %4, 0, implicit $exec :: (store (s32), addrspace 10)
...

# Bundling would introduce impossible cycles in the dataflow.
---
name:            same-bb-store-cannot-bundle
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: same-bb-store-cannot-bundle
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY [[S_LSHL_B32_]]
    ; GCN-NEXT: [[V_ADD_CO_U32_e64_:%[0-9]+]]:vgpr_32, [[V_ADD_CO_U32_e64_1:%[0-9]+]]:sreg_32_xm0_xexec = V_ADD_CO_U32_e64 12345, [[COPY]], 0, implicit $exec
    ; GCN-NEXT: V_STORE_IDX [[V_ADD_CO_U32_e64_]], [[V_ADD_CO_U32_e64_1]], 0, implicit $exec :: (store (s32), addrspace 10)
    ;
    ; ALLOC-LABEL: name: same-bb-store-cannot-bundle
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: [[V_ADD_CO_U32_e64_:%[0-9]+]]:vgpr_32, [[V_ADD_CO_U32_e64_1:%[0-9]+]]:sreg_32_xm0_xexec = V_ADD_CO_U32_e64 12345, [[S_LSHL_B32_]], 0, implicit $exec
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[V_ADD_CO_U32_e64_1]]
    ; ALLOC-NEXT: V_STORE_IDX [[V_ADD_CO_U32_e64_]], $idx1, 0, implicit $exec :: (store (s32), addrspace 10)
    ;
    ; LOWERED-LABEL: name: same-bb-store-cannot-bundle
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $vgpr0, renamable $sgpr0 = V_ADD_CO_U32_e64 12345, killed $sgpr0, 0, implicit $exec
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 64
    ; LOWERED-NEXT: $vgpr0 = V_MOV_B32_e32 $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:vgpr_32 = COPY %0:sreg_32_xexec_hi
    %2:vgpr_32, %3:sreg_32_xm0_xexec = V_ADD_CO_U32_e64 12345, %1, 0, implicit $exec
    V_STORE_IDX %2:vgpr_32, %3, 0, implicit $exec :: (store (s32), addrspace 10)
...

---
name:            same-bb-store-carryout
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: same-bb-store-carryout
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY [[S_LSHL_B32_]]
    ; GCN-NEXT: BUNDLE implicit-def $stg_dsta, implicit-def %3, implicit [[COPY]], implicit $exec, implicit [[S_LSHL_B32_]] {
    ; GCN-NEXT:   $stg_dsta, %3:sreg_32_xm0_xexec = V_ADD_CO_U32_e64 12345, [[COPY]], 0, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_]], 0, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: same-bb-store-carryout
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_dsta, implicit-def %3, implicit $idx1, implicit $exec, implicit [[S_LSHL_B32_]] {
    ; ALLOC-NEXT:   $stg_dsta, %3:sreg_32_xm0_xexec = V_ADD_CO_U32_e64 12345, [[S_LSHL_B32_]], 0, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 0, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: same-bb-store-carryout
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 renamable $sgpr0
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 64
    ; LOWERED-NEXT: undef $vgpr0, renamable $sgpr0 = V_ADD_CO_U32_e64 12345, killed $sgpr0, 0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:vgpr_32 = COPY %0:sreg_32_xexec_hi
    %2:vgpr_32, %3:sreg_32_xm0_xexec = V_ADD_CO_U32_e64 12345, %1, 0, implicit $exec
    V_STORE_IDX %2:vgpr_32, %0, 0, implicit $exec :: (store (s32), addrspace 10)
...

---
name:            same-bb-load-store-trivial
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: same-bb-load-store-trivial
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHL_B32_]], implicit $exec {
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 0, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_dsta = V_MAX_U32_e64 12345, internal $stg_srca, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_]], 0, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: same-bb-load-store-trivial
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit $idx1, implicit $exec {
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx1, 0, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta = V_MAX_U32_e64 12345, internal $stg_srca, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 0, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: same-bb-load-store-trivial
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 68
    ; LOWERED-NEXT: undef $vgpr0 = V_MAX_U32_e64 12345, undef $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:vgpr_32 = V_LOAD_IDX %0, 0, implicit $exec :: (load (s32), addrspace 10)
    %2:vgpr_32 = V_MAX_U32_e64 12345, %1, implicit $exec
    V_STORE_IDX %2:vgpr_32, %0, 0, implicit $exec :: (store (s32), addrspace 10)
...

---

name:            same-bb-load-store-fmac
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: same-bb-load-store-fmac
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[V_LOAD_IDX:%[0-9]+]]:vgpr_32 = V_LOAD_IDX [[S_LSHL_B32_]], 0, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT: [[DEF:%[0-9]+]]:vgpr_32 = IMPLICIT_DEF
    ; GCN-NEXT: [[V_FMAC_F32_e64_:%[0-9]+]]:vgpr_32 = V_FMAC_F32_e64 0, 12345, 0, [[V_LOAD_IDX]], 0, [[DEF]], 0, 0, implicit $mode, implicit $exec
    ; GCN-NEXT: V_STORE_IDX [[V_FMAC_F32_e64_]], [[S_LSHL_B32_]], 0, implicit $exec :: (store (s32), addrspace 10)
    ;
    ; ALLOC-LABEL: name: same-bb-load-store-fmac
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: [[V_LOAD_IDX:%[0-9]+]]:vgpr_32 = V_LOAD_IDX $idx1, 0, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT: [[DEF:%[0-9]+]]:vgpr_32 = IMPLICIT_DEF
    ; ALLOC-NEXT: [[V_FMAC_F32_e32_:%[0-9]+]]:vgpr_32 = V_FMAC_F32_e32 12345, [[V_LOAD_IDX]], [[DEF]], implicit $mode, implicit $exec
    ; ALLOC-NEXT: V_STORE_IDX [[V_FMAC_F32_e32_]], $idx1, 0, implicit $exec :: (store (s32), addrspace 10)
    ;
    ; LOWERED-LABEL: name: same-bb-load-store-fmac
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 1
    ; LOWERED-NEXT: $vgpr0 = V_MOV_B32_e32 undef $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: renamable $vgpr0 = V_FMAC_F32_e32 12345, killed $vgpr0, undef $vgpr0, implicit $mode, implicit $exec
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 64
    ; LOWERED-NEXT: $vgpr0 = V_MOV_B32_e32 $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:vgpr_32 = V_LOAD_IDX %0, 0, implicit $exec :: (load (s32), addrspace 10)
    %2:vgpr_32 = IMPLICIT_DEF
    %3:vgpr_32 = V_FMAC_F32_e64 0, 12345, 0, %1, 0, %2, 0, 0, implicit $mode, implicit $exec
    V_STORE_IDX %3:vgpr_32, %0, 0, implicit $exec :: (store (s32), addrspace 10)
...

---
name:            same-bb-load-store-different-idx
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: same-bb-load-store-different-idx
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; GCN-NEXT: BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHL_B32_]], implicit $exec, implicit [[S_LSHR_B32_]] {
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 0, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_dsta = V_MAX_U32_e64 12345, internal $stg_srca, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHR_B32_]], 0, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: same-bb-load-store-different-idx
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHR_B32_]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit $idx2, implicit $exec, implicit $idx1 {
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx2, 0, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta = V_MAX_U32_e64 12345, internal $stg_srca, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 0, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: same-bb-load-store-different-idx
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr1
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr1 = S_LSHR_B32 renamable $sgpr0, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 72
    ; LOWERED-NEXT: undef $vgpr0 = V_MAX_U32_e64 12345, undef $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:sreg_32_xexec_hi = S_LSHR_B32 %0, 2, implicit-def dead $scc
    %2:vgpr_32 = V_LOAD_IDX %0, 0, implicit $exec :: (load (s32), addrspace 10)
    %3:vgpr_32 = V_MAX_U32_e64 12345, %2, implicit $exec
    V_STORE_IDX %3:vgpr_32, %1, 0, implicit $exec :: (store (s32), addrspace 10)
...

---
name:            same-bb-load-store-different-idx-out-of-order
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: same-bb-load-store-different-idx-out-of-order
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; GCN-NEXT: [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 54321, [[S_LSHL_B32_]], implicit $exec
    ; GCN-NEXT: BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHR_B32_]], implicit $exec, implicit [[S_LSHL_B32_]] {
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHR_B32_]], 0, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_dsta = V_MAX_U32_e64 12345, internal $stg_srca, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_]], 0, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: same-bb-load-store-different-idx-out-of-order
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 [[S_LSHR_B32_]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit $idx2, implicit $exec, implicit $idx1 {
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx2, 0, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta = V_MAX_U32_e64 12345, internal $stg_srca, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 0, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: same-bb-load-store-different-idx-out-of-order
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr1
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr1 = S_LSHR_B32 renamable $sgpr0, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 72
    ; LOWERED-NEXT: undef $vgpr0 = V_MAX_U32_e64 12345, undef $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:sreg_32_xexec_hi = S_LSHR_B32 %0, 2, implicit-def dead $scc
    %2:vgpr_32 = V_LOAD_IDX %1, 0, implicit $exec :: (load (s32), addrspace 10)
    %3:vgpr_32 = V_MAX_U32_e64 12345, %2, implicit $exec
    %4:vgpr_32 = V_MAX_U32_e64 54321, %0, implicit $exec
    V_STORE_IDX %3:vgpr_32, %0, 0, implicit $exec :: (store (s32), addrspace 10)
...

---
name:            same-bb-multi-use-coremi
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: same-bb-multi-use-coremi
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: BUNDLE implicit-def $stg_srca, implicit-def %2, implicit [[S_LSHL_B32_]], implicit $exec {
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 0, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 12345, internal $stg_srca, implicit $exec
    ; GCN-NEXT: }
    ; GCN-NEXT: [[V_MIN_U32_e64_:%[0-9]+]]:vgpr_32 = V_MIN_U32_e64 12345, [[V_MAX_U32_e64_]], implicit $exec
    ; GCN-NEXT: V_STORE_IDX [[V_MAX_U32_e64_]], [[S_LSHL_B32_]], 0, implicit $exec :: (store (s32), addrspace 10)
    ;
    ; ALLOC-LABEL: name: same-bb-multi-use-coremi
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srca, implicit-def %2, implicit $idx1, implicit $exec {
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx1, 0, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 12345, internal $stg_srca, implicit $exec
    ; ALLOC-NEXT: }
    ; ALLOC-NEXT: V_STORE_IDX [[V_MAX_U32_e64_]], $idx1, 0, implicit $exec :: (store (s32), addrspace 10)
    ;
    ; LOWERED-LABEL: name: same-bb-multi-use-coremi
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 4
    ; LOWERED-NEXT: renamable $vgpr0 = V_MAX_U32_e64 12345, undef $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 64
    ; LOWERED-NEXT: $vgpr0 = V_MOV_B32_e32 $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:vgpr_32 = V_LOAD_IDX %0, 0, implicit $exec :: (load (s32), addrspace 10)
    %2:vgpr_32 = V_MAX_U32_e64 12345, %1, implicit $exec
    %3:vgpr_32 = V_MIN_U32_e64 12345, %2, implicit $exec
    V_STORE_IDX %2:vgpr_32, %0, 0, implicit $exec :: (store (s32), addrspace 10)
...

# TODO-GFX13 Should be able to duplicate load and bundle. AA is an issue.
---
name:            same-bb-multi-use-load-coremi
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: same-bb-multi-use-load-coremi
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[V_LOAD_IDX:%[0-9]+]]:vgpr_32 = V_LOAD_IDX [[S_LSHL_B32_]], 0, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT: BUNDLE implicit-def $stg_srca, implicit-def %2, implicit [[S_LSHL_B32_]], implicit $exec {
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 0, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 12345, internal $stg_srca, implicit $exec
    ; GCN-NEXT: }
    ; GCN-NEXT: [[V_MIN_U32_e64_:%[0-9]+]]:vgpr_32 = V_MIN_U32_e64 12345, [[V_MAX_U32_e64_]], implicit $exec
    ; GCN-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_MOV_B32 5
    ; GCN-NEXT: V_STORE_IDX [[V_MAX_U32_e64_]], [[S_MOV_B32_]], 0, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: BUNDLE implicit-def $stg_dsta, implicit [[V_LOAD_IDX]], implicit $exec, implicit [[S_LSHL_B32_]] {
    ; GCN-NEXT:   $stg_dsta = V_MIN_U32_e64 12345, [[V_LOAD_IDX]], implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_]], 16, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: same-bb-multi-use-load-coremi
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: [[V_LOAD_IDX:%[0-9]+]]:vgpr_32 = V_LOAD_IDX $idx1, 0, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srca, implicit-def %2, implicit $idx1, implicit $exec {
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx1, 0, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 12345, internal $stg_srca, implicit $exec
    ; ALLOC-NEXT: }
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 0
    ; ALLOC-NEXT: V_STORE_IDX [[V_MAX_U32_e64_]], $idx2, 5, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_dsta, implicit [[V_LOAD_IDX]], implicit $exec, implicit $idx1 {
    ; ALLOC-NEXT:   $stg_dsta = V_MIN_U32_e64 12345, [[V_LOAD_IDX]], implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 16, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: same-bb-multi-use-load-coremi
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr1
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 5
    ; LOWERED-NEXT: $vgpr0 = V_MOV_B32_e32 undef $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: renamable $vgpr1 = V_MAX_U32_e64 12345, undef $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 0
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 128
    ; LOWERED-NEXT: $vgpr5 = V_MOV_B32_e32 $vgpr1, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 64
    ; LOWERED-NEXT: undef $vgpr16 = V_MIN_U32_e64 12345, killed $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:vgpr_32 = V_LOAD_IDX %0, 0, implicit $exec :: (load (s32), addrspace 10)
    %2:vgpr_32 = V_MAX_U32_e64 12345, %1, implicit $exec
    %3:vgpr_32 = V_MIN_U32_e64 12345, %1, implicit $exec
    %4:vgpr_32 = V_MIN_U32_e64 12345, %2, implicit $exec
    %5:sreg_32_xexec_hi = S_MOV_B32 5
    V_STORE_IDX %2:vgpr_32, %5, 0, implicit $exec :: (store (s32), addrspace 10)
    V_STORE_IDX %3:vgpr_32, %0, 16, implicit $exec :: (store (s32), addrspace 10)
...

---
name:            multi-use-in-one-mi-load
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: multi-use-in-one-mi-load
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: BUNDLE implicit-def $stg_srca, implicit-def %2, implicit [[S_LSHL_B32_]], implicit $exec {
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 0, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 internal $stg_srca, internal $stg_srca, implicit $exec
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: multi-use-in-one-mi-load
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srca, implicit-def %2, implicit $idx1, implicit $exec {
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx1, 0, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 internal $stg_srca, internal $stg_srca, implicit $exec
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: multi-use-in-one-mi-load
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 5
    ; LOWERED-NEXT: renamable $vgpr0 = V_MAX_U32_e64 undef $vgpr0, undef $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:vgpr_32 = V_LOAD_IDX %0, 0, implicit $exec :: (load (s32), addrspace 10)
    %2:vgpr_32 = V_MAX_U32_e64 %1, %1, implicit $exec
...

---
name:            same-bb-multi-use-load
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: same-bb-multi-use-load
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: BUNDLE implicit-def $stg_srca, implicit-def %2, implicit [[S_LSHL_B32_]], implicit $exec {
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 0, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 12345, internal $stg_srca, implicit $exec
    ; GCN-NEXT: }
    ; GCN-NEXT: BUNDLE implicit-def $stg_srca, implicit-def %3, implicit [[S_LSHL_B32_]], implicit $exec {
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 0, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   [[V_MIN_U32_e64_:%[0-9]+]]:vgpr_32 = V_MIN_U32_e64 65432, internal $stg_srca, implicit $exec
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: same-bb-multi-use-load
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srca, implicit-def %2, implicit $idx1, implicit $exec {
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx1, 0, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 12345, internal $stg_srca, implicit $exec
    ; ALLOC-NEXT: }
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srca, implicit-def %3, implicit $idx1, implicit $exec {
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx1, 0, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   [[V_MIN_U32_e64_:%[0-9]+]]:vgpr_32 = V_MIN_U32_e64 65432, internal $stg_srca, implicit $exec
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: same-bb-multi-use-load
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 4
    ; LOWERED-NEXT: renamable $vgpr0 = V_MAX_U32_e64 12345, undef $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: renamable $vgpr0 = V_MIN_U32_e64 65432, undef $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:vgpr_32 = V_LOAD_IDX %0, 0, implicit $exec :: (load (s32), addrspace 10)
    %2:vgpr_32 = V_MAX_U32_e64 12345, %1, implicit $exec
    %3:vgpr_32 = V_MIN_U32_e64 65432, %1, implicit $exec
...


---
name:            load-2x2-uses
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: load-2x2-uses
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; GCN-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHR_B32_]], 3, implicit-def dead $scc
    ; GCN-NEXT: BUNDLE implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def %5, implicit [[S_LSHR_B32_]], implicit $exec, implicit [[S_LSHL_B32_]] {
    ; GCN-NEXT:   $stg_srcb = V_LOAD_IDX [[S_LSHR_B32_]], 10, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 5, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   [[V_LSHL_ADD_U32_e64_:%[0-9]+]]:vgpr_32 = V_LSHL_ADD_U32_e64 internal $stg_srca, internal $stg_srca, internal $stg_srcb, implicit $exec
    ; GCN-NEXT: }
    ; GCN-NEXT: BUNDLE implicit-def $stg_srca, implicit-def %6, implicit [[S_LSHR_B32_]], implicit $exec {
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHR_B32_]], 10, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   [[V_LSHL_ADD_U32_e64_1:%[0-9]+]]:vgpr_32 = V_LSHL_ADD_U32_e64 0, internal $stg_srca, internal $stg_srca, implicit $exec
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: load-2x2-uses
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHR_B32_]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def %5, implicit $idx1, implicit $exec, implicit $idx2 {
    ; ALLOC-NEXT:   $stg_srcb = V_LOAD_IDX $idx1, 10, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx2, 5, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   [[V_LSHL_ADD_U32_e64_:%[0-9]+]]:vgpr_32 = V_LSHL_ADD_U32_e64 internal $stg_srca, internal $stg_srca, internal $stg_srcb, implicit $exec
    ; ALLOC-NEXT: }
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srca, implicit-def %6, implicit $idx1, implicit $exec {
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx1, 10, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   [[V_LSHL_ADD_U32_e64_1:%[0-9]+]]:vgpr_32 = V_LSHL_ADD_U32_e64 0, internal $stg_srca, internal $stg_srca, implicit $exec
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: load-2x2-uses
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr1
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr1 = S_LSHR_B32 renamable $sgpr0, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 26
    ; LOWERED-NEXT: renamable $vgpr0 = V_LSHL_ADD_U32_e64 undef $vgpr5, undef $vgpr5, undef $vgpr10, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 20
    ; LOWERED-NEXT: renamable $vgpr0 = V_LSHL_ADD_U32_e64 0, undef $vgpr10, undef $vgpr10, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:sreg_32_xexec_hi = S_LSHR_B32 %0, 2, implicit-def dead $scc
    %2:sreg_32_xexec_hi = S_LSHL_B32 %1, 3, implicit-def dead $scc
    %3:vgpr_32 = V_LOAD_IDX %0, 5, implicit $exec :: (load (s32), addrspace 10)
    %4:vgpr_32 = V_LOAD_IDX %1, 10, implicit $exec :: (load (s32), addrspace 10)
    %5:vgpr_32 = V_LSHL_ADD_U32_e64 %3, %3, %4, implicit $exec
    %6:vgpr_32 = V_LSHL_ADD_U32_e64 0, %4, %4, implicit $exec
...

---
name:            same-bb-multi-use-load-store
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: same-bb-multi-use-load-store
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[V_LOAD_IDX:%[0-9]+]]:vgpr_32 = V_LOAD_IDX [[S_LSHL_B32_]], 0, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT: BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHL_B32_]], implicit $exec {
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 0, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_dsta = V_MAX_U32_e64 12345, internal $stg_srca, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_]], 0, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ; GCN-NEXT: BUNDLE implicit-def $stg_dsta, implicit [[V_LOAD_IDX]], implicit $exec, implicit [[S_LSHL_B32_]] {
    ; GCN-NEXT:   $stg_dsta = V_MIN_U32_e64 65432, [[V_LOAD_IDX]], implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_]], 0, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: same-bb-multi-use-load-store
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: [[V_LOAD_IDX:%[0-9]+]]:vgpr_32 = V_LOAD_IDX $idx1, 0, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit $idx1, implicit $exec {
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx1, 0, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta = V_MAX_U32_e64 12345, internal $stg_srca, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 0, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_dsta, implicit [[V_LOAD_IDX]], implicit $exec, implicit $idx1 {
    ; ALLOC-NEXT:   $stg_dsta = V_MIN_U32_e64 65432, [[V_LOAD_IDX]], implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 0, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: same-bb-multi-use-load-store
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 1
    ; LOWERED-NEXT: $vgpr0 = V_MOV_B32_e32 undef $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 68
    ; LOWERED-NEXT: undef $vgpr0 = V_MAX_U32_e64 12345, undef $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 64
    ; LOWERED-NEXT: undef $vgpr0 = V_MIN_U32_e64 65432, killed $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:vgpr_32 = V_LOAD_IDX %0, 0, implicit $exec :: (load (s32), addrspace 10)
    %2:vgpr_32 = V_MAX_U32_e64 12345, %1, implicit $exec
    %3:vgpr_32 = V_MIN_U32_e64 65432, %1, implicit $exec
    V_STORE_IDX %2:vgpr_32, %0, 0, implicit $exec :: (store (s32), addrspace 10)
    V_STORE_IDX %3:vgpr_32, %0, 0, implicit $exec :: (store (s32), addrspace 10)
...
---
name:            same-bb-load-store-vop2
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: same-bb-load-store-vop2
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; GCN-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHR_B32_]], 3, implicit-def dead $scc
    ; GCN-NEXT: [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 54321, [[S_LSHL_B32_]], implicit $exec
    ; GCN-NEXT: BUNDLE implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHR_B32_]], implicit $exec, implicit [[S_LSHL_B32_]], implicit [[S_LSHL_B32_1]] {
    ; GCN-NEXT:   $stg_srcb = V_LOAD_IDX [[S_LSHR_B32_]], 10, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 5, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_dsta = V_ADD_U32_e64 internal $stg_srca, internal $stg_srcb, 0, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_1]], 20, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: same-bb-load-store-vop2
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; ALLOC-NEXT: $idx3 = S_SET_GPR_IDX_U32 [[S_LSHR_B32_]]
    ; ALLOC-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHR_B32_]], 3, implicit-def dead $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_1]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def $stg_dsta, implicit $idx3, implicit $exec, implicit $idx2, implicit $idx1 {
    ; ALLOC-NEXT:   $stg_srcb = V_LOAD_IDX $idx3, 10, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx2, 5, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta = V_ADD_U32_e64 internal $stg_srca, internal $stg_srcb, 0, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 20, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: same-bb-load-store-vop2
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr1
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr1 = S_LSHR_B32 renamable $sgpr0, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 renamable $sgpr1, 3, implicit-def dead $scc
    ; LOWERED-NEXT: $idx3 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 78
    ; LOWERED-NEXT: undef $vgpr20 = V_ADD_U32_e64 undef $vgpr5, undef $vgpr10, 0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:sreg_32_xexec_hi = S_LSHR_B32 %0, 2, implicit-def dead $scc
    %2:sreg_32_xexec_hi = S_LSHL_B32 %1, 3, implicit-def dead $scc
    %3:vgpr_32 = V_LOAD_IDX %0, 5, implicit $exec :: (load (s32), addrspace 10)
    %4:vgpr_32 = V_LOAD_IDX %1, 10, implicit $exec :: (load (s32), addrspace 10)
    %5:vgpr_32 = V_ADD_U32_e64 %3, %4, 0, implicit $exec
    %6:vgpr_32 = V_MAX_U32_e64 54321, %0, implicit $exec
    V_STORE_IDX %5:vgpr_32, %2, 20, implicit $exec :: (store (s32), addrspace 10)
...

# Lowers VOP3 instructions by using idx0 save and restore
---
name:            same-bb-load-store-vop3
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: same-bb-load-store-vop3
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; GCN-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHR_B32_]], 3, implicit-def dead $scc
    ; GCN-NEXT: [[S_LSHR_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHR_B32_]], 4, implicit-def dead $scc
    ; GCN-NEXT: [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 54321, [[S_LSHL_B32_]], implicit $exec
    ; GCN-NEXT: BUNDLE implicit-def $stg_srcc, implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHL_B32_1]], implicit $exec, implicit [[S_LSHR_B32_]], implicit [[S_LSHL_B32_]], implicit [[S_LSHR_B32_1]] {
    ; GCN-NEXT:   $stg_srcc = V_LOAD_IDX [[S_LSHL_B32_1]], 15, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srcb = V_LOAD_IDX [[S_LSHR_B32_]], 10, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 5, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_dsta = V_LSHL_ADD_U32_e64 internal $stg_srca, internal $stg_srcb, internal $stg_srcc, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHR_B32_1]], 20, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: same-bb-load-store-vop3
    ; ALLOC: $idx0 = S_SET_GPR_IDX_U32 0
    ; ALLOC-NEXT: [[COPY:%[0-9]+]]:sreg_32_xm0_xexec = COPY $idx0
    ; ALLOC-NEXT: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; ALLOC-NEXT: $idx3 = S_SET_GPR_IDX_U32 [[S_LSHR_B32_]]
    ; ALLOC-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHR_B32_]], 3, implicit-def dead $scc
    ; ALLOC-NEXT: [[S_LSHR_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHR_B32_]], 4, implicit-def dead $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHR_B32_1]]
    ; ALLOC-NEXT: $idx0 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_1]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srcc, implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def $stg_dsta, implicit $idx0, implicit $exec, implicit $idx3, implicit $idx2, implicit $idx1 {
    ; ALLOC-NEXT:   $stg_srcc = V_LOAD_IDX $idx0, 15, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srcb = V_LOAD_IDX $idx3, 10, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx2, 5, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta = V_LSHL_ADD_U32_e64 internal $stg_srca, internal $stg_srcb, internal $stg_srcc, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 20, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ; ALLOC-NEXT: $idx0 = S_SET_GPR_IDX_U32 [[COPY]]
    ;
    ; LOWERED-LABEL: name: same-bb-load-store-vop3
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr1
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr2
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $sgpr1 = S_GETREG_B32 63532, implicit $mode
    ; LOWERED-NEXT: renamable $sgpr2 = S_LSHR_B32 renamable $sgpr0, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: $idx3 = S_SET_GPR_IDX_U32 renamable $sgpr2
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHR_B32 renamable $sgpr2, 4, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr2 = S_LSHL_B32 killed renamable $sgpr2, 3, implicit-def dead $scc
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: $idx0 = S_SET_GPR_IDX_U32 killed renamable $sgpr2
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 78
    ; LOWERED-NEXT: undef $vgpr20 = V_LSHL_ADD_U32_e64 undef $vgpr5, undef $vgpr10, undef $vgpr15, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: dead $idx0 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:sreg_32_xexec_hi = S_LSHR_B32 %0, 2, implicit-def dead $scc
    %2:sreg_32_xexec_hi = S_LSHL_B32 %1, 3, implicit-def dead $scc
    %3:sreg_32_xexec_hi = S_LSHR_B32 %1, 4, implicit-def dead $scc
    %4:vgpr_32 = V_LOAD_IDX %0, 5, implicit $exec :: (load (s32), addrspace 10)
    %5:vgpr_32 = V_LOAD_IDX %1, 10, implicit $exec :: (load (s32), addrspace 10)
    %6:vgpr_32 = V_LOAD_IDX %2, 15, implicit $exec :: (load (s32), addrspace 10)
    %7:vgpr_32 = V_LSHL_ADD_U32_e64 %4, %5, %6, implicit $exec
    %8:vgpr_32 = V_MAX_U32_e64 54321, %0, implicit $exec
    V_STORE_IDX %7:vgpr_32, %3, 20, implicit $exec :: (store (s32), addrspace 10)
...

---
name:            same-bb-load-store-vop3-two-unique-idx
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: same-bb-load-store-vop3-two-unique-idx
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; GCN-NEXT: [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 54321, [[S_LSHL_B32_]], implicit $exec
    ; GCN-NEXT: BUNDLE implicit-def $stg_srcc, implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHR_B32_]], implicit $exec, implicit [[S_LSHL_B32_]] {
    ; GCN-NEXT:   $stg_srcc = V_LOAD_IDX [[S_LSHR_B32_]], 15, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srcb = V_LOAD_IDX [[S_LSHL_B32_]], 10, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 5, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_dsta = V_LSHL_ADD_U32_e64 internal $stg_srca, internal $stg_srcb, internal $stg_srcc, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHR_B32_]], 20, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: same-bb-load-store-vop3-two-unique-idx
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHR_B32_]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srcc, implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def $stg_dsta, implicit $idx1, implicit $exec, implicit $idx2 {
    ; ALLOC-NEXT:   $stg_srcc = V_LOAD_IDX $idx1, 15, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srcb = V_LOAD_IDX $idx2, 10, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx2, 5, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta = V_LSHL_ADD_U32_e64 internal $stg_srca, internal $stg_srcb, internal $stg_srcc, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 20, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: same-bb-load-store-vop3-two-unique-idx
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr1
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr1 = S_LSHR_B32 renamable $sgpr0, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 90
    ; LOWERED-NEXT: undef $vgpr20 = V_LSHL_ADD_U32_e64 undef $vgpr5, undef $vgpr10, undef $vgpr15, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:sreg_32_xexec_hi = S_LSHR_B32 %0, 2, implicit-def dead $scc
    %2:vgpr_32 = V_LOAD_IDX %0, 5, implicit $exec :: (load (s32), addrspace 10)
    %3:vgpr_32 = V_LOAD_IDX %0, 10, implicit $exec :: (load (s32), addrspace 10)
    %4:vgpr_32 = V_LOAD_IDX %1, 15, implicit $exec :: (load (s32), addrspace 10)
    %5:vgpr_32 = V_LSHL_ADD_U32_e64 %2, %3, %4, implicit $exec
    %6:vgpr_32 = V_MAX_U32_e64 54321, %0, implicit $exec
    V_STORE_IDX %5:vgpr_32, %1, 20, implicit $exec :: (store (s32), addrspace 10)
...

---
name:            insert-set-gpr-idx-after-bundle
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: insert-set-gpr-idx-after-bundle
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; GCN-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHR_B32_]], 3, implicit-def dead $scc
    ; GCN-NEXT: [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 54321, [[S_LSHL_B32_]], implicit $exec
    ; GCN-NEXT: BUNDLE implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHR_B32_]], implicit $exec, implicit [[S_LSHL_B32_]], implicit [[S_LSHL_B32_1]] {
    ; GCN-NEXT:   $stg_srcb = V_LOAD_IDX [[S_LSHR_B32_]], 10, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 5, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_dsta = V_ADD_U32_e64 internal $stg_srca, internal $stg_srcb, 0, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_1]], 20, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ; GCN-NEXT: [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 3, implicit-def $scc
    ; GCN-NEXT: [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def $scc
    ; GCN-NEXT: BUNDLE implicit-def $stg_srcb, implicit-def $stg_srca, implicit [[S_LSHL_B32_2]], implicit $exec, implicit [[S_LSHL_B32_3]], implicit $m0 {
    ; GCN-NEXT:   $stg_srcb = V_LOAD_IDX [[S_LSHL_B32_2]], 1, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_3]], 2, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   DS_WRITE_B32 internal $stg_srca, internal $stg_srcb, 4, 0, implicit $exec, implicit $m0 :: (store (s32), addrspace 3)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: insert-set-gpr-idx-after-bundle
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; ALLOC-NEXT: $idx3 = S_SET_GPR_IDX_U32 [[S_LSHR_B32_]]
    ; ALLOC-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHR_B32_]], 3, implicit-def dead $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_1]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def $stg_dsta, implicit $idx3, implicit $exec, implicit $idx2, implicit $idx1 {
    ; ALLOC-NEXT:   $stg_srcb = V_LOAD_IDX $idx3, 10, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx2, 5, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta = V_ADD_U32_e64 internal $stg_srca, internal $stg_srcb, 0, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 20, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ; ALLOC-NEXT: [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 3, implicit-def $scc
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_2]]
    ; ALLOC-NEXT: [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_3]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srcb, implicit-def $stg_srca, implicit $idx2, implicit $exec, implicit $idx1, implicit $m0 {
    ; ALLOC-NEXT:   $stg_srcb = V_LOAD_IDX $idx2, 1, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx1, 2, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   DS_WRITE_B32 internal $stg_srca, internal $stg_srcb, 4, 0, implicit $exec, implicit $m0 :: (store (s32), addrspace 3)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: insert-set-gpr-idx-after-bundle
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr1
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr1 = S_LSHR_B32 renamable $sgpr0, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 renamable $sgpr1, 3, implicit-def dead $scc
    ; LOWERED-NEXT: $idx3 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 3, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr1 = S_LSHL_B32 1, 4, implicit-def dead $scc
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 78
    ; LOWERED-NEXT: undef $vgpr20 = V_ADD_U32_e64 undef $vgpr5, undef $vgpr10, 0, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 9
    ; LOWERED-NEXT: DS_WRITE_B32 undef $vgpr2, undef $vgpr1, 4, 0, <0x{{[0-9a-f]+}}>, implicit $exec, implicit $m0 :: (store (s32), addrspace 3)
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:sreg_32_xexec_hi = S_LSHR_B32 %0, 2, implicit-def dead $scc
    %2:sreg_32_xexec_hi = S_LSHL_B32 %1, 3, implicit-def dead $scc
    %3:vgpr_32 = V_LOAD_IDX %0, 5, implicit $exec :: (load (s32), addrspace 10)
    %4:vgpr_32 = V_LOAD_IDX %1, 10, implicit $exec :: (load (s32), addrspace 10)
    %5:vgpr_32 = V_ADD_U32_e64 %3, %4, 0, implicit $exec
    %6:vgpr_32 = V_MAX_U32_e64 54321, %0, implicit $exec
    V_STORE_IDX %5:vgpr_32, %2, 20, implicit $exec :: (store (s32), addrspace 10)
    %7:sreg_32_xexec_hi = S_LSHL_B32 1, 3, implicit-def $scc
    %8:vgpr_32 = V_LOAD_IDX %7, 1, implicit $exec :: (load (s32), addrspace 10)
    %9:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def $scc
    %10:vgpr_32 = V_LOAD_IDX %9, 2, implicit $exec :: (load (s32), addrspace 10)
    DS_WRITE_B32 %10, %8, 4, 0, implicit $exec, implicit $m0 :: (store (s32), addrspace 3)
...

---
name:            two-bundles-vop3-vop2
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: two-bundles-vop3-vop2
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; GCN-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHR_B32_]], 3, implicit-def dead $scc
    ; GCN-NEXT: [[S_LSHR_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHR_B32_]], 4, implicit-def dead $scc
    ; GCN-NEXT: [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 54321, [[S_LSHL_B32_]], implicit $exec
    ; GCN-NEXT: BUNDLE implicit-def $stg_srcc, implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHL_B32_1]], implicit $exec, implicit [[S_LSHR_B32_]], implicit [[S_LSHL_B32_]], implicit [[S_LSHR_B32_1]] {
    ; GCN-NEXT:   $stg_srcc = V_LOAD_IDX [[S_LSHL_B32_1]], 15, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srcb = V_LOAD_IDX [[S_LSHR_B32_]], 10, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 5, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_dsta = V_LSHL_ADD_U32_e64 internal $stg_srca, internal $stg_srcb, internal $stg_srcc, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHR_B32_1]], 20, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ; GCN-NEXT: [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 12, implicit-def $scc
    ; GCN-NEXT: [[S_LSHR_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 12, implicit-def dead $scc
    ; GCN-NEXT: [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHR_B32_]], 13, implicit-def dead $scc
    ; GCN-NEXT: [[V_MAX_U32_e64_1:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 54, [[S_LSHL_B32_]], implicit $exec
    ; GCN-NEXT: BUNDLE implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHR_B32_2]], implicit $exec, implicit [[S_LSHL_B32_2]], implicit [[S_LSHL_B32_3]] {
    ; GCN-NEXT:   $stg_srcb = V_LOAD_IDX [[S_LSHR_B32_2]], 11, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_2]], 6, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_dsta = V_ADD_U32_e64 internal $stg_srca, internal $stg_srcb, 0, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_3]], 21, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: two-bundles-vop3-vop2
    ; ALLOC: $idx0 = S_SET_GPR_IDX_U32 0
    ; ALLOC-NEXT: [[COPY:%[0-9]+]]:sreg_32_xm0_xexec = COPY $idx0
    ; ALLOC-NEXT: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; ALLOC-NEXT: $idx3 = S_SET_GPR_IDX_U32 [[S_LSHR_B32_]]
    ; ALLOC-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHR_B32_]], 3, implicit-def dead $scc
    ; ALLOC-NEXT: [[S_LSHR_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHR_B32_]], 4, implicit-def dead $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHR_B32_1]]
    ; ALLOC-NEXT: $idx0 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_1]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srcc, implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def $stg_dsta, implicit $idx0, implicit $exec, implicit $idx3, implicit $idx2, implicit $idx1 {
    ; ALLOC-NEXT:   $stg_srcc = V_LOAD_IDX $idx0, 15, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srcb = V_LOAD_IDX $idx3, 10, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx2, 5, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta = V_LSHL_ADD_U32_e64 internal $stg_srca, internal $stg_srcb, internal $stg_srcc, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 20, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ; ALLOC-NEXT: $idx0 = S_SET_GPR_IDX_U32 [[COPY]]
    ; ALLOC-NEXT: [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 12, implicit-def $scc
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_2]]
    ; ALLOC-NEXT: [[S_LSHR_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 12, implicit-def dead $scc
    ; ALLOC-NEXT: $idx3 = S_SET_GPR_IDX_U32 [[S_LSHR_B32_2]]
    ; ALLOC-NEXT: [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHR_B32_]], 13, implicit-def dead $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_3]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def $stg_dsta, implicit $idx3, implicit $exec, implicit $idx2, implicit $idx1 {
    ; ALLOC-NEXT:   $stg_srcb = V_LOAD_IDX $idx3, 11, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx2, 6, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta = V_ADD_U32_e64 internal $stg_srca, internal $stg_srcb, 0, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 21, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: two-bundles-vop3-vop2
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr1
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr2
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr3
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr4
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $sgpr1 = S_GETREG_B32 63532, implicit $mode
    ; LOWERED-NEXT: renamable $sgpr2 = S_LSHR_B32 renamable $sgpr0, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 renamable $sgpr0
    ; LOWERED-NEXT: renamable $sgpr3 = S_LSHR_B32 renamable $sgpr2, 4, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr4 = S_LSHL_B32 renamable $sgpr2, 3, implicit-def dead $scc
    ; LOWERED-NEXT: $idx3 = S_SET_GPR_IDX_U32 renamable $sgpr2
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr3
    ; LOWERED-NEXT: $idx0 = S_SET_GPR_IDX_U32 killed renamable $sgpr4
    ; LOWERED-NEXT: renamable $sgpr3 = S_LSHL_B32 1, 12, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHR_B32 killed renamable $sgpr0, 12, implicit-def dead $scc
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 78
    ; LOWERED-NEXT: undef $vgpr20 = V_LSHL_ADD_U32_e64 undef $vgpr5, undef $vgpr10, undef $vgpr15, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: dead $idx0 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 killed renamable $sgpr3
    ; LOWERED-NEXT: renamable $sgpr1 = S_LSHL_B32 killed renamable $sgpr2, 13, implicit-def dead $scc
    ; LOWERED-NEXT: $idx3 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    ; LOWERED-NEXT: undef $vgpr21 = V_ADD_U32_e64 undef $vgpr6, undef $vgpr11, 0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:sreg_32_xexec_hi = S_LSHR_B32 %0, 2, implicit-def dead $scc
    %2:sreg_32_xexec_hi = S_LSHL_B32 %1, 3, implicit-def dead $scc
    %3:sreg_32_xexec_hi = S_LSHR_B32 %1, 4, implicit-def dead $scc
    %4:vgpr_32 = V_LOAD_IDX %0, 5, implicit $exec :: (load (s32), addrspace 10)
    %5:vgpr_32 = V_LOAD_IDX %1, 10, implicit $exec :: (load (s32), addrspace 10)
    %6:vgpr_32 = V_LOAD_IDX %2, 15, implicit $exec :: (load (s32), addrspace 10)
    %7:vgpr_32 = V_LSHL_ADD_U32_e64 %4, %5, %6, implicit $exec
    %8:vgpr_32 = V_MAX_U32_e64 54321, %0, implicit $exec
    V_STORE_IDX %7:vgpr_32, %3, 20, implicit $exec :: (store (s32), addrspace 10)
    %9:sreg_32_xexec_hi = S_LSHL_B32 1, 12, implicit-def $scc
    %10:sreg_32_xexec_hi = S_LSHR_B32 %0, 12, implicit-def dead $scc
    %11:sreg_32_xexec_hi = S_LSHL_B32 %1, 13, implicit-def dead $scc
    %12:vgpr_32 = V_LOAD_IDX %9, 6, implicit $exec :: (load (s32), addrspace 10)
    %13:vgpr_32 = V_LOAD_IDX %10, 11, implicit $exec :: (load (s32), addrspace 10)
    %14:vgpr_32 = V_ADD_U32_e64 %12, %13, 0, implicit $exec
    %15:vgpr_32 = V_MAX_U32_e64 54, %0, implicit $exec
    V_STORE_IDX %14:vgpr_32, %11, 21, implicit $exec :: (store (s32), addrspace 10)
...

---
name:            two-bundles-same-idx
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: two-bundles-same-idx
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; GCN-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHR_B32_]], 3, implicit-def dead $scc
    ; GCN-NEXT: [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 54321, [[S_LSHL_B32_]], implicit $exec
    ; GCN-NEXT: BUNDLE implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHR_B32_]], implicit $exec, implicit [[S_LSHL_B32_]], implicit [[S_LSHL_B32_1]] {
    ; GCN-NEXT:   $stg_srcb = V_LOAD_IDX [[S_LSHR_B32_]], 10, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 5, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_dsta = V_ADD_U32_e64 internal $stg_srca, internal $stg_srcb, 0, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_1]], 20, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ; GCN-NEXT: [[V_MAX_U32_e64_1:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 54, [[S_LSHL_B32_]], implicit $exec
    ; GCN-NEXT: BUNDLE implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHR_B32_]], implicit $exec, implicit [[S_LSHL_B32_]], implicit [[S_LSHL_B32_1]] {
    ; GCN-NEXT:   $stg_srcb = V_LOAD_IDX [[S_LSHR_B32_]], 11, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 6, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_dsta = V_ADD_U32_e64 internal $stg_srca, internal $stg_srcb, 0, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_1]], 21, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: two-bundles-same-idx
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; ALLOC-NEXT: $idx3 = S_SET_GPR_IDX_U32 [[S_LSHR_B32_]]
    ; ALLOC-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHR_B32_]], 3, implicit-def dead $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_1]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def $stg_dsta, implicit $idx3, implicit $exec, implicit $idx2, implicit $idx1 {
    ; ALLOC-NEXT:   $stg_srcb = V_LOAD_IDX $idx3, 10, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx2, 5, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta = V_ADD_U32_e64 internal $stg_srca, internal $stg_srcb, 0, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 20, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def $stg_dsta, implicit $idx3, implicit $exec, implicit $idx2, implicit $idx1 {
    ; ALLOC-NEXT:   $stg_srcb = V_LOAD_IDX $idx3, 11, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx2, 6, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta = V_ADD_U32_e64 internal $stg_srca, internal $stg_srcb, 0, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 21, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: two-bundles-same-idx
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr1
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr1 = S_LSHR_B32 renamable $sgpr0, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 renamable $sgpr1, 3, implicit-def dead $scc
    ; LOWERED-NEXT: $idx3 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 78
    ; LOWERED-NEXT: undef $vgpr20 = V_ADD_U32_e64 undef $vgpr5, undef $vgpr10, 0, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: undef $vgpr21 = V_ADD_U32_e64 undef $vgpr6, undef $vgpr11, 0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:sreg_32_xexec_hi = S_LSHR_B32 %0, 2, implicit-def dead $scc
    %2:sreg_32_xexec_hi = S_LSHL_B32 %1, 3, implicit-def dead $scc
    %3:vgpr_32 = V_LOAD_IDX %0, 5, implicit $exec :: (load (s32), addrspace 10)
    %4:vgpr_32 = V_LOAD_IDX %1, 10, implicit $exec :: (load (s32), addrspace 10)
    %5:vgpr_32 = V_ADD_U32_e64 %3, %4, 0, implicit $exec
    %6:vgpr_32 = V_MAX_U32_e64 54321, %0, implicit $exec
    V_STORE_IDX %5:vgpr_32, %2, 20, implicit $exec :: (store (s32), addrspace 10)
    %7:vgpr_32 = V_LOAD_IDX %0, 6, implicit $exec :: (load (s32), addrspace 10)
    %8:vgpr_32 = V_LOAD_IDX %1, 11, implicit $exec :: (load (s32), addrspace 10)
    %9:vgpr_32 = V_ADD_U32_e64 %7, %8, 0, implicit $exec
    %10:vgpr_32 = V_MAX_U32_e64 54, %0, implicit $exec
    V_STORE_IDX %9:vgpr_32, %2, 21, implicit $exec :: (store (s32), addrspace 10)
...

---
name:            same-bb-wide-load-store
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: same-bb-wide-load-store
    ; GCN: [[S_MOV_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_MOV_B32 48
    ; GCN-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_MOV_B32_]], 2, implicit-def dead $scc
    ; GCN-NEXT: [[S_MOV_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_MOV_B32 32
    ; GCN-NEXT: [[S_LSHR_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_MOV_B32_1]], 2, implicit-def dead $scc
    ; GCN-NEXT: [[S_MOV_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_MOV_B32 0
    ; GCN-NEXT: [[S_LSHR_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_MOV_B32_2]], 2, implicit-def dead $scc
    ; GCN-NEXT: BUNDLE implicit-def dead $stg_srcb, implicit-def dead $stg_srca, implicit-def early-clobber $stg_dsta, implicit [[S_LSHR_B32_1]], implicit $exec, implicit [[S_LSHR_B32_]], implicit [[S_LSHR_B32_2]] {
    ; GCN-NEXT:   $stg_srcb = V_LOAD_IDX [[S_LSHR_B32_1]], 0, implicit $exec :: (load (s128), addrspace 10)
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHR_B32_]], 0, implicit $exec :: (load (s128), addrspace 10)
    ; GCN-NEXT:   early-clobber $stg_dsta = contract V_WMMA_F32_16X16X16_F16_w32_threeaddr 8, internal killed $stg_srca, 8, internal killed $stg_srcb, 8, 0, 0, 0, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHR_B32_2]], 0, implicit $exec :: (store (s256), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: same-bb-wide-load-store
    ; ALLOC: $idx2 = S_SET_GPR_IDX_U32 12
    ; ALLOC-NEXT: $idx3 = S_SET_GPR_IDX_U32 8
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 0
    ; ALLOC-NEXT: BUNDLE implicit-def dead $stg_srcb, implicit-def dead $stg_srca, implicit-def early-clobber $stg_dsta, implicit $idx3, implicit $exec, implicit $idx2, implicit $idx1 {
    ; ALLOC-NEXT:   $stg_srcb = V_LOAD_IDX $idx3, 0, implicit $exec :: (load (s128), addrspace 10)
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx2, 0, implicit $exec :: (load (s128), addrspace 10)
    ; ALLOC-NEXT:   early-clobber $stg_dsta = contract V_WMMA_F32_16X16X16_F16_w32_threeaddr 8, internal killed $stg_srca, 8, internal killed $stg_srcb, 8, 0, 0, 0, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 0, implicit $exec :: (store (s256), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: same-bb-wide-load-store
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 12
    ; LOWERED-NEXT: $idx3 = S_SET_GPR_IDX_U32 8
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 0
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 78
    ; LOWERED-NEXT: undef early-clobber $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7 = contract V_WMMA_F32_16X16X16_F16_w32_threeaddr 8, killed undef $vgpr0_vgpr1_vgpr2_vgpr3, 8, killed undef $vgpr0_vgpr1_vgpr2_vgpr3, 8, 0, 0, 0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_MOV_B32 48
    %1:sreg_32_xexec_hi = S_LSHR_B32 %0, 2, implicit-def dead $scc
    %2:vreg_128_align2 = V_LOAD_IDX %1, 0, implicit $exec :: (load (s128), addrspace 10)
    %3:sreg_32_xexec_hi = S_MOV_B32 32
    %4:sreg_32_xexec_hi = S_LSHR_B32 %3, 2, implicit-def dead $scc
    %5:vreg_128_align2 = V_LOAD_IDX %4, 0, implicit $exec :: (load (s128), addrspace 10)
    %6:vreg_256_align2 = contract V_WMMA_F32_16X16X16_F16_w32_threeaddr 8, killed %2, 8, killed %5, 8, 0, 0, 0, implicit $exec
    %7:sreg_32_xexec_hi = S_MOV_B32 0
    %8:sreg_32_xexec_hi = S_LSHR_B32 %7, 2, implicit-def dead $scc
    V_STORE_IDX %6, %8, 0, implicit $exec :: (store (s256), addrspace 10)
...

---
name:            unsafe-load-past-store
# We do not currently analyze index and offset values to optimize potentially aliasing loads and stores.
# Therefore we should not bundle %12:vgpr_32 = V_LOAD_IDX %9, 6 with %14:vgpr_32 = V_ADD_U32_e64 %12, %13 as that would move it past a potentially aliasing store
# We never move stores in the current bundling algorithm so will never do an unsafe move of store past a load, but when updating the test in the future ensure that
# V_STORE_IDX %7:vgpr_32, %3, 20 does not happen before %12:vgpr_32 = V_LOAD_IDX %9, 6
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: unsafe-load-past-store
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; GCN-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHR_B32_]], 3, implicit-def dead $scc
    ; GCN-NEXT: [[S_LSHR_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHR_B32_]], 4, implicit-def dead $scc
    ; GCN-NEXT: [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 54321, [[S_LSHL_B32_]], implicit $exec
    ; GCN-NEXT: [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 12, implicit-def $scc
    ; GCN-NEXT: [[S_LSHR_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 12, implicit-def dead $scc
    ; GCN-NEXT: [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHR_B32_]], 13, implicit-def dead $scc
    ; GCN-NEXT: [[V_LOAD_IDX:%[0-9]+]]:vgpr_32 = V_LOAD_IDX [[S_LSHL_B32_2]], 6, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT: BUNDLE implicit-def $stg_srcc, implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHL_B32_1]], implicit $exec, implicit [[S_LSHR_B32_]], implicit [[S_LSHL_B32_]], implicit [[S_LSHR_B32_1]] {
    ; GCN-NEXT:   $stg_srcc = V_LOAD_IDX [[S_LSHL_B32_1]], 15, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srcb = V_LOAD_IDX [[S_LSHR_B32_]], 10, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 5, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_dsta = V_LSHL_ADD_U32_e64 internal $stg_srca, internal $stg_srcb, internal $stg_srcc, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHR_B32_1]], 20, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ; GCN-NEXT: [[V_MAX_U32_e64_1:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 54, [[S_LSHL_B32_]], implicit $exec
    ; GCN-NEXT: BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHR_B32_2]], implicit $exec, implicit [[V_LOAD_IDX]], implicit [[S_LSHL_B32_3]] {
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHR_B32_2]], 11, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_dsta = V_ADD_U32_e64 [[V_LOAD_IDX]], internal $stg_srca, 0, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_3]], 21, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: unsafe-load-past-store
    ; ALLOC: $idx0 = S_SET_GPR_IDX_U32 0
    ; ALLOC-NEXT: [[COPY:%[0-9]+]]:sreg_32_xm0_xexec = COPY $idx0
    ; ALLOC-NEXT: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 [[S_LSHR_B32_]]
    ; ALLOC-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHR_B32_]], 3, implicit-def dead $scc
    ; ALLOC-NEXT: [[S_LSHR_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHR_B32_]], 4, implicit-def dead $scc
    ; ALLOC-NEXT: $idx3 = S_SET_GPR_IDX_U32 [[S_LSHR_B32_1]]
    ; ALLOC-NEXT: [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 12, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_2]]
    ; ALLOC-NEXT: [[S_LSHR_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 12, implicit-def dead $scc
    ; ALLOC-NEXT: [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHR_B32_]], 13, implicit-def dead $scc
    ; ALLOC-NEXT: [[V_LOAD_IDX:%[0-9]+]]:vgpr_32 = V_LOAD_IDX $idx1, 6, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: $idx0 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_1]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srcc, implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def $stg_dsta, implicit $idx0, implicit $exec, implicit $idx2, implicit $idx1, implicit $idx3 {
    ; ALLOC-NEXT:   $stg_srcc = V_LOAD_IDX $idx0, 15, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srcb = V_LOAD_IDX $idx2, 10, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx1, 5, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta = V_LSHL_ADD_U32_e64 internal $stg_srca, internal $stg_srcb, internal $stg_srcc, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx3, 20, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ; ALLOC-NEXT: $idx0 = S_SET_GPR_IDX_U32 [[COPY]]
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 [[S_LSHR_B32_2]]
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_3]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit $idx2, implicit $exec, implicit [[V_LOAD_IDX]], implicit $idx1 {
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx2, 11, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta = V_ADD_U32_e64 [[V_LOAD_IDX]], internal $stg_srca, 0, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 21, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: unsafe-load-past-store
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr1
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr2
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr3
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr4
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr5
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr5 = S_LSHL_B32 1, 12, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr1 = S_LSHR_B32 renamable $sgpr0, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $sgpr2 = S_GETREG_B32 63532, implicit $mode
    ; LOWERED-NEXT: renamable $sgpr4 = S_LSHR_B32 renamable $sgpr1, 4, implicit-def dead $scc
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 renamable $sgpr1
    ; LOWERED-NEXT: renamable $sgpr3 = S_LSHL_B32 renamable $sgpr1, 3, implicit-def dead $scc
    ; LOWERED-NEXT: $idx3 = S_SET_GPR_IDX_U32 killed renamable $sgpr4
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr5
    ; LOWERED-NEXT: renamable $sgpr4 = S_LSHR_B32 renamable $sgpr0, 12, implicit-def dead $scc
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 1
    ; LOWERED-NEXT: $vgpr0 = V_MOV_B32_e32 undef $vgpr6, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: $idx0 = S_SET_GPR_IDX_U32 killed renamable $sgpr3
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 killed renamable $sgpr1, 13, implicit-def dead $scc
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 201
    ; LOWERED-NEXT: undef $vgpr20 = V_LSHL_ADD_U32_e64 undef $vgpr5, undef $vgpr10, undef $vgpr15, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: dead $idx0 = S_SET_GPR_IDX_U32 killed renamable $sgpr2
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 killed renamable $sgpr4
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 72
    ; LOWERED-NEXT: undef $vgpr21 = V_ADD_U32_e64 killed $vgpr0, undef $vgpr11, 0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:sreg_32_xexec_hi = S_LSHR_B32 %0, 2, implicit-def dead $scc
    %2:sreg_32_xexec_hi = S_LSHL_B32 %1, 3, implicit-def dead $scc
    %3:sreg_32_xexec_hi = S_LSHR_B32 %1, 4, implicit-def dead $scc
    %4:vgpr_32 = V_LOAD_IDX %0, 5, implicit $exec :: (load (s32), addrspace 10)
    %5:vgpr_32 = V_LOAD_IDX %1, 10, implicit $exec :: (load (s32), addrspace 10)
    %6:vgpr_32 = V_LOAD_IDX %2, 15, implicit $exec :: (load (s32), addrspace 10)
    %7:vgpr_32 = V_LSHL_ADD_U32_e64 %4, %5, %6, implicit $exec
    %8:vgpr_32 = V_MAX_U32_e64 54321, %0, implicit $exec
    %9:sreg_32_xexec_hi = S_LSHL_B32 1, 12, implicit-def $scc
    %10:sreg_32_xexec_hi = S_LSHR_B32 %0, 12, implicit-def dead $scc
    %11:sreg_32_xexec_hi = S_LSHL_B32 %1, 13, implicit-def dead $scc
    %12:vgpr_32 = V_LOAD_IDX %9, 6, implicit $exec :: (load (s32), addrspace 10)
    V_STORE_IDX %7:vgpr_32, %3, 20, implicit $exec :: (store (s32), addrspace 10)
    %13:vgpr_32 = V_LOAD_IDX %10, 11, implicit $exec :: (load (s32), addrspace 10)
    %14:vgpr_32 = V_ADD_U32_e64 %12, %13, 0, implicit $exec
    %15:vgpr_32 = V_MAX_U32_e64 54, %0, implicit $exec
    V_STORE_IDX %14:vgpr_32, %11, 21, implicit $exec :: (store (s32), addrspace 10)
...

---
name:            tied-operand
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: tied-operand
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; GCN-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHR_B32_]], 3, implicit-def dead $scc
    ; GCN-NEXT: [[V_LOAD_IDX:%[0-9]+]]:vgpr_32 = V_LOAD_IDX [[S_LSHL_B32_]], 5, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT: [[V_LOAD_IDX1:%[0-9]+]]:vgpr_32 = V_LOAD_IDX [[S_LSHR_B32_]], 10, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT: [[BUFFER_ATOMIC_ADD_F32_VBUFFER_OFFEN_RTN:%[0-9]+]]:vgpr_32 = BUFFER_ATOMIC_ADD_F32_VBUFFER_OFFEN_RTN [[V_LOAD_IDX1]], [[V_LOAD_IDX]], undef $sgpr0_sgpr1_sgpr2_sgpr3, undef $sgpr3, 0, 0, implicit $exec
    ; GCN-NEXT: [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 54321, [[S_LSHL_B32_]], implicit $exec
    ; GCN-NEXT: [[V_MAX_U32_e64_1:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 12345, [[S_LSHL_B32_]], implicit $exec
    ; GCN-NEXT: [[BUFFER_ATOMIC_ADD_F32_VBUFFER_OFFEN_RTN1:%[0-9]+]]:vgpr_32 = BUFFER_ATOMIC_ADD_F32_VBUFFER_OFFEN_RTN [[V_MAX_U32_e64_1]], [[V_MAX_U32_e64_]], undef $sgpr0_sgpr1_sgpr2_sgpr3, undef $sgpr3, 0, 0, implicit $exec
    ; GCN-NEXT: V_STORE_IDX [[BUFFER_ATOMIC_ADD_F32_VBUFFER_OFFEN_RTN]], [[S_LSHL_B32_1]], 20, implicit $exec :: (store (s32), addrspace 10)
    ;
    ; ALLOC-LABEL: name: tied-operand
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx3 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 [[S_LSHR_B32_]]
    ; ALLOC-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHR_B32_]], 3, implicit-def dead $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_1]]
    ; ALLOC-NEXT: [[V_LOAD_IDX:%[0-9]+]]:vgpr_32 = V_LOAD_IDX $idx3, 5, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT: [[V_LOAD_IDX1:%[0-9]+]]:vgpr_32 = V_LOAD_IDX $idx2, 10, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT: [[BUFFER_ATOMIC_ADD_F32_VBUFFER_OFFEN_RTN:%[0-9]+]]:vgpr_32 = BUFFER_ATOMIC_ADD_F32_VBUFFER_OFFEN_RTN [[V_LOAD_IDX1]], [[V_LOAD_IDX]], undef $sgpr0_sgpr1_sgpr2_sgpr3, undef $sgpr3, 0, 0, implicit $exec
    ; ALLOC-NEXT: [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 54321, [[S_LSHL_B32_]], implicit $exec
    ; ALLOC-NEXT: [[V_MAX_U32_e64_1:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 12345, [[S_LSHL_B32_]], implicit $exec
    ; ALLOC-NEXT: [[BUFFER_ATOMIC_ADD_F32_VBUFFER_OFFEN_RTN1:%[0-9]+]]:vgpr_32 = BUFFER_ATOMIC_ADD_F32_VBUFFER_OFFEN_RTN [[V_MAX_U32_e64_1]], [[V_MAX_U32_e64_]], undef $sgpr0_sgpr1_sgpr2_sgpr3, undef $sgpr3, 0, 0, implicit $exec
    ; ALLOC-NEXT: V_STORE_IDX [[BUFFER_ATOMIC_ADD_F32_VBUFFER_OFFEN_RTN]], $idx1, 20, implicit $exec :: (store (s32), addrspace 10)
    ;
    ; LOWERED-LABEL: name: tied-operand
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr1
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr2
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr3
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr1
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr2
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr1 = S_LSHR_B32 renamable $sgpr0, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx3 = S_SET_GPR_IDX_U32 renamable $sgpr0
    ; LOWERED-NEXT: renamable $sgpr2 = S_LSHL_B32 renamable $sgpr1, 3, implicit-def dead $scc
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr2
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 3
    ; LOWERED-NEXT: $vgpr0 = V_MOV_B32_e32 undef $vgpr5, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 2
    ; LOWERED-NEXT: $vgpr1 = V_MOV_B32_e32 undef $vgpr10, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: renamable $vgpr2 = V_MAX_U32_e64 54321, $sgpr0, implicit $exec
    ; LOWERED-NEXT: renamable $vgpr3 = V_MAX_U32_e64 12345, killed $sgpr0, implicit $exec
    ; LOWERED-NEXT: GLOBAL_WB 24, implicit $exec
    ; LOWERED-NEXT: S_WAIT_STORECNT 0
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 0
    ; LOWERED-NEXT: renamable $vgpr1 = BUFFER_ATOMIC_ADD_F32_VBUFFER_OFFEN_RTN killed renamable $vgpr1, killed renamable $vgpr0, undef $sgpr0_sgpr1_sgpr2_sgpr3, undef $sgpr3, 0, 24, implicit $exec
    ; LOWERED-NEXT: S_WAIT_LOADCNT 0
    ; LOWERED-NEXT: GLOBAL_INV 24, implicit $exec
    ; LOWERED-NEXT: GLOBAL_WB 24, implicit $exec
    ; LOWERED-NEXT: S_WAIT_LOADCNT 0
    ; LOWERED-NEXT: S_WAIT_STORECNT 0
    ; LOWERED-NEXT: dead renamable $vgpr3 = BUFFER_ATOMIC_ADD_F32_VBUFFER_OFFEN_RTN killed renamable $vgpr3, killed renamable $vgpr2, undef $sgpr0_sgpr1_sgpr2_sgpr3, undef $sgpr3, 0, 24, implicit $exec
    ; LOWERED-NEXT: S_WAIT_LOADCNT 0
    ; LOWERED-NEXT: GLOBAL_INV 24, implicit $exec
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 64
    ; LOWERED-NEXT: $vgpr20 = V_MOV_B32_e32 $vgpr1, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:sreg_32_xexec_hi = S_LSHR_B32 %0, 2, implicit-def dead $scc
    %2:sreg_32_xexec_hi = S_LSHL_B32 %1, 3, implicit-def dead $scc
    %3:vgpr_32 = V_LOAD_IDX %0, 5, implicit $exec :: (load (s32), addrspace 10)
    %4:vgpr_32 = V_LOAD_IDX %1, 10, implicit $exec :: (load (s32), addrspace 10)
    %5:vgpr_32 = BUFFER_ATOMIC_ADD_F32_VBUFFER_OFFEN_RTN %4, %3, undef $sgpr0_sgpr1_sgpr2_sgpr3, undef $sgpr3, 0, 0, implicit $exec
    %6:vgpr_32 = V_MAX_U32_e64 54321, %0, implicit $exec
    %7:vgpr_32 = V_MAX_U32_e64 12345, %0, implicit $exec
    %8:vgpr_32 = BUFFER_ATOMIC_ADD_F32_VBUFFER_OFFEN_RTN %7, %6, undef $sgpr0_sgpr1_sgpr2_sgpr3, undef $sgpr3, 0, 0, implicit $exec
    V_STORE_IDX %5:vgpr_32, %2, 20, implicit $exec :: (store (s32), addrspace 10)
...

---
name:            coremi-load-store
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: coremi-load-store
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; GCN-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHR_B32_]], 3, implicit-def dead $scc
    ; GCN-NEXT: [[V_LOAD_IDX:%[0-9]+]]:vgpr_32 = V_LOAD_IDX [[S_LSHR_B32_]], 10, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT: [[DS_READ_B32_gfx9_:%[0-9]+]]:vgpr_32 = DS_READ_B32_gfx9 [[V_LOAD_IDX]], 0, 0, implicit $exec
    ; GCN-NEXT: [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 54321, [[S_LSHL_B32_]], implicit $exec
    ; GCN-NEXT: [[V_MAX_U32_e64_1:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 12345, [[S_LSHL_B32_]], implicit $exec
    ; GCN-NEXT: DS_WRITE_B32_gfx9 [[V_MAX_U32_e64_1]], [[V_MAX_U32_e64_]], 0, 0, implicit $exec
    ; GCN-NEXT: V_STORE_IDX [[DS_READ_B32_gfx9_]], [[S_LSHL_B32_1]], 20, implicit $exec :: (store (s32), addrspace 10)
    ;
    ; ALLOC-LABEL: name: coremi-load-store
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 [[S_LSHR_B32_]]
    ; ALLOC-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHR_B32_]], 3, implicit-def dead $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_1]]
    ; ALLOC-NEXT: [[V_LOAD_IDX:%[0-9]+]]:vgpr_32 = V_LOAD_IDX $idx2, 10, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT: [[DS_READ_B32_gfx9_:%[0-9]+]]:vgpr_32 = DS_READ_B32_gfx9 [[V_LOAD_IDX]], 0, 0, implicit $exec
    ; ALLOC-NEXT: [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 54321, [[S_LSHL_B32_]], implicit $exec
    ; ALLOC-NEXT: [[V_MAX_U32_e64_1:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 12345, [[S_LSHL_B32_]], implicit $exec
    ; ALLOC-NEXT: DS_WRITE_B32_gfx9 [[V_MAX_U32_e64_1]], [[V_MAX_U32_e64_]], 0, 0, implicit $exec
    ; ALLOC-NEXT: V_STORE_IDX [[DS_READ_B32_gfx9_]], $idx1, 20, implicit $exec :: (store (s32), addrspace 10)
    ;
    ; LOWERED-LABEL: name: coremi-load-store
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr1
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr2
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr1
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr2
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr1 = S_LSHR_B32 renamable $sgpr0, 2, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $vgpr1 = V_MAX_U32_e64 54321, $sgpr0, implicit $exec
    ; LOWERED-NEXT: renamable $sgpr2 = S_LSHL_B32 renamable $sgpr1, 3, implicit-def dead $scc
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr2
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 2
    ; LOWERED-NEXT: $vgpr0 = V_MOV_B32_e32 undef $vgpr10, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: renamable $vgpr2 = V_MAX_U32_e64 12345, killed $sgpr0, implicit $exec
    ; LOWERED-NEXT: S_WAIT_STORECNT 0
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 0
    ; LOWERED-NEXT: renamable $vgpr0 = DS_READ_B32_gfx9 killed renamable $vgpr0, 0, 0, implicit $exec
    ; LOWERED-NEXT: S_WAIT_DSCNT 0
    ; LOWERED-NEXT: GLOBAL_INV 24, implicit $exec
    ; LOWERED-NEXT: GLOBAL_WB 24, implicit $exec
    ; LOWERED-NEXT: S_WAIT_LOADCNT 0
    ; LOWERED-NEXT: S_WAIT_STORECNT 0
    ; LOWERED-NEXT: DS_WRITE_B32_gfx9 killed renamable $vgpr2, killed renamable $vgpr1, 0, 0, implicit $exec
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 64
    ; LOWERED-NEXT: $vgpr20 = V_MOV_B32_e32 $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:sreg_32_xexec_hi = S_LSHR_B32 %0, 2, implicit-def dead $scc
    %2:sreg_32_xexec_hi = S_LSHL_B32 %1, 3, implicit-def dead $scc
    %4:vgpr_32 = V_LOAD_IDX %1, 10, implicit $exec :: (load (s32), addrspace 10)
    %5:vgpr_32 = DS_READ_B32_gfx9 %4, 0, 0, implicit $exec
    %6:vgpr_32 = V_MAX_U32_e64 54321, %0, implicit $exec
    %7:vgpr_32 = V_MAX_U32_e64 12345, %0, implicit $exec
    DS_WRITE_B32_gfx9 %7, %6, 0, 0, implicit $exec
    V_STORE_IDX %5:vgpr_32, %2, 20, implicit $exec :: (store (s32), addrspace 10)
...

---
name:            coremi-store-store
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: coremi-store-store
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; GCN-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHR_B32_]], 3, implicit-def dead $scc
    ; GCN-NEXT: [[V_LOAD_IDX:%[0-9]+]]:vgpr_32 = V_LOAD_IDX [[S_LSHL_B32_]], 5, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT: [[V_LOAD_IDX1:%[0-9]+]]:vgpr_32 = V_LOAD_IDX [[S_LSHR_B32_]], 10, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT: [[DS_SUB_RTN_U32_:%[0-9]+]]:vgpr_32 = DS_SUB_RTN_U32 [[V_LOAD_IDX1]], [[V_LOAD_IDX]], 0, 0, implicit $exec, implicit $m0
    ; GCN-NEXT: [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 54321, [[S_LSHL_B32_]], implicit $exec
    ; GCN-NEXT: [[V_MAX_U32_e64_1:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 12345, [[S_LSHL_B32_]], implicit $exec
    ; GCN-NEXT: DS_WRITE_B32_gfx9 [[V_MAX_U32_e64_1]], [[V_MAX_U32_e64_]], 0, 0, implicit $exec
    ; GCN-NEXT: V_STORE_IDX [[DS_SUB_RTN_U32_]], [[S_LSHL_B32_1]], 20, implicit $exec :: (store (s32), addrspace 10)
    ;
    ; ALLOC-LABEL: name: coremi-store-store
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx3 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 [[S_LSHR_B32_]]
    ; ALLOC-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHR_B32_]], 3, implicit-def dead $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_1]]
    ; ALLOC-NEXT: [[V_LOAD_IDX:%[0-9]+]]:vgpr_32 = V_LOAD_IDX $idx3, 5, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT: [[V_LOAD_IDX1:%[0-9]+]]:vgpr_32 = V_LOAD_IDX $idx2, 10, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT: [[DS_SUB_RTN_U32_:%[0-9]+]]:vgpr_32 = DS_SUB_RTN_U32 [[V_LOAD_IDX1]], [[V_LOAD_IDX]], 0, 0, implicit $exec, implicit $m0
    ; ALLOC-NEXT: [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 54321, [[S_LSHL_B32_]], implicit $exec
    ; ALLOC-NEXT: [[V_MAX_U32_e64_1:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 12345, [[S_LSHL_B32_]], implicit $exec
    ; ALLOC-NEXT: DS_WRITE_B32_gfx9 [[V_MAX_U32_e64_1]], [[V_MAX_U32_e64_]], 0, 0, implicit $exec
    ; ALLOC-NEXT: V_STORE_IDX [[DS_SUB_RTN_U32_]], $idx1, 20, implicit $exec :: (store (s32), addrspace 10)
    ;
    ; LOWERED-LABEL: name: coremi-store-store
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr1
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr2
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr1
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr2
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr1 = S_LSHR_B32 renamable $sgpr0, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx3 = S_SET_GPR_IDX_U32 renamable $sgpr0
    ; LOWERED-NEXT: renamable $sgpr2 = S_LSHL_B32 renamable $sgpr1, 3, implicit-def dead $scc
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr2
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 3
    ; LOWERED-NEXT: $vgpr0 = V_MOV_B32_e32 undef $vgpr5, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 2
    ; LOWERED-NEXT: $vgpr1 = V_MOV_B32_e32 undef $vgpr10, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: renamable $vgpr2 = V_MAX_U32_e64 12345, $sgpr0, implicit $exec
    ; LOWERED-NEXT: GLOBAL_WB 24, implicit $exec
    ; LOWERED-NEXT: S_WAIT_STORECNT 0
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 0
    ; LOWERED-NEXT: renamable $vgpr0 = DS_SUB_RTN_U32 killed renamable $vgpr1, killed renamable $vgpr0, 0, 0, implicit $exec, implicit $m0
    ; LOWERED-NEXT: S_WAIT_DSCNT 0
    ; LOWERED-NEXT: GLOBAL_INV 24, implicit $exec
    ; LOWERED-NEXT: renamable $vgpr1 = V_MAX_U32_e64 54321, killed $sgpr0, implicit $exec
    ; LOWERED-NEXT: GLOBAL_WB 24, implicit $exec
    ; LOWERED-NEXT: S_WAIT_LOADCNT 0
    ; LOWERED-NEXT: S_WAIT_STORECNT 0
    ; LOWERED-NEXT: DS_WRITE_B32_gfx9 killed renamable $vgpr2, killed renamable $vgpr1, 0, 0, implicit $exec
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 64
    ; LOWERED-NEXT: $vgpr20 = V_MOV_B32_e32 $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:sreg_32_xexec_hi = S_LSHR_B32 %0, 2, implicit-def dead $scc
    %2:sreg_32_xexec_hi = S_LSHL_B32 %1, 3, implicit-def dead $scc
    %3:vgpr_32 = V_LOAD_IDX %0, 5, implicit $exec :: (load (s32), addrspace 10)
    %4:vgpr_32 = V_LOAD_IDX %1, 10, implicit $exec :: (load (s32), addrspace 10)
    %5:vgpr_32 = DS_SUB_RTN_U32 %4, %3, 0, 0, implicit $exec, implicit $m0
    %6:vgpr_32 = V_MAX_U32_e64 54321, %0, implicit $exec
    %7:vgpr_32 = V_MAX_U32_e64 12345, %0, implicit $exec
    DS_WRITE_B32_gfx9 %7, %6, 0, 0, implicit $exec
    V_STORE_IDX %5:vgpr_32, %2, 20, implicit $exec :: (store (s32), addrspace 10)
...

---
name:            coremi-store-store-trivially-distinct
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: coremi-store-store-trivially-distinct
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; GCN-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHR_B32_]], 3, implicit-def dead $scc
    ; GCN-NEXT: [[V_LOAD_IDX:%[0-9]+]]:vgpr_32 = V_LOAD_IDX [[S_LSHL_B32_]], 5, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT: [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 54321, [[S_LSHL_B32_]], implicit $exec
    ; GCN-NEXT: BUNDLE implicit-def $stg_srca, implicit [[S_LSHR_B32_]], implicit $exec, implicit [[V_MAX_U32_e64_]] {
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHR_B32_]], 10, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   DS_WRITE_B32_gfx9 internal $stg_srca, [[V_MAX_U32_e64_]], 4, 0, implicit $exec :: (store (s32), addrspace 3)
    ; GCN-NEXT: }
    ; GCN-NEXT: BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHR_B32_]], implicit $exec, implicit [[S_LSHL_B32_1]] {
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHR_B32_]], 10, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_dsta = DS_READ_B32_gfx9 internal $stg_srca, 0, 0, implicit $exec :: (load (s32), addrspace 3)
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_1]], 20, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: coremi-store-store-trivially-distinct
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def dead $scc
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 [[S_LSHR_B32_]]
    ; ALLOC-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHR_B32_]], 3, implicit-def dead $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_1]]
    ; ALLOC-NEXT: [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 54321, [[S_LSHL_B32_]], implicit $exec
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srca, implicit $idx2, implicit $exec, implicit [[V_MAX_U32_e64_]] {
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx2, 10, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   DS_WRITE_B32_gfx9 internal $stg_srca, [[V_MAX_U32_e64_]], 4, 0, implicit $exec :: (store (s32), addrspace 3)
    ; ALLOC-NEXT: }
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit $idx2, implicit $exec, implicit $idx1 {
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx2, 10, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta = DS_READ_B32_gfx9 internal $stg_srca, 0, 0, implicit $exec :: (load (s32), addrspace 3)
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 20, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: coremi-store-store-trivially-distinct
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr1
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr1 = S_LSHR_B32 renamable $sgpr0, 2, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $vgpr0 = V_MAX_U32_e64 54321, killed $sgpr0, implicit $exec
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 renamable $sgpr1, 3, implicit-def dead $scc
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 66
    ; LOWERED-NEXT: DS_WRITE_B32_gfx9 undef $vgpr10, killed renamable $vgpr0, 4, 0, <0x{{[0-9a-f]+}}>, implicit $exec :: (store (s32), addrspace 3)
    ; LOWERED-NEXT: undef $vgpr20 = DS_READ_B32_gfx9 undef $vgpr10, 0, 0, <0x{{[0-9a-f]+}}>, implicit $exec :: (load (s32), addrspace 3)
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:sreg_32_xexec_hi = S_LSHR_B32 %0, 2, implicit-def dead $scc
    %2:sreg_32_xexec_hi = S_LSHL_B32 %1, 3, implicit-def dead $scc
    %3:vgpr_32 = V_LOAD_IDX %0, 5, implicit $exec :: (load (s32), addrspace 10)
    %4:vgpr_32 = V_LOAD_IDX %1, 10, implicit $exec :: (load (s32), addrspace 10)
    %5:vgpr_32 = DS_READ_B32_gfx9 %4, 0, 0, implicit $exec :: (load (s32), addrspace 3)
    %6:vgpr_32 = V_MAX_U32_e64 54321, %0, implicit $exec
    DS_WRITE_B32_gfx9 %4, %6, 4, 0, implicit $exec :: (store (s32), addrspace 3)
    V_STORE_IDX %5:vgpr_32, %2, 20, implicit $exec :: (store (s32), addrspace 10)
...

---
name:            same-bb-load-store-no-core
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: same-bb-load-store-no-core
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: BUNDLE implicit-def $stg_dsta, implicit [[S_LSHL_B32_]], implicit $exec {
    ; GCN-NEXT:   $stg_dsta = V_LOAD_IDX [[S_LSHL_B32_]], 0, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_]], 1, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: same-bb-load-store-no-core
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_dsta, implicit $idx1, implicit $exec {
    ; ALLOC-NEXT:   $stg_dsta = V_LOAD_IDX $idx1, 0, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 1, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: same-bb-load-store-no-core
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 65
    ; LOWERED-NEXT: $vgpr1 = V_MOV_B32_e32 undef $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:vgpr_32 = V_LOAD_IDX %0, 0, implicit $exec :: (load (s32), addrspace 10)
    V_STORE_IDX %1:vgpr_32, %0, 1, implicit $exec :: (store (s32), addrspace 10)
...

---
name:            same-bb-wide-no-core
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: same-bb-wide-no-core
    ; GCN: [[S_MOV_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_MOV_B32 48
    ; GCN-NEXT: [[S_MOV_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_MOV_B32 16
    ; GCN-NEXT: [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 12345, [[S_MOV_B32_]], implicit $exec
    ; GCN-NEXT: BUNDLE implicit-def $stg_dsta, implicit [[S_MOV_B32_]], implicit $exec, implicit [[S_MOV_B32_1]] {
    ; GCN-NEXT:   $stg_dsta = V_LOAD_IDX [[S_MOV_B32_]], 8, implicit $exec :: (load (s128), addrspace 10)
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_MOV_B32_1]], 4, implicit $exec :: (store (s128), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: same-bb-wide-no-core
    ; ALLOC: $idx2 = S_SET_GPR_IDX_U32 48
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 16
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_dsta, implicit $idx2, implicit $exec, implicit $idx1 {
    ; ALLOC-NEXT:   $stg_dsta = V_LOAD_IDX $idx2, 8, implicit $exec :: (load (s128), addrspace 10)
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 4, implicit $exec :: (store (s128), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: same-bb-wide-no-core
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 48
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 16
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 66
    ; LOWERED-NEXT: $vgpr4 = V_MOV_B32_e32 undef $vgpr8, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: $vgpr5 = V_MOV_B32_e32 undef $vgpr9, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: $vgpr6 = V_MOV_B32_e32 undef $vgpr10, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: $vgpr7 = V_MOV_B32_e32 undef $vgpr11, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_MOV_B32 48
    %1:vreg_128_align2 = V_LOAD_IDX %0, 8, implicit $exec :: (load (s128), addrspace 10)
    %2:sreg_32_xexec_hi = S_MOV_B32 16
    %3:vgpr_32 = V_MAX_U32_e64 12345, %0, implicit $exec
    V_STORE_IDX %1, %2, 4, implicit $exec :: (store (s128), addrspace 10)
...

---
name:            wide-no-core-regno-wrap
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: wide-no-core-regno-wrap
    ; GCN: [[S_MOV_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_MOV_B32 48
    ; GCN-NEXT: [[S_MOV_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_MOV_B32 16
    ; GCN-NEXT: [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 12345, [[S_MOV_B32_]], implicit $exec
    ; GCN-NEXT: BUNDLE implicit-def $stg_dsta, implicit [[S_MOV_B32_]], implicit $exec, implicit [[S_MOV_B32_1]] {
    ; GCN-NEXT:   $stg_dsta = V_LOAD_IDX [[S_MOV_B32_]], 1022, implicit $exec :: (load (s128), addrspace 10)
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_MOV_B32_1]], 1020, implicit $exec :: (store (s128), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: wide-no-core-regno-wrap
    ; ALLOC: $idx2 = S_SET_GPR_IDX_U32 48
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 16
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_dsta, implicit $idx2, implicit $exec, implicit $idx1 {
    ; ALLOC-NEXT:   $stg_dsta = V_LOAD_IDX $idx2, 1022, implicit $exec :: (load (s128), addrspace 10)
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 1020, implicit $exec :: (store (s128), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: wide-no-core-regno-wrap
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 48
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 16
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 49986
    ; LOWERED-NEXT: $vgpr1020 = V_MOV_B32_e32 undef $vgpr1022, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: $vgpr1021 = V_MOV_B32_e32 undef $vgpr1023, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 49218
    ; LOWERED-NEXT: $vgpr1022 = V_MOV_B32_e32 undef $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: $vgpr1023 = V_MOV_B32_e32 undef $vgpr1, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_MOV_B32 48
    %1:vreg_128_align2 = V_LOAD_IDX %0, 1022, implicit $exec :: (load (s128), addrspace 10)
    %2:sreg_32_xexec_hi = S_MOV_B32 16
    %3:vgpr_32 = V_MAX_U32_e64 12345, %0, implicit $exec
    V_STORE_IDX %1, %2, 1020, implicit $exec :: (store (s128), addrspace 10)
...

---
name:            debug-instr
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: debug-instr
    ; GCN: DBG_VALUE %0:sreg_32, $noreg
    ;
    ; ALLOC-LABEL: name: debug-instr
    ; ALLOC: DBG_VALUE %0:sreg_32, $noreg
    ;
    ; LOWERED-LABEL: name: debug-instr
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    DBG_VALUE %0:sreg_32, $noreg
...

---
name:            no-copy
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: no-copy
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[V_LOAD_IDX:%[0-9]+]]:vgpr_32 = V_LOAD_IDX [[S_LSHL_B32_]], 0, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY [[V_LOAD_IDX]], implicit $exec
    ; GCN-NEXT: V_STORE_IDX [[COPY]], [[S_LSHL_B32_]], 0, implicit $exec :: (store (s32), addrspace 10)
    ;
    ; ALLOC-LABEL: name: no-copy
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: [[V_LOAD_IDX:%[0-9]+]]:vgpr_32 = V_LOAD_IDX $idx1, 0, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT: V_STORE_IDX [[V_LOAD_IDX]], $idx1, 0, implicit $exec :: (store (s32), addrspace 10)
    ;
    ; LOWERED-LABEL: name: no-copy
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 1
    ; LOWERED-NEXT: $vgpr0 = V_MOV_B32_e32 undef $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 64
    ; LOWERED-NEXT: $vgpr0 = V_MOV_B32_e32 $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:vgpr_32 = V_LOAD_IDX %0, 0, implicit $exec :: (load (s32), addrspace 10)
    %2:vgpr_32 = COPY %1, implicit $exec
    V_STORE_IDX %2:vgpr_32, %0, 0, implicit $exec :: (store (s32), addrspace 10)
...

---
name:            no-bundle-subreg-in
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: no-bundle-subreg-in
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[V_LOAD_IDX:%[0-9]+]]:vreg_128_align2 = V_LOAD_IDX [[S_LSHL_B32_]], 10, implicit $exec :: (load (s128), addrspace 10)
    ; GCN-NEXT: BUNDLE implicit-def $stg_dsta, implicit [[V_LOAD_IDX]], implicit $exec, implicit [[S_LSHL_B32_]] {
    ; GCN-NEXT:   $stg_dsta = V_MAX_U32_e64 [[V_LOAD_IDX]].sub0, [[V_LOAD_IDX]].sub1, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_]], 0, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: no-bundle-subreg-in
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: [[V_LOAD_IDX:%[0-9]+]]:vreg_128_align2 = V_LOAD_IDX $idx1, 10, implicit $exec :: (load (s128), addrspace 10)
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_dsta, implicit [[V_LOAD_IDX]], implicit $exec, implicit $idx1 {
    ; ALLOC-NEXT:   $stg_dsta = V_MAX_U32_e64 [[V_LOAD_IDX]].sub0, [[V_LOAD_IDX]].sub1, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 0, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: no-bundle-subreg-in
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr1
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr2
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr3
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 1
    ; LOWERED-NEXT: $vgpr0 = V_MOV_B32_e32 undef $vgpr10, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: $vgpr1 = V_MOV_B32_e32 undef $vgpr11, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: $vgpr2 = V_MOV_B32_e32 undef $vgpr12, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: $vgpr3 = V_MOV_B32_e32 undef $vgpr13, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 64
    ; LOWERED-NEXT: undef $vgpr0 = V_MAX_U32_e64 killed $vgpr0, killed $vgpr1, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:vreg_128_align2 = V_LOAD_IDX %0, 10, implicit $exec :: (load (s128), addrspace 10)
    %2:vgpr_32 = V_MAX_U32_e64 %1.sub0, %1.sub1, implicit $exec
    V_STORE_IDX %2:vgpr_32, %0, 0, implicit $exec :: (store (s32), addrspace 10)
...

---
name:            no-bundle-subreg-out
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: no-bundle-subreg-out
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: BUNDLE implicit-def $stg_srca, implicit-def %2, implicit [[S_LSHL_B32_]], implicit $exec {
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 10, implicit $exec :: (load (s64), addrspace 10)
    ; GCN-NEXT:   [[V_LSHRREV_B64_e64_:%[0-9]+]]:vreg_64_align2 = V_LSHRREV_B64_e64 2, internal $stg_srca, implicit $exec
    ; GCN-NEXT: }
    ; GCN-NEXT: V_STORE_IDX [[V_LSHRREV_B64_e64_]].sub1, [[S_LSHL_B32_]], 0, implicit $exec :: (store (s32), addrspace 10)
    ;
    ; ALLOC-LABEL: name: no-bundle-subreg-out
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srca, implicit-def %2, implicit $idx1, implicit $exec {
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx1, 10, implicit $exec :: (load (s64), addrspace 10)
    ; ALLOC-NEXT:   [[V_LSHRREV_B64_e64_:%[0-9]+]]:vreg_64_align2 = V_LSHRREV_B64_e64 2, internal $stg_srca, implicit $exec
    ; ALLOC-NEXT: }
    ; ALLOC-NEXT: V_STORE_IDX [[V_LSHRREV_B64_e64_]].sub1, $idx1, 0, implicit $exec :: (store (s32), addrspace 10)
    ;
    ; LOWERED-LABEL: name: no-bundle-subreg-out
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr1
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 4
    ; LOWERED-NEXT: renamable $vgpr0_vgpr1 = V_LSHRREV_B64_e64 2, undef $vgpr10_vgpr11, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 64
    ; LOWERED-NEXT: $vgpr0 = V_MOV_B32_e32 $vgpr1, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:vreg_64_align2 = V_LOAD_IDX %0, 10, implicit $exec :: (load (s64), addrspace 10)
    %2:vreg_64_align2 = V_LSHRREV_B64_e64 2, %1, implicit $exec
    V_STORE_IDX %2.sub1, %0, 0, implicit $exec :: (store (s32), addrspace 10)
...

---
name:            idx0-test-private-vgprs
machineFunctionInfo:
  laneSharedVGPRSize: 100
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:


    ; GCN-LABEL: name: idx0-test-private-vgprs
    ; GCN: [[DEF:%[0-9]+]]:sgpr_128 = IMPLICIT_DEF
    ; GCN-NEXT: [[BUFFER_LOAD_DWORD_OFFSET:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFSET [[DEF]], 0, 0, 0, 0, implicit $exec
    ; GCN-NEXT: [[DEF1:%[0-9]+]]:sgpr_128 = IMPLICIT_DEF
    ; GCN-NEXT: [[BUFFER_LOAD_DWORD_OFFSET1:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFSET [[DEF1]], 0, 0, 0, 0, implicit $exec
    ; GCN-NEXT: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 3, implicit-def dead $scc
    ; GCN-NEXT: [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def dead $scc
    ; GCN-NEXT: [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 5, implicit-def dead $scc
    ; GCN-NEXT: [[V_ADD_F32_e32_:%[0-9]+]]:vgpr_32 = V_ADD_F32_e32 [[BUFFER_LOAD_DWORD_OFFSET]], [[BUFFER_LOAD_DWORD_OFFSET1]], implicit $exec, implicit $mode
    ; GCN-NEXT: [[V_MAX_F32_e32_:%[0-9]+]]:vgpr_32 = V_MAX_F32_e32 [[V_ADD_F32_e32_]], [[BUFFER_LOAD_DWORD_OFFSET]], implicit $exec, implicit $mode
    ; GCN-NEXT: [[V_FMAC_F32_e64_:%[0-9]+]]:vgpr_32 = V_FMAC_F32_e64 0, [[BUFFER_LOAD_DWORD_OFFSET1]], 0, [[V_MAX_F32_e32_]], 0, [[V_ADD_F32_e32_]], 0, 0, implicit $exec, implicit $mode
    ; GCN-NEXT: BUNDLE implicit-def $stg_srcc, implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHL_B32_2]], implicit $exec, implicit [[S_LSHL_B32_1]], implicit [[S_LSHL_B32_]], implicit [[S_LSHL_B32_3]] {
    ; GCN-NEXT:   $stg_srcc = V_LOAD_IDX [[S_LSHL_B32_2]], 7, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srcb = V_LOAD_IDX [[S_LSHL_B32_1]], 6, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 5, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_dsta = V_LSHL_ADD_U32_e64 internal $stg_srca, internal $stg_srcb, internal $stg_srcc, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_3]], 8, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: idx0-test-private-vgprs
    ; ALLOC: $idx0 = S_SET_GPR_IDX_U32 0
    ; ALLOC-NEXT: [[COPY:%[0-9]+]]:sreg_32_xm0_xexec = COPY $idx0
    ; ALLOC-NEXT: [[DEF:%[0-9]+]]:sgpr_128 = IMPLICIT_DEF
    ; ALLOC-NEXT: [[BUFFER_LOAD_DWORD_OFFSET:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFSET [[DEF]], 0, 0, 0, 0, implicit $exec
    ; ALLOC-NEXT: [[DEF1:%[0-9]+]]:sgpr_128 = IMPLICIT_DEF
    ; ALLOC-NEXT: [[BUFFER_LOAD_DWORD_OFFSET1:%[0-9]+]]:vgpr_32 = BUFFER_LOAD_DWORD_OFFSET [[DEF1]], 0, 0, 0, 0, implicit $exec
    ; ALLOC-NEXT: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 3, implicit-def dead $scc
    ; ALLOC-NEXT: $idx3 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_1]]
    ; ALLOC-NEXT: [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def dead $scc
    ; ALLOC-NEXT: [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 5, implicit-def dead $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_3]]
    ; ALLOC-NEXT: [[V_ADD_F32_e32_:%[0-9]+]]:vgpr_32 = V_ADD_F32_e32 [[BUFFER_LOAD_DWORD_OFFSET]], [[BUFFER_LOAD_DWORD_OFFSET1]], implicit $exec, implicit $mode
    ; ALLOC-NEXT: [[V_MAX_F32_e32_:%[0-9]+]]:vgpr_32 = V_MAX_F32_e32 [[V_ADD_F32_e32_]], [[BUFFER_LOAD_DWORD_OFFSET]], implicit $exec, implicit $mode
    ; ALLOC-NEXT: [[V_FMAC_F32_e32_:%[0-9]+]]:vgpr_32 = V_FMAC_F32_e32 [[BUFFER_LOAD_DWORD_OFFSET1]], [[V_MAX_F32_e32_]], [[V_ADD_F32_e32_]], implicit $mode, implicit $exec
    ; ALLOC-NEXT: $idx0 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_2]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srcc, implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def $stg_dsta, implicit $idx0, implicit $exec, implicit $idx3, implicit $idx2, implicit $idx1 {
    ; ALLOC-NEXT:   $stg_srcc = V_LOAD_IDX $idx0, 7, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srcb = V_LOAD_IDX $idx3, 6, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx2, 5, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta = V_LSHL_ADD_U32_e64 internal $stg_srca, internal $stg_srcb, internal $stg_srcc, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 8, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ; ALLOC-NEXT: $idx0 = S_SET_GPR_IDX_U32 [[COPY]]
    ;
    ; LOWERED-LABEL: name: idx0-test-private-vgprs
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr1
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr2
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr1
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr2
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr3
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: $sgpr0 = S_GETREG_B32 63532, implicit $mode
    ; LOWERED-NEXT: S_WAIT_STORECNT 0
    ; LOWERED-NEXT: renamable $vgpr0 = BUFFER_LOAD_DWORD_OFFSET undef renamable $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 24, 0, implicit $exec
    ; LOWERED-NEXT: S_WAIT_LOADCNT 0
    ; LOWERED-NEXT: GLOBAL_INV 24, implicit $exec
    ; LOWERED-NEXT: S_WAIT_LOADCNT 0
    ; LOWERED-NEXT: renamable $vgpr1 = BUFFER_LOAD_DWORD_OFFSET undef renamable $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 24, 0, implicit $exec
    ; LOWERED-NEXT: S_WAIT_LOADCNT 0
    ; LOWERED-NEXT: GLOBAL_INV 24, implicit $exec
    ; LOWERED-NEXT: renamable $sgpr1 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr2 = S_LSHL_B32 1, 3, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr3 = S_LSHL_B32 1, 5, implicit-def dead $scc
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    ; LOWERED-NEXT: $idx3 = S_SET_GPR_IDX_U32 killed renamable $sgpr2
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr3
    ; LOWERED-NEXT: renamable $sgpr1 = S_LSHL_B32 1, 4, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $vgpr2 = V_ADD_F32_e32 $vgpr0, $vgpr1, implicit $exec, implicit $mode
    ; LOWERED-NEXT: renamable $vgpr0 = V_MAX_F32_e32 $vgpr2, killed $vgpr0, implicit $exec, implicit $mode
    ; LOWERED-NEXT: dead renamable $vgpr2 = V_FMAC_F32_e32 killed $vgpr1, killed $vgpr0, killed $vgpr2, implicit $mode, implicit $exec
    ; LOWERED-NEXT: $idx0 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 78
    ; LOWERED-NEXT: undef $vgpr8 = V_LSHL_ADD_U32_e64 undef $vgpr5, undef $vgpr6, undef $vgpr7, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: dead $idx0 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    %123:sgpr_128 = IMPLICIT_DEF
    %124:vgpr_32 = BUFFER_LOAD_DWORD_OFFSET %123, 0, 0, 0, 0, implicit $exec
    %125:sgpr_128 = IMPLICIT_DEF
    %126:vgpr_32 = BUFFER_LOAD_DWORD_OFFSET %125, 0, 0, 0, 0, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:sreg_32_xexec_hi = S_LSHL_B32 1, 3, implicit-def dead $scc
    %2:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def dead $scc
    %3:sreg_32_xexec_hi = S_LSHL_B32 1, 5, implicit-def dead $scc
    %4:vgpr_32 = V_LOAD_IDX %0, 5, implicit $exec :: (load (s32), addrspace 10)
    %5:vgpr_32 = V_LOAD_IDX %1, 6, implicit $exec :: (load (s32), addrspace 10)
    %6:vgpr_32 = V_LOAD_IDX %2, 7, implicit $exec :: (load (s32), addrspace 10)
    %12:vgpr_32 = V_ADD_F32_e32 %124, %126, implicit $exec, implicit $mode
    %13:vgpr_32 = V_MAX_F32_e32 %12, %124, implicit $exec, implicit $mode
    %14:vgpr_32 = V_FMAC_F32_e64 0, %126, 0, %13, 0, %12, 0, 0, implicit $exec, implicit $mode
    %7:vgpr_32 = V_LSHL_ADD_U32_e64 %4, %5, %6, implicit $exec
    V_STORE_IDX %7:vgpr_32, %3, 8, implicit $exec :: (store (s32), addrspace 10)
...

---
name:            idx0-test-idx0-bundle-late
machineFunctionInfo:
  laneSharedVGPRSize: 100
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |
  bb.0:
    ; GCN-LABEL: name: idx0-test-idx0-bundle-late
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 3, implicit-def dead $scc
    ; GCN-NEXT: [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def dead $scc
    ; GCN-NEXT: [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 5, implicit-def dead $scc
    ; GCN-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_MOV_B32 0
    ; GCN-NEXT: BUNDLE implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def %10, implicit [[S_MOV_B32_]], implicit $exec, implicit $mode {
    ; GCN-NEXT:   $stg_srcb = V_LOAD_IDX [[S_MOV_B32_]], 2, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_MOV_B32_]], 2, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   [[V_ADD_F32_e32_:%[0-9]+]]:vgpr_32 = V_ADD_F32_e32 internal $stg_srca, internal $stg_srcb, implicit $exec, implicit $mode
    ; GCN-NEXT: }
    ; GCN-NEXT: BUNDLE implicit-def $stg_srcc, implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHL_B32_2]], implicit $exec, implicit [[S_LSHL_B32_1]], implicit [[S_LSHL_B32_]], implicit [[S_LSHL_B32_3]] {
    ; GCN-NEXT:   $stg_srcc = V_LOAD_IDX [[S_LSHL_B32_2]], 15, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srcb = V_LOAD_IDX [[S_LSHL_B32_1]], 10, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 5, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_dsta = V_LSHL_ADD_U32_e64 internal $stg_srca, internal $stg_srcb, internal $stg_srcc, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_3]], 20, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: idx0-test-idx0-bundle-late
    ; ALLOC: $idx0 = S_SET_GPR_IDX_U32 0
    ; ALLOC-NEXT: [[COPY:%[0-9]+]]:sreg_32_xm0_xexec = COPY $idx0
    ; ALLOC-NEXT: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 3, implicit-def dead $scc
    ; ALLOC-NEXT: $idx3 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_1]]
    ; ALLOC-NEXT: [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def dead $scc
    ; ALLOC-NEXT: [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 5, implicit-def dead $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 0
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def %10, implicit $idx1, implicit $exec, implicit $mode {
    ; ALLOC-NEXT:   $stg_srcb = V_LOAD_IDX $idx1, 2, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx1, 2, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   [[V_ADD_F32_e32_:%[0-9]+]]:vgpr_32 = V_ADD_F32_e32 internal $stg_srca, internal $stg_srcb, implicit $exec, implicit $mode
    ; ALLOC-NEXT: }
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_3]]
    ; ALLOC-NEXT: $idx0 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_2]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srcc, implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def $stg_dsta, implicit $idx0, implicit $exec, implicit $idx3, implicit $idx2, implicit $idx1 {
    ; ALLOC-NEXT:   $stg_srcc = V_LOAD_IDX $idx0, 15, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srcb = V_LOAD_IDX $idx3, 10, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx2, 5, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta = V_LSHL_ADD_U32_e64 internal $stg_srca, internal $stg_srcb, internal $stg_srcc, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 20, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ; ALLOC-NEXT: $idx0 = S_SET_GPR_IDX_U32 [[COPY]]
    ;
    ; LOWERED-LABEL: name: idx0-test-idx0-bundle-late
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr1
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr2
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr1 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr2 = S_LSHL_B32 1, 3, implicit-def dead $scc
    ; LOWERED-NEXT: $sgpr0 = S_GETREG_B32 63532, implicit $mode
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    ; LOWERED-NEXT: $idx3 = S_SET_GPR_IDX_U32 killed renamable $sgpr2
    ; LOWERED-NEXT: renamable $sgpr1 = S_LSHL_B32 1, 4, implicit-def dead $scc
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 0
    ; LOWERED-NEXT: renamable $sgpr2 = S_LSHL_B32 1, 5, implicit-def dead $scc
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 5
    ; LOWERED-NEXT: renamable $vgpr0 = V_ADD_F32_e32 undef $vgpr2, undef $vgpr2, <0x{{[0-9a-f]+}}>, implicit $exec, implicit $mode
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr2
    ; LOWERED-NEXT: $idx0 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 78
    ; LOWERED-NEXT: undef $vgpr20 = V_LSHL_ADD_U32_e64 undef $vgpr5, undef $vgpr10, undef $vgpr15, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: dead $idx0 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:sreg_32_xexec_hi = S_LSHL_B32 1, 3, implicit-def dead $scc
    %2:sreg_32_xexec_hi = S_LSHL_B32 1, 4, implicit-def dead $scc
    %3:sreg_32_xexec_hi = S_LSHL_B32 1, 5, implicit-def dead $scc
    %4:vgpr_32 = V_LOAD_IDX %0, 5, implicit $exec :: (load (s32), addrspace 10)
    %5:vgpr_32 = V_LOAD_IDX %1, 10, implicit $exec :: (load (s32), addrspace 10)
    %6:vgpr_32 = V_LOAD_IDX %2, 15, implicit $exec :: (load (s32), addrspace 10)
    %15:sreg_32_xexec_hi = S_MOV_B32 0
    %16:vgpr_32 =  V_LOAD_IDX %15, 2, implicit $exec :: (load (s32), addrspace 10)
    %17:vgpr_32 =  V_LOAD_IDX %15, 2, implicit $exec :: (load (s32), addrspace 10)
    %18:vgpr_32 = V_ADD_F32_e32 %16, %17, implicit $exec, implicit $mode
    %7:vgpr_32 = V_LSHL_ADD_U32_e64 %4, %5, %6, implicit $exec
    V_STORE_IDX %7:vgpr_32, %3, 20, implicit $exec :: (store (s32), addrspace 10)
...

---
name:            redirect-with-idx0-bundle
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: redirect-with-idx0-bundle
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def $scc
    ; GCN-NEXT: [[S_LSHR_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 3, implicit-def $scc
    ; GCN-NEXT: [[S_LSHR_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 4, implicit-def dead $scc
    ; GCN-NEXT: [[V_LOAD_IDX:%[0-9]+]]:vgpr_32 = V_LOAD_IDX [[S_LSHR_B32_]], 10, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT: BUNDLE implicit-def $stg_srcc, implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHR_B32_1]], implicit $exec, implicit [[S_LSHR_B32_]], implicit [[S_LSHL_B32_]], implicit [[S_LSHR_B32_2]] {
    ; GCN-NEXT:   $stg_srcc = V_LOAD_IDX [[S_LSHR_B32_1]], 15, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srcb = V_LOAD_IDX [[S_LSHR_B32_]], 10, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 5, implicit $exec :: (load (s32), addrspace 10)
    ; GCN-NEXT:   $stg_dsta = V_LSHL_ADD_U32_e64 internal $stg_srca, internal $stg_srcb, internal $stg_srcc, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHR_B32_2]], 0, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ; GCN-NEXT: BUNDLE implicit-def $stg_dsta, implicit [[V_LOAD_IDX]], implicit $exec, implicit [[S_LSHR_B32_1]] {
    ; GCN-NEXT:   $stg_dsta = V_LSHL_ADD_U32_e64 0, [[V_LOAD_IDX]], [[V_LOAD_IDX]], implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHR_B32_1]], 0, implicit $exec :: (store (s32), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: redirect-with-idx0-bundle
    ; ALLOC: $idx0 = S_SET_GPR_IDX_U32 0
    ; ALLOC-NEXT: [[COPY:%[0-9]+]]:sreg_32_xm0_xexec = COPY $idx0
    ; ALLOC-NEXT: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx3 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 2, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHR_B32_]]
    ; ALLOC-NEXT: [[S_LSHR_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 3, implicit-def $scc
    ; ALLOC-NEXT: [[S_LSHR_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 [[S_LSHL_B32_]], 4, implicit-def dead $scc
    ; ALLOC-NEXT: $idx2 = S_SET_GPR_IDX_U32 [[S_LSHR_B32_2]]
    ; ALLOC-NEXT: [[V_LOAD_IDX:%[0-9]+]]:vgpr_32 = V_LOAD_IDX $idx1, 10, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT: $idx0 = S_SET_GPR_IDX_U32 [[S_LSHR_B32_1]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srcc, implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def $stg_dsta, implicit $idx0, implicit $exec, implicit $idx1, implicit $idx3, implicit $idx2 {
    ; ALLOC-NEXT:   $stg_srcc = V_LOAD_IDX $idx0, 15, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srcb = V_LOAD_IDX $idx1, 10, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx3, 5, implicit $exec :: (load (s32), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta = V_LSHL_ADD_U32_e64 internal $stg_srca, internal $stg_srcb, internal $stg_srcc, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx2, 0, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ; ALLOC-NEXT: $idx0 = S_SET_GPR_IDX_U32 [[COPY]]
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHR_B32_1]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_dsta, implicit [[V_LOAD_IDX]], implicit $exec, implicit $idx1 {
    ; ALLOC-NEXT:   $stg_dsta = V_LSHL_ADD_U32_e64 0, [[V_LOAD_IDX]], [[V_LOAD_IDX]], implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 0, implicit $exec :: (store (s32), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: redirect-with-idx0-bundle
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr1
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr2
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $sgpr1 = S_GETREG_B32 63532, implicit $mode
    ; LOWERED-NEXT: renamable $sgpr2 = S_LSHR_B32 renamable $sgpr0, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx3 = S_SET_GPR_IDX_U32 renamable $sgpr0
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr2
    ; LOWERED-NEXT: renamable $sgpr2 = S_LSHR_B32 renamable $sgpr0, 4, implicit-def dead $scc
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHR_B32 killed renamable $sgpr0, 3, implicit-def dead $scc
    ; LOWERED-NEXT: $idx2 = S_SET_GPR_IDX_U32 killed renamable $sgpr2
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 1
    ; LOWERED-NEXT: $vgpr0 = V_MOV_B32_e32 undef $vgpr10, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: $idx0 = S_SET_GPR_IDX_U32 renamable $sgpr0
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 135
    ; LOWERED-NEXT: undef $vgpr0 = V_LSHL_ADD_U32_e64 undef $vgpr5, undef $vgpr10, undef $vgpr15, <0x{{[0-9a-f]+}}>, implicit $exec
    ; LOWERED-NEXT: dead $idx0 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 64
    ; LOWERED-NEXT: undef $vgpr0 = V_LSHL_ADD_U32_e64 0, killed $vgpr0, $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:sreg_32_xexec_hi = S_LSHR_B32 %0, 2, implicit-def $scc
    %2:sreg_32_xexec_hi = S_LSHR_B32 %0, 3, implicit-def $scc
    %3:sreg_32_xexec_hi = S_LSHR_B32 %0, 4, implicit-def dead $scc
    %5:vgpr_32 = V_LOAD_IDX %0, 5, implicit $exec :: (load (s32), addrspace 10)
    %6:vgpr_32 = V_LOAD_IDX %1, 10, implicit $exec :: (load (s32), addrspace 10)
    %7:vgpr_32 = V_LOAD_IDX %2, 15, implicit $exec :: (load (s32), addrspace 10)
    %10:vgpr_32 = V_LSHL_ADD_U32_e64 %5, %6, %7, implicit $exec
    V_STORE_IDX %10:vgpr_32, %3, 0, implicit $exec :: (store (s32), addrspace 10)
    %11:vgpr_32 = V_LSHL_ADD_U32_e64 0, %6, %6, implicit $exec
    V_STORE_IDX %11:vgpr_32, %2, 0, implicit $exec :: (store (s32), addrspace 10)
...

---
name:            enable-dst-operand-class
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |

  bb.0:
    ; GCN-LABEL: name: enable-dst-operand-class
    ; GCN: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; GCN-NEXT: BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHL_B32_]], implicit $exec {
    ; GCN-NEXT:   $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 10, implicit $exec :: (load (s64), addrspace 10)
    ; GCN-NEXT:   $stg_dsta = V_LSHRREV_B64_e64 2, internal $stg_srca, implicit $exec
    ; GCN-NEXT:   V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_]], 0, implicit $exec :: (store (s64), addrspace 10)
    ; GCN-NEXT: }
    ;
    ; ALLOC-LABEL: name: enable-dst-operand-class
    ; ALLOC: [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    ; ALLOC-NEXT: $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
    ; ALLOC-NEXT: BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit $idx1, implicit $exec {
    ; ALLOC-NEXT:   $stg_srca = V_LOAD_IDX $idx1, 10, implicit $exec :: (load (s64), addrspace 10)
    ; ALLOC-NEXT:   $stg_dsta = V_LSHRREV_B64_e64 2, internal $stg_srca, implicit $exec
    ; ALLOC-NEXT:   V_STORE_IDX internal $stg_dsta, $idx1, 0, implicit $exec :: (store (s64), addrspace 10)
    ; ALLOC-NEXT: }
    ;
    ; LOWERED-LABEL: name: enable-dst-operand-class
    ; LOWERED: frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; LOWERED-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr0
    ; LOWERED-NEXT: S_WAIT_LOADCNT_DSCNT 0
    ; LOWERED-NEXT: S_WAIT_EXPCNT 0
    ; LOWERED-NEXT: S_WAIT_SAMPLECNT 0
    ; LOWERED-NEXT: S_WAIT_BVHCNT 0
    ; LOWERED-NEXT: S_WAIT_KMCNT 0
    ; LOWERED-NEXT: renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
    ; LOWERED-NEXT: $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
    ; LOWERED-NEXT: S_SET_VGPR_FRAMES 68
    ; LOWERED-NEXT: undef $vgpr0_vgpr1 = V_LSHRREV_B64_e64 2, undef $vgpr10_vgpr11, <0x{{[0-9a-f]+}}>, implicit $exec
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:vreg_64_align2 = V_LOAD_IDX %0, 10, implicit $exec :: (load (s64), addrspace 10)
    %2:vreg_64_align2 = V_LSHRREV_B64_e64 2, %1, implicit $exec
    V_STORE_IDX %2, %0, 0, implicit $exec :: (store (s64), addrspace 10)
...
---
name:            multi-bb-load-simple
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |
  ; GCN-LABEL: name: multi-bb-load-simple
  ; GCN: bb.0:
  ; GCN-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT:   [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
  ; GCN-NEXT:   S_CMP_EQ_U32 [[S_LSHL_B32_]], 0, implicit-def $scc
  ; GCN-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GCN-NEXT:   S_BRANCH %bb.1
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.1:
  ; GCN-NEXT:   successors: %bb.2(0x80000000)
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def %2, implicit [[S_LSHL_B32_]], implicit $exec {
  ; GCN-NEXT:     $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 0, implicit $exec :: (load (s32), addrspace 10)
  ; GCN-NEXT:     [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 12345, internal $stg_srca, implicit $exec
  ; GCN-NEXT:   }
  ; GCN-NEXT:   S_BRANCH %bb.2
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.2:
  ; GCN-NEXT:   S_ENDPGM 0
  ;
  ; ALLOC-LABEL: name: multi-bb-load-simple
  ; ALLOC: bb.0:
  ; ALLOC-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT:   [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
  ; ALLOC-NEXT:   S_CMP_EQ_U32 [[S_LSHL_B32_]], 0, implicit-def $scc
  ; ALLOC-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; ALLOC-NEXT:   S_BRANCH %bb.1
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT: bb.1:
  ; ALLOC-NEXT:   successors: %bb.2(0x80000000)
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT:   $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
  ; ALLOC-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def %2, implicit $idx1, implicit $exec {
  ; ALLOC-NEXT:     $stg_srca = V_LOAD_IDX $idx1, 0, implicit $exec :: (load (s32), addrspace 10)
  ; ALLOC-NEXT:     [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 12345, internal $stg_srca, implicit $exec
  ; ALLOC-NEXT:   }
  ; ALLOC-NEXT:   S_BRANCH %bb.2
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT: bb.2:
  ; ALLOC-NEXT:   S_ENDPGM 0
  ;
  ; LOWERED-LABEL: name: multi-bb-load-simple
  ; LOWERED: bb.0:
  ; LOWERED-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $vgpr0
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $sgpr0
  ; LOWERED-NEXT:   S_WAIT_LOADCNT_DSCNT 0
  ; LOWERED-NEXT:   S_WAIT_EXPCNT 0
  ; LOWERED-NEXT:   S_WAIT_SAMPLECNT 0
  ; LOWERED-NEXT:   S_WAIT_BVHCNT 0
  ; LOWERED-NEXT:   S_WAIT_KMCNT 0
  ; LOWERED-NEXT:   renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
  ; LOWERED-NEXT:   S_CMP_EQ_U32 renamable $sgpr0, 0, implicit-def $scc
  ; LOWERED-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit killed $scc
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT: bb.1:
  ; LOWERED-NEXT:   successors: %bb.2(0x80000000)
  ; LOWERED-NEXT:   liveins: $sgpr0
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT:   $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
  ; LOWERED-NEXT:   S_SET_VGPR_FRAMES 4
  ; LOWERED-NEXT:   renamable $vgpr0 = V_MAX_U32_e64 12345, undef $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT: bb.2:
  ; LOWERED-NEXT:   S_ENDPGM 0


  bb.0:
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:vgpr_32 = V_LOAD_IDX %0, 0, implicit $exec :: (load (s32), addrspace 10)
    S_CMP_EQ_U32 %0:sreg_32_xexec_hi, 0, implicit-def $scc
    S_CBRANCH_SCC1 %bb.2, implicit $scc
    S_BRANCH %bb.1

  bb.1:
    %2:vgpr_32 = V_MAX_U32_e64 12345, %1, implicit $exec
    S_BRANCH %bb.2

  bb.2:
    S_ENDPGM 0

...
---
name:            multi-bb-store-simple
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |
  ; GCN-LABEL: name: multi-bb-store-simple
  ; GCN: bb.0:
  ; GCN-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT:   [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
  ; GCN-NEXT:   S_CMP_EQ_U32 [[S_LSHL_B32_]], 0, implicit-def $scc
  ; GCN-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GCN-NEXT:   S_BRANCH %bb.1
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.1:
  ; GCN-NEXT:   successors: %bb.2(0x80000000)
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT:   [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_]], 2, implicit-def $scc
  ; GCN-NEXT:   BUNDLE implicit-def $stg_dsta, implicit [[S_LSHL_B32_]], implicit $exec, implicit [[S_LSHL_B32_1]] {
  ; GCN-NEXT:     $stg_dsta = V_MAX_U32_e64 12345, [[S_LSHL_B32_]], implicit $exec
  ; GCN-NEXT:     V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_1]], 0, implicit $exec :: (store (s32), addrspace 10)
  ; GCN-NEXT:   }
  ; GCN-NEXT:   S_BRANCH %bb.2
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.2:
  ; GCN-NEXT:   S_ENDPGM 0
  ;
  ; ALLOC-LABEL: name: multi-bb-store-simple
  ; ALLOC: bb.0:
  ; ALLOC-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT:   [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
  ; ALLOC-NEXT:   S_CMP_EQ_U32 [[S_LSHL_B32_]], 0, implicit-def $scc
  ; ALLOC-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; ALLOC-NEXT:   S_BRANCH %bb.1
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT: bb.1:
  ; ALLOC-NEXT:   successors: %bb.2(0x80000000)
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT:   [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_]], 2, implicit-def $scc
  ; ALLOC-NEXT:   $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_1]]
  ; ALLOC-NEXT:   BUNDLE implicit-def $stg_dsta, implicit [[S_LSHL_B32_]], implicit $exec, implicit $idx1 {
  ; ALLOC-NEXT:     $stg_dsta = V_MAX_U32_e64 12345, [[S_LSHL_B32_]], implicit $exec
  ; ALLOC-NEXT:     V_STORE_IDX internal $stg_dsta, $idx1, 0, implicit $exec :: (store (s32), addrspace 10)
  ; ALLOC-NEXT:   }
  ; ALLOC-NEXT:   S_BRANCH %bb.2
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT: bb.2:
  ; ALLOC-NEXT:   S_ENDPGM 0
  ;
  ; LOWERED-LABEL: name: multi-bb-store-simple
  ; LOWERED: bb.0:
  ; LOWERED-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $sgpr0
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $sgpr1
  ; LOWERED-NEXT:   S_WAIT_LOADCNT_DSCNT 0
  ; LOWERED-NEXT:   S_WAIT_EXPCNT 0
  ; LOWERED-NEXT:   S_WAIT_SAMPLECNT 0
  ; LOWERED-NEXT:   S_WAIT_BVHCNT 0
  ; LOWERED-NEXT:   S_WAIT_KMCNT 0
  ; LOWERED-NEXT:   renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
  ; LOWERED-NEXT:   S_CMP_EQ_U32 renamable $sgpr0, 0, implicit-def $scc
  ; LOWERED-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit killed $scc
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT: bb.1:
  ; LOWERED-NEXT:   successors: %bb.2(0x80000000)
  ; LOWERED-NEXT:   liveins: $sgpr0
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT:   renamable $sgpr1 = S_LSHL_B32 renamable $sgpr0, 2, implicit-def dead $scc
  ; LOWERED-NEXT:   $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
  ; LOWERED-NEXT:   S_SET_VGPR_FRAMES 64
  ; LOWERED-NEXT:   undef $vgpr0 = V_MAX_U32_e64 12345, killed $sgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT: bb.2:
  ; LOWERED-NEXT:   S_ENDPGM 0

  bb.0:
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:vgpr_32 = V_MAX_U32_e64 12345, %0:sreg_32_xexec_hi, implicit $exec
    S_CMP_EQ_U32 %0:sreg_32_xexec_hi, 0, implicit-def $scc
    S_CBRANCH_SCC1 %bb.2, implicit $scc
    S_BRANCH %bb.1

  bb.1:
    %2:sreg_32_xexec_hi = S_LSHL_B32 %0:sreg_32_xexec_hi, 2, implicit-def $scc
    V_STORE_IDX %1, %2:sreg_32_xexec_hi, 0, implicit $exec :: (store (s32), addrspace 10)
    S_BRANCH %bb.2

  bb.2:
    S_ENDPGM 0

...
---
name:            multi-bb-load-store-simple
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |
  ; GCN-LABEL: name: multi-bb-load-store-simple
  ; GCN: bb.0:
  ; GCN-NEXT:   successors: %bb.1(0x40000000), %bb.3(0x40000000)
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT:   [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
  ; GCN-NEXT:   S_CMP_EQ_U32 [[S_LSHL_B32_]], 0, implicit-def $scc
  ; GCN-NEXT:   S_CBRANCH_SCC1 %bb.1, implicit $scc
  ; GCN-NEXT:   S_BRANCH %bb.3
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.1:
  ; GCN-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT:   [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_]], 5, implicit-def $scc
  ; GCN-NEXT:   S_CMP_GT_U32 [[S_LSHL_B32_1]], 0, implicit-def $scc
  ; GCN-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GCN-NEXT:   S_BRANCH %bb.3
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.2:
  ; GCN-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHL_B32_]], implicit $exec {
  ; GCN-NEXT:     $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 0, implicit $exec :: (load (s32), addrspace 10)
  ; GCN-NEXT:     $stg_dsta = V_MAX_U32_e64 12345, internal $stg_srca, implicit $exec
  ; GCN-NEXT:     V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_]], 0, implicit $exec :: (store (s32), addrspace 10)
  ; GCN-NEXT:   }
  ; GCN-NEXT:   S_ENDPGM 0
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.3:
  ; GCN-NEXT:   S_ENDPGM 0
  ;
  ; ALLOC-LABEL: name: multi-bb-load-store-simple
  ; ALLOC: bb.0:
  ; ALLOC-NEXT:   successors: %bb.1(0x40000000), %bb.3(0x40000000)
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT:   [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
  ; ALLOC-NEXT:   S_CMP_EQ_U32 [[S_LSHL_B32_]], 0, implicit-def $scc
  ; ALLOC-NEXT:   S_CBRANCH_SCC1 %bb.1, implicit $scc
  ; ALLOC-NEXT:   S_BRANCH %bb.3
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT: bb.1:
  ; ALLOC-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT:   [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_]], 5, implicit-def $scc
  ; ALLOC-NEXT:   S_CMP_GT_U32 [[S_LSHL_B32_1]], 0, implicit-def $scc
  ; ALLOC-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; ALLOC-NEXT:   S_BRANCH %bb.3
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT: bb.2:
  ; ALLOC-NEXT:   $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
  ; ALLOC-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit $idx1, implicit $exec {
  ; ALLOC-NEXT:     $stg_srca = V_LOAD_IDX $idx1, 0, implicit $exec :: (load (s32), addrspace 10)
  ; ALLOC-NEXT:     $stg_dsta = V_MAX_U32_e64 12345, internal $stg_srca, implicit $exec
  ; ALLOC-NEXT:     V_STORE_IDX internal $stg_dsta, $idx1, 0, implicit $exec :: (store (s32), addrspace 10)
  ; ALLOC-NEXT:   }
  ; ALLOC-NEXT:   S_ENDPGM 0
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT: bb.3:
  ; ALLOC-NEXT:   S_ENDPGM 0
  ;
  ; LOWERED-LABEL: name: multi-bb-load-store-simple
  ; LOWERED: bb.0:
  ; LOWERED-NEXT:   successors: %bb.1(0x40000000), %bb.3(0x40000000)
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $sgpr0
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $sgpr1
  ; LOWERED-NEXT:   S_WAIT_LOADCNT_DSCNT 0
  ; LOWERED-NEXT:   S_WAIT_EXPCNT 0
  ; LOWERED-NEXT:   S_WAIT_SAMPLECNT 0
  ; LOWERED-NEXT:   S_WAIT_BVHCNT 0
  ; LOWERED-NEXT:   S_WAIT_KMCNT 0
  ; LOWERED-NEXT:   renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
  ; LOWERED-NEXT:   S_CMP_EQ_U32 renamable $sgpr0, 0, implicit-def $scc
  ; LOWERED-NEXT:   S_CBRANCH_SCC0 %bb.3, implicit killed $scc
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT: bb.1:
  ; LOWERED-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; LOWERED-NEXT:   liveins: $sgpr0
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT:   renamable $sgpr1 = S_LSHL_B32 renamable $sgpr0, 5, implicit-def dead $scc
  ; LOWERED-NEXT:   S_CMP_GT_U32 killed renamable $sgpr1, 0, implicit-def $scc
  ; LOWERED-NEXT:   S_CBRANCH_SCC0 %bb.3, implicit killed $scc
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT: bb.2:
  ; LOWERED-NEXT:   successors: %bb.3(0x80000000)
  ; LOWERED-NEXT:   liveins: $sgpr0
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT:   $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
  ; LOWERED-NEXT:   S_SET_VGPR_FRAMES 68
  ; LOWERED-NEXT:   undef $vgpr0 = V_MAX_U32_e64 12345, undef $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT: bb.3:
  ; LOWERED-NEXT:   S_ENDPGM 0

  bb.0:
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:vgpr_32 = V_LOAD_IDX %0:sreg_32_xexec_hi, 0, implicit $exec :: (load (s32), addrspace 10)
    S_CMP_EQ_U32 %0:sreg_32_xexec_hi, 0, implicit-def $scc
    S_CBRANCH_SCC1 %bb.1, implicit $scc
    S_BRANCH %bb.3

  bb.1:
    %2:vgpr_32 = V_MAX_U32_e64 12345, %1, implicit $exec
    %3:sreg_32_xexec_hi = S_LSHL_B32 %0, 5, implicit-def $scc
    S_CMP_GT_U32 %3:sreg_32_xexec_hi, 0, implicit-def $scc
    S_CBRANCH_SCC1 %bb.2, implicit $scc
    S_BRANCH %bb.3

  bb.2:
    V_STORE_IDX %2, %0:sreg_32_xexec_hi, 0, implicit $exec :: (store (s32), addrspace 10)
    S_ENDPGM 0

  bb.3:
    S_ENDPGM 0
...
# TODO Following test case could need updating after implementing defs with more than one use
---
name:            multi-bb-branched-stores
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |
  ; GCN-LABEL: name: multi-bb-branched-stores
  ; GCN: bb.0:
  ; GCN-NEXT:   successors: %bb.1(0x40000000), %bb.3(0x40000000)
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT:   [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
  ; GCN-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def %2, implicit [[S_LSHL_B32_]], implicit $exec {
  ; GCN-NEXT:     $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 0, implicit $exec :: (load (s32), addrspace 10)
  ; GCN-NEXT:     [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 12345, internal $stg_srca, implicit $exec
  ; GCN-NEXT:   }
  ; GCN-NEXT:   S_CMP_EQ_U32 [[S_LSHL_B32_]], 0, implicit-def $scc
  ; GCN-NEXT:   S_CBRANCH_SCC1 %bb.1, implicit $scc
  ; GCN-NEXT:   S_BRANCH %bb.3
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.1:
  ; GCN-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT:   [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_]], 1, implicit-def $scc
  ; GCN-NEXT:   V_STORE_IDX [[V_MAX_U32_e64_]], [[S_LSHL_B32_1]], 0, implicit $exec :: (store (s32), addrspace 10)
  ; GCN-NEXT:   S_CMP_GT_U32 [[S_LSHL_B32_1]], 0, implicit-def $scc
  ; GCN-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GCN-NEXT:   S_BRANCH %bb.3
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.2:
  ; GCN-NEXT:   successors: %bb.3(0x80000000)
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT:   [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_]], 2, implicit-def $scc
  ; GCN-NEXT:   V_STORE_IDX [[V_MAX_U32_e64_]], [[S_LSHL_B32_2]], 0, implicit $exec :: (store (s32), addrspace 10)
  ; GCN-NEXT:   S_BRANCH %bb.3
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.3:
  ; GCN-NEXT:   [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_]], 3, implicit-def $scc
  ; GCN-NEXT:   V_STORE_IDX [[V_MAX_U32_e64_]], [[S_LSHL_B32_3]], 0, implicit $exec :: (store (s32), addrspace 10)
  ; GCN-NEXT:   S_ENDPGM 0
  ;
  ; ALLOC-LABEL: name: multi-bb-branched-stores
  ; ALLOC: bb.0:
  ; ALLOC-NEXT:   successors: %bb.1(0x40000000), %bb.3(0x40000000)
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT:   [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
  ; ALLOC-NEXT:   $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
  ; ALLOC-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def %2, implicit $idx1, implicit $exec {
  ; ALLOC-NEXT:     $stg_srca = V_LOAD_IDX $idx1, 0, implicit $exec :: (load (s32), addrspace 10)
  ; ALLOC-NEXT:     [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 12345, internal $stg_srca, implicit $exec
  ; ALLOC-NEXT:   }
  ; ALLOC-NEXT:   S_CMP_EQ_U32 [[S_LSHL_B32_]], 0, implicit-def $scc
  ; ALLOC-NEXT:   S_CBRANCH_SCC1 %bb.1, implicit $scc
  ; ALLOC-NEXT:   S_BRANCH %bb.3
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT: bb.1:
  ; ALLOC-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT:   [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_]], 1, implicit-def $scc
  ; ALLOC-NEXT:   $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_1]]
  ; ALLOC-NEXT:   V_STORE_IDX [[V_MAX_U32_e64_]], $idx1, 0, implicit $exec :: (store (s32), addrspace 10)
  ; ALLOC-NEXT:   S_CMP_GT_U32 [[S_LSHL_B32_1]], 0, implicit-def $scc
  ; ALLOC-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; ALLOC-NEXT:   S_BRANCH %bb.3
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT: bb.2:
  ; ALLOC-NEXT:   successors: %bb.3(0x80000000)
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT:   [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_]], 2, implicit-def $scc
  ; ALLOC-NEXT:   $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_2]]
  ; ALLOC-NEXT:   V_STORE_IDX [[V_MAX_U32_e64_]], $idx1, 0, implicit $exec :: (store (s32), addrspace 10)
  ; ALLOC-NEXT:   S_BRANCH %bb.3
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT: bb.3:
  ; ALLOC-NEXT:   [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_]], 3, implicit-def $scc
  ; ALLOC-NEXT:   $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_3]]
  ; ALLOC-NEXT:   V_STORE_IDX [[V_MAX_U32_e64_]], $idx1, 0, implicit $exec :: (store (s32), addrspace 10)
  ; ALLOC-NEXT:   S_ENDPGM 0
  ;
  ; LOWERED-LABEL: name: multi-bb-branched-stores
  ; LOWERED: bb.0:
  ; LOWERED-NEXT:   successors: %bb.1(0x40000000), %bb.3(0x40000000)
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $vgpr0
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $sgpr0
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $sgpr1
  ; LOWERED-NEXT:   S_WAIT_LOADCNT_DSCNT 0
  ; LOWERED-NEXT:   S_WAIT_EXPCNT 0
  ; LOWERED-NEXT:   S_WAIT_SAMPLECNT 0
  ; LOWERED-NEXT:   S_WAIT_BVHCNT 0
  ; LOWERED-NEXT:   S_WAIT_KMCNT 0
  ; LOWERED-NEXT:   renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
  ; LOWERED-NEXT:   $idx1 = S_SET_GPR_IDX_U32 renamable $sgpr0
  ; LOWERED-NEXT:   S_CMP_EQ_U32 renamable $sgpr0, 0, implicit-def $scc
  ; LOWERED-NEXT:   S_SET_VGPR_FRAMES 4
  ; LOWERED-NEXT:   renamable $vgpr0 = V_MAX_U32_e64 12345, undef $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
  ; LOWERED-NEXT:   S_SET_VGPR_FRAMES 0
  ; LOWERED-NEXT:   S_CBRANCH_SCC0 %bb.3, implicit killed $scc
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT: bb.1:
  ; LOWERED-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; LOWERED-NEXT:   liveins: $sgpr0, $vgpr0
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT:   renamable $sgpr1 = S_LSHL_B32 renamable $sgpr0, 1, implicit-def dead $scc
  ; LOWERED-NEXT:   $idx1 = S_SET_GPR_IDX_U32 renamable $sgpr1
  ; LOWERED-NEXT:   S_CMP_GT_U32 killed renamable $sgpr1, 0, implicit-def $scc
  ; LOWERED-NEXT:   S_SET_VGPR_FRAMES 64
  ; LOWERED-NEXT:   $vgpr0 = V_MOV_B32_e32 $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
  ; LOWERED-NEXT:   S_SET_VGPR_FRAMES 0
  ; LOWERED-NEXT:   S_CBRANCH_SCC0 %bb.3, implicit killed $scc
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT: bb.2:
  ; LOWERED-NEXT:   successors: %bb.3(0x80000000)
  ; LOWERED-NEXT:   liveins: $sgpr0, $vgpr0
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT:   renamable $sgpr1 = S_LSHL_B32 renamable $sgpr0, 2, implicit-def dead $scc
  ; LOWERED-NEXT:   $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
  ; LOWERED-NEXT:   S_SET_VGPR_FRAMES 64
  ; LOWERED-NEXT:   $vgpr0 = V_MOV_B32_e32 $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT: bb.3:
  ; LOWERED-NEXT:   liveins: $sgpr0, $vgpr0
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT:   renamable $sgpr0 = S_LSHL_B32 killed renamable $sgpr0, 3, implicit-def dead $scc
  ; LOWERED-NEXT:   $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
  ; LOWERED-NEXT:   S_SET_VGPR_FRAMES 64
  ; LOWERED-NEXT:   $vgpr0 = V_MOV_B32_e32 $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
  ; LOWERED-NEXT:   S_ENDPGM 0

  bb.0:
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:vgpr_32 = V_LOAD_IDX %0:sreg_32_xexec_hi, 0, implicit $exec :: (load (s32), addrspace 10)
    %2:vgpr_32 = V_MAX_U32_e64 12345, %1, implicit $exec
    S_CMP_EQ_U32 %0:sreg_32_xexec_hi, 0, implicit-def $scc
    S_CBRANCH_SCC1 %bb.1, implicit $scc
    S_BRANCH %bb.3

  bb.1:
    %3:sreg_32_xexec_hi = S_LSHL_B32 %0, 1, implicit-def $scc
    V_STORE_IDX %2, %3:sreg_32_xexec_hi, 0, implicit $exec :: (store (s32), addrspace 10)
    S_CMP_GT_U32 %3:sreg_32_xexec_hi, 0, implicit-def $scc
    S_CBRANCH_SCC1 %bb.2, implicit $scc
    S_BRANCH %bb.3

  bb.2:
    %4:sreg_32_xexec_hi = S_LSHL_B32 %0, 2, implicit-def $scc
    V_STORE_IDX %2, %4:sreg_32_xexec_hi, 0, implicit $exec :: (store (s32), addrspace 10)
    S_BRANCH %bb.3

  bb.3:
    %5:sreg_32_xexec_hi = S_LSHL_B32 %0, 3, implicit-def $scc
    V_STORE_IDX %2, %5:sreg_32_xexec_hi, 0, implicit $exec :: (store (s32), addrspace 10)
    S_ENDPGM 0

...
---
name:            multi-bb-branched-loads
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |
  ; GCN-LABEL: name: multi-bb-branched-loads
  ; GCN: bb.0:
  ; GCN-NEXT:   successors: %bb.1(0x80000000)
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT:   [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
  ; GCN-NEXT:   S_BRANCH %bb.1
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.1:
  ; GCN-NEXT:   successors: %bb.2(0x80000000)
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT:   [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_]], 2, implicit-def $scc
  ; GCN-NEXT:   S_BRANCH %bb.2
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.2:
  ; GCN-NEXT:   successors: %bb.3(0x80000000)
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT:   [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_1]], 2, implicit-def $scc
  ; GCN-NEXT:   S_BRANCH %bb.3
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.3:
  ; GCN-NEXT:   BUNDLE implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def %6, implicit [[S_LSHL_B32_1]], implicit $exec {
  ; GCN-NEXT:     $stg_srcb = V_LOAD_IDX [[S_LSHL_B32_1]], 0, implicit $exec :: (load (s32), addrspace 10)
  ; GCN-NEXT:     $stg_srca = V_LOAD_IDX [[S_LSHL_B32_1]], 1, implicit $exec :: (load (s32), addrspace 10)
  ; GCN-NEXT:     [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 internal $stg_srca, internal $stg_srcb, implicit $exec
  ; GCN-NEXT:   }
  ; GCN-NEXT:   [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_2]], 1, implicit-def $scc
  ; GCN-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHL_B32_]], implicit $exec, implicit [[V_MAX_U32_e64_]], implicit [[S_LSHL_B32_3]] {
  ; GCN-NEXT:     $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 0, implicit $exec :: (load (s32), addrspace 10)
  ; GCN-NEXT:     $stg_dsta = V_ADD_U32_e64 internal $stg_srca, [[V_MAX_U32_e64_]], 0, implicit $exec
  ; GCN-NEXT:     V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_3]], 0, implicit $exec :: (store (s32), addrspace 10)
  ; GCN-NEXT:   }
  ; GCN-NEXT:   S_ENDPGM 0
  ;
  ; ALLOC-LABEL: name: multi-bb-branched-loads
  ; ALLOC: bb.0:
  ; ALLOC-NEXT:   successors: %bb.1(0x80000000)
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT:   [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
  ; ALLOC-NEXT:   S_BRANCH %bb.1
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT: bb.1:
  ; ALLOC-NEXT:   successors: %bb.2(0x80000000)
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT:   [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_]], 2, implicit-def $scc
  ; ALLOC-NEXT:   S_BRANCH %bb.2
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT: bb.2:
  ; ALLOC-NEXT:   successors: %bb.3(0x80000000)
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT:   [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_1]], 2, implicit-def $scc
  ; ALLOC-NEXT:   S_BRANCH %bb.3
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT: bb.3:
  ; ALLOC-NEXT:   $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_1]]
  ; ALLOC-NEXT:   $idx2 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
  ; ALLOC-NEXT:   BUNDLE implicit-def $stg_srcb, implicit-def $stg_srca, implicit-def %6, implicit $idx1, implicit $exec {
  ; ALLOC-NEXT:     $stg_srcb = V_LOAD_IDX $idx1, 0, implicit $exec :: (load (s32), addrspace 10)
  ; ALLOC-NEXT:     $stg_srca = V_LOAD_IDX $idx1, 1, implicit $exec :: (load (s32), addrspace 10)
  ; ALLOC-NEXT:     [[V_MAX_U32_e64_:%[0-9]+]]:vgpr_32 = V_MAX_U32_e64 internal $stg_srca, internal $stg_srcb, implicit $exec
  ; ALLOC-NEXT:   }
  ; ALLOC-NEXT:   [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_2]], 1, implicit-def $scc
  ; ALLOC-NEXT:   $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_3]]
  ; ALLOC-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit $idx2, implicit $exec, implicit [[V_MAX_U32_e64_]], implicit $idx1 {
  ; ALLOC-NEXT:     $stg_srca = V_LOAD_IDX $idx2, 0, implicit $exec :: (load (s32), addrspace 10)
  ; ALLOC-NEXT:     $stg_dsta = V_ADD_U32_e64 internal $stg_srca, [[V_MAX_U32_e64_]], 0, implicit $exec
  ; ALLOC-NEXT:     V_STORE_IDX internal $stg_dsta, $idx1, 0, implicit $exec :: (store (s32), addrspace 10)
  ; ALLOC-NEXT:   }
  ; ALLOC-NEXT:   S_ENDPGM 0
  ;
  ; LOWERED-LABEL: name: multi-bb-branched-loads
  ; LOWERED: bb.0:
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $vgpr0
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $sgpr0
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $sgpr1
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $sgpr2
  ; LOWERED-NEXT:   S_WAIT_LOADCNT_DSCNT 0
  ; LOWERED-NEXT:   S_WAIT_EXPCNT 0
  ; LOWERED-NEXT:   S_WAIT_SAMPLECNT 0
  ; LOWERED-NEXT:   S_WAIT_BVHCNT 0
  ; LOWERED-NEXT:   S_WAIT_KMCNT 0
  ; LOWERED-NEXT:   renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
  ; LOWERED-NEXT:   renamable $sgpr1 = S_LSHL_B32 renamable $sgpr0, 2, implicit-def dead $scc
  ; LOWERED-NEXT:   $idx1 = S_SET_GPR_IDX_U32 renamable $sgpr1
  ; LOWERED-NEXT:   $idx2 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
  ; LOWERED-NEXT:   S_SET_VGPR_FRAMES 5
  ; LOWERED-NEXT:   renamable $vgpr0 = V_MAX_U32_e64 undef $vgpr1, undef $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
  ; LOWERED-NEXT:   renamable $sgpr2 = S_LSHL_B32 killed renamable $sgpr1, 2, implicit-def dead $scc
  ; LOWERED-NEXT:   renamable $sgpr0 = S_LSHL_B32 killed renamable $sgpr2, 1, implicit-def dead $scc
  ; LOWERED-NEXT:   $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
  ; LOWERED-NEXT:   S_SET_VGPR_FRAMES 66
  ; LOWERED-NEXT:   undef $vgpr0 = V_ADD_U32_e64 undef $vgpr0, killed $vgpr0, 0, <0x{{[0-9a-f]+}}>, implicit $exec
  ; LOWERED-NEXT:   S_ENDPGM 0

  bb.0:
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:vgpr_32 = V_LOAD_IDX %0:sreg_32_xexec_hi, 0, implicit $exec :: (load (s32), addrspace 10)
    S_BRANCH %bb.1

  bb.1:
    %2:sreg_32_xexec_hi = S_LSHL_B32 %0:sreg_32_xexec_hi, 2, implicit-def $scc
    %3:vgpr_32 = V_LOAD_IDX %2:sreg_32_xexec_hi, 0, implicit $exec :: (load (s32), addrspace 10)
    S_BRANCH %bb.2

  bb.2:
    %4:sreg_32_xexec_hi = S_LSHL_B32 %2:sreg_32_xexec_hi, 2, implicit-def $scc
    %5:vgpr_32 = V_LOAD_IDX %2:sreg_32_xexec_hi, 1, implicit $exec :: (load (s32), addrspace 10)
    S_BRANCH %bb.3

  bb.3:
    %6:vgpr_32 = V_MAX_U32_e64 %5, %3, implicit $exec
    %7:vgpr_32 = V_ADD_U32_e64 %1, %6, 0, implicit $exec
    %8:sreg_32_xexec_hi = S_LSHL_B32 %4, 1, implicit-def $scc
    V_STORE_IDX %7, %8, 0, implicit $exec :: (store (s32), addrspace 10)
    S_ENDPGM 0

...
---
name:            multi-bb-convolve-phi-nodes
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |
  ; GCN-LABEL: name: multi-bb-convolve-phi-nodes
  ; GCN: bb.0:
  ; GCN-NEXT:   successors: %bb.1(0x80000000)
  ; GCN-NEXT:   liveins: $sgpr4, $idx0
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT:   [[S_LSHL_B32_:%[0-9]+]]:sreg_32 = S_LSHL_B32 $sgpr4, 4, implicit-def $scc
  ; GCN-NEXT:   S_BRANCH %bb.1
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.1:
  ; GCN-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT:   [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
  ; GCN-NEXT:   [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_1]], 4, implicit-def $scc
  ; GCN-NEXT:   [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_2]], 6, implicit-def $scc
  ; GCN-NEXT:   [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 7, 1, implicit-def $scc
  ; GCN-NEXT:   [[V_LOAD_IDX:%[0-9]+]]:vreg_96_align2 = V_LOAD_IDX [[S_LSHL_B32_3]], 0, implicit $exec, implicit $flat_scr :: (dereferenceable load (s96), align 4, addrspace 10)
  ; GCN-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; GCN-NEXT:   [[REG_SEQUENCE:%[0-9]+]]:sgpr_128 = REG_SEQUENCE [[S_MOV_B32_]], %subreg.sub0, [[S_MOV_B32_]], %subreg.sub1, [[S_MOV_B32_]], %subreg.sub2, [[S_MOV_B32_]], %subreg.sub3
  ; GCN-NEXT:   [[COPY:%[0-9]+]]:vreg_128_align2 = COPY [[REG_SEQUENCE]]
  ; GCN-NEXT:   S_CMP_EQ_U32 [[S_LSHL_B32_]], 0, implicit-def $scc
  ; GCN-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GCN-NEXT:   S_BRANCH %bb.3
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.2:
  ; GCN-NEXT:   successors: %bb.3(0x80000000)
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT:   [[S_LSHL_B32_4:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
  ; GCN-NEXT:   [[V_LOAD_IDX1:%[0-9]+]]:vreg_96_align2 = V_LOAD_IDX [[S_LSHL_B32_4]], 0, implicit $exec, implicit $flat_scr :: (dereferenceable load (s96), align 4, addrspace 10)
  ; GCN-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; GCN-NEXT:   [[REG_SEQUENCE1:%[0-9]+]]:sgpr_128 = REG_SEQUENCE [[S_MOV_B32_1]], %subreg.sub0, [[S_MOV_B32_1]], %subreg.sub1, [[S_MOV_B32_1]], %subreg.sub2, [[S_MOV_B32_1]], %subreg.sub3
  ; GCN-NEXT:   [[COPY1:%[0-9]+]]:vreg_128_align2 = COPY [[REG_SEQUENCE1]]
  ; GCN-NEXT:   S_BRANCH %bb.3
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.3:
  ; GCN-NEXT:   [[PHI:%[0-9]+]]:sreg_32_xexec_hi = PHI [[S_LSHL_B32_4]], %bb.2, [[S_LSHL_B32_2]], %bb.1
  ; GCN-NEXT:   [[PHI1:%[0-9]+]]:vreg_128_align2 = PHI [[COPY]], %bb.1, [[COPY1]], %bb.2
  ; GCN-NEXT:   [[PHI2:%[0-9]+]]:vreg_96_align2 = PHI [[V_LOAD_IDX]], %bb.1, [[V_LOAD_IDX1]], %bb.2
  ; GCN-NEXT:   [[S_LSHL_B32_5:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 killed [[PHI]], 3, implicit-def $scc
  ; GCN-NEXT:   BUNDLE implicit-def dead $stg_srcc, implicit-def dead $stg_srcb, implicit-def dead $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHR_B32_]], implicit $exec, implicit $flat_scr, implicit [[S_LSHL_B32_2]], implicit [[S_LSHL_B32_1]], implicit [[PHI1]], implicit [[PHI2]], implicit [[S_LSHL_B32_5]] {
  ; GCN-NEXT:     $stg_srcc = V_LOAD_IDX [[S_LSHR_B32_]], 288, implicit $exec, implicit $flat_scr :: (dereferenceable load (s96), align 4, addrspace 10)
  ; GCN-NEXT:     $stg_srcb = V_LOAD_IDX [[S_LSHL_B32_2]], 0, implicit $exec, implicit $flat_scr :: (dereferenceable load (s96), align 4, addrspace 10)
  ; GCN-NEXT:     $stg_srca = V_LOAD_IDX [[S_LSHL_B32_1]], 0, implicit $exec, implicit $flat_scr :: (dereferenceable load (s288), align 4, addrspace 10)
  ; GCN-NEXT:     $stg_dsta = contract V_CONVOLVE_F16_FP8_FP8_3x3_4x4 [[PHI1]], internal killed $stg_srca, internal killed $stg_srcb, [[PHI2]], internal killed $stg_srcc, 8, -1, 0, 0, implicit $exec
  ; GCN-NEXT:     V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_5]], 0, implicit $exec :: (store (s32), addrspace 10)
  ; GCN-NEXT:   }
  ; GCN-NEXT:   S_ENDPGM 0
  ;
  ; ALLOC-LABEL: name: multi-bb-convolve-phi-nodes
  ; ALLOC: bb.0:
  ; ALLOC-NEXT:   successors: %bb.1(0x80000000)
  ; ALLOC-NEXT:   liveins: $sgpr4, $idx0
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT:   $idx0 = S_SET_GPR_IDX_U32 0
  ; ALLOC-NEXT:   [[COPY:%[0-9]+]]:sreg_32_xm0_xexec = COPY $idx0
  ; ALLOC-NEXT:   [[S_LSHL_B32_:%[0-9]+]]:sreg_32 = S_LSHL_B32 $sgpr4, 4, implicit-def $scc
  ; ALLOC-NEXT:   S_BRANCH %bb.1
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT: bb.1:
  ; ALLOC-NEXT:   successors: %bb.2(0x40000000), %bb.3(0x40000000)
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT:   [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
  ; ALLOC-NEXT:   [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_1]], 4, implicit-def $scc
  ; ALLOC-NEXT:   [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_2]], 6, implicit-def $scc
  ; ALLOC-NEXT:   $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_3]]
  ; ALLOC-NEXT:   [[S_LSHR_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHR_B32 7, 1, implicit-def $scc
  ; ALLOC-NEXT:   [[V_LOAD_IDX:%[0-9]+]]:vreg_96_align2 = V_LOAD_IDX $idx1, 0, implicit $exec, implicit $flat_scr :: (dereferenceable load (s96), align 4, addrspace 10)
  ; ALLOC-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 0
  ; ALLOC-NEXT:   [[REG_SEQUENCE:%[0-9]+]]:sgpr_128 = REG_SEQUENCE [[S_MOV_B32_]], %subreg.sub0, [[S_MOV_B32_]], %subreg.sub1, [[S_MOV_B32_]], %subreg.sub2, [[S_MOV_B32_]], %subreg.sub3
  ; ALLOC-NEXT:   [[COPY1:%[0-9]+]]:vreg_128_align2 = COPY [[REG_SEQUENCE]]
  ; ALLOC-NEXT:   S_CMP_EQ_U32 [[S_LSHL_B32_]], 0, implicit-def $scc
  ; ALLOC-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; ALLOC-NEXT:   S_BRANCH %bb.3
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT: bb.2:
  ; ALLOC-NEXT:   successors: %bb.3(0x80000000)
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT:   [[S_LSHL_B32_4:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
  ; ALLOC-NEXT:   $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_4]]
  ; ALLOC-NEXT:   [[V_LOAD_IDX1:%[0-9]+]]:vreg_96_align2 = V_LOAD_IDX $idx1, 0, implicit $exec, implicit $flat_scr :: (dereferenceable load (s96), align 4, addrspace 10)
  ; ALLOC-NEXT:   [[COPY2:%[0-9]+]]:vreg_128_align2 = COPY [[REG_SEQUENCE]]
  ; ALLOC-NEXT:   S_BRANCH %bb.3
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT: bb.3:
  ; ALLOC-NEXT:   [[PHI:%[0-9]+]]:sreg_32_xexec_hi = PHI [[S_LSHL_B32_4]], %bb.2, [[S_LSHL_B32_2]], %bb.1
  ; ALLOC-NEXT:   [[PHI1:%[0-9]+]]:vreg_128_align2 = PHI [[COPY1]], %bb.1, [[COPY2]], %bb.2
  ; ALLOC-NEXT:   [[PHI2:%[0-9]+]]:vreg_96_align2 = PHI [[V_LOAD_IDX]], %bb.1, [[V_LOAD_IDX1]], %bb.2
  ; ALLOC-NEXT:   $idx3 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_2]]
  ; ALLOC-NEXT:   $idx2 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_1]]
  ; ALLOC-NEXT:   [[S_LSHL_B32_5:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 killed [[PHI]], 3, implicit-def $scc
  ; ALLOC-NEXT:   $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_5]]
  ; ALLOC-NEXT:   $idx0 = S_SET_GPR_IDX_U32 [[S_LSHR_B32_]]
  ; ALLOC-NEXT:   BUNDLE implicit-def dead $stg_srcc, implicit-def dead $stg_srcb, implicit-def dead $stg_srca, implicit-def $stg_dsta, implicit $idx0, implicit $exec, implicit $flat_scr, implicit $idx3, implicit $idx2, implicit [[PHI1]], implicit [[PHI2]], implicit $idx1 {
  ; ALLOC-NEXT:     $stg_srcc = V_LOAD_IDX $idx0, 288, implicit $exec, implicit $flat_scr :: (dereferenceable load (s96), align 4, addrspace 10)
  ; ALLOC-NEXT:     $stg_srcb = V_LOAD_IDX $idx3, 0, implicit $exec, implicit $flat_scr :: (dereferenceable load (s96), align 4, addrspace 10)
  ; ALLOC-NEXT:     $stg_srca = V_LOAD_IDX $idx2, 0, implicit $exec, implicit $flat_scr :: (dereferenceable load (s288), align 4, addrspace 10)
  ; ALLOC-NEXT:     $stg_dsta = contract V_CONVOLVE_F16_FP8_FP8_3x3_4x4 [[PHI1]], internal killed $stg_srca, internal killed $stg_srcb, [[PHI2]], internal killed $stg_srcc, 8, -1, 0, 0, implicit $exec
  ; ALLOC-NEXT:     V_STORE_IDX internal $stg_dsta, $idx1, 0, implicit $exec :: (store (s32), addrspace 10)
  ; ALLOC-NEXT:   }
  ; ALLOC-NEXT:   $idx0 = S_SET_GPR_IDX_U32 [[COPY]]
  ; ALLOC-NEXT:   S_ENDPGM 0
  ;
  ; LOWERED-LABEL: name: multi-bb-convolve-phi-nodes
  ; LOWERED: bb.0:
  ; LOWERED-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; LOWERED-NEXT:   liveins: $idx0, $sgpr4
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $vgpr0
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $vgpr1
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $vgpr2
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $vgpr3
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $vgpr4
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $vgpr5
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $vgpr6
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $sgpr0
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $sgpr1
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $sgpr2
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $sgpr3
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $sgpr4
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $sgpr5
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $sgpr6
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $sgpr7
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $sgpr8
  ; LOWERED-NEXT:   S_WAIT_LOADCNT_DSCNT 0
  ; LOWERED-NEXT:   S_WAIT_EXPCNT 0
  ; LOWERED-NEXT:   S_WAIT_SAMPLECNT 0
  ; LOWERED-NEXT:   S_WAIT_BVHCNT 0
  ; LOWERED-NEXT:   S_WAIT_KMCNT 0
  ; LOWERED-NEXT:   renamable $sgpr8 = S_LSHL_B32 killed $sgpr4, 4, implicit-def dead $scc
  ; LOWERED-NEXT:   renamable $sgpr4 = S_LSHL_B32 1, 2, implicit-def dead $scc
  ; LOWERED-NEXT:   renamable $sgpr0 = S_MOV_B32 0
  ; LOWERED-NEXT:   renamable $sgpr6 = S_LSHL_B32 renamable $sgpr4, 4, implicit-def dead $scc
  ; LOWERED-NEXT:   $sgpr5 = S_GETREG_B32 63532, implicit $mode
  ; LOWERED-NEXT:   renamable $sgpr3 = S_LSHL_B32 renamable $sgpr6, 6, implicit-def dead $scc
  ; LOWERED-NEXT:   $sgpr1 = S_MOV_B32 $sgpr0
  ; LOWERED-NEXT:   $sgpr2 = S_MOV_B32 $sgpr0
  ; LOWERED-NEXT:   $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr3
  ; LOWERED-NEXT:   $sgpr3 = S_MOV_B32 $sgpr0
  ; LOWERED-NEXT:   $vgpr0, $vgpr1 = V_DUAL_MOV_B32_e32_X_MOV_B32_e32_gfx13 $sgpr0, $sgpr1, implicit $exec, implicit $exec, implicit-def $vgpr0_vgpr1_vgpr2_vgpr3, implicit $sgpr0_sgpr1_sgpr2_sgpr3, implicit $exec, implicit $sgpr0_sgpr1_sgpr2_sgpr3
  ; LOWERED-NEXT:   S_SET_VGPR_FRAMES 1
  ; LOWERED-NEXT:   $vgpr4 = V_MOV_B32_e32 undef $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
  ; LOWERED-NEXT:   $vgpr5 = V_MOV_B32_e32 undef $vgpr1, <0x{{[0-9a-f]+}}>, implicit $exec
  ; LOWERED-NEXT:   $vgpr6 = V_MOV_B32_e32 undef $vgpr2, <0x{{[0-9a-f]+}}>, implicit $exec
  ; LOWERED-NEXT:   $vgpr2, $vgpr3 = V_DUAL_MOV_B32_e32_X_MOV_B32_e32_gfx13 $sgpr2, $sgpr3, implicit $exec, implicit $exec, implicit $sgpr0_sgpr1_sgpr2_sgpr3, implicit $exec, implicit $sgpr0_sgpr1_sgpr2_sgpr3, implicit $exec
  ; LOWERED-NEXT:   renamable $sgpr7 = S_LSHR_B32 7, 1, implicit-def dead $scc
  ; LOWERED-NEXT:   S_CMP_EQ_U32 killed renamable $sgpr8, 0, implicit-def $scc
  ; LOWERED-NEXT:   $sgpr8 = S_MOV_B32 $sgpr6
  ; LOWERED-NEXT:   S_SET_VGPR_FRAMES 0
  ; LOWERED-NEXT:   S_CBRANCH_SCC0 %bb.2, implicit killed $scc
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT: bb.1:
  ; LOWERED-NEXT:   successors: %bb.2(0x80000000)
  ; LOWERED-NEXT:   liveins: $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr0_sgpr1_sgpr2_sgpr3:0x00000000000000FF
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT:   renamable $sgpr8 = S_LSHL_B32 1, 2, implicit-def dead $scc
  ; LOWERED-NEXT:   $vgpr0, $vgpr1 = V_DUAL_MOV_B32_e32_X_MOV_B32_e32_gfx13 $sgpr0, $sgpr1, implicit $exec, implicit $exec, implicit-def $vgpr0_vgpr1_vgpr2_vgpr3, implicit $sgpr0_sgpr1_sgpr2_sgpr3, implicit $exec, implicit $sgpr0_sgpr1_sgpr2_sgpr3
  ; LOWERED-NEXT:   $idx1 = S_SET_GPR_IDX_U32 renamable $sgpr8
  ; LOWERED-NEXT:   $vgpr2, $vgpr3 = V_DUAL_MOV_B32_e32_X_MOV_B32_e32_gfx13 $sgpr2, killed $sgpr3, implicit $exec, implicit $exec, implicit $sgpr0_sgpr1_sgpr2_sgpr3, implicit $exec, implicit $sgpr0_sgpr1_sgpr2_sgpr3, implicit $exec
  ; LOWERED-NEXT:   S_SET_VGPR_FRAMES 1
  ; LOWERED-NEXT:   $vgpr4 = V_MOV_B32_e32 undef $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
  ; LOWERED-NEXT:   $vgpr5 = V_MOV_B32_e32 undef $vgpr1, <0x{{[0-9a-f]+}}>, implicit $exec
  ; LOWERED-NEXT:   $vgpr6 = V_MOV_B32_e32 undef $vgpr2, <0x{{[0-9a-f]+}}>, implicit $exec
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT: bb.2:
  ; LOWERED-NEXT:   liveins: $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $vgpr4_vgpr5_vgpr6, $vgpr0_vgpr1_vgpr2_vgpr3
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT:   renamable $sgpr0 = S_LSHL_B32 killed renamable $sgpr8, 3, implicit-def dead $scc
  ; LOWERED-NEXT:   $idx3 = S_SET_GPR_IDX_U32 killed renamable $sgpr6
  ; LOWERED-NEXT:   $idx2 = S_SET_GPR_IDX_U32 killed renamable $sgpr4
  ; LOWERED-NEXT:   $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
  ; LOWERED-NEXT:   $idx0 = S_SET_GPR_IDX_U32 killed renamable $sgpr7
  ; LOWERED-NEXT:   undef $vgpr0_vgpr1_vgpr2_vgpr3 = contract V_CONVOLVE_F16_FP8_FP8_3x3_4x4 killed $vgpr0_vgpr1_vgpr2_vgpr3, killed undef $vgpr0_vgpr1_vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8, killed undef $vgpr0_vgpr1_vgpr2, killed $vgpr4_vgpr5_vgpr6, killed undef $vgpr288_vgpr289_vgpr290, 8, -1, 12801, 0, <0x{{[0-9a-f]+}}>, implicit $exec
  ; LOWERED-NEXT:   dead $idx0 = S_SET_GPR_IDX_U32 killed renamable $sgpr5
  ; LOWERED-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1(0x80000000); %bb.1(100.00%)
    liveins: $sgpr4, $idx0
    %0:sreg_32 = S_LSHL_B32 $sgpr4, 4, implicit-def $scc
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.2(0x40000000), %bb.3(0x40000000); %bb.2(50.00%), %bb.3(50.00%)

    %1:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %2:sreg_32_xexec_hi = S_LSHL_B32 %1:sreg_32_xexec_hi, 4, implicit-def $scc
    %3:sreg_32_xexec_hi = S_LSHL_B32 %2:sreg_32_xexec_hi, 6, implicit-def $scc
    %4:sreg_32_xexec_hi = S_LSHR_B32 7, 1, implicit-def $scc
    %5:vreg_288_align2 = V_LOAD_IDX %1:sreg_32_xexec_hi, 0, implicit $exec, implicit $flat_scr :: (dereferenceable load (s288), align 4, addrspace 10)
    %6:vreg_96_align2 = V_LOAD_IDX %2:sreg_32_xexec_hi, 0, implicit $exec, implicit $flat_scr :: (dereferenceable load (s96), align 4, addrspace 10)
    %7:vreg_96_align2 = V_LOAD_IDX %3:sreg_32_xexec_hi, 0, implicit $exec, implicit $flat_scr :: (dereferenceable load (s96), align 4, addrspace 10)
    %8:vreg_96_align2 = V_LOAD_IDX %4:sreg_32_xexec_hi, 288, implicit $exec, implicit $flat_scr :: (dereferenceable load (s96), align 4, addrspace 10)
    %9:sreg_32 = S_MOV_B32 0
    %10:sgpr_128 = REG_SEQUENCE %9:sreg_32, %subreg.sub0, %9:sreg_32, %subreg.sub1, %9:sreg_32, %subreg.sub2, %9:sreg_32, %subreg.sub3
    %11:vreg_128_align2 = COPY %10:sgpr_128
    S_CMP_EQ_U32 %0:sreg_32, 0, implicit-def $scc
    S_CBRANCH_SCC1 %bb.2, implicit $scc
    S_BRANCH %bb.3

  bb.2:
    successors: %bb.3(0x80000000); %bb.3(100.00%)

    %12:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %13:vreg_96_align2 = V_LOAD_IDX %12:sreg_32_xexec_hi, 0, implicit $exec, implicit $flat_scr :: (dereferenceable load (s96), align 4, addrspace 10)
    %14:sreg_32 = S_MOV_B32 0
    %15:sgpr_128 = REG_SEQUENCE %14:sreg_32, %subreg.sub0, %14:sreg_32, %subreg.sub1, %14:sreg_32, %subreg.sub2, %14:sreg_32, %subreg.sub3
    %16:vreg_128_align2 = COPY %15:sgpr_128
    S_BRANCH %bb.3

  bb.3:

    %17:sreg_32_xexec_hi = PHI %12:sreg_32_xexec_hi, %bb.2, %2:sreg_32_xexec_hi, %bb.1
    %18:vreg_128_align2 = PHI %11:vreg_128_align2, %bb.1, %16:vreg_128_align2, %bb.2
    %19:vreg_96_align2 = PHI %7:vreg_96_align2, %bb.1, %13:vreg_96_align2, %bb.2
    %20:vreg_128_align2 = contract V_CONVOLVE_F16_FP8_FP8_3x3_4x4 %18:vreg_128_align2, killed %5:vreg_288_align2, killed %6:vreg_96_align2, %19:vreg_96_align2, killed %8:vreg_96_align2, 8, -1, 0, 0, implicit $exec
    %21:sreg_32_xexec_hi = S_LSHL_B32 killed %17:sreg_32_xexec_hi, 3, implicit-def $scc
    V_STORE_IDX %20:vreg_128_align2, %21:sreg_32_xexec_hi, 0, implicit $exec :: (store (s32), addrspace 10)
    S_ENDPGM 0

...
---
name:            multi-bb-simple-move-to-store
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |
  ; GCN-LABEL: name: multi-bb-simple-move-to-store
  ; GCN: bb.0:
  ; GCN-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT:   [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
  ; GCN-NEXT:   S_CMP_EQ_U32 [[S_LSHL_B32_]], 0, implicit-def $scc
  ; GCN-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; GCN-NEXT:   S_BRANCH %bb.1
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.1:
  ; GCN-NEXT:   successors: %bb.2(0x80000000)
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT:   [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_]], 2, implicit-def $scc
  ; GCN-NEXT:   [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_1]], 1, implicit-def $scc
  ; GCN-NEXT:   BUNDLE implicit-def $stg_dsta, implicit [[S_LSHL_B32_]], implicit $exec {
  ; GCN-NEXT:     $stg_dsta = V_LOAD_IDX [[S_LSHL_B32_]], 0, implicit $exec :: (load (s32), addrspace 10)
  ; GCN-NEXT:     V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_]], 0, implicit $exec :: (store (s32), addrspace 10)
  ; GCN-NEXT:   }
  ; GCN-NEXT:   [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_2]], 1, implicit-def $scc
  ; GCN-NEXT:   BUNDLE implicit-def $stg_dsta, implicit [[S_LSHL_B32_2]], implicit $exec, implicit [[S_LSHL_B32_3]] {
  ; GCN-NEXT:     $stg_dsta = V_MAX_U32_e64 23456, [[S_LSHL_B32_2]], implicit $exec
  ; GCN-NEXT:     V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_3]], 0, implicit $exec :: (store (s32), addrspace 10)
  ; GCN-NEXT:   }
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.2:
  ; GCN-NEXT:   S_ENDPGM 0
  ;
  ; ALLOC-LABEL: name: multi-bb-simple-move-to-store
  ; ALLOC: bb.0:
  ; ALLOC-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT:   [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
  ; ALLOC-NEXT:   S_CMP_EQ_U32 [[S_LSHL_B32_]], 0, implicit-def $scc
  ; ALLOC-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit $scc
  ; ALLOC-NEXT:   S_BRANCH %bb.1
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT: bb.1:
  ; ALLOC-NEXT:   successors: %bb.2(0x80000000)
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT:   $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
  ; ALLOC-NEXT:   [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_]], 2, implicit-def $scc
  ; ALLOC-NEXT:   [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_1]], 1, implicit-def $scc
  ; ALLOC-NEXT:   BUNDLE implicit-def $stg_dsta, implicit $idx1, implicit $exec {
  ; ALLOC-NEXT:     $stg_dsta = V_LOAD_IDX $idx1, 0, implicit $exec :: (load (s32), addrspace 10)
  ; ALLOC-NEXT:     V_STORE_IDX internal $stg_dsta, $idx1, 0, implicit $exec :: (store (s32), addrspace 10)
  ; ALLOC-NEXT:   }
  ; ALLOC-NEXT:   [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_2]], 1, implicit-def $scc
  ; ALLOC-NEXT:   $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_3]]
  ; ALLOC-NEXT:   BUNDLE implicit-def $stg_dsta, implicit [[S_LSHL_B32_2]], implicit $exec, implicit $idx1 {
  ; ALLOC-NEXT:     $stg_dsta = V_MAX_U32_e64 23456, [[S_LSHL_B32_2]], implicit $exec
  ; ALLOC-NEXT:     V_STORE_IDX internal $stg_dsta, $idx1, 0, implicit $exec :: (store (s32), addrspace 10)
  ; ALLOC-NEXT:   }
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT: bb.2:
  ; ALLOC-NEXT:   S_ENDPGM 0
  ;
  ; LOWERED-LABEL: name: multi-bb-simple-move-to-store
  ; LOWERED: bb.0:
  ; LOWERED-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $sgpr0
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $sgpr1
  ; LOWERED-NEXT:   S_WAIT_LOADCNT_DSCNT 0
  ; LOWERED-NEXT:   S_WAIT_EXPCNT 0
  ; LOWERED-NEXT:   S_WAIT_SAMPLECNT 0
  ; LOWERED-NEXT:   S_WAIT_BVHCNT 0
  ; LOWERED-NEXT:   S_WAIT_KMCNT 0
  ; LOWERED-NEXT:   renamable $sgpr0 = S_LSHL_B32 1, 2, implicit-def dead $scc
  ; LOWERED-NEXT:   S_CMP_EQ_U32 renamable $sgpr0, 0, implicit-def $scc
  ; LOWERED-NEXT:   S_CBRANCH_SCC1 %bb.2, implicit killed $scc
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT: bb.1:
  ; LOWERED-NEXT:   successors: %bb.2(0x80000000)
  ; LOWERED-NEXT:   liveins: $sgpr0
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT:   renamable $sgpr1 = S_LSHL_B32 renamable $sgpr0, 2, implicit-def dead $scc
  ; LOWERED-NEXT:   $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
  ; LOWERED-NEXT:   renamable $sgpr1 = S_LSHL_B32 killed renamable $sgpr1, 1, implicit-def dead $scc
  ; LOWERED-NEXT:   S_SET_VGPR_FRAMES 65
  ; LOWERED-NEXT:   $vgpr0 = V_MOV_B32_e32 undef $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
  ; LOWERED-NEXT:   renamable $sgpr0 = S_LSHL_B32 renamable $sgpr1, 1, implicit-def dead $scc
  ; LOWERED-NEXT:   $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr0
  ; LOWERED-NEXT:   undef $vgpr0 = V_MAX_U32_e64 23456, killed $sgpr1, <0x{{[0-9a-f]+}}>, implicit $exec
  ; LOWERED-NEXT: {{  $}}
  ; LOWERED-NEXT: bb.2:
  ; LOWERED-NEXT:   S_ENDPGM 0
  bb.0:
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:vgpr_32 = V_LOAD_IDX %0:sreg_32_xexec_hi, 0, implicit $exec :: (load (s32), addrspace 10)
    S_CMP_EQ_U32 %0:sreg_32_xexec_hi, 0, implicit-def $scc
    S_CBRANCH_SCC1 %bb.2, implicit $scc
    S_BRANCH %bb.1

  bb.1:
    %2:sreg_32_xexec_hi = S_LSHL_B32 %0:sreg_32_xexec_hi, 2, implicit-def $scc
    %3:sreg_32_xexec_hi = S_LSHL_B32 %2:sreg_32_xexec_hi, 1, implicit-def $scc
    V_STORE_IDX %1:vgpr_32, %0:sreg_32_xexec_hi, 0, implicit $exec :: (store (s32), addrspace 10)
    %5:vgpr_32 = V_MAX_U32_e64 23456, %3:sreg_32_xexec_hi, implicit $exec
    %6:sreg_32_xexec_hi = S_LSHL_B32 %3:sreg_32_xexec_hi, 1, implicit-def $scc
    V_STORE_IDX %5:vgpr_32, %6:sreg_32_xexec_hi, 0, implicit $exec :: (store (s32), addrspace 10)

  bb.2:
    S_ENDPGM 0

...
---
name:            multi-bb-coremis-swap-order
machineFunctionInfo:
  laneSharedVGPRSize: 1000
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
tracksRegLiveness: true
body:             |
  ; GCN-LABEL: name: multi-bb-coremis-swap-order
  ; GCN: bb.0:
  ; GCN-NEXT:   successors: %bb.1(0x80000000)
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT:   [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
  ; GCN-NEXT:   S_CMP_EQ_U32 [[S_LSHL_B32_]], 0, implicit-def $scc
  ; GCN-NEXT:   [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_]], 2, implicit-def $scc
  ; GCN-NEXT:   [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_1]], 1, implicit-def $scc
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.1:
  ; GCN-NEXT:   successors: %bb.2(0x80000000)
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT:   [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_2]], 1, implicit-def $scc
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.2:
  ; GCN-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def %6, implicit [[S_LSHL_B32_]], implicit $exec {
  ; GCN-NEXT:     $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 0, implicit $exec :: (load (s32), addrspace 10)
  ; GCN-NEXT:     [[V_READFIRSTLANE_B32_:%[0-9]+]]:sreg_32_xm0 = V_READFIRSTLANE_B32 internal $stg_srca, implicit $exec
  ; GCN-NEXT:   }
  ; GCN-NEXT:   [[S_LSHL_B32_4:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_3]], [[V_READFIRSTLANE_B32_]], implicit-def $scc
  ; GCN-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit [[S_LSHL_B32_]], implicit $exec, implicit [[S_LSHL_B32_2]], implicit [[S_LSHL_B32_4]] {
  ; GCN-NEXT:     $stg_srca = V_LOAD_IDX [[S_LSHL_B32_]], 0, implicit $exec :: (load (s32), addrspace 10)
  ; GCN-NEXT:     $stg_dsta = V_MAX_U32_e64 internal $stg_srca, [[S_LSHL_B32_2]], implicit $exec
  ; GCN-NEXT:     V_STORE_IDX internal $stg_dsta, [[S_LSHL_B32_4]], 0, implicit $exec :: (store (s32), addrspace 10)
  ; GCN-NEXT:   }
  ;
  ; ALLOC-LABEL: name: multi-bb-coremis-swap-order
  ; ALLOC: bb.0:
  ; ALLOC-NEXT:   successors: %bb.1(0x80000000)
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT:   [[S_LSHL_B32_:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
  ; ALLOC-NEXT:   [[S_LSHL_B32_1:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_]], 2, implicit-def $scc
  ; ALLOC-NEXT:   [[S_LSHL_B32_2:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_1]], 1, implicit-def $scc
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT: bb.1:
  ; ALLOC-NEXT:   successors: %bb.2(0x80000000)
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT:   [[S_LSHL_B32_3:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_2]], 1, implicit-def $scc
  ; ALLOC-NEXT: {{  $}}
  ; ALLOC-NEXT: bb.2:
  ; ALLOC-NEXT:   $idx2 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_]]
  ; ALLOC-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def %6, implicit $idx2, implicit $exec {
  ; ALLOC-NEXT:     $stg_srca = V_LOAD_IDX $idx2, 0, implicit $exec :: (load (s32), addrspace 10)
  ; ALLOC-NEXT:     [[V_READFIRSTLANE_B32_:%[0-9]+]]:sreg_32_xm0 = V_READFIRSTLANE_B32 internal $stg_srca, implicit $exec
  ; ALLOC-NEXT:   }
  ; ALLOC-NEXT:   [[S_LSHL_B32_4:%[0-9]+]]:sreg_32_xexec_hi = S_LSHL_B32 [[S_LSHL_B32_3]], [[V_READFIRSTLANE_B32_]], implicit-def $scc
  ; ALLOC-NEXT:   $idx1 = S_SET_GPR_IDX_U32 [[S_LSHL_B32_4]]
  ; ALLOC-NEXT:   BUNDLE implicit-def $stg_srca, implicit-def $stg_dsta, implicit $idx2, implicit $exec, implicit [[S_LSHL_B32_2]], implicit $idx1 {
  ; ALLOC-NEXT:     $stg_srca = V_LOAD_IDX $idx2, 0, implicit $exec :: (load (s32), addrspace 10)
  ; ALLOC-NEXT:     $stg_dsta = V_MAX_U32_e64 internal $stg_srca, [[S_LSHL_B32_2]], implicit $exec
  ; ALLOC-NEXT:     V_STORE_IDX internal $stg_dsta, $idx1, 0, implicit $exec :: (store (s32), addrspace 10)
  ; ALLOC-NEXT:   }
  ;
  ; LOWERED-LABEL: name: multi-bb-coremis-swap-order
  ; LOWERED: bb.0:
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION escape 0x0f, 0x09, 0x90, 0x40, 0x94, 0x04, 0x35, 0x24, 0x36, 0xe9, 0x02
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $sgpr0
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $sgpr1
  ; LOWERED-NEXT:   frame-setup CFI_INSTRUCTION undefined $sgpr2
  ; LOWERED-NEXT:   S_WAIT_LOADCNT_DSCNT 0
  ; LOWERED-NEXT:   S_WAIT_EXPCNT 0
  ; LOWERED-NEXT:   S_WAIT_SAMPLECNT 0
  ; LOWERED-NEXT:   S_WAIT_BVHCNT 0
  ; LOWERED-NEXT:   S_WAIT_KMCNT 0
  ; LOWERED-NEXT:   renamable $sgpr1 = S_LSHL_B32 1, 2, implicit-def dead $scc
  ; LOWERED-NEXT:   $idx2 = S_SET_GPR_IDX_U32 renamable $sgpr1
  ; LOWERED-NEXT:   renamable $sgpr0 = S_LSHL_B32 killed renamable $sgpr1, 2, implicit-def dead $scc
  ; LOWERED-NEXT:   S_SET_VGPR_FRAMES 66
  ; LOWERED-NEXT:   renamable $sgpr1 = V_READFIRSTLANE_B32 undef $vgpr0, <0x{{[0-9a-f]+}}>, implicit $exec
  ; LOWERED-NEXT:   renamable $sgpr0 = S_LSHL_B32 killed renamable $sgpr0, 1, implicit-def dead $scc
  ; LOWERED-NEXT:   renamable $sgpr2 = S_LSHL_B32 renamable $sgpr0, 1, implicit-def dead $scc
  ; LOWERED-NEXT:   renamable $sgpr1 = S_LSHL_B32 killed renamable $sgpr2, killed renamable $sgpr1, implicit-def dead $scc
  ; LOWERED-NEXT:   $idx1 = S_SET_GPR_IDX_U32 killed renamable $sgpr1
  ; LOWERED-NEXT:   undef $vgpr0 = V_MAX_U32_e64 undef $vgpr0, killed $sgpr0, <0x{{[0-9a-f]+}}>, implicit $exec

  bb.0:
    %0:sreg_32_xexec_hi = S_LSHL_B32 1, 2, implicit-def $scc
    %1:vgpr_32 = V_LOAD_IDX %0:sreg_32_xexec_hi, 0, implicit $exec :: (load (s32), addrspace 10)
    S_CMP_EQ_U32 %0:sreg_32_xexec_hi, 0, implicit-def $scc
    %2:sreg_32_xexec_hi = S_LSHL_B32 %0:sreg_32_xexec_hi, 2, implicit-def $scc
    %3:sreg_32_xexec_hi = S_LSHL_B32 %2:sreg_32_xexec_hi, 1, implicit-def $scc

  bb.1:
    %4:vgpr_32 = V_MAX_U32_e64 %1:vgpr_32, %3:sreg_32_xexec_hi, implicit $exec
    %5:sreg_32_xexec_hi = S_LSHL_B32 %3:sreg_32_xexec_hi, 1, implicit-def $scc

  bb.2:
    %6:sreg_32_xm0 = V_READFIRSTLANE_B32 %1:vgpr_32, implicit $exec
    %7:sreg_32_xexec_hi = S_LSHL_B32 %5:sreg_32_xexec_hi, %6:sreg_32_xm0, implicit-def $scc
    V_STORE_IDX %4:vgpr_32, %7:sreg_32_xexec_hi, 0, implicit $exec :: (store (s32), addrspace 10)
