; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -mtriple=amdgcn -mcpu=gfx1201 -mattr=+wavefrontsize32 -passes=amdgpu-codegenprepare -o - < %s | FileCheck %s --check-prefixes=CHECK,WAVE32
; RUN: opt -S -mtriple=amdgcn -mcpu=gfx1201 -mattr=+wavefrontsize64 -passes=amdgpu-codegenprepare -o - < %s | FileCheck %s --check-prefixes=CHECK,WAVE64

define amdgpu_kernel void @single_wave_workgroup(ptr addrspace(1) %out) #0 {
; CHECK-LABEL: define amdgpu_kernel void @single_wave_workgroup(
; CHECK-SAME: ptr addrspace(1) [[OUT:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:    fence syncscope("wavefront") acq_rel
; CHECK-NEXT:    ret void
;
  fence syncscope("workgroup") acq_rel
  ret void
}

define amdgpu_kernel void @single_wave_workgroup64(ptr addrspace(1) %out) #1 {
; WAVE32-LABEL: define amdgpu_kernel void @single_wave_workgroup64(
; WAVE32-SAME: ptr addrspace(1) [[OUT:%.*]]) #[[ATTR1:[0-9]+]] {
; WAVE32-NEXT:    fence syncscope("workgroup") acq_rel
; WAVE32-NEXT:    ret void
;
; WAVE64-LABEL: define amdgpu_kernel void @single_wave_workgroup64(
; WAVE64-SAME: ptr addrspace(1) [[OUT:%.*]]) #[[ATTR1:[0-9]+]] {
; WAVE64-NEXT:    fence syncscope("wavefront") acq_rel
; WAVE64-NEXT:    ret void
;
  fence syncscope("workgroup") acq_rel
  ret void
}

define amdgpu_kernel void @multi_wave_workgroup(ptr addrspace(1) %out) #2 {
; CHECK-LABEL: define amdgpu_kernel void @multi_wave_workgroup(
; CHECK-SAME: ptr addrspace(1) [[OUT:%.*]]) #[[ATTR2:[0-9]+]] {
; CHECK-NEXT:    fence syncscope("workgroup") acq_rel
; CHECK-NEXT:    ret void
;
  fence syncscope("workgroup") acq_rel
  ret void
}

attributes #0 = { "amdgpu-flat-work-group-size"="32,32" }
attributes #1 = { "amdgpu-flat-work-group-size"="64,64" }
attributes #2 = { "amdgpu-flat-work-group-size"="64,256" }
