; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx950 -amdgpu-sched-strategy=coexec --enable-post-misched=0 %s -o - 2>&1 | FileCheck %s

; The coexec scheduler strategy pushes RewriteMFMAForm into its pipeline so MFMA
; chains can be rewritten to the AGPR form when ArchVGPR pressure is excessive.
;
; This IR is reduced from a Triton-generated GEMM kernel with multiple (28 to be
; exact) MFMAs in a phi-carried loop with high VGPR pressure, every MFMA in the
; loop is rewritten to the AGPR-destination form (v_mfma_f32_16x16x32_f16 a*).

; FIXME: To enable on gfx950?
; CHECK: warning: {{.*}}'amdgpu-sched-strategy'='coexec' is only supported for gfx1250
; CHECK-LABEL: v5_local_prefetch:
; CHECK-COUNT-28: v_mfma_f32_16x16x32_f16 a
; CHECK-NOT: v_mfma_f32_16x16x32_f16 v

target triple = "amdgcn-amd-amdhsa"

define amdgpu_kernel void @v5_local_prefetch() #0 {
; CHECK-LABEL: v5_local_prefetch:
; CHECK:       ; %bb.0: ; %.lr.ph
; CHECK-NEXT:    v_mov_b32_e32 v2, 0
; CHECK-NEXT:    v_mov_b32_e32 v9, v2
; CHECK-NEXT:    v_mov_b32_e32 v11, v2
; CHECK-NEXT:    v_mov_b32_e32 v12, v2
; CHECK-NEXT:    v_mov_b32_e32 v13, v2
; CHECK-NEXT:    v_mov_b32_e32 v15, v2
; CHECK-NEXT:    v_mov_b32_e32 v16, v2
; CHECK-NEXT:    v_mov_b32_e32 v17, v2
; CHECK-NEXT:    v_mov_b32_e32 v19, v2
; CHECK-NEXT:    v_mov_b32_e32 v20, v2
; CHECK-NEXT:    v_mov_b32_e32 v25, v2
; CHECK-NEXT:    v_mov_b32_e32 v27, v2
; CHECK-NEXT:    v_mov_b32_e32 v31, v2
; CHECK-NEXT:    v_mov_b32_e32 v35, v2
; CHECK-NEXT:    v_mov_b32_e32 v36, v2
; CHECK-NEXT:    v_mov_b32_e32 v37, v2
; CHECK-NEXT:    v_mov_b32_e32 v39, v2
; CHECK-NEXT:    v_mov_b32_e32 v40, v2
; CHECK-NEXT:    v_mov_b32_e32 v41, v2
; CHECK-NEXT:    v_mov_b32_e32 v43, v2
; CHECK-NEXT:    v_mov_b32_e32 v44, v2
; CHECK-NEXT:    v_mov_b32_e32 v45, v2
; CHECK-NEXT:    v_mov_b32_e32 v47, v2
; CHECK-NEXT:    v_mov_b32_e32 v51, v2
; CHECK-NEXT:    v_mov_b32_e32 v5, v2
; CHECK-NEXT:    v_mov_b32_e32 v8, 0
; CHECK-NEXT:    v_mov_b32_e32 v10, 0
; CHECK-NEXT:    v_mov_b32_e32 v14, 0
; CHECK-NEXT:    v_mov_b32_e32 v18, 0
; CHECK-NEXT:    v_mov_b32_e32 v24, 0
; CHECK-NEXT:    v_mov_b32_e32 v26, 0
; CHECK-NEXT:    v_mov_b32_e32 v30, 0
; CHECK-NEXT:    v_mov_b32_e32 v54, 0
; CHECK-NEXT:    v_mov_b32_e32 v34, 0
; CHECK-NEXT:    v_mov_b32_e32 v38, 0
; CHECK-NEXT:    v_mov_b32_e32 v42, 0
; CHECK-NEXT:    v_mov_b32_e32 v46, 0
; CHECK-NEXT:    v_mov_b32_e32 v50, 0
; CHECK-NEXT:    s_mov_b32 s0, 0
; CHECK-NEXT:    s_mov_b32 s1, s0
; CHECK-NEXT:    s_mov_b32 s2, s0
; CHECK-NEXT:    s_mov_b32 s3, s0
; CHECK-NEXT:    v_mov_b64_e32 v[62:63], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[60:61], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[66:67], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[64:65], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[70:71], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[68:69], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[74:75], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[72:73], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[78:79], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[76:77], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[82:83], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[80:81], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[86:87], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[84:85], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[90:91], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[88:89], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[94:95], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[92:93], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[98:99], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[96:97], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[102:103], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[100:101], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[106:107], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[104:105], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[110:111], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[108:109], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[114:115], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[112:113], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[118:119], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[116:117], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[122:123], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[120:121], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[126:127], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[124:125], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[130:131], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[128:129], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[134:135], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[132:133], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[138:139], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[136:137], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[142:143], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[140:141], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[146:147], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[144:145], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[150:151], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[148:149], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[154:155], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[152:153], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[158:159], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[156:157], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[162:163], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[160:161], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[166:167], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[164:165], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[170:171], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[168:169], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[174:175], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[172:173], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[178:179], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[176:177], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[182:183], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[180:181], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[186:187], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[184:185], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[190:191], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[188:189], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[194:195], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[192:193], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[198:199], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[196:197], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[202:203], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[200:201], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[206:207], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[204:205], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[210:211], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[208:209], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[214:215], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[212:213], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[218:219], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[216:217], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[222:223], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[220:221], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[226:227], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[224:225], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[230:231], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[228:229], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[234:235], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[232:233], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[238:239], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[236:237], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[242:243], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[240:241], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[246:247], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[244:245], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[250:251], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[248:249], s[0:1]
; CHECK-NEXT:    v_mov_b64_e32 v[254:255], s[2:3]
; CHECK-NEXT:    v_mov_b64_e32 v[252:253], s[0:1]
; CHECK-NEXT:    v_accvgpr_write_b32 a0, s0
; CHECK-NEXT:    v_accvgpr_write_b32 a1, s1
; CHECK-NEXT:    v_accvgpr_write_b32 a2, s2
; CHECK-NEXT:    v_accvgpr_write_b32 a3, s3
; CHECK-NEXT:    v_accvgpr_write_b32 a7, s3
; CHECK-NEXT:    v_accvgpr_write_b32 a6, s2
; CHECK-NEXT:    v_accvgpr_write_b32 a5, s1
; CHECK-NEXT:    v_accvgpr_write_b32 a4, s0
; CHECK-NEXT:    v_accvgpr_write_b32 a11, s3
; CHECK-NEXT:    v_accvgpr_write_b32 a10, s2
; CHECK-NEXT:    v_accvgpr_write_b32 a9, s1
; CHECK-NEXT:    v_accvgpr_write_b32 a8, s0
; CHECK-NEXT:    v_accvgpr_write_b32 a15, s3
; CHECK-NEXT:    v_accvgpr_write_b32 a14, s2
; CHECK-NEXT:    v_accvgpr_write_b32 a13, s1
; CHECK-NEXT:    v_accvgpr_write_b32 a12, s0
; CHECK-NEXT:    v_mov_b32_e32 v56, 0
; CHECK-NEXT:    s_and_b64 vcc, exec, -1
; CHECK-NEXT:    ds_read_b128 a[16:19], v2
; CHECK-NEXT:    s_waitcnt lgkmcnt(0)
; CHECK-NEXT:    v_accvgpr_read_b32 v0, a16
; CHECK-NEXT:    v_accvgpr_read_b32 v1, a17
; CHECK-NEXT:    v_accvgpr_write_b32 a19, s3
; CHECK-NEXT:    v_accvgpr_write_b32 a18, s2
; CHECK-NEXT:    v_accvgpr_write_b32 a17, s1
; CHECK-NEXT:    v_accvgpr_write_b32 a16, s0
; CHECK-NEXT:    .p2align 5, , 4
; CHECK-NEXT:  .LBB0_1: ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[10:13], v[72:75], v[76:79], v[10:13]
; CHECK-NEXT:    s_nop 3
; CHECK-NEXT:    v_mov_b32_e32 v4, v56
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[14:17], v[88:91], v[92:95], v[14:17]
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[38:41], v[196:199], v[200:203], v[38:41]
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[42:45], v[212:215], v[216:219], v[42:45]
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[10:13], v[80:83], v[84:87], v[10:13]
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[14:17], v[96:99], v[100:103], v[14:17]
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[38:41], v[204:207], v[208:211], v[38:41]
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[42:45], v[220:223], v[224:227], v[42:45]
; CHECK-NEXT:    v_mov_b32_e32 v3, v2
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[32:35], v[0:3], v[184:187], v[34:37]
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[34:37], v[188:191], v[192:195], v[32:35]
; CHECK-NEXT:    v_mov_b32_e32 v6, v2
; CHECK-NEXT:    v_mov_b32_e32 v7, v2
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[6:9], v[0:3], v[60:63], v[6:9]
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[6:9], v[64:67], v[68:71], v[6:9]
; CHECK-NEXT:    v_mov_b32_e32 v21, v2
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[18:21], v[104:107], v[108:111], v[18:21]
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[18:21], v[112:115], v[116:119], v[18:21]
; CHECK-NEXT:    v_mov_b32_e32 v22, v2
; CHECK-NEXT:    v_mov_b32_e32 v23, v2
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[22:25], v[120:123], v[124:127], v[22:25]
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[22:25], v[128:131], v[132:135], v[22:25]
; CHECK-NEXT:    v_mov_b32_e32 v28, v2
; CHECK-NEXT:    v_mov_b32_e32 v29, v2
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[26:29], v[136:139], v[140:143], v[26:29]
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[26:29], v[144:147], v[148:151], v[26:29]
; CHECK-NEXT:    v_mov_b32_e32 v32, v2
; CHECK-NEXT:    v_mov_b32_e32 v33, v2
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[28:31], v[152:155], v[156:159], v[30:33]
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[30:33], v[160:163], v[164:167], v[28:31]
; CHECK-NEXT:    ; implicit-def: $vgpr55
; CHECK-NEXT:    ; implicit-def: $vgpr56
; CHECK-NEXT:    ; implicit-def: $vgpr57
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[52:55], v[168:171], v[172:175], v[54:57]
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[54:57], v[176:179], v[180:183], v[52:55]
; CHECK-NEXT:    v_mov_b32_e32 v48, v2
; CHECK-NEXT:    v_mov_b32_e32 v49, v2
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[46:49], v[228:231], v[232:235], v[46:49]
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[46:49], v[236:239], v[240:243], v[46:49]
; CHECK-NEXT:    s_nop 0
; CHECK-NEXT:    v_mov_b32_e32 v52, v2
; CHECK-NEXT:    v_mov_b32_e32 v53, v2
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[48:51], v[244:247], v[248:251], v[50:53]
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[50:53], v[252:255], a[0:3], v[48:51]
; CHECK-NEXT:    v_mov_b32_e32 v3, 1.0
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[56:59], a[4:7], a[8:11], v[2:5]
; CHECK-NEXT:    v_mfma_f32_16x16x32_f16 v[56:59], a[12:15], a[16:19], v[56:59]
; CHECK-NEXT:    s_nop 1
; CHECK-NEXT:    v_mov_b32_e32 v5, v4
; CHECK-NEXT:    s_mov_b64 vcc, vcc
; CHECK-NEXT:    s_cbranch_vccnz .LBB0_1
; CHECK-NEXT:  ; %bb.2: ; %DummyReturnBlock
; CHECK-NEXT:    s_endpgm
.lr.ph:
  %0 = load <8 x half>, ptr addrspace(3) null, align 16
  %1 = shufflevector <8 x half> %0, <8 x half> zeroinitializer, <2 x i32> <i32 0, i32 1>
  %2 = shufflevector <8 x half> %0, <8 x half> zeroinitializer, <2 x i32> <i32 2, i32 3>
  br label %3

3:                                                ; preds = %3, %.lr.ph
  %4 = phi float [ 0.000000e+00, %.lr.ph ], [ %53, %3 ]
  %5 = phi float [ 0.000000e+00, %.lr.ph ], [ %54, %3 ]
  %6 = phi float [ 0.000000e+00, %.lr.ph ], [ %61, %3 ]
  %7 = phi float [ 0.000000e+00, %.lr.ph ], [ %62, %3 ]
  %8 = phi float [ 0.000000e+00, %.lr.ph ], [ %63, %3 ]
  %9 = phi float [ 0.000000e+00, %.lr.ph ], [ %64, %3 ]
  %10 = phi float [ 0.000000e+00, %.lr.ph ], [ %71, %3 ]
  %11 = phi float [ 0.000000e+00, %.lr.ph ], [ %72, %3 ]
  %12 = phi float [ 0.000000e+00, %.lr.ph ], [ %73, %3 ]
  %13 = phi float [ 0.000000e+00, %.lr.ph ], [ %74, %3 ]
  %14 = phi float [ 0.000000e+00, %.lr.ph ], [ %80, %3 ]
  %15 = phi float [ 0.000000e+00, %.lr.ph ], [ %81, %3 ]
  %16 = phi float [ 0.000000e+00, %.lr.ph ], [ %82, %3 ]
  %17 = phi float [ 0.000000e+00, %.lr.ph ], [ %87, %3 ]
  %18 = phi float [ 0.000000e+00, %.lr.ph ], [ %88, %3 ]
  %19 = phi float [ 0.000000e+00, %.lr.ph ], [ %93, %3 ]
  %20 = phi float [ 0.000000e+00, %.lr.ph ], [ %94, %3 ]
  %21 = phi float [ 0.000000e+00, %.lr.ph ], [ %100, %3 ]
  %22 = phi float [ 0.000000e+00, %.lr.ph ], [ %101, %3 ]
  %23 = phi float [ 0.000000e+00, %.lr.ph ], [ %24, %3 ]
  %24 = phi float [ 0.000000e+00, %.lr.ph ], [ %106, %3 ]
  %25 = phi float [ 0.000000e+00, %.lr.ph ], [ %113, %3 ]
  %26 = phi float [ 0.000000e+00, %.lr.ph ], [ %114, %3 ]
  %27 = phi float [ 0.000000e+00, %.lr.ph ], [ %115, %3 ]
  %28 = phi float [ 0.000000e+00, %.lr.ph ], [ %116, %3 ]
  %29 = phi float [ 0.000000e+00, %.lr.ph ], [ %123, %3 ]
  %30 = phi float [ 0.000000e+00, %.lr.ph ], [ %124, %3 ]
  %31 = phi float [ 0.000000e+00, %.lr.ph ], [ %125, %3 ]
  %32 = phi float [ 0.000000e+00, %.lr.ph ], [ %126, %3 ]
  %33 = phi float [ 0.000000e+00, %.lr.ph ], [ %133, %3 ]
  %34 = phi float [ 0.000000e+00, %.lr.ph ], [ %134, %3 ]
  %35 = phi float [ 0.000000e+00, %.lr.ph ], [ %135, %3 ]
  %36 = phi float [ 0.000000e+00, %.lr.ph ], [ %136, %3 ]
  %37 = phi float [ 0.000000e+00, %.lr.ph ], [ %141, %3 ]
  %38 = phi float [ 0.000000e+00, %.lr.ph ], [ %142, %3 ]
  %39 = phi float [ 0.000000e+00, %.lr.ph ], [ %147, %3 ]
  %40 = phi float [ 0.000000e+00, %.lr.ph ], [ %148, %3 ]
  %41 = phi float [ 0.000000e+00, %.lr.ph ], [ %153, %3 ]
  %42 = phi float [ 0.000000e+00, %.lr.ph ], [ %41, %3 ]
  %43 = phi <2 x half> [ %1, %.lr.ph ], [ zeroinitializer, %3 ]
  %44 = phi <2 x half> [ %2, %.lr.ph ], [ zeroinitializer, %3 ]
  %45 = phi <8 x half> [ zeroinitializer, %.lr.ph ], [ <half 0.000000e+00, half 0.000000e+00, half poison, half poison, half poison, half poison, half poison, half poison>, %3 ]
  %46 = shufflevector <2 x half> %43, <2 x half> %44, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 poison, i32 poison, i32 poison, i32 poison>
  %47 = shufflevector <8 x half> %46, <8 x half> zeroinitializer, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 8, i32 9, i32 poison, i32 poison>
  %48 = shufflevector <8 x half> %46, <8 x half> zeroinitializer, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 8, i32 9>
  %49 = insertelement <4 x float> zeroinitializer, float %4, i64 2
  %50 = insertelement <4 x float> %49, float %5, i64 3
  %51 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> %47, <8 x half> zeroinitializer, <4 x float> %50, i32 0, i32 0, i32 0)
  %52 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> zeroinitializer, <8 x half> zeroinitializer, <4 x float> %51, i32 0, i32 0, i32 0)
  %53 = extractelement <4 x float> %52, i64 2
  %54 = extractelement <4 x float> %52, i64 3
  %55 = insertelement <4 x float> zeroinitializer, float %6, i64 0
  %56 = insertelement <4 x float> %55, float %7, i64 1
  %57 = insertelement <4 x float> %56, float %8, i64 2
  %58 = insertelement <4 x float> %57, float %9, i64 3
  %59 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> zeroinitializer, <8 x half> zeroinitializer, <4 x float> %58, i32 0, i32 0, i32 0)
  %60 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> zeroinitializer, <8 x half> zeroinitializer, <4 x float> %59, i32 0, i32 0, i32 0)
  %61 = extractelement <4 x float> %60, i64 0
  %62 = extractelement <4 x float> %60, i64 1
  %63 = extractelement <4 x float> %60, i64 2
  %64 = extractelement <4 x float> %60, i64 3
  %65 = insertelement <4 x float> zeroinitializer, float %10, i64 0
  %66 = insertelement <4 x float> %65, float %11, i64 1
  %67 = insertelement <4 x float> %66, float %12, i64 2
  %68 = insertelement <4 x float> %67, float %13, i64 3
  %69 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> zeroinitializer, <8 x half> zeroinitializer, <4 x float> %68, i32 0, i32 0, i32 0)
  %70 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> zeroinitializer, <8 x half> zeroinitializer, <4 x float> %69, i32 0, i32 0, i32 0)
  %71 = extractelement <4 x float> %70, i64 0
  %72 = extractelement <4 x float> %70, i64 1
  %73 = extractelement <4 x float> %70, i64 2
  %74 = extractelement <4 x float> %70, i64 3
  %75 = insertelement <4 x float> zeroinitializer, float %14, i64 0
  %76 = insertelement <4 x float> %75, float %15, i64 1
  %77 = insertelement <4 x float> %76, float %16, i64 2
  %78 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> zeroinitializer, <8 x half> zeroinitializer, <4 x float> %77, i32 0, i32 0, i32 0)
  %79 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> zeroinitializer, <8 x half> zeroinitializer, <4 x float> %78, i32 0, i32 0, i32 0)
  %80 = extractelement <4 x float> %79, i64 0
  %81 = extractelement <4 x float> %79, i64 1
  %82 = extractelement <4 x float> %79, i64 2
  %83 = insertelement <4 x float> zeroinitializer, float %17, i64 2
  %84 = insertelement <4 x float> %83, float %18, i64 3
  %85 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> zeroinitializer, <8 x half> zeroinitializer, <4 x float> %84, i32 0, i32 0, i32 0)
  %86 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> zeroinitializer, <8 x half> zeroinitializer, <4 x float> %85, i32 0, i32 0, i32 0)
  %87 = extractelement <4 x float> %86, i64 2
  %88 = extractelement <4 x float> %86, i64 3
  %89 = insertelement <4 x float> zeroinitializer, float %19, i64 0
  %90 = insertelement <4 x float> %89, float %20, i64 1
  %91 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> zeroinitializer, <8 x half> zeroinitializer, <4 x float> %90, i32 0, i32 0, i32 0)
  %92 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> zeroinitializer, <8 x half> zeroinitializer, <4 x float> %91, i32 0, i32 0, i32 0)
  %93 = extractelement <4 x float> %92, i64 0
  %94 = extractelement <4 x float> %92, i64 1
  %95 = shufflevector <8 x half> zeroinitializer, <8 x half> %45, <8 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 8, i32 9>
  %96 = insertelement <4 x float> zeroinitializer, float %21, i64 0
  %97 = insertelement <4 x float> %96, float %22, i64 1
  %98 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> %95, <8 x half> zeroinitializer, <4 x float> %97, i32 0, i32 0, i32 0)
  %99 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> zeroinitializer, <8 x half> zeroinitializer, <4 x float> %98, i32 0, i32 0, i32 0)
  %100 = extractelement <4 x float> %99, i64 0
  %101 = extractelement <4 x float> %99, i64 1
  %102 = insertelement <4 x float> poison, float %23, i64 0
  %103 = insertelement <4 x float> %102, float %24, i64 0
  %104 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> zeroinitializer, <8 x half> zeroinitializer, <4 x float> %103, i32 0, i32 0, i32 0)
  %105 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> zeroinitializer, <8 x half> zeroinitializer, <4 x float> %104, i32 0, i32 0, i32 0)
  %106 = extractelement <4 x float> %105, i64 0
  %107 = insertelement <4 x float> zeroinitializer, float %25, i64 0
  %108 = insertelement <4 x float> %107, float %26, i64 1
  %109 = insertelement <4 x float> %108, float %27, i64 2
  %110 = insertelement <4 x float> %109, float %28, i64 3
  %111 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> %48, <8 x half> zeroinitializer, <4 x float> %110, i32 0, i32 0, i32 0)
  %112 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> zeroinitializer, <8 x half> zeroinitializer, <4 x float> %111, i32 0, i32 0, i32 0)
  %113 = extractelement <4 x float> %112, i64 0
  %114 = extractelement <4 x float> %112, i64 1
  %115 = extractelement <4 x float> %112, i64 2
  %116 = extractelement <4 x float> %112, i64 3
  %117 = insertelement <4 x float> zeroinitializer, float %29, i64 0
  %118 = insertelement <4 x float> %117, float %30, i64 1
  %119 = insertelement <4 x float> %118, float %31, i64 2
  %120 = insertelement <4 x float> %119, float %32, i64 3
  %121 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> zeroinitializer, <8 x half> zeroinitializer, <4 x float> %120, i32 0, i32 0, i32 0)
  %122 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> zeroinitializer, <8 x half> zeroinitializer, <4 x float> %121, i32 0, i32 0, i32 0)
  %123 = extractelement <4 x float> %122, i64 0
  %124 = extractelement <4 x float> %122, i64 1
  %125 = extractelement <4 x float> %122, i64 2
  %126 = extractelement <4 x float> %122, i64 3
  %127 = insertelement <4 x float> zeroinitializer, float %33, i64 0
  %128 = insertelement <4 x float> %127, float %34, i64 1
  %129 = insertelement <4 x float> %128, float %35, i64 2
  %130 = insertelement <4 x float> %129, float %36, i64 3
  %131 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> zeroinitializer, <8 x half> zeroinitializer, <4 x float> %130, i32 0, i32 0, i32 0)
  %132 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> zeroinitializer, <8 x half> zeroinitializer, <4 x float> %131, i32 0, i32 0, i32 0)
  %133 = extractelement <4 x float> %132, i64 0
  %134 = extractelement <4 x float> %132, i64 1
  %135 = extractelement <4 x float> %132, i64 2
  %136 = extractelement <4 x float> %132, i64 3
  %137 = insertelement <4 x float> zeroinitializer, float %37, i64 0
  %138 = insertelement <4 x float> %137, float %38, i64 1
  %139 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> zeroinitializer, <8 x half> zeroinitializer, <4 x float> %138, i32 0, i32 0, i32 0)
  %140 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> zeroinitializer, <8 x half> zeroinitializer, <4 x float> %139, i32 0, i32 0, i32 0)
  %141 = extractelement <4 x float> %140, i64 0
  %142 = extractelement <4 x float> %140, i64 1
  %143 = insertelement <4 x float> zeroinitializer, float %39, i64 0
  %144 = insertelement <4 x float> %143, float %40, i64 1
  %145 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> zeroinitializer, <8 x half> zeroinitializer, <4 x float> %144, i32 0, i32 0, i32 0)
  %146 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> zeroinitializer, <8 x half> zeroinitializer, <4 x float> %145, i32 0, i32 0, i32 0)
  %147 = extractelement <4 x float> %146, i64 0
  %148 = extractelement <4 x float> %146, i64 1
  %149 = insertelement <4 x float> <float 0.000000e+00, float 1.000000e+00, float 0.000000e+00, float 0.000000e+00>, float %41, i64 2
  %150 = insertelement <4 x float> %149, float %42, i64 3
  %151 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> zeroinitializer, <8 x half> zeroinitializer, <4 x float> %150, i32 0, i32 0, i32 0)
  %152 = tail call <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half> zeroinitializer, <8 x half> zeroinitializer, <4 x float> %151, i32 0, i32 0, i32 0)
  %153 = extractelement <4 x float> %152, i64 0
  br label %3
}

declare <4 x float> @llvm.amdgcn.mfma.f32.16x16x32.f16(<8 x half>, <8 x half>, <4 x float>, i32 immarg, i32 immarg, i32 immarg)

attributes #0 = { "amdgpu-flat-work-group-size"="1,256" }
