; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -mtriple=amdgcn-amd-amdhsa -mcpu=gfx942 -passes=vector-combine -S %s | FileCheck %s --check-prefixes=CHECK,CHECK-OPT
; RUN: opt -mtriple=amdgcn-amd-amdhsa -mcpu=gfx942 -S %s | FileCheck %s --check-prefixes=CHECK,CHECK-NOOPT

; Test that multiple scalar selects from the same vector source are combined
; back into a vector select when the optimization is enabled, and remain as
; individual scalar selects when disabled.

; This pattern occurs when buffer_load_dwordx4 results are bitcast to v16i8,
; then each byte is extracted and conditionally selected with zero.

define amdgpu_kernel void @combine_scalar_selects_v16i8(
;
; CHECK-OPT-LABEL: define amdgpu_kernel void @combine_scalar_selects_v16i8(
; CHECK-OPT-SAME: ptr addrspace(1) [[OUT:%.*]], <4 x i32> [[BUFFER_RESOURCE:%.*]], i32 [[OFFSET:%.*]], i1 [[VALID:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-OPT-NEXT:  [[ENTRY:.*:]]
; CHECK-OPT-NEXT:    [[LOADED:%.*]] = call <4 x i32> @llvm.amdgcn.raw.buffer.load.v4i32(<4 x i32> [[BUFFER_RESOURCE]], i32 [[OFFSET]], i32 0, i32 0)
; CHECK-OPT-NEXT:    [[COMBINED_SEL:%.*]] = select i1 [[VALID]], <4 x i32> [[LOADED]], <4 x i32> zeroinitializer
; CHECK-OPT-NEXT:    [[COMBINED_BC:%.*]] = bitcast <4 x i32> [[COMBINED_SEL]] to <16 x i8>
; CHECK-OPT-NEXT:    [[TMP0:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 0
; CHECK-OPT-NEXT:    [[TMP9:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 1
; CHECK-OPT-NEXT:    [[TMP3:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 2
; CHECK-OPT-NEXT:    [[TMP12:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 3
; CHECK-OPT-NEXT:    [[TMP5:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 4
; CHECK-OPT-NEXT:    [[TMP14:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 5
; CHECK-OPT-NEXT:    [[TMP7:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 6
; CHECK-OPT-NEXT:    [[TMP1:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 7
; CHECK-OPT-NEXT:    [[TMP10:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 8
; CHECK-OPT-NEXT:    [[TMP4:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 9
; CHECK-OPT-NEXT:    [[TMP13:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 10
; CHECK-OPT-NEXT:    [[TMP6:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 11
; CHECK-OPT-NEXT:    [[TMP15:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 12
; CHECK-OPT-NEXT:    [[TMP8:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 13
; CHECK-OPT-NEXT:    [[TMP2:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 14
; CHECK-OPT-NEXT:    [[TMP11:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 15
; CHECK-OPT-NEXT:    store i8 [[TMP0]], ptr addrspace(1) [[OUT]], align 1
; CHECK-OPT-NEXT:    [[PTR1:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 1
; CHECK-OPT-NEXT:    store i8 [[TMP9]], ptr addrspace(1) [[PTR1]], align 1
; CHECK-OPT-NEXT:    [[PTR2:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 2
; CHECK-OPT-NEXT:    store i8 [[TMP3]], ptr addrspace(1) [[PTR2]], align 1
; CHECK-OPT-NEXT:    [[PTR3:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 3
; CHECK-OPT-NEXT:    store i8 [[TMP12]], ptr addrspace(1) [[PTR3]], align 1
; CHECK-OPT-NEXT:    [[PTR4:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 4
; CHECK-OPT-NEXT:    store i8 [[TMP5]], ptr addrspace(1) [[PTR4]], align 1
; CHECK-OPT-NEXT:    [[PTR5:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 5
; CHECK-OPT-NEXT:    store i8 [[TMP14]], ptr addrspace(1) [[PTR5]], align 1
; CHECK-OPT-NEXT:    [[PTR6:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 6
; CHECK-OPT-NEXT:    store i8 [[TMP7]], ptr addrspace(1) [[PTR6]], align 1
; CHECK-OPT-NEXT:    [[PTR7:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 7
; CHECK-OPT-NEXT:    store i8 [[TMP1]], ptr addrspace(1) [[PTR7]], align 1
; CHECK-OPT-NEXT:    [[PTR8:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 8
; CHECK-OPT-NEXT:    store i8 [[TMP10]], ptr addrspace(1) [[PTR8]], align 1
; CHECK-OPT-NEXT:    [[PTR9:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 9
; CHECK-OPT-NEXT:    store i8 [[TMP4]], ptr addrspace(1) [[PTR9]], align 1
; CHECK-OPT-NEXT:    [[PTR10:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 10
; CHECK-OPT-NEXT:    store i8 [[TMP13]], ptr addrspace(1) [[PTR10]], align 1
; CHECK-OPT-NEXT:    [[PTR11:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 11
; CHECK-OPT-NEXT:    store i8 [[TMP6]], ptr addrspace(1) [[PTR11]], align 1
; CHECK-OPT-NEXT:    [[PTR12:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 12
; CHECK-OPT-NEXT:    store i8 [[TMP15]], ptr addrspace(1) [[PTR12]], align 1
; CHECK-OPT-NEXT:    [[PTR13:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 13
; CHECK-OPT-NEXT:    store i8 [[TMP8]], ptr addrspace(1) [[PTR13]], align 1
; CHECK-OPT-NEXT:    [[PTR14:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 14
; CHECK-OPT-NEXT:    store i8 [[TMP2]], ptr addrspace(1) [[PTR14]], align 1
; CHECK-OPT-NEXT:    [[PTR15:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 15
; CHECK-OPT-NEXT:    store i8 [[TMP11]], ptr addrspace(1) [[PTR15]], align 1
; CHECK-OPT-NEXT:    ret void
;
; CHECK-NOOPT-LABEL: define amdgpu_kernel void @combine_scalar_selects_v16i8(
; CHECK-NOOPT-SAME: ptr addrspace(1) [[OUT:%.*]], <4 x i32> [[BUFFER_RESOURCE:%.*]], i32 [[OFFSET:%.*]], i1 [[VALID:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NOOPT-NEXT:  [[ENTRY:.*:]]
; CHECK-NOOPT-NEXT:    [[LOADED:%.*]] = call <4 x i32> @llvm.amdgcn.raw.buffer.load.v4i32(<4 x i32> [[BUFFER_RESOURCE]], i32 [[OFFSET]], i32 0, i32 0)
; CHECK-NOOPT-NEXT:    [[BYTES:%.*]] = bitcast <4 x i32> [[LOADED]] to <16 x i8>
; CHECK-NOOPT-NEXT:    [[E0:%.*]] = extractelement <16 x i8> [[BYTES]], i64 0
; CHECK-NOOPT-NEXT:    [[E1:%.*]] = extractelement <16 x i8> [[BYTES]], i64 1
; CHECK-NOOPT-NEXT:    [[E2:%.*]] = extractelement <16 x i8> [[BYTES]], i64 2
; CHECK-NOOPT-NEXT:    [[E3:%.*]] = extractelement <16 x i8> [[BYTES]], i64 3
; CHECK-NOOPT-NEXT:    [[E4:%.*]] = extractelement <16 x i8> [[BYTES]], i64 4
; CHECK-NOOPT-NEXT:    [[E5:%.*]] = extractelement <16 x i8> [[BYTES]], i64 5
; CHECK-NOOPT-NEXT:    [[E6:%.*]] = extractelement <16 x i8> [[BYTES]], i64 6
; CHECK-NOOPT-NEXT:    [[E7:%.*]] = extractelement <16 x i8> [[BYTES]], i64 7
; CHECK-NOOPT-NEXT:    [[E8:%.*]] = extractelement <16 x i8> [[BYTES]], i64 8
; CHECK-NOOPT-NEXT:    [[E9:%.*]] = extractelement <16 x i8> [[BYTES]], i64 9
; CHECK-NOOPT-NEXT:    [[E10:%.*]] = extractelement <16 x i8> [[BYTES]], i64 10
; CHECK-NOOPT-NEXT:    [[E11:%.*]] = extractelement <16 x i8> [[BYTES]], i64 11
; CHECK-NOOPT-NEXT:    [[E12:%.*]] = extractelement <16 x i8> [[BYTES]], i64 12
; CHECK-NOOPT-NEXT:    [[E13:%.*]] = extractelement <16 x i8> [[BYTES]], i64 13
; CHECK-NOOPT-NEXT:    [[E14:%.*]] = extractelement <16 x i8> [[BYTES]], i64 14
; CHECK-NOOPT-NEXT:    [[E15:%.*]] = extractelement <16 x i8> [[BYTES]], i64 15
; CHECK-NOOPT-NEXT:    [[S0:%.*]] = select i1 [[VALID]], i8 [[E0]], i8 0
; CHECK-NOOPT-NEXT:    [[S1:%.*]] = select i1 [[VALID]], i8 [[E1]], i8 0
; CHECK-NOOPT-NEXT:    [[S2:%.*]] = select i1 [[VALID]], i8 [[E2]], i8 0
; CHECK-NOOPT-NEXT:    [[S3:%.*]] = select i1 [[VALID]], i8 [[E3]], i8 0
; CHECK-NOOPT-NEXT:    [[S4:%.*]] = select i1 [[VALID]], i8 [[E4]], i8 0
; CHECK-NOOPT-NEXT:    [[S5:%.*]] = select i1 [[VALID]], i8 [[E5]], i8 0
; CHECK-NOOPT-NEXT:    [[S6:%.*]] = select i1 [[VALID]], i8 [[E6]], i8 0
; CHECK-NOOPT-NEXT:    [[S7:%.*]] = select i1 [[VALID]], i8 [[E7]], i8 0
; CHECK-NOOPT-NEXT:    [[S8:%.*]] = select i1 [[VALID]], i8 [[E8]], i8 0
; CHECK-NOOPT-NEXT:    [[S9:%.*]] = select i1 [[VALID]], i8 [[E9]], i8 0
; CHECK-NOOPT-NEXT:    [[S10:%.*]] = select i1 [[VALID]], i8 [[E10]], i8 0
; CHECK-NOOPT-NEXT:    [[S11:%.*]] = select i1 [[VALID]], i8 [[E11]], i8 0
; CHECK-NOOPT-NEXT:    [[S12:%.*]] = select i1 [[VALID]], i8 [[E12]], i8 0
; CHECK-NOOPT-NEXT:    [[S13:%.*]] = select i1 [[VALID]], i8 [[E13]], i8 0
; CHECK-NOOPT-NEXT:    [[S14:%.*]] = select i1 [[VALID]], i8 [[E14]], i8 0
; CHECK-NOOPT-NEXT:    [[S15:%.*]] = select i1 [[VALID]], i8 [[E15]], i8 0
; CHECK-NOOPT-NEXT:    store i8 [[S0]], ptr addrspace(1) [[OUT]], align 1
; CHECK-NOOPT-NEXT:    [[PTR1:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 1
; CHECK-NOOPT-NEXT:    store i8 [[S1]], ptr addrspace(1) [[PTR1]], align 1
; CHECK-NOOPT-NEXT:    [[PTR2:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 2
; CHECK-NOOPT-NEXT:    store i8 [[S2]], ptr addrspace(1) [[PTR2]], align 1
; CHECK-NOOPT-NEXT:    [[PTR3:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 3
; CHECK-NOOPT-NEXT:    store i8 [[S3]], ptr addrspace(1) [[PTR3]], align 1
; CHECK-NOOPT-NEXT:    [[PTR4:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 4
; CHECK-NOOPT-NEXT:    store i8 [[S4]], ptr addrspace(1) [[PTR4]], align 1
; CHECK-NOOPT-NEXT:    [[PTR5:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 5
; CHECK-NOOPT-NEXT:    store i8 [[S5]], ptr addrspace(1) [[PTR5]], align 1
; CHECK-NOOPT-NEXT:    [[PTR6:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 6
; CHECK-NOOPT-NEXT:    store i8 [[S6]], ptr addrspace(1) [[PTR6]], align 1
; CHECK-NOOPT-NEXT:    [[PTR7:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 7
; CHECK-NOOPT-NEXT:    store i8 [[S7]], ptr addrspace(1) [[PTR7]], align 1
; CHECK-NOOPT-NEXT:    [[PTR8:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 8
; CHECK-NOOPT-NEXT:    store i8 [[S8]], ptr addrspace(1) [[PTR8]], align 1
; CHECK-NOOPT-NEXT:    [[PTR9:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 9
; CHECK-NOOPT-NEXT:    store i8 [[S9]], ptr addrspace(1) [[PTR9]], align 1
; CHECK-NOOPT-NEXT:    [[PTR10:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 10
; CHECK-NOOPT-NEXT:    store i8 [[S10]], ptr addrspace(1) [[PTR10]], align 1
; CHECK-NOOPT-NEXT:    [[PTR11:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 11
; CHECK-NOOPT-NEXT:    store i8 [[S11]], ptr addrspace(1) [[PTR11]], align 1
; CHECK-NOOPT-NEXT:    [[PTR12:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 12
; CHECK-NOOPT-NEXT:    store i8 [[S12]], ptr addrspace(1) [[PTR12]], align 1
; CHECK-NOOPT-NEXT:    [[PTR13:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 13
; CHECK-NOOPT-NEXT:    store i8 [[S13]], ptr addrspace(1) [[PTR13]], align 1
; CHECK-NOOPT-NEXT:    [[PTR14:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 14
; CHECK-NOOPT-NEXT:    store i8 [[S14]], ptr addrspace(1) [[PTR14]], align 1
; CHECK-NOOPT-NEXT:    [[PTR15:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 15
; CHECK-NOOPT-NEXT:    store i8 [[S15]], ptr addrspace(1) [[PTR15]], align 1
; CHECK-NOOPT-NEXT:    ret void
;
  ptr addrspace(1) %out,
  <4 x i32> %buffer_resource,
  i32 %offset,
  i1 %valid
) {
entry:
  %loaded = call <4 x i32> @llvm.amdgcn.raw.buffer.load.v4i32(<4 x i32> %buffer_resource, i32 %offset, i32 0, i32 0)
  %bytes = bitcast <4 x i32> %loaded to <16 x i8>

  %e0 = extractelement <16 x i8> %bytes, i64 0
  %e1 = extractelement <16 x i8> %bytes, i64 1
  %e2 = extractelement <16 x i8> %bytes, i64 2
  %e3 = extractelement <16 x i8> %bytes, i64 3
  %e4 = extractelement <16 x i8> %bytes, i64 4
  %e5 = extractelement <16 x i8> %bytes, i64 5
  %e6 = extractelement <16 x i8> %bytes, i64 6
  %e7 = extractelement <16 x i8> %bytes, i64 7
  %e8 = extractelement <16 x i8> %bytes, i64 8
  %e9 = extractelement <16 x i8> %bytes, i64 9
  %e10 = extractelement <16 x i8> %bytes, i64 10
  %e11 = extractelement <16 x i8> %bytes, i64 11
  %e12 = extractelement <16 x i8> %bytes, i64 12
  %e13 = extractelement <16 x i8> %bytes, i64 13
  %e14 = extractelement <16 x i8> %bytes, i64 14
  %e15 = extractelement <16 x i8> %bytes, i64 15

  %s0 = select i1 %valid, i8 %e0, i8 0
  %s1 = select i1 %valid, i8 %e1, i8 0
  %s2 = select i1 %valid, i8 %e2, i8 0
  %s3 = select i1 %valid, i8 %e3, i8 0
  %s4 = select i1 %valid, i8 %e4, i8 0
  %s5 = select i1 %valid, i8 %e5, i8 0
  %s6 = select i1 %valid, i8 %e6, i8 0
  %s7 = select i1 %valid, i8 %e7, i8 0
  %s8 = select i1 %valid, i8 %e8, i8 0
  %s9 = select i1 %valid, i8 %e9, i8 0
  %s10 = select i1 %valid, i8 %e10, i8 0
  %s11 = select i1 %valid, i8 %e11, i8 0
  %s12 = select i1 %valid, i8 %e12, i8 0
  %s13 = select i1 %valid, i8 %e13, i8 0
  %s14 = select i1 %valid, i8 %e14, i8 0
  %s15 = select i1 %valid, i8 %e15, i8 0

  store i8 %s0, ptr addrspace(1) %out, align 1
  %ptr1 = getelementptr i8, ptr addrspace(1) %out, i64 1
  store i8 %s1, ptr addrspace(1) %ptr1, align 1
  %ptr2 = getelementptr i8, ptr addrspace(1) %out, i64 2
  store i8 %s2, ptr addrspace(1) %ptr2, align 1
  %ptr3 = getelementptr i8, ptr addrspace(1) %out, i64 3
  store i8 %s3, ptr addrspace(1) %ptr3, align 1
  %ptr4 = getelementptr i8, ptr addrspace(1) %out, i64 4
  store i8 %s4, ptr addrspace(1) %ptr4, align 1
  %ptr5 = getelementptr i8, ptr addrspace(1) %out, i64 5
  store i8 %s5, ptr addrspace(1) %ptr5, align 1
  %ptr6 = getelementptr i8, ptr addrspace(1) %out, i64 6
  store i8 %s6, ptr addrspace(1) %ptr6, align 1
  %ptr7 = getelementptr i8, ptr addrspace(1) %out, i64 7
  store i8 %s7, ptr addrspace(1) %ptr7, align 1
  %ptr8 = getelementptr i8, ptr addrspace(1) %out, i64 8
  store i8 %s8, ptr addrspace(1) %ptr8, align 1
  %ptr9 = getelementptr i8, ptr addrspace(1) %out, i64 9
  store i8 %s9, ptr addrspace(1) %ptr9, align 1
  %ptr10 = getelementptr i8, ptr addrspace(1) %out, i64 10
  store i8 %s10, ptr addrspace(1) %ptr10, align 1
  %ptr11 = getelementptr i8, ptr addrspace(1) %out, i64 11
  store i8 %s11, ptr addrspace(1) %ptr11, align 1
  %ptr12 = getelementptr i8, ptr addrspace(1) %out, i64 12
  store i8 %s12, ptr addrspace(1) %ptr12, align 1
  %ptr13 = getelementptr i8, ptr addrspace(1) %out, i64 13
  store i8 %s13, ptr addrspace(1) %ptr13, align 1
  %ptr14 = getelementptr i8, ptr addrspace(1) %out, i64 14
  store i8 %s14, ptr addrspace(1) %ptr14, align 1
  %ptr15 = getelementptr i8, ptr addrspace(1) %out, i64 15
  store i8 %s15, ptr addrspace(1) %ptr15, align 1

  ret void
}

; Test with v8i8 from v2i32 (smaller vector)
define amdgpu_kernel void @combine_scalar_selects_v8i8(
;
; CHECK-OPT-LABEL: define amdgpu_kernel void @combine_scalar_selects_v8i8(
; CHECK-OPT-SAME: ptr addrspace(1) [[OUT:%.*]], <2 x i32> [[SRC:%.*]], i1 [[COND:%.*]]) #[[ATTR0]] {
; CHECK-OPT-NEXT:  [[ENTRY:.*:]]
; CHECK-OPT-NEXT:    [[COMBINED_SEL:%.*]] = select i1 [[COND]], <2 x i32> [[SRC]], <2 x i32> zeroinitializer
; CHECK-OPT-NEXT:    [[COMBINED_BC:%.*]] = bitcast <2 x i32> [[COMBINED_SEL]] to <8 x i8>
; CHECK-OPT-NEXT:    [[TMP0:%.*]] = extractelement <8 x i8> [[COMBINED_BC]], i64 0
; CHECK-OPT-NEXT:    [[TMP3:%.*]] = extractelement <8 x i8> [[COMBINED_BC]], i64 1
; CHECK-OPT-NEXT:    [[TMP5:%.*]] = extractelement <8 x i8> [[COMBINED_BC]], i64 2
; CHECK-OPT-NEXT:    [[TMP7:%.*]] = extractelement <8 x i8> [[COMBINED_BC]], i64 3
; CHECK-OPT-NEXT:    [[TMP2:%.*]] = extractelement <8 x i8> [[COMBINED_BC]], i64 4
; CHECK-OPT-NEXT:    [[TMP4:%.*]] = extractelement <8 x i8> [[COMBINED_BC]], i64 5
; CHECK-OPT-NEXT:    [[TMP6:%.*]] = extractelement <8 x i8> [[COMBINED_BC]], i64 6
; CHECK-OPT-NEXT:    [[TMP1:%.*]] = extractelement <8 x i8> [[COMBINED_BC]], i64 7
; CHECK-OPT-NEXT:    store i8 [[TMP0]], ptr addrspace(1) [[OUT]], align 1
; CHECK-OPT-NEXT:    [[PTR1:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 1
; CHECK-OPT-NEXT:    store i8 [[TMP3]], ptr addrspace(1) [[PTR1]], align 1
; CHECK-OPT-NEXT:    [[PTR2:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 2
; CHECK-OPT-NEXT:    store i8 [[TMP5]], ptr addrspace(1) [[PTR2]], align 1
; CHECK-OPT-NEXT:    [[PTR3:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 3
; CHECK-OPT-NEXT:    store i8 [[TMP7]], ptr addrspace(1) [[PTR3]], align 1
; CHECK-OPT-NEXT:    [[PTR4:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 4
; CHECK-OPT-NEXT:    store i8 [[TMP2]], ptr addrspace(1) [[PTR4]], align 1
; CHECK-OPT-NEXT:    [[PTR5:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 5
; CHECK-OPT-NEXT:    store i8 [[TMP4]], ptr addrspace(1) [[PTR5]], align 1
; CHECK-OPT-NEXT:    [[PTR6:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 6
; CHECK-OPT-NEXT:    store i8 [[TMP6]], ptr addrspace(1) [[PTR6]], align 1
; CHECK-OPT-NEXT:    [[PTR7:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 7
; CHECK-OPT-NEXT:    store i8 [[TMP1]], ptr addrspace(1) [[PTR7]], align 1
; CHECK-OPT-NEXT:    ret void
;
; CHECK-NOOPT-LABEL: define amdgpu_kernel void @combine_scalar_selects_v8i8(
; CHECK-NOOPT-SAME: ptr addrspace(1) [[OUT:%.*]], <2 x i32> [[SRC:%.*]], i1 [[COND:%.*]]) #[[ATTR0]] {
; CHECK-NOOPT-NEXT:  [[ENTRY:.*:]]
; CHECK-NOOPT-NEXT:    [[BYTES:%.*]] = bitcast <2 x i32> [[SRC]] to <8 x i8>
; CHECK-NOOPT-NEXT:    [[E0:%.*]] = extractelement <8 x i8> [[BYTES]], i64 0
; CHECK-NOOPT-NEXT:    [[E1:%.*]] = extractelement <8 x i8> [[BYTES]], i64 1
; CHECK-NOOPT-NEXT:    [[E2:%.*]] = extractelement <8 x i8> [[BYTES]], i64 2
; CHECK-NOOPT-NEXT:    [[E3:%.*]] = extractelement <8 x i8> [[BYTES]], i64 3
; CHECK-NOOPT-NEXT:    [[E4:%.*]] = extractelement <8 x i8> [[BYTES]], i64 4
; CHECK-NOOPT-NEXT:    [[E5:%.*]] = extractelement <8 x i8> [[BYTES]], i64 5
; CHECK-NOOPT-NEXT:    [[E6:%.*]] = extractelement <8 x i8> [[BYTES]], i64 6
; CHECK-NOOPT-NEXT:    [[E7:%.*]] = extractelement <8 x i8> [[BYTES]], i64 7
; CHECK-NOOPT-NEXT:    [[S0:%.*]] = select i1 [[COND]], i8 [[E0]], i8 0
; CHECK-NOOPT-NEXT:    [[S1:%.*]] = select i1 [[COND]], i8 [[E1]], i8 0
; CHECK-NOOPT-NEXT:    [[S2:%.*]] = select i1 [[COND]], i8 [[E2]], i8 0
; CHECK-NOOPT-NEXT:    [[S3:%.*]] = select i1 [[COND]], i8 [[E3]], i8 0
; CHECK-NOOPT-NEXT:    [[S4:%.*]] = select i1 [[COND]], i8 [[E4]], i8 0
; CHECK-NOOPT-NEXT:    [[S5:%.*]] = select i1 [[COND]], i8 [[E5]], i8 0
; CHECK-NOOPT-NEXT:    [[S6:%.*]] = select i1 [[COND]], i8 [[E6]], i8 0
; CHECK-NOOPT-NEXT:    [[S7:%.*]] = select i1 [[COND]], i8 [[E7]], i8 0
; CHECK-NOOPT-NEXT:    store i8 [[S0]], ptr addrspace(1) [[OUT]], align 1
; CHECK-NOOPT-NEXT:    [[PTR1:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 1
; CHECK-NOOPT-NEXT:    store i8 [[S1]], ptr addrspace(1) [[PTR1]], align 1
; CHECK-NOOPT-NEXT:    [[PTR2:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 2
; CHECK-NOOPT-NEXT:    store i8 [[S2]], ptr addrspace(1) [[PTR2]], align 1
; CHECK-NOOPT-NEXT:    [[PTR3:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 3
; CHECK-NOOPT-NEXT:    store i8 [[S3]], ptr addrspace(1) [[PTR3]], align 1
; CHECK-NOOPT-NEXT:    [[PTR4:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 4
; CHECK-NOOPT-NEXT:    store i8 [[S4]], ptr addrspace(1) [[PTR4]], align 1
; CHECK-NOOPT-NEXT:    [[PTR5:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 5
; CHECK-NOOPT-NEXT:    store i8 [[S5]], ptr addrspace(1) [[PTR5]], align 1
; CHECK-NOOPT-NEXT:    [[PTR6:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 6
; CHECK-NOOPT-NEXT:    store i8 [[S6]], ptr addrspace(1) [[PTR6]], align 1
; CHECK-NOOPT-NEXT:    [[PTR7:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 7
; CHECK-NOOPT-NEXT:    store i8 [[S7]], ptr addrspace(1) [[PTR7]], align 1
; CHECK-NOOPT-NEXT:    ret void
;
  ptr addrspace(1) %out,
  <2 x i32> %src,
  i1 %cond
) {
entry:
  %bytes = bitcast <2 x i32> %src to <8 x i8>
  %e0 = extractelement <8 x i8> %bytes, i64 0
  %e1 = extractelement <8 x i8> %bytes, i64 1
  %e2 = extractelement <8 x i8> %bytes, i64 2
  %e3 = extractelement <8 x i8> %bytes, i64 3
  %e4 = extractelement <8 x i8> %bytes, i64 4
  %e5 = extractelement <8 x i8> %bytes, i64 5
  %e6 = extractelement <8 x i8> %bytes, i64 6
  %e7 = extractelement <8 x i8> %bytes, i64 7
  %s0 = select i1 %cond, i8 %e0, i8 0
  %s1 = select i1 %cond, i8 %e1, i8 0
  %s2 = select i1 %cond, i8 %e2, i8 0
  %s3 = select i1 %cond, i8 %e3, i8 0
  %s4 = select i1 %cond, i8 %e4, i8 0
  %s5 = select i1 %cond, i8 %e5, i8 0
  %s6 = select i1 %cond, i8 %e6, i8 0
  %s7 = select i1 %cond, i8 %e7, i8 0
  store i8 %s0, ptr addrspace(1) %out, align 1
  %ptr1 = getelementptr i8, ptr addrspace(1) %out, i64 1
  store i8 %s1, ptr addrspace(1) %ptr1, align 1
  %ptr2 = getelementptr i8, ptr addrspace(1) %out, i64 2
  store i8 %s2, ptr addrspace(1) %ptr2, align 1
  %ptr3 = getelementptr i8, ptr addrspace(1) %out, i64 3
  store i8 %s3, ptr addrspace(1) %ptr3, align 1
  %ptr4 = getelementptr i8, ptr addrspace(1) %out, i64 4
  store i8 %s4, ptr addrspace(1) %ptr4, align 1
  %ptr5 = getelementptr i8, ptr addrspace(1) %out, i64 5
  store i8 %s5, ptr addrspace(1) %ptr5, align 1
  %ptr6 = getelementptr i8, ptr addrspace(1) %out, i64 6
  store i8 %s6, ptr addrspace(1) %ptr6, align 1
  %ptr7 = getelementptr i8, ptr addrspace(1) %out, i64 7
  store i8 %s7, ptr addrspace(1) %ptr7, align 1
  ret void
}

; Test partial coverage: 10 out of 16 elements (should still combine, >= half)
define amdgpu_kernel void @combine_partial_selects(
;
; CHECK-OPT-LABEL: define amdgpu_kernel void @combine_partial_selects(
; CHECK-OPT-SAME: ptr addrspace(1) [[OUT:%.*]], <4 x i32> [[SRC:%.*]], i1 [[COND:%.*]]) #[[ATTR0]] {
; CHECK-OPT-NEXT:  [[ENTRY:.*:]]
; CHECK-OPT-NEXT:    [[COMBINED_SEL:%.*]] = select i1 [[COND]], <4 x i32> [[SRC]], <4 x i32> zeroinitializer
; CHECK-OPT-NEXT:    [[COMBINED_BC:%.*]] = bitcast <4 x i32> [[COMBINED_SEL]] to <16 x i8>
; CHECK-OPT-NEXT:    [[TMP0:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 0
; CHECK-OPT-NEXT:    [[TMP3:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 1
; CHECK-OPT-NEXT:    [[TMP6:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 2
; CHECK-OPT-NEXT:    [[TMP9:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 3
; CHECK-OPT-NEXT:    [[TMP2:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 4
; CHECK-OPT-NEXT:    [[TMP5:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 5
; CHECK-OPT-NEXT:    [[TMP8:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 6
; CHECK-OPT-NEXT:    [[TMP1:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 7
; CHECK-OPT-NEXT:    [[TMP4:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 8
; CHECK-OPT-NEXT:    [[TMP7:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 9
; CHECK-OPT-NEXT:    store i8 [[TMP0]], ptr addrspace(1) [[OUT]], align 1
; CHECK-OPT-NEXT:    [[PTR1:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 1
; CHECK-OPT-NEXT:    store i8 [[TMP3]], ptr addrspace(1) [[PTR1]], align 1
; CHECK-OPT-NEXT:    [[PTR2:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 2
; CHECK-OPT-NEXT:    store i8 [[TMP6]], ptr addrspace(1) [[PTR2]], align 1
; CHECK-OPT-NEXT:    [[PTR3:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 3
; CHECK-OPT-NEXT:    store i8 [[TMP9]], ptr addrspace(1) [[PTR3]], align 1
; CHECK-OPT-NEXT:    [[PTR4:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 4
; CHECK-OPT-NEXT:    store i8 [[TMP2]], ptr addrspace(1) [[PTR4]], align 1
; CHECK-OPT-NEXT:    [[PTR5:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 5
; CHECK-OPT-NEXT:    store i8 [[TMP5]], ptr addrspace(1) [[PTR5]], align 1
; CHECK-OPT-NEXT:    [[PTR6:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 6
; CHECK-OPT-NEXT:    store i8 [[TMP8]], ptr addrspace(1) [[PTR6]], align 1
; CHECK-OPT-NEXT:    [[PTR7:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 7
; CHECK-OPT-NEXT:    store i8 [[TMP1]], ptr addrspace(1) [[PTR7]], align 1
; CHECK-OPT-NEXT:    [[PTR8:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 8
; CHECK-OPT-NEXT:    store i8 [[TMP4]], ptr addrspace(1) [[PTR8]], align 1
; CHECK-OPT-NEXT:    [[PTR9:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 9
; CHECK-OPT-NEXT:    store i8 [[TMP7]], ptr addrspace(1) [[PTR9]], align 1
; CHECK-OPT-NEXT:    ret void
;
; CHECK-NOOPT-LABEL: define amdgpu_kernel void @combine_partial_selects(
; CHECK-NOOPT-SAME: ptr addrspace(1) [[OUT:%.*]], <4 x i32> [[SRC:%.*]], i1 [[COND:%.*]]) #[[ATTR0]] {
; CHECK-NOOPT-NEXT:  [[ENTRY:.*:]]
; CHECK-NOOPT-NEXT:    [[BYTES:%.*]] = bitcast <4 x i32> [[SRC]] to <16 x i8>
; CHECK-NOOPT-NEXT:    [[E0:%.*]] = extractelement <16 x i8> [[BYTES]], i64 0
; CHECK-NOOPT-NEXT:    [[E1:%.*]] = extractelement <16 x i8> [[BYTES]], i64 1
; CHECK-NOOPT-NEXT:    [[E2:%.*]] = extractelement <16 x i8> [[BYTES]], i64 2
; CHECK-NOOPT-NEXT:    [[E3:%.*]] = extractelement <16 x i8> [[BYTES]], i64 3
; CHECK-NOOPT-NEXT:    [[E4:%.*]] = extractelement <16 x i8> [[BYTES]], i64 4
; CHECK-NOOPT-NEXT:    [[E5:%.*]] = extractelement <16 x i8> [[BYTES]], i64 5
; CHECK-NOOPT-NEXT:    [[E6:%.*]] = extractelement <16 x i8> [[BYTES]], i64 6
; CHECK-NOOPT-NEXT:    [[E7:%.*]] = extractelement <16 x i8> [[BYTES]], i64 7
; CHECK-NOOPT-NEXT:    [[E8:%.*]] = extractelement <16 x i8> [[BYTES]], i64 8
; CHECK-NOOPT-NEXT:    [[E9:%.*]] = extractelement <16 x i8> [[BYTES]], i64 9
; CHECK-NOOPT-NEXT:    [[S0:%.*]] = select i1 [[COND]], i8 [[E0]], i8 0
; CHECK-NOOPT-NEXT:    [[S1:%.*]] = select i1 [[COND]], i8 [[E1]], i8 0
; CHECK-NOOPT-NEXT:    [[S2:%.*]] = select i1 [[COND]], i8 [[E2]], i8 0
; CHECK-NOOPT-NEXT:    [[S3:%.*]] = select i1 [[COND]], i8 [[E3]], i8 0
; CHECK-NOOPT-NEXT:    [[S4:%.*]] = select i1 [[COND]], i8 [[E4]], i8 0
; CHECK-NOOPT-NEXT:    [[S5:%.*]] = select i1 [[COND]], i8 [[E5]], i8 0
; CHECK-NOOPT-NEXT:    [[S6:%.*]] = select i1 [[COND]], i8 [[E6]], i8 0
; CHECK-NOOPT-NEXT:    [[S7:%.*]] = select i1 [[COND]], i8 [[E7]], i8 0
; CHECK-NOOPT-NEXT:    [[S8:%.*]] = select i1 [[COND]], i8 [[E8]], i8 0
; CHECK-NOOPT-NEXT:    [[S9:%.*]] = select i1 [[COND]], i8 [[E9]], i8 0
; CHECK-NOOPT-NEXT:    store i8 [[S0]], ptr addrspace(1) [[OUT]], align 1
; CHECK-NOOPT-NEXT:    [[PTR1:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 1
; CHECK-NOOPT-NEXT:    store i8 [[S1]], ptr addrspace(1) [[PTR1]], align 1
; CHECK-NOOPT-NEXT:    [[PTR2:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 2
; CHECK-NOOPT-NEXT:    store i8 [[S2]], ptr addrspace(1) [[PTR2]], align 1
; CHECK-NOOPT-NEXT:    [[PTR3:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 3
; CHECK-NOOPT-NEXT:    store i8 [[S3]], ptr addrspace(1) [[PTR3]], align 1
; CHECK-NOOPT-NEXT:    [[PTR4:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 4
; CHECK-NOOPT-NEXT:    store i8 [[S4]], ptr addrspace(1) [[PTR4]], align 1
; CHECK-NOOPT-NEXT:    [[PTR5:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 5
; CHECK-NOOPT-NEXT:    store i8 [[S5]], ptr addrspace(1) [[PTR5]], align 1
; CHECK-NOOPT-NEXT:    [[PTR6:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 6
; CHECK-NOOPT-NEXT:    store i8 [[S6]], ptr addrspace(1) [[PTR6]], align 1
; CHECK-NOOPT-NEXT:    [[PTR7:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 7
; CHECK-NOOPT-NEXT:    store i8 [[S7]], ptr addrspace(1) [[PTR7]], align 1
; CHECK-NOOPT-NEXT:    [[PTR8:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 8
; CHECK-NOOPT-NEXT:    store i8 [[S8]], ptr addrspace(1) [[PTR8]], align 1
; CHECK-NOOPT-NEXT:    [[PTR9:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 9
; CHECK-NOOPT-NEXT:    store i8 [[S9]], ptr addrspace(1) [[PTR9]], align 1
; CHECK-NOOPT-NEXT:    ret void
;
  ptr addrspace(1) %out,
  <4 x i32> %src,
  i1 %cond
) {
entry:
  %bytes = bitcast <4 x i32> %src to <16 x i8>
  ; Only extract and select 10 elements (indices 0-9)
  %e0 = extractelement <16 x i8> %bytes, i64 0
  %e1 = extractelement <16 x i8> %bytes, i64 1
  %e2 = extractelement <16 x i8> %bytes, i64 2
  %e3 = extractelement <16 x i8> %bytes, i64 3
  %e4 = extractelement <16 x i8> %bytes, i64 4
  %e5 = extractelement <16 x i8> %bytes, i64 5
  %e6 = extractelement <16 x i8> %bytes, i64 6
  %e7 = extractelement <16 x i8> %bytes, i64 7
  %e8 = extractelement <16 x i8> %bytes, i64 8
  %e9 = extractelement <16 x i8> %bytes, i64 9
  %s0 = select i1 %cond, i8 %e0, i8 0
  %s1 = select i1 %cond, i8 %e1, i8 0
  %s2 = select i1 %cond, i8 %e2, i8 0
  %s3 = select i1 %cond, i8 %e3, i8 0
  %s4 = select i1 %cond, i8 %e4, i8 0
  %s5 = select i1 %cond, i8 %e5, i8 0
  %s6 = select i1 %cond, i8 %e6, i8 0
  %s7 = select i1 %cond, i8 %e7, i8 0
  %s8 = select i1 %cond, i8 %e8, i8 0
  %s9 = select i1 %cond, i8 %e9, i8 0
  store i8 %s0, ptr addrspace(1) %out, align 1
  %ptr1 = getelementptr i8, ptr addrspace(1) %out, i64 1
  store i8 %s1, ptr addrspace(1) %ptr1, align 1
  %ptr2 = getelementptr i8, ptr addrspace(1) %out, i64 2
  store i8 %s2, ptr addrspace(1) %ptr2, align 1
  %ptr3 = getelementptr i8, ptr addrspace(1) %out, i64 3
  store i8 %s3, ptr addrspace(1) %ptr3, align 1
  %ptr4 = getelementptr i8, ptr addrspace(1) %out, i64 4
  store i8 %s4, ptr addrspace(1) %ptr4, align 1
  %ptr5 = getelementptr i8, ptr addrspace(1) %out, i64 5
  store i8 %s5, ptr addrspace(1) %ptr5, align 1
  %ptr6 = getelementptr i8, ptr addrspace(1) %out, i64 6
  store i8 %s6, ptr addrspace(1) %ptr6, align 1
  %ptr7 = getelementptr i8, ptr addrspace(1) %out, i64 7
  store i8 %s7, ptr addrspace(1) %ptr7, align 1
  %ptr8 = getelementptr i8, ptr addrspace(1) %out, i64 8
  store i8 %s8, ptr addrspace(1) %ptr8, align 1
  %ptr9 = getelementptr i8, ptr addrspace(1) %out, i64 9
  store i8 %s9, ptr addrspace(1) %ptr9, align 1
  ret void
}

; Negative test: should not combine if false value is not zero
define amdgpu_kernel void @no_combine_non_zero_false(
;
; CHECK-LABEL: define amdgpu_kernel void @no_combine_non_zero_false(
; CHECK-SAME: ptr addrspace(1) [[OUT:%.*]], <4 x i32> [[BUFFER_RESOURCE:%.*]], i32 [[OFFSET:%.*]], i1 [[VALID:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[LOADED:%.*]] = call <4 x i32> @llvm.amdgcn.raw.buffer.load.v4i32(<4 x i32> [[BUFFER_RESOURCE]], i32 [[OFFSET]], i32 0, i32 0)
; CHECK-NEXT:    [[BYTES:%.*]] = bitcast <4 x i32> [[LOADED]] to <16 x i8>
; CHECK-NEXT:    [[E0:%.*]] = extractelement <16 x i8> [[BYTES]], i64 0
; CHECK-NEXT:    [[S0:%.*]] = select i1 [[VALID]], i8 [[E0]], i8 1
; CHECK-NEXT:    store i8 [[S0]], ptr addrspace(1) [[OUT]], align 1
; CHECK-NEXT:    ret void
;
  ptr addrspace(1) %out,
  <4 x i32> %buffer_resource,
  i32 %offset,
  i1 %valid
) {
entry:
  %loaded = call <4 x i32> @llvm.amdgcn.raw.buffer.load.v4i32(<4 x i32> %buffer_resource, i32 %offset, i32 0, i32 0)
  %bytes = bitcast <4 x i32> %loaded to <16 x i8>
  %e0 = extractelement <16 x i8> %bytes, i64 0
  %s0 = select i1 %valid, i8 %e0, i8 1  ; false value is 1, not 0
  store i8 %s0, ptr addrspace(1) %out, align 1
  ret void
}

; Negative test: too few selects (only 4 out of 16, less than half)
define amdgpu_kernel void @no_combine_too_few_selects(
;
; CHECK-OPT-LABEL: define amdgpu_kernel void @no_combine_too_few_selects(
; CHECK-OPT-SAME: ptr addrspace(1) [[OUT:%.*]], <4 x i32> [[SRC:%.*]], i1 [[COND:%.*]]) #[[ATTR0]] {
; CHECK-OPT-NEXT:  [[ENTRY:.*:]]
; CHECK-OPT-NEXT:    [[SEL_BC:%.*]] = select i1 [[COND]], <4 x i32> [[SRC]], <4 x i32> zeroinitializer
; CHECK-OPT-NEXT:    [[BYTES:%.*]] = bitcast <4 x i32> [[SEL_BC]] to <16 x i8>
; CHECK-OPT-NEXT:    [[E0:%.*]] = extractelement <16 x i8> [[BYTES]], i64 0
; CHECK-OPT-NEXT:    [[S1:%.*]] = extractelement <16 x i8> [[BYTES]], i64 1
; CHECK-OPT-NEXT:    [[S2:%.*]] = extractelement <16 x i8> [[BYTES]], i64 2
; CHECK-OPT-NEXT:    [[S3:%.*]] = extractelement <16 x i8> [[BYTES]], i64 3
; CHECK-OPT-NEXT:    store i8 [[E0]], ptr addrspace(1) [[OUT]], align 1
; CHECK-OPT-NEXT:    [[PTR1:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 1
; CHECK-OPT-NEXT:    store i8 [[S1]], ptr addrspace(1) [[PTR1]], align 1
; CHECK-OPT-NEXT:    [[PTR2:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 2
; CHECK-OPT-NEXT:    store i8 [[S2]], ptr addrspace(1) [[PTR2]], align 1
; CHECK-OPT-NEXT:    [[PTR3:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 3
; CHECK-OPT-NEXT:    store i8 [[S3]], ptr addrspace(1) [[PTR3]], align 1
; CHECK-OPT-NEXT:    ret void
;
; CHECK-NOOPT-LABEL: define amdgpu_kernel void @no_combine_too_few_selects(
; CHECK-NOOPT-SAME: ptr addrspace(1) [[OUT:%.*]], <4 x i32> [[SRC:%.*]], i1 [[COND:%.*]]) #[[ATTR0]] {
; CHECK-NOOPT-NEXT:  [[ENTRY:.*:]]
; CHECK-NOOPT-NEXT:    [[BYTES:%.*]] = bitcast <4 x i32> [[SRC]] to <16 x i8>
; CHECK-NOOPT-NEXT:    [[E0:%.*]] = extractelement <16 x i8> [[BYTES]], i64 0
; CHECK-NOOPT-NEXT:    [[E1:%.*]] = extractelement <16 x i8> [[BYTES]], i64 1
; CHECK-NOOPT-NEXT:    [[E2:%.*]] = extractelement <16 x i8> [[BYTES]], i64 2
; CHECK-NOOPT-NEXT:    [[E3:%.*]] = extractelement <16 x i8> [[BYTES]], i64 3
; CHECK-NOOPT-NEXT:    [[S0:%.*]] = select i1 [[COND]], i8 [[E0]], i8 0
; CHECK-NOOPT-NEXT:    [[S1:%.*]] = select i1 [[COND]], i8 [[E1]], i8 0
; CHECK-NOOPT-NEXT:    [[S2:%.*]] = select i1 [[COND]], i8 [[E2]], i8 0
; CHECK-NOOPT-NEXT:    [[S3:%.*]] = select i1 [[COND]], i8 [[E3]], i8 0
; CHECK-NOOPT-NEXT:    store i8 [[S0]], ptr addrspace(1) [[OUT]], align 1
; CHECK-NOOPT-NEXT:    [[PTR1:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 1
; CHECK-NOOPT-NEXT:    store i8 [[S1]], ptr addrspace(1) [[PTR1]], align 1
; CHECK-NOOPT-NEXT:    [[PTR2:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 2
; CHECK-NOOPT-NEXT:    store i8 [[S2]], ptr addrspace(1) [[PTR2]], align 1
; CHECK-NOOPT-NEXT:    [[PTR3:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 3
; CHECK-NOOPT-NEXT:    store i8 [[S3]], ptr addrspace(1) [[PTR3]], align 1
; CHECK-NOOPT-NEXT:    ret void
;
  ptr addrspace(1) %out,
  <4 x i32> %src,
  i1 %cond
) {
entry:
  %bytes = bitcast <4 x i32> %src to <16 x i8>
  ; Only 4 selects - less than half of 16
  %e0 = extractelement <16 x i8> %bytes, i64 0
  %e1 = extractelement <16 x i8> %bytes, i64 1
  %e2 = extractelement <16 x i8> %bytes, i64 2
  %e3 = extractelement <16 x i8> %bytes, i64 3
  %s0 = select i1 %cond, i8 %e0, i8 0
  %s1 = select i1 %cond, i8 %e1, i8 0
  %s2 = select i1 %cond, i8 %e2, i8 0
  %s3 = select i1 %cond, i8 %e3, i8 0
  store i8 %s0, ptr addrspace(1) %out, align 1
  %ptr1 = getelementptr i8, ptr addrspace(1) %out, i64 1
  store i8 %s1, ptr addrspace(1) %ptr1, align 1
  %ptr2 = getelementptr i8, ptr addrspace(1) %out, i64 2
  store i8 %s2, ptr addrspace(1) %ptr2, align 1
  %ptr3 = getelementptr i8, ptr addrspace(1) %out, i64 3
  store i8 %s3, ptr addrspace(1) %ptr3, align 1
  ret void
}

; Test: extracts have additional unrelated uses (extracts can't be removed)
; The transformation should still be profitable as we reduce v_cndmask count
define amdgpu_kernel void @combine_with_extract_other_uses(
; CHECK-OPT-LABEL: define amdgpu_kernel void @combine_with_extract_other_uses(
; CHECK-OPT-SAME: ptr addrspace(1) [[OUT:%.*]], ptr addrspace(1) [[OUT2:%.*]], <2 x i32> [[SRC:%.*]], i1 [[COND:%.*]]) #[[ATTR0]] {
; CHECK-OPT-NEXT:  [[ENTRY:.*:]]
; CHECK-OPT-NEXT:    [[BYTES:%.*]] = bitcast <2 x i32> [[SRC]] to <8 x i8>
; CHECK-OPT-NEXT:    [[E0:%.*]] = extractelement <8 x i8> [[BYTES]], i64 0
; CHECK-OPT-NEXT:    [[E1:%.*]] = extractelement <8 x i8> [[BYTES]], i64 1
; CHECK-OPT-NEXT:    [[E2:%.*]] = extractelement <8 x i8> [[BYTES]], i64 2
; CHECK-OPT-NEXT:    [[E3:%.*]] = extractelement <8 x i8> [[BYTES]], i64 3
; CHECK-OPT-NEXT:    [[COMBINED_SEL:%.*]] = select i1 [[COND]], <2 x i32> [[SRC]], <2 x i32> zeroinitializer
; CHECK-OPT-NEXT:    [[COMBINED_BC:%.*]] = bitcast <2 x i32> [[COMBINED_SEL]] to <8 x i8>
; CHECK-OPT-NEXT:    [[TMP0:%.*]] = extractelement <8 x i8> [[COMBINED_BC]], i64 0
; CHECK-OPT-NEXT:    [[TMP3:%.*]] = extractelement <8 x i8> [[COMBINED_BC]], i64 1
; CHECK-OPT-NEXT:    [[TMP5:%.*]] = extractelement <8 x i8> [[COMBINED_BC]], i64 2
; CHECK-OPT-NEXT:    [[TMP7:%.*]] = extractelement <8 x i8> [[COMBINED_BC]], i64 3
; CHECK-OPT-NEXT:    [[TMP2:%.*]] = extractelement <8 x i8> [[COMBINED_BC]], i64 4
; CHECK-OPT-NEXT:    [[TMP4:%.*]] = extractelement <8 x i8> [[COMBINED_BC]], i64 5
; CHECK-OPT-NEXT:    [[TMP6:%.*]] = extractelement <8 x i8> [[COMBINED_BC]], i64 6
; CHECK-OPT-NEXT:    [[TMP1:%.*]] = extractelement <8 x i8> [[COMBINED_BC]], i64 7
; CHECK-OPT-NEXT:    store i8 [[TMP0]], ptr addrspace(1) [[OUT]], align 1
; CHECK-OPT-NEXT:    [[PTR1:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 1
; CHECK-OPT-NEXT:    store i8 [[TMP3]], ptr addrspace(1) [[PTR1]], align 1
; CHECK-OPT-NEXT:    [[PTR2:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 2
; CHECK-OPT-NEXT:    store i8 [[TMP5]], ptr addrspace(1) [[PTR2]], align 1
; CHECK-OPT-NEXT:    [[PTR3:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 3
; CHECK-OPT-NEXT:    store i8 [[TMP7]], ptr addrspace(1) [[PTR3]], align 1
; CHECK-OPT-NEXT:    [[PTR4:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 4
; CHECK-OPT-NEXT:    store i8 [[TMP2]], ptr addrspace(1) [[PTR4]], align 1
; CHECK-OPT-NEXT:    [[PTR5:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 5
; CHECK-OPT-NEXT:    store i8 [[TMP4]], ptr addrspace(1) [[PTR5]], align 1
; CHECK-OPT-NEXT:    [[PTR6:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 6
; CHECK-OPT-NEXT:    store i8 [[TMP6]], ptr addrspace(1) [[PTR6]], align 1
; CHECK-OPT-NEXT:    [[PTR7:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 7
; CHECK-OPT-NEXT:    store i8 [[TMP1]], ptr addrspace(1) [[PTR7]], align 1
; CHECK-OPT-NEXT:    [[SUM:%.*]] = add i8 [[E0]], [[E1]]
; CHECK-OPT-NEXT:    [[SUM2:%.*]] = add i8 [[SUM]], [[E2]]
; CHECK-OPT-NEXT:    [[SUM3:%.*]] = add i8 [[SUM2]], [[E3]]
; CHECK-OPT-NEXT:    store i8 [[SUM3]], ptr addrspace(1) [[OUT2]], align 1
; CHECK-OPT-NEXT:    ret void
;
; CHECK-NOOPT-LABEL: define amdgpu_kernel void @combine_with_extract_other_uses(
; CHECK-NOOPT-SAME: ptr addrspace(1) [[OUT:%.*]], ptr addrspace(1) [[OUT2:%.*]], <2 x i32> [[SRC:%.*]], i1 [[COND:%.*]]) #[[ATTR0]] {
; CHECK-NOOPT-NEXT:  [[ENTRY:.*:]]
; CHECK-NOOPT-NEXT:    [[BYTES:%.*]] = bitcast <2 x i32> [[SRC]] to <8 x i8>
; CHECK-NOOPT-NEXT:    [[E0:%.*]] = extractelement <8 x i8> [[BYTES]], i64 0
; CHECK-NOOPT-NEXT:    [[E1:%.*]] = extractelement <8 x i8> [[BYTES]], i64 1
; CHECK-NOOPT-NEXT:    [[E2:%.*]] = extractelement <8 x i8> [[BYTES]], i64 2
; CHECK-NOOPT-NEXT:    [[E3:%.*]] = extractelement <8 x i8> [[BYTES]], i64 3
; CHECK-NOOPT-NEXT:    [[E4:%.*]] = extractelement <8 x i8> [[BYTES]], i64 4
; CHECK-NOOPT-NEXT:    [[E5:%.*]] = extractelement <8 x i8> [[BYTES]], i64 5
; CHECK-NOOPT-NEXT:    [[E6:%.*]] = extractelement <8 x i8> [[BYTES]], i64 6
; CHECK-NOOPT-NEXT:    [[E7:%.*]] = extractelement <8 x i8> [[BYTES]], i64 7
; CHECK-NOOPT-NEXT:    [[S0:%.*]] = select i1 [[COND]], i8 [[E0]], i8 0
; CHECK-NOOPT-NEXT:    [[S1:%.*]] = select i1 [[COND]], i8 [[E1]], i8 0
; CHECK-NOOPT-NEXT:    [[S2:%.*]] = select i1 [[COND]], i8 [[E2]], i8 0
; CHECK-NOOPT-NEXT:    [[S3:%.*]] = select i1 [[COND]], i8 [[E3]], i8 0
; CHECK-NOOPT-NEXT:    [[S4:%.*]] = select i1 [[COND]], i8 [[E4]], i8 0
; CHECK-NOOPT-NEXT:    [[S5:%.*]] = select i1 [[COND]], i8 [[E5]], i8 0
; CHECK-NOOPT-NEXT:    [[S6:%.*]] = select i1 [[COND]], i8 [[E6]], i8 0
; CHECK-NOOPT-NEXT:    [[S7:%.*]] = select i1 [[COND]], i8 [[E7]], i8 0
; CHECK-NOOPT-NEXT:    store i8 [[S0]], ptr addrspace(1) [[OUT]], align 1
; CHECK-NOOPT-NEXT:    [[PTR1:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 1
; CHECK-NOOPT-NEXT:    store i8 [[S1]], ptr addrspace(1) [[PTR1]], align 1
; CHECK-NOOPT-NEXT:    [[PTR2:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 2
; CHECK-NOOPT-NEXT:    store i8 [[S2]], ptr addrspace(1) [[PTR2]], align 1
; CHECK-NOOPT-NEXT:    [[PTR3:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 3
; CHECK-NOOPT-NEXT:    store i8 [[S3]], ptr addrspace(1) [[PTR3]], align 1
; CHECK-NOOPT-NEXT:    [[PTR4:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 4
; CHECK-NOOPT-NEXT:    store i8 [[S4]], ptr addrspace(1) [[PTR4]], align 1
; CHECK-NOOPT-NEXT:    [[PTR5:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 5
; CHECK-NOOPT-NEXT:    store i8 [[S5]], ptr addrspace(1) [[PTR5]], align 1
; CHECK-NOOPT-NEXT:    [[PTR6:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 6
; CHECK-NOOPT-NEXT:    store i8 [[S6]], ptr addrspace(1) [[PTR6]], align 1
; CHECK-NOOPT-NEXT:    [[PTR7:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 7
; CHECK-NOOPT-NEXT:    store i8 [[S7]], ptr addrspace(1) [[PTR7]], align 1
; CHECK-NOOPT-NEXT:    [[SUM:%.*]] = add i8 [[E0]], [[E1]]
; CHECK-NOOPT-NEXT:    [[SUM2:%.*]] = add i8 [[SUM]], [[E2]]
; CHECK-NOOPT-NEXT:    [[SUM3:%.*]] = add i8 [[SUM2]], [[E3]]
; CHECK-NOOPT-NEXT:    store i8 [[SUM3]], ptr addrspace(1) [[OUT2]], align 1
; CHECK-NOOPT-NEXT:    ret void
;
  ptr addrspace(1) %out,
  ptr addrspace(1) %out2,
  <2 x i32> %src,
  i1 %cond
) {
entry:
  %bytes = bitcast <2 x i32> %src to <8 x i8>
  %e0 = extractelement <8 x i8> %bytes, i64 0
  %e1 = extractelement <8 x i8> %bytes, i64 1
  %e2 = extractelement <8 x i8> %bytes, i64 2
  %e3 = extractelement <8 x i8> %bytes, i64 3
  %e4 = extractelement <8 x i8> %bytes, i64 4
  %e5 = extractelement <8 x i8> %bytes, i64 5
  %e6 = extractelement <8 x i8> %bytes, i64 6
  %e7 = extractelement <8 x i8> %bytes, i64 7
  ; Selects that will be combined
  %s0 = select i1 %cond, i8 %e0, i8 0
  %s1 = select i1 %cond, i8 %e1, i8 0
  %s2 = select i1 %cond, i8 %e2, i8 0
  %s3 = select i1 %cond, i8 %e3, i8 0
  %s4 = select i1 %cond, i8 %e4, i8 0
  %s5 = select i1 %cond, i8 %e5, i8 0
  %s6 = select i1 %cond, i8 %e6, i8 0
  %s7 = select i1 %cond, i8 %e7, i8 0
  ; Store select results
  store i8 %s0, ptr addrspace(1) %out, align 1
  %ptr1 = getelementptr i8, ptr addrspace(1) %out, i64 1
  store i8 %s1, ptr addrspace(1) %ptr1, align 1
  %ptr2 = getelementptr i8, ptr addrspace(1) %out, i64 2
  store i8 %s2, ptr addrspace(1) %ptr2, align 1
  %ptr3 = getelementptr i8, ptr addrspace(1) %out, i64 3
  store i8 %s3, ptr addrspace(1) %ptr3, align 1
  %ptr4 = getelementptr i8, ptr addrspace(1) %out, i64 4
  store i8 %s4, ptr addrspace(1) %ptr4, align 1
  %ptr5 = getelementptr i8, ptr addrspace(1) %out, i64 5
  store i8 %s5, ptr addrspace(1) %ptr5, align 1
  %ptr6 = getelementptr i8, ptr addrspace(1) %out, i64 6
  store i8 %s6, ptr addrspace(1) %ptr6, align 1
  %ptr7 = getelementptr i8, ptr addrspace(1) %out, i64 7
  store i8 %s7, ptr addrspace(1) %ptr7, align 1
  ; Additional unrelated uses of the extracts - these prevent extract removal
  %sum = add i8 %e0, %e1
  %sum2 = add i8 %sum, %e2
  %sum3 = add i8 %sum2, %e3
  store i8 %sum3, ptr addrspace(1) %out2, align 1
  ret void
}

; Negative test: select with extract as false value (wrong operand position)
define amdgpu_kernel void @no_combine_wrong_operand_order(
;
; CHECK-LABEL: define amdgpu_kernel void @no_combine_wrong_operand_order(
; CHECK-SAME: ptr addrspace(1) [[OUT:%.*]], <2 x i32> [[SRC:%.*]], i1 [[COND:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[BYTES:%.*]] = bitcast <2 x i32> [[SRC]] to <8 x i8>
; CHECK-NEXT:    [[E0:%.*]] = extractelement <8 x i8> [[BYTES]], i64 0
; CHECK-NEXT:    [[E1:%.*]] = extractelement <8 x i8> [[BYTES]], i64 1
; CHECK-NEXT:    [[E2:%.*]] = extractelement <8 x i8> [[BYTES]], i64 2
; CHECK-NEXT:    [[E3:%.*]] = extractelement <8 x i8> [[BYTES]], i64 3
; CHECK-NEXT:    [[S0:%.*]] = select i1 [[COND]], i8 0, i8 [[E0]]
; CHECK-NEXT:    [[S1:%.*]] = select i1 [[COND]], i8 0, i8 [[E1]]
; CHECK-NEXT:    [[S2:%.*]] = select i1 [[COND]], i8 0, i8 [[E2]]
; CHECK-NEXT:    [[S3:%.*]] = select i1 [[COND]], i8 0, i8 [[E3]]
; CHECK-NEXT:    store i8 [[S0]], ptr addrspace(1) [[OUT]], align 1
; CHECK-NEXT:    [[PTR1:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 1
; CHECK-NEXT:    store i8 [[S1]], ptr addrspace(1) [[PTR1]], align 1
; CHECK-NEXT:    [[PTR2:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 2
; CHECK-NEXT:    store i8 [[S2]], ptr addrspace(1) [[PTR2]], align 1
; CHECK-NEXT:    [[PTR3:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 3
; CHECK-NEXT:    store i8 [[S3]], ptr addrspace(1) [[PTR3]], align 1
; CHECK-NEXT:    ret void
;
  ptr addrspace(1) %out,
  <2 x i32> %src,
  i1 %cond
) {
entry:
  %bytes = bitcast <2 x i32> %src to <8 x i8>
  %e0 = extractelement <8 x i8> %bytes, i64 0
  %e1 = extractelement <8 x i8> %bytes, i64 1
  %e2 = extractelement <8 x i8> %bytes, i64 2
  %e3 = extractelement <8 x i8> %bytes, i64 3
  ; Extract is false value, 0 is true value - should not combine
  %s0 = select i1 %cond, i8 0, i8 %e0
  %s1 = select i1 %cond, i8 0, i8 %e1
  %s2 = select i1 %cond, i8 0, i8 %e2
  %s3 = select i1 %cond, i8 0, i8 %e3
  store i8 %s0, ptr addrspace(1) %out, align 1
  %ptr1 = getelementptr i8, ptr addrspace(1) %out, i64 1
  store i8 %s1, ptr addrspace(1) %ptr1, align 1
  %ptr2 = getelementptr i8, ptr addrspace(1) %out, i64 2
  store i8 %s2, ptr addrspace(1) %ptr2, align 1
  %ptr3 = getelementptr i8, ptr addrspace(1) %out, i64 3
  store i8 %s3, ptr addrspace(1) %ptr3, align 1
  ret void
}

; Test <4 x i32> to <8 x i16> (32-bit elements to 16-bit elements)
define amdgpu_kernel void @combine_v4i32_to_v8i16(
; CHECK-OPT-LABEL: define amdgpu_kernel void @combine_v4i32_to_v8i16(
; CHECK-OPT-SAME: ptr addrspace(1) [[OUT:%.*]], <4 x i32> [[SRC:%.*]], i1 [[COND:%.*]]) #[[ATTR0]] {
; CHECK-OPT-NEXT:  [[ENTRY:.*:]]
; CHECK-OPT-NEXT:    [[COMBINED_SEL:%.*]] = select i1 [[COND]], <4 x i32> [[SRC]], <4 x i32> zeroinitializer
; CHECK-OPT-NEXT:    [[COMBINED_BC:%.*]] = bitcast <4 x i32> [[COMBINED_SEL]] to <8 x i16>
; CHECK-OPT-NEXT:    [[TMP0:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 0
; CHECK-OPT-NEXT:    [[TMP3:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 1
; CHECK-OPT-NEXT:    [[TMP5:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 2
; CHECK-OPT-NEXT:    [[TMP7:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 3
; CHECK-OPT-NEXT:    [[TMP2:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 4
; CHECK-OPT-NEXT:    [[TMP4:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 5
; CHECK-OPT-NEXT:    [[TMP6:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 6
; CHECK-OPT-NEXT:    [[TMP1:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 7
; CHECK-OPT-NEXT:    store i16 [[TMP0]], ptr addrspace(1) [[OUT]], align 2
; CHECK-OPT-NEXT:    [[PTR1:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 1
; CHECK-OPT-NEXT:    store i16 [[TMP3]], ptr addrspace(1) [[PTR1]], align 2
; CHECK-OPT-NEXT:    [[PTR2:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 2
; CHECK-OPT-NEXT:    store i16 [[TMP5]], ptr addrspace(1) [[PTR2]], align 2
; CHECK-OPT-NEXT:    [[PTR3:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 3
; CHECK-OPT-NEXT:    store i16 [[TMP7]], ptr addrspace(1) [[PTR3]], align 2
; CHECK-OPT-NEXT:    [[PTR4:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 4
; CHECK-OPT-NEXT:    store i16 [[TMP2]], ptr addrspace(1) [[PTR4]], align 2
; CHECK-OPT-NEXT:    [[PTR5:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 5
; CHECK-OPT-NEXT:    store i16 [[TMP4]], ptr addrspace(1) [[PTR5]], align 2
; CHECK-OPT-NEXT:    [[PTR6:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 6
; CHECK-OPT-NEXT:    store i16 [[TMP6]], ptr addrspace(1) [[PTR6]], align 2
; CHECK-OPT-NEXT:    [[PTR7:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 7
; CHECK-OPT-NEXT:    store i16 [[TMP1]], ptr addrspace(1) [[PTR7]], align 2
; CHECK-OPT-NEXT:    ret void
;
; CHECK-NOOPT-LABEL: define amdgpu_kernel void @combine_v4i32_to_v8i16(
; CHECK-NOOPT-SAME: ptr addrspace(1) [[OUT:%.*]], <4 x i32> [[SRC:%.*]], i1 [[COND:%.*]]) #[[ATTR0]] {
; CHECK-NOOPT-NEXT:  [[ENTRY:.*:]]
; CHECK-NOOPT-NEXT:    [[HALVES:%.*]] = bitcast <4 x i32> [[SRC]] to <8 x i16>
; CHECK-NOOPT-NEXT:    [[E0:%.*]] = extractelement <8 x i16> [[HALVES]], i64 0
; CHECK-NOOPT-NEXT:    [[E1:%.*]] = extractelement <8 x i16> [[HALVES]], i64 1
; CHECK-NOOPT-NEXT:    [[E2:%.*]] = extractelement <8 x i16> [[HALVES]], i64 2
; CHECK-NOOPT-NEXT:    [[E3:%.*]] = extractelement <8 x i16> [[HALVES]], i64 3
; CHECK-NOOPT-NEXT:    [[E4:%.*]] = extractelement <8 x i16> [[HALVES]], i64 4
; CHECK-NOOPT-NEXT:    [[E5:%.*]] = extractelement <8 x i16> [[HALVES]], i64 5
; CHECK-NOOPT-NEXT:    [[E6:%.*]] = extractelement <8 x i16> [[HALVES]], i64 6
; CHECK-NOOPT-NEXT:    [[E7:%.*]] = extractelement <8 x i16> [[HALVES]], i64 7
; CHECK-NOOPT-NEXT:    [[S0:%.*]] = select i1 [[COND]], i16 [[E0]], i16 0
; CHECK-NOOPT-NEXT:    [[S1:%.*]] = select i1 [[COND]], i16 [[E1]], i16 0
; CHECK-NOOPT-NEXT:    [[S2:%.*]] = select i1 [[COND]], i16 [[E2]], i16 0
; CHECK-NOOPT-NEXT:    [[S3:%.*]] = select i1 [[COND]], i16 [[E3]], i16 0
; CHECK-NOOPT-NEXT:    [[S4:%.*]] = select i1 [[COND]], i16 [[E4]], i16 0
; CHECK-NOOPT-NEXT:    [[S5:%.*]] = select i1 [[COND]], i16 [[E5]], i16 0
; CHECK-NOOPT-NEXT:    [[S6:%.*]] = select i1 [[COND]], i16 [[E6]], i16 0
; CHECK-NOOPT-NEXT:    [[S7:%.*]] = select i1 [[COND]], i16 [[E7]], i16 0
; CHECK-NOOPT-NEXT:    store i16 [[S0]], ptr addrspace(1) [[OUT]], align 2
; CHECK-NOOPT-NEXT:    [[PTR1:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 1
; CHECK-NOOPT-NEXT:    store i16 [[S1]], ptr addrspace(1) [[PTR1]], align 2
; CHECK-NOOPT-NEXT:    [[PTR2:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 2
; CHECK-NOOPT-NEXT:    store i16 [[S2]], ptr addrspace(1) [[PTR2]], align 2
; CHECK-NOOPT-NEXT:    [[PTR3:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 3
; CHECK-NOOPT-NEXT:    store i16 [[S3]], ptr addrspace(1) [[PTR3]], align 2
; CHECK-NOOPT-NEXT:    [[PTR4:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 4
; CHECK-NOOPT-NEXT:    store i16 [[S4]], ptr addrspace(1) [[PTR4]], align 2
; CHECK-NOOPT-NEXT:    [[PTR5:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 5
; CHECK-NOOPT-NEXT:    store i16 [[S5]], ptr addrspace(1) [[PTR5]], align 2
; CHECK-NOOPT-NEXT:    [[PTR6:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 6
; CHECK-NOOPT-NEXT:    store i16 [[S6]], ptr addrspace(1) [[PTR6]], align 2
; CHECK-NOOPT-NEXT:    [[PTR7:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 7
; CHECK-NOOPT-NEXT:    store i16 [[S7]], ptr addrspace(1) [[PTR7]], align 2
; CHECK-NOOPT-NEXT:    ret void
;
  ptr addrspace(1) %out,
  <4 x i32> %src,
  i1 %cond
) {
entry:
  %halves = bitcast <4 x i32> %src to <8 x i16>
  %e0 = extractelement <8 x i16> %halves, i64 0
  %e1 = extractelement <8 x i16> %halves, i64 1
  %e2 = extractelement <8 x i16> %halves, i64 2
  %e3 = extractelement <8 x i16> %halves, i64 3
  %e4 = extractelement <8 x i16> %halves, i64 4
  %e5 = extractelement <8 x i16> %halves, i64 5
  %e6 = extractelement <8 x i16> %halves, i64 6
  %e7 = extractelement <8 x i16> %halves, i64 7
  %s0 = select i1 %cond, i16 %e0, i16 0
  %s1 = select i1 %cond, i16 %e1, i16 0
  %s2 = select i1 %cond, i16 %e2, i16 0
  %s3 = select i1 %cond, i16 %e3, i16 0
  %s4 = select i1 %cond, i16 %e4, i16 0
  %s5 = select i1 %cond, i16 %e5, i16 0
  %s6 = select i1 %cond, i16 %e6, i16 0
  %s7 = select i1 %cond, i16 %e7, i16 0
  store i16 %s0, ptr addrspace(1) %out, align 2
  %ptr1 = getelementptr i16, ptr addrspace(1) %out, i64 1
  store i16 %s1, ptr addrspace(1) %ptr1, align 2
  %ptr2 = getelementptr i16, ptr addrspace(1) %out, i64 2
  store i16 %s2, ptr addrspace(1) %ptr2, align 2
  %ptr3 = getelementptr i16, ptr addrspace(1) %out, i64 3
  store i16 %s3, ptr addrspace(1) %ptr3, align 2
  %ptr4 = getelementptr i16, ptr addrspace(1) %out, i64 4
  store i16 %s4, ptr addrspace(1) %ptr4, align 2
  %ptr5 = getelementptr i16, ptr addrspace(1) %out, i64 5
  store i16 %s5, ptr addrspace(1) %ptr5, align 2
  %ptr6 = getelementptr i16, ptr addrspace(1) %out, i64 6
  store i16 %s6, ptr addrspace(1) %ptr6, align 2
  %ptr7 = getelementptr i16, ptr addrspace(1) %out, i64 7
  store i16 %s7, ptr addrspace(1) %ptr7, align 2
  ret void
}

; Test <4 x float> to <16 x i8> (float elements to byte elements)
define amdgpu_kernel void @combine_v4f32_to_v16i8(
; CHECK-OPT-LABEL: define amdgpu_kernel void @combine_v4f32_to_v16i8(
; CHECK-OPT-SAME: ptr addrspace(1) [[OUT:%.*]], <4 x float> [[SRC:%.*]], i1 [[COND:%.*]]) #[[ATTR0]] {
; CHECK-OPT-NEXT:  [[ENTRY:.*:]]
; CHECK-OPT-NEXT:    [[COMBINED_SEL:%.*]] = select i1 [[COND]], <4 x float> [[SRC]], <4 x float> zeroinitializer
; CHECK-OPT-NEXT:    [[COMBINED_BC:%.*]] = bitcast <4 x float> [[COMBINED_SEL]] to <16 x i8>
; CHECK-OPT-NEXT:    [[TMP0:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 0
; CHECK-OPT-NEXT:    [[TMP9:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 1
; CHECK-OPT-NEXT:    [[TMP3:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 2
; CHECK-OPT-NEXT:    [[TMP12:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 3
; CHECK-OPT-NEXT:    [[TMP5:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 4
; CHECK-OPT-NEXT:    [[TMP14:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 5
; CHECK-OPT-NEXT:    [[TMP7:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 6
; CHECK-OPT-NEXT:    [[TMP1:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 7
; CHECK-OPT-NEXT:    [[TMP10:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 8
; CHECK-OPT-NEXT:    [[TMP4:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 9
; CHECK-OPT-NEXT:    [[TMP13:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 10
; CHECK-OPT-NEXT:    [[TMP6:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 11
; CHECK-OPT-NEXT:    [[TMP15:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 12
; CHECK-OPT-NEXT:    [[TMP8:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 13
; CHECK-OPT-NEXT:    [[TMP2:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 14
; CHECK-OPT-NEXT:    [[TMP11:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 15
; CHECK-OPT-NEXT:    store i8 [[TMP0]], ptr addrspace(1) [[OUT]], align 1
; CHECK-OPT-NEXT:    [[PTR1:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 1
; CHECK-OPT-NEXT:    store i8 [[TMP9]], ptr addrspace(1) [[PTR1]], align 1
; CHECK-OPT-NEXT:    [[PTR2:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 2
; CHECK-OPT-NEXT:    store i8 [[TMP3]], ptr addrspace(1) [[PTR2]], align 1
; CHECK-OPT-NEXT:    [[PTR3:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 3
; CHECK-OPT-NEXT:    store i8 [[TMP12]], ptr addrspace(1) [[PTR3]], align 1
; CHECK-OPT-NEXT:    [[PTR4:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 4
; CHECK-OPT-NEXT:    store i8 [[TMP5]], ptr addrspace(1) [[PTR4]], align 1
; CHECK-OPT-NEXT:    [[PTR5:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 5
; CHECK-OPT-NEXT:    store i8 [[TMP14]], ptr addrspace(1) [[PTR5]], align 1
; CHECK-OPT-NEXT:    [[PTR6:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 6
; CHECK-OPT-NEXT:    store i8 [[TMP7]], ptr addrspace(1) [[PTR6]], align 1
; CHECK-OPT-NEXT:    [[PTR7:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 7
; CHECK-OPT-NEXT:    store i8 [[TMP1]], ptr addrspace(1) [[PTR7]], align 1
; CHECK-OPT-NEXT:    [[PTR8:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 8
; CHECK-OPT-NEXT:    store i8 [[TMP10]], ptr addrspace(1) [[PTR8]], align 1
; CHECK-OPT-NEXT:    [[PTR9:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 9
; CHECK-OPT-NEXT:    store i8 [[TMP4]], ptr addrspace(1) [[PTR9]], align 1
; CHECK-OPT-NEXT:    [[PTR10:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 10
; CHECK-OPT-NEXT:    store i8 [[TMP13]], ptr addrspace(1) [[PTR10]], align 1
; CHECK-OPT-NEXT:    [[PTR11:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 11
; CHECK-OPT-NEXT:    store i8 [[TMP6]], ptr addrspace(1) [[PTR11]], align 1
; CHECK-OPT-NEXT:    [[PTR12:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 12
; CHECK-OPT-NEXT:    store i8 [[TMP15]], ptr addrspace(1) [[PTR12]], align 1
; CHECK-OPT-NEXT:    [[PTR13:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 13
; CHECK-OPT-NEXT:    store i8 [[TMP8]], ptr addrspace(1) [[PTR13]], align 1
; CHECK-OPT-NEXT:    [[PTR14:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 14
; CHECK-OPT-NEXT:    store i8 [[TMP2]], ptr addrspace(1) [[PTR14]], align 1
; CHECK-OPT-NEXT:    [[PTR15:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 15
; CHECK-OPT-NEXT:    store i8 [[TMP11]], ptr addrspace(1) [[PTR15]], align 1
; CHECK-OPT-NEXT:    ret void
;
; CHECK-NOOPT-LABEL: define amdgpu_kernel void @combine_v4f32_to_v16i8(
; CHECK-NOOPT-SAME: ptr addrspace(1) [[OUT:%.*]], <4 x float> [[SRC:%.*]], i1 [[COND:%.*]]) #[[ATTR0]] {
; CHECK-NOOPT-NEXT:  [[ENTRY:.*:]]
; CHECK-NOOPT-NEXT:    [[BYTES:%.*]] = bitcast <4 x float> [[SRC]] to <16 x i8>
; CHECK-NOOPT-NEXT:    [[E0:%.*]] = extractelement <16 x i8> [[BYTES]], i64 0
; CHECK-NOOPT-NEXT:    [[E1:%.*]] = extractelement <16 x i8> [[BYTES]], i64 1
; CHECK-NOOPT-NEXT:    [[E2:%.*]] = extractelement <16 x i8> [[BYTES]], i64 2
; CHECK-NOOPT-NEXT:    [[E3:%.*]] = extractelement <16 x i8> [[BYTES]], i64 3
; CHECK-NOOPT-NEXT:    [[E4:%.*]] = extractelement <16 x i8> [[BYTES]], i64 4
; CHECK-NOOPT-NEXT:    [[E5:%.*]] = extractelement <16 x i8> [[BYTES]], i64 5
; CHECK-NOOPT-NEXT:    [[E6:%.*]] = extractelement <16 x i8> [[BYTES]], i64 6
; CHECK-NOOPT-NEXT:    [[E7:%.*]] = extractelement <16 x i8> [[BYTES]], i64 7
; CHECK-NOOPT-NEXT:    [[E8:%.*]] = extractelement <16 x i8> [[BYTES]], i64 8
; CHECK-NOOPT-NEXT:    [[E9:%.*]] = extractelement <16 x i8> [[BYTES]], i64 9
; CHECK-NOOPT-NEXT:    [[E10:%.*]] = extractelement <16 x i8> [[BYTES]], i64 10
; CHECK-NOOPT-NEXT:    [[E11:%.*]] = extractelement <16 x i8> [[BYTES]], i64 11
; CHECK-NOOPT-NEXT:    [[E12:%.*]] = extractelement <16 x i8> [[BYTES]], i64 12
; CHECK-NOOPT-NEXT:    [[E13:%.*]] = extractelement <16 x i8> [[BYTES]], i64 13
; CHECK-NOOPT-NEXT:    [[E14:%.*]] = extractelement <16 x i8> [[BYTES]], i64 14
; CHECK-NOOPT-NEXT:    [[E15:%.*]] = extractelement <16 x i8> [[BYTES]], i64 15
; CHECK-NOOPT-NEXT:    [[S0:%.*]] = select i1 [[COND]], i8 [[E0]], i8 0
; CHECK-NOOPT-NEXT:    [[S1:%.*]] = select i1 [[COND]], i8 [[E1]], i8 0
; CHECK-NOOPT-NEXT:    [[S2:%.*]] = select i1 [[COND]], i8 [[E2]], i8 0
; CHECK-NOOPT-NEXT:    [[S3:%.*]] = select i1 [[COND]], i8 [[E3]], i8 0
; CHECK-NOOPT-NEXT:    [[S4:%.*]] = select i1 [[COND]], i8 [[E4]], i8 0
; CHECK-NOOPT-NEXT:    [[S5:%.*]] = select i1 [[COND]], i8 [[E5]], i8 0
; CHECK-NOOPT-NEXT:    [[S6:%.*]] = select i1 [[COND]], i8 [[E6]], i8 0
; CHECK-NOOPT-NEXT:    [[S7:%.*]] = select i1 [[COND]], i8 [[E7]], i8 0
; CHECK-NOOPT-NEXT:    [[S8:%.*]] = select i1 [[COND]], i8 [[E8]], i8 0
; CHECK-NOOPT-NEXT:    [[S9:%.*]] = select i1 [[COND]], i8 [[E9]], i8 0
; CHECK-NOOPT-NEXT:    [[S10:%.*]] = select i1 [[COND]], i8 [[E10]], i8 0
; CHECK-NOOPT-NEXT:    [[S11:%.*]] = select i1 [[COND]], i8 [[E11]], i8 0
; CHECK-NOOPT-NEXT:    [[S12:%.*]] = select i1 [[COND]], i8 [[E12]], i8 0
; CHECK-NOOPT-NEXT:    [[S13:%.*]] = select i1 [[COND]], i8 [[E13]], i8 0
; CHECK-NOOPT-NEXT:    [[S14:%.*]] = select i1 [[COND]], i8 [[E14]], i8 0
; CHECK-NOOPT-NEXT:    [[S15:%.*]] = select i1 [[COND]], i8 [[E15]], i8 0
; CHECK-NOOPT-NEXT:    store i8 [[S0]], ptr addrspace(1) [[OUT]], align 1
; CHECK-NOOPT-NEXT:    [[PTR1:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 1
; CHECK-NOOPT-NEXT:    store i8 [[S1]], ptr addrspace(1) [[PTR1]], align 1
; CHECK-NOOPT-NEXT:    [[PTR2:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 2
; CHECK-NOOPT-NEXT:    store i8 [[S2]], ptr addrspace(1) [[PTR2]], align 1
; CHECK-NOOPT-NEXT:    [[PTR3:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 3
; CHECK-NOOPT-NEXT:    store i8 [[S3]], ptr addrspace(1) [[PTR3]], align 1
; CHECK-NOOPT-NEXT:    [[PTR4:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 4
; CHECK-NOOPT-NEXT:    store i8 [[S4]], ptr addrspace(1) [[PTR4]], align 1
; CHECK-NOOPT-NEXT:    [[PTR5:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 5
; CHECK-NOOPT-NEXT:    store i8 [[S5]], ptr addrspace(1) [[PTR5]], align 1
; CHECK-NOOPT-NEXT:    [[PTR6:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 6
; CHECK-NOOPT-NEXT:    store i8 [[S6]], ptr addrspace(1) [[PTR6]], align 1
; CHECK-NOOPT-NEXT:    [[PTR7:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 7
; CHECK-NOOPT-NEXT:    store i8 [[S7]], ptr addrspace(1) [[PTR7]], align 1
; CHECK-NOOPT-NEXT:    [[PTR8:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 8
; CHECK-NOOPT-NEXT:    store i8 [[S8]], ptr addrspace(1) [[PTR8]], align 1
; CHECK-NOOPT-NEXT:    [[PTR9:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 9
; CHECK-NOOPT-NEXT:    store i8 [[S9]], ptr addrspace(1) [[PTR9]], align 1
; CHECK-NOOPT-NEXT:    [[PTR10:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 10
; CHECK-NOOPT-NEXT:    store i8 [[S10]], ptr addrspace(1) [[PTR10]], align 1
; CHECK-NOOPT-NEXT:    [[PTR11:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 11
; CHECK-NOOPT-NEXT:    store i8 [[S11]], ptr addrspace(1) [[PTR11]], align 1
; CHECK-NOOPT-NEXT:    [[PTR12:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 12
; CHECK-NOOPT-NEXT:    store i8 [[S12]], ptr addrspace(1) [[PTR12]], align 1
; CHECK-NOOPT-NEXT:    [[PTR13:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 13
; CHECK-NOOPT-NEXT:    store i8 [[S13]], ptr addrspace(1) [[PTR13]], align 1
; CHECK-NOOPT-NEXT:    [[PTR14:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 14
; CHECK-NOOPT-NEXT:    store i8 [[S14]], ptr addrspace(1) [[PTR14]], align 1
; CHECK-NOOPT-NEXT:    [[PTR15:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 15
; CHECK-NOOPT-NEXT:    store i8 [[S15]], ptr addrspace(1) [[PTR15]], align 1
; CHECK-NOOPT-NEXT:    ret void
;
  ptr addrspace(1) %out,
  <4 x float> %src,
  i1 %cond
) {
entry:
  %bytes = bitcast <4 x float> %src to <16 x i8>
  %e0 = extractelement <16 x i8> %bytes, i64 0
  %e1 = extractelement <16 x i8> %bytes, i64 1
  %e2 = extractelement <16 x i8> %bytes, i64 2
  %e3 = extractelement <16 x i8> %bytes, i64 3
  %e4 = extractelement <16 x i8> %bytes, i64 4
  %e5 = extractelement <16 x i8> %bytes, i64 5
  %e6 = extractelement <16 x i8> %bytes, i64 6
  %e7 = extractelement <16 x i8> %bytes, i64 7
  %e8 = extractelement <16 x i8> %bytes, i64 8
  %e9 = extractelement <16 x i8> %bytes, i64 9
  %e10 = extractelement <16 x i8> %bytes, i64 10
  %e11 = extractelement <16 x i8> %bytes, i64 11
  %e12 = extractelement <16 x i8> %bytes, i64 12
  %e13 = extractelement <16 x i8> %bytes, i64 13
  %e14 = extractelement <16 x i8> %bytes, i64 14
  %e15 = extractelement <16 x i8> %bytes, i64 15
  %s0 = select i1 %cond, i8 %e0, i8 0
  %s1 = select i1 %cond, i8 %e1, i8 0
  %s2 = select i1 %cond, i8 %e2, i8 0
  %s3 = select i1 %cond, i8 %e3, i8 0
  %s4 = select i1 %cond, i8 %e4, i8 0
  %s5 = select i1 %cond, i8 %e5, i8 0
  %s6 = select i1 %cond, i8 %e6, i8 0
  %s7 = select i1 %cond, i8 %e7, i8 0
  %s8 = select i1 %cond, i8 %e8, i8 0
  %s9 = select i1 %cond, i8 %e9, i8 0
  %s10 = select i1 %cond, i8 %e10, i8 0
  %s11 = select i1 %cond, i8 %e11, i8 0
  %s12 = select i1 %cond, i8 %e12, i8 0
  %s13 = select i1 %cond, i8 %e13, i8 0
  %s14 = select i1 %cond, i8 %e14, i8 0
  %s15 = select i1 %cond, i8 %e15, i8 0
  store i8 %s0, ptr addrspace(1) %out, align 1
  %ptr1 = getelementptr i8, ptr addrspace(1) %out, i64 1
  store i8 %s1, ptr addrspace(1) %ptr1, align 1
  %ptr2 = getelementptr i8, ptr addrspace(1) %out, i64 2
  store i8 %s2, ptr addrspace(1) %ptr2, align 1
  %ptr3 = getelementptr i8, ptr addrspace(1) %out, i64 3
  store i8 %s3, ptr addrspace(1) %ptr3, align 1
  %ptr4 = getelementptr i8, ptr addrspace(1) %out, i64 4
  store i8 %s4, ptr addrspace(1) %ptr4, align 1
  %ptr5 = getelementptr i8, ptr addrspace(1) %out, i64 5
  store i8 %s5, ptr addrspace(1) %ptr5, align 1
  %ptr6 = getelementptr i8, ptr addrspace(1) %out, i64 6
  store i8 %s6, ptr addrspace(1) %ptr6, align 1
  %ptr7 = getelementptr i8, ptr addrspace(1) %out, i64 7
  store i8 %s7, ptr addrspace(1) %ptr7, align 1
  %ptr8 = getelementptr i8, ptr addrspace(1) %out, i64 8
  store i8 %s8, ptr addrspace(1) %ptr8, align 1
  %ptr9 = getelementptr i8, ptr addrspace(1) %out, i64 9
  store i8 %s9, ptr addrspace(1) %ptr9, align 1
  %ptr10 = getelementptr i8, ptr addrspace(1) %out, i64 10
  store i8 %s10, ptr addrspace(1) %ptr10, align 1
  %ptr11 = getelementptr i8, ptr addrspace(1) %out, i64 11
  store i8 %s11, ptr addrspace(1) %ptr11, align 1
  %ptr12 = getelementptr i8, ptr addrspace(1) %out, i64 12
  store i8 %s12, ptr addrspace(1) %ptr12, align 1
  %ptr13 = getelementptr i8, ptr addrspace(1) %out, i64 13
  store i8 %s13, ptr addrspace(1) %ptr13, align 1
  %ptr14 = getelementptr i8, ptr addrspace(1) %out, i64 14
  store i8 %s14, ptr addrspace(1) %ptr14, align 1
  %ptr15 = getelementptr i8, ptr addrspace(1) %out, i64 15
  store i8 %s15, ptr addrspace(1) %ptr15, align 1
  ret void
}

; Test <4 x float> to <8 x i16> (float elements to 16-bit elements)
define amdgpu_kernel void @combine_v4f32_to_v8i16(
; CHECK-OPT-LABEL: define amdgpu_kernel void @combine_v4f32_to_v8i16(
; CHECK-OPT-SAME: ptr addrspace(1) [[OUT:%.*]], <4 x float> [[SRC:%.*]], i1 [[COND:%.*]]) #[[ATTR0]] {
; CHECK-OPT-NEXT:  [[ENTRY:.*:]]
; CHECK-OPT-NEXT:    [[COMBINED_SEL:%.*]] = select i1 [[COND]], <4 x float> [[SRC]], <4 x float> zeroinitializer
; CHECK-OPT-NEXT:    [[COMBINED_BC:%.*]] = bitcast <4 x float> [[COMBINED_SEL]] to <8 x i16>
; CHECK-OPT-NEXT:    [[TMP0:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 0
; CHECK-OPT-NEXT:    [[TMP3:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 1
; CHECK-OPT-NEXT:    [[TMP5:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 2
; CHECK-OPT-NEXT:    [[TMP7:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 3
; CHECK-OPT-NEXT:    [[TMP2:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 4
; CHECK-OPT-NEXT:    [[TMP4:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 5
; CHECK-OPT-NEXT:    [[TMP6:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 6
; CHECK-OPT-NEXT:    [[TMP1:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 7
; CHECK-OPT-NEXT:    store i16 [[TMP0]], ptr addrspace(1) [[OUT]], align 2
; CHECK-OPT-NEXT:    [[PTR1:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 1
; CHECK-OPT-NEXT:    store i16 [[TMP3]], ptr addrspace(1) [[PTR1]], align 2
; CHECK-OPT-NEXT:    [[PTR2:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 2
; CHECK-OPT-NEXT:    store i16 [[TMP5]], ptr addrspace(1) [[PTR2]], align 2
; CHECK-OPT-NEXT:    [[PTR3:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 3
; CHECK-OPT-NEXT:    store i16 [[TMP7]], ptr addrspace(1) [[PTR3]], align 2
; CHECK-OPT-NEXT:    [[PTR4:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 4
; CHECK-OPT-NEXT:    store i16 [[TMP2]], ptr addrspace(1) [[PTR4]], align 2
; CHECK-OPT-NEXT:    [[PTR5:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 5
; CHECK-OPT-NEXT:    store i16 [[TMP4]], ptr addrspace(1) [[PTR5]], align 2
; CHECK-OPT-NEXT:    [[PTR6:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 6
; CHECK-OPT-NEXT:    store i16 [[TMP6]], ptr addrspace(1) [[PTR6]], align 2
; CHECK-OPT-NEXT:    [[PTR7:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 7
; CHECK-OPT-NEXT:    store i16 [[TMP1]], ptr addrspace(1) [[PTR7]], align 2
; CHECK-OPT-NEXT:    ret void
;
; CHECK-NOOPT-LABEL: define amdgpu_kernel void @combine_v4f32_to_v8i16(
; CHECK-NOOPT-SAME: ptr addrspace(1) [[OUT:%.*]], <4 x float> [[SRC:%.*]], i1 [[COND:%.*]]) #[[ATTR0]] {
; CHECK-NOOPT-NEXT:  [[ENTRY:.*:]]
; CHECK-NOOPT-NEXT:    [[HALVES:%.*]] = bitcast <4 x float> [[SRC]] to <8 x i16>
; CHECK-NOOPT-NEXT:    [[E0:%.*]] = extractelement <8 x i16> [[HALVES]], i64 0
; CHECK-NOOPT-NEXT:    [[E1:%.*]] = extractelement <8 x i16> [[HALVES]], i64 1
; CHECK-NOOPT-NEXT:    [[E2:%.*]] = extractelement <8 x i16> [[HALVES]], i64 2
; CHECK-NOOPT-NEXT:    [[E3:%.*]] = extractelement <8 x i16> [[HALVES]], i64 3
; CHECK-NOOPT-NEXT:    [[E4:%.*]] = extractelement <8 x i16> [[HALVES]], i64 4
; CHECK-NOOPT-NEXT:    [[E5:%.*]] = extractelement <8 x i16> [[HALVES]], i64 5
; CHECK-NOOPT-NEXT:    [[E6:%.*]] = extractelement <8 x i16> [[HALVES]], i64 6
; CHECK-NOOPT-NEXT:    [[E7:%.*]] = extractelement <8 x i16> [[HALVES]], i64 7
; CHECK-NOOPT-NEXT:    [[S0:%.*]] = select i1 [[COND]], i16 [[E0]], i16 0
; CHECK-NOOPT-NEXT:    [[S1:%.*]] = select i1 [[COND]], i16 [[E1]], i16 0
; CHECK-NOOPT-NEXT:    [[S2:%.*]] = select i1 [[COND]], i16 [[E2]], i16 0
; CHECK-NOOPT-NEXT:    [[S3:%.*]] = select i1 [[COND]], i16 [[E3]], i16 0
; CHECK-NOOPT-NEXT:    [[S4:%.*]] = select i1 [[COND]], i16 [[E4]], i16 0
; CHECK-NOOPT-NEXT:    [[S5:%.*]] = select i1 [[COND]], i16 [[E5]], i16 0
; CHECK-NOOPT-NEXT:    [[S6:%.*]] = select i1 [[COND]], i16 [[E6]], i16 0
; CHECK-NOOPT-NEXT:    [[S7:%.*]] = select i1 [[COND]], i16 [[E7]], i16 0
; CHECK-NOOPT-NEXT:    store i16 [[S0]], ptr addrspace(1) [[OUT]], align 2
; CHECK-NOOPT-NEXT:    [[PTR1:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 1
; CHECK-NOOPT-NEXT:    store i16 [[S1]], ptr addrspace(1) [[PTR1]], align 2
; CHECK-NOOPT-NEXT:    [[PTR2:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 2
; CHECK-NOOPT-NEXT:    store i16 [[S2]], ptr addrspace(1) [[PTR2]], align 2
; CHECK-NOOPT-NEXT:    [[PTR3:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 3
; CHECK-NOOPT-NEXT:    store i16 [[S3]], ptr addrspace(1) [[PTR3]], align 2
; CHECK-NOOPT-NEXT:    [[PTR4:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 4
; CHECK-NOOPT-NEXT:    store i16 [[S4]], ptr addrspace(1) [[PTR4]], align 2
; CHECK-NOOPT-NEXT:    [[PTR5:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 5
; CHECK-NOOPT-NEXT:    store i16 [[S5]], ptr addrspace(1) [[PTR5]], align 2
; CHECK-NOOPT-NEXT:    [[PTR6:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 6
; CHECK-NOOPT-NEXT:    store i16 [[S6]], ptr addrspace(1) [[PTR6]], align 2
; CHECK-NOOPT-NEXT:    [[PTR7:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 7
; CHECK-NOOPT-NEXT:    store i16 [[S7]], ptr addrspace(1) [[PTR7]], align 2
; CHECK-NOOPT-NEXT:    ret void
;
  ptr addrspace(1) %out,
  <4 x float> %src,
  i1 %cond
) {
entry:
  %halves = bitcast <4 x float> %src to <8 x i16>
  %e0 = extractelement <8 x i16> %halves, i64 0
  %e1 = extractelement <8 x i16> %halves, i64 1
  %e2 = extractelement <8 x i16> %halves, i64 2
  %e3 = extractelement <8 x i16> %halves, i64 3
  %e4 = extractelement <8 x i16> %halves, i64 4
  %e5 = extractelement <8 x i16> %halves, i64 5
  %e6 = extractelement <8 x i16> %halves, i64 6
  %e7 = extractelement <8 x i16> %halves, i64 7
  %s0 = select i1 %cond, i16 %e0, i16 0
  %s1 = select i1 %cond, i16 %e1, i16 0
  %s2 = select i1 %cond, i16 %e2, i16 0
  %s3 = select i1 %cond, i16 %e3, i16 0
  %s4 = select i1 %cond, i16 %e4, i16 0
  %s5 = select i1 %cond, i16 %e5, i16 0
  %s6 = select i1 %cond, i16 %e6, i16 0
  %s7 = select i1 %cond, i16 %e7, i16 0
  store i16 %s0, ptr addrspace(1) %out, align 2
  %ptr1 = getelementptr i16, ptr addrspace(1) %out, i64 1
  store i16 %s1, ptr addrspace(1) %ptr1, align 2
  %ptr2 = getelementptr i16, ptr addrspace(1) %out, i64 2
  store i16 %s2, ptr addrspace(1) %ptr2, align 2
  %ptr3 = getelementptr i16, ptr addrspace(1) %out, i64 3
  store i16 %s3, ptr addrspace(1) %ptr3, align 2
  %ptr4 = getelementptr i16, ptr addrspace(1) %out, i64 4
  store i16 %s4, ptr addrspace(1) %ptr4, align 2
  %ptr5 = getelementptr i16, ptr addrspace(1) %out, i64 5
  store i16 %s5, ptr addrspace(1) %ptr5, align 2
  %ptr6 = getelementptr i16, ptr addrspace(1) %out, i64 6
  store i16 %s6, ptr addrspace(1) %ptr6, align 2
  %ptr7 = getelementptr i16, ptr addrspace(1) %out, i64 7
  store i16 %s7, ptr addrspace(1) %ptr7, align 2
  ret void
}

; Test <2 x i64> to <16 x i8> (64-bit elements to byte elements)
define amdgpu_kernel void @combine_v2i64_to_v16i8(
; CHECK-OPT-LABEL: define amdgpu_kernel void @combine_v2i64_to_v16i8(
; CHECK-OPT-SAME: ptr addrspace(1) [[OUT:%.*]], <2 x i64> [[SRC:%.*]], i1 [[COND:%.*]]) #[[ATTR0]] {
; CHECK-OPT-NEXT:  [[ENTRY:.*:]]
; CHECK-OPT-NEXT:    [[COMBINED_SEL:%.*]] = select i1 [[COND]], <2 x i64> [[SRC]], <2 x i64> zeroinitializer
; CHECK-OPT-NEXT:    [[COMBINED_BC:%.*]] = bitcast <2 x i64> [[COMBINED_SEL]] to <16 x i8>
; CHECK-OPT-NEXT:    [[TMP0:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 0
; CHECK-OPT-NEXT:    [[TMP9:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 1
; CHECK-OPT-NEXT:    [[TMP3:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 2
; CHECK-OPT-NEXT:    [[TMP12:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 3
; CHECK-OPT-NEXT:    [[TMP5:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 4
; CHECK-OPT-NEXT:    [[TMP14:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 5
; CHECK-OPT-NEXT:    [[TMP7:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 6
; CHECK-OPT-NEXT:    [[TMP1:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 7
; CHECK-OPT-NEXT:    [[TMP10:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 8
; CHECK-OPT-NEXT:    [[TMP4:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 9
; CHECK-OPT-NEXT:    [[TMP13:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 10
; CHECK-OPT-NEXT:    [[TMP6:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 11
; CHECK-OPT-NEXT:    [[TMP15:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 12
; CHECK-OPT-NEXT:    [[TMP8:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 13
; CHECK-OPT-NEXT:    [[TMP2:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 14
; CHECK-OPT-NEXT:    [[TMP11:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 15
; CHECK-OPT-NEXT:    store i8 [[TMP0]], ptr addrspace(1) [[OUT]], align 1
; CHECK-OPT-NEXT:    [[PTR1:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 1
; CHECK-OPT-NEXT:    store i8 [[TMP9]], ptr addrspace(1) [[PTR1]], align 1
; CHECK-OPT-NEXT:    [[PTR2:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 2
; CHECK-OPT-NEXT:    store i8 [[TMP3]], ptr addrspace(1) [[PTR2]], align 1
; CHECK-OPT-NEXT:    [[PTR3:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 3
; CHECK-OPT-NEXT:    store i8 [[TMP12]], ptr addrspace(1) [[PTR3]], align 1
; CHECK-OPT-NEXT:    [[PTR4:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 4
; CHECK-OPT-NEXT:    store i8 [[TMP5]], ptr addrspace(1) [[PTR4]], align 1
; CHECK-OPT-NEXT:    [[PTR5:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 5
; CHECK-OPT-NEXT:    store i8 [[TMP14]], ptr addrspace(1) [[PTR5]], align 1
; CHECK-OPT-NEXT:    [[PTR6:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 6
; CHECK-OPT-NEXT:    store i8 [[TMP7]], ptr addrspace(1) [[PTR6]], align 1
; CHECK-OPT-NEXT:    [[PTR7:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 7
; CHECK-OPT-NEXT:    store i8 [[TMP1]], ptr addrspace(1) [[PTR7]], align 1
; CHECK-OPT-NEXT:    [[PTR8:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 8
; CHECK-OPT-NEXT:    store i8 [[TMP10]], ptr addrspace(1) [[PTR8]], align 1
; CHECK-OPT-NEXT:    [[PTR9:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 9
; CHECK-OPT-NEXT:    store i8 [[TMP4]], ptr addrspace(1) [[PTR9]], align 1
; CHECK-OPT-NEXT:    [[PTR10:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 10
; CHECK-OPT-NEXT:    store i8 [[TMP13]], ptr addrspace(1) [[PTR10]], align 1
; CHECK-OPT-NEXT:    [[PTR11:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 11
; CHECK-OPT-NEXT:    store i8 [[TMP6]], ptr addrspace(1) [[PTR11]], align 1
; CHECK-OPT-NEXT:    [[PTR12:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 12
; CHECK-OPT-NEXT:    store i8 [[TMP15]], ptr addrspace(1) [[PTR12]], align 1
; CHECK-OPT-NEXT:    [[PTR13:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 13
; CHECK-OPT-NEXT:    store i8 [[TMP8]], ptr addrspace(1) [[PTR13]], align 1
; CHECK-OPT-NEXT:    [[PTR14:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 14
; CHECK-OPT-NEXT:    store i8 [[TMP2]], ptr addrspace(1) [[PTR14]], align 1
; CHECK-OPT-NEXT:    [[PTR15:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 15
; CHECK-OPT-NEXT:    store i8 [[TMP11]], ptr addrspace(1) [[PTR15]], align 1
; CHECK-OPT-NEXT:    ret void
;
; CHECK-NOOPT-LABEL: define amdgpu_kernel void @combine_v2i64_to_v16i8(
; CHECK-NOOPT-SAME: ptr addrspace(1) [[OUT:%.*]], <2 x i64> [[SRC:%.*]], i1 [[COND:%.*]]) #[[ATTR0]] {
; CHECK-NOOPT-NEXT:  [[ENTRY:.*:]]
; CHECK-NOOPT-NEXT:    [[BYTES:%.*]] = bitcast <2 x i64> [[SRC]] to <16 x i8>
; CHECK-NOOPT-NEXT:    [[E0:%.*]] = extractelement <16 x i8> [[BYTES]], i64 0
; CHECK-NOOPT-NEXT:    [[E1:%.*]] = extractelement <16 x i8> [[BYTES]], i64 1
; CHECK-NOOPT-NEXT:    [[E2:%.*]] = extractelement <16 x i8> [[BYTES]], i64 2
; CHECK-NOOPT-NEXT:    [[E3:%.*]] = extractelement <16 x i8> [[BYTES]], i64 3
; CHECK-NOOPT-NEXT:    [[E4:%.*]] = extractelement <16 x i8> [[BYTES]], i64 4
; CHECK-NOOPT-NEXT:    [[E5:%.*]] = extractelement <16 x i8> [[BYTES]], i64 5
; CHECK-NOOPT-NEXT:    [[E6:%.*]] = extractelement <16 x i8> [[BYTES]], i64 6
; CHECK-NOOPT-NEXT:    [[E7:%.*]] = extractelement <16 x i8> [[BYTES]], i64 7
; CHECK-NOOPT-NEXT:    [[E8:%.*]] = extractelement <16 x i8> [[BYTES]], i64 8
; CHECK-NOOPT-NEXT:    [[E9:%.*]] = extractelement <16 x i8> [[BYTES]], i64 9
; CHECK-NOOPT-NEXT:    [[E10:%.*]] = extractelement <16 x i8> [[BYTES]], i64 10
; CHECK-NOOPT-NEXT:    [[E11:%.*]] = extractelement <16 x i8> [[BYTES]], i64 11
; CHECK-NOOPT-NEXT:    [[E12:%.*]] = extractelement <16 x i8> [[BYTES]], i64 12
; CHECK-NOOPT-NEXT:    [[E13:%.*]] = extractelement <16 x i8> [[BYTES]], i64 13
; CHECK-NOOPT-NEXT:    [[E14:%.*]] = extractelement <16 x i8> [[BYTES]], i64 14
; CHECK-NOOPT-NEXT:    [[E15:%.*]] = extractelement <16 x i8> [[BYTES]], i64 15
; CHECK-NOOPT-NEXT:    [[S0:%.*]] = select i1 [[COND]], i8 [[E0]], i8 0
; CHECK-NOOPT-NEXT:    [[S1:%.*]] = select i1 [[COND]], i8 [[E1]], i8 0
; CHECK-NOOPT-NEXT:    [[S2:%.*]] = select i1 [[COND]], i8 [[E2]], i8 0
; CHECK-NOOPT-NEXT:    [[S3:%.*]] = select i1 [[COND]], i8 [[E3]], i8 0
; CHECK-NOOPT-NEXT:    [[S4:%.*]] = select i1 [[COND]], i8 [[E4]], i8 0
; CHECK-NOOPT-NEXT:    [[S5:%.*]] = select i1 [[COND]], i8 [[E5]], i8 0
; CHECK-NOOPT-NEXT:    [[S6:%.*]] = select i1 [[COND]], i8 [[E6]], i8 0
; CHECK-NOOPT-NEXT:    [[S7:%.*]] = select i1 [[COND]], i8 [[E7]], i8 0
; CHECK-NOOPT-NEXT:    [[S8:%.*]] = select i1 [[COND]], i8 [[E8]], i8 0
; CHECK-NOOPT-NEXT:    [[S9:%.*]] = select i1 [[COND]], i8 [[E9]], i8 0
; CHECK-NOOPT-NEXT:    [[S10:%.*]] = select i1 [[COND]], i8 [[E10]], i8 0
; CHECK-NOOPT-NEXT:    [[S11:%.*]] = select i1 [[COND]], i8 [[E11]], i8 0
; CHECK-NOOPT-NEXT:    [[S12:%.*]] = select i1 [[COND]], i8 [[E12]], i8 0
; CHECK-NOOPT-NEXT:    [[S13:%.*]] = select i1 [[COND]], i8 [[E13]], i8 0
; CHECK-NOOPT-NEXT:    [[S14:%.*]] = select i1 [[COND]], i8 [[E14]], i8 0
; CHECK-NOOPT-NEXT:    [[S15:%.*]] = select i1 [[COND]], i8 [[E15]], i8 0
; CHECK-NOOPT-NEXT:    store i8 [[S0]], ptr addrspace(1) [[OUT]], align 1
; CHECK-NOOPT-NEXT:    [[PTR1:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 1
; CHECK-NOOPT-NEXT:    store i8 [[S1]], ptr addrspace(1) [[PTR1]], align 1
; CHECK-NOOPT-NEXT:    [[PTR2:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 2
; CHECK-NOOPT-NEXT:    store i8 [[S2]], ptr addrspace(1) [[PTR2]], align 1
; CHECK-NOOPT-NEXT:    [[PTR3:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 3
; CHECK-NOOPT-NEXT:    store i8 [[S3]], ptr addrspace(1) [[PTR3]], align 1
; CHECK-NOOPT-NEXT:    [[PTR4:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 4
; CHECK-NOOPT-NEXT:    store i8 [[S4]], ptr addrspace(1) [[PTR4]], align 1
; CHECK-NOOPT-NEXT:    [[PTR5:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 5
; CHECK-NOOPT-NEXT:    store i8 [[S5]], ptr addrspace(1) [[PTR5]], align 1
; CHECK-NOOPT-NEXT:    [[PTR6:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 6
; CHECK-NOOPT-NEXT:    store i8 [[S6]], ptr addrspace(1) [[PTR6]], align 1
; CHECK-NOOPT-NEXT:    [[PTR7:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 7
; CHECK-NOOPT-NEXT:    store i8 [[S7]], ptr addrspace(1) [[PTR7]], align 1
; CHECK-NOOPT-NEXT:    [[PTR8:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 8
; CHECK-NOOPT-NEXT:    store i8 [[S8]], ptr addrspace(1) [[PTR8]], align 1
; CHECK-NOOPT-NEXT:    [[PTR9:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 9
; CHECK-NOOPT-NEXT:    store i8 [[S9]], ptr addrspace(1) [[PTR9]], align 1
; CHECK-NOOPT-NEXT:    [[PTR10:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 10
; CHECK-NOOPT-NEXT:    store i8 [[S10]], ptr addrspace(1) [[PTR10]], align 1
; CHECK-NOOPT-NEXT:    [[PTR11:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 11
; CHECK-NOOPT-NEXT:    store i8 [[S11]], ptr addrspace(1) [[PTR11]], align 1
; CHECK-NOOPT-NEXT:    [[PTR12:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 12
; CHECK-NOOPT-NEXT:    store i8 [[S12]], ptr addrspace(1) [[PTR12]], align 1
; CHECK-NOOPT-NEXT:    [[PTR13:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 13
; CHECK-NOOPT-NEXT:    store i8 [[S13]], ptr addrspace(1) [[PTR13]], align 1
; CHECK-NOOPT-NEXT:    [[PTR14:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 14
; CHECK-NOOPT-NEXT:    store i8 [[S14]], ptr addrspace(1) [[PTR14]], align 1
; CHECK-NOOPT-NEXT:    [[PTR15:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 15
; CHECK-NOOPT-NEXT:    store i8 [[S15]], ptr addrspace(1) [[PTR15]], align 1
; CHECK-NOOPT-NEXT:    ret void
;
  ptr addrspace(1) %out,
  <2 x i64> %src,
  i1 %cond
) {
entry:
  %bytes = bitcast <2 x i64> %src to <16 x i8>
  %e0 = extractelement <16 x i8> %bytes, i64 0
  %e1 = extractelement <16 x i8> %bytes, i64 1
  %e2 = extractelement <16 x i8> %bytes, i64 2
  %e3 = extractelement <16 x i8> %bytes, i64 3
  %e4 = extractelement <16 x i8> %bytes, i64 4
  %e5 = extractelement <16 x i8> %bytes, i64 5
  %e6 = extractelement <16 x i8> %bytes, i64 6
  %e7 = extractelement <16 x i8> %bytes, i64 7
  %e8 = extractelement <16 x i8> %bytes, i64 8
  %e9 = extractelement <16 x i8> %bytes, i64 9
  %e10 = extractelement <16 x i8> %bytes, i64 10
  %e11 = extractelement <16 x i8> %bytes, i64 11
  %e12 = extractelement <16 x i8> %bytes, i64 12
  %e13 = extractelement <16 x i8> %bytes, i64 13
  %e14 = extractelement <16 x i8> %bytes, i64 14
  %e15 = extractelement <16 x i8> %bytes, i64 15
  %s0 = select i1 %cond, i8 %e0, i8 0
  %s1 = select i1 %cond, i8 %e1, i8 0
  %s2 = select i1 %cond, i8 %e2, i8 0
  %s3 = select i1 %cond, i8 %e3, i8 0
  %s4 = select i1 %cond, i8 %e4, i8 0
  %s5 = select i1 %cond, i8 %e5, i8 0
  %s6 = select i1 %cond, i8 %e6, i8 0
  %s7 = select i1 %cond, i8 %e7, i8 0
  %s8 = select i1 %cond, i8 %e8, i8 0
  %s9 = select i1 %cond, i8 %e9, i8 0
  %s10 = select i1 %cond, i8 %e10, i8 0
  %s11 = select i1 %cond, i8 %e11, i8 0
  %s12 = select i1 %cond, i8 %e12, i8 0
  %s13 = select i1 %cond, i8 %e13, i8 0
  %s14 = select i1 %cond, i8 %e14, i8 0
  %s15 = select i1 %cond, i8 %e15, i8 0
  store i8 %s0, ptr addrspace(1) %out, align 1
  %ptr1 = getelementptr i8, ptr addrspace(1) %out, i64 1
  store i8 %s1, ptr addrspace(1) %ptr1, align 1
  %ptr2 = getelementptr i8, ptr addrspace(1) %out, i64 2
  store i8 %s2, ptr addrspace(1) %ptr2, align 1
  %ptr3 = getelementptr i8, ptr addrspace(1) %out, i64 3
  store i8 %s3, ptr addrspace(1) %ptr3, align 1
  %ptr4 = getelementptr i8, ptr addrspace(1) %out, i64 4
  store i8 %s4, ptr addrspace(1) %ptr4, align 1
  %ptr5 = getelementptr i8, ptr addrspace(1) %out, i64 5
  store i8 %s5, ptr addrspace(1) %ptr5, align 1
  %ptr6 = getelementptr i8, ptr addrspace(1) %out, i64 6
  store i8 %s6, ptr addrspace(1) %ptr6, align 1
  %ptr7 = getelementptr i8, ptr addrspace(1) %out, i64 7
  store i8 %s7, ptr addrspace(1) %ptr7, align 1
  %ptr8 = getelementptr i8, ptr addrspace(1) %out, i64 8
  store i8 %s8, ptr addrspace(1) %ptr8, align 1
  %ptr9 = getelementptr i8, ptr addrspace(1) %out, i64 9
  store i8 %s9, ptr addrspace(1) %ptr9, align 1
  %ptr10 = getelementptr i8, ptr addrspace(1) %out, i64 10
  store i8 %s10, ptr addrspace(1) %ptr10, align 1
  %ptr11 = getelementptr i8, ptr addrspace(1) %out, i64 11
  store i8 %s11, ptr addrspace(1) %ptr11, align 1
  %ptr12 = getelementptr i8, ptr addrspace(1) %out, i64 12
  store i8 %s12, ptr addrspace(1) %ptr12, align 1
  %ptr13 = getelementptr i8, ptr addrspace(1) %out, i64 13
  store i8 %s13, ptr addrspace(1) %ptr13, align 1
  %ptr14 = getelementptr i8, ptr addrspace(1) %out, i64 14
  store i8 %s14, ptr addrspace(1) %ptr14, align 1
  %ptr15 = getelementptr i8, ptr addrspace(1) %out, i64 15
  store i8 %s15, ptr addrspace(1) %ptr15, align 1
  ret void
}

; Test <2 x i64> to <8 x i16> (64-bit elements to 16-bit elements)
define amdgpu_kernel void @combine_v2i64_to_v8i16(
; CHECK-OPT-LABEL: define amdgpu_kernel void @combine_v2i64_to_v8i16(
; CHECK-OPT-SAME: ptr addrspace(1) [[OUT:%.*]], <2 x i64> [[SRC:%.*]], i1 [[COND:%.*]]) #[[ATTR0]] {
; CHECK-OPT-NEXT:  [[ENTRY:.*:]]
; CHECK-OPT-NEXT:    [[COMBINED_SEL:%.*]] = select i1 [[COND]], <2 x i64> [[SRC]], <2 x i64> zeroinitializer
; CHECK-OPT-NEXT:    [[COMBINED_BC:%.*]] = bitcast <2 x i64> [[COMBINED_SEL]] to <8 x i16>
; CHECK-OPT-NEXT:    [[TMP0:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 0
; CHECK-OPT-NEXT:    [[TMP3:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 1
; CHECK-OPT-NEXT:    [[TMP5:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 2
; CHECK-OPT-NEXT:    [[TMP7:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 3
; CHECK-OPT-NEXT:    [[TMP2:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 4
; CHECK-OPT-NEXT:    [[TMP4:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 5
; CHECK-OPT-NEXT:    [[TMP6:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 6
; CHECK-OPT-NEXT:    [[TMP1:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 7
; CHECK-OPT-NEXT:    store i16 [[TMP0]], ptr addrspace(1) [[OUT]], align 2
; CHECK-OPT-NEXT:    [[PTR1:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 1
; CHECK-OPT-NEXT:    store i16 [[TMP3]], ptr addrspace(1) [[PTR1]], align 2
; CHECK-OPT-NEXT:    [[PTR2:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 2
; CHECK-OPT-NEXT:    store i16 [[TMP5]], ptr addrspace(1) [[PTR2]], align 2
; CHECK-OPT-NEXT:    [[PTR3:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 3
; CHECK-OPT-NEXT:    store i16 [[TMP7]], ptr addrspace(1) [[PTR3]], align 2
; CHECK-OPT-NEXT:    [[PTR4:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 4
; CHECK-OPT-NEXT:    store i16 [[TMP2]], ptr addrspace(1) [[PTR4]], align 2
; CHECK-OPT-NEXT:    [[PTR5:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 5
; CHECK-OPT-NEXT:    store i16 [[TMP4]], ptr addrspace(1) [[PTR5]], align 2
; CHECK-OPT-NEXT:    [[PTR6:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 6
; CHECK-OPT-NEXT:    store i16 [[TMP6]], ptr addrspace(1) [[PTR6]], align 2
; CHECK-OPT-NEXT:    [[PTR7:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 7
; CHECK-OPT-NEXT:    store i16 [[TMP1]], ptr addrspace(1) [[PTR7]], align 2
; CHECK-OPT-NEXT:    ret void
;
; CHECK-NOOPT-LABEL: define amdgpu_kernel void @combine_v2i64_to_v8i16(
; CHECK-NOOPT-SAME: ptr addrspace(1) [[OUT:%.*]], <2 x i64> [[SRC:%.*]], i1 [[COND:%.*]]) #[[ATTR0]] {
; CHECK-NOOPT-NEXT:  [[ENTRY:.*:]]
; CHECK-NOOPT-NEXT:    [[HALVES:%.*]] = bitcast <2 x i64> [[SRC]] to <8 x i16>
; CHECK-NOOPT-NEXT:    [[E0:%.*]] = extractelement <8 x i16> [[HALVES]], i64 0
; CHECK-NOOPT-NEXT:    [[E1:%.*]] = extractelement <8 x i16> [[HALVES]], i64 1
; CHECK-NOOPT-NEXT:    [[E2:%.*]] = extractelement <8 x i16> [[HALVES]], i64 2
; CHECK-NOOPT-NEXT:    [[E3:%.*]] = extractelement <8 x i16> [[HALVES]], i64 3
; CHECK-NOOPT-NEXT:    [[E4:%.*]] = extractelement <8 x i16> [[HALVES]], i64 4
; CHECK-NOOPT-NEXT:    [[E5:%.*]] = extractelement <8 x i16> [[HALVES]], i64 5
; CHECK-NOOPT-NEXT:    [[E6:%.*]] = extractelement <8 x i16> [[HALVES]], i64 6
; CHECK-NOOPT-NEXT:    [[E7:%.*]] = extractelement <8 x i16> [[HALVES]], i64 7
; CHECK-NOOPT-NEXT:    [[S0:%.*]] = select i1 [[COND]], i16 [[E0]], i16 0
; CHECK-NOOPT-NEXT:    [[S1:%.*]] = select i1 [[COND]], i16 [[E1]], i16 0
; CHECK-NOOPT-NEXT:    [[S2:%.*]] = select i1 [[COND]], i16 [[E2]], i16 0
; CHECK-NOOPT-NEXT:    [[S3:%.*]] = select i1 [[COND]], i16 [[E3]], i16 0
; CHECK-NOOPT-NEXT:    [[S4:%.*]] = select i1 [[COND]], i16 [[E4]], i16 0
; CHECK-NOOPT-NEXT:    [[S5:%.*]] = select i1 [[COND]], i16 [[E5]], i16 0
; CHECK-NOOPT-NEXT:    [[S6:%.*]] = select i1 [[COND]], i16 [[E6]], i16 0
; CHECK-NOOPT-NEXT:    [[S7:%.*]] = select i1 [[COND]], i16 [[E7]], i16 0
; CHECK-NOOPT-NEXT:    store i16 [[S0]], ptr addrspace(1) [[OUT]], align 2
; CHECK-NOOPT-NEXT:    [[PTR1:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 1
; CHECK-NOOPT-NEXT:    store i16 [[S1]], ptr addrspace(1) [[PTR1]], align 2
; CHECK-NOOPT-NEXT:    [[PTR2:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 2
; CHECK-NOOPT-NEXT:    store i16 [[S2]], ptr addrspace(1) [[PTR2]], align 2
; CHECK-NOOPT-NEXT:    [[PTR3:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 3
; CHECK-NOOPT-NEXT:    store i16 [[S3]], ptr addrspace(1) [[PTR3]], align 2
; CHECK-NOOPT-NEXT:    [[PTR4:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 4
; CHECK-NOOPT-NEXT:    store i16 [[S4]], ptr addrspace(1) [[PTR4]], align 2
; CHECK-NOOPT-NEXT:    [[PTR5:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 5
; CHECK-NOOPT-NEXT:    store i16 [[S5]], ptr addrspace(1) [[PTR5]], align 2
; CHECK-NOOPT-NEXT:    [[PTR6:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 6
; CHECK-NOOPT-NEXT:    store i16 [[S6]], ptr addrspace(1) [[PTR6]], align 2
; CHECK-NOOPT-NEXT:    [[PTR7:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 7
; CHECK-NOOPT-NEXT:    store i16 [[S7]], ptr addrspace(1) [[PTR7]], align 2
; CHECK-NOOPT-NEXT:    ret void
;
  ptr addrspace(1) %out,
  <2 x i64> %src,
  i1 %cond
) {
entry:
  %halves = bitcast <2 x i64> %src to <8 x i16>
  %e0 = extractelement <8 x i16> %halves, i64 0
  %e1 = extractelement <8 x i16> %halves, i64 1
  %e2 = extractelement <8 x i16> %halves, i64 2
  %e3 = extractelement <8 x i16> %halves, i64 3
  %e4 = extractelement <8 x i16> %halves, i64 4
  %e5 = extractelement <8 x i16> %halves, i64 5
  %e6 = extractelement <8 x i16> %halves, i64 6
  %e7 = extractelement <8 x i16> %halves, i64 7
  %s0 = select i1 %cond, i16 %e0, i16 0
  %s1 = select i1 %cond, i16 %e1, i16 0
  %s2 = select i1 %cond, i16 %e2, i16 0
  %s3 = select i1 %cond, i16 %e3, i16 0
  %s4 = select i1 %cond, i16 %e4, i16 0
  %s5 = select i1 %cond, i16 %e5, i16 0
  %s6 = select i1 %cond, i16 %e6, i16 0
  %s7 = select i1 %cond, i16 %e7, i16 0
  store i16 %s0, ptr addrspace(1) %out, align 2
  %ptr1 = getelementptr i16, ptr addrspace(1) %out, i64 1
  store i16 %s1, ptr addrspace(1) %ptr1, align 2
  %ptr2 = getelementptr i16, ptr addrspace(1) %out, i64 2
  store i16 %s2, ptr addrspace(1) %ptr2, align 2
  %ptr3 = getelementptr i16, ptr addrspace(1) %out, i64 3
  store i16 %s3, ptr addrspace(1) %ptr3, align 2
  %ptr4 = getelementptr i16, ptr addrspace(1) %out, i64 4
  store i16 %s4, ptr addrspace(1) %ptr4, align 2
  %ptr5 = getelementptr i16, ptr addrspace(1) %out, i64 5
  store i16 %s5, ptr addrspace(1) %ptr5, align 2
  %ptr6 = getelementptr i16, ptr addrspace(1) %out, i64 6
  store i16 %s6, ptr addrspace(1) %ptr6, align 2
  %ptr7 = getelementptr i16, ptr addrspace(1) %out, i64 7
  store i16 %s7, ptr addrspace(1) %ptr7, align 2
  ret void
}

; Test <2 x i64> to <4 x i32> (64-bit elements to 32-bit elements)
define amdgpu_kernel void @combine_v2i64_to_v4i32(
; CHECK-OPT-LABEL: define amdgpu_kernel void @combine_v2i64_to_v4i32(
; CHECK-OPT-SAME: ptr addrspace(1) [[OUT:%.*]], <2 x i64> [[SRC:%.*]], i1 [[COND:%.*]]) #[[ATTR0]] {
; CHECK-OPT-NEXT:  [[ENTRY:.*:]]
; CHECK-OPT-NEXT:    [[COMBINED_SEL:%.*]] = select i1 [[COND]], <2 x i64> [[SRC]], <2 x i64> zeroinitializer
; CHECK-OPT-NEXT:    [[COMBINED_BC:%.*]] = bitcast <2 x i64> [[COMBINED_SEL]] to <4 x i32>
; CHECK-OPT-NEXT:    [[TMP0:%.*]] = extractelement <4 x i32> [[COMBINED_BC]], i64 0
; CHECK-OPT-NEXT:    [[TMP1:%.*]] = extractelement <4 x i32> [[COMBINED_BC]], i64 1
; CHECK-OPT-NEXT:    [[TMP2:%.*]] = extractelement <4 x i32> [[COMBINED_BC]], i64 2
; CHECK-OPT-NEXT:    [[TMP3:%.*]] = extractelement <4 x i32> [[COMBINED_BC]], i64 3
; CHECK-OPT-NEXT:    store i32 [[TMP0]], ptr addrspace(1) [[OUT]], align 4
; CHECK-OPT-NEXT:    [[PTR1:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i64 1
; CHECK-OPT-NEXT:    store i32 [[TMP1]], ptr addrspace(1) [[PTR1]], align 4
; CHECK-OPT-NEXT:    [[PTR2:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i64 2
; CHECK-OPT-NEXT:    store i32 [[TMP2]], ptr addrspace(1) [[PTR2]], align 4
; CHECK-OPT-NEXT:    [[PTR3:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i64 3
; CHECK-OPT-NEXT:    store i32 [[TMP3]], ptr addrspace(1) [[PTR3]], align 4
; CHECK-OPT-NEXT:    ret void
;
; CHECK-NOOPT-LABEL: define amdgpu_kernel void @combine_v2i64_to_v4i32(
; CHECK-NOOPT-SAME: ptr addrspace(1) [[OUT:%.*]], <2 x i64> [[SRC:%.*]], i1 [[COND:%.*]]) #[[ATTR0]] {
; CHECK-NOOPT-NEXT:  [[ENTRY:.*:]]
; CHECK-NOOPT-NEXT:    [[WORDS:%.*]] = bitcast <2 x i64> [[SRC]] to <4 x i32>
; CHECK-NOOPT-NEXT:    [[E0:%.*]] = extractelement <4 x i32> [[WORDS]], i64 0
; CHECK-NOOPT-NEXT:    [[E1:%.*]] = extractelement <4 x i32> [[WORDS]], i64 1
; CHECK-NOOPT-NEXT:    [[E2:%.*]] = extractelement <4 x i32> [[WORDS]], i64 2
; CHECK-NOOPT-NEXT:    [[E3:%.*]] = extractelement <4 x i32> [[WORDS]], i64 3
; CHECK-NOOPT-NEXT:    [[S0:%.*]] = select i1 [[COND]], i32 [[E0]], i32 0
; CHECK-NOOPT-NEXT:    [[S1:%.*]] = select i1 [[COND]], i32 [[E1]], i32 0
; CHECK-NOOPT-NEXT:    [[S2:%.*]] = select i1 [[COND]], i32 [[E2]], i32 0
; CHECK-NOOPT-NEXT:    [[S3:%.*]] = select i1 [[COND]], i32 [[E3]], i32 0
; CHECK-NOOPT-NEXT:    store i32 [[S0]], ptr addrspace(1) [[OUT]], align 4
; CHECK-NOOPT-NEXT:    [[PTR1:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i64 1
; CHECK-NOOPT-NEXT:    store i32 [[S1]], ptr addrspace(1) [[PTR1]], align 4
; CHECK-NOOPT-NEXT:    [[PTR2:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i64 2
; CHECK-NOOPT-NEXT:    store i32 [[S2]], ptr addrspace(1) [[PTR2]], align 4
; CHECK-NOOPT-NEXT:    [[PTR3:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i64 3
; CHECK-NOOPT-NEXT:    store i32 [[S3]], ptr addrspace(1) [[PTR3]], align 4
; CHECK-NOOPT-NEXT:    ret void
;
  ptr addrspace(1) %out,
  <2 x i64> %src,
  i1 %cond
) {
entry:
  %words = bitcast <2 x i64> %src to <4 x i32>
  %e0 = extractelement <4 x i32> %words, i64 0
  %e1 = extractelement <4 x i32> %words, i64 1
  %e2 = extractelement <4 x i32> %words, i64 2
  %e3 = extractelement <4 x i32> %words, i64 3
  %s0 = select i1 %cond, i32 %e0, i32 0
  %s1 = select i1 %cond, i32 %e1, i32 0
  %s2 = select i1 %cond, i32 %e2, i32 0
  %s3 = select i1 %cond, i32 %e3, i32 0
  store i32 %s0, ptr addrspace(1) %out, align 4
  %ptr1 = getelementptr i32, ptr addrspace(1) %out, i64 1
  store i32 %s1, ptr addrspace(1) %ptr1, align 4
  %ptr2 = getelementptr i32, ptr addrspace(1) %out, i64 2
  store i32 %s2, ptr addrspace(1) %ptr2, align 4
  %ptr3 = getelementptr i32, ptr addrspace(1) %out, i64 3
  store i32 %s3, ptr addrspace(1) %ptr3, align 4
  ret void
}

; Test <2 x double> to <16 x i8> (double elements to byte elements)
define amdgpu_kernel void @combine_v2f64_to_v16i8(
; CHECK-OPT-LABEL: define amdgpu_kernel void @combine_v2f64_to_v16i8(
; CHECK-OPT-SAME: ptr addrspace(1) [[OUT:%.*]], <2 x double> [[SRC:%.*]], i1 [[COND:%.*]]) #[[ATTR0]] {
; CHECK-OPT-NEXT:  [[ENTRY:.*:]]
; CHECK-OPT-NEXT:    [[COMBINED_SEL:%.*]] = select i1 [[COND]], <2 x double> [[SRC]], <2 x double> zeroinitializer
; CHECK-OPT-NEXT:    [[COMBINED_BC:%.*]] = bitcast <2 x double> [[COMBINED_SEL]] to <16 x i8>
; CHECK-OPT-NEXT:    [[TMP0:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 0
; CHECK-OPT-NEXT:    [[TMP9:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 1
; CHECK-OPT-NEXT:    [[TMP3:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 2
; CHECK-OPT-NEXT:    [[TMP12:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 3
; CHECK-OPT-NEXT:    [[TMP5:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 4
; CHECK-OPT-NEXT:    [[TMP14:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 5
; CHECK-OPT-NEXT:    [[TMP7:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 6
; CHECK-OPT-NEXT:    [[TMP1:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 7
; CHECK-OPT-NEXT:    [[TMP10:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 8
; CHECK-OPT-NEXT:    [[TMP4:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 9
; CHECK-OPT-NEXT:    [[TMP13:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 10
; CHECK-OPT-NEXT:    [[TMP6:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 11
; CHECK-OPT-NEXT:    [[TMP15:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 12
; CHECK-OPT-NEXT:    [[TMP8:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 13
; CHECK-OPT-NEXT:    [[TMP2:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 14
; CHECK-OPT-NEXT:    [[TMP11:%.*]] = extractelement <16 x i8> [[COMBINED_BC]], i64 15
; CHECK-OPT-NEXT:    store i8 [[TMP0]], ptr addrspace(1) [[OUT]], align 1
; CHECK-OPT-NEXT:    [[PTR1:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 1
; CHECK-OPT-NEXT:    store i8 [[TMP9]], ptr addrspace(1) [[PTR1]], align 1
; CHECK-OPT-NEXT:    [[PTR2:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 2
; CHECK-OPT-NEXT:    store i8 [[TMP3]], ptr addrspace(1) [[PTR2]], align 1
; CHECK-OPT-NEXT:    [[PTR3:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 3
; CHECK-OPT-NEXT:    store i8 [[TMP12]], ptr addrspace(1) [[PTR3]], align 1
; CHECK-OPT-NEXT:    [[PTR4:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 4
; CHECK-OPT-NEXT:    store i8 [[TMP5]], ptr addrspace(1) [[PTR4]], align 1
; CHECK-OPT-NEXT:    [[PTR5:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 5
; CHECK-OPT-NEXT:    store i8 [[TMP14]], ptr addrspace(1) [[PTR5]], align 1
; CHECK-OPT-NEXT:    [[PTR6:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 6
; CHECK-OPT-NEXT:    store i8 [[TMP7]], ptr addrspace(1) [[PTR6]], align 1
; CHECK-OPT-NEXT:    [[PTR7:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 7
; CHECK-OPT-NEXT:    store i8 [[TMP1]], ptr addrspace(1) [[PTR7]], align 1
; CHECK-OPT-NEXT:    [[PTR8:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 8
; CHECK-OPT-NEXT:    store i8 [[TMP10]], ptr addrspace(1) [[PTR8]], align 1
; CHECK-OPT-NEXT:    [[PTR9:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 9
; CHECK-OPT-NEXT:    store i8 [[TMP4]], ptr addrspace(1) [[PTR9]], align 1
; CHECK-OPT-NEXT:    [[PTR10:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 10
; CHECK-OPT-NEXT:    store i8 [[TMP13]], ptr addrspace(1) [[PTR10]], align 1
; CHECK-OPT-NEXT:    [[PTR11:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 11
; CHECK-OPT-NEXT:    store i8 [[TMP6]], ptr addrspace(1) [[PTR11]], align 1
; CHECK-OPT-NEXT:    [[PTR12:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 12
; CHECK-OPT-NEXT:    store i8 [[TMP15]], ptr addrspace(1) [[PTR12]], align 1
; CHECK-OPT-NEXT:    [[PTR13:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 13
; CHECK-OPT-NEXT:    store i8 [[TMP8]], ptr addrspace(1) [[PTR13]], align 1
; CHECK-OPT-NEXT:    [[PTR14:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 14
; CHECK-OPT-NEXT:    store i8 [[TMP2]], ptr addrspace(1) [[PTR14]], align 1
; CHECK-OPT-NEXT:    [[PTR15:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 15
; CHECK-OPT-NEXT:    store i8 [[TMP11]], ptr addrspace(1) [[PTR15]], align 1
; CHECK-OPT-NEXT:    ret void
;
; CHECK-NOOPT-LABEL: define amdgpu_kernel void @combine_v2f64_to_v16i8(
; CHECK-NOOPT-SAME: ptr addrspace(1) [[OUT:%.*]], <2 x double> [[SRC:%.*]], i1 [[COND:%.*]]) #[[ATTR0]] {
; CHECK-NOOPT-NEXT:  [[ENTRY:.*:]]
; CHECK-NOOPT-NEXT:    [[BYTES:%.*]] = bitcast <2 x double> [[SRC]] to <16 x i8>
; CHECK-NOOPT-NEXT:    [[E0:%.*]] = extractelement <16 x i8> [[BYTES]], i64 0
; CHECK-NOOPT-NEXT:    [[E1:%.*]] = extractelement <16 x i8> [[BYTES]], i64 1
; CHECK-NOOPT-NEXT:    [[E2:%.*]] = extractelement <16 x i8> [[BYTES]], i64 2
; CHECK-NOOPT-NEXT:    [[E3:%.*]] = extractelement <16 x i8> [[BYTES]], i64 3
; CHECK-NOOPT-NEXT:    [[E4:%.*]] = extractelement <16 x i8> [[BYTES]], i64 4
; CHECK-NOOPT-NEXT:    [[E5:%.*]] = extractelement <16 x i8> [[BYTES]], i64 5
; CHECK-NOOPT-NEXT:    [[E6:%.*]] = extractelement <16 x i8> [[BYTES]], i64 6
; CHECK-NOOPT-NEXT:    [[E7:%.*]] = extractelement <16 x i8> [[BYTES]], i64 7
; CHECK-NOOPT-NEXT:    [[E8:%.*]] = extractelement <16 x i8> [[BYTES]], i64 8
; CHECK-NOOPT-NEXT:    [[E9:%.*]] = extractelement <16 x i8> [[BYTES]], i64 9
; CHECK-NOOPT-NEXT:    [[E10:%.*]] = extractelement <16 x i8> [[BYTES]], i64 10
; CHECK-NOOPT-NEXT:    [[E11:%.*]] = extractelement <16 x i8> [[BYTES]], i64 11
; CHECK-NOOPT-NEXT:    [[E12:%.*]] = extractelement <16 x i8> [[BYTES]], i64 12
; CHECK-NOOPT-NEXT:    [[E13:%.*]] = extractelement <16 x i8> [[BYTES]], i64 13
; CHECK-NOOPT-NEXT:    [[E14:%.*]] = extractelement <16 x i8> [[BYTES]], i64 14
; CHECK-NOOPT-NEXT:    [[E15:%.*]] = extractelement <16 x i8> [[BYTES]], i64 15
; CHECK-NOOPT-NEXT:    [[S0:%.*]] = select i1 [[COND]], i8 [[E0]], i8 0
; CHECK-NOOPT-NEXT:    [[S1:%.*]] = select i1 [[COND]], i8 [[E1]], i8 0
; CHECK-NOOPT-NEXT:    [[S2:%.*]] = select i1 [[COND]], i8 [[E2]], i8 0
; CHECK-NOOPT-NEXT:    [[S3:%.*]] = select i1 [[COND]], i8 [[E3]], i8 0
; CHECK-NOOPT-NEXT:    [[S4:%.*]] = select i1 [[COND]], i8 [[E4]], i8 0
; CHECK-NOOPT-NEXT:    [[S5:%.*]] = select i1 [[COND]], i8 [[E5]], i8 0
; CHECK-NOOPT-NEXT:    [[S6:%.*]] = select i1 [[COND]], i8 [[E6]], i8 0
; CHECK-NOOPT-NEXT:    [[S7:%.*]] = select i1 [[COND]], i8 [[E7]], i8 0
; CHECK-NOOPT-NEXT:    [[S8:%.*]] = select i1 [[COND]], i8 [[E8]], i8 0
; CHECK-NOOPT-NEXT:    [[S9:%.*]] = select i1 [[COND]], i8 [[E9]], i8 0
; CHECK-NOOPT-NEXT:    [[S10:%.*]] = select i1 [[COND]], i8 [[E10]], i8 0
; CHECK-NOOPT-NEXT:    [[S11:%.*]] = select i1 [[COND]], i8 [[E11]], i8 0
; CHECK-NOOPT-NEXT:    [[S12:%.*]] = select i1 [[COND]], i8 [[E12]], i8 0
; CHECK-NOOPT-NEXT:    [[S13:%.*]] = select i1 [[COND]], i8 [[E13]], i8 0
; CHECK-NOOPT-NEXT:    [[S14:%.*]] = select i1 [[COND]], i8 [[E14]], i8 0
; CHECK-NOOPT-NEXT:    [[S15:%.*]] = select i1 [[COND]], i8 [[E15]], i8 0
; CHECK-NOOPT-NEXT:    store i8 [[S0]], ptr addrspace(1) [[OUT]], align 1
; CHECK-NOOPT-NEXT:    [[PTR1:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 1
; CHECK-NOOPT-NEXT:    store i8 [[S1]], ptr addrspace(1) [[PTR1]], align 1
; CHECK-NOOPT-NEXT:    [[PTR2:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 2
; CHECK-NOOPT-NEXT:    store i8 [[S2]], ptr addrspace(1) [[PTR2]], align 1
; CHECK-NOOPT-NEXT:    [[PTR3:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 3
; CHECK-NOOPT-NEXT:    store i8 [[S3]], ptr addrspace(1) [[PTR3]], align 1
; CHECK-NOOPT-NEXT:    [[PTR4:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 4
; CHECK-NOOPT-NEXT:    store i8 [[S4]], ptr addrspace(1) [[PTR4]], align 1
; CHECK-NOOPT-NEXT:    [[PTR5:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 5
; CHECK-NOOPT-NEXT:    store i8 [[S5]], ptr addrspace(1) [[PTR5]], align 1
; CHECK-NOOPT-NEXT:    [[PTR6:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 6
; CHECK-NOOPT-NEXT:    store i8 [[S6]], ptr addrspace(1) [[PTR6]], align 1
; CHECK-NOOPT-NEXT:    [[PTR7:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 7
; CHECK-NOOPT-NEXT:    store i8 [[S7]], ptr addrspace(1) [[PTR7]], align 1
; CHECK-NOOPT-NEXT:    [[PTR8:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 8
; CHECK-NOOPT-NEXT:    store i8 [[S8]], ptr addrspace(1) [[PTR8]], align 1
; CHECK-NOOPT-NEXT:    [[PTR9:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 9
; CHECK-NOOPT-NEXT:    store i8 [[S9]], ptr addrspace(1) [[PTR9]], align 1
; CHECK-NOOPT-NEXT:    [[PTR10:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 10
; CHECK-NOOPT-NEXT:    store i8 [[S10]], ptr addrspace(1) [[PTR10]], align 1
; CHECK-NOOPT-NEXT:    [[PTR11:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 11
; CHECK-NOOPT-NEXT:    store i8 [[S11]], ptr addrspace(1) [[PTR11]], align 1
; CHECK-NOOPT-NEXT:    [[PTR12:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 12
; CHECK-NOOPT-NEXT:    store i8 [[S12]], ptr addrspace(1) [[PTR12]], align 1
; CHECK-NOOPT-NEXT:    [[PTR13:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 13
; CHECK-NOOPT-NEXT:    store i8 [[S13]], ptr addrspace(1) [[PTR13]], align 1
; CHECK-NOOPT-NEXT:    [[PTR14:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 14
; CHECK-NOOPT-NEXT:    store i8 [[S14]], ptr addrspace(1) [[PTR14]], align 1
; CHECK-NOOPT-NEXT:    [[PTR15:%.*]] = getelementptr i8, ptr addrspace(1) [[OUT]], i64 15
; CHECK-NOOPT-NEXT:    store i8 [[S15]], ptr addrspace(1) [[PTR15]], align 1
; CHECK-NOOPT-NEXT:    ret void
;
  ptr addrspace(1) %out,
  <2 x double> %src,
  i1 %cond
) {
entry:
  %bytes = bitcast <2 x double> %src to <16 x i8>
  %e0 = extractelement <16 x i8> %bytes, i64 0
  %e1 = extractelement <16 x i8> %bytes, i64 1
  %e2 = extractelement <16 x i8> %bytes, i64 2
  %e3 = extractelement <16 x i8> %bytes, i64 3
  %e4 = extractelement <16 x i8> %bytes, i64 4
  %e5 = extractelement <16 x i8> %bytes, i64 5
  %e6 = extractelement <16 x i8> %bytes, i64 6
  %e7 = extractelement <16 x i8> %bytes, i64 7
  %e8 = extractelement <16 x i8> %bytes, i64 8
  %e9 = extractelement <16 x i8> %bytes, i64 9
  %e10 = extractelement <16 x i8> %bytes, i64 10
  %e11 = extractelement <16 x i8> %bytes, i64 11
  %e12 = extractelement <16 x i8> %bytes, i64 12
  %e13 = extractelement <16 x i8> %bytes, i64 13
  %e14 = extractelement <16 x i8> %bytes, i64 14
  %e15 = extractelement <16 x i8> %bytes, i64 15
  %s0 = select i1 %cond, i8 %e0, i8 0
  %s1 = select i1 %cond, i8 %e1, i8 0
  %s2 = select i1 %cond, i8 %e2, i8 0
  %s3 = select i1 %cond, i8 %e3, i8 0
  %s4 = select i1 %cond, i8 %e4, i8 0
  %s5 = select i1 %cond, i8 %e5, i8 0
  %s6 = select i1 %cond, i8 %e6, i8 0
  %s7 = select i1 %cond, i8 %e7, i8 0
  %s8 = select i1 %cond, i8 %e8, i8 0
  %s9 = select i1 %cond, i8 %e9, i8 0
  %s10 = select i1 %cond, i8 %e10, i8 0
  %s11 = select i1 %cond, i8 %e11, i8 0
  %s12 = select i1 %cond, i8 %e12, i8 0
  %s13 = select i1 %cond, i8 %e13, i8 0
  %s14 = select i1 %cond, i8 %e14, i8 0
  %s15 = select i1 %cond, i8 %e15, i8 0
  store i8 %s0, ptr addrspace(1) %out, align 1
  %ptr1 = getelementptr i8, ptr addrspace(1) %out, i64 1
  store i8 %s1, ptr addrspace(1) %ptr1, align 1
  %ptr2 = getelementptr i8, ptr addrspace(1) %out, i64 2
  store i8 %s2, ptr addrspace(1) %ptr2, align 1
  %ptr3 = getelementptr i8, ptr addrspace(1) %out, i64 3
  store i8 %s3, ptr addrspace(1) %ptr3, align 1
  %ptr4 = getelementptr i8, ptr addrspace(1) %out, i64 4
  store i8 %s4, ptr addrspace(1) %ptr4, align 1
  %ptr5 = getelementptr i8, ptr addrspace(1) %out, i64 5
  store i8 %s5, ptr addrspace(1) %ptr5, align 1
  %ptr6 = getelementptr i8, ptr addrspace(1) %out, i64 6
  store i8 %s6, ptr addrspace(1) %ptr6, align 1
  %ptr7 = getelementptr i8, ptr addrspace(1) %out, i64 7
  store i8 %s7, ptr addrspace(1) %ptr7, align 1
  %ptr8 = getelementptr i8, ptr addrspace(1) %out, i64 8
  store i8 %s8, ptr addrspace(1) %ptr8, align 1
  %ptr9 = getelementptr i8, ptr addrspace(1) %out, i64 9
  store i8 %s9, ptr addrspace(1) %ptr9, align 1
  %ptr10 = getelementptr i8, ptr addrspace(1) %out, i64 10
  store i8 %s10, ptr addrspace(1) %ptr10, align 1
  %ptr11 = getelementptr i8, ptr addrspace(1) %out, i64 11
  store i8 %s11, ptr addrspace(1) %ptr11, align 1
  %ptr12 = getelementptr i8, ptr addrspace(1) %out, i64 12
  store i8 %s12, ptr addrspace(1) %ptr12, align 1
  %ptr13 = getelementptr i8, ptr addrspace(1) %out, i64 13
  store i8 %s13, ptr addrspace(1) %ptr13, align 1
  %ptr14 = getelementptr i8, ptr addrspace(1) %out, i64 14
  store i8 %s14, ptr addrspace(1) %ptr14, align 1
  %ptr15 = getelementptr i8, ptr addrspace(1) %out, i64 15
  store i8 %s15, ptr addrspace(1) %ptr15, align 1
  ret void
}

; Test <2 x double> to <8 x i16> (double elements to 16-bit elements)
define amdgpu_kernel void @combine_v2f64_to_v8i16(
; CHECK-OPT-LABEL: define amdgpu_kernel void @combine_v2f64_to_v8i16(
; CHECK-OPT-SAME: ptr addrspace(1) [[OUT:%.*]], <2 x double> [[SRC:%.*]], i1 [[COND:%.*]]) #[[ATTR0]] {
; CHECK-OPT-NEXT:  [[ENTRY:.*:]]
; CHECK-OPT-NEXT:    [[COMBINED_SEL:%.*]] = select i1 [[COND]], <2 x double> [[SRC]], <2 x double> zeroinitializer
; CHECK-OPT-NEXT:    [[COMBINED_BC:%.*]] = bitcast <2 x double> [[COMBINED_SEL]] to <8 x i16>
; CHECK-OPT-NEXT:    [[TMP0:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 0
; CHECK-OPT-NEXT:    [[TMP3:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 1
; CHECK-OPT-NEXT:    [[TMP5:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 2
; CHECK-OPT-NEXT:    [[TMP7:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 3
; CHECK-OPT-NEXT:    [[TMP2:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 4
; CHECK-OPT-NEXT:    [[TMP4:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 5
; CHECK-OPT-NEXT:    [[TMP6:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 6
; CHECK-OPT-NEXT:    [[TMP1:%.*]] = extractelement <8 x i16> [[COMBINED_BC]], i64 7
; CHECK-OPT-NEXT:    store i16 [[TMP0]], ptr addrspace(1) [[OUT]], align 2
; CHECK-OPT-NEXT:    [[PTR1:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 1
; CHECK-OPT-NEXT:    store i16 [[TMP3]], ptr addrspace(1) [[PTR1]], align 2
; CHECK-OPT-NEXT:    [[PTR2:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 2
; CHECK-OPT-NEXT:    store i16 [[TMP5]], ptr addrspace(1) [[PTR2]], align 2
; CHECK-OPT-NEXT:    [[PTR3:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 3
; CHECK-OPT-NEXT:    store i16 [[TMP7]], ptr addrspace(1) [[PTR3]], align 2
; CHECK-OPT-NEXT:    [[PTR4:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 4
; CHECK-OPT-NEXT:    store i16 [[TMP2]], ptr addrspace(1) [[PTR4]], align 2
; CHECK-OPT-NEXT:    [[PTR5:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 5
; CHECK-OPT-NEXT:    store i16 [[TMP4]], ptr addrspace(1) [[PTR5]], align 2
; CHECK-OPT-NEXT:    [[PTR6:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 6
; CHECK-OPT-NEXT:    store i16 [[TMP6]], ptr addrspace(1) [[PTR6]], align 2
; CHECK-OPT-NEXT:    [[PTR7:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 7
; CHECK-OPT-NEXT:    store i16 [[TMP1]], ptr addrspace(1) [[PTR7]], align 2
; CHECK-OPT-NEXT:    ret void
;
; CHECK-NOOPT-LABEL: define amdgpu_kernel void @combine_v2f64_to_v8i16(
; CHECK-NOOPT-SAME: ptr addrspace(1) [[OUT:%.*]], <2 x double> [[SRC:%.*]], i1 [[COND:%.*]]) #[[ATTR0]] {
; CHECK-NOOPT-NEXT:  [[ENTRY:.*:]]
; CHECK-NOOPT-NEXT:    [[HALVES:%.*]] = bitcast <2 x double> [[SRC]] to <8 x i16>
; CHECK-NOOPT-NEXT:    [[E0:%.*]] = extractelement <8 x i16> [[HALVES]], i64 0
; CHECK-NOOPT-NEXT:    [[E1:%.*]] = extractelement <8 x i16> [[HALVES]], i64 1
; CHECK-NOOPT-NEXT:    [[E2:%.*]] = extractelement <8 x i16> [[HALVES]], i64 2
; CHECK-NOOPT-NEXT:    [[E3:%.*]] = extractelement <8 x i16> [[HALVES]], i64 3
; CHECK-NOOPT-NEXT:    [[E4:%.*]] = extractelement <8 x i16> [[HALVES]], i64 4
; CHECK-NOOPT-NEXT:    [[E5:%.*]] = extractelement <8 x i16> [[HALVES]], i64 5
; CHECK-NOOPT-NEXT:    [[E6:%.*]] = extractelement <8 x i16> [[HALVES]], i64 6
; CHECK-NOOPT-NEXT:    [[E7:%.*]] = extractelement <8 x i16> [[HALVES]], i64 7
; CHECK-NOOPT-NEXT:    [[S0:%.*]] = select i1 [[COND]], i16 [[E0]], i16 0
; CHECK-NOOPT-NEXT:    [[S1:%.*]] = select i1 [[COND]], i16 [[E1]], i16 0
; CHECK-NOOPT-NEXT:    [[S2:%.*]] = select i1 [[COND]], i16 [[E2]], i16 0
; CHECK-NOOPT-NEXT:    [[S3:%.*]] = select i1 [[COND]], i16 [[E3]], i16 0
; CHECK-NOOPT-NEXT:    [[S4:%.*]] = select i1 [[COND]], i16 [[E4]], i16 0
; CHECK-NOOPT-NEXT:    [[S5:%.*]] = select i1 [[COND]], i16 [[E5]], i16 0
; CHECK-NOOPT-NEXT:    [[S6:%.*]] = select i1 [[COND]], i16 [[E6]], i16 0
; CHECK-NOOPT-NEXT:    [[S7:%.*]] = select i1 [[COND]], i16 [[E7]], i16 0
; CHECK-NOOPT-NEXT:    store i16 [[S0]], ptr addrspace(1) [[OUT]], align 2
; CHECK-NOOPT-NEXT:    [[PTR1:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 1
; CHECK-NOOPT-NEXT:    store i16 [[S1]], ptr addrspace(1) [[PTR1]], align 2
; CHECK-NOOPT-NEXT:    [[PTR2:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 2
; CHECK-NOOPT-NEXT:    store i16 [[S2]], ptr addrspace(1) [[PTR2]], align 2
; CHECK-NOOPT-NEXT:    [[PTR3:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 3
; CHECK-NOOPT-NEXT:    store i16 [[S3]], ptr addrspace(1) [[PTR3]], align 2
; CHECK-NOOPT-NEXT:    [[PTR4:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 4
; CHECK-NOOPT-NEXT:    store i16 [[S4]], ptr addrspace(1) [[PTR4]], align 2
; CHECK-NOOPT-NEXT:    [[PTR5:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 5
; CHECK-NOOPT-NEXT:    store i16 [[S5]], ptr addrspace(1) [[PTR5]], align 2
; CHECK-NOOPT-NEXT:    [[PTR6:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 6
; CHECK-NOOPT-NEXT:    store i16 [[S6]], ptr addrspace(1) [[PTR6]], align 2
; CHECK-NOOPT-NEXT:    [[PTR7:%.*]] = getelementptr i16, ptr addrspace(1) [[OUT]], i64 7
; CHECK-NOOPT-NEXT:    store i16 [[S7]], ptr addrspace(1) [[PTR7]], align 2
; CHECK-NOOPT-NEXT:    ret void
;
  ptr addrspace(1) %out,
  <2 x double> %src,
  i1 %cond
) {
entry:
  %halves = bitcast <2 x double> %src to <8 x i16>
  %e0 = extractelement <8 x i16> %halves, i64 0
  %e1 = extractelement <8 x i16> %halves, i64 1
  %e2 = extractelement <8 x i16> %halves, i64 2
  %e3 = extractelement <8 x i16> %halves, i64 3
  %e4 = extractelement <8 x i16> %halves, i64 4
  %e5 = extractelement <8 x i16> %halves, i64 5
  %e6 = extractelement <8 x i16> %halves, i64 6
  %e7 = extractelement <8 x i16> %halves, i64 7
  %s0 = select i1 %cond, i16 %e0, i16 0
  %s1 = select i1 %cond, i16 %e1, i16 0
  %s2 = select i1 %cond, i16 %e2, i16 0
  %s3 = select i1 %cond, i16 %e3, i16 0
  %s4 = select i1 %cond, i16 %e4, i16 0
  %s5 = select i1 %cond, i16 %e5, i16 0
  %s6 = select i1 %cond, i16 %e6, i16 0
  %s7 = select i1 %cond, i16 %e7, i16 0
  store i16 %s0, ptr addrspace(1) %out, align 2
  %ptr1 = getelementptr i16, ptr addrspace(1) %out, i64 1
  store i16 %s1, ptr addrspace(1) %ptr1, align 2
  %ptr2 = getelementptr i16, ptr addrspace(1) %out, i64 2
  store i16 %s2, ptr addrspace(1) %ptr2, align 2
  %ptr3 = getelementptr i16, ptr addrspace(1) %out, i64 3
  store i16 %s3, ptr addrspace(1) %ptr3, align 2
  %ptr4 = getelementptr i16, ptr addrspace(1) %out, i64 4
  store i16 %s4, ptr addrspace(1) %ptr4, align 2
  %ptr5 = getelementptr i16, ptr addrspace(1) %out, i64 5
  store i16 %s5, ptr addrspace(1) %ptr5, align 2
  %ptr6 = getelementptr i16, ptr addrspace(1) %out, i64 6
  store i16 %s6, ptr addrspace(1) %ptr6, align 2
  %ptr7 = getelementptr i16, ptr addrspace(1) %out, i64 7
  store i16 %s7, ptr addrspace(1) %ptr7, align 2
  ret void
}

; Test <2 x double> to <4 x i32> (double elements to 32-bit elements)
define amdgpu_kernel void @combine_v2f64_to_v4i32(
; CHECK-OPT-LABEL: define amdgpu_kernel void @combine_v2f64_to_v4i32(
; CHECK-OPT-SAME: ptr addrspace(1) [[OUT:%.*]], <2 x double> [[SRC:%.*]], i1 [[COND:%.*]]) #[[ATTR0]] {
; CHECK-OPT-NEXT:  [[ENTRY:.*:]]
; CHECK-OPT-NEXT:    [[COMBINED_SEL:%.*]] = select i1 [[COND]], <2 x double> [[SRC]], <2 x double> zeroinitializer
; CHECK-OPT-NEXT:    [[COMBINED_BC:%.*]] = bitcast <2 x double> [[COMBINED_SEL]] to <4 x i32>
; CHECK-OPT-NEXT:    [[TMP0:%.*]] = extractelement <4 x i32> [[COMBINED_BC]], i64 0
; CHECK-OPT-NEXT:    [[TMP1:%.*]] = extractelement <4 x i32> [[COMBINED_BC]], i64 1
; CHECK-OPT-NEXT:    [[TMP2:%.*]] = extractelement <4 x i32> [[COMBINED_BC]], i64 2
; CHECK-OPT-NEXT:    [[TMP3:%.*]] = extractelement <4 x i32> [[COMBINED_BC]], i64 3
; CHECK-OPT-NEXT:    store i32 [[TMP0]], ptr addrspace(1) [[OUT]], align 4
; CHECK-OPT-NEXT:    [[PTR1:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i64 1
; CHECK-OPT-NEXT:    store i32 [[TMP1]], ptr addrspace(1) [[PTR1]], align 4
; CHECK-OPT-NEXT:    [[PTR2:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i64 2
; CHECK-OPT-NEXT:    store i32 [[TMP2]], ptr addrspace(1) [[PTR2]], align 4
; CHECK-OPT-NEXT:    [[PTR3:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i64 3
; CHECK-OPT-NEXT:    store i32 [[TMP3]], ptr addrspace(1) [[PTR3]], align 4
; CHECK-OPT-NEXT:    ret void
;
; CHECK-NOOPT-LABEL: define amdgpu_kernel void @combine_v2f64_to_v4i32(
; CHECK-NOOPT-SAME: ptr addrspace(1) [[OUT:%.*]], <2 x double> [[SRC:%.*]], i1 [[COND:%.*]]) #[[ATTR0]] {
; CHECK-NOOPT-NEXT:  [[ENTRY:.*:]]
; CHECK-NOOPT-NEXT:    [[WORDS:%.*]] = bitcast <2 x double> [[SRC]] to <4 x i32>
; CHECK-NOOPT-NEXT:    [[E0:%.*]] = extractelement <4 x i32> [[WORDS]], i64 0
; CHECK-NOOPT-NEXT:    [[E1:%.*]] = extractelement <4 x i32> [[WORDS]], i64 1
; CHECK-NOOPT-NEXT:    [[E2:%.*]] = extractelement <4 x i32> [[WORDS]], i64 2
; CHECK-NOOPT-NEXT:    [[E3:%.*]] = extractelement <4 x i32> [[WORDS]], i64 3
; CHECK-NOOPT-NEXT:    [[S0:%.*]] = select i1 [[COND]], i32 [[E0]], i32 0
; CHECK-NOOPT-NEXT:    [[S1:%.*]] = select i1 [[COND]], i32 [[E1]], i32 0
; CHECK-NOOPT-NEXT:    [[S2:%.*]] = select i1 [[COND]], i32 [[E2]], i32 0
; CHECK-NOOPT-NEXT:    [[S3:%.*]] = select i1 [[COND]], i32 [[E3]], i32 0
; CHECK-NOOPT-NEXT:    store i32 [[S0]], ptr addrspace(1) [[OUT]], align 4
; CHECK-NOOPT-NEXT:    [[PTR1:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i64 1
; CHECK-NOOPT-NEXT:    store i32 [[S1]], ptr addrspace(1) [[PTR1]], align 4
; CHECK-NOOPT-NEXT:    [[PTR2:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i64 2
; CHECK-NOOPT-NEXT:    store i32 [[S2]], ptr addrspace(1) [[PTR2]], align 4
; CHECK-NOOPT-NEXT:    [[PTR3:%.*]] = getelementptr i32, ptr addrspace(1) [[OUT]], i64 3
; CHECK-NOOPT-NEXT:    store i32 [[S3]], ptr addrspace(1) [[PTR3]], align 4
; CHECK-NOOPT-NEXT:    ret void
;
  ptr addrspace(1) %out,
  <2 x double> %src,
  i1 %cond
) {
entry:
  %words = bitcast <2 x double> %src to <4 x i32>
  %e0 = extractelement <4 x i32> %words, i64 0
  %e1 = extractelement <4 x i32> %words, i64 1
  %e2 = extractelement <4 x i32> %words, i64 2
  %e3 = extractelement <4 x i32> %words, i64 3
  %s0 = select i1 %cond, i32 %e0, i32 0
  %s1 = select i1 %cond, i32 %e1, i32 0
  %s2 = select i1 %cond, i32 %e2, i32 0
  %s3 = select i1 %cond, i32 %e3, i32 0
  store i32 %s0, ptr addrspace(1) %out, align 4
  %ptr1 = getelementptr i32, ptr addrspace(1) %out, i64 1
  store i32 %s1, ptr addrspace(1) %ptr1, align 4
  %ptr2 = getelementptr i32, ptr addrspace(1) %out, i64 2
  store i32 %s2, ptr addrspace(1) %ptr2, align 4
  %ptr3 = getelementptr i32, ptr addrspace(1) %out, i64 3
  store i32 %s3, ptr addrspace(1) %ptr3, align 4
  ret void
}

declare <4 x i32> @llvm.amdgcn.raw.buffer.load.v4i32(<4 x i32>, i32, i32, i32 immarg)

