; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=amdgcn -mcpu=tahiti < %s | FileCheck -check-prefix=SI %s
; RUN: llc -mtriple=amdgcn -mcpu=tonga < %s | FileCheck -check-prefix=VI %s
; RUN: llc -mtriple=amdgcn  -mcpu=tonga -global-isel=1 -new-reg-bank-select < %s | FileCheck -check-prefix=VI-GISEL %s

; FIXME: Non-power-of-2 integer types like i65 do not work with GlobalISel on
; older targets.

declare i65 @llvm.ctpop.i65(i65) nounwind readnone

define i32 @s_ctpop_i65(i65 inreg %val) nounwind {
; SI-LABEL: s_ctpop_i65:
; SI:       ; %bb.0:
; SI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; SI-NEXT:    s_and_b32 s4, s18, 1
; SI-NEXT:    s_bcnt1_i32_b32 s4, s4
; SI-NEXT:    s_bcnt1_i32_b64 s5, s[16:17]
; SI-NEXT:    s_add_i32 s5, s5, s4
; SI-NEXT:    v_mov_b32_e32 v0, s5
; SI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-LABEL: s_ctpop_i65:
; VI:       ; %bb.0:
; VI-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-NEXT:    s_and_b32 s4, s18, 1
; VI-NEXT:    s_bcnt1_i32_b32 s4, s4
; VI-NEXT:    s_bcnt1_i32_b64 s5, s[16:17]
; VI-NEXT:    s_add_i32 s5, s5, s4
; VI-NEXT:    v_mov_b32_e32 v0, s5
; VI-NEXT:    s_setpc_b64 s[30:31]
;
; VI-GISEL-LABEL: s_ctpop_i65:
; VI-GISEL:       ; %bb.0:
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; VI-GISEL-NEXT:    s_and_b64 s[4:5], s[18:19], 1
; VI-GISEL-NEXT:    s_bcnt1_i32_b64 s6, s[16:17]
; VI-GISEL-NEXT:    s_bcnt1_i32_b64 s4, s[4:5]
; VI-GISEL-NEXT:    s_add_i32 s4, s4, s6
; VI-GISEL-NEXT:    v_mov_b32_e32 v0, s4
; VI-GISEL-NEXT:    s_setpc_b64 s[30:31]
  %ctpop = call i65 @llvm.ctpop.i65(i65 %val) nounwind readnone
  %truncctpop = trunc i65 %ctpop to i32
  ret i32 %truncctpop
}
