; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx950  < %s | FileCheck %s

; Regression test for an infinite DAGCombine loop involving freeze sinking
; through extract_subvector users of this shuffle/select chain.
; See https://github.com/ROCm/llvm-project/issues/2616 for the original report.
define amdgpu_kernel void @freeze_loop(<2 x i16> %v0, i1 %cond) {
; CHECK-LABEL: freeze_loop:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    s_waitcnt lgkmcnt(0)
; CHECK-NEXT:    s_bitcmp1_b32 s1, 0
; CHECK-NEXT:    s_cselect_b32 s0, s0, 0x10001
; CHECK-NEXT:    v_mov_b32_e32 v1, s0
; CHECK-NEXT:    ds_write_b32 v0, v1
; CHECK-NEXT:    s_endpgm
  %w0 = shufflevector <2 x i16> %v0, <2 x i16> zeroinitializer, <23 x i32> <i32 0, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison, i32 poison>
  %v1 = select i1 %cond, <23 x i16> %w0, <23 x i16> zeroinitializer
  %w1 = shufflevector <23 x i16> %v1, <23 x i16> zeroinitializer, <23 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 23, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22>
  %v2 = select i1 %cond, <23 x i16> zeroinitializer, <23 x i16> %w1
  %w2 = shufflevector <23 x i16> %v2, <23 x i16> zeroinitializer, <23 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 24, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22>
  %v3 = select i1 %cond, <23 x i16> zeroinitializer, <23 x i16> %w2
  %w3 = shufflevector <23 x i16> %v3, <23 x i16> zeroinitializer, <23 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 23, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22>
  %x0 = shufflevector <23 x i16> %v1, <23 x i16> zeroinitializer, <23 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 23, i32 poison, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22>
  %v4 = select i1 %cond, <23 x i16> zeroinitializer, <23 x i16> %w3
  %w5 = shufflevector <23 x i16> %v4, <23 x i16> zeroinitializer, <23 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 24, i32 15, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22>
  %y0 = select i1 %cond, <23 x i16> %x0, <23 x i16> %w5
  %x1 = shufflevector <23 x i16> %y0, <23 x i16> zeroinitializer, <23 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 23, i32 poison, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22>
  %y1 = select i1 %cond, <23 x i16> %x1, <23 x i16> %x0
  %z0 = shufflevector <23 x i16> %y1, <23 x i16> %w0, <23 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 23, i32 poison, i32 18, i32 19, i32 20, i32 21, i32 22>
  %x2 = shufflevector <23 x i16> %y1, <23 x i16> zeroinitializer, <23 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 24, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22>
  %y2 = select i1 %cond, <23 x i16> %z0, <23 x i16> %x2
  %x3 = shufflevector <23 x i16> %y2, <23 x i16> %w0, <23 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 23, i32 poison, i32 20, i32 21, i32 22>
  %x4 = shufflevector <23 x i16> %y0, <23 x i16> zeroinitializer, <23 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 23, i32 16, i32 17, i32 18, i32 19, i32 20, i32 21, i32 22>
  %y3 = select i1 %cond, <23 x i16> %x3, <23 x i16> %x4
  %x5 = shufflevector <23 x i16> %y3, <23 x i16> %w0, <23 x i32> <i32 0, i32 1, i32 2, i32 3, i32 4, i32 5, i32 6, i32 7, i32 8, i32 9, i32 10, i32 11, i32 12, i32 13, i32 14, i32 15, i32 16, i32 17, i32 18, i32 19, i32 23, i32 poison, i32 22>
  %y4 = select i1 %cond, <23 x i16> %x5, <23 x i16> splat (i16 1)
  %x6 = shufflevector <23 x i16> %y4, <23 x i16> zeroinitializer, <2 x i32> <i32 20, i32 21>
  store <2 x i16> %x6, ptr addrspace(3) null, align 2
  ret void
}
