; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -global-isel=0 -mtriple=amdgcn -mcpu=gfx1300 < %s | FileCheck -check-prefixes=GFX13,GFX13-SDAG %s
; RUN: llc -global-isel=1 -mtriple=amdgcn -mcpu=gfx1300 < %s | FileCheck -check-prefixes=GFX13,GFX13-GISEL %s

define amdgpu_ps float @dds_load_uniform(ptr addrspace(11) inreg %ptr) {
; GFX13-LABEL: dds_load_uniform:
; GFX13:       ; %bb.0:
; GFX13-NEXT:    v_mov_b32_e32 v0, 0
; GFX13-NEXT:    dds_load_b32 v0, v0, s0
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    ; return to shader part epilog
    %load = load i32, ptr addrspace(11) %ptr
    %to.vgpr = bitcast i32 %load to float
    ret float %to.vgpr
}

define amdgpu_ps float @dds_load(ptr addrspace(11) %ptr) {
; GFX13-LABEL: dds_load:
; GFX13:       ; %bb.0:
; GFX13-NEXT:    dds_load_b32 v0, v0, off
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    ; return to shader part epilog
    %load = load i32, ptr addrspace(11) %ptr
    %to.vgpr = bitcast i32 %load to float
    ret float %to.vgpr
}

define amdgpu_ps <2 x float> @dds_load_i64_uniform(ptr addrspace(11) inreg %ptr) {
; GFX13-LABEL: dds_load_i64_uniform:
; GFX13:       ; %bb.0:
; GFX13-NEXT:    v_mov_b32_e32 v0, 0
; GFX13-NEXT:    dds_load_b64 v[0:1], v0, s0
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    ; return to shader part epilog
    %load = load i64, ptr addrspace(11) %ptr
    %to.vgpr = bitcast i64 %load to <2 x float>
    ret <2 x float> %to.vgpr
}

define amdgpu_ps <2 x float> @dds_load_i64(ptr addrspace(11) %ptr) {
; GFX13-LABEL: dds_load_i64:
; GFX13:       ; %bb.0:
; GFX13-NEXT:    dds_load_b64 v[0:1], v0, off
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    ; return to shader part epilog
    %load = load i64, ptr addrspace(11) %ptr
    %to.vgpr = bitcast i64 %load to <2 x float>
    ret <2 x float> %to.vgpr
}

define amdgpu_ps <4 x float> @dds_load_i128_uniform(ptr addrspace(11) inreg %ptr) {
; GFX13-LABEL: dds_load_i128_uniform:
; GFX13:       ; %bb.0:
; GFX13-NEXT:    v_mov_b32_e32 v0, 0
; GFX13-NEXT:    dds_load_b128 v[0:3], v0, s0
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    ; return to shader part epilog
    %load = load i128, ptr addrspace(11) %ptr
    %to.vgpr = bitcast i128 %load to <4 x float>
    ret <4 x float> %to.vgpr
}

define amdgpu_ps <4 x float> @dds_load_i128(ptr addrspace(11) %ptr) {
; GFX13-LABEL: dds_load_i128:
; GFX13:       ; %bb.0:
; GFX13-NEXT:    dds_load_b128 v[0:3], v0, off
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    ; return to shader part epilog
    %load = load i128, ptr addrspace(11) %ptr
    %to.vgpr = bitcast i128 %load to <4 x float>
    ret <4 x float> %to.vgpr
}

define amdgpu_ps float @dds_load_saddr_i32_offset_8388607(ptr addrspace(11) inreg %sbase) {
; GFX13-LABEL: dds_load_saddr_i32_offset_8388607:
; GFX13:       ; %bb.0:
; GFX13-NEXT:    v_mov_b32_e32 v0, 0
; GFX13-NEXT:    dds_load_b32 v0, v0, s0 offset:8388607
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    ; return to shader part epilog
  %gep0 = getelementptr inbounds i8, ptr addrspace(11) %sbase, i32 8388607
  %load = load i32, ptr addrspace(11) %gep0
  %to.vgpr = bitcast i32 %load to float
  ret float %to.vgpr
}

define amdgpu_ps float @dds_load_saddr_f32_natural_addressing(ptr addrspace(11) inreg %sbase, ptr addrspace(11) %voffset.ptr) {
; GFX13-LABEL: dds_load_saddr_f32_natural_addressing:
; GFX13:       ; %bb.0:
; GFX13-NEXT:    dds_load_b32 v0, v0, off
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    v_lshlrev_b32_e32 v0, 2, v0
; GFX13-NEXT:    dds_load_b32 v0, v0, s0
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    ; return to shader part epilog
  %voffset = load i32, ptr addrspace(11) %voffset.ptr
  %gep = getelementptr inbounds float, ptr addrspace(11) %sbase, i32 %voffset
  %load = load float, ptr addrspace(11) %gep
  ret float %load
}


;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; GFX13-GISEL: {{.*}}
; GFX13-SDAG: {{.*}}
