; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx900 -o - %s | FileCheck --check-prefixes=CHECK,GFX900 %s
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx90a -amdgpu-spill-vgpr-to-agpr=0 -o - %s | FileCheck --check-prefixes=CHECK,GFX90A-V2A-DIS %s
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx90a -amdgpu-spill-vgpr-to-agpr=1 -o - %s | FileCheck --check-prefixes=CHECK,GFX90A-V2A-EN %s
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1010 -o - %s | FileCheck --check-prefixes=CHECK,WAVE32 %s

define protected amdgpu_kernel void @kern1() #0 {
; CHECK-LABEL: kern1:
; CHECK:       .Lfunc_begin0:
; CHECK-NEXT:    .cfi_sections .debug_frame
; CHECK-NEXT:    .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    .cfi_escape 0x0f, 0x04, 0x30, 0x36, 0xe9, 0x02 ; CFA is 0 in private_wave aspace
; CHECK-NEXT:    .cfi_undefined 16
; CHECK-NEXT:    s_endpgm
entry:
  ret void
}

define hidden void @func_no_clobber() #0 {
; CHECK-LABEL: func_no_clobber:
; CHECK:       .Lfunc_begin1:
; CHECK-NEXT:    .cfi_startproc
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    .cfi_llvm_def_aspace_cfa 64, 0, 6
; CHECK-NEXT:    .cfi_llvm_register_pair 16, 62, 32, 63, 32
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    s_setpc_b64 s[30:31]
entry:
  ret void
}

define void @callee_need_to_spill_fp_to_memory() #1 {
; GFX900-LABEL: callee_need_to_spill_fp_to_memory:
; GFX900:       .Lfunc_begin2:
; GFX900-NEXT:    .cfi_startproc
; GFX900-NEXT:  ; %bb.0:
; GFX900-NEXT:    .cfi_llvm_def_aspace_cfa 64, 0, 6
; GFX900-NEXT:    .cfi_llvm_register_pair 16, 62, 32, 63, 32
; GFX900-NEXT:    .cfi_undefined 2560
; GFX900-NEXT:    .cfi_undefined 2561
; GFX900-NEXT:    .cfi_undefined 2562
; GFX900-NEXT:    .cfi_undefined 2563
; GFX900-NEXT:    .cfi_undefined 2564
; GFX900-NEXT:    .cfi_undefined 2565
; GFX900-NEXT:    .cfi_undefined 2566
; GFX900-NEXT:    .cfi_undefined 2567
; GFX900-NEXT:    .cfi_undefined 2568
; GFX900-NEXT:    .cfi_undefined 2569
; GFX900-NEXT:    .cfi_undefined 2570
; GFX900-NEXT:    .cfi_undefined 2571
; GFX900-NEXT:    .cfi_undefined 2572
; GFX900-NEXT:    .cfi_undefined 2573
; GFX900-NEXT:    .cfi_undefined 2574
; GFX900-NEXT:    .cfi_undefined 2575
; GFX900-NEXT:    .cfi_undefined 2576
; GFX900-NEXT:    .cfi_undefined 2577
; GFX900-NEXT:    .cfi_undefined 2578
; GFX900-NEXT:    .cfi_undefined 2579
; GFX900-NEXT:    .cfi_undefined 2580
; GFX900-NEXT:    .cfi_undefined 2581
; GFX900-NEXT:    .cfi_undefined 2582
; GFX900-NEXT:    .cfi_undefined 2583
; GFX900-NEXT:    .cfi_undefined 2584
; GFX900-NEXT:    .cfi_undefined 2585
; GFX900-NEXT:    .cfi_undefined 2586
; GFX900-NEXT:    .cfi_undefined 2587
; GFX900-NEXT:    .cfi_undefined 2588
; GFX900-NEXT:    .cfi_undefined 2589
; GFX900-NEXT:    .cfi_undefined 2590
; GFX900-NEXT:    .cfi_undefined 2591
; GFX900-NEXT:    .cfi_undefined 2592
; GFX900-NEXT:    .cfi_undefined 2593
; GFX900-NEXT:    .cfi_undefined 2594
; GFX900-NEXT:    .cfi_undefined 2595
; GFX900-NEXT:    .cfi_undefined 2596
; GFX900-NEXT:    .cfi_undefined 2597
; GFX900-NEXT:    .cfi_undefined 2598
; GFX900-NEXT:    .cfi_undefined 2599
; GFX900-NEXT:    .cfi_undefined 2608
; GFX900-NEXT:    .cfi_undefined 2609
; GFX900-NEXT:    .cfi_undefined 2610
; GFX900-NEXT:    .cfi_undefined 2611
; GFX900-NEXT:    .cfi_undefined 2612
; GFX900-NEXT:    .cfi_undefined 2613
; GFX900-NEXT:    .cfi_undefined 2614
; GFX900-NEXT:    .cfi_undefined 2615
; GFX900-NEXT:    .cfi_undefined 2624
; GFX900-NEXT:    .cfi_undefined 2625
; GFX900-NEXT:    .cfi_undefined 2626
; GFX900-NEXT:    .cfi_undefined 2627
; GFX900-NEXT:    .cfi_undefined 2628
; GFX900-NEXT:    .cfi_undefined 2629
; GFX900-NEXT:    .cfi_undefined 2630
; GFX900-NEXT:    .cfi_undefined 2631
; GFX900-NEXT:    .cfi_undefined 2640
; GFX900-NEXT:    .cfi_undefined 2641
; GFX900-NEXT:    .cfi_undefined 2642
; GFX900-NEXT:    .cfi_undefined 2643
; GFX900-NEXT:    .cfi_undefined 2644
; GFX900-NEXT:    .cfi_undefined 2645
; GFX900-NEXT:    .cfi_undefined 2646
; GFX900-NEXT:    .cfi_undefined 2647
; GFX900-NEXT:    .cfi_undefined 2656
; GFX900-NEXT:    .cfi_undefined 2657
; GFX900-NEXT:    .cfi_undefined 2658
; GFX900-NEXT:    .cfi_undefined 2659
; GFX900-NEXT:    .cfi_undefined 2660
; GFX900-NEXT:    .cfi_undefined 2661
; GFX900-NEXT:    .cfi_undefined 2662
; GFX900-NEXT:    .cfi_undefined 2663
; GFX900-NEXT:    .cfi_undefined 2672
; GFX900-NEXT:    .cfi_undefined 2673
; GFX900-NEXT:    .cfi_undefined 2674
; GFX900-NEXT:    .cfi_undefined 2675
; GFX900-NEXT:    .cfi_undefined 2676
; GFX900-NEXT:    .cfi_undefined 2677
; GFX900-NEXT:    .cfi_undefined 2678
; GFX900-NEXT:    .cfi_undefined 2679
; GFX900-NEXT:    .cfi_undefined 2688
; GFX900-NEXT:    .cfi_undefined 2689
; GFX900-NEXT:    .cfi_undefined 2690
; GFX900-NEXT:    .cfi_undefined 2691
; GFX900-NEXT:    .cfi_undefined 2692
; GFX900-NEXT:    .cfi_undefined 2693
; GFX900-NEXT:    .cfi_undefined 2694
; GFX900-NEXT:    .cfi_undefined 2695
; GFX900-NEXT:    .cfi_undefined 2704
; GFX900-NEXT:    .cfi_undefined 2705
; GFX900-NEXT:    .cfi_undefined 2706
; GFX900-NEXT:    .cfi_undefined 2707
; GFX900-NEXT:    .cfi_undefined 2708
; GFX900-NEXT:    .cfi_undefined 2709
; GFX900-NEXT:    .cfi_undefined 2710
; GFX900-NEXT:    .cfi_undefined 2711
; GFX900-NEXT:    .cfi_undefined 2720
; GFX900-NEXT:    .cfi_undefined 2721
; GFX900-NEXT:    .cfi_undefined 2722
; GFX900-NEXT:    .cfi_undefined 2723
; GFX900-NEXT:    .cfi_undefined 2724
; GFX900-NEXT:    .cfi_undefined 2725
; GFX900-NEXT:    .cfi_undefined 2726
; GFX900-NEXT:    .cfi_undefined 2727
; GFX900-NEXT:    .cfi_undefined 2736
; GFX900-NEXT:    .cfi_undefined 2737
; GFX900-NEXT:    .cfi_undefined 2738
; GFX900-NEXT:    .cfi_undefined 2739
; GFX900-NEXT:    .cfi_undefined 2740
; GFX900-NEXT:    .cfi_undefined 2741
; GFX900-NEXT:    .cfi_undefined 2742
; GFX900-NEXT:    .cfi_undefined 2743
; GFX900-NEXT:    .cfi_undefined 2752
; GFX900-NEXT:    .cfi_undefined 2753
; GFX900-NEXT:    .cfi_undefined 2754
; GFX900-NEXT:    .cfi_undefined 2755
; GFX900-NEXT:    .cfi_undefined 2756
; GFX900-NEXT:    .cfi_undefined 2757
; GFX900-NEXT:    .cfi_undefined 2758
; GFX900-NEXT:    .cfi_undefined 2759
; GFX900-NEXT:    .cfi_undefined 2768
; GFX900-NEXT:    .cfi_undefined 2769
; GFX900-NEXT:    .cfi_undefined 2770
; GFX900-NEXT:    .cfi_undefined 2771
; GFX900-NEXT:    .cfi_undefined 2772
; GFX900-NEXT:    .cfi_undefined 2773
; GFX900-NEXT:    .cfi_undefined 2774
; GFX900-NEXT:    .cfi_undefined 2775
; GFX900-NEXT:    .cfi_undefined 2784
; GFX900-NEXT:    .cfi_undefined 2785
; GFX900-NEXT:    .cfi_undefined 2786
; GFX900-NEXT:    .cfi_undefined 2787
; GFX900-NEXT:    .cfi_undefined 2788
; GFX900-NEXT:    .cfi_undefined 2789
; GFX900-NEXT:    .cfi_undefined 2790
; GFX900-NEXT:    .cfi_undefined 2791
; GFX900-NEXT:    .cfi_undefined 2800
; GFX900-NEXT:    .cfi_undefined 2801
; GFX900-NEXT:    .cfi_undefined 2802
; GFX900-NEXT:    .cfi_undefined 2803
; GFX900-NEXT:    .cfi_undefined 2804
; GFX900-NEXT:    .cfi_undefined 2805
; GFX900-NEXT:    .cfi_undefined 2806
; GFX900-NEXT:    .cfi_undefined 2807
; GFX900-NEXT:    .cfi_undefined 36
; GFX900-NEXT:    .cfi_undefined 37
; GFX900-NEXT:    .cfi_undefined 38
; GFX900-NEXT:    .cfi_undefined 39
; GFX900-NEXT:    .cfi_undefined 40
; GFX900-NEXT:    .cfi_undefined 41
; GFX900-NEXT:    .cfi_undefined 42
; GFX900-NEXT:    .cfi_undefined 43
; GFX900-NEXT:    .cfi_undefined 44
; GFX900-NEXT:    .cfi_undefined 45
; GFX900-NEXT:    .cfi_undefined 46
; GFX900-NEXT:    .cfi_undefined 47
; GFX900-NEXT:    .cfi_undefined 48
; GFX900-NEXT:    .cfi_undefined 49
; GFX900-NEXT:    .cfi_undefined 50
; GFX900-NEXT:    .cfi_undefined 51
; GFX900-NEXT:    .cfi_undefined 52
; GFX900-NEXT:    .cfi_undefined 53
; GFX900-NEXT:    .cfi_undefined 54
; GFX900-NEXT:    .cfi_undefined 55
; GFX900-NEXT:    .cfi_undefined 56
; GFX900-NEXT:    .cfi_undefined 57
; GFX900-NEXT:    .cfi_undefined 58
; GFX900-NEXT:    .cfi_undefined 59
; GFX900-NEXT:    .cfi_undefined 60
; GFX900-NEXT:    .cfi_undefined 61
; GFX900-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX900-NEXT:    s_mov_b32 s40, s33
; GFX900-NEXT:    .cfi_register 65, 72
; GFX900-NEXT:    s_mov_b32 s33, s32
; GFX900-NEXT:    .cfi_def_cfa_register 65
; GFX900-NEXT:    buffer_store_dword v40, off, s[0:3], s33 offset:444 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v41, off, s[0:3], s33 offset:440 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v42, off, s[0:3], s33 offset:436 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v43, off, s[0:3], s33 offset:432 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v44, off, s[0:3], s33 offset:428 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v45, off, s[0:3], s33 offset:424 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v46, off, s[0:3], s33 offset:420 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v47, off, s[0:3], s33 offset:416 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v56, off, s[0:3], s33 offset:412 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v57, off, s[0:3], s33 offset:408 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v58, off, s[0:3], s33 offset:404 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v59, off, s[0:3], s33 offset:400 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v60, off, s[0:3], s33 offset:396 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v61, off, s[0:3], s33 offset:392 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v62, off, s[0:3], s33 offset:388 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v63, off, s[0:3], s33 offset:384 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v72, off, s[0:3], s33 offset:380 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v73, off, s[0:3], s33 offset:376 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v74, off, s[0:3], s33 offset:372 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v75, off, s[0:3], s33 offset:368 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v76, off, s[0:3], s33 offset:364 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v77, off, s[0:3], s33 offset:360 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v78, off, s[0:3], s33 offset:356 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v79, off, s[0:3], s33 offset:352 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v88, off, s[0:3], s33 offset:348 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v89, off, s[0:3], s33 offset:344 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v90, off, s[0:3], s33 offset:340 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v91, off, s[0:3], s33 offset:336 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v92, off, s[0:3], s33 offset:332 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v93, off, s[0:3], s33 offset:328 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v94, off, s[0:3], s33 offset:324 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v95, off, s[0:3], s33 offset:320 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v104, off, s[0:3], s33 offset:316 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v105, off, s[0:3], s33 offset:312 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v106, off, s[0:3], s33 offset:308 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v107, off, s[0:3], s33 offset:304 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v108, off, s[0:3], s33 offset:300 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v109, off, s[0:3], s33 offset:296 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v110, off, s[0:3], s33 offset:292 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v111, off, s[0:3], s33 offset:288 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v120, off, s[0:3], s33 offset:284 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v121, off, s[0:3], s33 offset:280 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v122, off, s[0:3], s33 offset:276 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v123, off, s[0:3], s33 offset:272 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v124, off, s[0:3], s33 offset:268 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v125, off, s[0:3], s33 offset:264 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v126, off, s[0:3], s33 offset:260 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v127, off, s[0:3], s33 offset:256 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v136, off, s[0:3], s33 offset:252 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v137, off, s[0:3], s33 offset:248 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v138, off, s[0:3], s33 offset:244 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v139, off, s[0:3], s33 offset:240 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v140, off, s[0:3], s33 offset:236 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v141, off, s[0:3], s33 offset:232 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v142, off, s[0:3], s33 offset:228 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v143, off, s[0:3], s33 offset:224 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v152, off, s[0:3], s33 offset:220 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v153, off, s[0:3], s33 offset:216 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v154, off, s[0:3], s33 offset:212 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v155, off, s[0:3], s33 offset:208 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v156, off, s[0:3], s33 offset:204 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v157, off, s[0:3], s33 offset:200 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v158, off, s[0:3], s33 offset:196 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v159, off, s[0:3], s33 offset:192 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v168, off, s[0:3], s33 offset:188 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v169, off, s[0:3], s33 offset:184 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v170, off, s[0:3], s33 offset:180 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v171, off, s[0:3], s33 offset:176 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v172, off, s[0:3], s33 offset:172 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v173, off, s[0:3], s33 offset:168 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v174, off, s[0:3], s33 offset:164 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v175, off, s[0:3], s33 offset:160 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v184, off, s[0:3], s33 offset:156 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v185, off, s[0:3], s33 offset:152 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v186, off, s[0:3], s33 offset:148 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v187, off, s[0:3], s33 offset:144 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v188, off, s[0:3], s33 offset:140 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v189, off, s[0:3], s33 offset:136 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v190, off, s[0:3], s33 offset:132 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v191, off, s[0:3], s33 offset:128 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v200, off, s[0:3], s33 offset:124 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v201, off, s[0:3], s33 offset:120 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v202, off, s[0:3], s33 offset:116 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v203, off, s[0:3], s33 offset:112 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v204, off, s[0:3], s33 offset:108 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v205, off, s[0:3], s33 offset:104 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v206, off, s[0:3], s33 offset:100 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v207, off, s[0:3], s33 offset:96 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v216, off, s[0:3], s33 offset:92 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v217, off, s[0:3], s33 offset:88 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v218, off, s[0:3], s33 offset:84 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v219, off, s[0:3], s33 offset:80 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v220, off, s[0:3], s33 offset:76 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v221, off, s[0:3], s33 offset:72 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v222, off, s[0:3], s33 offset:68 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v223, off, s[0:3], s33 offset:64 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v232, off, s[0:3], s33 offset:60 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v233, off, s[0:3], s33 offset:56 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v234, off, s[0:3], s33 offset:52 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v235, off, s[0:3], s33 offset:48 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v236, off, s[0:3], s33 offset:44 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v237, off, s[0:3], s33 offset:40 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v238, off, s[0:3], s33 offset:36 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v239, off, s[0:3], s33 offset:32 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v248, off, s[0:3], s33 offset:28 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v249, off, s[0:3], s33 offset:24 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v250, off, s[0:3], s33 offset:20 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v251, off, s[0:3], s33 offset:16 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v252, off, s[0:3], s33 offset:12 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v253, off, s[0:3], s33 offset:8 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v254, off, s[0:3], s33 offset:4 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v255, off, s[0:3], s33 ; 4-byte Folded Spill
; GFX900-NEXT:    ;;#ASMSTART
; GFX900-NEXT:    ; clobber nonpreserved SGPRs
; GFX900-NEXT:    ;;#ASMEND
; GFX900-NEXT:    ;;#ASMSTART
; GFX900-NEXT:    ; clobber all VGPRs
; GFX900-NEXT:    ;;#ASMEND
; GFX900-NEXT:    buffer_load_dword v255, off, s[0:3], s33 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v254, off, s[0:3], s33 offset:4 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v253, off, s[0:3], s33 offset:8 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v252, off, s[0:3], s33 offset:12 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v251, off, s[0:3], s33 offset:16 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v250, off, s[0:3], s33 offset:20 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v249, off, s[0:3], s33 offset:24 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v248, off, s[0:3], s33 offset:28 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v239, off, s[0:3], s33 offset:32 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v238, off, s[0:3], s33 offset:36 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v237, off, s[0:3], s33 offset:40 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v236, off, s[0:3], s33 offset:44 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v235, off, s[0:3], s33 offset:48 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v234, off, s[0:3], s33 offset:52 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v233, off, s[0:3], s33 offset:56 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v232, off, s[0:3], s33 offset:60 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v223, off, s[0:3], s33 offset:64 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v222, off, s[0:3], s33 offset:68 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v221, off, s[0:3], s33 offset:72 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v220, off, s[0:3], s33 offset:76 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v219, off, s[0:3], s33 offset:80 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v218, off, s[0:3], s33 offset:84 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v217, off, s[0:3], s33 offset:88 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v216, off, s[0:3], s33 offset:92 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v207, off, s[0:3], s33 offset:96 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v206, off, s[0:3], s33 offset:100 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v205, off, s[0:3], s33 offset:104 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v204, off, s[0:3], s33 offset:108 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v203, off, s[0:3], s33 offset:112 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v202, off, s[0:3], s33 offset:116 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v201, off, s[0:3], s33 offset:120 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v200, off, s[0:3], s33 offset:124 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v191, off, s[0:3], s33 offset:128 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v190, off, s[0:3], s33 offset:132 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v189, off, s[0:3], s33 offset:136 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v188, off, s[0:3], s33 offset:140 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v187, off, s[0:3], s33 offset:144 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v186, off, s[0:3], s33 offset:148 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v185, off, s[0:3], s33 offset:152 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v184, off, s[0:3], s33 offset:156 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v175, off, s[0:3], s33 offset:160 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v174, off, s[0:3], s33 offset:164 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v173, off, s[0:3], s33 offset:168 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v172, off, s[0:3], s33 offset:172 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v171, off, s[0:3], s33 offset:176 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v170, off, s[0:3], s33 offset:180 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v169, off, s[0:3], s33 offset:184 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v168, off, s[0:3], s33 offset:188 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v159, off, s[0:3], s33 offset:192 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v158, off, s[0:3], s33 offset:196 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v157, off, s[0:3], s33 offset:200 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v156, off, s[0:3], s33 offset:204 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v155, off, s[0:3], s33 offset:208 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v154, off, s[0:3], s33 offset:212 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v153, off, s[0:3], s33 offset:216 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v152, off, s[0:3], s33 offset:220 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v143, off, s[0:3], s33 offset:224 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v142, off, s[0:3], s33 offset:228 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v141, off, s[0:3], s33 offset:232 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v140, off, s[0:3], s33 offset:236 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v139, off, s[0:3], s33 offset:240 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v138, off, s[0:3], s33 offset:244 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v137, off, s[0:3], s33 offset:248 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v136, off, s[0:3], s33 offset:252 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v127, off, s[0:3], s33 offset:256 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v126, off, s[0:3], s33 offset:260 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v125, off, s[0:3], s33 offset:264 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v124, off, s[0:3], s33 offset:268 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v123, off, s[0:3], s33 offset:272 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v122, off, s[0:3], s33 offset:276 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v121, off, s[0:3], s33 offset:280 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v120, off, s[0:3], s33 offset:284 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v111, off, s[0:3], s33 offset:288 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v110, off, s[0:3], s33 offset:292 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v109, off, s[0:3], s33 offset:296 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v108, off, s[0:3], s33 offset:300 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v107, off, s[0:3], s33 offset:304 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v106, off, s[0:3], s33 offset:308 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v105, off, s[0:3], s33 offset:312 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v104, off, s[0:3], s33 offset:316 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v95, off, s[0:3], s33 offset:320 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v94, off, s[0:3], s33 offset:324 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v93, off, s[0:3], s33 offset:328 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v92, off, s[0:3], s33 offset:332 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v91, off, s[0:3], s33 offset:336 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v90, off, s[0:3], s33 offset:340 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v89, off, s[0:3], s33 offset:344 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v88, off, s[0:3], s33 offset:348 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v79, off, s[0:3], s33 offset:352 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v78, off, s[0:3], s33 offset:356 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v77, off, s[0:3], s33 offset:360 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v76, off, s[0:3], s33 offset:364 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v75, off, s[0:3], s33 offset:368 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v74, off, s[0:3], s33 offset:372 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v73, off, s[0:3], s33 offset:376 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v72, off, s[0:3], s33 offset:380 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v63, off, s[0:3], s33 offset:384 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v62, off, s[0:3], s33 offset:388 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v61, off, s[0:3], s33 offset:392 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v60, off, s[0:3], s33 offset:396 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v59, off, s[0:3], s33 offset:400 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v58, off, s[0:3], s33 offset:404 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v57, off, s[0:3], s33 offset:408 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v56, off, s[0:3], s33 offset:412 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v47, off, s[0:3], s33 offset:416 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v46, off, s[0:3], s33 offset:420 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v45, off, s[0:3], s33 offset:424 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v44, off, s[0:3], s33 offset:428 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v43, off, s[0:3], s33 offset:432 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v42, off, s[0:3], s33 offset:436 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v41, off, s[0:3], s33 offset:440 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v40, off, s[0:3], s33 offset:444 ; 4-byte Folded Reload
; GFX900-NEXT:    s_addk_i32 s32, 0x7100
; GFX900-NEXT:    s_mov_b32 s32, s33
; GFX900-NEXT:    .cfi_def_cfa_register 64
; GFX900-NEXT:    s_mov_b32 s33, s40
; GFX900-NEXT:    s_waitcnt vmcnt(0)
; GFX900-NEXT:    s_setpc_b64 s[30:31]
;
; GFX90A-V2A-DIS-LABEL: callee_need_to_spill_fp_to_memory:
; GFX90A-V2A-DIS:       .Lfunc_begin2:
; GFX90A-V2A-DIS-NEXT:    .cfi_startproc
; GFX90A-V2A-DIS-NEXT:  ; %bb.0:
; GFX90A-V2A-DIS-NEXT:    .cfi_llvm_def_aspace_cfa 64, 0, 6
; GFX90A-V2A-DIS-NEXT:    .cfi_llvm_register_pair 16, 62, 32, 63, 32
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2560
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2561
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2562
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2563
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2564
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2565
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2566
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2567
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2568
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2569
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2570
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2571
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2572
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2573
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2574
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2575
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2576
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2577
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2578
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2579
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2580
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2581
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2582
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2583
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2584
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2585
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2586
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2587
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2588
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2589
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2590
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2591
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2592
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2593
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2594
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2595
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2596
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2597
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2598
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2599
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2608
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2609
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2610
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2611
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2612
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2613
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2614
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2615
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2624
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2625
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2626
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2627
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2628
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2629
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2630
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2631
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2640
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2641
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2642
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2643
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2644
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2645
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2646
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2647
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2656
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2657
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2658
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2659
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2660
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2661
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2662
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2663
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2672
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2673
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2674
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2675
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2676
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2677
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2678
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2679
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2688
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2689
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2690
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2691
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2692
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2693
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2694
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2695
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2704
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2705
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2706
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2707
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2708
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2709
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2710
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2711
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2720
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2721
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2722
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2723
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2724
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2725
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2726
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2727
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2736
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2737
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2738
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2739
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2740
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2741
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2742
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2743
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2752
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2753
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2754
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2755
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2756
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2757
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2758
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2759
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2768
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2769
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2770
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2771
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2772
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2773
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2774
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2775
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2784
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2785
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2786
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2787
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2788
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2789
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2790
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2791
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2800
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2801
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2802
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2803
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2804
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2805
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2806
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2807
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 36
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 37
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 38
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 39
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 40
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 41
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 42
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 43
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 44
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 45
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 46
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 47
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 48
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 49
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 50
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 51
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 52
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 53
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 54
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 55
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 56
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 57
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 58
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 59
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 60
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 61
; GFX90A-V2A-DIS-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX90A-V2A-DIS-NEXT:    s_mov_b32 s40, s33
; GFX90A-V2A-DIS-NEXT:    .cfi_register 65, 72
; GFX90A-V2A-DIS-NEXT:    s_mov_b32 s33, s32
; GFX90A-V2A-DIS-NEXT:    .cfi_def_cfa_register 65
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v40, off, s[0:3], s33 offset:444 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v41, off, s[0:3], s33 offset:440 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v42, off, s[0:3], s33 offset:436 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v43, off, s[0:3], s33 offset:432 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v44, off, s[0:3], s33 offset:428 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v45, off, s[0:3], s33 offset:424 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v46, off, s[0:3], s33 offset:420 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v47, off, s[0:3], s33 offset:416 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v56, off, s[0:3], s33 offset:412 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v57, off, s[0:3], s33 offset:408 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v58, off, s[0:3], s33 offset:404 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v59, off, s[0:3], s33 offset:400 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v60, off, s[0:3], s33 offset:396 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v61, off, s[0:3], s33 offset:392 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v62, off, s[0:3], s33 offset:388 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v63, off, s[0:3], s33 offset:384 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v72, off, s[0:3], s33 offset:380 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v73, off, s[0:3], s33 offset:376 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v74, off, s[0:3], s33 offset:372 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v75, off, s[0:3], s33 offset:368 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v76, off, s[0:3], s33 offset:364 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v77, off, s[0:3], s33 offset:360 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v78, off, s[0:3], s33 offset:356 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v79, off, s[0:3], s33 offset:352 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v88, off, s[0:3], s33 offset:348 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v89, off, s[0:3], s33 offset:344 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v90, off, s[0:3], s33 offset:340 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v91, off, s[0:3], s33 offset:336 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v92, off, s[0:3], s33 offset:332 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v93, off, s[0:3], s33 offset:328 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v94, off, s[0:3], s33 offset:324 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v95, off, s[0:3], s33 offset:320 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v104, off, s[0:3], s33 offset:316 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v105, off, s[0:3], s33 offset:312 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v106, off, s[0:3], s33 offset:308 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v107, off, s[0:3], s33 offset:304 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v108, off, s[0:3], s33 offset:300 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v109, off, s[0:3], s33 offset:296 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v110, off, s[0:3], s33 offset:292 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v111, off, s[0:3], s33 offset:288 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v120, off, s[0:3], s33 offset:284 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v121, off, s[0:3], s33 offset:280 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v122, off, s[0:3], s33 offset:276 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v123, off, s[0:3], s33 offset:272 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v124, off, s[0:3], s33 offset:268 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v125, off, s[0:3], s33 offset:264 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v126, off, s[0:3], s33 offset:260 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v127, off, s[0:3], s33 offset:256 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v136, off, s[0:3], s33 offset:252 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v137, off, s[0:3], s33 offset:248 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v138, off, s[0:3], s33 offset:244 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v139, off, s[0:3], s33 offset:240 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v140, off, s[0:3], s33 offset:236 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v141, off, s[0:3], s33 offset:232 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v142, off, s[0:3], s33 offset:228 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v143, off, s[0:3], s33 offset:224 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v152, off, s[0:3], s33 offset:220 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v153, off, s[0:3], s33 offset:216 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v154, off, s[0:3], s33 offset:212 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v155, off, s[0:3], s33 offset:208 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v156, off, s[0:3], s33 offset:204 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v157, off, s[0:3], s33 offset:200 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v158, off, s[0:3], s33 offset:196 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v159, off, s[0:3], s33 offset:192 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v168, off, s[0:3], s33 offset:188 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v169, off, s[0:3], s33 offset:184 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v170, off, s[0:3], s33 offset:180 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v171, off, s[0:3], s33 offset:176 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v172, off, s[0:3], s33 offset:172 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v173, off, s[0:3], s33 offset:168 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v174, off, s[0:3], s33 offset:164 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v175, off, s[0:3], s33 offset:160 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v184, off, s[0:3], s33 offset:156 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v185, off, s[0:3], s33 offset:152 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v186, off, s[0:3], s33 offset:148 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v187, off, s[0:3], s33 offset:144 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v188, off, s[0:3], s33 offset:140 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v189, off, s[0:3], s33 offset:136 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v190, off, s[0:3], s33 offset:132 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v191, off, s[0:3], s33 offset:128 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v200, off, s[0:3], s33 offset:124 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v201, off, s[0:3], s33 offset:120 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v202, off, s[0:3], s33 offset:116 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v203, off, s[0:3], s33 offset:112 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v204, off, s[0:3], s33 offset:108 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v205, off, s[0:3], s33 offset:104 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v206, off, s[0:3], s33 offset:100 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v207, off, s[0:3], s33 offset:96 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v216, off, s[0:3], s33 offset:92 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v217, off, s[0:3], s33 offset:88 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v218, off, s[0:3], s33 offset:84 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v219, off, s[0:3], s33 offset:80 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v220, off, s[0:3], s33 offset:76 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v221, off, s[0:3], s33 offset:72 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v222, off, s[0:3], s33 offset:68 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v223, off, s[0:3], s33 offset:64 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v232, off, s[0:3], s33 offset:60 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v233, off, s[0:3], s33 offset:56 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v234, off, s[0:3], s33 offset:52 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v235, off, s[0:3], s33 offset:48 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v236, off, s[0:3], s33 offset:44 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v237, off, s[0:3], s33 offset:40 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v238, off, s[0:3], s33 offset:36 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v239, off, s[0:3], s33 offset:32 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v248, off, s[0:3], s33 offset:28 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v249, off, s[0:3], s33 offset:24 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v250, off, s[0:3], s33 offset:20 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v251, off, s[0:3], s33 offset:16 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v252, off, s[0:3], s33 offset:12 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v253, off, s[0:3], s33 offset:8 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v254, off, s[0:3], s33 offset:4 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v255, off, s[0:3], s33 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    ;;#ASMSTART
; GFX90A-V2A-DIS-NEXT:    ; clobber nonpreserved SGPRs
; GFX90A-V2A-DIS-NEXT:    ;;#ASMEND
; GFX90A-V2A-DIS-NEXT:    ;;#ASMSTART
; GFX90A-V2A-DIS-NEXT:    ; clobber all VGPRs
; GFX90A-V2A-DIS-NEXT:    ;;#ASMEND
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v255, off, s[0:3], s33 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v254, off, s[0:3], s33 offset:4 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v253, off, s[0:3], s33 offset:8 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v252, off, s[0:3], s33 offset:12 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v251, off, s[0:3], s33 offset:16 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v250, off, s[0:3], s33 offset:20 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v249, off, s[0:3], s33 offset:24 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v248, off, s[0:3], s33 offset:28 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v239, off, s[0:3], s33 offset:32 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v238, off, s[0:3], s33 offset:36 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v237, off, s[0:3], s33 offset:40 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v236, off, s[0:3], s33 offset:44 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v235, off, s[0:3], s33 offset:48 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v234, off, s[0:3], s33 offset:52 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v233, off, s[0:3], s33 offset:56 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v232, off, s[0:3], s33 offset:60 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v223, off, s[0:3], s33 offset:64 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v222, off, s[0:3], s33 offset:68 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v221, off, s[0:3], s33 offset:72 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v220, off, s[0:3], s33 offset:76 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v219, off, s[0:3], s33 offset:80 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v218, off, s[0:3], s33 offset:84 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v217, off, s[0:3], s33 offset:88 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v216, off, s[0:3], s33 offset:92 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v207, off, s[0:3], s33 offset:96 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v206, off, s[0:3], s33 offset:100 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v205, off, s[0:3], s33 offset:104 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v204, off, s[0:3], s33 offset:108 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v203, off, s[0:3], s33 offset:112 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v202, off, s[0:3], s33 offset:116 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v201, off, s[0:3], s33 offset:120 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v200, off, s[0:3], s33 offset:124 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v191, off, s[0:3], s33 offset:128 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v190, off, s[0:3], s33 offset:132 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v189, off, s[0:3], s33 offset:136 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v188, off, s[0:3], s33 offset:140 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v187, off, s[0:3], s33 offset:144 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v186, off, s[0:3], s33 offset:148 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v185, off, s[0:3], s33 offset:152 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v184, off, s[0:3], s33 offset:156 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v175, off, s[0:3], s33 offset:160 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v174, off, s[0:3], s33 offset:164 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v173, off, s[0:3], s33 offset:168 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v172, off, s[0:3], s33 offset:172 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v171, off, s[0:3], s33 offset:176 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v170, off, s[0:3], s33 offset:180 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v169, off, s[0:3], s33 offset:184 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v168, off, s[0:3], s33 offset:188 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v159, off, s[0:3], s33 offset:192 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v158, off, s[0:3], s33 offset:196 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v157, off, s[0:3], s33 offset:200 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v156, off, s[0:3], s33 offset:204 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v155, off, s[0:3], s33 offset:208 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v154, off, s[0:3], s33 offset:212 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v153, off, s[0:3], s33 offset:216 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v152, off, s[0:3], s33 offset:220 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v143, off, s[0:3], s33 offset:224 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v142, off, s[0:3], s33 offset:228 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v141, off, s[0:3], s33 offset:232 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v140, off, s[0:3], s33 offset:236 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v139, off, s[0:3], s33 offset:240 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v138, off, s[0:3], s33 offset:244 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v137, off, s[0:3], s33 offset:248 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v136, off, s[0:3], s33 offset:252 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v127, off, s[0:3], s33 offset:256 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v126, off, s[0:3], s33 offset:260 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v125, off, s[0:3], s33 offset:264 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v124, off, s[0:3], s33 offset:268 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v123, off, s[0:3], s33 offset:272 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v122, off, s[0:3], s33 offset:276 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v121, off, s[0:3], s33 offset:280 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v120, off, s[0:3], s33 offset:284 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v111, off, s[0:3], s33 offset:288 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v110, off, s[0:3], s33 offset:292 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v109, off, s[0:3], s33 offset:296 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v108, off, s[0:3], s33 offset:300 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v107, off, s[0:3], s33 offset:304 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v106, off, s[0:3], s33 offset:308 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v105, off, s[0:3], s33 offset:312 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v104, off, s[0:3], s33 offset:316 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v95, off, s[0:3], s33 offset:320 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v94, off, s[0:3], s33 offset:324 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v93, off, s[0:3], s33 offset:328 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v92, off, s[0:3], s33 offset:332 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v91, off, s[0:3], s33 offset:336 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v90, off, s[0:3], s33 offset:340 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v89, off, s[0:3], s33 offset:344 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v88, off, s[0:3], s33 offset:348 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v79, off, s[0:3], s33 offset:352 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v78, off, s[0:3], s33 offset:356 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v77, off, s[0:3], s33 offset:360 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v76, off, s[0:3], s33 offset:364 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v75, off, s[0:3], s33 offset:368 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v74, off, s[0:3], s33 offset:372 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v73, off, s[0:3], s33 offset:376 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v72, off, s[0:3], s33 offset:380 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v63, off, s[0:3], s33 offset:384 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v62, off, s[0:3], s33 offset:388 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v61, off, s[0:3], s33 offset:392 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v60, off, s[0:3], s33 offset:396 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v59, off, s[0:3], s33 offset:400 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v58, off, s[0:3], s33 offset:404 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v57, off, s[0:3], s33 offset:408 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v56, off, s[0:3], s33 offset:412 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v47, off, s[0:3], s33 offset:416 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v46, off, s[0:3], s33 offset:420 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v45, off, s[0:3], s33 offset:424 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v44, off, s[0:3], s33 offset:428 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v43, off, s[0:3], s33 offset:432 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v42, off, s[0:3], s33 offset:436 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v41, off, s[0:3], s33 offset:440 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v40, off, s[0:3], s33 offset:444 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    s_addk_i32 s32, 0x7100
; GFX90A-V2A-DIS-NEXT:    s_mov_b32 s32, s33
; GFX90A-V2A-DIS-NEXT:    .cfi_def_cfa_register 64
; GFX90A-V2A-DIS-NEXT:    s_mov_b32 s33, s40
; GFX90A-V2A-DIS-NEXT:    s_waitcnt vmcnt(0)
; GFX90A-V2A-DIS-NEXT:    s_setpc_b64 s[30:31]
;
; GFX90A-V2A-EN-LABEL: callee_need_to_spill_fp_to_memory:
; GFX90A-V2A-EN:       .Lfunc_begin2:
; GFX90A-V2A-EN-NEXT:    .cfi_startproc
; GFX90A-V2A-EN-NEXT:  ; %bb.0:
; GFX90A-V2A-EN-NEXT:    .cfi_llvm_def_aspace_cfa 64, 0, 6
; GFX90A-V2A-EN-NEXT:    .cfi_llvm_register_pair 16, 62, 32, 63, 32
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2560
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2561
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2562
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2563
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2564
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2565
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2566
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2567
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2568
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2569
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2570
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2571
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2572
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2573
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2574
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2575
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2576
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2577
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2578
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2579
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2580
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2581
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2582
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2583
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2584
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2585
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2586
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2587
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2588
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2589
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2590
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2591
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2592
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2593
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2594
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2595
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2596
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2597
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2598
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2599
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2608
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2609
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2610
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2611
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2612
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2613
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2614
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2615
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2624
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2625
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2626
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2627
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2628
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2629
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2630
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2631
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2640
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2641
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2642
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2643
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2644
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2645
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2646
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2647
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2656
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2657
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2658
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2659
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2660
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2661
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2662
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2663
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2672
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2673
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2674
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2675
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2676
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2677
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2678
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2679
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2688
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2689
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2690
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2691
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2692
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2693
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2694
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2695
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2704
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2705
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2706
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2707
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2708
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2709
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2710
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2711
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2720
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2721
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2722
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2723
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2724
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2725
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2726
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2727
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2736
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2737
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2738
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2739
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2740
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2741
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2742
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2743
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2752
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2753
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2754
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2755
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2756
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2757
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2758
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2759
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2768
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2769
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2770
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2771
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2772
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2773
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2774
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2775
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2784
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2785
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2786
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2787
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2788
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2789
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2790
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2791
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2800
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2801
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2802
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2803
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2804
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2805
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2806
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2807
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3072
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3073
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3074
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3075
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3076
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3077
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3078
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3079
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3080
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3081
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3082
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3083
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3084
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3085
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3086
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3087
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3088
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3089
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3090
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3091
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3092
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3093
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3094
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3095
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3096
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3097
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3098
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3099
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3100
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3101
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3102
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3103
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 36
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 37
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 38
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 39
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 40
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 41
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 42
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 43
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 44
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 45
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 46
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 47
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 48
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 49
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 50
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 51
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 52
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 53
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 54
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 55
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 56
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 57
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 58
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 59
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 60
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 61
; GFX90A-V2A-EN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX90A-V2A-EN-NEXT:    s_mov_b32 s40, s33
; GFX90A-V2A-EN-NEXT:    .cfi_register 65, 72
; GFX90A-V2A-EN-NEXT:    s_mov_b32 s33, s32
; GFX90A-V2A-EN-NEXT:    .cfi_def_cfa_register 65
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a0, v40 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a1, v41 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a2, v42 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a3, v43 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a4, v44 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a5, v45 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a6, v46 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a7, v47 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a8, v56 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a9, v57 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a10, v58 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a11, v59 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a12, v60 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a13, v61 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a14, v62 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a15, v63 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a16, v72 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a17, v73 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a18, v74 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a19, v75 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a20, v76 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a21, v77 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a22, v78 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a23, v79 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a24, v88 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a25, v89 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a26, v90 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a27, v91 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a28, v92 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a29, v93 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a30, v94 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a31, v95 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v104, off, s[0:3], s33 offset:316 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v105, off, s[0:3], s33 offset:312 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v106, off, s[0:3], s33 offset:308 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v107, off, s[0:3], s33 offset:304 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v108, off, s[0:3], s33 offset:300 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v109, off, s[0:3], s33 offset:296 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v110, off, s[0:3], s33 offset:292 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v111, off, s[0:3], s33 offset:288 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v120, off, s[0:3], s33 offset:284 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v121, off, s[0:3], s33 offset:280 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v122, off, s[0:3], s33 offset:276 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v123, off, s[0:3], s33 offset:272 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v124, off, s[0:3], s33 offset:268 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v125, off, s[0:3], s33 offset:264 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v126, off, s[0:3], s33 offset:260 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v127, off, s[0:3], s33 offset:256 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v136, off, s[0:3], s33 offset:252 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v137, off, s[0:3], s33 offset:248 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v138, off, s[0:3], s33 offset:244 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v139, off, s[0:3], s33 offset:240 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v140, off, s[0:3], s33 offset:236 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v141, off, s[0:3], s33 offset:232 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v142, off, s[0:3], s33 offset:228 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v143, off, s[0:3], s33 offset:224 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v152, off, s[0:3], s33 offset:220 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v153, off, s[0:3], s33 offset:216 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v154, off, s[0:3], s33 offset:212 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v155, off, s[0:3], s33 offset:208 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v156, off, s[0:3], s33 offset:204 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v157, off, s[0:3], s33 offset:200 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v158, off, s[0:3], s33 offset:196 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v159, off, s[0:3], s33 offset:192 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v168, off, s[0:3], s33 offset:188 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v169, off, s[0:3], s33 offset:184 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v170, off, s[0:3], s33 offset:180 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v171, off, s[0:3], s33 offset:176 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v172, off, s[0:3], s33 offset:172 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v173, off, s[0:3], s33 offset:168 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v174, off, s[0:3], s33 offset:164 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v175, off, s[0:3], s33 offset:160 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v184, off, s[0:3], s33 offset:156 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v185, off, s[0:3], s33 offset:152 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v186, off, s[0:3], s33 offset:148 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v187, off, s[0:3], s33 offset:144 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v188, off, s[0:3], s33 offset:140 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v189, off, s[0:3], s33 offset:136 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v190, off, s[0:3], s33 offset:132 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v191, off, s[0:3], s33 offset:128 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v200, off, s[0:3], s33 offset:124 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v201, off, s[0:3], s33 offset:120 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v202, off, s[0:3], s33 offset:116 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v203, off, s[0:3], s33 offset:112 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v204, off, s[0:3], s33 offset:108 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v205, off, s[0:3], s33 offset:104 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v206, off, s[0:3], s33 offset:100 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v207, off, s[0:3], s33 offset:96 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v216, off, s[0:3], s33 offset:92 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v217, off, s[0:3], s33 offset:88 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v218, off, s[0:3], s33 offset:84 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v219, off, s[0:3], s33 offset:80 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v220, off, s[0:3], s33 offset:76 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v221, off, s[0:3], s33 offset:72 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v222, off, s[0:3], s33 offset:68 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v223, off, s[0:3], s33 offset:64 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v232, off, s[0:3], s33 offset:60 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v233, off, s[0:3], s33 offset:56 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v234, off, s[0:3], s33 offset:52 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v235, off, s[0:3], s33 offset:48 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v236, off, s[0:3], s33 offset:44 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v237, off, s[0:3], s33 offset:40 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v238, off, s[0:3], s33 offset:36 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v239, off, s[0:3], s33 offset:32 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v248, off, s[0:3], s33 offset:28 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v249, off, s[0:3], s33 offset:24 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v250, off, s[0:3], s33 offset:20 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v251, off, s[0:3], s33 offset:16 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v252, off, s[0:3], s33 offset:12 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v253, off, s[0:3], s33 offset:8 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v254, off, s[0:3], s33 offset:4 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v255, off, s[0:3], s33 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    ;;#ASMSTART
; GFX90A-V2A-EN-NEXT:    ; clobber nonpreserved SGPRs
; GFX90A-V2A-EN-NEXT:    ;;#ASMEND
; GFX90A-V2A-EN-NEXT:    ;;#ASMSTART
; GFX90A-V2A-EN-NEXT:    ; clobber all VGPRs
; GFX90A-V2A-EN-NEXT:    ;;#ASMEND
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v255, off, s[0:3], s33 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v254, off, s[0:3], s33 offset:4 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v253, off, s[0:3], s33 offset:8 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v252, off, s[0:3], s33 offset:12 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v251, off, s[0:3], s33 offset:16 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v250, off, s[0:3], s33 offset:20 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v249, off, s[0:3], s33 offset:24 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v248, off, s[0:3], s33 offset:28 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v239, off, s[0:3], s33 offset:32 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v238, off, s[0:3], s33 offset:36 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v237, off, s[0:3], s33 offset:40 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v236, off, s[0:3], s33 offset:44 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v235, off, s[0:3], s33 offset:48 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v234, off, s[0:3], s33 offset:52 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v233, off, s[0:3], s33 offset:56 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v232, off, s[0:3], s33 offset:60 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v223, off, s[0:3], s33 offset:64 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v222, off, s[0:3], s33 offset:68 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v221, off, s[0:3], s33 offset:72 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v220, off, s[0:3], s33 offset:76 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v219, off, s[0:3], s33 offset:80 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v218, off, s[0:3], s33 offset:84 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v217, off, s[0:3], s33 offset:88 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v216, off, s[0:3], s33 offset:92 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v207, off, s[0:3], s33 offset:96 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v206, off, s[0:3], s33 offset:100 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v205, off, s[0:3], s33 offset:104 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v204, off, s[0:3], s33 offset:108 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v203, off, s[0:3], s33 offset:112 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v202, off, s[0:3], s33 offset:116 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v201, off, s[0:3], s33 offset:120 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v200, off, s[0:3], s33 offset:124 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v191, off, s[0:3], s33 offset:128 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v190, off, s[0:3], s33 offset:132 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v189, off, s[0:3], s33 offset:136 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v188, off, s[0:3], s33 offset:140 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v187, off, s[0:3], s33 offset:144 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v186, off, s[0:3], s33 offset:148 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v185, off, s[0:3], s33 offset:152 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v184, off, s[0:3], s33 offset:156 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v175, off, s[0:3], s33 offset:160 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v174, off, s[0:3], s33 offset:164 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v173, off, s[0:3], s33 offset:168 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v172, off, s[0:3], s33 offset:172 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v171, off, s[0:3], s33 offset:176 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v170, off, s[0:3], s33 offset:180 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v169, off, s[0:3], s33 offset:184 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v168, off, s[0:3], s33 offset:188 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v159, off, s[0:3], s33 offset:192 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v158, off, s[0:3], s33 offset:196 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v157, off, s[0:3], s33 offset:200 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v156, off, s[0:3], s33 offset:204 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v155, off, s[0:3], s33 offset:208 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v154, off, s[0:3], s33 offset:212 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v153, off, s[0:3], s33 offset:216 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v152, off, s[0:3], s33 offset:220 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v143, off, s[0:3], s33 offset:224 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v142, off, s[0:3], s33 offset:228 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v141, off, s[0:3], s33 offset:232 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v140, off, s[0:3], s33 offset:236 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v139, off, s[0:3], s33 offset:240 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v138, off, s[0:3], s33 offset:244 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v137, off, s[0:3], s33 offset:248 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v136, off, s[0:3], s33 offset:252 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v127, off, s[0:3], s33 offset:256 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v126, off, s[0:3], s33 offset:260 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v125, off, s[0:3], s33 offset:264 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v124, off, s[0:3], s33 offset:268 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v123, off, s[0:3], s33 offset:272 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v122, off, s[0:3], s33 offset:276 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v121, off, s[0:3], s33 offset:280 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v120, off, s[0:3], s33 offset:284 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v111, off, s[0:3], s33 offset:288 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v110, off, s[0:3], s33 offset:292 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v109, off, s[0:3], s33 offset:296 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v108, off, s[0:3], s33 offset:300 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v107, off, s[0:3], s33 offset:304 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v106, off, s[0:3], s33 offset:308 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v105, off, s[0:3], s33 offset:312 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v104, off, s[0:3], s33 offset:316 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    s_addk_i32 s32, 0x5100
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v95, a31 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v94, a30 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v93, a29 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v92, a28 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v91, a27 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v90, a26 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v89, a25 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v88, a24 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v79, a23 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v78, a22 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v77, a21 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v76, a20 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v75, a19 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v74, a18 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v73, a17 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v72, a16 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v63, a15 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v62, a14 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v61, a13 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v60, a12 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v59, a11 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v58, a10 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v57, a9 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v56, a8 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v47, a7 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v46, a6 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v45, a5 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v44, a4 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v43, a3 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v42, a2 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v41, a1 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v40, a0 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    s_mov_b32 s32, s33
; GFX90A-V2A-EN-NEXT:    .cfi_def_cfa_register 64
; GFX90A-V2A-EN-NEXT:    s_mov_b32 s33, s40
; GFX90A-V2A-EN-NEXT:    s_waitcnt vmcnt(0)
; GFX90A-V2A-EN-NEXT:    s_setpc_b64 s[30:31]
;
; WAVE32-LABEL: callee_need_to_spill_fp_to_memory:
; WAVE32:       .Lfunc_begin2:
; WAVE32-NEXT:    .cfi_startproc
; WAVE32-NEXT:  ; %bb.0:
; WAVE32-NEXT:    .cfi_llvm_def_aspace_cfa 64, 0, 6
; WAVE32-NEXT:    .cfi_llvm_register_pair 16, 62, 32, 63, 32
; WAVE32-NEXT:    .cfi_undefined 1536
; WAVE32-NEXT:    .cfi_undefined 1537
; WAVE32-NEXT:    .cfi_undefined 1538
; WAVE32-NEXT:    .cfi_undefined 1539
; WAVE32-NEXT:    .cfi_undefined 1540
; WAVE32-NEXT:    .cfi_undefined 1541
; WAVE32-NEXT:    .cfi_undefined 1542
; WAVE32-NEXT:    .cfi_undefined 1543
; WAVE32-NEXT:    .cfi_undefined 1544
; WAVE32-NEXT:    .cfi_undefined 1545
; WAVE32-NEXT:    .cfi_undefined 1546
; WAVE32-NEXT:    .cfi_undefined 1547
; WAVE32-NEXT:    .cfi_undefined 1548
; WAVE32-NEXT:    .cfi_undefined 1549
; WAVE32-NEXT:    .cfi_undefined 1550
; WAVE32-NEXT:    .cfi_undefined 1551
; WAVE32-NEXT:    .cfi_undefined 1552
; WAVE32-NEXT:    .cfi_undefined 1553
; WAVE32-NEXT:    .cfi_undefined 1554
; WAVE32-NEXT:    .cfi_undefined 1555
; WAVE32-NEXT:    .cfi_undefined 1556
; WAVE32-NEXT:    .cfi_undefined 1557
; WAVE32-NEXT:    .cfi_undefined 1558
; WAVE32-NEXT:    .cfi_undefined 1559
; WAVE32-NEXT:    .cfi_undefined 1560
; WAVE32-NEXT:    .cfi_undefined 1561
; WAVE32-NEXT:    .cfi_undefined 1562
; WAVE32-NEXT:    .cfi_undefined 1563
; WAVE32-NEXT:    .cfi_undefined 1564
; WAVE32-NEXT:    .cfi_undefined 1565
; WAVE32-NEXT:    .cfi_undefined 1566
; WAVE32-NEXT:    .cfi_undefined 1567
; WAVE32-NEXT:    .cfi_undefined 1568
; WAVE32-NEXT:    .cfi_undefined 1569
; WAVE32-NEXT:    .cfi_undefined 1570
; WAVE32-NEXT:    .cfi_undefined 1571
; WAVE32-NEXT:    .cfi_undefined 1572
; WAVE32-NEXT:    .cfi_undefined 1573
; WAVE32-NEXT:    .cfi_undefined 1574
; WAVE32-NEXT:    .cfi_undefined 1575
; WAVE32-NEXT:    .cfi_undefined 1584
; WAVE32-NEXT:    .cfi_undefined 1585
; WAVE32-NEXT:    .cfi_undefined 1586
; WAVE32-NEXT:    .cfi_undefined 1587
; WAVE32-NEXT:    .cfi_undefined 1588
; WAVE32-NEXT:    .cfi_undefined 1589
; WAVE32-NEXT:    .cfi_undefined 1590
; WAVE32-NEXT:    .cfi_undefined 1591
; WAVE32-NEXT:    .cfi_undefined 1600
; WAVE32-NEXT:    .cfi_undefined 1601
; WAVE32-NEXT:    .cfi_undefined 1602
; WAVE32-NEXT:    .cfi_undefined 1603
; WAVE32-NEXT:    .cfi_undefined 1604
; WAVE32-NEXT:    .cfi_undefined 1605
; WAVE32-NEXT:    .cfi_undefined 1606
; WAVE32-NEXT:    .cfi_undefined 1607
; WAVE32-NEXT:    .cfi_undefined 1616
; WAVE32-NEXT:    .cfi_undefined 1617
; WAVE32-NEXT:    .cfi_undefined 1618
; WAVE32-NEXT:    .cfi_undefined 1619
; WAVE32-NEXT:    .cfi_undefined 1620
; WAVE32-NEXT:    .cfi_undefined 1621
; WAVE32-NEXT:    .cfi_undefined 1622
; WAVE32-NEXT:    .cfi_undefined 1623
; WAVE32-NEXT:    .cfi_undefined 1632
; WAVE32-NEXT:    .cfi_undefined 1633
; WAVE32-NEXT:    .cfi_undefined 1634
; WAVE32-NEXT:    .cfi_undefined 1635
; WAVE32-NEXT:    .cfi_undefined 1636
; WAVE32-NEXT:    .cfi_undefined 1637
; WAVE32-NEXT:    .cfi_undefined 1638
; WAVE32-NEXT:    .cfi_undefined 1639
; WAVE32-NEXT:    .cfi_undefined 1648
; WAVE32-NEXT:    .cfi_undefined 1649
; WAVE32-NEXT:    .cfi_undefined 1650
; WAVE32-NEXT:    .cfi_undefined 1651
; WAVE32-NEXT:    .cfi_undefined 1652
; WAVE32-NEXT:    .cfi_undefined 1653
; WAVE32-NEXT:    .cfi_undefined 1654
; WAVE32-NEXT:    .cfi_undefined 1655
; WAVE32-NEXT:    .cfi_undefined 1664
; WAVE32-NEXT:    .cfi_undefined 1665
; WAVE32-NEXT:    .cfi_undefined 1666
; WAVE32-NEXT:    .cfi_undefined 1667
; WAVE32-NEXT:    .cfi_undefined 1668
; WAVE32-NEXT:    .cfi_undefined 1669
; WAVE32-NEXT:    .cfi_undefined 1670
; WAVE32-NEXT:    .cfi_undefined 1671
; WAVE32-NEXT:    .cfi_undefined 1680
; WAVE32-NEXT:    .cfi_undefined 1681
; WAVE32-NEXT:    .cfi_undefined 1682
; WAVE32-NEXT:    .cfi_undefined 1683
; WAVE32-NEXT:    .cfi_undefined 1684
; WAVE32-NEXT:    .cfi_undefined 1685
; WAVE32-NEXT:    .cfi_undefined 1686
; WAVE32-NEXT:    .cfi_undefined 1687
; WAVE32-NEXT:    .cfi_undefined 1696
; WAVE32-NEXT:    .cfi_undefined 1697
; WAVE32-NEXT:    .cfi_undefined 1698
; WAVE32-NEXT:    .cfi_undefined 1699
; WAVE32-NEXT:    .cfi_undefined 1700
; WAVE32-NEXT:    .cfi_undefined 1701
; WAVE32-NEXT:    .cfi_undefined 1702
; WAVE32-NEXT:    .cfi_undefined 1703
; WAVE32-NEXT:    .cfi_undefined 1712
; WAVE32-NEXT:    .cfi_undefined 1713
; WAVE32-NEXT:    .cfi_undefined 1714
; WAVE32-NEXT:    .cfi_undefined 1715
; WAVE32-NEXT:    .cfi_undefined 1716
; WAVE32-NEXT:    .cfi_undefined 1717
; WAVE32-NEXT:    .cfi_undefined 1718
; WAVE32-NEXT:    .cfi_undefined 1719
; WAVE32-NEXT:    .cfi_undefined 1728
; WAVE32-NEXT:    .cfi_undefined 1729
; WAVE32-NEXT:    .cfi_undefined 1730
; WAVE32-NEXT:    .cfi_undefined 1731
; WAVE32-NEXT:    .cfi_undefined 1732
; WAVE32-NEXT:    .cfi_undefined 1733
; WAVE32-NEXT:    .cfi_undefined 1734
; WAVE32-NEXT:    .cfi_undefined 1735
; WAVE32-NEXT:    .cfi_undefined 1744
; WAVE32-NEXT:    .cfi_undefined 1745
; WAVE32-NEXT:    .cfi_undefined 1746
; WAVE32-NEXT:    .cfi_undefined 1747
; WAVE32-NEXT:    .cfi_undefined 1748
; WAVE32-NEXT:    .cfi_undefined 1749
; WAVE32-NEXT:    .cfi_undefined 1750
; WAVE32-NEXT:    .cfi_undefined 1751
; WAVE32-NEXT:    .cfi_undefined 1760
; WAVE32-NEXT:    .cfi_undefined 1761
; WAVE32-NEXT:    .cfi_undefined 1762
; WAVE32-NEXT:    .cfi_undefined 1763
; WAVE32-NEXT:    .cfi_undefined 1764
; WAVE32-NEXT:    .cfi_undefined 1765
; WAVE32-NEXT:    .cfi_undefined 1766
; WAVE32-NEXT:    .cfi_undefined 1767
; WAVE32-NEXT:    .cfi_undefined 1776
; WAVE32-NEXT:    .cfi_undefined 1777
; WAVE32-NEXT:    .cfi_undefined 1778
; WAVE32-NEXT:    .cfi_undefined 1779
; WAVE32-NEXT:    .cfi_undefined 1780
; WAVE32-NEXT:    .cfi_undefined 1781
; WAVE32-NEXT:    .cfi_undefined 1782
; WAVE32-NEXT:    .cfi_undefined 1783
; WAVE32-NEXT:    .cfi_undefined 36
; WAVE32-NEXT:    .cfi_undefined 37
; WAVE32-NEXT:    .cfi_undefined 38
; WAVE32-NEXT:    .cfi_undefined 39
; WAVE32-NEXT:    .cfi_undefined 40
; WAVE32-NEXT:    .cfi_undefined 41
; WAVE32-NEXT:    .cfi_undefined 42
; WAVE32-NEXT:    .cfi_undefined 43
; WAVE32-NEXT:    .cfi_undefined 44
; WAVE32-NEXT:    .cfi_undefined 45
; WAVE32-NEXT:    .cfi_undefined 46
; WAVE32-NEXT:    .cfi_undefined 47
; WAVE32-NEXT:    .cfi_undefined 48
; WAVE32-NEXT:    .cfi_undefined 49
; WAVE32-NEXT:    .cfi_undefined 50
; WAVE32-NEXT:    .cfi_undefined 51
; WAVE32-NEXT:    .cfi_undefined 52
; WAVE32-NEXT:    .cfi_undefined 53
; WAVE32-NEXT:    .cfi_undefined 54
; WAVE32-NEXT:    .cfi_undefined 55
; WAVE32-NEXT:    .cfi_undefined 56
; WAVE32-NEXT:    .cfi_undefined 57
; WAVE32-NEXT:    .cfi_undefined 58
; WAVE32-NEXT:    .cfi_undefined 59
; WAVE32-NEXT:    .cfi_undefined 60
; WAVE32-NEXT:    .cfi_undefined 61
; WAVE32-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; WAVE32-NEXT:    s_mov_b32 s40, s33
; WAVE32-NEXT:    .cfi_register 65, 72
; WAVE32-NEXT:    s_mov_b32 s33, s32
; WAVE32-NEXT:    .cfi_def_cfa_register 65
; WAVE32-NEXT:    buffer_store_dword v40, off, s[0:3], s33 offset:444 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v41, off, s[0:3], s33 offset:440 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v42, off, s[0:3], s33 offset:436 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v43, off, s[0:3], s33 offset:432 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v44, off, s[0:3], s33 offset:428 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v45, off, s[0:3], s33 offset:424 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v46, off, s[0:3], s33 offset:420 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v47, off, s[0:3], s33 offset:416 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v56, off, s[0:3], s33 offset:412 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v57, off, s[0:3], s33 offset:408 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v58, off, s[0:3], s33 offset:404 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v59, off, s[0:3], s33 offset:400 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v60, off, s[0:3], s33 offset:396 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v61, off, s[0:3], s33 offset:392 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v62, off, s[0:3], s33 offset:388 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v63, off, s[0:3], s33 offset:384 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v72, off, s[0:3], s33 offset:380 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v73, off, s[0:3], s33 offset:376 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v74, off, s[0:3], s33 offset:372 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v75, off, s[0:3], s33 offset:368 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v76, off, s[0:3], s33 offset:364 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v77, off, s[0:3], s33 offset:360 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v78, off, s[0:3], s33 offset:356 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v79, off, s[0:3], s33 offset:352 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v88, off, s[0:3], s33 offset:348 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v89, off, s[0:3], s33 offset:344 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v90, off, s[0:3], s33 offset:340 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v91, off, s[0:3], s33 offset:336 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v92, off, s[0:3], s33 offset:332 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v93, off, s[0:3], s33 offset:328 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v94, off, s[0:3], s33 offset:324 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v95, off, s[0:3], s33 offset:320 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v104, off, s[0:3], s33 offset:316 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v105, off, s[0:3], s33 offset:312 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v106, off, s[0:3], s33 offset:308 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v107, off, s[0:3], s33 offset:304 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v108, off, s[0:3], s33 offset:300 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v109, off, s[0:3], s33 offset:296 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v110, off, s[0:3], s33 offset:292 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v111, off, s[0:3], s33 offset:288 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v120, off, s[0:3], s33 offset:284 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v121, off, s[0:3], s33 offset:280 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v122, off, s[0:3], s33 offset:276 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v123, off, s[0:3], s33 offset:272 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v124, off, s[0:3], s33 offset:268 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v125, off, s[0:3], s33 offset:264 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v126, off, s[0:3], s33 offset:260 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v127, off, s[0:3], s33 offset:256 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v136, off, s[0:3], s33 offset:252 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v137, off, s[0:3], s33 offset:248 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v138, off, s[0:3], s33 offset:244 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v139, off, s[0:3], s33 offset:240 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v140, off, s[0:3], s33 offset:236 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v141, off, s[0:3], s33 offset:232 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v142, off, s[0:3], s33 offset:228 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v143, off, s[0:3], s33 offset:224 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v152, off, s[0:3], s33 offset:220 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v153, off, s[0:3], s33 offset:216 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v154, off, s[0:3], s33 offset:212 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v155, off, s[0:3], s33 offset:208 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v156, off, s[0:3], s33 offset:204 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v157, off, s[0:3], s33 offset:200 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v158, off, s[0:3], s33 offset:196 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v159, off, s[0:3], s33 offset:192 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v168, off, s[0:3], s33 offset:188 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v169, off, s[0:3], s33 offset:184 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v170, off, s[0:3], s33 offset:180 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v171, off, s[0:3], s33 offset:176 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v172, off, s[0:3], s33 offset:172 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v173, off, s[0:3], s33 offset:168 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v174, off, s[0:3], s33 offset:164 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v175, off, s[0:3], s33 offset:160 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v184, off, s[0:3], s33 offset:156 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v185, off, s[0:3], s33 offset:152 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v186, off, s[0:3], s33 offset:148 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v187, off, s[0:3], s33 offset:144 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v188, off, s[0:3], s33 offset:140 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v189, off, s[0:3], s33 offset:136 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v190, off, s[0:3], s33 offset:132 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v191, off, s[0:3], s33 offset:128 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v200, off, s[0:3], s33 offset:124 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v201, off, s[0:3], s33 offset:120 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v202, off, s[0:3], s33 offset:116 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v203, off, s[0:3], s33 offset:112 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v204, off, s[0:3], s33 offset:108 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v205, off, s[0:3], s33 offset:104 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v206, off, s[0:3], s33 offset:100 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v207, off, s[0:3], s33 offset:96 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v216, off, s[0:3], s33 offset:92 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v217, off, s[0:3], s33 offset:88 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v218, off, s[0:3], s33 offset:84 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v219, off, s[0:3], s33 offset:80 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v220, off, s[0:3], s33 offset:76 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v221, off, s[0:3], s33 offset:72 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v222, off, s[0:3], s33 offset:68 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v223, off, s[0:3], s33 offset:64 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v232, off, s[0:3], s33 offset:60 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v233, off, s[0:3], s33 offset:56 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v234, off, s[0:3], s33 offset:52 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v235, off, s[0:3], s33 offset:48 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v236, off, s[0:3], s33 offset:44 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v237, off, s[0:3], s33 offset:40 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v238, off, s[0:3], s33 offset:36 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v239, off, s[0:3], s33 offset:32 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v248, off, s[0:3], s33 offset:28 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v249, off, s[0:3], s33 offset:24 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v250, off, s[0:3], s33 offset:20 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v251, off, s[0:3], s33 offset:16 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v252, off, s[0:3], s33 offset:12 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v253, off, s[0:3], s33 offset:8 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v254, off, s[0:3], s33 offset:4 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v255, off, s[0:3], s33 ; 4-byte Folded Spill
; WAVE32-NEXT:    ;;#ASMSTART
; WAVE32-NEXT:    ; clobber nonpreserved SGPRs
; WAVE32-NEXT:    ;;#ASMEND
; WAVE32-NEXT:    ;;#ASMSTART
; WAVE32-NEXT:    ; clobber all VGPRs
; WAVE32-NEXT:    ;;#ASMEND
; WAVE32-NEXT:    s_clause 0x3e ; 252-byte Folded Reload
; WAVE32-NEXT:    buffer_load_dword v255, off, s[0:3], s33
; WAVE32-NEXT:    buffer_load_dword v254, off, s[0:3], s33 offset:4
; WAVE32-NEXT:    buffer_load_dword v253, off, s[0:3], s33 offset:8
; WAVE32-NEXT:    buffer_load_dword v252, off, s[0:3], s33 offset:12
; WAVE32-NEXT:    buffer_load_dword v251, off, s[0:3], s33 offset:16
; WAVE32-NEXT:    buffer_load_dword v250, off, s[0:3], s33 offset:20
; WAVE32-NEXT:    buffer_load_dword v249, off, s[0:3], s33 offset:24
; WAVE32-NEXT:    buffer_load_dword v248, off, s[0:3], s33 offset:28
; WAVE32-NEXT:    buffer_load_dword v239, off, s[0:3], s33 offset:32
; WAVE32-NEXT:    buffer_load_dword v238, off, s[0:3], s33 offset:36
; WAVE32-NEXT:    buffer_load_dword v237, off, s[0:3], s33 offset:40
; WAVE32-NEXT:    buffer_load_dword v236, off, s[0:3], s33 offset:44
; WAVE32-NEXT:    buffer_load_dword v235, off, s[0:3], s33 offset:48
; WAVE32-NEXT:    buffer_load_dword v234, off, s[0:3], s33 offset:52
; WAVE32-NEXT:    buffer_load_dword v233, off, s[0:3], s33 offset:56
; WAVE32-NEXT:    buffer_load_dword v232, off, s[0:3], s33 offset:60
; WAVE32-NEXT:    buffer_load_dword v223, off, s[0:3], s33 offset:64
; WAVE32-NEXT:    buffer_load_dword v222, off, s[0:3], s33 offset:68
; WAVE32-NEXT:    buffer_load_dword v221, off, s[0:3], s33 offset:72
; WAVE32-NEXT:    buffer_load_dword v220, off, s[0:3], s33 offset:76
; WAVE32-NEXT:    buffer_load_dword v219, off, s[0:3], s33 offset:80
; WAVE32-NEXT:    buffer_load_dword v218, off, s[0:3], s33 offset:84
; WAVE32-NEXT:    buffer_load_dword v217, off, s[0:3], s33 offset:88
; WAVE32-NEXT:    buffer_load_dword v216, off, s[0:3], s33 offset:92
; WAVE32-NEXT:    buffer_load_dword v207, off, s[0:3], s33 offset:96
; WAVE32-NEXT:    buffer_load_dword v206, off, s[0:3], s33 offset:100
; WAVE32-NEXT:    buffer_load_dword v205, off, s[0:3], s33 offset:104
; WAVE32-NEXT:    buffer_load_dword v204, off, s[0:3], s33 offset:108
; WAVE32-NEXT:    buffer_load_dword v203, off, s[0:3], s33 offset:112
; WAVE32-NEXT:    buffer_load_dword v202, off, s[0:3], s33 offset:116
; WAVE32-NEXT:    buffer_load_dword v201, off, s[0:3], s33 offset:120
; WAVE32-NEXT:    buffer_load_dword v200, off, s[0:3], s33 offset:124
; WAVE32-NEXT:    buffer_load_dword v191, off, s[0:3], s33 offset:128
; WAVE32-NEXT:    buffer_load_dword v190, off, s[0:3], s33 offset:132
; WAVE32-NEXT:    buffer_load_dword v189, off, s[0:3], s33 offset:136
; WAVE32-NEXT:    buffer_load_dword v188, off, s[0:3], s33 offset:140
; WAVE32-NEXT:    buffer_load_dword v187, off, s[0:3], s33 offset:144
; WAVE32-NEXT:    buffer_load_dword v186, off, s[0:3], s33 offset:148
; WAVE32-NEXT:    buffer_load_dword v185, off, s[0:3], s33 offset:152
; WAVE32-NEXT:    buffer_load_dword v184, off, s[0:3], s33 offset:156
; WAVE32-NEXT:    buffer_load_dword v175, off, s[0:3], s33 offset:160
; WAVE32-NEXT:    buffer_load_dword v174, off, s[0:3], s33 offset:164
; WAVE32-NEXT:    buffer_load_dword v173, off, s[0:3], s33 offset:168
; WAVE32-NEXT:    buffer_load_dword v172, off, s[0:3], s33 offset:172
; WAVE32-NEXT:    buffer_load_dword v171, off, s[0:3], s33 offset:176
; WAVE32-NEXT:    buffer_load_dword v170, off, s[0:3], s33 offset:180
; WAVE32-NEXT:    buffer_load_dword v169, off, s[0:3], s33 offset:184
; WAVE32-NEXT:    buffer_load_dword v168, off, s[0:3], s33 offset:188
; WAVE32-NEXT:    buffer_load_dword v159, off, s[0:3], s33 offset:192
; WAVE32-NEXT:    buffer_load_dword v158, off, s[0:3], s33 offset:196
; WAVE32-NEXT:    buffer_load_dword v157, off, s[0:3], s33 offset:200
; WAVE32-NEXT:    buffer_load_dword v156, off, s[0:3], s33 offset:204
; WAVE32-NEXT:    buffer_load_dword v155, off, s[0:3], s33 offset:208
; WAVE32-NEXT:    buffer_load_dword v154, off, s[0:3], s33 offset:212
; WAVE32-NEXT:    buffer_load_dword v153, off, s[0:3], s33 offset:216
; WAVE32-NEXT:    buffer_load_dword v152, off, s[0:3], s33 offset:220
; WAVE32-NEXT:    buffer_load_dword v143, off, s[0:3], s33 offset:224
; WAVE32-NEXT:    buffer_load_dword v142, off, s[0:3], s33 offset:228
; WAVE32-NEXT:    buffer_load_dword v141, off, s[0:3], s33 offset:232
; WAVE32-NEXT:    buffer_load_dword v140, off, s[0:3], s33 offset:236
; WAVE32-NEXT:    buffer_load_dword v139, off, s[0:3], s33 offset:240
; WAVE32-NEXT:    buffer_load_dword v138, off, s[0:3], s33 offset:244
; WAVE32-NEXT:    buffer_load_dword v137, off, s[0:3], s33 offset:248
; WAVE32-NEXT:    s_clause 0x30 ; 196-byte Folded Reload
; WAVE32-NEXT:    buffer_load_dword v136, off, s[0:3], s33 offset:252
; WAVE32-NEXT:    buffer_load_dword v127, off, s[0:3], s33 offset:256
; WAVE32-NEXT:    buffer_load_dword v126, off, s[0:3], s33 offset:260
; WAVE32-NEXT:    buffer_load_dword v125, off, s[0:3], s33 offset:264
; WAVE32-NEXT:    buffer_load_dword v124, off, s[0:3], s33 offset:268
; WAVE32-NEXT:    buffer_load_dword v123, off, s[0:3], s33 offset:272
; WAVE32-NEXT:    buffer_load_dword v122, off, s[0:3], s33 offset:276
; WAVE32-NEXT:    buffer_load_dword v121, off, s[0:3], s33 offset:280
; WAVE32-NEXT:    buffer_load_dword v120, off, s[0:3], s33 offset:284
; WAVE32-NEXT:    buffer_load_dword v111, off, s[0:3], s33 offset:288
; WAVE32-NEXT:    buffer_load_dword v110, off, s[0:3], s33 offset:292
; WAVE32-NEXT:    buffer_load_dword v109, off, s[0:3], s33 offset:296
; WAVE32-NEXT:    buffer_load_dword v108, off, s[0:3], s33 offset:300
; WAVE32-NEXT:    buffer_load_dword v107, off, s[0:3], s33 offset:304
; WAVE32-NEXT:    buffer_load_dword v106, off, s[0:3], s33 offset:308
; WAVE32-NEXT:    buffer_load_dword v105, off, s[0:3], s33 offset:312
; WAVE32-NEXT:    buffer_load_dword v104, off, s[0:3], s33 offset:316
; WAVE32-NEXT:    buffer_load_dword v95, off, s[0:3], s33 offset:320
; WAVE32-NEXT:    buffer_load_dword v94, off, s[0:3], s33 offset:324
; WAVE32-NEXT:    buffer_load_dword v93, off, s[0:3], s33 offset:328
; WAVE32-NEXT:    buffer_load_dword v92, off, s[0:3], s33 offset:332
; WAVE32-NEXT:    buffer_load_dword v91, off, s[0:3], s33 offset:336
; WAVE32-NEXT:    buffer_load_dword v90, off, s[0:3], s33 offset:340
; WAVE32-NEXT:    buffer_load_dword v89, off, s[0:3], s33 offset:344
; WAVE32-NEXT:    buffer_load_dword v88, off, s[0:3], s33 offset:348
; WAVE32-NEXT:    buffer_load_dword v79, off, s[0:3], s33 offset:352
; WAVE32-NEXT:    buffer_load_dword v78, off, s[0:3], s33 offset:356
; WAVE32-NEXT:    buffer_load_dword v77, off, s[0:3], s33 offset:360
; WAVE32-NEXT:    buffer_load_dword v76, off, s[0:3], s33 offset:364
; WAVE32-NEXT:    buffer_load_dword v75, off, s[0:3], s33 offset:368
; WAVE32-NEXT:    buffer_load_dword v74, off, s[0:3], s33 offset:372
; WAVE32-NEXT:    buffer_load_dword v73, off, s[0:3], s33 offset:376
; WAVE32-NEXT:    buffer_load_dword v72, off, s[0:3], s33 offset:380
; WAVE32-NEXT:    buffer_load_dword v63, off, s[0:3], s33 offset:384
; WAVE32-NEXT:    buffer_load_dword v62, off, s[0:3], s33 offset:388
; WAVE32-NEXT:    buffer_load_dword v61, off, s[0:3], s33 offset:392
; WAVE32-NEXT:    buffer_load_dword v60, off, s[0:3], s33 offset:396
; WAVE32-NEXT:    buffer_load_dword v59, off, s[0:3], s33 offset:400
; WAVE32-NEXT:    buffer_load_dword v58, off, s[0:3], s33 offset:404
; WAVE32-NEXT:    buffer_load_dword v57, off, s[0:3], s33 offset:408
; WAVE32-NEXT:    buffer_load_dword v56, off, s[0:3], s33 offset:412
; WAVE32-NEXT:    buffer_load_dword v47, off, s[0:3], s33 offset:416
; WAVE32-NEXT:    buffer_load_dword v46, off, s[0:3], s33 offset:420
; WAVE32-NEXT:    buffer_load_dword v45, off, s[0:3], s33 offset:424
; WAVE32-NEXT:    buffer_load_dword v44, off, s[0:3], s33 offset:428
; WAVE32-NEXT:    buffer_load_dword v43, off, s[0:3], s33 offset:432
; WAVE32-NEXT:    buffer_load_dword v42, off, s[0:3], s33 offset:436
; WAVE32-NEXT:    buffer_load_dword v41, off, s[0:3], s33 offset:440
; WAVE32-NEXT:    buffer_load_dword v40, off, s[0:3], s33 offset:444
; WAVE32-NEXT:    s_addk_i32 s32, 0x3880
; WAVE32-NEXT:    s_mov_b32 s32, s33
; WAVE32-NEXT:    .cfi_def_cfa_register 64
; WAVE32-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; WAVE32-NEXT:    s_mov_b32 s33, s40
; WAVE32-NEXT:    s_waitcnt vmcnt(0)
; WAVE32-NEXT:    s_setpc_b64 s[30:31]
  call void asm sideeffect "; clobber nonpreserved SGPRs",
    "~{s4},~{s5},~{s6},~{s7},~{s8},~{s9}
    ,~{s10},~{s11},~{s12},~{s13},~{s14},~{s15},~{s16},~{s17},~{s18},~{s19}
    ,~{s20},~{s21},~{s22},~{s23},~{s24},~{s25},~{s26},~{s27},~{s28},~{s29}
    ,~{vcc}"()

  call void asm sideeffect "; clobber all VGPRs",
    "~{v0},~{v1},~{v2},~{v3},~{v4},~{v5},~{v6},~{v7},~{v8},~{v9}
    ,~{v10},~{v11},~{v12},~{v13},~{v14},~{v15},~{v16},~{v17},~{v18},~{v19}
    ,~{v20},~{v21},~{v22},~{v23},~{v24},~{v25},~{v26},~{v27},~{v28},~{v29}
    ,~{v30},~{v31},~{v32},~{v33},~{v34},~{v35},~{v36},~{v37},~{v38},~{v39}
    ,~{v40},~{v41},~{v42},~{v43},~{v44},~{v45},~{v46},~{v47},~{v48},~{v49}
    ,~{v50},~{v51},~{v52},~{v53},~{v54},~{v55},~{v56},~{v57},~{v58},~{v59}
    ,~{v60},~{v61},~{v62},~{v63},~{v64},~{v65},~{v66},~{v67},~{v68},~{v69}
    ,~{v70},~{v71},~{v72},~{v73},~{v74},~{v75},~{v76},~{v77},~{v78},~{v79}
    ,~{v80},~{v81},~{v82},~{v83},~{v84},~{v85},~{v86},~{v87},~{v88},~{v89}
    ,~{v90},~{v91},~{v92},~{v93},~{v94},~{v95},~{v96},~{v97},~{v98},~{v99}
    ,~{v100},~{v101},~{v102},~{v103},~{v104},~{v105},~{v106},~{v107},~{v108},~{v109}
    ,~{v110},~{v111},~{v112},~{v113},~{v114},~{v115},~{v116},~{v117},~{v118},~{v119}
    ,~{v120},~{v121},~{v122},~{v123},~{v124},~{v125},~{v126},~{v127},~{v128},~{v129}
    ,~{v130},~{v131},~{v132},~{v133},~{v134},~{v135},~{v136},~{v137},~{v138},~{v139}
    ,~{v140},~{v141},~{v142},~{v143},~{v144},~{v145},~{v146},~{v147},~{v148},~{v149}
    ,~{v150},~{v151},~{v152},~{v153},~{v154},~{v155},~{v156},~{v157},~{v158},~{v159}
    ,~{v160},~{v161},~{v162},~{v163},~{v164},~{v165},~{v166},~{v167},~{v168},~{v169}
    ,~{v170},~{v171},~{v172},~{v173},~{v174},~{v175},~{v176},~{v177},~{v178},~{v179}
    ,~{v180},~{v181},~{v182},~{v183},~{v184},~{v185},~{v186},~{v187},~{v188},~{v189}
    ,~{v190},~{v191},~{v192},~{v193},~{v194},~{v195},~{v196},~{v197},~{v198},~{v199}
    ,~{v200},~{v201},~{v202},~{v203},~{v204},~{v205},~{v206},~{v207},~{v208},~{v209}
    ,~{v210},~{v211},~{v212},~{v213},~{v214},~{v215},~{v216},~{v217},~{v218},~{v219}
    ,~{v220},~{v221},~{v222},~{v223},~{v224},~{v225},~{v226},~{v227},~{v228},~{v229}
    ,~{v230},~{v231},~{v232},~{v233},~{v234},~{v235},~{v236},~{v237},~{v238},~{v239}
    ,~{v240},~{v241},~{v242},~{v243},~{v244},~{v245},~{v246},~{v247},~{v248},~{v249}
    ,~{v250},~{v251},~{v252},~{v253},~{v254},~{v255}"()
  ret void
}

declare hidden void @ex() #0

define hidden void @func_call_clobber() #0 {
; GFX900-LABEL: func_call_clobber:
; GFX900:       .Lfunc_begin3:
; GFX900-NEXT:    .cfi_startproc
; GFX900-NEXT:  ; %bb.0: ; %entry
; GFX900-NEXT:    .cfi_llvm_def_aspace_cfa 64, 0, 6
; GFX900-NEXT:    .cfi_llvm_register_pair 16, 62, 32, 63, 32
; GFX900-NEXT:    .cfi_undefined 2560
; GFX900-NEXT:    .cfi_undefined 2561
; GFX900-NEXT:    .cfi_undefined 2562
; GFX900-NEXT:    .cfi_undefined 2563
; GFX900-NEXT:    .cfi_undefined 2564
; GFX900-NEXT:    .cfi_undefined 2565
; GFX900-NEXT:    .cfi_undefined 2566
; GFX900-NEXT:    .cfi_undefined 2567
; GFX900-NEXT:    .cfi_undefined 2568
; GFX900-NEXT:    .cfi_undefined 2569
; GFX900-NEXT:    .cfi_undefined 2570
; GFX900-NEXT:    .cfi_undefined 2571
; GFX900-NEXT:    .cfi_undefined 2572
; GFX900-NEXT:    .cfi_undefined 2573
; GFX900-NEXT:    .cfi_undefined 2574
; GFX900-NEXT:    .cfi_undefined 2575
; GFX900-NEXT:    .cfi_undefined 2576
; GFX900-NEXT:    .cfi_undefined 2577
; GFX900-NEXT:    .cfi_undefined 2578
; GFX900-NEXT:    .cfi_undefined 2579
; GFX900-NEXT:    .cfi_undefined 2580
; GFX900-NEXT:    .cfi_undefined 2581
; GFX900-NEXT:    .cfi_undefined 2582
; GFX900-NEXT:    .cfi_undefined 2583
; GFX900-NEXT:    .cfi_undefined 2584
; GFX900-NEXT:    .cfi_undefined 2585
; GFX900-NEXT:    .cfi_undefined 2586
; GFX900-NEXT:    .cfi_undefined 2587
; GFX900-NEXT:    .cfi_undefined 2588
; GFX900-NEXT:    .cfi_undefined 2589
; GFX900-NEXT:    .cfi_undefined 2590
; GFX900-NEXT:    .cfi_undefined 2591
; GFX900-NEXT:    .cfi_undefined 2592
; GFX900-NEXT:    .cfi_undefined 2593
; GFX900-NEXT:    .cfi_undefined 2594
; GFX900-NEXT:    .cfi_undefined 2595
; GFX900-NEXT:    .cfi_undefined 2596
; GFX900-NEXT:    .cfi_undefined 2597
; GFX900-NEXT:    .cfi_undefined 2598
; GFX900-NEXT:    .cfi_undefined 2599
; GFX900-NEXT:    .cfi_undefined 2608
; GFX900-NEXT:    .cfi_undefined 2609
; GFX900-NEXT:    .cfi_undefined 2610
; GFX900-NEXT:    .cfi_undefined 2611
; GFX900-NEXT:    .cfi_undefined 2612
; GFX900-NEXT:    .cfi_undefined 2613
; GFX900-NEXT:    .cfi_undefined 2614
; GFX900-NEXT:    .cfi_undefined 2615
; GFX900-NEXT:    .cfi_undefined 2624
; GFX900-NEXT:    .cfi_undefined 2625
; GFX900-NEXT:    .cfi_undefined 2626
; GFX900-NEXT:    .cfi_undefined 2627
; GFX900-NEXT:    .cfi_undefined 2628
; GFX900-NEXT:    .cfi_undefined 2629
; GFX900-NEXT:    .cfi_undefined 2630
; GFX900-NEXT:    .cfi_undefined 2631
; GFX900-NEXT:    .cfi_undefined 2640
; GFX900-NEXT:    .cfi_undefined 2641
; GFX900-NEXT:    .cfi_undefined 2642
; GFX900-NEXT:    .cfi_undefined 2643
; GFX900-NEXT:    .cfi_undefined 2644
; GFX900-NEXT:    .cfi_undefined 2645
; GFX900-NEXT:    .cfi_undefined 2646
; GFX900-NEXT:    .cfi_undefined 2647
; GFX900-NEXT:    .cfi_undefined 2656
; GFX900-NEXT:    .cfi_undefined 2657
; GFX900-NEXT:    .cfi_undefined 2658
; GFX900-NEXT:    .cfi_undefined 2659
; GFX900-NEXT:    .cfi_undefined 2660
; GFX900-NEXT:    .cfi_undefined 2661
; GFX900-NEXT:    .cfi_undefined 2662
; GFX900-NEXT:    .cfi_undefined 2663
; GFX900-NEXT:    .cfi_undefined 2672
; GFX900-NEXT:    .cfi_undefined 2673
; GFX900-NEXT:    .cfi_undefined 2674
; GFX900-NEXT:    .cfi_undefined 2675
; GFX900-NEXT:    .cfi_undefined 2676
; GFX900-NEXT:    .cfi_undefined 2677
; GFX900-NEXT:    .cfi_undefined 2678
; GFX900-NEXT:    .cfi_undefined 2679
; GFX900-NEXT:    .cfi_undefined 2688
; GFX900-NEXT:    .cfi_undefined 2689
; GFX900-NEXT:    .cfi_undefined 2690
; GFX900-NEXT:    .cfi_undefined 2691
; GFX900-NEXT:    .cfi_undefined 2692
; GFX900-NEXT:    .cfi_undefined 2693
; GFX900-NEXT:    .cfi_undefined 2694
; GFX900-NEXT:    .cfi_undefined 2695
; GFX900-NEXT:    .cfi_undefined 2704
; GFX900-NEXT:    .cfi_undefined 2705
; GFX900-NEXT:    .cfi_undefined 2706
; GFX900-NEXT:    .cfi_undefined 2707
; GFX900-NEXT:    .cfi_undefined 2708
; GFX900-NEXT:    .cfi_undefined 2709
; GFX900-NEXT:    .cfi_undefined 2710
; GFX900-NEXT:    .cfi_undefined 2711
; GFX900-NEXT:    .cfi_undefined 2720
; GFX900-NEXT:    .cfi_undefined 2721
; GFX900-NEXT:    .cfi_undefined 2722
; GFX900-NEXT:    .cfi_undefined 2723
; GFX900-NEXT:    .cfi_undefined 2724
; GFX900-NEXT:    .cfi_undefined 2725
; GFX900-NEXT:    .cfi_undefined 2726
; GFX900-NEXT:    .cfi_undefined 2727
; GFX900-NEXT:    .cfi_undefined 2736
; GFX900-NEXT:    .cfi_undefined 2737
; GFX900-NEXT:    .cfi_undefined 2738
; GFX900-NEXT:    .cfi_undefined 2739
; GFX900-NEXT:    .cfi_undefined 2740
; GFX900-NEXT:    .cfi_undefined 2741
; GFX900-NEXT:    .cfi_undefined 2742
; GFX900-NEXT:    .cfi_undefined 2743
; GFX900-NEXT:    .cfi_undefined 2752
; GFX900-NEXT:    .cfi_undefined 2753
; GFX900-NEXT:    .cfi_undefined 2754
; GFX900-NEXT:    .cfi_undefined 2755
; GFX900-NEXT:    .cfi_undefined 2756
; GFX900-NEXT:    .cfi_undefined 2757
; GFX900-NEXT:    .cfi_undefined 2758
; GFX900-NEXT:    .cfi_undefined 2759
; GFX900-NEXT:    .cfi_undefined 2768
; GFX900-NEXT:    .cfi_undefined 2769
; GFX900-NEXT:    .cfi_undefined 2770
; GFX900-NEXT:    .cfi_undefined 2771
; GFX900-NEXT:    .cfi_undefined 2772
; GFX900-NEXT:    .cfi_undefined 2773
; GFX900-NEXT:    .cfi_undefined 2774
; GFX900-NEXT:    .cfi_undefined 2775
; GFX900-NEXT:    .cfi_undefined 2784
; GFX900-NEXT:    .cfi_undefined 2785
; GFX900-NEXT:    .cfi_undefined 2786
; GFX900-NEXT:    .cfi_undefined 2787
; GFX900-NEXT:    .cfi_undefined 2788
; GFX900-NEXT:    .cfi_undefined 2789
; GFX900-NEXT:    .cfi_undefined 2790
; GFX900-NEXT:    .cfi_undefined 2791
; GFX900-NEXT:    .cfi_undefined 2800
; GFX900-NEXT:    .cfi_undefined 2801
; GFX900-NEXT:    .cfi_undefined 2802
; GFX900-NEXT:    .cfi_undefined 2803
; GFX900-NEXT:    .cfi_undefined 2804
; GFX900-NEXT:    .cfi_undefined 2805
; GFX900-NEXT:    .cfi_undefined 2806
; GFX900-NEXT:    .cfi_undefined 2807
; GFX900-NEXT:    .cfi_undefined 32
; GFX900-NEXT:    .cfi_undefined 33
; GFX900-NEXT:    .cfi_undefined 34
; GFX900-NEXT:    .cfi_undefined 35
; GFX900-NEXT:    .cfi_undefined 36
; GFX900-NEXT:    .cfi_undefined 37
; GFX900-NEXT:    .cfi_undefined 38
; GFX900-NEXT:    .cfi_undefined 39
; GFX900-NEXT:    .cfi_undefined 40
; GFX900-NEXT:    .cfi_undefined 41
; GFX900-NEXT:    .cfi_undefined 42
; GFX900-NEXT:    .cfi_undefined 43
; GFX900-NEXT:    .cfi_undefined 44
; GFX900-NEXT:    .cfi_undefined 45
; GFX900-NEXT:    .cfi_undefined 46
; GFX900-NEXT:    .cfi_undefined 47
; GFX900-NEXT:    .cfi_undefined 48
; GFX900-NEXT:    .cfi_undefined 49
; GFX900-NEXT:    .cfi_undefined 50
; GFX900-NEXT:    .cfi_undefined 51
; GFX900-NEXT:    .cfi_undefined 52
; GFX900-NEXT:    .cfi_undefined 53
; GFX900-NEXT:    .cfi_undefined 54
; GFX900-NEXT:    .cfi_undefined 55
; GFX900-NEXT:    .cfi_undefined 56
; GFX900-NEXT:    .cfi_undefined 57
; GFX900-NEXT:    .cfi_undefined 58
; GFX900-NEXT:    .cfi_undefined 59
; GFX900-NEXT:    .cfi_undefined 60
; GFX900-NEXT:    .cfi_undefined 61
; GFX900-NEXT:    .cfi_undefined 72
; GFX900-NEXT:    .cfi_undefined 73
; GFX900-NEXT:    .cfi_undefined 74
; GFX900-NEXT:    .cfi_undefined 75
; GFX900-NEXT:    .cfi_undefined 76
; GFX900-NEXT:    .cfi_undefined 77
; GFX900-NEXT:    .cfi_undefined 78
; GFX900-NEXT:    .cfi_undefined 79
; GFX900-NEXT:    .cfi_undefined 88
; GFX900-NEXT:    .cfi_undefined 89
; GFX900-NEXT:    .cfi_undefined 90
; GFX900-NEXT:    .cfi_undefined 91
; GFX900-NEXT:    .cfi_undefined 92
; GFX900-NEXT:    .cfi_undefined 93
; GFX900-NEXT:    .cfi_undefined 94
; GFX900-NEXT:    .cfi_undefined 95
; GFX900-NEXT:    .cfi_undefined 1096
; GFX900-NEXT:    .cfi_undefined 1097
; GFX900-NEXT:    .cfi_undefined 1098
; GFX900-NEXT:    .cfi_undefined 1099
; GFX900-NEXT:    .cfi_undefined 1100
; GFX900-NEXT:    .cfi_undefined 1101
; GFX900-NEXT:    .cfi_undefined 1102
; GFX900-NEXT:    .cfi_undefined 1103
; GFX900-NEXT:    .cfi_undefined 1112
; GFX900-NEXT:    .cfi_undefined 1113
; GFX900-NEXT:    .cfi_undefined 1114
; GFX900-NEXT:    .cfi_undefined 1115
; GFX900-NEXT:    .cfi_undefined 1116
; GFX900-NEXT:    .cfi_undefined 1117
; GFX900-NEXT:    .cfi_undefined 1118
; GFX900-NEXT:    .cfi_undefined 1119
; GFX900-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX900-NEXT:    s_mov_b32 s16, s33
; GFX900-NEXT:    s_mov_b32 s33, s32
; GFX900-NEXT:    s_or_saveexec_b64 s[18:19], -1
; GFX900-NEXT:    buffer_store_dword v40, off, s[0:3], s33 ; 4-byte Folded Spill
; GFX900-NEXT:    .cfi_offset 2600, 0
; GFX900-NEXT:    s_mov_b64 exec, s[18:19]
; GFX900-NEXT:    v_writelane_b32 v40, s16, 2
; GFX900-NEXT:    .cfi_llvm_vector_registers 65, 2600, 2, 32
; GFX900-NEXT:    .cfi_def_cfa_register 65
; GFX900-NEXT:    s_addk_i32 s32, 0x400
; GFX900-NEXT:    v_writelane_b32 v40, s30, 0
; GFX900-NEXT:    s_getpc_b64 s[16:17]
; GFX900-NEXT:    s_add_u32 s16, s16, ex@rel32@lo+4
; GFX900-NEXT:    s_addc_u32 s17, s17, ex@rel32@hi+12
; GFX900-NEXT:    v_writelane_b32 v40, s31, 1
; GFX900-NEXT:    s_swappc_b64 s[30:31], s[16:17]
; GFX900-NEXT:    v_readlane_b32 s30, v40, 0
; GFX900-NEXT:    v_readlane_b32 s31, v40, 1
; GFX900-NEXT:    s_mov_b32 s32, s33
; GFX900-NEXT:    v_readlane_b32 s4, v40, 2
; GFX900-NEXT:    s_or_saveexec_b64 s[6:7], -1
; GFX900-NEXT:    buffer_load_dword v40, off, s[0:3], s33 ; 4-byte Folded Reload
; GFX900-NEXT:    s_mov_b64 exec, s[6:7]
; GFX900-NEXT:    .cfi_def_cfa_register 64
; GFX900-NEXT:    s_mov_b32 s33, s4
; GFX900-NEXT:    s_waitcnt vmcnt(0)
; GFX900-NEXT:    s_setpc_b64 s[30:31]
;
; GFX90A-V2A-DIS-LABEL: func_call_clobber:
; GFX90A-V2A-DIS:       .Lfunc_begin3:
; GFX90A-V2A-DIS-NEXT:    .cfi_startproc
; GFX90A-V2A-DIS-NEXT:  ; %bb.0: ; %entry
; GFX90A-V2A-DIS-NEXT:    .cfi_llvm_def_aspace_cfa 64, 0, 6
; GFX90A-V2A-DIS-NEXT:    .cfi_llvm_register_pair 16, 62, 32, 63, 32
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2560
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2561
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2562
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2563
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2564
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2565
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2566
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2567
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2568
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2569
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2570
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2571
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2572
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2573
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2574
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2575
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2576
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2577
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2578
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2579
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2580
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2581
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2582
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2583
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2584
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2585
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2586
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2587
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2588
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2589
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2590
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2591
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2592
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2593
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2594
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2595
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2596
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2597
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2598
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2599
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2608
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2609
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2610
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2611
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2612
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2613
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2614
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2615
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2624
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2625
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2626
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2627
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2628
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2629
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2630
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2631
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2640
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2641
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2642
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2643
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2644
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2645
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2646
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2647
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2656
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2657
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2658
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2659
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2660
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2661
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2662
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2663
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2672
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2673
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2674
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2675
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2676
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2677
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2678
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2679
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2688
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2689
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2690
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2691
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2692
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2693
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2694
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2695
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2704
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2705
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2706
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2707
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2708
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2709
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2710
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2711
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2720
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2721
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2722
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2723
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2724
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2725
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2726
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2727
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2736
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2737
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2738
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2739
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2740
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2741
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2742
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2743
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2752
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2753
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2754
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2755
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2756
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2757
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2758
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2759
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2768
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2769
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2770
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2771
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2772
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2773
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2774
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2775
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2784
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2785
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2786
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2787
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2788
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2789
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2790
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2791
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2800
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2801
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2802
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2803
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2804
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2805
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2806
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 2807
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3072
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3073
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3074
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3075
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3076
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3077
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3078
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3079
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3080
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3081
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3082
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3083
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3084
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3085
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3086
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3087
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3088
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3089
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3090
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3091
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3092
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3093
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3094
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3095
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3096
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3097
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3098
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3099
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3100
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3101
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3102
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 3103
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 32
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 33
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 34
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 35
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 36
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 37
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 38
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 39
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 40
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 41
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 42
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 43
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 44
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 45
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 46
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 47
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 48
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 49
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 50
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 51
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 52
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 53
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 54
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 55
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 56
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 57
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 58
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 59
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 60
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 61
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 72
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 73
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 74
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 75
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 76
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 77
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 78
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 79
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 88
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 89
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 90
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 91
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 92
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 93
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 94
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 95
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 1096
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 1097
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 1098
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 1099
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 1100
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 1101
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 1102
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 1103
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 1112
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 1113
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 1114
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 1115
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 1116
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 1117
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 1118
; GFX90A-V2A-DIS-NEXT:    .cfi_undefined 1119
; GFX90A-V2A-DIS-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX90A-V2A-DIS-NEXT:    s_mov_b32 s16, s33
; GFX90A-V2A-DIS-NEXT:    s_mov_b32 s33, s32
; GFX90A-V2A-DIS-NEXT:    s_or_saveexec_b64 s[18:19], -1
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v40, off, s[0:3], s33 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    .cfi_offset 2600, 0
; GFX90A-V2A-DIS-NEXT:    s_mov_b64 exec, s[18:19]
; GFX90A-V2A-DIS-NEXT:    v_writelane_b32 v40, s16, 2
; GFX90A-V2A-DIS-NEXT:    .cfi_llvm_vector_registers 65, 2600, 2, 32
; GFX90A-V2A-DIS-NEXT:    .cfi_def_cfa_register 65
; GFX90A-V2A-DIS-NEXT:    s_addk_i32 s32, 0x400
; GFX90A-V2A-DIS-NEXT:    v_writelane_b32 v40, s30, 0
; GFX90A-V2A-DIS-NEXT:    s_getpc_b64 s[16:17]
; GFX90A-V2A-DIS-NEXT:    s_add_u32 s16, s16, ex@rel32@lo+4
; GFX90A-V2A-DIS-NEXT:    s_addc_u32 s17, s17, ex@rel32@hi+12
; GFX90A-V2A-DIS-NEXT:    v_writelane_b32 v40, s31, 1
; GFX90A-V2A-DIS-NEXT:    s_swappc_b64 s[30:31], s[16:17]
; GFX90A-V2A-DIS-NEXT:    v_readlane_b32 s30, v40, 0
; GFX90A-V2A-DIS-NEXT:    v_readlane_b32 s31, v40, 1
; GFX90A-V2A-DIS-NEXT:    s_mov_b32 s32, s33
; GFX90A-V2A-DIS-NEXT:    v_readlane_b32 s4, v40, 2
; GFX90A-V2A-DIS-NEXT:    s_or_saveexec_b64 s[6:7], -1
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v40, off, s[0:3], s33 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    s_mov_b64 exec, s[6:7]
; GFX90A-V2A-DIS-NEXT:    .cfi_def_cfa_register 64
; GFX90A-V2A-DIS-NEXT:    s_mov_b32 s33, s4
; GFX90A-V2A-DIS-NEXT:    s_waitcnt vmcnt(0)
; GFX90A-V2A-DIS-NEXT:    s_setpc_b64 s[30:31]
;
; GFX90A-V2A-EN-LABEL: func_call_clobber:
; GFX90A-V2A-EN:       .Lfunc_begin3:
; GFX90A-V2A-EN-NEXT:    .cfi_startproc
; GFX90A-V2A-EN-NEXT:  ; %bb.0: ; %entry
; GFX90A-V2A-EN-NEXT:    .cfi_llvm_def_aspace_cfa 64, 0, 6
; GFX90A-V2A-EN-NEXT:    .cfi_llvm_register_pair 16, 62, 32, 63, 32
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2560
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2561
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2562
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2563
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2564
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2565
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2566
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2567
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2568
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2569
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2570
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2571
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2572
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2573
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2574
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2575
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2576
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2577
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2578
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2579
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2580
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2581
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2582
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2583
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2584
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2585
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2586
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2587
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2588
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2589
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2590
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2591
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2592
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2593
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2594
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2595
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2596
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2597
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2598
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2599
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2608
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2609
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2610
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2611
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2612
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2613
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2614
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2615
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2624
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2625
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2626
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2627
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2628
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2629
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2630
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2631
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2640
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2641
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2642
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2643
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2644
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2645
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2646
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2647
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2656
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2657
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2658
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2659
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2660
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2661
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2662
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2663
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2672
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2673
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2674
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2675
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2676
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2677
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2678
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2679
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2688
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2689
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2690
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2691
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2692
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2693
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2694
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2695
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2704
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2705
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2706
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2707
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2708
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2709
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2710
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2711
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2720
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2721
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2722
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2723
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2724
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2725
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2726
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2727
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2736
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2737
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2738
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2739
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2740
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2741
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2742
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2743
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2752
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2753
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2754
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2755
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2756
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2757
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2758
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2759
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2768
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2769
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2770
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2771
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2772
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2773
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2774
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2775
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2784
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2785
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2786
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2787
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2788
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2789
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2790
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2791
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2800
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2801
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2802
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2803
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2804
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2805
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2806
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2807
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3072
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3073
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3074
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3075
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3076
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3077
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3078
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3079
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3080
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3081
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3082
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3083
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3084
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3085
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3086
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3087
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3088
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3089
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3090
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3091
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3092
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3093
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3094
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3095
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3096
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3097
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3098
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3099
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3100
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3101
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3102
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3103
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 32
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 33
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 34
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 35
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 36
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 37
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 38
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 39
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 40
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 41
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 42
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 43
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 44
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 45
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 46
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 47
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 48
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 49
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 50
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 51
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 52
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 53
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 54
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 55
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 56
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 57
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 58
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 59
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 60
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 61
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 72
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 73
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 74
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 75
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 76
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 77
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 78
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 79
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 88
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 89
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 90
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 91
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 92
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 93
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 94
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 95
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 1096
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 1097
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 1098
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 1099
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 1100
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 1101
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 1102
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 1103
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 1112
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 1113
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 1114
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 1115
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 1116
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 1117
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 1118
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 1119
; GFX90A-V2A-EN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX90A-V2A-EN-NEXT:    s_mov_b32 s16, s33
; GFX90A-V2A-EN-NEXT:    s_mov_b32 s33, s32
; GFX90A-V2A-EN-NEXT:    s_or_saveexec_b64 s[18:19], -1
; GFX90A-V2A-EN-NEXT:    buffer_store_dword v40, off, s[0:3], s33 ; 4-byte Folded Spill
; GFX90A-V2A-EN-NEXT:    .cfi_offset 2600, 0
; GFX90A-V2A-EN-NEXT:    s_mov_b64 exec, s[18:19]
; GFX90A-V2A-EN-NEXT:    v_writelane_b32 v40, s16, 2
; GFX90A-V2A-EN-NEXT:    .cfi_llvm_vector_registers 65, 2600, 2, 32
; GFX90A-V2A-EN-NEXT:    .cfi_def_cfa_register 65
; GFX90A-V2A-EN-NEXT:    s_addk_i32 s32, 0x400
; GFX90A-V2A-EN-NEXT:    v_writelane_b32 v40, s30, 0
; GFX90A-V2A-EN-NEXT:    s_getpc_b64 s[16:17]
; GFX90A-V2A-EN-NEXT:    s_add_u32 s16, s16, ex@rel32@lo+4
; GFX90A-V2A-EN-NEXT:    s_addc_u32 s17, s17, ex@rel32@hi+12
; GFX90A-V2A-EN-NEXT:    v_writelane_b32 v40, s31, 1
; GFX90A-V2A-EN-NEXT:    s_swappc_b64 s[30:31], s[16:17]
; GFX90A-V2A-EN-NEXT:    v_readlane_b32 s30, v40, 0
; GFX90A-V2A-EN-NEXT:    v_readlane_b32 s31, v40, 1
; GFX90A-V2A-EN-NEXT:    s_mov_b32 s32, s33
; GFX90A-V2A-EN-NEXT:    v_readlane_b32 s4, v40, 2
; GFX90A-V2A-EN-NEXT:    s_or_saveexec_b64 s[6:7], -1
; GFX90A-V2A-EN-NEXT:    buffer_load_dword v40, off, s[0:3], s33 ; 4-byte Folded Reload
; GFX90A-V2A-EN-NEXT:    s_mov_b64 exec, s[6:7]
; GFX90A-V2A-EN-NEXT:    .cfi_def_cfa_register 64
; GFX90A-V2A-EN-NEXT:    s_mov_b32 s33, s4
; GFX90A-V2A-EN-NEXT:    s_waitcnt vmcnt(0)
; GFX90A-V2A-EN-NEXT:    s_setpc_b64 s[30:31]
;
; WAVE32-LABEL: func_call_clobber:
; WAVE32:       .Lfunc_begin3:
; WAVE32-NEXT:    .cfi_startproc
; WAVE32-NEXT:  ; %bb.0: ; %entry
; WAVE32-NEXT:    .cfi_llvm_def_aspace_cfa 64, 0, 6
; WAVE32-NEXT:    .cfi_llvm_register_pair 16, 62, 32, 63, 32
; WAVE32-NEXT:    .cfi_undefined 1536
; WAVE32-NEXT:    .cfi_undefined 1537
; WAVE32-NEXT:    .cfi_undefined 1538
; WAVE32-NEXT:    .cfi_undefined 1539
; WAVE32-NEXT:    .cfi_undefined 1540
; WAVE32-NEXT:    .cfi_undefined 1541
; WAVE32-NEXT:    .cfi_undefined 1542
; WAVE32-NEXT:    .cfi_undefined 1543
; WAVE32-NEXT:    .cfi_undefined 1544
; WAVE32-NEXT:    .cfi_undefined 1545
; WAVE32-NEXT:    .cfi_undefined 1546
; WAVE32-NEXT:    .cfi_undefined 1547
; WAVE32-NEXT:    .cfi_undefined 1548
; WAVE32-NEXT:    .cfi_undefined 1549
; WAVE32-NEXT:    .cfi_undefined 1550
; WAVE32-NEXT:    .cfi_undefined 1551
; WAVE32-NEXT:    .cfi_undefined 1552
; WAVE32-NEXT:    .cfi_undefined 1553
; WAVE32-NEXT:    .cfi_undefined 1554
; WAVE32-NEXT:    .cfi_undefined 1555
; WAVE32-NEXT:    .cfi_undefined 1556
; WAVE32-NEXT:    .cfi_undefined 1557
; WAVE32-NEXT:    .cfi_undefined 1558
; WAVE32-NEXT:    .cfi_undefined 1559
; WAVE32-NEXT:    .cfi_undefined 1560
; WAVE32-NEXT:    .cfi_undefined 1561
; WAVE32-NEXT:    .cfi_undefined 1562
; WAVE32-NEXT:    .cfi_undefined 1563
; WAVE32-NEXT:    .cfi_undefined 1564
; WAVE32-NEXT:    .cfi_undefined 1565
; WAVE32-NEXT:    .cfi_undefined 1566
; WAVE32-NEXT:    .cfi_undefined 1567
; WAVE32-NEXT:    .cfi_undefined 1568
; WAVE32-NEXT:    .cfi_undefined 1569
; WAVE32-NEXT:    .cfi_undefined 1570
; WAVE32-NEXT:    .cfi_undefined 1571
; WAVE32-NEXT:    .cfi_undefined 1572
; WAVE32-NEXT:    .cfi_undefined 1573
; WAVE32-NEXT:    .cfi_undefined 1574
; WAVE32-NEXT:    .cfi_undefined 1575
; WAVE32-NEXT:    .cfi_undefined 1584
; WAVE32-NEXT:    .cfi_undefined 1585
; WAVE32-NEXT:    .cfi_undefined 1586
; WAVE32-NEXT:    .cfi_undefined 1587
; WAVE32-NEXT:    .cfi_undefined 1588
; WAVE32-NEXT:    .cfi_undefined 1589
; WAVE32-NEXT:    .cfi_undefined 1590
; WAVE32-NEXT:    .cfi_undefined 1591
; WAVE32-NEXT:    .cfi_undefined 1600
; WAVE32-NEXT:    .cfi_undefined 1601
; WAVE32-NEXT:    .cfi_undefined 1602
; WAVE32-NEXT:    .cfi_undefined 1603
; WAVE32-NEXT:    .cfi_undefined 1604
; WAVE32-NEXT:    .cfi_undefined 1605
; WAVE32-NEXT:    .cfi_undefined 1606
; WAVE32-NEXT:    .cfi_undefined 1607
; WAVE32-NEXT:    .cfi_undefined 1616
; WAVE32-NEXT:    .cfi_undefined 1617
; WAVE32-NEXT:    .cfi_undefined 1618
; WAVE32-NEXT:    .cfi_undefined 1619
; WAVE32-NEXT:    .cfi_undefined 1620
; WAVE32-NEXT:    .cfi_undefined 1621
; WAVE32-NEXT:    .cfi_undefined 1622
; WAVE32-NEXT:    .cfi_undefined 1623
; WAVE32-NEXT:    .cfi_undefined 1632
; WAVE32-NEXT:    .cfi_undefined 1633
; WAVE32-NEXT:    .cfi_undefined 1634
; WAVE32-NEXT:    .cfi_undefined 1635
; WAVE32-NEXT:    .cfi_undefined 1636
; WAVE32-NEXT:    .cfi_undefined 1637
; WAVE32-NEXT:    .cfi_undefined 1638
; WAVE32-NEXT:    .cfi_undefined 1639
; WAVE32-NEXT:    .cfi_undefined 1648
; WAVE32-NEXT:    .cfi_undefined 1649
; WAVE32-NEXT:    .cfi_undefined 1650
; WAVE32-NEXT:    .cfi_undefined 1651
; WAVE32-NEXT:    .cfi_undefined 1652
; WAVE32-NEXT:    .cfi_undefined 1653
; WAVE32-NEXT:    .cfi_undefined 1654
; WAVE32-NEXT:    .cfi_undefined 1655
; WAVE32-NEXT:    .cfi_undefined 1664
; WAVE32-NEXT:    .cfi_undefined 1665
; WAVE32-NEXT:    .cfi_undefined 1666
; WAVE32-NEXT:    .cfi_undefined 1667
; WAVE32-NEXT:    .cfi_undefined 1668
; WAVE32-NEXT:    .cfi_undefined 1669
; WAVE32-NEXT:    .cfi_undefined 1670
; WAVE32-NEXT:    .cfi_undefined 1671
; WAVE32-NEXT:    .cfi_undefined 1680
; WAVE32-NEXT:    .cfi_undefined 1681
; WAVE32-NEXT:    .cfi_undefined 1682
; WAVE32-NEXT:    .cfi_undefined 1683
; WAVE32-NEXT:    .cfi_undefined 1684
; WAVE32-NEXT:    .cfi_undefined 1685
; WAVE32-NEXT:    .cfi_undefined 1686
; WAVE32-NEXT:    .cfi_undefined 1687
; WAVE32-NEXT:    .cfi_undefined 1696
; WAVE32-NEXT:    .cfi_undefined 1697
; WAVE32-NEXT:    .cfi_undefined 1698
; WAVE32-NEXT:    .cfi_undefined 1699
; WAVE32-NEXT:    .cfi_undefined 1700
; WAVE32-NEXT:    .cfi_undefined 1701
; WAVE32-NEXT:    .cfi_undefined 1702
; WAVE32-NEXT:    .cfi_undefined 1703
; WAVE32-NEXT:    .cfi_undefined 1712
; WAVE32-NEXT:    .cfi_undefined 1713
; WAVE32-NEXT:    .cfi_undefined 1714
; WAVE32-NEXT:    .cfi_undefined 1715
; WAVE32-NEXT:    .cfi_undefined 1716
; WAVE32-NEXT:    .cfi_undefined 1717
; WAVE32-NEXT:    .cfi_undefined 1718
; WAVE32-NEXT:    .cfi_undefined 1719
; WAVE32-NEXT:    .cfi_undefined 1728
; WAVE32-NEXT:    .cfi_undefined 1729
; WAVE32-NEXT:    .cfi_undefined 1730
; WAVE32-NEXT:    .cfi_undefined 1731
; WAVE32-NEXT:    .cfi_undefined 1732
; WAVE32-NEXT:    .cfi_undefined 1733
; WAVE32-NEXT:    .cfi_undefined 1734
; WAVE32-NEXT:    .cfi_undefined 1735
; WAVE32-NEXT:    .cfi_undefined 1744
; WAVE32-NEXT:    .cfi_undefined 1745
; WAVE32-NEXT:    .cfi_undefined 1746
; WAVE32-NEXT:    .cfi_undefined 1747
; WAVE32-NEXT:    .cfi_undefined 1748
; WAVE32-NEXT:    .cfi_undefined 1749
; WAVE32-NEXT:    .cfi_undefined 1750
; WAVE32-NEXT:    .cfi_undefined 1751
; WAVE32-NEXT:    .cfi_undefined 1760
; WAVE32-NEXT:    .cfi_undefined 1761
; WAVE32-NEXT:    .cfi_undefined 1762
; WAVE32-NEXT:    .cfi_undefined 1763
; WAVE32-NEXT:    .cfi_undefined 1764
; WAVE32-NEXT:    .cfi_undefined 1765
; WAVE32-NEXT:    .cfi_undefined 1766
; WAVE32-NEXT:    .cfi_undefined 1767
; WAVE32-NEXT:    .cfi_undefined 1776
; WAVE32-NEXT:    .cfi_undefined 1777
; WAVE32-NEXT:    .cfi_undefined 1778
; WAVE32-NEXT:    .cfi_undefined 1779
; WAVE32-NEXT:    .cfi_undefined 1780
; WAVE32-NEXT:    .cfi_undefined 1781
; WAVE32-NEXT:    .cfi_undefined 1782
; WAVE32-NEXT:    .cfi_undefined 1783
; WAVE32-NEXT:    .cfi_undefined 32
; WAVE32-NEXT:    .cfi_undefined 33
; WAVE32-NEXT:    .cfi_undefined 34
; WAVE32-NEXT:    .cfi_undefined 35
; WAVE32-NEXT:    .cfi_undefined 36
; WAVE32-NEXT:    .cfi_undefined 37
; WAVE32-NEXT:    .cfi_undefined 38
; WAVE32-NEXT:    .cfi_undefined 39
; WAVE32-NEXT:    .cfi_undefined 40
; WAVE32-NEXT:    .cfi_undefined 41
; WAVE32-NEXT:    .cfi_undefined 42
; WAVE32-NEXT:    .cfi_undefined 43
; WAVE32-NEXT:    .cfi_undefined 44
; WAVE32-NEXT:    .cfi_undefined 45
; WAVE32-NEXT:    .cfi_undefined 46
; WAVE32-NEXT:    .cfi_undefined 47
; WAVE32-NEXT:    .cfi_undefined 48
; WAVE32-NEXT:    .cfi_undefined 49
; WAVE32-NEXT:    .cfi_undefined 50
; WAVE32-NEXT:    .cfi_undefined 51
; WAVE32-NEXT:    .cfi_undefined 52
; WAVE32-NEXT:    .cfi_undefined 53
; WAVE32-NEXT:    .cfi_undefined 54
; WAVE32-NEXT:    .cfi_undefined 55
; WAVE32-NEXT:    .cfi_undefined 56
; WAVE32-NEXT:    .cfi_undefined 57
; WAVE32-NEXT:    .cfi_undefined 58
; WAVE32-NEXT:    .cfi_undefined 59
; WAVE32-NEXT:    .cfi_undefined 60
; WAVE32-NEXT:    .cfi_undefined 61
; WAVE32-NEXT:    .cfi_undefined 72
; WAVE32-NEXT:    .cfi_undefined 73
; WAVE32-NEXT:    .cfi_undefined 74
; WAVE32-NEXT:    .cfi_undefined 75
; WAVE32-NEXT:    .cfi_undefined 76
; WAVE32-NEXT:    .cfi_undefined 77
; WAVE32-NEXT:    .cfi_undefined 78
; WAVE32-NEXT:    .cfi_undefined 79
; WAVE32-NEXT:    .cfi_undefined 88
; WAVE32-NEXT:    .cfi_undefined 89
; WAVE32-NEXT:    .cfi_undefined 90
; WAVE32-NEXT:    .cfi_undefined 91
; WAVE32-NEXT:    .cfi_undefined 92
; WAVE32-NEXT:    .cfi_undefined 93
; WAVE32-NEXT:    .cfi_undefined 94
; WAVE32-NEXT:    .cfi_undefined 95
; WAVE32-NEXT:    .cfi_undefined 1096
; WAVE32-NEXT:    .cfi_undefined 1097
; WAVE32-NEXT:    .cfi_undefined 1098
; WAVE32-NEXT:    .cfi_undefined 1099
; WAVE32-NEXT:    .cfi_undefined 1100
; WAVE32-NEXT:    .cfi_undefined 1101
; WAVE32-NEXT:    .cfi_undefined 1102
; WAVE32-NEXT:    .cfi_undefined 1103
; WAVE32-NEXT:    .cfi_undefined 1112
; WAVE32-NEXT:    .cfi_undefined 1113
; WAVE32-NEXT:    .cfi_undefined 1114
; WAVE32-NEXT:    .cfi_undefined 1115
; WAVE32-NEXT:    .cfi_undefined 1116
; WAVE32-NEXT:    .cfi_undefined 1117
; WAVE32-NEXT:    .cfi_undefined 1118
; WAVE32-NEXT:    .cfi_undefined 1119
; WAVE32-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; WAVE32-NEXT:    s_mov_b32 s16, s33
; WAVE32-NEXT:    s_mov_b32 s33, s32
; WAVE32-NEXT:    s_or_saveexec_b32 s17, -1
; WAVE32-NEXT:    buffer_store_dword v40, off, s[0:3], s33 ; 4-byte Folded Spill
; WAVE32-NEXT:    .cfi_offset 1576, 0
; WAVE32-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; WAVE32-NEXT:    s_mov_b32 exec_lo, s17
; WAVE32-NEXT:    v_writelane_b32 v40, s16, 2
; WAVE32-NEXT:    .cfi_llvm_vector_registers 65, 1576, 2, 32
; WAVE32-NEXT:    .cfi_def_cfa_register 65
; WAVE32-NEXT:    v_writelane_b32 v40, s30, 0
; WAVE32-NEXT:    s_addk_i32 s32, 0x200
; WAVE32-NEXT:    s_getpc_b64 s[16:17]
; WAVE32-NEXT:    s_add_u32 s16, s16, ex@rel32@lo+4
; WAVE32-NEXT:    s_addc_u32 s17, s17, ex@rel32@hi+12
; WAVE32-NEXT:    v_writelane_b32 v40, s31, 1
; WAVE32-NEXT:    s_swappc_b64 s[30:31], s[16:17]
; WAVE32-NEXT:    v_readlane_b32 s30, v40, 0
; WAVE32-NEXT:    v_readlane_b32 s31, v40, 1
; WAVE32-NEXT:    s_mov_b32 s32, s33
; WAVE32-NEXT:    v_readlane_b32 s4, v40, 2
; WAVE32-NEXT:    s_or_saveexec_b32 s5, -1
; WAVE32-NEXT:    buffer_load_dword v40, off, s[0:3], s33 ; 4-byte Folded Reload
; WAVE32-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; WAVE32-NEXT:    s_mov_b32 exec_lo, s5
; WAVE32-NEXT:    .cfi_def_cfa_register 64
; WAVE32-NEXT:    s_mov_b32 s33, s4
; WAVE32-NEXT:    s_waitcnt vmcnt(0)
; WAVE32-NEXT:    s_setpc_b64 s[30:31]
entry:
  call void @ex() #0
  ret void
}

define hidden void @func_spill_vgpr_to_vmem() #0 {
; GFX900-LABEL: func_spill_vgpr_to_vmem:
; GFX900:       .Lfunc_begin4:
; GFX900-NEXT:    .cfi_startproc
; GFX900-NEXT:  ; %bb.0: ; %entry
; GFX900-NEXT:    .cfi_llvm_def_aspace_cfa 64, 0, 6
; GFX900-NEXT:    .cfi_llvm_register_pair 16, 62, 32, 63, 32
; GFX900-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX900-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v41, off, s[0:3], s32 ; 4-byte Folded Spill
; GFX900-NEXT:    ;;#ASMSTART
; GFX900-NEXT:    ; clobber
; GFX900-NEXT:    ;;#ASMEND
; GFX900-NEXT:    ;;#ASMSTART
; GFX900-NEXT:    ; clobber
; GFX900-NEXT:    ;;#ASMEND
; GFX900-NEXT:    ;;#ASMSTART
; GFX900-NEXT:    ; clobber
; GFX900-NEXT:    ;;#ASMEND
; GFX900-NEXT:    ;;#ASMSTART
; GFX900-NEXT:    ; clobber
; GFX900-NEXT:    ;;#ASMEND
; GFX900-NEXT:    buffer_load_dword v41, off, s[0:3], s32 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; GFX900-NEXT:    s_waitcnt vmcnt(0)
; GFX900-NEXT:    s_setpc_b64 s[30:31]
;
; GFX90A-V2A-DIS-LABEL: func_spill_vgpr_to_vmem:
; GFX90A-V2A-DIS:       .Lfunc_begin4:
; GFX90A-V2A-DIS-NEXT:    .cfi_startproc
; GFX90A-V2A-DIS-NEXT:  ; %bb.0: ; %entry
; GFX90A-V2A-DIS-NEXT:    .cfi_llvm_def_aspace_cfa 64, 0, 6
; GFX90A-V2A-DIS-NEXT:    .cfi_llvm_register_pair 16, 62, 32, 63, 32
; GFX90A-V2A-DIS-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword a32, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword a33, off, s[0:3], s32 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    ;;#ASMSTART
; GFX90A-V2A-DIS-NEXT:    ; clobber
; GFX90A-V2A-DIS-NEXT:    ;;#ASMEND
; GFX90A-V2A-DIS-NEXT:    ;;#ASMSTART
; GFX90A-V2A-DIS-NEXT:    ; clobber
; GFX90A-V2A-DIS-NEXT:    ;;#ASMEND
; GFX90A-V2A-DIS-NEXT:    ;;#ASMSTART
; GFX90A-V2A-DIS-NEXT:    ; clobber
; GFX90A-V2A-DIS-NEXT:    ;;#ASMEND
; GFX90A-V2A-DIS-NEXT:    ;;#ASMSTART
; GFX90A-V2A-DIS-NEXT:    ; clobber
; GFX90A-V2A-DIS-NEXT:    ;;#ASMEND
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword a33, off, s[0:3], s32 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword a32, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    s_waitcnt vmcnt(0)
; GFX90A-V2A-DIS-NEXT:    s_setpc_b64 s[30:31]
;
; GFX90A-V2A-EN-LABEL: func_spill_vgpr_to_vmem:
; GFX90A-V2A-EN:       .Lfunc_begin4:
; GFX90A-V2A-EN-NEXT:    .cfi_startproc
; GFX90A-V2A-EN-NEXT:  ; %bb.0: ; %entry
; GFX90A-V2A-EN-NEXT:    .cfi_llvm_def_aspace_cfa 64, 0, 6
; GFX90A-V2A-EN-NEXT:    .cfi_llvm_register_pair 16, 62, 32, 63, 32
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2560
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2561
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3072
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3073
; GFX90A-V2A-EN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a0, v40 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a1, v41 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v0, a32 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v1, a33 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    ;;#ASMSTART
; GFX90A-V2A-EN-NEXT:    ; clobber
; GFX90A-V2A-EN-NEXT:    ;;#ASMEND
; GFX90A-V2A-EN-NEXT:    ;;#ASMSTART
; GFX90A-V2A-EN-NEXT:    ; clobber
; GFX90A-V2A-EN-NEXT:    ;;#ASMEND
; GFX90A-V2A-EN-NEXT:    ;;#ASMSTART
; GFX90A-V2A-EN-NEXT:    ; clobber
; GFX90A-V2A-EN-NEXT:    ;;#ASMEND
; GFX90A-V2A-EN-NEXT:    ;;#ASMSTART
; GFX90A-V2A-EN-NEXT:    ; clobber
; GFX90A-V2A-EN-NEXT:    ;;#ASMEND
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a33, v1 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a32, v0 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v41, a1 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v40, a0 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    s_setpc_b64 s[30:31]
;
; WAVE32-LABEL: func_spill_vgpr_to_vmem:
; WAVE32:       .Lfunc_begin4:
; WAVE32-NEXT:    .cfi_startproc
; WAVE32-NEXT:  ; %bb.0: ; %entry
; WAVE32-NEXT:    .cfi_llvm_def_aspace_cfa 64, 0, 6
; WAVE32-NEXT:    .cfi_llvm_register_pair 16, 62, 32, 63, 32
; WAVE32-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; WAVE32-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v41, off, s[0:3], s32 ; 4-byte Folded Spill
; WAVE32-NEXT:    ;;#ASMSTART
; WAVE32-NEXT:    ; clobber
; WAVE32-NEXT:    ;;#ASMEND
; WAVE32-NEXT:    ;;#ASMSTART
; WAVE32-NEXT:    ; clobber
; WAVE32-NEXT:    ;;#ASMEND
; WAVE32-NEXT:    ;;#ASMSTART
; WAVE32-NEXT:    ; clobber
; WAVE32-NEXT:    ;;#ASMEND
; WAVE32-NEXT:    ;;#ASMSTART
; WAVE32-NEXT:    ; clobber
; WAVE32-NEXT:    ;;#ASMEND
; WAVE32-NEXT:    s_clause 0x1 ; 8-byte Folded Reload
; WAVE32-NEXT:    buffer_load_dword v41, off, s[0:3], s32
; WAVE32-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:4
; WAVE32-NEXT:    s_waitcnt vmcnt(0)
; WAVE32-NEXT:    s_setpc_b64 s[30:31]
entry:
  call void asm sideeffect "; clobber", "~{v40}"() #0
  call void asm sideeffect "; clobber", "~{v41}"() #0
  call void asm sideeffect "; clobber", "~{a32}"() #0
  call void asm sideeffect "; clobber", "~{a33}"() #0
  ret void
}

define hidden void @func_spill_vgpr_to_agpr() #2 {
; GFX900-LABEL: func_spill_vgpr_to_agpr:
; GFX900:       .Lfunc_begin5:
; GFX900-NEXT:    .cfi_startproc
; GFX900-NEXT:  ; %bb.0:
; GFX900-NEXT:    .cfi_llvm_def_aspace_cfa 64, 0, 6
; GFX900-NEXT:    .cfi_llvm_register_pair 16, 62, 32, 63, 32
; GFX900-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX900-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; GFX900-NEXT:    buffer_store_dword v41, off, s[0:3], s32 ; 4-byte Folded Spill
; GFX900-NEXT:    ;;#ASMSTART
; GFX900-NEXT:    ; clobber
; GFX900-NEXT:    ;;#ASMEND
; GFX900-NEXT:    ;;#ASMSTART
; GFX900-NEXT:    ; clobber
; GFX900-NEXT:    ;;#ASMEND
; GFX900-NEXT:    ;;#ASMSTART
; GFX900-NEXT:    ; clobber
; GFX900-NEXT:    ;;#ASMEND
; GFX900-NEXT:    ;;#ASMSTART
; GFX900-NEXT:    ; clobber
; GFX900-NEXT:    ;;#ASMEND
; GFX900-NEXT:    buffer_load_dword v41, off, s[0:3], s32 ; 4-byte Folded Reload
; GFX900-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; GFX900-NEXT:    s_waitcnt vmcnt(0)
; GFX900-NEXT:    s_setpc_b64 s[30:31]
;
; GFX90A-V2A-DIS-LABEL: func_spill_vgpr_to_agpr:
; GFX90A-V2A-DIS:       .Lfunc_begin5:
; GFX90A-V2A-DIS-NEXT:    .cfi_startproc
; GFX90A-V2A-DIS-NEXT:  ; %bb.0:
; GFX90A-V2A-DIS-NEXT:    .cfi_llvm_def_aspace_cfa 64, 0, 6
; GFX90A-V2A-DIS-NEXT:    .cfi_llvm_register_pair 16, 62, 32, 63, 32
; GFX90A-V2A-DIS-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:12 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword v41, off, s[0:3], s32 offset:8 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword a32, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    buffer_store_dword a33, off, s[0:3], s32 ; 4-byte Folded Spill
; GFX90A-V2A-DIS-NEXT:    ;;#ASMSTART
; GFX90A-V2A-DIS-NEXT:    ; clobber
; GFX90A-V2A-DIS-NEXT:    ;;#ASMEND
; GFX90A-V2A-DIS-NEXT:    ;;#ASMSTART
; GFX90A-V2A-DIS-NEXT:    ; clobber
; GFX90A-V2A-DIS-NEXT:    ;;#ASMEND
; GFX90A-V2A-DIS-NEXT:    ;;#ASMSTART
; GFX90A-V2A-DIS-NEXT:    ; clobber
; GFX90A-V2A-DIS-NEXT:    ;;#ASMEND
; GFX90A-V2A-DIS-NEXT:    ;;#ASMSTART
; GFX90A-V2A-DIS-NEXT:    ; clobber
; GFX90A-V2A-DIS-NEXT:    ;;#ASMEND
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword a33, off, s[0:3], s32 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword a32, off, s[0:3], s32 offset:4 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v41, off, s[0:3], s32 offset:8 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:12 ; 4-byte Folded Reload
; GFX90A-V2A-DIS-NEXT:    s_waitcnt vmcnt(0)
; GFX90A-V2A-DIS-NEXT:    s_setpc_b64 s[30:31]
;
; GFX90A-V2A-EN-LABEL: func_spill_vgpr_to_agpr:
; GFX90A-V2A-EN:       .Lfunc_begin5:
; GFX90A-V2A-EN-NEXT:    .cfi_startproc
; GFX90A-V2A-EN-NEXT:  ; %bb.0:
; GFX90A-V2A-EN-NEXT:    .cfi_llvm_def_aspace_cfa 64, 0, 6
; GFX90A-V2A-EN-NEXT:    .cfi_llvm_register_pair 16, 62, 32, 63, 32
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2560
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 2561
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3072
; GFX90A-V2A-EN-NEXT:    .cfi_undefined 3073
; GFX90A-V2A-EN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a0, v40 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a1, v41 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v0, a32 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v1, a33 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    ;;#ASMSTART
; GFX90A-V2A-EN-NEXT:    ; clobber
; GFX90A-V2A-EN-NEXT:    ;;#ASMEND
; GFX90A-V2A-EN-NEXT:    ;;#ASMSTART
; GFX90A-V2A-EN-NEXT:    ; clobber
; GFX90A-V2A-EN-NEXT:    ;;#ASMEND
; GFX90A-V2A-EN-NEXT:    ;;#ASMSTART
; GFX90A-V2A-EN-NEXT:    ; clobber
; GFX90A-V2A-EN-NEXT:    ;;#ASMEND
; GFX90A-V2A-EN-NEXT:    ;;#ASMSTART
; GFX90A-V2A-EN-NEXT:    ; clobber
; GFX90A-V2A-EN-NEXT:    ;;#ASMEND
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a33, v1 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_write_b32 a32, v0 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v41, a1 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    v_accvgpr_read_b32 v40, a0 ; Reload Reuse
; GFX90A-V2A-EN-NEXT:    s_setpc_b64 s[30:31]
;
; WAVE32-LABEL: func_spill_vgpr_to_agpr:
; WAVE32:       .Lfunc_begin5:
; WAVE32-NEXT:    .cfi_startproc
; WAVE32-NEXT:  ; %bb.0:
; WAVE32-NEXT:    .cfi_llvm_def_aspace_cfa 64, 0, 6
; WAVE32-NEXT:    .cfi_llvm_register_pair 16, 62, 32, 63, 32
; WAVE32-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; WAVE32-NEXT:    buffer_store_dword v40, off, s[0:3], s32 offset:4 ; 4-byte Folded Spill
; WAVE32-NEXT:    buffer_store_dword v41, off, s[0:3], s32 ; 4-byte Folded Spill
; WAVE32-NEXT:    ;;#ASMSTART
; WAVE32-NEXT:    ; clobber
; WAVE32-NEXT:    ;;#ASMEND
; WAVE32-NEXT:    ;;#ASMSTART
; WAVE32-NEXT:    ; clobber
; WAVE32-NEXT:    ;;#ASMEND
; WAVE32-NEXT:    ;;#ASMSTART
; WAVE32-NEXT:    ; clobber
; WAVE32-NEXT:    ;;#ASMEND
; WAVE32-NEXT:    ;;#ASMSTART
; WAVE32-NEXT:    ; clobber
; WAVE32-NEXT:    ;;#ASMEND
; WAVE32-NEXT:    s_clause 0x1 ; 8-byte Folded Reload
; WAVE32-NEXT:    buffer_load_dword v41, off, s[0:3], s32
; WAVE32-NEXT:    buffer_load_dword v40, off, s[0:3], s32 offset:4
; WAVE32-NEXT:    s_waitcnt vmcnt(0)
; WAVE32-NEXT:    s_setpc_b64 s[30:31]
  call void asm sideeffect "; clobber", "~{v40}"()
  call void asm sideeffect "; clobber", "~{v41}"()
  call void asm sideeffect "; clobber", "~{a32}"()
  call void asm sideeffect "; clobber", "~{a33}"()
  ret void
}


; NOTE: Number of VGPRs available to kernel, and in turn number of corresponding CFIs generated,
; is dependent on waves/WG size. Since the intent here is to check whether we generate the correct
; CFIs, doing it for any one set of details is sufficient which also makes the test insensitive to
; changes in those details.
attributes #0 = { nounwind "amdgpu-waves-per-eu"="1,1" "amdgpu-flat-work-group-size"="128,128" }
attributes #1 = { nounwind "amdgpu-waves-per-eu"="1,1" "amdgpu-flat-work-group-size"="128,128" "frame-pointer"="all" }
attributes #2 = { nounwind }

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!2, !3}

!0 = distinct !DICompileUnit(language: DW_LANG_C99, file: !1, emissionKind: FullDebug)
!1 = !DIFile(filename: "filename", directory: "directory")
!2 = !{i32 7, !"Dwarf Version", i32 4}
!3 = !{i32 2, !"Debug Info Version", i32 3}
