; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt < %s --amdgpu-internalize-symbols --passes='default<O2>' -mtriple=amdgcn-amd-amdhsa -S | FileCheck %s

; By running AMDGPUAttributor early, "amdgpu-uniform-work-group-size"="true" can be applied to non-kernel functions.
; Make sure following pattern of reading blockDim.y from implicitarg pointer is cleaned up.
; A load from implicitarg pointer, a compare and select to drive an offset, and a final load using that offset is
; simplified into one direct load with a constant offset.
;
;  %13 = tail call ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
;  %14 = getelementptr inbounds nuw i8, ptr addrspace(4) %13, i64 4
;  %15 = tail call i32 @llvm.amdgcn.workgroup.id.y()
;  %16 = load i32, ptr addrspace(4) %14, align 4
;  %17 = icmp ult i32 %15, %16
;  %18 = select i1 %17, i64 14, i64 20
;  %19 = getelementptr inbounds nuw i8, ptr addrspace(4) %13, i64 %18
;  %20 = load i16, ptr addrspace(4) %19, align 2
;
; -->
;
;  %13 = tail call ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
;  %14 = getelementptr inbounds nuw i8, ptr addrspace(4) %13, i64 14
;  %15 = load i16, ptr addrspace(4) %14, align 2
;
; If AMDGOUAttributor is not run early, after the non-kernel callee is transformed (e.g. unroll), the target pattern
; for optimization using "amdgpu-uniform-work-group-size"="true" disappears. After inlining into the kernel,
; although the kernel has "amdgpu-uniform-work-group-size"="true", but it is useless.

target datalayout = "m:e-e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-p7:160:256:256:32-p8:128:128:128:48-p9:192:256:256:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7:8:9"
target triple = "amdgcn-amd-amdhsa"

%class.anon = type { ptr, ptr, ptr }

$_Z11MassVec3DPAILm192EEvPKdS1_Pdi = comdat any

$_ZZ11MassVec3DPAILm192EEvPKdS1_PdiENKUliE_clEi = comdat any

$_ZN25__hip_builtin_threadIdx_t7__get_zEv = comdat any

$_ZN25__hip_builtin_threadIdx_t7__get_yEv = comdat any

$_ZN24__hip_builtin_blockDim_t7__get_yEv = comdat any

@__const.__assert_fail.fmt = hidden unnamed_addr addrspace(4) constant [47 x i8] c"%s:%u: %s: Device-side assertion `%s' failed.\0A\00", align 16
@__oclc_ISA_version = hidden local_unnamed_addr addrspace(4) constant i32 9402, align 4
@__oclc_ABI_version = weak_odr hidden local_unnamed_addr addrspace(4) constant i32 600

; Function Attrs: convergent mustprogress norecurse nounwind
define protected amdgpu_kernel void @_Z11MassVec3DPAILm192EEvPKdS1_Pdi(ptr addrspace(1) noundef %0, ptr addrspace(1) noundef %1, ptr addrspace(1) noundef %2, i32 noundef %3) #0 comdat {
; CHECK-LABEL: define protected amdgpu_kernel void @_Z11MassVec3DPAILm192EEvPKdS1_Pdi(
; CHECK-SAME: ptr addrspace(1) noundef readonly captures(none) [[TMP0:%.*]], ptr addrspace(1) noundef readonly captures(none) [[TMP1:%.*]], ptr addrspace(1) noundef writeonly captures(none) [[TMP2:%.*]], i32 noundef [[TMP3:%.*]]) local_unnamed_addr #[[ATTR0:[0-9]+]] comdat {
; CHECK-NEXT:    [[TMP5:%.*]] = tail call range(i32 0, 1024) i32 @llvm.amdgcn.workitem.id.y()
; CHECK-NEXT:    [[TMP6:%.*]] = icmp samesign ult i32 [[TMP5]], 4
; CHECK-NEXT:    br i1 [[TMP6]], label %[[DOTLR_PH_I:.*]], label %[[_ZZ11MASSVEC3DPAILM192EEVPKDS1_PDIENKULIE_CLEI_EXIT:.*]]
; CHECK:       [[_LR_PH_I:.*:]]
; CHECK-NEXT:    [[TMP7:%.*]] = tail call ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
; CHECK-NEXT:    [[TMP8:%.*]] = getelementptr inbounds nuw i8, ptr addrspace(4) [[TMP7]], i64 14
; CHECK-NEXT:    [[TMP9:%.*]] = load i16, ptr addrspace(4) [[TMP8]], align 2, !tbaa [[SHORT_TBAA1:![0-9]+]]
; CHECK-NEXT:    [[TMP10:%.*]] = zext i16 [[TMP9]] to i32
; CHECK-NEXT:    br label %[[BB21:.*]]
; CHECK:       [[__CRIT_EDGE_I:.*:]]
; CHECK-NEXT:    [[DOT0910_1_I:%.*]] = phi i32 [ [[TMP19:%.*]], %[[DOT_CRIT_EDGE_I:.*]] ], [ [[TMP5]], %[[BB21]] ]
; CHECK-NEXT:    [[TMP11:%.*]] = add nuw nsw i32 [[DOT0910_1_I]], 4
; CHECK-NEXT:    [[TMP12:%.*]] = zext nneg i32 [[TMP11]] to i64
; CHECK-NEXT:    [[TMP13:%.*]] = getelementptr inbounds nuw double, ptr addrspace(1) [[TMP0]], i64 [[TMP12]]
; CHECK-NEXT:    [[TMP14:%.*]] = load double, ptr addrspace(1) [[TMP13]], align 8, !tbaa [[DOUBLE_TBAA5:![0-9]+]]
; CHECK-NEXT:    [[TMP15:%.*]] = getelementptr inbounds nuw double, ptr addrspace(1) [[TMP1]], i64 [[TMP12]]
; CHECK-NEXT:    [[TMP16:%.*]] = load double, ptr addrspace(1) [[TMP15]], align 8, !tbaa [[DOUBLE_TBAA5]]
; CHECK-NEXT:    [[TMP17:%.*]] = fadd contract double [[TMP14]], [[TMP16]]
; CHECK-NEXT:    [[TMP18:%.*]] = getelementptr inbounds nuw double, ptr addrspace(1) [[TMP2]], i64 [[TMP12]]
; CHECK-NEXT:    store double [[TMP17]], ptr addrspace(1) [[TMP18]], align 8, !tbaa [[DOUBLE_TBAA5]]
; CHECK-NEXT:    [[TMP19]] = add nuw nsw i32 [[DOT0910_1_I]], [[TMP10]]
; CHECK-NEXT:    [[TMP20:%.*]] = icmp samesign ult i32 [[TMP19]], 4
; CHECK-NEXT:    br i1 [[TMP20]], label %[[DOT_CRIT_EDGE_I]], label %[[_ZZ11MASSVEC3DPAILM192EEVPKDS1_PDIENKULIE_CLEI_EXIT]], !llvm.loop [[LOOP9:![0-9]+]]
; CHECK:       [[BB21]]:
; CHECK-NEXT:    [[DOT0910_I:%.*]] = phi i32 [ [[TMP5]], %[[DOTLR_PH_I]] ], [ [[TMP29:%.*]], %[[BB21]] ]
; CHECK-NEXT:    [[TMP22:%.*]] = zext nneg i32 [[DOT0910_I]] to i64
; CHECK-NEXT:    [[TMP23:%.*]] = getelementptr inbounds nuw double, ptr addrspace(1) [[TMP0]], i64 [[TMP22]]
; CHECK-NEXT:    [[TMP24:%.*]] = load double, ptr addrspace(1) [[TMP23]], align 8, !tbaa [[DOUBLE_TBAA5]]
; CHECK-NEXT:    [[TMP25:%.*]] = getelementptr inbounds nuw double, ptr addrspace(1) [[TMP1]], i64 [[TMP22]]
; CHECK-NEXT:    [[TMP26:%.*]] = load double, ptr addrspace(1) [[TMP25]], align 8, !tbaa [[DOUBLE_TBAA5]]
; CHECK-NEXT:    [[TMP27:%.*]] = fadd contract double [[TMP24]], [[TMP26]]
; CHECK-NEXT:    [[TMP28:%.*]] = getelementptr inbounds nuw double, ptr addrspace(1) [[TMP2]], i64 [[TMP22]]
; CHECK-NEXT:    store double [[TMP27]], ptr addrspace(1) [[TMP28]], align 8, !tbaa [[DOUBLE_TBAA5]]
; CHECK-NEXT:    [[TMP29]] = add nuw nsw i32 [[DOT0910_I]], [[TMP10]]
; CHECK-NEXT:    [[TMP30:%.*]] = icmp samesign ult i32 [[TMP29]], 4
; CHECK-NEXT:    br i1 [[TMP30]], label %[[BB21]], label %[[DOT_CRIT_EDGE_I]], !llvm.loop [[LOOP9]]
; CHECK:       [[_ZZ11MASSVEC3DPAILM192EEVPKDS1_PDIENKULIE_CLEI_EXIT]]:
; CHECK-NEXT:    ret void
;
  %5 = alloca ptr, align 8, addrspace(5)
  %6 = alloca ptr, align 8, addrspace(5)
  %7 = alloca ptr, align 8, addrspace(5)
  %8 = alloca ptr, align 8, addrspace(5)
  %9 = alloca ptr, align 8, addrspace(5)
  %10 = alloca ptr, align 8, addrspace(5)
  %11 = alloca i32, align 4, addrspace(5)
  %12 = alloca %class.anon, align 8, addrspace(5)
  %13 = addrspacecast ptr addrspace(5) %5 to ptr
  %14 = addrspacecast ptr addrspace(5) %6 to ptr
  %15 = addrspacecast ptr addrspace(5) %7 to ptr
  %16 = addrspacecast ptr addrspace(5) %8 to ptr
  %17 = addrspacecast ptr addrspace(5) %9 to ptr
  %18 = addrspacecast ptr addrspace(5) %10 to ptr
  %19 = addrspacecast ptr addrspace(5) %11 to ptr
  %20 = addrspacecast ptr addrspace(5) %12 to ptr
  store ptr addrspace(1) %0, ptr %13, align 8
  %21 = load ptr, ptr %13, align 8, !tbaa !7
  store ptr addrspace(1) %1, ptr %14, align 8
  %22 = load ptr, ptr %14, align 8, !tbaa !7
  store ptr addrspace(1) %2, ptr %15, align 8
  %23 = load ptr, ptr %15, align 8, !tbaa !7
  store ptr %21, ptr %16, align 8, !tbaa !7
  store ptr %22, ptr %17, align 8, !tbaa !7
  store ptr %23, ptr %18, align 8, !tbaa !7
  store i32 %3, ptr %19, align 4, !tbaa !12
  call void @llvm.lifetime.start.p5(ptr addrspace(5) %12)
  %24 = getelementptr inbounds nuw %class.anon, ptr %20, i32 0, i32 0
  store ptr %18, ptr %24, align 8, !tbaa !14
  %25 = getelementptr inbounds nuw %class.anon, ptr %20, i32 0, i32 1
  store ptr %16, ptr %25, align 8, !tbaa !14
  %26 = getelementptr inbounds nuw %class.anon, ptr %20, i32 0, i32 2
  store ptr %17, ptr %26, align 8, !tbaa !14
  %27 = call noundef i32 @_ZN25__hip_builtin_threadIdx_t7__get_zEv() #8
  call void @_ZZ11MassVec3DPAILm192EEvPKdS1_PdiENKUliE_clEi(ptr noundef nonnull align 8 dereferenceable(24) %20, i32 noundef %27) #8
  call void @llvm.lifetime.end.p5(ptr addrspace(5) %12)
  ret void
}

; Function Attrs: convergent inlinehint mustprogress nounwind
define weak_odr hidden void @_ZZ11MassVec3DPAILm192EEvPKdS1_PdiENKUliE_clEi(ptr noundef nonnull align 8 dereferenceable(24) %0, i32 noundef %1) #1 comdat align 2 {
  %3 = alloca ptr, align 8, addrspace(5)
  %4 = alloca i32, align 4, addrspace(5)
  %5 = alloca i32, align 4, addrspace(5)
  %6 = alloca i32, align 4, addrspace(5)
  %7 = alloca i32, align 4, addrspace(5)
  %8 = alloca i32, align 4, addrspace(5)
  %9 = addrspacecast ptr addrspace(5) %3 to ptr
  %10 = addrspacecast ptr addrspace(5) %4 to ptr
  %11 = addrspacecast ptr addrspace(5) %5 to ptr
  %12 = addrspacecast ptr addrspace(5) %6 to ptr
  %13 = addrspacecast ptr addrspace(5) %7 to ptr
  %14 = addrspacecast ptr addrspace(5) %8 to ptr
  store ptr %0, ptr %9, align 8, !tbaa !16
  store i32 %1, ptr %10, align 4, !tbaa !12
  %15 = load ptr, ptr %9, align 8
  call void @llvm.lifetime.start.p5(ptr addrspace(5) %5)
  store i32 0, ptr %11, align 4, !tbaa !12
  br label %16

16:                                               ; preds = %57, %2
  %17 = load i32, ptr %11, align 4, !tbaa !12
  %18 = icmp slt i32 %17, 2
  br i1 %18, label %20, label %19

19:                                               ; preds = %16
  store i32 2, ptr %12, align 4
  call void @llvm.lifetime.end.p5(ptr addrspace(5) %5)
  br label %60

20:                                               ; preds = %16
  call void @llvm.lifetime.start.p5(ptr addrspace(5) %7)
  %21 = call noundef i32 @_ZN25__hip_builtin_threadIdx_t7__get_yEv() #8
  store i32 %21, ptr %13, align 4, !tbaa !12
  br label %22

22:                                               ; preds = %52, %20
  %23 = load i32, ptr %13, align 4, !tbaa !12
  %24 = icmp slt i32 %23, 4
  br i1 %24, label %26, label %25

25:                                               ; preds = %22
  store i32 5, ptr %12, align 4
  call void @llvm.lifetime.end.p5(ptr addrspace(5) %7)
  br label %56

26:                                               ; preds = %22
  call void @llvm.lifetime.start.p5(ptr addrspace(5) %8)
  %27 = load i32, ptr %11, align 4, !tbaa !12
  %28 = mul nsw i32 4, %27
  %29 = load i32, ptr %13, align 4, !tbaa !12
  %30 = add nsw i32 %28, %29
  store i32 %30, ptr %14, align 4, !tbaa !12
  %31 = getelementptr inbounds nuw %class.anon, ptr %15, i32 0, i32 1
  %32 = load ptr, ptr %31, align 8, !tbaa !17
  %33 = load ptr, ptr %32, align 8, !tbaa !7
  %34 = load i32, ptr %14, align 4, !tbaa !12
  %35 = sext i32 %34 to i64
  %36 = getelementptr inbounds double, ptr %33, i64 %35
  %37 = load double, ptr %36, align 8, !tbaa !19
  %38 = getelementptr inbounds nuw %class.anon, ptr %15, i32 0, i32 2
  %39 = load ptr, ptr %38, align 8, !tbaa !21
  %40 = load ptr, ptr %39, align 8, !tbaa !7
  %41 = load i32, ptr %14, align 4, !tbaa !12
  %42 = sext i32 %41 to i64
  %43 = getelementptr inbounds double, ptr %40, i64 %42
  %44 = load double, ptr %43, align 8, !tbaa !19
  %45 = fadd contract double %37, %44
  %46 = getelementptr inbounds nuw %class.anon, ptr %15, i32 0, i32 0
  %47 = load ptr, ptr %46, align 8, !tbaa !22
  %48 = load ptr, ptr %47, align 8, !tbaa !7
  %49 = load i32, ptr %14, align 4, !tbaa !12
  %50 = sext i32 %49 to i64
  %51 = getelementptr inbounds double, ptr %48, i64 %50
  store double %45, ptr %51, align 8, !tbaa !19
  call void @llvm.lifetime.end.p5(ptr addrspace(5) %8)
  br label %52

52:                                               ; preds = %26
  %53 = call noundef i32 @_ZN24__hip_builtin_blockDim_t7__get_yEv() #8
  %54 = load i32, ptr %13, align 4, !tbaa !12
  %55 = add i32 %54, %53
  store i32 %55, ptr %13, align 4, !tbaa !12
  br label %22, !llvm.loop !23

56:                                               ; preds = %25
  br label %57

57:                                               ; preds = %56
  %58 = load i32, ptr %11, align 4, !tbaa !12
  %59 = add nsw i32 %58, 1
  store i32 %59, ptr %11, align 4, !tbaa !12
  br label %16, !llvm.loop !25

60:                                               ; preds = %19
  ret void
}

; Function Attrs: alwaysinline convergent mustprogress nounwind
define weak_odr hidden noundef i32 @_ZN25__hip_builtin_threadIdx_t7__get_zEv() #2 comdat align 2 {
  %1 = alloca i32, align 4, addrspace(5)
  %2 = addrspacecast ptr addrspace(5) %1 to ptr
  %3 = call noundef i32 @_ZL22__hip_get_thread_idx_zv() #8
  ret i32 %3
}

; Function Attrs: alwaysinline convergent mustprogress nounwind
define weak_odr hidden noundef i32 @_ZN25__hip_builtin_threadIdx_t7__get_yEv() #2 comdat align 2 {
  %1 = alloca i32, align 4, addrspace(5)
  %2 = addrspacecast ptr addrspace(5) %1 to ptr
  %3 = call noundef i32 @_ZL22__hip_get_thread_idx_yv() #8
  ret i32 %3
}

; Function Attrs: alwaysinline convergent mustprogress nounwind
define weak_odr hidden noundef i32 @_ZN24__hip_builtin_blockDim_t7__get_yEv() #2 comdat align 2 {
  %1 = alloca i32, align 4, addrspace(5)
  %2 = addrspacecast ptr addrspace(5) %1 to ptr
  %3 = call noundef i32 @_ZL21__hip_get_block_dim_yv() #8
  ret i32 %3
}

; Function Attrs: alwaysinline convergent mustprogress nounwind
define hidden noundef i32 @_ZL22__hip_get_thread_idx_yv() #2 {
  %1 = alloca i32, align 4, addrspace(5)
  %2 = addrspacecast ptr addrspace(5) %1 to ptr
  %3 = call i64 @__ockl_get_local_id(i32 noundef 1) #9
  %4 = trunc i64 %3 to i32
  ret i32 %4
}

; Function Attrs: alwaysinline convergent mustprogress nounwind
define hidden noundef i32 @_ZL21__hip_get_block_dim_yv() #2 {
  %1 = alloca i32, align 4, addrspace(5)
  %2 = addrspacecast ptr addrspace(5) %1 to ptr
  %3 = call i64 @__ockl_get_local_size(i32 noundef 1) #9
  %4 = trunc i64 %3 to i32
  ret i32 %4
}

; Function Attrs: alwaysinline convergent mustprogress nounwind
define hidden noundef i32 @_ZL22__hip_get_thread_idx_zv() #2 {
  %1 = alloca i32, align 4, addrspace(5)
  %2 = addrspacecast ptr addrspace(5) %1 to ptr
  %3 = call i64 @__ockl_get_local_id(i32 noundef 2) #9
  %4 = trunc i64 %3 to i32
  ret i32 %4
}

; Function Attrs: convergent mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define hidden range(i64 0, 1024) i64 @__ockl_get_local_id(i32 noundef %0) #3 {
  switch i32 %0, label %8 [
  i32 0, label %2
  i32 1, label %4
  i32 2, label %6
  ]

2:                                                ; preds = %1
  %3 = tail call noundef range(i32 0, 1024) i32 @llvm.amdgcn.workitem.id.x()
  br label %8

4:                                                ; preds = %1
  %5 = tail call noundef range(i32 0, 1024) i32 @llvm.amdgcn.workitem.id.y()
  br label %8

6:                                                ; preds = %1
  %7 = tail call noundef range(i32 0, 1024) i32 @llvm.amdgcn.workitem.id.z()
  br label %8

8:                                                ; preds = %6, %4, %2, %1
  %9 = phi i32 [ %7, %6 ], [ %5, %4 ], [ %3, %2 ], [ 0, %1 ]
  %10 = zext nneg i32 %9 to i64
  ret i64 %10
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare noundef range(i32 0, 1024) i32 @llvm.amdgcn.workitem.id.x() #4

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare noundef range(i32 0, 1024) i32 @llvm.amdgcn.workitem.id.y() #4

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare noundef range(i32 0, 1024) i32 @llvm.amdgcn.workitem.id.z() #4

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare noundef align 4 ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr() #4

; Function Attrs: convergent mustprogress nofree norecurse nosync nounwind willreturn memory(none)
define hidden range(i64 0, 65536) i64 @__ockl_get_local_size(i32 noundef %0) #5 {
  switch i32 %0, label %76 [
  i32 0, label %2
  i32 1, label %26
  i32 2, label %51
  ]

2:                                                ; preds = %1
  %3 = load i32, ptr addrspace(4) @__oclc_ABI_version, align 4, !tbaa !26
  %4 = icmp slt i32 %3, 500
  br i1 %4, label %5, label %17

5:                                                ; preds = %2
  %6 = tail call align 4 dereferenceable(64) ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
  %7 = tail call i32 @llvm.amdgcn.workgroup.id.x()
  %8 = getelementptr inbounds nuw i8, ptr addrspace(4) %6, i64 4
  %9 = load i16, ptr addrspace(4) %8, align 4, !range !30, !invariant.load !31, !noundef !31
  %10 = zext nneg i16 %9 to i32
  %11 = getelementptr inbounds nuw i8, ptr addrspace(4) %6, i64 12
  %12 = load i32, ptr addrspace(4) %11, align 4, !tbaa !32
  %13 = mul i32 %7, %10
  %14 = sub i32 %12, %13
  %15 = tail call i32 @llvm.umin.i32(i32 %14, i32 %10)
  %16 = zext nneg i32 %15 to i64
  br label %76

17:                                               ; preds = %2
  %18 = tail call i32 @llvm.amdgcn.workgroup.id.x()
  %19 = tail call ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
  %20 = load i32, ptr addrspace(4) %19, align 4, !tbaa !26
  %21 = icmp ult i32 %18, %20
  %22 = select i1 %21, i64 12, i64 18
  %23 = getelementptr inbounds nuw i8, ptr addrspace(4) %19, i64 %22
  %24 = load i16, ptr addrspace(4) %23, align 2, !tbaa !39
  %25 = zext i16 %24 to i64
  br label %76

26:                                               ; preds = %1
  %27 = load i32, ptr addrspace(4) @__oclc_ABI_version, align 4, !tbaa !26
  %28 = icmp slt i32 %27, 500
  br i1 %28, label %29, label %41

29:                                               ; preds = %26
  %30 = tail call align 4 dereferenceable(64) ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
  %31 = tail call i32 @llvm.amdgcn.workgroup.id.y()
  %32 = getelementptr inbounds nuw i8, ptr addrspace(4) %30, i64 6
  %33 = load i16, ptr addrspace(4) %32, align 2, !range !30, !invariant.load !31, !noundef !31
  %34 = zext nneg i16 %33 to i32
  %35 = getelementptr inbounds nuw i8, ptr addrspace(4) %30, i64 16
  %36 = load i32, ptr addrspace(4) %35, align 8, !tbaa !40
  %37 = mul i32 %31, %34
  %38 = sub i32 %36, %37
  %39 = tail call i32 @llvm.umin.i32(i32 %38, i32 %34)
  %40 = zext nneg i32 %39 to i64
  br label %76

41:                                               ; preds = %26
  %42 = tail call i32 @llvm.amdgcn.workgroup.id.y()
  %43 = tail call ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
  %44 = getelementptr inbounds nuw i8, ptr addrspace(4) %43, i64 4
  %45 = load i32, ptr addrspace(4) %44, align 4, !tbaa !26
  %46 = icmp ult i32 %42, %45
  %47 = select i1 %46, i64 14, i64 20
  %48 = getelementptr inbounds nuw i8, ptr addrspace(4) %43, i64 %47
  %49 = load i16, ptr addrspace(4) %48, align 2, !tbaa !39
  %50 = zext i16 %49 to i64
  br label %76

51:                                               ; preds = %1
  %52 = load i32, ptr addrspace(4) @__oclc_ABI_version, align 4, !tbaa !26
  %53 = icmp slt i32 %52, 500
  br i1 %53, label %54, label %66

54:                                               ; preds = %51
  %55 = tail call align 4 dereferenceable(64) ptr addrspace(4) @llvm.amdgcn.dispatch.ptr()
  %56 = tail call i32 @llvm.amdgcn.workgroup.id.z()
  %57 = getelementptr inbounds nuw i8, ptr addrspace(4) %55, i64 8
  %58 = load i16, ptr addrspace(4) %57, align 4, !range !30, !invariant.load !31, !noundef !31
  %59 = zext nneg i16 %58 to i32
  %60 = getelementptr inbounds nuw i8, ptr addrspace(4) %55, i64 20
  %61 = load i32, ptr addrspace(4) %60, align 4, !tbaa !41
  %62 = mul i32 %56, %59
  %63 = sub i32 %61, %62
  %64 = tail call i32 @llvm.umin.i32(i32 %63, i32 %59)
  %65 = zext nneg i32 %64 to i64
  br label %76

66:                                               ; preds = %51
  %67 = tail call i32 @llvm.amdgcn.workgroup.id.z()
  %68 = tail call ptr addrspace(4) @llvm.amdgcn.implicitarg.ptr()
  %69 = getelementptr inbounds nuw i8, ptr addrspace(4) %68, i64 8
  %70 = load i32, ptr addrspace(4) %69, align 4, !tbaa !26
  %71 = icmp ult i32 %67, %70
  %72 = select i1 %71, i64 16, i64 22
  %73 = getelementptr inbounds nuw i8, ptr addrspace(4) %68, i64 %72
  %74 = load i16, ptr addrspace(4) %73, align 2, !tbaa !39
  %75 = zext i16 %74 to i64
  br label %76

76:                                               ; preds = %66, %54, %41, %29, %17, %5, %1
  %77 = phi i64 [ 1, %1 ], [ %16, %5 ], [ %25, %17 ], [ %40, %29 ], [ %50, %41 ], [ %65, %54 ], [ %75, %66 ]
  ret i64 %77
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare noundef nonnull align 4 ptr addrspace(4) @llvm.amdgcn.dispatch.ptr() #4

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare noundef i32 @llvm.amdgcn.workgroup.id.x() #4

; Function Attrs: nocallback nocreateundeforpoison nofree nosync nounwind speculatable willreturn memory(none)
declare i32 @llvm.umin.i32(i32, i32) #6

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare noundef i32 @llvm.amdgcn.workgroup.id.y() #4

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare noundef i32 @llvm.amdgcn.workgroup.id.z() #4

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.start.p5(ptr addrspace(5) captures(none)) #7

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(argmem: readwrite)
declare void @llvm.lifetime.end.p5(ptr addrspace(5) captures(none)) #7

attributes #0 = { convergent mustprogress norecurse nounwind "amdgpu-flat-work-group-size"="1,192" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx942" "target-features"="+16-bit-insts,+atomic-buffer-global-pk-add-f16-insts,+atomic-ds-pk-add-16-insts,+atomic-fadd-rtn-insts,+atomic-flat-pk-add-16-insts,+atomic-global-pk-add-bf16-inst,+ci-insts,+dl-insts,+dot1-insts,+dot10-insts,+dot2-insts,+dot3-insts,+dot4-insts,+dot5-insts,+dot6-insts,+dot7-insts,+dpp,+fp8-conversion-insts,+fp8-insts,+gfx8-insts,+gfx9-insts,+gfx90a-insts,+gfx940-insts,+mai-insts,+s-memrealtime,+s-memtime-inst,+wavefrontsize64,+xf32-insts" "uniform-work-group-size"="true" }
attributes #1 = { convergent inlinehint mustprogress nounwind "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx942" "target-features"="+16-bit-insts,+atomic-buffer-global-pk-add-f16-insts,+atomic-ds-pk-add-16-insts,+atomic-fadd-rtn-insts,+atomic-flat-pk-add-16-insts,+atomic-global-pk-add-bf16-inst,+ci-insts,+dl-insts,+dot1-insts,+dot10-insts,+dot2-insts,+dot3-insts,+dot4-insts,+dot5-insts,+dot6-insts,+dot7-insts,+dpp,+fp8-conversion-insts,+fp8-insts,+gfx8-insts,+gfx9-insts,+gfx90a-insts,+gfx940-insts,+mai-insts,+s-memrealtime,+s-memtime-inst,+wavefrontsize64,+xf32-insts" }
attributes #2 = { alwaysinline convergent mustprogress nounwind "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx942" "target-features"="+16-bit-insts,+atomic-buffer-global-pk-add-f16-insts,+atomic-ds-pk-add-16-insts,+atomic-fadd-rtn-insts,+atomic-flat-pk-add-16-insts,+atomic-global-pk-add-bf16-inst,+ci-insts,+dl-insts,+dot1-insts,+dot10-insts,+dot2-insts,+dot3-insts,+dot4-insts,+dot5-insts,+dot6-insts,+dot7-insts,+dpp,+fp8-conversion-insts,+fp8-insts,+gfx8-insts,+gfx9-insts,+gfx90a-insts,+gfx940-insts,+mai-insts,+s-memrealtime,+s-memtime-inst,+wavefrontsize64,+xf32-insts" }
attributes #3 = { convergent mustprogress nofree norecurse nosync nounwind willreturn memory(none) "amdgpu-no-agpr" "amdgpu-no-completion-action" "amdgpu-no-default-queue" "amdgpu-no-dispatch-id" "amdgpu-no-dispatch-ptr" "amdgpu-no-flat-scratch-init" "amdgpu-no-heap-ptr" "amdgpu-no-hostcall-ptr" "amdgpu-no-implicitarg-ptr" "amdgpu-no-lds-kernel-id" "amdgpu-no-multigrid-sync-arg" "amdgpu-no-queue-ptr" "amdgpu-no-workgroup-id-x" "amdgpu-no-workgroup-id-y" "amdgpu-no-workgroup-id-z" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx942" "target-features"="+16-bit-insts,+atomic-buffer-global-pk-add-f16-insts,+atomic-ds-pk-add-16-insts,+atomic-fadd-rtn-insts,+atomic-flat-pk-add-16-insts,+atomic-global-pk-add-bf16-inst,+ci-insts,+dl-insts,+dot1-insts,+dot10-insts,+dot2-insts,+dot3-insts,+dot4-insts,+dot5-insts,+dot6-insts,+dot7-insts,+dpp,+fp8-conversion-insts,+fp8-insts,+gfx8-insts,+gfx9-insts,+gfx90a-insts,+gfx940-insts,+gws,+mai-insts,+s-memrealtime,+s-memtime-inst,+vmem-to-lds-load-insts,+wavefrontsize64,+xf32-insts" "uniform-work-group-size"="false" }
attributes #4 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #5 = { convergent mustprogress nofree norecurse nosync nounwind willreturn memory(none) "amdgpu-no-agpr" "amdgpu-no-completion-action" "amdgpu-no-default-queue" "amdgpu-no-dispatch-id" "amdgpu-no-flat-scratch-init" "amdgpu-no-heap-ptr" "amdgpu-no-hostcall-ptr" "amdgpu-no-lds-kernel-id" "amdgpu-no-multigrid-sync-arg" "amdgpu-no-queue-ptr" "amdgpu-no-workitem-id-x" "amdgpu-no-workitem-id-y" "amdgpu-no-workitem-id-z" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx942" "target-features"="+16-bit-insts,+atomic-buffer-global-pk-add-f16-insts,+atomic-ds-pk-add-16-insts,+atomic-fadd-rtn-insts,+atomic-flat-pk-add-16-insts,+atomic-global-pk-add-bf16-inst,+ci-insts,+dl-insts,+dot1-insts,+dot10-insts,+dot2-insts,+dot3-insts,+dot4-insts,+dot5-insts,+dot6-insts,+dot7-insts,+dpp,+fp8-conversion-insts,+fp8-insts,+gfx8-insts,+gfx9-insts,+gfx90a-insts,+gfx940-insts,+gws,+mai-insts,+s-memrealtime,+s-memtime-inst,+vmem-to-lds-load-insts,+wavefrontsize64,+xf32-insts" "uniform-work-group-size"="false" }
attributes #6 = { nocallback nocreateundeforpoison nofree nosync nounwind speculatable willreturn memory(none) }
attributes #7 = { nocallback nofree nosync nounwind willreturn memory(argmem: readwrite) }
attributes #8 = { convergent nounwind }
attributes #9 = { convergent nounwind willreturn memory(none) }

!opencl.ocl.version = !{!6, !6, !6, !6, !6, !6, !6, !6, !6, !6}

!0 = !{i32 1, !"amdhsa_code_object_version", i32 600}
!6 = !{i32 2, i32 0}
!7 = !{!8, !8, i64 0}
!8 = !{!"p1 double", !9, i64 0}
!9 = !{!"any pointer", !10, i64 0}
!10 = !{!"omnipotent char", !11, i64 0}
!11 = !{!"Simple C++ TBAA"}
!12 = !{!13, !13, i64 0}
!13 = !{!"int", !10, i64 0}
!14 = !{!15, !15, i64 0}
!15 = !{!"p2 double", !9, i64 0}
!16 = !{!9, !9, i64 0}
!17 = !{!18, !15, i64 8}
!18 = !{!"_ZTSZ11MassVec3DPAILm192EEvPKdS1_PdiEUliE_", !15, i64 0, !15, i64 8, !15, i64 16}
!19 = !{!20, !20, i64 0}
!20 = !{!"double", !10, i64 0}
!21 = !{!18, !15, i64 16}
!22 = !{!18, !15, i64 0}
!23 = distinct !{!23, !24}
!24 = !{!"llvm.loop.mustprogress"}
!25 = distinct !{!25, !24}
!26 = !{!27, !27, i64 0}
!27 = !{!"int", !28, i64 0}
!28 = !{!"omnipotent char", !29, i64 0}
!29 = !{!"Simple C/C++ TBAA"}
!30 = !{i16 1, i16 1025}
!31 = !{}
!32 = !{!33, !27, i64 12}
!33 = !{!"hsa_kernel_dispatch_packet_s", !34, i64 0, !34, i64 2, !34, i64 4, !34, i64 6, !34, i64 8, !34, i64 10, !27, i64 12, !27, i64 16, !27, i64 20, !27, i64 24, !27, i64 28, !28, i64 32, !35, i64 40, !37, i64 48, !38, i64 56}
!34 = !{!"short", !28, i64 0}
!35 = !{!"p1 void", !36, i64 0}
!36 = !{!"any pointer", !28, i64 0}
!37 = !{!"long", !28, i64 0}
!38 = !{!"hsa_signal_s", !37, i64 0}
!39 = !{!34, !34, i64 0}
!40 = !{!33, !27, i64 16}
!41 = !{!33, !27, i64 20}
;.
; CHECK: [[SHORT_TBAA1]] = !{[[META2:![0-9]+]], [[META2]], i64 0}
; CHECK: [[META2]] = !{!"short", [[META3:![0-9]+]], i64 0}
; CHECK: [[META3]] = !{!"omnipotent char", [[META4:![0-9]+]], i64 0}
; CHECK: [[META4]] = !{!"Simple C/C++ TBAA"}
; CHECK: [[DOUBLE_TBAA5]] = !{[[META6:![0-9]+]], [[META6]], i64 0}
; CHECK: [[META6]] = !{!"double", [[META7:![0-9]+]], i64 0}
; CHECK: [[META7]] = !{!"omnipotent char", [[META8:![0-9]+]], i64 0}
; CHECK: [[META8]] = !{!"Simple C++ TBAA"}
; CHECK: [[LOOP9]] = distinct !{[[LOOP9]], [[META10:![0-9]+]]}
; CHECK: [[META10]] = !{!"llvm.loop.mustprogress"}
;.
