; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx900 < %s | FileCheck %s

; Regression coverage for llvm/llvm-project#187482.
;
; fma(fdiv afn 1.0, fmul(x, x), fneg(y), z): the fdiv spelling emits an
; extra v_mul_f32_e64 with a -v0 source modifier (+4B) vs the equivalent
; llvm.amdgcn.rcp.f32 spelling. The follow-up commit fixes the fdiv path.

define float @fma_fdiv_fneg_rcp_spelling(float %x, float %y, float %z) {
; CHECK-LABEL: fma_fdiv_fneg_rcp_spelling:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    v_mul_f32_e32 v0, v0, v0
; CHECK-NEXT:    v_rcp_f32_e32 v0, v0
; CHECK-NEXT:    v_fma_f32 v0, v0, -v1, v2
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  %fmul = fmul float %x, %x
  %rcp = call float @llvm.amdgcn.rcp.f32(float %fmul)
  %fneg = fneg float %y
  %fma = call float @llvm.fmuladd.f32(float %rcp, float %fneg, float %z)
  ret float %fma
}

define float @fma_fdiv_fneg_fdiv_spelling(float %x, float %y, float %z) {
; CHECK-LABEL: fma_fdiv_fneg_fdiv_spelling:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    v_mul_f32_e32 v0, v0, v0
; CHECK-NEXT:    v_rcp_f32_e32 v0, v0
; CHECK-NEXT:    v_fma_f32 v0, v0, -v1, v2
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  %fmul = fmul float %x, %x
  %fdiv = fdiv afn float 1.000000e+00, %fmul
  %fneg = fneg float %y
  %fma = call float @llvm.fmuladd.f32(float %fdiv, float %fneg, float %z)
  ret float %fma
}

declare float @llvm.amdgcn.rcp.f32(float)
declare float @llvm.fmuladd.f32(float, float, float)
