# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -mtriple=amdgcn -mcpu=gfx1200 -passes=finalizebundle-test %s -o - | FileCheck %s

--- |

  @foo = addrspace(3) global i32 poison

  define void @test_overlap() { unreachable }
  define void @test_dead_redef() { unreachable }
  define void @test_tied() { unreachable }
  define void @test_mmo_merge1() { unreachable }
  define void @test_mmo_merge2() { unreachable }
  define void @test_mmo_drop() { unreachable }
  define void @test_partial_def_1() { unreachable }
  define void @test_partial_def_2() { unreachable }
  define void @test_partial_def_3() { unreachable }
  define void @test_partial_def_4() { unreachable }

...

---
name: test_overlap
body: |
  bb.0:
    liveins: $vgpr0_vgpr1
    ; CHECK-LABEL: name: test_overlap
    ; CHECK: liveins: $vgpr0_vgpr1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: BUNDLE implicit-def $vgpr2_vgpr3, implicit-def $vgpr3_vgpr4, implicit $vgpr0_vgpr1, implicit $exec, implicit $vgpr1_vgpr2 {
    ; CHECK-NEXT:   $vgpr2_vgpr3 = V_LSHLREV_B64_pseudo_e32 1, $vgpr0_vgpr1, implicit $exec
    ; CHECK-NEXT:   $vgpr3_vgpr4 = V_LSHLREV_B64_pseudo_e32 1, $vgpr1_vgpr2, implicit $exec
    ; CHECK-NEXT: }
    $vgpr2_vgpr3 = V_LSHLREV_B64_pseudo_e32 1, $vgpr0_vgpr1, implicit $exec
    $vgpr3_vgpr4 = V_LSHLREV_B64_pseudo_e32 1, $vgpr1_vgpr2, implicit $exec
...

---
name: test_dead_redef
body: |
  bb.0:
    liveins: $vgpr0
    ; CHECK-LABEL: name: test_dead_redef
    ; CHECK: liveins: $vgpr0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: BUNDLE implicit-def dead $vgpr1, implicit-def $vgpr0, implicit $vgpr0, implicit $exec {
    ; CHECK-NEXT:   $vgpr1 = V_MOV_B32_e32 $vgpr0, implicit $exec
    ; CHECK-NEXT:   $vgpr0 = V_MOV_B32_e32 internal $vgpr1, implicit $exec
    ; CHECK-NEXT:   dead $vgpr1 = V_MOV_B32_e32 internal $vgpr0, implicit $exec
    ; CHECK-NEXT: }
    $vgpr1 = V_MOV_B32_e32 $vgpr0, implicit $exec
    $vgpr0 = V_MOV_B32_e32 $vgpr1, implicit $exec
    dead $vgpr1 = V_MOV_B32_e32 $vgpr0, implicit $exec
...

---
name: test_tied
body: |
  bb.0:
    ; CHECK-LABEL: name: test_tied
    ; CHECK: BUNDLE implicit-def %0, implicit-def %2, implicit %1:vgpr_32(tied-def 1), implicit $mode, implicit $exec {
    ; CHECK-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY %1:vgpr_32
    ; CHECK-NEXT:   [[V_FMAC_F16_e32_:%[0-9]+]]:vgpr_32 = V_FMAC_F16_e32 internal [[COPY]], internal [[COPY]], %1:vgpr_32, implicit $mode, implicit $exec
    ; CHECK-NEXT: }
    %1:vgpr_32 = COPY %0:vgpr_32
    %2:vgpr_32 = V_FMAC_F16_e32 %1, %1, %0, implicit $mode, implicit $exec
...

---
name: test_mmo_merge1
body: |
  bb.0:
    ; CHECK-LABEL: name: test_mmo_merge1
    ; CHECK: BUNDLE implicit-def %0, implicit %1:vgpr_32, implicit $exec :: (store (s32) into @foo, addrspace 3) {
    ; CHECK-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY %1:vgpr_32
    ; CHECK-NEXT:   DS_WRITE_B32_gfx9 %1:vgpr_32, internal [[COPY]], 0, 0, implicit $exec :: (store (s32) into @foo, addrspace 3)
    ; CHECK-NEXT: }
    %1:vgpr_32 = COPY %0:vgpr_32
    DS_WRITE_B32_gfx9 %0, %1, 0, 0, implicit $exec :: (store (s32) into @foo, addrspace 3)
...

---
name: test_mmo_merge2
body: |
  bb.0:
    ; CHECK-LABEL: name: test_mmo_merge2
    ; CHECK: BUNDLE implicit %0:vgpr_32, implicit %1:vgpr_32, implicit $exec :: (store (s32) into @foo, addrspace 3), (store (s32) into @foo + 4, addrspace 3) {
    ; CHECK-NEXT:   DS_WRITE_B32_gfx9 %0:vgpr_32, %1:vgpr_32, 0, 0, implicit $exec :: (store (s32) into @foo, addrspace 3)
    ; CHECK-NEXT:   DS_WRITE_B32_gfx9 %0:vgpr_32, %1:vgpr_32, 4, 0, implicit $exec :: (store (s32) into @foo + 4, addrspace 3)
    ; CHECK-NEXT: }
    DS_WRITE_B32_gfx9 %0:vgpr_32, %1:vgpr_32, 0, 0, implicit $exec :: (store (s32) into @foo, addrspace 3)
    DS_WRITE_B32_gfx9 %0:vgpr_32, %1:vgpr_32, 4, 0, implicit $exec :: (store (s32) into @foo + 4, addrspace 3)
...

---
name: test_mmo_drop
body: |
  bb.0:
    ; CHECK-LABEL: name: test_mmo_drop
    ; CHECK: BUNDLE implicit %0:vgpr_32, implicit %1:vgpr_32, implicit $exec {
    ; CHECK-NEXT:   DS_WRITE_B32_gfx9 %0:vgpr_32, %1:vgpr_32, 0, 0, implicit $exec :: (store (s32) into @foo, addrspace 3)
    ; CHECK-NEXT:   DS_WRITE_B32_gfx9 %0:vgpr_32, %1:vgpr_32, 4, 0, implicit $exec
    ; CHECK-NEXT: }
    DS_WRITE_B32_gfx9 %0:vgpr_32, %1:vgpr_32, 0, 0, implicit $exec :: (store (s32) into @foo, addrspace 3)
    DS_WRITE_B32_gfx9 %0:vgpr_32, %1:vgpr_32, 4, 0, implicit $exec
...

---
name: test_partial_def_1
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $sgpr0_sgpr1, $vgpr1
    ; CHECK-LABEL: name: test_partial_def_1
    ; CHECK: liveins: $sgpr0_sgpr1, $vgpr1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: BUNDLE implicit-def $vgpr0_lo16, implicit-def dead $vgpr0, implicit $sgpr0_sgpr1, implicit $vgpr1, implicit $exec {
    ; CHECK-NEXT:   $vgpr0_lo16 = GLOBAL_LOAD_SHORT_D16_SADDR_t16 $sgpr0_sgpr1, $vgpr1, 0, 0, implicit $exec
    ; CHECK-NEXT:   $vgpr0 = GLOBAL_LOAD_SHORT_D16_HI_SADDR $sgpr0_sgpr1, $vgpr1, 512, 0, internal killed $vgpr0, implicit $exec
    ; CHECK-NEXT: }
    $vgpr0_lo16 = GLOBAL_LOAD_SHORT_D16_SADDR_t16 $sgpr0_sgpr1, $vgpr1, 0, 0, implicit $exec
    $vgpr0 = GLOBAL_LOAD_SHORT_D16_HI_SADDR $sgpr0_sgpr1, $vgpr1, 512, 0, killed $vgpr0, implicit $exec
...

---
name: test_partial_def_2
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $vgpr0
    ; CHECK-LABEL: name: test_partial_def_2
    ; CHECK: liveins: $vgpr0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: BUNDLE implicit-def $vgpr2_vgpr3, implicit-def $vgpr5_vgpr6, implicit $vgpr0_vgpr1 {
    ; CHECK-NEXT:   $vgpr2_vgpr3 = COPY $vgpr0_vgpr1
    ; CHECK-NEXT:   $vgpr5_vgpr6 = COPY internal $vgpr3_vgpr4
    ; CHECK-NEXT: }
    $vgpr2_vgpr3 = COPY $vgpr0_vgpr1
    $vgpr5_vgpr6 = COPY $vgpr3_vgpr4
...

---
name: test_partial_def_3
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $vgpr0_vgpr1
    ; CHECK-LABEL: name: test_partial_def_3
    ; CHECK: liveins: $vgpr0_vgpr1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: BUNDLE implicit-def $vgpr2_vgpr3, implicit-def $vgpr3_vgpr4, implicit-def $vgpr5_vgpr6_vgpr7, implicit-def $vgpr8_vgpr9, implicit $vgpr0_vgpr1 {
    ; CHECK-NEXT:   $vgpr2_vgpr3 = COPY $vgpr0_vgpr1
    ; CHECK-NEXT:   $vgpr3_vgpr4 = COPY $vgpr0_vgpr1
    ; CHECK-NEXT:   $vgpr5_vgpr6_vgpr7 = COPY internal $vgpr3_vgpr4_vgpr5
    ; CHECK-NEXT:   $vgpr8_vgpr9 = COPY internal $vgpr3_vgpr4
    ; CHECK-NEXT: }
    $vgpr2_vgpr3 = COPY $vgpr0_vgpr1
    $vgpr3_vgpr4 = COPY $vgpr0_vgpr1
    $vgpr5_vgpr6_vgpr7 = COPY $vgpr3_vgpr4_vgpr5
    $vgpr8_vgpr9 = COPY $vgpr3_vgpr4
...

---
name: test_partial_def_4
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $vgpr0
    ; CHECK-LABEL: name: test_partial_def_4
    ; CHECK: liveins: $vgpr0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: BUNDLE implicit-def $vgpr2_vgpr3, implicit-def $vgpr5_vgpr6, implicit $vgpr0_vgpr1, implicit undef $vgpr3_vgpr4 {
    ; CHECK-NEXT:   $vgpr2_vgpr3 = COPY $vgpr0_vgpr1
    ; CHECK-NEXT:   $vgpr5_vgpr6 = COPY undef $vgpr3_vgpr4
    ; CHECK-NEXT: }
    $vgpr2_vgpr3 = COPY $vgpr0_vgpr1
    $vgpr5_vgpr6 = COPY undef $vgpr3_vgpr4
...
