; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=amdgcn -mcpu=gfx600 < %s | FileCheck %s

; Test folding of float->int->float roundtrips into float-only operations.

define float @test_signed_basic(float %x) {
; CHECK-LABEL: test_signed_basic:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    v_cvt_i32_f32_e32 v0, v0
; CHECK-NEXT:    v_cvt_f32_i32_e32 v0, v0
; CHECK-NEXT:    s_setpc_b64 s[30:31]
entry:
  %i = fptosi float %x to i32
  %f = sitofp i32 %i to float
  ret float %f
}

define float @test_signed_basic_nsz(float %x) {
; CHECK-LABEL: test_signed_basic_nsz:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    v_trunc_f32_e32 v0, v0
; CHECK-NEXT:    s_setpc_b64 s[30:31]
entry:
  %i = fptosi float %x to i32
  %f = sitofp nsz i32 %i to float
  ret float %f
}

; For unsigned conversions, even when signed zeros are possible, we can still
; use truncate because fabs is free.
define float @test_unsigned_basic(float %x) {
; CHECK-LABEL: test_unsigned_basic:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    v_trunc_f32_e64 v0, |v0|
; CHECK-NEXT:    s_setpc_b64 s[30:31]
entry:
  %i = fptoui float %x to i32
  %f = uitofp i32 %i to float
  ret float %f
}

define float @test_unsigned_basic_nsz(float %x) {
; CHECK-LABEL: test_unsigned_basic_nsz:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    v_trunc_f32_e32 v0, v0
; CHECK-NEXT:    s_setpc_b64 s[30:31]
entry:
  %i = fptoui float %x to i32
  %f = uitofp nsz i32 %i to float
  ret float %f
}

; 16777217 is NOT exactly representable in f32.
define float @test_inexact_16777217(float %x) {
; CHECK-LABEL: test_inexact_16777217:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    v_cvt_i32_f32_e32 v0, v0
; CHECK-NEXT:    v_min_i32_e32 v0, 0x1000001, v0
; CHECK-NEXT:    v_cvt_f32_i32_e32 v0, v0
; CHECK-NEXT:    s_setpc_b64 s[30:31]
entry:
  %i = fptosi float %x to i32
  %clamped = call i32 @llvm.smin.i32(i32 %i, i32 16777217)
  %f = sitofp i32 %clamped to float
  ret float %f
}

declare i32 @llvm.smin.i32(i32, i32)
