; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc < %s -mtriple=amdgcn -mcpu=gfx90a -amdgpu-atomic-optimizer-strategy=None | FileCheck %s -check-prefix=GFX90A
; RUN: llc < %s -mtriple=amdgcn -mcpu=gfx940 -amdgpu-atomic-optimizer-strategy=None | FileCheck %s -check-prefix=GFX940
; RUN: llc < %s -mtriple=amdgcn -mcpu=gfx1210 -amdgpu-atomic-optimizer-strategy=None | FileCheck %s -check-prefix=GFX1210
; RUN: llc < %s -mtriple=amdgcn -mcpu=gfx1300 -amdgpu-atomic-optimizer-strategy=None | FileCheck %s -check-prefix=GFX13

declare double @llvm.amdgcn.struct.buffer.atomic.fmin.f64(double, <4 x i32>, i32, i32, i32, i32 immarg)
declare double @llvm.amdgcn.struct.ptr.buffer.atomic.fmin.f64(double, ptr addrspace(8), i32, i32, i32, i32 immarg)
declare double @llvm.amdgcn.raw.buffer.atomic.fmin.f64(double, <4 x i32>, i32, i32, i32 immarg)
declare double @llvm.amdgcn.raw.ptr.buffer.atomic.fmin.f64(double, ptr addrspace(8), i32, i32, i32 immarg)
declare double @llvm.amdgcn.struct.buffer.atomic.fmax.f64(double, <4 x i32>, i32, i32, i32, i32 immarg)
declare double @llvm.amdgcn.struct.ptr.buffer.atomic.fmax.f64(double, ptr addrspace(8), i32, i32, i32, i32 immarg)
declare double @llvm.amdgcn.raw.buffer.atomic.fmax.f64(double, <4 x i32>, i32, i32, i32 immarg)
declare double @llvm.amdgcn.raw.ptr.buffer.atomic.fmax.f64(double, ptr addrspace(8), i32, i32, i32 immarg)
declare double @llvm.amdgcn.global.atomic.fmin.f64.p1.f64(ptr addrspace(1) %ptr, double %data)
declare double @llvm.amdgcn.global.atomic.fmax.f64.p1.f64(ptr addrspace(1) %ptr, double %data)
declare double @llvm.amdgcn.flat.atomic.fmin.f64.p0.f64(ptr %ptr, double %data)
declare double @llvm.amdgcn.flat.atomic.fmax.f64.p0.f64(ptr %ptr, double %data)

define amdgpu_kernel void @raw_buffer_atomic_min_noret_f64(<4 x i32> %rsrc, double %data, i32 %vindex) {
; GFX90A-LABEL: raw_buffer_atomic_min_noret_f64:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX90A-NEXT:    s_load_dword s8, s[2:3], 0x3c
; GFX90A-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX90A-NEXT:    s_waitcnt lgkmcnt(0)
; GFX90A-NEXT:    v_pk_mov_b32 v[0:1], s[0:1], s[0:1] op_sel:[0,1]
; GFX90A-NEXT:    v_mov_b32_e32 v2, s8
; GFX90A-NEXT:    buffer_atomic_min_f64 v[0:1], v2, s[4:7], 0 offen
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: raw_buffer_atomic_min_noret_f64:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX940-NEXT:    s_load_dword s8, s[2:3], 0x3c
; GFX940-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX940-NEXT:    s_waitcnt lgkmcnt(0)
; GFX940-NEXT:    v_mov_b64_e32 v[0:1], s[0:1]
; GFX940-NEXT:    v_mov_b32_e32 v2, s8
; GFX940-NEXT:    buffer_atomic_min_f64 v[0:1], v2, s[4:7], 0 offen
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: raw_buffer_atomic_min_noret_f64:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    s_load_b96 s[4:6], s[2:3], 0x34
; GFX1210-NEXT:    s_wait_xcnt 0x0
; GFX1210-NEXT:    s_load_b128 s[0:3], s[2:3], 0x24
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    v_mov_b64_e32 v[0:1], s[4:5]
; GFX1210-NEXT:    v_mov_b32_e32 v2, s6
; GFX1210-NEXT:    buffer_atomic_min_num_f64 v[0:1], v2, s[0:3], null offen
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: raw_buffer_atomic_min_noret_f64:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    s_clause 0x1
; GFX13-NEXT:    s_load_b96 s[4:6], s[2:3], 0x34
; GFX13-NEXT:    s_load_b128 s[0:3], s[2:3], 0x24
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    v_mov_b64_e32 v[0:1], s[4:5]
; GFX13-NEXT:    v_mov_b32_e32 v2, s6
; GFX13-NEXT:    buffer_atomic_min_num_f64 v[0:1], v2, s[0:3], null offen
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.raw.buffer.atomic.fmin.f64(double %data, <4 x i32> %rsrc, i32 %vindex, i32 0, i32 0)
  ret void
}

define amdgpu_ps void @raw_buffer_atomic_min_rtn_f64(<4 x i32> inreg %rsrc, double %data, i32 %vindex) {
; GFX90A-LABEL: raw_buffer_atomic_min_rtn_f64:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    buffer_atomic_min_f64 v[0:1], v2, s[0:3], 0 offen glc
; GFX90A-NEXT:    s_waitcnt vmcnt(0)
; GFX90A-NEXT:    flat_store_dwordx2 v[0:1], v[0:1]
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: raw_buffer_atomic_min_rtn_f64:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    buffer_atomic_min_f64 v[0:1], v2, s[0:3], 0 offen sc0
; GFX940-NEXT:    s_waitcnt vmcnt(0)
; GFX940-NEXT:    flat_store_dwordx2 v[0:1], v[0:1] sc0 sc1
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: raw_buffer_atomic_min_rtn_f64:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    buffer_atomic_min_num_f64 v[0:1], v2, s[0:3], null offen th:TH_ATOMIC_RETURN
; GFX1210-NEXT:    s_wait_loadcnt 0x0
; GFX1210-NEXT:    flat_store_b64 v[0:1], v[0:1]
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: raw_buffer_atomic_min_rtn_f64:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    buffer_atomic_min_num_f64 v[0:1], v2, s[0:3], null offen th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    flat_store_b64 v[0:1], v[0:1]
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.raw.buffer.atomic.fmin.f64(double %data, <4 x i32> %rsrc, i32 %vindex, i32 0, i32 0)
  store double %ret, ptr undef
  ret void
}

define amdgpu_kernel void @raw_buffer_atomic_min_rtn_f64_off4_slc(<4 x i32> %rsrc, double %data, i32 %vindex, ptr addrspace(1) %out) {
; GFX90A-LABEL: raw_buffer_atomic_min_rtn_f64_off4_slc:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX90A-NEXT:    s_load_dword s10, s[2:3], 0x3c
; GFX90A-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX90A-NEXT:    s_load_dwordx2 s[8:9], s[2:3], 0x44
; GFX90A-NEXT:    s_waitcnt lgkmcnt(0)
; GFX90A-NEXT:    v_pk_mov_b32 v[0:1], s[0:1], s[0:1] op_sel:[0,1]
; GFX90A-NEXT:    v_mov_b32_e32 v2, s10
; GFX90A-NEXT:    buffer_atomic_min_f64 v[0:1], v2, s[4:7], 4 offen glc slc
; GFX90A-NEXT:    v_mov_b32_e32 v2, 0
; GFX90A-NEXT:    s_waitcnt vmcnt(0)
; GFX90A-NEXT:    global_store_dwordx2 v2, v[0:1], s[8:9]
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: raw_buffer_atomic_min_rtn_f64_off4_slc:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX940-NEXT:    s_load_dword s10, s[2:3], 0x3c
; GFX940-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX940-NEXT:    s_load_dwordx2 s[8:9], s[2:3], 0x44
; GFX940-NEXT:    s_waitcnt lgkmcnt(0)
; GFX940-NEXT:    v_mov_b64_e32 v[0:1], s[0:1]
; GFX940-NEXT:    v_mov_b32_e32 v2, s10
; GFX940-NEXT:    buffer_atomic_min_f64 v[0:1], v2, s[4:7], 4 offen sc0 nt
; GFX940-NEXT:    v_mov_b32_e32 v2, 0
; GFX940-NEXT:    s_waitcnt vmcnt(0)
; GFX940-NEXT:    global_store_dwordx2 v2, v[0:1], s[8:9] sc0 sc1
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: raw_buffer_atomic_min_rtn_f64_off4_slc:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    s_clause 0x1
; GFX1210-NEXT:    s_load_b96 s[8:10], s[2:3], 0x34
; GFX1210-NEXT:    s_load_b128 s[4:7], s[2:3], 0x24
; GFX1210-NEXT:    s_mov_b32 s0, 4
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    v_mov_b64_e32 v[0:1], s[8:9]
; GFX1210-NEXT:    v_mov_b32_e32 v2, s10
; GFX1210-NEXT:    buffer_atomic_min_num_f64 v[0:1], v2, s[4:7], s0 offen th:TH_ATOMIC_NT_RETURN
; GFX1210-NEXT:    s_wait_xcnt 0x0
; GFX1210-NEXT:    s_load_b64 s[0:1], s[2:3], 0x44
; GFX1210-NEXT:    v_mov_b32_e32 v2, 0
; GFX1210-NEXT:    s_wait_loadcnt 0x0
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    global_store_b64 v2, v[0:1], s[0:1]
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: raw_buffer_atomic_min_rtn_f64_off4_slc:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    s_clause 0x1
; GFX13-NEXT:    s_load_b96 s[8:10], s[2:3], 0x34
; GFX13-NEXT:    s_load_b128 s[4:7], s[2:3], 0x24
; GFX13-NEXT:    s_mov_b32 s0, 4
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    v_mov_b64_e32 v[0:1], s[8:9]
; GFX13-NEXT:    v_mov_b32_e32 v2, s10
; GFX13-NEXT:    buffer_atomic_min_num_f64 v[0:1], v2, s[4:7], s0 offen th:TH_ATOMIC_NT_RETURN
; GFX13-NEXT:    s_load_b64 s[0:1], s[2:3], 0x44
; GFX13-NEXT:    v_mov_b32_e32 v2, 0
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    global_store_b64 v2, v[0:1], s[0:1]
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.raw.buffer.atomic.fmin.f64(double %data, <4 x i32> %rsrc, i32 %vindex, i32 4, i32 2)
  store double %ret, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_kernel void @raw_ptr_buffer_atomic_min_noret_f64(ptr addrspace(8) %rsrc, double %data, i32 %vindex) {
; GFX90A-LABEL: raw_ptr_buffer_atomic_min_noret_f64:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX90A-NEXT:    s_load_dword s8, s[2:3], 0x3c
; GFX90A-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX90A-NEXT:    s_waitcnt lgkmcnt(0)
; GFX90A-NEXT:    v_pk_mov_b32 v[0:1], s[0:1], s[0:1] op_sel:[0,1]
; GFX90A-NEXT:    v_mov_b32_e32 v2, s8
; GFX90A-NEXT:    buffer_atomic_min_f64 v[0:1], v2, s[4:7], 0 offen
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: raw_ptr_buffer_atomic_min_noret_f64:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX940-NEXT:    s_load_dword s8, s[2:3], 0x3c
; GFX940-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX940-NEXT:    s_waitcnt lgkmcnt(0)
; GFX940-NEXT:    v_mov_b64_e32 v[0:1], s[0:1]
; GFX940-NEXT:    v_mov_b32_e32 v2, s8
; GFX940-NEXT:    buffer_atomic_min_f64 v[0:1], v2, s[4:7], 0 offen
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: raw_ptr_buffer_atomic_min_noret_f64:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    s_load_b96 s[4:6], s[2:3], 0x34
; GFX1210-NEXT:    s_wait_xcnt 0x0
; GFX1210-NEXT:    s_load_b128 s[0:3], s[2:3], 0x24
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    v_mov_b64_e32 v[0:1], s[4:5]
; GFX1210-NEXT:    v_mov_b32_e32 v2, s6
; GFX1210-NEXT:    buffer_atomic_min_num_f64 v[0:1], v2, s[0:3], null offen
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: raw_ptr_buffer_atomic_min_noret_f64:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    s_clause 0x1
; GFX13-NEXT:    s_load_b96 s[4:6], s[2:3], 0x34
; GFX13-NEXT:    s_load_b128 s[0:3], s[2:3], 0x24
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    v_mov_b64_e32 v[0:1], s[4:5]
; GFX13-NEXT:    v_mov_b32_e32 v2, s6
; GFX13-NEXT:    buffer_atomic_min_num_f64 v[0:1], v2, s[0:3], null offen
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.raw.ptr.buffer.atomic.fmin.f64(double %data, ptr addrspace(8) %rsrc, i32 %vindex, i32 0, i32 0)
  ret void
}

define amdgpu_ps void @raw_ptr_buffer_atomic_min_rtn_f64(ptr addrspace(8) inreg %rsrc, double %data, i32 %vindex) {
; GFX90A-LABEL: raw_ptr_buffer_atomic_min_rtn_f64:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    buffer_atomic_min_f64 v[0:1], v2, s[0:3], 0 offen glc
; GFX90A-NEXT:    s_waitcnt vmcnt(0)
; GFX90A-NEXT:    flat_store_dwordx2 v[0:1], v[0:1]
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: raw_ptr_buffer_atomic_min_rtn_f64:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    buffer_atomic_min_f64 v[0:1], v2, s[0:3], 0 offen sc0
; GFX940-NEXT:    s_waitcnt vmcnt(0)
; GFX940-NEXT:    flat_store_dwordx2 v[0:1], v[0:1] sc0 sc1
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: raw_ptr_buffer_atomic_min_rtn_f64:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    buffer_atomic_min_num_f64 v[0:1], v2, s[0:3], null offen th:TH_ATOMIC_RETURN
; GFX1210-NEXT:    s_wait_loadcnt 0x0
; GFX1210-NEXT:    flat_store_b64 v[0:1], v[0:1]
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: raw_ptr_buffer_atomic_min_rtn_f64:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    buffer_atomic_min_num_f64 v[0:1], v2, s[0:3], null offen th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    flat_store_b64 v[0:1], v[0:1]
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.raw.ptr.buffer.atomic.fmin.f64(double %data, ptr addrspace(8) %rsrc, i32 %vindex, i32 0, i32 0)
  store double %ret, ptr undef
  ret void
}

define amdgpu_kernel void @raw_ptr_buffer_atomic_min_rtn_f64_off4_slc(ptr addrspace(8) %rsrc, double %data, i32 %vindex, ptr addrspace(1) %out) {
; GFX90A-LABEL: raw_ptr_buffer_atomic_min_rtn_f64_off4_slc:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX90A-NEXT:    s_load_dword s10, s[2:3], 0x3c
; GFX90A-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX90A-NEXT:    s_load_dwordx2 s[8:9], s[2:3], 0x44
; GFX90A-NEXT:    s_waitcnt lgkmcnt(0)
; GFX90A-NEXT:    v_pk_mov_b32 v[0:1], s[0:1], s[0:1] op_sel:[0,1]
; GFX90A-NEXT:    v_mov_b32_e32 v2, s10
; GFX90A-NEXT:    buffer_atomic_min_f64 v[0:1], v2, s[4:7], 4 offen glc slc
; GFX90A-NEXT:    v_mov_b32_e32 v2, 0
; GFX90A-NEXT:    s_waitcnt vmcnt(0)
; GFX90A-NEXT:    global_store_dwordx2 v2, v[0:1], s[8:9]
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: raw_ptr_buffer_atomic_min_rtn_f64_off4_slc:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX940-NEXT:    s_load_dword s10, s[2:3], 0x3c
; GFX940-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX940-NEXT:    s_load_dwordx2 s[8:9], s[2:3], 0x44
; GFX940-NEXT:    s_waitcnt lgkmcnt(0)
; GFX940-NEXT:    v_mov_b64_e32 v[0:1], s[0:1]
; GFX940-NEXT:    v_mov_b32_e32 v2, s10
; GFX940-NEXT:    buffer_atomic_min_f64 v[0:1], v2, s[4:7], 4 offen sc0 nt
; GFX940-NEXT:    v_mov_b32_e32 v2, 0
; GFX940-NEXT:    s_waitcnt vmcnt(0)
; GFX940-NEXT:    global_store_dwordx2 v2, v[0:1], s[8:9] sc0 sc1
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: raw_ptr_buffer_atomic_min_rtn_f64_off4_slc:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    s_clause 0x1
; GFX1210-NEXT:    s_load_b96 s[8:10], s[2:3], 0x34
; GFX1210-NEXT:    s_load_b128 s[4:7], s[2:3], 0x24
; GFX1210-NEXT:    s_mov_b32 s0, 4
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    v_mov_b64_e32 v[0:1], s[8:9]
; GFX1210-NEXT:    v_mov_b32_e32 v2, s10
; GFX1210-NEXT:    buffer_atomic_min_num_f64 v[0:1], v2, s[4:7], s0 offen th:TH_ATOMIC_NT_RETURN
; GFX1210-NEXT:    s_wait_xcnt 0x0
; GFX1210-NEXT:    s_load_b64 s[0:1], s[2:3], 0x44
; GFX1210-NEXT:    v_mov_b32_e32 v2, 0
; GFX1210-NEXT:    s_wait_loadcnt 0x0
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    global_store_b64 v2, v[0:1], s[0:1]
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: raw_ptr_buffer_atomic_min_rtn_f64_off4_slc:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    s_clause 0x1
; GFX13-NEXT:    s_load_b96 s[8:10], s[2:3], 0x34
; GFX13-NEXT:    s_load_b128 s[4:7], s[2:3], 0x24
; GFX13-NEXT:    s_mov_b32 s0, 4
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    v_mov_b64_e32 v[0:1], s[8:9]
; GFX13-NEXT:    v_mov_b32_e32 v2, s10
; GFX13-NEXT:    buffer_atomic_min_num_f64 v[0:1], v2, s[4:7], s0 offen th:TH_ATOMIC_NT_RETURN
; GFX13-NEXT:    s_load_b64 s[0:1], s[2:3], 0x44
; GFX13-NEXT:    v_mov_b32_e32 v2, 0
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    global_store_b64 v2, v[0:1], s[0:1]
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.raw.ptr.buffer.atomic.fmin.f64(double %data, ptr addrspace(8) %rsrc, i32 %vindex, i32 4, i32 2)
  store double %ret, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_kernel void @struct_buffer_atomic_min_noret_f64(<4 x i32> %rsrc, double %data, i32 %vindex) {
; GFX90A-LABEL: struct_buffer_atomic_min_noret_f64:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX90A-NEXT:    s_load_dword s8, s[2:3], 0x3c
; GFX90A-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX90A-NEXT:    s_waitcnt lgkmcnt(0)
; GFX90A-NEXT:    v_pk_mov_b32 v[0:1], s[0:1], s[0:1] op_sel:[0,1]
; GFX90A-NEXT:    v_mov_b32_e32 v2, s8
; GFX90A-NEXT:    buffer_atomic_min_f64 v[0:1], v2, s[4:7], 0 idxen
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: struct_buffer_atomic_min_noret_f64:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX940-NEXT:    s_load_dword s8, s[2:3], 0x3c
; GFX940-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX940-NEXT:    s_waitcnt lgkmcnt(0)
; GFX940-NEXT:    v_mov_b64_e32 v[0:1], s[0:1]
; GFX940-NEXT:    v_mov_b32_e32 v2, s8
; GFX940-NEXT:    buffer_atomic_min_f64 v[0:1], v2, s[4:7], 0 idxen
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: struct_buffer_atomic_min_noret_f64:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    s_load_b96 s[4:6], s[2:3], 0x34
; GFX1210-NEXT:    s_wait_xcnt 0x0
; GFX1210-NEXT:    s_load_b128 s[0:3], s[2:3], 0x24
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    v_mov_b64_e32 v[0:1], s[4:5]
; GFX1210-NEXT:    v_mov_b32_e32 v2, s6
; GFX1210-NEXT:    buffer_atomic_min_num_f64 v[0:1], v2, s[0:3], null idxen
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: struct_buffer_atomic_min_noret_f64:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    s_clause 0x1
; GFX13-NEXT:    s_load_b96 s[4:6], s[2:3], 0x34
; GFX13-NEXT:    s_load_b128 s[0:3], s[2:3], 0x24
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    v_mov_b64_e32 v[0:1], s[4:5]
; GFX13-NEXT:    v_mov_b32_e32 v2, s6
; GFX13-NEXT:    buffer_atomic_min_num_f64 v[0:1], v2, s[0:3], null idxen
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.struct.buffer.atomic.fmin.f64(double %data, <4 x i32> %rsrc, i32 %vindex, i32 0, i32 0, i32 0)
  ret void
}

define amdgpu_ps void @struct_buffer_atomic_min_rtn_f64(<4 x i32> inreg %rsrc, double %data, i32 %vindex) {
; GFX90A-LABEL: struct_buffer_atomic_min_rtn_f64:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    buffer_atomic_min_f64 v[0:1], v2, s[0:3], 0 idxen glc
; GFX90A-NEXT:    s_waitcnt vmcnt(0)
; GFX90A-NEXT:    flat_store_dwordx2 v[0:1], v[0:1]
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: struct_buffer_atomic_min_rtn_f64:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    buffer_atomic_min_f64 v[0:1], v2, s[0:3], 0 idxen sc0
; GFX940-NEXT:    s_waitcnt vmcnt(0)
; GFX940-NEXT:    flat_store_dwordx2 v[0:1], v[0:1] sc0 sc1
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: struct_buffer_atomic_min_rtn_f64:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    buffer_atomic_min_num_f64 v[0:1], v2, s[0:3], null idxen th:TH_ATOMIC_RETURN
; GFX1210-NEXT:    s_wait_loadcnt 0x0
; GFX1210-NEXT:    flat_store_b64 v[0:1], v[0:1]
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: struct_buffer_atomic_min_rtn_f64:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    buffer_atomic_min_num_f64 v[0:1], v2, s[0:3], null idxen th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    flat_store_b64 v[0:1], v[0:1]
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.struct.buffer.atomic.fmin.f64(double %data, <4 x i32> %rsrc, i32 %vindex, i32 0, i32 0, i32 0)
  store double %ret, ptr undef
  ret void
}

define amdgpu_kernel void @struct_buffer_atomic_min_rtn_f64_off4_slc(<4 x i32> %rsrc, double %data, i32 %vindex, ptr addrspace(1) %out) {
; GFX90A-LABEL: struct_buffer_atomic_min_rtn_f64_off4_slc:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX90A-NEXT:    s_load_dword s10, s[2:3], 0x3c
; GFX90A-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX90A-NEXT:    s_load_dwordx2 s[8:9], s[2:3], 0x44
; GFX90A-NEXT:    s_waitcnt lgkmcnt(0)
; GFX90A-NEXT:    v_pk_mov_b32 v[0:1], s[0:1], s[0:1] op_sel:[0,1]
; GFX90A-NEXT:    v_mov_b32_e32 v2, s10
; GFX90A-NEXT:    buffer_atomic_min_f64 v[0:1], v2, s[4:7], 0 idxen offset:4 glc slc
; GFX90A-NEXT:    v_mov_b32_e32 v2, 0
; GFX90A-NEXT:    s_waitcnt vmcnt(0)
; GFX90A-NEXT:    global_store_dwordx2 v2, v[0:1], s[8:9]
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: struct_buffer_atomic_min_rtn_f64_off4_slc:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX940-NEXT:    s_load_dword s10, s[2:3], 0x3c
; GFX940-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX940-NEXT:    s_load_dwordx2 s[8:9], s[2:3], 0x44
; GFX940-NEXT:    s_waitcnt lgkmcnt(0)
; GFX940-NEXT:    v_mov_b64_e32 v[0:1], s[0:1]
; GFX940-NEXT:    v_mov_b32_e32 v2, s10
; GFX940-NEXT:    buffer_atomic_min_f64 v[0:1], v2, s[4:7], 0 idxen offset:4 sc0 nt
; GFX940-NEXT:    v_mov_b32_e32 v2, 0
; GFX940-NEXT:    s_waitcnt vmcnt(0)
; GFX940-NEXT:    global_store_dwordx2 v2, v[0:1], s[8:9] sc0 sc1
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: struct_buffer_atomic_min_rtn_f64_off4_slc:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    s_clause 0x2
; GFX1210-NEXT:    s_load_b96 s[8:10], s[2:3], 0x34
; GFX1210-NEXT:    s_load_b128 s[4:7], s[2:3], 0x24
; GFX1210-NEXT:    s_load_b64 s[0:1], s[2:3], 0x44
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    v_mov_b64_e32 v[0:1], s[8:9]
; GFX1210-NEXT:    v_mov_b32_e32 v2, s10
; GFX1210-NEXT:    buffer_atomic_min_num_f64 v[0:1], v2, s[4:7], null idxen offset:4 th:TH_ATOMIC_NT_RETURN
; GFX1210-NEXT:    s_wait_xcnt 0x0
; GFX1210-NEXT:    v_mov_b32_e32 v2, 0
; GFX1210-NEXT:    s_wait_loadcnt 0x0
; GFX1210-NEXT:    global_store_b64 v2, v[0:1], s[0:1]
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: struct_buffer_atomic_min_rtn_f64_off4_slc:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    s_clause 0x2
; GFX13-NEXT:    s_load_b96 s[8:10], s[2:3], 0x34
; GFX13-NEXT:    s_load_b128 s[4:7], s[2:3], 0x24
; GFX13-NEXT:    s_load_b64 s[0:1], s[2:3], 0x44
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    v_mov_b64_e32 v[0:1], s[8:9]
; GFX13-NEXT:    v_mov_b32_e32 v2, s10
; GFX13-NEXT:    buffer_atomic_min_num_f64 v[0:1], v2, s[4:7], null idxen offset:4 th:TH_ATOMIC_NT_RETURN
; GFX13-NEXT:    v_mov_b32_e32 v2, 0
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    global_store_b64 v2, v[0:1], s[0:1]
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.struct.buffer.atomic.fmin.f64(double %data, <4 x i32> %rsrc, i32 %vindex, i32 4, i32 0, i32 2)
  store double %ret, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_kernel void @struct_ptr_buffer_atomic_min_noret_f64(ptr addrspace(8) %rsrc, double %data, i32 %vindex) {
; GFX90A-LABEL: struct_ptr_buffer_atomic_min_noret_f64:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX90A-NEXT:    s_load_dword s8, s[2:3], 0x3c
; GFX90A-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX90A-NEXT:    s_waitcnt lgkmcnt(0)
; GFX90A-NEXT:    v_pk_mov_b32 v[0:1], s[0:1], s[0:1] op_sel:[0,1]
; GFX90A-NEXT:    v_mov_b32_e32 v2, s8
; GFX90A-NEXT:    buffer_atomic_min_f64 v[0:1], v2, s[4:7], 0 idxen
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: struct_ptr_buffer_atomic_min_noret_f64:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX940-NEXT:    s_load_dword s8, s[2:3], 0x3c
; GFX940-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX940-NEXT:    s_waitcnt lgkmcnt(0)
; GFX940-NEXT:    v_mov_b64_e32 v[0:1], s[0:1]
; GFX940-NEXT:    v_mov_b32_e32 v2, s8
; GFX940-NEXT:    buffer_atomic_min_f64 v[0:1], v2, s[4:7], 0 idxen
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: struct_ptr_buffer_atomic_min_noret_f64:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    s_load_b96 s[4:6], s[2:3], 0x34
; GFX1210-NEXT:    s_wait_xcnt 0x0
; GFX1210-NEXT:    s_load_b128 s[0:3], s[2:3], 0x24
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    v_mov_b64_e32 v[0:1], s[4:5]
; GFX1210-NEXT:    v_mov_b32_e32 v2, s6
; GFX1210-NEXT:    buffer_atomic_min_num_f64 v[0:1], v2, s[0:3], null idxen
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: struct_ptr_buffer_atomic_min_noret_f64:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    s_clause 0x1
; GFX13-NEXT:    s_load_b96 s[4:6], s[2:3], 0x34
; GFX13-NEXT:    s_load_b128 s[0:3], s[2:3], 0x24
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    v_mov_b64_e32 v[0:1], s[4:5]
; GFX13-NEXT:    v_mov_b32_e32 v2, s6
; GFX13-NEXT:    buffer_atomic_min_num_f64 v[0:1], v2, s[0:3], null idxen
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.struct.ptr.buffer.atomic.fmin.f64(double %data, ptr addrspace(8) %rsrc, i32 %vindex, i32 0, i32 0, i32 0)
  ret void
}

define amdgpu_ps void @struct_ptr_buffer_atomic_min_rtn_f64(ptr addrspace(8) inreg %rsrc, double %data, i32 %vindex) {
; GFX90A-LABEL: struct_ptr_buffer_atomic_min_rtn_f64:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    buffer_atomic_min_f64 v[0:1], v2, s[0:3], 0 idxen glc
; GFX90A-NEXT:    s_waitcnt vmcnt(0)
; GFX90A-NEXT:    flat_store_dwordx2 v[0:1], v[0:1]
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: struct_ptr_buffer_atomic_min_rtn_f64:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    buffer_atomic_min_f64 v[0:1], v2, s[0:3], 0 idxen sc0
; GFX940-NEXT:    s_waitcnt vmcnt(0)
; GFX940-NEXT:    flat_store_dwordx2 v[0:1], v[0:1] sc0 sc1
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: struct_ptr_buffer_atomic_min_rtn_f64:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    buffer_atomic_min_num_f64 v[0:1], v2, s[0:3], null idxen th:TH_ATOMIC_RETURN
; GFX1210-NEXT:    s_wait_loadcnt 0x0
; GFX1210-NEXT:    flat_store_b64 v[0:1], v[0:1]
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: struct_ptr_buffer_atomic_min_rtn_f64:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    buffer_atomic_min_num_f64 v[0:1], v2, s[0:3], null idxen th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    flat_store_b64 v[0:1], v[0:1]
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.struct.ptr.buffer.atomic.fmin.f64(double %data, ptr addrspace(8) %rsrc, i32 %vindex, i32 0, i32 0, i32 0)
  store double %ret, ptr undef
  ret void
}

define amdgpu_kernel void @struct_ptr_buffer_atomic_min_rtn_f64_off4_slc(ptr addrspace(8) %rsrc, double %data, i32 %vindex, ptr addrspace(1) %out) {
; GFX90A-LABEL: struct_ptr_buffer_atomic_min_rtn_f64_off4_slc:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX90A-NEXT:    s_load_dword s10, s[2:3], 0x3c
; GFX90A-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX90A-NEXT:    s_load_dwordx2 s[8:9], s[2:3], 0x44
; GFX90A-NEXT:    s_waitcnt lgkmcnt(0)
; GFX90A-NEXT:    v_pk_mov_b32 v[0:1], s[0:1], s[0:1] op_sel:[0,1]
; GFX90A-NEXT:    v_mov_b32_e32 v2, s10
; GFX90A-NEXT:    buffer_atomic_min_f64 v[0:1], v2, s[4:7], 0 idxen offset:4 glc slc
; GFX90A-NEXT:    v_mov_b32_e32 v2, 0
; GFX90A-NEXT:    s_waitcnt vmcnt(0)
; GFX90A-NEXT:    global_store_dwordx2 v2, v[0:1], s[8:9]
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: struct_ptr_buffer_atomic_min_rtn_f64_off4_slc:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX940-NEXT:    s_load_dword s10, s[2:3], 0x3c
; GFX940-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX940-NEXT:    s_load_dwordx2 s[8:9], s[2:3], 0x44
; GFX940-NEXT:    s_waitcnt lgkmcnt(0)
; GFX940-NEXT:    v_mov_b64_e32 v[0:1], s[0:1]
; GFX940-NEXT:    v_mov_b32_e32 v2, s10
; GFX940-NEXT:    buffer_atomic_min_f64 v[0:1], v2, s[4:7], 0 idxen offset:4 sc0 nt
; GFX940-NEXT:    v_mov_b32_e32 v2, 0
; GFX940-NEXT:    s_waitcnt vmcnt(0)
; GFX940-NEXT:    global_store_dwordx2 v2, v[0:1], s[8:9] sc0 sc1
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: struct_ptr_buffer_atomic_min_rtn_f64_off4_slc:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    s_clause 0x2
; GFX1210-NEXT:    s_load_b96 s[8:10], s[2:3], 0x34
; GFX1210-NEXT:    s_load_b128 s[4:7], s[2:3], 0x24
; GFX1210-NEXT:    s_load_b64 s[0:1], s[2:3], 0x44
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    v_mov_b64_e32 v[0:1], s[8:9]
; GFX1210-NEXT:    v_mov_b32_e32 v2, s10
; GFX1210-NEXT:    buffer_atomic_min_num_f64 v[0:1], v2, s[4:7], null idxen offset:4 th:TH_ATOMIC_NT_RETURN
; GFX1210-NEXT:    s_wait_xcnt 0x0
; GFX1210-NEXT:    v_mov_b32_e32 v2, 0
; GFX1210-NEXT:    s_wait_loadcnt 0x0
; GFX1210-NEXT:    global_store_b64 v2, v[0:1], s[0:1]
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: struct_ptr_buffer_atomic_min_rtn_f64_off4_slc:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    s_clause 0x2
; GFX13-NEXT:    s_load_b96 s[8:10], s[2:3], 0x34
; GFX13-NEXT:    s_load_b128 s[4:7], s[2:3], 0x24
; GFX13-NEXT:    s_load_b64 s[0:1], s[2:3], 0x44
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    v_mov_b64_e32 v[0:1], s[8:9]
; GFX13-NEXT:    v_mov_b32_e32 v2, s10
; GFX13-NEXT:    buffer_atomic_min_num_f64 v[0:1], v2, s[4:7], null idxen offset:4 th:TH_ATOMIC_NT_RETURN
; GFX13-NEXT:    v_mov_b32_e32 v2, 0
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    global_store_b64 v2, v[0:1], s[0:1]
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.struct.ptr.buffer.atomic.fmin.f64(double %data, ptr addrspace(8) %rsrc, i32 %vindex, i32 4, i32 0, i32 2)
  store double %ret, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_kernel void @raw_buffer_atomic_max_noret_f64(<4 x i32> %rsrc, double %data, i32 %vindex) {
; GFX90A-LABEL: raw_buffer_atomic_max_noret_f64:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX90A-NEXT:    s_load_dword s8, s[2:3], 0x3c
; GFX90A-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX90A-NEXT:    s_waitcnt lgkmcnt(0)
; GFX90A-NEXT:    v_pk_mov_b32 v[0:1], s[0:1], s[0:1] op_sel:[0,1]
; GFX90A-NEXT:    v_mov_b32_e32 v2, s8
; GFX90A-NEXT:    buffer_atomic_max_f64 v[0:1], v2, s[4:7], 0 offen
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: raw_buffer_atomic_max_noret_f64:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX940-NEXT:    s_load_dword s8, s[2:3], 0x3c
; GFX940-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX940-NEXT:    s_waitcnt lgkmcnt(0)
; GFX940-NEXT:    v_mov_b64_e32 v[0:1], s[0:1]
; GFX940-NEXT:    v_mov_b32_e32 v2, s8
; GFX940-NEXT:    buffer_atomic_max_f64 v[0:1], v2, s[4:7], 0 offen
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: raw_buffer_atomic_max_noret_f64:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    s_load_b96 s[4:6], s[2:3], 0x34
; GFX1210-NEXT:    s_wait_xcnt 0x0
; GFX1210-NEXT:    s_load_b128 s[0:3], s[2:3], 0x24
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    v_mov_b64_e32 v[0:1], s[4:5]
; GFX1210-NEXT:    v_mov_b32_e32 v2, s6
; GFX1210-NEXT:    buffer_atomic_max_num_f64 v[0:1], v2, s[0:3], null offen
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: raw_buffer_atomic_max_noret_f64:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    s_clause 0x1
; GFX13-NEXT:    s_load_b96 s[4:6], s[2:3], 0x34
; GFX13-NEXT:    s_load_b128 s[0:3], s[2:3], 0x24
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    v_mov_b64_e32 v[0:1], s[4:5]
; GFX13-NEXT:    v_mov_b32_e32 v2, s6
; GFX13-NEXT:    buffer_atomic_max_num_f64 v[0:1], v2, s[0:3], null offen
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.raw.buffer.atomic.fmax.f64(double %data, <4 x i32> %rsrc, i32 %vindex, i32 0, i32 0)
  ret void
}

define amdgpu_ps void @raw_buffer_atomic_max_rtn_f64(<4 x i32> inreg %rsrc, double %data, i32 %vindex) {
; GFX90A-LABEL: raw_buffer_atomic_max_rtn_f64:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    buffer_atomic_max_f64 v[0:1], v2, s[0:3], 0 offen glc
; GFX90A-NEXT:    s_waitcnt vmcnt(0)
; GFX90A-NEXT:    flat_store_dwordx2 v[0:1], v[0:1]
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: raw_buffer_atomic_max_rtn_f64:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    buffer_atomic_max_f64 v[0:1], v2, s[0:3], 0 offen sc0
; GFX940-NEXT:    s_waitcnt vmcnt(0)
; GFX940-NEXT:    flat_store_dwordx2 v[0:1], v[0:1] sc0 sc1
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: raw_buffer_atomic_max_rtn_f64:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    buffer_atomic_max_num_f64 v[0:1], v2, s[0:3], null offen th:TH_ATOMIC_RETURN
; GFX1210-NEXT:    s_wait_loadcnt 0x0
; GFX1210-NEXT:    flat_store_b64 v[0:1], v[0:1]
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: raw_buffer_atomic_max_rtn_f64:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    buffer_atomic_max_num_f64 v[0:1], v2, s[0:3], null offen th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    flat_store_b64 v[0:1], v[0:1]
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.raw.buffer.atomic.fmax.f64(double %data, <4 x i32> %rsrc, i32 %vindex, i32 0, i32 0)
  store double %ret, ptr undef
  ret void
}

define amdgpu_kernel void @raw_buffer_atomic_max_rtn_f64_off4_slc(<4 x i32> %rsrc, double %data, i32 %vindex, ptr addrspace(1) %out) {
; GFX90A-LABEL: raw_buffer_atomic_max_rtn_f64_off4_slc:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX90A-NEXT:    s_load_dword s10, s[2:3], 0x3c
; GFX90A-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX90A-NEXT:    s_load_dwordx2 s[8:9], s[2:3], 0x44
; GFX90A-NEXT:    s_waitcnt lgkmcnt(0)
; GFX90A-NEXT:    v_pk_mov_b32 v[0:1], s[0:1], s[0:1] op_sel:[0,1]
; GFX90A-NEXT:    v_mov_b32_e32 v2, s10
; GFX90A-NEXT:    buffer_atomic_max_f64 v[0:1], v2, s[4:7], 4 offen glc slc
; GFX90A-NEXT:    v_mov_b32_e32 v2, 0
; GFX90A-NEXT:    s_waitcnt vmcnt(0)
; GFX90A-NEXT:    global_store_dwordx2 v2, v[0:1], s[8:9]
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: raw_buffer_atomic_max_rtn_f64_off4_slc:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX940-NEXT:    s_load_dword s10, s[2:3], 0x3c
; GFX940-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX940-NEXT:    s_load_dwordx2 s[8:9], s[2:3], 0x44
; GFX940-NEXT:    s_waitcnt lgkmcnt(0)
; GFX940-NEXT:    v_mov_b64_e32 v[0:1], s[0:1]
; GFX940-NEXT:    v_mov_b32_e32 v2, s10
; GFX940-NEXT:    buffer_atomic_max_f64 v[0:1], v2, s[4:7], 4 offen sc0 nt
; GFX940-NEXT:    v_mov_b32_e32 v2, 0
; GFX940-NEXT:    s_waitcnt vmcnt(0)
; GFX940-NEXT:    global_store_dwordx2 v2, v[0:1], s[8:9] sc0 sc1
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: raw_buffer_atomic_max_rtn_f64_off4_slc:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    s_clause 0x1
; GFX1210-NEXT:    s_load_b96 s[8:10], s[2:3], 0x34
; GFX1210-NEXT:    s_load_b128 s[4:7], s[2:3], 0x24
; GFX1210-NEXT:    s_mov_b32 s0, 4
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    v_mov_b64_e32 v[0:1], s[8:9]
; GFX1210-NEXT:    v_mov_b32_e32 v2, s10
; GFX1210-NEXT:    buffer_atomic_max_num_f64 v[0:1], v2, s[4:7], s0 offen th:TH_ATOMIC_NT_RETURN
; GFX1210-NEXT:    s_wait_xcnt 0x0
; GFX1210-NEXT:    s_load_b64 s[0:1], s[2:3], 0x44
; GFX1210-NEXT:    v_mov_b32_e32 v2, 0
; GFX1210-NEXT:    s_wait_loadcnt 0x0
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    global_store_b64 v2, v[0:1], s[0:1]
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: raw_buffer_atomic_max_rtn_f64_off4_slc:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    s_clause 0x1
; GFX13-NEXT:    s_load_b96 s[8:10], s[2:3], 0x34
; GFX13-NEXT:    s_load_b128 s[4:7], s[2:3], 0x24
; GFX13-NEXT:    s_mov_b32 s0, 4
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    v_mov_b64_e32 v[0:1], s[8:9]
; GFX13-NEXT:    v_mov_b32_e32 v2, s10
; GFX13-NEXT:    buffer_atomic_max_num_f64 v[0:1], v2, s[4:7], s0 offen th:TH_ATOMIC_NT_RETURN
; GFX13-NEXT:    s_load_b64 s[0:1], s[2:3], 0x44
; GFX13-NEXT:    v_mov_b32_e32 v2, 0
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    global_store_b64 v2, v[0:1], s[0:1]
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.raw.buffer.atomic.fmax.f64(double %data, <4 x i32> %rsrc, i32 %vindex, i32 4, i32 2)
  store double %ret, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_kernel void @raw_ptr_buffer_atomic_max_noret_f64(ptr addrspace(8) %rsrc, double %data, i32 %vindex) {
; GFX90A-LABEL: raw_ptr_buffer_atomic_max_noret_f64:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX90A-NEXT:    s_load_dword s8, s[2:3], 0x3c
; GFX90A-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX90A-NEXT:    s_waitcnt lgkmcnt(0)
; GFX90A-NEXT:    v_pk_mov_b32 v[0:1], s[0:1], s[0:1] op_sel:[0,1]
; GFX90A-NEXT:    v_mov_b32_e32 v2, s8
; GFX90A-NEXT:    buffer_atomic_max_f64 v[0:1], v2, s[4:7], 0 offen
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: raw_ptr_buffer_atomic_max_noret_f64:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX940-NEXT:    s_load_dword s8, s[2:3], 0x3c
; GFX940-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX940-NEXT:    s_waitcnt lgkmcnt(0)
; GFX940-NEXT:    v_mov_b64_e32 v[0:1], s[0:1]
; GFX940-NEXT:    v_mov_b32_e32 v2, s8
; GFX940-NEXT:    buffer_atomic_max_f64 v[0:1], v2, s[4:7], 0 offen
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: raw_ptr_buffer_atomic_max_noret_f64:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    s_load_b96 s[4:6], s[2:3], 0x34
; GFX1210-NEXT:    s_wait_xcnt 0x0
; GFX1210-NEXT:    s_load_b128 s[0:3], s[2:3], 0x24
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    v_mov_b64_e32 v[0:1], s[4:5]
; GFX1210-NEXT:    v_mov_b32_e32 v2, s6
; GFX1210-NEXT:    buffer_atomic_max_num_f64 v[0:1], v2, s[0:3], null offen
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: raw_ptr_buffer_atomic_max_noret_f64:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    s_clause 0x1
; GFX13-NEXT:    s_load_b96 s[4:6], s[2:3], 0x34
; GFX13-NEXT:    s_load_b128 s[0:3], s[2:3], 0x24
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    v_mov_b64_e32 v[0:1], s[4:5]
; GFX13-NEXT:    v_mov_b32_e32 v2, s6
; GFX13-NEXT:    buffer_atomic_max_num_f64 v[0:1], v2, s[0:3], null offen
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.raw.ptr.buffer.atomic.fmax.f64(double %data, ptr addrspace(8) %rsrc, i32 %vindex, i32 0, i32 0)
  ret void
}

define amdgpu_ps void @raw_ptr_buffer_atomic_max_rtn_f64(ptr addrspace(8) inreg %rsrc, double %data, i32 %vindex) {
; GFX90A-LABEL: raw_ptr_buffer_atomic_max_rtn_f64:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    buffer_atomic_max_f64 v[0:1], v2, s[0:3], 0 offen glc
; GFX90A-NEXT:    s_waitcnt vmcnt(0)
; GFX90A-NEXT:    flat_store_dwordx2 v[0:1], v[0:1]
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: raw_ptr_buffer_atomic_max_rtn_f64:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    buffer_atomic_max_f64 v[0:1], v2, s[0:3], 0 offen sc0
; GFX940-NEXT:    s_waitcnt vmcnt(0)
; GFX940-NEXT:    flat_store_dwordx2 v[0:1], v[0:1] sc0 sc1
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: raw_ptr_buffer_atomic_max_rtn_f64:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    buffer_atomic_max_num_f64 v[0:1], v2, s[0:3], null offen th:TH_ATOMIC_RETURN
; GFX1210-NEXT:    s_wait_loadcnt 0x0
; GFX1210-NEXT:    flat_store_b64 v[0:1], v[0:1]
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: raw_ptr_buffer_atomic_max_rtn_f64:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    buffer_atomic_max_num_f64 v[0:1], v2, s[0:3], null offen th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    flat_store_b64 v[0:1], v[0:1]
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.raw.ptr.buffer.atomic.fmax.f64(double %data, ptr addrspace(8) %rsrc, i32 %vindex, i32 0, i32 0)
  store double %ret, ptr undef
  ret void
}

define amdgpu_kernel void @raw_ptr_buffer_atomic_max_rtn_f64_off4_slc(ptr addrspace(8) %rsrc, double %data, i32 %vindex, ptr addrspace(1) %out) {
; GFX90A-LABEL: raw_ptr_buffer_atomic_max_rtn_f64_off4_slc:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX90A-NEXT:    s_load_dword s10, s[2:3], 0x3c
; GFX90A-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX90A-NEXT:    s_load_dwordx2 s[8:9], s[2:3], 0x44
; GFX90A-NEXT:    s_waitcnt lgkmcnt(0)
; GFX90A-NEXT:    v_pk_mov_b32 v[0:1], s[0:1], s[0:1] op_sel:[0,1]
; GFX90A-NEXT:    v_mov_b32_e32 v2, s10
; GFX90A-NEXT:    buffer_atomic_max_f64 v[0:1], v2, s[4:7], 4 offen glc slc
; GFX90A-NEXT:    v_mov_b32_e32 v2, 0
; GFX90A-NEXT:    s_waitcnt vmcnt(0)
; GFX90A-NEXT:    global_store_dwordx2 v2, v[0:1], s[8:9]
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: raw_ptr_buffer_atomic_max_rtn_f64_off4_slc:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX940-NEXT:    s_load_dword s10, s[2:3], 0x3c
; GFX940-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX940-NEXT:    s_load_dwordx2 s[8:9], s[2:3], 0x44
; GFX940-NEXT:    s_waitcnt lgkmcnt(0)
; GFX940-NEXT:    v_mov_b64_e32 v[0:1], s[0:1]
; GFX940-NEXT:    v_mov_b32_e32 v2, s10
; GFX940-NEXT:    buffer_atomic_max_f64 v[0:1], v2, s[4:7], 4 offen sc0 nt
; GFX940-NEXT:    v_mov_b32_e32 v2, 0
; GFX940-NEXT:    s_waitcnt vmcnt(0)
; GFX940-NEXT:    global_store_dwordx2 v2, v[0:1], s[8:9] sc0 sc1
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: raw_ptr_buffer_atomic_max_rtn_f64_off4_slc:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    s_clause 0x1
; GFX1210-NEXT:    s_load_b96 s[8:10], s[2:3], 0x34
; GFX1210-NEXT:    s_load_b128 s[4:7], s[2:3], 0x24
; GFX1210-NEXT:    s_mov_b32 s0, 4
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    v_mov_b64_e32 v[0:1], s[8:9]
; GFX1210-NEXT:    v_mov_b32_e32 v2, s10
; GFX1210-NEXT:    buffer_atomic_max_num_f64 v[0:1], v2, s[4:7], s0 offen th:TH_ATOMIC_NT_RETURN
; GFX1210-NEXT:    s_wait_xcnt 0x0
; GFX1210-NEXT:    s_load_b64 s[0:1], s[2:3], 0x44
; GFX1210-NEXT:    v_mov_b32_e32 v2, 0
; GFX1210-NEXT:    s_wait_loadcnt 0x0
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    global_store_b64 v2, v[0:1], s[0:1]
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: raw_ptr_buffer_atomic_max_rtn_f64_off4_slc:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    s_clause 0x1
; GFX13-NEXT:    s_load_b96 s[8:10], s[2:3], 0x34
; GFX13-NEXT:    s_load_b128 s[4:7], s[2:3], 0x24
; GFX13-NEXT:    s_mov_b32 s0, 4
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    v_mov_b64_e32 v[0:1], s[8:9]
; GFX13-NEXT:    v_mov_b32_e32 v2, s10
; GFX13-NEXT:    buffer_atomic_max_num_f64 v[0:1], v2, s[4:7], s0 offen th:TH_ATOMIC_NT_RETURN
; GFX13-NEXT:    s_load_b64 s[0:1], s[2:3], 0x44
; GFX13-NEXT:    v_mov_b32_e32 v2, 0
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    global_store_b64 v2, v[0:1], s[0:1]
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.raw.ptr.buffer.atomic.fmax.f64(double %data, ptr addrspace(8) %rsrc, i32 %vindex, i32 4, i32 2)
  store double %ret, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_kernel void @struct_buffer_atomic_max_noret_f64(<4 x i32> %rsrc, double %data, i32 %vindex) {
; GFX90A-LABEL: struct_buffer_atomic_max_noret_f64:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX90A-NEXT:    s_load_dword s8, s[2:3], 0x3c
; GFX90A-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX90A-NEXT:    s_waitcnt lgkmcnt(0)
; GFX90A-NEXT:    v_pk_mov_b32 v[0:1], s[0:1], s[0:1] op_sel:[0,1]
; GFX90A-NEXT:    v_mov_b32_e32 v2, s8
; GFX90A-NEXT:    buffer_atomic_max_f64 v[0:1], v2, s[4:7], 0 idxen
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: struct_buffer_atomic_max_noret_f64:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX940-NEXT:    s_load_dword s8, s[2:3], 0x3c
; GFX940-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX940-NEXT:    s_waitcnt lgkmcnt(0)
; GFX940-NEXT:    v_mov_b64_e32 v[0:1], s[0:1]
; GFX940-NEXT:    v_mov_b32_e32 v2, s8
; GFX940-NEXT:    buffer_atomic_max_f64 v[0:1], v2, s[4:7], 0 idxen
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: struct_buffer_atomic_max_noret_f64:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    s_load_b96 s[4:6], s[2:3], 0x34
; GFX1210-NEXT:    s_wait_xcnt 0x0
; GFX1210-NEXT:    s_load_b128 s[0:3], s[2:3], 0x24
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    v_mov_b64_e32 v[0:1], s[4:5]
; GFX1210-NEXT:    v_mov_b32_e32 v2, s6
; GFX1210-NEXT:    buffer_atomic_max_num_f64 v[0:1], v2, s[0:3], null idxen
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: struct_buffer_atomic_max_noret_f64:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    s_clause 0x1
; GFX13-NEXT:    s_load_b96 s[4:6], s[2:3], 0x34
; GFX13-NEXT:    s_load_b128 s[0:3], s[2:3], 0x24
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    v_mov_b64_e32 v[0:1], s[4:5]
; GFX13-NEXT:    v_mov_b32_e32 v2, s6
; GFX13-NEXT:    buffer_atomic_max_num_f64 v[0:1], v2, s[0:3], null idxen
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.struct.buffer.atomic.fmax.f64(double %data, <4 x i32> %rsrc, i32 %vindex, i32 0, i32 0, i32 0)
  ret void
}

define amdgpu_ps void @struct_buffer_atomic_max_rtn_f64(<4 x i32> inreg %rsrc, double %data, i32 %vindex) {
; GFX90A-LABEL: struct_buffer_atomic_max_rtn_f64:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    buffer_atomic_max_f64 v[0:1], v2, s[0:3], 0 idxen glc
; GFX90A-NEXT:    s_waitcnt vmcnt(0)
; GFX90A-NEXT:    flat_store_dwordx2 v[0:1], v[0:1]
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: struct_buffer_atomic_max_rtn_f64:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    buffer_atomic_max_f64 v[0:1], v2, s[0:3], 0 idxen sc0
; GFX940-NEXT:    s_waitcnt vmcnt(0)
; GFX940-NEXT:    flat_store_dwordx2 v[0:1], v[0:1] sc0 sc1
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: struct_buffer_atomic_max_rtn_f64:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    buffer_atomic_max_num_f64 v[0:1], v2, s[0:3], null idxen th:TH_ATOMIC_RETURN
; GFX1210-NEXT:    s_wait_loadcnt 0x0
; GFX1210-NEXT:    flat_store_b64 v[0:1], v[0:1]
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: struct_buffer_atomic_max_rtn_f64:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    buffer_atomic_max_num_f64 v[0:1], v2, s[0:3], null idxen th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    flat_store_b64 v[0:1], v[0:1]
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.struct.buffer.atomic.fmax.f64(double %data, <4 x i32> %rsrc, i32 %vindex, i32 0, i32 0, i32 0)
  store double %ret, ptr undef
  ret void
}

define amdgpu_kernel void @struct_buffer_atomic_max_rtn_f64_off4_slc(<4 x i32> %rsrc, double %data, i32 %vindex, ptr addrspace(1) %out) {
; GFX90A-LABEL: struct_buffer_atomic_max_rtn_f64_off4_slc:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX90A-NEXT:    s_load_dword s10, s[2:3], 0x3c
; GFX90A-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX90A-NEXT:    s_load_dwordx2 s[8:9], s[2:3], 0x44
; GFX90A-NEXT:    s_waitcnt lgkmcnt(0)
; GFX90A-NEXT:    v_pk_mov_b32 v[0:1], s[0:1], s[0:1] op_sel:[0,1]
; GFX90A-NEXT:    v_mov_b32_e32 v2, s10
; GFX90A-NEXT:    buffer_atomic_max_f64 v[0:1], v2, s[4:7], 0 idxen offset:4 glc slc
; GFX90A-NEXT:    v_mov_b32_e32 v2, 0
; GFX90A-NEXT:    s_waitcnt vmcnt(0)
; GFX90A-NEXT:    global_store_dwordx2 v2, v[0:1], s[8:9]
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: struct_buffer_atomic_max_rtn_f64_off4_slc:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX940-NEXT:    s_load_dword s10, s[2:3], 0x3c
; GFX940-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX940-NEXT:    s_load_dwordx2 s[8:9], s[2:3], 0x44
; GFX940-NEXT:    s_waitcnt lgkmcnt(0)
; GFX940-NEXT:    v_mov_b64_e32 v[0:1], s[0:1]
; GFX940-NEXT:    v_mov_b32_e32 v2, s10
; GFX940-NEXT:    buffer_atomic_max_f64 v[0:1], v2, s[4:7], 0 idxen offset:4 sc0 nt
; GFX940-NEXT:    v_mov_b32_e32 v2, 0
; GFX940-NEXT:    s_waitcnt vmcnt(0)
; GFX940-NEXT:    global_store_dwordx2 v2, v[0:1], s[8:9] sc0 sc1
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: struct_buffer_atomic_max_rtn_f64_off4_slc:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    s_clause 0x2
; GFX1210-NEXT:    s_load_b96 s[8:10], s[2:3], 0x34
; GFX1210-NEXT:    s_load_b128 s[4:7], s[2:3], 0x24
; GFX1210-NEXT:    s_load_b64 s[0:1], s[2:3], 0x44
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    v_mov_b64_e32 v[0:1], s[8:9]
; GFX1210-NEXT:    v_mov_b32_e32 v2, s10
; GFX1210-NEXT:    buffer_atomic_max_num_f64 v[0:1], v2, s[4:7], null idxen offset:4 th:TH_ATOMIC_NT_RETURN
; GFX1210-NEXT:    s_wait_xcnt 0x0
; GFX1210-NEXT:    v_mov_b32_e32 v2, 0
; GFX1210-NEXT:    s_wait_loadcnt 0x0
; GFX1210-NEXT:    global_store_b64 v2, v[0:1], s[0:1]
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: struct_buffer_atomic_max_rtn_f64_off4_slc:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    s_clause 0x2
; GFX13-NEXT:    s_load_b96 s[8:10], s[2:3], 0x34
; GFX13-NEXT:    s_load_b128 s[4:7], s[2:3], 0x24
; GFX13-NEXT:    s_load_b64 s[0:1], s[2:3], 0x44
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    v_mov_b64_e32 v[0:1], s[8:9]
; GFX13-NEXT:    v_mov_b32_e32 v2, s10
; GFX13-NEXT:    buffer_atomic_max_num_f64 v[0:1], v2, s[4:7], null idxen offset:4 th:TH_ATOMIC_NT_RETURN
; GFX13-NEXT:    v_mov_b32_e32 v2, 0
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    global_store_b64 v2, v[0:1], s[0:1]
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.struct.buffer.atomic.fmax.f64(double %data, <4 x i32> %rsrc, i32 %vindex, i32 4, i32 0, i32 2)
  store double %ret, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_kernel void @struct_ptr_buffer_atomic_max_noret_f64(ptr addrspace(8) %rsrc, double %data, i32 %vindex) {
; GFX90A-LABEL: struct_ptr_buffer_atomic_max_noret_f64:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX90A-NEXT:    s_load_dword s8, s[2:3], 0x3c
; GFX90A-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX90A-NEXT:    s_waitcnt lgkmcnt(0)
; GFX90A-NEXT:    v_pk_mov_b32 v[0:1], s[0:1], s[0:1] op_sel:[0,1]
; GFX90A-NEXT:    v_mov_b32_e32 v2, s8
; GFX90A-NEXT:    buffer_atomic_max_f64 v[0:1], v2, s[4:7], 0 idxen
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: struct_ptr_buffer_atomic_max_noret_f64:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX940-NEXT:    s_load_dword s8, s[2:3], 0x3c
; GFX940-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX940-NEXT:    s_waitcnt lgkmcnt(0)
; GFX940-NEXT:    v_mov_b64_e32 v[0:1], s[0:1]
; GFX940-NEXT:    v_mov_b32_e32 v2, s8
; GFX940-NEXT:    buffer_atomic_max_f64 v[0:1], v2, s[4:7], 0 idxen
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: struct_ptr_buffer_atomic_max_noret_f64:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    s_load_b96 s[4:6], s[2:3], 0x34
; GFX1210-NEXT:    s_wait_xcnt 0x0
; GFX1210-NEXT:    s_load_b128 s[0:3], s[2:3], 0x24
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    v_mov_b64_e32 v[0:1], s[4:5]
; GFX1210-NEXT:    v_mov_b32_e32 v2, s6
; GFX1210-NEXT:    buffer_atomic_max_num_f64 v[0:1], v2, s[0:3], null idxen
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: struct_ptr_buffer_atomic_max_noret_f64:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    s_clause 0x1
; GFX13-NEXT:    s_load_b96 s[4:6], s[2:3], 0x34
; GFX13-NEXT:    s_load_b128 s[0:3], s[2:3], 0x24
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    v_mov_b64_e32 v[0:1], s[4:5]
; GFX13-NEXT:    v_mov_b32_e32 v2, s6
; GFX13-NEXT:    buffer_atomic_max_num_f64 v[0:1], v2, s[0:3], null idxen
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.struct.ptr.buffer.atomic.fmax.f64(double %data, ptr addrspace(8) %rsrc, i32 %vindex, i32 0, i32 0, i32 0)
  ret void
}

define amdgpu_ps void @struct_ptr_buffer_atomic_max_rtn_f64(ptr addrspace(8) inreg %rsrc, double %data, i32 %vindex) {
; GFX90A-LABEL: struct_ptr_buffer_atomic_max_rtn_f64:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    buffer_atomic_max_f64 v[0:1], v2, s[0:3], 0 idxen glc
; GFX90A-NEXT:    s_waitcnt vmcnt(0)
; GFX90A-NEXT:    flat_store_dwordx2 v[0:1], v[0:1]
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: struct_ptr_buffer_atomic_max_rtn_f64:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    buffer_atomic_max_f64 v[0:1], v2, s[0:3], 0 idxen sc0
; GFX940-NEXT:    s_waitcnt vmcnt(0)
; GFX940-NEXT:    flat_store_dwordx2 v[0:1], v[0:1] sc0 sc1
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: struct_ptr_buffer_atomic_max_rtn_f64:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    buffer_atomic_max_num_f64 v[0:1], v2, s[0:3], null idxen th:TH_ATOMIC_RETURN
; GFX1210-NEXT:    s_wait_loadcnt 0x0
; GFX1210-NEXT:    flat_store_b64 v[0:1], v[0:1]
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: struct_ptr_buffer_atomic_max_rtn_f64:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    buffer_atomic_max_num_f64 v[0:1], v2, s[0:3], null idxen th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    flat_store_b64 v[0:1], v[0:1]
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.struct.ptr.buffer.atomic.fmax.f64(double %data, ptr addrspace(8) %rsrc, i32 %vindex, i32 0, i32 0, i32 0)
  store double %ret, ptr undef
  ret void
}

define amdgpu_kernel void @struct_ptr_buffer_atomic_max_rtn_f64_off4_slc(ptr addrspace(8) %rsrc, double %data, i32 %vindex, ptr addrspace(1) %out) {
; GFX90A-LABEL: struct_ptr_buffer_atomic_max_rtn_f64_off4_slc:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX90A-NEXT:    s_load_dword s10, s[2:3], 0x3c
; GFX90A-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX90A-NEXT:    s_load_dwordx2 s[8:9], s[2:3], 0x44
; GFX90A-NEXT:    s_waitcnt lgkmcnt(0)
; GFX90A-NEXT:    v_pk_mov_b32 v[0:1], s[0:1], s[0:1] op_sel:[0,1]
; GFX90A-NEXT:    v_mov_b32_e32 v2, s10
; GFX90A-NEXT:    buffer_atomic_max_f64 v[0:1], v2, s[4:7], 0 idxen offset:4 glc slc
; GFX90A-NEXT:    v_mov_b32_e32 v2, 0
; GFX90A-NEXT:    s_waitcnt vmcnt(0)
; GFX90A-NEXT:    global_store_dwordx2 v2, v[0:1], s[8:9]
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: struct_ptr_buffer_atomic_max_rtn_f64_off4_slc:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    s_load_dwordx2 s[0:1], s[2:3], 0x34
; GFX940-NEXT:    s_load_dword s10, s[2:3], 0x3c
; GFX940-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX940-NEXT:    s_load_dwordx2 s[8:9], s[2:3], 0x44
; GFX940-NEXT:    s_waitcnt lgkmcnt(0)
; GFX940-NEXT:    v_mov_b64_e32 v[0:1], s[0:1]
; GFX940-NEXT:    v_mov_b32_e32 v2, s10
; GFX940-NEXT:    buffer_atomic_max_f64 v[0:1], v2, s[4:7], 0 idxen offset:4 sc0 nt
; GFX940-NEXT:    v_mov_b32_e32 v2, 0
; GFX940-NEXT:    s_waitcnt vmcnt(0)
; GFX940-NEXT:    global_store_dwordx2 v2, v[0:1], s[8:9] sc0 sc1
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: struct_ptr_buffer_atomic_max_rtn_f64_off4_slc:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    s_clause 0x2
; GFX1210-NEXT:    s_load_b96 s[8:10], s[2:3], 0x34
; GFX1210-NEXT:    s_load_b128 s[4:7], s[2:3], 0x24
; GFX1210-NEXT:    s_load_b64 s[0:1], s[2:3], 0x44
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    v_mov_b64_e32 v[0:1], s[8:9]
; GFX1210-NEXT:    v_mov_b32_e32 v2, s10
; GFX1210-NEXT:    buffer_atomic_max_num_f64 v[0:1], v2, s[4:7], null idxen offset:4 th:TH_ATOMIC_NT_RETURN
; GFX1210-NEXT:    s_wait_xcnt 0x0
; GFX1210-NEXT:    v_mov_b32_e32 v2, 0
; GFX1210-NEXT:    s_wait_loadcnt 0x0
; GFX1210-NEXT:    global_store_b64 v2, v[0:1], s[0:1]
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: struct_ptr_buffer_atomic_max_rtn_f64_off4_slc:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    s_clause 0x2
; GFX13-NEXT:    s_load_b96 s[8:10], s[2:3], 0x34
; GFX13-NEXT:    s_load_b128 s[4:7], s[2:3], 0x24
; GFX13-NEXT:    s_load_b64 s[0:1], s[2:3], 0x44
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    v_mov_b64_e32 v[0:1], s[8:9]
; GFX13-NEXT:    v_mov_b32_e32 v2, s10
; GFX13-NEXT:    buffer_atomic_max_num_f64 v[0:1], v2, s[4:7], null idxen offset:4 th:TH_ATOMIC_NT_RETURN
; GFX13-NEXT:    v_mov_b32_e32 v2, 0
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    global_store_b64 v2, v[0:1], s[0:1]
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.struct.ptr.buffer.atomic.fmax.f64(double %data, ptr addrspace(8) %rsrc, i32 %vindex, i32 4, i32 0, i32 2)
  store double %ret, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_kernel void @global_atomic_fmin_f64_noret(ptr addrspace(1) %ptr, double %data) {
; GFX90A-LABEL: global_atomic_fmin_f64_noret:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX90A-NEXT:    v_mov_b32_e32 v2, 0
; GFX90A-NEXT:    s_waitcnt lgkmcnt(0)
; GFX90A-NEXT:    v_mov_b32_e32 v0, s6
; GFX90A-NEXT:    v_mov_b32_e32 v1, s7
; GFX90A-NEXT:    global_atomic_min_f64 v2, v[0:1], s[4:5]
; GFX90A-NEXT:    s_waitcnt vmcnt(0)
; GFX90A-NEXT:    buffer_wbinvl1_vol
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: global_atomic_fmin_f64_noret:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX940-NEXT:    v_mov_b32_e32 v2, 0
; GFX940-NEXT:    s_waitcnt lgkmcnt(0)
; GFX940-NEXT:    v_mov_b32_e32 v0, s6
; GFX940-NEXT:    v_mov_b32_e32 v1, s7
; GFX940-NEXT:    buffer_wbl2 sc1
; GFX940-NEXT:    global_atomic_min_f64 v2, v[0:1], s[4:5]
; GFX940-NEXT:    s_waitcnt vmcnt(0)
; GFX940-NEXT:    buffer_inv sc1
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: global_atomic_fmin_f64_noret:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    s_load_b128 s[0:3], s[2:3], 0x24
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    v_dual_mov_b32 v2, 0 :: v_dual_mov_b32 v0, s2
; GFX1210-NEXT:    v_mov_b32_e32 v1, s3
; GFX1210-NEXT:    global_wb scope:SCOPE_DEV
; GFX1210-NEXT:    global_atomic_min_num_f64 v2, v[0:1], s[0:1] scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_storecnt 0x0
; GFX1210-NEXT:    global_inv scope:SCOPE_DEV
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: global_atomic_fmin_f64_noret:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    s_load_b128 s[0:3], s[2:3], 0x24
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    v_dual_mov_b32 v2, 0 :: v_dual_mov_b32 v0, s2
; GFX13-NEXT:    v_mov_b32_e32 v1, s3
; GFX13-NEXT:    global_wb scope:SCOPE_DEV
; GFX13-NEXT:    global_atomic_min_num_f64 v2, v[0:1], s[0:1] scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_storecnt 0x0
; GFX13-NEXT:    global_inv scope:SCOPE_DEV
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.global.atomic.fmin.f64.p1.f64(ptr addrspace(1) %ptr, double %data)
  ret void
}

define amdgpu_kernel void @global_atomic_fmax_f64_noret(ptr addrspace(1) %ptr, double %data) {
; GFX90A-LABEL: global_atomic_fmax_f64_noret:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX90A-NEXT:    v_mov_b32_e32 v2, 0
; GFX90A-NEXT:    s_waitcnt lgkmcnt(0)
; GFX90A-NEXT:    v_mov_b32_e32 v0, s6
; GFX90A-NEXT:    v_mov_b32_e32 v1, s7
; GFX90A-NEXT:    global_atomic_max_f64 v2, v[0:1], s[4:5]
; GFX90A-NEXT:    s_waitcnt vmcnt(0)
; GFX90A-NEXT:    buffer_wbinvl1_vol
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: global_atomic_fmax_f64_noret:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX940-NEXT:    v_mov_b32_e32 v2, 0
; GFX940-NEXT:    s_waitcnt lgkmcnt(0)
; GFX940-NEXT:    v_mov_b32_e32 v0, s6
; GFX940-NEXT:    v_mov_b32_e32 v1, s7
; GFX940-NEXT:    buffer_wbl2 sc1
; GFX940-NEXT:    global_atomic_max_f64 v2, v[0:1], s[4:5]
; GFX940-NEXT:    s_waitcnt vmcnt(0)
; GFX940-NEXT:    buffer_inv sc1
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: global_atomic_fmax_f64_noret:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    s_load_b128 s[0:3], s[2:3], 0x24
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    v_dual_mov_b32 v2, 0 :: v_dual_mov_b32 v0, s2
; GFX1210-NEXT:    v_mov_b32_e32 v1, s3
; GFX1210-NEXT:    global_wb scope:SCOPE_DEV
; GFX1210-NEXT:    global_atomic_max_num_f64 v2, v[0:1], s[0:1] scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_storecnt 0x0
; GFX1210-NEXT:    global_inv scope:SCOPE_DEV
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: global_atomic_fmax_f64_noret:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    s_load_b128 s[0:3], s[2:3], 0x24
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    v_dual_mov_b32 v2, 0 :: v_dual_mov_b32 v0, s2
; GFX13-NEXT:    v_mov_b32_e32 v1, s3
; GFX13-NEXT:    global_wb scope:SCOPE_DEV
; GFX13-NEXT:    global_atomic_max_num_f64 v2, v[0:1], s[0:1] scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_storecnt 0x0
; GFX13-NEXT:    global_inv scope:SCOPE_DEV
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.global.atomic.fmax.f64.p1.f64(ptr addrspace(1) %ptr, double %data)
  ret void
}

define double @global_atomic_fmax_f64_rtn(ptr addrspace(1) %ptr, double %data) {
; GFX90A-LABEL: global_atomic_fmax_f64_rtn:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX90A-NEXT:    global_atomic_max_f64 v[0:1], v[0:1], v[2:3], off glc
; GFX90A-NEXT:    s_waitcnt vmcnt(0)
; GFX90A-NEXT:    buffer_wbinvl1_vol
; GFX90A-NEXT:    s_setpc_b64 s[30:31]
;
; GFX940-LABEL: global_atomic_fmax_f64_rtn:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX940-NEXT:    buffer_wbl2 sc1
; GFX940-NEXT:    global_atomic_max_f64 v[0:1], v[0:1], v[2:3], off sc0
; GFX940-NEXT:    s_waitcnt vmcnt(0)
; GFX940-NEXT:    buffer_inv sc1
; GFX940-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1210-LABEL: global_atomic_fmax_f64_rtn:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    global_wb scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_storecnt 0x0
; GFX1210-NEXT:    global_atomic_max_num_f64 v[0:1], v[0:1], v[2:3], off th:TH_ATOMIC_RETURN scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_loadcnt 0x0
; GFX1210-NEXT:    global_inv scope:SCOPE_DEV
; GFX1210-NEXT:    s_set_pc_i64 s[30:31]
;
; GFX13-LABEL: global_atomic_fmax_f64_rtn:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX13-NEXT:    s_wait_expcnt 0x0
; GFX13-NEXT:    s_wait_samplecnt 0x0
; GFX13-NEXT:    s_wait_rtscnt 0x0
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    global_wb scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_storecnt 0x0
; GFX13-NEXT:    global_atomic_max_num_f64 v[0:1], v[0:1], v[2:3], off th:TH_ATOMIC_RETURN scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    global_inv scope:SCOPE_DEV
; GFX13-NEXT:    s_set_pc_i64 s[30:31]
main_body:
  %ret = call double @llvm.amdgcn.global.atomic.fmax.f64.p1.f64(ptr addrspace(1) %ptr, double %data)
  ret double %ret
}

define double @global_atomic_fmin_f64_rtn(ptr addrspace(1) %ptr, double %data) {
; GFX90A-LABEL: global_atomic_fmin_f64_rtn:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX90A-NEXT:    global_atomic_min_f64 v[0:1], v[0:1], v[2:3], off glc
; GFX90A-NEXT:    s_waitcnt vmcnt(0)
; GFX90A-NEXT:    buffer_wbinvl1_vol
; GFX90A-NEXT:    s_setpc_b64 s[30:31]
;
; GFX940-LABEL: global_atomic_fmin_f64_rtn:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX940-NEXT:    buffer_wbl2 sc1
; GFX940-NEXT:    global_atomic_min_f64 v[0:1], v[0:1], v[2:3], off sc0
; GFX940-NEXT:    s_waitcnt vmcnt(0)
; GFX940-NEXT:    buffer_inv sc1
; GFX940-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1210-LABEL: global_atomic_fmin_f64_rtn:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    global_wb scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_storecnt 0x0
; GFX1210-NEXT:    global_atomic_min_num_f64 v[0:1], v[0:1], v[2:3], off th:TH_ATOMIC_RETURN scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_loadcnt 0x0
; GFX1210-NEXT:    global_inv scope:SCOPE_DEV
; GFX1210-NEXT:    s_set_pc_i64 s[30:31]
;
; GFX13-LABEL: global_atomic_fmin_f64_rtn:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX13-NEXT:    s_wait_expcnt 0x0
; GFX13-NEXT:    s_wait_samplecnt 0x0
; GFX13-NEXT:    s_wait_rtscnt 0x0
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    global_wb scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_storecnt 0x0
; GFX13-NEXT:    global_atomic_min_num_f64 v[0:1], v[0:1], v[2:3], off th:TH_ATOMIC_RETURN scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    global_inv scope:SCOPE_DEV
; GFX13-NEXT:    s_set_pc_i64 s[30:31]
main_body:
  %ret = call double @llvm.amdgcn.global.atomic.fmin.f64.p1.f64(ptr addrspace(1) %ptr, double %data)
  ret double %ret
}

define amdgpu_kernel void @flat_atomic_fmin_f64_noret(ptr %ptr, double %data) {
; GFX90A-LABEL: flat_atomic_fmin_f64_noret:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX90A-NEXT:    s_waitcnt lgkmcnt(0)
; GFX90A-NEXT:    v_mov_b32_e32 v0, s4
; GFX90A-NEXT:    v_mov_b32_e32 v1, s5
; GFX90A-NEXT:    v_mov_b32_e32 v2, s6
; GFX90A-NEXT:    v_mov_b32_e32 v3, s7
; GFX90A-NEXT:    flat_atomic_min_f64 v[0:1], v[2:3]
; GFX90A-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX90A-NEXT:    buffer_wbinvl1_vol
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: flat_atomic_fmin_f64_noret:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX940-NEXT:    s_waitcnt lgkmcnt(0)
; GFX940-NEXT:    v_mov_b32_e32 v0, s4
; GFX940-NEXT:    v_mov_b32_e32 v1, s5
; GFX940-NEXT:    v_mov_b32_e32 v2, s6
; GFX940-NEXT:    v_mov_b32_e32 v3, s7
; GFX940-NEXT:    buffer_wbl2 sc1
; GFX940-NEXT:    flat_atomic_min_f64 v[0:1], v[2:3]
; GFX940-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX940-NEXT:    buffer_inv sc1
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: flat_atomic_fmin_f64_noret:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    s_load_b128 s[0:3], s[2:3], 0x24
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    v_dual_mov_b32 v2, 0 :: v_dual_mov_b32 v0, s2
; GFX1210-NEXT:    v_mov_b32_e32 v1, s3
; GFX1210-NEXT:    global_wb scope:SCOPE_DEV
; GFX1210-NEXT:    flat_atomic_min_num_f64 v2, v[0:1], s[0:1] scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_storecnt_dscnt 0x0
; GFX1210-NEXT:    global_inv scope:SCOPE_DEV
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: flat_atomic_fmin_f64_noret:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    s_load_b128 s[0:3], s[2:3], 0x24
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX13-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX13-NEXT:    global_wb scope:SCOPE_DEV
; GFX13-NEXT:    flat_atomic_min_num_f64 v[0:1], v[2:3] scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_storecnt_dscnt 0x0
; GFX13-NEXT:    global_inv scope:SCOPE_DEV
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.flat.atomic.fmin.f64.p0.f64(ptr %ptr, double %data)
  ret void
}

define double @flat_atomic_fmin_f64_rtn(ptr %ptr, double %data) {
; GFX90A-LABEL: flat_atomic_fmin_f64_rtn:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX90A-NEXT:    flat_atomic_min_f64 v[0:1], v[0:1], v[2:3] glc
; GFX90A-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX90A-NEXT:    buffer_wbinvl1_vol
; GFX90A-NEXT:    s_setpc_b64 s[30:31]
;
; GFX940-LABEL: flat_atomic_fmin_f64_rtn:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX940-NEXT:    buffer_wbl2 sc1
; GFX940-NEXT:    flat_atomic_min_f64 v[0:1], v[0:1], v[2:3] sc0
; GFX940-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX940-NEXT:    buffer_inv sc1
; GFX940-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1210-LABEL: flat_atomic_fmin_f64_rtn:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    global_wb scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_storecnt 0x0
; GFX1210-NEXT:    flat_atomic_min_num_f64 v[0:1], v[0:1], v[2:3] th:TH_ATOMIC_RETURN scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1210-NEXT:    global_inv scope:SCOPE_DEV
; GFX1210-NEXT:    s_set_pc_i64 s[30:31]
;
; GFX13-LABEL: flat_atomic_fmin_f64_rtn:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX13-NEXT:    s_wait_expcnt 0x0
; GFX13-NEXT:    s_wait_samplecnt 0x0
; GFX13-NEXT:    s_wait_rtscnt 0x0
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    global_wb scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_storecnt 0x0
; GFX13-NEXT:    flat_atomic_min_num_f64 v[0:1], v[0:1], v[2:3] th:TH_ATOMIC_RETURN scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX13-NEXT:    global_inv scope:SCOPE_DEV
; GFX13-NEXT:    s_set_pc_i64 s[30:31]
main_body:
  %ret = call double @llvm.amdgcn.flat.atomic.fmin.f64.p0.f64(ptr %ptr, double %data)
  ret double %ret
}

define amdgpu_kernel void @flat_atomic_fmax_f64_noret(ptr %ptr, double %data) {
; GFX90A-LABEL: flat_atomic_fmax_f64_noret:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX90A-NEXT:    s_waitcnt lgkmcnt(0)
; GFX90A-NEXT:    v_mov_b32_e32 v0, s4
; GFX90A-NEXT:    v_mov_b32_e32 v1, s5
; GFX90A-NEXT:    v_mov_b32_e32 v2, s6
; GFX90A-NEXT:    v_mov_b32_e32 v3, s7
; GFX90A-NEXT:    flat_atomic_max_f64 v[0:1], v[2:3]
; GFX90A-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX90A-NEXT:    buffer_wbinvl1_vol
; GFX90A-NEXT:    s_endpgm
;
; GFX940-LABEL: flat_atomic_fmax_f64_noret:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    s_load_dwordx4 s[4:7], s[2:3], 0x24
; GFX940-NEXT:    s_waitcnt lgkmcnt(0)
; GFX940-NEXT:    v_mov_b32_e32 v0, s4
; GFX940-NEXT:    v_mov_b32_e32 v1, s5
; GFX940-NEXT:    v_mov_b32_e32 v2, s6
; GFX940-NEXT:    v_mov_b32_e32 v3, s7
; GFX940-NEXT:    buffer_wbl2 sc1
; GFX940-NEXT:    flat_atomic_max_f64 v[0:1], v[2:3]
; GFX940-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX940-NEXT:    buffer_inv sc1
; GFX940-NEXT:    s_endpgm
;
; GFX1210-LABEL: flat_atomic_fmax_f64_noret:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    s_load_b128 s[0:3], s[2:3], 0x24
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    v_dual_mov_b32 v2, 0 :: v_dual_mov_b32 v0, s2
; GFX1210-NEXT:    v_mov_b32_e32 v1, s3
; GFX1210-NEXT:    global_wb scope:SCOPE_DEV
; GFX1210-NEXT:    flat_atomic_max_num_f64 v2, v[0:1], s[0:1] scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_storecnt_dscnt 0x0
; GFX1210-NEXT:    global_inv scope:SCOPE_DEV
; GFX1210-NEXT:    s_endpgm
;
; GFX13-LABEL: flat_atomic_fmax_f64_noret:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    s_load_b128 s[0:3], s[2:3], 0x24
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX13-NEXT:    v_dual_mov_b32 v2, s2 :: v_dual_mov_b32 v3, s3
; GFX13-NEXT:    global_wb scope:SCOPE_DEV
; GFX13-NEXT:    flat_atomic_max_num_f64 v[0:1], v[2:3] scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_storecnt_dscnt 0x0
; GFX13-NEXT:    global_inv scope:SCOPE_DEV
; GFX13-NEXT:    s_endpgm
main_body:
  %ret = call double @llvm.amdgcn.flat.atomic.fmax.f64.p0.f64(ptr %ptr, double %data)
  ret void
}

define double @flat_atomic_fmax_f64_rtn(ptr %ptr, double %data) {
; GFX90A-LABEL: flat_atomic_fmax_f64_rtn:
; GFX90A:       ; %bb.0: ; %main_body
; GFX90A-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX90A-NEXT:    flat_atomic_max_f64 v[0:1], v[0:1], v[2:3] glc
; GFX90A-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX90A-NEXT:    buffer_wbinvl1_vol
; GFX90A-NEXT:    s_setpc_b64 s[30:31]
;
; GFX940-LABEL: flat_atomic_fmax_f64_rtn:
; GFX940:       ; %bb.0: ; %main_body
; GFX940-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX940-NEXT:    buffer_wbl2 sc1
; GFX940-NEXT:    flat_atomic_max_f64 v[0:1], v[0:1], v[2:3] sc0
; GFX940-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX940-NEXT:    buffer_inv sc1
; GFX940-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1210-LABEL: flat_atomic_fmax_f64_rtn:
; GFX1210:       ; %bb.0: ; %main_body
; GFX1210-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    global_wb scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_storecnt 0x0
; GFX1210-NEXT:    flat_atomic_max_num_f64 v[0:1], v[0:1], v[2:3] th:TH_ATOMIC_RETURN scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1210-NEXT:    global_inv scope:SCOPE_DEV
; GFX1210-NEXT:    s_set_pc_i64 s[30:31]
;
; GFX13-LABEL: flat_atomic_fmax_f64_rtn:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX13-NEXT:    s_wait_expcnt 0x0
; GFX13-NEXT:    s_wait_samplecnt 0x0
; GFX13-NEXT:    s_wait_rtscnt 0x0
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    global_wb scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_storecnt 0x0
; GFX13-NEXT:    flat_atomic_max_num_f64 v[0:1], v[0:1], v[2:3] th:TH_ATOMIC_RETURN scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX13-NEXT:    global_inv scope:SCOPE_DEV
; GFX13-NEXT:    s_set_pc_i64 s[30:31]
main_body:
  %ret = call double @llvm.amdgcn.flat.atomic.fmax.f64.p0.f64(ptr %ptr, double %data)
  ret double %ret
}

define double @flat_atomic_fmin_f64_intrinsic_rtn__posoffset(ptr %ptr, double %data) #1 {
; GFX90A-LABEL: flat_atomic_fmin_f64_intrinsic_rtn__posoffset:
; GFX90A:       ; %bb.0:
; GFX90A-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX90A-NEXT:    flat_atomic_min_f64 v[0:1], v[0:1], v[2:3] glc
; GFX90A-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX90A-NEXT:    buffer_wbinvl1_vol
; GFX90A-NEXT:    s_setpc_b64 s[30:31]
;
; GFX940-LABEL: flat_atomic_fmin_f64_intrinsic_rtn__posoffset:
; GFX940:       ; %bb.0:
; GFX940-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX940-NEXT:    buffer_wbl2 sc1
; GFX940-NEXT:    flat_atomic_min_f64 v[0:1], v[0:1], v[2:3] sc0
; GFX940-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX940-NEXT:    buffer_inv sc1
; GFX940-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1210-LABEL: flat_atomic_fmin_f64_intrinsic_rtn__posoffset:
; GFX1210:       ; %bb.0:
; GFX1210-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    global_wb scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_storecnt 0x0
; GFX1210-NEXT:    flat_atomic_min_num_f64 v[0:1], v[0:1], v[2:3] th:TH_ATOMIC_RETURN scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1210-NEXT:    global_inv scope:SCOPE_DEV
; GFX1210-NEXT:    s_set_pc_i64 s[30:31]
;
; GFX13-LABEL: flat_atomic_fmin_f64_intrinsic_rtn__posoffset:
; GFX13:       ; %bb.0:
; GFX13-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX13-NEXT:    s_wait_expcnt 0x0
; GFX13-NEXT:    s_wait_samplecnt 0x0
; GFX13-NEXT:    s_wait_rtscnt 0x0
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    global_wb scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_storecnt 0x0
; GFX13-NEXT:    flat_atomic_min_num_f64 v[0:1], v[0:1], v[2:3] th:TH_ATOMIC_RETURN scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX13-NEXT:    global_inv scope:SCOPE_DEV
; GFX13-NEXT:    s_set_pc_i64 s[30:31]
  %gep = getelementptr double, ptr %ptr, i64 511
  %ret = call double @llvm.amdgcn.flat.atomic.fmin.f64.p0.f64(ptr %ptr, double %data)
  ret double %ret
}

define double @flat_atomic_fmin_f64_intrinsic_rtn__negoffset(ptr %ptr, double %data) #1 {
; GFX90A-LABEL: flat_atomic_fmin_f64_intrinsic_rtn__negoffset:
; GFX90A:       ; %bb.0:
; GFX90A-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX90A-NEXT:    v_add_co_u32_e32 v0, vcc, 0xfffff008, v0
; GFX90A-NEXT:    v_addc_co_u32_e32 v1, vcc, -1, v1, vcc
; GFX90A-NEXT:    flat_atomic_min_f64 v[0:1], v[0:1], v[2:3] glc
; GFX90A-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX90A-NEXT:    buffer_wbinvl1_vol
; GFX90A-NEXT:    s_setpc_b64 s[30:31]
;
; GFX940-LABEL: flat_atomic_fmin_f64_intrinsic_rtn__negoffset:
; GFX940:       ; %bb.0:
; GFX940-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX940-NEXT:    v_add_co_u32_e32 v0, vcc, 0xfffff008, v0
; GFX940-NEXT:    s_nop 1
; GFX940-NEXT:    v_addc_co_u32_e32 v1, vcc, -1, v1, vcc
; GFX940-NEXT:    buffer_wbl2 sc1
; GFX940-NEXT:    flat_atomic_min_f64 v[0:1], v[0:1], v[2:3] sc0
; GFX940-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX940-NEXT:    buffer_inv sc1
; GFX940-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1210-LABEL: flat_atomic_fmin_f64_intrinsic_rtn__negoffset:
; GFX1210:       ; %bb.0:
; GFX1210-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    global_wb scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_storecnt 0x0
; GFX1210-NEXT:    flat_atomic_min_num_f64 v[0:1], v[0:1], v[2:3] offset:-4088 th:TH_ATOMIC_RETURN scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1210-NEXT:    global_inv scope:SCOPE_DEV
; GFX1210-NEXT:    s_set_pc_i64 s[30:31]
;
; GFX13-LABEL: flat_atomic_fmin_f64_intrinsic_rtn__negoffset:
; GFX13:       ; %bb.0:
; GFX13-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX13-NEXT:    s_wait_expcnt 0x0
; GFX13-NEXT:    s_wait_samplecnt 0x0
; GFX13-NEXT:    s_wait_rtscnt 0x0
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    global_wb scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_storecnt 0x0
; GFX13-NEXT:    flat_atomic_min_num_f64 v[0:1], v[0:1], v[2:3] offset:61448 th:TH_ATOMIC_RETURN scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX13-NEXT:    global_inv scope:SCOPE_DEV
; GFX13-NEXT:    s_set_pc_i64 s[30:31]
  %gep = getelementptr double, ptr %ptr, i64 -511
  %ret = call double @llvm.amdgcn.flat.atomic.fmin.f64.p0.f64(ptr %gep, double %data)
  ret double %ret
}

define void @flat_atomic_fmin_f64_intrinsic_noret__posoffset(ptr %ptr, double %data) #1 {
; GFX90A-LABEL: flat_atomic_fmin_f64_intrinsic_noret__posoffset:
; GFX90A:       ; %bb.0:
; GFX90A-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX90A-NEXT:    flat_atomic_min_f64 v[0:1], v[2:3]
; GFX90A-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX90A-NEXT:    buffer_wbinvl1_vol
; GFX90A-NEXT:    s_setpc_b64 s[30:31]
;
; GFX940-LABEL: flat_atomic_fmin_f64_intrinsic_noret__posoffset:
; GFX940:       ; %bb.0:
; GFX940-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX940-NEXT:    buffer_wbl2 sc1
; GFX940-NEXT:    flat_atomic_min_f64 v[0:1], v[2:3]
; GFX940-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX940-NEXT:    buffer_inv sc1
; GFX940-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1210-LABEL: flat_atomic_fmin_f64_intrinsic_noret__posoffset:
; GFX1210:       ; %bb.0:
; GFX1210-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    global_wb scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_storecnt 0x0
; GFX1210-NEXT:    flat_atomic_min_num_f64 v[0:1], v[2:3] scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_storecnt_dscnt 0x0
; GFX1210-NEXT:    global_inv scope:SCOPE_DEV
; GFX1210-NEXT:    s_set_pc_i64 s[30:31]
;
; GFX13-LABEL: flat_atomic_fmin_f64_intrinsic_noret__posoffset:
; GFX13:       ; %bb.0:
; GFX13-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX13-NEXT:    s_wait_expcnt 0x0
; GFX13-NEXT:    s_wait_samplecnt 0x0
; GFX13-NEXT:    s_wait_rtscnt 0x0
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    global_wb scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_storecnt 0x0
; GFX13-NEXT:    flat_atomic_min_num_f64 v[0:1], v[2:3] scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_storecnt_dscnt 0x0
; GFX13-NEXT:    global_inv scope:SCOPE_DEV
; GFX13-NEXT:    s_set_pc_i64 s[30:31]
  %gep = getelementptr double, ptr %ptr, i64 511
  %unused = call double @llvm.amdgcn.flat.atomic.fmin.f64.p0.f64(ptr %ptr, double %data)
  ret void
}

define void @flat_atomic_fmin_f64_intrinsic_noret__negoffset(ptr %ptr, double %data) #1 {
; GFX90A-LABEL: flat_atomic_fmin_f64_intrinsic_noret__negoffset:
; GFX90A:       ; %bb.0:
; GFX90A-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX90A-NEXT:    v_add_co_u32_e32 v0, vcc, 0xfffff008, v0
; GFX90A-NEXT:    v_addc_co_u32_e32 v1, vcc, -1, v1, vcc
; GFX90A-NEXT:    flat_atomic_min_f64 v[0:1], v[2:3]
; GFX90A-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX90A-NEXT:    buffer_wbinvl1_vol
; GFX90A-NEXT:    s_setpc_b64 s[30:31]
;
; GFX940-LABEL: flat_atomic_fmin_f64_intrinsic_noret__negoffset:
; GFX940:       ; %bb.0:
; GFX940-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX940-NEXT:    v_add_co_u32_e32 v0, vcc, 0xfffff008, v0
; GFX940-NEXT:    s_nop 1
; GFX940-NEXT:    v_addc_co_u32_e32 v1, vcc, -1, v1, vcc
; GFX940-NEXT:    buffer_wbl2 sc1
; GFX940-NEXT:    flat_atomic_min_f64 v[0:1], v[2:3]
; GFX940-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX940-NEXT:    buffer_inv sc1
; GFX940-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1210-LABEL: flat_atomic_fmin_f64_intrinsic_noret__negoffset:
; GFX1210:       ; %bb.0:
; GFX1210-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    global_wb scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_storecnt 0x0
; GFX1210-NEXT:    flat_atomic_min_num_f64 v[0:1], v[2:3] offset:-4088 scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_storecnt_dscnt 0x0
; GFX1210-NEXT:    global_inv scope:SCOPE_DEV
; GFX1210-NEXT:    s_set_pc_i64 s[30:31]
;
; GFX13-LABEL: flat_atomic_fmin_f64_intrinsic_noret__negoffset:
; GFX13:       ; %bb.0:
; GFX13-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX13-NEXT:    s_wait_expcnt 0x0
; GFX13-NEXT:    s_wait_samplecnt 0x0
; GFX13-NEXT:    s_wait_rtscnt 0x0
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    global_wb scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_storecnt 0x0
; GFX13-NEXT:    flat_atomic_min_num_f64 v[0:1], v[2:3] offset:61448 scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_storecnt_dscnt 0x0
; GFX13-NEXT:    global_inv scope:SCOPE_DEV
; GFX13-NEXT:    s_set_pc_i64 s[30:31]
  %gep = getelementptr double, ptr %ptr, i64 -511
  %unused = call double @llvm.amdgcn.flat.atomic.fmin.f64.p0.f64(ptr %gep, double %data)
  ret void
}

define double @flat_atomic_fmax_f64_intrinsic_rtn__posoffset(ptr %ptr, double %data) #1 {
; GFX90A-LABEL: flat_atomic_fmax_f64_intrinsic_rtn__posoffset:
; GFX90A:       ; %bb.0:
; GFX90A-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX90A-NEXT:    flat_atomic_max_f64 v[0:1], v[0:1], v[2:3] glc
; GFX90A-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX90A-NEXT:    buffer_wbinvl1_vol
; GFX90A-NEXT:    s_setpc_b64 s[30:31]
;
; GFX940-LABEL: flat_atomic_fmax_f64_intrinsic_rtn__posoffset:
; GFX940:       ; %bb.0:
; GFX940-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX940-NEXT:    buffer_wbl2 sc1
; GFX940-NEXT:    flat_atomic_max_f64 v[0:1], v[0:1], v[2:3] sc0
; GFX940-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX940-NEXT:    buffer_inv sc1
; GFX940-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1210-LABEL: flat_atomic_fmax_f64_intrinsic_rtn__posoffset:
; GFX1210:       ; %bb.0:
; GFX1210-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    global_wb scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_storecnt 0x0
; GFX1210-NEXT:    flat_atomic_max_num_f64 v[0:1], v[0:1], v[2:3] th:TH_ATOMIC_RETURN scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1210-NEXT:    global_inv scope:SCOPE_DEV
; GFX1210-NEXT:    s_set_pc_i64 s[30:31]
;
; GFX13-LABEL: flat_atomic_fmax_f64_intrinsic_rtn__posoffset:
; GFX13:       ; %bb.0:
; GFX13-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX13-NEXT:    s_wait_expcnt 0x0
; GFX13-NEXT:    s_wait_samplecnt 0x0
; GFX13-NEXT:    s_wait_rtscnt 0x0
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    global_wb scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_storecnt 0x0
; GFX13-NEXT:    flat_atomic_max_num_f64 v[0:1], v[0:1], v[2:3] th:TH_ATOMIC_RETURN scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX13-NEXT:    global_inv scope:SCOPE_DEV
; GFX13-NEXT:    s_set_pc_i64 s[30:31]
  %gep = getelementptr double, ptr %ptr, i64 511
  %ret = call double @llvm.amdgcn.flat.atomic.fmax.f64.p0.f64(ptr %ptr, double %data)
  ret double %ret
}

define double @flat_atomic_fmax_f64_intrinsic_rtn__negoffset(ptr %ptr, double %data) #1 {
; GFX90A-LABEL: flat_atomic_fmax_f64_intrinsic_rtn__negoffset:
; GFX90A:       ; %bb.0:
; GFX90A-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX90A-NEXT:    v_add_co_u32_e32 v0, vcc, 0xfffff008, v0
; GFX90A-NEXT:    v_addc_co_u32_e32 v1, vcc, -1, v1, vcc
; GFX90A-NEXT:    flat_atomic_max_f64 v[0:1], v[0:1], v[2:3] glc
; GFX90A-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX90A-NEXT:    buffer_wbinvl1_vol
; GFX90A-NEXT:    s_setpc_b64 s[30:31]
;
; GFX940-LABEL: flat_atomic_fmax_f64_intrinsic_rtn__negoffset:
; GFX940:       ; %bb.0:
; GFX940-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX940-NEXT:    v_add_co_u32_e32 v0, vcc, 0xfffff008, v0
; GFX940-NEXT:    s_nop 1
; GFX940-NEXT:    v_addc_co_u32_e32 v1, vcc, -1, v1, vcc
; GFX940-NEXT:    buffer_wbl2 sc1
; GFX940-NEXT:    flat_atomic_max_f64 v[0:1], v[0:1], v[2:3] sc0
; GFX940-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX940-NEXT:    buffer_inv sc1
; GFX940-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1210-LABEL: flat_atomic_fmax_f64_intrinsic_rtn__negoffset:
; GFX1210:       ; %bb.0:
; GFX1210-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    global_wb scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_storecnt 0x0
; GFX1210-NEXT:    flat_atomic_max_num_f64 v[0:1], v[0:1], v[2:3] offset:-4088 th:TH_ATOMIC_RETURN scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1210-NEXT:    global_inv scope:SCOPE_DEV
; GFX1210-NEXT:    s_set_pc_i64 s[30:31]
;
; GFX13-LABEL: flat_atomic_fmax_f64_intrinsic_rtn__negoffset:
; GFX13:       ; %bb.0:
; GFX13-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX13-NEXT:    s_wait_expcnt 0x0
; GFX13-NEXT:    s_wait_samplecnt 0x0
; GFX13-NEXT:    s_wait_rtscnt 0x0
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    global_wb scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_storecnt 0x0
; GFX13-NEXT:    flat_atomic_max_num_f64 v[0:1], v[0:1], v[2:3] offset:61448 th:TH_ATOMIC_RETURN scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX13-NEXT:    global_inv scope:SCOPE_DEV
; GFX13-NEXT:    s_set_pc_i64 s[30:31]
  %gep = getelementptr double, ptr %ptr, i64 -511
  %ret = call double @llvm.amdgcn.flat.atomic.fmax.f64.p0.f64(ptr %gep, double %data)
  ret double %ret
}

define void @flat_atomic_fmax_f64_intrinsic_noret__posoffset(ptr %ptr, double %data) #1 {
; GFX90A-LABEL: flat_atomic_fmax_f64_intrinsic_noret__posoffset:
; GFX90A:       ; %bb.0:
; GFX90A-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX90A-NEXT:    flat_atomic_max_f64 v[0:1], v[2:3]
; GFX90A-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX90A-NEXT:    buffer_wbinvl1_vol
; GFX90A-NEXT:    s_setpc_b64 s[30:31]
;
; GFX940-LABEL: flat_atomic_fmax_f64_intrinsic_noret__posoffset:
; GFX940:       ; %bb.0:
; GFX940-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX940-NEXT:    buffer_wbl2 sc1
; GFX940-NEXT:    flat_atomic_max_f64 v[0:1], v[2:3]
; GFX940-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX940-NEXT:    buffer_inv sc1
; GFX940-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1210-LABEL: flat_atomic_fmax_f64_intrinsic_noret__posoffset:
; GFX1210:       ; %bb.0:
; GFX1210-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    global_wb scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_storecnt 0x0
; GFX1210-NEXT:    flat_atomic_max_num_f64 v[0:1], v[2:3] scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_storecnt_dscnt 0x0
; GFX1210-NEXT:    global_inv scope:SCOPE_DEV
; GFX1210-NEXT:    s_set_pc_i64 s[30:31]
;
; GFX13-LABEL: flat_atomic_fmax_f64_intrinsic_noret__posoffset:
; GFX13:       ; %bb.0:
; GFX13-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX13-NEXT:    s_wait_expcnt 0x0
; GFX13-NEXT:    s_wait_samplecnt 0x0
; GFX13-NEXT:    s_wait_rtscnt 0x0
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    global_wb scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_storecnt 0x0
; GFX13-NEXT:    flat_atomic_max_num_f64 v[0:1], v[2:3] scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_storecnt_dscnt 0x0
; GFX13-NEXT:    global_inv scope:SCOPE_DEV
; GFX13-NEXT:    s_set_pc_i64 s[30:31]
  %gep = getelementptr double, ptr %ptr, i64 511
  %unused = call double @llvm.amdgcn.flat.atomic.fmax.f64.p0.f64(ptr %ptr, double %data)
  ret void
}

define void @flat_atomic_fmax_f64_intrinsic_noret__negoffset(ptr %ptr, double %data) #1 {
; GFX90A-LABEL: flat_atomic_fmax_f64_intrinsic_noret__negoffset:
; GFX90A:       ; %bb.0:
; GFX90A-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX90A-NEXT:    v_add_co_u32_e32 v0, vcc, 0xfffff008, v0
; GFX90A-NEXT:    v_addc_co_u32_e32 v1, vcc, -1, v1, vcc
; GFX90A-NEXT:    flat_atomic_max_f64 v[0:1], v[2:3]
; GFX90A-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX90A-NEXT:    buffer_wbinvl1_vol
; GFX90A-NEXT:    s_setpc_b64 s[30:31]
;
; GFX940-LABEL: flat_atomic_fmax_f64_intrinsic_noret__negoffset:
; GFX940:       ; %bb.0:
; GFX940-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX940-NEXT:    v_add_co_u32_e32 v0, vcc, 0xfffff008, v0
; GFX940-NEXT:    s_nop 1
; GFX940-NEXT:    v_addc_co_u32_e32 v1, vcc, -1, v1, vcc
; GFX940-NEXT:    buffer_wbl2 sc1
; GFX940-NEXT:    flat_atomic_max_f64 v[0:1], v[2:3]
; GFX940-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX940-NEXT:    buffer_inv sc1
; GFX940-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1210-LABEL: flat_atomic_fmax_f64_intrinsic_noret__negoffset:
; GFX1210:       ; %bb.0:
; GFX1210-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX1210-NEXT:    s_wait_kmcnt 0x0
; GFX1210-NEXT:    global_wb scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_storecnt 0x0
; GFX1210-NEXT:    flat_atomic_max_num_f64 v[0:1], v[2:3] offset:-4088 scope:SCOPE_DEV
; GFX1210-NEXT:    s_wait_storecnt_dscnt 0x0
; GFX1210-NEXT:    global_inv scope:SCOPE_DEV
; GFX1210-NEXT:    s_set_pc_i64 s[30:31]
;
; GFX13-LABEL: flat_atomic_fmax_f64_intrinsic_noret__negoffset:
; GFX13:       ; %bb.0:
; GFX13-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX13-NEXT:    s_wait_expcnt 0x0
; GFX13-NEXT:    s_wait_samplecnt 0x0
; GFX13-NEXT:    s_wait_rtscnt 0x0
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    global_wb scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_storecnt 0x0
; GFX13-NEXT:    flat_atomic_max_num_f64 v[0:1], v[2:3] offset:61448 scope:SCOPE_DEV
; GFX13-NEXT:    s_wait_storecnt_dscnt 0x0
; GFX13-NEXT:    global_inv scope:SCOPE_DEV
; GFX13-NEXT:    s_set_pc_i64 s[30:31]
  %gep = getelementptr double, ptr %ptr, i64 -511
  %unused = call double @llvm.amdgcn.flat.atomic.fmax.f64.p0.f64(ptr %gep, double %data)
  ret void
}

attributes #0 = { "denormal-fp-math"="preserve-sign,preserve-sign" }
attributes #1 = { nounwind }
attributes #2 = { "denormal-fp-math"="ieee,ieee" }
attributes #3 = { "denormal-fp-math"="ieee,ieee" }
attributes #4 = { "denormal-fp-math"="preserve-sign,preserve-sign" }

!0 = !{}
