; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -global-isel=0 -mtriple=amdgcn--amdpal -mcpu=gfx1250 < %s | FileCheck %s --check-prefix=CHECK
; RUN: llc -global-isel=1 -mtriple=amdgcn--amdpal -mcpu=gfx1250 < %s | FileCheck %s --check-prefix=CHECK

define amdgpu_cs ptr addrspace(5) @frameaddr_cs_dvgpr(i32 %val) #0 {
; CHECK-LABEL: frameaddr_cs_dvgpr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_getreg_b32 s33, hwreg(HW_REG_WAVE_HW_ID2, 8, 2)
; CHECK-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; CHECK-NEXT:    s_cmp_lg_u32 0, s33
; CHECK-NEXT:    s_cmovk_i32 s33, 0x1c0
; CHECK-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1 ; msbs: dst=0 src0=0 src1=0 src2=0
; CHECK-NEXT:    s_mov_b32 s0, 0
; CHECK-NEXT:    scratch_store_b32 off, v0, s33 scope:SCOPE_SYS
; CHECK-NEXT:    s_wait_storecnt 0x0
; CHECK-NEXT:    ; return to shader part epilog
  %local = alloca i32, addrspace(5)
  store volatile i32 %val, ptr addrspace(5) %local
  %fp = call ptr addrspace(5) @llvm.frameaddress.p5(i32 0)
  ret ptr addrspace(5) %fp
}

define amdgpu_cs ptr addrspace(5) @frameaddr_cs_no_dvgpr(i32 %val) #1 {
; CHECK-LABEL: frameaddr_cs_no_dvgpr:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1 ; msbs: dst=0 src0=0 src1=0 src2=0
; CHECK-NEXT:    s_mov_b32 s0, 0
; CHECK-NEXT:    scratch_store_b32 off, v0, off scope:SCOPE_SYS
; CHECK-NEXT:    s_wait_storecnt 0x0
; CHECK-NEXT:    ; return to shader part epilog
  %local = alloca i32, addrspace(5)
  store volatile i32 %val, ptr addrspace(5) %local
  %fp = call ptr addrspace(5) @llvm.frameaddress.p5(i32 0)
  ret ptr addrspace(5) %fp
}

attributes #0 = { nounwind "amdgpu-dynamic-vgpr-block-size"="16" }
attributes #1 = { nounwind "amdgpu-dynamic-vgpr-block-size"="0" }
