; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -global-isel=0 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1250 -mattr=-real-true16 < %s | FileCheck -check-prefixes=GCN,GCN-SDAG,GCN-SDAG-FAKE16 %s
; RUN: llc -global-isel=1 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1250 -mattr=-real-true16 < %s | FileCheck -check-prefixes=GCN,GCN-GISEL,GCN-GISEL-FAKE16 %s
; RUN: llc -global-isel=0 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1250 -mattr=+real-true16 < %s | FileCheck -check-prefixes=GCN,GCN-SDAG,GCN-SDAG-REAL16 %s
; RUN: llc -global-isel=1 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1250 -mattr=+real-true16 < %s | FileCheck -check-prefixes=GCN,GCN-GISEL,GCN-GISEL-REAL16 %s

; Test S_WAIT_XCNT insertion for global_load/store clauses.
; Introduced additional operations in between the clauses to have the register dependency
; between the operands of VMEM operations and the def ops of VALU instructions that followed.

define void @test_i8load_v4i8store(ptr addrspace(1) %ptr_a, ptr addrspace(1) %ptr_b, ptr addrspace(1) %ptr_c, ptr addrspace(1) %ptr_d, ptr addrspace(1) %out) {
; GCN-SDAG-FAKE16-LABEL: test_i8load_v4i8store:
; GCN-SDAG-FAKE16:       ; %bb.0:
; GCN-SDAG-FAKE16-NEXT:    s_wait_loadcnt_dscnt 0x0
; GCN-SDAG-FAKE16-NEXT:    s_wait_kmcnt 0x0
; GCN-SDAG-FAKE16-NEXT:    global_load_u8 v6, v[4:5], off
; GCN-SDAG-FAKE16-NEXT:    global_load_u8 v7, v[2:3], off
; GCN-SDAG-FAKE16-NEXT:    global_load_u8 v10, v[0:1], off
; GCN-SDAG-FAKE16-NEXT:    s_wait_loadcnt 0x2
; GCN-SDAG-FAKE16-NEXT:    s_wait_xcnt 0x0
; GCN-SDAG-FAKE16-NEXT:    v_lshlrev_b16 v0, 8, v6
; GCN-SDAG-FAKE16-NEXT:    s_wait_loadcnt 0x0
; GCN-SDAG-FAKE16-NEXT:    v_perm_b32 v1, v10, v7, 0xc0c0004
; GCN-SDAG-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GCN-SDAG-FAKE16-NEXT:    v_or_b32_e32 v0, v6, v0
; GCN-SDAG-FAKE16-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; GCN-SDAG-FAKE16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GCN-SDAG-FAKE16-NEXT:    v_or_b32_e32 v0, v1, v0
; GCN-SDAG-FAKE16-NEXT:    global_store_b32 v[8:9], v0, off
; GCN-SDAG-FAKE16-NEXT:    s_set_pc_i64 s[30:31]
;
; GCN-GISEL-LABEL: test_i8load_v4i8store:
; GCN-GISEL:       ; %bb.0:
; GCN-GISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GCN-GISEL-NEXT:    s_wait_kmcnt 0x0
; GCN-GISEL-NEXT:    global_load_u8 v6, v[0:1], off
; GCN-GISEL-NEXT:    global_load_u8 v7, v[2:3], off
; GCN-GISEL-NEXT:    global_load_u8 v10, v[4:5], off
; GCN-GISEL-NEXT:    s_wait_loadcnt 0x1
; GCN-GISEL-NEXT:    s_wait_xcnt 0x2
; GCN-GISEL-NEXT:    v_lshl_or_b32 v0, v7, 8, v6
; GCN-GISEL-NEXT:    s_wait_loadcnt 0x0
; GCN-GISEL-NEXT:    s_wait_xcnt 0x1
; GCN-GISEL-NEXT:    v_dual_lshlrev_b32 v1, 16, v10 :: v_dual_lshlrev_b32 v2, 24, v10
; GCN-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GCN-GISEL-NEXT:    v_or3_b32 v0, v0, v1, v2
; GCN-GISEL-NEXT:    global_store_b32 v[8:9], v0, off
; GCN-GISEL-NEXT:    s_set_pc_i64 s[30:31]
;
; GCN-SDAG-REAL16-LABEL: test_i8load_v4i8store:
; GCN-SDAG-REAL16:       ; %bb.0:
; GCN-SDAG-REAL16-NEXT:    s_wait_loadcnt_dscnt 0x0
; GCN-SDAG-REAL16-NEXT:    s_wait_kmcnt 0x0
; GCN-SDAG-REAL16-NEXT:    global_load_u8 v6, v[4:5], off
; GCN-SDAG-REAL16-NEXT:    global_load_u8 v7, v[2:3], off
; GCN-SDAG-REAL16-NEXT:    global_load_u8 v10, v[0:1], off
; GCN-SDAG-REAL16-NEXT:    s_wait_loadcnt 0x2
; GCN-SDAG-REAL16-NEXT:    s_wait_xcnt 0x0
; GCN-SDAG-REAL16-NEXT:    v_lshlrev_b16 v0.l, 8, v6.l
; GCN-SDAG-REAL16-NEXT:    s_wait_loadcnt 0x0
; GCN-SDAG-REAL16-NEXT:    v_perm_b32 v1, v10, v7, 0xc0c0004
; GCN-SDAG-REAL16-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GCN-SDAG-REAL16-NEXT:    v_or_b16 v0.l, v6.l, v0.l
; GCN-SDAG-REAL16-NEXT:    v_lshlrev_b32_e32 v0, 16, v0
; GCN-SDAG-REAL16-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GCN-SDAG-REAL16-NEXT:    v_or_b32_e32 v0, v1, v0
; GCN-SDAG-REAL16-NEXT:    global_store_b32 v[8:9], v0, off
; GCN-SDAG-REAL16-NEXT:    s_set_pc_i64 s[30:31]
  %a = load i8, ptr addrspace(1) %ptr_a
  %b = load i8, ptr addrspace(1) %ptr_b
  %c = load i8, ptr addrspace(1) %ptr_c
  %d = load i8, ptr addrspace(1) %ptr_d
  %ins_0 = insertelement <4 x i8> poison, i8 %a, i32 0
  %ins_1 = insertelement <4 x i8> %ins_0, i8 %b, i32 1
  %ins_2 = insertelement <4 x i8> %ins_1, i8 %c, i32 2
  %ins_3 = insertelement <4 x i8> %ins_2, i8 %c, i32 3
  store <4 x i8> %ins_3, ptr addrspace(1) %out
  ret void
}

define i16 @test_v7i16_load_store(ptr addrspace(1) %ptr1, ptr addrspace(1) %ptr2) {
; GCN-SDAG-FAKE16-LABEL: test_v7i16_load_store:
; GCN-SDAG-FAKE16:       ; %bb.0:
; GCN-SDAG-FAKE16-NEXT:    s_wait_loadcnt_dscnt 0x0
; GCN-SDAG-FAKE16-NEXT:    s_wait_kmcnt 0x0
; GCN-SDAG-FAKE16-NEXT:    global_load_b128 v[4:7], v[0:1], off
; GCN-SDAG-FAKE16-NEXT:    global_load_b128 v[8:11], v[2:3], off
; GCN-SDAG-FAKE16-NEXT:    v_mov_b64_e32 v[12:13], 0
; GCN-SDAG-FAKE16-NEXT:    s_wait_loadcnt 0x0
; GCN-SDAG-FAKE16-NEXT:    s_wait_xcnt 0x1
; GCN-SDAG-FAKE16-NEXT:    v_pk_add_u16 v1, v6, v10
; GCN-SDAG-FAKE16-NEXT:    s_wait_xcnt 0x0
; GCN-SDAG-FAKE16-NEXT:    v_pk_add_u16 v3, v5, v9
; GCN-SDAG-FAKE16-NEXT:    v_pk_add_u16 v5, v7, v11
; GCN-SDAG-FAKE16-NEXT:    v_mov_b64_e32 v[6:7], 12
; GCN-SDAG-FAKE16-NEXT:    v_mov_b64_e32 v[10:11], 8
; GCN-SDAG-FAKE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v1
; GCN-SDAG-FAKE16-NEXT:    v_pk_add_u16 v2, v4, v8
; GCN-SDAG-FAKE16-NEXT:    s_clause 0x2
; GCN-SDAG-FAKE16-NEXT:    global_store_b16 v[6:7], v5, off
; GCN-SDAG-FAKE16-NEXT:    global_store_b32 v[10:11], v1, off
; GCN-SDAG-FAKE16-NEXT:    global_store_b64 v[12:13], v[2:3], off
; GCN-SDAG-FAKE16-NEXT:    s_set_pc_i64 s[30:31]
;
; GCN-GISEL-FAKE16-LABEL: test_v7i16_load_store:
; GCN-GISEL-FAKE16:       ; %bb.0:
; GCN-GISEL-FAKE16-NEXT:    s_wait_loadcnt_dscnt 0x0
; GCN-GISEL-FAKE16-NEXT:    s_wait_kmcnt 0x0
; GCN-GISEL-FAKE16-NEXT:    global_load_b128 v[4:7], v[0:1], off
; GCN-GISEL-FAKE16-NEXT:    global_load_b128 v[8:11], v[2:3], off
; GCN-GISEL-FAKE16-NEXT:    s_wait_xcnt 0x0
; GCN-GISEL-FAKE16-NEXT:    v_mov_b64_e32 v[2:3], 0
; GCN-GISEL-FAKE16-NEXT:    v_mov_b64_e32 v[12:13], 2
; GCN-GISEL-FAKE16-NEXT:    v_mov_b64_e32 v[14:15], 4
; GCN-GISEL-FAKE16-NEXT:    v_mov_b64_e32 v[16:17], 6
; GCN-GISEL-FAKE16-NEXT:    v_mov_b64_e32 v[18:19], 8
; GCN-GISEL-FAKE16-NEXT:    v_mov_b64_e32 v[20:21], 10
; GCN-GISEL-FAKE16-NEXT:    v_mov_b64_e32 v[22:23], 12
; GCN-GISEL-FAKE16-NEXT:    s_wait_loadcnt 0x0
; GCN-GISEL-FAKE16-NEXT:    v_pk_add_u16 v1, v6, v10
; GCN-GISEL-FAKE16-NEXT:    v_pk_add_u16 v4, v4, v8
; GCN-GISEL-FAKE16-NEXT:    v_pk_add_u16 v5, v5, v9
; GCN-GISEL-FAKE16-NEXT:    v_pk_add_u16 v6, v7, v11
; GCN-GISEL-FAKE16-NEXT:    s_clause 0x6
; GCN-GISEL-FAKE16-NEXT:    global_store_b16 v[2:3], v4, off
; GCN-GISEL-FAKE16-NEXT:    global_store_d16_hi_b16 v[12:13], v4, off
; GCN-GISEL-FAKE16-NEXT:    global_store_b16 v[14:15], v5, off
; GCN-GISEL-FAKE16-NEXT:    global_store_d16_hi_b16 v[16:17], v5, off
; GCN-GISEL-FAKE16-NEXT:    global_store_b16 v[18:19], v1, off
; GCN-GISEL-FAKE16-NEXT:    global_store_d16_hi_b16 v[20:21], v1, off
; GCN-GISEL-FAKE16-NEXT:    global_store_b16 v[22:23], v6, off
; GCN-GISEL-FAKE16-NEXT:    v_lshrrev_b32_e32 v0, 16, v1
; GCN-GISEL-FAKE16-NEXT:    s_set_pc_i64 s[30:31]
;
; GCN-SDAG-REAL16-LABEL: test_v7i16_load_store:
; GCN-SDAG-REAL16:       ; %bb.0:
; GCN-SDAG-REAL16-NEXT:    s_wait_loadcnt_dscnt 0x0
; GCN-SDAG-REAL16-NEXT:    s_wait_kmcnt 0x0
; GCN-SDAG-REAL16-NEXT:    global_load_b128 v[4:7], v[0:1], off
; GCN-SDAG-REAL16-NEXT:    global_load_b128 v[8:11], v[2:3], off
; GCN-SDAG-REAL16-NEXT:    s_wait_xcnt 0x0
; GCN-SDAG-REAL16-NEXT:    v_mov_b64_e32 v[2:3], 12
; GCN-SDAG-REAL16-NEXT:    v_mov_b64_e32 v[12:13], 8
; GCN-SDAG-REAL16-NEXT:    v_mov_b64_e32 v[14:15], 0
; GCN-SDAG-REAL16-NEXT:    s_wait_loadcnt 0x0
; GCN-SDAG-REAL16-NEXT:    v_pk_add_u16 v1, v7, v11
; GCN-SDAG-REAL16-NEXT:    v_pk_add_u16 v0, v6, v10
; GCN-SDAG-REAL16-NEXT:    v_pk_add_u16 v5, v5, v9
; GCN-SDAG-REAL16-NEXT:    v_pk_add_u16 v4, v4, v8
; GCN-SDAG-REAL16-NEXT:    s_clause 0x2
; GCN-SDAG-REAL16-NEXT:    global_store_b16 v[2:3], v1, off
; GCN-SDAG-REAL16-NEXT:    global_store_b32 v[12:13], v0, off
; GCN-SDAG-REAL16-NEXT:    global_store_b64 v[14:15], v[4:5], off
; GCN-SDAG-REAL16-NEXT:    s_wait_xcnt 0x1
; GCN-SDAG-REAL16-NEXT:    v_mov_b16_e32 v0.l, v0.h
; GCN-SDAG-REAL16-NEXT:    s_set_pc_i64 s[30:31]
;
; GCN-GISEL-REAL16-LABEL: test_v7i16_load_store:
; GCN-GISEL-REAL16:       ; %bb.0:
; GCN-GISEL-REAL16-NEXT:    s_wait_loadcnt_dscnt 0x0
; GCN-GISEL-REAL16-NEXT:    s_wait_kmcnt 0x0
; GCN-GISEL-REAL16-NEXT:    global_load_b128 v[4:7], v[0:1], off
; GCN-GISEL-REAL16-NEXT:    global_load_b128 v[8:11], v[2:3], off
; GCN-GISEL-REAL16-NEXT:    s_wait_xcnt 0x0
; GCN-GISEL-REAL16-NEXT:    v_mov_b64_e32 v[2:3], 0
; GCN-GISEL-REAL16-NEXT:    v_mov_b64_e32 v[12:13], 2
; GCN-GISEL-REAL16-NEXT:    v_mov_b64_e32 v[14:15], 4
; GCN-GISEL-REAL16-NEXT:    v_mov_b64_e32 v[16:17], 6
; GCN-GISEL-REAL16-NEXT:    v_mov_b64_e32 v[18:19], 8
; GCN-GISEL-REAL16-NEXT:    v_mov_b64_e32 v[20:21], 10
; GCN-GISEL-REAL16-NEXT:    v_mov_b64_e32 v[22:23], 12
; GCN-GISEL-REAL16-NEXT:    ; implicit-def: $vgpr0_hi16
; GCN-GISEL-REAL16-NEXT:    s_wait_loadcnt 0x0
; GCN-GISEL-REAL16-NEXT:    v_pk_add_u16 v1, v6, v10
; GCN-GISEL-REAL16-NEXT:    v_pk_add_u16 v4, v4, v8
; GCN-GISEL-REAL16-NEXT:    v_pk_add_u16 v5, v5, v9
; GCN-GISEL-REAL16-NEXT:    v_pk_add_u16 v6, v7, v11
; GCN-GISEL-REAL16-NEXT:    s_clause 0x6
; GCN-GISEL-REAL16-NEXT:    global_store_b16 v[2:3], v4, off
; GCN-GISEL-REAL16-NEXT:    global_store_d16_hi_b16 v[12:13], v4, off
; GCN-GISEL-REAL16-NEXT:    global_store_b16 v[14:15], v5, off
; GCN-GISEL-REAL16-NEXT:    global_store_d16_hi_b16 v[16:17], v5, off
; GCN-GISEL-REAL16-NEXT:    global_store_b16 v[18:19], v1, off
; GCN-GISEL-REAL16-NEXT:    global_store_d16_hi_b16 v[20:21], v1, off
; GCN-GISEL-REAL16-NEXT:    global_store_b16 v[22:23], v6, off
; GCN-GISEL-REAL16-NEXT:    v_mov_b16_e32 v0.l, v1.h
; GCN-GISEL-REAL16-NEXT:    s_set_pc_i64 s[30:31]
  %vec1 = load <7 x i16>, ptr addrspace(1) %ptr1
  %insert = insertelement <7 x i16> %vec1, i16 20, i32 4
  %vec2 = load <7 x i16>, ptr addrspace(1) %ptr2
  %add = add <7 x i16> %vec1, %vec2
  store <7 x i16> %add, ptr addrspace(1) null
  %elt = extractelement <7 x i16> %add, i32 5
  ret i16 %elt
}

define i32 @test_v64i32_load_store(ptr addrspace(1) %ptr, i32 %idx, ptr addrspace(1) %out) {
; GCN-SDAG-LABEL: test_v64i32_load_store:
; GCN-SDAG:       ; %bb.0:
; GCN-SDAG-NEXT:    s_wait_loadcnt_dscnt 0x0
; GCN-SDAG-NEXT:    s_wait_kmcnt 0x0
; GCN-SDAG-NEXT:    v_dual_mov_b32 v39, v4 :: v_dual_mov_b32 v38, v3
; GCN-SDAG-NEXT:    s_clause 0xf
; GCN-SDAG-NEXT:    global_load_b128 v[2:5], v[0:1], off offset:224
; GCN-SDAG-NEXT:    global_load_b128 v[6:9], v[0:1], off offset:240
; GCN-SDAG-NEXT:    global_load_b128 v[10:13], v[0:1], off offset:192
; GCN-SDAG-NEXT:    global_load_b128 v[14:17], v[0:1], off offset:208
; GCN-SDAG-NEXT:    global_load_b128 v[18:21], v[0:1], off offset:160
; GCN-SDAG-NEXT:    global_load_b128 v[22:25], v[0:1], off offset:176
; GCN-SDAG-NEXT:    global_load_b128 v[26:29], v[0:1], off offset:128
; GCN-SDAG-NEXT:    global_load_b128 v[30:33], v[0:1], off offset:144
; GCN-SDAG-NEXT:    global_load_b128 v[34:37], v[0:1], off offset:96
; GCN-SDAG-NEXT:    global_load_b128 v[48:51], v[0:1], off offset:112
; GCN-SDAG-NEXT:    global_load_b128 v[52:55], v[0:1], off offset:64
; GCN-SDAG-NEXT:    global_load_b128 v[64:67], v[0:1], off offset:80
; GCN-SDAG-NEXT:    global_load_b128 v[68:71], v[0:1], off offset:32
; GCN-SDAG-NEXT:    global_load_b128 v[80:83], v[0:1], off offset:48
; GCN-SDAG-NEXT:    global_load_b128 v[84:87], v[0:1], off
; GCN-SDAG-NEXT:    global_load_b128 v[96:99], v[0:1], off offset:16
; GCN-SDAG-NEXT:    s_wait_loadcnt 0xf
; GCN-SDAG-NEXT:    global_store_b128 v[38:39], v[2:5], off offset:224
; GCN-SDAG-NEXT:    s_wait_loadcnt 0xe
; GCN-SDAG-NEXT:    global_store_b128 v[38:39], v[6:9], off offset:240
; GCN-SDAG-NEXT:    s_wait_loadcnt 0xd
; GCN-SDAG-NEXT:    global_store_b128 v[38:39], v[10:13], off offset:192
; GCN-SDAG-NEXT:    s_wait_loadcnt 0xc
; GCN-SDAG-NEXT:    global_store_b128 v[38:39], v[14:17], off offset:208
; GCN-SDAG-NEXT:    s_wait_loadcnt 0xb
; GCN-SDAG-NEXT:    global_store_b128 v[38:39], v[18:21], off offset:160
; GCN-SDAG-NEXT:    s_wait_loadcnt 0xa
; GCN-SDAG-NEXT:    global_store_b128 v[38:39], v[22:25], off offset:176
; GCN-SDAG-NEXT:    s_wait_loadcnt 0x9
; GCN-SDAG-NEXT:    global_store_b128 v[38:39], v[26:29], off offset:128
; GCN-SDAG-NEXT:    s_wait_loadcnt 0x8
; GCN-SDAG-NEXT:    global_store_b128 v[38:39], v[30:33], off offset:144
; GCN-SDAG-NEXT:    s_wait_loadcnt 0x7
; GCN-SDAG-NEXT:    global_store_b128 v[38:39], v[34:37], off offset:96
; GCN-SDAG-NEXT:    s_wait_loadcnt 0x6
; GCN-SDAG-NEXT:    global_store_b128 v[38:39], v[48:51], off offset:112
; GCN-SDAG-NEXT:    s_wait_loadcnt 0x5
; GCN-SDAG-NEXT:    global_store_b128 v[38:39], v[52:55], off offset:64
; GCN-SDAG-NEXT:    s_wait_loadcnt 0x4
; GCN-SDAG-NEXT:    global_store_b128 v[38:39], v[64:67], off offset:80
; GCN-SDAG-NEXT:    s_wait_loadcnt 0x3
; GCN-SDAG-NEXT:    global_store_b128 v[38:39], v[68:71], off offset:32
; GCN-SDAG-NEXT:    s_wait_loadcnt 0x2
; GCN-SDAG-NEXT:    global_store_b128 v[38:39], v[80:83], off offset:48
; GCN-SDAG-NEXT:    s_wait_loadcnt 0x1
; GCN-SDAG-NEXT:    global_store_b128 v[38:39], v[84:87], off
; GCN-SDAG-NEXT:    s_wait_loadcnt 0x0
; GCN-SDAG-NEXT:    global_store_b128 v[38:39], v[96:99], off offset:16
; GCN-SDAG-NEXT:    s_wait_xcnt 0x10
; GCN-SDAG-NEXT:    v_mov_b32_e32 v0, v98
; GCN-SDAG-NEXT:    s_set_pc_i64 s[30:31]
;
; GCN-GISEL-LABEL: test_v64i32_load_store:
; GCN-GISEL:       ; %bb.0:
; GCN-GISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GCN-GISEL-NEXT:    s_wait_kmcnt 0x0
; GCN-GISEL-NEXT:    v_dual_mov_b32 v38, v3 :: v_dual_mov_b32 v39, v4
; GCN-GISEL-NEXT:    s_clause 0xf
; GCN-GISEL-NEXT:    global_load_b128 v[2:5], v[0:1], off offset:32
; GCN-GISEL-NEXT:    global_load_b128 v[6:9], v[0:1], off offset:48
; GCN-GISEL-NEXT:    global_load_b128 v[10:13], v[0:1], off
; GCN-GISEL-NEXT:    global_load_b128 v[14:17], v[0:1], off offset:16
; GCN-GISEL-NEXT:    global_load_b128 v[18:21], v[0:1], off offset:64
; GCN-GISEL-NEXT:    global_load_b128 v[22:25], v[0:1], off offset:80
; GCN-GISEL-NEXT:    global_load_b128 v[26:29], v[0:1], off offset:96
; GCN-GISEL-NEXT:    global_load_b128 v[30:33], v[0:1], off offset:112
; GCN-GISEL-NEXT:    global_load_b128 v[34:37], v[0:1], off offset:128
; GCN-GISEL-NEXT:    global_load_b128 v[48:51], v[0:1], off offset:144
; GCN-GISEL-NEXT:    global_load_b128 v[52:55], v[0:1], off offset:160
; GCN-GISEL-NEXT:    global_load_b128 v[64:67], v[0:1], off offset:176
; GCN-GISEL-NEXT:    global_load_b128 v[68:71], v[0:1], off offset:192
; GCN-GISEL-NEXT:    global_load_b128 v[80:83], v[0:1], off offset:208
; GCN-GISEL-NEXT:    global_load_b128 v[84:87], v[0:1], off offset:224
; GCN-GISEL-NEXT:    global_load_b128 v[96:99], v[0:1], off offset:240
; GCN-GISEL-NEXT:    s_wait_loadcnt 0xf
; GCN-GISEL-NEXT:    global_store_b128 v[38:39], v[2:5], off offset:32
; GCN-GISEL-NEXT:    s_wait_loadcnt 0xe
; GCN-GISEL-NEXT:    global_store_b128 v[38:39], v[6:9], off offset:48
; GCN-GISEL-NEXT:    s_wait_loadcnt 0xd
; GCN-GISEL-NEXT:    global_store_b128 v[38:39], v[10:13], off
; GCN-GISEL-NEXT:    s_wait_loadcnt 0xc
; GCN-GISEL-NEXT:    global_store_b128 v[38:39], v[14:17], off offset:16
; GCN-GISEL-NEXT:    s_wait_loadcnt 0xb
; GCN-GISEL-NEXT:    global_store_b128 v[38:39], v[18:21], off offset:64
; GCN-GISEL-NEXT:    s_wait_loadcnt 0xa
; GCN-GISEL-NEXT:    global_store_b128 v[38:39], v[22:25], off offset:80
; GCN-GISEL-NEXT:    s_wait_loadcnt 0x9
; GCN-GISEL-NEXT:    global_store_b128 v[38:39], v[26:29], off offset:96
; GCN-GISEL-NEXT:    s_wait_loadcnt 0x8
; GCN-GISEL-NEXT:    global_store_b128 v[38:39], v[30:33], off offset:112
; GCN-GISEL-NEXT:    s_wait_loadcnt 0x7
; GCN-GISEL-NEXT:    global_store_b128 v[38:39], v[34:37], off offset:128
; GCN-GISEL-NEXT:    s_wait_loadcnt 0x6
; GCN-GISEL-NEXT:    global_store_b128 v[38:39], v[48:51], off offset:144
; GCN-GISEL-NEXT:    s_wait_loadcnt 0x5
; GCN-GISEL-NEXT:    global_store_b128 v[38:39], v[52:55], off offset:160
; GCN-GISEL-NEXT:    s_wait_loadcnt 0x4
; GCN-GISEL-NEXT:    global_store_b128 v[38:39], v[64:67], off offset:176
; GCN-GISEL-NEXT:    s_wait_loadcnt 0x3
; GCN-GISEL-NEXT:    global_store_b128 v[38:39], v[68:71], off offset:192
; GCN-GISEL-NEXT:    s_wait_loadcnt 0x2
; GCN-GISEL-NEXT:    global_store_b128 v[38:39], v[80:83], off offset:208
; GCN-GISEL-NEXT:    s_wait_loadcnt 0x1
; GCN-GISEL-NEXT:    global_store_b128 v[38:39], v[84:87], off offset:224
; GCN-GISEL-NEXT:    s_wait_loadcnt 0x0
; GCN-GISEL-NEXT:    global_store_b128 v[38:39], v[96:99], off offset:240
; GCN-GISEL-NEXT:    s_wait_xcnt 0x10
; GCN-GISEL-NEXT:    v_mov_b32_e32 v0, v16
; GCN-GISEL-NEXT:    s_set_pc_i64 s[30:31]
  %vec = load <64 x i32>, ptr addrspace(1) %ptr
  store <64 x i32> %vec, ptr addrspace(1) %out, align 4
  %elt = extractelement <64 x i32> %vec, i32 6
  ret i32 %elt
}

define i64 @test_v16i64_load_store(ptr addrspace(1) %ptr_a, ptr addrspace(1) %ptr_b, ptr addrspace(1) %out) {
; GCN-SDAG-LABEL: test_v16i64_load_store:
; GCN-SDAG:       ; %bb.0:
; GCN-SDAG-NEXT:    s_wait_loadcnt_dscnt 0x0
; GCN-SDAG-NEXT:    s_wait_kmcnt 0x0
; GCN-SDAG-NEXT:    s_clause 0x7
; GCN-SDAG-NEXT:    global_load_b128 v[6:9], v[0:1], off offset:112
; GCN-SDAG-NEXT:    global_load_b128 v[10:13], v[0:1], off offset:96
; GCN-SDAG-NEXT:    global_load_b128 v[14:17], v[0:1], off offset:80
; GCN-SDAG-NEXT:    global_load_b128 v[18:21], v[0:1], off offset:48
; GCN-SDAG-NEXT:    global_load_b128 v[22:25], v[0:1], off offset:32
; GCN-SDAG-NEXT:    global_load_b128 v[26:29], v[0:1], off offset:16
; GCN-SDAG-NEXT:    global_load_b128 v[30:33], v[0:1], off
; GCN-SDAG-NEXT:    global_load_b128 v[34:37], v[0:1], off offset:64
; GCN-SDAG-NEXT:    v_mov_b64_e32 v[48:49], 48
; GCN-SDAG-NEXT:    v_mov_b64_e32 v[2:3], 0x70
; GCN-SDAG-NEXT:    v_mov_b64_e32 v[50:51], 32
; GCN-SDAG-NEXT:    v_mov_b64_e32 v[38:39], 0x60
; GCN-SDAG-NEXT:    v_mov_b64_e32 v[64:65], 16
; GCN-SDAG-NEXT:    v_mov_b64_e32 v[66:67], 0
; GCN-SDAG-NEXT:    v_mov_b64_e32 v[52:53], 0x50
; GCN-SDAG-NEXT:    s_wait_xcnt 0x0
; GCN-SDAG-NEXT:    v_dual_mov_b32 v1, 0 :: v_dual_mov_b32 v0, 0xc8
; GCN-SDAG-NEXT:    v_mov_b64_e32 v[54:55], 64
; GCN-SDAG-NEXT:    s_wait_loadcnt 0x7
; GCN-SDAG-NEXT:    global_store_b128 v[2:3], v[6:9], off
; GCN-SDAG-NEXT:    s_wait_loadcnt 0x6
; GCN-SDAG-NEXT:    global_store_b128 v[38:39], v[10:13], off
; GCN-SDAG-NEXT:    s_wait_loadcnt 0x5
; GCN-SDAG-NEXT:    s_wait_xcnt 0x1
; GCN-SDAG-NEXT:    v_dual_mov_b32 v2, v16 :: v_dual_mov_b32 v3, v17
; GCN-SDAG-NEXT:    s_wait_xcnt 0x0
; GCN-SDAG-NEXT:    v_add_nc_u64_e32 v[12:13], v[12:13], v[12:13]
; GCN-SDAG-NEXT:    v_add_nc_u64_e32 v[10:11], v[10:11], v[10:11]
; GCN-SDAG-NEXT:    s_wait_loadcnt 0x4
; GCN-SDAG-NEXT:    global_store_b128 v[48:49], v[18:21], off
; GCN-SDAG-NEXT:    s_wait_loadcnt 0x3
; GCN-SDAG-NEXT:    global_store_b128 v[50:51], v[22:25], off
; GCN-SDAG-NEXT:    s_wait_loadcnt 0x2
; GCN-SDAG-NEXT:    global_store_b128 v[64:65], v[26:29], off
; GCN-SDAG-NEXT:    s_wait_loadcnt 0x1
; GCN-SDAG-NEXT:    global_store_b128 v[66:67], v[30:33], off
; GCN-SDAG-NEXT:    s_wait_xcnt 0x0
; GCN-SDAG-NEXT:    v_add_nc_u64_e32 v[32:33], v[32:33], v[32:33]
; GCN-SDAG-NEXT:    v_add_nc_u64_e32 v[8:9], v[8:9], v[8:9]
; GCN-SDAG-NEXT:    v_add_nc_u64_e32 v[6:7], v[6:7], v[6:7]
; GCN-SDAG-NEXT:    s_wait_loadcnt 0x0
; GCN-SDAG-NEXT:    v_add_nc_u64_e32 v[50:51], v[36:37], v[36:37]
; GCN-SDAG-NEXT:    v_add_nc_u64_e32 v[48:49], v[34:35], v[34:35]
; GCN-SDAG-NEXT:    v_add_nc_u64_e32 v[16:17], v[16:17], v[16:17]
; GCN-SDAG-NEXT:    v_add_nc_u64_e32 v[14:15], 0xc8, v[14:15]
; GCN-SDAG-NEXT:    v_add_nc_u64_e32 v[28:29], v[28:29], v[28:29]
; GCN-SDAG-NEXT:    v_add_nc_u64_e32 v[26:27], v[26:27], v[26:27]
; GCN-SDAG-NEXT:    v_add_nc_u64_e32 v[30:31], v[30:31], v[30:31]
; GCN-SDAG-NEXT:    v_add_nc_u64_e32 v[20:21], v[20:21], v[20:21]
; GCN-SDAG-NEXT:    v_add_nc_u64_e32 v[18:19], v[18:19], v[18:19]
; GCN-SDAG-NEXT:    v_add_nc_u64_e32 v[24:25], 0x64, v[24:25]
; GCN-SDAG-NEXT:    v_add_nc_u64_e32 v[22:23], v[22:23], v[22:23]
; GCN-SDAG-NEXT:    s_clause 0x1
; GCN-SDAG-NEXT:    global_store_b128 v[52:53], v[0:3], off
; GCN-SDAG-NEXT:    global_store_b128 v[54:55], v[34:37], off
; GCN-SDAG-NEXT:    s_clause 0x7
; GCN-SDAG-NEXT:    global_store_b128 v[4:5], v[10:13], off offset:96
; GCN-SDAG-NEXT:    global_store_b128 v[4:5], v[6:9], off offset:112
; GCN-SDAG-NEXT:    global_store_b128 v[4:5], v[48:51], off offset:64
; GCN-SDAG-NEXT:    global_store_b128 v[4:5], v[14:17], off offset:80
; GCN-SDAG-NEXT:    global_store_b128 v[4:5], v[22:25], off offset:32
; GCN-SDAG-NEXT:    global_store_b128 v[4:5], v[18:21], off offset:48
; GCN-SDAG-NEXT:    global_store_b128 v[4:5], v[30:33], off
; GCN-SDAG-NEXT:    global_store_b128 v[4:5], v[26:29], off offset:16
; GCN-SDAG-NEXT:    s_wait_xcnt 0x9
; GCN-SDAG-NEXT:    v_dual_mov_b32 v0, v32 :: v_dual_mov_b32 v1, v33
; GCN-SDAG-NEXT:    s_set_pc_i64 s[30:31]
;
; GCN-GISEL-LABEL: test_v16i64_load_store:
; GCN-GISEL:       ; %bb.0:
; GCN-GISEL-NEXT:    s_wait_loadcnt_dscnt 0x0
; GCN-GISEL-NEXT:    s_wait_kmcnt 0x0
; GCN-GISEL-NEXT:    s_clause 0x7
; GCN-GISEL-NEXT:    global_load_b128 v[6:9], v[0:1], off offset:80
; GCN-GISEL-NEXT:    global_load_b128 v[10:13], v[0:1], off
; GCN-GISEL-NEXT:    global_load_b128 v[14:17], v[0:1], off offset:16
; GCN-GISEL-NEXT:    global_load_b128 v[18:21], v[0:1], off offset:32
; GCN-GISEL-NEXT:    global_load_b128 v[22:25], v[0:1], off offset:48
; GCN-GISEL-NEXT:    global_load_b128 v[26:29], v[0:1], off offset:96
; GCN-GISEL-NEXT:    global_load_b128 v[30:33], v[0:1], off offset:112
; GCN-GISEL-NEXT:    global_load_b128 v[34:37], v[0:1], off offset:64
; GCN-GISEL-NEXT:    v_mov_b64_e32 v[38:39], 0
; GCN-GISEL-NEXT:    v_mov_b64_e32 v[48:49], 16
; GCN-GISEL-NEXT:    v_mov_b64_e32 v[50:51], 32
; GCN-GISEL-NEXT:    v_mov_b64_e32 v[52:53], 48
; GCN-GISEL-NEXT:    v_mov_b64_e32 v[66:67], 0x60
; GCN-GISEL-NEXT:    v_mov_b64_e32 v[68:69], 0x70
; GCN-GISEL-NEXT:    v_mov_b64_e32 v[54:55], 64
; GCN-GISEL-NEXT:    s_wait_xcnt 0x0
; GCN-GISEL-NEXT:    v_mov_b64_e32 v[0:1], 0xc8
; GCN-GISEL-NEXT:    v_mov_b64_e32 v[64:65], 0x50
; GCN-GISEL-NEXT:    s_wait_loadcnt 0x6
; GCN-GISEL-NEXT:    global_store_b128 v[38:39], v[10:13], off
; GCN-GISEL-NEXT:    s_wait_loadcnt 0x5
; GCN-GISEL-NEXT:    global_store_b128 v[48:49], v[14:17], off
; GCN-GISEL-NEXT:    s_wait_loadcnt 0x4
; GCN-GISEL-NEXT:    global_store_b128 v[50:51], v[18:21], off
; GCN-GISEL-NEXT:    s_wait_loadcnt 0x3
; GCN-GISEL-NEXT:    global_store_b128 v[52:53], v[22:25], off
; GCN-GISEL-NEXT:    s_wait_loadcnt 0x2
; GCN-GISEL-NEXT:    global_store_b128 v[66:67], v[26:29], off
; GCN-GISEL-NEXT:    s_wait_loadcnt 0x1
; GCN-GISEL-NEXT:    global_store_b128 v[68:69], v[30:33], off
; GCN-GISEL-NEXT:    s_wait_xcnt 0x5
; GCN-GISEL-NEXT:    v_add_nc_u64_e32 v[12:13], v[12:13], v[12:13]
; GCN-GISEL-NEXT:    v_mov_b64_e32 v[2:3], v[8:9]
; GCN-GISEL-NEXT:    v_add_nc_u64_e32 v[10:11], v[10:11], v[10:11]
; GCN-GISEL-NEXT:    s_wait_xcnt 0x4
; GCN-GISEL-NEXT:    v_add_nc_u64_e32 v[14:15], v[14:15], v[14:15]
; GCN-GISEL-NEXT:    v_add_nc_u64_e32 v[16:17], v[16:17], v[16:17]
; GCN-GISEL-NEXT:    s_wait_xcnt 0x3
; GCN-GISEL-NEXT:    v_add_nc_u64_e32 v[18:19], v[18:19], v[18:19]
; GCN-GISEL-NEXT:    v_add_nc_u64_e32 v[20:21], 0x64, v[20:21]
; GCN-GISEL-NEXT:    s_wait_xcnt 0x2
; GCN-GISEL-NEXT:    v_add_nc_u64_e32 v[22:23], v[22:23], v[22:23]
; GCN-GISEL-NEXT:    v_add_nc_u64_e32 v[24:25], v[24:25], v[24:25]
; GCN-GISEL-NEXT:    s_wait_loadcnt 0x0
; GCN-GISEL-NEXT:    v_add_nc_u64_e32 v[48:49], v[34:35], v[34:35]
; GCN-GISEL-NEXT:    v_add_nc_u64_e32 v[50:51], v[36:37], v[36:37]
; GCN-GISEL-NEXT:    v_add_nc_u64_e32 v[6:7], 0xc8, v[6:7]
; GCN-GISEL-NEXT:    v_add_nc_u64_e32 v[8:9], v[8:9], v[8:9]
; GCN-GISEL-NEXT:    s_wait_xcnt 0x1
; GCN-GISEL-NEXT:    v_add_nc_u64_e32 v[26:27], v[26:27], v[26:27]
; GCN-GISEL-NEXT:    v_add_nc_u64_e32 v[28:29], v[28:29], v[28:29]
; GCN-GISEL-NEXT:    s_wait_xcnt 0x0
; GCN-GISEL-NEXT:    v_add_nc_u64_e32 v[30:31], v[30:31], v[30:31]
; GCN-GISEL-NEXT:    v_add_nc_u64_e32 v[32:33], v[32:33], v[32:33]
; GCN-GISEL-NEXT:    s_clause 0x1
; GCN-GISEL-NEXT:    global_store_b128 v[54:55], v[34:37], off
; GCN-GISEL-NEXT:    global_store_b128 v[64:65], v[0:3], off
; GCN-GISEL-NEXT:    s_clause 0x7
; GCN-GISEL-NEXT:    global_store_b128 v[4:5], v[10:13], off
; GCN-GISEL-NEXT:    global_store_b128 v[4:5], v[14:17], off offset:16
; GCN-GISEL-NEXT:    global_store_b128 v[4:5], v[18:21], off offset:32
; GCN-GISEL-NEXT:    global_store_b128 v[4:5], v[22:25], off offset:48
; GCN-GISEL-NEXT:    global_store_b128 v[4:5], v[48:51], off offset:64
; GCN-GISEL-NEXT:    global_store_b128 v[4:5], v[6:9], off offset:80
; GCN-GISEL-NEXT:    global_store_b128 v[4:5], v[26:29], off offset:96
; GCN-GISEL-NEXT:    global_store_b128 v[4:5], v[30:33], off offset:112
; GCN-GISEL-NEXT:    s_wait_xcnt 0x8
; GCN-GISEL-NEXT:    v_dual_mov_b32 v0, v12 :: v_dual_mov_b32 v1, v13
; GCN-GISEL-NEXT:    s_set_pc_i64 s[30:31]
  %a = load <16 x i64>, ptr addrspace(1) %ptr_a, align 4
  %in_a = insertelement <16 x i64> %a, i64 100, i32 5
  store <16 x i64> %in_a, ptr addrspace(1) null
  %b = load <16 x i64>, ptr addrspace(1) %ptr_b, align 4
  %in_b = insertelement <16 x i64> %a, i64 200, i32 10
  store <16 x i64> %in_b, ptr addrspace(1) null
  %add = add <16 x i64> %in_a, %in_b
  store <16 x i64> %add, ptr addrspace(1) %out, align 4
  %elt = extractelement <16 x i64> %add, i32 1
  ret i64 %elt
}

define amdgpu_kernel void @test_v7i16_load_store_kernel(ptr addrspace(1) %ptr1, ptr addrspace(1) %ptr2, ptr addrspace(1) %out) {
; GCN-SDAG-LABEL: test_v7i16_load_store_kernel:
; GCN-SDAG:       ; %bb.0:
; GCN-SDAG-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1 ; msbs: dst=0 src0=0 src1=0 src2=0
; GCN-SDAG-NEXT:    s_load_b128 s[0:3], s[4:5], 0x0 nv
; GCN-SDAG-NEXT:    v_and_b32_e32 v8, 0x3ff, v0
; GCN-SDAG-NEXT:    s_wait_xcnt 0x0
; GCN-SDAG-NEXT:    s_load_b64 s[4:5], s[4:5], 0x10 nv
; GCN-SDAG-NEXT:    v_mov_b64_e32 v[10:11], 8
; GCN-SDAG-NEXT:    v_mov_b64_e32 v[12:13], 0
; GCN-SDAG-NEXT:    s_wait_kmcnt 0x0
; GCN-SDAG-NEXT:    s_clause 0x1
; GCN-SDAG-NEXT:    global_load_b128 v[0:3], v8, s[0:1] scale_offset
; GCN-SDAG-NEXT:    global_load_b128 v[4:7], v8, s[2:3] scale_offset
; GCN-SDAG-NEXT:    s_wait_xcnt 0x0
; GCN-SDAG-NEXT:    v_mov_b64_e32 v[8:9], 12
; GCN-SDAG-NEXT:    s_wait_loadcnt 0x0
; GCN-SDAG-NEXT:    v_pk_add_u16 v3, v3, v7
; GCN-SDAG-NEXT:    v_pk_add_u16 v2, v2, v6
; GCN-SDAG-NEXT:    v_pk_add_u16 v1, v1, v5
; GCN-SDAG-NEXT:    v_pk_add_u16 v0, v0, v4
; GCN-SDAG-NEXT:    v_mov_b32_e32 v4, 0
; GCN-SDAG-NEXT:    s_clause 0x2
; GCN-SDAG-NEXT:    global_store_b16 v[8:9], v3, off
; GCN-SDAG-NEXT:    global_store_b32 v[10:11], v2, off
; GCN-SDAG-NEXT:    global_store_b64 v[12:13], v[0:1], off
; GCN-SDAG-NEXT:    global_store_d16_hi_b16 v4, v2, s[4:5]
; GCN-SDAG-NEXT:    s_endpgm
;
; GCN-GISEL-LABEL: test_v7i16_load_store_kernel:
; GCN-GISEL:       ; %bb.0:
; GCN-GISEL-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1 ; msbs: dst=0 src0=0 src1=0 src2=0
; GCN-GISEL-NEXT:    s_load_b128 s[0:3], s[4:5], 0x0 nv
; GCN-GISEL-NEXT:    v_and_b32_e32 v8, 0x3ff, v0
; GCN-GISEL-NEXT:    s_wait_xcnt 0x0
; GCN-GISEL-NEXT:    s_load_b64 s[4:5], s[4:5], 0x10 nv
; GCN-GISEL-NEXT:    v_mov_b64_e32 v[10:11], 2
; GCN-GISEL-NEXT:    v_mov_b64_e32 v[12:13], 4
; GCN-GISEL-NEXT:    v_mov_b64_e32 v[14:15], 6
; GCN-GISEL-NEXT:    v_mov_b64_e32 v[16:17], 8
; GCN-GISEL-NEXT:    v_mov_b64_e32 v[18:19], 10
; GCN-GISEL-NEXT:    v_mov_b64_e32 v[20:21], 12
; GCN-GISEL-NEXT:    s_wait_kmcnt 0x0
; GCN-GISEL-NEXT:    s_clause 0x1
; GCN-GISEL-NEXT:    global_load_b128 v[0:3], v8, s[0:1] scale_offset
; GCN-GISEL-NEXT:    global_load_b128 v[4:7], v8, s[2:3] scale_offset
; GCN-GISEL-NEXT:    s_wait_xcnt 0x0
; GCN-GISEL-NEXT:    v_mov_b64_e32 v[8:9], 0
; GCN-GISEL-NEXT:    s_wait_loadcnt 0x0
; GCN-GISEL-NEXT:    v_pk_add_u16 v0, v0, v4
; GCN-GISEL-NEXT:    v_pk_add_u16 v1, v1, v5
; GCN-GISEL-NEXT:    v_pk_add_u16 v2, v2, v6
; GCN-GISEL-NEXT:    v_mov_b32_e32 v4, 0
; GCN-GISEL-NEXT:    v_pk_add_u16 v3, v3, v7
; GCN-GISEL-NEXT:    s_clause 0x6
; GCN-GISEL-NEXT:    global_store_b16 v[8:9], v0, off
; GCN-GISEL-NEXT:    global_store_d16_hi_b16 v[10:11], v0, off
; GCN-GISEL-NEXT:    global_store_b16 v[12:13], v1, off
; GCN-GISEL-NEXT:    global_store_d16_hi_b16 v[14:15], v1, off
; GCN-GISEL-NEXT:    global_store_b16 v[16:17], v2, off
; GCN-GISEL-NEXT:    global_store_d16_hi_b16 v[18:19], v2, off
; GCN-GISEL-NEXT:    global_store_b16 v[20:21], v3, off
; GCN-GISEL-NEXT:    global_store_d16_hi_b16 v4, v2, s[4:5]
; GCN-GISEL-NEXT:    s_endpgm
  %tid = call i32 @llvm.amdgcn.workitem.id.x()
  %gep1 = getelementptr inbounds <7 x i16>, ptr addrspace(1) %ptr1, i32 %tid
  %gep2 = getelementptr inbounds <7 x i16>, ptr addrspace(1) %ptr2, i32 %tid
  %vec1 = load <7 x i16>, ptr addrspace(1) %gep1
  %insert = insertelement <7 x i16> %vec1, i16 20, i32 4
  %vec2 = load <7 x i16>, ptr addrspace(1) %gep2
  %add = add <7 x i16> %vec1, %vec2
  store <7 x i16> %add, ptr addrspace(1) null
  %elt = extractelement <7 x i16> %add, i32 5
  store i16 %elt, ptr addrspace(1) %out
  ret void
}

;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; GCN: {{.*}}
