; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=amdgcn-- -mcpu=gfx1300 -verify-machineinstrs -o - %s | FileCheck %s

target datalayout = "A5"

@exchange = external local_unnamed_addr addrspace(10) global [70 x float], align 4

define dso_local amdgpu_kernel void @_Z3foov() local_unnamed_addr "amdgpu-wavegroup-enable" !reqd_work_group_size !{i32 128, i32 1, i32 1} {
; CHECK-LABEL: _Z3foov:
; CHECK:       _Z3foov$local:
; CHECK-NEXT:    .type _Z3foov$local,@function
; CHECK-NEXT:  ; %bb.0: ; %entry
; CHECK-NEXT:    s_getreg_b32 s0, hwreg(HW_REG_WAVE_GROUP_INFO, 16, 4)
; CHECK-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(SKIP_2) | instid1(SALU_CYCLE_1)
; CHECK-NEXT:    s_mul_i32 s1, s0, 9
; CHECK-NEXT:    s_mul_i32 s33, s0, s8
; CHECK-NEXT:    s_add_co_u32 s1, s1, 0x46
; CHECK-NEXT:    s_set_gpr_idx_u32 idx0, s1
; CHECK-NEXT:    ; sched_barrier mask(0x00000000)
; CHECK-NEXT:    s_mov_b32 s0, 0
; CHECK-NEXT:    s_mov_b32 s1, 0
; CHECK-NEXT:    ; implicit-def: $vgpr0
; CHECK-NEXT:    ; implicit-def: $vgpr1
; CHECK-NEXT:    ; implicit-def: $vgpr2
; CHECK-NEXT:    ; implicit-def: $vgpr3
; CHECK-NEXT:    ; implicit-def: $vgpr4
; CHECK-NEXT:    ; implicit-def: $vgpr5
; CHECK-NEXT:    ; implicit-def: $vgpr6
; CHECK-NEXT:    ; implicit-def: $vgpr7
; CHECK-NEXT:  .LBB0_1: ; %for.body
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; CHECK-NEXT:    s_and_b32 s2, s1, 7
; CHECK-NEXT:    s_lshr_b32 s3, s0, 2
; CHECK-NEXT:    s_cmp_eq_u32 s2, 7
; CHECK-NEXT:    s_set_gpr_idx_u32 idx1, s3
; CHECK-NEXT:    s_cselect_b32 s3, -1, 0
; CHECK-NEXT:    s_cmp_eq_u32 s2, 6
; CHECK-NEXT:    s_set_vgpr_frames 4 ; vsrc0_idx=0 vsrc1_idx=1 vsrc2_idx=0 vdst_idx=0 vsrc0_msb=0 vsrc1_msb=0 vsrc2_msb=0 vdst_msb=0
; CHECK-NEXT:    v_cndmask_b32_e64 v7, v7, g1[0], s3
; CHECK-NEXT:    s_cselect_b32 s3, -1, 0
; CHECK-NEXT:    s_cmp_eq_u32 s2, 5
; CHECK-NEXT:    v_cndmask_b32_e64 v6, v6, g1[0], s3
; CHECK-NEXT:    s_cselect_b32 s3, -1, 0
; CHECK-NEXT:    s_cmp_eq_u32 s2, 4
; CHECK-NEXT:    v_cndmask_b32_e64 v5, v5, g1[0], s3
; CHECK-NEXT:    s_cselect_b32 s3, -1, 0
; CHECK-NEXT:    s_cmp_eq_u32 s2, 3
; CHECK-NEXT:    v_cndmask_b32_e64 v4, v4, g1[0], s3
; CHECK-NEXT:    s_cselect_b32 s3, -1, 0
; CHECK-NEXT:    s_cmp_eq_u32 s2, 2
; CHECK-NEXT:    v_cndmask_b32_e64 v3, v3, g1[0], s3
; CHECK-NEXT:    s_cselect_b32 s3, -1, 0
; CHECK-NEXT:    s_cmp_eq_u32 s2, 1
; CHECK-NEXT:    v_cndmask_b32_e64 v2, v2, g1[0], s3
; CHECK-NEXT:    s_cselect_b32 s3, -1, 0
; CHECK-NEXT:    s_cmp_eq_u32 s2, 0
; CHECK-NEXT:    v_cndmask_b32_e64 v1, v1, g1[0], s3
; CHECK-NEXT:    s_cselect_b32 s2, -1, 0
; CHECK-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; CHECK-NEXT:    v_cndmask_b32_e64 v0, v0, g1[0], s2
; CHECK-NEXT:    s_add_co_i32 s1, s1, 1
; CHECK-NEXT:    s_add_co_i32 s0, s0, 4
; CHECK-NEXT:    s_cmp_lg_u32 s1, 0x46
; CHECK-NEXT:    s_set_vgpr_frames 0 ; vsrc0_idx=0 vsrc1_idx=0 vsrc2_idx=0 vdst_idx=0 vsrc0_msb=0 vsrc1_msb=0 vsrc2_msb=0 vdst_msb=0
; CHECK-NEXT:    s_cbranch_scc1 .LBB0_1
; CHECK-NEXT:  ; %bb.2: ; %for.body8.preheader
; CHECK-NEXT:    s_mov_b32 s0, 0
; CHECK-NEXT:    s_mov_b32 s1, 0
; CHECK-NEXT:  .LBB0_3: ; %for.body8
; CHECK-NEXT:    ; =>This Inner Loop Header: Depth=1
; CHECK-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(SALU_CYCLE_1)
; CHECK-NEXT:    s_and_b32 s2, s1, 7
; CHECK-NEXT:    s_cmp_eq_u32 s2, 1
; CHECK-NEXT:    s_cselect_b32 vcc_lo, -1, 0
; CHECK-NEXT:    s_cmp_eq_u32 s2, 2
; CHECK-NEXT:    v_cndmask_b32_e32 v8, v0, v1, vcc_lo
; CHECK-NEXT:    s_cselect_b32 vcc_lo, -1, 0
; CHECK-NEXT:    s_cmp_eq_u32 s2, 3
; CHECK-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_1)
; CHECK-NEXT:    v_cndmask_b32_e32 v8, v8, v2, vcc_lo
; CHECK-NEXT:    s_cselect_b32 vcc_lo, -1, 0
; CHECK-NEXT:    s_cmp_eq_u32 s2, 4
; CHECK-NEXT:    v_cndmask_b32_e32 v8, v8, v3, vcc_lo
; CHECK-NEXT:    s_cselect_b32 vcc_lo, -1, 0
; CHECK-NEXT:    s_cmp_eq_u32 s2, 5
; CHECK-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_1)
; CHECK-NEXT:    v_cndmask_b32_e32 v8, v8, v4, vcc_lo
; CHECK-NEXT:    s_cselect_b32 vcc_lo, -1, 0
; CHECK-NEXT:    s_cmp_eq_u32 s2, 6
; CHECK-NEXT:    v_cndmask_b32_e32 v8, v8, v5, vcc_lo
; CHECK-NEXT:    s_cselect_b32 vcc_lo, -1, 0
; CHECK-NEXT:    s_cmp_eq_u32 s2, 7
; CHECK-NEXT:    s_cselect_b32 s2, -1, 0
; CHECK-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; CHECK-NEXT:    v_cndmask_b32_e32 v8, v8, v6, vcc_lo
; CHECK-NEXT:    s_add_co_i32 s1, s1, 1
; CHECK-NEXT:    s_lshr_b32 s3, s0, 2
; CHECK-NEXT:    s_add_co_i32 s0, s0, 4
; CHECK-NEXT:    s_cmp_eq_u32 s1, 0x46
; CHECK-NEXT:    s_set_gpr_idx_u32 idx1, s3
; CHECK-NEXT:    s_set_vgpr_frames 64 ; vsrc0_idx=0 vsrc1_idx=0 vsrc2_idx=0 vdst_idx=1 vsrc0_msb=0 vsrc1_msb=0 vsrc2_msb=0 vdst_msb=0
; CHECK-NEXT:    v_cndmask_b32_e64 g1[0], v8, v7, s2
; CHECK-NEXT:    s_set_vgpr_frames 0 ; vsrc0_idx=0 vsrc1_idx=0 vsrc2_idx=0 vdst_idx=0 vsrc0_msb=0 vsrc1_msb=0 vsrc2_msb=0 vdst_msb=0
; CHECK-NEXT:    s_cbranch_scc0 .LBB0_3
; CHECK-NEXT:  ; %bb.4: ; %for.cond.cleanup6
; CHECK-NEXT:    s_endpgm
entry:
  br label %for.body

for.body:                                         ; preds = %entry, %for.body
  %i.024 = phi i32 [ 0, %entry ], [ %inc, %for.body ]
  %promotealloca23 = phi <8 x float> [ undef, %entry ], [ %1, %for.body ]
  %arrayidx = getelementptr inbounds [70 x float], ptr addrspace(10) @exchange, i32 0, i32 %i.024
  %0 = load float, ptr addrspace(10) %arrayidx, align 4, !tbaa !4
  %rem = urem i32 %i.024, 8
  %idxprom1 = zext nneg i32 %rem to i64
  %1 = insertelement <8 x float> %promotealloca23, float %0, i64 %idxprom1
  %inc = add nuw nsw i32 %i.024, 1
  %exitcond.not = icmp eq i32 %inc, 70
  br i1 %exitcond.not, label %for.body8, label %for.body, !llvm.loop !8

for.cond.cleanup6:                                ; preds = %for.body8
  ret void

for.body8:                                        ; preds = %for.body, %for.body8
  %i3.025 = phi i32 [ %inc15, %for.body8 ], [ 0, %for.body ]
  %rem9 = urem i32 %i3.025, 8
  %idxprom10 = zext nneg i32 %rem9 to i64
  %2 = extractelement <8 x float> %1, i64 %idxprom10
  %arrayidx13 = getelementptr inbounds [70 x float], ptr addrspace(10) @exchange, i32 0, i32 %i3.025
  store float %2, ptr addrspace(10) %arrayidx13, align 4, !tbaa !4
  %inc15 = add nuw nsw i32 %i3.025, 1
  %exitcond26.not = icmp eq i32 %inc15, 70
  br i1 %exitcond26.not, label %for.cond.cleanup6, label %for.body8, !llvm.loop !11
}

!llvm.module.flags = !{!0, !1, !2}

!0 = !{i32 1, !"amdhsa_code_object_version", i32 500}
!1 = !{i32 1, !"amdgpu_printf_kind", !"hostcall"}
!2 = !{i32 1, !"wchar_size", i32 4}
!4 = !{!5, !5, i64 0}
!5 = !{!"float", !6, i64 0}
!6 = !{!"omnipotent char", !7, i64 0}
!7 = !{!"Simple C++ TBAA"}
!8 = distinct !{!8, !9, !10}
!9 = !{!"llvm.loop.mustprogress"}
!10 = !{!"llvm.loop.unroll.disable"}
!11 = distinct !{!11, !9, !10}
