# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# Reduced from a large FMHA-style region (MFMA tower + VALU + V_PK_FMA_F32 +
# IGLP_OPT 4 between SCHED_BARRIERs). Pair with `iglp-unpack-mfma-vpk.ll` (IR).
#
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx942 -run-pass=amdgpu-iglp-unpack -o - %s | FileCheck %s

---
name:            iglp_unpack_mfma_vpk
tracksRegLiveness: true
body:             |
  bb.0:
    ; CHECK-LABEL: name: iglp_unpack_mfma_vpk
    ; CHECK: SCHED_BARRIER 0
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:vreg_128_align2 = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:vreg_128_align2 = IMPLICIT_DEF
    ; CHECK-NEXT: early-clobber %2:vreg_512_align2 = contract V_MFMA_F32_32X32X8F16_vgprcd_e64 [[DEF]].sub0_sub1, [[DEF1]].sub0_sub1, 0, 0, 0, 0, implicit $mode, implicit $exec
    ; CHECK-NEXT: dead [[V_MFMA_F32_32X32X8F16_mac_vgprcd_e64_:%[0-9]+]]:vreg_512_align2 = contract V_MFMA_F32_32X32X8F16_mac_vgprcd_e64 [[DEF]].sub2_sub3, [[DEF1]].sub2_sub3, [[V_MFMA_F32_32X32X8F16_mac_vgprcd_e64_]], 0, 0, 0, implicit $mode, implicit $exec
    ; CHECK-NEXT: dead [[DEF2:%[0-9]+]]:sgpr_256 = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF3:%[0-9]+]]:sgpr_64 = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF4:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF5:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; CHECK-NEXT: dead [[V_FMA_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_FMA_F32_e64 0, [[DEF5]].sub0, 0, [[DEF3]].sub0, 0, [[DEF4]].sub0, 0, 0, implicit $mode, implicit $exec
    ; CHECK-NEXT: dead [[V_FMA_F32_e64_1:%[0-9]+]]:vgpr_32 = nofpexcept V_FMA_F32_e64 0, [[DEF5]].sub1, 0, [[DEF3]].sub0, 0, [[DEF4]].sub1, 0, 0, implicit $mode, implicit $exec
    ; CHECK-NEXT: IGLP_OPT 4
    ; CHECK-NEXT: SCHED_BARRIER 0
    ; CHECK-NEXT: S_ENDPGM 0
    SCHED_BARRIER 0
    %0:vreg_128_align2 = IMPLICIT_DEF
    %1:vreg_128_align2 = IMPLICIT_DEF
    early-clobber %2:vreg_512_align2 = contract V_MFMA_F32_32X32X8F16_vgprcd_e64 %0.sub0_sub1:vreg_128_align2, %1.sub0_sub1:vreg_128_align2, 0, 0, 0, 0, implicit $mode, implicit $exec
    %2:vreg_512_align2 = contract V_MFMA_F32_32X32X8F16_mac_vgprcd_e64 %0.sub2_sub3:vreg_128_align2, %1.sub2_sub3:vreg_128_align2, %2:vreg_512_align2, 0, 0, 0, implicit $mode, implicit $exec
    %3:sgpr_256 = IMPLICIT_DEF
    %8:sgpr_64 = IMPLICIT_DEF
    %10:vreg_64_align2 = IMPLICIT_DEF
    %28:vreg_64_align2 = IMPLICIT_DEF
    %31:vreg_64_align2 = nofpexcept V_PK_FMA_F32 8, %28:vreg_64_align2, 0, %8:sgpr_64, 8, %10:vreg_64_align2, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    IGLP_OPT 4
    SCHED_BARRIER 0
    S_ENDPGM 0
...
