; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx942 < %s | FileCheck %s --check-prefixes=CHECK

declare void @extern_fn() #0          ; forces HasIndirectCall path
define void @big_vgpr_user() #1 {
  %v0 = call i32 asm sideeffect "; def $0", "=v"()
  %v1 = call i32 asm sideeffect "; def $0", "=v"()
  %v2 = call i32 asm sideeffect "; def $0", "=v"()
  %v3 = call i32 asm sideeffect "; def $0", "=v"()
  %v4 = call i32 asm sideeffect "; def $0", "=v"()
  %v5 = call i32 asm sideeffect "; def $0", "=v"()
  %v6 = call i32 asm sideeffect "; def $0", "=v"()
  %v7 = call i32 asm sideeffect "; def $0", "=v"()
  %v8 = call i32 asm sideeffect "; def $0", "=v"()
  %v9 = call i32 asm sideeffect "; def $0", "=v"()
  %v10 = call i32 asm sideeffect "; def $0", "=v"()
  %v11 = call i32 asm sideeffect "; def $0", "=v"()
  %v12 = call i32 asm sideeffect "; def $0", "=v"()
  %v13 = call i32 asm sideeffect "; def $0", "=v"()
  %v14 = call i32 asm sideeffect "; def $0", "=v"()
  %v15 = call i32 asm sideeffect "; def $0", "=v"()
  %v16 = call i32 asm sideeffect "; def $0", "=v"()
  %v17 = call i32 asm sideeffect "; def $0", "=v"()
  %v18 = call i32 asm sideeffect "; def $0", "=v"()
  %v19 = call i32 asm sideeffect "; def $0", "=v"()
  %v20 = call i32 asm sideeffect "; def $0", "=v"()
  %v21 = call i32 asm sideeffect "; def $0", "=v"()
  %v22 = call i32 asm sideeffect "; def $0", "=v"()
  %v23 = call i32 asm sideeffect "; def $0", "=v"()
  %v24 = call i32 asm sideeffect "; def $0", "=v"()
  %v25 = call i32 asm sideeffect "; def $0", "=v"()
  %v26 = call i32 asm sideeffect "; def $0", "=v"()
  %v27 = call i32 asm sideeffect "; def $0", "=v"()
  %v28 = call i32 asm sideeffect "; def $0", "=v"()
  %v29 = call i32 asm sideeffect "; def $0", "=v"()
  %v30 = call i32 asm sideeffect "; def $0", "=v"()
  %v31 = call i32 asm sideeffect "; def $0", "=v"()
  %v32 = call i32 asm sideeffect "; def $0", "=v"()
  %v33 = call i32 asm sideeffect "; def $0", "=v"()
  %v34 = call i32 asm sideeffect "; def $0", "=v"()
  %v35 = call i32 asm sideeffect "; def $0", "=v"()
  %v36 = call i32 asm sideeffect "; def $0", "=v"()
  %v37 = call i32 asm sideeffect "; def $0", "=v"()
  %v38 = call i32 asm sideeffect "; def $0", "=v"()
  %v39 = call i32 asm sideeffect "; def $0", "=v"()
  %v40 = call i32 asm sideeffect "; def $0", "=v"()
  %v41 = call i32 asm sideeffect "; def $0", "=v"()
  %v42 = call i32 asm sideeffect "; def $0", "=v"()
  %v43 = call i32 asm sideeffect "; def $0", "=v"()
  %v44 = call i32 asm sideeffect "; def $0", "=v"()
  %v45 = call i32 asm sideeffect "; def $0", "=v"()
  %v46 = call i32 asm sideeffect "; def $0", "=v"()
  %v47 = call i32 asm sideeffect "; def $0", "=v"()
  %v48 = call i32 asm sideeffect "; def $0", "=v"()
  %v49 = call i32 asm sideeffect "; def $0", "=v"()
  %v50 = call i32 asm sideeffect "; def $0", "=v"()
  %v51 = call i32 asm sideeffect "; def $0", "=v"()
  %v52 = call i32 asm sideeffect "; def $0", "=v"()
  %v53 = call i32 asm sideeffect "; def $0", "=v"()
  %v54 = call i32 asm sideeffect "; def $0", "=v"()
  %v55 = call i32 asm sideeffect "; def $0", "=v"()
  %v56 = call i32 asm sideeffect "; def $0", "=v"()
  %v57 = call i32 asm sideeffect "; def $0", "=v"()
  %v58 = call i32 asm sideeffect "; def $0", "=v"()
  %v59 = call i32 asm sideeffect "; def $0", "=v"()
  %v60 = call i32 asm sideeffect "; def $0", "=v"()
  %v61 = call i32 asm sideeffect "; def $0", "=v"()
  %v62 = call i32 asm sideeffect "; def $0", "=v"()
  %v63 = call i32 asm sideeffect "; def $0", "=v"()
  %v64 = call i32 asm sideeffect "; def $0", "=v"()
  %v65 = call i32 asm sideeffect "; def $0", "=v"()
  %v66 = call i32 asm sideeffect "; def $0", "=v"()
  %v67 = call i32 asm sideeffect "; def $0", "=v"()
  %v68 = call i32 asm sideeffect "; def $0", "=v"()
  %v69 = call i32 asm sideeffect "; def $0", "=v"()
  %v70 = call i32 asm sideeffect "; def $0", "=v"()
  %v71 = call i32 asm sideeffect "; def $0", "=v"()
  %v72 = call i32 asm sideeffect "; def $0", "=v"()
  %v73 = call i32 asm sideeffect "; def $0", "=v"()
  %v74 = call i32 asm sideeffect "; def $0", "=v"()
  %v75 = call i32 asm sideeffect "; def $0", "=v"()
  %v76 = call i32 asm sideeffect "; def $0", "=v"()
  %v77 = call i32 asm sideeffect "; def $0", "=v"()
  %v78 = call i32 asm sideeffect "; def $0", "=v"()
  %v79 = call i32 asm sideeffect "; def $0", "=v"()
  %v80 = call i32 asm sideeffect "; def $0", "=v"()
  %v81 = call i32 asm sideeffect "; def $0", "=v"()
  %v82 = call i32 asm sideeffect "; def $0", "=v"()
  %v83 = call i32 asm sideeffect "; def $0", "=v"()
  %v84 = call i32 asm sideeffect "; def $0", "=v"()
  %v85 = call i32 asm sideeffect "; def $0", "=v"()
  %v86 = call i32 asm sideeffect "; def $0", "=v"()
  %v87 = call i32 asm sideeffect "; def $0", "=v"()
  %v88 = call i32 asm sideeffect "; def $0", "=v"()
  %v89 = call i32 asm sideeffect "; def $0", "=v"()
  %v90 = call i32 asm sideeffect "; def $0", "=v"()
  %v91 = call i32 asm sideeffect "; def $0", "=v"()
  %v92 = call i32 asm sideeffect "; def $0", "=v"()
  %v93 = call i32 asm sideeffect "; def $0", "=v"()
  %v94 = call i32 asm sideeffect "; def $0", "=v"()
  %v95 = call i32 asm sideeffect "; def $0", "=v"()
  %v96 = call i32 asm sideeffect "; def $0", "=v"()
  %v97 = call i32 asm sideeffect "; def $0", "=v"()
  %v98 = call i32 asm sideeffect "; def $0", "=v"()
  %v99 = call i32 asm sideeffect "; def $0", "=v"()
  %v100 = call i32 asm sideeffect "; def $0", "=v"()
  %v101 = call i32 asm sideeffect "; def $0", "=v"()
  %v102 = call i32 asm sideeffect "; def $0", "=v"()
  %v103 = call i32 asm sideeffect "; def $0", "=v"()
  %v104 = call i32 asm sideeffect "; def $0", "=v"()
  %v105 = call i32 asm sideeffect "; def $0", "=v"()
  %v106 = call i32 asm sideeffect "; def $0", "=v"()
  %v107 = call i32 asm sideeffect "; def $0", "=v"()
  %v108 = call i32 asm sideeffect "; def $0", "=v"()
  %v109 = call i32 asm sideeffect "; def $0", "=v"()
  %v110 = call i32 asm sideeffect "; def $0", "=v"()
  %v111 = call i32 asm sideeffect "; def $0", "=v"()
  %v112 = call i32 asm sideeffect "; def $0", "=v"()
  %v113 = call i32 asm sideeffect "; def $0", "=v"()
  %v114 = call i32 asm sideeffect "; def $0", "=v"()
  %v115 = call i32 asm sideeffect "; def $0", "=v"()
  %v116 = call i32 asm sideeffect "; def $0", "=v"()
  %v117 = call i32 asm sideeffect "; def $0", "=v"()
  %v118 = call i32 asm sideeffect "; def $0", "=v"()
  %v119 = call i32 asm sideeffect "; def $0", "=v"()
  %v120 = call i32 asm sideeffect "; def $0", "=v"()
  %v121 = call i32 asm sideeffect "; def $0", "=v"()
  %v122 = call i32 asm sideeffect "; def $0", "=v"()
  %v123 = call i32 asm sideeffect "; def $0", "=v"()
  %v124 = call i32 asm sideeffect "; def $0", "=v"()
  %v125 = call i32 asm sideeffect "; def $0", "=v"()
  call void asm sideeffect "; use $0", "v"(i32 %v0)
  call void asm sideeffect "; use $0", "v"(i32 %v1)
  call void asm sideeffect "; use $0", "v"(i32 %v2)
  call void asm sideeffect "; use $0", "v"(i32 %v3)
  call void asm sideeffect "; use $0", "v"(i32 %v4)
  call void asm sideeffect "; use $0", "v"(i32 %v5)
  call void asm sideeffect "; use $0", "v"(i32 %v6)
  call void asm sideeffect "; use $0", "v"(i32 %v7)
  call void asm sideeffect "; use $0", "v"(i32 %v8)
  call void asm sideeffect "; use $0", "v"(i32 %v9)
  call void asm sideeffect "; use $0", "v"(i32 %v10)
  call void asm sideeffect "; use $0", "v"(i32 %v11)
  call void asm sideeffect "; use $0", "v"(i32 %v12)
  call void asm sideeffect "; use $0", "v"(i32 %v13)
  call void asm sideeffect "; use $0", "v"(i32 %v14)
  call void asm sideeffect "; use $0", "v"(i32 %v15)
  call void asm sideeffect "; use $0", "v"(i32 %v16)
  call void asm sideeffect "; use $0", "v"(i32 %v17)
  call void asm sideeffect "; use $0", "v"(i32 %v18)
  call void asm sideeffect "; use $0", "v"(i32 %v19)
  call void asm sideeffect "; use $0", "v"(i32 %v20)
  call void asm sideeffect "; use $0", "v"(i32 %v21)
  call void asm sideeffect "; use $0", "v"(i32 %v22)
  call void asm sideeffect "; use $0", "v"(i32 %v23)
  call void asm sideeffect "; use $0", "v"(i32 %v24)
  call void asm sideeffect "; use $0", "v"(i32 %v25)
  call void asm sideeffect "; use $0", "v"(i32 %v26)
  call void asm sideeffect "; use $0", "v"(i32 %v27)
  call void asm sideeffect "; use $0", "v"(i32 %v28)
  call void asm sideeffect "; use $0", "v"(i32 %v29)
  call void asm sideeffect "; use $0", "v"(i32 %v30)
  call void asm sideeffect "; use $0", "v"(i32 %v31)
  call void asm sideeffect "; use $0", "v"(i32 %v32)
  call void asm sideeffect "; use $0", "v"(i32 %v33)
  call void asm sideeffect "; use $0", "v"(i32 %v34)
  call void asm sideeffect "; use $0", "v"(i32 %v35)
  call void asm sideeffect "; use $0", "v"(i32 %v36)
  call void asm sideeffect "; use $0", "v"(i32 %v37)
  call void asm sideeffect "; use $0", "v"(i32 %v38)
  call void asm sideeffect "; use $0", "v"(i32 %v39)
  call void asm sideeffect "; use $0", "v"(i32 %v40)
  call void asm sideeffect "; use $0", "v"(i32 %v41)
  call void asm sideeffect "; use $0", "v"(i32 %v42)
  call void asm sideeffect "; use $0", "v"(i32 %v43)
  call void asm sideeffect "; use $0", "v"(i32 %v44)
  call void asm sideeffect "; use $0", "v"(i32 %v45)
  call void asm sideeffect "; use $0", "v"(i32 %v46)
  call void asm sideeffect "; use $0", "v"(i32 %v47)
  call void asm sideeffect "; use $0", "v"(i32 %v48)
  call void asm sideeffect "; use $0", "v"(i32 %v49)
  call void asm sideeffect "; use $0", "v"(i32 %v50)
  call void asm sideeffect "; use $0", "v"(i32 %v51)
  call void asm sideeffect "; use $0", "v"(i32 %v52)
  call void asm sideeffect "; use $0", "v"(i32 %v53)
  call void asm sideeffect "; use $0", "v"(i32 %v54)
  call void asm sideeffect "; use $0", "v"(i32 %v55)
  call void asm sideeffect "; use $0", "v"(i32 %v56)
  call void asm sideeffect "; use $0", "v"(i32 %v57)
  call void asm sideeffect "; use $0", "v"(i32 %v58)
  call void asm sideeffect "; use $0", "v"(i32 %v59)
  call void asm sideeffect "; use $0", "v"(i32 %v60)
  call void asm sideeffect "; use $0", "v"(i32 %v61)
  call void asm sideeffect "; use $0", "v"(i32 %v62)
  call void asm sideeffect "; use $0", "v"(i32 %v63)
  call void asm sideeffect "; use $0", "v"(i32 %v64)
  call void asm sideeffect "; use $0", "v"(i32 %v65)
  call void asm sideeffect "; use $0", "v"(i32 %v66)
  call void asm sideeffect "; use $0", "v"(i32 %v67)
  call void asm sideeffect "; use $0", "v"(i32 %v68)
  call void asm sideeffect "; use $0", "v"(i32 %v69)
  call void asm sideeffect "; use $0", "v"(i32 %v70)
  call void asm sideeffect "; use $0", "v"(i32 %v71)
  call void asm sideeffect "; use $0", "v"(i32 %v72)
  call void asm sideeffect "; use $0", "v"(i32 %v73)
  call void asm sideeffect "; use $0", "v"(i32 %v74)
  call void asm sideeffect "; use $0", "v"(i32 %v75)
  call void asm sideeffect "; use $0", "v"(i32 %v76)
  call void asm sideeffect "; use $0", "v"(i32 %v77)
  call void asm sideeffect "; use $0", "v"(i32 %v78)
  call void asm sideeffect "; use $0", "v"(i32 %v79)
  call void asm sideeffect "; use $0", "v"(i32 %v80)
  call void asm sideeffect "; use $0", "v"(i32 %v81)
  call void asm sideeffect "; use $0", "v"(i32 %v82)
  call void asm sideeffect "; use $0", "v"(i32 %v83)
  call void asm sideeffect "; use $0", "v"(i32 %v84)
  call void asm sideeffect "; use $0", "v"(i32 %v85)
  call void asm sideeffect "; use $0", "v"(i32 %v86)
  call void asm sideeffect "; use $0", "v"(i32 %v87)
  call void asm sideeffect "; use $0", "v"(i32 %v88)
  call void asm sideeffect "; use $0", "v"(i32 %v89)
  call void asm sideeffect "; use $0", "v"(i32 %v90)
  call void asm sideeffect "; use $0", "v"(i32 %v91)
  call void asm sideeffect "; use $0", "v"(i32 %v92)
  call void asm sideeffect "; use $0", "v"(i32 %v93)
  call void asm sideeffect "; use $0", "v"(i32 %v94)
  call void asm sideeffect "; use $0", "v"(i32 %v95)
  call void asm sideeffect "; use $0", "v"(i32 %v96)
  call void asm sideeffect "; use $0", "v"(i32 %v97)
  call void asm sideeffect "; use $0", "v"(i32 %v98)
  call void asm sideeffect "; use $0", "v"(i32 %v99)
  call void asm sideeffect "; use $0", "v"(i32 %v100)
  call void asm sideeffect "; use $0", "v"(i32 %v101)
  call void asm sideeffect "; use $0", "v"(i32 %v102)
  call void asm sideeffect "; use $0", "v"(i32 %v103)
  call void asm sideeffect "; use $0", "v"(i32 %v104)
  call void asm sideeffect "; use $0", "v"(i32 %v105)
  call void asm sideeffect "; use $0", "v"(i32 %v106)
  call void asm sideeffect "; use $0", "v"(i32 %v107)
  call void asm sideeffect "; use $0", "v"(i32 %v108)
  call void asm sideeffect "; use $0", "v"(i32 %v109)
  call void asm sideeffect "; use $0", "v"(i32 %v110)
  call void asm sideeffect "; use $0", "v"(i32 %v111)
  call void asm sideeffect "; use $0", "v"(i32 %v112)
  call void asm sideeffect "; use $0", "v"(i32 %v113)
  call void asm sideeffect "; use $0", "v"(i32 %v114)
  call void asm sideeffect "; use $0", "v"(i32 %v115)
  call void asm sideeffect "; use $0", "v"(i32 %v116)
  call void asm sideeffect "; use $0", "v"(i32 %v117)
  call void asm sideeffect "; use $0", "v"(i32 %v118)
  call void asm sideeffect "; use $0", "v"(i32 %v119)
  call void asm sideeffect "; use $0", "v"(i32 %v120)
  call void asm sideeffect "; use $0", "v"(i32 %v121)
  call void asm sideeffect "; use $0", "v"(i32 %v122)
  call void asm sideeffect "; use $0", "v"(i32 %v123)
  call void asm sideeffect "; use $0", "v"(i32 %v124)
  call void asm sideeffect "; use $0", "v"(i32 %v125)
  ret void
}
define internal void @small_callee() {
    ret void
}

define amdgpu_kernel void @kernel_indirect_attributed() #0 {
    
    call void @extern_fn()
    ret void
}

; CHECK: .set .Lkernel_indirect_attributed.num_vgpr, min(64, max(32, amdgpu.max_num_vgpr))
; CHECK: .set .Lkernel_indirect_attributed.num_agpr, min(64, max(0, amdgpu.max_num_agpr))

define amdgpu_kernel void @kernel_indirect_unattributed() { 
    call void @extern_fn()
    ret void
}

; CHECK: .set .Lkernel_indirect_unattributed.num_vgpr, min(64, max(32, amdgpu.max_num_vgpr))
; CHECK: .set .Lkernel_indirect_unattributed.num_agpr, min(64, max(0, amdgpu.max_num_agpr))

define amdgpu_kernel void @kernel_direct_only() {
    call void @small_callee()
    ret void
}

; CHECK: .set .Lkernel_direct_only.num_vgpr, max({{[0-9]+}}, .Lsmall_callee.num_vgpr)


attributes #0 = { "amdgpu-flat-work-group-size"="1,1024" }
attributes #1 = {nounwind noinline norecurse "amdgpu-agpr-alloc"="0"}

; CHECK: .set amdgpu.max_num_vgpr, {{[0-9]+}}

; CHECK-LABEL: .symbol: kernel_indirect_attributed.kd
; CHECK: .vgpr_count: 64

; CHECK-LABEL:  .symbol: kernel_indirect_unattributed.kd
; CHECK: .vgpr_count: 64

; CHECK-LABEL: .symbol: kernel_direct_only.kd
; CHECK: .vgpr_count: 32

