; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=amdgcn -mcpu=gfx900 < %s | FileCheck -check-prefix=GFX9 %s

; Reproducer from https://github.com/llvm/llvm-project/issues/89971
; A VGPR-producing zext i1 feeding an inline asm with "s" constraint must
; be moved to SGPR (via v_readfirstlane_b32), not left as a VGPR.
define hidden i32 @test_s_constraint_from_ballot(i32 noundef %mask) {
; GFX9-LABEL: test_s_constraint_from_ballot:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX9-NEXT:    v_cmp_ne_u32_e32 vcc, 0, v0
; GFX9-NEXT:    s_cmp_eq_u64 vcc, 0
; GFX9-NEXT:    s_cselect_b64 s[4:5], -1, 0
; GFX9-NEXT:    v_cndmask_b32_e64 v0, 0, 1, s[4:5]
; GFX9-NEXT:    v_readfirstlane_b32 s4, v0
; GFX9-NEXT:    ;;#ASMSTART
; GFX9-NEXT:    s_mov_b32 s4, s4
; GFX9-NEXT:    ;;#ASMEND
; GFX9-NEXT:    v_mov_b32_e32 v0, s4
; GFX9-NEXT:    s_setpc_b64 s[30:31]
  %tobool = icmp ne i32 %mask, 0
  %ballot = tail call i64 @llvm.amdgcn.ballot.i64(i1 %tobool)
  %cmp = icmp eq i64 %ballot, 0
  %conv = zext i1 %cmp to i32
  %result = tail call i32 asm sideeffect "s_mov_b32 $0, $1", "=s,s"(i32 %conv)
  ret i32 %result
}

declare i64 @llvm.amdgcn.ballot.i64(i1)
