; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: not llc -mtriple=amdgcn -mcpu=gfx908 -filetype=null %s 2>&1 | FileCheck -check-prefix=ERR %s
; RUN: llc -mtriple=amdgcn -mcpu=gfx90a < %s | FileCheck %s

; FIXME: Shouldn't emit and
; ERR: error: could not allocate input reg for constraint 'VA'
define void @use_A_i16(i16 %x) {
; CHECK-LABEL: use_A_i16:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; CHECK-NEXT:    ;;#ASMSTART
; CHECK-NEXT:    ; use v0
; CHECK-NEXT:    ;;#ASMEND
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  call void asm sideeffect "; use $0", "^VA"(i16 %x)
  ret void
}

; ERR: error: could not allocate input reg for constraint 'VA'
define void @use_A_f16(half %x) {
; CHECK-LABEL: use_A_f16:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    ;;#ASMSTART
; CHECK-NEXT:    ; use v0
; CHECK-NEXT:    ;;#ASMEND
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  call void asm sideeffect "; use $0", "^VA"(half %x)
  ret void
}

; ERR: error: could not allocate input reg for constraint 'VA'
define void @use_A_bf16(bfloat %x) {
; CHECK-LABEL: use_A_bf16:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    ;;#ASMSTART
; CHECK-NEXT:    ; use v0
; CHECK-NEXT:    ;;#ASMEND
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  call void asm sideeffect "; use $0", "^VA"(bfloat %x)
  ret void
}

; ERR: error: could not allocate input reg for constraint 'VA'
define void @use_A_v2i16(<2 x i16> %x) {
; CHECK-LABEL: use_A_v2i16:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    ;;#ASMSTART
; CHECK-NEXT:    ; use v0
; CHECK-NEXT:    ;;#ASMEND
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  call void asm sideeffect "; use $0", "^VA"(<2 x i16> %x)
  ret void
}

; ERR: error: could not allocate input reg for constraint 'VA'
define void @use_A_v2f16(<2 x half> %x) {
; CHECK-LABEL: use_A_v2f16:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    ;;#ASMSTART
; CHECK-NEXT:    ; use v0
; CHECK-NEXT:    ;;#ASMEND
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  call void asm sideeffect "; use $0", "^VA"(<2 x half> %x)
  ret void
}

; ERR: error: could not allocate input reg for constraint 'VA'
define void @use_A_v2bf16(<2 x bfloat> %x) {
; CHECK-LABEL: use_A_v2bf16:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    ;;#ASMSTART
; CHECK-NEXT:    ; use v0
; CHECK-NEXT:    ;;#ASMEND
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  call void asm sideeffect "; use $0", "^VA"(<2 x bfloat> %x)
  ret void
}

; ERR: error: could not allocate input reg for constraint 'VA'
define void @use_A_i32(i32 %x) {
; CHECK-LABEL: use_A_i32:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    ;;#ASMSTART
; CHECK-NEXT:    ; use v0
; CHECK-NEXT:    ;;#ASMEND
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  call void asm sideeffect "; use $0", "^VA"(i32 %x)
  ret void
}

; ERR: error: could not allocate input reg for constraint 'VA'
define void @use_A_f32(float %x) {
; CHECK-LABEL: use_A_f32:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    ;;#ASMSTART
; CHECK-NEXT:    ; use v0
; CHECK-NEXT:    ;;#ASMEND
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  call void asm sideeffect "; use $0", "^VA"(float %x)
  ret void
}

; ERR: error: could not allocate input reg for constraint 'VA'
define void @use_A_i64(i64 %x) {
; CHECK-LABEL: use_A_i64:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    ;;#ASMSTART
; CHECK-NEXT:    ; use v[0:1]
; CHECK-NEXT:    ;;#ASMEND
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  call void asm sideeffect "; use $0", "^VA"(i64 %x)
  ret void
}

; ERR: error: could not allocate input reg for constraint 'VA'
define void @use_A_f64(double %x) {
; CHECK-LABEL: use_A_f64:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    ;;#ASMSTART
; CHECK-NEXT:    ; use v[0:1]
; CHECK-NEXT:    ;;#ASMEND
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  call void asm sideeffect "; use $0", "^VA"(double %x)
  ret void
}

; ERR: error: could not allocate input reg for constraint 'VA'
define void @use_A_p1(ptr addrspace(1) %x) {
; CHECK-LABEL: use_A_p1:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    ;;#ASMSTART
; CHECK-NEXT:    ; use v[0:1]
; CHECK-NEXT:    ;;#ASMEND
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  call void asm sideeffect "; use $0", "^VA"(ptr addrspace(1) %x)
  ret void
}

; ERR: error: could not allocate input reg for constraint 'VA'
define void @use_A_v32i32(<32 x i32> %x) {
; CHECK-LABEL: use_A_v32i32:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    ;;#ASMSTART
; CHECK-NEXT:    ; use v[0:31]
; CHECK-NEXT:    ;;#ASMEND
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  call void asm sideeffect "; use $0", "^VA"(<32 x i32> %x)
  ret void
}

; ERR: error: could not allocate input reg for constraint 'VA'
define void @use_A_v32f32(<32 x float> %x) {
; CHECK-LABEL: use_A_v32f32:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    buffer_load_dword v31, off, s[0:3], s32
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    ;;#ASMSTART
; CHECK-NEXT:    ; use v[0:31]
; CHECK-NEXT:    ;;#ASMEND
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  call void asm sideeffect "; use $0", "^VA"(<32 x float> %x)
  ret void
}

; ERR: error: could not allocate output register for constraint 'VA'
define i16 @def_A_i16() {
; CHECK-LABEL: def_A_i16:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    ;;#ASMSTART
; CHECK-NEXT:    ; def v0
; CHECK-NEXT:    ;;#ASMEND
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  %ret = call i16 asm sideeffect "; def $0", "=^VA"()
  ret i16 %ret
}

; ERR: error: could not allocate output register for constraint 'VA'
define i32 @def_A_i32() {
; CHECK-LABEL: def_A_i32:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    ;;#ASMSTART
; CHECK-NEXT:    ; def v0
; CHECK-NEXT:    ;;#ASMEND
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  %ret = call i32 asm sideeffect "; def $0", "=^VA"()
  ret i32 %ret
}

; ERR: error: could not allocate output register for constraint 'VA'
define ptr addrspace(1) @def_A_p1() {
; CHECK-LABEL: def_A_p1:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    ;;#ASMSTART
; CHECK-NEXT:    ; def v[0:1]
; CHECK-NEXT:    ;;#ASMEND
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  %ret = call ptr addrspace(1) asm sideeffect "; def $0", "=^VA"()
  ret ptr addrspace(1) %ret
}
