# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx90a -O3 -start-before=greedy \
# RUN:     -stop-after=virtregrewriter %s -o - | FileCheck %s

# Check VirtRegRewriter does not crashed with "cannot represent required
# subregister defs". Regression caused by #197467.

--- |
  define void @issue197467() #0 {
  entry:
    br label %loop
  loop:
    br label %loop
  }

  attributes #0 = { "target-cpu"="gfx90a" }
...
---
name:            issue197467
tracksRegLiveness: true
registers:
  - { id: 1,  class: sreg_64,        preferred-register: '' }
  - { id: 13, class: vgpr_32,        preferred-register: '' }
  - { id: 14, class: vgpr_32,        preferred-register: '' }
  - { id: 15, class: vgpr_32,        preferred-register: '' }
  - { id: 16, class: sgpr_32,        preferred-register: '' }
  - { id: 17, class: vgpr_32,        preferred-register: '' }
  - { id: 18, class: vgpr_32,        preferred-register: '' }
  - { id: 19, class: sreg_64_xexec,  preferred-register: '' }
  - { id: 21, class: sreg_32,        preferred-register: '' }
  - { id: 23, class: sreg_32_xm0,    preferred-register: '' }
  - { id: 29, class: sreg_32,        preferred-register: '%1' }
  - { id: 30, class: sreg_32,        preferred-register: '' }
  - { id: 32, class: sreg_32,        preferred-register: '' }
  - { id: 33, class: av_32,          preferred-register: '' }
  - { id: 35, class: sreg_64,        preferred-register: '' }
  - { id: 37, class: sreg_64,        preferred-register: '' }
machineFunctionInfo:
  scratchRSrcReg:    '$sgpr0_sgpr1_sgpr2_sgpr3'
  frameOffsetReg:    '$sgpr33'
  stackPtrOffsetReg: '$sgpr32'
  returnsVoid:       true
body:             |
  ; CHECK-LABEL: name: issue197467
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $sgpr4_sgpr5 = S_MOV_B64_IMM_PSEUDO 1900
  ; CHECK-NEXT:   renamable $sgpr6 = S_MOV_B32 1092616192
  ; CHECK-NEXT:   renamable $vcc = S_AND_B64 $exec, -1, implicit-def dead $scc
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.loop:
  ; CHECK-NEXT:   successors: %bb.1(0x7c000000), %bb.2(0x04000000)
  ; CHECK-NEXT:   liveins: $vcc, $sgpr6, $sgpr4_sgpr5:0x000000000000000F
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   [[V_CVT_F32_U32_e32_:%[0-9]+]]:vgpr_32 = V_CVT_F32_U32_e32 $sgpr4, implicit $mode, implicit $exec
  ; CHECK-NEXT:   renamable $sgpr5 = S_MUL_I32 renamable $sgpr4, 246
  ; CHECK-NEXT:   [[V_MUL_F32_e32_:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F32_e32 1036831949, [[V_CVT_F32_U32_e32_]], implicit $mode, implicit $exec
  ; CHECK-NEXT:   [[V_TRUNC_F32_e32_:%[0-9]+]]:vgpr_32 = nofpexcept V_TRUNC_F32_e32 [[V_MUL_F32_e32_]], implicit $mode, implicit $exec
  ; CHECK-NEXT:   [[V_CVT_U32_F32_e32_:%[0-9]+]]:vgpr_32 = nofpexcept V_CVT_U32_F32_e32 [[V_TRUNC_F32_e32_]], implicit $mode, implicit $exec
  ; CHECK-NEXT:   [[V_MAD_F32_e64_:%[0-9]+]]:vgpr_32 = V_MAD_F32_e64 1, [[V_TRUNC_F32_e32_]], 0, $sgpr6, 0, [[V_CVT_F32_U32_e32_]], 0, 0, implicit $mode, implicit $exec
  ; CHECK-NEXT:   renamable $sgpr8_sgpr9 = nofpexcept V_CMP_LE_F32_e64 0, $sgpr6, 2, [[V_MAD_F32_e64_]], 0, implicit $mode, implicit $exec
  ; CHECK-NEXT:   S_CMP_LG_U64 killed renamable $sgpr8_sgpr9, 0, implicit-def $scc
  ; CHECK-NEXT:   renamable $sgpr7 = V_READFIRSTLANE_B32 [[V_CVT_U32_F32_e32_]], implicit $exec
  ; CHECK-NEXT:   renamable $sgpr7 = S_ADDC_U32 killed renamable $sgpr7, 0, implicit-def dead $scc, implicit $scc
  ; CHECK-NEXT:   renamable $sgpr5 = S_OR_B32 killed renamable $sgpr5, killed renamable $sgpr4, implicit-def dead $scc
  ; CHECK-NEXT:   renamable $sgpr4 = S_AND_B32 killed renamable $sgpr7, 2047, implicit-def dead $scc
  ; CHECK-NEXT:   renamable $sgpr5 = S_OR_B32 killed renamable $sgpr5, 1, implicit-def dead $scc
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:av_32 = COPY killed renamable $sgpr5
  ; CHECK-NEXT:   BUFFER_STORE_BYTE_OFFSET [[COPY]], $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (store (s8) into `ptr addrspace(5) null`, addrspace 5)
  ; CHECK-NEXT:   S_CBRANCH_VCCNZ %bb.1, implicit $vcc
  ; CHECK-NEXT:   S_BRANCH %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   SI_RETURN
  bb.0.entry:
    successors: %bb.1(0x80000000)

    %37:sreg_64 = S_MOV_B64_IMM_PSEUDO 1900
    %16:sgpr_32 = S_MOV_B32 1092616192
    %35:sreg_64 = S_AND_B64 $exec, -1, implicit-def dead $scc

  bb.1.loop:
    successors: %bb.1(0x7c000000), %bb.2(0x04000000)

    %1:sreg_64 = COPY %37
    %13:vgpr_32 = V_CVT_F32_U32_e32 %1.sub0, implicit $mode, implicit $exec
    %29:sreg_32 = S_MUL_I32 %1.sub0, 246
    %14:vgpr_32 = nofpexcept V_MUL_F32_e32 1036831949, %13, implicit $mode, implicit $exec
    %15:vgpr_32 = nofpexcept V_TRUNC_F32_e32 %14, implicit $mode, implicit $exec
    %18:vgpr_32 = nofpexcept V_CVT_U32_F32_e32 %15, implicit $mode, implicit $exec
    %17:vgpr_32 = V_MAD_F32_e64 1, %15, 0, %16, 0, %13, 0, 0, implicit $mode, implicit $exec
    %19:sreg_64_xexec = nofpexcept V_CMP_LE_F32_e64 0, %16, 2, %17, 0, implicit $mode, implicit $exec
    S_CMP_LG_U64 %19, 0, implicit-def $scc
    %23:sreg_32_xm0 = V_READFIRSTLANE_B32 %18, implicit $exec
    %21:sreg_32 = S_ADDC_U32 %23, 0, implicit-def dead $scc, implicit $scc
    %30:sreg_32 = S_OR_B32 %29, %1.sub0, implicit-def dead $scc
    undef %37.sub0:sreg_64 = S_AND_B32 %21, 2047, implicit-def dead $scc
    %32:sreg_32 = S_OR_B32 %30, 1, implicit-def dead $scc
    %33:av_32 = COPY %32
    BUFFER_STORE_BYTE_OFFSET %33, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (store (s8) into `ptr addrspace(5) null`, addrspace 5)
    $vcc = COPY %35
    S_CBRANCH_VCCNZ %bb.1, implicit $vcc
    S_BRANCH %bb.2

  bb.2:
    SI_RETURN
...
