; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=amdgcn-amd-amdhsa -mcpu=gfx900 -verify-machineinstrs -stop-after=finalize-isel | FileCheck %s -check-prefixes=GFX9

declare hidden void @external_void_func_a15i32_inreg([16 x i32] inreg)

define void @test_call_external_void_func_a15i32_inreg([16 x i32] inreg %arg0) {
  ; GFX9-LABEL: name: test_call_external_void_func_a15i32_inreg
  ; GFX9: bb.0 (%ir-block.0):
  ; GFX9-NEXT:   liveins: $sgpr4_sgpr5, $sgpr6_sgpr7, $sgpr8_sgpr9, $sgpr10_sgpr11, $sgpr12, $sgpr13, $sgpr14, $sgpr15, $sgpr16, $sgpr17, $sgpr18, $sgpr19, $sgpr20, $sgpr21, $sgpr22, $sgpr23, $sgpr24, $sgpr25, $sgpr26, $sgpr27, $sgpr28, $sgpr29, $vgpr0, $vgpr1, $vgpr31
  ; GFX9-NEXT: {{  $}}
  ; GFX9-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr31
  ; GFX9-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX9-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX9-NEXT:   [[COPY3:%[0-9]+]]:sgpr_32 = COPY $sgpr29
  ; GFX9-NEXT:   [[COPY4:%[0-9]+]]:sgpr_32 = COPY $sgpr28
  ; GFX9-NEXT:   [[COPY5:%[0-9]+]]:sgpr_32 = COPY $sgpr27
  ; GFX9-NEXT:   [[COPY6:%[0-9]+]]:sgpr_32 = COPY $sgpr26
  ; GFX9-NEXT:   [[COPY7:%[0-9]+]]:sgpr_32 = COPY $sgpr25
  ; GFX9-NEXT:   [[COPY8:%[0-9]+]]:sgpr_32 = COPY $sgpr24
  ; GFX9-NEXT:   [[COPY9:%[0-9]+]]:sgpr_32 = COPY $sgpr23
  ; GFX9-NEXT:   [[COPY10:%[0-9]+]]:sgpr_32 = COPY $sgpr22
  ; GFX9-NEXT:   [[COPY11:%[0-9]+]]:sgpr_32 = COPY $sgpr21
  ; GFX9-NEXT:   [[COPY12:%[0-9]+]]:sgpr_32 = COPY $sgpr20
  ; GFX9-NEXT:   [[COPY13:%[0-9]+]]:sgpr_32 = COPY $sgpr19
  ; GFX9-NEXT:   [[COPY14:%[0-9]+]]:sgpr_32 = COPY $sgpr18
  ; GFX9-NEXT:   [[COPY15:%[0-9]+]]:sgpr_32 = COPY $sgpr17
  ; GFX9-NEXT:   [[COPY16:%[0-9]+]]:sgpr_32 = COPY $sgpr16
  ; GFX9-NEXT:   [[COPY17:%[0-9]+]]:sgpr_32 = COPY $sgpr15
  ; GFX9-NEXT:   [[COPY18:%[0-9]+]]:sgpr_32 = COPY $sgpr14
  ; GFX9-NEXT:   [[COPY19:%[0-9]+]]:sgpr_32 = COPY $sgpr13
  ; GFX9-NEXT:   [[COPY20:%[0-9]+]]:sgpr_32 = COPY $sgpr12
  ; GFX9-NEXT:   [[COPY21:%[0-9]+]]:sgpr_64 = COPY $sgpr10_sgpr11
  ; GFX9-NEXT:   [[COPY22:%[0-9]+]]:sgpr_64 = COPY $sgpr8_sgpr9
  ; GFX9-NEXT:   [[COPY23:%[0-9]+]]:sgpr_64 = COPY $sgpr6_sgpr7
  ; GFX9-NEXT:   [[COPY24:%[0-9]+]]:sgpr_64 = COPY $sgpr4_sgpr5
  ; GFX9-NEXT:   ADJCALLSTACKUP 0, 0, implicit-def dead $scc, implicit-def $sgpr32, implicit $sgpr32
  ; GFX9-NEXT:   [[SI_PC_ADD_REL_OFFSET:%[0-9]+]]:sreg_64 = SI_PC_ADD_REL_OFFSET target-flags(amdgpu-rel32-lo) @external_void_func_a15i32_inreg, target-flags(amdgpu-rel32-hi) @external_void_func_a15i32_inreg, implicit-def dead $scc
  ; GFX9-NEXT:   [[COPY25:%[0-9]+]]:sgpr_128 = COPY $sgpr0_sgpr1_sgpr2_sgpr3
  ; GFX9-NEXT:   $sgpr4_sgpr5 = COPY [[COPY24]]
  ; GFX9-NEXT:   $sgpr6_sgpr7 = COPY [[COPY23]]
  ; GFX9-NEXT:   $sgpr8_sgpr9 = COPY [[COPY22]]
  ; GFX9-NEXT:   $sgpr10_sgpr11 = COPY [[COPY21]]
  ; GFX9-NEXT:   $sgpr12 = COPY [[COPY20]]
  ; GFX9-NEXT:   $sgpr13 = COPY [[COPY19]]
  ; GFX9-NEXT:   $sgpr14 = COPY [[COPY18]]
  ; GFX9-NEXT:   $sgpr15 = COPY [[COPY17]]
  ; GFX9-NEXT:   $vgpr31 = COPY [[COPY]]
  ; GFX9-NEXT:   $sgpr0_sgpr1_sgpr2_sgpr3 = COPY [[COPY25]]
  ; GFX9-NEXT:   $sgpr0 = COPY [[COPY16]]
  ; GFX9-NEXT:   $sgpr1 = COPY [[COPY15]]
  ; GFX9-NEXT:   $sgpr2 = COPY [[COPY14]]
  ; GFX9-NEXT:   $sgpr3 = COPY [[COPY13]]
  ; GFX9-NEXT:   $sgpr16 = COPY [[COPY12]]
  ; GFX9-NEXT:   $sgpr17 = COPY [[COPY11]]
  ; GFX9-NEXT:   $sgpr18 = COPY [[COPY10]]
  ; GFX9-NEXT:   $sgpr19 = COPY [[COPY9]]
  ; GFX9-NEXT:   $sgpr20 = COPY [[COPY8]]
  ; GFX9-NEXT:   $sgpr21 = COPY [[COPY7]]
  ; GFX9-NEXT:   $sgpr22 = COPY [[COPY6]]
  ; GFX9-NEXT:   $sgpr23 = COPY [[COPY5]]
  ; GFX9-NEXT:   $sgpr24 = COPY [[COPY4]]
  ; GFX9-NEXT:   $sgpr25 = COPY [[COPY3]]
  ; GFX9-NEXT:   $sgpr26 = V_READFIRSTLANE_B32 [[COPY2]], implicit $exec
  ; GFX9-NEXT:   $sgpr27 = V_READFIRSTLANE_B32 [[COPY1]], implicit $exec
  ; GFX9-NEXT:   $sgpr30_sgpr31 = SI_CALL killed [[SI_PC_ADD_REL_OFFSET]], @external_void_func_a15i32_inreg, csr_amdgpu, implicit $sgpr4_sgpr5, implicit $sgpr6_sgpr7, implicit $sgpr8_sgpr9, implicit $sgpr10_sgpr11, implicit $sgpr12, implicit $sgpr13, implicit $sgpr14, implicit $sgpr15, implicit $vgpr31, implicit $sgpr0_sgpr1_sgpr2_sgpr3, implicit $sgpr0, implicit $sgpr1, implicit $sgpr2, implicit $sgpr3, implicit $sgpr16, implicit $sgpr17, implicit $sgpr18, implicit $sgpr19, implicit $sgpr20, implicit $sgpr21, implicit $sgpr22, implicit $sgpr23, implicit $sgpr24, implicit $sgpr25, implicit $sgpr26, implicit $sgpr27
  ; GFX9-NEXT:   ADJCALLSTACKDOWN 0, 0, implicit-def dead $scc, implicit-def $sgpr32, implicit $sgpr32
  ; GFX9-NEXT:   SI_RETURN
  call void @external_void_func_a15i32_inreg([16 x i32] inreg %arg0)
  ret void
}
