; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 3
; RUN: llc -mtriple=amdgcn--amdpal -mcpu=gfx1200 -mattr=wavefrontsize32 < %s | FileCheck %s --check-prefixes=GFX12-W32
; RUN: llc -mtriple=amdgcn--amdpal -mcpu=gfx1200 -mattr=wavefrontsize64 < %s | FileCheck %s --check-prefixes=GFX12-W64
; RUN: llc -mtriple=amdgcn--amdpal -mcpu=gfx1250 -mattr=wavefrontsize32 < %s | FileCheck %s --check-prefixes=GFX1250
; RUN: llc -mtriple=amdgcn--amdpal -mcpu=gfx1300 -mattr=wavefrontsize32 < %s | FileCheck %s --check-prefixes=GFX13-W32
; RUN: llc -mtriple=amdgcn--amdpal -mcpu=gfx1300 -mattr=wavefrontsize64 < %s | FileCheck %s --check-prefixes=GFX13-W64

@sym = external addrspace(4) constant [2 x <3 x i32>]

define amdgpu_gs ptr addrspace(4) @v_add_symbol(i64 %arg) {
; GFX12-W32-LABEL: v_add_symbol:
; GFX12-W32:       ; %bb.0:
; GFX12-W32-NEXT:    v_lshlrev_b64_e32 v[0:1], 4, v[0:1]
; GFX12-W32-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX12-W32-NEXT:    v_add_co_u32 v0, vcc_lo, sym@abs32@lo, v0
; GFX12-W32-NEXT:    v_add_co_ci_u32_e64 v1, null, sym@abs32@hi, v1, vcc_lo
; GFX12-W32-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX12-W32-NEXT:    v_readfirstlane_b32 s0, v0
; GFX12-W32-NEXT:    v_readfirstlane_b32 s1, v1
; GFX12-W32-NEXT:    ; return to shader part epilog
;
; GFX12-W64-LABEL: v_add_symbol:
; GFX12-W64:       ; %bb.0:
; GFX12-W64-NEXT:    v_lshlrev_b64_e32 v[0:1], 4, v[0:1]
; GFX12-W64-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX12-W64-NEXT:    v_add_co_u32 v0, vcc, sym@abs32@lo, v0
; GFX12-W64-NEXT:    v_add_co_ci_u32_e64 v1, null, sym@abs32@hi, v1, vcc
; GFX12-W64-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX12-W64-NEXT:    v_readfirstlane_b32 s0, v0
; GFX12-W64-NEXT:    v_readfirstlane_b32 s1, v1
; GFX12-W64-NEXT:    ; return to shader part epilog
;
; GFX1250-LABEL: v_add_symbol:
; GFX1250:       ; %bb.0:
; GFX1250-NEXT:    v_lshl_add_u64 v[0:1], v[0:1], 4, sym@abs64
; GFX1250-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX1250-NEXT:    v_readfirstlane_b32 s0, v0
; GFX1250-NEXT:    v_readfirstlane_b32 s1, v1
; GFX1250-NEXT:    ; return to shader part epilog
;
; GFX13-W32-LABEL: v_add_symbol:
; GFX13-W32:       ; %bb.0:
; GFX13-W32-NEXT:    v_lshlrev_b64_e32 v[0:1], 4, v[0:1]
; GFX13-W32-NEXT:    s_mov_b64 s[0:1], sym@abs64
; GFX13-W32-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX13-W32-NEXT:    v_add_co_u32 v0, vcc_lo, v0, sym@abs64
; GFX13-W32-NEXT:    v_add_co_ci_u32_e64 v1, null, s1, v1, vcc_lo
; GFX13-W32-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX13-W32-NEXT:    v_readfirstlane_b32 s0, v0
; GFX13-W32-NEXT:    v_readfirstlane_b32 s1, v1
; GFX13-W32-NEXT:    ; return to shader part epilog
;
; GFX13-W64-LABEL: v_add_symbol:
; GFX13-W64:       ; %bb.0:
; GFX13-W64-NEXT:    v_lshlrev_b64_e32 v[0:1], 4, v[0:1]
; GFX13-W64-NEXT:    s_mov_b64 s[0:1], sym@abs64
; GFX13-W64-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX13-W64-NEXT:    v_add_co_u32 v0, vcc, v0, sym@abs64
; GFX13-W64-NEXT:    v_add_co_ci_u32_e64 v1, null, s1, v1, vcc
; GFX13-W64-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX13-W64-NEXT:    v_readfirstlane_b32 s0, v0
; GFX13-W64-NEXT:    v_readfirstlane_b32 s1, v1
; GFX13-W64-NEXT:    ; return to shader part epilog
  %i = getelementptr [2 x <3 x i32>], ptr addrspace(4) @sym, i64 0, i64 %arg
  ret ptr addrspace(4) %i
}
