; RUN: llc -enable-new-pm -disable-verify -mtriple=amdgcn--amdhsa -print-pipeline-passes < %s 2>&1 \
; RUN:   | FileCheck -check-prefix=GCN-O2 %s

; RUN: llc -O3 -enable-new-pm -disable-verify -mtriple=amdgcn--amdhsa -print-pipeline-passes < %s 2>&1 \
; RUN:   | FileCheck -check-prefix=GCN-O3 %s

; GCN-O2: require<MachineModuleAnalysis>
; GCN-O2: require<profile-summary>
; GCN-O2: require<collector-metadata>
; GCN-O2: pre-isel-intrinsic-lowering
; GCN-O2: function(expand-large-div-rem
; GCN-O2: expand-fp)
; GCN-O2: amdgpu-remove-incompatible-functions
; GCN-O2: amdgpu-printf-runtime-binding
; GCN-O2: amdgpu-lower-ctor-dtor
; GCN-O2: function(amdgpu-image-intrinsic-opt)
; GCN-O2: expand-variadics
; GCN-O2: amdgpu-always-inline
; GCN-O2: always-inline
; GCN-O2: amdgpu-export-kernel-runtime-handles
; GCN-O2: amdgpu-sw-lower-lds
; GCN-O2: amdgpu-lower-module-lds
; GCN-O2: function(infer-address-spaces
; GCN-O2: amdgpu-atomic-optimizer
; GCN-O2: atomic-expand
; GCN-O2: amdgpu-promote-alloca
; GCN-O2: separate-const-offset-from-gep<>
; GCN-O2: slsr
; GCN-O2: early-cse<>
; GCN-O2: nary-reassociate
; GCN-O2: early-cse<>
; GCN-O2: amdgpu-codegenprepare
; GCN-O2: loop-mssa(loop-reduce)
; GCN-O2: mergeicmps
; GCN-O2: expand-memcmp
; GCN-O2: gc-lowering
; GCN-O2: lower-constant-intrinsics
; GCN-O2: UnreachableBlockElimPass
; GCN-O2: consthoist
; GCN-O2: ReplaceWithVeclib
; GCN-O2: partially-inline-libcalls
; GCN-O2: ee-instrument<post-inline>
; GCN-O2: scalarize-masked-mem-intrin
; GCN-O2: ExpandReductionsPass
; GCN-O2: early-cse<>
; GCN-O2: amdgpu-lower-kernel-arguments)
; GCN-O2: amdgpu-lower-buffer-fat-pointers
; GCN-O2: cgscc(function(codegenprepare
; GCN-O2: load-store-vectorizer
; GCN-O2: lower-switch
; GCN-O2: lower-invoke
; GCN-O2: UnreachableBlockElimPass
; GCN-O2: flatten-cfg
; GCN-O2: sink
; GCN-O2: amdgpu-late-codegenprepare
; GCN-O2: amdgpu-unify-divergent-exit-nodes
; GCN-O2: fix-irreducible
; GCN-O2: unify-loop-exits
; GCN-O2: StructurizeCFGPass
; GCN-O2: amdgpu-annotate-uniform
; GCN-O2: si-annotate-control-flow
; GCN-O2: amdgpu-rewrite-undef-for-phi
; GCN-O2: lcssa))
; GCN-O2: amdgpu-perf-hint
; GCN-O2: cgscc(function(require<uniformity>
; GCN-O2: callbr-prepare
; GCN-O2: safe-stack
; GCN-O2: stack-protector))
; GCN-O2: cgscc(function(machine-function(amdgpu-isel
; GCN-O2: si-fix-sgpr-copies
; GCN-O2: si-i1-copies
; GCN-O2: finalize-isel
; GCN-O2: early-tailduplication
; GCN-O2: opt-phis
; GCN-O2: stack-coloring
; GCN-O2: localstackalloc
; GCN-O2: dead-mi-elimination
; GCN-O2: early-machinelicm
; GCN-O2: machine-cse
; GCN-O2: machine-sink
; GCN-O2: peephole-opt
; GCN-O2: dead-mi-elimination
; GCN-O2: si-fold-operands
; GCN-O2: gcn-dpp-combine
; GCN-O2: si-load-store-opt
; GCN-O2: si-peephole-sdwa
; GCN-O2: early-machinelicm
; GCN-O2: machine-cse
; GCN-O2: si-fold-operands
; GCN-O2: dead-mi-elimination
; GCN-O2: si-shrink-instructions
; GCN-O2: detect-dead-lanes
; GCN-O2: InitUndefPass
; GCN-O2: ProcessImplicitDefsPass
; GCN-O2: unreachable-mbb-elimination
; GCN-O2: require<live-vars>
; GCN-O2: require<machine-loops>
; GCN-O2: phi-node-elimination
; GCN-O2: two-address-instruction
; GCN-O2: register-coalescer
; GCN-O2: rename-independent-subregs
; GCN-O2: machine-scheduler
; GCN-O2: greedy<all>
; GCN-O2: amdgpu-nsa-reassign
; GCN-O2: VirtRegRewriterPass
; GCN-O2: stack-slot-coloring
; GCN-O2: machine-cp
; GCN-O2: machinelicm
; GCN-O2: si-fix-vgpr-copies
; GCN-O2: si-optimize-exec-masking
; GCN-O2: remove-redundant-debug-values
; GCN-O2: fixup-statepoint-caller-saved
; GCN-O2: PostRAMachineSinkingPass
; GCN-O2: ShrinkWrapPass
; GCN-O2: PrologEpilogInserterPass
; GCN-O2: branch-folder
; GCN-O2: tailduplication
; GCN-O2: machine-latecleanup
; GCN-O2: machine-cp
; GCN-O2: post-ra-pseudos
; GCN-O2: postmisched
; GCN-O2: block-placement
; GCN-O2: fentry-insert
; GCN-O2: xray-instrumentation
; GCN-O2: patchable-function
; GCN-O2: gcn-create-vopd
; GCN-O2: si-memory-legalizer
; GCN-O2: si-insert-waitcnts
; GCN-O2: si-late-branch-lowering
; GCN-O2: si-pre-emit-peephole
; GCN-O2: post-RA-hazard-rec
; GCN-O2: AMDGPUWaitSGPRHazardsPass
; GCN-O2: amdgpu-insert-delay-alu
; GCN-O2: branch-relaxation
; GCN-O2: remove-loads-into-fake-uses
; GCN-O2: live-debug-values
; GCN-O2: machine-sanmd
; GCN-O2: stack-frame-layout)
; GCN-O2: invalidate<machine-function-info>))

; GCN-O3: require<MachineModuleAnalysis>
; GCN-O3: require<profile-summary>
; GCN-O3: require<collector-metadata>
; GCN-O3: pre-isel-intrinsic-lowering
; GCN-O3: function(expand-large-div-rem
; GCN-O3: expand-fp)
; GCN-O3: amdgpu-remove-incompatible-functions
; GCN-O3: amdgpu-printf-runtime-binding
; GCN-O3: amdgpu-lower-ctor-dtor
; GCN-O3: function(amdgpu-image-intrinsic-opt)
; GCN-O3: expand-variadics
; GCN-O3: amdgpu-always-inline
; GCN-O3: always-inline
; GCN-O3: amdgpu-export-kernel-runtime-handles
; GCN-O3: amdgpu-sw-lower-lds
; GCN-O3: amdgpu-lower-module-lds
; GCN-O3: function(infer-address-spaces
; GCN-O3: amdgpu-atomic-optimizer
; GCN-O3: atomic-expand
; GCN-O3: amdgpu-promote-alloca
; GCN-O3: separate-const-offset-from-gep<>
; GCN-O3: slsr
; GCN-O3: gvn<>
; GCN-O3: nary-reassociate
; GCN-O3: early-cse<>
; GCN-O3: amdgpu-codegenprepare
; GCN-O3: loop-mssa(loop-reduce)
; GCN-O3: mergeicmps
; GCN-O3: expand-memcmp
; GCN-O3: gc-lowering
; GCN-O3: lower-constant-intrinsics
; GCN-O3: UnreachableBlockElimPass
; GCN-O3: consthoist
; GCN-O3: ReplaceWithVeclib
; GCN-O3: partially-inline-libcalls
; GCN-O3: ee-instrument<post-inline>
; GCN-O3: scalarize-masked-mem-intrin
; GCN-O3: ExpandReductionsPass
; GCN-O3: gvn<>
; GCN-O3: amdgpu-lower-kernel-arguments)
; GCN-O3: amdgpu-lower-buffer-fat-pointers
; GCN-O3: cgscc(function(codegenprepare
; GCN-O3: load-store-vectorizer
; GCN-O3: lower-switch
; GCN-O3: lower-invoke
; GCN-O3: UnreachableBlockElimPass
; GCN-O3: flatten-cfg
; GCN-O3: sink
; GCN-O3: amdgpu-late-codegenprepare
; GCN-O3: amdgpu-unify-divergent-exit-nodes
; GCN-O3: fix-irreducible
; GCN-O3: unify-loop-exits
; GCN-O3: StructurizeCFGPass
; GCN-O3: amdgpu-annotate-uniform
; GCN-O3: si-annotate-control-flow
; GCN-O3: amdgpu-rewrite-undef-for-phi
; GCN-O3: lcssa))
; GCN-O3: amdgpu-perf-hint
; GCN-O3: cgscc(function(require<uniformity>
; GCN-O3: callbr-prepare
; GCN-O3: safe-stack
; GCN-O3: stack-protector))
; GCN-O3: cgscc(function(machine-function(amdgpu-isel
; GCN-O3: si-fix-sgpr-copies
; GCN-O3: si-i1-copies
; GCN-O3: finalize-isel
; GCN-O3: early-tailduplication
; GCN-O3: opt-phis
; GCN-O3: stack-coloring
; GCN-O3: localstackalloc
; GCN-O3: dead-mi-elimination
; GCN-O3: early-machinelicm
; GCN-O3: machine-cse
; GCN-O3: machine-sink
; GCN-O3: peephole-opt
; GCN-O3: dead-mi-elimination
; GCN-O3: si-fold-operands
; GCN-O3: gcn-dpp-combine
; GCN-O3: si-load-store-opt
; GCN-O3: si-peephole-sdwa
; GCN-O3: early-machinelicm
; GCN-O3: machine-cse
; GCN-O3: si-fold-operands
; GCN-O3: dead-mi-elimination
; GCN-O3: si-shrink-instructions
; GCN-O3: detect-dead-lanes
; GCN-O3: InitUndefPass
; GCN-O3: ProcessImplicitDefsPass
; GCN-O3: unreachable-mbb-elimination
; GCN-O3: require<live-vars>
; GCN-O3: require<machine-loops>
; GCN-O3: phi-node-elimination
; GCN-O3: two-address-instruction
; GCN-O3: register-coalescer
; GCN-O3: rename-independent-subregs
; GCN-O3: machine-scheduler
; GCN-O3: greedy<all>
; GCN-O3: amdgpu-nsa-reassign
; GCN-O3: VirtRegRewriterPass
; GCN-O3: stack-slot-coloring
; GCN-O3: machine-cp
; GCN-O3: machinelicm
; GCN-O3: si-fix-vgpr-copies
; GCN-O3: si-optimize-exec-masking
; GCN-O3: remove-redundant-debug-values
; GCN-O3: fixup-statepoint-caller-saved
; GCN-O3: PostRAMachineSinkingPass
; GCN-O3: ShrinkWrapPass
; GCN-O3: PrologEpilogInserterPass
; GCN-O3: branch-folder
; GCN-O3: tailduplication
; GCN-O3: machine-latecleanup
; GCN-O3: machine-cp
; GCN-O3: post-ra-pseudos
; GCN-O3: postmisched
; GCN-O3: block-placement
; GCN-O3: fentry-insert
; GCN-O3: xray-instrumentation
; GCN-O3: patchable-function
; GCN-O3: gcn-create-vopd
; GCN-O3: si-memory-legalizer
; GCN-O3: si-insert-waitcnts
; GCN-O3: si-late-branch-lowering
; GCN-O3: si-pre-emit-peephole
; GCN-O3: post-RA-hazard-rec
; GCN-O3: AMDGPUWaitSGPRHazardsPass
; GCN-O3: amdgpu-insert-delay-alu
; GCN-O3: branch-relaxation
; GCN-O3: remove-loads-into-fake-uses
; GCN-O3: live-debug-values
; GCN-O3: machine-sanmd
; GCN-O3: stack-frame-layout)
; GCN-O3: invalidate<machine-function-info>))


define void @empty() {
  ret void
}
