; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
;RUN: llc < %s -mtriple=amdgcn -mcpu=gfx1300 -amdgpu-atomic-optimizer-strategy=None -verify-machineinstrs | FileCheck -check-prefixes=GFX13,GFX13-SDAG %s
;RUN: llc < %s -mtriple=amdgcn -mcpu=gfx1300 -amdgpu-atomic-optimizer-strategy=None -global-isel -verify-machineinstrs | FileCheck -check-prefixes=GFX13,GFX13-GISEL %s

define amdgpu_ps float @test1(i32 inreg %rsrc, i32 %data, i32 %voffset) {
; GFX13-LABEL: test1:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    buffer_atomic_swap_b32 v0, off, s0, null th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_movk_i32 s1, 0x1ffc
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    buffer_atomic_swap_b32 v0, v1, s0, null offen th:TH_ATOMIC_RETURN
; GFX13-NEXT:    v_add_nc_u32_e32 v1, 42, v1
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    buffer_atomic_swap_b32 v0, v1, s0, null offen th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    buffer_atomic_swap_b32 v0, off, s0, s1 offset:4 th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    s_clause 0x1
; GFX13-NEXT:    buffer_atomic_swap_b32 v0, off, s0, null
; GFX13-NEXT:    buffer_atomic_swap_b32 v0, off, s0, null th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %o1 = call i32 @llvm.amdgcn.raw.buffer.atomic.swap.i32(i32 %data, i32 %rsrc, i32 0, i32 0, i32 0)
  %o3 = call i32 @llvm.amdgcn.raw.buffer.atomic.swap.i32(i32 %o1, i32 %rsrc, i32 %voffset, i32 0, i32 0)
  %off5 = add i32 %voffset, 42
  %o5 = call i32 @llvm.amdgcn.raw.buffer.atomic.swap.i32(i32 %o3, i32 %rsrc, i32 %off5, i32 0, i32 0)
  %o6 = call i32 @llvm.amdgcn.raw.buffer.atomic.swap.i32(i32 %o5, i32 %rsrc, i32 4, i32 8188, i32 0)
  %unused = call i32 @llvm.amdgcn.raw.buffer.atomic.swap.i32(i32 %o6, i32 %rsrc, i32 0, i32 0, i32 0)
  %o7 = bitcast i32 %o6 to float
  %out = call float @llvm.amdgcn.raw.buffer.atomic.swap.f32(float %o7, i32 %rsrc, i32 0, i32 0, i32 0)
  ret float %out
}

define amdgpu_ps float @test2(i32 inreg %rsrc, i32 %data, i32 %voffset) {
; GFX13-LABEL: test2:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    buffer_atomic_add_u32 v0, v1, s0, null offen th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    buffer_atomic_sub_u32 v0, v1, s0, null offen th:TH_ATOMIC_NT_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    buffer_atomic_min_i32 v0, v1, s0, null offen th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    buffer_atomic_min_u32 v0, v1, s0, null offen th:TH_ATOMIC_NT_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    buffer_atomic_max_i32 v0, v1, s0, null offen th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    buffer_atomic_max_u32 v0, v1, s0, null offen th:TH_ATOMIC_NT_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    buffer_atomic_and_b32 v0, v1, s0, null offen th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    buffer_atomic_or_b32 v0, v1, s0, null offen th:TH_ATOMIC_NT_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    buffer_atomic_xor_b32 v0, v1, s0, null offen th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    buffer_atomic_inc_u32 v0, v1, s0, null offen th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    buffer_atomic_dec_u32 v0, v1, s0, null offen th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %t1 = call i32 @llvm.amdgcn.raw.buffer.atomic.add.i32(i32 %data, i32 %rsrc, i32 %voffset, i32 0, i32 0)
  %t2 = call i32 @llvm.amdgcn.raw.buffer.atomic.sub.i32(i32 %t1, i32 %rsrc, i32 %voffset, i32 0, i32 2)
  %t3 = call i32 @llvm.amdgcn.raw.buffer.atomic.smin.i32(i32 %t2, i32 %rsrc, i32 %voffset, i32 0, i32 0)
  %t4 = call i32 @llvm.amdgcn.raw.buffer.atomic.umin.i32(i32 %t3, i32 %rsrc, i32 %voffset, i32 0, i32 2)
  %t5 = call i32 @llvm.amdgcn.raw.buffer.atomic.smax.i32(i32 %t4, i32 %rsrc, i32 %voffset, i32 0, i32 0)
  %t6 = call i32 @llvm.amdgcn.raw.buffer.atomic.umax.i32(i32 %t5, i32 %rsrc, i32 %voffset, i32 0, i32 2)
  %t7 = call i32 @llvm.amdgcn.raw.buffer.atomic.and.i32(i32 %t6, i32 %rsrc, i32 %voffset, i32 0, i32 0)
  %t8 = call i32 @llvm.amdgcn.raw.buffer.atomic.or.i32(i32 %t7, i32 %rsrc, i32 %voffset, i32 0, i32 2)
  %t9 = call i32 @llvm.amdgcn.raw.buffer.atomic.xor.i32(i32 %t8, i32 %rsrc, i32 %voffset, i32 0, i32 0)
  %t10 = call i32 @llvm.amdgcn.raw.buffer.atomic.inc.i32(i32 %t9, i32 %rsrc, i32 %voffset, i32 0, i32 0)
  %t11 = call i32 @llvm.amdgcn.raw.buffer.atomic.dec.i32(i32 %t10, i32 %rsrc, i32 %voffset, i32 0, i32 0)
  %out = bitcast i32 %t11 to float
  ret float %out
}

define amdgpu_ps float @test3(i32 inreg %rsrc, i32 %data, i32 %cmp, i32 %vindex, i32 %voffset) {
; GFX13-LABEL: test3:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    v_dual_mov_b32 v4, v1 :: v_dual_mov_b32 v3, v0
; GFX13-NEXT:    s_movk_i32 s1, 0x1ffc
; GFX13-NEXT:    v_add_nc_u32_e32 v0, 44, v2
; GFX13-NEXT:    buffer_atomic_cmpswap_b32 v[3:4], off, s0, null th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    v_mov_b32_e32 v4, v1
; GFX13-NEXT:    buffer_atomic_cmpswap_b32 v[3:4], v2, s0, null offen th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    v_mov_b32_e32 v4, v1
; GFX13-NEXT:    buffer_atomic_cmpswap_b32 v[3:4], v0, s0, null offen th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    v_mov_b32_e32 v4, v1
; GFX13-NEXT:    buffer_atomic_cmpswap_b32 v[3:4], off, s0, s1 offset:4 th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    v_mov_b32_e32 v0, v3
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %o1 = call i32 @llvm.amdgcn.raw.buffer.atomic.cmpswap.i32(i32 %data, i32 %cmp, i32 %rsrc, i32 0, i32 0, i32 0)
  %o3 = call i32 @llvm.amdgcn.raw.buffer.atomic.cmpswap.i32(i32 %o1, i32 %cmp, i32 %rsrc, i32 %voffset, i32 0, i32 0)
  %ofs.5 = add i32 %voffset, 44
  %o5 = call i32 @llvm.amdgcn.raw.buffer.atomic.cmpswap.i32(i32 %o3, i32 %cmp, i32 %rsrc, i32 %ofs.5, i32 0, i32 0)
  %o6 = call i32 @llvm.amdgcn.raw.buffer.atomic.cmpswap.i32(i32 %o5, i32 %cmp, i32 %rsrc, i32 4, i32 8188, i32 0)

  %out = bitcast i32 %o6 to float
  ret float %out
}

define amdgpu_ps float @test5(i32 inreg %rsrc, i64 %data, i64 %cmp, i32 %vindex, i32 %voffset) {
; GFX13-LABEL: test5:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    v_dual_mov_b32 v8, v3 :: v_dual_mov_b32 v7, v2
; GFX13-NEXT:    v_dual_mov_b32 v6, v1 :: v_dual_mov_b32 v5, v0
; GFX13-NEXT:    v_add_nc_u32_e32 v0, 44, v4
; GFX13-NEXT:    s_movk_i32 s1, 0x1ffc
; GFX13-NEXT:    buffer_atomic_cmpswap_b64 v[5:8], off, s0, null th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    v_dual_mov_b32 v8, v3 :: v_dual_mov_b32 v7, v2
; GFX13-NEXT:    buffer_atomic_cmpswap_b64 v[5:8], v4, s0, null offen th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    v_dual_mov_b32 v8, v3 :: v_dual_mov_b32 v7, v2
; GFX13-NEXT:    buffer_atomic_cmpswap_b64 v[5:8], v0, s0, null offen th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    v_dual_mov_b32 v8, v3 :: v_dual_mov_b32 v7, v2
; GFX13-NEXT:    buffer_atomic_cmpswap_b64 v[5:8], off, s0, s1 offset:4 th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    v_xor_b32_e32 v0, v5, v6
; GFX13-NEXT:    v_cls_i32_e32 v1, v6
; GFX13-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX13-NEXT:    v_dual_ashrrev_i32 v0, 31, v0 :: v_dual_add_nc_u32 v1, -1, v1
; GFX13-NEXT:    v_add_nc_u32_e32 v0, 32, v0
; GFX13-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX13-NEXT:    v_min_u32_e32 v2, v1, v0
; GFX13-NEXT:    v_lshlrev_b64_e32 v[0:1], v2, v[5:6]
; GFX13-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX13-NEXT:    v_min_u32_e32 v0, 1, v0
; GFX13-NEXT:    v_dual_sub_nc_u32 v1, 32, v2 :: v_dual_bitop2_b32 v0, v1, v0 bitop3:0x54
; GFX13-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX13-NEXT:    v_cvt_f32_i32_e32 v0, v0
; GFX13-NEXT:    v_ldexp_f32 v0, v0, v1
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %o1 = call i64 @llvm.amdgcn.raw.buffer.atomic.cmpswap.i64(i64 %data, i64 %cmp, i32 %rsrc, i32 0, i32 0, i32 0)
  %o3 = call i64 @llvm.amdgcn.raw.buffer.atomic.cmpswap.i64(i64 %o1, i64 %cmp, i32 %rsrc, i32 %voffset, i32 0, i32 0)
  %ofs.5 = add i32 %voffset, 44
  %o5 = call i64 @llvm.amdgcn.raw.buffer.atomic.cmpswap.i64(i64 %o3, i64 %cmp, i32 %rsrc, i32 %ofs.5, i32 0, i32 0)
  %o6 = call i64 @llvm.amdgcn.raw.buffer.atomic.cmpswap.i64(i64 %o5, i64 %cmp, i32 %rsrc, i32 4, i32 8188, i32 0)
  %out = sitofp i64 %o6 to float
  ret float %out
}

define amdgpu_ps float @test_volatile(i32 inreg %rsrc, i32 %data, i32 %voffset) {
; GFX13-LABEL: test_volatile:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    buffer_atomic_add_u32 v0, v1, s0, null offen th:TH_ATOMIC_RETURN
; GFX13-NEXT:    s_wait_loadcnt 0x0
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %t1 = call i32 @llvm.amdgcn.raw.buffer.atomic.add.i32(i32 %data, i32 %rsrc, i32 %voffset, i32 0, i32 -2147483648)
  %out = bitcast i32 %t1 to float
  ret float %out
}

define amdgpu_ps void @test_volatile_noret(i32 inreg %rsrc, i32 %data, i32 %voffset) {
; GFX13-LABEL: test_volatile_noret:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    buffer_atomic_add_u32 v0, v1, s0, null offen
; GFX13-NEXT:    s_endpgm
main_body:
  %t1 = call i32 @llvm.amdgcn.raw.buffer.atomic.add.i32(i32 %data, i32 %rsrc, i32 %voffset, i32 0, i32 -2147483648)
  ret void
}

declare i32 @llvm.amdgcn.raw.buffer.atomic.swap.i32(i32, i32, i32, i32, i32) #0
declare float @llvm.amdgcn.raw.buffer.atomic.swap.f32(float, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.raw.buffer.atomic.add.i32(i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.raw.buffer.atomic.sub.i32(i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.raw.buffer.atomic.smin.i32(i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.raw.buffer.atomic.umin.i32(i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.raw.buffer.atomic.smax.i32(i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.raw.buffer.atomic.umax.i32(i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.raw.buffer.atomic.and.i32(i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.raw.buffer.atomic.or.i32(i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.raw.buffer.atomic.xor.i32(i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.raw.buffer.atomic.inc.i32(i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.raw.buffer.atomic.dec.i32(i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.raw.buffer.atomic.cmpswap.i32(i32, i32, i32, i32, i32, i32) #0
declare i64 @llvm.amdgcn.raw.buffer.atomic.cmpswap.i64(i64, i64, i32, i32, i32, i32) #0

attributes #0 = { nounwind }
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; GFX13-GISEL: {{.*}}
; GFX13-SDAG: {{.*}}
