; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel=0 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1250 -show-mc-encoding < %s | FileCheck -check-prefix=GFX1250 %s
; RUN: llc -global-isel=1 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1250 -show-mc-encoding < %s | FileCheck -check-prefix=GFX1250 %s

declare void @llvm.amdgcn.s.setprio.inc.wg(i16) #0

define void @test_llvm.amdgcn.s.setprio.inc.wg() #0 {
; GFX1250-LABEL: test_llvm.amdgcn.s.setprio.inc.wg:
; GFX1250:       ; %bb.0:
; GFX1250-NEXT:    s_wait_loadcnt_dscnt 0x0 ; encoding: [0x00,0x00,0xc8,0xbf]
; GFX1250-NEXT:    s_wait_kmcnt 0x0 ; encoding: [0x00,0x00,0xc7,0xbf]
; GFX1250-NEXT:    s_setprio_inc_wg 0 ; encoding: [0x00,0x00,0xbe,0xbf]
; GFX1250-NEXT:    s_setprio_inc_wg 1 ; encoding: [0x01,0x00,0xbe,0xbf]
; GFX1250-NEXT:    s_setprio_inc_wg 2 ; encoding: [0x02,0x00,0xbe,0xbf]
; GFX1250-NEXT:    s_setprio_inc_wg 3 ; encoding: [0x03,0x00,0xbe,0xbf]
; GFX1250-NEXT:    s_setprio_inc_wg 10 ; encoding: [0x0a,0x00,0xbe,0xbf]
; GFX1250-NEXT:    s_setprio_inc_wg -1 ; encoding: [0xff,0xff,0xbe,0xbf]
; GFX1250-NEXT:    s_setprio_inc_wg 0 ; encoding: [0x00,0x00,0xbe,0xbf]
; GFX1250-NEXT:    s_setprio_inc_wg 1 ; encoding: [0x01,0x00,0xbe,0xbf]
; GFX1250-NEXT:    s_setprio_inc_wg -1 ; encoding: [0xff,0xff,0xbe,0xbf]
; GFX1250-NEXT:    s_set_pc_i64 s[30:31] ; encoding: [0x1e,0x48,0x80,0xbe]
  call void @llvm.amdgcn.s.setprio.inc.wg(i16 0)
  call void @llvm.amdgcn.s.setprio.inc.wg(i16 1)
  call void @llvm.amdgcn.s.setprio.inc.wg(i16 2)
  call void @llvm.amdgcn.s.setprio.inc.wg(i16 3)
  call void @llvm.amdgcn.s.setprio.inc.wg(i16 10)
  call void @llvm.amdgcn.s.setprio.inc.wg(i16 65535)
  call void @llvm.amdgcn.s.setprio.inc.wg(i16 65536)
  call void @llvm.amdgcn.s.setprio.inc.wg(i16 65537)
  call void @llvm.amdgcn.s.setprio.inc.wg(i16 -1)
  ret void
}

attributes #0 = { nounwind }
