; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel=0 -march=amdgcn -mcpu=gfx1210 -verify-machineinstrs < %s | FileCheck %s -check-prefix=GCN
; RUN: llc -global-isel=1 -march=amdgcn -mcpu=gfx1210 -verify-machineinstrs < %s | FileCheck %s -check-prefix=GCN
; RUN: llc -global-isel=0 -march=amdgcn -mcpu=gfx1300 -verify-machineinstrs < %s | FileCheck %s -check-prefix=GCN
; RUN: llc -global-isel=1 -march=amdgcn -mcpu=gfx1300 -verify-machineinstrs < %s | FileCheck %s -check-prefix=GCN

define amdgpu_ps void @test_asynccnt() {
; GCN-LABEL: test_asynccnt:
; GCN:       ; %bb.0:
; GCN-NEXT:    global_wb scope:SCOPE_SYS
; GCN-NEXT:    s_wait_asynccnt 0x0
; GCN-NEXT:    global_inv scope:SCOPE_SYS
; GCN-NEXT:    s_endpgm
  call void @llvm.amdgcn.s.wait.asynccnt(i16 0)
  ret void
}

define amdgpu_ps void @test_tensorcnt() {
; GCN-LABEL: test_tensorcnt:
; GCN:       ; %bb.0:
; GCN-NEXT:    global_wb scope:SCOPE_SYS
; GCN-NEXT:    s_wait_tensorcnt 0x0
; GCN-NEXT:    global_inv scope:SCOPE_SYS
; GCN-NEXT:    s_endpgm
  call void @llvm.amdgcn.s.wait.tensorcnt(i16 0)
  ret void
}

declare void @llvm.amdgcn.s.wait.asynccnt(i16)
declare void @llvm.amdgcn.s.wait.tensorcnt(i16)
