; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -global-isel=0 -mtriple=amdgcn -mcpu=gfx1300 -verify-machineinstrs < %s | FileCheck -check-prefixes=GFX13,GFX13-SDAG %s
; RUN: llc -global-isel=1 -mtriple=amdgcn -mcpu=gfx1300 -verify-machineinstrs < %s | FileCheck -check-prefixes=GFX13,GFX13-GISEL %s

declare <6 x i32> @llvm.amdgcn.cvt.scalef32.pk32.bf6.f32(<32 x float> %src, float %scale)
declare <6 x i32> @llvm.amdgcn.cvt.scalef32.pk32.fp6.f32(<32 x float> %src, float %scale)

define amdgpu_kernel void @test_cvt_scalef32_pk32_bf6_f32_v(ptr addrspace(1) %out, <32 x float> %src, float %scale) {
; GFX13-SDAG-LABEL: test_cvt_scalef32_pk32_bf6_f32_v:
; GFX13-SDAG:       ; %bb.0:
; GFX13-SDAG-NEXT:    s_clause 0x3
; GFX13-SDAG-NEXT:    s_load_b512 s[36:51], s[4:5], 0xa4
; GFX13-SDAG-NEXT:    s_load_b512 s[8:23], s[4:5], 0xe4
; GFX13-SDAG-NEXT:    s_load_b64 s[0:1], s[4:5], 0x24
; GFX13-SDAG-NEXT:    s_load_b32 s2, s[4:5], 0x124
; GFX13-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v32, 0 :: v_dual_mov_b32 v0, s36
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v1, s37 :: v_dual_mov_b32 v2, s38
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v3, s39 :: v_dual_mov_b32 v4, s40
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v5, s41 :: v_dual_mov_b32 v6, s42
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v7, s43 :: v_dual_mov_b32 v8, s44
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v9, s45 :: v_dual_mov_b32 v10, s46
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v11, s47 :: v_dual_mov_b32 v12, s48
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v13, s49 :: v_dual_mov_b32 v14, s50
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v15, s51 :: v_dual_mov_b32 v16, s8
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v17, s9 :: v_dual_mov_b32 v18, s10
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v19, s11 :: v_dual_mov_b32 v20, s12
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v21, s13 :: v_dual_mov_b32 v22, s14
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v23, s15 :: v_dual_mov_b32 v24, s16
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v25, s17 :: v_dual_mov_b32 v26, s18
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v27, s19 :: v_dual_mov_b32 v28, s20
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v29, s21 :: v_dual_mov_b32 v30, s22
; GFX13-SDAG-NEXT:    v_mov_b32_e32 v31, s23
; GFX13-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX13-SDAG-NEXT:    v_cvt_scalef32_pk32_bf6_f32 v[0:5], v[0:31], s2
; GFX13-SDAG-NEXT:    s_clause 0x1
; GFX13-SDAG-NEXT:    global_store_b64 v32, v[4:5], s[0:1] offset:16 scope:SCOPE_SE
; GFX13-SDAG-NEXT:    global_store_b128 v32, v[0:3], s[0:1] scope:SCOPE_SE
; GFX13-SDAG-NEXT:    s_endpgm
;
; GFX13-GISEL-LABEL: test_cvt_scalef32_pk32_bf6_f32_v:
; GFX13-GISEL:       ; %bb.0:
; GFX13-GISEL-NEXT:    s_clause 0x3
; GFX13-GISEL-NEXT:    s_load_b512 s[36:51], s[4:5], 0xa4
; GFX13-GISEL-NEXT:    s_load_b512 s[52:67], s[4:5], 0xe4
; GFX13-GISEL-NEXT:    s_load_b32 s2, s[4:5], 0x124
; GFX13-GISEL-NEXT:    s_load_b64 s[0:1], s[4:5], 0x24
; GFX13-GISEL-NEXT:    s_wait_kmcnt 0x0
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v32, 0 :: v_dual_mov_b32 v0, s36
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v1, s37 :: v_dual_mov_b32 v2, s38
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v3, s39 :: v_dual_mov_b32 v4, s40
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v5, s41 :: v_dual_mov_b32 v6, s42
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v7, s43 :: v_dual_mov_b32 v8, s44
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v9, s45 :: v_dual_mov_b32 v10, s46
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v11, s47 :: v_dual_mov_b32 v12, s48
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v13, s49 :: v_dual_mov_b32 v14, s50
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v15, s51 :: v_dual_mov_b32 v16, s52
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v17, s53 :: v_dual_mov_b32 v18, s54
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v19, s55 :: v_dual_mov_b32 v20, s56
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v21, s57 :: v_dual_mov_b32 v22, s58
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v23, s59 :: v_dual_mov_b32 v24, s60
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v25, s61 :: v_dual_mov_b32 v26, s62
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v27, s63 :: v_dual_mov_b32 v28, s64
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v29, s65 :: v_dual_mov_b32 v30, s66
; GFX13-GISEL-NEXT:    v_mov_b32_e32 v31, s67
; GFX13-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX13-GISEL-NEXT:    v_cvt_scalef32_pk32_bf6_f32 v[0:5], v[0:31], s2
; GFX13-GISEL-NEXT:    s_clause 0x1
; GFX13-GISEL-NEXT:    global_store_b128 v32, v[0:3], s[0:1] scope:SCOPE_SE
; GFX13-GISEL-NEXT:    global_store_b64 v32, v[4:5], s[0:1] offset:16 scope:SCOPE_SE
; GFX13-GISEL-NEXT:    s_endpgm
  %cvt = tail call <6 x i32> @llvm.amdgcn.cvt.scalef32.pk32.bf6.f32(<32 x float> %src, float %scale)
  store <6 x i32> %cvt, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_kernel void @test_cvt_scalef32_pk32_bf6_f32_s(ptr addrspace(1) %out, <32 x float> %src) {
; GFX13-SDAG-LABEL: test_cvt_scalef32_pk32_bf6_f32_s:
; GFX13-SDAG:       ; %bb.0:
; GFX13-SDAG-NEXT:    s_clause 0x2
; GFX13-SDAG-NEXT:    s_load_b512 s[36:51], s[4:5], 0xa4
; GFX13-SDAG-NEXT:    s_load_b512 s[8:23], s[4:5], 0xe4
; GFX13-SDAG-NEXT:    s_load_b64 s[0:1], s[4:5], 0x24
; GFX13-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v32, 0 :: v_dual_mov_b32 v0, s36
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v1, s37 :: v_dual_mov_b32 v2, s38
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v3, s39 :: v_dual_mov_b32 v4, s40
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v5, s41 :: v_dual_mov_b32 v6, s42
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v7, s43 :: v_dual_mov_b32 v8, s44
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v9, s45 :: v_dual_mov_b32 v10, s46
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v11, s47 :: v_dual_mov_b32 v12, s48
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v13, s49 :: v_dual_mov_b32 v14, s50
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v15, s51 :: v_dual_mov_b32 v16, s8
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v17, s9 :: v_dual_mov_b32 v18, s10
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v19, s11 :: v_dual_mov_b32 v20, s12
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v21, s13 :: v_dual_mov_b32 v22, s14
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v23, s15 :: v_dual_mov_b32 v24, s16
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v25, s17 :: v_dual_mov_b32 v26, s18
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v27, s19 :: v_dual_mov_b32 v28, s20
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v29, s21 :: v_dual_mov_b32 v30, s22
; GFX13-SDAG-NEXT:    v_mov_b32_e32 v31, s23
; GFX13-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX13-SDAG-NEXT:    v_cvt_scalef32_pk32_bf6_f32 v[0:5], v[0:31], 0x42c80000
; GFX13-SDAG-NEXT:    s_clause 0x1
; GFX13-SDAG-NEXT:    global_store_b64 v32, v[4:5], s[0:1] offset:16 scope:SCOPE_SE
; GFX13-SDAG-NEXT:    global_store_b128 v32, v[0:3], s[0:1] scope:SCOPE_SE
; GFX13-SDAG-NEXT:    s_endpgm
;
; GFX13-GISEL-LABEL: test_cvt_scalef32_pk32_bf6_f32_s:
; GFX13-GISEL:       ; %bb.0:
; GFX13-GISEL-NEXT:    s_clause 0x2
; GFX13-GISEL-NEXT:    s_load_b512 s[36:51], s[4:5], 0xa4
; GFX13-GISEL-NEXT:    s_load_b512 s[52:67], s[4:5], 0xe4
; GFX13-GISEL-NEXT:    s_load_b64 s[0:1], s[4:5], 0x24
; GFX13-GISEL-NEXT:    s_wait_kmcnt 0x0
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v32, 0 :: v_dual_mov_b32 v0, s36
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v1, s37 :: v_dual_mov_b32 v2, s38
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v3, s39 :: v_dual_mov_b32 v4, s40
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v5, s41 :: v_dual_mov_b32 v6, s42
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v7, s43 :: v_dual_mov_b32 v8, s44
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v9, s45 :: v_dual_mov_b32 v10, s46
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v11, s47 :: v_dual_mov_b32 v12, s48
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v13, s49 :: v_dual_mov_b32 v14, s50
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v15, s51 :: v_dual_mov_b32 v16, s52
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v17, s53 :: v_dual_mov_b32 v18, s54
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v19, s55 :: v_dual_mov_b32 v20, s56
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v21, s57 :: v_dual_mov_b32 v22, s58
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v23, s59 :: v_dual_mov_b32 v24, s60
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v25, s61 :: v_dual_mov_b32 v26, s62
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v27, s63 :: v_dual_mov_b32 v28, s64
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v29, s65 :: v_dual_mov_b32 v30, s66
; GFX13-GISEL-NEXT:    v_mov_b32_e32 v31, s67
; GFX13-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX13-GISEL-NEXT:    v_cvt_scalef32_pk32_bf6_f32 v[0:5], v[0:31], 0x42c80000
; GFX13-GISEL-NEXT:    s_clause 0x1
; GFX13-GISEL-NEXT:    global_store_b128 v32, v[0:3], s[0:1] scope:SCOPE_SE
; GFX13-GISEL-NEXT:    global_store_b64 v32, v[4:5], s[0:1] offset:16 scope:SCOPE_SE
; GFX13-GISEL-NEXT:    s_endpgm
  %cvt = tail call <6 x i32> @llvm.amdgcn.cvt.scalef32.pk32.bf6.f32(<32 x float> %src, float 100.0)
  store <6 x i32> %cvt, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_kernel void @test_cvt_scalef32_pk32_bf6_f32_v_inreg_src(ptr addrspace(1) %out, <32 x float> inreg %src, float %scale) {
; GFX13-SDAG-LABEL: test_cvt_scalef32_pk32_bf6_f32_v_inreg_src:
; GFX13-SDAG:       ; %bb.0:
; GFX13-SDAG-NEXT:    s_clause 0x3
; GFX13-SDAG-NEXT:    s_load_b512 s[36:51], s[4:5], 0xa4
; GFX13-SDAG-NEXT:    s_load_b512 s[8:23], s[4:5], 0xe4
; GFX13-SDAG-NEXT:    s_load_b32 s2, s[4:5], 0x124
; GFX13-SDAG-NEXT:    s_load_b64 s[0:1], s[4:5], 0x24
; GFX13-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v32, 0 :: v_dual_mov_b32 v0, s36
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v1, s37 :: v_dual_mov_b32 v2, s38
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v3, s39 :: v_dual_mov_b32 v4, s40
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v5, s41 :: v_dual_mov_b32 v6, s42
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v7, s43 :: v_dual_mov_b32 v8, s44
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v9, s45 :: v_dual_mov_b32 v10, s46
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v11, s47 :: v_dual_mov_b32 v12, s48
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v13, s49 :: v_dual_mov_b32 v14, s50
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v15, s51 :: v_dual_mov_b32 v16, s8
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v17, s9 :: v_dual_mov_b32 v18, s10
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v19, s11 :: v_dual_mov_b32 v20, s12
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v21, s13 :: v_dual_mov_b32 v22, s14
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v23, s15 :: v_dual_mov_b32 v24, s16
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v25, s17 :: v_dual_mov_b32 v26, s18
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v27, s19 :: v_dual_mov_b32 v28, s20
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v29, s21 :: v_dual_mov_b32 v30, s22
; GFX13-SDAG-NEXT:    v_mov_b32_e32 v31, s23
; GFX13-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX13-SDAG-NEXT:    v_cvt_scalef32_pk32_bf6_f32 v[0:5], v[0:31], s2
; GFX13-SDAG-NEXT:    s_clause 0x1
; GFX13-SDAG-NEXT:    global_store_b64 v32, v[4:5], s[0:1] offset:16 scope:SCOPE_SE
; GFX13-SDAG-NEXT:    global_store_b128 v32, v[0:3], s[0:1] scope:SCOPE_SE
; GFX13-SDAG-NEXT:    s_endpgm
;
; GFX13-GISEL-LABEL: test_cvt_scalef32_pk32_bf6_f32_v_inreg_src:
; GFX13-GISEL:       ; %bb.0:
; GFX13-GISEL-NEXT:    s_clause 0x3
; GFX13-GISEL-NEXT:    s_load_b512 s[36:51], s[4:5], 0xa4
; GFX13-GISEL-NEXT:    s_load_b512 s[52:67], s[4:5], 0xe4
; GFX13-GISEL-NEXT:    s_load_b32 s2, s[4:5], 0x124
; GFX13-GISEL-NEXT:    s_load_b64 s[0:1], s[4:5], 0x24
; GFX13-GISEL-NEXT:    s_wait_kmcnt 0x0
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v32, 0 :: v_dual_mov_b32 v0, s36
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v1, s37 :: v_dual_mov_b32 v2, s38
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v3, s39 :: v_dual_mov_b32 v4, s40
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v5, s41 :: v_dual_mov_b32 v6, s42
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v7, s43 :: v_dual_mov_b32 v8, s44
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v9, s45 :: v_dual_mov_b32 v10, s46
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v11, s47 :: v_dual_mov_b32 v12, s48
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v13, s49 :: v_dual_mov_b32 v14, s50
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v15, s51 :: v_dual_mov_b32 v16, s52
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v17, s53 :: v_dual_mov_b32 v18, s54
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v19, s55 :: v_dual_mov_b32 v20, s56
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v21, s57 :: v_dual_mov_b32 v22, s58
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v23, s59 :: v_dual_mov_b32 v24, s60
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v25, s61 :: v_dual_mov_b32 v26, s62
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v27, s63 :: v_dual_mov_b32 v28, s64
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v29, s65 :: v_dual_mov_b32 v30, s66
; GFX13-GISEL-NEXT:    v_mov_b32_e32 v31, s67
; GFX13-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX13-GISEL-NEXT:    v_cvt_scalef32_pk32_bf6_f32 v[0:5], v[0:31], s2
; GFX13-GISEL-NEXT:    s_clause 0x1
; GFX13-GISEL-NEXT:    global_store_b128 v32, v[0:3], s[0:1] scope:SCOPE_SE
; GFX13-GISEL-NEXT:    global_store_b64 v32, v[4:5], s[0:1] offset:16 scope:SCOPE_SE
; GFX13-GISEL-NEXT:    s_endpgm
  %cvt = tail call <6 x i32> @llvm.amdgcn.cvt.scalef32.pk32.bf6.f32(<32 x float> %src, float %scale)
  store <6 x i32> %cvt, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_kernel void @test_cvt_scalef32_pk32_bf6_f32_s_inreg_src(ptr addrspace(1) %out, <32 x float> inreg %src) {
; GFX13-SDAG-LABEL: test_cvt_scalef32_pk32_bf6_f32_s_inreg_src:
; GFX13-SDAG:       ; %bb.0:
; GFX13-SDAG-NEXT:    s_clause 0x2
; GFX13-SDAG-NEXT:    s_load_b512 s[36:51], s[4:5], 0xa4
; GFX13-SDAG-NEXT:    s_load_b512 s[8:23], s[4:5], 0xe4
; GFX13-SDAG-NEXT:    s_load_b64 s[0:1], s[4:5], 0x24
; GFX13-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v32, 0 :: v_dual_mov_b32 v0, s36
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v1, s37 :: v_dual_mov_b32 v2, s38
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v3, s39 :: v_dual_mov_b32 v4, s40
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v5, s41 :: v_dual_mov_b32 v6, s42
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v7, s43 :: v_dual_mov_b32 v8, s44
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v9, s45 :: v_dual_mov_b32 v10, s46
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v11, s47 :: v_dual_mov_b32 v12, s48
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v13, s49 :: v_dual_mov_b32 v14, s50
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v15, s51 :: v_dual_mov_b32 v16, s8
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v17, s9 :: v_dual_mov_b32 v18, s10
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v19, s11 :: v_dual_mov_b32 v20, s12
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v21, s13 :: v_dual_mov_b32 v22, s14
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v23, s15 :: v_dual_mov_b32 v24, s16
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v25, s17 :: v_dual_mov_b32 v26, s18
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v27, s19 :: v_dual_mov_b32 v28, s20
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v29, s21 :: v_dual_mov_b32 v30, s22
; GFX13-SDAG-NEXT:    v_mov_b32_e32 v31, s23
; GFX13-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX13-SDAG-NEXT:    v_cvt_scalef32_pk32_bf6_f32 v[0:5], v[0:31], 0x42c80000
; GFX13-SDAG-NEXT:    s_clause 0x1
; GFX13-SDAG-NEXT:    global_store_b64 v32, v[4:5], s[0:1] offset:16 scope:SCOPE_SE
; GFX13-SDAG-NEXT:    global_store_b128 v32, v[0:3], s[0:1] scope:SCOPE_SE
; GFX13-SDAG-NEXT:    s_endpgm
;
; GFX13-GISEL-LABEL: test_cvt_scalef32_pk32_bf6_f32_s_inreg_src:
; GFX13-GISEL:       ; %bb.0:
; GFX13-GISEL-NEXT:    s_clause 0x2
; GFX13-GISEL-NEXT:    s_load_b512 s[36:51], s[4:5], 0xa4
; GFX13-GISEL-NEXT:    s_load_b512 s[52:67], s[4:5], 0xe4
; GFX13-GISEL-NEXT:    s_load_b64 s[0:1], s[4:5], 0x24
; GFX13-GISEL-NEXT:    s_wait_kmcnt 0x0
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v32, 0 :: v_dual_mov_b32 v0, s36
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v1, s37 :: v_dual_mov_b32 v2, s38
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v3, s39 :: v_dual_mov_b32 v4, s40
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v5, s41 :: v_dual_mov_b32 v6, s42
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v7, s43 :: v_dual_mov_b32 v8, s44
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v9, s45 :: v_dual_mov_b32 v10, s46
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v11, s47 :: v_dual_mov_b32 v12, s48
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v13, s49 :: v_dual_mov_b32 v14, s50
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v15, s51 :: v_dual_mov_b32 v16, s52
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v17, s53 :: v_dual_mov_b32 v18, s54
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v19, s55 :: v_dual_mov_b32 v20, s56
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v21, s57 :: v_dual_mov_b32 v22, s58
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v23, s59 :: v_dual_mov_b32 v24, s60
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v25, s61 :: v_dual_mov_b32 v26, s62
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v27, s63 :: v_dual_mov_b32 v28, s64
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v29, s65 :: v_dual_mov_b32 v30, s66
; GFX13-GISEL-NEXT:    v_mov_b32_e32 v31, s67
; GFX13-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX13-GISEL-NEXT:    v_cvt_scalef32_pk32_bf6_f32 v[0:5], v[0:31], 0x42c80000
; GFX13-GISEL-NEXT:    s_clause 0x1
; GFX13-GISEL-NEXT:    global_store_b128 v32, v[0:3], s[0:1] scope:SCOPE_SE
; GFX13-GISEL-NEXT:    global_store_b64 v32, v[4:5], s[0:1] offset:16 scope:SCOPE_SE
; GFX13-GISEL-NEXT:    s_endpgm
  %cvt = tail call <6 x i32> @llvm.amdgcn.cvt.scalef32.pk32.bf6.f32(<32 x float> %src, float 100.0)
  store <6 x i32> %cvt, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_kernel void @test_cvt_scalef32_pk32_fp6_f32_v(ptr addrspace(1) %out, <32 x float> %src, float %scale) {
; GFX13-SDAG-LABEL: test_cvt_scalef32_pk32_fp6_f32_v:
; GFX13-SDAG:       ; %bb.0:
; GFX13-SDAG-NEXT:    s_clause 0x3
; GFX13-SDAG-NEXT:    s_load_b512 s[36:51], s[4:5], 0xa4
; GFX13-SDAG-NEXT:    s_load_b512 s[8:23], s[4:5], 0xe4
; GFX13-SDAG-NEXT:    s_load_b64 s[0:1], s[4:5], 0x24
; GFX13-SDAG-NEXT:    s_load_b32 s2, s[4:5], 0x124
; GFX13-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v32, 0 :: v_dual_mov_b32 v0, s36
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v1, s37 :: v_dual_mov_b32 v2, s38
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v3, s39 :: v_dual_mov_b32 v4, s40
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v5, s41 :: v_dual_mov_b32 v6, s42
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v7, s43 :: v_dual_mov_b32 v8, s44
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v9, s45 :: v_dual_mov_b32 v10, s46
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v11, s47 :: v_dual_mov_b32 v12, s48
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v13, s49 :: v_dual_mov_b32 v14, s50
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v15, s51 :: v_dual_mov_b32 v16, s8
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v17, s9 :: v_dual_mov_b32 v18, s10
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v19, s11 :: v_dual_mov_b32 v20, s12
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v21, s13 :: v_dual_mov_b32 v22, s14
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v23, s15 :: v_dual_mov_b32 v24, s16
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v25, s17 :: v_dual_mov_b32 v26, s18
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v27, s19 :: v_dual_mov_b32 v28, s20
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v29, s21 :: v_dual_mov_b32 v30, s22
; GFX13-SDAG-NEXT:    v_mov_b32_e32 v31, s23
; GFX13-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX13-SDAG-NEXT:    v_cvt_scalef32_pk32_fp6_f32 v[0:5], v[0:31], s2
; GFX13-SDAG-NEXT:    s_clause 0x1
; GFX13-SDAG-NEXT:    global_store_b64 v32, v[4:5], s[0:1] offset:16 scope:SCOPE_SE
; GFX13-SDAG-NEXT:    global_store_b128 v32, v[0:3], s[0:1] scope:SCOPE_SE
; GFX13-SDAG-NEXT:    s_endpgm
;
; GFX13-GISEL-LABEL: test_cvt_scalef32_pk32_fp6_f32_v:
; GFX13-GISEL:       ; %bb.0:
; GFX13-GISEL-NEXT:    s_clause 0x3
; GFX13-GISEL-NEXT:    s_load_b512 s[36:51], s[4:5], 0xa4
; GFX13-GISEL-NEXT:    s_load_b512 s[52:67], s[4:5], 0xe4
; GFX13-GISEL-NEXT:    s_load_b32 s2, s[4:5], 0x124
; GFX13-GISEL-NEXT:    s_load_b64 s[0:1], s[4:5], 0x24
; GFX13-GISEL-NEXT:    s_wait_kmcnt 0x0
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v32, 0 :: v_dual_mov_b32 v0, s36
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v1, s37 :: v_dual_mov_b32 v2, s38
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v3, s39 :: v_dual_mov_b32 v4, s40
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v5, s41 :: v_dual_mov_b32 v6, s42
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v7, s43 :: v_dual_mov_b32 v8, s44
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v9, s45 :: v_dual_mov_b32 v10, s46
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v11, s47 :: v_dual_mov_b32 v12, s48
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v13, s49 :: v_dual_mov_b32 v14, s50
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v15, s51 :: v_dual_mov_b32 v16, s52
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v17, s53 :: v_dual_mov_b32 v18, s54
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v19, s55 :: v_dual_mov_b32 v20, s56
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v21, s57 :: v_dual_mov_b32 v22, s58
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v23, s59 :: v_dual_mov_b32 v24, s60
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v25, s61 :: v_dual_mov_b32 v26, s62
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v27, s63 :: v_dual_mov_b32 v28, s64
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v29, s65 :: v_dual_mov_b32 v30, s66
; GFX13-GISEL-NEXT:    v_mov_b32_e32 v31, s67
; GFX13-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX13-GISEL-NEXT:    v_cvt_scalef32_pk32_fp6_f32 v[0:5], v[0:31], s2
; GFX13-GISEL-NEXT:    s_clause 0x1
; GFX13-GISEL-NEXT:    global_store_b128 v32, v[0:3], s[0:1] scope:SCOPE_SE
; GFX13-GISEL-NEXT:    global_store_b64 v32, v[4:5], s[0:1] offset:16 scope:SCOPE_SE
; GFX13-GISEL-NEXT:    s_endpgm
  %cvt = tail call <6 x i32> @llvm.amdgcn.cvt.scalef32.pk32.fp6.f32(<32 x float> %src, float %scale)
  store <6 x i32> %cvt, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_kernel void @test_cvt_scalef32_pk32_fp6_f32_s(ptr addrspace(1) %out, <32 x float> %src) {
; GFX13-SDAG-LABEL: test_cvt_scalef32_pk32_fp6_f32_s:
; GFX13-SDAG:       ; %bb.0:
; GFX13-SDAG-NEXT:    s_clause 0x2
; GFX13-SDAG-NEXT:    s_load_b512 s[36:51], s[4:5], 0xa4
; GFX13-SDAG-NEXT:    s_load_b512 s[8:23], s[4:5], 0xe4
; GFX13-SDAG-NEXT:    s_load_b64 s[0:1], s[4:5], 0x24
; GFX13-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v32, 0 :: v_dual_mov_b32 v0, s36
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v1, s37 :: v_dual_mov_b32 v2, s38
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v3, s39 :: v_dual_mov_b32 v4, s40
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v5, s41 :: v_dual_mov_b32 v6, s42
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v7, s43 :: v_dual_mov_b32 v8, s44
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v9, s45 :: v_dual_mov_b32 v10, s46
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v11, s47 :: v_dual_mov_b32 v12, s48
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v13, s49 :: v_dual_mov_b32 v14, s50
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v15, s51 :: v_dual_mov_b32 v16, s8
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v17, s9 :: v_dual_mov_b32 v18, s10
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v19, s11 :: v_dual_mov_b32 v20, s12
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v21, s13 :: v_dual_mov_b32 v22, s14
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v23, s15 :: v_dual_mov_b32 v24, s16
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v25, s17 :: v_dual_mov_b32 v26, s18
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v27, s19 :: v_dual_mov_b32 v28, s20
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v29, s21 :: v_dual_mov_b32 v30, s22
; GFX13-SDAG-NEXT:    v_mov_b32_e32 v31, s23
; GFX13-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX13-SDAG-NEXT:    v_cvt_scalef32_pk32_fp6_f32 v[0:5], v[0:31], 0x42c80000
; GFX13-SDAG-NEXT:    s_clause 0x1
; GFX13-SDAG-NEXT:    global_store_b64 v32, v[4:5], s[0:1] offset:16 scope:SCOPE_SE
; GFX13-SDAG-NEXT:    global_store_b128 v32, v[0:3], s[0:1] scope:SCOPE_SE
; GFX13-SDAG-NEXT:    s_endpgm
;
; GFX13-GISEL-LABEL: test_cvt_scalef32_pk32_fp6_f32_s:
; GFX13-GISEL:       ; %bb.0:
; GFX13-GISEL-NEXT:    s_clause 0x2
; GFX13-GISEL-NEXT:    s_load_b512 s[36:51], s[4:5], 0xa4
; GFX13-GISEL-NEXT:    s_load_b512 s[52:67], s[4:5], 0xe4
; GFX13-GISEL-NEXT:    s_load_b64 s[0:1], s[4:5], 0x24
; GFX13-GISEL-NEXT:    s_wait_kmcnt 0x0
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v32, 0 :: v_dual_mov_b32 v0, s36
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v1, s37 :: v_dual_mov_b32 v2, s38
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v3, s39 :: v_dual_mov_b32 v4, s40
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v5, s41 :: v_dual_mov_b32 v6, s42
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v7, s43 :: v_dual_mov_b32 v8, s44
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v9, s45 :: v_dual_mov_b32 v10, s46
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v11, s47 :: v_dual_mov_b32 v12, s48
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v13, s49 :: v_dual_mov_b32 v14, s50
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v15, s51 :: v_dual_mov_b32 v16, s52
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v17, s53 :: v_dual_mov_b32 v18, s54
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v19, s55 :: v_dual_mov_b32 v20, s56
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v21, s57 :: v_dual_mov_b32 v22, s58
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v23, s59 :: v_dual_mov_b32 v24, s60
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v25, s61 :: v_dual_mov_b32 v26, s62
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v27, s63 :: v_dual_mov_b32 v28, s64
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v29, s65 :: v_dual_mov_b32 v30, s66
; GFX13-GISEL-NEXT:    v_mov_b32_e32 v31, s67
; GFX13-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX13-GISEL-NEXT:    v_cvt_scalef32_pk32_fp6_f32 v[0:5], v[0:31], 0x42c80000
; GFX13-GISEL-NEXT:    s_clause 0x1
; GFX13-GISEL-NEXT:    global_store_b128 v32, v[0:3], s[0:1] scope:SCOPE_SE
; GFX13-GISEL-NEXT:    global_store_b64 v32, v[4:5], s[0:1] offset:16 scope:SCOPE_SE
; GFX13-GISEL-NEXT:    s_endpgm
  %cvt = tail call <6 x i32> @llvm.amdgcn.cvt.scalef32.pk32.fp6.f32(<32 x float> %src, float 100.0)
  store <6 x i32> %cvt, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_kernel void @test_cvt_scalef32_pk32_fp6_f32_v_inreg_src(ptr addrspace(1) %out, <32 x float> inreg %src, float %scale) {
; GFX13-SDAG-LABEL: test_cvt_scalef32_pk32_fp6_f32_v_inreg_src:
; GFX13-SDAG:       ; %bb.0:
; GFX13-SDAG-NEXT:    s_clause 0x3
; GFX13-SDAG-NEXT:    s_load_b512 s[36:51], s[4:5], 0xa4
; GFX13-SDAG-NEXT:    s_load_b512 s[8:23], s[4:5], 0xe4
; GFX13-SDAG-NEXT:    s_load_b32 s2, s[4:5], 0x124
; GFX13-SDAG-NEXT:    s_load_b64 s[0:1], s[4:5], 0x24
; GFX13-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v32, 0 :: v_dual_mov_b32 v0, s36
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v1, s37 :: v_dual_mov_b32 v2, s38
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v3, s39 :: v_dual_mov_b32 v4, s40
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v5, s41 :: v_dual_mov_b32 v6, s42
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v7, s43 :: v_dual_mov_b32 v8, s44
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v9, s45 :: v_dual_mov_b32 v10, s46
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v11, s47 :: v_dual_mov_b32 v12, s48
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v13, s49 :: v_dual_mov_b32 v14, s50
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v15, s51 :: v_dual_mov_b32 v16, s8
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v17, s9 :: v_dual_mov_b32 v18, s10
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v19, s11 :: v_dual_mov_b32 v20, s12
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v21, s13 :: v_dual_mov_b32 v22, s14
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v23, s15 :: v_dual_mov_b32 v24, s16
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v25, s17 :: v_dual_mov_b32 v26, s18
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v27, s19 :: v_dual_mov_b32 v28, s20
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v29, s21 :: v_dual_mov_b32 v30, s22
; GFX13-SDAG-NEXT:    v_mov_b32_e32 v31, s23
; GFX13-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX13-SDAG-NEXT:    v_cvt_scalef32_pk32_fp6_f32 v[0:5], v[0:31], s2
; GFX13-SDAG-NEXT:    s_clause 0x1
; GFX13-SDAG-NEXT:    global_store_b64 v32, v[4:5], s[0:1] offset:16 scope:SCOPE_SE
; GFX13-SDAG-NEXT:    global_store_b128 v32, v[0:3], s[0:1] scope:SCOPE_SE
; GFX13-SDAG-NEXT:    s_endpgm
;
; GFX13-GISEL-LABEL: test_cvt_scalef32_pk32_fp6_f32_v_inreg_src:
; GFX13-GISEL:       ; %bb.0:
; GFX13-GISEL-NEXT:    s_clause 0x3
; GFX13-GISEL-NEXT:    s_load_b512 s[36:51], s[4:5], 0xa4
; GFX13-GISEL-NEXT:    s_load_b512 s[52:67], s[4:5], 0xe4
; GFX13-GISEL-NEXT:    s_load_b32 s2, s[4:5], 0x124
; GFX13-GISEL-NEXT:    s_load_b64 s[0:1], s[4:5], 0x24
; GFX13-GISEL-NEXT:    s_wait_kmcnt 0x0
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v32, 0 :: v_dual_mov_b32 v0, s36
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v1, s37 :: v_dual_mov_b32 v2, s38
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v3, s39 :: v_dual_mov_b32 v4, s40
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v5, s41 :: v_dual_mov_b32 v6, s42
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v7, s43 :: v_dual_mov_b32 v8, s44
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v9, s45 :: v_dual_mov_b32 v10, s46
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v11, s47 :: v_dual_mov_b32 v12, s48
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v13, s49 :: v_dual_mov_b32 v14, s50
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v15, s51 :: v_dual_mov_b32 v16, s52
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v17, s53 :: v_dual_mov_b32 v18, s54
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v19, s55 :: v_dual_mov_b32 v20, s56
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v21, s57 :: v_dual_mov_b32 v22, s58
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v23, s59 :: v_dual_mov_b32 v24, s60
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v25, s61 :: v_dual_mov_b32 v26, s62
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v27, s63 :: v_dual_mov_b32 v28, s64
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v29, s65 :: v_dual_mov_b32 v30, s66
; GFX13-GISEL-NEXT:    v_mov_b32_e32 v31, s67
; GFX13-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX13-GISEL-NEXT:    v_cvt_scalef32_pk32_fp6_f32 v[0:5], v[0:31], s2
; GFX13-GISEL-NEXT:    s_clause 0x1
; GFX13-GISEL-NEXT:    global_store_b128 v32, v[0:3], s[0:1] scope:SCOPE_SE
; GFX13-GISEL-NEXT:    global_store_b64 v32, v[4:5], s[0:1] offset:16 scope:SCOPE_SE
; GFX13-GISEL-NEXT:    s_endpgm
  %cvt = tail call <6 x i32> @llvm.amdgcn.cvt.scalef32.pk32.fp6.f32(<32 x float> %src, float %scale)
  store <6 x i32> %cvt, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_kernel void @test_cvt_scalef32_pk32_fp6_f32_s_inreg_src(ptr addrspace(1) %out, <32 x float> inreg %src) {
; GFX13-SDAG-LABEL: test_cvt_scalef32_pk32_fp6_f32_s_inreg_src:
; GFX13-SDAG:       ; %bb.0:
; GFX13-SDAG-NEXT:    s_clause 0x2
; GFX13-SDAG-NEXT:    s_load_b512 s[36:51], s[4:5], 0xa4
; GFX13-SDAG-NEXT:    s_load_b512 s[8:23], s[4:5], 0xe4
; GFX13-SDAG-NEXT:    s_load_b64 s[0:1], s[4:5], 0x24
; GFX13-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v32, 0 :: v_dual_mov_b32 v0, s36
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v1, s37 :: v_dual_mov_b32 v2, s38
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v3, s39 :: v_dual_mov_b32 v4, s40
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v5, s41 :: v_dual_mov_b32 v6, s42
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v7, s43 :: v_dual_mov_b32 v8, s44
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v9, s45 :: v_dual_mov_b32 v10, s46
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v11, s47 :: v_dual_mov_b32 v12, s48
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v13, s49 :: v_dual_mov_b32 v14, s50
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v15, s51 :: v_dual_mov_b32 v16, s8
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v17, s9 :: v_dual_mov_b32 v18, s10
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v19, s11 :: v_dual_mov_b32 v20, s12
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v21, s13 :: v_dual_mov_b32 v22, s14
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v23, s15 :: v_dual_mov_b32 v24, s16
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v25, s17 :: v_dual_mov_b32 v26, s18
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v27, s19 :: v_dual_mov_b32 v28, s20
; GFX13-SDAG-NEXT:    v_dual_mov_b32 v29, s21 :: v_dual_mov_b32 v30, s22
; GFX13-SDAG-NEXT:    v_mov_b32_e32 v31, s23
; GFX13-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX13-SDAG-NEXT:    v_cvt_scalef32_pk32_fp6_f32 v[0:5], v[0:31], 0x42c80000
; GFX13-SDAG-NEXT:    s_clause 0x1
; GFX13-SDAG-NEXT:    global_store_b64 v32, v[4:5], s[0:1] offset:16 scope:SCOPE_SE
; GFX13-SDAG-NEXT:    global_store_b128 v32, v[0:3], s[0:1] scope:SCOPE_SE
; GFX13-SDAG-NEXT:    s_endpgm
;
; GFX13-GISEL-LABEL: test_cvt_scalef32_pk32_fp6_f32_s_inreg_src:
; GFX13-GISEL:       ; %bb.0:
; GFX13-GISEL-NEXT:    s_clause 0x2
; GFX13-GISEL-NEXT:    s_load_b512 s[36:51], s[4:5], 0xa4
; GFX13-GISEL-NEXT:    s_load_b512 s[52:67], s[4:5], 0xe4
; GFX13-GISEL-NEXT:    s_load_b64 s[0:1], s[4:5], 0x24
; GFX13-GISEL-NEXT:    s_wait_kmcnt 0x0
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v32, 0 :: v_dual_mov_b32 v0, s36
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v1, s37 :: v_dual_mov_b32 v2, s38
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v3, s39 :: v_dual_mov_b32 v4, s40
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v5, s41 :: v_dual_mov_b32 v6, s42
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v7, s43 :: v_dual_mov_b32 v8, s44
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v9, s45 :: v_dual_mov_b32 v10, s46
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v11, s47 :: v_dual_mov_b32 v12, s48
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v13, s49 :: v_dual_mov_b32 v14, s50
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v15, s51 :: v_dual_mov_b32 v16, s52
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v17, s53 :: v_dual_mov_b32 v18, s54
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v19, s55 :: v_dual_mov_b32 v20, s56
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v21, s57 :: v_dual_mov_b32 v22, s58
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v23, s59 :: v_dual_mov_b32 v24, s60
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v25, s61 :: v_dual_mov_b32 v26, s62
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v27, s63 :: v_dual_mov_b32 v28, s64
; GFX13-GISEL-NEXT:    v_dual_mov_b32 v29, s65 :: v_dual_mov_b32 v30, s66
; GFX13-GISEL-NEXT:    v_mov_b32_e32 v31, s67
; GFX13-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX13-GISEL-NEXT:    v_cvt_scalef32_pk32_fp6_f32 v[0:5], v[0:31], 0x42c80000
; GFX13-GISEL-NEXT:    s_clause 0x1
; GFX13-GISEL-NEXT:    global_store_b128 v32, v[0:3], s[0:1] scope:SCOPE_SE
; GFX13-GISEL-NEXT:    global_store_b64 v32, v[4:5], s[0:1] offset:16 scope:SCOPE_SE
; GFX13-GISEL-NEXT:    s_endpgm
  %cvt = tail call <6 x i32> @llvm.amdgcn.cvt.scalef32.pk32.fp6.f32(<32 x float> %src, float 100.0)
  store <6 x i32> %cvt, ptr addrspace(1) %out, align 8
  ret void
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; GFX13: {{.*}}
