; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=amdgcn -mcpu=gfx942 -O0 --global-isel=false -o - %s | FileCheck %s

declare i32 @llvm.amdgcn.workitem.id.x() #0
declare i32 @llvm.amdgcn.workitem.id.y() #0
declare i32 @llvm.amdgcn.workitem.id.z() #0

define amdgpu_ps i32 @test_workitem_id_x() #1 {
; CHECK-LABEL: test_workitem_id_x:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_mov_b32 s0, 0
; CHECK-NEXT:    ; return to shader part epilog
  %id = call i32 @llvm.amdgcn.workitem.id.x()
  ret i32 %id
}

define amdgpu_ps i32 @test_workitem_id_y() #1 {
; CHECK-LABEL: test_workitem_id_y:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_mov_b32 s0, 0
; CHECK-NEXT:    ; return to shader part epilog
  %id = call i32 @llvm.amdgcn.workitem.id.y()
  ret i32 %id
}

define amdgpu_ps i32 @test_workitem_id_z() #1 {
; CHECK-LABEL: test_workitem_id_z:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_mov_b32 s0, 0
; CHECK-NEXT:    ; return to shader part epilog
  %id = call i32 @llvm.amdgcn.workitem.id.z()
  ret i32 %id
}

attributes #0 = { nounwind readnone }
attributes #1 = { nounwind }
