; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=amdgcn -mcpu=gfx1300 -verify-machineinstrs < %s | FileCheck -check-prefixes=GFX13 %s

define amdgpu_kernel void @test_enable_scheduling_stall_const() {
; GFX13-LABEL: test_enable_scheduling_stall_const:
; GFX13:       ; %bb.0:
; GFX13-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_SCHED_MODE, 4, 1), 1
; GFX13-NEXT:    s_endpgm
  call void @llvm.amdgcn.set.wmma.scheduling(i32 1)
  ret void
}

define amdgpu_kernel void @test_disable_scheduling_stall_const() {
; GFX13-LABEL: test_disable_scheduling_stall_const:
; GFX13:       ; %bb.0:
; GFX13-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_SCHED_MODE, 4, 1), 0
; GFX13-NEXT:    s_endpgm
  call void @llvm.amdgcn.set.wmma.scheduling(i32 0)
  ret void
}

define amdgpu_kernel void @test_set_scheduling_stall_var(i32 %val) {
; GFX13-LABEL: test_set_scheduling_stall_var:
; GFX13:       ; %bb.0:
; GFX13-NEXT:    s_load_b32 s0, s[4:5], 0x24
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    s_setreg_b32 hwreg(HW_REG_SCHED_MODE, 4, 1), s0
; GFX13-NEXT:    s_endpgm
  call void @llvm.amdgcn.set.wmma.scheduling(i32 %val)
  ret void
}

declare void @llvm.amdgcn.set.wmma.scheduling(i32) #0

attributes #0 = { nounwind }
