; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -global-isel=0 -mtriple=amdgcn -mcpu=tonga < %s | FileCheck -check-prefix=WAVE64 %s
; RUN: llc -global-isel=1 -mtriple=amdgcn -mcpu=tonga < %s | FileCheck -check-prefix=WAVE64 %s
; RUN: llc -global-isel=0 -mtriple=amdgcn -mcpu=gfx1010 < %s | FileCheck -check-prefix=GFX10 %s
; RUN: llc -global-isel=1 -mtriple=amdgcn -mcpu=gfx1010 < %s | FileCheck -check-prefix=GFX10 %s
; RUN: llc -global-isel=0 -mtriple=amdgcn -mcpu=gfx1100 < %s | FileCheck -check-prefix=GFX11 %s
; RUN: llc -global-isel=1 -mtriple=amdgcn -mcpu=gfx1100 < %s | FileCheck -check-prefix=GFX11 %s

define amdgpu_ps float @ret(i32 %v0, i32 %v1) #1 {
; WAVE64-LABEL: ret:
; WAVE64:       ; %bb.0: ; %main_body
; WAVE64-NEXT:    v_cmp_eq_u32_e32 vcc, v0, v1
; WAVE64-NEXT:    s_wqm_b64 s[0:1], vcc
; WAVE64-NEXT:    v_cndmask_b32_e64 v0, 0, 1.0, s[0:1]
; WAVE64-NEXT:    ; return to shader part epilog
;
; GFX10-LABEL: ret:
; GFX10:       ; %bb.0: ; %main_body
; GFX10-NEXT:    v_cmp_eq_u32_e32 vcc_lo, v0, v1
; GFX10-NEXT:    s_wqm_b32 s0, vcc_lo
; GFX10-NEXT:    v_cndmask_b32_e64 v0, 0, 1.0, s0
; GFX10-NEXT:    ; return to shader part epilog
;
; GFX11-LABEL: ret:
; GFX11:       ; %bb.0: ; %main_body
; GFX11-NEXT:    v_cmp_eq_u32_e32 vcc_lo, v0, v1
; GFX11-NEXT:    s_wqm_b32 s0, vcc_lo
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    v_cndmask_b32_e64 v0, 0, 1.0, s0
; GFX11-NEXT:    ; return to shader part epilog
main_body:
  %c = icmp eq i32 %v0, %v1
  %w = call i1 @llvm.amdgcn.wqm.vote(i1 %c)
  %r = select i1 %w, float 1.0, float 0.0
  ret float %r
}

define amdgpu_ps float @true() #1 {
; WAVE64-LABEL: true:
; WAVE64:       ; %bb.0: ; %main_body
; WAVE64-NEXT:    s_wqm_b64 s[0:1], -1
; WAVE64-NEXT:    v_cndmask_b32_e64 v0, 0, 1.0, s[0:1]
; WAVE64-NEXT:    ; return to shader part epilog
;
; GFX10-LABEL: true:
; GFX10:       ; %bb.0: ; %main_body
; GFX10-NEXT:    s_wqm_b32 s0, -1
; GFX10-NEXT:    v_cndmask_b32_e64 v0, 0, 1.0, s0
; GFX10-NEXT:    ; return to shader part epilog
;
; GFX11-LABEL: true:
; GFX11:       ; %bb.0: ; %main_body
; GFX11-NEXT:    s_wqm_b32 s0, -1
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    v_cndmask_b32_e64 v0, 0, 1.0, s0
; GFX11-NEXT:    ; return to shader part epilog
main_body:
  %w = call i1 @llvm.amdgcn.wqm.vote(i1 true)
  %r = select i1 %w, float 1.0, float 0.0
  ret float %r
}

define amdgpu_ps float @false() #1 {
; WAVE64-LABEL: false:
; WAVE64:       ; %bb.0: ; %main_body
; WAVE64-NEXT:    s_wqm_b64 s[0:1], 0
; WAVE64-NEXT:    v_cndmask_b32_e64 v0, 0, 1.0, s[0:1]
; WAVE64-NEXT:    ; return to shader part epilog
;
; GFX10-LABEL: false:
; GFX10:       ; %bb.0: ; %main_body
; GFX10-NEXT:    s_wqm_b32 s0, 0
; GFX10-NEXT:    v_cndmask_b32_e64 v0, 0, 1.0, s0
; GFX10-NEXT:    ; return to shader part epilog
;
; GFX11-LABEL: false:
; GFX11:       ; %bb.0: ; %main_body
; GFX11-NEXT:    s_wqm_b32 s0, 0
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX11-NEXT:    v_cndmask_b32_e64 v0, 0, 1.0, s0
; GFX11-NEXT:    ; return to shader part epilog
main_body:
  %w = call i1 @llvm.amdgcn.wqm.vote(i1 false)
  %r = select i1 %w, float 1.0, float 0.0
  ret float %r
}

; Note: an almost identical test for this exists in llvm.amdgcn.kill.ll
define amdgpu_ps float @kill(i32 %v0, i32 %v1) #1 {
; WAVE64-LABEL: kill:
; WAVE64:       ; %bb.0: ; %main_body
; WAVE64-NEXT:    v_cmp_eq_u32_e32 vcc, v0, v1
; WAVE64-NEXT:    s_wqm_b64 s[2:3], vcc
; WAVE64-NEXT:    s_mov_b64 s[0:1], exec
; WAVE64-NEXT:    s_andn2_b64 s[2:3], exec, s[2:3]
; WAVE64-NEXT:    s_andn2_b64 s[0:1], s[0:1], s[2:3]
; WAVE64-NEXT:    s_cbranch_scc0 .LBB3_2
; WAVE64-NEXT:  ; %bb.1: ; %main_body
; WAVE64-NEXT:    s_and_b64 exec, exec, s[0:1]
; WAVE64-NEXT:    v_mov_b32_e32 v0, 0
; WAVE64-NEXT:    s_branch .LBB3_3
; WAVE64-NEXT:  .LBB3_2:
; WAVE64-NEXT:    s_mov_b64 exec, 0
; WAVE64-NEXT:    exp null, off, off, off, off done vm
; WAVE64-NEXT:    s_endpgm
; WAVE64-NEXT:  .LBB3_3:
;
; GFX10-LABEL: kill:
; GFX10:       ; %bb.0: ; %main_body
; GFX10-NEXT:    v_cmp_eq_u32_e32 vcc_lo, v0, v1
; GFX10-NEXT:    s_mov_b32 s0, exec_lo
; GFX10-NEXT:    s_wqm_b32 s1, vcc_lo
; GFX10-NEXT:    s_andn2_b32 s1, exec_lo, s1
; GFX10-NEXT:    s_andn2_b32 s0, s0, s1
; GFX10-NEXT:    s_cbranch_scc0 .LBB3_2
; GFX10-NEXT:  ; %bb.1: ; %main_body
; GFX10-NEXT:    s_and_b32 exec_lo, exec_lo, s0
; GFX10-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-NEXT:    s_branch .LBB3_3
; GFX10-NEXT:  .LBB3_2:
; GFX10-NEXT:    s_mov_b32 exec_lo, 0
; GFX10-NEXT:    exp null, off, off, off, off done vm
; GFX10-NEXT:    s_endpgm
; GFX10-NEXT:  .LBB3_3:
;
; GFX11-LABEL: kill:
; GFX11:       ; %bb.0: ; %main_body
; GFX11-NEXT:    v_cmp_eq_u32_e32 vcc_lo, v0, v1
; GFX11-NEXT:    s_mov_b32 s0, exec_lo
; GFX11-NEXT:    s_wqm_b32 s1, vcc_lo
; GFX11-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(SALU_CYCLE_1)
; GFX11-NEXT:    s_and_not1_b32 s1, exec_lo, s1
; GFX11-NEXT:    s_and_not1_b32 s0, s0, s1
; GFX11-NEXT:    s_cbranch_scc0 .LBB3_2
; GFX11-NEXT:  ; %bb.1: ; %main_body
; GFX11-NEXT:    s_and_b32 exec_lo, exec_lo, s0
; GFX11-NEXT:    v_mov_b32_e32 v0, 0
; GFX11-NEXT:    s_branch .LBB3_3
; GFX11-NEXT:  .LBB3_2:
; GFX11-NEXT:    s_mov_b32 exec_lo, 0
; GFX11-NEXT:    exp mrt0, off, off, off, off done
; GFX11-NEXT:    s_endpgm
; GFX11-NEXT:  .LBB3_3:
main_body:
  %c = icmp eq i32 %v0, %v1
  %w = call i1 @llvm.amdgcn.wqm.vote(i1 %c)
  call void @llvm.amdgcn.kill(i1 %w)
  ret float 0.0
}

declare void @llvm.amdgcn.kill(i1) #1
declare i1 @llvm.amdgcn.wqm.vote(i1)

attributes #1 = { nounwind }
