; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=amdgcn -mcpu=gfx1300 -verify-machineinstrs -show-mc-encoding < %s | FileCheck -check-prefixes=GFX13 %s

define amdgpu_ps float @atomic_swap_1d(i32 inreg %rsrc, i32 %data, i32 %s) {
; GFX13-LABEL: atomic_swap_1d:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    image_atomic_swap v0, v1, s0 dmask:0x1 dim:SQ_RSRC_IMG_1D th:TH_ATOMIC_RETURN ; encoding: [0x00,0xc0,0x43,0xd0,0x00,0x00,0x11,0x00,0x01,0x00,0x00,0x00]
; GFX13-NEXT:    s_wait_loadcnt 0x0 ; encoding: [0x00,0x00,0xc0,0xbf]
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.swap.1d.i32.i32(i32 %data, i32 %s, i32 %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps <2 x float> @atomic_swap_1d_i64(i32 inreg %rsrc, i64 %data, i32 %s) {
; GFX13-LABEL: atomic_swap_1d_i64:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    image_atomic_swap v[0:1], v2, s0 dmask:0x3 dim:SQ_RSRC_IMG_1D th:TH_ATOMIC_RETURN ; encoding: [0x00,0xc0,0xc3,0xd0,0x00,0x00,0x11,0x00,0x02,0x00,0x00,0x00]
; GFX13-NEXT:    s_wait_loadcnt 0x0 ; encoding: [0x00,0x00,0xc0,0xbf]
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %v = call i64 @llvm.amdgcn.image.atomic.swap.1d.i64.i32(i64 %data, i32 %s, i32 %rsrc, i32 0, i32 0)
  %out = bitcast i64 %v to <2 x float>
  ret <2 x float> %out
}

define amdgpu_ps float @atomic_add_1d(i32 inreg %rsrc, i32 %data, i32 %s) {
; GFX13-LABEL: atomic_add_1d:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    image_atomic_add_uint v0, v1, s0 dmask:0x1 dim:SQ_RSRC_IMG_1D th:TH_ATOMIC_RETURN ; encoding: [0x00,0x40,0x44,0xd0,0x00,0x00,0x11,0x00,0x01,0x00,0x00,0x00]
; GFX13-NEXT:    s_wait_loadcnt 0x0 ; encoding: [0x00,0x00,0xc0,0xbf]
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.add.1d.i32.i32(i32 %data, i32 %s, i32 %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_sub_1d(i32 inreg %rsrc, i32 %data, i32 %s) {
; GFX13-LABEL: atomic_sub_1d:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    image_atomic_sub_uint v0, v1, s0 dmask:0x1 dim:SQ_RSRC_IMG_1D th:TH_ATOMIC_RETURN ; encoding: [0x00,0x80,0x44,0xd0,0x00,0x00,0x11,0x00,0x01,0x00,0x00,0x00]
; GFX13-NEXT:    s_wait_loadcnt 0x0 ; encoding: [0x00,0x00,0xc0,0xbf]
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.sub.1d.i32.i32(i32 %data, i32 %s, i32 %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_smin_1d(i32 inreg %rsrc, i32 %data, i32 %s) {
; GFX13-LABEL: atomic_smin_1d:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    image_atomic_min_int v0, v1, s0 dmask:0x1 dim:SQ_RSRC_IMG_1D th:TH_ATOMIC_RETURN ; encoding: [0x00,0x00,0x45,0xd0,0x00,0x00,0x11,0x00,0x01,0x00,0x00,0x00]
; GFX13-NEXT:    s_wait_loadcnt 0x0 ; encoding: [0x00,0x00,0xc0,0xbf]
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.smin.1d.i32.i32(i32 %data, i32 %s, i32 %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_umin_1d(i32 inreg %rsrc, i32 %data, i32 %s) {
; GFX13-LABEL: atomic_umin_1d:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    image_atomic_min_uint v0, v1, s0 dmask:0x1 dim:SQ_RSRC_IMG_1D th:TH_ATOMIC_RETURN ; encoding: [0x00,0x40,0x45,0xd0,0x00,0x00,0x11,0x00,0x01,0x00,0x00,0x00]
; GFX13-NEXT:    s_wait_loadcnt 0x0 ; encoding: [0x00,0x00,0xc0,0xbf]
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.umin.1d.i32.i32(i32 %data, i32 %s, i32 %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_smax_1d(i32 inreg %rsrc, i32 %data, i32 %s) {
; GFX13-LABEL: atomic_smax_1d:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    image_atomic_max_int v0, v1, s0 dmask:0x1 dim:SQ_RSRC_IMG_1D th:TH_ATOMIC_RETURN ; encoding: [0x00,0x80,0x45,0xd0,0x00,0x00,0x11,0x00,0x01,0x00,0x00,0x00]
; GFX13-NEXT:    s_wait_loadcnt 0x0 ; encoding: [0x00,0x00,0xc0,0xbf]
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.smax.1d.i32.i32(i32 %data, i32 %s, i32 %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_umax_1d(i32 inreg %rsrc, i32 %data, i32 %s) {
; GFX13-LABEL: atomic_umax_1d:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    image_atomic_max_uint v0, v1, s0 dmask:0x1 dim:SQ_RSRC_IMG_1D th:TH_ATOMIC_RETURN ; encoding: [0x00,0xc0,0x45,0xd0,0x00,0x00,0x11,0x00,0x01,0x00,0x00,0x00]
; GFX13-NEXT:    s_wait_loadcnt 0x0 ; encoding: [0x00,0x00,0xc0,0xbf]
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.umax.1d.i32.i32(i32 %data, i32 %s, i32 %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_and_1d(i32 inreg %rsrc, i32 %data, i32 %s) {
; GFX13-LABEL: atomic_and_1d:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    image_atomic_and v0, v1, s0 dmask:0x1 dim:SQ_RSRC_IMG_1D th:TH_ATOMIC_RETURN ; encoding: [0x00,0x00,0x46,0xd0,0x00,0x00,0x11,0x00,0x01,0x00,0x00,0x00]
; GFX13-NEXT:    s_wait_loadcnt 0x0 ; encoding: [0x00,0x00,0xc0,0xbf]
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.and.1d.i32.i32(i32 %data, i32 %s, i32 %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_or_1d(i32 inreg %rsrc, i32 %data, i32 %s) {
; GFX13-LABEL: atomic_or_1d:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    image_atomic_or v0, v1, s0 dmask:0x1 dim:SQ_RSRC_IMG_1D th:TH_ATOMIC_RETURN ; encoding: [0x00,0x40,0x46,0xd0,0x00,0x00,0x11,0x00,0x01,0x00,0x00,0x00]
; GFX13-NEXT:    s_wait_loadcnt 0x0 ; encoding: [0x00,0x00,0xc0,0xbf]
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.or.1d.i32.i32(i32 %data, i32 %s, i32 %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_xor_1d(i32 inreg %rsrc, i32 %data, i32 %s) {
; GFX13-LABEL: atomic_xor_1d:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    image_atomic_xor v0, v1, s0 dmask:0x1 dim:SQ_RSRC_IMG_1D th:TH_ATOMIC_RETURN ; encoding: [0x00,0x80,0x46,0xd0,0x00,0x00,0x11,0x00,0x01,0x00,0x00,0x00]
; GFX13-NEXT:    s_wait_loadcnt 0x0 ; encoding: [0x00,0x00,0xc0,0xbf]
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.xor.1d.i32.i32(i32 %data, i32 %s, i32 %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_inc_1d(i32 inreg %rsrc, i32 %data, i32 %s) {
; GFX13-LABEL: atomic_inc_1d:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    image_atomic_inc_uint v0, v1, s0 dmask:0x1 dim:SQ_RSRC_IMG_1D th:TH_ATOMIC_RETURN ; encoding: [0x00,0xc0,0x46,0xd0,0x00,0x00,0x11,0x00,0x01,0x00,0x00,0x00]
; GFX13-NEXT:    s_wait_loadcnt 0x0 ; encoding: [0x00,0x00,0xc0,0xbf]
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.inc.1d.i32.i32(i32 %data, i32 %s, i32 %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_dec_1d(i32 inreg %rsrc, i32 %data, i32 %s) {
; GFX13-LABEL: atomic_dec_1d:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    image_atomic_dec_uint v0, v1, s0 dmask:0x1 dim:SQ_RSRC_IMG_1D th:TH_ATOMIC_RETURN ; encoding: [0x00,0x00,0x47,0xd0,0x00,0x00,0x11,0x00,0x01,0x00,0x00,0x00]
; GFX13-NEXT:    s_wait_loadcnt 0x0 ; encoding: [0x00,0x00,0xc0,0xbf]
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.dec.1d.i32.i32(i32 %data, i32 %s, i32 %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_cmpswap_1d(i32 inreg %rsrc, i32 %cmp, i32 %swap, i32 %s) {
; GFX13-LABEL: atomic_cmpswap_1d:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    image_atomic_cmpswap v[0:1], v2, s0 dmask:0x3 dim:SQ_RSRC_IMG_1D th:TH_ATOMIC_RETURN ; encoding: [0x00,0x00,0xc4,0xd0,0x00,0x00,0x11,0x00,0x02,0x00,0x00,0x00]
; GFX13-NEXT:    s_wait_loadcnt 0x0 ; encoding: [0x00,0x00,0xc0,0xbf]
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.cmpswap.1d.i32.i32(i32 %cmp, i32 %swap, i32 %s, i32 %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps <2 x float> @atomic_cmpswap_1d_64(i32 inreg %rsrc, i64 %cmp, i64 %swap, i32 %s) {
; GFX13-LABEL: atomic_cmpswap_1d_64:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    image_atomic_cmpswap v[0:3], v4, s0 dmask:0xf dim:SQ_RSRC_IMG_1D th:TH_ATOMIC_RETURN ; encoding: [0x00,0x00,0xc4,0xd3,0x00,0x00,0x11,0x00,0x04,0x00,0x00,0x00]
; GFX13-NEXT:    s_wait_loadcnt 0x0 ; encoding: [0x00,0x00,0xc0,0xbf]
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %v = call i64 @llvm.amdgcn.image.atomic.cmpswap.1d.i64.i32(i64 %cmp, i64 %swap, i32 %s, i32 %rsrc, i32 0, i32 0)
  %out = bitcast i64 %v to <2 x float>
  ret <2 x float> %out
}

define amdgpu_ps float @atomic_add_2d(i32 inreg %rsrc, i32 %data, i32 %s, i32 %t) {
; GFX13-LABEL: atomic_add_2d:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    image_atomic_add_uint v0, [v1, v2], s0 dmask:0x1 dim:SQ_RSRC_IMG_2D th:TH_ATOMIC_RETURN ; encoding: [0x01,0x40,0x44,0xd0,0x00,0x00,0x11,0x00,0x01,0x02,0x00,0x00]
; GFX13-NEXT:    s_wait_loadcnt 0x0 ; encoding: [0x00,0x00,0xc0,0xbf]
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.add.2d.i32.i32(i32 %data, i32 %s, i32 %t, i32 %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_add_3d(i32 inreg %rsrc, i32 %data, i32 %s, i32 %t, i32 %r) {
; GFX13-LABEL: atomic_add_3d:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    image_atomic_add_uint v0, [v1, v2, v3], s0 dmask:0x1 dim:SQ_RSRC_IMG_3D th:TH_ATOMIC_RETURN ; encoding: [0x02,0x40,0x44,0xd0,0x00,0x00,0x11,0x00,0x01,0x02,0x03,0x00]
; GFX13-NEXT:    s_wait_loadcnt 0x0 ; encoding: [0x00,0x00,0xc0,0xbf]
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.add.3d.i32.i32(i32 %data, i32 %s, i32 %t, i32 %r, i32 %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_add_cube(i32 inreg %rsrc, i32 %data, i32 %s, i32 %t, i32 %face) {
; GFX13-LABEL: atomic_add_cube:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    image_atomic_add_uint v0, [v1, v2, v3], s0 dmask:0x1 dim:SQ_RSRC_IMG_CUBE th:TH_ATOMIC_RETURN ; encoding: [0x03,0x40,0x44,0xd0,0x00,0x00,0x11,0x00,0x01,0x02,0x03,0x00]
; GFX13-NEXT:    s_wait_loadcnt 0x0 ; encoding: [0x00,0x00,0xc0,0xbf]
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.add.cube.i32.i32(i32 %data, i32 %s, i32 %t, i32 %face, i32 %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_add_1darray(i32 inreg %rsrc, i32 %data, i32 %s, i32 %slice) {
; GFX13-LABEL: atomic_add_1darray:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    image_atomic_add_uint v0, [v1, v2], s0 dmask:0x1 dim:SQ_RSRC_IMG_1D_ARRAY th:TH_ATOMIC_RETURN ; encoding: [0x04,0x40,0x44,0xd0,0x00,0x00,0x11,0x00,0x01,0x02,0x00,0x00]
; GFX13-NEXT:    s_wait_loadcnt 0x0 ; encoding: [0x00,0x00,0xc0,0xbf]
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.add.1darray.i32.i32(i32 %data, i32 %s, i32 %slice, i32 %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_add_2darray(i32 inreg %rsrc, i32 %data, i32 %s, i32 %t, i32 %slice) {
; GFX13-LABEL: atomic_add_2darray:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    image_atomic_add_uint v0, [v1, v2, v3], s0 dmask:0x1 dim:SQ_RSRC_IMG_2D_ARRAY th:TH_ATOMIC_RETURN ; encoding: [0x05,0x40,0x44,0xd0,0x00,0x00,0x11,0x00,0x01,0x02,0x03,0x00]
; GFX13-NEXT:    s_wait_loadcnt 0x0 ; encoding: [0x00,0x00,0xc0,0xbf]
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.add.2darray.i32.i32(i32 %data, i32 %s, i32 %t, i32 %slice, i32 %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_add_2dmsaa(i32 inreg %rsrc, i32 %data, i32 %s, i32 %t, i32 %fragid) {
; GFX13-LABEL: atomic_add_2dmsaa:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    image_atomic_add_uint v0, [v1, v2, v3], s0 dmask:0x1 dim:SQ_RSRC_IMG_2D_MSAA th:TH_ATOMIC_RETURN ; encoding: [0x06,0x40,0x44,0xd0,0x00,0x00,0x11,0x00,0x01,0x02,0x03,0x00]
; GFX13-NEXT:    s_wait_loadcnt 0x0 ; encoding: [0x00,0x00,0xc0,0xbf]
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.add.2dmsaa.i32.i32(i32 %data, i32 %s, i32 %t, i32 %fragid, i32 %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_add_2darraymsaa(i32 inreg %rsrc, i32 %data, i32 %s, i32 %t, i32 %slice, i32 %fragid) {
; GFX13-LABEL: atomic_add_2darraymsaa:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    image_atomic_add_uint v0, [v1, v2, v3, v4], s0 dmask:0x1 dim:SQ_RSRC_IMG_2D_MSAA_ARRAY th:TH_ATOMIC_RETURN ; encoding: [0x07,0x40,0x44,0xd0,0x00,0x00,0x11,0x00,0x01,0x02,0x03,0x04]
; GFX13-NEXT:    s_wait_loadcnt 0x0 ; encoding: [0x00,0x00,0xc0,0xbf]
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.add.2darraymsaa.i32.i32(i32 %data, i32 %s, i32 %t, i32 %slice, i32 %fragid, i32 %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_add_1d_slc(i32 inreg %rsrc, i32 %data, i32 %s) {
; GFX13-LABEL: atomic_add_1d_slc:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    image_atomic_add_uint v0, v1, s0 dmask:0x1 dim:SQ_RSRC_IMG_1D th:TH_ATOMIC_NT_RETURN ; encoding: [0x00,0x40,0x44,0xd0,0x00,0x00,0x31,0x00,0x01,0x00,0x00,0x00]
; GFX13-NEXT:    s_wait_loadcnt 0x0 ; encoding: [0x00,0x00,0xc0,0xbf]
; GFX13-NEXT:    ; return to shader part epilog
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.add.1d.i32.i32(i32 %data, i32 %s, i32 %rsrc, i32 0, i32 2)
  %out = bitcast i32 %v to float
  ret float %out
}

declare i32 @llvm.amdgcn.image.atomic.swap.1d.i32.i32(i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.image.atomic.add.1d.i32.i32(i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.image.atomic.sub.1d.i32.i32(i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.image.atomic.smin.1d.i32.i32(i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.image.atomic.umin.1d.i32.i32(i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.image.atomic.smax.1d.i32.i32(i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.image.atomic.umax.1d.i32.i32(i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.image.atomic.and.1d.i32.i32(i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.image.atomic.or.1d.i32.i32(i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.image.atomic.xor.1d.i32.i32(i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.image.atomic.inc.1d.i32.i32(i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.image.atomic.dec.1d.i32.i32(i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.image.atomic.cmpswap.1d.i32.i32(i32, i32, i32, i32, i32, i32) #0

declare i64 @llvm.amdgcn.image.atomic.swap.1d.i64.i32(i64, i32, i32, i32, i32) #0
declare i64 @llvm.amdgcn.image.atomic.cmpswap.1d.i64.i32(i64, i64, i32, i32, i32, i32) #0

declare i32 @llvm.amdgcn.image.atomic.add.2d.i32.i32(i32, i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.image.atomic.add.3d.i32.i32(i32, i32, i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.image.atomic.add.cube.i32.i32(i32, i32, i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.image.atomic.add.1darray.i32.i32(i32, i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.image.atomic.add.2darray.i32.i32(i32, i32, i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.image.atomic.add.2dmsaa.i32.i32(i32, i32, i32, i32, i32, i32, i32) #0
declare i32 @llvm.amdgcn.image.atomic.add.2darraymsaa.i32.i32(i32, i32, i32, i32, i32, i32, i32, i32) #0

attributes #0 = { nounwind }
attributes #1 = { nounwind readonly }
attributes #2 = { nounwind readnone }
