; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -march=amdgcn -mcpu=gfx950 -global-isel=0 < %s | FileCheck -enable-var-scope --check-prefix=GCN %s
; xUN: llc -march=amdgcn -mcpu=gfx950 -global-isel=1 < %s | FileCheck -enable-var-scope --check-prefix=GCN %s


declare <4 x float> @llvm.amdgcn.mfma.f32.16x16x128.f8f6f4.scaled(<8 x i32>, <8 x i32>, <4 x float>, i32 immarg, i32 immarg, i32 immarg,
                                                                   i32 immarg, i32, i32 immarg, i32)


define <4 x float> @test_mfma_f32_16x16x128_f8f6f4_scaled_0_0(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2, i32 %scale0, i32 %scale1) {
; GCN-LABEL: test_mfma_f32_16x16x128_f8f6f4_scaled_0_0:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_accvgpr_write_b32 a0, v16
; GCN-NEXT:    v_accvgpr_write_b32 a1, v17
; GCN-NEXT:    v_accvgpr_write_b32 a2, v18
; GCN-NEXT:    v_accvgpr_write_b32 a3, v19
; GCN-NEXT:    v_mfma_ld_scale_b32 v20, v21 op_sel_hi:[0,0]
; GCN-NEXT:    s_nop 0
; GCN-NEXT:    v_mfma_f32_16x16x128_f8f6f4 a[0:3], v[0:7], v[8:15], a[0:3]
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 2
; GCN-NEXT:    v_accvgpr_read_b32 v0, a0
; GCN-NEXT:    v_accvgpr_read_b32 v1, a1
; GCN-NEXT:    v_accvgpr_read_b32 v2, a2
; GCN-NEXT:    v_accvgpr_read_b32 v3, a3
; GCN-NEXT:    s_setpc_b64 s[30:31]
  %result = call <4 x float> @llvm.amdgcn.mfma.f32.16x16x128.f8f6f4.scaled(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2,
  i32 immarg 0, i32 immarg 0, i32 immarg 0,
  i32 immarg 0, i32 %scale0, i32 immarg 0, i32 %scale1)
  ret <4 x float> %result
}

define <4 x float> @test_mfma_f32_16x16x128_f8f6f4_scaled_1_1(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2, i32 %scale0, i32 %scale1) {
; GCN-LABEL: test_mfma_f32_16x16x128_f8f6f4_scaled_1_1:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_accvgpr_write_b32 a0, v16
; GCN-NEXT:    v_accvgpr_write_b32 a1, v17
; GCN-NEXT:    v_accvgpr_write_b32 a2, v18
; GCN-NEXT:    v_accvgpr_write_b32 a3, v19
; GCN-NEXT:    v_mfma_ld_scale_b32 v20, v21 op_sel:[1,1] op_sel_hi:[0,0]
; GCN-NEXT:    s_nop 0
; GCN-NEXT:    v_mfma_f32_16x16x128_f8f6f4 a[0:3], v[0:7], v[8:15], a[0:3]
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 2
; GCN-NEXT:    v_accvgpr_read_b32 v0, a0
; GCN-NEXT:    v_accvgpr_read_b32 v1, a1
; GCN-NEXT:    v_accvgpr_read_b32 v2, a2
; GCN-NEXT:    v_accvgpr_read_b32 v3, a3
; GCN-NEXT:    s_setpc_b64 s[30:31]
  %result = call <4 x float> @llvm.amdgcn.mfma.f32.16x16x128.f8f6f4.scaled(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2,
  i32 immarg 0, i32 immarg 0, i32 immarg 0,
  i32 immarg 1, i32 %scale0, i32 immarg 1, i32 %scale1)
  ret <4 x float> %result
}

define <4 x float> @test_mfma_f32_16x16x128_f8f6f4_scaled_2_2(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2, i32 %scale0, i32 %scale1) {
; GCN-LABEL: test_mfma_f32_16x16x128_f8f6f4_scaled_2_2:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_accvgpr_write_b32 a0, v16
; GCN-NEXT:    v_accvgpr_write_b32 a1, v17
; GCN-NEXT:    v_accvgpr_write_b32 a2, v18
; GCN-NEXT:    v_accvgpr_write_b32 a3, v19
; GCN-NEXT:    v_mfma_ld_scale_b32 v20, v21
; GCN-NEXT:    s_nop 0
; GCN-NEXT:    v_mfma_f32_16x16x128_f8f6f4 a[0:3], v[0:7], v[8:15], a[0:3]
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 2
; GCN-NEXT:    v_accvgpr_read_b32 v0, a0
; GCN-NEXT:    v_accvgpr_read_b32 v1, a1
; GCN-NEXT:    v_accvgpr_read_b32 v2, a2
; GCN-NEXT:    v_accvgpr_read_b32 v3, a3
; GCN-NEXT:    s_setpc_b64 s[30:31]
  %result = call <4 x float> @llvm.amdgcn.mfma.f32.16x16x128.f8f6f4.scaled(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2,
  i32 immarg 0, i32 immarg 0, i32 immarg 0,
  i32 immarg 2, i32 %scale0, i32 immarg 2, i32 %scale1)
  ret <4 x float> %result
}

define <4 x float> @test_mfma_f32_16x16x128_f8f6f4_scaled_3_3(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2, i32 %scale0, i32 %scale1) {
; GCN-LABEL: test_mfma_f32_16x16x128_f8f6f4_scaled_3_3:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_accvgpr_write_b32 a0, v16
; GCN-NEXT:    v_accvgpr_write_b32 a1, v17
; GCN-NEXT:    v_accvgpr_write_b32 a2, v18
; GCN-NEXT:    v_accvgpr_write_b32 a3, v19
; GCN-NEXT:    v_mfma_ld_scale_b32 v20, v21 op_sel:[1,1]
; GCN-NEXT:    s_nop 0
; GCN-NEXT:    v_mfma_f32_16x16x128_f8f6f4 a[0:3], v[0:7], v[8:15], a[0:3]
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 2
; GCN-NEXT:    v_accvgpr_read_b32 v0, a0
; GCN-NEXT:    v_accvgpr_read_b32 v1, a1
; GCN-NEXT:    v_accvgpr_read_b32 v2, a2
; GCN-NEXT:    v_accvgpr_read_b32 v3, a3
; GCN-NEXT:    s_setpc_b64 s[30:31]
  %result = call <4 x float> @llvm.amdgcn.mfma.f32.16x16x128.f8f6f4.scaled(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2,
  i32 immarg 0, i32 immarg 0, i32 immarg 0,
  i32 immarg 3, i32 %scale0, i32 immarg 3, i32 %scale1)
  ret <4 x float> %result
}

define <4 x float> @test_mfma_f32_16x16x128_f8f6f4_scaled_0_3(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2, i32 %scale0, i32 %scale1) {
; GCN-LABEL: test_mfma_f32_16x16x128_f8f6f4_scaled_0_3:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_accvgpr_write_b32 a0, v16
; GCN-NEXT:    v_accvgpr_write_b32 a1, v17
; GCN-NEXT:    v_accvgpr_write_b32 a2, v18
; GCN-NEXT:    v_accvgpr_write_b32 a3, v19
; GCN-NEXT:    v_mfma_ld_scale_b32 v20, v21 op_sel:[0,1] op_sel_hi:[0,1]
; GCN-NEXT:    s_nop 0
; GCN-NEXT:    v_mfma_f32_16x16x128_f8f6f4 a[0:3], v[0:7], v[8:15], a[0:3]
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 2
; GCN-NEXT:    v_accvgpr_read_b32 v0, a0
; GCN-NEXT:    v_accvgpr_read_b32 v1, a1
; GCN-NEXT:    v_accvgpr_read_b32 v2, a2
; GCN-NEXT:    v_accvgpr_read_b32 v3, a3
; GCN-NEXT:    s_setpc_b64 s[30:31]
  %result = call <4 x float> @llvm.amdgcn.mfma.f32.16x16x128.f8f6f4.scaled(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2,
  i32 immarg 0, i32 immarg 0, i32 immarg 0,
  i32 immarg 0, i32 %scale0, i32 immarg 3, i32 %scale1)
  ret <4 x float> %result
}

define <4 x float> @test_mfma_f32_16x16x128_f8f6f4_scaled_3_0(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2, i32 %scale0, i32 %scale1) {
; GCN-LABEL: test_mfma_f32_16x16x128_f8f6f4_scaled_3_0:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_accvgpr_write_b32 a0, v16
; GCN-NEXT:    v_accvgpr_write_b32 a1, v17
; GCN-NEXT:    v_accvgpr_write_b32 a2, v18
; GCN-NEXT:    v_accvgpr_write_b32 a3, v19
; GCN-NEXT:    v_mfma_ld_scale_b32 v20, v21 op_sel:[1,0] op_sel_hi:[1,0]
; GCN-NEXT:    s_nop 0
; GCN-NEXT:    v_mfma_f32_16x16x128_f8f6f4 a[0:3], v[0:7], v[8:15], a[0:3]
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 2
; GCN-NEXT:    v_accvgpr_read_b32 v0, a0
; GCN-NEXT:    v_accvgpr_read_b32 v1, a1
; GCN-NEXT:    v_accvgpr_read_b32 v2, a2
; GCN-NEXT:    v_accvgpr_read_b32 v3, a3
; GCN-NEXT:    s_setpc_b64 s[30:31]
  %result = call <4 x float> @llvm.amdgcn.mfma.f32.16x16x128.f8f6f4.scaled(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2,
  i32 immarg 0, i32 immarg 0, i32 immarg 0,
  i32 immarg 3, i32 %scale0, i32 immarg 0, i32 %scale1)
  ret <4 x float> %result
}

define <4 x float> @test_mfma_f32_16x16x128_f8f6f4_scaled_2_3(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2, i32 %scale0, i32 %scale1) {
; GCN-LABEL: test_mfma_f32_16x16x128_f8f6f4_scaled_2_3:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_accvgpr_write_b32 a0, v16
; GCN-NEXT:    v_accvgpr_write_b32 a1, v17
; GCN-NEXT:    v_accvgpr_write_b32 a2, v18
; GCN-NEXT:    v_accvgpr_write_b32 a3, v19
; GCN-NEXT:    v_mfma_ld_scale_b32 v20, v21 op_sel:[0,1]
; GCN-NEXT:    s_nop 0
; GCN-NEXT:    v_mfma_f32_16x16x128_f8f6f4 a[0:3], v[0:7], v[8:15], a[0:3]
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 2
; GCN-NEXT:    v_accvgpr_read_b32 v0, a0
; GCN-NEXT:    v_accvgpr_read_b32 v1, a1
; GCN-NEXT:    v_accvgpr_read_b32 v2, a2
; GCN-NEXT:    v_accvgpr_read_b32 v3, a3
; GCN-NEXT:    s_setpc_b64 s[30:31]
  %result = call <4 x float> @llvm.amdgcn.mfma.f32.16x16x128.f8f6f4.scaled(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2,
  i32 immarg 0, i32 immarg 0, i32 immarg 0,
  i32 immarg 2, i32 %scale0, i32 immarg 3, i32 %scale1)
  ret <4 x float> %result
}

define <4 x float> @test_mfma_f32_16x16x128_f8f6f4_scaled_3_2(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2, i32 %scale0, i32 %scale1) {
; GCN-LABEL: test_mfma_f32_16x16x128_f8f6f4_scaled_3_2:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_accvgpr_write_b32 a0, v16
; GCN-NEXT:    v_accvgpr_write_b32 a1, v17
; GCN-NEXT:    v_accvgpr_write_b32 a2, v18
; GCN-NEXT:    v_accvgpr_write_b32 a3, v19
; GCN-NEXT:    v_mfma_ld_scale_b32 v20, v21 op_sel:[1,0]
; GCN-NEXT:    s_nop 0
; GCN-NEXT:    v_mfma_f32_16x16x128_f8f6f4 a[0:3], v[0:7], v[8:15], a[0:3]
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 2
; GCN-NEXT:    v_accvgpr_read_b32 v0, a0
; GCN-NEXT:    v_accvgpr_read_b32 v1, a1
; GCN-NEXT:    v_accvgpr_read_b32 v2, a2
; GCN-NEXT:    v_accvgpr_read_b32 v3, a3
; GCN-NEXT:    s_setpc_b64 s[30:31]
  %result = call <4 x float> @llvm.amdgcn.mfma.f32.16x16x128.f8f6f4.scaled(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2,
  i32 immarg 0, i32 immarg 0, i32 immarg 0,
  i32 immarg 3, i32 %scale0, i32 immarg 2, i32 %scale1)
  ret <4 x float> %result
}

define <4 x float> @test_mfma_f32_16x16x128_f8f6f4_scaled_3_0__cbsz3__abid2__blgp1(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2, i32 %scale0, i32 %scale1) {
; GCN-LABEL: test_mfma_f32_16x16x128_f8f6f4_scaled_3_0__cbsz3__abid2__blgp1:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_accvgpr_write_b32 a0, v16
; GCN-NEXT:    v_accvgpr_write_b32 a1, v17
; GCN-NEXT:    v_accvgpr_write_b32 a2, v18
; GCN-NEXT:    v_accvgpr_write_b32 a3, v19
; GCN-NEXT:    v_mfma_ld_scale_b32 v20, v21 op_sel:[1,0] op_sel_hi:[1,0]
; GCN-NEXT:    s_nop 0
; GCN-NEXT:    v_mfma_f32_16x16x128_f8f6f4 a[0:3], v[0:7], v[8:15], a[0:3] cbsz:3 abid:2 blgp:1
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 2
; GCN-NEXT:    v_accvgpr_read_b32 v0, a0
; GCN-NEXT:    v_accvgpr_read_b32 v1, a1
; GCN-NEXT:    v_accvgpr_read_b32 v2, a2
; GCN-NEXT:    v_accvgpr_read_b32 v3, a3
; GCN-NEXT:    s_setpc_b64 s[30:31]
  %result = call <4 x float> @llvm.amdgcn.mfma.f32.16x16x128.f8f6f4.scaled(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2,
  i32 immarg 3, i32 immarg 2, i32 immarg 1,
  i32 immarg 3, i32 %scale0, i32 immarg 0, i32 %scale1)
  ret <4 x float> %result
}

define <4 x float> @test_mfma_f32_16x16x128_f8f6f4_scaled_3_0__cbsz3__abid2__blgp7(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2, i32 %scale0, i32 %scale1) {
; GCN-LABEL: test_mfma_f32_16x16x128_f8f6f4_scaled_3_0__cbsz3__abid2__blgp7:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_accvgpr_write_b32 a0, v16
; GCN-NEXT:    v_accvgpr_write_b32 a1, v17
; GCN-NEXT:    v_accvgpr_write_b32 a2, v18
; GCN-NEXT:    v_accvgpr_write_b32 a3, v19
; GCN-NEXT:    v_mfma_ld_scale_b32 v20, v21 op_sel:[1,0] op_sel_hi:[1,0]
; GCN-NEXT:    s_nop 0
; GCN-NEXT:    v_mfma_f32_16x16x128_f8f6f4 a[0:3], v[0:7], v[8:15], a[0:3] cbsz:3 abid:2 blgp:7
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 2
; GCN-NEXT:    v_accvgpr_read_b32 v0, a0
; GCN-NEXT:    v_accvgpr_read_b32 v1, a1
; GCN-NEXT:    v_accvgpr_read_b32 v2, a2
; GCN-NEXT:    v_accvgpr_read_b32 v3, a3
; GCN-NEXT:    s_setpc_b64 s[30:31]
  %result = call <4 x float> @llvm.amdgcn.mfma.f32.16x16x128.f8f6f4.scaled(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2,
  i32 immarg 3, i32 immarg 2, i32 immarg 7,
  i32 immarg 3, i32 %scale0, i32 immarg 0, i32 %scale1)
  ret <4 x float> %result
}

define <4 x float> @test_mfma_f32_16x16x128_f8f6f4_scaled_3_0__cbsz3__abid3__blgp7(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2, i32 %scale0, i32 %scale1) {
; GCN-LABEL: test_mfma_f32_16x16x128_f8f6f4_scaled_3_0__cbsz3__abid3__blgp7:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_accvgpr_write_b32 a0, v16
; GCN-NEXT:    v_accvgpr_write_b32 a1, v17
; GCN-NEXT:    v_accvgpr_write_b32 a2, v18
; GCN-NEXT:    v_accvgpr_write_b32 a3, v19
; GCN-NEXT:    v_mfma_ld_scale_b32 v20, v21 op_sel:[1,0] op_sel_hi:[1,0]
; GCN-NEXT:    s_nop 0
; GCN-NEXT:    v_mfma_f32_16x16x128_f8f6f4 a[0:3], v[0:7], v[8:15], a[0:3] cbsz:3 abid:3 blgp:7
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 2
; GCN-NEXT:    v_accvgpr_read_b32 v0, a0
; GCN-NEXT:    v_accvgpr_read_b32 v1, a1
; GCN-NEXT:    v_accvgpr_read_b32 v2, a2
; GCN-NEXT:    v_accvgpr_read_b32 v3, a3
; GCN-NEXT:    s_setpc_b64 s[30:31]
  %result = call <4 x float> @llvm.amdgcn.mfma.f32.16x16x128.f8f6f4.scaled(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2,
  i32 immarg 3, i32 immarg 3, i32 immarg 7,
  i32 immarg 3, i32 %scale0, i32 immarg 0, i32 %scale1)
  ret <4 x float> %result
}

define <4 x float> @test_mfma_f32_16x16x128_f8f6f4_scaled_0_0__sgpr_scaleA__sgpr_scaleB(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2, i32 inreg %scale0, i32 inreg %scale1) {
; GCN-LABEL: test_mfma_f32_16x16x128_f8f6f4_scaled_0_0__sgpr_scaleA__sgpr_scaleB:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_accvgpr_write_b32 a0, v16
; GCN-NEXT:    v_accvgpr_write_b32 a1, v17
; GCN-NEXT:    v_accvgpr_write_b32 a2, v18
; GCN-NEXT:    v_accvgpr_write_b32 a3, v19
; GCN-NEXT:    v_mov_b32_e32 v16, s1
; GCN-NEXT:    v_mfma_ld_scale_b32 s0, v16 op_sel_hi:[0,0]
; GCN-NEXT:    v_mfma_f32_16x16x128_f8f6f4 a[0:3], v[0:7], v[8:15], a[0:3]
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 2
; GCN-NEXT:    v_accvgpr_read_b32 v0, a0
; GCN-NEXT:    v_accvgpr_read_b32 v1, a1
; GCN-NEXT:    v_accvgpr_read_b32 v2, a2
; GCN-NEXT:    v_accvgpr_read_b32 v3, a3
; GCN-NEXT:    s_setpc_b64 s[30:31]
  %result = call <4 x float> @llvm.amdgcn.mfma.f32.16x16x128.f8f6f4.scaled(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2,
  i32 immarg 0, i32 immarg 0, i32 immarg 0,
  i32 immarg 0, i32 %scale0, i32 immarg 0, i32 %scale1)
  ret <4 x float> %result
}

define <4 x float> @test_mfma_f32_16x16x128_f8f6f4_scaled_0_0__sgpr_scaleA__vgpr_scaleB(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2, i32 inreg %scale0, i32 %scale1) {
; GCN-LABEL: test_mfma_f32_16x16x128_f8f6f4_scaled_0_0__sgpr_scaleA__vgpr_scaleB:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_accvgpr_write_b32 a0, v16
; GCN-NEXT:    v_accvgpr_write_b32 a1, v17
; GCN-NEXT:    v_accvgpr_write_b32 a2, v18
; GCN-NEXT:    v_accvgpr_write_b32 a3, v19
; GCN-NEXT:    v_mfma_ld_scale_b32 s0, v20 op_sel_hi:[0,0]
; GCN-NEXT:    s_nop 0
; GCN-NEXT:    v_mfma_f32_16x16x128_f8f6f4 a[0:3], v[0:7], v[8:15], a[0:3]
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 2
; GCN-NEXT:    v_accvgpr_read_b32 v0, a0
; GCN-NEXT:    v_accvgpr_read_b32 v1, a1
; GCN-NEXT:    v_accvgpr_read_b32 v2, a2
; GCN-NEXT:    v_accvgpr_read_b32 v3, a3
; GCN-NEXT:    s_setpc_b64 s[30:31]
  %result = call <4 x float> @llvm.amdgcn.mfma.f32.16x16x128.f8f6f4.scaled(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2,
  i32 immarg 0, i32 immarg 0, i32 immarg 0,
  i32 immarg 0, i32 %scale0, i32 immarg 0, i32 %scale1)
  ret <4 x float> %result
}

define <4 x float> @test_mfma_f32_16x16x128_f8f6f4_scaled_0_0__vgpr_scaleA__sgpr_scaleB(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2, i32 %scale0, i32 inreg %scale1) {
; GCN-LABEL: test_mfma_f32_16x16x128_f8f6f4_scaled_0_0__vgpr_scaleA__sgpr_scaleB:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_accvgpr_write_b32 a0, v16
; GCN-NEXT:    v_accvgpr_write_b32 a1, v17
; GCN-NEXT:    v_accvgpr_write_b32 a2, v18
; GCN-NEXT:    v_accvgpr_write_b32 a3, v19
; GCN-NEXT:    v_mfma_ld_scale_b32 v20, s0 op_sel_hi:[0,0]
; GCN-NEXT:    s_nop 0
; GCN-NEXT:    v_mfma_f32_16x16x128_f8f6f4 a[0:3], v[0:7], v[8:15], a[0:3]
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 2
; GCN-NEXT:    v_accvgpr_read_b32 v0, a0
; GCN-NEXT:    v_accvgpr_read_b32 v1, a1
; GCN-NEXT:    v_accvgpr_read_b32 v2, a2
; GCN-NEXT:    v_accvgpr_read_b32 v3, a3
; GCN-NEXT:    s_setpc_b64 s[30:31]
  %result = call <4 x float> @llvm.amdgcn.mfma.f32.16x16x128.f8f6f4.scaled(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2,
  i32 immarg 0, i32 immarg 0, i32 immarg 0,
  i32 immarg 0, i32 %scale0, i32 immarg 0, i32 %scale1)
  ret <4 x float> %result
}


define <4 x float> @test_mfma_f32_16x16x128_f8f6f4_scaled_0_0_sgprs(<8 x i32> inreg %arg0, <8 x i32> inreg %arg1, <4 x float> inreg %arg2, i32 %scale0, i32 %scale1) {
; GCN-LABEL: test_mfma_f32_16x16x128_f8f6f4_scaled_0_0_sgprs:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_accvgpr_write_b32 a0, s16
; GCN-NEXT:    v_accvgpr_write_b32 a1, s17
; GCN-NEXT:    v_accvgpr_write_b32 a2, s18
; GCN-NEXT:    v_accvgpr_write_b32 a3, s19
; GCN-NEXT:    v_mov_b32_e32 v2, s8
; GCN-NEXT:    v_mov_b32_e32 v3, s9
; GCN-NEXT:    v_mov_b32_e32 v4, s10
; GCN-NEXT:    v_mov_b32_e32 v5, s11
; GCN-NEXT:    v_mov_b32_e32 v6, s12
; GCN-NEXT:    v_mov_b32_e32 v7, s13
; GCN-NEXT:    v_mov_b32_e32 v8, s14
; GCN-NEXT:    v_mov_b32_e32 v9, s15
; GCN-NEXT:    v_mov_b32_e32 v10, s0
; GCN-NEXT:    v_mov_b32_e32 v11, s1
; GCN-NEXT:    v_mov_b32_e32 v12, s2
; GCN-NEXT:    v_mov_b32_e32 v13, s3
; GCN-NEXT:    v_mov_b32_e32 v14, s4
; GCN-NEXT:    v_mov_b32_e32 v15, s5
; GCN-NEXT:    v_mov_b32_e32 v16, s6
; GCN-NEXT:    v_mov_b32_e32 v17, s7
; GCN-NEXT:    v_mfma_ld_scale_b32 v0, v1 op_sel_hi:[0,0]
; GCN-NEXT:    s_nop 0
; GCN-NEXT:    v_mfma_f32_16x16x128_f8f6f4 a[0:3], v[10:17], v[2:9], a[0:3]
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 2
; GCN-NEXT:    v_accvgpr_read_b32 v0, a0
; GCN-NEXT:    v_accvgpr_read_b32 v1, a1
; GCN-NEXT:    v_accvgpr_read_b32 v2, a2
; GCN-NEXT:    v_accvgpr_read_b32 v3, a3
; GCN-NEXT:    s_setpc_b64 s[30:31]
  %result = call <4 x float> @llvm.amdgcn.mfma.f32.16x16x128.f8f6f4.scaled(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2,
  i32 immarg 0, i32 immarg 0, i32 immarg 0,
  i32 immarg 0, i32 %scale0, i32 immarg 0, i32 %scale1)
  ret <4 x float> %result
}

define <4 x float> @test_mfma_f32_16x16x128_f8f6f4_scaled_0_0_sgpr_vgpr_vgpr__sgpr_vgpr(<8 x i32> inreg %arg0, <8 x i32> %arg1, <4 x float> %arg2, i32 inreg %scale0, i32 %scale1) {
; GCN-LABEL: test_mfma_f32_16x16x128_f8f6f4_scaled_0_0_sgpr_vgpr_vgpr__sgpr_vgpr:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_accvgpr_write_b32 a0, v8
; GCN-NEXT:    v_accvgpr_write_b32 a1, v9
; GCN-NEXT:    v_accvgpr_write_b32 a2, v10
; GCN-NEXT:    v_accvgpr_write_b32 a3, v11
; GCN-NEXT:    v_mov_b32_e32 v14, s0
; GCN-NEXT:    v_mov_b32_e32 v15, s1
; GCN-NEXT:    v_mov_b32_e32 v16, s2
; GCN-NEXT:    v_mov_b32_e32 v17, s3
; GCN-NEXT:    v_mov_b32_e32 v18, s4
; GCN-NEXT:    v_mov_b32_e32 v19, s5
; GCN-NEXT:    v_mov_b32_e32 v20, s6
; GCN-NEXT:    v_mov_b32_e32 v21, s7
; GCN-NEXT:    v_mfma_ld_scale_b32 s8, v12 op_sel_hi:[0,0]
; GCN-NEXT:    s_nop 0
; GCN-NEXT:    v_mfma_f32_16x16x128_f8f6f4 a[0:3], v[14:21], v[0:7], a[0:3]
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 2
; GCN-NEXT:    v_accvgpr_read_b32 v0, a0
; GCN-NEXT:    v_accvgpr_read_b32 v1, a1
; GCN-NEXT:    v_accvgpr_read_b32 v2, a2
; GCN-NEXT:    v_accvgpr_read_b32 v3, a3
; GCN-NEXT:    s_setpc_b64 s[30:31]
  %result = call <4 x float> @llvm.amdgcn.mfma.f32.16x16x128.f8f6f4.scaled(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2,
  i32 immarg 0, i32 immarg 0, i32 immarg 0,
  i32 immarg 0, i32 %scale0, i32 immarg 0, i32 %scale1)
  ret <4 x float> %result
}

define <4 x float> @test_mfma_f32_16x16x128_f8f6f4_scaled_0_0_sgpr_vgpr_vgpr__vgpr_sgpr(<8 x i32> inreg %arg0, <8 x i32> %arg1, <4 x float> %arg2, i32 %scale0, i32 inreg %scale1) {
; GCN-LABEL: test_mfma_f32_16x16x128_f8f6f4_scaled_0_0_sgpr_vgpr_vgpr__vgpr_sgpr:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_accvgpr_write_b32 a0, v8
; GCN-NEXT:    v_accvgpr_write_b32 a1, v9
; GCN-NEXT:    v_accvgpr_write_b32 a2, v10
; GCN-NEXT:    v_accvgpr_write_b32 a3, v11
; GCN-NEXT:    v_mov_b32_e32 v14, s0
; GCN-NEXT:    v_mov_b32_e32 v15, s1
; GCN-NEXT:    v_mov_b32_e32 v16, s2
; GCN-NEXT:    v_mov_b32_e32 v17, s3
; GCN-NEXT:    v_mov_b32_e32 v18, s4
; GCN-NEXT:    v_mov_b32_e32 v19, s5
; GCN-NEXT:    v_mov_b32_e32 v20, s6
; GCN-NEXT:    v_mov_b32_e32 v21, s7
; GCN-NEXT:    v_mfma_ld_scale_b32 v12, s8 op_sel_hi:[0,0]
; GCN-NEXT:    s_nop 0
; GCN-NEXT:    v_mfma_f32_16x16x128_f8f6f4 a[0:3], v[14:21], v[0:7], a[0:3]
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 2
; GCN-NEXT:    v_accvgpr_read_b32 v0, a0
; GCN-NEXT:    v_accvgpr_read_b32 v1, a1
; GCN-NEXT:    v_accvgpr_read_b32 v2, a2
; GCN-NEXT:    v_accvgpr_read_b32 v3, a3
; GCN-NEXT:    s_setpc_b64 s[30:31]
  %result = call <4 x float> @llvm.amdgcn.mfma.f32.16x16x128.f8f6f4.scaled(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2,
  i32 immarg 0, i32 immarg 0, i32 immarg 0,
  i32 immarg 0, i32 %scale0, i32 immarg 0, i32 %scale1)
  ret <4 x float> %result
}

define <4 x float> @test_mfma_f32_16x16x128_f8f6f4_scaled_0_0_vgpr_sgpr_vgpr__vgpr_sgpr(<8 x i32> %arg0, <8 x i32> inreg %arg1, <4 x float> %arg2, i32 %scale0, i32 inreg %scale1) {
; GCN-LABEL: test_mfma_f32_16x16x128_f8f6f4_scaled_0_0_vgpr_sgpr_vgpr__vgpr_sgpr:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_accvgpr_write_b32 a0, v8
; GCN-NEXT:    v_accvgpr_write_b32 a1, v9
; GCN-NEXT:    v_accvgpr_write_b32 a2, v10
; GCN-NEXT:    v_accvgpr_write_b32 a3, v11
; GCN-NEXT:    v_mov_b32_e32 v14, s0
; GCN-NEXT:    v_mov_b32_e32 v15, s1
; GCN-NEXT:    v_mov_b32_e32 v16, s2
; GCN-NEXT:    v_mov_b32_e32 v17, s3
; GCN-NEXT:    v_mov_b32_e32 v18, s4
; GCN-NEXT:    v_mov_b32_e32 v19, s5
; GCN-NEXT:    v_mov_b32_e32 v20, s6
; GCN-NEXT:    v_mov_b32_e32 v21, s7
; GCN-NEXT:    v_mfma_ld_scale_b32 v12, s8 op_sel_hi:[0,0]
; GCN-NEXT:    s_nop 0
; GCN-NEXT:    v_mfma_f32_16x16x128_f8f6f4 a[0:3], v[0:7], v[14:21], a[0:3]
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 2
; GCN-NEXT:    v_accvgpr_read_b32 v0, a0
; GCN-NEXT:    v_accvgpr_read_b32 v1, a1
; GCN-NEXT:    v_accvgpr_read_b32 v2, a2
; GCN-NEXT:    v_accvgpr_read_b32 v3, a3
; GCN-NEXT:    s_setpc_b64 s[30:31]
  %result = call <4 x float> @llvm.amdgcn.mfma.f32.16x16x128.f8f6f4.scaled(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2,
  i32 immarg 0, i32 immarg 0, i32 immarg 0,
  i32 immarg 0, i32 %scale0, i32 immarg 0, i32 %scale1)
  ret <4 x float> %result
}

define <4 x float> @test_mfma_f32_16x16x128_f8f6f4_scaled_0_0_vgpr_vgpr_sgpr__vgpr_sgpr(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> inreg %arg2, i32 %scale0, i32 inreg %scale1) {
; GCN-LABEL: test_mfma_f32_16x16x128_f8f6f4_scaled_0_0_vgpr_vgpr_sgpr__vgpr_sgpr:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_accvgpr_write_b32 a0, s0
; GCN-NEXT:    v_accvgpr_write_b32 a1, s1
; GCN-NEXT:    v_accvgpr_write_b32 a2, s2
; GCN-NEXT:    v_accvgpr_write_b32 a3, s3
; GCN-NEXT:    v_mfma_ld_scale_b32 v16, s4 op_sel_hi:[0,0]
; GCN-NEXT:    s_nop 0
; GCN-NEXT:    v_mfma_f32_16x16x128_f8f6f4 a[0:3], v[0:7], v[8:15], a[0:3]
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 2
; GCN-NEXT:    v_accvgpr_read_b32 v0, a0
; GCN-NEXT:    v_accvgpr_read_b32 v1, a1
; GCN-NEXT:    v_accvgpr_read_b32 v2, a2
; GCN-NEXT:    v_accvgpr_read_b32 v3, a3
; GCN-NEXT:    s_setpc_b64 s[30:31]
  %result = call <4 x float> @llvm.amdgcn.mfma.f32.16x16x128.f8f6f4.scaled(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2,
  i32 immarg 0, i32 immarg 0, i32 immarg 0,
  i32 immarg 0, i32 %scale0, i32 immarg 0, i32 %scale1)
  ret <4 x float> %result
}

define <4 x float> @test_mfma_f32_16x16x128_f8f6f4_scaled_0_0_sgpr_vgpr_sgpr__vgpr_sgpr(<8 x i32> inreg %arg0, <8 x i32> %arg1, <4 x float> inreg %arg2, i32 %scale0, i32 inreg %scale1) {
; GCN-LABEL: test_mfma_f32_16x16x128_f8f6f4_scaled_0_0_sgpr_vgpr_sgpr__vgpr_sgpr:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_accvgpr_write_b32 a0, s8
; GCN-NEXT:    v_accvgpr_write_b32 a1, s9
; GCN-NEXT:    v_accvgpr_write_b32 a2, s10
; GCN-NEXT:    v_accvgpr_write_b32 a3, s11
; GCN-NEXT:    v_mov_b32_e32 v10, s0
; GCN-NEXT:    v_mov_b32_e32 v11, s1
; GCN-NEXT:    v_mov_b32_e32 v12, s2
; GCN-NEXT:    v_mov_b32_e32 v13, s3
; GCN-NEXT:    v_mov_b32_e32 v14, s4
; GCN-NEXT:    v_mov_b32_e32 v15, s5
; GCN-NEXT:    v_mov_b32_e32 v16, s6
; GCN-NEXT:    v_mov_b32_e32 v17, s7
; GCN-NEXT:    v_mfma_ld_scale_b32 v8, s12 op_sel_hi:[0,0]
; GCN-NEXT:    s_nop 0
; GCN-NEXT:    v_mfma_f32_16x16x128_f8f6f4 a[0:3], v[10:17], v[0:7], a[0:3]
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 2
; GCN-NEXT:    v_accvgpr_read_b32 v0, a0
; GCN-NEXT:    v_accvgpr_read_b32 v1, a1
; GCN-NEXT:    v_accvgpr_read_b32 v2, a2
; GCN-NEXT:    v_accvgpr_read_b32 v3, a3
; GCN-NEXT:    s_setpc_b64 s[30:31]
  %result = call <4 x float> @llvm.amdgcn.mfma.f32.16x16x128.f8f6f4.scaled(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2,
  i32 immarg 0, i32 immarg 0, i32 immarg 0,
  i32 immarg 0, i32 %scale0, i32 immarg 0, i32 %scale1)
  ret <4 x float> %result
}

define <4 x float> @test_mfma_f32_16x16x128_f8f6f4_scaled_0_0__scaleA_inlineimm__scaleB_inlineimm(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2, i32 %scale0, i32 %scale1) {
; GCN-LABEL: test_mfma_f32_16x16x128_f8f6f4_scaled_0_0__scaleA_inlineimm__scaleB_inlineimm:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_accvgpr_write_b32 a0, v16
; GCN-NEXT:    v_accvgpr_write_b32 a1, v17
; GCN-NEXT:    v_accvgpr_write_b32 a2, v18
; GCN-NEXT:    v_accvgpr_write_b32 a3, v19
; GCN-NEXT:    v_mov_b32_e32 v16, 0xffffffe8
; GCN-NEXT:    v_mfma_ld_scale_b32 33, v16
; GCN-NEXT:    v_mfma_f32_16x16x128_f8f6f4 a[0:3], v[0:7], v[8:15], a[0:3]
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 2
; GCN-NEXT:    v_accvgpr_read_b32 v0, a0
; GCN-NEXT:    v_accvgpr_read_b32 v1, a1
; GCN-NEXT:    v_accvgpr_read_b32 v2, a2
; GCN-NEXT:    v_accvgpr_read_b32 v3, a3
; GCN-NEXT:    s_setpc_b64 s[30:31]
  %result = call <4 x float> @llvm.amdgcn.mfma.f32.16x16x128.f8f6f4.scaled(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2,
  i32 immarg 0, i32 immarg 0, i32 immarg 0,
  i32 immarg 2, i32 33, i32 immarg 2, i32 -24)
  ret <4 x float> %result
}

define <4 x float> @test_mfma_f32_16x16x128_f8f6f4_scaled_0_0__scaleA_kimm__scaleB_inlineimm(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2, i32 %scale0, i32 %scale1) {
; GCN-LABEL: test_mfma_f32_16x16x128_f8f6f4_scaled_0_0__scaleA_kimm__scaleB_inlineimm:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_accvgpr_write_b32 a0, v16
; GCN-NEXT:    s_movk_i32 s0, 0x41
; GCN-NEXT:    v_accvgpr_write_b32 a1, v17
; GCN-NEXT:    v_accvgpr_write_b32 a2, v18
; GCN-NEXT:    v_accvgpr_write_b32 a3, v19
; GCN-NEXT:    v_mov_b32_e32 v16, 0xffffffe8
; GCN-NEXT:    v_mfma_ld_scale_b32 s0, v16
; GCN-NEXT:    v_mfma_f32_16x16x128_f8f6f4 a[0:3], v[0:7], v[8:15], a[0:3]
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 2
; GCN-NEXT:    v_accvgpr_read_b32 v0, a0
; GCN-NEXT:    v_accvgpr_read_b32 v1, a1
; GCN-NEXT:    v_accvgpr_read_b32 v2, a2
; GCN-NEXT:    v_accvgpr_read_b32 v3, a3
; GCN-NEXT:    s_setpc_b64 s[30:31]
  %result = call <4 x float> @llvm.amdgcn.mfma.f32.16x16x128.f8f6f4.scaled(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2,
  i32 immarg 0, i32 immarg 0, i32 immarg 0,
  i32 immarg 2, i32 65, i32 immarg 2, i32 -24)
  ret <4 x float> %result
}

define <4 x float> @test_mfma_f32_16x16x128_f8f6f4_scaled_0_0__scaleA_kimm__scaleB_kimm(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2, i32 %scale0, i32 %scale1) {
; GCN-LABEL: test_mfma_f32_16x16x128_f8f6f4_scaled_0_0__scaleA_kimm__scaleB_kimm:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    v_accvgpr_write_b32 a0, v16
; GCN-NEXT:    s_movk_i32 s0, 0x41
; GCN-NEXT:    v_accvgpr_write_b32 a1, v17
; GCN-NEXT:    v_accvgpr_write_b32 a2, v18
; GCN-NEXT:    v_accvgpr_write_b32 a3, v19
; GCN-NEXT:    v_mov_b32_e32 v16, 0x4d
; GCN-NEXT:    v_mfma_ld_scale_b32 s0, v16
; GCN-NEXT:    v_mfma_f32_16x16x128_f8f6f4 a[0:3], v[0:7], v[8:15], a[0:3]
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 2
; GCN-NEXT:    v_accvgpr_read_b32 v0, a0
; GCN-NEXT:    v_accvgpr_read_b32 v1, a1
; GCN-NEXT:    v_accvgpr_read_b32 v2, a2
; GCN-NEXT:    v_accvgpr_read_b32 v3, a3
; GCN-NEXT:    s_setpc_b64 s[30:31]
  %result = call <4 x float> @llvm.amdgcn.mfma.f32.16x16x128.f8f6f4.scaled(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2,
  i32 immarg 0, i32 immarg 0, i32 immarg 0,
  i32 immarg 2, i32 65, i32 immarg 2, i32 77)
  ret <4 x float> %result
}

define amdgpu_kernel void @test_mfma_f32_16x16x128_f8f6f4__vgprcd(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2, i32 %scale0, i32 %scale1, ptr addrspace(1) %ptr) #0 {
; GCN-LABEL: test_mfma_f32_16x16x128_f8f6f4__vgprcd:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_load_dwordx16 s[4:19], s[0:1], 0x24
; GCN-NEXT:    v_mov_b32_e32 v20, 0
; GCN-NEXT:    s_waitcnt lgkmcnt(0)
; GCN-NEXT:    v_mov_b32_e32 v0, s4
; GCN-NEXT:    v_mov_b32_e32 v1, s5
; GCN-NEXT:    v_mov_b32_e32 v2, s6
; GCN-NEXT:    v_mov_b32_e32 v3, s7
; GCN-NEXT:    s_load_dwordx8 s[0:7], s[0:1], 0x64
; GCN-NEXT:    v_mov_b32_e32 v4, s8
; GCN-NEXT:    v_mov_b32_e32 v5, s9
; GCN-NEXT:    v_mov_b32_e32 v6, s10
; GCN-NEXT:    v_mov_b32_e32 v7, s11
; GCN-NEXT:    s_waitcnt lgkmcnt(0)
; GCN-NEXT:    v_mov_b32_e32 v21, s5
; GCN-NEXT:    v_mov_b32_e32 v8, s12
; GCN-NEXT:    v_mov_b32_e32 v9, s13
; GCN-NEXT:    v_mov_b32_e32 v10, s14
; GCN-NEXT:    v_mov_b32_e32 v11, s15
; GCN-NEXT:    v_mov_b32_e32 v12, s16
; GCN-NEXT:    v_mov_b32_e32 v13, s17
; GCN-NEXT:    v_mov_b32_e32 v14, s18
; GCN-NEXT:    v_mov_b32_e32 v15, s19
; GCN-NEXT:    v_mov_b32_e32 v16, s0
; GCN-NEXT:    v_mov_b32_e32 v17, s1
; GCN-NEXT:    v_mov_b32_e32 v18, s2
; GCN-NEXT:    v_mov_b32_e32 v19, s3
; GCN-NEXT:    v_mfma_ld_scale_b32 s4, v21 op_sel:[1,1] op_sel_hi:[1,0]
; GCN-NEXT:    s_nop 0
; GCN-NEXT:    v_mfma_f32_16x16x128_f8f6f4 v[0:3], v[0:7], v[8:15], v[16:19] cbsz:3 abid:2 blgp:1
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 2
; GCN-NEXT:    global_store_dwordx4 v20, v[0:3], s[6:7]
; GCN-NEXT:    s_endpgm
  %result = call <4 x float> @llvm.amdgcn.mfma.f32.16x16x128.f8f6f4.scaled(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2,
  i32 immarg 3, i32 immarg 2, i32 immarg 1,
  i32 immarg 3, i32 %scale0, i32 immarg 1, i32 %scale1)
  store <4 x float> %result, ptr addrspace(1) %ptr
  ret void
}

define amdgpu_kernel void @test_mfma_f32_16x16x128_f8f6f4__vgprcd___scaleA_kimm__scaleB__inlineimm(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2, ptr addrspace(1) %ptr) #0 {
; GCN-LABEL: test_mfma_f32_16x16x128_f8f6f4__vgprcd___scaleA_kimm__scaleB__inlineimm:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_load_dwordx16 s[4:19], s[0:1], 0x24
; GCN-NEXT:    s_movk_i32 s2, 0x41
; GCN-NEXT:    v_mov_b32_e32 v21, 0xffffffe8
; GCN-NEXT:    v_mov_b32_e32 v20, 0
; GCN-NEXT:    s_waitcnt lgkmcnt(0)
; GCN-NEXT:    v_mov_b32_e32 v0, s4
; GCN-NEXT:    v_mov_b32_e32 v1, s5
; GCN-NEXT:    v_mov_b32_e32 v2, s6
; GCN-NEXT:    v_mov_b32_e32 v3, s7
; GCN-NEXT:    s_load_dwordx4 s[4:7], s[0:1], 0x64
; GCN-NEXT:    v_mov_b32_e32 v4, s8
; GCN-NEXT:    s_load_dwordx2 s[0:1], s[0:1], 0x74
; GCN-NEXT:    v_mov_b32_e32 v5, s9
; GCN-NEXT:    v_mov_b32_e32 v6, s10
; GCN-NEXT:    s_waitcnt lgkmcnt(0)
; GCN-NEXT:    v_mov_b64_e32 v[18:19], s[6:7]
; GCN-NEXT:    v_mov_b32_e32 v7, s11
; GCN-NEXT:    v_mov_b32_e32 v8, s12
; GCN-NEXT:    v_mov_b32_e32 v9, s13
; GCN-NEXT:    v_mov_b32_e32 v10, s14
; GCN-NEXT:    v_mov_b32_e32 v11, s15
; GCN-NEXT:    v_mov_b32_e32 v12, s16
; GCN-NEXT:    v_mov_b32_e32 v13, s17
; GCN-NEXT:    v_mov_b32_e32 v14, s18
; GCN-NEXT:    v_mov_b32_e32 v15, s19
; GCN-NEXT:    v_mov_b64_e32 v[16:17], s[4:5]
; GCN-NEXT:    v_mfma_ld_scale_b32 s2, v21 op_sel:[1,1] op_sel_hi:[1,0]
; GCN-NEXT:    s_nop 0
; GCN-NEXT:    v_mfma_f32_16x16x128_f8f6f4 v[0:3], v[0:7], v[8:15], v[16:19] cbsz:3 abid:2 blgp:1
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 2
; GCN-NEXT:    global_store_dwordx4 v20, v[0:3], s[0:1]
; GCN-NEXT:    s_endpgm
  %result = call <4 x float> @llvm.amdgcn.mfma.f32.16x16x128.f8f6f4.scaled(<8 x i32> %arg0, <8 x i32> %arg1, <4 x float> %arg2,
  i32 immarg 3, i32 immarg 2, i32 immarg 1,
  i32 immarg 3, i32 65, i32 immarg 1, i32 -24)
  store <4 x float> %result, ptr addrspace(1) %ptr
  ret void
}

attributes #0 = { "amdgpu-flat-work-group-size"="512,512" }
