; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -march=amdgcn -mcpu=gfx1211 -verify-machineinstrs < %s | FileCheck %s --check-prefix=GFX1211
; RUN: llc -march=amdgcn -mcpu=gfx1211 -global-isel -verify-machineinstrs < %s | FileCheck %s --check-prefix=GISEL

define amdgpu_ps void @test_wmma_f64_16x16x4_f64(<2 x double> %A, <2 x double> %B, <8 x double> %C, ptr addrspace(1) %out) {
; GFX1211-LABEL: test_wmma_f64_16x16x4_f64:
; GFX1211:       ; %bb.0: ; %bb
; GFX1211-NEXT:    v_wmma_f64_16x16x4_f64 v[8:23], v[0:3], v[4:7], v[8:23]
; GFX1211-NEXT:    s_clause 0x3
; GFX1211-NEXT:    global_store_b128 v[24:25], v[20:23], off offset:48
; GFX1211-NEXT:    global_store_b128 v[24:25], v[16:19], off offset:32
; GFX1211-NEXT:    global_store_b128 v[24:25], v[12:15], off offset:16
; GFX1211-NEXT:    global_store_b128 v[24:25], v[8:11], off
; GFX1211-NEXT:    s_endpgm
;
; GISEL-LABEL: test_wmma_f64_16x16x4_f64:
; GISEL:       ; %bb.0: ; %bb
; GISEL-NEXT:    v_wmma_f64_16x16x4_f64 v[8:23], v[0:3], v[4:7], v[8:23]
; GISEL-NEXT:    s_clause 0x3
; GISEL-NEXT:    global_store_b128 v[24:25], v[8:11], off
; GISEL-NEXT:    global_store_b128 v[24:25], v[12:15], off offset:16
; GISEL-NEXT:    global_store_b128 v[24:25], v[16:19], off offset:32
; GISEL-NEXT:    global_store_b128 v[24:25], v[20:23], off offset:48
; GISEL-NEXT:    s_endpgm
bb:
  %res = call <8 x double> @llvm.amdgcn.wmma.f64.16x16x4.f64.v8f64.v2f64(i1 0, <2 x double> %A, i1 0, <2 x double> %B, i16 0, <8 x double> %C)
  store <8 x double> %res, ptr addrspace(1) %out
  ret void
}

define amdgpu_ps void @test_wmma_f64_16x16x8_f64(<4 x double> %A, <4 x double> %B, <8 x double> %C, ptr addrspace(1) %out) {
; GFX1211-LABEL: test_wmma_f64_16x16x8_f64:
; GFX1211:       ; %bb.0: ; %bb
; GFX1211-NEXT:    v_wmma_f64_16x16x8_f64 v[16:31], v[0:7], v[8:15], v[16:31]
; GFX1211-NEXT:    s_clause 0x3
; GFX1211-NEXT:    global_store_b128 v[32:33], v[28:31], off offset:48
; GFX1211-NEXT:    global_store_b128 v[32:33], v[24:27], off offset:32
; GFX1211-NEXT:    global_store_b128 v[32:33], v[20:23], off offset:16
; GFX1211-NEXT:    global_store_b128 v[32:33], v[16:19], off
; GFX1211-NEXT:    s_endpgm
;
; GISEL-LABEL: test_wmma_f64_16x16x8_f64:
; GISEL:       ; %bb.0: ; %bb
; GISEL-NEXT:    v_wmma_f64_16x16x8_f64 v[16:31], v[0:7], v[8:15], v[16:31]
; GISEL-NEXT:    s_clause 0x3
; GISEL-NEXT:    global_store_b128 v[32:33], v[16:19], off
; GISEL-NEXT:    global_store_b128 v[32:33], v[20:23], off offset:16
; GISEL-NEXT:    global_store_b128 v[32:33], v[24:27], off offset:32
; GISEL-NEXT:    global_store_b128 v[32:33], v[28:31], off offset:48
; GISEL-NEXT:    s_endpgm
bb:
  %res = call <8 x double> @llvm.amdgcn.wmma.f64.16x16x8.f64.v8f64.v4f64(i1 0, <4 x double> %A, i1 0, <4 x double> %B, i16 0, <8 x double> %C)
  store <8 x double> %res, ptr addrspace(1) %out
  ret void
}

define amdgpu_ps void @test_wmma_f32_16x16x32_f16(<16 x half> %A, <16 x half> %B, <8 x float> %C, ptr addrspace(1) %out) {
; GFX1211-LABEL: test_wmma_f32_16x16x32_f16:
; GFX1211:       ; %bb.0: ; %bb
; GFX1211-NEXT:    v_wmma_f32_16x16x32_f16 v[16:23], v[0:7], v[8:15], v[16:23]
; GFX1211-NEXT:    s_clause 0x1
; GFX1211-NEXT:    global_store_b128 v[24:25], v[20:23], off offset:16
; GFX1211-NEXT:    global_store_b128 v[24:25], v[16:19], off
; GFX1211-NEXT:    s_endpgm
;
; GISEL-LABEL: test_wmma_f32_16x16x32_f16:
; GISEL:       ; %bb.0: ; %bb
; GISEL-NEXT:    v_wmma_f32_16x16x32_f16 v[16:23], v[0:7], v[8:15], v[16:23]
; GISEL-NEXT:    s_clause 0x1
; GISEL-NEXT:    global_store_b128 v[24:25], v[16:19], off
; GISEL-NEXT:    global_store_b128 v[24:25], v[20:23], off offset:16
; GISEL-NEXT:    s_endpgm
bb:
  %res = call <8 x float> @llvm.amdgcn.wmma.f32.16x16x32.f16.v8f32.v16f16(i1 0, <16 x half> %A, i1 0, <16 x half> %B, i16 0, <8 x float> %C)
  store <8 x float> %res, ptr addrspace(1) %out
  ret void
}

define amdgpu_ps void @test_wmma_f16_16x16x32_f16(<16 x half> %A, <16 x half> %B, <8 x half> %C, ptr addrspace(1) %out) {
; GFX1211-LABEL: test_wmma_f16_16x16x32_f16:
; GFX1211:       ; %bb.0: ; %bb
; GFX1211-NEXT:    v_wmma_f16_16x16x32_f16 v[16:19], v[0:7], v[8:15], v[16:19]
; GFX1211-NEXT:    global_store_b128 v[20:21], v[16:19], off
; GFX1211-NEXT:    s_endpgm
;
; GISEL-LABEL: test_wmma_f16_16x16x32_f16:
; GISEL:       ; %bb.0: ; %bb
; GISEL-NEXT:    v_wmma_f16_16x16x32_f16 v[16:19], v[0:7], v[8:15], v[16:19]
; GISEL-NEXT:    global_store_b128 v[20:21], v[16:19], off
; GISEL-NEXT:    s_endpgm
bb:
  %res = call <8 x half> @llvm.amdgcn.wmma.f16.16x16x32.f16.v8f16.v16f16(i1 0, <16 x half> %A, i1 0, <16 x half> %B, i16 0, <8 x half> %C)
  store <8 x half> %res, ptr addrspace(1) %out
  ret void
}

define amdgpu_ps void @test_swmmac_f32_16x16x64_f16(<16 x half> %A, <32 x half> %B, <8 x float> %C, i16 %Index, ptr addrspace(1) %out) {
; GFX1211-LABEL: test_swmmac_f32_16x16x64_f16:
; GFX1211:       ; %bb.0: ; %bb
; GFX1211-NEXT:    v_swmmac_f32_16x16x64_f16 v[24:31], v[0:7], v[8:23], v32
; GFX1211-NEXT:    v_dual_mov_b32 v35, v34 :: v_dual_mov_b32 v34, v33
; GFX1211-NEXT:    s_clause 0x1
; GFX1211-NEXT:    global_store_b128 v[34:35], v[28:31], off offset:16
; GFX1211-NEXT:    global_store_b128 v[34:35], v[24:27], off
; GFX1211-NEXT:    s_endpgm
;
; GISEL-LABEL: test_swmmac_f32_16x16x64_f16:
; GISEL:       ; %bb.0: ; %bb
; GISEL-NEXT:    v_swmmac_f32_16x16x64_f16 v[24:31], v[0:7], v[8:23], v32
; GISEL-NEXT:    v_dual_mov_b32 v36, v33 :: v_dual_mov_b32 v37, v34
; GISEL-NEXT:    s_clause 0x1
; GISEL-NEXT:    global_store_b128 v[36:37], v[24:27], off
; GISEL-NEXT:    global_store_b128 v[36:37], v[28:31], off offset:16
; GISEL-NEXT:    s_endpgm
bb:
  %res = call <8 x float> @llvm.amdgcn.swmmac.f32.16x16x64.f16.v8f32.v16f16.v32f16.i16(i1 0, <16 x half> %A, i1 0, <32 x half> %B, <8 x float> %C, i16 %Index)
  store <8 x float> %res, ptr addrspace(1) %out
  ret void
}

define amdgpu_ps void @test_swmmac_f16_16x16x64_f16(<16 x half> %A, <32 x half> %B, <8 x half> %C, i16 %Index, ptr addrspace(1) %out) {
; GFX1211-LABEL: test_swmmac_f16_16x16x64_f16:
; GFX1211:       ; %bb.0: ; %bb
; GFX1211-NEXT:    v_swmmac_f16_16x16x64_f16 v[24:27], v[0:7], v[8:23], v28
; GFX1211-NEXT:    v_dual_mov_b32 v31, v30 :: v_dual_mov_b32 v30, v29
; GFX1211-NEXT:    global_store_b128 v[30:31], v[24:27], off
; GFX1211-NEXT:    s_endpgm
;
; GISEL-LABEL: test_swmmac_f16_16x16x64_f16:
; GISEL:       ; %bb.0: ; %bb
; GISEL-NEXT:    v_swmmac_f16_16x16x64_f16 v[24:27], v[0:7], v[8:23], v28
; GISEL-NEXT:    v_dual_mov_b32 v32, v29 :: v_dual_mov_b32 v33, v30
; GISEL-NEXT:    global_store_b128 v[32:33], v[24:27], off
; GISEL-NEXT:    s_endpgm
bb:
  %res = call <8 x half> @llvm.amdgcn.swmmac.f16.16x16x64.f16.v8f16.v16f16.v32f16.i16(i1 0, <16 x half> %A, i1 0, <32 x half> %B, <8 x half> %C, i16 %Index)
  store <8 x half> %res, ptr addrspace(1) %out
  ret void
}

declare <8 x double> @llvm.amdgcn.wmma.f64.16x16x4.f64.v8f64.v2f64(i1, <2 x double>, i1, <2 x double>, i16, <8 x double>)
declare <8 x double> @llvm.amdgcn.wmma.f64.16x16x8.f64.v8f64.v4f64(i1, <4 x double>, i1, <4 x double>, i16, <8 x double>)
declare <8 x float> @llvm.amdgcn.wmma.f32.16x16x32.f16.v8f32.v16f16(i1, <16 x half>, i1, <16 x half>, i16, <8 x float>)
declare <8 x half> @llvm.amdgcn.wmma.f16.16x16x32.f16.v8f16.v16f16(i1, <16 x half>, i1, <16 x half>, i16, <8 x half>)

declare <8 x float> @llvm.amdgcn.swmmac.f32.16x16x64.f16.v8f32.v16f16.v32f16.i16(i1, <16 x half>, i1, <32 x half>, <8 x float>, i16)
declare <8 x half> @llvm.amdgcn.swmmac.f16.16x16x64.f16.v8f16.v16f16.v32f16.i16(i1, <16 x half>, i1, <32 x half>, <8 x half>, i16)
