; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
;RUN: llc < %s -mtriple=amdgcn -mcpu=gfx1300 -verify-machineinstrs | FileCheck -check-prefix=GFX13 %s
;RUN: llc < %s -global-isel -mtriple=amdgcn -mcpu=gfx1300 -verify-machineinstrs | FileCheck -check-prefix=GFX13 %s

define amdgpu_kernel void @tbuffer_store_d16_x(i32 inreg %rsrc, half %data) {
; GFX13-LABEL: tbuffer_store_d16_x:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    s_load_b64 s[0:1], s[4:5], 0x24
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    v_mov_b32_e32 v0, s1
; GFX13-NEXT:    tbuffer_store_d16_format_x v0, off, s0, null format:[BUF_FMT_10_10_10_2_SNORM]
; GFX13-NEXT:    s_endpgm
main_body:
  call void @llvm.amdgcn.raw.tbuffer.store.f16(half %data, i32 %rsrc, i32 0, i32 0, i32 33, i32 0)
  ret void
}

define amdgpu_kernel void @tbuffer_store_d16_xy(i32 inreg %rsrc, <2 x half> %data) {
; GFX13-LABEL: tbuffer_store_d16_xy:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    s_load_b64 s[0:1], s[4:5], 0x24
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    v_mov_b32_e32 v0, s1
; GFX13-NEXT:    tbuffer_store_d16_format_xy v0, off, s0, null format:[BUF_FMT_10_10_10_2_SNORM]
; GFX13-NEXT:    s_endpgm
main_body:
  call void @llvm.amdgcn.raw.tbuffer.store.v2f16(<2 x half> %data, i32 %rsrc, i32 0, i32 0, i32 33, i32 0)
  ret void
}

define amdgpu_kernel void @tbuffer_store_d16_xyz(i32 inreg %rsrc, <4 x half> %data) {
main_body:
  %data_subvec = shufflevector <4 x half> %data, <4 x half> undef, <3 x i32> <i32 0, i32 1, i32 2>
  call void @llvm.amdgcn.raw.tbuffer.store.v3f16(<3 x half> %data_subvec, i32 %rsrc, i32 0, i32 0, i32 33, i32 0)
  ret void
}

define amdgpu_kernel void @tbuffer_store_d16_xyzw(i32 inreg %rsrc, <4 x half> %data) {
; GFX13-LABEL: tbuffer_store_d16_xyzw:
; GFX13:       ; %bb.0: ; %main_body
; GFX13-NEXT:    s_clause 0x1
; GFX13-NEXT:    s_load_b64 s[0:1], s[4:5], 0x2c
; GFX13-NEXT:    s_load_b32 s2, s[4:5], 0x24
; GFX13-NEXT:    s_wait_kmcnt 0x0
; GFX13-NEXT:    v_dual_mov_b32 v0, s0 :: v_dual_mov_b32 v1, s1
; GFX13-NEXT:    tbuffer_store_d16_format_xyzw v[0:1], off, s2, null format:[BUF_FMT_10_10_10_2_SNORM]
; GFX13-NEXT:    s_endpgm
main_body:
  call void @llvm.amdgcn.raw.tbuffer.store.v4f16(<4 x half> %data, i32 %rsrc, i32 0, i32 0, i32 33, i32 0)
  ret void
}

declare void @llvm.amdgcn.raw.tbuffer.store.f16(half, i32, i32, i32, i32, i32)
declare void @llvm.amdgcn.raw.tbuffer.store.v2f16(<2 x half>, i32, i32, i32, i32, i32)
declare void @llvm.amdgcn.raw.tbuffer.store.v3f16(<3 x half>, i32, i32, i32, i32, i32)
declare void @llvm.amdgcn.raw.tbuffer.store.v4f16(<4 x half>, i32, i32, i32, i32, i32)
