; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -global-isel=0 -march=amdgcn -mcpu=gfx1300 -verify-machineinstrs < %s | FileCheck -check-prefixes=GFX13,GFX13-SDAG %s
; RUN: llc -global-isel=1 -march=amdgcn -mcpu=gfx1300 -verify-machineinstrs < %s | FileCheck -check-prefixes=GFX13,GFX13-GISEL %s

define amdgpu_cs void @test_swc_reorder(i64 %arg){
; GFX13-LABEL: test_swc_reorder:
; GFX13:       ; %bb.0:
; GFX13-NEXT:    swc_reorder v0, v[0:1]
; GFX13-NEXT:    s_wait_swccnt 0x0
; GFX13-NEXT:    export prim v0, off, off, off done
; GFX13-NEXT:    s_endpgm
  %ret = call i32 @llvm.amdgcn.swc.reorder(i64 %arg)
  call void @llvm.amdgcn.exp.i32(i32 20, i32 1, i32 %ret, i32 undef, i32 undef, i32 undef, i1 true, i1 false)
  ret void
}

define amdgpu_cs void @test_swc_flush(){
; GFX13-LABEL: test_swc_flush:
; GFX13:       ; %bb.0:
; GFX13-NEXT:    global_wb scope:SCOPE_SYS
; GFX13-NEXT:    s_wait_storecnt 0x0
; GFX13-NEXT:    swc_flush scope:SCOPE_SYS
; GFX13-NEXT:    global_inv scope:SCOPE_SYS
; GFX13-NEXT:    s_endpgm
  call void @llvm.amdgcn.swc.flush()
  ret void
}

define amdgpu_cs void @test_swc_reorder_swap(i64 %arg){
; GFX13-LABEL: test_swc_reorder_swap:
; GFX13:       ; %bb.0:
; GFX13-NEXT:    swc_reorder_swap v0, v[0:1]
; GFX13-NEXT:    s_wait_swccnt 0x0
; GFX13-NEXT:    export prim v0, off, off, off done
; GFX13-NEXT:    s_endpgm
  %ret = call i32 @llvm.amdgcn.swc.reorder.swap(i64 %arg)
  call void @llvm.amdgcn.exp.i32(i32 20, i32 1, i32 %ret, i32 undef, i32 undef, i32 undef, i1 true, i1 false)
  ret void
}

define amdgpu_cs void @test_swc_reorder_swap_resume(){
; GFX13-LABEL: test_swc_reorder_swap_resume:
; GFX13:       ; %bb.0:
; GFX13-NEXT:    swc_reorder_swap_resume v0
; GFX13-NEXT:    s_wait_swccnt 0x0
; GFX13-NEXT:    export prim v0, off, off, off done
; GFX13-NEXT:    s_endpgm
  %ret = call i32 @llvm.amdgcn.swc.reorder.swap.resume()
  call void @llvm.amdgcn.exp.i32(i32 20, i32 1, i32 %ret, i32 undef, i32 undef, i32 undef, i1 true, i1 false)
  ret void
}

define amdgpu_cs void @test_swc_get_exchange_state(){
; GFX13-LABEL: test_swc_get_exchange_state:
; GFX13:       ; %bb.0:
; GFX13-NEXT:    swc_get_exchange_state v0
; GFX13-NEXT:    s_wait_swccnt 0x0
; GFX13-NEXT:    export prim v0, off, off, off done
; GFX13-NEXT:    s_endpgm
  %ret = call i32 @llvm.amdgcn.swc.get.exchange.state()
  call void @llvm.amdgcn.exp.i32(i32 20, i32 1, i32 %ret, i32 undef, i32 undef, i32 undef, i1 true, i1 false)
  ret void
}

define amdgpu_cs void @test_swc_set_exchange_state(i32 %arg){
; GFX13-LABEL: test_swc_set_exchange_state:
; GFX13:       ; %bb.0:
; GFX13-NEXT:    swc_set_exchange_state, v0
; GFX13-NEXT:    s_endpgm
  call void @llvm.amdgcn.swc.set.exchange.state(i32 %arg)
  ret void
}

define amdgpu_cs void @test_swc_abort_exchange(){
; GFX13-LABEL: test_swc_abort_exchange:
; GFX13:       ; %bb.0:
; GFX13-NEXT:    global_wb scope:SCOPE_SYS
; GFX13-NEXT:    s_wait_storecnt 0x0
; GFX13-NEXT:    swc_abort_exchange scope:SCOPE_SYS
; GFX13-NEXT:    global_inv scope:SCOPE_SYS
; GFX13-NEXT:    s_endpgm
  call void @llvm.amdgcn.swc.abort.exchange()
  ret void
}
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; GFX13-GISEL: {{.*}}
; GFX13-SDAG: {{.*}}
