; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel=0 -march=amdgcn -mcpu=gfx1300 -O3 -verify-machineinstrs < %s | FileCheck -check-prefixes=CHECK %s

@dst = external local_unnamed_addr addrspace(10) global <8 x float>, align 32
@sem = internal addrspace(3) global target("amdgcn.semaphore", 1) poison
@sem2 = internal addrspace(3) global target("amdgcn.semaphore", 1) poison

define amdgpu_kernel void @get_wavegroup_id_in_cluster(ptr addrspace(1) %use) "amdgpu-cluster-dims"="4,1,1" "amdgpu-wavegroup-enable" "amdgpu-spatial-cluster" !reqd_work_group_size !{i32 32, i32 8, i32 1} {
; CHECK-LABEL: get_wavegroup_id_in_cluster:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_getreg_b32 s0, hwreg(HW_REG_WAVE_GROUP_INFO, 16, 4)
; CHECK-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; CHECK-NEXT:    s_mul_i32 s1, s0, 2
; CHECK-NEXT:    s_mul_i32 s33, s0, s8
; CHECK-NEXT:    s_set_gpr_idx_u32 idx0, s1
; CHECK-NEXT:    ; sched_barrier mask(0x00000000)
; CHECK-NEXT:    s_load_b64 s[0:1], s[4:5], 0x24
; CHECK-NEXT:    s_getreg_b32 s2, hwreg(HW_REG_WAVE_GROUP_INFO, 4, 4)
; CHECK-NEXT:    s_bfe_u32 s3, ttmp8, 0x20019
; CHECK-NEXT:    s_lshl_b32 s2, s2, 2
; CHECK-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(SALU_CYCLE_1)
; CHECK-NEXT:    s_or_b32 s2, s2, s3
; CHECK-NEXT:    v_dual_mov_b32 v0, 0 :: v_dual_mov_b32 v1, s2
; CHECK-NEXT:    s_wait_kmcnt 0x0
; CHECK-NEXT:    global_store_b32 v0, v1, s[0:1] scope:SCOPE_SE
; CHECK-NEXT:    s_endpgm
entry:
  %wg_cluster = call i32 @llvm.amdgcn.wavegroup.id.in.cluster()
  store i32 %wg_cluster, ptr addrspace(1) %use
  ret void
}
