; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel=0 -march=amdgcn -mcpu=gfx1300 -verify-machineinstrs < %s | FileCheck -check-prefixes=GFX13,GFX13-SDAG %s
; RUN: llc -global-isel=1 -march=amdgcn -mcpu=gfx1300 -verify-machineinstrs < %s | FileCheck -check-prefixes=GFX13,GFX13-GISEL %s

declare void @llvm.amdgcn.dds.load.async.to.lds.b32(ptr addrspace(11) %gaddr, ptr addrspace(3) %laddr, i32 %offset, i32 %cpol)
declare void @llvm.amdgcn.dds.load.async.to.lds.b64(ptr addrspace(11) %gaddr, ptr addrspace(3) %laddr, i32 %offset, i32 %cpol)
declare void @llvm.amdgcn.dds.load.async.to.lds.b128(ptr addrspace(11) %gaddr, ptr addrspace(3) %laddr, i32 %offset, i32 %cpol)


define amdgpu_ps void @dds_load_async_to_lds_b32_vaddr(ptr addrspace(11) %gaddr, ptr addrspace(3) %laddr) {
; GFX13-SDAG-LABEL: dds_load_async_to_lds_b32_vaddr:
; GFX13-SDAG:       ; %bb.0: ; %entry
; GFX13-SDAG-NEXT:    s_mov_b32 s0, 16
; GFX13-SDAG-NEXT:    dds_load_async_to_lds_b32 v1, v0, s0 offset:16 th:TH_LOAD_HT scope:SCOPE_SE
; GFX13-SDAG-NEXT:    s_endpgm
;
; GFX13-GISEL-LABEL: dds_load_async_to_lds_b32_vaddr:
; GFX13-GISEL:       ; %bb.0: ; %entry
; GFX13-GISEL-NEXT:    v_add_nc_u32_e32 v0, 16, v0
; GFX13-GISEL-NEXT:    dds_load_async_to_lds_b32 v1, v0, off offset:16 th:TH_LOAD_HT scope:SCOPE_SE
; GFX13-GISEL-NEXT:    s_endpgm
entry:
  %gep = getelementptr i32, ptr addrspace(11) %gaddr, i32 4
  call void @llvm.amdgcn.dds.load.async.to.lds.b32(ptr addrspace(11) %gep, ptr addrspace(3) %laddr, i32 16, i32 10)
  ret void
}

define amdgpu_ps void @dds_load_async_to_lds_b32_saddr(ptr addrspace(11) inreg %gaddr, ptr addrspace(3) %laddr) {
; GFX13-LABEL: dds_load_async_to_lds_b32_saddr:
; GFX13:       ; %bb.0: ; %entry
; GFX13-NEXT:    v_mov_b32_e32 v1, 16
; GFX13-NEXT:    dds_load_async_to_lds_b32 v0, v1, s0 offset:16
; GFX13-NEXT:    s_endpgm
entry:
  %gep = getelementptr i32, ptr addrspace(11) %gaddr, i32 4
  call void @llvm.amdgcn.dds.load.async.to.lds.b32(ptr addrspace(11) %gep, ptr addrspace(3) %laddr, i32 16, i32 0)
  ret void
}

define amdgpu_ps void @dds_load_async_to_lds_b64_vaddr(ptr addrspace(11) %gaddr, ptr addrspace(3) %laddr) {
; GFX13-SDAG-LABEL: dds_load_async_to_lds_b64_vaddr:
; GFX13-SDAG:       ; %bb.0: ; %entry
; GFX13-SDAG-NEXT:    s_mov_b32 s0, 16
; GFX13-SDAG-NEXT:    dds_load_async_to_lds_b64 v1, v0, s0 offset:16 th:TH_LOAD_NT_HT scope:SCOPE_DEV
; GFX13-SDAG-NEXT:    s_endpgm
;
; GFX13-GISEL-LABEL: dds_load_async_to_lds_b64_vaddr:
; GFX13-GISEL:       ; %bb.0: ; %entry
; GFX13-GISEL-NEXT:    v_add_nc_u32_e32 v0, 16, v0
; GFX13-GISEL-NEXT:    dds_load_async_to_lds_b64 v1, v0, off offset:16 th:TH_LOAD_NT_HT scope:SCOPE_DEV
; GFX13-GISEL-NEXT:    s_endpgm
entry:
  %gep = getelementptr i32, ptr addrspace(11) %gaddr, i32 4
  call void @llvm.amdgcn.dds.load.async.to.lds.b64(ptr addrspace(11) %gep, ptr addrspace(3) %laddr, i32 16, i32 22)
  ret void
}

define amdgpu_ps void @dds_load_async_to_lds_b64_saddr(ptr addrspace(11) inreg %gaddr, ptr addrspace(3) %laddr) {
; GFX13-LABEL: dds_load_async_to_lds_b64_saddr:
; GFX13:       ; %bb.0: ; %entry
; GFX13-NEXT:    v_mov_b32_e32 v1, 16
; GFX13-NEXT:    dds_load_async_to_lds_b64 v0, v1, s0 offset:16
; GFX13-NEXT:    s_endpgm
entry:
  %gep = getelementptr i32, ptr addrspace(11) %gaddr, i32 4
  call void @llvm.amdgcn.dds.load.async.to.lds.b64(ptr addrspace(11) %gep, ptr addrspace(3) %laddr, i32 16, i32 0)
  ret void
}

define amdgpu_ps void @dds_load_async_to_lds_b128_vaddr(ptr addrspace(11) %gaddr, ptr addrspace(3) %laddr) {
; GFX13-SDAG-LABEL: dds_load_async_to_lds_b128_vaddr:
; GFX13-SDAG:       ; %bb.0: ; %entry
; GFX13-SDAG-NEXT:    s_mov_b32 s0, 16
; GFX13-SDAG-NEXT:    dds_load_async_to_lds_b128 v1, v0, s0 offset:16 th:TH_LOAD_BYPASS scope:SCOPE_SYS
; GFX13-SDAG-NEXT:    s_endpgm
;
; GFX13-GISEL-LABEL: dds_load_async_to_lds_b128_vaddr:
; GFX13-GISEL:       ; %bb.0: ; %entry
; GFX13-GISEL-NEXT:    v_add_nc_u32_e32 v0, 16, v0
; GFX13-GISEL-NEXT:    dds_load_async_to_lds_b128 v1, v0, off offset:16 th:TH_LOAD_BYPASS scope:SCOPE_SYS
; GFX13-GISEL-NEXT:    s_endpgm
entry:
  %gep = getelementptr i32, ptr addrspace(11) %gaddr, i32 4
  call void @llvm.amdgcn.dds.load.async.to.lds.b128(ptr addrspace(11) %gep, ptr addrspace(3) %laddr, i32 16, i32 27)
  ret void
}

define amdgpu_ps void @dds_load_async_to_lds_b128_saddr(ptr addrspace(11) inreg %gaddr, ptr addrspace(3) %laddr) {
; GFX13-LABEL: dds_load_async_to_lds_b128_saddr:
; GFX13:       ; %bb.0: ; %entry
; GFX13-NEXT:    v_mov_b32_e32 v1, 16
; GFX13-NEXT:    dds_load_async_to_lds_b128 v0, v1, s0 offset:16
; GFX13-NEXT:    s_endpgm
entry:
  %gep = getelementptr i32, ptr addrspace(11) %gaddr, i32 4
  call void @llvm.amdgcn.dds.load.async.to.lds.b128(ptr addrspace(11) %gep, ptr addrspace(3) %laddr, i32 16, i32 0)
  ret void
}

define amdgpu_ps void @dds_load_async_to_lds_b32_saddr_scale_offset(ptr addrspace(11) inreg %gaddr, ptr addrspace(3) %laddr, i32 %idx) {
; GFX13-LABEL: dds_load_async_to_lds_b32_saddr_scale_offset:
; GFX13:       ; %bb.0: ; %entry
; GFX13-NEXT:    v_lshlrev_b32_e32 v1, 2, v1
; GFX13-NEXT:    dds_load_async_to_lds_b32 v0, v1, s0 offset:16 th:TH_LOAD_NT
; GFX13-NEXT:    s_endpgm
entry:
  %idxprom = sext i32 %idx to i64
  %gep = getelementptr i32, ptr addrspace(11) %gaddr, i64 %idxprom
  call void @llvm.amdgcn.dds.load.async.to.lds.b32(ptr addrspace(11) %gep, ptr addrspace(3) %laddr, i32 16, i32 1)
  ret void
}

define amdgpu_ps void @dds_load_async_to_lds_b64_saddr_scale_offset(ptr addrspace(11) inreg %gaddr, ptr addrspace(3) %laddr, i32 %idx) {
; GFX13-LABEL: dds_load_async_to_lds_b64_saddr_scale_offset:
; GFX13:       ; %bb.0: ; %entry
; GFX13-NEXT:    v_lshlrev_b32_e32 v1, 2, v1
; GFX13-NEXT:    dds_load_async_to_lds_b64 v0, v1, s0 offset:16 th:TH_LOAD_NT
; GFX13-NEXT:    s_endpgm
entry:
  %idxprom = sext i32 %idx to i64
  %gep = getelementptr i32, ptr addrspace(11) %gaddr, i64 %idxprom
  call void @llvm.amdgcn.dds.load.async.to.lds.b64(ptr addrspace(11) %gep, ptr addrspace(3) %laddr, i32 16, i32 1)
  ret void
}

define amdgpu_ps void @dds_load_async_to_lds_b64_saddr_no_scale_offset(ptr addrspace(11) inreg %gaddr, ptr addrspace(3) %laddr, i32 %idx) {
; GFX13-LABEL: dds_load_async_to_lds_b64_saddr_no_scale_offset:
; GFX13:       ; %bb.0: ; %entry
; GFX13-NEXT:    v_lshlrev_b32_e32 v1, 2, v1
; GFX13-NEXT:    dds_load_async_to_lds_b64 v0, v1, s0 offset:16 th:TH_LOAD_NT
; GFX13-NEXT:    s_endpgm
entry:
  %idxprom = sext i32 %idx to i64
  %gep = getelementptr i32, ptr addrspace(11) %gaddr, i64 %idxprom
  call void @llvm.amdgcn.dds.load.async.to.lds.b64(ptr addrspace(11) %gep, ptr addrspace(3) %laddr, i32 16, i32 1)
  ret void
}
