; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -march=amdgcn -mcpu=gfx1300 -global-isel=0 -verify-machineinstrs < %s | FileCheck --check-prefixes=CHECK,SDAG %s
; RUN: llc -march=amdgcn -mcpu=gfx1300 -global-isel=1 -verify-machineinstrs < %s | FileCheck --check-prefixes=CHECK,GISEL %s

define amdgpu_cs i32 @test32_constant_all() {
; CHECK-LABEL: test32_constant_all:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_movk_i32 m0, 0x500
; CHECK-NEXT:    s_mov_from_global_b32 s0, s104
; CHECK-NEXT:    ; return to shader part epilog
  %a = call i32 @llvm.amdgcn.s.mov.from.global.i32(i16 104, i32 1280)
  ret i32 %a
}

define amdgpu_cs i64 @test64_constant_all() {
; CHECK-LABEL: test64_constant_all:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_movk_i32 m0, 0x500
; CHECK-NEXT:    s_mov_from_global_b64 s[0:1], s[104:105]
; CHECK-NEXT:    ; return to shader part epilog
  %a = call i64 @llvm.amdgcn.s.mov.from.global.i64(i16 104, i32 1280)
  ret i64 %a
}

define amdgpu_cs i32 @test32_uniform_m0(i32 inreg %m0) {
; CHECK-LABEL: test32_uniform_m0:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_mov_b32 m0, s0
; CHECK-NEXT:    s_mov_from_global_b32 s0, s10
; CHECK-NEXT:    ; return to shader part epilog
  %a = call i32 @llvm.amdgcn.s.mov.from.global.i32(i16 10, i32 %m0)
  ret i32 %a
}

; TODO: The inserted s_delay_alu is misguided. This is a VALU -> SALU dependency
;       which is handled by a HW dependency counter for correctness.
define amdgpu_cs i64 @test64_divergent_m0(i32 %m0) {
; CHECK-LABEL: test64_divergent_m0:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    v_readfirstlane_b32 s0, v0
; CHECK-NEXT:    s_mov_b32 m0, s0
; CHECK-NEXT:    s_mov_from_global_b64 s[0:1], s[10:11]
; CHECK-NEXT:    ; return to shader part epilog
  %a = call i64 @llvm.amdgcn.s.mov.from.global.i64(i16 10, i32 %m0)
  ret i64 %a
}

; Test that redundant M0 setups are avoided.
define amdgpu_cs i32 @test_multiple_uses(i32 inreg %m0a, i32 inreg %m0b) {
; CHECK-LABEL: test_multiple_uses:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_mov_b32 m0, s0
; CHECK-NEXT:    s_mov_from_global_b32 s0, s0
; CHECK-NEXT:    s_mov_from_global_b32 s2, s3
; CHECK-NEXT:    s_mov_b32 m0, s1
; CHECK-NEXT:    s_xor_b32 s0, s0, s2
; CHECK-NEXT:    s_mov_from_global_b32 s1, s4
; CHECK-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; CHECK-NEXT:    s_xor_b32 s0, s0, s1
; CHECK-NEXT:    ; return to shader part epilog
  %a = call i32 @llvm.amdgcn.s.mov.from.global.i32(i16 0, i32 %m0a)
  %b = call i32 @llvm.amdgcn.s.mov.from.global.i32(i16 3, i32 %m0a)
  %c = call i32 @llvm.amdgcn.s.mov.from.global.i32(i16 4, i32 %m0b)
  %r.0 = xor i32 %a, %b
  %r.1 = xor i32 %r.0, %c
  ret i32 %r.1
}

declare i32 @llvm.amdgcn.s.mov.from.global.i32(i16, i32)
declare i64 @llvm.amdgcn.s.mov.from.global.i64(i16, i32)
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; GISEL: {{.*}}
; SDAG: {{.*}}
