; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -mtriple=amdgcn -mcpu=gfx1251 < %s | FileCheck %s --check-prefix=GFX1251
; RUN: llc -mtriple=amdgcn -mcpu=gfx1251 -global-isel -new-reg-bank-select < %s | FileCheck %s --check-prefix=GISEL

define amdgpu_ps void @test_wmma_f64_16x16x4_f64(<2 x double> %A, <2 x double> %B, ptr addrspace(1) %out) {
; GFX1251-LABEL: test_wmma_f64_16x16x4_f64:
; GFX1251:       ; %bb.0: ; %bb
; GFX1251-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1 ; msbs: dst=0 src0=0 src1=0 src2=0
; GFX1251-NEXT:    v_wmma_f64_16x16x4_f64 v[10:25], v[0:3], v[4:7], 1.0
; GFX1251-NEXT:    s_clause 0x3
; GFX1251-NEXT:    global_store_b128 v[8:9], v[22:25], off offset:48
; GFX1251-NEXT:    global_store_b128 v[8:9], v[18:21], off offset:32
; GFX1251-NEXT:    global_store_b128 v[8:9], v[14:17], off offset:16
; GFX1251-NEXT:    global_store_b128 v[8:9], v[10:13], off
; GFX1251-NEXT:    s_endpgm
;
; GISEL-LABEL: test_wmma_f64_16x16x4_f64:
; GISEL:       ; %bb.0: ; %bb
; GISEL-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1 ; msbs: dst=0 src0=0 src1=0 src2=0
; GISEL-NEXT:    v_wmma_f64_16x16x4_f64 v[10:25], v[0:3], v[4:7], 1.0
; GISEL-NEXT:    s_clause 0x3
; GISEL-NEXT:    global_store_b128 v[8:9], v[10:13], off
; GISEL-NEXT:    global_store_b128 v[8:9], v[14:17], off offset:16
; GISEL-NEXT:    global_store_b128 v[8:9], v[18:21], off offset:32
; GISEL-NEXT:    global_store_b128 v[8:9], v[22:25], off offset:48
; GISEL-NEXT:    s_endpgm
bb:
  %res = call <8 x double> @llvm.amdgcn.wmma.f64.16x16x4.f64.v8f64.v2f64(i1 0, <2 x double> %A, i1 0, <2 x double> %B, i16 0, <8 x double> <double 1.0, double 1.0, double 1.0, double 1.0, double 1.0, double 1.0, double 1.0, double 1.0>, i1 false, i1 false)
  store <8 x double> %res, ptr addrspace(1) %out
  ret void
}

define amdgpu_ps void @test_wmma_f64_16x16x4_f64_non_splat(<2 x double> %A, <2 x double> %B, ptr addrspace(1) %out) {
; GFX1251-LABEL: test_wmma_f64_16x16x4_f64_non_splat:
; GFX1251:       ; %bb.0: ; %bb
; GFX1251-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1 ; msbs: dst=0 src0=0 src1=0 src2=0
; GFX1251-NEXT:    v_dual_mov_b32 v10, 0 :: v_dual_mov_b32 v11, 0x3ff00000
; GFX1251-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX1251-NEXT:    v_dual_mov_b32 v15, 2.0 :: v_dual_mov_b32 v12, v10
; GFX1251-NEXT:    v_dual_mov_b32 v13, v11 :: v_dual_mov_b32 v14, v10
; GFX1251-NEXT:    v_dual_mov_b32 v16, v10 :: v_dual_mov_b32 v17, v11
; GFX1251-NEXT:    v_dual_mov_b32 v18, v10 :: v_dual_mov_b32 v19, v11
; GFX1251-NEXT:    v_dual_mov_b32 v20, v10 :: v_dual_mov_b32 v21, v11
; GFX1251-NEXT:    v_dual_mov_b32 v22, v10 :: v_dual_mov_b32 v23, v11
; GFX1251-NEXT:    v_dual_mov_b32 v24, v10 :: v_dual_mov_b32 v25, v11
; GFX1251-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1251-NEXT:    v_wmma_f64_16x16x4_f64 v[10:25], v[0:3], v[4:7], v[10:25]
; GFX1251-NEXT:    s_clause 0x3
; GFX1251-NEXT:    global_store_b128 v[8:9], v[22:25], off offset:48
; GFX1251-NEXT:    global_store_b128 v[8:9], v[18:21], off offset:32
; GFX1251-NEXT:    global_store_b128 v[8:9], v[14:17], off offset:16
; GFX1251-NEXT:    global_store_b128 v[8:9], v[10:13], off
; GFX1251-NEXT:    s_endpgm
;
; GISEL-LABEL: test_wmma_f64_16x16x4_f64_non_splat:
; GISEL:       ; %bb.0: ; %bb
; GISEL-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1 ; msbs: dst=0 src0=0 src1=0 src2=0
; GISEL-NEXT:    s_mov_b64 s[0:1], 1.0
; GISEL-NEXT:    s_mov_b64 s[4:5], 2.0
; GISEL-NEXT:    s_mov_b64 s[14:15], s[0:1]
; GISEL-NEXT:    s_mov_b64 s[2:3], s[0:1]
; GISEL-NEXT:    s_mov_b64 s[6:7], s[0:1]
; GISEL-NEXT:    s_mov_b64 s[8:9], s[0:1]
; GISEL-NEXT:    s_mov_b64 s[10:11], s[0:1]
; GISEL-NEXT:    s_mov_b64 s[12:13], s[0:1]
; GISEL-NEXT:    v_mov_b64_e32 v[24:25], s[14:15]
; GISEL-NEXT:    v_mov_b64_e32 v[22:23], s[12:13]
; GISEL-NEXT:    v_mov_b64_e32 v[20:21], s[10:11]
; GISEL-NEXT:    v_mov_b64_e32 v[18:19], s[8:9]
; GISEL-NEXT:    v_mov_b64_e32 v[16:17], s[6:7]
; GISEL-NEXT:    v_mov_b64_e32 v[14:15], s[4:5]
; GISEL-NEXT:    v_mov_b64_e32 v[12:13], s[2:3]
; GISEL-NEXT:    v_mov_b64_e32 v[10:11], s[0:1]
; GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GISEL-NEXT:    v_wmma_f64_16x16x4_f64 v[10:25], v[0:3], v[4:7], v[10:25]
; GISEL-NEXT:    s_clause 0x3
; GISEL-NEXT:    global_store_b128 v[8:9], v[10:13], off
; GISEL-NEXT:    global_store_b128 v[8:9], v[14:17], off offset:16
; GISEL-NEXT:    global_store_b128 v[8:9], v[18:21], off offset:32
; GISEL-NEXT:    global_store_b128 v[8:9], v[22:25], off offset:48
; GISEL-NEXT:    s_endpgm
bb:
  %res = call <8 x double> @llvm.amdgcn.wmma.f64.16x16x4.f64.v8f64.v2f64(i1 0, <2 x double> %A, i1 0, <2 x double> %B, i16 0, <8 x double> <double 1.0, double 1.0, double 2.0, double 1.0, double 1.0, double 1.0, double 1.0, double 1.0>, i1 false, i1 false)
  store <8 x double> %res, ptr addrspace(1) %out
  ret void
}

define amdgpu_ps void @test_wmma_f64_16x16x4_f64_non_inlineable(<2 x double> %A, <2 x double> %B, ptr addrspace(1) %out) {
; GFX1251-LABEL: test_wmma_f64_16x16x4_f64_non_inlineable:
; GFX1251:       ; %bb.0: ; %bb
; GFX1251-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1 ; msbs: dst=0 src0=0 src1=0 src2=0
; GFX1251-NEXT:    v_dual_mov_b32 v10, 0 :: v_dual_mov_b32 v11, 0x40080000
; GFX1251-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1251-NEXT:    v_dual_mov_b32 v12, v10 :: v_dual_mov_b32 v13, v11
; GFX1251-NEXT:    v_dual_mov_b32 v14, v10 :: v_dual_mov_b32 v15, v11
; GFX1251-NEXT:    v_dual_mov_b32 v16, v10 :: v_dual_mov_b32 v17, v11
; GFX1251-NEXT:    v_dual_mov_b32 v18, v10 :: v_dual_mov_b32 v19, v11
; GFX1251-NEXT:    v_dual_mov_b32 v20, v10 :: v_dual_mov_b32 v21, v11
; GFX1251-NEXT:    v_dual_mov_b32 v22, v10 :: v_dual_mov_b32 v23, v11
; GFX1251-NEXT:    v_dual_mov_b32 v24, v10 :: v_dual_mov_b32 v25, v11
; GFX1251-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1251-NEXT:    v_wmma_f64_16x16x4_f64 v[10:25], v[0:3], v[4:7], v[10:25]
; GFX1251-NEXT:    s_clause 0x3
; GFX1251-NEXT:    global_store_b128 v[8:9], v[22:25], off offset:48
; GFX1251-NEXT:    global_store_b128 v[8:9], v[18:21], off offset:32
; GFX1251-NEXT:    global_store_b128 v[8:9], v[14:17], off offset:16
; GFX1251-NEXT:    global_store_b128 v[8:9], v[10:13], off
; GFX1251-NEXT:    s_endpgm
;
; GISEL-LABEL: test_wmma_f64_16x16x4_f64_non_inlineable:
; GISEL:       ; %bb.0: ; %bb
; GISEL-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1 ; msbs: dst=0 src0=0 src1=0 src2=0
; GISEL-NEXT:    s_mov_b64 s[0:1], 0x4008000000000000
; GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GISEL-NEXT:    s_mov_b64 s[14:15], s[0:1]
; GISEL-NEXT:    s_mov_b64 s[2:3], s[0:1]
; GISEL-NEXT:    s_mov_b64 s[4:5], s[0:1]
; GISEL-NEXT:    s_mov_b64 s[6:7], s[0:1]
; GISEL-NEXT:    s_mov_b64 s[8:9], s[0:1]
; GISEL-NEXT:    s_mov_b64 s[10:11], s[0:1]
; GISEL-NEXT:    s_mov_b64 s[12:13], s[0:1]
; GISEL-NEXT:    v_mov_b64_e32 v[24:25], s[14:15]
; GISEL-NEXT:    v_mov_b64_e32 v[22:23], s[12:13]
; GISEL-NEXT:    v_mov_b64_e32 v[20:21], s[10:11]
; GISEL-NEXT:    v_mov_b64_e32 v[18:19], s[8:9]
; GISEL-NEXT:    v_mov_b64_e32 v[16:17], s[6:7]
; GISEL-NEXT:    v_mov_b64_e32 v[14:15], s[4:5]
; GISEL-NEXT:    v_mov_b64_e32 v[12:13], s[2:3]
; GISEL-NEXT:    v_mov_b64_e32 v[10:11], s[0:1]
; GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GISEL-NEXT:    v_wmma_f64_16x16x4_f64 v[10:25], v[0:3], v[4:7], v[10:25]
; GISEL-NEXT:    s_clause 0x3
; GISEL-NEXT:    global_store_b128 v[8:9], v[10:13], off
; GISEL-NEXT:    global_store_b128 v[8:9], v[14:17], off offset:16
; GISEL-NEXT:    global_store_b128 v[8:9], v[18:21], off offset:32
; GISEL-NEXT:    global_store_b128 v[8:9], v[22:25], off offset:48
; GISEL-NEXT:    s_endpgm
bb:
  %res = call <8 x double> @llvm.amdgcn.wmma.f64.16x16x4.f64.v8f64.v2f64(i1 0, <2 x double> %A, i1 0, <2 x double> %B, i16 0, <8 x double> <double 3.0, double 3.0, double 3.0, double 3.0, double 3.0, double 3.0, double 3.0, double 3.0>, i1 false, i1 false)
  store <8 x double> %res, ptr addrspace(1) %out
  ret void
}

declare <8 x double> @llvm.amdgcn.wmma.f64.16x16x4.f64.v8f64.v2f64(i1, <2 x double>, i1, <2 x double>, i16, <8 x double>, i1, i1)
