; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -global-isel=0 -march=amdgcn -mcpu=gfx1210 -verify-machineinstrs < %s | FileCheck -check-prefix=GCN %s
; RUN: llc -global-isel=1 -march=amdgcn -mcpu=gfx1210 -verify-machineinstrs < %s | FileCheck -check-prefix=GCN %s

declare <2 x i16> @llvm.amdgcn.pk.add.bf16(<2 x i16> %src0, <2 x i16> %src1) #0

define amdgpu_ps float @pk_add_bf16_vv(<2 x i16> %src0, <2 x i16> %src1) #1 {
; GCN-LABEL: pk_add_bf16_vv:
; GCN:       ; %bb.0:
; GCN-NEXT:    v_pk_add_bf16 v0, v0, v1
; GCN-NEXT:    ; return to shader part epilog
  %val = call <2 x i16> @llvm.amdgcn.pk.add.bf16(<2 x i16> %src0, <2 x i16> %src1) #0
  %ret = bitcast <2 x i16> %val to float
  ret float %ret
}

define amdgpu_ps float @pk_add_bf16_ss(<2 x i16> inreg %src0, <2 x i16> inreg %src1) #1 {
; GCN-LABEL: pk_add_bf16_ss:
; GCN:       ; %bb.0:
; GCN-NEXT:    v_pk_add_bf16 v0, s0, s1
; GCN-NEXT:    ; return to shader part epilog
  %val = call <2 x i16> @llvm.amdgcn.pk.add.bf16(<2 x i16> %src0, <2 x i16> %src1) #0
  %ret = bitcast <2 x i16> %val to float
  ret float %ret
}

define amdgpu_ps float @pk_add_bf16_vi(<2 x i16> %src0) #1 {
; GCN-LABEL: pk_add_bf16_vi:
; GCN:       ; %bb.0:
; GCN-NEXT:    v_pk_add_bf16 v0, v0, 1 op_sel_hi:[1,0]
; GCN-NEXT:    ; return to shader part epilog
  %val = call <2 x i16> @llvm.amdgcn.pk.add.bf16(<2 x i16> %src0, <2 x i16> <i16 1, i16 1>) #0
  %ret = bitcast <2 x i16> %val to float
  ret float %ret
}

define amdgpu_ps float @pk_add_bf16_vl(<2 x i16> %src0) #1 {
; GCN-LABEL: pk_add_bf16_vl:
; GCN:       ; %bb.0:
; GCN-NEXT:    v_pk_add_bf16 v0, 0x640064, v0
; GCN-NEXT:    ; return to shader part epilog
  %val = call <2 x i16> @llvm.amdgcn.pk.add.bf16(<2 x i16> %src0, <2 x i16> <i16 100, i16 100>) #0
  %ret = bitcast <2 x i16> %val to float
  ret float %ret
}

define amdgpu_ps float @pk_add_bf16_vll(<2 x i16> %src0) #1 {
; GCN-LABEL: pk_add_bf16_vll:
; GCN:       ; %bb.0:
; GCN-NEXT:    v_pk_add_bf16 v0, 0x650064, v0
; GCN-NEXT:    ; return to shader part epilog
  %val = call <2 x i16> @llvm.amdgcn.pk.add.bf16(<2 x i16> %src0, <2 x i16> <i16 100, i16 101>) #0
  %ret = bitcast <2 x i16> %val to float
  ret float %ret
}

attributes #0 = { nounwind readnone }
attributes #1 = { nounwind }
