; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -global-isel=0 -mtriple=amdgcn -mcpu=gfx1210 -verify-machineinstrs < %s | FileCheck -check-prefix=GFX1210-SDAG %s
; RUN: llc -global-isel=1 -mtriple=amdgcn -mcpu=gfx1210 -verify-machineinstrs < %s | FileCheck -check-prefix=GFX1210-GISEL %s

declare <2 x i32> @llvm.amdgcn.cvt.scalef32.sr.pk8.fp8.bf16(<8 x bfloat> %src, i32 %sr, float %scale)
declare <2 x i32> @llvm.amdgcn.cvt.scalef32.sr.pk8.bf8.bf16(<8 x bfloat> %src, i32 %sr, float %scale)
declare <2 x i32> @llvm.amdgcn.cvt.scalef32.sr.pk8.fp8.f16(<8 x half> %src, i32 %sr, float %scale)
declare <2 x i32> @llvm.amdgcn.cvt.scalef32.sr.pk8.bf8.f16(<8 x half> %src, i32 %sr, float %scale)
declare <2 x i32> @llvm.amdgcn.cvt.scalef32.sr.pk8.fp8.f32(<8 x float> %src, i32 %sr, float %scale)
declare <2 x i32> @llvm.amdgcn.cvt.scalef32.sr.pk8.bf8.f32(<8 x float> %src, i32 %sr, float %scale)
declare i32 @llvm.amdgcn.cvt.scalef32.sr.pk8.fp4.f32(<8 x float> %src, i32 %sr, float %scale)
declare i32 @llvm.amdgcn.cvt.scalef32.sr.pk8.fp4.f16(<8 x half> %src, i32 %sr, float %scale)
declare i32 @llvm.amdgcn.cvt.scalef32.sr.pk8.fp4.bf16(<8 x bfloat> %src, i32 %sr, float %scale)

define amdgpu_ps void @test_scalef32_sr_pk8_fp8_bf16_vv(<8 x bfloat> %src, i32 %sr, float %scale, ptr addrspace(1) %out) {
; GFX1210-SDAG-LABEL: test_scalef32_sr_pk8_fp8_bf16_vv:
; GFX1210-SDAG:       ; %bb.0:
; GFX1210-SDAG-NEXT:    v_cvt_scalef32_sr_pk8_fp8_bf16 v[8:9], v[0:3], v4, v5
; GFX1210-SDAG-NEXT:    global_store_b64 v[6:7], v[8:9], off
; GFX1210-SDAG-NEXT:    s_endpgm
;
; GFX1210-GISEL-LABEL: test_scalef32_sr_pk8_fp8_bf16_vv:
; GFX1210-GISEL:       ; %bb.0:
; GFX1210-GISEL-NEXT:    v_dual_lshrrev_b32 v8, 16, v0 :: v_dual_lshrrev_b32 v9, 16, v1
; GFX1210-GISEL-NEXT:    v_dual_lshrrev_b32 v10, 16, v2 :: v_dual_lshrrev_b32 v11, 16, v3
; GFX1210-GISEL-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX1210-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX1210-GISEL-NEXT:    v_dual_lshlrev_b32 v8, 16, v8 :: v_dual_lshlrev_b32 v9, 16, v9
; GFX1210-GISEL-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; GFX1210-GISEL-NEXT:    v_dual_lshlrev_b32 v10, 16, v10 :: v_dual_lshlrev_b32 v11, 16, v11
; GFX1210-GISEL-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX1210-GISEL-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GFX1210-GISEL-NEXT:    v_or_b32_e32 v0, v8, v0
; GFX1210-GISEL-NEXT:    v_or_b32_e32 v1, v9, v1
; GFX1210-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX1210-GISEL-NEXT:    v_or_b32_e32 v2, v10, v2
; GFX1210-GISEL-NEXT:    v_or_b32_e32 v3, v11, v3
; GFX1210-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1210-GISEL-NEXT:    v_cvt_scalef32_sr_pk8_fp8_bf16 v[8:9], v[0:3], v4, v5
; GFX1210-GISEL-NEXT:    global_store_b64 v[6:7], v[8:9], off
; GFX1210-GISEL-NEXT:    s_endpgm
  %cvt = tail call <2 x i32> @llvm.amdgcn.cvt.scalef32.sr.pk8.fp8.bf16(<8 x bfloat> %src, i32 %sr, float %scale)
  store <2 x i32> %cvt, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_ps void @test_scalef32_sr_pk8_fp8_bf16_sl(<8 x bfloat> inreg %src, i32 inreg %sr, ptr addrspace(1) %out) {
; GFX1210-SDAG-LABEL: test_scalef32_sr_pk8_fp8_bf16_sl:
; GFX1210-SDAG:       ; %bb.0:
; GFX1210-SDAG-NEXT:    v_dual_mov_b32 v2, s0 :: v_dual_mov_b32 v3, s1
; GFX1210-SDAG-NEXT:    v_dual_mov_b32 v4, s2 :: v_dual_mov_b32 v5, s3
; GFX1210-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1210-SDAG-NEXT:    v_cvt_scalef32_sr_pk8_fp8_bf16 v[6:7], v[2:5], s4, 0x42c80000
; GFX1210-SDAG-NEXT:    global_store_b64 v[0:1], v[6:7], off
; GFX1210-SDAG-NEXT:    s_endpgm
;
; GFX1210-GISEL-LABEL: test_scalef32_sr_pk8_fp8_bf16_sl:
; GFX1210-GISEL:       ; %bb.0:
; GFX1210-GISEL-NEXT:    s_lshr_b32 s5, s0, 16
; GFX1210-GISEL-NEXT:    s_lshr_b32 s6, s1, 16
; GFX1210-GISEL-NEXT:    s_lshr_b32 s7, s2, 16
; GFX1210-GISEL-NEXT:    s_lshr_b32 s8, s3, 16
; GFX1210-GISEL-NEXT:    s_lshl_b32 s5, s5, 16
; GFX1210-GISEL-NEXT:    s_and_b32 s0, s0, 0xffff
; GFX1210-GISEL-NEXT:    s_lshl_b32 s6, s6, 16
; GFX1210-GISEL-NEXT:    s_and_b32 s1, s1, 0xffff
; GFX1210-GISEL-NEXT:    s_or_b32 s0, s5, s0
; GFX1210-GISEL-NEXT:    s_or_b32 s1, s6, s1
; GFX1210-GISEL-NEXT:    s_lshl_b32 s5, s7, 16
; GFX1210-GISEL-NEXT:    s_and_b32 s2, s2, 0xffff
; GFX1210-GISEL-NEXT:    s_lshl_b32 s6, s8, 16
; GFX1210-GISEL-NEXT:    s_and_b32 s3, s3, 0xffff
; GFX1210-GISEL-NEXT:    s_or_b32 s2, s5, s2
; GFX1210-GISEL-NEXT:    s_or_b32 s3, s6, s3
; GFX1210-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX1210-GISEL-NEXT:    v_mov_b64_e32 v[4:5], s[2:3]
; GFX1210-GISEL-NEXT:    v_mov_b64_e32 v[2:3], s[0:1]
; GFX1210-GISEL-NEXT:    v_cvt_scalef32_sr_pk8_fp8_bf16 v[6:7], v[2:5], s4, 0x42c80000
; GFX1210-GISEL-NEXT:    global_store_b64 v[0:1], v[6:7], off
; GFX1210-GISEL-NEXT:    s_endpgm
  %cvt = tail call <2 x i32> @llvm.amdgcn.cvt.scalef32.sr.pk8.fp8.bf16(<8 x bfloat> %src, i32 %sr, float 100.0)
  store <2 x i32> %cvt, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_ps void @test_scalef32_sr_pk8_bf8_bf16_vv(<8 x bfloat> %src, i32 %sr, float %scale, ptr addrspace(1) %out) {
; GFX1210-SDAG-LABEL: test_scalef32_sr_pk8_bf8_bf16_vv:
; GFX1210-SDAG:       ; %bb.0:
; GFX1210-SDAG-NEXT:    v_cvt_scalef32_sr_pk8_bf8_bf16 v[8:9], v[0:3], v4, v5
; GFX1210-SDAG-NEXT:    global_store_b64 v[6:7], v[8:9], off
; GFX1210-SDAG-NEXT:    s_endpgm
;
; GFX1210-GISEL-LABEL: test_scalef32_sr_pk8_bf8_bf16_vv:
; GFX1210-GISEL:       ; %bb.0:
; GFX1210-GISEL-NEXT:    v_dual_lshrrev_b32 v8, 16, v0 :: v_dual_lshrrev_b32 v9, 16, v1
; GFX1210-GISEL-NEXT:    v_dual_lshrrev_b32 v10, 16, v2 :: v_dual_lshrrev_b32 v11, 16, v3
; GFX1210-GISEL-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX1210-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX1210-GISEL-NEXT:    v_dual_lshlrev_b32 v8, 16, v8 :: v_dual_lshlrev_b32 v9, 16, v9
; GFX1210-GISEL-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; GFX1210-GISEL-NEXT:    v_dual_lshlrev_b32 v10, 16, v10 :: v_dual_lshlrev_b32 v11, 16, v11
; GFX1210-GISEL-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX1210-GISEL-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GFX1210-GISEL-NEXT:    v_or_b32_e32 v0, v8, v0
; GFX1210-GISEL-NEXT:    v_or_b32_e32 v1, v9, v1
; GFX1210-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX1210-GISEL-NEXT:    v_or_b32_e32 v2, v10, v2
; GFX1210-GISEL-NEXT:    v_or_b32_e32 v3, v11, v3
; GFX1210-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1210-GISEL-NEXT:    v_cvt_scalef32_sr_pk8_bf8_bf16 v[8:9], v[0:3], v4, v5
; GFX1210-GISEL-NEXT:    global_store_b64 v[6:7], v[8:9], off
; GFX1210-GISEL-NEXT:    s_endpgm
  %cvt = tail call <2 x i32> @llvm.amdgcn.cvt.scalef32.sr.pk8.bf8.bf16(<8 x bfloat> %src, i32 %sr, float %scale)
  store <2 x i32> %cvt, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_ps void @test_scalef32_sr_pk8_bf8_bf16_sl(<8 x bfloat> inreg %src, i32 inreg %sr, ptr addrspace(1) %out) {
; GFX1210-SDAG-LABEL: test_scalef32_sr_pk8_bf8_bf16_sl:
; GFX1210-SDAG:       ; %bb.0:
; GFX1210-SDAG-NEXT:    v_dual_mov_b32 v2, s0 :: v_dual_mov_b32 v3, s1
; GFX1210-SDAG-NEXT:    v_dual_mov_b32 v4, s2 :: v_dual_mov_b32 v5, s3
; GFX1210-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1210-SDAG-NEXT:    v_cvt_scalef32_sr_pk8_bf8_bf16 v[6:7], v[2:5], s4, 0x42c80000
; GFX1210-SDAG-NEXT:    global_store_b64 v[0:1], v[6:7], off
; GFX1210-SDAG-NEXT:    s_endpgm
;
; GFX1210-GISEL-LABEL: test_scalef32_sr_pk8_bf8_bf16_sl:
; GFX1210-GISEL:       ; %bb.0:
; GFX1210-GISEL-NEXT:    s_lshr_b32 s5, s0, 16
; GFX1210-GISEL-NEXT:    s_lshr_b32 s6, s1, 16
; GFX1210-GISEL-NEXT:    s_lshr_b32 s7, s2, 16
; GFX1210-GISEL-NEXT:    s_lshr_b32 s8, s3, 16
; GFX1210-GISEL-NEXT:    s_lshl_b32 s5, s5, 16
; GFX1210-GISEL-NEXT:    s_and_b32 s0, s0, 0xffff
; GFX1210-GISEL-NEXT:    s_lshl_b32 s6, s6, 16
; GFX1210-GISEL-NEXT:    s_and_b32 s1, s1, 0xffff
; GFX1210-GISEL-NEXT:    s_or_b32 s0, s5, s0
; GFX1210-GISEL-NEXT:    s_or_b32 s1, s6, s1
; GFX1210-GISEL-NEXT:    s_lshl_b32 s5, s7, 16
; GFX1210-GISEL-NEXT:    s_and_b32 s2, s2, 0xffff
; GFX1210-GISEL-NEXT:    s_lshl_b32 s6, s8, 16
; GFX1210-GISEL-NEXT:    s_and_b32 s3, s3, 0xffff
; GFX1210-GISEL-NEXT:    s_or_b32 s2, s5, s2
; GFX1210-GISEL-NEXT:    s_or_b32 s3, s6, s3
; GFX1210-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX1210-GISEL-NEXT:    v_mov_b64_e32 v[4:5], s[2:3]
; GFX1210-GISEL-NEXT:    v_mov_b64_e32 v[2:3], s[0:1]
; GFX1210-GISEL-NEXT:    v_cvt_scalef32_sr_pk8_bf8_bf16 v[6:7], v[2:5], s4, 0x42c80000
; GFX1210-GISEL-NEXT:    global_store_b64 v[0:1], v[6:7], off
; GFX1210-GISEL-NEXT:    s_endpgm
  %cvt = tail call <2 x i32> @llvm.amdgcn.cvt.scalef32.sr.pk8.bf8.bf16(<8 x bfloat> %src, i32 %sr, float 100.0)
  store <2 x i32> %cvt, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_ps void @test_scalef32_sr_pk8_fp8_f16_vv(<8 x half> %src, i32 %sr, float %scale, ptr addrspace(1) %out) {
; GFX1210-SDAG-LABEL: test_scalef32_sr_pk8_fp8_f16_vv:
; GFX1210-SDAG:       ; %bb.0:
; GFX1210-SDAG-NEXT:    v_cvt_scalef32_sr_pk8_fp8_f16 v[8:9], v[0:3], v4, v5
; GFX1210-SDAG-NEXT:    global_store_b64 v[6:7], v[8:9], off
; GFX1210-SDAG-NEXT:    s_endpgm
;
; GFX1210-GISEL-LABEL: test_scalef32_sr_pk8_fp8_f16_vv:
; GFX1210-GISEL:       ; %bb.0:
; GFX1210-GISEL-NEXT:    v_cvt_scalef32_sr_pk8_fp8_f16 v[8:9], v[0:3], v4, v5
; GFX1210-GISEL-NEXT:    global_store_b64 v[6:7], v[8:9], off
; GFX1210-GISEL-NEXT:    s_endpgm
  %cvt = tail call <2 x i32> @llvm.amdgcn.cvt.scalef32.sr.pk8.fp8.f16(<8 x half> %src, i32 %sr, float %scale)
  store <2 x i32> %cvt, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_ps void @test_scalef32_sr_pk8_fp8_f16_sl(<8 x half> inreg %src, i32 inreg %sr, ptr addrspace(1) %out) {
; GFX1210-SDAG-LABEL: test_scalef32_sr_pk8_fp8_f16_sl:
; GFX1210-SDAG:       ; %bb.0:
; GFX1210-SDAG-NEXT:    v_dual_mov_b32 v2, s0 :: v_dual_mov_b32 v3, s1
; GFX1210-SDAG-NEXT:    v_dual_mov_b32 v4, s2 :: v_dual_mov_b32 v5, s3
; GFX1210-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1210-SDAG-NEXT:    v_cvt_scalef32_sr_pk8_fp8_f16 v[6:7], v[2:5], s4, 0x42c80000
; GFX1210-SDAG-NEXT:    global_store_b64 v[0:1], v[6:7], off
; GFX1210-SDAG-NEXT:    s_endpgm
;
; GFX1210-GISEL-LABEL: test_scalef32_sr_pk8_fp8_f16_sl:
; GFX1210-GISEL:       ; %bb.0:
; GFX1210-GISEL-NEXT:    v_mov_b64_e32 v[4:5], s[2:3]
; GFX1210-GISEL-NEXT:    v_mov_b64_e32 v[2:3], s[0:1]
; GFX1210-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1210-GISEL-NEXT:    v_cvt_scalef32_sr_pk8_fp8_f16 v[6:7], v[2:5], s4, 0x42c80000
; GFX1210-GISEL-NEXT:    global_store_b64 v[0:1], v[6:7], off
; GFX1210-GISEL-NEXT:    s_endpgm
  %cvt = tail call <2 x i32> @llvm.amdgcn.cvt.scalef32.sr.pk8.fp8.f16(<8 x half> %src, i32 %sr, float 100.0)
  store <2 x i32> %cvt, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_ps void @test_scalef32_sr_pk8_bf8_f16_vv(<8 x half> %src, i32 %sr, float %scale, ptr addrspace(1) %out) {
; GFX1210-SDAG-LABEL: test_scalef32_sr_pk8_bf8_f16_vv:
; GFX1210-SDAG:       ; %bb.0:
; GFX1210-SDAG-NEXT:    v_cvt_scalef32_sr_pk8_bf8_f16 v[8:9], v[0:3], v4, v5
; GFX1210-SDAG-NEXT:    global_store_b64 v[6:7], v[8:9], off
; GFX1210-SDAG-NEXT:    s_endpgm
;
; GFX1210-GISEL-LABEL: test_scalef32_sr_pk8_bf8_f16_vv:
; GFX1210-GISEL:       ; %bb.0:
; GFX1210-GISEL-NEXT:    v_cvt_scalef32_sr_pk8_bf8_f16 v[8:9], v[0:3], v4, v5
; GFX1210-GISEL-NEXT:    global_store_b64 v[6:7], v[8:9], off
; GFX1210-GISEL-NEXT:    s_endpgm
  %cvt = tail call <2 x i32> @llvm.amdgcn.cvt.scalef32.sr.pk8.bf8.f16(<8 x half> %src, i32 %sr, float %scale)
  store <2 x i32> %cvt, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_ps void @test_scalef32_sr_pk8_bf8_f16_sl(<8 x half> inreg %src, i32 inreg %sr, ptr addrspace(1) %out) {
; GFX1210-SDAG-LABEL: test_scalef32_sr_pk8_bf8_f16_sl:
; GFX1210-SDAG:       ; %bb.0:
; GFX1210-SDAG-NEXT:    v_dual_mov_b32 v2, s0 :: v_dual_mov_b32 v3, s1
; GFX1210-SDAG-NEXT:    v_dual_mov_b32 v4, s2 :: v_dual_mov_b32 v5, s3
; GFX1210-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1210-SDAG-NEXT:    v_cvt_scalef32_sr_pk8_bf8_f16 v[6:7], v[2:5], s4, 0x42c80000
; GFX1210-SDAG-NEXT:    global_store_b64 v[0:1], v[6:7], off
; GFX1210-SDAG-NEXT:    s_endpgm
;
; GFX1210-GISEL-LABEL: test_scalef32_sr_pk8_bf8_f16_sl:
; GFX1210-GISEL:       ; %bb.0:
; GFX1210-GISEL-NEXT:    v_mov_b64_e32 v[4:5], s[2:3]
; GFX1210-GISEL-NEXT:    v_mov_b64_e32 v[2:3], s[0:1]
; GFX1210-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1210-GISEL-NEXT:    v_cvt_scalef32_sr_pk8_bf8_f16 v[6:7], v[2:5], s4, 0x42c80000
; GFX1210-GISEL-NEXT:    global_store_b64 v[0:1], v[6:7], off
; GFX1210-GISEL-NEXT:    s_endpgm
  %cvt = tail call <2 x i32> @llvm.amdgcn.cvt.scalef32.sr.pk8.bf8.f16(<8 x half> %src, i32 %sr, float 100.0)
  store <2 x i32> %cvt, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_ps void @test_scalef32_sr_pk8_bf8_f32_vv(<8 x float> %src, i32 %sr, float %scale, ptr addrspace(1) %out) {
; GFX1210-SDAG-LABEL: test_scalef32_sr_pk8_bf8_f32_vv:
; GFX1210-SDAG:       ; %bb.0:
; GFX1210-SDAG-NEXT:    v_cvt_scalef32_sr_pk8_bf8_f32 v[12:13], v[0:7], v8, v9
; GFX1210-SDAG-NEXT:    global_store_b64 v[10:11], v[12:13], off
; GFX1210-SDAG-NEXT:    s_endpgm
;
; GFX1210-GISEL-LABEL: test_scalef32_sr_pk8_bf8_f32_vv:
; GFX1210-GISEL:       ; %bb.0:
; GFX1210-GISEL-NEXT:    v_cvt_scalef32_sr_pk8_bf8_f32 v[12:13], v[0:7], v8, v9
; GFX1210-GISEL-NEXT:    global_store_b64 v[10:11], v[12:13], off
; GFX1210-GISEL-NEXT:    s_endpgm
  %cvt = tail call <2 x i32> @llvm.amdgcn.cvt.scalef32.sr.pk8.bf8.f32(<8 x float> %src, i32 %sr, float %scale)
  store <2 x i32> %cvt, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_ps void @test_scalef32_sr_pk8_bf8_f32_sl(<8 x float> inreg %src, i32 inreg %sr, ptr addrspace(1) %out) {
; GFX1210-SDAG-LABEL: test_scalef32_sr_pk8_bf8_f32_sl:
; GFX1210-SDAG:       ; %bb.0:
; GFX1210-SDAG-NEXT:    v_dual_mov_b32 v2, s0 :: v_dual_mov_b32 v3, s1
; GFX1210-SDAG-NEXT:    v_dual_mov_b32 v4, s2 :: v_dual_mov_b32 v5, s3
; GFX1210-SDAG-NEXT:    v_dual_mov_b32 v6, s4 :: v_dual_mov_b32 v7, s5
; GFX1210-SDAG-NEXT:    v_dual_mov_b32 v8, s6 :: v_dual_mov_b32 v9, s7
; GFX1210-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1210-SDAG-NEXT:    v_cvt_scalef32_sr_pk8_bf8_f32 v[10:11], v[2:9], s8, 0x42c80000
; GFX1210-SDAG-NEXT:    global_store_b64 v[0:1], v[10:11], off
; GFX1210-SDAG-NEXT:    s_endpgm
;
; GFX1210-GISEL-LABEL: test_scalef32_sr_pk8_bf8_f32_sl:
; GFX1210-GISEL:       ; %bb.0:
; GFX1210-GISEL-NEXT:    v_mov_b64_e32 v[8:9], s[6:7]
; GFX1210-GISEL-NEXT:    v_mov_b64_e32 v[6:7], s[4:5]
; GFX1210-GISEL-NEXT:    v_mov_b64_e32 v[4:5], s[2:3]
; GFX1210-GISEL-NEXT:    v_mov_b64_e32 v[2:3], s[0:1]
; GFX1210-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1210-GISEL-NEXT:    v_cvt_scalef32_sr_pk8_bf8_f32 v[10:11], v[2:9], s8, 0x42c80000
; GFX1210-GISEL-NEXT:    global_store_b64 v[0:1], v[10:11], off
; GFX1210-GISEL-NEXT:    s_endpgm
  %cvt = tail call <2 x i32> @llvm.amdgcn.cvt.scalef32.sr.pk8.bf8.f32(<8 x float> %src, i32 %sr, float 100.0)
  store <2 x i32> %cvt, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_ps void @test_scalef32_sr_pk8_fp8_f32_vv(<8 x float> %src, i32 %sr, float %scale, ptr addrspace(1) %out) {
; GFX1210-SDAG-LABEL: test_scalef32_sr_pk8_fp8_f32_vv:
; GFX1210-SDAG:       ; %bb.0:
; GFX1210-SDAG-NEXT:    v_cvt_scalef32_sr_pk8_fp8_f32 v[12:13], v[0:7], v8, v9
; GFX1210-SDAG-NEXT:    global_store_b64 v[10:11], v[12:13], off
; GFX1210-SDAG-NEXT:    s_endpgm
;
; GFX1210-GISEL-LABEL: test_scalef32_sr_pk8_fp8_f32_vv:
; GFX1210-GISEL:       ; %bb.0:
; GFX1210-GISEL-NEXT:    v_cvt_scalef32_sr_pk8_fp8_f32 v[12:13], v[0:7], v8, v9
; GFX1210-GISEL-NEXT:    global_store_b64 v[10:11], v[12:13], off
; GFX1210-GISEL-NEXT:    s_endpgm
  %cvt = tail call <2 x i32> @llvm.amdgcn.cvt.scalef32.sr.pk8.fp8.f32(<8 x float> %src, i32 %sr, float %scale)
  store <2 x i32> %cvt, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_ps void @test_scalef32_sr_pk8_fp8_f32_sl(<8 x float> inreg %src, i32 inreg %sr, ptr addrspace(1) %out) {
; GFX1210-SDAG-LABEL: test_scalef32_sr_pk8_fp8_f32_sl:
; GFX1210-SDAG:       ; %bb.0:
; GFX1210-SDAG-NEXT:    v_dual_mov_b32 v2, s0 :: v_dual_mov_b32 v3, s1
; GFX1210-SDAG-NEXT:    v_dual_mov_b32 v4, s2 :: v_dual_mov_b32 v5, s3
; GFX1210-SDAG-NEXT:    v_dual_mov_b32 v6, s4 :: v_dual_mov_b32 v7, s5
; GFX1210-SDAG-NEXT:    v_dual_mov_b32 v8, s6 :: v_dual_mov_b32 v9, s7
; GFX1210-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1210-SDAG-NEXT:    v_cvt_scalef32_sr_pk8_fp8_f32 v[10:11], v[2:9], s8, 0x42c80000
; GFX1210-SDAG-NEXT:    global_store_b64 v[0:1], v[10:11], off
; GFX1210-SDAG-NEXT:    s_endpgm
;
; GFX1210-GISEL-LABEL: test_scalef32_sr_pk8_fp8_f32_sl:
; GFX1210-GISEL:       ; %bb.0:
; GFX1210-GISEL-NEXT:    v_mov_b64_e32 v[8:9], s[6:7]
; GFX1210-GISEL-NEXT:    v_mov_b64_e32 v[6:7], s[4:5]
; GFX1210-GISEL-NEXT:    v_mov_b64_e32 v[4:5], s[2:3]
; GFX1210-GISEL-NEXT:    v_mov_b64_e32 v[2:3], s[0:1]
; GFX1210-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1210-GISEL-NEXT:    v_cvt_scalef32_sr_pk8_fp8_f32 v[10:11], v[2:9], s8, 0x42c80000
; GFX1210-GISEL-NEXT:    global_store_b64 v[0:1], v[10:11], off
; GFX1210-GISEL-NEXT:    s_endpgm
  %cvt = tail call <2 x i32> @llvm.amdgcn.cvt.scalef32.sr.pk8.fp8.f32(<8 x float> %src, i32 %sr, float 100.0)
  store <2 x i32> %cvt, ptr addrspace(1) %out, align 8
  ret void
}

define amdgpu_ps void @test_scalef32_sr_pk8_fp4_f32_vv(<8 x float> %src, i32 %sr, float %scale, ptr addrspace(1) %out) {
; GFX1210-SDAG-LABEL: test_scalef32_sr_pk8_fp4_f32_vv:
; GFX1210-SDAG:       ; %bb.0:
; GFX1210-SDAG-NEXT:    v_cvt_scalef32_sr_pk8_fp4_f32 v12, v[0:7], v8, v9
; GFX1210-SDAG-NEXT:    global_store_b32 v[10:11], v12, off
; GFX1210-SDAG-NEXT:    s_endpgm
;
; GFX1210-GISEL-LABEL: test_scalef32_sr_pk8_fp4_f32_vv:
; GFX1210-GISEL:       ; %bb.0:
; GFX1210-GISEL-NEXT:    v_cvt_scalef32_sr_pk8_fp4_f32 v12, v[0:7], v8, v9
; GFX1210-GISEL-NEXT:    global_store_b32 v[10:11], v12, off
; GFX1210-GISEL-NEXT:    s_endpgm
  %cvt = tail call i32 @llvm.amdgcn.cvt.scalef32.sr.pk8.fp4.f32(<8 x float> %src, i32 %sr, float %scale)
  store i32 %cvt, ptr addrspace(1) %out, align 4
  ret void
}

define amdgpu_ps void @test_scalef32_sr_pk8_fp4_f32_sl(<8 x float> inreg %src, i32 inreg %sr, ptr addrspace(1) %out) {
; GFX1210-SDAG-LABEL: test_scalef32_sr_pk8_fp4_f32_sl:
; GFX1210-SDAG:       ; %bb.0:
; GFX1210-SDAG-NEXT:    v_dual_mov_b32 v2, s0 :: v_dual_mov_b32 v3, s1
; GFX1210-SDAG-NEXT:    v_dual_mov_b32 v4, s2 :: v_dual_mov_b32 v5, s3
; GFX1210-SDAG-NEXT:    v_dual_mov_b32 v6, s4 :: v_dual_mov_b32 v7, s5
; GFX1210-SDAG-NEXT:    v_dual_mov_b32 v8, s6 :: v_dual_mov_b32 v9, s7
; GFX1210-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1210-SDAG-NEXT:    v_cvt_scalef32_sr_pk8_fp4_f32 v10, v[2:9], s8, 0x42c80000
; GFX1210-SDAG-NEXT:    global_store_b32 v[0:1], v10, off
; GFX1210-SDAG-NEXT:    s_endpgm
;
; GFX1210-GISEL-LABEL: test_scalef32_sr_pk8_fp4_f32_sl:
; GFX1210-GISEL:       ; %bb.0:
; GFX1210-GISEL-NEXT:    v_mov_b64_e32 v[8:9], s[6:7]
; GFX1210-GISEL-NEXT:    v_mov_b64_e32 v[6:7], s[4:5]
; GFX1210-GISEL-NEXT:    v_mov_b64_e32 v[4:5], s[2:3]
; GFX1210-GISEL-NEXT:    v_mov_b64_e32 v[2:3], s[0:1]
; GFX1210-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1210-GISEL-NEXT:    v_cvt_scalef32_sr_pk8_fp4_f32 v10, v[2:9], s8, 0x42c80000
; GFX1210-GISEL-NEXT:    global_store_b32 v[0:1], v10, off
; GFX1210-GISEL-NEXT:    s_endpgm
  %cvt = tail call i32 @llvm.amdgcn.cvt.scalef32.sr.pk8.fp4.f32(<8 x float> %src, i32 %sr, float 100.0)
  store i32 %cvt, ptr addrspace(1) %out, align 4
  ret void
}

define amdgpu_ps void @test_scalef32_sr_pk8_fp4_f16_vv(<8 x half> %src, i32 %sr, float %scale, ptr addrspace(1) %out) {
; GFX1210-SDAG-LABEL: test_scalef32_sr_pk8_fp4_f16_vv:
; GFX1210-SDAG:       ; %bb.0:
; GFX1210-SDAG-NEXT:    v_cvt_scalef32_sr_pk8_fp4_f16 v8, v[0:3], v4, v5
; GFX1210-SDAG-NEXT:    global_store_b32 v[6:7], v8, off
; GFX1210-SDAG-NEXT:    s_endpgm
;
; GFX1210-GISEL-LABEL: test_scalef32_sr_pk8_fp4_f16_vv:
; GFX1210-GISEL:       ; %bb.0:
; GFX1210-GISEL-NEXT:    v_cvt_scalef32_sr_pk8_fp4_f16 v8, v[0:3], v4, v5
; GFX1210-GISEL-NEXT:    global_store_b32 v[6:7], v8, off
; GFX1210-GISEL-NEXT:    s_endpgm
  %cvt = tail call i32 @llvm.amdgcn.cvt.scalef32.sr.pk8.fp4.f16(<8 x half> %src, i32 %sr, float %scale)
  store i32 %cvt, ptr addrspace(1) %out, align 4
  ret void
}

define amdgpu_ps void @test_scalef32_sr_pk8_fp4_f16_sl(<8 x half> inreg %src, i32 inreg %sr, ptr addrspace(1) %out) {
; GFX1210-SDAG-LABEL: test_scalef32_sr_pk8_fp4_f16_sl:
; GFX1210-SDAG:       ; %bb.0:
; GFX1210-SDAG-NEXT:    v_dual_mov_b32 v2, s0 :: v_dual_mov_b32 v3, s1
; GFX1210-SDAG-NEXT:    v_dual_mov_b32 v4, s2 :: v_dual_mov_b32 v5, s3
; GFX1210-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1210-SDAG-NEXT:    v_cvt_scalef32_sr_pk8_fp4_f16 v6, v[2:5], s4, 0x42c80000
; GFX1210-SDAG-NEXT:    global_store_b32 v[0:1], v6, off
; GFX1210-SDAG-NEXT:    s_endpgm
;
; GFX1210-GISEL-LABEL: test_scalef32_sr_pk8_fp4_f16_sl:
; GFX1210-GISEL:       ; %bb.0:
; GFX1210-GISEL-NEXT:    v_mov_b64_e32 v[4:5], s[2:3]
; GFX1210-GISEL-NEXT:    v_mov_b64_e32 v[2:3], s[0:1]
; GFX1210-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1210-GISEL-NEXT:    v_cvt_scalef32_sr_pk8_fp4_f16 v6, v[2:5], s4, 0x42c80000
; GFX1210-GISEL-NEXT:    global_store_b32 v[0:1], v6, off
; GFX1210-GISEL-NEXT:    s_endpgm
  %cvt = tail call i32 @llvm.amdgcn.cvt.scalef32.sr.pk8.fp4.f16(<8 x half> %src, i32 %sr, float 100.0)
  store i32 %cvt, ptr addrspace(1) %out, align 4
  ret void
}

define amdgpu_ps void @test_scalef32_sr_pk8_fp4_bf16_vv(<8 x bfloat> %src, i32 %sr, float %scale, ptr addrspace(1) %out) {
; GFX1210-SDAG-LABEL: test_scalef32_sr_pk8_fp4_bf16_vv:
; GFX1210-SDAG:       ; %bb.0:
; GFX1210-SDAG-NEXT:    v_cvt_scalef32_sr_pk8_fp4_bf16 v8, v[0:3], v4, v5
; GFX1210-SDAG-NEXT:    global_store_b32 v[6:7], v8, off
; GFX1210-SDAG-NEXT:    s_endpgm
;
; GFX1210-GISEL-LABEL: test_scalef32_sr_pk8_fp4_bf16_vv:
; GFX1210-GISEL:       ; %bb.0:
; GFX1210-GISEL-NEXT:    v_dual_lshrrev_b32 v8, 16, v0 :: v_dual_lshrrev_b32 v9, 16, v1
; GFX1210-GISEL-NEXT:    v_dual_lshrrev_b32 v10, 16, v2 :: v_dual_lshrrev_b32 v11, 16, v3
; GFX1210-GISEL-NEXT:    v_and_b32_e32 v0, 0xffff, v0
; GFX1210-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX1210-GISEL-NEXT:    v_dual_lshlrev_b32 v8, 16, v8 :: v_dual_lshlrev_b32 v9, 16, v9
; GFX1210-GISEL-NEXT:    v_and_b32_e32 v1, 0xffff, v1
; GFX1210-GISEL-NEXT:    v_dual_lshlrev_b32 v10, 16, v10 :: v_dual_lshlrev_b32 v11, 16, v11
; GFX1210-GISEL-NEXT:    v_and_b32_e32 v2, 0xffff, v2
; GFX1210-GISEL-NEXT:    v_and_b32_e32 v3, 0xffff, v3
; GFX1210-GISEL-NEXT:    v_or_b32_e32 v0, v8, v0
; GFX1210-GISEL-NEXT:    v_or_b32_e32 v1, v9, v1
; GFX1210-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX1210-GISEL-NEXT:    v_or_b32_e32 v2, v10, v2
; GFX1210-GISEL-NEXT:    v_or_b32_e32 v3, v11, v3
; GFX1210-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1210-GISEL-NEXT:    v_cvt_scalef32_sr_pk8_fp4_bf16 v8, v[0:3], v4, v5
; GFX1210-GISEL-NEXT:    global_store_b32 v[6:7], v8, off
; GFX1210-GISEL-NEXT:    s_endpgm
  %cvt = tail call i32 @llvm.amdgcn.cvt.scalef32.sr.pk8.fp4.bf16(<8 x bfloat> %src, i32 %sr, float %scale)
  store i32 %cvt, ptr addrspace(1) %out, align 4
  ret void
}

define amdgpu_ps void @test_scalef32_sr_pk8_fp4_bf16_sl(<8 x bfloat> inreg %src, i32 inreg %sr, ptr addrspace(1) %out) {
; GFX1210-SDAG-LABEL: test_scalef32_sr_pk8_fp4_bf16_sl:
; GFX1210-SDAG:       ; %bb.0:
; GFX1210-SDAG-NEXT:    v_dual_mov_b32 v2, s0 :: v_dual_mov_b32 v3, s1
; GFX1210-SDAG-NEXT:    v_dual_mov_b32 v4, s2 :: v_dual_mov_b32 v5, s3
; GFX1210-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1210-SDAG-NEXT:    v_cvt_scalef32_sr_pk8_fp4_bf16 v6, v[2:5], s4, 0x42c80000
; GFX1210-SDAG-NEXT:    global_store_b32 v[0:1], v6, off
; GFX1210-SDAG-NEXT:    s_endpgm
;
; GFX1210-GISEL-LABEL: test_scalef32_sr_pk8_fp4_bf16_sl:
; GFX1210-GISEL:       ; %bb.0:
; GFX1210-GISEL-NEXT:    s_lshr_b32 s5, s0, 16
; GFX1210-GISEL-NEXT:    s_lshr_b32 s6, s1, 16
; GFX1210-GISEL-NEXT:    s_lshr_b32 s7, s2, 16
; GFX1210-GISEL-NEXT:    s_lshr_b32 s8, s3, 16
; GFX1210-GISEL-NEXT:    s_lshl_b32 s5, s5, 16
; GFX1210-GISEL-NEXT:    s_and_b32 s0, s0, 0xffff
; GFX1210-GISEL-NEXT:    s_lshl_b32 s6, s6, 16
; GFX1210-GISEL-NEXT:    s_and_b32 s1, s1, 0xffff
; GFX1210-GISEL-NEXT:    s_or_b32 s0, s5, s0
; GFX1210-GISEL-NEXT:    s_or_b32 s1, s6, s1
; GFX1210-GISEL-NEXT:    s_lshl_b32 s5, s7, 16
; GFX1210-GISEL-NEXT:    s_and_b32 s2, s2, 0xffff
; GFX1210-GISEL-NEXT:    s_lshl_b32 s6, s8, 16
; GFX1210-GISEL-NEXT:    s_and_b32 s3, s3, 0xffff
; GFX1210-GISEL-NEXT:    s_or_b32 s2, s5, s2
; GFX1210-GISEL-NEXT:    s_or_b32 s3, s6, s3
; GFX1210-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX1210-GISEL-NEXT:    v_mov_b64_e32 v[4:5], s[2:3]
; GFX1210-GISEL-NEXT:    v_mov_b64_e32 v[2:3], s[0:1]
; GFX1210-GISEL-NEXT:    v_cvt_scalef32_sr_pk8_fp4_bf16 v6, v[2:5], s4, 0x42c80000
; GFX1210-GISEL-NEXT:    global_store_b32 v[0:1], v6, off
; GFX1210-GISEL-NEXT:    s_endpgm
  %cvt = tail call i32 @llvm.amdgcn.cvt.scalef32.sr.pk8.fp4.bf16(<8 x bfloat> %src, i32 %sr, float 100.0)
  store i32 %cvt, ptr addrspace(1) %out, align 4
  ret void
}
