; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel=0 -march=amdgcn -mcpu=fiji -verify-machineinstrs < %s | FileCheck -check-prefixes=PRE-GFX10,VI,VI-SDAG %s
; RUN: llc -global-isel=1 -march=amdgcn -mcpu=fiji -verify-machineinstrs < %s | FileCheck -check-prefixes=PRE-GFX10,VI,VI-GISEL %s
; RUN: llc -global-isel=0 -march=amdgcn -mcpu=gfx900 -verify-machineinstrs < %s | FileCheck -check-prefixes=PRE-GFX10,GFX9,GFX9-SDAG %s
; RUN: llc -global-isel=1 -march=amdgcn -mcpu=gfx900 -verify-machineinstrs < %s | FileCheck -check-prefixes=PRE-GFX10,GFX9,GFX9-GISEL %s
; RUN: llc -global-isel=0 -march=amdgcn -mcpu=gfx1010 -mattr=+wavefrontsize32,-wavefrontsize64 -verify-machineinstrs < %s | FileCheck -check-prefixes=GFX10GFX11-SDAG,GFX10-32,GFX10-32-SDAG %s
; RUN: llc -global-isel=1 -march=amdgcn -mcpu=gfx1010 -mattr=+wavefrontsize32,-wavefrontsize64 -verify-machineinstrs < %s | FileCheck -check-prefixes=GFX10-32,GFX10-32-GISEL %s
; RUN: llc -global-isel=0 -march=amdgcn -mcpu=gfx1010 -mattr=-wavefrontsize32,+wavefrontsize64 -verify-machineinstrs < %s | FileCheck -check-prefixes=GFX10GFX11-SDAG,GFX10-64,GFX10-64-SDAG %s
; RUN: llc -global-isel=1 -march=amdgcn -mcpu=gfx1010 -mattr=-wavefrontsize32,+wavefrontsize64 -verify-machineinstrs < %s | FileCheck -check-prefixes=GFX10-64,GFX10-64-GISEL %s
; RUN: llc -global-isel=0 -march=amdgcn -mcpu=gfx1150 -mattr=-wavefrontsize32,+wavefrontsize64 -verify-machineinstrs < %s | FileCheck -check-prefixes=GFX10GFX11-SDAG,GFX1150,GFX1150-SDAG %s
; RUN: llc -global-isel=1 -march=amdgcn -mcpu=gfx1150 -mattr=-wavefrontsize32,+wavefrontsize64 -verify-machineinstrs < %s | FileCheck -check-prefixes=GFX1150,GFX1150-GISEL %s
; RUN: llc -global-isel=0 -march=amdgcn -mcpu=gfx1200 -mattr=-wavefrontsize32,+wavefrontsize64 -verify-machineinstrs < %s | FileCheck -check-prefixes=GFX12,GFX12-SDAG %s
; RUN: llc -global-isel=1 -march=amdgcn -mcpu=gfx1200 -mattr=-wavefrontsize32,+wavefrontsize64 -verify-machineinstrs < %s | FileCheck -check-prefixes=GFX12,GFX12-GISEL %s

@Lds = addrspace(3) global [16384 x i32] poison

define amdgpu_ps void @test_waterfall_readlane(i32 addrspace(1)* inreg %out, <2 x i32> addrspace(1)* inreg %in, i32 %tid) #1 {
; VI-SDAG-LABEL: test_waterfall_readlane:
; VI-SDAG:       ; %bb.0:
; VI-SDAG-NEXT:    v_ashrrev_i32_e32 v1, 31, v0
; VI-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 3, v[0:1]
; VI-SDAG-NEXT:    v_mov_b32_e32 v2, s3
; VI-SDAG-NEXT:    v_add_u32_e32 v0, vcc, s2, v0
; VI-SDAG-NEXT:    v_addc_u32_e32 v1, vcc, v2, v1, vcc
; VI-SDAG-NEXT:    flat_load_dwordx2 v[2:3], v[0:1]
; VI-SDAG-NEXT:    v_mov_b32_e32 v0, s0
; VI-SDAG-NEXT:    v_mov_b32_e32 v1, s1
; VI-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; VI-SDAG-NEXT:  .LBB0_1: ; =>This Inner Loop Header: Depth=1
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    v_readfirstlane_b32 s4, v3
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[2:3], s4, v3
; VI-SDAG-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; VI-SDAG-NEXT:    s_nop 1
; VI-SDAG-NEXT:    v_readlane_b32 s4, v2, s4
; VI-SDAG-NEXT:    v_mov_b32_e32 v4, s4
; VI-SDAG-NEXT:    ; implicit-def: $vgpr2_vgpr3
; VI-SDAG-NEXT:    s_xor_b64 exec, exec, s[2:3]
; VI-SDAG-NEXT:    s_cbranch_execnz .LBB0_1
; VI-SDAG-NEXT:  ; %bb.2:
; VI-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; VI-SDAG-NEXT:    flat_store_dword v[0:1], v4
; VI-SDAG-NEXT:    s_endpgm
;
; VI-GISEL-LABEL: test_waterfall_readlane:
; VI-GISEL:       ; %bb.0:
; VI-GISEL-NEXT:    v_ashrrev_i32_e32 v1, 31, v0
; VI-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 3, v[0:1]
; VI-GISEL-NEXT:    v_mov_b32_e32 v2, s2
; VI-GISEL-NEXT:    v_mov_b32_e32 v3, s3
; VI-GISEL-NEXT:    v_add_u32_e32 v0, vcc, v2, v0
; VI-GISEL-NEXT:    v_addc_u32_e32 v1, vcc, v3, v1, vcc
; VI-GISEL-NEXT:    flat_load_dwordx2 v[0:1], v[0:1]
; VI-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; VI-GISEL-NEXT:  .LBB0_1: ; =>This Inner Loop Header: Depth=1
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    v_readfirstlane_b32 s6, v1
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[4:5], s6, v1
; VI-GISEL-NEXT:    s_and_saveexec_b64 s[4:5], s[4:5]
; VI-GISEL-NEXT:    s_nop 1
; VI-GISEL-NEXT:    v_readlane_b32 s6, v0, s6
; VI-GISEL-NEXT:    v_mov_b32_e32 v2, s6
; VI-GISEL-NEXT:    ; implicit-def: $vgpr0_vgpr1
; VI-GISEL-NEXT:    s_xor_b64 exec, exec, s[4:5]
; VI-GISEL-NEXT:    s_cbranch_execnz .LBB0_1
; VI-GISEL-NEXT:  ; %bb.2:
; VI-GISEL-NEXT:    s_mov_b64 exec, s[2:3]
; VI-GISEL-NEXT:    v_mov_b32_e32 v0, s0
; VI-GISEL-NEXT:    v_mov_b32_e32 v1, s1
; VI-GISEL-NEXT:    flat_store_dword v[0:1], v2
; VI-GISEL-NEXT:    s_endpgm
;
; GFX9-SDAG-LABEL: test_waterfall_readlane:
; GFX9-SDAG:       ; %bb.0:
; GFX9-SDAG-NEXT:    v_ashrrev_i32_e32 v1, 31, v0
; GFX9-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 3, v[0:1]
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v2, s3
; GFX9-SDAG-NEXT:    v_add_co_u32_e32 v0, vcc, s2, v0
; GFX9-SDAG-NEXT:    v_addc_co_u32_e32 v1, vcc, v2, v1, vcc
; GFX9-SDAG-NEXT:    global_load_dwordx2 v[0:1], v[0:1], off
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v2, 0
; GFX9-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX9-SDAG-NEXT:  .LBB0_1: ; =>This Inner Loop Header: Depth=1
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s6, v1
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[4:5], s6, v1
; GFX9-SDAG-NEXT:    s_and_saveexec_b64 s[4:5], s[4:5]
; GFX9-SDAG-NEXT:    s_nop 1
; GFX9-SDAG-NEXT:    v_readlane_b32 s6, v0, s6
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v3, s6
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr0_vgpr1
; GFX9-SDAG-NEXT:    s_xor_b64 exec, exec, s[4:5]
; GFX9-SDAG-NEXT:    s_cbranch_execnz .LBB0_1
; GFX9-SDAG-NEXT:  ; %bb.2:
; GFX9-SDAG-NEXT:    s_mov_b64 exec, s[2:3]
; GFX9-SDAG-NEXT:    global_store_dword v2, v3, s[0:1]
; GFX9-SDAG-NEXT:    s_endpgm
;
; GFX9-GISEL-LABEL: test_waterfall_readlane:
; GFX9-GISEL:       ; %bb.0:
; GFX9-GISEL-NEXT:    v_ashrrev_i32_e32 v1, 31, v0
; GFX9-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 3, v[0:1]
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v2, s2
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v3, s3
; GFX9-GISEL-NEXT:    v_add_co_u32_e32 v0, vcc, v2, v0
; GFX9-GISEL-NEXT:    v_addc_co_u32_e32 v1, vcc, v3, v1, vcc
; GFX9-GISEL-NEXT:    global_load_dwordx2 v[0:1], v[0:1], off
; GFX9-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX9-GISEL-NEXT:  .LBB0_1: ; =>This Inner Loop Header: Depth=1
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s6, v1
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[4:5], s6, v1
; GFX9-GISEL-NEXT:    s_and_saveexec_b64 s[4:5], s[4:5]
; GFX9-GISEL-NEXT:    s_nop 1
; GFX9-GISEL-NEXT:    v_readlane_b32 s6, v0, s6
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v2, s6
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr0_vgpr1
; GFX9-GISEL-NEXT:    s_xor_b64 exec, exec, s[4:5]
; GFX9-GISEL-NEXT:    s_cbranch_execnz .LBB0_1
; GFX9-GISEL-NEXT:  ; %bb.2:
; GFX9-GISEL-NEXT:    s_mov_b64 exec, s[2:3]
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX9-GISEL-NEXT:    global_store_dword v0, v2, s[0:1]
; GFX9-GISEL-NEXT:    s_endpgm
;
; GFX10-32-SDAG-LABEL: test_waterfall_readlane:
; GFX10-32-SDAG:       ; %bb.0:
; GFX10-32-SDAG-NEXT:    v_ashrrev_i32_e32 v1, 31, v0
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v2, 0
; GFX10-32-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 3, v[0:1]
; GFX10-32-SDAG-NEXT:    v_add_co_u32 v0, vcc_lo, s2, v0
; GFX10-32-SDAG-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, s3, v1, vcc_lo
; GFX10-32-SDAG-NEXT:    s_mov_b32 s3, exec_lo
; GFX10-32-SDAG-NEXT:    s_mov_b32 s2, exec_lo
; GFX10-32-SDAG-NEXT:    global_load_dwordx2 v[0:1], v[0:1], off
; GFX10-32-SDAG-NEXT:  .LBB0_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s4, v1
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s4, v1
; GFX10-32-SDAG-NEXT:    v_readlane_b32 s4, v0, s4
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v3, s4
; GFX10-32-SDAG-NEXT:    s_andn2_wrexec_b32 s3, s3
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr0_vgpr1
; GFX10-32-SDAG-NEXT:    s_cbranch_execnz .LBB0_1
; GFX10-32-SDAG-NEXT:  ; %bb.2:
; GFX10-32-SDAG-NEXT:    s_mov_b32 exec_lo, s2
; GFX10-32-SDAG-NEXT:    global_store_dword v2, v3, s[0:1]
; GFX10-32-SDAG-NEXT:    s_endpgm
;
; GFX10-32-GISEL-LABEL: test_waterfall_readlane:
; GFX10-32-GISEL:       ; %bb.0:
; GFX10-32-GISEL-NEXT:    v_ashrrev_i32_e32 v1, 31, v0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v2, s2
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v3, s3
; GFX10-32-GISEL-NEXT:    s_mov_b32 s3, exec_lo
; GFX10-32-GISEL-NEXT:    s_mov_b32 s2, exec_lo
; GFX10-32-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 3, v[0:1]
; GFX10-32-GISEL-NEXT:    v_add_co_u32 v0, vcc_lo, v2, v0
; GFX10-32-GISEL-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, v3, v1, vcc_lo
; GFX10-32-GISEL-NEXT:    global_load_dwordx2 v[0:1], v[0:1], off
; GFX10-32-GISEL-NEXT:  .LBB0_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s4, v1
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s4, v1
; GFX10-32-GISEL-NEXT:    v_readlane_b32 s4, v0, s4
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v2, s4
; GFX10-32-GISEL-NEXT:    s_andn2_wrexec_b32 s3, s3
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr0_vgpr1
; GFX10-32-GISEL-NEXT:    s_cbranch_execnz .LBB0_1
; GFX10-32-GISEL-NEXT:  ; %bb.2:
; GFX10-32-GISEL-NEXT:    s_mov_b32 exec_lo, s2
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-32-GISEL-NEXT:    global_store_dword v0, v2, s[0:1]
; GFX10-32-GISEL-NEXT:    s_endpgm
;
; GFX10-64-SDAG-LABEL: test_waterfall_readlane:
; GFX10-64-SDAG:       ; %bb.0:
; GFX10-64-SDAG-NEXT:    v_ashrrev_i32_e32 v1, 31, v0
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v2, 0
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX10-64-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 3, v[0:1]
; GFX10-64-SDAG-NEXT:    v_add_co_u32 v0, vcc, s2, v0
; GFX10-64-SDAG-NEXT:    v_add_co_ci_u32_e32 v1, vcc, s3, v1, vcc
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX10-64-SDAG-NEXT:    global_load_dwordx2 v[0:1], v[0:1], off
; GFX10-64-SDAG-NEXT:  .LBB0_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s6, v1
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s6, v1
; GFX10-64-SDAG-NEXT:    v_readlane_b32 s6, v0, s6
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v3, s6
; GFX10-64-SDAG-NEXT:    s_andn2_wrexec_b64 s[4:5], s[4:5]
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr0_vgpr1
; GFX10-64-SDAG-NEXT:    s_cbranch_execnz .LBB0_1
; GFX10-64-SDAG-NEXT:  ; %bb.2:
; GFX10-64-SDAG-NEXT:    s_mov_b64 exec, s[2:3]
; GFX10-64-SDAG-NEXT:    global_store_dword v2, v3, s[0:1]
; GFX10-64-SDAG-NEXT:    s_endpgm
;
; GFX10-64-GISEL-LABEL: test_waterfall_readlane:
; GFX10-64-GISEL:       ; %bb.0:
; GFX10-64-GISEL-NEXT:    v_ashrrev_i32_e32 v1, 31, v0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v2, s2
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v3, s3
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX10-64-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 3, v[0:1]
; GFX10-64-GISEL-NEXT:    v_add_co_u32 v0, vcc, v2, v0
; GFX10-64-GISEL-NEXT:    v_add_co_ci_u32_e32 v1, vcc, v3, v1, vcc
; GFX10-64-GISEL-NEXT:    global_load_dwordx2 v[0:1], v[0:1], off
; GFX10-64-GISEL-NEXT:  .LBB0_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s6, v1
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s6, v1
; GFX10-64-GISEL-NEXT:    v_readlane_b32 s6, v0, s6
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v2, s6
; GFX10-64-GISEL-NEXT:    s_andn2_wrexec_b64 s[4:5], s[4:5]
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr0_vgpr1
; GFX10-64-GISEL-NEXT:    s_cbranch_execnz .LBB0_1
; GFX10-64-GISEL-NEXT:  ; %bb.2:
; GFX10-64-GISEL-NEXT:    s_mov_b64 exec, s[2:3]
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-64-GISEL-NEXT:    global_store_dword v0, v2, s[0:1]
; GFX10-64-GISEL-NEXT:    s_endpgm
;
; GFX1150-SDAG-LABEL: test_waterfall_readlane:
; GFX1150-SDAG:       ; %bb.0:
; GFX1150-SDAG-NEXT:    v_ashrrev_i32_e32 v1, 31, v0
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v2, 0
; GFX1150-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX1150-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 3, v[0:1]
; GFX1150-SDAG-NEXT:    v_add_co_u32 v0, vcc, s2, v0
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1150-SDAG-NEXT:    v_add_co_ci_u32_e64 v1, null, s3, v1, vcc
; GFX1150-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX1150-SDAG-NEXT:    global_load_b64 v[0:1], v[0:1], off
; GFX1150-SDAG-NEXT:  .LBB0_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s6, v1
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s6, v1
; GFX1150-SDAG-NEXT:    v_readlane_b32 s6, v0, s6
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v3, s6
; GFX1150-SDAG-NEXT:    s_and_not1_wrexec_b64 s[4:5], s[4:5]
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr0_vgpr1
; GFX1150-SDAG-NEXT:    s_cbranch_execnz .LBB0_1
; GFX1150-SDAG-NEXT:  ; %bb.2:
; GFX1150-SDAG-NEXT:    s_mov_b64 exec, s[2:3]
; GFX1150-SDAG-NEXT:    global_store_b32 v2, v3, s[0:1]
; GFX1150-SDAG-NEXT:    s_endpgm
;
; GFX1150-GISEL-LABEL: test_waterfall_readlane:
; GFX1150-GISEL:       ; %bb.0:
; GFX1150-GISEL-NEXT:    v_ashrrev_i32_e32 v1, 31, v0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v2, s2
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v3, s3
; GFX1150-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX1150-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX1150-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 3, v[0:1]
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX1150-GISEL-NEXT:    v_add_co_u32 v0, vcc, v2, v0
; GFX1150-GISEL-NEXT:    v_add_co_ci_u32_e64 v1, null, v3, v1, vcc
; GFX1150-GISEL-NEXT:    global_load_b64 v[0:1], v[0:1], off
; GFX1150-GISEL-NEXT:  .LBB0_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s6, v1
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s6, v1
; GFX1150-GISEL-NEXT:    v_readlane_b32 s6, v0, s6
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v2, s6
; GFX1150-GISEL-NEXT:    s_and_not1_wrexec_b64 s[4:5], s[4:5]
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr0_vgpr1
; GFX1150-GISEL-NEXT:    s_cbranch_execnz .LBB0_1
; GFX1150-GISEL-NEXT:  ; %bb.2:
; GFX1150-GISEL-NEXT:    s_mov_b64 exec, s[2:3]
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX1150-GISEL-NEXT:    global_store_b32 v0, v2, s[0:1]
; GFX1150-GISEL-NEXT:    s_endpgm
;
; GFX12-SDAG-LABEL: test_waterfall_readlane:
; GFX12-SDAG:       ; %bb.0:
; GFX12-SDAG-NEXT:    v_ashrrev_i32_e32 v1, 31, v0
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v2, 0
; GFX12-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX12-SDAG-NEXT:    v_lshlrev_b64_e32 v[0:1], 3, v[0:1]
; GFX12-SDAG-NEXT:    v_add_co_u32 v0, vcc, s2, v0
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX12-SDAG-NEXT:    v_add_co_ci_u32_e64 v1, null, s3, v1, vcc
; GFX12-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX12-SDAG-NEXT:    global_load_b64 v[0:1], v[0:1], off
; GFX12-SDAG-NEXT:  .LBB0_1: ; =>This Inner Loop Header: Depth=1
; GFX12-SDAG-NEXT:    s_wait_loadcnt 0x0
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s6, v1
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_1)
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s6, v1
; GFX12-SDAG-NEXT:    v_readlane_b32 s6, v0, s6
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v3, s6
; GFX12-SDAG-NEXT:    s_and_not1_wrexec_b64 s[4:5], s[4:5]
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr0_vgpr1
; GFX12-SDAG-NEXT:    s_cbranch_execnz .LBB0_1
; GFX12-SDAG-NEXT:  ; %bb.2:
; GFX12-SDAG-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-SDAG-NEXT:    s_mov_b64 exec, s[2:3]
; GFX12-SDAG-NEXT:    global_store_b32 v2, v3, s[0:1]
; GFX12-SDAG-NEXT:    s_endpgm
;
; GFX12-GISEL-LABEL: test_waterfall_readlane:
; GFX12-GISEL:       ; %bb.0:
; GFX12-GISEL-NEXT:    v_ashrrev_i32_e32 v1, 31, v0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v2, s2
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v3, s3
; GFX12-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX12-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX12-GISEL-NEXT:    v_lshlrev_b64_e32 v[0:1], 3, v[0:1]
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX12-GISEL-NEXT:    v_add_co_u32 v0, vcc, v2, v0
; GFX12-GISEL-NEXT:    v_add_co_ci_u32_e64 v1, null, v3, v1, vcc
; GFX12-GISEL-NEXT:    global_load_b64 v[0:1], v[0:1], off
; GFX12-GISEL-NEXT:  .LBB0_1: ; =>This Inner Loop Header: Depth=1
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x0
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s6, v1
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_1)
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s6, v1
; GFX12-GISEL-NEXT:    v_readlane_b32 s6, v0, s6
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v2, s6
; GFX12-GISEL-NEXT:    s_and_not1_wrexec_b64 s[4:5], s[4:5]
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr0_vgpr1
; GFX12-GISEL-NEXT:    s_cbranch_execnz .LBB0_1
; GFX12-GISEL-NEXT:  ; %bb.2:
; GFX12-GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-GISEL-NEXT:    s_mov_b64 exec, s[2:3]
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX12-GISEL-NEXT:    global_store_b32 v0, v2, s[0:1]
; GFX12-GISEL-NEXT:    s_endpgm
  %gep.in = getelementptr <2 x i32>, <2 x i32> addrspace(1)* %in, i32 %tid
  %args = load <2 x i32>, <2 x i32> addrspace(1)* %gep.in
  %value = extractelement <2 x i32> %args, i32 0
  %lane = extractelement <2 x i32> %args, i32 1
  %wf_token = call token @llvm.amdgcn.waterfall.begin.i32(token poison, i32 %lane)
  %readlane = call i32 @llvm.amdgcn.waterfall.readfirstlane.i32.i32(token %wf_token, i32 %lane)
  %readlane1 = call i32 @llvm.amdgcn.readlane(i32 %value, i32 %readlane)
  %readlane2 = call i32 @llvm.amdgcn.waterfall.end.i32(token %wf_token, i32 %readlane1)
  ; This store instruction should be outside the waterfall loop and the value
  ; being stored generated incrementally in the loop itself
  store i32 %readlane2, i32 addrspace(1)* %out, align 4

  ret void
}

define amdgpu_ps <4 x float> @test_waterfall_non_uniform_img(<8 x i32> addrspace(4)* inreg %in, i32 %index, float %s, <4 x i32> inreg %samp) #1 {
; VI-SDAG-LABEL: test_waterfall_non_uniform_img:
; VI-SDAG:       ; %bb.0:
; VI-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; VI-SDAG-NEXT:    s_wqm_b64 exec, exec
; VI-SDAG-NEXT:    s_mov_b32 s7, s5
; VI-SDAG-NEXT:    s_mov_b32 s6, s4
; VI-SDAG-NEXT:    s_mov_b32 s5, s3
; VI-SDAG-NEXT:    s_mov_b32 s4, s2
; VI-SDAG-NEXT:    v_mov_b32_e32 v4, v1
; VI-SDAG-NEXT:    v_mov_b32_e32 v5, v0
; VI-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; VI-SDAG-NEXT:  .LBB1_1: ; =>This Inner Loop Header: Depth=1
; VI-SDAG-NEXT:    v_readfirstlane_b32 s10, v5
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[12:13], s10, v5
; VI-SDAG-NEXT:    s_and_saveexec_b64 s[20:21], s[12:13]
; VI-SDAG-NEXT:    s_ashr_i32 s11, s10, 31
; VI-SDAG-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; VI-SDAG-NEXT:    s_add_u32 s10, s0, s10
; VI-SDAG-NEXT:    s_addc_u32 s11, s1, s11
; VI-SDAG-NEXT:    s_load_dwordx8 s[12:19], s[10:11], 0x0
; VI-SDAG-NEXT:    ; implicit-def: $vgpr5
; VI-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; VI-SDAG-NEXT:    image_sample v[0:3], v4, s[12:19], s[4:7] dmask:0xf
; VI-SDAG-NEXT:    ; implicit-def: $vgpr4
; VI-SDAG-NEXT:    s_xor_b64 exec, exec, s[20:21]
; VI-SDAG-NEXT:    s_cbranch_execnz .LBB1_1
; VI-SDAG-NEXT:  ; %bb.2:
; VI-SDAG-NEXT:    s_mov_b64 exec, s[2:3]
; VI-SDAG-NEXT:    s_and_b64 exec, exec, s[8:9]
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    ; return to shader part epilog
;
; VI-GISEL-LABEL: test_waterfall_non_uniform_img:
; VI-GISEL:       ; %bb.0:
; VI-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; VI-GISEL-NEXT:    s_wqm_b64 exec, exec
; VI-GISEL-NEXT:    v_mov_b32_e32 v5, v0
; VI-GISEL-NEXT:    v_mov_b32_e32 v4, v1
; VI-GISEL-NEXT:    s_mov_b32 s8, s2
; VI-GISEL-NEXT:    s_mov_b32 s9, s3
; VI-GISEL-NEXT:    s_mov_b32 s10, s4
; VI-GISEL-NEXT:    s_mov_b32 s11, s5
; VI-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; VI-GISEL-NEXT:  .LBB1_1: ; =>This Inner Loop Header: Depth=1
; VI-GISEL-NEXT:    v_readfirstlane_b32 s4, v5
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[12:13], s4, v5
; VI-GISEL-NEXT:    s_and_saveexec_b64 s[20:21], s[12:13]
; VI-GISEL-NEXT:    s_ashr_i32 s5, s4, 31
; VI-GISEL-NEXT:    s_lshl_b64 s[4:5], s[4:5], 5
; VI-GISEL-NEXT:    s_add_u32 s4, s0, s4
; VI-GISEL-NEXT:    s_addc_u32 s5, s1, s5
; VI-GISEL-NEXT:    s_load_dwordx8 s[12:19], s[4:5], 0x0
; VI-GISEL-NEXT:    ; implicit-def: $vgpr5
; VI-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; VI-GISEL-NEXT:    image_sample v[0:3], v4, s[12:19], s[8:11] dmask:0xf
; VI-GISEL-NEXT:    ; implicit-def: $vgpr4
; VI-GISEL-NEXT:    s_xor_b64 exec, exec, s[20:21]
; VI-GISEL-NEXT:    s_cbranch_execnz .LBB1_1
; VI-GISEL-NEXT:  ; %bb.2:
; VI-GISEL-NEXT:    s_mov_b64 exec, s[2:3]
; VI-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    ; return to shader part epilog
;
; GFX9-SDAG-LABEL: test_waterfall_non_uniform_img:
; GFX9-SDAG:       ; %bb.0:
; GFX9-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX9-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX9-SDAG-NEXT:    s_mov_b32 s7, s5
; GFX9-SDAG-NEXT:    s_mov_b32 s6, s4
; GFX9-SDAG-NEXT:    s_mov_b32 s5, s3
; GFX9-SDAG-NEXT:    s_mov_b32 s4, s2
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v4, v1
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v5, v0
; GFX9-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX9-SDAG-NEXT:  .LBB1_1: ; =>This Inner Loop Header: Depth=1
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s10, v5
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[12:13], s10, v5
; GFX9-SDAG-NEXT:    s_and_saveexec_b64 s[20:21], s[12:13]
; GFX9-SDAG-NEXT:    s_ashr_i32 s11, s10, 31
; GFX9-SDAG-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; GFX9-SDAG-NEXT:    s_add_u32 s10, s0, s10
; GFX9-SDAG-NEXT:    s_addc_u32 s11, s1, s11
; GFX9-SDAG-NEXT:    s_load_dwordx8 s[12:19], s[10:11], 0x0
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX9-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; GFX9-SDAG-NEXT:    image_sample v[0:3], v4, s[12:19], s[4:7] dmask:0xf
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX9-SDAG-NEXT:    s_xor_b64 exec, exec, s[20:21]
; GFX9-SDAG-NEXT:    s_cbranch_execnz .LBB1_1
; GFX9-SDAG-NEXT:  ; %bb.2:
; GFX9-SDAG-NEXT:    s_mov_b64 exec, s[2:3]
; GFX9-SDAG-NEXT:    s_and_b64 exec, exec, s[8:9]
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    ; return to shader part epilog
;
; GFX9-GISEL-LABEL: test_waterfall_non_uniform_img:
; GFX9-GISEL:       ; %bb.0:
; GFX9-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX9-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v5, v0
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v4, v1
; GFX9-GISEL-NEXT:    s_mov_b32 s8, s2
; GFX9-GISEL-NEXT:    s_mov_b32 s9, s3
; GFX9-GISEL-NEXT:    s_mov_b32 s10, s4
; GFX9-GISEL-NEXT:    s_mov_b32 s11, s5
; GFX9-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX9-GISEL-NEXT:  .LBB1_1: ; =>This Inner Loop Header: Depth=1
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s4, v5
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[12:13], s4, v5
; GFX9-GISEL-NEXT:    s_and_saveexec_b64 s[20:21], s[12:13]
; GFX9-GISEL-NEXT:    s_ashr_i32 s5, s4, 31
; GFX9-GISEL-NEXT:    s_lshl_b64 s[4:5], s[4:5], 5
; GFX9-GISEL-NEXT:    s_add_u32 s4, s0, s4
; GFX9-GISEL-NEXT:    s_addc_u32 s5, s1, s5
; GFX9-GISEL-NEXT:    s_load_dwordx8 s[12:19], s[4:5], 0x0
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX9-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; GFX9-GISEL-NEXT:    image_sample v[0:3], v4, s[12:19], s[8:11] dmask:0xf
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX9-GISEL-NEXT:    s_xor_b64 exec, exec, s[20:21]
; GFX9-GISEL-NEXT:    s_cbranch_execnz .LBB1_1
; GFX9-GISEL-NEXT:  ; %bb.2:
; GFX9-GISEL-NEXT:    s_mov_b64 exec, s[2:3]
; GFX9-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-32-SDAG-LABEL: test_waterfall_non_uniform_img:
; GFX10-32-SDAG:       ; %bb.0:
; GFX10-32-SDAG-NEXT:    s_mov_b32 s8, exec_lo
; GFX10-32-SDAG-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v4, v1
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v5, v0
; GFX10-32-SDAG-NEXT:    s_mov_b32 s7, s5
; GFX10-32-SDAG-NEXT:    s_mov_b32 s6, s4
; GFX10-32-SDAG-NEXT:    s_mov_b32 s5, s3
; GFX10-32-SDAG-NEXT:    s_mov_b32 s4, s2
; GFX10-32-SDAG-NEXT:    s_mov_b32 s3, exec_lo
; GFX10-32-SDAG-NEXT:    s_mov_b32 s2, exec_lo
; GFX10-32-SDAG-NEXT:  .LBB1_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s10, v5
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s10, v5
; GFX10-32-SDAG-NEXT:    s_ashr_i32 s11, s10, 31
; GFX10-32-SDAG-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; GFX10-32-SDAG-NEXT:    s_add_u32 s10, s0, s10
; GFX10-32-SDAG-NEXT:    s_addc_u32 s11, s1, s11
; GFX10-32-SDAG-NEXT:    s_load_dwordx8 s[12:19], s[10:11], 0x0
; GFX10-32-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-32-SDAG-NEXT:    image_sample v[0:3], v4, s[12:19], s[4:7] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX10-32-SDAG-NEXT:    s_andn2_wrexec_b32 s3, s3
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX10-32-SDAG-NEXT:    s_cbranch_execnz .LBB1_1
; GFX10-32-SDAG-NEXT:  ; %bb.2:
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-SDAG-NEXT:    s_mov_b32 exec_lo, s2
; GFX10-32-SDAG-NEXT:    s_and_b32 exec_lo, exec_lo, s8
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-32-GISEL-LABEL: test_waterfall_non_uniform_img:
; GFX10-32-GISEL:       ; %bb.0:
; GFX10-32-GISEL-NEXT:    s_mov_b32 s6, exec_lo
; GFX10-32-GISEL-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v5, v0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v4, v1
; GFX10-32-GISEL-NEXT:    s_mov_b32 s8, s2
; GFX10-32-GISEL-NEXT:    s_mov_b32 s9, s3
; GFX10-32-GISEL-NEXT:    s_mov_b32 s10, s4
; GFX10-32-GISEL-NEXT:    s_mov_b32 s11, s5
; GFX10-32-GISEL-NEXT:    s_mov_b32 s3, exec_lo
; GFX10-32-GISEL-NEXT:    s_mov_b32 s2, exec_lo
; GFX10-32-GISEL-NEXT:  .LBB1_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s4, v5
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s4, v5
; GFX10-32-GISEL-NEXT:    s_ashr_i32 s5, s4, 31
; GFX10-32-GISEL-NEXT:    s_lshl_b64 s[4:5], s[4:5], 5
; GFX10-32-GISEL-NEXT:    s_add_u32 s4, s0, s4
; GFX10-32-GISEL-NEXT:    s_addc_u32 s5, s1, s5
; GFX10-32-GISEL-NEXT:    s_load_dwordx8 s[12:19], s[4:5], 0x0
; GFX10-32-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-32-GISEL-NEXT:    image_sample v[0:3], v4, s[12:19], s[8:11] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX10-32-GISEL-NEXT:    s_andn2_wrexec_b32 s3, s3
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX10-32-GISEL-NEXT:    s_cbranch_execnz .LBB1_1
; GFX10-32-GISEL-NEXT:  ; %bb.2:
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-GISEL-NEXT:    s_mov_b32 exec_lo, s2
; GFX10-32-GISEL-NEXT:    s_and_b32 exec_lo, exec_lo, s6
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-64-SDAG-LABEL: test_waterfall_non_uniform_img:
; GFX10-64-SDAG:       ; %bb.0:
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX10-64-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v4, v1
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v5, v0
; GFX10-64-SDAG-NEXT:    s_mov_b32 s7, s5
; GFX10-64-SDAG-NEXT:    s_mov_b32 s6, s4
; GFX10-64-SDAG-NEXT:    s_mov_b32 s5, s3
; GFX10-64-SDAG-NEXT:    s_mov_b32 s4, s2
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[10:11], exec
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX10-64-SDAG-NEXT:  .LBB1_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s12, v5
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s12, v5
; GFX10-64-SDAG-NEXT:    s_ashr_i32 s13, s12, 31
; GFX10-64-SDAG-NEXT:    s_lshl_b64 s[12:13], s[12:13], 5
; GFX10-64-SDAG-NEXT:    s_add_u32 s12, s0, s12
; GFX10-64-SDAG-NEXT:    s_addc_u32 s13, s1, s13
; GFX10-64-SDAG-NEXT:    s_load_dwordx8 s[12:19], s[12:13], 0x0
; GFX10-64-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-64-SDAG-NEXT:    image_sample v[0:3], v4, s[12:19], s[4:7] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX10-64-SDAG-NEXT:    s_andn2_wrexec_b64 s[10:11], s[10:11]
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX10-64-SDAG-NEXT:    s_cbranch_execnz .LBB1_1
; GFX10-64-SDAG-NEXT:  ; %bb.2:
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-SDAG-NEXT:    s_mov_b64 exec, s[2:3]
; GFX10-64-SDAG-NEXT:    s_and_b64 exec, exec, s[8:9]
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-64-GISEL-LABEL: test_waterfall_non_uniform_img:
; GFX10-64-GISEL:       ; %bb.0:
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX10-64-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v5, v0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v4, v1
; GFX10-64-GISEL-NEXT:    s_mov_b32 s8, s2
; GFX10-64-GISEL-NEXT:    s_mov_b32 s9, s3
; GFX10-64-GISEL-NEXT:    s_mov_b32 s10, s4
; GFX10-64-GISEL-NEXT:    s_mov_b32 s11, s5
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX10-64-GISEL-NEXT:  .LBB1_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s12, v5
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s12, v5
; GFX10-64-GISEL-NEXT:    s_ashr_i32 s13, s12, 31
; GFX10-64-GISEL-NEXT:    s_lshl_b64 s[12:13], s[12:13], 5
; GFX10-64-GISEL-NEXT:    s_add_u32 s12, s0, s12
; GFX10-64-GISEL-NEXT:    s_addc_u32 s13, s1, s13
; GFX10-64-GISEL-NEXT:    s_load_dwordx8 s[12:19], s[12:13], 0x0
; GFX10-64-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-64-GISEL-NEXT:    image_sample v[0:3], v4, s[12:19], s[8:11] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX10-64-GISEL-NEXT:    s_andn2_wrexec_b64 s[4:5], s[4:5]
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX10-64-GISEL-NEXT:    s_cbranch_execnz .LBB1_1
; GFX10-64-GISEL-NEXT:  ; %bb.2:
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-GISEL-NEXT:    s_mov_b64 exec, s[2:3]
; GFX10-64-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:    ; return to shader part epilog
;
; GFX1150-SDAG-LABEL: test_waterfall_non_uniform_img:
; GFX1150-SDAG:       ; %bb.0:
; GFX1150-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX1150-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v4, v1
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v5, v0
; GFX1150-SDAG-NEXT:    s_mov_b32 s7, s5
; GFX1150-SDAG-NEXT:    s_mov_b32 s6, s4
; GFX1150-SDAG-NEXT:    s_mov_b32 s5, s3
; GFX1150-SDAG-NEXT:    s_mov_b32 s4, s2
; GFX1150-SDAG-NEXT:    s_mov_b64 s[10:11], exec
; GFX1150-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX1150-SDAG-NEXT:  .LBB1_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s12, v5
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(SALU_CYCLE_1)
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s12, v5
; GFX1150-SDAG-NEXT:    s_ashr_i32 s13, s12, 31
; GFX1150-SDAG-NEXT:    s_lshl_b64 s[12:13], s[12:13], 5
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-SDAG-NEXT:    s_add_u32 s12, s0, s12
; GFX1150-SDAG-NEXT:    s_addc_u32 s13, s1, s13
; GFX1150-SDAG-NEXT:    s_load_b256 s[12:19], s[12:13], 0x0
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX1150-SDAG-NEXT:    image_sample v[0:3], v4, s[12:19], s[4:7] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX1150-SDAG-NEXT:    s_and_not1_wrexec_b64 s[10:11], s[10:11]
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX1150-SDAG-NEXT:    s_cbranch_execnz .LBB1_1
; GFX1150-SDAG-NEXT:  ; %bb.2:
; GFX1150-SDAG-NEXT:    s_mov_b64 exec, s[2:3]
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-SDAG-NEXT:    s_and_b64 exec, exec, s[8:9]
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:    ; return to shader part epilog
;
; GFX1150-GISEL-LABEL: test_waterfall_non_uniform_img:
; GFX1150-GISEL:       ; %bb.0:
; GFX1150-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX1150-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v5, v0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v4, v1
; GFX1150-GISEL-NEXT:    s_mov_b32 s8, s2
; GFX1150-GISEL-NEXT:    s_mov_b32 s9, s3
; GFX1150-GISEL-NEXT:    s_mov_b32 s10, s4
; GFX1150-GISEL-NEXT:    s_mov_b32 s11, s5
; GFX1150-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX1150-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX1150-GISEL-NEXT:  .LBB1_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s12, v5
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(SALU_CYCLE_1)
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s12, v5
; GFX1150-GISEL-NEXT:    s_ashr_i32 s13, s12, 31
; GFX1150-GISEL-NEXT:    s_lshl_b64 s[12:13], s[12:13], 5
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-GISEL-NEXT:    s_add_u32 s12, s0, s12
; GFX1150-GISEL-NEXT:    s_addc_u32 s13, s1, s13
; GFX1150-GISEL-NEXT:    s_load_b256 s[12:19], s[12:13], 0x0
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX1150-GISEL-NEXT:    image_sample v[0:3], v4, s[12:19], s[8:11] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX1150-GISEL-NEXT:    s_and_not1_wrexec_b64 s[4:5], s[4:5]
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX1150-GISEL-NEXT:    s_cbranch_execnz .LBB1_1
; GFX1150-GISEL-NEXT:  ; %bb.2:
; GFX1150-GISEL-NEXT:    s_mov_b64 exec, s[2:3]
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    ; return to shader part epilog
;
; GFX12-SDAG-LABEL: test_waterfall_non_uniform_img:
; GFX12-SDAG:       ; %bb.0:
; GFX12-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX12-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v4, v1
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v5, v0
; GFX12-SDAG-NEXT:    s_mov_b32 s7, s5
; GFX12-SDAG-NEXT:    s_mov_b32 s6, s4
; GFX12-SDAG-NEXT:    s_mov_b32 s5, s3
; GFX12-SDAG-NEXT:    s_mov_b32 s4, s2
; GFX12-SDAG-NEXT:    s_mov_b64 s[10:11], exec
; GFX12-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX12-SDAG-NEXT:  .LBB1_1: ; =>This Inner Loop Header: Depth=1
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s12, v5
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s12, v5
; GFX12-SDAG-NEXT:    s_ashr_i32 s13, s12, 31
; GFX12-SDAG-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-SDAG-NEXT:    s_lshl_b64 s[12:13], s[12:13], 5
; GFX12-SDAG-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-SDAG-NEXT:    s_add_nc_u64 s[12:13], s[0:1], s[12:13]
; GFX12-SDAG-NEXT:    s_load_b256 s[12:19], s[12:13], 0x0
; GFX12-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    image_sample v[0:3], v4, s[12:19], s[4:7] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX12-SDAG-NEXT:    s_and_not1_wrexec_b64 s[10:11], s[10:11]
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX12-SDAG-NEXT:    s_cbranch_execnz .LBB1_1
; GFX12-SDAG-NEXT:  ; %bb.2:
; GFX12-SDAG-NEXT:    s_mov_b64 exec, s[2:3]
; GFX12-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-SDAG-NEXT:    s_and_b64 exec, exec, s[8:9]
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    ; return to shader part epilog
;
; GFX12-GISEL-LABEL: test_waterfall_non_uniform_img:
; GFX12-GISEL:       ; %bb.0:
; GFX12-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX12-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v5, v0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v4, v1
; GFX12-GISEL-NEXT:    s_mov_b32 s8, s2
; GFX12-GISEL-NEXT:    s_mov_b32 s9, s3
; GFX12-GISEL-NEXT:    s_mov_b32 s10, s4
; GFX12-GISEL-NEXT:    s_mov_b32 s11, s5
; GFX12-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX12-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX12-GISEL-NEXT:  .LBB1_1: ; =>This Inner Loop Header: Depth=1
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s12, v5
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s12, v5
; GFX12-GISEL-NEXT:    s_ashr_i32 s13, s12, 31
; GFX12-GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-GISEL-NEXT:    s_lshl_b64 s[12:13], s[12:13], 5
; GFX12-GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-GISEL-NEXT:    s_add_co_u32 s12, s0, s12
; GFX12-GISEL-NEXT:    s_add_co_ci_u32 s13, s1, s13
; GFX12-GISEL-NEXT:    s_load_b256 s[12:19], s[12:13], 0x0
; GFX12-GISEL-NEXT:    s_wait_kmcnt 0x0
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    image_sample v[0:3], v4, s[12:19], s[8:11] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX12-GISEL-NEXT:    s_and_not1_wrexec_b64 s[4:5], s[4:5]
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX12-GISEL-NEXT:    s_cbranch_execnz .LBB1_1
; GFX12-GISEL-NEXT:  ; %bb.2:
; GFX12-GISEL-NEXT:    s_mov_b64 exec, s[2:3]
; GFX12-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    ; return to shader part epilog
  %wf_token = call token @llvm.amdgcn.waterfall.begin.i32(token poison, i32 %index)
  %s_idx = call i32 @llvm.amdgcn.waterfall.readfirstlane.i32.i32(token %wf_token, i32 %index)
  %ptr = getelementptr <8 x i32>, <8 x i32> addrspace(4)* %in, i32 %s_idx
  %rsrc = load <8 x i32>, <8 x i32> addrspace(4) * %ptr, align 32
  %r = call <4 x float> @llvm.amdgcn.image.sample.1d.v4f32.f32(i32 15, float %s, <8 x i32> %rsrc, <4 x i32> %samp, i1 0, i32 0, i32 0)
  %r1 = call <4 x float> @llvm.amdgcn.waterfall.end.v4f32(token %wf_token, <4 x float> %r)

  ret <4 x float> %r1
}

define amdgpu_ps <4 x float> @test_waterfall_non_uniform_img_single_read(<8 x i32> addrspace(4)* inreg %in, i32 %index, float %s, <4 x i32> inreg %samp) #1 {
; VI-SDAG-LABEL: test_waterfall_non_uniform_img_single_read:
; VI-SDAG:       ; %bb.0:
; VI-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; VI-SDAG-NEXT:    s_wqm_b64 exec, exec
; VI-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; VI-SDAG-NEXT:    v_ashrrev_i32_e32 v5, 31, v4
; VI-SDAG-NEXT:    v_mov_b32_e32 v6, v1
; VI-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[4:5]
; VI-SDAG-NEXT:    v_mov_b32_e32 v2, s1
; VI-SDAG-NEXT:    v_add_u32_e32 v0, vcc, s0, v0
; VI-SDAG-NEXT:    v_addc_u32_e32 v1, vcc, v2, v1, vcc
; VI-SDAG-NEXT:    v_add_u32_e32 v2, vcc, 16, v0
; VI-SDAG-NEXT:    v_addc_u32_e32 v3, vcc, 0, v1, vcc
; VI-SDAG-NEXT:    flat_load_dwordx4 v[7:10], v[0:1]
; VI-SDAG-NEXT:    flat_load_dwordx4 v[11:14], v[2:3]
; VI-SDAG-NEXT:    s_mov_b32 s7, s5
; VI-SDAG-NEXT:    s_mov_b32 s6, s4
; VI-SDAG-NEXT:    s_mov_b32 s5, s3
; VI-SDAG-NEXT:    s_mov_b32 s4, s2
; VI-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:  .LBB2_1: ; =>This Inner Loop Header: Depth=1
; VI-SDAG-NEXT:    v_readfirstlane_b32 s2, v4
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v4
; VI-SDAG-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; VI-SDAG-NEXT:    v_readfirstlane_b32 s12, v7
; VI-SDAG-NEXT:    v_readfirstlane_b32 s13, v8
; VI-SDAG-NEXT:    v_readfirstlane_b32 s14, v9
; VI-SDAG-NEXT:    v_readfirstlane_b32 s15, v10
; VI-SDAG-NEXT:    v_readfirstlane_b32 s16, v11
; VI-SDAG-NEXT:    v_readfirstlane_b32 s17, v12
; VI-SDAG-NEXT:    v_readfirstlane_b32 s18, v13
; VI-SDAG-NEXT:    v_readfirstlane_b32 s19, v14
; VI-SDAG-NEXT:    ; implicit-def: $vgpr4
; VI-SDAG-NEXT:    ; implicit-def: $vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14
; VI-SDAG-NEXT:    s_nop 4
; VI-SDAG-NEXT:    image_sample v[0:3], v6, s[12:19], s[4:7] dmask:0xf
; VI-SDAG-NEXT:    ; implicit-def: $vgpr6
; VI-SDAG-NEXT:    s_xor_b64 exec, exec, s[2:3]
; VI-SDAG-NEXT:    s_cbranch_execnz .LBB2_1
; VI-SDAG-NEXT:  ; %bb.2:
; VI-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; VI-SDAG-NEXT:    s_and_b64 exec, exec, s[8:9]
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    ; return to shader part epilog
;
; VI-GISEL-LABEL: test_waterfall_non_uniform_img_single_read:
; VI-GISEL:       ; %bb.0:
; VI-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; VI-GISEL-NEXT:    s_wqm_b64 exec, exec
; VI-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; VI-GISEL-NEXT:    v_ashrrev_i32_e32 v5, 31, v4
; VI-GISEL-NEXT:    v_mov_b32_e32 v6, v1
; VI-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[4:5]
; VI-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; VI-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; VI-GISEL-NEXT:    v_add_u32_e32 v0, vcc, v2, v0
; VI-GISEL-NEXT:    v_addc_u32_e32 v1, vcc, v3, v1, vcc
; VI-GISEL-NEXT:    v_add_u32_e32 v2, vcc, 16, v0
; VI-GISEL-NEXT:    v_addc_u32_e32 v3, vcc, 0, v1, vcc
; VI-GISEL-NEXT:    flat_load_dwordx4 v[7:10], v[0:1]
; VI-GISEL-NEXT:    flat_load_dwordx4 v[11:14], v[2:3]
; VI-GISEL-NEXT:    s_mov_b32 s8, s2
; VI-GISEL-NEXT:    s_mov_b32 s9, s3
; VI-GISEL-NEXT:    s_mov_b32 s10, s4
; VI-GISEL-NEXT:    s_mov_b32 s11, s5
; VI-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:  .LBB2_1: ; =>This Inner Loop Header: Depth=1
; VI-GISEL-NEXT:    v_readfirstlane_b32 s2, v4
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v4
; VI-GISEL-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; VI-GISEL-NEXT:    v_readfirstlane_b32 s12, v7
; VI-GISEL-NEXT:    v_readfirstlane_b32 s13, v8
; VI-GISEL-NEXT:    v_readfirstlane_b32 s14, v9
; VI-GISEL-NEXT:    v_readfirstlane_b32 s15, v10
; VI-GISEL-NEXT:    v_readfirstlane_b32 s16, v11
; VI-GISEL-NEXT:    v_readfirstlane_b32 s17, v12
; VI-GISEL-NEXT:    v_readfirstlane_b32 s18, v13
; VI-GISEL-NEXT:    v_readfirstlane_b32 s19, v14
; VI-GISEL-NEXT:    ; implicit-def: $vgpr4
; VI-GISEL-NEXT:    ; implicit-def: $vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14
; VI-GISEL-NEXT:    s_nop 4
; VI-GISEL-NEXT:    image_sample v[0:3], v6, s[12:19], s[8:11] dmask:0xf
; VI-GISEL-NEXT:    ; implicit-def: $vgpr6
; VI-GISEL-NEXT:    s_xor_b64 exec, exec, s[2:3]
; VI-GISEL-NEXT:    s_cbranch_execnz .LBB2_1
; VI-GISEL-NEXT:  ; %bb.2:
; VI-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; VI-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    ; return to shader part epilog
;
; GFX9-SDAG-LABEL: test_waterfall_non_uniform_img_single_read:
; GFX9-SDAG:       ; %bb.0:
; GFX9-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX9-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX9-SDAG-NEXT:    v_ashrrev_i32_e32 v5, 31, v4
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v6, v1
; GFX9-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[4:5]
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v2, s1
; GFX9-SDAG-NEXT:    v_add_co_u32_e32 v0, vcc, s0, v0
; GFX9-SDAG-NEXT:    v_addc_co_u32_e32 v1, vcc, v2, v1, vcc
; GFX9-SDAG-NEXT:    global_load_dwordx4 v[11:14], v[0:1], off offset:16
; GFX9-SDAG-NEXT:    global_load_dwordx4 v[7:10], v[0:1], off
; GFX9-SDAG-NEXT:    s_mov_b32 s7, s5
; GFX9-SDAG-NEXT:    s_mov_b32 s6, s4
; GFX9-SDAG-NEXT:    s_mov_b32 s5, s3
; GFX9-SDAG-NEXT:    s_mov_b32 s4, s2
; GFX9-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:  .LBB2_1: ; =>This Inner Loop Header: Depth=1
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s2, v4
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v4
; GFX9-SDAG-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s12, v7
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s13, v8
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s14, v9
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s15, v10
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s16, v11
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s17, v12
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s18, v13
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s19, v14
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14
; GFX9-SDAG-NEXT:    s_nop 4
; GFX9-SDAG-NEXT:    image_sample v[0:3], v6, s[12:19], s[4:7] dmask:0xf
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr6
; GFX9-SDAG-NEXT:    s_xor_b64 exec, exec, s[2:3]
; GFX9-SDAG-NEXT:    s_cbranch_execnz .LBB2_1
; GFX9-SDAG-NEXT:  ; %bb.2:
; GFX9-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX9-SDAG-NEXT:    s_and_b64 exec, exec, s[8:9]
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    ; return to shader part epilog
;
; GFX9-GISEL-LABEL: test_waterfall_non_uniform_img_single_read:
; GFX9-GISEL:       ; %bb.0:
; GFX9-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX9-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX9-GISEL-NEXT:    v_ashrrev_i32_e32 v5, 31, v4
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v6, v1
; GFX9-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[4:5]
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX9-GISEL-NEXT:    v_add_co_u32_e32 v0, vcc, v2, v0
; GFX9-GISEL-NEXT:    v_addc_co_u32_e32 v1, vcc, v3, v1, vcc
; GFX9-GISEL-NEXT:    global_load_dwordx4 v[7:10], v[0:1], off
; GFX9-GISEL-NEXT:    global_load_dwordx4 v[11:14], v[0:1], off offset:16
; GFX9-GISEL-NEXT:    s_mov_b32 s8, s2
; GFX9-GISEL-NEXT:    s_mov_b32 s9, s3
; GFX9-GISEL-NEXT:    s_mov_b32 s10, s4
; GFX9-GISEL-NEXT:    s_mov_b32 s11, s5
; GFX9-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:  .LBB2_1: ; =>This Inner Loop Header: Depth=1
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s2, v4
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v4
; GFX9-GISEL-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s12, v7
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s13, v8
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s14, v9
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s15, v10
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s16, v11
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s17, v12
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s18, v13
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s19, v14
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14
; GFX9-GISEL-NEXT:    s_nop 4
; GFX9-GISEL-NEXT:    image_sample v[0:3], v6, s[12:19], s[8:11] dmask:0xf
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr6
; GFX9-GISEL-NEXT:    s_xor_b64 exec, exec, s[2:3]
; GFX9-GISEL-NEXT:    s_cbranch_execnz .LBB2_1
; GFX9-GISEL-NEXT:  ; %bb.2:
; GFX9-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX9-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-32-SDAG-LABEL: test_waterfall_non_uniform_img_single_read:
; GFX10-32-SDAG:       ; %bb.0:
; GFX10-32-SDAG-NEXT:    s_mov_b32 s8, exec_lo
; GFX10-32-SDAG-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v6, v1
; GFX10-32-SDAG-NEXT:    s_mov_b32 s7, s5
; GFX10-32-SDAG-NEXT:    s_mov_b32 s6, s4
; GFX10-32-SDAG-NEXT:    s_mov_b32 s5, s3
; GFX10-32-SDAG-NEXT:    v_ashrrev_i32_e32 v5, 31, v4
; GFX10-32-SDAG-NEXT:    s_mov_b32 s4, s2
; GFX10-32-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[4:5]
; GFX10-32-SDAG-NEXT:    v_add_co_u32 v0, vcc_lo, s0, v0
; GFX10-32-SDAG-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, s1, v1, vcc_lo
; GFX10-32-SDAG-NEXT:    s_mov_b32 s1, exec_lo
; GFX10-32-SDAG-NEXT:    s_mov_b32 s0, exec_lo
; GFX10-32-SDAG-NEXT:    s_clause 0x1
; GFX10-32-SDAG-NEXT:    global_load_dwordx4 v[11:14], v[0:1], off offset:16
; GFX10-32-SDAG-NEXT:    global_load_dwordx4 v[7:10], v[0:1], off
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-SDAG-NEXT:  .LBB2_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s2, v4
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s2, v4
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s12, v7
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s13, v8
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s14, v9
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s15, v10
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s16, v11
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s17, v12
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s18, v13
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s19, v14
; GFX10-32-SDAG-NEXT:    image_sample v[0:3], v6, s[12:19], s[4:7] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX10-32-SDAG-NEXT:    s_andn2_wrexec_b32 s1, s1
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr6
; GFX10-32-SDAG-NEXT:    s_cbranch_execnz .LBB2_1
; GFX10-32-SDAG-NEXT:  ; %bb.2:
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-SDAG-NEXT:    s_mov_b32 exec_lo, s0
; GFX10-32-SDAG-NEXT:    s_and_b32 exec_lo, exec_lo, s8
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-32-GISEL-LABEL: test_waterfall_non_uniform_img_single_read:
; GFX10-32-GISEL:       ; %bb.0:
; GFX10-32-GISEL-NEXT:    s_mov_b32 s6, exec_lo
; GFX10-32-GISEL-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v6, v1
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX10-32-GISEL-NEXT:    s_mov_b32 s8, s2
; GFX10-32-GISEL-NEXT:    v_ashrrev_i32_e32 v5, 31, v4
; GFX10-32-GISEL-NEXT:    s_mov_b32 s9, s3
; GFX10-32-GISEL-NEXT:    s_mov_b32 s10, s4
; GFX10-32-GISEL-NEXT:    s_mov_b32 s11, s5
; GFX10-32-GISEL-NEXT:    s_mov_b32 s1, exec_lo
; GFX10-32-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[4:5]
; GFX10-32-GISEL-NEXT:    s_mov_b32 s0, exec_lo
; GFX10-32-GISEL-NEXT:    v_add_co_u32 v0, vcc_lo, v2, v0
; GFX10-32-GISEL-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, v3, v1, vcc_lo
; GFX10-32-GISEL-NEXT:    s_clause 0x1
; GFX10-32-GISEL-NEXT:    global_load_dwordx4 v[7:10], v[0:1], off
; GFX10-32-GISEL-NEXT:    global_load_dwordx4 v[11:14], v[0:1], off offset:16
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:  .LBB2_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s2, v4
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s2, v4
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s12, v7
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s13, v8
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s14, v9
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s15, v10
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s16, v11
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s17, v12
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s18, v13
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s19, v14
; GFX10-32-GISEL-NEXT:    image_sample v[0:3], v6, s[12:19], s[8:11] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX10-32-GISEL-NEXT:    s_andn2_wrexec_b32 s1, s1
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr6
; GFX10-32-GISEL-NEXT:    s_cbranch_execnz .LBB2_1
; GFX10-32-GISEL-NEXT:  ; %bb.2:
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-GISEL-NEXT:    s_mov_b32 exec_lo, s0
; GFX10-32-GISEL-NEXT:    s_and_b32 exec_lo, exec_lo, s6
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-64-SDAG-LABEL: test_waterfall_non_uniform_img_single_read:
; GFX10-64-SDAG:       ; %bb.0:
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX10-64-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v6, v1
; GFX10-64-SDAG-NEXT:    s_mov_b32 s7, s5
; GFX10-64-SDAG-NEXT:    s_mov_b32 s6, s4
; GFX10-64-SDAG-NEXT:    s_mov_b32 s5, s3
; GFX10-64-SDAG-NEXT:    v_ashrrev_i32_e32 v5, 31, v4
; GFX10-64-SDAG-NEXT:    s_mov_b32 s4, s2
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX10-64-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[4:5]
; GFX10-64-SDAG-NEXT:    v_add_co_u32 v0, vcc, s0, v0
; GFX10-64-SDAG-NEXT:    v_add_co_ci_u32_e32 v1, vcc, s1, v1, vcc
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX10-64-SDAG-NEXT:    s_clause 0x1
; GFX10-64-SDAG-NEXT:    global_load_dwordx4 v[11:14], v[0:1], off offset:16
; GFX10-64-SDAG-NEXT:    global_load_dwordx4 v[7:10], v[0:1], off
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-SDAG-NEXT:  .LBB2_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s10, v4
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s10, v4
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s12, v7
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s13, v8
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s14, v9
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s15, v10
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s16, v11
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s17, v12
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s18, v13
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s19, v14
; GFX10-64-SDAG-NEXT:    image_sample v[0:3], v6, s[12:19], s[4:7] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX10-64-SDAG-NEXT:    s_andn2_wrexec_b64 s[2:3], s[2:3]
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr6
; GFX10-64-SDAG-NEXT:    s_cbranch_execnz .LBB2_1
; GFX10-64-SDAG-NEXT:  ; %bb.2:
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX10-64-SDAG-NEXT:    s_and_b64 exec, exec, s[8:9]
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-64-GISEL-LABEL: test_waterfall_non_uniform_img_single_read:
; GFX10-64-GISEL:       ; %bb.0:
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX10-64-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v6, v1
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX10-64-GISEL-NEXT:    s_mov_b32 s8, s2
; GFX10-64-GISEL-NEXT:    v_ashrrev_i32_e32 v5, 31, v4
; GFX10-64-GISEL-NEXT:    s_mov_b32 s9, s3
; GFX10-64-GISEL-NEXT:    s_mov_b32 s10, s4
; GFX10-64-GISEL-NEXT:    s_mov_b32 s11, s5
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX10-64-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[4:5]
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX10-64-GISEL-NEXT:    v_add_co_u32 v0, vcc, v2, v0
; GFX10-64-GISEL-NEXT:    v_add_co_ci_u32_e32 v1, vcc, v3, v1, vcc
; GFX10-64-GISEL-NEXT:    s_clause 0x1
; GFX10-64-GISEL-NEXT:    global_load_dwordx4 v[7:10], v[0:1], off
; GFX10-64-GISEL-NEXT:    global_load_dwordx4 v[11:14], v[0:1], off offset:16
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:  .LBB2_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s4, v4
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s4, v4
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s12, v7
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s13, v8
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s14, v9
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s15, v10
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s16, v11
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s17, v12
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s18, v13
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s19, v14
; GFX10-64-GISEL-NEXT:    image_sample v[0:3], v6, s[12:19], s[8:11] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX10-64-GISEL-NEXT:    s_andn2_wrexec_b64 s[2:3], s[2:3]
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr6
; GFX10-64-GISEL-NEXT:    s_cbranch_execnz .LBB2_1
; GFX10-64-GISEL-NEXT:  ; %bb.2:
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX10-64-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:    ; return to shader part epilog
;
; GFX1150-SDAG-LABEL: test_waterfall_non_uniform_img_single_read:
; GFX1150-SDAG:       ; %bb.0:
; GFX1150-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX1150-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v6, v1
; GFX1150-SDAG-NEXT:    s_mov_b32 s7, s5
; GFX1150-SDAG-NEXT:    s_mov_b32 s6, s4
; GFX1150-SDAG-NEXT:    s_mov_b32 s5, s3
; GFX1150-SDAG-NEXT:    v_ashrrev_i32_e32 v5, 31, v4
; GFX1150-SDAG-NEXT:    s_mov_b32 s4, s2
; GFX1150-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX1150-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[4:5]
; GFX1150-SDAG-NEXT:    v_add_co_u32 v0, vcc, s0, v0
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1150-SDAG-NEXT:    v_add_co_ci_u32_e64 v1, null, s1, v1, vcc
; GFX1150-SDAG-NEXT:    s_clause 0x1
; GFX1150-SDAG-NEXT:    global_load_b128 v[11:14], v[0:1], off offset:16
; GFX1150-SDAG-NEXT:    global_load_b128 v[7:10], v[0:1], off
; GFX1150-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:  .LBB2_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s10, v4
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s10, v4
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s12, v7
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s13, v8
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s14, v9
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s15, v10
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s16, v11
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s17, v12
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s18, v13
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s19, v14
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:    image_sample v[0:3], v6, s[12:19], s[4:7] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX1150-SDAG-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr6
; GFX1150-SDAG-NEXT:    s_cbranch_execnz .LBB2_1
; GFX1150-SDAG-NEXT:  ; %bb.2:
; GFX1150-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-SDAG-NEXT:    s_and_b64 exec, exec, s[8:9]
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:    ; return to shader part epilog
;
; GFX1150-GISEL-LABEL: test_waterfall_non_uniform_img_single_read:
; GFX1150-GISEL:       ; %bb.0:
; GFX1150-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX1150-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v6, v1
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX1150-GISEL-NEXT:    s_mov_b32 s8, s2
; GFX1150-GISEL-NEXT:    v_ashrrev_i32_e32 v5, 31, v4
; GFX1150-GISEL-NEXT:    s_mov_b32 s9, s3
; GFX1150-GISEL-NEXT:    s_mov_b32 s10, s4
; GFX1150-GISEL-NEXT:    s_mov_b32 s11, s5
; GFX1150-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX1150-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[4:5]
; GFX1150-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX1150-GISEL-NEXT:    v_add_co_u32 v0, vcc, v2, v0
; GFX1150-GISEL-NEXT:    v_add_co_ci_u32_e64 v1, null, v3, v1, vcc
; GFX1150-GISEL-NEXT:    s_clause 0x1
; GFX1150-GISEL-NEXT:    global_load_b128 v[7:10], v[0:1], off
; GFX1150-GISEL-NEXT:    global_load_b128 v[11:14], v[0:1], off offset:16
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:  .LBB2_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s4, v4
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s4, v4
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s12, v7
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s13, v8
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s14, v9
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s15, v10
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s16, v11
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s17, v12
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s18, v13
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s19, v14
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    image_sample v[0:3], v6, s[12:19], s[8:11] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX1150-GISEL-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr6
; GFX1150-GISEL-NEXT:    s_cbranch_execnz .LBB2_1
; GFX1150-GISEL-NEXT:  ; %bb.2:
; GFX1150-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    ; return to shader part epilog
;
; GFX12-SDAG-LABEL: test_waterfall_non_uniform_img_single_read:
; GFX12-SDAG:       ; %bb.0:
; GFX12-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX12-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v6, v1
; GFX12-SDAG-NEXT:    s_mov_b32 s7, s5
; GFX12-SDAG-NEXT:    s_mov_b32 s6, s4
; GFX12-SDAG-NEXT:    s_mov_b32 s5, s3
; GFX12-SDAG-NEXT:    v_ashrrev_i32_e32 v5, 31, v4
; GFX12-SDAG-NEXT:    s_mov_b32 s4, s2
; GFX12-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX12-SDAG-NEXT:    v_lshlrev_b64_e32 v[0:1], 5, v[4:5]
; GFX12-SDAG-NEXT:    v_add_co_u32 v0, vcc, s0, v0
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX12-SDAG-NEXT:    v_add_co_ci_u32_e64 v1, null, s1, v1, vcc
; GFX12-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX12-SDAG-NEXT:    s_clause 0x1
; GFX12-SDAG-NEXT:    global_load_b128 v[11:14], v[0:1], off offset:16
; GFX12-SDAG-NEXT:    global_load_b128 v[7:10], v[0:1], off
; GFX12-SDAG-NEXT:  .LBB2_1: ; =>This Inner Loop Header: Depth=1
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s10, v4
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s10, v4
; GFX12-SDAG-NEXT:    s_wait_loadcnt 0x0
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s12, v7
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s13, v8
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s14, v9
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s15, v10
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s16, v11
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s17, v12
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s18, v13
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s19, v14
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    image_sample v[0:3], v6, s[12:19], s[4:7] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX12-SDAG-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr6
; GFX12-SDAG-NEXT:    s_cbranch_execnz .LBB2_1
; GFX12-SDAG-NEXT:  ; %bb.2:
; GFX12-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX12-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-SDAG-NEXT:    s_and_b64 exec, exec, s[8:9]
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    ; return to shader part epilog
;
; GFX12-GISEL-LABEL: test_waterfall_non_uniform_img_single_read:
; GFX12-GISEL:       ; %bb.0:
; GFX12-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX12-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v6, v1
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX12-GISEL-NEXT:    s_mov_b32 s8, s2
; GFX12-GISEL-NEXT:    v_ashrrev_i32_e32 v5, 31, v4
; GFX12-GISEL-NEXT:    s_mov_b32 s9, s3
; GFX12-GISEL-NEXT:    s_mov_b32 s10, s4
; GFX12-GISEL-NEXT:    s_mov_b32 s11, s5
; GFX12-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX12-GISEL-NEXT:    v_lshlrev_b64_e32 v[0:1], 5, v[4:5]
; GFX12-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX12-GISEL-NEXT:    v_add_co_u32 v0, vcc, v2, v0
; GFX12-GISEL-NEXT:    v_add_co_ci_u32_e64 v1, null, v3, v1, vcc
; GFX12-GISEL-NEXT:    s_clause 0x1
; GFX12-GISEL-NEXT:    global_load_b128 v[7:10], v[0:1], off
; GFX12-GISEL-NEXT:    global_load_b128 v[11:14], v[0:1], off offset:16
; GFX12-GISEL-NEXT:  .LBB2_1: ; =>This Inner Loop Header: Depth=1
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s4, v4
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s4, v4
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x1
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s12, v7
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s13, v8
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s14, v9
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s15, v10
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x0
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s16, v11
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s17, v12
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s18, v13
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s19, v14
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    image_sample v[0:3], v6, s[12:19], s[8:11] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX12-GISEL-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr6
; GFX12-GISEL-NEXT:    s_cbranch_execnz .LBB2_1
; GFX12-GISEL-NEXT:  ; %bb.2:
; GFX12-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX12-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    ; return to shader part epilog
  %ptr = getelementptr <8 x i32>, <8 x i32> addrspace(4)* %in, i32 %index
  %rsrc = load <8 x i32>, <8 x i32> addrspace(4) * %ptr, align 32
  %wf_token = call token @llvm.amdgcn.waterfall.begin.i32(token poison, i32 %index)
  %s_rsrc = call <8 x i32> @llvm.amdgcn.waterfall.readfirstlane.v8i32.v8i32(token %wf_token, <8 x i32> %rsrc)
  %r = call <4 x float> @llvm.amdgcn.image.sample.1d.v4f32.f32(i32 15, float %s, <8 x i32> %s_rsrc, <4 x i32> %samp, i1 0, i32 0, i32 0)
  %r1 = call <4 x float> @llvm.amdgcn.waterfall.end.v4f32(token %wf_token, <4 x float> %r)

  ret <4 x float> %r1
}

define amdgpu_ps void @test_multiple_groups(i32 addrspace(1)* inreg %out1, i32 addrspace(1)* inreg %out2, i32 %idx1, i32 %idx2, i32 %val) #1 {
; VI-SDAG-LABEL: test_multiple_groups:
; VI-SDAG:       ; %bb.0:
; VI-SDAG-NEXT:    v_mov_b32_e32 v3, s2
; VI-SDAG-NEXT:    v_mov_b32_e32 v4, s3
; VI-SDAG-NEXT:    v_mov_b32_e32 v5, s0
; VI-SDAG-NEXT:    v_mov_b32_e32 v6, s1
; VI-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; VI-SDAG-NEXT:  .LBB3_1: ; =>This Inner Loop Header: Depth=1
; VI-SDAG-NEXT:    v_readfirstlane_b32 s4, v0
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[2:3], s4, v0
; VI-SDAG-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; VI-SDAG-NEXT:    s_nop 1
; VI-SDAG-NEXT:    v_readlane_b32 s4, v2, s4
; VI-SDAG-NEXT:    v_mov_b32_e32 v7, s4
; VI-SDAG-NEXT:    ; implicit-def: $vgpr0
; VI-SDAG-NEXT:    s_xor_b64 exec, exec, s[2:3]
; VI-SDAG-NEXT:    s_cbranch_execnz .LBB3_1
; VI-SDAG-NEXT:  ; %bb.2:
; VI-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; VI-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; VI-SDAG-NEXT:    flat_store_dword v[5:6], v7
; VI-SDAG-NEXT:  .LBB3_3: ; =>This Inner Loop Header: Depth=1
; VI-SDAG-NEXT:    v_readfirstlane_b32 s4, v1
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[2:3], s4, v1
; VI-SDAG-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; VI-SDAG-NEXT:    s_nop 1
; VI-SDAG-NEXT:    v_readlane_b32 s4, v2, s4
; VI-SDAG-NEXT:    v_mov_b32_e32 v0, s4
; VI-SDAG-NEXT:    ; implicit-def: $vgpr1
; VI-SDAG-NEXT:    ; implicit-def: $vgpr2
; VI-SDAG-NEXT:    s_xor_b64 exec, exec, s[2:3]
; VI-SDAG-NEXT:    s_cbranch_execnz .LBB3_3
; VI-SDAG-NEXT:  ; %bb.4:
; VI-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; VI-SDAG-NEXT:    flat_store_dword v[3:4], v0
; VI-SDAG-NEXT:    s_endpgm
;
; VI-GISEL-LABEL: test_multiple_groups:
; VI-GISEL:       ; %bb.0:
; VI-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; VI-GISEL-NEXT:  .LBB3_1: ; =>This Inner Loop Header: Depth=1
; VI-GISEL-NEXT:    v_readfirstlane_b32 s8, v0
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[6:7], s8, v0
; VI-GISEL-NEXT:    s_and_saveexec_b64 s[6:7], s[6:7]
; VI-GISEL-NEXT:    s_nop 1
; VI-GISEL-NEXT:    v_readlane_b32 s8, v2, s8
; VI-GISEL-NEXT:    v_mov_b32_e32 v3, s8
; VI-GISEL-NEXT:    ; implicit-def: $vgpr0
; VI-GISEL-NEXT:    s_xor_b64 exec, exec, s[6:7]
; VI-GISEL-NEXT:    s_cbranch_execnz .LBB3_1
; VI-GISEL-NEXT:  ; %bb.2:
; VI-GISEL-NEXT:    s_mov_b64 exec, s[4:5]
; VI-GISEL-NEXT:    v_mov_b32_e32 v5, s1
; VI-GISEL-NEXT:    v_mov_b32_e32 v4, s0
; VI-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; VI-GISEL-NEXT:    flat_store_dword v[4:5], v3
; VI-GISEL-NEXT:  .LBB3_3: ; =>This Inner Loop Header: Depth=1
; VI-GISEL-NEXT:    v_readfirstlane_b32 s6, v1
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[4:5], s6, v1
; VI-GISEL-NEXT:    s_and_saveexec_b64 s[4:5], s[4:5]
; VI-GISEL-NEXT:    s_nop 1
; VI-GISEL-NEXT:    v_readlane_b32 s6, v2, s6
; VI-GISEL-NEXT:    v_mov_b32_e32 v0, s6
; VI-GISEL-NEXT:    ; implicit-def: $vgpr1
; VI-GISEL-NEXT:    ; implicit-def: $vgpr2
; VI-GISEL-NEXT:    s_xor_b64 exec, exec, s[4:5]
; VI-GISEL-NEXT:    s_cbranch_execnz .LBB3_3
; VI-GISEL-NEXT:  ; %bb.4:
; VI-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; VI-GISEL-NEXT:    v_mov_b32_e32 v1, s2
; VI-GISEL-NEXT:    v_mov_b32_e32 v2, s3
; VI-GISEL-NEXT:    flat_store_dword v[1:2], v0
; VI-GISEL-NEXT:    s_endpgm
;
; GFX9-SDAG-LABEL: test_multiple_groups:
; GFX9-SDAG:       ; %bb.0:
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v3, 0
; GFX9-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX9-SDAG-NEXT:  .LBB3_1: ; =>This Inner Loop Header: Depth=1
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s8, v0
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[6:7], s8, v0
; GFX9-SDAG-NEXT:    s_and_saveexec_b64 s[6:7], s[6:7]
; GFX9-SDAG-NEXT:    s_nop 1
; GFX9-SDAG-NEXT:    v_readlane_b32 s8, v2, s8
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v4, s8
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr0
; GFX9-SDAG-NEXT:    s_xor_b64 exec, exec, s[6:7]
; GFX9-SDAG-NEXT:    s_cbranch_execnz .LBB3_1
; GFX9-SDAG-NEXT:  ; %bb.2:
; GFX9-SDAG-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-SDAG-NEXT:    global_store_dword v3, v4, s[0:1]
; GFX9-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX9-SDAG-NEXT:  .LBB3_3: ; =>This Inner Loop Header: Depth=1
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s6, v1
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[4:5], s6, v1
; GFX9-SDAG-NEXT:    s_and_saveexec_b64 s[4:5], s[4:5]
; GFX9-SDAG-NEXT:    s_nop 1
; GFX9-SDAG-NEXT:    v_readlane_b32 s6, v2, s6
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v0, s6
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr1
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr2
; GFX9-SDAG-NEXT:    s_xor_b64 exec, exec, s[4:5]
; GFX9-SDAG-NEXT:    s_cbranch_execnz .LBB3_3
; GFX9-SDAG-NEXT:  ; %bb.4:
; GFX9-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX9-SDAG-NEXT:    global_store_dword v3, v0, s[2:3]
; GFX9-SDAG-NEXT:    s_endpgm
;
; GFX9-GISEL-LABEL: test_multiple_groups:
; GFX9-GISEL:       ; %bb.0:
; GFX9-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX9-GISEL-NEXT:  .LBB3_1: ; =>This Inner Loop Header: Depth=1
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s8, v0
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[6:7], s8, v0
; GFX9-GISEL-NEXT:    s_and_saveexec_b64 s[6:7], s[6:7]
; GFX9-GISEL-NEXT:    s_nop 1
; GFX9-GISEL-NEXT:    v_readlane_b32 s8, v2, s8
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v3, s8
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr0
; GFX9-GISEL-NEXT:    s_xor_b64 exec, exec, s[6:7]
; GFX9-GISEL-NEXT:    s_cbranch_execnz .LBB3_1
; GFX9-GISEL-NEXT:  ; %bb.2:
; GFX9-GISEL-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX9-GISEL-NEXT:    global_store_dword v0, v3, s[0:1]
; GFX9-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX9-GISEL-NEXT:  .LBB3_3: ; =>This Inner Loop Header: Depth=1
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s6, v1
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[4:5], s6, v1
; GFX9-GISEL-NEXT:    s_and_saveexec_b64 s[4:5], s[4:5]
; GFX9-GISEL-NEXT:    s_nop 1
; GFX9-GISEL-NEXT:    v_readlane_b32 s6, v2, s6
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v3, s6
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr1
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr2
; GFX9-GISEL-NEXT:    s_xor_b64 exec, exec, s[4:5]
; GFX9-GISEL-NEXT:    s_cbranch_execnz .LBB3_3
; GFX9-GISEL-NEXT:  ; %bb.4:
; GFX9-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX9-GISEL-NEXT:    global_store_dword v0, v3, s[2:3]
; GFX9-GISEL-NEXT:    s_endpgm
;
; GFX10-32-SDAG-LABEL: test_multiple_groups:
; GFX10-32-SDAG:       ; %bb.0:
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v3, 0
; GFX10-32-SDAG-NEXT:    s_mov_b32 s5, exec_lo
; GFX10-32-SDAG-NEXT:    s_mov_b32 s4, exec_lo
; GFX10-32-SDAG-NEXT:  .LBB3_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s6, v0
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s6, v0
; GFX10-32-SDAG-NEXT:    v_readlane_b32 s6, v2, s6
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v4, s6
; GFX10-32-SDAG-NEXT:    s_andn2_wrexec_b32 s5, s5
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr0
; GFX10-32-SDAG-NEXT:    s_cbranch_execnz .LBB3_1
; GFX10-32-SDAG-NEXT:  ; %bb.2:
; GFX10-32-SDAG-NEXT:    s_mov_b32 exec_lo, s4
; GFX10-32-SDAG-NEXT:    global_store_dword v3, v4, s[0:1]
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-SDAG-NEXT:    s_mov_b32 s1, exec_lo
; GFX10-32-SDAG-NEXT:    s_mov_b32 s0, exec_lo
; GFX10-32-SDAG-NEXT:  .LBB3_3: ; =>This Inner Loop Header: Depth=1
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s4, v1
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s4, v1
; GFX10-32-SDAG-NEXT:    v_readlane_b32 s4, v2, s4
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v0, s4
; GFX10-32-SDAG-NEXT:    s_andn2_wrexec_b32 s1, s1
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr1
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr2
; GFX10-32-SDAG-NEXT:    s_cbranch_execnz .LBB3_3
; GFX10-32-SDAG-NEXT:  ; %bb.4:
; GFX10-32-SDAG-NEXT:    s_mov_b32 exec_lo, s0
; GFX10-32-SDAG-NEXT:    global_store_dword v3, v0, s[2:3]
; GFX10-32-SDAG-NEXT:    s_endpgm
;
; GFX10-32-GISEL-LABEL: test_multiple_groups:
; GFX10-32-GISEL:       ; %bb.0:
; GFX10-32-GISEL-NEXT:    s_mov_b32 s5, exec_lo
; GFX10-32-GISEL-NEXT:    s_mov_b32 s4, exec_lo
; GFX10-32-GISEL-NEXT:  .LBB3_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s6, v0
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s6, v0
; GFX10-32-GISEL-NEXT:    v_readlane_b32 s6, v2, s6
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v3, s6
; GFX10-32-GISEL-NEXT:    s_andn2_wrexec_b32 s5, s5
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr0
; GFX10-32-GISEL-NEXT:    s_cbranch_execnz .LBB3_1
; GFX10-32-GISEL-NEXT:  ; %bb.2:
; GFX10-32-GISEL-NEXT:    s_mov_b32 exec_lo, s4
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-32-GISEL-NEXT:    global_store_dword v0, v3, s[0:1]
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-GISEL-NEXT:    s_mov_b32 s1, exec_lo
; GFX10-32-GISEL-NEXT:    s_mov_b32 s0, exec_lo
; GFX10-32-GISEL-NEXT:  .LBB3_3: ; =>This Inner Loop Header: Depth=1
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s4, v1
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s4, v1
; GFX10-32-GISEL-NEXT:    v_readlane_b32 s4, v2, s4
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v3, s4
; GFX10-32-GISEL-NEXT:    s_andn2_wrexec_b32 s1, s1
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr1
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr2
; GFX10-32-GISEL-NEXT:    s_cbranch_execnz .LBB3_3
; GFX10-32-GISEL-NEXT:  ; %bb.4:
; GFX10-32-GISEL-NEXT:    s_mov_b32 exec_lo, s0
; GFX10-32-GISEL-NEXT:    global_store_dword v0, v3, s[2:3]
; GFX10-32-GISEL-NEXT:    s_endpgm
;
; GFX10-64-SDAG-LABEL: test_multiple_groups:
; GFX10-64-SDAG:       ; %bb.0:
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v3, 0
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX10-64-SDAG-NEXT:  .LBB3_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s8, v0
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s8, v0
; GFX10-64-SDAG-NEXT:    v_readlane_b32 s8, v2, s8
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v4, s8
; GFX10-64-SDAG-NEXT:    s_andn2_wrexec_b64 s[6:7], s[6:7]
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr0
; GFX10-64-SDAG-NEXT:    s_cbranch_execnz .LBB3_1
; GFX10-64-SDAG-NEXT:  ; %bb.2:
; GFX10-64-SDAG-NEXT:    s_mov_b64 exec, s[4:5]
; GFX10-64-SDAG-NEXT:    global_store_dword v3, v4, s[0:1]
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX10-64-SDAG-NEXT:  .LBB3_3: ; =>This Inner Loop Header: Depth=1
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s6, v1
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s6, v1
; GFX10-64-SDAG-NEXT:    v_readlane_b32 s6, v2, s6
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v0, s6
; GFX10-64-SDAG-NEXT:    s_andn2_wrexec_b64 s[4:5], s[4:5]
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr1
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr2
; GFX10-64-SDAG-NEXT:    s_cbranch_execnz .LBB3_3
; GFX10-64-SDAG-NEXT:  ; %bb.4:
; GFX10-64-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX10-64-SDAG-NEXT:    global_store_dword v3, v0, s[2:3]
; GFX10-64-SDAG-NEXT:    s_endpgm
;
; GFX10-64-GISEL-LABEL: test_multiple_groups:
; GFX10-64-GISEL:       ; %bb.0:
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX10-64-GISEL-NEXT:  .LBB3_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s8, v0
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s8, v0
; GFX10-64-GISEL-NEXT:    v_readlane_b32 s8, v2, s8
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v3, s8
; GFX10-64-GISEL-NEXT:    s_andn2_wrexec_b64 s[6:7], s[6:7]
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr0
; GFX10-64-GISEL-NEXT:    s_cbranch_execnz .LBB3_1
; GFX10-64-GISEL-NEXT:  ; %bb.2:
; GFX10-64-GISEL-NEXT:    s_mov_b64 exec, s[4:5]
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX10-64-GISEL-NEXT:    global_store_dword v0, v3, s[0:1]
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX10-64-GISEL-NEXT:  .LBB3_3: ; =>This Inner Loop Header: Depth=1
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s6, v1
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s6, v1
; GFX10-64-GISEL-NEXT:    v_readlane_b32 s6, v2, s6
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v3, s6
; GFX10-64-GISEL-NEXT:    s_andn2_wrexec_b64 s[4:5], s[4:5]
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr1
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr2
; GFX10-64-GISEL-NEXT:    s_cbranch_execnz .LBB3_3
; GFX10-64-GISEL-NEXT:  ; %bb.4:
; GFX10-64-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX10-64-GISEL-NEXT:    global_store_dword v0, v3, s[2:3]
; GFX10-64-GISEL-NEXT:    s_endpgm
;
; GFX1150-SDAG-LABEL: test_multiple_groups:
; GFX1150-SDAG:       ; %bb.0:
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v3, 0
; GFX1150-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; GFX1150-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX1150-SDAG-NEXT:  .LBB3_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s8, v0
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s8, v0
; GFX1150-SDAG-NEXT:    v_readlane_b32 s8, v2, s8
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v4, s8
; GFX1150-SDAG-NEXT:    s_and_not1_wrexec_b64 s[6:7], s[6:7]
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr0
; GFX1150-SDAG-NEXT:    s_cbranch_execnz .LBB3_1
; GFX1150-SDAG-NEXT:  ; %bb.2:
; GFX1150-SDAG-NEXT:    s_mov_b64 exec, s[4:5]
; GFX1150-SDAG-NEXT:    global_store_b32 v3, v4, s[0:1]
; GFX1150-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX1150-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX1150-SDAG-NEXT:  .LBB3_3: ; =>This Inner Loop Header: Depth=1
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s6, v1
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s6, v1
; GFX1150-SDAG-NEXT:    v_readlane_b32 s6, v2, s6
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v0, s6
; GFX1150-SDAG-NEXT:    s_and_not1_wrexec_b64 s[4:5], s[4:5]
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr1
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr2
; GFX1150-SDAG-NEXT:    s_cbranch_execnz .LBB3_3
; GFX1150-SDAG-NEXT:  ; %bb.4:
; GFX1150-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1150-SDAG-NEXT:    global_store_b32 v3, v0, s[2:3]
; GFX1150-SDAG-NEXT:    s_endpgm
;
; GFX1150-GISEL-LABEL: test_multiple_groups:
; GFX1150-GISEL:       ; %bb.0:
; GFX1150-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX1150-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX1150-GISEL-NEXT:  .LBB3_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s8, v0
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s8, v0
; GFX1150-GISEL-NEXT:    v_readlane_b32 s8, v2, s8
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v3, s8
; GFX1150-GISEL-NEXT:    s_and_not1_wrexec_b64 s[6:7], s[6:7]
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr0
; GFX1150-GISEL-NEXT:    s_cbranch_execnz .LBB3_1
; GFX1150-GISEL-NEXT:  ; %bb.2:
; GFX1150-GISEL-NEXT:    s_mov_b64 exec, s[4:5]
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX1150-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX1150-GISEL-NEXT:    global_store_b32 v0, v3, s[0:1]
; GFX1150-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX1150-GISEL-NEXT:  .LBB3_3: ; =>This Inner Loop Header: Depth=1
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s6, v1
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s6, v1
; GFX1150-GISEL-NEXT:    v_readlane_b32 s6, v2, s6
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v3, s6
; GFX1150-GISEL-NEXT:    s_and_not1_wrexec_b64 s[4:5], s[4:5]
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr1
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr2
; GFX1150-GISEL-NEXT:    s_cbranch_execnz .LBB3_3
; GFX1150-GISEL-NEXT:  ; %bb.4:
; GFX1150-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1150-GISEL-NEXT:    global_store_b32 v0, v3, s[2:3]
; GFX1150-GISEL-NEXT:    s_endpgm
;
; GFX12-SDAG-LABEL: test_multiple_groups:
; GFX12-SDAG:       ; %bb.0:
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v3, 0
; GFX12-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; GFX12-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX12-SDAG-NEXT:  .LBB3_1: ; =>This Inner Loop Header: Depth=1
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s8, v0
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_1)
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s8, v0
; GFX12-SDAG-NEXT:    v_readlane_b32 s8, v2, s8
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v4, s8
; GFX12-SDAG-NEXT:    s_and_not1_wrexec_b64 s[6:7], s[6:7]
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr0
; GFX12-SDAG-NEXT:    s_cbranch_execnz .LBB3_1
; GFX12-SDAG-NEXT:  ; %bb.2:
; GFX12-SDAG-NEXT:    s_mov_b64 exec, s[4:5]
; GFX12-SDAG-NEXT:    global_store_b32 v3, v4, s[0:1]
; GFX12-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX12-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX12-SDAG-NEXT:  .LBB3_3: ; =>This Inner Loop Header: Depth=1
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s6, v1
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_1)
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s6, v1
; GFX12-SDAG-NEXT:    v_readlane_b32 s6, v2, s6
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v0, s6
; GFX12-SDAG-NEXT:    s_and_not1_wrexec_b64 s[4:5], s[4:5]
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr1
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr2
; GFX12-SDAG-NEXT:    s_cbranch_execnz .LBB3_3
; GFX12-SDAG-NEXT:  ; %bb.4:
; GFX12-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX12-SDAG-NEXT:    global_store_b32 v3, v0, s[2:3]
; GFX12-SDAG-NEXT:    s_endpgm
;
; GFX12-GISEL-LABEL: test_multiple_groups:
; GFX12-GISEL:       ; %bb.0:
; GFX12-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX12-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX12-GISEL-NEXT:  .LBB3_1: ; =>This Inner Loop Header: Depth=1
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s8, v0
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_1)
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s8, v0
; GFX12-GISEL-NEXT:    v_readlane_b32 s8, v2, s8
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v3, s8
; GFX12-GISEL-NEXT:    s_and_not1_wrexec_b64 s[6:7], s[6:7]
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr0
; GFX12-GISEL-NEXT:    s_cbranch_execnz .LBB3_1
; GFX12-GISEL-NEXT:  ; %bb.2:
; GFX12-GISEL-NEXT:    s_mov_b64 exec, s[4:5]
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX12-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX12-GISEL-NEXT:    global_store_b32 v0, v3, s[0:1]
; GFX12-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX12-GISEL-NEXT:  .LBB3_3: ; =>This Inner Loop Header: Depth=1
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s6, v1
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_1)
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s6, v1
; GFX12-GISEL-NEXT:    v_readlane_b32 s6, v2, s6
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v3, s6
; GFX12-GISEL-NEXT:    s_and_not1_wrexec_b64 s[4:5], s[4:5]
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr1
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr2
; GFX12-GISEL-NEXT:    s_cbranch_execnz .LBB3_3
; GFX12-GISEL-NEXT:  ; %bb.4:
; GFX12-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX12-GISEL-NEXT:    global_store_b32 v0, v3, s[2:3]
; GFX12-GISEL-NEXT:    s_endpgm
  %wf_token = call token @llvm.amdgcn.waterfall.begin.i32(token poison, i32 %idx1)
  %readlane1 = call i32 @llvm.amdgcn.waterfall.readfirstlane.i32.i32(token %wf_token, i32 %idx1)
  %readlane1.1 = call i32 @llvm.amdgcn.readlane(i32 %val, i32 %readlane1)
  %readlane1.2 = call i32 @llvm.amdgcn.waterfall.end.i32(token %wf_token, i32 %readlane1.1)
  ; This store instruction should be outside the waterfall loop and the value
  ; being stored generated incrementally in the loop itself
  store i32 %readlane1.2, i32 addrspace(1)* %out1, align 4

  %wf_token2 = call token @llvm.amdgcn.waterfall.begin.i32(token poison, i32 %idx2)
  %readlane2 = call i32 @llvm.amdgcn.waterfall.readfirstlane.i32.i32(token %wf_token2, i32 %idx2)
  %readlane2.1 = call i32 @llvm.amdgcn.readlane(i32 %val, i32 %readlane2)
  %readlane2.2 = call i32 @llvm.amdgcn.waterfall.end.i32(token %wf_token2, i32 %readlane2.1)
  store i32 %readlane2.2, i32 addrspace(1)* %out2, align 4

  ret void
}


define amdgpu_ps <4 x float> @test_waterfall_non_uniform_img_multi_rl(<8 x i32> addrspace(4)* inreg %in, <4 x i32> addrspace(4)* inreg %samp_in, i32 %index, float %s, i32 %val) #1 {
; VI-SDAG-LABEL: test_waterfall_non_uniform_img_multi_rl:
; VI-SDAG:       ; %bb.0:
; VI-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; VI-SDAG-NEXT:    s_wqm_b64 exec, exec
; VI-SDAG-NEXT:    v_mov_b32_e32 v5, v2
; VI-SDAG-NEXT:    v_mov_b32_e32 v4, v1
; VI-SDAG-NEXT:    v_mov_b32_e32 v6, v0
; VI-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; VI-SDAG-NEXT:  .LBB4_1: ; =>This Inner Loop Header: Depth=1
; VI-SDAG-NEXT:    v_readfirstlane_b32 s8, v6
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[10:11], s8, v6
; VI-SDAG-NEXT:    s_and_saveexec_b64 s[20:21], s[10:11]
; VI-SDAG-NEXT:    s_ashr_i32 s9, s8, 31
; VI-SDAG-NEXT:    s_lshl_b64 s[8:9], s[8:9], 5
; VI-SDAG-NEXT:    v_readfirstlane_b32 s10, v5
; VI-SDAG-NEXT:    s_add_u32 s8, s0, s8
; VI-SDAG-NEXT:    s_addc_u32 s9, s1, s9
; VI-SDAG-NEXT:    s_ashr_i32 s11, s10, 31
; VI-SDAG-NEXT:    s_lshl_b64 s[10:11], s[10:11], 4
; VI-SDAG-NEXT:    s_add_u32 s16, s2, s10
; VI-SDAG-NEXT:    s_addc_u32 s17, s3, s11
; VI-SDAG-NEXT:    s_load_dwordx8 s[8:15], s[8:9], 0x0
; VI-SDAG-NEXT:    s_load_dwordx4 s[16:19], s[16:17], 0x0
; VI-SDAG-NEXT:    ; implicit-def: $vgpr6
; VI-SDAG-NEXT:    ; implicit-def: $vgpr5
; VI-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; VI-SDAG-NEXT:    image_sample v[0:3], v4, s[8:15], s[16:19] dmask:0xf
; VI-SDAG-NEXT:    ; implicit-def: $vgpr4
; VI-SDAG-NEXT:    s_xor_b64 exec, exec, s[20:21]
; VI-SDAG-NEXT:    s_cbranch_execnz .LBB4_1
; VI-SDAG-NEXT:  ; %bb.2:
; VI-SDAG-NEXT:    s_mov_b64 exec, s[6:7]
; VI-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    ; return to shader part epilog
;
; VI-GISEL-LABEL: test_waterfall_non_uniform_img_multi_rl:
; VI-GISEL:       ; %bb.0:
; VI-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; VI-GISEL-NEXT:    s_wqm_b64 exec, exec
; VI-GISEL-NEXT:    v_mov_b32_e32 v5, v0
; VI-GISEL-NEXT:    v_mov_b32_e32 v4, v1
; VI-GISEL-NEXT:    v_mov_b32_e32 v6, v2
; VI-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; VI-GISEL-NEXT:  .LBB4_1: ; =>This Inner Loop Header: Depth=1
; VI-GISEL-NEXT:    v_readfirstlane_b32 s8, v5
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[10:11], s8, v5
; VI-GISEL-NEXT:    s_and_saveexec_b64 s[20:21], s[10:11]
; VI-GISEL-NEXT:    s_ashr_i32 s9, s8, 31
; VI-GISEL-NEXT:    s_lshl_b64 s[8:9], s[8:9], 5
; VI-GISEL-NEXT:    v_readfirstlane_b32 s10, v6
; VI-GISEL-NEXT:    s_add_u32 s8, s0, s8
; VI-GISEL-NEXT:    s_addc_u32 s9, s1, s9
; VI-GISEL-NEXT:    s_ashr_i32 s11, s10, 31
; VI-GISEL-NEXT:    s_lshl_b64 s[10:11], s[10:11], 4
; VI-GISEL-NEXT:    s_add_u32 s16, s2, s10
; VI-GISEL-NEXT:    s_addc_u32 s17, s3, s11
; VI-GISEL-NEXT:    s_load_dwordx8 s[8:15], s[8:9], 0x0
; VI-GISEL-NEXT:    s_load_dwordx4 s[16:19], s[16:17], 0x0
; VI-GISEL-NEXT:    ; implicit-def: $vgpr5
; VI-GISEL-NEXT:    ; implicit-def: $vgpr6
; VI-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; VI-GISEL-NEXT:    image_sample v[0:3], v4, s[8:15], s[16:19] dmask:0xf
; VI-GISEL-NEXT:    ; implicit-def: $vgpr4
; VI-GISEL-NEXT:    s_xor_b64 exec, exec, s[20:21]
; VI-GISEL-NEXT:    s_cbranch_execnz .LBB4_1
; VI-GISEL-NEXT:  ; %bb.2:
; VI-GISEL-NEXT:    s_mov_b64 exec, s[6:7]
; VI-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    ; return to shader part epilog
;
; GFX9-SDAG-LABEL: test_waterfall_non_uniform_img_multi_rl:
; GFX9-SDAG:       ; %bb.0:
; GFX9-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX9-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v5, v2
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v4, v1
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v6, v0
; GFX9-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; GFX9-SDAG-NEXT:  .LBB4_1: ; =>This Inner Loop Header: Depth=1
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s8, v6
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[10:11], s8, v6
; GFX9-SDAG-NEXT:    s_and_saveexec_b64 s[20:21], s[10:11]
; GFX9-SDAG-NEXT:    s_ashr_i32 s9, s8, 31
; GFX9-SDAG-NEXT:    s_lshl_b64 s[8:9], s[8:9], 5
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s10, v5
; GFX9-SDAG-NEXT:    s_add_u32 s22, s0, s8
; GFX9-SDAG-NEXT:    s_addc_u32 s23, s1, s9
; GFX9-SDAG-NEXT:    s_ashr_i32 s11, s10, 31
; GFX9-SDAG-NEXT:    s_lshl_b64 s[8:9], s[10:11], 4
; GFX9-SDAG-NEXT:    s_add_u32 s24, s2, s8
; GFX9-SDAG-NEXT:    s_addc_u32 s25, s3, s9
; GFX9-SDAG-NEXT:    s_load_dwordx8 s[8:15], s[22:23], 0x0
; GFX9-SDAG-NEXT:    s_load_dwordx4 s[16:19], s[24:25], 0x0
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr6
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX9-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; GFX9-SDAG-NEXT:    image_sample v[0:3], v4, s[8:15], s[16:19] dmask:0xf
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX9-SDAG-NEXT:    s_xor_b64 exec, exec, s[20:21]
; GFX9-SDAG-NEXT:    s_cbranch_execnz .LBB4_1
; GFX9-SDAG-NEXT:  ; %bb.2:
; GFX9-SDAG-NEXT:    s_mov_b64 exec, s[6:7]
; GFX9-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    ; return to shader part epilog
;
; GFX9-GISEL-LABEL: test_waterfall_non_uniform_img_multi_rl:
; GFX9-GISEL:       ; %bb.0:
; GFX9-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX9-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v5, v0
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v4, v1
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v6, v2
; GFX9-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX9-GISEL-NEXT:  .LBB4_1: ; =>This Inner Loop Header: Depth=1
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s8, v5
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[10:11], s8, v5
; GFX9-GISEL-NEXT:    s_and_saveexec_b64 s[20:21], s[10:11]
; GFX9-GISEL-NEXT:    s_ashr_i32 s9, s8, 31
; GFX9-GISEL-NEXT:    s_lshl_b64 s[8:9], s[8:9], 5
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s10, v6
; GFX9-GISEL-NEXT:    s_add_u32 s22, s0, s8
; GFX9-GISEL-NEXT:    s_addc_u32 s23, s1, s9
; GFX9-GISEL-NEXT:    s_ashr_i32 s11, s10, 31
; GFX9-GISEL-NEXT:    s_lshl_b64 s[8:9], s[10:11], 4
; GFX9-GISEL-NEXT:    s_add_u32 s24, s2, s8
; GFX9-GISEL-NEXT:    s_addc_u32 s25, s3, s9
; GFX9-GISEL-NEXT:    s_load_dwordx8 s[8:15], s[22:23], 0x0
; GFX9-GISEL-NEXT:    s_load_dwordx4 s[16:19], s[24:25], 0x0
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr6
; GFX9-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; GFX9-GISEL-NEXT:    image_sample v[0:3], v4, s[8:15], s[16:19] dmask:0xf
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX9-GISEL-NEXT:    s_xor_b64 exec, exec, s[20:21]
; GFX9-GISEL-NEXT:    s_cbranch_execnz .LBB4_1
; GFX9-GISEL-NEXT:  ; %bb.2:
; GFX9-GISEL-NEXT:    s_mov_b64 exec, s[6:7]
; GFX9-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-32-SDAG-LABEL: test_waterfall_non_uniform_img_multi_rl:
; GFX10-32-SDAG:       ; %bb.0:
; GFX10-32-SDAG-NEXT:    s_mov_b32 s4, exec_lo
; GFX10-32-SDAG-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v5, v2
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v4, v1
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v6, v0
; GFX10-32-SDAG-NEXT:    s_mov_b32 s6, exec_lo
; GFX10-32-SDAG-NEXT:    s_mov_b32 s5, exec_lo
; GFX10-32-SDAG-NEXT:  .LBB4_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s8, v6
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s8, v6
; GFX10-32-SDAG-NEXT:    s_ashr_i32 s9, s8, 31
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s10, v5
; GFX10-32-SDAG-NEXT:    s_lshl_b64 s[8:9], s[8:9], 5
; GFX10-32-SDAG-NEXT:    s_add_u32 s20, s0, s8
; GFX10-32-SDAG-NEXT:    s_addc_u32 s21, s1, s9
; GFX10-32-SDAG-NEXT:    s_ashr_i32 s11, s10, 31
; GFX10-32-SDAG-NEXT:    s_lshl_b64 s[8:9], s[10:11], 4
; GFX10-32-SDAG-NEXT:    s_add_u32 s22, s2, s8
; GFX10-32-SDAG-NEXT:    s_addc_u32 s23, s3, s9
; GFX10-32-SDAG-NEXT:    s_load_dwordx8 s[8:15], s[20:21], 0x0
; GFX10-32-SDAG-NEXT:    s_load_dwordx4 s[16:19], s[22:23], 0x0
; GFX10-32-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-32-SDAG-NEXT:    image_sample v[0:3], v4, s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX10-32-SDAG-NEXT:    s_andn2_wrexec_b32 s6, s6
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr6
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX10-32-SDAG-NEXT:    s_cbranch_execnz .LBB4_1
; GFX10-32-SDAG-NEXT:  ; %bb.2:
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-SDAG-NEXT:    s_mov_b32 exec_lo, s5
; GFX10-32-SDAG-NEXT:    s_and_b32 exec_lo, exec_lo, s4
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-32-GISEL-LABEL: test_waterfall_non_uniform_img_multi_rl:
; GFX10-32-GISEL:       ; %bb.0:
; GFX10-32-GISEL-NEXT:    s_mov_b32 s4, exec_lo
; GFX10-32-GISEL-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v5, v0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v4, v1
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v6, v2
; GFX10-32-GISEL-NEXT:    s_mov_b32 s6, exec_lo
; GFX10-32-GISEL-NEXT:    s_mov_b32 s5, exec_lo
; GFX10-32-GISEL-NEXT:  .LBB4_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s8, v5
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s8, v5
; GFX10-32-GISEL-NEXT:    s_ashr_i32 s9, s8, 31
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s10, v6
; GFX10-32-GISEL-NEXT:    s_lshl_b64 s[8:9], s[8:9], 5
; GFX10-32-GISEL-NEXT:    s_add_u32 s20, s0, s8
; GFX10-32-GISEL-NEXT:    s_addc_u32 s21, s1, s9
; GFX10-32-GISEL-NEXT:    s_ashr_i32 s11, s10, 31
; GFX10-32-GISEL-NEXT:    s_lshl_b64 s[8:9], s[10:11], 4
; GFX10-32-GISEL-NEXT:    s_add_u32 s22, s2, s8
; GFX10-32-GISEL-NEXT:    s_addc_u32 s23, s3, s9
; GFX10-32-GISEL-NEXT:    s_load_dwordx8 s[8:15], s[20:21], 0x0
; GFX10-32-GISEL-NEXT:    s_load_dwordx4 s[16:19], s[22:23], 0x0
; GFX10-32-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-32-GISEL-NEXT:    image_sample v[0:3], v4, s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX10-32-GISEL-NEXT:    s_andn2_wrexec_b32 s6, s6
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr6
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX10-32-GISEL-NEXT:    s_cbranch_execnz .LBB4_1
; GFX10-32-GISEL-NEXT:  ; %bb.2:
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-GISEL-NEXT:    s_mov_b32 exec_lo, s5
; GFX10-32-GISEL-NEXT:    s_and_b32 exec_lo, exec_lo, s4
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-64-SDAG-LABEL: test_waterfall_non_uniform_img_multi_rl:
; GFX10-64-SDAG:       ; %bb.0:
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX10-64-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v5, v2
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v4, v1
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v6, v0
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; GFX10-64-SDAG-NEXT:  .LBB4_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s10, v6
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s10, v6
; GFX10-64-SDAG-NEXT:    s_ashr_i32 s11, s10, 31
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s12, v5
; GFX10-64-SDAG-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; GFX10-64-SDAG-NEXT:    s_add_u32 s10, s0, s10
; GFX10-64-SDAG-NEXT:    s_addc_u32 s11, s1, s11
; GFX10-64-SDAG-NEXT:    s_ashr_i32 s13, s12, 31
; GFX10-64-SDAG-NEXT:    s_lshl_b64 s[12:13], s[12:13], 4
; GFX10-64-SDAG-NEXT:    s_add_u32 s24, s2, s12
; GFX10-64-SDAG-NEXT:    s_addc_u32 s25, s3, s13
; GFX10-64-SDAG-NEXT:    s_load_dwordx8 s[12:19], s[10:11], 0x0
; GFX10-64-SDAG-NEXT:    s_load_dwordx4 s[20:23], s[24:25], 0x0
; GFX10-64-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-64-SDAG-NEXT:    image_sample v[0:3], v4, s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX10-64-SDAG-NEXT:    s_andn2_wrexec_b64 s[8:9], s[8:9]
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr6
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX10-64-SDAG-NEXT:    s_cbranch_execnz .LBB4_1
; GFX10-64-SDAG-NEXT:  ; %bb.2:
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-SDAG-NEXT:    s_mov_b64 exec, s[6:7]
; GFX10-64-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-64-GISEL-LABEL: test_waterfall_non_uniform_img_multi_rl:
; GFX10-64-GISEL:       ; %bb.0:
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX10-64-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v5, v0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v4, v1
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v6, v2
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[8:9], exec
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX10-64-GISEL-NEXT:  .LBB4_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s10, v5
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s10, v5
; GFX10-64-GISEL-NEXT:    s_ashr_i32 s11, s10, 31
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s12, v6
; GFX10-64-GISEL-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; GFX10-64-GISEL-NEXT:    s_add_u32 s10, s0, s10
; GFX10-64-GISEL-NEXT:    s_addc_u32 s11, s1, s11
; GFX10-64-GISEL-NEXT:    s_ashr_i32 s13, s12, 31
; GFX10-64-GISEL-NEXT:    s_lshl_b64 s[12:13], s[12:13], 4
; GFX10-64-GISEL-NEXT:    s_add_u32 s24, s2, s12
; GFX10-64-GISEL-NEXT:    s_addc_u32 s25, s3, s13
; GFX10-64-GISEL-NEXT:    s_load_dwordx8 s[12:19], s[10:11], 0x0
; GFX10-64-GISEL-NEXT:    s_load_dwordx4 s[20:23], s[24:25], 0x0
; GFX10-64-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-64-GISEL-NEXT:    image_sample v[0:3], v4, s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX10-64-GISEL-NEXT:    s_andn2_wrexec_b64 s[8:9], s[8:9]
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr6
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX10-64-GISEL-NEXT:    s_cbranch_execnz .LBB4_1
; GFX10-64-GISEL-NEXT:  ; %bb.2:
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-GISEL-NEXT:    s_mov_b64 exec, s[6:7]
; GFX10-64-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:    ; return to shader part epilog
;
; GFX1150-SDAG-LABEL: test_waterfall_non_uniform_img_multi_rl:
; GFX1150-SDAG:       ; %bb.0:
; GFX1150-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX1150-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v5, v2
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v4, v1
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v6, v0
; GFX1150-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX1150-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; GFX1150-SDAG-NEXT:  .LBB4_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s10, v6
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s10, v6
; GFX1150-SDAG-NEXT:    s_ashr_i32 s11, s10, 31
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s12, v5
; GFX1150-SDAG-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(SKIP_2) | instid1(SALU_CYCLE_1)
; GFX1150-SDAG-NEXT:    s_add_u32 s10, s0, s10
; GFX1150-SDAG-NEXT:    s_addc_u32 s11, s1, s11
; GFX1150-SDAG-NEXT:    s_ashr_i32 s13, s12, 31
; GFX1150-SDAG-NEXT:    s_lshl_b64 s[12:13], s[12:13], 4
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-SDAG-NEXT:    s_add_u32 s20, s2, s12
; GFX1150-SDAG-NEXT:    s_addc_u32 s21, s3, s13
; GFX1150-SDAG-NEXT:    s_load_b256 s[12:19], s[10:11], 0x0
; GFX1150-SDAG-NEXT:    s_load_b128 s[20:23], s[20:21], 0x0
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX1150-SDAG-NEXT:    image_sample v[0:3], v4, s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX1150-SDAG-NEXT:    s_and_not1_wrexec_b64 s[8:9], s[8:9]
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr6
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX1150-SDAG-NEXT:    s_cbranch_execnz .LBB4_1
; GFX1150-SDAG-NEXT:  ; %bb.2:
; GFX1150-SDAG-NEXT:    s_mov_b64 exec, s[6:7]
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:    ; return to shader part epilog
;
; GFX1150-GISEL-LABEL: test_waterfall_non_uniform_img_multi_rl:
; GFX1150-GISEL:       ; %bb.0:
; GFX1150-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX1150-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v5, v0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v4, v1
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v6, v2
; GFX1150-GISEL-NEXT:    s_mov_b64 s[8:9], exec
; GFX1150-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX1150-GISEL-NEXT:  .LBB4_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s10, v5
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_3) | instid1(SALU_CYCLE_1)
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s10, v5
; GFX1150-GISEL-NEXT:    s_ashr_i32 s11, s10, 31
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s12, v6
; GFX1150-GISEL-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; GFX1150-GISEL-NEXT:    s_add_u32 s10, s0, s10
; GFX1150-GISEL-NEXT:    s_addc_u32 s11, s1, s11
; GFX1150-GISEL-NEXT:    s_ashr_i32 s13, s12, 31
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(SALU_CYCLE_1)
; GFX1150-GISEL-NEXT:    s_lshl_b64 s[12:13], s[12:13], 4
; GFX1150-GISEL-NEXT:    s_add_u32 s20, s2, s12
; GFX1150-GISEL-NEXT:    s_addc_u32 s21, s3, s13
; GFX1150-GISEL-NEXT:    s_load_b256 s[12:19], s[10:11], 0x0
; GFX1150-GISEL-NEXT:    s_load_b128 s[20:23], s[20:21], 0x0
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX1150-GISEL-NEXT:    image_sample v[0:3], v4, s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX1150-GISEL-NEXT:    s_and_not1_wrexec_b64 s[8:9], s[8:9]
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr6
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX1150-GISEL-NEXT:    s_cbranch_execnz .LBB4_1
; GFX1150-GISEL-NEXT:  ; %bb.2:
; GFX1150-GISEL-NEXT:    s_mov_b64 exec, s[6:7]
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    ; return to shader part epilog
;
; GFX12-SDAG-LABEL: test_waterfall_non_uniform_img_multi_rl:
; GFX12-SDAG:       ; %bb.0:
; GFX12-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX12-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v5, v2
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v4, v1
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v6, v0
; GFX12-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX12-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; GFX12-SDAG-NEXT:  .LBB4_1: ; =>This Inner Loop Header: Depth=1
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s10, v6
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s10, v6
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s12, v5
; GFX12-SDAG-NEXT:    s_ashr_i32 s11, s10, 31
; GFX12-SDAG-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-SDAG-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; GFX12-SDAG-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-SDAG-NEXT:    s_add_nc_u64 s[10:11], s[0:1], s[10:11]
; GFX12-SDAG-NEXT:    s_ashr_i32 s13, s12, 31
; GFX12-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(SALU_CYCLE_1)
; GFX12-SDAG-NEXT:    s_lshl_b64 s[12:13], s[12:13], 4
; GFX12-SDAG-NEXT:    s_add_nc_u64 s[20:21], s[2:3], s[12:13]
; GFX12-SDAG-NEXT:    s_load_b256 s[12:19], s[10:11], 0x0
; GFX12-SDAG-NEXT:    s_load_b128 s[20:23], s[20:21], 0x0
; GFX12-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    image_sample v[0:3], v4, s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX12-SDAG-NEXT:    s_and_not1_wrexec_b64 s[8:9], s[8:9]
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr6
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX12-SDAG-NEXT:    s_cbranch_execnz .LBB4_1
; GFX12-SDAG-NEXT:  ; %bb.2:
; GFX12-SDAG-NEXT:    s_mov_b64 exec, s[6:7]
; GFX12-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    ; return to shader part epilog
;
; GFX12-GISEL-LABEL: test_waterfall_non_uniform_img_multi_rl:
; GFX12-GISEL:       ; %bb.0:
; GFX12-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX12-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v5, v0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v4, v1
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v6, v2
; GFX12-GISEL-NEXT:    s_mov_b64 s[8:9], exec
; GFX12-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX12-GISEL-NEXT:  .LBB4_1: ; =>This Inner Loop Header: Depth=1
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s10, v5
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s10, v5
; GFX12-GISEL-NEXT:    s_ashr_i32 s11, s10, 31
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s12, v6
; GFX12-GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-GISEL-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; GFX12-GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-GISEL-NEXT:    s_add_co_u32 s10, s0, s10
; GFX12-GISEL-NEXT:    s_add_co_ci_u32 s11, s1, s11
; GFX12-GISEL-NEXT:    s_ashr_i32 s13, s12, 31
; GFX12-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(SALU_CYCLE_1)
; GFX12-GISEL-NEXT:    s_lshl_b64 s[12:13], s[12:13], 4
; GFX12-GISEL-NEXT:    s_add_co_u32 s20, s2, s12
; GFX12-GISEL-NEXT:    s_add_co_ci_u32 s21, s3, s13
; GFX12-GISEL-NEXT:    s_load_b256 s[12:19], s[10:11], 0x0
; GFX12-GISEL-NEXT:    s_load_b128 s[20:23], s[20:21], 0x0
; GFX12-GISEL-NEXT:    s_wait_kmcnt 0x0
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    image_sample v[0:3], v4, s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX12-GISEL-NEXT:    s_and_not1_wrexec_b64 s[8:9], s[8:9]
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr6
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX12-GISEL-NEXT:    s_cbranch_execnz .LBB4_1
; GFX12-GISEL-NEXT:  ; %bb.2:
; GFX12-GISEL-NEXT:    s_mov_b64 exec, s[6:7]
; GFX12-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    ; return to shader part epilog
  %wf_token = call token @llvm.amdgcn.waterfall.begin.i32(token poison, i32 %index)
  %s_idx = call i32 @llvm.amdgcn.waterfall.readfirstlane.i32.i32(token %wf_token, i32 %index)
  %s_idx2 = call i32 @llvm.amdgcn.waterfall.readfirstlane.i32.i32(token %wf_token, i32 %val)
  %ptr = getelementptr <8 x i32>, <8 x i32> addrspace(4)* %in, i32 %s_idx
  %ptr2 = getelementptr <4 x i32>, <4 x i32> addrspace(4)* %samp_in, i32 %s_idx2
  %rsrc = load <8 x i32>, <8 x i32> addrspace(4) * %ptr, align 32
  %samp = load <4 x i32>, <4 x i32> addrspace(4) * %ptr2, align 32
  %r = call <4 x float> @llvm.amdgcn.image.sample.1d.v4f32.f32(i32 15, float %s, <8 x i32> %rsrc, <4 x i32> %samp, i1 0, i32 0, i32 0)
  %r1 = call <4 x float> @llvm.amdgcn.waterfall.end.v4f32(token %wf_token, <4 x float> %r)

  ret <4 x float> %r1
}

define amdgpu_ps <4 x float> @test_waterfall_non_uni_img_2_idx(<8 x i32> addrspace(4)* inreg %in, <4 x i32> addrspace(4)* inreg %samp_in, i32 %index1, i32 %index2, float %s, <2 x i32> %dummy) #1 {
; VI-SDAG-LABEL: test_waterfall_non_uni_img_2_idx:
; VI-SDAG:       ; %bb.0:
; VI-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; VI-SDAG-NEXT:    s_wqm_b64 exec, exec
; VI-SDAG-NEXT:    v_mov_b32_e32 v6, v2
; VI-SDAG-NEXT:    v_mov_b32_e32 v5, v1
; VI-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; VI-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; VI-SDAG-NEXT:  .LBB5_1: ; =>This Inner Loop Header: Depth=1
; VI-SDAG-NEXT:    v_readfirstlane_b32 s12, v4
; VI-SDAG-NEXT:    v_readfirstlane_b32 s13, v5
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[8:9], s12, v4
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[10:11], s13, v5
; VI-SDAG-NEXT:    s_and_b64 s[8:9], s[8:9], s[10:11]
; VI-SDAG-NEXT:    s_and_saveexec_b64 s[20:21], s[8:9]
; VI-SDAG-NEXT:    s_ashr_i32 s9, s12, 31
; VI-SDAG-NEXT:    s_mov_b32 s8, s12
; VI-SDAG-NEXT:    s_lshl_b64 s[8:9], s[8:9], 5
; VI-SDAG-NEXT:    s_add_u32 s8, s0, s8
; VI-SDAG-NEXT:    s_addc_u32 s9, s1, s9
; VI-SDAG-NEXT:    s_ashr_i32 s11, s13, 31
; VI-SDAG-NEXT:    s_mov_b32 s10, s13
; VI-SDAG-NEXT:    s_lshl_b64 s[10:11], s[10:11], 4
; VI-SDAG-NEXT:    s_add_u32 s16, s2, s10
; VI-SDAG-NEXT:    s_addc_u32 s17, s3, s11
; VI-SDAG-NEXT:    s_load_dwordx8 s[8:15], s[8:9], 0x0
; VI-SDAG-NEXT:    s_load_dwordx4 s[16:19], s[16:17], 0x0
; VI-SDAG-NEXT:    ; implicit-def: $vgpr4_vgpr5
; VI-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; VI-SDAG-NEXT:    image_sample v[0:3], v6, s[8:15], s[16:19] dmask:0xf
; VI-SDAG-NEXT:    ; implicit-def: $vgpr6
; VI-SDAG-NEXT:    s_xor_b64 exec, exec, s[20:21]
; VI-SDAG-NEXT:    s_cbranch_execnz .LBB5_1
; VI-SDAG-NEXT:  ; %bb.2:
; VI-SDAG-NEXT:    s_mov_b64 exec, s[6:7]
; VI-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    ; return to shader part epilog
;
; VI-GISEL-LABEL: test_waterfall_non_uni_img_2_idx:
; VI-GISEL:       ; %bb.0:
; VI-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; VI-GISEL-NEXT:    s_wqm_b64 exec, exec
; VI-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; VI-GISEL-NEXT:    v_mov_b32_e32 v5, v1
; VI-GISEL-NEXT:    v_mov_b32_e32 v6, v2
; VI-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; VI-GISEL-NEXT:  .LBB5_1: ; =>This Inner Loop Header: Depth=1
; VI-GISEL-NEXT:    v_readfirstlane_b32 s12, v4
; VI-GISEL-NEXT:    v_readfirstlane_b32 s13, v5
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[8:9], s12, v4
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[10:11], s13, v5
; VI-GISEL-NEXT:    s_and_b64 s[8:9], s[8:9], s[10:11]
; VI-GISEL-NEXT:    s_and_saveexec_b64 s[20:21], s[8:9]
; VI-GISEL-NEXT:    s_ashr_i32 s9, s12, 31
; VI-GISEL-NEXT:    s_mov_b32 s8, s12
; VI-GISEL-NEXT:    s_lshl_b64 s[8:9], s[8:9], 5
; VI-GISEL-NEXT:    s_add_u32 s8, s0, s8
; VI-GISEL-NEXT:    s_addc_u32 s9, s1, s9
; VI-GISEL-NEXT:    s_ashr_i32 s11, s13, 31
; VI-GISEL-NEXT:    s_mov_b32 s10, s13
; VI-GISEL-NEXT:    s_lshl_b64 s[10:11], s[10:11], 4
; VI-GISEL-NEXT:    s_add_u32 s16, s2, s10
; VI-GISEL-NEXT:    s_addc_u32 s17, s3, s11
; VI-GISEL-NEXT:    s_load_dwordx8 s[8:15], s[8:9], 0x0
; VI-GISEL-NEXT:    s_load_dwordx4 s[16:19], s[16:17], 0x0
; VI-GISEL-NEXT:    ; implicit-def: $vgpr4_vgpr5
; VI-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; VI-GISEL-NEXT:    image_sample v[0:3], v6, s[8:15], s[16:19] dmask:0xf
; VI-GISEL-NEXT:    ; implicit-def: $vgpr6
; VI-GISEL-NEXT:    s_xor_b64 exec, exec, s[20:21]
; VI-GISEL-NEXT:    s_cbranch_execnz .LBB5_1
; VI-GISEL-NEXT:  ; %bb.2:
; VI-GISEL-NEXT:    s_mov_b64 exec, s[6:7]
; VI-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    ; return to shader part epilog
;
; GFX9-SDAG-LABEL: test_waterfall_non_uni_img_2_idx:
; GFX9-SDAG:       ; %bb.0:
; GFX9-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX9-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v6, v2
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v5, v1
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX9-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; GFX9-SDAG-NEXT:  .LBB5_1: ; =>This Inner Loop Header: Depth=1
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s12, v4
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s13, v5
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[8:9], s12, v4
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[10:11], s13, v5
; GFX9-SDAG-NEXT:    s_and_b64 s[8:9], s[8:9], s[10:11]
; GFX9-SDAG-NEXT:    s_and_saveexec_b64 s[20:21], s[8:9]
; GFX9-SDAG-NEXT:    s_ashr_i32 s9, s12, 31
; GFX9-SDAG-NEXT:    s_mov_b32 s8, s12
; GFX9-SDAG-NEXT:    s_lshl_b64 s[8:9], s[8:9], 5
; GFX9-SDAG-NEXT:    s_add_u32 s22, s0, s8
; GFX9-SDAG-NEXT:    s_addc_u32 s23, s1, s9
; GFX9-SDAG-NEXT:    s_ashr_i32 s9, s13, 31
; GFX9-SDAG-NEXT:    s_mov_b32 s8, s13
; GFX9-SDAG-NEXT:    s_lshl_b64 s[8:9], s[8:9], 4
; GFX9-SDAG-NEXT:    s_add_u32 s24, s2, s8
; GFX9-SDAG-NEXT:    s_addc_u32 s25, s3, s9
; GFX9-SDAG-NEXT:    s_load_dwordx8 s[8:15], s[22:23], 0x0
; GFX9-SDAG-NEXT:    s_load_dwordx4 s[16:19], s[24:25], 0x0
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr4_vgpr5
; GFX9-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; GFX9-SDAG-NEXT:    image_sample v[0:3], v6, s[8:15], s[16:19] dmask:0xf
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr6
; GFX9-SDAG-NEXT:    s_xor_b64 exec, exec, s[20:21]
; GFX9-SDAG-NEXT:    s_cbranch_execnz .LBB5_1
; GFX9-SDAG-NEXT:  ; %bb.2:
; GFX9-SDAG-NEXT:    s_mov_b64 exec, s[6:7]
; GFX9-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    ; return to shader part epilog
;
; GFX9-GISEL-LABEL: test_waterfall_non_uni_img_2_idx:
; GFX9-GISEL:       ; %bb.0:
; GFX9-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX9-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v5, v1
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v6, v2
; GFX9-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX9-GISEL-NEXT:  .LBB5_1: ; =>This Inner Loop Header: Depth=1
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s12, v4
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s13, v5
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[8:9], s12, v4
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[10:11], s13, v5
; GFX9-GISEL-NEXT:    s_and_b64 s[8:9], s[8:9], s[10:11]
; GFX9-GISEL-NEXT:    s_and_saveexec_b64 s[20:21], s[8:9]
; GFX9-GISEL-NEXT:    s_ashr_i32 s9, s12, 31
; GFX9-GISEL-NEXT:    s_mov_b32 s8, s12
; GFX9-GISEL-NEXT:    s_lshl_b64 s[8:9], s[8:9], 5
; GFX9-GISEL-NEXT:    s_add_u32 s22, s0, s8
; GFX9-GISEL-NEXT:    s_addc_u32 s23, s1, s9
; GFX9-GISEL-NEXT:    s_ashr_i32 s9, s13, 31
; GFX9-GISEL-NEXT:    s_mov_b32 s8, s13
; GFX9-GISEL-NEXT:    s_lshl_b64 s[8:9], s[8:9], 4
; GFX9-GISEL-NEXT:    s_add_u32 s24, s2, s8
; GFX9-GISEL-NEXT:    s_addc_u32 s25, s3, s9
; GFX9-GISEL-NEXT:    s_load_dwordx8 s[8:15], s[22:23], 0x0
; GFX9-GISEL-NEXT:    s_load_dwordx4 s[16:19], s[24:25], 0x0
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr4_vgpr5
; GFX9-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; GFX9-GISEL-NEXT:    image_sample v[0:3], v6, s[8:15], s[16:19] dmask:0xf
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr6
; GFX9-GISEL-NEXT:    s_xor_b64 exec, exec, s[20:21]
; GFX9-GISEL-NEXT:    s_cbranch_execnz .LBB5_1
; GFX9-GISEL-NEXT:  ; %bb.2:
; GFX9-GISEL-NEXT:    s_mov_b64 exec, s[6:7]
; GFX9-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-32-SDAG-LABEL: test_waterfall_non_uni_img_2_idx:
; GFX10-32-SDAG:       ; %bb.0:
; GFX10-32-SDAG-NEXT:    s_mov_b32 s4, exec_lo
; GFX10-32-SDAG-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v6, v2
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v5, v1
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-32-SDAG-NEXT:    s_mov_b32 s6, exec_lo
; GFX10-32-SDAG-NEXT:    s_mov_b32 s5, exec_lo
; GFX10-32-SDAG-NEXT:  .LBB5_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s7, v4
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s10, v5
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s7, v4
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s10, v5
; GFX10-32-SDAG-NEXT:    s_ashr_i32 s9, s7, 31
; GFX10-32-SDAG-NEXT:    s_mov_b32 s8, s7
; GFX10-32-SDAG-NEXT:    s_lshl_b64 s[8:9], s[8:9], 5
; GFX10-32-SDAG-NEXT:    s_add_u32 s20, s0, s8
; GFX10-32-SDAG-NEXT:    s_addc_u32 s21, s1, s9
; GFX10-32-SDAG-NEXT:    s_ashr_i32 s9, s10, 31
; GFX10-32-SDAG-NEXT:    s_mov_b32 s8, s10
; GFX10-32-SDAG-NEXT:    s_lshl_b64 s[8:9], s[8:9], 4
; GFX10-32-SDAG-NEXT:    s_add_u32 s22, s2, s8
; GFX10-32-SDAG-NEXT:    s_addc_u32 s23, s3, s9
; GFX10-32-SDAG-NEXT:    s_load_dwordx8 s[8:15], s[20:21], 0x0
; GFX10-32-SDAG-NEXT:    s_load_dwordx4 s[16:19], s[22:23], 0x0
; GFX10-32-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-32-SDAG-NEXT:    image_sample v[0:3], v6, s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX10-32-SDAG-NEXT:    s_andn2_wrexec_b32 s6, s6
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr4_vgpr5
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr6
; GFX10-32-SDAG-NEXT:    s_cbranch_execnz .LBB5_1
; GFX10-32-SDAG-NEXT:  ; %bb.2:
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-SDAG-NEXT:    s_mov_b32 exec_lo, s5
; GFX10-32-SDAG-NEXT:    s_and_b32 exec_lo, exec_lo, s4
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-32-GISEL-LABEL: test_waterfall_non_uni_img_2_idx:
; GFX10-32-GISEL:       ; %bb.0:
; GFX10-32-GISEL-NEXT:    s_mov_b32 s4, exec_lo
; GFX10-32-GISEL-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v5, v1
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v6, v2
; GFX10-32-GISEL-NEXT:    s_mov_b32 s6, exec_lo
; GFX10-32-GISEL-NEXT:    s_mov_b32 s5, exec_lo
; GFX10-32-GISEL-NEXT:  .LBB5_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s7, v4
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s10, v5
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s7, v4
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s10, v5
; GFX10-32-GISEL-NEXT:    s_ashr_i32 s9, s7, 31
; GFX10-32-GISEL-NEXT:    s_mov_b32 s8, s7
; GFX10-32-GISEL-NEXT:    s_lshl_b64 s[8:9], s[8:9], 5
; GFX10-32-GISEL-NEXT:    s_add_u32 s20, s0, s8
; GFX10-32-GISEL-NEXT:    s_addc_u32 s21, s1, s9
; GFX10-32-GISEL-NEXT:    s_ashr_i32 s9, s10, 31
; GFX10-32-GISEL-NEXT:    s_mov_b32 s8, s10
; GFX10-32-GISEL-NEXT:    s_lshl_b64 s[8:9], s[8:9], 4
; GFX10-32-GISEL-NEXT:    s_add_u32 s22, s2, s8
; GFX10-32-GISEL-NEXT:    s_addc_u32 s23, s3, s9
; GFX10-32-GISEL-NEXT:    s_load_dwordx8 s[8:15], s[20:21], 0x0
; GFX10-32-GISEL-NEXT:    s_load_dwordx4 s[16:19], s[22:23], 0x0
; GFX10-32-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-32-GISEL-NEXT:    image_sample v[0:3], v6, s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX10-32-GISEL-NEXT:    s_andn2_wrexec_b32 s6, s6
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr4_vgpr5
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr6
; GFX10-32-GISEL-NEXT:    s_cbranch_execnz .LBB5_1
; GFX10-32-GISEL-NEXT:  ; %bb.2:
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-GISEL-NEXT:    s_mov_b32 exec_lo, s5
; GFX10-32-GISEL-NEXT:    s_and_b32 exec_lo, exec_lo, s4
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-64-SDAG-LABEL: test_waterfall_non_uni_img_2_idx:
; GFX10-64-SDAG:       ; %bb.0:
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX10-64-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v6, v2
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v5, v1
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; GFX10-64-SDAG-NEXT:  .LBB5_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s10, v4
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s12, v5
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s10, v4
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s12, v5
; GFX10-64-SDAG-NEXT:    s_ashr_i32 s11, s10, 31
; GFX10-64-SDAG-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; GFX10-64-SDAG-NEXT:    s_add_u32 s10, s0, s10
; GFX10-64-SDAG-NEXT:    s_addc_u32 s11, s1, s11
; GFX10-64-SDAG-NEXT:    s_ashr_i32 s13, s12, 31
; GFX10-64-SDAG-NEXT:    s_lshl_b64 s[12:13], s[12:13], 4
; GFX10-64-SDAG-NEXT:    s_add_u32 s24, s2, s12
; GFX10-64-SDAG-NEXT:    s_addc_u32 s25, s3, s13
; GFX10-64-SDAG-NEXT:    s_load_dwordx8 s[12:19], s[10:11], 0x0
; GFX10-64-SDAG-NEXT:    s_load_dwordx4 s[20:23], s[24:25], 0x0
; GFX10-64-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-64-SDAG-NEXT:    image_sample v[0:3], v6, s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX10-64-SDAG-NEXT:    s_andn2_wrexec_b64 s[8:9], s[8:9]
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr4_vgpr5
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr6
; GFX10-64-SDAG-NEXT:    s_cbranch_execnz .LBB5_1
; GFX10-64-SDAG-NEXT:  ; %bb.2:
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-SDAG-NEXT:    s_mov_b64 exec, s[6:7]
; GFX10-64-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-64-GISEL-LABEL: test_waterfall_non_uni_img_2_idx:
; GFX10-64-GISEL:       ; %bb.0:
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX10-64-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v5, v1
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v6, v2
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[8:9], exec
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX10-64-GISEL-NEXT:  .LBB5_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s10, v4
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s12, v5
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s10, v4
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s12, v5
; GFX10-64-GISEL-NEXT:    s_ashr_i32 s11, s10, 31
; GFX10-64-GISEL-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; GFX10-64-GISEL-NEXT:    s_add_u32 s10, s0, s10
; GFX10-64-GISEL-NEXT:    s_addc_u32 s11, s1, s11
; GFX10-64-GISEL-NEXT:    s_ashr_i32 s13, s12, 31
; GFX10-64-GISEL-NEXT:    s_lshl_b64 s[12:13], s[12:13], 4
; GFX10-64-GISEL-NEXT:    s_add_u32 s24, s2, s12
; GFX10-64-GISEL-NEXT:    s_addc_u32 s25, s3, s13
; GFX10-64-GISEL-NEXT:    s_load_dwordx8 s[12:19], s[10:11], 0x0
; GFX10-64-GISEL-NEXT:    s_load_dwordx4 s[20:23], s[24:25], 0x0
; GFX10-64-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-64-GISEL-NEXT:    image_sample v[0:3], v6, s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX10-64-GISEL-NEXT:    s_andn2_wrexec_b64 s[8:9], s[8:9]
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr4_vgpr5
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr6
; GFX10-64-GISEL-NEXT:    s_cbranch_execnz .LBB5_1
; GFX10-64-GISEL-NEXT:  ; %bb.2:
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-GISEL-NEXT:    s_mov_b64 exec, s[6:7]
; GFX10-64-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:    ; return to shader part epilog
;
; GFX1150-SDAG-LABEL: test_waterfall_non_uni_img_2_idx:
; GFX1150-SDAG:       ; %bb.0:
; GFX1150-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX1150-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v6, v2
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v5, v1
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX1150-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX1150-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; GFX1150-SDAG-NEXT:  .LBB5_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s10, v4
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s12, v5
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s10, v4
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(SALU_CYCLE_1)
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s12, v5
; GFX1150-SDAG-NEXT:    s_ashr_i32 s11, s10, 31
; GFX1150-SDAG-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(SKIP_2) | instid1(SALU_CYCLE_1)
; GFX1150-SDAG-NEXT:    s_add_u32 s10, s0, s10
; GFX1150-SDAG-NEXT:    s_addc_u32 s11, s1, s11
; GFX1150-SDAG-NEXT:    s_ashr_i32 s13, s12, 31
; GFX1150-SDAG-NEXT:    s_lshl_b64 s[12:13], s[12:13], 4
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-SDAG-NEXT:    s_add_u32 s20, s2, s12
; GFX1150-SDAG-NEXT:    s_addc_u32 s21, s3, s13
; GFX1150-SDAG-NEXT:    s_load_b256 s[12:19], s[10:11], 0x0
; GFX1150-SDAG-NEXT:    s_load_b128 s[20:23], s[20:21], 0x0
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX1150-SDAG-NEXT:    image_sample v[0:3], v6, s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX1150-SDAG-NEXT:    s_and_not1_wrexec_b64 s[8:9], s[8:9]
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr4_vgpr5
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr6
; GFX1150-SDAG-NEXT:    s_cbranch_execnz .LBB5_1
; GFX1150-SDAG-NEXT:  ; %bb.2:
; GFX1150-SDAG-NEXT:    s_mov_b64 exec, s[6:7]
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:    ; return to shader part epilog
;
; GFX1150-GISEL-LABEL: test_waterfall_non_uni_img_2_idx:
; GFX1150-GISEL:       ; %bb.0:
; GFX1150-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX1150-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v5, v1
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v6, v2
; GFX1150-GISEL-NEXT:    s_mov_b64 s[8:9], exec
; GFX1150-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX1150-GISEL-NEXT:  .LBB5_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s10, v4
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s12, v5
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s10, v4
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s12, v5
; GFX1150-GISEL-NEXT:    s_ashr_i32 s11, s10, 31
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(SALU_CYCLE_1)
; GFX1150-GISEL-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; GFX1150-GISEL-NEXT:    s_add_u32 s10, s0, s10
; GFX1150-GISEL-NEXT:    s_addc_u32 s11, s1, s11
; GFX1150-GISEL-NEXT:    s_ashr_i32 s13, s12, 31
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(SALU_CYCLE_1)
; GFX1150-GISEL-NEXT:    s_lshl_b64 s[12:13], s[12:13], 4
; GFX1150-GISEL-NEXT:    s_add_u32 s20, s2, s12
; GFX1150-GISEL-NEXT:    s_addc_u32 s21, s3, s13
; GFX1150-GISEL-NEXT:    s_load_b256 s[12:19], s[10:11], 0x0
; GFX1150-GISEL-NEXT:    s_load_b128 s[20:23], s[20:21], 0x0
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX1150-GISEL-NEXT:    image_sample v[0:3], v6, s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX1150-GISEL-NEXT:    s_and_not1_wrexec_b64 s[8:9], s[8:9]
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr4_vgpr5
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr6
; GFX1150-GISEL-NEXT:    s_cbranch_execnz .LBB5_1
; GFX1150-GISEL-NEXT:  ; %bb.2:
; GFX1150-GISEL-NEXT:    s_mov_b64 exec, s[6:7]
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    ; return to shader part epilog
;
; GFX12-SDAG-LABEL: test_waterfall_non_uni_img_2_idx:
; GFX12-SDAG:       ; %bb.0:
; GFX12-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX12-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v6, v2
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v5, v1
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX12-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX12-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; GFX12-SDAG-NEXT:  .LBB5_1: ; =>This Inner Loop Header: Depth=1
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_2)
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s10, v4
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s12, v5
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s10, v4
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s12, v5
; GFX12-SDAG-NEXT:    s_ashr_i32 s11, s10, 31
; GFX12-SDAG-NEXT:    s_ashr_i32 s13, s12, 31
; GFX12-SDAG-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-SDAG-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; GFX12-SDAG-NEXT:    s_lshl_b64 s[12:13], s[12:13], 4
; GFX12-SDAG-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-SDAG-NEXT:    s_add_nc_u64 s[10:11], s[0:1], s[10:11]
; GFX12-SDAG-NEXT:    s_add_nc_u64 s[20:21], s[2:3], s[12:13]
; GFX12-SDAG-NEXT:    s_load_b256 s[12:19], s[10:11], 0x0
; GFX12-SDAG-NEXT:    s_load_b128 s[20:23], s[20:21], 0x0
; GFX12-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    image_sample v[0:3], v6, s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX12-SDAG-NEXT:    s_and_not1_wrexec_b64 s[8:9], s[8:9]
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr4_vgpr5
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr6
; GFX12-SDAG-NEXT:    s_cbranch_execnz .LBB5_1
; GFX12-SDAG-NEXT:  ; %bb.2:
; GFX12-SDAG-NEXT:    s_mov_b64 exec, s[6:7]
; GFX12-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    ; return to shader part epilog
;
; GFX12-GISEL-LABEL: test_waterfall_non_uni_img_2_idx:
; GFX12-GISEL:       ; %bb.0:
; GFX12-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX12-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v5, v1
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v6, v2
; GFX12-GISEL-NEXT:    s_mov_b64 s[8:9], exec
; GFX12-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX12-GISEL-NEXT:  .LBB5_1: ; =>This Inner Loop Header: Depth=1
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s10, v4
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s12, v5
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s10, v4
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s12, v5
; GFX12-GISEL-NEXT:    s_ashr_i32 s11, s10, 31
; GFX12-GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-GISEL-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; GFX12-GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-GISEL-NEXT:    s_add_co_u32 s10, s0, s10
; GFX12-GISEL-NEXT:    s_add_co_ci_u32 s11, s1, s11
; GFX12-GISEL-NEXT:    s_ashr_i32 s13, s12, 31
; GFX12-GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-GISEL-NEXT:    s_lshl_b64 s[12:13], s[12:13], 4
; GFX12-GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-GISEL-NEXT:    s_add_co_u32 s20, s2, s12
; GFX12-GISEL-NEXT:    s_add_co_ci_u32 s21, s3, s13
; GFX12-GISEL-NEXT:    s_load_b256 s[12:19], s[10:11], 0x0
; GFX12-GISEL-NEXT:    s_load_b128 s[20:23], s[20:21], 0x0
; GFX12-GISEL-NEXT:    s_wait_kmcnt 0x0
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    image_sample v[0:3], v6, s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX12-GISEL-NEXT:    s_and_not1_wrexec_b64 s[8:9], s[8:9]
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr4_vgpr5
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr6
; GFX12-GISEL-NEXT:    s_cbranch_execnz .LBB5_1
; GFX12-GISEL-NEXT:  ; %bb.2:
; GFX12-GISEL-NEXT:    s_mov_b64 exec, s[6:7]
; GFX12-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    ; return to shader part epilog
  %t_idx = insertelement <2 x i32> %dummy, i32 %index1, i32 0
  %combined_idx = insertelement <2 x i32> %t_idx, i32 %index2, i32 1
  %wf_token = call token @llvm.amdgcn.waterfall.begin.v2i32(token poison, <2 x i32> %combined_idx)
  %s_c_idx = call <2 x i32> @llvm.amdgcn.waterfall.readfirstlane.v2i32.v2i32(token %wf_token, <2 x i32> %combined_idx)
  %s_idx1 = extractelement <2 x i32> %s_c_idx, i32 0
  %s_idx2 = extractelement <2 x i32> %s_c_idx, i32 1
  %ptr = getelementptr <8 x i32>, <8 x i32> addrspace(4)* %in, i32 %s_idx1
  %ptr2 = getelementptr <4 x i32>, <4 x i32> addrspace(4)* %samp_in, i32 %s_idx2
  %rsrc = load <8 x i32>, <8 x i32> addrspace(4) * %ptr, align 32
  %samp = load <4 x i32>, <4 x i32> addrspace(4) * %ptr2, align 32
  %r = call <4 x float> @llvm.amdgcn.image.sample.1d.v4f32.f32(i32 15, float %s, <8 x i32> %rsrc, <4 x i32> %samp, i1 0, i32 0, i32 0)
  %r1 = call <4 x float> @llvm.amdgcn.waterfall.end.v4f32(token %wf_token, <4 x float> %r)

  ret <4 x float> %r1
}

define amdgpu_ps <4 x float> @test_remove_waterfall_multi_rl(<8 x i32> addrspace(4)* inreg %in, <4 x i32> addrspace(4)* inreg %samp_in, i32 %index, float %s, i32 inreg %val1, i32 inreg %val2) #1 {
; VI-LABEL: test_remove_waterfall_multi_rl:
; VI:       ; %bb.0:
; VI-NEXT:    s_mov_b64 s[12:13], exec
; VI-NEXT:    s_mov_b32 s6, s5
; VI-NEXT:    s_wqm_b64 exec, exec
; VI-NEXT:    s_ashr_i32 s5, s4, 31
; VI-NEXT:    s_lshl_b64 s[4:5], s[4:5], 5
; VI-NEXT:    s_add_u32 s0, s0, s4
; VI-NEXT:    s_addc_u32 s1, s1, s5
; VI-NEXT:    s_ashr_i32 s7, s6, 31
; VI-NEXT:    s_lshl_b64 s[4:5], s[6:7], 4
; VI-NEXT:    s_add_u32 s8, s2, s4
; VI-NEXT:    s_addc_u32 s9, s3, s5
; VI-NEXT:    s_load_dwordx8 s[0:7], s[0:1], 0x0
; VI-NEXT:    s_load_dwordx4 s[8:11], s[8:9], 0x0
; VI-NEXT:    s_and_b64 exec, exec, s[12:13]
; VI-NEXT:    s_waitcnt lgkmcnt(0)
; VI-NEXT:    image_sample v[0:3], v1, s[0:7], s[8:11] dmask:0xf
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    ; return to shader part epilog
;
; GFX9-LABEL: test_remove_waterfall_multi_rl:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_mov_b64 s[12:13], exec
; GFX9-NEXT:    s_mov_b32 s6, s5
; GFX9-NEXT:    s_wqm_b64 exec, exec
; GFX9-NEXT:    s_ashr_i32 s5, s4, 31
; GFX9-NEXT:    s_lshl_b64 s[4:5], s[4:5], 5
; GFX9-NEXT:    s_add_u32 s14, s0, s4
; GFX9-NEXT:    s_addc_u32 s15, s1, s5
; GFX9-NEXT:    s_ashr_i32 s7, s6, 31
; GFX9-NEXT:    s_lshl_b64 s[0:1], s[6:7], 4
; GFX9-NEXT:    s_add_u32 s16, s2, s0
; GFX9-NEXT:    s_addc_u32 s17, s3, s1
; GFX9-NEXT:    s_load_dwordx8 s[0:7], s[14:15], 0x0
; GFX9-NEXT:    s_load_dwordx4 s[8:11], s[16:17], 0x0
; GFX9-NEXT:    s_and_b64 exec, exec, s[12:13]
; GFX9-NEXT:    s_waitcnt lgkmcnt(0)
; GFX9-NEXT:    image_sample v[0:3], v1, s[0:7], s[8:11] dmask:0xf
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    ; return to shader part epilog
;
; GFX10-32-LABEL: test_remove_waterfall_multi_rl:
; GFX10-32:       ; %bb.0:
; GFX10-32-NEXT:    s_mov_b32 s16, exec_lo
; GFX10-32-NEXT:    s_mov_b32 s6, s5
; GFX10-32-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-NEXT:    s_ashr_i32 s5, s4, 31
; GFX10-32-NEXT:    s_lshl_b64 s[4:5], s[4:5], 5
; GFX10-32-NEXT:    s_add_u32 s12, s0, s4
; GFX10-32-NEXT:    s_addc_u32 s13, s1, s5
; GFX10-32-NEXT:    s_ashr_i32 s7, s6, 31
; GFX10-32-NEXT:    s_lshl_b64 s[0:1], s[6:7], 4
; GFX10-32-NEXT:    s_add_u32 s14, s2, s0
; GFX10-32-NEXT:    s_addc_u32 s15, s3, s1
; GFX10-32-NEXT:    s_load_dwordx8 s[0:7], s[12:13], 0x0
; GFX10-32-NEXT:    s_load_dwordx4 s[8:11], s[14:15], 0x0
; GFX10-32-NEXT:    s_and_b32 exec_lo, exec_lo, s16
; GFX10-32-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-32-NEXT:    image_sample v[0:3], v1, s[0:7], s[8:11] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX10-32-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-NEXT:    ; return to shader part epilog
;
; GFX10-64-LABEL: test_remove_waterfall_multi_rl:
; GFX10-64:       ; %bb.0:
; GFX10-64-NEXT:    s_mov_b64 s[12:13], exec
; GFX10-64-NEXT:    s_mov_b32 s6, s5
; GFX10-64-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-NEXT:    s_ashr_i32 s5, s4, 31
; GFX10-64-NEXT:    s_lshl_b64 s[4:5], s[4:5], 5
; GFX10-64-NEXT:    s_add_u32 s14, s0, s4
; GFX10-64-NEXT:    s_addc_u32 s15, s1, s5
; GFX10-64-NEXT:    s_ashr_i32 s7, s6, 31
; GFX10-64-NEXT:    s_lshl_b64 s[0:1], s[6:7], 4
; GFX10-64-NEXT:    s_add_u32 s16, s2, s0
; GFX10-64-NEXT:    s_addc_u32 s17, s3, s1
; GFX10-64-NEXT:    s_load_dwordx8 s[0:7], s[14:15], 0x0
; GFX10-64-NEXT:    s_load_dwordx4 s[8:11], s[16:17], 0x0
; GFX10-64-NEXT:    s_and_b64 exec, exec, s[12:13]
; GFX10-64-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-64-NEXT:    image_sample v[0:3], v1, s[0:7], s[8:11] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX10-64-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-NEXT:    ; return to shader part epilog
;
; GFX1150-LABEL: test_remove_waterfall_multi_rl:
; GFX1150:       ; %bb.0:
; GFX1150-NEXT:    s_mov_b64 s[12:13], exec
; GFX1150-NEXT:    s_mov_b32 s6, s5
; GFX1150-NEXT:    s_wqm_b64 exec, exec
; GFX1150-NEXT:    s_ashr_i32 s5, s4, 31
; GFX1150-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(SALU_CYCLE_1)
; GFX1150-NEXT:    s_lshl_b64 s[4:5], s[4:5], 5
; GFX1150-NEXT:    s_add_u32 s0, s0, s4
; GFX1150-NEXT:    s_addc_u32 s1, s1, s5
; GFX1150-NEXT:    s_ashr_i32 s7, s6, 31
; GFX1150-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(SALU_CYCLE_1)
; GFX1150-NEXT:    s_lshl_b64 s[4:5], s[6:7], 4
; GFX1150-NEXT:    s_add_u32 s8, s2, s4
; GFX1150-NEXT:    s_addc_u32 s9, s3, s5
; GFX1150-NEXT:    s_load_b256 s[0:7], s[0:1], 0x0
; GFX1150-NEXT:    s_load_b128 s[8:11], s[8:9], 0x0
; GFX1150-NEXT:    s_and_b64 exec, exec, s[12:13]
; GFX1150-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1150-NEXT:    image_sample v[0:3], v1, s[0:7], s[8:11] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX1150-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-NEXT:    ; return to shader part epilog
;
; GFX12-SDAG-LABEL: test_remove_waterfall_multi_rl:
; GFX12-SDAG:       ; %bb.0:
; GFX12-SDAG-NEXT:    s_mov_b64 s[12:13], exec
; GFX12-SDAG-NEXT:    s_mov_b32 s6, s5
; GFX12-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX12-SDAG-NEXT:    s_ashr_i32 s5, s4, 31
; GFX12-SDAG-NEXT:    s_ashr_i32 s7, s6, 31
; GFX12-SDAG-NEXT:    s_lshl_b64 s[4:5], s[4:5], 5
; GFX12-SDAG-NEXT:    s_lshl_b64 s[6:7], s[6:7], 4
; GFX12-SDAG-NEXT:    s_add_nc_u64 s[0:1], s[0:1], s[4:5]
; GFX12-SDAG-NEXT:    s_add_nc_u64 s[8:9], s[2:3], s[6:7]
; GFX12-SDAG-NEXT:    s_load_b256 s[0:7], s[0:1], 0x0
; GFX12-SDAG-NEXT:    s_load_b128 s[8:11], s[8:9], 0x0
; GFX12-SDAG-NEXT:    s_and_b64 exec, exec, s[12:13]
; GFX12-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX12-SDAG-NEXT:    image_sample v[0:3], v1, s[0:7], s[8:11] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    ; return to shader part epilog
;
; GFX12-GISEL-LABEL: test_remove_waterfall_multi_rl:
; GFX12-GISEL:       ; %bb.0:
; GFX12-GISEL-NEXT:    s_mov_b64 s[12:13], exec
; GFX12-GISEL-NEXT:    s_mov_b32 s6, s5
; GFX12-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX12-GISEL-NEXT:    s_ashr_i32 s5, s4, 31
; GFX12-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(SALU_CYCLE_1)
; GFX12-GISEL-NEXT:    s_lshl_b64 s[4:5], s[4:5], 5
; GFX12-GISEL-NEXT:    s_add_co_u32 s0, s0, s4
; GFX12-GISEL-NEXT:    s_add_co_ci_u32 s1, s1, s5
; GFX12-GISEL-NEXT:    s_ashr_i32 s7, s6, 31
; GFX12-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(SALU_CYCLE_1)
; GFX12-GISEL-NEXT:    s_lshl_b64 s[4:5], s[6:7], 4
; GFX12-GISEL-NEXT:    s_add_co_u32 s8, s2, s4
; GFX12-GISEL-NEXT:    s_add_co_ci_u32 s9, s3, s5
; GFX12-GISEL-NEXT:    s_load_b256 s[0:7], s[0:1], 0x0
; GFX12-GISEL-NEXT:    s_load_b128 s[8:11], s[8:9], 0x0
; GFX12-GISEL-NEXT:    s_and_b64 exec, exec, s[12:13]
; GFX12-GISEL-NEXT:    s_wait_kmcnt 0x0
; GFX12-GISEL-NEXT:    image_sample v[0:3], v1, s[0:7], s[8:11] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    ; return to shader part epilog
  %wf_token = call token @llvm.amdgcn.waterfall.begin.i32(token poison, i32 %index)
  %s_idx = call i32 @llvm.amdgcn.waterfall.readfirstlane.i32.i32(token %wf_token, i32 %val1)
  %s_idx2 = call i32 @llvm.amdgcn.waterfall.readfirstlane.i32.i32(token %wf_token, i32 %val2)
  %ptr = getelementptr <8 x i32>, <8 x i32> addrspace(4)* %in, i32 %s_idx
  %ptr2 = getelementptr <4 x i32>, <4 x i32> addrspace(4)* %samp_in, i32 %s_idx2
  %rsrc = load <8 x i32>, <8 x i32> addrspace(4) * %ptr, align 32
  %samp = load <4 x i32>, <4 x i32> addrspace(4) * %ptr2, align 32
  %r = call <4 x float> @llvm.amdgcn.image.sample.1d.v4f32.f32(i32 15, float %s, <8 x i32> %rsrc, <4 x i32> %samp, i1 0, i32 0, i32 0)
  %r1 = call <4 x float> @llvm.amdgcn.waterfall.end.v4f32(token %wf_token, <4 x float> %r)

  ret <4 x float> %r1
}

define amdgpu_ps <4 x float> @test_keep_waterfall_multi_rl(<8 x i32> addrspace(4)* inreg %in, <4 x i32> addrspace(4)* inreg %samp_in, i32 %index, float %s, i32 inreg %val) #1 {
; VI-SDAG-LABEL: test_keep_waterfall_multi_rl:
; VI-SDAG:       ; %bb.0:
; VI-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; VI-SDAG-NEXT:    s_wqm_b64 exec, exec
; VI-SDAG-NEXT:    v_mov_b32_e32 v4, v1
; VI-SDAG-NEXT:    v_mov_b32_e32 v5, v0
; VI-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; VI-SDAG-NEXT:  .LBB7_1: ; =>This Inner Loop Header: Depth=1
; VI-SDAG-NEXT:    v_readfirstlane_b32 s10, v5
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[12:13], s10, v5
; VI-SDAG-NEXT:    s_and_saveexec_b64 s[24:25], s[12:13]
; VI-SDAG-NEXT:    s_ashr_i32 s11, s10, 31
; VI-SDAG-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; VI-SDAG-NEXT:    s_add_u32 s10, s0, s10
; VI-SDAG-NEXT:    s_addc_u32 s11, s1, s11
; VI-SDAG-NEXT:    s_ashr_i32 s5, s4, 31
; VI-SDAG-NEXT:    s_lshl_b64 s[12:13], s[4:5], 4
; VI-SDAG-NEXT:    s_add_u32 s20, s2, s12
; VI-SDAG-NEXT:    s_addc_u32 s21, s3, s13
; VI-SDAG-NEXT:    s_load_dwordx8 s[12:19], s[10:11], 0x0
; VI-SDAG-NEXT:    s_load_dwordx4 s[20:23], s[20:21], 0x0
; VI-SDAG-NEXT:    ; implicit-def: $vgpr5
; VI-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; VI-SDAG-NEXT:    image_sample v[0:3], v4, s[12:19], s[20:23] dmask:0xf
; VI-SDAG-NEXT:    ; implicit-def: $vgpr4
; VI-SDAG-NEXT:    s_xor_b64 exec, exec, s[24:25]
; VI-SDAG-NEXT:    s_cbranch_execnz .LBB7_1
; VI-SDAG-NEXT:  ; %bb.2:
; VI-SDAG-NEXT:    s_mov_b64 exec, s[8:9]
; VI-SDAG-NEXT:    s_and_b64 exec, exec, s[6:7]
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    ; return to shader part epilog
;
; VI-GISEL-LABEL: test_keep_waterfall_multi_rl:
; VI-GISEL:       ; %bb.0:
; VI-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; VI-GISEL-NEXT:    s_wqm_b64 exec, exec
; VI-GISEL-NEXT:    v_mov_b32_e32 v5, v0
; VI-GISEL-NEXT:    v_mov_b32_e32 v4, v1
; VI-GISEL-NEXT:    s_mov_b64 s[8:9], exec
; VI-GISEL-NEXT:  .LBB7_1: ; =>This Inner Loop Header: Depth=1
; VI-GISEL-NEXT:    v_readfirstlane_b32 s10, v5
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[12:13], s10, v5
; VI-GISEL-NEXT:    s_and_saveexec_b64 s[24:25], s[12:13]
; VI-GISEL-NEXT:    s_ashr_i32 s11, s10, 31
; VI-GISEL-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; VI-GISEL-NEXT:    s_add_u32 s10, s0, s10
; VI-GISEL-NEXT:    s_addc_u32 s11, s1, s11
; VI-GISEL-NEXT:    s_ashr_i32 s5, s4, 31
; VI-GISEL-NEXT:    s_lshl_b64 s[12:13], s[4:5], 4
; VI-GISEL-NEXT:    s_add_u32 s20, s2, s12
; VI-GISEL-NEXT:    s_addc_u32 s21, s3, s13
; VI-GISEL-NEXT:    s_load_dwordx8 s[12:19], s[10:11], 0x0
; VI-GISEL-NEXT:    s_load_dwordx4 s[20:23], s[20:21], 0x0
; VI-GISEL-NEXT:    ; implicit-def: $vgpr5
; VI-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; VI-GISEL-NEXT:    image_sample v[0:3], v4, s[12:19], s[20:23] dmask:0xf
; VI-GISEL-NEXT:    ; implicit-def: $vgpr4
; VI-GISEL-NEXT:    s_xor_b64 exec, exec, s[24:25]
; VI-GISEL-NEXT:    s_cbranch_execnz .LBB7_1
; VI-GISEL-NEXT:  ; %bb.2:
; VI-GISEL-NEXT:    s_mov_b64 exec, s[8:9]
; VI-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    ; return to shader part epilog
;
; GFX9-SDAG-LABEL: test_keep_waterfall_multi_rl:
; GFX9-SDAG:       ; %bb.0:
; GFX9-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; GFX9-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v4, v1
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v5, v0
; GFX9-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX9-SDAG-NEXT:  .LBB7_1: ; =>This Inner Loop Header: Depth=1
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s10, v5
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[12:13], s10, v5
; GFX9-SDAG-NEXT:    s_and_saveexec_b64 s[24:25], s[12:13]
; GFX9-SDAG-NEXT:    s_ashr_i32 s11, s10, 31
; GFX9-SDAG-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; GFX9-SDAG-NEXT:    s_add_u32 s10, s0, s10
; GFX9-SDAG-NEXT:    s_addc_u32 s11, s1, s11
; GFX9-SDAG-NEXT:    s_ashr_i32 s5, s4, 31
; GFX9-SDAG-NEXT:    s_lshl_b64 s[12:13], s[4:5], 4
; GFX9-SDAG-NEXT:    s_add_u32 s26, s2, s12
; GFX9-SDAG-NEXT:    s_addc_u32 s27, s3, s13
; GFX9-SDAG-NEXT:    s_load_dwordx8 s[12:19], s[10:11], 0x0
; GFX9-SDAG-NEXT:    s_load_dwordx4 s[20:23], s[26:27], 0x0
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX9-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; GFX9-SDAG-NEXT:    image_sample v[0:3], v4, s[12:19], s[20:23] dmask:0xf
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX9-SDAG-NEXT:    s_xor_b64 exec, exec, s[24:25]
; GFX9-SDAG-NEXT:    s_cbranch_execnz .LBB7_1
; GFX9-SDAG-NEXT:  ; %bb.2:
; GFX9-SDAG-NEXT:    s_mov_b64 exec, s[8:9]
; GFX9-SDAG-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    ; return to shader part epilog
;
; GFX9-GISEL-LABEL: test_keep_waterfall_multi_rl:
; GFX9-GISEL:       ; %bb.0:
; GFX9-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX9-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v5, v0
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v4, v1
; GFX9-GISEL-NEXT:    s_mov_b64 s[8:9], exec
; GFX9-GISEL-NEXT:  .LBB7_1: ; =>This Inner Loop Header: Depth=1
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s10, v5
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[12:13], s10, v5
; GFX9-GISEL-NEXT:    s_and_saveexec_b64 s[24:25], s[12:13]
; GFX9-GISEL-NEXT:    s_ashr_i32 s11, s10, 31
; GFX9-GISEL-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; GFX9-GISEL-NEXT:    s_add_u32 s10, s0, s10
; GFX9-GISEL-NEXT:    s_addc_u32 s11, s1, s11
; GFX9-GISEL-NEXT:    s_ashr_i32 s5, s4, 31
; GFX9-GISEL-NEXT:    s_lshl_b64 s[12:13], s[4:5], 4
; GFX9-GISEL-NEXT:    s_add_u32 s26, s2, s12
; GFX9-GISEL-NEXT:    s_addc_u32 s27, s3, s13
; GFX9-GISEL-NEXT:    s_load_dwordx8 s[12:19], s[10:11], 0x0
; GFX9-GISEL-NEXT:    s_load_dwordx4 s[20:23], s[26:27], 0x0
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX9-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; GFX9-GISEL-NEXT:    image_sample v[0:3], v4, s[12:19], s[20:23] dmask:0xf
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX9-GISEL-NEXT:    s_xor_b64 exec, exec, s[24:25]
; GFX9-GISEL-NEXT:    s_cbranch_execnz .LBB7_1
; GFX9-GISEL-NEXT:  ; %bb.2:
; GFX9-GISEL-NEXT:    s_mov_b64 exec, s[8:9]
; GFX9-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-32-SDAG-LABEL: test_keep_waterfall_multi_rl:
; GFX10-32-SDAG:       ; %bb.0:
; GFX10-32-SDAG-NEXT:    s_mov_b32 s6, exec_lo
; GFX10-32-SDAG-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v4, v1
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v5, v0
; GFX10-32-SDAG-NEXT:    s_mov_b32 s8, exec_lo
; GFX10-32-SDAG-NEXT:    s_mov_b32 s7, exec_lo
; GFX10-32-SDAG-NEXT:  .LBB7_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s10, v5
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s10, v5
; GFX10-32-SDAG-NEXT:    s_ashr_i32 s11, s10, 31
; GFX10-32-SDAG-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; GFX10-32-SDAG-NEXT:    s_add_u32 s10, s0, s10
; GFX10-32-SDAG-NEXT:    s_addc_u32 s11, s1, s11
; GFX10-32-SDAG-NEXT:    s_ashr_i32 s5, s4, 31
; GFX10-32-SDAG-NEXT:    s_lshl_b64 s[12:13], s[4:5], 4
; GFX10-32-SDAG-NEXT:    s_add_u32 s24, s2, s12
; GFX10-32-SDAG-NEXT:    s_addc_u32 s25, s3, s13
; GFX10-32-SDAG-NEXT:    s_load_dwordx8 s[12:19], s[10:11], 0x0
; GFX10-32-SDAG-NEXT:    s_load_dwordx4 s[20:23], s[24:25], 0x0
; GFX10-32-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-32-SDAG-NEXT:    image_sample v[0:3], v4, s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX10-32-SDAG-NEXT:    s_andn2_wrexec_b32 s8, s8
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX10-32-SDAG-NEXT:    s_cbranch_execnz .LBB7_1
; GFX10-32-SDAG-NEXT:  ; %bb.2:
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-SDAG-NEXT:    s_mov_b32 exec_lo, s7
; GFX10-32-SDAG-NEXT:    s_and_b32 exec_lo, exec_lo, s6
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-32-GISEL-LABEL: test_keep_waterfall_multi_rl:
; GFX10-32-GISEL:       ; %bb.0:
; GFX10-32-GISEL-NEXT:    s_mov_b32 s6, exec_lo
; GFX10-32-GISEL-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v5, v0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v4, v1
; GFX10-32-GISEL-NEXT:    s_mov_b32 s8, exec_lo
; GFX10-32-GISEL-NEXT:    s_mov_b32 s7, exec_lo
; GFX10-32-GISEL-NEXT:  .LBB7_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s10, v5
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s10, v5
; GFX10-32-GISEL-NEXT:    s_ashr_i32 s11, s10, 31
; GFX10-32-GISEL-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; GFX10-32-GISEL-NEXT:    s_add_u32 s10, s0, s10
; GFX10-32-GISEL-NEXT:    s_addc_u32 s11, s1, s11
; GFX10-32-GISEL-NEXT:    s_ashr_i32 s5, s4, 31
; GFX10-32-GISEL-NEXT:    s_lshl_b64 s[12:13], s[4:5], 4
; GFX10-32-GISEL-NEXT:    s_add_u32 s24, s2, s12
; GFX10-32-GISEL-NEXT:    s_addc_u32 s25, s3, s13
; GFX10-32-GISEL-NEXT:    s_load_dwordx8 s[12:19], s[10:11], 0x0
; GFX10-32-GISEL-NEXT:    s_load_dwordx4 s[20:23], s[24:25], 0x0
; GFX10-32-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-32-GISEL-NEXT:    image_sample v[0:3], v4, s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX10-32-GISEL-NEXT:    s_andn2_wrexec_b32 s8, s8
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX10-32-GISEL-NEXT:    s_cbranch_execnz .LBB7_1
; GFX10-32-GISEL-NEXT:  ; %bb.2:
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-GISEL-NEXT:    s_mov_b32 exec_lo, s7
; GFX10-32-GISEL-NEXT:    s_and_b32 exec_lo, exec_lo, s6
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-64-SDAG-LABEL: test_keep_waterfall_multi_rl:
; GFX10-64-SDAG:       ; %bb.0:
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; GFX10-64-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v4, v1
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v5, v0
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[10:11], exec
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX10-64-SDAG-NEXT:  .LBB7_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s12, v5
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s12, v5
; GFX10-64-SDAG-NEXT:    s_ashr_i32 s13, s12, 31
; GFX10-64-SDAG-NEXT:    s_lshl_b64 s[12:13], s[12:13], 5
; GFX10-64-SDAG-NEXT:    s_add_u32 s24, s0, s12
; GFX10-64-SDAG-NEXT:    s_addc_u32 s25, s1, s13
; GFX10-64-SDAG-NEXT:    s_ashr_i32 s5, s4, 31
; GFX10-64-SDAG-NEXT:    s_lshl_b64 s[12:13], s[4:5], 4
; GFX10-64-SDAG-NEXT:    s_add_u32 s26, s2, s12
; GFX10-64-SDAG-NEXT:    s_addc_u32 s27, s3, s13
; GFX10-64-SDAG-NEXT:    s_load_dwordx8 s[12:19], s[24:25], 0x0
; GFX10-64-SDAG-NEXT:    s_load_dwordx4 s[20:23], s[26:27], 0x0
; GFX10-64-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-64-SDAG-NEXT:    image_sample v[0:3], v4, s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX10-64-SDAG-NEXT:    s_andn2_wrexec_b64 s[10:11], s[10:11]
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX10-64-SDAG-NEXT:    s_cbranch_execnz .LBB7_1
; GFX10-64-SDAG-NEXT:  ; %bb.2:
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-SDAG-NEXT:    s_mov_b64 exec, s[8:9]
; GFX10-64-SDAG-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-64-GISEL-LABEL: test_keep_waterfall_multi_rl:
; GFX10-64-GISEL:       ; %bb.0:
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX10-64-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v5, v0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v4, v1
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[10:11], exec
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[8:9], exec
; GFX10-64-GISEL-NEXT:  .LBB7_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s12, v5
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s12, v5
; GFX10-64-GISEL-NEXT:    s_ashr_i32 s13, s12, 31
; GFX10-64-GISEL-NEXT:    s_lshl_b64 s[12:13], s[12:13], 5
; GFX10-64-GISEL-NEXT:    s_add_u32 s24, s0, s12
; GFX10-64-GISEL-NEXT:    s_addc_u32 s25, s1, s13
; GFX10-64-GISEL-NEXT:    s_ashr_i32 s5, s4, 31
; GFX10-64-GISEL-NEXT:    s_lshl_b64 s[12:13], s[4:5], 4
; GFX10-64-GISEL-NEXT:    s_add_u32 s26, s2, s12
; GFX10-64-GISEL-NEXT:    s_addc_u32 s27, s3, s13
; GFX10-64-GISEL-NEXT:    s_load_dwordx8 s[12:19], s[24:25], 0x0
; GFX10-64-GISEL-NEXT:    s_load_dwordx4 s[20:23], s[26:27], 0x0
; GFX10-64-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-64-GISEL-NEXT:    image_sample v[0:3], v4, s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX10-64-GISEL-NEXT:    s_andn2_wrexec_b64 s[10:11], s[10:11]
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX10-64-GISEL-NEXT:    s_cbranch_execnz .LBB7_1
; GFX10-64-GISEL-NEXT:  ; %bb.2:
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-GISEL-NEXT:    s_mov_b64 exec, s[8:9]
; GFX10-64-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:    ; return to shader part epilog
;
; GFX1150-SDAG-LABEL: test_keep_waterfall_multi_rl:
; GFX1150-SDAG:       ; %bb.0:
; GFX1150-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; GFX1150-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v4, v1
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v5, v0
; GFX1150-SDAG-NEXT:    s_mov_b64 s[10:11], exec
; GFX1150-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX1150-SDAG-NEXT:  .LBB7_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s12, v5
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s12, v5
; GFX1150-SDAG-NEXT:    s_ashr_i32 s13, s12, 31
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(SALU_CYCLE_1)
; GFX1150-SDAG-NEXT:    s_lshl_b64 s[12:13], s[12:13], 5
; GFX1150-SDAG-NEXT:    s_add_u32 s12, s0, s12
; GFX1150-SDAG-NEXT:    s_addc_u32 s13, s1, s13
; GFX1150-SDAG-NEXT:    s_ashr_i32 s5, s4, 31
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(SALU_CYCLE_1)
; GFX1150-SDAG-NEXT:    s_lshl_b64 s[14:15], s[4:5], 4
; GFX1150-SDAG-NEXT:    s_add_u32 s20, s2, s14
; GFX1150-SDAG-NEXT:    s_addc_u32 s21, s3, s15
; GFX1150-SDAG-NEXT:    s_load_b256 s[12:19], s[12:13], 0x0
; GFX1150-SDAG-NEXT:    s_load_b128 s[20:23], s[20:21], 0x0
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX1150-SDAG-NEXT:    image_sample v[0:3], v4, s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX1150-SDAG-NEXT:    s_and_not1_wrexec_b64 s[10:11], s[10:11]
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX1150-SDAG-NEXT:    s_cbranch_execnz .LBB7_1
; GFX1150-SDAG-NEXT:  ; %bb.2:
; GFX1150-SDAG-NEXT:    s_mov_b64 exec, s[8:9]
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-SDAG-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:    ; return to shader part epilog
;
; GFX1150-GISEL-LABEL: test_keep_waterfall_multi_rl:
; GFX1150-GISEL:       ; %bb.0:
; GFX1150-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX1150-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v5, v0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v4, v1
; GFX1150-GISEL-NEXT:    s_mov_b64 s[10:11], exec
; GFX1150-GISEL-NEXT:    s_mov_b64 s[8:9], exec
; GFX1150-GISEL-NEXT:  .LBB7_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s12, v5
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s12, v5
; GFX1150-GISEL-NEXT:    s_ashr_i32 s13, s12, 31
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(SALU_CYCLE_1)
; GFX1150-GISEL-NEXT:    s_lshl_b64 s[12:13], s[12:13], 5
; GFX1150-GISEL-NEXT:    s_add_u32 s12, s0, s12
; GFX1150-GISEL-NEXT:    s_addc_u32 s13, s1, s13
; GFX1150-GISEL-NEXT:    s_ashr_i32 s5, s4, 31
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(SALU_CYCLE_1)
; GFX1150-GISEL-NEXT:    s_lshl_b64 s[14:15], s[4:5], 4
; GFX1150-GISEL-NEXT:    s_add_u32 s20, s2, s14
; GFX1150-GISEL-NEXT:    s_addc_u32 s21, s3, s15
; GFX1150-GISEL-NEXT:    s_load_b256 s[12:19], s[12:13], 0x0
; GFX1150-GISEL-NEXT:    s_load_b128 s[20:23], s[20:21], 0x0
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX1150-GISEL-NEXT:    image_sample v[0:3], v4, s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX1150-GISEL-NEXT:    s_and_not1_wrexec_b64 s[10:11], s[10:11]
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX1150-GISEL-NEXT:    s_cbranch_execnz .LBB7_1
; GFX1150-GISEL-NEXT:  ; %bb.2:
; GFX1150-GISEL-NEXT:    s_mov_b64 exec, s[8:9]
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    ; return to shader part epilog
;
; GFX12-SDAG-LABEL: test_keep_waterfall_multi_rl:
; GFX12-SDAG:       ; %bb.0:
; GFX12-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; GFX12-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v4, v1
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v5, v0
; GFX12-SDAG-NEXT:    s_mov_b64 s[10:11], exec
; GFX12-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX12-SDAG-NEXT:  .LBB7_1: ; =>This Inner Loop Header: Depth=1
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s12, v5
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s12, v5
; GFX12-SDAG-NEXT:    s_ashr_i32 s13, s12, 31
; GFX12-SDAG-NEXT:    s_ashr_i32 s5, s4, 31
; GFX12-SDAG-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-SDAG-NEXT:    s_lshl_b64 s[12:13], s[12:13], 5
; GFX12-SDAG-NEXT:    s_lshl_b64 s[14:15], s[4:5], 4
; GFX12-SDAG-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-SDAG-NEXT:    s_add_nc_u64 s[12:13], s[0:1], s[12:13]
; GFX12-SDAG-NEXT:    s_add_nc_u64 s[20:21], s[2:3], s[14:15]
; GFX12-SDAG-NEXT:    s_load_b256 s[12:19], s[12:13], 0x0
; GFX12-SDAG-NEXT:    s_load_b128 s[20:23], s[20:21], 0x0
; GFX12-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    image_sample v[0:3], v4, s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX12-SDAG-NEXT:    s_and_not1_wrexec_b64 s[10:11], s[10:11]
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX12-SDAG-NEXT:    s_cbranch_execnz .LBB7_1
; GFX12-SDAG-NEXT:  ; %bb.2:
; GFX12-SDAG-NEXT:    s_mov_b64 exec, s[8:9]
; GFX12-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-SDAG-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    ; return to shader part epilog
;
; GFX12-GISEL-LABEL: test_keep_waterfall_multi_rl:
; GFX12-GISEL:       ; %bb.0:
; GFX12-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX12-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v5, v0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v4, v1
; GFX12-GISEL-NEXT:    s_mov_b64 s[10:11], exec
; GFX12-GISEL-NEXT:    s_mov_b64 s[8:9], exec
; GFX12-GISEL-NEXT:  .LBB7_1: ; =>This Inner Loop Header: Depth=1
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s12, v5
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s12, v5
; GFX12-GISEL-NEXT:    s_ashr_i32 s13, s12, 31
; GFX12-GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-GISEL-NEXT:    s_lshl_b64 s[12:13], s[12:13], 5
; GFX12-GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-GISEL-NEXT:    s_add_co_u32 s12, s0, s12
; GFX12-GISEL-NEXT:    s_add_co_ci_u32 s13, s1, s13
; GFX12-GISEL-NEXT:    s_ashr_i32 s5, s4, 31
; GFX12-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(SALU_CYCLE_1)
; GFX12-GISEL-NEXT:    s_lshl_b64 s[14:15], s[4:5], 4
; GFX12-GISEL-NEXT:    s_add_co_u32 s20, s2, s14
; GFX12-GISEL-NEXT:    s_add_co_ci_u32 s21, s3, s15
; GFX12-GISEL-NEXT:    s_load_b256 s[12:19], s[12:13], 0x0
; GFX12-GISEL-NEXT:    s_load_b128 s[20:23], s[20:21], 0x0
; GFX12-GISEL-NEXT:    s_wait_kmcnt 0x0
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    image_sample v[0:3], v4, s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX12-GISEL-NEXT:    s_and_not1_wrexec_b64 s[10:11], s[10:11]
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX12-GISEL-NEXT:    s_cbranch_execnz .LBB7_1
; GFX12-GISEL-NEXT:  ; %bb.2:
; GFX12-GISEL-NEXT:    s_mov_b64 exec, s[8:9]
; GFX12-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    ; return to shader part epilog
  %wf_token = call token @llvm.amdgcn.waterfall.begin.i32(token poison, i32 %index)
  %s_idx = call i32 @llvm.amdgcn.waterfall.readfirstlane.i32.i32(token %wf_token, i32 %index)
  %s_idx2 = call i32 @llvm.amdgcn.waterfall.readfirstlane.i32.i32(token %wf_token, i32 %val)
  %ptr = getelementptr <8 x i32>, <8 x i32> addrspace(4)* %in, i32 %s_idx
  %ptr2 = getelementptr <4 x i32>, <4 x i32> addrspace(4)* %samp_in, i32 %s_idx2
  %rsrc = load <8 x i32>, <8 x i32> addrspace(4) * %ptr, align 32
  %samp = load <4 x i32>, <4 x i32> addrspace(4) * %ptr2, align 32
  %r = call <4 x float> @llvm.amdgcn.image.sample.1d.v4f32.f32(i32 15, float %s, <8 x i32> %rsrc, <4 x i32> %samp, i1 0, i32 0, i32 0)
  %r1 = call <4 x float> @llvm.amdgcn.waterfall.end.v4f32(token %wf_token, <4 x float> %r)

  ret <4 x float> %r1
}

define amdgpu_ps void @test_waterfall_sample_with_kill(<8 x i32> addrspace(4)* inreg %in, <4 x i32> addrspace(4)* inreg %samp_in, i32 %index, float %s, i32 inreg %val, float %dummy_f0, float %dummy_f1, float %dummy_f2) #1 {
; VI-LABEL: test_waterfall_sample_with_kill:
; VI:       ; %bb.0:
; VI-NEXT:    s_mov_b64 s[6:7], exec
; VI-NEXT:    s_wqm_b64 exec, exec
; VI-NEXT:    s_mov_b64 s[8:9], exec
; VI-NEXT:  .LBB8_1: ; =>This Inner Loop Header: Depth=1
; VI-NEXT:    v_readfirstlane_b32 s10, v0
; VI-NEXT:    v_cmp_eq_u32_e64 s[12:13], s10, v0
; VI-NEXT:    s_and_saveexec_b64 s[24:25], s[12:13]
; VI-NEXT:    s_ashr_i32 s11, s10, 31
; VI-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; VI-NEXT:    s_add_u32 s10, s0, s10
; VI-NEXT:    s_addc_u32 s11, s1, s11
; VI-NEXT:    s_ashr_i32 s5, s4, 31
; VI-NEXT:    s_lshl_b64 s[12:13], s[4:5], 4
; VI-NEXT:    s_add_u32 s20, s2, s12
; VI-NEXT:    s_addc_u32 s21, s3, s13
; VI-NEXT:    s_load_dwordx8 s[12:19], s[10:11], 0x0
; VI-NEXT:    s_load_dwordx4 s[20:23], s[20:21], 0x0
; VI-NEXT:    ; implicit-def: $vgpr0
; VI-NEXT:    s_waitcnt lgkmcnt(0)
; VI-NEXT:    image_sample v[5:8], v1, s[12:19], s[20:23] dmask:0xf
; VI-NEXT:    ; implicit-def: $vgpr1
; VI-NEXT:    s_xor_b64 exec, exec, s[24:25]
; VI-NEXT:    s_cbranch_execnz .LBB8_1
; VI-NEXT:  ; %bb.2:
; VI-NEXT:    s_mov_b64 exec, s[8:9]
; VI-NEXT:    s_and_b64 exec, exec, s[6:7]
; VI-NEXT:    s_waitcnt vmcnt(0)
; VI-NEXT:    v_cmp_gt_f32_e32 vcc, 0, v5
; VI-NEXT:    s_and_saveexec_b64 s[0:1], vcc
; VI-NEXT:    s_xor_b64 s[0:1], exec, s[0:1]
; VI-NEXT:    s_cbranch_execz .LBB8_5
; VI-NEXT:  ; %bb.3: ; %.kill
; VI-NEXT:    s_andn2_b64 s[6:7], s[6:7], exec
; VI-NEXT:    s_cbranch_scc0 .LBB8_6
; VI-NEXT:  ; %bb.4: ; %.kill
; VI-NEXT:    s_mov_b64 exec, 0
; VI-NEXT:  .LBB8_5: ; %.exit
; VI-NEXT:    s_or_b64 exec, exec, s[0:1]
; VI-NEXT:    v_mov_b32_e32 v0, 0
; VI-NEXT:    exp mrt0, v0, off, off, off done vm
; VI-NEXT:    s_endpgm
; VI-NEXT:  .LBB8_6:
; VI-NEXT:    s_mov_b64 exec, 0
; VI-NEXT:    exp null, off, off, off, off done vm
; VI-NEXT:    s_endpgm
;
; GFX9-LABEL: test_waterfall_sample_with_kill:
; GFX9:       ; %bb.0:
; GFX9-NEXT:    s_mov_b64 s[6:7], exec
; GFX9-NEXT:    s_wqm_b64 exec, exec
; GFX9-NEXT:    s_mov_b64 s[8:9], exec
; GFX9-NEXT:  .LBB8_1: ; =>This Inner Loop Header: Depth=1
; GFX9-NEXT:    v_readfirstlane_b32 s10, v0
; GFX9-NEXT:    v_cmp_eq_u32_e64 s[12:13], s10, v0
; GFX9-NEXT:    s_and_saveexec_b64 s[24:25], s[12:13]
; GFX9-NEXT:    s_ashr_i32 s11, s10, 31
; GFX9-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; GFX9-NEXT:    s_add_u32 s10, s0, s10
; GFX9-NEXT:    s_addc_u32 s11, s1, s11
; GFX9-NEXT:    s_ashr_i32 s5, s4, 31
; GFX9-NEXT:    s_lshl_b64 s[12:13], s[4:5], 4
; GFX9-NEXT:    s_add_u32 s26, s2, s12
; GFX9-NEXT:    s_addc_u32 s27, s3, s13
; GFX9-NEXT:    s_load_dwordx8 s[12:19], s[10:11], 0x0
; GFX9-NEXT:    s_load_dwordx4 s[20:23], s[26:27], 0x0
; GFX9-NEXT:    ; implicit-def: $vgpr0
; GFX9-NEXT:    s_waitcnt lgkmcnt(0)
; GFX9-NEXT:    image_sample v[5:8], v1, s[12:19], s[20:23] dmask:0xf
; GFX9-NEXT:    ; implicit-def: $vgpr1
; GFX9-NEXT:    s_xor_b64 exec, exec, s[24:25]
; GFX9-NEXT:    s_cbranch_execnz .LBB8_1
; GFX9-NEXT:  ; %bb.2:
; GFX9-NEXT:    s_mov_b64 exec, s[8:9]
; GFX9-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX9-NEXT:    s_waitcnt vmcnt(0)
; GFX9-NEXT:    v_cmp_gt_f32_e32 vcc, 0, v5
; GFX9-NEXT:    s_and_saveexec_b64 s[0:1], vcc
; GFX9-NEXT:    s_xor_b64 s[0:1], exec, s[0:1]
; GFX9-NEXT:    s_cbranch_execz .LBB8_5
; GFX9-NEXT:  ; %bb.3: ; %.kill
; GFX9-NEXT:    s_andn2_b64 s[6:7], s[6:7], exec
; GFX9-NEXT:    s_cbranch_scc0 .LBB8_6
; GFX9-NEXT:  ; %bb.4: ; %.kill
; GFX9-NEXT:    s_mov_b64 exec, 0
; GFX9-NEXT:  .LBB8_5: ; %.exit
; GFX9-NEXT:    s_or_b64 exec, exec, s[0:1]
; GFX9-NEXT:    v_mov_b32_e32 v0, 0
; GFX9-NEXT:    exp mrt0, v0, off, off, off done vm
; GFX9-NEXT:    s_endpgm
; GFX9-NEXT:  .LBB8_6:
; GFX9-NEXT:    s_mov_b64 exec, 0
; GFX9-NEXT:    exp null, off, off, off, off done vm
; GFX9-NEXT:    s_endpgm
;
; GFX10-32-LABEL: test_waterfall_sample_with_kill:
; GFX10-32:       ; %bb.0:
; GFX10-32-NEXT:    s_mov_b32 s6, exec_lo
; GFX10-32-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-NEXT:    s_mov_b32 s8, exec_lo
; GFX10-32-NEXT:    s_mov_b32 s7, exec_lo
; GFX10-32-NEXT:  .LBB8_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-NEXT:    v_readfirstlane_b32 s10, v0
; GFX10-32-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-NEXT:    v_cmpx_eq_u32_e32 s10, v0
; GFX10-32-NEXT:    s_ashr_i32 s11, s10, 31
; GFX10-32-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; GFX10-32-NEXT:    s_add_u32 s10, s0, s10
; GFX10-32-NEXT:    s_addc_u32 s11, s1, s11
; GFX10-32-NEXT:    s_ashr_i32 s5, s4, 31
; GFX10-32-NEXT:    s_lshl_b64 s[12:13], s[4:5], 4
; GFX10-32-NEXT:    s_add_u32 s24, s2, s12
; GFX10-32-NEXT:    s_addc_u32 s25, s3, s13
; GFX10-32-NEXT:    s_load_dwordx8 s[12:19], s[10:11], 0x0
; GFX10-32-NEXT:    s_load_dwordx4 s[20:23], s[24:25], 0x0
; GFX10-32-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-32-NEXT:    image_sample v[5:8], v1, s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX10-32-NEXT:    s_andn2_wrexec_b32 s8, s8
; GFX10-32-NEXT:    ; implicit-def: $vgpr0
; GFX10-32-NEXT:    ; implicit-def: $vgpr1
; GFX10-32-NEXT:    s_cbranch_execnz .LBB8_1
; GFX10-32-NEXT:  ; %bb.2:
; GFX10-32-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-NEXT:    s_mov_b32 exec_lo, s7
; GFX10-32-NEXT:    s_and_b32 exec_lo, exec_lo, s6
; GFX10-32-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-NEXT:    v_cmp_gt_f32_e32 vcc_lo, 0, v5
; GFX10-32-NEXT:    s_and_saveexec_b32 s0, vcc_lo
; GFX10-32-NEXT:    s_xor_b32 s0, exec_lo, s0
; GFX10-32-NEXT:    s_cbranch_execz .LBB8_5
; GFX10-32-NEXT:  ; %bb.3: ; %.kill
; GFX10-32-NEXT:    s_andn2_b32 s6, s6, exec_lo
; GFX10-32-NEXT:    s_cbranch_scc0 .LBB8_6
; GFX10-32-NEXT:  ; %bb.4: ; %.kill
; GFX10-32-NEXT:    s_mov_b32 exec_lo, 0
; GFX10-32-NEXT:  .LBB8_5: ; %.exit
; GFX10-32-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; GFX10-32-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-32-NEXT:    exp mrt0, v0, off, off, off done vm
; GFX10-32-NEXT:    s_endpgm
; GFX10-32-NEXT:  .LBB8_6:
; GFX10-32-NEXT:    s_mov_b32 exec_lo, 0
; GFX10-32-NEXT:    exp null, off, off, off, off done vm
; GFX10-32-NEXT:    s_endpgm
;
; GFX10-64-LABEL: test_waterfall_sample_with_kill:
; GFX10-64:       ; %bb.0:
; GFX10-64-NEXT:    s_mov_b64 s[6:7], exec
; GFX10-64-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-NEXT:    s_mov_b64 s[10:11], exec
; GFX10-64-NEXT:    s_mov_b64 s[8:9], exec
; GFX10-64-NEXT:  .LBB8_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-NEXT:    v_readfirstlane_b32 s12, v0
; GFX10-64-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-NEXT:    v_cmpx_eq_u32_e32 s12, v0
; GFX10-64-NEXT:    s_ashr_i32 s13, s12, 31
; GFX10-64-NEXT:    s_lshl_b64 s[12:13], s[12:13], 5
; GFX10-64-NEXT:    s_add_u32 s24, s0, s12
; GFX10-64-NEXT:    s_addc_u32 s25, s1, s13
; GFX10-64-NEXT:    s_ashr_i32 s5, s4, 31
; GFX10-64-NEXT:    s_lshl_b64 s[12:13], s[4:5], 4
; GFX10-64-NEXT:    s_add_u32 s26, s2, s12
; GFX10-64-NEXT:    s_addc_u32 s27, s3, s13
; GFX10-64-NEXT:    s_load_dwordx8 s[12:19], s[24:25], 0x0
; GFX10-64-NEXT:    s_load_dwordx4 s[20:23], s[26:27], 0x0
; GFX10-64-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-64-NEXT:    image_sample v[5:8], v1, s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX10-64-NEXT:    s_andn2_wrexec_b64 s[10:11], s[10:11]
; GFX10-64-NEXT:    ; implicit-def: $vgpr0
; GFX10-64-NEXT:    ; implicit-def: $vgpr1
; GFX10-64-NEXT:    s_cbranch_execnz .LBB8_1
; GFX10-64-NEXT:  ; %bb.2:
; GFX10-64-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-NEXT:    s_mov_b64 exec, s[8:9]
; GFX10-64-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX10-64-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-NEXT:    v_cmp_gt_f32_e32 vcc, 0, v5
; GFX10-64-NEXT:    s_and_saveexec_b64 s[0:1], vcc
; GFX10-64-NEXT:    s_xor_b64 s[0:1], exec, s[0:1]
; GFX10-64-NEXT:    s_cbranch_execz .LBB8_5
; GFX10-64-NEXT:  ; %bb.3: ; %.kill
; GFX10-64-NEXT:    s_andn2_b64 s[6:7], s[6:7], exec
; GFX10-64-NEXT:    s_cbranch_scc0 .LBB8_6
; GFX10-64-NEXT:  ; %bb.4: ; %.kill
; GFX10-64-NEXT:    s_mov_b64 exec, 0
; GFX10-64-NEXT:  .LBB8_5: ; %.exit
; GFX10-64-NEXT:    s_or_b64 exec, exec, s[0:1]
; GFX10-64-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-64-NEXT:    exp mrt0, v0, off, off, off done vm
; GFX10-64-NEXT:    s_endpgm
; GFX10-64-NEXT:  .LBB8_6:
; GFX10-64-NEXT:    s_mov_b64 exec, 0
; GFX10-64-NEXT:    exp null, off, off, off, off done vm
; GFX10-64-NEXT:    s_endpgm
;
; GFX1150-LABEL: test_waterfall_sample_with_kill:
; GFX1150:       ; %bb.0:
; GFX1150-NEXT:    s_setprio 2
; GFX1150-NEXT:    s_mov_b64 s[6:7], exec
; GFX1150-NEXT:    s_wqm_b64 exec, exec
; GFX1150-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-NEXT:    s_mov_b64 s[10:11], exec
; GFX1150-NEXT:    s_mov_b64 s[8:9], exec
; GFX1150-NEXT:  .LBB8_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-NEXT:    v_readfirstlane_b32 s12, v0
; GFX1150-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(SALU_CYCLE_1)
; GFX1150-NEXT:    v_cmpx_eq_u32_e32 s12, v0
; GFX1150-NEXT:    s_ashr_i32 s13, s12, 31
; GFX1150-NEXT:    s_lshl_b64 s[12:13], s[12:13], 5
; GFX1150-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(SKIP_2) | instid1(SALU_CYCLE_1)
; GFX1150-NEXT:    s_add_u32 s12, s0, s12
; GFX1150-NEXT:    s_addc_u32 s13, s1, s13
; GFX1150-NEXT:    s_ashr_i32 s5, s4, 31
; GFX1150-NEXT:    s_lshl_b64 s[14:15], s[4:5], 4
; GFX1150-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-NEXT:    s_add_u32 s20, s2, s14
; GFX1150-NEXT:    s_addc_u32 s21, s3, s15
; GFX1150-NEXT:    s_load_b256 s[12:19], s[12:13], 0x0
; GFX1150-NEXT:    s_load_b128 s[20:23], s[20:21], 0x0
; GFX1150-NEXT:    s_waitcnt vmcnt(0) lgkmcnt(0)
; GFX1150-NEXT:    image_sample v[5:8], v1, s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX1150-NEXT:    s_and_not1_wrexec_b64 s[10:11], s[10:11]
; GFX1150-NEXT:    ; implicit-def: $vgpr0
; GFX1150-NEXT:    ; implicit-def: $vgpr1
; GFX1150-NEXT:    s_cbranch_execnz .LBB8_1
; GFX1150-NEXT:  ; %bb.2:
; GFX1150-NEXT:    s_mov_b64 exec, s[8:9]
; GFX1150-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(SALU_CYCLE_1)
; GFX1150-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX1150-NEXT:    s_mov_b64 s[0:1], exec
; GFX1150-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-NEXT:    v_cmpx_gt_f32_e32 0, v5
; GFX1150-NEXT:    s_xor_b64 s[0:1], exec, s[0:1]
; GFX1150-NEXT:    s_cbranch_execz .LBB8_5
; GFX1150-NEXT:  ; %bb.3: ; %.kill
; GFX1150-NEXT:    s_and_not1_b64 s[6:7], s[6:7], exec
; GFX1150-NEXT:    s_cbranch_scc0 .LBB8_6
; GFX1150-NEXT:  ; %bb.4: ; %.kill
; GFX1150-NEXT:    s_mov_b64 exec, 0
; GFX1150-NEXT:  .LBB8_5: ; %.exit
; GFX1150-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-NEXT:    s_or_b64 exec, exec, s[0:1]
; GFX1150-NEXT:    v_mov_b32_e32 v0, 0
; GFX1150-NEXT:    exp mrt0, v0, off, off, off done
; GFX1150-NEXT:    s_setprio 0
; GFX1150-NEXT:    s_nop 0
; GFX1150-NEXT:    s_nop 0
; GFX1150-NEXT:    s_endpgm
; GFX1150-NEXT:  .LBB8_6:
; GFX1150-NEXT:    s_mov_b64 exec, 0
; GFX1150-NEXT:    exp mrt0, off, off, off, off done
; GFX1150-NEXT:    s_setprio 0
; GFX1150-NEXT:    s_nop 0
; GFX1150-NEXT:    s_nop 0
; GFX1150-NEXT:    s_endpgm
;
; GFX12-SDAG-LABEL: test_waterfall_sample_with_kill:
; GFX12-SDAG:       ; %bb.0:
; GFX12-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; GFX12-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX12-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-SDAG-NEXT:    s_mov_b64 s[10:11], exec
; GFX12-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX12-SDAG-NEXT:  .LBB8_1: ; =>This Inner Loop Header: Depth=1
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s12, v0
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s12, v0
; GFX12-SDAG-NEXT:    s_ashr_i32 s13, s12, 31
; GFX12-SDAG-NEXT:    s_ashr_i32 s5, s4, 31
; GFX12-SDAG-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-SDAG-NEXT:    s_lshl_b64 s[12:13], s[12:13], 5
; GFX12-SDAG-NEXT:    s_lshl_b64 s[14:15], s[4:5], 4
; GFX12-SDAG-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-SDAG-NEXT:    s_add_nc_u64 s[12:13], s[0:1], s[12:13]
; GFX12-SDAG-NEXT:    s_add_nc_u64 s[20:21], s[2:3], s[14:15]
; GFX12-SDAG-NEXT:    s_load_b256 s[12:19], s[12:13], 0x0
; GFX12-SDAG-NEXT:    s_load_b128 s[20:23], s[20:21], 0x0
; GFX12-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    image_sample v[5:8], v1, s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX12-SDAG-NEXT:    s_and_not1_wrexec_b64 s[10:11], s[10:11]
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr0
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr1
; GFX12-SDAG-NEXT:    s_cbranch_execnz .LBB8_1
; GFX12-SDAG-NEXT:  ; %bb.2:
; GFX12-SDAG-NEXT:    s_mov_b64 exec, s[8:9]
; GFX12-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(SALU_CYCLE_1)
; GFX12-SDAG-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX12-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    v_cmpx_gt_f32_e32 0, v5
; GFX12-SDAG-NEXT:    s_xor_b64 s[0:1], exec, s[0:1]
; GFX12-SDAG-NEXT:    s_cbranch_execz .LBB8_5
; GFX12-SDAG-NEXT:  ; %bb.3: ; %.kill
; GFX12-SDAG-NEXT:    s_and_not1_b64 s[6:7], s[6:7], exec
; GFX12-SDAG-NEXT:    s_cbranch_scc0 .LBB8_6
; GFX12-SDAG-NEXT:  ; %bb.4: ; %.kill
; GFX12-SDAG-NEXT:    s_mov_b64 exec, 0
; GFX12-SDAG-NEXT:  .LBB8_5: ; %.exit
; GFX12-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-SDAG-NEXT:    s_or_b64 exec, exec, s[0:1]
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX12-SDAG-NEXT:    export mrt0, v0, off, off, off done
; GFX12-SDAG-NEXT:    s_endpgm
; GFX12-SDAG-NEXT:  .LBB8_6:
; GFX12-SDAG-NEXT:    s_mov_b64 exec, 0
; GFX12-SDAG-NEXT:    export mrt0, off, off, off, off done
; GFX12-SDAG-NEXT:    s_endpgm
;
; GFX12-GISEL-LABEL: test_waterfall_sample_with_kill:
; GFX12-GISEL:       ; %bb.0:
; GFX12-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX12-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX12-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-GISEL-NEXT:    s_mov_b64 s[10:11], exec
; GFX12-GISEL-NEXT:    s_mov_b64 s[8:9], exec
; GFX12-GISEL-NEXT:  .LBB8_1: ; =>This Inner Loop Header: Depth=1
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s12, v0
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s12, v0
; GFX12-GISEL-NEXT:    s_ashr_i32 s13, s12, 31
; GFX12-GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-GISEL-NEXT:    s_lshl_b64 s[12:13], s[12:13], 5
; GFX12-GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-GISEL-NEXT:    s_add_co_u32 s12, s0, s12
; GFX12-GISEL-NEXT:    s_add_co_ci_u32 s13, s1, s13
; GFX12-GISEL-NEXT:    s_ashr_i32 s5, s4, 31
; GFX12-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(SALU_CYCLE_1)
; GFX12-GISEL-NEXT:    s_lshl_b64 s[14:15], s[4:5], 4
; GFX12-GISEL-NEXT:    s_add_co_u32 s20, s2, s14
; GFX12-GISEL-NEXT:    s_add_co_ci_u32 s21, s3, s15
; GFX12-GISEL-NEXT:    s_load_b256 s[12:19], s[12:13], 0x0
; GFX12-GISEL-NEXT:    s_load_b128 s[20:23], s[20:21], 0x0
; GFX12-GISEL-NEXT:    s_wait_kmcnt 0x0
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    image_sample v[5:8], v1, s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_1D
; GFX12-GISEL-NEXT:    s_and_not1_wrexec_b64 s[10:11], s[10:11]
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr0
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr1
; GFX12-GISEL-NEXT:    s_cbranch_execnz .LBB8_1
; GFX12-GISEL-NEXT:  ; %bb.2:
; GFX12-GISEL-NEXT:    s_mov_b64 exec, s[8:9]
; GFX12-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(SALU_CYCLE_1)
; GFX12-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX12-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    v_cmpx_gt_f32_e32 0, v5
; GFX12-GISEL-NEXT:    s_xor_b64 s[0:1], exec, s[0:1]
; GFX12-GISEL-NEXT:    s_cbranch_execz .LBB8_5
; GFX12-GISEL-NEXT:  ; %bb.3: ; %.kill
; GFX12-GISEL-NEXT:    s_and_not1_b64 s[6:7], s[6:7], exec
; GFX12-GISEL-NEXT:    s_cbranch_scc0 .LBB8_6
; GFX12-GISEL-NEXT:  ; %bb.4: ; %.kill
; GFX12-GISEL-NEXT:    s_mov_b64 exec, 0
; GFX12-GISEL-NEXT:  .LBB8_5: ; %.exit
; GFX12-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-GISEL-NEXT:    s_or_b64 exec, exec, s[0:1]
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX12-GISEL-NEXT:    export mrt0, v0, off, off, off done
; GFX12-GISEL-NEXT:    s_endpgm
; GFX12-GISEL-NEXT:  .LBB8_6:
; GFX12-GISEL-NEXT:    s_mov_b64 exec, 0
; GFX12-GISEL-NEXT:    export mrt0, off, off, off, off done
; GFX12-GISEL-NEXT:    s_endpgm
  %wf_token = call token @llvm.amdgcn.waterfall.begin.i32(token poison, i32 %index)
  %s_idx = call i32 @llvm.amdgcn.waterfall.readfirstlane.i32.i32(token %wf_token, i32 %index)
  %s_idx2 = call i32 @llvm.amdgcn.waterfall.readfirstlane.i32.i32(token %wf_token, i32 %val)
  %ptr = getelementptr <8 x i32>, <8 x i32> addrspace(4)* %in, i32 %s_idx
  %ptr2 = getelementptr <4 x i32>, <4 x i32> addrspace(4)* %samp_in, i32 %s_idx2
  %rsrc = load <8 x i32>, <8 x i32> addrspace(4) * %ptr, align 32
  %samp = load <4 x i32>, <4 x i32> addrspace(4) * %ptr2, align 32
  %r = call <4 x float> @llvm.amdgcn.image.sample.1d.v4f32.f32(i32 15, float %s, <8 x i32> %rsrc, <4 x i32> %samp, i1 0, i32 0, i32 0)
  %r1 = call <4 x float> @llvm.amdgcn.waterfall.end.v4f32(token %wf_token, <4 x float> %r)
  %r2 = extractelement <4 x float> %r1, i32 0
  %cond = fcmp olt float %r2, 0.000000e+00
  br i1 %cond, label %.kill, label %.exit

.kill:
  call void @llvm.amdgcn.kill(i1 false)
  br label %.exit

.exit:
  call void @llvm.amdgcn.exp.f32(i32 immarg 0, i32 immarg 1, float 0.000000e+00, float %dummy_f0, float %dummy_f1, float %dummy_f2, i1 immarg true, i1 immarg true)
  ret void
}


define amdgpu_ps <4 x float> @test_waterfall_multi_begin(<8 x i32> addrspace(4)* inreg %in, <4 x i32> addrspace(4)* inreg %s_in,
; VI-SDAG-LABEL: test_waterfall_multi_begin:
; VI-SDAG:       ; %bb.0:
; VI-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; VI-SDAG-NEXT:    s_wqm_b64 exec, exec
; VI-SDAG-NEXT:    v_mov_b32_e32 v7, v2
; VI-SDAG-NEXT:    v_ashrrev_i32_e32 v8, 31, v7
; VI-SDAG-NEXT:    v_mov_b32_e32 v6, v1
; VI-SDAG-NEXT:    v_mov_b32_e32 v5, v0
; VI-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[7:8]
; VI-SDAG-NEXT:    v_mov_b32_e32 v2, s1
; VI-SDAG-NEXT:    v_add_u32_e32 v0, vcc, s0, v0
; VI-SDAG-NEXT:    v_ashrrev_i32_e32 v4, 31, v3
; VI-SDAG-NEXT:    v_addc_u32_e32 v1, vcc, v2, v1, vcc
; VI-SDAG-NEXT:    v_lshlrev_b64 v[2:3], 4, v[3:4]
; VI-SDAG-NEXT:    v_mov_b32_e32 v4, s3
; VI-SDAG-NEXT:    v_add_u32_e32 v2, vcc, s2, v2
; VI-SDAG-NEXT:    v_addc_u32_e32 v3, vcc, v4, v3, vcc
; VI-SDAG-NEXT:    flat_load_dwordx4 v[7:10], v[0:1]
; VI-SDAG-NEXT:    v_add_u32_e32 v0, vcc, 16, v0
; VI-SDAG-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-SDAG-NEXT:    flat_load_dwordx4 v[11:14], v[0:1]
; VI-SDAG-NEXT:    flat_load_dwordx4 v[15:18], v[2:3]
; VI-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; VI-SDAG-NEXT:  .LBB9_1: ; =>This Inner Loop Header: Depth=1
; VI-SDAG-NEXT:    v_readfirstlane_b32 s2, v5
; VI-SDAG-NEXT:    v_readfirstlane_b32 s6, v6
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v5
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[6:7], s6, v6
; VI-SDAG-NEXT:    s_and_b64 s[2:3], s[2:3], s[6:7]
; VI-SDAG-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; VI-SDAG-NEXT:    s_waitcnt vmcnt(2)
; VI-SDAG-NEXT:    v_readfirstlane_b32 s8, v7
; VI-SDAG-NEXT:    v_readfirstlane_b32 s9, v8
; VI-SDAG-NEXT:    v_readfirstlane_b32 s10, v9
; VI-SDAG-NEXT:    v_readfirstlane_b32 s11, v10
; VI-SDAG-NEXT:    s_waitcnt vmcnt(1)
; VI-SDAG-NEXT:    v_readfirstlane_b32 s12, v11
; VI-SDAG-NEXT:    v_readfirstlane_b32 s13, v12
; VI-SDAG-NEXT:    v_readfirstlane_b32 s14, v13
; VI-SDAG-NEXT:    v_readfirstlane_b32 s15, v14
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    v_readfirstlane_b32 s16, v15
; VI-SDAG-NEXT:    v_readfirstlane_b32 s17, v16
; VI-SDAG-NEXT:    v_readfirstlane_b32 s18, v17
; VI-SDAG-NEXT:    v_readfirstlane_b32 s19, v18
; VI-SDAG-NEXT:    v_mov_b32_e32 v1, v0
; VI-SDAG-NEXT:    ; implicit-def: $vgpr5
; VI-SDAG-NEXT:    ; implicit-def: $vgpr6
; VI-SDAG-NEXT:    ; implicit-def: $vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14
; VI-SDAG-NEXT:    ; implicit-def: $vgpr15_vgpr16_vgpr17_vgpr18
; VI-SDAG-NEXT:    s_nop 3
; VI-SDAG-NEXT:    image_sample v[0:3], v[0:1], s[8:15], s[16:19] dmask:0xf
; VI-SDAG-NEXT:    s_xor_b64 exec, exec, s[2:3]
; VI-SDAG-NEXT:    s_cbranch_execnz .LBB9_1
; VI-SDAG-NEXT:  ; %bb.2:
; VI-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; VI-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    ; return to shader part epilog
;
; VI-GISEL-LABEL: test_waterfall_multi_begin:
; VI-GISEL:       ; %bb.0:
; VI-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; VI-GISEL-NEXT:    s_wqm_b64 exec, exec
; VI-GISEL-NEXT:    v_mov_b32_e32 v6, v3
; VI-GISEL-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; VI-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; VI-GISEL-NEXT:    v_mov_b32_e32 v5, v1
; VI-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[2:3]
; VI-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; VI-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; VI-GISEL-NEXT:    v_add_u32_e32 v0, vcc, v2, v0
; VI-GISEL-NEXT:    v_ashrrev_i32_e32 v7, 31, v6
; VI-GISEL-NEXT:    v_addc_u32_e32 v1, vcc, v3, v1, vcc
; VI-GISEL-NEXT:    v_lshlrev_b64 v[2:3], 4, v[6:7]
; VI-GISEL-NEXT:    v_mov_b32_e32 v7, s3
; VI-GISEL-NEXT:    v_mov_b32_e32 v6, s2
; VI-GISEL-NEXT:    v_add_u32_e32 v2, vcc, v6, v2
; VI-GISEL-NEXT:    v_addc_u32_e32 v3, vcc, v7, v3, vcc
; VI-GISEL-NEXT:    flat_load_dwordx4 v[6:9], v[0:1]
; VI-GISEL-NEXT:    v_add_u32_e32 v0, vcc, 16, v0
; VI-GISEL-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-GISEL-NEXT:    flat_load_dwordx4 v[10:13], v[0:1]
; VI-GISEL-NEXT:    flat_load_dwordx4 v[14:17], v[2:3]
; VI-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; VI-GISEL-NEXT:  .LBB9_1: ; =>This Inner Loop Header: Depth=1
; VI-GISEL-NEXT:    v_readfirstlane_b32 s2, v4
; VI-GISEL-NEXT:    v_readfirstlane_b32 s6, v5
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v4
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[6:7], s6, v5
; VI-GISEL-NEXT:    s_and_b64 s[2:3], s[2:3], s[6:7]
; VI-GISEL-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; VI-GISEL-NEXT:    s_mov_b32 s6, 0
; VI-GISEL-NEXT:    s_mov_b32 s7, s6
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    v_mov_b32_e32 v0, s6
; VI-GISEL-NEXT:    s_waitcnt vmcnt(2)
; VI-GISEL-NEXT:    v_readfirstlane_b32 s8, v6
; VI-GISEL-NEXT:    v_readfirstlane_b32 s9, v7
; VI-GISEL-NEXT:    v_readfirstlane_b32 s10, v8
; VI-GISEL-NEXT:    v_readfirstlane_b32 s11, v9
; VI-GISEL-NEXT:    s_waitcnt vmcnt(1)
; VI-GISEL-NEXT:    v_readfirstlane_b32 s12, v10
; VI-GISEL-NEXT:    v_readfirstlane_b32 s13, v11
; VI-GISEL-NEXT:    v_readfirstlane_b32 s14, v12
; VI-GISEL-NEXT:    v_readfirstlane_b32 s15, v13
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    v_readfirstlane_b32 s16, v14
; VI-GISEL-NEXT:    v_readfirstlane_b32 s17, v15
; VI-GISEL-NEXT:    v_readfirstlane_b32 s18, v16
; VI-GISEL-NEXT:    v_readfirstlane_b32 s19, v17
; VI-GISEL-NEXT:    v_mov_b32_e32 v1, s7
; VI-GISEL-NEXT:    ; implicit-def: $vgpr4
; VI-GISEL-NEXT:    ; implicit-def: $vgpr5
; VI-GISEL-NEXT:    ; implicit-def: $vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13
; VI-GISEL-NEXT:    ; implicit-def: $vgpr14_vgpr15_vgpr16_vgpr17
; VI-GISEL-NEXT:    s_nop 3
; VI-GISEL-NEXT:    image_sample v[0:3], v[0:1], s[8:15], s[16:19] dmask:0xf
; VI-GISEL-NEXT:    s_xor_b64 exec, exec, s[2:3]
; VI-GISEL-NEXT:    s_cbranch_execnz .LBB9_1
; VI-GISEL-NEXT:  ; %bb.2:
; VI-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; VI-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    ; return to shader part epilog
;
; GFX9-SDAG-LABEL: test_waterfall_multi_begin:
; GFX9-SDAG:       ; %bb.0:
; GFX9-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX9-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v7, v2
; GFX9-SDAG-NEXT:    v_ashrrev_i32_e32 v8, 31, v7
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v6, v1
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v5, v0
; GFX9-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[7:8]
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v2, s1
; GFX9-SDAG-NEXT:    v_add_co_u32_e32 v0, vcc, s0, v0
; GFX9-SDAG-NEXT:    v_ashrrev_i32_e32 v4, 31, v3
; GFX9-SDAG-NEXT:    v_addc_co_u32_e32 v1, vcc, v2, v1, vcc
; GFX9-SDAG-NEXT:    v_lshlrev_b64 v[2:3], 4, v[3:4]
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v4, s3
; GFX9-SDAG-NEXT:    v_add_co_u32_e32 v2, vcc, s2, v2
; GFX9-SDAG-NEXT:    v_addc_co_u32_e32 v3, vcc, v4, v3, vcc
; GFX9-SDAG-NEXT:    global_load_dwordx4 v[11:14], v[0:1], off offset:16
; GFX9-SDAG-NEXT:    global_load_dwordx4 v[7:10], v[0:1], off
; GFX9-SDAG-NEXT:    global_load_dwordx4 v[15:18], v[2:3], off
; GFX9-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX9-SDAG-NEXT:  .LBB9_1: ; =>This Inner Loop Header: Depth=1
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s2, v5
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s6, v6
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v5
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[6:7], s6, v6
; GFX9-SDAG-NEXT:    s_and_b64 s[2:3], s[2:3], s[6:7]
; GFX9-SDAG-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(1)
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s8, v7
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s9, v8
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s10, v9
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s11, v10
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s12, v11
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s13, v12
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s14, v13
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s15, v14
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s16, v15
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s17, v16
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s18, v17
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s19, v18
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v1, v0
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr6
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr15_vgpr16_vgpr17_vgpr18
; GFX9-SDAG-NEXT:    s_nop 3
; GFX9-SDAG-NEXT:    image_sample v[0:3], v[0:1], s[8:15], s[16:19] dmask:0xf
; GFX9-SDAG-NEXT:    s_xor_b64 exec, exec, s[2:3]
; GFX9-SDAG-NEXT:    s_cbranch_execnz .LBB9_1
; GFX9-SDAG-NEXT:  ; %bb.2:
; GFX9-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX9-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    ; return to shader part epilog
;
; GFX9-GISEL-LABEL: test_waterfall_multi_begin:
; GFX9-GISEL:       ; %bb.0:
; GFX9-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX9-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v6, v3
; GFX9-GISEL-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v5, v1
; GFX9-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[2:3]
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX9-GISEL-NEXT:    v_add_co_u32_e32 v0, vcc, v2, v0
; GFX9-GISEL-NEXT:    v_ashrrev_i32_e32 v7, 31, v6
; GFX9-GISEL-NEXT:    v_addc_co_u32_e32 v1, vcc, v3, v1, vcc
; GFX9-GISEL-NEXT:    v_lshlrev_b64 v[2:3], 4, v[6:7]
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v7, s3
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v6, s2
; GFX9-GISEL-NEXT:    v_add_co_u32_e32 v2, vcc, v6, v2
; GFX9-GISEL-NEXT:    v_addc_co_u32_e32 v3, vcc, v7, v3, vcc
; GFX9-GISEL-NEXT:    global_load_dwordx4 v[6:9], v[0:1], off
; GFX9-GISEL-NEXT:    global_load_dwordx4 v[10:13], v[0:1], off offset:16
; GFX9-GISEL-NEXT:    global_load_dwordx4 v[14:17], v[2:3], off
; GFX9-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX9-GISEL-NEXT:  .LBB9_1: ; =>This Inner Loop Header: Depth=1
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s2, v4
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s6, v5
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v4
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[6:7], s6, v5
; GFX9-GISEL-NEXT:    s_and_b64 s[2:3], s[2:3], s[6:7]
; GFX9-GISEL-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; GFX9-GISEL-NEXT:    s_mov_b32 s6, 0
; GFX9-GISEL-NEXT:    s_mov_b32 s7, s6
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v0, s6
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(2)
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s8, v6
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s9, v7
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s10, v8
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s11, v9
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(1)
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s12, v10
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s13, v11
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s14, v12
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s15, v13
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s16, v14
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s17, v15
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s18, v16
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s19, v17
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v1, s7
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr14_vgpr15_vgpr16_vgpr17
; GFX9-GISEL-NEXT:    s_nop 3
; GFX9-GISEL-NEXT:    image_sample v[0:3], v[0:1], s[8:15], s[16:19] dmask:0xf
; GFX9-GISEL-NEXT:    s_xor_b64 exec, exec, s[2:3]
; GFX9-GISEL-NEXT:    s_cbranch_execnz .LBB9_1
; GFX9-GISEL-NEXT:  ; %bb.2:
; GFX9-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX9-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-32-SDAG-LABEL: test_waterfall_multi_begin:
; GFX10-32-SDAG:       ; %bb.0:
; GFX10-32-SDAG-NEXT:    s_mov_b32 s4, exec_lo
; GFX10-32-SDAG-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v7, v2
; GFX10-32-SDAG-NEXT:    v_ashrrev_i32_e32 v4, 31, v3
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v6, v1
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v5, v0
; GFX10-32-SDAG-NEXT:    v_ashrrev_i32_e32 v8, 31, v7
; GFX10-32-SDAG-NEXT:    v_lshlrev_b64 v[2:3], 4, v[3:4]
; GFX10-32-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[7:8]
; GFX10-32-SDAG-NEXT:    v_add_co_u32 v0, vcc_lo, s0, v0
; GFX10-32-SDAG-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, s1, v1, vcc_lo
; GFX10-32-SDAG-NEXT:    v_add_co_u32 v2, vcc_lo, s2, v2
; GFX10-32-SDAG-NEXT:    v_add_co_ci_u32_e32 v3, vcc_lo, s3, v3, vcc_lo
; GFX10-32-SDAG-NEXT:    s_clause 0x1
; GFX10-32-SDAG-NEXT:    global_load_dwordx4 v[11:14], v[0:1], off offset:16
; GFX10-32-SDAG-NEXT:    global_load_dwordx4 v[7:10], v[0:1], off
; GFX10-32-SDAG-NEXT:    global_load_dwordx4 v[15:18], v[2:3], off
; GFX10-32-SDAG-NEXT:    s_mov_b32 s1, exec_lo
; GFX10-32-SDAG-NEXT:    s_mov_b32 s0, exec_lo
; GFX10-32-SDAG-NEXT:  .LBB9_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s2, v5
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s3, v6
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s2, v5
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s3, v6
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(1)
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s8, v7
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s9, v8
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s10, v9
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s11, v10
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s12, v11
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s13, v12
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s14, v13
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s15, v14
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s16, v15
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s17, v16
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s18, v17
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s19, v18
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-32-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-32-SDAG-NEXT:    s_andn2_wrexec_b32 s1, s1
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr6
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr15_vgpr16_vgpr17_vgpr18
; GFX10-32-SDAG-NEXT:    s_cbranch_execnz .LBB9_1
; GFX10-32-SDAG-NEXT:  ; %bb.2:
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-SDAG-NEXT:    s_mov_b32 exec_lo, s0
; GFX10-32-SDAG-NEXT:    s_and_b32 exec_lo, exec_lo, s4
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-32-GISEL-LABEL: test_waterfall_multi_begin:
; GFX10-32-GISEL:       ; %bb.0:
; GFX10-32-GISEL-NEXT:    s_mov_b32 s4, exec_lo
; GFX10-32-GISEL-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v6, v3
; GFX10-32-GISEL-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v5, v1
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v9, s3
; GFX10-32-GISEL-NEXT:    v_ashrrev_i32_e32 v7, 31, v6
; GFX10-32-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[2:3]
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v8, s2
; GFX10-32-GISEL-NEXT:    v_lshlrev_b64 v[6:7], 4, v[6:7]
; GFX10-32-GISEL-NEXT:    s_mov_b32 s1, exec_lo
; GFX10-32-GISEL-NEXT:    s_mov_b32 s0, exec_lo
; GFX10-32-GISEL-NEXT:    v_add_co_u32 v0, vcc_lo, v2, v0
; GFX10-32-GISEL-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, v3, v1, vcc_lo
; GFX10-32-GISEL-NEXT:    v_add_co_u32 v2, vcc_lo, v8, v6
; GFX10-32-GISEL-NEXT:    v_add_co_ci_u32_e32 v3, vcc_lo, v9, v7, vcc_lo
; GFX10-32-GISEL-NEXT:    s_clause 0x1
; GFX10-32-GISEL-NEXT:    global_load_dwordx4 v[6:9], v[0:1], off
; GFX10-32-GISEL-NEXT:    global_load_dwordx4 v[10:13], v[0:1], off offset:16
; GFX10-32-GISEL-NEXT:    global_load_dwordx4 v[14:17], v[2:3], off
; GFX10-32-GISEL-NEXT:  .LBB9_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s2, v4
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s3, v5
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s2, v4
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s3, v5
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(2)
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s8, v6
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s9, v7
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s10, v8
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s11, v9
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(1)
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s12, v10
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s13, v11
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s14, v12
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s15, v13
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s16, v14
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s17, v15
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s18, v16
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s19, v17
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-32-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-32-GISEL-NEXT:    s_andn2_wrexec_b32 s1, s1
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr14_vgpr15_vgpr16_vgpr17
; GFX10-32-GISEL-NEXT:    s_cbranch_execnz .LBB9_1
; GFX10-32-GISEL-NEXT:  ; %bb.2:
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-GISEL-NEXT:    s_mov_b32 exec_lo, s0
; GFX10-32-GISEL-NEXT:    s_and_b32 exec_lo, exec_lo, s4
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-64-SDAG-LABEL: test_waterfall_multi_begin:
; GFX10-64-SDAG:       ; %bb.0:
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX10-64-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v7, v2
; GFX10-64-SDAG-NEXT:    v_ashrrev_i32_e32 v4, 31, v3
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v6, v1
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v5, v0
; GFX10-64-SDAG-NEXT:    v_ashrrev_i32_e32 v8, 31, v7
; GFX10-64-SDAG-NEXT:    v_lshlrev_b64 v[2:3], 4, v[3:4]
; GFX10-64-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[7:8]
; GFX10-64-SDAG-NEXT:    v_add_co_u32 v0, vcc, s0, v0
; GFX10-64-SDAG-NEXT:    v_add_co_ci_u32_e32 v1, vcc, s1, v1, vcc
; GFX10-64-SDAG-NEXT:    v_add_co_u32 v2, vcc, s2, v2
; GFX10-64-SDAG-NEXT:    v_add_co_ci_u32_e32 v3, vcc, s3, v3, vcc
; GFX10-64-SDAG-NEXT:    s_clause 0x1
; GFX10-64-SDAG-NEXT:    global_load_dwordx4 v[11:14], v[0:1], off offset:16
; GFX10-64-SDAG-NEXT:    global_load_dwordx4 v[7:10], v[0:1], off
; GFX10-64-SDAG-NEXT:    global_load_dwordx4 v[15:18], v[2:3], off
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX10-64-SDAG-NEXT:  .LBB9_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s6, v5
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s7, v6
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s6, v5
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s7, v6
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(1)
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s8, v7
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s9, v8
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s10, v9
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s11, v10
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s12, v11
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s13, v12
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s14, v13
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s15, v14
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s16, v15
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s17, v16
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s18, v17
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s19, v18
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-64-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-64-SDAG-NEXT:    s_andn2_wrexec_b64 s[2:3], s[2:3]
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr6
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr15_vgpr16_vgpr17_vgpr18
; GFX10-64-SDAG-NEXT:    s_cbranch_execnz .LBB9_1
; GFX10-64-SDAG-NEXT:  ; %bb.2:
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX10-64-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-64-GISEL-LABEL: test_waterfall_multi_begin:
; GFX10-64-GISEL:       ; %bb.0:
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX10-64-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v6, v3
; GFX10-64-GISEL-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v5, v1
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v9, s3
; GFX10-64-GISEL-NEXT:    v_ashrrev_i32_e32 v7, 31, v6
; GFX10-64-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[2:3]
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v8, s2
; GFX10-64-GISEL-NEXT:    v_lshlrev_b64 v[6:7], 4, v[6:7]
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX10-64-GISEL-NEXT:    v_add_co_u32 v0, vcc, v2, v0
; GFX10-64-GISEL-NEXT:    v_add_co_ci_u32_e32 v1, vcc, v3, v1, vcc
; GFX10-64-GISEL-NEXT:    v_add_co_u32 v2, vcc, v8, v6
; GFX10-64-GISEL-NEXT:    v_add_co_ci_u32_e32 v3, vcc, v9, v7, vcc
; GFX10-64-GISEL-NEXT:    s_clause 0x1
; GFX10-64-GISEL-NEXT:    global_load_dwordx4 v[6:9], v[0:1], off
; GFX10-64-GISEL-NEXT:    global_load_dwordx4 v[10:13], v[0:1], off offset:16
; GFX10-64-GISEL-NEXT:    global_load_dwordx4 v[14:17], v[2:3], off
; GFX10-64-GISEL-NEXT:  .LBB9_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s6, v4
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s7, v5
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s6, v4
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s7, v5
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(2)
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s8, v6
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s9, v7
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s10, v8
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s11, v9
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(1)
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s12, v10
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s13, v11
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s14, v12
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s15, v13
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s16, v14
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s17, v15
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s18, v16
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s19, v17
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-64-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-64-GISEL-NEXT:    s_andn2_wrexec_b64 s[2:3], s[2:3]
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr14_vgpr15_vgpr16_vgpr17
; GFX10-64-GISEL-NEXT:    s_cbranch_execnz .LBB9_1
; GFX10-64-GISEL-NEXT:  ; %bb.2:
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX10-64-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:    ; return to shader part epilog
;
; GFX1150-SDAG-LABEL: test_waterfall_multi_begin:
; GFX1150-SDAG:       ; %bb.0:
; GFX1150-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX1150-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v7, v2
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v6, v1
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v5, v0
; GFX1150-SDAG-NEXT:    v_ashrrev_i32_e32 v4, 31, v3
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX1150-SDAG-NEXT:    v_ashrrev_i32_e32 v8, 31, v7
; GFX1150-SDAG-NEXT:    v_lshlrev_b64 v[2:3], 4, v[3:4]
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX1150-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[7:8]
; GFX1150-SDAG-NEXT:    v_add_co_u32 v0, vcc, s0, v0
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX1150-SDAG-NEXT:    v_add_co_ci_u32_e64 v1, null, s1, v1, vcc
; GFX1150-SDAG-NEXT:    v_add_co_u32 v2, vcc, s2, v2
; GFX1150-SDAG-NEXT:    s_waitcnt_depctr depctr_va_vcc(0)
; GFX1150-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX1150-SDAG-NEXT:    v_add_co_ci_u32_e64 v3, null, s3, v3, vcc
; GFX1150-SDAG-NEXT:    s_clause 0x1
; GFX1150-SDAG-NEXT:    global_load_b128 v[11:14], v[0:1], off offset:16
; GFX1150-SDAG-NEXT:    global_load_b128 v[7:10], v[0:1], off
; GFX1150-SDAG-NEXT:    global_load_b128 v[15:18], v[2:3], off
; GFX1150-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX1150-SDAG-NEXT:  .LBB9_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s6, v5
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s7, v6
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s6, v5
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s7, v6
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(1)
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s8, v7
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s9, v8
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s10, v9
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s11, v10
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s12, v11
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s13, v12
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s14, v13
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s15, v14
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s16, v15
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s17, v16
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s18, v17
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s19, v18
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX1150-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX1150-SDAG-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr6
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr15_vgpr16_vgpr17_vgpr18
; GFX1150-SDAG-NEXT:    s_cbranch_execnz .LBB9_1
; GFX1150-SDAG-NEXT:  ; %bb.2:
; GFX1150-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:    ; return to shader part epilog
;
; GFX1150-GISEL-LABEL: test_waterfall_multi_begin:
; GFX1150-GISEL:       ; %bb.0:
; GFX1150-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX1150-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v6, v3
; GFX1150-GISEL-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v5, v1
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v9, s3
; GFX1150-GISEL-NEXT:    v_ashrrev_i32_e32 v7, 31, v6
; GFX1150-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[2:3]
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v8, s2
; GFX1150-GISEL-NEXT:    v_lshlrev_b64 v[6:7], 4, v[6:7]
; GFX1150-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX1150-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX1150-GISEL-NEXT:    v_add_co_u32 v0, vcc, v2, v0
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX1150-GISEL-NEXT:    v_add_co_ci_u32_e64 v1, null, v3, v1, vcc
; GFX1150-GISEL-NEXT:    v_add_co_u32 v2, vcc, v8, v6
; GFX1150-GISEL-NEXT:    s_waitcnt_depctr depctr_va_vcc(0)
; GFX1150-GISEL-NEXT:    v_add_co_ci_u32_e64 v3, null, v9, v7, vcc
; GFX1150-GISEL-NEXT:    s_clause 0x1
; GFX1150-GISEL-NEXT:    global_load_b128 v[6:9], v[0:1], off
; GFX1150-GISEL-NEXT:    global_load_b128 v[10:13], v[0:1], off offset:16
; GFX1150-GISEL-NEXT:    global_load_b128 v[14:17], v[2:3], off
; GFX1150-GISEL-NEXT:  .LBB9_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s6, v4
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s7, v5
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s6, v4
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s7, v5
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(2)
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s8, v6
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s9, v7
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s10, v8
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s11, v9
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(1)
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s12, v10
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s13, v11
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s14, v12
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s15, v13
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s16, v14
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s17, v15
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s18, v16
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s19, v17
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX1150-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX1150-GISEL-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr14_vgpr15_vgpr16_vgpr17
; GFX1150-GISEL-NEXT:    s_cbranch_execnz .LBB9_1
; GFX1150-GISEL-NEXT:  ; %bb.2:
; GFX1150-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    ; return to shader part epilog
;
; GFX12-SDAG-LABEL: test_waterfall_multi_begin:
; GFX12-SDAG:       ; %bb.0:
; GFX12-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX12-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v7, v2
; GFX12-SDAG-NEXT:    v_ashrrev_i32_e32 v4, 31, v3
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v6, v1
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v5, v0
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX12-SDAG-NEXT:    v_ashrrev_i32_e32 v8, 31, v7
; GFX12-SDAG-NEXT:    v_lshlrev_b64_e32 v[2:3], 4, v[3:4]
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX12-SDAG-NEXT:    v_lshlrev_b64_e32 v[0:1], 5, v[7:8]
; GFX12-SDAG-NEXT:    v_add_co_u32 v0, vcc, s0, v0
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX12-SDAG-NEXT:    v_add_co_ci_u32_e64 v1, null, s1, v1, vcc
; GFX12-SDAG-NEXT:    v_add_co_u32 v2, vcc, s2, v2
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_vcc(0)
; GFX12-SDAG-NEXT:    v_add_co_ci_u32_e64 v3, null, s3, v3, vcc
; GFX12-SDAG-NEXT:    s_clause 0x1
; GFX12-SDAG-NEXT:    global_load_b128 v[11:14], v[0:1], off offset:16
; GFX12-SDAG-NEXT:    global_load_b128 v[7:10], v[0:1], off
; GFX12-SDAG-NEXT:    global_load_b128 v[15:18], v[2:3], off
; GFX12-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX12-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX12-SDAG-NEXT:  .LBB9_1: ; =>This Inner Loop Header: Depth=1
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s6, v5
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s7, v6
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s6, v5
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s7, v6
; GFX12-SDAG-NEXT:    s_wait_loadcnt 0x1
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s8, v7
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s9, v8
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s10, v9
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s11, v10
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s12, v11
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s13, v12
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s14, v13
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s15, v14
; GFX12-SDAG-NEXT:    s_wait_loadcnt 0x0
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s16, v15
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s17, v16
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s18, v17
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s19, v18
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX12-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX12-SDAG-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr6
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr15_vgpr16_vgpr17_vgpr18
; GFX12-SDAG-NEXT:    s_cbranch_execnz .LBB9_1
; GFX12-SDAG-NEXT:  ; %bb.2:
; GFX12-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX12-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-SDAG-NEXT:    ; return to shader part epilog
;
; GFX12-GISEL-LABEL: test_waterfall_multi_begin:
; GFX12-GISEL:       ; %bb.0:
; GFX12-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX12-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v6, v3
; GFX12-GISEL-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v5, v1
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v9, s3
; GFX12-GISEL-NEXT:    v_ashrrev_i32_e32 v7, 31, v6
; GFX12-GISEL-NEXT:    v_lshlrev_b64_e32 v[0:1], 5, v[2:3]
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v8, s2
; GFX12-GISEL-NEXT:    v_lshlrev_b64_e32 v[6:7], 4, v[6:7]
; GFX12-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX12-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX12-GISEL-NEXT:    v_add_co_u32 v0, vcc, v2, v0
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX12-GISEL-NEXT:    v_add_co_ci_u32_e64 v1, null, v3, v1, vcc
; GFX12-GISEL-NEXT:    v_add_co_u32 v2, vcc, v8, v6
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_vcc(0)
; GFX12-GISEL-NEXT:    v_add_co_ci_u32_e64 v3, null, v9, v7, vcc
; GFX12-GISEL-NEXT:    s_clause 0x1
; GFX12-GISEL-NEXT:    global_load_b128 v[6:9], v[0:1], off
; GFX12-GISEL-NEXT:    global_load_b128 v[10:13], v[0:1], off offset:16
; GFX12-GISEL-NEXT:    global_load_b128 v[14:17], v[2:3], off
; GFX12-GISEL-NEXT:  .LBB9_1: ; =>This Inner Loop Header: Depth=1
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s6, v4
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s7, v5
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s6, v4
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s7, v5
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x2
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s8, v6
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s9, v7
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s10, v8
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s11, v9
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x1
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s12, v10
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s13, v11
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s14, v12
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s15, v13
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x0
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s16, v14
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s17, v15
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s18, v16
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s19, v17
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX12-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX12-GISEL-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr14_vgpr15_vgpr16_vgpr17
; GFX12-GISEL-NEXT:    s_cbranch_execnz .LBB9_1
; GFX12-GISEL-NEXT:  ; %bb.2:
; GFX12-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX12-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-GISEL-NEXT:    ; return to shader part epilog
                                                         i32 %idx1, i32 %idx2, i32 %s_idx, i32 %s_idx2) #1 {
  %rptr = getelementptr <8 x i32>, <8 x i32> addrspace(4)* %in, i32 %s_idx
  %sptr = getelementptr <4 x i32>, <4 x i32> addrspace(4)* %s_in, i32 %s_idx2
  %rsrc = load <8 x i32>, <8 x i32> addrspace(4)* %rptr, align 16
  %srsrc = load <4 x i32>, <4 x i32> addrspace(4)* %sptr, align 16
  %tok = call token @llvm.amdgcn.waterfall.begin.i32(token poison, i32 %idx1)
  %tok1 = call token @llvm.amdgcn.waterfall.begin.i32(token %tok, i32 %idx2)
  %s_rsrc = call <8 x i32> @llvm.amdgcn.waterfall.readfirstlane.v8i32.v8i32(token %tok1, <8 x i32> %rsrc)
  %s_srsrc = call <4 x i32> @llvm.amdgcn.waterfall.readfirstlane.v4i32.v4i32(token %tok1, <4 x i32> %srsrc)
  %r = call <4 x float> @llvm.amdgcn.image.sample.2d.v4f32.f32(i32 15, float 0.000000e+00, float 0.000000e+00, <8 x i32> %s_rsrc, <4 x i32> %s_srsrc, i1 false, i32 0, i32 0)
  %r1 = call <4 x float> @llvm.amdgcn.waterfall.end.v4f32(token %tok1, <4 x float> %r)

  ret <4 x float> %r1
}

define amdgpu_ps <4 x float> @test_waterfall_full_idx_multi_begin(<8 x i32> addrspace(4)* inreg %in, <4 x i32> addrspace(4)* inreg %s_in,
; VI-SDAG-LABEL: test_waterfall_full_idx_multi_begin:
; VI-SDAG:       ; %bb.0:
; VI-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; VI-SDAG-NEXT:    s_wqm_b64 exec, exec
; VI-SDAG-NEXT:    v_mov_b32_e32 v2, v0
; VI-SDAG-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; VI-SDAG-NEXT:    v_lshlrev_b64 v[2:3], 5, v[2:3]
; VI-SDAG-NEXT:    v_mov_b32_e32 v0, s1
; VI-SDAG-NEXT:    v_add_u32_e32 v8, vcc, s0, v2
; VI-SDAG-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; VI-SDAG-NEXT:    v_addc_u32_e32 v9, vcc, v0, v3, vcc
; VI-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 4, v[1:2]
; VI-SDAG-NEXT:    v_mov_b32_e32 v2, s3
; VI-SDAG-NEXT:    v_add_u32_e32 v0, vcc, s2, v0
; VI-SDAG-NEXT:    v_addc_u32_e32 v1, vcc, v2, v1, vcc
; VI-SDAG-NEXT:    v_add_u32_e32 v2, vcc, 16, v8
; VI-SDAG-NEXT:    v_addc_u32_e32 v3, vcc, 0, v9, vcc
; VI-SDAG-NEXT:    flat_load_dwordx4 v[4:7], v[8:9]
; VI-SDAG-NEXT:    flat_load_dwordx4 v[8:11], v[2:3]
; VI-SDAG-NEXT:    flat_load_dwordx4 v[12:15], v[0:1]
; VI-SDAG-NEXT:    s_mov_b64 s[10:11], exec
; VI-SDAG-NEXT:  .LBB10_1: ; =>This Inner Loop Header: Depth=1
; VI-SDAG-NEXT:    s_waitcnt vmcnt(2)
; VI-SDAG-NEXT:    v_readfirstlane_b32 s0, v4
; VI-SDAG-NEXT:    v_readfirstlane_b32 s1, v5
; VI-SDAG-NEXT:    v_readfirstlane_b32 s2, v6
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[16:17], s0, v4
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[18:19], s1, v5
; VI-SDAG-NEXT:    v_readfirstlane_b32 s3, v7
; VI-SDAG-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[18:19], s2, v6
; VI-SDAG-NEXT:    s_waitcnt vmcnt(1)
; VI-SDAG-NEXT:    v_readfirstlane_b32 s4, v8
; VI-SDAG-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[18:19], s3, v7
; VI-SDAG-NEXT:    v_readfirstlane_b32 s5, v9
; VI-SDAG-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[18:19], s4, v8
; VI-SDAG-NEXT:    v_readfirstlane_b32 s6, v10
; VI-SDAG-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[18:19], s5, v9
; VI-SDAG-NEXT:    v_readfirstlane_b32 s7, v11
; VI-SDAG-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[18:19], s6, v10
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    v_readfirstlane_b32 s12, v12
; VI-SDAG-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[18:19], s7, v11
; VI-SDAG-NEXT:    v_readfirstlane_b32 s13, v13
; VI-SDAG-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[18:19], s12, v12
; VI-SDAG-NEXT:    v_readfirstlane_b32 s14, v14
; VI-SDAG-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[18:19], s13, v13
; VI-SDAG-NEXT:    v_readfirstlane_b32 s15, v15
; VI-SDAG-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[18:19], s14, v14
; VI-SDAG-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[18:19], s15, v15
; VI-SDAG-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; VI-SDAG-NEXT:    s_and_saveexec_b64 s[16:17], s[16:17]
; VI-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; VI-SDAG-NEXT:    v_mov_b32_e32 v1, v0
; VI-SDAG-NEXT:    image_sample v[0:3], v[0:1], s[0:7], s[12:15] dmask:0xf
; VI-SDAG-NEXT:    ; implicit-def: $vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11
; VI-SDAG-NEXT:    ; implicit-def: $vgpr12_vgpr13_vgpr14_vgpr15
; VI-SDAG-NEXT:    s_xor_b64 exec, exec, s[16:17]
; VI-SDAG-NEXT:    s_cbranch_execnz .LBB10_1
; VI-SDAG-NEXT:  ; %bb.2:
; VI-SDAG-NEXT:    s_mov_b64 exec, s[10:11]
; VI-SDAG-NEXT:    s_and_b64 exec, exec, s[8:9]
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    ; return to shader part epilog
;
; VI-GISEL-LABEL: test_waterfall_full_idx_multi_begin:
; VI-GISEL:       ; %bb.0:
; VI-GISEL-NEXT:    s_mov_b64 s[8:9], exec
; VI-GISEL-NEXT:    s_wqm_b64 exec, exec
; VI-GISEL-NEXT:    v_mov_b32_e32 v2, v1
; VI-GISEL-NEXT:    v_ashrrev_i32_e32 v1, 31, v0
; VI-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[0:1]
; VI-GISEL-NEXT:    v_mov_b32_e32 v4, s1
; VI-GISEL-NEXT:    v_mov_b32_e32 v3, s0
; VI-GISEL-NEXT:    v_add_u32_e32 v0, vcc, v3, v0
; VI-GISEL-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; VI-GISEL-NEXT:    v_addc_u32_e32 v1, vcc, v4, v1, vcc
; VI-GISEL-NEXT:    v_lshlrev_b64 v[2:3], 4, v[2:3]
; VI-GISEL-NEXT:    v_mov_b32_e32 v5, s3
; VI-GISEL-NEXT:    v_mov_b32_e32 v4, s2
; VI-GISEL-NEXT:    v_add_u32_e32 v2, vcc, v4, v2
; VI-GISEL-NEXT:    v_addc_u32_e32 v3, vcc, v5, v3, vcc
; VI-GISEL-NEXT:    flat_load_dwordx4 v[4:7], v[0:1]
; VI-GISEL-NEXT:    v_add_u32_e32 v0, vcc, 16, v0
; VI-GISEL-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-GISEL-NEXT:    flat_load_dwordx4 v[8:11], v[0:1]
; VI-GISEL-NEXT:    flat_load_dwordx4 v[12:15], v[2:3]
; VI-GISEL-NEXT:    s_mov_b64 s[10:11], exec
; VI-GISEL-NEXT:  .LBB10_1: ; =>This Inner Loop Header: Depth=1
; VI-GISEL-NEXT:    s_waitcnt vmcnt(2)
; VI-GISEL-NEXT:    v_readfirstlane_b32 s0, v4
; VI-GISEL-NEXT:    v_readfirstlane_b32 s1, v5
; VI-GISEL-NEXT:    v_readfirstlane_b32 s2, v6
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[16:17], s0, v4
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[18:19], s1, v5
; VI-GISEL-NEXT:    v_readfirstlane_b32 s3, v7
; VI-GISEL-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[18:19], s2, v6
; VI-GISEL-NEXT:    s_waitcnt vmcnt(1)
; VI-GISEL-NEXT:    v_readfirstlane_b32 s4, v8
; VI-GISEL-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[18:19], s3, v7
; VI-GISEL-NEXT:    v_readfirstlane_b32 s5, v9
; VI-GISEL-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[18:19], s4, v8
; VI-GISEL-NEXT:    v_readfirstlane_b32 s6, v10
; VI-GISEL-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[18:19], s5, v9
; VI-GISEL-NEXT:    v_readfirstlane_b32 s7, v11
; VI-GISEL-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[18:19], s6, v10
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    v_readfirstlane_b32 s12, v12
; VI-GISEL-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[18:19], s7, v11
; VI-GISEL-NEXT:    v_readfirstlane_b32 s13, v13
; VI-GISEL-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[18:19], s12, v12
; VI-GISEL-NEXT:    v_readfirstlane_b32 s14, v14
; VI-GISEL-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[18:19], s13, v13
; VI-GISEL-NEXT:    v_readfirstlane_b32 s15, v15
; VI-GISEL-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[18:19], s14, v14
; VI-GISEL-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[18:19], s15, v15
; VI-GISEL-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; VI-GISEL-NEXT:    s_and_saveexec_b64 s[16:17], s[16:17]
; VI-GISEL-NEXT:    s_mov_b32 s18, 0
; VI-GISEL-NEXT:    s_mov_b32 s19, s18
; VI-GISEL-NEXT:    v_mov_b32_e32 v0, s18
; VI-GISEL-NEXT:    v_mov_b32_e32 v1, s19
; VI-GISEL-NEXT:    image_sample v[0:3], v[0:1], s[0:7], s[12:15] dmask:0xf
; VI-GISEL-NEXT:    ; implicit-def: $vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11
; VI-GISEL-NEXT:    ; implicit-def: $vgpr12_vgpr13_vgpr14_vgpr15
; VI-GISEL-NEXT:    s_xor_b64 exec, exec, s[16:17]
; VI-GISEL-NEXT:    s_cbranch_execnz .LBB10_1
; VI-GISEL-NEXT:  ; %bb.2:
; VI-GISEL-NEXT:    s_mov_b64 exec, s[10:11]
; VI-GISEL-NEXT:    s_and_b64 exec, exec, s[8:9]
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    ; return to shader part epilog
;
; GFX9-SDAG-LABEL: test_waterfall_full_idx_multi_begin:
; GFX9-SDAG:       ; %bb.0:
; GFX9-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX9-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v2, v0
; GFX9-SDAG-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX9-SDAG-NEXT:    v_lshlrev_b64 v[2:3], 5, v[2:3]
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v0, s1
; GFX9-SDAG-NEXT:    v_add_co_u32_e32 v16, vcc, s0, v2
; GFX9-SDAG-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX9-SDAG-NEXT:    v_addc_co_u32_e32 v17, vcc, v0, v3, vcc
; GFX9-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 4, v[1:2]
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v2, s3
; GFX9-SDAG-NEXT:    v_add_co_u32_e32 v0, vcc, s2, v0
; GFX9-SDAG-NEXT:    v_addc_co_u32_e32 v1, vcc, v2, v1, vcc
; GFX9-SDAG-NEXT:    global_load_dwordx4 v[8:11], v[16:17], off offset:16
; GFX9-SDAG-NEXT:    global_load_dwordx4 v[4:7], v[16:17], off
; GFX9-SDAG-NEXT:    global_load_dwordx4 v[12:15], v[0:1], off
; GFX9-SDAG-NEXT:    s_mov_b64 s[10:11], exec
; GFX9-SDAG-NEXT:  .LBB10_1: ; =>This Inner Loop Header: Depth=1
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(1)
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s0, v4
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s1, v5
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s2, v6
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[16:17], s0, v4
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[18:19], s1, v5
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s3, v7
; GFX9-SDAG-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[18:19], s2, v6
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s4, v8
; GFX9-SDAG-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[18:19], s3, v7
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s5, v9
; GFX9-SDAG-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[18:19], s4, v8
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s6, v10
; GFX9-SDAG-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[18:19], s5, v9
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s7, v11
; GFX9-SDAG-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[18:19], s6, v10
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s12, v12
; GFX9-SDAG-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[18:19], s7, v11
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s13, v13
; GFX9-SDAG-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[18:19], s12, v12
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s14, v14
; GFX9-SDAG-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[18:19], s13, v13
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s15, v15
; GFX9-SDAG-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[18:19], s14, v14
; GFX9-SDAG-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[18:19], s15, v15
; GFX9-SDAG-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; GFX9-SDAG-NEXT:    s_and_saveexec_b64 s[16:17], s[16:17]
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v1, v0
; GFX9-SDAG-NEXT:    image_sample v[0:3], v[0:1], s[0:7], s[12:15] dmask:0xf
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr12_vgpr13_vgpr14_vgpr15
; GFX9-SDAG-NEXT:    s_xor_b64 exec, exec, s[16:17]
; GFX9-SDAG-NEXT:    s_cbranch_execnz .LBB10_1
; GFX9-SDAG-NEXT:  ; %bb.2:
; GFX9-SDAG-NEXT:    s_mov_b64 exec, s[10:11]
; GFX9-SDAG-NEXT:    s_and_b64 exec, exec, s[8:9]
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    ; return to shader part epilog
;
; GFX9-GISEL-LABEL: test_waterfall_full_idx_multi_begin:
; GFX9-GISEL:       ; %bb.0:
; GFX9-GISEL-NEXT:    s_mov_b64 s[8:9], exec
; GFX9-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v2, v1
; GFX9-GISEL-NEXT:    v_ashrrev_i32_e32 v1, 31, v0
; GFX9-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[0:1]
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v4, s1
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v3, s0
; GFX9-GISEL-NEXT:    v_add_co_u32_e32 v0, vcc, v3, v0
; GFX9-GISEL-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX9-GISEL-NEXT:    v_addc_co_u32_e32 v1, vcc, v4, v1, vcc
; GFX9-GISEL-NEXT:    v_lshlrev_b64 v[2:3], 4, v[2:3]
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v5, s3
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v4, s2
; GFX9-GISEL-NEXT:    v_add_co_u32_e32 v2, vcc, v4, v2
; GFX9-GISEL-NEXT:    v_addc_co_u32_e32 v3, vcc, v5, v3, vcc
; GFX9-GISEL-NEXT:    global_load_dwordx4 v[4:7], v[0:1], off
; GFX9-GISEL-NEXT:    global_load_dwordx4 v[8:11], v[0:1], off offset:16
; GFX9-GISEL-NEXT:    global_load_dwordx4 v[12:15], v[2:3], off
; GFX9-GISEL-NEXT:    s_mov_b64 s[10:11], exec
; GFX9-GISEL-NEXT:  .LBB10_1: ; =>This Inner Loop Header: Depth=1
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(2)
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s0, v4
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s1, v5
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s2, v6
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[16:17], s0, v4
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[18:19], s1, v5
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s3, v7
; GFX9-GISEL-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[18:19], s2, v6
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(1)
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s4, v8
; GFX9-GISEL-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[18:19], s3, v7
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s5, v9
; GFX9-GISEL-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[18:19], s4, v8
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s6, v10
; GFX9-GISEL-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[18:19], s5, v9
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s7, v11
; GFX9-GISEL-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[18:19], s6, v10
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s12, v12
; GFX9-GISEL-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[18:19], s7, v11
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s13, v13
; GFX9-GISEL-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[18:19], s12, v12
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s14, v14
; GFX9-GISEL-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[18:19], s13, v13
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s15, v15
; GFX9-GISEL-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[18:19], s14, v14
; GFX9-GISEL-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[18:19], s15, v15
; GFX9-GISEL-NEXT:    s_and_b64 s[16:17], s[16:17], s[18:19]
; GFX9-GISEL-NEXT:    s_and_saveexec_b64 s[16:17], s[16:17]
; GFX9-GISEL-NEXT:    s_mov_b32 s18, 0
; GFX9-GISEL-NEXT:    s_mov_b32 s19, s18
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v0, s18
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v1, s19
; GFX9-GISEL-NEXT:    image_sample v[0:3], v[0:1], s[0:7], s[12:15] dmask:0xf
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr12_vgpr13_vgpr14_vgpr15
; GFX9-GISEL-NEXT:    s_xor_b64 exec, exec, s[16:17]
; GFX9-GISEL-NEXT:    s_cbranch_execnz .LBB10_1
; GFX9-GISEL-NEXT:  ; %bb.2:
; GFX9-GISEL-NEXT:    s_mov_b64 exec, s[10:11]
; GFX9-GISEL-NEXT:    s_and_b64 exec, exec, s[8:9]
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-32-SDAG-LABEL: test_waterfall_full_idx_multi_begin:
; GFX10-32-SDAG:       ; %bb.0:
; GFX10-32-SDAG-NEXT:    s_mov_b32 s4, exec_lo
; GFX10-32-SDAG-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v3, v0
; GFX10-32-SDAG-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX10-32-SDAG-NEXT:    v_ashrrev_i32_e32 v4, 31, v3
; GFX10-32-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 4, v[1:2]
; GFX10-32-SDAG-NEXT:    v_lshlrev_b64 v[3:4], 5, v[3:4]
; GFX10-32-SDAG-NEXT:    v_add_co_u32 v2, vcc_lo, s0, v3
; GFX10-32-SDAG-NEXT:    v_add_co_ci_u32_e32 v3, vcc_lo, s1, v4, vcc_lo
; GFX10-32-SDAG-NEXT:    v_add_co_u32 v0, vcc_lo, s2, v0
; GFX10-32-SDAG-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, s3, v1, vcc_lo
; GFX10-32-SDAG-NEXT:    s_clause 0x1
; GFX10-32-SDAG-NEXT:    global_load_dwordx4 v[8:11], v[2:3], off offset:16
; GFX10-32-SDAG-NEXT:    global_load_dwordx4 v[4:7], v[2:3], off
; GFX10-32-SDAG-NEXT:    global_load_dwordx4 v[12:15], v[0:1], off
; GFX10-32-SDAG-NEXT:    s_mov_b32 s1, exec_lo
; GFX10-32-SDAG-NEXT:    s_mov_b32 s0, exec_lo
; GFX10-32-SDAG-NEXT:  .LBB10_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(1)
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s8, v4
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s9, v5
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s10, v6
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s11, v7
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s12, v8
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s13, v9
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s14, v10
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s15, v11
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s16, v12
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s17, v13
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s18, v14
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s19, v15
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s8, v4
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s9, v5
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s10, v6
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s11, v7
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s12, v8
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s13, v9
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s14, v10
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s15, v11
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s16, v12
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s17, v13
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s18, v14
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s19, v15
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-32-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-32-SDAG-NEXT:    s_andn2_wrexec_b32 s1, s1
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr12_vgpr13_vgpr14_vgpr15
; GFX10-32-SDAG-NEXT:    s_cbranch_execnz .LBB10_1
; GFX10-32-SDAG-NEXT:  ; %bb.2:
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-SDAG-NEXT:    s_mov_b32 exec_lo, s0
; GFX10-32-SDAG-NEXT:    s_and_b32 exec_lo, exec_lo, s4
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-32-GISEL-LABEL: test_waterfall_full_idx_multi_begin:
; GFX10-32-GISEL:       ; %bb.0:
; GFX10-32-GISEL-NEXT:    s_mov_b32 s4, exec_lo
; GFX10-32-GISEL-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v2, v1
; GFX10-32-GISEL-NEXT:    v_ashrrev_i32_e32 v1, 31, v0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v5, s1
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v4, s0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v7, s3
; GFX10-32-GISEL-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX10-32-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[0:1]
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v6, s2
; GFX10-32-GISEL-NEXT:    s_mov_b32 s1, exec_lo
; GFX10-32-GISEL-NEXT:    s_mov_b32 s0, exec_lo
; GFX10-32-GISEL-NEXT:    v_lshlrev_b64 v[2:3], 4, v[2:3]
; GFX10-32-GISEL-NEXT:    v_add_co_u32 v0, vcc_lo, v4, v0
; GFX10-32-GISEL-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, v5, v1, vcc_lo
; GFX10-32-GISEL-NEXT:    v_add_co_u32 v2, vcc_lo, v6, v2
; GFX10-32-GISEL-NEXT:    v_add_co_ci_u32_e32 v3, vcc_lo, v7, v3, vcc_lo
; GFX10-32-GISEL-NEXT:    s_clause 0x1
; GFX10-32-GISEL-NEXT:    global_load_dwordx4 v[4:7], v[0:1], off
; GFX10-32-GISEL-NEXT:    global_load_dwordx4 v[8:11], v[0:1], off offset:16
; GFX10-32-GISEL-NEXT:    global_load_dwordx4 v[12:15], v[2:3], off
; GFX10-32-GISEL-NEXT:  .LBB10_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(2)
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s8, v4
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s9, v5
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s10, v6
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s11, v7
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(1)
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s12, v8
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s13, v9
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s14, v10
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s15, v11
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s16, v12
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s17, v13
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s18, v14
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s19, v15
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s8, v4
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s9, v5
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s10, v6
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s11, v7
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s12, v8
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s13, v9
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s14, v10
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s15, v11
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s16, v12
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s17, v13
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s18, v14
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s19, v15
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-32-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-32-GISEL-NEXT:    s_andn2_wrexec_b32 s1, s1
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr12_vgpr13_vgpr14_vgpr15
; GFX10-32-GISEL-NEXT:    s_cbranch_execnz .LBB10_1
; GFX10-32-GISEL-NEXT:  ; %bb.2:
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-GISEL-NEXT:    s_mov_b32 exec_lo, s0
; GFX10-32-GISEL-NEXT:    s_and_b32 exec_lo, exec_lo, s4
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-64-SDAG-LABEL: test_waterfall_full_idx_multi_begin:
; GFX10-64-SDAG:       ; %bb.0:
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX10-64-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v3, v0
; GFX10-64-SDAG-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX10-64-SDAG-NEXT:    v_ashrrev_i32_e32 v4, 31, v3
; GFX10-64-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 4, v[1:2]
; GFX10-64-SDAG-NEXT:    v_lshlrev_b64 v[3:4], 5, v[3:4]
; GFX10-64-SDAG-NEXT:    v_add_co_u32 v2, vcc, s0, v3
; GFX10-64-SDAG-NEXT:    v_add_co_ci_u32_e32 v3, vcc, s1, v4, vcc
; GFX10-64-SDAG-NEXT:    v_add_co_u32 v0, vcc, s2, v0
; GFX10-64-SDAG-NEXT:    v_add_co_ci_u32_e32 v1, vcc, s3, v1, vcc
; GFX10-64-SDAG-NEXT:    s_clause 0x1
; GFX10-64-SDAG-NEXT:    global_load_dwordx4 v[8:11], v[2:3], off offset:16
; GFX10-64-SDAG-NEXT:    global_load_dwordx4 v[4:7], v[2:3], off
; GFX10-64-SDAG-NEXT:    global_load_dwordx4 v[12:15], v[0:1], off
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX10-64-SDAG-NEXT:  .LBB10_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(1)
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s8, v4
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s9, v5
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s10, v6
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s11, v7
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s12, v8
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s13, v9
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s14, v10
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s15, v11
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s16, v12
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s17, v13
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s18, v14
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s19, v15
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s8, v4
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s9, v5
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s10, v6
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s11, v7
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s12, v8
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s13, v9
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s14, v10
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s15, v11
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s16, v12
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s17, v13
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s18, v14
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s19, v15
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-64-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-64-SDAG-NEXT:    s_andn2_wrexec_b64 s[2:3], s[2:3]
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr12_vgpr13_vgpr14_vgpr15
; GFX10-64-SDAG-NEXT:    s_cbranch_execnz .LBB10_1
; GFX10-64-SDAG-NEXT:  ; %bb.2:
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX10-64-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-64-GISEL-LABEL: test_waterfall_full_idx_multi_begin:
; GFX10-64-GISEL:       ; %bb.0:
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX10-64-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v2, v1
; GFX10-64-GISEL-NEXT:    v_ashrrev_i32_e32 v1, 31, v0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v5, s1
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v4, s0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v7, s3
; GFX10-64-GISEL-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX10-64-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[0:1]
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v6, s2
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX10-64-GISEL-NEXT:    v_lshlrev_b64 v[2:3], 4, v[2:3]
; GFX10-64-GISEL-NEXT:    v_add_co_u32 v0, vcc, v4, v0
; GFX10-64-GISEL-NEXT:    v_add_co_ci_u32_e32 v1, vcc, v5, v1, vcc
; GFX10-64-GISEL-NEXT:    v_add_co_u32 v2, vcc, v6, v2
; GFX10-64-GISEL-NEXT:    v_add_co_ci_u32_e32 v3, vcc, v7, v3, vcc
; GFX10-64-GISEL-NEXT:    s_clause 0x1
; GFX10-64-GISEL-NEXT:    global_load_dwordx4 v[4:7], v[0:1], off
; GFX10-64-GISEL-NEXT:    global_load_dwordx4 v[8:11], v[0:1], off offset:16
; GFX10-64-GISEL-NEXT:    global_load_dwordx4 v[12:15], v[2:3], off
; GFX10-64-GISEL-NEXT:  .LBB10_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(2)
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s8, v4
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s9, v5
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s10, v6
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s11, v7
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(1)
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s12, v8
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s13, v9
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s14, v10
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s15, v11
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s16, v12
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s17, v13
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s18, v14
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s19, v15
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s8, v4
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s9, v5
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s10, v6
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s11, v7
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s12, v8
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s13, v9
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s14, v10
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s15, v11
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s16, v12
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s17, v13
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s18, v14
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s19, v15
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-64-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-64-GISEL-NEXT:    s_andn2_wrexec_b64 s[2:3], s[2:3]
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr12_vgpr13_vgpr14_vgpr15
; GFX10-64-GISEL-NEXT:    s_cbranch_execnz .LBB10_1
; GFX10-64-GISEL-NEXT:  ; %bb.2:
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX10-64-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:    ; return to shader part epilog
;
; GFX1150-SDAG-LABEL: test_waterfall_full_idx_multi_begin:
; GFX1150-SDAG:       ; %bb.0:
; GFX1150-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX1150-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v3, v0
; GFX1150-SDAG-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX1150-SDAG-NEXT:    v_ashrrev_i32_e32 v4, 31, v3
; GFX1150-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 4, v[1:2]
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX1150-SDAG-NEXT:    v_lshlrev_b64 v[3:4], 5, v[3:4]
; GFX1150-SDAG-NEXT:    v_add_co_u32 v2, vcc, s0, v3
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX1150-SDAG-NEXT:    v_add_co_ci_u32_e64 v3, null, s1, v4, vcc
; GFX1150-SDAG-NEXT:    v_add_co_u32 v0, vcc, s2, v0
; GFX1150-SDAG-NEXT:    s_waitcnt_depctr depctr_va_vcc(0)
; GFX1150-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX1150-SDAG-NEXT:    v_add_co_ci_u32_e64 v1, null, s3, v1, vcc
; GFX1150-SDAG-NEXT:    s_clause 0x1
; GFX1150-SDAG-NEXT:    global_load_b128 v[8:11], v[2:3], off offset:16
; GFX1150-SDAG-NEXT:    global_load_b128 v[4:7], v[2:3], off
; GFX1150-SDAG-NEXT:    global_load_b128 v[12:15], v[0:1], off
; GFX1150-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX1150-SDAG-NEXT:  .LBB10_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(1)
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s8, v4
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s9, v5
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s10, v6
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s11, v7
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s12, v8
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s13, v9
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s14, v10
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s15, v11
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s16, v12
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s17, v13
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s18, v14
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s19, v15
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s8, v4
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s9, v5
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s10, v6
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s11, v7
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s12, v8
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s13, v9
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s14, v10
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s15, v11
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s16, v12
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s17, v13
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s18, v14
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s19, v15
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX1150-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX1150-SDAG-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr12_vgpr13_vgpr14_vgpr15
; GFX1150-SDAG-NEXT:    s_cbranch_execnz .LBB10_1
; GFX1150-SDAG-NEXT:  ; %bb.2:
; GFX1150-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:    ; return to shader part epilog
;
; GFX1150-GISEL-LABEL: test_waterfall_full_idx_multi_begin:
; GFX1150-GISEL:       ; %bb.0:
; GFX1150-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX1150-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v2, v1
; GFX1150-GISEL-NEXT:    v_ashrrev_i32_e32 v1, 31, v0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v5, s1
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v4, s0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v7, s3
; GFX1150-GISEL-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX1150-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[0:1]
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v6, s2
; GFX1150-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX1150-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX1150-GISEL-NEXT:    v_lshlrev_b64 v[2:3], 4, v[2:3]
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX1150-GISEL-NEXT:    v_add_co_u32 v0, vcc, v4, v0
; GFX1150-GISEL-NEXT:    v_add_co_ci_u32_e64 v1, null, v5, v1, vcc
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX1150-GISEL-NEXT:    v_add_co_u32 v2, vcc, v6, v2
; GFX1150-GISEL-NEXT:    s_waitcnt_depctr depctr_va_vcc(0)
; GFX1150-GISEL-NEXT:    v_add_co_ci_u32_e64 v3, null, v7, v3, vcc
; GFX1150-GISEL-NEXT:    s_clause 0x1
; GFX1150-GISEL-NEXT:    global_load_b128 v[4:7], v[0:1], off
; GFX1150-GISEL-NEXT:    global_load_b128 v[8:11], v[0:1], off offset:16
; GFX1150-GISEL-NEXT:    global_load_b128 v[12:15], v[2:3], off
; GFX1150-GISEL-NEXT:  .LBB10_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(2)
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s8, v4
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s9, v5
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s10, v6
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s11, v7
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(1)
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s12, v8
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s13, v9
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s14, v10
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s15, v11
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s16, v12
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s17, v13
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s18, v14
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s19, v15
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s8, v4
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s9, v5
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s10, v6
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s11, v7
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s12, v8
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s13, v9
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s14, v10
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s15, v11
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s16, v12
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s17, v13
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s18, v14
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s19, v15
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX1150-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX1150-GISEL-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr12_vgpr13_vgpr14_vgpr15
; GFX1150-GISEL-NEXT:    s_cbranch_execnz .LBB10_1
; GFX1150-GISEL-NEXT:  ; %bb.2:
; GFX1150-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    ; return to shader part epilog
;
; GFX12-SDAG-LABEL: test_waterfall_full_idx_multi_begin:
; GFX12-SDAG:       ; %bb.0:
; GFX12-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX12-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v3, v0
; GFX12-SDAG-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX12-SDAG-NEXT:    v_ashrrev_i32_e32 v4, 31, v3
; GFX12-SDAG-NEXT:    v_lshlrev_b64_e32 v[0:1], 4, v[1:2]
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX12-SDAG-NEXT:    v_lshlrev_b64_e32 v[3:4], 5, v[3:4]
; GFX12-SDAG-NEXT:    v_add_co_u32 v2, vcc, s0, v3
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX12-SDAG-NEXT:    v_add_co_ci_u32_e64 v3, null, s1, v4, vcc
; GFX12-SDAG-NEXT:    v_add_co_u32 v0, vcc, s2, v0
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_vcc(0)
; GFX12-SDAG-NEXT:    v_add_co_ci_u32_e64 v1, null, s3, v1, vcc
; GFX12-SDAG-NEXT:    s_clause 0x1
; GFX12-SDAG-NEXT:    global_load_b128 v[8:11], v[2:3], off offset:16
; GFX12-SDAG-NEXT:    global_load_b128 v[4:7], v[2:3], off
; GFX12-SDAG-NEXT:    global_load_b128 v[12:15], v[0:1], off
; GFX12-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX12-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX12-SDAG-NEXT:  .LBB10_1: ; =>This Inner Loop Header: Depth=1
; GFX12-SDAG-NEXT:    s_wait_loadcnt 0x1
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s8, v4
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s9, v5
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s10, v6
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s11, v7
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s12, v8
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s13, v9
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s14, v10
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s15, v11
; GFX12-SDAG-NEXT:    s_wait_loadcnt 0x0
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s16, v12
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s17, v13
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s18, v14
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s19, v15
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s8, v4
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s9, v5
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s10, v6
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s11, v7
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s12, v8
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s13, v9
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s14, v10
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s15, v11
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s16, v12
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s17, v13
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s18, v14
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s19, v15
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX12-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX12-SDAG-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr12_vgpr13_vgpr14_vgpr15
; GFX12-SDAG-NEXT:    s_cbranch_execnz .LBB10_1
; GFX12-SDAG-NEXT:  ; %bb.2:
; GFX12-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX12-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-SDAG-NEXT:    ; return to shader part epilog
;
; GFX12-GISEL-LABEL: test_waterfall_full_idx_multi_begin:
; GFX12-GISEL:       ; %bb.0:
; GFX12-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX12-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v2, v1
; GFX12-GISEL-NEXT:    v_ashrrev_i32_e32 v1, 31, v0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v5, s1
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v4, s0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v7, s3
; GFX12-GISEL-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX12-GISEL-NEXT:    v_lshlrev_b64_e32 v[0:1], 5, v[0:1]
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v6, s2
; GFX12-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX12-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX12-GISEL-NEXT:    v_lshlrev_b64_e32 v[2:3], 4, v[2:3]
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX12-GISEL-NEXT:    v_add_co_u32 v0, vcc, v4, v0
; GFX12-GISEL-NEXT:    v_add_co_ci_u32_e64 v1, null, v5, v1, vcc
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(SKIP_1) | instid1(VALU_DEP_4)
; GFX12-GISEL-NEXT:    v_add_co_u32 v2, vcc, v6, v2
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_vcc(0)
; GFX12-GISEL-NEXT:    v_add_co_ci_u32_e64 v3, null, v7, v3, vcc
; GFX12-GISEL-NEXT:    s_clause 0x1
; GFX12-GISEL-NEXT:    global_load_b128 v[4:7], v[0:1], off
; GFX12-GISEL-NEXT:    global_load_b128 v[8:11], v[0:1], off offset:16
; GFX12-GISEL-NEXT:    global_load_b128 v[12:15], v[2:3], off
; GFX12-GISEL-NEXT:  .LBB10_1: ; =>This Inner Loop Header: Depth=1
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x2
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s8, v4
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s9, v5
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s10, v6
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s11, v7
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x1
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s12, v8
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s13, v9
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s14, v10
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s15, v11
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x0
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s16, v12
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s17, v13
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s18, v14
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s19, v15
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s8, v4
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s9, v5
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s10, v6
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s11, v7
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s12, v8
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s13, v9
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s14, v10
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s15, v11
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s16, v12
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s17, v13
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s18, v14
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s19, v15
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX12-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX12-GISEL-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr12_vgpr13_vgpr14_vgpr15
; GFX12-GISEL-NEXT:    s_cbranch_execnz .LBB10_1
; GFX12-GISEL-NEXT:  ; %bb.2:
; GFX12-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX12-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-GISEL-NEXT:    ; return to shader part epilog
                                                                  i32 %s_idx, i32 %s_idx2) #1 {
  %rptr = getelementptr <8 x i32>, <8 x i32> addrspace(4)* %in, i32 %s_idx
  %sptr = getelementptr <4 x i32>, <4 x i32> addrspace(4)* %s_in, i32 %s_idx2
  %rsrc = load <8 x i32>, <8 x i32> addrspace(4)* %rptr, align 16
  %srsrc = load <4 x i32>, <4 x i32> addrspace(4)* %sptr, align 16
  %tok = call token @llvm.amdgcn.waterfall.begin.v8i32(token poison, <8 x i32> %rsrc)
  %tok1 = call token @llvm.amdgcn.waterfall.begin.v4i32(token %tok, <4 x i32> %srsrc)
  %s_rsrc = call <8 x i32> @llvm.amdgcn.waterfall.readfirstlane.v8i32.v8i32(token %tok1, <8 x i32> %rsrc)
  %s_srsrc = call <4 x i32> @llvm.amdgcn.waterfall.readfirstlane.v4i32.v4i32(token %tok1, <4 x i32> %srsrc)
  %r = call <4 x float> @llvm.amdgcn.image.sample.2d.v4f32.f32(i32 15, float 0.000000e+00, float 0.000000e+00, <8 x i32> %s_rsrc, <4 x i32> %s_srsrc, i1 false, i32 0, i32 0)
  %r1 = call <4 x float> @llvm.amdgcn.waterfall.end.v4f32(token %tok1, <4 x float> %r)

  ret <4 x float> %r1
}

define amdgpu_ps <4 x float> @test_waterfall_multi_begin_uniform_idx_1(<8 x i32> addrspace(4)* inreg %in,
; VI-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_1:
; VI-SDAG:       ; %bb.0:
; VI-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; VI-SDAG-NEXT:    s_wqm_b64 exec, exec
; VI-SDAG-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; VI-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; VI-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 4, v[1:2]
; VI-SDAG-NEXT:    v_mov_b32_e32 v2, s3
; VI-SDAG-NEXT:    v_add_u32_e32 v0, vcc, s2, v0
; VI-SDAG-NEXT:    v_addc_u32_e32 v1, vcc, v2, v1, vcc
; VI-SDAG-NEXT:    flat_load_dwordx4 v[5:8], v[0:1]
; VI-SDAG-NEXT:    s_mov_b32 s4, s5
; VI-SDAG-NEXT:    s_ashr_i32 s5, s5, 31
; VI-SDAG-NEXT:    s_lshl_b64 s[2:3], s[4:5], 5
; VI-SDAG-NEXT:    s_add_u32 s0, s0, s2
; VI-SDAG-NEXT:    s_addc_u32 s1, s1, s3
; VI-SDAG-NEXT:    s_load_dwordx8 s[0:7], s[0:1], 0x0
; VI-SDAG-NEXT:    s_mov_b64 s[10:11], exec
; VI-SDAG-NEXT:  .LBB11_1: ; =>This Inner Loop Header: Depth=1
; VI-SDAG-NEXT:    v_readfirstlane_b32 s12, v4
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[12:13], s12, v4
; VI-SDAG-NEXT:    s_and_saveexec_b64 s[16:17], s[12:13]
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    v_readfirstlane_b32 s12, v5
; VI-SDAG-NEXT:    v_readfirstlane_b32 s13, v6
; VI-SDAG-NEXT:    v_readfirstlane_b32 s14, v7
; VI-SDAG-NEXT:    v_readfirstlane_b32 s15, v8
; VI-SDAG-NEXT:    v_mov_b32_e32 v1, v0
; VI-SDAG-NEXT:    ; implicit-def: $vgpr4
; VI-SDAG-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8
; VI-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; VI-SDAG-NEXT:    s_nop 2
; VI-SDAG-NEXT:    image_sample v[0:3], v[0:1], s[0:7], s[12:15] dmask:0xf
; VI-SDAG-NEXT:    s_xor_b64 exec, exec, s[16:17]
; VI-SDAG-NEXT:    s_cbranch_execnz .LBB11_1
; VI-SDAG-NEXT:  ; %bb.2:
; VI-SDAG-NEXT:    s_mov_b64 exec, s[10:11]
; VI-SDAG-NEXT:    s_and_b64 exec, exec, s[8:9]
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    ; return to shader part epilog
;
; VI-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_1:
; VI-GISEL:       ; %bb.0:
; VI-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; VI-GISEL-NEXT:    s_wqm_b64 exec, exec
; VI-GISEL-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; VI-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; VI-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 4, v[1:2]
; VI-GISEL-NEXT:    v_mov_b32_e32 v2, s2
; VI-GISEL-NEXT:    v_mov_b32_e32 v3, s3
; VI-GISEL-NEXT:    v_add_u32_e32 v0, vcc, v2, v0
; VI-GISEL-NEXT:    v_addc_u32_e32 v1, vcc, v3, v1, vcc
; VI-GISEL-NEXT:    flat_load_dwordx4 v[5:8], v[0:1]
; VI-GISEL-NEXT:    s_mov_b32 s8, s5
; VI-GISEL-NEXT:    s_ashr_i32 s9, s5, 31
; VI-GISEL-NEXT:    s_lshl_b64 s[2:3], s[8:9], 5
; VI-GISEL-NEXT:    s_add_u32 s0, s0, s2
; VI-GISEL-NEXT:    s_addc_u32 s1, s1, s3
; VI-GISEL-NEXT:    s_load_dwordx8 s[8:15], s[0:1], 0x0
; VI-GISEL-NEXT:    v_mov_b32_e32 v9, s4
; VI-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; VI-GISEL-NEXT:  .LBB11_1: ; =>This Inner Loop Header: Depth=1
; VI-GISEL-NEXT:    v_readfirstlane_b32 s2, v9
; VI-GISEL-NEXT:    v_readfirstlane_b32 s4, v4
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v9
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[4:5], s4, v4
; VI-GISEL-NEXT:    s_and_b64 s[2:3], s[2:3], s[4:5]
; VI-GISEL-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; VI-GISEL-NEXT:    s_mov_b32 s4, 0
; VI-GISEL-NEXT:    s_mov_b32 s5, s4
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    v_mov_b32_e32 v0, s4
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    v_readfirstlane_b32 s16, v5
; VI-GISEL-NEXT:    v_readfirstlane_b32 s17, v6
; VI-GISEL-NEXT:    v_readfirstlane_b32 s18, v7
; VI-GISEL-NEXT:    v_readfirstlane_b32 s19, v8
; VI-GISEL-NEXT:    v_mov_b32_e32 v1, s5
; VI-GISEL-NEXT:    ; implicit-def: $vgpr9
; VI-GISEL-NEXT:    ; implicit-def: $vgpr4
; VI-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8
; VI-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; VI-GISEL-NEXT:    s_nop 2
; VI-GISEL-NEXT:    image_sample v[0:3], v[0:1], s[8:15], s[16:19] dmask:0xf
; VI-GISEL-NEXT:    s_xor_b64 exec, exec, s[2:3]
; VI-GISEL-NEXT:    s_cbranch_execnz .LBB11_1
; VI-GISEL-NEXT:  ; %bb.2:
; VI-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; VI-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    ; return to shader part epilog
;
; GFX9-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_1:
; GFX9-SDAG:       ; %bb.0:
; GFX9-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX9-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX9-SDAG-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX9-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 4, v[1:2]
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v2, s3
; GFX9-SDAG-NEXT:    v_add_co_u32_e32 v0, vcc, s2, v0
; GFX9-SDAG-NEXT:    v_addc_co_u32_e32 v1, vcc, v2, v1, vcc
; GFX9-SDAG-NEXT:    global_load_dwordx4 v[5:8], v[0:1], off
; GFX9-SDAG-NEXT:    s_mov_b32 s4, s5
; GFX9-SDAG-NEXT:    s_ashr_i32 s5, s5, 31
; GFX9-SDAG-NEXT:    s_lshl_b64 s[2:3], s[4:5], 5
; GFX9-SDAG-NEXT:    s_add_u32 s10, s0, s2
; GFX9-SDAG-NEXT:    s_addc_u32 s11, s1, s3
; GFX9-SDAG-NEXT:    s_load_dwordx8 s[0:7], s[10:11], 0x0
; GFX9-SDAG-NEXT:    s_mov_b64 s[10:11], exec
; GFX9-SDAG-NEXT:  .LBB11_1: ; =>This Inner Loop Header: Depth=1
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s12, v4
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[12:13], s12, v4
; GFX9-SDAG-NEXT:    s_and_saveexec_b64 s[16:17], s[12:13]
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s12, v5
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s13, v6
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s14, v7
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s15, v8
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v1, v0
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8
; GFX9-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; GFX9-SDAG-NEXT:    s_nop 2
; GFX9-SDAG-NEXT:    image_sample v[0:3], v[0:1], s[0:7], s[12:15] dmask:0xf
; GFX9-SDAG-NEXT:    s_xor_b64 exec, exec, s[16:17]
; GFX9-SDAG-NEXT:    s_cbranch_execnz .LBB11_1
; GFX9-SDAG-NEXT:  ; %bb.2:
; GFX9-SDAG-NEXT:    s_mov_b64 exec, s[10:11]
; GFX9-SDAG-NEXT:    s_and_b64 exec, exec, s[8:9]
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    ; return to shader part epilog
;
; GFX9-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_1:
; GFX9-GISEL:       ; %bb.0:
; GFX9-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX9-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX9-GISEL-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX9-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 4, v[1:2]
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v2, s2
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v3, s3
; GFX9-GISEL-NEXT:    v_add_co_u32_e32 v0, vcc, v2, v0
; GFX9-GISEL-NEXT:    v_addc_co_u32_e32 v1, vcc, v3, v1, vcc
; GFX9-GISEL-NEXT:    global_load_dwordx4 v[5:8], v[0:1], off
; GFX9-GISEL-NEXT:    s_mov_b32 s8, s5
; GFX9-GISEL-NEXT:    s_ashr_i32 s9, s5, 31
; GFX9-GISEL-NEXT:    s_lshl_b64 s[2:3], s[8:9], 5
; GFX9-GISEL-NEXT:    s_add_u32 s0, s0, s2
; GFX9-GISEL-NEXT:    s_addc_u32 s1, s1, s3
; GFX9-GISEL-NEXT:    s_load_dwordx8 s[8:15], s[0:1], 0x0
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v9, s4
; GFX9-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX9-GISEL-NEXT:  .LBB11_1: ; =>This Inner Loop Header: Depth=1
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s2, v9
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s4, v4
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v9
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[4:5], s4, v4
; GFX9-GISEL-NEXT:    s_and_b64 s[2:3], s[2:3], s[4:5]
; GFX9-GISEL-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; GFX9-GISEL-NEXT:    s_mov_b32 s4, 0
; GFX9-GISEL-NEXT:    s_mov_b32 s5, s4
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v0, s4
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s16, v5
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s17, v6
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s18, v7
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s19, v8
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v1, s5
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr9
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8
; GFX9-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; GFX9-GISEL-NEXT:    s_nop 2
; GFX9-GISEL-NEXT:    image_sample v[0:3], v[0:1], s[8:15], s[16:19] dmask:0xf
; GFX9-GISEL-NEXT:    s_xor_b64 exec, exec, s[2:3]
; GFX9-GISEL-NEXT:    s_cbranch_execnz .LBB11_1
; GFX9-GISEL-NEXT:  ; %bb.2:
; GFX9-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX9-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-32-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_1:
; GFX10-32-SDAG:       ; %bb.0:
; GFX10-32-SDAG-NEXT:    s_mov_b32 s8, exec_lo
; GFX10-32-SDAG-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-SDAG-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-32-SDAG-NEXT:    s_mov_b32 s4, s5
; GFX10-32-SDAG-NEXT:    s_ashr_i32 s5, s5, 31
; GFX10-32-SDAG-NEXT:    s_mov_b32 s9, exec_lo
; GFX10-32-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 4, v[1:2]
; GFX10-32-SDAG-NEXT:    v_add_co_u32 v0, vcc_lo, s2, v0
; GFX10-32-SDAG-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, s3, v1, vcc_lo
; GFX10-32-SDAG-NEXT:    s_lshl_b64 s[2:3], s[4:5], 5
; GFX10-32-SDAG-NEXT:    s_add_u32 s10, s0, s2
; GFX10-32-SDAG-NEXT:    global_load_dwordx4 v[5:8], v[0:1], off
; GFX10-32-SDAG-NEXT:    s_addc_u32 s11, s1, s3
; GFX10-32-SDAG-NEXT:    s_load_dwordx8 s[0:7], s[10:11], 0x0
; GFX10-32-SDAG-NEXT:    s_mov_b32 s10, exec_lo
; GFX10-32-SDAG-NEXT:  .LBB11_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s11, v4
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s11, v4
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s12, v5
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s13, v6
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s14, v7
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s15, v8
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-32-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-32-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[0:7], s[12:15] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-32-SDAG-NEXT:    s_andn2_wrexec_b32 s10, s10
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8
; GFX10-32-SDAG-NEXT:    s_cbranch_execnz .LBB11_1
; GFX10-32-SDAG-NEXT:  ; %bb.2:
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-SDAG-NEXT:    s_mov_b32 exec_lo, s9
; GFX10-32-SDAG-NEXT:    s_and_b32 exec_lo, exec_lo, s8
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-32-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_1:
; GFX10-32-GISEL:       ; %bb.0:
; GFX10-32-GISEL-NEXT:    s_mov_b32 s6, exec_lo
; GFX10-32-GISEL-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-GISEL-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-32-GISEL-NEXT:    s_mov_b32 s8, s5
; GFX10-32-GISEL-NEXT:    s_ashr_i32 s9, s5, 31
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v9, s4
; GFX10-32-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 4, v[1:2]
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v2, s2
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v3, s3
; GFX10-32-GISEL-NEXT:    s_lshl_b64 s[2:3], s[8:9], 5
; GFX10-32-GISEL-NEXT:    s_add_u32 s0, s0, s2
; GFX10-32-GISEL-NEXT:    v_add_co_u32 v0, vcc_lo, v2, v0
; GFX10-32-GISEL-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, v3, v1, vcc_lo
; GFX10-32-GISEL-NEXT:    s_addc_u32 s1, s1, s3
; GFX10-32-GISEL-NEXT:    s_load_dwordx8 s[8:15], s[0:1], 0x0
; GFX10-32-GISEL-NEXT:    global_load_dwordx4 v[5:8], v[0:1], off
; GFX10-32-GISEL-NEXT:    s_mov_b32 s1, exec_lo
; GFX10-32-GISEL-NEXT:    s_mov_b32 s0, exec_lo
; GFX10-32-GISEL-NEXT:  .LBB11_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s2, v9
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s3, v4
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s2, v9
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s3, v4
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s16, v5
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s17, v6
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s18, v7
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s19, v8
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-32-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-32-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-32-GISEL-NEXT:    s_andn2_wrexec_b32 s1, s1
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr9
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8
; GFX10-32-GISEL-NEXT:    s_cbranch_execnz .LBB11_1
; GFX10-32-GISEL-NEXT:  ; %bb.2:
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-GISEL-NEXT:    s_mov_b32 exec_lo, s0
; GFX10-32-GISEL-NEXT:    s_and_b32 exec_lo, exec_lo, s6
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-64-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_1:
; GFX10-64-SDAG:       ; %bb.0:
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX10-64-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-SDAG-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-64-SDAG-NEXT:    s_mov_b32 s4, s5
; GFX10-64-SDAG-NEXT:    s_ashr_i32 s5, s5, 31
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[12:13], exec
; GFX10-64-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 4, v[1:2]
; GFX10-64-SDAG-NEXT:    v_add_co_u32 v0, vcc, s2, v0
; GFX10-64-SDAG-NEXT:    v_add_co_ci_u32_e32 v1, vcc, s3, v1, vcc
; GFX10-64-SDAG-NEXT:    s_lshl_b64 s[2:3], s[4:5], 5
; GFX10-64-SDAG-NEXT:    s_add_u32 s10, s0, s2
; GFX10-64-SDAG-NEXT:    global_load_dwordx4 v[5:8], v[0:1], off
; GFX10-64-SDAG-NEXT:    s_addc_u32 s11, s1, s3
; GFX10-64-SDAG-NEXT:    s_load_dwordx8 s[0:7], s[10:11], 0x0
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[10:11], exec
; GFX10-64-SDAG-NEXT:  .LBB11_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s14, v4
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s14, v4
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s16, v5
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s17, v6
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s18, v7
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s19, v8
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-64-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-64-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[0:7], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-64-SDAG-NEXT:    s_andn2_wrexec_b64 s[12:13], s[12:13]
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8
; GFX10-64-SDAG-NEXT:    s_cbranch_execnz .LBB11_1
; GFX10-64-SDAG-NEXT:  ; %bb.2:
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-SDAG-NEXT:    s_mov_b64 exec, s[10:11]
; GFX10-64-SDAG-NEXT:    s_and_b64 exec, exec, s[8:9]
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-64-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_1:
; GFX10-64-GISEL:       ; %bb.0:
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX10-64-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-GISEL-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-64-GISEL-NEXT:    s_mov_b32 s8, s5
; GFX10-64-GISEL-NEXT:    s_ashr_i32 s9, s5, 31
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v9, s4
; GFX10-64-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 4, v[1:2]
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v2, s2
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v3, s3
; GFX10-64-GISEL-NEXT:    s_lshl_b64 s[2:3], s[8:9], 5
; GFX10-64-GISEL-NEXT:    s_add_u32 s0, s0, s2
; GFX10-64-GISEL-NEXT:    v_add_co_u32 v0, vcc, v2, v0
; GFX10-64-GISEL-NEXT:    v_add_co_ci_u32_e32 v1, vcc, v3, v1, vcc
; GFX10-64-GISEL-NEXT:    s_addc_u32 s1, s1, s3
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX10-64-GISEL-NEXT:    s_load_dwordx8 s[8:15], s[0:1], 0x0
; GFX10-64-GISEL-NEXT:    global_load_dwordx4 v[5:8], v[0:1], off
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX10-64-GISEL-NEXT:  .LBB11_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s4, v9
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s5, v4
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s4, v9
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s5, v4
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s16, v5
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s17, v6
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s18, v7
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s19, v8
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-64-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-64-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-64-GISEL-NEXT:    s_andn2_wrexec_b64 s[2:3], s[2:3]
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr9
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8
; GFX10-64-GISEL-NEXT:    s_cbranch_execnz .LBB11_1
; GFX10-64-GISEL-NEXT:  ; %bb.2:
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX10-64-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:    ; return to shader part epilog
;
; GFX1150-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_1:
; GFX1150-SDAG:       ; %bb.0:
; GFX1150-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX1150-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX1150-SDAG-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX1150-SDAG-NEXT:    s_mov_b32 s4, s5
; GFX1150-SDAG-NEXT:    s_ashr_i32 s5, s5, 31
; GFX1150-SDAG-NEXT:    s_mov_b64 s[12:13], exec
; GFX1150-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 4, v[1:2]
; GFX1150-SDAG-NEXT:    s_mov_b64 s[10:11], exec
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX1150-SDAG-NEXT:    v_add_co_u32 v0, vcc, s2, v0
; GFX1150-SDAG-NEXT:    v_add_co_ci_u32_e64 v1, null, s3, v1, vcc
; GFX1150-SDAG-NEXT:    s_lshl_b64 s[2:3], s[4:5], 5
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-SDAG-NEXT:    s_add_u32 s0, s0, s2
; GFX1150-SDAG-NEXT:    global_load_b128 v[5:8], v[0:1], off
; GFX1150-SDAG-NEXT:    s_addc_u32 s1, s1, s3
; GFX1150-SDAG-NEXT:    s_load_b256 s[0:7], s[0:1], 0x0
; GFX1150-SDAG-NEXT:  .LBB11_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s14, v4
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s14, v4
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s16, v5
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s17, v6
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s18, v7
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s19, v8
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX1150-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1150-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[0:7], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX1150-SDAG-NEXT:    s_and_not1_wrexec_b64 s[12:13], s[12:13]
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8
; GFX1150-SDAG-NEXT:    s_cbranch_execnz .LBB11_1
; GFX1150-SDAG-NEXT:  ; %bb.2:
; GFX1150-SDAG-NEXT:    s_mov_b64 exec, s[10:11]
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-SDAG-NEXT:    s_and_b64 exec, exec, s[8:9]
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:    ; return to shader part epilog
;
; GFX1150-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_1:
; GFX1150-GISEL:       ; %bb.0:
; GFX1150-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX1150-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX1150-GISEL-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX1150-GISEL-NEXT:    s_mov_b32 s8, s5
; GFX1150-GISEL-NEXT:    s_ashr_i32 s9, s5, 31
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v9, s4
; GFX1150-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 4, v[1:2]
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v2, s2
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v3, s3
; GFX1150-GISEL-NEXT:    s_lshl_b64 s[2:3], s[8:9], 5
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX1150-GISEL-NEXT:    s_add_u32 s0, s0, s2
; GFX1150-GISEL-NEXT:    v_add_co_u32 v0, vcc, v2, v0
; GFX1150-GISEL-NEXT:    s_addc_u32 s1, s1, s3
; GFX1150-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX1150-GISEL-NEXT:    s_load_b256 s[8:15], s[0:1], 0x0
; GFX1150-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX1150-GISEL-NEXT:    v_add_co_ci_u32_e64 v1, null, v3, v1, vcc
; GFX1150-GISEL-NEXT:    global_load_b128 v[5:8], v[0:1], off
; GFX1150-GISEL-NEXT:  .LBB11_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s4, v9
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s5, v4
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s4, v9
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s5, v4
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s16, v5
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s17, v6
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s18, v7
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s19, v8
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX1150-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1150-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX1150-GISEL-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr9
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8
; GFX1150-GISEL-NEXT:    s_cbranch_execnz .LBB11_1
; GFX1150-GISEL-NEXT:  ; %bb.2:
; GFX1150-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    ; return to shader part epilog
;
; GFX12-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_1:
; GFX12-SDAG:       ; %bb.0:
; GFX12-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX12-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX12-SDAG-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX12-SDAG-NEXT:    s_mov_b32 s4, s5
; GFX12-SDAG-NEXT:    s_ashr_i32 s5, s5, 31
; GFX12-SDAG-NEXT:    s_mov_b64 s[12:13], exec
; GFX12-SDAG-NEXT:    v_lshlrev_b64_e32 v[0:1], 4, v[1:2]
; GFX12-SDAG-NEXT:    s_mov_b64 s[10:11], exec
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX12-SDAG-NEXT:    v_add_co_u32 v0, vcc, s2, v0
; GFX12-SDAG-NEXT:    v_add_co_ci_u32_e64 v1, null, s3, v1, vcc
; GFX12-SDAG-NEXT:    s_lshl_b64 s[2:3], s[4:5], 5
; GFX12-SDAG-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-SDAG-NEXT:    s_add_nc_u64 s[0:1], s[0:1], s[2:3]
; GFX12-SDAG-NEXT:    global_load_b128 v[5:8], v[0:1], off
; GFX12-SDAG-NEXT:    s_load_b256 s[0:7], s[0:1], 0x0
; GFX12-SDAG-NEXT:  .LBB11_1: ; =>This Inner Loop Header: Depth=1
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s14, v4
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s14, v4
; GFX12-SDAG-NEXT:    s_wait_loadcnt 0x0
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s16, v5
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s17, v6
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s18, v7
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s19, v8
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX12-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX12-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[0:7], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX12-SDAG-NEXT:    s_and_not1_wrexec_b64 s[12:13], s[12:13]
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8
; GFX12-SDAG-NEXT:    s_cbranch_execnz .LBB11_1
; GFX12-SDAG-NEXT:  ; %bb.2:
; GFX12-SDAG-NEXT:    s_mov_b64 exec, s[10:11]
; GFX12-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-SDAG-NEXT:    s_and_b64 exec, exec, s[8:9]
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    ; return to shader part epilog
;
; GFX12-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_1:
; GFX12-GISEL:       ; %bb.0:
; GFX12-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX12-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX12-GISEL-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX12-GISEL-NEXT:    s_mov_b32 s8, s5
; GFX12-GISEL-NEXT:    s_ashr_i32 s9, s5, 31
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v9, s4
; GFX12-GISEL-NEXT:    v_lshlrev_b64_e32 v[0:1], 4, v[1:2]
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v2, s2
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v3, s3
; GFX12-GISEL-NEXT:    s_lshl_b64 s[2:3], s[8:9], 5
; GFX12-GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-GISEL-NEXT:    s_add_co_u32 s0, s0, s2
; GFX12-GISEL-NEXT:    v_add_co_u32 v0, vcc, v2, v0
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX12-GISEL-NEXT:    v_add_co_ci_u32_e64 v1, null, v3, v1, vcc
; GFX12-GISEL-NEXT:    s_add_co_ci_u32 s1, s1, s3
; GFX12-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX12-GISEL-NEXT:    s_load_b256 s[8:15], s[0:1], 0x0
; GFX12-GISEL-NEXT:    global_load_b128 v[5:8], v[0:1], off
; GFX12-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX12-GISEL-NEXT:  .LBB11_1: ; =>This Inner Loop Header: Depth=1
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s4, v9
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s5, v4
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s4, v9
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s5, v4
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x0
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s16, v5
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s17, v6
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s18, v7
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s19, v8
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX12-GISEL-NEXT:    s_wait_kmcnt 0x0
; GFX12-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX12-GISEL-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr9
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8
; GFX12-GISEL-NEXT:    s_cbranch_execnz .LBB11_1
; GFX12-GISEL-NEXT:  ; %bb.2:
; GFX12-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX12-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-GISEL-NEXT:    ; return to shader part epilog
       <4 x i32> addrspace(4)* inreg %s_in, i32 inreg %idx1, i32 %idx2, i32 inreg %s_idx, i32 %s_idx2) #1 {
  %rptr = getelementptr <8 x i32>, <8 x i32> addrspace(4)* %in, i32 %s_idx
  %sptr = getelementptr <4 x i32>, <4 x i32> addrspace(4)* %s_in, i32 %s_idx2
  %rsrc = load <8 x i32>, <8 x i32> addrspace(4)* %rptr, align 16
  %srsrc = load <4 x i32>, <4 x i32> addrspace(4)* %sptr, align 16
  %tok = call token @llvm.amdgcn.waterfall.begin.i32(token poison, i32 %idx1)
  %tok1 = call token @llvm.amdgcn.waterfall.begin.i32(token %tok, i32 %idx2)
  %s_rsrc = call <8 x i32> @llvm.amdgcn.waterfall.readfirstlane.v8i32.v8i32(token %tok1, <8 x i32> %rsrc)
  %s_srsrc = call <4 x i32> @llvm.amdgcn.waterfall.readfirstlane.v4i32.v4i32(token %tok1, <4 x i32> %srsrc)
  %r = call <4 x float> @llvm.amdgcn.image.sample.2d.v4f32.f32(i32 15, float 0.000000e+00, float 0.000000e+00, <8 x i32> %s_rsrc, <4 x i32> %s_srsrc, i1 false, i32 0, i32 0)
  %r1 = call <4 x float> @llvm.amdgcn.waterfall.end.v4f32(token %tok1, <4 x float> %r)

  ret <4 x float> %r1
}

define amdgpu_ps <4 x float> @test_waterfall_multi_begin_uniform_idx_2(<8 x i32> addrspace(4)* inreg %in,
; VI-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_2:
; VI-SDAG:       ; %bb.0:
; VI-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; VI-SDAG-NEXT:    s_mov_b32 s4, s5
; VI-SDAG-NEXT:    s_wqm_b64 exec, exec
; VI-SDAG-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; VI-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; VI-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[1:2]
; VI-SDAG-NEXT:    v_mov_b32_e32 v2, s1
; VI-SDAG-NEXT:    v_add_u32_e32 v0, vcc, s0, v0
; VI-SDAG-NEXT:    v_addc_u32_e32 v1, vcc, v2, v1, vcc
; VI-SDAG-NEXT:    flat_load_dwordx4 v[5:8], v[0:1]
; VI-SDAG-NEXT:    v_add_u32_e32 v0, vcc, 16, v0
; VI-SDAG-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-SDAG-NEXT:    flat_load_dwordx4 v[9:12], v[0:1]
; VI-SDAG-NEXT:    s_ashr_i32 s5, s5, 31
; VI-SDAG-NEXT:    s_lshl_b64 s[0:1], s[4:5], 4
; VI-SDAG-NEXT:    s_add_u32 s0, s2, s0
; VI-SDAG-NEXT:    s_addc_u32 s1, s3, s1
; VI-SDAG-NEXT:    s_load_dwordx4 s[0:3], s[0:1], 0x0
; VI-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; VI-SDAG-NEXT:  .LBB12_1: ; =>This Inner Loop Header: Depth=1
; VI-SDAG-NEXT:    v_readfirstlane_b32 s8, v4
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[8:9], s8, v4
; VI-SDAG-NEXT:    s_and_saveexec_b64 s[16:17], s[8:9]
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; VI-SDAG-NEXT:    s_waitcnt vmcnt(1)
; VI-SDAG-NEXT:    v_readfirstlane_b32 s8, v5
; VI-SDAG-NEXT:    v_readfirstlane_b32 s9, v6
; VI-SDAG-NEXT:    v_readfirstlane_b32 s10, v7
; VI-SDAG-NEXT:    v_readfirstlane_b32 s11, v8
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    v_readfirstlane_b32 s12, v9
; VI-SDAG-NEXT:    v_readfirstlane_b32 s13, v10
; VI-SDAG-NEXT:    v_readfirstlane_b32 s14, v11
; VI-SDAG-NEXT:    v_readfirstlane_b32 s15, v12
; VI-SDAG-NEXT:    v_mov_b32_e32 v1, v0
; VI-SDAG-NEXT:    ; implicit-def: $vgpr4
; VI-SDAG-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; VI-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; VI-SDAG-NEXT:    s_nop 2
; VI-SDAG-NEXT:    image_sample v[0:3], v[0:1], s[8:15], s[0:3] dmask:0xf
; VI-SDAG-NEXT:    s_xor_b64 exec, exec, s[16:17]
; VI-SDAG-NEXT:    s_cbranch_execnz .LBB12_1
; VI-SDAG-NEXT:  ; %bb.2:
; VI-SDAG-NEXT:    s_mov_b64 exec, s[4:5]
; VI-SDAG-NEXT:    s_and_b64 exec, exec, s[6:7]
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    ; return to shader part epilog
;
; VI-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_2:
; VI-GISEL:       ; %bb.0:
; VI-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; VI-GISEL-NEXT:    s_wqm_b64 exec, exec
; VI-GISEL-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; VI-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; VI-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[1:2]
; VI-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; VI-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; VI-GISEL-NEXT:    v_add_u32_e32 v0, vcc, v2, v0
; VI-GISEL-NEXT:    v_addc_u32_e32 v1, vcc, v3, v1, vcc
; VI-GISEL-NEXT:    flat_load_dwordx4 v[5:8], v[0:1]
; VI-GISEL-NEXT:    v_add_u32_e32 v0, vcc, 16, v0
; VI-GISEL-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-GISEL-NEXT:    flat_load_dwordx4 v[9:12], v[0:1]
; VI-GISEL-NEXT:    s_mov_b32 s8, s5
; VI-GISEL-NEXT:    s_ashr_i32 s9, s5, 31
; VI-GISEL-NEXT:    s_lshl_b64 s[0:1], s[8:9], 4
; VI-GISEL-NEXT:    s_add_u32 s0, s2, s0
; VI-GISEL-NEXT:    s_addc_u32 s1, s3, s1
; VI-GISEL-NEXT:    s_load_dwordx4 s[0:3], s[0:1], 0x0
; VI-GISEL-NEXT:    v_mov_b32_e32 v13, s4
; VI-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; VI-GISEL-NEXT:    s_mov_b32 s18, 0
; VI-GISEL-NEXT:  .LBB12_1: ; =>This Inner Loop Header: Depth=1
; VI-GISEL-NEXT:    v_readfirstlane_b32 s8, v4
; VI-GISEL-NEXT:    v_readfirstlane_b32 s10, v13
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[8:9], s8, v4
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[10:11], s10, v13
; VI-GISEL-NEXT:    s_and_b64 s[8:9], s[8:9], s[10:11]
; VI-GISEL-NEXT:    s_and_saveexec_b64 s[16:17], s[8:9]
; VI-GISEL-NEXT:    s_mov_b32 s19, s18
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    v_mov_b32_e32 v0, s18
; VI-GISEL-NEXT:    s_waitcnt vmcnt(1)
; VI-GISEL-NEXT:    v_readfirstlane_b32 s8, v5
; VI-GISEL-NEXT:    v_readfirstlane_b32 s9, v6
; VI-GISEL-NEXT:    v_readfirstlane_b32 s10, v7
; VI-GISEL-NEXT:    v_readfirstlane_b32 s11, v8
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    v_readfirstlane_b32 s12, v9
; VI-GISEL-NEXT:    v_readfirstlane_b32 s13, v10
; VI-GISEL-NEXT:    v_readfirstlane_b32 s14, v11
; VI-GISEL-NEXT:    v_readfirstlane_b32 s15, v12
; VI-GISEL-NEXT:    v_mov_b32_e32 v1, s19
; VI-GISEL-NEXT:    ; implicit-def: $vgpr4
; VI-GISEL-NEXT:    ; implicit-def: $vgpr13
; VI-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; VI-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; VI-GISEL-NEXT:    s_nop 2
; VI-GISEL-NEXT:    image_sample v[0:3], v[0:1], s[8:15], s[0:3] dmask:0xf
; VI-GISEL-NEXT:    s_xor_b64 exec, exec, s[16:17]
; VI-GISEL-NEXT:    s_cbranch_execnz .LBB12_1
; VI-GISEL-NEXT:  ; %bb.2:
; VI-GISEL-NEXT:    s_mov_b64 exec, s[4:5]
; VI-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    ; return to shader part epilog
;
; GFX9-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_2:
; GFX9-SDAG:       ; %bb.0:
; GFX9-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; GFX9-SDAG-NEXT:    s_mov_b32 s4, s5
; GFX9-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX9-SDAG-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX9-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[1:2]
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v2, s1
; GFX9-SDAG-NEXT:    v_add_co_u32_e32 v0, vcc, s0, v0
; GFX9-SDAG-NEXT:    v_addc_co_u32_e32 v1, vcc, v2, v1, vcc
; GFX9-SDAG-NEXT:    global_load_dwordx4 v[9:12], v[0:1], off offset:16
; GFX9-SDAG-NEXT:    global_load_dwordx4 v[5:8], v[0:1], off
; GFX9-SDAG-NEXT:    s_ashr_i32 s5, s5, 31
; GFX9-SDAG-NEXT:    s_lshl_b64 s[0:1], s[4:5], 4
; GFX9-SDAG-NEXT:    s_add_u32 s0, s2, s0
; GFX9-SDAG-NEXT:    s_addc_u32 s1, s3, s1
; GFX9-SDAG-NEXT:    s_load_dwordx4 s[0:3], s[0:1], 0x0
; GFX9-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX9-SDAG-NEXT:  .LBB12_1: ; =>This Inner Loop Header: Depth=1
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s8, v4
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[8:9], s8, v4
; GFX9-SDAG-NEXT:    s_and_saveexec_b64 s[16:17], s[8:9]
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s8, v5
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s9, v6
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s10, v7
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s11, v8
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s12, v9
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s13, v10
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s14, v11
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s15, v12
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v1, v0
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX9-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; GFX9-SDAG-NEXT:    s_nop 2
; GFX9-SDAG-NEXT:    image_sample v[0:3], v[0:1], s[8:15], s[0:3] dmask:0xf
; GFX9-SDAG-NEXT:    s_xor_b64 exec, exec, s[16:17]
; GFX9-SDAG-NEXT:    s_cbranch_execnz .LBB12_1
; GFX9-SDAG-NEXT:  ; %bb.2:
; GFX9-SDAG-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-SDAG-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    ; return to shader part epilog
;
; GFX9-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_2:
; GFX9-GISEL:       ; %bb.0:
; GFX9-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX9-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX9-GISEL-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX9-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[1:2]
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX9-GISEL-NEXT:    v_add_co_u32_e32 v0, vcc, v2, v0
; GFX9-GISEL-NEXT:    v_addc_co_u32_e32 v1, vcc, v3, v1, vcc
; GFX9-GISEL-NEXT:    global_load_dwordx4 v[5:8], v[0:1], off
; GFX9-GISEL-NEXT:    global_load_dwordx4 v[9:12], v[0:1], off offset:16
; GFX9-GISEL-NEXT:    s_mov_b32 s8, s5
; GFX9-GISEL-NEXT:    s_ashr_i32 s9, s5, 31
; GFX9-GISEL-NEXT:    s_lshl_b64 s[0:1], s[8:9], 4
; GFX9-GISEL-NEXT:    s_add_u32 s0, s2, s0
; GFX9-GISEL-NEXT:    s_addc_u32 s1, s3, s1
; GFX9-GISEL-NEXT:    s_load_dwordx4 s[0:3], s[0:1], 0x0
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v13, s4
; GFX9-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX9-GISEL-NEXT:    s_mov_b32 s18, 0
; GFX9-GISEL-NEXT:  .LBB12_1: ; =>This Inner Loop Header: Depth=1
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s8, v4
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s10, v13
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[8:9], s8, v4
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[10:11], s10, v13
; GFX9-GISEL-NEXT:    s_and_b64 s[8:9], s[8:9], s[10:11]
; GFX9-GISEL-NEXT:    s_and_saveexec_b64 s[16:17], s[8:9]
; GFX9-GISEL-NEXT:    s_mov_b32 s19, s18
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v0, s18
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(1)
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s8, v5
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s9, v6
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s10, v7
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s11, v8
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s12, v9
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s13, v10
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s14, v11
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s15, v12
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v1, s19
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr13
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX9-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; GFX9-GISEL-NEXT:    s_nop 2
; GFX9-GISEL-NEXT:    image_sample v[0:3], v[0:1], s[8:15], s[0:3] dmask:0xf
; GFX9-GISEL-NEXT:    s_xor_b64 exec, exec, s[16:17]
; GFX9-GISEL-NEXT:    s_cbranch_execnz .LBB12_1
; GFX9-GISEL-NEXT:  ; %bb.2:
; GFX9-GISEL-NEXT:    s_mov_b64 exec, s[4:5]
; GFX9-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-32-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_2:
; GFX10-32-SDAG:       ; %bb.0:
; GFX10-32-SDAG-NEXT:    s_mov_b32 s4, exec_lo
; GFX10-32-SDAG-NEXT:    s_mov_b32 s6, s5
; GFX10-32-SDAG-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-SDAG-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-32-SDAG-NEXT:    s_ashr_i32 s7, s5, 31
; GFX10-32-SDAG-NEXT:    s_mov_b32 s5, exec_lo
; GFX10-32-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[1:2]
; GFX10-32-SDAG-NEXT:    v_add_co_u32 v0, vcc_lo, s0, v0
; GFX10-32-SDAG-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, s1, v1, vcc_lo
; GFX10-32-SDAG-NEXT:    s_lshl_b64 s[0:1], s[6:7], 4
; GFX10-32-SDAG-NEXT:    s_mov_b32 s6, exec_lo
; GFX10-32-SDAG-NEXT:    s_add_u32 s0, s2, s0
; GFX10-32-SDAG-NEXT:    s_clause 0x1
; GFX10-32-SDAG-NEXT:    global_load_dwordx4 v[9:12], v[0:1], off offset:16
; GFX10-32-SDAG-NEXT:    global_load_dwordx4 v[5:8], v[0:1], off
; GFX10-32-SDAG-NEXT:    s_addc_u32 s1, s3, s1
; GFX10-32-SDAG-NEXT:    s_load_dwordx4 s[0:3], s[0:1], 0x0
; GFX10-32-SDAG-NEXT:  .LBB12_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s7, v4
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s7, v4
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s8, v5
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s9, v6
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s10, v7
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s11, v8
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s12, v9
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s13, v10
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s14, v11
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s15, v12
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-32-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-32-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[0:3] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-32-SDAG-NEXT:    s_andn2_wrexec_b32 s6, s6
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX10-32-SDAG-NEXT:    s_cbranch_execnz .LBB12_1
; GFX10-32-SDAG-NEXT:  ; %bb.2:
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-SDAG-NEXT:    s_mov_b32 exec_lo, s5
; GFX10-32-SDAG-NEXT:    s_and_b32 exec_lo, exec_lo, s4
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-32-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_2:
; GFX10-32-GISEL:       ; %bb.0:
; GFX10-32-GISEL-NEXT:    s_mov_b32 s6, exec_lo
; GFX10-32-GISEL-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-GISEL-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-32-GISEL-NEXT:    s_mov_b32 s8, s5
; GFX10-32-GISEL-NEXT:    s_ashr_i32 s9, s5, 31
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v13, s4
; GFX10-32-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[1:2]
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX10-32-GISEL-NEXT:    s_lshl_b64 s[0:1], s[8:9], 4
; GFX10-32-GISEL-NEXT:    s_mov_b32 s5, exec_lo
; GFX10-32-GISEL-NEXT:    s_add_u32 s0, s2, s0
; GFX10-32-GISEL-NEXT:    s_addc_u32 s1, s3, s1
; GFX10-32-GISEL-NEXT:    v_add_co_u32 v0, vcc_lo, v2, v0
; GFX10-32-GISEL-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, v3, v1, vcc_lo
; GFX10-32-GISEL-NEXT:    s_load_dwordx4 s[0:3], s[0:1], 0x0
; GFX10-32-GISEL-NEXT:    s_mov_b32 s4, exec_lo
; GFX10-32-GISEL-NEXT:    s_clause 0x1
; GFX10-32-GISEL-NEXT:    global_load_dwordx4 v[5:8], v[0:1], off
; GFX10-32-GISEL-NEXT:    global_load_dwordx4 v[9:12], v[0:1], off offset:16
; GFX10-32-GISEL-NEXT:  .LBB12_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s7, v4
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s8, v13
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s7, v4
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s8, v13
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(1)
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s8, v5
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s9, v6
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s10, v7
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s11, v8
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s12, v9
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s13, v10
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s14, v11
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s15, v12
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-32-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-32-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[0:3] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-32-GISEL-NEXT:    s_andn2_wrexec_b32 s5, s5
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr13
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX10-32-GISEL-NEXT:    s_cbranch_execnz .LBB12_1
; GFX10-32-GISEL-NEXT:  ; %bb.2:
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-GISEL-NEXT:    s_mov_b32 exec_lo, s4
; GFX10-32-GISEL-NEXT:    s_and_b32 exec_lo, exec_lo, s6
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-64-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_2:
; GFX10-64-SDAG:       ; %bb.0:
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; GFX10-64-SDAG-NEXT:    s_mov_b32 s4, s5
; GFX10-64-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-SDAG-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-64-SDAG-NEXT:    s_ashr_i32 s5, s5, 31
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX10-64-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[1:2]
; GFX10-64-SDAG-NEXT:    v_add_co_u32 v0, vcc, s0, v0
; GFX10-64-SDAG-NEXT:    v_add_co_ci_u32_e32 v1, vcc, s1, v1, vcc
; GFX10-64-SDAG-NEXT:    s_lshl_b64 s[0:1], s[4:5], 4
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX10-64-SDAG-NEXT:    s_add_u32 s0, s2, s0
; GFX10-64-SDAG-NEXT:    s_clause 0x1
; GFX10-64-SDAG-NEXT:    global_load_dwordx4 v[9:12], v[0:1], off offset:16
; GFX10-64-SDAG-NEXT:    global_load_dwordx4 v[5:8], v[0:1], off
; GFX10-64-SDAG-NEXT:    s_addc_u32 s1, s3, s1
; GFX10-64-SDAG-NEXT:    s_load_dwordx4 s[0:3], s[0:1], 0x0
; GFX10-64-SDAG-NEXT:  .LBB12_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s10, v4
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s10, v4
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s12, v5
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s13, v6
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s14, v7
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s15, v8
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s16, v9
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s17, v10
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s18, v11
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s19, v12
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-64-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-64-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[12:19], s[0:3] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-64-SDAG-NEXT:    s_andn2_wrexec_b64 s[8:9], s[8:9]
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX10-64-SDAG-NEXT:    s_cbranch_execnz .LBB12_1
; GFX10-64-SDAG-NEXT:  ; %bb.2:
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-SDAG-NEXT:    s_mov_b64 exec, s[4:5]
; GFX10-64-SDAG-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-64-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_2:
; GFX10-64-GISEL:       ; %bb.0:
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX10-64-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-GISEL-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-64-GISEL-NEXT:    s_mov_b32 s8, s5
; GFX10-64-GISEL-NEXT:    s_ashr_i32 s9, s5, 31
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v13, s4
; GFX10-64-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[1:2]
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX10-64-GISEL-NEXT:    s_lshl_b64 s[0:1], s[8:9], 4
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[8:9], exec
; GFX10-64-GISEL-NEXT:    s_add_u32 s0, s2, s0
; GFX10-64-GISEL-NEXT:    s_addc_u32 s1, s3, s1
; GFX10-64-GISEL-NEXT:    v_add_co_u32 v0, vcc, v2, v0
; GFX10-64-GISEL-NEXT:    v_add_co_ci_u32_e32 v1, vcc, v3, v1, vcc
; GFX10-64-GISEL-NEXT:    s_load_dwordx4 s[0:3], s[0:1], 0x0
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX10-64-GISEL-NEXT:    s_clause 0x1
; GFX10-64-GISEL-NEXT:    global_load_dwordx4 v[5:8], v[0:1], off
; GFX10-64-GISEL-NEXT:    global_load_dwordx4 v[9:12], v[0:1], off offset:16
; GFX10-64-GISEL-NEXT:  .LBB12_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s10, v4
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s11, v13
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s10, v4
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s11, v13
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(1)
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s12, v5
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s13, v6
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s14, v7
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s15, v8
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s16, v9
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s17, v10
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s18, v11
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s19, v12
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-64-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-64-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[12:19], s[0:3] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-64-GISEL-NEXT:    s_andn2_wrexec_b64 s[8:9], s[8:9]
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr13
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX10-64-GISEL-NEXT:    s_cbranch_execnz .LBB12_1
; GFX10-64-GISEL-NEXT:  ; %bb.2:
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-GISEL-NEXT:    s_mov_b64 exec, s[4:5]
; GFX10-64-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:    ; return to shader part epilog
;
; GFX1150-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_2:
; GFX1150-SDAG:       ; %bb.0:
; GFX1150-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; GFX1150-SDAG-NEXT:    s_mov_b32 s4, s5
; GFX1150-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX1150-SDAG-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX1150-SDAG-NEXT:    s_ashr_i32 s5, s5, 31
; GFX1150-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX1150-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[1:2]
; GFX1150-SDAG-NEXT:    v_add_co_u32 v0, vcc, s0, v0
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1150-SDAG-NEXT:    v_add_co_ci_u32_e64 v1, null, s1, v1, vcc
; GFX1150-SDAG-NEXT:    s_clause 0x1
; GFX1150-SDAG-NEXT:    global_load_b128 v[9:12], v[0:1], off offset:16
; GFX1150-SDAG-NEXT:    global_load_b128 v[5:8], v[0:1], off
; GFX1150-SDAG-NEXT:    s_lshl_b64 s[0:1], s[4:5], 4
; GFX1150-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX1150-SDAG-NEXT:    s_add_u32 s0, s2, s0
; GFX1150-SDAG-NEXT:    s_addc_u32 s1, s3, s1
; GFX1150-SDAG-NEXT:    s_load_b128 s[0:3], s[0:1], 0x0
; GFX1150-SDAG-NEXT:  .LBB12_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s10, v4
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s10, v4
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s12, v5
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s13, v6
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s14, v7
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s15, v8
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s16, v9
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s17, v10
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s18, v11
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s19, v12
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX1150-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1150-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[12:19], s[0:3] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX1150-SDAG-NEXT:    s_and_not1_wrexec_b64 s[8:9], s[8:9]
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX1150-SDAG-NEXT:    s_cbranch_execnz .LBB12_1
; GFX1150-SDAG-NEXT:  ; %bb.2:
; GFX1150-SDAG-NEXT:    s_mov_b64 exec, s[4:5]
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-SDAG-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:    ; return to shader part epilog
;
; GFX1150-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_2:
; GFX1150-GISEL:       ; %bb.0:
; GFX1150-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX1150-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX1150-GISEL-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX1150-GISEL-NEXT:    s_mov_b32 s8, s5
; GFX1150-GISEL-NEXT:    s_ashr_i32 s9, s5, 31
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v13, s4
; GFX1150-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[1:2]
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX1150-GISEL-NEXT:    s_lshl_b64 s[0:1], s[8:9], 4
; GFX1150-GISEL-NEXT:    s_mov_b64 s[8:9], exec
; GFX1150-GISEL-NEXT:    s_add_u32 s0, s2, s0
; GFX1150-GISEL-NEXT:    s_addc_u32 s1, s3, s1
; GFX1150-GISEL-NEXT:    v_add_co_u32 v0, vcc, v2, v0
; GFX1150-GISEL-NEXT:    s_load_b128 s[0:3], s[0:1], 0x0
; GFX1150-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX1150-GISEL-NEXT:    v_add_co_ci_u32_e64 v1, null, v3, v1, vcc
; GFX1150-GISEL-NEXT:    s_clause 0x1
; GFX1150-GISEL-NEXT:    global_load_b128 v[5:8], v[0:1], off
; GFX1150-GISEL-NEXT:    global_load_b128 v[9:12], v[0:1], off offset:16
; GFX1150-GISEL-NEXT:  .LBB12_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s10, v4
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s11, v13
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s10, v4
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s11, v13
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(1)
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s12, v5
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s13, v6
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s14, v7
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s15, v8
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s16, v9
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s17, v10
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s18, v11
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s19, v12
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX1150-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1150-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[12:19], s[0:3] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX1150-GISEL-NEXT:    s_and_not1_wrexec_b64 s[8:9], s[8:9]
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr13
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX1150-GISEL-NEXT:    s_cbranch_execnz .LBB12_1
; GFX1150-GISEL-NEXT:  ; %bb.2:
; GFX1150-GISEL-NEXT:    s_mov_b64 exec, s[4:5]
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    ; return to shader part epilog
;
; GFX12-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_2:
; GFX12-SDAG:       ; %bb.0:
; GFX12-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; GFX12-SDAG-NEXT:    s_mov_b32 s4, s5
; GFX12-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX12-SDAG-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX12-SDAG-NEXT:    s_ashr_i32 s5, s5, 31
; GFX12-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX12-SDAG-NEXT:    v_lshlrev_b64_e32 v[0:1], 5, v[1:2]
; GFX12-SDAG-NEXT:    v_add_co_u32 v0, vcc, s0, v0
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX12-SDAG-NEXT:    v_add_co_ci_u32_e64 v1, null, s1, v1, vcc
; GFX12-SDAG-NEXT:    s_lshl_b64 s[0:1], s[4:5], 4
; GFX12-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX12-SDAG-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-SDAG-NEXT:    s_add_nc_u64 s[0:1], s[2:3], s[0:1]
; GFX12-SDAG-NEXT:    s_clause 0x1
; GFX12-SDAG-NEXT:    global_load_b128 v[9:12], v[0:1], off offset:16
; GFX12-SDAG-NEXT:    global_load_b128 v[5:8], v[0:1], off
; GFX12-SDAG-NEXT:    s_load_b128 s[0:3], s[0:1], 0x0
; GFX12-SDAG-NEXT:  .LBB12_1: ; =>This Inner Loop Header: Depth=1
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s10, v4
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s10, v4
; GFX12-SDAG-NEXT:    s_wait_loadcnt 0x0
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s12, v5
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s13, v6
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s14, v7
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s15, v8
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s16, v9
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s17, v10
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s18, v11
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s19, v12
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX12-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX12-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[12:19], s[0:3] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX12-SDAG-NEXT:    s_and_not1_wrexec_b64 s[8:9], s[8:9]
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX12-SDAG-NEXT:    s_cbranch_execnz .LBB12_1
; GFX12-SDAG-NEXT:  ; %bb.2:
; GFX12-SDAG-NEXT:    s_mov_b64 exec, s[4:5]
; GFX12-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-SDAG-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    ; return to shader part epilog
;
; GFX12-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_2:
; GFX12-GISEL:       ; %bb.0:
; GFX12-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX12-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX12-GISEL-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX12-GISEL-NEXT:    s_mov_b32 s8, s5
; GFX12-GISEL-NEXT:    s_ashr_i32 s9, s5, 31
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v13, s4
; GFX12-GISEL-NEXT:    v_lshlrev_b64_e32 v[0:1], 5, v[1:2]
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX12-GISEL-NEXT:    s_lshl_b64 s[0:1], s[8:9], 4
; GFX12-GISEL-NEXT:    s_mov_b64 s[8:9], exec
; GFX12-GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-GISEL-NEXT:    s_add_co_u32 s0, s2, s0
; GFX12-GISEL-NEXT:    s_add_co_ci_u32 s1, s3, s1
; GFX12-GISEL-NEXT:    v_add_co_u32 v0, vcc, v2, v0
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX12-GISEL-NEXT:    v_add_co_ci_u32_e64 v1, null, v3, v1, vcc
; GFX12-GISEL-NEXT:    s_load_b128 s[0:3], s[0:1], 0x0
; GFX12-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX12-GISEL-NEXT:    s_clause 0x1
; GFX12-GISEL-NEXT:    global_load_b128 v[5:8], v[0:1], off
; GFX12-GISEL-NEXT:    global_load_b128 v[9:12], v[0:1], off offset:16
; GFX12-GISEL-NEXT:  .LBB12_1: ; =>This Inner Loop Header: Depth=1
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s10, v4
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s11, v13
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s10, v4
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s11, v13
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x1
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s12, v5
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s13, v6
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s14, v7
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s15, v8
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x0
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s16, v9
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s17, v10
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s18, v11
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s19, v12
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX12-GISEL-NEXT:    s_wait_kmcnt 0x0
; GFX12-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[12:19], s[0:3] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX12-GISEL-NEXT:    s_and_not1_wrexec_b64 s[8:9], s[8:9]
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr13
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX12-GISEL-NEXT:    s_cbranch_execnz .LBB12_1
; GFX12-GISEL-NEXT:  ; %bb.2:
; GFX12-GISEL-NEXT:    s_mov_b64 exec, s[4:5]
; GFX12-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    ; return to shader part epilog
       <4 x i32> addrspace(4)* inreg %s_in, i32 %idx1, i32 inreg %idx2, i32 %s_idx, i32 inreg %s_idx2) #1 {
  %rptr = getelementptr <8 x i32>, <8 x i32> addrspace(4)* %in, i32 %s_idx
  %sptr = getelementptr <4 x i32>, <4 x i32> addrspace(4)* %s_in, i32 %s_idx2
  %rsrc = load <8 x i32>, <8 x i32> addrspace(4)* %rptr, align 16
  %srsrc = load <4 x i32>, <4 x i32> addrspace(4)* %sptr, align 16
  %tok = call token @llvm.amdgcn.waterfall.begin.i32(token poison, i32 %idx1)
  %tok1 = call token @llvm.amdgcn.waterfall.begin.i32(token %tok, i32 %idx2)
  %s_rsrc = call <8 x i32> @llvm.amdgcn.waterfall.readfirstlane.v8i32.v8i32(token %tok1, <8 x i32> %rsrc)
  %s_srsrc = call <4 x i32> @llvm.amdgcn.waterfall.readfirstlane.v4i32.v4i32(token %tok1, <4 x i32> %srsrc)
  %r = call <4 x float> @llvm.amdgcn.image.sample.2d.v4f32.f32(i32 15, float 0.000000e+00, float 0.000000e+00, <8 x i32> %s_rsrc, <4 x i32> %s_srsrc, i1 false, i32 0, i32 0)
  %r1 = call <4 x float> @llvm.amdgcn.waterfall.end.v4f32(token %tok1, <4 x float> %r)

  ret <4 x float> %r1
}

define amdgpu_ps <4 x float> @test_waterfall_multi_begin_uniform_idx_3(<8 x i32> addrspace(4)* inreg %in,
; VI-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_3:
; VI-SDAG:       ; %bb.0:
; VI-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; VI-SDAG-NEXT:    s_wqm_b64 exec, exec
; VI-SDAG-NEXT:    v_mov_b32_e32 v5, v1
; VI-SDAG-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; VI-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; VI-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[5:6]
; VI-SDAG-NEXT:    v_mov_b32_e32 v3, s1
; VI-SDAG-NEXT:    v_add_u32_e32 v0, vcc, s0, v0
; VI-SDAG-NEXT:    v_addc_u32_e32 v1, vcc, v3, v1, vcc
; VI-SDAG-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; VI-SDAG-NEXT:    v_lshlrev_b64 v[2:3], 4, v[2:3]
; VI-SDAG-NEXT:    v_mov_b32_e32 v5, s3
; VI-SDAG-NEXT:    v_add_u32_e32 v2, vcc, s2, v2
; VI-SDAG-NEXT:    v_addc_u32_e32 v3, vcc, v5, v3, vcc
; VI-SDAG-NEXT:    flat_load_dwordx4 v[5:8], v[0:1]
; VI-SDAG-NEXT:    v_add_u32_e32 v0, vcc, 16, v0
; VI-SDAG-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-SDAG-NEXT:    flat_load_dwordx4 v[9:12], v[0:1]
; VI-SDAG-NEXT:    flat_load_dwordx4 v[13:16], v[2:3]
; VI-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; VI-SDAG-NEXT:  .LBB13_1: ; =>This Inner Loop Header: Depth=1
; VI-SDAG-NEXT:    v_readfirstlane_b32 s2, v4
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v4
; VI-SDAG-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; VI-SDAG-NEXT:    s_waitcnt vmcnt(2)
; VI-SDAG-NEXT:    v_readfirstlane_b32 s8, v5
; VI-SDAG-NEXT:    v_readfirstlane_b32 s9, v6
; VI-SDAG-NEXT:    v_readfirstlane_b32 s10, v7
; VI-SDAG-NEXT:    v_readfirstlane_b32 s11, v8
; VI-SDAG-NEXT:    s_waitcnt vmcnt(1)
; VI-SDAG-NEXT:    v_readfirstlane_b32 s12, v9
; VI-SDAG-NEXT:    v_readfirstlane_b32 s13, v10
; VI-SDAG-NEXT:    v_readfirstlane_b32 s14, v11
; VI-SDAG-NEXT:    v_readfirstlane_b32 s15, v12
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    v_readfirstlane_b32 s16, v13
; VI-SDAG-NEXT:    v_readfirstlane_b32 s17, v14
; VI-SDAG-NEXT:    v_readfirstlane_b32 s18, v15
; VI-SDAG-NEXT:    v_readfirstlane_b32 s19, v16
; VI-SDAG-NEXT:    v_mov_b32_e32 v1, v0
; VI-SDAG-NEXT:    ; implicit-def: $vgpr4
; VI-SDAG-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; VI-SDAG-NEXT:    ; implicit-def: $vgpr13_vgpr14_vgpr15_vgpr16
; VI-SDAG-NEXT:    s_nop 3
; VI-SDAG-NEXT:    image_sample v[0:3], v[0:1], s[8:15], s[16:19] dmask:0xf
; VI-SDAG-NEXT:    s_xor_b64 exec, exec, s[2:3]
; VI-SDAG-NEXT:    s_cbranch_execnz .LBB13_1
; VI-SDAG-NEXT:  ; %bb.2:
; VI-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; VI-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    ; return to shader part epilog
;
; VI-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_3:
; VI-GISEL:       ; %bb.0:
; VI-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; VI-GISEL-NEXT:    s_wqm_b64 exec, exec
; VI-GISEL-NEXT:    v_mov_b32_e32 v5, v2
; VI-GISEL-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; VI-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; VI-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[1:2]
; VI-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; VI-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; VI-GISEL-NEXT:    v_add_u32_e32 v0, vcc, v2, v0
; VI-GISEL-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; VI-GISEL-NEXT:    v_addc_u32_e32 v1, vcc, v3, v1, vcc
; VI-GISEL-NEXT:    v_lshlrev_b64 v[2:3], 4, v[5:6]
; VI-GISEL-NEXT:    v_mov_b32_e32 v6, s3
; VI-GISEL-NEXT:    v_mov_b32_e32 v5, s2
; VI-GISEL-NEXT:    v_add_u32_e32 v2, vcc, v5, v2
; VI-GISEL-NEXT:    v_addc_u32_e32 v3, vcc, v6, v3, vcc
; VI-GISEL-NEXT:    flat_load_dwordx4 v[5:8], v[0:1]
; VI-GISEL-NEXT:    v_add_u32_e32 v0, vcc, 16, v0
; VI-GISEL-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-GISEL-NEXT:    flat_load_dwordx4 v[9:12], v[0:1]
; VI-GISEL-NEXT:    flat_load_dwordx4 v[13:16], v[2:3]
; VI-GISEL-NEXT:    v_mov_b32_e32 v17, s4
; VI-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; VI-GISEL-NEXT:  .LBB13_1: ; =>This Inner Loop Header: Depth=1
; VI-GISEL-NEXT:    v_readfirstlane_b32 s2, v17
; VI-GISEL-NEXT:    v_readfirstlane_b32 s4, v4
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v17
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[4:5], s4, v4
; VI-GISEL-NEXT:    s_and_b64 s[2:3], s[2:3], s[4:5]
; VI-GISEL-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; VI-GISEL-NEXT:    s_mov_b32 s4, 0
; VI-GISEL-NEXT:    s_mov_b32 s5, s4
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    v_mov_b32_e32 v0, s4
; VI-GISEL-NEXT:    s_waitcnt vmcnt(2)
; VI-GISEL-NEXT:    v_readfirstlane_b32 s8, v5
; VI-GISEL-NEXT:    v_readfirstlane_b32 s9, v6
; VI-GISEL-NEXT:    v_readfirstlane_b32 s10, v7
; VI-GISEL-NEXT:    v_readfirstlane_b32 s11, v8
; VI-GISEL-NEXT:    s_waitcnt vmcnt(1)
; VI-GISEL-NEXT:    v_readfirstlane_b32 s12, v9
; VI-GISEL-NEXT:    v_readfirstlane_b32 s13, v10
; VI-GISEL-NEXT:    v_readfirstlane_b32 s14, v11
; VI-GISEL-NEXT:    v_readfirstlane_b32 s15, v12
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    v_readfirstlane_b32 s16, v13
; VI-GISEL-NEXT:    v_readfirstlane_b32 s17, v14
; VI-GISEL-NEXT:    v_readfirstlane_b32 s18, v15
; VI-GISEL-NEXT:    v_readfirstlane_b32 s19, v16
; VI-GISEL-NEXT:    v_mov_b32_e32 v1, s5
; VI-GISEL-NEXT:    ; implicit-def: $vgpr17
; VI-GISEL-NEXT:    ; implicit-def: $vgpr4
; VI-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; VI-GISEL-NEXT:    ; implicit-def: $vgpr13_vgpr14_vgpr15_vgpr16
; VI-GISEL-NEXT:    s_nop 3
; VI-GISEL-NEXT:    image_sample v[0:3], v[0:1], s[8:15], s[16:19] dmask:0xf
; VI-GISEL-NEXT:    s_xor_b64 exec, exec, s[2:3]
; VI-GISEL-NEXT:    s_cbranch_execnz .LBB13_1
; VI-GISEL-NEXT:  ; %bb.2:
; VI-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; VI-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    ; return to shader part epilog
;
; GFX9-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_3:
; GFX9-SDAG:       ; %bb.0:
; GFX9-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX9-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v5, v1
; GFX9-SDAG-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX9-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[5:6]
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v3, s1
; GFX9-SDAG-NEXT:    v_add_co_u32_e32 v0, vcc, s0, v0
; GFX9-SDAG-NEXT:    v_addc_co_u32_e32 v1, vcc, v3, v1, vcc
; GFX9-SDAG-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX9-SDAG-NEXT:    v_lshlrev_b64 v[2:3], 4, v[2:3]
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v5, s3
; GFX9-SDAG-NEXT:    v_add_co_u32_e32 v2, vcc, s2, v2
; GFX9-SDAG-NEXT:    v_addc_co_u32_e32 v3, vcc, v5, v3, vcc
; GFX9-SDAG-NEXT:    global_load_dwordx4 v[9:12], v[0:1], off offset:16
; GFX9-SDAG-NEXT:    global_load_dwordx4 v[5:8], v[0:1], off
; GFX9-SDAG-NEXT:    global_load_dwordx4 v[13:16], v[2:3], off
; GFX9-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX9-SDAG-NEXT:  .LBB13_1: ; =>This Inner Loop Header: Depth=1
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s2, v4
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v4
; GFX9-SDAG-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(1)
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s8, v5
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s9, v6
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s10, v7
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s11, v8
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s12, v9
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s13, v10
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s14, v11
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s15, v12
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s16, v13
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s17, v14
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s18, v15
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s19, v16
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v1, v0
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr13_vgpr14_vgpr15_vgpr16
; GFX9-SDAG-NEXT:    s_nop 3
; GFX9-SDAG-NEXT:    image_sample v[0:3], v[0:1], s[8:15], s[16:19] dmask:0xf
; GFX9-SDAG-NEXT:    s_xor_b64 exec, exec, s[2:3]
; GFX9-SDAG-NEXT:    s_cbranch_execnz .LBB13_1
; GFX9-SDAG-NEXT:  ; %bb.2:
; GFX9-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX9-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    ; return to shader part epilog
;
; GFX9-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_3:
; GFX9-GISEL:       ; %bb.0:
; GFX9-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX9-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v5, v2
; GFX9-GISEL-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX9-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[1:2]
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX9-GISEL-NEXT:    v_add_co_u32_e32 v0, vcc, v2, v0
; GFX9-GISEL-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; GFX9-GISEL-NEXT:    v_addc_co_u32_e32 v1, vcc, v3, v1, vcc
; GFX9-GISEL-NEXT:    v_lshlrev_b64 v[2:3], 4, v[5:6]
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v6, s3
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v5, s2
; GFX9-GISEL-NEXT:    v_add_co_u32_e32 v2, vcc, v5, v2
; GFX9-GISEL-NEXT:    v_addc_co_u32_e32 v3, vcc, v6, v3, vcc
; GFX9-GISEL-NEXT:    global_load_dwordx4 v[5:8], v[0:1], off
; GFX9-GISEL-NEXT:    global_load_dwordx4 v[9:12], v[0:1], off offset:16
; GFX9-GISEL-NEXT:    global_load_dwordx4 v[13:16], v[2:3], off
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v17, s4
; GFX9-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX9-GISEL-NEXT:  .LBB13_1: ; =>This Inner Loop Header: Depth=1
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s2, v17
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s4, v4
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v17
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[4:5], s4, v4
; GFX9-GISEL-NEXT:    s_and_b64 s[2:3], s[2:3], s[4:5]
; GFX9-GISEL-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; GFX9-GISEL-NEXT:    s_mov_b32 s4, 0
; GFX9-GISEL-NEXT:    s_mov_b32 s5, s4
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v0, s4
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(2)
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s8, v5
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s9, v6
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s10, v7
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s11, v8
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(1)
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s12, v9
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s13, v10
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s14, v11
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s15, v12
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s16, v13
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s17, v14
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s18, v15
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s19, v16
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v1, s5
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr17
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr13_vgpr14_vgpr15_vgpr16
; GFX9-GISEL-NEXT:    s_nop 3
; GFX9-GISEL-NEXT:    image_sample v[0:3], v[0:1], s[8:15], s[16:19] dmask:0xf
; GFX9-GISEL-NEXT:    s_xor_b64 exec, exec, s[2:3]
; GFX9-GISEL-NEXT:    s_cbranch_execnz .LBB13_1
; GFX9-GISEL-NEXT:  ; %bb.2:
; GFX9-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX9-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-32-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_3:
; GFX10-32-SDAG:       ; %bb.0:
; GFX10-32-SDAG-NEXT:    s_mov_b32 s4, exec_lo
; GFX10-32-SDAG-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v5, v1
; GFX10-32-SDAG-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-32-SDAG-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; GFX10-32-SDAG-NEXT:    v_lshlrev_b64 v[2:3], 4, v[2:3]
; GFX10-32-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[5:6]
; GFX10-32-SDAG-NEXT:    v_add_co_u32 v0, vcc_lo, s0, v0
; GFX10-32-SDAG-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, s1, v1, vcc_lo
; GFX10-32-SDAG-NEXT:    v_add_co_u32 v2, vcc_lo, s2, v2
; GFX10-32-SDAG-NEXT:    v_add_co_ci_u32_e32 v3, vcc_lo, s3, v3, vcc_lo
; GFX10-32-SDAG-NEXT:    s_clause 0x1
; GFX10-32-SDAG-NEXT:    global_load_dwordx4 v[9:12], v[0:1], off offset:16
; GFX10-32-SDAG-NEXT:    global_load_dwordx4 v[5:8], v[0:1], off
; GFX10-32-SDAG-NEXT:    global_load_dwordx4 v[13:16], v[2:3], off
; GFX10-32-SDAG-NEXT:    s_mov_b32 s1, exec_lo
; GFX10-32-SDAG-NEXT:    s_mov_b32 s0, exec_lo
; GFX10-32-SDAG-NEXT:  .LBB13_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s2, v4
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s2, v4
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(1)
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s8, v5
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s9, v6
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s10, v7
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s11, v8
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s12, v9
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s13, v10
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s14, v11
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s15, v12
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s16, v13
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s17, v14
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s18, v15
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s19, v16
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-32-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-32-SDAG-NEXT:    s_andn2_wrexec_b32 s1, s1
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr13_vgpr14_vgpr15_vgpr16
; GFX10-32-SDAG-NEXT:    s_cbranch_execnz .LBB13_1
; GFX10-32-SDAG-NEXT:  ; %bb.2:
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-SDAG-NEXT:    s_mov_b32 exec_lo, s0
; GFX10-32-SDAG-NEXT:    s_and_b32 exec_lo, exec_lo, s4
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-32-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_3:
; GFX10-32-GISEL:       ; %bb.0:
; GFX10-32-GISEL-NEXT:    s_mov_b32 s5, exec_lo
; GFX10-32-GISEL-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v5, v2
; GFX10-32-GISEL-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v8, s3
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v7, s2
; GFX10-32-GISEL-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; GFX10-32-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[1:2]
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v17, s4
; GFX10-32-GISEL-NEXT:    v_lshlrev_b64 v[5:6], 4, v[5:6]
; GFX10-32-GISEL-NEXT:    s_mov_b32 s1, exec_lo
; GFX10-32-GISEL-NEXT:    s_mov_b32 s0, exec_lo
; GFX10-32-GISEL-NEXT:    v_add_co_u32 v0, vcc_lo, v2, v0
; GFX10-32-GISEL-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, v3, v1, vcc_lo
; GFX10-32-GISEL-NEXT:    v_add_co_u32 v2, vcc_lo, v7, v5
; GFX10-32-GISEL-NEXT:    v_add_co_ci_u32_e32 v3, vcc_lo, v8, v6, vcc_lo
; GFX10-32-GISEL-NEXT:    s_clause 0x1
; GFX10-32-GISEL-NEXT:    global_load_dwordx4 v[5:8], v[0:1], off
; GFX10-32-GISEL-NEXT:    global_load_dwordx4 v[9:12], v[0:1], off offset:16
; GFX10-32-GISEL-NEXT:    global_load_dwordx4 v[13:16], v[2:3], off
; GFX10-32-GISEL-NEXT:  .LBB13_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s2, v17
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s3, v4
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s2, v17
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s3, v4
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(2)
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s8, v5
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s9, v6
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s10, v7
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s11, v8
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(1)
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s12, v9
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s13, v10
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s14, v11
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s15, v12
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s16, v13
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s17, v14
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s18, v15
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s19, v16
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-32-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-32-GISEL-NEXT:    s_andn2_wrexec_b32 s1, s1
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr17
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr13_vgpr14_vgpr15_vgpr16
; GFX10-32-GISEL-NEXT:    s_cbranch_execnz .LBB13_1
; GFX10-32-GISEL-NEXT:  ; %bb.2:
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-GISEL-NEXT:    s_mov_b32 exec_lo, s0
; GFX10-32-GISEL-NEXT:    s_and_b32 exec_lo, exec_lo, s5
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-64-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_3:
; GFX10-64-SDAG:       ; %bb.0:
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX10-64-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v5, v1
; GFX10-64-SDAG-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-64-SDAG-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; GFX10-64-SDAG-NEXT:    v_lshlrev_b64 v[2:3], 4, v[2:3]
; GFX10-64-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[5:6]
; GFX10-64-SDAG-NEXT:    v_add_co_u32 v0, vcc, s0, v0
; GFX10-64-SDAG-NEXT:    v_add_co_ci_u32_e32 v1, vcc, s1, v1, vcc
; GFX10-64-SDAG-NEXT:    v_add_co_u32 v2, vcc, s2, v2
; GFX10-64-SDAG-NEXT:    v_add_co_ci_u32_e32 v3, vcc, s3, v3, vcc
; GFX10-64-SDAG-NEXT:    s_clause 0x1
; GFX10-64-SDAG-NEXT:    global_load_dwordx4 v[9:12], v[0:1], off offset:16
; GFX10-64-SDAG-NEXT:    global_load_dwordx4 v[5:8], v[0:1], off
; GFX10-64-SDAG-NEXT:    global_load_dwordx4 v[13:16], v[2:3], off
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX10-64-SDAG-NEXT:  .LBB13_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s6, v4
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s6, v4
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(1)
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s8, v5
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s9, v6
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s10, v7
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s11, v8
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s12, v9
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s13, v10
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s14, v11
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s15, v12
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s16, v13
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s17, v14
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s18, v15
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s19, v16
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-64-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-64-SDAG-NEXT:    s_andn2_wrexec_b64 s[2:3], s[2:3]
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr13_vgpr14_vgpr15_vgpr16
; GFX10-64-SDAG-NEXT:    s_cbranch_execnz .LBB13_1
; GFX10-64-SDAG-NEXT:  ; %bb.2:
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX10-64-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-64-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_3:
; GFX10-64-GISEL:       ; %bb.0:
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX10-64-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v5, v2
; GFX10-64-GISEL-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v8, s3
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v7, s2
; GFX10-64-GISEL-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; GFX10-64-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[1:2]
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v17, s4
; GFX10-64-GISEL-NEXT:    v_lshlrev_b64 v[5:6], 4, v[5:6]
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX10-64-GISEL-NEXT:    v_add_co_u32 v0, vcc, v2, v0
; GFX10-64-GISEL-NEXT:    v_add_co_ci_u32_e32 v1, vcc, v3, v1, vcc
; GFX10-64-GISEL-NEXT:    v_add_co_u32 v2, vcc, v7, v5
; GFX10-64-GISEL-NEXT:    v_add_co_ci_u32_e32 v3, vcc, v8, v6, vcc
; GFX10-64-GISEL-NEXT:    s_clause 0x1
; GFX10-64-GISEL-NEXT:    global_load_dwordx4 v[5:8], v[0:1], off
; GFX10-64-GISEL-NEXT:    global_load_dwordx4 v[9:12], v[0:1], off offset:16
; GFX10-64-GISEL-NEXT:    global_load_dwordx4 v[13:16], v[2:3], off
; GFX10-64-GISEL-NEXT:  .LBB13_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s4, v17
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s5, v4
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s4, v17
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s5, v4
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(2)
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s8, v5
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s9, v6
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s10, v7
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s11, v8
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(1)
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s12, v9
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s13, v10
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s14, v11
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s15, v12
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s16, v13
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s17, v14
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s18, v15
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s19, v16
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-64-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-64-GISEL-NEXT:    s_andn2_wrexec_b64 s[2:3], s[2:3]
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr17
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr13_vgpr14_vgpr15_vgpr16
; GFX10-64-GISEL-NEXT:    s_cbranch_execnz .LBB13_1
; GFX10-64-GISEL-NEXT:  ; %bb.2:
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX10-64-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:    ; return to shader part epilog
;
; GFX1150-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_3:
; GFX1150-SDAG:       ; %bb.0:
; GFX1150-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX1150-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v5, v1
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX1150-SDAG-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX1150-SDAG-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; GFX1150-SDAG-NEXT:    v_lshlrev_b64 v[2:3], 4, v[2:3]
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX1150-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[5:6]
; GFX1150-SDAG-NEXT:    v_add_co_u32 v0, vcc, s0, v0
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX1150-SDAG-NEXT:    v_add_co_ci_u32_e64 v1, null, s1, v1, vcc
; GFX1150-SDAG-NEXT:    v_add_co_u32 v2, vcc, s2, v2
; GFX1150-SDAG-NEXT:    s_waitcnt_depctr depctr_va_vcc(0)
; GFX1150-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX1150-SDAG-NEXT:    v_add_co_ci_u32_e64 v3, null, s3, v3, vcc
; GFX1150-SDAG-NEXT:    s_clause 0x1
; GFX1150-SDAG-NEXT:    global_load_b128 v[9:12], v[0:1], off offset:16
; GFX1150-SDAG-NEXT:    global_load_b128 v[5:8], v[0:1], off
; GFX1150-SDAG-NEXT:    global_load_b128 v[13:16], v[2:3], off
; GFX1150-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX1150-SDAG-NEXT:  .LBB13_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s6, v4
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s6, v4
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(1)
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s8, v5
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s9, v6
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s10, v7
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s11, v8
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s12, v9
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s13, v10
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s14, v11
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s15, v12
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s16, v13
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s17, v14
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s18, v15
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s19, v16
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX1150-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX1150-SDAG-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr13_vgpr14_vgpr15_vgpr16
; GFX1150-SDAG-NEXT:    s_cbranch_execnz .LBB13_1
; GFX1150-SDAG-NEXT:  ; %bb.2:
; GFX1150-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:    ; return to shader part epilog
;
; GFX1150-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_3:
; GFX1150-GISEL:       ; %bb.0:
; GFX1150-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX1150-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v5, v2
; GFX1150-GISEL-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v8, s3
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v7, s2
; GFX1150-GISEL-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; GFX1150-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[1:2]
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v17, s4
; GFX1150-GISEL-NEXT:    v_lshlrev_b64 v[5:6], 4, v[5:6]
; GFX1150-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX1150-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX1150-GISEL-NEXT:    v_add_co_u32 v0, vcc, v2, v0
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX1150-GISEL-NEXT:    v_add_co_ci_u32_e64 v1, null, v3, v1, vcc
; GFX1150-GISEL-NEXT:    v_add_co_u32 v2, vcc, v7, v5
; GFX1150-GISEL-NEXT:    s_waitcnt_depctr depctr_va_vcc(0)
; GFX1150-GISEL-NEXT:    v_add_co_ci_u32_e64 v3, null, v8, v6, vcc
; GFX1150-GISEL-NEXT:    s_clause 0x1
; GFX1150-GISEL-NEXT:    global_load_b128 v[5:8], v[0:1], off
; GFX1150-GISEL-NEXT:    global_load_b128 v[9:12], v[0:1], off offset:16
; GFX1150-GISEL-NEXT:    global_load_b128 v[13:16], v[2:3], off
; GFX1150-GISEL-NEXT:  .LBB13_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s4, v17
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s5, v4
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s4, v17
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s5, v4
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(2)
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s8, v5
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s9, v6
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s10, v7
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s11, v8
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(1)
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s12, v9
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s13, v10
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s14, v11
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s15, v12
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s16, v13
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s17, v14
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s18, v15
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s19, v16
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX1150-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX1150-GISEL-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr17
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr13_vgpr14_vgpr15_vgpr16
; GFX1150-GISEL-NEXT:    s_cbranch_execnz .LBB13_1
; GFX1150-GISEL-NEXT:  ; %bb.2:
; GFX1150-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    ; return to shader part epilog
;
; GFX12-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_3:
; GFX12-SDAG:       ; %bb.0:
; GFX12-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX12-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v5, v1
; GFX12-SDAG-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX12-SDAG-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; GFX12-SDAG-NEXT:    v_lshlrev_b64_e32 v[2:3], 4, v[2:3]
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX12-SDAG-NEXT:    v_lshlrev_b64_e32 v[0:1], 5, v[5:6]
; GFX12-SDAG-NEXT:    v_add_co_u32 v0, vcc, s0, v0
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX12-SDAG-NEXT:    v_add_co_ci_u32_e64 v1, null, s1, v1, vcc
; GFX12-SDAG-NEXT:    v_add_co_u32 v2, vcc, s2, v2
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_vcc(0)
; GFX12-SDAG-NEXT:    v_add_co_ci_u32_e64 v3, null, s3, v3, vcc
; GFX12-SDAG-NEXT:    s_clause 0x1
; GFX12-SDAG-NEXT:    global_load_b128 v[9:12], v[0:1], off offset:16
; GFX12-SDAG-NEXT:    global_load_b128 v[5:8], v[0:1], off
; GFX12-SDAG-NEXT:    global_load_b128 v[13:16], v[2:3], off
; GFX12-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX12-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX12-SDAG-NEXT:  .LBB13_1: ; =>This Inner Loop Header: Depth=1
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s6, v4
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s6, v4
; GFX12-SDAG-NEXT:    s_wait_loadcnt 0x1
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s8, v5
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s9, v6
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s10, v7
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s11, v8
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s12, v9
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s13, v10
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s14, v11
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s15, v12
; GFX12-SDAG-NEXT:    s_wait_loadcnt 0x0
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s16, v13
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s17, v14
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s18, v15
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s19, v16
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX12-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX12-SDAG-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr13_vgpr14_vgpr15_vgpr16
; GFX12-SDAG-NEXT:    s_cbranch_execnz .LBB13_1
; GFX12-SDAG-NEXT:  ; %bb.2:
; GFX12-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX12-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-SDAG-NEXT:    ; return to shader part epilog
;
; GFX12-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_3:
; GFX12-GISEL:       ; %bb.0:
; GFX12-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX12-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v5, v2
; GFX12-GISEL-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v8, s3
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v7, s2
; GFX12-GISEL-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; GFX12-GISEL-NEXT:    v_lshlrev_b64_e32 v[0:1], 5, v[1:2]
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v17, s4
; GFX12-GISEL-NEXT:    v_lshlrev_b64_e32 v[5:6], 4, v[5:6]
; GFX12-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX12-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX12-GISEL-NEXT:    v_add_co_u32 v0, vcc, v2, v0
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX12-GISEL-NEXT:    v_add_co_ci_u32_e64 v1, null, v3, v1, vcc
; GFX12-GISEL-NEXT:    v_add_co_u32 v2, vcc, v7, v5
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_vcc(0)
; GFX12-GISEL-NEXT:    v_add_co_ci_u32_e64 v3, null, v8, v6, vcc
; GFX12-GISEL-NEXT:    s_clause 0x1
; GFX12-GISEL-NEXT:    global_load_b128 v[5:8], v[0:1], off
; GFX12-GISEL-NEXT:    global_load_b128 v[9:12], v[0:1], off offset:16
; GFX12-GISEL-NEXT:    global_load_b128 v[13:16], v[2:3], off
; GFX12-GISEL-NEXT:  .LBB13_1: ; =>This Inner Loop Header: Depth=1
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s4, v17
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s5, v4
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s4, v17
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s5, v4
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x2
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s8, v5
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s9, v6
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s10, v7
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s11, v8
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x1
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s12, v9
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s13, v10
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s14, v11
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s15, v12
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x0
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s16, v13
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s17, v14
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s18, v15
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s19, v16
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX12-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX12-GISEL-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr17
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr13_vgpr14_vgpr15_vgpr16
; GFX12-GISEL-NEXT:    s_cbranch_execnz .LBB13_1
; GFX12-GISEL-NEXT:  ; %bb.2:
; GFX12-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX12-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-GISEL-NEXT:    ; return to shader part epilog
       <4 x i32> addrspace(4)* inreg %s_in, i32 inreg %idx1, i32 %idx2, i32 %s_idx, i32 %s_idx2) #1 {
  %rptr = getelementptr <8 x i32>, <8 x i32> addrspace(4)* %in, i32 %s_idx
  %sptr = getelementptr <4 x i32>, <4 x i32> addrspace(4)* %s_in, i32 %s_idx2
  %rsrc = load <8 x i32>, <8 x i32> addrspace(4)* %rptr, align 16
  %srsrc = load <4 x i32>, <4 x i32> addrspace(4)* %sptr, align 16
  %tok = call token @llvm.amdgcn.waterfall.begin.i32(token poison, i32 %idx1)
  %tok1 = call token @llvm.amdgcn.waterfall.begin.i32(token %tok, i32 %idx2)
  %s_rsrc = call <8 x i32> @llvm.amdgcn.waterfall.readfirstlane.v8i32.v8i32(token %tok1, <8 x i32> %rsrc)
  %s_srsrc = call <4 x i32> @llvm.amdgcn.waterfall.readfirstlane.v4i32.v4i32(token %tok1, <4 x i32> %srsrc)
  %r = call <4 x float> @llvm.amdgcn.image.sample.2d.v4f32.f32(i32 15, float 0.000000e+00, float 0.000000e+00, <8 x i32> %s_rsrc, <4 x i32> %s_srsrc, i1 false, i32 0, i32 0)
  %r1 = call <4 x float> @llvm.amdgcn.waterfall.end.v4f32(token %tok1, <4 x float> %r)

  ret <4 x float> %r1
}

define amdgpu_ps <4 x float> @test_waterfall_multi_begin_uniform_idx_4(<8 x i32> addrspace(4)* inreg %in,
; VI-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_4:
; VI-SDAG:       ; %bb.0:
; VI-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; VI-SDAG-NEXT:    s_wqm_b64 exec, exec
; VI-SDAG-NEXT:    v_mov_b32_e32 v5, v1
; VI-SDAG-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; VI-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; VI-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[5:6]
; VI-SDAG-NEXT:    v_mov_b32_e32 v3, s1
; VI-SDAG-NEXT:    v_add_u32_e32 v0, vcc, s0, v0
; VI-SDAG-NEXT:    v_addc_u32_e32 v1, vcc, v3, v1, vcc
; VI-SDAG-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; VI-SDAG-NEXT:    v_lshlrev_b64 v[2:3], 4, v[2:3]
; VI-SDAG-NEXT:    v_mov_b32_e32 v5, s3
; VI-SDAG-NEXT:    v_add_u32_e32 v2, vcc, s2, v2
; VI-SDAG-NEXT:    v_addc_u32_e32 v3, vcc, v5, v3, vcc
; VI-SDAG-NEXT:    flat_load_dwordx4 v[5:8], v[0:1]
; VI-SDAG-NEXT:    v_add_u32_e32 v0, vcc, 16, v0
; VI-SDAG-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-SDAG-NEXT:    flat_load_dwordx4 v[9:12], v[0:1]
; VI-SDAG-NEXT:    flat_load_dwordx4 v[13:16], v[2:3]
; VI-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; VI-SDAG-NEXT:  .LBB14_1: ; =>This Inner Loop Header: Depth=1
; VI-SDAG-NEXT:    v_readfirstlane_b32 s2, v4
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v4
; VI-SDAG-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; VI-SDAG-NEXT:    s_waitcnt vmcnt(2)
; VI-SDAG-NEXT:    v_readfirstlane_b32 s8, v5
; VI-SDAG-NEXT:    v_readfirstlane_b32 s9, v6
; VI-SDAG-NEXT:    v_readfirstlane_b32 s10, v7
; VI-SDAG-NEXT:    v_readfirstlane_b32 s11, v8
; VI-SDAG-NEXT:    s_waitcnt vmcnt(1)
; VI-SDAG-NEXT:    v_readfirstlane_b32 s12, v9
; VI-SDAG-NEXT:    v_readfirstlane_b32 s13, v10
; VI-SDAG-NEXT:    v_readfirstlane_b32 s14, v11
; VI-SDAG-NEXT:    v_readfirstlane_b32 s15, v12
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    v_readfirstlane_b32 s16, v13
; VI-SDAG-NEXT:    v_readfirstlane_b32 s17, v14
; VI-SDAG-NEXT:    v_readfirstlane_b32 s18, v15
; VI-SDAG-NEXT:    v_readfirstlane_b32 s19, v16
; VI-SDAG-NEXT:    v_mov_b32_e32 v1, v0
; VI-SDAG-NEXT:    ; implicit-def: $vgpr4
; VI-SDAG-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; VI-SDAG-NEXT:    ; implicit-def: $vgpr13_vgpr14_vgpr15_vgpr16
; VI-SDAG-NEXT:    s_nop 3
; VI-SDAG-NEXT:    image_sample v[0:3], v[0:1], s[8:15], s[16:19] dmask:0xf
; VI-SDAG-NEXT:    s_xor_b64 exec, exec, s[2:3]
; VI-SDAG-NEXT:    s_cbranch_execnz .LBB14_1
; VI-SDAG-NEXT:  ; %bb.2:
; VI-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; VI-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    ; return to shader part epilog
;
; VI-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_4:
; VI-GISEL:       ; %bb.0:
; VI-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; VI-GISEL-NEXT:    s_wqm_b64 exec, exec
; VI-GISEL-NEXT:    v_mov_b32_e32 v5, v2
; VI-GISEL-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; VI-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; VI-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[1:2]
; VI-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; VI-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; VI-GISEL-NEXT:    v_add_u32_e32 v0, vcc, v2, v0
; VI-GISEL-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; VI-GISEL-NEXT:    v_addc_u32_e32 v1, vcc, v3, v1, vcc
; VI-GISEL-NEXT:    v_lshlrev_b64 v[2:3], 4, v[5:6]
; VI-GISEL-NEXT:    v_mov_b32_e32 v6, s3
; VI-GISEL-NEXT:    v_mov_b32_e32 v5, s2
; VI-GISEL-NEXT:    v_add_u32_e32 v2, vcc, v5, v2
; VI-GISEL-NEXT:    v_addc_u32_e32 v3, vcc, v6, v3, vcc
; VI-GISEL-NEXT:    flat_load_dwordx4 v[5:8], v[0:1]
; VI-GISEL-NEXT:    v_add_u32_e32 v0, vcc, 16, v0
; VI-GISEL-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-GISEL-NEXT:    flat_load_dwordx4 v[9:12], v[0:1]
; VI-GISEL-NEXT:    flat_load_dwordx4 v[13:16], v[2:3]
; VI-GISEL-NEXT:    v_mov_b32_e32 v17, s4
; VI-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; VI-GISEL-NEXT:  .LBB14_1: ; =>This Inner Loop Header: Depth=1
; VI-GISEL-NEXT:    v_readfirstlane_b32 s2, v4
; VI-GISEL-NEXT:    v_readfirstlane_b32 s4, v17
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v4
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[4:5], s4, v17
; VI-GISEL-NEXT:    s_and_b64 s[2:3], s[2:3], s[4:5]
; VI-GISEL-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; VI-GISEL-NEXT:    s_mov_b32 s4, 0
; VI-GISEL-NEXT:    s_mov_b32 s5, s4
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    v_mov_b32_e32 v0, s4
; VI-GISEL-NEXT:    s_waitcnt vmcnt(2)
; VI-GISEL-NEXT:    v_readfirstlane_b32 s8, v5
; VI-GISEL-NEXT:    v_readfirstlane_b32 s9, v6
; VI-GISEL-NEXT:    v_readfirstlane_b32 s10, v7
; VI-GISEL-NEXT:    v_readfirstlane_b32 s11, v8
; VI-GISEL-NEXT:    s_waitcnt vmcnt(1)
; VI-GISEL-NEXT:    v_readfirstlane_b32 s12, v9
; VI-GISEL-NEXT:    v_readfirstlane_b32 s13, v10
; VI-GISEL-NEXT:    v_readfirstlane_b32 s14, v11
; VI-GISEL-NEXT:    v_readfirstlane_b32 s15, v12
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    v_readfirstlane_b32 s16, v13
; VI-GISEL-NEXT:    v_readfirstlane_b32 s17, v14
; VI-GISEL-NEXT:    v_readfirstlane_b32 s18, v15
; VI-GISEL-NEXT:    v_readfirstlane_b32 s19, v16
; VI-GISEL-NEXT:    v_mov_b32_e32 v1, s5
; VI-GISEL-NEXT:    ; implicit-def: $vgpr4
; VI-GISEL-NEXT:    ; implicit-def: $vgpr17
; VI-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; VI-GISEL-NEXT:    ; implicit-def: $vgpr13_vgpr14_vgpr15_vgpr16
; VI-GISEL-NEXT:    s_nop 3
; VI-GISEL-NEXT:    image_sample v[0:3], v[0:1], s[8:15], s[16:19] dmask:0xf
; VI-GISEL-NEXT:    s_xor_b64 exec, exec, s[2:3]
; VI-GISEL-NEXT:    s_cbranch_execnz .LBB14_1
; VI-GISEL-NEXT:  ; %bb.2:
; VI-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; VI-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    ; return to shader part epilog
;
; GFX9-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_4:
; GFX9-SDAG:       ; %bb.0:
; GFX9-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX9-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v5, v1
; GFX9-SDAG-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX9-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[5:6]
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v3, s1
; GFX9-SDAG-NEXT:    v_add_co_u32_e32 v0, vcc, s0, v0
; GFX9-SDAG-NEXT:    v_addc_co_u32_e32 v1, vcc, v3, v1, vcc
; GFX9-SDAG-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX9-SDAG-NEXT:    v_lshlrev_b64 v[2:3], 4, v[2:3]
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v5, s3
; GFX9-SDAG-NEXT:    v_add_co_u32_e32 v2, vcc, s2, v2
; GFX9-SDAG-NEXT:    v_addc_co_u32_e32 v3, vcc, v5, v3, vcc
; GFX9-SDAG-NEXT:    global_load_dwordx4 v[9:12], v[0:1], off offset:16
; GFX9-SDAG-NEXT:    global_load_dwordx4 v[5:8], v[0:1], off
; GFX9-SDAG-NEXT:    global_load_dwordx4 v[13:16], v[2:3], off
; GFX9-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX9-SDAG-NEXT:  .LBB14_1: ; =>This Inner Loop Header: Depth=1
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s2, v4
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v4
; GFX9-SDAG-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(1)
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s8, v5
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s9, v6
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s10, v7
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s11, v8
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s12, v9
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s13, v10
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s14, v11
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s15, v12
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s16, v13
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s17, v14
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s18, v15
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s19, v16
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v1, v0
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr13_vgpr14_vgpr15_vgpr16
; GFX9-SDAG-NEXT:    s_nop 3
; GFX9-SDAG-NEXT:    image_sample v[0:3], v[0:1], s[8:15], s[16:19] dmask:0xf
; GFX9-SDAG-NEXT:    s_xor_b64 exec, exec, s[2:3]
; GFX9-SDAG-NEXT:    s_cbranch_execnz .LBB14_1
; GFX9-SDAG-NEXT:  ; %bb.2:
; GFX9-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX9-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    ; return to shader part epilog
;
; GFX9-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_4:
; GFX9-GISEL:       ; %bb.0:
; GFX9-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX9-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v5, v2
; GFX9-GISEL-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX9-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[1:2]
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX9-GISEL-NEXT:    v_add_co_u32_e32 v0, vcc, v2, v0
; GFX9-GISEL-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; GFX9-GISEL-NEXT:    v_addc_co_u32_e32 v1, vcc, v3, v1, vcc
; GFX9-GISEL-NEXT:    v_lshlrev_b64 v[2:3], 4, v[5:6]
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v6, s3
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v5, s2
; GFX9-GISEL-NEXT:    v_add_co_u32_e32 v2, vcc, v5, v2
; GFX9-GISEL-NEXT:    v_addc_co_u32_e32 v3, vcc, v6, v3, vcc
; GFX9-GISEL-NEXT:    global_load_dwordx4 v[5:8], v[0:1], off
; GFX9-GISEL-NEXT:    global_load_dwordx4 v[9:12], v[0:1], off offset:16
; GFX9-GISEL-NEXT:    global_load_dwordx4 v[13:16], v[2:3], off
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v17, s4
; GFX9-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX9-GISEL-NEXT:  .LBB14_1: ; =>This Inner Loop Header: Depth=1
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s2, v4
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s4, v17
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v4
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[4:5], s4, v17
; GFX9-GISEL-NEXT:    s_and_b64 s[2:3], s[2:3], s[4:5]
; GFX9-GISEL-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; GFX9-GISEL-NEXT:    s_mov_b32 s4, 0
; GFX9-GISEL-NEXT:    s_mov_b32 s5, s4
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v0, s4
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(2)
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s8, v5
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s9, v6
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s10, v7
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s11, v8
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(1)
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s12, v9
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s13, v10
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s14, v11
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s15, v12
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s16, v13
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s17, v14
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s18, v15
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s19, v16
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v1, s5
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr17
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr13_vgpr14_vgpr15_vgpr16
; GFX9-GISEL-NEXT:    s_nop 3
; GFX9-GISEL-NEXT:    image_sample v[0:3], v[0:1], s[8:15], s[16:19] dmask:0xf
; GFX9-GISEL-NEXT:    s_xor_b64 exec, exec, s[2:3]
; GFX9-GISEL-NEXT:    s_cbranch_execnz .LBB14_1
; GFX9-GISEL-NEXT:  ; %bb.2:
; GFX9-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX9-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-32-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_4:
; GFX10-32-SDAG:       ; %bb.0:
; GFX10-32-SDAG-NEXT:    s_mov_b32 s4, exec_lo
; GFX10-32-SDAG-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v5, v1
; GFX10-32-SDAG-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-32-SDAG-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; GFX10-32-SDAG-NEXT:    v_lshlrev_b64 v[2:3], 4, v[2:3]
; GFX10-32-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[5:6]
; GFX10-32-SDAG-NEXT:    v_add_co_u32 v0, vcc_lo, s0, v0
; GFX10-32-SDAG-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, s1, v1, vcc_lo
; GFX10-32-SDAG-NEXT:    v_add_co_u32 v2, vcc_lo, s2, v2
; GFX10-32-SDAG-NEXT:    v_add_co_ci_u32_e32 v3, vcc_lo, s3, v3, vcc_lo
; GFX10-32-SDAG-NEXT:    s_clause 0x1
; GFX10-32-SDAG-NEXT:    global_load_dwordx4 v[9:12], v[0:1], off offset:16
; GFX10-32-SDAG-NEXT:    global_load_dwordx4 v[5:8], v[0:1], off
; GFX10-32-SDAG-NEXT:    global_load_dwordx4 v[13:16], v[2:3], off
; GFX10-32-SDAG-NEXT:    s_mov_b32 s1, exec_lo
; GFX10-32-SDAG-NEXT:    s_mov_b32 s0, exec_lo
; GFX10-32-SDAG-NEXT:  .LBB14_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s2, v4
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s2, v4
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(1)
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s8, v5
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s9, v6
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s10, v7
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s11, v8
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s12, v9
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s13, v10
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s14, v11
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s15, v12
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s16, v13
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s17, v14
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s18, v15
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s19, v16
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-32-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-32-SDAG-NEXT:    s_andn2_wrexec_b32 s1, s1
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr13_vgpr14_vgpr15_vgpr16
; GFX10-32-SDAG-NEXT:    s_cbranch_execnz .LBB14_1
; GFX10-32-SDAG-NEXT:  ; %bb.2:
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-SDAG-NEXT:    s_mov_b32 exec_lo, s0
; GFX10-32-SDAG-NEXT:    s_and_b32 exec_lo, exec_lo, s4
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-32-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_4:
; GFX10-32-GISEL:       ; %bb.0:
; GFX10-32-GISEL-NEXT:    s_mov_b32 s5, exec_lo
; GFX10-32-GISEL-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v5, v2
; GFX10-32-GISEL-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v8, s3
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v7, s2
; GFX10-32-GISEL-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; GFX10-32-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[1:2]
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v17, s4
; GFX10-32-GISEL-NEXT:    v_lshlrev_b64 v[5:6], 4, v[5:6]
; GFX10-32-GISEL-NEXT:    s_mov_b32 s1, exec_lo
; GFX10-32-GISEL-NEXT:    s_mov_b32 s0, exec_lo
; GFX10-32-GISEL-NEXT:    v_add_co_u32 v0, vcc_lo, v2, v0
; GFX10-32-GISEL-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, v3, v1, vcc_lo
; GFX10-32-GISEL-NEXT:    v_add_co_u32 v2, vcc_lo, v7, v5
; GFX10-32-GISEL-NEXT:    v_add_co_ci_u32_e32 v3, vcc_lo, v8, v6, vcc_lo
; GFX10-32-GISEL-NEXT:    s_clause 0x1
; GFX10-32-GISEL-NEXT:    global_load_dwordx4 v[5:8], v[0:1], off
; GFX10-32-GISEL-NEXT:    global_load_dwordx4 v[9:12], v[0:1], off offset:16
; GFX10-32-GISEL-NEXT:    global_load_dwordx4 v[13:16], v[2:3], off
; GFX10-32-GISEL-NEXT:  .LBB14_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s2, v4
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s3, v17
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s2, v4
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s3, v17
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(2)
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s8, v5
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s9, v6
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s10, v7
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s11, v8
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(1)
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s12, v9
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s13, v10
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s14, v11
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s15, v12
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s16, v13
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s17, v14
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s18, v15
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s19, v16
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-32-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-32-GISEL-NEXT:    s_andn2_wrexec_b32 s1, s1
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr17
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr13_vgpr14_vgpr15_vgpr16
; GFX10-32-GISEL-NEXT:    s_cbranch_execnz .LBB14_1
; GFX10-32-GISEL-NEXT:  ; %bb.2:
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-GISEL-NEXT:    s_mov_b32 exec_lo, s0
; GFX10-32-GISEL-NEXT:    s_and_b32 exec_lo, exec_lo, s5
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-64-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_4:
; GFX10-64-SDAG:       ; %bb.0:
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX10-64-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v5, v1
; GFX10-64-SDAG-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-64-SDAG-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; GFX10-64-SDAG-NEXT:    v_lshlrev_b64 v[2:3], 4, v[2:3]
; GFX10-64-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[5:6]
; GFX10-64-SDAG-NEXT:    v_add_co_u32 v0, vcc, s0, v0
; GFX10-64-SDAG-NEXT:    v_add_co_ci_u32_e32 v1, vcc, s1, v1, vcc
; GFX10-64-SDAG-NEXT:    v_add_co_u32 v2, vcc, s2, v2
; GFX10-64-SDAG-NEXT:    v_add_co_ci_u32_e32 v3, vcc, s3, v3, vcc
; GFX10-64-SDAG-NEXT:    s_clause 0x1
; GFX10-64-SDAG-NEXT:    global_load_dwordx4 v[9:12], v[0:1], off offset:16
; GFX10-64-SDAG-NEXT:    global_load_dwordx4 v[5:8], v[0:1], off
; GFX10-64-SDAG-NEXT:    global_load_dwordx4 v[13:16], v[2:3], off
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX10-64-SDAG-NEXT:  .LBB14_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s6, v4
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s6, v4
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(1)
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s8, v5
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s9, v6
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s10, v7
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s11, v8
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s12, v9
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s13, v10
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s14, v11
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s15, v12
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s16, v13
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s17, v14
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s18, v15
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s19, v16
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-64-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-64-SDAG-NEXT:    s_andn2_wrexec_b64 s[2:3], s[2:3]
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr13_vgpr14_vgpr15_vgpr16
; GFX10-64-SDAG-NEXT:    s_cbranch_execnz .LBB14_1
; GFX10-64-SDAG-NEXT:  ; %bb.2:
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX10-64-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-64-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_4:
; GFX10-64-GISEL:       ; %bb.0:
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX10-64-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v5, v2
; GFX10-64-GISEL-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v8, s3
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v7, s2
; GFX10-64-GISEL-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; GFX10-64-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[1:2]
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v17, s4
; GFX10-64-GISEL-NEXT:    v_lshlrev_b64 v[5:6], 4, v[5:6]
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX10-64-GISEL-NEXT:    v_add_co_u32 v0, vcc, v2, v0
; GFX10-64-GISEL-NEXT:    v_add_co_ci_u32_e32 v1, vcc, v3, v1, vcc
; GFX10-64-GISEL-NEXT:    v_add_co_u32 v2, vcc, v7, v5
; GFX10-64-GISEL-NEXT:    v_add_co_ci_u32_e32 v3, vcc, v8, v6, vcc
; GFX10-64-GISEL-NEXT:    s_clause 0x1
; GFX10-64-GISEL-NEXT:    global_load_dwordx4 v[5:8], v[0:1], off
; GFX10-64-GISEL-NEXT:    global_load_dwordx4 v[9:12], v[0:1], off offset:16
; GFX10-64-GISEL-NEXT:    global_load_dwordx4 v[13:16], v[2:3], off
; GFX10-64-GISEL-NEXT:  .LBB14_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s4, v4
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s5, v17
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s4, v4
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s5, v17
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(2)
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s8, v5
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s9, v6
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s10, v7
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s11, v8
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(1)
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s12, v9
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s13, v10
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s14, v11
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s15, v12
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s16, v13
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s17, v14
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s18, v15
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s19, v16
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-64-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-64-GISEL-NEXT:    s_andn2_wrexec_b64 s[2:3], s[2:3]
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr17
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr13_vgpr14_vgpr15_vgpr16
; GFX10-64-GISEL-NEXT:    s_cbranch_execnz .LBB14_1
; GFX10-64-GISEL-NEXT:  ; %bb.2:
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX10-64-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:    ; return to shader part epilog
;
; GFX1150-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_4:
; GFX1150-SDAG:       ; %bb.0:
; GFX1150-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX1150-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v5, v1
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX1150-SDAG-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX1150-SDAG-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; GFX1150-SDAG-NEXT:    v_lshlrev_b64 v[2:3], 4, v[2:3]
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX1150-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[5:6]
; GFX1150-SDAG-NEXT:    v_add_co_u32 v0, vcc, s0, v0
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX1150-SDAG-NEXT:    v_add_co_ci_u32_e64 v1, null, s1, v1, vcc
; GFX1150-SDAG-NEXT:    v_add_co_u32 v2, vcc, s2, v2
; GFX1150-SDAG-NEXT:    s_waitcnt_depctr depctr_va_vcc(0)
; GFX1150-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX1150-SDAG-NEXT:    v_add_co_ci_u32_e64 v3, null, s3, v3, vcc
; GFX1150-SDAG-NEXT:    s_clause 0x1
; GFX1150-SDAG-NEXT:    global_load_b128 v[9:12], v[0:1], off offset:16
; GFX1150-SDAG-NEXT:    global_load_b128 v[5:8], v[0:1], off
; GFX1150-SDAG-NEXT:    global_load_b128 v[13:16], v[2:3], off
; GFX1150-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX1150-SDAG-NEXT:  .LBB14_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s6, v4
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s6, v4
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(1)
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s8, v5
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s9, v6
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s10, v7
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s11, v8
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s12, v9
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s13, v10
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s14, v11
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s15, v12
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s16, v13
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s17, v14
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s18, v15
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s19, v16
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX1150-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX1150-SDAG-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr13_vgpr14_vgpr15_vgpr16
; GFX1150-SDAG-NEXT:    s_cbranch_execnz .LBB14_1
; GFX1150-SDAG-NEXT:  ; %bb.2:
; GFX1150-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:    ; return to shader part epilog
;
; GFX1150-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_4:
; GFX1150-GISEL:       ; %bb.0:
; GFX1150-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX1150-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v5, v2
; GFX1150-GISEL-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v8, s3
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v7, s2
; GFX1150-GISEL-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; GFX1150-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[1:2]
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v17, s4
; GFX1150-GISEL-NEXT:    v_lshlrev_b64 v[5:6], 4, v[5:6]
; GFX1150-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX1150-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX1150-GISEL-NEXT:    v_add_co_u32 v0, vcc, v2, v0
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX1150-GISEL-NEXT:    v_add_co_ci_u32_e64 v1, null, v3, v1, vcc
; GFX1150-GISEL-NEXT:    v_add_co_u32 v2, vcc, v7, v5
; GFX1150-GISEL-NEXT:    s_waitcnt_depctr depctr_va_vcc(0)
; GFX1150-GISEL-NEXT:    v_add_co_ci_u32_e64 v3, null, v8, v6, vcc
; GFX1150-GISEL-NEXT:    s_clause 0x1
; GFX1150-GISEL-NEXT:    global_load_b128 v[5:8], v[0:1], off
; GFX1150-GISEL-NEXT:    global_load_b128 v[9:12], v[0:1], off offset:16
; GFX1150-GISEL-NEXT:    global_load_b128 v[13:16], v[2:3], off
; GFX1150-GISEL-NEXT:  .LBB14_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s4, v4
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s5, v17
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s4, v4
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s5, v17
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(2)
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s8, v5
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s9, v6
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s10, v7
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s11, v8
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(1)
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s12, v9
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s13, v10
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s14, v11
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s15, v12
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s16, v13
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s17, v14
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s18, v15
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s19, v16
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX1150-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX1150-GISEL-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr17
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr13_vgpr14_vgpr15_vgpr16
; GFX1150-GISEL-NEXT:    s_cbranch_execnz .LBB14_1
; GFX1150-GISEL-NEXT:  ; %bb.2:
; GFX1150-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    ; return to shader part epilog
;
; GFX12-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_4:
; GFX12-SDAG:       ; %bb.0:
; GFX12-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX12-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v5, v1
; GFX12-SDAG-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_3) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX12-SDAG-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; GFX12-SDAG-NEXT:    v_lshlrev_b64_e32 v[2:3], 4, v[2:3]
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX12-SDAG-NEXT:    v_lshlrev_b64_e32 v[0:1], 5, v[5:6]
; GFX12-SDAG-NEXT:    v_add_co_u32 v0, vcc, s0, v0
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX12-SDAG-NEXT:    v_add_co_ci_u32_e64 v1, null, s1, v1, vcc
; GFX12-SDAG-NEXT:    v_add_co_u32 v2, vcc, s2, v2
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_vcc(0)
; GFX12-SDAG-NEXT:    v_add_co_ci_u32_e64 v3, null, s3, v3, vcc
; GFX12-SDAG-NEXT:    s_clause 0x1
; GFX12-SDAG-NEXT:    global_load_b128 v[9:12], v[0:1], off offset:16
; GFX12-SDAG-NEXT:    global_load_b128 v[5:8], v[0:1], off
; GFX12-SDAG-NEXT:    global_load_b128 v[13:16], v[2:3], off
; GFX12-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX12-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX12-SDAG-NEXT:  .LBB14_1: ; =>This Inner Loop Header: Depth=1
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s6, v4
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s6, v4
; GFX12-SDAG-NEXT:    s_wait_loadcnt 0x1
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s8, v5
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s9, v6
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s10, v7
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s11, v8
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s12, v9
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s13, v10
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s14, v11
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s15, v12
; GFX12-SDAG-NEXT:    s_wait_loadcnt 0x0
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s16, v13
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s17, v14
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s18, v15
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s19, v16
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX12-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX12-SDAG-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr4
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr13_vgpr14_vgpr15_vgpr16
; GFX12-SDAG-NEXT:    s_cbranch_execnz .LBB14_1
; GFX12-SDAG-NEXT:  ; %bb.2:
; GFX12-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX12-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-SDAG-NEXT:    ; return to shader part epilog
;
; GFX12-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_4:
; GFX12-GISEL:       ; %bb.0:
; GFX12-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX12-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v5, v2
; GFX12-GISEL-NEXT:    v_ashrrev_i32_e32 v2, 31, v1
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v8, s3
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v7, s2
; GFX12-GISEL-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; GFX12-GISEL-NEXT:    v_lshlrev_b64_e32 v[0:1], 5, v[1:2]
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v17, s4
; GFX12-GISEL-NEXT:    v_lshlrev_b64_e32 v[5:6], 4, v[5:6]
; GFX12-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX12-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX12-GISEL-NEXT:    v_add_co_u32 v0, vcc, v2, v0
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX12-GISEL-NEXT:    v_add_co_ci_u32_e64 v1, null, v3, v1, vcc
; GFX12-GISEL-NEXT:    v_add_co_u32 v2, vcc, v7, v5
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_vcc(0)
; GFX12-GISEL-NEXT:    v_add_co_ci_u32_e64 v3, null, v8, v6, vcc
; GFX12-GISEL-NEXT:    s_clause 0x1
; GFX12-GISEL-NEXT:    global_load_b128 v[5:8], v[0:1], off
; GFX12-GISEL-NEXT:    global_load_b128 v[9:12], v[0:1], off offset:16
; GFX12-GISEL-NEXT:    global_load_b128 v[13:16], v[2:3], off
; GFX12-GISEL-NEXT:  .LBB14_1: ; =>This Inner Loop Header: Depth=1
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s4, v4
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s5, v17
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s4, v4
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s5, v17
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x2
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s8, v5
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s9, v6
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s10, v7
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s11, v8
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x1
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s12, v9
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s13, v10
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s14, v11
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s15, v12
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x0
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s16, v13
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s17, v14
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s18, v15
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s19, v16
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX12-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX12-GISEL-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr17
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8_vgpr9_vgpr10_vgpr11_vgpr12
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr13_vgpr14_vgpr15_vgpr16
; GFX12-GISEL-NEXT:    s_cbranch_execnz .LBB14_1
; GFX12-GISEL-NEXT:  ; %bb.2:
; GFX12-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX12-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-GISEL-NEXT:    ; return to shader part epilog
       <4 x i32> addrspace(4)* inreg %s_in, i32 %idx1, i32 inreg %idx2, i32 %s_idx, i32 %s_idx2) #1 {
  %rptr = getelementptr <8 x i32>, <8 x i32> addrspace(4)* %in, i32 %s_idx
  %sptr = getelementptr <4 x i32>, <4 x i32> addrspace(4)* %s_in, i32 %s_idx2
  %rsrc = load <8 x i32>, <8 x i32> addrspace(4)* %rptr, align 16
  %srsrc = load <4 x i32>, <4 x i32> addrspace(4)* %sptr, align 16
  %tok = call token @llvm.amdgcn.waterfall.begin.i32(token poison, i32 %idx1)
  %tok1 = call token @llvm.amdgcn.waterfall.begin.i32(token %tok, i32 %idx2)
  %s_rsrc = call <8 x i32> @llvm.amdgcn.waterfall.readfirstlane.v8i32.v8i32(token %tok1, <8 x i32> %rsrc)
  %s_srsrc = call <4 x i32> @llvm.amdgcn.waterfall.readfirstlane.v4i32.v4i32(token %tok1, <4 x i32> %srsrc)
  %r = call <4 x float> @llvm.amdgcn.image.sample.2d.v4f32.f32(i32 15, float 0.000000e+00, float 0.000000e+00, <8 x i32> %s_rsrc, <4 x i32> %s_srsrc, i1 false, i32 0, i32 0)
  %r1 = call <4 x float> @llvm.amdgcn.waterfall.end.v4f32(token %tok1, <4 x float> %r)

  ret <4 x float> %r1
}

define amdgpu_ps {<4 x float>,<4 x float>} @test_waterfall_multi_begin_uniform_idx_1_2loops(
; VI-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_1_2loops:
; VI-SDAG:       ; %bb.0:
; VI-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; VI-SDAG-NEXT:    s_wqm_b64 exec, exec
; VI-SDAG-NEXT:    v_mov_b32_e32 v7, v2
; VI-SDAG-NEXT:    v_ashrrev_i32_e32 v8, 31, v7
; VI-SDAG-NEXT:    v_mov_b32_e32 v6, v1
; VI-SDAG-NEXT:    v_mov_b32_e32 v5, v0
; VI-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[7:8]
; VI-SDAG-NEXT:    v_mov_b32_e32 v2, s1
; VI-SDAG-NEXT:    v_add_u32_e32 v0, vcc, s0, v0
; VI-SDAG-NEXT:    v_ashrrev_i32_e32 v4, 31, v3
; VI-SDAG-NEXT:    v_addc_u32_e32 v1, vcc, v2, v1, vcc
; VI-SDAG-NEXT:    v_lshlrev_b64 v[2:3], 4, v[3:4]
; VI-SDAG-NEXT:    v_mov_b32_e32 v4, s3
; VI-SDAG-NEXT:    v_add_u32_e32 v2, vcc, s2, v2
; VI-SDAG-NEXT:    v_addc_u32_e32 v3, vcc, v4, v3, vcc
; VI-SDAG-NEXT:    flat_load_dwordx4 v[11:14], v[0:1]
; VI-SDAG-NEXT:    v_add_u32_e32 v0, vcc, 16, v0
; VI-SDAG-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-SDAG-NEXT:    flat_load_dwordx4 v[15:18], v[0:1]
; VI-SDAG-NEXT:    flat_load_dwordx4 v[7:10], v[2:3]
; VI-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:  .LBB15_1: ; =>This Inner Loop Header: Depth=1
; VI-SDAG-NEXT:    v_readfirstlane_b32 s2, v5
; VI-SDAG-NEXT:    v_readfirstlane_b32 s6, v6
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v5
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[6:7], s6, v6
; VI-SDAG-NEXT:    s_and_b64 s[2:3], s[2:3], s[6:7]
; VI-SDAG-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; VI-SDAG-NEXT:    s_mov_b32 s6, 0
; VI-SDAG-NEXT:    s_mov_b32 s7, s6
; VI-SDAG-NEXT:    v_mov_b32_e32 v20, s7
; VI-SDAG-NEXT:    v_readfirstlane_b32 s8, v11
; VI-SDAG-NEXT:    v_readfirstlane_b32 s9, v12
; VI-SDAG-NEXT:    v_readfirstlane_b32 s10, v13
; VI-SDAG-NEXT:    v_readfirstlane_b32 s11, v14
; VI-SDAG-NEXT:    v_readfirstlane_b32 s12, v15
; VI-SDAG-NEXT:    v_readfirstlane_b32 s13, v16
; VI-SDAG-NEXT:    v_readfirstlane_b32 s14, v17
; VI-SDAG-NEXT:    v_readfirstlane_b32 s15, v18
; VI-SDAG-NEXT:    v_readfirstlane_b32 s16, v7
; VI-SDAG-NEXT:    v_readfirstlane_b32 s17, v8
; VI-SDAG-NEXT:    v_readfirstlane_b32 s18, v9
; VI-SDAG-NEXT:    v_readfirstlane_b32 s19, v10
; VI-SDAG-NEXT:    v_mov_b32_e32 v19, s6
; VI-SDAG-NEXT:    ; implicit-def: $vgpr5
; VI-SDAG-NEXT:    ; implicit-def: $vgpr6
; VI-SDAG-NEXT:    s_nop 3
; VI-SDAG-NEXT:    image_sample v[0:3], v[19:20], s[8:15], s[16:19] dmask:0xf
; VI-SDAG-NEXT:    s_xor_b64 exec, exec, s[2:3]
; VI-SDAG-NEXT:    s_cbranch_execnz .LBB15_1
; VI-SDAG-NEXT:  ; %bb.2:
; VI-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; VI-SDAG-NEXT:    v_readfirstlane_b32 s8, v11
; VI-SDAG-NEXT:    v_readfirstlane_b32 s9, v12
; VI-SDAG-NEXT:    v_readfirstlane_b32 s10, v13
; VI-SDAG-NEXT:    v_readfirstlane_b32 s11, v14
; VI-SDAG-NEXT:    v_readfirstlane_b32 s12, v15
; VI-SDAG-NEXT:    v_readfirstlane_b32 s13, v16
; VI-SDAG-NEXT:    v_readfirstlane_b32 s14, v17
; VI-SDAG-NEXT:    v_readfirstlane_b32 s15, v18
; VI-SDAG-NEXT:    v_readfirstlane_b32 s0, v7
; VI-SDAG-NEXT:    v_readfirstlane_b32 s1, v8
; VI-SDAG-NEXT:    v_readfirstlane_b32 s2, v9
; VI-SDAG-NEXT:    v_readfirstlane_b32 s3, v10
; VI-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; VI-SDAG-NEXT:    s_nop 3
; VI-SDAG-NEXT:    image_sample v[4:7], v[19:20], s[8:15], s[0:3] dmask:0xf
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    ; return to shader part epilog
;
; VI-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_1_2loops:
; VI-GISEL:       ; %bb.0:
; VI-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; VI-GISEL-NEXT:    s_wqm_b64 exec, exec
; VI-GISEL-NEXT:    v_mov_b32_e32 v6, v3
; VI-GISEL-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; VI-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; VI-GISEL-NEXT:    v_mov_b32_e32 v5, v1
; VI-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[2:3]
; VI-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; VI-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; VI-GISEL-NEXT:    v_add_u32_e32 v0, vcc, v2, v0
; VI-GISEL-NEXT:    v_ashrrev_i32_e32 v7, 31, v6
; VI-GISEL-NEXT:    v_addc_u32_e32 v1, vcc, v3, v1, vcc
; VI-GISEL-NEXT:    v_lshlrev_b64 v[2:3], 4, v[6:7]
; VI-GISEL-NEXT:    v_mov_b32_e32 v7, s3
; VI-GISEL-NEXT:    v_mov_b32_e32 v6, s2
; VI-GISEL-NEXT:    v_add_u32_e32 v2, vcc, v6, v2
; VI-GISEL-NEXT:    v_addc_u32_e32 v3, vcc, v7, v3, vcc
; VI-GISEL-NEXT:    flat_load_dwordx4 v[8:11], v[0:1]
; VI-GISEL-NEXT:    v_add_u32_e32 v0, vcc, 16, v0
; VI-GISEL-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-GISEL-NEXT:    flat_load_dwordx4 v[12:15], v[0:1]
; VI-GISEL-NEXT:    flat_load_dwordx4 v[16:19], v[2:3]
; VI-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; VI-GISEL-NEXT:    s_mov_b32 s20, 0
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:  .LBB15_1: ; =>This Inner Loop Header: Depth=1
; VI-GISEL-NEXT:    v_readfirstlane_b32 s2, v4
; VI-GISEL-NEXT:    v_readfirstlane_b32 s8, v5
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v4
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[8:9], s8, v5
; VI-GISEL-NEXT:    s_and_b64 s[2:3], s[2:3], s[8:9]
; VI-GISEL-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; VI-GISEL-NEXT:    s_mov_b32 s21, s20
; VI-GISEL-NEXT:    v_mov_b32_e32 v20, s20
; VI-GISEL-NEXT:    v_readfirstlane_b32 s8, v8
; VI-GISEL-NEXT:    v_readfirstlane_b32 s9, v9
; VI-GISEL-NEXT:    v_readfirstlane_b32 s10, v10
; VI-GISEL-NEXT:    v_readfirstlane_b32 s11, v11
; VI-GISEL-NEXT:    v_readfirstlane_b32 s12, v12
; VI-GISEL-NEXT:    v_readfirstlane_b32 s13, v13
; VI-GISEL-NEXT:    v_readfirstlane_b32 s14, v14
; VI-GISEL-NEXT:    v_readfirstlane_b32 s15, v15
; VI-GISEL-NEXT:    v_readfirstlane_b32 s16, v16
; VI-GISEL-NEXT:    v_readfirstlane_b32 s17, v17
; VI-GISEL-NEXT:    v_readfirstlane_b32 s18, v18
; VI-GISEL-NEXT:    v_readfirstlane_b32 s19, v19
; VI-GISEL-NEXT:    v_mov_b32_e32 v21, s21
; VI-GISEL-NEXT:    ; implicit-def: $vgpr4
; VI-GISEL-NEXT:    ; implicit-def: $vgpr5
; VI-GISEL-NEXT:    s_nop 3
; VI-GISEL-NEXT:    image_sample v[0:3], v[20:21], s[8:15], s[16:19] dmask:0xf
; VI-GISEL-NEXT:    s_xor_b64 exec, exec, s[2:3]
; VI-GISEL-NEXT:    s_cbranch_execnz .LBB15_1
; VI-GISEL-NEXT:  ; %bb.2:
; VI-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; VI-GISEL-NEXT:    v_mov_b32_e32 v22, s4
; VI-GISEL-NEXT:    v_mov_b32_e32 v23, s5
; VI-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; VI-GISEL-NEXT:  .LBB15_3: ; =>This Inner Loop Header: Depth=1
; VI-GISEL-NEXT:    v_readfirstlane_b32 s2, v22
; VI-GISEL-NEXT:    v_readfirstlane_b32 s4, v23
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v22
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[4:5], s4, v23
; VI-GISEL-NEXT:    s_and_b64 s[2:3], s[2:3], s[4:5]
; VI-GISEL-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; VI-GISEL-NEXT:    v_readfirstlane_b32 s8, v8
; VI-GISEL-NEXT:    v_readfirstlane_b32 s9, v9
; VI-GISEL-NEXT:    v_readfirstlane_b32 s10, v10
; VI-GISEL-NEXT:    v_readfirstlane_b32 s11, v11
; VI-GISEL-NEXT:    v_readfirstlane_b32 s12, v12
; VI-GISEL-NEXT:    v_readfirstlane_b32 s13, v13
; VI-GISEL-NEXT:    v_readfirstlane_b32 s14, v14
; VI-GISEL-NEXT:    v_readfirstlane_b32 s15, v15
; VI-GISEL-NEXT:    v_readfirstlane_b32 s16, v16
; VI-GISEL-NEXT:    v_readfirstlane_b32 s17, v17
; VI-GISEL-NEXT:    v_readfirstlane_b32 s18, v18
; VI-GISEL-NEXT:    v_readfirstlane_b32 s19, v19
; VI-GISEL-NEXT:    ; implicit-def: $vgpr22
; VI-GISEL-NEXT:    ; implicit-def: $vgpr23
; VI-GISEL-NEXT:    ; implicit-def: $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
; VI-GISEL-NEXT:    ; implicit-def: $vgpr16_vgpr17_vgpr18_vgpr19
; VI-GISEL-NEXT:    s_nop 4
; VI-GISEL-NEXT:    image_sample v[4:7], v[20:21], s[8:15], s[16:19] dmask:0xf
; VI-GISEL-NEXT:    ; implicit-def: $vgpr20_vgpr21
; VI-GISEL-NEXT:    s_xor_b64 exec, exec, s[2:3]
; VI-GISEL-NEXT:    s_cbranch_execnz .LBB15_3
; VI-GISEL-NEXT:  ; %bb.4:
; VI-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; VI-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    ; return to shader part epilog
;
; GFX9-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_1_2loops:
; GFX9-SDAG:       ; %bb.0:
; GFX9-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX9-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v7, v2
; GFX9-SDAG-NEXT:    v_ashrrev_i32_e32 v8, 31, v7
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v6, v1
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v5, v0
; GFX9-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[7:8]
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v2, s1
; GFX9-SDAG-NEXT:    v_add_co_u32_e32 v0, vcc, s0, v0
; GFX9-SDAG-NEXT:    v_ashrrev_i32_e32 v4, 31, v3
; GFX9-SDAG-NEXT:    v_addc_co_u32_e32 v1, vcc, v2, v1, vcc
; GFX9-SDAG-NEXT:    v_lshlrev_b64 v[2:3], 4, v[3:4]
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v4, s3
; GFX9-SDAG-NEXT:    v_add_co_u32_e32 v2, vcc, s2, v2
; GFX9-SDAG-NEXT:    v_addc_co_u32_e32 v3, vcc, v4, v3, vcc
; GFX9-SDAG-NEXT:    global_load_dwordx4 v[11:14], v[0:1], off offset:16
; GFX9-SDAG-NEXT:    global_load_dwordx4 v[15:18], v[0:1], off
; GFX9-SDAG-NEXT:    global_load_dwordx4 v[7:10], v[2:3], off
; GFX9-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:  .LBB15_1: ; =>This Inner Loop Header: Depth=1
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s2, v5
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s6, v6
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v5
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[6:7], s6, v6
; GFX9-SDAG-NEXT:    s_and_b64 s[2:3], s[2:3], s[6:7]
; GFX9-SDAG-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; GFX9-SDAG-NEXT:    s_mov_b32 s6, 0
; GFX9-SDAG-NEXT:    s_mov_b32 s7, s6
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v20, s7
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s8, v15
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s9, v16
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s10, v17
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s11, v18
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s12, v11
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s13, v12
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s14, v13
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s15, v14
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s16, v7
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s17, v8
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s18, v9
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s19, v10
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v19, s6
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr6
; GFX9-SDAG-NEXT:    s_nop 3
; GFX9-SDAG-NEXT:    image_sample v[0:3], v[19:20], s[8:15], s[16:19] dmask:0xf
; GFX9-SDAG-NEXT:    s_xor_b64 exec, exec, s[2:3]
; GFX9-SDAG-NEXT:    s_cbranch_execnz .LBB15_1
; GFX9-SDAG-NEXT:  ; %bb.2:
; GFX9-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s8, v15
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s9, v16
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s10, v17
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s11, v18
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s12, v11
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s13, v12
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s14, v13
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s15, v14
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s0, v7
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s1, v8
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s2, v9
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s3, v10
; GFX9-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX9-SDAG-NEXT:    s_nop 3
; GFX9-SDAG-NEXT:    image_sample v[4:7], v[19:20], s[8:15], s[0:3] dmask:0xf
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    ; return to shader part epilog
;
; GFX9-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_1_2loops:
; GFX9-GISEL:       ; %bb.0:
; GFX9-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX9-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v6, v3
; GFX9-GISEL-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v5, v1
; GFX9-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[2:3]
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX9-GISEL-NEXT:    v_add_co_u32_e32 v0, vcc, v2, v0
; GFX9-GISEL-NEXT:    v_ashrrev_i32_e32 v7, 31, v6
; GFX9-GISEL-NEXT:    v_addc_co_u32_e32 v1, vcc, v3, v1, vcc
; GFX9-GISEL-NEXT:    v_lshlrev_b64 v[2:3], 4, v[6:7]
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v7, s3
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v6, s2
; GFX9-GISEL-NEXT:    v_add_co_u32_e32 v2, vcc, v6, v2
; GFX9-GISEL-NEXT:    v_addc_co_u32_e32 v3, vcc, v7, v3, vcc
; GFX9-GISEL-NEXT:    global_load_dwordx4 v[8:11], v[0:1], off
; GFX9-GISEL-NEXT:    global_load_dwordx4 v[12:15], v[0:1], off offset:16
; GFX9-GISEL-NEXT:    global_load_dwordx4 v[16:19], v[2:3], off
; GFX9-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX9-GISEL-NEXT:    s_mov_b32 s20, 0
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:  .LBB15_1: ; =>This Inner Loop Header: Depth=1
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s2, v4
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s8, v5
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v4
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[8:9], s8, v5
; GFX9-GISEL-NEXT:    s_and_b64 s[2:3], s[2:3], s[8:9]
; GFX9-GISEL-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; GFX9-GISEL-NEXT:    s_mov_b32 s21, s20
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v20, s20
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s8, v8
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s9, v9
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s10, v10
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s11, v11
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s12, v12
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s13, v13
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s14, v14
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s15, v15
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s16, v16
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s17, v17
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s18, v18
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s19, v19
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v21, s21
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX9-GISEL-NEXT:    s_nop 3
; GFX9-GISEL-NEXT:    image_sample v[0:3], v[20:21], s[8:15], s[16:19] dmask:0xf
; GFX9-GISEL-NEXT:    s_xor_b64 exec, exec, s[2:3]
; GFX9-GISEL-NEXT:    s_cbranch_execnz .LBB15_1
; GFX9-GISEL-NEXT:  ; %bb.2:
; GFX9-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v22, s4
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v23, s5
; GFX9-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX9-GISEL-NEXT:  .LBB15_3: ; =>This Inner Loop Header: Depth=1
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s2, v22
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s4, v23
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v22
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[4:5], s4, v23
; GFX9-GISEL-NEXT:    s_and_b64 s[2:3], s[2:3], s[4:5]
; GFX9-GISEL-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s8, v8
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s9, v9
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s10, v10
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s11, v11
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s12, v12
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s13, v13
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s14, v14
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s15, v15
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s16, v16
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s17, v17
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s18, v18
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s19, v19
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr22
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr23
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr16_vgpr17_vgpr18_vgpr19
; GFX9-GISEL-NEXT:    s_nop 4
; GFX9-GISEL-NEXT:    image_sample v[4:7], v[20:21], s[8:15], s[16:19] dmask:0xf
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr20_vgpr21
; GFX9-GISEL-NEXT:    s_xor_b64 exec, exec, s[2:3]
; GFX9-GISEL-NEXT:    s_cbranch_execnz .LBB15_3
; GFX9-GISEL-NEXT:  ; %bb.4:
; GFX9-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX9-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-32-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_1_2loops:
; GFX10-32-SDAG:       ; %bb.0:
; GFX10-32-SDAG-NEXT:    s_mov_b32 s4, exec_lo
; GFX10-32-SDAG-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v7, v2
; GFX10-32-SDAG-NEXT:    v_ashrrev_i32_e32 v4, 31, v3
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v6, v1
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v5, v0
; GFX10-32-SDAG-NEXT:    v_ashrrev_i32_e32 v8, 31, v7
; GFX10-32-SDAG-NEXT:    v_lshlrev_b64 v[2:3], 4, v[3:4]
; GFX10-32-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[7:8]
; GFX10-32-SDAG-NEXT:    v_add_co_u32 v0, vcc_lo, s0, v0
; GFX10-32-SDAG-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, s1, v1, vcc_lo
; GFX10-32-SDAG-NEXT:    v_add_co_u32 v2, vcc_lo, s2, v2
; GFX10-32-SDAG-NEXT:    v_add_co_ci_u32_e32 v3, vcc_lo, s3, v3, vcc_lo
; GFX10-32-SDAG-NEXT:    s_clause 0x1
; GFX10-32-SDAG-NEXT:    global_load_dwordx4 v[11:14], v[0:1], off offset:16
; GFX10-32-SDAG-NEXT:    global_load_dwordx4 v[15:18], v[0:1], off
; GFX10-32-SDAG-NEXT:    global_load_dwordx4 v[7:10], v[2:3], off
; GFX10-32-SDAG-NEXT:    s_mov_b32 s1, exec_lo
; GFX10-32-SDAG-NEXT:    s_mov_b32 s0, exec_lo
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-SDAG-NEXT:  .LBB15_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s2, v5
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s3, v6
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s2, v5
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s3, v6
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s8, v15
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s9, v16
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s10, v17
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s11, v18
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s12, v11
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s13, v12
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s14, v13
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s15, v14
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s16, v7
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s17, v8
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s18, v9
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s19, v10
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v4, 0
; GFX10-32-SDAG-NEXT:    image_sample v[0:3], [v4, v4], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-32-SDAG-NEXT:    s_andn2_wrexec_b32 s1, s1
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr6
; GFX10-32-SDAG-NEXT:    s_cbranch_execnz .LBB15_1
; GFX10-32-SDAG-NEXT:  ; %bb.2:
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-SDAG-NEXT:    s_mov_b32 exec_lo, s0
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s8, v15
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s9, v16
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s10, v17
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s11, v18
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s12, v11
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s13, v12
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s14, v13
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s15, v14
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s0, v7
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s1, v8
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s2, v9
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s3, v10
; GFX10-32-SDAG-NEXT:    s_and_b32 exec_lo, exec_lo, s4
; GFX10-32-SDAG-NEXT:    image_sample v[4:7], [v4, v4], s[8:15], s[0:3] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-32-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_1_2loops:
; GFX10-32-GISEL:       ; %bb.0:
; GFX10-32-GISEL-NEXT:    s_mov_b32 s6, exec_lo
; GFX10-32-GISEL-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v6, v3
; GFX10-32-GISEL-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v5, v1
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v9, s3
; GFX10-32-GISEL-NEXT:    v_ashrrev_i32_e32 v7, 31, v6
; GFX10-32-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[2:3]
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v8, s2
; GFX10-32-GISEL-NEXT:    v_lshlrev_b64 v[6:7], 4, v[6:7]
; GFX10-32-GISEL-NEXT:    s_mov_b32 s1, exec_lo
; GFX10-32-GISEL-NEXT:    s_mov_b32 s0, exec_lo
; GFX10-32-GISEL-NEXT:    v_add_co_u32 v0, vcc_lo, v2, v0
; GFX10-32-GISEL-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, v3, v1, vcc_lo
; GFX10-32-GISEL-NEXT:    v_add_co_u32 v2, vcc_lo, v8, v6
; GFX10-32-GISEL-NEXT:    v_add_co_ci_u32_e32 v3, vcc_lo, v9, v7, vcc_lo
; GFX10-32-GISEL-NEXT:    s_clause 0x1
; GFX10-32-GISEL-NEXT:    global_load_dwordx4 v[8:11], v[0:1], off
; GFX10-32-GISEL-NEXT:    global_load_dwordx4 v[12:15], v[0:1], off offset:16
; GFX10-32-GISEL-NEXT:    global_load_dwordx4 v[16:19], v[2:3], off
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:  .LBB15_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s2, v4
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s3, v5
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s2, v4
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s3, v5
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s8, v8
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s9, v9
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s10, v10
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s11, v11
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s12, v12
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s13, v13
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s14, v14
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s15, v15
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s16, v16
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s17, v17
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s18, v18
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s19, v19
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v20, 0
; GFX10-32-GISEL-NEXT:    image_sample v[0:3], [v20, v20], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-32-GISEL-NEXT:    s_andn2_wrexec_b32 s1, s1
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX10-32-GISEL-NEXT:    s_cbranch_execnz .LBB15_1
; GFX10-32-GISEL-NEXT:  ; %bb.2:
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-GISEL-NEXT:    s_mov_b32 exec_lo, s0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v21, s4
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v22, s5
; GFX10-32-GISEL-NEXT:    s_mov_b32 s1, exec_lo
; GFX10-32-GISEL-NEXT:    s_mov_b32 s0, exec_lo
; GFX10-32-GISEL-NEXT:  .LBB15_3: ; =>This Inner Loop Header: Depth=1
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s2, v21
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s3, v22
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s2, v21
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s3, v22
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s8, v8
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s9, v9
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s10, v10
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s11, v11
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s12, v12
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s13, v13
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s14, v14
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s15, v15
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s16, v16
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s17, v17
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s18, v18
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s19, v19
; GFX10-32-GISEL-NEXT:    image_sample v[4:7], [v20, v20], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-32-GISEL-NEXT:    s_andn2_wrexec_b32 s1, s1
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr21
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr22
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr16_vgpr17_vgpr18_vgpr19
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr20
; GFX10-32-GISEL-NEXT:    s_cbranch_execnz .LBB15_3
; GFX10-32-GISEL-NEXT:  ; %bb.4:
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-GISEL-NEXT:    s_mov_b32 exec_lo, s0
; GFX10-32-GISEL-NEXT:    s_and_b32 exec_lo, exec_lo, s6
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-64-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_1_2loops:
; GFX10-64-SDAG:       ; %bb.0:
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX10-64-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v7, v2
; GFX10-64-SDAG-NEXT:    v_ashrrev_i32_e32 v4, 31, v3
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v6, v1
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v5, v0
; GFX10-64-SDAG-NEXT:    v_ashrrev_i32_e32 v8, 31, v7
; GFX10-64-SDAG-NEXT:    v_lshlrev_b64 v[2:3], 4, v[3:4]
; GFX10-64-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[7:8]
; GFX10-64-SDAG-NEXT:    v_add_co_u32 v0, vcc, s0, v0
; GFX10-64-SDAG-NEXT:    v_add_co_ci_u32_e32 v1, vcc, s1, v1, vcc
; GFX10-64-SDAG-NEXT:    v_add_co_u32 v2, vcc, s2, v2
; GFX10-64-SDAG-NEXT:    v_add_co_ci_u32_e32 v3, vcc, s3, v3, vcc
; GFX10-64-SDAG-NEXT:    s_clause 0x1
; GFX10-64-SDAG-NEXT:    global_load_dwordx4 v[11:14], v[0:1], off offset:16
; GFX10-64-SDAG-NEXT:    global_load_dwordx4 v[15:18], v[0:1], off
; GFX10-64-SDAG-NEXT:    global_load_dwordx4 v[7:10], v[2:3], off
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-SDAG-NEXT:  .LBB15_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s6, v5
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s7, v6
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s6, v5
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s7, v6
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s8, v15
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s9, v16
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s10, v17
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s11, v18
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s12, v11
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s13, v12
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s14, v13
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s15, v14
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s16, v7
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s17, v8
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s18, v9
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s19, v10
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v4, 0
; GFX10-64-SDAG-NEXT:    image_sample v[0:3], [v4, v4], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-64-SDAG-NEXT:    s_andn2_wrexec_b64 s[2:3], s[2:3]
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr6
; GFX10-64-SDAG-NEXT:    s_cbranch_execnz .LBB15_1
; GFX10-64-SDAG-NEXT:  ; %bb.2:
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s8, v15
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s9, v16
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s10, v17
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s11, v18
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s12, v11
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s13, v12
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s14, v13
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s15, v14
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s0, v7
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s1, v8
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s2, v9
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s3, v10
; GFX10-64-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX10-64-SDAG-NEXT:    image_sample v[4:7], [v4, v4], s[8:15], s[0:3] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-64-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_1_2loops:
; GFX10-64-GISEL:       ; %bb.0:
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX10-64-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v6, v3
; GFX10-64-GISEL-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v5, v1
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v9, s3
; GFX10-64-GISEL-NEXT:    v_ashrrev_i32_e32 v7, 31, v6
; GFX10-64-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[2:3]
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v8, s2
; GFX10-64-GISEL-NEXT:    v_lshlrev_b64 v[6:7], 4, v[6:7]
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX10-64-GISEL-NEXT:    v_add_co_u32 v0, vcc, v2, v0
; GFX10-64-GISEL-NEXT:    v_add_co_ci_u32_e32 v1, vcc, v3, v1, vcc
; GFX10-64-GISEL-NEXT:    v_add_co_u32 v2, vcc, v8, v6
; GFX10-64-GISEL-NEXT:    v_add_co_ci_u32_e32 v3, vcc, v9, v7, vcc
; GFX10-64-GISEL-NEXT:    s_clause 0x1
; GFX10-64-GISEL-NEXT:    global_load_dwordx4 v[8:11], v[0:1], off
; GFX10-64-GISEL-NEXT:    global_load_dwordx4 v[12:15], v[0:1], off offset:16
; GFX10-64-GISEL-NEXT:    global_load_dwordx4 v[16:19], v[2:3], off
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:  .LBB15_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s8, v4
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s9, v5
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s8, v4
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s9, v5
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s8, v8
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s9, v9
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s10, v10
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s11, v11
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s12, v12
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s13, v13
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s14, v14
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s15, v15
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s16, v16
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s17, v17
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s18, v18
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s19, v19
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v20, 0
; GFX10-64-GISEL-NEXT:    image_sample v[0:3], [v20, v20], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-64-GISEL-NEXT:    s_andn2_wrexec_b64 s[2:3], s[2:3]
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX10-64-GISEL-NEXT:    s_cbranch_execnz .LBB15_1
; GFX10-64-GISEL-NEXT:  ; %bb.2:
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v21, s4
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v22, s5
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX10-64-GISEL-NEXT:  .LBB15_3: ; =>This Inner Loop Header: Depth=1
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s4, v21
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s5, v22
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s4, v21
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s5, v22
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s8, v8
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s9, v9
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s10, v10
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s11, v11
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s12, v12
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s13, v13
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s14, v14
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s15, v15
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s16, v16
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s17, v17
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s18, v18
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s19, v19
; GFX10-64-GISEL-NEXT:    image_sample v[4:7], [v20, v20], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-64-GISEL-NEXT:    s_andn2_wrexec_b64 s[2:3], s[2:3]
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr21
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr22
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr16_vgpr17_vgpr18_vgpr19
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr20
; GFX10-64-GISEL-NEXT:    s_cbranch_execnz .LBB15_3
; GFX10-64-GISEL-NEXT:  ; %bb.4:
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX10-64-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:    ; return to shader part epilog
;
; GFX1150-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_1_2loops:
; GFX1150-SDAG:       ; %bb.0:
; GFX1150-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX1150-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v7, v2
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v6, v1
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v5, v0
; GFX1150-SDAG-NEXT:    v_ashrrev_i32_e32 v4, 31, v3
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX1150-SDAG-NEXT:    v_ashrrev_i32_e32 v8, 31, v7
; GFX1150-SDAG-NEXT:    v_lshlrev_b64 v[2:3], 4, v[3:4]
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX1150-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[7:8]
; GFX1150-SDAG-NEXT:    v_add_co_u32 v0, vcc, s0, v0
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX1150-SDAG-NEXT:    v_add_co_ci_u32_e64 v1, null, s1, v1, vcc
; GFX1150-SDAG-NEXT:    v_add_co_u32 v2, vcc, s2, v2
; GFX1150-SDAG-NEXT:    s_waitcnt_depctr depctr_va_vcc(0)
; GFX1150-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX1150-SDAG-NEXT:    v_add_co_ci_u32_e64 v3, null, s3, v3, vcc
; GFX1150-SDAG-NEXT:    s_clause 0x1
; GFX1150-SDAG-NEXT:    global_load_b128 v[11:14], v[0:1], off offset:16
; GFX1150-SDAG-NEXT:    global_load_b128 v[15:18], v[0:1], off
; GFX1150-SDAG-NEXT:    global_load_b128 v[7:10], v[2:3], off
; GFX1150-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:  .LBB15_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s6, v5
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s7, v6
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s6, v5
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s7, v6
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s8, v15
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s9, v16
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s10, v17
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s11, v18
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s12, v11
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s13, v12
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s14, v13
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s15, v14
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s16, v7
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s17, v8
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s18, v9
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s19, v10
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v4, 0
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:    image_sample v[0:3], [v4, v4], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX1150-SDAG-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr6
; GFX1150-SDAG-NEXT:    s_cbranch_execnz .LBB15_1
; GFX1150-SDAG-NEXT:  ; %bb.2:
; GFX1150-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s8, v15
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s9, v16
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s10, v17
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s11, v18
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s12, v11
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s13, v12
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s14, v13
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s15, v14
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s0, v7
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s1, v8
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s2, v9
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s3, v10
; GFX1150-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX1150-SDAG-NEXT:    image_sample v[4:7], [v4, v4], s[8:15], s[0:3] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:    ; return to shader part epilog
;
; GFX1150-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_1_2loops:
; GFX1150-GISEL:       ; %bb.0:
; GFX1150-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX1150-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v6, v3
; GFX1150-GISEL-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v5, v1
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v9, s3
; GFX1150-GISEL-NEXT:    v_ashrrev_i32_e32 v7, 31, v6
; GFX1150-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[2:3]
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v8, s2
; GFX1150-GISEL-NEXT:    v_lshlrev_b64 v[6:7], 4, v[6:7]
; GFX1150-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX1150-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX1150-GISEL-NEXT:    v_add_co_u32 v0, vcc, v2, v0
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX1150-GISEL-NEXT:    v_add_co_ci_u32_e64 v1, null, v3, v1, vcc
; GFX1150-GISEL-NEXT:    v_add_co_u32 v2, vcc, v8, v6
; GFX1150-GISEL-NEXT:    s_waitcnt_depctr depctr_va_vcc(0)
; GFX1150-GISEL-NEXT:    v_add_co_ci_u32_e64 v3, null, v9, v7, vcc
; GFX1150-GISEL-NEXT:    s_clause 0x1
; GFX1150-GISEL-NEXT:    global_load_b128 v[8:11], v[0:1], off
; GFX1150-GISEL-NEXT:    global_load_b128 v[12:15], v[0:1], off offset:16
; GFX1150-GISEL-NEXT:    global_load_b128 v[16:19], v[2:3], off
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:  .LBB15_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s8, v4
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s9, v5
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s8, v4
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s9, v5
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s8, v8
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s9, v9
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s10, v10
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s11, v11
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s12, v12
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s13, v13
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s14, v14
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s15, v15
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s16, v16
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s17, v17
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s18, v18
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s19, v19
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v20, 0
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    image_sample v[0:3], [v20, v20], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX1150-GISEL-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX1150-GISEL-NEXT:    s_cbranch_execnz .LBB15_1
; GFX1150-GISEL-NEXT:  ; %bb.2:
; GFX1150-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v21, s4
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v22, s5
; GFX1150-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX1150-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX1150-GISEL-NEXT:  .LBB15_3: ; =>This Inner Loop Header: Depth=1
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s4, v21
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s5, v22
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s4, v21
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s5, v22
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s8, v8
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s9, v9
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s10, v10
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s11, v11
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s12, v12
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s13, v13
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s14, v14
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s15, v15
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s16, v16
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s17, v17
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s18, v18
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s19, v19
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    image_sample v[4:7], [v20, v20], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX1150-GISEL-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr21
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr22
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr16_vgpr17_vgpr18_vgpr19
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr20
; GFX1150-GISEL-NEXT:    s_cbranch_execnz .LBB15_3
; GFX1150-GISEL-NEXT:  ; %bb.4:
; GFX1150-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    ; return to shader part epilog
;
; GFX12-SDAG-LABEL: test_waterfall_multi_begin_uniform_idx_1_2loops:
; GFX12-SDAG:       ; %bb.0:
; GFX12-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX12-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v7, v2
; GFX12-SDAG-NEXT:    v_ashrrev_i32_e32 v4, 31, v3
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v6, v1
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v5, v0
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX12-SDAG-NEXT:    v_ashrrev_i32_e32 v8, 31, v7
; GFX12-SDAG-NEXT:    v_lshlrev_b64_e32 v[2:3], 4, v[3:4]
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX12-SDAG-NEXT:    v_lshlrev_b64_e32 v[0:1], 5, v[7:8]
; GFX12-SDAG-NEXT:    v_add_co_u32 v0, vcc, s0, v0
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX12-SDAG-NEXT:    v_add_co_ci_u32_e64 v1, null, s1, v1, vcc
; GFX12-SDAG-NEXT:    v_add_co_u32 v2, vcc, s2, v2
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_vcc(0)
; GFX12-SDAG-NEXT:    v_add_co_ci_u32_e64 v3, null, s3, v3, vcc
; GFX12-SDAG-NEXT:    s_clause 0x1
; GFX12-SDAG-NEXT:    global_load_b128 v[11:14], v[0:1], off offset:16
; GFX12-SDAG-NEXT:    global_load_b128 v[15:18], v[0:1], off
; GFX12-SDAG-NEXT:    global_load_b128 v[7:10], v[2:3], off
; GFX12-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX12-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX12-SDAG-NEXT:  .LBB15_1: ; =>This Inner Loop Header: Depth=1
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s6, v5
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s7, v6
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s6, v5
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s7, v6
; GFX12-SDAG-NEXT:    s_wait_loadcnt 0x1
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s8, v15
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s9, v16
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s10, v17
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s11, v18
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s12, v11
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s13, v12
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s14, v13
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s15, v14
; GFX12-SDAG-NEXT:    s_wait_loadcnt 0x0
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s16, v7
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s17, v8
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s18, v9
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s19, v10
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v4, 0
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    image_sample v[0:3], [v4, v4], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX12-SDAG-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr6
; GFX12-SDAG-NEXT:    s_cbranch_execnz .LBB15_1
; GFX12-SDAG-NEXT:  ; %bb.2:
; GFX12-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s8, v15
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s9, v16
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s10, v17
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s11, v18
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s12, v11
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s13, v12
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s14, v13
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s15, v14
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s0, v7
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s1, v8
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s2, v9
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s3, v10
; GFX12-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX12-SDAG-NEXT:    image_sample v[4:7], [v4, v4], s[8:15], s[0:3] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    ; return to shader part epilog
;
; GFX12-GISEL-LABEL: test_waterfall_multi_begin_uniform_idx_1_2loops:
; GFX12-GISEL:       ; %bb.0:
; GFX12-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX12-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v6, v3
; GFX12-GISEL-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v5, v1
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v9, s3
; GFX12-GISEL-NEXT:    v_ashrrev_i32_e32 v7, 31, v6
; GFX12-GISEL-NEXT:    v_lshlrev_b64_e32 v[0:1], 5, v[2:3]
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v8, s2
; GFX12-GISEL-NEXT:    v_lshlrev_b64_e32 v[6:7], 4, v[6:7]
; GFX12-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX12-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX12-GISEL-NEXT:    v_add_co_u32 v0, vcc, v2, v0
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX12-GISEL-NEXT:    v_add_co_ci_u32_e64 v1, null, v3, v1, vcc
; GFX12-GISEL-NEXT:    v_add_co_u32 v2, vcc, v8, v6
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_vcc(0)
; GFX12-GISEL-NEXT:    v_add_co_ci_u32_e64 v3, null, v9, v7, vcc
; GFX12-GISEL-NEXT:    s_clause 0x1
; GFX12-GISEL-NEXT:    global_load_b128 v[8:11], v[0:1], off
; GFX12-GISEL-NEXT:    global_load_b128 v[12:15], v[0:1], off offset:16
; GFX12-GISEL-NEXT:    global_load_b128 v[16:19], v[2:3], off
; GFX12-GISEL-NEXT:  .LBB15_1: ; =>This Inner Loop Header: Depth=1
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s8, v4
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s9, v5
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s8, v4
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s9, v5
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x2
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s8, v8
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s9, v9
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s10, v10
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s11, v11
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x1
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s12, v12
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s13, v13
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s14, v14
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s15, v15
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x0
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s16, v16
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s17, v17
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s18, v18
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s19, v19
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v20, 0
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    image_sample v[0:3], [v20, v20], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX12-GISEL-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr4
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX12-GISEL-NEXT:    s_cbranch_execnz .LBB15_1
; GFX12-GISEL-NEXT:  ; %bb.2:
; GFX12-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v21, s4
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v22, s5
; GFX12-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX12-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX12-GISEL-NEXT:  .LBB15_3: ; =>This Inner Loop Header: Depth=1
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s4, v21
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s5, v22
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s4, v21
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s5, v22
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s8, v8
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s9, v9
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s10, v10
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s11, v11
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s12, v12
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s13, v13
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s14, v14
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s15, v15
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s16, v16
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s17, v17
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s18, v18
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s19, v19
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    image_sample v[4:7], [v20, v20], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX12-GISEL-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr21
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr22
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr8_vgpr9_vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr16_vgpr17_vgpr18_vgpr19
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr20
; GFX12-GISEL-NEXT:    s_cbranch_execnz .LBB15_3
; GFX12-GISEL-NEXT:  ; %bb.4:
; GFX12-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX12-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-GISEL-NEXT:    s_and_b64 exec, exec, s[6:7]
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-GISEL-NEXT:    ; return to shader part epilog
       <8 x i32> addrspace(4)* inreg %in, <4 x i32> addrspace(4)* inreg %s_in,
       i32 %idx1, i32 %idx2, i32 inreg %idx3, i32 inreg%idx4,
       i32 %s_idx, i32 %s_idx2, { <4 x float>, <4 x float> } %dummy) #1 {
  %rptr = getelementptr <8 x i32>, <8 x i32> addrspace(4)* %in, i32 %s_idx
  %sptr = getelementptr <4 x i32>, <4 x i32> addrspace(4)* %s_in, i32 %s_idx2
  %rsrc = load <8 x i32>, <8 x i32> addrspace(4)* %rptr, align 16
  %srsrc = load <4 x i32>, <4 x i32> addrspace(4)* %sptr, align 16
  %tok = call token @llvm.amdgcn.waterfall.begin.i32(token poison, i32 %idx1)
  %tok1 = call token @llvm.amdgcn.waterfall.begin.i32(token %tok, i32 %idx2)
  %s_rsrc = call <8 x i32> @llvm.amdgcn.waterfall.readfirstlane.v8i32.v8i32(token %tok1, <8 x i32> %rsrc)
  %s_srsrc = call <4 x i32> @llvm.amdgcn.waterfall.readfirstlane.v4i32.v4i32(token %tok1, <4 x i32> %srsrc)
  %r = call <4 x float> @llvm.amdgcn.image.sample.2d.v4f32.f32(i32 15, float 0.000000e+00, float 0.000000e+00, <8 x i32> %s_rsrc, <4 x i32> %s_srsrc, i1 false, i32 0, i32 0)
  %r1 = call <4 x float> @llvm.amdgcn.waterfall.end.v4f32(token %tok1, <4 x float> %r)

  %tok2 = call token @llvm.amdgcn.waterfall.begin.i32(token poison, i32 %idx3)
  %tok3 = call token @llvm.amdgcn.waterfall.begin.i32(token %tok2, i32 %idx4)
  %s_rsrc1 = call <8 x i32> @llvm.amdgcn.waterfall.readfirstlane.v8i32.v8i32(token %tok3, <8 x i32> %rsrc)
  %s_srsrc1 = call <4 x i32> @llvm.amdgcn.waterfall.readfirstlane.v4i32.v4i32(token %tok3, <4 x i32> %srsrc)
  %r2 = call <4 x float> @llvm.amdgcn.image.sample.2d.v4f32.f32(i32 15, float 0.000000e+00, float 0.000000e+00, <8 x i32> %s_rsrc1, <4 x i32> %s_srsrc1, i1 false, i32 0, i32 0)
  %r3 = call <4 x float> @llvm.amdgcn.waterfall.end.v4f32(token %tok3, <4 x float> %r2)

  %insert = insertvalue { <4 x float>, <4 x float> } %dummy, <4 x float> %r1, 0
  %insert1 = insertvalue { <4 x float>, <4 x float> } %insert, <4 x float> %r3, 1
  ret {<4 x float> , <4 x float>} %insert1
}

define amdgpu_gfx i32 @test_indirect_call_vgpr_ptr_arg_and_reuse(i32 %i, i32 %fptr) {
; PRE-GFX10-LABEL: test_indirect_call_vgpr_ptr_arg_and_reuse:
; PRE-GFX10:       ; %bb.0:
; PRE-GFX10-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; PRE-GFX10-NEXT:    s_mov_b32 s34, s33
; PRE-GFX10-NEXT:    s_mov_b32 s33, s32
; PRE-GFX10-NEXT:    s_or_saveexec_b64 s[36:37], -1
; PRE-GFX10-NEXT:    buffer_store_dword v40, off, s[0:3], s33 ; 4-byte Folded Spill
; PRE-GFX10-NEXT:    s_mov_b64 exec, s[36:37]
; PRE-GFX10-NEXT:    v_writelane_b32 v40, s34, 6
; PRE-GFX10-NEXT:    s_addk_i32 s32, 0x400
; PRE-GFX10-NEXT:    v_writelane_b32 v40, s4, 0
; PRE-GFX10-NEXT:    v_writelane_b32 v40, s5, 1
; PRE-GFX10-NEXT:    v_writelane_b32 v40, s6, 2
; PRE-GFX10-NEXT:    v_writelane_b32 v40, s7, 3
; PRE-GFX10-NEXT:    v_writelane_b32 v40, s30, 4
; PRE-GFX10-NEXT:    v_writelane_b32 v40, s31, 5
; PRE-GFX10-NEXT:    s_mov_b64 s[4:5], exec
; PRE-GFX10-NEXT:  .LBB16_1: ; =>This Inner Loop Header: Depth=1
; PRE-GFX10-NEXT:    v_readfirstlane_b32 s34, v1
; PRE-GFX10-NEXT:    v_cmp_eq_u32_e64 s[36:37], s34, v1
; PRE-GFX10-NEXT:    s_and_saveexec_b64 s[6:7], s[36:37]
; PRE-GFX10-NEXT:    s_mov_b32 s35, 0
; PRE-GFX10-NEXT:    s_swappc_b64 s[30:31], s[34:35]
; PRE-GFX10-NEXT:    v_mov_b32_e32 v2, v0
; PRE-GFX10-NEXT:    ; implicit-def: $vgpr1
; PRE-GFX10-NEXT:    ; implicit-def: $vgpr0
; PRE-GFX10-NEXT:    s_xor_b64 exec, exec, s[6:7]
; PRE-GFX10-NEXT:    s_cbranch_execnz .LBB16_1
; PRE-GFX10-NEXT:  ; %bb.2:
; PRE-GFX10-NEXT:    s_mov_b64 exec, s[4:5]
; PRE-GFX10-NEXT:    v_readlane_b32 s30, v40, 4
; PRE-GFX10-NEXT:    v_mov_b32_e32 v0, v2
; PRE-GFX10-NEXT:    v_readlane_b32 s31, v40, 5
; PRE-GFX10-NEXT:    v_readlane_b32 s7, v40, 3
; PRE-GFX10-NEXT:    v_readlane_b32 s6, v40, 2
; PRE-GFX10-NEXT:    v_readlane_b32 s5, v40, 1
; PRE-GFX10-NEXT:    v_readlane_b32 s4, v40, 0
; PRE-GFX10-NEXT:    s_mov_b32 s32, s33
; PRE-GFX10-NEXT:    v_readlane_b32 s34, v40, 6
; PRE-GFX10-NEXT:    s_or_saveexec_b64 s[36:37], -1
; PRE-GFX10-NEXT:    buffer_load_dword v40, off, s[0:3], s33 ; 4-byte Folded Reload
; PRE-GFX10-NEXT:    s_mov_b64 exec, s[36:37]
; PRE-GFX10-NEXT:    s_mov_b32 s33, s34
; PRE-GFX10-NEXT:    s_waitcnt vmcnt(0)
; PRE-GFX10-NEXT:    s_setpc_b64 s[30:31]
;
; GFX10-32-LABEL: test_indirect_call_vgpr_ptr_arg_and_reuse:
; GFX10-32:       ; %bb.0:
; GFX10-32-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX10-32-NEXT:    s_mov_b32 s34, s33
; GFX10-32-NEXT:    s_mov_b32 s33, s32
; GFX10-32-NEXT:    s_or_saveexec_b32 s35, -1
; GFX10-32-NEXT:    buffer_store_dword v40, off, s[0:3], s33 ; 4-byte Folded Spill
; GFX10-32-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-NEXT:    s_mov_b32 exec_lo, s35
; GFX10-32-NEXT:    v_writelane_b32 v40, s34, 4
; GFX10-32-NEXT:    s_addk_i32 s32, 0x200
; GFX10-32-NEXT:    v_writelane_b32 v40, s4, 0
; GFX10-32-NEXT:    v_writelane_b32 v40, s5, 1
; GFX10-32-NEXT:    v_writelane_b32 v40, s30, 2
; GFX10-32-NEXT:    v_writelane_b32 v40, s31, 3
; GFX10-32-NEXT:    s_mov_b32 s5, exec_lo
; GFX10-32-NEXT:    s_mov_b32 s4, exec_lo
; GFX10-32-NEXT:  .LBB16_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-NEXT:    v_readfirstlane_b32 s34, v1
; GFX10-32-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-NEXT:    v_cmpx_eq_u32_e32 s34, v1
; GFX10-32-NEXT:    s_mov_b32 s35, 0
; GFX10-32-NEXT:    s_swappc_b64 s[30:31], s[34:35]
; GFX10-32-NEXT:    v_mov_b32_e32 v2, v0
; GFX10-32-NEXT:    s_andn2_wrexec_b32 s5, s5
; GFX10-32-NEXT:    ; implicit-def: $vgpr1
; GFX10-32-NEXT:    ; implicit-def: $vgpr0
; GFX10-32-NEXT:    s_cbranch_execnz .LBB16_1
; GFX10-32-NEXT:  ; %bb.2:
; GFX10-32-NEXT:    s_mov_b32 exec_lo, s4
; GFX10-32-NEXT:    v_readlane_b32 s30, v40, 2
; GFX10-32-NEXT:    v_mov_b32_e32 v0, v2
; GFX10-32-NEXT:    v_readlane_b32 s31, v40, 3
; GFX10-32-NEXT:    v_readlane_b32 s5, v40, 1
; GFX10-32-NEXT:    v_readlane_b32 s4, v40, 0
; GFX10-32-NEXT:    s_mov_b32 s32, s33
; GFX10-32-NEXT:    v_readlane_b32 s34, v40, 4
; GFX10-32-NEXT:    s_or_saveexec_b32 s35, -1
; GFX10-32-NEXT:    buffer_load_dword v40, off, s[0:3], s33 ; 4-byte Folded Reload
; GFX10-32-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-NEXT:    s_mov_b32 exec_lo, s35
; GFX10-32-NEXT:    s_mov_b32 s33, s34
; GFX10-32-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-NEXT:    s_setpc_b64 s[30:31]
;
; GFX10-64-LABEL: test_indirect_call_vgpr_ptr_arg_and_reuse:
; GFX10-64:       ; %bb.0:
; GFX10-64-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX10-64-NEXT:    s_mov_b32 s34, s33
; GFX10-64-NEXT:    s_mov_b32 s33, s32
; GFX10-64-NEXT:    s_or_saveexec_b64 s[36:37], -1
; GFX10-64-NEXT:    buffer_store_dword v40, off, s[0:3], s33 ; 4-byte Folded Spill
; GFX10-64-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-NEXT:    s_mov_b64 exec, s[36:37]
; GFX10-64-NEXT:    v_writelane_b32 v40, s34, 6
; GFX10-64-NEXT:    s_addk_i32 s32, 0x400
; GFX10-64-NEXT:    v_writelane_b32 v40, s4, 0
; GFX10-64-NEXT:    v_writelane_b32 v40, s5, 1
; GFX10-64-NEXT:    v_writelane_b32 v40, s6, 2
; GFX10-64-NEXT:    v_writelane_b32 v40, s7, 3
; GFX10-64-NEXT:    v_writelane_b32 v40, s30, 4
; GFX10-64-NEXT:    v_writelane_b32 v40, s31, 5
; GFX10-64-NEXT:    s_mov_b64 s[6:7], exec
; GFX10-64-NEXT:    s_mov_b64 s[4:5], exec
; GFX10-64-NEXT:  .LBB16_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-NEXT:    v_readfirstlane_b32 s34, v1
; GFX10-64-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-NEXT:    v_cmpx_eq_u32_e32 s34, v1
; GFX10-64-NEXT:    s_mov_b32 s35, 0
; GFX10-64-NEXT:    s_swappc_b64 s[30:31], s[34:35]
; GFX10-64-NEXT:    v_mov_b32_e32 v2, v0
; GFX10-64-NEXT:    s_andn2_wrexec_b64 s[6:7], s[6:7]
; GFX10-64-NEXT:    ; implicit-def: $vgpr1
; GFX10-64-NEXT:    ; implicit-def: $vgpr0
; GFX10-64-NEXT:    s_cbranch_execnz .LBB16_1
; GFX10-64-NEXT:  ; %bb.2:
; GFX10-64-NEXT:    s_mov_b64 exec, s[4:5]
; GFX10-64-NEXT:    v_readlane_b32 s30, v40, 4
; GFX10-64-NEXT:    v_mov_b32_e32 v0, v2
; GFX10-64-NEXT:    v_readlane_b32 s31, v40, 5
; GFX10-64-NEXT:    v_readlane_b32 s7, v40, 3
; GFX10-64-NEXT:    v_readlane_b32 s6, v40, 2
; GFX10-64-NEXT:    v_readlane_b32 s5, v40, 1
; GFX10-64-NEXT:    v_readlane_b32 s4, v40, 0
; GFX10-64-NEXT:    s_mov_b32 s32, s33
; GFX10-64-NEXT:    v_readlane_b32 s34, v40, 6
; GFX10-64-NEXT:    s_or_saveexec_b64 s[36:37], -1
; GFX10-64-NEXT:    buffer_load_dword v40, off, s[0:3], s33 ; 4-byte Folded Reload
; GFX10-64-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-NEXT:    s_mov_b64 exec, s[36:37]
; GFX10-64-NEXT:    s_mov_b32 s33, s34
; GFX10-64-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-NEXT:    s_setpc_b64 s[30:31]
;
; GFX1150-LABEL: test_indirect_call_vgpr_ptr_arg_and_reuse:
; GFX1150:       ; %bb.0:
; GFX1150-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GFX1150-NEXT:    s_mov_b32 s0, s33
; GFX1150-NEXT:    s_mov_b32 s33, s32
; GFX1150-NEXT:    s_or_saveexec_b64 s[2:3], -1
; GFX1150-NEXT:    scratch_store_b32 off, v40, s33 ; 4-byte Folded Spill
; GFX1150-NEXT:    s_mov_b64 exec, s[2:3]
; GFX1150-NEXT:    v_writelane_b32 v40, s0, 6
; GFX1150-NEXT:    s_add_i32 s32, s32, 16
; GFX1150-NEXT:    v_writelane_b32 v40, s4, 0
; GFX1150-NEXT:    v_writelane_b32 v40, s5, 1
; GFX1150-NEXT:    v_writelane_b32 v40, s6, 2
; GFX1150-NEXT:    v_writelane_b32 v40, s7, 3
; GFX1150-NEXT:    v_writelane_b32 v40, s30, 4
; GFX1150-NEXT:    v_writelane_b32 v40, s31, 5
; GFX1150-NEXT:    s_mov_b64 s[6:7], exec
; GFX1150-NEXT:    s_mov_b64 s[4:5], exec
; GFX1150-NEXT:  .LBB16_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-NEXT:    v_readfirstlane_b32 s0, v1
; GFX1150-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(SALU_CYCLE_1)
; GFX1150-NEXT:    v_cmpx_eq_u32_e32 s0, v1
; GFX1150-NEXT:    s_mov_b32 s1, 0
; GFX1150-NEXT:    s_swappc_b64 s[30:31], s[0:1]
; GFX1150-NEXT:    v_mov_b32_e32 v2, v0
; GFX1150-NEXT:    s_and_not1_wrexec_b64 s[6:7], s[6:7]
; GFX1150-NEXT:    ; implicit-def: $vgpr1
; GFX1150-NEXT:    ; implicit-def: $vgpr0
; GFX1150-NEXT:    s_cbranch_execnz .LBB16_1
; GFX1150-NEXT:  ; %bb.2:
; GFX1150-NEXT:    s_mov_b64 exec, s[4:5]
; GFX1150-NEXT:    v_readlane_b32 s30, v40, 4
; GFX1150-NEXT:    v_mov_b32_e32 v0, v2
; GFX1150-NEXT:    v_readlane_b32 s31, v40, 5
; GFX1150-NEXT:    v_readlane_b32 s7, v40, 3
; GFX1150-NEXT:    v_readlane_b32 s6, v40, 2
; GFX1150-NEXT:    v_readlane_b32 s5, v40, 1
; GFX1150-NEXT:    v_readlane_b32 s4, v40, 0
; GFX1150-NEXT:    s_mov_b32 s32, s33
; GFX1150-NEXT:    v_readlane_b32 s0, v40, 6
; GFX1150-NEXT:    s_or_saveexec_b64 s[2:3], -1
; GFX1150-NEXT:    scratch_load_b32 v40, off, s33 ; 4-byte Folded Reload
; GFX1150-NEXT:    s_mov_b64 exec, s[2:3]
; GFX1150-NEXT:    s_mov_b32 s33, s0
; GFX1150-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-NEXT:    s_setpc_b64 s[30:31]
;
; GFX12-LABEL: test_indirect_call_vgpr_ptr_arg_and_reuse:
; GFX12:       ; %bb.0:
; GFX12-NEXT:    s_wait_loadcnt_dscnt 0x0
; GFX12-NEXT:    s_wait_expcnt 0x0
; GFX12-NEXT:    s_wait_samplecnt 0x0
; GFX12-NEXT:    s_wait_bvhcnt 0x0
; GFX12-NEXT:    s_wait_kmcnt 0x0
; GFX12-NEXT:    s_mov_b32 s0, s33
; GFX12-NEXT:    s_mov_b32 s33, s32
; GFX12-NEXT:    s_or_saveexec_b64 s[2:3], -1
; GFX12-NEXT:    scratch_store_b32 off, v40, s33 ; 4-byte Folded Spill
; GFX12-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-NEXT:    s_mov_b64 exec, s[2:3]
; GFX12-NEXT:    v_writelane_b32 v40, s0, 6
; GFX12-NEXT:    s_add_co_i32 s32, s32, 16
; GFX12-NEXT:    v_writelane_b32 v40, s4, 0
; GFX12-NEXT:    v_writelane_b32 v40, s5, 1
; GFX12-NEXT:    v_writelane_b32 v40, s6, 2
; GFX12-NEXT:    v_writelane_b32 v40, s7, 3
; GFX12-NEXT:    v_writelane_b32 v40, s30, 4
; GFX12-NEXT:    v_writelane_b32 v40, s31, 5
; GFX12-NEXT:    s_mov_b64 s[6:7], exec
; GFX12-NEXT:    s_mov_b64 s[4:5], exec
; GFX12-NEXT:  .LBB16_1: ; =>This Inner Loop Header: Depth=1
; GFX12-NEXT:    v_readfirstlane_b32 s0, v1
; GFX12-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX12-NEXT:    v_cmpx_eq_u32_e32 s0, v1
; GFX12-NEXT:    s_mov_b32 s1, 0
; GFX12-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-NEXT:    s_swappc_b64 s[30:31], s[0:1]
; GFX12-NEXT:    v_mov_b32_e32 v2, v0
; GFX12-NEXT:    s_and_not1_wrexec_b64 s[6:7], s[6:7]
; GFX12-NEXT:    ; implicit-def: $vgpr1
; GFX12-NEXT:    ; implicit-def: $vgpr0
; GFX12-NEXT:    s_cbranch_execnz .LBB16_1
; GFX12-NEXT:  ; %bb.2:
; GFX12-NEXT:    s_mov_b64 exec, s[4:5]
; GFX12-NEXT:    v_readlane_b32 s30, v40, 4
; GFX12-NEXT:    v_mov_b32_e32 v0, v2
; GFX12-NEXT:    v_readlane_b32 s31, v40, 5
; GFX12-NEXT:    v_readlane_b32 s7, v40, 3
; GFX12-NEXT:    v_readlane_b32 s6, v40, 2
; GFX12-NEXT:    v_readlane_b32 s5, v40, 1
; GFX12-NEXT:    v_readlane_b32 s4, v40, 0
; GFX12-NEXT:    s_mov_b32 s32, s33
; GFX12-NEXT:    v_readlane_b32 s0, v40, 6
; GFX12-NEXT:    s_or_saveexec_b64 s[2:3], -1
; GFX12-NEXT:    scratch_load_b32 v40, off, s33 ; 4-byte Folded Reload
; GFX12-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-NEXT:    s_mov_b64 exec, s[2:3]
; GFX12-NEXT:    s_mov_b32 s33, s0
; GFX12-NEXT:    s_wait_loadcnt 0x0
; GFX12-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-NEXT:    s_setpc_b64 s[30:31]
  %tok = call token @llvm.amdgcn.waterfall.begin.i32(token poison, i32 %fptr)
  %s_fptr = call i32 @llvm.amdgcn.waterfall.readfirstlane.i32.i32(token %tok, i32 %fptr)
  %ext = zext i32 %s_fptr to i64
  %f = inttoptr i64 %ext to i32(i32)*
  %callres = call amdgpu_gfx i32 %f(i32 %i)
  %r3 = call i32 @llvm.amdgcn.waterfall.end.i32(token %tok, i32 %callres)
  ret i32 %r3
}

define amdgpu_ps {<4 x float>,<4 x float>} @test_waterfall_multi_end_1loop(
; VI-SDAG-LABEL: test_waterfall_multi_end_1loop:
; VI-SDAG:       ; %bb.0:
; VI-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; VI-SDAG-NEXT:    s_wqm_b64 exec, exec
; VI-SDAG-NEXT:    v_mov_b32_e32 v4, v2
; VI-SDAG-NEXT:    v_ashrrev_i32_e32 v5, 31, v4
; VI-SDAG-NEXT:    v_mov_b32_e32 v8, v1
; VI-SDAG-NEXT:    v_mov_b32_e32 v9, v0
; VI-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[4:5]
; VI-SDAG-NEXT:    v_mov_b32_e32 v2, s1
; VI-SDAG-NEXT:    v_add_u32_e32 v0, vcc, s0, v0
; VI-SDAG-NEXT:    v_ashrrev_i32_e32 v4, 31, v3
; VI-SDAG-NEXT:    v_addc_u32_e32 v1, vcc, v2, v1, vcc
; VI-SDAG-NEXT:    v_lshlrev_b64 v[2:3], 4, v[3:4]
; VI-SDAG-NEXT:    v_mov_b32_e32 v4, s3
; VI-SDAG-NEXT:    v_add_u32_e32 v2, vcc, s2, v2
; VI-SDAG-NEXT:    v_addc_u32_e32 v3, vcc, v4, v3, vcc
; VI-SDAG-NEXT:    flat_load_dwordx4 v[10:13], v[0:1]
; VI-SDAG-NEXT:    v_add_u32_e32 v0, vcc, 16, v0
; VI-SDAG-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-SDAG-NEXT:    flat_load_dwordx4 v[14:17], v[0:1]
; VI-SDAG-NEXT:    flat_load_dwordx4 v[18:21], v[2:3]
; VI-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; VI-SDAG-NEXT:  .LBB17_1: ; =>This Inner Loop Header: Depth=1
; VI-SDAG-NEXT:    v_readfirstlane_b32 s2, v9
; VI-SDAG-NEXT:    v_readfirstlane_b32 s6, v8
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v9
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[6:7], s6, v8
; VI-SDAG-NEXT:    s_and_b64 s[2:3], s[2:3], s[6:7]
; VI-SDAG-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; VI-SDAG-NEXT:    s_waitcnt vmcnt(1)
; VI-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    v_mov_b32_e32 v4, 0.5
; VI-SDAG-NEXT:    s_waitcnt vmcnt(2)
; VI-SDAG-NEXT:    v_readfirstlane_b32 s8, v10
; VI-SDAG-NEXT:    v_readfirstlane_b32 s9, v11
; VI-SDAG-NEXT:    v_readfirstlane_b32 s10, v12
; VI-SDAG-NEXT:    v_readfirstlane_b32 s11, v13
; VI-SDAG-NEXT:    s_waitcnt vmcnt(1)
; VI-SDAG-NEXT:    v_readfirstlane_b32 s12, v14
; VI-SDAG-NEXT:    v_readfirstlane_b32 s13, v15
; VI-SDAG-NEXT:    v_readfirstlane_b32 s14, v16
; VI-SDAG-NEXT:    v_readfirstlane_b32 s15, v17
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    v_readfirstlane_b32 s16, v18
; VI-SDAG-NEXT:    v_readfirstlane_b32 s17, v19
; VI-SDAG-NEXT:    v_readfirstlane_b32 s18, v20
; VI-SDAG-NEXT:    v_readfirstlane_b32 s19, v21
; VI-SDAG-NEXT:    v_mov_b32_e32 v1, v0
; VI-SDAG-NEXT:    v_mov_b32_e32 v5, v4
; VI-SDAG-NEXT:    s_nop 2
; VI-SDAG-NEXT:    image_sample v[0:3], v[0:1], s[8:15], s[16:19] dmask:0xf
; VI-SDAG-NEXT:    image_sample v[4:7], v[4:5], s[8:15], s[16:19] dmask:0xf
; VI-SDAG-NEXT:    ; implicit-def: $vgpr9
; VI-SDAG-NEXT:    ; implicit-def: $vgpr8
; VI-SDAG-NEXT:    ; implicit-def: $vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17
; VI-SDAG-NEXT:    ; implicit-def: $vgpr18_vgpr19_vgpr20_vgpr21
; VI-SDAG-NEXT:    s_xor_b64 exec, exec, s[2:3]
; VI-SDAG-NEXT:    s_cbranch_execnz .LBB17_1
; VI-SDAG-NEXT:  ; %bb.2:
; VI-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; VI-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    ; return to shader part epilog
;
; VI-GISEL-LABEL: test_waterfall_multi_end_1loop:
; VI-GISEL:       ; %bb.0:
; VI-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; VI-GISEL-NEXT:    s_wqm_b64 exec, exec
; VI-GISEL-NEXT:    v_mov_b32_e32 v4, v3
; VI-GISEL-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; VI-GISEL-NEXT:    v_mov_b32_e32 v8, v0
; VI-GISEL-NEXT:    v_mov_b32_e32 v9, v1
; VI-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[2:3]
; VI-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; VI-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; VI-GISEL-NEXT:    v_add_u32_e32 v0, vcc, v2, v0
; VI-GISEL-NEXT:    v_ashrrev_i32_e32 v5, 31, v4
; VI-GISEL-NEXT:    v_addc_u32_e32 v1, vcc, v3, v1, vcc
; VI-GISEL-NEXT:    v_lshlrev_b64 v[2:3], 4, v[4:5]
; VI-GISEL-NEXT:    v_mov_b32_e32 v5, s3
; VI-GISEL-NEXT:    v_mov_b32_e32 v4, s2
; VI-GISEL-NEXT:    v_add_u32_e32 v2, vcc, v4, v2
; VI-GISEL-NEXT:    v_addc_u32_e32 v3, vcc, v5, v3, vcc
; VI-GISEL-NEXT:    flat_load_dwordx4 v[10:13], v[0:1]
; VI-GISEL-NEXT:    v_add_u32_e32 v0, vcc, 16, v0
; VI-GISEL-NEXT:    v_addc_u32_e32 v1, vcc, 0, v1, vcc
; VI-GISEL-NEXT:    flat_load_dwordx4 v[14:17], v[0:1]
; VI-GISEL-NEXT:    flat_load_dwordx4 v[18:21], v[2:3]
; VI-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; VI-GISEL-NEXT:  .LBB17_1: ; =>This Inner Loop Header: Depth=1
; VI-GISEL-NEXT:    v_readfirstlane_b32 s2, v8
; VI-GISEL-NEXT:    v_readfirstlane_b32 s6, v9
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v8
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[6:7], s6, v9
; VI-GISEL-NEXT:    s_and_b64 s[2:3], s[2:3], s[6:7]
; VI-GISEL-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; VI-GISEL-NEXT:    s_mov_b32 s6, 0
; VI-GISEL-NEXT:    s_mov_b32 s7, s6
; VI-GISEL-NEXT:    s_waitcnt vmcnt(1)
; VI-GISEL-NEXT:    v_mov_b32_e32 v0, s6
; VI-GISEL-NEXT:    v_mov_b32_e32 v1, s7
; VI-GISEL-NEXT:    s_mov_b32 s6, 0.5
; VI-GISEL-NEXT:    s_mov_b32 s7, s6
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    v_mov_b32_e32 v4, s6
; VI-GISEL-NEXT:    s_waitcnt vmcnt(2)
; VI-GISEL-NEXT:    v_readfirstlane_b32 s8, v10
; VI-GISEL-NEXT:    v_readfirstlane_b32 s9, v11
; VI-GISEL-NEXT:    v_readfirstlane_b32 s10, v12
; VI-GISEL-NEXT:    v_readfirstlane_b32 s11, v13
; VI-GISEL-NEXT:    s_waitcnt vmcnt(1)
; VI-GISEL-NEXT:    v_readfirstlane_b32 s12, v14
; VI-GISEL-NEXT:    v_readfirstlane_b32 s13, v15
; VI-GISEL-NEXT:    v_readfirstlane_b32 s14, v16
; VI-GISEL-NEXT:    v_readfirstlane_b32 s15, v17
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    v_readfirstlane_b32 s16, v18
; VI-GISEL-NEXT:    v_readfirstlane_b32 s17, v19
; VI-GISEL-NEXT:    v_readfirstlane_b32 s18, v20
; VI-GISEL-NEXT:    v_readfirstlane_b32 s19, v21
; VI-GISEL-NEXT:    v_mov_b32_e32 v5, s7
; VI-GISEL-NEXT:    s_nop 3
; VI-GISEL-NEXT:    image_sample v[0:3], v[0:1], s[8:15], s[16:19] dmask:0xf
; VI-GISEL-NEXT:    image_sample v[4:7], v[4:5], s[8:15], s[16:19] dmask:0xf
; VI-GISEL-NEXT:    ; implicit-def: $vgpr8
; VI-GISEL-NEXT:    ; implicit-def: $vgpr9
; VI-GISEL-NEXT:    ; implicit-def: $vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17
; VI-GISEL-NEXT:    ; implicit-def: $vgpr18_vgpr19_vgpr20_vgpr21
; VI-GISEL-NEXT:    s_xor_b64 exec, exec, s[2:3]
; VI-GISEL-NEXT:    s_cbranch_execnz .LBB17_1
; VI-GISEL-NEXT:  ; %bb.2:
; VI-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; VI-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    ; return to shader part epilog
;
; GFX9-SDAG-LABEL: test_waterfall_multi_end_1loop:
; GFX9-SDAG:       ; %bb.0:
; GFX9-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX9-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v4, v2
; GFX9-SDAG-NEXT:    v_ashrrev_i32_e32 v5, 31, v4
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v8, v1
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v9, v0
; GFX9-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[4:5]
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v2, s1
; GFX9-SDAG-NEXT:    v_add_co_u32_e32 v0, vcc, s0, v0
; GFX9-SDAG-NEXT:    v_ashrrev_i32_e32 v4, 31, v3
; GFX9-SDAG-NEXT:    v_addc_co_u32_e32 v1, vcc, v2, v1, vcc
; GFX9-SDAG-NEXT:    v_lshlrev_b64 v[2:3], 4, v[3:4]
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v4, s3
; GFX9-SDAG-NEXT:    v_add_co_u32_e32 v2, vcc, s2, v2
; GFX9-SDAG-NEXT:    v_addc_co_u32_e32 v3, vcc, v4, v3, vcc
; GFX9-SDAG-NEXT:    global_load_dwordx4 v[14:17], v[0:1], off offset:16
; GFX9-SDAG-NEXT:    global_load_dwordx4 v[10:13], v[0:1], off
; GFX9-SDAG-NEXT:    global_load_dwordx4 v[18:21], v[2:3], off
; GFX9-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:  .LBB17_1: ; =>This Inner Loop Header: Depth=1
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s2, v9
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s6, v8
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v9
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[6:7], s6, v8
; GFX9-SDAG-NEXT:    s_and_b64 s[2:3], s[2:3], s[6:7]
; GFX9-SDAG-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v8, 0
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s8, v10
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s9, v11
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s10, v12
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s11, v13
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s12, v14
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s13, v15
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s14, v16
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s15, v17
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s16, v18
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s17, v19
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s18, v20
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s19, v21
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v9, v8
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v10, 0.5
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v11, v10
; GFX9-SDAG-NEXT:    s_nop 1
; GFX9-SDAG-NEXT:    image_sample v[0:3], v[8:9], s[8:15], s[16:19] dmask:0xf
; GFX9-SDAG-NEXT:    image_sample v[4:7], v[10:11], s[8:15], s[16:19] dmask:0xf
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr9
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr8
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr18_vgpr19_vgpr20_vgpr21
; GFX9-SDAG-NEXT:    s_xor_b64 exec, exec, s[2:3]
; GFX9-SDAG-NEXT:    s_cbranch_execnz .LBB17_1
; GFX9-SDAG-NEXT:  ; %bb.2:
; GFX9-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX9-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    ; return to shader part epilog
;
; GFX9-GISEL-LABEL: test_waterfall_multi_end_1loop:
; GFX9-GISEL:       ; %bb.0:
; GFX9-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX9-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v4, v3
; GFX9-GISEL-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v8, v0
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v9, v1
; GFX9-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[2:3]
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX9-GISEL-NEXT:    v_add_co_u32_e32 v0, vcc, v2, v0
; GFX9-GISEL-NEXT:    v_ashrrev_i32_e32 v5, 31, v4
; GFX9-GISEL-NEXT:    v_addc_co_u32_e32 v1, vcc, v3, v1, vcc
; GFX9-GISEL-NEXT:    v_lshlrev_b64 v[2:3], 4, v[4:5]
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v5, s3
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v4, s2
; GFX9-GISEL-NEXT:    v_add_co_u32_e32 v2, vcc, v4, v2
; GFX9-GISEL-NEXT:    v_addc_co_u32_e32 v3, vcc, v5, v3, vcc
; GFX9-GISEL-NEXT:    global_load_dwordx4 v[10:13], v[0:1], off
; GFX9-GISEL-NEXT:    global_load_dwordx4 v[14:17], v[0:1], off offset:16
; GFX9-GISEL-NEXT:    global_load_dwordx4 v[18:21], v[2:3], off
; GFX9-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:  .LBB17_1: ; =>This Inner Loop Header: Depth=1
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s2, v8
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s6, v9
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v8
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[6:7], s6, v9
; GFX9-GISEL-NEXT:    s_and_b64 s[2:3], s[2:3], s[6:7]
; GFX9-GISEL-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; GFX9-GISEL-NEXT:    s_mov_b32 s6, 0
; GFX9-GISEL-NEXT:    s_mov_b32 s7, s6
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v9, s7
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v8, s6
; GFX9-GISEL-NEXT:    s_mov_b32 s6, 0.5
; GFX9-GISEL-NEXT:    s_mov_b32 s7, s6
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s8, v10
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s9, v11
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s10, v12
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s11, v13
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s12, v14
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s13, v15
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s14, v16
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s15, v17
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s16, v18
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s17, v19
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s18, v20
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s19, v21
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v11, s7
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v10, s6
; GFX9-GISEL-NEXT:    s_nop 2
; GFX9-GISEL-NEXT:    image_sample v[0:3], v[8:9], s[8:15], s[16:19] dmask:0xf
; GFX9-GISEL-NEXT:    image_sample v[4:7], v[10:11], s[8:15], s[16:19] dmask:0xf
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr8
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr9
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr18_vgpr19_vgpr20_vgpr21
; GFX9-GISEL-NEXT:    s_xor_b64 exec, exec, s[2:3]
; GFX9-GISEL-NEXT:    s_cbranch_execnz .LBB17_1
; GFX9-GISEL-NEXT:  ; %bb.2:
; GFX9-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX9-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-32-SDAG-LABEL: test_waterfall_multi_end_1loop:
; GFX10-32-SDAG:       ; %bb.0:
; GFX10-32-SDAG-NEXT:    s_mov_b32 s4, exec_lo
; GFX10-32-SDAG-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v5, v2
; GFX10-32-SDAG-NEXT:    v_ashrrev_i32_e32 v4, 31, v3
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v8, v1
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v9, v0
; GFX10-32-SDAG-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; GFX10-32-SDAG-NEXT:    v_lshlrev_b64 v[2:3], 4, v[3:4]
; GFX10-32-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[5:6]
; GFX10-32-SDAG-NEXT:    v_add_co_u32 v0, vcc_lo, s0, v0
; GFX10-32-SDAG-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, s1, v1, vcc_lo
; GFX10-32-SDAG-NEXT:    v_add_co_u32 v2, vcc_lo, s2, v2
; GFX10-32-SDAG-NEXT:    v_add_co_ci_u32_e32 v3, vcc_lo, s3, v3, vcc_lo
; GFX10-32-SDAG-NEXT:    s_clause 0x1
; GFX10-32-SDAG-NEXT:    global_load_dwordx4 v[14:17], v[0:1], off offset:16
; GFX10-32-SDAG-NEXT:    global_load_dwordx4 v[10:13], v[0:1], off
; GFX10-32-SDAG-NEXT:    global_load_dwordx4 v[18:21], v[2:3], off
; GFX10-32-SDAG-NEXT:    s_mov_b32 s1, exec_lo
; GFX10-32-SDAG-NEXT:    s_mov_b32 s0, exec_lo
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-SDAG-NEXT:  .LBB17_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s2, v9
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s3, v8
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s2, v9
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s3, v8
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s8, v10
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s9, v11
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s10, v12
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s11, v13
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s12, v14
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s13, v15
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s14, v16
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s15, v17
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s16, v18
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s17, v19
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s18, v20
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s19, v21
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v8, 0
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v9, 0.5
; GFX10-32-SDAG-NEXT:    image_sample v[0:3], [v8, v8], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-32-SDAG-NEXT:    image_sample v[4:7], [v9, v9], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-32-SDAG-NEXT:    s_andn2_wrexec_b32 s1, s1
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr9
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr8
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr18_vgpr19_vgpr20_vgpr21
; GFX10-32-SDAG-NEXT:    s_cbranch_execnz .LBB17_1
; GFX10-32-SDAG-NEXT:  ; %bb.2:
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-SDAG-NEXT:    s_mov_b32 exec_lo, s0
; GFX10-32-SDAG-NEXT:    s_and_b32 exec_lo, exec_lo, s4
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-32-GISEL-LABEL: test_waterfall_multi_end_1loop:
; GFX10-32-GISEL:       ; %bb.0:
; GFX10-32-GISEL-NEXT:    s_mov_b32 s4, exec_lo
; GFX10-32-GISEL-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v4, v3
; GFX10-32-GISEL-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v8, v0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v9, v1
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v7, s3
; GFX10-32-GISEL-NEXT:    v_ashrrev_i32_e32 v5, 31, v4
; GFX10-32-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[2:3]
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v6, s2
; GFX10-32-GISEL-NEXT:    v_lshlrev_b64 v[4:5], 4, v[4:5]
; GFX10-32-GISEL-NEXT:    s_mov_b32 s1, exec_lo
; GFX10-32-GISEL-NEXT:    s_mov_b32 s0, exec_lo
; GFX10-32-GISEL-NEXT:    v_add_co_u32 v0, vcc_lo, v2, v0
; GFX10-32-GISEL-NEXT:    v_add_co_ci_u32_e32 v1, vcc_lo, v3, v1, vcc_lo
; GFX10-32-GISEL-NEXT:    v_add_co_u32 v2, vcc_lo, v6, v4
; GFX10-32-GISEL-NEXT:    v_add_co_ci_u32_e32 v3, vcc_lo, v7, v5, vcc_lo
; GFX10-32-GISEL-NEXT:    s_clause 0x1
; GFX10-32-GISEL-NEXT:    global_load_dwordx4 v[10:13], v[0:1], off
; GFX10-32-GISEL-NEXT:    global_load_dwordx4 v[14:17], v[0:1], off offset:16
; GFX10-32-GISEL-NEXT:    global_load_dwordx4 v[18:21], v[2:3], off
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:  .LBB17_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s2, v8
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s3, v9
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s2, v8
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s3, v9
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s8, v10
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s9, v11
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s10, v12
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s11, v13
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s12, v14
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s13, v15
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s14, v16
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s15, v17
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s16, v18
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s17, v19
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s18, v20
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s19, v21
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v8, 0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v9, 0.5
; GFX10-32-GISEL-NEXT:    image_sample v[0:3], [v8, v8], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-32-GISEL-NEXT:    image_sample v[4:7], [v9, v9], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-32-GISEL-NEXT:    s_andn2_wrexec_b32 s1, s1
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr8
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr9
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr18_vgpr19_vgpr20_vgpr21
; GFX10-32-GISEL-NEXT:    s_cbranch_execnz .LBB17_1
; GFX10-32-GISEL-NEXT:  ; %bb.2:
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-GISEL-NEXT:    s_mov_b32 exec_lo, s0
; GFX10-32-GISEL-NEXT:    s_and_b32 exec_lo, exec_lo, s4
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-64-SDAG-LABEL: test_waterfall_multi_end_1loop:
; GFX10-64-SDAG:       ; %bb.0:
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX10-64-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v5, v2
; GFX10-64-SDAG-NEXT:    v_ashrrev_i32_e32 v4, 31, v3
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v8, v1
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v9, v0
; GFX10-64-SDAG-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; GFX10-64-SDAG-NEXT:    v_lshlrev_b64 v[2:3], 4, v[3:4]
; GFX10-64-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[5:6]
; GFX10-64-SDAG-NEXT:    v_add_co_u32 v0, vcc, s0, v0
; GFX10-64-SDAG-NEXT:    v_add_co_ci_u32_e32 v1, vcc, s1, v1, vcc
; GFX10-64-SDAG-NEXT:    v_add_co_u32 v2, vcc, s2, v2
; GFX10-64-SDAG-NEXT:    v_add_co_ci_u32_e32 v3, vcc, s3, v3, vcc
; GFX10-64-SDAG-NEXT:    s_clause 0x1
; GFX10-64-SDAG-NEXT:    global_load_dwordx4 v[14:17], v[0:1], off offset:16
; GFX10-64-SDAG-NEXT:    global_load_dwordx4 v[10:13], v[0:1], off
; GFX10-64-SDAG-NEXT:    global_load_dwordx4 v[18:21], v[2:3], off
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-SDAG-NEXT:  .LBB17_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s6, v9
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s7, v8
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s6, v9
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s7, v8
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s8, v10
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s9, v11
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s10, v12
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s11, v13
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s12, v14
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s13, v15
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s14, v16
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s15, v17
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s16, v18
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s17, v19
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s18, v20
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s19, v21
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v8, 0
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v9, 0.5
; GFX10-64-SDAG-NEXT:    image_sample v[0:3], [v8, v8], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-64-SDAG-NEXT:    image_sample v[4:7], [v9, v9], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-64-SDAG-NEXT:    s_andn2_wrexec_b64 s[2:3], s[2:3]
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr9
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr8
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr18_vgpr19_vgpr20_vgpr21
; GFX10-64-SDAG-NEXT:    s_cbranch_execnz .LBB17_1
; GFX10-64-SDAG-NEXT:  ; %bb.2:
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX10-64-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-64-GISEL-LABEL: test_waterfall_multi_end_1loop:
; GFX10-64-GISEL:       ; %bb.0:
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX10-64-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v4, v3
; GFX10-64-GISEL-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v8, v0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v9, v1
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v7, s3
; GFX10-64-GISEL-NEXT:    v_ashrrev_i32_e32 v5, 31, v4
; GFX10-64-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[2:3]
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v6, s2
; GFX10-64-GISEL-NEXT:    v_lshlrev_b64 v[4:5], 4, v[4:5]
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX10-64-GISEL-NEXT:    v_add_co_u32 v0, vcc, v2, v0
; GFX10-64-GISEL-NEXT:    v_add_co_ci_u32_e32 v1, vcc, v3, v1, vcc
; GFX10-64-GISEL-NEXT:    v_add_co_u32 v2, vcc, v6, v4
; GFX10-64-GISEL-NEXT:    v_add_co_ci_u32_e32 v3, vcc, v7, v5, vcc
; GFX10-64-GISEL-NEXT:    s_clause 0x1
; GFX10-64-GISEL-NEXT:    global_load_dwordx4 v[10:13], v[0:1], off
; GFX10-64-GISEL-NEXT:    global_load_dwordx4 v[14:17], v[0:1], off offset:16
; GFX10-64-GISEL-NEXT:    global_load_dwordx4 v[18:21], v[2:3], off
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:  .LBB17_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s6, v8
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s7, v9
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s6, v8
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s7, v9
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s8, v10
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s9, v11
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s10, v12
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s11, v13
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s12, v14
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s13, v15
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s14, v16
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s15, v17
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s16, v18
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s17, v19
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s18, v20
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s19, v21
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v8, 0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v9, 0.5
; GFX10-64-GISEL-NEXT:    image_sample v[0:3], [v8, v8], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-64-GISEL-NEXT:    image_sample v[4:7], [v9, v9], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-64-GISEL-NEXT:    s_andn2_wrexec_b64 s[2:3], s[2:3]
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr8
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr9
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr18_vgpr19_vgpr20_vgpr21
; GFX10-64-GISEL-NEXT:    s_cbranch_execnz .LBB17_1
; GFX10-64-GISEL-NEXT:  ; %bb.2:
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX10-64-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:    ; return to shader part epilog
;
; GFX1150-SDAG-LABEL: test_waterfall_multi_end_1loop:
; GFX1150-SDAG:       ; %bb.0:
; GFX1150-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX1150-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v5, v2
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v8, v1
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v9, v0
; GFX1150-SDAG-NEXT:    v_ashrrev_i32_e32 v4, 31, v3
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX1150-SDAG-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; GFX1150-SDAG-NEXT:    v_lshlrev_b64 v[2:3], 4, v[3:4]
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX1150-SDAG-NEXT:    v_lshlrev_b64 v[0:1], 5, v[5:6]
; GFX1150-SDAG-NEXT:    v_add_co_u32 v0, vcc, s0, v0
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX1150-SDAG-NEXT:    v_add_co_ci_u32_e64 v1, null, s1, v1, vcc
; GFX1150-SDAG-NEXT:    v_add_co_u32 v2, vcc, s2, v2
; GFX1150-SDAG-NEXT:    s_waitcnt_depctr depctr_va_vcc(0)
; GFX1150-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX1150-SDAG-NEXT:    v_add_co_ci_u32_e64 v3, null, s3, v3, vcc
; GFX1150-SDAG-NEXT:    s_clause 0x1
; GFX1150-SDAG-NEXT:    global_load_b128 v[14:17], v[0:1], off offset:16
; GFX1150-SDAG-NEXT:    global_load_b128 v[10:13], v[0:1], off
; GFX1150-SDAG-NEXT:    global_load_b128 v[18:21], v[2:3], off
; GFX1150-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX1150-SDAG-NEXT:  .LBB17_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s6, v9
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s7, v8
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s6, v9
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s7, v8
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(1)
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s8, v10
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s9, v11
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s10, v12
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s11, v13
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s12, v14
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s13, v15
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s14, v16
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s15, v17
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s16, v18
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s17, v19
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s18, v20
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s19, v21
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v4, 0.5
; GFX1150-SDAG-NEXT:    s_clause 0x1
; GFX1150-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX1150-SDAG-NEXT:    image_sample v[4:7], [v4, v4], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX1150-SDAG-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr9
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr8
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr18_vgpr19_vgpr20_vgpr21
; GFX1150-SDAG-NEXT:    s_cbranch_execnz .LBB17_1
; GFX1150-SDAG-NEXT:  ; %bb.2:
; GFX1150-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:    ; return to shader part epilog
;
; GFX1150-GISEL-LABEL: test_waterfall_multi_end_1loop:
; GFX1150-GISEL:       ; %bb.0:
; GFX1150-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX1150-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v4, v3
; GFX1150-GISEL-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v8, v0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v9, v1
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v7, s3
; GFX1150-GISEL-NEXT:    v_ashrrev_i32_e32 v5, 31, v4
; GFX1150-GISEL-NEXT:    v_lshlrev_b64 v[0:1], 5, v[2:3]
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v6, s2
; GFX1150-GISEL-NEXT:    v_lshlrev_b64 v[4:5], 4, v[4:5]
; GFX1150-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX1150-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX1150-GISEL-NEXT:    v_add_co_u32 v0, vcc, v2, v0
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX1150-GISEL-NEXT:    v_add_co_ci_u32_e64 v1, null, v3, v1, vcc
; GFX1150-GISEL-NEXT:    v_add_co_u32 v2, vcc, v6, v4
; GFX1150-GISEL-NEXT:    s_waitcnt_depctr depctr_va_vcc(0)
; GFX1150-GISEL-NEXT:    v_add_co_ci_u32_e64 v3, null, v7, v5, vcc
; GFX1150-GISEL-NEXT:    s_clause 0x1
; GFX1150-GISEL-NEXT:    global_load_b128 v[10:13], v[0:1], off
; GFX1150-GISEL-NEXT:    global_load_b128 v[14:17], v[0:1], off offset:16
; GFX1150-GISEL-NEXT:    global_load_b128 v[18:21], v[2:3], off
; GFX1150-GISEL-NEXT:  .LBB17_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s6, v8
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s7, v9
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s6, v8
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s7, v9
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(2)
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s8, v10
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s9, v11
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s10, v12
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s11, v13
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(1)
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s12, v14
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s13, v15
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s14, v16
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s15, v17
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s16, v18
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s17, v19
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s18, v20
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s19, v21
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v4, 0.5
; GFX1150-GISEL-NEXT:    s_clause 0x1
; GFX1150-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX1150-GISEL-NEXT:    image_sample v[4:7], [v4, v4], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX1150-GISEL-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr8
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr9
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr18_vgpr19_vgpr20_vgpr21
; GFX1150-GISEL-NEXT:    s_cbranch_execnz .LBB17_1
; GFX1150-GISEL-NEXT:  ; %bb.2:
; GFX1150-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    ; return to shader part epilog
;
; GFX12-SDAG-LABEL: test_waterfall_multi_end_1loop:
; GFX12-SDAG:       ; %bb.0:
; GFX12-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX12-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v5, v2
; GFX12-SDAG-NEXT:    v_ashrrev_i32_e32 v4, 31, v3
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v8, v1
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v9, v0
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_4) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX12-SDAG-NEXT:    v_ashrrev_i32_e32 v6, 31, v5
; GFX12-SDAG-NEXT:    v_lshlrev_b64_e32 v[2:3], 4, v[3:4]
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX12-SDAG-NEXT:    v_lshlrev_b64_e32 v[0:1], 5, v[5:6]
; GFX12-SDAG-NEXT:    v_add_co_u32 v0, vcc, s0, v0
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_4)
; GFX12-SDAG-NEXT:    v_add_co_ci_u32_e64 v1, null, s1, v1, vcc
; GFX12-SDAG-NEXT:    v_add_co_u32 v2, vcc, s2, v2
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_vcc(0)
; GFX12-SDAG-NEXT:    v_add_co_ci_u32_e64 v3, null, s3, v3, vcc
; GFX12-SDAG-NEXT:    s_clause 0x1
; GFX12-SDAG-NEXT:    global_load_b128 v[14:17], v[0:1], off offset:16
; GFX12-SDAG-NEXT:    global_load_b128 v[10:13], v[0:1], off
; GFX12-SDAG-NEXT:    global_load_b128 v[18:21], v[2:3], off
; GFX12-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX12-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX12-SDAG-NEXT:  .LBB17_1: ; =>This Inner Loop Header: Depth=1
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s6, v9
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s7, v8
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s6, v9
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s7, v8
; GFX12-SDAG-NEXT:    s_wait_loadcnt 0x1
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s8, v10
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s9, v11
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s10, v12
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s11, v13
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s12, v14
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s13, v15
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s14, v16
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s15, v17
; GFX12-SDAG-NEXT:    s_wait_loadcnt 0x0
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s16, v18
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s17, v19
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s18, v20
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s19, v21
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x1
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v4, 0.5
; GFX12-SDAG-NEXT:    s_clause 0x1
; GFX12-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX12-SDAG-NEXT:    image_sample v[4:7], [v4, v4], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX12-SDAG-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr9
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr8
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr18_vgpr19_vgpr20_vgpr21
; GFX12-SDAG-NEXT:    s_cbranch_execnz .LBB17_1
; GFX12-SDAG-NEXT:  ; %bb.2:
; GFX12-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX12-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-SDAG-NEXT:    ; return to shader part epilog
;
; GFX12-GISEL-LABEL: test_waterfall_multi_end_1loop:
; GFX12-GISEL:       ; %bb.0:
; GFX12-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX12-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v4, v3
; GFX12-GISEL-NEXT:    v_ashrrev_i32_e32 v3, 31, v2
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v8, v0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v9, v1
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v7, s3
; GFX12-GISEL-NEXT:    v_ashrrev_i32_e32 v5, 31, v4
; GFX12-GISEL-NEXT:    v_lshlrev_b64_e32 v[0:1], 5, v[2:3]
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v3, s1
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v2, s0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v6, s2
; GFX12-GISEL-NEXT:    v_lshlrev_b64_e32 v[4:5], 4, v[4:5]
; GFX12-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX12-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX12-GISEL-NEXT:    v_add_co_u32 v0, vcc, v2, v0
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_3)
; GFX12-GISEL-NEXT:    v_add_co_ci_u32_e64 v1, null, v3, v1, vcc
; GFX12-GISEL-NEXT:    v_add_co_u32 v2, vcc, v6, v4
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_vcc(0)
; GFX12-GISEL-NEXT:    v_add_co_ci_u32_e64 v3, null, v7, v5, vcc
; GFX12-GISEL-NEXT:    s_clause 0x1
; GFX12-GISEL-NEXT:    global_load_b128 v[10:13], v[0:1], off
; GFX12-GISEL-NEXT:    global_load_b128 v[14:17], v[0:1], off offset:16
; GFX12-GISEL-NEXT:    global_load_b128 v[18:21], v[2:3], off
; GFX12-GISEL-NEXT:  .LBB17_1: ; =>This Inner Loop Header: Depth=1
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s6, v8
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s7, v9
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s6, v8
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s7, v9
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x2
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s8, v10
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s9, v11
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s10, v12
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s11, v13
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x1
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s12, v14
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s13, v15
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s14, v16
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s15, v17
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x0
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s16, v18
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s17, v19
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s18, v20
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s19, v21
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x1
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v4, 0.5
; GFX12-GISEL-NEXT:    s_clause 0x1
; GFX12-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX12-GISEL-NEXT:    image_sample v[4:7], [v4, v4], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX12-GISEL-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr8
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr9
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr10_vgpr11_vgpr12_vgpr13_vgpr14_vgpr15_vgpr16_vgpr17
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr18_vgpr19_vgpr20_vgpr21
; GFX12-GISEL-NEXT:    s_cbranch_execnz .LBB17_1
; GFX12-GISEL-NEXT:  ; %bb.2:
; GFX12-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX12-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-GISEL-NEXT:    ; return to shader part epilog
       <8 x i32> addrspace(4)* inreg %in, <4 x i32> addrspace(4)* inreg %s_in,
       i32 %idx1, i32 %idx2, i32 %s_idx, i32 %s_idx2, { <4 x float>, <4 x float> } %dummy) #1 {
  %rptr = getelementptr <8 x i32>, <8 x i32> addrspace(4)* %in, i32 %s_idx
  %sptr = getelementptr <4 x i32>, <4 x i32> addrspace(4)* %s_in, i32 %s_idx2
  %rsrc = load <8 x i32>, <8 x i32> addrspace(4)* %rptr, align 16
  %srsrc = load <4 x i32>, <4 x i32> addrspace(4)* %sptr, align 16
  %tok = call token @llvm.amdgcn.waterfall.begin.i32(token poison, i32 %idx1)
  %tok1 = call token @llvm.amdgcn.waterfall.begin.i32(token %tok, i32 %idx2)
  %s_rsrc = call <8 x i32> @llvm.amdgcn.waterfall.readfirstlane.v8i32.v8i32(token %tok1, <8 x i32> %rsrc)
  %s_srsrc = call <4 x i32> @llvm.amdgcn.waterfall.readfirstlane.v4i32.v4i32(token %tok1, <4 x i32> %srsrc)
  %r = call <4 x float> @llvm.amdgcn.image.sample.2d.v4f32.f32(i32 15, float 0.000000e+00, float 0.000000e+00, <8 x i32> %s_rsrc, <4 x i32> %s_srsrc, i1 false, i32 0, i32 0)
  %r2 = call <4 x float> @llvm.amdgcn.image.sample.2d.v4f32.f32(i32 15, float 0.500000e+00, float 0.500000e+00, <8 x i32> %s_rsrc, <4 x i32> %s_srsrc, i1 false, i32 0, i32 0)
  %r1 = call <4 x float> @llvm.amdgcn.waterfall.end.v4f32(token %tok1, <4 x float> %r)
  %r3 = call <4 x float> @llvm.amdgcn.waterfall.end.v4f32(token %tok1, <4 x float> %r2)

  %insert = insertvalue { <4 x float>, <4 x float> } %dummy, <4 x float> %r1, 0
  %insert1 = insertvalue { <4 x float>, <4 x float> } %insert, <4 x float> %r3, 1
  ret {<4 x float> , <4 x float>} %insert1
}

define amdgpu_ps {<4 x float>,<4 x float>} @test_waterfall_multi_end_1loop_rsrc_load_inside(
; VI-SDAG-LABEL: test_waterfall_multi_end_1loop_rsrc_load_inside:
; VI-SDAG:       ; %bb.0:
; VI-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; VI-SDAG-NEXT:    s_wqm_b64 exec, exec
; VI-SDAG-NEXT:    v_mov_b32_e32 v8, v3
; VI-SDAG-NEXT:    v_mov_b32_e32 v9, v2
; VI-SDAG-NEXT:    v_mov_b32_e32 v10, v1
; VI-SDAG-NEXT:    v_mov_b32_e32 v11, v0
; VI-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; VI-SDAG-NEXT:  .LBB18_1: ; =>This Inner Loop Header: Depth=1
; VI-SDAG-NEXT:    v_readfirstlane_b32 s8, v11
; VI-SDAG-NEXT:    v_readfirstlane_b32 s10, v10
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[8:9], s8, v11
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[10:11], s10, v10
; VI-SDAG-NEXT:    s_and_b64 s[8:9], s[8:9], s[10:11]
; VI-SDAG-NEXT:    s_and_saveexec_b64 s[20:21], s[8:9]
; VI-SDAG-NEXT:    v_readfirstlane_b32 s8, v9
; VI-SDAG-NEXT:    v_readfirstlane_b32 s10, v8
; VI-SDAG-NEXT:    s_ashr_i32 s9, s8, 31
; VI-SDAG-NEXT:    s_ashr_i32 s11, s10, 31
; VI-SDAG-NEXT:    s_lshl_b64 s[8:9], s[8:9], 5
; VI-SDAG-NEXT:    s_add_u32 s8, s0, s8
; VI-SDAG-NEXT:    s_addc_u32 s9, s1, s9
; VI-SDAG-NEXT:    s_lshl_b64 s[10:11], s[10:11], 4
; VI-SDAG-NEXT:    s_add_u32 s16, s2, s10
; VI-SDAG-NEXT:    s_addc_u32 s17, s3, s11
; VI-SDAG-NEXT:    s_load_dwordx8 s[8:15], s[8:9], 0x0
; VI-SDAG-NEXT:    s_load_dwordx4 s[16:19], s[16:17], 0x0
; VI-SDAG-NEXT:    s_waitcnt vmcnt(1)
; VI-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    v_mov_b32_e32 v4, 0.5
; VI-SDAG-NEXT:    v_mov_b32_e32 v1, v0
; VI-SDAG-NEXT:    v_mov_b32_e32 v5, v4
; VI-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; VI-SDAG-NEXT:    image_sample v[0:3], v[0:1], s[8:15], s[16:19] dmask:0xf
; VI-SDAG-NEXT:    image_sample v[4:7], v[4:5], s[8:15], s[16:19] dmask:0xf
; VI-SDAG-NEXT:    ; implicit-def: $vgpr11
; VI-SDAG-NEXT:    ; implicit-def: $vgpr10
; VI-SDAG-NEXT:    ; implicit-def: $vgpr9
; VI-SDAG-NEXT:    ; implicit-def: $vgpr8
; VI-SDAG-NEXT:    s_xor_b64 exec, exec, s[20:21]
; VI-SDAG-NEXT:    s_cbranch_execnz .LBB18_1
; VI-SDAG-NEXT:  ; %bb.2:
; VI-SDAG-NEXT:    s_mov_b64 exec, s[6:7]
; VI-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    ; return to shader part epilog
;
; VI-GISEL-LABEL: test_waterfall_multi_end_1loop_rsrc_load_inside:
; VI-GISEL:       ; %bb.0:
; VI-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; VI-GISEL-NEXT:    s_wqm_b64 exec, exec
; VI-GISEL-NEXT:    v_mov_b32_e32 v8, v0
; VI-GISEL-NEXT:    v_mov_b32_e32 v11, v1
; VI-GISEL-NEXT:    v_mov_b32_e32 v9, v2
; VI-GISEL-NEXT:    v_mov_b32_e32 v10, v3
; VI-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; VI-GISEL-NEXT:  .LBB18_1: ; =>This Inner Loop Header: Depth=1
; VI-GISEL-NEXT:    v_readfirstlane_b32 s8, v8
; VI-GISEL-NEXT:    v_readfirstlane_b32 s10, v11
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[8:9], s8, v8
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[10:11], s10, v11
; VI-GISEL-NEXT:    s_and_b64 s[8:9], s[8:9], s[10:11]
; VI-GISEL-NEXT:    s_and_saveexec_b64 s[20:21], s[8:9]
; VI-GISEL-NEXT:    v_readfirstlane_b32 s8, v9
; VI-GISEL-NEXT:    v_readfirstlane_b32 s10, v10
; VI-GISEL-NEXT:    s_ashr_i32 s9, s8, 31
; VI-GISEL-NEXT:    s_ashr_i32 s11, s10, 31
; VI-GISEL-NEXT:    s_lshl_b64 s[8:9], s[8:9], 5
; VI-GISEL-NEXT:    s_add_u32 s8, s0, s8
; VI-GISEL-NEXT:    s_addc_u32 s9, s1, s9
; VI-GISEL-NEXT:    s_lshl_b64 s[10:11], s[10:11], 4
; VI-GISEL-NEXT:    s_add_u32 s16, s2, s10
; VI-GISEL-NEXT:    s_addc_u32 s17, s3, s11
; VI-GISEL-NEXT:    s_load_dwordx8 s[8:15], s[8:9], 0x0
; VI-GISEL-NEXT:    s_load_dwordx4 s[16:19], s[16:17], 0x0
; VI-GISEL-NEXT:    s_mov_b32 s22, 0
; VI-GISEL-NEXT:    s_mov_b32 s23, s22
; VI-GISEL-NEXT:    s_waitcnt vmcnt(1)
; VI-GISEL-NEXT:    v_mov_b32_e32 v0, s22
; VI-GISEL-NEXT:    v_mov_b32_e32 v1, s23
; VI-GISEL-NEXT:    s_mov_b32 s22, 0.5
; VI-GISEL-NEXT:    s_mov_b32 s23, s22
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    v_mov_b32_e32 v4, s22
; VI-GISEL-NEXT:    v_mov_b32_e32 v5, s23
; VI-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; VI-GISEL-NEXT:    image_sample v[0:3], v[0:1], s[8:15], s[16:19] dmask:0xf
; VI-GISEL-NEXT:    image_sample v[4:7], v[4:5], s[8:15], s[16:19] dmask:0xf
; VI-GISEL-NEXT:    ; implicit-def: $vgpr8
; VI-GISEL-NEXT:    ; implicit-def: $vgpr11
; VI-GISEL-NEXT:    ; implicit-def: $vgpr9
; VI-GISEL-NEXT:    ; implicit-def: $vgpr10
; VI-GISEL-NEXT:    s_xor_b64 exec, exec, s[20:21]
; VI-GISEL-NEXT:    s_cbranch_execnz .LBB18_1
; VI-GISEL-NEXT:  ; %bb.2:
; VI-GISEL-NEXT:    s_mov_b64 exec, s[6:7]
; VI-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    ; return to shader part epilog
;
; GFX9-SDAG-LABEL: test_waterfall_multi_end_1loop_rsrc_load_inside:
; GFX9-SDAG:       ; %bb.0:
; GFX9-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX9-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v8, v3
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v9, v2
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v10, v1
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v11, v0
; GFX9-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; GFX9-SDAG-NEXT:  .LBB18_1: ; =>This Inner Loop Header: Depth=1
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s8, v11
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s10, v10
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[8:9], s8, v11
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[10:11], s10, v10
; GFX9-SDAG-NEXT:    s_and_b64 s[8:9], s[8:9], s[10:11]
; GFX9-SDAG-NEXT:    s_and_saveexec_b64 s[20:21], s[8:9]
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s8, v9
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s10, v8
; GFX9-SDAG-NEXT:    s_ashr_i32 s9, s8, 31
; GFX9-SDAG-NEXT:    s_ashr_i32 s11, s10, 31
; GFX9-SDAG-NEXT:    s_lshl_b64 s[8:9], s[8:9], 5
; GFX9-SDAG-NEXT:    s_add_u32 s22, s0, s8
; GFX9-SDAG-NEXT:    s_addc_u32 s23, s1, s9
; GFX9-SDAG-NEXT:    s_lshl_b64 s[8:9], s[10:11], 4
; GFX9-SDAG-NEXT:    s_add_u32 s24, s2, s8
; GFX9-SDAG-NEXT:    s_addc_u32 s25, s3, s9
; GFX9-SDAG-NEXT:    s_load_dwordx8 s[8:15], s[22:23], 0x0
; GFX9-SDAG-NEXT:    s_load_dwordx4 s[16:19], s[24:25], 0x0
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v8, 0
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v9, v8
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v10, 0.5
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v11, v10
; GFX9-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; GFX9-SDAG-NEXT:    image_sample v[0:3], v[8:9], s[8:15], s[16:19] dmask:0xf
; GFX9-SDAG-NEXT:    image_sample v[4:7], v[10:11], s[8:15], s[16:19] dmask:0xf
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr11
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr10
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr9
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr8
; GFX9-SDAG-NEXT:    s_xor_b64 exec, exec, s[20:21]
; GFX9-SDAG-NEXT:    s_cbranch_execnz .LBB18_1
; GFX9-SDAG-NEXT:  ; %bb.2:
; GFX9-SDAG-NEXT:    s_mov_b64 exec, s[6:7]
; GFX9-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    ; return to shader part epilog
;
; GFX9-GISEL-LABEL: test_waterfall_multi_end_1loop_rsrc_load_inside:
; GFX9-GISEL:       ; %bb.0:
; GFX9-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX9-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v8, v0
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v11, v1
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v9, v2
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v10, v3
; GFX9-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX9-GISEL-NEXT:  .LBB18_1: ; =>This Inner Loop Header: Depth=1
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s8, v8
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s10, v11
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[8:9], s8, v8
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[10:11], s10, v11
; GFX9-GISEL-NEXT:    s_and_b64 s[8:9], s[8:9], s[10:11]
; GFX9-GISEL-NEXT:    s_and_saveexec_b64 s[20:21], s[8:9]
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s8, v9
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s10, v10
; GFX9-GISEL-NEXT:    s_ashr_i32 s9, s8, 31
; GFX9-GISEL-NEXT:    s_ashr_i32 s11, s10, 31
; GFX9-GISEL-NEXT:    s_lshl_b64 s[8:9], s[8:9], 5
; GFX9-GISEL-NEXT:    s_add_u32 s22, s0, s8
; GFX9-GISEL-NEXT:    s_addc_u32 s23, s1, s9
; GFX9-GISEL-NEXT:    s_lshl_b64 s[8:9], s[10:11], 4
; GFX9-GISEL-NEXT:    s_add_u32 s24, s2, s8
; GFX9-GISEL-NEXT:    s_addc_u32 s25, s3, s9
; GFX9-GISEL-NEXT:    s_load_dwordx8 s[8:15], s[22:23], 0x0
; GFX9-GISEL-NEXT:    s_load_dwordx4 s[16:19], s[24:25], 0x0
; GFX9-GISEL-NEXT:    s_mov_b32 s22, 0
; GFX9-GISEL-NEXT:    s_mov_b32 s23, s22
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v8, s22
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v9, s23
; GFX9-GISEL-NEXT:    s_mov_b32 s22, 0.5
; GFX9-GISEL-NEXT:    s_mov_b32 s23, s22
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v10, s22
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v11, s23
; GFX9-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; GFX9-GISEL-NEXT:    image_sample v[0:3], v[8:9], s[8:15], s[16:19] dmask:0xf
; GFX9-GISEL-NEXT:    image_sample v[4:7], v[10:11], s[8:15], s[16:19] dmask:0xf
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr8
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr11
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr9
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr10
; GFX9-GISEL-NEXT:    s_xor_b64 exec, exec, s[20:21]
; GFX9-GISEL-NEXT:    s_cbranch_execnz .LBB18_1
; GFX9-GISEL-NEXT:  ; %bb.2:
; GFX9-GISEL-NEXT:    s_mov_b64 exec, s[6:7]
; GFX9-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-32-SDAG-LABEL: test_waterfall_multi_end_1loop_rsrc_load_inside:
; GFX10-32-SDAG:       ; %bb.0:
; GFX10-32-SDAG-NEXT:    s_mov_b32 s4, exec_lo
; GFX10-32-SDAG-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v8, v3
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v9, v2
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v10, v1
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v11, v0
; GFX10-32-SDAG-NEXT:    s_mov_b32 s6, exec_lo
; GFX10-32-SDAG-NEXT:    s_mov_b32 s5, exec_lo
; GFX10-32-SDAG-NEXT:  .LBB18_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s7, v11
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s8, v10
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s7, v11
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s8, v10
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s8, v9
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s10, v8
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v8, 0
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v9, 0.5
; GFX10-32-SDAG-NEXT:    s_ashr_i32 s9, s8, 31
; GFX10-32-SDAG-NEXT:    s_ashr_i32 s11, s10, 31
; GFX10-32-SDAG-NEXT:    s_lshl_b64 s[8:9], s[8:9], 5
; GFX10-32-SDAG-NEXT:    s_add_u32 s20, s0, s8
; GFX10-32-SDAG-NEXT:    s_addc_u32 s21, s1, s9
; GFX10-32-SDAG-NEXT:    s_lshl_b64 s[8:9], s[10:11], 4
; GFX10-32-SDAG-NEXT:    s_add_u32 s22, s2, s8
; GFX10-32-SDAG-NEXT:    s_addc_u32 s23, s3, s9
; GFX10-32-SDAG-NEXT:    s_load_dwordx8 s[8:15], s[20:21], 0x0
; GFX10-32-SDAG-NEXT:    s_load_dwordx4 s[16:19], s[22:23], 0x0
; GFX10-32-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-32-SDAG-NEXT:    image_sample v[0:3], [v8, v8], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-32-SDAG-NEXT:    image_sample v[4:7], [v9, v9], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-32-SDAG-NEXT:    s_andn2_wrexec_b32 s6, s6
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr11
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr10
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr9
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr8
; GFX10-32-SDAG-NEXT:    s_cbranch_execnz .LBB18_1
; GFX10-32-SDAG-NEXT:  ; %bb.2:
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-SDAG-NEXT:    s_mov_b32 exec_lo, s5
; GFX10-32-SDAG-NEXT:    s_and_b32 exec_lo, exec_lo, s4
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-32-GISEL-LABEL: test_waterfall_multi_end_1loop_rsrc_load_inside:
; GFX10-32-GISEL:       ; %bb.0:
; GFX10-32-GISEL-NEXT:    s_mov_b32 s4, exec_lo
; GFX10-32-GISEL-NEXT:    s_wqm_b32 exec_lo, exec_lo
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v8, v0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v9, v1
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v10, v2
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v11, v3
; GFX10-32-GISEL-NEXT:    s_mov_b32 s6, exec_lo
; GFX10-32-GISEL-NEXT:    s_mov_b32 s5, exec_lo
; GFX10-32-GISEL-NEXT:  .LBB18_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s7, v8
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s8, v9
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s7, v8
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s8, v9
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s8, v10
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s10, v11
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v8, 0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v9, 0.5
; GFX10-32-GISEL-NEXT:    s_ashr_i32 s9, s8, 31
; GFX10-32-GISEL-NEXT:    s_ashr_i32 s11, s10, 31
; GFX10-32-GISEL-NEXT:    s_lshl_b64 s[8:9], s[8:9], 5
; GFX10-32-GISEL-NEXT:    s_add_u32 s20, s0, s8
; GFX10-32-GISEL-NEXT:    s_addc_u32 s21, s1, s9
; GFX10-32-GISEL-NEXT:    s_lshl_b64 s[8:9], s[10:11], 4
; GFX10-32-GISEL-NEXT:    s_add_u32 s22, s2, s8
; GFX10-32-GISEL-NEXT:    s_addc_u32 s23, s3, s9
; GFX10-32-GISEL-NEXT:    s_load_dwordx8 s[8:15], s[20:21], 0x0
; GFX10-32-GISEL-NEXT:    s_load_dwordx4 s[16:19], s[22:23], 0x0
; GFX10-32-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-32-GISEL-NEXT:    image_sample v[0:3], [v8, v8], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-32-GISEL-NEXT:    image_sample v[4:7], [v9, v9], s[8:15], s[16:19] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-32-GISEL-NEXT:    s_andn2_wrexec_b32 s6, s6
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr8
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr9
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr10
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr11
; GFX10-32-GISEL-NEXT:    s_cbranch_execnz .LBB18_1
; GFX10-32-GISEL-NEXT:  ; %bb.2:
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-GISEL-NEXT:    s_mov_b32 exec_lo, s5
; GFX10-32-GISEL-NEXT:    s_and_b32 exec_lo, exec_lo, s4
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-64-SDAG-LABEL: test_waterfall_multi_end_1loop_rsrc_load_inside:
; GFX10-64-SDAG:       ; %bb.0:
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX10-64-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v8, v3
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v9, v2
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v10, v1
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v11, v0
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; GFX10-64-SDAG-NEXT:  .LBB18_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s10, v11
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s11, v10
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s10, v11
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s11, v10
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s10, v9
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s12, v8
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v8, 0
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v9, 0.5
; GFX10-64-SDAG-NEXT:    s_ashr_i32 s11, s10, 31
; GFX10-64-SDAG-NEXT:    s_ashr_i32 s13, s12, 31
; GFX10-64-SDAG-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; GFX10-64-SDAG-NEXT:    s_add_u32 s10, s0, s10
; GFX10-64-SDAG-NEXT:    s_addc_u32 s11, s1, s11
; GFX10-64-SDAG-NEXT:    s_lshl_b64 s[12:13], s[12:13], 4
; GFX10-64-SDAG-NEXT:    s_add_u32 s24, s2, s12
; GFX10-64-SDAG-NEXT:    s_addc_u32 s25, s3, s13
; GFX10-64-SDAG-NEXT:    s_load_dwordx8 s[12:19], s[10:11], 0x0
; GFX10-64-SDAG-NEXT:    s_load_dwordx4 s[20:23], s[24:25], 0x0
; GFX10-64-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-64-SDAG-NEXT:    image_sample v[0:3], [v8, v8], s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-64-SDAG-NEXT:    image_sample v[4:7], [v9, v9], s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-64-SDAG-NEXT:    s_andn2_wrexec_b64 s[8:9], s[8:9]
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr11
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr10
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr9
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr8
; GFX10-64-SDAG-NEXT:    s_cbranch_execnz .LBB18_1
; GFX10-64-SDAG-NEXT:  ; %bb.2:
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-SDAG-NEXT:    s_mov_b64 exec, s[6:7]
; GFX10-64-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-64-GISEL-LABEL: test_waterfall_multi_end_1loop_rsrc_load_inside:
; GFX10-64-GISEL:       ; %bb.0:
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX10-64-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v8, v0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v9, v1
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v10, v2
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v11, v3
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[8:9], exec
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX10-64-GISEL-NEXT:  .LBB18_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s10, v8
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s11, v9
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s10, v8
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s11, v9
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s10, v10
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s12, v11
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v8, 0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v9, 0.5
; GFX10-64-GISEL-NEXT:    s_ashr_i32 s11, s10, 31
; GFX10-64-GISEL-NEXT:    s_ashr_i32 s13, s12, 31
; GFX10-64-GISEL-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; GFX10-64-GISEL-NEXT:    s_add_u32 s10, s0, s10
; GFX10-64-GISEL-NEXT:    s_addc_u32 s11, s1, s11
; GFX10-64-GISEL-NEXT:    s_lshl_b64 s[12:13], s[12:13], 4
; GFX10-64-GISEL-NEXT:    s_add_u32 s24, s2, s12
; GFX10-64-GISEL-NEXT:    s_addc_u32 s25, s3, s13
; GFX10-64-GISEL-NEXT:    s_load_dwordx8 s[12:19], s[10:11], 0x0
; GFX10-64-GISEL-NEXT:    s_load_dwordx4 s[20:23], s[24:25], 0x0
; GFX10-64-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; GFX10-64-GISEL-NEXT:    image_sample v[0:3], [v8, v8], s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-64-GISEL-NEXT:    image_sample v[4:7], [v9, v9], s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX10-64-GISEL-NEXT:    s_andn2_wrexec_b64 s[8:9], s[8:9]
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr8
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr9
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr10
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr11
; GFX10-64-GISEL-NEXT:    s_cbranch_execnz .LBB18_1
; GFX10-64-GISEL-NEXT:  ; %bb.2:
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-GISEL-NEXT:    s_mov_b64 exec, s[6:7]
; GFX10-64-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:    ; return to shader part epilog
;
; GFX1150-SDAG-LABEL: test_waterfall_multi_end_1loop_rsrc_load_inside:
; GFX1150-SDAG:       ; %bb.0:
; GFX1150-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX1150-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v8, v3
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v9, v2
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v10, v1
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v11, v0
; GFX1150-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX1150-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; GFX1150-SDAG-NEXT:  .LBB18_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_2)
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s10, v11
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s11, v10
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s10, v11
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s11, v10
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s10, v9
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s12, v8
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(1)
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v4, 0.5
; GFX1150-SDAG-NEXT:    s_ashr_i32 s11, s10, 31
; GFX1150-SDAG-NEXT:    s_ashr_i32 s13, s12, 31
; GFX1150-SDAG-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(SKIP_2) | instid1(SALU_CYCLE_1)
; GFX1150-SDAG-NEXT:    s_add_u32 s10, s0, s10
; GFX1150-SDAG-NEXT:    s_addc_u32 s11, s1, s11
; GFX1150-SDAG-NEXT:    s_lshl_b64 s[12:13], s[12:13], 4
; GFX1150-SDAG-NEXT:    s_add_u32 s20, s2, s12
; GFX1150-SDAG-NEXT:    s_addc_u32 s21, s3, s13
; GFX1150-SDAG-NEXT:    s_load_b256 s[12:19], s[10:11], 0x0
; GFX1150-SDAG-NEXT:    s_load_b128 s[20:23], s[20:21], 0x0
; GFX1150-SDAG-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1150-SDAG-NEXT:    s_clause 0x1
; GFX1150-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX1150-SDAG-NEXT:    image_sample v[4:7], [v4, v4], s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX1150-SDAG-NEXT:    s_and_not1_wrexec_b64 s[8:9], s[8:9]
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr11
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr10
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr9
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr8
; GFX1150-SDAG-NEXT:    s_cbranch_execnz .LBB18_1
; GFX1150-SDAG-NEXT:  ; %bb.2:
; GFX1150-SDAG-NEXT:    s_mov_b64 exec, s[6:7]
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:    ; return to shader part epilog
;
; GFX1150-GISEL-LABEL: test_waterfall_multi_end_1loop_rsrc_load_inside:
; GFX1150-GISEL:       ; %bb.0:
; GFX1150-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX1150-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v8, v0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v9, v1
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v10, v2
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v11, v3
; GFX1150-GISEL-NEXT:    s_mov_b64 s[8:9], exec
; GFX1150-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX1150-GISEL-NEXT:  .LBB18_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s10, v8
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s11, v9
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s10, v8
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s11, v9
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s10, v10
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s12, v11
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(1)
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v4, 0.5
; GFX1150-GISEL-NEXT:    s_ashr_i32 s11, s10, 31
; GFX1150-GISEL-NEXT:    s_ashr_i32 s13, s12, 31
; GFX1150-GISEL-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(SKIP_2) | instid1(SALU_CYCLE_1)
; GFX1150-GISEL-NEXT:    s_add_u32 s10, s0, s10
; GFX1150-GISEL-NEXT:    s_addc_u32 s11, s1, s11
; GFX1150-GISEL-NEXT:    s_lshl_b64 s[12:13], s[12:13], 4
; GFX1150-GISEL-NEXT:    s_add_u32 s20, s2, s12
; GFX1150-GISEL-NEXT:    s_addc_u32 s21, s3, s13
; GFX1150-GISEL-NEXT:    s_load_b256 s[12:19], s[10:11], 0x0
; GFX1150-GISEL-NEXT:    s_load_b128 s[20:23], s[20:21], 0x0
; GFX1150-GISEL-NEXT:    s_waitcnt lgkmcnt(0)
; GFX1150-GISEL-NEXT:    s_clause 0x1
; GFX1150-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX1150-GISEL-NEXT:    image_sample v[4:7], [v4, v4], s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX1150-GISEL-NEXT:    s_and_not1_wrexec_b64 s[8:9], s[8:9]
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr8
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr9
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr10
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr11
; GFX1150-GISEL-NEXT:    s_cbranch_execnz .LBB18_1
; GFX1150-GISEL-NEXT:  ; %bb.2:
; GFX1150-GISEL-NEXT:    s_mov_b64 exec, s[6:7]
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX1150-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    ; return to shader part epilog
;
; GFX12-SDAG-LABEL: test_waterfall_multi_end_1loop_rsrc_load_inside:
; GFX12-SDAG:       ; %bb.0:
; GFX12-SDAG-NEXT:    s_mov_b64 s[4:5], exec
; GFX12-SDAG-NEXT:    s_wqm_b64 exec, exec
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v8, v3
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v9, v2
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v10, v1
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v11, v0
; GFX12-SDAG-NEXT:    s_mov_b64 s[8:9], exec
; GFX12-SDAG-NEXT:    s_mov_b64 s[6:7], exec
; GFX12-SDAG-NEXT:  .LBB18_1: ; =>This Inner Loop Header: Depth=1
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_2) | instid1(VALU_DEP_2)
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s10, v11
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s11, v10
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s10, v11
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s11, v10
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s10, v9
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s12, v8
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x1
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v4, 0.5
; GFX12-SDAG-NEXT:    s_ashr_i32 s11, s10, 31
; GFX12-SDAG-NEXT:    s_ashr_i32 s13, s12, 31
; GFX12-SDAG-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-SDAG-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; GFX12-SDAG-NEXT:    s_lshl_b64 s[12:13], s[12:13], 4
; GFX12-SDAG-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-SDAG-NEXT:    s_add_nc_u64 s[10:11], s[0:1], s[10:11]
; GFX12-SDAG-NEXT:    s_add_nc_u64 s[20:21], s[2:3], s[12:13]
; GFX12-SDAG-NEXT:    s_load_b256 s[12:19], s[10:11], 0x0
; GFX12-SDAG-NEXT:    s_load_b128 s[20:23], s[20:21], 0x0
; GFX12-SDAG-NEXT:    s_wait_kmcnt 0x0
; GFX12-SDAG-NEXT:    s_clause 0x1
; GFX12-SDAG-NEXT:    image_sample v[0:3], [v0, v0], s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX12-SDAG-NEXT:    image_sample v[4:7], [v4, v4], s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX12-SDAG-NEXT:    s_and_not1_wrexec_b64 s[8:9], s[8:9]
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr11
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr10
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr9
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr8
; GFX12-SDAG-NEXT:    s_cbranch_execnz .LBB18_1
; GFX12-SDAG-NEXT:  ; %bb.2:
; GFX12-SDAG-NEXT:    s_mov_b64 exec, s[6:7]
; GFX12-SDAG-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-SDAG-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX12-SDAG-NEXT:    s_wait_samplecnt 0x0
; GFX12-SDAG-NEXT:    ; return to shader part epilog
;
; GFX12-GISEL-LABEL: test_waterfall_multi_end_1loop_rsrc_load_inside:
; GFX12-GISEL:       ; %bb.0:
; GFX12-GISEL-NEXT:    s_mov_b64 s[4:5], exec
; GFX12-GISEL-NEXT:    s_wqm_b64 exec, exec
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v8, v0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v9, v1
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v10, v2
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v11, v3
; GFX12-GISEL-NEXT:    s_mov_b64 s[8:9], exec
; GFX12-GISEL-NEXT:    s_mov_b64 s[6:7], exec
; GFX12-GISEL-NEXT:  .LBB18_1: ; =>This Inner Loop Header: Depth=1
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s10, v8
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s11, v9
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_2)
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s10, v8
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s11, v9
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s10, v10
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s12, v11
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x1
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v4, 0.5
; GFX12-GISEL-NEXT:    s_ashr_i32 s11, s10, 31
; GFX12-GISEL-NEXT:    s_ashr_i32 s13, s12, 31
; GFX12-GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-GISEL-NEXT:    s_lshl_b64 s[10:11], s[10:11], 5
; GFX12-GISEL-NEXT:    s_wait_alu depctr_sa_sdst(0)
; GFX12-GISEL-NEXT:    s_add_co_u32 s10, s0, s10
; GFX12-GISEL-NEXT:    s_add_co_ci_u32 s11, s1, s11
; GFX12-GISEL-NEXT:    s_lshl_b64 s[12:13], s[12:13], 4
; GFX12-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-GISEL-NEXT:    s_add_co_u32 s20, s2, s12
; GFX12-GISEL-NEXT:    s_add_co_ci_u32 s21, s3, s13
; GFX12-GISEL-NEXT:    s_load_b256 s[12:19], s[10:11], 0x0
; GFX12-GISEL-NEXT:    s_load_b128 s[20:23], s[20:21], 0x0
; GFX12-GISEL-NEXT:    s_wait_kmcnt 0x0
; GFX12-GISEL-NEXT:    s_clause 0x1
; GFX12-GISEL-NEXT:    image_sample v[0:3], [v0, v0], s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX12-GISEL-NEXT:    image_sample v[4:7], [v4, v4], s[12:19], s[20:23] dmask:0xf dim:SQ_RSRC_IMG_2D
; GFX12-GISEL-NEXT:    s_and_not1_wrexec_b64 s[8:9], s[8:9]
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr8
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr9
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr10
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr11
; GFX12-GISEL-NEXT:    s_cbranch_execnz .LBB18_1
; GFX12-GISEL-NEXT:  ; %bb.2:
; GFX12-GISEL-NEXT:    s_mov_b64 exec, s[6:7]
; GFX12-GISEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; GFX12-GISEL-NEXT:    s_and_b64 exec, exec, s[4:5]
; GFX12-GISEL-NEXT:    s_wait_samplecnt 0x0
; GFX12-GISEL-NEXT:    ; return to shader part epilog
       <8 x i32> addrspace(4)* inreg %in, <4 x i32> addrspace(4)* inreg %s_in,
       i32 %idx1, i32 %idx2, i32 %s_idx, i32 %s_idx2, { <4 x float>, <4 x float> } %dummy) #1 {
  %tok = call token @llvm.amdgcn.waterfall.begin.i32(token poison, i32 %idx1)
  %tok1 = call token @llvm.amdgcn.waterfall.begin.i32(token %tok, i32 %idx2)
  %widx0 = call i32 @llvm.amdgcn.waterfall.readfirstlane.i32.i32(token %tok1, i32 %s_idx)
  %widx1 = call i32 @llvm.amdgcn.waterfall.readfirstlane.i32.i32(token %tok1, i32 %s_idx2)
  %widx0a = sext i32 %widx0 to i64
  %widx1a = sext i32 %widx1 to i64
  %rptr = getelementptr <8 x i32>, <8 x i32> addrspace(4)* %in, i64 %widx0a
  %sptr = getelementptr <4 x i32>, <4 x i32> addrspace(4)* %s_in, i64 %widx1a
  %rsrc = load <8 x i32>, <8 x i32> addrspace(4)* %rptr, align 32
  %srsrc = load <4 x i32>, <4 x i32> addrspace(4)* %sptr, align 16

  %r = call <4 x float> @llvm.amdgcn.image.sample.2d.v4f32.f32(i32 15, float 0.000000e+00, float 0.000000e+00, <8 x i32> %rsrc, <4 x i32> %srsrc, i1 false, i32 0, i32 0)
  %r2 = call <4 x float> @llvm.amdgcn.image.sample.2d.v4f32.f32(i32 15, float 0.500000e+00, float 0.500000e+00, <8 x i32> %rsrc, <4 x i32> %srsrc, i1 false, i32 0, i32 0)
  %r1 = call <4 x float> @llvm.amdgcn.waterfall.end.v4f32(token %tok1, <4 x float> %r)
  %r3 = call <4 x float> @llvm.amdgcn.waterfall.end.v4f32(token %tok1, <4 x float> %r2)

  %insert = insertvalue { <4 x float>, <4 x float> } %dummy, <4 x float> %r1, 0
  %insert1 = insertvalue { <4 x float>, <4 x float> } %insert, <4 x float> %r3, 1
  ret {<4 x float> , <4 x float>} %insert1
}

define amdgpu_ps {<4 x float>,float} @test_waterfall_multi_end_struct(
; VI-SDAG-LABEL: test_waterfall_multi_end_struct:
; VI-SDAG:       ; %bb.0:
; VI-SDAG-NEXT:    v_mov_b32_e32 v9, v4
; VI-SDAG-NEXT:    v_mov_b32_e32 v8, v3
; VI-SDAG-NEXT:    v_mov_b32_e32 v7, v2
; VI-SDAG-NEXT:    v_mov_b32_e32 v6, v1
; VI-SDAG-NEXT:    v_mov_b32_e32 v10, v0
; VI-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; VI-SDAG-NEXT:  .LBB19_1: ; =>This Inner Loop Header: Depth=1
; VI-SDAG-NEXT:    v_readfirstlane_b32 s2, v10
; VI-SDAG-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v10
; VI-SDAG-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; VI-SDAG-NEXT:    v_readfirstlane_b32 s4, v6
; VI-SDAG-NEXT:    v_readfirstlane_b32 s5, v7
; VI-SDAG-NEXT:    v_readfirstlane_b32 s6, v8
; VI-SDAG-NEXT:    v_readfirstlane_b32 s7, v9
; VI-SDAG-NEXT:    v_mov_b32_e32 v1, v0
; VI-SDAG-NEXT:    v_mov_b32_e32 v2, v0
; VI-SDAG-NEXT:    v_mov_b32_e32 v3, v0
; VI-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; VI-SDAG-NEXT:    ; implicit-def: $vgpr10
; VI-SDAG-NEXT:    ; implicit-def: $vgpr6_vgpr7_vgpr8_vgpr9
; VI-SDAG-NEXT:    s_nop 0
; VI-SDAG-NEXT:    buffer_load_format_xyzw v[0:4], v5, s[4:7], 0 idxen tfe
; VI-SDAG-NEXT:    ; implicit-def: $vgpr5
; VI-SDAG-NEXT:    s_xor_b64 exec, exec, s[2:3]
; VI-SDAG-NEXT:    s_cbranch_execnz .LBB19_1
; VI-SDAG-NEXT:  ; %bb.2:
; VI-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    ; return to shader part epilog
;
; VI-GISEL-LABEL: test_waterfall_multi_end_struct:
; VI-GISEL:       ; %bb.0:
; VI-GISEL-NEXT:    v_mov_b32_e32 v10, v0
; VI-GISEL-NEXT:    v_mov_b32_e32 v6, v1
; VI-GISEL-NEXT:    v_mov_b32_e32 v7, v2
; VI-GISEL-NEXT:    v_mov_b32_e32 v8, v3
; VI-GISEL-NEXT:    v_mov_b32_e32 v9, v4
; VI-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; VI-GISEL-NEXT:  .LBB19_1: ; =>This Inner Loop Header: Depth=1
; VI-GISEL-NEXT:    v_readfirstlane_b32 s2, v10
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v10
; VI-GISEL-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; VI-GISEL-NEXT:    v_readfirstlane_b32 s4, v6
; VI-GISEL-NEXT:    v_readfirstlane_b32 s5, v7
; VI-GISEL-NEXT:    v_readfirstlane_b32 s6, v8
; VI-GISEL-NEXT:    v_readfirstlane_b32 s7, v9
; VI-GISEL-NEXT:    v_mov_b32_e32 v1, v0
; VI-GISEL-NEXT:    v_mov_b32_e32 v2, v0
; VI-GISEL-NEXT:    v_mov_b32_e32 v3, v0
; VI-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; VI-GISEL-NEXT:    ; implicit-def: $vgpr10
; VI-GISEL-NEXT:    ; implicit-def: $vgpr6_vgpr7_vgpr8_vgpr9
; VI-GISEL-NEXT:    s_nop 0
; VI-GISEL-NEXT:    buffer_load_format_xyzw v[0:4], v5, s[4:7], 0 idxen tfe
; VI-GISEL-NEXT:    ; implicit-def: $vgpr5
; VI-GISEL-NEXT:    s_xor_b64 exec, exec, s[2:3]
; VI-GISEL-NEXT:    s_cbranch_execnz .LBB19_1
; VI-GISEL-NEXT:  ; %bb.2:
; VI-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    ; return to shader part epilog
;
; GFX9-SDAG-LABEL: test_waterfall_multi_end_struct:
; GFX9-SDAG:       ; %bb.0:
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v9, v4
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v8, v3
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v7, v2
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v6, v1
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v10, v0
; GFX9-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX9-SDAG-NEXT:  .LBB19_1: ; =>This Inner Loop Header: Depth=1
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s2, v10
; GFX9-SDAG-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v10
; GFX9-SDAG-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s4, v6
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s5, v7
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s6, v8
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s7, v9
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v1, v0
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v2, v0
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v3, v0
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr10
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr6_vgpr7_vgpr8_vgpr9
; GFX9-SDAG-NEXT:    s_nop 0
; GFX9-SDAG-NEXT:    buffer_load_format_xyzw v[0:4], v5, s[4:7], 0 idxen tfe
; GFX9-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX9-SDAG-NEXT:    s_xor_b64 exec, exec, s[2:3]
; GFX9-SDAG-NEXT:    s_cbranch_execnz .LBB19_1
; GFX9-SDAG-NEXT:  ; %bb.2:
; GFX9-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    ; return to shader part epilog
;
; GFX9-GISEL-LABEL: test_waterfall_multi_end_struct:
; GFX9-GISEL:       ; %bb.0:
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v10, v0
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v6, v1
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v7, v2
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v8, v3
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v9, v4
; GFX9-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX9-GISEL-NEXT:  .LBB19_1: ; =>This Inner Loop Header: Depth=1
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s2, v10
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v10
; GFX9-GISEL-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s4, v6
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s5, v7
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s6, v8
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s7, v9
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v1, v0
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v2, v0
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v3, v0
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr10
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr6_vgpr7_vgpr8_vgpr9
; GFX9-GISEL-NEXT:    s_nop 0
; GFX9-GISEL-NEXT:    buffer_load_format_xyzw v[0:4], v5, s[4:7], 0 idxen tfe
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX9-GISEL-NEXT:    s_xor_b64 exec, exec, s[2:3]
; GFX9-GISEL-NEXT:    s_cbranch_execnz .LBB19_1
; GFX9-GISEL-NEXT:  ; %bb.2:
; GFX9-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-32-SDAG-LABEL: test_waterfall_multi_end_struct:
; GFX10-32-SDAG:       ; %bb.0:
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v9, v4
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v8, v3
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v7, v2
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v6, v1
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v10, v0
; GFX10-32-SDAG-NEXT:    s_mov_b32 s1, exec_lo
; GFX10-32-SDAG-NEXT:    s_mov_b32 s0, exec_lo
; GFX10-32-SDAG-NEXT:  .LBB19_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s2, v10
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-SDAG-NEXT:    v_cmpx_eq_u32_e32 s2, v10
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s4, v6
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s5, v7
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s6, v8
; GFX10-32-SDAG-NEXT:    v_readfirstlane_b32 s7, v9
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v1, v0
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v2, v0
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v3, v0
; GFX10-32-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-32-SDAG-NEXT:    buffer_load_format_xyzw v[0:4], v5, s[4:7], 0 idxen tfe
; GFX10-32-SDAG-NEXT:    s_andn2_wrexec_b32 s1, s1
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr10
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr6_vgpr7_vgpr8_vgpr9
; GFX10-32-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX10-32-SDAG-NEXT:    s_cbranch_execnz .LBB19_1
; GFX10-32-SDAG-NEXT:  ; %bb.2:
; GFX10-32-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-SDAG-NEXT:    s_mov_b32 exec_lo, s0
; GFX10-32-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-32-GISEL-LABEL: test_waterfall_multi_end_struct:
; GFX10-32-GISEL:       ; %bb.0:
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v10, v0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v6, v1
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v7, v2
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v8, v3
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v9, v4
; GFX10-32-GISEL-NEXT:    s_mov_b32 s1, exec_lo
; GFX10-32-GISEL-NEXT:    s_mov_b32 s0, exec_lo
; GFX10-32-GISEL-NEXT:  .LBB19_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s2, v10
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s2, v10
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s4, v6
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s5, v7
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s6, v8
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s7, v9
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v1, v0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v2, v0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v3, v0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-32-GISEL-NEXT:    buffer_load_format_xyzw v[0:4], v5, s[4:7], 0 idxen tfe
; GFX10-32-GISEL-NEXT:    s_andn2_wrexec_b32 s1, s1
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr10
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr6_vgpr7_vgpr8_vgpr9
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX10-32-GISEL-NEXT:    s_cbranch_execnz .LBB19_1
; GFX10-32-GISEL-NEXT:  ; %bb.2:
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-GISEL-NEXT:    s_mov_b32 exec_lo, s0
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-64-SDAG-LABEL: test_waterfall_multi_end_struct:
; GFX10-64-SDAG:       ; %bb.0:
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v9, v4
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v8, v3
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v7, v2
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v6, v1
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v10, v0
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX10-64-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX10-64-SDAG-NEXT:  .LBB19_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s4, v10
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-SDAG-NEXT:    v_cmpx_eq_u32_e32 s4, v10
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s4, v6
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s5, v7
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s6, v8
; GFX10-64-SDAG-NEXT:    v_readfirstlane_b32 s7, v9
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v1, v0
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v2, v0
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v3, v0
; GFX10-64-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-64-SDAG-NEXT:    buffer_load_format_xyzw v[0:4], v5, s[4:7], 0 idxen tfe
; GFX10-64-SDAG-NEXT:    s_andn2_wrexec_b64 s[2:3], s[2:3]
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr10
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr6_vgpr7_vgpr8_vgpr9
; GFX10-64-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX10-64-SDAG-NEXT:    s_cbranch_execnz .LBB19_1
; GFX10-64-SDAG-NEXT:  ; %bb.2:
; GFX10-64-SDAG-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX10-64-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-64-GISEL-LABEL: test_waterfall_multi_end_struct:
; GFX10-64-GISEL:       ; %bb.0:
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v10, v0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v6, v1
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v7, v2
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v8, v3
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v9, v4
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX10-64-GISEL-NEXT:  .LBB19_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s4, v10
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s4, v10
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s4, v6
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s5, v7
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s6, v8
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s7, v9
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v1, v0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v2, v0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v3, v0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-64-GISEL-NEXT:    buffer_load_format_xyzw v[0:4], v5, s[4:7], 0 idxen tfe
; GFX10-64-GISEL-NEXT:    s_andn2_wrexec_b64 s[2:3], s[2:3]
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr10
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr6_vgpr7_vgpr8_vgpr9
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX10-64-GISEL-NEXT:    s_cbranch_execnz .LBB19_1
; GFX10-64-GISEL-NEXT:  ; %bb.2:
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:    ; return to shader part epilog
;
; GFX1150-SDAG-LABEL: test_waterfall_multi_end_struct:
; GFX1150-SDAG:       ; %bb.0:
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v9, v4
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v8, v3
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v7, v2
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v6, v1
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v10, v0
; GFX1150-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX1150-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX1150-SDAG-NEXT:  .LBB19_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s4, v10
; GFX1150-SDAG-NEXT:    v_cmpx_eq_u32_e32 s4, v10
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s4, v6
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s5, v7
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s6, v8
; GFX1150-SDAG-NEXT:    v_readfirstlane_b32 s7, v9
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v1, v0
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v2, v0
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v3, v0
; GFX1150-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX1150-SDAG-NEXT:    buffer_load_format_xyzw v[0:4], v5, s[4:7], 0 idxen tfe
; GFX1150-SDAG-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr10
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr6_vgpr7_vgpr8_vgpr9
; GFX1150-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX1150-SDAG-NEXT:    s_cbranch_execnz .LBB19_1
; GFX1150-SDAG-NEXT:  ; %bb.2:
; GFX1150-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1150-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-SDAG-NEXT:    ; return to shader part epilog
;
; GFX1150-GISEL-LABEL: test_waterfall_multi_end_struct:
; GFX1150-GISEL:       ; %bb.0:
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v10, v0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v6, v1
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v7, v2
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v8, v3
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v9, v4
; GFX1150-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX1150-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX1150-GISEL-NEXT:  .LBB19_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s4, v10
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s4, v10
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s4, v6
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s5, v7
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s6, v8
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s7, v9
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v1, v0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v2, v0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v3, v0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX1150-GISEL-NEXT:    buffer_load_format_xyzw v[0:4], v5, s[4:7], 0 idxen tfe
; GFX1150-GISEL-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr10
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr6_vgpr7_vgpr8_vgpr9
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX1150-GISEL-NEXT:    s_cbranch_execnz .LBB19_1
; GFX1150-GISEL-NEXT:  ; %bb.2:
; GFX1150-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    ; return to shader part epilog
;
; GFX12-SDAG-LABEL: test_waterfall_multi_end_struct:
; GFX12-SDAG:       ; %bb.0:
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v9, v4
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v8, v3
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v7, v2
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v6, v1
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v10, v0
; GFX12-SDAG-NEXT:    s_mov_b64 s[2:3], exec
; GFX12-SDAG-NEXT:    s_mov_b64 s[0:1], exec
; GFX12-SDAG-NEXT:  .LBB19_1: ; =>This Inner Loop Header: Depth=1
; GFX12-SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s4, v10
; GFX12-SDAG-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-SDAG-NEXT:    v_cmpx_eq_u32_e32 s4, v10
; GFX12-SDAG-NEXT:    s_wait_loadcnt 0x0
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s4, v6
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s5, v7
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s6, v8
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s7, v9
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v1, v0
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v2, v0
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v3, v0
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX12-SDAG-NEXT:    buffer_load_format_xyzw v[0:4], v5, s[4:7], null idxen tfe
; GFX12-SDAG-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr10
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr6_vgpr7_vgpr8_vgpr9
; GFX12-SDAG-NEXT:    ; implicit-def: $vgpr5
; GFX12-SDAG-NEXT:    s_cbranch_execnz .LBB19_1
; GFX12-SDAG-NEXT:  ; %bb.2:
; GFX12-SDAG-NEXT:    s_mov_b64 exec, s[0:1]
; GFX12-SDAG-NEXT:    s_wait_loadcnt 0x0
; GFX12-SDAG-NEXT:    ; return to shader part epilog
;
; GFX12-GISEL-LABEL: test_waterfall_multi_end_struct:
; GFX12-GISEL:       ; %bb.0:
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v10, v0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v6, v1
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v7, v2
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v8, v3
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v9, v4
; GFX12-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX12-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX12-GISEL-NEXT:  .LBB19_1: ; =>This Inner Loop Header: Depth=1
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s4, v10
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s4, v10
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s4, v6
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s5, v7
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s6, v8
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s7, v9
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v1, v0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v2, v0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v3, v0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX12-GISEL-NEXT:    buffer_load_format_xyzw v[0:4], v5, s[4:7], null idxen tfe
; GFX12-GISEL-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr10
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr6_vgpr7_vgpr8_vgpr9
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr5
; GFX12-GISEL-NEXT:    s_cbranch_execnz .LBB19_1
; GFX12-GISEL-NEXT:  ; %bb.2:
; GFX12-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x0
; GFX12-GISEL-NEXT:    ; return to shader part epilog
              i32 %idx, <4 x i32> %s_idx, i32 %v_inp, { <4 x float>, float } %dummy) #1 {
  %tok = call token @llvm.amdgcn.waterfall.begin.i32(token poison, i32 %idx)
  %widx0 = call <4 x i32> @llvm.amdgcn.waterfall.readfirstlane.v4i32.v4i32(token %tok, <4 x i32> %s_idx)
  %val = call { <4 x float>, i32 } @llvm.amdgcn.struct.buffer.load.format.sl_v4f32i32s(<4 x i32> %widx0, i32 %v_inp, i32 0, i32 0, i32 0)
  %payl = extractvalue { <4 x float>, i32 } %val, 0
  %tfe = extractvalue { <4 x float>, i32 } %val, 1
  %r0 = call <4 x float> @llvm.amdgcn.waterfall.end.v4f32(token %tok, <4 x float> %payl)
  %r1 = call i32 @llvm.amdgcn.waterfall.end.i32(token %tok, i32 %tfe)
  %r1.float = bitcast i32 %r1 to float

  %insert = insertvalue { <4 x float>, float } %dummy, <4 x float> %r0, 0
  %insert1 = insertvalue { <4 x float>, float } %insert, float %r1.float, 1
  ret {<4 x float> , float} %insert1
}

define amdgpu_ps {<4 x float>,float} @test_waterfall_multi_end_struct_uniform(
; VI-SDAG-LABEL: test_waterfall_multi_end_struct_uniform:
; VI-SDAG:       ; %bb.0:
; VI-SDAG-NEXT:    v_readfirstlane_b32 s0, v0
; VI-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; VI-SDAG-NEXT:    v_mov_b32_e32 v5, v4
; VI-SDAG-NEXT:    v_readfirstlane_b32 s1, v1
; VI-SDAG-NEXT:    v_readfirstlane_b32 s2, v2
; VI-SDAG-NEXT:    v_readfirstlane_b32 s3, v3
; VI-SDAG-NEXT:    v_mov_b32_e32 v1, v0
; VI-SDAG-NEXT:    v_mov_b32_e32 v2, v0
; VI-SDAG-NEXT:    v_mov_b32_e32 v3, v0
; VI-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; VI-SDAG-NEXT:    s_nop 0
; VI-SDAG-NEXT:    buffer_load_format_xyzw v[0:4], v5, s[0:3], 0 idxen tfe
; VI-SDAG-NEXT:    s_waitcnt vmcnt(0)
; VI-SDAG-NEXT:    ; return to shader part epilog
;
; VI-GISEL-LABEL: test_waterfall_multi_end_struct_uniform:
; VI-GISEL:       ; %bb.0:
; VI-GISEL-NEXT:    v_mov_b32_e32 v5, v0
; VI-GISEL-NEXT:    v_mov_b32_e32 v6, v1
; VI-GISEL-NEXT:    v_mov_b32_e32 v7, v2
; VI-GISEL-NEXT:    v_mov_b32_e32 v8, v3
; VI-GISEL-NEXT:    v_mov_b32_e32 v9, v4
; VI-GISEL-NEXT:    v_mov_b32_e32 v10, s0
; VI-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; VI-GISEL-NEXT:  .LBB20_1: ; =>This Inner Loop Header: Depth=1
; VI-GISEL-NEXT:    v_readfirstlane_b32 s2, v10
; VI-GISEL-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v10
; VI-GISEL-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; VI-GISEL-NEXT:    v_readfirstlane_b32 s4, v5
; VI-GISEL-NEXT:    v_readfirstlane_b32 s5, v6
; VI-GISEL-NEXT:    v_readfirstlane_b32 s6, v7
; VI-GISEL-NEXT:    v_readfirstlane_b32 s7, v8
; VI-GISEL-NEXT:    v_mov_b32_e32 v1, v0
; VI-GISEL-NEXT:    v_mov_b32_e32 v2, v0
; VI-GISEL-NEXT:    v_mov_b32_e32 v3, v0
; VI-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; VI-GISEL-NEXT:    ; implicit-def: $vgpr10
; VI-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8
; VI-GISEL-NEXT:    s_nop 0
; VI-GISEL-NEXT:    buffer_load_format_xyzw v[0:4], v9, s[4:7], 0 idxen tfe
; VI-GISEL-NEXT:    ; implicit-def: $vgpr9
; VI-GISEL-NEXT:    s_xor_b64 exec, exec, s[2:3]
; VI-GISEL-NEXT:    s_cbranch_execnz .LBB20_1
; VI-GISEL-NEXT:  ; %bb.2:
; VI-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; VI-GISEL-NEXT:    s_waitcnt vmcnt(0)
; VI-GISEL-NEXT:    ; return to shader part epilog
;
; GFX9-SDAG-LABEL: test_waterfall_multi_end_struct_uniform:
; GFX9-SDAG:       ; %bb.0:
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s0, v0
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v5, v4
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s1, v1
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s2, v2
; GFX9-SDAG-NEXT:    v_readfirstlane_b32 s3, v3
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v1, v0
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v2, v0
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v3, v0
; GFX9-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX9-SDAG-NEXT:    s_nop 0
; GFX9-SDAG-NEXT:    buffer_load_format_xyzw v[0:4], v5, s[0:3], 0 idxen tfe
; GFX9-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX9-SDAG-NEXT:    ; return to shader part epilog
;
; GFX9-GISEL-LABEL: test_waterfall_multi_end_struct_uniform:
; GFX9-GISEL:       ; %bb.0:
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v5, v0
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v6, v1
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v7, v2
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v8, v3
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v9, v4
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v10, s0
; GFX9-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX9-GISEL-NEXT:  .LBB20_1: ; =>This Inner Loop Header: Depth=1
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s2, v10
; GFX9-GISEL-NEXT:    v_cmp_eq_u32_e64 s[2:3], s2, v10
; GFX9-GISEL-NEXT:    s_and_saveexec_b64 s[2:3], s[2:3]
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s4, v5
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s5, v6
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s6, v7
; GFX9-GISEL-NEXT:    v_readfirstlane_b32 s7, v8
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v1, v0
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v2, v0
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v3, v0
; GFX9-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr10
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8
; GFX9-GISEL-NEXT:    s_nop 0
; GFX9-GISEL-NEXT:    buffer_load_format_xyzw v[0:4], v9, s[4:7], 0 idxen tfe
; GFX9-GISEL-NEXT:    ; implicit-def: $vgpr9
; GFX9-GISEL-NEXT:    s_xor_b64 exec, exec, s[2:3]
; GFX9-GISEL-NEXT:    s_cbranch_execnz .LBB20_1
; GFX9-GISEL-NEXT:  ; %bb.2:
; GFX9-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX9-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX9-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10GFX11-SDAG-LABEL: test_waterfall_multi_end_struct_uniform:
; GFX10GFX11-SDAG:       ; %bb.0:
; GFX10GFX11-SDAG-NEXT:    v_mov_b32_e32 v5, v4
; GFX10GFX11-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX10GFX11-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX10GFX11-SDAG-NEXT:    v_readfirstlane_b32 s1, v1
; GFX10GFX11-SDAG-NEXT:    v_readfirstlane_b32 s2, v2
; GFX10GFX11-SDAG-NEXT:    v_readfirstlane_b32 s3, v3
; GFX10GFX11-SDAG-NEXT:    v_readfirstlane_b32 s0, v4
; GFX10GFX11-SDAG-NEXT:    v_mov_b32_e32 v1, v0
; GFX10GFX11-SDAG-NEXT:    v_mov_b32_e32 v2, v0
; GFX10GFX11-SDAG-NEXT:    v_mov_b32_e32 v3, v0
; GFX10GFX11-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX10GFX11-SDAG-NEXT:    buffer_load_format_xyzw v[0:4], v5, s[0:3], 0 idxen tfe
; GFX10GFX11-SDAG-NEXT:    s_waitcnt vmcnt(0)
; GFX10GFX11-SDAG-NEXT:    ; return to shader part epilog
;
; GFX10-32-GISEL-LABEL: test_waterfall_multi_end_struct_uniform:
; GFX10-32-GISEL:       ; %bb.0:
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v5, v0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v6, v1
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v7, v2
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v8, v3
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v9, v4
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v10, s0
; GFX10-32-GISEL-NEXT:    s_mov_b32 s1, exec_lo
; GFX10-32-GISEL-NEXT:    s_mov_b32 s0, exec_lo
; GFX10-32-GISEL-NEXT:  .LBB20_1: ; =>This Inner Loop Header: Depth=1
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s2, v10
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-32-GISEL-NEXT:    v_cmpx_eq_u32_e32 s2, v10
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s4, v5
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s5, v6
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s6, v7
; GFX10-32-GISEL-NEXT:    v_readfirstlane_b32 s7, v8
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v1, v0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v2, v0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v3, v0
; GFX10-32-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-32-GISEL-NEXT:    buffer_load_format_xyzw v[0:4], v9, s[4:7], 0 idxen tfe
; GFX10-32-GISEL-NEXT:    s_andn2_wrexec_b32 s1, s1
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr10
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8
; GFX10-32-GISEL-NEXT:    ; implicit-def: $vgpr9
; GFX10-32-GISEL-NEXT:    s_cbranch_execnz .LBB20_1
; GFX10-32-GISEL-NEXT:  ; %bb.2:
; GFX10-32-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-32-GISEL-NEXT:    s_mov_b32 exec_lo, s0
; GFX10-32-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-32-GISEL-NEXT:    ; return to shader part epilog
;
; GFX10-64-GISEL-LABEL: test_waterfall_multi_end_struct_uniform:
; GFX10-64-GISEL:       ; %bb.0:
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v5, v0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v6, v1
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v7, v2
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v8, v3
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v9, v4
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v10, s0
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX10-64-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX10-64-GISEL-NEXT:  .LBB20_1: ; =>This Inner Loop Header: Depth=1
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s4, v10
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_sa_sdst(0)
; GFX10-64-GISEL-NEXT:    v_cmpx_eq_u32_e32 s4, v10
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s4, v5
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s5, v6
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s6, v7
; GFX10-64-GISEL-NEXT:    v_readfirstlane_b32 s7, v8
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v1, v0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v2, v0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v3, v0
; GFX10-64-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX10-64-GISEL-NEXT:    buffer_load_format_xyzw v[0:4], v9, s[4:7], 0 idxen tfe
; GFX10-64-GISEL-NEXT:    s_andn2_wrexec_b64 s[2:3], s[2:3]
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr10
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8
; GFX10-64-GISEL-NEXT:    ; implicit-def: $vgpr9
; GFX10-64-GISEL-NEXT:    s_cbranch_execnz .LBB20_1
; GFX10-64-GISEL-NEXT:  ; %bb.2:
; GFX10-64-GISEL-NEXT:    s_waitcnt_depctr depctr_vm_vsrc(0)
; GFX10-64-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX10-64-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX10-64-GISEL-NEXT:    ; return to shader part epilog
;
; GFX1150-GISEL-LABEL: test_waterfall_multi_end_struct_uniform:
; GFX1150-GISEL:       ; %bb.0:
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v5, v0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v6, v1
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v7, v2
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v8, v3
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v9, v4
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v10, s0
; GFX1150-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX1150-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX1150-GISEL-NEXT:  .LBB20_1: ; =>This Inner Loop Header: Depth=1
; GFX1150-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(NEXT) | instid1(VALU_DEP_1)
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s4, v10
; GFX1150-GISEL-NEXT:    v_cmpx_eq_u32_e32 s4, v10
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s4, v5
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s5, v6
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s6, v7
; GFX1150-GISEL-NEXT:    v_readfirstlane_b32 s7, v8
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v1, v0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v2, v0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v3, v0
; GFX1150-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX1150-GISEL-NEXT:    buffer_load_format_xyzw v[0:4], v9, s[4:7], 0 idxen tfe
; GFX1150-GISEL-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr10
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8
; GFX1150-GISEL-NEXT:    ; implicit-def: $vgpr9
; GFX1150-GISEL-NEXT:    s_cbranch_execnz .LBB20_1
; GFX1150-GISEL-NEXT:  ; %bb.2:
; GFX1150-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX1150-GISEL-NEXT:    s_waitcnt vmcnt(0)
; GFX1150-GISEL-NEXT:    ; return to shader part epilog
;
; GFX12-SDAG-LABEL: test_waterfall_multi_end_struct_uniform:
; GFX12-SDAG:       ; %bb.0:
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v5, v4
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v0, 0
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s1, v1
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s2, v2
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s3, v3
; GFX12-SDAG-NEXT:    v_readfirstlane_b32 s0, v4
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v1, v0
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v2, v0
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v3, v0
; GFX12-SDAG-NEXT:    v_mov_b32_e32 v4, v0
; GFX12-SDAG-NEXT:    buffer_load_format_xyzw v[0:4], v5, s[0:3], null idxen tfe
; GFX12-SDAG-NEXT:    s_wait_loadcnt 0x0
; GFX12-SDAG-NEXT:    ; return to shader part epilog
;
; GFX12-GISEL-LABEL: test_waterfall_multi_end_struct_uniform:
; GFX12-GISEL:       ; %bb.0:
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v5, v0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v6, v1
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v7, v2
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v8, v3
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v9, v4
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v10, s0
; GFX12-GISEL-NEXT:    s_mov_b64 s[2:3], exec
; GFX12-GISEL-NEXT:    s_mov_b64 s[0:1], exec
; GFX12-GISEL-NEXT:  .LBB20_1: ; =>This Inner Loop Header: Depth=1
; GFX12-GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_1) | instskip(SKIP_1) | instid1(VALU_DEP_1)
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s4, v10
; GFX12-GISEL-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-GISEL-NEXT:    v_cmpx_eq_u32_e32 s4, v10
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v0, 0
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s4, v5
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s5, v6
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s6, v7
; GFX12-GISEL-NEXT:    v_readfirstlane_b32 s7, v8
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v1, v0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v2, v0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v3, v0
; GFX12-GISEL-NEXT:    v_mov_b32_e32 v4, v0
; GFX12-GISEL-NEXT:    buffer_load_format_xyzw v[0:4], v9, s[4:7], null idxen tfe
; GFX12-GISEL-NEXT:    s_and_not1_wrexec_b64 s[2:3], s[2:3]
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr10
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr5_vgpr6_vgpr7_vgpr8
; GFX12-GISEL-NEXT:    ; implicit-def: $vgpr9
; GFX12-GISEL-NEXT:    s_cbranch_execnz .LBB20_1
; GFX12-GISEL-NEXT:  ; %bb.2:
; GFX12-GISEL-NEXT:    s_mov_b64 exec, s[0:1]
; GFX12-GISEL-NEXT:    s_wait_loadcnt 0x0
; GFX12-GISEL-NEXT:    ; return to shader part epilog
              i32 inreg %idx, <4 x i32> %s_idx, i32 %v_inp, { <4 x float>, float } %dummy) #1 {
  %tok = call token @llvm.amdgcn.waterfall.begin.i32(token poison, i32 %idx)
  %widx0 = call <4 x i32> @llvm.amdgcn.waterfall.readfirstlane.v4i32.v4i32(token %tok, <4 x i32> %s_idx)
  %val = call { <4 x float>, i32 } @llvm.amdgcn.struct.buffer.load.format.sl_v4f32i32s(<4 x i32> %widx0, i32 %v_inp, i32 0, i32 0, i32 0)
  %payl = extractvalue { <4 x float>, i32 } %val, 0
  %tfe = extractvalue { <4 x float>, i32 } %val, 1
  %r0 = call <4 x float> @llvm.amdgcn.waterfall.end.v4f32(token %tok, <4 x float> %payl)
  %r1 = call i32 @llvm.amdgcn.waterfall.end.i32(token %tok, i32 %tfe)
  %r1.float = bitcast i32 %r1 to float

  %insert = insertvalue { <4 x float>, float } %dummy, <4 x float> %r0, 0
  %insert1 = insertvalue { <4 x float>, float } %insert, float %r1.float, 1
  ret {<4 x float> , float} %insert1
}

%struct.wobble = type { float, float }

declare token @llvm.amdgcn.waterfall.begin.i32(token, i32) #6
declare token @llvm.amdgcn.waterfall.begin.v2i32(token, <2 x i32>) #6
declare token @llvm.amdgcn.waterfall.begin.v4i32(token, <4 x i32>) #6
declare token @llvm.amdgcn.waterfall.begin.v8i32(token, <8 x i32>) #1
declare token @llvm.amdgcn.waterfall.begin.p3(token, ptr addrspace(3))
declare i32 @llvm.amdgcn.waterfall.readfirstlane.i32.i32(token, i32) #6
declare <2 x i32> @llvm.amdgcn.waterfall.readfirstlane.v2i32.v2i32(token, <2 x i32>) #6
declare <8 x i32> @llvm.amdgcn.waterfall.readfirstlane.v8i32.v8i32(token, <8 x i32>) #6
declare <4 x i32> @llvm.amdgcn.waterfall.readfirstlane.v4i32.v4i32(token, <4 x i32>) #1
declare i16 @llvm.amdgcn.waterfall.end.i16(token, i16) #6
declare i32 @llvm.amdgcn.waterfall.end.i32(token, i32) #6
declare <4 x float> @llvm.amdgcn.waterfall.end.v4f32(token, <4 x float>) #6
declare <8 x i32> @llvm.amdgcn.waterfall.end.v8i32(token, <8 x i32>) #6
declare i32 @llvm.amdgcn.readlane(i32, i32) #0
declare <4 x float> @llvm.amdgcn.image.sample.1d.v4f32.f32(i32, float, <8 x i32>, <4 x i32>, i1, i32, i32)
declare <4 x float> @llvm.amdgcn.image.sample.2d.v4f32.f32(i32, float, float, <8 x i32>, <4 x i32>, i1, i32, i32)
declare void @llvm.amdgcn.image.store.1d.v4f32.i32(<4 x float>, i32, i32, <8 x i32>, i32, i32)
declare i64 @llvm.amdgcn.s.getpc() #3
declare float @llvm.amdgcn.buffer.load.ushort(<4 x i32>, i32, i32, i1, i1) #4
declare float @llvm.amdgcn.buffer.load.f32(<4 x i32>, i32, i32, i1, i1) #4
declare <4 x float> @llvm.amdgcn.buffer.load.v4f32(<4 x i32>, i32, i32, i1, i1) #4
declare i32 @llvm.amdgcn.s.buffer.load.i32(<4 x i32>, i32, i32) #2
declare { <4 x float>, i32 } @llvm.amdgcn.struct.buffer.load.format.sl_v4f32i32s(<4 x i32>, i32, i32, i32, i32) #4
declare <4 x i32> @llvm.amdgcn.s.buffer.load.v4i32(<4 x i32>, i32, i1) #2
declare void @llvm.amdgcn.buffer.store.short(float, <4 x i32>, i32, i32, i1, i1) #5
declare void @llvm.amdgcn.buffer.store.f32(float, <4 x i32>, i32, i32, i1, i1) #5
declare void @llvm.amdgcn.buffer.store.v4f32(<4 x float>, <4 x i32>, i32, i32, i1, i1) #5
declare void @llvm.amdgcn.kill(i1) #1
declare void @llvm.amdgcn.exp.f32(i32 immarg, i32 immarg, float, float, float, float, i1 immarg, i1 immarg) #7

attributes #0 = { nounwind readnone convergent }
attributes #1 = { nounwind }
attributes #2 = { nounwind readnone }
attributes #3 = { nounwind readnone speculatable }
attributes #4 = { nounwind readonly }
attributes #5 = { nounwind writeonly }
attributes #6 = { nounwind }
attributes #7 = { inaccessiblememonly nounwind writeonly }
