; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple=amdgcn -mcpu=gfx1300 -verify-machineinstrs | FileCheck -enable-var-scope -check-prefixes=GFX13-PACKED %s

define amdgpu_ps half @tbuffer_load_d16_x(i32 %rsrc) {
; GFX13-PACKED-LABEL: tbuffer_load_d16_x:
; GFX13-PACKED:       ; %bb.0: ; %main_body
; GFX13-PACKED-NEXT:    v_mov_b32_e32 v1, 0
; GFX13-PACKED-NEXT:    tbuffer_load_d16_format_x v0, v1, v0, null format:[BUF_FMT_32_FLOAT] idxen
; GFX13-PACKED-NEXT:    s_wait_loadcnt 0x0
; GFX13-PACKED-NEXT:    ; return to shader part epilog
main_body:
  %data = call half @llvm.amdgcn.struct.tbuffer.load.f16(i32 %rsrc, i32 0, i32 0, i32 0, i32 22, i32 0)
  ret half %data
}

define amdgpu_ps half @tbuffer_load_d16_xy(i32 %rsrc) {
; GFX13-PACKED-LABEL: tbuffer_load_d16_xy:
; GFX13-PACKED:       ; %bb.0: ; %main_body
; GFX13-PACKED-NEXT:    v_mov_b32_e32 v1, 0
; GFX13-PACKED-NEXT:    tbuffer_load_d16_format_xy v0, v1, v0, null format:[BUF_FMT_32_FLOAT] idxen
; GFX13-PACKED-NEXT:    s_wait_loadcnt 0x0
; GFX13-PACKED-NEXT:    v_lshrrev_b32_e32 v0, 16, v0
; GFX13-PACKED-NEXT:    ; return to shader part epilog
main_body:
  %data = call <2 x half> @llvm.amdgcn.struct.tbuffer.load.v2f16(i32 %rsrc, i32 0, i32 0, i32 0, i32 22, i32 0)
  %elt = extractelement <2 x half> %data, i32 1
  ret half %elt
}

define amdgpu_ps half @tbuffer_load_d16_xyz(i32 %rsrc) {
; GFX13-PACKED-LABEL: tbuffer_load_d16_xyz:
; GFX13-PACKED:       ; %bb.0: ; %main_body
; GFX13-PACKED-NEXT:    v_mov_b32_e32 v1, 0
; GFX13-PACKED-NEXT:    tbuffer_load_d16_format_xyz v[0:1], v1, v0, null format:[BUF_FMT_32_FLOAT] idxen
; GFX13-PACKED-NEXT:    s_wait_loadcnt 0x0
; GFX13-PACKED-NEXT:    v_mov_b32_e32 v0, v1
; GFX13-PACKED-NEXT:    ; return to shader part epilog
main_body:
  %data = call <3 x half> @llvm.amdgcn.struct.tbuffer.load.v3f16(i32 %rsrc, i32 0, i32 0, i32 0, i32 22, i32 0)
  %elt = extractelement <3 x half> %data, i32 2
  ret half %elt
}

define amdgpu_ps half @tbuffer_load_d16_xyzw(i32 %rsrc) {
; GFX13-PACKED-LABEL: tbuffer_load_d16_xyzw:
; GFX13-PACKED:       ; %bb.0: ; %main_body
; GFX13-PACKED-NEXT:    v_mov_b32_e32 v1, 0
; GFX13-PACKED-NEXT:    tbuffer_load_d16_format_xyzw v[0:1], v1, v0, null format:[BUF_FMT_32_FLOAT] idxen
; GFX13-PACKED-NEXT:    s_wait_loadcnt 0x0
; GFX13-PACKED-NEXT:    v_lshrrev_b32_e32 v0, 16, v1
; GFX13-PACKED-NEXT:    ; return to shader part epilog
main_body:
  %data = call <4 x half> @llvm.amdgcn.struct.tbuffer.load.v4f16(i32 %rsrc, i32 0, i32 0, i32 0, i32 22, i32 0)
  %elt = extractelement <4 x half> %data, i32 3
  ret half %elt
}

declare half @llvm.amdgcn.struct.tbuffer.load.f16(i32, i32, i32, i32, i32, i32)
declare <2 x half> @llvm.amdgcn.struct.tbuffer.load.v2f16(i32, i32, i32, i32, i32, i32)
declare <3 x half> @llvm.amdgcn.struct.tbuffer.load.v3f16(i32, i32, i32, i32, i32, i32)
declare <4 x half> @llvm.amdgcn.struct.tbuffer.load.v4f16(i32, i32, i32, i32, i32, i32)
