; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
; RUN: llc -mtriple=amdgcn -mcpu=tonga -stop-after=virtregrewriter -verify-machineinstrs < %s | FileCheck -check-prefixes=GFX8-RA %s
; RUN: llc -mtriple=amdgcn -mcpu=gfx1010 -stop-after=virtregrewriter -verify-machineinstrs < %s | FileCheck -check-prefixes=GFX10-RA %s
; RUN: llc -mtriple=amdgcn -mcpu=gfx1100 -stop-after=virtregrewriter -verify-machineinstrs < %s | FileCheck -check-prefixes=GFX11-RA %s
; RUN: llc -mtriple=amdgcn -mcpu=gfx1200 -stop-after=virtregrewriter -verify-machineinstrs < %s | FileCheck -check-prefixes=GFX12-RA %s

define amdgpu_ps <4 x float> @load_3d(<8 x i32> inreg %rsrc, i32 %s, i32 %t, i32 %r) {
  ; GFX8-RA-LABEL: name: load_3d
  ; GFX8-RA: bb.0.main_body:
  ; GFX8-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1, $vgpr2
  ; GFX8-RA-NEXT: {{  $}}
  ; GFX8-RA-NEXT:   undef [[COPY:%[0-9]+]].sub2:vreg_96 = COPY $vgpr2
  ; GFX8-RA-NEXT:   [[COPY:%[0-9]+]].sub1:vreg_96 = COPY $vgpr1
  ; GFX8-RA-NEXT:   [[COPY:%[0-9]+]].sub0:vreg_96 = COPY $vgpr0
  ; GFX8-RA-NEXT:   [[IMAGE_LOAD_V4_V3_:%[0-9]+]]:vreg_128 = IMAGE_LOAD_V4_V3 [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, 15, -1, 0, 0, 0, 0, 0, 0, implicit $exec :: (dereferenceable load (s128), addrspace 8)
  ; GFX8-RA-NEXT:   $vgpr0 = COPY [[IMAGE_LOAD_V4_V3_]].sub0
  ; GFX8-RA-NEXT:   $vgpr1 = COPY [[IMAGE_LOAD_V4_V3_]].sub1
  ; GFX8-RA-NEXT:   $vgpr2 = COPY [[IMAGE_LOAD_V4_V3_]].sub2
  ; GFX8-RA-NEXT:   $vgpr3 = COPY [[IMAGE_LOAD_V4_V3_]].sub3
  ; GFX8-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, $vgpr1, $vgpr2, killed $vgpr3
  ;
  ; GFX10-RA-LABEL: name: load_3d
  ; GFX10-RA: bb.0.main_body:
  ; GFX10-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1, $vgpr2
  ; GFX10-RA-NEXT: {{  $}}
  ; GFX10-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr2
  ; GFX10-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX10-RA-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX10-RA-NEXT:   [[IMAGE_LOAD_V4_V3_nsa_gfx10_:%[0-9]+]]:vreg_128 = IMAGE_LOAD_V4_V3_nsa_gfx10 [[COPY2]], [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, 15, 2, -1, 0, 0, 0, 0, 0, 0, implicit $exec :: (dereferenceable load (s128), addrspace 8)
  ; GFX10-RA-NEXT:   $vgpr0 = COPY [[IMAGE_LOAD_V4_V3_nsa_gfx10_]].sub0
  ; GFX10-RA-NEXT:   $vgpr1 = COPY [[IMAGE_LOAD_V4_V3_nsa_gfx10_]].sub1
  ; GFX10-RA-NEXT:   $vgpr2 = COPY [[IMAGE_LOAD_V4_V3_nsa_gfx10_]].sub2
  ; GFX10-RA-NEXT:   $vgpr3 = COPY [[IMAGE_LOAD_V4_V3_nsa_gfx10_]].sub3
  ; GFX10-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, $vgpr1, $vgpr2, killed $vgpr3
  ;
  ; GFX11-RA-LABEL: name: load_3d
  ; GFX11-RA: bb.0.main_body:
  ; GFX11-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1, $vgpr2
  ; GFX11-RA-NEXT: {{  $}}
  ; GFX11-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr2
  ; GFX11-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX11-RA-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX11-RA-NEXT:   [[IMAGE_LOAD_V4_V3_nsa_gfx11_:%[0-9]+]]:vreg_128 = IMAGE_LOAD_V4_V3_nsa_gfx11 [[COPY2]], [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, 15, 2, -1, 0, 0, 0, 0, 0, 0, implicit $exec :: (dereferenceable load (s128), addrspace 8)
  ; GFX11-RA-NEXT:   $vgpr0 = COPY [[IMAGE_LOAD_V4_V3_nsa_gfx11_]].sub0
  ; GFX11-RA-NEXT:   $vgpr1 = COPY [[IMAGE_LOAD_V4_V3_nsa_gfx11_]].sub1
  ; GFX11-RA-NEXT:   $vgpr2 = COPY [[IMAGE_LOAD_V4_V3_nsa_gfx11_]].sub2
  ; GFX11-RA-NEXT:   $vgpr3 = COPY [[IMAGE_LOAD_V4_V3_nsa_gfx11_]].sub3
  ; GFX11-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, $vgpr1, $vgpr2, killed $vgpr3
  ;
  ; GFX12-RA-LABEL: name: load_3d
  ; GFX12-RA: bb.0.main_body:
  ; GFX12-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1, $vgpr2
  ; GFX12-RA-NEXT: {{  $}}
  ; GFX12-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr2
  ; GFX12-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX12-RA-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX12-RA-NEXT:   [[IMAGE_LOAD_V4_V3_gfx12_:%[0-9]+]]:vreg_128 = IMAGE_LOAD_V4_V3_gfx12 [[COPY2]], [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, 15, 2, 0, 0, 0, 0, 0, implicit $exec :: (dereferenceable load (s128), addrspace 8)
  ; GFX12-RA-NEXT:   $vgpr0 = COPY [[IMAGE_LOAD_V4_V3_gfx12_]].sub0
  ; GFX12-RA-NEXT:   $vgpr1 = COPY [[IMAGE_LOAD_V4_V3_gfx12_]].sub1
  ; GFX12-RA-NEXT:   $vgpr2 = COPY [[IMAGE_LOAD_V4_V3_gfx12_]].sub2
  ; GFX12-RA-NEXT:   $vgpr3 = COPY [[IMAGE_LOAD_V4_V3_gfx12_]].sub3
  ; GFX12-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, $vgpr1, $vgpr2, killed $vgpr3
main_body:
  %v = call <4 x float> @llvm.amdgcn.image.load.3d(i32 15, i32 %s, i32 %t, i32 %r, <8 x i32> %rsrc, i32 0, i32 0)
  ret <4 x float> %v
}

define amdgpu_ps <4 x float> @load_3d_r128(<4 x i32> inreg %rsrc, i32 %s, i32 %t, i32 %r) {
  ; GFX8-RA-LABEL: name: load_3d_r128
  ; GFX8-RA: bb.0.main_body:
  ; GFX8-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $vgpr0, $vgpr1, $vgpr2
  ; GFX8-RA-NEXT: {{  $}}
  ; GFX8-RA-NEXT:   undef [[COPY:%[0-9]+]].sub2:vreg_96 = COPY $vgpr2
  ; GFX8-RA-NEXT:   [[COPY:%[0-9]+]].sub1:vreg_96 = COPY $vgpr1
  ; GFX8-RA-NEXT:   [[COPY:%[0-9]+]].sub0:vreg_96 = COPY $vgpr0
  ; GFX8-RA-NEXT:   [[IMAGE_LOAD_V4_V3_:%[0-9]+]]:vreg_128 = IMAGE_LOAD_V4_V3 [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, 15, -1, 0, -1, 0, 0, 0, 0, implicit $exec :: (dereferenceable load (s128), addrspace 8)
  ; GFX8-RA-NEXT:   $vgpr0 = COPY [[IMAGE_LOAD_V4_V3_]].sub0
  ; GFX8-RA-NEXT:   $vgpr1 = COPY [[IMAGE_LOAD_V4_V3_]].sub1
  ; GFX8-RA-NEXT:   $vgpr2 = COPY [[IMAGE_LOAD_V4_V3_]].sub2
  ; GFX8-RA-NEXT:   $vgpr3 = COPY [[IMAGE_LOAD_V4_V3_]].sub3
  ; GFX8-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, $vgpr1, $vgpr2, killed $vgpr3
  ;
  ; GFX10-RA-LABEL: name: load_3d_r128
  ; GFX10-RA: bb.0.main_body:
  ; GFX10-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $vgpr0, $vgpr1, $vgpr2
  ; GFX10-RA-NEXT: {{  $}}
  ; GFX10-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr2
  ; GFX10-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX10-RA-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX10-RA-NEXT:   [[IMAGE_LOAD_V4_V3_nsa_gfx10_:%[0-9]+]]:vreg_128 = IMAGE_LOAD_V4_V3_nsa_gfx10 [[COPY2]], [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, 15, 2, -1, 0, -1, 0, 0, 0, 0, implicit $exec :: (dereferenceable load (s128), addrspace 8)
  ; GFX10-RA-NEXT:   $vgpr0 = COPY [[IMAGE_LOAD_V4_V3_nsa_gfx10_]].sub0
  ; GFX10-RA-NEXT:   $vgpr1 = COPY [[IMAGE_LOAD_V4_V3_nsa_gfx10_]].sub1
  ; GFX10-RA-NEXT:   $vgpr2 = COPY [[IMAGE_LOAD_V4_V3_nsa_gfx10_]].sub2
  ; GFX10-RA-NEXT:   $vgpr3 = COPY [[IMAGE_LOAD_V4_V3_nsa_gfx10_]].sub3
  ; GFX10-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, $vgpr1, $vgpr2, killed $vgpr3
  ;
  ; GFX11-RA-LABEL: name: load_3d_r128
  ; GFX11-RA: bb.0.main_body:
  ; GFX11-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $vgpr0, $vgpr1, $vgpr2
  ; GFX11-RA-NEXT: {{  $}}
  ; GFX11-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr2
  ; GFX11-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX11-RA-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX11-RA-NEXT:   [[IMAGE_LOAD_V4_V3_nsa_gfx11_:%[0-9]+]]:vreg_128 = IMAGE_LOAD_V4_V3_nsa_gfx11 [[COPY2]], [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, 15, 2, -1, 0, -1, 0, 0, 0, 0, implicit $exec :: (dereferenceable load (s128), addrspace 8)
  ; GFX11-RA-NEXT:   $vgpr0 = COPY [[IMAGE_LOAD_V4_V3_nsa_gfx11_]].sub0
  ; GFX11-RA-NEXT:   $vgpr1 = COPY [[IMAGE_LOAD_V4_V3_nsa_gfx11_]].sub1
  ; GFX11-RA-NEXT:   $vgpr2 = COPY [[IMAGE_LOAD_V4_V3_nsa_gfx11_]].sub2
  ; GFX11-RA-NEXT:   $vgpr3 = COPY [[IMAGE_LOAD_V4_V3_nsa_gfx11_]].sub3
  ; GFX11-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, $vgpr1, $vgpr2, killed $vgpr3
  ;
  ; GFX12-RA-LABEL: name: load_3d_r128
  ; GFX12-RA: bb.0.main_body:
  ; GFX12-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $vgpr0, $vgpr1, $vgpr2
  ; GFX12-RA-NEXT: {{  $}}
  ; GFX12-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr2
  ; GFX12-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX12-RA-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX12-RA-NEXT:   [[IMAGE_LOAD_V4_V3_gfx12_:%[0-9]+]]:vreg_128 = IMAGE_LOAD_V4_V3_gfx12 [[COPY2]], [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, 15, 2, 0, -1, 0, 0, 0, implicit $exec :: (dereferenceable load (s128), addrspace 8)
  ; GFX12-RA-NEXT:   $vgpr0 = COPY [[IMAGE_LOAD_V4_V3_gfx12_]].sub0
  ; GFX12-RA-NEXT:   $vgpr1 = COPY [[IMAGE_LOAD_V4_V3_gfx12_]].sub1
  ; GFX12-RA-NEXT:   $vgpr2 = COPY [[IMAGE_LOAD_V4_V3_gfx12_]].sub2
  ; GFX12-RA-NEXT:   $vgpr3 = COPY [[IMAGE_LOAD_V4_V3_gfx12_]].sub3
  ; GFX12-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, $vgpr1, $vgpr2, killed $vgpr3
main_body:
  %v = call <4 x float> @llvm.amdgcn.image.load.3d(i32 15, i32 %s, i32 %t, i32 %r, <4 x i32> %rsrc, i32 0, i32 0)
  ret <4 x float> %v
}

define amdgpu_ps void @store_3d(<8 x i32> inreg %rsrc, <4 x float> %vdata, i32 %s, i32 %t, i32 %r) {
  ; GFX8-RA-LABEL: name: store_3d
  ; GFX8-RA: bb.0.main_body:
  ; GFX8-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6
  ; GFX8-RA-NEXT: {{  $}}
  ; GFX8-RA-NEXT:   undef [[COPY:%[0-9]+]].sub2:vreg_96 = COPY $vgpr6
  ; GFX8-RA-NEXT:   [[COPY:%[0-9]+]].sub1:vreg_96 = COPY $vgpr5
  ; GFX8-RA-NEXT:   [[COPY:%[0-9]+]].sub0:vreg_96 = COPY $vgpr4
  ; GFX8-RA-NEXT:   undef [[COPY1:%[0-9]+]].sub3:vreg_128 = COPY $vgpr3
  ; GFX8-RA-NEXT:   [[COPY1:%[0-9]+]].sub2:vreg_128 = COPY $vgpr2
  ; GFX8-RA-NEXT:   [[COPY1:%[0-9]+]].sub1:vreg_128 = COPY $vgpr1
  ; GFX8-RA-NEXT:   [[COPY1:%[0-9]+]].sub0:vreg_128 = COPY $vgpr0
  ; GFX8-RA-NEXT:   IMAGE_STORE_V4_V3 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, 15, -1, 0, 0, 0, 0, 0, 0, implicit $exec :: (dereferenceable store (s128), addrspace 8)
  ; GFX8-RA-NEXT:   S_ENDPGM 0
  ;
  ; GFX10-RA-LABEL: name: store_3d
  ; GFX10-RA: bb.0.main_body:
  ; GFX10-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6
  ; GFX10-RA-NEXT: {{  $}}
  ; GFX10-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr6
  ; GFX10-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr5
  ; GFX10-RA-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr4
  ; GFX10-RA-NEXT:   undef [[COPY3:%[0-9]+]].sub3:vreg_128 = COPY $vgpr3
  ; GFX10-RA-NEXT:   [[COPY3:%[0-9]+]].sub2:vreg_128 = COPY $vgpr2
  ; GFX10-RA-NEXT:   [[COPY3:%[0-9]+]].sub1:vreg_128 = COPY $vgpr1
  ; GFX10-RA-NEXT:   [[COPY3:%[0-9]+]].sub0:vreg_128 = COPY $vgpr0
  ; GFX10-RA-NEXT:   IMAGE_STORE_V4_V3_nsa_gfx10 [[COPY3]], [[COPY2]], [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, 15, 2, -1, 0, 0, 0, 0, 0, 0, implicit $exec :: (dereferenceable store (s128), addrspace 8)
  ; GFX10-RA-NEXT:   S_ENDPGM 0
  ;
  ; GFX11-RA-LABEL: name: store_3d
  ; GFX11-RA: bb.0.main_body:
  ; GFX11-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6
  ; GFX11-RA-NEXT: {{  $}}
  ; GFX11-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr6
  ; GFX11-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr5
  ; GFX11-RA-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr4
  ; GFX11-RA-NEXT:   undef [[COPY3:%[0-9]+]].sub3:vreg_128 = COPY $vgpr3
  ; GFX11-RA-NEXT:   [[COPY3:%[0-9]+]].sub2:vreg_128 = COPY $vgpr2
  ; GFX11-RA-NEXT:   [[COPY3:%[0-9]+]].sub1:vreg_128 = COPY $vgpr1
  ; GFX11-RA-NEXT:   [[COPY3:%[0-9]+]].sub0:vreg_128 = COPY $vgpr0
  ; GFX11-RA-NEXT:   IMAGE_STORE_V4_V3_nsa_gfx11 [[COPY3]], [[COPY2]], [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, 15, 2, -1, 0, 0, 0, 0, 0, 0, implicit $exec :: (dereferenceable store (s128), addrspace 8)
  ; GFX11-RA-NEXT:   S_ENDPGM 0
  ;
  ; GFX12-RA-LABEL: name: store_3d
  ; GFX12-RA: bb.0.main_body:
  ; GFX12-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6
  ; GFX12-RA-NEXT: {{  $}}
  ; GFX12-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr6
  ; GFX12-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr5
  ; GFX12-RA-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr4
  ; GFX12-RA-NEXT:   undef [[COPY3:%[0-9]+]].sub3:vreg_128 = COPY $vgpr3
  ; GFX12-RA-NEXT:   [[COPY3:%[0-9]+]].sub2:vreg_128 = COPY $vgpr2
  ; GFX12-RA-NEXT:   [[COPY3:%[0-9]+]].sub1:vreg_128 = COPY $vgpr1
  ; GFX12-RA-NEXT:   [[COPY3:%[0-9]+]].sub0:vreg_128 = COPY $vgpr0
  ; GFX12-RA-NEXT:   IMAGE_STORE_V4_V3_gfx12 [[COPY3]], [[COPY2]], [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, 15, 2, 0, 0, 0, 0, 0, implicit $exec :: (dereferenceable store (s128), addrspace 8)
  ; GFX12-RA-NEXT:   S_ENDPGM 0
main_body:
  call void @llvm.amdgcn.image.store.3d(<4 x float> %vdata, i32 15, i32 %s, i32 %t, i32 %r, <8 x i32> %rsrc, i32 0, i32 0)
  ret void
}
define amdgpu_ps void @store_3d_r128(<4 x i32> inreg %rsrc, <4 x float> %vdata, i32 %s, i32 %t, i32 %r) {
  ; GFX8-RA-LABEL: name: store_3d_r128
  ; GFX8-RA: bb.0.main_body:
  ; GFX8-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6
  ; GFX8-RA-NEXT: {{  $}}
  ; GFX8-RA-NEXT:   undef [[COPY:%[0-9]+]].sub2:vreg_96 = COPY $vgpr6
  ; GFX8-RA-NEXT:   [[COPY:%[0-9]+]].sub1:vreg_96 = COPY $vgpr5
  ; GFX8-RA-NEXT:   [[COPY:%[0-9]+]].sub0:vreg_96 = COPY $vgpr4
  ; GFX8-RA-NEXT:   undef [[COPY1:%[0-9]+]].sub3:vreg_128 = COPY $vgpr3
  ; GFX8-RA-NEXT:   [[COPY1:%[0-9]+]].sub2:vreg_128 = COPY $vgpr2
  ; GFX8-RA-NEXT:   [[COPY1:%[0-9]+]].sub1:vreg_128 = COPY $vgpr1
  ; GFX8-RA-NEXT:   [[COPY1:%[0-9]+]].sub0:vreg_128 = COPY $vgpr0
  ; GFX8-RA-NEXT:   IMAGE_STORE_V4_V3 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, 15, -1, 0, -1, 0, 0, 0, 0, implicit $exec :: (dereferenceable store (s128), addrspace 8)
  ; GFX8-RA-NEXT:   S_ENDPGM 0
  ;
  ; GFX10-RA-LABEL: name: store_3d_r128
  ; GFX10-RA: bb.0.main_body:
  ; GFX10-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6
  ; GFX10-RA-NEXT: {{  $}}
  ; GFX10-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr6
  ; GFX10-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr5
  ; GFX10-RA-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr4
  ; GFX10-RA-NEXT:   undef [[COPY3:%[0-9]+]].sub3:vreg_128 = COPY $vgpr3
  ; GFX10-RA-NEXT:   [[COPY3:%[0-9]+]].sub2:vreg_128 = COPY $vgpr2
  ; GFX10-RA-NEXT:   [[COPY3:%[0-9]+]].sub1:vreg_128 = COPY $vgpr1
  ; GFX10-RA-NEXT:   [[COPY3:%[0-9]+]].sub0:vreg_128 = COPY $vgpr0
  ; GFX10-RA-NEXT:   IMAGE_STORE_V4_V3_nsa_gfx10 [[COPY3]], [[COPY2]], [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, 15, 2, -1, 0, -1, 0, 0, 0, 0, implicit $exec :: (dereferenceable store (s128), addrspace 8)
  ; GFX10-RA-NEXT:   S_ENDPGM 0
  ;
  ; GFX11-RA-LABEL: name: store_3d_r128
  ; GFX11-RA: bb.0.main_body:
  ; GFX11-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6
  ; GFX11-RA-NEXT: {{  $}}
  ; GFX11-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr6
  ; GFX11-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr5
  ; GFX11-RA-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr4
  ; GFX11-RA-NEXT:   undef [[COPY3:%[0-9]+]].sub3:vreg_128 = COPY $vgpr3
  ; GFX11-RA-NEXT:   [[COPY3:%[0-9]+]].sub2:vreg_128 = COPY $vgpr2
  ; GFX11-RA-NEXT:   [[COPY3:%[0-9]+]].sub1:vreg_128 = COPY $vgpr1
  ; GFX11-RA-NEXT:   [[COPY3:%[0-9]+]].sub0:vreg_128 = COPY $vgpr0
  ; GFX11-RA-NEXT:   IMAGE_STORE_V4_V3_nsa_gfx11 [[COPY3]], [[COPY2]], [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, 15, 2, -1, 0, -1, 0, 0, 0, 0, implicit $exec :: (dereferenceable store (s128), addrspace 8)
  ; GFX11-RA-NEXT:   S_ENDPGM 0
  ;
  ; GFX12-RA-LABEL: name: store_3d_r128
  ; GFX12-RA: bb.0.main_body:
  ; GFX12-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $vgpr0, $vgpr1, $vgpr2, $vgpr3, $vgpr4, $vgpr5, $vgpr6
  ; GFX12-RA-NEXT: {{  $}}
  ; GFX12-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr6
  ; GFX12-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr5
  ; GFX12-RA-NEXT:   [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr4
  ; GFX12-RA-NEXT:   undef [[COPY3:%[0-9]+]].sub3:vreg_128 = COPY $vgpr3
  ; GFX12-RA-NEXT:   [[COPY3:%[0-9]+]].sub2:vreg_128 = COPY $vgpr2
  ; GFX12-RA-NEXT:   [[COPY3:%[0-9]+]].sub1:vreg_128 = COPY $vgpr1
  ; GFX12-RA-NEXT:   [[COPY3:%[0-9]+]].sub0:vreg_128 = COPY $vgpr0
  ; GFX12-RA-NEXT:   IMAGE_STORE_V4_V3_gfx12 [[COPY3]], [[COPY2]], [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, 15, 2, 0, -1, 0, 0, 0, implicit $exec :: (dereferenceable store (s128), addrspace 8)
  ; GFX12-RA-NEXT:   S_ENDPGM 0
main_body:
  call void @llvm.amdgcn.image.store.3d(<4 x float> %vdata, i32 15, i32 %s, i32 %t, i32 %r, <4 x i32> %rsrc, i32 0, i32 0)
  ret void
}


define amdgpu_ps <4 x float> @getresinfo_2d(<8 x i32> inreg %rsrc, i32 %mip) {
  ; GFX8-RA-LABEL: name: getresinfo_2d
  ; GFX8-RA: bb.0.main_body:
  ; GFX8-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0
  ; GFX8-RA-NEXT: {{  $}}
  ; GFX8-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX8-RA-NEXT:   [[IMAGE_GET_RESINFO_V4_V1_:%[0-9]+]]:vreg_128 = IMAGE_GET_RESINFO_V4_V1 [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, 15, -1, 0, 0, 0, 0, 0, implicit $exec
  ; GFX8-RA-NEXT:   $vgpr0 = COPY [[IMAGE_GET_RESINFO_V4_V1_]].sub0
  ; GFX8-RA-NEXT:   $vgpr1 = COPY [[IMAGE_GET_RESINFO_V4_V1_]].sub1
  ; GFX8-RA-NEXT:   $vgpr2 = COPY [[IMAGE_GET_RESINFO_V4_V1_]].sub2
  ; GFX8-RA-NEXT:   $vgpr3 = COPY [[IMAGE_GET_RESINFO_V4_V1_]].sub3
  ; GFX8-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, killed $vgpr1, killed $vgpr2, killed $vgpr3
  ;
  ; GFX10-RA-LABEL: name: getresinfo_2d
  ; GFX10-RA: bb.0.main_body:
  ; GFX10-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0
  ; GFX10-RA-NEXT: {{  $}}
  ; GFX10-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX10-RA-NEXT:   [[IMAGE_GET_RESINFO_V4_V1_gfx10_:%[0-9]+]]:vreg_128 = IMAGE_GET_RESINFO_V4_V1_gfx10 [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, 15, 1, -1, 0, 0, 0, 0, 0, implicit $exec
  ; GFX10-RA-NEXT:   $vgpr0 = COPY [[IMAGE_GET_RESINFO_V4_V1_gfx10_]].sub0
  ; GFX10-RA-NEXT:   $vgpr1 = COPY [[IMAGE_GET_RESINFO_V4_V1_gfx10_]].sub1
  ; GFX10-RA-NEXT:   $vgpr2 = COPY [[IMAGE_GET_RESINFO_V4_V1_gfx10_]].sub2
  ; GFX10-RA-NEXT:   $vgpr3 = COPY [[IMAGE_GET_RESINFO_V4_V1_gfx10_]].sub3
  ; GFX10-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, killed $vgpr1, killed $vgpr2, killed $vgpr3
  ;
  ; GFX11-RA-LABEL: name: getresinfo_2d
  ; GFX11-RA: bb.0.main_body:
  ; GFX11-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0
  ; GFX11-RA-NEXT: {{  $}}
  ; GFX11-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX11-RA-NEXT:   [[IMAGE_GET_RESINFO_V4_V1_gfx11_:%[0-9]+]]:vreg_128 = IMAGE_GET_RESINFO_V4_V1_gfx11 [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, 15, 1, -1, 0, 0, 0, 0, 0, implicit $exec
  ; GFX11-RA-NEXT:   $vgpr0 = COPY [[IMAGE_GET_RESINFO_V4_V1_gfx11_]].sub0
  ; GFX11-RA-NEXT:   $vgpr1 = COPY [[IMAGE_GET_RESINFO_V4_V1_gfx11_]].sub1
  ; GFX11-RA-NEXT:   $vgpr2 = COPY [[IMAGE_GET_RESINFO_V4_V1_gfx11_]].sub2
  ; GFX11-RA-NEXT:   $vgpr3 = COPY [[IMAGE_GET_RESINFO_V4_V1_gfx11_]].sub3
  ; GFX11-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, killed $vgpr1, killed $vgpr2, killed $vgpr3
  ;
  ; GFX12-RA-LABEL: name: getresinfo_2d
  ; GFX12-RA: bb.0.main_body:
  ; GFX12-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0
  ; GFX12-RA-NEXT: {{  $}}
  ; GFX12-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX12-RA-NEXT:   [[IMAGE_GET_RESINFO_V4_V1_gfx12_:%[0-9]+]]:vreg_128 = IMAGE_GET_RESINFO_V4_V1_gfx12 [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, 15, 1, 0, 0, 0, 0, implicit $exec
  ; GFX12-RA-NEXT:   $vgpr0 = COPY [[IMAGE_GET_RESINFO_V4_V1_gfx12_]].sub0
  ; GFX12-RA-NEXT:   $vgpr1 = COPY [[IMAGE_GET_RESINFO_V4_V1_gfx12_]].sub1
  ; GFX12-RA-NEXT:   $vgpr2 = COPY [[IMAGE_GET_RESINFO_V4_V1_gfx12_]].sub2
  ; GFX12-RA-NEXT:   $vgpr3 = COPY [[IMAGE_GET_RESINFO_V4_V1_gfx12_]].sub3
  ; GFX12-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, killed $vgpr1, killed $vgpr2, killed $vgpr3
main_body:
  %v = call <4 x float> @llvm.amdgcn.image.getresinfo.2d(i32 15, i32 %mip, <8 x i32> %rsrc, i32 0, i32 0)
  ret <4 x float> %v
}

define amdgpu_ps <4 x float> @getresinfo_2d_r128(<4 x i32> inreg %rsrc, i32 %mip) {
  ; GFX8-RA-LABEL: name: getresinfo_2d_r128
  ; GFX8-RA: bb.0.main_body:
  ; GFX8-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $vgpr0
  ; GFX8-RA-NEXT: {{  $}}
  ; GFX8-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX8-RA-NEXT:   [[IMAGE_GET_RESINFO_V4_V1_:%[0-9]+]]:vreg_128 = IMAGE_GET_RESINFO_V4_V1 [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, 15, -1, 0, -1, 0, 0, 0, implicit $exec
  ; GFX8-RA-NEXT:   $vgpr0 = COPY [[IMAGE_GET_RESINFO_V4_V1_]].sub0
  ; GFX8-RA-NEXT:   $vgpr1 = COPY [[IMAGE_GET_RESINFO_V4_V1_]].sub1
  ; GFX8-RA-NEXT:   $vgpr2 = COPY [[IMAGE_GET_RESINFO_V4_V1_]].sub2
  ; GFX8-RA-NEXT:   $vgpr3 = COPY [[IMAGE_GET_RESINFO_V4_V1_]].sub3
  ; GFX8-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, killed $vgpr1, killed $vgpr2, killed $vgpr3
  ;
  ; GFX10-RA-LABEL: name: getresinfo_2d_r128
  ; GFX10-RA: bb.0.main_body:
  ; GFX10-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $vgpr0
  ; GFX10-RA-NEXT: {{  $}}
  ; GFX10-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX10-RA-NEXT:   [[IMAGE_GET_RESINFO_V4_V1_gfx10_:%[0-9]+]]:vreg_128 = IMAGE_GET_RESINFO_V4_V1_gfx10 [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, 15, 1, -1, 0, -1, 0, 0, 0, implicit $exec
  ; GFX10-RA-NEXT:   $vgpr0 = COPY [[IMAGE_GET_RESINFO_V4_V1_gfx10_]].sub0
  ; GFX10-RA-NEXT:   $vgpr1 = COPY [[IMAGE_GET_RESINFO_V4_V1_gfx10_]].sub1
  ; GFX10-RA-NEXT:   $vgpr2 = COPY [[IMAGE_GET_RESINFO_V4_V1_gfx10_]].sub2
  ; GFX10-RA-NEXT:   $vgpr3 = COPY [[IMAGE_GET_RESINFO_V4_V1_gfx10_]].sub3
  ; GFX10-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, killed $vgpr1, killed $vgpr2, killed $vgpr3
  ;
  ; GFX11-RA-LABEL: name: getresinfo_2d_r128
  ; GFX11-RA: bb.0.main_body:
  ; GFX11-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $vgpr0
  ; GFX11-RA-NEXT: {{  $}}
  ; GFX11-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX11-RA-NEXT:   [[IMAGE_GET_RESINFO_V4_V1_gfx11_:%[0-9]+]]:vreg_128 = IMAGE_GET_RESINFO_V4_V1_gfx11 [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, 15, 1, -1, 0, -1, 0, 0, 0, implicit $exec
  ; GFX11-RA-NEXT:   $vgpr0 = COPY [[IMAGE_GET_RESINFO_V4_V1_gfx11_]].sub0
  ; GFX11-RA-NEXT:   $vgpr1 = COPY [[IMAGE_GET_RESINFO_V4_V1_gfx11_]].sub1
  ; GFX11-RA-NEXT:   $vgpr2 = COPY [[IMAGE_GET_RESINFO_V4_V1_gfx11_]].sub2
  ; GFX11-RA-NEXT:   $vgpr3 = COPY [[IMAGE_GET_RESINFO_V4_V1_gfx11_]].sub3
  ; GFX11-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, killed $vgpr1, killed $vgpr2, killed $vgpr3
  ;
  ; GFX12-RA-LABEL: name: getresinfo_2d_r128
  ; GFX12-RA: bb.0.main_body:
  ; GFX12-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $vgpr0
  ; GFX12-RA-NEXT: {{  $}}
  ; GFX12-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX12-RA-NEXT:   [[IMAGE_GET_RESINFO_V4_V1_gfx12_:%[0-9]+]]:vreg_128 = IMAGE_GET_RESINFO_V4_V1_gfx12 [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, 15, 1, 0, -1, 0, 0, implicit $exec
  ; GFX12-RA-NEXT:   $vgpr0 = COPY [[IMAGE_GET_RESINFO_V4_V1_gfx12_]].sub0
  ; GFX12-RA-NEXT:   $vgpr1 = COPY [[IMAGE_GET_RESINFO_V4_V1_gfx12_]].sub1
  ; GFX12-RA-NEXT:   $vgpr2 = COPY [[IMAGE_GET_RESINFO_V4_V1_gfx12_]].sub2
  ; GFX12-RA-NEXT:   $vgpr3 = COPY [[IMAGE_GET_RESINFO_V4_V1_gfx12_]].sub3
  ; GFX12-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, killed $vgpr1, killed $vgpr2, killed $vgpr3
main_body:
  %v = call <4 x float> @llvm.amdgcn.image.getresinfo.2d(i32 15, i32 %mip, <4 x i32> %rsrc, i32 0, i32 0)
  ret <4 x float> %v
}


define amdgpu_ps float @atomic_swap_1d(<8 x i32> inreg %rsrc, i32 %data, i32 %s) {
  ; GFX8-RA-LABEL: name: atomic_swap_1d
  ; GFX8-RA: bb.0.main_body:
  ; GFX8-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1
  ; GFX8-RA-NEXT: {{  $}}
  ; GFX8-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX8-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX8-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = IMAGE_ATOMIC_SWAP_V1_V1_vi [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, 1, -1, 1, 0, 0, 0, 0, implicit $exec :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX8-RA-NEXT:   $vgpr0 = COPY [[COPY1]]
  ; GFX8-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0
  ;
  ; GFX10-RA-LABEL: name: atomic_swap_1d
  ; GFX10-RA: bb.0.main_body:
  ; GFX10-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1
  ; GFX10-RA-NEXT: {{  $}}
  ; GFX10-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX10-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX10-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = IMAGE_ATOMIC_SWAP_V1_V1_gfx10 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, 1, 0, -1, 1, 0, 0, 0, 0, implicit $exec :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10-RA-NEXT:   $vgpr0 = COPY [[COPY1]]
  ; GFX10-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0
  ;
  ; GFX11-RA-LABEL: name: atomic_swap_1d
  ; GFX11-RA: bb.0.main_body:
  ; GFX11-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1
  ; GFX11-RA-NEXT: {{  $}}
  ; GFX11-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX11-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX11-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = IMAGE_ATOMIC_SWAP_V1_V1_gfx11 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, 1, 0, -1, 1, 0, 0, 0, 0, implicit $exec :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX11-RA-NEXT:   $vgpr0 = COPY [[COPY1]]
  ; GFX11-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0
  ;
  ; GFX12-RA-LABEL: name: atomic_swap_1d
  ; GFX12-RA: bb.0.main_body:
  ; GFX12-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1
  ; GFX12-RA-NEXT: {{  $}}
  ; GFX12-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX12-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX12-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = IMAGE_ATOMIC_SWAP_V1_V1_gfx12 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, 1, 0, 1, 0, 0, 0, implicit $exec :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX12-RA-NEXT:   $vgpr0 = COPY [[COPY1]]
  ; GFX12-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.swap.1d(i32 %data, i32 %s, <8 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_swap_1d_r128(<4 x i32> inreg %rsrc, i32 %data, i32 %s) {
  ; GFX8-RA-LABEL: name: atomic_swap_1d_r128
  ; GFX8-RA: bb.0.main_body:
  ; GFX8-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $vgpr0, $vgpr1
  ; GFX8-RA-NEXT: {{  $}}
  ; GFX8-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX8-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX8-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = IMAGE_ATOMIC_SWAP_V1_V1_vi [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, 1, -1, 1, -1, 0, 0, 0, implicit $exec :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX8-RA-NEXT:   $vgpr0 = COPY [[COPY1]]
  ; GFX8-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0
  ;
  ; GFX10-RA-LABEL: name: atomic_swap_1d_r128
  ; GFX10-RA: bb.0.main_body:
  ; GFX10-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $vgpr0, $vgpr1
  ; GFX10-RA-NEXT: {{  $}}
  ; GFX10-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX10-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX10-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = IMAGE_ATOMIC_SWAP_V1_V1_gfx10 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, 1, 0, -1, 1, -1, 0, 0, 0, implicit $exec :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10-RA-NEXT:   $vgpr0 = COPY [[COPY1]]
  ; GFX10-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0
  ;
  ; GFX11-RA-LABEL: name: atomic_swap_1d_r128
  ; GFX11-RA: bb.0.main_body:
  ; GFX11-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $vgpr0, $vgpr1
  ; GFX11-RA-NEXT: {{  $}}
  ; GFX11-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX11-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX11-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = IMAGE_ATOMIC_SWAP_V1_V1_gfx11 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, 1, 0, -1, 1, -1, 0, 0, 0, implicit $exec :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX11-RA-NEXT:   $vgpr0 = COPY [[COPY1]]
  ; GFX11-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0
  ;
  ; GFX12-RA-LABEL: name: atomic_swap_1d_r128
  ; GFX12-RA: bb.0.main_body:
  ; GFX12-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $vgpr0, $vgpr1
  ; GFX12-RA-NEXT: {{  $}}
  ; GFX12-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX12-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX12-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = IMAGE_ATOMIC_SWAP_V1_V1_gfx12 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, 1, 0, 1, -1, 0, 0, implicit $exec :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX12-RA-NEXT:   $vgpr0 = COPY [[COPY1]]
  ; GFX12-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.swap.1d(i32 %data, i32 %s, <4 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_cmpswap_1d(<8 x i32> inreg %rsrc, i32 %cmp, i32 %swap, i32 %s) {
  ; GFX8-RA-LABEL: name: atomic_cmpswap_1d
  ; GFX8-RA: bb.0.main_body:
  ; GFX8-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1, $vgpr2
  ; GFX8-RA-NEXT: {{  $}}
  ; GFX8-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr2
  ; GFX8-RA-NEXT:   undef [[COPY1:%[0-9]+]].sub1:vreg_64 = COPY $vgpr1
  ; GFX8-RA-NEXT:   [[COPY1:%[0-9]+]].sub0:vreg_64 = COPY $vgpr0
  ; GFX8-RA-NEXT:   [[COPY1:%[0-9]+]]:vreg_64 = IMAGE_ATOMIC_CMPSWAP_V2_V1_vi [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, 3, -1, 1, 0, 0, 0, 0, implicit $exec :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX8-RA-NEXT:   $vgpr0 = COPY [[COPY1]].sub0
  ; GFX8-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0
  ;
  ; GFX10-RA-LABEL: name: atomic_cmpswap_1d
  ; GFX10-RA: bb.0.main_body:
  ; GFX10-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1, $vgpr2
  ; GFX10-RA-NEXT: {{  $}}
  ; GFX10-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr2
  ; GFX10-RA-NEXT:   undef [[COPY1:%[0-9]+]].sub1:vreg_64 = COPY $vgpr1
  ; GFX10-RA-NEXT:   [[COPY1:%[0-9]+]].sub0:vreg_64 = COPY $vgpr0
  ; GFX10-RA-NEXT:   [[COPY1:%[0-9]+]]:vreg_64 = IMAGE_ATOMIC_CMPSWAP_V2_V1_gfx10 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, 3, 0, -1, 1, 0, 0, 0, 0, implicit $exec :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10-RA-NEXT:   $vgpr0 = COPY [[COPY1]].sub0
  ; GFX10-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0
  ;
  ; GFX11-RA-LABEL: name: atomic_cmpswap_1d
  ; GFX11-RA: bb.0.main_body:
  ; GFX11-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1, $vgpr2
  ; GFX11-RA-NEXT: {{  $}}
  ; GFX11-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr2
  ; GFX11-RA-NEXT:   undef [[COPY1:%[0-9]+]].sub1:vreg_64 = COPY $vgpr1
  ; GFX11-RA-NEXT:   [[COPY1:%[0-9]+]].sub0:vreg_64 = COPY $vgpr0
  ; GFX11-RA-NEXT:   [[COPY1:%[0-9]+]]:vreg_64 = IMAGE_ATOMIC_CMPSWAP_V2_V1_gfx11 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, 3, 0, -1, 1, 0, 0, 0, 0, implicit $exec :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX11-RA-NEXT:   $vgpr0 = COPY [[COPY1]].sub0
  ; GFX11-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0
  ;
  ; GFX12-RA-LABEL: name: atomic_cmpswap_1d
  ; GFX12-RA: bb.0.main_body:
  ; GFX12-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1, $vgpr2
  ; GFX12-RA-NEXT: {{  $}}
  ; GFX12-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr2
  ; GFX12-RA-NEXT:   undef [[COPY1:%[0-9]+]].sub1:vreg_64 = COPY $vgpr1
  ; GFX12-RA-NEXT:   [[COPY1:%[0-9]+]].sub0:vreg_64 = COPY $vgpr0
  ; GFX12-RA-NEXT:   [[COPY1:%[0-9]+]]:vreg_64 = IMAGE_ATOMIC_CMPSWAP_V2_V1_gfx12 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, 3, 0, 1, 0, 0, 0, implicit $exec :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX12-RA-NEXT:   $vgpr0 = COPY [[COPY1]].sub0
  ; GFX12-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.cmpswap.1d(i32 %cmp, i32 %swap, i32 %s, <8 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_cmpswap_1d_r128(<4 x i32> inreg %rsrc, i32 %cmp, i32 %swap, i32 %s) {
  ; GFX8-RA-LABEL: name: atomic_cmpswap_1d_r128
  ; GFX8-RA: bb.0.main_body:
  ; GFX8-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $vgpr0, $vgpr1, $vgpr2
  ; GFX8-RA-NEXT: {{  $}}
  ; GFX8-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr2
  ; GFX8-RA-NEXT:   undef [[COPY1:%[0-9]+]].sub1:vreg_64 = COPY $vgpr1
  ; GFX8-RA-NEXT:   [[COPY1:%[0-9]+]].sub0:vreg_64 = COPY $vgpr0
  ; GFX8-RA-NEXT:   [[COPY1:%[0-9]+]]:vreg_64 = IMAGE_ATOMIC_CMPSWAP_V2_V1_vi [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, 3, -1, 1, -1, 0, 0, 0, implicit $exec :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX8-RA-NEXT:   $vgpr0 = COPY [[COPY1]].sub0
  ; GFX8-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0
  ;
  ; GFX10-RA-LABEL: name: atomic_cmpswap_1d_r128
  ; GFX10-RA: bb.0.main_body:
  ; GFX10-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $vgpr0, $vgpr1, $vgpr2
  ; GFX10-RA-NEXT: {{  $}}
  ; GFX10-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr2
  ; GFX10-RA-NEXT:   undef [[COPY1:%[0-9]+]].sub1:vreg_64 = COPY $vgpr1
  ; GFX10-RA-NEXT:   [[COPY1:%[0-9]+]].sub0:vreg_64 = COPY $vgpr0
  ; GFX10-RA-NEXT:   [[COPY1:%[0-9]+]]:vreg_64 = IMAGE_ATOMIC_CMPSWAP_V2_V1_gfx10 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, 3, 0, -1, 1, -1, 0, 0, 0, implicit $exec :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10-RA-NEXT:   $vgpr0 = COPY [[COPY1]].sub0
  ; GFX10-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0
  ;
  ; GFX11-RA-LABEL: name: atomic_cmpswap_1d_r128
  ; GFX11-RA: bb.0.main_body:
  ; GFX11-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $vgpr0, $vgpr1, $vgpr2
  ; GFX11-RA-NEXT: {{  $}}
  ; GFX11-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr2
  ; GFX11-RA-NEXT:   undef [[COPY1:%[0-9]+]].sub1:vreg_64 = COPY $vgpr1
  ; GFX11-RA-NEXT:   [[COPY1:%[0-9]+]].sub0:vreg_64 = COPY $vgpr0
  ; GFX11-RA-NEXT:   [[COPY1:%[0-9]+]]:vreg_64 = IMAGE_ATOMIC_CMPSWAP_V2_V1_gfx11 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, 3, 0, -1, 1, -1, 0, 0, 0, implicit $exec :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX11-RA-NEXT:   $vgpr0 = COPY [[COPY1]].sub0
  ; GFX11-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0
  ;
  ; GFX12-RA-LABEL: name: atomic_cmpswap_1d_r128
  ; GFX12-RA: bb.0.main_body:
  ; GFX12-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $vgpr0, $vgpr1, $vgpr2
  ; GFX12-RA-NEXT: {{  $}}
  ; GFX12-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr2
  ; GFX12-RA-NEXT:   undef [[COPY1:%[0-9]+]].sub1:vreg_64 = COPY $vgpr1
  ; GFX12-RA-NEXT:   [[COPY1:%[0-9]+]].sub0:vreg_64 = COPY $vgpr0
  ; GFX12-RA-NEXT:   [[COPY1:%[0-9]+]]:vreg_64 = IMAGE_ATOMIC_CMPSWAP_V2_V1_gfx12 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, 3, 0, 1, -1, 0, 0, implicit $exec :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX12-RA-NEXT:   $vgpr0 = COPY [[COPY1]].sub0
  ; GFX12-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.cmpswap.1d(i32 %cmp, i32 %swap, i32 %s, <4 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_add_1d(<8 x i32> inreg %rsrc, i32 %data, i32 %s) {
  ; GFX8-RA-LABEL: name: atomic_add_1d
  ; GFX8-RA: bb.0.main_body:
  ; GFX8-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1
  ; GFX8-RA-NEXT: {{  $}}
  ; GFX8-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX8-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX8-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = IMAGE_ATOMIC_ADD_V1_V1_vi [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, 1, -1, 1, 0, 0, 0, 0, implicit $exec :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX8-RA-NEXT:   $vgpr0 = COPY [[COPY1]]
  ; GFX8-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0
  ;
  ; GFX10-RA-LABEL: name: atomic_add_1d
  ; GFX10-RA: bb.0.main_body:
  ; GFX10-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1
  ; GFX10-RA-NEXT: {{  $}}
  ; GFX10-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX10-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX10-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = IMAGE_ATOMIC_ADD_V1_V1_gfx10 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, 1, 0, -1, 1, 0, 0, 0, 0, implicit $exec :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10-RA-NEXT:   $vgpr0 = COPY [[COPY1]]
  ; GFX10-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0
  ;
  ; GFX11-RA-LABEL: name: atomic_add_1d
  ; GFX11-RA: bb.0.main_body:
  ; GFX11-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1
  ; GFX11-RA-NEXT: {{  $}}
  ; GFX11-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX11-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX11-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = IMAGE_ATOMIC_ADD_V1_V1_gfx11 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, 1, 0, -1, 1, 0, 0, 0, 0, implicit $exec :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX11-RA-NEXT:   $vgpr0 = COPY [[COPY1]]
  ; GFX11-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0
  ;
  ; GFX12-RA-LABEL: name: atomic_add_1d
  ; GFX12-RA: bb.0.main_body:
  ; GFX12-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1
  ; GFX12-RA-NEXT: {{  $}}
  ; GFX12-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX12-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX12-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = IMAGE_ATOMIC_ADD_V1_V1_gfx12 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, 1, 0, 1, 0, 0, 0, implicit $exec :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX12-RA-NEXT:   $vgpr0 = COPY [[COPY1]]
  ; GFX12-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.add.1d(i32 %data, i32 %s, <8 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}

define amdgpu_ps float @atomic_add_1d_r128(<4 x i32> inreg %rsrc, i32 %data, i32 %s) {
  ; GFX8-RA-LABEL: name: atomic_add_1d_r128
  ; GFX8-RA: bb.0.main_body:
  ; GFX8-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $vgpr0, $vgpr1
  ; GFX8-RA-NEXT: {{  $}}
  ; GFX8-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX8-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX8-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = IMAGE_ATOMIC_ADD_V1_V1_vi [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, 1, -1, 1, -1, 0, 0, 0, implicit $exec :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX8-RA-NEXT:   $vgpr0 = COPY [[COPY1]]
  ; GFX8-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0
  ;
  ; GFX10-RA-LABEL: name: atomic_add_1d_r128
  ; GFX10-RA: bb.0.main_body:
  ; GFX10-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $vgpr0, $vgpr1
  ; GFX10-RA-NEXT: {{  $}}
  ; GFX10-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX10-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX10-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = IMAGE_ATOMIC_ADD_V1_V1_gfx10 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, 1, 0, -1, 1, -1, 0, 0, 0, implicit $exec :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX10-RA-NEXT:   $vgpr0 = COPY [[COPY1]]
  ; GFX10-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0
  ;
  ; GFX11-RA-LABEL: name: atomic_add_1d_r128
  ; GFX11-RA: bb.0.main_body:
  ; GFX11-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $vgpr0, $vgpr1
  ; GFX11-RA-NEXT: {{  $}}
  ; GFX11-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX11-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX11-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = IMAGE_ATOMIC_ADD_V1_V1_gfx11 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, 1, 0, -1, 1, -1, 0, 0, 0, implicit $exec :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX11-RA-NEXT:   $vgpr0 = COPY [[COPY1]]
  ; GFX11-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0
  ;
  ; GFX12-RA-LABEL: name: atomic_add_1d_r128
  ; GFX12-RA: bb.0.main_body:
  ; GFX12-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $vgpr0, $vgpr1
  ; GFX12-RA-NEXT: {{  $}}
  ; GFX12-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX12-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX12-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = IMAGE_ATOMIC_ADD_V1_V1_gfx12 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, 1, 0, 1, -1, 0, 0, implicit $exec :: (volatile dereferenceable load store (s32), addrspace 8)
  ; GFX12-RA-NEXT:   $vgpr0 = COPY [[COPY1]]
  ; GFX12-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0
main_body:
  %v = call i32 @llvm.amdgcn.image.atomic.add.1d(i32 %data, i32 %s, <4 x i32> %rsrc, i32 0, i32 0)
  %out = bitcast i32 %v to float
  ret float %out
}


define amdgpu_ps <4 x float> @sample_1d(<8 x i32> inreg %rsrc, <4 x i32> inreg %samp, float %s) {
  ; GFX8-RA-LABEL: name: sample_1d
  ; GFX8-RA: bb.0.main_body:
  ; GFX8-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $sgpr10, $sgpr11, $vgpr0
  ; GFX8-RA-NEXT: {{  $}}
  ; GFX8-RA-NEXT:   renamable $sgpr12_sgpr13 = COPY $exec
  ; GFX8-RA-NEXT:   $exec = S_WQM_B64 $exec, implicit-def $scc
  ; GFX8-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX8-RA-NEXT:   $exec = S_AND_B64 $exec, killed renamable $sgpr12_sgpr13, implicit-def $scc
  ; GFX8-RA-NEXT:   [[IMAGE_SAMPLE_V4_V1_:%[0-9]+]]:vreg_128 = IMAGE_SAMPLE_V4_V1 [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, killed renamable $sgpr8_sgpr9_sgpr10_sgpr11, 15, 0, 0, 0, 0, 0, 0, 0, implicit $exec :: (dereferenceable load (s128), addrspace 8)
  ; GFX8-RA-NEXT:   $vgpr0 = COPY [[IMAGE_SAMPLE_V4_V1_]].sub0
  ; GFX8-RA-NEXT:   $vgpr1 = COPY [[IMAGE_SAMPLE_V4_V1_]].sub1
  ; GFX8-RA-NEXT:   $vgpr2 = COPY [[IMAGE_SAMPLE_V4_V1_]].sub2
  ; GFX8-RA-NEXT:   $vgpr3 = COPY [[IMAGE_SAMPLE_V4_V1_]].sub3
  ; GFX8-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, killed $vgpr1, killed $vgpr2, killed $vgpr3
  ;
  ; GFX10-RA-LABEL: name: sample_1d
  ; GFX10-RA: bb.0.main_body:
  ; GFX10-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $sgpr10, $sgpr11, $vgpr0
  ; GFX10-RA-NEXT: {{  $}}
  ; GFX10-RA-NEXT:   renamable $sgpr12 = COPY $exec_lo
  ; GFX10-RA-NEXT:   $exec_lo = S_WQM_B32 $exec_lo, implicit-def $scc
  ; GFX10-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX10-RA-NEXT:   $exec_lo = S_AND_B32 $exec_lo, killed renamable $sgpr12, implicit-def $scc
  ; GFX10-RA-NEXT:   [[IMAGE_SAMPLE_V4_V1_gfx10_:%[0-9]+]]:vreg_128 = IMAGE_SAMPLE_V4_V1_gfx10 [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, killed renamable $sgpr8_sgpr9_sgpr10_sgpr11, 15, 0, 0, 0, 0, 0, 0, 0, 0, implicit $exec :: (dereferenceable load (s128), addrspace 8)
  ; GFX10-RA-NEXT:   $vgpr0 = COPY [[IMAGE_SAMPLE_V4_V1_gfx10_]].sub0
  ; GFX10-RA-NEXT:   $vgpr1 = COPY [[IMAGE_SAMPLE_V4_V1_gfx10_]].sub1
  ; GFX10-RA-NEXT:   $vgpr2 = COPY [[IMAGE_SAMPLE_V4_V1_gfx10_]].sub2
  ; GFX10-RA-NEXT:   $vgpr3 = COPY [[IMAGE_SAMPLE_V4_V1_gfx10_]].sub3
  ; GFX10-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, killed $vgpr1, killed $vgpr2, killed $vgpr3
  ;
  ; GFX11-RA-LABEL: name: sample_1d
  ; GFX11-RA: bb.0.main_body:
  ; GFX11-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $sgpr10, $sgpr11, $vgpr0
  ; GFX11-RA-NEXT: {{  $}}
  ; GFX11-RA-NEXT:   renamable $sgpr12 = COPY $exec_lo
  ; GFX11-RA-NEXT:   $exec_lo = S_WQM_B32 $exec_lo, implicit-def $scc
  ; GFX11-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX11-RA-NEXT:   $exec_lo = S_AND_B32 $exec_lo, killed renamable $sgpr12, implicit-def $scc
  ; GFX11-RA-NEXT:   [[IMAGE_SAMPLE_V4_V1_gfx11_:%[0-9]+]]:vreg_128 = IMAGE_SAMPLE_V4_V1_gfx11 [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, killed renamable $sgpr8_sgpr9_sgpr10_sgpr11, 15, 0, 0, 0, 0, 0, 0, 0, 0, implicit $exec :: (dereferenceable load (s128), addrspace 8)
  ; GFX11-RA-NEXT:   $vgpr0 = COPY [[IMAGE_SAMPLE_V4_V1_gfx11_]].sub0
  ; GFX11-RA-NEXT:   $vgpr1 = COPY [[IMAGE_SAMPLE_V4_V1_gfx11_]].sub1
  ; GFX11-RA-NEXT:   $vgpr2 = COPY [[IMAGE_SAMPLE_V4_V1_gfx11_]].sub2
  ; GFX11-RA-NEXT:   $vgpr3 = COPY [[IMAGE_SAMPLE_V4_V1_gfx11_]].sub3
  ; GFX11-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, killed $vgpr1, killed $vgpr2, killed $vgpr3
  ;
  ; GFX12-RA-LABEL: name: sample_1d
  ; GFX12-RA: bb.0.main_body:
  ; GFX12-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $sgpr10, $sgpr11, $vgpr0
  ; GFX12-RA-NEXT: {{  $}}
  ; GFX12-RA-NEXT:   renamable $sgpr12 = COPY $exec_lo
  ; GFX12-RA-NEXT:   $exec_lo = S_WQM_B32 $exec_lo, implicit-def $scc
  ; GFX12-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX12-RA-NEXT:   $exec_lo = S_AND_B32 $exec_lo, killed renamable $sgpr12, implicit-def $scc
  ; GFX12-RA-NEXT:   [[IMAGE_SAMPLE_V4_V1_gfx12_:%[0-9]+]]:vreg_128 = IMAGE_SAMPLE_V4_V1_gfx12 [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, killed renamable $sgpr8_sgpr9_sgpr10_sgpr11, 15, 0, 0, 0, 0, 0, 0, 0, 0, implicit $exec :: (dereferenceable load (s128), addrspace 8)
  ; GFX12-RA-NEXT:   $vgpr0 = COPY [[IMAGE_SAMPLE_V4_V1_gfx12_]].sub0
  ; GFX12-RA-NEXT:   $vgpr1 = COPY [[IMAGE_SAMPLE_V4_V1_gfx12_]].sub1
  ; GFX12-RA-NEXT:   $vgpr2 = COPY [[IMAGE_SAMPLE_V4_V1_gfx12_]].sub2
  ; GFX12-RA-NEXT:   $vgpr3 = COPY [[IMAGE_SAMPLE_V4_V1_gfx12_]].sub3
  ; GFX12-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, killed $vgpr1, killed $vgpr2, killed $vgpr3
main_body:
  %v = call <4 x float> @llvm.amdgcn.image.sample.1d(i32 15, float %s, <8 x i32> %rsrc, <4 x i32> %samp, i1 0, i32 0, i32 0)
  ret <4 x float> %v
}

define amdgpu_ps <4 x float> @sample_1d_r128(<4 x i32> inreg %rsrc, <4 x i32> inreg %samp, float %s) {
  ; GFX8-RA-LABEL: name: sample_1d_r128
  ; GFX8-RA: bb.0.main_body:
  ; GFX8-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0
  ; GFX8-RA-NEXT: {{  $}}
  ; GFX8-RA-NEXT:   renamable $sgpr8_sgpr9 = COPY $exec
  ; GFX8-RA-NEXT:   $exec = S_WQM_B64 $exec, implicit-def $scc
  ; GFX8-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX8-RA-NEXT:   $exec = S_AND_B64 $exec, killed renamable $sgpr8_sgpr9, implicit-def $scc
  ; GFX8-RA-NEXT:   [[IMAGE_SAMPLE_V4_V1_:%[0-9]+]]:vreg_128 = IMAGE_SAMPLE_V4_V1 [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, killed renamable $sgpr4_sgpr5_sgpr6_sgpr7, 15, 0, 0, -1, 0, 0, 0, 0, implicit $exec :: (dereferenceable load (s128), addrspace 8)
  ; GFX8-RA-NEXT:   $vgpr0 = COPY [[IMAGE_SAMPLE_V4_V1_]].sub0
  ; GFX8-RA-NEXT:   $vgpr1 = COPY [[IMAGE_SAMPLE_V4_V1_]].sub1
  ; GFX8-RA-NEXT:   $vgpr2 = COPY [[IMAGE_SAMPLE_V4_V1_]].sub2
  ; GFX8-RA-NEXT:   $vgpr3 = COPY [[IMAGE_SAMPLE_V4_V1_]].sub3
  ; GFX8-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, killed $vgpr1, killed $vgpr2, killed $vgpr3
  ;
  ; GFX10-RA-LABEL: name: sample_1d_r128
  ; GFX10-RA: bb.0.main_body:
  ; GFX10-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0
  ; GFX10-RA-NEXT: {{  $}}
  ; GFX10-RA-NEXT:   renamable $sgpr8 = COPY $exec_lo
  ; GFX10-RA-NEXT:   $exec_lo = S_WQM_B32 $exec_lo, implicit-def $scc
  ; GFX10-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX10-RA-NEXT:   $exec_lo = S_AND_B32 $exec_lo, killed renamable $sgpr8, implicit-def $scc
  ; GFX10-RA-NEXT:   [[IMAGE_SAMPLE_V4_V1_gfx10_:%[0-9]+]]:vreg_128 = IMAGE_SAMPLE_V4_V1_gfx10 [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, killed renamable $sgpr4_sgpr5_sgpr6_sgpr7, 15, 0, 0, 0, -1, 0, 0, 0, 0, implicit $exec :: (dereferenceable load (s128), addrspace 8)
  ; GFX10-RA-NEXT:   $vgpr0 = COPY [[IMAGE_SAMPLE_V4_V1_gfx10_]].sub0
  ; GFX10-RA-NEXT:   $vgpr1 = COPY [[IMAGE_SAMPLE_V4_V1_gfx10_]].sub1
  ; GFX10-RA-NEXT:   $vgpr2 = COPY [[IMAGE_SAMPLE_V4_V1_gfx10_]].sub2
  ; GFX10-RA-NEXT:   $vgpr3 = COPY [[IMAGE_SAMPLE_V4_V1_gfx10_]].sub3
  ; GFX10-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, killed $vgpr1, killed $vgpr2, killed $vgpr3
  ;
  ; GFX11-RA-LABEL: name: sample_1d_r128
  ; GFX11-RA: bb.0.main_body:
  ; GFX11-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0
  ; GFX11-RA-NEXT: {{  $}}
  ; GFX11-RA-NEXT:   renamable $sgpr8 = COPY $exec_lo
  ; GFX11-RA-NEXT:   $exec_lo = S_WQM_B32 $exec_lo, implicit-def $scc
  ; GFX11-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX11-RA-NEXT:   $exec_lo = S_AND_B32 $exec_lo, killed renamable $sgpr8, implicit-def $scc
  ; GFX11-RA-NEXT:   [[IMAGE_SAMPLE_V4_V1_gfx11_:%[0-9]+]]:vreg_128 = IMAGE_SAMPLE_V4_V1_gfx11 [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, killed renamable $sgpr4_sgpr5_sgpr6_sgpr7, 15, 0, 0, 0, -1, 0, 0, 0, 0, implicit $exec :: (dereferenceable load (s128), addrspace 8)
  ; GFX11-RA-NEXT:   $vgpr0 = COPY [[IMAGE_SAMPLE_V4_V1_gfx11_]].sub0
  ; GFX11-RA-NEXT:   $vgpr1 = COPY [[IMAGE_SAMPLE_V4_V1_gfx11_]].sub1
  ; GFX11-RA-NEXT:   $vgpr2 = COPY [[IMAGE_SAMPLE_V4_V1_gfx11_]].sub2
  ; GFX11-RA-NEXT:   $vgpr3 = COPY [[IMAGE_SAMPLE_V4_V1_gfx11_]].sub3
  ; GFX11-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, killed $vgpr1, killed $vgpr2, killed $vgpr3
  ;
  ; GFX12-RA-LABEL: name: sample_1d_r128
  ; GFX12-RA: bb.0.main_body:
  ; GFX12-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0
  ; GFX12-RA-NEXT: {{  $}}
  ; GFX12-RA-NEXT:   renamable $sgpr8 = COPY $exec_lo
  ; GFX12-RA-NEXT:   $exec_lo = S_WQM_B32 $exec_lo, implicit-def $scc
  ; GFX12-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX12-RA-NEXT:   $exec_lo = S_AND_B32 $exec_lo, killed renamable $sgpr8, implicit-def $scc
  ; GFX12-RA-NEXT:   [[IMAGE_SAMPLE_V4_V1_gfx12_:%[0-9]+]]:vreg_128 = IMAGE_SAMPLE_V4_V1_gfx12 [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, killed renamable $sgpr4_sgpr5_sgpr6_sgpr7, 15, 0, 0, 0, -1, 0, 0, 0, 0, implicit $exec :: (dereferenceable load (s128), addrspace 8)
  ; GFX12-RA-NEXT:   $vgpr0 = COPY [[IMAGE_SAMPLE_V4_V1_gfx12_]].sub0
  ; GFX12-RA-NEXT:   $vgpr1 = COPY [[IMAGE_SAMPLE_V4_V1_gfx12_]].sub1
  ; GFX12-RA-NEXT:   $vgpr2 = COPY [[IMAGE_SAMPLE_V4_V1_gfx12_]].sub2
  ; GFX12-RA-NEXT:   $vgpr3 = COPY [[IMAGE_SAMPLE_V4_V1_gfx12_]].sub3
  ; GFX12-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, killed $vgpr1, killed $vgpr2, killed $vgpr3
main_body:
  %v = call <4 x float> @llvm.amdgcn.image.sample.1d(i32 15, float %s, <4 x i32> %rsrc, <4 x i32> %samp, i1 0, i32 0, i32 0)
  ret <4 x float> %v
}


define amdgpu_ps <4 x float> @gather4_2d(<8 x i32> inreg %rsrc, <4 x i32> inreg %samp, float %s, float %t) {
  ; GFX8-RA-LABEL: name: gather4_2d
  ; GFX8-RA: bb.0.main_body:
  ; GFX8-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $sgpr10, $sgpr11, $vgpr0, $vgpr1
  ; GFX8-RA-NEXT: {{  $}}
  ; GFX8-RA-NEXT:   renamable $sgpr12_sgpr13 = COPY $exec
  ; GFX8-RA-NEXT:   $exec = S_WQM_B64 $exec, implicit-def $scc
  ; GFX8-RA-NEXT:   undef [[COPY:%[0-9]+]].sub1:vreg_64 = COPY $vgpr1
  ; GFX8-RA-NEXT:   [[COPY:%[0-9]+]].sub0:vreg_64 = COPY $vgpr0
  ; GFX8-RA-NEXT:   $exec = S_AND_B64 $exec, killed renamable $sgpr12_sgpr13, implicit-def $scc
  ; GFX8-RA-NEXT:   [[IMAGE_GATHER4_V4_V2_:%[0-9]+]]:vreg_128 = IMAGE_GATHER4_V4_V2 [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, killed renamable $sgpr8_sgpr9_sgpr10_sgpr11, 1, 0, 0, 0, 0, 0, 0, 0, implicit $exec :: (dereferenceable load (s128), addrspace 8)
  ; GFX8-RA-NEXT:   $vgpr0 = COPY [[IMAGE_GATHER4_V4_V2_]].sub0
  ; GFX8-RA-NEXT:   $vgpr1 = COPY [[IMAGE_GATHER4_V4_V2_]].sub1
  ; GFX8-RA-NEXT:   $vgpr2 = COPY [[IMAGE_GATHER4_V4_V2_]].sub2
  ; GFX8-RA-NEXT:   $vgpr3 = COPY [[IMAGE_GATHER4_V4_V2_]].sub3
  ; GFX8-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, $vgpr1, killed $vgpr2, killed $vgpr3
  ;
  ; GFX10-RA-LABEL: name: gather4_2d
  ; GFX10-RA: bb.0.main_body:
  ; GFX10-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $sgpr10, $sgpr11, $vgpr0, $vgpr1
  ; GFX10-RA-NEXT: {{  $}}
  ; GFX10-RA-NEXT:   renamable $sgpr12 = COPY $exec_lo
  ; GFX10-RA-NEXT:   $exec_lo = S_WQM_B32 $exec_lo, implicit-def $scc
  ; GFX10-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX10-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX10-RA-NEXT:   $exec_lo = S_AND_B32 $exec_lo, killed renamable $sgpr12, implicit-def $scc
  ; GFX10-RA-NEXT:   [[IMAGE_GATHER4_V4_V2_nsa_gfx10_:%[0-9]+]]:vreg_128 = IMAGE_GATHER4_V4_V2_nsa_gfx10 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, killed renamable $sgpr8_sgpr9_sgpr10_sgpr11, 1, 1, 0, 0, 0, 0, 0, 0, 0, implicit $exec :: (dereferenceable load (s128), addrspace 8)
  ; GFX10-RA-NEXT:   $vgpr0 = COPY [[IMAGE_GATHER4_V4_V2_nsa_gfx10_]].sub0
  ; GFX10-RA-NEXT:   $vgpr1 = COPY [[IMAGE_GATHER4_V4_V2_nsa_gfx10_]].sub1
  ; GFX10-RA-NEXT:   $vgpr2 = COPY [[IMAGE_GATHER4_V4_V2_nsa_gfx10_]].sub2
  ; GFX10-RA-NEXT:   $vgpr3 = COPY [[IMAGE_GATHER4_V4_V2_nsa_gfx10_]].sub3
  ; GFX10-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, $vgpr1, killed $vgpr2, killed $vgpr3
  ;
  ; GFX11-RA-LABEL: name: gather4_2d
  ; GFX11-RA: bb.0.main_body:
  ; GFX11-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $sgpr10, $sgpr11, $vgpr0, $vgpr1
  ; GFX11-RA-NEXT: {{  $}}
  ; GFX11-RA-NEXT:   renamable $sgpr12 = COPY $exec_lo
  ; GFX11-RA-NEXT:   $exec_lo = S_WQM_B32 $exec_lo, implicit-def $scc
  ; GFX11-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX11-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX11-RA-NEXT:   $exec_lo = S_AND_B32 $exec_lo, killed renamable $sgpr12, implicit-def $scc
  ; GFX11-RA-NEXT:   [[IMAGE_GATHER4_V4_V2_nsa_gfx11_:%[0-9]+]]:vreg_128 = IMAGE_GATHER4_V4_V2_nsa_gfx11 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, killed renamable $sgpr8_sgpr9_sgpr10_sgpr11, 1, 1, 0, 0, 0, 0, 0, 0, 0, implicit $exec :: (dereferenceable load (s128), addrspace 8)
  ; GFX11-RA-NEXT:   $vgpr0 = COPY [[IMAGE_GATHER4_V4_V2_nsa_gfx11_]].sub0
  ; GFX11-RA-NEXT:   $vgpr1 = COPY [[IMAGE_GATHER4_V4_V2_nsa_gfx11_]].sub1
  ; GFX11-RA-NEXT:   $vgpr2 = COPY [[IMAGE_GATHER4_V4_V2_nsa_gfx11_]].sub2
  ; GFX11-RA-NEXT:   $vgpr3 = COPY [[IMAGE_GATHER4_V4_V2_nsa_gfx11_]].sub3
  ; GFX11-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, $vgpr1, killed $vgpr2, killed $vgpr3
  ;
  ; GFX12-RA-LABEL: name: gather4_2d
  ; GFX12-RA: bb.0.main_body:
  ; GFX12-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $sgpr10, $sgpr11, $vgpr0, $vgpr1
  ; GFX12-RA-NEXT: {{  $}}
  ; GFX12-RA-NEXT:   renamable $sgpr12 = COPY $exec_lo
  ; GFX12-RA-NEXT:   $exec_lo = S_WQM_B32 $exec_lo, implicit-def $scc
  ; GFX12-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX12-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX12-RA-NEXT:   $exec_lo = S_AND_B32 $exec_lo, killed renamable $sgpr12, implicit-def $scc
  ; GFX12-RA-NEXT:   [[IMAGE_GATHER4_V4_V2_gfx12_:%[0-9]+]]:vreg_128 = IMAGE_GATHER4_V4_V2_gfx12 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, killed renamable $sgpr8_sgpr9_sgpr10_sgpr11, 1, 1, 0, 0, 0, 0, 0, 0, 0, implicit $exec :: (dereferenceable load (s128), addrspace 8)
  ; GFX12-RA-NEXT:   $vgpr0 = COPY [[IMAGE_GATHER4_V4_V2_gfx12_]].sub0
  ; GFX12-RA-NEXT:   $vgpr1 = COPY [[IMAGE_GATHER4_V4_V2_gfx12_]].sub1
  ; GFX12-RA-NEXT:   $vgpr2 = COPY [[IMAGE_GATHER4_V4_V2_gfx12_]].sub2
  ; GFX12-RA-NEXT:   $vgpr3 = COPY [[IMAGE_GATHER4_V4_V2_gfx12_]].sub3
  ; GFX12-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, $vgpr1, killed $vgpr2, killed $vgpr3
main_body:
  %v = call <4 x float> @llvm.amdgcn.image.gather4.2d(i32 1, float %s, float %t, <8 x i32> %rsrc, <4 x i32> %samp, i1 0, i32 0, i32 0)
  ret <4 x float> %v
}

define amdgpu_ps <4 x float> @gather4_2d_r128(<4 x i32> inreg %rsrc, <4 x i32> inreg %samp, float %s, float %t) {
  ; GFX8-RA-LABEL: name: gather4_2d_r128
  ; GFX8-RA: bb.0.main_body:
  ; GFX8-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1
  ; GFX8-RA-NEXT: {{  $}}
  ; GFX8-RA-NEXT:   renamable $sgpr8_sgpr9 = COPY $exec
  ; GFX8-RA-NEXT:   $exec = S_WQM_B64 $exec, implicit-def $scc
  ; GFX8-RA-NEXT:   undef [[COPY:%[0-9]+]].sub1:vreg_64 = COPY $vgpr1
  ; GFX8-RA-NEXT:   [[COPY:%[0-9]+]].sub0:vreg_64 = COPY $vgpr0
  ; GFX8-RA-NEXT:   $exec = S_AND_B64 $exec, killed renamable $sgpr8_sgpr9, implicit-def $scc
  ; GFX8-RA-NEXT:   [[IMAGE_GATHER4_V4_V2_:%[0-9]+]]:vreg_128 = IMAGE_GATHER4_V4_V2 [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, killed renamable $sgpr4_sgpr5_sgpr6_sgpr7, 1, 0, 0, -1, 0, 0, 0, 0, implicit $exec :: (dereferenceable load (s128), addrspace 8)
  ; GFX8-RA-NEXT:   $vgpr0 = COPY [[IMAGE_GATHER4_V4_V2_]].sub0
  ; GFX8-RA-NEXT:   $vgpr1 = COPY [[IMAGE_GATHER4_V4_V2_]].sub1
  ; GFX8-RA-NEXT:   $vgpr2 = COPY [[IMAGE_GATHER4_V4_V2_]].sub2
  ; GFX8-RA-NEXT:   $vgpr3 = COPY [[IMAGE_GATHER4_V4_V2_]].sub3
  ; GFX8-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, $vgpr1, killed $vgpr2, killed $vgpr3
  ;
  ; GFX10-RA-LABEL: name: gather4_2d_r128
  ; GFX10-RA: bb.0.main_body:
  ; GFX10-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1
  ; GFX10-RA-NEXT: {{  $}}
  ; GFX10-RA-NEXT:   renamable $sgpr8 = COPY $exec_lo
  ; GFX10-RA-NEXT:   $exec_lo = S_WQM_B32 $exec_lo, implicit-def $scc
  ; GFX10-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX10-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX10-RA-NEXT:   $exec_lo = S_AND_B32 $exec_lo, killed renamable $sgpr8, implicit-def $scc
  ; GFX10-RA-NEXT:   [[IMAGE_GATHER4_V4_V2_nsa_gfx10_:%[0-9]+]]:vreg_128 = IMAGE_GATHER4_V4_V2_nsa_gfx10 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, killed renamable $sgpr4_sgpr5_sgpr6_sgpr7, 1, 1, 0, 0, -1, 0, 0, 0, 0, implicit $exec :: (dereferenceable load (s128), addrspace 8)
  ; GFX10-RA-NEXT:   $vgpr0 = COPY [[IMAGE_GATHER4_V4_V2_nsa_gfx10_]].sub0
  ; GFX10-RA-NEXT:   $vgpr1 = COPY [[IMAGE_GATHER4_V4_V2_nsa_gfx10_]].sub1
  ; GFX10-RA-NEXT:   $vgpr2 = COPY [[IMAGE_GATHER4_V4_V2_nsa_gfx10_]].sub2
  ; GFX10-RA-NEXT:   $vgpr3 = COPY [[IMAGE_GATHER4_V4_V2_nsa_gfx10_]].sub3
  ; GFX10-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, $vgpr1, killed $vgpr2, killed $vgpr3
  ;
  ; GFX11-RA-LABEL: name: gather4_2d_r128
  ; GFX11-RA: bb.0.main_body:
  ; GFX11-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1
  ; GFX11-RA-NEXT: {{  $}}
  ; GFX11-RA-NEXT:   renamable $sgpr8 = COPY $exec_lo
  ; GFX11-RA-NEXT:   $exec_lo = S_WQM_B32 $exec_lo, implicit-def $scc
  ; GFX11-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX11-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX11-RA-NEXT:   $exec_lo = S_AND_B32 $exec_lo, killed renamable $sgpr8, implicit-def $scc
  ; GFX11-RA-NEXT:   [[IMAGE_GATHER4_V4_V2_nsa_gfx11_:%[0-9]+]]:vreg_128 = IMAGE_GATHER4_V4_V2_nsa_gfx11 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, killed renamable $sgpr4_sgpr5_sgpr6_sgpr7, 1, 1, 0, 0, -1, 0, 0, 0, 0, implicit $exec :: (dereferenceable load (s128), addrspace 8)
  ; GFX11-RA-NEXT:   $vgpr0 = COPY [[IMAGE_GATHER4_V4_V2_nsa_gfx11_]].sub0
  ; GFX11-RA-NEXT:   $vgpr1 = COPY [[IMAGE_GATHER4_V4_V2_nsa_gfx11_]].sub1
  ; GFX11-RA-NEXT:   $vgpr2 = COPY [[IMAGE_GATHER4_V4_V2_nsa_gfx11_]].sub2
  ; GFX11-RA-NEXT:   $vgpr3 = COPY [[IMAGE_GATHER4_V4_V2_nsa_gfx11_]].sub3
  ; GFX11-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, $vgpr1, killed $vgpr2, killed $vgpr3
  ;
  ; GFX12-RA-LABEL: name: gather4_2d_r128
  ; GFX12-RA: bb.0.main_body:
  ; GFX12-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1
  ; GFX12-RA-NEXT: {{  $}}
  ; GFX12-RA-NEXT:   renamable $sgpr8 = COPY $exec_lo
  ; GFX12-RA-NEXT:   $exec_lo = S_WQM_B32 $exec_lo, implicit-def $scc
  ; GFX12-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX12-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX12-RA-NEXT:   $exec_lo = S_AND_B32 $exec_lo, killed renamable $sgpr8, implicit-def $scc
  ; GFX12-RA-NEXT:   [[IMAGE_GATHER4_V4_V2_gfx12_:%[0-9]+]]:vreg_128 = IMAGE_GATHER4_V4_V2_gfx12 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, killed renamable $sgpr4_sgpr5_sgpr6_sgpr7, 1, 1, 0, 0, -1, 0, 0, 0, 0, implicit $exec :: (dereferenceable load (s128), addrspace 8)
  ; GFX12-RA-NEXT:   $vgpr0 = COPY [[IMAGE_GATHER4_V4_V2_gfx12_]].sub0
  ; GFX12-RA-NEXT:   $vgpr1 = COPY [[IMAGE_GATHER4_V4_V2_gfx12_]].sub1
  ; GFX12-RA-NEXT:   $vgpr2 = COPY [[IMAGE_GATHER4_V4_V2_gfx12_]].sub2
  ; GFX12-RA-NEXT:   $vgpr3 = COPY [[IMAGE_GATHER4_V4_V2_gfx12_]].sub3
  ; GFX12-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, $vgpr1, killed $vgpr2, killed $vgpr3
main_body:
  %v = call <4 x float> @llvm.amdgcn.image.gather4.2d(i32 1, float %s, float %t, <4 x i32> %rsrc, <4 x i32> %samp, i1 0, i32 0, i32 0)
  ret <4 x float> %v
}


define amdgpu_ps <2 x float> @getlod_2d(<8 x i32> inreg %rsrc, <4 x i32> inreg %samp, float %s, float %t) {
  ; GFX8-RA-LABEL: name: getlod_2d
  ; GFX8-RA: bb.0.main_body:
  ; GFX8-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $sgpr10, $sgpr11, $vgpr0, $vgpr1
  ; GFX8-RA-NEXT: {{  $}}
  ; GFX8-RA-NEXT:   renamable $sgpr12_sgpr13 = COPY $exec
  ; GFX8-RA-NEXT:   $exec = S_WQM_B64 $exec, implicit-def $scc
  ; GFX8-RA-NEXT:   undef [[COPY:%[0-9]+]].sub1:vreg_64 = COPY $vgpr1
  ; GFX8-RA-NEXT:   [[COPY:%[0-9]+]].sub0:vreg_64 = COPY $vgpr0
  ; GFX8-RA-NEXT:   $exec = S_AND_B64 $exec, killed renamable $sgpr12_sgpr13, implicit-def $scc
  ; GFX8-RA-NEXT:   [[IMAGE_GET_LOD_V2_V2_:%[0-9]+]]:vreg_64 = IMAGE_GET_LOD_V2_V2 [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, killed renamable $sgpr8_sgpr9_sgpr10_sgpr11, 3, 0, 0, 0, 0, 0, 0, implicit $exec
  ; GFX8-RA-NEXT:   $vgpr0 = COPY [[IMAGE_GET_LOD_V2_V2_]].sub0
  ; GFX8-RA-NEXT:   $vgpr1 = COPY [[IMAGE_GET_LOD_V2_V2_]].sub1
  ; GFX8-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, $vgpr1
  ;
  ; GFX10-RA-LABEL: name: getlod_2d
  ; GFX10-RA: bb.0.main_body:
  ; GFX10-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $sgpr10, $sgpr11, $vgpr0, $vgpr1
  ; GFX10-RA-NEXT: {{  $}}
  ; GFX10-RA-NEXT:   renamable $sgpr12 = COPY $exec_lo
  ; GFX10-RA-NEXT:   $exec_lo = S_WQM_B32 $exec_lo, implicit-def $scc
  ; GFX10-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX10-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX10-RA-NEXT:   $exec_lo = S_AND_B32 $exec_lo, killed renamable $sgpr12, implicit-def $scc
  ; GFX10-RA-NEXT:   [[IMAGE_GET_LOD_V2_V2_nsa_gfx10_:%[0-9]+]]:vreg_64 = IMAGE_GET_LOD_V2_V2_nsa_gfx10 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, killed renamable $sgpr8_sgpr9_sgpr10_sgpr11, 3, 1, 0, 0, 0, 0, 0, 0, implicit $exec
  ; GFX10-RA-NEXT:   $vgpr0 = COPY [[IMAGE_GET_LOD_V2_V2_nsa_gfx10_]].sub0
  ; GFX10-RA-NEXT:   $vgpr1 = COPY [[IMAGE_GET_LOD_V2_V2_nsa_gfx10_]].sub1
  ; GFX10-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, $vgpr1
  ;
  ; GFX11-RA-LABEL: name: getlod_2d
  ; GFX11-RA: bb.0.main_body:
  ; GFX11-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $sgpr10, $sgpr11, $vgpr0, $vgpr1
  ; GFX11-RA-NEXT: {{  $}}
  ; GFX11-RA-NEXT:   renamable $sgpr12 = COPY $exec_lo
  ; GFX11-RA-NEXT:   $exec_lo = S_WQM_B32 $exec_lo, implicit-def $scc
  ; GFX11-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX11-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX11-RA-NEXT:   $exec_lo = S_AND_B32 $exec_lo, killed renamable $sgpr12, implicit-def $scc
  ; GFX11-RA-NEXT:   [[IMAGE_GET_LOD_V2_V2_nsa_gfx11_:%[0-9]+]]:vreg_64 = IMAGE_GET_LOD_V2_V2_nsa_gfx11 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, killed renamable $sgpr8_sgpr9_sgpr10_sgpr11, 3, 1, 0, 0, 0, 0, 0, 0, implicit $exec
  ; GFX11-RA-NEXT:   $vgpr0 = COPY [[IMAGE_GET_LOD_V2_V2_nsa_gfx11_]].sub0
  ; GFX11-RA-NEXT:   $vgpr1 = COPY [[IMAGE_GET_LOD_V2_V2_nsa_gfx11_]].sub1
  ; GFX11-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, $vgpr1
  ;
  ; GFX12-RA-LABEL: name: getlod_2d
  ; GFX12-RA: bb.0.main_body:
  ; GFX12-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $sgpr10, $sgpr11, $vgpr0, $vgpr1
  ; GFX12-RA-NEXT: {{  $}}
  ; GFX12-RA-NEXT:   renamable $sgpr12 = COPY $exec_lo
  ; GFX12-RA-NEXT:   $exec_lo = S_WQM_B32 $exec_lo, implicit-def $scc
  ; GFX12-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX12-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX12-RA-NEXT:   $exec_lo = S_AND_B32 $exec_lo, killed renamable $sgpr12, implicit-def $scc
  ; GFX12-RA-NEXT:   [[IMAGE_GET_LOD_V2_V2_gfx12_:%[0-9]+]]:vreg_64 = IMAGE_GET_LOD_V2_V2_gfx12 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3_sgpr4_sgpr5_sgpr6_sgpr7, killed renamable $sgpr8_sgpr9_sgpr10_sgpr11, 3, 1, 0, 0, 0, 0, 0, 0, implicit $exec
  ; GFX12-RA-NEXT:   $vgpr0 = COPY [[IMAGE_GET_LOD_V2_V2_gfx12_]].sub0
  ; GFX12-RA-NEXT:   $vgpr1 = COPY [[IMAGE_GET_LOD_V2_V2_gfx12_]].sub1
  ; GFX12-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, $vgpr1
main_body:
  %r = call <2 x float> @llvm.amdgcn.image.getlod.2d(i32 3, float %s, float %t, <8 x i32> %rsrc, <4 x i32> %samp, i1 0, i32 0, i32 0)
  ret <2 x float> %r
}

define amdgpu_ps <2 x float> @getlod_2d_r128(<4 x i32> inreg %rsrc, <4 x i32> inreg %samp, float %s, float %t) {
  ; GFX8-RA-LABEL: name: getlod_2d_r128
  ; GFX8-RA: bb.0.main_body:
  ; GFX8-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1
  ; GFX8-RA-NEXT: {{  $}}
  ; GFX8-RA-NEXT:   renamable $sgpr8_sgpr9 = COPY $exec
  ; GFX8-RA-NEXT:   $exec = S_WQM_B64 $exec, implicit-def $scc
  ; GFX8-RA-NEXT:   undef [[COPY:%[0-9]+]].sub1:vreg_64 = COPY $vgpr1
  ; GFX8-RA-NEXT:   [[COPY:%[0-9]+]].sub0:vreg_64 = COPY $vgpr0
  ; GFX8-RA-NEXT:   $exec = S_AND_B64 $exec, killed renamable $sgpr8_sgpr9, implicit-def $scc
  ; GFX8-RA-NEXT:   [[IMAGE_GET_LOD_V2_V2_:%[0-9]+]]:vreg_64 = IMAGE_GET_LOD_V2_V2 [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, killed renamable $sgpr4_sgpr5_sgpr6_sgpr7, 3, 0, 0, -1, 0, 0, 0, implicit $exec
  ; GFX8-RA-NEXT:   $vgpr0 = COPY [[IMAGE_GET_LOD_V2_V2_]].sub0
  ; GFX8-RA-NEXT:   $vgpr1 = COPY [[IMAGE_GET_LOD_V2_V2_]].sub1
  ; GFX8-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, $vgpr1
  ;
  ; GFX10-RA-LABEL: name: getlod_2d_r128
  ; GFX10-RA: bb.0.main_body:
  ; GFX10-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1
  ; GFX10-RA-NEXT: {{  $}}
  ; GFX10-RA-NEXT:   renamable $sgpr8 = COPY $exec_lo
  ; GFX10-RA-NEXT:   $exec_lo = S_WQM_B32 $exec_lo, implicit-def $scc
  ; GFX10-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX10-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX10-RA-NEXT:   $exec_lo = S_AND_B32 $exec_lo, killed renamable $sgpr8, implicit-def $scc
  ; GFX10-RA-NEXT:   [[IMAGE_GET_LOD_V2_V2_nsa_gfx10_:%[0-9]+]]:vreg_64 = IMAGE_GET_LOD_V2_V2_nsa_gfx10 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, killed renamable $sgpr4_sgpr5_sgpr6_sgpr7, 3, 1, 0, 0, -1, 0, 0, 0, implicit $exec
  ; GFX10-RA-NEXT:   $vgpr0 = COPY [[IMAGE_GET_LOD_V2_V2_nsa_gfx10_]].sub0
  ; GFX10-RA-NEXT:   $vgpr1 = COPY [[IMAGE_GET_LOD_V2_V2_nsa_gfx10_]].sub1
  ; GFX10-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, $vgpr1
  ;
  ; GFX11-RA-LABEL: name: getlod_2d_r128
  ; GFX11-RA: bb.0.main_body:
  ; GFX11-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1
  ; GFX11-RA-NEXT: {{  $}}
  ; GFX11-RA-NEXT:   renamable $sgpr8 = COPY $exec_lo
  ; GFX11-RA-NEXT:   $exec_lo = S_WQM_B32 $exec_lo, implicit-def $scc
  ; GFX11-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX11-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX11-RA-NEXT:   $exec_lo = S_AND_B32 $exec_lo, killed renamable $sgpr8, implicit-def $scc
  ; GFX11-RA-NEXT:   [[IMAGE_GET_LOD_V2_V2_nsa_gfx11_:%[0-9]+]]:vreg_64 = IMAGE_GET_LOD_V2_V2_nsa_gfx11 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, killed renamable $sgpr4_sgpr5_sgpr6_sgpr7, 3, 1, 0, 0, -1, 0, 0, 0, implicit $exec
  ; GFX11-RA-NEXT:   $vgpr0 = COPY [[IMAGE_GET_LOD_V2_V2_nsa_gfx11_]].sub0
  ; GFX11-RA-NEXT:   $vgpr1 = COPY [[IMAGE_GET_LOD_V2_V2_nsa_gfx11_]].sub1
  ; GFX11-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, $vgpr1
  ;
  ; GFX12-RA-LABEL: name: getlod_2d_r128
  ; GFX12-RA: bb.0.main_body:
  ; GFX12-RA-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2, $sgpr3, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $vgpr0, $vgpr1
  ; GFX12-RA-NEXT: {{  $}}
  ; GFX12-RA-NEXT:   renamable $sgpr8 = COPY $exec_lo
  ; GFX12-RA-NEXT:   $exec_lo = S_WQM_B32 $exec_lo, implicit-def $scc
  ; GFX12-RA-NEXT:   [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
  ; GFX12-RA-NEXT:   [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
  ; GFX12-RA-NEXT:   $exec_lo = S_AND_B32 $exec_lo, killed renamable $sgpr8, implicit-def $scc
  ; GFX12-RA-NEXT:   [[IMAGE_GET_LOD_V2_V2_gfx12_:%[0-9]+]]:vreg_64 = IMAGE_GET_LOD_V2_V2_gfx12 [[COPY1]], [[COPY]], killed renamable $sgpr0_sgpr1_sgpr2_sgpr3, killed renamable $sgpr4_sgpr5_sgpr6_sgpr7, 3, 1, 0, 0, -1, 0, 0, 0, implicit $exec
  ; GFX12-RA-NEXT:   $vgpr0 = COPY [[IMAGE_GET_LOD_V2_V2_gfx12_]].sub0
  ; GFX12-RA-NEXT:   $vgpr1 = COPY [[IMAGE_GET_LOD_V2_V2_gfx12_]].sub1
  ; GFX12-RA-NEXT:   SI_RETURN_TO_EPILOG $vgpr0, $vgpr1
main_body:
  %r = call <2 x float> @llvm.amdgcn.image.getlod.2d(i32 3, float %s, float %t, <4 x i32> %rsrc, <4 x i32> %samp, i1 0, i32 0, i32 0)
  ret <2 x float> %r
}
