; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 4
; RUN: llc -global-isel=0 -march=amdgcn -mcpu=gfx1210 -verify-machineinstrs < %s | FileCheck -check-prefix=GCN %s
; RUN: llc -global-isel=1 -march=amdgcn -mcpu=gfx1210 -verify-machineinstrs < %s | FileCheck -check-prefix=GCN %s

declare <2 x i16> @llvm.amdgcn.pk.fma.bf16(<2 x i16> %src0, <2 x i16> %src1, <2 x i16> %src2) #0

define amdgpu_ps float @pk_fma_bf16_vvv(<2 x i16> %src0, <2 x i16> %src1, <2 x i16> %src2) #1 {
; GCN-LABEL: pk_fma_bf16_vvv:
; GCN:       ; %bb.0:
; GCN-NEXT:    v_pk_fma_bf16 v0, v0, v1, v2
; GCN-NEXT:    ; return to shader part epilog
  %val = call <2 x i16> @llvm.amdgcn.pk.fma.bf16(<2 x i16> %src0, <2 x i16> %src1, <2 x i16> %src2) #0
  %ret = bitcast <2 x i16> %val to float
  ret float %ret
}

define amdgpu_ps float @pk_fma_bf16_sss(<2 x i16> inreg %src0, <2 x i16> inreg %src1, <2 x i16> inreg %src2) #1 {
; GCN-LABEL: pk_fma_bf16_sss:
; GCN:       ; %bb.0:
; GCN-NEXT:    v_mov_b32_e32 v0, s2
; GCN-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; GCN-NEXT:    v_pk_fma_bf16 v0, s0, s1, v0
; GCN-NEXT:    ; return to shader part epilog
  %val = call <2 x i16> @llvm.amdgcn.pk.fma.bf16(<2 x i16> %src0, <2 x i16> %src1, <2 x i16> %src2) #0
  %ret = bitcast <2 x i16> %val to float
  ret float %ret
}

define amdgpu_ps float @pk_fma_bf16_vvi(<2 x i16> %src0, <2 x i16> %src1) #1 {
; GCN-LABEL: pk_fma_bf16_vvi:
; GCN:       ; %bb.0:
; GCN-NEXT:    v_pk_fma_bf16 v0, v0, v1, 1 op_sel_hi:[1,1,0]
; GCN-NEXT:    ; return to shader part epilog
  %val = call <2 x i16> @llvm.amdgcn.pk.fma.bf16(<2 x i16> %src0, <2 x i16> %src1, <2 x i16> <i16 1, i16 1>) #0
  %ret = bitcast <2 x i16> %val to float
  ret float %ret
}

define amdgpu_ps float @pk_fma_bf16_vlv(<2 x i16> %src0, <2 x i16> %src2) #1 {
; GCN-LABEL: pk_fma_bf16_vlv:
; GCN:       ; %bb.0:
; GCN-NEXT:    v_pk_fma_bf16 v0, 0x640064, v0, v1
; GCN-NEXT:    ; return to shader part epilog
  %val = call <2 x i16> @llvm.amdgcn.pk.fma.bf16(<2 x i16> %src0, <2 x i16> <i16 100, i16 100>, <2 x i16> %src2) #0
  %ret = bitcast <2 x i16> %val to float
  ret float %ret
}

define amdgpu_ps float @pk_fma_bf16_vvll(<2 x i16> %src0, <2 x i16> %src1) #1 {
; GCN-LABEL: pk_fma_bf16_vvll:
; GCN:       ; %bb.0:
; GCN-NEXT:    v_pk_fma_bf16 v0, v0, v1, 0x650064
; GCN-NEXT:    ; return to shader part epilog
  %val = call <2 x i16> @llvm.amdgcn.pk.fma.bf16(<2 x i16> %src0, <2 x i16> %src1, <2 x i16> <i16 100, i16 101>) #0
  %ret = bitcast <2 x i16> %val to float
  ret float %ret
}

attributes #0 = { nounwind readnone }
attributes #1 = { nounwind }
