; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -mtriple=amdgcn-- -mcpu=hawaii -passes=amdgpu-codegenprepare \
; RUN:   -amdgpu-enable-fp32-recip-newton-raphson %s | FileCheck -check-prefix=OPT %s
; RUN: opt -S -mtriple=amdgcn-- -mcpu=hawaii -passes=amdgpu-codegenprepare \
; RUN:   -amdgpu-enable-fp32-recip-newton-raphson -denormal-fp-math-f32=preserve-sign \
; RUN:   %s | FileCheck -check-prefix=OPT-FTZ %s

; IEEE mode (default): branch + NR with large-normal scaling.
; FTZ mode: branch + NR without scaling.
define amdgpu_kernel void @test_fdiv_recip_f32(ptr addrspace(1) %out, float %x) #0 {
; OPT-LABEL: define amdgpu_kernel void @test_fdiv_recip_f32(
; OPT-SAME: ptr addrspace(1) [[OUT:%.*]], float [[X:%.*]]) #[[ATTR0:[0-9]+]] {
; OPT-NEXT:    [[TMP2:%.*]] = call float @llvm.fabs.f32(float [[X]])
; OPT-NEXT:    [[TMP10:%.*]] = fcmp ogt float [[TMP2]], f0x7E800000
; OPT-NEXT:    [[TMP3:%.*]] = select i1 [[TMP10]], float f0x2F800000, float 1.000000e+00
; OPT-NEXT:    [[TMP4:%.*]] = fcmp olt float [[TMP2]], f0x00800000
; OPT-NEXT:    [[TMP11:%.*]] = select i1 [[TMP4]], float f0x4F800000, float [[TMP3]]
; OPT-NEXT:    [[TMP5:%.*]] = fmul float [[X]], [[TMP11]]
; OPT-NEXT:    [[TMP6:%.*]] = call float @llvm.amdgcn.rcp.f32(float [[TMP5]])
; OPT-NEXT:    [[TMP7:%.*]] = call float @llvm.fma.f32(float [[TMP5]], float [[TMP6]], float -1.000000e+00)
; OPT-NEXT:    [[TMP8:%.*]] = fneg float [[TMP7]]
; OPT-NEXT:    [[TMP9:%.*]] = call float @llvm.fma.f32(float [[TMP6]], float [[TMP8]], float [[TMP6]])
; OPT-NEXT:    [[TMP14:%.*]] = fmul float [[TMP9]], [[TMP11]]
; OPT-NEXT:    [[TMP12:%.*]] = call float @llvm.amdgcn.div.fixup.f32(float [[TMP14]], float [[X]], float 1.000000e+00)
; OPT-NEXT:    store float [[TMP12]], ptr addrspace(1) [[OUT]], align 4
; OPT-NEXT:    ret void
;
; OPT-FTZ-LABEL: define amdgpu_kernel void @test_fdiv_recip_f32(
; OPT-FTZ-SAME: ptr addrspace(1) [[OUT:%.*]], float [[X:%.*]]) #[[ATTR0:[0-9]+]] {
; OPT-FTZ-NEXT:    [[TMP2:%.*]] = call float @llvm.amdgcn.rcp.f32(float [[X]])
; OPT-FTZ-NEXT:    [[TMP3:%.*]] = call float @llvm.fma.f32(float [[X]], float [[TMP2]], float -1.000000e+00)
; OPT-FTZ-NEXT:    [[TMP4:%.*]] = fneg float [[TMP3]]
; OPT-FTZ-NEXT:    [[TMP5:%.*]] = call float @llvm.fma.f32(float [[TMP2]], float [[TMP4]], float [[TMP2]])
; OPT-FTZ-NEXT:    [[TMP7:%.*]] = call float @llvm.amdgcn.div.fixup.f32(float [[TMP5]], float [[X]], float 1.000000e+00)
; OPT-FTZ-NEXT:    store float [[TMP7]], ptr addrspace(1) [[OUT]], align 4
; OPT-FTZ-NEXT:    ret void
;
  %fdiv = fdiv float 1.0, %x
  store float %fdiv, ptr addrspace(1) %out, align 4
  ret void
}

; Negative reciprocal: -1.0/x should also be transformed (fneg + rcp).
define amdgpu_kernel void @test_fdiv_neg_recip_f32(ptr addrspace(1) %out, float %x) #0 {
; OPT-LABEL: define amdgpu_kernel void @test_fdiv_neg_recip_f32(
; OPT-SAME: ptr addrspace(1) [[OUT:%.*]], float [[X:%.*]]) #[[ATTR0]] {
; OPT-NEXT:    [[TMP1:%.*]] = fneg float [[X]]
; OPT-NEXT:    [[TMP3:%.*]] = call float @llvm.fabs.f32(float [[TMP1]])
; OPT-NEXT:    [[TMP11:%.*]] = fcmp ogt float [[TMP3]], f0x7E800000
; OPT-NEXT:    [[TMP4:%.*]] = select i1 [[TMP11]], float f0x2F800000, float 1.000000e+00
; OPT-NEXT:    [[TMP5:%.*]] = fcmp olt float [[TMP3]], f0x00800000
; OPT-NEXT:    [[TMP12:%.*]] = select i1 [[TMP5]], float f0x4F800000, float [[TMP4]]
; OPT-NEXT:    [[TMP6:%.*]] = fmul float [[TMP1]], [[TMP12]]
; OPT-NEXT:    [[TMP7:%.*]] = call float @llvm.amdgcn.rcp.f32(float [[TMP6]])
; OPT-NEXT:    [[TMP8:%.*]] = call float @llvm.fma.f32(float [[TMP6]], float [[TMP7]], float -1.000000e+00)
; OPT-NEXT:    [[TMP9:%.*]] = fneg float [[TMP8]]
; OPT-NEXT:    [[TMP10:%.*]] = call float @llvm.fma.f32(float [[TMP7]], float [[TMP9]], float [[TMP7]])
; OPT-NEXT:    [[TMP15:%.*]] = fmul float [[TMP10]], [[TMP12]]
; OPT-NEXT:    [[TMP13:%.*]] = call float @llvm.amdgcn.div.fixup.f32(float [[TMP15]], float [[TMP1]], float 1.000000e+00)
; OPT-NEXT:    store float [[TMP13]], ptr addrspace(1) [[OUT]], align 4
; OPT-NEXT:    ret void
;
; OPT-FTZ-LABEL: define amdgpu_kernel void @test_fdiv_neg_recip_f32(
; OPT-FTZ-SAME: ptr addrspace(1) [[OUT:%.*]], float [[X:%.*]]) #[[ATTR0]] {
; OPT-FTZ-NEXT:    [[TMP1:%.*]] = fneg float [[X]]
; OPT-FTZ-NEXT:    [[TMP3:%.*]] = call float @llvm.amdgcn.rcp.f32(float [[TMP1]])
; OPT-FTZ-NEXT:    [[TMP4:%.*]] = call float @llvm.fma.f32(float [[TMP1]], float [[TMP3]], float -1.000000e+00)
; OPT-FTZ-NEXT:    [[TMP5:%.*]] = fneg float [[TMP4]]
; OPT-FTZ-NEXT:    [[TMP6:%.*]] = call float @llvm.fma.f32(float [[TMP3]], float [[TMP5]], float [[TMP3]])
; OPT-FTZ-NEXT:    [[TMP8:%.*]] = call float @llvm.amdgcn.div.fixup.f32(float [[TMP6]], float [[TMP1]], float 1.000000e+00)
; OPT-FTZ-NEXT:    store float [[TMP8]], ptr addrspace(1) [[OUT]], align 4
; OPT-FTZ-NEXT:    ret void
;
  %fdiv = fdiv float -1.0, %x
  store float %fdiv, ptr addrspace(1) %out, align 4
  ret void
}

; Non-reciprocal division should not be transformed.
define amdgpu_kernel void @test_fdiv_non_recip_f32(ptr addrspace(1) %out, float %x, float %y) #0 {
; OPT-LABEL: define amdgpu_kernel void @test_fdiv_non_recip_f32(
; OPT-SAME: ptr addrspace(1) [[OUT:%.*]], float [[X:%.*]], float [[Y:%.*]]) #[[ATTR0]] {
; OPT-NEXT:    [[FDIV:%.*]] = fdiv float [[Y]], [[X]]
; OPT-NEXT:    store float [[FDIV]], ptr addrspace(1) [[OUT]], align 4
; OPT-NEXT:    ret void
;
; OPT-FTZ-LABEL: define amdgpu_kernel void @test_fdiv_non_recip_f32(
; OPT-FTZ-SAME: ptr addrspace(1) [[OUT:%.*]], float [[X:%.*]], float [[Y:%.*]]) #[[ATTR0]] {
; OPT-FTZ-NEXT:    [[FDIV:%.*]] = fdiv float [[Y]], [[X]]
; OPT-FTZ-NEXT:    store float [[FDIV]], ptr addrspace(1) [[OUT]], align 4
; OPT-FTZ-NEXT:    ret void
;
  %fdiv = fdiv float %y, %x
  store float %fdiv, ptr addrspace(1) %out, align 4
  ret void
}

; Known-normal denominator (IEEE mode): NR inline with scaling, no branch.
; Known-normal denominator (FTZ mode): NR inline, no scaling, no branch.
define amdgpu_kernel void @test_fdiv_recip_f32_known_normal(ptr addrspace(1) %out, float nofpclass(nan inf zero sub) %x) #0 {
; OPT-LABEL: define amdgpu_kernel void @test_fdiv_recip_f32_known_normal(
; OPT-SAME: ptr addrspace(1) [[OUT:%.*]], float nofpclass(nan inf zero sub) [[X:%.*]]) #[[ATTR0]] {
; OPT-NEXT:    [[TMP1:%.*]] = call float @llvm.fabs.f32(float [[X]])
; OPT-NEXT:    [[TMP2:%.*]] = fcmp ogt float [[TMP1]], f0x7E800000
; OPT-NEXT:    [[TMP3:%.*]] = select i1 [[TMP2]], float f0x2F800000, float 1.000000e+00
; OPT-NEXT:    [[TMP10:%.*]] = fcmp olt float [[TMP1]], f0x00800000
; OPT-NEXT:    [[TMP11:%.*]] = select i1 [[TMP10]], float f0x4F800000, float [[TMP3]]
; OPT-NEXT:    [[TMP4:%.*]] = fmul float [[X]], [[TMP11]]
; OPT-NEXT:    [[TMP5:%.*]] = call float @llvm.amdgcn.rcp.f32(float [[TMP4]])
; OPT-NEXT:    [[TMP6:%.*]] = call float @llvm.fma.f32(float [[TMP4]], float [[TMP5]], float -1.000000e+00)
; OPT-NEXT:    [[TMP7:%.*]] = fneg float [[TMP6]]
; OPT-NEXT:    [[TMP8:%.*]] = call float @llvm.fma.f32(float [[TMP5]], float [[TMP7]], float [[TMP5]])
; OPT-NEXT:    [[TMP9:%.*]] = fmul float [[TMP8]], [[TMP11]]
; OPT-NEXT:    [[TMP12:%.*]] = call float @llvm.amdgcn.div.fixup.f32(float [[TMP9]], float [[X]], float 1.000000e+00)
; OPT-NEXT:    store float [[TMP12]], ptr addrspace(1) [[OUT]], align 4
; OPT-NEXT:    ret void
;
; OPT-FTZ-LABEL: define amdgpu_kernel void @test_fdiv_recip_f32_known_normal(
; OPT-FTZ-SAME: ptr addrspace(1) [[OUT:%.*]], float nofpclass(nan inf zero sub) [[X:%.*]]) #[[ATTR0]] {
; OPT-FTZ-NEXT:    [[TMP1:%.*]] = call float @llvm.amdgcn.rcp.f32(float [[X]])
; OPT-FTZ-NEXT:    [[TMP2:%.*]] = call float @llvm.fma.f32(float [[X]], float [[TMP1]], float -1.000000e+00)
; OPT-FTZ-NEXT:    [[TMP3:%.*]] = fneg float [[TMP2]]
; OPT-FTZ-NEXT:    [[TMP4:%.*]] = call float @llvm.fma.f32(float [[TMP1]], float [[TMP3]], float [[TMP1]])
; OPT-FTZ-NEXT:    [[TMP5:%.*]] = call float @llvm.amdgcn.div.fixup.f32(float [[TMP4]], float [[X]], float 1.000000e+00)
; OPT-FTZ-NEXT:    store float [[TMP5]], ptr addrspace(1) [[OUT]], align 4
; OPT-FTZ-NEXT:    ret void
;
  %fdiv = fdiv float 1.0, %x
  store float %fdiv, ptr addrspace(1) %out, align 4
  ret void
}


; Vector reciprocal: <2 x float> should be scalarized and each lane transformed.
define amdgpu_kernel void @test_fdiv_recip_v2f32(ptr addrspace(1) %out, <2 x float> %x) #0 {
; OPT-LABEL: define amdgpu_kernel void @test_fdiv_recip_v2f32(
; OPT-SAME: ptr addrspace(1) [[OUT:%.*]], <2 x float> [[X:%.*]]) #[[ATTR0]] {
; OPT-NEXT:    [[TMP1:%.*]] = extractelement <2 x float> [[X]], i64 0
; OPT-NEXT:    [[TMP4:%.*]] = extractelement <2 x float> [[X]], i64 1
; OPT-NEXT:    [[TMP14:%.*]] = call float @llvm.fabs.f32(float [[TMP1]])
; OPT-NEXT:    [[TMP11:%.*]] = fcmp ogt float [[TMP14]], f0x7E800000
; OPT-NEXT:    [[TMP13:%.*]] = select i1 [[TMP11]], float f0x2F800000, float 1.000000e+00
; OPT-NEXT:    [[TMP15:%.*]] = fcmp olt float [[TMP14]], f0x00800000
; OPT-NEXT:    [[TMP12:%.*]] = select i1 [[TMP15]], float f0x4F800000, float [[TMP13]]
; OPT-NEXT:    [[TMP28:%.*]] = fmul float [[TMP1]], [[TMP12]]
; OPT-NEXT:    [[TMP7:%.*]] = call float @llvm.amdgcn.rcp.f32(float [[TMP28]])
; OPT-NEXT:    [[TMP8:%.*]] = call float @llvm.fma.f32(float [[TMP28]], float [[TMP7]], float -1.000000e+00)
; OPT-NEXT:    [[TMP9:%.*]] = fneg float [[TMP8]]
; OPT-NEXT:    [[TMP10:%.*]] = call float @llvm.fma.f32(float [[TMP7]], float [[TMP9]], float [[TMP7]])
; OPT-NEXT:    [[TMP25:%.*]] = fmul float [[TMP10]], [[TMP12]]
; OPT-NEXT:    [[TMP29:%.*]] = call float @llvm.amdgcn.div.fixup.f32(float [[TMP25]], float [[TMP1]], float 1.000000e+00)
; OPT-NEXT:    [[TMP17:%.*]] = call float @llvm.fabs.f32(float [[TMP4]])
; OPT-NEXT:    [[TMP26:%.*]] = fcmp ogt float [[TMP17]], f0x7E800000
; OPT-NEXT:    [[TMP18:%.*]] = select i1 [[TMP26]], float f0x2F800000, float 1.000000e+00
; OPT-NEXT:    [[TMP19:%.*]] = fcmp olt float [[TMP17]], f0x00800000
; OPT-NEXT:    [[TMP31:%.*]] = select i1 [[TMP19]], float f0x4F800000, float [[TMP18]]
; OPT-NEXT:    [[TMP20:%.*]] = fmul float [[TMP4]], [[TMP31]]
; OPT-NEXT:    [[TMP21:%.*]] = call float @llvm.amdgcn.rcp.f32(float [[TMP20]])
; OPT-NEXT:    [[TMP22:%.*]] = call float @llvm.fma.f32(float [[TMP20]], float [[TMP21]], float -1.000000e+00)
; OPT-NEXT:    [[TMP23:%.*]] = fneg float [[TMP22]]
; OPT-NEXT:    [[TMP24:%.*]] = call float @llvm.fma.f32(float [[TMP21]], float [[TMP23]], float [[TMP21]])
; OPT-NEXT:    [[TMP32:%.*]] = fmul float [[TMP24]], [[TMP31]]
; OPT-NEXT:    [[TMP5:%.*]] = call float @llvm.amdgcn.div.fixup.f32(float [[TMP32]], float [[TMP4]], float 1.000000e+00)
; OPT-NEXT:    [[TMP3:%.*]] = insertelement <2 x float> poison, float [[TMP29]], i64 0
; OPT-NEXT:    [[TMP6:%.*]] = insertelement <2 x float> [[TMP3]], float [[TMP5]], i64 1
; OPT-NEXT:    store <2 x float> [[TMP6]], ptr addrspace(1) [[OUT]], align 8
; OPT-NEXT:    ret void
;
; OPT-FTZ-LABEL: define amdgpu_kernel void @test_fdiv_recip_v2f32(
; OPT-FTZ-SAME: ptr addrspace(1) [[OUT:%.*]], <2 x float> [[X:%.*]]) #[[ATTR0]] {
; OPT-FTZ-NEXT:    [[TMP1:%.*]] = extractelement <2 x float> [[X]], i64 0
; OPT-FTZ-NEXT:    [[TMP4:%.*]] = extractelement <2 x float> [[X]], i64 1
; OPT-FTZ-NEXT:    [[TMP7:%.*]] = call float @llvm.amdgcn.rcp.f32(float [[TMP1]])
; OPT-FTZ-NEXT:    [[TMP8:%.*]] = call float @llvm.fma.f32(float [[TMP1]], float [[TMP7]], float -1.000000e+00)
; OPT-FTZ-NEXT:    [[TMP9:%.*]] = fneg float [[TMP8]]
; OPT-FTZ-NEXT:    [[TMP10:%.*]] = call float @llvm.fma.f32(float [[TMP7]], float [[TMP9]], float [[TMP7]])
; OPT-FTZ-NEXT:    [[TMP12:%.*]] = call float @llvm.amdgcn.div.fixup.f32(float [[TMP10]], float [[TMP1]], float 1.000000e+00)
; OPT-FTZ-NEXT:    [[TMP21:%.*]] = call float @llvm.amdgcn.rcp.f32(float [[TMP4]])
; OPT-FTZ-NEXT:    [[TMP22:%.*]] = call float @llvm.fma.f32(float [[TMP4]], float [[TMP21]], float -1.000000e+00)
; OPT-FTZ-NEXT:    [[TMP23:%.*]] = fneg float [[TMP22]]
; OPT-FTZ-NEXT:    [[TMP24:%.*]] = call float @llvm.fma.f32(float [[TMP21]], float [[TMP23]], float [[TMP21]])
; OPT-FTZ-NEXT:    [[TMP5:%.*]] = call float @llvm.amdgcn.div.fixup.f32(float [[TMP24]], float [[TMP4]], float 1.000000e+00)
; OPT-FTZ-NEXT:    [[TMP3:%.*]] = insertelement <2 x float> poison, float [[TMP12]], i64 0
; OPT-FTZ-NEXT:    [[TMP6:%.*]] = insertelement <2 x float> [[TMP3]], float [[TMP5]], i64 1
; OPT-FTZ-NEXT:    store <2 x float> [[TMP6]], ptr addrspace(1) [[OUT]], align 8
; OPT-FTZ-NEXT:    ret void
;
  %fdiv = fdiv <2 x float> <float 1.0, float 1.0>, %x
  store <2 x float> %fdiv, ptr addrspace(1) %out, align 8
  ret void
}


; Negative vector reciprocal: <-1.0, -1.0>/x should be scalarized and each lane transformed.
define amdgpu_kernel void @test_fdiv_neg_recip_v2f32(ptr addrspace(1) %out, <2 x float> %x) #0 {
; OPT-LABEL: define amdgpu_kernel void @test_fdiv_neg_recip_v2f32(
; OPT-SAME: ptr addrspace(1) [[OUT:%.*]], <2 x float> [[X:%.*]]) #[[ATTR0]] {
; OPT-NEXT:    [[TMP1:%.*]] = extractelement <2 x float> [[X]], i64 0
; OPT-NEXT:    [[TMP2:%.*]] = extractelement <2 x float> [[X]], i64 1
; OPT-NEXT:    [[TMP3:%.*]] = fneg float [[TMP1]]
; OPT-NEXT:    [[TMP5:%.*]] = call float @llvm.fabs.f32(float [[TMP3]])
; OPT-NEXT:    [[TMP13:%.*]] = fcmp ogt float [[TMP5]], f0x7E800000
; OPT-NEXT:    [[TMP6:%.*]] = select i1 [[TMP13]], float f0x2F800000, float 1.000000e+00
; OPT-NEXT:    [[TMP7:%.*]] = fcmp olt float [[TMP5]], f0x00800000
; OPT-NEXT:    [[TMP14:%.*]] = select i1 [[TMP7]], float f0x4F800000, float [[TMP6]]
; OPT-NEXT:    [[TMP8:%.*]] = fmul float [[TMP3]], [[TMP14]]
; OPT-NEXT:    [[TMP9:%.*]] = call float @llvm.amdgcn.rcp.f32(float [[TMP8]])
; OPT-NEXT:    [[TMP10:%.*]] = call float @llvm.fma.f32(float [[TMP8]], float [[TMP9]], float -1.000000e+00)
; OPT-NEXT:    [[TMP11:%.*]] = fneg float [[TMP10]]
; OPT-NEXT:    [[TMP12:%.*]] = call float @llvm.fma.f32(float [[TMP9]], float [[TMP11]], float [[TMP9]])
; OPT-NEXT:    [[TMP26:%.*]] = fmul float [[TMP12]], [[TMP14]]
; OPT-NEXT:    [[TMP15:%.*]] = call float @llvm.amdgcn.div.fixup.f32(float [[TMP26]], float [[TMP3]], float 1.000000e+00)
; OPT-NEXT:    [[TMP16:%.*]] = fneg float [[TMP2]]
; OPT-NEXT:    [[TMP18:%.*]] = call float @llvm.fabs.f32(float [[TMP16]])
; OPT-NEXT:    [[TMP19:%.*]] = fcmp ogt float [[TMP18]], f0x7E800000
; OPT-NEXT:    [[TMP20:%.*]] = select i1 [[TMP19]], float f0x2F800000, float 1.000000e+00
; OPT-NEXT:    [[TMP27:%.*]] = fcmp olt float [[TMP18]], f0x00800000
; OPT-NEXT:    [[TMP33:%.*]] = select i1 [[TMP27]], float f0x4F800000, float [[TMP20]]
; OPT-NEXT:    [[TMP21:%.*]] = fmul float [[TMP16]], [[TMP33]]
; OPT-NEXT:    [[TMP22:%.*]] = call float @llvm.amdgcn.rcp.f32(float [[TMP21]])
; OPT-NEXT:    [[TMP23:%.*]] = call float @llvm.fma.f32(float [[TMP21]], float [[TMP22]], float -1.000000e+00)
; OPT-NEXT:    [[TMP24:%.*]] = fneg float [[TMP23]]
; OPT-NEXT:    [[TMP25:%.*]] = call float @llvm.fma.f32(float [[TMP22]], float [[TMP24]], float [[TMP22]])
; OPT-NEXT:    [[TMP34:%.*]] = fmul float [[TMP25]], [[TMP33]]
; OPT-NEXT:    [[TMP28:%.*]] = call float @llvm.amdgcn.div.fixup.f32(float [[TMP34]], float [[TMP16]], float 1.000000e+00)
; OPT-NEXT:    [[TMP29:%.*]] = insertelement <2 x float> poison, float [[TMP15]], i64 0
; OPT-NEXT:    [[TMP30:%.*]] = insertelement <2 x float> [[TMP29]], float [[TMP28]], i64 1
; OPT-NEXT:    store <2 x float> [[TMP30]], ptr addrspace(1) [[OUT]], align 8
; OPT-NEXT:    ret void
;
; OPT-FTZ-LABEL: define amdgpu_kernel void @test_fdiv_neg_recip_v2f32(
; OPT-FTZ-SAME: ptr addrspace(1) [[OUT:%.*]], <2 x float> [[X:%.*]]) #[[ATTR0]] {
; OPT-FTZ-NEXT:    [[TMP1:%.*]] = extractelement <2 x float> [[X]], i64 0
; OPT-FTZ-NEXT:    [[TMP2:%.*]] = extractelement <2 x float> [[X]], i64 1
; OPT-FTZ-NEXT:    [[TMP3:%.*]] = fneg float [[TMP1]]
; OPT-FTZ-NEXT:    [[TMP5:%.*]] = call float @llvm.amdgcn.rcp.f32(float [[TMP3]])
; OPT-FTZ-NEXT:    [[TMP6:%.*]] = call float @llvm.fma.f32(float [[TMP3]], float [[TMP5]], float -1.000000e+00)
; OPT-FTZ-NEXT:    [[TMP7:%.*]] = fneg float [[TMP6]]
; OPT-FTZ-NEXT:    [[TMP8:%.*]] = call float @llvm.fma.f32(float [[TMP5]], float [[TMP7]], float [[TMP5]])
; OPT-FTZ-NEXT:    [[TMP10:%.*]] = call float @llvm.amdgcn.div.fixup.f32(float [[TMP8]], float [[TMP3]], float 1.000000e+00)
; OPT-FTZ-NEXT:    [[TMP11:%.*]] = fneg float [[TMP2]]
; OPT-FTZ-NEXT:    [[TMP13:%.*]] = call float @llvm.amdgcn.rcp.f32(float [[TMP11]])
; OPT-FTZ-NEXT:    [[TMP14:%.*]] = call float @llvm.fma.f32(float [[TMP11]], float [[TMP13]], float -1.000000e+00)
; OPT-FTZ-NEXT:    [[TMP15:%.*]] = fneg float [[TMP14]]
; OPT-FTZ-NEXT:    [[TMP16:%.*]] = call float @llvm.fma.f32(float [[TMP13]], float [[TMP15]], float [[TMP13]])
; OPT-FTZ-NEXT:    [[TMP18:%.*]] = call float @llvm.amdgcn.div.fixup.f32(float [[TMP16]], float [[TMP11]], float 1.000000e+00)
; OPT-FTZ-NEXT:    [[TMP19:%.*]] = insertelement <2 x float> poison, float [[TMP10]], i64 0
; OPT-FTZ-NEXT:    [[TMP20:%.*]] = insertelement <2 x float> [[TMP19]], float [[TMP18]], i64 1
; OPT-FTZ-NEXT:    store <2 x float> [[TMP20]], ptr addrspace(1) [[OUT]], align 8
; OPT-FTZ-NEXT:    ret void
;
  %fdiv = fdiv <2 x float> <float -1.0, float -1.0>, %x
  store <2 x float> %fdiv, ptr addrspace(1) %out, align 8
  ret void
}

; f64 should not be transformed (only f32).
define amdgpu_kernel void @test_fdiv_recip_f64(ptr addrspace(1) %out, double %x) #0 {
; OPT-LABEL: define amdgpu_kernel void @test_fdiv_recip_f64(
; OPT-SAME: ptr addrspace(1) [[OUT:%.*]], double [[X:%.*]]) #[[ATTR0]] {
; OPT-NEXT:    [[FDIV:%.*]] = fdiv double 1.000000e+00, [[X]]
; OPT-NEXT:    store double [[FDIV]], ptr addrspace(1) [[OUT]], align 8
; OPT-NEXT:    ret void
;
; OPT-FTZ-LABEL: define amdgpu_kernel void @test_fdiv_recip_f64(
; OPT-FTZ-SAME: ptr addrspace(1) [[OUT:%.*]], double [[X:%.*]]) #[[ATTR0]] {
; OPT-FTZ-NEXT:    [[FDIV:%.*]] = fdiv double 1.000000e+00, [[X]]
; OPT-FTZ-NEXT:    store double [[FDIV]], ptr addrspace(1) [[OUT]], align 8
; OPT-FTZ-NEXT:    ret void
;
  %fdiv = fdiv double 1.0, %x
  store double %fdiv, ptr addrspace(1) %out, align 8
  ret void
}

; Verify that fast-math flags on the original fdiv are preserved on
; the instructions emitted by the NR expansion.
define amdgpu_kernel void @test_fdiv_recip_f32_fmf(ptr addrspace(1) %out, float %x) #0 {
; OPT-LABEL: define amdgpu_kernel void @test_fdiv_recip_f32_fmf(
; OPT-SAME: ptr addrspace(1) [[OUT:%.*]], float [[X:%.*]]) #[[ATTR0]] {
; OPT-NEXT:    [[TMP2:%.*]] = call nnan ninf float @llvm.fabs.f32(float [[X]])
; OPT-NEXT:    [[TMP10:%.*]] = fcmp nnan ninf ogt float [[TMP2]], f0x7E800000
; OPT-NEXT:    [[TMP3:%.*]] = select nnan ninf i1 [[TMP10]], float f0x2F800000, float 1.000000e+00
; OPT-NEXT:    [[TMP4:%.*]] = fcmp nnan ninf olt float [[TMP2]], f0x00800000
; OPT-NEXT:    [[TMP11:%.*]] = select nnan ninf i1 [[TMP4]], float f0x4F800000, float [[TMP3]]
; OPT-NEXT:    [[TMP5:%.*]] = fmul nnan ninf float [[X]], [[TMP11]]
; OPT-NEXT:    [[TMP6:%.*]] = call nnan ninf float @llvm.amdgcn.rcp.f32(float [[TMP5]])
; OPT-NEXT:    [[TMP7:%.*]] = call nnan ninf float @llvm.fma.f32(float [[TMP5]], float [[TMP6]], float -1.000000e+00)
; OPT-NEXT:    [[TMP8:%.*]] = fneg nnan ninf float [[TMP7]]
; OPT-NEXT:    [[TMP9:%.*]] = call nnan ninf float @llvm.fma.f32(float [[TMP6]], float [[TMP8]], float [[TMP6]])
; OPT-NEXT:    [[TMP14:%.*]] = fmul nnan ninf float [[TMP9]], [[TMP11]]
; OPT-NEXT:    [[TMP12:%.*]] = call nnan ninf float @llvm.amdgcn.div.fixup.f32(float [[TMP14]], float [[X]], float 1.000000e+00)
; OPT-NEXT:    store float [[TMP12]], ptr addrspace(1) [[OUT]], align 4
; OPT-NEXT:    ret void
;
; OPT-FTZ-LABEL: define amdgpu_kernel void @test_fdiv_recip_f32_fmf(
; OPT-FTZ-SAME: ptr addrspace(1) [[OUT:%.*]], float [[X:%.*]]) #[[ATTR0]] {
; OPT-FTZ-NEXT:    [[TMP2:%.*]] = call nnan ninf float @llvm.amdgcn.rcp.f32(float [[X]])
; OPT-FTZ-NEXT:    [[TMP3:%.*]] = call nnan ninf float @llvm.fma.f32(float [[X]], float [[TMP2]], float -1.000000e+00)
; OPT-FTZ-NEXT:    [[TMP4:%.*]] = fneg nnan ninf float [[TMP3]]
; OPT-FTZ-NEXT:    [[TMP5:%.*]] = call nnan ninf float @llvm.fma.f32(float [[TMP2]], float [[TMP4]], float [[TMP2]])
; OPT-FTZ-NEXT:    [[TMP7:%.*]] = call nnan ninf float @llvm.amdgcn.div.fixup.f32(float [[TMP5]], float [[X]], float 1.000000e+00)
; OPT-FTZ-NEXT:    store float [[TMP7]], ptr addrspace(1) [[OUT]], align 4
; OPT-FTZ-NEXT:    ret void
;
  %fdiv = fdiv nnan ninf float 1.0, %x
  store float %fdiv, ptr addrspace(1) %out, align 4
  ret void
}

; Verify that fast-math flags are preserved through vector scalarization.
define amdgpu_kernel void @test_fdiv_recip_v2f32_fmf(ptr addrspace(1) %out, <2 x float> %x) #0 {
; OPT-LABEL: define amdgpu_kernel void @test_fdiv_recip_v2f32_fmf(
; OPT-SAME: ptr addrspace(1) [[OUT:%.*]], <2 x float> [[X:%.*]]) #[[ATTR0]] {
; OPT-NEXT:    [[TMP1:%.*]] = extractelement <2 x float> [[X]], i64 0
; OPT-NEXT:    [[TMP2:%.*]] = extractelement <2 x float> [[X]], i64 1
; OPT-NEXT:    [[TMP4:%.*]] = call nnan ninf float @llvm.fabs.f32(float [[TMP1]])
; OPT-NEXT:    [[TMP12:%.*]] = fcmp nnan ninf ogt float [[TMP4]], f0x7E800000
; OPT-NEXT:    [[TMP5:%.*]] = select nnan ninf i1 [[TMP12]], float f0x2F800000, float 1.000000e+00
; OPT-NEXT:    [[TMP6:%.*]] = fcmp nnan ninf olt float [[TMP4]], f0x00800000
; OPT-NEXT:    [[TMP13:%.*]] = select nnan ninf i1 [[TMP6]], float f0x4F800000, float [[TMP5]]
; OPT-NEXT:    [[TMP7:%.*]] = fmul nnan ninf float [[TMP1]], [[TMP13]]
; OPT-NEXT:    [[TMP8:%.*]] = call nnan ninf float @llvm.amdgcn.rcp.f32(float [[TMP7]])
; OPT-NEXT:    [[TMP9:%.*]] = call nnan ninf float @llvm.fma.f32(float [[TMP7]], float [[TMP8]], float -1.000000e+00)
; OPT-NEXT:    [[TMP10:%.*]] = fneg nnan ninf float [[TMP9]]
; OPT-NEXT:    [[TMP11:%.*]] = call nnan ninf float @llvm.fma.f32(float [[TMP8]], float [[TMP10]], float [[TMP8]])
; OPT-NEXT:    [[TMP24:%.*]] = fmul nnan ninf float [[TMP11]], [[TMP13]]
; OPT-NEXT:    [[TMP14:%.*]] = call nnan ninf float @llvm.amdgcn.div.fixup.f32(float [[TMP24]], float [[TMP1]], float 1.000000e+00)
; OPT-NEXT:    [[TMP16:%.*]] = call nnan ninf float @llvm.fabs.f32(float [[TMP2]])
; OPT-NEXT:    [[TMP17:%.*]] = fcmp nnan ninf ogt float [[TMP16]], f0x7E800000
; OPT-NEXT:    [[TMP18:%.*]] = select nnan ninf i1 [[TMP17]], float f0x2F800000, float 1.000000e+00
; OPT-NEXT:    [[TMP25:%.*]] = fcmp nnan ninf olt float [[TMP16]], f0x00800000
; OPT-NEXT:    [[TMP31:%.*]] = select nnan ninf i1 [[TMP25]], float f0x4F800000, float [[TMP18]]
; OPT-NEXT:    [[TMP19:%.*]] = fmul nnan ninf float [[TMP2]], [[TMP31]]
; OPT-NEXT:    [[TMP20:%.*]] = call nnan ninf float @llvm.amdgcn.rcp.f32(float [[TMP19]])
; OPT-NEXT:    [[TMP21:%.*]] = call nnan ninf float @llvm.fma.f32(float [[TMP19]], float [[TMP20]], float -1.000000e+00)
; OPT-NEXT:    [[TMP22:%.*]] = fneg nnan ninf float [[TMP21]]
; OPT-NEXT:    [[TMP23:%.*]] = call nnan ninf float @llvm.fma.f32(float [[TMP20]], float [[TMP22]], float [[TMP20]])
; OPT-NEXT:    [[TMP32:%.*]] = fmul nnan ninf float [[TMP23]], [[TMP31]]
; OPT-NEXT:    [[TMP26:%.*]] = call nnan ninf float @llvm.amdgcn.div.fixup.f32(float [[TMP32]], float [[TMP2]], float 1.000000e+00)
; OPT-NEXT:    [[TMP27:%.*]] = insertelement <2 x float> poison, float [[TMP14]], i64 0
; OPT-NEXT:    [[TMP28:%.*]] = insertelement <2 x float> [[TMP27]], float [[TMP26]], i64 1
; OPT-NEXT:    store <2 x float> [[TMP28]], ptr addrspace(1) [[OUT]], align 8
; OPT-NEXT:    ret void
;
; OPT-FTZ-LABEL: define amdgpu_kernel void @test_fdiv_recip_v2f32_fmf(
; OPT-FTZ-SAME: ptr addrspace(1) [[OUT:%.*]], <2 x float> [[X:%.*]]) #[[ATTR0]] {
; OPT-FTZ-NEXT:    [[TMP1:%.*]] = extractelement <2 x float> [[X]], i64 0
; OPT-FTZ-NEXT:    [[TMP2:%.*]] = extractelement <2 x float> [[X]], i64 1
; OPT-FTZ-NEXT:    [[TMP4:%.*]] = call nnan ninf float @llvm.amdgcn.rcp.f32(float [[TMP1]])
; OPT-FTZ-NEXT:    [[TMP5:%.*]] = call nnan ninf float @llvm.fma.f32(float [[TMP1]], float [[TMP4]], float -1.000000e+00)
; OPT-FTZ-NEXT:    [[TMP6:%.*]] = fneg nnan ninf float [[TMP5]]
; OPT-FTZ-NEXT:    [[TMP7:%.*]] = call nnan ninf float @llvm.fma.f32(float [[TMP4]], float [[TMP6]], float [[TMP4]])
; OPT-FTZ-NEXT:    [[TMP9:%.*]] = call nnan ninf float @llvm.amdgcn.div.fixup.f32(float [[TMP7]], float [[TMP1]], float 1.000000e+00)
; OPT-FTZ-NEXT:    [[TMP11:%.*]] = call nnan ninf float @llvm.amdgcn.rcp.f32(float [[TMP2]])
; OPT-FTZ-NEXT:    [[TMP12:%.*]] = call nnan ninf float @llvm.fma.f32(float [[TMP2]], float [[TMP11]], float -1.000000e+00)
; OPT-FTZ-NEXT:    [[TMP13:%.*]] = fneg nnan ninf float [[TMP12]]
; OPT-FTZ-NEXT:    [[TMP14:%.*]] = call nnan ninf float @llvm.fma.f32(float [[TMP11]], float [[TMP13]], float [[TMP11]])
; OPT-FTZ-NEXT:    [[TMP16:%.*]] = call nnan ninf float @llvm.amdgcn.div.fixup.f32(float [[TMP14]], float [[TMP2]], float 1.000000e+00)
; OPT-FTZ-NEXT:    [[TMP17:%.*]] = insertelement <2 x float> poison, float [[TMP9]], i64 0
; OPT-FTZ-NEXT:    [[TMP18:%.*]] = insertelement <2 x float> [[TMP17]], float [[TMP16]], i64 1
; OPT-FTZ-NEXT:    store <2 x float> [[TMP18]], ptr addrspace(1) [[OUT]], align 8
; OPT-FTZ-NEXT:    ret void
;
  %fdiv = fdiv nnan ninf <2 x float> splat (float 1.0), %x
  store <2 x float> %fdiv, ptr addrspace(1) %out, align 8
  ret void
}

attributes #0 = { nounwind }
