; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -march=amdgcn -mcpu=gfx1200 -global-isel=0 -verify-machineinstrs < %s | FileCheck --check-prefixes=CHECK,SDAG %s
; RUN: llc -march=amdgcn -mcpu=gfx1200 -global-isel=1 -verify-machineinstrs < %s | FileCheck --check-prefixes=CHECK,GISEL %s

define amdgpu_cs i32 @test32_constant_all() {
; CHECK-LABEL: test32_constant_all:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_mov_b32 s0, 0
; CHECK-NEXT:    s_movk_i32 m0, 0x500
; CHECK-NEXT:    s_swap_to_global_b32 s102, s0
; CHECK-NEXT:    ; return to shader part epilog
  %r = call i32 @llvm.amdgcn.s.swap.to.global.i32(i16 102, i32 0, i32 1280)
  ret i32 %r
}

define amdgpu_cs i32 @test32_uniform_all(i32 inreg %x, i32 inreg %m0) {
; CHECK-LABEL: test32_uniform_all:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_mov_b32 m0, s1
; CHECK-NEXT:    s_swap_to_global_b32 s9, s0
; CHECK-NEXT:    ; return to shader part epilog
  %r = call i32 @llvm.amdgcn.s.swap.to.global.i32(i16 9, i32 %x, i32 %m0)
  ret i32 %r
}

; TODO: The S_DELAY_ALU here is misguided. The dependency is handled in HW.
define amdgpu_cs i32 @test32_divergent_all(i32 %x, i32 %m0) {
; SDAG-LABEL: test32_divergent_all:
; SDAG:       ; %bb.0:
; SDAG-NEXT:    v_readfirstlane_b32 s1, v1
; SDAG-NEXT:    v_readfirstlane_b32 s0, v0
; SDAG-NEXT:    s_delay_alu instid0(VALU_DEP_2) | instskip(NEXT) | instid1(VALU_DEP_1)
; SDAG-NEXT:    s_mov_b32 m0, s1
; SDAG-NEXT:    s_swap_to_global_b32 s9, s0
; SDAG-NEXT:    ; return to shader part epilog
;
; GISEL-LABEL: test32_divergent_all:
; GISEL:       ; %bb.0:
; GISEL-NEXT:    v_readfirstlane_b32 s0, v0
; GISEL-NEXT:    v_readfirstlane_b32 m0, v1
; GISEL-NEXT:    s_delay_alu instid0(VALU_DEP_2)
; GISEL-NEXT:    s_swap_to_global_b32 s9, s0
; GISEL-NEXT:    ; return to shader part epilog
  %r = call i32 @llvm.amdgcn.s.swap.to.global.i32(i16 9, i32 %x, i32 %m0)
  ret i32 %r
}

declare i32 @llvm.amdgcn.s.swap.to.global.i32(i16, i32, i32)
