; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=amdgcn -mcpu=gfx900 < %s | FileCheck -check-prefix=GCN %s
; RUN: llc -global-isel -new-reg-bank-select -mtriple=amdgcn -mcpu=gfx900 < %s | FileCheck -check-prefix=GCN %s

define amdgpu_kernel void @test_s_nop() {
; GCN-LABEL: test_s_nop:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_nop 0
; GCN-NEXT:    s_nop 1
; GCN-NEXT:    s_nop 2
; GCN-NEXT:    s_nop 3
; GCN-NEXT:    s_nop 4
; GCN-NEXT:    s_nop 5
; GCN-NEXT:    s_nop 6
; GCN-NEXT:    s_nop 7
; GCN-NEXT:    s_nop 63
; GCN-NEXT:    s_endpgm
  call void @llvm.amdgcn.s.nop(i16 0)
  call void @llvm.amdgcn.s.nop(i16 1)
  call void @llvm.amdgcn.s.nop(i16 2)
  call void @llvm.amdgcn.s.nop(i16 3)
  call void @llvm.amdgcn.s.nop(i16 4)
  call void @llvm.amdgcn.s.nop(i16 5)
  call void @llvm.amdgcn.s.nop(i16 6)
  call void @llvm.amdgcn.s.nop(i16 7)
  call void @llvm.amdgcn.s.nop(i16 63)
  ret void
}

declare void @llvm.amdgcn.s.nop(i16)
