; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=amdgcn-amd-amdhsa -verify-machineinstrs < %s | FileCheck %s

; Allow intrinsics llvm.amdgcn.buffer.wbinvl1 and llvm.amdgcn.buffer.wbinvl1.vol to be
; lowered to the instruction buffer_inv for GFX940+.
; 
declare void @llvm.amdgcn.buffer.wbinvl1()
declare void @llvm.amdgcn.buffer.wbinvl1.vol()

define void @test_wbinvl1_gfx908() #0 {
; CHECK-LABEL: test_wbinvl1_gfx908:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    buffer_wbinvl1
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  call void @llvm.amdgcn.buffer.wbinvl1()
  ret void
}

define void @test_wbinvl1_vol_gfx908() #0 {
; CHECK-LABEL: test_wbinvl1_vol_gfx908:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    buffer_wbinvl1_vol
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  call void @llvm.amdgcn.buffer.wbinvl1.vol()
  ret void
}

define void @test_wbinvl1_gfx90a() #1 {
; CHECK-LABEL: test_wbinvl1_gfx90a:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    buffer_wbinvl1
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  call void @llvm.amdgcn.buffer.wbinvl1()
  ret void
}

define void @test_wbinvl1_vol_gfx90a() #1 {
; CHECK-LABEL: test_wbinvl1_vol_gfx90a:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    buffer_wbinvl1_vol
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  call void @llvm.amdgcn.buffer.wbinvl1.vol()
  ret void
}

define void @test_wbinvl1_gfx940() #2 {
; CHECK-LABEL: test_wbinvl1_gfx940:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    buffer_inv
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  call void @llvm.amdgcn.buffer.wbinvl1()
  ret void
}

define void @test_wbinvl1_vol_gfx940() #2 {
; CHECK-LABEL: test_wbinvl1_vol_gfx940:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    buffer_inv
; CHECK-NEXT:    s_setpc_b64 s[30:31]
  call void @llvm.amdgcn.buffer.wbinvl1.vol()
  ret void
}

attributes #0 = { nounwind "target-cpu"="gfx908" }
attributes #1 = { nounwind "target-cpu"="gfx90a" }
attributes #2 = { nounwind "target-cpu"="gfx940" }
