# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=amdgcn -mcpu=gfx900 -run-pass=postrapseudos -verify-machineinstrs -o - %s | FileCheck -check-prefix=GCN %s

---
name:            lshl_or_expand
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $sgpr0, $sgpr1, $sgpr2
    ; GCN-LABEL: name: lshl_or_expand
    ; GCN: liveins: $sgpr0, $sgpr1, $sgpr2
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: $sgpr3 = S_LSHL_B32 killed $sgpr0, killed $sgpr1, implicit-def $scc
    ; GCN-NEXT: $sgpr3 = S_OR_B32 $sgpr3, killed $sgpr2, implicit-def $scc
    ; GCN-NEXT: S_ENDPGM 0, implicit $sgpr3
    renamable $sgpr3 = S_LSHL_OR_B32 killed $sgpr0, killed $sgpr1, killed $sgpr2, implicit-def $scc
    S_ENDPGM 0, implicit $sgpr3
...

---
name:            lshl_or_expand_pack
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $sgpr0
    ; GCN-LABEL: name: lshl_or_expand_pack
    ; GCN: liveins: $sgpr0
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: $sgpr3 = S_LSHL_B32 $sgpr0, 16, implicit-def $scc
    ; GCN-NEXT: $sgpr3 = S_OR_B32 $sgpr3, $sgpr0, implicit-def $scc
    ; GCN-NEXT: S_ENDPGM 0, implicit $sgpr3
    renamable $sgpr3 = S_LSHL_OR_B32 killed $sgpr0, 16, $sgpr0, implicit-def $scc
    S_ENDPGM 0, implicit $sgpr3
...
