# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1100 -mattr=+real-true16 -run-pass=machine-cp -o - %s | FileCheck -check-prefixes=CHECK %s

# vgpr2_hi16 should not fold into sgpr4_hi16
---
name:            test_machine_copy
alignment:       1
tracksRegLiveness: true
machineFunctionInfo:
  isEntryFunction: true
body:             |
  bb.0:
  liveins: $vgpr0, $sgpr4_sgpr5
    ; CHECK-LABEL: name: test_machine_copy
    ; CHECK: liveins: $vgpr0, $sgpr4_sgpr5
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: $sgpr0_sgpr1_sgpr2_sgpr3 = S_LOAD_DWORDX4_IMM renamable $sgpr4_sgpr5, 0, 0
    ; CHECK-NEXT: $vgpr0 = V_AND_B32_e64 1023, killed $vgpr0, implicit $exec
    ; CHECK-NEXT: $vgpr0 = nuw nsw V_LSHLREV_B32_e64 2, killed $vgpr0, implicit $exec
    ; CHECK-NEXT: $sgpr4 = S_LOAD_DWORD_IMM killed renamable $sgpr4_sgpr5, 16, 0
    ; CHECK-NEXT: $vgpr1 = GLOBAL_LOAD_DWORD_SADDR renamable $sgpr2_sgpr3, renamable $vgpr0, 0, 0, implicit $exec
    ; CHECK-NEXT: $vgpr2 = COPY killed renamable $sgpr4
    ; CHECK-NEXT: $vgpr1_lo16 = COPY killed renamable $vgpr2_hi16
    ; CHECK-NEXT: GLOBAL_STORE_DWORD_SADDR killed renamable $vgpr0, killed renamable $vgpr1, killed renamable $sgpr0_sgpr1, 0, 0, implicit $exec
    ; CHECK-NEXT: S_ENDPGM 0
  $sgpr0_sgpr1_sgpr2_sgpr3 = S_LOAD_DWORDX4_IMM renamable $sgpr4_sgpr5, 0, 0
  $vgpr0 = V_AND_B32_e64 1023, killed $vgpr0, implicit $exec
  $vgpr0 = nuw nsw V_LSHLREV_B32_e64 2, killed $vgpr0, implicit $exec
  $sgpr4 = S_LOAD_DWORD_IMM killed renamable $sgpr4_sgpr5, 16, 0
  $vgpr1 = GLOBAL_LOAD_DWORD_SADDR renamable $sgpr2_sgpr3, renamable $vgpr0, 0, 0, implicit $exec
  $vgpr2 = COPY killed renamable $sgpr4
  $vgpr1_lo16 = COPY killed renamable $vgpr2_hi16
  GLOBAL_STORE_DWORD_SADDR killed renamable $vgpr0, killed renamable $vgpr1, killed renamable $sgpr0_sgpr1, 0, 0, implicit $exec
  S_ENDPGM 0
...

