# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=amdgcn -mcpu=gfx900 -run-pass=machinelicm -verify-machineinstrs -o - %s | FileCheck %s
# RUN: llc -mtriple=amdgcn -mcpu=gfx900 -passes=machinelicm -o - %s | FileCheck %s

# Test that post-RA MachineLICM can hoist an instruction using a live-in
# register that is not defined within the loop. Previously, all live-in
# registers were conservatively treated as non-invariant, which blocked
# hoisting.

---
# $sgpr0 is defined in the preheader and is live-in to the loop body but
# never redefined inside the loop. The S_MOV_B32 reading $sgpr0 should
# be hoisted to the preheader.
name: hoist_livein_not_def_in_loop
tracksRegLiveness: true
body: |
  ; CHECK-LABEL: name: hoist_livein_not_def_in_loop
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $sgpr0, $sgpr1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $sgpr0 = S_MOV_B32 0
  ; CHECK-NEXT:   $sgpr2 = S_MOV_B32 $sgpr0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $sgpr0, $sgpr1, $sgpr2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   S_NOP 0, implicit $sgpr2
  ; CHECK-NEXT:   $sgpr1 = S_ADD_I32 $sgpr1, 1, implicit-def $scc
  ; CHECK-NEXT:   S_CBRANCH_SCC1 %bb.1, implicit $scc
  ; CHECK-NEXT:   S_BRANCH %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   liveins: $sgpr2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   S_NOP 0, implicit $sgpr2
  ; CHECK-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1
    liveins: $sgpr0, $sgpr1

    $sgpr0 = S_MOV_B32 0

  bb.1:
    successors: %bb.1, %bb.2
    liveins: $sgpr0, $sgpr1

    $sgpr2 = S_MOV_B32 $sgpr0
    S_NOP 0, implicit $sgpr2
    $sgpr1 = S_ADD_I32 $sgpr1, 1, implicit-def $scc
    S_CBRANCH_SCC1 %bb.1, implicit $scc
    S_BRANCH %bb.2

  bb.2:
    liveins: $sgpr2

    S_NOP 0, implicit $sgpr2
    S_ENDPGM 0
...

---
# $sgpr0 is live-in to the loop and also defined inside the loop. The
# S_MOV_B32 reading $sgpr0 should NOT be hoisted since $sgpr0 is not
# loop-invariant.
name: no_hoist_livein_def_in_loop
tracksRegLiveness: true
body: |
  ; CHECK-LABEL: name: no_hoist_livein_def_in_loop
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $sgpr0, $sgpr1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $sgpr0 = S_MOV_B32 0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $sgpr0, $sgpr1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $sgpr2 = S_MOV_B32 $sgpr0
  ; CHECK-NEXT:   $sgpr0 = S_ADD_I32 $sgpr0, 1, implicit-def $scc
  ; CHECK-NEXT:   S_NOP 0, implicit $sgpr2
  ; CHECK-NEXT:   $sgpr1 = S_ADD_I32 $sgpr1, -1, implicit-def $scc
  ; CHECK-NEXT:   S_CBRANCH_SCC1 %bb.1, implicit $scc
  ; CHECK-NEXT:   S_BRANCH %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   liveins: $sgpr2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   S_NOP 0, implicit $sgpr2
  ; CHECK-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1
    liveins: $sgpr0, $sgpr1

    $sgpr0 = S_MOV_B32 0

  bb.1:
    successors: %bb.1, %bb.2
    liveins: $sgpr0, $sgpr1

    $sgpr2 = S_MOV_B32 $sgpr0
    $sgpr0 = S_ADD_I32 $sgpr0, 1, implicit-def $scc
    S_NOP 0, implicit $sgpr2
    $sgpr1 = S_ADD_I32 $sgpr1, -1, implicit-def $scc
    S_CBRANCH_SCC1 %bb.1, implicit $scc
    S_BRANCH %bb.2

  bb.2:
    liveins: $sgpr2

    S_NOP 0, implicit $sgpr2
    S_ENDPGM 0
...
