; NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6

; RUN: llc -mtriple=amdgcn -mcpu=gfx1201 -stop-after=si-memory-legalizer < %s -o - | FileCheck %s --check-prefixes=CHECK,WAVE32
; RUN: llc -mtriple=amdgcn -mcpu=gfx1201 -mattr=+wavefrontsize64 -stop-after=si-memory-legalizer < %s -o - | FileCheck %s --check-prefixes=CHECK,WAVE64

define amdgpu_kernel void @single_wave_workgroup32() #0 {
  ; CHECK-LABEL: name: single_wave_workgroup32
  ; CHECK: bb.0 (%ir-block.0):
  ; CHECK-NEXT:   S_ENDPGM 0
  fence syncscope("workgroup") acq_rel
  ret void
}

define amdgpu_kernel void @single_wave_workgroup64() #1 {
  ; WAVE32-LABEL: name: single_wave_workgroup64
  ; WAVE32: bb.0 (%ir-block.0):
  ; WAVE32-NEXT:   S_WAIT_BVHCNT_soft 0
  ; WAVE32-NEXT:   S_WAIT_SAMPLECNT_soft 0
  ; WAVE32-NEXT:   S_WAIT_LOADCNT_soft 0
  ; WAVE32-NEXT:   S_WAIT_STORECNT_soft 0
  ; WAVE32-NEXT:   S_WAIT_DSCNT_soft 0
  ; WAVE32-NEXT:   GLOBAL_INV 8, implicit $exec
  ; WAVE32-NEXT:   S_ENDPGM 0
  ;
  ; WAVE64-LABEL: name: single_wave_workgroup64
  ; WAVE64: bb.0 (%ir-block.0):
  ; WAVE64-NEXT:   S_ENDPGM 0
  fence syncscope("workgroup") acq_rel
  ret void
}

define amdgpu_kernel void @multi_wave_workgroup() #2 {
  ; CHECK-LABEL: name: multi_wave_workgroup
  ; CHECK: bb.0 (%ir-block.0):
  ; CHECK-NEXT:   S_WAIT_BVHCNT_soft 0
  ; CHECK-NEXT:   S_WAIT_SAMPLECNT_soft 0
  ; CHECK-NEXT:   S_WAIT_LOADCNT_soft 0
  ; CHECK-NEXT:   S_WAIT_STORECNT_soft 0
  ; CHECK-NEXT:   S_WAIT_DSCNT_soft 0
  ; CHECK-NEXT:   GLOBAL_INV 8, implicit $exec
  ; CHECK-NEXT:   S_ENDPGM 0
  fence syncscope("workgroup") acq_rel
  ret void
}

attributes #0 = { "amdgpu-flat-work-group-size"="32,32" }
attributes #1 = { "amdgpu-flat-work-group-size"="64,64" }
attributes #2 = { "amdgpu-flat-work-group-size"="64,256" }

