# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=amdgcn -mcpu=gfx90a -mattr=-vgpr-align2 -run-pass=si-merge-vgpr-copies -verify-machineinstrs -o - %s | FileCheck -check-prefixes=GCN,GFX90A-NO-ALIGN %s
# RUN: llc -mtriple=amdgcn -mcpu=gfx90a                     -run-pass=si-merge-vgpr-copies -verify-machineinstrs -o - %s | FileCheck -check-prefixes=GCN,GFX90A-ALIGN    %s
# RUN: llc -mtriple=amdgcn -mcpu=gfx942 -mattr=-vgpr-align2 -run-pass=si-merge-vgpr-copies -verify-machineinstrs -o - %s | FileCheck -check-prefixes=GCN,GFX942-NO-ALIGN %s
# RUN: llc -mtriple=amdgcn -mcpu=gfx942                     -run-pass=si-merge-vgpr-copies -verify-machineinstrs -o - %s | FileCheck -check-prefixes=GCN,GFX942-ALIGN    %s

# Check that merging of 32-bit copies can be done for odd-aligned VGPR registers
# if the target supports it.
# All targets that currently enable this pass (hasPkMovB32 or hasMovB64) also
# require even-aligned VGPR pairs (needsAlignedVGPRs). The -vgpr-align2 flag
# is used here to synthesize a target where the pass runs without the alignment
# requirement, exercising the conditional alignment check.

---
name:            test_odd_aligned_src
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $vgpr4, $vgpr5
    ; NO-ALIGN-LABEL: name: test_odd_aligned_src
    ; NO-ALIGN: liveins: $vgpr4, $vgpr5
    ; NO-ALIGN-NEXT: {{  $}}
    ; NO-ALIGN-NEXT: $vgpr1_vgpr2 = COPY $vgpr4_vgpr5, implicit $exec
    ; NO-ALIGN-NEXT: S_ENDPGM 0, implicit $vgpr1, implicit $vgpr2
    ; ALIGN-LABEL: name: test_odd_aligned_src
    ; ALIGN: liveins: $vgpr4, $vgpr5
    ; ALIGN-NEXT: {{  $}}
    ; ALIGN-NEXT: $vgpr1 = COPY $vgpr4
    ; ALIGN-NEXT: $vgpr2 = COPY $vgpr5
    ; ALIGN-NEXT: S_ENDPGM 0, implicit $vgpr1, implicit $vgpr2
    ; GFX90A-NO-ALIGN-LABEL: name: test_odd_aligned_src
    ; GFX90A-NO-ALIGN: liveins: $vgpr4, $vgpr5
    ; GFX90A-NO-ALIGN-NEXT: {{  $}}
    ; GFX90A-NO-ALIGN-NEXT: $vgpr1_vgpr2 = COPY $vgpr4_vgpr5, implicit $exec
    ; GFX90A-NO-ALIGN-NEXT: S_ENDPGM 0, implicit $vgpr1, implicit $vgpr2
    ;
    ; GFX90A-ALIGN-LABEL: name: test_odd_aligned_src
    ; GFX90A-ALIGN: liveins: $vgpr4, $vgpr5
    ; GFX90A-ALIGN-NEXT: {{  $}}
    ; GFX90A-ALIGN-NEXT: $vgpr1 = COPY $vgpr4
    ; GFX90A-ALIGN-NEXT: $vgpr2 = COPY $vgpr5
    ; GFX90A-ALIGN-NEXT: S_ENDPGM 0, implicit $vgpr1, implicit $vgpr2
    ;
    ; GFX942-NO-ALIGN-LABEL: name: test_odd_aligned_src
    ; GFX942-NO-ALIGN: liveins: $vgpr4, $vgpr5
    ; GFX942-NO-ALIGN-NEXT: {{  $}}
    ; GFX942-NO-ALIGN-NEXT: $vgpr1_vgpr2 = COPY $vgpr4_vgpr5, implicit $exec
    ; GFX942-NO-ALIGN-NEXT: S_ENDPGM 0, implicit $vgpr1, implicit $vgpr2
    ;
    ; GFX942-ALIGN-LABEL: name: test_odd_aligned_src
    ; GFX942-ALIGN: liveins: $vgpr4, $vgpr5
    ; GFX942-ALIGN-NEXT: {{  $}}
    ; GFX942-ALIGN-NEXT: $vgpr1 = COPY $vgpr4
    ; GFX942-ALIGN-NEXT: $vgpr2 = COPY $vgpr5
    ; GFX942-ALIGN-NEXT: S_ENDPGM 0, implicit $vgpr1, implicit $vgpr2
    $vgpr1 = COPY $vgpr4
    $vgpr2 = COPY $vgpr5
    S_ENDPGM 0, implicit $vgpr1, implicit $vgpr2
...

---
name:            test_odd_aligned_dst
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $vgpr3, $vgpr4
    ; NO-ALIGN-LABEL: name: test_odd_aligned_dst
    ; NO-ALIGN: liveins: $vgpr3, $vgpr4
    ; NO-ALIGN-NEXT: {{  $}}
    ; NO-ALIGN-NEXT: $vgpr0_vgpr1 = COPY $vgpr3_vgpr4, implicit $exec
    ; NO-ALIGN-NEXT: S_ENDPGM 0, implicit $vgpr0, implicit $vgpr1
    ; ALIGN-LABEL: name: test_odd_aligned_dst
    ; ALIGN: liveins: $vgpr3, $vgpr4
    ; ALIGN-NEXT: {{  $}}
    ; ALIGN-NEXT: $vgpr0 = COPY $vgpr3
    ; ALIGN-NEXT: $vgpr1 = COPY $vgpr4
    ; ALIGN-NEXT: S_ENDPGM 0, implicit $vgpr0, implicit $vgpr1
    ; GFX90A-NO-ALIGN-LABEL: name: test_odd_aligned_dst
    ; GFX90A-NO-ALIGN: liveins: $vgpr3, $vgpr4
    ; GFX90A-NO-ALIGN-NEXT: {{  $}}
    ; GFX90A-NO-ALIGN-NEXT: $vgpr0_vgpr1 = COPY $vgpr3_vgpr4, implicit $exec
    ; GFX90A-NO-ALIGN-NEXT: S_ENDPGM 0, implicit $vgpr0, implicit $vgpr1
    ;
    ; GFX90A-ALIGN-LABEL: name: test_odd_aligned_dst
    ; GFX90A-ALIGN: liveins: $vgpr3, $vgpr4
    ; GFX90A-ALIGN-NEXT: {{  $}}
    ; GFX90A-ALIGN-NEXT: $vgpr0 = COPY $vgpr3
    ; GFX90A-ALIGN-NEXT: $vgpr1 = COPY $vgpr4
    ; GFX90A-ALIGN-NEXT: S_ENDPGM 0, implicit $vgpr0, implicit $vgpr1
    ;
    ; GFX942-NO-ALIGN-LABEL: name: test_odd_aligned_dst
    ; GFX942-NO-ALIGN: liveins: $vgpr3, $vgpr4
    ; GFX942-NO-ALIGN-NEXT: {{  $}}
    ; GFX942-NO-ALIGN-NEXT: $vgpr0_vgpr1 = COPY $vgpr3_vgpr4, implicit $exec
    ; GFX942-NO-ALIGN-NEXT: S_ENDPGM 0, implicit $vgpr0, implicit $vgpr1
    ;
    ; GFX942-ALIGN-LABEL: name: test_odd_aligned_dst
    ; GFX942-ALIGN: liveins: $vgpr3, $vgpr4
    ; GFX942-ALIGN-NEXT: {{  $}}
    ; GFX942-ALIGN-NEXT: $vgpr0 = COPY $vgpr3
    ; GFX942-ALIGN-NEXT: $vgpr1 = COPY $vgpr4
    ; GFX942-ALIGN-NEXT: S_ENDPGM 0, implicit $vgpr0, implicit $vgpr1
    $vgpr0 = COPY $vgpr3
    $vgpr1 = COPY $vgpr4
    S_ENDPGM 0, implicit $vgpr0, implicit $vgpr1
...

---
name:            test_odd_aligned_src_dst
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $vgpr3, $vgpr4
    ; NO-ALIGN-LABEL: name: test_odd_aligned_src_dst
    ; NO-ALIGN: liveins: $vgpr3, $vgpr4
    ; NO-ALIGN-NEXT: {{  $}}
    ; NO-ALIGN-NEXT: $vgpr1_vgpr2 = COPY $vgpr3_vgpr4, implicit $exec
    ; NO-ALIGN-NEXT: S_ENDPGM 0, implicit $vgpr1, implicit $vgpr2
    ; ALIGN-LABEL: name: test_odd_aligned_src_dst
    ; ALIGN: liveins: $vgpr3, $vgpr4
    ; ALIGN-NEXT: {{  $}}
    ; ALIGN-NEXT: $vgpr1 = COPY $vgpr3
    ; ALIGN-NEXT: $vgpr2 = COPY $vgpr4
    ; ALIGN-NEXT: S_ENDPGM 0, implicit $vgpr1, implicit $vgpr2
    ; GFX90A-NO-ALIGN-LABEL: name: test_odd_aligned_src_dst
    ; GFX90A-NO-ALIGN: liveins: $vgpr3, $vgpr4
    ; GFX90A-NO-ALIGN-NEXT: {{  $}}
    ; GFX90A-NO-ALIGN-NEXT: $vgpr1_vgpr2 = COPY $vgpr3_vgpr4, implicit $exec
    ; GFX90A-NO-ALIGN-NEXT: S_ENDPGM 0, implicit $vgpr1, implicit $vgpr2
    ;
    ; GFX90A-ALIGN-LABEL: name: test_odd_aligned_src_dst
    ; GFX90A-ALIGN: liveins: $vgpr3, $vgpr4
    ; GFX90A-ALIGN-NEXT: {{  $}}
    ; GFX90A-ALIGN-NEXT: $vgpr1 = COPY $vgpr3
    ; GFX90A-ALIGN-NEXT: $vgpr2 = COPY $vgpr4
    ; GFX90A-ALIGN-NEXT: S_ENDPGM 0, implicit $vgpr1, implicit $vgpr2
    ;
    ; GFX942-NO-ALIGN-LABEL: name: test_odd_aligned_src_dst
    ; GFX942-NO-ALIGN: liveins: $vgpr3, $vgpr4
    ; GFX942-NO-ALIGN-NEXT: {{  $}}
    ; GFX942-NO-ALIGN-NEXT: $vgpr1_vgpr2 = COPY $vgpr3_vgpr4, implicit $exec
    ; GFX942-NO-ALIGN-NEXT: S_ENDPGM 0, implicit $vgpr1, implicit $vgpr2
    ;
    ; GFX942-ALIGN-LABEL: name: test_odd_aligned_src_dst
    ; GFX942-ALIGN: liveins: $vgpr3, $vgpr4
    ; GFX942-ALIGN-NEXT: {{  $}}
    ; GFX942-ALIGN-NEXT: $vgpr1 = COPY $vgpr3
    ; GFX942-ALIGN-NEXT: $vgpr2 = COPY $vgpr4
    ; GFX942-ALIGN-NEXT: S_ENDPGM 0, implicit $vgpr1, implicit $vgpr2
    $vgpr1 = COPY $vgpr3
    $vgpr2 = COPY $vgpr4
    S_ENDPGM 0, implicit $vgpr1, implicit $vgpr2
...

---
name:            test_odd_aligned_dst_even_aligned_sgpr_src
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $sgpr4, $sgpr5
    ; GFX90A-LABEL: name: test_odd_aligned_dst_even_aligned_sgpr_src
    ; GFX90A: liveins: $sgpr4, $sgpr5
    ; GFX90A-NEXT: {{  $}}
    ; GFX90A-NEXT: $vgpr1 = COPY $sgpr4
    ; GFX90A-NEXT: $vgpr2 = COPY $sgpr5
    ; GFX90A-NEXT: S_ENDPGM 0, implicit $vgpr1, implicit $vgpr2
    ; ALIGN-LABEL: name: test_odd_aligned_dst_even_aligned_sgpr_src
    ; ALIGN: liveins: $sgpr4, $sgpr5
    ; ALIGN-NEXT: {{  $}}
    ; ALIGN-NEXT: $vgpr1 = COPY $sgpr4
    ; ALIGN-NEXT: $vgpr2 = COPY $sgpr5
    ; ALIGN-NEXT: S_ENDPGM 0, implicit $vgpr1, implicit $vgpr2
    ; GFX90A-NO-ALIGN-LABEL: name: test_odd_aligned_dst_even_aligned_sgpr_src
    ; GFX90A-NO-ALIGN: liveins: $sgpr4, $sgpr5
    ; GFX90A-NO-ALIGN-NEXT: {{  $}}
    ; GFX90A-NO-ALIGN-NEXT: $vgpr1 = COPY $sgpr4
    ; GFX90A-NO-ALIGN-NEXT: $vgpr2 = COPY $sgpr5
    ; GFX90A-NO-ALIGN-NEXT: S_ENDPGM 0, implicit $vgpr1, implicit $vgpr2
    ;
    ; GFX90A-ALIGN-LABEL: name: test_odd_aligned_dst_even_aligned_sgpr_src
    ; GFX90A-ALIGN: liveins: $sgpr4, $sgpr5
    ; GFX90A-ALIGN-NEXT: {{  $}}
    ; GFX90A-ALIGN-NEXT: $vgpr1 = COPY $sgpr4
    ; GFX90A-ALIGN-NEXT: $vgpr2 = COPY $sgpr5
    ; GFX90A-ALIGN-NEXT: S_ENDPGM 0, implicit $vgpr1, implicit $vgpr2
    ;
    ; GFX942-NO-ALIGN-LABEL: name: test_odd_aligned_dst_even_aligned_sgpr_src
    ; GFX942-NO-ALIGN: liveins: $sgpr4, $sgpr5
    ; GFX942-NO-ALIGN-NEXT: {{  $}}
    ; GFX942-NO-ALIGN-NEXT: $vgpr1_vgpr2 = COPY $sgpr4_sgpr5, implicit $exec
    ; GFX942-NO-ALIGN-NEXT: S_ENDPGM 0, implicit $vgpr1, implicit $vgpr2
    ;
    ; GFX942-ALIGN-LABEL: name: test_odd_aligned_dst_even_aligned_sgpr_src
    ; GFX942-ALIGN: liveins: $sgpr4, $sgpr5
    ; GFX942-ALIGN-NEXT: {{  $}}
    ; GFX942-ALIGN-NEXT: $vgpr1 = COPY $sgpr4
    ; GFX942-ALIGN-NEXT: $vgpr2 = COPY $sgpr5
    ; GFX942-ALIGN-NEXT: S_ENDPGM 0, implicit $vgpr1, implicit $vgpr2
    $vgpr1 = COPY $sgpr4
    $vgpr2 = COPY $sgpr5
    S_ENDPGM 0, implicit $vgpr1, implicit $vgpr2
...

---
name:            test_no_odd_aligned_sgpr_src
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $sgpr3, $sgpr4
    ; GCN-LABEL: name: test_no_odd_aligned_sgpr_src
    ; GCN: liveins: $sgpr3, $sgpr4
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: $vgpr0 = COPY $sgpr3
    ; GCN-NEXT: $vgpr1 = COPY $sgpr4
    ; GCN-NEXT: S_ENDPGM 0, implicit $vgpr0, implicit $vgpr1
    $vgpr0 = COPY $sgpr3
    $vgpr1 = COPY $sgpr4
    S_ENDPGM 0, implicit $vgpr0, implicit $vgpr1
...
