# NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx950 -start-after=livevars %s -o - | FileCheck -check-prefix=GCN %s

# Check that hinting mfma OpC and Dst to each other helps RA to avoid spilling
--- |
  define amdgpu_kernel void @mfma_hint_opc_and_dst_to_avoid_spilling(ptr addrspace(1) %out) #0 {
  ; GCN-LABEL: mfma_hint_opc_and_dst_to_avoid_spilling:
  ; GCN:       ; %bb.0:
  ; GCN-NEXT:    v_mov_b32_e32 v60, 0
  ; GCN-NEXT:    s_mov_b32 s0, 4
  ; GCN-NEXT:    v_mov_b32_e32 v61, v60
  ; GCN-NEXT:    v_mov_b32_e32 v62, v60
  ; GCN-NEXT:    v_mov_b32_e32 v63, v60
  ; GCN-NEXT:    v_mov_b32_e32 v0, v60
  ; GCN-NEXT:    v_mov_b32_e32 v1, v60
  ; GCN-NEXT:    v_mov_b32_e32 v2, v60
  ; GCN-NEXT:    v_mov_b32_e32 v3, v60
  ; GCN-NEXT:    v_mov_b32_e32 v4, v60
  ; GCN-NEXT:    v_mov_b32_e32 v5, v60
  ; GCN-NEXT:    v_mov_b32_e32 v6, v60
  ; GCN-NEXT:    v_mov_b32_e32 v7, v60
  ; GCN-NEXT:    v_mov_b32_e32 v8, v60
  ; GCN-NEXT:    v_mov_b32_e32 v9, v60
  ; GCN-NEXT:    v_mov_b32_e32 v10, v60
  ; GCN-NEXT:    v_mov_b32_e32 v11, v60
  ; GCN-NEXT:    v_mov_b32_e32 v12, v60
  ; GCN-NEXT:    v_mov_b32_e32 v13, v60
  ; GCN-NEXT:    v_mov_b32_e32 v14, v60
  ; GCN-NEXT:    v_mov_b32_e32 v15, v60
  ; GCN-NEXT:    v_mov_b32_e32 v16, v60
  ; GCN-NEXT:    v_mov_b32_e32 v17, v60
  ; GCN-NEXT:    v_mov_b32_e32 v18, v60
  ; GCN-NEXT:    v_mov_b32_e32 v19, v60
  ; GCN-NEXT:    v_mov_b32_e32 v20, v60
  ; GCN-NEXT:    v_mov_b32_e32 v21, v60
  ; GCN-NEXT:    v_mov_b32_e32 v22, v60
  ; GCN-NEXT:    v_mov_b32_e32 v23, v60
  ; GCN-NEXT:    v_mov_b32_e32 v24, v60
  ; GCN-NEXT:    v_mov_b32_e32 v25, v60
  ; GCN-NEXT:    v_mov_b32_e32 v26, v60
  ; GCN-NEXT:    v_mov_b32_e32 v27, v60
  ; GCN-NEXT:    .p2align 5, , 4
  ; GCN-NEXT:  .LBB0_1: ; =>This Inner Loop Header: Depth=1
  ; GCN-NEXT:    s_nop 5
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[28:31], v[0:3], v[0:3], v[24:27]
  ; GCN-NEXT:    s_add_i32 s0, s0, -1
  ; GCN-NEXT:    s_cmp_lg_u32 s0, 0
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[32:35], v[0:3], v[0:3], v[20:23]
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[36:39], v[0:3], v[0:3], v[16:19]
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[40:43], v[0:3], v[0:3], v[12:15]
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[44:47], v[0:3], v[0:3], v[8:11]
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[48:51], v[0:3], v[0:3], v[4:7]
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[52:55], v[0:3], v[0:3], v[0:3]
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[56:59], v[0:3], v[0:3], v[60:63]
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[24:27], v[0:3], v[0:3], v[28:31]
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[20:23], v[0:3], v[0:3], v[32:35]
  ; GCN-NEXT:    s_nop 0
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[16:19], v[0:3], v[0:3], v[36:39]
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[12:15], v[0:3], v[0:3], v[40:43]
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[8:11], v[0:3], v[0:3], v[44:47]
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[4:7], v[0:3], v[0:3], v[48:51]
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[0:3], v[0:3], v[0:3], v[52:55]
  ; GCN-NEXT:    s_nop 7
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[24:27], v[0:3], v[0:3], v[24:27]
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[20:23], v[0:3], v[0:3], v[20:23]
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[16:19], v[0:3], v[0:3], v[16:19]
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[12:15], v[0:3], v[0:3], v[12:15]
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[8:11], v[0:3], v[0:3], v[8:11]
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[4:7], v[0:3], v[0:3], v[4:7]
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[0:3], v[0:3], v[0:3], v[0:3]
  ; GCN-NEXT:    s_nop 7
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[60:63], v[0:3], v[0:3], v[56:59]
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[60:63], v[0:3], v[0:3], v[60:63]
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[24:27], v[0:3], v[0:3], v[24:27]
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[20:23], v[0:3], v[0:3], v[20:23]
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[16:19], v[0:3], v[0:3], v[16:19]
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[12:15], v[0:3], v[0:3], v[12:15]
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[8:11], v[0:3], v[0:3], v[8:11]
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[4:7], v[0:3], v[0:3], v[4:7]
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[0:3], v[0:3], v[0:3], v[0:3]
  ; GCN-NEXT:    s_nop 7
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[60:63], v[0:3], v[0:3], v[60:63]
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[24:27], v[0:3], v[0:3], v[24:27]
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[20:23], v[0:3], v[0:3], v[20:23]
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[16:19], v[0:3], v[0:3], v[16:19]
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[12:15], v[0:3], v[0:3], v[12:15]
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[8:11], v[0:3], v[0:3], v[8:11]
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[4:7], v[0:3], v[0:3], v[4:7]
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[0:3], v[0:3], v[0:3], v[0:3]
  ; GCN-NEXT:    s_nop 7
  ; GCN-NEXT:    v_mfma_f32_16x16x32_f16 v[60:63], v[0:3], v[0:3], v[60:63]
  ; GCN-NEXT:    s_cbranch_scc1 .LBB0_1
  ; GCN-NEXT:  ; %bb.2:
  ; GCN-NEXT:    s_load_dwordx2 s[0:1], s[4:5], 0x0
  ; GCN-NEXT:    s_mov_b32 s3, 0x27000
  ; GCN-NEXT:    s_mov_b32 s2, 0x7ffffffe
  ; GCN-NEXT:    s_waitcnt lgkmcnt(0)
  ; GCN-NEXT:    s_and_b32 s1, s1, 0xffff
  ; GCN-NEXT:    buffer_wbl2 sc0 sc1
  ; GCN-NEXT:    s_waitcnt vmcnt(0)
  ; GCN-NEXT:    buffer_store_dwordx4 v[28:31], off, s[0:3], 0 sc0 sc1
  ; GCN-NEXT:    buffer_wbl2 sc0 sc1
  ; GCN-NEXT:    s_waitcnt vmcnt(0)
  ; GCN-NEXT:    buffer_store_dwordx4 v[32:35], off, s[0:3], 0 offset:16 sc0 sc1
  ; GCN-NEXT:    buffer_wbl2 sc0 sc1
  ; GCN-NEXT:    s_waitcnt vmcnt(0)
  ; GCN-NEXT:    buffer_store_dwordx4 v[36:39], off, s[0:3], 0 offset:32 sc0 sc1
  ; GCN-NEXT:    buffer_wbl2 sc0 sc1
  ; GCN-NEXT:    s_waitcnt vmcnt(0)
  ; GCN-NEXT:    buffer_store_dwordx4 v[40:43], off, s[0:3], 0 offset:48 sc0 sc1
  ; GCN-NEXT:    buffer_wbl2 sc0 sc1
  ; GCN-NEXT:    s_waitcnt vmcnt(0)
  ; GCN-NEXT:    buffer_store_dwordx4 v[44:47], off, s[0:3], 0 offset:64 sc0 sc1
  ; GCN-NEXT:    buffer_wbl2 sc0 sc1
  ; GCN-NEXT:    s_waitcnt vmcnt(0)
  ; GCN-NEXT:    buffer_store_dwordx4 v[48:51], off, s[0:3], 0 offset:80 sc0 sc1
  ; GCN-NEXT:    buffer_wbl2 sc0 sc1
  ; GCN-NEXT:    s_waitcnt vmcnt(0)
  ; GCN-NEXT:    buffer_store_dwordx4 v[52:55], off, s[0:3], 0 offset:96 sc0 sc1
  ; GCN-NEXT:    buffer_wbl2 sc0 sc1
  ; GCN-NEXT:    s_waitcnt vmcnt(0)
  ; GCN-NEXT:    buffer_store_dwordx4 v[56:59], off, s[0:3], 0 offset:112 sc0 sc1
  ; GCN-NEXT:    s_endpgm
    ret void
  }

  attributes #0 = { "amdgpu-agpr-alloc"="0" "amdgpu-waves-per-eu"="8,8" }

  !0 = !{}
...
---
name:            mfma_hint_opc_and_dst_to_avoid_spilling
tracksRegLiveness: true
machineFunctionInfo:
  isEntryFunction: true
body:             |
  bb.0:
    successors: %bb.1(0x80000000)
    liveins: $sgpr4_sgpr5

    %85:sgpr_64(p4) = COPY killed $sgpr4_sgpr5
    %92:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
    %90:sreg_32 = S_MOV_B32 4

  bb.1:
    successors: %bb.2(0x04000000), %bb.1(0x7c000000)

    %0:sreg_32 = PHI %90, %bb.0, %73, %bb.1
    %1:av_32 = PHI %92, %bb.0, %41, %bb.1
    %2:av_32 = PHI %92, %bb.0, %42, %bb.1
    %3:av_32 = PHI %92, %bb.0, %43, %bb.1
    %4:av_32 = PHI %92, %bb.0, %44, %bb.1
    %5:av_32 = PHI %92, %bb.0, %45, %bb.1
    %6:av_32 = PHI %92, %bb.0, %46, %bb.1
    %7:av_32 = PHI %92, %bb.0, %47, %bb.1
    %8:av_32 = PHI %92, %bb.0, %48, %bb.1
    %9:av_32 = PHI %92, %bb.0, %49, %bb.1
    %10:av_32 = PHI %92, %bb.0, %50, %bb.1
    %11:av_32 = PHI %92, %bb.0, %51, %bb.1
    %12:av_32 = PHI %92, %bb.0, %52, %bb.1
    %13:av_32 = PHI %92, %bb.0, %53, %bb.1
    %14:av_32 = PHI %92, %bb.0, %54, %bb.1
    %15:av_32 = PHI %92, %bb.0, %55, %bb.1
    %16:av_32 = PHI %92, %bb.0, %56, %bb.1
    %17:av_32 = PHI %92, %bb.0, %57, %bb.1
    %18:av_32 = PHI %92, %bb.0, %58, %bb.1
    %19:av_32 = PHI %92, %bb.0, %59, %bb.1
    %20:av_32 = PHI %92, %bb.0, %60, %bb.1
    %21:av_32 = PHI %92, %bb.0, %61, %bb.1
    %22:av_32 = PHI %92, %bb.0, %62, %bb.1
    %23:av_32 = PHI %92, %bb.0, %63, %bb.1
    %24:av_32 = PHI %92, %bb.0, %64, %bb.1
    %25:av_32 = PHI %92, %bb.0, %65, %bb.1
    %26:av_32 = PHI %92, %bb.0, %66, %bb.1
    %27:av_32 = PHI %92, %bb.0, %67, %bb.1
    %28:av_32 = PHI %92, %bb.0, %68, %bb.1
    %29:av_32 = PHI %92, %bb.0, %69, %bb.1
    %30:av_32 = PHI %92, %bb.0, %70, %bb.1
    %31:av_32 = PHI %92, %bb.0, %71, %bb.1
    %32:av_32 = PHI %92, %bb.0, %72, %bb.1
    %93:vreg_128_align2 = REG_SEQUENCE killed %29, %subreg.sub0, killed %30, %subreg.sub1, killed %31, %subreg.sub2, killed %32, %subreg.sub3
    %94:vreg_128_align2 = REG_SEQUENCE killed %25, %subreg.sub0, killed %26, %subreg.sub1, killed %27, %subreg.sub2, killed %28, %subreg.sub3
    %95:vreg_128_align2 = REG_SEQUENCE killed %21, %subreg.sub0, killed %22, %subreg.sub1, killed %23, %subreg.sub2, killed %24, %subreg.sub3
    %96:vreg_128_align2 = REG_SEQUENCE killed %17, %subreg.sub0, killed %18, %subreg.sub1, killed %19, %subreg.sub2, killed %20, %subreg.sub3
    %97:vreg_128_align2 = REG_SEQUENCE killed %13, %subreg.sub0, killed %14, %subreg.sub1, killed %15, %subreg.sub2, killed %16, %subreg.sub3
    %98:vreg_128_align2 = REG_SEQUENCE killed %9, %subreg.sub0, killed %10, %subreg.sub1, killed %11, %subreg.sub2, killed %12, %subreg.sub3
    %99:vreg_128_align2 = REG_SEQUENCE killed %5, %subreg.sub0, killed %6, %subreg.sub1, killed %7, %subreg.sub2, killed %8, %subreg.sub3
    %100:vreg_128_align2 = REG_SEQUENCE killed %1, %subreg.sub0, killed %2, %subreg.sub1, killed %3, %subreg.sub2, killed %4, %subreg.sub3
    %101:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %103:av_128_align2, undef %105:av_128_align2, killed %93, 0, 0, 0, implicit $mode, implicit $exec
    %106:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %108:av_128_align2, undef %110:av_128_align2, killed %94, 0, 0, 0, implicit $mode, implicit $exec
    %111:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %113:av_128_align2, undef %115:av_128_align2, killed %95, 0, 0, 0, implicit $mode, implicit $exec
    %116:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %118:av_128_align2, undef %120:av_128_align2, killed %96, 0, 0, 0, implicit $mode, implicit $exec
    %121:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %123:av_128_align2, undef %125:av_128_align2, killed %97, 0, 0, 0, implicit $mode, implicit $exec
    %126:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %128:av_128_align2, undef %130:av_128_align2, killed %98, 0, 0, 0, implicit $mode, implicit $exec
    %131:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %133:av_128_align2, undef %135:av_128_align2, killed %99, 0, 0, 0, implicit $mode, implicit $exec
    %136:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %138:av_128_align2, undef %140:av_128_align2, killed %100, 0, 0, 0, implicit $mode, implicit $exec
    %141:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %143:av_128_align2, undef %145:av_128_align2, %101, 0, 0, 0, implicit $mode, implicit $exec
    %146:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %148:av_128_align2, undef %150:av_128_align2, %106, 0, 0, 0, implicit $mode, implicit $exec
    %151:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %153:av_128_align2, undef %155:av_128_align2, %111, 0, 0, 0, implicit $mode, implicit $exec
    %156:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %158:av_128_align2, undef %160:av_128_align2, %116, 0, 0, 0, implicit $mode, implicit $exec
    %161:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %163:av_128_align2, undef %165:av_128_align2, %121, 0, 0, 0, implicit $mode, implicit $exec
    %166:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %168:av_128_align2, undef %170:av_128_align2, %126, 0, 0, 0, implicit $mode, implicit $exec
    %171:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %173:av_128_align2, undef %175:av_128_align2, %131, 0, 0, 0, implicit $mode, implicit $exec
    %176:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %178:av_128_align2, undef %180:av_128_align2, %136, 0, 0, 0, implicit $mode, implicit $exec
    %181:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %183:av_128_align2, undef %185:av_128_align2, killed %141, 0, 0, 0, implicit $mode, implicit $exec
    %186:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %188:av_128_align2, undef %190:av_128_align2, killed %146, 0, 0, 0, implicit $mode, implicit $exec
    %191:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %193:av_128_align2, undef %195:av_128_align2, killed %151, 0, 0, 0, implicit $mode, implicit $exec
    %196:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %198:av_128_align2, undef %200:av_128_align2, killed %156, 0, 0, 0, implicit $mode, implicit $exec
    %201:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %203:av_128_align2, undef %205:av_128_align2, killed %161, 0, 0, 0, implicit $mode, implicit $exec
    %206:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %208:av_128_align2, undef %210:av_128_align2, killed %166, 0, 0, 0, implicit $mode, implicit $exec
    %211:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %213:av_128_align2, undef %215:av_128_align2, killed %171, 0, 0, 0, implicit $mode, implicit $exec
    %216:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %218:av_128_align2, undef %220:av_128_align2, killed %176, 0, 0, 0, implicit $mode, implicit $exec
    %221:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %223:av_128_align2, undef %225:av_128_align2, killed %181, 0, 0, 0, implicit $mode, implicit $exec
    %226:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %228:av_128_align2, undef %230:av_128_align2, killed %186, 0, 0, 0, implicit $mode, implicit $exec
    %231:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %233:av_128_align2, undef %235:av_128_align2, killed %191, 0, 0, 0, implicit $mode, implicit $exec
    %236:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %238:av_128_align2, undef %240:av_128_align2, killed %196, 0, 0, 0, implicit $mode, implicit $exec
    %241:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %243:av_128_align2, undef %245:av_128_align2, killed %201, 0, 0, 0, implicit $mode, implicit $exec
    %246:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %248:av_128_align2, undef %250:av_128_align2, killed %206, 0, 0, 0, implicit $mode, implicit $exec
    %251:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %253:av_128_align2, undef %255:av_128_align2, killed %211, 0, 0, 0, implicit $mode, implicit $exec
    %256:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %258:av_128_align2, undef %260:av_128_align2, killed %216, 0, 0, 0, implicit $mode, implicit $exec
    %261:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %263:av_128_align2, undef %265:av_128_align2, killed %221, 0, 0, 0, implicit $mode, implicit $exec
    %266:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %268:av_128_align2, undef %270:av_128_align2, killed %226, 0, 0, 0, implicit $mode, implicit $exec
    %271:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %273:av_128_align2, undef %275:av_128_align2, killed %231, 0, 0, 0, implicit $mode, implicit $exec
    %276:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %278:av_128_align2, undef %280:av_128_align2, killed %236, 0, 0, 0, implicit $mode, implicit $exec
    %281:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %283:av_128_align2, undef %285:av_128_align2, killed %241, 0, 0, 0, implicit $mode, implicit $exec
    %286:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %288:av_128_align2, undef %290:av_128_align2, killed %246, 0, 0, 0, implicit $mode, implicit $exec
    %291:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %293:av_128_align2, undef %295:av_128_align2, killed %251, 0, 0, 0, implicit $mode, implicit $exec
    S_NOP 0
    S_NOP 0
    S_NOP 0
    S_NOP 0
    S_NOP 0
    S_NOP 0
    S_NOP 0
    S_NOP 0
    S_NOP 0
    S_NOP 0
    S_NOP 0
    S_NOP 0
    S_NOP 0
    S_NOP 0
    S_NOP 0
    S_NOP 0
    S_NOP 0
    S_NOP 0
    S_NOP 0
    S_NOP 0
    S_NOP 0
    S_NOP 0
    S_NOP 0
    S_NOP 0
    S_NOP 0
    S_NOP 0
    %296:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 undef %298:av_128_align2, undef %300:av_128_align2, killed %256, 0, 0, 0, implicit $mode, implicit $exec
    %41:av_32 = COPY %296.sub0
    %42:av_32 = COPY %296.sub1
    %43:av_32 = COPY %296.sub2
    %44:av_32 = COPY killed %296.sub3
    %45:av_32 = COPY %291.sub0
    %46:av_32 = COPY %291.sub1
    %47:av_32 = COPY %291.sub2
    %48:av_32 = COPY killed %291.sub3
    %49:av_32 = COPY %286.sub0
    %50:av_32 = COPY %286.sub1
    %51:av_32 = COPY %286.sub2
    %52:av_32 = COPY killed %286.sub3
    %53:av_32 = COPY %281.sub0
    %54:av_32 = COPY %281.sub1
    %55:av_32 = COPY %281.sub2
    %56:av_32 = COPY killed %281.sub3
    %57:av_32 = COPY %276.sub0
    %58:av_32 = COPY %276.sub1
    %59:av_32 = COPY %276.sub2
    %60:av_32 = COPY killed %276.sub3
    %61:av_32 = COPY %271.sub0
    %62:av_32 = COPY %271.sub1
    %63:av_32 = COPY %271.sub2
    %64:av_32 = COPY killed %271.sub3
    %65:av_32 = COPY %266.sub0
    %66:av_32 = COPY %266.sub1
    %67:av_32 = COPY %266.sub2
    %68:av_32 = COPY killed %266.sub3
    %69:av_32 = COPY %261.sub0
    %70:av_32 = COPY %261.sub1
    %71:av_32 = COPY %261.sub2
    %72:av_32 = COPY killed %261.sub3
    %73:sreg_32 = nsw S_ADD_I32 killed %0, -1, implicit-def dead $scc
    S_CMP_LG_U32 %73, 0, implicit-def $scc
    S_CBRANCH_SCC1 %bb.1, implicit killed $scc
    S_BRANCH %bb.2

  bb.2:
    %303:sreg_64_xexec = S_LOAD_DWORDX2_IMM killed %85(p4), 0, 0
    %306:sreg_32 = S_AND_B32 %303.sub1, 65535, implicit-def dead $scc
    %308:sreg_32 = S_MOV_B32 159744
    %309:sreg_32 = S_MOV_B32 2147483646
    %310:sgpr_128 = REG_SEQUENCE killed %303.sub0, %subreg.sub0, killed %306, %subreg.sub1, killed %309, %subreg.sub2, killed %308, %subreg.sub3
    BUFFER_STORE_DWORDX4_OFFSET_exact killed %101, %310, 0, 0, 0, 0, implicit $exec
    BUFFER_STORE_DWORDX4_OFFSET_exact killed %106, %310, 0, 16, 0, 0, implicit $exec
    BUFFER_STORE_DWORDX4_OFFSET_exact killed %111, %310, 0, 32, 0, 0, implicit $exec
    BUFFER_STORE_DWORDX4_OFFSET_exact killed %116, %310, 0, 48, 0, 0, implicit $exec
    BUFFER_STORE_DWORDX4_OFFSET_exact killed %121, %310, 0, 64, 0, 0, implicit $exec
    BUFFER_STORE_DWORDX4_OFFSET_exact killed %126, %310, 0, 80, 0, 0, implicit $exec
    BUFFER_STORE_DWORDX4_OFFSET_exact killed %131, %310, 0, 96, 0, 0, implicit $exec
    BUFFER_STORE_DWORDX4_OFFSET_exact killed %136, killed %310, 0, 112, 0, 0, implicit $exec
    S_ENDPGM 0
...
