# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -march=amdgcn -mcpu=gfx90a -run-pass=machine-scheduler %s -o - -amdgpu-mfma-cluster=1 2>&1 | FileCheck -check-prefix=PRERA %s
# RUN: llc -march=amdgcn -mcpu=gfx90a -run-pass=machine-scheduler %s -o - 2>&1 | FileCheck -check-prefix=DEFAULT %s
# RUN: llc -march=amdgcn -mcpu=gfx90a -start-before=machine-scheduler -stop-after=postmisched %s -o - -amdgpu-mfma-cluster=1 2>&1 | FileCheck -check-prefix=BOTHSCHEDPASS %s
# RUN: llc -march=amdgcn -mcpu=gfx90a -run-pass=machine-scheduler %s -o - -amdgpu-mfma-cluster=1 -amdgpu-mfma-cluster-size=2 2>&1 | FileCheck -check-prefix=TWOLIMIT %s
# RUN: llc -march=amdgcn -mcpu=gfx90a -run-pass=postmisched  %s -o - -amdgpu-mfma-cluster=1 2>&1| FileCheck -check-prefix=POSTRA %s


---
name: no_cluster
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $sgpr0, $vgpr10_vgpr11
    ; PRERA-LABEL: name: no_cluster
    ; PRERA: liveins: $sgpr0, $vgpr10_vgpr11
    ; PRERA-NEXT: {{  $}}
    ; PRERA-NEXT: $vgpr1 = V_MOV_B32_e32 1, implicit $exec
    ; PRERA-NEXT: $vgpr0 = V_MOV_B32_e32 1, implicit $exec
    ; PRERA-NEXT: $vgpr1 = V_ADD_F16_e32 $vgpr1, $vgpr0, implicit $mode, implicit $exec
    ; PRERA-NEXT: GLOBAL_STORE_DWORD $vgpr10_vgpr11, $vgpr1, 0, 0, implicit $exec
    ; PRERA-NEXT: $vgpr2 = V_MOV_B32_e32 1, implicit $exec
    ; PRERA-NEXT: $vgpr3 = DS_READ_U16_gfx9 $vgpr2, 0, 0, implicit $exec
    ; PRERA-NEXT: $vgpr4 = GLOBAL_LOAD_USHORT $vgpr0_vgpr1, 0, 0, implicit $exec
    ; PRERA-NEXT: $vgpr8 = V_MOV_B32_e32 0, implicit $exec
    ; PRERA-NEXT: $vgpr9 = V_MOV_B32_e32 9, implicit $exec
    ; PRERA-NEXT: $vgpr7 = GLOBAL_LOAD_USHORT $vgpr8_vgpr9, 0, 0, implicit $exec
    ; PRERA-NEXT: $vgpr5 = V_XOR_B32_e32 $vgpr1, $vgpr0, implicit $exec
    ; PRERA-NEXT: $vgpr6 = V_MUL_LO_U32_e64 $vgpr1, $sgpr0, implicit $exec
    ; DEFAULT-LABEL: name: no_cluster
    ; DEFAULT: liveins: $sgpr0, $vgpr10_vgpr11
    ; DEFAULT-NEXT: {{  $}}
    ; DEFAULT-NEXT: $vgpr1 = V_MOV_B32_e32 1, implicit $exec
    ; DEFAULT-NEXT: $vgpr0 = V_MOV_B32_e32 1, implicit $exec
    ; DEFAULT-NEXT: $vgpr1 = V_ADD_F16_e32 $vgpr1, $vgpr0, implicit $mode, implicit $exec
    ; DEFAULT-NEXT: GLOBAL_STORE_DWORD $vgpr10_vgpr11, $vgpr1, 0, 0, implicit $exec
    ; DEFAULT-NEXT: $vgpr2 = V_MOV_B32_e32 1, implicit $exec
    ; DEFAULT-NEXT: $vgpr3 = DS_READ_U16_gfx9 $vgpr2, 0, 0, implicit $exec
    ; DEFAULT-NEXT: $vgpr4 = GLOBAL_LOAD_USHORT $vgpr0_vgpr1, 0, 0, implicit $exec
    ; DEFAULT-NEXT: $vgpr8 = V_MOV_B32_e32 0, implicit $exec
    ; DEFAULT-NEXT: $vgpr9 = V_MOV_B32_e32 9, implicit $exec
    ; DEFAULT-NEXT: $vgpr7 = GLOBAL_LOAD_USHORT $vgpr8_vgpr9, 0, 0, implicit $exec
    ; DEFAULT-NEXT: $vgpr5 = V_XOR_B32_e32 $vgpr1, $vgpr0, implicit $exec
    ; DEFAULT-NEXT: $vgpr6 = V_MUL_LO_U32_e64 $vgpr1, $sgpr0, implicit $exec
    ; BOTHSCHEDPASS-LABEL: name: no_cluster
    ; BOTHSCHEDPASS: liveins: $sgpr0, $vgpr10_vgpr11
    ; BOTHSCHEDPASS-NEXT: {{  $}}
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION llvm_def_aspace_cfa <badreg>, 0, 6
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION escape 0x10, 0x10, 0x08, 0x90, 0x3e, 0x93, 0x04, 0x90, 0x3f, 0x93, 0x04
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr0_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr1_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr2_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr3_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr4_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr5_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr6_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr7_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr8_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr9_lo16
    ; BOTHSCHEDPASS-NEXT: $vgpr1 = V_MOV_B32_e32 1, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr0 = V_MOV_B32_e32 1, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr1 = V_ADD_F16_e32 killed $vgpr1, $vgpr0, implicit $mode, implicit $exec
    ; BOTHSCHEDPASS-NEXT: GLOBAL_STORE_DWORD killed $vgpr10_vgpr11, $vgpr1, 0, 0, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr2 = V_MOV_B32_e32 1, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr8 = V_MOV_B32_e32 0, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr9 = V_MOV_B32_e32 9, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr3 = DS_READ_U16_gfx9 killed $vgpr2, 0, 0, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr4 = GLOBAL_LOAD_USHORT $vgpr0_vgpr1, 0, 0, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr7 = GLOBAL_LOAD_USHORT killed $vgpr8_vgpr9, 0, 0, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr5 = V_XOR_B32_e32 $vgpr1, killed $vgpr0, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr6 = V_MUL_LO_U32_e64 killed $vgpr1, killed $sgpr0, implicit $exec
    ; TWOLIMIT-LABEL: name: no_cluster
    ; TWOLIMIT: liveins: $sgpr0, $vgpr10_vgpr11
    ; TWOLIMIT-NEXT: {{  $}}
    ; TWOLIMIT-NEXT: $vgpr1 = V_MOV_B32_e32 1, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr0 = V_MOV_B32_e32 1, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr1 = V_ADD_F16_e32 $vgpr1, $vgpr0, implicit $mode, implicit $exec
    ; TWOLIMIT-NEXT: GLOBAL_STORE_DWORD $vgpr10_vgpr11, $vgpr1, 0, 0, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr2 = V_MOV_B32_e32 1, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr3 = DS_READ_U16_gfx9 $vgpr2, 0, 0, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr4 = GLOBAL_LOAD_USHORT $vgpr0_vgpr1, 0, 0, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr8 = V_MOV_B32_e32 0, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr9 = V_MOV_B32_e32 9, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr7 = GLOBAL_LOAD_USHORT $vgpr8_vgpr9, 0, 0, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr5 = V_XOR_B32_e32 $vgpr1, $vgpr0, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr6 = V_MUL_LO_U32_e64 $vgpr1, $sgpr0, implicit $exec
    ; POSTRA-LABEL: name: no_cluster
    ; POSTRA: liveins: $sgpr0, $vgpr10_vgpr11
    ; POSTRA-NEXT: {{  $}}
    ; POSTRA-NEXT: $vgpr1 = V_MOV_B32_e32 1, implicit $exec
    ; POSTRA-NEXT: $vgpr0 = V_MOV_B32_e32 1, implicit $exec
    ; POSTRA-NEXT: $vgpr1 = V_ADD_F16_e32 killed $vgpr1, $vgpr0, implicit $mode, implicit $exec
    ; POSTRA-NEXT: $vgpr8 = V_MOV_B32_e32 0, implicit $exec
    ; POSTRA-NEXT: $vgpr9 = V_MOV_B32_e32 9, implicit $exec
    ; POSTRA-NEXT: GLOBAL_STORE_DWORD killed $vgpr10_vgpr11, $vgpr1, 0, 0, implicit $exec
    ; POSTRA-NEXT: $vgpr2 = V_MOV_B32_e32 1, implicit $exec
    ; POSTRA-NEXT: $vgpr3 = DS_READ_U16_gfx9 killed $vgpr2, 0, 0, implicit $exec
    ; POSTRA-NEXT: $vgpr4 = GLOBAL_LOAD_USHORT $vgpr0_vgpr1, 0, 0, implicit $exec
    ; POSTRA-NEXT: $vgpr7 = GLOBAL_LOAD_USHORT killed $vgpr8_vgpr9, 0, 0, implicit $exec
    ; POSTRA-NEXT: $vgpr5 = V_XOR_B32_e32 $vgpr1, killed $vgpr0, implicit $exec
    ; POSTRA-NEXT: $vgpr6 = V_MUL_LO_U32_e64 killed $vgpr1, killed $sgpr0, implicit $exec
    $vgpr1 = V_MOV_B32_e32 1, implicit $exec
    $vgpr0 = V_MOV_B32_e32 1, implicit $exec
    $vgpr8 = V_MOV_B32_e32 0, implicit $exec
    $vgpr9 = V_MOV_B32_e32 9, implicit $exec
    $vgpr1 = V_ADD_F16_e32 $vgpr1, $vgpr0, implicit $mode, implicit $exec
    GLOBAL_STORE_DWORD $vgpr10_vgpr11, $vgpr1, 0, 0, implicit $exec
    $vgpr2 = V_MOV_B32_e32 1, implicit $exec
    $vgpr3 = DS_READ_U16_gfx9 $vgpr2, 0, 0, implicit $exec
    $vgpr4 = GLOBAL_LOAD_USHORT $vgpr0_vgpr1, 0, 0, implicit $exec
    $vgpr5 = V_XOR_B32_e32 $vgpr1, $vgpr0, implicit $exec
    $vgpr6 = V_MUL_LO_U32_e64 $vgpr1, $sgpr0, implicit $exec
    $vgpr7 = GLOBAL_LOAD_USHORT $vgpr8_vgpr9, 0, 0, implicit $exec
...


---
name: basic_cluster
tracksRegLiveness: true
body:             |
  bb.0:
    liveins:  $agpr0_agpr1_agpr2_agpr3, $agpr4_agpr5_agpr6_agpr7,  $agpr8_agpr9_agpr10_agpr11, $agpr12_agpr13_agpr14_agpr15
    ; PRERA-LABEL: name: basic_cluster
    ; PRERA: liveins: $agpr0_agpr1_agpr2_agpr3, $agpr4_agpr5_agpr6_agpr7, $agpr8_agpr9_agpr10_agpr11, $agpr12_agpr13_agpr14_agpr15
    ; PRERA-NEXT: {{  $}}
    ; PRERA-NEXT: $vgpr1 = V_MOV_B32_e32 1, implicit $exec
    ; PRERA-NEXT: $vgpr3 = V_MOV_B32_e32 1, implicit $exec
    ; PRERA-NEXT: $vgpr0 = V_MOV_B32_e32 1, implicit $exec
    ; PRERA-NEXT: $vgpr4 = V_MOV_B32_e32 1, implicit $exec
    ; PRERA-NEXT: $agpr0_agpr1_agpr2_agpr3 = V_MFMA_F32_4X4X1F32_e64 $vgpr1, $vgpr0, $agpr0_agpr1_agpr2_agpr3, 0, 0, 0, implicit $mode, implicit $exec
    ; PRERA-NEXT: $agpr4_agpr5_agpr6_agpr7 = V_MFMA_F32_4X4X1F32_e64 $vgpr3, $vgpr4, $agpr4_agpr5_agpr6_agpr7, 0, 0, 0, implicit $mode, implicit $exec
    ; PRERA-NEXT: $agpr8_agpr9_agpr10_agpr11 = V_MFMA_F32_4X4X1F32_e64 $vgpr3, $vgpr4, $agpr8_agpr9_agpr10_agpr11, 0, 0, 0, implicit $mode, implicit $exec
    ; PRERA-NEXT: $vgpr5 = V_XOR_B32_e32 $vgpr1, $vgpr0, implicit $exec
    ; PRERA-NEXT: $agpr12_agpr13_agpr14_agpr15 = V_MFMA_F32_4X4X1F32_e64 $vgpr1, $vgpr0, $agpr12_agpr13_agpr14_agpr15, 0, 0, 0, implicit $mode, implicit $exec
    ; PRERA-NEXT: $vgpr5 = V_MOV_B32_e32 1, implicit $exec
    ; PRERA-NEXT: $vgpr6 = V_MOV_B32_e32 1, implicit $exec
    ; PRERA-NEXT: $agpr4_agpr5_agpr6_agpr7 = V_MFMA_F32_4X4X1F32_e64 $vgpr5, $vgpr6, $agpr4_agpr5_agpr6_agpr7, 0, 0, 0, implicit $mode, implicit $exec
    ; PRERA-NEXT: $vgpr2 = V_MOV_B32_e32 1, implicit $exec
    ; DEFAULT-LABEL: name: basic_cluster
    ; DEFAULT: liveins: $agpr0_agpr1_agpr2_agpr3, $agpr4_agpr5_agpr6_agpr7, $agpr8_agpr9_agpr10_agpr11, $agpr12_agpr13_agpr14_agpr15
    ; DEFAULT-NEXT: {{  $}}
    ; DEFAULT-NEXT: $vgpr1 = V_MOV_B32_e32 1, implicit $exec
    ; DEFAULT-NEXT: $vgpr0 = V_MOV_B32_e32 1, implicit $exec
    ; DEFAULT-NEXT: $agpr0_agpr1_agpr2_agpr3 = V_MFMA_F32_4X4X1F32_e64 $vgpr1, $vgpr0, $agpr0_agpr1_agpr2_agpr3, 0, 0, 0, implicit $mode, implicit $exec
    ; DEFAULT-NEXT: $vgpr3 = V_MOV_B32_e32 1, implicit $exec
    ; DEFAULT-NEXT: $vgpr4 = V_MOV_B32_e32 1, implicit $exec
    ; DEFAULT-NEXT: $agpr4_agpr5_agpr6_agpr7 = V_MFMA_F32_4X4X1F32_e64 $vgpr3, $vgpr4, $agpr4_agpr5_agpr6_agpr7, 0, 0, 0, implicit $mode, implicit $exec
    ; DEFAULT-NEXT: $vgpr5 = V_XOR_B32_e32 $vgpr1, $vgpr0, implicit $exec
    ; DEFAULT-NEXT: $agpr8_agpr9_agpr10_agpr11 = V_MFMA_F32_4X4X1F32_e64 $vgpr3, $vgpr4, $agpr8_agpr9_agpr10_agpr11, 0, 0, 0, implicit $mode, implicit $exec
    ; DEFAULT-NEXT: $vgpr5 = V_MOV_B32_e32 1, implicit $exec
    ; DEFAULT-NEXT: $vgpr6 = V_MOV_B32_e32 1, implicit $exec
    ; DEFAULT-NEXT: $agpr4_agpr5_agpr6_agpr7 = V_MFMA_F32_4X4X1F32_e64 $vgpr5, $vgpr6, $agpr4_agpr5_agpr6_agpr7, 0, 0, 0, implicit $mode, implicit $exec
    ; DEFAULT-NEXT: $agpr12_agpr13_agpr14_agpr15 = V_MFMA_F32_4X4X1F32_e64 $vgpr1, $vgpr0, $agpr12_agpr13_agpr14_agpr15, 0, 0, 0, implicit $mode, implicit $exec
    ; DEFAULT-NEXT: $vgpr2 = V_MOV_B32_e32 1, implicit $exec
    ; BOTHSCHEDPASS-LABEL: name: basic_cluster
    ; BOTHSCHEDPASS: liveins: $agpr0_agpr1_agpr2_agpr3, $agpr4_agpr5_agpr6_agpr7, $agpr8_agpr9_agpr10_agpr11, $agpr12_agpr13_agpr14_agpr15
    ; BOTHSCHEDPASS-NEXT: {{  $}}
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION llvm_def_aspace_cfa <badreg>, 0, 6
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION escape 0x10, 0x10, 0x08, 0x90, 0x3e, 0x93, 0x04, 0x90, 0x3f, 0x93, 0x04
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr0_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr1_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr2_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr3_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr4_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr5_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr6_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr0_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr1_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr2_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr3_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr4_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr5_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr6_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr7_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr8_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr9_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr10_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr11_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr12_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr13_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr14_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr15_lo16
    ; BOTHSCHEDPASS-NEXT: $vgpr1 = V_MOV_B32_e32 1, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr3 = V_MOV_B32_e32 1, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr0 = V_MOV_B32_e32 1, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr5 = V_XOR_B32_e32 $vgpr1, $vgpr0, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr5 = V_MOV_B32_e32 1, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr4 = V_MOV_B32_e32 1, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $agpr0_agpr1_agpr2_agpr3 = V_MFMA_F32_4X4X1F32_e64 $vgpr1, $vgpr0, killed $agpr0_agpr1_agpr2_agpr3, 0, 0, 0, implicit $mode, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr6 = V_MOV_B32_e32 1, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $agpr4_agpr5_agpr6_agpr7 = V_MFMA_F32_4X4X1F32_e64 $vgpr3, $vgpr4, killed $agpr4_agpr5_agpr6_agpr7, 0, 0, 0, implicit $mode, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr2 = V_MOV_B32_e32 1, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $agpr8_agpr9_agpr10_agpr11 = V_MFMA_F32_4X4X1F32_e64 killed $vgpr3, killed $vgpr4, killed $agpr8_agpr9_agpr10_agpr11, 0, 0, 0, implicit $mode, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $agpr12_agpr13_agpr14_agpr15 = V_MFMA_F32_4X4X1F32_e64 killed $vgpr1, killed $vgpr0, killed $agpr12_agpr13_agpr14_agpr15, 0, 0, 0, implicit $mode, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $agpr4_agpr5_agpr6_agpr7 = V_MFMA_F32_4X4X1F32_e64 killed $vgpr5, killed $vgpr6, killed $agpr4_agpr5_agpr6_agpr7, 0, 0, 0, implicit $mode, implicit $exec
    ; TWOLIMIT-LABEL: name: basic_cluster
    ; TWOLIMIT: liveins: $agpr0_agpr1_agpr2_agpr3, $agpr4_agpr5_agpr6_agpr7, $agpr8_agpr9_agpr10_agpr11, $agpr12_agpr13_agpr14_agpr15
    ; TWOLIMIT-NEXT: {{  $}}
    ; TWOLIMIT-NEXT: $vgpr1 = V_MOV_B32_e32 1, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr3 = V_MOV_B32_e32 1, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr0 = V_MOV_B32_e32 1, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr4 = V_MOV_B32_e32 1, implicit $exec
    ; TWOLIMIT-NEXT: $agpr0_agpr1_agpr2_agpr3 = V_MFMA_F32_4X4X1F32_e64 $vgpr1, $vgpr0, $agpr0_agpr1_agpr2_agpr3, 0, 0, 0, implicit $mode, implicit $exec
    ; TWOLIMIT-NEXT: $agpr4_agpr5_agpr6_agpr7 = V_MFMA_F32_4X4X1F32_e64 $vgpr3, $vgpr4, $agpr4_agpr5_agpr6_agpr7, 0, 0, 0, implicit $mode, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr5 = V_XOR_B32_e32 $vgpr1, $vgpr0, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr5 = V_MOV_B32_e32 1, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr6 = V_MOV_B32_e32 1, implicit $exec
    ; TWOLIMIT-NEXT: $agpr8_agpr9_agpr10_agpr11 = V_MFMA_F32_4X4X1F32_e64 $vgpr3, $vgpr4, $agpr8_agpr9_agpr10_agpr11, 0, 0, 0, implicit $mode, implicit $exec
    ; TWOLIMIT-NEXT: $agpr4_agpr5_agpr6_agpr7 = V_MFMA_F32_4X4X1F32_e64 $vgpr5, $vgpr6, $agpr4_agpr5_agpr6_agpr7, 0, 0, 0, implicit $mode, implicit $exec
    ; TWOLIMIT-NEXT: $agpr12_agpr13_agpr14_agpr15 = V_MFMA_F32_4X4X1F32_e64 $vgpr1, $vgpr0, $agpr12_agpr13_agpr14_agpr15, 0, 0, 0, implicit $mode, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr2 = V_MOV_B32_e32 1, implicit $exec
    ; POSTRA-LABEL: name: basic_cluster
    ; POSTRA: liveins: $agpr0_agpr1_agpr2_agpr3, $agpr4_agpr5_agpr6_agpr7, $agpr8_agpr9_agpr10_agpr11, $agpr12_agpr13_agpr14_agpr15
    ; POSTRA-NEXT: {{  $}}
    ; POSTRA-NEXT: $vgpr1 = V_MOV_B32_e32 1, implicit $exec
    ; POSTRA-NEXT: $vgpr0 = V_MOV_B32_e32 1, implicit $exec
    ; POSTRA-NEXT: $vgpr3 = V_MOV_B32_e32 1, implicit $exec
    ; POSTRA-NEXT: $vgpr5 = V_XOR_B32_e32 $vgpr1, $vgpr0, implicit $exec
    ; POSTRA-NEXT: $vgpr5 = V_MOV_B32_e32 1, implicit $exec
    ; POSTRA-NEXT: $vgpr4 = V_MOV_B32_e32 1, implicit $exec
    ; POSTRA-NEXT: $agpr0_agpr1_agpr2_agpr3 = V_MFMA_F32_4X4X1F32_e64 $vgpr1, $vgpr0, killed $agpr0_agpr1_agpr2_agpr3, 0, 0, 0, implicit $mode, implicit $exec
    ; POSTRA-NEXT: $vgpr6 = V_MOV_B32_e32 1, implicit $exec
    ; POSTRA-NEXT: $agpr4_agpr5_agpr6_agpr7 = V_MFMA_F32_4X4X1F32_e64 $vgpr3, $vgpr4, killed $agpr4_agpr5_agpr6_agpr7, 0, 0, 0, implicit $mode, implicit $exec
    ; POSTRA-NEXT: $vgpr2 = V_MOV_B32_e32 1, implicit $exec
    ; POSTRA-NEXT: $agpr8_agpr9_agpr10_agpr11 = V_MFMA_F32_4X4X1F32_e64 killed $vgpr3, killed $vgpr4, killed $agpr8_agpr9_agpr10_agpr11, 0, 0, 0, implicit $mode, implicit $exec
    ; POSTRA-NEXT: $agpr12_agpr13_agpr14_agpr15 = V_MFMA_F32_4X4X1F32_e64 killed $vgpr1, killed $vgpr0, killed $agpr12_agpr13_agpr14_agpr15, 0, 0, 0, implicit $mode, implicit $exec
    ; POSTRA-NEXT: $agpr4_agpr5_agpr6_agpr7 = V_MFMA_F32_4X4X1F32_e64 killed $vgpr5, killed $vgpr6, killed $agpr4_agpr5_agpr6_agpr7, 0, 0, 0, implicit $mode, implicit $exec
    $vgpr1 = V_MOV_B32_e32 1, implicit $exec
    $vgpr0 = V_MOV_B32_e32 1, implicit $exec
    $agpr0_agpr1_agpr2_agpr3 = V_MFMA_F32_4X4X1F32_e64 $vgpr1, $vgpr0, $agpr0_agpr1_agpr2_agpr3, 0, 0, 0, implicit $mode, implicit $exec
    $vgpr2 = V_MOV_B32_e32 1, implicit $exec
    $vgpr3 = V_MOV_B32_e32 1, implicit $exec
    $vgpr4 = V_MOV_B32_e32 1, implicit $exec
    $agpr4_agpr5_agpr6_agpr7 = V_MFMA_F32_4X4X1F32_e64 $vgpr3, $vgpr4, $agpr4_agpr5_agpr6_agpr7, 0, 0, 0, implicit $mode, implicit $exec
    $vgpr5 = V_XOR_B32_e32 $vgpr1, $vgpr0, implicit $exec
    $vgpr5 = V_MOV_B32_e32 1, implicit $exec
    $vgpr6 = V_MOV_B32_e32 1, implicit $exec
    $agpr8_agpr9_agpr10_agpr11 = V_MFMA_F32_4X4X1F32_e64 $vgpr3, $vgpr4, $agpr8_agpr9_agpr10_agpr11, 0, 0, 0, implicit $mode, implicit $exec
    $agpr4_agpr5_agpr6_agpr7 = V_MFMA_F32_4X4X1F32_e64 $vgpr5, $vgpr6, $agpr4_agpr5_agpr6_agpr7, 0, 0, 0, implicit $mode, implicit $exec
    $agpr12_agpr13_agpr14_agpr15 = V_MFMA_F32_4X4X1F32_e64 $vgpr1, $vgpr0, $agpr12_agpr13_agpr14_agpr15, 0, 0, 0, implicit $mode, implicit $exec
...


---
name: complex_cluster
tracksRegLiveness: true
body:             |
  bb.0:
    liveins:  $agpr0_agpr1_agpr2_agpr3, $agpr4_agpr5_agpr6_agpr7,  $agpr8_agpr9_agpr10_agpr11, $agpr12_agpr13_agpr14_agpr15, $sgpr0, $vgpr10_vgpr11
    ; PRERA-LABEL: name: complex_cluster
    ; PRERA: liveins: $agpr0_agpr1_agpr2_agpr3, $agpr4_agpr5_agpr6_agpr7, $agpr8_agpr9_agpr10_agpr11, $agpr12_agpr13_agpr14_agpr15, $sgpr0, $vgpr10_vgpr11
    ; PRERA-NEXT: {{  $}}
    ; PRERA-NEXT: $vgpr1 = V_MOV_B32_e32 1, implicit $exec
    ; PRERA-NEXT: $vgpr0 = V_MOV_B32_e32 1, implicit $exec
    ; PRERA-NEXT: $agpr0_agpr1_agpr2_agpr3 = V_MFMA_F32_4X4X1F32_e64 $vgpr1, $vgpr0, $agpr0_agpr1_agpr2_agpr3, 0, 0, 0, implicit $mode, implicit $exec
    ; PRERA-NEXT: $vgpr1 = V_ADD_F16_e32 $vgpr1, $vgpr0, implicit $mode, implicit $exec
    ; PRERA-NEXT: GLOBAL_STORE_DWORD $vgpr10_vgpr11, $vgpr1, 0, 0, implicit $exec
    ; PRERA-NEXT: $vgpr2 = V_MOV_B32_e32 1, implicit $exec
    ; PRERA-NEXT: $vgpr3 = V_MOV_B32_e32 1, implicit $exec
    ; PRERA-NEXT: $vgpr3 = DS_READ_U16_gfx9 $vgpr2, 0, 0, implicit $exec
    ; PRERA-NEXT: $vgpr4 = V_MOV_B32_e32 1, implicit $exec
    ; PRERA-NEXT: $vgpr4 = GLOBAL_LOAD_USHORT $vgpr0_vgpr1, 0, 0, implicit $exec
    ; PRERA-NEXT: $agpr4_agpr5_agpr6_agpr7 = V_MFMA_F32_4X4X1F32_e64 $vgpr3, $vgpr4, $agpr4_agpr5_agpr6_agpr7, 0, 0, 0, implicit $mode, implicit $exec
    ; PRERA-NEXT: $agpr8_agpr9_agpr10_agpr11 = V_MFMA_F32_4X4X1F32_e64 $vgpr3, $vgpr4, $agpr8_agpr9_agpr10_agpr11, 0, 0, 0, implicit $mode, implicit $exec
    ; PRERA-NEXT: $vgpr5 = V_XOR_B32_e32 $vgpr1, $vgpr0, implicit $exec
    ; PRERA-NEXT: $agpr12_agpr13_agpr14_agpr15 = V_MFMA_F32_4X4X1F32_e64 $vgpr1, $vgpr0, $agpr12_agpr13_agpr14_agpr15, 0, 0, 0, implicit $mode, implicit $exec
    ; PRERA-NEXT: $vgpr5 = V_MOV_B32_e32 1, implicit $exec
    ; PRERA-NEXT: $vgpr6 = V_MOV_B32_e32 1, implicit $exec
    ; PRERA-NEXT: $agpr4_agpr5_agpr6_agpr7 = V_MFMA_F32_4X4X1F32_e64 $vgpr5, $vgpr6, $agpr4_agpr5_agpr6_agpr7, 0, 0, 0, implicit $mode, implicit $exec
    ; PRERA-NEXT: $vgpr5 = V_XOR_B32_e32 $vgpr1, $vgpr0, implicit $exec
    ; PRERA-NEXT: $vgpr6 = V_MUL_LO_U32_e64 $vgpr1, $sgpr0, implicit $exec
    ; PRERA-NEXT: $vgpr8 = V_MOV_B32_e32 0, implicit $exec
    ; PRERA-NEXT: $vgpr9 = V_MOV_B32_e32 9, implicit $exec
    ; DEFAULT-LABEL: name: complex_cluster
    ; DEFAULT: liveins: $agpr0_agpr1_agpr2_agpr3, $agpr4_agpr5_agpr6_agpr7, $agpr8_agpr9_agpr10_agpr11, $agpr12_agpr13_agpr14_agpr15, $sgpr0, $vgpr10_vgpr11
    ; DEFAULT-NEXT: {{  $}}
    ; DEFAULT-NEXT: $vgpr1 = V_MOV_B32_e32 1, implicit $exec
    ; DEFAULT-NEXT: $vgpr0 = V_MOV_B32_e32 1, implicit $exec
    ; DEFAULT-NEXT: $agpr0_agpr1_agpr2_agpr3 = V_MFMA_F32_4X4X1F32_e64 $vgpr1, $vgpr0, $agpr0_agpr1_agpr2_agpr3, 0, 0, 0, implicit $mode, implicit $exec
    ; DEFAULT-NEXT: $vgpr1 = V_ADD_F16_e32 $vgpr1, $vgpr0, implicit $mode, implicit $exec
    ; DEFAULT-NEXT: GLOBAL_STORE_DWORD $vgpr10_vgpr11, $vgpr1, 0, 0, implicit $exec
    ; DEFAULT-NEXT: $vgpr2 = V_MOV_B32_e32 1, implicit $exec
    ; DEFAULT-NEXT: $vgpr3 = V_MOV_B32_e32 1, implicit $exec
    ; DEFAULT-NEXT: $vgpr3 = DS_READ_U16_gfx9 $vgpr2, 0, 0, implicit $exec
    ; DEFAULT-NEXT: $agpr12_agpr13_agpr14_agpr15 = V_MFMA_F32_4X4X1F32_e64 $vgpr1, $vgpr0, $agpr12_agpr13_agpr14_agpr15, 0, 0, 0, implicit $mode, implicit $exec
    ; DEFAULT-NEXT: $vgpr4 = V_MOV_B32_e32 1, implicit $exec
    ; DEFAULT-NEXT: $vgpr4 = GLOBAL_LOAD_USHORT $vgpr0_vgpr1, 0, 0, implicit $exec
    ; DEFAULT-NEXT: $agpr4_agpr5_agpr6_agpr7 = V_MFMA_F32_4X4X1F32_e64 $vgpr3, $vgpr4, $agpr4_agpr5_agpr6_agpr7, 0, 0, 0, implicit $mode, implicit $exec
    ; DEFAULT-NEXT: $vgpr5 = V_XOR_B32_e32 $vgpr1, $vgpr0, implicit $exec
    ; DEFAULT-NEXT: $agpr8_agpr9_agpr10_agpr11 = V_MFMA_F32_4X4X1F32_e64 $vgpr3, $vgpr4, $agpr8_agpr9_agpr10_agpr11, 0, 0, 0, implicit $mode, implicit $exec
    ; DEFAULT-NEXT: $vgpr5 = V_MOV_B32_e32 1, implicit $exec
    ; DEFAULT-NEXT: $vgpr6 = V_MOV_B32_e32 1, implicit $exec
    ; DEFAULT-NEXT: $agpr4_agpr5_agpr6_agpr7 = V_MFMA_F32_4X4X1F32_e64 $vgpr5, $vgpr6, $agpr4_agpr5_agpr6_agpr7, 0, 0, 0, implicit $mode, implicit $exec
    ; DEFAULT-NEXT: $vgpr5 = V_XOR_B32_e32 $vgpr1, $vgpr0, implicit $exec
    ; DEFAULT-NEXT: $vgpr6 = V_MUL_LO_U32_e64 $vgpr1, $sgpr0, implicit $exec
    ; DEFAULT-NEXT: $vgpr8 = V_MOV_B32_e32 0, implicit $exec
    ; DEFAULT-NEXT: $vgpr9 = V_MOV_B32_e32 9, implicit $exec
    ; BOTHSCHEDPASS-LABEL: name: complex_cluster
    ; BOTHSCHEDPASS: liveins: $sgpr0, $agpr0_agpr1_agpr2_agpr3, $agpr4_agpr5_agpr6_agpr7, $agpr8_agpr9_agpr10_agpr11, $agpr12_agpr13_agpr14_agpr15, $vgpr10_vgpr11
    ; BOTHSCHEDPASS-NEXT: {{  $}}
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION llvm_def_aspace_cfa <badreg>, 0, 6
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION escape 0x10, 0x10, 0x08, 0x90, 0x3e, 0x93, 0x04, 0x90, 0x3f, 0x93, 0x04
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr0_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr1_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr2_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr3_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr4_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr5_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr6_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr8_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr9_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr0_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr1_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr2_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr3_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr4_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr5_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr6_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr7_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr8_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr9_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr10_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr11_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr12_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr13_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr14_lo16
    ; BOTHSCHEDPASS-NEXT: frame-setup CFI_INSTRUCTION undefined $agpr15_lo16
    ; BOTHSCHEDPASS-NEXT: $vgpr1 = V_MOV_B32_e32 1, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr0 = V_MOV_B32_e32 1, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr2 = V_MOV_B32_e32 1, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr3 = V_MOV_B32_e32 1, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr4 = V_MOV_B32_e32 1, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $agpr0_agpr1_agpr2_agpr3 = V_MFMA_F32_4X4X1F32_e64 $vgpr1, $vgpr0, killed $agpr0_agpr1_agpr2_agpr3, 0, 0, 0, implicit $mode, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr1 = V_ADD_F16_e32 killed $vgpr1, $vgpr0, implicit $mode, implicit $exec
    ; BOTHSCHEDPASS-NEXT: GLOBAL_STORE_DWORD killed $vgpr10_vgpr11, $vgpr1, 0, 0, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr3 = DS_READ_U16_gfx9 killed $vgpr2, 0, 0, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr4 = GLOBAL_LOAD_USHORT $vgpr0_vgpr1, 0, 0, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr5 = V_XOR_B32_e32 $vgpr1, $vgpr0, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr5 = V_MOV_B32_e32 1, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr6 = V_MOV_B32_e32 1, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr8 = V_MOV_B32_e32 0, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr9 = V_MOV_B32_e32 9, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $agpr4_agpr5_agpr6_agpr7 = V_MFMA_F32_4X4X1F32_e64 $vgpr3, $vgpr4, killed $agpr4_agpr5_agpr6_agpr7, 0, 0, 0, implicit $mode, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $agpr8_agpr9_agpr10_agpr11 = V_MFMA_F32_4X4X1F32_e64 killed $vgpr3, killed $vgpr4, killed $agpr8_agpr9_agpr10_agpr11, 0, 0, 0, implicit $mode, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $agpr12_agpr13_agpr14_agpr15 = V_MFMA_F32_4X4X1F32_e64 $vgpr1, $vgpr0, killed $agpr12_agpr13_agpr14_agpr15, 0, 0, 0, implicit $mode, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $agpr4_agpr5_agpr6_agpr7 = V_MFMA_F32_4X4X1F32_e64 killed $vgpr5, killed $vgpr6, killed $agpr4_agpr5_agpr6_agpr7, 0, 0, 0, implicit $mode, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr5 = V_XOR_B32_e32 $vgpr1, killed $vgpr0, implicit $exec
    ; BOTHSCHEDPASS-NEXT: $vgpr6 = V_MUL_LO_U32_e64 killed $vgpr1, killed $sgpr0, implicit $exec
    ; TWOLIMIT-LABEL: name: complex_cluster
    ; TWOLIMIT: liveins: $agpr0_agpr1_agpr2_agpr3, $agpr4_agpr5_agpr6_agpr7, $agpr8_agpr9_agpr10_agpr11, $agpr12_agpr13_agpr14_agpr15, $sgpr0, $vgpr10_vgpr11
    ; TWOLIMIT-NEXT: {{  $}}
    ; TWOLIMIT-NEXT: $vgpr1 = V_MOV_B32_e32 1, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr0 = V_MOV_B32_e32 1, implicit $exec
    ; TWOLIMIT-NEXT: $agpr0_agpr1_agpr2_agpr3 = V_MFMA_F32_4X4X1F32_e64 $vgpr1, $vgpr0, $agpr0_agpr1_agpr2_agpr3, 0, 0, 0, implicit $mode, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr1 = V_ADD_F16_e32 $vgpr1, $vgpr0, implicit $mode, implicit $exec
    ; TWOLIMIT-NEXT: GLOBAL_STORE_DWORD $vgpr10_vgpr11, $vgpr1, 0, 0, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr2 = V_MOV_B32_e32 1, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr3 = V_MOV_B32_e32 1, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr3 = DS_READ_U16_gfx9 $vgpr2, 0, 0, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr4 = V_MOV_B32_e32 1, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr4 = GLOBAL_LOAD_USHORT $vgpr0_vgpr1, 0, 0, implicit $exec
    ; TWOLIMIT-NEXT: $agpr4_agpr5_agpr6_agpr7 = V_MFMA_F32_4X4X1F32_e64 $vgpr3, $vgpr4, $agpr4_agpr5_agpr6_agpr7, 0, 0, 0, implicit $mode, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr5 = V_XOR_B32_e32 $vgpr1, $vgpr0, implicit $exec
    ; TWOLIMIT-NEXT: $agpr8_agpr9_agpr10_agpr11 = V_MFMA_F32_4X4X1F32_e64 $vgpr3, $vgpr4, $agpr8_agpr9_agpr10_agpr11, 0, 0, 0, implicit $mode, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr5 = V_MOV_B32_e32 1, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr6 = V_MOV_B32_e32 1, implicit $exec
    ; TWOLIMIT-NEXT: $agpr4_agpr5_agpr6_agpr7 = V_MFMA_F32_4X4X1F32_e64 $vgpr5, $vgpr6, $agpr4_agpr5_agpr6_agpr7, 0, 0, 0, implicit $mode, implicit $exec
    ; TWOLIMIT-NEXT: $agpr12_agpr13_agpr14_agpr15 = V_MFMA_F32_4X4X1F32_e64 $vgpr1, $vgpr0, $agpr12_agpr13_agpr14_agpr15, 0, 0, 0, implicit $mode, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr5 = V_XOR_B32_e32 $vgpr1, $vgpr0, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr6 = V_MUL_LO_U32_e64 $vgpr1, $sgpr0, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr8 = V_MOV_B32_e32 0, implicit $exec
    ; TWOLIMIT-NEXT: $vgpr9 = V_MOV_B32_e32 9, implicit $exec
    ; POSTRA-LABEL: name: complex_cluster
    ; POSTRA: liveins: $agpr0_agpr1_agpr2_agpr3, $agpr4_agpr5_agpr6_agpr7, $agpr8_agpr9_agpr10_agpr11, $agpr12_agpr13_agpr14_agpr15, $sgpr0, $vgpr10_vgpr11
    ; POSTRA-NEXT: {{  $}}
    ; POSTRA-NEXT: $vgpr1 = V_MOV_B32_e32 1, implicit $exec
    ; POSTRA-NEXT: $vgpr0 = V_MOV_B32_e32 1, implicit $exec
    ; POSTRA-NEXT: $vgpr2 = V_MOV_B32_e32 1, implicit $exec
    ; POSTRA-NEXT: $vgpr3 = V_MOV_B32_e32 1, implicit $exec
    ; POSTRA-NEXT: $vgpr4 = V_MOV_B32_e32 1, implicit $exec
    ; POSTRA-NEXT: $agpr0_agpr1_agpr2_agpr3 = V_MFMA_F32_4X4X1F32_e64 $vgpr1, $vgpr0, killed $agpr0_agpr1_agpr2_agpr3, 0, 0, 0, implicit $mode, implicit $exec
    ; POSTRA-NEXT: $vgpr1 = V_ADD_F16_e32 killed $vgpr1, $vgpr0, implicit $mode, implicit $exec
    ; POSTRA-NEXT: GLOBAL_STORE_DWORD killed $vgpr10_vgpr11, $vgpr1, 0, 0, implicit $exec
    ; POSTRA-NEXT: $vgpr3 = DS_READ_U16_gfx9 killed $vgpr2, 0, 0, implicit $exec
    ; POSTRA-NEXT: $vgpr4 = GLOBAL_LOAD_USHORT $vgpr0_vgpr1, 0, 0, implicit $exec
    ; POSTRA-NEXT: $vgpr5 = V_XOR_B32_e32 $vgpr1, $vgpr0, implicit $exec
    ; POSTRA-NEXT: $vgpr5 = V_MOV_B32_e32 1, implicit $exec
    ; POSTRA-NEXT: $vgpr6 = V_MOV_B32_e32 1, implicit $exec
    ; POSTRA-NEXT: $vgpr8 = V_MOV_B32_e32 0, implicit $exec
    ; POSTRA-NEXT: $vgpr9 = V_MOV_B32_e32 9, implicit $exec
    ; POSTRA-NEXT: $agpr4_agpr5_agpr6_agpr7 = V_MFMA_F32_4X4X1F32_e64 $vgpr3, $vgpr4, killed $agpr4_agpr5_agpr6_agpr7, 0, 0, 0, implicit $mode, implicit $exec
    ; POSTRA-NEXT: $agpr8_agpr9_agpr10_agpr11 = V_MFMA_F32_4X4X1F32_e64 killed $vgpr3, killed $vgpr4, killed $agpr8_agpr9_agpr10_agpr11, 0, 0, 0, implicit $mode, implicit $exec
    ; POSTRA-NEXT: $agpr12_agpr13_agpr14_agpr15 = V_MFMA_F32_4X4X1F32_e64 $vgpr1, $vgpr0, killed $agpr12_agpr13_agpr14_agpr15, 0, 0, 0, implicit $mode, implicit $exec
    ; POSTRA-NEXT: $agpr4_agpr5_agpr6_agpr7 = V_MFMA_F32_4X4X1F32_e64 killed $vgpr5, killed $vgpr6, killed $agpr4_agpr5_agpr6_agpr7, 0, 0, 0, implicit $mode, implicit $exec
    ; POSTRA-NEXT: $vgpr5 = V_XOR_B32_e32 $vgpr1, killed $vgpr0, implicit $exec
    ; POSTRA-NEXT: $vgpr6 = V_MUL_LO_U32_e64 killed $vgpr1, killed $sgpr0, implicit $exec
    $vgpr1 = V_MOV_B32_e32 1, implicit $exec
    $vgpr0 = V_MOV_B32_e32 1, implicit $exec
    $vgpr8 = V_MOV_B32_e32 0, implicit $exec
    $vgpr9 = V_MOV_B32_e32 9, implicit $exec
    $agpr0_agpr1_agpr2_agpr3 = V_MFMA_F32_4X4X1F32_e64 $vgpr1, $vgpr0, $agpr0_agpr1_agpr2_agpr3, 0, 0, 0, implicit $mode, implicit $exec
    $vgpr2 = V_MOV_B32_e32 1, implicit $exec
    $vgpr3 = V_MOV_B32_e32 1, implicit $exec
    $vgpr4 = V_MOV_B32_e32 1, implicit $exec
    $vgpr1 = V_ADD_F16_e32 $vgpr1, $vgpr0, implicit $mode, implicit $exec
    GLOBAL_STORE_DWORD $vgpr10_vgpr11, $vgpr1, 0, 0, implicit $exec
    $vgpr3 = DS_READ_U16_gfx9 $vgpr2, 0, 0, implicit $exec
    $vgpr4 = GLOBAL_LOAD_USHORT $vgpr0_vgpr1, 0, 0, implicit $exec
    $agpr4_agpr5_agpr6_agpr7 = V_MFMA_F32_4X4X1F32_e64 $vgpr3, $vgpr4, $agpr4_agpr5_agpr6_agpr7, 0, 0, 0, implicit $mode, implicit $exec
    $vgpr5 = V_XOR_B32_e32 $vgpr1, $vgpr0, implicit $exec
    $vgpr5 = V_MOV_B32_e32 1, implicit $exec
    $vgpr6 = V_MOV_B32_e32 1, implicit $exec
    $agpr8_agpr9_agpr10_agpr11 = V_MFMA_F32_4X4X1F32_e64 $vgpr3, $vgpr4, $agpr8_agpr9_agpr10_agpr11, 0, 0, 0, implicit $mode, implicit $exec
    $agpr4_agpr5_agpr6_agpr7 = V_MFMA_F32_4X4X1F32_e64 $vgpr5, $vgpr6, $agpr4_agpr5_agpr6_agpr7, 0, 0, 0, implicit $mode, implicit $exec
    $vgpr5 = V_XOR_B32_e32 $vgpr1, $vgpr0, implicit $exec
    $vgpr6 = V_MUL_LO_U32_e64 $vgpr1, $sgpr0, implicit $exec
    $agpr12_agpr13_agpr14_agpr15 = V_MFMA_F32_4X4X1F32_e64 $vgpr1, $vgpr0, $agpr12_agpr13_agpr14_agpr15, 0, 0, 0, implicit $mode, implicit $exec
...
