; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc < %s -mtriple amdgcn | FileCheck %s -check-prefixes=CHECK

declare dso_local void @main()

define dso_local void @naked() naked "frame-pointer"="all" {
; CHECK-LABEL: naked:
; CHECK:       .Lnaked$local:
; CHECK-NEXT:    .type .Lnaked$local,@function
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    s_getpc_b64 s[16:17]
; CHECK-NEXT:    s_add_u32 s16, s16, main@rel32@lo+4
; CHECK-NEXT:    s_addc_u32 s17, s17, main@rel32@hi+12
; CHECK-NEXT:    s_swappc_b64 s[30:31], s[16:17]
  call void @main()
  unreachable
}

define dso_local void @normal() "frame-pointer"="all" {
; CHECK-LABEL: normal:
; CHECK:       .Lnormal$local:
; CHECK-NEXT:    .type .Lnormal$local,@function
; CHECK-NEXT:  ; %bb.0:
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    s_mov_b32 s16, s33
; CHECK-NEXT:    s_mov_b32 s33, s32
; CHECK-NEXT:    s_or_saveexec_b64 s[18:19], -1
; CHECK-NEXT:    buffer_store_dword v40, off, s[0:3], s33 ; 4-byte Folded Spill
; CHECK-NEXT:    s_mov_b64 exec, s[18:19]
; CHECK-NEXT:    s_waitcnt expcnt(0)
; CHECK-NEXT:    v_writelane_b32 v40, s16, 2
; CHECK-NEXT:    s_addk_i32 s32, 0x400
; CHECK-NEXT:    v_writelane_b32 v40, s30, 0
; CHECK-NEXT:    v_writelane_b32 v40, s31, 1
; CHECK-NEXT:    s_getpc_b64 s[16:17]
; CHECK-NEXT:    s_add_u32 s16, s16, main@rel32@lo+4
; CHECK-NEXT:    s_addc_u32 s17, s17, main@rel32@hi+12
; CHECK-NEXT:    s_swappc_b64 s[30:31], s[16:17]
  call void @main()
  unreachable
}
