; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -mtriple=r600-- -passes=amdgpu-printf-runtime-binding -mcpu=r600 -S < %s | FileCheck %s
; RUN: opt -mtriple=amdgcn-- -passes=amdgpu-printf-runtime-binding -mcpu=fiji -S < %s | FileCheck %s
; RUN: opt -mtriple=amdgcn--amdhsa -passes=amdgpu-printf-runtime-binding -mcpu=fiji -S < %s | FileCheck %s

define amdgpu_kernel void @test_kernel(i32 %n) {
; CHECK-LABEL: define amdgpu_kernel void @test_kernel(
; CHECK-SAME: i32 [[N:%.*]]) #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[MEM:%.*]] = alloca float, align 4, addrspace(5)
; CHECK-NEXT:    [[STR:%.*]] = alloca [9 x i8], align 1, addrspace(5)
; CHECK-NEXT:    [[CALL1:%.*]] = call float (i32, ...) @printf(i32 [[N]], ptr addrspace(5) [[STR]], i32 [[N]])
; CHECK-NEXT:    store float [[CALL1]], ptr addrspace(5) [[MEM]], align 4
; CHECK-NEXT:    ret void
;
entry:
  %mem = alloca float, align 4, addrspace(5)
  %str = alloca [9 x i8], align 1, addrspace(5)
  %call1 = call float (i32, ...) @printf(i32 %n, ptr addrspace(5) %str, i32 %n)
  store float %call1, ptr addrspace(5) %mem, align 4
  ret void
}

define float @test_func(i32 %n) {
; CHECK-LABEL: define float @test_func(
; CHECK-SAME: i32 [[N:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[STR:%.*]] = alloca [9 x i8], align 1, addrspace(5)
; CHECK-NEXT:    [[CALL1:%.*]] = call float (i32, ...) @printf(i32 [[N]], ptr addrspace(5) [[STR]], i32 [[N]])
; CHECK-NEXT:    ret float [[CALL1]]
;
entry:
  %str = alloca [9 x i8], align 1, addrspace(5)
  %call1 = call float (i32, ...) @printf(i32 %n, ptr addrspace(5) %str, i32 %n)
  ret float %call1
}

declare float @printf(i32, ...)
