# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -march=amdgcn -mcpu=fiji -verify-machineinstrs -run-pass=si-optimize-exec-masking -o - %s | FileCheck %s

# There are multiple _term pseudos here. Starting from the end of the
# block, they all need to be converted to regular copies removed in
# order to avoid making the verifier unhappy.

---
name:  multi_term_pseudos
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: multi_term_pseudos
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT:   liveins: $sgpr4_sgpr5, $sgpr6_sgpr7, $sgpr8_sgpr9
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $exec = PRED_COPY killed renamable $sgpr4_sgpr5
  ; CHECK-NEXT:   renamable $sgpr10_sgpr11 = PRED_COPY killed renamable $sgpr6_sgpr7, implicit $exec
  ; CHECK-NEXT:   renamable $sgpr12_sgpr13 = PRED_COPY killed renamable $sgpr8_sgpr9, implicit $exec
  ; CHECK-NEXT:   S_CBRANCH_EXECZ %bb.1, implicit $exec
  ; CHECK-NEXT:   S_BRANCH %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $sgpr12_sgpr13
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   S_ENDPGM 0, implicit $sgpr12_sgpr13
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   liveins: $sgpr12_sgpr13
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   S_ENDPGM 0, implicit $sgpr12_sgpr13
  bb.0:
    successors: %bb.2(0x40000000), %bb.1(0x40000000)
    liveins: $sgpr4_sgpr5, $sgpr6_sgpr7, $sgpr8_sgpr9
    $exec = S_MOV_B64_term killed renamable $sgpr4_sgpr5
    renamable $sgpr10_sgpr11 = S_MOV_B64_term killed renamable $sgpr6_sgpr7, implicit $exec
    renamable $sgpr12_sgpr13 = S_MOV_B64_term killed renamable $sgpr8_sgpr9, implicit $exec
    S_CBRANCH_EXECZ %bb.1, implicit $exec
    S_BRANCH %bb.2

  bb.1:
    liveins: $sgpr12_sgpr13
    S_ENDPGM 0, implicit $sgpr12_sgpr13

  bb.2:
    liveins: $sgpr12_sgpr13
    S_ENDPGM 0, implicit $sgpr12_sgpr13

...
