# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -march=amdgcn -mcpu=fiji -verify-machineinstrs -run-pass=si-optimize-exec-masking -o - %s | FileCheck %s

# Make sure we can still optimize writes to exec when there are
# additional terminators after the exec write. This can happen with
# phi users of control flow intrinsics.

---
name: instructions_after_copy_to_exec
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: instructions_after_copy_to_exec
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; CHECK-NEXT:   liveins: $vgpr0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $vgpr1 = V_MOV_B32_e32 0, implicit $exec
  ; CHECK-NEXT:   renamable $vcc = V_CMP_EQ_U32_e64 0, killed $vgpr0, implicit $exec
  ; CHECK-NEXT:   $sgpr0_sgpr1 = S_AND_SAVEEXEC_B64 $vcc, implicit-def $exec, implicit-def $scc, implicit $exec
  ; CHECK-NEXT:   renamable $sgpr0_sgpr1 = S_XOR_B64 $exec, killed renamable $sgpr0_sgpr1, implicit-def dead $scc
  ; CHECK-NEXT:   renamable $sgpr0_sgpr1 = PRED_COPY killed renamable $sgpr0_sgpr1, implicit $exec
  ; CHECK-NEXT:   S_CBRANCH_EXECZ %bb.2, implicit $exec
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT:   liveins: $sgpr0_sgpr1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   S_NOP 0, implicit $sgpr0_sgpr1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   liveins: $sgpr0_sgpr1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   S_NOP 0, implicit $sgpr0_sgpr1
  bb.0:
    liveins: $vgpr0

    renamable $vgpr1 = V_MOV_B32_e32 0, implicit $exec
    renamable $vcc = V_CMP_EQ_U32_e64 0, killed $vgpr0, implicit $exec
    renamable $sgpr0_sgpr1 = COPY $exec, implicit-def $exec
    renamable $sgpr2_sgpr3 = S_AND_B64 renamable $sgpr0_sgpr1, renamable $vcc, implicit-def dead $scc
    renamable $sgpr0_sgpr1 = S_XOR_B64 renamable $sgpr2_sgpr3, killed renamable $sgpr0_sgpr1, implicit-def dead $scc
    $exec = S_MOV_B64_term killed renamable $sgpr2_sgpr3
    renamable $sgpr0_sgpr1 = S_MOV_B64_term killed renamable $sgpr0_sgpr1, implicit $exec
    S_CBRANCH_EXECZ %bb.2, implicit $exec

  bb.1:
    liveins: $sgpr0_sgpr1

    S_NOP 0, implicit $sgpr0_sgpr1

  bb.2:
    liveins: $sgpr0_sgpr1

    S_NOP 0, implicit $sgpr0_sgpr1

...
