; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel -new-reg-bank-select -O0 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1031 < %s | FileCheck %s

; Testcase which happened to trigger a liveness verifier error
define amdgpu_kernel void @test_long_add4(<4 x i64> %arg) #0 {
; CHECK-LABEL: test_long_add4:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_mov_b64 s[6:7], 0
; CHECK-NEXT:    v_mov_b32_e32 v0, s6
; CHECK-NEXT:    v_mov_b32_e32 v1, s7
; CHECK-NEXT:    global_load_dwordx4 v[2:5], v[0:1], off
; CHECK-NEXT:    s_mov_b64 s[4:5], 16
; CHECK-NEXT:    v_mov_b32_e32 v0, s4
; CHECK-NEXT:    v_mov_b32_e32 v1, s5
; CHECK-NEXT:    global_load_dwordx4 v[10:13], v[0:1], off
; CHECK-NEXT:    ; kill: def $vgpr2_vgpr3_vgpr4_vgpr5 killed $vgpr2_vgpr3_vgpr4_vgpr5 def $vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9 killed $exec
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v6, v10
; CHECK-NEXT:    v_mov_b32_e32 v7, v11
; CHECK-NEXT:    v_mov_b32_e32 v8, v12
; CHECK-NEXT:    v_mov_b32_e32 v9, v13
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v0, v3
; CHECK-NEXT:    v_readfirstlane_b32 s12, v1
; CHECK-NEXT:    v_readfirstlane_b32 s13, v0
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_mov_b32_e32 v0, v5
; CHECK-NEXT:    v_readfirstlane_b32 s10, v1
; CHECK-NEXT:    v_readfirstlane_b32 s11, v0
; CHECK-NEXT:    v_mov_b32_e32 v1, v6
; CHECK-NEXT:    v_mov_b32_e32 v0, v7
; CHECK-NEXT:    v_readfirstlane_b32 s8, v1
; CHECK-NEXT:    v_readfirstlane_b32 s9, v0
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_mov_b32_e32 v0, v9
; CHECK-NEXT:    v_readfirstlane_b32 s16, v1
; CHECK-NEXT:    v_readfirstlane_b32 s14, v0
; CHECK-NEXT:    v_mov_b32_e32 v0, s6
; CHECK-NEXT:    v_mov_b32_e32 v1, s7
; CHECK-NEXT:    global_load_dwordx4 v[2:5], v[0:1], off
; CHECK-NEXT:    v_mov_b32_e32 v0, s4
; CHECK-NEXT:    v_mov_b32_e32 v1, s5
; CHECK-NEXT:    global_load_dwordx4 v[10:13], v[0:1], off
; CHECK-NEXT:    ; kill: def $vgpr2_vgpr3_vgpr4_vgpr5 killed $vgpr2_vgpr3_vgpr4_vgpr5 def $vgpr2_vgpr3_vgpr4_vgpr5_vgpr6_vgpr7_vgpr8_vgpr9 killed $exec
; CHECK-NEXT:    s_waitcnt vmcnt(0)
; CHECK-NEXT:    v_mov_b32_e32 v6, v10
; CHECK-NEXT:    v_mov_b32_e32 v7, v11
; CHECK-NEXT:    v_mov_b32_e32 v8, v12
; CHECK-NEXT:    v_mov_b32_e32 v9, v13
; CHECK-NEXT:    v_mov_b32_e32 v1, v2
; CHECK-NEXT:    v_mov_b32_e32 v0, v3
; CHECK-NEXT:    v_readfirstlane_b32 s23, v1
; CHECK-NEXT:    v_readfirstlane_b32 s22, v0
; CHECK-NEXT:    v_mov_b32_e32 v1, v4
; CHECK-NEXT:    v_mov_b32_e32 v0, v5
; CHECK-NEXT:    v_readfirstlane_b32 s21, v1
; CHECK-NEXT:    v_readfirstlane_b32 s20, v0
; CHECK-NEXT:    v_mov_b32_e32 v1, v6
; CHECK-NEXT:    v_mov_b32_e32 v0, v7
; CHECK-NEXT:    v_readfirstlane_b32 s19, v1
; CHECK-NEXT:    v_readfirstlane_b32 s18, v0
; CHECK-NEXT:    v_mov_b32_e32 v1, v8
; CHECK-NEXT:    v_mov_b32_e32 v0, v9
; CHECK-NEXT:    v_readfirstlane_b32 s17, v1
; CHECK-NEXT:    v_readfirstlane_b32 s15, v0
; CHECK-NEXT:    s_add_u32 s12, s12, s23
; CHECK-NEXT:    s_cselect_b32 s23, 1, 0
; CHECK-NEXT:    s_cmp_lg_u32 s23, 0
; CHECK-NEXT:    s_addc_u32 s22, s13, s22
; CHECK-NEXT:    ; kill: def $sgpr12 killed $sgpr12 def $sgpr12_sgpr13
; CHECK-NEXT:    s_mov_b32 s13, s22
; CHECK-NEXT:    s_add_u32 s10, s10, s21
; CHECK-NEXT:    s_cselect_b32 s21, 1, 0
; CHECK-NEXT:    s_cmp_lg_u32 s21, 0
; CHECK-NEXT:    s_addc_u32 s20, s11, s20
; CHECK-NEXT:    ; kill: def $sgpr10 killed $sgpr10 def $sgpr10_sgpr11
; CHECK-NEXT:    s_mov_b32 s11, s20
; CHECK-NEXT:    s_add_u32 s8, s8, s19
; CHECK-NEXT:    s_cselect_b32 s19, 1, 0
; CHECK-NEXT:    s_cmp_lg_u32 s19, 0
; CHECK-NEXT:    s_addc_u32 s18, s9, s18
; CHECK-NEXT:    ; kill: def $sgpr8 killed $sgpr8 def $sgpr8_sgpr9
; CHECK-NEXT:    s_mov_b32 s9, s18
; CHECK-NEXT:    s_add_u32 s16, s16, s17
; CHECK-NEXT:    s_cselect_b32 s17, 1, 0
; CHECK-NEXT:    s_cmp_lg_u32 s17, 0
; CHECK-NEXT:    s_addc_u32 s14, s14, s15
; CHECK-NEXT:    ; kill: def $sgpr16 killed $sgpr16 def $sgpr16_sgpr17
; CHECK-NEXT:    s_mov_b32 s17, s14
; CHECK-NEXT:    ; kill: def $sgpr12_sgpr13 killed $sgpr12_sgpr13 def $sgpr12_sgpr13_sgpr14_sgpr15
; CHECK-NEXT:    s_mov_b64 s[14:15], s[10:11]
; CHECK-NEXT:    ; kill: def $sgpr8_sgpr9 killed $sgpr8_sgpr9 def $sgpr8_sgpr9_sgpr10_sgpr11
; CHECK-NEXT:    s_mov_b64 s[10:11], s[16:17]
; CHECK-NEXT:    v_mov_b32_e32 v2, s12
; CHECK-NEXT:    v_mov_b32_e32 v3, s13
; CHECK-NEXT:    v_mov_b32_e32 v4, s14
; CHECK-NEXT:    v_mov_b32_e32 v5, s15
; CHECK-NEXT:    v_mov_b32_e32 v0, s6
; CHECK-NEXT:    v_mov_b32_e32 v1, s7
; CHECK-NEXT:    global_store_dwordx4 v[0:1], v[2:5], off
; CHECK-NEXT:    v_mov_b32_e32 v2, s8
; CHECK-NEXT:    v_mov_b32_e32 v3, s9
; CHECK-NEXT:    v_mov_b32_e32 v4, s10
; CHECK-NEXT:    v_mov_b32_e32 v5, s11
; CHECK-NEXT:    v_mov_b32_e32 v0, s4
; CHECK-NEXT:    v_mov_b32_e32 v1, s5
; CHECK-NEXT:    global_store_dwordx4 v[0:1], v[2:5], off
; CHECK-NEXT:    s_endpgm
entry:
  %load0 = load <4 x i64>, ptr addrspace(1) null, align 32
  %load1 = load <4 x i64>, ptr addrspace(1) null, align 32
  %add = add <4 x i64> %load0, %load1
  store <4 x i64> %add, ptr addrspace(1) null, align 32
  ret void
}

attributes #0 = { noinline optnone }
