# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -mtriple=amdgcn -mcpu=gfx942 -run-pass si-peephole-sdwa,dead-mi-elimination -o - %s | FileCheck -check-prefixes=GFX9 %s

--- |
  source_filename = "/home/vikashgu/work/upstream/llvm-project/llvm/test/CodeGen/AMDGPU/vector-fp16.ll"
  target datalayout = "e-p:64:64-p1:64:64-p2:32:32-p3:32:32-p4:64:64-p5:32:32-p6:32:32-p7:160:256:256:32-p8:128:128-p9:192:256:256:32-i64:64-v16:16-v24:32-v32:32-v48:64-v96:128-v192:256-v256:256-v512:512-v1024:1024-v2048:2048-n32:64-S32-A5-G1-ni:7:8:9"
  target triple = "amdgcn-amd-amdhsa"

  define <4 x half> @sin_v4f16(<4 x half> %a) #0 {
    %res = call <4 x half> @llvm.sin.v4f16(<4 x half> %a)
    ret <4 x half> %res
  }

  define <4 x half> @cos_v4f16(<4 x half> %a) #0 {
    %res = call <4 x half> @llvm.cos.v4f16(<4 x half> %a)
    ret <4 x half> %res
  }

  define <4 x half> @log_v4f16(<4 x half> %a) #0 {
    %res = call <4 x half> @llvm.log.v4f16(<4 x half> %a)
    ret <4 x half> %res
  }

  define <4 x half> @log2_v4f16(<4 x half> %a) #0 {
    %res = call <4 x half> @llvm.log2.v4f16(<4 x half> %a)
    ret <4 x half> %res
  }

  define <4 x half> @exp_v4f16(<4 x half> %a) #0 {
    %res = call <4 x half> @llvm.exp.v4f16(<4 x half> %a)
    ret <4 x half> %res
  }

  define <4 x half> @cascaded_v4f16(<4 x half> %a) #0 {
    %b = call <4 x half> @llvm.log2.v4f16(<4 x half> %a)
    %res = call <4 x half> @llvm.sin.v4f16(<4 x half> %b)
    ret <4 x half> %res
  }

  define void @unbalanced_operations_packed(<4 x half> %a) #0 {
    ret void
  }

  declare <4 x half> @llvm.cos.v4f16(<4 x half>) #1

  declare <4 x half> @llvm.exp.v4f16(<4 x half>) #1

  declare <4 x half> @llvm.log.v4f16(<4 x half>) #1

  declare <4 x half> @llvm.log2.v4f16(<4 x half>) #1

  declare <4 x half> @llvm.sin.v4f16(<4 x half>) #1

  attributes #0 = { "target-cpu"="gfx942" }
  attributes #1 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) "target-cpu"="gfx942" }
...


---
name:            sin_v4f16
tracksRegLiveness: true
body:             |
  bb.0 (%ir-block.0):
    liveins: $vgpr0, $vgpr1

    ; GFX9-LABEL: name: sin_v4f16
    ; GFX9: liveins: $vgpr0, $vgpr1
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
    ; GFX9-NEXT: [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX9-NEXT: [[V_MOV_B32_e32_:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 12568, implicit $exec
    ; GFX9-NEXT: [[V_MUL_F16_sdwa:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F16_sdwa 0, [[COPY]], 0, [[V_MOV_B32_e32_]], 0, 0, 4, 2, 4, 6, implicit $mode, implicit $exec, implicit [[COPY]](tied-def 0)
    ; GFX9-NEXT: [[V_SIN_F16_sdwa:%[0-9]+]]:vgpr_32 = nofpexcept V_SIN_F16_sdwa 0, killed [[V_MUL_F16_sdwa]], 0, 0, 4, 2, 4, implicit $mode, implicit $exec, implicit killed [[V_MUL_F16_sdwa]](tied-def 0)
    ; GFX9-NEXT: [[V_MOV_B32_e32_1:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 12568, implicit $exec
    ; GFX9-NEXT: [[V_MUL_F16_sdwa1:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F16_sdwa 0, [[V_SIN_F16_sdwa]], 0, [[V_MOV_B32_e32_1]], 0, 0, 5, 2, 5, 6, implicit $mode, implicit $exec, implicit [[V_SIN_F16_sdwa]](tied-def 0)
    ; GFX9-NEXT: [[V_SIN_F16_sdwa1:%[0-9]+]]:vgpr_32 = nofpexcept V_SIN_F16_sdwa 0, killed [[V_MUL_F16_sdwa1]], 0, 0, 5, 2, 5, implicit $mode, implicit $exec, implicit killed [[V_MUL_F16_sdwa1]](tied-def 0)
    ; GFX9-NEXT: [[V_MOV_B32_e32_2:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 12568, implicit $exec
    ; GFX9-NEXT: [[V_MUL_F16_sdwa2:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F16_sdwa 0, [[COPY1]], 0, [[V_MOV_B32_e32_2]], 0, 0, 4, 2, 4, 6, implicit $mode, implicit $exec, implicit [[COPY1]](tied-def 0)
    ; GFX9-NEXT: [[V_SIN_F16_sdwa2:%[0-9]+]]:vgpr_32 = nofpexcept V_SIN_F16_sdwa 0, killed [[V_MUL_F16_sdwa2]], 0, 0, 4, 2, 4, implicit $mode, implicit $exec, implicit killed [[V_MUL_F16_sdwa2]](tied-def 0)
    ; GFX9-NEXT: [[V_MOV_B32_e32_3:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 12568, implicit $exec
    ; GFX9-NEXT: [[V_MUL_F16_sdwa3:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F16_sdwa 0, [[V_SIN_F16_sdwa2]], 0, [[V_MOV_B32_e32_3]], 0, 0, 5, 2, 5, 6, implicit $mode, implicit $exec, implicit [[V_SIN_F16_sdwa2]](tied-def 0)
    ; GFX9-NEXT: [[V_SIN_F16_sdwa3:%[0-9]+]]:vgpr_32 = nofpexcept V_SIN_F16_sdwa 0, killed [[V_MUL_F16_sdwa3]], 0, 0, 5, 2, 5, implicit $mode, implicit $exec, implicit killed [[V_MUL_F16_sdwa3]](tied-def 0)
    ; GFX9-NEXT: $vgpr0 = COPY [[V_SIN_F16_sdwa3]]
    ; GFX9-NEXT: $vgpr1 = COPY [[V_SIN_F16_sdwa1]]
    ; GFX9-NEXT: SI_RETURN implicit $vgpr0, implicit $vgpr1
    %9:vgpr_32 = COPY $vgpr1
    %8:vgpr_32 = COPY $vgpr0
    %12:vgpr_32 = nofpexcept V_MUL_F16_e64 0, %9, 0, 12568, 0, 0, implicit $mode, implicit $exec
    %13:vgpr_32 = nofpexcept V_SIN_F16_e64 0, killed %12, 0, 0, implicit $mode, implicit $exec
    %15:vgpr_32 = V_LSHRREV_B32_e64 16, %9, implicit $exec
    %17:vgpr_32 = nofpexcept V_MUL_F16_e64 0, %15, 0, 12568, 0, 0, implicit $mode, implicit $exec
    %18:vgpr_32 = nofpexcept V_SIN_F16_e64 0, killed %17, 0, 0, implicit $mode, implicit $exec
    %20:vgpr_32 = nofpexcept V_MUL_F16_e64 0, %8, 0, 12568, 0, 0, implicit $mode, implicit $exec
    %21:vgpr_32 = nofpexcept V_SIN_F16_e64 0, killed %20, 0, 0, implicit $mode, implicit $exec
    %22:vgpr_32 = V_LSHRREV_B32_e64 16, %8, implicit $exec
    %24:vgpr_32 = nofpexcept V_MUL_F16_e64 0, %22, 0, 12568, 0, 0, implicit $mode, implicit $exec
    %25:vgpr_32 = nofpexcept V_SIN_F16_e64 0, killed %24, 0, 0, implicit $mode, implicit $exec
    %26:vgpr_32 = nofpexcept V_PACK_B32_F16_e64 0, killed %21, 0, killed %25, 0, 0, implicit $mode, implicit $exec
    %27:vgpr_32 = nofpexcept V_PACK_B32_F16_e64 0, killed %13, 0, killed %18, 0, 0, implicit $mode, implicit $exec
    $vgpr0 = COPY %26
    $vgpr1 = COPY %27
    SI_RETURN implicit $vgpr0, implicit $vgpr1
...

---
name:            cos_v4f16
tracksRegLiveness: true
body:             |
  bb.0 (%ir-block.0):
    liveins: $vgpr0, $vgpr1

    ; GFX9-LABEL: name: cos_v4f16
    ; GFX9: liveins: $vgpr0, $vgpr1
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
    ; GFX9-NEXT: [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX9-NEXT: [[V_MOV_B32_e32_:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 12568, implicit $exec
    ; GFX9-NEXT: [[V_MUL_F16_sdwa:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F16_sdwa 0, [[COPY]], 0, [[V_MOV_B32_e32_]], 0, 0, 4, 2, 4, 6, implicit $mode, implicit $exec, implicit [[COPY]](tied-def 0)
    ; GFX9-NEXT: [[V_COS_F16_sdwa:%[0-9]+]]:vgpr_32 = nofpexcept V_COS_F16_sdwa 0, killed [[V_MUL_F16_sdwa]], 0, 0, 4, 2, 4, implicit $mode, implicit $exec, implicit killed [[V_MUL_F16_sdwa]](tied-def 0)
    ; GFX9-NEXT: [[V_MOV_B32_e32_1:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 12568, implicit $exec
    ; GFX9-NEXT: [[V_MUL_F16_sdwa1:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F16_sdwa 0, [[V_COS_F16_sdwa]], 0, [[V_MOV_B32_e32_1]], 0, 0, 5, 2, 5, 6, implicit $mode, implicit $exec, implicit [[V_COS_F16_sdwa]](tied-def 0)
    ; GFX9-NEXT: [[V_COS_F16_sdwa1:%[0-9]+]]:vgpr_32 = nofpexcept V_COS_F16_sdwa 0, killed [[V_MUL_F16_sdwa1]], 0, 0, 5, 2, 5, implicit $mode, implicit $exec, implicit killed [[V_MUL_F16_sdwa1]](tied-def 0)
    ; GFX9-NEXT: [[V_MOV_B32_e32_2:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 12568, implicit $exec
    ; GFX9-NEXT: [[V_MUL_F16_sdwa2:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F16_sdwa 0, [[COPY1]], 0, [[V_MOV_B32_e32_2]], 0, 0, 4, 2, 4, 6, implicit $mode, implicit $exec, implicit [[COPY1]](tied-def 0)
    ; GFX9-NEXT: [[V_COS_F16_sdwa2:%[0-9]+]]:vgpr_32 = nofpexcept V_COS_F16_sdwa 0, killed [[V_MUL_F16_sdwa2]], 0, 0, 4, 2, 4, implicit $mode, implicit $exec, implicit killed [[V_MUL_F16_sdwa2]](tied-def 0)
    ; GFX9-NEXT: [[V_MOV_B32_e32_3:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 12568, implicit $exec
    ; GFX9-NEXT: [[V_MUL_F16_sdwa3:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F16_sdwa 0, [[V_COS_F16_sdwa2]], 0, [[V_MOV_B32_e32_3]], 0, 0, 5, 2, 5, 6, implicit $mode, implicit $exec, implicit [[V_COS_F16_sdwa2]](tied-def 0)
    ; GFX9-NEXT: [[V_COS_F16_sdwa3:%[0-9]+]]:vgpr_32 = nofpexcept V_COS_F16_sdwa 0, killed [[V_MUL_F16_sdwa3]], 0, 0, 5, 2, 5, implicit $mode, implicit $exec, implicit killed [[V_MUL_F16_sdwa3]](tied-def 0)
    ; GFX9-NEXT: $vgpr0 = COPY [[V_COS_F16_sdwa3]]
    ; GFX9-NEXT: $vgpr1 = COPY [[V_COS_F16_sdwa1]]
    ; GFX9-NEXT: SI_RETURN implicit $vgpr0, implicit $vgpr1
    %9:vgpr_32 = COPY $vgpr1
    %8:vgpr_32 = COPY $vgpr0
    %12:vgpr_32 = nofpexcept V_MUL_F16_e64 0, %9, 0, 12568, 0, 0, implicit $mode, implicit $exec
    %13:vgpr_32 = nofpexcept V_COS_F16_e64 0, killed %12, 0, 0, implicit $mode, implicit $exec
    %15:vgpr_32 = V_LSHRREV_B32_e64 16, %9, implicit $exec
    %17:vgpr_32 = nofpexcept V_MUL_F16_e64 0, %15, 0, 12568, 0, 0, implicit $mode, implicit $exec
    %18:vgpr_32 = nofpexcept V_COS_F16_e64 0, killed %17, 0, 0, implicit $mode, implicit $exec
    %20:vgpr_32 = nofpexcept V_MUL_F16_e64 0, %8, 0, 12568, 0, 0, implicit $mode, implicit $exec
    %21:vgpr_32 = nofpexcept V_COS_F16_e64 0, killed %20, 0, 0, implicit $mode, implicit $exec
    %22:vgpr_32 = V_LSHRREV_B32_e64 16, %8, implicit $exec
    %24:vgpr_32 = nofpexcept V_MUL_F16_e64 0, %22, 0, 12568, 0, 0, implicit $mode, implicit $exec
    %25:vgpr_32 = nofpexcept V_COS_F16_e64 0, killed %24, 0, 0, implicit $mode, implicit $exec
    %26:vgpr_32 = nofpexcept V_PACK_B32_F16_e64 0, killed %21, 0, killed %25, 0, 0, implicit $mode, implicit $exec
    %27:vgpr_32 = nofpexcept V_PACK_B32_F16_e64 0, killed %13, 0, killed %18, 0, 0, implicit $mode, implicit $exec
    $vgpr0 = COPY %26
    $vgpr1 = COPY %27
    SI_RETURN implicit $vgpr0, implicit $vgpr1
...

---
name:            log_v4f16
tracksRegLiveness: true
body:             |
  bb.0 (%ir-block.0):
    liveins: $vgpr0, $vgpr1

    ; GFX9-LABEL: name: log_v4f16
    ; GFX9: liveins: $vgpr0, $vgpr1
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
    ; GFX9-NEXT: [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX9-NEXT: [[V_LOG_F16_sdwa:%[0-9]+]]:vgpr_32 = nofpexcept V_LOG_F16_sdwa 0, [[COPY]], 0, 0, 4, 2, 4, implicit $mode, implicit $exec, implicit [[COPY]](tied-def 0)
    ; GFX9-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 14732
    ; GFX9-NEXT: [[V_MUL_F16_sdwa:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F16_sdwa 0, killed [[V_LOG_F16_sdwa]], 0, [[S_MOV_B32_]], 0, 0, 4, 2, 4, 6, implicit $mode, implicit $exec, implicit killed [[V_LOG_F16_sdwa]](tied-def 0)
    ; GFX9-NEXT: [[V_LOG_F16_sdwa1:%[0-9]+]]:vgpr_32 = nofpexcept V_LOG_F16_sdwa 0, [[V_MUL_F16_sdwa]], 0, 0, 5, 2, 5, implicit $mode, implicit $exec, implicit [[V_MUL_F16_sdwa]](tied-def 0)
    ; GFX9-NEXT: [[V_MUL_F16_sdwa1:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F16_sdwa 0, killed [[V_LOG_F16_sdwa1]], 0, [[S_MOV_B32_]], 0, 0, 5, 2, 5, 6, implicit $mode, implicit $exec, implicit killed [[V_LOG_F16_sdwa1]](tied-def 0)
    ; GFX9-NEXT: [[V_LOG_F16_sdwa2:%[0-9]+]]:vgpr_32 = nofpexcept V_LOG_F16_sdwa 0, [[COPY1]], 0, 0, 4, 2, 4, implicit $mode, implicit $exec, implicit [[COPY1]](tied-def 0)
    ; GFX9-NEXT: [[V_MUL_F16_sdwa2:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F16_sdwa 0, killed [[V_LOG_F16_sdwa2]], 0, [[S_MOV_B32_]], 0, 0, 4, 2, 4, 6, implicit $mode, implicit $exec, implicit killed [[V_LOG_F16_sdwa2]](tied-def 0)
    ; GFX9-NEXT: [[V_LOG_F16_sdwa3:%[0-9]+]]:vgpr_32 = nofpexcept V_LOG_F16_sdwa 0, [[V_MUL_F16_sdwa2]], 0, 0, 5, 2, 5, implicit $mode, implicit $exec, implicit [[V_MUL_F16_sdwa2]](tied-def 0)
    ; GFX9-NEXT: [[V_MUL_F16_sdwa3:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F16_sdwa 0, killed [[V_LOG_F16_sdwa3]], 0, [[S_MOV_B32_]], 0, 0, 5, 2, 5, 6, implicit $mode, implicit $exec, implicit killed [[V_LOG_F16_sdwa3]](tied-def 0)
    ; GFX9-NEXT: $vgpr0 = COPY [[V_MUL_F16_sdwa3]]
    ; GFX9-NEXT: $vgpr1 = COPY [[V_MUL_F16_sdwa1]]
    ; GFX9-NEXT: SI_RETURN implicit $vgpr0, implicit $vgpr1
    %9:vgpr_32 = COPY $vgpr1
    %8:vgpr_32 = COPY $vgpr0
    %11:vgpr_32 = nofpexcept V_LOG_F16_e64 0, %9, 0, 0, implicit $mode, implicit $exec
    %12:sreg_32 = S_MOV_B32 14732
    %13:vgpr_32 = nofpexcept V_MUL_F16_e64 0, killed %11, 0, %12, 0, 0, implicit $mode, implicit $exec
    %15:vgpr_32 = V_LSHRREV_B32_e64 16, %9, implicit $exec
    %17:vgpr_32 = nofpexcept V_LOG_F16_e64 0, %15, 0, 0, implicit $mode, implicit $exec
    %18:vgpr_32 = nofpexcept V_MUL_F16_e64 0, killed %17, 0, %12, 0, 0, implicit $mode, implicit $exec
    %20:vgpr_32 = nofpexcept V_LOG_F16_e64 0, %8, 0, 0, implicit $mode, implicit $exec
    %21:vgpr_32 = nofpexcept V_MUL_F16_e64 0, killed %20, 0, %12, 0, 0, implicit $mode, implicit $exec
    %22:vgpr_32 = V_LSHRREV_B32_e64 16, %8, implicit $exec
    %24:vgpr_32 = nofpexcept V_LOG_F16_e64 0, %22, 0, 0, implicit $mode, implicit $exec
    %25:vgpr_32 = nofpexcept V_MUL_F16_e64 0, killed %24, 0, %12, 0, 0, implicit $mode, implicit $exec
    %26:vgpr_32 = nofpexcept V_PACK_B32_F16_e64 0, killed %21, 0, killed %25, 0, 0, implicit $mode, implicit $exec
    %27:vgpr_32 = nofpexcept V_PACK_B32_F16_e64 0, killed %13, 0, killed %18, 0, 0, implicit $mode, implicit $exec
    $vgpr0 = COPY %26
    $vgpr1 = COPY %27
    SI_RETURN implicit $vgpr0, implicit $vgpr1
...

---
name:            log2_v4f16
tracksRegLiveness: true
body:             |
  bb.0 (%ir-block.0):
    liveins: $vgpr0, $vgpr1

    ; GFX9-LABEL: name: log2_v4f16
    ; GFX9: liveins: $vgpr0, $vgpr1
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
    ; GFX9-NEXT: [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX9-NEXT: [[V_LOG_F16_sdwa:%[0-9]+]]:vgpr_32 = nofpexcept V_LOG_F16_sdwa 0, [[COPY]], 0, 0, 5, 2, 5, implicit $mode, implicit $exec, implicit [[COPY]](tied-def 0)
    ; GFX9-NEXT: [[V_LOG_F16_sdwa1:%[0-9]+]]:vgpr_32 = nofpexcept V_LOG_F16_sdwa 0, [[COPY1]], 0, 0, 5, 2, 5, implicit $mode, implicit $exec, implicit [[COPY1]](tied-def 0)
    ; GFX9-NEXT: [[V_LOG_F16_sdwa2:%[0-9]+]]:vgpr_32 = nofpexcept V_LOG_F16_sdwa 0, [[V_LOG_F16_sdwa]], 0, 0, 4, 2, 4, implicit $mode, implicit $exec, implicit [[V_LOG_F16_sdwa]](tied-def 0)
    ; GFX9-NEXT: [[V_LOG_F16_sdwa3:%[0-9]+]]:vgpr_32 = nofpexcept V_LOG_F16_sdwa 0, [[V_LOG_F16_sdwa1]], 0, 0, 4, 2, 4, implicit $mode, implicit $exec, implicit [[V_LOG_F16_sdwa1]](tied-def 0)
    ; GFX9-NEXT: $vgpr0 = COPY [[V_LOG_F16_sdwa3]]
    ; GFX9-NEXT: $vgpr1 = COPY [[V_LOG_F16_sdwa2]]
    ; GFX9-NEXT: SI_RETURN implicit $vgpr0, implicit $vgpr1
    %9:vgpr_32 = COPY $vgpr1
    %8:vgpr_32 = COPY $vgpr0
    %11:vgpr_32 = V_LSHRREV_B32_e64 16, %9, implicit $exec
    %13:vgpr_32 = nofpexcept V_LOG_F16_e64 0, %11, 0, 0, implicit $mode, implicit $exec
    %14:vgpr_32 = V_LSHRREV_B32_e64 16, %8, implicit $exec
    %16:vgpr_32 = nofpexcept V_LOG_F16_e64 0, %14, 0, 0, implicit $mode, implicit $exec
    %18:vgpr_32 = nofpexcept V_LOG_F16_e64 0, %9, 0, 0, implicit $mode, implicit $exec
    %20:vgpr_32 = nofpexcept V_LOG_F16_e64 0, %8, 0, 0, implicit $mode, implicit $exec
    %21:vgpr_32 = nofpexcept V_PACK_B32_F16_e64 0, killed %20, 0, killed %16, 0, 0, implicit $mode, implicit $exec
    %22:vgpr_32 = nofpexcept V_PACK_B32_F16_e64 0, killed %18, 0, killed %13, 0, 0, implicit $mode, implicit $exec
    $vgpr0 = COPY %21
    $vgpr1 = COPY %22
    SI_RETURN implicit $vgpr0, implicit $vgpr1
...

---
name:            exp_v4f16
tracksRegLiveness: true
body:             |
  bb.0 (%ir-block.0):
    liveins: $vgpr0, $vgpr1

    ; GFX9-LABEL: name: exp_v4f16
    ; GFX9: liveins: $vgpr0, $vgpr1
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
    ; GFX9-NEXT: [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX9-NEXT: [[V_CVT_F32_F16_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_CVT_F32_F16_e64 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[S_MOV_B32_:%[0-9]+]]:sgpr_32 = S_MOV_B32 1069066811
    ; GFX9-NEXT: [[V_MUL_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F32_e64 0, killed [[V_CVT_F32_F16_e64_]], 0, [[S_MOV_B32_]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_EXP_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_EXP_F32_e64 0, killed [[V_MUL_F32_e64_]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_CVT_F16_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_CVT_F16_F32_e64 0, killed [[V_EXP_F32_e64_]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_CVT_F32_F16_sdwa:%[0-9]+]]:vgpr_32 = nofpexcept V_CVT_F32_F16_sdwa 0, [[COPY]], 0, 0, 6, 0, 5, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_MUL_F32_e64_1:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F32_e64 0, killed [[V_CVT_F32_F16_sdwa]], 0, [[S_MOV_B32_]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_EXP_F32_e64_1:%[0-9]+]]:vgpr_32 = nofpexcept V_EXP_F32_e64 0, killed [[V_MUL_F32_e64_1]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_CVT_F16_F32_e64_1:%[0-9]+]]:vgpr_32 = nofpexcept V_CVT_F16_F32_e64 0, killed [[V_EXP_F32_e64_1]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_CVT_F32_F16_e64_1:%[0-9]+]]:vgpr_32 = nofpexcept V_CVT_F32_F16_e64 0, [[COPY1]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_MUL_F32_e64_2:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F32_e64 0, killed [[V_CVT_F32_F16_e64_1]], 0, [[S_MOV_B32_]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_EXP_F32_e64_2:%[0-9]+]]:vgpr_32 = nofpexcept V_EXP_F32_e64 0, killed [[V_MUL_F32_e64_2]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_CVT_F16_F32_e64_2:%[0-9]+]]:vgpr_32 = nofpexcept V_CVT_F16_F32_e64 0, killed [[V_EXP_F32_e64_2]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_CVT_F32_F16_sdwa1:%[0-9]+]]:vgpr_32 = nofpexcept V_CVT_F32_F16_sdwa 0, [[COPY1]], 0, 0, 6, 0, 5, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_MUL_F32_e64_3:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F32_e64 0, killed [[V_CVT_F32_F16_sdwa1]], 0, [[S_MOV_B32_]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_EXP_F32_e64_3:%[0-9]+]]:vgpr_32 = nofpexcept V_EXP_F32_e64 0, killed [[V_MUL_F32_e64_3]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_CVT_F16_F32_e64_3:%[0-9]+]]:vgpr_32 = nofpexcept V_CVT_F16_F32_e64 0, killed [[V_EXP_F32_e64_3]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_PACK_B32_F16_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_PACK_B32_F16_e64 0, killed [[V_CVT_F16_F32_e64_2]], 0, killed [[V_CVT_F16_F32_e64_3]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_PACK_B32_F16_e64_1:%[0-9]+]]:vgpr_32 = nofpexcept V_PACK_B32_F16_e64 0, killed [[V_CVT_F16_F32_e64_]], 0, killed [[V_CVT_F16_F32_e64_1]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: $vgpr0 = COPY [[V_PACK_B32_F16_e64_]]
    ; GFX9-NEXT: $vgpr1 = COPY [[V_PACK_B32_F16_e64_1]]
    ; GFX9-NEXT: SI_RETURN implicit $vgpr0, implicit $vgpr1
    %9:vgpr_32 = COPY $vgpr1
    %8:vgpr_32 = COPY $vgpr0
    %11:vgpr_32 = nofpexcept V_CVT_F32_F16_e64 0, %9, 0, 0, implicit $mode, implicit $exec
    %12:sgpr_32 = S_MOV_B32 1069066811
    %13:vgpr_32 = nofpexcept V_MUL_F32_e64 0, killed %11, 0, %12, 0, 0, implicit $mode, implicit $exec
    %14:vgpr_32 = nofpexcept V_EXP_F32_e64 0, killed %13, 0, 0, implicit $mode, implicit $exec
    %15:vgpr_32 = nofpexcept V_CVT_F16_F32_e64 0, killed %14, 0, 0, implicit $mode, implicit $exec
    %17:vgpr_32 = V_LSHRREV_B32_e64 16, %9, implicit $exec
    %19:vgpr_32 = nofpexcept V_CVT_F32_F16_e64 0, %17, 0, 0, implicit $mode, implicit $exec
    %20:vgpr_32 = nofpexcept V_MUL_F32_e64 0, killed %19, 0, %12, 0, 0, implicit $mode, implicit $exec
    %21:vgpr_32 = nofpexcept V_EXP_F32_e64 0, killed %20, 0, 0, implicit $mode, implicit $exec
    %22:vgpr_32 = nofpexcept V_CVT_F16_F32_e64 0, killed %21, 0, 0, implicit $mode, implicit $exec
    %24:vgpr_32 = nofpexcept V_CVT_F32_F16_e64 0, %8, 0, 0, implicit $mode, implicit $exec
    %25:vgpr_32 = nofpexcept V_MUL_F32_e64 0, killed %24, 0, %12, 0, 0, implicit $mode, implicit $exec
    %26:vgpr_32 = nofpexcept V_EXP_F32_e64 0, killed %25, 0, 0, implicit $mode, implicit $exec
    %27:vgpr_32 = nofpexcept V_CVT_F16_F32_e64 0, killed %26, 0, 0, implicit $mode, implicit $exec
    %28:vgpr_32 = V_LSHRREV_B32_e64 16, %8, implicit $exec
    %30:vgpr_32 = nofpexcept V_CVT_F32_F16_e64 0, %28, 0, 0, implicit $mode, implicit $exec
    %31:vgpr_32 = nofpexcept V_MUL_F32_e64 0, killed %30, 0, %12, 0, 0, implicit $mode, implicit $exec
    %32:vgpr_32 = nofpexcept V_EXP_F32_e64 0, killed %31, 0, 0, implicit $mode, implicit $exec
    %33:vgpr_32 = nofpexcept V_CVT_F16_F32_e64 0, killed %32, 0, 0, implicit $mode, implicit $exec
    %34:vgpr_32 = nofpexcept V_PACK_B32_F16_e64 0, killed %27, 0, killed %33, 0, 0, implicit $mode, implicit $exec
    %35:vgpr_32 = nofpexcept V_PACK_B32_F16_e64 0, killed %15, 0, killed %22, 0, 0, implicit $mode, implicit $exec
    $vgpr0 = COPY %34
    $vgpr1 = COPY %35
    SI_RETURN implicit $vgpr0, implicit $vgpr1
...

---
name:            cascaded_v4f16
tracksRegLiveness: true
body:             |
  bb.0 (%ir-block.0):
    liveins: $vgpr0, $vgpr1

    ; GFX9-LABEL: name: cascaded_v4f16
    ; GFX9: liveins: $vgpr0, $vgpr1
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
    ; GFX9-NEXT: [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX9-NEXT: [[V_LOG_F16_sdwa:%[0-9]+]]:vgpr_32 = nofpexcept V_LOG_F16_sdwa 0, [[COPY1]], 0, 0, 6, 0, 5, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_LOG_F16_sdwa1:%[0-9]+]]:vgpr_32 = nofpexcept V_LOG_F16_sdwa 0, [[COPY]], 0, 0, 6, 0, 5, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_LOG_F16_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_LOG_F16_e64 0, [[COPY1]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_LOG_F16_e64_1:%[0-9]+]]:vgpr_32 = nofpexcept V_LOG_F16_e64 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_MUL_F16_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F16_e64 0, killed [[V_LOG_F16_e64_1]], 0, 12568, 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_SIN_F16_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_SIN_F16_e64 0, killed [[V_MUL_F16_e64_]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_MUL_F16_e64_1:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F16_e64 0, killed [[V_LOG_F16_sdwa1]], 0, 12568, 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_SIN_F16_e64_1:%[0-9]+]]:vgpr_32 = nofpexcept V_SIN_F16_e64 0, killed [[V_MUL_F16_e64_1]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_MUL_F16_e64_2:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F16_e64 0, killed [[V_LOG_F16_e64_]], 0, 12568, 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_SIN_F16_e64_2:%[0-9]+]]:vgpr_32 = nofpexcept V_SIN_F16_e64 0, killed [[V_MUL_F16_e64_2]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_MUL_F16_e64_3:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F16_e64 0, killed [[V_LOG_F16_sdwa]], 0, 12568, 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_SIN_F16_e64_3:%[0-9]+]]:vgpr_32 = nofpexcept V_SIN_F16_e64 0, killed [[V_MUL_F16_e64_3]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_PACK_B32_F16_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_PACK_B32_F16_e64 0, killed [[V_SIN_F16_e64_2]], 0, killed [[V_SIN_F16_e64_3]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: [[V_PACK_B32_F16_e64_1:%[0-9]+]]:vgpr_32 = nofpexcept V_PACK_B32_F16_e64 0, killed [[V_SIN_F16_e64_]], 0, killed [[V_SIN_F16_e64_1]], 0, 0, implicit $mode, implicit $exec
    ; GFX9-NEXT: $vgpr0 = COPY [[V_PACK_B32_F16_e64_]]
    ; GFX9-NEXT: $vgpr1 = COPY [[V_PACK_B32_F16_e64_1]]
    ; GFX9-NEXT: SI_RETURN implicit $vgpr0, implicit $vgpr1
    %9:vgpr_32 = COPY $vgpr1
    %8:vgpr_32 = COPY $vgpr0
    %11:vgpr_32 = V_LSHRREV_B32_e64 16, %8, implicit $exec
    %13:vgpr_32 = nofpexcept V_LOG_F16_e64 0, %11, 0, 0, implicit $mode, implicit $exec
    %14:vgpr_32 = V_LSHRREV_B32_e64 16, %9, implicit $exec
    %16:vgpr_32 = nofpexcept V_LOG_F16_e64 0, %14, 0, 0, implicit $mode, implicit $exec
    %18:vgpr_32 = nofpexcept V_LOG_F16_e64 0, %8, 0, 0, implicit $mode, implicit $exec
    %20:vgpr_32 = nofpexcept V_LOG_F16_e64 0, %9, 0, 0, implicit $mode, implicit $exec
    %22:vgpr_32 = nofpexcept V_MUL_F16_e64 0, killed %20, 0, 12568, 0, 0, implicit $mode, implicit $exec
    %23:vgpr_32 = nofpexcept V_SIN_F16_e64 0, killed %22, 0, 0, implicit $mode, implicit $exec
    %24:vgpr_32 = nofpexcept V_MUL_F16_e64 0, killed %16, 0, 12568, 0, 0, implicit $mode, implicit $exec
    %25:vgpr_32 = nofpexcept V_SIN_F16_e64 0, killed %24, 0, 0, implicit $mode, implicit $exec
    %26:vgpr_32 = nofpexcept V_MUL_F16_e64 0, killed %18, 0, 12568, 0, 0, implicit $mode, implicit $exec
    %27:vgpr_32 = nofpexcept V_SIN_F16_e64 0, killed %26, 0, 0, implicit $mode, implicit $exec
    %28:vgpr_32 = nofpexcept V_MUL_F16_e64 0, killed %13, 0, 12568, 0, 0, implicit $mode, implicit $exec
    %29:vgpr_32 = nofpexcept V_SIN_F16_e64 0, killed %28, 0, 0, implicit $mode, implicit $exec
    %30:vgpr_32 = nofpexcept V_PACK_B32_F16_e64 0, killed %27, 0, killed %29, 0, 0, implicit $mode, implicit $exec
    %31:vgpr_32 = nofpexcept V_PACK_B32_F16_e64 0, killed %23, 0, killed %25, 0, 0, implicit $mode, implicit $exec
    $vgpr0 = COPY %30
    $vgpr1 = COPY %31
    SI_RETURN implicit $vgpr0, implicit $vgpr1
...

---
name:            unbalanced_operations_packed
tracksRegLiveness: true
body:             |
  bb.0 (%ir-block.0):
    liveins: $vgpr0, $vgpr1
    ; GFX9-LABEL: name: unbalanced_operations_packed
    ; GFX9: liveins: $vgpr0, $vgpr1
    ; GFX9-NEXT: {{  $}}
    ; GFX9-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr1
    ; GFX9-NEXT: [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX9-NEXT: [[V_LOG_F16_sdwa:%[0-9]+]]:vgpr_32 = nofpexcept V_LOG_F16_sdwa 0, [[COPY]], 0, 0, 4, 2, 4, implicit $mode, implicit $exec, implicit [[COPY]](tied-def 0)
    ; GFX9-NEXT: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 14732
    ; GFX9-NEXT: [[V_MUL_F16_sdwa:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F16_sdwa 0, killed [[V_LOG_F16_sdwa]], 0, [[S_MOV_B32_]], 0, 0, 4, 2, 4, 6, implicit $mode, implicit $exec, implicit killed [[V_LOG_F16_sdwa]](tied-def 0)
    ; GFX9-NEXT: [[V_LOG_F16_sdwa1:%[0-9]+]]:vgpr_32 = nofpexcept V_LOG_F16_sdwa 0, [[V_MUL_F16_sdwa]], 0, 0, 5, 2, 5, implicit $mode, implicit $exec, implicit [[V_MUL_F16_sdwa]](tied-def 0)
    ; GFX9-NEXT: [[V_LOG_F16_sdwa2:%[0-9]+]]:vgpr_32 = nofpexcept V_LOG_F16_sdwa 0, [[COPY1]], 0, 0, 4, 2, 4, implicit $mode, implicit $exec, implicit [[COPY1]](tied-def 0)
    ; GFX9-NEXT: [[V_LOG_F16_sdwa3:%[0-9]+]]:vgpr_32 = nofpexcept V_LOG_F16_sdwa 0, [[V_LOG_F16_sdwa2]], 0, 0, 5, 2, 5, implicit $mode, implicit $exec, implicit [[V_LOG_F16_sdwa2]](tied-def 0)
    ; GFX9-NEXT: [[V_MUL_F16_sdwa1:%[0-9]+]]:vgpr_32 = nofpexcept V_MUL_F16_sdwa 0, killed [[V_LOG_F16_sdwa3]], 0, [[S_MOV_B32_]], 0, 0, 5, 2, 5, 6, implicit $mode, implicit $exec, implicit killed [[V_LOG_F16_sdwa3]](tied-def 0)
    ; GFX9-NEXT: $vgpr0 = COPY [[V_MUL_F16_sdwa1]]
    ; GFX9-NEXT: $vgpr1 = COPY [[V_LOG_F16_sdwa1]]
    ; GFX9-NEXT: SI_RETURN implicit $vgpr0, implicit $vgpr1
    %9:vgpr_32 = COPY $vgpr1
    %8:vgpr_32 = COPY $vgpr0
    %11:vgpr_32 = nofpexcept V_LOG_F16_e64 0, %9, 0, 0, implicit $mode, implicit $exec
    %12:sreg_32 = S_MOV_B32 14732
    %13:vgpr_32 = nofpexcept V_MUL_F16_e64 0, killed %11, 0, %12, 0, 0, implicit $mode, implicit $exec
    %15:vgpr_32 = V_LSHRREV_B32_e64 16, %9, implicit $exec
    %17:vgpr_32 = nofpexcept V_LOG_F16_e64 0, %15, 0, 0, implicit $mode, implicit $exec
    %20:vgpr_32 = nofpexcept V_LOG_F16_e64 0, %8, 0, 0, implicit $mode, implicit $exec
    %22:vgpr_32 = V_LSHRREV_B32_e64 16, %8, implicit $exec
    %24:vgpr_32 = nofpexcept V_LOG_F16_e64 0, %22, 0, 0, implicit $mode, implicit $exec
    %25:vgpr_32 = nofpexcept V_MUL_F16_e64 0, killed %24, 0, %12, 0, 0, implicit $mode, implicit $exec
    %26:vgpr_32 = nofpexcept V_PACK_B32_F16_e64 0, killed %20, 0, killed %25, 0, 0, implicit $mode, implicit $exec
    %27:vgpr_32 = nofpexcept V_PACK_B32_F16_e64 0, killed %13, 0, killed %17, 0, 0, implicit $mode, implicit $exec
    $vgpr0 = COPY %26
    $vgpr1 = COPY %27
    SI_RETURN implicit $vgpr0, implicit $vgpr1
...
