# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=hawaii -verify-machineinstrs -run-pass=prologepilog %s -o - | FileCheck %s

# Frame virtual SGPRs should not be used, as the register scavenger cannot usefully spill them anymore.
# Spilling is also worse than increment and restore of a frame register. There should be no spills remaining.

---
name: scavenge_sgpr_pei
tracksRegLiveness: true

stack:
  - { id: 0, type: default, size: 4, alignment: 4096 }

machineFunctionInfo:
  isEntryFunction: false
  scratchRSrcReg:  $sgpr0_sgpr1_sgpr2_sgpr3
  frameOffsetReg:  $sgpr33
  stackPtrOffsetReg:  $sgpr32

body:             |
  bb.0:
    liveins: $vgpr1

    ; CHECK-LABEL: name: scavenge_sgpr_pei
    ; CHECK: liveins: $vgpr1, $vgpr2
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION llvm_def_aspace_cfa $sgpr32, 0, 6
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30, 32, $sgpr31, 32
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr0
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr4
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr5
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr6
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr7
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr8
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr9
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr10
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr11
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr12
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr13
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr14
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr15
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr16
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr17
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr18
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr19
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr20
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr21
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr22
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr23
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr24
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr25
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr26
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr27
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr28
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr29
    ; CHECK-NEXT: $sgpr4 = COPY $sgpr33
    ; CHECK-NEXT: $sgpr33 = frame-setup S_ADD_I32 $sgpr32, 262080, implicit-def $scc
    ; CHECK-NEXT: $sgpr33 = frame-setup S_AND_B32 killed $sgpr33, 4294705152, implicit-def dead $scc
    ; CHECK-NEXT: $sgpr6_sgpr7 = S_XOR_SAVEEXEC_B64 -1, implicit-def $exec, implicit-def dead $scc, implicit $exec
    ; CHECK-NEXT: $sgpr5 = S_ADD_I32 $sgpr33, 262400, implicit-def dead $scc
    ; CHECK-NEXT: BUFFER_STORE_DWORD_OFFSET $vgpr2, $sgpr0_sgpr1_sgpr2_sgpr3, killed $sgpr5, 0, 0, 0, implicit $exec :: (store (s32) into %stack.2, addrspace 5)
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION offset $vgpr2, 262400
    ; CHECK-NEXT: $exec = S_MOV_B64 killed $sgpr6_sgpr7
    ; CHECK-NEXT: $vgpr2 = SI_SPILL_S32_TO_VGPR $sgpr4, 0, undef $vgpr2
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION llvm_vector_registers $sgpr33, $vgpr2, 0, 32
    ; CHECK-NEXT: $vgpr2 = SI_SPILL_S32_TO_VGPR $sgpr34, 1, undef $vgpr2
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION llvm_vector_registers $sgpr34, $vgpr2, 1, 32
    ; CHECK-NEXT: $sgpr34 = frame-setup COPY $sgpr32
    ; CHECK-NEXT: frame-setup CFI_INSTRUCTION def_cfa_register $sgpr33
    ; CHECK-NEXT: $sgpr32 = frame-setup S_ADD_I32 $sgpr32, 786432, implicit-def dead $scc
    ; CHECK-NEXT: S_NOP 0, implicit-def $sgpr4, implicit-def $sgpr5, implicit-def $sgpr6, implicit-def $sgpr7, implicit-def $sgpr8, implicit-def $sgpr9, implicit-def $sgpr10, implicit-def $sgpr11, implicit-def $sgpr12, implicit-def $sgpr13, implicit-def $sgpr14, implicit-def $sgpr15, implicit-def $sgpr16, implicit-def $sgpr17, implicit-def $sgpr18, implicit-def $sgpr19, implicit-def $sgpr20, implicit-def $sgpr21, implicit-def $sgpr22, implicit-def $sgpr23, implicit-def $sgpr24, implicit-def $sgpr25, implicit-def $sgpr26, implicit-def $sgpr27, implicit-def $sgpr28, implicit-def $sgpr29, implicit-def $sgpr30, implicit-def $sgpr31, implicit-def $vcc
    ; CHECK-NEXT: $sgpr33 = S_LSHR_B32 $sgpr33, 6, implicit-def $scc
    ; CHECK-NEXT: $sgpr33 = S_ADD_I32 killed $sgpr33, 4096, implicit-def $scc
    ; CHECK-NEXT: $vgpr3 = COPY killed $sgpr33
    ; CHECK-NEXT: $sgpr33 = S_ADD_I32 killed $sgpr33, -4096, implicit-def $scc
    ; CHECK-NEXT: $sgpr33 = S_LSHL_B32 $sgpr33, 6, implicit-def $scc
    ; CHECK-NEXT: $vgpr0 = V_OR_B32_e32 killed $vgpr3, $vgpr1, implicit $exec, implicit $sgpr4, implicit $sgpr5, implicit $sgpr6, implicit $sgpr7, implicit $sgpr8, implicit $sgpr9, implicit $sgpr10, implicit $sgpr11, implicit $sgpr12, implicit $sgpr13, implicit $sgpr14, implicit $sgpr15, implicit $sgpr16, implicit $sgpr17, implicit $sgpr18, implicit $sgpr19, implicit $sgpr20, implicit $sgpr21, implicit $sgpr22, implicit $sgpr23, implicit $sgpr24, implicit $sgpr25, implicit $sgpr26, implicit $sgpr27, implicit $sgpr28, implicit $sgpr29, implicit $sgpr30, implicit $sgpr31
    ; CHECK-NEXT: $sgpr32 = frame-destroy COPY $sgpr34
    ; CHECK-NEXT: $sgpr4 = SI_RESTORE_S32_FROM_VGPR $vgpr2, 0
    ; CHECK-NEXT: $sgpr34 = SI_RESTORE_S32_FROM_VGPR $vgpr2, 1
    ; CHECK-NEXT: $sgpr6_sgpr7 = S_XOR_SAVEEXEC_B64 -1, implicit-def $exec, implicit-def dead $scc, implicit $exec
    ; CHECK-NEXT: $sgpr5 = S_ADD_I32 $sgpr33, 262400, implicit-def dead $scc
    ; CHECK-NEXT: $vgpr2 = BUFFER_LOAD_DWORD_OFFSET $sgpr0_sgpr1_sgpr2_sgpr3, killed $sgpr5, 0, 0, 0, implicit $exec :: (load (s32) from %stack.2, addrspace 5)
    ; CHECK-NEXT: $exec = S_MOV_B64 killed $sgpr6_sgpr7
    ; CHECK-NEXT: $sgpr32 = frame-destroy S_ADD_I32 $sgpr32, -786432, implicit-def dead $scc
    ; CHECK-NEXT: frame-destroy CFI_INSTRUCTION def_cfa_register $sgpr32
    ; CHECK-NEXT: $sgpr33 = COPY $sgpr4
    ; CHECK-NEXT: S_ENDPGM 0, implicit $vcc
    S_NOP 0, implicit-def $sgpr4, implicit-def $sgpr5, implicit-def $sgpr6, implicit-def $sgpr7, implicit-def $sgpr8, implicit-def $sgpr9, implicit-def $sgpr10, implicit-def $sgpr11, implicit-def $sgpr12, implicit-def $sgpr13, implicit-def $sgpr14, implicit-def $sgpr15, implicit-def $sgpr16, implicit-def $sgpr17, implicit-def $sgpr18, implicit-def $sgpr19, implicit-def $sgpr20, implicit-def $sgpr21, implicit-def $sgpr22, implicit-def $sgpr23, implicit-def $sgpr24, implicit-def $sgpr25, implicit-def $sgpr26, implicit-def $sgpr27, implicit-def $sgpr28, implicit-def $sgpr29, implicit-def $sgpr30, implicit-def $sgpr31, implicit-def $vcc
    $vgpr0 = V_OR_B32_e32 %stack.0, $vgpr1, implicit $exec, implicit $sgpr4, implicit $sgpr5, implicit $sgpr6, implicit $sgpr7, implicit $sgpr8, implicit $sgpr9, implicit $sgpr10, implicit $sgpr11, implicit $sgpr12, implicit $sgpr13, implicit $sgpr14, implicit $sgpr15, implicit $sgpr16, implicit $sgpr17, implicit $sgpr18, implicit $sgpr19, implicit $sgpr20, implicit $sgpr21, implicit $sgpr22, implicit $sgpr23, implicit $sgpr24, implicit $sgpr25, implicit $sgpr26, implicit $sgpr27, implicit $sgpr28, implicit $sgpr29, implicit $sgpr30, implicit $sgpr31
    S_ENDPGM 0, implicit $vcc
...
