# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=amdgcn -mcpu=gfx908 -run-pass=postra-machine-sink -o - %s | FileCheck %s

---
name:            test_undef_use_sinking
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_undef_use_sinking
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $sgpr0 = S_MOV_B32 1
  ; CHECK-NEXT:   renamable $sgpr1 = COPY killed renamable $sgpr0, implicit undef $vgpr0
  ; CHECK-NEXT:   $vgpr0 = V_MOV_B32_e32 0, implicit $exec
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $sgpr1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   S_ENDPGM 0, implicit $sgpr1
  bb.0:
    successors: %bb.1

    renamable $sgpr0 = S_MOV_B32 1
    renamable $sgpr1 = COPY killed renamable $sgpr0, implicit undef $vgpr0
    $vgpr0 = V_MOV_B32_e32 0, implicit $exec

  bb.1:
    liveins: $sgpr1
    S_ENDPGM 0, implicit $sgpr1
...
---
name:            test_internal_read_sinking
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: test_internal_read_sinking
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $sgpr0 = S_MOV_B32 1
  ; CHECK-NEXT:   $vgpr1 = V_MOV_B32_e32 0, implicit $exec
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   liveins: $sgpr0, $vgpr0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $sgpr1 = COPY killed renamable $sgpr0, implicit-def $vgpr0, implicit internal $vgpr0
  ; CHECK-NEXT:   S_ENDPGM 0, implicit $sgpr1
  bb.0:
    successors: %bb.1

    renamable $sgpr0 = S_MOV_B32 1
    renamable $sgpr1 = COPY killed renamable $sgpr0, implicit-def $vgpr0, implicit internal $vgpr0
    $vgpr1 = V_MOV_B32_e32 0, implicit $exec

  bb.1:
    liveins: $sgpr1, $vgpr0
    S_ENDPGM 0, implicit $sgpr1
...
