# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx950 -verify-machineinstrs --run-pass=amdgpu-pre-ra-optimizations %s -o - | FileCheck %s
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx950 -verify-machineinstrs --amdgpu-avgpr-inflation=1 --run-pass=amdgpu-pre-ra-optimizations %s -o - | FileCheck %s -check-prefix=INFLATE

---
name: agpr_constraint
tracksRegLiveness: true
body: |
  bb.0:
    ; CHECK-LABEL: name: agpr_constraint
    ; CHECK: [[DEF:%[0-9]+]]:vgpr_32 = IMPLICIT_DEF
    ; CHECK-NEXT: [[DS_READ_B128_gfx9_:%[0-9]+]]:areg_128_align2 = DS_READ_B128_gfx9 [[DEF]], 0, 0, implicit $exec
    ; CHECK-NEXT: INLINEASM &"", 1 /* sideeffect attdialect */, 6291466 /* regdef:AReg_128_Align2 */, def dead [[DS_READ_B128_gfx9_]], 2147483657 /* reguse tiedto:$0 */, [[DS_READ_B128_gfx9_]](tied-def 3)
    ; CHECK-NEXT: S_ENDPGM 0, amdgpu_allvgprs
    ;
    ; INFLATE-LABEL: name: agpr_constraint
    ; INFLATE: [[DEF:%[0-9]+]]:vgpr_32 = IMPLICIT_DEF
    ; INFLATE-NEXT: [[DS_READ_B128_gfx9_:%[0-9]+]]:areg_128_align2 = DS_READ_B128_gfx9 [[DEF]], 0, 0, implicit $exec
    ; INFLATE-NEXT: INLINEASM &"", 1 /* sideeffect attdialect */, 6291466 /* regdef:AReg_128_Align2 */, def dead [[DS_READ_B128_gfx9_]], 2147483657 /* reguse tiedto:$0 */, [[DS_READ_B128_gfx9_]](tied-def 3)
    ; INFLATE-NEXT: S_ENDPGM 0, amdgpu_allvgprs
    %0:vgpr_32 = IMPLICIT_DEF
    %1:areg_128_align2 = DS_READ_B128_gfx9 %0, 0, 0, implicit $exec
    INLINEASM &"", 1 /* sideeffect attdialect */, 6291466 /* regdef:AReg_128_Align2 */, def %1, 2147483657 /* reguse tiedto:$0 */, %1(tied-def 3)
    S_ENDPGM 0, amdgpu_allvgprs
...

---
name: vgpr_constraint
tracksRegLiveness: true
body: |
  bb.0:
    ; CHECK-LABEL: name: vgpr_constraint
    ; CHECK: [[DEF:%[0-9]+]]:vgpr_32 = IMPLICIT_DEF
    ; CHECK-NEXT: [[DS_READ_B128_gfx9_:%[0-9]+]]:vreg_128_align2 = DS_READ_B128_gfx9 [[DEF]], 0, 0, implicit $exec
    ; CHECK-NEXT: INLINEASM &"", 1 /* sideeffect attdialect */, 6422538 /* regdef:VReg_128_Align2 */, def dead [[DS_READ_B128_gfx9_]], 2147483657 /* reguse tiedto:$0 */, [[DS_READ_B128_gfx9_]](tied-def 3)
    ; CHECK-NEXT: S_ENDPGM 0, amdgpu_allvgprs
    ;
    ; INFLATE-LABEL: name: vgpr_constraint
    ; INFLATE: [[DEF:%[0-9]+]]:vgpr_32 = IMPLICIT_DEF
    ; INFLATE-NEXT: [[DS_READ_B128_gfx9_:%[0-9]+]]:vreg_128_align2 = DS_READ_B128_gfx9 [[DEF]], 0, 0, implicit $exec
    ; INFLATE-NEXT: INLINEASM &"", 1 /* sideeffect attdialect */, 6422538 /* regdef:VReg_128_Align2 */, def dead [[DS_READ_B128_gfx9_]], 2147483657 /* reguse tiedto:$0 */, [[DS_READ_B128_gfx9_]](tied-def 3)
    ; INFLATE-NEXT: S_ENDPGM 0, amdgpu_allvgprs
    %0:vgpr_32 = IMPLICIT_DEF
    %1:vreg_128_align2 = DS_READ_B128_gfx9 %0, 0, 0, implicit $exec
    INLINEASM &"", 1 /* sideeffect attdialect */, 6422538 /* regdef:VReg_128_Align2 */, def %1, 2147483657 /* reguse tiedto:$0 */, %1(tied-def 3)
    S_ENDPGM 0, amdgpu_allvgprs
...

---
name: no_constraint
tracksRegLiveness: true
body: |
  bb.0:
    ; CHECK-LABEL: name: no_constraint
    ; CHECK: [[DEF:%[0-9]+]]:vgpr_32 = IMPLICIT_DEF
    ; CHECK-NEXT: dead [[DS_READ_B128_gfx9_:%[0-9]+]]:vreg_128_align2 = DS_READ_B128_gfx9 [[DEF]], 0, 0, implicit $exec
    ; CHECK-NEXT: S_ENDPGM 0, amdgpu_allvgprs
    ;
    ; INFLATE-LABEL: name: no_constraint
    ; INFLATE: [[DEF:%[0-9]+]]:vgpr_32 = IMPLICIT_DEF
    ; INFLATE-NEXT: dead [[DS_READ_B128_gfx9_:%[0-9]+]]:av_128_align2 = DS_READ_B128_gfx9 [[DEF]], 0, 0, implicit $exec
    ; INFLATE-NEXT: S_ENDPGM 0, amdgpu_allvgprs
    %0:vgpr_32 = IMPLICIT_DEF
    %1:vreg_128_align2 = DS_READ_B128_gfx9 %0, 0, 0, implicit $exec
    S_ENDPGM 0, amdgpu_allvgprs
...
