# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx906 -verify-machineinstrs -run-pass=prologepilog -o - %s | FileCheck -check-prefix=GCN %s

# The scratch register vgpr0 is used here to spill sgpr35 register.
# The function also returns a value that goes via. vgpr0.
# This test is to ensure the vgpr0 store/restore inserted at the prolog/epilog
# preserves only its inactive lanes to ensure the outgoing value will not be overwritten.

---
name: preserve_scratch_vgpr_inactive_lanes
tracksRegLiveness: true
machineFunctionInfo:
  scratchRSrcReg:  $sgpr0_sgpr1_sgpr2_sgpr3
  frameOffsetReg:  $sgpr33
  stackPtrOffsetReg:  $sgpr32

body:             |
  bb.0:
    liveins: $sgpr35, $vgpr0, $sgpr30_sgpr31
    ; GCN-LABEL: name: preserve_scratch_vgpr_inactive_lanes
    ; GCN: liveins: $sgpr35, $vgpr0, $sgpr30_sgpr31
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: frame-setup CFI_INSTRUCTION llvm_def_aspace_cfa $sgpr32_lo16, 0, 6
    ; GCN-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30_lo16, 32, $sgpr31_lo16, 32
    ; GCN-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr0_lo16
    ; GCN-NEXT: $vgpr0 = SI_SPILL_S32_TO_VGPR $sgpr35, 0, killed $vgpr0
    ; GCN-NEXT: $sgpr35 = S_MOV_B32 5
    ; GCN-NEXT: $sgpr35 = SI_RESTORE_S32_FROM_VGPR $vgpr0, 0
    ; GCN-NEXT: renamable $vgpr0 = V_MOV_B32_e32 10, implicit $exec
    ; GCN-NEXT: S_SETPC_B64_return killed renamable $sgpr30_sgpr31, implicit $vgpr0
    renamable $vgpr0 = SI_SPILL_S32_TO_VGPR $sgpr35, 0, killed $vgpr0
    $sgpr35 = S_MOV_B32 5
    $sgpr35 = SI_RESTORE_S32_FROM_VGPR $vgpr0, 0
    renamable $vgpr0 = V_MOV_B32_e32 10, implicit $exec
    S_SETPC_B64_return killed renamable $sgpr30_sgpr31, implicit $vgpr0
...
