; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1300 -amdgpu-promote-private=true -private-object-reg-chunk-size=4 -verify-machineinstrs -o - %s | FileCheck --check-prefixes=CHECK,KERNEL %s

define amdgpu_kernel void @foo(ptr addrspace(5) %out, i32 %x) {
; CHECK-LABEL: foo:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_load_b32 s0, s[4:5], 0x0
; CHECK-NEXT:    ; implicit-def: $vgpr0_vgpr1_vgpr2_vgpr3
; CHECK-NEXT:    s_set_gpr_idx_u32 idx1, 0
; CHECK-NEXT:    v_mov_b32_e32 v0, 0x40a00000
; CHECK-NEXT:    v_mov_b32_e32 v1, 0x40e00000
; CHECK-NEXT:    ; implicit-def: $vgpr30_vgpr31_vgpr32_vgpr33
; CHECK-NEXT:    ; implicit-def: $vgpr34_vgpr35_vgpr36_vgpr37
; CHECK-NEXT:    ; implicit-def: $vgpr38_vgpr39_vgpr40_vgpr41
; CHECK-NEXT:    ; implicit-def: $vgpr42_vgpr43_vgpr44_vgpr45
; CHECK-NEXT:    ; implicit-def: $vgpr46_vgpr47_vgpr48_vgpr49
; CHECK-NEXT:    ; implicit-def: $vgpr50_vgpr51_vgpr52_vgpr53
; CHECK-NEXT:    ; implicit-def: $vgpr54_vgpr55_vgpr56_vgpr57
; CHECK-NEXT:    ; implicit-def: $vgpr58_vgpr59
; CHECK-NEXT:    ; implicit-def: $vgpr4_vgpr5_vgpr6_vgpr7
; CHECK-NEXT:    ; implicit-def: $vgpr8_vgpr9_vgpr10_vgpr11
; CHECK-NEXT:    ; implicit-def: $vgpr12_vgpr13_vgpr14_vgpr15
; CHECK-NEXT:    ; implicit-def: $vgpr16_vgpr17_vgpr18_vgpr19
; CHECK-NEXT:    ; implicit-def: $vgpr20_vgpr21_vgpr22_vgpr23
; CHECK-NEXT:    ; implicit-def: $vgpr24_vgpr25_vgpr26_vgpr27
; CHECK-NEXT:    ; implicit-def: $vgpr28_vgpr29
; CHECK-NEXT:    s_wait_kmcnt 0x0
; CHECK-NEXT:    s_clause 0x1
; CHECK-NEXT:    scratch_store_b32 off, v0, s0 offset:20 scope:SCOPE_SE
; CHECK-NEXT:    scratch_store_b32 off, v1, s0 offset:28 scope:SCOPE_SE
; CHECK-NEXT:    s_set_vgpr_frames 64 ; vsrc0_idx=0 vsrc1_idx=0 vsrc2_idx=0 vdst_idx=1 vsrc0_msb=0 vsrc1_msb=0 vsrc2_msb=0 vdst_msb=0
; CHECK-NEXT:    v_mov_b32_e32 g1[31], v0
; CHECK-NEXT:    v_mov_b32_e32 g1[1], v1
; CHECK-NEXT:    s_endpgm
entry:
  %p = alloca [30 x float], align 4, addrspace(5)
  %p.1 = getelementptr [30 x float], ptr addrspace(5) %p, i32 0, i32 1
  store float 5.0, ptr addrspace(5) %p.1, align 4
  %vp = load float, ptr addrspace(5) %p.1, align 4

  %q = alloca [30 x float], align 4, addrspace(5)
  %q.1 = getelementptr [30 x float], ptr addrspace(5) %q, i32 0, i32 1
  store float 7.0, ptr addrspace(5) %q.1, align 4
  %vq = load float, ptr addrspace(5) %q.1, align 4

  %out.5 = getelementptr i32, ptr addrspace(5) %out, i32 5
  store float %vp, ptr addrspace(5) %out.5

  %out.7 = getelementptr i32, ptr addrspace(5) %out, i32 7
  store float %vq, ptr addrspace(5) %out.7

  ret void
}

; KERNEL:    .enable_wavegroup: false
; KERNEL-NEXT:    .group_segment_fixed_size: 0
; KERNEL-NEXT:    .kernarg_segment_align: 8
; KERNEL-NEXT:    .kernarg_segment_size: 264
; KERNEL-NEXT:    .laneshared_segment_fixed_size: 0
; KERNEL-NEXT:    .max_flat_workgroup_size: 1024
; KERNEL-NEXT:    .name:           foo
; KERNEL-NEXT:    .private_segment_fixed_size: 244
; KERNEL-NEXT:    .sgpr_count:     6
; KERNEL-NEXT:    .sgpr_spill_count: 0
; KERNEL-NEXT:    .spatial_cluster: false
; KERNEL-NEXT:    .symbol:         foo.kd
; KERNEL-NEXT:    .uses_dynamic_stack: false
; KERNEL-NEXT:    .vgpr_count:     60
; KERNEL-NEXT:    .vgpr_spill_count: 0
; KERNEL-NEXT:    .wavefront_size: 32
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; KERNEL: {{.*}}
