; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -mtriple=amdgcn-unknown-amdhsa -passes=amdgpu-promote-alloca < %s | FileCheck %s

; Verify that the !amdgpu.non.volatile metadata is set if promoting an alloca fails.

define amdgpu_kernel void @test(i64 %val, i1 %cond) {
; CHECK-LABEL: define amdgpu_kernel void @test(
; CHECK-SAME: i64 [[VAL:%.*]], i1 [[COND:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[STACK:%.*]] = alloca [4 x i64], align 4, addrspace(5)
; CHECK-NEXT:    [[STACK_1:%.*]] = getelementptr inbounds i64, ptr addrspace(5) [[STACK]], i32 1
; CHECK-NEXT:    store i64 43, ptr addrspace(5) [[STACK]], align 8, !amdgpu.non.volatile [[META0:![0-9]+]]
; CHECK-NEXT:    br i1 [[COND]], label %[[LOOP:.*]], label %[[END:.*]]
; CHECK:       [[LOOP]]:
; CHECK-NEXT:    [[PSTACK:%.*]] = phi ptr addrspace(5) [ [[STACK]], %[[ENTRY]] ], [ [[STACK_1]], %[[LOOP]] ]
; CHECK-NEXT:    [[LOAD:%.*]] = load i64, ptr addrspace(5) [[PSTACK]], align 8, !amdgpu.non.volatile [[META0]]
; CHECK-NEXT:    store i64 32, ptr addrspace(5) [[STACK_1]], align 8, !amdgpu.non.volatile [[META0]]
; CHECK-NEXT:    [[LOOP_CC:%.*]] = icmp ne i64 [[LOAD]], 32
; CHECK-NEXT:    br i1 [[LOOP_CC]], label %[[LOOP]], label %[[END]]
; CHECK:       [[END]]:
; CHECK-NEXT:    [[RELOAD:%.*]] = load i64, ptr addrspace(5) [[STACK]], align 8, !amdgpu.non.volatile [[META0]]
; CHECK-NEXT:    [[RELOAD_1:%.*]] = load i64, ptr addrspace(5) [[STACK_1]], align 8, !amdgpu.non.volatile [[META0]]
; CHECK-NEXT:    ret void
;
entry:
  %stack = alloca [4 x i64], align 4, addrspace(5)
  %stack.1 = getelementptr inbounds i64, ptr addrspace(5) %stack, i32 1
  store i64 43, ptr addrspace(5) %stack
  br i1 %cond, label %loop, label %end

loop:
  %pstack = phi ptr addrspace(5) [%stack, %entry], [%stack.1, %loop]
  %load = load i64, ptr addrspace(5) %pstack
  store i64 32, ptr addrspace(5) %stack.1
  %loop.cc = icmp ne i64 %load, 32
  br i1 %loop.cc, label %loop, label %end

end:
  %reload = load i64, ptr addrspace(5) %stack
  %reload.1 = load i64, ptr addrspace(5) %stack.1
  ret void
}
;.
; CHECK: [[META0]] = !{}
;.
