; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -mtriple=amdgcn-unknown-unknown -passes=amdgpu-promote-alloca < %s | FileCheck %s

define void @alloca_value_cross_reference() {
; CHECK-LABEL: define void @alloca_value_cross_reference() {
; CHECK-NEXT:  [[_ENTRY:.*:]]
; CHECK-NEXT:    [[HIT_ORDERED:%.*]] = alloca [16 x float], align 4, addrspace(5)
; CHECK-NEXT:    [[HIT_INDEX:%.*]] = alloca [16 x i32], align 4, addrspace(5)
; CHECK-NEXT:    store i32 0, ptr addrspace(5) [[HIT_INDEX]], align 4
; CHECK-NEXT:    br [[DOTLR_PH5:label %.*]]
; CHECK:       [[_LR_PH5:.*:]]
; CHECK-NEXT:    [[I:%.*]] = load i32, ptr addrspace(5) [[HIT_INDEX]], align 4
; CHECK-NEXT:    [[P:%.*]] = getelementptr float, ptr addrspace(5) [[HIT_ORDERED]], i32 [[I]]
; CHECK-NEXT:    store float 0.000000e+00, ptr addrspace(5) [[P]], align 4
; CHECK-NEXT:    ret void
;
.entry:
  %hit_ordered = alloca [16 x float], align 4, addrspace(5)
  %hit_index = alloca [16 x i32], align 4, addrspace(5)
  store i32 0, ptr addrspace(5) %hit_index, align 4
  br label %.lr.ph5

  ; The separate block is needed to avoid constant-folding on
  ; the load from %hit_index.
.lr.ph5:
  %i = load i32, ptr addrspace(5) %hit_index, align 4
  %p = getelementptr float, ptr addrspace(5) %hit_ordered, i32 %i
  store float 0.000000e+00, ptr addrspace(5) %p, align 4
  ret void
}
