; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 6
; RUN: opt -S -mtriple=amdgcn-amd-amdhsa -passes=amdgpu-promote-alloca %s | FileCheck %s

define amdgpu_kernel void @kernel(ptr %p) {
; CHECK-LABEL: define amdgpu_kernel void @kernel(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[ASCAST:%.*]] = addrspacecast ptr [[P]] to ptr addrspace(1)
; CHECK-NEXT:    [[ALLOCA:%.*]] = freeze <14 x i32> poison
; CHECK-NEXT:    [[LOAD:%.*]] = load i32, ptr addrspace(1) [[ASCAST]], align 4
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[LOAD]], 0
; CHECK-NEXT:    br i1 [[CMP]], label %[[BB_1:.*]], label %[[BB_2:.*]]
; CHECK:       [[BB_2]]:
; CHECK-NEXT:    br label %[[BB_1]]
; CHECK:       [[BB_1]]:
; CHECK-NEXT:    [[TMP0:%.*]] = insertelement <14 x i32> [[ALLOCA]], i32 0, i32 0
; CHECK-NEXT:    ret void
;
entry:
  %ascast = addrspacecast ptr %p to ptr addrspace(1)
  %alloca = alloca [14 x i32], addrspace(5)
  %load = load i32, ptr addrspace(1) %ascast
  %cmp = icmp eq i32 %load, 0
  br i1 %cmp, label %bb.1, label %bb.2

bb.2:
  store i32 poison, ptr addrspace(5) %alloca
  br label %bb.1

bb.1:
  store i32 0, ptr addrspace(5) %alloca
  ret void

uselistorder ptr addrspace(5) %alloca, { 1, 0 }
}
