; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -global-isel=1 -new-reg-bank-select -mtriple=amdgcn -mcpu=gfx1100 < %s | FileCheck -check-prefixes=GFX11 %s
; RUN: llc -global-isel=1 -new-reg-bank-select -mtriple=amdgcn -mcpu=gfx1200 < %s | FileCheck -check-prefixes=GFX12 %s

define amdgpu_cs half @exp2_f16_uniform(half inreg %src) {
; GFX11-LABEL: exp2_f16_uniform:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    v_exp_f16_e32 v0.l, s0
; GFX11-NEXT:    ; return to shader part epilog
;
; GFX12-LABEL: exp2_f16_uniform:
; GFX12:       ; %bb.0:
; GFX12-NEXT:    v_s_exp_f16 s0, s0
; GFX12-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-NEXT:    s_delay_alu instid0(TRANS32_DEP_1)
; GFX12-NEXT:    v_mov_b32_e32 v0, s0
; GFX12-NEXT:    ; return to shader part epilog
  %r = call half @llvm.exp2.f16(half %src)
  ret half %r
}

define amdgpu_cs half @exp2_f16_divergent(half %src) {
; GFX11-LABEL: exp2_f16_divergent:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    v_exp_f16_e32 v0.l, v0.l
; GFX11-NEXT:    ; return to shader part epilog
;
; GFX12-LABEL: exp2_f16_divergent:
; GFX12:       ; %bb.0:
; GFX12-NEXT:    v_exp_f16_e32 v0.l, v0.l
; GFX12-NEXT:    ; return to shader part epilog
  %r = call half @llvm.exp2.f16(half %src)
  ret half %r
}

define amdgpu_cs float @amdgcn_exp2_f32_uniform(float inreg %src) {
; GFX11-LABEL: amdgcn_exp2_f32_uniform:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    v_exp_f32_e32 v0, s0
; GFX11-NEXT:    ; return to shader part epilog
;
; GFX12-LABEL: amdgcn_exp2_f32_uniform:
; GFX12:       ; %bb.0:
; GFX12-NEXT:    v_s_exp_f32 s0, s0
; GFX12-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-NEXT:    s_delay_alu instid0(TRANS32_DEP_1)
; GFX12-NEXT:    v_mov_b32_e32 v0, s0
; GFX12-NEXT:    ; return to shader part epilog
  %r = call float @llvm.amdgcn.exp2.f32(float %src)
  ret float %r
}

define amdgpu_cs float @amdgcn_exp2_f32_divergent(float %src) {
; GFX11-LABEL: amdgcn_exp2_f32_divergent:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    v_exp_f32_e32 v0, v0
; GFX11-NEXT:    ; return to shader part epilog
;
; GFX12-LABEL: amdgcn_exp2_f32_divergent:
; GFX12:       ; %bb.0:
; GFX12-NEXT:    v_exp_f32_e32 v0, v0
; GFX12-NEXT:    ; return to shader part epilog
  %r = call float @llvm.amdgcn.exp2.f32(float %src)
  ret float %r
}

define amdgpu_cs half @amdgcn_exp2_f16_uniform(half inreg %src) {
; GFX11-LABEL: amdgcn_exp2_f16_uniform:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    v_exp_f16_e32 v0.l, s0
; GFX11-NEXT:    ; return to shader part epilog
;
; GFX12-LABEL: amdgcn_exp2_f16_uniform:
; GFX12:       ; %bb.0:
; GFX12-NEXT:    v_s_exp_f16 s0, s0
; GFX12-NEXT:    s_wait_alu depctr_va_sdst(0)
; GFX12-NEXT:    s_delay_alu instid0(TRANS32_DEP_1)
; GFX12-NEXT:    v_mov_b32_e32 v0, s0
; GFX12-NEXT:    ; return to shader part epilog
  %r = call half @llvm.amdgcn.exp2.f16(half %src)
  ret half %r
}

define amdgpu_cs half @amdgcn_exp2_f16_divergent(half %src) {
; GFX11-LABEL: amdgcn_exp2_f16_divergent:
; GFX11:       ; %bb.0:
; GFX11-NEXT:    v_exp_f16_e32 v0.l, v0.l
; GFX11-NEXT:    ; return to shader part epilog
;
; GFX12-LABEL: amdgcn_exp2_f16_divergent:
; GFX12:       ; %bb.0:
; GFX12-NEXT:    v_exp_f16_e32 v0.l, v0.l
; GFX12-NEXT:    ; return to shader part epilog
  %r = call half @llvm.amdgcn.exp2.f16(half %src)
  ret half %r
}
