; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 5
; RUN: opt -mtriple=amdgcn-amd-amdhsa -verify-each -passes=amdgpu-rank-specialization,instcombine,simplifycfg -S -o - %s | FileCheck --check-prefixes=CHECK %s

declare void @dummy_common()
declare void @dummy_ranks01_a()
declare void @dummy_ranks234567_a()

; Function Attrs: convergent mustprogress noinline norecurse nounwind optnone
define dso_local amdgpu_kernel void @test_kernel() #0 !dbg !9 !reqd_work_group_size !31 {
; CHECK-LABEL: define dso_local amdgpu_kernel void @test_kernel(
; CHECK-SAME: ) #[[ATTR0:[0-9]+]] !dbg [[DBG4:![0-9]+]] !reqd_work_group_size [[META31:![0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 0, ptr nonnull @test_kernel.rank_0_1)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 1, ptr nonnull @test_kernel.rank_0_1)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 2, ptr nonnull @test_kernel.rank_2_3_4_5_6_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 3, ptr nonnull @test_kernel.rank_2_3_4_5_6_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 4, ptr nonnull @test_kernel.rank_2_3_4_5_6_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 5, ptr nonnull @test_kernel.rank_2_3_4_5_6_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 6, ptr nonnull @test_kernel.rank_2_3_4_5_6_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 7, ptr nonnull @test_kernel.rank_2_3_4_5_6_7)
; CHECK-NEXT:    ret void
;
entry:
  %wid = call i32 @llvm.amdgcn.wave.id.in.wavegroup()
  %cmp1 = icmp uge i32 %wid, 2
  br i1 %cmp1, label %if, label %else

if:                                               ; preds = %entry
  %0 = call i32 @dummy_ranks234567_a()
  br label %end

else:                                             ; preds = %entry
  %1 = call i32 @dummy_ranks01_a()
  br label %end

end:                                              ; preds = %else, %if
  %3 = call i32 @dummy_common()
  ret void
}

attributes #0 = { "amdgpu-wavegroup-enable" }

!llvm.module.flags = !{!27, !28, !29, !30}

!0 = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: !1, producer: "clang version 21.0.0git (git@github.com:AMD-Lightning-Internal/llvm-project.git b155115ba73f8b3081ca5a16c8cde7421773c756)", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, retainedTypes: !2, globals: !6, splitDebugInlining: false, nameTableKind: None)
!1 = !DIFile(filename: "D:\\develop\\llvm-project-C\\llvm\\test\\CodeGen\\AMDGPU\\<stdin>", directory: "D:\\develop\\llvm-project-C\\llvm\\build\\bin")
!2 = !{!3, !4}
!3 = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
!4 = !DIDerivedType(tag: DW_TAG_typedef, name: "s32_t", file: !5, line: 2, baseType: !3)
!5 = !DIFile(filename: "test\\CodeGen\\AMDGPU\\small_example_1.cpp", directory: "D:\\develop\\llvm-project-C\\llvm")
!6 = !{!7, !20}
!7 = !DIGlobalVariableExpression(var: !8, expr: !DIExpression())
!8 = distinct !DIGlobalVariable(name: "shared_input", scope: !9, file: !5, line: 35, type: !13, isLocal: true, isDefinition: true)
!9 = distinct !DISubprogram(name: "test_kernel", scope: !5, file: !5, line: 29, type: !10, scopeLine: 30, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: !0, retainedNodes: !12)
!10 = !DISubroutineType(types: !11)
!11 = !{null}
!12 = !{}
!13 = !DICompositeType(tag: DW_TAG_array_type, baseType: !14, size: 128, elements: !18)
!14 = !DIDerivedType(tag: DW_TAG_typedef, name: "s32_input_t", file: !5, line: 11, baseType: !15)
!15 = !DICompositeType(tag: DW_TAG_array_type, baseType: !4, size: 128, flags: DIFlagVector, elements: !16)
!16 = !{!17}
!17 = !DISubrange(count: 3)
!18 = !{!19}
!19 = !DISubrange(count: 1)
!20 = !DIGlobalVariableExpression(var: !21, expr: !DIExpression())
!21 = distinct !DIGlobalVariable(name: "shared_weight", scope: !9, file: !5, line: 36, type: !22, isLocal: true, isDefinition: true)
!22 = !DICompositeType(tag: DW_TAG_array_type, baseType: !23, size: 1024, elements: !18)
!23 = !DIDerivedType(tag: DW_TAG_typedef, name: "s32_weight_t", file: !5, line: 9, baseType: !24)
!24 = !DICompositeType(tag: DW_TAG_array_type, baseType: !4, size: 1024, flags: DIFlagVector, elements: !25)
!25 = !{!26}
!26 = !DISubrange(count: 18)
!27 = !{i32 1, !"amdhsa_code_object_version", i32 600}
!28 = !{i32 1, !"amdgpu_printf_kind", !"hostcall"}
!29 = !{i32 2, !"Debug Info Version", i32 3}
!30 = !{i32 1, !"wchar_size", i32 4}
!31 = !{i32 128, i32 1, i32 1}

; Check that a new DISubprogram got created during cloning for each of the specializations.
;.
; CHECK: attributes #[[ATTR0]] = { "amdgpu-wavegroup-enable" }
; CHECK: attributes #[[ATTR1:[0-9]+]] = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
; CHECK: attributes #[[ATTR2:[0-9]+]] = { "amdgpu-wavegroup-enable" "amdgpu-wavegroup-rank-function" }
; CHECK: attributes #[[ATTR3:[0-9]+]] = { convergent nounwind }
;.
; CHECK: [[META0:![0-9]+]] = !{i32 1, !"amdhsa_code_object_version", i32 600}
; CHECK: [[META1:![0-9]+]] = !{i32 1, !"amdgpu_printf_kind", !"hostcall"}
; CHECK: [[META2:![0-9]+]] = !{i32 2, !"Debug Info Version", i32 3}
; CHECK: [[META3:![0-9]+]] = !{i32 1, !"wchar_size", i32 4}
; CHECK: [[DBG4]] = distinct !DISubprogram(name: "test_kernel", scope: [[META5:![0-9]+]], file: [[META5]], line: 29, type: [[META6:![0-9]+]], scopeLine: 30, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: [[META8:![0-9]+]], retainedNodes: [[META30:![0-9]+]])
; CHECK: [[META5]] = !DIFile(filename: "{{.*}}test\\CodeGen\\AMDGPU\\small_example_1.cpp", directory: {{.*}})
; CHECK: [[META6]] = !DISubroutineType(types: [[META7:![0-9]+]])
; CHECK: [[META7]] = !{null}
; CHECK: [[META8]] = distinct !DICompileUnit(language: DW_LANG_C_plus_plus_14, file: [[META9:![0-9]+]], producer: "{{.*}}clang version {{.*}}", isOptimized: false, runtimeVersion: 0, emissionKind: FullDebug, retainedTypes: [[META10:![0-9]+]], globals: [[META13:![0-9]+]], splitDebugInlining: false, nameTableKind: None)
; CHECK: [[META9]] = !DIFile(filename: "{{.*}}D:\\develop\\llvm-project-C\\llvm\\test\\CodeGen\\AMDGPU\\<stdin>", directory: {{.*}})
; CHECK: [[META10]] = !{[[META11:![0-9]+]], [[META12:![0-9]+]]}
; CHECK: [[META11]] = !DIBasicType(name: "int", size: 32, encoding: DW_ATE_signed)
; CHECK: [[META12]] = !DIDerivedType(tag: DW_TAG_typedef, name: "s32_t", file: [[META5]], line: 2, baseType: [[META11]])
; CHECK: [[META13]] = !{[[META14:![0-9]+]], [[META23:![0-9]+]]}
; CHECK: [[META14]] = !DIGlobalVariableExpression(var: [[META15:![0-9]+]], expr: !DIExpression())
; CHECK: [[META15]] = distinct !DIGlobalVariable(name: "shared_input", scope: [[DBG4]], file: [[META5]], line: 35, type: [[META16:![0-9]+]], isLocal: true, isDefinition: true)
; CHECK: [[META16]] = !DICompositeType(tag: DW_TAG_array_type, baseType: [[META17:![0-9]+]], size: 128, elements: [[META21:![0-9]+]])
; CHECK: [[META17]] = !DIDerivedType(tag: DW_TAG_typedef, name: "s32_input_t", file: [[META5]], line: 11, baseType: [[META18:![0-9]+]])
; CHECK: [[META18]] = !DICompositeType(tag: DW_TAG_array_type, baseType: [[META12]], size: 128, flags: DIFlagVector, elements: [[META19:![0-9]+]])
; CHECK: [[META19]] = !{[[META20:![0-9]+]]}
; CHECK: [[META20]] = !DISubrange(count: 3)
; CHECK: [[META21]] = !{[[META22:![0-9]+]]}
; CHECK: [[META22]] = !DISubrange(count: 1)
; CHECK: [[META23]] = !DIGlobalVariableExpression(var: [[META24:![0-9]+]], expr: !DIExpression())
; CHECK: [[META24]] = distinct !DIGlobalVariable(name: "shared_weight", scope: [[DBG4]], file: [[META5]], line: 36, type: [[META25:![0-9]+]], isLocal: true, isDefinition: true)
; CHECK: [[META25]] = !DICompositeType(tag: DW_TAG_array_type, baseType: [[META26:![0-9]+]], size: 1024, elements: [[META21]])
; CHECK: [[META26]] = !DIDerivedType(tag: DW_TAG_typedef, name: "s32_weight_t", file: [[META5]], line: 9, baseType: [[META27:![0-9]+]])
; CHECK: [[META27]] = !DICompositeType(tag: DW_TAG_array_type, baseType: [[META12]], size: 1024, flags: DIFlagVector, elements: [[META28:![0-9]+]])
; CHECK: [[META28]] = !{[[META29:![0-9]+]]}
; CHECK: [[META29]] = !DISubrange(count: 18)
; CHECK: [[META30]] = !{}
; CHECK: [[META31]] = !{i32 128, i32 1, i32 1}
; CHECK: [[META32:![0-9]+]] = distinct !DISubprogram(name: "test_kernel", linkageName: "test_kernel.rank_0_1", scope: [[META5]], file: [[META5]], line: 29, type: [[META6]], scopeLine: 30, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: [[META8]], retainedNodes: [[META30]])
; CHECK: [[META33:![0-9]+]] = distinct !DISubprogram(name: "test_kernel", linkageName: "test_kernel.rank_2_3_4_5_6_7", scope: [[META5]], file: [[META5]], line: 29, type: [[META6]], scopeLine: 30, flags: DIFlagPrototyped, spFlags: DISPFlagDefinition, unit: [[META8]], retainedNodes: [[META30]])
; CHECK: [[META34:![0-9]+]] = !{[[META35:![0-9]+]]}
; CHECK: [[META35]] = !{i64 1, i1 false}
;.
