; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --include-generated-funcs --version 5
; RUN: opt -mtriple=amdgcn-amd-amdhsa -verify-each -passes=amdgpu-rank-specialization,instcombine,simplifycfg -S -o - %s | FileCheck --check-prefixes=CHECK %s

target datalayout = "A5"

; Dummy function declarations to improve test readability/bloat.
declare void @dummy_common()
declare void @dummy_rank1_a()
declare void @dummy_rank1_b()

define amdgpu_kernel void @test_kernel_1() local_unnamed_addr "amdgpu-wavegroup-enable" {
entry:
  %0 = call i32 @llvm.amdgcn.wave.id.in.wavegroup()
  br label %for.cond

for.cond:                                         ; preds = %if.end, %entry
  %i.0 = phi i32 [ 0, %entry ], [ %inc, %if.end ]
  call void @dummy_common()
  %cmp = icmp samesign ult i32 %i.0, 2
  br i1 %cmp, label %for.body, label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.cond
  %cmp4 = icmp eq i32 %0, 1
  br i1 %cmp4, label %if.then5, label %if.end7

for.body:                                         ; preds = %for.cond
  %cmp2 = icmp eq i32 %0, 1
  br i1 %cmp2, label %if.then, label %if.end

if.then:                                          ; preds = %for.body
  call void @dummy_rank1_a()
  br label %if.end

if.end:                                           ; preds = %if.then, %for.body
  %inc = add nuw nsw i32 %i.0, 1
  br label %for.cond

if.then5:                                         ; preds = %for.cond.cleanup
  call void @dummy_rank1_b()
  br label %if.end7

if.end7:                                          ; preds = %if.then5, %for.cond.cleanup
  ret void
}

; This test makes sure the no-rank-specialization attribute successfully prevents the optimization
; from running on the previous kernel

define amdgpu_kernel void @test_kernel_1_disabled() local_unnamed_addr "amdgpu-wavegroup-enable" "amdgpu-no-rank-specialization" {
entry:
  %0 = call i32 @llvm.amdgcn.wave.id.in.wavegroup()
  br label %for.cond

for.cond:                                         ; preds = %if.end, %entry
  %i.0 = phi i32 [ 0, %entry ], [ %inc, %if.end ]
  call void @dummy_common()
  %cmp = icmp samesign ult i32 %i.0, 2
  br i1 %cmp, label %for.body, label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.cond
  %cmp4 = icmp eq i32 %0, 1
  br i1 %cmp4, label %if.then5, label %if.end7

for.body:                                         ; preds = %for.cond
  %cmp2 = icmp eq i32 %0, 1
  br i1 %cmp2, label %if.then, label %if.end

if.then:                                          ; preds = %for.body
  call void @dummy_rank1_a()
  br label %if.end

if.end:                                           ; preds = %if.then, %for.body
  %inc = add nuw nsw i32 %i.0, 1
  br label %for.cond

if.then5:                                         ; preds = %for.cond.cleanup
  call void @dummy_rank1_b()
  br label %if.end7

if.end7:                                          ; preds = %if.then5, %for.cond.cleanup
  ret void
}

declare void @dummy_rank0_a()
declare void @dummy_ranks16_a()

define amdgpu_kernel void @test_kernel_2() local_unnamed_addr "amdgpu-wavegroup-enable" {
entry:
  %0 = call i32 @llvm.amdgcn.wave.id.in.wavegroup()
  br label %for.cond

for.cond:                                         ; preds = %if.end, %entry
  %i.0 = phi i32 [ 0, %entry ], [ %inc, %if.end ]
  %cmp = icmp samesign ult i32 %i.0, 2
  br i1 %cmp, label %for.body, label %for.cond10

for.body:                                         ; preds = %for.cond
  switch i32 %0, label %if.end [
  i32 6, label %if.then
  i32 1, label %if.then
  ]

if.then:                                          ; preds = %for.body, %for.body
  call void @dummy_ranks16_a()
  br label %if.end

if.end:                                           ; preds = %for.body, %if.then
  call void @dummy_common()
  %inc = add nuw nsw i32 %i.0, 1
  br label %for.cond

for.cond10:                                       ; preds = %for.cond, %for.inc35
  %j.0 = phi i32 [ %inc36, %for.inc35 ], [ 0, %for.cond ]
  call void @dummy_common()
  %cmp11 = icmp samesign ult i32 %j.0, 2
  br i1 %cmp11, label %for.cond16, label %for.cond.cleanup12

for.cond.cleanup12:                               ; preds = %for.cond10
  ret void

for.cond16:                                       ; preds = %for.cond10, %for.inc26
  %k15.0 = phi i32 [ %inc27, %for.inc26 ], [ 0, %for.cond10 ]
  %cmp17 = icmp samesign ult i32 %k15.0, 3
  br i1 %cmp17, label %for.body19, label %for.cond.cleanup18

for.cond.cleanup18:                               ; preds = %for.cond16
  %cmp29 = icmp eq i32 %0, 1
  br i1 %cmp29, label %if.then30, label %for.inc35

for.body19:                                       ; preds = %for.cond16
  %cmp20 = icmp eq i32 %0, 0
  br i1 %cmp20, label %if.then21, label %for.inc26

if.then21:                                        ; preds = %for.body19
  call void @dummy_rank0_a()
  br label %for.inc26

for.inc26:                                        ; preds = %for.body19, %if.then21
  %inc27 = add nuw nsw i32 %k15.0, 1
  br label %for.cond16

if.then30:                                        ; preds = %for.cond.cleanup18
  call void @dummy_rank1_a()
  br label %for.inc35

for.inc35:                                        ; preds = %for.cond.cleanup18, %if.then30
  %inc36 = add nuw nsw i32 %j.0, 1
  br label %for.cond10
}

declare void @dummy_rank6_a()
declare void @dummy_ranks013_a()
declare void @dummy_ranks2457_a()

define amdgpu_kernel void @test_kernel_3() local_unnamed_addr "amdgpu-wavegroup-enable" {
entry:
  %0 = call i32 @llvm.amdgcn.wave.id.in.wavegroup()
  br label %for.cond

for.cond:                                         ; preds = %for.inc40, %entry
  %i.0 = phi i32 [ 0, %entry ], [ %inc41, %for.inc40 ]
  %cmp = icmp samesign ult i32 %i.0, 10
  br i1 %cmp, label %for.body, label %for.cond.cleanup

for.cond.cleanup:                                 ; preds = %for.cond
  ret void

for.body:                                         ; preds = %for.cond
  switch i32 %0, label %if.else34 [
  i32 3, label %if.then
  i32 1, label %if.then
  i32 0, label %if.then
  i32 6, label %if.then31
  ]

if.then:                                          ; preds = %for.body, %for.body, %for.body
  call void @dummy_ranks013_a()
  br label %for.cond11

for.cond11:                                       ; preds = %for.inc27, %if.then
  %j.0 = phi i32 [ 0, %if.then ], [ %inc28, %for.inc27 ]
  %cmp12 = icmp samesign ult i32 %j.0, 2
  br i1 %cmp12, label %for.cond15, label %for.inc40

for.cond15:                                       ; preds = %for.cond11, %for.inc
  %k.0 = phi i32 [ %inc, %for.inc ], [ 0, %for.cond11 ]
  %cmp16 = icmp samesign ult i32 %k.0, 3
  br i1 %cmp16, label %for.body18, label %for.cond.cleanup17

for.cond.cleanup17:                               ; preds = %for.cond15
  %cmp8 = icmp eq i32 %0, 1
  br i1 %cmp8, label %if.then22, label %for.inc27

for.body18:                                       ; preds = %for.cond15
  %cmp7 = icmp eq i32 %0, 0
  br i1 %cmp7, label %if.then20, label %for.inc

if.then20:                                        ; preds = %for.body18
  call void @dummy_rank0_a()
  br label %for.inc

for.inc:                                          ; preds = %for.body18, %if.then20
  %inc = add nuw nsw i32 %k.0, 1
  br label %for.cond15

if.then22:                                        ; preds = %for.cond.cleanup17
  call void @dummy_rank1_a()
  br label %for.inc27

for.inc27:                                        ; preds = %for.cond.cleanup17, %if.then22
  %inc28 = add nuw nsw i32 %j.0, 1
  br label %for.cond11

if.then31:                                        ; preds = %for.body
  call void @dummy_rank6_a()
  br label %for.inc40

if.else34:                                        ; preds = %for.body
  call void @dummy_ranks2457_a()
  br label %for.inc40

for.inc40:                                        ; preds = %for.cond11, %if.else34, %if.then31
  call void @dummy_common()
  %inc41 = add nuw nsw i32 %i.0, 1
  br label %for.cond
}

declare void @dummy_ranks0167_a()
declare void @dummy_ranks2345_a()

define amdgpu_kernel void @test_kernel_4() local_unnamed_addr "amdgpu-wavegroup-enable" {
entry:
  %0 = call i32 @llvm.amdgcn.wave.id.in.wavegroup()
  br label %for.body

for.cond.cleanup:                                 ; preds = %if.end13
  ret void

for.body:                                         ; preds = %entry, %if.end13
  %i.027 = phi i32 [ 0, %entry ], [ %inc15, %if.end13 ]
  %lt.2 = icmp ult i32 %0, 2
  %gt.5 = icmp ugt i32 %0, 5
  %or.cond = or i1 %lt.2, %gt.5
  br i1 %or.cond, label %for.body5, label %if.else

for.body5:                                        ; preds = %for.body
  call void @dummy_ranks0167_a()
  br label %if.end13

if.else:                                          ; preds = %for.body
  call void @dummy_ranks2345_a()
  br label %if.end13

if.end13:                                         ; preds = %for.body5, %if.else
  call void @dummy_common()
  %inc15 = add nuw nsw i32 %i.027, 1
  %exitcond28 = icmp eq i32 %inc15, 10
  br i1 %exitcond28, label %for.cond.cleanup, label %for.body
}

declare void @dummy_ranks57_a()
declare void @dummy_ranks012346_a()

; The test case below does not trigger the pass because the current implementation doesn't
; handle the %tobool arg of %or.cond. TODO: Explore handling this more complex case.

define amdgpu_kernel void @test_kernel_5() local_unnamed_addr "amdgpu-wavegroup-enable" {
entry:
  %0 = call i32 @llvm.amdgcn.wave.id.in.wavegroup()
  br label %for.body

for.cond.cleanup:                                 ; preds = %if.end13
  ret void

for.body:                                         ; preds = %entry, %if.end13
  %i.027 = phi i32 [ 0, %entry ], [ %inc15, %if.end13 ]
  %rem = and i32 %0, 1
  %tobool = icmp ne i32 %rem, 0
  %cmp1 = icmp ugt i32 %0, 4
  %or.cond = and i1 %cmp1, %tobool
  br i1 %or.cond, label %for.body5, label %if.else

for.body5:                                        ; preds = %for.body, %for.body5
  %j.026 = phi i32 [ %inc, %for.body5 ], [ 0, %for.body ]
  call void @dummy_ranks57_a()
  %inc = add nuw nsw i32 %j.026, 1
  %exitcond = icmp eq i32 %inc, 5
  br i1 %exitcond, label %if.end13, label %for.body5

if.else:                                          ; preds = %for.body
  call void @dummy_ranks012346_a()
  br i1 %tobool, label %if.end13, label %if.then8

if.then8:                                         ; preds = %if.else
  br label %if.end13

if.end13:                                         ; preds = %for.body5, %if.else, %if.then8
  call void @dummy_common()
  %inc15 = add nuw nsw i32 %i.027, 1
  %exitcond28 = icmp eq i32 %inc15, 10
  br i1 %exitcond28, label %for.cond.cleanup, label %for.body
}

@.str = private unnamed_addr constant [4 x i8] c"%d\0A\00", align 1

; The intent of this test case is to show an example where %wid feeds an icmp, but
; that icmp doesn't feed a conditional branch, so we shouldn't specialize anything.
define amdgpu_kernel void @test_kernel_6(i32* %base) "amdgpu-wavegroup-enable" {
entry:
  %wid = call i32 @llvm.amdgcn.wave.id.in.wavegroup()
  %cmp = icmp eq i32 %wid, 0
  %ptr0 = getelementptr inbounds i32, i32* %base, i32 0
  %ptr4 = getelementptr inbounds i32, i32* %base, i32 4
  %selptr = select i1 %cmp, i32* %ptr0, i32* %ptr4
  %val = load i32, i32* %selptr, align 4
  %fmt = getelementptr inbounds [4 x i8], [4 x i8]* @.str, i32 0, i32 0
  call i32 (i8*, ...) @dummy_common(i8* %fmt, i32 %val)
  ret void
}

declare void @dummy_ranks01_a()
declare void @dummy_ranks234567_a()

; test_kernel_7 generates two clones. In each one, although %wid is used in icmp %cmp2,
; this i1 doesn't feed a conditional branch. The result is that we can't replace this
; i1 with a constant true/false in either kernel.

define amdgpu_kernel void @test_kernel_7(i32* %base) "amdgpu-wavegroup-enable" {
entry:
  %wid = call i32 @llvm.amdgcn.wave.id.in.wavegroup()
  %cmp1 = icmp uge i32 %wid, 2
  br i1 %cmp1, label %if, label %else

if:
  call i32 @dummy_ranks234567_a()
  br label %end

else:
  call i32 @dummy_ranks01_a()
  br label %end

end:
  %ptr0 = getelementptr inbounds i32, i32* %base, i32 0
  %ptr4 = getelementptr inbounds i32, i32* %base, i32 4
  %cmp2 = icmp eq i32 %wid, 0
  %selptr = select i1 %cmp2, i32* %ptr0, i32* %ptr4
  %val = load i32, i32* %selptr, align 4
  %fmt = getelementptr inbounds [4 x i8], [4 x i8]* @.str, i32 0, i32 0
  call i32 (i8*, ...) @dummy_common(i8* %fmt, i32 %val)
  ret void
}

; This test case is similar to test_case_4, but the binary op (%or.cond1 in this case) feeds
; another binary op rather than a conditional branch.

declare void @dummy_ranks17_a()
declare void @dummy_ranks023456_a()

define amdgpu_kernel void @test_kernel_8() local_unnamed_addr "amdgpu-wavegroup-enable" {
entry:
  %0 = call i32 @llvm.amdgcn.wave.id.in.wavegroup()
  br label %for.body

for.cond.cleanup:                                 ; preds = %if.end13
  ret void

for.body:                                         ; preds = %entry, %if.end13
  %i.027 = phi i32 [ 0, %entry ], [ %inc15, %if.end13 ]
  %lt.2 = icmp ult i32 %0, 2
  %gt.5 = icmp ugt i32 %0, 5
  %or.cond1 = or i1 %lt.2, %gt.5
  %odds = and i32 %0, 1
  %as_i1 = icmp ne i32 %odds, 0
  %or.cond2 = and i1 %or.cond1, %as_i1
  br i1 %or.cond2, label %for.body5, label %if.else

for.body5:                                        ; preds = %for.body
  call void @dummy_ranks17_a()
  br label %if.end13

if.else:                                          ; preds = %for.body
  call void @dummy_ranks023456_a()
  br label %if.end13

if.end13:                                         ; preds = %for.body5, %if.else
  call void @dummy_common()
  %inc15 = add nuw nsw i32 %i.027, 1
  %exitcond28 = icmp eq i32 %inc15, 10
  br i1 %exitcond28, label %for.cond.cleanup, label %for.body
}

declare void @dummy_ranks23_a()
declare void @dummy_ranks014567_a()

define amdgpu_kernel void @test_kernel_9(i32* %base) "amdgpu-wavegroup-enable" {
entry:
  %wid = call i32 @llvm.amdgcn.wave.id.in.wavegroup()
  %cmp1 = icmp uge i32 %wid, 2
  %mulwid = udiv i32 %wid, 4
  %and = icmp eq i32 %mulwid, 1
  %xor = xor i1 %cmp1, %and
  br i1 %xor, label %if, label %else

if:
  call i32 @dummy_ranks23_a()
  br label %end

else:
  call i32 @dummy_ranks014567_a()
  br label %end

end:
  call i32 (i1, ...) @dummy_common(i1 %xor)
  ret void
}

declare void @dummy_ranks0123_a()
declare void @dummy_ranks4567_a()

define amdgpu_kernel void @test_kernel_10() local_unnamed_addr "amdgpu-wavegroup-enable" {
entry:
  %0 = call i32 @llvm.amdgcn.wave.id.in.wavegroup()
  br label %for.body

for.cond.cleanup:                                 ; preds = %if.end13
  ret void

for.body:                                         ; preds = %entry, %if.end13
  %i.027 = phi i32 [ 0, %entry ], [ %inc15, %if.end13 ]
  %f0 = sitofp i32 %0 to float
  %div = fdiv float %f0, 4.0
  %div_int = fptosi float %div to i32
  %bool = icmp ne i32 %div_int, 0
  br i1 %bool, label %for.body5, label %if.else

for.body5:                                        ; preds = %for.body
  call void @dummy_ranks0123_a()
  br label %if.end13

if.else:                                          ; preds = %for.body
  call void @dummy_ranks4567_a()
  br label %if.end13

if.end13:                                         ; preds = %for.body5, %if.else
  call void @dummy_common()
  %inc15 = add nuw nsw i32 %i.027, 1
  %exitcond28 = icmp eq i32 %inc15, 10
  br i1 %exitcond28, label %for.cond.cleanup, label %for.body
}

; CHECK-LABEL: define amdgpu_kernel void @test_kernel_1(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR0:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 0, ptr nonnull @test_kernel_1.rank_0_2_3_4_5_6_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 1, ptr nonnull @test_kernel_1.rank_1)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 2, ptr nonnull @test_kernel_1.rank_0_2_3_4_5_6_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 3, ptr nonnull @test_kernel_1.rank_0_2_3_4_5_6_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 4, ptr nonnull @test_kernel_1.rank_0_2_3_4_5_6_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 5, ptr nonnull @test_kernel_1.rank_0_2_3_4_5_6_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 6, ptr nonnull @test_kernel_1.rank_0_2_3_4_5_6_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 7, ptr nonnull @test_kernel_1.rank_0_2_3_4_5_6_7)
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define amdgpu_kernel void @test_kernel_1_disabled(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR1:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 @llvm.amdgcn.wave.id.in.wavegroup()
; CHECK-NEXT:    br label %[[FOR_COND:.*]]
; CHECK:       [[FOR_COND]]:
; CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[INC:%.*]], %[[IF_END:.*]] ]
; CHECK-NEXT:    call void @dummy_common()
; CHECK-NEXT:    [[CMP:%.*]] = icmp samesign ult i32 [[I_0]], 2
; CHECK-NEXT:    br i1 [[CMP]], label %[[FOR_BODY:.*]], label %[[FOR_COND_CLEANUP:.*]]
; CHECK:       [[FOR_COND_CLEANUP]]:
; CHECK-NEXT:    [[CMP4:%.*]] = icmp eq i32 [[TMP0]], 1
; CHECK-NEXT:    br i1 [[CMP4]], label %[[IF_THEN5:.*]], label %[[IF_END7:.*]]
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[CMP2:%.*]] = icmp eq i32 [[TMP0]], 1
; CHECK-NEXT:    br i1 [[CMP2]], label %[[IF_THEN:.*]], label %[[IF_END]]
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    call void @dummy_rank1_a()
; CHECK-NEXT:    br label %[[IF_END]]
; CHECK:       [[IF_END]]:
; CHECK-NEXT:    [[INC]] = add nuw nsw i32 [[I_0]], 1
; CHECK-NEXT:    br label %[[FOR_COND]]
; CHECK:       [[IF_THEN5]]:
; CHECK-NEXT:    call void @dummy_rank1_b()
; CHECK-NEXT:    br label %[[IF_END7]]
; CHECK:       [[IF_END7]]:
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define amdgpu_kernel void @test_kernel_2(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 0, ptr nonnull @test_kernel_2.rank_0)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 1, ptr nonnull @test_kernel_2.rank_1)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 2, ptr nonnull @test_kernel_2.rank_2_3_4_5_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 3, ptr nonnull @test_kernel_2.rank_2_3_4_5_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 4, ptr nonnull @test_kernel_2.rank_2_3_4_5_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 5, ptr nonnull @test_kernel_2.rank_2_3_4_5_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 6, ptr nonnull @test_kernel_2.rank_6)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 7, ptr nonnull @test_kernel_2.rank_2_3_4_5_7)
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define amdgpu_kernel void @test_kernel_3(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 0, ptr nonnull @test_kernel_3.rank_0)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 1, ptr nonnull @test_kernel_3.rank_1)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 2, ptr nonnull @test_kernel_3.rank_2_4_5_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 3, ptr nonnull @test_kernel_3.rank_3)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 4, ptr nonnull @test_kernel_3.rank_2_4_5_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 5, ptr nonnull @test_kernel_3.rank_2_4_5_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 6, ptr nonnull @test_kernel_3.rank_6)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 7, ptr nonnull @test_kernel_3.rank_2_4_5_7)
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define amdgpu_kernel void @test_kernel_4(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 0, ptr nonnull @test_kernel_4.rank_0_1_6_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 1, ptr nonnull @test_kernel_4.rank_0_1_6_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 2, ptr nonnull @test_kernel_4.rank_2_3_4_5)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 3, ptr nonnull @test_kernel_4.rank_2_3_4_5)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 4, ptr nonnull @test_kernel_4.rank_2_3_4_5)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 5, ptr nonnull @test_kernel_4.rank_2_3_4_5)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 6, ptr nonnull @test_kernel_4.rank_0_1_6_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 7, ptr nonnull @test_kernel_4.rank_0_1_6_7)
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define amdgpu_kernel void @test_kernel_5(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 0, ptr nonnull @test_kernel_5.rank_0_2_4_6)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 1, ptr nonnull @test_kernel_5.rank_1_3)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 2, ptr nonnull @test_kernel_5.rank_0_2_4_6)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 3, ptr nonnull @test_kernel_5.rank_1_3)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 4, ptr nonnull @test_kernel_5.rank_0_2_4_6)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 5, ptr nonnull @test_kernel_5.rank_5_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 6, ptr nonnull @test_kernel_5.rank_0_2_4_6)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 7, ptr nonnull @test_kernel_5.rank_5_7)
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define amdgpu_kernel void @test_kernel_6(
; CHECK-SAME: ptr [[BASE:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[WID:%.*]] = call i32 @llvm.amdgcn.wave.id.in.wavegroup()
; CHECK-NEXT:    [[CMP:%.*]] = icmp eq i32 [[WID]], 0
; CHECK-NEXT:    [[SELPTR_IDX:%.*]] = select i1 [[CMP]], i64 0, i64 16
; CHECK-NEXT:    [[SELPTR:%.*]] = getelementptr inbounds nuw i8, ptr [[BASE]], i64 [[SELPTR_IDX]]
; CHECK-NEXT:    [[VAL:%.*]] = load i32, ptr [[SELPTR]], align 4
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 (ptr, ...) @dummy_common(ptr nonnull @.str, i32 [[VAL]])
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define amdgpu_kernel void @test_kernel_7(
; CHECK-SAME: ptr [[BASE:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 0, ptr nonnull @test_kernel_7.rank_0_1)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 1, ptr nonnull @test_kernel_7.rank_0_1)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 2, ptr nonnull @test_kernel_7.rank_2_3_4_5_6_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 3, ptr nonnull @test_kernel_7.rank_2_3_4_5_6_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 4, ptr nonnull @test_kernel_7.rank_2_3_4_5_6_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 5, ptr nonnull @test_kernel_7.rank_2_3_4_5_6_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 6, ptr nonnull @test_kernel_7.rank_2_3_4_5_6_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 7, ptr nonnull @test_kernel_7.rank_2_3_4_5_6_7)
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define amdgpu_kernel void @test_kernel_8(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 0, ptr nonnull @test_kernel_8.rank_0_2_3_4_5_6)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 1, ptr nonnull @test_kernel_8.rank_1_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 2, ptr nonnull @test_kernel_8.rank_0_2_3_4_5_6)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 3, ptr nonnull @test_kernel_8.rank_0_2_3_4_5_6)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 4, ptr nonnull @test_kernel_8.rank_0_2_3_4_5_6)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 5, ptr nonnull @test_kernel_8.rank_0_2_3_4_5_6)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 6, ptr nonnull @test_kernel_8.rank_0_2_3_4_5_6)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 7, ptr nonnull @test_kernel_8.rank_1_7)
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define amdgpu_kernel void @test_kernel_9(
; CHECK-SAME: ptr [[BASE:%.*]]) #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 0, ptr nonnull @test_kernel_9.rank_0_1_4_5_6_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 1, ptr nonnull @test_kernel_9.rank_0_1_4_5_6_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 2, ptr nonnull @test_kernel_9.rank_2_3)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 3, ptr nonnull @test_kernel_9.rank_2_3)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 4, ptr nonnull @test_kernel_9.rank_0_1_4_5_6_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 5, ptr nonnull @test_kernel_9.rank_0_1_4_5_6_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 6, ptr nonnull @test_kernel_9.rank_0_1_4_5_6_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 7, ptr nonnull @test_kernel_9.rank_0_1_4_5_6_7)
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define amdgpu_kernel void @test_kernel_10(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR0]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 0, ptr nonnull @test_kernel_10.rank_0_1_2_3)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 1, ptr nonnull @test_kernel_10.rank_0_1_2_3)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 2, ptr nonnull @test_kernel_10.rank_0_1_2_3)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 3, ptr nonnull @test_kernel_10.rank_0_1_2_3)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 4, ptr nonnull @test_kernel_10.rank_4_5_6_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 5, ptr nonnull @test_kernel_10.rank_4_5_6_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 6, ptr nonnull @test_kernel_10.rank_4_5_6_7)
; CHECK-NEXT:    call void @llvm.amdgcn.wavegroup.rank.p0(i32 7, ptr nonnull @test_kernel_10.rank_4_5_6_7)
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define internal amdgpu_kernel void @test_kernel_1.rank_0_2_3_4_5_6_7(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR3:[0-9]+]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_COND:.*]]
; CHECK:       [[FOR_COND]]:
; CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[INC:%.*]], %[[IF_END:.*]] ]
; CHECK-NEXT:    call void @dummy_common()
; CHECK-NEXT:    [[CMP:%.*]] = icmp samesign ult i32 [[I_0]], 2
; CHECK-NEXT:    br i1 [[CMP]], label %[[IF_END]], label %[[IF_END7:.*]]
; CHECK:       [[IF_END]]:
; CHECK-NEXT:    [[INC]] = add nuw nsw i32 [[I_0]], 1
; CHECK-NEXT:    br label %[[FOR_COND]]
; CHECK:       [[IF_END7]]:
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define internal amdgpu_kernel void @test_kernel_1.rank_1(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_COND:.*]]
; CHECK:       [[FOR_COND]]:
; CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[INC:%.*]], %[[IF_THEN:.*]] ]
; CHECK-NEXT:    call void @dummy_common()
; CHECK-NEXT:    [[CMP:%.*]] = icmp samesign ult i32 [[I_0]], 2
; CHECK-NEXT:    br i1 [[CMP]], label %[[IF_THEN]], label %[[IF_THEN5:.*]]
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    call void @dummy_rank1_a()
; CHECK-NEXT:    [[INC]] = add nuw nsw i32 [[I_0]], 1
; CHECK-NEXT:    br label %[[FOR_COND]]
; CHECK:       [[IF_THEN5]]:
; CHECK-NEXT:    call void @dummy_rank1_b()
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define internal amdgpu_kernel void @test_kernel_2.rank_2_3_4_5_7(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_COND:.*]]
; CHECK:       [[FOR_COND]]:
; CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[INC:%.*]], %[[IF_END:.*]] ]
; CHECK-NEXT:    [[CMP:%.*]] = icmp samesign ult i32 [[I_0]], 2
; CHECK-NEXT:    br i1 [[CMP]], label %[[IF_END]], label %[[FOR_COND10:.*]]
; CHECK:       [[IF_END]]:
; CHECK-NEXT:    call void @dummy_common()
; CHECK-NEXT:    [[INC]] = add nuw nsw i32 [[I_0]], 1
; CHECK-NEXT:    br label %[[FOR_COND]]
; CHECK:       [[FOR_COND10]]:
; CHECK-NEXT:    [[J_0:%.*]] = phi i32 [ [[INC36:%.*]], %[[FOR_INC35:.*]] ], [ 0, %[[FOR_COND]] ]
; CHECK-NEXT:    call void @dummy_common()
; CHECK-NEXT:    [[CMP11:%.*]] = icmp samesign ult i32 [[J_0]], 2
; CHECK-NEXT:    br i1 [[CMP11]], label %[[FOR_COND16:.*]], label %[[FOR_COND_CLEANUP12:.*]]
; CHECK:       [[FOR_COND_CLEANUP12]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_COND16]]:
; CHECK-NEXT:    [[K15_0:%.*]] = phi i32 [ [[INC27:%.*]], %[[FOR_INC26:.*]] ], [ 0, %[[FOR_COND10]] ]
; CHECK-NEXT:    [[CMP17:%.*]] = icmp samesign ult i32 [[K15_0]], 3
; CHECK-NEXT:    br i1 [[CMP17]], label %[[FOR_INC26]], label %[[FOR_INC35]]
; CHECK:       [[FOR_INC26]]:
; CHECK-NEXT:    [[INC27]] = add nuw nsw i32 [[K15_0]], 1
; CHECK-NEXT:    br label %[[FOR_COND16]]
; CHECK:       [[FOR_INC35]]:
; CHECK-NEXT:    [[INC36]] = add nuw nsw i32 [[J_0]], 1
; CHECK-NEXT:    br label %[[FOR_COND10]]
;
;
; CHECK-LABEL: define internal amdgpu_kernel void @test_kernel_2.rank_6(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_COND:.*]]
; CHECK:       [[FOR_COND]]:
; CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[INC:%.*]], %[[IF_THEN:.*]] ]
; CHECK-NEXT:    [[CMP:%.*]] = icmp samesign ult i32 [[I_0]], 2
; CHECK-NEXT:    br i1 [[CMP]], label %[[IF_THEN]], label %[[FOR_COND10:.*]]
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    call void @dummy_ranks16_a()
; CHECK-NEXT:    call void @dummy_common()
; CHECK-NEXT:    [[INC]] = add nuw nsw i32 [[I_0]], 1
; CHECK-NEXT:    br label %[[FOR_COND]]
; CHECK:       [[FOR_COND10]]:
; CHECK-NEXT:    [[J_0:%.*]] = phi i32 [ [[INC36:%.*]], %[[FOR_INC35:.*]] ], [ 0, %[[FOR_COND]] ]
; CHECK-NEXT:    call void @dummy_common()
; CHECK-NEXT:    [[CMP11:%.*]] = icmp samesign ult i32 [[J_0]], 2
; CHECK-NEXT:    br i1 [[CMP11]], label %[[FOR_COND16:.*]], label %[[FOR_COND_CLEANUP12:.*]]
; CHECK:       [[FOR_COND_CLEANUP12]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_COND16]]:
; CHECK-NEXT:    [[K15_0:%.*]] = phi i32 [ [[INC27:%.*]], %[[FOR_INC26:.*]] ], [ 0, %[[FOR_COND10]] ]
; CHECK-NEXT:    [[CMP17:%.*]] = icmp samesign ult i32 [[K15_0]], 3
; CHECK-NEXT:    br i1 [[CMP17]], label %[[FOR_INC26]], label %[[FOR_INC35]]
; CHECK:       [[FOR_INC26]]:
; CHECK-NEXT:    [[INC27]] = add nuw nsw i32 [[K15_0]], 1
; CHECK-NEXT:    br label %[[FOR_COND16]]
; CHECK:       [[FOR_INC35]]:
; CHECK-NEXT:    [[INC36]] = add nuw nsw i32 [[J_0]], 1
; CHECK-NEXT:    br label %[[FOR_COND10]]
;
;
; CHECK-LABEL: define internal amdgpu_kernel void @test_kernel_2.rank_1(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_COND:.*]]
; CHECK:       [[FOR_COND]]:
; CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[INC:%.*]], %[[IF_THEN:.*]] ]
; CHECK-NEXT:    [[CMP:%.*]] = icmp samesign ult i32 [[I_0]], 2
; CHECK-NEXT:    br i1 [[CMP]], label %[[IF_THEN]], label %[[FOR_COND10:.*]]
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    call void @dummy_ranks16_a()
; CHECK-NEXT:    call void @dummy_common()
; CHECK-NEXT:    [[INC]] = add nuw nsw i32 [[I_0]], 1
; CHECK-NEXT:    br label %[[FOR_COND]]
; CHECK:       [[FOR_COND10]]:
; CHECK-NEXT:    [[J_0:%.*]] = phi i32 [ [[INC36:%.*]], %[[IF_THEN30:.*]] ], [ 0, %[[FOR_COND]] ]
; CHECK-NEXT:    call void @dummy_common()
; CHECK-NEXT:    [[CMP11:%.*]] = icmp samesign ult i32 [[J_0]], 2
; CHECK-NEXT:    br i1 [[CMP11]], label %[[FOR_COND16:.*]], label %[[FOR_COND_CLEANUP12:.*]]
; CHECK:       [[FOR_COND_CLEANUP12]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_COND16]]:
; CHECK-NEXT:    [[K15_0:%.*]] = phi i32 [ [[INC27:%.*]], %[[FOR_INC26:.*]] ], [ 0, %[[FOR_COND10]] ]
; CHECK-NEXT:    [[CMP17:%.*]] = icmp samesign ult i32 [[K15_0]], 3
; CHECK-NEXT:    br i1 [[CMP17]], label %[[FOR_INC26]], label %[[IF_THEN30]]
; CHECK:       [[FOR_INC26]]:
; CHECK-NEXT:    [[INC27]] = add nuw nsw i32 [[K15_0]], 1
; CHECK-NEXT:    br label %[[FOR_COND16]]
; CHECK:       [[IF_THEN30]]:
; CHECK-NEXT:    call void @dummy_rank1_a()
; CHECK-NEXT:    [[INC36]] = add nuw nsw i32 [[J_0]], 1
; CHECK-NEXT:    br label %[[FOR_COND10]]
;
;
; CHECK-LABEL: define internal amdgpu_kernel void @test_kernel_2.rank_0(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_COND:.*]]
; CHECK:       [[FOR_COND]]:
; CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[INC:%.*]], %[[IF_END:.*]] ]
; CHECK-NEXT:    [[CMP:%.*]] = icmp samesign ult i32 [[I_0]], 2
; CHECK-NEXT:    br i1 [[CMP]], label %[[IF_END]], label %[[FOR_COND10:.*]]
; CHECK:       [[IF_END]]:
; CHECK-NEXT:    call void @dummy_common()
; CHECK-NEXT:    [[INC]] = add nuw nsw i32 [[I_0]], 1
; CHECK-NEXT:    br label %[[FOR_COND]]
; CHECK:       [[FOR_COND10]]:
; CHECK-NEXT:    [[J_0:%.*]] = phi i32 [ [[INC36:%.*]], %[[FOR_INC35:.*]] ], [ 0, %[[FOR_COND]] ]
; CHECK-NEXT:    call void @dummy_common()
; CHECK-NEXT:    [[CMP11:%.*]] = icmp samesign ult i32 [[J_0]], 2
; CHECK-NEXT:    br i1 [[CMP11]], label %[[FOR_COND16:.*]], label %[[FOR_COND_CLEANUP12:.*]]
; CHECK:       [[FOR_COND_CLEANUP12]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_COND16]]:
; CHECK-NEXT:    [[K15_0:%.*]] = phi i32 [ [[INC27:%.*]], %[[IF_THEN21:.*]] ], [ 0, %[[FOR_COND10]] ]
; CHECK-NEXT:    [[CMP17:%.*]] = icmp samesign ult i32 [[K15_0]], 3
; CHECK-NEXT:    br i1 [[CMP17]], label %[[IF_THEN21]], label %[[FOR_INC35]]
; CHECK:       [[IF_THEN21]]:
; CHECK-NEXT:    call void @dummy_rank0_a()
; CHECK-NEXT:    [[INC27]] = add nuw nsw i32 [[K15_0]], 1
; CHECK-NEXT:    br label %[[FOR_COND16]]
; CHECK:       [[FOR_INC35]]:
; CHECK-NEXT:    [[INC36]] = add nuw nsw i32 [[J_0]], 1
; CHECK-NEXT:    br label %[[FOR_COND10]]
;
;
; CHECK-LABEL: define internal amdgpu_kernel void @test_kernel_3.rank_2_4_5_7(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_COND:.*]]
; CHECK:       [[FOR_COND]]:
; CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[INC41:%.*]], %[[IF_ELSE34:.*]] ]
; CHECK-NEXT:    [[CMP:%.*]] = icmp samesign ult i32 [[I_0]], 10
; CHECK-NEXT:    br i1 [[CMP]], label %[[IF_ELSE34]], label %[[FOR_COND_CLEANUP:.*]]
; CHECK:       [[FOR_COND_CLEANUP]]:
; CHECK-NEXT:    ret void
; CHECK:       [[IF_ELSE34]]:
; CHECK-NEXT:    call void @dummy_ranks2457_a()
; CHECK-NEXT:    call void @dummy_common()
; CHECK-NEXT:    [[INC41]] = add nuw nsw i32 [[I_0]], 1
; CHECK-NEXT:    br label %[[FOR_COND]]
;
;
; CHECK-LABEL: define internal amdgpu_kernel void @test_kernel_3.rank_3(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_COND:.*]]
; CHECK:       [[FOR_COND]]:
; CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[INC41:%.*]], %[[FOR_INC40:.*]] ]
; CHECK-NEXT:    [[CMP:%.*]] = icmp samesign ult i32 [[I_0]], 10
; CHECK-NEXT:    br i1 [[CMP]], label %[[IF_THEN:.*]], label %[[FOR_COND_CLEANUP:.*]]
; CHECK:       [[FOR_COND_CLEANUP]]:
; CHECK-NEXT:    ret void
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    call void @dummy_ranks013_a()
; CHECK-NEXT:    br label %[[FOR_COND11:.*]]
; CHECK:       [[FOR_COND11]]:
; CHECK-NEXT:    [[J_0:%.*]] = phi i32 [ 0, %[[IF_THEN]] ], [ [[INC28:%.*]], %[[FOR_INC27:.*]] ]
; CHECK-NEXT:    [[CMP12:%.*]] = icmp samesign ult i32 [[J_0]], 2
; CHECK-NEXT:    br i1 [[CMP12]], label %[[FOR_COND15:.*]], label %[[FOR_INC40]]
; CHECK:       [[FOR_COND15]]:
; CHECK-NEXT:    [[K_0:%.*]] = phi i32 [ [[INC:%.*]], %[[FOR_INC:.*]] ], [ 0, %[[FOR_COND11]] ]
; CHECK-NEXT:    [[CMP16:%.*]] = icmp samesign ult i32 [[K_0]], 3
; CHECK-NEXT:    br i1 [[CMP16]], label %[[FOR_INC]], label %[[FOR_INC27]]
; CHECK:       [[FOR_INC]]:
; CHECK-NEXT:    [[INC]] = add nuw nsw i32 [[K_0]], 1
; CHECK-NEXT:    br label %[[FOR_COND15]]
; CHECK:       [[FOR_INC27]]:
; CHECK-NEXT:    [[INC28]] = add nuw nsw i32 [[J_0]], 1
; CHECK-NEXT:    br label %[[FOR_COND11]]
; CHECK:       [[FOR_INC40]]:
; CHECK-NEXT:    call void @dummy_common()
; CHECK-NEXT:    [[INC41]] = add nuw nsw i32 [[I_0]], 1
; CHECK-NEXT:    br label %[[FOR_COND]]
;
;
; CHECK-LABEL: define internal amdgpu_kernel void @test_kernel_3.rank_6(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_COND:.*]]
; CHECK:       [[FOR_COND]]:
; CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[INC41:%.*]], %[[IF_THEN31:.*]] ]
; CHECK-NEXT:    [[CMP:%.*]] = icmp samesign ult i32 [[I_0]], 10
; CHECK-NEXT:    br i1 [[CMP]], label %[[IF_THEN31]], label %[[FOR_COND_CLEANUP:.*]]
; CHECK:       [[FOR_COND_CLEANUP]]:
; CHECK-NEXT:    ret void
; CHECK:       [[IF_THEN31]]:
; CHECK-NEXT:    call void @dummy_rank6_a()
; CHECK-NEXT:    call void @dummy_common()
; CHECK-NEXT:    [[INC41]] = add nuw nsw i32 [[I_0]], 1
; CHECK-NEXT:    br label %[[FOR_COND]]
;
;
; CHECK-LABEL: define internal amdgpu_kernel void @test_kernel_3.rank_1(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_COND:.*]]
; CHECK:       [[FOR_COND]]:
; CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[INC41:%.*]], %[[FOR_INC40:.*]] ]
; CHECK-NEXT:    [[CMP:%.*]] = icmp samesign ult i32 [[I_0]], 10
; CHECK-NEXT:    br i1 [[CMP]], label %[[IF_THEN:.*]], label %[[FOR_COND_CLEANUP:.*]]
; CHECK:       [[FOR_COND_CLEANUP]]:
; CHECK-NEXT:    ret void
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    call void @dummy_ranks013_a()
; CHECK-NEXT:    br label %[[FOR_COND11:.*]]
; CHECK:       [[FOR_COND11]]:
; CHECK-NEXT:    [[J_0:%.*]] = phi i32 [ 0, %[[IF_THEN]] ], [ [[INC28:%.*]], %[[IF_THEN22:.*]] ]
; CHECK-NEXT:    [[CMP12:%.*]] = icmp samesign ult i32 [[J_0]], 2
; CHECK-NEXT:    br i1 [[CMP12]], label %[[FOR_COND15:.*]], label %[[FOR_INC40]]
; CHECK:       [[FOR_COND15]]:
; CHECK-NEXT:    [[K_0:%.*]] = phi i32 [ [[INC:%.*]], %[[FOR_INC:.*]] ], [ 0, %[[FOR_COND11]] ]
; CHECK-NEXT:    [[CMP16:%.*]] = icmp samesign ult i32 [[K_0]], 3
; CHECK-NEXT:    br i1 [[CMP16]], label %[[FOR_INC]], label %[[IF_THEN22]]
; CHECK:       [[FOR_INC]]:
; CHECK-NEXT:    [[INC]] = add nuw nsw i32 [[K_0]], 1
; CHECK-NEXT:    br label %[[FOR_COND15]]
; CHECK:       [[IF_THEN22]]:
; CHECK-NEXT:    call void @dummy_rank1_a()
; CHECK-NEXT:    [[INC28]] = add nuw nsw i32 [[J_0]], 1
; CHECK-NEXT:    br label %[[FOR_COND11]]
; CHECK:       [[FOR_INC40]]:
; CHECK-NEXT:    call void @dummy_common()
; CHECK-NEXT:    [[INC41]] = add nuw nsw i32 [[I_0]], 1
; CHECK-NEXT:    br label %[[FOR_COND]]
;
;
; CHECK-LABEL: define internal amdgpu_kernel void @test_kernel_3.rank_0(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_COND:.*]]
; CHECK:       [[FOR_COND]]:
; CHECK-NEXT:    [[I_0:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[INC41:%.*]], %[[FOR_INC40:.*]] ]
; CHECK-NEXT:    [[CMP:%.*]] = icmp samesign ult i32 [[I_0]], 10
; CHECK-NEXT:    br i1 [[CMP]], label %[[IF_THEN:.*]], label %[[FOR_COND_CLEANUP:.*]]
; CHECK:       [[FOR_COND_CLEANUP]]:
; CHECK-NEXT:    ret void
; CHECK:       [[IF_THEN]]:
; CHECK-NEXT:    call void @dummy_ranks013_a()
; CHECK-NEXT:    br label %[[FOR_COND11:.*]]
; CHECK:       [[FOR_COND11]]:
; CHECK-NEXT:    [[J_0:%.*]] = phi i32 [ 0, %[[IF_THEN]] ], [ [[INC28:%.*]], %[[FOR_INC27:.*]] ]
; CHECK-NEXT:    [[CMP12:%.*]] = icmp samesign ult i32 [[J_0]], 2
; CHECK-NEXT:    br i1 [[CMP12]], label %[[FOR_COND15:.*]], label %[[FOR_INC40]]
; CHECK:       [[FOR_COND15]]:
; CHECK-NEXT:    [[K_0:%.*]] = phi i32 [ [[INC:%.*]], %[[IF_THEN20:.*]] ], [ 0, %[[FOR_COND11]] ]
; CHECK-NEXT:    [[CMP16:%.*]] = icmp samesign ult i32 [[K_0]], 3
; CHECK-NEXT:    br i1 [[CMP16]], label %[[IF_THEN20]], label %[[FOR_INC27]]
; CHECK:       [[IF_THEN20]]:
; CHECK-NEXT:    call void @dummy_rank0_a()
; CHECK-NEXT:    [[INC]] = add nuw nsw i32 [[K_0]], 1
; CHECK-NEXT:    br label %[[FOR_COND15]]
; CHECK:       [[FOR_INC27]]:
; CHECK-NEXT:    [[INC28]] = add nuw nsw i32 [[J_0]], 1
; CHECK-NEXT:    br label %[[FOR_COND11]]
; CHECK:       [[FOR_INC40]]:
; CHECK-NEXT:    call void @dummy_common()
; CHECK-NEXT:    [[INC41]] = add nuw nsw i32 [[I_0]], 1
; CHECK-NEXT:    br label %[[FOR_COND]]
;
;
; CHECK-LABEL: define internal amdgpu_kernel void @test_kernel_4.rank_2_3_4_5(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND_CLEANUP:.*]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[I_027:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[INC15:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    call void @dummy_ranks2345_a()
; CHECK-NEXT:    call void @dummy_common()
; CHECK-NEXT:    [[INC15]] = add nuw nsw i32 [[I_027]], 1
; CHECK-NEXT:    [[EXITCOND28:%.*]] = icmp eq i32 [[INC15]], 10
; CHECK-NEXT:    br i1 [[EXITCOND28]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]]
;
;
; CHECK-LABEL: define internal amdgpu_kernel void @test_kernel_4.rank_0_1_6_7(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND_CLEANUP:.*]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[I_027:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[INC15:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    call void @dummy_ranks0167_a()
; CHECK-NEXT:    call void @dummy_common()
; CHECK-NEXT:    [[INC15]] = add nuw nsw i32 [[I_027]], 1
; CHECK-NEXT:    [[EXITCOND28:%.*]] = icmp eq i32 [[INC15]], 10
; CHECK-NEXT:    br i1 [[EXITCOND28]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]]
;
;
; CHECK-LABEL: define internal amdgpu_kernel void @test_kernel_5.rank_0_2_4_6(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND_CLEANUP:.*]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[I_027:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[INC15:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    call void @dummy_ranks012346_a()
; CHECK-NEXT:    call void @dummy_common()
; CHECK-NEXT:    [[INC15]] = add nuw nsw i32 [[I_027]], 1
; CHECK-NEXT:    [[EXITCOND28:%.*]] = icmp eq i32 [[INC15]], 10
; CHECK-NEXT:    br i1 [[EXITCOND28]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]]
;
;
; CHECK-LABEL: define internal amdgpu_kernel void @test_kernel_5.rank_1_3(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND_CLEANUP:.*]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[I_027:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[INC15:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    call void @dummy_ranks012346_a()
; CHECK-NEXT:    call void @dummy_common()
; CHECK-NEXT:    [[INC15]] = add nuw nsw i32 [[I_027]], 1
; CHECK-NEXT:    [[EXITCOND28:%.*]] = icmp eq i32 [[INC15]], 10
; CHECK-NEXT:    br i1 [[EXITCOND28]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]]
;
;
; CHECK-LABEL: define internal amdgpu_kernel void @test_kernel_5.rank_5_7(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND_CLEANUP:.*]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[I_027:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[INC15:%.*]], %[[IF_END13:.*]] ]
; CHECK-NEXT:    br label %[[FOR_BODY5:.*]]
; CHECK:       [[FOR_BODY5]]:
; CHECK-NEXT:    [[J_026:%.*]] = phi i32 [ [[INC:%.*]], %[[FOR_BODY5]] ], [ 0, %[[FOR_BODY]] ]
; CHECK-NEXT:    call void @dummy_ranks57_a()
; CHECK-NEXT:    [[INC]] = add nuw nsw i32 [[J_026]], 1
; CHECK-NEXT:    [[EXITCOND:%.*]] = icmp eq i32 [[INC]], 5
; CHECK-NEXT:    br i1 [[EXITCOND]], label %[[IF_END13]], label %[[FOR_BODY5]]
; CHECK:       [[IF_END13]]:
; CHECK-NEXT:    call void @dummy_common()
; CHECK-NEXT:    [[INC15]] = add nuw nsw i32 [[I_027]], 1
; CHECK-NEXT:    [[EXITCOND28:%.*]] = icmp eq i32 [[INC15]], 10
; CHECK-NEXT:    br i1 [[EXITCOND28]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]]
;
;
; CHECK-LABEL: define internal amdgpu_kernel void @test_kernel_7.rank_0_1(
; CHECK-SAME: ptr [[BASE:%.*]]) #[[ATTR3]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 @dummy_ranks01_a()
; CHECK-NEXT:    [[WID:%.*]] = call i32 @llvm.amdgcn.wave.id.in.wavegroup()
; CHECK-NEXT:    [[CMP2:%.*]] = icmp eq i32 [[WID]], 0
; CHECK-NEXT:    [[SELPTR_IDX:%.*]] = select i1 [[CMP2]], i64 0, i64 16
; CHECK-NEXT:    [[SELPTR:%.*]] = getelementptr inbounds nuw i8, ptr [[BASE]], i64 [[SELPTR_IDX]]
; CHECK-NEXT:    [[VAL:%.*]] = load i32, ptr [[SELPTR]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 (ptr, ...) @dummy_common(ptr nonnull @.str, i32 [[VAL]])
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define internal amdgpu_kernel void @test_kernel_7.rank_2_3_4_5_6_7(
; CHECK-SAME: ptr [[BASE:%.*]]) #[[ATTR3]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 @dummy_ranks234567_a()
; CHECK-NEXT:    [[WID:%.*]] = call i32 @llvm.amdgcn.wave.id.in.wavegroup()
; CHECK-NEXT:    [[CMP2:%.*]] = icmp eq i32 [[WID]], 0
; CHECK-NEXT:    [[SELPTR_IDX:%.*]] = select i1 [[CMP2]], i64 0, i64 16
; CHECK-NEXT:    [[SELPTR:%.*]] = getelementptr inbounds nuw i8, ptr [[BASE]], i64 [[SELPTR_IDX]]
; CHECK-NEXT:    [[VAL:%.*]] = load i32, ptr [[SELPTR]], align 4
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 (ptr, ...) @dummy_common(ptr nonnull @.str, i32 [[VAL]])
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define internal amdgpu_kernel void @test_kernel_8.rank_0_2_3_4_5_6(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND_CLEANUP:.*]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[I_027:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[INC15:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    call void @dummy_ranks023456_a()
; CHECK-NEXT:    call void @dummy_common()
; CHECK-NEXT:    [[INC15]] = add nuw nsw i32 [[I_027]], 1
; CHECK-NEXT:    [[EXITCOND28:%.*]] = icmp eq i32 [[INC15]], 10
; CHECK-NEXT:    br i1 [[EXITCOND28]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]]
;
;
; CHECK-LABEL: define internal amdgpu_kernel void @test_kernel_8.rank_1_7(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND_CLEANUP:.*]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[I_027:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[INC15:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    call void @dummy_ranks17_a()
; CHECK-NEXT:    call void @dummy_common()
; CHECK-NEXT:    [[INC15]] = add nuw nsw i32 [[I_027]], 1
; CHECK-NEXT:    [[EXITCOND28:%.*]] = icmp eq i32 [[INC15]], 10
; CHECK-NEXT:    br i1 [[EXITCOND28]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]]
;
;
; CHECK-LABEL: define internal amdgpu_kernel void @test_kernel_9.rank_0_1_4_5_6_7(
; CHECK-SAME: ptr [[BASE:%.*]]) #[[ATTR3]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 @dummy_ranks014567_a()
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 (i1, ...) @dummy_common(i1 false)
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define internal amdgpu_kernel void @test_kernel_9.rank_2_3(
; CHECK-SAME: ptr [[BASE:%.*]]) #[[ATTR3]] {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[TMP0:%.*]] = call i32 @dummy_ranks23_a()
; CHECK-NEXT:    [[TMP1:%.*]] = call i32 (i1, ...) @dummy_common(i1 true)
; CHECK-NEXT:    ret void
;
;
; CHECK-LABEL: define internal amdgpu_kernel void @test_kernel_10.rank_0_1_2_3(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND_CLEANUP:.*]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[I_027:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[INC15:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    call void @dummy_ranks4567_a()
; CHECK-NEXT:    call void @dummy_common()
; CHECK-NEXT:    [[INC15]] = add nuw nsw i32 [[I_027]], 1
; CHECK-NEXT:    [[EXITCOND28:%.*]] = icmp eq i32 [[INC15]], 10
; CHECK-NEXT:    br i1 [[EXITCOND28]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]]
;
;
; CHECK-LABEL: define internal amdgpu_kernel void @test_kernel_10.rank_4_5_6_7(
; CHECK-SAME: ) local_unnamed_addr #[[ATTR3]] {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    br label %[[FOR_BODY:.*]]
; CHECK:       [[FOR_COND_CLEANUP:.*]]:
; CHECK-NEXT:    ret void
; CHECK:       [[FOR_BODY]]:
; CHECK-NEXT:    [[I_027:%.*]] = phi i32 [ 0, %[[ENTRY]] ], [ [[INC15:%.*]], %[[FOR_BODY]] ]
; CHECK-NEXT:    call void @dummy_ranks0123_a()
; CHECK-NEXT:    call void @dummy_common()
; CHECK-NEXT:    [[INC15]] = add nuw nsw i32 [[I_027]], 1
; CHECK-NEXT:    [[EXITCOND28:%.*]] = icmp eq i32 [[INC15]], 10
; CHECK-NEXT:    br i1 [[EXITCOND28]], label %[[FOR_COND_CLEANUP]], label %[[FOR_BODY]]
;
