; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=amdgcn -mcpu=gfx900 < %s | FileCheck %s
define amdgpu_ps i64 @ordertest(i64 inreg %val0) {
; CHECK-LABEL: ordertest:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_lshr_b32 s0, s1, 2
; CHECK-NEXT:    s_cselect_b64 s[2:3], -1, 0
; CHECK-NEXT:    s_mov_b32 s1, 0
; CHECK-NEXT:    v_cndmask_b32_e64 v2, 0, 1, s[2:3]
; CHECK-NEXT:    v_lshrrev_b64 v[0:1], v2, s[0:1]
; CHECK-NEXT:    v_xor_b32_e32 v0, v2, v0
; CHECK-NEXT:    v_readfirstlane_b32 s0, v0
; CHECK-NEXT:    ; return to shader part epilog
  %shl = lshr i64 %val0, 34
  %result = and i64 %shl, 4294967295
  %cmp = icmp ne i64 %result, 0
  %zext = zext i1 %cmp to i64
  %param0 = lshr i64 %shl, %zext
  %param = and i64 %param0, 4294967295
  %xory = xor i64 %zext, %param
  ret i64 %xory
}
