# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -mtriple=amdgcn -mcpu=gfx1200 -run-pass=si-pre-emit-peephole %s -o - | FileCheck %s
# Test removal of blocks that only contain an unconditional branch.

# bb.1 is redundant and will be eliminated.
---
name:            test
body:             |
  ; CHECK-LABEL: name: test
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   S_NOP 0
  ; CHECK-NEXT:   S_BRANCH %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   SI_RETURN
  bb.0:
    S_NOP 0
    S_BRANCH %bb.1
  bb.1:
    S_BRANCH %bb.2
  bb.2:
    SI_RETURN
...


# Entry block and self-loops cannot be eliminated.
---
name:            negative_test
body:             |
  ; CHECK-LABEL: name: negative_test
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors: %bb.2(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   S_BRANCH %bb.2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   S_BRANCH %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   SI_RETURN
  bb.0:
    S_BRANCH %bb.2
  bb.1:
    S_BRANCH %bb.1
  bb.2:
    SI_RETURN
...
