# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=amdgcn -mcpu=gfx900 --stress-regalloc=2 -run-pass=greedy -o - %s | FileCheck %s

# Test that SOP2 instructions with dead SCC are rematerialized under register pressure

---
name: test_remat_s_add_i32
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $sgpr0

    ; CHECK-LABEL: name: test_remat_s_add_i32
    ; CHECK: liveins: $sgpr0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:sreg_32 = COPY $sgpr0
    ; CHECK-NEXT: S_NOP 0, implicit-def $sgpr1
    ; CHECK-NEXT: [[S_ADD_I32_:%[0-9]+]]:sreg_32 = S_ADD_I32 [[COPY]], [[COPY]], implicit-def dead $scc
    ; CHECK-NEXT: S_ENDPGM 0, implicit [[COPY]], implicit [[S_ADD_I32_]]
    %0:sreg_32 = COPY $sgpr0


    %1:sreg_32 = S_ADD_I32 %0, %0, implicit-def dead $scc


    S_NOP 0, implicit-def $sgpr1


    S_ENDPGM 0, implicit %0, implicit %1
...
---
name: test_remat_s_min_i32
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $sgpr0

    ; CHECK-LABEL: name: test_remat_s_min_i32
    ; CHECK: liveins: $sgpr0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:sreg_32 = COPY $sgpr0
    ; CHECK-NEXT: S_NOP 0, implicit-def $sgpr1
    ; CHECK-NEXT: [[S_MIN_I32_:%[0-9]+]]:sreg_32 = S_MIN_I32 [[COPY]], 100, implicit-def dead $scc
    ; CHECK-NEXT: S_ENDPGM 0, implicit [[COPY]], implicit [[S_MIN_I32_]]
    %0:sreg_32 = COPY $sgpr0
    %1:sreg_32 = S_MIN_I32 %0, 100, implicit-def dead $scc


    S_NOP 0, implicit-def $sgpr1


    S_ENDPGM 0, implicit %0, implicit %1
...
---
name: test_remat_s_max_i32
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $sgpr0

    ; CHECK-LABEL: name: test_remat_s_max_i32
    ; CHECK: liveins: $sgpr0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:sreg_32 = COPY $sgpr0
    ; CHECK-NEXT: S_NOP 0, implicit-def $sgpr1
    ; CHECK-NEXT: [[S_MAX_I32_:%[0-9]+]]:sreg_32 = S_MAX_I32 [[COPY]], 0, implicit-def dead $scc
    ; CHECK-NEXT: S_ENDPGM 0, implicit [[COPY]], implicit [[S_MAX_I32_]]
    %0:sreg_32 = COPY $sgpr0
    %1:sreg_32 = S_MAX_I32 %0, 0, implicit-def dead $scc


    S_NOP 0, implicit-def $sgpr1


    S_ENDPGM 0, implicit %0, implicit %1
...
---
name: test_remat_s_and_b32
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $sgpr0

    ; CHECK-LABEL: name: test_remat_s_and_b32
    ; CHECK: liveins: $sgpr0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:sreg_32 = COPY $sgpr0
    ; CHECK-NEXT: S_NOP 0, implicit-def $sgpr1
    ; CHECK-NEXT: [[S_AND_B32_:%[0-9]+]]:sreg_32 = S_AND_B32 [[COPY]], 255, implicit-def dead $scc
    ; CHECK-NEXT: S_ENDPGM 0, implicit [[COPY]], implicit [[S_AND_B32_]]
    %0:sreg_32 = COPY $sgpr0
    %1:sreg_32 = S_AND_B32 %0, 255, implicit-def dead $scc


    S_NOP 0, implicit-def $sgpr1


    S_ENDPGM 0, implicit %0, implicit %1
...
---
name: test_remat_s_or_b32
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $sgpr0

    ; CHECK-LABEL: name: test_remat_s_or_b32
    ; CHECK: liveins: $sgpr0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:sreg_32 = COPY $sgpr0
    ; CHECK-NEXT: S_NOP 0, implicit-def $sgpr1
    ; CHECK-NEXT: [[S_OR_B32_:%[0-9]+]]:sreg_32 = S_OR_B32 [[COPY]], 4096, implicit-def dead $scc
    ; CHECK-NEXT: S_ENDPGM 0, implicit [[COPY]], implicit [[S_OR_B32_]]
    %0:sreg_32 = COPY $sgpr0
    %1:sreg_32 = S_OR_B32 %0, 4096, implicit-def dead $scc


    S_NOP 0, implicit-def $sgpr1


    S_ENDPGM 0, implicit %0, implicit %1
...
---
name: test_no_remat_scc_live
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $sgpr0

    ; CHECK-LABEL: name: test_no_remat_scc_live
    ; CHECK: liveins: $sgpr0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:sreg_32 = COPY $sgpr0
    ; CHECK-NEXT: [[S_ADD_I32_:%[0-9]+]]:sreg_32_xm0_xexec = S_ADD_I32 [[COPY]], [[COPY]], implicit-def $scc
    ; CHECK-NEXT: SI_SPILL_S32_SAVE [[S_ADD_I32_]], %stack.0, implicit $exec, implicit $sp_reg :: (store (s32) into %stack.0, addrspace 5)
    ; CHECK-NEXT: S_CMPK_EQ_I32 [[COPY]], 42, implicit-def $scc
    ; CHECK-NEXT: S_NOP 0, implicit-def $sgpr1
    ; CHECK-NEXT: [[SI_SPILL_S32_RESTORE:%[0-9]+]]:sreg_32_xm0_xexec = SI_SPILL_S32_RESTORE %stack.0, implicit $exec, implicit $sp_reg :: (load (s32) from %stack.0, addrspace 5)
    ; CHECK-NEXT: [[S_CSELECT_B32_:%[0-9]+]]:sreg_32 = S_CSELECT_B32 [[SI_SPILL_S32_RESTORE]], [[COPY]], implicit $scc
    ; CHECK-NEXT: S_ENDPGM 0, implicit [[S_CSELECT_B32_]]
    %0:sreg_32 = COPY $sgpr0
    %1:sreg_32 = S_ADD_I32 %0, %0, implicit-def $scc

    S_CMPK_EQ_I32 %0, 42, implicit-def $scc

    S_NOP 0, implicit-def $sgpr1


    ; Use SCC to keep it live
    %2:sreg_32 = S_CSELECT_B32 %1, %0, implicit $scc
    S_ENDPGM 0, implicit %2
...
---
name: test_no_remat_multiple_implicit_defs
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $sgpr0

    ; CHECK-LABEL: name: test_no_remat_multiple_implicit_defs
    ; CHECK: liveins: $sgpr0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:sreg_32 = COPY $sgpr0
    ; CHECK-NEXT: dead [[S_ADD_I32_:%[0-9]+]]:sreg_32 = S_ADD_I32 [[COPY]], 1, implicit-def $scc
    ; CHECK-NEXT: [[S_ADDC_U32_:%[0-9]+]]:sreg_32_xm0_xexec = S_ADDC_U32 [[COPY]], [[COPY]], implicit-def dead $scc, implicit $scc
    ; CHECK-NEXT: SI_SPILL_S32_SAVE [[S_ADDC_U32_]], %stack.0, implicit $exec, implicit $sp_reg :: (store (s32) into %stack.0, addrspace 5)
    ; CHECK-NEXT: S_NOP 0, implicit-def $sgpr1
    ; CHECK-NEXT: [[SI_SPILL_S32_RESTORE:%[0-9]+]]:sreg_32_xm0_xexec = SI_SPILL_S32_RESTORE %stack.0, implicit $exec, implicit $sp_reg :: (load (s32) from %stack.0, addrspace 5)
    ; CHECK-NEXT: S_ENDPGM 0, implicit [[COPY]], implicit [[SI_SPILL_S32_RESTORE]]
    %0:sreg_32 = COPY $sgpr0
    %2:sreg_32 = S_ADD_I32 %0, 1, implicit-def $scc
    %1:sreg_32 = S_ADDC_U32 %0, %0, implicit-def dead $scc, implicit $scc


    S_NOP 0, implicit-def $sgpr1

    S_ENDPGM 0, implicit %0, implicit %1
...
---
name: test_no_remat_exec_def
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $sgpr0_sgpr1, $exec
    ; Instructions that define EXEC should not be rematerialized

    ; CHECK-LABEL: name: test_no_remat_exec_def
    ; CHECK: liveins: $sgpr0_sgpr1, $exec
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:sreg_64 = COPY $sgpr0_sgpr1
    ; CHECK-NEXT: [[S_AND_SAVEEXEC_B64_:%[0-9]+]]:sreg_64 = S_AND_SAVEEXEC_B64 [[COPY]], implicit-def $exec, implicit-def dead $scc, implicit $exec
    ; CHECK-NEXT: SI_SPILL_S64_SAVE [[S_AND_SAVEEXEC_B64_]], %stack.0, implicit $exec, implicit $sp_reg :: (store (s64) into %stack.0, align 4, addrspace 5)
    ; CHECK-NEXT: S_NOP 0, implicit-def $sgpr2_sgpr3
    ; CHECK-NEXT: [[SI_SPILL_S64_RESTORE:%[0-9]+]]:sreg_64 = SI_SPILL_S64_RESTORE %stack.0, implicit $exec, implicit $sp_reg :: (load (s64) from %stack.0, align 4, addrspace 5)
    ; CHECK-NEXT: S_ENDPGM 0, implicit [[COPY]], implicit [[SI_SPILL_S64_RESTORE]]
    %0:sreg_64 = COPY $sgpr0_sgpr1
    %1:sreg_64 = S_AND_SAVEEXEC_B64 %0, implicit-def $exec, implicit-def dead $scc, implicit $exec


    S_NOP 0, implicit-def $sgpr2_sgpr3


    S_ENDPGM 0, implicit %0, implicit %1
...
---
name: test_no_remat_addc_different_operands
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $sgpr0
    ; S_ADDC_U32 uses SCC from previous instruction, cannot be rematerialized

    ; CHECK-LABEL: name: test_no_remat_addc_different_operands
    ; CHECK: liveins: $sgpr0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:sreg_32 = COPY $sgpr0
    ; CHECK-NEXT: dead [[S_ADD_I32_:%[0-9]+]]:sreg_32 = S_ADD_I32 [[COPY]], 5, implicit-def $scc
    ; CHECK-NEXT: [[S_ADDC_U32_:%[0-9]+]]:sreg_32_xm0_xexec = S_ADDC_U32 [[COPY]], 1, implicit-def dead $scc, implicit $scc
    ; CHECK-NEXT: SI_SPILL_S32_SAVE [[S_ADDC_U32_]], %stack.0, implicit $exec, implicit $sp_reg :: (store (s32) into %stack.0, addrspace 5)
    ; CHECK-NEXT: S_NOP 0, implicit-def $sgpr1
    ; CHECK-NEXT: [[SI_SPILL_S32_RESTORE:%[0-9]+]]:sreg_32_xm0_xexec = SI_SPILL_S32_RESTORE %stack.0, implicit $exec, implicit $sp_reg :: (load (s32) from %stack.0, addrspace 5)
    ; CHECK-NEXT: S_ENDPGM 0, implicit [[COPY]], implicit [[SI_SPILL_S32_RESTORE]]
    %0:sreg_32 = COPY $sgpr0
    dead %2:sreg_32 = S_ADD_I32 %0, 5, implicit-def $scc
    %1:sreg_32 = S_ADDC_U32 %0, 1, implicit-def dead $scc, implicit $scc


    S_NOP 0, implicit-def $sgpr1


    S_ENDPGM 0, implicit %0, implicit %1
...
---
name: test_no_remat_scc_chain
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $sgpr0
    ; Instruction with live SCC should not be rematerialized

    ; CHECK-LABEL: name: test_no_remat_scc_chain
    ; CHECK: liveins: $sgpr0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:sreg_32 = COPY $sgpr0
    ; CHECK-NEXT: [[S_ADD_I32_:%[0-9]+]]:sreg_32_xm0_xexec = S_ADD_I32 [[COPY]], 2, implicit-def $scc
    ; CHECK-NEXT: SI_SPILL_S32_SAVE [[S_ADD_I32_]], %stack.0, implicit $exec, implicit $sp_reg :: (store (s32) into %stack.0, addrspace 5)
    ; CHECK-NEXT: S_NOP 0, implicit-def $sgpr1
    ; CHECK-NEXT: [[SI_SPILL_S32_RESTORE:%[0-9]+]]:sreg_32_xm0_xexec = SI_SPILL_S32_RESTORE %stack.0, implicit $exec, implicit $sp_reg :: (load (s32) from %stack.0, addrspace 5)
    ; CHECK-NEXT: [[S_CSELECT_B32_:%[0-9]+]]:sreg_32 = S_CSELECT_B32 [[SI_SPILL_S32_RESTORE]], [[COPY]], implicit $scc
    ; CHECK-NEXT: S_ENDPGM 0, implicit [[S_CSELECT_B32_]]
    %0:sreg_32 = COPY $sgpr0
    %1:sreg_32 = S_ADD_I32 %0, 2, implicit-def $scc


    S_NOP 0, implicit-def $sgpr1


    %2:sreg_32 = S_CSELECT_B32 %1, %0, implicit $scc
    S_ENDPGM 0, implicit %2
...
