; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=amdgcn -mcpu=gfx1250 < %s | FileCheck %s

; The cost model treats async DMA at its 1-cycle issue cost rather than the
; scheduling model's full memory latency. When the guarded block contains
; only cheap ALU and the async load (no waitcnts), the branch is removed.
;
define amdgpu_ps void @async_load_no_waitcnt(
; CHECK-LABEL: async_load_no_waitcnt:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_WAVE_MODE, 25, 1), 1 ; msbs: dst=0 src0=0 src1=0 src2=0
; CHECK-NEXT:    s_mov_b32 s2, exec_lo
; CHECK-NEXT:    v_cmpx_lt_i32_e64 s0, v1
; CHECK-NEXT:  ; %bb.1: ; %do_load
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    global_load_async_to_lds_b128 v0, v1, s[0:1]
; CHECK-NEXT:  ; %bb.2: ; %join
; CHECK-NEXT:    s_or_b32 exec_lo, exec_lo, s2
; CHECK-NEXT:    s_wait_asynccnt 0x0
; CHECK-NEXT:    s_endpgm
    ptr addrspace(1) inreg %gaddr,
    ptr addrspace(3) %laddr,
    i32 %bound
) {
  %tid = tail call i32 @llvm.amdgcn.workitem.id.x()
  %cmp = icmp slt i32 %tid, %bound
  br i1 %cmp, label %do_load, label %skip

do_load:
  tail call void @llvm.amdgcn.global.load.async.to.lds.b128(
      ptr addrspace(1) %gaddr,
      ptr addrspace(3) %laddr,
      i32 0, i32 0)
  br label %join

skip:
  br label %join

join:
  tail call void @llvm.amdgcn.s.wait.asynccnt(i16 0)
  ret void
}
