; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1100 < %s | FileCheck %s

; This used to fail machine verification after rename-independent-subregs
; created duplicate unused-lane subranges while repairing missing predecessor
; definitions for a split subregister component.

define <7 x i32> @multiple_predecessor_unused_lanes(<7 x i32> %ha, i32 %h.sel) {
; CHECK-LABEL: multiple_predecessor_unused_lanes:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; CHECK-NEXT:    v_and_b32_e32 v7, 3, v7
; CHECK-NEXT:    s_mov_b32 s0, exec_lo
; CHECK-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; CHECK-NEXT:    v_cmpx_lt_i32_e32 0, v7
; CHECK-NEXT:    s_xor_b32 s0, exec_lo, s0
; CHECK-NEXT:    s_cbranch_execz .LBB0_6
; CHECK-NEXT:  ; %bb.1: ; %LeafBlock
; CHECK-NEXT:    s_mov_b32 s1, exec_lo
; CHECK-NEXT:    v_cmpx_ne_u32_e32 1, v7
; CHECK-NEXT:    s_xor_b32 s1, exec_lo, s1
; CHECK-NEXT:  ; %bb.2: ; %h.default
; CHECK-NEXT:    v_xor_b32_e32 v5, 1, v5
; CHECK-NEXT:    ; implicit-def: $vgpr6
; CHECK-NEXT:    v_mov_b32_e32 v12, v6
; CHECK-NEXT:    v_dual_mov_b32 v9, v3 :: v_dual_mov_b32 v8, v2
; CHECK-NEXT:    s_delay_alu instid0(VALU_DEP_3)
; CHECK-NEXT:    v_dual_mov_b32 v11, v5 :: v_dual_mov_b32 v10, v4
; CHECK-NEXT:    v_dual_mov_b32 v7, v1 :: v_dual_mov_b32 v6, v0
; CHECK-NEXT:  ; %bb.3: ; %Flow
; CHECK-NEXT:    s_and_not1_saveexec_b32 s1, s1
; CHECK-NEXT:  ; %bb.4: ; %h.shuffle
; CHECK-NEXT:    v_mov_b32_e32 v7, v0
; CHECK-NEXT:    v_mov_b32_e32 v8, v0
; CHECK-NEXT:    v_mov_b32_e32 v10, v0
; CHECK-NEXT:    ; implicit-def: $vgpr11
; CHECK-NEXT:    ; implicit-def: $vgpr12
; CHECK-NEXT:  ; %bb.5: ; %Flow1
; CHECK-NEXT:    s_or_b32 exec_lo, exec_lo, s1
; CHECK-NEXT:    ; implicit-def: $vgpr1
; CHECK-NEXT:  .LBB0_6: ; %Flow2
; CHECK-NEXT:    s_and_not1_saveexec_b32 s0, s0
; CHECK-NEXT:    s_cbranch_execz .LBB0_8
; CHECK-NEXT:  ; %bb.7: ; %h.add
; CHECK-NEXT:    v_or_b32_e32 v12, 1, v6
; CHECK-NEXT:    v_or_b32_e32 v11, 1, v5
; CHECK-NEXT:    v_or_b32_e32 v10, 1, v4
; CHECK-NEXT:    v_or_b32_e32 v9, 1, v3
; CHECK-NEXT:    v_or_b32_e32 v8, 1, v2
; CHECK-NEXT:    v_or_b32_e32 v7, 1, v1
; CHECK-NEXT:    v_or_b32_e32 v6, 1, v0
; CHECK-NEXT:  .LBB0_8: ; %UnifiedReturnBlock
; CHECK-NEXT:    s_or_b32 exec_lo, exec_lo, s0
; CHECK-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; CHECK-NEXT:    v_dual_mov_b32 v0, v6 :: v_dual_mov_b32 v1, v7
; CHECK-NEXT:    v_dual_mov_b32 v2, v8 :: v_dual_mov_b32 v3, v9
; CHECK-NEXT:    v_dual_mov_b32 v4, v10 :: v_dual_mov_b32 v5, v11
; CHECK-NEXT:    v_mov_b32_e32 v6, v12
; CHECK-NEXT:    s_setpc_b64 s[30:31]
entry:
  %h.case = and i32 %h.sel, 3
  switch i32 %h.case, label %h.default [
    i32 0, label %h.add
    i32 1, label %h.shuffle
  ]

common.ret:
  %ret = phi <7 x i32> [ %h.shuf, %h.shuffle ], [ %h.x, %h.default ]
  ret <7 x i32> %ret

h.add:
  %h.addv = or <7 x i32> %ha, splat (i32 1)
  ret <7 x i32> %h.addv

h.shuffle:
  %h.shuf = shufflevector <7 x i32> %ha, <7 x i32> %ha, <7 x i32> <i32 6, i32 0, i32 0, i32 poison, i32 0, i32 poison, i32 poison>
  br label %common.ret

h.default:
  %h.x = xor <7 x i32> %ha, <i32 0, i32 poison, i32 0, i32 0, i32 0, i32 1, i32 poison>
  br label %common.ret
}
