# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx950 \
# RUN:     -run-pass=machine-scheduler \
# RUN:     -amdgpu-disable-rewrite-mfma-form-sched-stage=false \
# RUN:     -o - %s | FileCheck %s
#
# Bug test (loop variant): isMAI -> isMFMA fix in isReachingDefAGPRForm.
#
# The loop-carried accumulator %acc has TWO reaching defs at the MFMA's src2:
#   1. V_ACCVGPR_READ_B32_e64 from bb.0 (entry, executed once)
#      -> isMAI=true, isMFMA=false -> WRONG to treat as AGPR-form
#   2. The MFMA itself from bb.1 back-edge (loop, executed many times)
#      -> isMFMA=true -> correctly skipped (already AGPR after rewrite)
#
# Without the fix (isMAI): both reaching defs return true -> no CopyForDef
#   -> lower cost -> rewrite fires -> %acc wrongly becomes areg -> no bridge copy.
#
# With the fix (isMFMA): V_ACCVGPR_READ_B32 returns false -> CopyForDef
#   -> a bridge copy "areg_src2 = COPY %acc:vreg" is inserted before the MFMA
#   -> %acc (vreg) is bridged correctly to AGPR for the rewritten MFMA.

--- |
  define void @test_accvgpr_read_loop() #0 {
  entry:
    br label %loop
  loop:
    br i1 undef, label %epilogue, label %loop
  epilogue:
    ret void
  }

  attributes #0 = { "amdgpu-waves-per-eu"="1,1" "amdgpu-flat-work-group-size"="64,64" }
...

---
name:            test_accvgpr_read_loop
tracksRegLiveness: true
liveins:
  - { reg: '$vgpr0' }
  - { reg: '$sgpr4_sgpr5' }
machineFunctionInfo:
  isEntryFunction: true
  scratchRSrcReg:  '$sgpr96_sgpr97_sgpr98_sgpr99'
  stackPtrOffsetReg: '$sgpr32'
  argumentInfo:
    privateSegmentBuffer: { reg: '$sgpr0_sgpr1_sgpr2_sgpr3' }
    kernargSegmentPtr:    { reg: '$sgpr4_sgpr5' }
    workGroupIDX:         { reg: '$sgpr6' }
    privateSegmentWaveByteOffset: { reg: '$sgpr7' }
    workItemIDX:          { reg: '$vgpr0' }
  sgprForEXECCopy: '$sgpr100_sgpr101'
body: |
  ; CHECK-LABEL: name: test_accvgpr_read_loop
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $vgpr0, $sgpr4_sgpr5
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %p1:vreg_1024 = IMPLICIT_DEF
  ; CHECK-NEXT:   %p2:vreg_1024 = IMPLICIT_DEF
  ; CHECK-NEXT:   %p3:vreg_1024 = IMPLICIT_DEF
  ; CHECK-NEXT:   %p4:vreg_1024 = IMPLICIT_DEF
  ; CHECK-NEXT:   %p5:vreg_1024 = IMPLICIT_DEF
  ; CHECK-NEXT:   %p6:vreg_1024 = IMPLICIT_DEF
  ; CHECK-NEXT:   S_NOP 0, implicit-def %av0
  ; CHECK-NEXT:   S_NOP 0, implicit-def %av1
  ; CHECK-NEXT:   %p7:vreg_1024 = IMPLICIT_DEF
  ; CHECK-NEXT:   SCHED_BARRIER 0
  ; CHECK-NEXT:   %agpr0:areg_128_align2 = IMPLICIT_DEF
  ; CHECK-NEXT:   undef %acc.sub0:vreg_128_align2 = V_ACCVGPR_READ_B32_e64 %agpr0.sub0, implicit $exec
  ; CHECK-NEXT:   %acc.sub1:vreg_128_align2 = V_ACCVGPR_READ_B32_e64 %agpr0.sub1, implicit $exec
  ; CHECK-NEXT:   %acc.sub2:vreg_128_align2 = V_ACCVGPR_READ_B32_e64 %agpr0.sub2, implicit $exec
  ; CHECK-NEXT:   %acc.sub3:vreg_128_align2 = V_ACCVGPR_READ_B32_e64 %agpr0.sub3, implicit $exec
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:areg_128_align2 = COPY %acc
  ; CHECK-NEXT:   $scc = IMPLICIT_DEF
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1.loop:
  ; CHECK-NEXT:   successors: %bb.2(0x04000000), %bb.1(0x7c000000)
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   %ctr:sreg_32 = S_MOV_B32 0
  ; CHECK-NEXT:   S_CMP_EQ_U32 %ctr, 0, implicit-def $scc
  ; CHECK-NEXT:   [[DEF:%[0-9]+]]:av_128_align2 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[DEF1:%[0-9]+]]:av_128_align2 = IMPLICIT_DEF
  ; CHECK-NEXT:   [[COPY:%[0-9]+]]:areg_128_align2 = V_MFMA_F32_16X16X32_F16_e64 [[DEF]], [[DEF1]], [[COPY]], 0, 0, 0, implicit $mode, implicit $exec
  ; CHECK-NEXT:   S_CBRANCH_SCC0 %bb.1, implicit $scc
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2.epilogue:
  ; CHECK-NEXT:   [[COPY1:%[0-9]+]]:vreg_128_align2 = COPY [[COPY]]
  ; CHECK-NEXT:   %acc_out:vreg_128_align2 = COPY [[COPY1]]
  ; CHECK-NEXT:   [[DEF2:%[0-9]+]]:vreg_1024 = IMPLICIT_DEF
  ; CHECK-NEXT:   KILL [[DEF2]], %p1, %p2, %p3, %p4, %p5, %p6, %p7, %acc_out
  ; CHECK-NEXT:   S_NOP 0, implicit %av0, implicit %av1
  ; CHECK-NEXT:   S_ENDPGM 0
  bb.0.entry:
    successors: %bb.1(0x80000000)
    liveins: $vgpr0, $sgpr4_sgpr5

    ; 8 x vreg_1024 = 256 arch VGPRs pressure padding.
    ; These are live throughout the loop (killed in bb.2), so the loop body
    ; has high arch VGPR pressure, triggering RegionsWithExcessArchVGPR.
    %p0:vreg_1024 = IMPLICIT_DEF
    %p1:vreg_1024 = IMPLICIT_DEF
    %p2:vreg_1024 = IMPLICIT_DEF
    %p3:vreg_1024 = IMPLICIT_DEF
    %p4:vreg_1024 = IMPLICIT_DEF
    %p5:vreg_1024 = IMPLICIT_DEF
    %p6:vreg_1024 = IMPLICIT_DEF
    %p7:vreg_1024 = IMPLICIT_DEF
    S_NOP 0, implicit-def %av0:av_512
    S_NOP 0, implicit-def %av1:av_512
    SCHED_BARRIER 0

    ; MFMA src0/src1 (half-precision matrices).
    %s0:av_128_align2 = IMPLICIT_DEF
    %s1:av_128_align2 = IMPLICIT_DEF

    ; AGPR source register.
    %agpr0:areg_128_align2 = IMPLICIT_DEF

    ; Initial loop-carried accumulator value via V_ACCVGPR_READ_B32_e64.
    ; isMAI(%acc_init_def) = true, but isMFMA = false (AGPR->VGPR copy).
    ; This is the "entry reaching def" seen by findReachingDefs at the loop MFMA.
    ; WITH fix: isReachingDefAGPRForm returns false -> bridge copy inserted.
    ; WITHOUT fix: isReachingDefAGPRForm returns true  -> NO bridge copy.
    undef %acc.sub0:vreg_128_align2 = V_ACCVGPR_READ_B32_e64 %agpr0.sub0, implicit $exec
    %acc.sub1:vreg_128_align2 = V_ACCVGPR_READ_B32_e64 %agpr0.sub1, implicit $exec
    %acc.sub2:vreg_128_align2 = V_ACCVGPR_READ_B32_e64 %agpr0.sub2, implicit $exec
    %acc.sub3:vreg_128_align2 = V_ACCVGPR_READ_B32_e64 %agpr0.sub3, implicit $exec

    $scc = IMPLICIT_DEF

  bb.1.loop:
    ; Loop taken probability ~97%: RelFreq(bb.1/entry) ~= 32.
    ; SpillCost(loop) = -savings * 2 * 32 -> very negative.
    ; CopyForDef(V_ACCVGPR_READ_B32 in entry): cost = 9 * 1 = 9 (small fixed).
    ; Net: rewrite is profitable despite the extra bridge copy.
    successors: %bb.2(0x04000000), %bb.1(0x7c000000)

    ; Self-referential MFMA: %acc = MFMA(src0, src1, %acc).
    ; The src2 (%acc) has two reaching defs:
    ;   bb.0: V_ACCVGPR_READ_B32 -> isMFMA=false -> CopyForDef (with fix)
    ;   bb.1: this MFMA (back-edge) -> isMFMA=true -> isReachingDefAGPRForm=true
    %acc:vreg_128_align2 = V_MFMA_F32_16X16X32_F16_vgprcd_e64 %s0, %s1, %acc, 0, 0, 0, implicit $mode, implicit $exec

    %ctr:sreg_32 = S_MOV_B32 0
    S_CMP_EQ_U32 %ctr, 0, implicit-def $scc
    S_CBRANCH_SCC0 %bb.1, implicit killed $scc

  bb.2.epilogue:
    ; Only COPY user of %acc -> isRewriteCandidate passes.
    %acc_out:vreg_128_align2 = COPY %acc
    KILL %p0, %p1, %p2, %p3, %p4, %p5, %p6, %p7, %acc_out
    S_NOP 0, implicit %av0, implicit %av1
    S_ENDPGM 0
