; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 6
; RUN: opt -S -mtriple=amdgcn-- -passes=amdgpu-lower-exec-sync < %s 2>&1 | FileCheck %s

@bar = internal addrspace(15) global target("amdgcn.named.barrier", 0) poison
@bar2 = internal addrspace(15) global target("amdgcn.named.barrier", 0) poison

;.
; CHECK: @bar = internal addrspace(15) global target("amdgcn.named.barrier", 0) poison, !absolute_symbol [[META0:![0-9]+]]
; CHECK: @bar2 = internal addrspace(15) global target("amdgcn.named.barrier", 0) poison, !absolute_symbol [[META0]]
;.
define void @func1() {
; CHECK-LABEL: define void @func1() {
; CHECK-NEXT:    call void @llvm.amdgcn.s.barrier.join(ptr addrspace(15) @bar)
; CHECK-NEXT:    call void @llvm.amdgcn.s.barrier.signal.var(ptr addrspace(15) @bar, i32 7)
; CHECK-NEXT:    call void @llvm.amdgcn.s.barrier.wait(i16 1)
; CHECK-NEXT:    ret void
;
  call void @llvm.amdgcn.s.barrier.join(ptr addrspace(15) @bar)
  call void @llvm.amdgcn.s.barrier.signal.var(ptr addrspace(15) @bar, i32 7)
  call void @llvm.amdgcn.s.barrier.wait(i16 1)
  ret void
}

define void @func2() {
; CHECK-LABEL: define void @func2() {
; CHECK-NEXT:    call void @llvm.amdgcn.s.barrier.join(ptr addrspace(15) @bar2)
; CHECK-NEXT:    call void @llvm.amdgcn.s.barrier.signal.var(ptr addrspace(15) @bar2, i32 7)
; CHECK-NEXT:    call void @llvm.amdgcn.s.barrier.wait(i16 1)
; CHECK-NEXT:    ret void
;
  call void @llvm.amdgcn.s.barrier.join(ptr addrspace(15) @bar2)
  call void @llvm.amdgcn.s.barrier.signal.var(ptr addrspace(15) @bar2, i32 7)
  call void @llvm.amdgcn.s.barrier.wait(i16 1)
  ret void
}

define amdgpu_kernel void @kernel1(ptr addrspace(1) %out, ptr addrspace(15) %in) {
; CHECK-LABEL: define amdgpu_kernel void @kernel1(
; CHECK-SAME: ptr addrspace(1) [[OUT:%.*]], ptr addrspace(15) [[IN:%.*]]) {
; CHECK-NEXT:    call void @func1()
; CHECK-NEXT:    [[STATE3:%.*]] = call i32 @llvm.amdgcn.s.get.barrier.state(i32 -1)
; CHECK-NEXT:    ret void
;
  call void @func1()
  %state3 = call i32 @llvm.amdgcn.s.get.barrier.state(i32 -1)
  ret void
}

define amdgpu_kernel void @kernel2(ptr addrspace(1) %out, ptr addrspace(15) %in) {
; CHECK-LABEL: define amdgpu_kernel void @kernel2(
; CHECK-SAME: ptr addrspace(1) [[OUT:%.*]], ptr addrspace(15) [[IN:%.*]]) {
; CHECK-NEXT:    call void @func1()
; CHECK-NEXT:    ret void
;
  call void @func1()
  ret void
}

define amdgpu_kernel void @kernel3(ptr addrspace(1) %out, ptr addrspace(15) %in) {
; CHECK-LABEL: define amdgpu_kernel void @kernel3(
; CHECK-SAME: ptr addrspace(1) [[OUT:%.*]], ptr addrspace(15) [[IN:%.*]]) {
; CHECK-NEXT:    call void @func2()
; CHECK-NEXT:    [[STATE3:%.*]] = call i32 @llvm.amdgcn.s.get.barrier.state(i32 -1)
; CHECK-NEXT:    ret void
;
  call void @func2()
  %state3 = call i32 @llvm.amdgcn.s.get.barrier.state(i32 -1)
  ret void
}

define amdgpu_kernel void @kernel4(ptr addrspace(1) %out, ptr addrspace(15) %in) {
; CHECK-LABEL: define amdgpu_kernel void @kernel4(
; CHECK-SAME: ptr addrspace(1) [[OUT:%.*]], ptr addrspace(15) [[IN:%.*]]) {
; CHECK-NEXT:    call void @func2()
; CHECK-NEXT:    ret void
;
  call void @func2()
  ret void
}


;.
; CHECK: attributes #[[ATTR0:[0-9]+]] = { convergent nocallback nofree nounwind willreturn }
;.
; CHECK: [[META0]] = !{i32 1, i32 2}
;.
