# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1250 -run-pass=si-global-load-saddr-to-vaddr \
# RUN:   -amdgpu-global-load-saddr-to-vaddr-max-converts=1 -o - %s \
# RUN:   | FileCheck -check-prefix=CAP1 %s
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1250 -run-pass=si-global-load-saddr-to-vaddr \
# RUN:   -o - %s | FileCheck -check-prefix=NOBUDGET %s

# Test: With max-converts=1, only the highest SGPR-pressure candidate is
# converted. Candidate 1 has SGPR pressure 4 (sgpr44, sgpr45, sgpr46, sgpr47
# all live), candidate 2 has pressure 2 (only sgpr44, sgpr45 live).
# The pass picks candidate 1 for conversion and leaves candidate 2 as SADDR.
# Without the budget cap, both are converted.
---
name:            budget_cap_picks_highest_pressure
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $sgpr44_sgpr45, $sgpr46, $sgpr47

    ; CAP1-LABEL: name: budget_cap_picks_highest_pressure
    ; CAP1: liveins: $sgpr44_sgpr45, $sgpr46, $sgpr47
    ; CAP1-NEXT: {{  $}}
    ; CAP1-NEXT: [[DEF:%[0-9]+]]:vgpr_32 = IMPLICIT_DEF
    ; CAP1-NEXT: [[COPY:%[0-9]+]]:vreg_64_align2 = COPY $sgpr44_sgpr45
    ; CAP1-NEXT: [[GLOBAL_LOAD_DWORD:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD [[COPY]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; CAP1-NEXT: $sgpr44 = S_MOV_B32 $sgpr46
    ; CAP1-NEXT: $sgpr45 = S_MOV_B32 $sgpr47
    ; CAP1-NEXT: [[GLOBAL_LOAD_DWORD_SADDR:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR $sgpr44_sgpr45, [[DEF]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; CAP1-NEXT: $sgpr44 = S_MOV_B32 1
    ; CAP1-NEXT: S_ENDPGM 0, implicit [[GLOBAL_LOAD_DWORD]], implicit [[GLOBAL_LOAD_DWORD_SADDR]]
    ;
    ; NOBUDGET-LABEL: name: budget_cap_picks_highest_pressure
    ; NOBUDGET: liveins: $sgpr44_sgpr45, $sgpr46, $sgpr47
    ; NOBUDGET-NEXT: {{  $}}
    ; NOBUDGET-NEXT: [[DEF:%[0-9]+]]:vgpr_32 = IMPLICIT_DEF
    ; NOBUDGET-NEXT: [[COPY:%[0-9]+]]:vreg_64_align2 = COPY $sgpr44_sgpr45
    ; NOBUDGET-NEXT: [[GLOBAL_LOAD_DWORD:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD [[COPY]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; NOBUDGET-NEXT: $sgpr44 = S_MOV_B32 $sgpr46
    ; NOBUDGET-NEXT: $sgpr45 = S_MOV_B32 $sgpr47
    ; NOBUDGET-NEXT: [[COPY1:%[0-9]+]]:vreg_64_align2 = COPY $sgpr44_sgpr45
    ; NOBUDGET-NEXT: [[GLOBAL_LOAD_DWORD1:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD [[COPY1]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; NOBUDGET-NEXT: KILL killed [[COPY]], killed [[COPY1]]
    ; NOBUDGET-NEXT: $sgpr44 = S_MOV_B32 1
    ; NOBUDGET-NEXT: S_ENDPGM 0, implicit [[GLOBAL_LOAD_DWORD]], implicit [[GLOBAL_LOAD_DWORD1]]
    %0:vgpr_32 = IMPLICIT_DEF
    %1:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR $sgpr44_sgpr45, %0, 0, 0, implicit $exec :: (load (s32), addrspace 1)
    $sgpr44 = S_MOV_B32 $sgpr46
    $sgpr45 = S_MOV_B32 $sgpr47
    %2:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR $sgpr44_sgpr45, %0, 0, 0, implicit $exec :: (load (s32), addrspace 1)
    $sgpr44 = S_MOV_B32 1
    S_ENDPGM 0, implicit %1, implicit %2
...
