# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1250 -verify-machineinstrs -run-pass=greedy,si-fix-xcnt-stall-saddr-reuse -o - %s | FileCheck -check-prefix=GFX1250 %s
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx942 -verify-machineinstrs -run-pass=greedy,si-fix-xcnt-stall-saddr-reuse -o - %s | FileCheck -check-prefix=GFX942 %s

# Two loads using different virtual SGPRs that RA assigns to the same physical
# pair. The first load's saddr is "redefined" (via VRM) by the second load's
# saddr definition. Zero vaddr (V_MOV_B32_e32 0) exercises the simple COPY path.
---
name:            zero_vaddr_reuse
tracksRegLiveness: true
registers:
  - { id: 0, class: sreg_64_xexec_xnull, preferred-register: '$sgpr4_sgpr5' }
  - { id: 1, class: vgpr_32 }
  - { id: 2, class: vgpr_32 }
  - { id: 3, class: sreg_64_xexec_xnull, preferred-register: '$sgpr4_sgpr5' }
  - { id: 4, class: vgpr_32 }
body:             |
  bb.0:
    liveins: $sgpr0_sgpr1

    ; GFX1250-LABEL: name: zero_vaddr_reuse
    ; GFX1250: liveins: $sgpr0_sgpr1
    ; GFX1250-NEXT: {{  $}}
    ; GFX1250-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 0, 0 :: (dereferenceable invariant load (s64))
    ; GFX1250-NEXT: [[V_MOV_B32_e32_:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
    ; GFX1250-NEXT: [[COPY:%[0-9]+]]:vreg_64_align2 = COPY [[S_LOAD_DWORDX2_IMM]]
    ; GFX1250-NEXT: [[GLOBAL_LOAD_DWORD:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD [[COPY]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX1250-NEXT: [[S_LOAD_DWORDX2_IMM1:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 8, 0 :: (dereferenceable invariant load (s64))
    ; GFX1250-NEXT: [[GLOBAL_LOAD_DWORD_SADDR:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM1]], [[V_MOV_B32_e32_]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX1250-NEXT: KILL killed [[COPY]]
    ; GFX1250-NEXT: S_ENDPGM 0, implicit [[GLOBAL_LOAD_DWORD]], implicit [[GLOBAL_LOAD_DWORD_SADDR]]
    ;
    ; GFX942-LABEL: name: zero_vaddr_reuse
    ; GFX942: liveins: $sgpr0_sgpr1
    ; GFX942-NEXT: {{  $}}
    ; GFX942-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 0, 0 :: (dereferenceable invariant load (s64))
    ; GFX942-NEXT: [[V_MOV_B32_e32_:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
    ; GFX942-NEXT: [[GLOBAL_LOAD_DWORD_SADDR:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM]], [[V_MOV_B32_e32_]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX942-NEXT: [[S_LOAD_DWORDX2_IMM1:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 8, 0 :: (dereferenceable invariant load (s64))
    ; GFX942-NEXT: [[GLOBAL_LOAD_DWORD_SADDR1:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM1]], [[V_MOV_B32_e32_]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX942-NEXT: S_ENDPGM 0, implicit [[GLOBAL_LOAD_DWORD_SADDR]], implicit [[GLOBAL_LOAD_DWORD_SADDR1]]
    %0:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 0, 0 :: (dereferenceable invariant load (s64))
    %1:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
    %2:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR %0, %1, 0, 0, implicit $exec :: (load (s32), addrspace 1)
    %3:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 8, 0 :: (dereferenceable invariant load (s64))
    %4:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR %3, %1, 0, 0, implicit $exec :: (load (s32), addrspace 1)
    S_ENDPGM 0, implicit %2, implicit %4
...

# Same scenario but with a non-zero vaddr offset, exercises the full
# sext + add path.
---
name:            nonzero_vaddr_reuse
tracksRegLiveness: true
registers:
  - { id: 0, class: sreg_64_xexec_xnull, preferred-register: '$sgpr4_sgpr5' }
  - { id: 1, class: vgpr_32 }
  - { id: 2, class: vgpr_32 }
  - { id: 3, class: sreg_64_xexec_xnull, preferred-register: '$sgpr4_sgpr5' }
  - { id: 4, class: vgpr_32 }
body:             |
  bb.0:
    liveins: $sgpr0_sgpr1, $vgpr0

    ; GFX1250-LABEL: name: nonzero_vaddr_reuse
    ; GFX1250: liveins: $sgpr0_sgpr1, $vgpr0
    ; GFX1250-NEXT: {{  $}}
    ; GFX1250-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 0, 0 :: (dereferenceable invariant load (s64))
    ; GFX1250-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX1250-NEXT: [[COPY1:%[0-9]+]]:vgpr_32 = COPY [[COPY]]
    ; GFX1250-NEXT: [[V_ASHRREV_I32_e64_:%[0-9]+]]:vgpr_32 = V_ASHRREV_I32_e64 31, [[COPY1]], implicit $exec
    ; GFX1250-NEXT: undef [[COPY2:%[0-9]+]].sub0:vreg_64_align2 = COPY [[COPY1]]
    ; GFX1250-NEXT: [[COPY2:%[0-9]+]].sub1:vreg_64_align2 = COPY [[V_ASHRREV_I32_e64_]]
    ; GFX1250-NEXT: [[V_ADD_U64_e64_:%[0-9]+]]:vreg_64_align2 = V_ADD_U64_e64 [[S_LOAD_DWORDX2_IMM]], [[COPY2]], 0, implicit $exec
    ; GFX1250-NEXT: [[GLOBAL_LOAD_DWORD:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD [[V_ADD_U64_e64_]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX1250-NEXT: [[S_LOAD_DWORDX2_IMM1:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 8, 0 :: (dereferenceable invariant load (s64))
    ; GFX1250-NEXT: [[GLOBAL_LOAD_DWORD_SADDR:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM1]], [[COPY]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX1250-NEXT: KILL killed [[V_ADD_U64_e64_]]
    ; GFX1250-NEXT: S_ENDPGM 0, implicit [[GLOBAL_LOAD_DWORD]], implicit [[GLOBAL_LOAD_DWORD_SADDR]]
    ;
    ; GFX942-LABEL: name: nonzero_vaddr_reuse
    ; GFX942: liveins: $sgpr0_sgpr1, $vgpr0
    ; GFX942-NEXT: {{  $}}
    ; GFX942-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 0, 0 :: (dereferenceable invariant load (s64))
    ; GFX942-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX942-NEXT: [[GLOBAL_LOAD_DWORD_SADDR:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM]], [[COPY]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX942-NEXT: [[S_LOAD_DWORDX2_IMM1:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 8, 0 :: (dereferenceable invariant load (s64))
    ; GFX942-NEXT: [[GLOBAL_LOAD_DWORD_SADDR1:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM1]], [[COPY]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX942-NEXT: S_ENDPGM 0, implicit [[GLOBAL_LOAD_DWORD_SADDR]], implicit [[GLOBAL_LOAD_DWORD_SADDR1]]
    %0:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 0, 0 :: (dereferenceable invariant load (s64))
    %1:vgpr_32 = COPY $vgpr0
    %2:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR %0, %1, 0, 0, implicit $exec :: (load (s32), addrspace 1)
    %3:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 8, 0 :: (dereferenceable invariant load (s64))
    %4:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR %3, %1, 0, 0, implicit $exec :: (load (s32), addrspace 1)
    S_ENDPGM 0, implicit %2, implicit %4
...

# Store variant — verifies stores are also converted.
---
name:            store_reuse
tracksRegLiveness: true
registers:
  - { id: 0, class: sreg_64_xexec_xnull, preferred-register: '$sgpr4_sgpr5' }
  - { id: 1, class: vgpr_32 }
  - { id: 2, class: vgpr_32 }
  - { id: 3, class: sreg_64_xexec_xnull, preferred-register: '$sgpr4_sgpr5' }
body:             |
  bb.0:
    liveins: $sgpr0_sgpr1, $vgpr0

    ; GFX1250-LABEL: name: store_reuse
    ; GFX1250: liveins: $sgpr0_sgpr1, $vgpr0
    ; GFX1250-NEXT: {{  $}}
    ; GFX1250-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 0, 0 :: (dereferenceable invariant load (s64))
    ; GFX1250-NEXT: [[V_MOV_B32_e32_:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
    ; GFX1250-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX1250-NEXT: [[COPY1:%[0-9]+]]:vreg_64_align2 = COPY [[S_LOAD_DWORDX2_IMM]]
    ; GFX1250-NEXT: GLOBAL_STORE_DWORD [[COPY1]], [[COPY]], 0, 0, implicit $exec :: (store (s32), addrspace 1)
    ; GFX1250-NEXT: [[S_LOAD_DWORDX2_IMM1:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 8, 0 :: (dereferenceable invariant load (s64))
    ; GFX1250-NEXT: GLOBAL_STORE_DWORD_SADDR [[V_MOV_B32_e32_]], [[COPY]], [[S_LOAD_DWORDX2_IMM1]], 0, 0, implicit $exec :: (store (s32), addrspace 1)
    ; GFX1250-NEXT: KILL killed [[COPY1]]
    ; GFX1250-NEXT: S_ENDPGM 0
    ;
    ; GFX942-LABEL: name: store_reuse
    ; GFX942: liveins: $sgpr0_sgpr1, $vgpr0
    ; GFX942-NEXT: {{  $}}
    ; GFX942-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 0, 0 :: (dereferenceable invariant load (s64))
    ; GFX942-NEXT: [[V_MOV_B32_e32_:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
    ; GFX942-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX942-NEXT: GLOBAL_STORE_DWORD_SADDR [[V_MOV_B32_e32_]], [[COPY]], [[S_LOAD_DWORDX2_IMM]], 0, 0, implicit $exec :: (store (s32), addrspace 1)
    ; GFX942-NEXT: [[S_LOAD_DWORDX2_IMM1:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 8, 0 :: (dereferenceable invariant load (s64))
    ; GFX942-NEXT: GLOBAL_STORE_DWORD_SADDR [[V_MOV_B32_e32_]], [[COPY]], [[S_LOAD_DWORDX2_IMM1]], 0, 0, implicit $exec :: (store (s32), addrspace 1)
    ; GFX942-NEXT: S_ENDPGM 0
    %0:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 0, 0 :: (dereferenceable invariant load (s64))
    %1:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
    %2:vgpr_32 = COPY $vgpr0
    GLOBAL_STORE_DWORD_SADDR %1, %2, %0, 0, 0, implicit $exec :: (store (s32), addrspace 1)
    %3:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 8, 0 :: (dereferenceable invariant load (s64))
    GLOBAL_STORE_DWORD_SADDR %1, %2, %3, 0, 0, implicit $exec :: (store (s32), addrspace 1)
    S_ENDPGM 0
...

# No reuse — different preferred registers, pass should not convert.
---
name:            no_reuse
tracksRegLiveness: true
registers:
  - { id: 0, class: sreg_64_xexec_xnull, preferred-register: '$sgpr4_sgpr5' }
  - { id: 1, class: vgpr_32 }
  - { id: 2, class: vgpr_32 }
  - { id: 3, class: sreg_64_xexec_xnull, preferred-register: '$sgpr6_sgpr7' }
  - { id: 4, class: vgpr_32 }
body:             |
  bb.0:
    liveins: $sgpr0_sgpr1

    ; GFX1250-LABEL: name: no_reuse
    ; GFX1250: liveins: $sgpr0_sgpr1
    ; GFX1250-NEXT: {{  $}}
    ; GFX1250-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 0, 0 :: (dereferenceable invariant load (s64))
    ; GFX1250-NEXT: [[V_MOV_B32_e32_:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
    ; GFX1250-NEXT: [[GLOBAL_LOAD_DWORD_SADDR:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM]], [[V_MOV_B32_e32_]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX1250-NEXT: [[S_LOAD_DWORDX2_IMM1:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 8, 0 :: (dereferenceable invariant load (s64))
    ; GFX1250-NEXT: [[GLOBAL_LOAD_DWORD_SADDR1:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM1]], [[V_MOV_B32_e32_]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX1250-NEXT: S_ENDPGM 0, implicit [[GLOBAL_LOAD_DWORD_SADDR]], implicit [[GLOBAL_LOAD_DWORD_SADDR1]]
    ;
    ; GFX942-LABEL: name: no_reuse
    ; GFX942: liveins: $sgpr0_sgpr1
    ; GFX942-NEXT: {{  $}}
    ; GFX942-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 0, 0 :: (dereferenceable invariant load (s64))
    ; GFX942-NEXT: [[V_MOV_B32_e32_:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
    ; GFX942-NEXT: [[GLOBAL_LOAD_DWORD_SADDR:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM]], [[V_MOV_B32_e32_]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX942-NEXT: [[S_LOAD_DWORDX2_IMM1:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 8, 0 :: (dereferenceable invariant load (s64))
    ; GFX942-NEXT: [[GLOBAL_LOAD_DWORD_SADDR1:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM1]], [[V_MOV_B32_e32_]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX942-NEXT: S_ENDPGM 0, implicit [[GLOBAL_LOAD_DWORD_SADDR]], implicit [[GLOBAL_LOAD_DWORD_SADDR1]]
    %0:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 0, 0 :: (dereferenceable invariant load (s64))
    %1:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
    %2:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR %0, %1, 0, 0, implicit $exec :: (load (s32), addrspace 1)
    %3:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 8, 0 :: (dereferenceable invariant load (s64))
    %4:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR %3, %1, 0, 0, implicit $exec :: (load (s32), addrspace 1)
    S_ENDPGM 0, implicit %2, implicit %4
...

# 18 loads with the same preferred SGPR pair — exercises per-load KILL
# placement at SAddrKillDistance (default 16) instructions after each load.
---
name:            flush_group_kill
tracksRegLiveness: true
registers:
  - { id: 0, class: vgpr_32 }
  - { id: 1, class: sreg_64_xexec_xnull, preferred-register: '$sgpr4_sgpr5' }
  - { id: 2, class: vgpr_32 }
  - { id: 3, class: sreg_64_xexec_xnull, preferred-register: '$sgpr4_sgpr5' }
  - { id: 4, class: vgpr_32 }
  - { id: 5, class: sreg_64_xexec_xnull, preferred-register: '$sgpr4_sgpr5' }
  - { id: 6, class: vgpr_32 }
  - { id: 7, class: sreg_64_xexec_xnull, preferred-register: '$sgpr4_sgpr5' }
  - { id: 8, class: vgpr_32 }
  - { id: 9, class: sreg_64_xexec_xnull, preferred-register: '$sgpr4_sgpr5' }
  - { id: 10, class: vgpr_32 }
  - { id: 11, class: sreg_64_xexec_xnull, preferred-register: '$sgpr4_sgpr5' }
  - { id: 12, class: vgpr_32 }
  - { id: 13, class: sreg_64_xexec_xnull, preferred-register: '$sgpr4_sgpr5' }
  - { id: 14, class: vgpr_32 }
  - { id: 15, class: sreg_64_xexec_xnull, preferred-register: '$sgpr4_sgpr5' }
  - { id: 16, class: vgpr_32 }
  - { id: 17, class: sreg_64_xexec_xnull, preferred-register: '$sgpr4_sgpr5' }
  - { id: 18, class: vgpr_32 }
  - { id: 19, class: sreg_64_xexec_xnull, preferred-register: '$sgpr4_sgpr5' }
  - { id: 20, class: vgpr_32 }
  - { id: 21, class: sreg_64_xexec_xnull, preferred-register: '$sgpr4_sgpr5' }
  - { id: 22, class: vgpr_32 }
  - { id: 23, class: sreg_64_xexec_xnull, preferred-register: '$sgpr4_sgpr5' }
  - { id: 24, class: vgpr_32 }
  - { id: 25, class: sreg_64_xexec_xnull, preferred-register: '$sgpr4_sgpr5' }
  - { id: 26, class: vgpr_32 }
  - { id: 27, class: sreg_64_xexec_xnull, preferred-register: '$sgpr4_sgpr5' }
  - { id: 28, class: vgpr_32 }
  - { id: 29, class: sreg_64_xexec_xnull, preferred-register: '$sgpr4_sgpr5' }
  - { id: 30, class: vgpr_32 }
  - { id: 31, class: sreg_64_xexec_xnull, preferred-register: '$sgpr4_sgpr5' }
  - { id: 32, class: vgpr_32 }
  - { id: 33, class: sreg_64_xexec_xnull, preferred-register: '$sgpr4_sgpr5' }
  - { id: 34, class: vgpr_32 }
  - { id: 35, class: sreg_64_xexec_xnull, preferred-register: '$sgpr4_sgpr5' }
  - { id: 36, class: vgpr_32 }
body:             |
  bb.0:
    liveins: $sgpr0_sgpr1

    ; GFX1250-LABEL: name: flush_group_kill
    ; GFX1250: liveins: $sgpr0_sgpr1
    ; GFX1250-NEXT: {{  $}}
    ; GFX1250-NEXT: [[V_MOV_B32_e32_:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
    ; GFX1250-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 0, 0 :: (dereferenceable invariant load (s64))
    ; GFX1250-NEXT: [[COPY:%[0-9]+]]:vreg_64_align2 = COPY [[S_LOAD_DWORDX2_IMM]]
    ; GFX1250-NEXT: [[GLOBAL_LOAD_DWORD:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD [[COPY]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX1250-NEXT: [[S_LOAD_DWORDX2_IMM1:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 8, 0 :: (dereferenceable invariant load (s64))
    ; GFX1250-NEXT: [[COPY1:%[0-9]+]]:vreg_64_align2 = COPY [[S_LOAD_DWORDX2_IMM1]]
    ; GFX1250-NEXT: [[GLOBAL_LOAD_DWORD1:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD [[COPY1]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX1250-NEXT: [[S_LOAD_DWORDX2_IMM2:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 16, 0 :: (dereferenceable invariant load (s64))
    ; GFX1250-NEXT: [[COPY2:%[0-9]+]]:vreg_64_align2 = COPY [[S_LOAD_DWORDX2_IMM2]]
    ; GFX1250-NEXT: [[GLOBAL_LOAD_DWORD2:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD [[COPY2]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX1250-NEXT: [[S_LOAD_DWORDX2_IMM3:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 24, 0 :: (dereferenceable invariant load (s64))
    ; GFX1250-NEXT: [[COPY3:%[0-9]+]]:vreg_64_align2 = COPY [[S_LOAD_DWORDX2_IMM3]]
    ; GFX1250-NEXT: [[GLOBAL_LOAD_DWORD3:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD [[COPY3]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX1250-NEXT: [[S_LOAD_DWORDX2_IMM4:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 32, 0 :: (dereferenceable invariant load (s64))
    ; GFX1250-NEXT: [[COPY4:%[0-9]+]]:vreg_64_align2 = COPY [[S_LOAD_DWORDX2_IMM4]]
    ; GFX1250-NEXT: [[GLOBAL_LOAD_DWORD4:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD [[COPY4]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX1250-NEXT: [[S_LOAD_DWORDX2_IMM5:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 40, 0 :: (dereferenceable invariant load (s64))
    ; GFX1250-NEXT: [[COPY5:%[0-9]+]]:vreg_64_align2 = COPY [[S_LOAD_DWORDX2_IMM5]]
    ; GFX1250-NEXT: [[GLOBAL_LOAD_DWORD5:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD [[COPY5]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX1250-NEXT: [[S_LOAD_DWORDX2_IMM6:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 48, 0 :: (dereferenceable invariant load (s64))
    ; GFX1250-NEXT: KILL killed [[COPY]]
    ; GFX1250-NEXT: [[COPY6:%[0-9]+]]:vreg_64_align2 = COPY [[S_LOAD_DWORDX2_IMM6]]
    ; GFX1250-NEXT: [[GLOBAL_LOAD_DWORD6:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD [[COPY6]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX1250-NEXT: KILL killed [[COPY1]]
    ; GFX1250-NEXT: [[S_LOAD_DWORDX2_IMM7:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 56, 0 :: (dereferenceable invariant load (s64))
    ; GFX1250-NEXT: [[COPY7:%[0-9]+]]:vreg_64_align2 = COPY [[S_LOAD_DWORDX2_IMM7]]
    ; GFX1250-NEXT: KILL killed [[COPY2]]
    ; GFX1250-NEXT: [[GLOBAL_LOAD_DWORD7:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD [[COPY7]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX1250-NEXT: [[S_LOAD_DWORDX2_IMM8:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 64, 0 :: (dereferenceable invariant load (s64))
    ; GFX1250-NEXT: KILL killed [[COPY3]]
    ; GFX1250-NEXT: [[COPY8:%[0-9]+]]:vreg_64_align2 = COPY [[S_LOAD_DWORDX2_IMM8]]
    ; GFX1250-NEXT: [[GLOBAL_LOAD_DWORD8:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD [[COPY8]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX1250-NEXT: KILL killed [[COPY4]]
    ; GFX1250-NEXT: [[S_LOAD_DWORDX2_IMM9:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 72, 0 :: (dereferenceable invariant load (s64))
    ; GFX1250-NEXT: [[COPY9:%[0-9]+]]:vreg_64_align2 = COPY [[S_LOAD_DWORDX2_IMM9]]
    ; GFX1250-NEXT: KILL killed [[COPY5]]
    ; GFX1250-NEXT: [[GLOBAL_LOAD_DWORD9:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD [[COPY9]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX1250-NEXT: [[S_LOAD_DWORDX2_IMM10:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 80, 0 :: (dereferenceable invariant load (s64))
    ; GFX1250-NEXT: [[COPY10:%[0-9]+]]:vreg_64_align2 = COPY [[S_LOAD_DWORDX2_IMM10]]
    ; GFX1250-NEXT: KILL killed [[COPY6]]
    ; GFX1250-NEXT: [[GLOBAL_LOAD_DWORD10:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD [[COPY10]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX1250-NEXT: [[S_LOAD_DWORDX2_IMM11:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 88, 0 :: (dereferenceable invariant load (s64))
    ; GFX1250-NEXT: [[COPY11:%[0-9]+]]:vreg_64_align2 = COPY [[S_LOAD_DWORDX2_IMM11]]
    ; GFX1250-NEXT: [[GLOBAL_LOAD_DWORD11:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD [[COPY11]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX1250-NEXT: KILL killed [[COPY7]]
    ; GFX1250-NEXT: [[S_LOAD_DWORDX2_IMM12:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 96, 0 :: (dereferenceable invariant load (s64))
    ; GFX1250-NEXT: [[COPY12:%[0-9]+]]:vreg_64_align2 = COPY [[S_LOAD_DWORDX2_IMM12]]
    ; GFX1250-NEXT: [[GLOBAL_LOAD_DWORD12:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD [[COPY12]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX1250-NEXT: KILL killed [[COPY8]]
    ; GFX1250-NEXT: [[S_LOAD_DWORDX2_IMM13:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 104, 0 :: (dereferenceable invariant load (s64))
    ; GFX1250-NEXT: [[COPY13:%[0-9]+]]:vreg_64_align2 = COPY [[S_LOAD_DWORDX2_IMM13]]
    ; GFX1250-NEXT: [[GLOBAL_LOAD_DWORD13:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD [[COPY13]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX1250-NEXT: [[S_LOAD_DWORDX2_IMM14:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 112, 0 :: (dereferenceable invariant load (s64))
    ; GFX1250-NEXT: KILL killed [[COPY9]]
    ; GFX1250-NEXT: [[COPY14:%[0-9]+]]:vreg_64_align2 = COPY [[S_LOAD_DWORDX2_IMM14]]
    ; GFX1250-NEXT: [[GLOBAL_LOAD_DWORD14:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD [[COPY14]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX1250-NEXT: [[S_LOAD_DWORDX2_IMM15:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 120, 0 :: (dereferenceable invariant load (s64))
    ; GFX1250-NEXT: KILL killed [[COPY10]]
    ; GFX1250-NEXT: [[COPY15:%[0-9]+]]:vreg_64_align2 = COPY [[S_LOAD_DWORDX2_IMM15]]
    ; GFX1250-NEXT: [[GLOBAL_LOAD_DWORD15:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD [[COPY15]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX1250-NEXT: KILL killed [[COPY11]]
    ; GFX1250-NEXT: [[S_LOAD_DWORDX2_IMM16:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 128, 0 :: (dereferenceable invariant load (s64))
    ; GFX1250-NEXT: [[COPY16:%[0-9]+]]:vreg_64_align2 = COPY [[S_LOAD_DWORDX2_IMM16]]
    ; GFX1250-NEXT: [[GLOBAL_LOAD_DWORD16:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD [[COPY16]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX1250-NEXT: KILL killed [[COPY12]]
    ; GFX1250-NEXT: [[S_LOAD_DWORDX2_IMM17:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 136, 0 :: (dereferenceable invariant load (s64))
    ; GFX1250-NEXT: [[GLOBAL_LOAD_DWORD_SADDR:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM17]], [[V_MOV_B32_e32_]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX1250-NEXT: KILL killed [[COPY13]]
    ; GFX1250-NEXT: KILL killed [[COPY14]]
    ; GFX1250-NEXT: KILL killed [[COPY15]]
    ; GFX1250-NEXT: KILL killed [[COPY16]]
    ; GFX1250-NEXT: S_ENDPGM 0, implicit [[GLOBAL_LOAD_DWORD]], implicit [[GLOBAL_LOAD_DWORD1]], implicit [[GLOBAL_LOAD_DWORD2]], implicit [[GLOBAL_LOAD_DWORD3]], implicit [[GLOBAL_LOAD_DWORD4]], implicit [[GLOBAL_LOAD_DWORD5]], implicit [[GLOBAL_LOAD_DWORD6]], implicit [[GLOBAL_LOAD_DWORD7]], implicit [[GLOBAL_LOAD_DWORD8]], implicit [[GLOBAL_LOAD_DWORD9]], implicit [[GLOBAL_LOAD_DWORD10]], implicit [[GLOBAL_LOAD_DWORD11]], implicit [[GLOBAL_LOAD_DWORD12]], implicit [[GLOBAL_LOAD_DWORD13]], implicit [[GLOBAL_LOAD_DWORD14]], implicit [[GLOBAL_LOAD_DWORD15]], implicit [[GLOBAL_LOAD_DWORD16]], implicit [[GLOBAL_LOAD_DWORD_SADDR]]
    ;
    ; GFX942-LABEL: name: flush_group_kill
    ; GFX942: liveins: $sgpr0_sgpr1
    ; GFX942-NEXT: {{  $}}
    ; GFX942-NEXT: [[V_MOV_B32_e32_:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
    ; GFX942-NEXT: [[S_LOAD_DWORDX2_IMM:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 0, 0 :: (dereferenceable invariant load (s64))
    ; GFX942-NEXT: [[GLOBAL_LOAD_DWORD_SADDR:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM]], [[V_MOV_B32_e32_]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX942-NEXT: [[S_LOAD_DWORDX2_IMM1:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 8, 0 :: (dereferenceable invariant load (s64))
    ; GFX942-NEXT: [[GLOBAL_LOAD_DWORD_SADDR1:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM1]], [[V_MOV_B32_e32_]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX942-NEXT: [[S_LOAD_DWORDX2_IMM2:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 16, 0 :: (dereferenceable invariant load (s64))
    ; GFX942-NEXT: [[GLOBAL_LOAD_DWORD_SADDR2:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM2]], [[V_MOV_B32_e32_]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX942-NEXT: [[S_LOAD_DWORDX2_IMM3:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 24, 0 :: (dereferenceable invariant load (s64))
    ; GFX942-NEXT: [[GLOBAL_LOAD_DWORD_SADDR3:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM3]], [[V_MOV_B32_e32_]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX942-NEXT: [[S_LOAD_DWORDX2_IMM4:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 32, 0 :: (dereferenceable invariant load (s64))
    ; GFX942-NEXT: [[GLOBAL_LOAD_DWORD_SADDR4:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM4]], [[V_MOV_B32_e32_]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX942-NEXT: [[S_LOAD_DWORDX2_IMM5:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 40, 0 :: (dereferenceable invariant load (s64))
    ; GFX942-NEXT: [[GLOBAL_LOAD_DWORD_SADDR5:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM5]], [[V_MOV_B32_e32_]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX942-NEXT: [[S_LOAD_DWORDX2_IMM6:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 48, 0 :: (dereferenceable invariant load (s64))
    ; GFX942-NEXT: [[GLOBAL_LOAD_DWORD_SADDR6:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM6]], [[V_MOV_B32_e32_]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX942-NEXT: [[S_LOAD_DWORDX2_IMM7:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 56, 0 :: (dereferenceable invariant load (s64))
    ; GFX942-NEXT: [[GLOBAL_LOAD_DWORD_SADDR7:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM7]], [[V_MOV_B32_e32_]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX942-NEXT: [[S_LOAD_DWORDX2_IMM8:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 64, 0 :: (dereferenceable invariant load (s64))
    ; GFX942-NEXT: [[GLOBAL_LOAD_DWORD_SADDR8:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM8]], [[V_MOV_B32_e32_]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX942-NEXT: [[S_LOAD_DWORDX2_IMM9:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 72, 0 :: (dereferenceable invariant load (s64))
    ; GFX942-NEXT: [[GLOBAL_LOAD_DWORD_SADDR9:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM9]], [[V_MOV_B32_e32_]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX942-NEXT: [[S_LOAD_DWORDX2_IMM10:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 80, 0 :: (dereferenceable invariant load (s64))
    ; GFX942-NEXT: [[GLOBAL_LOAD_DWORD_SADDR10:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM10]], [[V_MOV_B32_e32_]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX942-NEXT: [[S_LOAD_DWORDX2_IMM11:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 88, 0 :: (dereferenceable invariant load (s64))
    ; GFX942-NEXT: [[GLOBAL_LOAD_DWORD_SADDR11:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM11]], [[V_MOV_B32_e32_]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX942-NEXT: [[S_LOAD_DWORDX2_IMM12:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 96, 0 :: (dereferenceable invariant load (s64))
    ; GFX942-NEXT: [[GLOBAL_LOAD_DWORD_SADDR12:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM12]], [[V_MOV_B32_e32_]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX942-NEXT: [[S_LOAD_DWORDX2_IMM13:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 104, 0 :: (dereferenceable invariant load (s64))
    ; GFX942-NEXT: [[GLOBAL_LOAD_DWORD_SADDR13:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM13]], [[V_MOV_B32_e32_]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX942-NEXT: [[S_LOAD_DWORDX2_IMM14:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 112, 0 :: (dereferenceable invariant load (s64))
    ; GFX942-NEXT: [[GLOBAL_LOAD_DWORD_SADDR14:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM14]], [[V_MOV_B32_e32_]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX942-NEXT: [[S_LOAD_DWORDX2_IMM15:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 120, 0 :: (dereferenceable invariant load (s64))
    ; GFX942-NEXT: [[GLOBAL_LOAD_DWORD_SADDR15:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM15]], [[V_MOV_B32_e32_]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX942-NEXT: [[S_LOAD_DWORDX2_IMM16:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 128, 0 :: (dereferenceable invariant load (s64))
    ; GFX942-NEXT: [[GLOBAL_LOAD_DWORD_SADDR16:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM16]], [[V_MOV_B32_e32_]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX942-NEXT: [[S_LOAD_DWORDX2_IMM17:%[0-9]+]]:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 136, 0 :: (dereferenceable invariant load (s64))
    ; GFX942-NEXT: [[GLOBAL_LOAD_DWORD_SADDR17:%[0-9]+]]:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR [[S_LOAD_DWORDX2_IMM17]], [[V_MOV_B32_e32_]], 0, 0, implicit $exec :: (load (s32), addrspace 1)
    ; GFX942-NEXT: S_ENDPGM 0, implicit [[GLOBAL_LOAD_DWORD_SADDR]], implicit [[GLOBAL_LOAD_DWORD_SADDR1]], implicit [[GLOBAL_LOAD_DWORD_SADDR2]], implicit [[GLOBAL_LOAD_DWORD_SADDR3]], implicit [[GLOBAL_LOAD_DWORD_SADDR4]], implicit [[GLOBAL_LOAD_DWORD_SADDR5]], implicit [[GLOBAL_LOAD_DWORD_SADDR6]], implicit [[GLOBAL_LOAD_DWORD_SADDR7]], implicit [[GLOBAL_LOAD_DWORD_SADDR8]], implicit [[GLOBAL_LOAD_DWORD_SADDR9]], implicit [[GLOBAL_LOAD_DWORD_SADDR10]], implicit [[GLOBAL_LOAD_DWORD_SADDR11]], implicit [[GLOBAL_LOAD_DWORD_SADDR12]], implicit [[GLOBAL_LOAD_DWORD_SADDR13]], implicit [[GLOBAL_LOAD_DWORD_SADDR14]], implicit [[GLOBAL_LOAD_DWORD_SADDR15]], implicit [[GLOBAL_LOAD_DWORD_SADDR16]], implicit [[GLOBAL_LOAD_DWORD_SADDR17]]
    %0:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
    %1:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 0, 0 :: (dereferenceable invariant load (s64))
    %2:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR %1, %0, 0, 0, implicit $exec :: (load (s32), addrspace 1)
    %3:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 8, 0 :: (dereferenceable invariant load (s64))
    %4:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR %3, %0, 0, 0, implicit $exec :: (load (s32), addrspace 1)
    %5:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 16, 0 :: (dereferenceable invariant load (s64))
    %6:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR %5, %0, 0, 0, implicit $exec :: (load (s32), addrspace 1)
    %7:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 24, 0 :: (dereferenceable invariant load (s64))
    %8:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR %7, %0, 0, 0, implicit $exec :: (load (s32), addrspace 1)
    %9:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 32, 0 :: (dereferenceable invariant load (s64))
    %10:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR %9, %0, 0, 0, implicit $exec :: (load (s32), addrspace 1)
    %11:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 40, 0 :: (dereferenceable invariant load (s64))
    %12:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR %11, %0, 0, 0, implicit $exec :: (load (s32), addrspace 1)
    %13:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 48, 0 :: (dereferenceable invariant load (s64))
    %14:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR %13, %0, 0, 0, implicit $exec :: (load (s32), addrspace 1)
    %15:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 56, 0 :: (dereferenceable invariant load (s64))
    %16:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR %15, %0, 0, 0, implicit $exec :: (load (s32), addrspace 1)
    %17:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 64, 0 :: (dereferenceable invariant load (s64))
    %18:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR %17, %0, 0, 0, implicit $exec :: (load (s32), addrspace 1)
    %19:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 72, 0 :: (dereferenceable invariant load (s64))
    %20:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR %19, %0, 0, 0, implicit $exec :: (load (s32), addrspace 1)
    %21:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 80, 0 :: (dereferenceable invariant load (s64))
    %22:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR %21, %0, 0, 0, implicit $exec :: (load (s32), addrspace 1)
    %23:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 88, 0 :: (dereferenceable invariant load (s64))
    %24:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR %23, %0, 0, 0, implicit $exec :: (load (s32), addrspace 1)
    %25:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 96, 0 :: (dereferenceable invariant load (s64))
    %26:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR %25, %0, 0, 0, implicit $exec :: (load (s32), addrspace 1)
    %27:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 104, 0 :: (dereferenceable invariant load (s64))
    %28:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR %27, %0, 0, 0, implicit $exec :: (load (s32), addrspace 1)
    %29:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 112, 0 :: (dereferenceable invariant load (s64))
    %30:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR %29, %0, 0, 0, implicit $exec :: (load (s32), addrspace 1)
    %31:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 120, 0 :: (dereferenceable invariant load (s64))
    %32:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR %31, %0, 0, 0, implicit $exec :: (load (s32), addrspace 1)
    %33:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 128, 0 :: (dereferenceable invariant load (s64))
    %34:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR %33, %0, 0, 0, implicit $exec :: (load (s32), addrspace 1)
    %35:sreg_64_xexec_xnull = S_LOAD_DWORDX2_IMM $sgpr0_sgpr1, 136, 0 :: (dereferenceable invariant load (s64))
    %36:vgpr_32 = GLOBAL_LOAD_DWORD_SADDR %35, %0, 0, 0, implicit $exec :: (load (s32), addrspace 1)
    S_ENDPGM 0, implicit %2, implicit %4, implicit %6, implicit %8, implicit %10, implicit %12, implicit %14, implicit %16, implicit %18, implicit %20, implicit %22, implicit %24, implicit %26, implicit %28, implicit %30, implicit %32, implicit %34, implicit %36
...
