# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -mtriple=amdgcn -mcpu=gfx950 -run-pass=amdgpu-pre-ra-optimizations -o - %s | FileCheck -check-prefix=UNIFIED %s
# RUN: llc -mtriple=amdgcn -mcpu=gfx908 -run-pass=amdgpu-pre-ra-optimizations -o - %s | FileCheck -check-prefix=SPLIT %s

---
name:            reconstrain
tracksRegLiveness: true
machineFunctionInfo:
  isEntryFunction: true
  scratchRSrcReg:  '$sgpr24_sgpr25_sgpr26_sgpr27'
  frameOffsetReg:  '$sgpr32'
  stackPtrOffsetReg: '$sgpr32'
  argumentInfo:
    privateSegmentBuffer: { reg: '$sgpr0_sgpr1_sgpr2_sgpr3' }
    privateSegmentWaveByteOffset: { reg: '$sgpr33' }
  maxArchVGPRPressure:  2
body:             |
  bb.0:
    liveins: $vgpr0, $vgpr1
    ; UNIFIED-LABEL: name: reconstrain
    ; UNIFIED: liveins: $vgpr0, $vgpr1
    ; UNIFIED-NEXT: {{  $}}
    ; UNIFIED-NEXT: [[DEF:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; UNIFIED-NEXT: S_NOP 0, implicit [[DEF]]
    ; UNIFIED-NEXT: S_ENDPGM 0
    ;
    ; SPLIT-LABEL: name: reconstrain
    ; SPLIT: liveins: $vgpr0, $vgpr1
    ; SPLIT-NEXT: {{  $}}
    ; SPLIT-NEXT: [[DEF:%[0-9]+]]:av_64_align2 = IMPLICIT_DEF
    ; SPLIT-NEXT: S_NOP 0, implicit [[DEF]]
    ; SPLIT-NEXT: S_ENDPGM 0
    %0:av_64_align2 = IMPLICIT_DEF
    S_NOP 0, implicit %0
    S_ENDPGM 0
...

---
name:            unspecified_yaml
tracksRegLiveness: true
machineFunctionInfo:
  isEntryFunction: true
  scratchRSrcReg:  '$sgpr24_sgpr25_sgpr26_sgpr27'
  frameOffsetReg:  '$sgpr32'
  stackPtrOffsetReg: '$sgpr32'
  argumentInfo:
    privateSegmentBuffer: { reg: '$sgpr0_sgpr1_sgpr2_sgpr3' }
    privateSegmentWaveByteOffset: { reg: '$sgpr33' }
body:             |
  bb.0:
    liveins: $vgpr0, $vgpr1
    ; UNIFIED-LABEL: name: unspecified_yaml
    ; UNIFIED: liveins: $vgpr0, $vgpr1
    ; UNIFIED-NEXT: {{  $}}
    ; UNIFIED-NEXT: [[DEF:%[0-9]+]]:av_64_align2 = IMPLICIT_DEF
    ; UNIFIED-NEXT: S_NOP 0, implicit [[DEF]]
    ; UNIFIED-NEXT: S_ENDPGM 0
    ;
    ; SPLIT-LABEL: name: unspecified_yaml
    ; SPLIT: liveins: $vgpr0, $vgpr1
    ; SPLIT-NEXT: {{  $}}
    ; SPLIT-NEXT: [[DEF:%[0-9]+]]:av_64_align2 = IMPLICIT_DEF
    ; SPLIT-NEXT: S_NOP 0, implicit [[DEF]]
    ; SPLIT-NEXT: S_ENDPGM 0
    %0:av_64_align2 = IMPLICIT_DEF
    S_NOP 0, implicit %0
    S_ENDPGM 0
...

---
name:            constrain_highrp
tracksRegLiveness: true
machineFunctionInfo:
  isEntryFunction: true
  scratchRSrcReg:  '$sgpr24_sgpr25_sgpr26_sgpr27'
  frameOffsetReg:  '$sgpr32'
  stackPtrOffsetReg: '$sgpr32'
  argumentInfo:
    privateSegmentBuffer: { reg: '$sgpr0_sgpr1_sgpr2_sgpr3' }
    privateSegmentWaveByteOffset: { reg: '$sgpr33' }
  maxArchVGPRPressure:  255
body:             |
  bb.0:
    liveins: $vgpr0, $vgpr1
    ; UNIFIED-LABEL: name: constrain_highrp
    ; UNIFIED: liveins: $vgpr0, $vgpr1
    ; UNIFIED-NEXT: {{  $}}
    ; UNIFIED-NEXT: [[DEF:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; UNIFIED-NEXT: S_NOP 0, implicit [[DEF]]
    ; UNIFIED-NEXT: S_ENDPGM 0
    ;
    ; SPLIT-LABEL: name: constrain_highrp
    ; SPLIT: liveins: $vgpr0, $vgpr1
    ; SPLIT-NEXT: {{  $}}
    ; SPLIT-NEXT: [[DEF:%[0-9]+]]:av_64_align2 = IMPLICIT_DEF
    ; SPLIT-NEXT: S_NOP 0, implicit [[DEF]]
    ; SPLIT-NEXT: S_ENDPGM 0
    %0:av_64_align2 = IMPLICIT_DEF
    S_NOP 0, implicit %0
    S_ENDPGM 0
...

---
name:            no_constrain_highrp
tracksRegLiveness: true
machineFunctionInfo:
  isEntryFunction: true
  scratchRSrcReg:  '$sgpr24_sgpr25_sgpr26_sgpr27'
  frameOffsetReg:  '$sgpr32'
  stackPtrOffsetReg: '$sgpr32'
  argumentInfo:
    privateSegmentBuffer: { reg: '$sgpr0_sgpr1_sgpr2_sgpr3' }
    privateSegmentWaveByteOffset: { reg: '$sgpr33' }
  maxArchVGPRPressure:  256
body:             |
  bb.0:
    liveins: $vgpr0, $vgpr1
    ; UNIFIED-LABEL: name: no_constrain_highrp
    ; UNIFIED: liveins: $vgpr0, $vgpr1
    ; UNIFIED-NEXT: {{  $}}
    ; UNIFIED-NEXT: [[DEF:%[0-9]+]]:av_64_align2 = IMPLICIT_DEF
    ; UNIFIED-NEXT: S_NOP 0, implicit [[DEF]]
    ; UNIFIED-NEXT: S_ENDPGM 0
    ;
    ; SPLIT-LABEL: name: no_constrain_highrp
    ; SPLIT: liveins: $vgpr0, $vgpr1
    ; SPLIT-NEXT: {{  $}}
    ; SPLIT-NEXT: [[DEF:%[0-9]+]]:av_64_align2 = IMPLICIT_DEF
    ; SPLIT-NEXT: S_NOP 0, implicit [[DEF]]
    ; SPLIT-NEXT: S_ENDPGM 0
    %0:av_64_align2 = IMPLICIT_DEF
    S_NOP 0, implicit %0
    S_ENDPGM 0
...

---
name:            no_constrain_highrp1
tracksRegLiveness: true
machineFunctionInfo:
  isEntryFunction: true
  scratchRSrcReg:  '$sgpr24_sgpr25_sgpr26_sgpr27'
  frameOffsetReg:  '$sgpr32'
  stackPtrOffsetReg: '$sgpr32'
  argumentInfo:
    privateSegmentBuffer: { reg: '$sgpr0_sgpr1_sgpr2_sgpr3' }
    privateSegmentWaveByteOffset: { reg: '$sgpr33' }
  maxArchVGPRPressure:  257
body:             |
  bb.0:
    liveins: $vgpr0, $vgpr1
    ; UNIFIED-LABEL: name: no_constrain_highrp1
    ; UNIFIED: liveins: $vgpr0, $vgpr1
    ; UNIFIED-NEXT: {{  $}}
    ; UNIFIED-NEXT: [[DEF:%[0-9]+]]:av_64_align2 = IMPLICIT_DEF
    ; UNIFIED-NEXT: S_NOP 0, implicit [[DEF]]
    ; UNIFIED-NEXT: S_ENDPGM 0
    ;
    ; SPLIT-LABEL: name: no_constrain_highrp1
    ; SPLIT: liveins: $vgpr0, $vgpr1
    ; SPLIT-NEXT: {{  $}}
    ; SPLIT-NEXT: [[DEF:%[0-9]+]]:av_64_align2 = IMPLICIT_DEF
    ; SPLIT-NEXT: S_NOP 0, implicit [[DEF]]
    ; SPLIT-NEXT: S_ENDPGM 0
    %0:av_64_align2 = IMPLICIT_DEF
    S_NOP 0, implicit %0
    S_ENDPGM 0
...

---
name:            no_constrain_use
tracksRegLiveness: true
machineFunctionInfo:
  isEntryFunction: true
  scratchRSrcReg:  '$sgpr24_sgpr25_sgpr26_sgpr27'
  frameOffsetReg:  '$sgpr32'
  stackPtrOffsetReg: '$sgpr32'
  argumentInfo:
    privateSegmentBuffer: { reg: '$sgpr0_sgpr1_sgpr2_sgpr3' }
    privateSegmentWaveByteOffset: { reg: '$sgpr33' }
  maxArchVGPRPressure:  0
body:             |
  bb.0:
    liveins: $vgpr0, $vgpr1
    ; UNIFIED-LABEL: name: no_constrain_use
    ; UNIFIED: liveins: $vgpr0, $vgpr1
    ; UNIFIED-NEXT: {{  $}}
    ; UNIFIED-NEXT: [[DEF:%[0-9]+]]:av_64_align2 = IMPLICIT_DEF
    ; UNIFIED-NEXT: INLINEASM &"; use $0", 0 /* attdialect */, 3473417 /* reguse:AReg_64 */, [[DEF]]
    ; UNIFIED-NEXT: S_NOP 0, implicit [[DEF]]
    ; UNIFIED-NEXT: S_ENDPGM 0
    ;
    ; SPLIT-LABEL: name: no_constrain_use
    ; SPLIT: liveins: $vgpr0, $vgpr1
    ; SPLIT-NEXT: {{  $}}
    ; SPLIT-NEXT: [[DEF:%[0-9]+]]:av_64_align2 = IMPLICIT_DEF
    ; SPLIT-NEXT: INLINEASM &"; use $0", 0 /* attdialect */, 3473417 /* reguse:AReg_64 */, [[DEF]]
    ; SPLIT-NEXT: S_NOP 0, implicit [[DEF]]
    ; SPLIT-NEXT: S_ENDPGM 0
    %0:av_64_align2 = IMPLICIT_DEF
    INLINEASM &"; use $0", 0 /* attdialect */, 3473417 /* reguse:AReg_64 */, %0
    S_NOP 0, implicit %0
    S_ENDPGM 0
...
