# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc %s -mtriple=amdgcn -mcpu=gfx1030 -run-pass=si-peephole-sdwa -o - | FileCheck %s

# For conversion of_CNDMASK_B32_e64 to SDWA, the destination of V_CMP_O_F16_e64 must be
# changed to vcc_lo first. This would introduce a vcc_hi use that requires special
# handling in si-peephole-sdwa.

---
name: v_minimum_v2f16__nsz
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $vgpr0, $vgpr1

    ; CHECK-LABEL: name: v_minimum_v2f16__nsz
    ; CHECK: liveins: $vgpr0, $vgpr1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[DEF:%[0-9]+]]:vgpr_32 = IMPLICIT_DEF
    ; CHECK-NEXT: [[DEF1:%[0-9]+]]:sreg_32_xm0_xexec = IMPLICIT_DEF
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; CHECK-NEXT: [[V_PK_MIN_F16_:%[0-9]+]]:vgpr_32 = V_PK_MIN_F16 8, [[COPY]], 8, undef [[DEF]], 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    ; CHECK-NEXT: [[V_CNDMASK_B32_e64_:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, 32256, 0, [[V_PK_MIN_F16_]], killed undef [[DEF1]], implicit $exec
    ; CHECK-NEXT: [[V_LSHRREV_B32_e64_:%[0-9]+]]:vgpr_32 = V_LSHRREV_B32_e64 16, [[COPY]], implicit $exec
    ; CHECK-NEXT: [[V_CMP_O_F16_sdwa:%[0-9]+]]:sreg_32_xm0_xexec = V_CMP_O_F16_sdwa 0, [[COPY]], 0, undef [[V_CNDMASK_B32_e64_]], 0, 5, 6, implicit $mode, implicit $exec
    ; CHECK-NEXT: [[V_LSHRREV_B32_e64_1:%[0-9]+]]:vgpr_32 = V_LSHRREV_B32_e64 16, undef [[V_PK_MIN_F16_]], implicit $exec
    ; CHECK-NEXT: [[V_CNDMASK_B32_e64_1:%[0-9]+]]:vgpr_32 = V_CNDMASK_B32_e64 0, 32256, 0, undef [[V_LSHRREV_B32_e64_1]], killed undef [[V_CMP_O_F16_sdwa]], implicit $exec
    ; CHECK-NEXT: [[V_PERM_B32_e64_:%[0-9]+]]:vgpr_32 = V_PERM_B32_e64 killed [[V_CNDMASK_B32_e64_1]], [[V_CNDMASK_B32_e64_]], 84148480, implicit $exec
    ; CHECK-NEXT: $vgpr0 = COPY [[V_PERM_B32_e64_]]
    ; CHECK-NEXT: SI_RETURN implicit $vgpr0
    %30:vgpr_32 = IMPLICIT_DEF
    %31:sreg_32_xm0_xexec = IMPLICIT_DEF
    %8:vgpr_32 = COPY $vgpr0
    %13:vgpr_32 = V_PK_MIN_F16 8, %8, 8, undef %30, 0, 0, 0, 0, 0, implicit $mode, implicit $exec
    %16:vgpr_32 = V_CNDMASK_B32_e64 0, 32256, 0, %13, killed undef %31, implicit $exec
    %20:vgpr_32 = V_LSHRREV_B32_e64 16, %8, implicit $exec
    %22:sreg_32_xm0_xexec = V_CMP_O_F16_e64 0, undef %20, 0, undef %16, 0, implicit $mode, implicit $exec
    %23:vgpr_32 = V_LSHRREV_B32_e64 16, undef %13, implicit $exec
    %25:vgpr_32 = V_CNDMASK_B32_e64 0, 32256, 0, undef %23, killed undef %22, implicit $exec
    %27:vgpr_32 = V_PERM_B32_e64 killed %25, killed %16, 84148480, implicit $exec
    $vgpr0 = COPY %27
    SI_RETURN implicit $vgpr0

...
