# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=amdgcn -mcpu=gfx1250 -mattr=+real-true16 -run-pass=si-shrink-instructions -verify-machineinstrs %s -o - | FileCheck %s

# Test folding complementary V_PERM_B32_e64 pairs into V_SWAP_B16.

---
name: perm_to_swap
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $vgpr0, $vgpr1
    ; CHECK-LABEL: name: perm_to_swap
    ; CHECK: liveins: $vgpr0, $vgpr1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vgpr_32_lo128 = COPY $vgpr0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vgpr_32_lo128 = COPY $vgpr1
    ; CHECK-NEXT: [[V_SWAP_B16_:%[0-9]+]]:vgpr_16_lo128, [[V_SWAP_B16_1:%[0-9]+]]:vgpr_16_lo128 = V_SWAP_B16 [[COPY]].lo16, [[COPY1]].hi16, implicit $exec
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vgpr_32 = REG_SEQUENCE [[V_SWAP_B16_]], %subreg.hi16, [[COPY1]].lo16, %subreg.lo16
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:vgpr_32 = REG_SEQUENCE [[V_SWAP_B16_1]], %subreg.lo16, [[COPY]].hi16, %subreg.hi16
    ; CHECK-NEXT: S_NOP 0, implicit [[REG_SEQUENCE]], implicit [[REG_SEQUENCE1]]
    %0:vgpr_32 = COPY $vgpr0
    %1:vgpr_32 = COPY $vgpr1
    %2:vgpr_32 = V_PERM_B32_e64 %0, %1, 84148480, implicit $exec   ; 0x05040100
    %3:vgpr_32 = V_PERM_B32_e64 %0, %1, 117834498, implicit $exec  ; 0x07060302
    S_NOP 0, implicit %2, implicit %3
...

---
name: perm_to_swap_subreg
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $vgpr0_vgpr1_vgpr2_vgpr3
    ; CHECK-LABEL: name: perm_to_swap_subreg
    ; CHECK: liveins: $vgpr0_vgpr1_vgpr2_vgpr3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:av_128_with_sub0_sub1_sub2_in_av_96_align2_and_av_96_with_sub2_in_vgpr_32_lo128 = COPY $vgpr0_vgpr1_vgpr2_vgpr3
    ; CHECK-NEXT: [[V_SWAP_B16_:%[0-9]+]]:vgpr_16_lo128, [[V_SWAP_B16_1:%[0-9]+]]:vgpr_16_lo128 = V_SWAP_B16 [[COPY]].sub1_hi16, [[COPY]].sub3_lo16, implicit $exec
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vgpr_32 = REG_SEQUENCE [[V_SWAP_B16_]], %subreg.lo16, [[COPY]].sub3_hi16, %subreg.hi16
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:vgpr_32 = REG_SEQUENCE [[V_SWAP_B16_1]], %subreg.hi16, [[COPY]].sub1_lo16, %subreg.lo16
    ; CHECK-NEXT: [[V_SWAP_B16_2:%[0-9]+]]:vgpr_16_lo128, [[V_SWAP_B16_3:%[0-9]+]]:vgpr_16_lo128 = V_SWAP_B16 [[COPY]].hi16, [[COPY]].sub2_lo16, implicit $exec
    ; CHECK-NEXT: [[REG_SEQUENCE2:%[0-9]+]]:vgpr_32 = REG_SEQUENCE [[V_SWAP_B16_2]], %subreg.lo16, [[COPY]].sub2_hi16, %subreg.hi16
    ; CHECK-NEXT: [[REG_SEQUENCE3:%[0-9]+]]:vgpr_32 = REG_SEQUENCE [[V_SWAP_B16_3]], %subreg.hi16, [[COPY]].lo16, %subreg.lo16
    ; CHECK-NEXT: S_NOP 0, implicit [[REG_SEQUENCE]], implicit [[REG_SEQUENCE1]], implicit [[REG_SEQUENCE2]], implicit [[REG_SEQUENCE3]]
    %0:vreg_128_align2 = COPY $vgpr0_vgpr1_vgpr2_vgpr3
    %1:vgpr_32 = V_PERM_B32_e64 %0.sub1, %0.sub3, 50464518, implicit $exec   ; 0x03020706
    %2:vgpr_32 = V_PERM_B32_e64 %0.sub1, %0.sub3, 16778500, implicit $exec   ; 0x01000504
    %3:vgpr_32 = V_PERM_B32_e64 %0.sub0, %0.sub2, 50464518, implicit $exec   ; 0x03020706
    %4:vgpr_32 = V_PERM_B32_e64 %0.sub0, %0.sub2, 16778500, implicit $exec   ; 0x01000504
    S_NOP 0, implicit %1, implicit %2, implicit %3, implicit %4
...

---
name: perm_to_swap_separated
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3
    ; CHECK-LABEL: name: perm_to_swap_separated
    ; CHECK: liveins: $vgpr0, $vgpr1, $vgpr2, $vgpr3
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vgpr_32_lo128 = COPY $vgpr0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vgpr_32_lo128 = COPY $vgpr1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr2
    ; CHECK-NEXT: [[COPY3:%[0-9]+]]:vgpr_32 = COPY $vgpr3
    ; CHECK-NEXT: [[V_SWAP_B16_:%[0-9]+]]:vgpr_16_lo128, [[V_SWAP_B16_1:%[0-9]+]]:vgpr_16_lo128 = V_SWAP_B16 [[COPY]].lo16, [[COPY1]].hi16, implicit $exec
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vgpr_32 = REG_SEQUENCE [[V_SWAP_B16_]], %subreg.hi16, [[COPY1]].lo16, %subreg.lo16
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:vgpr_32 = REG_SEQUENCE [[V_SWAP_B16_1]], %subreg.lo16, [[COPY]].hi16, %subreg.hi16
    ; CHECK-NEXT: [[V_ADD_U32_e32_:%[0-9]+]]:vgpr_32 = V_ADD_U32_e32 [[COPY2]], [[COPY3]], implicit $exec
    ; CHECK-NEXT: S_NOP 0, implicit [[REG_SEQUENCE]], implicit [[V_ADD_U32_e32_]], implicit [[REG_SEQUENCE1]]
    %0:vgpr_32 = COPY $vgpr0
    %1:vgpr_32 = COPY $vgpr1
    %2:vgpr_32 = COPY $vgpr2
    %3:vgpr_32 = COPY $vgpr3
    %4:vgpr_32 = V_PERM_B32_e64 %0, %1, 84148480, implicit $exec   ; 0x05040100
    %5:vgpr_32 = V_ADD_U32_e64 %2, %3, 0, implicit $exec
    %6:vgpr_32 = V_PERM_B32_e64 %0, %1, 117834498, implicit $exec  ; 0x07060302
    S_NOP 0, implicit %4, implicit %5, implicit %6
...

---
name: perm_to_swap_reversed_operands
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $vgpr0, $vgpr1
    ; CHECK-LABEL: name: perm_to_swap_reversed_operands
    ; CHECK: liveins: $vgpr0, $vgpr1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vgpr_32_lo128 = COPY $vgpr0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vgpr_32_lo128 = COPY $vgpr1
    ; CHECK-NEXT: [[V_SWAP_B16_:%[0-9]+]]:vgpr_16_lo128, [[V_SWAP_B16_1:%[0-9]+]]:vgpr_16_lo128 = V_SWAP_B16 [[COPY1]].hi16, [[COPY]].lo16, implicit $exec
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vgpr_32 = REG_SEQUENCE [[V_SWAP_B16_]], %subreg.lo16, [[COPY]].hi16, %subreg.hi16
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:vgpr_32 = REG_SEQUENCE [[V_SWAP_B16_1]], %subreg.hi16, [[COPY1]].lo16, %subreg.lo16
    ; CHECK-NEXT: S_NOP 0, implicit [[REG_SEQUENCE1]], implicit [[REG_SEQUENCE]]
    %0:vgpr_32 = COPY $vgpr0
    %1:vgpr_32 = COPY $vgpr1
    %2:vgpr_32 = V_PERM_B32_e64 %0, %1, 84148480, implicit $exec   ; 0x05040100
    %3:vgpr_32 = V_PERM_B32_e64 %1, %0, 50464518, implicit $exec   ; 0x03020706 (reversed operands)
    S_NOP 0, implicit %2, implicit %3
...

---
name: perm_no_swap_exec_mod
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $vgpr0, $vgpr1, $sgpr0
    ; CHECK-LABEL: name: perm_no_swap_exec_mod
    ; CHECK: liveins: $vgpr0, $vgpr1, $sgpr0
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
    ; CHECK-NEXT: [[COPY2:%[0-9]+]]:sgpr_32 = COPY $sgpr0
    ; CHECK-NEXT: [[V_PERM_B32_e64_:%[0-9]+]]:vgpr_32 = V_PERM_B32_e64 [[COPY]], [[COPY1]], 84148480, implicit $exec
    ; CHECK-NEXT: $exec_lo = S_MOV_B32 [[COPY2]]
    ; CHECK-NEXT: [[V_PERM_B32_e64_1:%[0-9]+]]:vgpr_32 = V_PERM_B32_e64 [[COPY]], [[COPY1]], 117834498, implicit $exec
    ; CHECK-NEXT: S_NOP 0, implicit [[V_PERM_B32_e64_]], implicit [[V_PERM_B32_e64_1]]
    %0:vgpr_32 = COPY $vgpr0
    %1:vgpr_32 = COPY $vgpr1
    %2:sgpr_32 = COPY $sgpr0
    %3:vgpr_32 = V_PERM_B32_e64 %0, %1, 84148480, implicit $exec   ; 0x05040100
    $exec_lo = S_MOV_B32 %2
    %4:vgpr_32 = V_PERM_B32_e64 %0, %1, 117834498, implicit $exec  ; 0x07060302
    S_NOP 0, implicit %3, implicit %4
...

---
name: perm_to_swap_materialized_mask
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $vgpr0, $vgpr1
    ; CHECK-LABEL: name: perm_to_swap_materialized_mask
    ; CHECK: liveins: $vgpr0, $vgpr1
    ; CHECK-NEXT: {{  $}}
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:vgpr_32_lo128 = COPY $vgpr0
    ; CHECK-NEXT: [[COPY1:%[0-9]+]]:vgpr_32_lo128 = COPY $vgpr1
    ; CHECK-NEXT: [[V_MOV_B32_e32_:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 84148480, implicit $exec
    ; CHECK-NEXT: [[V_MOV_B32_e32_1:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 117834498, implicit $exec
    ; CHECK-NEXT: [[V_SWAP_B16_:%[0-9]+]]:vgpr_16_lo128, [[V_SWAP_B16_1:%[0-9]+]]:vgpr_16_lo128 = V_SWAP_B16 [[COPY]].lo16, [[COPY1]].hi16, implicit $exec
    ; CHECK-NEXT: [[REG_SEQUENCE:%[0-9]+]]:vgpr_32 = REG_SEQUENCE [[V_SWAP_B16_]], %subreg.hi16, [[COPY1]].lo16, %subreg.lo16
    ; CHECK-NEXT: [[REG_SEQUENCE1:%[0-9]+]]:vgpr_32 = REG_SEQUENCE [[V_SWAP_B16_1]], %subreg.lo16, [[COPY]].hi16, %subreg.hi16
    ; CHECK-NEXT: S_NOP 0, implicit [[REG_SEQUENCE]], implicit [[REG_SEQUENCE1]]
    %0:vgpr_32 = COPY $vgpr0
    %1:vgpr_32 = COPY $vgpr1
    %2:vgpr_32 = V_MOV_B32_e32 84148480, implicit $exec   ; 0x05040100
    %3:vgpr_32 = V_MOV_B32_e32 117834498, implicit $exec  ; 0x07060302
    %4:vgpr_32 = V_PERM_B32_e64 %0, %1, %2, implicit $exec
    %5:vgpr_32 = V_PERM_B32_e64 %0, %1, %3, implicit $exec
    S_NOP 0, implicit %4, implicit %5
...
