# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 3
# RUN: llc -mtriple=amdgcn -mcpu=gfx1250 -run-pass si-shrink-instructions -verify-machineinstrs %s -o - | FileCheck %s -check-prefix=GFX1250

---
name: fma_cvv_f64
body: |
  bb.0:
    ; GFX1250-LABEL: name: fma_cvv_f64
    ; GFX1250: $vgpr0_vgpr1 = IMPLICIT_DEF
    ; GFX1250-NEXT: $vgpr2_vgpr3 = IMPLICIT_DEF
    ; GFX1250-NEXT: $vgpr4_vgpr5 = V_FMAMK_F64 $vgpr0_vgpr1, 4638355772470722560, $vgpr2_vgpr3, implicit $mode, implicit $exec
    ; GFX1250-NEXT: SI_RETURN implicit $vgpr4_vgpr5
    $vgpr0_vgpr1 = IMPLICIT_DEF
    $vgpr2_vgpr3 = IMPLICIT_DEF
    $vgpr4_vgpr5 = V_FMA_F64_e64 0, 4638355772470722560, 0, $vgpr0_vgpr1, 0, $vgpr2_vgpr3, 0, 0, implicit $mode, implicit $exec
    SI_RETURN implicit $vgpr4_vgpr5
...

---
name: fma_vcv_f64
body: |
  bb.0:
    ; GFX1250-LABEL: name: fma_vcv_f64
    ; GFX1250: $vgpr0_vgpr1 = IMPLICIT_DEF
    ; GFX1250-NEXT: $vgpr2_vgpr3 = IMPLICIT_DEF
    ; GFX1250-NEXT: $vgpr4_vgpr5 = V_FMAMK_F64 $vgpr0_vgpr1, 4638355772470722560, $vgpr2_vgpr3, implicit $mode, implicit $exec
    ; GFX1250-NEXT: SI_RETURN implicit $vgpr4_vgpr5
    $vgpr0_vgpr1 = IMPLICIT_DEF
    $vgpr2_vgpr3 = IMPLICIT_DEF
    $vgpr4_vgpr5 = V_FMA_F64_e64 0, $vgpr0_vgpr1, 0, 4638355772470722560, 0, $vgpr2_vgpr3, 0, 0, implicit $mode, implicit $exec
    SI_RETURN implicit $vgpr4_vgpr5
...

---
name: fma_vvc_f64
body: |
  bb.0:
    ; GFX1250-LABEL: name: fma_vvc_f64
    ; GFX1250: $vgpr0_vgpr1 = IMPLICIT_DEF
    ; GFX1250-NEXT: $vgpr2_vgpr3 = IMPLICIT_DEF
    ; GFX1250-NEXT: $vgpr4_vgpr5 = V_FMAAK_F64 $vgpr0_vgpr1, $vgpr2_vgpr3, 4638355772470722560, implicit $mode, implicit $exec
    ; GFX1250-NEXT: SI_RETURN implicit $vgpr4_vgpr5
    $vgpr0_vgpr1 = IMPLICIT_DEF
    $vgpr2_vgpr3 = IMPLICIT_DEF
    $vgpr4_vgpr5 = V_FMA_F64_e64 0, $vgpr0_vgpr1, 0, $vgpr2_vgpr3, 0, 4638355772470722560, 0, 0, implicit $mode, implicit $exec
    SI_RETURN implicit $vgpr4_vgpr5
...

---
name: fma_vsc_f64
body: |
  bb.0:
    ; GFX1250-LABEL: name: fma_vsc_f64
    ; GFX1250: $vgpr0_vgpr1 = IMPLICIT_DEF
    ; GFX1250-NEXT: $vgpr2_vgpr3 = IMPLICIT_DEF
    ; GFX1250-NEXT: $vgpr4_vgpr5 = V_FMAAK_F64 $vgpr0_vgpr1, $vgpr2_vgpr3, 4638355772470722560, implicit $mode, implicit $exec
    ; GFX1250-NEXT: SI_RETURN implicit $vgpr4_vgpr5
    $vgpr0_vgpr1 = IMPLICIT_DEF
    $vgpr2_vgpr3 = IMPLICIT_DEF
    $vgpr4_vgpr5 = V_FMA_F64_e64 0, $vgpr0_vgpr1, 0, $vgpr2_vgpr3, 0, 4638355772470722560, 0, 0, implicit $mode, implicit $exec
    SI_RETURN implicit $vgpr4_vgpr5
...
