# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx90a -run-pass=si-fold-operands -verify-machineinstrs -o - %s | FileCheck -check-prefix=GFX90A %s
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx900 -run-pass=si-fold-operands -verify-machineinstrs -o - %s | FileCheck -check-prefix=GFX900 %s

# Test that V_FMAC is converted to V_FMA when accumulator is dead,
# but preserved when accumulator feeds a PHI (loop-carried dependency).

# Simple case: accumulator is not used after FMA - should convert to v_fma_f64
---
name:            fmac_no_use_accumulator
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $vgpr0_vgpr1, $vgpr2_vgpr3, $vgpr4_vgpr5
    ; GFX90A-LABEL: name: fmac_no_use_accumulator
    ; GFX90A: liveins: $vgpr0_vgpr1, $vgpr2_vgpr3, $vgpr4_vgpr5
    ; GFX90A-NEXT: {{  $}}
    ; GFX90A-NEXT: [[COPY:%[0-9]+]]:vreg_64_align2 = COPY $vgpr4_vgpr5
    ; GFX90A-NEXT: [[COPY1:%[0-9]+]]:vreg_64_align2 = COPY $vgpr2_vgpr3
    ; GFX90A-NEXT: [[COPY2:%[0-9]+]]:vreg_64_align2 = COPY $vgpr0_vgpr1
    ; GFX90A-NEXT: [[V_FMA_F64_e64_:%[0-9]+]]:vreg_64_align2 = nofpexcept V_FMA_F64_e64 0, killed [[COPY2]], 0, [[COPY1]], 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX90A-NEXT: $vgpr0 = COPY [[V_FMA_F64_e64_]].sub0
    ; GFX90A-NEXT: $vgpr1 = COPY [[V_FMA_F64_e64_]].sub1
    ; GFX90A-NEXT: SI_RETURN implicit $vgpr0, implicit $vgpr1
    ;
    ; GFX900-LABEL: name: fmac_no_use_accumulator
    ; GFX900: liveins: $vgpr0_vgpr1, $vgpr2_vgpr3, $vgpr4_vgpr5
    ; GFX900-NEXT: {{  $}}
    ; GFX900-NEXT: [[COPY:%[0-9]+]]:vreg_64_align2 = COPY $vgpr4_vgpr5
    ; GFX900-NEXT: [[COPY1:%[0-9]+]]:vreg_64_align2 = COPY $vgpr2_vgpr3
    ; GFX900-NEXT: [[COPY2:%[0-9]+]]:vreg_64_align2 = COPY $vgpr0_vgpr1
    ; GFX900-NEXT: [[V_FMAC_F64_e64_:%[0-9]+]]:vreg_64_align2 = nofpexcept V_FMAC_F64_e64 0, killed [[COPY2]], 0, [[COPY1]], 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX900-NEXT: $vgpr0 = COPY [[V_FMAC_F64_e64_]].sub0
    ; GFX900-NEXT: $vgpr1 = COPY [[V_FMAC_F64_e64_]].sub1
    ; GFX900-NEXT: SI_RETURN implicit $vgpr0, implicit $vgpr1
    %30:vreg_64_align2 = COPY $vgpr4_vgpr5
    %29:vreg_64_align2 = COPY $vgpr2_vgpr3
    %28:vreg_64_align2 = COPY $vgpr0_vgpr1
    %17:vreg_64_align2 = nofpexcept V_FMAC_F64_e64 0, killed %28, 0, %29, 0, %30, 0, 0, implicit $mode, implicit $exec
    $vgpr0 = COPY %17.sub0
    $vgpr1 = COPY %17.sub1
    SI_RETURN implicit $vgpr0, implicit $vgpr1
...

# F32 variant: accumulator is unused - should convert to v_fma_f32
---
name:            fmac_no_use_accumulator_f32
tracksRegLiveness: true
body:             |
  bb.0:
    liveins: $vgpr0, $vgpr1, $vgpr2
    ; GFX90A-LABEL: name: fmac_no_use_accumulator_f32
    ; GFX90A: liveins: $vgpr0, $vgpr1, $vgpr2
    ; GFX90A-NEXT: {{  $}}
    ; GFX90A-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr2
    ; GFX90A-NEXT: [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
    ; GFX90A-NEXT: [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX90A-NEXT: [[V_FMA_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_FMA_F32_e64 0, [[COPY2]], 0, [[COPY1]], 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX90A-NEXT: $vgpr0 = COPY [[V_FMA_F32_e64_]]
    ; GFX90A-NEXT: SI_RETURN implicit $vgpr0
    ;
    ; GFX900-LABEL: name: fmac_no_use_accumulator_f32
    ; GFX900: liveins: $vgpr0, $vgpr1, $vgpr2
    ; GFX900-NEXT: {{  $}}
    ; GFX900-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr2
    ; GFX900-NEXT: [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
    ; GFX900-NEXT: [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX900-NEXT: [[V_FMAC_F32_e64_:%[0-9]+]]:vgpr_32 = nofpexcept V_FMAC_F32_e64 0, [[COPY2]], 0, [[COPY1]], 0, [[COPY]], 0, 0, implicit $mode, implicit $exec
    ; GFX900-NEXT: $vgpr0 = COPY [[V_FMAC_F32_e64_]]
    ; GFX900-NEXT: SI_RETURN implicit $vgpr0
    %10:vgpr_32 = COPY $vgpr2
    %9:vgpr_32 = COPY $vgpr1
    %8:vgpr_32 = COPY $vgpr0
    %11:vgpr_32 = nofpexcept V_FMAC_F32_e64 0, %8, 0, %9, 0, %10, 0, 0, implicit $mode, implicit $exec
    $vgpr0 = COPY %11
    SI_RETURN implicit $vgpr0
...

# Loop case: accumulator feeds PHI - should preserve v_fmac_f64
---
name: fmac_loop_accumulator
tracksRegLiveness: true
body: |
  ; GFX90A-LABEL: name: fmac_loop_accumulator
  ; GFX90A: bb.0:
  ; GFX90A-NEXT:   successors: %bb.1(0x80000000)
  ; GFX90A-NEXT:   liveins: $vgpr0_vgpr1, $vgpr2_vgpr3, $vgpr4_vgpr5, $sgpr0
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   [[COPY:%[0-9]+]]:vreg_64_align2 = COPY $vgpr0_vgpr1
  ; GFX90A-NEXT:   [[COPY1:%[0-9]+]]:vreg_64_align2 = COPY $vgpr2_vgpr3
  ; GFX90A-NEXT:   [[COPY2:%[0-9]+]]:vreg_64_align2 = COPY $vgpr4_vgpr5
  ; GFX90A-NEXT:   [[COPY3:%[0-9]+]]:sreg_32 = COPY $sgpr0
  ; GFX90A-NEXT:   S_BRANCH %bb.1
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT: bb.1:
  ; GFX90A-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   [[PHI:%[0-9]+]]:vreg_64_align2 = PHI [[COPY2]], %bb.0, %5, %bb.1
  ; GFX90A-NEXT:   [[V_FMAC_F64_e64_:%[0-9]+]]:vreg_64_align2 = nofpexcept V_FMAC_F64_e64 0, [[COPY]], 0, [[COPY1]], 0, [[PHI]], 0, 0, implicit $mode, implicit $exec
  ; GFX90A-NEXT:   [[S_ADD_I32_:%[0-9]+]]:sreg_32 = S_ADD_I32 [[COPY3]], 1, implicit-def dead $scc
  ; GFX90A-NEXT:   S_CMP_LT_I32 [[S_ADD_I32_]], 100, implicit-def $scc
  ; GFX90A-NEXT:   S_CBRANCH_SCC1 %bb.1, implicit $scc
  ; GFX90A-NEXT:   S_BRANCH %bb.2
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT: bb.2:
  ; GFX90A-NEXT:   $vgpr0_vgpr1 = COPY [[V_FMAC_F64_e64_]]
  ; GFX90A-NEXT:   S_ENDPGM 0, implicit $vgpr0_vgpr1
  ;
  ; GFX900-LABEL: name: fmac_loop_accumulator
  ; GFX900: bb.0:
  ; GFX900-NEXT:   successors: %bb.1(0x80000000)
  ; GFX900-NEXT:   liveins: $vgpr0_vgpr1, $vgpr2_vgpr3, $vgpr4_vgpr5, $sgpr0
  ; GFX900-NEXT: {{  $}}
  ; GFX900-NEXT:   [[COPY:%[0-9]+]]:vreg_64_align2 = COPY $vgpr0_vgpr1
  ; GFX900-NEXT:   [[COPY1:%[0-9]+]]:vreg_64_align2 = COPY $vgpr2_vgpr3
  ; GFX900-NEXT:   [[COPY2:%[0-9]+]]:vreg_64_align2 = COPY $vgpr4_vgpr5
  ; GFX900-NEXT:   [[COPY3:%[0-9]+]]:sreg_32 = COPY $sgpr0
  ; GFX900-NEXT:   S_BRANCH %bb.1
  ; GFX900-NEXT: {{  $}}
  ; GFX900-NEXT: bb.1:
  ; GFX900-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; GFX900-NEXT: {{  $}}
  ; GFX900-NEXT:   [[PHI:%[0-9]+]]:vreg_64_align2 = PHI [[COPY2]], %bb.0, %5, %bb.1
  ; GFX900-NEXT:   [[V_FMAC_F64_e64_:%[0-9]+]]:vreg_64_align2 = nofpexcept V_FMAC_F64_e64 0, [[COPY]], 0, [[COPY1]], 0, [[PHI]], 0, 0, implicit $mode, implicit $exec
  ; GFX900-NEXT:   [[S_ADD_I32_:%[0-9]+]]:sreg_32 = S_ADD_I32 [[COPY3]], 1, implicit-def dead $scc
  ; GFX900-NEXT:   S_CMP_LT_I32 [[S_ADD_I32_]], 100, implicit-def $scc
  ; GFX900-NEXT:   S_CBRANCH_SCC1 %bb.1, implicit $scc
  ; GFX900-NEXT:   S_BRANCH %bb.2
  ; GFX900-NEXT: {{  $}}
  ; GFX900-NEXT: bb.2:
  ; GFX900-NEXT:   $vgpr0_vgpr1 = COPY [[V_FMAC_F64_e64_]]
  ; GFX900-NEXT:   S_ENDPGM 0, implicit $vgpr0_vgpr1
  bb.0:
    liveins: $vgpr0_vgpr1, $vgpr2_vgpr3, $vgpr4_vgpr5, $sgpr0
    successors: %bb.1
    %0:vreg_64_align2 = COPY $vgpr0_vgpr1
    %1:vreg_64_align2 = COPY $vgpr2_vgpr3
    %2:vreg_64_align2 = COPY $vgpr4_vgpr5
    %4:sreg_32 = COPY $sgpr0
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.1, %bb.2
    ; PHI node creates loop-carried dependency
    %3:vreg_64_align2 = PHI %2, %bb.0, %5, %bb.1
    %5:vreg_64_align2 = nofpexcept V_FMAC_F64_e64 0, %0, 0, %1, 0, %3, 0, 0, implicit $mode, implicit $exec
    %6:sreg_32 = S_ADD_I32 %4, 1, implicit-def dead $scc
    S_CMP_LT_I32 %6, 100, implicit-def $scc
    S_CBRANCH_SCC1 %bb.1, implicit $scc
    S_BRANCH %bb.2

  bb.2:
    $vgpr0_vgpr1 = COPY %5
    S_ENDPGM 0, implicit $vgpr0_vgpr1
...

# Accumulator used after in same BB - should preserve v_fmac
---
name: fmac_accumulator_used_after_same_bb
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $vgpr0_vgpr1, $vgpr2_vgpr3, $vgpr4_vgpr5
    ; GFX90A-LABEL: name: fmac_accumulator_used_after_same_bb
    ; GFX90A: liveins: $vgpr0_vgpr1, $vgpr2_vgpr3, $vgpr4_vgpr5
    ; GFX90A-NEXT: {{  $}}
    ; GFX90A-NEXT: [[COPY:%[0-9]+]]:vreg_64_align2 = COPY $vgpr0_vgpr1
    ; GFX90A-NEXT: [[COPY1:%[0-9]+]]:vreg_64_align2 = COPY $vgpr2_vgpr3
    ; GFX90A-NEXT: [[COPY2:%[0-9]+]]:vreg_64_align2 = COPY $vgpr4_vgpr5
    ; GFX90A-NEXT: [[V_FMAC_F64_e64_:%[0-9]+]]:vreg_64_align2 = nofpexcept V_FMAC_F64_e64 0, [[COPY]], 0, [[COPY1]], 0, [[COPY2]], 0, 0, implicit $mode, implicit $exec
    ; GFX90A-NEXT: [[V_ADD_F64_e64_:%[0-9]+]]:vreg_64_align2 = nofpexcept V_ADD_F64_e64 0, [[COPY2]], 0, [[COPY1]], 0, 0, implicit $mode, implicit $exec
    ; GFX90A-NEXT: $vgpr0_vgpr1 = COPY [[V_ADD_F64_e64_]]
    ; GFX90A-NEXT: S_ENDPGM 0, implicit $vgpr0_vgpr1
    ;
    ; GFX900-LABEL: name: fmac_accumulator_used_after_same_bb
    ; GFX900: liveins: $vgpr0_vgpr1, $vgpr2_vgpr3, $vgpr4_vgpr5
    ; GFX900-NEXT: {{  $}}
    ; GFX900-NEXT: [[COPY:%[0-9]+]]:vreg_64_align2 = COPY $vgpr0_vgpr1
    ; GFX900-NEXT: [[COPY1:%[0-9]+]]:vreg_64_align2 = COPY $vgpr2_vgpr3
    ; GFX900-NEXT: [[COPY2:%[0-9]+]]:vreg_64_align2 = COPY $vgpr4_vgpr5
    ; GFX900-NEXT: [[V_FMAC_F64_e64_:%[0-9]+]]:vreg_64_align2 = nofpexcept V_FMAC_F64_e64 0, [[COPY]], 0, [[COPY1]], 0, [[COPY2]], 0, 0, implicit $mode, implicit $exec
    ; GFX900-NEXT: [[V_ADD_F64_e64_:%[0-9]+]]:vreg_64_align2 = nofpexcept V_ADD_F64_e64 0, [[COPY2]], 0, [[COPY1]], 0, 0, implicit $mode, implicit $exec
    ; GFX900-NEXT: $vgpr0_vgpr1 = COPY [[V_ADD_F64_e64_]]
    ; GFX900-NEXT: S_ENDPGM 0, implicit $vgpr0_vgpr1
    %0:vreg_64_align2 = COPY $vgpr0_vgpr1
    %1:vreg_64_align2 = COPY $vgpr2_vgpr3
    %2:vreg_64_align2 = COPY $vgpr4_vgpr5
    %3:vreg_64_align2 = nofpexcept V_FMAC_F64_e64 0, %0, 0, %1, 0, %2, 0, 0, implicit $mode, implicit $exec
    %4:vreg_64_align2 = nofpexcept V_ADD_F64_e64 0, %2, 0, %1, 0, 0, implicit $mode, implicit $exec
    $vgpr0_vgpr1 = COPY %4
    S_ENDPGM 0, implicit $vgpr0_vgpr1
...

# Accumulator live across BBs - should preserve v_fmac
---
name: fmac_accumulator_live_across_bb
tracksRegLiveness: true
body: |
  ; GFX90A-LABEL: name: fmac_accumulator_live_across_bb
  ; GFX90A: bb.0:
  ; GFX90A-NEXT:   successors: %bb.1(0x80000000)
  ; GFX90A-NEXT:   liveins: $vgpr0_vgpr1, $vgpr2_vgpr3, $vgpr4_vgpr5
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT:   [[COPY:%[0-9]+]]:vreg_64_align2 = COPY $vgpr0_vgpr1
  ; GFX90A-NEXT:   [[COPY1:%[0-9]+]]:vreg_64_align2 = COPY $vgpr2_vgpr3
  ; GFX90A-NEXT:   [[COPY2:%[0-9]+]]:vreg_64_align2 = COPY $vgpr4_vgpr5
  ; GFX90A-NEXT:   [[V_FMAC_F64_e64_:%[0-9]+]]:vreg_64_align2 = nofpexcept V_FMAC_F64_e64 0, [[COPY]], 0, [[COPY1]], 0, [[COPY2]], 0, 0, implicit $mode, implicit $exec
  ; GFX90A-NEXT:   S_BRANCH %bb.1
  ; GFX90A-NEXT: {{  $}}
  ; GFX90A-NEXT: bb.1:
  ; GFX90A-NEXT:   [[V_ADD_F64_e64_:%[0-9]+]]:vreg_64_align2 = nofpexcept V_ADD_F64_e64 0, [[COPY2]], 0, [[COPY1]], 0, 0, implicit $mode, implicit $exec
  ; GFX90A-NEXT:   $vgpr0_vgpr1 = COPY [[V_ADD_F64_e64_]]
  ; GFX90A-NEXT:   S_ENDPGM 0, implicit $vgpr0_vgpr1
  ;
  ; GFX900-LABEL: name: fmac_accumulator_live_across_bb
  ; GFX900: bb.0:
  ; GFX900-NEXT:   successors: %bb.1(0x80000000)
  ; GFX900-NEXT:   liveins: $vgpr0_vgpr1, $vgpr2_vgpr3, $vgpr4_vgpr5
  ; GFX900-NEXT: {{  $}}
  ; GFX900-NEXT:   [[COPY:%[0-9]+]]:vreg_64_align2 = COPY $vgpr0_vgpr1
  ; GFX900-NEXT:   [[COPY1:%[0-9]+]]:vreg_64_align2 = COPY $vgpr2_vgpr3
  ; GFX900-NEXT:   [[COPY2:%[0-9]+]]:vreg_64_align2 = COPY $vgpr4_vgpr5
  ; GFX900-NEXT:   [[V_FMAC_F64_e64_:%[0-9]+]]:vreg_64_align2 = nofpexcept V_FMAC_F64_e64 0, [[COPY]], 0, [[COPY1]], 0, [[COPY2]], 0, 0, implicit $mode, implicit $exec
  ; GFX900-NEXT:   S_BRANCH %bb.1
  ; GFX900-NEXT: {{  $}}
  ; GFX900-NEXT: bb.1:
  ; GFX900-NEXT:   [[V_ADD_F64_e64_:%[0-9]+]]:vreg_64_align2 = nofpexcept V_ADD_F64_e64 0, [[COPY2]], 0, [[COPY1]], 0, 0, implicit $mode, implicit $exec
  ; GFX900-NEXT:   $vgpr0_vgpr1 = COPY [[V_ADD_F64_e64_]]
  ; GFX900-NEXT:   S_ENDPGM 0, implicit $vgpr0_vgpr1
  bb.0:
    liveins: $vgpr0_vgpr1, $vgpr2_vgpr3, $vgpr4_vgpr5
    successors: %bb.1
    %0:vreg_64_align2 = COPY $vgpr0_vgpr1
    %1:vreg_64_align2 = COPY $vgpr2_vgpr3
    %2:vreg_64_align2 = COPY $vgpr4_vgpr5
    %3:vreg_64_align2 = nofpexcept V_FMAC_F64_e64 0, %0, 0, %1, 0, %2, 0, 0, implicit $mode, implicit $exec
    S_BRANCH %bb.1

  bb.1:
    %4:vreg_64_align2 = nofpexcept V_ADD_F64_e64 0, %2, 0, %1, 0, 0, implicit $mode, implicit $exec
    $vgpr0_vgpr1 = COPY %4
    S_ENDPGM 0, implicit $vgpr0_vgpr1
...

# Accumulator reg is killed - should convert to FMA
---
name: fmac_accumulator_dead_can_convert
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $vgpr0_vgpr1, $vgpr2_vgpr3, $vgpr4_vgpr5
    ; GFX90A-LABEL: name: fmac_accumulator_dead_can_convert
    ; GFX90A: liveins: $vgpr0_vgpr1, $vgpr2_vgpr3, $vgpr4_vgpr5
    ; GFX90A-NEXT: {{  $}}
    ; GFX90A-NEXT: [[COPY:%[0-9]+]]:vreg_64_align2 = COPY $vgpr0_vgpr1
    ; GFX90A-NEXT: [[COPY1:%[0-9]+]]:vreg_64_align2 = COPY $vgpr2_vgpr3
    ; GFX90A-NEXT: [[COPY2:%[0-9]+]]:vreg_64_align2 = COPY $vgpr4_vgpr5
    ; GFX90A-NEXT: [[V_FMA_F64_e64_:%[0-9]+]]:vreg_64_align2 = nofpexcept V_FMA_F64_e64 0, killed [[COPY]], 0, killed [[COPY1]], 0, killed [[COPY2]], 0, 0, implicit $mode, implicit $exec
    ; GFX90A-NEXT: $vgpr0_vgpr1 = COPY [[V_FMA_F64_e64_]]
    ; GFX90A-NEXT: S_ENDPGM 0
    ;
    ; GFX900-LABEL: name: fmac_accumulator_dead_can_convert
    ; GFX900: liveins: $vgpr0_vgpr1, $vgpr2_vgpr3, $vgpr4_vgpr5
    ; GFX900-NEXT: {{  $}}
    ; GFX900-NEXT: [[COPY:%[0-9]+]]:vreg_64_align2 = COPY $vgpr0_vgpr1
    ; GFX900-NEXT: [[COPY1:%[0-9]+]]:vreg_64_align2 = COPY $vgpr2_vgpr3
    ; GFX900-NEXT: [[COPY2:%[0-9]+]]:vreg_64_align2 = COPY $vgpr4_vgpr5
    ; GFX900-NEXT: [[V_FMAC_F64_e64_:%[0-9]+]]:vreg_64_align2 = nofpexcept V_FMAC_F64_e64 0, killed [[COPY]], 0, killed [[COPY1]], 0, killed [[COPY2]], 0, 0, implicit $mode, implicit $exec
    ; GFX900-NEXT: $vgpr0_vgpr1 = COPY [[V_FMAC_F64_e64_]]
    ; GFX900-NEXT: S_ENDPGM 0
    %0:vreg_64_align2 = COPY $vgpr0_vgpr1
    %1:vreg_64_align2 = COPY $vgpr2_vgpr3
    %2:vreg_64_align2 = COPY $vgpr4_vgpr5
    %3:vreg_64_align2 = nofpexcept V_FMAC_F64_e64 0, killed %0, 0, killed %1, 0, killed %2, 0, 0, implicit $mode, implicit $exec
    $vgpr0_vgpr1 = COPY %3
    S_ENDPGM 0
...

# V_MAC variant: accumulator is dead - should convert to V_MAD
---
name: mac_f32_dead_accumulator
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $vgpr0, $vgpr1, $vgpr2
    ; GFX90A-LABEL: name: mac_f32_dead_accumulator
    ; GFX90A: liveins: $vgpr0, $vgpr1, $vgpr2
    ; GFX90A-NEXT: {{  $}}
    ; GFX90A-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX90A-NEXT: [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
    ; GFX90A-NEXT: [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr2
    ; GFX90A-NEXT: [[V_MAD_F32_e64_:%[0-9]+]]:vgpr_32 = V_MAD_F32_e64 0, killed [[COPY]], 0, killed [[COPY1]], 0, killed [[COPY2]], 0, 0, implicit $mode, implicit $exec
    ; GFX90A-NEXT: $vgpr0 = COPY [[V_MAD_F32_e64_]]
    ; GFX90A-NEXT: S_ENDPGM 0
    ;
    ; GFX900-LABEL: name: mac_f32_dead_accumulator
    ; GFX900: liveins: $vgpr0, $vgpr1, $vgpr2
    ; GFX900-NEXT: {{  $}}
    ; GFX900-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX900-NEXT: [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
    ; GFX900-NEXT: [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr2
    ; GFX900-NEXT: [[V_MAC_F32_e64_:%[0-9]+]]:vgpr_32 = V_MAC_F32_e64 0, killed [[COPY]], 0, killed [[COPY1]], 0, killed [[COPY2]], 0, 0, implicit $mode, implicit $exec
    ; GFX900-NEXT: $vgpr0 = COPY [[V_MAC_F32_e64_]]
    ; GFX900-NEXT: S_ENDPGM 0
    %0:vgpr_32 = COPY $vgpr0
    %1:vgpr_32 = COPY $vgpr1
    %2:vgpr_32 = COPY $vgpr2
    %3:vgpr_32 = V_MAC_F32_e64 0, killed %0, 0, killed %1, 0, killed %2, 0, 0, implicit $mode, implicit $exec
    $vgpr0 = COPY %3
    S_ENDPGM 0
...

# V_MAC_F16 variant: accumulator is unused - should convert to V_MAD_F16
---
name: mac_f16_dead_accumulator
tracksRegLiveness: true
body: |
  bb.0:
    liveins: $vgpr0, $vgpr1, $vgpr2
    ; GFX90A-LABEL: name: mac_f16_dead_accumulator
    ; GFX90A: liveins: $vgpr0, $vgpr1, $vgpr2
    ; GFX90A-NEXT: {{  $}}
    ; GFX90A-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX90A-NEXT: [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
    ; GFX90A-NEXT: [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr2
    ; GFX90A-NEXT: [[V_MAD_F16_e64_:%[0-9]+]]:vgpr_32 = V_MAD_F16_e64 0, killed [[COPY]], 0, killed [[COPY1]], 0, [[COPY2]], 0, 0, implicit $mode, implicit $exec
    ; GFX90A-NEXT: $vgpr0 = COPY [[V_MAD_F16_e64_]]
    ; GFX90A-NEXT: S_ENDPGM 0
    ;
    ; GFX900-LABEL: name: mac_f16_dead_accumulator
    ; GFX900: liveins: $vgpr0, $vgpr1, $vgpr2
    ; GFX900-NEXT: {{  $}}
    ; GFX900-NEXT: [[COPY:%[0-9]+]]:vgpr_32 = COPY $vgpr0
    ; GFX900-NEXT: [[COPY1:%[0-9]+]]:vgpr_32 = COPY $vgpr1
    ; GFX900-NEXT: [[COPY2:%[0-9]+]]:vgpr_32 = COPY $vgpr2
    ; GFX900-NEXT: [[V_MAC_F16_e64_:%[0-9]+]]:vgpr_32 = V_MAC_F16_e64 0, killed [[COPY]], 0, killed [[COPY1]], 0, [[COPY2]], 0, 0, implicit $mode, implicit $exec
    ; GFX900-NEXT: $vgpr0 = COPY [[V_MAC_F16_e64_]]
    ; GFX900-NEXT: S_ENDPGM 0
    %0:vgpr_32 = COPY $vgpr0
    %1:vgpr_32 = COPY $vgpr1
    %2:vgpr_32 = COPY $vgpr2
    %3:vgpr_32 = V_MAC_F16_e64 0, killed %0, 0, killed %1, 0, %2, 0, 0, implicit $mode, implicit $exec
    $vgpr0 = COPY %3
    S_ENDPGM 0
...
