# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 5
# RUN: llc -mtriple=amdgcn -mcpu=gfx90a -run-pass=si-fold-operands -verify-machineinstrs -o - %s 2>&1 | FileCheck %s

---

name: s_mov_b32_imm_literal_copy_s_to_av_32
tracksRegLiveness: true
body:             |
  bb.0:
    ; CHECK-LABEL: name: s_mov_b32_imm_literal_copy_s_to_av_32
    ; CHECK: [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 999
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:av_32 = COPY [[S_MOV_B32_]]
    ; CHECK-NEXT: $agpr0 = COPY [[COPY]]
    ; CHECK-NEXT: S_ENDPGM 0
    %0:sreg_32 = S_MOV_B32 999
    %1:av_32 = COPY %0
    $agpr0 = COPY %1
    S_ENDPGM 0
...

---

name: v_mov_b32_imm_literal_copy_v_to_av_32
tracksRegLiveness: true
body:             |
  bb.0:
    ; CHECK-LABEL: name: v_mov_b32_imm_literal_copy_v_to_av_32
    ; CHECK: [[V_MOV_B32_e32_:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 999, implicit $exec
    ; CHECK-NEXT: [[COPY:%[0-9]+]]:av_32 = COPY [[V_MOV_B32_e32_]]
    ; CHECK-NEXT: $agpr0 = COPY [[COPY]]
    ; CHECK-NEXT: S_ENDPGM 0
    %0:vgpr_32 = V_MOV_B32_e32 999, implicit $exec
    %1:av_32 = COPY %0
    $agpr0 = COPY %1
    S_ENDPGM 0
...
