# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 6
# RUN: llc -mtriple=amdgcn -mcpu=gfx90a -run-pass=si-i1-copies -o - %s | FileCheck -check-prefixes=GCN %s

---
name:              phi_with_dependencies1
# SCC def instruction (S_CMP_LG_U32) is below PHI dependancy ($17)
tracksRegLiveness: true
body:             |
  ; GCN-LABEL: name: phi_with_dependencies1
  ; GCN: bb.0:
  ; GCN-NEXT:   successors: %bb.1(0x80000000)
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 1
  ; GCN-NEXT:   [[DEF:%[0-9]+]]:sreg_64 = IMPLICIT_DEF
  ; GCN-NEXT:   S_BRANCH %bb.1
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.1:
  ; GCN-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT:   [[PHI:%[0-9]+]]:sreg_64 = PHI [[DEF]], %bb.0, %5, %bb.1
  ; GCN-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 2
  ; GCN-NEXT:   [[V_MOV_B32_e32_:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
  ; GCN-NEXT:   [[V_CMP_EQ_U32_e64_:%[0-9]+]]:sreg_64 = V_CMP_EQ_U32_e64 killed [[V_MOV_B32_e32_]], 1, implicit $exec
  ; GCN-NEXT:   [[S_ANDN2_B64_:%[0-9]+]]:sreg_64 = S_ANDN2_B64 [[PHI]], $exec, implicit-def $scc
  ; GCN-NEXT:   [[S_AND_B64_:%[0-9]+]]:sreg_64 = S_AND_B64 [[V_CMP_EQ_U32_e64_]], $exec, implicit-def $scc
  ; GCN-NEXT:   [[S_OR_B64_:%[0-9]+]]:sreg_64 = S_OR_B64 [[S_ANDN2_B64_]], [[S_AND_B64_]], implicit-def $scc
  ; GCN-NEXT:   S_CMP_LG_U32 [[S_MOV_B32_]], killed [[S_MOV_B32_1]], implicit-def $scc
  ; GCN-NEXT:   S_CBRANCH_SCC1 %bb.1, implicit $scc
  ; GCN-NEXT:   S_BRANCH %bb.2
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.2:
  ; GCN-NEXT:   [[COPY:%[0-9]+]]:sreg_64_xexec = COPY [[S_OR_B64_]]
  ; GCN-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1(0x80000000)
    %0:sreg_32 = S_MOV_B32 1
    S_BRANCH %bb.1

  bb.1:
    successors: %bb.2, %bb.1
    %13:sreg_32 = S_MOV_B32 2
    %16:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
    %17:sreg_64 = V_CMP_EQ_U32_e64 killed %16:vgpr_32, 1, implicit $exec
    %1:vreg_1 = COPY %17:sreg_64
    S_CMP_LG_U32 %0:sreg_32, killed %13:sreg_32, implicit-def $scc
    S_CBRANCH_SCC1 %bb.1, implicit $scc
    S_BRANCH %bb.2

  bb.2:
  ; predecessors: %bb.1
    %2:vreg_1 = PHI %1:vreg_1, %bb.1
    %19:sreg_64_xexec = COPY %2:vreg_1
    S_ENDPGM 0
...

---
name:              phi_with_dependencies2
# SCC def instruction (S_CMP_LG_U32) is above PHI dependancy ($17) definition and set SCC instruction can be moved below
tracksRegLiveness: true
body:             |
  ; GCN-LABEL: name: phi_with_dependencies2
  ; GCN: bb.0:
  ; GCN-NEXT:   successors: %bb.1(0x80000000)
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 1
  ; GCN-NEXT:   [[DEF:%[0-9]+]]:sreg_64 = IMPLICIT_DEF
  ; GCN-NEXT:   S_BRANCH %bb.1
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.1:
  ; GCN-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT:   [[PHI:%[0-9]+]]:sreg_64 = PHI [[DEF]], %bb.0, %5, %bb.1
  ; GCN-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 2
  ; GCN-NEXT:   [[V_MOV_B32_e32_:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
  ; GCN-NEXT:   [[V_CMP_EQ_U32_e64_:%[0-9]+]]:sreg_64 = V_CMP_EQ_U32_e64 killed [[V_MOV_B32_e32_]], 1, implicit $exec
  ; GCN-NEXT:   [[S_ANDN2_B64_:%[0-9]+]]:sreg_64 = S_ANDN2_B64 [[PHI]], $exec, implicit-def $scc
  ; GCN-NEXT:   [[S_AND_B64_:%[0-9]+]]:sreg_64 = S_AND_B64 [[V_CMP_EQ_U32_e64_]], $exec, implicit-def $scc
  ; GCN-NEXT:   [[S_OR_B64_:%[0-9]+]]:sreg_64 = S_OR_B64 [[S_ANDN2_B64_]], [[S_AND_B64_]], implicit-def $scc
  ; GCN-NEXT:   S_CMP_LG_U32 [[S_MOV_B32_]], killed [[S_MOV_B32_1]], implicit-def $scc
  ; GCN-NEXT:   S_CBRANCH_SCC1 %bb.1, implicit $scc
  ; GCN-NEXT:   S_BRANCH %bb.2
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.2:
  ; GCN-NEXT:   [[COPY:%[0-9]+]]:sreg_64_xexec = COPY [[S_OR_B64_]]
  ; GCN-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1(0x80000000); %bb.1(100.00%)
    %0:sreg_32 = S_MOV_B32 1
    S_BRANCH %bb.1

  bb.1:
  ; predecessors: %bb.0, %bb.1
    successors: %bb.2, %bb.1

    %13:sreg_32 = S_MOV_B32 2
    S_CMP_LG_U32 %0:sreg_32, killed %13:sreg_32, implicit-def $scc
    %16:vgpr_32 = V_MOV_B32_e32 0, implicit $exec
    %17:sreg_64 = V_CMP_EQ_U32_e64 killed %16:vgpr_32, 1, implicit $exec
    %1:vreg_1 = COPY %17:sreg_64
    S_CBRANCH_SCC1 %bb.1, implicit $scc
    S_BRANCH %bb.2

  bb.2:
  ; predecessors: %bb.1
    %2:vreg_1 = PHI %1:vreg_1, %bb.1
    %19:sreg_64_xexec = COPY %2:vreg_1
    S_ENDPGM 0
...

---
name:              phi_with_dependencies3
# SCC def instruction (V_MOV_B32_e32) is above PHI dependancy ($17) definition and cannot be move below
tracksRegLiveness: true
body:             |
  ; GCN-LABEL: name: phi_with_dependencies3
  ; GCN: bb.0:
  ; GCN-NEXT:   successors: %bb.1(0x80000000)
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT:   [[S_MOV_B32_:%[0-9]+]]:sreg_32 = S_MOV_B32 1
  ; GCN-NEXT:   [[DEF:%[0-9]+]]:sreg_64 = IMPLICIT_DEF
  ; GCN-NEXT:   S_BRANCH %bb.1
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.1:
  ; GCN-NEXT:   successors: %bb.2(0x40000000), %bb.1(0x40000000)
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT:   [[PHI:%[0-9]+]]:sreg_64 = PHI [[DEF]], %bb.0, %5, %bb.1
  ; GCN-NEXT:   [[S_MOV_B32_1:%[0-9]+]]:sreg_32 = S_MOV_B32 2
  ; GCN-NEXT:   S_CMP_LG_U32 [[S_MOV_B32_]], killed [[S_MOV_B32_1]], implicit-def $scc
  ; GCN-NEXT:   [[V_MOV_B32_e32_:%[0-9]+]]:vgpr_32 = V_MOV_B32_e32 0, implicit $exec, implicit-def $scc
  ; GCN-NEXT:   [[V_CMP_EQ_U32_e64_:%[0-9]+]]:sreg_64 = V_CMP_EQ_U32_e64 killed [[V_MOV_B32_e32_]], 1, implicit $exec
  ; GCN-NEXT:   [[S_CSELECT_B32_:%[0-9]+]]:sreg_32 = S_CSELECT_B32 1, 0, implicit $scc
  ; GCN-NEXT:   [[S_ANDN2_B64_:%[0-9]+]]:sreg_64 = S_ANDN2_B64 [[PHI]], $exec, implicit-def $scc
  ; GCN-NEXT:   [[S_AND_B64_:%[0-9]+]]:sreg_64 = S_AND_B64 [[V_CMP_EQ_U32_e64_]], $exec, implicit-def $scc
  ; GCN-NEXT:   [[S_OR_B64_:%[0-9]+]]:sreg_64 = S_OR_B64 [[S_ANDN2_B64_]], [[S_AND_B64_]], implicit-def $scc
  ; GCN-NEXT:   S_CMP_LG_U32 [[S_CSELECT_B32_]], 0, implicit-def $scc, implicit-def $scc
  ; GCN-NEXT:   S_CBRANCH_SCC1 %bb.1, implicit $scc
  ; GCN-NEXT:   S_BRANCH %bb.2
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.2:
  ; GCN-NEXT:   [[COPY:%[0-9]+]]:sreg_64_xexec = COPY [[S_OR_B64_]]
  ; GCN-NEXT:   S_ENDPGM 0
  bb.0:
    successors: %bb.1(0x80000000); %bb.1(100.00%)
    %0:sreg_32 = S_MOV_B32 1
    S_BRANCH %bb.1

  bb.1:
  ; predecessors: %bb.0, %bb.1
    successors: %bb.2(0x40000000), %bb.1(0x40000000); %bb.2(50.00%), %bb.1(50.00%)

    %1:sreg_32 = S_MOV_B32 2
    S_CMP_LG_U32 %0:sreg_32, killed %1:sreg_32, implicit-def $scc
    %2:vgpr_32 = V_MOV_B32_e32 0, implicit $exec, implicit-def $scc
    %4:sreg_64 = V_CMP_EQ_U32_e64 killed %2:vgpr_32, 1, implicit $exec
    %5:vreg_1 = COPY %4:sreg_64
    S_CBRANCH_SCC1 %bb.1, implicit $scc
    S_BRANCH %bb.2

  bb.2:
  ; predecessors: %bb.1
    %6:vreg_1 = PHI %5:vreg_1, %bb.1
    %7:sreg_64_xexec = COPY %6:vreg_1
    S_ENDPGM 0

...
