; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -global-isel=0 -march=amdgcn -mcpu=gfx1300 -O3 -verify-machineinstrs < %s | FileCheck -check-prefixes=CHECK %s

@dst = external local_unnamed_addr addrspace(10) global <8 x float>, align 32
@sem = internal addrspace(3) global target("amdgcn.semaphore", 1) poison
@sem2 = internal addrspace(3) global target("amdgcn.semaphore", 1) poison

define amdgpu_kernel void @set_and_is_chain() "amdgpu-cluster-dims"="4,1,1" "amdgpu-wavegroup-enable" "amdgpu-spatial-cluster" !reqd_work_group_size !{i32 32, i32 8, i32 1} {
; CHECK-LABEL: set_and_is_chain:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_getreg_b32 s0, hwreg(HW_REG_WAVE_GROUP_INFO, 16, 4)
; CHECK-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; CHECK-NEXT:    s_mul_i32 s1, s0, 0
; CHECK-NEXT:    s_mul_i32 s33, s0, s8
; CHECK-NEXT:    s_set_gpr_idx_u32 idx0, s1
; CHECK-NEXT:    ; sched_barrier mask(0x00000000)
; CHECK-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_MODE, 12, 1), -1
; CHECK-NEXT:    s_getreg_b32 s0, hwreg(HW_REG_MODE, 12, 1)
; CHECK-NEXT:    s_setreg_imm32_b32 hwreg(HW_REG_MODE, 12, 1), -1
; CHECK-NEXT:    s_getreg_b32 s1, hwreg(HW_REG_MODE, 13, 1)
; CHECK-NEXT:    s_setreg_b32 hwreg(HW_REG_MODE, 12, 1), s0
; CHECK-NEXT:    s_setreg_b32 hwreg(HW_REG_MODE, 13, 1), s1
; CHECK-NEXT:    s_endpgm
entry:
  call void @llvm.amdgcn.spatial.cluster.set.chain.start(i1 true)
  %i1 = call i1 @llvm.amdgcn.spatial.cluster.is.chain.start()
  call void @llvm.amdgcn.spatial.cluster.set.chain.start(i1 true)
  %i2 = call i1 @llvm.amdgcn.spatial.cluster.is.chain.end()
  call void @llvm.amdgcn.spatial.cluster.set.chain.start(i1 %i1)
  call void @llvm.amdgcn.spatial.cluster.set.chain.end(i1 %i2)
  ret void
}

define amdgpu_kernel void @signal_next_prev() "amdgpu-cluster-dims"="4,1,1" "amdgpu-wavegroup-enable" "amdgpu-spatial-cluster" !reqd_work_group_size !{i32 32, i32 8, i32 1} {
; CHECK-LABEL: signal_next_prev:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_getreg_b32 s0, hwreg(HW_REG_WAVE_GROUP_INFO, 16, 4)
; CHECK-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; CHECK-NEXT:    s_mul_i32 s1, s0, 0
; CHECK-NEXT:    s_mul_i32 s33, s0, s8
; CHECK-NEXT:    s_set_gpr_idx_u32 idx0, s1
; CHECK-NEXT:    ; sched_barrier mask(0x00000000)
; CHECK-NEXT:    v_send_vgpr_next_b32 off, off, off sema_id:1 sema_wave_id:1 sema_id_refl:2 sema_wave_id_refl:1 wait_va_vdst:0
; CHECK-NEXT:    v_send_vgpr_prev_b32 off, off, off sema_id:1 sema_wave_id:1 sema_id_refl:2 sema_wave_id_refl:1 wait_va_vdst:0
; CHECK-NEXT:    s_endpgm
entry:
  call void @llvm.amdgcn.spatial.cluster.signal.next(ptr addrspace(3) @sem, ptr addrspace(3) @sem2)
  call void @llvm.amdgcn.spatial.cluster.signal.prev(ptr addrspace(3) @sem, ptr addrspace(3) @sem2)
  ret void
}


define amdgpu_kernel void @send_next_prev(i32 %i1, ptr addrspace(1) %p) "amdgpu-cluster-dims"="4,1,1" "amdgpu-wavegroup-enable" "amdgpu-spatial-cluster" !reqd_work_group_size !{i32 32, i32 8, i32 1} {
; CHECK-LABEL: send_next_prev:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_getreg_b32 s0, hwreg(HW_REG_WAVE_GROUP_INFO, 16, 4)
; CHECK-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(SKIP_2) | instid1(SALU_CYCLE_1)
; CHECK-NEXT:    s_mul_i32 s1, s0, 2
; CHECK-NEXT:    s_mul_i32 s33, s0, s8
; CHECK-NEXT:    s_add_co_u32 s1, s1, 8
; CHECK-NEXT:    s_set_gpr_idx_u32 idx0, s1
; CHECK-NEXT:    ; sched_barrier mask(0x00000000)
; CHECK-NEXT:    s_clause 0x1
; CHECK-NEXT:    s_load_b32 s2, s[4:5], 0x24
; CHECK-NEXT:    s_load_b64 s[0:1], s[4:5], 0x2c
; CHECK-NEXT:    s_getreg_b32 s3, hwreg(HW_REG_WAVE_GROUP_INFO, 4, 4)
; CHECK-NEXT:    s_bfe_u32 s4, ttmp8, 0x20019
; CHECK-NEXT:    s_lshl_b32 s3, s3, 2
; CHECK-NEXT:    s_set_gpr_idx_u32 idx1, 0
; CHECK-NEXT:    s_wait_kmcnt 0x0
; CHECK-NEXT:    v_mov_b32_e32 v0, s2
; CHECK-NEXT:    s_or_b32 s2, s3, s4
; CHECK-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; CHECK-NEXT:    v_mov_b32_e32 v1, s2
; CHECK-NEXT:    s_set_vgpr_frames 0x44 ; vsrc0_idx=0 vsrc1_idx=1 vsrc2_idx=0 vdst_idx=1 vsrc0_msb=0 vsrc1_msb=0 vsrc2_msb=0 vdst_msb=0
; CHECK-NEXT:    v_send_vgpr_next_b32 g1[0], g1[1], v0 sema_id:1 sema_wave_id:1 sema_id_refl:2 sema_wave_id_refl:1 wait_va_vdst:0
; CHECK-NEXT:    v_send_vgpr_prev_b32 g1[0], g1[1], v0 sema_id:1 sema_wave_id:1 sema_id_refl:2 sema_wave_id_refl:1 wait_va_vdst:0
; CHECK-NEXT:    global_store_b32 v1, g1[0], s[0:1] scale_offset
; CHECK-NEXT:    s_endpgm
entry:
  %wg_cluster = call i32 @llvm.amdgcn.wavegroup.id.in.cluster()
  %p0 = getelementptr i32, ptr addrspace(1) %p, i32 %wg_cluster
  %pdst = getelementptr i32, ptr addrspace(10) @dst, i32 0
  %prefl = getelementptr i32, ptr addrspace(10) @dst, i32 1
  call void @llvm.amdgcn.spatial.cluster.send.next(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(3) @sem,
                                                  ptr addrspace(10) %prefl, ptr addrspace(3) @sem2, i32 0);
  call void @llvm.amdgcn.spatial.cluster.send.prev(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(3) @sem,
                                                  ptr addrspace(10) %prefl, ptr addrspace(3) @sem2, i32 0);
  %val = load i32, ptr addrspace(10) %pdst, align 4
  store i32 %val, ptr addrspace(1) %p0
  ret void
}

define amdgpu_kernel void @send_next_prev_nowrite(i32 %i1, ptr addrspace(1) %p) "amdgpu-cluster-dims"="4,1,1" "amdgpu-wavegroup-enable" "amdgpu-spatial-cluster" !reqd_work_group_size !{i32 32, i32 8, i32 1} {
; CHECK-LABEL: send_next_prev_nowrite:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_getreg_b32 s0, hwreg(HW_REG_WAVE_GROUP_INFO, 16, 4)
; CHECK-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(SKIP_2) | instid1(SALU_CYCLE_1)
; CHECK-NEXT:    s_mul_i32 s1, s0, 2
; CHECK-NEXT:    s_mul_i32 s33, s0, s8
; CHECK-NEXT:    s_add_co_u32 s1, s1, 8
; CHECK-NEXT:    s_set_gpr_idx_u32 idx0, s1
; CHECK-NEXT:    ; sched_barrier mask(0x00000000)
; CHECK-NEXT:    s_clause 0x1
; CHECK-NEXT:    s_load_b32 s2, s[4:5], 0x24
; CHECK-NEXT:    s_load_b64 s[0:1], s[4:5], 0x2c
; CHECK-NEXT:    s_getreg_b32 s3, hwreg(HW_REG_WAVE_GROUP_INFO, 4, 4)
; CHECK-NEXT:    s_bfe_u32 s4, ttmp8, 0x20019
; CHECK-NEXT:    s_lshl_b32 s3, s3, 2
; CHECK-NEXT:    s_set_gpr_idx_u32 idx1, 0
; CHECK-NEXT:    s_wait_kmcnt 0x0
; CHECK-NEXT:    v_mov_b32_e32 v0, s2
; CHECK-NEXT:    s_or_b32 s2, s3, s4
; CHECK-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; CHECK-NEXT:    v_mov_b32_e32 v1, s2
; CHECK-NEXT:    s_set_vgpr_frames 0x44 ; vsrc0_idx=0 vsrc1_idx=1 vsrc2_idx=0 vdst_idx=1 vsrc0_msb=0 vsrc1_msb=0 vsrc2_msb=0 vdst_msb=0
; CHECK-NEXT:    v_send_vgpr_next_b32 g1[0], g1[1], v0 sema_wave_id:0 sema_wave_id_refl:0 wait_va_vdst:0
; CHECK-NEXT:    v_send_vgpr_prev_b32 g1[0], g1[1], v0 sema_wave_id:0 sema_wave_id_refl:0 wait_va_vdst:0
; CHECK-NEXT:    global_store_b32 v1, g1[0], s[0:1] scale_offset
; CHECK-NEXT:    s_endpgm
entry:
  %wg_cluster = call i32 @llvm.amdgcn.wavegroup.id.in.cluster()
  %p0 = getelementptr i32, ptr addrspace(1) %p, i32 %wg_cluster
  %pdst = getelementptr i32, ptr addrspace(10) @dst, i32 0
  %prefl = getelementptr i32, ptr addrspace(10) @dst, i32 1
  call void @llvm.amdgcn.spatial.cluster.send.next(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)),
                                                  ptr addrspace(10) %prefl, ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)), i32 0);
  call void @llvm.amdgcn.spatial.cluster.send.prev(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)),
                                                  ptr addrspace(10) %prefl, ptr addrspace(3) addrspacecast (ptr null to ptr addrspace(3)), i32 0);
  %val = load i32, ptr addrspace(10) %pdst, align 4
  store i32 %val, ptr addrspace(1) %p0
  ret void
}

define void @send_next_prev_non_kernel(i32 %i1, ptr addrspace(1) %p) {
; CHECK-LABEL: send_next_prev_non_kernel:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_wait_loadcnt_dscnt 0x0
; CHECK-NEXT:    s_wait_expcnt 0x0
; CHECK-NEXT:    s_wait_samplecnt 0x0
; CHECK-NEXT:    s_wait_rtscnt 0x0
; CHECK-NEXT:    s_wait_kmcnt 0x0
; CHECK-NEXT:    s_getreg_b32 s0, hwreg(HW_REG_WAVE_GROUP_INFO, 4, 4)
; CHECK-NEXT:    s_bfe_u32 s1, ttmp8, 0x20019
; CHECK-NEXT:    s_lshl_b32 s0, s0, 2
; CHECK-NEXT:    s_set_gpr_idx_u32 idx1, 0
; CHECK-NEXT:    s_or_b32 s0, s0, s1
; CHECK-NEXT:    s_set_vgpr_frames 0x44 ; vsrc0_idx=0 vsrc1_idx=1 vsrc2_idx=0 vdst_idx=1 vsrc0_msb=0 vsrc1_msb=0 vsrc2_msb=0 vdst_msb=0
; CHECK-NEXT:    v_send_vgpr_next_b32 g1[0], g1[1], v0 sema_id:1 sema_wave_id:1 sema_id_refl:2 sema_wave_id_refl:1 wait_va_vdst:0
; CHECK-NEXT:    s_ashr_i32 s1, s0, 31
; CHECK-NEXT:    v_send_vgpr_prev_b32 g1[0], g1[1], v0 sema_id:1 sema_wave_id:1 sema_id_refl:2 sema_wave_id_refl:1 wait_va_vdst:0
; CHECK-NEXT:    s_lshl_b64 s[0:1], s[0:1], 2
; CHECK-NEXT:    s_set_vgpr_frames 0 ; vsrc0_idx=0 vsrc1_idx=0 vsrc2_idx=0 vdst_idx=0 vsrc0_msb=0 vsrc1_msb=0 vsrc2_msb=0 vdst_msb=0
; CHECK-NEXT:    v_add_co_u32 v1, vcc_lo, v1, s0
; CHECK-NEXT:    s_delay_alu instid0(VALU_DEP_1)
; CHECK-NEXT:    v_add_co_ci_u32_e64 v2, null, s1, v2, vcc_lo
; CHECK-NEXT:    s_set_vgpr_frames 4 ; vsrc0_idx=0 vsrc1_idx=1 vsrc2_idx=0 vdst_idx=0 vsrc0_msb=0 vsrc1_msb=0 vsrc2_msb=0 vdst_msb=0
; CHECK-NEXT:    global_store_b32 v[1:2], g1[0], off
; CHECK-NEXT:    s_set_vgpr_frames 0 ; vsrc0_idx=0 vsrc1_idx=0 vsrc2_idx=0 vdst_idx=0 vsrc0_msb=0 vsrc1_msb=0 vsrc2_msb=0 vdst_msb=0
; CHECK-NEXT:    s_set_pc_i64 s[30:31]
entry:
  %wg_cluster = call i32 @llvm.amdgcn.wavegroup.id.in.cluster()
  %p0 = getelementptr i32, ptr addrspace(1) %p, i32 %wg_cluster
  %pdst = getelementptr i32, ptr addrspace(10) @dst, i32 0
  %prefl = getelementptr i32, ptr addrspace(10) @dst, i32 1
  call void @llvm.amdgcn.spatial.cluster.send.next(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(3) @sem,
                                                  ptr addrspace(10) %prefl, ptr addrspace(3) @sem2, i32 0);
  call void @llvm.amdgcn.spatial.cluster.send.prev(i32 %i1, ptr addrspace(10) %pdst, ptr addrspace(3) @sem,
                                                  ptr addrspace(10) %prefl, ptr addrspace(3) @sem2, i32 0);
  %val = load i32, ptr addrspace(10) %pdst, align 4
  store i32 %val, ptr addrspace(1) %p0
  ret void
}
