# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx908 -run-pass=prologepilog -verify-machineinstrs -o - %s | FileCheck -check-prefix=GCN %s

# There are free scratch SGPRs available and hence use the smallest available pair for exec copy
# instead of the pair in the CSR range already given.

---
name:            shift_back_exec_copy_reserved_reg
tracksRegLiveness: true
frameInfo:
  maxAlignment:    4
machineFunctionInfo:
  isEntryFunction: false
  scratchRSrcReg:  '$sgpr0_sgpr1_sgpr2_sgpr3'
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
  sgprForEXECCopy: '$sgpr34_sgpr35'
body:             |
  bb.0:
    liveins: $sgpr30_sgpr31, $vgpr0
    ; GCN-LABEL: name: shift_back_exec_copy_reserved_reg
    ; GCN: liveins: $sgpr30_sgpr31, $vgpr0
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: frame-setup CFI_INSTRUCTION llvm_def_aspace_cfa $sgpr32_lo16, 0, 6
    ; GCN-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30_lo16, 32, $sgpr31_lo16, 32
    ; GCN-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr0_lo16
    ; GCN-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr1_lo16
    ; GCN-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr4_lo16
    ; GCN-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr5_lo16
    ; GCN-NEXT: $vgpr0 = SI_SPILL_S32_TO_VGPR $sgpr30, 0, killed $vgpr0
    ; GCN-NEXT: $vgpr0 = SI_SPILL_S32_TO_VGPR $sgpr31, 1, killed $vgpr0
    ; GCN-NEXT: $sgpr4_sgpr5 = S_OR_SAVEEXEC_B64 -1, implicit-def $exec, implicit-def dead $scc, implicit $exec
    ; GCN-NEXT: $vgpr1 = COPY $vgpr0
    ; GCN-NEXT: $exec = S_MOV_B64 killed $sgpr4_sgpr5
    ; GCN-NEXT: $sgpr30 = SI_RESTORE_S32_FROM_VGPR $vgpr1, 0
    ; GCN-NEXT: $sgpr31 = SI_RESTORE_S32_FROM_VGPR $vgpr1, 1
    ; GCN-NEXT: S_SETPC_B64 $sgpr30_sgpr31
    $vgpr0 = SI_SPILL_S32_TO_VGPR $sgpr30, 0, killed $vgpr0
    $vgpr0 = SI_SPILL_S32_TO_VGPR $sgpr31, 1, killed $vgpr0
    $sgpr34_sgpr35 = S_OR_SAVEEXEC_B64 -1, implicit-def $exec, implicit-def dead $scc, implicit $exec
    $vgpr1 = COPY $vgpr0
    $exec = S_MOV_B64 killed $sgpr34_sgpr35
    $sgpr30 = SI_RESTORE_S32_FROM_VGPR $vgpr1, 0
    $sgpr31 = SI_RESTORE_S32_FROM_VGPR $vgpr1, 1
    S_SETPC_B64 $sgpr30_sgpr31
...

# All scratch registers are made unavailable so that the CSR SGPR pair used for EXEC copy needed spills at prolog and epilog.

---
name:            spill_exec_copy_reserved_reg
tracksRegLiveness: true
frameInfo:
  maxAlignment:    4
machineFunctionInfo:
  isEntryFunction: false
  scratchRSrcReg:  '$sgpr0_sgpr1_sgpr2_sgpr3'
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
  sgprForEXECCopy: '$sgpr34_sgpr35'
body:             |
  bb.0:
    liveins: $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $sgpr10, $sgpr11, $sgpr12, $sgpr13, $sgpr14, $sgpr15, $sgpr16, $sgpr17, $sgpr18, $sgpr19, $sgpr20, $sgpr21, $sgpr22, $sgpr23, $sgpr24, $sgpr25, $sgpr26, $sgpr27, $sgpr30_sgpr31, $vcc, $vgpr0
    ; GCN-LABEL: name: spill_exec_copy_reserved_reg
    ; GCN: liveins: $vcc, $sgpr4, $sgpr5, $sgpr6, $sgpr7, $sgpr8, $sgpr9, $sgpr10, $sgpr11, $sgpr12, $sgpr13, $sgpr14, $sgpr15, $sgpr16, $sgpr17, $sgpr18, $sgpr19, $sgpr20, $sgpr21, $sgpr22, $sgpr23, $sgpr24, $sgpr25, $sgpr26, $sgpr27, $vgpr0, $vgpr2, $sgpr30_sgpr31
    ; GCN-NEXT: {{  $}}
    ; GCN-NEXT: frame-setup CFI_INSTRUCTION llvm_def_aspace_cfa $sgpr32_lo16, 0, 6
    ; GCN-NEXT: frame-setup CFI_INSTRUCTION llvm_register_pair $pc_reg, $sgpr30_lo16, 32, $sgpr31_lo16, 32
    ; GCN-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr0_lo16
    ; GCN-NEXT: frame-setup CFI_INSTRUCTION undefined $vgpr1_lo16
    ; GCN-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr28_lo16
    ; GCN-NEXT: frame-setup CFI_INSTRUCTION undefined $sgpr29_lo16
    ; GCN-NEXT: $sgpr28_sgpr29 = S_XOR_SAVEEXEC_B64 -1, implicit-def $exec, implicit-def dead $scc, implicit $exec
    ; GCN-NEXT: BUFFER_STORE_DWORD_OFFSET $vgpr2, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr32, 0, 0, 0, implicit $exec :: (store (s32) into %stack.1, addrspace 5)
    ; GCN-NEXT: frame-setup CFI_INSTRUCTION offset $vgpr2_lo16, 0
    ; GCN-NEXT: $exec = S_MOV_B64 killed $sgpr28_sgpr29
    ; GCN-NEXT: $vgpr2 = SI_SPILL_S32_TO_VGPR $sgpr34, 0, undef $vgpr2
    ; GCN-NEXT: frame-setup CFI_INSTRUCTION llvm_vector_registers $sgpr34_lo16, $vgpr2_lo16, 0, 32
    ; GCN-NEXT: $vgpr2 = SI_SPILL_S32_TO_VGPR $sgpr35, 1, undef $vgpr2
    ; GCN-NEXT: frame-setup CFI_INSTRUCTION llvm_vector_registers $sgpr35_lo16, $vgpr2_lo16, 1, 32
    ; GCN-NEXT: $vgpr0 = SI_SPILL_S32_TO_VGPR $sgpr30, 0, killed $vgpr0
    ; GCN-NEXT: $vgpr0 = SI_SPILL_S32_TO_VGPR $sgpr31, 1, killed $vgpr0
    ; GCN-NEXT: $sgpr34_sgpr35 = S_OR_SAVEEXEC_B64 -1, implicit-def $exec, implicit-def dead $scc, implicit $exec
    ; GCN-NEXT: $sgpr28_sgpr29 = IMPLICIT_DEF
    ; GCN-NEXT: $vgpr1 = COPY $vgpr0
    ; GCN-NEXT: S_NOP 0, implicit $sgpr28_sgpr29
    ; GCN-NEXT: $exec = S_MOV_B64 killed $sgpr34_sgpr35
    ; GCN-NEXT: $sgpr30 = SI_RESTORE_S32_FROM_VGPR $vgpr1, 0
    ; GCN-NEXT: $sgpr31 = SI_RESTORE_S32_FROM_VGPR $vgpr1, 1
    ; GCN-NEXT: S_SETPC_B64 $sgpr30_sgpr31, implicit $sgpr4, implicit $sgpr5, implicit $sgpr6, implicit $sgpr7, implicit $sgpr8_sgpr9_sgpr10, implicit $sgpr11, implicit $sgpr12, implicit $sgpr13, implicit $sgpr14, implicit $sgpr15, implicit $sgpr15, implicit $sgpr17, implicit $sgpr18, implicit $sgpr19, implicit $sgpr20, implicit $sgpr21, implicit $sgpr22, implicit $sgpr23, implicit $sgpr24, implicit $sgpr25, implicit $sgpr26, implicit $sgpr27, implicit $vcc
    $vgpr0 = SI_SPILL_S32_TO_VGPR $sgpr30, 0, killed $vgpr0
    $vgpr0 = SI_SPILL_S32_TO_VGPR $sgpr31, 1, killed $vgpr0
    $sgpr34_sgpr35 = S_OR_SAVEEXEC_B64 -1, implicit-def $exec, implicit-def dead $scc, implicit $exec
    $sgpr28_sgpr29 = IMPLICIT_DEF
    $vgpr1 = COPY $vgpr0
    S_NOP 0, implicit $sgpr28_sgpr29
    $exec = S_MOV_B64 killed $sgpr34_sgpr35
    $sgpr30 = SI_RESTORE_S32_FROM_VGPR $vgpr1, 0
    $sgpr31 = SI_RESTORE_S32_FROM_VGPR $vgpr1, 1
    S_SETPC_B64 $sgpr30_sgpr31, implicit $sgpr4, implicit $sgpr5, implicit $sgpr6, implicit $sgpr7, implicit $sgpr8_sgpr9_sgpr10, implicit $sgpr11, implicit $sgpr12, implicit $sgpr13, implicit $sgpr14, implicit $sgpr15, implicit $sgpr15, implicit $sgpr17, implicit $sgpr18, implicit $sgpr19, implicit $sgpr20, implicit $sgpr21, implicit $sgpr22, implicit $sgpr23, implicit $sgpr24, implicit $sgpr25, implicit $sgpr26, implicit $sgpr27, implicit $vcc
...
