# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=amdgcn -run-pass=block-placement -tail-dup-placement-threshold=2 -verify-machineinstrs -o - %s | FileCheck -check-prefix=GCN %s

# Check that tail duplication correctly counts instructions in a bundle.
# The bundle below shall not be duplicated.

---
name:            tail_dup_bundle
body:             |
  ; GCN-LABEL: name: tail_dup_bundle
  ; GCN: bb.0:
  ; GCN-NEXT:   successors: %bb.2(0x80000000)
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.2:
  ; GCN-NEXT:   BUNDLE {
  ; GCN-NEXT:     S_NOP 0
  ; GCN-NEXT:     S_NOP 0
  ; GCN-NEXT:   }
  ; GCN-NEXT:   S_ENDPGM 0
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT: bb.1:
  ; GCN-NEXT:   successors: %bb.2(0x80000000)
  ; GCN-NEXT: {{  $}}
  ; GCN-NEXT:   S_BRANCH %bb.2
  bb.0:
    successors: %bb.2(0x80000000)

    S_BRANCH %bb.2

  bb.1:
    successors: %bb.2(0x80000000)

  bb.2:

    BUNDLE {
      S_NOP 0
      S_NOP 0
    }
    S_ENDPGM 0

...
