; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
;RUN: llc < %s -mtriple=r600 -mcpu=redwood | FileCheck %s

;CHECK-NOT: MOV

define amdgpu_vs void @test(<4 x float> inreg %reg0) {
; CHECK-LABEL: test:
; CHECK:       ; %bb.0:
; CHECK-NEXT:    CALL_FS
; CHECK-NEXT:    ALU 2, @16, KC0[], KC1[]
; CHECK-NEXT:    TEX 0 @10
; CHECK-NEXT:    ALU 1, @19, KC0[], KC1[]
; CHECK-NEXT:    TEX 0 @12
; CHECK-NEXT:    ALU 1, @21, KC0[], KC1[]
; CHECK-NEXT:    TEX 0 @14
; CHECK-NEXT:    ALU 7, @23, KC0[], KC1[]
; CHECK-NEXT:    EXPORT T0.XYZW
; CHECK-NEXT:    CF_END
; CHECK-NEXT:    Fetch clause starting at 10:
; CHECK-NEXT:     TEX_SAMPLE T2.XYZW, T1.XY__ RID:0 SID:0 CT:UUUU
; CHECK-NEXT:    Fetch clause starting at 12:
; CHECK-NEXT:     TEX_SAMPLE T3.XYZW, T1.ZX__ RID:0 SID:0 CT:UUUU
; CHECK-NEXT:    Fetch clause starting at 14:
; CHECK-NEXT:     TEX_SAMPLE T0.XYZW, T1.W___ RID:0 SID:0 CT:UUUU
; CHECK-NEXT:    ALU clause starting at 16:
; CHECK-NEXT:     MUL_IEEE T1.X, T0.X, literal.x,
; CHECK-NEXT:     MUL_IEEE * T1.Y, T0.Y, literal.x,
; CHECK-NEXT:    1077936128(3.000000e+00), 0(0.000000e+00)
; CHECK-NEXT:    ALU clause starting at 19:
; CHECK-NEXT:     MUL_IEEE * T1.Z, T0.Z, literal.x,
; CHECK-NEXT:    1077936128(3.000000e+00), 0(0.000000e+00)
; CHECK-NEXT:    ALU clause starting at 21:
; CHECK-NEXT:     MUL_IEEE * T1.W, T0.W, literal.x,
; CHECK-NEXT:    1077936128(3.000000e+00), 0(0.000000e+00)
; CHECK-NEXT:    ALU clause starting at 23:
; CHECK-NEXT:     ADD T1.W, T2.W, T3.W,
; CHECK-NEXT:     ADD * T2.W, T2.Z, T3.Z,
; CHECK-NEXT:     ADD * T0.W, PV.W, T0.W,
; CHECK-NEXT:     ADD T0.Z, T2.W, T0.Z,
; CHECK-NEXT:     ADD * T1.W, T2.Y, T3.Y,
; CHECK-NEXT:     ADD T0.Y, PV.W, T0.Y,
; CHECK-NEXT:     ADD * T1.W, T2.X, T3.X,
; CHECK-NEXT:     ADD * T0.X, PV.W, T0.X,
  %1 = extractelement <4 x float> %reg0, i32 0
  %2 = extractelement <4 x float> %reg0, i32 1
  %3 = extractelement <4 x float> %reg0, i32 2
  %4 = extractelement <4 x float> %reg0, i32 3
  %5 = fmul float %1, 3.0
  %6 = fmul float %2, 3.0
  %7 = fmul float %3, 3.0
  %8 = fmul float %4, 3.0
  %9 = insertelement <4 x float> poison, float %5, i32 0
  %10 = insertelement <4 x float> %9, float %6, i32 1
  %11 = insertelement <4 x float> poison, float %7, i32 0
  %12 = insertelement <4 x float> %11, float %5, i32 1
  %13 = insertelement <4 x float> poison, float %8, i32 0
  %14 = call <4 x float> @llvm.r600.tex(<4 x float> %10, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0)
  %15 = call <4 x float> @llvm.r600.tex(<4 x float> %12, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0)
  %16 = call <4 x float> @llvm.r600.tex(<4 x float> %13, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0, i32 0)
  %17 = fadd <4 x float> %14, %15
  %18 = fadd <4 x float> %17, %16
  call void @llvm.r600.store.swizzle(<4 x float> %18, i32 0, i32 0)
  ret void
}

declare <4 x float> @llvm.r600.tex(<4 x float>, i32, i32, i32, i32, i32, i32, i32, i32, i32) readnone
declare void @llvm.r600.store.swizzle(<4 x float>, i32, i32)
