# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=amdgcn -mcpu=gfx90a -run-pass=finalize-isel -x mir < %s | FileCheck -check-prefix=GFX9 %s
# RUN: llc -mtriple=amdgcn -mcpu=gfx1100 -run-pass=finalize-isel -x mir < %s | FileCheck -check-prefix=GFX11 %s
# RUN: llc -mtriple=amdgcn -mcpu=gfx1200 -run-pass=finalize-isel -x mir < %s | FileCheck -check-prefix=GFX12 %s
# RUN: llc -mtriple=amdgcn -mcpu=gfx90a -passes=finalize-isel -x mir < %s | FileCheck -check-prefix=GFX9 %s
# RUN: llc -mtriple=amdgcn -mcpu=gfx1100 -passes=finalize-isel -x mir < %s | FileCheck -check-prefix=GFX11 %s
# RUN: llc -mtriple=amdgcn -mcpu=gfx1200 -passes=finalize-isel -x mir < %s | FileCheck -check-prefix=GFX12 %s


---
name: reg_ops
tracksRegLiveness: true
body: |
  bb.0:
    ; GFX9-LABEL: name: reg_ops
    ; GFX9: [[DEF:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; GFX9-NEXT: [[DEF1:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; GFX9-NEXT: [[V_ADD_F64_e64_:%[0-9]+]]:vreg_64_align2 = V_ADD_F64_e64 0, [[DEF]], 1, [[DEF1]], 0, 0, implicit $mode, implicit $exec
    ;
    ; GFX11-LABEL: name: reg_ops
    ; GFX11: [[DEF:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; GFX11-NEXT: [[DEF1:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; GFX11-NEXT: [[V_ADD_F64_e64_:%[0-9]+]]:vreg_64_align2 = V_ADD_F64_e64 0, [[DEF]], 1, [[DEF1]], 0, 0, implicit $mode, implicit $exec
    ;
    ; GFX12-LABEL: name: reg_ops
    ; GFX12: [[DEF:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; GFX12-NEXT: [[DEF1:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; GFX12-NEXT: [[V_ADD_F64_e64_gfx12_:%[0-9]+]]:vreg_64_align2 = V_ADD_F64_e64_gfx12 0, [[DEF]], 1, [[DEF1]], 0, 0, implicit $mode, implicit $exec
    %0:vreg_64_align2 = IMPLICIT_DEF
    %1:vreg_64_align2 = IMPLICIT_DEF
    %2:vreg_64_align2 = V_SUB_F64_PSEUDO 0, %0, 0, %1, 0, 0, implicit-def $vcc, implicit $exec
...

---
name: neg_flag
tracksRegLiveness: true
body: |
  bb.0:
    ; GFX9-LABEL: name: neg_flag
    ; GFX9: [[DEF:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; GFX9-NEXT: [[DEF1:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; GFX9-NEXT: [[V_ADD_F64_e64_:%[0-9]+]]:vreg_64_align2 = V_ADD_F64_e64 0, [[DEF]], 0, [[DEF1]], 0, 0, implicit $mode, implicit $exec
    ;
    ; GFX11-LABEL: name: neg_flag
    ; GFX11: [[DEF:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; GFX11-NEXT: [[DEF1:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; GFX11-NEXT: [[V_ADD_F64_e64_:%[0-9]+]]:vreg_64_align2 = V_ADD_F64_e64 0, [[DEF]], 0, [[DEF1]], 0, 0, implicit $mode, implicit $exec
    ;
    ; GFX12-LABEL: name: neg_flag
    ; GFX12: [[DEF:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; GFX12-NEXT: [[DEF1:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; GFX12-NEXT: [[V_ADD_F64_e64_gfx12_:%[0-9]+]]:vreg_64_align2 = V_ADD_F64_e64_gfx12 0, [[DEF]], 0, [[DEF1]], 0, 0, implicit $mode, implicit $exec
    %0:vreg_64_align2 = IMPLICIT_DEF
    %1:vreg_64_align2 = IMPLICIT_DEF
    %2:vreg_64_align2 = V_SUB_F64_PSEUDO 0, %0, 1, %1, 0, 0, implicit-def $vcc, implicit $exec
...

---
name: abs_flag
tracksRegLiveness: true
body: |
  bb.0:
    ; GFX9-LABEL: name: abs_flag
    ; GFX9: [[DEF:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; GFX9-NEXT: [[DEF1:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; GFX9-NEXT: [[V_ADD_F64_e64_:%[0-9]+]]:vreg_64_align2 = V_ADD_F64_e64 0, [[DEF]], 3, [[DEF1]], 0, 0, implicit $mode, implicit $exec
    ;
    ; GFX11-LABEL: name: abs_flag
    ; GFX11: [[DEF:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; GFX11-NEXT: [[DEF1:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; GFX11-NEXT: [[V_ADD_F64_e64_:%[0-9]+]]:vreg_64_align2 = V_ADD_F64_e64 0, [[DEF]], 3, [[DEF1]], 0, 0, implicit $mode, implicit $exec
    ;
    ; GFX12-LABEL: name: abs_flag
    ; GFX12: [[DEF:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; GFX12-NEXT: [[DEF1:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; GFX12-NEXT: [[V_ADD_F64_e64_gfx12_:%[0-9]+]]:vreg_64_align2 = V_ADD_F64_e64_gfx12 0, [[DEF]], 3, [[DEF1]], 0, 0, implicit $mode, implicit $exec
    %0:vreg_64_align2 = IMPLICIT_DEF
    %1:vreg_64_align2 = IMPLICIT_DEF
    %2:vreg_64_align2 = V_SUB_F64_PSEUDO 0, %0, 2, %1, 0, 0, implicit-def $vcc, implicit $exec
...

---
name: neg_abs_flag
tracksRegLiveness: true
body: |
  bb.0:
    ; GFX9-LABEL: name: neg_abs_flag
    ; GFX9: [[DEF:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; GFX9-NEXT: [[DEF1:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; GFX9-NEXT: [[V_ADD_F64_e64_:%[0-9]+]]:vreg_64_align2 = V_ADD_F64_e64 0, [[DEF]], 2, [[DEF1]], 0, 0, implicit $mode, implicit $exec
    ;
    ; GFX11-LABEL: name: neg_abs_flag
    ; GFX11: [[DEF:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; GFX11-NEXT: [[DEF1:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; GFX11-NEXT: [[V_ADD_F64_e64_:%[0-9]+]]:vreg_64_align2 = V_ADD_F64_e64 0, [[DEF]], 2, [[DEF1]], 0, 0, implicit $mode, implicit $exec
    ;
    ; GFX12-LABEL: name: neg_abs_flag
    ; GFX12: [[DEF:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; GFX12-NEXT: [[DEF1:%[0-9]+]]:vreg_64_align2 = IMPLICIT_DEF
    ; GFX12-NEXT: [[V_ADD_F64_e64_gfx12_:%[0-9]+]]:vreg_64_align2 = V_ADD_F64_e64_gfx12 0, [[DEF]], 2, [[DEF1]], 0, 0, implicit $mode, implicit $exec
    %0:vreg_64_align2 = IMPLICIT_DEF
    %1:vreg_64_align2 = IMPLICIT_DEF
    %2:vreg_64_align2 = V_SUB_F64_PSEUDO 0, %0, 3, %1, 0, 0, implicit-def $vcc, implicit $exec
...
