# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx908 -amdgpu-spill-vgpr-to-agpr=true -verify-machineinstrs -start-before=si-lower-sgpr-spills -stop-after=prologepilog -o - %s | FileCheck --check-prefixes=CHECK-ORIG-OPS %s
# RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx908 -amdgpu-spill-vgpr-to-agpr=true -verify-machineinstrs -start-before=si-lower-sgpr-spills -stop-after=prologepilog -o - -emit-heterogeneous-dwarf-as-user-ops %s | FileCheck --check-prefixes=CHECK-USER-OPS %s

# After handling the VGPR spill to AGPR copy in SILowerSGPRSpills pass, replace the dead frame index in the DBG_VALUE instruction with reg 0.
# Otherwise, the test would crash during PEI while trying to replace the dead frame index.
--- |
  define amdgpu_kernel void @test() { ret void }

  !0 = distinct !DICompileUnit(language: DW_LANG_C99, file: !4, producer: "llvm", isOptimized: true, runtimeVersion: 0, emissionKind: FullDebug, enums: !4, retainedTypes: !4)
  !1 = !DILocalVariable(name: "a", scope: !2, file: !4, line: 126, type: !6)
  !2 = distinct !DISubprogram(name: "test", scope: !4, file: !4, line: 1, type: !3, isLocal: false, isDefinition: true, scopeLine: 2, flags: DIFlagPrototyped, isOptimized: true, unit: !0, retainedNodes: !5)
  !3 = !DISubroutineType(types: !4)
  !4 = !{null}
  !5 = !{!1}
  !6 = !DIDerivedType(tag: DW_TAG_pointer_type, baseType: !7, size: 64, align: 32)
  !7 = !DIBasicType(name: "int", size: 32, align: 32, encoding: DW_ATE_signed)
  !8 = distinct !DILifetime(object: !1, location: !DIExpr())
  !9 = !DILocation(line: 10, column: 9, scope: !2)

...
---
name:            test
tracksRegLiveness: true
frameInfo:
  maxAlignment:    4
stack:
  - { id: 0, type: spill-slot, size: 4, alignment: 4 }
machineFunctionInfo:
  maxKernArgAlign: 4
  isEntryFunction: true
  waveLimiter:     true
  scratchRSrcReg:  '$sgpr96_sgpr97_sgpr98_sgpr99'
  stackPtrOffsetReg: '$sgpr32'
  frameOffsetReg: '$sgpr33'
  hasSpilledVGPRs: true
  argumentInfo:
    privateSegmentBuffer: { reg: '$sgpr0_sgpr1_sgpr2_sgpr3' }
    dispatchPtr:     { reg: '$sgpr4_sgpr5' }
    kernargSegmentPtr: { reg: '$sgpr6_sgpr7' }
    workGroupIDX:    { reg: '$sgpr8' }
    privateSegmentWaveByteOffset: { reg: '$sgpr9' }
body:             |
  ; CHECK-ORIG-OPS-LABEL: name: test
  ; CHECK-ORIG-OPS: bb.0:
  ; CHECK-ORIG-OPS-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-ORIG-OPS-NEXT:   liveins: $agpr0
  ; CHECK-ORIG-OPS-NEXT: {{  $}}
  ; CHECK-ORIG-OPS-NEXT:   frame-setup CFI_INSTRUCTION escape 0x0f, 0x04, 0x30, 0x36, 0xe9, 0x02
  ; CHECK-ORIG-OPS-NEXT:   frame-setup CFI_INSTRUCTION undefined $pc_reg
  ; CHECK-ORIG-OPS-NEXT:   $vgpr2 = IMPLICIT_DEF
  ; CHECK-ORIG-OPS-NEXT:   $agpr0 = V_ACCVGPR_WRITE_B32_e64 $vgpr2, implicit $exec
  ; CHECK-ORIG-OPS-NEXT: {{  $}}
  ; CHECK-ORIG-OPS-NEXT: bb.1:
  ; CHECK-ORIG-OPS-NEXT:   liveins: $agpr0
  ; CHECK-ORIG-OPS-NEXT: {{  $}}
  ; CHECK-ORIG-OPS-NEXT:   $vgpr2 = V_ACCVGPR_READ_B32_e64 $agpr0, implicit $exec
  ; CHECK-ORIG-OPS-NEXT:   S_ENDPGM 0
  ;
  ; CHECK-USER-OPS-LABEL: name: test
  ; CHECK-USER-OPS: bb.0:
  ; CHECK-USER-OPS-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-USER-OPS-NEXT:   liveins: $agpr0
  ; CHECK-USER-OPS-NEXT: {{  $}}
  ; CHECK-USER-OPS-NEXT:   frame-setup CFI_INSTRUCTION escape 0x0f, 0x04, 0x30, 0x36, 0xe9, 0x02
  ; CHECK-USER-OPS-NEXT:   frame-setup CFI_INSTRUCTION undefined $pc_reg
  ; CHECK-USER-OPS-NEXT:   $vgpr2 = IMPLICIT_DEF
  ; CHECK-USER-OPS-NEXT:   $agpr0 = V_ACCVGPR_WRITE_B32_e64 $vgpr2, implicit $exec
  ; CHECK-USER-OPS-NEXT: {{  $}}
  ; CHECK-USER-OPS-NEXT: bb.1:
  ; CHECK-USER-OPS-NEXT:   liveins: $agpr0
  ; CHECK-USER-OPS-NEXT: {{  $}}
  ; CHECK-USER-OPS-NEXT:   $vgpr2 = V_ACCVGPR_READ_B32_e64 $agpr0, implicit $exec
  ; CHECK-USER-OPS-NEXT:   S_ENDPGM 0
  bb.0:
    $vgpr2 = IMPLICIT_DEF
    SI_SPILL_V32_SAVE $vgpr2, %stack.0, $sgpr32, 0, implicit $exec :: (store (s32) into %stack.0, align 4, addrspace 5)
    DBG_DEF !8, %stack.0

  bb.1:
    renamable $vgpr2 = SI_SPILL_V32_RESTORE %stack.0, $sgpr32, 0, implicit $exec :: (load (s32) from %stack.0, align 4, addrspace 5)
    S_ENDPGM 0
