; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 6
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1100 -O2 -verify-machineinstrs < %s | FileCheck %s -check-prefixes=GCN,SDAG
; RUN: llc -global-isel -global-isel-abort=1 -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1100 -O2 -verify-machineinstrs < %s | FileCheck %s -check-prefixes=GCN,GISEL

; gfx1100 has no AGPRs to hide spills. Each function produces a long-lived
; <4 x i32> %held and a second <4 x i32> %other, then runs an inline-asm clobber
; of v8-v15; with "amdgpu-num-vgpr"="16" that leaves only enough room for one of
; the two to stay in registers across the clobber, so exactly one is spilled.
;
; Without the pin, %held (the longest-lived value, lowest spill weight) is the
; one spilled and reloaded. With llvm.amdgcn.internal.vgpr.pin applied to %held,
; markNotSpillable redirects the spill to %other and %held stays in VGPRs across
; the clobber. Compare the @nopin (held spilled) vs @pin (other spilled) output.

define void @nopin(ptr addrspace(1) %p) #0 {
; GCN-LABEL: nopin:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    ;;#ASMSTART
; GCN-NEXT:    ; def held
; GCN-NEXT:    ;;#ASMEND
; GCN-NEXT:    scratch_store_b128 off, v[2:5], s32 ; 16-byte Folded Spill
; GCN-NEXT:    ;;#ASMSTART
; GCN-NEXT:    ; def other
; GCN-NEXT:    ;;#ASMEND
; GCN-NEXT:    ;;#ASMSTART
; GCN-NEXT:    ; clobber
; GCN-NEXT:    ;;#ASMEND
; GCN-NEXT:    global_store_b128 v[0:1], v[2:5], off dlc
; GCN-NEXT:    s_waitcnt_vscnt null, 0x0
; GCN-NEXT:    scratch_load_b128 v[2:5], off, s32 ; 16-byte Folded Reload
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    global_store_b128 v[0:1], v[2:5], off dlc
; GCN-NEXT:    s_waitcnt_vscnt null, 0x0
; GCN-NEXT:    s_setpc_b64 s[30:31]
  %held = call <4 x i32> asm sideeffect "; def held", "=v"()
  %other = call <4 x i32> asm sideeffect "; def other", "=v"()
  call void asm sideeffect "; clobber", "~{v8},~{v9},~{v10},~{v11},~{v12},~{v13},~{v14},~{v15}"()
  store volatile <4 x i32> %other, ptr addrspace(1) %p
  store volatile <4 x i32> %held, ptr addrspace(1) %p
  ret void
}

define void @pin(ptr addrspace(1) %p) #0 {
; GCN-LABEL: pin:
; GCN:       ; %bb.0:
; GCN-NEXT:    s_waitcnt vmcnt(0) expcnt(0) lgkmcnt(0)
; GCN-NEXT:    ;;#ASMSTART
; GCN-NEXT:    ; def held
; GCN-NEXT:    ;;#ASMEND
; GCN-NEXT:    ;;#ASMSTART
; GCN-NEXT:    ; def other
; GCN-NEXT:    ;;#ASMEND
; GCN-NEXT:    scratch_store_b128 off, v[6:9], s32 ; 16-byte Folded Spill
; GCN-NEXT:    ;;#ASMSTART
; GCN-NEXT:    ; clobber
; GCN-NEXT:    ;;#ASMEND
; GCN-NEXT:    scratch_load_b128 v[6:9], off, s32 ; 16-byte Folded Reload
; GCN-NEXT:    s_waitcnt vmcnt(0)
; GCN-NEXT:    global_store_b128 v[0:1], v[6:9], off dlc
; GCN-NEXT:    s_waitcnt_vscnt null, 0x0
; GCN-NEXT:    global_store_b128 v[0:1], v[2:5], off dlc
; GCN-NEXT:    s_waitcnt_vscnt null, 0x0
; GCN-NEXT:    s_setpc_b64 s[30:31]
  %held = call <4 x i32> asm sideeffect "; def held", "=v"()
  call void @llvm.amdgcn.internal.vgpr.pin.v4i32(<4 x i32> %held)
  %other = call <4 x i32> asm sideeffect "; def other", "=v"()
  call void asm sideeffect "; clobber", "~{v8},~{v9},~{v10},~{v11},~{v12},~{v13},~{v14},~{v15}"()
  store volatile <4 x i32> %other, ptr addrspace(1) %p
  store volatile <4 x i32> %held, ptr addrspace(1) %p
  ret void
}

declare void @llvm.amdgcn.internal.vgpr.pin.v4i32(<4 x i32>)

attributes #0 = { nounwind "amdgpu-num-vgpr"="16" }
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; GISEL: {{.*}}
; SDAG: {{.*}}
