; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -mtriple=amdgcn -mcpu=gfx1300 -verify-machineinstrs < %s | FileCheck %s --check-prefix=GFX13

define amdgpu_ps void @test_permute_pair_2src_interleave_b64(i32 %src0, i32 %src1, ptr addrspace(1) %out0, ptr addrspace(1) %out1) {
; GFX13-LABEL: test_permute_pair_2src_interleave_b64:
; GFX13:       ; %bb.0: ; %bb
; GFX13-NEXT:    v_permute_pair_2src_interleave_b64 v0, v1, v0, v1 aux_data:2
; GFX13-NEXT:    global_store_b32 v[2:3], v0, off scope:SCOPE_SE
; GFX13-NEXT:    global_store_b32 v[4:5], v1, off scope:SCOPE_SE
; GFX13-NEXT:    s_endpgm
bb:
  %pair = call { i32, i32 } @llvm.amdgcn.permute.pair.2src.interleave.b64(i32 %src0, i32 %src1, i32 2)
  %dst0 = extractvalue { i32, i32 } %pair, 0
  %dst1 = extractvalue { i32, i32 } %pair, 1
  store i32 %dst0, ptr addrspace(1) %out0
  store i32 %dst1, ptr addrspace(1) %out1
  ret void
}

define amdgpu_ps void @test_permute_pack_tensor_2src_b64(i32 %src0, i32 %src1, ptr addrspace(1) %out0, ptr addrspace(1) %out1) {
; GFX13-LABEL: test_permute_pack_tensor_2src_b64:
; GFX13:       ; %bb.0: ; %bb
; GFX13-NEXT:    v_permute_pack_tensor_2src_b64 v0, v1, v0, v1 aux_data:2
; GFX13-NEXT:    global_store_b32 v[2:3], v0, off scope:SCOPE_SE
; GFX13-NEXT:    global_store_b32 v[4:5], v1, off scope:SCOPE_SE
; GFX13-NEXT:    s_endpgm
bb:
  %pair = call { i32, i32 } @llvm.amdgcn.permute.pack.tensor.2src.b64(i32 %src0, i32 %src1, i32 2)
  %dst0 = extractvalue { i32, i32 } %pair, 0
  %dst1 = extractvalue { i32, i32 } %pair, 1
  store i32 %dst0, ptr addrspace(1) %out0
  store i32 %dst1, ptr addrspace(1) %out1
  ret void
}
