; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1300 -o - < %s | FileCheck --check-prefixes=CHECK,KERNEL %s

; Test a laneshared global that is too large to ever fit into registers.

@ls = external addrspace(10) global [2048 x i32], align 4

; TODO-GFX13: Use test to show how to get rid of the unneeded global_inv/wb

define amdgpu_kernel void @wavegroup_kernel() "amdgpu-wavegroup-enable" "amdgpu-no-dispatch-ptr" "amdgpu-no-implicitarg-ptr" "amdgpu-no-dispatch-id" "amdgpu-no-workgroup-id-y" "amdgpu-no-workgroup-id-z" "amdgpu-no-cluster-id-x" "amdgpu-no-cluster-id-y" "amdgpu-no-cluster-id-z" !reqd_work_group_size !{i32 32, i32 8, i32 1} {
; CHECK-LABEL: wavegroup_kernel:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_getreg_b32 s0, hwreg(HW_REG_WAVE_GROUP_INFO, 16, 4)
; CHECK-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; CHECK-NEXT:    s_mul_i32 s1, s0, 1
; CHECK-NEXT:    s_mul_i32 s33, s0, s2
; CHECK-NEXT:    s_set_gpr_idx_u32 idx0, s1
; CHECK-NEXT:    s_add_co_u32 s33, s33, 0x2000
; CHECK-NEXT:    ; sched_barrier mask(0x00000000)
; CHECK-NEXT:    s_mov_b32 s0, 4
; CHECK-NEXT:    scratch_load_b32 v0, off, s0
; CHECK-NEXT:    s_mov_b32 s0, 8
; CHECK-NEXT:    s_wait_loadcnt 0x0
; CHECK-NEXT:    scratch_store_b32 off, v0, s0
; CHECK-NEXT:    s_endpgm
entry:
  %src = getelementptr i32, ptr addrspace(10) @ls, i32 1
  %dst = getelementptr i32, ptr addrspace(10) @ls, i32 2
  %x = load i32, ptr addrspace(10) %src
  store i32 %x, ptr addrspace(10) %dst
  ret void
}

; KERNEL:      .amdhsa_kernel wavegroup_kernel
; KERNEL-NEXT:         .amdhsa_group_segment_fixed_size 0
; KERNEL-NEXT:         .amdhsa_private_segment_fixed_size 0
; KERNEL-NEXT:         .amdhsa_kernarg_size 0
; KERNEL-NEXT:         .amdhsa_user_sgpr_count 3
; KERNEL-NEXT:         .amdhsa_user_sgpr_dispatch_ptr 0
; KERNEL-NEXT:         .amdhsa_user_sgpr_queue_ptr 1
; KERNEL-NEXT:         .amdhsa_user_sgpr_kernarg_segment_ptr 0
; KERNEL-NEXT:         .amdhsa_user_sgpr_dispatch_id 0
; KERNEL-NEXT:         .amdhsa_user_sgpr_private_segment_size 1
; KERNEL-NEXT:         .amdhsa_wavefront_size32 1
; KERNEL-NEXT:         .amdhsa_uses_dynamic_stack 0
; KERNEL-NEXT:         .amdhsa_enable_wavegroup 1
; KERNEL-NEXT:         .amdhsa_enable_spatial_cluster 0
; KERNEL-NEXT:         .amdhsa_enable_asymmetric_cluster_clamp 0
; KERNEL-NEXT:         .amdhsa_laneshared_segment_fixed_size 8192
; KERNEL-NEXT:         .amdhsa_enable_private_segment 1
; KERNEL-NEXT:         .amdhsa_system_sgpr_workgroup_id_x 1
; KERNEL-NEXT:         .amdhsa_system_sgpr_workgroup_id_y 0
; KERNEL-NEXT:         .amdhsa_system_sgpr_workgroup_id_z 0
; KERNEL-NEXT:         .amdhsa_system_sgpr_workgroup_info 0
; KERNEL-NEXT:         .amdhsa_system_vgpr_workitem_id 1
; KERNEL-NEXT:         .amdhsa_next_free_vgpr 2
; KERNEL-NEXT:         .amdhsa_next_free_sgpr 34
; KERNEL-NEXT:         .amdhsa_named_barrier_count 0
; KERNEL-NEXT:         .amdhsa_reserve_vcc 0
; KERNEL-NEXT:         .amdhsa_float_round_mode_32 0
; KERNEL-NEXT:         .amdhsa_float_round_mode_16_64 0
; KERNEL-NEXT:         .amdhsa_float_denorm_mode_32 3
; KERNEL-NEXT:         .amdhsa_float_denorm_mode_16_64 3
; KERNEL-NEXT:         .amdhsa_fp16_overflow 0
; KERNEL-NEXT:         .amdhsa_workgroup_processor_mode 1
; KERNEL-NEXT:         .amdhsa_memory_ordered 1
; KERNEL-NEXT:         .amdhsa_forward_progress 1
; KERNEL-NEXT:         .amdhsa_inst_pref_size 1
; KERNEL-NEXT:         .amdhsa_round_robin_scheduling 0

; KERNEL:      {{^}}amdhsa.kernels:
; KERNEL-NEXT:  - .args: []
; KERNEL-NEXT:    .enable_wavegroup: true
; KERNEL-NEXT:    .group_segment_fixed_size: 0
; KERNEL-NEXT:    .kernarg_segment_align: 4
; KERNEL-NEXT:    .kernarg_segment_size: 0
; KERNEL-NEXT:    .laneshared_segment_fixed_size: 8192
; KERNEL-NEXT:    .max_flat_workgroup_size: 1024
; KERNEL-NEXT:    .name:           wavegroup_kernel
; KERNEL-NEXT:    .private_segment_fixed_size: 0
; KERNEL-NEXT:    .reqd_workgroup_size:
; KERNEL-NEXT:      - 32
; KERNEL-NEXT:      - 8
; KERNEL-NEXT:      - 1
; KERNEL-NEXT:    .sgpr_count:     34
; KERNEL-NEXT:    .sgpr_spill_count: 0
; KERNEL-NEXT:    .spatial_cluster: false
; KERNEL-NEXT:    .symbol:         wavegroup_kernel.kd
; KERNEL-NEXT:    .uses_dynamic_stack: false
; KERNEL-NEXT:    .vgpr_count:     2
; KERNEL-NEXT:    .vgpr_spill_count: 0
; KERNEL-NEXT:    .wavefront_size: 32
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; KERNEL: {{.*}}
