; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1300 -o - < %s | FileCheck --check-prefixes=CHECK,KERNEL %s
; RUN: not --crash llc -mtriple=amdgcn -mcpu=gfx1300 -mattr=+cumode -o /dev/null %s 2>&1 | FileCheck -check-prefix=CUMODE-ERR %s
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1300 -o - -filetype=obj < %s | llvm-objdump --disassemble - | FileCheck --check-prefixes=DISASM %s

; CUMODE-ERR: LLVM ERROR: cannot enable cumode when wavegroup is enabled

;
; Check that binary emit also fills in the VGPR count correctly.
;
; DISASM-LABEL: 0000000000000000 <wavegroup_kernel>:
; DISASM-NEXT:    s_getreg_b32 s0, hwreg(HW_REG_WAVE_GROUP_INFO, 16, 4)
; DISASM-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; DISASM-NEXT:    s_mul_i32 s1, s0, 2
; DISASM-NEXT:    s_mul_i32 s33, s0, s4
; DISASM-NEXT:    s_set_gpr_idx_u32 idx0, s1

define amdgpu_kernel void @wavegroup_kernel(ptr addrspace(1) %p) #0 "amdgpu-wavegroup-enable" "amdgpu-no-dispatch-ptr" "amdgpu-no-implicitarg-ptr" "amdgpu-no-dispatch-id" "amdgpu-no-workgroup-id-y" "amdgpu-no-workgroup-id-z" "amdgpu-no-cluster-id-x" "amdgpu-no-cluster-id-y" "amdgpu-no-cluster-id-z" !reqd_work_group_size !{i32 32, i32 8, i32 1} {
; CHECK-LABEL: wavegroup_kernel:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_getreg_b32 s0, hwreg(HW_REG_WAVE_GROUP_INFO, 16, 4)
; CHECK-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; CHECK-NEXT:    s_mul_i32 s1, s0, 2
; CHECK-NEXT:    s_mul_i32 s33, s0, s4
; CHECK-NEXT:    s_set_gpr_idx_u32 idx0, s1
; CHECK-NEXT:    ; sched_barrier mask(0x00000000)
; CHECK-NEXT:    s_bfe_u32 s4, ttmp6, 0x4000c
; CHECK-NEXT:    s_load_b64 s[0:1], s[2:3], 0x0
; CHECK-NEXT:    s_add_co_i32 s4, s4, 1
; CHECK-NEXT:    s_and_b32 s3, ttmp6, 15
; CHECK-NEXT:    s_mul_i32 s4, ttmp9, s4
; CHECK-NEXT:    s_getreg_b32 s5, hwreg(HW_REG_WAVE_GROUP_INFO, 0, 4)
; CHECK-NEXT:    s_bfe_u32 s2, ttmp8, 0x20019
; CHECK-NEXT:    s_add_co_i32 s3, s3, s4
; CHECK-NEXT:    s_cmp_eq_u32 s5, 0
; CHECK-NEXT:    s_getreg_b32 s4, hwreg(HW_REG_WAVE_GROUP_INFO, 16, 4)
; CHECK-NEXT:    s_cselect_b32 s3, ttmp9, s3
; CHECK-NEXT:    s_lshl_b32 s2, s2, 6
; CHECK-NEXT:    s_lshl_b32 s3, s3, 8
; CHECK-NEXT:    v_mbcnt_lo_u32_b32 v0, -1, 0
; CHECK-NEXT:    s_or_b32 s2, s3, s2
; CHECK-NEXT:    s_lshl_b32 s3, s4, 5
; CHECK-NEXT:    v_mov_b32_e32 v1, 0
; CHECK-NEXT:    s_or_b32 s2, s2, s3
; CHECK-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; CHECK-NEXT:    v_or3_b32 v0, s2, v0, v0
; CHECK-NEXT:    s_wait_kmcnt 0x0
; CHECK-NEXT:    global_store_b32 v0, v1, s[0:1] scale_offset scope:SCOPE_SE
; CHECK-NEXT:    s_endpgm
entry:
  %wg_x = call i32 @llvm.amdgcn.workgroup.id.x()
  %wavegroup = call i32 @llvm.amdgcn.wavegroup.id()
  %wave = call i32 @llvm.amdgcn.wave.id.in.wavegroup()
  %lane = call i32 @llvm.amdgcn.mbcnt.lo(i32 -1, i32 0)
  %tidx = call i32 @llvm.amdgcn.workitem.id.x()
  %t0 = mul i32 %wg_x, 4
  %t1 = or i32 %t0, %wavegroup
  %t2 = mul i32 %t1, 2
  %t3 = or i32 %t2, %wave
  %t4 = mul i32 %t3, 32
  %t5 = or i32 %t4, %lane
  %t6 = or i32 %t5, %tidx
  %p0 = getelementptr i32, ptr addrspace(1) %p, i32 %t6
  store i32 0, ptr addrspace(1) %p0
  ret void
}

attributes #0 = {"amdgpu-flat-work-group-size"="256,256"}

; KERNEL:      .amdhsa_kernel wavegroup_kernel
; KERNEL-NEXT:         .amdhsa_group_segment_fixed_size 0
; KERNEL-NEXT:         .amdhsa_private_segment_fixed_size 0
; KERNEL-NEXT:         .amdhsa_kernarg_size 8
; KERNEL-NEXT:         .amdhsa_user_sgpr_count 5
; KERNEL-NEXT:         .amdhsa_user_sgpr_dispatch_ptr 0
; KERNEL-NEXT:         .amdhsa_user_sgpr_queue_ptr 1
; KERNEL-NEXT:         .amdhsa_user_sgpr_kernarg_segment_ptr 1
; KERNEL-NEXT:         .amdhsa_user_sgpr_dispatch_id 0
; KERNEL-NEXT:         .amdhsa_user_sgpr_private_segment_size 1
; KERNEL-NEXT:         .amdhsa_wavefront_size32 1
; KERNEL-NEXT:         .amdhsa_uses_dynamic_stack 0
; KERNEL-NEXT:         .amdhsa_enable_wavegroup 1
; KERNEL-NEXT:         .amdhsa_enable_spatial_cluster 0
; KERNEL-NEXT:         .amdhsa_enable_asymmetric_cluster_clamp 0
; KERNEL-NEXT:         .amdhsa_laneshared_segment_fixed_size 0
; KERNEL-NEXT:         .amdhsa_enable_private_segment 0
; KERNEL-NEXT:         .amdhsa_system_sgpr_workgroup_id_x 1
; KERNEL-NEXT:         .amdhsa_system_sgpr_workgroup_id_y 0
; KERNEL-NEXT:         .amdhsa_system_sgpr_workgroup_id_z 0
; KERNEL-NEXT:         .amdhsa_system_sgpr_workgroup_info 0
; KERNEL-NEXT:         .amdhsa_system_vgpr_workitem_id 1
; KERNEL-NEXT:         .amdhsa_next_free_vgpr 4
; KERNEL-NEXT:         .amdhsa_next_free_sgpr 34
; KERNEL-NEXT:		     .amdhsa_named_barrier_count 0
; KERNEL-NEXT:		     .amdhsa_reserve_vcc 0
; KERNEL-NEXT:         .amdhsa_float_round_mode_32 0
; KERNEL-NEXT:         .amdhsa_float_round_mode_16_64 0
; KERNEL-NEXT:         .amdhsa_float_denorm_mode_32 3
; KERNEL-NEXT:         .amdhsa_float_denorm_mode_16_64 3
; KERNEL-NEXT:         .amdhsa_fp16_overflow 0
; KERNEL-NEXT:         .amdhsa_workgroup_processor_mode 1
; KERNEL-NEXT:         .amdhsa_memory_ordered 1
; KERNEL-NEXT:         .amdhsa_forward_progress 1
; KERNEL-NEXT:         .amdhsa_inst_pref_size 2
; KERNEL-NEXT:         .amdhsa_round_robin_scheduling 0

; KERNEL:      {{^}}amdhsa.kernels:
; KERNEL-NEXT:  - .args:
; KERNEL-NEXT:      - .address_space:  global
; KERNEL-NEXT:        .name:           p
; KERNEL-NEXT:        .offset:         0
; KERNEL-NEXT:        .size:           8
; KERNEL-NEXT:        .value_kind:     global_buffer
; KERNEL-NEXT:    .enable_wavegroup: true
; KERNEL-NEXT:    .group_segment_fixed_size: 0
; KERNEL-NEXT:    .kernarg_segment_align: 8
; KERNEL-NEXT:    .kernarg_segment_size: 8
; KERNEL-NEXT:    .laneshared_segment_fixed_size: 0
; KERNEL-NEXT:    .max_flat_workgroup_size: 256
; KERNEL-NEXT:    .name:           wavegroup_kernel
; KERNEL-NEXT:    .private_segment_fixed_size: 0
; KERNEL-NEXT:    .reqd_workgroup_size:
; KERNEL-NEXT:      - 32
; KERNEL-NEXT:      - 8
; KERNEL-NEXT:      - 1
; KERNEL-NEXT:    .sgpr_count:     34
; KERNEL-NEXT:    .sgpr_spill_count: 0
; KERNEL-NEXT:    .spatial_cluster: false
; KERNEL-NEXT:    .symbol:         wavegroup_kernel.kd
; KERNEL-NEXT:    .uses_dynamic_stack: false
; KERNEL-NEXT:    .vgpr_count:     4
; KERNEL-NEXT:    .vgpr_spill_count: 0
; KERNEL-NEXT:    .wavefront_size: 32
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; KERNEL: {{.*}}
