; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1300 -o - < %s | FileCheck --check-prefixes=KERNEL %s

; Test a laneshared global that is large yet fit into registers.

@ls = external addrspace(10) global [512 x i32], align 4

define amdgpu_kernel void @wavegroup_kernel() "amdgpu-wavegroup-enable" "amdgpu-no-dispatch-ptr" "amdgpu-no-implicitarg-ptr" "amdgpu-no-dispatch-id" "amdgpu-no-workgroup-id-y" "amdgpu-no-workgroup-id-z" !reqd_work_group_size !{i32 32, i32 8, i32 1} {
; KERNEL-LABEL: wavegroup_kernel:
; KERNEL:       ; %bb.0: ; %entry
; KERNEL-NEXT:    s_getreg_b32 s0, hwreg(HW_REG_WAVE_GROUP_INFO, 16, 4)
; KERNEL-NEXT:    s_delay_alu instid0(SALU_CYCLE_1) | instskip(SKIP_2) | instid1(SALU_CYCLE_1)
; KERNEL-NEXT:    s_mul_i32 s1, s0, 0
; KERNEL-NEXT:    s_mul_i32 s33, s0, s2
; KERNEL-NEXT:    s_add_co_u32 s1, s1, 0x200
; KERNEL-NEXT:    s_set_gpr_idx_u32 idx0, s1
; KERNEL-NEXT:    ; sched_barrier mask(0x00000000)
; KERNEL-NEXT:    s_set_gpr_idx_u32 idx1, 0
; KERNEL-NEXT:    s_set_vgpr_frames 0x41 ; vsrc0_idx=1 vsrc1_idx=0 vsrc2_idx=0 vdst_idx=1 vsrc0_msb=0 vsrc1_msb=0 vsrc2_msb=0 vdst_msb=0
; KERNEL-NEXT:    v_mov_b32_e32 g1[2], g1[1]
; KERNEL-NEXT:    s_endpgm
entry:
  %src = getelementptr i32, ptr addrspace(10) @ls, i32 1
  %dst = getelementptr i32, ptr addrspace(10) @ls, i32 2
  %x = load i32, ptr addrspace(10) %src
  store i32 %x, ptr addrspace(10) %dst
  ret void
}
; KERNEL:      {{^}}amdhsa.kernels:
; KERNEL-NEXT:  - .args: []
; KERNEL-NEXT:    .enable_wavegroup: true
; KERNEL-NEXT:    .group_segment_fixed_size: 0
; KERNEL-NEXT:    .kernarg_segment_align: 4
; KERNEL-NEXT:    .kernarg_segment_size: 0
; KERNEL-NEXT:    .laneshared_segment_fixed_size: 0
; KERNEL-NEXT:    .max_flat_workgroup_size: 1024
; KERNEL-NEXT:    .name:           wavegroup_kernel
; KERNEL-NEXT:    .private_segment_fixed_size: 0
; KERNEL-NEXT:    .reqd_workgroup_size:
; KERNEL-NEXT:      - 32
; KERNEL-NEXT:      - 8
; KERNEL-NEXT:      - 1
; KERNEL-NEXT:    .sgpr_count:     34
; KERNEL-NEXT:    .sgpr_spill_count: 0
; KERNEL-NEXT:    .spatial_cluster: false
; KERNEL-NEXT:    .symbol:         wavegroup_kernel.kd
; KERNEL-NEXT:    .uses_dynamic_stack: false
; KERNEL-NEXT:    .vgpr_count:     512
; KERNEL-NEXT:    .vgpr_spill_count: 0
; KERNEL-NEXT:    .wavefront_size: 32
