; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 5
; RUN: llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx1300 -verify-machineinstrs -o - %s | FileCheck --check-prefixes=CHECK,RANK %s

; This test has those function attributes setup so that kern-arg-segment-ptr should use s[0-1].
; Those preloaded sgprs need to be preserved in the main-kernel so that they can be used
; in the rank-functions.

target datalayout = "A5"

@weights = external local_unnamed_addr addrspace(10) global <9 x i32>, align 64
@col_center = external local_unnamed_addr addrspace(10) global <3 x i32>, align 16
@col_left = external local_unnamed_addr addrspace(10) global <3 x i32>, align 16
@col_right = external local_unnamed_addr addrspace(10) global <3 x i32>, align 16
@out = external local_unnamed_addr addrspace(10) global <8 x i16>, align 16

@sem1 = internal addrspace(3) global target("amdgcn.semaphore", 1) poison
@sem2 = internal addrspace(3) global target("amdgcn.semaphore", 2) poison

define private amdgpu_kernel void @input(ptr addrspace(1) %inbuf, ptr addrspace(1) %wbuf, ptr addrspace(1) %outbuf) #0 #1 {
; CHECK-LABEL: input:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_load_b128 s[0:3], s[0:1], 0x0
; CHECK-NEXT:    s_wait_kmcnt 0x0
; CHECK-NEXT:    s_clause 0x2
; CHECK-NEXT:    s_load_b96 s[4:6], s[0:1], 0x0
; CHECK-NEXT:    s_load_b96 s[8:10], s[0:1], 0x100
; CHECK-NEXT:    s_load_b96 s[12:14], s[0:1], 0x200
; CHECK-NEXT:    s_clause 0x2
; CHECK-NEXT:    s_load_b96 s[16:18], s[2:3], 0x0
; CHECK-NEXT:    s_load_b96 s[20:22], s[2:3], 0x100
; CHECK-NEXT:    s_load_b96 s[0:2], s[2:3], 0x200
; CHECK-NEXT:    s_set_gpr_idx_u32 idx1, 0
; CHECK-NEXT:    s_wait_kmcnt 0x0
; CHECK-NEXT:    v_dual_mov_b32 v0, s4 :: v_dual_mov_b32 v1, s5
; CHECK-NEXT:    v_dual_mov_b32 v6, s12 :: v_dual_mov_b32 v7, s13
; CHECK-NEXT:    v_dual_mov_b32 v12, s20 :: v_dual_mov_b32 v13, s21
; CHECK-NEXT:    v_dual_mov_b32 v2, s6 :: v_dual_mov_b32 v3, s8
; CHECK-NEXT:    v_dual_mov_b32 v8, s14 :: v_dual_mov_b32 v9, s16
; CHECK-NEXT:    v_dual_mov_b32 v14, s22 :: v_dual_mov_b32 v17, s2
; CHECK-NEXT:    v_dual_mov_b32 v4, s9 :: v_dual_mov_b32 v5, s10
; CHECK-NEXT:    v_dual_mov_b32 v10, s17 :: v_dual_mov_b32 v11, s18
; CHECK-NEXT:    v_dual_mov_b32 v16, s1 :: v_dual_mov_b32 v15, s0
; CHECK-NEXT:    s_set_vgpr_frames 64 ; vsrc0_idx=0 vsrc1_idx=0 vsrc2_idx=0 vdst_idx=1 vsrc0_msb=0 vsrc1_msb=0 vsrc2_msb=0 vdst_msb=0
; CHECK-NEXT:    v_mov_b32_e32 g1[20], v3
; CHECK-NEXT:    v_mov_b32_e32 g1[21], v4
; CHECK-NEXT:    v_mov_b32_e32 g1[22], v5
; CHECK-NEXT:    v_mov_b32_e32 g1[24], v6
; CHECK-NEXT:    v_mov_b32_e32 g1[25], v7
; CHECK-NEXT:    v_mov_b32_e32 g1[26], v8
; CHECK-NEXT:    v_mov_b32_e32 g1[16], v0
; CHECK-NEXT:    v_mov_b32_e32 g1[17], v1
; CHECK-NEXT:    v_mov_b32_e32 g1[18], v2
; CHECK-NEXT:    v_mov_b32_e32 g1[0], v9
; CHECK-NEXT:    v_mov_b32_e32 g1[1], v10
; CHECK-NEXT:    v_mov_b32_e32 g1[2], v11
; CHECK-NEXT:    v_mov_b32_e32 g1[48], v12
; CHECK-NEXT:    v_mov_b32_e32 g1[49], v13
; CHECK-NEXT:    v_mov_b32_e32 g1[50], v14
; CHECK-NEXT:    v_mov_b32_e32 g1[96], v15
; CHECK-NEXT:    v_mov_b32_e32 g1[97], v16
; CHECK-NEXT:    v_mov_b32_e32 g1[98], v17
; CHECK-NEXT:    s_sema_signal 17
; CHECK-NEXT:    s_endpgm
entry:
  %vec30 = load <3 x i32>, ptr addrspace(1) %inbuf, align 16
  %ld.p1 = getelementptr <3 x i32>, ptr addrspace(1) %inbuf, i64 16
  %vec31 = load <3 x i32>, ptr addrspace(1) %ld.p1, align 16
  %ld.p2 = getelementptr <3 x i32>, ptr addrspace(1) %inbuf, i64 32
  %vec32 = load <3 x i32>, ptr addrspace(1) %ld.p2, align 16

  %wei30 = load <3 x i32>, ptr addrspace(1) %wbuf, align 64
  %w.p1 = getelementptr <3 x i32>, ptr addrspace(1) %wbuf, i64 16
  %wei31 = load <3 x i32>, ptr addrspace(1) %w.p1, align 16
  %w.p2 = getelementptr <3 x i32>, ptr addrspace(1) %wbuf, i64 32
  %wei32 = load <3 x i32>, ptr addrspace(1) %w.p2, align 16

  store <3 x i32> %vec30, ptr addrspace(10) @col_center, align 16
  store <3 x i32> %vec31, ptr addrspace(10) @col_left, align 16
  store <3 x i32> %vec32, ptr addrspace(10) @col_right, align 16

  store <3 x i32> %wei30, ptr addrspace(10) @weights, align 64
  %wei.p1 = getelementptr <3 x i32>, ptr addrspace(10) @weights, i64 12
  store <3 x i32> %wei31, ptr addrspace(10) %wei.p1, align 64
  %wei.p2 = getelementptr <3 x i32>, ptr addrspace(10) @weights, i64 24
  store <3 x i32> %wei32, ptr addrspace(10) %wei.p2, align 64

  call void @llvm.amdgcn.s.sema.signal(ptr addrspace(3) @sem1)
  ret void
}

define private amdgpu_kernel void @compute(ptr addrspace(1) %inbuf, ptr addrspace(1) %wbuf, ptr addrspace(1) %outbuf) #0 #1 {
; CHECK-LABEL: compute:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_sema_wait 1
; CHECK-NEXT:    s_set_gpr_idx_u32 idx1, 0
; CHECK-NEXT:    v_convolve_f16_fp8_fp8 g1[28:31], 0, g1[0:8], g1[16:18], g1[20:22], g1[24:26] aux_data:42 clamp idxs:0x111101
; CHECK-NEXT:    s_sema_signal 33
; CHECK-NEXT:    s_endpgm
entry:
  call void @llvm.amdgcn.s.sema.wait(ptr addrspace(3) @sem1)
  %vec30 = load <3 x i32>, ptr addrspace(10) @col_center, align 16
  %vec31 = load <3 x i32>, ptr addrspace(10) @col_left, align 16
  %vec32 = load <3 x i32>, ptr addrspace(10) @col_right, align 16
  %wei = load <9 x i32>, ptr addrspace(10) @weights, align 64
  %0 = tail call contract <8 x half> @llvm.amdgcn.convolve.f16.fp8.fp8.3x3.v8f16.v8f16.v9i32.v3i32(<8 x half> zeroinitializer, <9 x i32> %wei, <3 x i32> %vec30, <3 x i32> %vec31, <3 x i32> %vec32, i32 42, i1 true)
  store <8 x half> %0, ptr addrspace(10) @out, align 16, !tbaa !4
  call void @llvm.amdgcn.s.sema.signal(ptr addrspace(3) @sem2)
  ret void
}

define private amdgpu_kernel void @output(ptr addrspace(1) %inbuf, ptr addrspace(1) %wbuf, ptr addrspace(1) %outbuf) #0 #1 {
; CHECK-LABEL: output:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_load_b64 s[0:1], s[0:1], 0x10
; CHECK-NEXT:    v_mov_b32_e32 v0, 0
; CHECK-NEXT:    s_sema_wait 1
; CHECK-NEXT:    s_set_gpr_idx_u32 idx1, 0
; CHECK-NEXT:    s_wait_kmcnt 0x0
; CHECK-NEXT:    s_set_vgpr_frames 4 ; vsrc0_idx=0 vsrc1_idx=1 vsrc2_idx=0 vdst_idx=0 vsrc0_msb=0 vsrc1_msb=0 vsrc2_msb=0 vdst_msb=0
; CHECK-NEXT:    global_store_b128 v0, g1[28:31], s[0:1]
; CHECK-NEXT:    s_endpgm
entry:
  call void @llvm.amdgcn.s.sema.wait(ptr addrspace(3) @sem2)
  %0 = load <8 x half>, ptr addrspace(10) @out, align 16
  store <8 x half> %0, ptr addrspace(1) %outbuf, align 16
  ret void
}

; Function Attrs: convergent mustprogress nofree norecurse nosync nounwind memory(readwrite, argmem: none, inaccessiblemem: none)
define amdgpu_kernel void @main(ptr addrspace(1) %inbuf, ptr addrspace(1) %wbuf, ptr addrspace(1) %outbuf) #0 !reqd_work_group_size !{i32 32, i32 12, i32 1} {
; CHECK-LABEL: main:
; CHECK:       ; %bb.0: ; %entry
; CHECK-NEXT:    s_getreg_b32 s3, hwreg(HW_REG_WAVE_GROUP_INFO, 16, 4)
; CHECK-NEXT:    s_delay_alu instid0(SALU_CYCLE_1)
; CHECK-NEXT:    s_mul_i32 s4, s3, 0
; CHECK-NEXT:    s_mul_i32 s33, s3, s2
; CHECK-NEXT:    s_add_co_u32 s4, s4, 32
; CHECK-NEXT:    s_add_co_u32 s32, s33, 0
; CHECK-NEXT:    s_set_gpr_idx_u32 idx0, s4
; CHECK-NEXT:    ; sched_barrier mask(0x00000000)
; CHECK-NEXT:    s_getreg_b32 s3, hwreg(HW_REG_WAVE_GROUP_INFO, 16, 4)
; CHECK-NEXT:    s_set_gpr_idx_u32 idx0, 32
; CHECK-NEXT:    s_cmp_eq_u32 s3, 0
; CHECK-NEXT:    s_cbranch_scc0 .LBB3_2
; CHECK-NEXT:  ; %bb.1:
; CHECK-NEXT:    s_add_pc_i64 input@rel64-8
; CHECK-NEXT:  .LBB3_2: ; %entry
; CHECK-NEXT:    s_add_gpr_idx_u32 idx0, 18
; CHECK-NEXT:    s_cmp_eq_u32 s3, 1
; CHECK-NEXT:    s_cbranch_scc0 .LBB3_4
; CHECK-NEXT:  ; %bb.3:
; CHECK-NEXT:    s_add_pc_i64 compute@rel64-8
; CHECK-NEXT:  .LBB3_4: ; %entry
; CHECK-NEXT:    s_add_gpr_idx_u32 idx0, 0
; CHECK-NEXT:    s_cmp_eq_u32 s3, 2
; CHECK-NEXT:    s_cbranch_scc0 .LBB3_6
; CHECK-NEXT:  ; %bb.5:
; CHECK-NEXT:    s_add_pc_i64 output@rel64-8
; CHECK-NEXT:  .LBB3_6: ; %entry
; CHECK-NEXT:    s_add_gpr_idx_u32 idx0, 1
; CHECK-NEXT:    s_endpgm
entry:
  call void @llvm.amdgcn.wavegroup.rank(i32 0, ptr @input)
  call void @llvm.amdgcn.wavegroup.rank(i32 1, ptr @compute)
  call void @llvm.amdgcn.wavegroup.rank(i32 2, ptr @output)
  ret void
}

; Function Attrs: convergent nounwind
declare void @llvm.amdgcn.wavegroup.rank.p0(i32 immarg, ptr) #2

attributes #0 = { mustprogress nofree norecurse nosync nounwind willreturn memory(argmem: readwrite) "amdgpu-agpr-alloc"="0" "amdgpu-flat-work-group-size"="1,1024" "amdgpu-no-cluster-id-x" "amdgpu-no-cluster-id-y" "amdgpu-no-cluster-id-z" "amdgpu-no-completion-action" "amdgpu-no-default-queue" "amdgpu-no-dispatch-id" "amdgpu-no-dispatch-ptr" "amdgpu-no-flat-scratch-init" "amdgpu-no-heap-ptr" "amdgpu-no-hostcall-ptr" "amdgpu-no-implicitarg-ptr" "amdgpu-no-lds-kernel-id" "amdgpu-no-multigrid-sync-arg" "amdgpu-no-queue-ptr" "amdgpu-no-workgroup-id-x" "amdgpu-no-workgroup-id-y" "amdgpu-no-workgroup-id-z" "amdgpu-no-workitem-id-x" "amdgpu-no-workitem-id-y" "amdgpu-no-workitem-id-z" "amdgpu-wavegroup-enable" "amdgpu-waves-per-eu"="8,16" "no-trapping-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="gfx1300" "target-features"="+16-bit-insts,+ashr-pk-insts,+atomic-buffer-global-pk-add-f16-insts,+atomic-buffer-pk-add-bf16-inst,+atomic-ds-pk-add-16-insts,+atomic-fadd-rtn-insts,+atomic-flat-pk-add-16-insts,+atomic-global-pk-add-bf16-inst,+bf16-cvt-insts,+bf16-pk-insts,+bf16-trans-insts,+bitop3-insts,+ci-insts,+dl-insts,+dot7-insts,+dot8-insts,+dpp,+f16bf16-to-fp6bf6-cvt-scale-insts,+f32-to-f16bf16-cvt-sr-insts,+fp8-conversion-insts,+fp8e5m3-insts,+gfx10-3-insts,+gfx10-insts,+gfx11-insts,+gfx12-insts,+gfx1250-insts,+gfx1251-gemm-insts,+gfx13-insts,+gfx8-insts,+gfx9-insts,+parallel-bit-insts,+permlane16-swap,+prng-inst,+tanh-insts,+tensor-cvt-lut-insts,+transpose-load-f4f6-insts,+vmem-pref-insts,+wavefrontsize32" "uniform-work-group-size"="true" }
attributes #1 = { "amdgpu-wavegroup-rank-function" }
attributes #2 = { convergent nounwind }

; RANK:         .set main.private_seg_size, max(0, 0+max(.Linput.private_seg_size, .Lcompute.private_seg_size, .Loutput.private_seg_size))
; RANK:         .set main.num_vgpr_rank_sum, 0+.Linput.num_vgpr+.Lcompute.num_vgpr+.Loutput.num_vgpr
; RANK: ; NumVGPRsForWavesPerEU: 51

; Function Attrs: convergent mustprogress nocallback nofree nosync nounwind willreturn memory(none)
declare <8 x half> @llvm.amdgcn.convolve.f16.fp8.fp8.3x3.v8f16.v8f16.v9i32.v3i32(<8 x half>, <9 x i32>, <3 x i32>, <3 x i32>, <3 x i32>, i32 immarg, i1 immarg) #1

!4 = !{!5, !5, i64 0}
!5 = !{!"omnipotent char", !6, i64 0}
!6 = !{!"Simple C++ TBAA"}

;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; RANK: {{.*}}
